### ISSUE TITLE
Orient DB (3.2.21) is not running in Distributed mode

### ISSUE THREAD

**Issue by ChaitraSatish** [orientechnologies/orientdb#10035]
## Expected behavior  
We are running Orient db 3.2.21  in distributed mode ( 3 instances) all in different Linux servers.
There are several java applications (In production) which connects to this database and we expect DB ( all three instances) to be up and running without any downtime.

## Actual behavior  
When orient database is started, all three instances will be up and running for 10-15 mins, later two of the servers shutdown.

Below are  the error messages thrown by other two Orient db instances:
```
SEVER Exception in thread 'OrientDBEmbedded-3' [ScalingThreadPoolExecutor]
SEVER Exception in thread 'OrientDBEmbedded-1' [ScalingThreadPoolExecutor]
java.lang.NullPointerException
```
When trying to write to the database, below is the exception :
Suppressed: com.orientechnologies.orient.server.distributed.ODistributedException: Cannot set ownership of cluster 'reserve_2' to the server 'xxx', because the server has no that cluster (sharding).

Below are the configuration files:

1. orientdb-server-config.xml
```
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<orient-server>
<handlers>
<handler class="com.orientechnologies.orient.server.hazelcast.OHazelcastPlugin">
<parameters>
<parameter value="true" name="enabled"/>
<parameter value="${ORIENTDB_HOME}/config/default-distributed-db-config.json" name="configuration.db.default"/>
<parameter value="${ORIENTDB_HOME}/config/hazelcast.xml" name="configuration.hazelcast"/>
<parameter value="xxx" name="nodeName"/>
</parameters>
</handler>
```
2. default-distributed-db-config.json
```
{
  "autoDeploy": true,
  "hotAlignment": false,
  "readQuorum": 1,
  "writeQuorum": "majority",
  "executionMode": "undefined",
  "failureAvailableNodesLessQuorum": false,
  "readYourWrites": true,
  "newNodeStrategy": "dynamic",
  "servers": {
    "*": "master"
  },
  "clusters": {
    "internal": {
    },
    "*": {
      "servers": ["<NEW_NODE>"]
    }
  }
}
```
3. hazlecast.xml
```
<network>
<port auto-increment="true">2434</port>
<join>
<multicast enabled="false">
<multicast-group>235.1.1.1</multicast-group>
<multicast-port>2434</multicast-port>
</multicast>
<tcp-ip enabled="true">
<member>server1:2434</member>
<member>server2:2434</member>
<member>server3:2434</member>
</tcp-ip>
<kubernetes enabled="false">
<pod-label-name>orientdb-cluster-member</pod-label-name>
<pod-label-value>true</pod-label-value>
<service-port>2434</service-port>
</kubernetes>
</join>
</network>
```

This setup is in our Production environment. We seek your quick response/resolution.

**Comment by tglman** [comment]
Hi,

Do you have by chance the logs of the 3 servers? you should find them in the `log` folder of the distribution.

Regards

**Comment by ChaitraSatish** [comment]
Hi,

Please refer the below logs :

Server1.log
```
2023-11-12 16:05:44:481 INFO  {db=IEP} [] Reassigning ownership of clusters for database IEP... [OHazelcastPlugin]
2023-11-12 16:05:44:482 INFO  {db=IEP} [] Setting new distributed configuration for database: IEP (version=2139251)
 [ODistributedConfigurationManager]
2023-11-12 16:05:44:482 SEVER Exception in thread 'OrientDBEmbedded-2' [ScalingThreadPoolExecutor]
java.lang.NullPointerException

2023-11-12 16:05:44:483 INFO  {db=IEP} [] Broadcasting new distributed configuration for database: IEP (version=2139251)
 [OHazelcastClusterMetadataManager]
2023-11-12 16:05:44:487 INFO  {db=IEP} [] Reassigning ownership of clusters for database IEP... [OHazelcastPlugin]
2023-11-12 16:05:44:487 INFO  {db=IEP} [] Setting new distributed configuration for database: IEP (version=2139252)
 [ODistributedConfigurationManager]
2023-11-12 16:05:44:487 SEVER Exception in thread 'OrientDBEmbedded-4' [ScalingThreadPoolExecutor]
java.lang.NullPointerException

2023-11-12 16:05:44:487 INFO  {db=IEP} [] Broadcasting new distributed configuration for database: IEP (version=2139252)
 [OHazelcastClusterMetadataManager]
2023-11-12 16:05:44:491 INFO  {db=IEP} [] Reassigning ownership of clusters for database IEP... [OHazelcastPlugin]
2023-11-12 16:05:44:491 INFO  {db=IEP} [] Setting new distributed configuration for database: IEP (version=2139253)
 [ODistributedConfigurationManager]
2023-11-12 16:05:44:491 SEVER Exception in thread 'OrientDBEmbedded-3' [ScalingThreadPoolExecutor]
java.lang.NullPointerException

2023-11-12 16:05:44:491 INFO  {db=IEP} [] Broadcasting new distributed configuration for database: IEP (version=2139253)
 [OHazelcastClusterMetadataManager]
2023-11-12 16:05:44:502 INFO  {db=IEP} [] Reassigning ownership of clusters for database IEP... [OHazelcastPlugin]
2023-11-12 16:05:44:503 INFO  {db=IEP} [] Setting new distributed configuration for database: IEP (version=2139254)
 [ODistributedConfigurationManager]
2023-11-12 16:05:44:503 SEVER Exception in thread 'OrientDBEmbedded-1' [ScalingThreadPoolExecutor]
java.lang.NullPointerException

2023-11-12 16:05:44:503 INFO  {db=IEP} [] Broadcasting new distributed configuration for database: IEP (version=2139254)
 [OHazelcastClusterMetadataManager]
2023-11-12 16:05:44:505 INFO  {db=IEP} [] Reassigning ownership of clusters for database IEP... [OHazelcastPlugin]
2023-11-12 16:05:44:505 INFO  {db=IEP} [] Reassigning ownership of clusters for database IEP... [OHazelcastPlugin]
2023-11-12 16:05:44:505 INFO  {db=IEP} [] Setting new distributed configuration for database: IEP (version=2139255)
 [ODistributedConfigurationManager]
2023-11-12 16:05:44:505 SEVER Exception in thread 'OrientDBEmbedded-2' [ScalingThreadPoolExecutor]
java.lang.NullPointerException

2023-11-12 16:05:44:506 INFO  {db=IEP} [] Broadcasting new distributed configuration for database: IEP (version=2139255)
 [OHazelcastClusterMetadataManager]
2023-11-12 16:05:44:506 INFO  {db=IEP} [] Reassigning ownership of clusters for database IEP... [OHazelcastPlugin]
2023-11-12 16:05:44:507 INFO  {db=IEP} [] Reassigning ownership of clusters for database IEP... [OHazelcastPlugin]
2023-11-12 16:05:44:508 INFO  {db=IEP} [] Reassigning ownership of clusters for database IEP... [OHazelcastPlugin]
2023-11-12 16:05:44:510 INFO  {db=IEP} [] Reassigning ownership of clusters for database IEP... [OHazelcastPlugin]
2023-11-12 16:05:44:510 INFO  {db=IEP} [] Setting new distributed configuration for database: IEP (version=2139256)
 [ODistributedConfigurationManager]
2023-11-12 16:05:44:511 SEVER Exception in thread 'OrientDBEmbedded-4' [ScalingThreadPoolExecutor]
java.lang.NullPointerException
```
Server2.log
```
2023-11-10 18:13:30:573 SEVER Exception in thread 'OrientDBEmbedded-4' [ScalingThreadPoolExecutor]
com.orientechnologies.orient.core.exception.ODatabaseException: Cannot open database 'IEP'
	at com.orientechnologies.orient.core.db.OrientDBEmbedded.openNoAuthorization(OrientDBEmbedded.java:531)
	at com.orientechnologies.orient.core.db.OrientDBEmbedded.lambda$executeNoAuthorization$9(OrientDBEmbedded.java:1229)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
Caused by: com.orientechnologies.orient.core.exception.OStorageException: Error during fetching list of files
	at com.orientechnologies.orient.core.storage.disk.OLocalPaginatedStorage.exists(OLocalPaginatedStorage.java:840)
	at com.orientechnologies.orient.core.db.OrientDBEmbedded.getOrInitStorage(OrientDBEmbedded.java:662)
	at com.orientechnologies.orient.core.db.OrientDBEmbedded.getAndOpenStorage(OrientDBEmbedded.java:590)
	at com.orientechnologies.orient.core.db.OrientDBEmbedded.openNoAuthorization(OrientDBEmbedded.java:523)
	... 5 more
Caused by: java.nio.file.FileSystemException: /opt/orientdb/databases/IEP: Too many open files
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:91)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
	at sun.nio.fs.UnixFileSystemProvider.newDirectoryStream(UnixFileSystemProvider.java:427)
	at java.nio.file.Files.newDirectoryStream(Files.java:457)
	at com.orientechnologies.orient.core.storage.disk.OLocalPaginatedStorage.exists(OLocalPaginatedStorage.java:823)
	... 8 more

2023-11-10 18:13:30:574 INFO  [] Setting new distributed configuration for database: IEP (version=803347)
 [ODistributedConfigurationManager]
2023-11-10 18:13:30:575 SEVER Exception in thread 'OrientDBEmbedded-3' [ScalingThreadPoolExecutor]
com.orientechnologies.orient.core.exception.ODatabaseException: Cannot open database 'IEP'
	at com.orientechnologies.orient.core.db.OrientDBEmbedded.openNoAuthorization(OrientDBEmbedded.java:531)
	at com.orientechnologies.orient.core.db.OrientDBEmbedded.lambda$executeNoAuthorization$9(OrientDBEmbedded.java:1229)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
Caused by: com.orientechnologies.orient.core.exception.OStorageException: Error during fetching list of files
	at com.orientechnologies.orient.core.storage.disk.OLocalPaginatedStorage.exists(OLocalPaginatedStorage.java:840)
	at com.orientechnologies.orient.core.db.OrientDBEmbedded.getOrInitStorage(OrientDBEmbedded.java:662)
	at com.orientechnologies.orient.core.db.OrientDBEmbedded.getAndOpenStorage(OrientDBEmbedded.java:590)
	at com.orientechnologies.orient.core.db.OrientDBEmbedded.openNoAuthorization(OrientDBEmbedded.java:523)
	... 5 more
Caused by: java.nio.file.FileSystemException: /opt/orientdb/databases/IEP: Too many open files
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:91)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
	at sun.nio.fs.UnixFileSystemProvider.newDirectoryStream(UnixFileSystemProvider.java:427)
	at java.nio.file.Files.newDirectoryStream(Files.java:457)
	at com.orientechnologies.orient.core.storage.disk.OLocalPaginatedStorage.exists(OLocalPaginatedStorage.java:823)
	... 8 more

2023-11-10 18:13:30:576 INFO  [] Setting new distributed configuration for database: IEP (version=803348)
 [ODistributedConfigurationManager]
2023-11-10 18:13:30:576 SEVER Exception in thread 'OrientDBEmbedded-2' [ScalingThreadPoolExecutor]
com.orientechnologies.orient.core.exception.ODatabaseException: Cannot open database 'IEP'
	at com.orientechnologies.orient.core.db.OrientDBEmbedded.openNoAuthorization(OrientDBEmbedded.java:531)
	at com.orientechnologies.orient.core.db.OrientDBEmbedded.lambda$executeNoAuthorization$9(OrientDBEmbedded.java:1229)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
Caused by: com.orientechnologies.orient.core.exception.OStorageException: Error during fetching list of files
	at com.orientechnologies.orient.core.storage.disk.OLocalPaginatedStorage.exists(OLocalPaginatedStorage.java:840)
	at com.orientechnologies.orient.core.db.OrientDBEmbedded.getOrInitStorage(OrientDBEmbedded.java:662)
	at com.orientechnologies.orient.core.db.OrientDBEmbedded.getAndOpenStorage(OrientDBEmbedded.java:590)
	at com.orientechnologies.orient.core.db.OrientDBEmbedded.openNoAuthorization(OrientDBEmbedded.java:523)
	... 5 more
Caused by: java.nio.file.FileSystemException: /opt/orientdb/databases/IEP: Too many open files
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:91)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
	at sun.nio.fs.UnixFileSystemProvider.newDirectoryStream(UnixFileSystemProvider.java:427)
	at java.nio.file.Files.newDirectoryStream(Files.java:457)
	at com.orientechnologies.orient.core.storage.disk.OLocalPaginatedStorage.exists(OLocalPaginatedStorage.java:823)
	... 8 more
```
Server3.log:
```
2023-11-12 14:47:43:490 SEVER Exception in thread 'OrientDBEmbedded-2' [ScalingThreadPoolExecutor]
java.lang.NullPointerException

2023-11-12 14:47:43:491 INFO  [] Setting new distributed configuration for database: IEP (version=2100566)
 [ODistributedConfigurationManager]
2023-11-12 14:47:43:492 SEVER Exception in thread 'OrientDBEmbedded-3' [ScalingThreadPoolExecutor]
java.lang.NullPointerException

2023-11-12 14:47:43:501 INFO  [] Setting new distributed configuration for database: IEP (version=2100567)
 [ODistributedConfigurationManager]
2023-11-12 14:47:43:501 SEVER Exception in thread 'OrientDBEmbedded-4' [ScalingThreadPoolExecutor]
java.lang.NullPointerException

2023-11-12 14:47:43:502 INFO  [] Setting new distributed configuration for database: IEP (version=2100568)
 [ODistributedConfigurationManager]
2023-11-12 14:47:43:502 SEVER Exception in thread 'OrientDBEmbedded-1' [ScalingThreadPoolExecutor]
java.lang.NullPointerException

2023-11-12 14:47:43:522 INFO  [] Setting new distributed configuration for database: IEP (version=2100569)
 [ODistributedConfigurationManager]
2023-11-12 14:47:43:522 SEVER Exception in thread 'OrientDBEmbedded-2' [ScalingThreadPoolExecutor]
java.lang.NullPointerException

2023-11-12 14:47:43:524 INFO  [] Setting new distributed configuration for database: IEP (version=2100570)
 [ODistributedConfigurationManager]
2023-11-12 14:47:43:524 SEVER Exception in thread 'OrientDBEmbedded-3' [ScalingThreadPoolExecutor]
java.lang.NullPointerException

2023-11-12 14:47:43:527 INFO  [] Setting new distributed configuration for database: IEP (version=2100571)
 [ODistributedConfigurationManager]
2023-11-12 14:47:43:527 SEVER Exception in thread 'OrientDBEmbedded-4' [ScalingThreadPoolExecutor]
java.lang.NullPointerException

2023-11-12 14:47:43:529 INFO  [] Setting new distributed configuration for database: IEP (version=2100572)
 [ODistributedConfigurationManager]
2023-11-12 14:47:43:529 SEVER Exception in thread 'OrientDBEmbedded-1' [ScalingThreadPoolExecutor]
java.lang.NullPointerException

2023-11-12 14:47:43:531 INFO  [] Setting new distributed configuration for database: IEP (version=2100573)
 [ODistributedConfigurationManager]
2023-11-12 14:47:43:531 SEVER Exception in thread 'OrientDBEmbedded-2' [ScalingThreadPoolExecutor]
java.lang.NullPointerException

2023-11-12 14:47:43:540 INFO  [] Setting new distributed configuration for database: IEP (version=2100574)
 [ODistributedConfigurationManager]
2023-11-12 14:47:43:540 SEVER Exception in thread 'OrientDBEmbedded-3' [ScalingThreadPoolExecutor]
java.lang.NullPointerException

2023-11-12 14:47:43:545 INFO  [] Setting new distributed configuration for database: IEP (version=2100575)
 [ODistributedConfigurationManager]
2023-11-12 14:47:43:545 SEVER Exception in thread 'OrientDBEmbedded-4' [ScalingThreadPoolExecutor]
java.lang.NullPointerException

2023-11-12 14:47:43:561 INFO  [] Setting new distributed configuration for database: IEP (version=2100576)
 [ODistributedConfigurationManager]
2023-11-12 14:47:43:561 SEVER Exception in thread 'OrientDBEmbedded-1' [ScalingThreadPoolExecutor]
java.lang.NullPointerException
```

**Comment by ChaitraSatish** [comment]
Hi Team, 

Logs have been attached in the previous comment.
Please provide feedback.

**Comment by ChaitraSatish** [comment]
Hi Team,

We are unable to step in to production  due to this issue.
Kindly help us to resolve this as early as possible.

**Comment by lvca** [comment]
I see this exception that is likely related to the OS settings about how many open files can have a process:

```
Caused by: java.nio.file.FileSystemException: /opt/orientdb/databases/IEP: Too many open files
```

Check this out: https://www.tecmint.com/increase-set-open-file-limits-in-linux/

**Comment by ChaitraSatish** [comment]
@lvca Thanks for the suggestion. We followed the link and updated the following in cat /proc/35527/limits:

Limit                     Soft Limit           Hard Limit           Units
Max cpu time              unlimited            unlimited            seconds
Max file size             unlimited            unlimited            bytes
Max data size             unlimited            unlimited            bytes
Max stack size            8388608              unlimited            bytes
Max core file size        0                    unlimited            bytes
Max resident set          unlimited            unlimited            bytes
Max processes             513699               513699               processes
Max open files            65536                65536                files
Max locked memory         65536                65536                bytes

Following is the error got while running database:

+-------------+------+--------------------------+-----+---------+-----------------+-----------------+------------------------+
|Name         |Status|Databases                 |Conns|StartedOn|Binary           |HTTP             |UsedMemory              |
+-------------+------+--------------------------+-----+---------+-----------------+-----------------+------------------------+
|server3(*)|ONLINE|IEP=NOT_AVAILABLE (MASTER)|5    |11:45:39 |x.x.x.x:2424|x.x.x.x:2480|1.14GB/14.22GB (7.99%)  |
|             |      |demodb=ONLINE (MASTER)    |     |         |                 |                 |                        |
|server2|ONLINE|IEP=NOT_AVAILABLE (MASTER)|4    |11:41:40 |x.x.x.x:2424|x.x.x.x:2480|1.79GB/14.22GB (12.60%) |
|             |      |demodb=ONLINE (MASTER)    |     |         |                 |                 |                        |
|server1|ONLINE|IEP=ONLINE (MASTER)       |8    |11:40:23 |x.x.x.x:2424|x.x.x.x:2480|714.48MB/14.22GB (4.91%)|
|             |      |demodb=ONLINE (MASTER)    |     |         |                 |                 |                        |
+-------------+------+--------------------------+-----+---------+-----------------+-----------------+------------------------+
[OHazelcastPlugin]
2023-11-23 11:46:07:505 INFO  [server3] Trying to recover current server for database 'IEP'... [OClusterHealthChecker]
2023-11-23 11:46:07:509 SEVER [server3] Cannot install database 'IEP' on local node, because no servers are available [OHazelcastPlugin]
2023-11-23 11:46:07:510 INFO  [server3] Recover cannot be completed for database 'IEP' [OClusterHealthChecker]


Please provide your feedback on this.

**Comment by ChaitraSatish** [comment]
Hi Team,

Awaiting for your feedback.

**Comment by ChaitraSatish** [comment]
Hi Team,
After updating the limit for OS related files, the database is running in all three instances.

Thanks for the suggestion. Closing this ticket.
