### ISSUE TITLE
The database instance is not set in the current thread. Be sure to set it with: ODatabaseRecordThreadLocal.instance().set(db);

### ISSUE THREAD

**Issue by jamieb22** [orientechnologies/orientdb#10090]
## Expected behavior  
 No error

## Actual behavior  

2024-02-06 12:59:30:954 SEVER Error reading request [ONetworkProtocolBinary]
com.orientechnologies.orient.core.exception.OSerializationException: Error on unmarshalling content. Class: q
        at com.orientechnologies.orient.core.serialization.serializer.stream.OStreamSerializerAnyStreamable.fromStream(OStreamSerializerAnyStreamable.java:92)
        at com.orientechnologies.orient.client.remote.message.OCommandRequest.read(OCommandRequest.java:70)
        at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.sessionRequest(ONetworkProtocolBinary.java:319)
        at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.execute(ONetworkProtocolBinary.java:239)
        at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:67)
Caused by: com.orientechnologies.orient.core.exception.ODatabaseException: The database instance is not set in the current thread. Be sure to set it with: ODatabaseRecordThreadLocal.instance().set(db);
        at com.orientechnologies.orient.core.db.ODatabaseRecordThreadLocal.get(ODatabaseRecordThreadLocal.java:61)
        at com.orientechnologies.orient.core.sql.query.OSQLQuery.deserializeQueryParameters(OSQLQuery.java:147)
        at com.orientechnologies.orient.core.sql.query.OSQLQuery.queryFromStream(OSQLQuery.java:137)
        at com.orientechnologies.orient.core.sql.query.OSQLSynchQuery.queryFromStream(OSQLSynchQuery.java:147)
        at com.orientechnologies.orient.core.sql.query.OSQLQuery.fromStream(OSQLQuery.java:109)
        at com.orientechnologies.orient.core.serialization.serializer.stream.OStreamSerializerAnyStreamable.fromStream(OStreamSerializerAnyStreamable.java:86)
        ... 4 more

## Steps to reproduce  

The server just runs for a while, and then outputs the above message continually. Over and over.

**Comment by jamieb22** [comment]
Could you please update the error to include database name. For example:
`The database **XYZ** instance is not set in the current thread. Be sure to set it with: `
So its at least possible determine which database is running into problems.

**Comment by jamieb22** [comment]
Andrey... is this error generated by the server? Its not ommunicated from the client? It sppears this error is serious as once it occurs, my Orient DB keeps outputting the error indefinitely and the server eventually stops processing further requirests. Is there a workaround to this issue? Perhaps, an OrientDB setting that could help in the interim. Thank you.

**Comment by jamieb22** [comment]
Apologies. This is our issue,  Our modern code is using Kotlin co-routines and Orient DB thread locale is not set unless we set the Orient DB thread locale variable on co-routine ContextElement.

```
withContext(
        ODatabaseRecordThreadLocal.instance()
            .asContextElement(value = application.database.graphFactory().tx.rawGraph)
    ) {
.... orient DB call
}
```
