### ISSUE TITLE
The database instance is not set in the current thread. Be sure to set it with: ODatabaseRecordThreadLocal.instance().set(db);

### ISSUE THREAD

**Issue by jamieb22** [orientechnologies/orientdb#10110]
## Expected behavior  

We are using the recommended transaction pattern (see below) through out our application orient DB client code, and yet the Orient DB server is returning an error "The database instance is not set in the current thread. ". 
```
    OrientGraphFactory factory = new OrientGraphFactory("remote:127.0.0.1/db").setupPool(1,10);
    OrientGraph graph = factory.getTx();
    try {
      ...
    } finally {
       graph.shutdown();
    }
```
The client code is connecting to an Orient DB server running 3.2.26. 

## Actual behavior  

The error outtputted is "The database instance is not set in the current thread. Be sure to set it with: ODatabaseRecordThreadLocal.instance().set(db);" yet we are using using transactions described at https://orientdb.com/docs/2.2.x/Graph-Database-Tinkerpop.html

```
2024-02-08 14:01:58:480 SEVER Error on unmarshalling content. Class: q [OStreamSerializerAnyStreamable]
com.orientechnologies.orient.core.exception.ODatabaseException: The database instance is not set in the current thread. Be sure to set it with: ODatabaseRecordThreadLocal.instance().set(db);
	at com.orientechnologies.orient.core.db.ODatabaseRecordThreadLocal.get(ODatabaseRecordThreadLocal.java:61)
	at com.orientechnologies.orient.core.sql.query.OSQLQuery.deserializeQueryParameters(OSQLQuery.java:147)
	at com.orientechnologies.orient.core.sql.query.OSQLQuery.queryFromStream(OSQLQuery.java:137)
	at com.orientechnologies.orient.core.sql.query.OSQLSynchQuery.queryFromStream(OSQLSynchQuery.java:147)
	at com.orientechnologies.orient.core.sql.query.OSQLQuery.fromStream(OSQLQuery.java:109)
	at com.orientechnologies.orient.core.serialization.serializer.stream.OStreamSerializerAnyStreamable.fromStream(OStreamSerializerAnyStreamable.java:86)
	at com.orientechnologies.orient.client.remote.message.OCommandRequest.read(OCommandRequest.java:70)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.sessionRequest(ONetworkProtocolBinary.java:318)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.execute(ONetworkProtocolBinary.java:238)
	at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:68)

2024-02-08 14:01:58:480 SEVER Error reading request [ONetworkProtocolBinary]
com.orientechnologies.orient.core.exception.OSerializationException: Error on unmarshalling content. Class: q
	at com.orientechnologies.orient.core.serialization.serializer.stream.OStreamSerializerAnyStreamable.fromStream(OStreamSerializerAnyStreamable.java:92)
	at com.orientechnologies.orient.client.remote.message.OCommandRequest.read(OCommandRequest.java:70)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.sessionRequest(ONetworkProtocolBinary.java:318)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.execute(ONetworkProtocolBinary.java:238)
	at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:68)
Caused by: com.orientechnologies.orient.core.exception.ODatabaseException: The database instance is not set in the current thread. Be sure to set it with: ODatabaseRecordThreadLocal.instance().set(db);
	at com.orientechnologies.orient.core.db.ODatabaseRecordThreadLocal.get(ODatabaseRecordThreadLocal.java:61)
	at com.orientechnologies.orient.core.sql.query.OSQLQuery.deserializeQueryParameters(OSQLQuery.java:147)
	at com.orientechnologies.orient.core.sql.query.OSQLQuery.queryFromStream(OSQLQuery.java:137)
	at com.orientechnologies.orient.core.sql.query.OSQLSynchQuery.queryFromStream(OSQLSynchQuery.java:147)
	at com.orientechnologies.orient.core.sql.query.OSQLQuery.fromStream(OSQLQuery.java:109)
	at com.orientechnologies.orient.core.serialization.serializer.stream.OStreamSerializerAnyStreamable.fromStream(OStreamSerializerAnyStreamable.java:86
```

## Steps to reproduce  
<add here>  
<An SQL script to reproduce the problem or a JUnit test case will increase **A LOT** the chance to have a quick fix>

**Comment by jamieb22** [comment]
Duplicate of https://github.com/orientechnologies/orientdb/issues/10090
