### ISSUE TITLE
Fail to save 2 new records of the same class on OrientDB embedded mode

### ISSUE THREAD

**Issue by cuongrep** [orientechnologies/orientdb#10184]
## Expected behavior  
I have used OrientDb embedded mode.
I tried to save 2 records of the same class (with iForceCreate is true) using only one ODatabaseDocumentTx.
I hope that it will be stored in Database.

## Actual behavior  
The console report the exception:
```bash
Caused by: com.orientechnologies.orient.core.exception.OConcurrentModificationException: Cannot UPDATE the record #164:0 because the version is not the latest. Probably you are updating an old record or it has been modified by another user (db=v1 your=v0)
	DB name="vertexDb"
	Error Code="3"
	at com.orientechnologies.orient.core.conflict.OVersionRecordConflictStrategy.checkVersions(OVersionRecordConflictStrategy.java:61)
	at com.orientechnologies.orient.core.conflict.OVersionRecordConflictStrategy.onUpdate(OVersionRecordConflictStrategy.java:47)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.checkAndIncrementVersion(OAbstractPaginatedStorage.java:5721)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.doUpdateRecord(OAbstractPaginatedStorage.java:5176)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.commitEntry(OAbstractPaginatedStorage.java:5820)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.commit(OAbstractPaginatedStorage.java:2517)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.commit(OAbstractPaginatedStorage.java:2342)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentEmbedded.internalCommit(ODatabaseDocumentEmbedded.java:1951)
	at com.orientechnologies.orient.core.tx.OTransactionOptimistic.doCommit(OTransactionOptimistic.java:623)
	at com.orientechnologies.orient.core.tx.OTransactionOptimistic.commit(OTransactionOptimistic.java:116)
```

## Steps to reproduce  
- using OrientDb embedded mode.
- try to save 2 records of the same class (with iForceCreate is true) using only one ODatabaseDocumentTx.

**Comment by andrii0lomakin** [comment]
Hi @cuongrep , 
This exception shows that the version of the record that you loaded is older than the one stored in a database. As for now, I do not see why you treat such behavior as buggy.
Could you write a snippet of the code you used?

**Comment by cuongrep** [comment]
Hi @laa,
Thank you for your reply.
As of now, I had an issue when preparing a snippet of the code I used, therefore I can't provide it right now.
Meanwhile, I can brief my current situation as below:
- I have used OrientDb v3.2.24 embedded mode in a private project based on Play Framework
- I tried to create a new record by using save method as code below:
                `dbConnection.save(oModel.fromJSON(oModelJson), ODatabase.OPERATION_MODE.SYNCHRONOUS, true, // force create
                        null, null);`
in which dbConnection is an instance of ODatabaseDocumentTx
- I have faced an issue as below:
`com.xxxx.db.exception.DbConcurrentModificationException: Cannot UPDATE the record #166:0 because the version is not the latest. Probably you are updating an old record or it has been modified by another user (db=v1 your=v0)`
- When I checked database on the OrientDb studio by copying the database and paste it into an OrientDb database folder, I saw the record was stored in the database, but I have no idea why the version is 3?
**1. Do you have any idea why I got the situation?**
p/s: When I run the same function on OrientDB v3.2.24 remote mode, everything works fine.
It is weird
**2. I wonder whether OrientDb works different between 2 modes?**
**3. I wonder whether OrientDb embedded mode just temporary stores data on memory before committing data on disk? Could you please let me know if I'm incorrect here?**

**Comment by andrii0lomakin** [comment]
Hi @cuongrep 
The methods you use are internal ones.
You should not force the database to do something.
Also, if you use a deprecated class, please access the database over the OrientDB root instance.

**Comment by cuongrep** [comment]
Hi @laa,
It seems we found a solution.
For OrientDb embedded mode,
We need to empty the Local cache every time we invoke save to create (iForceCreate = true) a new record using the db.getLocalCache().invalidate(); command. By this approach, we ensure that the next time we invoke save within the same databaseConnection, no previous data be tried to save again.

Anyway, thank you for your reply.

**Comment by tglman** [comment]
Hi, 

If you needed to clear the local cache is because you were reusing ODocument/OElement instances across iterations, the correct way is to have an instance of ODocument/OElement for each logic record you have,as well  as stated before do not use ODatabaseDocumentTX, will be removed in next version, just use ODatabaseSession with the public APIs it provides
