### ISSUE TITLE
Is OrientDB version 1.0.1 supports java 11?

### ISSUE THREAD

**Issue by Thejas-Jain-M-J** [orientechnologies/orientdb#10221]
## Actual behavior  
Apr 23, 2024 10:51:24 AM com.orientechnologies.common.log.OLogManager log
SEVERE: Error on loading index by configuration: {type:DICTIONARY,name:dictionary,clusters:[0],mapRid:#1:83}
java.lang.IllegalArgumentException: com.orientechnologies.orient.core.index.OIndexFactory is not an ImageIO SPI class
        at java.desktop/javax.imageio.spi.ServiceRegistry.checkClassAllowed(Unknown Source)
        at java.desktop/javax.imageio.spi.ServiceRegistry.lookupProviders(Unknown Source)
        at com.orientechnologies.common.util.OClassLoaderHelper.lookupProviderWithOrientClassLoader(OClassLoaderHelper.java:25)
        at com.orientechnologies.orient.core.index.OIndexes.getFactories(OIndexes.java:71)
        at com.orientechnologies.orient.core.index.OIndexes.getAllFactories(OIndexes.java:86)
        at com.orientechnologies.orient.core.index.OIndexes.createIndex(OIndexes.java:116)
        at com.orientechnologies.orient.core.index.OIndexManagerShared.fromStream(OIndexManagerShared.java:144)
        at com.orientechnologies.orient.core.type.ODocumentWrapperNoClass.reload(ODocumentWrapperNoClass.java:68)
        at com.orientechnologies.orient.core.index.OIndexManagerAbstract.load(OIndexManagerAbstract.java:99)
        at com.orientechnologies.orient.core.index.OIndexManagerAbstract.load(OIndexManagerAbstract.java:52)
        at com.orientechnologies.orient.core.metadata.OMetadata$1.call(OMetadata.java:106)
        at com.orientechnologies.orient.core.metadata.OMetadata$1.call(OMetadata.java:97)
        at com.orientechnologies.common.concur.resource.OSharedContainerImpl.getResource(OSharedContainerImpl.java:53)
        at com.orientechnologies.orient.core.metadata.OMetadata.init(OMetadata.java:96)
        at com.orientechnologies.orient.core.metadata.OMetadata.load(OMetadata.java:53)
        at com.orientechnologies.orient.core.db.record.ODatabaseRecordAbstract.open(ODatabaseRecordAbstract.java:110)
        at com.orientechnologies.orient.core.db.ODatabaseWrapperAbstract.open(ODatabaseWrapperAbstract.java:47)
        at com.orientechnologies.orient.core.db.ODatabaseWrapperAbstract.open(ODatabaseWrapperAbstract.java:47)
        at com.accurev.accusync.storage.service.StorageService.openDb(StorageService.java:136)
        at com.accurev.accusync.storage.service.StorageService.testOpen(StorageService.java:617)
        at com.accurev.accusync.storage.service.StorageService.upgradeClasses(StorageService.java:701)
        at com.accurev.accusync.core.launcher.DefaultLauncher.upgrade(DefaultLauncher.java:239)
        at com.accurev.accusync.core.launcher.DefaultLauncher.startServices(DefaultLauncher.java:288)
        at com.accurev.accusync.core.launcher.DefaultLauncher.run(DefaultLauncher.java:135)

## Steps to reproduce  
I am trying to run my application with java 11.There i am using orient DB version 1.0.1. With java 8 it was working fine. But with java 11 it is failing. Is this versions is n ot compatible with java 11?

**Comment by tglman** [comment]
OrientDB 1.x is long out of support, so not sure if is supported and if is not will never be.

Regards
