### ISSUE TITLE
Search for log files in a more clever way to avoid IOException [moved]

### ISSUE THREAD

**Issue by lvca** [orientechnologies/orientdb#1022]
This is [Issue 1022](http://code.google.com/p/orient/issues/detail?id=1022) moved from a Google Code project.
Added by 2012-08-16T16:33:41.000Z by [gabipetr...@gmail.com](http://code.google.com/u/115643217538536659046/).
Please review that bug for more context and additional comments, but update this bug.

Original labels: Type-Defect, Priority-Medium, Release

### Original description

    In 1.1.0.
    
    If I try to start the server.sh from another place other than orientdb/bin I get the following exception:
    
    java.io.IOException: Couldn't get lock for ../log/orient-server.log
    java.io.IOException: Couldn't get lock for ../log/orient-server.log
    	at java.util.logging.FileHandler.openFiles(FileHandler.java:372)
    	at java.util.logging.FileHandler.<init>(FileHandler.java:208)
    	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:39)
    	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:27)
    	at java.lang.reflect.Constructor.newInstance(Constructor.java:513)
    	at java.lang.Class.newInstance0(Class.java:355)
    	at java.lang.Class.newInstance(Class.java:308)
    	at java.util.logging.LogManager$3.run(LogManager.java:359)
    	at java.security.AccessController.doPrivileged(Native Method)
    	at java.util.logging.LogManager.loadLoggerHandlers(LogManager.java:345)
    	at java.util.logging.LogManager.initializeGlobalHandlers(LogManager.java:1032)
    	at java.util.logging.LogManager.access$1100(LogManager.java:129)
    	at java.util.logging.LogManager$RootLogger.getHandlers(LogManager.java:1113)
    	at com.orientechnologies.common.log.OLogManager.installCustomFormatter(OLogManager.java:268)
    	at com.orientechnologies.orient.server.OServer.<init>(OServer.java:101)
    	at com.orientechnologies.orient.server.OServerMain.create(OServerMain.java:22)
    	at com.orientechnologies.orient.server.OServerMain.main(OServerMain.java:31)
    
    
    ../log/orient-server.log should be relative to the orient bin directory not to CWD.

**Comment by lvca** [comment]
This has been fixed long time ago.
