### ISSUE TITLE
Index breaks after upgrade migration

### ISSUE THREAD

**Issue by ishvo** [orientechnologies/orientdb#10367]
## Expected behavior  
Rebuilding an index does not break the database

## Actual behavior  
When causing a rebuild after the import it break the database, making it impossible to log in over console or over the java library.

## Steps to reproduce  
Export a database which have a class with an index created using: "CREATE INDEX Idx ON Example (id) NOTUNIQUE METADATA {ignoreNullValues: true}" on orientdb 2.2.37 (ran directly on the host) and export using the console.
Import into orientdb3.2.36 (dockerized). 
Log into the web interface and rebuild the index.
I could not fix the broken database.

Edit: I did not encounter this issue on "UNIQUE" indices.

## Workaround
After importing the database, drop the index and create it again. 
The old index had "SBTREE" engine and the new one has "CELL_BTREE" to which I can't seem to find documentation.
This is only possible if the database is not broken yet.

**Comment by tglman** [comment]
Hi,

Thanks to report this, we will double check, do you have by any chances logs/stack traces related to this problem, it may speed up the resolution.

Regards

**Comment by ishvo** [comment]
Yes.

This is a breaking NOTUNIQUE index rebuild (it loops somewhere so I cut it at some point):
```
2024-12-13 10:08:22 2024-12-13 09:08:22:059 SEVER Exception `15B56D77` in storage `plocal:/orientdb/databases/db`: 3.2.36 (build ${buildNumber}, branch UNKNOWN) [OLocalPaginatedStorage]
2024-12-13 10:08:22 com.orientechnologies.orient.core.storage.index.sbtree.local.v1.OSBTreeException: Null keys are not supported.      DB name="db"     Component Name="IdxContractClaimed"
2024-12-13 10:08:22     at com.orientechnologies.orient.core.storage.index.sbtree.local.v1.OSBTreeV1.checkNullSupport(OSBTreeV1.java:810)
2024-12-13 10:08:22     at com.orientechnologies.orient.core.storage.index.sbtree.local.v1.OSBTreeV1.get(OSBTreeV1.java:189)
2024-12-13 10:08:22     at com.orientechnologies.orient.core.storage.index.engine.OSBTreeIndexEngine.get(OSBTreeIndexEngine.java:202)
2024-12-13 10:08:22     at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.doGetIndexValue(OAbstractPaginatedStorage.java:3079)
2024-12-13 10:08:22     at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.getIndexValue(OAbstractPaginatedStorage.java:3054)
2024-12-13 10:08:22     at com.orientechnologies.orient.core.index.OIndexMultiValues.getRidsIgnoreTx(OIndexMultiValues.java:91)
2024-12-13 10:08:22     at com.orientechnologies.orient.core.index.OIndexMultiValues.getRids(OIndexMultiValues.java:120)
2024-12-13 10:08:22     at com.orientechnologies.orient.core.index.OIndexAbstract.doDelete(OIndexAbstract.java:661)
2024-12-13 10:08:22     at com.orientechnologies.orient.core.index.OIndexAbstract.rebuild(OIndexAbstract.java:473)
2024-12-13 10:08:22     at com.orientechnologies.orient.core.index.OIndexAbstract.rebuild(OIndexAbstract.java:338)
2024-12-13 10:08:22     at com.orientechnologies.orient.core.sql.parser.ORebuildIndexStatement.executeSimple(ORebuildIndexStatement.java:51)
2024-12-13 10:08:22     at com.orientechnologies.orient.core.sql.executor.OSingleOpExecutionPlan.executeInternal(OSingleOpExecutionPlan.java:63)
2024-12-13 10:08:22     at com.orientechnologies.orient.core.sql.parser.OSimpleExecStatement.execute(OSimpleExecStatement.java:45)
2024-12-13 10:08:22     at com.orientechnologies.orient.core.sql.parser.OStatement.execute(OStatement.java:76)
2024-12-13 10:08:22     at com.orientechnologies.orient.core.db.document.ODatabaseDocumentEmbedded.command(ODatabaseDocumentEmbedded.java:634)
2024-12-13 10:08:22     at com.orientechnologies.orient.server.network.protocol.http.command.post.OServerCommandPostCommand.executeStatement(OServerCommandPostCommand.java:221)
2024-12-13 10:08:22     at com.orientechnologies.orient.server.network.protocol.http.command.post.OServerCommandPostCommand.execute(OServerCommandPostCommand.java:104)
2024-12-13 10:08:22     at com.orientechnologies.orient.server.network.protocol.http.command.post.OServerCommandPostCommandGraph.execute(OServerCommandPostCommandGraph.java:34)
2024-12-13 10:08:22     at com.orientechnologies.orient.server.network.protocol.http.ONetworkProtocolHttpAbstract.service(ONetworkProtocolHttpAbstract.java:242)
2024-12-13 10:08:22     at com.orientechnologies.orient.server.network.protocol.http.ONetworkProtocolHttpAbstract.execute(ONetworkProtocolHttpAbstract.java:800)
2024-12-13 10:08:22     at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:68)
2024-12-13 10:08:22 
2024-12-13 10:08:22 2024-12-13 09:08:22:059 SEVER {db=db} Error Dropping Index IdxContractClaimed [OIndexNotUnique]
2024-12-13 10:08:22 com.orientechnologies.orient.core.storage.index.sbtree.local.v1.OSBTreeException: Null keys are not supported.      DB name="db"     Component Name="IdxContractClaimed"
2024-12-13 10:08:22     at com.orientechnologies.orient.core.storage.index.sbtree.local.v1.OSBTreeV1.checkNullSupport(OSBTreeV1.java:810)
2024-12-13 10:08:22     at com.orientechnologies.orient.core.storage.index.sbtree.local.v1.OSBTreeV1.get(OSBTreeV1.java:189)
2024-12-13 10:08:22     at com.orientechnologies.orient.core.storage.index.engine.OSBTreeIndexEngine.get(OSBTreeIndexEngine.java:202)
2024-12-13 10:08:22     at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.doGetIndexValue(OAbstractPaginatedStorage.java:3079)
2024-12-13 10:08:22     at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.getIndexValue(OAbstractPaginatedStorage.java:3054)
2024-12-13 10:08:22     at com.orientechnologies.orient.core.index.OIndexMultiValues.getRidsIgnoreTx(OIndexMultiValues.java:91)
2024-12-13 10:08:22     at com.orientechnologies.orient.core.index.OIndexMultiValues.getRids(OIndexMultiValues.java:120)
2024-12-13 10:08:22     at com.orientechnologies.orient.core.index.OIndexAbstract.doDelete(OIndexAbstract.java:661)
2024-12-13 10:08:22     at com.orientechnologies.orient.core.index.OIndexAbstract.rebuild(OIndexAbstract.java:473)
2024-12-13 10:08:22     at com.orientechnologies.orient.core.index.OIndexAbstract.rebuild(OIndexAbstract.java:338)
2024-12-13 10:08:22     at com.orientechnologies.orient.core.sql.parser.ORebuildIndexStatement.executeSimple(ORebuildIndexStatement.java:51)
2024-12-13 10:08:22     at com.orientechnologies.orient.core.sql.executor.OSingleOpExecutionPlan.executeInternal(OSingleOpExecutionPlan.java:63)
2024-12-13 10:08:22     at com.orientechnologies.orient.core.sql.parser.OSimpleExecStatement.execute(OSimpleExecStatement.java:45)
2024-12-13 10:08:22     at com.orientechnologies.orient.core.sql.parser.OStatement.execute(OStatement.java:76)
2024-12-13 10:08:22     at com.orientechnologies.orient.core.db.document.ODatabaseDocumentEmbedded.command(ODatabaseDocumentEmbedded.java:634)
2024-12-13 10:08:22     at com.orientechnologies.orient.server.network.protocol.http.command.post.OServerCommandPostCommand.executeStatement(OServerCommandPostCommand.java:221)
2024-12-13 10:08:22     at com.orientechnologies.orient.server.network.protocol.http.command.post.OServerCommandPostCommand.execute(OServerCommandPostCommand.java:104)
2024-12-13 10:08:22     at com.orientechnologies.orient.server.network.protocol.http.command.post.OServerCommandPostCommandGraph.execute(OServerCommandPostCommandGraph.java:34)
2024-12-13 10:08:22     at com.orientechnologies.orient.server.network.protocol.http.ONetworkProtocolHttpAbstract.service(ONetworkProtocolHttpAbstract.java:242)
2024-12-13 10:08:22     at com.orientechnologies.orient.server.network.protocol.http.ONetworkProtocolHttpAbstract.execute(ONetworkProtocolHttpAbstract.java:800)
2024-12-13 10:08:22     at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:68)
2024-12-13 10:08:22 
2024-12-13 10:08:22 2024-12-13 09:08:22:068 SEVER Exception `6336CD9A` in storage `plocal:/orientdb/databases/db`: 3.2.36 (build ${buildNumber}, branch UNKNOWN) [OLocalPaginatedStorage]
2024-12-13 10:08:22 com.orientechnologies.orient.core.exception.OStorageException: Exception during execution of atomic operation inside of storage db   DB name="db"
2024-12-13 10:08:22     at com.orientechnologies.orient.core.storage.impl.local.paginated.atomicoperations.OAtomicOperationsManager.calculateInsideAtomicOperation(OAtomicOperationsManager.java:128)
2024-12-13 10:08:22     at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.addIndexEngine(OAbstractPaginatedStorage.java:2724)
2024-12-13 10:08:22     at com.orientechnologies.orient.core.index.OIndexAbstract.rebuild(OIndexAbstract.java:487)
2024-12-13 10:08:22     at com.orientechnologies.orient.core.index.OIndexAbstract.rebuild(OIndexAbstract.java:338)
2024-12-13 10:08:22     at com.orientechnologies.orient.core.sql.parser.ORebuildIndexStatement.executeSimple(ORebuildIndexStatement.java:51)
2024-12-13 10:08:22     at com.orientechnologies.orient.core.sql.executor.OSingleOpExecutionPlan.executeInternal(OSingleOpExecutionPlan.java:63)
2024-12-13 10:08:22     at com.orientechnologies.orient.core.sql.parser.OSimpleExecStatement.execute(OSimpleExecStatement.java:45)
2024-12-13 10:08:22     at com.orientechnologies.orient.core.sql.parser.OStatement.execute(OStatement.java:76)
2024-12-13 10:08:22     at com.orientechnologies.orient.core.db.document.ODatabaseDocumentEmbedded.command(ODatabaseDocumentEmbedded.java:634)
2024-12-13 10:08:22     at com.orientechnologies.orient.server.network.protocol.http.command.post.OServerCommandPostCommand.executeStatement(OServerCommandPostCommand.java:221)
2024-12-13 10:08:22     at com.orientechnologies.orient.server.network.protocol.http.command.post.OServerCommandPostCommand.execute(OServerCommandPostCommand.java:104)
2024-12-13 10:08:22     at com.orientechnologies.orient.server.network.protocol.http.command.post.OServerCommandPostCommandGraph.execute(OServerCommandPostCommandGraph.java:34)
2024-12-13 10:08:22     at com.orientechnologies.orient.server.network.protocol.http.ONetworkProtocolHttpAbstract.service(ONetworkProtocolHttpAbstract.java:242)
2024-12-13 10:08:22     at com.orientechnologies.orient.server.network.protocol.http.ONetworkProtocolHttpAbstract.execute(ONetworkProtocolHttpAbstract.java:800)
2024-12-13 10:08:22     at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:68)
2024-12-13 10:08:22 Caused by: com.orientechnologies.orient.core.exception.OStorageException: Exception during execution of component operation inside of storage db     DB name="db"
2024-12-13 10:08:22     at com.orientechnologies.orient.core.storage.impl.local.paginated.atomicoperations.OAtomicOperationsManager.calculateInsideComponentOperation(OAtomicOperationsManager.java:226)
2024-12-13 10:08:22     at com.orientechnologies.orient.core.storage.impl.local.paginated.atomicoperations.OAtomicOperationsManager.calculateInsideComponentOperation(OAtomicOperationsManager.java:213)
2024-12-13 10:08:22     at com.orientechnologies.orient.core.storage.impl.local.paginated.base.ODurableComponent.calculateInsideComponentOperation(ODurableComponent.java:96)
2024-12-13 10:08:22     at com.orientechnologies.orient.core.storage.index.sbtreebonsai.local.OSBTreeBonsaiLocal.createComponent(OSBTreeBonsaiLocal.java:88)
2024-12-13 10:08:22     at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.lambda$addIndexEngine$13(OAbstractPaginatedStorage.java:2781)
2024-12-13 10:08:22     at com.orientechnologies.orient.core.storage.impl.local.paginated.atomicoperations.OAtomicOperationsManager.calculateInsideAtomicOperation(OAtomicOperationsManager.java:122)
2024-12-13 10:08:22     ... 14 more
2024-12-13 10:08:22 Caused by: com.orientechnologies.orient.core.exception.OStorageException: Ridbag component with name IdxContractClaimed.irs already exists    DB name="db"
2024-12-13 10:08:22     at com.orientechnologies.orient.core.storage.index.sbtreebonsai.local.OSBTreeBonsaiLocal.lambda$createComponent$0(OSBTreeBonsaiLocal.java:93)
2024-12-13 10:08:22     at com.orientechnologies.orient.core.storage.impl.local.paginated.atomicoperations.OAtomicOperationsManager.calculateInsideComponentOperation(OAtomicOperationsManager.java:221)
2024-12-13 10:08:22     ... 19 more
```

**Comment by tglman** [comment]
Hi,

I think this is the case because of changed behavior, so now if you set "ignoreNullValues=true" if you save a record with a null value it does give an error, this was not the case before, I'm double checking this logic and when it was changed, because ignoring should not mean failing, but I guess the old storage maintainer didn't think so, will update soon on this.

**Comment by ishvo** [comment]
Giving an error would be somewhat ok, but it breaks the entire database.

Dropping and creating the index again solves this issue.

**Comment by tglman** [comment]
Hi,

I actually found that there where two checks one high level to avoid to send null to low level, and one low level that create this issue, in the case of rebuild index the first high level check was missing, so I did add it, this should be fixed from the next hotfix 3.2.38.

Regards

**Comment by tglman** [comment]
Hi,

This should be fixed in 3.2.38, can you try again with this release ?

**Comment by tglman** [comment]
Hi,

closing this, feel free to reopen if you still see the problem.

**Comment by aryanPatilhm2** [comment]
Hi @tglman 
Could you please advise on how to resolve this issue on our existing production server database? We're currently running version 3.2.31, and upgrading at this time is not an option.
I followed the suggested workaround and dropped the index (which is a NOTUNIQUE_HASH_INDEX using the HASH_INDEX engine), but I’m unable to recreate it. The same issue persists.
I also attempted to manually delete the affected .irs file(only .irs file of that indexed property), but even after that, recreating the index still fails.
Now, we’re encountering an additional issue, as described in the bug report below.
[cannot (re)create indexes anymore](https://github.com/orientechnologies/orientdb/issues/7659)
 Would you recommend a different solution?

**Comment by tglman** [comment]
Hi,

The only way to avoid it to fail in the old version is to actually index null values, so when you crate the index just remove the part `{ignoreNullValues: true}` or set it to false `{ignoreNullValues: false}`, this may have only some small performance impact for record with null values.

when you say you got the same problem of here: https://github.com/orientechnologies/orientdb/issues/7659 which one do you refer, there are quite a few problems, can you actually open a specific issue with your specific problem, because it may be quite different error trace int 3.2.x

Regards

**Comment by RolT** [comment]
Hello,

I'm having a issue with a similar cause: I have an index with `{ignoreNullValues: true}`, where all the values are NULL (yes I know, not really a useful index...). What happened is that in 2.2, the .irs file was missing for that index, but the 3.2 version expect that file to exist. When running `REBUILD INDEX *` I'm getting the following error:

```
SEVERE: Exception `554DB19D` in storage `plocal:C:\./db`: 3.2.44 (build ${buildNumber}, branch UNKNOWN)
com.orientechnologies.orient.core.exception.OStorageException: Internal error happened in storage db please restart the server or re-open the storage to undergo the restore process and fix the error.	DB name="db"
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.checkErrorState(OAbstractPaginatedStorage.java:4587)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.checkOpennessAndMigration(OAbstractPaginatedStorage.java:4567)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.addIndexEngine(OAbstractPaginatedStorage.java:2721)
	at com.orientechnologies.orient.core.index.OIndexAbstract.rebuild(OIndexAbstract.java:487)
	at com.orientechnologies.orient.core.index.OIndexAbstract.rebuild(OIndexAbstract.java:338)
	at com.orientechnologies.orient.core.sql.parser.ORebuildIndexStatement.executeSimple(ORebuildIndexStatement.java:36)
	at com.orientechnologies.orient.core.sql.executor.OSingleOpExecutionPlan.executeInternal(OSingleOpExecutionPlan.java:63)
	at com.orientechnologies.orient.core.sql.parser.OSimpleExecStatement.execute(OSimpleExecStatement.java:45)
	at com.orientechnologies.orient.core.sql.parser.OStatement.execute(OStatement.java:76)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentEmbedded.command(ODatabaseDocumentEmbedded.java:634)
	at com.orientechnologies.orient.console.OConsoleDatabaseApp.sqlCommand(OConsoleDatabaseApp.java:3583)
	at com.orientechnologies.orient.console.OConsoleDatabaseApp.rebuildIndex(OConsoleDatabaseApp.java:1554)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at com.orientechnologies.common.console.OConsoleApplication.execute(OConsoleApplication.java:456)
	at com.orientechnologies.common.console.OConsoleApplication.executeCommands(OConsoleApplication.java:283)
	at com.orientechnologies.common.console.OConsoleApplication.executeBatch(OConsoleApplication.java:238)
	at com.orientechnologies.common.console.OConsoleApplication.run(OConsoleApplication.java:153)
	at com.orientechnologies.orient.graph.console.OGremlinConsole.main(OGremlinConsole.java:71)
Caused by: com.orientechnologies.orient.core.exception.OStorageException: Exception during execution of component operation inside component Run.meanHardness.irs in storage db	DB name="db"
	at com.orientechnologies.orient.core.storage.impl.local.paginated.atomicoperations.OAtomicOperationsManager.executeInsideComponentOperation(OAtomicOperationsManager.java:172)
	at com.orientechnologies.orient.core.storage.impl.local.paginated.atomicoperations.OAtomicOperationsManager.executeInsideComponentOperation(OAtomicOperationsManager.java:157)
	at com.orientechnologies.orient.core.storage.impl.local.paginated.base.ODurableComponent.executeInsideComponentOperation(ODurableComponent.java:102)
	at com.orientechnologies.orient.core.storage.index.sbtreebonsai.local.OSBTreeBonsaiLocal.deleteComponent(OSBTreeBonsaiLocal.java:595)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.lambda$deleteIndexEngine$14(OAbstractPaginatedStorage.java:2912)
	at com.orientechnologies.orient.core.storage.impl.local.paginated.atomicoperations.OAtomicOperationsManager.executeInsideAtomicOperation(OAtomicOperationsManager.java:140)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.deleteIndexEngine(OAbstractPaginatedStorage.java:2896)
	at com.orientechnologies.orient.core.index.OIndexAbstract.doDelete(OIndexAbstract.java:673)
	at com.orientechnologies.orient.core.index.OIndexAbstract.rebuild(OIndexAbstract.java:473)
	... 17 more
Caused by: com.orientechnologies.orient.core.exception.OStorageException: File with name Run.meanHardness.irs does not exist in storage db	DB name="db"
	at com.orientechnologies.orient.core.storage.cache.local.OWOWCache.loadFile(OWOWCache.java:655)
	at com.orientechnologies.orient.core.storage.impl.local.paginated.atomicoperations.OAtomicOperationBinaryTracking.loadFile(OAtomicOperationBinaryTracking.java:345)
	at com.orientechnologies.orient.core.storage.impl.local.paginated.base.ODurableComponent.openFile(ODurableComponent.java:180)
	at com.orientechnologies.orient.core.storage.index.sbtreebonsai.local.OSBTreeBonsaiLocal.lambda$deleteComponent$7(OSBTreeBonsaiLocal.java:598)
	at com.orientechnologies.orient.core.storage.impl.local.paginated.atomicoperations.OAtomicOperationsManager.executeInsideComponentOperation(OAtomicOperationsManager.java:165)
	... 25 more
```

The operation tries to delete the .irs file and fail. I could not even drop the faulty index. I tried adding a empty .irs file but that did not help. To salvage the database, I had to export / import the whole database. Is there a way to ignore the error and force the rebuild of the index based on the data ?

**Comment by ishvo** [comment]
Hey @RolT , my workaround is to import and delete the index before trying to reindex. Create a new index in 3.x again and that worked for me.

I believe that one can alternatively delete the index before the emport the create it again after the import.
