### ISSUE TITLE
Error in binding a list parameter on an indexed field [moved]

### ISSUE THREAD

**Issue by lvca** [orientechnologies/orientdb#1074]
This is [Issue 1074](http://code.google.com/p/orient/issues/detail?id=1074) moved from a Google Code project.
Added by 2012-09-27T12:59:25.000Z by [r.ventag...@gmail.com](http://code.google.com/u/116388565395359186910/).
Please review that bug for more context and additional comments, but update this bug.
 Closed (Fixed).

Original labels: Type-Defect, Priority-Medium, v1.2.0
### Original description

```
OrientDB release? 1.1.0
But I have tried also with latest SNAPSHOT version (build number r6556) and I have the same problem.


<b>What steps will reproduce the problem?</b>

Execute this standalone test:

@Test
    public void testSelectFromListParameter() {

        OGraphDatabase db = new OGraphDatabase(&quot;memory:test&quot;);
        db.create();

        OClass placeClass = db.createVertexType(&quot;Place&quot;);
        placeClass.createProperty(&quot;id&quot;, OType.STRING);
        placeClass.createProperty(&quot;descr&quot;, OType.STRING);
        placeClass.createIndex(&quot;place_id_index&quot;, INDEX_TYPE.UNIQUE, &quot;id&quot;);

        ODocument odoc = new ODocument(&quot;Place&quot;);
        odoc.field(&quot;id&quot;, &quot;adda&quot;);
        odoc.field(&quot;descr&quot;, &quot;Adda&quot;);
        db.save(odoc);

        odoc = new ODocument(&quot;Place&quot;);
        odoc.field(&quot;id&quot;, &quot;lago_di_como&quot;);
        odoc.field(&quot;descr&quot;, &quot;Lago di Como&quot;);
        db.save(odoc);

        Map<String, Object> params = new HashMap<String, Object>();
        List<String> inputValues = new ArrayList<String>();
        inputValues.add(&quot;lago_di_como&quot;);
        inputValues.add(&quot;lecco&quot;);
        params.put(&quot;place&quot;, inputValues);

        List<ODocument> result = new OSQLSynchQuery<ODocument>(&quot;select from place where id in :place&quot;).execute(params);
        assertEquals(1, result.size());

        db.close();
    }


<b>What is the expected output? What do you see instead?</b>

I get a ClassCastException on query execution:
com.orientechnologies.orient.core.exception.OCommandExecutionException: Error on execution of command: OSQLQuery [text=select  from place where id in :place]
    at com.orientechnologies.orient.core.storage.OStorageEmbedded.executeCommand(OStorageEmbedded.java:89)
    at com.orientechnologies.orient.core.storage.OStorageEmbedded.command(OStorageEmbedded.java:74)
    at com.orientechnologies.orient.core.sql.query.OSQLQuery.run(OSQLQuery.java:68)
    at com.orientechnologies.orient.core.sql.query.OSQLSynchQuery.run(OSQLSynchQuery.java:78)
    at com.orientechnologies.orient.core.query.OQueryAbstract.execute(OQueryAbstract.java:30)
    at SelectCollectionTest.testSelectFromListParameter(SelectCollectionTest.java:69)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:616)
    at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:45)
    at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
    at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:42)
    at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20)
    at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:263)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:68)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:47)
    at org.junit.runners.ParentRunner$3.run(ParentRunner.java:231)
    at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:60)
    at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:229)
    at org.junit.runners.ParentRunner.access$000(ParentRunner.java:50)
    at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:222)
    at org.junit.runners.ParentRunner.run(ParentRunner.java:300)
    at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
    at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)
Caused by: java.lang.ClassCastException: com.orientechnologies.orient.core.sql.filter.OSQLFilterItemParameter cannot be cast to java.util.List
    at com.orientechnologies.orient.core.sql.operator.OQueryOperatorIn.executeIndexQuery(OQueryOperatorIn.java:111)
    at com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.searchForIndexes(OCommandExecutorSQLSelect.java:426)
    at com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.searchInClasses(OCommandExecutorSQLSelect.java:359)
    at com.orientechnologies.orient.core.sql.OCommandExecutorSQLResultsetAbstract.assignTarget(OCommandExecutorSQLResultsetAbstract.java:135)
    at com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.assignTarget(OCommandExecutorSQLSelect.java:222)
    at com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.executeSearch(OCommandExecutorSQLSelect.java:208)
    at com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.execute(OCommandExecutorSQLSelect.java:198)
    at com.orientechnologies.orient.core.sql.OCommandExecutorSQLDelegate.execute(OCommandExecutorSQLDelegate.java:54)
    at com.orientechnologies.orient.core.storage.OStorageEmbedded.executeCommand(OStorageEmbedded.java:82)
    ... 28 more


In order to help you to identify the problem, I can tell you that if I comment away the &quot;index&quot; creation the test works.
```

**Comment by mathieubodin** [comment]
Error is still occurring in 2.0-rc1

**Comment by lvca** [comment]
Could you provide the new stack trace with the error?

**Comment by mathieubodin** [comment]
Here is the stack :

```java
Caused by: java.lang.ClassCastException: com.orientechnologies.orient.core.sql.filter.OSQLFilterItemParameter cannot be cast to java.util.List
	at com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.searchInIndex(OCommandExecutorSQLSelect.java:1829)
	at com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.assignTarget(OCommandExecutorSQLSelect.java:437)
	at com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.executeSearch(OCommandExecutorSQLSelect.java:417)
	at com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.execute(OCommandExecutorSQLSelect.java:388)
	at com.orientechnologies.orient.core.sql.OCommandExecutorSQLDelegate.execute(OCommandExecutorSQLDelegate.java:64)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.executeCommand(OAbstractPaginatedStorage.java:1163)
```

I look into OCommandExecutorSQLSelect.class on line #1829 in debug mode

```java
final List<Object> origValues = (List<Object>) compiledFilter.getRootCondition().getRight();
```

It appears that the getRight() method return an instance com.orientechnologies.orient.core.sql.filter.OSQLFilterItemParameter.

For the record, the use case is mainly the same. I finally avoid querying the index and it work, but I fear for the queries performances.
