### ISSUE TITLE
Java API: SKIP binding property ignored and fails executing query [moved]

### ISSUE THREAD

**Issue by lvca** [orientechnologies/orientdb#1163]
This is [Issue 1163](http://code.google.com/p/orient/issues/detail?id=1163) moved from a Google Code project.
Added by 2012-11-07T13:23:30.000Z by [alex.ded...@gmail.com](http://code.google.com/u/115548372219125782542/).
Please review that bug for more context and additional comments, but update this bug.

Original labels: Type-Defect, Priority-Medium, v2.0.0

### Original description

    OrientDB release? 
    OrientDB Server v1.2.0
    
    <b>What steps will reproduce the problem?</b>
    [source]
                    OSQLSynchQuery<ODocument> query = new OSQLSynchQuery<ODocument>(
                            &quot;SELECT FROM vRecord WHERE ownerId = :ownerId ORDER BY updatedAt DESC SKIP :offset&quot;
                            );
                    Map<String,Object> params = new HashMap<String,Object>();
                    params.put(&quot;ownerId&quot;, userId);
                    params.put(&quot;offset&quot;, 10);
    
                    List<ODocument> resultSet = db.command(query).execute(params);
    [/source]
    
    Exception:
    com.orientechnologies.orient.core.sql.OCommandSQLParsingException: Error on parsing command at position #73: Invalid SKIP value setted to ':OFFSET' but it should be a valid positive integer. Example: SKIP 10
    Command: SELECT FROM vRecord WHERE ownerId = :ownerId ORDER BY updatedAt DESC SKIP :offset
    ---------------------------------------------------------------------------------^
    	at com.orientechnologies.orient.core.sql.OCommandExecutorSQLAbstract.throwParsingException(OCommandExecutorSQLAbstract.java:46)
    	at com.orientechnologies.orient.core.sql.OCommandExecutorSQLResultsetAbstract.parseSkip(OCommandExecutorSQLResultsetAbstract.java:279)
    	at com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.parse(OCommandExecutorSQLSelect.java:145)
    	at com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.parse(OCommandExecutorSQLSelect.java:79)
    	at com.orientechnologies.orient.core.sql.OCommandExecutorSQLDelegate.parse(OCommandExecutorSQLDelegate.java:48)
    	at com.orientechnologies.orient.core.sql.OCommandExecutorSQLDelegate.parse(OCommandExecutorSQLDelegate.java:33)
    	at com.orientechnologies.orient.core.storage.OStorageEmbedded.command(OStorageEmbedded.java:77)
    	at com.orientechnologies.orient.core.sql.query.OSQLQuery.run(OSQLQuery.java:69)
    
    
    <b>What is the expected output? What do you see instead?</b>
    Why :offset is not bind properly?
    Current workaround is:
    &quot;SELECT FROM vRecord WHERE ownerId = :ownerId ORDER BY updatedAt DESC SKIP &quot; + offset

**Comment by lvca** [comment]
Duplicate #2801
