### ISSUE TITLE
Warning on log files at startup

### ISSUE THREAD

**Issue by odino** [orientechnologies/orientdb#1462]
If you start the server **not** from the `bin` folder (ie `./bin/server.sh`):

```
~/Downloads/orientdb-graphed-1.4.0-SNAPSHOT  ᐅ ./bin/server.sh                                   
           .                                              
          .`        `                                     
          ,      `:.                                      
         `,`    ,:`                                       
         .,.   :,,                                        
         .,,  ,,,                                         
    .    .,.:::::  ````                                   
    ,`   .::,,,,::.,,,,,,`;;                      .:      
    `,.  ::,,,,,,,:.,,.`  `                       .:      
     ,,:,:,,,,,,,,::.   `        `         ``     .:      
      ,,:.,,,,,,,,,: `::, ,,   ::,::`   : :,::`  ::::     
       ,:,,,,,,,,,,::,:   ,,  :.    :   ::    :   .:      
        :,,,,,,,,,,:,::   ,,  :      :  :     :   .:      
  `     :,,,,,,,,,,:,::,  ,, .::::::::  :     :   .:      
  `,...,,:,,,,,,,,,: .:,. ,, ,,         :     :   .:      
    .,,,,::,,,,,,,:  `: , ,,  :     `   :     :   .:      
      ...,::,,,,::.. `:  .,,  :,    :   :     :   .:      
           ,::::,,,. `:   ,,   :::::    :     :   .:      
           ,,:` `,,.                                      
          ,,,    .,`                                      
         ,,.     `,                     GRAPH-DB Server   
       ``        `.                                       
                 ``                                       
                 `                                        
Can't load log handler "java.util.logging.FileHandler"
java.io.IOException: Couldn't get lock for ../log/orient-server.log
java.io.IOException: Couldn't get lock for ../log/orient-server.log
	at java.util.logging.FileHandler.openFiles(FileHandler.java:372)
	at java.util.logging.FileHandler.<init>(FileHandler.java:208)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:39)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:27)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:513)
	at java.lang.Class.newInstance0(Class.java:355)
	at java.lang.Class.newInstance(Class.java:308)
	at java.util.logging.LogManager$3.run(LogManager.java:359)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.util.logging.LogManager.loadLoggerHandlers(LogManager.java:345)
	at java.util.logging.LogManager.initializeGlobalHandlers(LogManager.java:1032)
	at java.util.logging.LogManager.access$1100(LogManager.java:129)
	at java.util.logging.LogManager$RootLogger.getHandlers(LogManager.java:1113)
	at java.util.logging.Logger.log(Logger.java:474)
	at java.util.logging.Logger.doLog(Logger.java:500)
	at java.util.logging.Logger.log(Logger.java:523)
	at com.orientechnologies.common.log.OLogManager.log(OLogManager.java:45)
	at com.orientechnologies.common.log.OLogManager.info(OLogManager.java:81)
	at com.orientechnologies.common.profiler.OProfiler.startRecording(OProfiler.java:124)
	at com.orientechnologies.orient.core.Orient.<init>(Orient.java:90)
	at com.orientechnologies.orient.core.Orient.<clinit>(Orient.java:70)
	at com.orientechnologies.orient.core.config.OGlobalConfiguration$5.change(OGlobalConfiguration.java:346)
	at com.orientechnologies.orient.core.config.OGlobalConfiguration.setValue(OGlobalConfiguration.java:453)
	at com.orientechnologies.orient.core.config.OGlobalConfiguration.readConfiguration(OGlobalConfiguration.java:558)
	at com.orientechnologies.orient.core.config.OGlobalConfiguration.<clinit>(OGlobalConfiguration.java:420)
	at com.orientechnologies.orient.server.OServer.defaultSettings(OServer.java:616)
	at com.orientechnologies.orient.server.OServer.<init>(OServer.java:98)
	at com.orientechnologies.orient.server.OServerMain.create(OServerMain.java:22)
	at com.orientechnologies.orient.server.OServerMain.main(OServerMain.java:31)
```

**Comment by StarpTech** [comment]
On Windows:

You have to fix the `java.util.logging.FileHandler.pattern``in the orientdb-server-log-properties
to an absolute path like

`C:\\Users\\...`
