### ISSUE TITLE
db.close does not work on remote db.

### ISSUE THREAD

**Issue by andrii0lomakin** [orientechnologies/orientdb#1686]
am experiencing a pretty critical problem with version 1.5.1.

All the requests in my application are handled in the following way:

ODatabaseDocument conn = null;

try {
   conn = new ODatabaseDocumentTx(dbName).open(username, password);

   // do stuff

} finally{
   conn.close();
}

As you can see no database pools are used. After a while the application is not able to process any request. The following Exception is shown in the client application log:

java.lang.OutOfMemoryError: unable to create new native thread
        at java.lang.Thread.start0(Native Method) [rt.jar:1.7.0_25]
        at java.lang.Thread.start(Thread.java:693) [rt.jar:1.7.0_25]
        at com.orientechnologies.orient.enterprise.channel.binary.OAsynchChannelServiceThread.<init>(OAsynchChannelServiceThread.java:40)
        at com.orientechnologies.orient.enterprise.channel.binary.OChannelBinaryClient.<init>(OChannelBinaryClient.java:89)
        at com.orientechnologies.orient.client.remote.OStorageRemote.createNetworkConnection(OStorageRemote.java:1712)
        at com.orientechnologies.orient.client.remote.OStorageRemote.beginResponse(OStorageRemote.java:1886)
        at com.orientechnologies.orient.client.remote.OStorageRemote.openRemoteDatabase(OStorageRemote.java:1572)
        at com.orientechnologies.orient.client.remote.OStorageRemote.open(OStorageRemote.java:176)
        at com.orientechnologies.orient.client.remote.OStorageRemoteThread.open(OStorageRemoteThread.java:70)
        at com.orientechnologies.orient.core.db.raw.ODatabaseRaw.open(ODatabaseRaw.java:105)
        at com.orientechnologies.orient.core.db.ODatabaseWrapperAbstract.open(ODatabaseWrapperAbstract.java:49)
        at com.orientechnologies.orient.core.db.record.ODatabaseRecordAbstract.open(ODatabaseRecordAbstract.java:119)
        at com.orientechnologies.orient.core.db.ODatabaseWrapperAbstract.open(ODatabaseWrapperAbstract.java:49)

Moreover, the Server Management panel in Orient Studio shows a long list of binary active connections but the Database field is not specified.
If I restart the client application the active connections disappeared and the application returns to work properly.

Since I am pretty sure to close all the connections (the close() call is in the finally block) I think there is a problem with the OrientDB close() method.
Is there any workaround to sort it out?

**Comment by hosseinGanjyar** [comment]
I have using nodejs+orient, insert 8000000 records, but no freed memory.
[https://github.com/orientechnologies/orientdb/issues/7080](url)
