### ISSUE TITLE
Intermittent OTransactionException

### ISSUE THREAD

**Issue by MelissaMifsud** [orientechnologies/orientdb#1687]
On 1.5.1, using OObjectDatabase:

com.orientechnologies.orient.core.exception.OTransactionException: Invalid state of the transaction. The transaction must be begun.
	at com.orientechnologies.orient.core.tx.OTransactionRealAbstract.checkTransaction(OTransactionRealAbstract.java:345)
	at com.orientechnologies.orient.core.tx.OTransactionOptimistic.addRecord(OTransactionOptimistic.java:235)
	at com.orientechnologies.orient.core.tx.OTransactionOptimistic.loadRecord(OTransactionOptimistic.java:214)
	at com.orientechnologies.orient.core.db.record.ODatabaseRecordTx.load(ODatabaseRecordTx.java:201)
	at com.orientechnologies.orient.core.db.record.ODatabaseRecordTx.load(ODatabaseRecordTx.java:37)
	at com.orientechnologies.orient.core.id.ORecordId.getRecord(ORecordId.java:296)
	at com.orientechnologies.orient.core.db.record.ORecordLazyList.convertLink2Record(ORecordLazyList.java:357)
	at com.orientechnologies.orient.core.db.record.ORecordLazyList.get(ORecordLazyList.java:202)
	at com.orientechnologies.orient.core.db.record.ORecordLazyList.get(ORecordLazyList.java:42)
	at com.orientechnologies.orient.object.db.OObjectLazyList.get(OObjectLazyList.java:144)
	at com.orientechnologies.orient.object.db.OObjectLazyListIterator.next(OObjectLazyListIterator.java:53)
	at com.orientechnologies.orient.object.db.OObjectLazyListIterator.next(OObjectLazyListIterator.java:49)

**Comment by lvca** [comment]
N reproducible anymore

**Comment by lvca** [comment]
No reproducible anymore
