### ISSUE TITLE
(OObjectTxDatabase) Intermittent NPE when saving

### ISSUE THREAD

**Issue by MelissaMifsud** [orientechnologies/orientdb#1688]
This problem occurs intermittently on 1.5.1

java.lang.NullPointerException
	at com.orientechnologies.orient.core.record.impl.ODocument.field(ODocument.java:572)
	at com.orientechnologies.orient.core.record.impl.ODocument.field(ODocument.java:636)
	at com.orientechnologies.orient.object.enhancement.OObjectProxyMethodHandler.getDocFieldValue(OObjectProxyMethodHandler.java:349)
	at com.orientechnologies.orient.object.enhancement.OObjectProxyMethodHandler.getValue(OObjectProxyMethodHandler.java:285)
	at com.orientechnologies.orient.object.enhancement.OObjectProxyMethodHandler.updateLoadedFieldMap(OObjectProxyMethodHandler.java:232)
	at com.orientechnologies.orient.object.db.OObjectDatabaseTx.save(OObjectDatabaseTx.java:426)
	at com.orientechnologies.orient.object.db.OObjectDatabaseTx.save(OObjectDatabaseTx.java:334)

**Comment by tglman** [comment]
Really old issue, closing problably was solved long time ago,
