### ISSUE TITLE
During a programatic schema creation, myclass.setAbstract( true ), fails

### ISSUE THREAD

**Issue by ppet** [orientechnologies/orientdb#1785]
val schema = db.getMetadata.getSchema
val theClass:OClass =  schema.createClass("className", schema.getClass("superClass"))
theClass.createProperty("prop1", OType.STRING)
... REPEATED

theClass.setStrictMode(true) // OK so far
theClass.setAbstract( true ) // fails
schema.save

theClass.setAbstract( true ) throws this exception:
Exception in thread "main" com.orientechnologies.orient.core.exception.ODatabaseException: Error on reading records size for cluster with id '11'
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:39)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:27)
    at java.lang.reflect.Constructor.newInstance(Constructor.java:513)
    at com.orientechnologies.common.log.OLogManager.exception(OLogManager.java:162)
    at com.orientechnologies.orient.core.db.raw.ODatabaseRaw.getClusterRecordSizeById(ODatabaseRaw.java:398)
    at com.orientechnologies.orient.core.db.ODatabaseWrapperAbstract.getClusterRecordSizeById(ODatabaseWrapperAbstract.java:197)
    at com.orientechnologies.orient.core.metadata.schema.OClassImpl.setAbstractInternal(OClassImpl.java:745)
    at com.orientechnologies.orient.core.metadata.schema.OClassImpl.setAbstract(OClassImpl.java:728)
    at models.DataSchema$.createSchema(DataSchema.scala:80)
    at models.Test$.main(Test.scala:96)
    at models.Test.main(Test.scala)
Caused by: java.lang.UnsupportedOperationException: getRecordsSize()
    at com.orientechnologies.orient.client.remote.OClusterRemote.getRecordsSize(OClusterRemote.java:208)
    at com.orientechnologies.orient.core.db.raw.ODatabaseRaw.getClusterRecordSizeById(ODatabaseRaw.java:396)
    ... 6 more

**Comment by lvca** [comment]
Fixed long time ago.
