### ISSUE TITLE
In which situation cause this problem?

### ISSUE THREAD

**Issue by arebya** [orientechnologies/orientdb#2261]
```
WARNING: Caught I/O errors from /10.58.49.21:8424 (local socket=0.0.0.0/0.0.0.0:44868), trying to reconnect (error: java.io.IOException: Stream closed)
2014-04-21 15:00:47,431 [http-bio-8658-exec-9] ERROR 500.jsp - Timeout on acquiring lock against resource of class: class com.orientechnologies.orient.core.db.ODatabasePoolBase$1 with timeout=600000
com.orientechnologies.common.concur.OTimeoutException: Timeout on acquiring lock against resource of class: class com.orientechnologies.orient.core.db.ODatabasePoolBase$1 with timeout=600000
        at com.orientechnologies.common.concur.lock.OAdaptiveLock.lock(OAdaptiveLock.java:84) ~[orient-commons-1.7-rc2.jar:1.7-rc2]
        at com.orientechnologies.orient.core.db.ODatabasePoolAbstract.onStorageUnregistered(ODatabasePoolAbstract.java:225) ~[orientdb-core-1.7-rc2.jar:1.7-rc2]
        at com.orientechnologies.orient.core.Orient.unregisterStorage(Orient.java:341) ~[orientdb-core-1.7-rc2.jar:1.7-rc2]
        at com.orientechnologies.orient.client.remote.OStorageRemoteThread.close(OStorageRemoteThread.java:189) ~[orientdb-client-1.7-rc2.jar:1.7-rc2]
        at com.orientechnologies.orient.core.db.raw.ODatabaseRaw.close(ODatabaseRaw.java:513) ~[orientdb-core-1.7-rc2.jar:1.7-rc2]
        at com.orientechnologies.orient.core.db.ODatabaseWrapperAbstract.close(ODatabaseWrapperAbstract.java:85) ~[orientdb-core-1.7-rc2.jar:1.7-rc2]
        at com.orientechnologies.orient.core.db.record.ODatabaseRecordAbstract.close(ODatabaseRecordAbstract.java:434) ~[orientdb-core-1.7-rc2.jar:1.7-rc2]
        at com.orientechnologies.orient.core.db.record.ODatabaseRecordTx.close(ODatabaseRecordTx.java:194) ~[orientdb-core-1.7-rc2.jar:1.7-rc2]
        at com.orientechnologies.orient.core.db.ODatabaseWrapperAbstract.close(ODatabaseWrapperAbstract.java:85) ~[orientdb-core-1.7-rc2.jar:1.7-rc2]
        at com.tinkerpop.blueprints.impls.orient.OrientGraphFactory.setupPool(OrientGraphFactory.java:83) ~[orientdb-graphdb-1.7-rc2.jar:1.7-rc2]

```

**Comment by lvca** [comment]
No answer after long time, closing.
