### ISSUE TITLE
v2.0-snap- Boolean cannot be serialized 

### ISSUE THREAD

**Issue by publicocean0** [orientechnologies/orientdb#2486]
com.orientechnologies.orient.core.exception.OSerializationException: Type Boolean cannot be serialized because is not part of registered entities. To fix this error register this class
    at com.orientechnologies.orient.object.db.OObjectDatabaseTx.newInstance(OObjectDatabaseTx.java:137)
    at com.orientechnologies.orient.object.db.OObjectDatabaseTx.newInstance(OObjectDatabaseTx.java:93)
    at com.orientechnologies.orient.object.enhancement.OObjectEntitySerializer.serializeObject(OObjectEntitySerializer.java:120)
    at com.orientechnologies.orient.object.db.OObjectDatabaseTx.getRecordByUserObject(OObjectDatabaseTx.java:714)
    at com.orientechnologies.orient.object.db.OObjectLazyMap.put(OObjectLazyMap.java:100)

**Comment by tglman** [comment]
Hi,

Probably fixed long time ago, closing.

Regards
