### ISSUE TITLE
db creation fails on Windows with clustering 

### ISSUE THREAD

**Issue by odbuser2** [orientechnologies/orientdb#2600]
```
OrientDB 1.7.7-SNAPSHOT (uses hazelcast 3.2.2)
OS : Windows (8.1 and 2008 Server fail), osx (works), solaris 10 (works)
```

I'm using OrientDB embedded.  The hazelcast configuration does not include any remote nodes besides itself.  The app creates the database on startup and it's working under OSX and Solaris 10 but it fails on Windows 8.1 and 2008 Server when trying to "create class V".

Another user reported that it is also failing on Linux.
https://groups.google.com/forum/#!topic/orient-database/vAREt3Vdn08

Here's the stacktrace:
```
[MYHOST] Installing distributed storage on database 'db'
[MYHOST] Publishing online status for database MYHOST.db...
[MYHOST] Database MYHOST.db is online, waking up listeners on local node...
[MYHOST] received updated status MYHOST.db=ONLINE
[MYHOST] No nodes configured for partition 'db.[]' request: id=-1 from=MYHOST task=command_sql(create class V)
ODistributedStorage@74   |Cannot route COMMAND operation to the distributed node
com.orientechnologies.orient.server.distributed.ODistributedException: No nodes configured for partition 'db.[]' request: id=-1 from=MYHOST task=command_sql(create class V) userName=admin
        at com.orientechnologies.orient.server.hazelcast.OHazelcastPlugin.sendRequest(OHazelcastPlugin.java:367) ~[bundleFile:1.7.6]
        at com.orientechnologies.orient.server.distributed.ODistributedStorage.command(ODistributedStorage.java:185) ~[bundleFile:1.7.6]
        at com.orientechnologies.orient.core.command.OCommandRequestTextAbstract.execute(OCommandRequestTextAbstract.java:59) [bundleFile:1.7.6]
        at com.orientechnologies.orient.core.metadata.schema.OSchemaShared.createClass(OSchemaShared.java:306) [bundleFile:1.7.6]
        at com.orientechnologies.orient.core.metadata.schema.OSchemaShared.createClass(OSchemaShared.java:160) [bundleFile:1.7.6]
        at com.orientechnologies.orient.core.metadata.schema.OSchemaProxy.createClass(OSchemaProxy.java:62) [bundleFile:1.7.6]
        at com.tinkerpop.blueprints.impls.orient.OrientBaseGraph.checkForGraphSchema(OrientBaseGraph.java:1571) [bundleFile:1.7.6]
        at com.tinkerpop.blueprints.impls.orient.OrientBaseGraph.openOrCreate(OrientBaseGraph.java:1747) [bundleFile:1.7.6]
        at com.tinkerpop.blueprints.impls.orient.OrientBaseGraph.<init>(OrientBaseGraph.java:131) [bundleFile:1.7.6]
        at com.tinkerpop.blueprints.impls.orient.OrientBaseGraph.<init>(OrientBaseGraph.java:197) [bundleFile:1.7.6]
        at com.tinkerpop.blueprints.impls.orient.OrientGraphNoTx.<init>(OrientGraphNoTx.java:44) [bundleFile:1.7.6]
```

**Comment by lvca** [comment]
Old issue, closing. In case please reopen it.
