### ISSUE TITLE
Calling `console.sh file.sql` fails if file.sql starts with a comment

### ISSUE THREAD

**Issue by garrett-gottlieb** [orientechnologies/orientdb#2604]
If the sql file starts with a comment, eg.
```
-- test
CREATE DATABASE remote:localhost/pumpup root pass plocal graph
```
It will fail with
```
Exception in thread "main" java.lang.IllegalStateException: Unexpected end of file
	at com.orientechnologies.common.console.ODFACommandStream.nextCommand(ODFACommandStream.java:81)
	at com.orientechnologies.common.console.OConsoleApplication.executeCommands(OConsoleApplication.java:205)
	at com.orientechnologies.common.console.OConsoleApplication.executeBatch(OConsoleApplication.java:199)
	at com.orientechnologies.common.console.OConsoleApplication.run(OConsoleApplication.java:138)
	at com.orientechnologies.orient.graph.console.OGremlinConsole.main(OGremlinConsole.java:54)
```

**EDIT**
This is weirder than I thought. I'm not sure what's causing it anymore, but this fails:
```sql

-- NOTE: do not start this file with a comment, otherwise it will fail

-- create and connect to database
CREATE DATABASE remote:localhost/pumpup root pass plocal graph
CONNECT remote:localhost/pumpup root pass

-- set datetimeformat to match parse (and javascript)
ALTER DATABASE DATETIMEFORMAT yyyy-MM-dd'T'HH:mm:ss.SSS'Z'

-- enable counting of graph edges
ALTER DATABASE CUSTOM useLightweightEdges=false

-- abstract vertex class
CREATE CLASS PumpUp ABSTRACT
CREATE PROPERTY PumpUp.objectId STRING
CREATE INDEX PumpUp.objectId UNIQUE_HASH_INDEX
CREATE PROPERTY PumpUp.createdAt DATETIME
CREATE PROPERTY PumpUp.updatedAt DATETIME
CREATE INDEX PumpUp.updatedAt NOTUNIQUE
CREATE PROPERTY PumpUp.ACL EMBEDDEDMAP EMBEDDEDMAP
CREATE PROPERTY PumpUp.replacedACL BOOLEAN
CREATE INDEX PumpUp.replacedACL NOTUNIQUE_HASH_INDEX

-- record level security (TURNED OFF BECAUSE OF ORIENTO NullPointerException on SELECTs)
-- ALTER CLASS PumpUp SUPERCLASS ORestricted
-- TODO: change superclass to ORestricted
ALTER CLASS V SUPERCLASS PumpUp
ALTER CLASS E SUPERCLASS PumpUp

-- make OUser and ORole Vertices
ALTER CLASS OIdentity SUPERCLASS V

-- vertex classes
CREATE CLASS ActivityLog EXTENDS V
CREATE CLASS Comment EXTENDS V
CREATE CLASS Exercise EXTENDS V
CREATE CLASS ExerciseVariation EXTENDS V
CREATE CLASS Follow EXTENDS V
CREATE CLASS Hashtag EXTENDS V
CREATE CLASS Invite EXTENDS V
CREATE CLASS Like EXTENDS V
CREATE CLASS LogHashtag EXTENDS V
CREATE CLASS Notification EXTENDS V
CREATE CLASS PromoCode EXTENDS V
CREATE CLASS Post EXTENDS V
CREATE CLASS Settings EXTENDS V
CREATE CLASS Subscription EXTENDS V
CREATE CLASS Tip EXTENDS V
CREATE CLASS WeightLog EXTENDS V
CREATE CLASS Workout EXTENDS V
CREATE CLASS WorkoutExercise EXTENDS V
CREATE CLASS WorkoutExerciseLog EXTENDS V
CREATE CLASS WorkoutLog EXTENDS V
CREATE CLASS WorkoutSchedule EXTENDS V
CREATE CLASS WorkoutSection EXTENDS V
CREATE CLASS WorkoutSectionLog EXTENDS V

-- edge classes
-- pointer
CREATE CLASS Logged EXTENDS E
CREATE CLASS HasComment EXTENDS E
CREATE CLASS Commented EXTENDS E
CREATE CLASS WasPosted EXTENDS E
CREATE CLASS Posted EXTENDS E
CREATE CLASS WasPosted EXTENDS E
CREATE CLASS HasData EXTENDS E
CREATE CLASS Claimed EXTENDS E
CREATE CLASS Logged EXTENDS E
CREATE CLASS Built EXTENDS E
CREATE CLASS HasExercise EXTENDS E
CREATE CLASS BelongsToSection EXTENDS E
CREATE CLASS WasLogged EXTENDS E
CREATE CLASS BelongsToWorkoutSectionLog EXTENDS E
CREATE CLASS Logged EXTENDS E
CREATE CLASS Schedules EXTENDS E
CREATE CLASS BelongsToWorkout EXTENDS E
CREATE CLASS BelongsToWorkoutLog EXTENDS E
CREATE CLASS WasLogged EXTENDS E
-- class
CREATE CLASS HasVariation EXTENDS E
CREATE CLASS HasHashtag EXTENDS E
CREATE CLASS Follows EXTENDS E
CREATE CLASS Likes EXTENDS E

-- OUser
DELETE FROM OUser
CREATE PROPERTY OUser.username STRING
CREATE INDEX OUser.username UNIQUE

```

And this succeeds
```sql
-- create and connect to database
-- test
DROP DATABASE remote:localhost/pumpup root pass plocal
CREATE DATABASE remote:localhost/pumpup root pass plocal graph
CONNECT remote:localhost/pumpup root pass


-- set datetimeformat to match parse (and javascript)
ALTER DATABASE DATETIMEFORMAT yyyy-MM-dd'T'HH:mm:ss.SSS'Z'

-- enable counting of graph edges
ALTER DATABASE CUSTOM useLightweightEdges=false

-- abstract vertex class
CREATE CLASS PumpUp ABSTRACT
CREATE PROPERTY PumpUp.objectId STRING
CREATE INDEX PumpUp.objectId UNIQUE_HASH_INDEX
CREATE PROPERTY PumpUp.createdAt DATETIME
CREATE PROPERTY PumpUp.updatedAt DATETIME
CREATE INDEX PumpUp.updatedAt NOTUNIQUE
CREATE PROPERTY PumpUp.ACL EMBEDDEDMAP EMBEDDEDMAP
CREATE PROPERTY PumpUp.replacedACL BOOLEAN
CREATE INDEX PumpUp.replacedACL NOTUNIQUE_HASH_INDEX

-- record level security (TURNED OFF BECAUSE OF ORIENTO NullPointerException on SELECTs)
-- ALTER CLASS PumpUp SUPERCLASS ORestricted
-- TODO: change superclass to ORestricted
ALTER CLASS V SUPERCLASS PumpUp
ALTER CLASS E SUPERCLASS PumpUp

-- make OUser and ORole Vertices
ALTER CLASS OIdentity SUPERCLASS V

-- vertex classes
CREATE CLASS ActivityLog EXTENDS V
CREATE CLASS Comment EXTENDS V
CREATE CLASS Exercise EXTENDS V
CREATE CLASS ExerciseVariation EXTENDS V
CREATE CLASS Follow EXTENDS V
CREATE CLASS Hashtag EXTENDS V
CREATE CLASS Invite EXTENDS V
CREATE CLASS Like EXTENDS V
CREATE CLASS LogHashtag EXTENDS V
CREATE CLASS Notification EXTENDS V
CREATE CLASS PromoCode EXTENDS V
CREATE CLASS Post EXTENDS V
CREATE CLASS Settings EXTENDS V
CREATE CLASS Subscription EXTENDS V
CREATE CLASS Tip EXTENDS V
CREATE CLASS WeightLog EXTENDS V
CREATE CLASS Workout EXTENDS V
CREATE CLASS WorkoutExercise EXTENDS V
CREATE CLASS WorkoutExerciseLog EXTENDS V
CREATE CLASS WorkoutLog EXTENDS V
CREATE CLASS WorkoutSchedule EXTENDS V
CREATE CLASS WorkoutSection EXTENDS V
CREATE CLASS WorkoutSectionLog EXTENDS V

-- edge classes
-- pointer
CREATE CLASS Logged EXTENDS E
CREATE CLASS HasComment EXTENDS E
CREATE CLASS Commented EXTENDS E
CREATE CLASS WasPosted EXTENDS E
CREATE CLASS Posted EXTENDS E
CREATE CLASS HasData EXTENDS E
CREATE CLASS Claimed EXTENDS E
CREATE CLASS Built EXTENDS E
CREATE CLASS HasExercise EXTENDS E
CREATE CLASS BelongsToSection EXTENDS E
CREATE CLASS WasLogged EXTENDS E
CREATE CLASS BelongsToWorkoutSectionLog EXTENDS E
CREATE CLASS Schedules EXTENDS E
CREATE CLASS BelongsToWorkout EXTENDS E
CREATE CLASS BelongsToWorkoutLog EXTENDS E
-- class
CREATE CLASS HasVariation EXTENDS E
CREATE CLASS HasHashtag EXTENDS E
CREATE CLASS Follows EXTENDS E
CREATE CLASS Likes EXTENDS E

-- OUser
DELETE FROM OUser
CREATE PROPERTY OUser.username STRING
CREATE INDEX OUser.username UNIQUE

```

**Comment by luigidellaquila** [comment]
comments with -- are currently not supported, please use /* comment */ syntax instead

Closing

Thanks

Luigi
