### ISSUE TITLE
Tomcat redeploy using OrientGraphFactory

### ISSUE THREAD

**Issue by GerardSoleCa** [orientechnologies/orientdb#2607]
Hello,

I'm having issues when my CI server redeploys the webapp in a Tomcat servlet container.

What I've do and tested is create a ServletContextListener which on initialization starts the persistance layer by executing the following methods:

``` java
private OrientGraphFactory graphDB;
private OrientGraphFactory oauthDB;
[....]
OGlobalConfiguration.STORAGE_KEEP_OPEN.setValue(false);
String orientdbHome = this.cfg.getEnvirontment().getOrientDBHOME();
System.setProperty("ORIENTDB_HOME", orientdbHome);
String url = this.cfg.getEnvirontment().getOrientDBDatastore();
String oauthDbURL = this.cfg.getEnvirontment().getOrientDBOAuth();
graphDB = new OrientGraphFactory("plocal:" + orientdbHome + "/databases/" + url).setupPool(1, 10);
oauthDB = new OrientGraphFactory("plocal:" + orientdbHome + "/databases/" + oauthDbURL).setupPool(1, 10);
```

Then, on redeploy the contextDestroyedMethod calls the persistence close function:

``` java
graphDB.close();
oauth.close();
```

I use the db like the following snippet. I think thats the proper way to use the graphFactory.

``` java
OrientGraph graph = graphDb.getTx();
        try {
            A3HashMap<String, Object> prop = new A3HashMap<String, Object>();
            prop.put(User.ID, u.getId());
            prop.put(User.NAME, u.getName());
            prop.put(User.EMAIL, u.getEmail());
            prop.put(User.PASSWORD, PasswordUtil.encryptPassword(password));
            prop.put(User.PROVIDER, u.getProvider().ordinal());
            prop.put(User.ENABLED, u.isEnabled());
            prop.put(User.TIMESTAMP, u.getTimestamp());
            prop.put(User.CREATION_DATE, u.getCreationDate());

            prop.cleanNullValues();

            graph.addVertex(A3DBClasses.USER, prop);
        } catch (OValidationException e) {
        } finally {
            graph.shutdown();
        }
```

Thanks in advance!
Gerard.

PS: This is the log from tomcat when trying to redeploy:

``` java
###################################   
Destroying context
###################################


jul 22, 2014 9:02:19 PM org.apache.catalina.loader.WebappClassLoader clearReferencesThreads
Grave: The web application [/aaaida-server] appears to have started a thread named [Timer-1] but has failed to stop it. This is very likely to create a memory leak.
jul 22, 2014 9:02:19 PM org.apache.catalina.loader.WebappClassLoader clearReferencesThreads
Grave: The web application [/aaaida-server] appears to have started a thread named [OrientDB MemoryWatchDog] but has failed to stop it. This is very likely to create a memory leak.
jul 22, 2014 9:02:19 PM org.apache.catalina.loader.WebappClassLoader clearReferencesThreads
Grave: The web application [/aaaida-server] appears to have started a thread named [OrientDB WAL Flush Task (aaaida-db)] but has failed to stop it. This is very likely to create a memory leak.
jul 22, 2014 9:02:19 PM org.apache.catalina.loader.WebappClassLoader clearReferencesThreads
Grave: The web application [/aaaida-server] appears to have started a thread named [OrientDB WAL Flush Task (oauth-db)] but has failed to stop it. This is very likely to create a memory leak.
jul 22, 2014 9:02:19 PM org.apache.catalina.loader.WebappClassLoader clearReferencesThreads
Grave: The web application [/aaaida-server] appears to have started a thread named [OrientDB WAL Flush Task (aaaida-db)] but has failed to stop it. This is very likely to create a memory leak.
jul 22, 2014 9:02:19 PM org.apache.catalina.loader.WebappClassLoader clearReferencesThreads
Grave: The web application [/aaaida-server] appears to have started a thread named [Thread-21] but has failed to stop it. This is very likely to create a memory leak.
jul 22, 2014 9:02:19 PM org.apache.catalina.loader.WebappClassLoader clearReferencesThreads
Grave: The web application [/aaaida-server] appears to have started a thread named [OrientDB Write Cache Flush Task (aaaida-db)] but has failed to stop it. This is very likely to create a memory leak.
jul 22, 2014 9:02:20 PM org.apache.catalina.startup.HostConfig checkResources
INFO: Undeploying context [/aaaida-server]
jul 22, 2014 9:02:21 PM org.apache.catalina.startup.HostConfig deployWAR
INFO: Deploying web application archive /var/lib/tomcat7/webapps/aaaida-server.war
Starting context
jul 22, 2014 9:02:30 PM org.apache.catalina.core.StandardContext startInternal
Grave: Error listenerStart
jul 22, 2014 9:02:30 PM org.apache.catalina.core.StandardContext startInternal
Grave: Context [/aaaida-server] startup failed due to previous errors
###################################   
Destroying context
###################################


jul 22, 2014 9:02:31 PM org.apache.catalina.loader.WebappClassLoader clearReferencesThreads
Grave: The web application [/aaaida-server] appears to have started a thread named [Timer-2] but has failed to stop it. This is very likely to create a memory leak.
jul 22, 2014 9:02:31 PM org.apache.catalina.loader.WebappClassLoader clearReferencesThreads
Grave: The web application [/aaaida-server] appears to have started a thread named [OrientDB MemoryWatchDog] but has failed to stop it. This is very likely to create a memory leak.
jul 22, 2014 9:02:38 PM org.apache.catalina.loader.WebappClassLoader loadClass
INFO: Illegal access: this web application instance has been stopped already.  Could not load java.lang.management.MemoryMXBean.  The eventual following stack trace is caused by an error thrown for debugging purposes as well as to attempt to terminate the thread which caused the illegal access, and has no functional impact.
java.lang.IllegalStateException
        at org.apache.catalina.loader.WebappClassLoader.loadClass(WebappClassLoader.java:1597)
        at org.apache.catalina.loader.WebappClassLoader.loadClass(WebappClassLoader.java:1556)
        at com.orientechnologies.orient.core.memory.OMemoryWatchDog$3.run(OMemoryWatchDog.java:163)
        at java.util.TimerThread.mainLoop(Timer.java:555)
        at java.util.TimerThread.run(Timer.java:505)

jul 22, 2014 9:02:38 PM org.apache.catalina.loader.WebappClassLoader loadClass
INFO: Illegal access: this web application instance has been stopped already.  Could not load java.lang.management.MemoryUsage.  The eventual following stack trace is caused by an error thrown for debugging purposes as well as to attempt to terminate the thread which caused the illegal access, and has no functional impact.
java.lang.IllegalStateException
        at org.apache.catalina.loader.WebappClassLoader.loadClass(WebappClassLoader.java:1597)
        at org.apache.catalina.loader.WebappClassLoader.loadClass(WebappClassLoader.java:1556)
        at com.orientechnologies.orient.core.memory.OMemoryWatchDog$3.run(OMemoryWatchDog.java:164)
        at java.util.TimerThread.mainLoop(Timer.java:555)
        at java.util.TimerThread.run(Timer.java:505)








jul 22, 2014 9:03:16 PM org.apache.catalina.util.LifecycleBase stop
INFO: The stop() method was called on component [StandardEngine[Catalina].StandardHost[localhost].StandardContext[/aaaida-server]] after stop() had already been called. The second call will be ignored.
jul 22, 2014 9:03:17 PM org.apache.catalina.startup.HostConfig checkResources
INFO: Undeploying context [/aaaida-server]
jul 22, 2014 9:03:17 PM org.apache.catalina.startup.HostConfig deployWAR
INFO: Deploying web application archive /var/lib/tomcat7/webapps/aaaida-server.war
Starting context
jul 22, 2014 9:03:26 PM org.apache.catalina.core.StandardContext startInternal
Grave: Error listenerStart
jul 22, 2014 9:03:26 PM org.apache.catalina.core.StandardContext startInternal
Grave: Context [/aaaida-server] startup failed due to previous errors

```

**Comment by skwidge** [comment]
I'm still seeing this same issue with version 2.1.10. I'm running OrientDB embedded (plocal) in a Tomcat web app using SpringMVC.

I'm using Ivy for dependencies:
```
	<dependencies defaultconf="*->*,!sources,!javadoc">
		<dependency org="com.fasterxml.jackson.core" name="jackson-databind" rev="latest.release" />
		<dependency org="org.springframework" name="spring-context" rev="latest.release" />
		<dependency org="org.springframework" name="spring-webmvc" rev="latest.release" />
		<exclude org="com.ashtonit" module="odbresource" />
		<exclude org="javax.servlet" />
	</dependencies>
```

And https://github.com/skwidge/OdbResource/releases/tag/v2.0.1 in the apache-tomcat/lib directory.

Tomcat is version 8.0

```
2016-02-29 21:31:12:951 INFO  A valid shutdown command was received via the shutdown port. Stopping the Server instance. [StandardServer]
2016-02-29 21:31:12:952 INFO  Pausing ProtocolHandler ["http-nio-8080"] [Http11NioProtocol]
2016-02-29 21:31:12:955 INFO  Pausing ProtocolHandler ["ajp-nio-8009"] [AjpNioProtocol]
2016-02-29 21:31:13:006 INFO  Stopping service Catalina [StandardService]
2016-02-29 21:31:13:018 INFO  Destroying Spring FrameworkServlet 'dispatcher' [[/MyWebApp]]
2016-02-29 21:31:13:028 WARNI The web application [MyWebApp] appears to have started a thread named [OrientDB WAL Flush Task (tm)] but has failed to stop it. This is very likely to create a memory leak. Stack trace of thread:
 sun.misc.Unsafe.park(Native Method)
 java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215)
 java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2078)
 java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:1093)
 java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:809)
 java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1067)
 java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1127)
 java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
 java.lang.Thread.run(Thread.java:745) [WebappClassLoaderBase]
2016-02-29 21:31:13:028 WARNI The web application [MyWebApp] appears to have started a thread named [OrientDB Write Cache Flush Task (tm)] but has failed to stop it. This is very likely to create a memory leak. Stack trace of thread:
 sun.misc.Unsafe.park(Native Method)
 java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215)
 java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2078)
 java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:1093)
 java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:809)
 java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1067)
 java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1127)
 java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
 java.lang.Thread.run(Thread.java:745) [WebappClassLoaderBase]
2016-02-29 21:31:13:035 INFO  Stopping ProtocolHandler ["http-nio-8080"] [Http11NioProtocol]
2016-02-29 21:31:13:037 INFO  Stopping ProtocolHandler ["ajp-nio-8009"] [AjpNioProtocol]
2016-02-29 21:31:13:043 INFO  Destroying ProtocolHandler ["http-nio-8080"] [Http11NioProtocol]
2016-02-29 21:31:13:044 INFO  Destroying ProtocolHandler ["ajp-nio-8009"] [AjpNioProtocol]
```
