### ISSUE TITLE
ClassCastException when trying to get ORecordBytes with OrientDB via Graph API

### ISSUE THREAD

**Issue by lvca** [orientechnologies/orientdb#2643]
I tried to use OrientDB to store images/byte data and followed this tutorial: Store it with ORecordBytes (I chose the "Store it with ORecordBytes" approach").

Storing the data with the following code doesn't seem to cause any trouble:

``` java
   Vertex vertex = db.addVertex("class:items");
   ...
   ORecordBytes imageRecord = new ORecordBytes(stream.toByteArray());
   imageRecord.save();
   vertex.setProperty("image", imageRecord);
   ...
   db.commit();
```

However, when I attempt to retrieve the data like this:

``` java
    ORecordBytes imageRecord = vertex.getProperty("image");
```

... I get this for the line above:

Exception in thread "main" java.lang.ClassCastException: com.orientechnologies.orient.core.record.impl.ORecordBytes cannot be cast to com.orientechnologies.orient.core.record.impl.ODocument
at com.tinkerpop.blueprints.impls.orient.OrientBaseGraph.getElement(OrientBaseGraph.java:1145)
at com.tinkerpop.blueprints.impls.orient.OrientElement.getProperty(OrientElement.java:186)
at service.database.DAO.OrientDBGraphAPIItemDAO.vertexToItem(OrientDBGraphAPIItemDAO.java:154)
at service.database.DAO.OrientDBGraphAPIItemDAO.create(OrientDBGraphAPIItemDAO.java:68)
at testing.TestApplication.main(TestApplication.java:69)
I don't really see at which point I am making a cast to ODocument but I don't know the internals of OrientDB. As the tutorial is written for the Document API I am wondering if that could be the cause? Or am I just missing something else?

**Comment by Maiakov** [comment]
have the same problem
