### ISSUE TITLE
OClass.setAbstract(false) has side effect that changes OClass.defaultClusterID and causes OSchemaException on ODocument.save()

### ISSUE THREAD

**Issue by bodymindarts** [orientechnologies/orientdb#2718]
ODatabaseDocumentTx db = new ODatabaseDocumentTx("plocal:testDB");
		db.create();
		OSchema schema = db.getMetadata().getSchema();
		OClass someClass = schema.createClass("SomeClass");

		int beforeId = someClass.getDefaultClusterId();
		someClass.setAbstract(false);
		int afterId = someClass.getDefaultClusterId();

Here beforeId != aterId
afterId will be the default clusterID

When trying to save an instance of "SomeClass"

		ODocument doc = db.newInstance("SomeClass");
		doc.field("name", "myname");
		doc.save();

the following exception is thrown:

com.orientechnologies.orient.core.exception.OSchemaException: Record saved into cluster default should be saved with class null but saved with class SomeClass
	at com.orientechnologies.orient.core.db.record.ODatabaseRecordAbstract.checkRecordClass(ODatabaseRecordAbstract.java:1552)
	at com.orientechnologies.orient.core.db.record.ODatabaseRecordAbstract.executeSaveRecord(ODatabaseRecordAbstract.java:1099)
	at com.orientechnologies.orient.core.tx.OTransactionNoTx.saveRecord(OTransactionNoTx.java:79)
	at com.orientechnologies.orient.core.db.record.ODatabaseRecordTx.save(ODatabaseRecordTx.java:319)
	at com.orientechnologies.orient.core.db.record.ODatabaseRecordTx.save(ODatabaseRecordTx.java:40)
	at com.orientechnologies.orient.core.record.ORecordAbstract.save(ORecordAbstract.java:334)
	at com.orientechnologies.orient.core.record.impl.ODocument.save(ODocument.java:1458)
	at com.orientechnologies.orient.core.record.impl.ODocument.save(ODocument.java:1447)
	at com.orientechnologies.orient.core.record.impl.ODocument.save(ODocument.java:1436)

**Comment by lvca** [comment]
Already fixed in v2.1.0.
