### ISSUE TITLE
(Customer 39) OrientDB Server shutdown doesn't complete in a timely manner

### ISSUE THREAD

**Issue by lloydchang** [orientechnologies/orientdb#2736]
Hi @lvca @enisher @laa
CC @mattaylor @henryzhao81 @hcmwork @stuartking @pmoorhead

**Version:** OrientDB 1.7.4
**Frequency:** 5 incidents across 2 servers in 2 days

**Steps to Reproduce:**

```
service orientdb stop
```

which effectively executes...

```
cd "$ORIENTDB_DIR/bin"
/usr/bin/nohup ${ORIENTDB_DIR}/bin/shutdown.sh 1>${ORIENTDB_DIR}/log/orientdb.log 2> ${ORIENTDB_DIR}/log/orientdb.err
```

**INCIDENT 1** happened on Server 1 running OrientDB 1.7.4

```
+ service orientdb stop
Stopping OrientDB server daemon.. (running as root)
tail: /opt/orient/log/orientdb.err: file truncated
Aug 27, 2014 1:24:55 AM com.orientechnologies.common.log.OLogManager log
INFO: Loading configuration from: /opt/orient/config/orientdb-server-config.xml...
^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@
...
2014-08-27 01:24:56:003 WARN Reached maximum number of concurrent connections (1000), reject incoming connection from /10.224.176.11:36168 [OServerNetworkListener]
2014-08-27 01:25:00:910 WARN Low free heap memory (11%): reducing cached records number from 4 to 3 [ODefaultCache$OLowMemoryListener]
...
```

**INCIDENT 2** happened on Server 1 running OrientDB 1.7.4

```
+ service orientdb stop
Stopping OrientDB server daemon.. (running as root)
tail: /opt/orient/log/orientdb.err: file truncated
Aug 27, 2014 7:02:54 AM com.orientechnologies.common.log.OLogManager log
...
2014-08-27 07:02:55:485 INFO - storage: pharos... [Orient]
2014-08-27 07:02:55:488 WARN Repairing security structures... [OSecurityShared]
2014-08-27 07:02:55:488 WARN Repair completed [OSecurityShared]Please wait 5 seconds...
Please wait 5 seconds...
Please wait 5 seconds...
Please wait 5 seconds...
Please wait 5 seconds...
Please wait 5 seconds...
Please wait 5 seconds...
Please wait 5 seconds...

2014-08-27 07:03:34:551 SEVE    at java.lang.Thread.getStackTrace(Thread.java:1589)
    at com.orientechnologies.common.concur.resource.OSharedResourceAdaptive.acquireExclusiveLock(OSharedResourceAdaptive.java:119)
    at com.orientechnologies.common.concur.resource.OSharedResourceAdaptiveExternal.acquireExclusiveLock(OSharedResourceAdaptiveExternal.java:31)
    at com.orientechnologies.orient.core.storage.impl.local.paginated.OLocalPaginatedStorage.doClose(OLocalPaginatedStorage.java:1931)
    at com.orientechnologies.orient.core.storage.impl.local.paginated.OLocalPaginatedStorage.close(OLocalPaginatedStorage.java:340)
    at com.orientechnologies.orient.core.storage.OStorageAbstract.close(OStorageAbstract.java:106)
    at com.orientechnologies.orient.core.db.raw.ODatabaseRaw.close(ODatabaseRaw.java:516)
    at com.orientechnologies.orient.core.db.ODatabaseWrapperAbstract.close(ODatabaseWrapperAbstract.java:81)
...
```

**INCIDENT 3** happened on Server 1 running OrientDB 1.7.4

```
+ service orientdb stop
Stopping OrientDB server daemon.. (running as root)
tail: /opt/orient/log/orientdb.err: file truncated
Aug 27, 2014 9:20:06 AM com.orientechnologies.common.log.OLogManager log
INFO: Loading configuration from: /opt/orient/config/orientdb-server-config.xml...
java.net.ConnectException: Connection refused
    at java.net.PlainSocketImpl.socketConnect(Native Method)
    at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:339)
    at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:198)
    at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:182)
    at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
    at java.net.Socket.connect(Socket.java:579)
    at com.orientechnologies.orient.enterprise.channel.binary.OChannelBinaryAsynchClient.<init>(OChannelBinaryAsynchClient.java:77)
    at com.orientechnologies.orient.enterprise.channel.binary.OChannelBinaryAsynchClient.<init>(OChannelBinaryAsynchClient.java:57)
    at com.orientechnologies.orient.enterprise.channel.binary.OChannelBinaryAsynchClientSynch.<init>(OChannelBinaryAsynchClientSynch.java:32)
    at com.orientechnologies.orient.server.OServerShutdownMain.connect(OServerShutdownMain.java:103)
    at com.orientechnologies.orient.server.OServerShutdownMain.main(OServerShutdownMain.java:135)
java.net.ConnectException: Connection refused
    at java.net.PlainSocketImpl.socketConnect(Native Method)
    at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:339)
    at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:198)
    at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:182)
    at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
    at java.net.Socket.connect(Socket.java:579)
    at com.orientechnologies.orient.enterprise.channel.binary.OChannelBinaryAsynchClient.<init>(OChannelBinaryAsynchClient.java:77)
    at com.orientechnologies.orient.enterprise.channel.binary.OChannelBinaryAsynchClient.<init>(OChannelBinaryAsynchClient.java:57)
    at com.orientechnologies.orient.enterprise.channel.binary.OChannelBinaryAsynchClientSynch.<init>(OChannelBinaryAsynchClientSynch.java:32)
    at com.orientechnologies.orient.server.OServerShutdownMain.connect(OServerShutdownMain.java:103)
    at com.orientechnologies.orient.server.OServerShutdownMain.main(OServerShutdownMain.java:135)
java.net.ConnectException: Connection refused
    at java.net.PlainSocketImpl.socketConnect(Native Method)
    at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:339)
    at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:198)
    at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:182)
    at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
    at java.net.Socket.connect(Socket.java:579)
    at com.orientechnologies.orient.enterprise.channel.binary.OChannelBinaryAsynchClient.<init>(OChannelBinaryAsynchClient.java:77)
    at com.orientechnologies.orient.enterprise.channel.binary.OChannelBinaryAsynchClient.<init>(OChannelBinaryAsynchClient.java:57)
    at com.orientechnologies.orient.enterprise.channel.binary.OChannelBinaryAsynchClientSynch.<init>(OChannelBinaryAsynchClientSynch.java:32)
    at com.orientechnologies.orient.server.OServerShutdownMain.connect(OServerShutdownMain.java:103)
    at com.orientechnologies.orient.server.OServerShutdownMain.main(OServerShutdownMain.java:135)
java.net.ConnectException: Connection refused
    at java.net.PlainSocketImpl.socketConnect(Native Method)
    at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:339)
    at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:198)
    at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:182)
    at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
    at java.net.Socket.connect(Socket.java:579)
    at com.orientechnologies.orient.enterprise.channel.binary.OChannelBinaryAsynchClient.<init>(OChannelBinaryAsynchClient.java:77)
    at com.orientechnologies.orient.enterprise.channel.binary.OChannelBinaryAsynchClient.<init>(OChannelBinaryAsynchClient.java:57)
    at com.orientechnologies.orient.enterprise.channel.binary.OChannelBinaryAsynchClientSynch.<init>(OChannelBinaryAsynchClientSynch.java:32)
    at com.orientechnologies.orient.server.OServerShutdownMain.connect(OServerShutdownMain.java:103)
    at com.orientechnologies.orient.server.OServerShutdownMain.main(OServerShutdownMain.java:135)
java.net.ConnectException: Connection refused
    at java.net.PlainSocketImpl.socketConnect(Native Method)
    at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:339)
    at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:198)
    at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:182)
    at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
    at java.net.Socket.connect(Socket.java:579)
    at com.orientechnologies.orient.enterprise.channel.binary.OChannelBinaryAsynchClient.<init>(OChannelBinaryAsynchClient.java:77)
    at com.orientechnologies.orient.enterprise.channel.binary.OChannelBinaryAsynchClient.<init>(OChannelBinaryAsynchClient.java:57)
    at com.orientechnologies.orient.enterprise.channel.binary.OChannelBinaryAsynchClientSynch.<init>(OChannelBinaryAsynchClientSynch.java:32)
    at com.orientechnologies.orient.server.OServerShutdownMain.connect(OServerShutdownMain.java:103)
    at com.orientechnologies.orient.server.OServerShutdownMain.main(OServerShutdownMain.java:135)
java.net.ConnectException: Connection refused
    at java.net.PlainSocketImpl.socketConnect(Native Method)
    at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:339)
    at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:198)
    at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:182)
    at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
    at java.net.Socket.connect(Socket.java:579)
    at com.orientechnologies.orient.enterprise.channel.binary.OChannelBinaryAsynchClient.<init>(OChannelBinaryAsynchClient.java:77)
    at com.orientechnologies.orient.enterprise.channel.binary.OChannelBinaryAsynchClient.<init>(OChannelBinaryAsynchClient.java:57)
    at com.orientechnologies.orient.enterprise.channel.binary.OChannelBinaryAsynchClientSynch.<init>(OChannelBinaryAsynchClientSynch.java:32)
    at com.orientechnologies.orient.server.OServerShutdownMain.connect(OServerShutdownMain.java:103)
    at com.orientechnologies.orient.server.OServerShutdownMain.main(OServerShutdownMain.java:135)
java.net.ConnectException: Connection refused
    at java.net.PlainSocketImpl.socketConnect(Native Method)
    at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:339)
    at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:198)
    at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:182)
    at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
    at java.net.Socket.connect(Socket.java:579)
    at com.orientechnologies.orient.enterprise.channel.binary.OChannelBinaryAsynchClient.<init>(OChannelBinaryAsynchClient.java:77)
    at com.orientechnologies.orient.enterprise.channel.binary.OChannelBinaryAsynchClient.<init>(OChannelBinaryAsynchClient.java:57)
    at com.orientechnologies.orient.enterprise.channel.binary.OChannelBinaryAsynchClientSynch.<init>(OChannelBinaryAsynchClientSynch.java:32)
    at com.orientechnologies.orient.server.OServerShutdownMain.connect(OServerShutdownMain.java:103)
    at com.orientechnologies.orient.server.OServerShutdownMain.main(OServerShutdownMain.java:135)
...
```

**INCIDENT 4** happened on Server 1 running OrientDB 1.7.4

```
+ service orientdb stop
Stopping OrientDB server daemon.. (running as root)
tail: /opt/orient/log/orientdb.err: file truncated
Aug 27, 2014 9:33:11 AM com.orientechnologies.common.log.OLogManager log
INFO: Loading configuration from: /opt/orient/config/orientdb-server-config.xml...
java.net.ConnectException: Connection refused
    at java.net.PlainSocketImpl.socketConnect(Native Method)
    at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:339)
    at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:198)
    at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:182)
    at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
    at java.net.Socket.connect(Socket.java:579)
    at com.orientechnologies.orient.enterprise.channel.binary.OChannelBinaryAsynchClient.<init>(OChannelBinaryAsynchClient.java:77)
    at com.orientechnologies.orient.enterprise.channel.binary.OChannelBinaryAsynchClient.<init>(OChannelBinaryAsynchClient.java:57)
    at com.orientechnologies.orient.enterprise.channel.binary.OChannelBinaryAsynchClientSynch.<init>(OChannelBinaryAsynchClientSynch.java:32)
    at com.orientechnologies.orient.server.OServerShutdownMain.connect(OServerShutdownMain.java:103)
    at com.orientechnologies.orient.server.OServerShutdownMain.main(OServerShutdownMain.java:135)
...
```

**INCIDENT 5** happened on Server 2 running OrientDB 1.7.4

```
+ service orientdb stop
Stopping OrientDB server daemon.. (running as root)
Aug 28, 2014 6:56:22 PM com.orientechnologies.common.log.OLogManager log
INFO: Loading configuration from: /opt/orient/config/orientdb-server-config.xml...
java.net.ConnectException: Connection refused
        at java.net.PlainSocketImpl.socketConnect(Native Method)
        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:339)
        at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:198)
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:182)
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
        at java.net.Socket.connect(Socket.java:579)
        at com.orientechnologies.orient.enterprise.channel.binary.OChannelBinaryAsynchClient.<init>(OChannelBinaryAsynchClient.java:77)
        at com.orientechnologies.orient.enterprise.channel.binary.OChannelBinaryAsynchClient.<init>(OChannelBinaryAsynchClient.java:57)
        at com.orientechnologies.orient.enterprise.channel.binary.OChannelBinaryAsynchClientSynch.<init>(OChannelBinaryAsynchClientSynch.java:32)
        at com.orientechnologies.orient.server.OServerShutdownMain.connect(OServerShutdownMain.java:103)
        at com.orientechnologies.orient.server.OServerShutdownMain.main(OServerShutdownMain.java:135)
...
```

**Comment by publicocean0** [comment]
hi i found a problem with shutdown code introduced in orientdb. Surely it can create a lot of problems in a orientdb cllient hosting in more open system but also in server. 
The shutdown in orientdb are not handled directly using java shutdown hook but with SignalHandler. 
It gives more possibilities but gives also a side effect. The handlers is executed not following the right order in closing VM. 
the right order is .... before VM call all hooks installed, deregistring other handlers, close classes destroying data before to exit ... and then the database connections are closed. 
The connections to database might be closed in the ending , not in the beginning of shutdown. 
Now it is possible the connections are closed before the VM is completing to destroy data in the VM.

**Comment by lvca** [comment]
We used signals to catch any possible case to avoid to break the DB. This works well with server and usually clients. Are you using an App Server?

**Comment by publicocean0** [comment]
yes i m using orientdb in a server that is making a specific task .... all is ok but when the server is shutdown for any reason, it might save the status of specific running data, so the status can be realoaded correctly at startup. 
I added a hook ... but the first problem is i cant know in what order is executed ... so i solved it before patching java hooks handler ... now hooks is executed folling a priorityqueue. So it is executed before to  close other classes (as hanzelcast for example). Solved it remains the problem with orientdb ... when it try to save data it find the connection close anyway because signal handler dont follow hooks.  
Pratically the connections are closed before to all... before any hooks, but it might be closed in the ending ... granting the all the logic related a shutdown is executed correctly. 
I thought to modify OConnectionManager ... instead to command directly the shutdown when it received the signal ... it add a hook in the end of queue so orientdb shutdown will be executed at the end.

**Comment by dcarr178** [comment]
in orientdb version 2.1.1 the file bin/shutdown.sh does not work. The only thing that I can get to work is kill <pid>.

**Comment by lvca** [comment]
@dcarr178 Please could you open a new issue for that?

**Comment by dcarr178** [comment]
@lvca I dropped my db and started over which seemed to correct the problem so I cannot reproduce anymore. Will create a new issue if I can reproduce again. The weirdest part was the log file entry that said Error:null.
