### ISSUE TITLE
addVertex does not accept variables for it's class

### ISSUE THREAD

**Issue by kwoxer** [orientechnologies/orientdb#2745]
Well strange thing. If I say

```java
noTxGraph.addVertex("class:" + className, propertyName, propertyValue);
```
if doesn't work.

```java
Exception in thread "main" com.orientechnologies.orient.core.exception.OSchemaException: Found invalid class name. Character '%' cannot be used in class name.
	at com.orientechnologies.orient.core.metadata.schema.OSchemaShared.createClassInternal(OSchemaShared.java:340)
	at com.orientechnologies.orient.core.metadata.schema.OSchemaShared.createClass(OSchemaShared.java:314)
	at com.orientechnologies.orient.core.metadata.schema.OSchemaProxy.createClass(OSchemaProxy.java:77)
	at com.tinkerpop.blueprints.impls.orient.OrientElement$1.call(OrientElement.java:469)
	at com.tinkerpop.blueprints.impls.orient.OrientElement$1.call(OrientElement.java:465)
	at com.tinkerpop.blueprints.impls.orient.OrientBaseGraph.executeOutsideTx(OrientBaseGraph.java:1658)
	at com.tinkerpop.blueprints.impls.orient.OrientElement.checkForClassInSchema(OrientElement.java:464)
	at com.tinkerpop.blueprints.impls.orient.OrientVertex.<init>(OrientVertex.java:54)
	at com.tinkerpop.blueprints.impls.orient.OrientBaseGraph.addVertex(OrientBaseGraph.java:425)
	at de.mapegy.graph.orientdb.Orient_CreateEdge.insertVertex(Orient_CreateEdge.java:53)
	at de.mapegy.graph.orientdb.Orient_CreateEdge.createTestDataset(Orient_CreateEdge.java:39)
	at de.mapegy.graph.orientdb.Orient_CreateEdge.main(Orient_CreateEdge.java:34)
```
But if I do it this way. Without a variable it works:
```java
noTxGraph.addVertex("class:Person", propertyName, propertyValue);
```
className is just a normal String

Btw this does also work:
```
noTxGraph.addVertex("class:" + "Person", propertyName, propertyValue);
```

**Comment by lvca** [comment]
The right syntax is:

    noTxGraph.addVertex(className, propertyName, propertyValue);
