### ISSUE TITLE
skip and limit cannot be set via positional parameters?

### ISSUE THREAD

**Issue by ghost** [orientechnologies/orientdb#2801]
Both:
db.query(new OSQLSynchQuery<ODocument>("select from Person skip ? limit ?"), 0, 20)
db.command(new OSQLSynchQuery<ODocument>("select from Person skip ? limit ?")).execute(0, 20)

result in an exception. I would expect that it would be possible to set these values via positional parameters. The exception is:

Caught: com.orientechnologies.orient.core.sql.OCommandSQLParsingException: Error on parsing command at position #23: Invalid SKIP value setted to '?' but it should be a valid positive integer. Example: SKIP 10
Command: select from Person skip ? limit ?
-------------------------------^
com.orientechnologies.orient.core.sql.OCommandSQLParsingException: Error on parsing command at position #23: Invalid SKIP value setted to '?' but it should be a valid positive integer. Example: SKIP 10
Command: select from Person skip ? limit ?
-------------------------------^
	at com.orientechnologies.orient.core.sql.OCommandExecutorSQLAbstract.throwParsingException(OCommandExecutorSQLAbstract.java:83)
	at com.orientechnologies.orient.core.sql.OCommandExecutorSQLResultsetAbstract.parseSkip(OCommandExecutorSQLResultsetAbstract.java:277)
	at com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.parse(OCommandExecutorSQLSelect.java:211)
	at com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.parse(OCommandExecutorSQLSelect.java:78)
	at com.orientechnologies.orient.core.sql.OCommandExecutorSQLDelegate.parse(OCommandExecutorSQLDelegate.java:52)
	at com.orientechnologies.orient.core.sql.OCommandExecutorSQLDelegate.parse(OCommandExecutorSQLDelegate.java:33)
	at com.orientechnologies.orient.core.storage.OStorageEmbedded.command(OStorageEmbedded.java:81)
	at com.orientechnologies.orient.core.sql.query.OSQLQuery.run(OSQLQuery.java:69)
	at com.orientechnologies.orient.core.sql.query.OSQLSynchQuery.run(OSQLSynchQuery.java:80)
	at com.orientechnologies.orient.core.query.OQueryAbstract.execute(OQueryAbstract.java:29)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.command(ONetworkProtocolBinary.java:1181)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.executeRequest(ONetworkProtocolBinary.java:340)
	at com.orientechnologies.orient.server.network.protocol.binary.OBinaryNetworkProtocolAbstract.execute(OBinaryNetworkProtocolAbstract.java:169)
	at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:45)

**Comment by luigidellaquila** [comment]
fixed in 2.1 (develop branch)
