### ISSUE TITLE
(Customer ID = 53) ODB doesn't correctly create vertex if started in distributed mode

### ISSUE THREAD

**Issue by carloprad** [orientechnologies/orientdb#2836]
First, my environment:
CentOS 6.5   64bit
Oracle JDK 1.7.60   64bit
ODB 1.7.9

I created a new database, having started ODB server in distributed mode, but without a peer.

In the use case I report here, we are creating a new KShape vertex. 
The class KShape extends KIdentifiable, hence contains a mandatory property named "guid".

When our application tries to insert a new vertex, ODB replies with this exception:

```
Cannot commit new folder to gDB
com.orientechnologies.orient.server.distributed.ODistributedException: Error on execution distributed CREATE_RECORD
        at com.orientechnologies.orient.server.distributed.ODistributedStorage.createRecord(ODistributedStorage.java:361)
        at com.orientechnologies.orient.core.db.raw.ODatabaseRaw.save(ODatabaseRaw.java:271)
        at com.orientechnologies.orient.core.db.record.ODatabaseRecordAbstract.executeSaveRecord(ODatabaseRecordAbstract.java:1136)
        at com.orientechnologies.orient.core.tx.OTransactionOptimistic.addRecord(OTransactionOptimistic.java:311)
        at com.orientechnologies.orient.core.tx.OTransactionOptimistic.saveRecord(OTransactionOptimistic.java:250)
        at com.orientechnologies.orient.core.db.record.ODatabaseRecordTx.save(ODatabaseRecordTx.java:322)
        at com.orientechnologies.orient.core.db.record.ODatabaseRecordTx.save(ODatabaseRecordTx.java:303)
        at com.orientechnologies.orient.core.db.record.ODatabaseRecordTx.save(ODatabaseRecordTx.java:40)
        at com.orientechnologies.orient.core.serialization.serializer.record.string.ORecordSerializerCSVAbstract.linkToStream(ORecordSerializerCSVAbstract.java:97)
        at com.orientechnologies.orient.core.serialization.serializer.record.string.ORecordSerializerCSVAbstract.fieldToStream(ORecordSerializerCSVAbstract.java:351)
        at com.orientechnologies.orient.core.serialization.serializer.record.string.ORecordSerializerSchemaAware2CSV.toString(ORecordSerializerSchemaAware2CSV.java:495)
        at com.orientechnologies.orient.core.serialization.serializer.record.string.ORecordSerializerStringAbstract.toStream(ORecordSerializerStringAbstract.java:673)
        at com.orientechnologies.orient.core.serialization.serializer.record.string.ORecordSerializerSchemaAware2CSV.toStream(ORecordSerializerSchemaAware2CSV.java:258)
        at com.orientechnologies.orient.core.record.ORecordSchemaAwareAbstract.toStream(ORecordSchemaAwareAbstract.java:420)
        at com.orientechnologies.orient.core.record.ORecordSchemaAwareAbstract.toStream(ORecordSchemaAwareAbstract.java:415)
        at com.orientechnologies.orient.core.record.impl.ODocument.toStream(ODocument.java:423)
        at com.orientechnologies.orient.core.db.record.ODatabaseRecordAbstract.executeSaveRecord(ODatabaseRecordAbstract.java:1087)
        at com.orientechnologies.orient.core.tx.OTransactionOptimistic.addRecord(OTransactionOptimistic.java:311)
        at com.orientechnologies.orient.core.tx.OTransactionOptimistic.saveRecord(OTransactionOptimistic.java:250)
        at com.orientechnologies.orient.core.db.record.ODatabaseRecordTx.save(ODatabaseRecordTx.java:322)
        at com.orientechnologies.orient.core.db.record.ODatabaseRecordTx.save(ODatabaseRecordTx.java:303)
        at com.orientechnologies.orient.core.db.record.ODatabaseRecordTx.save(ODatabaseRecordTx.java:40)
        at com.orientechnologies.orient.core.serialization.serializer.record.string.ORecordSerializerCSVAbstract.linkToStream(ORecordSerializerCSVAbstract.java:97)
        at com.orientechnologies.orient.core.serialization.serializer.record.string.ORecordSerializerCSVAbstract.fieldToStream(ORecordSerializerCSVAbstract.java:351)
        at com.orientechnologies.orient.core.serialization.serializer.record.string.ORecordSerializerSchemaAware2CSV.toString(ORecordSerializerSchemaAware2CSV.java:495)
        at com.orientechnologies.orient.core.serialization.serializer.record.string.ORecordSerializerStringAbstract.toStream(ORecordSerializerStringAbstract.java:673)
        at com.orientechnologies.orient.core.serialization.serializer.record.string.ORecordSerializerSchemaAware2CSV.toStream(ORecordSerializerSchemaAware2CSV.java:258)
        at com.orientechnologies.orient.core.record.ORecordSchemaAwareAbstract.toStream(ORecordSchemaAwareAbstract.java:420)
        at com.orientechnologies.orient.core.record.ORecordSchemaAwareAbstract.toStream(ORecordSchemaAwareAbstract.java:415)
        at com.orientechnologies.orient.core.record.impl.ODocument.toStream(ODocument.java:423)
        at com.orientechnologies.orient.server.distributed.ODistributedStorage.commit(ODistributedStorage.java:637)
        at com.orientechnologies.orient.core.tx.OTransactionOptimistic.doCommit(OTransactionOptimistic.java:469)
        at com.orientechnologies.orient.core.tx.OTransactionOptimistic.commit(OTransactionOptimistic.java:148)
        at com.orientechnologies.orient.core.db.record.ODatabaseRecordTx.commit(ODatabaseRecordTx.java:142)
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.commit(ODatabaseDocumentTx.java:511)
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.commit(ODatabaseDocumentTx.java:503)
        at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.commit(ONetworkProtocolBinary.java:1096)
        at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.executeRequest(ONetworkProtocolBinary.java:344)
        at com.orientechnologies.orient.server.network.protocol.binary.OBinaryNetworkProtocolAbstract.execute(OBinaryNetworkProtocolAbstract.java:169)
        at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:45)
Caused by: com.orientechnologies.orient.core.exception.OValidationException: The field 'KIdentifiable.guid' is mandatory, but not found on record: KShape#138:-2 v0
        at com.orientechnologies.orient.core.record.ORecordSchemaAwareAbstract.validateField(ORecordSchemaAwareAbstract.java:70)
        at com.orientechnologies.orient.core.record.ORecordSchemaAwareAbstract.validate(ORecordSchemaAwareAbstract.java:338)
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.save(ODatabaseDocumentTx.java:436)
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.save(ODatabaseDocumentTx.java:56)
        at com.orientechnologies.orient.core.record.ORecordAbstract.save(ORecordAbstract.java:335)
        at com.orientechnologies.orient.core.record.impl.ODocument.save(ODocument.java:1439)
        at com.orientechnologies.orient.core.record.impl.ODocument.save(ODocument.java:58)
        at com.orientechnologies.orient.server.distributed.task.OCreateRecordTask.execute(OCreateRecordTask.java:65)
        at com.orientechnologies.orient.server.hazelcast.OHazelcastPlugin.executeOnLocalNode(OHazelcastPlugin.java:681)
        at com.orientechnologies.orient.server.hazelcast.OHazelcastDistributedDatabase.onMessage(OHazelcastDistributedDatabase.java:538)
        at com.orientechnologies.orient.server.hazelcast.OHazelcastDistributedDatabase$1.run(OHazelcastDistributedDatabase.java:257)
        at java.lang.Thread.run(Thread.java:745)
```

So it seems that we didn't provide the "guid" value, but we actually did that properly (it ALWAYS works fine in stand-alone mode) and our tcpdump output confirms that:

```
11:09:54.797731 IP localhost.60608 > localhost.kofax-svr: Flags [P.], seq 583:2492, ack 9238, win 256, options [nop,nop,TS val 1731819239 ecr 1731819199], length 1909
E.....@.@.a...........  x.$^................
g9v.g9v.<.....................d...RKShape@guid:"b469ec4c12a04e22886b8d18069de863",type:"document",color:"#00ff00",name:"abc",in_HasShape:#27:0,out_HasShapeSection:#140:-3,out_HasProperty                     Descriptor:#131:-4                                                                                                                                                                                              ............d...
....KDomain@guid:"e7c614b4de334992abd0392c972228f8",out_HasGroup:%A40p655nBU/glfr4TEJrAsQAAAACAC0AAAAAAAAAAAAtAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAA==;,type:"O",name:"Test",description:"                     Dominio di Test",out_AccessContract:#58:0,out_HasTrashCan:#28:0,out_HasOrganizationInfo:#47:0,out_HasDrive:#36:0,in_PrefersDomain:#48:0,in_CanEnterDomain:#31:0,out_HasList:#168:0,out_Has                     Shape:#138:-2
```

We're using the TinkerPop API and the java code that generates this action looks like the following.
As I wrote above, the same code works well if ODB is started in standalone mode:

```
/*
 oGraph contains an instance of OrientGraph
 className contains "class:KShape" ; 
 params contains a few properties, including the guid
*/

OrientVertex result = oGraph.addVertex(className, params);
result.save();

```

**Comment by carloprad** [comment]
Hi @lvca ,
I'm sorry for the missed reply, but I was sick for a while...
I've just tried with the latest snapshot, and the test passed as expected.
Thanks!

**Comment by lvca** [comment]
Great ;-)

**Comment by lvca** [comment]
I mean, no great for your sickness :-) Great about the closed issue ;-)

**Comment by carloprad** [comment]
;-)
