### ISSUE TITLE
[Distributed embedded] ArrayOutOfBound on browsing a class

### ISSUE THREAD

**Issue by mdymczyk** [orientechnologies/orientdb#2852]
Cluster config: 1 node in distributed mode
Version: 1.7.7 (did not try on 2.0-M1 due to #2738)

Clean db with a schema, I open a connection, open the DB and try to browse for a class:

```java
try (ODatabaseDocumentTx db = new ODatabaseDocumentTx(dbLoc) {
  db.open(user, passwd);
  db.browseClass("myclazz");
}
```

And I get (randomly and very rarerly):

```java
java.lang.ArrayIndexOutOfBoundsException: 0
        at com.orientechnologies.orient.core.iterator.ORecordIteratorClusters.updateClusterRange(ORecordIteratorClusters.java:350) ~[orientdb-core-
1.7.7.jar:1.7.7]
        at com.orientechnologies.orient.core.iterator.ORecordIteratorClusters.config(ORecordIteratorClusters.java:361) ~[orientdb-core-1.7.7.jar:1.
7.7]
        at com.orientechnologies.orient.core.iterator.ORecordIteratorClass.<init>(ORecordIteratorClass.java:73) ~[orientdb-core-1.7.7.jar:1.7.7]
        at com.orientechnologies.orient.core.iterator.ORecordIteratorClass.<init>(ORecordIteratorClass.java:56) ~[orientdb-core-1.7.7.jar:1.7.7]
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.browseClass(ODatabaseDocumentTx.java:209) ~[orientdb-core-1.7.7.jar:1.
7.7]
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.browseClass(ODatabaseDocumentTx.java:197) ~[orientdb-core-1.7.7.jar:1.
7.7]
```

**Comment by JPMoresmau** [comment]
I'm getting the exact error on 2.0. I'm not even creating data, just the schema: vertex types and properties and indices. I systematically get after a few (around a 100) types:

Exception in thread "main" com.orientechnologies.orient.core.exception.OCommandExecutionException: Error on execution of command: sql.select count(*) from Index where name.type() not in ["STRING"] and name is not null
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.executeCommand(OAbstractPaginatedStorage.java:1182)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.command(OAbstractPaginatedStorage.java:1165)
	at com.orientechnologies.orient.core.command.OCommandRequestTextAbstract.execute(OCommandRequestTextAbstract.java:63)
	at com.orientechnologies.orient.core.metadata.schema.OClassImpl.checkPersistentPropertyType(OClassImpl.java:1646)
	at com.orientechnologies.orient.core.metadata.schema.OClassImpl.addPropertyInternal(OClassImpl.java:1351)
	at com.orientechnologies.orient.core.sql.OCommandExecutorSQLCreateProperty.execute(OCommandExecutorSQLCreateProperty.java:140)
	at com.orientechnologies.orient.core.sql.OCommandExecutorSQLDelegate.execute(OCommandExecutorSQLDelegate.java:64)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.executeCommand(OAbstractPaginatedStorage.java:1176)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.command(OAbstractPaginatedStorage.java:1165)
	at com.orientechnologies.orient.core.command.OCommandRequestTextAbstract.execute(OCommandRequestTextAbstract.java:63)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.command(ONetworkProtocolBinary.java:1180)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.executeRequest(ONetworkProtocolBinary.java:385)
	at com.orientechnologies.orient.server.network.protocol.binary.OBinaryNetworkProtocolAbstract.execute(OBinaryNetworkProtocolAbstract.java:216)
	at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:65)
Caused by: java.lang.ArrayIndexOutOfBoundsException: 1
	at com.orientechnologies.orient.core.iterator.ORecordIteratorClusters.updateClusterRange(ORecordIteratorClusters.java:362)
	at com.orientechnologies.orient.core.iterator.ORecordIteratorClusters.setRange(ORecordIteratorClusters.java:70)
	at com.orientechnologies.orient.core.sql.OCommandExecutorSQLResultsetAbstract.searchInClasses(OCommandExecutorSQLResultsetAbstract.java:446)
	at com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.searchInClasses(OCommandExecutorSQLSelect.java:761)
	at com.orientechnologies.orient.core.sql.OCommandExecutorSQLResultsetAbstract.assignTarget(OCommandExecutorSQLResultsetAbstract.java:193)
	at com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.assignTarget(OCommandExecutorSQLSelect.java:440)
	at com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.executeSearch(OCommandExecutorSQLSelect.java:422)
	at com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.execute(OCommandExecutorSQLSelect.java:393)
	at com.orientechnologies.orient.core.sql.OCommandExecutorSQLDelegate.execute(OCommandExecutorSQLDelegate.java:64)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.executeCommand(OAbstractPaginatedStorage.java:1176)
	... 13 more

the code runs wrapped in `graph.executeOutsideTx`

JP

**Comment by JPMoresmau** [comment]
I'm trying to narrow down a scenario that fails, I'll post code when I can.

**Comment by lvca** [comment]
Found the problem.

**Comment by lvca** [comment]
Without a test case I'm not sure if it's fixed. Please could you retry with 2.0.1-SNAPSHOT?

**Comment by JPMoresmau** [comment]
Still the same issue in orientdb-community-2.1-20150127.144608-13-distribution, but I see now that it's just been commited, so I suppose I need today's snapshot, not yesterday.

**Comment by JPMoresmau** [comment]
OK, confusion between 2.0.1 and 2.1 snapshots... I'll try with 2.0.1... Sorry...

**Comment by JPMoresmau** [comment]
Can confirm with orientdb-community-2.0.1-20150128.003628-6-distribution the issue is gone. Thanks a million!

**Comment by lvca** [comment]
Cool, thanks for reporting it.
