### ISSUE TITLE
ArrayIndexOutOfBound Exception when using binary protocol (Custom ID 39)

### ISSUE THREAD

**Issue by henryzhao81** [orientechnologies/orientdb#2953]
Switch to using testing 2.0 source code, I found a issue when I using Console which goes to binary protocol. Following are the cases:

create class tuser;
create class tgroup;
create property tuser.name STRING;
create property tuser.groups LINKSET tgroup;
create property tgroup.name STRING;
create property tgroup.memberUsers LINKSET tuser;
insert into tuser set name = 'test1';        //Inserted record 'tuser#105:0{name:test1} v1' 
insert into tuser set name = 'test2';        //Inserted record 'tuser#105:1{name:test1} v1'
insert into tuser set name = 'test3';        //Inserted record 'tuser#105:2{name:test1} v1'
insert into tuser set name = 'test4';        //Inserted record 'tuser#105:3{name:test1} v1'
insert into tuser set name = 'test5';        //Inserted record 'tuser#105:4{name:test1} v1'
insert into tuser set name = 'test6';        //Inserted record 'tuser#105:5{name:test1} v1'
insert into tuser set name = 'test7';        //Inserted record 'tuser#105:6{name:test1} v1'
insert into tuser set name = 'test8';        //Inserted record 'tuser#105:7{name:test1} v1'
insert into tuser set name = 'test9';        //Inserted record 'tuser#105:8{name:test1} v1'
insert into tgroup set name = 'testgroup1';  //Inserted record 'tgroup#107:0{name:testgroup1} v1' 
update #105:0 set groups = [#107:0];
update #107:0 set memberUsers = [#105:1,#105:2,#105:3,#105:4,#105:5,#105:6,#105:7,#105:8];

When I execute : select from #105:0, on server side it keep throw ArrayIndexOutOfBoundsException, it works fine when I execute on studio.
Error on iterating record collection
com.orientechnologies.orient.core.exception.ODatabaseException: Error on retrieving record #105:2
	at com.orientechnologies.orient.core.db.record.ODatabaseRecordAbstract.executeReadRecord(ODatabaseRecordAbstract.java:945)
	at com.orientechnologies.orient.core.tx.OTransactionNoTx.loadRecord(OTransactionNoTx.java:79)
	at com.orientechnologies.orient.core.db.record.ODatabaseRecordTx.load(ODatabaseRecordTx.java:264)
	at com.orientechnologies.orient.core.db.record.ODatabaseRecordTx.load(ODatabaseRecordTx.java:43)
	at com.orientechnologies.orient.core.id.ORecordId.getRecord(ORecordId.java:302)
	at com.orientechnologies.orient.core.db.record.OLazyRecordIterator.next(OLazyRecordIterator.java:75)
	at com.orientechnologies.orient.core.db.record.OLazyRecordIterator.next(OLazyRecordIterator.java:38)
	at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinaryV0.writeLinkCollection(ORecordSerializerBinaryV0.java:586)
	at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinaryV0.writeSingleValue(ORecordSerializerBinaryV0.java:467)
	at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinaryV0.serialize(ORecordSerializerBinaryV0.java:180)
	at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinary.toStream(ORecordSerializerBinary.java:81)
	at com.orientechnologies.orient.core.record.impl.ODocument.toStream(ODocument.java:1884)
	at com.orientechnologies.orient.core.record.impl.ODocument.toStream(ODocument.java:654)
	at com.orientechnologies.orient.server.network.protocol.binary.OBinaryNetworkProtocolAbstract.getRecordBytes(OBinaryNetworkProtocolAbstract.java:418)
	at com.orientechnologies.orient.server.network.protocol.binary.OBinaryNetworkProtocolAbstract.writeRecord(OBinaryNetworkProtocolAbstract.java:353)
	at com.orientechnologies.orient.server.network.protocol.binary.OBinaryNetworkProtocolAbstract.writeIdentifiable(OBinaryNetworkProtocolAbstract.java:129)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.command(ONetworkProtocolBinary.java:1163)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.executeRequest(ONetworkProtocolBinary.java:343)
	at com.orientechnologies.orient.server.network.protocol.binary.OBinaryNetworkProtocolAbstract.execute(OBinaryNetworkProtocolAbstract.java:180)
	at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:65)
Caused by: java.lang.ArrayIndexOutOfBoundsException
Error on iterating record collection
com.orientechnologies.orient.core.exception.ODatabaseException: Error on retrieving record #105:3
	at com.orientechnologies.orient.core.db.record.ODatabaseRecordAbstract.executeReadRecord(ODatabaseRecordAbstract.java:945)
	at com.orientechnologies.orient.core.tx.OTransactionNoTx.loadRecord(OTransactionNoTx.java:79)
	at com.orientechnologies.orient.core.db.record.ODatabaseRecordTx.load(ODatabaseRecordTx.java:264)
	at com.orientechnologies.orient.core.db.record.ODatabaseRecordTx.load(ODatabaseRecordTx.java:43)
	at com.orientechnologies.orient.core.id.ORecordId.getRecord(ORecordId.java:302)
	at com.orientechnologies.orient.core.db.record.OLazyRecordIterator.next(OLazyRecordIterator.java:75)
	at com.orientechnologies.orient.core.db.record.OLazyRecordIterator.next(OLazyRecordIterator.java:38)
	at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinaryV0.writeLinkCollection(ORecordSerializerBinaryV0.java:586)
	at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinaryV0.writeSingleValue(ORecordSerializerBinaryV0.java:467)
	at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinaryV0.serialize(ORecordSerializerBinaryV0.java:180)
	at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinary.toStream(ORecordSerializerBinary.java:81)
	at com.orientechnologies.orient.core.record.impl.ODocument.toStream(ODocument.java:1884)
	at com.orientechnologies.orient.core.record.impl.ODocument.toStream(ODocument.java:654)
	at com.orientechnologies.orient.server.network.protocol.binary.OBinaryNetworkProtocolAbstract.getRecordBytes(OBinaryNetworkProtocolAbstract.java:418)
	at com.orientechnologies.orient.server.network.protocol.binary.OBinaryNetworkProtocolAbstract.writeRecord(OBinaryNetworkProtocolAbstract.java:353)
	at com.orientechnologies.orient.server.network.protocol.binary.OBinaryNetworkProtocolAbstract.writeIdentifiable(OBinaryNetworkProtocolAbstract.java:129)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.command(ONetworkProtocolBinary.java:1163)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.executeRequest(ONetworkProtocolBinary.java:343)
	at com.orientechnologies.orient.server.network.protocol.binary.OBinaryNetworkProtocolAbstract.execute(OBinaryNetworkProtocolAbstract.java:180)
	at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:65)
Caused by: java.lang.ArrayIndexOutOfBoundsException
… …

After debug the source code,  find out due to 2.0 we did lots of changes on protocol.

When iterator memberUsers which is a linkset, somehow recordSerializer was set in ONetworkThreadLocalSerializer.(Fiirst time read serializer was set to null in thread local). when call fromStream, it was expect first bytes as serilizerVersion followed by document binary, but somehow it was missing. Then throw ArrayIndexOutofBound exception,

ORecordSerializerBinary.java
  @Override
  public ORecord fromStream(final byte[] iSource, ORecord iRecord, final String[] iFields) {
    if (iSource.length == 0)
      return iRecord;
    if (iRecord == null)
      iRecord = new ODocument();
    else
      checkTypeODocument(iRecord);

    BytesContainer container = new BytesContainer(iSource);
    container.skip(1);
    serializerByVersion[iSource[0]].deserialize((ODocument) iRecord, container);//ArrayIndexOutOfBoundsException
    ORecordInternal.clearSource(iRecord);
    return iRecord;
  }

**Comment by tglman** [comment]
after last changes with the dirty manager, and the remove of the ONetworkThreadLocalSerializer this should not happen anymore, closing
