### ISSUE TITLE
[2.0M2] Any operation using the Blueprints OrientGraph API fails

### ISSUE THREAD

**Issue by machinelearner** [orientechnologies/orientdb#2997]
`com.orientechnologies.orient.core.exception.ODatabaseException: Database instance is not set in current thread. Assure to set it with: ODatabaseRecordThreadLocal.INSTANCE.set(db);
	at com.orientechnologies.orient.core.db.ODatabaseRecordThreadLocal.get(ODatabaseRecordThreadLocal.java:35)
	at com.orientechnologies.orient.core.index.OIndexManagerAbstract.getDatabase(OIndexManagerAbstract.java:390)
	at com.orientechnologies.orient.core.index.OIndexManagerAbstract.preProcessBeforeReturn(OIndexManagerAbstract.java:433)
	at com.orientechnologies.orient.core.index.OIndexManagerAbstract.getIndexes(OIndexManagerAbstract.java:155)
	at com.orientechnologies.orient.core.index.OIndexManagerProxy.getIndexes(OIndexManagerProxy.java:56)
	at com.tinkerpop.blueprints.impls.orient.OrientBaseGraph.getIndexedKeys(OrientBaseGraph.java:1376)
	at com.tinkerpop.blueprints.impls.orient.OrientGraphQuery$OrientGraphQueryIterable.getIndexedKeys(OrientGraphQuery.java:88)
	at com.tinkerpop.blueprints.util.DefaultGraphQuery$DefaultGraphQueryIterable.getElementIterable(DefaultGraphQuery.java:145)
	at com.tinkerpop.blueprints.util.DefaultGraphQuery$DefaultGraphQueryIterable.<init>(DefaultGraphQuery.java:82)
	at com.tinkerpop.blueprints.impls.orient.OrientGraphQuery$OrientGraphQueryIterable.<init>(OrientGraphQuery.java:81)
	at com.tinkerpop.blueprints.impls.orient.OrientGraphQuery.vertices(OrientGraphQuery.java:160)`.....

is an example stacktrace failing for query

`((OrientGraphQuery) orientGraph.query()).labels("Resource").has("_id", Compare.EQUAL, resourceId).limit(2).vertices()`

similar(Same) behaviour while doing other CRUD operations

The way OrientGraph instance is instantiated

``` java
public class OrientGraphModule extends AbstractModule {
//Guice module to instantiate orientdb client interface 
    private final Settings settings;
    private OrientGraph orientGraph;

    public OrientGraphModule(Settings settings) {
        this.settings = settings;
    }

    @Override
    protected void configure() {
        bind(OrientGraph.class).toInstance(orientGraph());
    }

    public OrientGraph orientGraph() {
        OGlobalConfiguration.CACHE_LOCAL_ENABLED.setValue(false);
       //dbUrl is driven from configuration: eg: remote:localhost/tenantedDatabase
        orientGraph = new OrientGraph(settings.dbUrl());
        ODatabaseRecordThreadLocal.INSTANCE.set(orientGraph.getRawGraph());
        return orientGraph;
    }
}
```

Is there anything missing? 
If i'm not wrong,  the ThreadLocal option is set within OrientGraph initialization as well. Facing this problem while evaluating the OrientDb 2.0M2 version (moving from 1.7.8)

**Comment by lvca** [comment]
The issue has been closed because no response has been received after a while. In case the issue is still valid, please reopen it or write a comment that explains why it's still valid and a way to reproduce it. Thank you.
