### ISSUE TITLE
Async behaviour of new ODatabaseDocumentTx(url)

### ISSUE THREAD

**Issue by PhantomYdn** [orientechnologies/orientdb#3050]
Starting from some version from OrientDB-2.0-M1 I some from time to time following exception:

```
com.orientechnologies.orient.core.exception.ODatabaseException: Database 'plocal:Orienteer' is closed
    at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.checkOpeness(ODatabaseDocumentTx.java:2591)
    at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.getMetadata(ODatabaseDocumentTx.java:714)
    at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.getMetadata(ODatabaseDocumentTx.java:141)
    at com.orientechnologies.orient.core.index.OIndexManagerAbstract.releaseExclusiveLock(OIndexManagerAbstract.java:381)
    at com.orientechnologies.orient.core.index.OIndexManagerShared.recreateIndexes(OIndexManagerShared.java:289)
    at com.orientechnologies.orient.core.index.OIndexManagerProxy.recreateIndexes(OIndexManagerProxy.java:142)
    at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.initAtFirstOpen(ODatabaseDocumentTx.java:2637)
    at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.open(ODatabaseDocumentTx.java:258)
```

It's pretty strange, because actually DB is opening as you can see in stacktrace.

But if there is Thread.sleep(1000) between  `ODatabaseDocumentTx db = new ODatabaseDocumentTx(dbURL);`
and  `db.open(username, password);` everything is going well.

A long with mentioned exception I see following in the logs:

```
2014-11-10 15:49:22:161 INFO OrientDB Server v2.0-SNAPSHOT is starting up... [OServer]
2014-11-10 15:49:22:216 INFO Databases directory: C:\eclipse\workspace\Orienteer\.\databases [OServer]
2014-11-10 15:49:22:278 INFO Listening binary connections on 0.0.0.0:2424 (protocol v.26, socket=default) [OServerNetworkListener]
2014-11-10 15:49:22:299 INFO Listening http connections on 0.0.0.0:2480 (protocol v.10, socket=default) [OServerNetworkListener]
2014-11-10 15:49:22:320 INFO OrientDB Server v2.0-SNAPSHOT is active. [OServer]
2014-11-10 15:49:22:441 WARN segment file 'database.ocf' was not closed correctly last time [OSingleFileSegment]
2014-11-10 15:49:22:909 WARN Storage Orienteer was not closed properly. Will try to restore from write ahead log. [OLocalPaginatedStorage]
2014-11-10 15:49:22:909 INFO Looking for last checkpoint... [OLocalPaginatedStorage]
2014-11-10 15:49:22:922 INFO FULL checkpoint found. [OLocalPaginatedStorage]
2014-11-10 15:49:22:925 INFO Data restore procedure from full checkpoint is started. Restore is performed from LSN OLogSequenceNumber{segment=0, position=6224903} [OLocalPaginatedStorage]
2014-11-10 15:49:23:017 INFO Apply last batch of operations are read from WAL. [OLocalPaginatedStorage]
2014-11-10 15:49:23:018 WARN Record com.orientechnologies.orient.core.storage.impl.local.paginated.wal.OCheckpointEndRecord{lsn=OLogSequenceNumber{segment=0, position=6224927}} will be skipped during data restore. [OLocalPaginatedStorage]
```

Why fresh created DB looks "broken" for OrientDB is another story. But, I guess, that there is some missed synchronization between creation ODatabaseDocumentTx instance and actual opening that DB. May be some flag like "reparing" will help a little bit: at least to wait time when DB can be opened.

**Comment by gkgt80** [comment]
My Environment details 
1. orientdb-community-2.0.12 
2.  java version "1.8.0_45"
Java(TM) SE Runtime Environment (build 1.8.0_45-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.45-b02, mixed mode)
3.  Running on Windows

My Scenario :
1. I am loading data in Orient Graph via Java client
2. OrientGraphFactory factory = new OrientGraphFactory(
				"remote:localhost/test", "root", "root").setupPool(1,
				2);
		graph = factory.getTx();

Exception I am getting ->

com.orientechnologies.orient.core.exception.ODatabaseException: Database 'remote:localhost/test' is closed
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.checkOpeness(ODatabaseDocumentTx.java:2647)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.executeReadRecord(ODatabaseDocumentTx.java:1556)
	at com.orientechnologies.orient.core.tx.OTransactionOptimistic.loadRecord(OTransactionOptimistic.java:226)
	at com.orientechnologies.orient.core.tx.OTransactionOptimistic.loadRecord(OTransactionOptimistic.java:237)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.load(ODatabaseDocumentTx.java:1452)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.load(ODatabaseDocumentTx.java:118)
	at com.orientechnologies.orient.core.id.ORecordId.getRecord(ORecordId.java:318)
	at com.tinkerpop.blueprints.impls.orient.OrientBaseGraph.getVertex(OrientBaseGraph.java:748)
