### ISSUE TITLE
Out of memory after 7396000 records loaded

### ISSUE THREAD

**Issue by maiklos** [orientechnologies/orientdb#3159]
I think I've found memory leak.

The test case is following:
1) create graph db on local filesystem
2) keep loading some random data via graph API
3) after some (rather long) time (cca 30 minutes - 7396000 records loaded in my case) heap memory is exhausted and my application crashes with following exception:

<pre>
Exception in thread "main" java.lang.OutOfMemoryError: GC overhead limit exceeded
	at java.lang.Long.toUnsignedString(Long.java:242)
	at java.lang.Long.toHexString(Long.java:177)
	at java.util.UUID.digits(UUID.java:385)
	at java.util.UUID.toString(UUID.java:375)
	at com.tinkerpop.blueprints.impls.orient.OrientElement.setProperties(OrientElement.java:139)
	at com.tinkerpop.blueprints.impls.orient.OrientBaseGraph.addVertex(OrientBaseGraph.java:474)
	at com.github.maiklos.orientdb_sandbox.Run.start(Run.java:43)
	at com.github.maiklos.orientdb_sandbox.Run.main(Run.java:19)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:134)
</pre>

demonstration is available here: https://github.com/maiklos/orientdb_sandbox/commit/ef3f7c2cfc52db9cb9c6f0a59e54b7093c92d260

I run it with -Xmx64M. Also the resulting database size is 5.3G so enough space is needed on filesystem.
jvisualvm snapshot is here: 
![outofmemory_orientdb](https://cloud.githubusercontent.com/assets/251009/5366857/81e0aa68-7ff7-11e4-8670-0ea143c5adb5.png)

**Comment by laa** [comment]
Seem like it fixed :-) I close it.

**Comment by LorenaSuarez** [comment]
Please I have a problem with OrientDB and Java I have a program with this query to calculate the shortest path to 300000 but the program is very slow someone can help me how I do the memory configuration I read this post but I don't understand how I do this changes @laa and @maiklos please help me

**Comment by cmassi** [comment]
Hi Lorena, <br> check http://orientdb.com/docs/last/Performance-Tuning.html for sample jvm options, and http://orientdb.com/docs/last/Configuration.html for xml properties too. <br> For an appropriate Xmx value, you could monitor gc activity with additional options in your server.sh and java client (e.g for server: -XX:+PrintGCDetails -XX:+PrintGCTimeStamps -XX:+PrintGCDateStamps -XX:+PrintTenuringDistribution -Xloggc:$ORIENTDB_HOME/log/gc_%p_%t.log) <br>  You can check at startup current jvm settings with +XX:+PrintFlagsFinal and current orientdb properties with -Denvironment.dumpCfgAtStartup=true <br> You can set appropriate values for direct memory and buffers, e.g: -XX:MaxDirectMemorySize=12g -Dstorage.diskCache.bufferSize=12288 (or buffer size in xml, in mb, with buffer size <= direct memory).<br> Claudio
