### ISSUE TITLE
1.7.7 -> 2.0 fails to find users

### ISSUE THREAD

**Issue by mdymczyk** [orientechnologies/orientdb#3167]
OS: database created on Windows 8, tested on Windows 8 and Ubuntu 14

I'm trying to start my db created with 1.7.7 using the newest source code (2.0 SNAPSHOT) or the newest console (2.0-M3) but I'm getting:

```
Connecting to database [plocal:<MY_PATH>/database/orientdb/databases/db] with user 'admin'...
Error: com.orientechnologies.orient.core.exception.OSecurityAccessException: User or password not valid for database: 'db'
```

I can successfully connect with older console (1.7.7), the user is there:

```
orientdb {db}> select from ouser

----+----+----------+-------------------------------------------------------------------------+------+-----
#   |@RID|name      |password                                                                 |status|roles
----+----+----------+-------------------------------------------------------------------------+------+-----
0   |#5:0|admin     |{SHA-256}8C6976E5B5410415BDE908BD4DEE15DFB167A9C873FC4BB8A81F6F2AB448A918|ACTIVE|[1]  
1   |#5:1|reader    |{SHA-256}3D0941964AA3EBDCB00CCEF58B1BB399F9F898465E9886D5AEC7F31090A0FB30|ACTIVE|[1]  
2   |#5:2|writer    |{SHA-256}B93006774CBDD4B299389A03AC3D88C3A76B460D538795BC12718011A909FBA5|ACTIVE|[1]  
3   |#5:3|replicator|{SHA-256}C5C405236B891916BAC25169A1A39C28DC3F394C5FD7D36A9FDCE31AA4700B5C|ACTIVE|[1]  
----+----+----------+-------------------------------------------------------------------------+------+-----

4 item(s) found. Query executed in 0.001 sec(s).
```

Tried the same thing on Linux with a db created of linux (with 1.7.7) and all works fine.

Stacktrace:

```java
com.orientechnologies.orient.core.exception.OSecurityAccessException: User or password not valid for database: 'db'
	at com.orientechnologies.orient.core.metadata.security.OSecurityShared.authenticate(OSecurityShared.java:160) ~[orientdb-core-2.0-SNAPSHOT.jar:2.0-SNAPSHOT]
	at com.orientechnologies.orient.core.metadata.security.OSecurityProxy.authenticate(OSecurityProxy.java:87) ~[orientdb-core-2.0-SNAPSHOT.jar:2.0-SNAPSHOT]
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.open(ODatabaseDocumentTx.java:283) ~[orientdb-core-2.0-SNAPSHOT.jar:2.0-SNAPSHOT]
	at com.orientechnologies.orient.core.db.OPartitionedDatabasePool.acquire(OPartitionedDatabasePool.java:278) ~[orientdb-core-2.0-SNAPSHOT.jar:2.0-SNAPSHOT]
```

When I go into ```OSecurityShared#getUser``` and change ```"select from OUser where name = '"``` to use ```like``` instead ```"select from OUser where name like '"``` it does find the user.

**Comment by lvca** [comment]
@mdymczyk Sorry I don't remember if we already fix this issue. Did you send me the database?
