### ISSUE TITLE
Out of memory after 644593 records loaded

### ISSUE THREAD

**Issue by magstellon** [orientechnologies/orientdb#3181]
Hi,

I use OrientDB ETL tool in order to import 1 700 000 records from an RDBMS. A record contains 44 fields which are varchar2, number and timestamp.

After about 644 000 records loaded into OrientDB, i get an error message : 
<code>Error on creating record in cluster: com.orientechnologies.orient.core.storage.impl.local.paginated.OPaginatedCluster@1f3e27b
com.orientechnologies.orient.core.exception.OStorageException
        at com.orientechnologies.orient.core.storage.impl.local.paginated.OPaginatedCluster.createRecord(OPaginatedCluster.java:398)
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.doCreateRecord(OAbstractPaginatedStorage.java:1359)
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.createRecord(OAbstractPaginatedStorage.java:598)
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.executeSaveRecord(ODatabaseDocumentTx.java:1625)
        at com.orientechnologies.orient.core.tx.OTransactionNoTx.saveRecord(OTransactionNoTx.java:93)
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.save(ODatabaseDocumentTx.java:2162)
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.save(ODatabaseDocumentTx.java:123)
        at com.orientechnologies.orient.core.record.impl.ODocument.save(ODocument.java:1650)
        at com.orientechnologies.orient.core.record.impl.ODocument.save(ODocument.java:1641)
        at com.tinkerpop.blueprints.impls.orient.OrientElement.save(OrientElement.java:291)
        at com.tinkerpop.blueprints.impls.orient.OrientElement.save(OrientElement.java:276)
        at com.tinkerpop.blueprints.impls.orient.OrientElement.setProperty(OrientElement.java:178)
        at com.orientechnologies.orient.etl.transformer.OVertexTransformer.executeTransform(OVertexTransformer.java:73)
        at com.orientechnologies.orient.etl.transformer.OAbstractTransformer.transform(OAbstractTransformer.java:37)
        at com.orientechnologies.orient.etl.OETLPipeline.execute(OETLPipeline.java:108)
        at com.orientechnologies.orient.etl.OETLProcessor.executeSequentially(OETLProcessor.java:464)
        at com.orientechnologies.orient.etl.OETLProcessor.execute(OETLProcessor.java:257)
        at com.orientechnologies.orient.etl.OETLProcessor.main(OETLProcessor.java:225)
Caused by: java.lang.OutOfMemoryError
        at sun.misc.Unsafe.allocateMemory(Native Method)
        at com.orientechnologies.common.directmemory.OUnsafeMemory.allocate(OUnsafeMemory.java:85)
        at com.orientechnologies.common.directmemory.ODirectMemoryPointer.<init>(ODirectMemoryPointer.java:70)
        at com.orientechnologies.orient.core.index.hashindex.local.cache.OWOWCache.cacheFileContent(OWOWCache.java:926)
        at com.orientechnologies.orient.core.index.hashindex.local.cache.OWOWCache.load(OWOWCache.java:414)
        at com.orientechnologies.orient.core.index.hashindex.local.cache.OReadWriteDiskCache.updateCache(OReadWriteDiskCache.java:667)
        at com.orientechnologies.orient.core.index.hashindex.local.cache.OReadWriteDiskCache.doLoad(OReadWriteDiskCache.java:300)
        at com.orientechnologies.orient.core.index.hashindex.local.cache.OReadWriteDiskCache.load(OReadWriteDiskCache.java:268)
        at com.orientechnologies.orient.core.storage.impl.local.paginated.OPaginatedCluster.addEntry(OPaginatedCluster.java:1363)
        at com.orientechnologies.orient.core.storage.impl.local.paginated.OPaginatedCluster.createRecord(OPaginatedCluster.java:387)
        ... 17 more
Error in Pipeline execution: com.orientechnologies.orient.core.exception.ODatabaseException: Error on saving record in cluster 11
com.orientechnologies.orient.core.exception.ODatabaseException: Error on saving record in cluster 11
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.executeSaveRecord(ODatabaseDocumentTx.java:1666)
        at com.orientechnologies.orient.core.tx.OTransactionNoTx.saveRecord(OTransactionNoTx.java:93)
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.save(ODatabaseDocumentTx.java:2162)
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.save(ODatabaseDocumentTx.java:123)
        at com.orientechnologies.orient.core.record.impl.ODocument.save(ODocument.java:1650)
        at com.orientechnologies.orient.core.record.impl.ODocument.save(ODocument.java:1641)
        at com.tinkerpop.blueprints.impls.orient.OrientElement.save(OrientElement.java:291)
        at com.tinkerpop.blueprints.impls.orient.OrientElement.save(OrientElement.java:276)
        at com.tinkerpop.blueprints.impls.orient.OrientElement.setProperty(OrientElement.java:178)
        at com.orientechnologies.orient.etl.transformer.OVertexTransformer.executeTransform(OVertexTransformer.java:73)
        at com.orientechnologies.orient.etl.transformer.OAbstractTransformer.transform(OAbstractTransformer.java:37)
        at com.orientechnologies.orient.etl.OETLPipeline.execute(OETLPipeline.java:108)
        at com.orientechnologies.orient.etl.OETLProcessor.executeSequentially(OETLProcessor.java:464)
        at com.orientechnologies.orient.etl.OETLProcessor.execute(OETLProcessor.java:257)
        at com.orientechnologies.orient.etl.OETLProcessor.main(OETLProcessor.java:225)
Caused by: java.lang.NullPointerException

There is insufficient memory for the Java Runtime Environment to continue.
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.executeSaveRecord(ODatabaseDocumentTx.java:1627) Native memory allocation (malloc) failed to allocate
66584   ... 14 more bytes
 for Chunk::newETL process halted: com.orientechnologies.orient.etl.OETLProcessHaltedException: com.orientechnologies.orient.core.exception.ODatabaseException: Error on saving record in cluster 11

An error report file with more information is saved as:
C:\Users\MNH1\Documents\Programmes\orientdb-community-2.0-M3\bin\hs_err_pid8724.log</code>

Even if I increase the Java heap size and the swap backing store, i have got an OutOfMemoryError.

**Comment by zhuobao** [comment]
@lvca do you have a final solution for this?

**Comment by lvca** [comment]
@zhuobao what's your ETL?
