### ISSUE TITLE
'OStorageException: File with id 155 does not exist' during Index rebuilding

### ISSUE THREAD

**Issue by adithyank** [orientechnologies/orientdb#3182]
Creating this issue as per the comment by @laa in https://groups.google.com/forum/#!topic/orient-database/NqijZy-IUz0

OrientDB version : 2.0-M3

Our application was killed (kill -9) due to OutOfMemory. When we start next time, index rebuilding started. After some time, this Exception has come....
Will it impact in 'not creating the index'??? 
i.e., the application will be able to retrieve the data from the index.... right?????

Pls clarify

`
2014-12-12 17:40:27:756 INFO  Index POR_MSP1_1.key was successfully created and rebuild is going to be started. [OIndexManagerShared$RecreateIndexesTask]
2014-12-12 17:40:27:767 INFO  - Rebuilding index rcainv.POR_MSP1_1.key (estimated 539210 items)... [OIndexRebuildOutputListener]
2014-12-12 17:40:37:768 INFO  --> 56.75% progress, 306,014 indexed so far (30,601 items/sec) [OIndexRebuildOutputListener]
2014-12-12 17:40:46:355 INFO  --> OK, indexed 539,210 items in 18,588 ms [OIndexRebuildOutputListener]
2014-12-12 17:40:46:985 INFO  Rebuild of POR_MSP1_1.key index was successfully finished. [OIndexManagerShared$RecreateIndexesTask]
2014-12-12 17:40:46:986 INFO  Start creation of index CIRCUIT.key [OIndexManagerShared$RecreateIndexesTask]Error during addition of index {type:UNIQUE_HASH_INDEX,name:CIRCUIT.key,indexDefi
nition:{className:CIRCUIT,field:key,keyType:STRING,collate:default,nullValuesIgnored:true},indexDefinitionClass:com.orientechnologies.orient.core.index.OPropertyIndexDefinition,clusters:[1
],mapRid:#1:35,algorithm:SBTREE,valueContainerAlgorithm:NONE}
com.orientechnologies.orient.core.exception.OStorageException: File with id 155 does not exist.
        at com.orientechnologies.orient.core.index.hashindex.local.cache.OWOWCache.openFile(OWOWCache.java:313)
        at com.orientechnologies.orient.core.index.hashindex.local.cache.OReadWriteDiskCache.openFile(OReadWriteDiskCache.java:164)
        at com.orientechnologies.orient.core.index.hashindex.local.OLocalHashTable.deleteWithoutLoad(OLocalHashTable.java:720)
        at com.orientechnologies.orient.core.index.engine.OHashTableIndexEngine.deleteWithoutLoad(OHashTableIndexEngine.java:115)
        at com.orientechnologies.orient.core.index.OIndexAbstract.deleteWithoutIndexLoad(OIndexAbstract.java:495)
        at com.orientechnologies.orient.core.index.OIndexManagerShared$RecreateIndexesTask.createAutomaticIndex(OIndexManagerShared.java:500)
        at com.orientechnologies.orient.core.index.OIndexManagerShared$RecreateIndexesTask.recreateIndex(OIndexManagerShared.java:486)
        at com.orientechnologies.orient.core.index.OIndexManagerShared$RecreateIndexesTask.recreateIndexes(OIndexManagerShared.java:460)
        at com.orientechnologies.orient.core.index.OIndexManagerShared$RecreateIndexesTask.run(OIndexManagerShared.java:449)
        at java.lang.Thread.run(Thread.java:745)

2014-12-12 17:40:47:001 INFO  Start creation of index POR_TLWITHCTP.key [OIndexManagerShared$RecreateIndexesTask]
2014-12-12 17:40:47:413 INFO  Index POR_TLWITHCTP.key was successfully created and rebuild is going to be started. [OIndexManagerShared$RecreateIndexesTask]
`

**Comment by laa** [comment]
Close it because it is not reporducable, but feel free to reopen it.
