### ISSUE TITLE
OTimeoutException: Timeout on acquiring exclusive lock against resource of class

### ISSUE THREAD

**Issue by adithyank** [orientechnologies/orientdb#3183]
I am creating this issue based on the comment by @laa at https://groups.google.com/forum/#!topic/orient-database/MXE-4DHZoJ8

---
OrientDB Version : 2.0-M3

our software reads from doc db in multi threads while there is another only one thread creating records.......!

1. What is the reason for this Exception???
2. Does this mean that the writing thread's transaction has not been committed/rolledback in 30 seconds. If yes, I want to give you another input that all our transactions are committed and closed within 5 seconds from the time of db.begin()

```
com.orientechnologies.orient.core.exception.ODatabaseException: Error on retrieving record #43:1148902 (cluster: por_point)
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.executeReadRecord(ODatabaseDocumentTx.java:1530) ~[orientdb-core-2.0-M3.jar:2.0-M3]
        at com.orientechnologies.orient.core.tx.OTransactionOptimistic.loadRecord(OTransactionOptimistic.java:221) ~[orientdb-core-2.0-M3.jar:2.0-M3]
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.load(ODatabaseDocumentTx.java:1354) ~[orientdb-core-2.0-M3.jar:2.0-M3]
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.load(ODatabaseDocumentTx.java:123) ~[orientdb-core-2.0-M3.jar:2.0-M3]
        at com.orientechnologies.orient.core.id.ORecordId.getRecord(ORecordId.java:309) ~[orientdb-core-2.0-M3.jar:2.0-M3]
        at in.co.nmsworks.documenttdb.db.DocDB.getDocTypeObjects(DocDB.java:118) ~[cygnetOTNMS.jar:?]
        at in.co.nmsworks.cygnet.telecom.fault.rcasia.inventory.store.RcaInvReader.getEntitiesByNonUniqueKeySearch(RcaInvReader.java:344) ~[cygnetOTNMS.jar:?]
        at in.co.nmsworks.cygnet.telecom.fault.rcasia.inventory.store.RcaInvReader.getPointEntities(RcaInvReader.java:354) ~[cygnetOTNMS.jar:?]
        at in.co.nmsworks.cygnet.telecom.fault.rcasia.inventory.store.RcaInvReader.buildImpactAnalysisDataHolderForCTP(RcaInvReader.java:279) ~[cygnetOTNMS.jar:?]
        at in.co.nmsworks.cygnet.telecom.fault.rcasia.plug.impl.circuit.impact.node.constructor.impl2.CTPImpactAnalysisDataBuilder.buildImpactAnalysisData(CTPImpactAnalysisDataBuilder.java:40) ~[cygnetOTNMS.jar:?]
        at in.co.nmsworks.cygnet.telecom.fault.rcasia.plug.impl.circuit.impl2.CircuitPlugHelper.getImpactAnalysisDataHolder(CircuitPlugHelper.java:117) ~[cygnetOTNMS.jar:?]
        at in.co.nmsworks.cygnet.telecom.fault.rcasia.plug.impl.circuit.impl2.CircuitPlug.getImpactAnalysisDataHolder(CircuitPlug.java:216) ~[cygnetOTNMS.jar:?]
        at in.co.nmsworks.cygnet.telecom.fault.rcasia.plug.impl.circuit.impl2.CircuitPlug.analyze(CircuitPlug.java:105) [cygnetOTNMS.jar:?]
        at in.co.nmsworks.cygnet.telecom.fault.rcasia.plug.Plug.computeAndStore(Plug.java:111) [cygnetOTNMS.jar:?]
        at in.co.nmsworks.cygnet.telecom.fault.rcasia.server.PlugInvokationTask.getPlugResult(PlugInvokationTask.java:126) [cygnetOTNMS.jar:?]
        at in.co.nmsworks.cygnet.telecom.fault.rcasia.server.PlugInvokationTask.compute(PlugInvokationTask.java:66) [cygnetOTNMS.jar:?]
        at in.co.nmsworks.cygnet.telecom.fault.rcasia.server.PlugInvokationTask.compute(PlugInvokationTask.java:37) [cygnetOTNMS.jar:?]
        at java.util.concurrent.RecursiveTask.exec(RecursiveTask.java:93) [?:1.7.0_55]
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:334) [?:1.7.0_55]
        at java.util.concurrent.ForkJoinWorkerThread.execTask(ForkJoinWorkerThread.java:604) [?:1.7.0_55]
        at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:762) [?:1.7.0_55]
        at java.util.concurrent.ForkJoinPool.work(ForkJoinPool.java:646) [?:1.7.0_55]
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:398) [?:1.7.0_55]
Caused by: com.orientechnologies.common.concur.OTimeoutException: Timeout on acquiring exclusive lock against resource of class: class com.orientechnologies.common.concur.resource.OSharedResourceAdaptiveExternal with timeout=30000
        at com.orientechnologies.common.concur.resource.OSharedResourceAdaptive.throwTimeoutException(OSharedResourceAdaptive.java:188) ~[orientdb-core-2.0-M3.jar:2.0-M3]
        at com.orientechnologies.common.concur.resource.OSharedResourceAdaptive.acquireSharedLock(OSharedResourceAdaptive.java:165) ~[orientdb-core-2.0-M3.jar:2.0-M3]
        at com.orientechnologies.common.concur.resource.OSharedResourceAdaptiveExternal.acquireSharedLock(OSharedResourceAdaptiveExternal.java:44) ~[orientdb-core-2.0-M3.jar:2.0-M3]
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.readRecord(OAbstractPaginatedStorage.java:1198) ~[orientdb-core-2.0-M3.jar:2.0-M3]
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.readRecord(OAbstractPaginatedStorage.java:644) ~[orientdb-core-2.0-M3.jar:2.0-M3]
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.executeReadRecord(ODatabaseDocumentTx.java:1497) ~[orientdb-core-2.0-M3.jar:2.0-M3]
```

**Comment by lvca** [comment]
We removed this timeout in 2.0. In your case it's possible the flush time is slower than timeout.

**Comment by adithyank** [comment]
> We removed this timeout in 2.0. In your case it's possible the flush time is slower than timeout.

So, what should be done to avoid this Exception ?

**Comment by laa** [comment]
You should do nothing, we already did this into the code.
