### ISSUE TITLE
(Client=55) ArrayIndexOutOfBoundsException after importing ~10M records

### ISSUE THREAD

**Issue by garrett-gottlieb** [orientechnologies/orientdb#3192]
After running my ETL overnight, I woke up to a frozen computer, so I had to reboot it. It seems my database is now in an invalid state. I can connect to it, but I can't do anything.

```
[19:43:46] Starting OrientDB
           .
          .`        `
          ,      `:.
         `,`    ,:`
         .,.   :,,
         .,,  ,,,
    .    .,.:::::  ````                                 :::::::::     :::::::::
    ,`   .::,,,,::.,,,,,,`;;                      .:    ::::::::::    :::    :::
    `,.  ::,,,,,,,:.,,.`  `                       .:    :::      :::  :::     :::
     ,,:,:,,,,,,,,::.   `        `         ``     .:    :::      :::  :::     :::
      ,,:.,,,,,,,,,: `::, ,,   ::,::`   : :,::`  ::::   :::      :::  :::    :::
       ,:,,,,,,,,,,::,:   ,,  :.    :   ::    :   .:    :::      :::  :::::::
        :,,,,,,,,,,:,::   ,,  :      :  :     :   .:    :::      :::  :::::::::
  `     :,,,,,,,,,,:,::,  ,, .::::::::  :     :   .:    :::      :::  :::     :::
  `,...,,:,,,,,,,,,: .:,. ,, ,,         :     :   .:    :::      :::  :::     :::
    .,,,,::,,,,,,,:  `: , ,,  :     `   :     :   .:    :::      :::  :::     :::
      ...,::,,,,::.. `:  .,,  :,    :   :     :   .:    :::::::::::   :::     :::
           ,::::,,,. `:   ,,   :::::    :     :   .:    :::::::::     ::::::::::
           ,,:` `,,.
          ,,,    .,`
         ,,.     `,                                          GRAPH DATABASE
       ``        `.
                 ``                                         www.orientdb.org
                 `

2014-12-13 19:43:47:617 INFO  OrientDB auto-config DISKCACHE=13,880MB (heap=455MB os=16,384MB disk=214,640MB) [orientechnologies]
2014-12-13 19:43:47:619 INFO  Loading configuration from: /Users/gsquare567/Sites/pumpup/server/libs/orientdb-community-2.0-SNAPSHOT/config/orientdb-server-config.xml... [OServerConfigurationLoaderXml]
2014-12-13 19:43:47:737 INFO  OrientDB Server v2.0-SNAPSHOT (build UNKNOWN@r; 2014-12-04 22:29:22-0500) is starting up... [OServer]
2014-12-13 19:43:47:753 INFO  Databases directory: /Users/gsquare567/Sites/pumpup/server/libs/orientdb-community-2.0-SNAPSHOT/databases [OServer]
2014-12-13 19:43:47:778 INFO  Listening binary connections on 0.0.0.0:2424 (protocol v.26, socket=default) [OServerNetworkListener]
2014-12-13 19:43:47:778 INFO  Listening http connections on 0.0.0.0:2480 (protocol v.10, socket=default) [OServerNetworkListener]
2014-12-13 19:43:47:787 INFO  Installing dynamic plugin 'studio-2.0.zip'... [OServerPluginManager]
2014-12-13 19:43:47:832 INFO  Installing GREMLIN language v.2.6.0 - graph.pool.max=50 [OGraphServerHandler]
2014-12-13 19:43:47:834 INFO  [OVariableParser.resolveVariables] Error on resolving property: distributed [orientechnologies]
2014-12-13 19:43:47:835 INFO  Installing Script interpreter. WARN: authenticated clients can execute any kind of code into the server by using the following allowed languages: [sql] [OServerSideScriptInterpreter]
2014-12-13 19:43:47:836 INFO  OrientDB Server v2.0-SNAPSHOT is active. [OServer]Sent run-time exception to the client /127.0.0.1:53487: com.orientechnologies.orient.core.exception.ODatabaseException: Error on retrieving record #25:608298 (cluster: workout)
com.orientechnologies.orient.core.exception.ODatabaseException: Error on retrieving record #25:608298 (cluster: workout)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.executeReadRecord(ODatabaseDocumentTx.java:1541)
	at com.orientechnologies.orient.core.tx.OTransactionNoTx.loadRecord(OTransactionNoTx.java:79)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.load(ODatabaseDocumentTx.java:1379)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.load(ODatabaseDocumentTx.java:124)
	at com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.executeSearchRecord(OCommandExecutorSQLSelect.java:478)
	at com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.fetchFromTarget(OCommandExecutorSQLSelect.java:1281)
	at com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.fetchValuesFromIndexCursor(OCommandExecutorSQLSelect.java:1627)
	at com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.optimizeSort(OCommandExecutorSQLSelect.java:1608)
	at com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.tryOptimizeSort(OCommandExecutorSQLSelect.java:1396)
	at com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.searchForIndexes(OCommandExecutorSQLSelect.java:1519)
	at com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.searchInClasses(OCommandExecutorSQLSelect.java:734)
	at com.orientechnologies.orient.core.sql.OCommandExecutorSQLResultsetAbstract.assignTarget(OCommandExecutorSQLResultsetAbstract.java:185)
	at com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.assignTarget(OCommandExecutorSQLSelect.java:435)
	at com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.executeSearch(OCommandExecutorSQLSelect.java:417)
	at com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.execute(OCommandExecutorSQLSelect.java:388)
	at com.orientechnologies.orient.core.sql.OCommandExecutorSQLDelegate.execute(OCommandExecutorSQLDelegate.java:64)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.executeCommand(OAbstractPaginatedStorage.java:1157)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.command(OAbstractPaginatedStorage.java:1146)
	at com.orientechnologies.orient.core.command.OCommandRequestTextAbstract.execute(OCommandRequestTextAbstract.java:63)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.command(ONetworkProtocolBinary.java:1101)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.executeRequest(ONetworkProtocolBinary.java:338)
	at com.orientechnologies.orient.server.network.protocol.binary.OBinaryNetworkProtocolAbstract.execute(OBinaryNetworkProtocolAbstract.java:201)
	at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:65)
Caused by: java.lang.ArrayIndexOutOfBoundsException
	at java.lang.System.arraycopy(Native Method)
	at com.orientechnologies.orient.core.compression.impl.ONothingCompression.uncompress(ONothingCompression.java:49)
	at com.orientechnologies.orient.core.storage.impl.local.paginated.OPaginatedCluster.readRecord(OPaginatedCluster.java:558)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.doReadRecord(OAbstractPaginatedStorage.java:1769)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.readRecord(OAbstractPaginatedStorage.java:1406)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.readRecord(OAbstractPaginatedStorage.java:679)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.executeReadRecord(ODatabaseDocumentTx.java:1509)
	... 22 more
```

Running a query like
```sql
select from workout order by updatedAt desc
```
yields
```
2014-12-13 19:48:25:250 SEVERE Internal server error:
java.lang.ArrayIndexOutOfBoundsException [ONetworkProtocolHttpDb]
```

**Comment by laa** [comment]
Closed because was out of dated.
