### ISSUE TITLE
Once connection pool is exhausted, cannot shutdown orientdb cleanly

### ISSUE THREAD

**Issue by uttamatsimility** [orientechnologies/orientdb#3195]
There could be 2 issues at play.

1. I had a bug in my code that was not closing OrientDB connection after use. The problem is, those connections are left open even if I kill the client java process. What is the default timeout for connection?

2. Once we run into such situation, shutdown doesn't work because shutdown thread cannot find the connection to send the kill signal. There is a need for a backdoor to send the kill signal

Here are the relevant log statements
2014-12-14 07:27:59:793 WARNING Reached maximum number of concurrent connections (2035), reject incoming connection from /XXXXX:50127 [OServerNetworkListener]

and

com.orientechnologies.orient.enterprise.channel.binary.ONetworkProtocolException: Cannot read protocol version from remote server XXXX:2424: java.io.EOFException
	at com.orientechnologies.orient.enterprise.channel.binary.OChannelBinaryAsynchClient.<init>(OChannelBinaryAsynchClient.java:98)
	at com.orientechnologies.orient.enterprise.channel.binary.OChannelBinaryAsynchClient.<init>(OChannelBinaryAsynchClient.java:62)
	at com.orientechnologies.orient.enterprise.channel.binary.OChannelBinaryAsynchClientSynch.<init>(OChannelBinaryAsynchClientSynch.java:36)
	at com.orientechnologies.orient.server.OServerShutdownMain.connect(OServerShutdownMain.java:107)
	at com.orientechnologies.orient.server.OServerShutdownMain.main(OServerShutdownMain.java:139)

**Comment by lvca** [comment]
What's the status of this issue?

**Comment by lvca** [comment]
Closing

**Comment by lvca** [comment]
If the server connection pool is exhausted the only way is killing the process (SOFTKILL)
