### ISSUE TITLE
OStorageException: File with id 184690147382 does not exist

### ISSUE THREAD

**Issue by adithyank** [orientechnologies/orientdb#3205]
OrientDB Version : 2.0-M3
JDK : Oracle 1.7.0_40

During our Database building exercise, this Exception is coming during commit call

```
com.orientechnologies.orient.core.exception.OStorageException
        at com.orientechnologies.orient.core.index.hashindex.local.OLocalHashTable.put(OLocalHashTable.java:442) ~[orientdb-core-2.0-M3.jar:2.0-M3]
        at com.orientechnologies.orient.core.index.engine.OHashTableIndexEngine.put(OHashTableIndexEngine.java:160) ~[orientdb-core-2.0-M3.jar:2.0-M3]
        at com.orientechnologies.orient.core.index.OIndexMultiValues.commitSnapshot(OIndexMultiValues.java:255) ~[orientdb-core-2.0-M3.jar:2.0-M3]
        at com.orientechnologies.orient.core.index.OIndexAbstract.commit(OIndexAbstract.java:643) ~[orientdb-core-2.0-M3.jar:2.0-M3]
        at com.orientechnologies.orient.core.tx.OTransactionOptimistic$CommitIndexesCallback.run(OTransactionOptimistic.java:98) ~[orientdb-core-2.0-M3.jar:2.0-M3]
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.commit(OAbstractPaginatedStorage.java:864) ~[orientdb-core-2.0-M3.jar:2.0-M3]
        at com.orientechnologies.orient.core.tx.OTransactionOptimistic.doCommit(OTransactionOptimistic.java:455) ~[orientdb-core-2.0-M3.jar:2.0-M3]
        at com.orientechnologies.orient.core.tx.OTransactionOptimistic.commit(OTransactionOptimistic.java:142) ~[orientdb-core-2.0-M3.jar:2.0-M3]
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.commit(ODatabaseDocumentTx.java:2261) ~[orientdb-core-2.0-M3.jar:2.0-M3]
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.commit(ODatabaseDocumentTx.java:2231) ~[orientdb-core-2.0-M3.jar:2.0-M3]
        at in.co.nmsworks.documenttdb.db.DocDB.commit(DocDB.java:482) ~[cygnetOTNMS.jar:?]
        at in.co.nmsworks.cygnet.telecom.fault.rcasia.inventory.store.RcaInvWriter.addAll(RcaInvWriter.java:107) [cygnetOTNMS.jar:?]
        at in.co.nmsworks.cygnet.telecom.fault.rcasia.inventory.store.RcaInvWriter.addAll(RcaInvWriter.java:78) [cygnetOTNMS.jar:?]
        at in.co.nmsworks.cygnet.telecom.fault.rcasia.inventory.dao.InventoryDAO.save(InventoryDAO.java:106) [cygnetOTNMS.jar:?]
        at in.co.nmsworks.cygnet.telecom.fault.rcasia.inventory.queue.InventoryDataPersister.saveDAOData(InventoryDataPersister.java:224) [cygnetOTNMS.jar:?]
        at in.co.nmsworks.cygnet.telecom.fault.rcasia.inventory.queue.InventoryDataPersister.processAddition(InventoryDataPersister.java:199) [cygnetOTNMS.jar:?]
        at in.co.nmsworks.cygnet.telecom.fault.rcasia.inventory.queue.InventoryDataPersister.run(InventoryDataPersister.java:69) [cygnetOTNMS.jar:?]
Caused by: com.orientechnologies.orient.core.exception.OStorageException: File with id 184690147382 does not exist.
        at com.orientechnologies.orient.core.index.hashindex.local.cache.OWOWCache.openFile(OWOWCache.java:313) ~[orientdb-core-2.0-M3.jar:2.0-M3]
        at com.orientechnologies.orient.core.index.hashindex.local.cache.OReadWriteDiskCache.openFile(OReadWriteDiskCache.java:164) ~[orientdb-core-2.0-M3.jar:2.0-M3]
        at com.orientechnologies.orient.core.index.sbtreebonsai.local.OSBTreeBonsaiLocal.load(OSBTreeBonsaiLocal.java:492) ~[orientdb-core-2.0-M3.jar:2.0-M3]
        at com.orientechnologies.orient.core.db.record.ridbag.sbtree.OIndexRIDContainerSBTree.<init>(OIndexRIDContainerSBTree.java:61) ~[orientdb-core-2.0-M3.jar:2.0-M3]
        at com.orientechnologies.orient.core.serialization.serializer.stream.OStreamSerializerSBTreeIndexRIDContainer.deserializeFromDirectMemoryObject(OStreamSerializerSBTreeIndexRIDContainer
        at com.orientechnologies.orient.core.serialization.serializer.stream.OStreamSerializerSBTreeIndexRIDContainer.deserializeFromDirectMemoryObject(OStreamSerializerSBTreeIndexRIDContainer
        at com.orientechnologies.orient.core.storage.impl.local.paginated.base.ODurablePage.deserializeFromDirectMemory(ODurablePage.java:117) ~[orientdb-core-2.0-M3.jar:2.0-M3]
        at com.orientechnologies.orient.core.index.hashindex.local.OHashIndexBucket.getEntry(OHashIndexBucket.java:131) ~[orientdb-core-2.0-M3.jar:2.0-M3]
        at com.orientechnologies.orient.core.index.hashindex.local.OHashIndexBucket$EntryIterator.next(OHashIndexBucket.java:350) ~[orientdb-core-2.0-M3.jar:2.0-M3]
        at com.orientechnologies.orient.core.index.hashindex.local.OHashIndexBucket$EntryIterator.next(OHashIndexBucket.java:333) ~[orientdb-core-2.0-M3.jar:2.0-M3]
        at com.orientechnologies.orient.core.index.hashindex.local.OLocalHashTable.splitBucketContent(OLocalHashTable.java:1891) ~[orientdb-core-2.0-M3.jar:2.0-M3]
        at com.orientechnologies.orient.core.index.hashindex.local.OLocalHashTable.splitBucket(OLocalHashTable.java:1953) ~[orientdb-core-2.0-M3.jar:2.0-M3]
        at com.orientechnologies.orient.core.index.hashindex.local.OLocalHashTable.doPut(OLocalHashTable.java:1543) ~[orientdb-core-2.0-M3.jar:2.0-M3]
        at com.orientechnologies.orient.core.index.hashindex.local.OLocalHashTable.put(OLocalHashTable.java:434) ~[orientdb-core-2.0-M3.jar:2.0-M3]
        ... 16 more
```

The following two different values are coming during this Exception

```
Caused by: com.orientechnologies.orient.core.exception.OStorageException: File with id 184690147382 does not exist.
Caused by: com.orientechnologies.orient.core.exception.OStorageException: File with id 0 does not exist.
```

Should I give any more information. Pls advice

**Comment by laa** [comment]
Close it because it is not reporducable, but feel free to reopen it.
