### ISSUE TITLE
(Client=55) OUsers getting created without mandatory fields and causing errors during other queries

### ISSUE THREAD

**Issue by garrett-gottlieb** [orientechnologies/orientdb#3221]
When querying for posts made by a set of users, i get a NullPointerException:

```
Sent run-time exception to the client /206.223.160.138:42833: com.orientechnologies.orient.core.exception.OCommandExecutionException: Error on execution of command: sql.SELECT COUNT(*) FROM (SELECT EXPAND(OUT('UserWrotePost')) FROM [#5:2042747,#5:2120327,#5:2114122,#5:2057483,#5:2118784,#5:2129738,#5:2137949,#5:2135310,#5:2133745,#5:2138408,#5:2131699]) WHERE actionId IN [2000,2001,2002,2003,2004,1,8,207,1300] WHERE createdAt > date('2014-12-17T17:21:09.827Z')
com.orientechnologies.orient.core.exception.OCommandExecutionException: Error on execution of command: sql.SELECT COUNT(*) FROM (SELECT EXPAND(OUT('UserWrotePost')) FROM [#5:2042747,#5:2120327,#5:2114122,#5:2057483,#5:2118784,#5:2129738,#5:2137949,#5:2135310,#5:2133745,#5:2138408,#5:2131699]) WHERE actionId IN [2000,2001,2002,2003,2004,1,8,207,1300] WHERE createdAt > date('2014-12-17T17:21:09.827Z')
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.executeCommand(OAbstractPaginatedStorage.java:1169)
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.command(OAbstractPaginatedStorage.java:1152)
        at com.orientechnologies.orient.core.command.OCommandRequestTextAbstract.execute(OCommandRequestTextAbstract.java:63)
        at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.command(ONetworkProtocolBinary.java:1179)
        at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.executeRequest(ONetworkProtocolBinary.java:385)
        at com.orientechnologies.orient.server.network.protocol.binary.OBinaryNetworkProtocolAbstract.execute(OBinaryNetworkProtocolAbstract.java:216)
        at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:65)
Caused by: java.lang.NullPointerException
        at com.orientechnologies.orient.core.storage.impl.local.paginated.base.ODurablePage.deserializeFromDirectMemory(ODurablePage.java:117)
        at com.orientechnologies.orient.core.index.sbtreebonsai.local.OSBTreeBonsaiBucket.getEntry(OSBTreeBonsaiBucket.java:272)
        at com.orientechnologies.orient.core.index.sbtreebonsai.local.OSBTreeBonsaiLocal.firstKey(OSBTreeBonsaiLocal.java:831)
        at com.orientechnologies.orient.core.db.record.ridbag.sbtree.OSBTreeRidBag$SBTreeMapEntryIterator.init(OSBTreeRidBag.java:483)
        at com.orientechnologies.orient.core.db.record.ridbag.sbtree.OSBTreeRidBag$SBTreeMapEntryIterator.<init>(OSBTreeRidBag.java:417)
        at com.orientechnologies.orient.core.db.record.ridbag.sbtree.OSBTreeRidBag.rawIterator(OSBTreeRidBag.java:524)
        at com.orientechnologies.orient.core.db.record.ridbag.ORidBag.rawIterator(ORidBag.java:152)
        at com.tinkerpop.blueprints.impls.orient.OrientVertex.getVertices(OrientVertex.java:604)
inary.java:385)
        at com.orientechnologies.orient.server.network.protocol.binary.OBinaryNetworkProtocolAbstract.execute(OBinaryNetworkProtocolAbstract.java:216)
        at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:65)
Caused by: java.lang.NullPointerException
        at com.orientechnologies.orient.core.storage.impl.local.paginated.base.ODurablePage.deserializeFromDirectMemory(ODurablePage.java:117)
        at com.orientechnologies.orient.core.index.sbtreebonsai.local.OSBTreeBonsaiBucket.getEntry(OSBTreeBonsaiBucket.java:272)
        at com.orientechnologies.orient.core.index.sbtreebonsai.local.OSBTreeBonsaiLocal.firstKey(OSBTreeBonsaiLocal.java:831)
        at com.orientechnologies.orient.core.db.record.ridbag.sbtree.OSBTreeRidBag$SBTreeMapEntryIterator.init(OSBTreeRidBag.java:483)
        at com.orientechnologies.orient.core.db.record.ridbag.sbtree.OSBTreeRidBag$SBTreeMapEntryIterator.<init>(OSBTreeRidBag.java:417)
        at com.orientechnologies.orient.core.db.record.ridbag.sbtree.OSBTreeRidBag.rawIterator(OSBTreeRidBag.java:524)
        at com.orientechnologies.orient.core.db.record.ridbag.ORidBag.rawIterator(ORidBag.java:152)
        at com.tinkerpop.blueprints.impls.orient.OrientVertex.getVertices(OrientVertex.java:604)
        at com.orientechnologies.orient.graph.sql.functions.OSQLFunctionMove.v2v(OSQLFunctionMove.java:95)
        at com.orientechnologies.orient.graph.sql.functions.OSQLFunctionOut.move(OSQLFunctionOut.java:41)
        at com.orientechnologies.orient.graph.sql.functions.OSQLFunctionMove$2.call(OSQLFunctionMove.java:82)
        at com.orientechnologies.orient.graph.sql.functions.OSQLFunctionMove$2.call(OSQLFunctionMove.java:79)
        at com.orientechnologies.orient.core.sql.OSQLEngine.foreachRecord(OSQLEngine.java:277)
        at com.orientechnologies.orient.graph.sql.functions.OSQLFunctionMove.execute(OSQLFunctionMove.java:79)
        at com.orientechnologies.orient.core.sql.functions.OSQLFunctionRuntime.execute(OSQLFunctionRuntime.java:126)
        at com.orientechnologies.orient.core.sql.functions.OSQLFunctionRuntime.getValue(OSQLFunctionRuntime.java:142)
        at com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.applyExpand(OCommandExecutorSQLSelect.java:1739)
        at com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.iterator(OCommandExecutorSQLSelect.java:353)
        at com.orientechnologies.orient.core.sql.OCommandExecutorSQLResultsetDelegate.iterator(OCommandExecutorSQLResultsetDelegate.java:50)
        at com.orientechnologies.orient.core.sql.OCommandExecutorSQLResultsetAbstract.assignTarget(OCommandExecutorSQLResultsetAbstract.java:193)
        at com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.assignTarget(OCommandExecutorSQLSelect.java:435)
        at com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.executeSearch(OCommandExecutorSQLSelect.java:417)
        at com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.execute(OCommandExecutorSQLSelect.java:388)
        at com.orientechnologies.orient.core.sql.OCommandExecutorSQLDelegate.execute(OCommandExecutorSQLDelegate.java:64)
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.executeCommand(OAbstractPaginatedStorage.java:1163)
        ... 6 more
```

There is also a fetching error like this:
```
Fetching error on record #5:2135310
java.lang.NullPointerException
        at com.orientechnologies.orient.core.storage.impl.local.paginated.base.ODurablePage.deserializeFromDirectMemory(ODurablePage.java:117)
        at com.orientechnologies.orient.core.index.sbtreebonsai.local.OSBTreeBonsaiBucket.getEntry(OSBTreeBonsaiBucket.java:272)
        at com.orientechnologies.orient.core.index.sbtreebonsai.local.OSBTreeBonsaiLocal.firstKey(OSBTreeBonsaiLocal.java:831)
        at com.orientechnologies.orient.core.db.record.ridbag.sbtree.OSBTreeRidBag$SBTreeMapEntryIterator.init(OSBTreeRidBag.java:483)
        at com.orientechnologies.orient.core.db.record.ridbag.sbtree.OSBTreeRidBag$SBTreeMapEntryIterator.<init>(OSBTreeRidBag.java:417)
        at com.orientechnologies.orient.core.db.record.ridbag.sbtree.OSBTreeRidBag.rawIterator(OSBTreeRidBag.java:524)
        at com.orientechnologies.orient.core.db.record.ridbag.ORidBag.rawIterator(ORidBag.java:152)
        at com.orientechnologies.orient.core.fetch.OFetchHelper.processRecordRidMap(OFetchHelper.java:138)
        at com.orientechnologies.orient.core.fetch.OFetchHelper.fetch(OFetchHelper.java:67)
        at com.orientechnologies.orient.core.serialization.serializer.record.string.ORecordSerializerJSON.toString(ORecordSerializerJSON.java:337)
        at com.orientechnologies.orient.core.serialization.serializer.record.string.ORecordSerializerStringAbstract.toString(ORecordSerializerStringAbstract.java:655)
        at com.orientechnologies.orient.core.record.ORecordAbstract.toJSON(ORecordAbstract.java:193)
        at com.orientechnologies.orient.server.network.protocol.http.OHttpResponse.formatMultiValue(OHttpResponse.java:336)
        at com.orientechnologies.orient.server.network.protocol.http.OHttpResponse.writeRecords(OHttpResponse.java:312)
        at com.orientechnologies.orient.server.network.protocol.http.OHttpResponse.writeResult(OHttpResponse.java:211)
        at com.orientechnologies.orient.server.network.protocol.http.command.post.OServerCommandPostCommand.execute(OServerCommandPostCommand.java:91)
        at com.orientechnologies.orient.server.network.protocol.http.ONetworkProtocolHttpAbstract.service(ONetworkProtocolHttpAbstract.java:200)
        at com.orientechnologies.orient.server.network.protocol.http.ONetworkProtocolHttpAbstract.execute(ONetworkProtocolHttpAbstract.java:600)
        at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:65)
```

or an `ODirectMemoryViolationException`:
```
Fetching error on record #5:2138408
com.orientechnologies.common.directmemory.ODirectMemoryViolationException: Provided offset [1540576812] is more than size of allocated area  [65552]
        at com.orientechnologies.common.directmemory.ODirectMemoryPointer.rangeCheck(ODirectMemoryPointer.java:215)
        at com.orientechnologies.common.directmemory.ODirectMemoryPointer.getByte(ODirectMemoryPointer.java:140)
        at com.orientechnologies.orient.core.storage.impl.local.paginated.base.ODurablePage.getByteValue(ODurablePage.java:121)
        at com.orientechnologies.orient.core.index.sbtreebonsai.local.OSBTreeBonsaiBucket.<init>(OSBTreeBonsaiBucket.java:163)
        at com.orientechnologies.orient.core.index.sbtreebonsai.local.OSBTreeBonsaiLocal.findBucket(OSBTreeBonsaiLocal.java:1209)
        at com.orientechnologies.orient.core.index.sbtreebonsai.local.OSBTreeBonsaiLocal.loadEntriesMajor(OSBTreeBonsaiLocal.java:736)
        at com.orientechnologies.orient.core.db.record.ridbag.sbtree.OSBTreeRidBag$SBTreeMapEntryIterator.prefetchData(OSBTreeRidBag.java:447)
        at com.orientechnologies.orient.core.db.record.ridbag.sbtree.OSBTreeRidBag$SBTreeMapEntryIterator.next(OSBTreeRidBag.java:429)
        at com.orientechnologies.orient.core.db.record.ridbag.sbtree.OSBTreeRidBag$SBTreeMapEntryIterator.next(OSBTreeRidBag.java:409)
        at com.orientechnologies.orient.core.db.record.ridbag.sbtree.OSBTreeRidBag.nextChangedNotRemovedSBTreeEntry(OSBTreeRidBag.java:998)
        at com.orientechnologies.orient.core.db.record.ridbag.sbtree.OSBTreeRidBag.access$200(OSBTreeRidBag.java:56)
        at com.orientechnologies.orient.core.db.record.ridbag.sbtree.OSBTreeRidBag$RIDBagIterator.next(OSBTreeRidBag.java:328)
        at com.orientechnologies.orient.core.db.record.ridbag.sbtree.OSBTreeRidBag$RIDBagIterator.next(OSBTreeRidBag.java:252)
        at com.orientechnologies.orient.core.fetch.OFetchHelper.fetchCollection(OFetchHelper.java:467)
        at com.orientechnologies.orient.core.fetch.OFetchHelper.fetch(OFetchHelper.java:362)
        at com.orientechnologies.orient.core.fetch.OFetchHelper.processRecord(OFetchHelper.java:303)
        at com.orientechnologies.orient.core.fetch.OFetchHelper.fetch(OFetchHelper.java:69)
        at com.orientechnologies.orient.core.serialization.serializer.record.string.ORecordSerializerJSON.toString(ORecordSerializerJSON.java:337)
        at com.orientechnologies.orient.core.serialization.serializer.record.string.ORecordSerializerStringAbstract.toString(ORecordSerializerStringAbstract.java:655)
        at com.orientechnologies.orient.core.record.ORecordAbstract.toJSON(ORecordAbstract.java:193)
        at com.orientechnologies.orient.server.network.protocol.http.OHttpResponse.formatMultiValue(OHttpResponse.java:336)
        at com.orientechnologies.orient.server.network.protocol.http.OHttpResponse.writeRecords(OHttpResponse.java:312)
        at com.orientechnologies.orient.server.network.protocol.http.OHttpResponse.writeResult(OHttpResponse.java:211)
        at com.orientechnologies.orient.server.network.protocol.http.command.post.OServerCommandPostCommand.execute(OServerCommandPostCommand.java:91)
        at com.orientechnologies.orient.server.network.protocol.http.ONetworkProtocolHttpAbstract.service(ONetworkProtocolHttpAbstract.java:200)
        at com.orientechnologies.orient.server.network.protocol.http.ONetworkProtocolHttpAbstract.execute(ONetworkProtocolHttpAbstract.java:600)
        at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:65)
```

**Comment by laa** [comment]
Fixed in latests 2.1.x version
