### ISSUE TITLE
OSchemaException: ORole.rules that is not compatible with the type LINKMAP

### ISSUE THREAD

**Issue by uttamatsimility** [orientechnologies/orientdb#3222]
Upgraded the OrientDB from 2.0-M3 to 2.0-SNAPSHOT. I tried to load the db created with earlier (M3) version of OrientDB. Now I am getting following error

Caused by: com.orientechnologies.orient.core.exception.OSchemaException: The database contains some schemaless data in the property ORole.rules that is not compatible with the type LINKMAP
	at com.orientechnologies.orient.core.metadata.schema.OClassImpl.checkPersistentPropertyType(OClassImpl.java:1636)
	at com.orientechnologies.orient.core.metadata.schema.OClassImpl.addProperty(OClassImpl.java:1964)
	at com.orientechnologies.orient.core.metadata.schema.OClassImpl.createProperty(OClassImpl.java:594)
	at com.orientechnologies.orient.object.metadata.schema.OSchemaProxyObject.generateLinkProperty(OSchemaProxyObject.java:430)
	at com.orientechnologies.orient.object.metadata.schema.OSchemaProxyObject.generateSchema(OSchemaProxyObject.java:294)
	at com.orientechnologies.orient.object.metadata.schema.OSchemaProxyObject.synchronizeSchema(OSchemaProxyObject.java:353)

Is there any step of "upgrade" that I am missing? What is the best way to fix ORule records?

**Comment by laa** [comment]
I close it because it was not answered during 2 weeks feel free to reopen it.
