### ISSUE TITLE
(Client=55) Deadlock caused by user without password

### ISSUE THREAD

**Issue by garrett-gottlieb** [orientechnologies/orientdb#3233]
There are two issues here:
1. A user was created without a password, and
2. This caused a deadlock when an ETL tried to work with this record

Here is the output:
```
Sent run-time exception to the client /127.0.0.1:40895: com.orientechnologies.orient.core.exception.OCommandExecutionException: Error on execution of command: sql.select from #5:2139052
com.orientechnologies.orient.core.exception.OCommandExecutionException: Error on execution of command: sql.select from #5:2139052
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.executeCommand(OAbstractPaginatedStorage.java:1169)
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.command(OAbstractPaginatedStorage.java:1152)
        at com.orientechnologies.orient.core.sql.query.OSQLQuery.run(OSQLQuery.java:71)
        at com.orientechnologies.orient.core.query.OQueryAbstract.execute(OQueryAbstract.java:33)
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.query(ODatabaseDocumentTx.java:627)
        at com.orientechnologies.orient.core.sql.OCommandExecutorSQLUpdate.execute(OCommandExecutorSQLUpdate.java:209)
        at com.orientechnologies.orient.core.sql.OCommandExecutorSQLDelegate.execute(OCommandExecutorSQLDelegate.java:64)
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.executeCommand(OAbstractPaginatedStorage.java:1163)
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.command(OAbstractPaginatedStorage.java:1152)
        at com.orientechnologies.orient.core.command.OCommandRequestTextAbstract.execute(OCommandRequestTextAbstract.java:63)
        at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.command(ONetworkProtocolBinary.java:1179)
        at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.executeRequest(ONetworkProtocolBinary.java:385)
        at com.orientechnologies.orient.server.network.protocol.binary.OBinaryNetworkProtocolAbstract.execute(OBinaryNetworkProtocolAbstract.java:216)
        at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:65)
Caused by: com.orientechnologies.orient.core.exception.OValidationException: The field 'OUser.password' is mandatory, but not found on record: OUser#5:2139052{out_UserLikesPost:[1]} v69604
        at com.orientechnologies.orient.core.record.impl.ODocument.validateField(ODocument.java:259)
        at com.orientechnologies.orient.core.record.impl.ODocument.validate(ODocument.java:1905)
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.save(ODatabaseDocumentTx.java:2214)
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.save(ODatabaseDocumentTx.java:117)
        at com.orientechnologies.orient.core.record.impl.ODocument.save(ODocument.java:1672)
        at com.orientechnologies.orient.core.record.impl.ODocument.save(ODocument.java:1663)
        at com.orientechnologies.orient.core.sql.OCommandExecutorSQLUpdate.result(OCommandExecutorSQLUpdate.java:266)
        at com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.addResult(OCommandExecutorSQLSelect.java:611)
        at com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.handleResult(OCommandExecutorSQLSelect.java:547)
        at com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.executeSearchRecord(OCommandExecutorSQLSelect.java:501)
        at com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.fetchFromTarget(OCommandExecutorSQLSelect.java:1283)
        at com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.executeSearch(OCommandExecutorSQLSelect.java:430)
actPaginatedStorage.executeCommand(OAbstractPaginatedStorage.java:1163)
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.command(OAbstractPaginatedStorage.java:1152)
        at com.orientechnologies.orient.core.command.OCommandRequestTextAbstract.execute(OCommandRequestTextAbstract.java:63)
        at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.command(ONetworkProtocolBinary.java:1179)
        at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.executeRequest(ONetworkProtocolBinary.java:385)
        at com.orientechnologies.orient.server.network.protocol.binary.OBinaryNetworkProtocolAbstract.execute(OBinaryNetworkProtocolAbstract.java:216)
        at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:65)
Caused by: com.orientechnologies.common.concur.OTimeoutException: Can not lock record for 3000000 ms. seems record is deadlocked by other record
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.acquireReadLock(OAbstractPaginatedStorage.java:1287)
        at com.orientechnologies.orient.core.tx.OTransactionAbstract.lockRecord(OTransactionAbstract.java:104)
        at com.orientechnologies.orient.core.id.ORecordId.lock(ORecordId.java:277)
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.lockRecord(OAbstractPaginatedStorage.java:1767)
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.readRecord(OAbstractPaginatedStorage.java:1406)
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.readRecord(OAbstractPaginatedStorage.java:681)
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.executeReadRecord(ODatabaseDocumentTx.java:1568)
        ... 40 more
```

The real issue seems to be how these users are getting created without mandatory fields. I'm using the ETL to create users, and it seems to work for 99% of users but for some reason some are inserted without mandatory fields. It would be great if ODB could reject them from the ETL in this case.

**Comment by lvca** [comment]
Fixed long time ago.
