### ISSUE TITLE
(Client=55) OQueryParsingException should print out the whole query, not just the erroneous field

### ISSUE THREAD

**Issue by garrett-gottlieb** [orientechnologies/orientdb#3235]
As I'm running the ETL, errors that just tell me I have a misformatted date are useless as by the time I see the error, the error record has been lost or skipped. It would be much more useful if I could see the entire query so I could dig deeper into the record.

```
Sent run-time exception to the client /127.0.0.1:40135: com.orientechnologies.orient.core.exception.OQueryParsingException: Error on formatting date 'Fri Dec 19 00:53:51 UTC 2014' using the format: yyyy-MM-dd'T'HH:mm:ss.SSS'Z'
com.orientechnologies.orient.core.exception.OQueryParsingException: Error on formatting date 'Fri Dec 19 00:53:51 UTC 2014' using the format: yyyy-MM-dd'T'HH:mm:ss.SSS'Z'
        at com.orientechnologies.orient.core.sql.functions.misc.OSQLFunctionDate.execute(OSQLFunctionDate.java:77)
        at com.orientechnologies.orient.core.sql.functions.OSQLFunctionRuntime.execute(OSQLFunctionRuntime.java:126)
        at com.orientechnologies.orient.core.sql.functions.OSQLFunctionRuntime.getValue(OSQLFunctionRuntime.java:142)
        at com.orientechnologies.orient.core.sql.OSQLHelper.getValue(OSQLHelper.java:231)
        at com.orientechnologies.orient.core.sql.OFilterAnalyzer.createIndexedProperty(OFilterAnalyzer.java:229)
        at com.orientechnologies.orient.core.sql.OFilterAnalyzer.analyzeIndexMethod(OFilterAnalyzer.java:154)
        at com.orientechnologies.orient.core.sql.OFilterAnalyzer.analyzeFilterBranch(OFilterAnalyzer.java:139)
        at com.orientechnologies.orient.core.sql.OFilterAnalyzer.analyzeIntersection(OFilterAnalyzer.java:174)
        at com.orientechnologies.orient.core.sql.OFilterAnalyzer.analyzeFilterBranch(OFilterAnalyzer.java:137)
        at com.orientechnologies.orient.core.sql.OFilterAnalyzer.analyzeCondition(OFilterAnalyzer.java:103)
        at com.orientechnologies.orient.core.sql.OFilterAnalyzer.analyzeOrFilterBranch(OFilterAnalyzer.java:84)
        at com.orientechnologies.orient.core.sql.OFilterAnalyzer.analyzeMainCondition(OFilterAnalyzer.java:58)
        at com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.searchForIndexes(OCommandExecutorSQLSelect.java:1416)
        at com.orientechnologies.orient.core.sql.OCommandExecutorSQLSe        at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:65)
Caused by: java.text.ParseException: Unparseable date: "Sun Oct 26 22:52:04 UTC 2014"
        at java.text.DateFormat.parse(DateFormat.java:366)
        at com.orientechnologies.orient.core.sql.functions.misc.OSQLFunctionDate.execute(OSQLFunctionDate.java:75)
        ... 25 more
        at com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.execute(OCommandExecutorSQLSelect.java:388)
        at com.orientechnologies.orient.core.sql.OCommandExecutorSQLDelegate.execute(OCommandExecutorSQLDelegate.java:64)
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.executeCommand(OAbstractPaginatedStorage.java:1163)
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.comm^[[O
alyzer.java:139)
        at com.orientechnologies.orient.core.sql.OFilterAnalyzer.analyzeIntersection(OFilterAnalyzer.java:174)
        at com.orientechnologies.orient.core.sql.OFilterAnalyzer.analyzeFilterBranch(OFilterAnalyzer.java:137)
        at com.orientechnologies.orient.core.sql.OFilterAnalyzer.analyzeCondition(OFilterAnalyzer.java:103)
        at com.orientechnologies.orient.core.sql.OFilterAnalyzer.analyzeOrFilterBranch(OFilterAnalyzer.java:84)
        at com.orientechnologies.orient.core.sql.OFilterAnalyzer.analyzeMainCondition(OFilterAnalyzer.java:58)
        at com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.searchForIndexes(OCommandExecutorSQLSelect.java:1416)
        at com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.searchInClasses(OCommandExecutorSQLSelect.java:734)
        at com.orientechnologies.orient.core.sql.OCommandExecutorSQLResultsetAbstract.assignTarget(OCommandExecutorSQLResultsetAbstract.java:186)
        at com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.assignTarget(OCommandExecutorSQLSelect.java:435)
        at com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.executeSearch(OCommandExecutorSQLSelect.java:417)
        at com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.execute(OCommandExecutorSQLSelect.java:388)
        at com.orientechnologies.orient.core.sql.OCommandExecutorSQLDelegate.execute(OCommandExecutorSQLDelegate.java:64)
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.executeCommand(OAbstractPaginatedStorage.java:1163)
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.command(OAbstractPaginatedStorage.java:1152)
        at com.orientechnologies.orient.core.command.OCommandRequestTextAbstract.execute(OCommandRequestTextAbstract.java:63)
        at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.command(ONetworkProtocolBinary.java:1179)
        at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.executeRequest(ONetworkProtocolBinary.java:385)
        at com.orientechnologies.orient.server.network.protocol.binary.OBinaryNetworkProtocolAbstract.execute(OBinaryNetworkProtocolAbstract.java:216)
        at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:65)
Caused by: java.text.ParseException: Unparseable date: "Fri Dec 19 02:48:59 UTC 2014"
        at java.text.DateFormat.parse(DateFormat.java:366)
        at com.orientechnologies.orient.core.sql.functions.misc.OSQLFunctionDate.execute(OSQLFunctionDate.java:75)
        ... 25 more
```

**Comment by luigidellaquila** [comment]
Fixed long time ago with the new SQL parser

Closing

Thanks

Luigi
