### ISSUE TITLE
[Distributed] Weird 100% cpu utilization on acquiring new connection

### ISSUE THREAD

**Issue by mdymczyk** [orientechnologies/orientdb#3237]
Version: 2.0-RC
Number of nodes: 3

I was trying out the latest release, I'm not sure if it's the correct way but I was getting the connection like this:

```java
private static OPartitionedDatabasePoolFactory factory = new OPartitionedDatabasePoolFactory(1);

public static ODatabaseDocumentTx connect(DbProfile dbProfile) {
        ODatabaseDocumentTx acquired = factory.get(dbProfile.getDbLocation(),
                        dbProfile.getAuthCredentials().getUser(),
                        dbProfile.getAuthCredentials().getPassword())
                        .acquire();
        acquired.setConflictStrategy(OAutoMergeRecordConflictStrategy.NAME);
        return acquired;
}
```

When two users tried to do the same operation (list all entries in my DB) one thread would get blocked and the second one, holding the lock, would just do... nothing?

```java
"jetty-7011-database" prio=10 tid=0x00007f4070167800 nid=0x1e89 runnable [0x00007f3fd8db6000]
   java.lang.Thread.State: RUNNABLE
	at com.orientechnologies.orient.server.hazelcast.OHazelcastPlugin.onOpen(OHazelcastPlugin.java:405)
	- locked <0x000000070aabf5c0> (a java.util.HashMap)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.callOnOpenListeners(ODatabaseDocumentTx.java:335)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.open(ODatabaseDocumentTx.java:269)
	at com.orientechnologies.orient.core.db.OPartitionedDatabasePool.acquire(OPartitionedDatabasePool.java:278)
	at com.mypackage.database.db.utils.DatabaseUtils.connect(DatabaseUtils.java:32)
	at com.mypackage.database.db.DatabaseManagerImpl$DbIterator.hasNext(DatabaseManagerImpl.java:519)
	...


"jetty-6885-database" prio=10 tid=0x00007f407021b800 nid=0x1a69 waiting for monitor entry [0x00007f3fe0bdc000]
   java.lang.Thread.State: BLOCKED (on object monitor)
	at com.orientechnologies.orient.server.hazelcast.OHazelcastPlugin.onOpen(OHazelcastPlugin.java:405)
	- locked <0x000000070aabf5c0> (a java.util.HashMap)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.callOnOpenListeners(ODatabaseDocumentTx.java:335)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.open(ODatabaseDocumentTx.java:269)
	at com.orientechnologies.orient.core.db.OPartitionedDatabasePool.acquire(OPartitionedDatabasePool.java:278)
	at com.mypackage.database.db.utils.DatabaseUtils.connect(DatabaseUtils.java:32)
	at com.mypackage.database.db.DatabaseManagerImpl$DbIterator.hasNext(DatabaseManagerImpl.java:519)
	...
```

As you can see one is blocked and the other one is just there on the lock in a runnable state.

Both of those use up a lot of CPU:
```
 PID USER PR NI VIRT RES SHR S %CPU %MEM TIME+ COMMAND
 6761 root 24 4 9151m 5.1g 33m R 96.6 33.5 2742:28 java
 7817 root 16 -4 9151m 5.1g 33m R 96.6 33.5 2742:27 java
```

Around 97% each! And they've been like this for almost 2 days.

When I try to then list all (on that same machine) it works fine...

**Comment by lvca** [comment]
Closed because no response.
