### ISSUE TITLE
(Client=55) ignoreNullValues on index causes "Null keys are not supported" if excluded from save

### ISSUE THREAD

**Issue by garrett-gottlieb** [orientechnologies/orientdb#3245]
After creating an index that can handle `photo is not null` in queries:
```
CREATE PROPERTY Post.photo STRING
CREATE INDEX Post.photo ON Post (photo) NOTUNIQUE_HASH_INDEX METADATA {ignoreNullValues : false}
```
and creating a vertex without the `photo` property:
```
{
    likeCount: 0,
    commentCount: 0,
    actionId: 2001,
    note: null,
    ACL: {
        c5p2150124: {
            write: true
        },
        '*': {
            read: true
        }
    },
    private: false,
    updatedAt: Fri Dec 19 2014 21: 35: 29 GMT - 0500(EST),
    createdAt: Fri Dec 19 2014 21: 35: 29 GMT - 0500(EST)
}
```
I receive the error:
```
Sent run-time exception to the client /127.0.0.1:60451: com.orientechnologies.orient.core.index.sbtree.local.OSBTreeException: Null keys are not supported.
com.orientechnologies.orient.core.index.sbtree.local.OSBTreeException: Null keys are not supported.
  at com.orientechnologies.orient.core.index.sbtree.local.OSBTree.checkNullSupport(OSBTree.java:764)
  at com.orientechnologies.orient.core.index.sbtree.local.OSBTree.get(OSBTree.java:185)
  at com.orientechnologies.orient.core.index.engine.OSBTreeIndexEngine.get(OSBTreeIndexEngine.java:226)
  at com.orientechnologies.orient.core.index.OIndexMultiValues.putInSnapshot(OIndexMultiValues.java:162)
  at com.orientechnologies.orient.core.index.OIndexAbstract.applyIndexTxEntry(OIndexAbstract.java:1001)
  at com.orientechnologies.orient.core.index.OIndexAbstract.addTxOperation(OIndexAbstract.java:676)
  at com.orientechnologies.orient.core.tx.OTransactionOptimistic$CommitIndexesCallback.run(OTransactionOptimistic.java:98)
  at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.commit(OAbstractPaginatedStorage.java:901)
  at com.orientechnologies.orient.core.tx.OTransactionOptimistic.doCommit(OTransactionOptimistic.java:482)
  at com.orientechnologies.orient.core.tx.OTransactionOptimistic.commit(OTransactionOptimistic.java:147)
  at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.commit(ODatabaseDocumentTx.java:2369)
  at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.commit(ODatabaseDocumentTx.java:2339)
  at com.orientechnologies.orient.core.command.script.OCommandExecutorScript.executeSQLScript(OCommandExecutorScript.java:230)
  at com.orientechnologies.orient.core.command.script.OCommandExecutorScript.executeSQL(OCommandExecutorScript.java:137)
  at com.orientechnologies.orient.core.command.script.OCommandExecutorScript.executeInContext(OCommandExecutorScript.java:81)
  at com.orientechnologies.orient.core.command.script.OCommandExecutorScript.execute(OCommandExecutorScript.java:72)
  at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.executeCommand(OAbstractPaginatedStorage.java:1163)
  at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.command(OAbstractPaginatedStorage.java:1152)
  at com.orientechnologies.orient.core.command.OCommandRequestTextAbstract.execute(OCommandRequestTextAbstract.java:63)
  at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.command(ONetworkProtocolBinary.java:1179)
  at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.executeRequest(ONetworkProtocolBinary.java:385)
  at com.orientechnologies.orient.server.network.protocol.binary.OBinaryNetworkProtocolAbstract.execute(OBinaryNetworkProtocolAbstract.java:216)
  at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:65)
```
ODB should count undefined as null, so if I queried for `photo is null` the record that was attempted to be inserted would show up.

**Comment by tobiemh** [comment]
Hi @garrett-gottlieb was this done in distributed-mode or single-mode setup?

**Comment by lvca** [comment]
The issue has been closed because no response has been received after a while. In case the issue is still valid, please reopen it or write a comment that explains why it's still valid and a way to reproduce it. Thank you.
