### ISSUE TITLE
(Client=55) FETCHPLAN with out_*:0 wildcard causes StackOverflowError

### ISSUE THREAD

**Issue by garrett-gottlieb** [orientechnologies/orientdb#3247]
When I use wildcard with `:0` for `FETCHPLAN`, I always get StackOverflowError:
```
select from post
fetchplan out_*:0
```

Here's the console error (at least as much as I can grab). It is a recursive error and causes the DB to crash.

```
...
        at com.orientechnologies.orient.core.fetch.OFetchHelper.fetchRidMap(OFetchHelper.java:176)
        at com.orientechnologies.orient.core.fetch.OFetchHelper.processRecordRidMap(OFetchHelper.java:158)
        at com.orientechnologies.orient.core.fetch.OFetchHelper.fetchRidMap(OFetchHelper.java:173)
        at com.orientechnologies.orient.core.fetch.OFetchHelper.processRecordRidMap(OFetchHelper.java:158)
        at com.orientechnologies.orient.core.fetch.OFetchHelper.updateRidMap(OFetchHelper.java:248)
        at com.orientechnologies.orient.core.fetch.OFetchHelper.fetchCollectionRidMap(OFetchHelper.java:203)
        at com.orientechnologies.orient.core.fetch.OFetchHelper.fetchRidMap(OFetchHelper.java:176)
        at com.orientechnologies.orient.core.fetch.OFetchHelper.processRecordRidMap(OFetchHelper.java:158)
        at com.orientechnologies.orient.core.fetch.OFetchHelper.update        at com.orientechnologies.orient.core.fetch.OFetchHelper.fetchDocumentRidMap(OFetchHelper.java:190)
        at com.orientechnologies.orient.core.fetch.OFetchHelper.fetchRidMap(OFetchHelper.java:173)
        at com.orientechnologies.orient.core.fetch.OFetchHelper.processRecordRidMap(OFetchHelper.java:158)
        at com.orientechnologies.orient.core.fetch.OFetchHelper.updateRidMap(OFetchHelper.java:248)
        at com.orientechnologies.orient.core.fetch.OFetchHelper.fetchCollectionRidMap(OFetchHelper.java:203)
        at com.orientechnologies.orient.core.fetch.OFetchHelper.fetchRidMap(OFetchHelper.java:176)
        at com.orientechnologies.orient.core.fetch.OFetchHelper.processRecordRidMap(OFetchHelper.java:158)
        at com.orientechnologies.orient.core.fetch.OFetchHelper.fetchCollectionRidMap(OFetchHelper.java:203)
        at com.orientechnologies.orient.core.fetch.OFetchHelper.fetchRidMap(OFetchHelper.java:176)
        at com.orientechnologies.orient.core.fetch.OFetchHelper.processRecordRidMap(OFetchHelper.java:158)
        at com.orientechnologies.orient.core.fetch.OFetchHelper.updateRidMap(OFetchHelper.java:248)
        at com.orientechnologies.orient.core.fetch.OFetchHelper.fetchDocumentRidMap(OFetchHelper.java:190)
        at com.orientechnologies.orient.core.fetch.OFetchHelper.fetchRidMap(OFetchHelper.java:173)
        at com.orientechnologies.orient.core.fetch.OFetchHelper.processRecordRidMap(OFetchHelper.java:158)
        at com.orientechnologies.orient.core.fetch.OFetchHelper.updateRidMap(OFetchHelper.java:248)
        at com.orientechnologies.orient.core.fetch.OFetchHelper.fetchCollectionRidMap(OFetchHelper.java:203)
        at com.orientechnologies.orient.core.fetch.OFetchHelper.fetchRidMap(OFetchHelper.java:176)
        at com.orientechnologies.orient.core.fetch.OFetchHelper.processRecordRidMap(OFetchHelper.java:158)
        at com.orientechnologies.orient.core.fetch.OFetchHelper.updateRidMap(OFetchHelper.java:248)
        at com.orientechnologies.orient.core.fetch.OFetchHelper.fetchDocumentRidMap(OFetchHelper.java:190)
        at com.orientechnologies.orient.core.fetch.OFetchHelper.fetchRidMap(OFetchHelper.java:173)
        at com.orientechnologies.orient.core.fetch.OFetchHelper.processRecordRidMap(OFetchHelper.java:158)
        at com.orientechnologies.orient.core.fetch.OFetchHelper.updateRidMap(OFetchHelper.java:248)
        at com.orientechnologies.orient.core.fetch.OFetchHelper.fetchCollectionRidMap(OFetchHelper.java:203)
        at com.orientechnologies.orient.core.fetch.OFetchHelper.fetchRidMap(OFetchHelper.java:176)
        at com.orientechnologies.orient.core.fetch.OFetchHelper.processRecordRidMap(OFetchHelper.java:158)
        at com.orientechnologies.orient.core.fetch.OFetchHelper.updateRidMap(OFetchHelper.java:248)
        at com.orientechnologies.orient.core.fetch.OFetchHelper.fetchDocumentRidMap(OFetchHelper.java:190)
        at com.orientechnologies.orient.core.fetch.OFetchHelper.fetchRidMap(OFetchHelper.java:173)
        at com.orientechnologies.orient.core.fetch.OFetchHelper.processRecordRidMap(OFetchHelper.java:158)
        at com.orientechnologies.orient.core.fetch.OFetchHelper.updateRidMap(OFetchHelper.java:248)
        at com.orientechnologies.orient.core.fetch.OFetchHelper.fetchCollectionRidMap(OFetchHelper.java:203)
        at com.orientechnologies.orient.core.fetch.OFetchHelper.fetchRidMap(OFetchHelper.java:176)
        at 
...
```

**Comment by lvca** [comment]
Fixed in 2.1
