### ISSUE TITLE
"repair database" not doing anything

### ISSUE THREAD

**Issue by AaronSchulz** [orientechnologies/orientdb#3256]
Running "repair database" via the console shows:

- Fixing dirty links...

I see only ~10% CPU usage and zero disk I/O. I'm not sure what it's actually doing.

Logs show:
```
com.orientechnologies.common.directmemory.ODirectMemoryViolationException: Provided offset [19308902
] is more than size of allocated area  [65552]
        at com.orientechnologies.common.directmemory.ODirectMemoryPointer.rangeCheck(ODirectMemoryPo
inter.java:215)
        at com.orientechnologies.common.directmemory.ODirectMemoryPointer.getByte(ODirectMemoryPoint
er.java:140)
        at com.orientechnologies.orient.core.storage.impl.local.paginated.base.ODurablePage.getByteV
alue(ODurablePage.java:121)
        at com.orientechnologies.orient.core.index.sbtreebonsai.local.OSBTreeBonsaiBucket.<init>(OSB
TreeBonsaiBucket.java:163)
        at com.orientechnologies.orient.core.index.sbtreebonsai.local.OSBTreeBonsaiLocal.findBucket(
OSBTreeBonsaiLocal.java:1209)
        at com.orientechnologies.orient.core.index.sbtreebonsai.local.OSBTreeBonsaiLocal.loadEntries
Major(OSBTreeBonsaiLocal.java:736)
        at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.sbTree
BonsaiGetEntriesMajor(ONetworkProtocolBinary.java:1822)
        at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.execut
eRequest(ONetworkProtocolBinary.java:437)
        at com.orientechnologies.orient.server.network.protocol.binary.OBinaryNetworkProtocolAbstrac
t.execute(OBinaryNetworkProtocolAbstract.java:216)
        at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:65)
Sent run-time exception to the client /127.0.0.1:58850: com.orientechnologies.common.directmemory.OD
irectMemoryViolationException: Provided offset [19308902] is more than size of allocated area  [6555
2]
com.orientechnologies.common.directmemory.ODirectMemoryViolationException: Provided offset [19308902
] is more than size of allocated area  [65552]
        at com.orientechnologies.common.directmemory.ODirectMemoryPointer.rangeCheck(ODirectMemoryPo
inter.java:215)
        at com.orientechnologies.common.directmemory.ODirectMemoryPointer.getByte(ODirectMemoryPoint
er.java:140)
        at com.orientechnologies.orient.core.storage.impl.local.paginated.base.ODurablePage.getByteV
alue(ODurablePage.java:121)
        at com.orientechnologies.orient.core.index.sbtreebonsai.local.OSBTreeBonsaiBucket.<init>(OSB
TreeBonsaiBucket.java:163)
        at com.orientechnologies.orient.core.index.sbtreebonsai.local.OSBTreeBonsaiLocal.findBucket(
OSBTreeBonsaiLocal.java:1209)
        at com.orientechnologies.orient.core.index.sbtreebonsai.local.OSBTreeBonsaiLocal.loadEntries
Major(OSBTreeBonsaiLocal.java:736)
        at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.sbTree
BonsaiGetEntriesMajor(ONetworkProtocolBinary.java:1822)
        at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.execut
eRequest(ONetworkProtocolBinary.java:437)
        at com.orientechnologies.orient.server.network.protocol.binary.OBinaryNetworkProtocolAbstrac
t.execute(OBinaryNetworkProtocolAbstract.java:216)
        at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:65)
Sent run-time exception to the client /127.0.0.1:58850: com.orientechnologies.common.directmemory.OD
irectMemoryViolationException: Negative offset was provided
com.orientechnologies.common.directmemory.ODirectMemoryViolationException: Negative offset was provi
ded
        at com.orientechnologies.common.directmemory.ODirectMemoryPointer.rangeCheck(ODirectMemoryPo
inter.java:209)
        at com.orientechnologies.common.directmemory.ODirectMemoryPointer.getByte(ODirectMemoryPoint
er.java:140)
        at com.orientechnologies.orient.core.storage.impl.local.paginated.base.ODurablePage.getByteV
alue(ODurablePage.java:121)
        at com.orientechnologies.orient.core.index.sbtreebonsai.local.OSBTreeBonsaiBucket.<init>(OSB
TreeBonsaiBucket.java:163)
        at com.orientechnologies.orient.core.index.sbtreebonsai.local.OSBTreeBonsaiLocal.findBucket(
OSBTreeBonsaiLocal.java:1209)
        at com.orientechnologies.orient.core.index.sbtreebonsai.local.OSBTreeBonsaiLocal.loadEntries
Major(OSBTreeBonsaiLocal.java:736)
        at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.sbTree
BonsaiGetEntriesMajor(ONetworkProtocolBinary.java:1822)
        at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.execut
eRequest(ONetworkProtocolBinary.java:437)
        at com.orientechnologies.orient.server.network.protocol.binary.OBinaryNetworkProtocolAbstrac
t.execute(OBinaryNetworkProtocolAbstract.java:216)
        at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:65)
Sent run-time exception to the client /127.0.0.1:59176: com.orientechnologies.common.directmemory.OD
irectMemoryViolationException: Provided offset [19308902] is more than size of allocated area  [6555
2]
com.orientechnologies.common.directmemory.ODirectMemoryViolationException: Provided offset [19308902
] is more than size of allocated area  [65552]
        at com.orientechnologies.common.directmemory.ODirectMemoryPointer.rangeCheck(ODirectMemoryPo
inter.java:215)
        at com.orientechnologies.common.directmemory.ODirectMemoryPointer.getByte(ODirectMemoryPoint
er.java:140)
        at com.orientechnologies.orient.core.storage.impl.local.paginated.base.ODurablePage.getByteV
alue(ODurablePage.java:121)
        at com.orientechnologies.orient.core.index.sbtreebonsai.local.OSBTreeBonsaiBucket.<init>(OSB
TreeBonsaiBucket.java:163)
        at com.orientechnologies.orient.core.index.sbtreebonsai.local.OSBTreeBonsaiLocal.findBucket(
OSBTreeBonsaiLocal.java:1209)
        at com.orientechnologies.orient.core.index.sbtreebonsai.local.OSBTreeBonsaiLocal.loadEntries
Major(OSBTreeBonsaiLocal.java:736)
        at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.sbTree
BonsaiGetEntriesMajor(ONetworkProtocolBinary.java:1822)
        at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.execut
eRequest(ONetworkProtocolBinary.java:437)
        at com.orientechnologies.orient.server.network.protocol.binary.OBinaryNetworkProtocolAbstrac
t.execute(OBinaryNetworkProtocolAbstract.java:216)
        at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:65)
Sent run-time exception to the client /127.0.0.1:59176: com.orientechnologies.common.directmemory.OD
irectMemoryViolationException: Provided offset [19308902] is more than size of allocated area  [6555
2]
com.orientechnologies.common.directmemory.ODirectMemoryViolationException: Provided offset [19308902
] is more than size of allocated area  [65552]
        at com.orientechnologies.common.directmemory.ODirectMemoryPointer.rangeCheck(ODirectMemoryPo
inter.java:215)
        at com.orientechnologies.common.directmemory.ODirectMemoryPointer.getByte(ODirectMemoryPoint
er.java:140)
        at com.orientechnologies.orient.core.storage.impl.local.paginated.base.ODurablePage.getByteV
alue(ODurablePage.java:121)
        at com.orientechnologies.orient.core.index.sbtreebonsai.local.OSBTreeBonsaiBucket.<init>(OSB
TreeBonsaiBucket.java:163)
        at com.orientechnologies.orient.core.index.sbtreebonsai.local.OSBTreeBonsaiLocal.findBucket(
OSBTreeBonsaiLocal.java:1209)
        at com.orientechnologies.orient.core.index.sbtreebonsai.local.OSBTreeBonsaiLocal.loadEntries
Major(OSBTreeBonsaiLocal.java:736)
        at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.sbTree
BonsaiGetEntriesMajor(ONetworkProtocolBinary.java:1822)
        at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.execut
eRequest(ONetworkProtocolBinary.java:437)
        at com.orientechnologies.orient.server.network.protocol.binary.OBinaryNetworkProtocolAbstrac
t.execute(OBinaryNetworkProtocolAbstract.java:216)
        at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:65)
Sent run-time exception to the client /127.0.0.1:59176: com.orientechnologies.common.directmemory.OD
irectMemoryViolationException: Provided offset [19308902] is more than size of allocated area  [6555
2]
com.orientechnologies.common.directmemory.ODirectMemoryViolationException: Provided offset [19308902
] is more than size of allocated area  [65552]
        at com.orientechnologies.common.directmemory.ODirectMemoryPointer.rangeCheck(ODirectMemoryPo
inter.java:215)
        at com.orientechnologies.common.directmemory.ODirectMemoryPointer.getByte(ODirectMemoryPoint
er.java:140)
        at com.orientechnologies.orient.core.storage.impl.local.paginated.base.ODurablePage.getByteV
alue(ODurablePage.java:121)
        at com.orientechnologies.orient.core.index.sbtreebonsai.local.OSBTreeBonsaiBucket.<init>(OSB
TreeBonsaiBucket.java:163)
        at com.orientechnologies.orient.core.index.sbtreebonsai.local.OSBTreeBonsaiLocal.findBucket(
OSBTreeBonsaiLocal.java:1209)
        at com.orientechnologies.orient.core.index.sbtreebonsai.local.OSBTreeBonsaiLocal.loadEntries
Major(OSBTreeBonsaiLocal.java:736)
        at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.sbTree
BonsaiGetEntriesMajor(ONetworkProtocolBinary.java:1822)
        at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.execut
eRequest(ONetworkProtocolBinary.java:437)
        at com.orientechnologies.orient.server.network.protocol.binary.OBinaryNetworkProtocolAbstrac
t.execute(OBinaryNetworkProtocolAbstract.java:216)
        at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:65)
Sent run-time exception to the client /127.0.0.1:59176: com.orientechnologies.common.directmemory.OD
irectMemoryViolationException: Negative offset was provided
com.orientechnologies.common.directmemory.ODirectMemoryViolationException: Negative offset was provi
ded
        at com.orientechnologies.common.directmemory.ODirectMemoryPointer.rangeCheck(ODirectMemoryPo
inter.java:209)
        at com.orientechnologies.common.directmemory.ODirectMemoryPointer.getByte(ODirectMemoryPoint
er.java:140)
        at com.orientechnologies.orient.core.storage.impl.local.paginated.base.ODurablePage.getByteV
alue(ODurablePage.java:121)
        at com.orientechnologies.orient.core.index.sbtreebonsai.local.OSBTreeBonsaiBucket.<init>(OSB
TreeBonsaiBucket.java:163)
        at com.orientechnologies.orient.core.index.sbtreebonsai.local.OSBTreeBonsaiLocal.findBucket(
OSBTreeBonsaiLocal.java:1209)
        at com.orientechnologies.orient.core.index.sbtreebonsai.local.OSBTreeBonsaiLocal.loadEntries
Major(OSBTreeBonsaiLocal.java:736)
        at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.sbTree
BonsaiGetEntriesMajor(ONetworkProtocolBinary.java:1822)
        at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.execut
eRequest(ONetworkProtocolBinary.java:437)
        at com.orientechnologies.orient.server.network.protocol.binary.OBinaryNetworkProtocolAbstrac
t.execute(OBinaryNetworkProtocolAbstract.java:216)
        at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:65)
```

**Comment by AaronSchulz** [comment]
In general, a first step would be to make the output of repair more robust, to see what it's doing a bit better.

**Comment by lvca** [comment]
We already improved `repair database` command.
