### ISSUE TITLE
Error during transasction commit

### ISSUE THREAD

**Issue by AaronSchulz** [orientechnologies/orientdb#3257]
After getting killed by Windows due to low system RAM (the fault of some other program wasting memory), I can't seem to issue writes to Orient anymore. "repair" just hangs, so can't use that. On any attempt to write anything I always get:
```
2014-12-22 11:30:17:545 SEVERE Internal server error:
com.orientechnologies.orient.core.exception.OStorageException: Error during transaction commit.
--> java.lang.NullPointerException [ONetworkProtocolHttpDb]Error during context close for db null
com.orientechnologies.orient.core.exception.OStorageException: Error during transaction commit.
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.commit(OAb
stractPaginatedStorage.java:924)
        at com.orientechnologies.orient.core.tx.OTransactionOptimistic.doCommit(OTransactionOptimist
ic.java:483)
        at com.orientechnologies.orient.core.tx.OTransactionOptimistic.commit(OTransactionOptimistic
.java:147)
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.commit(ODatabaseDocumen
tTx.java:2369)
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.commit(ODatabaseDocumen
tTx.java:2339)
        at com.tinkerpop.blueprints.impls.orient.OrientBaseGraph.shutdown(OrientBaseGraph.java:1128)

        at com.orientechnologies.orient.graph.sql.OGraphCommandExecutorSQLFactory.runInTx(OGraphComm
andExecutorSQLFactory.java:147)
        at com.orientechnologies.orient.graph.sql.OCommandExecutorSQLCreateEdge.execute(OCommandExec
utorSQLCreateEdge.java:114)
        at com.orientechnologies.orient.core.sql.OCommandExecutorSQLDelegate.execute(OCommandExecuto
rSQLDelegate.java:64)
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.executeCom
mand(OAbstractPaginatedStorage.java:1172)
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.command(OA
bstractPaginatedStorage.java:1161)
        at com.orientechnologies.orient.core.command.OCommandRequestTextAbstract.execute(OCommandReq
uestTextAbstract.java:63)
        at com.orientechnologies.orient.core.command.script.OCommandExecutorScript.executeSQLScript(
OCommandExecutorScript.java:331)
        at com.orientechnologies.orient.core.command.script.OCommandExecutorScript.executeSQL(OComma
ndExecutorScript.java:138)
        at com.orientechnologies.orient.core.command.script.OCommandExecutorScript.executeInContext(
OCommandExecutorScript.java:82)
        at com.orientechnologies.orient.core.command.script.OCommandExecutorScript.execute(OCommandE
xecutorScript.java:73)
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.executeCom
mand(OAbstractPaginatedStorage.java:1172)
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.command(OA
bstractPaginatedStorage.java:1161)
        at com.orientechnologies.orient.core.command.OCommandRequestTextAbstract.execute(OCommandReq
uestTextAbstract.java:63)
        at com.orientechnologies.orient.server.network.protocol.http.command.post.OServerCommandPost
Batch.execute(OServerCommandPostBatch.java:184)
        at com.orientechnologies.orient.server.network.protocol.http.ONetworkProtocolHttpAbstract.se
rvice(ONetworkProtocolHttpAbstract.java:200)
        at com.orientechnologies.orient.server.network.protocol.http.ONetworkProtocolHttpAbstract.ex
ecute(ONetworkProtocolHttpAbstract.java:600)
        at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:65)
Caused by: java.lang.NullPointerException
        at com.orientechnologies.orient.core.serialization.serializer.binary.impl.index.OCompositeKe
ySerializer.deserializeFromDirectMemoryObject(OCompositeKeySerializer.java:309)
        at com.orientechnologies.orient.core.serialization.serializer.binary.impl.index.OCompositeKe
ySerializer.deserializeFromDirectMemoryObject(OCompositeKeySerializer.java:44)
        at com.orientechnologies.orient.core.storage.impl.local.paginated.base.ODurablePage.deserial
izeFromDirectMemory(ODurablePage.java:117)
        at com.orientechnologies.orient.core.index.sbtree.local.OSBTreeBucket.getKey(OSBTreeBucket.j
ava:236)
        at com.orientechnologies.orient.core.index.sbtree.local.OSBTreeBucket.find(OSBTreeBucket.jav
a:131)
        at com.orientechnologies.orient.core.index.sbtree.local.OSBTree.findBucket(OSBTree.java:1526
)
        at com.orientechnologies.orient.core.index.sbtree.local.OSBTree.get(OSBTree.java:190)
        at com.orientechnologies.orient.core.index.engine.OSBTreeIndexEngine.get(OSBTreeIndexEngine.
java:226)
        at com.orientechnologies.orient.core.index.OIndexMultiValues.removeFromSnapshot(OIndexMultiV
alues.java:250)
        at com.orientechnologies.orient.core.index.OIndexAbstract.applyIndexTxEntry(OIndexAbstract.j
ava:1006)
        at com.orientechnologies.orient.core.index.OIndexAbstract.addTxOperation(OIndexAbstract.java
:673)
        at com.orientechnologies.orient.core.tx.OTransactionOptimistic$CommitIndexesCallback.run(OTr
ansactionOptimistic.java:98)
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.commit(OAb
stractPaginatedStorage.java:910)
        ... 22 more

2014-12-22 11:30:17:590 SEVERE Internal server error:
com.orientechnologies.orient.core.exception.OStorageException: Error during transaction commit.
--> java.lang.NullPointerException [ONetworkProtocolHttpDb]
```

**Comment by laa** [comment]
Hi,
Could you try the same case with wal fuzzy checkpoints implemented.

**Comment by AaronSchulz** [comment]
So if someone manually configures the WAL size manually can there be corruption on crashes or does it sanity check the config to prevent this?

**Comment by laa** [comment]
Hi,
In latest version of source code storage controls wal size itself without
users interference, it is impossible to configure it manually any more.


On Sat, Jan 10, 2015 at 12:12 PM, Aaron <notifications@github.com> wrote:

> So if someone manually configures the WAL size manually can there be
> corruption on crashes or does it sanity check the config to prevent this?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/orientechnologies/orientdb/issues/3257#issuecomment-69450795>
> .
>



-- 
Best regards,
Andrey Lomakin.

**Comment by AaronSchulz** [comment]
I can't reproduce this now; assuming the cause is fixed unless something new somehow comes up.

The issues with repair already have a bug.
