### ISSUE TITLE
Can't create light weight edge in 2.0 RC1 

### ISSUE THREAD

**Issue by bkkoo** [orientechnologies/orientdb#3271]
1. Create new database
2. alter database custom useLightweightEdges=true
3. create edge from A to B  

No light weight edge is created but the new edge document is created in stead

**Comment by bkkoo** [comment]
Test Case:

1. Create new database via studio web app with following setting:
  Name: Test1
  Server User: root
  Server Password: *****
  Advanced Options: checked 
  Storage Type: plocal
  Database type: graph
  Lightweight edges: checked (true)

2. Make sure that useLightweightEdges is enable by issue the follwing command at the console

   alter database custom useLightweightEdges=true

3. Check again to make sure that useLightweightEdges is enable
  - In studio web app: Database Management -> Configuration -> Custom Properties 
    useLightweightEdges is set to true.

4. Create 2 Vertex
   
   create vertex set name = "koo" (rid = #9:0)
   create vertex set name = "pop" (rid = #9:1)

5. Create Edge
  
   create edge from #9:1 to #9:0
   --> new heavy edge is create with rid = #10:0

   create edge E from #9:1 to #9:0
   --> new heavy edge is created with rid = #10:1

6. Creating new Edge type

   create class Rel extends E

   create edge Rel from #9:1 to #9:0

   --> new heavy edge is created with rid = #12:0


7. I code in scala and never found such problem. But when switching to 2.0RC1 with all orientdb lib dependency change to 2.0RC1 and create new database and enable useLightweightEdges when running following code

  val v1 = g.getVertex("#9:1")
  val v2 = g.getVertex("#9:2")
  v1.addEdge("Rel", v2)

  orientdb create class Rel that Extends E
  and then it create heavy weight edge

  but in 1.7.10 and 2.0M3 it does not create new Edge Class and not create heavy weight edge but it create lightWeightEdges!

**Comment by 8forty** [comment]
@bkkoo Note that your step 3. currently doesn't work, since studio shows the useLightweightEdges set to true no matter what it's real value is (see studio issue https://github.com/orientechnologies/orientdb-studio/issues/220)

**Comment by bkkoo** [comment]
@8forty Please take a look that I not only set it via studio but I set it in the terminal console too (on step 2)

**Comment by 8forty** [comment]
@bkkoo yes I saw that, just letting you know that studio is currently broken and won't show you the actual value of useLightweightEdges.

**Comment by carloprad** [comment]
I have the same problem:
here an SQL test case script:
```
ALTER DATABASE custom useLightweightEdges=true

CREATE CLASS first EXTENDS V

CREATE CLASS second EXTENDS first
        CREATE PROPERTY second.name STRING

CREATE CLASS secondPackage EXTENDS first
        CREATE PROPERTY secondPackage.name STRING

CREATE CLASS bridge EXTENDS E

CREATE VERTEX secondPackage set name='theName'
CREATE VERTEX second set name='nikname'

CREATE EDGE bridge FROM (SELECT FROM secondPackage WHERE name='theName') to (SELECT FROM second WHERE name='nikname')
```

Here the exception:
```
orientdb {db=TEST1}> ALTER DATABASE custom useLightweightEdges=true

Database updated successfully

orientdb {db=TEST1}> CREATE CLASS first EXTENDS V

Class created successfully. Total classes in database now: 11

orientdb {db=TEST1}> CREATE CLASS second EXTENDS first

Class created successfully. Total classes in database now: 12

orientdb {db=TEST1}> CREATE PROPERTY second.name STRING

Property created successfully with id=1

orientdb {db=TEST1}> CREATE CLASS secondPackage EXTENDS first

Class created successfully. Total classes in database now: 13

orientdb {db=TEST1}> CREATE PROPERTY secondPackage.name STRING

Property created successfully with id=1

orientdb {db=TEST1}> CREATE CLASS bridge EXTENDS E

Class created successfully. Total classes in database now: 14

orientdb {db=TEST1}> CREATE VERTEX secondPackage set name='theName'

Created vertex 'secondPackage#13:0{name:theName} v1' in 0.031000 sec(s).

orientdb {db=TEST1}> CREATE VERTEX second set name='nikname'

Created vertex 'second#12:0{name:nikname} v1' in 0.008000 sec(s).

orientdb {db=TEST1}> CREATE EDGE bridge FROM (SELECT FROM secondPackage WHERE name='theName') to (SELECT FROM second WHERE name='nikname')
[node1420713975911] error on executing distributed request 45 on local node: record_update(#12:0 v.2)
Cannot UPDATE the record #12:0 because the version is not the latest. Probably you are updating an old record or it has been modified by another user (db=v3 your=v2)
-> com.orientechnologies.orient.core.conflict.OVersionRecordConflictStrategy.checkVersions(OVersionRecordConflictStrategy.java:54)
-> com.orientechnologies.orient.core.conflict.OVersionRecordConflictStrategy.onUpdate(OVersionRecordConflictStrategy.java:41)
-> com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.checkAndIncrementVersion(OAbstractPaginatedStorage.java:2006)
-> com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.doUpdateRecord(OAbstractPaginatedStorage.java:1640)
-> com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.updateRecord(OAbstractPaginatedStorage.java:722)
-> com.orientechnologies.orient.server.distributed.ODistributedStorage.updateRecord(ODistributedStorage.java:559)
-> com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.executeSaveRecord(ODatabaseDocumentTx.java:1718)
-> com.orientechnologies.orient.core.tx.OTransactionNoTx.saveRecord(OTransactionNoTx.java:94)
-> com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.save(ODatabaseDocumentTx.java:2270)
-> com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.save(ODatabaseDocumentTx.java:2107)
-> com.orientechnologies.orient.server.distributed.task.OUpdateRecordTask.execute(OUpdateRecordTask.java:82)
-> com.orientechnologies.orient.server.hazelcast.OHazelcastPlugin.executeOnLocalNode(OHazelcastPlugin.java:734)
-> com.orientechnologies.orient.server.hazelcast.ODistributedWorker.onMessage(ODistributedWorker.java:294)
-> com.orientechnologies.orient.server.hazelcast.ODistributedWorker.run(ODistributedWorker.java:117)Error on unmarshalling record #-1:-1 (com.orientechnologies.orient.core.exception.OConcurrentModificationException: Cannot UPDATE the record #12:0 because the version is not the latest. Probably you are updating an old record or it has been modified by another user (db=v3 your=v2))
Cannot UPDATE the record #12:0 because the version is not the latest. Probably you are updating an old record or it has been modified by another user (db=v3 your=v2)
-> com.orientechnologies.orient.core.conflict.OVersionRecordConflictStrategy.checkVersions(OVersionRecordConflictStrategy.java:54)
-> com.orientechnologies.orient.core.conflict.OVersionRecordConflictStrategy.onUpdate(OVersionRecordConflictStrategy.java:41)
-> com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.checkAndIncrementVersion(OAbstractPaginatedStorage.java:2006)
-> com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.doUpdateRecord(OAbstractPaginatedStorage.java:1640)
-> com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.updateRecord(OAbstractPaginatedStorage.java:722)
-> com.orientechnologies.orient.server.distributed.ODistributedStorage.updateRecord(ODistributedStorage.java:559)
-> com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.executeSaveRecord(ODatabaseDocumentTx.java:1718)
-> com.orientechnologies.orient.core.tx.OTransactionNoTx.saveRecord(OTransactionNoTx.java:94)
-> com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.save(ODatabaseDocumentTx.java:2270)
-> com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.save(ODatabaseDocumentTx.java:2107)
-> com.orientechnologies.orient.server.distributed.task.OUpdateRecordTask.execute(OUpdateRecordTask.java:82)
-> com.orientechnologies.orient.server.hazelcast.OHazelcastPlugin.executeOnLocalNode(OHazelcastPlugin.java:734)
-> com.orientechnologies.orient.server.hazelcast.ODistributedWorker.onMessage(ODistributedWorker.java:294)
-> com.orientechnologies.orient.server.hazelcast.ODistributedWorker.run(ODistributedWorker.java:117)
2015-01-08 15:37:56:026 WARN [ONetworkProtocolBinary] Cannot serialize record: e[#13:0->#12:0][#13:0-bridge->#12:0]
Created edge '[]' in 0.045000 sec(s).
```




My ODB server is started in distributed mode, though without a peer.

Note the hazelcast exception at DB creation time:
```
orientdb> CREATE DATABASE remote:localhost/TEST1 root root plocal

Creating database [remote:localhost/TEST1] using the storage type [plocal]...
2015-01-08 15:46:29:886 INFO  [node1420713975911] loaded database configuration from disk: /opt/orientdb/config/default-distributed-db-config.json [OHazelcastPlugin]
2015-01-08 15:46:29:892 INFO  [node1420713975911] updated distributed configuration for database: TEST1:
----------
{
  "autoDeploy": true,
  "hotAlignment": false,
  "executionMode": "undefined",
  "readQuorum": 1,
  "writeQuorum": 2,
  "failureAvailableNodesLessQuorum": false,
  "readYourWrites": true,"clusters":{
    "internal": {
},
    "index": {
},
    "*": {
  "servers": ["<NEW_NODE>"]
}
    },
  "version": 0
}
---------- [OHazelcastPlugin]
2015-01-08 15:46:36:643 INFO  [node1420713975911] adding node 'node1420713975911' in partition: db=TEST1 [*] [OHazelcastDistributedDatabase]
2015-01-08 15:46:36:645 INFO  [node1420713975911] received added status node1420713975911.TEST1=OFFLINE [OHazelcastPlugin]
2015-01-08 15:46:36:648 INFO  [node1420713975911] updated distributed configuration for database: TEST1:
----------
{
  "autoDeploy": true,
  "hotAlignment": false,
  "executionMode": "undefined",
  "readQuorum": 1,
  "writeQuorum": 2,
  "failureAvailableNodesLessQuorum": false,
  "readYourWrites": true,"clusters":{
    "internal": {
},
    "index": {
},
    "*": {
  "servers": ["node1420713975911","<NEW_NODE>"]
}
    },
  "version": 1
}
---------- [OHazelcastPlugin]
2015-01-08 15:46:36:648 INFO  [node1420713975911] Saving distributed configuration file for database 'TEST1' to: /opt/orientdb/databases/TEST1/distributed-config.json [OHazelcastPlugin]
2015-01-08 15:46:36:653 INFO  [node1420713975911] updated distributed configuration for database: TEST1:
----------
{
  "version": 1,
  "autoDeploy": true,
  "hotAlignment": false,
  "executionMode": "undefined",
  "readQuorum": 1,
  "writeQuorum": 2,
  "failureAvailableNodesLessQuorum": false,
  "readYourWrites": true,"clusters":{
    "internal": {
},
    "index": {
},
    "*": {
  "servers": ["node1420713975911","<NEW_NODE>"]
}
    }
}
---------- [OHazelcastPlugin]
2015-01-08 15:46:36:654 INFO  [node1420713975911] Saving distributed configuration file for database 'TEST1' to: /opt/orientdb/databases/TEST1/distributed-config.json [OHazelcastPlugin][192.168.202.24]:2434 [orientdb] [3.3] hz._hzInstance_1_orientdb.event-1 caught an exception while processing task:com.hazelcast.spi.impl.EventServiceImpl$LocalEventDispatcher@1ed7809a
java.lang.NullPointerException
        at com.orientechnologies.orient.server.OClientConnectionManager.pushDistribCfg2Clients(OClientConnectionManager.java:297)
        at com.orientechnologies.orient.server.hazelcast.OHazelcastPlugin.entryAdded(OHazelcastPlugin.java:598)
        at com.hazelcast.map.MapEventPublishingService.dispatch0(MapEventPublishingService.java:85)
        at com.hazelcast.map.MapEventPublishingService.dispatchEntryEventData(MapEventPublishingService.java:64)
        at com.hazelcast.map.MapEventPublishingService.dispatchEvent(MapEventPublishingService.java:39)
        at com.hazelcast.map.MapEventPublishingService.dispatchEvent(MapEventPublishingService.java:17)
        at com.hazelcast.map.MapService.dispatchEvent(MapService.java:76)
        at com.hazelcast.map.MapService.dispatchEvent(MapService.java:51)
        at com.hazelcast.spi.impl.EventServiceImpl$LocalEventDispatcher.run(EventServiceImpl.java:658)
        at com.hazelcast.util.executor.StripedExecutor$Worker.process(StripedExecutor.java:189)
        at com.hazelcast.util.executor.StripedExecutor$Worker.run(StripedExecutor.java:173)

2015-01-08 15:46:36:662 INFO  [node1420713975911] found no previous messages in queue orientdb.node.node1420713975911.TEST1.request [OHazelcastDistributedMessageService]
2015-01-08 15:46:36:671 INFO  [node1420713975911] Installing distributed storage on database 'TEST1' [ODistributedStorage]
2015-01-08 15:46:36:673 INFO  [node1420713975911] found no previous messages in queue orientdb.node.node1420713975911.TEST1.insert.request [OHazelcastDistributedMessageService]
2015-01-08 15:46:36:676 INFO  [node1420713975911] Publishing online status for database node1420713975911.TEST1... [OHazelcastDistributedDatabase]
2015-01-08 15:46:36:678 INFO  [node1420713975911] Installing distributed storage on database 'TEST1' [ODistributedStorage]
2015-01-08 15:46:36:679 INFO  [node1420713975911] received updated status node1420713975911.TEST1=ONLINE [OHazelcastPlugin]
2015-01-08 15:46:39:726 INFO  Created database 'TEST1' of type 'plocal' [ONetworkProtocolBinary]
Connecting to database [remote:localhost/TEST1] with user 'admin'...OK

DISTRIBUTED CONFIGURATION:
{
  "members": [{
      "id": "591c2451-c42d-4e9f-a4af-24c8c85ae1b8",
      "name": "node1420713975911",
      "startedOn": "2015-01-08 15:45:56",
      "listeners": [{"protocol":"ONetworkProtocolBinary","listen":"192.168.202.24:2424"},{"protocol":"ONetworkProtocolHttpDb","listen":"192.168.202.24:2480"}],
      "databases": []
      }
  ],
  "localName": "_hzInstance_1_orientdb",
  "localId": "591c2451-c42d-4e9f-a4af-24c8c85ae1b8"
}
Database created successfully.

Current database is: remote:localhost/TEST1
```

**Comment by lvca** [comment]
@carloprad what release?

**Comment by carloprad** [comment]
latest snapshot

**Comment by luigidellaquila** [comment]
creation of lightweight edges was fixed. Could you try it on latest sources ("develop" branch)?

@carloprad I think that in distributed mode there is another kind of problem, I'm seeing concurrent modification exceptions there. For this reason I'm leaving this open and assigning it to @lvca for a check

**Comment by lvca** [comment]
@carloprad tested with 2.0-SNAPSHOT and works.

**Comment by carloprad** [comment]
The problem reappears with the 2.0 final version, here the test case:
- 2 ODB servers in distributed mode
- OS: linux 64 bit
- JDK: oracle 1.8.25 64 bit
- create a new database having only 1 server active
- start the second server, and verify the correct synchronization
- execute this script:
```
connect remote:localhost/test admin admin

alter database custom useLightweightEdges=true

create class Foo extends V
create property Foo.key String
CREATE INDEX FooKey on Foo(key) UNIQUE_HASH_INDEX

create class Bar extends V
create property Bar.key String
CREATE INDEX BarKey on Bar(key) UNIQUE_HASH_INDEX

create class knows extends E

create vertex Foo set key = 'kf001'
create vertex Bar set key = 'kb001'
create edge knows FROM (SELECT FROM Foo WHERE key='kf001') to (SELECT FROM Bar WHERE key='kb001')

select from knows
```

The "create edge" command seems to work, but the edge is not created. Here the output:
```
orientdb> connect remote:localhost/test admin admin

Connecting to database [remote:localhost/test] with user 'admin'...OK

DISTRIBUTED CONFIGURATION:
{
  "members": [{
      "id": "e5c82544-bbe9-4c54-9ba8-e5e5155b29af",
      "name": "nodo-1",
      "startedOn": "2015-01-21 12:47:04",
      "listeners": [{"protocol":"ONetworkProtocolBinary","listen":"192.168.202.223:2424"},{"protocol":"ONetworkProtocolHttpDb","listen":"192.168.202.223:2480"}],
      "databases": []
      },{
      "id": "1ca2c94b-5cb6-4b8f-a4c7-a2cfacfcd1d4",
      "name": "nodo-2",
      "startedOn": "2015-01-21 12:48:24",
      "listeners": [{"protocol":"ONetworkProtocolBinary","listen":"192.168.202.24:2424"},{"protocol":"ONetworkProtocolHttpDb","listen":"192.168.202.24:2480"}],
      "databases": []
      }
  ],
  "localName": "_hzInstance_1_orientdb",
  "localId": "e5c82544-bbe9-4c54-9ba8-e5e5155b29af"
}
orientdb {db=test}> alter database custom useLightweightEdges=true

Database updated successfully

orientdb {db=test}> create class Foo extends V

Class created successfully. Total classes in database now: 11

orientdb {db=test}> create property Foo.key String

Property created successfully with id=1

orientdb {db=test}> CREATE INDEX FooKey on Foo(key) UNIQUE_HASH_INDEX


Creating index...
Created index successfully with 0 entries in 3.152000 sec(s).


Index created successfully
orientdb {db=test}> create class Bar extends V

Class created successfully. Total classes in database now: 12

orientdb {db=test}> create property Bar.key String

Property created successfully with id=1

orientdb {db=test}> CREATE INDEX BarKey on Bar(key) UNIQUE_HASH_INDEX


Creating index...
Created index successfully with 0 entries in 2.894000 sec(s).


Index created successfully
orientdb {db=test}> create class knows extends E

Class created successfully. Total classes in database now: 13

orientdb {db=test}> create vertex Foo set key = 'kf001'

Created vertex 'Foo#18:0{key:kf001} v1' in 0.153000 sec(s).

orientdb {db=test}> create vertex Bar set key = 'kb001'

Created vertex 'Bar#19:0{key:kb001} v1' in 0.025000 sec(s).

orientdb {db=test}> create edge knows FROM (SELECT FROM Foo WHERE key='kf001') to (SELECT FROM Bar WHERE key='kb001')

Created edge '[knows{in:#19:0,out:#18:0}]' in 0.215000 sec(s).

orientdb {db=test}> select from knows


0 item(s) found. Query executed in 0.004 sec(s).
```

**Comment by lvca** [comment]
It's not an issue: in case of lightweight edges you can't query the class because there is no record on it. Look at: http://www.orientechnologies.com/docs/last/orientdb.wiki/Lightweight-Edges.html

**Comment by carloprad** [comment]
OK, thanks!
