### ISSUE TITLE
Bug with Export / Import and Record level security 

### ISSUE THREAD

**Issue by Bretto** [orientechnologies/orientdb#3279]
senario:

```
 create database remote:localhost/exportDB brett brett plocal
 create database remote:localhost/importDB brett brett plocal

 connect remote:localhost/exportDB brett brett

 alter class V superclass orestricted
 alter class E superclass orestricted
 alter class OIdentity superclass OTriggered

 insert into orole set name = 'visitor', mode = 0
 update orole set inheritedRole = (select from orole where name = 'reader') where name = 'visitor'
 update orole put rules = "database.cluster.ouser", 3 where name = "visitor"
 update orole put rules = "database.class.ouser", 3 where name = "visitor"

 insert into OUser set name = 'visitor', status = 'ACTIVE', password = 'visitor', roles = [#4:3]

 CREATE CLASS AppData extends V
 CREATE PROPERTY AppData.data STRING

 connect remote:localhost/exportDB visitor visitor
 insert into OUser set name = 'user1', status = 'ACTIVE', password = 'user1' , roles = [#4:2]

 connect remote:localhost/exportDB user1 user1
 insert into AppData (data) values ('testData1')

 connect remote:localhost/exportDB brett brett
 DELETE VERTEX from appdata where data='testData1'
 delete from ouser where name='user1'

 connect remote:localhost/exportDB visitor visitor
 insert into OUser set name = 'user2', status = 'ACTIVE', password = 'user2' , roles = [#4:2]

 connect remote:localhost/exportDB user2 user2
 insert into AppData (data) values ('testData2')

 export database exportDB
```

ok now try to import the exportDB

```
connect remote:localhost/importDB brett brett 
import database /Users/Separ8/Documents/workspace/orientdb-community-2.0-rc1/bin/exportDB.json.gz 
```

Error

```
Importing database database /Users/Separ8/Documents/workspace/orientdb-community-2.0-rc1/bin/exportDB.json.gz...
Started import of database 'remote:localhost/importDB' from /Users/Separ8/Documents/workspace/orientdb-community-2.0-rc1/bin/exportDB.json.gz...
Non merge mode (-merge=false): removing all default non security classes
- Class ORIDs was removed.
- Class OFunction was removed.
- Class E was removed.
- Class V was removed.
- Class ORestricted was removed.
- Class OSchedule was removed.
- Class OTriggered was removed.
Removed 7 classes.
Importing database info...OK
Importing clusters...
- Creating cluster 'internal'...OK, assigned id=0
- Creating cluster 'default'...OK, assigned id=3
- Creating cluster 'orole'...OK, assigned id=4
- Creating cluster 'ouser'...OK, assigned id=5
- Creating cluster 'ofunction'...OK, assigned id=6
- Creating cluster 'oschedule'...OK, assigned id=7
- Creating cluster 'orids'...OK, assigned id=8
- Creating cluster 'v'...OK, assigned id=9
- Creating cluster 'e'...OK, assigned id=10
- Creating cluster 'appdata'...OK, assigned id=11
- Creating cluster '_studio'...OK, assigned id=12
Rebuilding indexes of truncated clusters ...
Done 2 indexes were rebuilt.
Done. Imported 11 clusters
Importing database schema...OK (12 classes)

Importing records...Error importing record #-1:-1. Source line 0, column 19840
Error on database import happened just before line 0, column 19841
com.orientechnologies.orient.enterprise.channel.binary.OResponseProcessingException: Exception during response processing.
    at com.orientechnologies.orient.enterprise.channel.binary.OChannelBinaryAsynchClient.throwSerializedException(OChannelBinaryAsynchClient.java:441)
    at com.orientechnologies.orient.enterprise.channel.binary.OChannelBinaryAsynchClient.handleStatus(OChannelBinaryAsynchClient.java:396)
    at com.orientechnologies.orient.enterprise.channel.binary.OChannelBinaryAsynchClient.beginResponse(OChannelBinaryAsynchClient.java:282)
    at com.orientechnologies.orient.enterprise.channel.binary.OChannelBinaryAsynchClient.beginResponse(OChannelBinaryAsynchClient.java:171)
    at com.orientechnologies.orient.client.remote.OStorageRemote.beginResponse(OStorageRemote.java:1852)
    at com.orientechnologies.orient.client.remote.OStorageRemote.createRecord(OStorageRemote.java:355)
    at com.orientechnologies.orient.client.remote.OStorageRemoteThread.createRecord(OStorageRemoteThread.java:243)
    at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.executeSaveRecord(ODatabaseDocumentTx.java:1712)
    at com.orientechnologies.orient.core.tx.OTransactionNoTx.saveRecord(OTransactionNoTx.java:94)
    at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.save(ODatabaseDocumentTx.java:2270)
    at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.save(ODatabaseDocumentTx.java:117)
    at com.orientechnologies.orient.core.record.impl.ODocument.save(ODocument.java:1672)
    at com.orientechnologies.orient.core.record.impl.ODocument.save(ODocument.java:1663)
    at com.orientechnologies.orient.core.record.impl.ODocument.save(ODocument.java:71)
    at com.orientechnologies.orient.core.db.tool.ODatabaseImport.importRecord(ODatabaseImport.java:1291)
    at com.orientechnologies.orient.core.db.tool.ODatabaseImport.importRecords(ODatabaseImport.java:1187)
    at com.orientechnologies.orient.core.db.tool.ODatabaseImport.importDatabase(ODatabaseImport.java:425)
    at com.orientechnologies.orient.console.OConsoleDatabaseApp.importDatabase(OConsoleDatabaseApp.java:1538)
    at com.orientechnologies.orient.graph.console.OGremlinConsole.importDatabase(OGremlinConsole.java:124)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:601)
    at com.orientechnologies.common.console.OConsoleApplication.execute(OConsoleApplication.java:381)
    at com.orientechnologies.common.console.OConsoleApplication.executeCommands(OConsoleApplication.java:246)
    at com.orientechnologies.common.console.OConsoleApplication.run(OConsoleApplication.java:135)
    at com.orientechnologies.orient.graph.console.OGremlinConsole.main(OGremlinConsole.java:62)
Caused by: com.orientechnologies.orient.core.exception.OValidationException: The field 'AppData._allow' has been declared as LINKSET but contains a null record (probably a deleted record?)
    at com.orientechnologies.orient.core.record.impl.ODocument.validateLink(ODocument.java:443)
    at com.orientechnologies.orient.core.record.impl.ODocument.validateLinkCollection(ODocument.java:430)
    at com.orientechnologies.orient.core.record.impl.ODocument.validateField(ODocument.java:281)
    at com.orientechnologies.orient.core.record.impl.ODocument.validate(ODocument.java:1905)
    at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.save(ODatabaseDocumentTx.java:2214)
    at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.save(ODatabaseDocumentTx.java:2107)
    at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.save(ODatabaseDocumentTx.java:117)
    at com.orientechnologies.orient.server.network.protocol.binary.OBinaryNetworkProtocolAbstract.createRecord(OBinaryNetworkProtocolAbstract.java:349)
    at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.createRecord(ONetworkProtocolBinary.java:1373)
    at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.executeRequest(ONetworkProtocolBinary.java:350)
    at com.orientechnologies.orient.server.network.protocol.binary.OBinaryNetworkProtocolAbstract.execute(OBinaryNetworkProtocolAbstract.java:216)
    at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:65)

Error: com.orientechnologies.orient.core.db.tool.ODatabaseExportException: Error on importing database 'importDB' from file: /Users/Separ8/Documents/workspace/orientdb-community-2.0-rc1/bin/exportDB.json.gz

Error: com.orientechnologies.orient.enterprise.channel.binary.OResponseProcessingException: Exception during response processing.

Error: com.orientechnologies.orient.core.exception.OValidationException: The field 'AppData._allow' has been declared as LINKSET but contains a null record (probably a deleted record?)
```

the issue lies with the delete of a user record, if you don't delete a user and its data the export import works...

**Comment by lvca** [comment]
@tglman issue attributed are missing, I'm adding them...

**Comment by nooruls143** [comment]
I am having the same issue when I am upgrading the version 1.7.x to 2.0.x and I just downloaded the latest version 2.0-rc1 from your website. Is that version fixed this issue?  My error log as below:

Error: com.orientechnologies.orient.core.db.tool.ODatabaseExportException: Error on importing database 'pricewiz' from file: /root/Downloads/pricewiz.export.gz

Error: com.orientechnologies.orient.enterprise.channel.binary.OResponseProcessingException: Exception during response processing.

Error: com.orientechnologies.orient.core.exception.OValidationException: The field 'Dic_Category.link_category' has been declared as LINKSET but contains a null record (probably a deleted record?)

**Comment by n0lf** [comment]
Is this fixed? I get this error, or a very similar one, when I try to import my 1.7.9 db to 2.0 (official release). 
I get: 

"The field person.emails has been declared as LINKSET but contains a null record (probably a deleted record?)"

I'm sure there is no broken link in this collection and even if there is it shouldn't break the import, right?

**Comment by lvca** [comment]
Do you have the full stack trace?

**Comment by n0lf** [comment]
com.orientechnologies.orient.core.exception.OValidationException: The field personal.emails' has been declared as LINKSET but contains a null record (probably a deleted record?)
	at com.orientechnologies.orient.core.record.impl.ODocument.validateLink(ODocument.java:451)
	at com.orientechnologies.orient.core.record.impl.ODocument.validateLinkCollection(ODocument.java:435)
	at com.orientechnologies.orient.core.record.impl.ODocument.validateField(ODocument.java:286)
	at com.orientechnologies.orient.core.record.impl.ODocument.validate(ODocument.java:1985)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.save(ODatabaseDocumentTx.java:2215)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.save(ODatabaseDocumentTx.java:2108)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.save(ODatabaseDocumentTx.java:117)
	at com.orientechnologies.orient.server.network.protocol.binary.OBinaryNetworkProtocolAbstract.createRecord(OBinaryNetworkProtocolAbstract.java:349)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.createRecord(ONetworkProtocolBinary.java:1375)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.executeRequest(ONetworkProtocolBinary.java:350)
	at com.orientechnologies.orient.server.network.protocol.binary.OBinaryNetworkProtocolAbstract.execute(OBinaryNetworkProtocolAbstract.java:216)
	at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:65)

Btw, I followed the instructions on https://raw.githubusercontent.com/wiki/orientechnologies/orientdb/Migration-from-1.7.x-to-2.0.x.md
