### ISSUE TITLE
NPE at OLocalHashTable.get(OLocalHashTable.java:392)

### ISSUE THREAD

**Issue by adithyank** [orientechnologies/orientdb#3282]
When index rebuilding was running in our Application that uses OrientDB in plocal mode, the application was shutdown. The below Exception came during this time

```
2014-12-24 19:05:04:559 INFO  --> 61.62% progress, 2,100,078 indexed so far (15,507 items/sec) [OIndexRebuildOutputListener]
2014-12-24 19:05:08:768 INFO  - storage: rcainv... [Orient]-- error on closing storage
com.orientechnologies.common.concur.OTimeoutException: Timeout on acquiring exclusive lock against resource of class: class com.orientechnologies.orient.core.index.OIndexUnique with timeou
t=5000
Owner thread : Thread[OrientDB rebuild indexes,5,main]
        at sun.misc.Unsafe.park(Native Method)
        at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:226)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedNanos(AbstractQueuedSynchronizer.java:1033)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer.tryAcquireSharedNanos(AbstractQueuedSynchronizer.java:1326)
        at java.util.concurrent.locks.ReentrantReadWriteLock$ReadLock.tryLock(ReentrantReadWriteLock.java:873)
        at com.orientechnologies.common.concur.resource.OSharedResourceAdaptive.acquireSharedLock(OSharedResourceAdaptive.java:145)
        at com.orientechnologies.common.concur.resource.OSharedResourceAdaptiveExternal.acquireSharedLock(OSharedResourceAdaptiveExternal.java:44)
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.readRecord(OAbstractPaginatedStorage.java:1198)
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.readRecord(OAbstractPaginatedStorage.java:644)
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.executeReadRecord(ODatabaseDocumentTx.java:1497)
        at com.orientechnologies.orient.core.tx.OTransactionNoTx.loadRecord(OTransactionNoTx.java:79)
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.load(ODatabaseDocumentTx.java:1367)
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.load(ODatabaseDocumentTx.java:123)
        at com.orientechnologies.orient.core.iterator.OIdentifiableIterator.readCurrentRecord(OIdentifiableIterator.java:278)
        at com.orientechnologies.orient.core.iterator.ORecordIteratorCluster.hasNext(ORecordIteratorCluster.java:132)
        at com.orientechnologies.orient.core.index.OIndexAbstract.indexCluster(OIndexAbstract.java:851)
        at com.orientechnologies.orient.core.index.OIndexAbstract.rebuild(OIndexAbstract.java:384)
        at com.orientechnologies.orient.core.index.OIndexManagerShared$RecreateIndexesTask.createAutomaticIndex(OIndexManagerShared.java:508)
        at com.orientechnologies.orient.core.index.OIndexManagerShared$RecreateIndexesTask.recreateIndex(OIndexManagerShared.java:486)
        at com.orientechnologies.orient.core.index.OIndexManagerShared$RecreateIndexesTask.recreateIndexes(OIndexManagerShared.java:460)
        at com.orientechnologies.orient.core.index.OIndexManagerShared$RecreateIndexesTask.run(OIndexManagerShared.java:449)
        at java.lang.Thread.run(Thread.java:745)

        at com.orientechnologies.common.concur.resource.OSharedResourceAdaptive.throwTimeoutException(OSharedResourceAdaptive.java:188)
        at com.orientechnologies.common.concur.resource.OSharedResourceAdaptive.acquireSharedLock(OSharedResourceAdaptive.java:165)
        at com.orientechnologies.common.concur.resource.OSharedResourceAdaptiveExternal.acquireSharedLock(OSharedResourceAdaptiveExternal.java:44)
        at com.orientechnologies.orient.core.index.OIndexAbstract.flush(OIndexAbstract.java:177)
        at com.orientechnologies.orient.core.index.OIndexManagerAbstract.flush(OIndexManagerAbstract.java:140)
        at com.orientechnologies.orient.core.index.OIndexManagerAbstract.close(OIndexManagerAbstract.java:233)
        at com.orientechnologies.orient.core.storage.OStorageAbstract.close(OStorageAbstract.java:104)
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.doClose(OAbstractPaginatedStorage.java:1731)
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.close(OAbstractPaginatedStorage.java:270)
        at com.orientechnologies.orient.core.Orient.closeAllStorages(Orient.java:249)
        at com.orientechnologies.orient.core.Orient.shutdown(Orient.java:206)
        at in.co.nmsworks.documenttdb.spi.impl.orient.OrientInternal.shutdown(OrientInternal.java:398)
```

After that, when we restarted our application, index rebuilding was happening.....
Also this time, the application got shutdown. Time time, all the below Exceptions came..

```
2014-12-24 19:37:51:658 INFO  - storage: rcainv... [Orient]
2014-12-24 19:37:51:659 INFO  --> OK, indexed 543,379 items in 23,452 ms [OIndexRebuildOutputListener]Error during addition of index {type:UNIQUE_HASH_INDEX,name:POR_NE.key,indexDefinition:{className:POR_NE,field:key,keyType:STRING,collate:default,nullValuesIgnored:true},indexDefinitionClass:com.orientechnologies.orient.core.index.OPropertyIndexDefinition,clusters:[1],mapRid:#1:46,algorithm:SBTREE,valueContainerAlgorithm:NONE}
com.orientechnologies.orient.core.index.OIndexException: Error on rebuilding the index for clusters: [por_ne]
        at com.orientechnologies.orient.core.index.OIndexAbstract.rebuild(OIndexAbstract.java:402)
        at com.orientechnologies.orient.core.index.OIndexManagerShared$RecreateIndexesTask.createAutomaticIndex(OIndexManagerShared.java:508)
        at com.orientechnologies.orient.core.index.OIndexManagerShared$RecreateIndexesTask.recreateIndex(OIndexManagerShared.java:486)
        at com.orientechnologies.orient.core.index.OIndexManagerShared$RecreateIndexesTask.recreateIndexes(OIndexManagerShared.java:460)
        at com.orientechnologies.orient.core.index.OIndexManagerShared$RecreateIndexesTask.run(OIndexManagerShared.java:449)
        at java.lang.Thread.run(Thread.java:745)
Caused by: com.orientechnologies.orient.core.exception.OStorageException: Storage rcainv is not opened.
        at com.orientechnologies.orient.core.storage.OStorageEmbedded.checkOpeness(OStorageEmbedded.java:243)
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.getPhysicalClusterNameById(OAbstractPaginatedStorage.java:962)
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.executeReadRecord(ODatabaseDocumentTx.java:1530)
        at com.orientechnologies.orient.core.tx.OTransactionNoTx.loadRecord(OTransactionNoTx.java:79)
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.load(ODatabaseDocumentTx.java:1367)
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.load(ODatabaseDocumentTx.java:123)
        at com.orientechnologies.orient.core.iterator.OIdentifiableIterator.readCurrentRecord(OIdentifiableIterator.java:278)
        at com.orientechnologies.orient.core.iterator.ORecordIteratorCluster.hasNext(ORecordIteratorCluster.java:132)
        at com.orientechnologies.orient.core.index.OIndexAbstract.indexCluster(OIndexAbstract.java:851)
        at com.orientechnologies.orient.core.index.OIndexAbstract.rebuild(OIndexAbstract.java:384)
        ... 5 more

```

THe below Exception came multiple times
```
2014-12-24 19:37:51:703 INFO  Start creation of index REL_DRI_PATTERN_TO_BRIDGE_PATTERN.enuk [OIndexManagerShared$RecreateIndexesTask]Error during addition of index {type:NOTUNIQUE_HASH_INDEX,name:REL_DRI_PATTERN_TO_BRIDGE_PATTERN.enuk,indexDefinition:{className:REL_DRI_PATTERN_TO_BRIDGE_PATTERN,field:enuk,keyType:STRING,collate:default,nullValuesIgnored:true},indexDefinitionClass:com.orientechnologies.orient.core.index.OPropertyIndexDefinition,clusters:[1],mapRid:#1:91,algorithm:SBTREE,valueContainerAlgorithm:SBTREEBONSAISET}
java.lang.NullPointerException
        at com.orientechnologies.orient.core.index.hashindex.local.OLocalHashTable.delete(OLocalHashTable.java:1242)
        at com.orientechnologies.orient.core.index.engine.OHashTableIndexEngine.delete(OHashTableIndexEngine.java:120)
        at com.orientechnologies.orient.core.index.OIndexAbstract.create(OIndexAbstract.java:227)
        at com.orientechnologies.orient.core.index.OIndexMultiValues.create(OIndexMultiValues.java:262)
        at com.orientechnologies.orient.core.index.OIndexMultiValues.create(OIndexMultiValues.java:51)
        at com.orientechnologies.orient.core.index.OIndexManagerShared$RecreateIndexesTask.createAutomaticIndex(OIndexManagerShared.java:501)
        at com.orientechnologies.orient.core.index.OIndexManagerShared$RecreateIndexesTask.recreateIndex(OIndexManagerShared.java:486)
        at com.orientechnologies.orient.core.index.OIndexManagerShared$RecreateIndexesTask.recreateIndexes(OIndexManagerShared.java:460)
        at com.orientechnologies.orient.core.index.OIndexManagerShared$RecreateIndexesTask.run(OIndexManagerShared.java:449)
        at java.lang.Thread.run(Thread.java:745)

```

After this, we restarted our application again. It did not trigger any index re-builidng and application got initialized successfully. Then when we tried to retrieve the documents, the below Exception is thrown every time with some classes.

```
java.lang.NullPointerException
        at com.orientechnologies.orient.core.index.hashindex.local.OLocalHashTable.get(OLocalHashTable.java:392) ~[orientdb-core-2.0-M3.jar:2.0-M3]
        at com.orientechnologies.orient.core.index.engine.OHashTableIndexEngine.get(OHashTableIndexEngine.java:155) ~[orientdb-core-2.0-M3.jar:2.0-M3]
        at com.orientechnologies.orient.core.index.OIndexMultiValues.get(OIndexMultiValues.java:65) ~[orientdb-core-2.0-M3.jar:2.0-M3]
        at com.orientechnologies.orient.core.index.OIndexMultiValues.get(OIndexMultiValues.java:51) ~[orientdb-core-2.0-M3.jar:2.0-M3]
        at com.orientechnologies.orient.core.index.OIndexAbstractDelegate.get(OIndexAbstractDelegate.java:59) ~[orientdb-core-2.0-M3.jar:2.0-M3]
        at com.orientechnologies.orient.core.index.OIndexTxAwareMultiValue.get(OIndexTxAwareMultiValue.java:272) ~[orientdb-core-2.0-M3.jar:2.0-M3]
        at com.orientechnologies.orient.core.index.OIndexTxAwareMultiValue.get(OIndexTxAwareMultiValue.java:40) ~[orientdb-core-2.0-M3.jar:2.0-M3]
        at in.co.nmsworks.documenttdb.db.DocDB.getDocTypeObjects(DocDB.java:114) ~[cygnetOTNMS.jar:?]
        at in.co.nmsworks.cygnet.telecom.fault.rcasia.inventory.store.RcaInvReader.getEntitiesByNonUniqueKeySearch(RcaInvReader.java:405) ~[cygnetOTNMS.jar:?]
```

Should I conclude, DB has got corrupted ?
Don't say 'yes' !!!

Pls advice

**Comment by laa** [comment]
Yes,
But if we stop server in the middle of index rebuild. 
We need either to wait till rebuild will be finished or remove index from system.
I will implement the first one.

**Comment by adithyank** [comment]
What will happen now when the application is killed (kill -9) during index rebuilding?
Will index rebuilding start again when the application gets restarted?

**Comment by laa** [comment]
Index rebuild is non tx operation.
So yes if you kill app during index rebuild all indexes will be rebuild.

On Tue, Jan 6, 2015 at 9:00 AM, K Adithyan <notifications@github.com> wrote:

> What will happen now when the application is killed (kill -9) during index
> rebuilding?
> Will index rebuilding start again when the application gets restarted?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/orientechnologies/orientdb/issues/3282#issuecomment-68832999>
> .
>



-- 
Best regards,
Andrey Lomakin.
