### ISSUE TITLE
Error on releasing a non acquired lock by the requester

### ISSUE THREAD

**Issue by azzazeli** [orientechnologies/orientdb#3291]
Hi,
I'm using orientdb version 1.7.10
After setting logger to 'Debug' level I've found following error in log file

```
2014-12-29 15:39:12 DEBUG OLocalPaginatedStorage(OrientDB <- BinaryClient (/127.0.0.1:63237)) - Error on record unlock
com.orientechnologies.common.concur.lock.OLockException: Error on releasing a non acquired lock by the requester 'Thread[OrientDB <- BinaryClient (/127.0.0.1:63237),5,OrientDB]' against the resource: '#11:13891'
        at com.orientechnologies.common.concur.lock.OLockManager.releaseLock(OLockManager.java:175)[orient-commons-1.7.10.jar:1.7.10]
        at com.orientechnologies.orient.core.storage.impl.local.paginated.OLocalPaginatedStorage.commit(OLocalPaginatedStorage.java:1126)[orientdb-core-1.7.10.jar:1.7.10]
        at com.orientechnologies.orient.core.tx.OTransactionOptimistic.doCommit(OTransactionOptimistic.java:469)[orientdb-core-1.7.10.jar:1.7.10]
        at com.orientechnologies.orient.core.tx.OTransactionOptimistic.commit(OTransactionOptimistic.java:148)[orientdb-core-1.7.10.jar:1.7.10]
        at com.orientechnologies.orient.core.db.record.ODatabaseRecordTx.commit(ODatabaseRecordTx.java:142)[orientdb-core-1.7.10.jar:1.7.10]
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.commit(ODatabaseDocumentTx.java:511)[orientdb-core-1.7.10.jar:1.7.10]
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.commit(ODatabaseDocumentTx.java:503)[orientdb-core-1.7.10.jar:1.7.10]
        at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.commit(ONetworkProtocolBinary.java:1096)[orientdb-server-1.7.10.jar:1.7.10]
        at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.executeRequest(ONetworkProtocolBinary.java:344)[orientdb-server-1.7.10.jar:1.7.10]
        at com.orientechnologies.orient.server.network.protocol.binary.OBinaryNetworkProtocolAbstract.execute(OBinaryNetworkProtocolAbstract.java:170)[orientdb-server-1.7.10.jar:1.7.10]
        at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:45)[orient-commons-1.7.10.jar:1.7.10]
```

Seems that error occurs for every operation. 

Is there a way to fix it?

Thanks,
Alex.

**Comment by laa** [comment]
I if you do not try we will never be sure about your concrete case (obviously), so you either should try RC or wait till final release.
