### ISSUE TITLE
"Error on fetching record" during index rebuild after OOM

### ISSUE THREAD

**Issue by AaronSchulz** [orientechnologies/orientdb#3295]
After a JVM OOM caused by a slow query, I had to kill the orient server and restart it. Upon restart, it did WAL recovery and started rebuilding the indexes. I see a few dozen errors like the following:

2014-12-29 12:34:24:187 INFO  --> 33.16% progress, 5,529,133 indexed so far (13,756 items/sec) [OIndexRebuildOutputListener]Error on fetching record d
uring browsing. The record has been skipped
com.orientechnologies.orient.core.exception.ODatabaseException: Error on retrieving record #11:5545453 (cluster: item)
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.executeReadRecord(ODatabaseDocumentTx.java:1601)
        at com.orientechnologies.orient.core.tx.OTransactionNoTx.loadRecord(OTransactionNoTx.java:80)
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.load(ODatabaseDocumentTx.java:1433)
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.load(ODatabaseDocumentTx.java:117)
        at com.orientechnologies.orient.core.iterator.OIdentifiableIterator.readCurrentRecord(OIdentifiableIterator.java:278)
        at com.orientechnologies.orient.core.iterator.ORecordIteratorCluster.hasNext(ORecordIteratorCluster.java:132)
        at com.orientechnologies.orient.core.index.OIndexAbstract.indexCluster(OIndexAbstract.java:904)
        at com.orientechnologies.orient.core.index.OIndexAbstract.rebuild(OIndexAbstract.java:391)
        at com.orientechnologies.orient.core.index.OIndexManagerShared$RecreateIndexesTask.createAutomaticIndex(OIndexManagerShared.java:507)
        at com.orientechnologies.orient.core.index.OIndexManagerShared$RecreateIndexesTask.recreateIndex(OIndexManagerShared.java:485)
        at com.orientechnologies.orient.core.index.OIndexManagerShared$RecreateIndexesTask.recreateIndexes(OIndexManagerShared.java:459)
        at com.orientechnologies.orient.core.index.OIndexManagerShared$RecreateIndexesTask.run(OIndexManagerShared.java:448)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ArrayIndexOutOfBoundsException
        at com.orientechnologies.orient.core.compression.impl.ONothingCompression.uncompress(ONothingCompression.java:49)
        at com.orientechnologies.orient.core.storage.impl.local.paginated.OPaginatedCluster.readRecord(OPaginatedCluster.java:558)
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.doReadRecord(OAbstractPaginatedStorage.java:1789)
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.readRecord(OAbstractPaginatedStorage.java:1421)
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.readRecord(OAbstractPaginatedStorage.java:690)
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.executeReadRecord(ODatabaseDocumentTx.java:1568)
        ... 12 more

Since WAL is enabled (syncOnFlush is on too) and all the updates where in SQL transactions, I wonder how this keeps happening. Shouldn't Orient be able to use the WAL to finish applying any changes? Is this actual corruption or just some other bug?

**Comment by laa** [comment]
Hi,
Could you provide example of operations which were lead to index rebuild ?

**Comment by AaronSchulz** [comment]
Lots was going on at the time so it's hard to recall, I think it was the query from https://github.com/orientechnologies/orientdb/issues/3260. 

I haven't ran into any corruption since the last batch of WAL changes. I'll keep an eye out if anything happens.

**Comment by AaronSchulz** [comment]
I tried doing edge updates while killing orient this morning. It looks like the index rebuild and recovery from the fuzzy checkpoint and wal worked fine. I'm not seeing any error or corruption. Less abrupt SIGINT kills worked fine too (e.g. not using shutdown.sh). I was planning on closing this today :)
