### ISSUE TITLE
OTimeoutException: Timeout on acquiring exclusive lock against resource of class: class OIndexNotUnique with timeout=5000

### ISSUE THREAD

**Issue by adithyank** [orientechnologies/orientdb#3302]
OrientDB Version : 2.0-M3

our software reads from doc db in multi threads while there is another only one thread creating records.......!

What is the reason for this Exception???
Does this mean that the writing thread's transaction has not been committed/rolledback in 30 seconds. If yes, I want to give you another input that all our transactions are committed and closed within 5 seconds from the time of db.begin()

```
com.orientechnologies.common.concur.OTimeoutException: Timeout on acquiring exclusive lock against resource of class: class com.orientechnologies.orient.core.index.OIndexNotUnique with timeout=5000
Owner thread : Thread[InventoryDataPersister,5,main]
        at sun.misc.Unsafe.unpark(Native Method)
        at java.util.concurrent.locks.LockSupport.unpark(LockSupport.java:152)
        at com.orientechnologies.common.concur.lock.OReadersWriterSpinLock.releaseWriteLock(OReadersWriterSpinLock.java:170)
        at com.orientechnologies.orient.core.index.hashindex.local.cache.OReadWriteDiskCache.openFile(OReadWriteDiskCache.java:150)
        at com.orientechnologies.orient.core.db.record.ridbag.sbtree.OIndexRIDContainer.resolveFileIdByName(OIndexRIDContainer.java:76)
        at com.orientechnologies.orient.core.db.record.ridbag.sbtree.OIndexRIDContainer.<init>(OIndexRIDContainer.java:53)
        at com.orientechnologies.orient.core.index.OIndexMultiValues.putInSnapshot(OIndexMultiValues.java:163)
        at com.orientechnologies.orient.core.index.OIndexAbstract.applyIndexTxEntry(OIndexAbstract.java:948)
        at com.orientechnologies.orient.core.index.OIndexAbstract.addTxOperation(OIndexAbstract.java:626)
        at com.orientechnologies.orient.core.tx.OTransactionOptimistic$CommitIndexesCallback.run(OTransactionOptimistic.java:93)
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.commit(OAbstractPaginatedStorage.java:864)
        at com.orientechnologies.orient.core.tx.OTransactionOptimistic.doCommit(OTransactionOptimistic.java:455)
        at com.orientechnologies.orient.core.tx.OTransactionOptimistic.commit(OTransactionOptimistic.java:142)
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.commit(ODatabaseDocumentTx.java:2261)
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.commit(ODatabaseDocumentTx.java:2231)
        at in.co.nmsworks.documenttdb.db.DocDB.commit(DocDB.java:482)
        at in.co.nmsworks.cygnet.telecom.fault.rcasia.inventory.store.RcaInvWriter.addAll(RcaInvWriter.java:118)
        at in.co.nmsworks.cygnet.telecom.fault.rcasia.inventory.store.RcaInvWriter.addAll(RcaInvWriter.java:76)
        at in.co.nmsworks.cygnet.telecom.fault.rcasia.inventory.dao.InventoryDAO.save(InventoryDAO.java:106)
        at in.co.nmsworks.cygnet.telecom.fault.rcasia.inventory.queue.InventoryDataPersister.saveDAOData(InventoryDataPersister.java:331)
        at in.co.nmsworks.cygnet.telecom.fault.rcasia.inventory.queue.InventoryDataPersister.processAddition(InventoryDataPersister.java:306)
        at in.co.nmsworks.cygnet.telecom.fault.rcasia.inventory.queue.InventoryDataPersister.run(InventoryDataPersister.java:71)


        at com.orientechnologies.common.concur.resource.OSharedResourceAdaptive.throwTimeoutException(OSharedResourceAdaptive.java:188) ~[orientdb-core-2.0-M3.jar:2.0-M3]
        at com.orientechnologies.common.concur.resource.OSharedResourceAdaptive.acquireSharedLock(OSharedResourceAdaptive.java:165) ~[orientdb-core-2.0-M3.jar:2.0-M3]
        at com.orientechnologies.common.concur.resource.OSharedResourceAdaptiveExternal.acquireSharedLock(OSharedResourceAdaptiveExternal.java:44) ~[orientdb-core-2.0-M3.jar:2.0-M3]
        at com.orientechnologies.orient.core.index.OIndexMultiValues.get(OIndexMultiValues.java:62) ~[orientdb-core-2.0-M3.jar:2.0-M3]
        at com.orientechnologies.orient.core.index.OIndexMultiValues.get(OIndexMultiValues.java:51) ~[orientdb-core-2.0-M3.jar:2.0-M3]
        at com.orientechnologies.orient.core.index.OIndexAbstractDelegate.get(OIndexAbstractDelegate.java:59) ~[orientdb-core-2.0-M3.jar:2.0-M3]
        at com.orientechnologies.orient.core.index.OIndexTxAwareMultiValue.get(OIndexTxAwareMultiValue.java:272) ~[orientdb-core-2.0-M3.jar:2.0-M3]
        at com.orientechnologies.orient.core.index.OIndexTxAwareMultiValue.get(OIndexTxAwareMultiValue.java:40) ~[orientdb-core-2.0-M3.jar:2.0-M3]
        at in.co.nmsworks.documenttdb.db.DocDB.getDocTypeObjects(DocDB.java:114) ~[cygnetOTNMS.jar:?]
        at in.co.nmsworks.cygnet.telecom.fault.rcasia.inventory.store.RcaInvReader.getEntitiesByNonUniqueKeySearch(RcaInvReader.java:406) ~[cygnetOTNMS.jar:?]
        at in.co.nmsworks.cygnet.telecom.fault.rcasia.inventory.store.RcaInvReader.getPointEntities(RcaInvReader.java:434) ~[cygnetOTNMS.jar:?]
        at in.co.nmsworks.cygnet.telecom.fault.rcasia.inventory.store.RcaInvReader.buildImpactAnalysisDataHolderForCTP(RcaInvReader.java:337) ~[cygnetOTNMS.jar:?]
        at in.co.nmsworks.cygnet.telecom.fault.rcasia.inventory.store.RcaInvReader.buildImpactAnalysisDataHolderForCTP(RcaInvReader.java:324) ~[cygnetOTNMS.jar:?]
        at in.co.nmsworks.cygnet.telecom.fault.rcasia.plug.impl.circuit.impact.node.constructor.impl2.CTPImpactAnalysisDataBuilder.buildImpactAnalysisData(CTPImpactAnalysisDataBuilder.java:40) ~[cygnetOTNMS.jar:?]
        at in.co.nmsworks.cygnet.telecom.fault.rcasia.plug.impl.circuit.impl2.CircuitPlugHelper.getImpactAnalysisDataHolder(CircuitPlugHelper.java:129) ~[cygnetOTNMS.jar:?]
        at in.co.nmsworks.cygnet.telecom.fault.rcasia.plug.impl.circuit.impl2.CircuitPlug.getImpactAnalysisDataHolder(CircuitPlug.java:234) ~[cygnetOTNMS.jar:?]
        at in.co.nmsworks.cygnet.telecom.fault.rcasia.plug.impl.circuit.impl2.CircuitPlug.analyze(CircuitPlug.java:106) [cygnetOTNMS.jar:?]
        at in.co.nmsworks.cygnet.telecom.fault.rcasia.plug.impl.circuit.impl2.CircuitPlug.onInventoryChange(CircuitPlug.java:265) [cygnetOTNMS.jar:?]
        at in.co.nmsworks.cygnet.telecom.fault.rcasia.plug.Plug.computeAndStore(Plug.java:121) [cygnetOTNMS.jar:?]
        at in.co.nmsworks.cygnet.telecom.fault.rcasia.server.PlugInvokationTask.getPlugResult(PlugInvokationTask.java:122) [cygnetOTNMS.jar:?]
        at in.co.nmsworks.cygnet.telecom.fault.rcasia.server.PlugInvokationTask.compute(PlugInvokationTask.java:67) [cygnetOTNMS.jar:?]
        at in.co.nmsworks.cygnet.telecom.fault.rcasia.server.PlugInvokationTask.compute(PlugInvokationTask.java:38) [cygnetOTNMS.jar:?]
        at java.util.concurrent.RecursiveTask.exec(RecursiveTask.java:93) [?:1.7.0_71]
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:334) [?:1.7.0_71]
        at java.util.concurrent.ForkJoinWorkerThread.execTask(ForkJoinWorkerThread.java:604) [?:1.7.0_71]
        at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:762) [?:1.7.0_71]
        at java.util.concurrent.ForkJoinPool.work(ForkJoinPool.java:646) [?:1.7.0_71]
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:398) [?:1.7.0_71]
```

By code, I understand that I have to increase `OGlobalConfiguration.MVRBTREE_TIMEOUT` to workaround this problem.

But, `OGlobalConfiguration.MVRBTREE_TIMEOUT` is deprecated...?
Is it the right way to increase this value or is there something else I have to do?

**Comment by laa** [comment]
Hi, 
I removed this timeout it is old legacy and it is not needed any way.

**Comment by adithyank** [comment]
Making it 0 means it will wait indefinitely?

**Comment by laa** [comment]
It was done to prevent deadlock in very early versions of product, now it
is not needed it will wait for some time but not indefinitely, lock uses
queue inside, so lock eventually will be acquired.

On Tue, Jan 6, 2015 at 8:36 AM, K Adithyan <notifications@github.com> wrote:

> Making it 0 means it will wait indefinitely?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/orientechnologies/orientdb/issues/3302#issuecomment-68831704>
> .
>



-- 
Best regards,
Andrey Lomakin.
