### ISSUE TITLE
Some Indices Corruption after proper OrientDB shutdown

### ISSUE THREAD

**Issue by adithyank** [orientechnologies/orientdb#3309]
When we restarted our application that hosts OrientDB in plocal mode, we saw the below lines in nohup.out...

```
2014-12-31 19:39:01:695 WARNING Cannot load index 'ChildKeyMSP11.k' from storage (rid=#1:319): rebuilt it from scratch [OIndexUnique]
2014-12-31 19:39:01:704 INFO  - Rebuilding index rcainv.ChildKeyMSP11.k (estimated 588232 items)... [OIndexRebuildOutputListener]
2014-12-31 19:39:01:728 INFO  --> OK, indexed 588,232 items in 24 ms [OIndexRebuildOutputListener]
2014-12-31 19:39:01:729 SEVERE Cannot rebuild index 'ChildKeyMSP11.k' from storage (rid=#1:319) because 'com.orientechnologies.orient.core.index.OIndexException: Error on rebuilding the index for clusters: [childkeymsp11]'. The index will be removed in configuration [OIndexUnique]
2014-12-31 19:39:02:434 INFO  - Rebuilding index rcainv.ChildKeyMSP11.k (estimated 588232 items)... [OIndexRebuildOutputListener]
2014-12-31 19:39:12:435 INFO  --> 86.19% progress, 506,969 indexed so far (50,696 items/sec) [OIndexRebuildOutputListener]
2014-12-31 19:39:13:818 INFO  --> OK, indexed 588,232 items in 11,384 ms [OIndexRebuildOutputListener]RCA Server ........................................................ [INITED]
```

No other information about other indices...

When the application starts functioning, lot of following Exceptions came.....

```
java.lang.NullPointerException
        at com.orientechnologies.orient.core.index.hashindex.local.OLocalHashTable.get(OLocalHashTable.java:392) ~[orientdb-core-2.0-M3.jar:2.0-M3]
        at com.orientechnologies.orient.core.index.engine.OHashTableIndexEngine.get(OHashTableIndexEngine.java:155) ~[orientdb-core-2.0-M3.jar:2.0-M3]
        at com.orientechnologies.orient.core.index.OIndexOneValue.get(OIndexOneValue.java:57) ~[orientdb-core-2.0-M3.jar:2.0-M3]
        at com.orientechnologies.orient.core.index.OIndexOneValue.get(OIndexOneValue.java:44) ~[orientdb-core-2.0-M3.jar:2.0-M3]
        at com.orientechnologies.orient.core.index.OIndexAbstractDelegate.get(OIndexAbstractDelegate.java:59) ~[orientdb-core-2.0-M3.jar:2.0-M3]
        at com.orientechnologies.orient.core.index.OIndexTxAwareOneValue.get(OIndexTxAwareOneValue.java:233) ~[orientdb-core-2.0-M3.jar:2.0-M3]
        at com.orientechnologies.orient.core.index.OIndexTxAwareOneValue.contains(OIndexTxAwareOneValue.java:253) ~[orientdb-core-2.0-M3.jar:2.0-M3]
```

When I saw the indexes through console, I got the below output. Lot of indices are with 0 size (where value must be there)

```
----------------------------------------------+------------+-----------------------+----------------+------------+
 NAME                                         | TYPE       |         CLASS         |     FIELDS     | RECORDS    |
----------------------------------------------+------------+-----------------------+----------------+------------+
 ASON_SNC.key                                 | UNIQUE_... | ASON_SNC              | key            |       2973 |
 ChildKey.k                                   | UNIQUE_... | ChildKey              | k              |     703743 |
 ChildKeyMSP11.k                              | UNIQUE_... | ChildKeyMSP11         | k              |     588232 |
 ChildKeySeq.k                                | UNIQUE_... | ChildKeySeq           | k              |          0 |
 ChildKeySNCP.k                               | UNIQUE_... | ChildKeySNCP          | k              |     587999 |
 CIRCUIT.key                                  | UNIQUE_... | CIRCUIT               | key            |          0 |
 CircuitRoute.k                               | UNIQUE_... | CircuitRoute          | k              |     106406 |
 CktMainSeqPat.ckt                            | UNIQUE_... | CktMainSeqPat         | ckt            |     508333 |
 CRNE.k                                       | UNIQUE_... | CRNE                  | k              |    3865413 |
 CRPoint.k                                    | UNIQUE     | CRPoint               | k              |    8167347 |
 CRTLWithCTP.k                                | UNIQUE_... | CRTLWithCTP           | k              |          0 |
 CRTLWithoutCTP.k                             | UNIQUE_... | CRTLWithoutCTP        | k              |     605316 |
 DER_PAT_ASON_SNCP.endNEName                  | NOTUNIQ... | DER_PAT_ASON_SNCP     | endNEName      |          0 |
 DER_PAT_ASON_SNCP.key                        | UNIQUE_... | DER_PAT_ASON_SNCP     | key            |          0 |
 DER_PAT_ASON_SNCP.startNEName                | NOTUNIQ... | DER_PAT_ASON_SNCP     | startNE...     |          0 |
 DER_PAT_COMBINED_UNI_DIR_PATH.key            | UNIQUE_... | DER_PAT_COMBINED_UN...| key            |        385 |
 DER_PAT_DOUBLE_INTERCONNECT.key              | UNIQUE_... | DER_PAT_DOUBLE_INTE...| key            |          2 |
 DER_PAT_DRI.key                              | UNIQUE_... | DER_PAT_DRI           | key            |          2 |
 DER_PAT_FOUR_FIBER_BLSR.key                  | UNIQUE_... | DER_PAT_FOUR_FIBER_...| key            |          0 |
 DER_PAT_MIXED_SNCP.endNEName                 | NOTUNIQ... | DER_PAT_MIXED_SNCP    | endNEName      |         37 |
 DER_PAT_MIXED_SNCP.key                       | UNIQUE_... | DER_PAT_MIXED_SNCP    | key            |        440 |
 DER_PAT_MIXED_SNCP.startNEName               | NOTUNIQ... | DER_PAT_MIXED_SNCP    | startNE...     |          0 |
 DER_PAT_OPEN_CIRCUIT.key                     | UNIQUE_... | DER_PAT_OPEN_CIRCUIT  | key            |      27236 |
 DER_PAT_SEQUENCE.key                         | UNIQUE_... | DER_PAT_SEQUENCE      | key            |     269734 |
 DER_PAT_SNCP.key                             | UNIQUE_... | DER_PAT_SNCP          | key            |      73041 |
 DER_PAT_TL_PGP_TYPE_MISMATCH.key             | UNIQUE_... | DER_PAT_TL_PGP_TYPE...| key            |          0 |
 DER_PAT_TL_WITHOUT_CTP_MSP_PAIR.key          | UNIQUE_... | DER_PAT_TL_WITHOUT_...| key            |          0 |
 DER_PAT_TWO_FIBER_BLSR.key                   | UNIQUE_... | DER_PAT_TWO_FIBER_BLSR| key            |          0 |
 dictionary                                   | DICTIONARY |                       |                |          0 |
 NWScanPlugGraph.k                            | UNIQUE_... | NWScanPlugGraph       | k              |     508333 |
 OBJECT_EQPT.key                              | UNIQUE_... | OBJECT_EQPT           | key            |          0 |
 OBJECT_PTP.key                               | UNIQUE_... | OBJECT_PTP            | key            |     973128 |
 ORole.name                                   | UNIQUE     | ORole                 | name           |          3 |
 OUser.name                                   | UNIQUE     | OUser                 | name           |          4 |
 PAT_ASON_TL.asonSeqUniqueKey                 | NOTUNIQ... | PAT_ASON_TL           | asonSeq...     |       5868 |
 PAT_ASON_TL.key                              | UNIQUE_... | PAT_ASON_TL           | key            |       5868 |
 PAT_MSP1_1_TOPOLOGY.key                      | UNIQUE_... | PAT_MSP1_1_TOPOLOGY   | key            |          0 |
 PAT_MSP1_N_TOPOLOGY.key                      | UNIQUE_... | PAT_MSP1_N_TOPOLOGY   | key            |         79 |
 PAT_NE.key                                   | UNIQUE_... | PAT_NE                | key            |          0 |
 PAT_TL.aEndUniqueKey                         | NOTUNIQ... | PAT_TL                | aEndUni...     |      43530 |
 PAT_TL.key                                   | UNIQUE_... | PAT_TL                | key            |      43531 |
 PAT_TL.zEndUniqueKey                         | NOTUNIQ... | PAT_TL                | zEndUni...     |      43531 |
 POR_ASON_EDGE.key                            | UNIQUE_... | POR_ASON_EDGE         | key            |      44238 |
 POR_ASON_EDGE.patternKey                     | NOTUNIQ... | POR_ASON_EDGE         | patternKey     |       5868 |
 POR_ASON_NE.key                              | UNIQUE_... | POR_ASON_NE           | key            |      15746 |
 POR_ASON_NE.patternKey                       | NOTUNIQ... | POR_ASON_NE           | patternKey     |          0 |
 POR_ASON_SNC_COMP_PATH.endNeName             | NOTUNIQ... | POR_ASON_SNC_COMP_PATH| endNeName      |         63 |
 POR_ASON_SNC_COMP_PATH.key                   | UNIQUE_... | POR_ASON_SNC_COMP_PATH| key            |          0 |
 POR_ASON_SNC_COMP_PATH.startNeName           | NOTUNIQ... | POR_ASON_SNC_COMP_PATH| startNe...     |          0 |
 POR_ASON_SNC_SEQUENCE.key                    | UNIQUE_... | POR_ASON_SNC_SEQUENCE | key            |       5946 |
 POR_ASON_SNCP.key                            | UNIQUE_... | POR_ASON_SNCP         | key            |      20772 |
 POR_ASON_SNCP.patternKey                     | NOTUNIQ... | POR_ASON_SNCP         | patternKey     |       2657 |
 POR_COMBINEDUNIDIRECTIONALPATH.key           | UNIQUE_... | POR_COMBINEDUNIDIRE...| key            |        559 |
 POR_COMBINEDUNIDIRECTIONALPATH.patternKey    | NOTUNIQ... | POR_COMBINEDUNIDIRE...| patternKey     |        385 |
 POR_DOUBLEINTERCONNECT.key                   | UNIQUE_... | POR_DOUBLEINTERCONNECT| key            |         33 |
 POR_DOUBLEINTERCONNECT.patternKey            | NOTUNIQ... | POR_DOUBLEINTERCONNECT| patternKey     |          0 |
 POR_DRI.key                                  | UNIQUE_... | POR_DRI               | key            |         33 |
 POR_DRI.patternKey                           | NOTUNIQ... | POR_DRI               | patternKey     |          0 |
 POR_FOURFIBERBLSR.key                        | UNIQUE_... | POR_FOURFIBERBLSR     | key            |          0 |
 POR_FOURFIBERBLSR.patternKey                 | NOTUNIQ... | POR_FOURFIBERBLSR     | patternKey     |          0 |
 POR_MIXED_SNCP.key                           | UNIQUE_... | POR_MIXED_SNCP        | key            |          0 |
 POR_MIXED_SNCP.patternKey                    | NOTUNIQ... | POR_MIXED_SNCP        | patternKey     |        440 |
 POR_MSP1_1.key                               | UNIQUE_... | POR_MSP1_1            | key            |     588232 |
 POR_MSP1_1.patternKey                        | NOTUNIQ... | POR_MSP1_1            | patternKey     |       7730 |
 POR_MSP1_N.key                               | UNIQUE_... | POR_MSP1_N            | key            |       8848 |
 POR_MSP1_N.patternKey                        | NOTUNIQ... | POR_MSP1_N            | patternKey     |          0 |
 POR_NE.key                                   | UNIQUE_... | POR_NE                | key            |          0 |
 POR_NE.patternKey                            | NOTUNIQ... | POR_NE                | patternKey     |      22002 |
 POR_OPENCIRCUIT.key                          | UNIQUE_... | POR_OPENCIRCUIT       | key            |     150706 |
 POR_OPENCIRCUIT.patternKey                   | NOTUNIQ... | POR_OPENCIRCUIT       | patternKey     |      27236 |
 POR_POINT.hoPointUK                          | NOTUNIQ... | POR_POINT             | hoPointUK      |     302702 |
 POR_POINT.key                                | UNIQUE_... | POR_POINT             | key            |          0 |
 POR_POINT.ptpUK                              | NOTUNIQ... | POR_POINT             | ptpUK          |      96506 |
 POR_POINT.tpName                             | NOTUNIQ... | POR_POINT             | tpName         |    7372841 |
 POR_SEQUENCE.key                             | UNIQUE_... | POR_SEQUENCE          | key            |          0 |
 POR_SEQUENCE.patternKey                      | NOTUNIQ... | POR_SEQUENCE          | patternKey     |          0 |
 POR_SNCP.key                                 | UNIQUE_... | POR_SNCP              | key            |     587999 |
 POR_SNCP.patternKey                          | NOTUNIQ... | POR_SNCP              | patternKey     |      73041 |
 POR_TLINRLWITHOUTCTP.key                     | UNIQUE_... | POR_TLINRLWITHOUTCTP  | key            |          0 |
 POR_TLINRLWITHOUTCTP.patternKey              | NOTUNIQ... | POR_TLINRLWITHOUTCTP  | patternKey     |        851 |
 POR_TLPGPTYPEMISMATCH.key                    | UNIQUE_... | POR_TLPGPTYPEMISMATCH | key            |          0 |
 POR_TLPGPTYPEMISMATCH.patternKey             | NOTUNIQ... | POR_TLPGPTYPEMISMATCH | patternKey     |          0 |
 POR_TLWITHCTP.key                            | UNIQUE_... | POR_TLWITHCTP         | key            |          0 |
 POR_TLWITHCTP.patternKey                     | NOTUNIQ... | POR_TLWITHCTP         | patternKey     |      34723 |
 POR_TLWITHOUTCTP.key                         | UNIQUE_... | POR_TLWITHOUTCTP      | key            |          0 |
 POR_TLWITHOUTCTP.patternKey                  | NOTUNIQ... | POR_TLWITHOUTCTP      | patternKey     |       4130 |
 POR_TLWITHOUTCTPMSPPAIR.key                  | UNIQUE_... | POR_TLWITHOUTCTPMSP...| key            |          0 |
 POR_TLWITHOUTCTPMSPPAIR.patternKey           | NOTUNIQ... | POR_TLWITHOUTCTPMSP...| patternKey     |          0 |
 POR_TWOFIBERBLSR.key                         | UNIQUE_... | POR_TWOFIBERBLSR      | key            |       1247 |
 POR_TWOFIBERBLSR.patternKey                  | NOTUNIQ... | POR_TWOFIBERBLSR      | patternKey     |         40 |
 REL_ASON_TL_PAT_TO_ASON_SEQ.enuk             | NOTUNIQ... | REL_ASON_TL_PAT_TO_...| enuk           |          0 |
 REL_ASON_TL_PAT_TO_ASON_SEQ.snuk             | NOTUNIQ... | REL_ASON_TL_PAT_TO_...| snuk           |          0 |
 REL_ASON_TL_PAT_TO_ASON_SEQ.uk               | UNIQUE_... | REL_ASON_TL_PAT_TO_...| uk             |          0 |
 REL_COMP_PATH_PATTERN_TO_OTHER_WORKER_PATT...| NOTUNIQ... | REL_COMP_PATH_PATTE...| enuk           |          0 |
 REL_COMP_PATH_PATTERN_TO_OTHER_WORKER_PATT...| NOTUNIQ... | REL_COMP_PATH_PATTE...| snuk           |         79 |
 REL_COMP_PATH_PATTERN_TO_OTHER_WORKER_PATT...| UNIQUE_... | REL_COMP_PATH_PATTE...| uk             |        189 |
 REL_COMP_PATH_PATTERN_TO_PATH1_PATTERN.enuk  | NOTUNIQ... | REL_COMP_PATH_PATTE...| enuk           |          0 |
 REL_COMP_PATH_PATTERN_TO_PATH1_PATTERN.snuk  | NOTUNIQ... | REL_COMP_PATH_PATTE...| snuk           |        385 |
 REL_COMP_PATH_PATTERN_TO_PATH1_PATTERN.uk    | UNIQUE_... | REL_COMP_PATH_PATTE...| uk             |        385 |
 REL_COMP_PATH_PATTERN_TO_PATH2_PATTERN.enuk  | NOTUNIQ... | REL_COMP_PATH_PATTE...| enuk           |        385 |
 REL_COMP_PATH_PATTERN_TO_PATH2_PATTERN.snuk  | NOTUNIQ... | REL_COMP_PATH_PATTE...| snuk           |          0 |
 REL_COMP_PATH_PATTERN_TO_PATH2_PATTERN.uk    | UNIQUE_... | REL_COMP_PATH_PATTE...| uk             |          0 |
 REL_COMP_PATH_PATTERN_TO_PROTECTION_PATTER...| NOTUNIQ... | REL_COMP_PATH_PATTE...| enuk           |      69488 |
 REL_COMP_PATH_PATTERN_TO_PROTECTION_PATTER...| NOTUNIQ... | REL_COMP_PATH_PATTE...| snuk           |          0 |
 REL_COMP_PATH_PATTERN_TO_PROTECTION_PATTER...| UNIQUE_... | REL_COMP_PATH_PATTE...| uk             |      83867 |
 REL_COMP_PATH_PATTERN_TO_SEQ1_PATTERN.enuk   | NOTUNIQ... | REL_COMP_PATH_PATTE...| enuk           |      21688 |
 REL_COMP_PATH_PATTERN_TO_SEQ1_PATTERN.snuk   | NOTUNIQ... | REL_COMP_PATH_PATTE...| snuk           |      27237 |
 REL_COMP_PATH_PATTERN_TO_SEQ1_PATTERN.uk     | UNIQUE_... | REL_COMP_PATH_PATTE...| uk             |          0 |
 REL_COMP_PATH_PATTERN_TO_SEQ2_PATTERN.enuk   | NOTUNIQ... | REL_COMP_PATH_PATTE...| enuk           |          0 |
 REL_COMP_PATH_PATTERN_TO_SEQ2_PATTERN.snuk   | NOTUNIQ... | REL_COMP_PATH_PATTE...| snuk           |       9834 |
 REL_COMP_PATH_PATTERN_TO_SEQ2_PATTERN.uk     | UNIQUE_... | REL_COMP_PATH_PATTE...| uk             |       9834 |
 REL_COMP_PATH_PATTERN_TO_WORKER_PATTERN.enuk | NOTUNIQ... | REL_COMP_PATH_PATTE...| enuk           |          0 |
 REL_COMP_PATH_PATTERN_TO_WORKER_PATTERN.snuk | NOTUNIQ... | REL_COMP_PATH_PATTE...| snuk           |          0 |
 REL_COMP_PATH_PATTERN_TO_WORKER_PATTERN.uk   | UNIQUE_... | REL_COMP_PATH_PATTE...| uk             |      83993 |
 REL_DRI_PATTERN_TO_BRIDGE_PATTERN.enuk       | NOTUNIQ... | REL_DRI_PATTERN_TO_...| enuk           |          0 |
 REL_DRI_PATTERN_TO_BRIDGE_PATTERN.snuk       | NOTUNIQ... | REL_DRI_PATTERN_TO_...| snuk           |          2 |
 REL_DRI_PATTERN_TO_BRIDGE_PATTERN.uk         | UNIQUE_... | REL_DRI_PATTERN_TO_...| uk             |          2 |
 REL_DRI_PATTERN_TO_PROTECTION_PATTERN.enuk   | NOTUNIQ... | REL_DRI_PATTERN_TO_...| enuk           |          0 |
 REL_DRI_PATTERN_TO_PROTECTION_PATTERN.snuk   | NOTUNIQ... | REL_DRI_PATTERN_TO_...| snuk           |          2 |
 REL_DRI_PATTERN_TO_PROTECTION_PATTERN.uk     | UNIQUE_... | REL_DRI_PATTERN_TO_...| uk             |          0 |
 REL_DRI_PATTERN_TO_WORKER_PATTERN.enuk       | NOTUNIQ... | REL_DRI_PATTERN_TO_...| enuk           |          0 |
 REL_DRI_PATTERN_TO_WORKER_PATTERN.snuk       | NOTUNIQ... | REL_DRI_PATTERN_TO_...| snuk           |          2 |
 REL_DRI_PATTERN_TO_WORKER_PATTERN.uk         | UNIQUE_... | REL_DRI_PATTERN_TO_...| uk             |          2 |
 REL_EQPT_TO_EQPT.enuk                        | NOTUNIQ... | REL_EQPT_TO_EQPT      | enuk           |          0 |
 REL_EQPT_TO_EQPT.snuk                        | NOTUNIQ... | REL_EQPT_TO_EQPT      | snuk           |          0 |
 REL_EQPT_TO_EQPT.uk                          | UNIQUE_... | REL_EQPT_TO_EQPT      | uk             |          0 |
 REL_EQPT_TO_PTP.enuk                         | NOTUNIQ... | REL_EQPT_TO_PTP       | enuk           |     973128 |
 REL_EQPT_TO_PTP.snuk                         | NOTUNIQ... | REL_EQPT_TO_PTP       | snuk           |      99839 |
 REL_EQPT_TO_PTP.uk                           | UNIQUE_... | REL_EQPT_TO_PTP       | uk             |          0 |
 REL_SEQ_PATTERN_TO_CHILD_PATTERN.enuk        | NOTUNIQ... | REL_SEQ_PATTERN_TO_...| enuk           |     142824 |
 REL_SEQ_PATTERN_TO_CHILD_PATTERN.snuk        | NOTUNIQ... | REL_SEQ_PATTERN_TO_...| snuk           |          0 |
 REL_SEQ_PATTERN_TO_CHILD_PATTERN.uk          | UNIQUE_... | REL_SEQ_PATTERN_TO_...| uk             |          0 |
 REL_TL_PGP_TYPE_MISMATCH_PATTERN_TO_TL.enuk  | NOTUNIQ... | REL_TL_PGP_TYPE_MIS...| enuk           |          0 |
 REL_TL_PGP_TYPE_MISMATCH_PATTERN_TO_TL.snuk  | NOTUNIQ... | REL_TL_PGP_TYPE_MIS...| snuk           |          0 |
 REL_TL_PGP_TYPE_MISMATCH_PATTERN_TO_TL.uk    | UNIQUE_... | REL_TL_PGP_TYPE_MIS...| uk             |          0 |
----------------------------------------------+------------+-----------------------+----------------+------------+
 TOTAL = 135                                                                                            28029253 |
-----------------------------------------------------------------------------------------------------------------+
```

I took one index and gave the command
```
orientdb {db=rcainv}> rebuild index CRTLWithCTP.k;


Rebuilding index(es)...
Error: com.orientechnologies.orient.core.index.OIndexException: Error on rebuilding the index for clusters: [crtlwithctp]

Error: java.lang.NullPointerException
```

At the same time, in our app's nohup, I got the below Exception

```
com.orientechnologies.orient.core.index.OIndexException: Error on rebuilding the index for clusters: [crpoint]
        at com.orientechnologies.orient.core.index.OIndexAbstract.rebuild(OIndexAbstract.java:402)
        at com.orientechnologies.orient.core.index.OIndexAbstract.rebuild(OIndexAbstract.java:310)
        at com.orientechnologies.orient.core.index.OIndexAbstractDelegate.rebuild(OIndexAbstractDelegate.java:142)
        at com.orientechnologies.orient.core.sql.OCommandExecutorSQLRebuildIndex.execute(OCommandExecutorSQLRebuildIndex.java:95)
        at com.orientechnologies.orient.core.sql.OCommandExecutorSQLDelegate.execute(OCommandExecutorSQLDelegate.java:64)
        at com.orientechnologies.orient.core.storage.OStorageEmbedded.executeCommand(OStorageEmbedded.java:86)
        at com.orientechnologies.orient.core.storage.OStorageEmbedded.command(OStorageEmbedded.java:75)
        at com.orientechnologies.orient.core.command.OCommandRequestTextAbstract.execute(OCommandRequestTextAbstract.java:63)
        at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.command(ONetworkProtocolBinary.java:1101)
        at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.executeRequest(ONetworkProtocolBinary.java:338)
        at com.orientechnologies.orient.server.network.protocol.binary.OBinaryNetworkProtocolAbstract.execute(OBinaryNetworkProtocolAbstract.java:201)
        at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:65)
Caused by: java.lang.NullPointerException
```

I tried dropping some indices and created the index newly. It succeeded.

1. Why is it happening?
2. During the previous application session, OrientDB was shutdown properly only

**Comment by laa** [comment]
Hi,
Almost all problems which you created are the same in nutshell hash index is broken after shutdown or addition. I propose to fix initial problem and then retest the rest of them. Could you provide me data log and program which you used to restore index content ?

**Comment by adithyank** [comment]
But, while building this database, that ODirectMemoryViolation exception did not come.
Does your statement hold good still?

**Comment by laa** [comment]
I think that index was broken before memory violation ,this exception is only side effect.

**Comment by laa** [comment]
I think that index was broken before memory violation ,this exception is only side effect.

**Comment by laa** [comment]
I think that index was broken before memory violation ,this exception is only side effect.

**Comment by laa** [comment]
Workaround was found. Will be properly fixed by new disk cache memory management approach.
