### ISSUE TITLE
(Client=55) Clustering: Cannot find best cluster for class 'OUser'

### ISSUE THREAD

**Issue by thecyman** [orientechnologies/orientdb#3311]
In a 2-node cluster, there is an issue. I'm having trouble finding the exact source, but here's what I have so far:
### Part 1
- I startup up node 1.
- I then started node 2.

### Part 2
Node 2's status isn't yet online:
```
WARNING Distributed server is not yet ONLINE (status=STARTING), reject incoming connection from /172.31.32.191:46027 [OServerNetworkListener]
```

### Part 3
I then ran, on node #1:
```sql
orientdb {db=pumpup}> insert into OUser set password='test', status='ACTIVE', name='some_test_user'
```

This resulted in pages and pages of output on node 2, similar to:
```
2014-12-31 21:32:00:586 WARNING Distributed server is not yet ONLINE (status=STARTING), reject incoming connection from /172.31.32.191:46026 [OServerNetworkListener]
2014-12-31 21:32:00:715 WARNING Distributed server is not yet ONLINE (status=STARTING), reject incoming connection from /172.31.32.191:46027 [OServerNetworkListener]
2014-12-31 21:32:00:816 WARNING Distributed server is not yet ONLINE (status=STARTING), reject incoming connection from /172.31.32.191:46028 [OServerNetworkListener]
2014-12-31 21:32:00:976 WARNING Distributed server is not yet ONLINE (status=STARTING), reject incoming connection from /172.31.32.191:46029 [OServerNetworkListener]
```

It also resulting in pages and page of output in node 1's console. This message was repeated in a loop:
```
2014-12-31 21:31:45:639 WARNING Connection re-acquired transparently after 3ms and 1 retries: no errors will be thrown at application level [OStorageRemote]Error on formatting message 'Caught I/O errors, trying to reconnect (error: %s)'
java.util.MissingFormatArgumentException: Format specifier 's'
	at java.util.Formatter.format(Formatter.java:2487)
	at java.util.Formatter.format(Formatter.java:2423)
	at java.lang.String.format(String.java:2790)
	at com.orientechnologies.common.log.OLogManager.log(OLogManager.java:92)
	at com.orientechnologies.common.log.OLogManager.warn(OLogManager.java:147)
	at com.orientechnologies.orient.client.remote.OStorageRemote.handleException(OStorageRemote.java:1464)
	at com.orientechnologies.orient.client.remote.OStorageRemote.command(OStorageRemote.java:1007)
	at com.orientechnologies.orient.client.remote.OStorageRemoteThread.command(OStorageRemoteThread.java:434)
	at com.orientechnologies.orient.core.command.OCommandRequestTextAbstract.execute(OCommandRequestTextAbstract.java:63)
	at com.orientechnologies.orient.console.OConsoleDatabaseApp.sqlCommand(OConsoleDatabaseApp.java:2268)
	at com.orientechnologies.orient.console.OConsoleDatabaseApp.insert(OConsoleDatabaseApp.java:477)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at com.orientechnologies.common.console.OConsoleApplication.execute(OConsoleApplication.java:381)
	at com.orientechnologies.common.console.OConsoleApplication.executeCommands(OConsoleApplication.java:246)
	at com.orientechnologies.common.console.OConsoleApplication.run(OConsoleApplication.java:135)
	at com.orientechnologies.orient.graph.console.OGremlinConsole.main(OGremlinConsole.java:62)
```

### Part 4
I hit CTRL+C on node 2's ODB.
In node 1's console, I then got the error:
```
Error: com.orientechnologies.common.exception.OException: Cannot find best cluster for class 'OUser'. ClusterStrategy=local
```

**Comment by kadishmal** [comment]
Can this be related to #2981?

**Comment by lvca** [comment]
It could be the same one.

**Comment by lvca** [comment]
Please can you try with last 2.0-SNAPSHOT?

**Comment by lvca** [comment]
Ok, I'm closing it. In case, please comment it again.
