### ISSUE TITLE
(Client=55) OUser's data disappeared

### ISSUE THREAD

**Issue by garrett-gottlieb** [orientechnologies/orientdb#3317]
They have no data now. This is clearly a popular user, they have over 100k updates, likely caused by a lot of other users following them:
```
        {
            "@type": "d",
            "@rid": "#5:2042390",
            "@version": 105691,
            "@class": "OUser"
        }
```

Here's the error:
```
Sent run-time exception to the client /127.0.0.1:59381: com.orientechnologies.orient.core.exception.OCommandExecutionException: Error on execution of command: sql.select from #5:2042390
com.orientechnologies.orient.core.exception.OCommandExecutionException: Error on execution of command: sql.select from #5:2042390
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.executeCommand(OAbstractPaginatedStorage.java:1178)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.command(OAbstractPaginatedStorage.java:1161)
	at com.orientechnologies.orient.core.sql.query.OSQLQuery.run(OSQLQuery.java:71)
	at com.orientechnologies.orient.core.query.OQueryAbstract.execute(OQueryAbstract.java:33)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.query(ODatabaseDocumentTx.java:627)
	at com.orientechnologies.orient.core.sql.OCommandExecutorSQLUpdate.execute(OCommandExecutorSQLUpdate.java:209)
	at com.orientechnologies.orient.core.sql.OCommandExecutorSQLDelegate.execute(OCommandExecutorSQLDelegate.java:64)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.executeCommand(OAbstractPaginatedStorage.java:1172)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.command(OAbstractPaginatedStorage.java:1161)
	at com.orientechnologies.orient.core.command.OCommandRequestTextAbstract.execute(OCommandRequestTextAbstract.java:63)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.command(ONetworkProtocolBinary.java:1179)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.executeRequest(ONetworkProtocolBinary.java:385)
	at com.orientechnologies.orient.server.network.protocol.binary.OBinaryNetworkProtocolAbstract.execute(OBinaryNetworkProtocolAbstract.java:216)
	at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:65)
Caused by: com.orientechnologies.orient.core.exception.OValidationException: The field 'OUser.password' is mandatory, but not found on record: OUser#5:2042390{out_UserLikesPost:[1]} v105691
	at com.orientechnologies.orient.core.record.impl.ODocument.validateField(ODocument.java:285)
	at com.orientechnologies.orient.core.record.impl.ODocument.validate(ODocument.java:1983)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.save(ODatabaseDocumentTx.java:2214)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.save(ODatabaseDocumentTx.java:117)
	at com.orientechnologies.orient.core.record.impl.ODocument.save(ODocument.java:1745)
	at com.orientechnologies.orient.core.record.impl.ODocument.save(ODocument.java:1736)
	at com.orientechnologies.orient.core.sql.OCommandExecutorSQLUpdate.result(OCommandExecutorSQLUpdate.java:266)
	at com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.addResult(OCommandExecutorSQLSelect.java:618)
	at com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.handleResult(OCommandExecutorSQLSelect.java:554)
	at com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.executeSearchRecord(OCommandExecutorSQLSelect.java:508)
	at com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.fetchFromTarget(OCommandExecutorSQLSelect.java:1301)
	at com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.executeSearch(OCommandExecutorSQLSelect.java:434)
	at com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.execute(OCommandExecutorSQLSelect.java:392)
	at com.orientechnologies.orient.core.sql.OCommandExecutorSQLDelegate.execute(OCommandExecutorSQLDelegate.java:64)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.executeCommand(OAbstractPaginatedStorage.java:1172)
	... 13 more
```

This is very serious. For this to be happening right now is extremely scary.

**Comment by lvca** [comment]
Was this error thrown with half GB of heap?

**Comment by garrett-gottlieb** [comment]
No, this is still being thrown. Here's the startup log for the current run of the database:
```
2015-01-02 00:45:51:689 INFO  OrientDB auto-config DISKCACHE=185,695MB (heap=58,254MB os=245,997MB disk=3,884,757MB) [orientechnologies]
2015-01-02 00:45:51:692 INFO  Loading configuration from: /ephemeral/pumpup-etl/server/libs/orientdb-current/config/orientdb-server-config.xml... [OServerConfigurationLoaderXml]
2015-01-02 00:45:51:839 INFO  OrientDB Server v2.0-SNAPSHOT (build UNKNOWN@r; 2014-12-04 22:29:22-0500) is starting up... [OServer]
2015-01-02 00:45:51:856 INFO  Databases directory: /ephemeral/pumpup-etl/server/libs/orientdb-current/databases [OServer]
2015-01-02 00:45:51:881 INFO  Listening binary connections on 0.0.0.0:2424 (protocol v.28, socket=default) [OServerNetworkListener]
2015-01-02 00:45:51:882 INFO  Listening http connections on 0.0.0.0:2480 (protocol v.10, socket=default) [OServerNetworkListener]
2015-01-02 00:45:51:893 INFO  Installing dynamic plugin 'studio-2.0.zip'... [OServerPluginManager]
2015-01-02 00:45:51:944 INFO  Installing GREMLIN language v.2.6.0 - graph.pool.max=50 [OGraphServerHandler]
2015-01-02 00:45:51:944 INFO  [OVariableParser.resolveVariables] Error on resolving property: distributed [orientechnologies]
2015-01-02 00:45:51:945 INFO  Installing Script interpreter. WARN: authenticated clients can execute any kind of code into the server by using the following allowed languages: [sql] [OServerSideScriptInterpreter]
2015-01-02 00:45:51:945 INFO  OrientDB Server v2.0-SNAPSHOT is active. [OServer]
2015-01-02 00:46:00:370 SEVERE Can not restore 0 WAL master record for storage pumpup crc check is failed [ODiskWriteAheadLog]
```

**Comment by tglman** [comment]
@garrett-gottlieb i feel that this issue is related to the fix of: https://github.com/orientechnologies/orientdb/issues/3263 I'll add more comment there.

**Comment by tglman** [comment]
@garrett-gottlieb do you still have this problem after i reverted the the fix ?

**Comment by tglman** [comment]
no feedback so far, closing it, reopen it if the issue still exist.
