### ISSUE TITLE
(Client=55) Caused by: java.lang.OutOfMemoryError: GC overhead limit exceeded

### ISSUE THREAD

**Issue by garrett-gottlieb** [orientechnologies/orientdb#3318]
Here's the full error:
```
Sent run-time exception to the client /127.0.0.1:59262: com.orientechnologies.orient.core.exception.ODatabaseException: Error on saving record #65:32591068
com.orientechnologies.orient.core.exception.ODatabaseException: Error on saving record #65:32591068
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.executeSaveRecord(ODatabaseDocumentTx.java:1756)
	at com.orientechnologies.orient.core.tx.OTransactionNoTx.saveRecord(OTransactionNoTx.java:94)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.save(ODatabaseDocumentTx.java:2270)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.save(ODatabaseDocumentTx.java:2107)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.save(ODatabaseDocumentTx.java:117)
	at com.orientechnologies.orient.server.network.protocol.binary.OBinaryNetworkProtocolAbstract.updateRecord(OBinaryNetworkProtocolAbstract.java:374)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.updateRecord(ONetworkProtocolBinary.java:1344)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.executeRequest(ONetworkProtocolBinary.java:354)
	at com.orientechnologies.orient.server.network.protocol.binary.OBinaryNetworkProtocolAbstract.execute(OBinaryNetworkProtocolAbstract.java:216)
	at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:65)
Caused by: java.lang.OutOfMemoryError: GC overhead limit exceeded
```

Our server has 240GB and 56GB free:
```
ubuntu@bowser:~/pumpup/server$ free -h
             total       used       free     shared    buffers     cached
Mem:          240G       183G        56G       468K       160M       163G
-/+ buffers/cache:        19G       220G
Swap:         499G         0B       499G
```

**Comment by garrett-gottlieb** [comment]
This was likely caused by accidentally using too little memory for the heap:
```
./server.sh -Xmx512m -Dstorage.diskCache.bufferSize=3000
```

We have since increased it:
```
cd libs/orientdb-current/bin && ./server.sh -Xmx64G -Dstorage.wal.maxSize=60000
```

But I'm logging this as it may be linked to the issue of critical importance: https://github.com/orientechnologies/orientdb/issues/3317

**Comment by lvca** [comment]
Ok, I'm closing this.
