### ISSUE TITLE
(Client=55) Can't find object with problematic date without full query

### ISSUE THREAD

**Issue by garrett-gottlieb** [orientechnologies/orientdb#3320]
I get a lot of these very weird errors when running the ETL, but can never debug them because I don't have the full query that's causing the problem:
```
Sent run-time exception to the client /127.0.0.1:35304: com.orientechnologies.orient.core.exception.OQueryParsingException: Error on formatting date 'Fri Jan 02 01:14:01 UTC 2015' using the format: yyyy-MM-dd'T'HH:mm:ss.SSS'Z'
com.orientechnologies.orient.core.exception.OQueryParsingException: Error on formatting date 'Fri Jan 02 01:14:01 UTC 2015' using the format: yyyy-MM-dd'T'HH:mm:ss.SSS'Z'
        at com.orientechnologies.orient.core.sql.functions.misc.OSQLFunctionDate.execute(OSQLFunctionDate.java:77)
        at com.orientechnologies.orient.core.sql.functions.OSQLFunctionRuntime.execute(OSQLFunctionRuntime.java:126)
        at com.orientechnologies.orient.core.sql.functions.OSQLFunctionRuntime.getValue(OSQLFunctionRuntime.java:142)
        at com.orientechnologies.orient.core.sql.OSQLHelper.getValue(OSQLHelper.java:231)
        at com.orientechnologies.orient.core.sql.OFilterAnalyzer.createIndexedProperty(OFilterAnalyzer.java:229)
        at com.orientechnologies.orient.core.sql.OFilterAnalyzer.analyzeIndexMethod(OFilterAnalyzer.java:154)
        at com.orientechnologies.orient.core.sql.OFilterAnalyzer.analyzeFilterBranch(OFilterAnalyzer.java:139)
        at com.orientechnologies.orient.core.sql.OFilterAnalyzer.analyzeIntersection(OFilterAnalyzer.java:174)
        at com.orientechnologies.orient.core.sql.OFilterAnalyzer.analyzeFilterBranch(OFilterAnalyzer.java:137)
        at com.orientechnologies.orient.core.sql.OFilterAnalyzer.analyzeCondition(OFilterAnalyzer.java:103)
        at com.orientechnologies.orient.core.sql.OFilterAnalyzer.analyzeOrFilterBranch(OFilterAnalyzer.java:84)
        at com.orientechnologies.orient.core.sql.OFilterAnalyzer.analyzeMainCondition(OFilterAnalyzer.java:58)
        at com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.searchForIndexes(OCommandExecutorSQLSelect.java:1434)
        at com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.searchInClasses(OCommandExecutorSQLSelect.java:741)
        at com.orientechnologies.orient.core.sql.OCommandExecutorSQLResultsetAbstract.assignTarget(OCommandExecutorSQLResultsetAbstract.java:186)
        at com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.assignTarget(OCommandExecutorSQLSelect.java:439)
        at com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.executeSearch(OCommandExecutorSQLSelect.java:421)
        at com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.execute(OCommandExecutorSQLSelect.java:392)
        at com.orientechnologies.orient.core.sql.OCommandExecutorSQLDelegate.execute(OCommandExecutorSQLDelegate.java:64)
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.executeCommand(OAbstractPaginatedStorage.java:1172)
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.command(OAbstractPaginatedStorage.java:1161)
        at com.orientechnologies.orient.core.command.OCommandRequestTextAbstract.execute(OCommandRequestTextAbstract.java:63)
        at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.command(ONetworkProtocolBinary.java:1179)
        at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.executeRequest(ONetworkProtocolBinary.java:385)
        at com.orientechnologies.orient.server.network.protocol.binary.OBinaryNetworkProtocolAbstract.execute(OBinaryNetworkProtocolAbstract.java:216)
        at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:65)
Caused by: java.text.ParseException: Unparseable date: "Fri Jan 02 01:14:01 UTC 2015"
        at java.text.DateFormat.parse(DateFormat.java:366)
        at com.orientechnologies.orient.core.sql.functions.misc.OSQLFunctionDate.execute(OSQLFunctionDate.java:75)
        ... 25 more
```
I have no idea why this is happening, but neither ODB or the ETL is giving me enough information to debug.

This is related to https://github.com/orientechnologies/orientdb/issues/3296 and https://github.com/orientechnologies/orientdb/issues/3235. It is crucial to log entire queries so we can debug.

**Comment by lvca** [comment]
How the date "Fri Jan 02 01:14:01 UTC 2015" arrives?

**Comment by garrett-gottlieb** [comment]
I have no idea. In our JSON data it always arrives as `yyyy-MM-dd'T'HH:mm:ss.SSS'Z'`. That is Parse.com's format, and any date retrieved by them should be in that format. We query them, dump resulting JSON into a file, and run ETL on that file. If I knew the RID or the full query (with the Parse.com `objectId`) I might be able to determine where the Date got translated to this, but I'm not sure. I get a lot of these, too. Probably for 1% of records imported, I'm guessing from the OUser ETL (but again, I have no idea).

**Comment by lvca** [comment]
Seems the date format was no correct. I'm closing it. In case somebody else sees the same problem, please reopen/comment on this.
