### ISSUE TITLE
Can't run OrientDB in mule

### ISSUE THREAD

**Issue by mirobimbo** [orientechnologies/orientdb#3337]
Hello, I haven't been able to run OrientDB under mule environment. I tired to:
1) install java 1.7
2) run orientdb-community-1.7.10 on local machine
3) download and run Anypoint Studio 4.1.0, create new Mule Project -> 3.5.0 CE, Use maven
4) Add dependencies to pom of new project:

```
<dependency>
        <groupId>com.orientechnologies</groupId>
        <artifactId>orient-commons</artifactId>
        <version>1.7.9</version>
    </dependency>
    <dependency>
        <groupId>com.orientechnologies</groupId>
        <artifactId>orientdb-core</artifactId>
        <version>1.7.9</version>
    </dependency>
    <dependency>
        <groupId>com.orientechnologies</groupId>
        <artifactId>orientdb-client</artifactId>
        <version>1.7.9</version>
    </dependency>
    <dependency>
        <groupId>com.orientechnologies</groupId>
        <artifactId>orientdb-enterprise</artifactId>
        <version>1.7.9</version>
    </dependency>
    <dependency>
        <groupId>junit</groupId>
        <artifactId>junit</artifactId>
        <version>4.11</version>
        <scope>test</scope>
    </dependency>
```

5)  create new Class:

```
public class TestOrient {

@Test
public void test(){
    ODatabaseDocumentTx db = new ODatabaseDocumentTx("remote:localhost/test").open("root", "pass");

    // CREATE A NEW DOCUMENT AND FILL IT
    ODocument doc = new ODocument("Persondd");
    doc.field( "name", "Luke" );
    doc.field( "surname", "Skywalker" );
    doc.field( "city", new ODocument("City").field("name","Rome").field("country", "Italy") );

    // SAVE THE DOCUMENT
    doc.save();

    db.close();

}
}
```

---

6) run `TestOrient` as JUnit test. You will get an Error:

```
java.lang.NoSuchMethodError: javax.el.ExpressionFactory.newInstance()Ljavax/el/ExpressionFactory;
    at com.sun.script.juel.JuelScriptEngine.<init>(JuelScriptEngine.java:95)
    at com.sun.script.juel.JuelScriptEngineFactory.getScriptEngine(JuelScriptEngineFactory.java:241)
    at com.orientechnologies.orient.core.command.script.OScriptManager.<init>(OScriptManager.java:74)
    at com.orientechnologies.orient.core.Orient.<init>(Orient.java:59)
    at com.orientechnologies.orient.core.Orient.<clinit>(Orient.java:53)
    at com.orientechnologies.orient.core.serialization.serializer.record.string.ORecordSerializerStringAbstract.<clinit>(ORecordSerializerStringAbstract.java:47)
    at com.orientechnologies.orient.core.serialization.serializer.record.ORecordSerializerFactory.<init>(ORecordSerializerFactory.java:40)
    at com.orientechnologies.orient.core.serialization.serializer.record.ORecordSerializerFactory.<clinit>(ORecordSerializerFactory.java:32)
    at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.<clinit>(ODatabaseDocumentTx.java:58)
```

---

I think the problem is it havn't been expected there will be such an old library as Juel in classpath (needed by mule). When I've edited class `OScriptManager` on line 57

```
 ...
for (ScriptEngineFactory f : scriptEngineManager.getEngineFactories()) {
    if("juel".equals(f.getEngineName())) continue; //NEW LINE
  if (f.getParameter("THREADING") != null) { 
...
```

It worked! :)

**Comment by lvca** [comment]
Have you tried with OrientDB 2.0.x?

**Comment by lvca** [comment]
Not relevant anymore, closing it.
