### ISSUE TITLE
ORecordNotFoundException thrown on vertex.remove()

### ISSUE THREAD

**Issue by pdolega** [orientechnologies/orientdb#3344]
Following code throws ORecordNotFoundException (on `remove()` line):

```
    val emitter = read(emitterId)
    ...
    try {
      emitter.getVertex.remove()
    } catch {
      case ex: Throwable =>
        ex.printStackTrace()
        throw ex
    }
```

Obviously vertex is in database as it's correctly read couple of lines above (and even when I stop on breakpoint in the line of `remove` I can still correctly read it from db. Actually it seems that this `remove` actually does remove the vertex as after exception is being thrown when I stop in breakpoint in `catch` clause I cannot find this vertex in db anymore (and yet still throws exception).

Version: 2.0-RC1
Database is created like this:

```
application.conf:
# Orient db test access
orient {
  db {
    address="memory:test-db"
    user="admin"
    password="admin"
  }
}
```

```
val factory = new OrientGraphFactory("memory:test-db", "admin", "admin")
val graph = factory.getNoTx
```

Exception's stack trace:
```
com.orientechnologies.orient.core.exception.ORecordNotFoundException: The record with id #13:0 was not found
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.executeDeleteRecord(ODatabaseDocumentTx.java:1816)
	at com.orientechnologies.orient.core.tx.OTransactionNoTx.deleteRecord(OTransactionNoTx.java:116)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.delete(ODatabaseDocumentTx.java:2300)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.delete(ODatabaseDocumentTx.java:117)
	at com.orientechnologies.orient.core.record.ORecordAbstract.delete(ORecordAbstract.java:289)
	at com.tinkerpop.blueprints.impls.orient.OrientVertex.deleteEdgeIfAny(OrientVertex.java:438)
	at com.tinkerpop.blueprints.impls.orient.OrientVertex.removeEdges(OrientVertex.java:317)
	at com.tinkerpop.blueprints.impls.orient.OrientVertex.remove(OrientVertex.java:675)
	at com.nexelem.nutstrap.play.dao.EmitterDao.deleteEmitter(EmitterDao.scala:67)
	at com.nexelem.nutstrap.play.actor.FactoryActor$$anonfun$com$nexelem$nutstrap$play$actor$FactoryActor$$delete$1$$anonfun$apply$4$$anonfun$apply$5.apply(FactoryActor.scala:132)
	at com.nexelem.nutstrap.play.actor.FactoryActor$$anonfun$com$nexelem$nutstrap$play$actor$FactoryActor$$delete$1$$anonfun$apply$4$$anonfun$apply$5.apply(FactoryActor.scala:131)
	at scala.collection.Iterator$class.foreach(Iterator.scala:743)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1195)
	at com.nexelem.nutstrap.play.actor.FactoryActor$$anonfun$com$nexelem$nutstrap$play$actor$FactoryActor$$delete$1$$anonfun$apply$4.apply(FactoryActor.scala:131)
	at com.nexelem.nutstrap.play.actor.FactoryActor$$anonfun$com$nexelem$nutstrap$play$actor$FactoryActor$$delete$1$$anonfun$apply$4.apply(FactoryActor.scala:130)
	at scala.collection.Iterator$class.foreach(Iterator.scala:743)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1195)
	at com.nexelem.nutstrap.play.actor.FactoryActor$$anonfun$com$nexelem$nutstrap$play$actor$FactoryActor$$delete$1.apply(FactoryActor.scala:130)
	at com.nexelem.nutstrap.play.actor.FactoryActor$$anonfun$com$nexelem$nutstrap$play$actor$FactoryActor$$delete$1.apply(FactoryActor.scala:125)
	at com.nexelem.nutstrap.common.db.TransactionManager$class.withTransaction(TransactionManager.scala:14)
	at com.nexelem.nutstrap.common.db.OrientTransactionManager.withTransaction(OrientTransactionManager.scala:10)
	at com.nexelem.nutstrap.play.actor.FactoryActor.com$nexelem$nutstrap$play$actor$FactoryActor$$delete(FactoryActor.scala:125)
	at com.nexelem.nutstrap.play.actor.FactoryActor$$anonfun$tryReceive$1.applyOrElse(FactoryActor.scala:48)
	at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:36)
	at com.nexelem.nutstrap.common.actor.AbstractActor$$anonfun$receive$1.applyOrElse(AbstractActor.scala:28)
	at akka.actor.Actor$class.aroundReceive(Actor.scala:465)
	at com.nexelem.nutstrap.common.actor.AbstractActor.aroundReceive(AbstractActor.scala:11)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:516)
	at akka.actor.ActorCell.invoke(ActorCell.scala:487)
	at akka.testkit.CallingThreadDispatcher.process$1(CallingThreadDispatcher.scala:251)
	at akka.testkit.CallingThreadDispatcher.runQueue(CallingThreadDispatcher.scala:284)
	at akka.testkit.CallingThreadDispatcher.dispatch(CallingThreadDispatcher.scala:208)
	at akka.actor.dungeon.Dispatch$class.sendMessage(Dispatch.scala:123)
	at akka.actor.ActorCell.sendMessage(ActorCell.scala:369)
	at akka.actor.Cell$class.sendMessage(ActorCell.scala:290)
	at akka.actor.ActorCell.sendMessage(ActorCell.scala:369)
	at akka.actor.LocalActorRef.$bang(ActorRef.scala:384)
	at com.nexelem.fallout.play.actor.FactoryActorSpec$$anonfun$1$$anonfun$apply$mcV$sp$1$$anonfun$apply$mcV$sp$2.apply$mcV$sp(FactoryActorSpec.scala:46)
	at com.nexelem.fallout.play.actor.FactoryActorSpec$$anonfun$1$$anonfun$apply$mcV$sp$1$$anonfun$apply$mcV$sp$2.apply(FactoryActorSpec.scala:36)
	at com.nexelem.fallout.play.actor.FactoryActorSpec$$anonfun$1$$anonfun$apply$mcV$sp$1$$anonfun$apply$mcV$sp$2.apply(FactoryActorSpec.scala:36)
	at play.api.test.PlayRunners$class.running(Helpers.scala:49)
	at play.api.test.Helpers$.running(Helpers.scala:396)
	at com.nexelem.fallout.play.actor.FactoryActorSpec$$anonfun$1$$anonfun$apply$mcV$sp$1.apply$mcV$sp(FactoryActorSpec.scala:36)
	at com.nexelem.fallout.play.actor.FactoryActorSpec$$anonfun$1$$anonfun$apply$mcV$sp$1.apply(FactoryActorSpec.scala:36)
	at com.nexelem.fallout.play.actor.FactoryActorSpec$$anonfun$1$$anonfun$apply$mcV$sp$1.apply(FactoryActorSpec.scala:36)
	at org.scalatest.Transformer$$anonfun$apply$1.apply$mcV$sp(Transformer.scala:22)
	at org.scalatest.OutcomeOf$class.outcomeOf(OutcomeOf.scala:85)
	at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
	at org.scalatest.Transformer.apply(Transformer.scala:22)
	at org.scalatest.Transformer.apply(Transformer.scala:20)
	at org.scalatest.WordSpecLike$$anon$1.apply(WordSpecLike.scala:953)
	at org.scalatest.Suite$class.withFixture(Suite.scala:1122)
	at com.nexelem.nutstrap.test.util.actor.ActorSpec.withFixture(ActorSpec.scala:16)
	at org.scalatest.WordSpecLike$class.invokeWithFixture$1(WordSpecLike.scala:950)
	at org.scalatest.WordSpecLike$$anonfun$runTest$1.apply(WordSpecLike.scala:962)
	at org.scalatest.WordSpecLike$$anonfun$runTest$1.apply(WordSpecLike.scala:962)
	at org.scalatest.SuperEngine.runTestImpl(Engine.scala:306)
	at org.scalatest.WordSpecLike$class.runTest(WordSpecLike.scala:962)
	at com.nexelem.nutstrap.test.util.actor.ActorSpec.org$scalatest$BeforeAndAfterEach$$super$runTest(ActorSpec.scala:16)
	at org.scalatest.BeforeAndAfterEach$class.runTest(BeforeAndAfterEach.scala:255)
	at com.nexelem.nutstrap.test.util.actor.ActorSpec.runTest(ActorSpec.scala:16)
	at org.scalatest.WordSpecLike$$anonfun$runTests$1.apply(WordSpecLike.scala:1021)
	at org.scalatest.WordSpecLike$$anonfun$runTests$1.apply(WordSpecLike.scala:1021)
	at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:413)
	at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:401)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:401)
	at org.scalatest.SuperEngine.org$scalatest$SuperEngine$$runTestsInBranch(Engine.scala:390)
	at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:427)
	at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:401)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:401)
	at org.scalatest.SuperEngine.org$scalatest$SuperEngine$$runTestsInBranch(Engine.scala:396)
	at org.scalatest.SuperEngine.runTestsImpl(Engine.scala:483)
	at org.scalatest.WordSpecLike$class.runTests(WordSpecLike.scala:1021)
	at com.nexelem.nutstrap.test.util.actor.ActorSpec.runTests(ActorSpec.scala:16)
	at org.scalatest.Suite$class.run(Suite.scala:1424)
	at com.nexelem.nutstrap.test.util.actor.ActorSpec.org$scalatest$WordSpecLike$$super$run(ActorSpec.scala:16)
	at org.scalatest.WordSpecLike$$anonfun$run$1.apply(WordSpecLike.scala:1067)
	at org.scalatest.WordSpecLike$$anonfun$run$1.apply(WordSpecLike.scala:1067)
	at org.scalatest.SuperEngine.runImpl(Engine.scala:545)
	at org.scalatest.WordSpecLike$class.run(WordSpecLike.scala:1067)
	at com.nexelem.nutstrap.test.util.actor.ActorSpec.org$scalatest$BeforeAndAfterAll$$super$run(ActorSpec.scala:16)
	at org.scalatest.BeforeAndAfterAll$class.liftedTree1$1(BeforeAndAfterAll.scala:257)
	at org.scalatest.BeforeAndAfterAll$class.run(BeforeAndAfterAll.scala:256)
	at com.nexelem.nutstrap.test.util.actor.ActorSpec.run(ActorSpec.scala:16)
	at org.scalatest.tools.SuiteRunner.run(SuiteRunner.scala:55)
	at org.scalatest.tools.Runner$$anonfun$doRunRunRunDaDoRunRun$3.apply(Runner.scala:2563)
	at org.scalatest.tools.Runner$$anonfun$doRunRunRunDaDoRunRun$3.apply(Runner.scala:2557)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at org.scalatest.tools.Runner$.doRunRunRunDaDoRunRun(Runner.scala:2557)
	at org.scalatest.tools.Runner$$anonfun$runOptionallyWithPassFailReporter$2.apply(Runner.scala:1044)
	at org.scalatest.tools.Runner$$anonfun$runOptionallyWithPassFailReporter$2.apply(Runner.scala:1043)
	at org.scalatest.tools.Runner$.withClassLoaderAndDispatchReporter(Runner.scala:2722)
	at org.scalatest.tools.Runner$.runOptionallyWithPassFailReporter(Runner.scala:1043)
	at org.scalatest.tools.Runner$.run(Runner.scala:883)
	at org.scalatest.tools.Runner.run(Runner.scala)
	at org.jetbrains.plugins.scala.testingSupport.scalaTest.ScalaTestRunner.runScalaTest2(ScalaTestRunner.java:137)
	at org.jetbrains.plugins.scala.testingSupport.scalaTest.ScalaTestRunner.main(ScalaTestRunner.java:28)
```

**Comment by pdolega** [comment]
Seems that reverting back to version 2.0-M3 solves the problem. Regression bug ?

**Comment by laa** [comment]
Hm ... I will take it.

**Comment by laa** [comment]
I will fix issue but never use notx graph db it may be used only for initial load of data.

**Comment by laa** [comment]
sorry it is not vertex but edge is absent, once again please do not use non-tx db. in case of errors you may end up in inconsistent state like this when vertex is present but edge is not. could you either  provide test case to reproduce issue or repeat the same on tx database and to check that issue is still reproducible on tx mode.

**Comment by pdolega** [comment]
@laa 
I'll double check it on tx database but not sure if that would be that easy though. 

To give you some information on this:
We use in-memory, no-tx version in unit tests. In normal mode of operation (application running) we naturally use transactional graph but in tests we want to take a look at data put to db here and there (even though normally transaction wouldn't be committed yet - that's verification part of the unit tests). 

Our business logic is written with heavy use of Akka so it is naturally multi-threaded - this is also additional reason we cannot use transactions in tests (AFAIK transaction scope is heavily bound to threads in OrientDb). Long story short - using non-tx in tests simplifies testing a lot. As for inconsistent state - we don't care that much. Db data is being recreated on each test run.

**Comment by lvca** [comment]
Fixed.
