### ISSUE TITLE
2.0-rc1: error in exception handling

### ISSUE THREAD

**Issue by 8forty** [orientechnologies/orientdb#3385]
I got this error on my orient client-side, apparently somewhere in the error-handling chain a string-format is not handled correctly:
```
Jan 13, 2015 11:59:38 PM com.orientechnologies.common.log.OLogManager log
WARNING: Error on formatting message 'Caught I/O errors, trying to reconnect (error: %s)'
java.util.MissingFormatArgumentException: Format specifier 's'
	at java.util.Formatter.format(Formatter.java:2487)
	at java.util.Formatter.format(Formatter.java:2423)
	at java.lang.String.format(String.java:2797)
	at com.orientechnologies.common.log.OLogManager.log(OLogManager.java:92)
	at com.orientechnologies.common.log.OLogManager.warn(OLogManager.java:147)
	at com.orientechnologies.orient.client.remote.OStorageRemote.handleException(OStorageRemote.java:1510)
	at com.orientechnologies.orient.client.remote.OStorageRemote.readRecord(OStorageRemote.java:508)
	at com.orientechnologies.orient.client.remote.OStorageRemoteThread.readRecord(OStorageRemoteThread.java:253)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.executeReadRecord(ODatabaseDocumentTx.java:1568)
	at com.orientechnologies.orient.core.tx.OTransactionOptimistic.loadRecord(OTransactionOptimistic.java:226)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.load(ODatabaseDocumentTx.java:1420)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.load(ODatabaseDocumentTx.java:117)
	at com.orientechnologies.orient.core.record.impl.ODocument.field(ODocument.java:847)
	at com.tinkerpop.blueprints.impls.orient.OrientElement.getProperty(OrientElement.java:253)
...

Jan 13, 2015 11:59:38 PM com.orientechnologies.common.log.OLogManager log
WARNING: Connection re-acquired transparently after 2ms and 1 retries to server 'fox:2424/smsrb-copy': no errors will be thrown at application level
```

**Comment by lvca** [comment]
Please use 2.0-rc2 where we already fix a bug very close to it.
