### ISSUE TITLE
NullPointerException on DB startup

### ISSUE THREAD

**Issue by PhantomYdn** [orientechnologies/orientdb#3387]
Guys,

Sometimes(!!!) during memory based db startup I have following in RC2 (In RC1 everything was good):

```java
Caused by: com.orientechnologies.orient.core.exception.ODatabaseException: Cannot create database 'WicketOrientTestDb'
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.create(ODatabaseDocumentTx.java:436)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.create(ODatabaseDocumentTx.java:352)
	at ru.ydn.wicket.wicketorientdb.OrientDbTestWebApplication$1.onAfterServerStartupAndActivation(OrientDbTestWebApplication.java:28)
	at ru.ydn.wicket.wicketorientdb.EmbeddOrientDbApplicationListener.onAfterInitialized(EmbeddOrientDbApplicationListener.java:78)
	... 26 more
Caused by: com.orientechnologies.orient.core.exception.ODatabaseException: Error on saving record in cluster #0
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.executeSaveRecord(ODatabaseDocumentTx.java:1754)
	at com.orientechnologies.orient.core.tx.OTransactionNoTx.saveRecord(OTransactionNoTx.java:94)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.save(ODatabaseDocumentTx.java:2270)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.save(ODatabaseDocumentTx.java:117)
	at com.orientechnologies.orient.core.record.impl.ODocument.save(ODocument.java:1750)
	at com.orientechnologies.orient.core.record.impl.ODocument.save(ODocument.java:1746)
	at com.orientechnologies.orient.core.type.ODocumentWrapper.save(ODocumentWrapper.java:106)
	at com.orientechnologies.orient.core.type.ODocumentWrapperNoClass.save(ODocumentWrapperNoClass.java:88)
	at com.orientechnologies.orient.core.metadata.schema.OSchemaShared.create(OSchemaShared.java:796)
	at com.orientechnologies.orient.core.metadata.schema.OSchemaProxy.create(OSchemaProxy.java:54)
	at com.orientechnologies.orient.core.metadata.OMetadataDefault.create(OMetadataDefault.java:91)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.create(ODatabaseDocumentTx.java:406)
	... 29 more
Caused by: java.lang.NullPointerException
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.callbackHooks(ODatabaseDocumentTx.java:938)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.callbackHookFinalize(ODatabaseDocumentTx.java:2746)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.executeSaveRecord(ODatabaseDocumentTx.java:1742)
	... 40 more
```

It seems to me that reason is following commit: https://github.com/orientechnologies/orientdb/commit/2275b84862d4db3f3ef66956ab02abe9a66a3002

Issue really happens occasianlly and primary on linux boxes.
For datailes take a look to this:
https://travis-ci.org/PhantomYdn/wicket-orientdb/builds/46936996
If I will refresh exactly the same build it might became successfull.

**Comment by PhantomYdn** [comment]
Just found might be related issue: as you can see, sometimes OrientDB is trying to get next available port instead of using previous one. So, it seems to me, that something might be wrong with shutdown synchronization. I don't remember such issues on RC1.

**Comment by laa** [comment]
Hi,
How did you start OrientDB ? In servlet application ? Then you should call com.orientechnologies.orient.core.Orient#startup in http://docs.oracle.com/javaee/6/api/javax/servlet/ServletContextListener.html#contextInitialized%28javax.servlet.ServletContextEvent%29 .
I mark this issue as not a bug now, but if it persists after you add this call, feel free to reopen it.

**Comment by PhantomYdn** [comment]
Guys,

It's not a servlet context directly: lifecycle supported within application.
But that were tests and they were OK on RC1 and doesn't work in 100% on RC2.
Can you, please, point me to some issue wihin RC2 where lifecycle was inforces? Might be some other invokations of startups missing.

**Comment by PhantomYdn** [comment]
I explicitly invoke startup at the very begining of the app lifecycle and the same:

https://travis-ci.org/PhantomYdn/wicket-orientdb/builds/47005552

**Comment by PhantomYdn** [comment]
There is following test case:

```java
final String PLOCAL_DB_NAME = "plocal:testDBLifeCycle";

@Test
	public void testDoubleDbLifeCycle() throws Exception
	{
		testOrientDbLifeCycle(true, false);
		testOrientDbLifeCycle(false, false);
		testOrientDbLifeCycle(false, true); // MAGIC LINE!
	}
	
	public void testOrientDbLifeCycle(boolean createDb, boolean dropDb) throws Exception
	{
		Orient.instance().startup();
		Orient.instance().removeShutdownHook();
		OServer server = OServerMain.create();
		server.startup(OrientDbTestWebApplication.class.getResource("db.config.xml").openStream());
		server.activate();
		if(createDb)
		{
			ODatabaseDocument dbToCreate = new ODatabaseDocumentTx(PLOCAL_DB_NAME);
			if(!dbToCreate.exists()) dbToCreate.create();
			dbToCreate.close();
		}
		ODatabaseDocument db = new OPartitionedDatabasePoolFactory().get(PLOCAL_DB_NAME, "admin", "admin").acquire();
		db.close();
		if(dropDb)
		{
			ODatabaseDocument dbToDrop = new ODatabaseDocumentTx(PLOCAL_DB_NAME);
			dbToDrop.open("admin", "admin");
			dbToDrop.drop();
		}
		server.shutdown();
		Orient.instance().shutdown();
	}
```

If you will run this from scratch: it will be OK. 

But if you then:
1) comment out "magic line"
2) run test one more time (it will be OK)
3) and one more time(!!!!)

P.3 will not be sucessfull.

Exception:
```java
Caused by: java.lang.NullPointerException
	at com.orientechnologies.orient.core.serialization.serializer.record.OSerializationSetThreadLocal.check(OSerializationSetThreadLocal.java:41)
	at com.orientechnologies.orient.core.db.record.ORecordLazySet$1.<init>(ORecordLazySet.java:80)
	at com.orientechnologies.orient.core.db.record.ORecordLazySet.iterator(ORecordLazySet.java:78)
	at com.orientechnologies.orient.core.metadata.security.OUser.fromStream(OUser.java:92)
	at com.orientechnologies.orient.core.metadata.security.OUser.<init>(OUser.java:74)
	at com.orientechnologies.orient.core.metadata.security.OSecurityShared.getUser(OSecurityShared.java:493)
	at com.orientechnologies.orient.core.metadata.security.OSecurityShared.getUser(OSecurityShared.java:215)
	at com.orientechnologies.orient.core.metadata.security.OSecurityShared.authenticate(OSecurityShared.java:169)
	at com.orientechnologies.orient.core.metadata.security.OSecurityProxy.authenticate(OSecurityProxy.java:87)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.open(ODatabaseDocumentTx.java:259)
```

P.S. some dramatic change in RC2:(( It's much further from final than RC1...

**Comment by laa** [comment]
Illa,
Thank you very much that is what I needed !

On Thu, Jan 15, 2015 at 10:02 AM, Ilia Naryzhny <notifications@github.com>
wrote:

> There is following test case:
>
> final String PLOCAL_DB_NAME = "plocal:testDBLifeCycle";
>
> @Test
>     public void testDoubleDbLifeCycle() throws Exception
>     {
>         testOrientDbLifeCycle(true, false);
>         testOrientDbLifeCycle(false, false);
>         testOrientDbLifeCycle(false, true); // MAGIC LINE!
>     }
>
>     public void testOrientDbLifeCycle(boolean createDb, boolean dropDb) throws Exception
>     {
>         Orient.instance().startup();
>         Orient.instance().removeShutdownHook();
>         OServer server = OServerMain.create();
>         server.startup(OrientDbTestWebApplication.class.getResource("db.config.xml").openStream());
>         server.activate();
>         if(createDb)
>         {
>             ODatabaseDocument dbToCreate = new ODatabaseDocumentTx(PLOCAL_DB_NAME);
>             if(!dbToCreate.exists()) dbToCreate.create();
>             dbToCreate.close();
>         }
>         ODatabaseDocument db = new OPartitionedDatabasePoolFactory().get(PLOCAL_DB_NAME, "admin", "admin").acquire();
>         db.close();
>         if(dropDb)
>         {
>             ODatabaseDocument dbToDrop = new ODatabaseDocumentTx(PLOCAL_DB_NAME);
>             dbToDrop.open("admin", "admin");
>             dbToDrop.drop();
>         }
>         server.shutdown();
>         Orient.instance().shutdown();
>     }
>
> If you will run this from scratch: it will be OK.
>
> But if you then:
> 1) comment out "magic line"
> 2) run test one more time (it will be OK)
> 3) and one more time(!!!!)
>
> P.3 will not be sucessfull.
>
> Exception:
>
> Caused by: java.lang.NullPointerException
>     at com.orientechnologies.orient.core.serialization.serializer.record.OSerializationSetThreadLocal.check(OSerializationSetThreadLocal.java:41)
>     at com.orientechnologies.orient.core.db.record.ORecordLazySet$1.<init>(ORecordLazySet.java:80)
>     at com.orientechnologies.orient.core.db.record.ORecordLazySet.iterator(ORecordLazySet.java:78)
>     at com.orientechnologies.orient.core.metadata.security.OUser.fromStream(OUser.java:92)
>     at com.orientechnologies.orient.core.metadata.security.OUser.<init>(OUser.java:74)
>     at com.orientechnologies.orient.core.metadata.security.OSecurityShared.getUser(OSecurityShared.java:493)
>     at com.orientechnologies.orient.core.metadata.security.OSecurityShared.getUser(OSecurityShared.java:215)
>     at com.orientechnologies.orient.core.metadata.security.OSecurityShared.authenticate(OSecurityShared.java:169)
>     at com.orientechnologies.orient.core.metadata.security.OSecurityProxy.authenticate(OSecurityProxy.java:87)
>     at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.open(ODatabaseDocumentTx.java:259)
>
> P.S. some dramatic change in RC2:(( It's much further from final than
> RC1...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/orientechnologies/orientdb/issues/3387#issuecomment-70051613>
> .
>



-- 
Best regards,
Andrey Lomakin.

**Comment by PhantomYdn** [comment]
@laa 

Thank you for fix, but original Exception is still there...
Mentioned testcase at the and sometimes returns me following even on my desktop.
I have idea, that repeating of the issue depends upon hardware what you have. So sometimes I can catch this:

```java
com.orientechnologies.common.exception.OException: Error on creation of shared resource
	at com.orientechnologies.common.concur.resource.OSharedContainerImpl.getResource(OSharedContainerImpl.java:59)
	at com.orientechnologies.orient.core.metadata.OMetadataDefault.init(OMetadataDefault.java:175)
	at com.orientechnologies.orient.core.metadata.OMetadataDefault.load(OMetadataDefault.java:77)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.initAtFirstOpen(ODatabaseDocumentTx.java:2626)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.open(ODatabaseDocumentTx.java:254)
	at com.orientechnologies.orient.core.db.OPartitionedDatabasePool.acquire(OPartitionedDatabasePool.java:285)
	at ru.ydn.wicket.wicketorientdb.orientdb.TestStandaloneOrientDBCompatibility.testOrientDbLifeCycle(TestStandaloneOrientDBCompatibility.java:135)
	at ru.ydn.wicket.wicketorientdb.orientdb.TestStandaloneOrientDBCompatibility.testPLocalDbLifeCycle(TestStandaloneOrientDBCompatibility.java:89)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)
Caused by: com.orientechnologies.orient.core.exception.ORecordNotFoundException: The record with id '#0:1' not found
	at com.orientechnologies.orient.core.record.ORecordAbstract.reload(ORecordAbstract.java:266)
	at com.orientechnologies.orient.core.record.impl.ODocument.reload(ODocument.java:687)
	at com.orientechnologies.orient.core.type.ODocumentWrapper.reload(ODocumentWrapper.java:91)
	at com.orientechnologies.orient.core.type.ODocumentWrapperNoClass.reload(ODocumentWrapperNoClass.java:73)
	at com.orientechnologies.orient.core.metadata.schema.OSchemaShared.load(OSchemaShared.java:784)
	at com.orientechnologies.orient.core.metadata.OMetadataDefault$1.call(OMetadataDefault.java:180)
	at com.orientechnologies.orient.core.metadata.OMetadataDefault$1.call(OMetadataDefault.java:175)
	at com.orientechnologies.common.concur.resource.OSharedContainerImpl.getResource(OSharedContainerImpl.java:57)
	... 30 more
Caused by: com.orientechnologies.orient.core.exception.ODatabaseException: Error on retrieving record #0:1 (cluster: internal)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.executeReadRecord(ODatabaseDocumentTx.java:1601)
	at com.orientechnologies.orient.core.tx.OTransactionNoTx.loadRecord(OTransactionNoTx.java:80)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.reload(ODatabaseDocumentTx.java:1449)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.reload(ODatabaseDocumentTx.java:117)
	at com.orientechnologies.orient.core.record.ORecordAbstract.reload(ORecordAbstract.java:260)
	... 37 more
Caused by: java.lang.NullPointerException
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.callbackHooks(ODatabaseDocumentTx.java:938)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.executeReadRecord(ODatabaseDocumentTx.java:1583)
	... 41 more
```

@laa , @lvca ,

If you don't mind: can we have provided test case somewhere in OrientDB?
I understand, that it's a little bit tricky and require reload, but even simple version will ensure that everything is OK if run OrientDB in the same JVM.

A little bit enhanced version:

```java
final String PLOCAL_DB_NAME = "plocal:testDBLifeCycle";
	final String MEMORY_DB_NAME = "memory:testDBLifeCycle";
	
	@Test
	public void testPLocalDbLifeCycle() throws Exception
	{
		testOrientDbLifeCycle(PLOCAL_DB_NAME, true, false);
		testOrientDbLifeCycle(PLOCAL_DB_NAME, false, false);
		testOrientDbLifeCycle(PLOCAL_DB_NAME, false, true);
		testOrientDbLifeCycle(PLOCAL_DB_NAME, true, false);
		testOrientDbLifeCycle(PLOCAL_DB_NAME, false, true);
	}
	
	@Test
	public void testPLocalDbLifeCycleSVT() throws Exception
	{
		for(int i=0;i<10;i++)
			testOrientDbLifeCycle(PLOCAL_DB_NAME, true, true);
	}
	
	@Test
	public void testMemoryDbLifeCycle() throws Exception
	{
		for(int i=0;i<10;i++)
			testOrientDbLifeCycle(MEMORY_DB_NAME, true, true);
	}
	
	@Test(expected=OStorageException.class)
	public void testMemoryDBShouldDisapear() throws Exception
	{
		try
		{
			testOrientDbLifeCycle(MEMORY_DB_NAME, true, false);
			testOrientDbLifeCycle(MEMORY_DB_NAME, false, true);
		} finally
		{
			Orient.instance().shutdown();
		}
	}
	
	public void testOrientDbLifeCycle(String dbURL, boolean createDb, boolean dropDb) throws Exception
	{
		Orient.instance().startup();
		Orient.instance().removeShutdownHook();
		OServer server = OServerMain.create();
		server.startup(OrientDbTestWebApplication.class.getResource("db.config.xml").openStream());
		server.activate();
		if(createDb)
		{
			ODatabaseDocument dbToCreate = new ODatabaseDocumentTx(dbURL);
			if(!dbToCreate.exists()) dbToCreate.create();
			dbToCreate.close();
		}
		ODatabaseDocument db = new OPartitionedDatabasePoolFactory().get(dbURL, "admin", "admin").acquire();
		db.close();
		if(dropDb)
		{
			ODatabaseDocument dbToDrop = new ODatabaseDocumentTx(dbURL);
			dbToDrop.open("admin", "admin");
			dbToDrop.drop();
		}
		server.shutdown();
		Orient.instance().shutdown();
	}
```

**Comment by PhantomYdn** [comment]
And finally, it seems to me that problem is in shutdown process: problem with startup occur on second loop. If add Thread.sleep(XXX) it might help, but it my case it leads to even more unpredictable errors. 
Plus one more NullPointerException to the collection:)

```java
Caused by: java.lang.NullPointerException
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.setCurrentDatabaseInThreadLocal(ODatabaseDocumentTx.java:2568)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.create(ODatabaseDocumentTx.java:357)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.create(ODatabaseDocumentTx.java:352)
	at ru.ydn.wicket.wicketorientdb.OrientDbTestWebApplication$1.onAfterServerStartupAndActivation(OrientDbTestWebApplication.java:29)
	at ru.ydn.wicket.wicketorientdb.EmbeddOrientDbApplicationListener.onAfterInitialized(EmbeddOrientDbApplicationListener.java:78)
```

More complete stacktrace: https://travis-ci.org/PhantomYdn/wicket-orientdb/builds/47191827

**Comment by laa** [comment]
Illa on latest version I tried like 10 times without success in reproduction of given bug. We should investigate it on your side. Please feel free to access me through Skype as you will be online and have time to investigate given problem.

**Comment by PhantomYdn** [comment]
Thank you, Andrey!
Latest commit do fix the problem. Please advice when are you going to have RC3? It's pretty inconvinient to stick on SNAPSHOT version...

**Comment by laa** [comment]
It is question for @lvca  :-)

**Comment by lvca** [comment]
I don't know if releasing 2.0-rc3 could help since on Tuesday we'll release the final one.

**Comment by PhantomYdn** [comment]
That's good news:) But once rc2 was a little bit not so stable as rc1: it might be natural to expect  degradation...
