### ISSUE TITLE
NullPointerException on DB shutdown

### ISSUE THREAD

**Issue by PhantomYdn** [orientechnologies/orientdb#3391]
Guys,

Something really wrong with RC2. 
On shutdown I see sometimes following

```java
java.lang.NullPointerException
        at com.orientechnologies.orient.server.OClientConnectionManager.<init>(OClientConnectionManager.java:58)
        at com.orientechnologies.orient.server.OClientConnectionManager.<clinit>(OClientConnectionManager.java:51)
        at com.orientechnologies.orient.server.OServer.shutdown(OServer.java:344)
        at ru.ydn.wicket.wicketorientdb.EmbeddOrientDbApplicationListener.onBeforeDestroyed(EmbeddOrientDbApplicationListener.java:93)
        at org.apache.wicket.ApplicationListenerCollection$2.notify(ApplicationListenerCollection.java:52)
        at org.apache.wicket.ApplicationListenerCollection$2.notify(ApplicationListenerCollection.java:48)
        at org.apache.wicket.util.listener.ListenerCollection$1.notify(ListenerCollection.java:120)
        at org.apache.wicket.util.listener.ListenerCollection.reversedNotify(ListenerCollection.java:144)
        at org.apache.wicket.util.listener.ListenerCollection.reversedNotifyIgnoringExceptions(ListenerCollection.java:113)
        at org.apache.wicket.ApplicationListenerCollection.onBeforeDestroyed(ApplicationListenerCollection.java:47)
        at org.apache.wicket.Application.internalDestroy(Application.java:651)
        at org.apache.wicket.protocol.http.WebApplication.internalDestroy(WebApplication.java:701)
        at org.apache.wicket.protocol.http.WicketFilter.destroy(WicketFilter.java:588)
        at org.eclipse.jetty.servlet.FilterHolder.destroyInstance(FilterHolder.java:141)
        at org.eclipse.jetty.servlet.FilterHolder.doStop(FilterHolder.java:119)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.stop(AbstractLifeCycle.java:89)
        at org.eclipse.jetty.servlet.ServletHandler.doStop(ServletHandler.java:195)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.stop(AbstractLifeCycle.java:89)
        at org.eclipse.jetty.server.handler.HandlerWrapper.doStop(HandlerWrapper.java:107)
        at org.eclipse.jetty.security.SecurityHandler.doStop(SecurityHandler.java:391)
        at org.eclipse.jetty.security.ConstraintSecurityHandler.doStop(ConstraintSecurityHandler.java:243)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.stop(AbstractLifeCycle.java:89)
        at org.eclipse.jetty.server.handler.HandlerWrapper.doStop(HandlerWrapper.java:107)
        at org.eclipse.jetty.server.session.SessionHandler.doStop(SessionHandler.java:132)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.stop(AbstractLifeCycle.java:89)
        at org.eclipse.jetty.server.handler.HandlerWrapper.doStop(HandlerWrapper.java:107)
        at org.eclipse.jetty.server.handler.ContextHandler.doStop(ContextHandler.java:777)
        at org.eclipse.jetty.servlet.ServletContextHandler.doStop(ServletContextHandler.java:149)
        at org.eclipse.jetty.webapp.WebAppContext.doStop(WebAppContext.java:506)
        at org.mortbay.jetty.plugin.JettyWebAppContext.doStop(JettyWebAppContext.java:279)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.stop(AbstractLifeCycle.java:89)
        at org.eclipse.jetty.server.handler.HandlerCollection.doStop(HandlerCollection.java:250)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.stop(AbstractLifeCycle.java:89)
        at org.eclipse.jetty.server.handler.HandlerCollection.doStop(HandlerCollection.java:250)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.stop(AbstractLifeCycle.java:89)
        at org.eclipse.jetty.server.handler.HandlerWrapper.doStop(HandlerWrapper.java:107)
        at org.eclipse.jetty.server.Server.doStop(Server.java:342)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.stop(AbstractLifeCycle.java:89)
        at org.eclipse.jetty.util.thread.ShutdownThread.run(ShutdownThread.java:132)
``` 

Might be related to #3387. 
Unfortunatly, considering switching back to RC1:(

**Comment by PhantomYdn** [comment]
Guys,

Final problem is there: OClientConnectionManager.

If OClientConnectionManager was not used before shutdown it can't be even initialized as class because of "static XXX instance" construction require running Orient instance which is actually is shutting down.
