### ISSUE TITLE
WARNING segment file 'database.ocf' was not closed correctly last time

### ISSUE THREAD

**Issue by SpareShade** [orientechnologies/orientdb#3392]
Hello guys,
I'm getting the above warning quite often, and as consequence I cannot access the DB.
Orientdb is running on Ubuntu ( in Virtualbox ), using the 
```
OrientDB Server v2.0-rc2 (build UNKNOWN@r; 2015-01-12 23:01:40+0000) 
```

```
2015-01-15 17:45:16:327 WARNING segment file 'database.ocf' was not closed correctly last time [OSingleFileSegment]
2015-01-15 17:45:16:577 WARNING Storage galleryapp was not closed properly. Will try to restore from write ahead log. [OLocalPaginatedStorage]
2015-01-15 17:45:16:577 INFO  Looking for last checkpoint... [OLocalPaginatedStorage]
2015-01-15 17:45:16:593 INFO  FULL checkpoint found. [OLocalPaginatedStorage]
2015-01-15 17:45:16:596 INFO  Data restore procedure from full checkpoint is started. Restore is performed from LSN OLogSequenceNumber{segment=2, position=27136736} [OLocalPaginatedStorage]java.lang.OutOfMemoryError: Java heap space
Dumping heap to java_pid2578.hprof ...
Heap dump file created [8838559 bytes in 0.108 secs]
java.net.SocketException: Socket closed
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.read(SocketInputStream.java:152)
	at java.net.SocketInputStream.read(SocketInputStream.java:122)
	at java.io.BufferedInputStream.fill(BufferedInputStream.java:235)
	at java.io.BufferedInputStream.read(BufferedInputStream.java:254)
	at com.orientechnologies.orient.enterprise.channel.text.OChannelText.read(OChannelText.java:61)
	at com.orientechnologies.orient.server.network.protocol.http.ONetworkProtocolHttpAbstract.readAllContent(ONetworkProtocolHttpAbstract.java:419)
	at com.orientechnologies.orient.server.network.protocol.http.ONetworkProtocolHttpAbstract.execute(ONetworkProtocolHttpAbstract.java:626)
	at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:65)
```
I cannot see much activity with orientdb instance as in attempting to "Data restore procedure from full checkpoint is started", and on subsequent attempts to access the DB, the server outputs:

```
2015-01-15 17:52:00:366 WARNING segment file 'database.ocf' was not closed correctly last time [OSingleFileSegment]
2015-01-15 17:52:00:396 SEVERE Internal server error:
com.orientechnologies.orient.core.exception.OStorageException: Cannot open local storage '/opt/orientdb-community-2.0-rc2/databases/galleryapp' with mode=rw
--> com.orientechnologies.common.concur.lock.OLockException: File '/opt/orientdb-community-2.0-rc2/databases/galleryapp/internal.pcl' is locked by another process, maybe the database is in use by another process. Use the remote mode with a OrientDB server to allow multiple access to the same database. [ONetworkProtocolHttpDb]
```

Could these be due to putting the machine to sleep?

**Comment by SpareShade** [comment]
In addition, the database was started with orientdb's rc1 version, and if when I try to open it with rc1 instead of rc2 I some extra info "File with id 134 does not exist". not sure if that helps :)
(db naming is different but it is the same db all the way through)
```
2015-01-15 18:39:36:899 SEVERE Internal server error:
com.orientechnologies.orient.core.exception.OStorageException: Cannot open local storage '/opt/orientdb/databases/galleryapp-rc2' with mode=rw
--> com.orientechnologies.orient.core.exception.OStorageException: File with id 134 does not exist. [ONetworkProtocolHttpDb]

**Comment by laa** [comment]
Hi,
That is because you have huge restore buffer such huge is not needed any more so I will make it small.

**Comment by laa** [comment]
Also you error means that you do not close server correctly. How do you close server btw ?

**Comment by Uditmittal** [comment]
Hello Team,
i still get this error With  v2.0
Connecting to database [remote:localhost/tikali] with user 'root'...
2016-05-20 05:38:07:563 WARNING {db=tikali} segment file 'database.ocf' was not closed correctly last time [OSingleFileSegment]
2016-05-20 05:38:07:816 WARNING {db=tikali} Storage tikali was not closed properly. Will try to restore from write ahead log. [OLocalPaginatedStorage]
2016-05-20 05:38:07:817 INFO  {db=tikali} Looking for last checkpoint... [OLocalPaginatedStorage]
2016-05-20 05:38:07:866 INFO  {db=tikali} Found FUZZY checkpoint. [OLocalPaginatedStorage]
2016-05-20 05:38:07:875 INFO  {db=tikali} Data restore procedure from FUZZY checkpoint is started. [OLocalPaginatedStorage]
2016-05-20 05:38:25:142 INFO  {db=tikali} WAL size exceed configured heap memory for recovery (storage.wal.restore.batchSize=50000). Fetching WAL records in batch [OLocalPaginatedStorage]{db=tikali} Exception during storage data restore.
com.orientechnologies.orient.core.exception.OStorageException: File with id 145 does not exist.
	at com.orientechnologies.orient.core.index.hashindex.local.cache.OWOWCache.openFile(OWOWCache.java:326)
	at com.orientechnologies.orient.core.index.hashindex.local.cache.OReadWriteDiskCache.openFile(OReadWriteDiskCache.java:166)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.restoreWALBatch(OAbstractPaginatedStorage.java:2470)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.restoreFrom(OAbstractPaginatedStorage.java:2385)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.restoreFromFuzzyCheckPoint(OAbstractPaginatedStorage.java:2306)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.restoreFromCheckPoint(OAbstractPaginatedStorage.java:2281)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.restoreFromWAL(OAbstractPaginatedStorage.java:2214)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.restoreIfNeeded(OAbstractPaginatedStorage.java:1561)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.open(OAbstractPaginatedStorage.java:205)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.open(ODatabaseDocumentTx.java:243)
	at com.orientechnologies.orient.server.OServer.openDatabase(OServer.java:631)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.openDatabase(ONetworkProtocolBinary.java:651)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.executeRequest(ONetworkProtocolBinary.java:282)
	at com.orientechnologies.orient.server.network.protocol.binary.OBinaryNetworkProtocolAbstract.execute(OBinaryNetworkProtocolAbstract.java:216)
	at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:65)
Sent run-time exception to the client /127.0.0.1:60043: com.orientechnologies.orient.core.exception.OStorageException: Cannot open local storage '/fio/realtimesystem/servers/orientdb/databases/tikali' with mode=rw
com.orientechnologies.orient.core.exception.OStorageException: Cannot open local storage '/fio/realtimesystem/servers/orientdb/databases/tikali' with mode=rw
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.open(OAbstractPaginatedStorage.java:214)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.open(ODatabaseDocumentTx.java:243)
	at com.orientechnologies.orient.server.OServer.openDatabase(OServer.java:631)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.openDatabase(ONetworkProtocolBinary.java:651)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.executeRequest(ONetworkProtocolBinary.java:282)
	at com.orientechnologies.orient.server.network.protocol.binary.OBinaryNetworkProtocolAbstract.execute(OBinaryNetworkProtocolAbstract.java:216)
	at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:65)
Caused by: com.orientechnologies.orient.core.exception.OStorageException: File with id 145 does not exist.
	at com.orientechnologies.orient.core.index.hashindex.local.cache.OWOWCache.openFile(OWOWCache.java:326)
	at com.orientechnologies.orient.core.index.hashindex.local.cache.OReadWriteDiskCache.openFile(OReadWriteDiskCache.java:166)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.restoreWALBatch(OAbstractPaginatedStorage.java:2470)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.restoreFrom(OAbstractPaginatedStorage.java:2385)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.restoreFromFuzzyCheckPoint(OAbstractPaginatedStorage.java:2306)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.restoreFromCheckPoint(OAbstractPaginatedStorage.java:2281)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.restoreFromWAL(OAbstractPaginatedStorage.java:2214)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.restoreIfNeeded(OAbstractPaginatedStorage.java:1561)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.open(OAbstractPaginatedStorage.java:205)
	... 6 more

Error: com.orientechnologies.orient.core.exception.OStorageException: Cannot open local storage '/fio/realtimesystem/servers/orientdb/databases/tikali' with mode=rw

Error: com.orientechnologies.orient.core.exception.OStorageException: File with id 145 does not exist.

**Comment by laa** [comment]
@Uditmittal We do not provide support for 2.0 version of community edition. Is this behaviour reproducible in 2.2 version ?

**Comment by kishykumar** [comment]
Luca suggested the following workaround in Orientdb 1.7:
OGlobalConfiguration.STORAGE_KEEP_OPEN.setValue(false);
 
http://orient-database.narkive.com/ybCtrD6X/embedded-database-shutdown
