### ISSUE TITLE
CONFLICTSTRATEGY - automerge

### ISSUE THREAD

**Issue by lvca** [orientechnologies/orientdb#3396]
The database is created and set the CONFLICTSTRATEGY to auto merge. The database server prints the concurrent modification exception. I am currently using 2.0 rc2.

Alter command:  ALTER database CONFLICTSTRATEGY automerge

```
com.orientechnologies.orient.core.exception.OConcurrentModificationException: Cannot UPDATE the record #197:4 because the version is not the latest. Probably you are updating an old record or it has been modified by another user (db=v5 your=v4)
	at com.orientechnologies.orient.core.conflict.OVersionRecordConflictStrategy.checkVersions(OVersionRecordConflictStrategy.java:54)
	at com.orientechnologies.orient.core.conflict.OVersionRecordConflictStrategy.onUpdate(OVersionRecordConflictStrategy.java:41)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.checkAndIncrementVersion(OAbstractPaginatedStorage.java:2006)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.doUpdateRecord(OAbstractPaginatedStorage.java:1640)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.commitEntry(OAbstractPaginatedStorage.java:2087)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.commit(OAbstractPaginatedStorage.java:907)
	at com.orientechnologies.orient.core.tx.OTransactionOptimistic.doCommit(OTransactionOptimistic.java:483)
	at com.orientechnologies.orient.core.tx.OTransactionOptimistic.commit(OTransactionOptimistic.java:147)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.commit(ODatabaseDocumentTx.java:2369)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.commit(ODatabaseDocumentTx.java:2339)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.commit(ONetworkProtocolBinary.java:1087)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.executeRequest(ONetworkProtocolBinary.java:389)
	at com.orientechnologies.orient.server.network.protocol.binary.OBinaryNetworkProtocolAbstract.execute(OBinaryNetworkProtocolAbstract.java:216)
	at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:65)
```

Also Is there a Java API way to configure CONFLICTSTRATEGY when a class is created.

Attached a sample program to re-produce the issue.

```java
import java.util.Set;

import com.orientechnologies.orient.client.remote.OServerAdmin;
import com.orientechnologies.orient.core.metadata.schema.OClass;
import com.orientechnologies.orient.core.sql.OCommandSQL;
import com.tinkerpop.blueprints.Vertex;
import com.tinkerpop.blueprints.impls.orient.OrientBaseGraph;
import com.tinkerpop.blueprints.impls.orient.OrientGraph;
import com.tinkerpop.blueprints.impls.orient.OrientGraphFactory;
import com.tinkerpop.blueprints.impls.orient.OrientGraphNoTx;
import com.tinkerpop.blueprints.impls.orient.OrientVertex;


public final class DatabaseConflictStaterogyTest {

    private String dbName;
    private OrientGraphFactory graphReadFactory;

    public DatabaseConflictStaterogyTest(String dbName) {
        this.dbName = dbName;
        checkAndCreateDatabase(dbName);
    }

    public void runTest() {
        OrientBaseGraph orientGraph = new OrientGraphNoTx(getDBURL());
        createVertexType(orientGraph, "Test");
        orientGraph.shutdown();

        OrientBaseGraph graph = getGraphFactory().getTx();

        Vertex vertex = graph.addVertex("class:Test");
        vertex.setProperty("prop1", "v1-1");
        vertex.setProperty("prop2", "v2-1");
        vertex.setProperty("prop3", "v3-1");
        graph.shutdown();

        Thread th1 = startThread( 2, 1000, "prop1");
        Thread th2 = startThread( 3, 2000, "prop1");
        Thread th3 = startThread( 4, 3000, "prop1");
        try {
            th1.join();
            th2.join();
            th3.join();
        } catch (Exception ex) {
            ex.printStackTrace();
        }

    }

    private Thread startThread(int version, long timeout, String key) {

        Thread th = new Thread() {
            @Override
            public void run() {
                OrientVertex vtx1 = null;
                OrientGraph graph = getGraphFactory().getTx();
                Iterable<Vertex> vtxs = graph.getVertices();
                for (Vertex vtx : vtxs) {
                    vtx1 = (OrientVertex)vtx;
                }
                try {
                    Thread.sleep(timeout);
                } catch (InterruptedException e) {
                    e.printStackTrace();
                }
                vtx1.setProperty(key, "key-" + version);
                graph.commit();
                printVertex(version+"", vtx1);
                graph.shutdown();
            }
        };
        th.start();
        return th;
    }

    public void printVertex(String info, OrientVertex vtx) {
        System.out.println("--------" + info + " ----------");
        System.out.println(vtx);
        Set<String> keys = vtx.getPropertyKeys();
        for (String key: keys) {
            System.out.println("Key = " + key + " Value = " + vtx.getProperty(key));
        }
    }

    /**
     * @return
     */
    public String getDBURL() {
        return "remote:" + "localhost" + "/" + dbName;
    }

    private OrientGraphFactory getGraphFactory() {
        if (graphReadFactory == null) {
            log("Datastore pool created with size : 10, db location: " + getDBURL());
            graphReadFactory = new OrientGraphFactory(getDBURL()).setupPool(1, 10);
        }
        return graphReadFactory;
    }

    /**
     *
     */
    public void checkAndCreateDatabase(String dbName) {
        try {
            OServerAdmin serverAdmin = new OServerAdmin(getDBURL()).connect("root", "C63447B06BE9A894BFB16031C23796421202D3FE136EC5D617578B025F405343");
            if (!serverAdmin.existsDatabase("plocal")) {
                log("Database does not exists. New database is created");
                serverAdmin.createDatabase(dbName,"graph", "plocal");
                OrientBaseGraph orientGraph = new OrientGraphNoTx(getDBURL());
                log("Set database CONFLICTSTRATEGY to automerge");
                orientGraph.command(new OCommandSQL("ALTER database CONFLICTSTRATEGY automerge")).execute();
                orientGraph.shutdown();
            } else {
                log(dbName + "database already exists");
            }
            serverAdmin.close();
        } catch (Exception ex) {
            log("Failed to create database", ex);
        }
    }

    private void createVertexType(OrientBaseGraph orientGraph, String className) {
        OClass clazz = orientGraph.getVertexType(className);
        if (clazz == null) {
            log("Creating vertex type - " + className);
            orientGraph.createVertexType(className);
        }
    }

    private void log(String message) {
        System.out.println(message);
    }

    private void log(String message, Throwable th) {
        System.out.println(th.getMessage());
        th.printStackTrace();
    }

    public static void main(String args[]) {
        DatabaseConflictStaterogyTest test = new DatabaseConflictStaterogyTest("dbcdb");
        test.runTest();
        Runtime.getRuntime().halt(0);
    }
}
```

**Comment by lvca** [comment]
Fixed!

PS: I wish all users provide test case like you :-)
