### ISSUE TITLE
DB building suspended with message 'Max cache limit is reached (3000 vs. 3001), sync flush is performed'

### ISSUE THREAD

**Issue by adithyank** [orientechnologies/orientdb#3412]
OrientDB Version : 2.0 RC-2
OS : CentOS 6.4
JRE : Oracle 1.7.0_55

In our server application we use only one Thread for adding records in OreintDB and multiple Threads will be reading the records. This is how we have designed

We started building our inventory database. After 20% of building, following message got printed in nohup.out continuously for say 110 times and then overall operation halted. The thread dump stayed in the same place when we took the thread dump multiple times.

```
2015-01-17 00:06:15:187 INFO  Max cache limit is reached (3000 vs. 3001), sync flush is performed. [ODiskWriteAheadLog$LogSegment]
2015-01-17 00:06:25:390 INFO  Max cache limit is reached (3000 vs. 3001), sync flush is performed. [ODiskWriteAheadLog$LogSegment]
2015-01-17 00:06:36:070 INFO  Max cache limit is reached (3000 vs. 3001), sync flush is performed. [ODiskWriteAheadLog$LogSegment]
2015-01-17 00:07:00:294 INFO  Max cache limit is reached (3000 vs. 3001), sync flush is performed. [ODiskWriteAheadLog$LogSegment]
2015-01-17 00:07:11:683 INFO  Max cache limit is reached (3000 vs. 3001), sync flush is performed. [ODiskWriteAheadLog$LogSegment]
2015-01-17 00:07:23:506 INFO  Max cache limit is reached (3000 vs. 3001), sync flush is performed. [ODiskWriteAheadLog$LogSegment]
2015-01-17 00:07:32:049 INFO  Max cache limit is reached (3000 vs. 3001), sync flush is performed. [ODiskWriteAheadLog$LogSegment]
2015-01-17 00:07:43:620 INFO  Max cache limit is reached (3000 vs. 3001), sync flush is performed. [ODiskWriteAheadLog$LogSegment]
2015-01-17 00:07:55:173 INFO  Max cache limit is reached (3000 vs. 3001), sync flush is performed. [ODiskWriteAheadLog$LogSegment]
```

The thread dump of the writing thread is given below

```
"InventoryDataPersister" prio=10 tid=0x00007f9cfc14c800 nid=0x4165 waiting on condition [0x00007f9b9affb000]
   java.lang.Thread.State: WAITING (parking)
        at sun.misc.Unsafe.park(Native Method)
        - parking to wait for  <0x00007fa1df3a39a8> (a java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask)
        at java.util.concurrent.locks.LockSupport.park(LockSupport.java:186)
        at java.util.concurrent.FutureTask.awaitDone(FutureTask.java:425)
        at java.util.concurrent.FutureTask.get(FutureTask.java:187)
        at com.orientechnologies.orient.core.index.hashindex.local.cache.OWOWCache.addAllocatedSpace(OWOWCache.java:193)
        at com.orientechnologies.orient.core.index.hashindex.local.cache.OWOWCache.cacheFileContent(OWOWCache.java:914)
        at com.orientechnologies.orient.core.index.hashindex.local.cache.OWOWCache.load(OWOWCache.java:425)
        at com.orientechnologies.orient.core.index.hashindex.local.cache.OReadWriteDiskCache.updateCache(OReadWriteDiskCache.java:676)
        at com.orientechnologies.orient.core.index.hashindex.local.cache.OReadWriteDiskCache.doLoad(OReadWriteDiskCache.java:302)
        at com.orientechnologies.orient.core.index.hashindex.local.cache.OReadWriteDiskCache.load(OReadWriteDiskCache.java:270)
        at com.orientechnologies.orient.core.storage.impl.local.paginated.OPaginatedCluster.addEntry(OPaginatedCluster.java:1338)
        at com.orientechnologies.orient.core.storage.impl.local.paginated.OPaginatedCluster.createRecord(OPaginatedCluster.java:387)
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.doCreateRecord(OAbstractPaginatedStorage.java:1582)
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.commitEntry(OAbstractPaginatedStorage.java:2064)
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.commit(OAbstractPaginatedStorage.java:907)
        at com.orientechnologies.orient.core.tx.OTransactionOptimistic.doCommit(OTransactionOptimistic.java:483)
        at com.orientechnologies.orient.core.tx.OTransactionOptimistic.commit(OTransactionOptimistic.java:147)
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.commit(ODatabaseDocumentTx.java:2369)
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.commit(ODatabaseDocumentTx.java:2339)
        at in.co.nmsworks.documenttdb.db.DocDB.commit(DocDB.java:594)
        at in.co.nmsworks.cygnet.telecom.fault.rcasia.inventory.store.RcaInvWriter.addAll(RcaInvWriter.java:164)
        at in.co.nmsworks.cygnet.telecom.fault.rcasia.inventory.store.RcaInvWriter.addAll(RcaInvWriter.java:117)
        at in.co.nmsworks.cygnet.telecom.fault.rcasia.inventory.dao.InventoryDAO.save(InventoryDAO.java:106)
        at in.co.nmsworks.cygnet.telecom.fault.rcasia.inventory.queue.InventoryDataPersister.saveDAOData(InventoryDataPersister.java:356)
        at in.co.nmsworks.cygnet.telecom.fault.rcasia.inventory.queue.InventoryDataPersister.processAddition(InventoryDataPersister.java:331)
        at in.co.nmsworks.cygnet.telecom.fault.rcasia.inventory.queue.InventoryDataPersister.run(InventoryDataPersister.java:72)

   Locked ownable synchronizers:
        - <0x00007fa1c07dfda0> (a java.util.concurrent.locks.ReentrantReadWriteLock$NonfairSync)
        - <0x00007fa1c10871f8> (a java.util.concurrent.locks.ReentrantReadWriteLock$NonfairSync)
        - <0x00007fa1cb056038> (a java.util.concurrent.locks.ReentrantReadWriteLock$NonfairSync)
        - <0x00007fa1ded819f8> (a java.util.concurrent.locks.ReentrantReadWriteLock$NonfairSync)
        - <0x00007fa1ded81d68> (a java.util.concurrent.locks.ReentrantReadWriteLock$NonfairSync)
        - <0x00007fa1ded81fa8> (a java.util.concurrent.locks.ReentrantReadWriteLock$NonfairSync)
        - <0x00007fa1ded82270> (a java.util.concurrent.locks.ReentrantReadWriteLock$NonfairSync)
        - <0x00007fa1ded82a40> (a java.util.concurrent.locks.ReentrantReadWriteLock$NonfairSync)
        - <0x00007fa1ded82cc0> (a java.util.concurrent.locks.ReentrantReadWriteLock$NonfairSync)
        - <0x00007fa1ded82dd0> (a java.util.concurrent.locks.ReentrantReadWriteLock$NonfairSync)
        - <0x00007fa1ded82f90> (a java.util.concurrent.locks.ReentrantReadWriteLock$NonfairSync)
        - <0x00007fa1ded83188> (a java.util.concurrent.locks.ReentrantReadWriteLock$NonfairSync)
        - <0x00007fa1ded83380> (a java.util.concurrent.locks.ReentrantReadWriteLock$NonfairSync)
        - <0x00007fa1ded83578> (a java.util.concurrent.locks.ReentrantReadWriteLock$NonfairSync)
        - <0x00007fa1ded83770> (a java.util.concurrent.locks.ReentrantReadWriteLock$NonfairSync)
        - <0x00007fa1ded83ff0> (a java.util.concurrent.locks.ReentrantReadWriteLock$NonfairSync)
        - <0x00007fa1ded85460> (a java.util.concurrent.locks.ReentrantReadWriteLock$NonfairSync)
        - <0x00007fa1ded88ad8> (a java.util.concurrent.locks.ReentrantReadWriteLock$NonfairSync)
        - <0x00007fa1ded8d130> (a java.util.concurrent.locks.ReentrantReadWriteLock$NonfairSync)
        - <0x00007fa1ded912a8> (a java.util.concurrent.locks.ReentrantReadWriteLock$NonfairSync)
        - <0x00007fa1ded91a58> (a java.util.concurrent.locks.ReentrantReadWriteLock$NonfairSync)
        - <0x00007fa1ded95148> (a java.util.concurrent.locks.ReentrantReadWriteLock$NonfairSync)
        - <0x00007fa1deda09c0> (a java.util.concurrent.locks.ReentrantReadWriteLock$NonfairSync)
        - <0x00007fa1dedaa518> (a java.util.concurrent.locks.ReentrantReadWriteLock$NonfairSync)
        - <0x00007fa1dedaf918> (a java.util.concurrent.locks.ReentrantReadWriteLock$NonfairSync)
        - <0x00007fa1dedb0e00> (a java.util.concurrent.locks.ReentrantReadWriteLock$NonfairSync)
        - <0x00007fa1dedb1040> (a java.util.concurrent.locks.ReentrantReadWriteLock$NonfairSync)
        - <0x00007fa1dedc90d8> (a java.util.concurrent.locks.ReentrantReadWriteLock$NonfairSync)
        - <0x00007fa1dee2d3b0> (a java.util.concurrent.locks.ReentrantReadWriteLock$NonfairSync)
        - <0x00007fa1dee34288> (a java.util.concurrent.locks.ReentrantReadWriteLock$NonfairSync)
        - <0x00007fa1dee344c8> (a java.util.concurrent.locks.ReentrantReadWriteLock$NonfairSync)
```

In this stage, we checked the size of the orientdb directory, it was 163 GB. Usually, the size of the DB will be 60GB after the inventory building is 100% over. Now, even with 20% of inventory building, the size of the DB is 163 GB. The database directory had around 700 `*.wal` files totaling to 153 GB. This is another unusual behavior we observed. The free disk space was 50GB at this stage.

Then we did shutdown our application gracefully using kill <pid> (not kill -9 <pid>). After that, we got message in nohup that orient shutdown complete.

Then when we restarted the application, all indices started rebuilding.

So, to avoid long time in index rebuilding, we had to delete the database directory and starting the inventory building again from starting. Since, it is a testing environment, we could do this. But, this may occur again as we did not do any other change.

Another Input:
We explicit set below two variables
``` java
OGlobalConfiguration.STORAGE_LOCK_TIMEOUT.setValue(5 * 60 * 1000);
OGlobalConfiguration.MVRBTREE_TIMEOUT.setValue(5 * 60 * 1000);
```

My Questions

1. Why the `*.wal` files occupy 153 DB when the inventory building is just 20% over.
2. Even after proper shutdown of Orient, why the indices started rebuilding?

**Comment by laa** [comment]
Hi @adithyank ,
Could you repeat this test and give:
1. Full thread dump not only  single thread.
2. Send me your Skype account.

About your questions:
1. "Why the *.wal files occupy 153 DB when the inventory building is just 20% over." You have stucked on fuzzy checkpoint which should remove unneeded wal files.
2. What about concrete storage shutdown did you get message that your storage was closed ?

I am very worried about character of your bugs, may we have a chat to have a chance to resolve them all before 2.0 release ?

**Comment by adithyank** [comment]
@laa I have some difficulty in installing skype in my CentOS-7 laptop. Can we chat using my gmail id (adithyank@gmail.com).....?

**Comment by adithyank** [comment]
@laa I have some difficulty in getting skype installed in my centos-7 laptop...
Is my gmail id ok (adi.k.dev@gmail.com).....?

**Comment by laa** [comment]
Yes, sure no problem. I asked Skype because it is very popular IM system.

On Sat, Jan 17, 2015 at 9:21 PM, K Adithyan <notifications@github.com>
wrote:

> @laa <https://github.com/laa> I have some difficulty in getting skype
> installed in my centos-7 laptop...
> Is my gmail id ok (adi.k.dev@gmail.com).....?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/orientechnologies/orientdb/issues/3412#issuecomment-70380346>
> .
>



-- 
Best regards,
Andrey Lomakin.

**Comment by adithyank** [comment]
Full thread dump taken during that time is given here...

https://www.dropbox.com/s/debri08ox1fopan/orientHangThreadDump.txt?dl=0

**Comment by adithyank** [comment]
Same issue with new jars of 2.0snapshot build... attaching the full thread dump now...

https://www.dropbox.com/s/1qoehl3hs2hw9yb/orientHangTD.txt?dl=0

**Comment by adithyank** [comment]
Andrey, sorry !
The operation did not get suspended now. it is running only
we have wrongly decided based on the messages in nohup. We will observe for some more time and tell you
Sorry.

**Comment by adithyank** [comment]
It got suspended... Attaching the thread dumps

https://www.dropbox.com/s/mdq020iuuki6tbu/td.zip?dl=0

**Comment by adithyank** [comment]
It is running still
But, after our inventory building is 70% done, the below Exception came and nothing got saved after that

```
com.orientechnologies.orient.core.exception.OLowDiskSpaceException: Error occurred while executing a write operation to database 'rcainv' due to limited free space on the disk (52448 MB). The database is now working in read-only mode. Please close the database (or stop OrientDB), make room on your hard drive and then reopen the database. The minimal required space is (52476 MB). Required space is calculated as sum of disk space required by WAL (you can change it by setting parameter storage.wal.maxSize) and space required for data.
       at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.checkLowDiskSpace(OAbstractPaginatedStorage.java:2575) ~[orientdb-core-2.1-SNAPSHOT.jar:2.1-SNAPSHOT]
       at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.commit(OAbstractPaginatedStorage.java:883) ~[orientdb-core-2.1-SNAPSHOT.jar:2.1-SNAPSHOT]
       at com.orientechnologies.orient.core.tx.OTransactionOptimistic.doCommit(OTransactionOptimistic.java:483) ~[orientdb-core-2.1-SNAPSHOT.jar:2.1-SNAPSHOT]
       at com.orientechnologies.orient.core.tx.OTransactionOptimistic.commit(OTransactionOptimistic.java:147) ~[orientdb-core-2.1-SNAPSHOT.jar:2.1-SNAPSHOT]
       at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.commit(ODatabaseDocumentTx.java:2370) ~[orientdb-core-2.1-SNAPSHOT.jar:2.1-SNAPSHOT]
       at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.commit(ODatabaseDocumentTx.java:2340) ~[orientdb-core-2.1-SNAPSHOT.jar:2.1-SNAPSHOT]
       at in.co.nmsworks.documenttdb.db.DocDB.commit(DocDB.java:580) ~[cygnetOTNMS.jar:?]
       at in.co.nmsworks.cygnet.telecom.fault.rcasia.inventory.store.RcaInvWriter.addAll(RcaInvWriter.java:166) [cygnetOTNMS.jar:?]
       at in.co.nmsworks.cygnet.telecom.fault.rcasia.inventory.store.RcaInvWriter.addAll(RcaInvWriter.java:132) [cygnetOTNMS.jar:?]
       at in.co.nmsworks.cygnet.telecom.fault.rcasia.inventory.dao.InventoryDAO.save(InventoryDAO.java:106) [cygnetOTNMS.jar:?]
```

but, the particular partition has 13GB free.

**Comment by lvca** [comment]
In 2.0.1-hotfix and develop branches I've slightly improved this message to report also the current DiskCache settings. However can you provide us the first line of log that reports WAL size?

**Comment by adithyank** [comment]
@lvca I am giving what you asked. But, I am informing yout hat andrey is already on the job to resolve this issue

```
INFO: OrientDB auto-config DISKCACHE=13,094MB (heap=17,066MB os=32,209MB disk=193,405MB)
```

**Comment by lvca** [comment]
I've reopened it. Please let me know if it's already fixed.

**Comment by adithyank** [comment]
After the distribution orientdb-community-2.0.1-SNAPSHOT-distribution.zip shared by Andrey, we built the inventory twice... 

1. The inventory building completed successfully. It did not get suspended in the middle
2. Low disk space exception did not come

So, this build is okay

**Comment by lvca** [comment]
Great, thanks.

**Comment by dikaiosune** [comment]
I think I'm experiencing a similar issue in 2.0.1/2/3:

```
INFO  [2015-03-01 19:06:19,031] com.orientechnologies.orient.core.storage.impl.local.paginated.wal.ODiskWriteAheadLog$LogSegment: {db=bacon} Max cache limit is reached (3000 vs. 3002), sync flush is performed.
INFO  [2015-03-01 19:06:34,362] com.orientechnologies.orient.core.storage.impl.local.paginated.wal.ODiskWriteAheadLog$LogSegment: {db=bacon} Max cache limit is reached (3000 vs. 3001), sync flush is performed.
INFO  [2015-03-01 19:06:42,444] com.orientechnologies.orient.core.storage.impl.local.paginated.wal.ODiskWriteAheadLog$LogSegment: {db=bacon} Max cache limit is reached (3000 vs. 3001), sync flush is performed.
INFO  [2015-03-01 19:06:50,572] com.orientechnologies.orient.core.storage.impl.local.paginated.wal.ODiskWriteAheadLog$LogSegment: {db=bacon} Max cache limit is reached (3000 vs. 3001), sync flush is performed.
INFO  [2015-03-01 19:07:01,158] com.orientechnologies.orient.core.storage.impl.local.paginated.wal.ODiskWriteAheadLog$LogSegment: {db=bacon} Max cache limit is reached (3000 vs. 3002), sync flush is performed.
```

Here is the thread dump:

https://dl.dropboxusercontent.com/u/622920/orientdb-threaddump-030115.txt

I've tried three different versions (2.0.1, 2.0.2, 2.0.3) and I can reproduce in all of them. Here are the two flush threads in VisualVM:

![image](https://cloud.githubusercontent.com/assets/6812281/6432409/da151f42-c00d-11e4-93fe-2cfa7458d5a5.png)

Any suggestions for avoiding this issue?

**Comment by lvca** [comment]
@laa Is this an issue or can we downgrade the log level to just debug?

**Comment by dikaiosune** [comment]
It seems to be suspending other operations in the graph -- let me do some more debugging to make sure it's not an issue in my access of the database.

**Comment by laa** [comment]
Hi do you mean execution is frozen forever or waiting for a long time. In last case It is super simple to fix merely increase wal cache size .

**Comment by laa** [comment]
Also write cache wal task has nothing to do with WAL ))
