### ISSUE TITLE
NPE on move Records To Secondary Cache

### ISSUE THREAD

**Issue by azzazeli** [orientechnologies/orientdb#3424]
I have a standalone installation of orient db version 1.7.10 with heavy loading (select, insert, update)
After some time of loading I've found a NPE in logs and orient db server stopped to work.
Here is the log:
```
2015-01-16 17:28:18 ERROR ONetworkProtocolBinary(OrientDB <- BinaryClient (/127.0.0.1:59675)) - Sent run-time exception to the client /127.0.0.1:59675: java.lang.NullPointerException
java.lang.NullPointerException
	at com.orientechnologies.orient.core.cache.OLevel1RecordCache.moveRecordsToSecondaryCache(OLevel1RecordCache.java:149)[orientdb-core-1.7.10.jar:1.7.10]
	at com.orientechnologies.orient.core.cache.OLevel1RecordCache.clear(OLevel1RecordCache.java:140)[orientdb-core-1.7.10.jar:1.7.10]
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.onAfterRequest(ONetworkProtocolBinary.java:199)[orientdb-server-1.7.10.jar:1.7.10]
	at com.orientechnologies.orient.server.network.protocol.binary.OBinaryNetworkProtocolAbstract.execute(OBinaryNetworkProtocolAbstract.java:176)[orientdb-server-1.7.10.jar:1.7.10]
	at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:45)[orient-commons-1.7.10.jar:1.7.10]
2015-01-16 17:28:19 ERROR ONetworkProtocolBinary(OrientDB <- BinaryClient (/127.0.0.1:59679)) - Sent run-time exception to the client /127.0.0.1:59679: com.orientechnologies.orient.core.exception.OConcurrentModificationException: Cannot UPDATE the record #9:104667 because the version is not the latest. Probably you are updating an old record or it has been modified by another user (db=v15 your=v14)
com.orientechnologies.orient.core.exception.OConcurrentModificationException: Cannot UPDATE the record #9:104667 because the version is not the latest. Probably you are updating an old record or it has been modified by another user (db=v15 your=v14)
	at com.orientechnologies.orient.core.storage.impl.local.paginated.OLocalPaginatedStorage.updateRecord(OLocalPaginatedStorage.java:804)[orientdb-core-1.7.10.jar:1.7.10]
	at com.orientechnologies.orient.core.storage.impl.local.paginated.OLocalPaginatedStorage.commitEntry(OLocalPaginatedStorage.java:2105)[orientdb-core-1.7.10.jar:1.7.10]
	at com.orientechnologies.orient.core.storage.impl.local.paginated.OLocalPaginatedStorage.commit(OLocalPaginatedStorage.java:1097)[orientdb-core-1.7.10.jar:1.7.10]
	at com.orientechnologies.orient.core.tx.OTransactionOptimistic.doCommit(OTransactionOptimistic.java:469)[orientdb-core-1.7.10.jar:1.7.10]
	at com.orientechnologies.orient.core.tx.OTransactionOptimistic.commit(OTransactionOptimistic.java:148)[orientdb-core-1.7.10.jar:1.7.10]
	at com.orientechnologies.orient.core.db.record.ODatabaseRecordTx.commit(ODatabaseRecordTx.java:142)[orientdb-core-1.7.10.jar:1.7.10]
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.commit(ODatabaseDocumentTx.java:511)[orientdb-core-1.7.10.jar:1.7.10]
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.commit(ODatabaseDocumentTx.java:503)[orientdb-core-1.7.10.jar:1.7.10]
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.commit(ONetworkProtocolBinary.java:1096)[orientdb-server-1.7.10.jar:1.7.10]
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.executeRequest(ONetworkProtocolBinary.java:344)[orientdb-server-1.7.10.jar:1.7.10]
	at com.orientechnologies.orient.server.network.protocol.binary.OBinaryNetworkProtocolAbstract.execute(OBinaryNetworkProtocolAbstract.java:170)[orientdb-server-1.7.10.jar:1.7.10]
	at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:45)[orient-commons-1.7.10.jar:1.7.10]

```

**Comment by laa** [comment]
HI, in new DB design we do not have second level cache could you try it ?

**Comment by azzazeli** [comment]
I cant use rc version in production.

**Comment by laa** [comment]
Just, wait a week I think and we will release final version.
I will let you know.

**Comment by laa** [comment]
We will release 2.0 tomorrow, so I close issue.
