### ISSUE TITLE
ODB 2.0-RC2 doesn't correctly handle the EDGE creation in distributed mode

### ISSUE THREAD

**Issue by carloprad** [orientechnologies/orientdb#3425]
TEST CASE:
- 2 ODB instances, synchronized in distributed mode (default setting)
- ODB version: 2.0-rc2 (also tried with the 2015/01/19 snapshot)
- JDK: oracle 1.8.0_25 (64 bit)
- O.S.: CentOS Linux release 7.0.1406 (Core) (64 bit)

Here the SQL script:
```
connect remote:localhost/test admin admin

create class Foo extends V
create property Foo.key String
CREATE INDEX FooKey on Foo(key) UNIQUE_HASH_INDEX

create class Bar extends V
create property Bar.key String
CREATE INDEX BarKey on Bar(key) UNIQUE_HASH_INDEX

create class knows extends E

create vertex Foo set key = 'kf001'
create vertex Bar set key = 'kb001'
create edge knows FROM (SELECT FROM Foo WHERE key='kf001') to (SELECT FROM Bar WHERE key='kb001')
```

Here the unexpected behavior (2 records instead of 1):
```
orientdb {db=test}> select from knows

----+-----+------+-----+-----
#   |@RID |@CLASS|out  |in
----+-----+------+-----+-----
0   |#20:0|knows |null |null
1   |#20:1|knows |#18:0|#19:0
----+-----+------+-----+-----

2 item(s) found. Query executed in 0.023 sec(s).
```

**Comment by lvca** [comment]
Reproduced. I'm working on it.

**Comment by carloprad** [comment]
Hi @lvca 
I've just tried with the today's snapshot, now it's impossible to create the edge.

Here the console output:
```
orientdb {db=test}> create edge knows FROM (SELECT FROM Foo WHERE key='kf001') to (SELECT FROM Bar WHERE key='kb001')

Error: com.orientechnologies.orient.core.exception.OStorageException: Cannot route COMMAND operation to the distributed node

Error: com.orientechnologies.orient.server.distributed.ODistributedException: Error on inserting into cluster 'knows' where local node 'centos-7' is not the master of it, but it's 'cetnos-6.6'
```

Here the orientdb log:
```
Sent run-time exception to the client /127.0.0.1:50966: com.orientechnologies.orient.core.exception.OStorageException: Cannot route COMMAND operation to the distributed node
com.orientechnologies.orient.core.exception.OStorageException: Cannot route COMMAND operation to the distributed node
        at com.orientechnologies.orient.server.distributed.ODistributedStorage.handleDistributedException(ODistributedStorage.java:1217)
        at com.orientechnologies.orient.server.distributed.ODistributedStorage.command(ODistributedStorage.java:394)
        at com.orientechnologies.orient.core.command.OCommandRequestTextAbstract.execute(OCommandRequestTextAbstract.java:63)
        at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.command(ONetworkProtocolBinary.java:1180)
        at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.executeRequest(ONetworkProtocolBinary.java:385)
        at com.orientechnologies.orient.server.network.protocol.binary.OBinaryNetworkProtocolAbstract.execute(OBinaryNetworkProtocolAbstract.java:216)
        at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:65)
Caused by: com.orientechnologies.orient.server.distributed.ODistributedException: Error on inserting into cluster 'knows' where local node 'centos-7' is not the master of it, but it's 'cetnos-6.6'
        at com.orientechnologies.orient.server.distributed.ODistributedStorage.createRecord(ODistributedStorage.java:430)
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.executeSaveRecord(ODatabaseDocumentTx.java:1713)
        at com.orientechnologies.orient.core.tx.OTransactionOptimistic.addRecord(OTransactionOptimistic.java:307)
        at com.orientechnologies.orient.core.tx.OTransactionOptimistic.saveRecord(OTransactionOptimistic.java:248)
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.save(ODatabaseDocumentTx.java:2271)
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.save(ODatabaseDocumentTx.java:117)
        at com.orientechnologies.orient.core.record.impl.ODocument.save(ODocument.java:1768)
        at com.orientechnologies.orient.core.record.impl.ODocument.save(ODocument.java:1759)
        at com.orientechnologies.orient.core.record.impl.ODocument.save(ODocument.java:97)
        at com.orientechnologies.orient.core.db.record.ridbag.embedded.OEmbeddedRidBag.serialize(OEmbeddedRidBag.java:369)
        at com.orientechnologies.orient.core.db.record.ridbag.ORidBag.toStream(ORidBag.java:264)
        at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinaryV0.writeSingleValue(ORecordSerializerBinaryV0.java:575)
        at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinaryV0.serialize(ORecordSerializerBinaryV0.java:255)
        at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinary.toStream(ORecordSerializerBinary.java:104)
        at com.orientechnologies.orient.core.record.impl.ODocument.toStream(ODocument.java:2084)
        at com.orientechnologies.orient.core.record.impl.ODocument.toStream(ODocument.java:704)
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.executeSaveRecord(ODatabaseDocumentTx.java:1655)
        at com.orientechnologies.orient.core.tx.OTransactionOptimistic.addRecord(OTransactionOptimistic.java:307)
        at com.orientechnologies.orient.core.tx.OTransactionOptimistic.saveRecord(OTransactionOptimistic.java:248)
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.save(ODatabaseDocumentTx.java:2271)
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.save(ODatabaseDocumentTx.java:117)
        at com.orientechnologies.orient.core.record.impl.ODocument.save(ODocument.java:1768)
        at com.orientechnologies.orient.core.record.impl.ODocument.save(ODocument.java:1759)
        at com.orientechnologies.orient.core.record.impl.ODocument.save(ODocument.java:97)
        at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinaryV0.recursiveLinkSave(ORecordSerializerBinaryV0.java:668)
        at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinaryV0.writeOptimizedLink(ORecordSerializerBinaryV0.java:682)
        at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinaryV0.writeSingleValue(ORecordSerializerBinaryV0.java:566)
        at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinaryV0.serialize(ORecordSerializerBinaryV0.java:255)
        at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinary.toStream(ORecordSerializerBinary.java:104)
        at com.orientechnologies.orient.core.record.impl.ODocument.toStream(ODocument.java:2084)
        at com.orientechnologies.orient.core.record.impl.ODocument.toStream(ODocument.java:704)
        at com.orientechnologies.orient.server.distributed.ODistributedStorage.commit(ODistributedStorage.java:800)
        at com.orientechnologies.orient.core.tx.OTransactionOptimistic.doCommit(OTransactionOptimistic.java:483)
        at com.orientechnologies.orient.core.tx.OTransactionOptimistic.commit(OTransactionOptimistic.java:147)
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.commit(ODatabaseDocumentTx.java:2370)
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.commit(ODatabaseDocumentTx.java:2340)
        at com.tinkerpop.blueprints.impls.orient.OrientTransactionalGraph.commit(OrientTransactionalGraph.java:161)
        at com.orientechnologies.orient.graph.sql.OGraphCommandExecutorSQLFactory.runInTx(OGraphCommandExecutorSQLFactory.java:131)
        at com.orientechnologies.orient.graph.sql.OGraphCommandExecutorSQLFactory.runInTx(OGraphCommandExecutorSQLFactory.java:146)
        at com.orientechnologies.orient.graph.sql.OCommandExecutorSQLCreateEdge.execute(OCommandExecutorSQLCreateEdge.java:126)
        at com.orientechnologies.orient.core.sql.OCommandExecutorSQLDelegate.execute(OCommandExecutorSQLDelegate.java:64)
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.executeCommand(OAbstractPaginatedStorage.java:1174)
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.command(OAbstractPaginatedStorage.java:1163)
        at com.orientechnologies.orient.server.distributed.ODistributedStorage.command(ODistributedStorage.java:237)
        ... 5 more
```

**Comment by carloprad** [comment]
I also tried using lightweight edges, encountering another kind of error:
The edge is created, but we cannot complete a simple "select" query, that indefinitely stands:
```
orientdb {db=test}> alter database custom useLightweightEdges=true

Database updated successfully

orientdb {db=test}> create class Foo extends V

Class created successfully. Total classes in database now: 11

orientdb {db=test}> create property Foo.key String

Property created successfully with id=1

orientdb {db=test}> CREATE INDEX FooKey on Foo(key) UNIQUE_HASH_INDEX


Creating index...
Created index successfully with 0 entries in 3.428000 sec(s).


Index created successfully
orientdb {db=test}> create class Bar extends V

Class created successfully. Total classes in database now: 12

orientdb {db=test}> create property Bar.key String

Property created successfully with id=1

orientdb {db=test}> CREATE INDEX BarKey on Bar(key) UNIQUE_HASH_INDEX


Creating index...
Created index successfully with 0 entries in 3.210000 sec(s).


Index created successfully
orientdb {db=test}> create class knows extends E

Class created successfully. Total classes in database now: 13

orientdb {db=test}> create vertex Foo set key = 'kf001'

Created vertex 'Foo#12:0{key:kf001} v1' in 0.165000 sec(s).

orientdb {db=test}> create vertex Bar set key = 'kb001'

Created vertex 'Bar#13:0{key:kb001} v1' in 0.040000 sec(s).

orientdb {db=test}> create edge knows FROM (SELECT FROM Foo WHERE key='kf001') to (SELECT FROM Bar WHERE key='kb001')

Created edge '[]' in 0.295000 sec(s).

orientdb {db=test}> select from knows
```

Here the orientdb log:
```
error on executing distributed request 16 on local node: record_update(#13:0 v.2)
com.orientechnologies.orient.core.exception.OConcurrentModificationException: Cannot UPDATE the record #13:0 because the version is not the latest. Probably you are updating an old record or it has been modified by another user (db=v3 your=v2)
        at com.orientechnologies.orient.core.conflict.OVersionRecordConflictStrategy.checkVersions(OVersionRecordConflictStrategy.java:54)
        at com.orientechnologies.orient.core.conflict.OVersionRecordConflictStrategy.onUpdate(OVersionRecordConflictStrategy.java:41)
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.checkAndIncrementVersion(OAbstractPaginatedStorage.java:2007)
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.doUpdateRecord(OAbstractPaginatedStorage.java:1641)
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.updateRecord(OAbstractPaginatedStorage.java:724)
        at com.orientechnologies.orient.server.distributed.ODistributedStorage.updateRecord(ODistributedStorage.java:539)
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.executeSaveRecord(ODatabaseDocumentTx.java:1719)
        at com.orientechnologies.orient.core.tx.OTransactionNoTx.saveRecord(OTransactionNoTx.java:94)
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.save(ODatabaseDocumentTx.java:2271)
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.save(ODatabaseDocumentTx.java:2108)
        at com.orientechnologies.orient.server.distributed.task.OUpdateRecordTask.execute(OUpdateRecordTask.java:82)
        at com.orientechnologies.orient.server.hazelcast.OHazelcastPlugin.executeOnLocalNode(OHazelcastPlugin.java:735)
        at com.orientechnologies.orient.server.hazelcast.ODistributedWorker.onMessage(ODistributedWorker.java:300)
        at com.orientechnologies.orient.server.hazelcast.ODistributedWorker.run(ODistributedWorker.java:121)

2015-01-20 11:47:33:371 WARNING [centos-7] detected 1 node(s) in timeout or in conflict and quorum (2) has not been reached, rolling back changes for request (id=16 from=centos-7 task=record_update(#13:0 v.2) userName=admin) [ODistributedResponseManager]
2015-01-20 11:47:33:373 WARNING [centos-7] Quorum 2 not reached for request (id=16 from=centos-7 task=record_update(#13:0 v.2) userName=admin). Timeout=64ms Servers in timeout/conflict are:
 - centos-7: com.orientechnologies.orient.core.exception.OConcurrentModificationException: Cannot UPDATE the record #13:0 because the version is not the latest. Probably you are updating an old record or it has been modified by another user (db=v3 your=v2)
Received: {cetnos-6.6=com.orientechnologies.orient.core.exception.OConcurrentModificationException: Cannot UPDATE the record #13:0 because the version is not the latest. Probably you are updating an old record or it has been modified by another user (db=v3 your=v2), centos-7=com.orientechnologies.orient.core.exception.OConcurrentModificationException: Cannot UPDATE the record #13:0 because the version is not the latest. Probably you are updating an old record or it has been modified by another user (db=v3 your=v2)} [ODistributedResponseManager]
2015-01-20 11:47:33:374 WARNING [centos-7] sending undo message for request (id=16 from=centos-7 task=record_update(#13:0 v.2) userName=admin) to server cetnos-6.6 [ODistributedResponseManager]
2015-01-20 11:47:33:392 WARNING [centos-7] sending undo message for request (id=16 from=centos-7 task=record_update(#13:0 v.2) userName=admin) to server centos-7 [ODistributedResponseManager]Cannot route UPDATE_RECORD operation for #13:0 to the distributed node
com.orientechnologies.orient.server.distributed.ODistributedException: Error on executing distributed request (id=16 from=centos-7 task=record_update(#13:0 v.2) userName=admin) against database 'test.[bar]' to nodes [cetnos-6.6, centos-7]
        at com.orientechnologies.orient.server.hazelcast.OHazelcastDistributedDatabase.send2Nodes(OHazelcastDistributedDatabase.java:194)
        at com.orientechnologies.orient.server.hazelcast.OHazelcastPlugin.sendRequest(OHazelcastPlugin.java:348)
        at com.orientechnologies.orient.server.distributed.ODistributedStorage.updateRecord(ODistributedStorage.java:568)
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.executeSaveRecord(ODatabaseDocumentTx.java:1719)
        at com.orientechnologies.orient.core.tx.OTransactionNoTx.saveRecord(OTransactionNoTx.java:94)
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.save(ODatabaseDocumentTx.java:2271)
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.save(ODatabaseDocumentTx.java:117)
        at com.orientechnologies.orient.core.record.impl.ODocument.save(ODocument.java:1768)
        at com.orientechnologies.orient.core.record.impl.ODocument.save(ODocument.java:1759)
        at com.orientechnologies.orient.core.record.impl.ODocument.save(ODocument.java:97)
        at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinaryV0.recursiveLinkSave(ORecordSerializerBinaryV0.java:668)
        at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinaryV0.writeOptimizedLink(ORecordSerializerBinaryV0.java:682)
        at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinaryV0.writeSingleValue(ORecordSerializerBinaryV0.java:566)
        at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinaryV0.serialize(ORecordSerializerBinaryV0.java:255)
        at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinary.toStream(ORecordSerializerBinary.java:104)
        at com.orientechnologies.orient.core.record.impl.ODocument.toStream(ODocument.java:2084)
        at com.orientechnologies.orient.core.record.impl.ODocument.toStream(ODocument.java:704)
        at com.orientechnologies.orient.server.network.protocol.binary.OBinaryNetworkProtocolAbstract.getRecordBytes(OBinaryNetworkProtocolAbstract.java:407)
        at com.orientechnologies.orient.server.network.protocol.binary.OBinaryNetworkProtocolAbstract.writeRecord(OBinaryNetworkProtocolAbstract.java:422)
        at com.orientechnologies.orient.server.network.protocol.binary.OBinaryNetworkProtocolAbstract.writeIdentifiable(OBinaryNetworkProtocolAbstract.java:139)
        at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.command(ONetworkProtocolBinary.java:1218)
        at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.executeRequest(ONetworkProtocolBinary.java:385)
        at com.orientechnologies.orient.server.network.protocol.binary.OBinaryNetworkProtocolAbstract.execute(OBinaryNetworkProtocolAbstract.java:216)
        at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:65)
Caused by: com.orientechnologies.orient.server.distributed.ODistributedException: Quorum 2 not reached for request (id=16 from=centos-7 task=record_update(#13:0 v.2) userName=admin). Timeout=64ms Servers in timeout/conflict are:
 - centos-7: com.orientechnologies.orient.core.exception.OConcurrentModificationException: Cannot UPDATE the record #13:0 because the version is not the latest. Probably you are updating an old record or it has been modified by another user (db=v3 your=v2)
Received: {cetnos-6.6=com.orientechnologies.orient.core.exception.OConcurrentModificationException: Cannot UPDATE the record #13:0 because the version is not the latest. Probably you are updating an old record or it has been modified by another user (db=v3 your=v2), centos-7=com.orientechnologies.orient.core.exception.OConcurrentModificationException: Cannot UPDATE the record #13:0 because the version is not the latest. Probably you are updating an old record or it has been modified by another user (db=v3 your=v2)}
        at com.orientechnologies.orient.server.distributed.ODistributedResponseManager.manageConflicts(ODistributedResponseManager.java:576)
        at com.orientechnologies.orient.server.distributed.ODistributedResponseManager.getFinalResponse(ODistributedResponseManager.java:340)
        at com.orientechnologies.orient.server.hazelcast.OHazelcastDistributedDatabase.waitForResponse(OHazelcastDistributedDatabase.java:364)
        at com.orientechnologies.orient.server.hazelcast.OHazelcastDistributedDatabase.send2Nodes(OHazelcastDistributedDatabase.java:191)
        ... 23 more
Error on unmarshalling record #-1:-1 (com.orientechnologies.orient.server.distributed.ODistributedException: Quorum 2 not reached for request (id=16 from=centos-7 task=record_update(#13:0 v.2) userName=admin). Timeout=64ms Servers in timeout/conflict are:
 - centos-7: com.orientechnologies.orient.core.exception.OConcurrentModificationException: Cannot UPDATE the record #13:0 because the version is not the latest. Probably you are updating an old record or it has been modified by another user (db=v3 your=v2)
Received: {cetnos-6.6=com.orientechnologies.orient.core.exception.OConcurrentModificationException: Cannot UPDATE the record #13:0 because the version is not the latest. Probably you are updating an old record or it has been modified by another user (db=v3 your=v2), centos-7=com.orientechnologies.orient.core.exception.OConcurrentModificationException: Cannot UPDATE the record #13:0 because the version is not the latest. Probably you are updating an old record or it has been modified by another user (db=v3 your=v2)})
com.orientechnologies.orient.server.distributed.ODistributedException: Quorum 2 not reached for request (id=16 from=centos-7 task=record_update(#13:0 v.2) userName=admin). Timeout=64ms Servers in timeout/conflict are:
 - centos-7: com.orientechnologies.orient.core.exception.OConcurrentModificationException: Cannot UPDATE the record #13:0 because the version is not the latest. Probably you are updating an old record or it has been modified by another user (db=v3 your=v2)
Received: {cetnos-6.6=com.orientechnologies.orient.core.exception.OConcurrentModificationException: Cannot UPDATE the record #13:0 because the version is not the latest. Probably you are updating an old record or it has been modified by another user (db=v3 your=v2), centos-7=com.orientechnologies.orient.core.exception.OConcurrentModificationException: Cannot UPDATE the record #13:0 because the version is not the latest. Probably you are updating an old record or it has been modified by another user (db=v3 your=v2)}
        at com.orientechnologies.orient.server.distributed.ODistributedResponseManager.manageConflicts(ODistributedResponseManager.java:576)
        at com.orientechnologies.orient.server.distributed.ODistributedResponseManager.getFinalResponse(ODistributedResponseManager.java:340)
        at com.orientechnologies.orient.server.hazelcast.OHazelcastDistributedDatabase.waitForResponse(OHazelcastDistributedDatabase.java:364)
        at com.orientechnologies.orient.server.hazelcast.OHazelcastDistributedDatabase.send2Nodes(OHazelcastDistributedDatabase.java:191)
        at com.orientechnologies.orient.server.hazelcast.OHazelcastPlugin.sendRequest(OHazelcastPlugin.java:348)
        at com.orientechnologies.orient.server.distributed.ODistributedStorage.updateRecord(ODistributedStorage.java:568)
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.executeSaveRecord(ODatabaseDocumentTx.java:1719)
        at com.orientechnologies.orient.core.tx.OTransactionNoTx.saveRecord(OTransactionNoTx.java:94)
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.save(ODatabaseDocumentTx.java:2271)
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.save(ODatabaseDocumentTx.java:117)
        at com.orientechnologies.orient.core.record.impl.ODocument.save(ODocument.java:1768)
        at com.orientechnologies.orient.core.record.impl.ODocument.save(ODocument.java:1759)
        at com.orientechnologies.orient.core.record.impl.ODocument.save(ODocument.java:97)
        at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinaryV0.recursiveLinkSave(ORecordSerializerBinaryV0.java:668)
        at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinaryV0.writeOptimizedLink(ORecordSerializerBinaryV0.java:682)
        at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinaryV0.writeSingleValue(ORecordSerializerBinaryV0.java:566)
        at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinaryV0.serialize(ORecordSerializerBinaryV0.java:255)
        at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinary.toStream(ORecordSerializerBinary.java:104)
        at com.orientechnologies.orient.core.record.impl.ODocument.toStream(ODocument.java:2084)
        at com.orientechnologies.orient.core.record.impl.ODocument.toStream(ODocument.java:704)
        at com.orientechnologies.orient.server.network.protocol.binary.OBinaryNetworkProtocolAbstract.getRecordBytes(OBinaryNetworkProtocolAbstract.java:407)
        at com.orientechnologies.orient.server.network.protocol.binary.OBinaryNetworkProtocolAbstract.writeRecord(OBinaryNetworkProtocolAbstract.java:422)
        at com.orientechnologies.orient.server.network.protocol.binary.OBinaryNetworkProtocolAbstract.writeIdentifiable(OBinaryNetworkProtocolAbstract.java:139)
        at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.command(ONetworkProtocolBinary.java:1218)
        at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.executeRequest(ONetworkProtocolBinary.java:385)
        at com.orientechnologies.orient.server.network.protocol.binary.OBinaryNetworkProtocolAbstract.execute(OBinaryNetworkProtocolAbstract.java:216)
        at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:65)

2015-01-20 11:47:33:418 WARNING Cannot serialize record: e[#12:0->#13:0][#12:0-knows->#13:0] [ONetworkProtocolBinary]
```
