### ISSUE TITLE
Vertex.getProperty on an embedded list of documents doesn't work right

### ISSUE THREAD

**Issue by countfloyd** [orientechnologies/orientdb#3427]
I've created a vertex with an embedded list of documents like so:

List<ODocument> l = ....
v.setProperty("rules", l);

Trying to read them back is a problem. If I try:

v.getProperty("rules")

I get an OrientElementIterable containing one ORecordLazyList which contains ODocument's. I haven't been successful converting this to a List.

If I try:

((OrientVertex)v).getRecord().field("rules")

I get an ORecordLazyList of ODocuments which I can then treat like a list and everything is fine. The Vertex.getProperty seems to insert an extra iterable at the top.

**Comment by countfloyd** [comment]
The bigger problem is if I try to iterate on the OrientElementIterable returned from Vertex.getProperty, I get an exception:

```java
[java.lang.IllegalArgumentException: Cannot determine the graph element type because the document class is null. Probably this is a projection, use the EXPAND() function] with root cause
java.lang.IllegalArgumentException: Cannot determine the graph element type because the document class is null. Probably this is a projection, use the EXPAND() function
	at com.tinkerpop.blueprints.impls.orient.OrientElementIterator.next(OrientElementIterator.java:70)
	at com.tinkerpop.blueprints.impls.orient.OrientElementIterator.next(OrientElementIterator.java:34)
	at com.guildone.synergy.server.rest.elements.FiltersResource.getFilterFromVertex(FiltersResource.java:201)
	at com.guildone.synergy.server.rest.elements.FiltersResource.lambda$getFiltersForUser$8(FiltersResource.java:185)
	at com.guildone.synergy.server.rest.elements.FiltersResource$$Lambda$11/732670953.apply(Unknown Source)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.Iterator.forEachRemaining(Iterator.java:116)
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:512)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:502)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at com.guildone.synergy.server.rest.elements.FiltersResource.getFiltersForUser(FiltersResource.java:186)
```java

**Comment by lvca** [comment]
Wich version?

**Comment by countfloyd** [comment]
Sorry, 2.0-rc2

**Comment by lvca** [comment]
Please could you provide a test case for this?

**Comment by countfloyd** [comment]
OK, here is a testcase:

```java
import java.util.ArrayList;
import java.util.List;

import com.orientechnologies.orient.core.record.impl.ODocument;
import com.tinkerpop.blueprints.Vertex;
import com.tinkerpop.blueprints.impls.orient.OrientGraph;
import com.tinkerpop.blueprints.impls.orient.OrientGraphFactory;
import com.tinkerpop.blueprints.impls.orient.OrientGraphNoTx;

public class OrientBug {
	public static void main(String[] args) {
		OrientGraphFactory factory = new OrientGraphFactory("memory:/tmp/test", "admin", "admin");
		OrientGraphNoTx gn = factory.getNoTx();
		gn.createVertexType("testv");
		gn.shutdown();
		OrientGraph g = factory.getTx();
		try {
			Vertex v = g.addVertex("class:testv");
			v.setProperty("name", "test");
			ODocument d1 = new ODocument();
			d1.field("f", "one");
			ODocument d2 = new ODocument();
			d2.field("f", "two");
			List<ODocument> ds = new ArrayList<>();
			ds.add(d1);
			ds.add(d2);
			v.setProperty("docs", ds);
		}
		finally {
			g.shutdown();
		}
		g = factory.getTx();
		try {
			Iterable<Vertex> vs = g.getVertices();
			Vertex v = vs.iterator().next();
			System.err.println("v: "+v.getProperty("name"));
			// Following line creates error
			Iterable<ODocument> ds = v.getProperty("docs");
			// This line works correctly if you uncomment it
//			List<ODocument> ds = ((OrientVertex)v).getRecord().field("docs");
			for (ODocument d : ds) {
				System.err.println("doc: "+d.field("f"));
			}
		}
		finally {
			g.shutdown();
		}
	}
}

**Comment by fabriziofortino** [comment]
This works if you specify the *docs* property type as EMBEDDEDLIST.

Replace:
```
gn.createVertexType("testv");
```
with:
```
OrientVertexType vertexType = gn.createVertexType("testv");
vertexType.createProperty("docs", OType.EMBEDDEDLIST);
```

**Comment by fabriziofortino** [comment]
@lvca I am on holiday right now. I'll start working on this next Monday.

**Comment by lvca** [comment]
Thanks Fabrizio, I'm checking it now.
