### ISSUE TITLE
Export - Import database fails to import composite Lucene index on 2.0 final

### ISSUE THREAD

**Issue by Maarten88** [orientechnologies/orientdb#3430]
The index is created as:
create index Person.SearchName on Person (FirstName,LastName) FULLTEXT ENGINE LUCENE

I export the database from the portal, then import it from the console on my dev machine (Windows 8.1) and the error below appears. 
```
Index 'Person.SearchName'...Error on database import happened just before line 0, column 68685567
com.orientechnologies.orient.core.index.OIndexException: FULLTEXT indexes cannot be used as composite ones.
        at com.orientechnologies.orient.core.index.OIndexFullText.create(OIndexFullText.java:222)
        at com.orientechnologies.orient.core.index.OIndexFullText.create(OIndexFullText.java:45)
        at com.orientechnologies.orient.core.index.OIndexManagerShared.createIndex(OIndexManagerShared.java:169)
        at com.orientechnologies.orient.core.index.OIndexManagerProxy.createIndex(OIndexManagerProxy.java:79)
        at com.orientechnologies.orient.core.sql.OCommandExecutorSQLCreateIndex.execute(OCommandExecutorSQLCreateIndex.j
ava:259)
        at com.orientechnologies.orient.core.sql.OCommandExecutorSQLDelegate.execute(OCommandExecutorSQLDelegate.java:64
)
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.executeCommand(OAbstractPagina
tedStorage.java:1176)
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.command(OAbstractPaginatedStor
age.java:1165)
        at com.orientechnologies.orient.core.command.OCommandRequestTextAbstract.execute(OCommandRequestTextAbstract.jav
a:63)
        at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.command(ONetworkProtocolBi
nary.java:1180)
        at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.executeRequest(ONetworkPro
tocolBinary.java:385)
        at com.orientechnologies.orient.server.network.protocol.binary.OBinaryNetworkProtocolAbstract.execute(OBinaryNet
workProtocolAbstract.java:216)
        at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:65)
```

**Comment by jingjingbic** [comment]
We are having this issue too in our backup/restore process. We are in the process of upgrade our production db to 2.0. This is a blocking issue for us right now. It will be appreciated if you can fix it soon.

Thanks,
Jing

**Comment by lvca** [comment]
@jingjingbic are you using composite index too?

**Comment by jingjingbic** [comment]
Yes.

**Comment by n0lf** [comment]
any progress on this?

according to the file OIndexFullText.java (https://github.com/orientechnologies/orientdb/blob/master/core/src/main/java/com/orientechnologies/orient/core/index/OIndexFullText.java) there is a strict check for this, which is probably meant for the built in Orientdb fulltext index, not the Lucene index. The only way we've found around this is to rebuild the indexes after import.

**Comment by pzhan** [comment]
Similar problem here: I'm using OrientDB 2.0.8 and during the indexes import, it doesn't try to create a lucene index, but the OrientDB fulltext index. Moreover, since I created an index on an EMBEDDEDLIST by value, it doesn't re-create the index by value. I'm doing the same as n0lf, rebuilding the indexes after import.

**Comment by maggiolo00** [comment]
This should be fixed by 
https://github.com/orientechnologies/orientdb/issues/4473
The problem was that the engine was not used in export/import.
