### ISSUE TITLE
Some wrong query in console produce around 40 million lines of Exception

### ISSUE THREAD

**Issue by adithyank** [orientechnologies/orientdb#3444]
Orient DB Version : 2.0 rc1

Our application connects to DB in plocal mode and starts embedded server inside for console query access. When I gave some wrong query in the console. Some big paragraph I pasted wrongly as below

```
select * from CRPoint where key = '<some big paragraph here.......
```

Suddenly, the below Exception started printing in nohup and it is printed and it keeps printing even after I killed that console session. The no of lines in nohup is more than 40 million and this Exception is kept on printed

```
com.orientechnologies.orient.core.exception.ODatabaseException: Database 'plocal:orientdatabases/rcainv' is closed
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.checkOpeness(ODatabaseDocumentTx.java:2583)
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.executeReadRecord(ODatabaseDocumentTx.java:1523)
        at com.orientechnologies.orient.core.tx.OTransactionNoTx.loadRecord(OTransactionNoTx.java:80)
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.load(ODatabaseDocumentTx.java:1433)
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.load(ODatabaseDocumentTx.java:117)
        at com.orientechnologies.orient.core.iterator.OIdentifiableIterator.readCurrentRecord(OIdentifiableIterator.java:278)
        at com.orientechnologies.orient.core.iterator.ORecordIteratorClusters.hasNext(ORecordIteratorClusters.java:147)
        at com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.fetchFromTarget(OCommandExecutorSQLSelect.java:1268)
        at com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.executeSearch(OCommandExecutorSQLSelect.java:430)
        at com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.execute(OCommandExecutorSQLSelect.java:388)
        at com.orientechnologies.orient.core.sql.OCommandExecutorSQLDelegate.execute(OCommandExecutorSQLDelegate.java:64)
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.executeCommand(OAbstractPaginatedStorage.java:1163)
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.command(OAbstractPaginatedStorage.java:1152)
        at com.orientechnologies.orient.core.sql.query.OSQLQuery.run(OSQLQuery.java:71)
        at com.orientechnologies.orient.core.sql.query.OSQLSynchQuery.run(OSQLSynchQuery.java:85)
        at com.orientechnologies.orient.core.query.OQueryAbstract.execute(OQueryAbstract.java:33)
        at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.command(ONetworkProtocolBinary.java:1179)
        at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.executeRequest(ONetworkProtocolBinary.java:385)
        at com.orientechnologies.orient.server.network.protocol.binary.OBinaryNetworkProtocolAbstract.execute(OBinaryNetworkProtocolAbstract.java:216)
        at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:65)
```

Something to be done to arrest this issue pls...

**Comment by lvca** [comment]
@tglman do we call Thread.interrupt() in case of socket exception in the server?

**Comment by tglman** [comment]
hi @adithyank 

Can you send a test case, that will help a lot to identify the problems, that in this case seems two, one on the query handling, another on error management. it may be enough a full query with the big paragraph there.

**Comment by adithyank** [comment]
The below is the query that produced that much logs in nohup.

```
select * from CRPoint where key = '| evidence of such monitoring to law enforcement officials.       |
Last login: Fri Jan 23 12:01:51 2015 from tctsl-sgh74106.vsnl.co.in
| This system is for the use of authorized users only.            |
| Individuals using this computer system without authority, or in |
| excess of their authority, are subject to having all of their   |
| activities on this system monitored and recorded by system      |
| personnel.                                                      |
| In the course of monitoring individuals improperly using this   |
| system, or in the course of system maintenance, the activities  |
| of authorized users may also be monitored.                      |
|                                                                 |
| Anyone using this system expressly consents to such monitoring  |
| and is advised that if such monitoring reveals possible         |
| evidence of criminal activity, system personnel may provide the |
| evidence of such monitoring to law enforcement officials.       |
|-----------------------------------------------------------------|
```

But, I tried the same thing now in idle state. i.e., no orientdb reads/writes are happening now. It did not happen this time

Some more inputs

1. When it produced lot of lines, our database building activity was running. i.e., come commits would have been in progress
2. I pasted this query in console in one of the terminals of MobaXTerm software
3. Our application server was running RHEL 6.4 remote machine with orientdb in plocal mode

**Comment by tglman** [comment]
Hi @adithyank 
Sorry for this late response, i tryed to run the query that you posted, with no result, is probable that the issue depends on how meny record you had and if there was an index on that field, it could be have just triggered the error because the database was overloaded,  anyway we have a better management of connection in 2.0 compared to RC1 so this should not happen now.

**Comment by adithyank** [comment]
@tglman Ok. You can close this issue now. If it occurs again, I will reopen...

Thanks

**Comment by adithyank** [comment]
I have found way to reproduce this. Pls see the below console output. 

1. Just connect to any database.
2. Type any select query
3. press Enter button
4. Immediately pressing the enter button 'press `CTRL-C` quickly
5. Now this console session closes
6. see the server logs.... lot of logs got printed....

Someone, pls reopen this issue

```
orientdb {server=remote:localhost/}> connect remote:localhost/GratefulDeadConcerts root root

Disconnecting from remote server [remote:localhost/]...
OK
Connecting to database [remote:localhost/GratefulDeadConcerts] with user 'root'...OK
orientdb {db=GratefulDeadConcerts}> classes;


CLASSES
----------------------------------------------+------------------------------------+------------+----------------+
 NAME                                         | SUPERCLASS                         | CLUSTERS   | RECORDS        |
----------------------------------------------+------------------------------------+------------+----------------+
 _studio                                      |                                    | 14         |              1 |
 E                                            |                                    | 10         |              1 |
 followed_by                                  | E                                  | 11         |           7047 |
 OFunction                                    |                                    | 6          |              1 |
 OIdentity                                    |                                    | -          |              0 |
 ORestricted                                  |                                    | -          |              0 |
 ORIDs                                        |                                    | 8          |              0 |
 ORole                                        | OIdentity                          | 4          |              3 |
 OSchedule                                    |                                    | 7          |              0 |
 OTriggered                                   |                                    | -          |              0 |
 OUser                                        | OIdentity                          | 5          |              3 |
 sung_by                                      | E                                  | 13         |            501 |
 V                                            |                                    | 9          |            809 |
 written_by                                   | E                                  | 12         |            501 |
----------------------------------------------+------------------------------------+------------+----------------+
 TOTAL = 14                                                                                                 8867 |
----------------------------------------------+------------------------------------+------------+----------------+
orientdb {db=GratefulDeadConcerts}> select from followed_by;
[root@adithyan /mnt/data/adi/installation-files/common/graphdb/orientdb/orient-2.0.2/orientdb-community-2.0.2/bin]# 
````

**Comment by tglman** [comment]
fixed closing
