### ISSUE TITLE
 Cannot create the index

### ISSUE THREAD

**Issue by PavelNiedoba** [orientechnologies/orientdb#3446]
Using 2.0

I'm creating new DB with indexes on application startup.
12 of 19 indexes gets create successfully. Then I get exception
com.orientechnologies.orient.core.index.OIndexException: Cannot create the index 'Exchange.order'
at com.orientechnologies.orient.core.index.OIndexAbstract.create(OIndexAbstract.java:240)
at com.orientechnologies.orient.core.index.OIndexOneValue.create(OIndexOneValue.java:108)
at com.orientechnologies.orient.core.index.OIndexOneValue.create(OIndexOneValue.java:45)
at com.orientechnologies.orient.core.index.OIndexManagerShared.createIndex(OIndexManagerShared.java:169)
at com.orientechnologies.orient.core.index.OIndexManagerProxy.createIndex(OIndexManagerProxy.java:79)
at com.orientechnologies.orient.core.metadata.schema.OClassImpl.createIndex(OClassImpl.java:1434)
at com.orientechnologies.orient.core.sql.OCommandExecutorSQLCreateIndex.execute(OCommandExecutorSQLCreateIndex.java:252)
at com.orientechnologies.orient.core.sql.OCommandExecutorSQLDelegate.execute(OCommandExecutorSQLDelegate.java:64)
at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.executeCommand(OAbstractPaginatedStorage.java:1176)
at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.command(OAbstractPaginatedStorage.java:1165)
at com.orientechnologies.orient.core.command.OCommandRequestTextAbstract.execute(OCommandRequestTextAbstract.java:63)
at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.command(ONetworkProtocolBinary.java:1180)
at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.executeRequest(ONetworkProtocolBinary.java:385)
at com.orientechnologies.orient.server.network.protocol.binary.OBinaryNetworkProtocolAbstract.execute(OBinaryNetworkProtocolAbstract.java:216)
at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:65)

Same happens in studio. The command is

create index Exchange.order on Exchange (order) UNIQUE_HASH_INDEX
and it worked fine with 1.7.*

Maybe the problem is that schema was not created correctly. When I look at it in studio->schema I dont see Type and LinkedClass set on order property

When I try to set it manually
I get
java.lang.IllegalArgumentException: Cannot change property type from CUSTOM to LINK [ONetworkProtocolHttpDb]
2015-01-23 11:02:06:201 SEVERE Internal server error:
com.orientechnologies.orient.core.exception.OSchemaException: Linked class is not supported for type: CUSTOM [ONetworkProtocolHttpDb]

btw. how can I print schema for given class (so I can paste it here?)

I managed to export whole schema. Exchange object looks like this:

{
"name": "Exchange",
"default-cluster-id": 20,
"cluster-ids": [20],
"super-class": "ObservablePojoWithId",
"cluster-selection": "round-robin",
"properties": [
{
"name": "addressTransaction",
"type": "CUSTOM",
"collate": "default"
},
{
"name": "bankTransaction",
"type": "CUSTOM",
"collate": "default"
},
{
"name": "customer",
"type": "CUSTOM",
"collate": "default"
},
{
"name": "order",
"type": "CUSTOM",
"collate": "default"
},
{
"name": "warnings",
"type": "EMBEDDEDLIST",
"linked-type": "STRING",
"collate": "default"
}
]
},

"type": "CUSTOM" is likely the problem

Which brings question: When I do:

db.getEntityManager().registerEntityClasses("first");
db.getEntityManager().registerEntityClasses("second");

Can objects from first have links to second ?

**Comment by luigidellaquila** [comment]
Hi @PavelNiedoba 

I'm afraid you are right, it seems that the schema was not created correctly.
Could you try to drop and re-create the properties (http://orientdb.com/docs/last/SQL-Drop-Property.html) ? It will not affect your data.

Luigi

**Comment by laa** [comment]
Closed because of no reply.
