### ISSUE TITLE
NPE from OObjectProxyMethodHandler

### ISSUE THREAD

**Issue by PavelNiedoba** [orientechnologies/orientdb#3447]
getting db this way: (remote:/bbb)
OObjectDatabaseTx db;
db.setAutomaticSchemaGeneration(true);
db.getEntityManager().registerEntityClasses("mypkg.persisted*");

when I run query:
select from User where loginName='root'
I get User object correctly returned
but user.getPassword() fails with:

java.lang.NullPointerException at com.orientechnologies.orient.object.enhancement.OObjectProxyMethodHandler.getDocFieldValue(OObjectProxyMethodHandler.java:362)
at com.orientechnologies.orient.object.enhancement.OObjectProxyMethodHandler.getValue(OObjectProxyMethodHandler.java:351)
at com.orientechnologies.orient.object.enhancement.OObjectProxyMethodHandler.getValue(OObjectProxyMethodHandler.java:288)
at com.orientechnologies.orient.object.enhancement.OObjectProxyMethodHandler.manageGetMethod(OObjectProxyMethodHandler.java:277)
at com.orientechnologies.orient.object.enhancement.OObjectProxyMethodHandler.invoke(OObjectProxyMethodHandler.java:103)
at ....persisted.User_$$javassist_0.getPassword(User$$_javassist_0.java)

I tried corresponding query in studio
select password from User where loginName='root'

and it works as expected

exactly same code worked with 1.7.9 and 1.7.10
User is simple class with primitives only and has no links

**Comment by tglman** [comment]
this is a really old issue, it should not happen anymore, closing, reopen if you are able to reproduce.
