### ISSUE TITLE
Can not create class in distributed mode

### ISSUE THREAD

**Issue by nin-jin** [orientechnologies/orientdb#3461]
I have two instances of OrientDB 2.0 in separate docker containers

My app executes on start:

create class xxx-model extends V
create class xxx-person extends xxx-model
create class xxx-assessment extends xxx-model

then in db2 logs i found:

2015-01-25T22:03:24.332114254Z 2015-01-25 22:03:24:331 INFO  [beta] installed database 'xxx' [OHazelcastPlugin]
2015-01-25T22:03:24.503537394Z 2015-01-25 22:03:24:332 WARNING [beta] found 1 messages in queue orientdb.node.beta.xxx.request, aligning the database... [OHazelcastDistributedMessageService]
2015-01-25T22:03:25.726411103Z 2015-01-25 22:03:24:503 INFO  {db=skeddy} [beta] Installing distributed storage on database 'xxx' [ODistributedStorage]
2015-01-25T22:03:29.762663964Z 2015-01-25 22:03:25:726 INFO  [beta] class 'E', creation of new local cluster 'e_beta' (id=-1) [OHazelcastPlugin]
2015-01-25T22:03:29.763047720Z 2015-01-25 22:03:29:762 SEVERE [beta] error on creating cluster 'e_beta' in class 'E' [OHazelcastPlugin][172.17.0.49]:2434 [orientdb] [3.3] hz._hzInstance_1_orientdb.event-2 caught an exception while processing task:com.hazelcast.spi.impl.EventServiceImpl$LocalEventDispatcher@6c178eb9
2015-01-25T22:03:29.763068229Z com.orientechnologies.orient.server.distributed.ODistributedException: com.orientechnologies.orient.server.distributed.ODistributedException: Error on creating cluster 'e_beta' in class 'E'
2015-01-25T22:03:29.763068229Z  at com.orientechnologies.orient.server.hazelcast.OHazelcastDistributedDatabase.configureDatabase(OHazelcastDistributedDatabase.java:215)
2015-01-25T22:03:29.763068229Z  at com.orientechnologies.orient.server.hazelcast.OHazelcastPlugin.installDatabase(OHazelcastPlugin.java:924)
2015-01-25T22:03:29.763068229Z  at com.orientechnologies.orient.server.hazelcast.OHazelcastPlugin.installNewDatabases(OHazelcastPlugin.java:1099)
2015-01-25T22:03:29.763081740Z  at com.orientechnologies.orient.server.hazelcast.OHazelcastPlugin.entryAdded(OHazelcastPlugin.java:602)
2015-01-25T22:03:29.763081740Z  at com.hazelcast.map.MapEventPublishingService.dispatch0(MapEventPublishingService.java:85)
2015-01-25T22:03:29.763081740Z  at com.hazelcast.map.MapEventPublishingService.dispatchEntryEventData(MapEventPublishingService.java:64)
2015-01-25T22:03:29.763081740Z  at com.hazelcast.map.MapEventPublishingService.dispatchEvent(MapEventPublishingService.java:39)
2015-01-25T22:03:29.763081740Z  at com.hazelcast.map.MapEventPublishingService.dispatchEvent(MapEventPublishingService.java:17)
2015-01-25T22:03:29.763096298Z  at com.hazelcast.map.MapService.dispatchEvent(MapService.java:76)
2015-01-25T22:03:29.763096298Z  at com.hazelcast.map.MapService.dispatchEvent(MapService.java:51)
2015-01-25T22:03:29.763096298Z  at com.hazelcast.spi.impl.EventServiceImpl$LocalEventDispatcher.run(EventServiceImpl.java:658)
2015-01-25T22:03:29.763096298Z  at com.hazelcast.util.executor.StripedExecutor$Worker.process(StripedExecutor.java:189)
2015-01-25T22:03:29.763096298Z  at com.hazelcast.util.executor.StripedExecutor$Worker.run(StripedExecutor.java:173)
2015-01-25T22:03:29.763113432Z Caused by: com.orientechnologies.orient.server.distributed.ODistributedException: Error on creating cluster 'e_beta' in class 'E'
2015-01-25T22:03:29.763113432Z  at com.orientechnologies.orient.server.hazelcast.OHazelcastPlugin.installLocalClusterPerClass(OHazelcastPlugin.java:1244)
2015-01-25T22:03:29.763113432Z  at com.orientechnologies.orient.server.hazelcast.OHazelcastPlugin.installDbClustersForLocalNode(OHazelcastPlugin.java:960)
2015-01-25T22:03:29.763113432Z  at com.orientechnologies.orient.server.hazelcast.OHazelcastPlugin$1.call(OHazelcastPlugin.java:927)
2015-01-25T22:03:29.763113432Z  at com.orientechnologies.orient.server.hazelcast.OHazelcastPlugin$1.call(OHazelcastPlugin.java:924)
2015-01-25T22:03:29.763113432Z  at com.orientechnologies.orient.server.hazelcast.OHazelcastDistributedDatabase.configureDatabase(OHazelcastDistributedDatabase.java:213)
2015-01-25T22:03:29.763142531Z  ... 12 more

**Comment by lvca** [comment]
I saw this:

    2015-01-25T22:03:24.503537394Z 2015-01-25 22:03:24:332 WARNING [beta] found 1 messages in queue orientdb.node.beta.xxx.request, aligning the database... [OHazelcastDistributedMessageService]

So did you restarted the node? Also, can you provide the distributed-config.json file?

**Comment by nin-jin** [comment]
Of course.

{
   "version": 0,
   "autoDeploy": true,
   "hotAlignment": true,
   "executionMode": "undefined",
   "readQuorum": 1,
   "writeQuorum": 2,
   "failureAvailableNodesLessQuorum": false,
   "readYourWrites": true,"clusters":{
     "internal": {
 },
     "index": {
 },
     "*": {
   "servers": ["alpha","beta","<NEW_NODE>"]
 }
     }
 }

**Comment by lvca** [comment]
We reported some problem with:

    "hotAlignment": true,

Please could you retry with `"hotAlignment": false`?

**Comment by nin-jin** [comment]
Same problem

2015-01-26 07:29:39:321 INFO  [beta] class 'V', creation of new local cluster 'v_beta' (id=-1) [OHazelcastPlugin]
2015-01-26 07:29:43:314 SEVERE [beta] error on creating cluster 'v_beta' in class 'V' [OHazelcastPlugin][172.17.0.83]:2434 [orientdb] [3.3] hz._hzInstance_1_orientdb.event-2 caught an exception while processing task:com.hazelcast.spi.impl.EventServiceImpl$LocalEventDispatcher@1b3821a6
com.orientechnologies.orient.server.distributed.ODistributedException: com.orientechnologies.orient.server.distributed.ODistributedException: Error on creating cluster 'v_beta' in class 'V'

**Comment by nin-jin** [comment]
I uses nodejs "oriento" module and see this warning in app after startup:

unsupported pushed data format: 8localName:"_hzInstance_1_orientdb",localId:"2766e5b4-8de8-41d8-a413-824989d5c270",members:[(id:"2be51bf6-45de-43d7-8374-c81b3aa558f8",name:"beta",startedOn:1422257341478t,listeners:[{"protocol":"ONetworkProtocolBinary","listen":"172.17.0.83:2424"},{"protocol":"ONetworkProtocolHttpDb","listen":"172.17.0.83:2480"}],databases:<>),(id:"2766e5b4-8de8-41d8-a413-824989d5c270",name:"alpha",startedOn:1422257340926t,listeners:[{"protocol":"ONetworkProtocolBinary","listen":"172.17.0.82:2424"},{"protocol":"ONetworkProtocolHttpDb","listen":"172.17.0.82:2480"}],databases:<>)]

**Comment by lvca** [comment]
Fixed months ago.
