### ISSUE TITLE
After closing db, exception Class User already exists in current database

### ISSUE THREAD

**Issue by vitorenesduarte** [orientechnologies/orientdb#3471]
```java
      ODatabaseDocument db = new ODatabaseDocumentTx("remote:localhost/Run");
      try {
         db.open("admin", "admin");
         ODocument d = new ODocument("User");
         d.save();
      } finally {
         db.close();
      }

      try {
         db.open("admin", "admin");
         ODocument d = new ODocument("User");
         d.save();
      } finally {
         db.close();
      }
```

```bash
Exception in thread "main" com.orientechnologies.orient.core.exception.OSchemaException: Class User already exists in current database
	at com.orientechnologies.orient.core.metadata.schema.OSchemaShared.doCreateClass(OSchemaShared.java:905)
	at com.orientechnologies.orient.core.metadata.schema.OSchemaShared.createClass(OSchemaShared.java:362)
	at com.orientechnologies.orient.core.metadata.schema.OSchemaProxy.createClass(OSchemaProxy.java:111)
	at com.orientechnologies.orient.core.sql.OCommandExecutorSQLCreateClass.execute(OCommandExecutorSQLCreateClass.java:144)
	at com.orientechnologies.orient.core.sql.OCommandExecutorSQLDelegate.execute(OCommandExecutorSQLDelegate.java:64)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.executeCommand(OAbstractPaginatedStorage.java:1176)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.command(OAbstractPaginatedStorage.java:1165)
	at com.orientechnologies.orient.core.command.OCommandRequestTextAbstract.execute(OCommandRequestTextAbstract.java:63)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.command(ONetworkProtocolBinary.java:1180)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.executeRequest(ONetworkProtocolBinary.java:385)
	at com.orientechnologies.orient.server.network.protocol.binary.OBinaryNetworkProtocolAbstract.execute(OBinaryNetworkProtocolAbstract.java:216)
	at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:65)
```

The first record is saved in the db, the second throws this exception. Don't know if it is an issue or if I did something wrong.

**Comment by vitorenesduarte** [comment]
This goes without any problem.
```java
      ODatabaseDocument db = new ODatabaseDocumentTx("remote:localhost/Run");
      try {
         db.open("admin", "admin");
         ODocument d = new ODocument("User");
         d.save();
      } finally {
         db.close();
      }

      ODatabaseDocument db2 = new ODatabaseDocumentTx("remote:localhost/Run");
      try {
         db2.open("admin", "admin");
         ODocument d = new ODocument("User");
         d.save();
      } finally {
         db2.close();
      }
```

**Comment by laa** [comment]
Looks  like a bug. @tglman could you look on it ?

**Comment by lvca** [comment]
Seems the schema is not update.

**Comment by tglman** [comment]
@vitorenesduarte usueally you should create the class before use it, anyway we support also this, so i fixed it.
