### ISSUE TITLE
OrientDB 2.0: A record isn't created on 3-node cluster

### ISSUE THREAD

**Issue by srgg** [orientechnologies/orientdb#3479]
Regardless how schema is created (on 1 running node or in offline mode), it's impossible to insert a record in 3-node cluster. "Quorum 2 not reached" exception is thrown.
For example, during Artist creation the following error appeared:
```
    "Quorum 2 not reached for request (id=190 from=node54 task=tx userName=admin). Timeout=21ms Servers in timeout/conflict are:"
```

In the logs of first node there was the following:

```
    2015-01-22 12:57:30:665 WARNING [node54] detected 2 node(s) in timeout or in conflict and quorum (2) has not been reached, rolling back changes for request (id=188 from=node54 task=tx userName=admin) [ODistributedResponseManager]
    2015-01-22 12:57:30:665 WARNING [node54] Quorum 2 not reached for request (id=188 from=node54 task=tx userName=admin). Timeout=30ms Servers in timeout/conflict are:
     - node54: [#12:0 v.1]
     - node72: [#50:0 v.1]
    Received: {node54=[#12:0 v.1], node58=[#41:0 v.1], node72=[#50:0 v.1]} [ODistributedResponseManager]
    2015-01-22 12:57:30:665 WARNING [node54] sending undo message for request (id=188 from=node54 task=tx userName=admin) to server node54 [ODistributedResponseManager]
    2015-01-22 12:57:30:677 WARNING [node54] sending undo message for request (id=188 from=node54 task=tx userName=admin) to server node58 [ODistributedResponseManager]
    2015-01-22 12:57:30:685 WARNING [node54] sending undo message for request (id=188 from=node54 task=tx userName=admin) to server node72 [ODistributedResponseManager]Cannot route TX operation against distributed node
    com.orientechnologies.orient.server.distributed.ODistributedException: Error on executing distributed request (id=188 from=node54 task=tx userName=admin) against database 'ipaas_ivelichko_albums.[default]' to nodes [node58, node54, node72]
        at com.orientechnologies.orient.server.hazelcast.OHazelcastDistributedDatabase.send2Nodes(OHazelcastDistributedDatabase.java:194)
        at com.orientechnologies.orient.server.hazelcast.OHazelcastPlugin.sendRequest(OHazelcastPlugin.java:348)
        at com.orientechnologies.orient.server.distributed.ODistributedStorage.commit(ODistributedStorage.java:841)
        at com.orientechnologies.orient.core.tx.OTransactionOptimistic.doCommit(OTransactionOptimistic.java:483)
        at com.orientechnologies.orient.core.tx.OTransactionOptimistic.commit(OTransactionOptimistic.java:147)
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.commit(ODatabaseDocumentTx.java:2370)
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.commit(ODatabaseDocumentTx.java:2340)
        at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.commit(ONetworkProtocolBinary.java:1087)
        at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.executeRequest(ONetworkProtocolBinary.java:389)
        at com.orientechnologies.orient.server.network.protocol.binary.OBinaryNetworkProtocolAbstract.execute(OBinaryNetworkProtocolAbstract.java:216)
        at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:65)
    Caused by: com.orientechnologies.orient.server.distributed.ODistributedException: Quorum 2 not reached for request (id=188 from=node54 task=tx userName=admin). Timeout=30ms Servers in timeout/conflict are:
     - node54: [#12:0 v.1]
     - node72: [#50:0 v.1]
    Received: {node54=[#12:0 v.1], node58=[#41:0 v.1], node72=[#50:0 v.1]}
        at com.orientechnologies.orient.server.distributed.ODistributedResponseManager.manageConflicts(ODistributedResponseManager.java:576)
        at com.orientechnologies.orient.server.distributed.ODistributedResponseManager.getFinalResponse(ODistributedResponseManager.java:340)
        at com.orientechnologies.orient.server.hazelcast.OHazelcastDistributedDatabase.waitForResponse(OHazelcastDistributedDatabase.java:364)
        at com.orientechnologies.orient.server.hazelcast.OHazelcastDistributedDatabase.send2Nodes(OHazelcastDistributedDatabase.java:191)
        ... 10 more
    Sent run-time exception to the client /10.0.1.62:33330: com.orientechnologies.orient.server.distributed.ODistributedException: Quorum 2 not reached for request (id=188 from=node54 task=tx userName=admin). Timeout=30ms Servers in timeout/conflict are:
     - node54: [#12:0 v.1]
     - node72: [#50:0 v.1]
    Received: {node54=[#12:0 v.1], node58=[#41:0 v.1], node72=[#50:0 v.1]}
    com.orientechnologies.orient.server.distributed.ODistributedException: Quorum 2 not reached for request (id=188 from=node54 task=tx userName=admin). Timeout=30ms Servers in timeout/conflict are:
     - node54: [#12:0 v.1]
     - node72: [#50:0 v.1]
    Received: {node54=[#12:0 v.1], node58=[#41:0 v.1], node72=[#50:0 v.1]}
        at com.orientechnologies.orient.server.distributed.ODistributedResponseManager.manageConflicts(ODistributedResponseManager.java:576)
        at com.orientechnologies.orient.server.distributed.ODistributedResponseManager.getFinalResponse(ODistributedResponseManager.java:340)
        at com.orientechnologies.orient.server.hazelcast.OHazelcastDistributedDatabase.waitForResponse(OHazelcastDistributedDatabase.java:364)
        at com.orientechnologies.orient.server.hazelcast.OHazelcastDistributedDatabase.send2Nodes(OHazelcastDistributedDatabase.java:191)
        at com.orientechnologies.orient.server.hazelcast.OHazelcastPlugin.sendRequest(OHazelcastPlugin.java:348)
        at com.orientechnologies.orient.server.distributed.ODistributedStorage.commit(ODistributedStorage.java:841)
        at com.orientechnologies.orient.core.tx.OTransactionOptimistic.doCommit(OTransactionOptimistic.java:483)
        at com.orientechnologies.orient.core.tx.OTransactionOptimistic.commit(OTransactionOptimistic.java:147)
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.commit(ODatabaseDocumentTx.java:2370)
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.commit(ODatabaseDocumentTx.java:2340)
        at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.commit(ONetworkProtocolBinary.java:1087)
        at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.executeRequest(ONetworkProtocolBinary.java:389)
        at com.orientechnologies.orient.server.network.protocol.binary.OBinaryNetworkProtocolAbstract.execute(OBinaryNetworkProtocolAbstract.java:216)
        at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:
```

**Comment by lvca** [comment]
Fixed in 2.0.2-SNAPSHOT and 2.1-SNAPSHOT.
