### ISSUE TITLE
'Index with name XX already exists' after OIndex.delete() call

### ISSUE THREAD

**Issue by adithyank** [orientechnologies/orientdb#3485]
I have written a method like this to handle some cases of index corruptions.

i.e., if a particular class has records and the index size is 0, then i m deleting the index and recreating it. This happens when our application starts.

``` java
private static OIndex createIndexIfNeeded(ODatabaseDocumentTx database, String dataTypeName, OClass oclass, Index indexConfig)
	{
		OIndexManagerProxy im = database.getMetadata().getIndexManager();
		String indexName = indexName(dataTypeName, indexConfig.getKeyField());
		
		boolean exists = im.existsIndex(indexName);
		
		if (!exists)
		{
			oclass.createIndex(indexName, getIndexType(indexConfig), indexConfig.getKeyField());
		}
		else
		{
			long classRecCount = oclass.count();

			if (classRecCount > 0)
			{
				OIndex<?> index = im.getIndex(indexName);
				long size = index.getSize();
				if (size == 0)
				{
					logger.info("Index size = 0 for index [{}]. Class Record Count = {}. Hence Dropping and recreating index...", index.getName(), oclass.count());
					index.delete();
					/*line no : 333*/ oclass.createIndex(indexName, getIndexType(indexConfig), indexConfig.getKeyField());
				}
			}
		}

		OIndex<?> index = im.getIndex(indexName);
		String msg = exists ? "Index already exists" : "Index newly created";
		logger.info("{}, index size = {}, index = {}", msg, index.getSize(), index.getConfiguration().toJSON());
		return index;
	}
```

But, this thrrows the below exception...

```
com.orientechnologies.orient.core.index.OIndexException: Index with name por_point.hopointuk already exists.
        at com.orientechnologies.orient.core.index.OIndexManagerShared.createIndex(OIndexManagerShared.java:133) ~[orientdb-core-2.0-rc1.jar:2.0-rc1]
        at com.orientechnologies.orient.core.index.OIndexManagerProxy.createIndex(OIndexManagerProxy.java:79) ~[orientdb-core-2.0-rc1.jar:2.0-rc1]
        at com.orientechnologies.orient.core.metadata.schema.OClassImpl.createIndex(OClassImpl.java:1432) ~[orientdb-core-2.0-rc1.jar:2.0-rc1]
        at com.orientechnologies.orient.core.metadata.schema.OClassImpl.createIndex(OClassImpl.java:1397) ~[orientdb-core-2.0-rc1.jar:2.0-rc1]
        at com.orientechnologies.orient.core.metadata.schema.OClassImpl.createIndex(OClassImpl.java:1387) ~[orientdb-core-2.0-rc1.jar:2.0-rc1]
        at com.orientechnologies.orient.core.metadata.schema.OClassImpl.createIndex(OClassImpl.java:1383) ~[orientdb-core-2.0-rc1.jar:2.0-rc1]
        at in.co.nmsworks.documenttdb.spi.impl.orient.OrientInternal.createIndexIfNeeded(OrientInternal.java:333) ~[cygnetOTNMS.jar:?]
        at in.co.nmsworks.documenttdb.spi.impl.orient.OrientInternal.prepareDocumentDataType(OrientInternal.java:247) ~[cygnetOTNMS.jar:?]
        at in.co.nmsworks.documenttdb.spi.impl.orient.OrientInternal.prepareSchema(OrientInternal.java:228) ~[cygnetOTNMS.jar:?]
        at in.co.nmsworks.documenttdb.spi.impl.orient.OrientInternal.ensureDatabaseAvailability(OrientInternal.java:202) [cygnetOTNMS.jar:?]
        at in.co.nmsworks.documenttdb.spi.impl.orient.OrientInternal.initialize(OrientInternal.java:73) [cygnetOTNMS.jar:?]
        at in.co.nmsworks.documenttdb.NoSqlService.init(NoSqlService.java:19) [cygnetOTNMS.jar:?]
        at in.co.nmsworks.nms.system.ServicesHelper.initNoSqlDatabaseService(ServicesHelper.java:104) [cygnetOTNMS.jar:?]
        at in.co.nmsworks.nms.system.Controller.start(Controller.java:216) [cygnetOTNMS.jar:?]
        at in.co.nmsworks.nms.system.Controller.main(Controller.java:427) [cygnetOTNMS.jar:?]
```

I am calling `oclass.createIndex` only after OIndex.delete() call. 
Am I doing something wrong or is it a real issue?

**Comment by adithyank** [comment]
Used OrientDB version : 2.0 rc1

**Comment by adithyank** [comment]
Attaching a main class that demonstrates this issue. 

Code link : https://gist.github.com/adithyank/7494a2a6ed3f0bb01ca8

When I run this class below is the output...

```
creating....
created class = docnode
existsIndex before creation = false
index created
index = {"@type":"d","@version":0,"type":"UNIQUE_HASH_INDEX","name":"docnode.name","indexDefinition":{"@type":"d","@version":0,"className":"docnode","field":"name","keyType":"STRING","collate":"default","nullValuesIgnored":true},"indexDefinitionClass":"com.orientechnologies.orient.core.index.OPropertyIndexDefinition","clusters":["docnode"],"mapRid":"#1:2","algorithm":"SBTREE","valueContainerAlgorithm":"NONE","@fieldTypes":"clusters=e,mapRid=x"}
------------------------------
index deleted
------------------------------
existsIndex after deleting index = true
------------------------------
class exists
existsIndex before creation = true
```

This output shows that the existsIndex() method returns true after deleting the index...

The behavior is same for `OClass.INDEX_TYPE.UNIQUE_HASH_INDEX` and `OClass.INDEX_TYPE.NOTUNIQUE_HASH_INDEX`

**Comment by adithyank** [comment]
Sorry. Wrong clicked the close button. Reopening now...

**Comment by laa** [comment]
This client needs to use 2.1 version so I move issue there

**Comment by laa** [comment]
That is not a but, you can not call directly com.orientechnologies.orient.core.index.OIndex#delete method. You should use com.orientechnologies.orient.core.index.OIndexManagerProxy#dropIndex instead. I marked one as internal and second one as user api
