### ISSUE TITLE
Inconsistent server reads when client issues REQUEST_DB_EXIST using binary protocol

### ISSUE THREAD

**Issue by quux00** [orientechnologies/orientdb#3486]
I am just starting to write a Go (golang) client for OrientDB and I found a problem in the `REQUEST_DB_EXIST` request using the binary network protocol.

I issue a `REQUEST_DB_EXIST` request, sending all the correct fields: 

```
(command:byte)(sessionId:int)(database-name:string)(server-storage-type:string)
```

If I do this after calling `REQUEST_CONNECT` and getting a proper `sessionId` established it works fine.  With packet tracing output on the server I see the expected output:

```
Reading byte (1 byte)... [OChannelBinaryServer]
Read byte: 6 [OChannelBinaryServer]
Reading int (4 bytes)... [OChannelBinaryServer]
Read int: 163 [OChannelBinaryServer]
Reading string (4+N bytes)... [OChannelBinaryServer]
Read string: cars [OChannelBinaryServer]    <-- dbname
Reading string (4+N bytes)... [OChannelBinaryServer]
Read string: plocal [OChannelBinaryServer]   <-- storageType
Writing byte (1 byte): 0 [OChannelBinaryServer]
Writing int (4 bytes): 163 [OChannelBinaryServer]
Writing byte (1 byte): 1 [OChannelBinaryServer]
Flush [OChannelBinaryServer]
```

However if I improperly call `REQUEST_DB_EXIST` without calling `REQUEST_CONNECT` first (thus sending a negative number for the `sessionId`), the server does **not** try to read the last field - `storage-type`.  Instead it stops after reading the dbname and sends back the (expected) "user not authenticated" error.

```
Reading byte (1 byte)... [OChannelBinaryServer]
Read byte: 6 [OChannelBinaryServer]
Reading int (4 bytes)... [OChannelBinaryServer]
Read int: -1 [OChannelBinaryServer]     <-- invalid session-id
Reading string (4+N bytes)... [OChannelBinaryServer]
Read string: cars [OChannelBinaryServer]   <-- dbname is read, but not storage type
Writing byte (1 byte): 1 [OChannelBinaryServer]
Writing int (4 bytes): -1 [OChannelBinaryServer]
Writing byte (1 byte): 1 [OChannelBinaryServer]
Writing string (4+68=72 bytes): com.orientechnologies.orient.core.exception.OSecurityAccessException [OChannelBinaryServer]
Writing string (4+30=34 bytes): Server user not authenticated. [OChannelBinaryServer]
Writing byte (1 byte): 0 [OChannelBinaryServer]
Flush [OChannelBinaryServer]Sent run-time exception to the client /127.0.0.1:40817: com.orientechnologies.orient.core.exception.OSecurityAccessException: Server user not authenticated.
com.orientechnologies.orient.core.exception.OSecurityAccessException: Server user not authenticated.
    at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.checkServerAccess(ONetworkProtocolBinary.java:464)
    at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.existsDatabase(ONetworkProtocolBinary.java:939)
    at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.executeRequest(ONetworkProtocolBinary.java:298)
    at com.orientechnologies.orient.server.network.protocol.binary.OBinaryNetworkProtocolAbstract.execute(OBinaryNetworkProtocolAbstract.java:216)
    at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:65)
```

While my client accurately reads back the exception info, the problem is that when I send another command to the server, there is still the `storage-type` sitting unread in its TCP session buffer, so it then reads that first when I send another command and gets errors (NPE) and closes the connection:

```
Reading byte (1 byte)... [OChannelBinaryServer]
Read byte: 0 [OChannelBinaryServer]     <-- this is the first byte of the storage-type, not the command I just sent
Reading int (4 bytes)... [OChannelBinaryServer]
Read int: 1648 [OChannelBinaryServer]
Closing socket... [OChannelBinaryServer]Error during sending an error to client
java.lang.NullPointerException
    at com.orientechnologies.orient.enterprise.channel.binary.OChannelBinary.writeByte(OChannelBinary.java:247)
    at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.sendError(ONetworkProtocolBinary.java:717)
    at com.orientechnologies.orient.server.network.protocol.binary.OBinaryNetworkProtocolAbstract.sendErrorOrDropConnection(OBinaryNetworkProtocolAbstract.java:254)
    at com.orientechnologies.orient.server.network.protocol.binary.OBinaryNetworkProtocolAbstract.execute(OBinaryNetworkProtocolAbstract.java:231)
    at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:65)
Exception in thread "OrientDB <- BinaryClient (/127.0.0.1:40817)" java.lang.NullPointerException
    at com.orientechnologies.orient.enterprise.channel.binary.OChannelBinary.close(OChannelBinary.java:393)
    at com.orientechnologies.orient.server.network.protocol.binary.OBinaryNetworkProtocolAbstract.shutdown(OBinaryNetworkProtocolAbstract.java:112)
    at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.shutdown(ONetworkProtocolBinary.java:145)
    at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:72)
```

I found this using the binaries downloaded from the OrientDB website: orientdb-community-2.0-rc2. I have not yet tested it against other versions of OrientDB.

**Comment by tglman** [comment]
hi @quux00,
yes this is a bug the only way to clean up the connection in the current implementation is drop it after the error is sent, i'll fix it in that way.

**Comment by quux00** [comment]
Hi @tglman, 

I haven't read the OrientDB code, and perhaps I'm not understanding your comment, but my hope was that just reading the `storageType` field in all scenarios would solve the problem without having to drop the connection.

**Comment by tglman** [comment]
hi @quux00,

We did some architectural changes in 3.0, now we read first the data and after check the authentication/validity of the message, so since 3.0 it want drop the connection anymore.

I'll close this
