### ISSUE TITLE
OrientDB 2.0 - Orient server shutdown hangs in an embedded app running on tomcat 7

### ISSUE THREAD

**Issue by dshurt** [orientechnologies/orientdb#3488]
I'm using OrientDB embedded in application running on Tomcat 7. 
 When the application starts up it starts Orient.   With version 1.7.10 orient starts and shutdown fine.  However, with version 2.0 it hangs on shutdown.  I traced the issue to the OClientConnectionManager shutdown...it hangs on joining one the protocol threads. 

The DB is started:
OServer server = OServerMain.create();
server.activate();

Shutdown:
server.shutdown();

Also, I switch from 1.7.10 to 2.0 and data was fine however switching back to 1.7.10 the data was corrupted.

**Comment by lvca** [comment]
What do you mean for "data"?

**Comment by dshurt** [comment]
The database data.  The error message indicated the database was corrupt.  
Here the error message:
2015-01-28 13:35:37:969 INFO OrientDB Server v1.7.10 is starting up... [OServer]
2015-01-28 13:35:37:990 INFO Databases directory: C:\var\openstorefront\db\databases [OServer]
2015-01-28 13:35:38:082 INFO Listening binary connections on 0.0.0.0:2424 (protocol v.21, socket=default) [OServerNetworkListener]
2015-01-28 13:35:38:084 INFO Listening http connections on 0.0.0.0:2480 (protocol v.10, socket=default) [OServerNetworkListener]
2015-01-28 13:35:38:191 INFO Installing GREMLIN language v.2.5.0 - graph.pool.max=50 [OGraphServerHandler]
2015-01-28 13:35:38:218 INFO Installing Script interpreter. WARN: authenticated clients can execute any kind of code into the server by using the following allowed languages: [sql] [OServerSideScriptInterpreter]
2015-01-28 13:35:38:218 INFO OrientDB Server v1.7.10 is active. [OServer]
2015-01-28 13:35:38:546 WARN segment file 'database.ocf' was not closed correctly last time [OSingleFileSegment]
2015-01-28 13:35:39:242 WARN Storage openstorefront was not closed properly. Will try to restore from write ahead log. [OLocalPaginatedStorage]
2015-01-28 13:35:39:242 INFO Looking for last checkpoint... [OLocalPaginatedStorage]
2015-01-28 13:35:39:255 INFO FULL checkpoint found. [OLocalPaginatedStorage]
2015-01-28 13:35:39:258 INFO Data restore procedure from full checkpoint is started. Restore is performed from LSN OLogSequenceNumber{segment=4, position=18059770} [OLocalPaginatedStorage]Exception during storage data restore.
java.lang.ArrayIndexOutOfBoundsException: 499
	at com.orientechnologies.orient.core.storage.impl.local.paginated.wal.OPageChanges.deserializeCompressedInteger(OPageChanges.java:167)
	at com.orientechnologies.orient.core.storage.impl.local.paginated.wal.OPageChanges.fromStream(OPageChanges.java:97)
	at com.orientechnologies.orient.core.storage.impl.local.paginated.wal.OUpdatePageRecord.fromStream(OUpdatePageRecord.java:82)
	at com.orientechnologies.orient.core.storage.impl.local.paginated.wal.OWALRecordsFactory.fromStream(OWALRecordsFactory.java:107)
	at com.orientechnologies.orient.core.storage.impl.local.paginated.wal.OWriteAheadLog.read(OWriteAheadLog.java:922)
	at com.orientechnologies.orient.core.storage.impl.local.paginated.OLocalPaginatedStorage.restoreFrom(OLocalPaginatedStorage.java:1778)
	at com.orientechnologies.orient.core.storage.impl.local.paginated.OLocalPaginatedStorage.restoreFromFullCheckPoint(OLocalPaginatedStorage.java:1718)
	at com.orientechnologies.orient.core.storage.impl.local.paginated.OLocalPaginatedStorage.restoreFromCheckPoint(OLocalPaginatedStorage.java:1706)
	at com.orientechnologies.orient.core.storage.impl.local.paginated.OLocalPaginatedStorage.restoreFromWAL(OLocalPaginatedStorage.java:1654)
	at com.orientechnologies.orient.core.storage.impl.local.paginated.OLocalPaginatedStorage.restoreIfNeeded(OLocalPaginatedStorage.java:1559)
	at com.orientechnologies.orient.core.storage.impl.local.paginated.OLocalPaginatedStorage.open(OLocalPaginatedStorage.java:252)
	at com.orientechnologies.orient.core.db.raw.ODatabaseRaw.open(ODatabaseRaw.java:107)
	at com.orientechnologies.orient.core.db.ODatabaseWrapperAbstract.open(ODatabaseWrapperAbstract.java:49)
	at com.orientechnologies.orient.core.db.record.ODatabaseRecordAbstract.open(ODatabaseRecordAbstract.java:268)
	at com.orientechnologies.orient.core.db.ODatabaseWrapperAbstract.open(ODatabaseWrapperAbstract.java:49)
	at com.orientechnologies.orient.server.OServer.openDatabase(OServer.java:557)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.openDatabase(ONetworkProtocolBinary.java:630)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.executeRequest(ONetworkProtocolBinary.java:229)
	at com.orientechnologies.orient.server.network.protocol.binary.OBinaryNetworkProtocolAbstract.execute(OBinaryNetworkProtocolAbstract.java:170)
	at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:45)
Sent run-time exception to the client /127.0.0.1:63108: com.orientechnologies.orient.core.exception.OStorageException: Cannot open local storage '/var/openstorefront/db/databases/openstorefront' with mode=rw
com.orientechnologies.orient.core.exception.OStorageException: Cannot open local storage '/var/openstorefront/db/databases/openstorefront' with mode=rw
	at com.orientechnologies.orient.core.storage.impl.local.paginated.OLocalPaginatedStorage.open(OLocalPaginatedStorage.java:258)
	at com.orientechnologies.orient.core.db.raw.ODatabaseRaw.open(ODatabaseRaw.java:107)
	at com.orientechnologies.orient.core.db.ODatabaseWrapperAbstract.open(ODatabaseWrapperAbstract.java:49)
	at com.orientechnologies.orient.core.db.record.ODatabaseRecordAbstract.open(ODatabaseRecordAbstract.java:268)
	at com.orientechnologies.orient.core.db.ODatabaseWrapperAbstract.open(ODatabaseWrapperAbstract.java:49)
	at com.orientechnologies.orient.server.OServer.openDatabase(OServer.java:557)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.openDatabase(ONetworkProtocolBinary.java:630)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.executeRequest(ONetworkProtocolBinary.java:229)
	at com.orientechnologies.orient.server.network.protocol.binary.OBinaryNetworkProtocolAbstract.execute(OBinaryNetworkProtocolAbstract.java:170)
	at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:45)
Caused by: java.lang.ArrayIndexOutOfBoundsException: 499
	at com.orientechnologies.orient.core.storage.impl.local.paginated.wal.OPageChanges.deserializeCompressedInteger(OPageChanges.java:167)
	at com.orientechnologies.orient.core.storage.impl.local.paginated.wal.OPageChanges.fromStream(OPageChanges.java:97)
	at com.orientechnologies.orient.core.storage.impl.local.paginated.wal.OUpdatePageRecord.fromStream(OUpdatePageRecord.java:82)
	at com.orientechnologies.orient.core.storage.impl.local.paginated.wal.OWALRecordsFactory.fromStream(OWALRecordsFactory.java:107)
	at com.orientechnologies.orient.core.storage.impl.local.paginated.wal.OWriteAheadLog.read(OWriteAheadLog.java:922)
	at com.orientechnologies.orient.core.storage.impl.local.paginated.OLocalPaginatedStorage.restoreFrom(OLocalPaginatedStorage.java:1778)
	at com.orientechnologies.orient.core.storage.impl.local.paginated.OLocalPaginatedStorage.restoreFromFullCheckPoint(OLocalPaginatedStorage.java:1718)
	at com.orientechnologies.orient.core.storage.impl.local.paginated.OLocalPaginatedStorage.restoreFromCheckPoint(OLocalPaginatedStorage.java:1706)
	at com.orientechnologies.orient.core.storage.impl.local.paginated.OLocalPaginatedStorage.restoreFromWAL(OLocalPaginatedStorage.java:1654)
	at com.orientechnologies.orient.core.storage.impl.local.paginated.OLocalPaginatedStorage.restoreIfNeeded(OLocalPaginatedStorage.java:1559)
	at com.orientechnologies.orient.core.storage.impl.local.paginated.OLocalPaginatedStorage.open(OLocalPaginatedStorage.java:252)
	... 9 more
Error occuring starting orient
com.orientechnologies.orient.core.exception.OStorageException: Cannot open local storage '/var/openstorefront/db/databases/openstorefront' with mode=rw
	at com.orientechnologies.orient.core.storage.impl.local.paginated.OLocalPaginatedStorage.open(OLocalPaginatedStorage.java:258)
	at com.orientechnologies.orient.core.db.raw.ODatabaseRaw.open(ODatabaseRaw.java:107)
	at com.orientechnologies.orient.core.db.ODatabaseWrapperAbstract.open(ODatabaseWrapperAbstract.java:49)
	at com.orientechnologies.orient.core.db.record.ODatabaseRecordAbstract.open(ODatabaseRecordAbstract.java:268)
	at com.orientechnologies.orient.core.db.ODatabaseWrapperAbstract.open(ODatabaseWrapperAbstract.java:49)
	at com.orientechnologies.orient.server.OServer.openDatabase(OServer.java:557)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.openDatabase(ONetworkProtocolBinary.java:630)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.executeRequest(ONetworkProtocolBinary.java:229)
	at com.orientechnologies.orient.server.network.protocol.binary.OBinaryNetworkProtocolAbstract.execute(OBinaryNetworkProtocolAbstract.java:170)
	at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:45)
Caused by: java.lang.ArrayIndexOutOfBoundsException: 499
	at com.orientechnologies.orient.core.storage.impl.local.paginated.wal.OPageChanges.deserializeCompressedInteger(OPageChanges.java:167)
	at com.orientechnologies.orient.core.storage.impl.local.paginated.wal.OPageChanges.fromStream(OPageChanges.java:97)
	at com.orientechnologies.orient.core.storage.impl.local.paginated.wal.OUpdatePageRecord.fromStream(OUpdatePageRecord.java:82)
	at com.orientechnologies.orient.core.storage.impl.local.paginated.wal.OWALRecordsFactory.fromStream(OWALRecordsFactory.java:107)
	at com.orientechnologies.orient.core.storage.impl.local.paginated.wal.OWriteAheadLog.read(OWriteAheadLog.java:922)
	at com.orientechnologies.orient.core.storage.impl.local.paginated.OLocalPaginatedStorage.restoreFrom(OLocalPaginatedStorage.java:1778)
	at com.orientechnologies.orient.core.storage.impl.local.paginated.OLocalPaginatedStorage.restoreFromFullCheckPoint(OLocalPaginatedStorage.java:1718)
	at com.orientechnologies.orient.core.storage.impl.local.paginated.OLocalPaginatedStorage.restoreFromCheckPoint(OLocalPaginatedStorage.java:1706)
	at com.orientechnologies.orient.core.storage.impl.local.paginated.OLocalPaginatedStorage.restoreFromWAL(OLocalPaginatedStorage.java:1654)
	at com.orientechnologies.orient.core.storage.impl.local.paginated.OLocalPaginatedStorage.restoreIfNeeded(OLocalPaginatedStorage.java:1559)
	at com.orientechnologies.orient.core.storage.impl.local.paginated.OLocalPaginatedStorage.open(OLocalPaginatedStorage.java:252)
	... 9 more
Exception sending context initialized event to listener instance of class edu.usu.sdl.openstorefront.web.init.ApplicationInit
edu.usu.sdl.openstorefront.exception.OpenStorefrontRuntimeException: com.orientechnologies.orient.core.exception.OStorageException: Cannot open local storage '/var/openstorefront/db/databases/openstorefront' with mode=rw  Error Type Code: SYS
	at edu.usu.sdl.openstorefront.service.manager.DBManager.init(DBManager.java:90)
	at edu.usu.sdl.openstorefront.service.manager.DBManager.initialize(DBManager.java:46)
	at edu.usu.sdl.openstorefront.web.init.ApplicationInit.startupManager(ApplicationInit.java:72)
	at edu.usu.sdl.openstorefront.web.init.ApplicationInit.contextInitialized(ApplicationInit.java:57)
	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4992)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5490)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:901)
	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:877)
	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:649)
	at org.apache.catalina.startup.HostConfig.deployDescriptor(HostConfig.java:672)
	at org.apache.catalina.startup.HostConfig$DeployDescriptor.run(HostConfig.java:1862)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: com.orientechnologies.orient.core.exception.OStorageException: Cannot open local storage '/var/openstorefront/db/databases/openstorefront' with mode=rw
	at com.orientechnologies.orient.core.storage.impl.local.paginated.OLocalPaginatedStorage.open(OLocalPaginatedStorage.java:258)
	at com.orientechnologies.orient.core.db.raw.ODatabaseRaw.open(ODatabaseRaw.java:107)
	at com.orientechnologies.orient.core.db.ODatabaseWrapperAbstract.open(ODatabaseWrapperAbstract.java:49)
	at com.orientechnologies.orient.core.db.record.ODatabaseRecordAbstract.open(ODatabaseRecordAbstract.java:268)
	at com.orientechnologies.orient.core.db.ODatabaseWrapperAbstract.open(ODatabaseWrapperAbstract.java:49)
	at com.orientechnologies.orient.server.OServer.openDatabase(OServer.java:557)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.openDatabase(ONetworkProtocolBinary.java:630)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.executeRequest(ONetworkProtocolBinary.java:229)
	at com.orientechnologies.orient.server.network.protocol.binary.OBinaryNetworkProtocolAbstract.execute(OBinaryNetworkProtocolAbstract.java:170)
	at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:45)
Caused by: java.lang.ArrayIndexOutOfBoundsException: 499
	at com.orientechnologies.orient.core.storage.impl.local.paginated.wal.OPageChanges.deserializeCompressedInteger(OPageChanges.java:167)
	at com.orientechnologies.orient.core.storage.impl.local.paginated.wal.OPageChanges.fromStream(OPageChanges.java:97)
	at com.orientechnologies.orient.core.storage.impl.local.paginated.wal.OUpdatePageRecord.fromStream(OUpdatePageRecord.java:82)
	at com.orientechnologies.orient.core.storage.impl.local.paginated.wal.OWALRecordsFactory.fromStream(OWALRecordsFactory.java:107)
	at com.orientechnologies.orient.core.storage.impl.local.paginated.wal.OWriteAheadLog.read(OWriteAheadLog.java:922)
	at com.orientechnologies.orient.core.storage.impl.local.paginated.OLocalPaginatedStorage.restoreFrom(OLocalPaginatedStorage.java:1778)
	at com.orientechnologies.orient.core.storage.impl.local.paginated.OLocalPaginatedStorage.restoreFromFullCheckPoint(OLocalPaginatedStorage.java:1718)
	at com.orientechnologies.orient.core.storage.impl.local.paginated.OLocalPaginatedStorage.restoreFromCheckPoint(OLocalPaginatedStorage.java:1706)
	at com.orientechnologies.orient.core.storage.impl.local.paginated.OLocalPaginatedStorage.restoreFromWAL(OLocalPaginatedStorage.java:1654)
	at com.orientechnologies.orient.core.storage.impl.local.paginated.OLocalPaginatedStorage.restoreIfNeeded(OLocalPaginatedStorage.java:1559)
	at com.orientechnologies.orient.core.storage.impl.local.paginated.OLocalPaginatedStorage.open(OLocalPaginatedStorage.java:252)
	... 9 more

**Comment by lvca** [comment]
You cannot downgrade and have your database working if modified with a more recent version.

**Comment by lvca** [comment]
By the way, do you have the stacktrace of OClientConnectionManager when it hung?

**Comment by dshurt** [comment]
Thanks, for your prompt response.  I was able to recreate the database and reloaded it.   I just wasn't sure that this was the expected behavior when switching between the two versions.   
Ok, yeah that make sense. 

On the OClientConnectionManager I never got a stacktrace.  It would just hang and I would have to kill the process.   Tracing led me to this point as to where it was hanging.

          if (entry.getValue().protocol.isAlive())
            entry.getValue().protocol.join(); //Thread join

**Comment by lvca** [comment]
@tglman Did you changed something here recently?

**Comment by tglman** [comment]
Hi,

Yes and i did also a fix for the 2.0.1, but i'm not 100% sure that fixed everything because i found some changes i forgot to commit that remained in stash, i commited them some time ago, i'll porte them on 2.0.2

**Comment by tglman** [comment]
should be fixed by https://github.com/orientechnologies/orientdb/commit/b17739f1244b214e95c0f533a36bcbc929ebea13 closing
