### ISSUE TITLE
Issues importing an exported database

### ISSUE THREAD

**Issue by sjohnc** [orientechnologies/orientdb#3528]
Having an issue on v1.7.6 where after exporting a database. I cannot always import this via the console. Most of the time it fails with the below error. Sometimes even with the same exported file it will fail the first time and then pass the 2nd time. 

I had to create a simple bash script as a workaround that would attempt to import it multiple times until it passes or tries 10 times.

The idx mentioned is an Index on the id field in the device table using a Unique Hash Index as per the line "CREATE INDEX idx ON device (id) UNIQUE_HASH_INDEX" in the code that was uses to form the database and tables.

Via Console:

```
Just using import/export commands after connection:

    orientdb {devicelayer}> export database test                                
    Exporting current database to: database test in GZipped JSON format ...

    Started export of database 'devicelayer' to test.json.gz...
    Exporting database info...OK
    Exporting clusters...OK (11 clusters)
    Exporting schema...OK (10 classes)
    Exporting records...
    - Cluster 'internal' (id=0)...OK (records=3/3)
    - Cluster 'index' (id=1).............OK (records=189/189)
    - Cluster 'manindex' (id=2).............OK (records=82/82)
    - Cluster 'default' (id=3)...OK (records=0/0)
    - Cluster 'orole' (id=4)...OK (records=3/3)
    - Cluster 'ouser' (id=5)...OK (records=3/3)
    - Cluster 'orids' (id=6)...OK (records=0/0)
    - Cluster 'ofunction' (id=7)...OK (records=0/0)
    - Cluster 'oschedule' (id=8)...OK (records=0/0)
    - Cluster 'device' (id=9)...OK (records=10/10)
    - Cluster 'autoincrement' (id=10)...OK (records=1/1)

    Done. Exported 291 of total 291 records

    Exporting index info...
    - Index dictionary...OK
    - Index idx...OK
    - Index OUser.name...OK
    - Index ORole.name...OK
    - Index device.serial...OK
    OK (6 indexes)
    Exporting manual indexes content...
    - Exporting index dictionary ...OK (entries=0)
    OK (1 manual indexes)

    Database export completed in 232ms
    orientdb {devicelayer}> import database test.json.gz                                                 

    Importing database test.json.gz...
    Started import of database 'remote:localhost:2430/devicelayer' from test.json.gz...
    Non merge mode (-merge=false): removing all default non security classes
    - Class OFunction was removed.
    - Class ORIDs was removed.
    - Class autoincrement was removed.
    - Class device was removed.
    - Class ORestricted was removed.
    - Class OSchedule was removed.
    - Class OTriggered was removed.
    Removed 7 classes.
    Importing database info...OK
    Importing clusters...
    - Creating cluster 'internal'...OK, assigned id=0
    - Creating cluster 'default'...OK, assigned id=3
    - Creating cluster 'orole'...OK, assigned id=4
    - Creating cluster 'ouser'...OK, assigned id=5
    - Creating cluster 'orids'...OK, assigned id=6
    - Creating cluster 'ofunction'...OK, assigned id=7
    - Creating cluster 'oschedule'...OK, assigned id=8
    - Creating cluster 'device'...OK, assigned id=9
    - Creating cluster 'autoincrement'...OK, assigned id=10
    Rebuilding indexes of truncated clusters ...Error on database import happened just before line 0, column 771
    com.orientechnologies.orient.core.exception.OCommandExecutionException: Index 'idx' not found
      at com.orientechnologies.orient.core.sql.OCommandExecutorSQLRebuildIndex.execute(OCommandExecutorSQLRebuildIndex.java:85)
      at com.orientechnologies.orient.core.sql.OCommandExecutorSQLDelegate.execute(OCommandExecutorSQLDelegate.java:60)
      at com.orientechnologies.orient.core.storage.OStorageEmbedded.executeCommand(OStorageEmbedded.java:94)
      at com.orientechnologies.orient.core.storage.OStorageEmbedded.command(OStorageEmbedded.java:83)
      at com.orientechnologies.orient.core.command.OCommandRequestTextAbstract.execute(OCommandRequestTextAbstract.java:59)
      at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.command(ONetworkProtocolBinary.java:1181)
      at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.executeRequest(ONetworkProtocolBinary.java:340)
      at com.orientechnologies.orient.server.network.protocol.binary.OBinaryNetworkProtocolAbstract.execute(OBinaryNetworkProtocolAbstract.java:169)
      at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:45)

    Error: com.orientechnologies.orient.core.db.tool.ODatabaseExportException: Error on importing database 'devicelayer' from file: test.json.gz

    Error: com.orientechnologies.orient.core.exception.OCommandExecutionException: Index 'idx' not found

Using connect and import on the same line after exporting.

    orientdb {devicelayer}> connect remote:localhost:2430/devicelayer **** ****; import database test.json.gz;             

    Disconnecting from the database [devicelayer]...OK
    Connecting to database [remote:localhost:2430/devicelayer] with user '****'...OK
    Importing database test.json.gz...
    Started import of database 'remote:localhost:2430/devicelayer' from test.json.gz...
    Non merge mode (-merge=false): removing all default non security classes
    - Class ORIDs was removed.
    - Class OFunction was removed.
    - Class autoincrement was removed.
    - Class device was removed.
    - Class ORestricted was removed.
    - Class OSchedule was removed.
    - Class OTriggered was removed.
    Removed 7 classes.
    Importing database info...OK
    Importing clusters...
    - Creating cluster 'internal'...OK, assigned id=0
    - Creating cluster 'default'...OK, assigned id=3
    - Creating cluster 'orole'...OK, assigned id=4
    - Creating cluster 'ouser'...OK, assigned id=5
    - Creating cluster 'orids'...OK, assigned id=6
    - Creating cluster 'ofunction'...OK, assigned id=7
    - Creating cluster 'oschedule'...OK, assigned id=8
    - Creating cluster 'device'...OK, assigned id=9
    - Creating cluster 'autoincrement'...OK, assigned id=10
    Rebuilding indexes of truncated clusters ...Error on database import happened just before line 0, column 771
    com.orientechnologies.orient.core.exception.OCommandExecutionException: Index 'idx' not found
      at com.orientechnologies.orient.core.sql.OCommandExecutorSQLRebuildIndex.execute(OCommandExecutorSQLRebuildIndex.java:85)
      at com.orientechnologies.orient.core.sql.OCommandExecutorSQLDelegate.execute(OCommandExecutorSQLDelegate.java:60)
      at com.orientechnologies.orient.core.storage.OStorageEmbedded.executeCommand(OStorageEmbedded.java:94)
      at com.orientechnologies.orient.core.storage.OStorageEmbedded.command(OStorageEmbedded.java:83)
      at com.orientechnologies.orient.core.command.OCommandRequestTextAbstract.execute(OCommandRequestTextAbstract.java:59)
      at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.command(ONetworkProtocolBinary.java:1181)
      at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.executeRequest(ONetworkProtocolBinary.java:340)
      at com.orientechnologies.orient.server.network.protocol.binary.OBinaryNetworkProtocolAbstract.execute(OBinaryNetworkProtocolAbstract.java:169)
      at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:45)

    Error: com.orientechnologies.orient.core.db.tool.ODatabaseExportException: Error on importing database 'devicelayer' from file: test.json.gz

    Error: com.orientechnologies.orient.core.exception.OCommandExecutionException: Index 'idx' not found

    orientdb {devicelayer}> connect remote:localhost:2430/devicelayer **** ****; import database test.json.gz;

    Disconnecting from the database [devicelayer]...OK
    Connecting to database [remote:localhost:2430/devicelayer] with user '****'...
    2015-02-04 17:07:34:958 WARN Repairing security structures... [OSecurityShared]
    2015-02-04 17:07:36:269 WARN Repair completed [OSecurityShared]OK
    Importing database test.json.gz...
    Started import of database 'remote:localhost:2430/devicelayer' from test.json.gz...
    Non merge mode (-merge=false): removing all default non security classes
    - Class ORIDs was removed.
    - Class ORestricted was removed.
    Removed 2 classes.
    Importing database info...OK
    Importing clusters...
    - Creating cluster 'internal'...OK, assigned id=0
    - Creating cluster 'default'...OK, assigned id=3
    - Creating cluster 'orole'...OK, assigned id=4
    - Creating cluster 'ouser'...OK, assigned id=5
    - Creating cluster 'orids'...OK, assigned id=6
    - Creating cluster 'ofunction'...OK, assigned id=7
    - Creating cluster 'oschedule'...OK, assigned id=8
    - Creating cluster 'device'...OK, assigned id=9
    - Creating cluster 'autoincrement'...OK, assigned id=10
    Rebuilding indexes of truncated clusters ...
    Done 1 indexes were rebuilt.
    Done. Imported 9 clusters
    Importing database schema...OK (10 classes)
    Importing records...
    - Importing records into cluster 'internal' (id=0):  = 2 records
    - Importing records into cluster 'orole' (id=4):  = 3 records
    - Importing records into cluster 'ouser' (id=5):  = 3 records
    - Importing records into cluster 'device' (id=9):  = 10 records
    - Importing records into cluster 'autoincrement' (id=10): 
    Started migration of links (-migrateLinks=true). Links are going to be updated according to new RIDs:
    - Cluster autoincrement... Processed: 1
    - Cluster oschedule... Processed: 0
    - Cluster orole... Processed: 3
    - Cluster ouser... Processed: 3
    - Cluster default... Processed: 0
    - Cluster ofunction... Processed: 0
    - Cluster device... Processed: 10
    - Cluster orids... Processed: 0
    Total links updated: 17

    Done. Imported 18 records

    Importing indexes ...
    - Index 'dictionary'...OK
    - Index 'idx'...
    2015-02-04 17:07:44:698 INFO - Rebuilding index devicelayer.idx (estimated 10 items)... [OIndexRebuildOutputListener]
    2015-02-04 17:07:44:700 INFO --> OK, indexed 10 items in 2 ms [OIndexRebuildOutputListener]OK
    - Index 'OUser.name'...
    2015-02-04 17:07:45:782 INFO - Rebuilding index devicelayer.OUser.name (estimated 3 items)... [OIndexRebuildOutputListener]
    2015-02-04 17:07:45:782 INFO --> OK, indexed 3 items in 1 ms [OIndexRebuildOutputListener]OK
    - Index 'ORole.name'...
    2015-02-04 17:07:46:669 INFO - Rebuilding index devicelayer.ORole.name (estimated 3 items)... [OIndexRebuildOutputListener]
    2015-02-04 17:07:46:669 INFO --> OK, indexed 3 items in 0 ms [OIndexRebuildOutputListener]OK
    - Index 'device.serial'...
    2015-02-04 17:07:47:446 INFO - Rebuilding index devicelayer.device.serial (estimated 10 items)... [OIndexRebuildOutputListener]
    2015-02-04 17:07:47:447 INFO --> OK, indexed 10 items in 1 ms [OIndexRebuildOutputListener]OK
    Done. Created 5 indexes.
    Importing manual index entries...
    - Index 'dictionary'...OK (0 entries)
    Done. Imported 1 indexes.
    Rebuild of stale indexes...
    Stale indexes were rebuilt...
    Deleting RID Mapping table...OK


    Database import completed in 11559 ms
```

Via script:

```
Restoring Device Layer OrientDB database from file DLbackup_OrientDB.json.gz Attempt #1

OrientDB console v.1.7.6 (build UNKNOWN@r; 2014-07-17 18:56:22+0200) www.orientechnologies.com
Type 'help' to display all the commands supported.
Installing extensions for GREMLIN language v.2.5.0

orientdb> connect remote:localhost:2430/devicelayer **** **** 

Connecting to database [remote:localhost:2430/devicelayer] with user '**** '...OK
orientdb {devicelayer}> import database /opt/dorado/owareapps/scripts/DLbackup_OrientDB.json.gz

Importing database /opt/dorado/owareapps/scripts/DLbackup_OrientDB.json.gz...
Started import of database 'remote:localhost:2430/devicelayer' from /opt/dorado/owareapps/scripts/DLbackup_OrientDB.json.gz...
Non merge mode (-merge=false): removing all default non security classes
- Class autoincrement was removed.
- Class OFunction was removed.
- Class ORIDs was removed.
- Class ORestricted was removed.
- Class device was removed.
- Class OTriggered was removed.
- Class OSchedule was removed.
Removed 7 classes.
Importing database info...OK
Importing clusters...
- Creating cluster 'internal'...OK, assigned id=0
- Creating cluster 'default'...OK, assigned id=3
- Creating cluster 'orole'...OK, assigned id=4
- Creating cluster 'ouser'...OK, assigned id=5
- Creating cluster 'orids'...OK, assigned id=6
- Creating cluster 'ofunction'...OK, assigned id=7
- Creating cluster 'oschedule'...OK, assigned id=8
- Creating cluster 'device'...OK, assigned id=9
- Creating cluster 'autoincrement'...OK, assigned id=10
Rebuilding indexes of truncated clusters ...Error on database import happened just before line 0, column 771
com.orientechnologies.orient.core.exception.OCommandExecutionException: Index 'idx' not found
  at com.orientechnologies.orient.core.sql.OCommandExecutorSQLRebuildIndex.execute(OCommandExecutorSQLRebuildIndex.java:85)
  at com.orientechnologies.orient.core.sql.OCommandExecutorSQLDelegate.execute(OCommandExecutorSQLDelegate.java:60)
  at com.orientechnologies.orient.core.storage.OStorageEmbedded.executeCommand(OStorageEmbedded.java:94)
  at com.orientechnologies.orient.core.storage.OStorageEmbedded.command(OStorageEmbedded.java:83)
  at com.orientechnologies.orient.core.command.OCommandRequestTextAbstract.execute(OCommandRequestTextAbstract.java:59)
  at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.command(ONetworkProtocolBinary.java:1181)
  at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.executeRequest(ONetworkProtocolBinary.java:340)
  at com.orientechnologies.orient.server.network.protocol.binary.OBinaryNetworkProtocolAbstract.execute(OBinaryNetworkProtocolAbstract.java:169)
  at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:45)

Error: com.orientechnologies.orient.core.db.tool.ODatabaseExportException: Error on importing database 'devicelayer' from file: /opt/dorado/owareapps/scripts/DLbackup_OrientDB.json.gz

Error: com.orientechnologies.orient.core.exception.OCommandExecutionException: Index 'idx' not foundRestoring Device Layer OrientDB database from file DLbackup_OrientDB.json.gz Attempt #2

2015-02-04 16:54:31:227 WARN Repairing security structures... [OSecurityShared]
2015-02-04 16:54:33:192 WARN Repair completed [OSecurityShared]
2015-02-04 16:54:43:270 INFO - Rebuilding index devicelayer.idx (estimated 10 items)... [OIndexRebuildOutputListener]
2015-02-04 16:54:43:271 INFO --> OK, indexed 10 items in 1 ms [OIndexRebuildOutputListener]
2015-02-04 16:54:45:083 INFO - Rebuilding index devicelayer.OUser.name (estimated 3 items)... [OIndexRebuildOutputListener]
2015-02-04 16:54:45:083 INFO --> OK, indexed 3 items in 0 ms [OIndexRebuildOutputListener]
2015-02-04 16:54:46:221 INFO - Rebuilding index devicelayer.ORole.name (estimated 3 items)... [OIndexRebuildOutputListener]
2015-02-04 16:54:46:221 INFO --> OK, indexed 3 items in 1 ms [OIndexRebuildOutputListener]
2015-02-04 16:54:47:132 INFO - Rebuilding index devicelayer.device.serial (estimated 10 items)... [OIndexRebuildOutputListener]
2015-02-04 16:54:47:133 INFO --> OK, indexed 10 items in 1 ms [OIndexRebuildOutputListener]
OrientDB console v.1.7.6 (build UNKNOWN@r; 2014-07-17 18:56:22+0200) www.orientechnologies.com
Type 'help' to display all the commands supported.
Installing extensions for GREMLIN language v.2.5.0

orientdb> connect remote:localhost:2430/devicelayer **** **** 

Connecting to database [remote:localhost:2430/devicelayer] with user '**** '...OK
orientdb {devicelayer}> import database /opt/dorado/owareapps/scripts/DLbackup_OrientDB.json.gz

Importing database /opt/dorado/owareapps/scripts/DLbackup_OrientDB.json.gz...
Started import of database 'remote:localhost:2430/devicelayer' from /opt/dorado/owareapps/scripts/DLbackup_OrientDB.json.gz...
Non merge mode (-merge=false): removing all default non security classes
- Class ORIDs was removed.
- Class ORestricted was removed.
Removed 2 classes.
Importing database info...OK
Importing clusters...
- Creating cluster 'internal'...OK, assigned id=0
- Creating cluster 'default'...OK, assigned id=3
- Creating cluster 'orole'...OK, assigned id=4
- Creating cluster 'ouser'...OK, assigned id=5
- Creating cluster 'orids'...OK, assigned id=6
- Creating cluster 'ofunction'...OK, assigned id=7
- Creating cluster 'oschedule'...OK, assigned id=8
- Creating cluster 'device'...OK, assigned id=9
- Creating cluster 'autoincrement'...OK, assigned id=10
Rebuilding indexes of truncated clusters ...
Done 1 indexes were rebuilt.
Done. Imported 9 clusters
Importing database schema...OK (10 classes)
Importing records...
- Importing records into cluster 'internal' (id=0):  = 2 records
- Importing records into cluster 'orole' (id=4):  = 3 records
- Importing records into cluster 'ouser' (id=5):  = 3 records
- Importing records into cluster 'device' (id=9):  = 10 records
- Importing records into cluster 'autoincrement' (id=10): 
Started migration of links (-migrateLinks=true). Links are going to be updated according to new RIDs:
- Cluster autoincrement... Processed: 1
- Cluster oschedule... Processed: 0
- Cluster orole... Processed: 3
- Cluster ouser... Processed: 3
- Cluster default... Processed: 0
- Cluster ofunction... Processed: 0
- Cluster device... Processed: 10
- Cluster orids... Processed: 0
Total links updated: 17

Done. Imported 18 records

Importing indexes ...
- Index 'dictionary'...OK
- Index 'idx'...OK
- Index 'OUser.name'...OK
- Index 'ORole.name'...OK
- Index 'device.serial'...OK
Done. Created 5 indexes.
Importing manual index entries...
- Index 'dictionary'...OK (0 entries)
Done. Imported 1 indexes.
Rebuild of stale indexes...
Stale indexes were rebuilt...
Deleting RID Mapping table...OK
```

Script:

```
DL_TRY=true
COUNTER=0
while [ $DL_TRY ]
do
    COUNTER=$((COUNTER + 1))
    echo "Restoring Device Layer OrientDB database from file DLbackup_OrientDB.json.gz Attempt #$COUNTER"
    DL_RESTORE=$((${OWARE_HOME}/../adtran3rd/orientdb/bin/console.sh "connect remote:localhost:2430/devicelayer username password;import database $backup_dl_orient_file;") 2>&1)
    printf "$DL_RESTORE"
    if [[ $DL_RESTORE != *"OCommandExecutionException"*  ||  $COUNTER -gt 10 ]]
    then
        DL_TRY=false
        break
    fi
done
```

**Comment by lvca** [comment]
Please import the database using "plocal", rather than remote connection.

**Comment by sjohnc** [comment]
Can backup/export remain as remote, we only need to use the local storage for import/restore correct? I see you added the 2.2 milestone and bug labels to this so can I assume this may be fixed so you could import via remote connections? Or is it just best practice to shutdown the entire orient server prior to imports?

**Comment by lvca** [comment]
The main problem is to disable server side validation during import. After 2.2 you could do that. You can always import with no shutdown, but if you use plocal you have to.

**Comment by lvca** [comment]
Is this issue still valid?

**Comment by sjohnc** [comment]
I haven't updated to check, the milestone was 2.2 and it hasn't been released yet has it?

**Comment by btym** [comment]
@lvca: Yes, issue still occurs in 2.1.4:

```
Importing database database db_schemas/nuget.json.gz...
Started import of database 'remote:localhost/test_export' from db_schemas/nuget.json.gz...
Non merge mode (-merge=false): removing all default non security classes
Removed 0 classes.
Importing database info...OK
Importing clusters...
- Creating cluster 'internal'...OK, assigned id=0
- Creating cluster 'default'...OK, assigned id=3
- Creating cluster 'orole'...OK, assigned id=4
- Creating cluster 'ouser'...OK, assigned id=5
- Creating cluster 'ofunction'...OK, assigned id=6
- Creating cluster 'oschedule'...OK, assigned id=7
- Creating cluster 'orids'...OK, assigned id=8
- Creating cluster 'v'...OK, assigned id=9
- Creating cluster 'e'...OK, assigned id=10
- Creating cluster '_studio'...OK, assigned id=11
- Creating cluster 'package'...OK, assigned id=12
- Creating cluster 'dependency'...OK, assigned id=13
- Creating cluster 'tag'...OK, assigned id=14
Rebuilding indexes of truncated clusters ...Error on database import happened just before line 0, column 659
com.orientechnologies.orient.core.exception.OCommandExecutionException: Index 'Package.p_name' not found
	at com.orientechnologies.orient.core.sql.OCommandExecutorSQLRebuildIndex.execute(OCommandExecutorSQLRebuildIndex.java:89)
	at com.orientechnologies.orient.core.sql.OCommandExecutorSQLDelegate.execute(OCommandExecutorSQLDelegate.java:90)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.executeCommand(OAbstractPaginatedStorage.java:1452)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.command(OAbstractPaginatedStorage.java:1433)
	at com.orientechnologies.orient.core.command.OCommandRequestTextAbstract.execute(OCommandRequestTextAbstract.java:63)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.command(ONetworkProtocolBinary.java:1319)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.executeRequest(ONetworkProtocolBinary.java:396)
	at com.orientechnologies.orient.server.network.protocol.binary.OBinaryNetworkProtocolAbstract.execute(OBinaryNetworkProtocolAbstract.java:223)
	at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:77)

Error: com.orientechnologies.orient.core.db.tool.ODatabaseExportException: Error on importing database 'test_export' from file: db_schemas/nuget.json.gz

Error: com.orientechnologies.orient.core.exception.OCommandExecutionException: Index 'Package.p_name' not found
```

Interestingly, it imported fine after a server restart.

**Comment by tglman** [comment]
Hi,
since 2.2.x and 3.0.0 the import is done server side, this issue is not valid anymore, closing
