### ISSUE TITLE
Databases cannot be created if default-distributed-db-config.json is changed while server is running

### ISSUE THREAD

**Issue by rtc-draper** [orientechnologies/orientdb#3585]
I think all you need to do is drop the "final" qualifier here:

https://github.com/orientechnologies/orientdb/blob/master/server/src/main/java/com/orientechnologies/orient/server/distributed/ODistributedAbstractPlugin.java#L279

The error you get is as follows:
```
Creating database [remote:localhost/rick-test3] using the storage type [plocal]...Cannot create the remote storage: rick-test3
com.orientechnologies.orient.core.exception.ODatabaseException: Cannot create database 'rick-test3'
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.create(ODatabaseDocumentTx.java:439)
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.create(ODatabaseDocumentTx.java:352)
        at com.orientechnologies.orient.core.db.ODatabaseFactory$1.create(ODatabaseFactory.java:108)
        at com.orientechnologies.orient.server.network.protocol.binary.OBinaryNetworkProtocolAbstract.createDatabase(OBinaryNetworkProtocolAbstract.java:269)
        at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.createDatabase(ONetworkProtocolBinary.java:980)
        at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.executeRequest(ONetworkProtocolBinary.java:290)
        at com.orientechnologies.orient.server.network.protocol.binary.OBinaryNetworkProtocolAbstract.execute(OBinaryNetworkProtocolAbstract.java:216)
        at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:65)
Caused by: com.orientechnologies.orient.core.exception.OConfigurationException: Cannot load default distributed database config file: /opt/orientdb/config/default-distributed-db-config.json
        at com.orientechnologies.orient.server.distributed.ODistributedAbstractPlugin.getDatabaseConfiguration(ODistributedAbstractPlugin.java:286)
        at com.orientechnologies.orient.server.hazelcast.OHazelcastPlugin.onCreateClass(OHazelcastPlugin.java:441)
        at com.orientechnologies.orient.core.metadata.schema.OSchemaShared.doCreateClass(OSchemaShared.java:953)
        at com.orientechnologies.orient.core.metadata.schema.OSchemaShared.createClass(OSchemaShared.java:362)
        at com.orientechnologies.orient.core.metadata.schema.OSchemaShared.createClass(OSchemaShared.java:262)
        at com.orientechnologies.orient.core.metadata.schema.OSchemaShared.createAbstractClass(OSchemaShared.java:344)
        at com.orientechnologies.orient.core.metadata.schema.OSchemaProxy.createAbstractClass(OSchemaProxy.java:123)
        at com.orientechnologies.orient.core.metadata.security.OSecurityShared.createMetadata(OSecurityShared.java:354)
        at com.orientechnologies.orient.core.metadata.security.OSecurityShared.create(OSecurityShared.java:307)
        at com.orientechnologies.orient.core.metadata.security.OSecurityProxy.create(OSecurityProxy.java:74)
        at com.orientechnologies.orient.core.metadata.OMetadataDefault.create(OMetadataDefault.java:93)
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.create(ODatabaseDocumentTx.java:406)
        ... 7 more
```

**Comment by rtc-draper** [comment]
I tried to come up with repro steps but couldn't get it to pop up again. In my case we were testing turning hotAlignment true/false. I've also seen this exception with syntax errors in the file, so it might still be useful to make the two types of errors distinguishable.

Separately, the distributed server will not come online if you encounter this error (it says in a "STARTING" loop forever) because the database you tried to create is only half generated. When encountering this exception I would expect the system to roll back and delete the database folder.

**Comment by lvca** [comment]
@rtc-draper `hotAlignment:true` is not fully working: http://www.orientechnologies.com/docs/last/orientdb.wiki/Distributed-Architecture.html#limitations
