### ISSUE TITLE
Query throws NoSuchElementException

### ISSUE THREAD

**Issue by p1tz** [orientechnologies/orientdb#3588]
I recently looked into other graph databases because of the death of http://thinkaurelius.github.io/titan/

Found orientdb, but ran into trouble at the first steps (using 2.0.2):

I am running orientdb-server embedded in distributed mode (connect via remote:), I create 2 vertices and one edge between them in the first transaction, count everything in the second, and in the third try to do blueprint queries.

The relevant example that fails with a `NoSuchElementException` is:

```java
assertNotNull(t.getVertices("_id", "v1").iterator().next().query().labels("some-label").edges().iterator().next());
```

The testcode is severly ugly, but Ill post everything, maybe I am doing something severly wrong:

```java
package firststeps;

import com.orientechnologies.orient.client.remote.OServerAdmin;
import com.orientechnologies.orient.core.config.OGlobalConfiguration;
import com.orientechnologies.orient.core.exception.OSchemaException;
import com.orientechnologies.orient.core.sql.OCommandSQL;
import com.orientechnologies.orient.server.OServer;
import com.orientechnologies.orient.server.OServerMain;
import com.tinkerpop.blueprints.Vertex;
import com.tinkerpop.blueprints.impls.orient.OrientEdge;
import com.tinkerpop.blueprints.impls.orient.OrientGraph;
import com.tinkerpop.blueprints.impls.orient.OrientGraphFactory;
import java.io.File;
import java.io.IOException;
import org.apache.commons.configuration.BaseConfiguration;
import org.apache.commons.configuration.Configuration;
import org.apache.commons.io.FileUtils;
import org.junit.AfterClass;
import org.junit.BeforeClass;
import org.junit.Test;

import static org.junit.Assert.*;


public class OrientdbEdgeTest
{
  private static OServer server;
  
  static
  {
    System.setProperty("ORIENTDB_ROOT_PASSWORD", "root");
  }
  
  public OrientdbEdgeTest()
  {
  }
  
  
  @AfterClass
  public static void tearDownClass()
  {
    if (server != null) server.shutdown();
  }
  
  @Test
  public void testEdges() throws Exception
  {
    OrientGraphFactory factory = getGraphFactory();
    
    try
    {  
      factory.getNoTx().createEdgeType("some-label");
    } catch(OSchemaException ex) {
      if (!ex.getMessage().contains("exists")) throw(ex);
    }
    
    OrientGraph t = factory.getTx();
    
    Vertex v1 = t.addVertex(null);
    Vertex v2 = t.addVertex(null);
    v1.setProperty("_id", "v1");
    v2.setProperty("_id", "v2");
    
    OrientEdge edge = t.addEdge(null, v1, v2, "some-label");
    edge.setProperty("some", "thing");
    
    t.commit();
    t.shutdown();
    
    t = factory.getTx();
    
    assertEquals(2, t.countVertices());
    assertEquals(1, t.countEdges());
    assertNotNull(t.getVertices("_id", "v1").iterator().next());
    assertNotNull(t.getVertices("_id", "v2").iterator().next());
    t.commit();
    t.shutdown();
    
    t = factory.getTx();
    
    // works
    assertEquals(1, t.getVertices("_id", "v1").iterator().next().query().labels("some-label").count());
    // NoSuchElementException
    assertNotNull(t.getVertices("_id", "v1").iterator().next().query().labels("some-label").edges().iterator().next());
    
    t.commit();
  }
  
  protected static OrientGraphFactory getGraphFactory() throws Exception
  {
    Configuration conf = new BaseConfiguration();
    
    conf.setProperty("storage.url", "remote:localhost/test");
    conf.setProperty("storage.pool-min", "1");
    conf.setProperty("storage.pool-max", "10");
    conf.setProperty("storage.user", "admin");
    conf.setProperty("storage.password", "admin");
    
    
    OGlobalConfiguration.CLIENT_CONNECT_POOL_WAIT_TIMEOUT.setValue(15000);
    
    verifyDatabaseExists(conf);
    
    return new OrientGraphFactory(conf.getString("storage.url"), conf.getString("storage.user"), conf.getString("storage.password")).setupPool(conf.getInt("storage.pool-min"), conf.getInt("storage.pool-max"));
  }
  
  @BeforeClass
  public static void setup() throws Exception
  {
    File file = new File("./target/databases/");
    if (file.exists()) FileUtils.deleteDirectory(file);
    file.mkdirs();
    
    server = OServerMain.create();
    server.startup("<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?>\n" +
"<orient-server>\n" +
"    <handlers>\n" +
"        <!-- GRAPH PLUGIN -->\n" +
"        <handler class=\"com.orientechnologies.orient.graph.handler.OGraphServerHandler\">\n" +
"            <parameters>\n" +
"                <parameter name=\"enabled\" value=\"true\"/>\n" +
"                <parameter name=\"graph.pool.max\" value=\"50\"/>\n" +
"            </parameters>\n" +
"        </handler>\n" +
"       \n" +
      "<handler class=\"com.orientechnologies.orient.server.hazelcast.OHazelcastPlugin\">\n" +
"            <parameters>\n" +
"                <parameter name=\"nodeName\" value=\"unittest\" />\n" +
"                <parameter name=\"enabled\" value=\"true\"/>\n" +
"                <parameter name=\"configuration.db.default\"\n" +
"                           value=\"src/test/resources/default-distributed-db-config.json\"/>\n" +
"                <parameter name=\"configuration.hazelcast\" value=\"src/test/resources/hazelcast.xml\"/>\n" +
"                <parameter name=\"conflict.resolver.impl\"\n" +
"                           value=\"com.orientechnologies.orient.server.distributed.conflict.ODefaultReplicationConflictResolver\"/>\n" +
"\n" +
"                <!-- PARTITIONING STRATEGIES -->\n" +
"                <parameter name=\"sharding.strategy.round-robin\"\n" +
"                           value=\"com.orientechnologies.orient.server.hazelcast.sharding.strategy.ORoundRobinPartitioninStrategy\"/>\n" +
"            </parameters>\n" +
"        </handler>"+
"    </handlers>\n" +
"    <network>\n" +
"        <protocols>\n" +
"            <protocol name=\"binary\"\n" +
"                      implementation=\"com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary\"/>\n" +
"        </protocols>\n" +
"        <listeners>\n" +
"            <listener protocol=\"binary\" ip-address=\"0.0.0.0\" port-range=\"2424-2430\"/>\n" +
"        </listeners>\n" +
"        <cluster>\n" +
"        </cluster>\n" +
"    </network>\n" +
"    <storages>\n" +
"    </storages>\n" +
"    <users>\n" +
"      <user name=\"admin\" password=\"admin\" resources=\"*\"/>\n" +
"    </users>\n" +
"    <properties>\n" +
"\n" +
"        <!-- Uses the Hazelcast's distributed cache as 2nd level cache -->\n" +
"        <!-- <entry name=\"cache.level2.impl\" value=\"com.orientechnologies.orient.server.hazelcast.OHazelcastCache\" /> -->\n" +
"\n" +
"        <!-- DATABASE POOL: size min/max -->\n" +
"        <entry name=\"db.pool.min\" value=\"1\"/>\n" +
"        <entry name=\"db.pool.max\" value=\"20\"/>\n" +
"\n" +
"        <!-- LEVEL1 AND 2 CACHE: enable/disable and set the size as number of entries -->\n" +
"        <entry name=\"cache.level1.enabled\" value=\"false\"/>\n" +
"        <entry name=\"cache.level1.size\" value=\"1000\"/>\n" +
"        <entry name=\"cache.level2.enabled\" value=\"false\"/>\n" +
"        <entry name=\"cache.level2.size\" value=\"1000\"/>\n" +
"\n" +
"<entry name=\"server.database.path\" value=\"target/databases\" />"+      
"        <!-- PROFILER: configures the profiler as <seconds-for-snapshot>,<archive-snapshot-size>,<summary-size>  -->\n" +
"        <entry name=\"profiler.enabled\" value=\"true\"/>\n" +
"        <!-- <entry name=\"profiler.config\" value=\"30,10,10\" />  -->\n" +
"\n" +
"        <!-- LOG: enable/Disable logging. Levels are: finer, fine, finest, info, warning -->\n" +
"        <entry name=\"log.console.level\" value=\"finest\"/>\n" +
"        <entry name=\"log.file.level\" value=\"finest\"/>\n" +
"    </properties>\n" +
"</orient-server>");
    
    server.activate();
  } 
  
  private static void verifyDatabaseExists(Configuration conf)
  {
    final String url = conf.getString("storage.url");
    
    if (!url.startsWith("remote:")) return;
    
    try 
    {
      final OServerAdmin admin = new OServerAdmin(url);

      admin.connect(conf.getString("storage.user"), conf.getString("storage.password"));

      if (!admin.existsDatabase())
      {
        System.err.println("creating database " + url);
        admin.createDatabase("graph", "plocal");
      }
      
      try
      {  
        OrientGraph t = new OrientGraph(url, conf.getString("storage.user"), conf.getString("storage.password"));
        t.command(new OCommandSQL("alter database custom useLightweightEdges=false")).execute();
        t.commit();
        t.shutdown();
      } catch(Throwable ignored) {
        // blank
      }
      
      try
      {  
        OrientGraph t = new OrientGraph(url, conf.getString("storage.user"), conf.getString("storage.password"));
        t.command(new OCommandSQL("ALTER CLASS V CLUSTERSELECTION balanced")).execute();
        t.commit();
        t.shutdown();
      } catch(Throwable ignored) {
        // blank
      }
      
      try
      {  
        OrientGraph t = new OrientGraph(url, conf.getString("storage.user"), conf.getString("storage.password"));
        t.command(new OCommandSQL("ALTER CLASS E CLUSTERSELECTION balanced")).execute();
        t.commit();
        t.shutdown();
      } catch(Throwable ignored) {
        // blank
      }
      
      admin.close();
    } catch (IOException ex1) {
      throw new RuntimeException(ex1);
    }
  }
}
```

the distributed.json:

```json
{
    "autoDeploy": true,
    "hotAlignment": false,
    "executionMode": "synchronous",
    "readQuorum": 1,
    "writeQuorum": 1,
    "failureAvailableNodesLessQuorum": false,
    "readYourWrites": true,
    "clusters": {
        "internal": {
        },
        "index": {
        },
        "*": {
            "servers" : [ "<NEW_NODE>" ]
        }
    }
}
```

(setting executionMode to asynchronous makes the counts fail, am I misinterpreting transaction garantuees?)

**Comment by lvca** [comment]
Please could you try 2.0.3-SNAPSHOT from https://oss.sonatype.org/content/repositories/snapshots/com/orientechnologies/orientdb-community/2.0.3-SNAPSHOT/ ?

**Comment by p1tz** [comment]
hi,

still the same:

```
Scanning for projects...

[...]

Downloaded: libs-snapshot/com/orientechnologies/orientdb-enterprise/2.0.3-SNAPSHOT/orientdb-enterprise-2.0.3-20150213.150313-5.jar (39 KB at 5.2 KB/sec)
                         
Downloaded: libs-snapshot/com/orientechnologies/orientdb-distributed/2.0.3-SNAPSHOT/orientdb-distributed-2.0.3-20150213.150429-5.jar (58 KB at 7.7 KB/sec)
               
Downloaded: libs-snapshot/com/orientechnologies/orientdb-core/2.0.3-SNAPSHOT/orientdb-core-2.0.3-20150213.150303-5.jar (2582 KB at 76.1 KB/sec)

2015-02-15 00:49:31:744 INFO  OrientDB auto-config DISKCACHE=10,695MB (heap=3,641MB os=16,384MB disk=16,245MB) [orientechnologies]
2015-02-15 00:49:31:747 INFO  Loading configuration from input stream [OServerConfigurationLoaderXml]
2015-02-15 00:49:31:879 INFO  OrientDB Server v2.0.3-SNAPSHOT is starting up... [OServer]
2015-02-15 00:49:31:900 INFO  Databases directory: target/databases [OServer]
2015-02-15 00:49:31:925 INFO  Listening binary connections on 0.0.0.0:2424 (protocol v.28, socket=default) [OServerNetworkListener]
2015-02-15 00:49:31:949 INFO  Installing GREMLIN language v.2.6.0 - graph.pool.max=50 [OGraphServerHandler]
2015-02-15 00:49:32:052 INFO  Starting distributed server 'unittest'... [OHazelcastPlugin]
2015-02-15 00:49:32:090 INFO  Configuring Hazelcast from 'src/test/resources/hazelcast.xml'. [FileSystemXmlConfig]
2015-02-15 00:49:32:361 INFO  [LOCAL] [orientdbtest] [3.3] Prefer IPv4 stack is true. [DefaultAddressPicker]
2015-02-15 00:49:32:376 INFO  [LOCAL] [orientdbtest] [3.3] Picked Address[192.168.178.20]:2434, using socket ServerSocket[addr=/0:0:0:0:0:0:0:0,localport=2434], bind any local is true [DefaultAddressPicker]
2015-02-15 00:49:32:413 INFO  [192.168.178.20]:2434 [orientdbtest] [3.3] Starting with 16 generic operation threads and 16 partition operation threads. [BasicOperationScheduler]
2015-02-15 00:49:32:488 INFO  [192.168.178.20]:2434 [orientdbtest] [3.3] Hazelcast 3.3 (20140907) starting at Address[192.168.178.20]:2434 [system]
2015-02-15 00:49:32:488 INFO  [192.168.178.20]:2434 [orientdbtest] [3.3] Copyright (C) 2008-2014 Hazelcast.com [system]
2015-02-15 00:49:32:497 INFO  [192.168.178.20]:2434 [orientdbtest] [3.3] Creating MulticastJoiner [Node]
2015-02-15 00:49:32:503 INFO  [192.168.178.20]:2434 [orientdbtest] [3.3] Address[192.168.178.20]:2434 is STARTING [LifecycleService]
2015-02-15 00:49:36:711 INFO  [192.168.178.20]:2434 [orientdbtest] [3.3] 


Members [1] {
	Member [192.168.178.20]:2434 this
}
 [MulticastJoiner]
2015-02-15 00:49:36:835 INFO  [192.168.178.20]:2434 [orientdbtest] [3.3] Address[192.168.178.20]:2434 is STARTED [LifecycleService]
2015-02-15 00:49:36:978 INFO  [192.168.178.20]:2434 [orientdbtest] [3.3] Initializing cluster partition table first arrangement... [InternalPartitionService]
2015-02-15 00:49:37:031 INFO  [unittest] found no previous messages in queue orientdb.node.unittest.response [OHazelcastDistributedMessageService]
2015-02-15 00:49:37:032 WARNING [unittest] updated node status to 'ONLINE' [OHazelcastPlugin]
2015-02-15 00:49:37:033 INFO  OrientDB Server v2.0.3-SNAPSHOT is active. [OServer]creating database remote:localhost/test

2015-02-15 00:49:37:453 INFO  {db=test} [unittest] loaded database configuration from disk: src/test/resources/default-distributed-db-config.json [OHazelcastPlugin]
2015-02-15 00:49:37:465 WARNING {db=test} [unittest] updated distributed configuration for database: test:
----------
{
  "autoDeploy": true,
  "hotAlignment": false,
  "executionMode": "synchronous",
  "readQuorum": 1,
  "writeQuorum": 1,
  "failureAvailableNodesLessQuorum": false,
  "readYourWrites": true,"clusters":{
    "internal": {
},
    "index": {
},
    "*": {
  "servers": ["<NEW_NODE>"]
}
    },
  "version": 0
}
---------- [OHazelcastPlugin]
2015-02-15 00:49:38:123 INFO  {db=test} [unittest] adding node 'unittest' in partition: db=test [*] [OHazelcastDistributedDatabase]
2015-02-15 00:49:38:124 WARNING {db=test} [unittest] updated distributed configuration for database: test:
----------
{
  "autoDeploy": true,
  "hotAlignment": false,
  "executionMode": "synchronous",
  "readQuorum": 1,
  "writeQuorum": 1,
  "failureAvailableNodesLessQuorum": false,
  "readYourWrites": true,"clusters":{
    "internal": {
},
    "index": {
},
    "*": {
  "servers": ["unittest","<NEW_NODE>"]
}
    },
  "version": 1
}
---------- [OHazelcastPlugin]
2015-02-15 00:49:38:126 INFO  [unittest] received new status unittest.test=SYNCHRONIZING [OHazelcastPlugin]
2015-02-15 00:49:38:126 INFO  {db=test} [unittest] Saving distributed configuration file for database 'test' to: target/databases/test/distributed-config.json [OHazelcastPlugin]
2015-02-15 00:49:38:131 INFO  {db=test} [unittest] found no previous messages in queue orientdb.node.unittest.test.request [OHazelcastDistributedMessageService]
2015-02-15 00:49:38:132 WARNING [unittest] updated distributed configuration for database: test:
----------
{
  "version": 1,
  "autoDeploy": true,
  "hotAlignment": false,
  "executionMode": "synchronous",
  "readQuorum": 1,
  "writeQuorum": 1,
  "failureAvailableNodesLessQuorum": false,
  "readYourWrites": true,"clusters":{
    "internal": {
},
    "index": {
},
    "*": {
  "servers": ["unittest","<NEW_NODE>"]
}
    }
}
---------- [OHazelcastPlugin]
2015-02-15 00:49:38:132 INFO  [unittest] Saving distributed configuration file for database 'test' to: target/databases/test/distributed-config.json [OHazelcastPlugin]
2015-02-15 00:49:38:137 INFO  Sent updated cluster configuration to the remote client 127.0.0.1:51191 [OClientConnectionManager]
2015-02-15 00:49:38:153 INFO  {db=test} [unittest] Installing distributed storage on database 'test' [ODistributedStorage]
2015-02-15 00:49:38:155 INFO  [unittest] Publishing online status for database unittest.test... [OHazelcastDistributedDatabase]
2015-02-15 00:49:38:157 INFO  [unittest] received updated status unittest.test=ONLINE [OHazelcastPlugin]
2015-02-15 00:49:38:159 INFO  [unittest] Installing distributed storage on database 'test' [ODistributedStorage]
2015-02-15 00:49:38:287 INFO  Created database 'test' of type 'plocal' [ONetworkProtocolBinary]
2015-02-15 00:49:38:376 SEVERE [unittest] database.getTransaction().isActive(): true [OHazelcastPlugin]
2015-02-15 00:49:38:395 SEVERE [unittest] database.getTransaction().isActive(): true [OHazelcastPlugin]
2015-02-15 00:49:38:406 SEVERE [unittest] database.getTransaction().isActive(): true [OHazelcastPlugin]
2015-02-15 00:49:38:435 SEVERE [unittest] database.getTransaction().isActive(): true [OHazelcastPlugin]
2015-02-15 00:49:38:468 SEVERE [unittest] database.getTransaction().isActive(): true [OHazelcastPlugin]
2015-02-15 00:49:38:474 SEVERE [unittest] database.getTransaction().isActive(): true [OHazelcastPlugin]
2015-02-15 00:49:38:513 SEVERE [unittest] database.getTransaction().isActive(): true [OHazelcastPlugin]
2015-02-15 00:49:38:531 SEVERE [unittest] database.getTransaction().isActive(): true [OHazelcastPlugin]
2015-02-15 00:49:38:533 SEVERE [unittest] database.getTransaction().isActive(): true [OHazelcastPlugin]
2015-02-15 00:49:38:600 SEVERE [unittest] database.getTransaction().isActive(): true [OHazelcastPlugin]
2015-02-15 00:49:38:700 SEVERE [unittest] database.getTransaction().isActive(): true [OHazelcastPlugin]
2015-02-15 00:49:38:740 SEVERE [unittest] database.getTransaction().isActive(): true [OHazelcastPlugin]
2015-02-15 00:49:38:762 WARNING Record (#-1:-4) is null [OrientEdgeIterator]
2015-02-15 00:49:38:777 INFO  OrientDB Server is shutting down... [OServer]
2015-02-15 00:49:38:777 INFO  Shutting down listeners: [OServer]
2015-02-15 00:49:38:777 INFO  - ONetworkProtocolBinary /0.0.0.0:2424: [OServer]
2015-02-15 00:49:38:778 INFO  Shutting down protocols [OServer]
2015-02-15 00:49:38:778 INFO  Shutting down plugins: [OServerPluginManager]
2015-02-15 00:49:38:778 INFO  - cluster [OServerPluginManager]
2015-02-15 00:49:38:779 WARNING [unittest] Shutdown asynchronous queue worker completed [ODistributedStorage$2]
2015-02-15 00:49:38:783 WARNING [unittest] Shutdown asynchronous queue worker completed [ODistributedStorage$2]
2015-02-15 00:49:38:783 WARNING Shutting down node unittest... [OHazelcastPlugin]
2015-02-15 00:49:38:784 WARNING [unittest] updated node status to 'SHUTTINGDOWN' [OHazelcastPlugin]
2015-02-15 00:49:38:784 WARNING [unittest] Shutdown distributed worker completed [ODistributedWorker]
2015-02-15 00:49:38:786 INFO  [192.168.178.20]:2434 [orientdbtest] [3.3] Address[192.168.178.20]:2434 is SHUTTING_DOWN [LifecycleService]
2015-02-15 00:49:38:821 INFO  [192.168.178.20]:2434 [orientdbtest] [3.3] Destroying node initializer. [initializer]
2015-02-15 00:49:38:821 INFO  [192.168.178.20]:2434 [orientdbtest] [3.3] Hazelcast Shutdown is completed in 34 ms. [Node]
2015-02-15 00:49:38:882 INFO  [192.168.178.20]:2434 [orientdbtest] [3.3] Address[192.168.178.20]:2434 is SHUTDOWN [LifecycleService]
2015-02-15 00:49:38:882 WARNING [unittest] updated node status to 'OFFLINE' [OHazelcastPlugin]
2015-02-15 00:49:38:883 INFO  - graph [OServerPluginManager]
2015-02-15 00:49:38:885 INFO  Shutting down databases: [OServer]
2015-02-15 00:49:38:885 INFO  - closing storage: test... [Orient]
2015-02-15 00:49:38:885 SEVERE Removing disconnected network channel '127.0.0.1:2424/test'... [OStorageRemote]
2015-02-15 00:49:53:887 INFO  - closing storage: test... [Orient]
2015-02-15 00:49:53:888 INFO  - closing storage: test... [Orient]
2015-02-15 00:49:53:912 INFO  - closing storage: test... [Orient]
2015-02-15 00:49:53:912 INFO  - closing storage: test... [Orient]
2015-02-15 00:49:53:915 INFO  OrientDB Engine shutdown complete [Orient]
2015-02-15 00:49:53:915 INFO  OrientDB Server shutdown complete [OServer]Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 22.758 sec <<< FAILURE! - in OrientdbEdgeTest
testEdges(OrientdbEdgeTest)  Time elapsed: 1.746 sec  <<< ERROR!
java.util.NoSuchElementException: null
	at com.tinkerpop.blueprints.util.DefaultVertexQuery$DefaultVertexQueryIterable$1.next(DefaultVertexQuery.java:151)
	at com.tinkerpop.blueprints.util.DefaultVertexQuery$DefaultVertexQueryIterable$1.next(DefaultVertexQuery.java:114)
	at OrientdbEdgeTest.testEdges(OrientdbEdgeTest.java:88)


Results :

Tests in error: 
  OrientdbEdgeTest.testEdges:88 » NoSuchElement

Tests run: 1, Failures: 0, Errors: 1, Skipped: 0

------------------------------------------------------------------------
BUILD FAILURE
------------------------------------------------------------------------
Total time: 2:28.993s
Finished at: Sun Feb 15 00:49:53 CET 2015
Final Memory: 22M/149M
------------------------------------------------------------------------
```

**Comment by p1tz** [comment]
I think this is new?
```
WARNING Record (#-1:-4) is null [OrientEdgeIterator]
```

**Comment by p1tz** [comment]
the actual test suite, if that might help, where I extracted this test case from fails e.g. with
(It tries to read a temp record from the database?)

```java
java.lang.IllegalArgumentException: Cannot read record #-1:-4 since the position is invalid in database 'test'
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.readRecord(OAbstractPaginatedStorage.java:1409)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.readRecord(OAbstractPaginatedStorage.java:697)
	at com.orientechnologies.orient.server.distributed.ODistributedStorage$5.call(ODistributedStorage.java:539)
	at com.orientechnologies.orient.server.distributed.ODistributedAbstractPlugin.runInDistributedMode(ODistributedAbstractPlugin.java:75)
```

**Comment by lvca** [comment]
Reproduced! Working on it...

**Comment by p1tz** [comment]
:+1: thank you
