### ISSUE TITLE
Set embedded field using Document API

### ISSUE THREAD

**Issue by vitorenesduarte** [orientechnologies/orientdb#3612]
**2.0.2.**
Hi,

``` java
      ODatabaseDocument db = new ODatabaseDocumentTx("remote:localhost/New");
      try {
         db.open("admin", "admin");
         db.command(new OCommandSQL("create class Product")).execute();
         db.command(new OCommandSQL("create property Product.data EMBEDDED")).execute();

         db.getMetadata().getSchema().reload();

         ODocument product = new ODocument("Product");
         product.field("data", "{'currency':'EUR'}");
         product.save();
      } finally {
         db.close();
      }
```

throws:

``` bash
Exception in thread "main" com.orientechnologies.orient.core.exception.OValidationException: The field 'Product.data' has been declared as EMBEDDED but an incompatible type is used. Value: {'currency':'EUR'}
    at com.orientechnologies.orient.core.record.impl.ODocument.validateEmbedded(ODocument.java:507)
    at com.orientechnologies.orient.core.record.impl.ODocument.validateField(ODocument.java:296)
    at com.orientechnologies.orient.core.record.impl.ODocument.validate(ODocument.java:1912)
    at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.save(ODatabaseDocumentTx.java:2218)
    at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.save(ODatabaseDocumentTx.java:117)
    at com.orientechnologies.orient.core.record.impl.ODocument.save(ODocument.java:1704)
    at com.orientechnologies.orient.core.record.impl.ODocument.save(ODocument.java:1695)
    at com.asap54.server.test.server.Embedded.embedded(Embedded.java:34)
    at com.asap54.server.test.server.Embedded.main(Embedded.java:20)
```

From studio I'm able to:

``` sql
insert into Product set data = {'currency':'EUR'}
```

What am I doing wrong here?

Thank you,

**Comment by rmuller** [comment]
With product.field("data", "{'currency':'EUR'}"); you store a STRING value (with value "{'currency':'EUR'}"), not JSON. So the field value should be (an instanceof) ODocument or Map.

**Comment by vitorenesduarte** [comment]
Thanks @rmuller, makes sense :)
I'll leave it here for the future generations:
```java
         ODocument product = new ODocument("Product");
         ODocument data = new ODocument();
         data.field("currency", "EUR");
         product.field("data", data);
         product.save();
```

**Comment by voondo** [comment]
(latest 2.2 snapshot)
Maybe I miss something but if it works with a non transactional database, with a transactional one I get this kind of error : `The field 'Product.price' has been declared as EMBEDDED but the value is a document with the valid RecordID Price#220:-3`
I tried `price.setIdentity(null)` but it doesn't like it (NPE at com/orientechnologies/orient/core/record/impl/ODirtyManager.java:125 )

**Comment by jamie-kemp** [comment]
I am also seeing this issue when trying to update an existing embedded document:

```java
	OrientGraphFactory orientGraphFactory = new OrientGraphFactory("plocal:testdb", "admin", "admin").setupPool(1, 3);
	OrientBaseGraph graph = orientGraphFactory.getNoTx();

	OrientVertexType childType = graph.createVertexType("Child");
	OrientVertexType parentType = graph.createVertexType("Parent");
	parentType.createProperty("embed", OType.EMBEDDED, childType);
	graph.shutdown();

	graph = orientGraphFactory.getTx();
	Vertex v = graph.addVertex("class:Parent");
	ODocument child = new ODocument("Child");
	child.field("test", "A value");
	v.setProperty("embed", child);
	graph.commit(); //works
	graph.shutdown();

	graph = orientGraphFactory.getTx();
	Vertex v2 = graph.getVerticesOfClass("Parent").iterator().next();
	Vertex child2 = v2.getProperty("embed");
	child2.setProperty("test" ,"New value");
	graph.commit(); //fails with exception
	graph.shutdown();
```
Exception: `The field 'Parent.embed' has been declared as EMBEDDED but the value is a document with the valid RecordID Child#12:-2{test:New value} v0`

Tested on 2.1.6 and latest 2.2.0 snapshot.

**Comment by voondo** [comment]
Any news about this problem ? Should we reopen a new issue ?

**Comment by voondo** [comment]
Thanks.
FYI I just commented lines 465 to 467 in ODocument.java and everything seems to work fine. Maybe the test should be `isPersistent` instead of `isValid` ?

**Comment by OnlyXYL** [comment]
Hi,
 I met it too.I want to Set embedded field using document, and I met the error. how can i achieve it.
