### ISSUE TITLE
NPE on graph API commit in the OrientDB console.

### ISSUE THREAD

**Issue by flauzon** [orientechnologies/orientdb#3625]
With orientDB 2.0.2

I've been storing Vertex with many many edges (sometimes more than 10'000 vertex linked together with edges). 

I decided to Delete Vertex from my vertex class (about 158'000 records). At which point orientDB complained with an out of memory exception and quit (actually, I started orientdb just before the delete, so I'm pretty sure it's the delete vertex operation that failed).

My JAVA_HOME points to JDK 1.6_45

So I decided to simply delete my database folder and start from scratch. I've created my schemas and classes and now I have a NPE when my graph.commit() is called when storing vertex and edges.

The exception is at the end of this issue.

My actual code is this (which worked fine for a while)
```
    public boolean processSnapshotsStorageGraph(String nodeName, String jsonData)
	{
		boolean retval = false;
		ODatabaseDocumentTx db = connectionPool.acquire();
		OrientGraph graph = graphFactory.getTx();
		try 
		{
			ODocument batch = new ODocument().fromJSON("{ \"snapshots\":"+jsonData+"}");			
			final Collection<Map<Object, Object>> snapshots;		    
		    snapshots = batch.field("snapshots");
		    if (snapshots != null && (!snapshots.isEmpty()))
		    {
		    	List<OrientVertex> stackV = new ArrayList<OrientVertex>(16);
		    	ODocument lastDoc = null;
		    	ODocument doc = null;
		    	int cnt = snapshots.size();
		    	container.logger().info("Storing " + cnt + " snapshots.");
				for (Map<Object, Object> snapshot : snapshots) 
				{
					doc = new ODocument(snapshot);
					
					int depth = doc.field("depth");
					doc.setClassName("BeanSnapshot");
					doc.setFieldType("timeStamp", OType.DATETIME);
					doc.field("nodeName",   getIdForMap(db, "JBossNode",    (String)nodeName,   nodeIdMap));
					doc.field("className",  getIdForMap(db, "BeanClass",   (String)doc.field("className"),  classIdMap));
					doc.field("methodName", getIdForMap(db, "BeanMethod",   (String)doc.field("methodName"), methodIdMap));
					
					--cnt;
					OrientVertex tmpV = graph.getVertex(doc);
					stackV.add(tmpV);
					if ((cnt == 0) || ((depth == 1) && (lastDoc != null)))
					{
						// Process stackV
						if (stackV.size() > 1)
						{
							for (int idx = 0; idx < stackV.size()-1; ++idx)
							{
								OrientVertex from = stackV.get(idx+0);
								OrientVertex to = stackV.get(idx+1);
								graph.addEdge("class:BeanSnapshotEdge", from, to, null);
								
								if ((idx & 127) == 127)									
								{
									graph.commit();
								}
							}
						}
						else
						{
							graph.addEdge("class:BeanSnapshotEdge", tmpV, tmpV, null);		
						}
						
						stackV.clear();
					}
					lastDoc = doc;
				}
		    }
			graph.commit();
			retval = true;
		} 
		catch(Exception e) 
		{
			graph.rollback();
		}
		finally 
		{
			db.close();
			graph.shutdown();
		}
		return retval;
	}
```

```
java.lang.NullPointerException
        at com.orientechnologies.orient.core.metadata.OMetadataDefault$ThreadLocalSchemaSnapshot.access$100(OMetadataDefault.java:279)
        at com.orientechnologies.orient.core.metadata.OMetadataDefault.clearThreadLocalSchemaSnapshot(OMetadataDefault.java:122)
        at com.orientechnologies.orient.core.record.impl.ODocument.getGlobalPropertyById(ODocument.java:1943)
        at com.orientechnologies.orient.core.record.impl.ODocumentInternal.getGlobalPropertyById(ODocumentInternal.java:55)
        at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinaryV0.getGlobalProperty(ORecordSerializerBinaryV0.java:275)
        at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinaryV0.deserializePartial(ORecordSerializerBinaryV0.java:127)
        at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinary.fromStream(ORecordSerializerBinary.java:72)
        at com.orientechnologies.orient.core.record.impl.ODocument.deserializeFields(ODocument.java:1753)
        at com.orientechnologies.orient.core.record.impl.ODocument.checkForFields(ODocument.java:2181)
        at com.orientechnologies.orient.core.record.impl.ODocument.fetchClassName(ODocument.java:2240)
        at com.orientechnologies.orient.core.record.impl.ODocument.getImmutableSchemaClass(ODocument.java:1959)
        at com.orientechnologies.orient.core.record.impl.ODocumentInternal.getImmutableSchemaClass(ODocumentInternal.java:51)
        at com.orientechnologies.orient.core.db.record.OClassTrigger.onTrigger(OClassTrigger.java:185)
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.callbackHooks(ODatabaseDocumentTx.java:966)
        at com.orientechnologies.orient.core.tx.OTransactionOptimistic.addRecord(OTransactionOptimistic.java:277)
        at com.orientechnologies.orient.server.tx.OTransactionOptimisticProxy.begin(OTransactionOptimisticProxy.java:148)
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.begin(ODatabaseDocumentTx.java:1507)
        at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.commit(ONetworkProtocolBinary.java:1084)
        at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.executeRequest(ONetworkProtocolBinary.java:389)
        at com.orientechnologies.orient.server.network.protocol.binary.OBinaryNetworkProtocolAbstract.execute(OBinaryNetworkProtocolAbstract.java:216)
        at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:65)
{db=naidStats} Sent run-time exception to the client /127.0.0.1:51044: java.lang.NullPointerException
java.lang.NullPointerException
        at com.orientechnologies.orient.core.metadata.OMetadataDefault$ThreadLocalSchemaSnapshot.access$100(OMetadataDefault.java:279)
        at com.orientechnologies.orient.core.metadata.OMetadataDefault.clearThreadLocalSchemaSnapshot(OMetadataDefault.java:122)
        at com.orientechnologies.orient.core.record.impl.ODocument.getGlobalPropertyById(ODocument.java:1943)
        at com.orientechnologies.orient.core.record.impl.ODocumentInternal.getGlobalPropertyById(ODocumentInternal.java:55)
        at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinaryV0.getGlobalProperty(ORecordSerializerBinaryV0.java:275)
        at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinaryV0.deserializePartial(ORecordSerializerBinaryV0.java:127)
        at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinary.fromStream(ORecordSerializerBinary.java:72)
        at com.orientechnologies.orient.core.record.impl.ODocument.deserializeFields(ODocument.java:1753)
        at com.orientechnologies.orient.core.record.impl.ODocument.checkForFields(ODocument.java:2181)
        at com.orientechnologies.orient.core.record.impl.ODocument.fetchClassName(ODocument.java:2240)
        at com.orientechnologies.orient.core.record.impl.ODocument.getImmutableSchemaClass(ODocument.java:1959)
        at com.orientechnologies.orient.core.record.impl.ODocumentInternal.getImmutableSchemaClass(ODocumentInternal.java:51)
        at com.orientechnologies.orient.core.db.record.OClassTrigger.onTrigger(OClassTrigger.java:185)
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.callbackHooks(ODatabaseDocumentTx.java:966)
        at com.orientechnologies.orient.core.tx.OTransactionOptimistic.addRecord(OTransactionOptimistic.java:277)
        at com.orientechnologies.orient.server.tx.OTransactionOptimisticProxy.begin(OTransactionOptimisticProxy.java:148)
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.begin(ODatabaseDocumentTx.java:1507)
        at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.commit(ONetworkProtocolBinary.java:1084)
        at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.executeRequest(ONetworkProtocolBinary.java:389)
        at com.orientechnologies.orient.server.network.protocol.binary.OBinaryNetworkProtocolAbstract.execute(OBinaryNetworkProtocolAbstract.java:216)
        at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:65)
```

**Comment by flauzon** [comment]
I've found part of my issues, my client was bound to 2.0 graph api instead of 2.0.2. Sorry about that!

However, I did have an out of memory exception on DELETE vertex, which is not bound to my client..

**Comment by lvca** [comment]
@flauzon ok I'm closing this one. Feel free to open a new issue for the OOM on DELETE.
