### ISSUE TITLE
ODistributedException when try to insert record from client side in distributed mode.

### ISSUE THREAD

**Issue by rinkymangal2010** [orientechnologies/orientdb#3682]
Hi,

I am getting below exception when try to insert record from client side in distributed mode:

com.orientechnologies.orient.server.distributed.ODistributedException: Quorum 2 not reached for request (id=32 from=node1425368744878 task=command_sql(insert into index:dictionary (key,rid) values (?,?)) userName=). Timeout=16ms Servers in timeout/conflict are:
 - node1425368844791: {rid:#18:0,key:user6284781860667377211}
Received: {node1425368844791={rid:#18:0,key:user6284781860667377211}, node1425368744878={rid:#18:0,key:user6284781860667377211}}
        at com.orientechnologies.orient.server.distributed.ODistributedResponseManager.manageConflicts(ODistributedResponseManager.java:576)
        at com.orientechnologies.orient.server.distributed.ODistributedResponseManager.getFinalResponse(ODistributedResponseManager.java:340)
        at com.orientechnologies.orient.server.hazelcast.OHazelcastDistributedDatabase.waitForResponse(OHazelcastDistributedDatabase.java:364)
        at com.orientechnologies.orient.server.hazelcast.OHazelcastDistributedDatabase.send2Nodes(OHazelcastDistributedDatabase.java:191)
        at com.orientechnologies.orient.server.hazelcast.OHazelcastPlugin.sendRequest(OHazelcastPlugin.java:349)
        at com.orientechnologies.orient.server.distributed.ODistributedStorage.command(ODistributedStorage.java:262)
        at com.orientechnologies.orient.core.command.OCommandRequestTextAbstract.execute(OCommandRequestTextAbstract.java:63)
        at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.command(ONetworkProtocolBinary.java:1178)
        at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.executeRequest(ONetworkProtocolBinary.java:385)
        at com.orientechnologies.orient.server.network.protocol.binary.OBinaryNetworkProtocolAbstract.execute(OBinaryNetworkProtocolAbstract.java:220)
        at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:69)

While if i insert record from orientdb server console or via UI there is no error.

Tried with Orientdb version:
2.0.1 and
2.0.3

Regards,
Rinky

**Comment by lvca** [comment]
This has been already fixed in 2.0.15 and 2.1.2
