### ISSUE TITLE
Transactions fail in distributed mode (com.orientechnologies.orient.core.exception.ODatabaseException: Error on retrieving record #-1:-3 (cluster: null))

### ISSUE THREAD

**Issue by povman** [orientechnologies/orientdb#3690]
Run one instance of dserver.

Use this SQL to create a database:
```
CREATE DATABASE remote:localhost/Test root password plocal
CREATE CLASS Client;
CREATE CLASS Matter;
```

Run another instance of dserver. Wait until they synchronise.

Run this java code:
```
package com.tkbt;

import com.orientechnologies.orient.core.db.document.ODatabaseDocumentPool;
import com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx;
import com.orientechnologies.orient.core.record.ORecord;
import com.orientechnologies.orient.core.record.impl.ODocument;
import com.orientechnologies.orient.core.db.OPartitionedDatabasePool;

import java.util.ArrayList;
import java.util.List;

public class Main {

    public static void main(String[] args) {
        ODatabaseDocumentTx db = new ODatabaseDocumentTx("remote:localhost/Test").open("root", "password");
        db.begin();
        try {
            ODocument client = new ODocument("Client");
            ODocument matter = new ODocument("Matter");
            matter.field("client", client);
            List clientMatters = new ArrayList();
            clientMatters.add(matter);
            client.field("matters", clientMatters);
            client.save();
            matter.save();
            db.commit();
        } finally {
            db.close();
        }
    }
}
```

You will get this exception:
```
Exception in thread "main" com.orientechnologies.orient.server.distributed.ODistributedException: Quorum 2 not reached for request (id=24 from=password task=tx userName=). Timeout=37ms Servers in timeout/conflict are:
 - password: com.orientechnologies.orient.core.exception.ODatabaseException: Error on retrieving record #-1:-3 (cluster: null)
Received: {password=com.orientechnologies.orient.core.exception.ODatabaseException: Error on retrieving record #-1:-3 (cluster: null), secondarypass=com.orientechnologies.orient.core.exception.ODatabaseException: Error on retrieving record #-1:-3 (cluster: null)}
	at com.orientechnologies.orient.server.distributed.ODistributedResponseManager.manageConflicts(ODistributedResponseManager.java:576)
	at com.orientechnologies.orient.server.distributed.ODistributedResponseManager.getFinalResponse(ODistributedResponseManager.java:340)
	at com.orientechnologies.orient.server.hazelcast.OHazelcastDistributedDatabase.waitForResponse(OHazelcastDistributedDatabase.java:364)
	at com.orientechnologies.orient.server.hazelcast.OHazelcastDistributedDatabase.send2Nodes(OHazelcastDistributedDatabase.java:191)
	at com.orientechnologies.orient.server.hazelcast.OHazelcastPlugin.sendRequest(OHazelcastPlugin.java:349)
	at com.orientechnologies.orient.server.distributed.ODistributedStorage.commit(ODistributedStorage.java:895)
	at com.orientechnologies.orient.core.tx.OTransactionOptimistic.doCommit(OTransactionOptimistic.java:483)
	at com.orientechnologies.orient.core.tx.OTransactionOptimistic.commit(OTransactionOptimistic.java:147)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.commit(ODatabaseDocumentTx.java:2376)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.commit(ODatabaseDocumentTx.java:2346)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.commit(ONetworkProtocolBinary.java:1087)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.executeRequest(ONetworkProtocolBinary.java:389)
	at com.orientechnologies.orient.server.network.protocol.binary.OBinaryNetworkProtocolAbstract.execute(OBinaryNetworkProtocolAbstract.java:220)
	at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:69)
```

**Comment by lvca** [comment]
The problem was on LINKLIST type instead of the default LINKSET. Now it's fixed.

**Comment by povman** [comment]
The code I posted before now works, but the following gives an exception:
```
package com.tkbt;
import com.orientechnologies.orient.core.db.document.ODatabaseDocumentPool;
import com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx;
import com.orientechnologies.orient.core.record.ORecord;
import com.orientechnologies.orient.core.record.impl.ODocument;
import com.orientechnologies.orient.core.db.OPartitionedDatabasePool;
import java.util.ArrayList;
import java.util.List;

public class Main {

    public static void main(String[] args) throws Exception {
        String id = String.valueOf(Math.random());
        ODatabaseDocumentTx db = new ODatabaseDocumentTx("remote:localhost/Test").open("root", "password");
        db.begin();
        try {
            ODocument client = new ODocument("Client");
            ODocument matter = new ODocument("Matter");
            matter.field("client", client);
            matter.field("id", id);
            List clientMatters = new ArrayList();
            clientMatters.add(matter);
            client.field("matters", clientMatters);
            client.save();
            matter.save();
            db.commit();
        } finally {
            db.close();
        }

        ODatabaseDocumentTx db2 = new ODatabaseDocumentTx("remote:localhost/Test").open("root", "password");
        db2.begin();
        try {
            ODocument matter = null;
            for (ODocument doc : db2.browseCluster("Matter")) {
                if (doc.field("id").equals(id)) {
                    matter = doc;
                    break;
                }
            }
            if (matter == null) {
                throw new Exception("Matter not found with id" + id);
            }
            matter.field("client", new ODocument());
            matter.save();
            db2.commit();
        } finally {
            db2.close();
        }
    }
}
```

Exception:
```
Exception in thread "main" com.orientechnologies.orient.server.distributed.ODistributedException: Quorum 2 not reached for request (id=30 from=primary task=tx userName=). Timeout=22ms Servers in timeout/conflict are:
 - primary: com.orientechnologies.orient.core.exception.ODatabaseException: Error on retrieving record #-1:-2 (cluster: null)
Received: {secondary=com.orientechnologies.orient.core.exception.ODatabaseException: Error on retrieving record #-1:-2 (cluster: null), primary=com.orientechnologies.orient.core.exception.ODatabaseException: Error on retrieving record #-1:-2 (cluster: null)}
	at com.orientechnologies.orient.server.distributed.ODistributedResponseManager.manageConflicts(ODistributedResponseManager.java:576)
	at com.orientechnologies.orient.server.distributed.ODistributedResponseManager.getFinalResponse(ODistributedResponseManager.java:340)
	at com.orientechnologies.orient.server.hazelcast.OHazelcastDistributedDatabase.waitForResponse(OHazelcastDistributedDatabase.java:364)
	at com.orientechnologies.orient.server.hazelcast.OHazelcastDistributedDatabase.send2Nodes(OHazelcastDistributedDatabase.java:191)
	at com.orientechnologies.orient.server.hazelcast.OHazelcastPlugin.sendRequest(OHazelcastPlugin.java:349)
	at com.orientechnologies.orient.server.distributed.ODistributedStorage.commit(ODistributedStorage.java:895)
	at com.orientechnologies.orient.core.tx.OTransactionOptimistic.doCommit(OTransactionOptimistic.java:483)
	at com.orientechnologies.orient.core.tx.OTransactionOptimistic.commit(OTransactionOptimistic.java:147)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.commit(ODatabaseDocumentTx.java:2376)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.commit(ODatabaseDocumentTx.java:2346)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.commit(ONetworkProtocolBinary.java:1087)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.executeRequest(ONetworkProtocolBinary.java:389)
	at com.orientechnologies.orient.server.network.protocol.binary.OBinaryNetworkProtocolAbstract.execute(OBinaryNetworkProtocolAbstract.java:220)
	at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:69)
```

**Comment by gemmell** [comment]
Any known workarounds? We are wanting to go live soon and if this is not fixed we either need to go live without clustering/HA which is incredibly risky.

**Comment by lvca** [comment]
Reproduced.

**Comment by povman** [comment]
Yep seems to work for us now.

**Comment by gemmell** [comment]
This fails again with the latest code in 2.0.x branch.

**Comment by lvca** [comment]
Did you test with asynch or default replication mode?

**Comment by gemmell** [comment]
See https://github.com/orientechnologies/orientdb/issues/3770
