### ISSUE TITLE
Error on initializing Lucene index

### ISSUE THREAD

**Issue by vitorenesduarte** [orientechnologies/orientdb#3699]
__v2.0.4__
Hi,
```sql
# create.sql
connect remote:localhost root root
create database remote:localhost/Demo root root plocal
script sql
ALTER DATABASE CUSTOM useLightweightEdges = true
CREATE CLASS User EXTENDS V
CREATE PROPERTY User.username string
ALTER PROPERTY User.username NOTNULL true
CREATE PROPERTY User.name string

CREATE INDEX UserLUCENE ON User (username, name) FULLTEXT ENGINE LUCENE

end
```
```bash
./console create.sql
```
The script returns:
```bash
Server side script executed in 1.078000 sec(s). Value returned is: 0
```
but the server:
```bash
2015-03-04 18:23:35:413 INFO  {db=Demo} Created database 'Demo' of type 'plocal' [ONetworkProtocolBinary]{db=Demo} Error on initializing Lucene index
org.apache.lucene.store.LockObtainFailedException: Lock obtain timed out: NativeFSLock@/Users/vitorenes/home/progs/orientdb-community-2.0.4/databases/Demo/luceneIndexes/UserLUCENE/write.lock
	at org.apache.lucene.store.Lock.obtain(Lock.java:89)
	at org.apache.lucene.index.IndexWriter.<init>(IndexWriter.java:702)
	at com.orientechnologies.lucene.manager.OLuceneFullTextIndexManager.createIndexWriter(OLuceneFullTextIndexManager.java:57)
	at com.orientechnologies.lucene.manager.OLuceneIndexManagerAbstract.reOpen(OLuceneIndexManagerAbstract.java:336)
	at com.orientechnologies.lucene.manager.OLuceneIndexManagerAbstract.initIndex(OLuceneIndexManagerAbstract.java:301)
	at com.orientechnologies.lucene.manager.OLuceneIndexManagerAbstract.createIndex(OLuceneIndexManagerAbstract.java:91)
	at com.orientechnologies.lucene.OLuceneIndexEngine.create(OLuceneIndexEngine.java:57)
	at com.orientechnologies.orient.core.index.OIndexAbstract.rebuild(OIndexAbstract.java:390)
	at com.orientechnologies.lucene.index.OLuceneIndexNotUnique.rebuild(OLuceneIndexNotUnique.java:178)
	at com.orientechnologies.orient.core.index.OIndexAbstract.create(OIndexAbstract.java:233)
	at com.orientechnologies.orient.core.index.OIndexMultiValues.create(OIndexMultiValues.java:287)
	at com.orientechnologies.lucene.index.OLuceneIndexNotUnique.create(OLuceneIndexNotUnique.java:50)
	at com.orientechnologies.lucene.index.OLuceneIndexNotUnique.create(OLuceneIndexNotUnique.java:37)
	at com.orientechnologies.orient.core.index.OIndexManagerShared.createIndex(OIndexManagerShared.java:169)
	at com.orientechnologies.orient.core.index.OIndexManagerProxy.createIndex(OIndexManagerProxy.java:79)
	at com.orientechnologies.orient.core.metadata.schema.OClassImpl.createIndex(OClassImpl.java:1434)
	at com.orientechnologies.orient.core.sql.OCommandExecutorSQLCreateIndex.execute(OCommandExecutorSQLCreateIndex.java:262)
	at com.orientechnologies.orient.core.sql.OCommandExecutorSQLDelegate.execute(OCommandExecutorSQLDelegate.java:64)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.executeCommand(OAbstractPaginatedStorage.java:1184)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.command(OAbstractPaginatedStorage.java:1173)
	at com.orientechnologies.orient.core.command.OCommandRequestTextAbstract.execute(OCommandRequestTextAbstract.java:63)
	at com.orientechnologies.orient.core.command.script.OCommandExecutorScript.executeSQLScript(OCommandExecutorScript.java:335)
	at com.orientechnologies.orient.core.command.script.OCommandExecutorScript.executeSQL(OCommandExecutorScript.java:138)
	at com.orientechnologies.orient.core.command.script.OCommandExecutorScript.executeInContext(OCommandExecutorScript.java:82)
	at com.orientechnologies.orient.core.command.script.OCommandExecutorScript.execute(OCommandExecutorScript.java:73)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.executeCommand(OAbstractPaginatedStorage.java:1184)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.command(OAbstractPaginatedStorage.java:1173)
	at com.orientechnologies.orient.core.command.OCommandRequestTextAbstract.execute(OCommandRequestTextAbstract.java:63)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.command(ONetworkProtocolBinary.java:1178)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.executeRequest(ONetworkProtocolBinary.java:385)
	at com.orientechnologies.orient.server.network.protocol.binary.OBinaryNetworkProtocolAbstract.execute(OBinaryNetworkProtocolAbstract.java:220)
	at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:69)
```

I think this was working on previous releases, but not entirely sure.
Thanks,

**Comment by lvca** [comment]
Do you have an OrientDB instance up & running?

**Comment by vitorenesduarte** [comment]
Yes. The database is created and the schema too.

**Comment by tobiemh** [comment]
This existed in v2.0.3 but not in v2.0.2

**Comment by jingjingbic** [comment]
I have the same error in our application. We use plocal. 2.0.3

**Comment by vitorenesduarte** [comment]
@lvca since this problem was introduced recently, wouldn't be easier to fix it now that later?

**Comment by lvca** [comment]
@vitorenesduarte I moved it to 2.0.5. Enrico will work tomorrow on it.

**Comment by vitorenesduarte** [comment]
Thank you @lvca :)

**Comment by vitorenesduarte** [comment]
@lvca @syshex
This seems fixed in __2.0.5__.
