### ISSUE TITLE
NullPointerException during orient shutdown (2.0.4)

### ISSUE THREAD

**Issue by gsine** [orientechnologies/orientdb#3700]
I searched through the other NPE issues reported during shutdown and couldn't find a matching trace.

I upgraded to 2.0.4 after having used 2.0-M1 for some time.

I use the OrientGraphFactory to connect to a remote OrientDB, from wildfly.

OrientGraphFactory ogf =  new OrientGraphFactory(dbUrl, dbUsername, dbUserpass);
 ogf.setupPool(dbPoolMin, dbPoolMax);

Then, for transactions I get an instance from the pool with -
ogf.getTx()
followed by commit() and shutdown() as required.

When I shutdown Wildfly, I see the following -
13:45:34,005 SEVERE [com.orientechnologies.orient.core.Orient] (Thread-68) Error during orient shutdown.: java.lang.NullPointerException
        at com.orientechnologies.orient.client.remote.OStorageRemote.getServerURL(OStorageRemote.java:159) [orientdb-client.jar:2.0.4]
        at com.orientechnologies.orient.client.remote.OStorageRemoteThread.popSession(OStorageRemoteThread.java:716) [orientdb-client.jar:2.0.4]
        at com.orientechnologies.orient.client.remote.OStorageRemoteThread.close(OStorageRemoteThread.java:199) [orientdb-client.jar:2.0.4]
        at com.orientechnologies.orient.core.db.OPartitionedDatabasePool.close(OPartitionedDatabasePool.java:318) [orientdb-core.jar:2.0.4]
        at com.orientechnologies.orient.core.db.OPartitionedDatabasePool.onShutdown(OPartitionedDatabasePool.java:300) [orientdb-core.jar:2.0.4]
        at com.orientechnologies.orient.core.Orient.shutdown(Orient.java:312) [orientdb-core.jar:2.0.4]
        at com.orientechnologies.orient.core.OrientShutdownHook.run(OrientShutdownHook.java:32) [orientdb-core.jar:2.0.4]

I have been seeing this since I upgraded to 2.0.4.
Could you please let me know if there is anything else to be done in 2.0.4?

Thanks and Best Regards,
GPN

**Comment by tinhtooaung** [comment]
Hello, i am quite new to orientdb.
I am having exact error with scala 2.11.6,  play2.4 and orientdb 2.0.10

val dbFactory = new OrientGraphFactory(dbUrl.getOrElse("remote:localhost"),
    dbServerUser.getOrElse("admin"),
    dbServerPassword.getOrElse("admin"))
    .setupPool(dbPoolMin.getOrElse(1), dbPoolMax.getOrElse(10))

Everything is working fine until I call dbFactory.close().

Thanks
===========================================

java.lang.NullPointerException: null
        at com.orientechnologies.orient.client.remote.OStorageRemote.getServerURL(OStorageRemote.java:159) ~[orientdb-client-2.0.10.jar:2.0.10]
        at com.orientechnologies.orient.client.remote.OStorageRemoteThread.popSession(OStorageRemoteThread.java:716) ~[orientdb-client-2.0.10.jar:2.0.10]
        at com.orientechnologies.orient.client.remote.OStorageRemoteThread.close(OStorageRemoteThread.java:199) ~[orientdb-client-2.0.10.jar:2.0.10]
        at com.orientechnologies.orient.core.db.OPartitionedDatabasePool.close(OPartitionedDatabasePool.java:352) ~[orientdb-core-2.0.10.jar:2.0.10]
        at com.orientechnologies.orient.core.db.OPartitionedDatabasePool.onShutdown(OPartitionedDatabasePool.java:334) ~[orientdb-core-2.0.10.jar:2.0.10]
        at com.orientechnologies.orient.core.Orient.shutdown(Orient.java:314) ~[orientdb-core-2.0.10.jar:2.0.10]
        at com.orientechnologies.orient.core.OSignalHandler.handle(OSignalHandler.java:52) [orientdb-core-2.0.10.jar:2.0.10]
        at sun.misc.Signal$1.run(Signal.java:212) [na:1.8.0_25]
        at java.lang.Thread.run(Thread.java:745) [na:1.8.0_25]

**Comment by lvca** [comment]
Fixed by 69b868b024bf85182c1295076984ac29de073230
