### ISSUE TITLE
maven tests fail when another server is running

### ISSUE THREAD

**Issue by krichter722** [orientechnologies/orientdb#3704]
the output the relevant part of `mvn install` in the source root is

    $ mvn install
    [output omitted]
    -------------------------------------------------------
     T E S T S
    -------------------------------------------------------
    Running TestSuite
    Configuring TestNG with: TestNG652Configurator

    2015-03-05 13:50:52:360 INFO  OrientDB auto-config DISKCACHE=12.034MB (heap=1.820MB os=15.903MB disk=67.995MB) [orientechnologies]
    2015-03-05 13:50:52:364 INFO  Loading configuration from input stream [OServerConfigurationLoaderXml]
    2015-03-05 13:50:52:531 INFO  OrientDB Server v2.0.4 is starting up... [OServer]
    2015-03-05 13:50:52:555 INFO  Databases directory: /mnt/DATA/sources/orientdb/server/./target/db/databases [OServer]
    2015-03-05 13:50:52:586 INFO  Port 0.0.0.0:2424 busy, trying the next available... [OServerNetworkListener]
    2015-03-05 13:50:52:586 INFO  Listening binary connections on 0.0.0.0:2425 (protocol v.28, socket=default) [OServerNetworkListener]
    2015-03-05 13:50:52:587 INFO  Port 0.0.0.0:2480 busy, trying the next available... [OServerNetworkListener]
    2015-03-05 13:50:52:587 INFO  Listening http connections on 0.0.0.0:2481 (protocol v.10, socket=default) [OServerNetworkListener]
    2015-03-05 13:50:52:592 INFO  Installing dynamic plugin 'studio-2.0.zip'... [OServerPluginManager]
    2015-03-05 13:50:52:678 INFO  JMX plugin installed and active: profilerManaged=true [OJMXPlugin]
    2015-03-05 13:50:52:745 INFO  Installing Script interpreter. WARN: authenticated clients can execute any kind of code into the server by using the following allowed languages: [sql] [OServerSideScriptInterpreter]
    2015-03-05 13:50:52:745 INFO  OrientDB Server v2.0.4 is active. [OServer]Cannot connect to the remote server/database 'remote:localhost/test'
    com.orientechnologies.orient.core.exception.OSecurityAccessException: Wrong user/password to [connect] to the remote OrientDB Server instance. Get the user/password from the config/orientdb-server-config.xml file
	    at com.orientechnologies.orient.server.OServer.serverLogin(OServer.java:446)
	    at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.connect(ONetworkProtocolBinary.java:692)
	    at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.executeRequest(ONetworkProtocolBinary.java:274)
	    at com.orientechnologies.orient.server.network.protocol.binary.OBinaryNetworkProtocolAbstract.execute(OBinaryNetworkProtocolAbstract.java:220)
	    at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:69)
    Cannot connect to the remote server/database 'remote:localhost/test'
    com.orientechnologies.orient.core.exception.OSecurityAccessException: Wrong user/password to [connect] to the remote OrientDB Server instance. Get the user/password from the config/orientdb-server-config.xml file
	    at com.orientechnologies.orient.server.OServer.serverLogin(OServer.java:446)
	    at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.connect(ONetworkProtocolBinary.java:692)
	    at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.executeRequest(ONetworkProtocolBinary.java:274)
	    at com.orientechnologies.orient.server.network.protocol.binary.OBinaryNetworkProtocolAbstract.execute(OBinaryNetworkProtocolAbstract.java:220)
	    at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:69)

    2015-03-05 13:50:52:821 INFO  OrientDB Server is shutting down... [OServer]
    2015-03-05 13:50:52:821 INFO  Shutting down listeners: [OServer]
    2015-03-05 13:50:52:885 INFO  - ONetworkProtocolBinary /0.0.0.0:2425: [OServer]
    2015-03-05 13:50:52:885 INFO  - ONetworkProtocolHttpDb /0.0.0.0:2481: [OServer]
    2015-03-05 13:50:52:886 INFO  Shutting down protocols [OServer]
    2015-03-05 13:50:52:886 INFO  Shutting down plugins: [OServerPluginManager]
    2015-03-05 13:50:52:888 INFO  - studio [OServerPluginManager]
    2015-03-05 13:50:52:888 INFO  - script-interpreter [OServerPluginManager]
    2015-03-05 13:50:52:888 INFO  - jmx [OServerPluginManager]
    2015-03-05 13:50:52:891 INFO  Shutting down databases: [OServer]
    2015-03-05 13:50:52:897 INFO  OrientDB Engine shutdown complete [Orient]
    2015-03-05 13:50:52:897 INFO  OrientDB Server shutdown complete [OServer]
    2015-03-05 13:50:54:460 INFO  [?] Installing distributed storage on database 'null' [ODistributedStorage]
    2015-03-05 13:50:54:523 INFO  [?] Installing distributed storage on database 'null' [ODistributedStorage]
    2015-03-05 13:50:54:525 INFO  [?] Installing distributed storage on database 'null' [ODistributedStorage]
    2015-03-05 13:50:54:559 INFO  [?] Installing distributed storage on database 'null' [ODistributedStorage]
    2015-03-05 13:50:54:561 INFO  [?] Installing distributed storage on database 'null' [ODistributedStorage]Tests run: 16, Failures: 2, Errors: 0, Skipped: 0, Time elapsed: 2.832 sec <<< FAILURE! - in TestSuite
    createBinaryDatabaseConnectCsv(com.orientechnologies.orient.server.network.TestNetworkSerializerIndipendency)  Time elapsed: 0.067 sec  <<< FAILURE!
    com.orientechnologies.orient.core.exception.OStorageException: Cannot connect to the remote server/database 'remote:localhost/test'
	    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	    at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	    at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	    at com.orientechnologies.common.log.OLogManager.error(OLogManager.java:193)
	    at com.orientechnologies.orient.client.remote.OServerAdmin.connect(OServerAdmin.java:115)
	    at com.orientechnologies.orient.server.network.TestNetworkSerializerIndipendency.createDatabase(TestNetworkSerializerIndipendency.java:72)
	    at com.orientechnologies.orient.server.network.TestNetworkSerializerIndipendency.createBinaryDatabaseConnectCsv(TestNetworkSerializerIndipendency.java:80)
    Caused by: com.orientechnologies.orient.core.exception.OSecurityAccessException: Wrong user/password to [connect] to the remote OrientDB Server instance. Get the user/password from the config/orientdb-server-config.xml file
	    at com.orientechnologies.orient.server.OServer.serverLogin(OServer.java:446)
	    at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.connect(ONetworkProtocolBinary.java:692)
	    at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.executeRequest(ONetworkProtocolBinary.java:274)
	    at com.orientechnologies.orient.server.network.protocol.binary.OBinaryNetworkProtocolAbstract.execute(OBinaryNetworkProtocolAbstract.java:220)
	    at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:69)

    createCsvDatabaseConnectBinary(com.orientechnologies.orient.server.network.TestNetworkSerializerIndipendency)  Time elapsed: 0.004 sec  <<< FAILURE!
    com.orientechnologies.orient.core.exception.OStorageException: Cannot connect to the remote server/database 'remote:localhost/test'
	    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	    at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	    at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	    at com.orientechnologies.common.log.OLogManager.error(OLogManager.java:193)
	    at com.orientechnologies.orient.client.remote.OServerAdmin.connect(OServerAdmin.java:115)
	    at com.orientechnologies.orient.server.network.TestNetworkSerializerIndipendency.createDatabase(TestNetworkSerializerIndipendency.java:72)
	    at com.orientechnologies.orient.server.network.TestNetworkSerializerIndipendency.createCsvDatabaseConnectBinary(TestNetworkSerializerIndipendency.java:37)
    Caused by: com.orientechnologies.orient.core.exception.OSecurityAccessException: Wrong user/password to [connect] to the remote OrientDB Server instance. Get the user/password from the config/orientdb-server-config.xml file
	    at com.orientechnologies.orient.server.OServer.serverLogin(OServer.java:446)
	    at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.connect(ONetworkProtocolBinary.java:692)
	    at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.executeRequest(ONetworkProtocolBinary.java:274)
	    at com.orientechnologies.orient.server.network.protocol.binary.OBinaryNetworkProtocolAbstract.execute(OBinaryNetworkProtocolAbstract.java:220)
	    at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:69)

    Results :

    Failed tests: 
      TestNetworkSerializerIndipendency.createBinaryDatabaseConnectCsv:80->createDatabase:72 » OStorage
      TestNetworkSerializerIndipendency.createCsvDatabaseConnectBinary:37->createDatabase:72 » OStorage

    Tests run: 16, Failures: 2, Errors: 0, Skipped: 0

    [INFO] ------------------------------------------------------------------------
    [INFO] Reactor Summary:
    [INFO] 
    [INFO] OrientDB ........................................... SUCCESS [  6.027 s]
    [INFO] OrientDB Test Commons .............................. SUCCESS [  1.487 s]
    [INFO] OrientDB Core ...................................... SUCCESS [11:07 min]
    [INFO] OrientDB Enterprise ................................ SUCCESS [  0.667 s]
    [INFO] OrientDB Client .................................... SUCCESS [  1.709 s]
    [INFO] OrientDB Object .................................... SUCCESS [  5.828 s]
    [INFO] OrientDB Server .................................... FAILURE [  6.693 s]
    [INFO] OrientDB Tools ..................................... SKIPPED
    [INFO] OrientDB GraphDB ................................... SKIPPED
    [INFO] OrientDB Tests ..................................... SKIPPED
    [INFO] OrientDB Distributed Server ........................ SKIPPED
    [INFO] ------------------------------------------------------------------------
    [INFO] BUILD FAILURE
    [INFO] ------------------------------------------------------------------------
    [INFO] Total time: 11:30 min
    [INFO] Finished at: 2015-03-05T13:50:54+01:00
    [INFO] Final Memory: 19M/419M
    [INFO] ------------------------------------------------------------------------
    [ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.17:test (default-test) on project orientdb-server: There are test failures.
    [ERROR] 
    [ERROR] Please refer to /mnt/DATA/sources/orientdb/server/target/surefire-reports for the individual test results.
    [ERROR] -> [Help 1]
    [ERROR] 
    [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
    [ERROR] Re-run Maven using the -X switch to enable full debug logging.
    [ERROR] 
    [ERROR] For more information about the errors and possible solutions, please read the following articles:
    [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
    [ERROR] 
    [ERROR] After correcting the problems, you can resume the build with the command
    [ERROR]   mvn <goals> -rf :orientdb-server

verified with git tag `2.0.4` (no newer commit available). It might be necessary to change to non-default number for all ports used in unit tests.

**Comment by tglman** [comment]
yes we are aware of that, is due to de fact that the port is busy. 

It's not really critical i think, you can run all te tests when there are no server around

**Comment by lvca** [comment]
This is how tests are working, closing the issue.
