### ISSUE TITLE
Moving from Document API to Graph API

### ISSUE THREAD

**Issue by KIC** [orientechnologies/orientdb#3709]
When one moves from Document API to Graph API and use .getDatabase() you will get an "no such Method" exception when you make .close() as you have learned in DocumentAPI. 

<pre>
private OrientGraphFactory pool = new OrientGraphFactory(orientHost + "/" + orientDB, orientUser, orientPass).setupPool(1,10);
        ODatabaseDocumentTx db = pool.getDatabase();

public String getOneByField(String table, String field, String value) {
        //ODatabaseDocumentTx db = pool.acquire();
        ODatabaseDocumentTx db = pool.getDatabase();

        try {
            List<ODocument> query = db.query(new OSQLSynchQuery<ODocument>(MSG("select * from ${1} where ${2} = '${3}'", table, field, value)));
            return query.size() > 0 ? query.get(0).toJSON() : null;
        } finally {
            db.close(); // this will result in an exception
        }
    }
</pre>    

Stack:
<pre>
Caused by: java.lang.NoSuchMethodError: com.orientechnologies.common.concur.resource.OResourcePool.getAllResources()Ljava/util/Collection;
	at com.orientechnologies.orient.client.remote.ORemoteConnectionManager.closePool(ORemoteConnectionManager.java:194) [orientdb-client-2.0.4.jar:2.0.4]
	at com.orientechnologies.orient.client.remote.ORemoteConnectionManager.closePool(ORemoteConnectionManager.java:190) [orientdb-client-2.0.4.jar:2.0.4]
	at com.orientechnologies.orient.client.remote.OStorageRemote.close(OStorageRemote.java:301) [orientdb-client-2.0.4.jar:2.0.4]
	at com.orientechnologies.orient.core.storage.OStorageAbstract.close(OStorageAbstract.java:95) [orientdb-core-2.0.4.jar:2.0.4]
	at com.orientechnologies.orient.client.remote.OStorageRemoteThread.close(OStorageRemoteThread.java:195) [orientdb-client-2.0.4.jar:2.0.4]
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.close(ODatabaseDocumentTx.java:1082) [orientdb-core-2.0.4.jar:2.0.4]
	at com.mindbusters.cms.module.core.api.db.OrientDb.count(OrientDb.java:249) [classes:]
	at com.mindbusters.cms.module.core.api.db.OrientDb$Proxy$_$$_WeldClientProxy.count(Unknown Source) [classes:]
	at com.mindbusters.cms.module.core.api.profile.OrientProfileApi.isAdam(OrientProfileApi.java:58) [classes:]
	at com.mindbusters.cms.module.core.api.profile.OrientProfileApi$Proxy$_$$_WeldClientProxy.isAdam(Unknown Source) [classes:]
	at com.mindbusters.cms.module.core.oauth.SocialAuth.isAdam(SocialAuth.java:241) [classes:]
	at com.mindbusters.cms.module.core.oauth.SocialAuth$Proxy$_$$_WeldClientProxy.isAdam(Unknown Source) [classes:]
	at com.mindbusters.cms.module.core.SessionStore.isUser(SessionStore.java:35) [classes:]
	at com.mindbusters.cms.module.core.SessionStore$Proxy$_$$_WeldClientProxy.isUser(Unknown Source) [classes:]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) [rt.jar:1.8.0_25]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) [rt.jar:1.8.0_25]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) [rt.jar:1.8.0_25]
	at java.lang.reflect.Method.invoke(Method.java:483) [rt.jar:1.8.0_25]
	at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:137) [resteasy-jaxrs-3.0.10.Final.jar:]
	at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:296) [resteasy-jaxrs-3.0.10.Final.jar:]
	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:250) [resteasy-jaxrs-3.0.10.Final.jar:]
	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:237) [resteasy-jaxrs-3.0.10.Final.jar:]
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:356) [resteasy-jaxrs-3.0.10.Final.jar:]
	... 31 more
</pre>

**Comment by vitorenesduarte** [comment]
Something like this may work for you:
```java
   private String something(){
      String json = null;
      OrientGraphFactory factory = new OrientGraphFactory("remote:localhost/GratefulDeadConcerts", "admin", "admin");
      OrientGraph graph = factory.getTx();
      try{
         OSQLSynchQuery query = new OSQLSynchQuery("select from #9:1");
         Iterable result = graph.command(query).execute();
         Iterator it = result.iterator();
         if(it.hasNext()){
            json = ((OrientVertex) it.next()).getRecord().toJSON();
         }
      } finally{
         graph.shutdown();
      }
      
      return json;
   }
```

**Comment by KIC** [comment]
I think you missed the point that i have used a ODatabaseDocumentTx. I want to use doument and graph api. I think I can move back to the document api and use 

<pre>
ODatabaseDocumentPool pool = new ODatabaseDocumentPool(“plocal:/temp/mydb”); OrientGraph g = new OrientGraph(pool.acquire());
</pre>

To get a graph api instead of using the graph api to get a document api.

**Comment by KIC** [comment]
And yes I see the example is not a good one sine i use sql there (but it was the smallest piece of code). Usually i use the ODocument and document api. But I want graph api too.

**Comment by vitorenesduarte** [comment]
You said move, not mix :)
Glad you solved the problem.

**Comment by KIC** [comment]
That is true :) but the issue is: When an api provides a method and a method call results in an exception "no such method". Then this is bug (from my point of view) which should be fixed.

**Comment by lvca** [comment]
The exception:

    Caused by: java.lang.NoSuchMethodError: com.orientechnologies.common.concur.resource.OResourcePool.getAllResources()Ljava/util/Collection;

Means you mixed multiple version of jars in your classpath.

**Comment by KIC** [comment]
yes you are right! sorry for bothering about that (after years I am still not a good friend of classpath/classloaders :-) ).
