### ISSUE TITLE
Error On Connection to Database

### ISSUE THREAD

**Issue by codeniac** [orientechnologies/orientdb#3724]
When trying to connect to a database JOJO i get this errror!

```
2015-03-06 20:25:14:177 WARNING {db=JOJO} segment file 'database.ocf' was not closed correctly last time [OSingleFileSegment]{db=JOJO} Error during file initialization for storage JOJO
java.io.FileNotFoundException: /opt/orient/databases/JOJO/JOJO.1.wal (Permission denied)
	at java.io.RandomAccessFile.open(Native Method)
	at java.io.RandomAccessFile.<init>(RandomAccessFile.java:241)
	at com.orientechnologies.orient.core.storage.impl.local.paginated.wal.ODiskWriteAheadLog$LogSegment.<init>(ODiskWriteAheadLog.java:242)
	at com.orientechnologies.orient.core.storage.impl.local.paginated.wal.ODiskWriteAheadLog$LogSegment.<init>(ODiskWriteAheadLog.java:93)
	at com.orientechnologies.orient.core.storage.impl.local.paginated.wal.ODiskWriteAheadLog.<init>(ODiskWriteAheadLog.java:698)
	at com.orientechnologies.orient.core.storage.impl.local.paginated.wal.ODiskWriteAheadLog.<init>(ODiskWriteAheadLog.java:623)
	at com.orientechnologies.orient.core.storage.impl.local.paginated.OLocalPaginatedStorage.initWalAndDiskCache(OLocalPaginatedStorage.java:283)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.open(OAbstractPaginatedStorage.java:169)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.open(ODatabaseDocumentTx.java:243)
	at com.orientechnologies.orient.console.OConsoleDatabaseApp.connect(OConsoleDatabaseApp.java:227)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at com.orientechnologies.common.console.OConsoleApplication.execute(OConsoleApplication.java:381)
	at com.orientechnologies.common.console.OConsoleApplication.executeCommands(OConsoleApplication.java:246)
	at com.orientechnologies.common.console.OConsoleApplication.run(OConsoleApplication.java:135)
	at com.orientechnologies.orient.graph.console.OGremlinConsole.main(OGremlinConsole.java:62)

Error: com.orientechnologies.orient.core.exception.OStorageException: Cannot open local storage '/opt/orient/databases/JOJO' with mode=rw

Error: java.lang.IllegalStateException: Error during file initialization for storage JOJO

Error: java.io.FileNotFoundException: /opt/orient/databases/JOJO/JOJO.1.wal (Permission denied)
```

**Comment by PhantomYdn** [comment]
What system user used for running OrientDB?
What system user is an owner of /opt/orient/databases/JOJO and inner files?
What security rights on those files? (ls -l) 

I guess the problem is in system rights configuration on your environment.

**Comment by lvca** [comment]
Seems you had no authorization on the file system.
