### ISSUE TITLE
execute parameters cannot include vertex/edge classes

### ISSUE THREAD

**Issue by zifnab87** [orientechnologies/orientdb#3729]
If I run that (I know this is deprecated way to get the documentdb)	
```java
		ODatabaseDocumentTx documentdb = ODatabaseDocumentPool.global().acquire("remote:localhost/nooul", "root", "root");
		OCommandSQL upsert = new OCommandSQL("UPDATE :innerTextClass SET innerText= :innerText UPSERT RETURN AFTER @rid WHERE innerText = :innerText");
		String innerTextStr = " test text ";
		Map<String,Object> params = new HashMap<String,Object>();
		params.put("innerText", innerTextStr);
		params.put("innerTextClass", "FactPersonalInnerText");
		ArrayList<ORecordId> rids = documentdb.command(upsert).execute(params);
		documentdb.close();
		System.out.println(rids.get(0));
		//return rids.get(0);
```
I get this exception:
```
Exception in thread "main" com.orientechnologies.orient.core.sql.OCommandSQLParsingException: Error on parsing command at position #73: Upsert only works with class names . Use UPDATE <class>|cluster:<cluster>> [SET|ADD|PUT|REMOVE|INCREMENT|CONTENT {<JSON>}|MERGE {<JSON>}] [[,] <field-name> = <expression>|<sub-command>]* [LOCK <NONE|RECORD>] [UPSERT] [RETURN <COUNT|BEFORE|AFTER>] [WHERE <conditions>]
Command: UPDATE :innerTextClass SET innerText= :innerText UPSERT RETURN AFTER @rid WHERE innerText = :innerText
---------------------------------------------------------------------------------^
	at com.orientechnologies.orient.core.sql.OCommandExecutorSQLAbstract.throwSyntaxErrorException(OCommandExecutorSQLAbstract.java:89)
	at com.orientechnologies.orient.core.sql.OCommandExecutorSQLUpdate.parse(OCommandExecutorSQLUpdate.java:179)
	at com.orientechnologies.orient.core.sql.OCommandExecutorSQLUpdate.parse(OCommandExecutorSQLUpdate.java:64)
	at com.orientechnologies.orient.core.sql.OCommandExecutorSQLDelegate.parse(OCommandExecutorSQLDelegate.java:56)
	at com.orientechnologies.orient.core.sql.OCommandExecutorSQLDelegate.parse(OCommandExecutorSQLDelegate.java:37)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.command(OAbstractPaginatedStorage.java:1171)
	at com.orientechnologies.orient.core.command.OCommandRequestTextAbstract.execute(OCommandRequestTextAbstract.java:63)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.command(ONetworkProtocolBinary.java:1178)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.executeRequest(ONetworkProtocolBinary.java:385)
	at com.orientechnologies.orient.server.network.protocol.binary.OBinaryNetworkProtocolAbstract.execute(OBinaryNetworkProtocolAbstract.java:220)
	at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:69)
```
If I hardcode the className in the query it works fine. It would be nice if I could upsert a vertex or an edge from the Graph API too

**Comment by lvca** [comment]
This should be supported from v2.1
