### ISSUE TITLE
2.0.3 java.lang.String cannot be cast to com.orientechnologies.orient.core.db.record.OIdentifiable

### ISSUE THREAD

**Issue by stevehu** [orientechnologies/orientdb#3734]
In Java API, delete a vertex with graph.removeVertex(bfn) got the following error on deleting edges. The vertex is derived from document oid like bfn = graph.getVertex(oid.getRecord());

java.lang.ClassCastException: java.lang.String cannot be cast to com.orientechnologies.orient.core.db.record.OIdentifiable
	at com.tinkerpop.blueprints.impls.orient.OrientVertex.removeEdges(OrientVertex.java:365) ~[orientdb-graphdb-2.0.3.jar:2.0.3]
	at com.tinkerpop.blueprints.impls.orient.OrientVertex.remove(OrientVertex.java:680) ~[orientdb-graphdb-2.0.3.jar:2.0.3]
	at com.tinkerpop.blueprints.impls.orient.OrientBaseGraph.removeVertex(OrientBaseGraph.java:754) ~[orientdb-graphdb-2.0.3.jar:2.0.3]
	at com.networknt.light.rule.AbstractBfnRule.delBfnDb(AbstractBfnRule.java:239) [na:na]
	at com.networknt.light.rule.AbstractBfnRule.delBfnEv(AbstractBfnRule.java:227) [na:na]
	at com.networknt.light.rule.forum.DelForumEvRule.execute(DelForumEvRule.java:27) [na:na]
	at com.networknt.light.rule.RuleEngine$1.run(RuleEngine.java:93) [classes/:na]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_31]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_31]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_31]

**Comment by stevehu** [comment]
Upon further investigation, it looks like I have write a string into the in_Own somehow. I don't know if this is a bug or not as an edge is defined for the vertex as "Own". Once this happens I have to recreate the database as db is corrupted.

    "in_Own": [
      "Plant",
      "#35:0"
    ],

**Comment by lvca** [comment]
If you didn't create any constraint, the schema-less side of OrientDB lets it pass as string.

**Comment by lvca** [comment]
By the way how did you create it as string?

**Comment by stevehu** [comment]
Thanks for the quick response. I just create a vertex buy passing a HashMap.
            OrientVertex bfn = graph.addVertex("class:" + className, data);

**Comment by lvca** [comment]
The problem refers to the edge. How did you fill the list with the string?

**Comment by stevehu** [comment]
In my data, there is a list call out_Own and "Plant" is an element.
