### ISSUE TITLE
manual insertion/deletion on composite key index failure inside batch operation

### ISSUE THREAD

**Issue by danrub** [orientechnologies/orientdb#3737]
When trying to execute batch sql command against the server, and the batch has a insertion of key and rid targeting an composite key index, the execution fails with stack trace:

Caused by: java.lang.IllegalStateException: Object of classjava.util.ArrayList can not be compared
        at com.orientechnologies.common.comparator.ODefaultComparator.compare(ODefaultComparator.java:55)
        at java.util.TreeMap.compare(TreeMap.java:1188)
        at java.util.TreeMap.put(TreeMap.java:531)
        at com.orientechnologies.orient.core.tx.OTransactionIndexChanges.getChangesPerKey(OTransactionIndexChanges.java:54)
        at com.orientechnologies.orient.core.tx.OTransactionRealAbstract.addIndexEntry(OTransactionRealAbstract.java:304)
        at com.orientechnologies.orient.core.index.OIndexTxAware.put(OIndexTxAware.java:97)
        at com.orientechnologies.orient.core.index.OIndexTxAware.put(OIndexTxAware.java:41)
        at com.orientechnologies.orient.core.sql.OCommandExecutorSQLInsert.execute(OCommandExecutorSQLInsert.java:200)
        at com.orientechnologies.orient.core.sql.OCommandExecutorSQLDelegate.execute(OCommandExecutorSQLDelegate.java:83)
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.executeCommand(OAbstractPaginatedStorage.java:1185)

Use Case:

CREATE INDEX test NOTUNIQUE LINK,LINK

batch command1:

BEGIN
let $i1 = INSERT INTO index:test (key,rid) values ([#1:1,#1:2],#1:3)
COMMIT RETRY 1
RETURN 1

batch command2:

BEGIN
let $d1 = DELETE FROM index:test WHERE key = [#1:1,#1:2]
COMMIT RETRY 1
RETURN 1

possibly related to issue #2741

**Comment by tglman** [comment]
tested on 2.1 impossible to reproduce it, closing
