### ISSUE TITLE
Database isn't dropped in distributed mode

### ISSUE THREAD

**Issue by tobiemh** [orientechnologies/orientdb#3746]
```sql
CREATE DATABASE remote:127.0.0.1/testdatabase root root plocal graph
DROP DATABASE remote:127.0.0.1/testdatabase root root
CREATE DATABASE remote:127.0.0.1/testdatabase root root plocal graph
```

```shell
Creating database [remote:127.0.0.1/testdatabase] using the storage type [plocal]...
Database created successfully.
Current database is: remote:127.0.0.1/testdatabase

Disconnecting from remote server [remote:127.0.0.1/testdatabase]...
Database 'remote:127.0.0.1/testdatabase' deleted successfully

Creating database [remote:127.0.0.1/testdatabase] using the storage type [plocal]...Cannot create the remote storage: testdatabase
com.orientechnologies.orient.core.exception.ODatabaseException: Cannot create database 'testdatabase'
    at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.create(ODatabaseDocumentTx.java:439)
    at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.create(ODatabaseDocumentTx.java:352)
    at com.orientechnologies.orient.core.db.ODatabaseFactory$1.create(ODatabaseFactory.java:108)
    at com.orientechnologies.orient.server.network.protocol.binary.OBinaryNetworkProtocolAbstract.createDatabase(OBinaryNetworkProtocolAbstract.java:273)
    at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.createDatabase(ONetworkProtocolBinary.java:980)
    at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.executeRequest(ONetworkProtocolBinary.java:290)
    at com.orientechnologies.orient.server.network.protocol.binary.OBinaryNetworkProtocolAbstract.execute(OBinaryNetworkProtocolAbstract.java:220)
    at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:69)
Caused by: com.orientechnologies.orient.core.exception.ODatabaseException: Cannot open database
    at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.open(ODatabaseDocumentTx.java:276)
    at com.orientechnologies.orient.server.OServer.openDatabase(OServer.java:674)
    at com.orientechnologies.orient.server.hazelcast.OHazelcastPlugin.installDbClustersLocalStrategy(OHazelcastPlugin.java:1093)
    at com.orientechnologies.orient.server.hazelcast.OHazelcastPlugin.onOpen(OHazelcastPlugin.java:418)
    at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.callOnOpenListeners(ODatabaseDocumentTx.java:336)
    at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.open(ODatabaseDocumentTx.java:270)
    at com.orientechnologies.orient.server.OServer.openDatabase(OServer.java:647)
    at com.orientechnologies.orient.server.OServer.openDatabase(OServer.java:613)
    at com.orientechnologies.orient.server.hazelcast.ODistributedWorker.initDatabaseInstance(ODistributedWorker.java:161)
    at com.orientechnologies.orient.server.hazelcast.OHazelcastDistributedDatabase.unqueuePendingMessages(OHazelcastDistributedDatabase.java:264)
    at com.orientechnologies.orient.server.hazelcast.OHazelcastDistributedDatabase.configureDatabase(OHazelcastDistributedDatabase.java:209)
    at com.orientechnologies.orient.server.hazelcast.OHazelcastPlugin.onCreate(OHazelcastPlugin.java:382)
    at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.create(ODatabaseDocumentTx.java:429)
    ... 7 more
Caused by: java.lang.IllegalStateException: Database testdatabase is already open
    at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.open(ODatabaseDocumentTx.java:237)
    ... 19 more

Error: com.orientechnologies.orient.core.exception.OStorageException: Cannot create the remote storage: testdatabase

Error: com.orientechnologies.orient.core.exception.ODatabaseException: Cannot create database 'testdatabase'

Error: com.orientechnologies.orient.core.exception.ODatabaseException: Cannot open database

Error: java.lang.IllegalStateException: Database testdatabase is already open
```

NOTE: The same problem occurs when using the console or the studio.

***

OrientDB version: 2.0.4

**Comment by lvca** [comment]
Tested with 2.0.5 and works. Remember to drop the database from the server you want to be dropped.

**Comment by lvca** [comment]
```
MacBook-Pro:draper luca$ ./orientdb-1/bin/console.sh "DROP DATABASE remote:localhost/test root password"

OrientDB console v.2.0.6-SNAPSHOT (build UNKNOWN@r; 2015-03-16 21:13:00+0000) www.orientechnologies.com
Type 'help' to display all the supported commands.
Installing extensions for GREMLIN language v.2.6.0

orientdb> DROP DATABASE remote:localhost/test root password

2015-03-16 22:52:37:697 INFO  Dropped database 'test' [ONetworkProtocolBinary]
2015-03-16 22:52:37:765 WARNING [node1] Shutdown asynchronous queue worker completed [ODistributedStorage$2]
Disconnecting from remote server [remote:localhost/test]...
OK

Database 'remote:localhost/test' deleted successfully
```

**Comment by tobiemh** [comment]
Just tested this with 2.0.5. The database supposedly drops without any errors on the server side, but when you try to create a database with the same name then there are errors:

Setup two nodes 172.17.8.101 and 172.17.8.102

```sql
CREATE DATABASE remote:172.17.8.101/testdatabase root root plocal graph
# Creating database [remote:127.0.0.1/testdatabase] using the storage type [plocal]...
# Database created successfully.
# Current database is: remote:127.0.0.1/testdatabase
```

Wait for database to sync to secondary node (172.17.8.102)...

```sql
DROP DATABASE remote:172.17.8.101/testdatabase root root
# Disconnecting from remote server [remote:172.17.8.101/testdatabase]...
# Database 'remote:172.17.8.101/testdatabase' deleted successfully
DROP DATABASE remote:172.17.8.102/testdatabase root root
# Disconnecting from remote server [remote:172.17.8.102/testdatabase]...
# Database 'remote:172.17.8.102/testdatabase' deleted successfully
```

Then try to create a database with the same name on either of the nodes...

```sql
CREATE DATABASE remote:172.17.8.101/testdatabase root root plocal graph
```

Results in the following error on server 1:
```
2015-03-17 00:10:19:110 SEVERE Internal server error:
java.lang.IllegalStateException: Database onlineplatforms is already open [ONetworkProtocolHttpDb][core-4]<-[core-3] error on executing distributed request 35: deploy_db
com.orientechnologies.orient.core.exception.ODatabaseException: Database 'plocal:/opt/orient/databases/onlineplatforms' is closed
   at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.checkOpeness(ODatabaseDocumentTx.java:2590)
   at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.rollback(ODatabaseDocumentTx.java:2425)
   at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.rollback(ODatabaseDocumentTx.java:2420)
   at com.orientechnologies.orient.server.hazelcast.ODistributedWorker.onMessage(ODistributedWorker.java:304)
   at com.orientechnologies.orient.server.hazelcast.ODistributedWorker.run(ODistributedWorker.java:121)
```

And the following error on server 2:

```
2015-03-17 00:09:44:313 WARNING [core-1] Shutdown asynchronous queue worker completed [ODistributedStorage$2][core-1]<-[core-3] error on executing distributed request 35: deploy_db
com.orientechnologies.orient.core.exception.ODatabaseException: Database 'plocal:/opt/orient/databases/onlineplatforms' is closed
   at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.checkOpeness(ODatabaseDocumentTx.java:2590)
   at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.rollback(ODatabaseDocumentTx.java:2425)
   at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.rollback(ODatabaseDocumentTx.java:2420)
   at com.orientechnologies.orient.server.hazelcast.ODistributedWorker.onMessage(ODistributedWorker.java:304)
```

I was mainly using this for doing tests on the database, so not really intended to be used in production, but thought it might be a bug anyway.

***

OrientDB version 2.0.5

**Comment by lvca** [comment]
You should drop the database from each servers, otherwise will still be there. That's why on other servers give errors.

**Comment by tobiemh** [comment]
Yeh I dropped the database on all of the connected servers, before trying to create the database again. The [last comment](https://github.com/orientechnologies/orientdb/issues/3746#issuecomment-82003576) was using just 2 connected servers, but it's the same with 3,4,5 servers in distributed mode. 

Successful DROP DATABASE on both nodes:

```sql
DROP DATABASE remote:172.17.8.101/testdatabase root root
# Disconnecting from remote server [remote:172.17.8.101/testdatabase]...
# Database 'remote:172.17.8.101/testdatabase' deleted successfully
DROP DATABASE remote:172.17.8.102/testdatabase root root
# Disconnecting from remote server [remote:172.17.8.102/testdatabase]...
# Database 'remote:172.17.8.102/testdatabase' deleted successfully
```

but this won't work on either server afterwards...

```sql
CREATE DATABASE remote:172.17.8.101/testdatabase root root plocal graph
```

**Comment by romainPellerin** [comment]
Hi @lvca 

I have exactly the same error on my distributed OrientDB instances with 2 nodes.
The database *mydb* was created on the "slave" instance.
After a drop database via OrientDB studio, on the slave then on the master, impossible to create a new database with the same name. I reproduce the same error by dropping the database from console.sh.
I was obliged to erase physically the database with a **sudo rm -rf /opt/orientdb/databases/mydb** on both instances to be able to create a new *mydb*.

OrientDB version: 2.0.6

**Comment by tobiemh** [comment]
Yep this is still happening on 2.0.5, 2.0.6, 2.0.7.

#3947 is probably the same issue

**Comment by lvca** [comment]
drop and recreate of database distributed is not supported. Try `sync database FULL_REPLACE` command

**Comment by stefanbacon** [comment]
Been trying to reset (drop and create a new database) a distributed database too. 
the sync command is not available from orientdb console (2.1.3)
I'm using it through the java api but haven't figured out how to use to reset a database.
Anyone got this working?

Thanks

**Comment by tobiemh** [comment]
@lvca how should we use the `sync database FULL_REPLACE` command? Can this be done from the console? And if not, how do we go about dropping / resetting / replacing a distributed database from the console?

Thanks

**Comment by stefanbacon** [comment]
managed to do a db reset like this:

In my scenaria I had 2 orientdb instances in distributed mode:
1. bring the distributed orientdb instances offline
2. bring a standalone instance online
3. drop the database
4. create database
5. export blank database with -includeSecurity=true (we'll use this export to reset the database) 

now when you want to reset db you can:
1. bring orientdb distributed instances offline
2. bring standalone instances online
3. on each standalone instance do a drop then a create then an import with -preserveClusterIDs=true of our blankdb export
4. shutdown standalone instances and bring back the distributed instances online

**Comment by lukeasrodgers** [comment]
FWIW I get the same `java.lang.IllegalStateException` with 2.0.6 but not with 2.0.2 even in standalone mode.
