### ISSUE TITLE
OCommandSQL  create lucene index throws exception

### ISSUE THREAD

**Issue by syshex** [orientechnologies/orientdb#3752]
Running 2.0.4 embedded.

Trying to create a Lucene index like this : 
```
OrientGraphNoTx graph = OrientDBInstance.getInstance().getNoTxGraph();
OrientVertexType personVertexType = graph.createVertexType(ContactosVertexType.PESSOA.name);
graph.command(new OCommandSQL("create index Pessoa.nome on Pessoa(nome) FULLTEXT ENGINE LUCENE"));
```

Produces nothing. No exception, and no Lucene Index.  I was under the impression (from the javadocs) that calling  command() on a NoTX Graph would execute the command. But apparently it doesn't. 

Since command returns a  OCommandRequest ,  I tried calling execute on that commandRequest, like so:
```
OrientGraphNoTx graph = OrientDBInstance.getInstance().getNoTxGraph();
OrientVertexType personVertexType = graph.createVertexType(ContactosVertexType.PESSOA.name);
graph.command(new OCommandSQL("create index Pessoa.nome on Pessoa(nome) FULLTEXT ENGINE LUCENE")).execute();
```

Here , I get an Index created (confirmed through Studio, which I've got running embedded as well) but throws an exception referring to a lock : 
```
[error] c.o.l.m.OLuceneFullTextIndexManager - {db=contactos} Error on initializing Lucene index
org.apache.lucene.store.LockObtainFailedException: Lock obtain timed out: NativeFSLock@/home/rui/projects/IT-Contactos/datafolder/databases/contactos/luceneIndexes/Pessoa.nome/write.lock
	at org.apache.lucene.store.Lock.obtain(Lock.java:89) ~[lucene-core-4.7.0.jar:4.7.0 1570806 - simon - 2014-02-22 08:25:23]
	at org.apache.lucene.index.IndexWriter.<init>(IndexWriter.java:702) ~[lucene-core-4.7.0.jar:4.7.0 1570806 - simon - 2014-02-22 08:25:23]
	at com.orientechnologies.lucene.manager.OLuceneFullTextIndexManager.createIndexWriter(OLuceneFullTextIndexManager.java:57) ~[orientdb-lucene-2.0.4.jar:na]
	at com.orientechnologies.lucene.manager.OLuceneIndexManagerAbstract.reOpen(OLuceneIndexManagerAbstract.java:336) [orientdb-lucene-2.0.4.jar:na]
	at com.orientechnologies.lucene.manager.OLuceneIndexManagerAbstract.initIndex(OLuceneIndexManagerAbstract.java:301) [orientdb-lucene-2.0.4.jar:na]
```

Not too sure I'm doing this right or if this is a bug. My project dependencies are:
```
  "com.orientechnologies" % "orientdb-enterprise" % "2.0.4",
  "com.orientechnologies" % "orientdb-server" % "2.0.4",
  "com.orientechnologies" % "orientdb-graphdb" % "2.0.4",
  "com.orientechnologies" % "orientdb-lucene" % "2.0.4",
  "com.orientechnologies" % "orientdb-jdbc" % "2.0.4"
```

**Comment by syshex** [comment]
Actually as Vitor pointed out by email, this is the same as https://github.com/orientechnologies/orientdb/issues/3699  .

I tried now creating that same index using studio and I get the same problem.
