### ISSUE TITLE
ORecordNotFoundException instead of OConcurrentModificationException

### ISSUE THREAD

**Issue by profic** [orientechnologies/orientdb#3760]
Hi Luca. I have downloaded and run OrientDB 2.0.5 in single mode. I wrote a test for check ACID, in this test case I tried to emulate updates from 20 multiple threads. Unfortunately, I got ORecordNotFoundException instead of expected OConcurrentModificationException. 

Thanks, Vlad

    @Test
    public void testMultipleThreadUpdatesPlainEdges() throws Exception {

        int threadsCount = 20;
        ExecutorService service = Executors.newFixedThreadPool(threadsCount);

        OrientGraph t1 = factory.graph();
        t1.begin();
        t1.getVerticesOfClass("Person").forEach(t1::removeVertex);
        t1.commit();

        t1.begin();
        OrientVertex luca = t1.addVertex("class:Person");
        luca.setProperty("name", "Luca");

        OrientVertex ferrari = t1.addVertex("class:Car");
        ferrari.setProperty("name", "Ferrari Modena");

        luca.addEdge("Owns", ferrari);

        OrientVertex mercedes = t1.addVertex("class:Car");
        mercedes.setProperty("name", "Mercedes");

        t1.commit();

        final CountDownLatch threadLatch = new CountDownLatch(threadsCount);
        final CountDownLatch mainLatch = new CountDownLatch(threadsCount);

        for (int i = 0; i < threadsCount; i++) {
            service.execute(() -> {
                ODatabaseDocumentTx tx = factory.openDatabase();
                ODatabaseRecordThreadLocal.INSTANCE.set(tx);

                OrientGraph t2 = factory.graph();
                t2.begin();
                Vertex luca1 = t2.getVertices("Person.name", "Luca").iterator().next();
                Vertex mercedes1 = t2.getVertices("Car.name", "Mercedes").iterator().next();
                luca1.getEdges(Direction.OUT, "Owns").forEach(t2::removeEdge);
                luca1.addEdge("Owns", mercedes1);
                threadLatch.countDown();
                try {
                    threadLatch.await();
                    t2.commit();
                } catch (InterruptedException e) {
                    throw new RuntimeException(e);
                } finally {
                    mainLatch.countDown();
                }
            });
        }
        mainLatch.await();
    }

And the same exception from each of thread:

Exception in thread "pool-3-thread-5" Exception in thread "pool-3-thread-9" com.orientechnologies.orient.core.exception.ORecordNotFoundException: The record with id '#33:45' not found
	at com.orientechnologies.orient.core.record.ORecordAbstract.reload(ORecordAbstract.java:266)
	at com.orientechnologies.orient.core.record.impl.ODocument.reload(ODocument.java:666)
	at com.orientechnologies.orient.core.record.impl.ODocument.reload(ODocument.java:75)
	at com.orientechnologies.orient.core.record.ORecordAbstract.reload(ORecordAbstract.java:252)
	at com.orientechnologies.orient.core.record.ORecordAbstract.reload(ORecordAbstract.java:248)
	at com.orientechnologies.orient.core.index.OClassIndexManager.onRecordBeforeDelete(OClassIndexManager.java:364)
	at com.orientechnologies.orient.core.hook.ODocumentHookAbstract.onTrigger(ODocumentHookAbstract.java:263)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.callbackHooks(ODatabaseDocumentTx.java:966)
	at com.orientechnologies.orient.core.tx.OTransactionOptimistic.addRecord(OTransactionOptimistic.java:291)
	at com.orientechnologies.orient.server.tx.OTransactionOptimisticProxy.begin(OTransactionOptimisticProxy.java:148)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.begin(ODatabaseDocumentTx.java:1507)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.commit(ONetworkProtocolBinary.java:1084)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.executeRequest(ONetworkProtocolBinary.java:389)
	at com.orientechnologies.orient.server.network.protocol.binary.OBinaryNetworkProtocolAbstract.execute(OBinaryNetworkProtocolAbstract.java:220)
	at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:69)
Caused by: com.orientechnologies.orient.core.exception.ORecordNotFoundException: Record with rid #33:45 was not found in database
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.reload(ODatabaseDocumentTx.java:1459)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.reload(ODatabaseDocumentTx.java:117)
	at com.orientechnologies.orient.core.record.ORecordAbstract.reload(ORecordAbstract.java:260)
	... 14 more

**Comment by profic** [comment]
And with 2 threads I got correct message and exception:

Exception in thread "pool-3-thread-1" com.orientechnologies.orient.core.exception.OConcurrentModificationException: Cannot UPDATE the record #31:26 because the version is not the latest. Probably you are updating an old record or it has been modified by another user (db=v78 your=v77)
	at com.orientechnologies.orient.core.conflict.OVersionRecordConflictStrategy.checkVersions(OVersionRecordConflictStrategy.java:55)
	at com.orientechnologies.orient.core.conflict.OVersionRecordConflictStrategy.onUpdate(OVersionRecordConflictStrategy.java:42)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.checkAndIncrementVersion(OAbstractPaginatedStorage.java:2020)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.doUpdateRecord(OAbstractPaginatedStorage.java:1657)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.commitEntry(OAbstractPaginatedStorage.java:2105)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.commit(OAbstractPaginatedStorage.java:917)
	at com.orientechnologies.orient.core.tx.OTransactionOptimistic.doCommit(OTransactionOptimistic.java:483)
	at com.orientechnologies.orient.core.tx.OTransactionOptimistic.commit(OTransactionOptimistic.java:147)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.commit(ODatabaseDocumentTx.java:2376)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.commit(ODatabaseDocumentTx.java:2346)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.commit(ONetworkProtocolBinary.java:1087)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.executeRequest(ONetworkProtocolBinary.java:389)
	at com.orientechnologies.orient.server.network.protocol.binary.OBinaryNetworkProtocolAbstract.execute(OBinaryNetworkProtocolAbstract.java:220)
	at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:69)

**Comment by lvca** [comment]
Please could you retry with 2.0.7?

**Comment by tglman** [comment]
no reply, i'm going to close this, reopen it if you can reproduce it again
