### ISSUE TITLE
OConcurrentModificationException while  creating relations between verticies

### ISSUE THREAD

**Issue by profic** [orientechnologies/orientdb#3761]
I created one instance of class Car with name "Mercedes" and want to create a relation between this car and two instances of class Person. Test throws an exception: OConcurrentModificationException. How can I avoid it and create as many edges as I want from many Persons to the same vertex Car?

Thanks, Vlad

        @Test
        public void testInsertFromDifferentThreads() throws InterruptedException {

        int threadsCount = 2;
        ExecutorService service = Executors.newFixedThreadPool(threadsCount);

        OrientGraph t1 = factory.graph();
        t1.begin();
        t1.getVerticesOfClass("Person").forEach(t1::removeVertex);
        t1.commit();

        t1.begin();
        OrientVertex mercedes = t1.addVertex("class:Car");
        mercedes.setProperty("name", "Mercedes");
        t1.commit();

        final CountDownLatch threadLatch = new CountDownLatch(threadsCount);
        final CountDownLatch mainLatch = new CountDownLatch(threadsCount);

        for (int i = 0; i < threadsCount; i++) {
            service.execute(() -> {
                ODatabaseDocumentTx tx = factory.openDatabase();
                ODatabaseRecordThreadLocal.INSTANCE.set(tx);

                OrientGraph t2 = factory.graph();
                t2.begin();

                OrientVertex luca = t2.addVertex("class:Person");
                luca.setProperty("name", "Luca");

                Vertex mercedes1 = t2.getVertices("Car.name", "Mercedes").iterator().next();
                luca.addEdge("Owns", mercedes1);

                threadLatch.countDown();
                try {
                    threadLatch.await();
                    t2.commit();
                } catch (InterruptedException e) {
                    throw new RuntimeException(e);
                } finally {
                    mainLatch.countDown();
                }
            });
        }
        mainLatch.await();

        assertEquals(threadsCount, t1.countVertices("Person"));
    }

Stacktrace:

Exception in thread "pool-3-thread-1" com.orientechnologies.orient.core.exception.OConcurrentModificationException: Cannot UPDATE the record #32:2 because the version is not the latest. Probably you are updating an old record or it has been modified by another user (db=v62 your=v61)
	at com.orientechnologies.orient.core.conflict.OVersionRecordConflictStrategy.checkVersions(OVersionRecordConflictStrategy.java:55)
	at com.orientechnologies.orient.core.conflict.OVersionRecordConflictStrategy.onUpdate(OVersionRecordConflictStrategy.java:42)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.checkAndIncrementVersion(OAbstractPaginatedStorage.java:2020)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.doUpdateRecord(OAbstractPaginatedStorage.java:1657)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.commitEntry(OAbstractPaginatedStorage.java:2105)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.commit(OAbstractPaginatedStorage.java:917)
	at com.orientechnologies.orient.core.tx.OTransactionOptimistic.doCommit(OTransactionOptimistic.java:483)
	at com.orientechnologies.orient.core.tx.OTransactionOptimistic.commit(OTransactionOptimistic.java:147)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.commit(ODatabaseDocumentTx.java:2376)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.commit(ODatabaseDocumentTx.java:2346)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.commit(ONetworkProtocolBinary.java:1087)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.executeRequest(ONetworkProtocolBinary.java:389)
	at com.orientechnologies.orient.server.network.protocol.binary.OBinaryNetworkProtocolAbstract.execute(OBinaryNetworkProtocolAbstract.java:220)
	at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:69)

**Comment by profic** [comment]
Is there any updates with this issue?

**Comment by lvca** [comment]
@profic This seems the classic case where you should manage the exception and retry. Isn't it?

**Comment by profic** [comment]
@lvca I have done it as you suggested. Now my test looks like:

    @Test
    public void testInsertFromDifferentThreads() throws InterruptedException {

        int threadsCount = 10;
        ExecutorService service = Executors.newFixedThreadPool(threadsCount);

        for (int x = 0; x < 100; x++) {

            OrientGraph t1 = factory.graph();
            t1.begin();
            t1.getVerticesOfClass("Person").forEach(t1::removeVertex);
            t1.getVerticesOfClass("Car").forEach(t1::removeVertex);
            t1.commit();

            t1.begin();
            OrientVertex mercedes = t1.addVertex("class:Car");
            mercedes.setProperty("name", "Mercedes");
            t1.commit();

            final CountDownLatch threadLatch = new CountDownLatch(threadsCount);
            final CountDownLatch mainLatch = new CountDownLatch(threadsCount);

            for (int i = 0; i < threadsCount; i++) {
                service.execute(() -> {
                    ODatabaseDocumentTx tx = factory.openDatabase();
                    ODatabaseRecordThreadLocal.INSTANCE.set(tx);

                    OrientGraph t2 = factory.graph();
                    Vertex mercedes1 = null;
                    Iterator<Vertex> iter = t2.getVertices("Car.name", "Mercedes").iterator();
                    boolean hasNext = iter.hasNext();
                    try {
                        mercedes1 = iter.next();
                    } catch (Exception e) {
                        System.out.println("no such element, but: " + hasNext);
                    }
                    while (true) {
                        try {
                            t2.begin();
                            OrientVertex luca = t2.addVertex("class:Person");
                            luca.setProperty("name", "Luca");

                            luca.addEdge("Owns", mercedes1);

                            awaitAndCountDown(threadLatch);
                            t2.commit();
                            System.out.println("commit successful");
                            mainLatch.countDown();
                            break;
                        } catch (OConcurrentModificationException e) {
                            System.out.println("try to commit again");
                            t2.rollback();
                        } catch (Exception ex) {
                            ex.printStackTrace();
                            mainLatch.countDown();
                            break;
                        }
                    }
                    t2.shutdown();
                });
            }

            mainLatch.await();

            assertEquals(threadsCount, t1.countVertices("Person"));
        }
    }


Now I'm getting another exception when I'm trying to rollback ( t2.rollback ):

Exception in thread "pool-3-thread-8" com.orientechnologies.orient.core.exception.ODatabaseException: Database instance has been released to the pool. Get another database instance from the pool with the right username and password
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTxPooled.checkOpeness(ODatabaseDocumentTxPooled.java:138)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.rollback(ODatabaseDocumentTx.java:2425)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.rollback(ODatabaseDocumentTx.java:2420)
	at com.tinkerpop.blueprints.impls.orient.OrientTransactionalGraph.rollback(OrientTransactionalGraph.java:176)
	at com.edifecs.platform.df.dao.orientdb.OrientDBTest.lambda$testInsertFromDifferentThreads$0(OrientDBTest.java:147)
	at com.edifecs.platform.df.dao.orientdb.OrientDBTest$$Lambda$16/876945112.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by profic** [comment]
Ok, now I catch an eception and retry again. When O run test for 1000 records, I get about 200 concurrent modification exception, but when I run test second time and try to add more edges and vertices, there are no exceptions at all and the version of single vertex to which I create edges does'n increment.

**Comment by tglman** [comment]
@profic this is due to the use of the (ridbag)[http://www.orientechnologies.com/docs/last/RidBag.html] if you set  RID_BAG_EMBEDDED_TO_SBTREEBONSAI_THRESHOLD to 0 this should never happen but be aware that is a database settings and you may don't want this behaviour in other classes, just read the documentation for more info ;)
