### ISSUE TITLE
Strange behaviour of transactions spanning a dynamic hook addition

### ISSUE THREAD

**Issue by nharraud** [orientechnologies/orientdb#3763]
Hi,
I was curious to see what happens when a dynamic hook is added as a transaction is running. The result is quite surprising.

The test is simple. There are two scripts, let's call them client1 and client2.

client1:
- create a database 'mydb'
- add a class 'MyClass' extending OTriggered
- insert an object { myField: 'oldValue' } of type 'MyClass'
- add a hook `print('\\nDOC READ "' + doc.field('myField') + '"\\n')` to 'MyClass' as onAfterRead. This will slow down the next SQL batch.
- send an SQL BATCH:
```
   REQUEST: BEGIN
     LET firstObj = SELECT * FROM myclass WHERE myField = "oldValue"
     LET middleObj0 = SELECT * FROM myclass WHERE myField = "oldValue0"
     LET middleObj1 = SELECT * FROM myclass WHERE myField = "oldValue1"
     ... (500 selects in order to slow the batch)
     LET middleObj498 = SELECT * FROM myclass WHERE myField = "oldValue498"
     LET middleObj499 = SELECT * FROM myclass WHERE myField = "oldValue499"
     LET lastObj = SELECT * FROM myclass WHERE myField = "oldValue"
    COMMIT RETRY 100
```
- wait for the returned values firstObj and lastObj

client2:
- add a hook `doc.field('myField', 'newReadValue!!!');` to 'MyClass' as onBeforeRead

The test scenario is:
- run script client1
- when you see the server starting to print  `DOC READ "oldValue"`, which means that the server is executing the batch, run client2

Then the server log changes and I see this:

```
...
DOC READ "oldValue"

DOC READ "oldValue"

DOC READ "oldValue"

DOC READ "oldValue"

DOC READ "oldValue"

DOC READ "oldValue"
{db=mydb} Error on fetching record during browsing. The record has been skipped
com.orientechnologies.orient.core.exception.ODatabaseException: Error on retrieving record #11:0 (cluster: myclass)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.executeReadRecord(ODatabaseDocumentTx.java:1605)
	at com.orientechnologies.orient.core.tx.OTransactionOptimistic.loadRecord(OTransactionOptimistic.java:226)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.load(ODatabaseDocumentTx.java:1437)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.load(ODatabaseDocumentTx.java:117)
	at com.orientechnologies.orient.core.iterator.OIdentifiableIterator.readCurrentRecord(OIdentifiableIterator.java:278)
	at com.orientechnologies.orient.core.iterator.ORecordIteratorClusters.begin(ORecordIteratorClusters.java:285)
	at com.orientechnologies.orient.core.iterator.ORecordIteratorClass.config(ORecordIteratorClass.java:138)
	at com.orientechnologies.orient.core.iterator.ORecordIteratorClass.<init>(ORecordIteratorClass.java:82)
	at com.orientechnologies.orient.core.sql.OCommandExecutorSQLResultsetAbstract.searchInClasses(OCommandExecutorSQLResultsetAbstract.java:447)
	at com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.searchInClasses(OCommandExecutorSQLSelect.java:768)
	at com.orientechnologies.orient.core.sql.OCommandExecutorSQLResultsetAbstract.assignTarget(OCommandExecutorSQLResultsetAbstract.java:194)
	at com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.assignTarget(OCommandExecutorSQLSelect.java:438)
	at com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.executeSearch(OCommandExecutorSQLSelect.java:420)
	at com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.execute(OCommandExecutorSQLSelect.java:391)
	at com.orientechnologies.orient.core.sql.OCommandExecutorSQLDelegate.execute(OCommandExecutorSQLDelegate.java:64)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.executeCommand(OAbstractPaginatedStorage.java:1184)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.command(OAbstractPaginatedStorage.java:1173)
	at com.orientechnologies.orient.core.command.OCommandRequestTextAbstract.execute(OCommandRequestTextAbstract.java:63)
	at com.orientechnologies.orient.core.command.script.OCommandExecutorScript.executeSQLScript(OCommandExecutorScript.java:192)
	at com.orientechnologies.orient.core.command.script.OCommandExecutorScript.executeSQL(OCommandExecutorScript.java:138)
	at com.orientechnologies.orient.core.command.script.OCommandExecutorScript.executeInContext(OCommandExecutorScript.java:82)
	at com.orientechnologies.orient.core.command.script.OCommandExecutorScript.execute(OCommandExecutorScript.java:73)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.executeCommand(OAbstractPaginatedStorage.java:1184)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.command(OAbstractPaginatedStorage.java:1173)
	at com.orientechnologies.orient.core.command.OCommandRequestTextAbstract.execute(OCommandRequestTextAbstract.java:63)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.command(ONetworkProtocolBinary.java:1178)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.executeRequest(ONetworkProtocolBinary.java:385)
	at com.orientechnologies.orient.server.network.protocol.binary.OBinaryNetworkProtocolAbstract.execute(OBinaryNetworkProtocolAbstract.java:220)
	at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:69)
Caused by: java.lang.IllegalArgumentException: Script pool for database 'mydb' is not configured
	at com.orientechnologies.orient.core.command.script.OScriptManager.releaseDatabaseEngine(OScriptManager.java:215)
	at com.orientechnologies.orient.core.db.record.OClassTrigger.executeFunction(OClassTrigger.java:322)
	at com.orientechnologies.orient.core.db.record.OClassTrigger.onRecordAfterRead(OClassTrigger.java:123)
	at com.orientechnologies.orient.core.hook.ODocumentHookAbstract.onTrigger(ODocumentHookAbstract.java:236)
	at com.orientechnologies.orient.core.db.record.OClassTrigger.onTrigger(OClassTrigger.java:185)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.callbackHooks(ODatabaseDocumentTx.java:966)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.executeReadRecord(ODatabaseDocumentTx.java:1563)
	... 28 more

DOC READ "newReadValue!!!"

DOC READ "newReadValue!!!"

DOC READ "newReadValue!!!"
...
```

The client1 script ends without any error but returned "firstObj" and "lastObj" are different:
firstObj:
```
 {
  "@type": "d",
  "@class": "myclass",
  "myField": "newReadValue!!!",
  "@rid": "#11:0"
 }
```
lastObj:
```
 {
  "classId": -2,
  "value": null
 }
```

When I run client1 without running client2 the server logs do not show any exception and lastObj is the same as firstObj.

I used "oriento" library for my tests and can provide the scripts. I preferred giving the gist if it than the code as it was easier to read.
The OrientDB server deployment I am using is a v2.0.4 and publicly accessible on docker registry: https://registry.hub.docker.com/u/joaodubas/orientdb/

I suppose that this is a bug. What should be the correct behaviour in this situation? Do transaction check the class's version and rollback when it conflicts?

**Comment by tglman** [comment]
hi @nharraud,
As today we don't support the install of hooks while transaction is running, it shouldn't be a huge issue, because usually install of hooks are done in phase of "deploy", not when the system is under load,
we don't have in the plan to support this right now, it may be supported in future.

pushing forward.

**Comment by nharraud** [comment]
Hi @tglman,
Thank you, this is a clear answer.
In case you wonder why I tried to do this: I wanted to use hooks as a mean to replicate the data in another storage system (Elasticsearch). Dynamically adding hooks would have enabled me to change the mapping at run time. I will search for another way to do it.

**Comment by lvca** [comment]
I'd rather close this issue, avoiding to keep all these hundreds enhancements to cover any possible cases. Better set limitations.
