### ISSUE TITLE
upgrade from 2.0.4 to 2.0.5 npe in getInvolvedClusters

### ISSUE THREAD

**Issue by p1tz** [orientechnologies/orientdb#3764]
happens on the server side via sql

```java
SEVERE: Cannot route COMMAND operation to the distributed node
java.lang.NullPointerException
	at com.orientechnologies.orient.core.sql.OCommandExecutorSQLAbstract.getInvolvedClustersOfClasses(OCommandExecutorSQLAbstract.java:155)
	at com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.getInvolvedClusters(OCommandExecutorSQLSelect.java:316)
	at com.orientechnologies.orient.server.distributed.ODistributedStorage.command(ODistributedStorage.java:267)
	at com.orientechnologies.orient.core.sql.query.OSQLQuery.run(OSQLQuery.java:71)
	at com.orientechnologies.orient.core.sql.query.OSQLSynchQuery.run(OSQLSynchQuery.java:85)
	at com.orientechnologies.orient.core.query.OQueryAbstract.execute(OQueryAbstract.java:33)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.command(ONetworkProtocolBinary.java:1178)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.executeRequest(ONetworkProtocolBinary.java:385)
	at com.orientechnologies.orient.server.network.protocol.binary.OBinaryNetworkProtocolAbstract.execute(OBinaryNetworkProtocolAbstract.java:220)
	at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:69)
```

**Comment by luigidellaquila** [comment]
How can I replicate this? Do you have a deterministic way to do this or a test case?

Thanks

**Comment by p1tz** [comment]
I do not, I am now using 2.1-rc3 and I haven't seen it again.
