### ISSUE TITLE
Adjusting hazelcast timeouts and lack of errors in async mode

### ISSUE THREAD

**Issue by gemmell** [orientechnologies/orientdb#3765]
So we are now hitting the next set of woes in distributed mode. Essentially in our setup we have 2 servers on opposite sides of the world and we are doing a write to one of them. When the config is:
```json
{"@type":"d","@version":0,"version":40,"autoDeploy":true,"hotAlignment":false,"executionMode":"asynchronous","readQuorum":1,"writeQuorum":2,"failureAvailableNodesLessQuorum":false,"readYourWrites":true,"clusters":{"...
```

We get absolutely no errors in orient, the client believes that it all wrote OK, but it is not there in the database. If we turn the executionMode back to "undefined" we get the errors outlined below - i.e. a timeout. Firstly do you know which hazelcast parameter I need to tweak to increase the timeout? Secondly, it seems to think it's not executing on the other end and is rolling back.... why would it not find the other end executing it? I will set the quorum to 1 but I don't know that it is a solution. I would also like to highlight again that when it's in async mode we don't seem to get any log events but it still doesn't save. Here are our errors:

```
2015-03-13 08:30:28:898 WARNING [172.31.6.12]:5701 [orientdb] [3.3] No response for 20000 ms. BasicInvocationFuture{invocation=BasicInvocation{ serviceName='hz:impl:queueService', op=com.hazelcast.queue.impl.OfferOperation@4cf1a32e, partitionId=23, replicaIndex=0, tryCount=250, tryPauseMillis=500, invokeCount=1, callTimeout=10000, target=Address[10.0.1.96]:5701}, done=false} [BasicInvocation]
2015-03-13 08:30:28:898 WARNING [172.31.6.12]:5701 [orientdb] [3.3] Asking if operation execution has been started: BasicInvocationFuture{invocation=BasicInvocation{ serviceName='hz:impl:queueService', op=com.hazelcast.queue.impl.OfferOperation@4cf1a32e, partitionId=23, replicaIndex=0, tryCount=250, tryPauseMillis=500, invokeCount=1, callTimeout=10000, target=Address[10.0.1.96]:5701}, done=false} [BasicInvocation][172.31.6.12]:5701 [orientdb] [3.3] While asking 'is-executing': BasicInvocationFuture{invocation=BasicInvocation{ serviceName='hz:impl:queueService', op=com.hazelcast.queue.impl.OfferOperation@4cf1a32e, partitionId=23, replicaIndex=0, tryCount=250, tryPauseMillis=500, invokeCount=1, callTimeout=10000, target=Address[10.0.1.96]:5701}, done=false}
java.util.concurrent.TimeoutException: Call BasicInvocation{ serviceName='hz:impl:queueService', op=com.hazelcast.spi.impl.IsStillExecutingOperation@48aeeb11, partitionId=-1, replicaIndex=0, tryCount=0, tryPauseMillis=0, invokeCount=1, callTimeout=5000, target=Address[10.0.1.96]:5701} encountered a timeout
        at com.hazelcast.spi.impl.BasicInvocationFuture.resolveApplicationResponse(BasicInvocationFuture.java:321)
        at com.hazelcast.spi.impl.BasicInvocationFuture.resolveApplicationResponseOrThrowException(BasicInvocationFuture.java:289)
        at com.hazelcast.spi.impl.BasicInvocationFuture.get(BasicInvocationFuture.java:181)
        at com.hazelcast.spi.impl.BasicInvocationFuture.isOperationExecuting(BasicInvocationFuture.java:390)
        at com.hazelcast.spi.impl.BasicInvocationFuture.waitForResponse(BasicInvocationFuture.java:228)
        at com.hazelcast.spi.impl.BasicInvocationFuture.get(BasicInvocationFuture.java:180)
        at com.hazelcast.spi.impl.BasicInvocationFuture.get(BasicInvocationFuture.java:160)
        at com.hazelcast.queue.impl.proxy.QueueProxySupport.invokeAndGet(QueueProxySupport.java:173)
        at com.hazelcast.queue.impl.proxy.QueueProxySupport.offerInternal(QueueProxySupport.java:91)
        at com.hazelcast.queue.impl.proxy.QueueProxyImpl.offer(QueueProxyImpl.java:76)
        at com.orientechnologies.orient.server.hazelcast.OHazelcastDistributedDatabase.send2Nodes(OHazelcastDistributedDatabase.java:175)
        at com.orientechnologies.orient.server.hazelcast.OHazelcastPlugin.sendRequest(OHazelcastPlugin.java:350)
        at com.orientechnologies.orient.server.distributed.ODistributedStorage$2.run(ODistributedStorage.java:160)

2015-03-13 08:30:33:899 WARNING [172.31.6.12]:5701 [orientdb] [3.3] 'is-executing': false -> BasicInvocationFuture{invocation=BasicInvocation{ serviceName='hz:impl:queueService', op=com.hazelcast.queue.impl.OfferOperation@4cf1a32e, partitionId=23, replicaIndex=0, tryCount=250, tryPauseMillis=500, invokeCount=1, callTimeout=10000, target=Address[10.0.1.96]:5701}, done=false} [BasicInvocation][Sydney] Error on executing asynch operation
com.orientechnologies.orient.server.distributed.ODistributedException: Error on executing distributed request (id=310 from=Sydney task=tx userName=) against database 'Ice.[]' to nodes [Frankfurt]
        at com.orientechnologies.orient.server.hazelcast.OHazelcastDistributedDatabase.send2Nodes(OHazelcastDistributedDatabase.java:194)
        at com.orientechnologies.orient.server.hazelcast.OHazelcastPlugin.sendRequest(OHazelcastPlugin.java:350)
        at com.orientechnologies.orient.server.distributed.ODistributedStorage$2.run(ODistributedStorage.java:160)
Caused by: com.hazelcast.core.OperationTimeoutException: No response for 20000 ms. Aborting invocation! BasicInvocationFuture{invocation=BasicInvocation{ serviceName='hz:impl:queueService', op=com.hazelcast.queue.impl.OfferOperation@4cf1a32e, partitionId=23, replicaIndex=0, tryCount=250, tryPauseMillis=500, invokeCount=1, callTimeout=10000, target=Address[10.0.1.96]:5701}, done=false} Not all backups have completed  backups-expected:0 backups-completed: 0
        at com.hazelcast.spi.impl.BasicInvocationFuture.newOperationTimeoutException(BasicInvocationFuture.java:272)
        at com.hazelcast.spi.impl.BasicInvocationFuture.waitForResponse(BasicInvocationFuture.java:233)
        at com.hazelcast.spi.impl.BasicInvocationFuture.get(BasicInvocationFuture.java:180)
        at com.hazelcast.spi.impl.BasicInvocationFuture.get(BasicInvocationFuture.java:160)
        at com.hazelcast.queue.impl.proxy.QueueProxySupport.invokeAndGet(QueueProxySupport.java:173)
        at com.hazelcast.queue.impl.proxy.QueueProxySupport.offerInternal(QueueProxySupport.java:91)
        at com.hazelcast.queue.impl.proxy.QueueProxyImpl.offer(QueueProxyImpl.java:76)
        at com.orientechnologies.orient.server.hazelcast.OHazelcastDistributedDatabase.send2Nodes(OHazelcastDistributedDatabase.java:175)
        at com.orientechnologies.orient.server.hazelcast.OHazelcastPlugin.sendRequest(OHazelcastPlugin.java:350)
        at com.orientechnologies.orient.server.distributed.ODistributedStorage$2.run(ODistributedStorage.java:160)
        at ------ End remote and begin local stack-trace ------.(Unknown Source)
        at com.hazelcast.spi.impl.BasicInvocationFuture.resolveApplicationResponse(BasicInvocationFuture.java:356)
        at com.hazelcast.spi.impl.BasicInvocationFuture.resolveApplicationResponseOrThrowException(BasicInvocationFuture.java:289)
        at com.hazelcast.spi.impl.BasicInvocationFuture.get(BasicInvocationFuture.java:181)
        at com.hazelcast.spi.impl.BasicInvocationFuture.get(BasicInvocationFuture.java:160)
        at com.hazelcast.queue.impl.proxy.QueueProxySupport.invokeAndGet(QueueProxySupport.java:173)
        at com.hazelcast.queue.impl.proxy.QueueProxySupport.offerInternal(QueueProxySupport.java:91)
        at com.hazelcast.queue.impl.proxy.QueueProxyImpl.offer(QueueProxyImpl.java:76)
        at com.orientechnologies.orient.server.hazelcast.OHazelcastDistributedDatabase.send2Nodes(OHazelcastDistributedDatabase.java:175)
        ... 2 more

2015-03-13 08:31:45:875 WARNING [172.31.6.12]:5701 [orientdb] [3.3] No response for 20001 ms. BasicInvocationFuture{invocation=BasicInvocation{ serviceName='hz:impl:queueService', op=com.hazelcast.queue.impl.OfferOperation@7aca1028, partitionId=23, replicaIndex=0, tryCount=250, tryPauseMillis=500, invokeCount=1, callTimeout=10000, target=Address[10.0.1.96]:5701}, done=false} [BasicInvocation]
2015-03-13 08:31:45:875 WARNING [172.31.6.12]:5701 [orientdb] [3.3] Asking if operation execution has been started: BasicInvocationFuture{invocation=BasicInvocation{ serviceName='hz:impl:queueService', op=com.hazelcast.queue.impl.OfferOperation@7aca1028, partitionId=23, replicaIndex=0, tryCount=250, tryPauseMillis=500, invokeCount=1, callTimeout=10000, target=Address[10.0.1.96]:5701}, done=false} [BasicInvocation][172.31.6.12]:5701 [orientdb] [3.3] While asking 'is-executing': BasicInvocationFuture{invocation=BasicInvocation{ serviceName='hz:impl:queueService', op=com.hazelcast.queue.impl.OfferOperation@7aca1028, partitionId=23, replicaIndex=0, tryCount=250, tryPauseMillis=500, invokeCount=1, callTimeout=10000, target=Address[10.0.1.96]:5701}, done=false}
java.util.concurrent.TimeoutException: Call BasicInvocation{ serviceName='hz:impl:queueService', op=com.hazelcast.spi.impl.IsStillExecutingOperation@5431f304, partitionId=-1, replicaIndex=0, tryCount=0, tryPauseMillis=0, invokeCount=1, callTimeout=5000, target=Address[10.0.1.96]:5701} encountered a timeout
        at com.hazelcast.spi.impl.BasicInvocationFuture.resolveApplicationResponse(BasicInvocationFuture.java:321)
        at com.hazelcast.spi.impl.BasicInvocationFuture.resolveApplicationResponseOrThrowException(BasicInvocationFuture.java:289)
        at com.hazelcast.spi.impl.BasicInvocationFuture.get(BasicInvocationFuture.java:181)
        at com.hazelcast.spi.impl.BasicInvocationFuture.isOperationExecuting(BasicInvocationFuture.java:390)
        at com.hazelcast.spi.impl.BasicInvocationFuture.waitForResponse(BasicInvocationFuture.java:228)
        at com.hazelcast.spi.impl.BasicInvocationFuture.get(BasicInvocationFuture.java:180)
        at com.hazelcast.spi.impl.BasicInvocationFuture.get(BasicInvocationFuture.java:160)
        at com.hazelcast.queue.impl.proxy.QueueProxySupport.invokeAndGet(QueueProxySupport.java:173)
        at com.hazelcast.queue.impl.proxy.QueueProxySupport.offerInternal(QueueProxySupport.java:91)
        at com.hazelcast.queue.impl.proxy.QueueProxyImpl.offer(QueueProxyImpl.java:76)
        at com.orientechnologies.orient.server.hazelcast.OHazelcastDistributedDatabase.send2Nodes(OHazelcastDistributedDatabase.java:175)
        at com.orientechnologies.orient.server.hazelcast.OHazelcastPlugin.sendRequest(OHazelcastPlugin.java:350)
        at com.orientechnologies.orient.server.distributed.ODistributedStorage$2.run(ODistributedStorage.java:160)

2015-03-13 08:31:50:879 WARNING [172.31.6.12]:5701 [orientdb] [3.3] 'is-executing': false -> BasicInvocationFuture{invocation=BasicInvocation{ serviceName='hz:impl:queueService', op=com.hazelcast.queue.impl.OfferOperation@7aca1028, partitionId=23, replicaIndex=0, tryCount=250, tryPauseMillis=500, invokeCount=1, callTimeout=10000, target=Address[10.0.1.96]:5701}, done=false} [BasicInvocation][Sydney] Error on executing asynch operation
com.orientechnologies.orient.server.distributed.ODistributedException: Error on executing distributed request (id=311 from=Sydney task=tx userName=) against database 'Ice.[]' to nodes [Frankfurt]
        at com.orientechnologies.orient.server.hazelcast.OHazelcastDistributedDatabase.send2Nodes(OHazelcastDistributedDatabase.java:194)
        at com.orientechnologies.orient.server.hazelcast.OHazelcastPlugin.sendRequest(OHazelcastPlugin.java:350)
        at com.orientechnologies.orient.server.distributed.ODistributedStorage$2.run(ODistributedStorage.java:160)
Caused by: com.hazelcast.core.OperationTimeoutException: No response for 20000 ms. Aborting invocation! BasicInvocationFuture{invocation=BasicInvocation{ serviceName='hz:impl:queueService', op=com.hazelcast.queue.impl.OfferOperation@7aca1028, partitionId=23, replicaIndex=0, tryCount=250, tryPauseMillis=500, invokeCount=1, callTimeout=10000, target=Address[10.0.1.96]:5701}, done=false} Not all backups have completed  backups-expected:0 backups-completed: 0
        at com.hazelcast.spi.impl.BasicInvocationFuture.newOperationTimeoutException(BasicInvocationFuture.java:272)
        at com.hazelcast.spi.impl.BasicInvocationFuture.waitForResponse(BasicInvocationFuture.java:233)
        at com.hazelcast.spi.impl.BasicInvocationFuture.get(BasicInvocationFuture.java:180)
        at com.hazelcast.spi.impl.BasicInvocationFuture.get(BasicInvocationFuture.java:160)
        at com.hazelcast.queue.impl.proxy.QueueProxySupport.invokeAndGet(QueueProxySupport.java:173)
        at com.hazelcast.queue.impl.proxy.QueueProxySupport.offerInternal(QueueProxySupport.java:91)
        at com.hazelcast.queue.impl.proxy.QueueProxyImpl.offer(QueueProxyImpl.java:76)
        at com.orientechnologies.orient.server.hazelcast.OHazelcastDistributedDatabase.send2Nodes(OHazelcastDistributedDatabase.java:175)
        at com.orientechnologies.orient.server.hazelcast.OHazelcastPlugin.sendRequest(OHazelcastPlugin.java:350)
        at com.orientechnologies.orient.server.distributed.ODistributedStorage$2.run(ODistributedStorage.java:160)
        at ------ End remote and begin local stack-trace ------.(Unknown Source)
        at com.hazelcast.spi.impl.BasicInvocationFuture.resolveApplicationResponse(BasicInvocationFuture.java:356)
        at com.hazelcast.spi.impl.BasicInvocationFuture.resolveApplicationResponseOrThrowException(BasicInvocationFuture.java:289)
        at com.hazelcast.spi.impl.BasicInvocationFuture.get(BasicInvocationFuture.java:181)
        at com.hazelcast.spi.impl.BasicInvocationFuture.get(BasicInvocationFuture.java:160)
        at com.hazelcast.queue.impl.proxy.QueueProxySupport.invokeAndGet(QueueProxySupport.java:173)
        at com.hazelcast.queue.impl.proxy.QueueProxySupport.offerInternal(QueueProxySupport.java:91)
        at com.hazelcast.queue.impl.proxy.QueueProxyImpl.offer(QueueProxyImpl.java:76)
        at com.orientechnologies.orient.server.hazelcast.OHazelcastDistributedDatabase.send2Nodes(OHazelcastDistributedDatabase.java:175)
        ... 2 more

2015-03-13 08:33:04:515 WARNING [172.31.6.12]:5701 [orientdb] [3.3] No response for 20000 ms. BasicInvocationFuture{invocation=BasicInvocation{ serviceName='hz:impl:queueService', op=com.hazelcast.queue.impl.OfferOperation@22a00d60, partitionId=23, replicaIndex=0, tryCount=250, tryPauseMillis=500, invokeCount=1, callTimeout=10000, target=Address[10.0.1.96]:5701}, done=false} [BasicInvocation]
2015-03-13 08:33:04:515 WARNING [172.31.6.12]:5701 [orientdb] [3.3] Asking if operation execution has been started: BasicInvocationFuture{invocation=BasicInvocation{ serviceName='hz:impl:queueService', op=com.hazelcast.queue.impl.OfferOperation@22a00d60, partitionId=23, replicaIndex=0, tryCount=250, tryPauseMillis=500, invokeCount=1, callTimeout=10000, target=Address[10.0.1.96]:5701}, done=false} [BasicInvocation]
2015-03-13 08:33:08:900 WARNING [172.31.6.12]:5701 [orientdb] [3.3] 'is-executing': false -> BasicInvocationFuture{invocation=BasicInvocation{ serviceName='hz:impl:queueService', op=com.hazelcast.queue.impl.OfferOperation@22a00d60, partitionId=23, replicaIndex=0, tryCount=250, tryPauseMillis=500, invokeCount=1, callTimeout=10000, target=Address[10.0.1.96]:5701}, done=false} [BasicInvocation] 
```

**Comment by lvca** [comment]
Take a look at: http://docs.hazelcast.org/docs/latest/manual/html/configurationproperties.html and try enlarging timeouts in `config/hazelcast.xml` file. About OrientDB, please set this (in orientdb-server-config.xml):

```
distributed.queueTimeout = 30000
distributed.asynchResponsesTimeout = 60000
distributed.purgeResponsesTimerDelay = 60000
distributed.commandTaskTimeout = 120000
distributed.crudTaskTimeout = 15000
```

**Comment by tobiemh** [comment]
With regards to the `"execution": "asynchronous"` problem is this similar to #3691?

In asynchronous mode, the records are synchronised to all of the other database nodes in the cluster except for the one on which the query was executed.

***

OrientDB version: 2.0.5

**Comment by gemmell** [comment]
@tobiemh Yes, I just checked the other server - it is there - so same issue as #3691 for async. Will investigate sync. The ping time is 304ms and I can connect in both directions - some of our transactions take 6 seconds to complete (!) so I was wondering if perhaps the long transactions have something to do with it. Will post back with more data soon.

**Comment by lvca** [comment]
@gemmell did you try to enlarge OrientDB and Hazelcast timeouts ?

**Comment by gemmell** [comment]
@lvca Not yet, do I set them in <properties>?
i.e 
  <entry value="30000" name="distributed.queueTimeout"/>

I did confirm my theory. If I run a very small transaction, no problems, if I run a big one, it hits this issue. In reality due to the latency (~300ms) I don't want to be running like with the write quorum like this, but async mode doesn't quite work like it should and this may be a bug (it actually checks if the other side is doing the insert and seems to think it's not).

**Comment by lvca** [comment]
Asynch mode checks if the quorum is reached, but does it in asynchronous way, while the client has the OK as soon as the local node answer OK. However I checked the timeout of transaction tasks and it's the same as for CRUD operation. So I've changed the timeout for TX (OTxTask.java) to be:

```java
  /**
   * Computes the timeout according to the transaction size.
   * 
   * @return
   */
  @Override
  public long getTimeout() {
    final long to = OGlobalConfiguration.DISTRIBUTED_CRUD_TASK_SYNCH_TIMEOUT.getValueAsLong();
    return to + ((to / 2) * tasks.size());
  }
```

it's in 2.0.6-SNAPSHOT and 2.1-SNAPSHOT.

**Comment by gemmell** [comment]
So I should try 2.0.6 snapshot and not change any configs?

**Comment by lvca** [comment]
Yes.

**Comment by lvca** [comment]
Do you have any news on this?

**Comment by gemmell** [comment]
Seems to still occur. We are just making sure that we really did deploy the one built from the source (pretty sure we did).

**Comment by lvca** [comment]
Ok, so I'm waiting for you test with such settings

**Comment by gemmell** [comment]
We currently hit http://www.prjhub.com/#/issues/3797 so I can test after that.

**Comment by lvca** [comment]
@gemmell, now that issue prjhub 3797 is fixed (please confirm it), could you test this?

**Comment by lvca** [comment]
Hey @gemmell, any news on this? I'm closing it. In case, please reopen this one.
