### ISSUE TITLE
Cannot route READ_RECORD operation for #-1:-2 to the distributed node

### ISSUE THREAD

**Issue by gemmell** [orientechnologies/orientdb#3770]
Using 2.0.x branch (soon to become 2.0.6), we are getting the following error again.

Cannot route READ_RECORD operation for #-1:-2 to the distributed node
```java.lang.IllegalArgumentException: Cannot read record #-1:-2 since the position is invalid in database 'Ice'
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.readRecord(OAbstractPaginatedStorage.java:1414)
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.readRecord(OAbstractPaginatedStorage.java:694)
        at com.orientechnologies.orient.server.distributed.ODistributedStorage$5.call(ODistributedStorage.java:537)
        at com.orientechnologies.orient.server.distributed.ODistributedAbstractPlugin.runInDistributedMode(ODistributedAbstractPlugin.java:75)
        at com.orientechnologies.orient.server.distributed.ODistributedStorage.readRecord(ODistributedStorage.java:534)
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.executeReadRecord(ODatabaseDocumentTx.java:1572)
        at com.orientechnologies.orient.core.tx.OTransactionOptimistic.loadRecord(OTransactionOptimistic.java:226)
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.load(ODatabaseDocumentTx.java:1424)
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.load(ODatabaseDocumentTx.java:117)
        at com.orientechnologies.orient.core.id.ORecordId.getRecord(ORecordId.java:313)
        at com.orientechnologies.orient.core.db.record.ORecordLazySet.convertLinks2Records(ORecordLazySet.java:146)
        at com.orientechnologies.orient.server.distributed.task.OTxTask.execute(OTxTask.java:100)
        at com.orientechnologies.orient.server.hazelcast.OHazelcastPlugin.executeOnLocalNode(OHazelcastPlugin.java:757)
        at com.orientechnologies.orient.server.hazelcast.ODistributedWorker.onMessage(ODistributedWorker.java:300)
        at com.orientechnologies.orient.server.hazelcast.ODistributedWorker.run(ODistributedWorker.java:121)
Error on distributed transaction commit
com.orientechnologies.orient.core.exception.ODatabaseException: Error on retrieving record #-1:-2 (cluster: null)
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.executeReadRecord(ODatabaseDocumentTx.java:1605)
        at com.orientechnologies.orient.core.tx.OTransactionOptimistic.loadRecord(OTransactionOptimistic.java:226)
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.load(ODatabaseDocumentTx.java:1424)
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.load(ODatabaseDocumentTx.java:117)
        at com.orientechnologies.orient.core.id.ORecordId.getRecord(ORecordId.java:313)
        at com.orientechnologies.orient.core.db.record.ORecordLazySet.convertLinks2Records(ORecordLazySet.java:146)
        at com.orientechnologies.orient.server.distributed.task.OTxTask.execute(OTxTask.java:100)
        at com.orientechnologies.orient.server.hazelcast.OHazelcastPlugin.executeOnLocalNode(OHazelcastPlugin.java:757)
        at com.orientechnologies.orient.server.hazelcast.ODistributedWorker.onMessage(ODistributedWorker.java:300)
        at com.orientechnologies.orient.server.hazelcast.ODistributedWorker.run(ODistributedWorker.java:121)
Caused by: com.orientechnologies.orient.core.exception.OStorageException: Cannot route READ_RECORD operation for #-1:-2 to the distributed node
        at com.orientechnologies.orient.server.distributed.ODistributedStorage.handleDistributedException(ODistributedStorage.java:1287)
        at com.orientechnologies.orient.server.distributed.ODistributedStorage.readRecord(ODistributedStorage.java:557)
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.executeReadRecord(ODatabaseDocumentTx.java:1572)
        ... 9 more
Caused by: java.lang.IllegalArgumentException: Cannot read record #-1:-2 since the position is invalid in database 'Ice'
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.readRecord(OAbstractPaginatedStorage.java:1414)
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.readRecord(OAbstractPaginatedStorage.java:694)
        at com.orientechnologies.orient.server.distributed.ODistributedStorage$5.call(ODistributedStorage.java:537)
        at com.orientechnologies.orient.server.distributed.ODistributedAbstractPlugin.runInDistributedMode(ODistributedAbstractPlugin.java:75)
        at com.orientechnologies.orient.server.distributed.ODistributedStorage.readRecord(ODistributedStorage.java:534)
        ... 10 more```

**Comment by gemmell** [comment]
I should note: This is occuring on the server that it is syncing to! So we saved to the Sydney database, and we are getting this exception on the Frankfurt server.

**Comment by lvca** [comment]
What operation did you execute here?

**Comment by gemmell** [comment]
Our transactional save operation that creates a bunch of ODocuments and Links.

**Comment by gemmell** [comment]
Changed config to
`"autoDeploy":true,"hotAlignment":true,"executionMode":"synchronous","readQuorum":1,"writeQuorum":2,"failureAvailableNodesLessQuorum":false,"readYourWrites":true,`
i.e. turned off async. Now I get:
`java.lang.IllegalArgumentException: Cannot read record #-1:7565 since the position is invalid in database 'Ice'
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.readRecord(OAbstractPaginatedStorage.java:1414)
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.readRecord(OAbstractPaginatedStorage.java:694)
        at com.orientechnologies.orient.server.distributed.ODistributedStorage$5.call(ODistributedStorage.java:537)
        at com.orientechnologies.orient.server.distributed.ODistributedAbstractPlugin.runInDistributedMode(ODistributedAbstractPlugin.java:75)
        at com.orientechnologies.orient.server.distributed.ODistributedStorage.readRecord(ODistributedStorage.java:534)
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.executeReadRecord(ODatabaseDocumentTx.java:1572)
        at com.orientechnologies.orient.core.tx.OTransactionNoTx.loadRecord(OTransactionNoTx.java:80)
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.load(ODatabaseDocumentTx.java:1437)
        at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.readRecord(ONetworkProtocolBinary.java:1453)
        at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.executeRequest(ONetworkProtocolBinary.java:346)
        at com.orientechnologies.orient.server.network.protocol.binary.OBinaryNetworkProtocolAbstract.execute(OBinaryNetworkProtocolAbstract.java:220)
        at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:69)
Sent run-time exception to the client /172.17.0.181:50995: com.orientechnologies.orient.core.exception.ODatabaseException: Error on retrieving record #-1:7565 (cluster: null)
com.orientechnologies.orient.core.exception.ODatabaseException: Error on retrieving record #-1:7565 (cluster: null)
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.executeReadRecord(ODatabaseDocumentTx.java:1605)
        at com.orientechnologies.orient.core.tx.OTransactionNoTx.loadRecord(OTransactionNoTx.java:80)
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.load(ODatabaseDocumentTx.java:1437)
        at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.readRecord(ONetworkProtocolBinary.java:1453)
        at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.executeRequest(ONetworkProtocolBinary.java:346)
        at com.orientechnologies.orient.server.network.protocol.binary.OBinaryNetworkProtocolAbstract.execute(OBinaryNetworkProtocolAbstract.java:220)
        at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:69)
Caused by: com.orientechnologies.orient.core.exception.OStorageException: Cannot route READ_RECORD operation for #-1:7565 to the distributed node
        at com.orientechnologies.orient.server.distributed.ODistributedStorage.handleDistributedException(ODistributedStorage.java:1287)
        at com.orientechnologies.orient.server.distributed.ODistributedStorage.readRecord(ODistributedStorage.java:557)
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.executeReadRecord(ODatabaseDocumentTx.java:1572)
        ... 6 more
Caused by: java.lang.IllegalArgumentException: Cannot read record #-1:7565 since the position is invalid in database 'Ice'
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.readRecord(OAbstractPaginatedStorage.java:1414)
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.readRecord(OAbstractPaginatedStorage.java:694)
        at com.orientechnologies.orient.server.distributed.ODistributedStorage$5.call(ODistributedStorage.java:537)
        at com.orientechnologies.orient.server.distributed.ODistributedAbstractPlugin.runInDistributedMode(ODistributedAbstractPlugin.java:75)
        at com.orientechnologies.orient.server.distributed.ODistributedStorage.readRecord(ODistributedStorage.java:534)
        ... 7 more
`

But this time on the server I am executing on (Sydney).

**Comment by gemmell** [comment]
It looks to me like in async mode it's actually trying to sync from the other instance (Frankfurt) back to the server the original query was executed on.

**Comment by gemmell** [comment]
Please note that these are occurring on a build after https://github.com/orientechnologies/orientdb/issues/3691 was reported as fixed.

**Comment by lvca** [comment]
Could you provide me a test case? Or tell me the operations you're executing in transaction. Also code snippet is ok.

**Comment by gemmell** [comment]
Yes, see https://github.com/orientechnologies/orientdb/issues/3690
Exact same code fails. You should probably add it to your tests.

**Comment by lvca** [comment]
@povman commented in the issue that #3690 was fixed: "Yep seems to work for us now.".

**Comment by lvca** [comment]
What I'd need is a test case that fail. Is the same as for #3690? We already tested and fixed it. Am I wrong? Please help me to understand.

**Comment by gemmell** [comment]
Yes, you fixed it, and then one of your changes since has broken it again. That exact test that we gave to you in #3690 fails with the latest code in the 2.0.x branch.

**Comment by gemmell** [comment]
To be absolutely clear, here is your test case:
Run one instance of dserver.

Use this SQL to create a database:

CREATE DATABASE remote:localhost/Test root password plocal
CREATE CLASS Client;
CREATE CLASS Matter;
Run another instance of dserver. Wait until they synchronise.

Run this java code:
```
package com.tkbt;
import com.orientechnologies.orient.core.db.document.ODatabaseDocumentPool;
import com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx;
import com.orientechnologies.orient.core.record.ORecord;
import com.orientechnologies.orient.core.record.impl.ODocument;
import com.orientechnologies.orient.core.db.OPartitionedDatabasePool;
import java.util.ArrayList;
import java.util.List;

public class Main {

    public static void main(String[] args) throws Exception {
        String id = String.valueOf(Math.random());
        ODatabaseDocumentTx db = new ODatabaseDocumentTx("remote:localhost/Test").open("root", "password");
        db.begin();
        try {
            ODocument client = new ODocument("Client");
            ODocument matter = new ODocument("Matter");
            matter.field("client", client);
            matter.field("id", id);
            List clientMatters = new ArrayList();
            clientMatters.add(matter);
            client.field("matters", clientMatters);
            client.save();
            matter.save();
            db.commit();
        } finally {
            db.close();
        }

        ODatabaseDocumentTx db2 = new ODatabaseDocumentTx("remote:localhost/Test").open("root", "password");
        db2.begin();
        try {
            ODocument matter = null;
            for (ODocument doc : db2.browseCluster("Matter")) {
                if (doc.field("id").equals(id)) {
                    matter = doc;
                    break;
                }
            }
            if (matter == null) {
                throw new Exception("Matter not found with id" + id);
            }
            matter.field("client", new ODocument());
            matter.save();
            db2.commit();
        } finally {
            db2.close();
        }
    }
}
```

**Comment by lukeworthtkbt** [comment]
It isn't failing the same way as last time. This time, the server we are connected to succeeds, but the distributed server sees an exception while it is synchronising changes.

**Comment by gemmell** [comment]
Actually, depends on whether executionMode is asynchronous or not. If it is not, then it fails in the same way.

**Comment by lukeworthtkbt** [comment]
Here is a console log of me building OrientDb from git (revision 76a3cb551b6cc1dd875b5071b407ddebe58d04e5), and then setting up two distributed servers and running our test code: http://pastebin.com/yMcnmX4S

Take note of the edit to config/default-distributed-db-config.json, as that seems necessary to make the bug happen.

The line where it says "# I am about to run our test code" is where I execute the java code from https://github.com/orientechnologies/orientdb/issues/3690#issuecomment-77081221

**Comment by gemmell** [comment]
To reproduce just follow the steps Luke has posted in postbin. Really can't make it any clearer than that.

**Comment by lvca** [comment]
Reproduced with mode = asynchronous, with synchronous worked. Working on it.

**Comment by tomer-h** [comment]
We are also encountering this issue in 2.0.5, we would rather not use snapshots in production. Any update on when 2.0.6 will be released?

**Comment by lvca** [comment]
OrientDB 2.0.6 is out
