### ISSUE TITLE
create lucene index fails from java remote 

### ISSUE THREAD

**Issue by uulu** [orientechnologies/orientdb#3780]
There is an issue where the api fails to make Lucene indexes correctly via the java api to a remote database:

### Works###
``` java
database.command(new OCommandSQL("create index "+table+".name on "+table+" (name) FULLTEXT ENGINE LUCENE"));
```
### Doesn't work###
```java
vert.createIndex(table+".name", "FULLTEXT",null,null,"LUCENE", new String[]{"name"});
```
The reason is [OPropertyIndexDefinition](https://github.com/orientechnologies/orientdb/blob/master/core/src/main/java/com/orientechnologies/orient/core/index/OPropertyIndexDefinition.java)  is adding a **STRING** field
 * _createIndexDDL_ is set to "create index test.name FULLTEXT **STRING** ENGINE LUCENE" in OIndexManagerRemote

```Stacktrace
Exception in thread "main" com.orientechnologies.orient.enterprise.channel.binary.OResponseProcessingException: Exception during response processing.
	at com.orientechnologies.orient.enterprise.channel.binary.OChannelBinaryAsynchClient.throwSerializedException(OChannelBinaryAsynchClient.java:441)
	at com.orientechnologies.orient.enterprise.channel.binary.OChannelBinaryAsynchClient.handleStatus(OChannelBinaryAsynchClient.java:396)
	at com.orientechnologies.orient.enterprise.channel.binary.OChannelBinaryAsynchClient.beginResponse(OChannelBinaryAsynchClient.java:282)
	at com.orientechnologies.orient.enterprise.channel.binary.OChannelBinaryAsynchClient.beginResponse(OChannelBinaryAsynchClient.java:171)
	at com.orientechnologies.orient.client.remote.OStorageRemote.beginResponse(OStorageRemote.java:1870)
	at com.orientechnologies.orient.client.remote.OStorageRemote.command(OStorageRemote.java:985)
	at com.orientechnologies.orient.client.remote.OStorageRemoteThread.command(OStorageRemoteThread.java:436)
	at com.orientechnologies.orient.core.command.OCommandRequestTextAbstract.execute(OCommandRequestTextAbstract.java:63)
	at com.orientechnologies.orient.core.index.OIndexManagerRemote.createIndex(OIndexManagerRemote.java:63)
	at com.orientechnologies.orient.core.index.OIndexManagerProxy.createIndex(OIndexManagerProxy.java:79)
	at com.orientechnologies.orient.core.metadata.schema.OClassImpl.createIndex(OClassImpl.java:1434)
...
Caused by: java.lang.IllegalArgumentException: No enum constant com.orientechnologies.orient.core.metadata.schema.OType.STRING ENGINE LUCENE
```

**Comment by maggiolo00** [comment]
Seems duplicate.
https://github.com/orientechnologies/orientdb/issues/2969
