### ISSUE TITLE
Commit transaction does nothing and produces no error messages

### ISSUE THREAD

**Issue by lukeworthtkbt** [orientechnologies/orientdb#3790]
Using git revision 329651391ce1c209d1e56cafafb07002978989c7, I follow the procedure described in https://github.com/orientechnologies/orientdb/issues/3770#issuecomment-83228774
When I run the Java program, I get this output:
```
Mar 23, 2015 5:02:18 PM com.orientechnologies.common.log.OLogManager log
INFO: OrientDB auto-config DISKCACHE=1,137MB (heap=910MB os=4,096MB disk=7,120MB)
Exception in thread "main" java.lang.Exception: Matter not found with id0.43298458363146575
	at com.tkbt.Main.main(Main.java:42)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:134)
```

Neither instance of orientdb shows any error messages. Is it just me or does this happen for other people?

**Comment by lvca** [comment]
With asynchronous replication the TX is executed on local node: if succeed the OK is sent to the client. If then, during the asynchronous replication any errors occur, the transaction is rollbacked. With asynch replication you can see dirty records (the isolation level is relaxed). Tried with synchronous replication and works.

Now why this fail with asynchronous? I'm logging the reason if that.

**Comment by lvca** [comment]
Reproduced. The tx worked, but cluster id was the default one: 3. That's why record can't be found. Fixed.
