### ISSUE TITLE
Setting pool size on memory databases using orient graph factory results in an exception

### ISSUE THREAD

**Issue by mohamnag** [orientechnologies/orientdb#3794]
So this started with an strange test fail when we replaced the remote database with an memory one for the sake of faster tests. the setup process looked like following:
```
orientGraphFactory = new OrientGraphFactory(remoteServer, user, password).setupPool(1, 5);
return orientGraphFactory.getTx();
```
as long as we used `plocal:` or `remote:` for `remoteServer` url, everything was fine, but as soon as we replaced it with `memory:` the tests started failing with following exception:
```
com.orientechnologies.orient.core.exception.OStorageException: Cannot open local storage 'sslc5' with mode=rw
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.open(OAbstractPaginatedStorage.java:217)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.open(ODatabaseDocumentTx.java:243)
	at com.orientechnologies.orient.core.db.OPartitionedDatabasePool.acquire(OPartitionedDatabasePool.java:285)
	at com.tinkerpop.blueprints.impls.orient.OrientBaseGraph.<init>(OrientBaseGraph.java:163)
	at com.tinkerpop.blueprints.impls.orient.OrientTransactionalGraph.<init>(OrientTransactionalGraph.java:78)
	at com.tinkerpop.blueprints.impls.orient.OrientGraph.<init>(OrientGraph.java:128)
	at com.tinkerpop.blueprints.impls.orient.OrientGraphFactory.getTx(OrientGraphFactory.java:74)
	at at.smartassets.sslc.backend.OrientDB.getGraph(OrientDB.java:48)
	at at.smartassets.sslc.backend.models.UserModel.create(UserModel.java:274)
	at at.smartassets.sslc.backend.test.unit.models.UserModelUnitTest.userModelEmailInvalidCreationTest(UserModelUnitTest.java:93)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:160)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:74)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:211)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:67)
Caused by: com.orientechnologies.orient.core.exception.OStorageException: Cannot open the storage 'sslc5' because it does not exist in path: sslc5
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.open(OAbstractPaginatedStorage.java:162)
	... 31 more
```

after testing a lot of configurations, I found out that the problem is actually setting the pool size. As soon as I removed `.setupPool(1, 5)` everything started acting correctly.

**Comment by mohamnag** [comment]
for the sake of record, using 
```
com.orientechnologies:orientdb-client:2.0.5
com.orientechnologies:orientdb-graphdb:2.0.5
```

**Comment by lvca** [comment]
Try creating it first with:

```java
new OrientGraphNoTx(url);
```
