### ISSUE TITLE
Import VehicleHistoryGraph database fails

### ISSUE THREAD

**Issue by sebbes** [orientechnologies/orientdb#3796]
Hi,

I am new to orientdb. I tried to import the VehicleHistoryGraph , got the following exception (using community version 2.0.5, OS: Debian 7): 
Non merge mode (-merge=false): removing all default non security classes
Removed 0 classes.Error on database import happened just before line 77, column 446
java.lang.NumberFormatException: For input string: ":�9�"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Integer.parseInt(Integer.java:492)
	at com.orientechnologies.orient.core.serialization.serializer.OJSONReader.nextChar(OJSONReader.java:273)
	at com.orientechnologies.orient.core.serialization.serializer.OJSONReader.readNext(OJSONReader.java:174)
	at com.orientechnologies.orient.core.serialization.serializer.OJSONReader.readString(OJSONReader.java:92)
	at com.orientechnologies.orient.core.serialization.serializer.OJSONReader.readString(OJSONReader.java:87)
	at com.orientechnologies.orient.core.serialization.serializer.OJSONReader.readString(OJSONReader.java:83)
	at com.orientechnologies.orient.core.db.tool.ODatabaseImport.importDatabase(ODatabaseImport.java:416)
	at com.orientechnologies.orient.console.OConsoleDatabaseApp.importDatabase(OConsoleDatabaseApp.java:1539)
	at com.orientechnologies.orient.graph.console.OGremlinConsole.importDatabase(OGremlinConsole.java:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at com.orientechnologies.common.console.OConsoleApplication.execute(OConsoleApplication.java:381)
	at com.orientechnologies.common.console.OConsoleApplication.executeCommands(OConsoleApplication.java:246)
	at com.orientechnologies.common.console.OConsoleApplication.run(OConsoleApplication.java:135)
	at com.orientechnologies.orient.graph.console.OGremlinConsole.main(OGremlinConsole.java:62)

Is this a bug or am I doing anything wrong?

Kind regards,
Sebastian

**Comment by lvca** [comment]
Are you import that database from what kind of file?

**Comment by sebbes** [comment]
I import from a zip file. The import via the "cloud import" gave me a 403, so I downloaded the zip file and tried to import via command line.

**Comment by lvca** [comment]
Sorry, I was sure to have responded. Don't import it, just uncompress the database under the "databases" directory.
