### ISSUE TITLE
Gremlin concurrency issue

### ISSUE THREAD

**Issue by RoarN** [orientechnologies/orientdb#3798]
OrientDB 2.0.5 on Windows 7

Run the attached code to create a small data structure and run queries from several threads. This will result in exceptions like:
```
com.orientechnologies.orient.core.exception.ODatabaseException: Error on retrieving record #11:18879 (cluster: thing)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.executeReadRecord(ODatabaseDocumentTx.java:1605)
	at com.orientechnologies.orient.core.tx.OTransactionOptimistic.loadRecord(OTransactionOptimistic.java:226)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.load(ODatabaseDocumentTx.java:1424)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.load(ODatabaseDocumentTx.java:117)
	at com.orientechnologies.orient.core.record.impl.ODocument.field(ODocument.java:859)
	at com.orientechnologies.orient.core.index.OIndexRemoteOneValue.get(OIndexRemoteOneValue.java:55)
	at com.orientechnologies.orient.core.index.OIndexRemoteOneValue.get(OIndexRemoteOneValue.java:43)
	at com.tinkerpop.blueprints.impls.orient.OrientBaseGraph.getVertices(OrientBaseGraph.java:857)
	at com.ceeview.test.db.orient.concurrent.ConcurrentTest2.getVertex(ConcurrentTest2.java:107)
	at com.ceeview.test.db.orient.concurrent.ConcurrentTest2.access$2(ConcurrentTest2.java:104)
	at com.ceeview.test.db.orient.concurrent.ConcurrentTest2$GremlinWorker.run(ConcurrentTest2.java:188)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.runAndReset(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: com.orientechnologies.orient.core.exception.ODatabaseException: Error on retrieving record #11:18879 (cluster: thing)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.executeReadRecord(ODatabaseDocumentTx.java:1605)
	at com.orientechnologies.orient.core.tx.OTransactionNoTx.loadRecord(OTransactionNoTx.java:80)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.load(ODatabaseDocumentTx.java:1437)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.readRecord(ONetworkProtocolBinary.java:1453)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.executeRequest(ONetworkProtocolBinary.java:346)
	at com.orientechnologies.orient.server.network.protocol.binary.OBinaryNetworkProtocolAbstract.execute(OBinaryNetworkProtocolAbstract.java:220)
	at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:69)
Caused by: com.orientechnologies.common.concur.lock.OLockException: Cannot unlock a never acquired lock
	at com.orientechnologies.orient.core.tx.OTransactionAbstract.unlockRecord(OTransactionAbstract.java:137)
	at com.orientechnologies.orient.core.id.ORecordId.unlock(ORecordId.java:287)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.unlockRecord(OAbstractPaginatedStorage.java:1769)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.readRecord(OAbstractPaginatedStorage.java:1443)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.readRecord(OAbstractPaginatedStorage.java:694)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.executeReadRecord(ODatabaseDocumentTx.java:1572)
	... 6 more
---
```
Experimenting with starting different threads showed that:
- one gremlin thread works fine
- one gremlin thread in any combination with other threads will result in an exception
- running without any gremlin request works just fine

This issue is very serious for any application server implementation that runs lots of parallel requests against the database (the way we do).

Note 1. It does not behave this way on 1.7.10 as far as I can see.
Note 2. The setup part of the test code runs MUCH faster on 1.7.10

Regards
Roar N

**Comment by RoarN** [comment]
package com.ceeview.test.db.orient.concurrent;

import java.util.Random;
import java.util.concurrent.ScheduledThreadPoolExecutor;
import java.util.concurrent.TimeUnit;

import com.orientechnologies.orient.core.db.OPartitionedDatabasePool;
import com.orientechnologies.orient.core.metadata.schema.OClass;
import com.orientechnologies.orient.core.metadata.schema.OType;
import com.orientechnologies.orient.graph.gremlin.OCommandGremlin;
import com.tinkerpop.blueprints.Direction;
import com.tinkerpop.blueprints.Vertex;
import com.tinkerpop.blueprints.impls.orient.OrientGraph;
import com.tinkerpop.blueprints.impls.orient.OrientGraphNoTx;

public class ConcurrentTest2
{
	private Random rand = new Random();
	private int max = 100;
	private int children = 25;
	private boolean running = true;
	
	private ScheduledThreadPoolExecutor executor = new ScheduledThreadPoolExecutor(5);

	static String url = "remote:localhost/test";
	static String user = "admin";
	static String password = "admin";

	private OPartitionedDatabasePool pool = new OPartitionedDatabasePool(url, user, password);
	
	private OrientGraph getGraph()
	{
//		ODatabaseDocumentTx conn = ODatabaseDocumentPool.global().acquire(url, user, password);
//		return new OrientGraph(conn);
		
		return new OrientGraph(pool.acquire());
	}

	void setup()
	{
		long start = System.currentTimeMillis();
		System.out.println("setup() start");
		OrientGraphNoTx graph = new OrientGraphNoTx(url);
		try
		{

			OClass thing = graph.getVertexType("Thing");
			if (thing == null)
			{
				thing = graph.createVertexType("Thing");
				thing.createProperty("thingId", OType.STRING);
				thing.createIndex("thingId", OClass.INDEX_TYPE.UNIQUE, "thingId");

				graph.createEdgeType("has_thing");

				for (int i = 0; i < max; i++)
				{
					String pId = String.format("%04d", i);
					Vertex p = graph.addVertex("class:Thing");
					p.setProperty("thingId", pId);
					System.out.println("adding " + pId);
					for (int j = 0; j < children; j++)
					{
						String cId = String.format("%04d", j);
						Vertex c = graph.addVertex("class:Thing");
						c.setProperty("thingId", String.format("%s-%s", pId, cId));
						p.addEdge("has_thing", c);
						
						for (int k = 0; k < children; k++)
						{
							String ccId = String.format("%04d", k);
							Vertex cc = graph.addVertex("class:Thing");
							cc.setProperty("thingId", String.format("%s-%s-%s", pId, cId,ccId));
							c.addEdge("has_thing", cc);
						}
					}
				}
				graph.commit();
				System.out.println("setup() done in " + (System.currentTimeMillis() - start) + " ms");
			}
		}
		catch (Exception e)
		{
			e.printStackTrace();
		}
		finally
		{
			graph.shutdown();
		}
	}

	private String randomIndex()
	{
		return String.format("%04d", rand.nextInt(max));
	}

	private boolean isRunning()
	{
		return running;
	}

	private Vertex getVertex(OrientGraph graph, String id)
	{
		// System.out.println("getVertex: " + myid);
		for (Vertex v : graph.getVertices("Thing.thingId", id))
		{
			return v;
		}
		return null;
	}

	@SuppressWarnings("unchecked")
	private void readAll()
	{
		try
		{
			long start = System.currentTimeMillis();
			long total = 0;
			OrientGraph graph = getGraph();
			
			for (int i = 0; i < max; i++)
			{
				String id = String.format("%04d", i);
				Vertex vParent = getVertex(graph, id);
				total++;
				String req = String.format("g.v('%s').out('has_thing').out('has_thing')", vParent.getId());
				for (Vertex v : (Iterable<Vertex>) graph.command(new OCommandGremlin(req)).execute())
				{
					total++;
				}
			}
			
			System.out.println("fetched all data (" + total + ") in " + (System.currentTimeMillis() - start) + " ms");
			Thread.sleep(3000);
		}
		catch (Exception e)
		{
			e.printStackTrace();
		}
		
	}
	
	class Worker implements Runnable
	{
		@Override
		public void run()
		{
			try
			{
				String id = randomIndex();
				System.out.println("Worker: " + id);
				
				OrientGraph graph = getGraph();
				Vertex vParent = getVertex(graph, id);
				for (Vertex v : vParent.getVertices(Direction.OUT, "has_thing"))
				{
//					System.out.println("   " + v);
				}
			}
			catch (Throwable e)
			{
				running = false;
				e.printStackTrace();
			}
		}
	};

	class GremlinWorker implements Runnable
	{
		@SuppressWarnings("unchecked")
		@Override
		public void run()
		{
			try
			{
				String id = randomIndex();
				System.out.println("GremlinWorker: " + id);
				
				OrientGraph graph = getGraph();
				Vertex vParent = getVertex(graph, id);

				String req = String.format("g.v('%s').out('has_thing')", vParent.getId());
//				System.out.println("Gremlin request: " + req);

				for (Vertex v : (Iterable<Vertex>) graph.command(new OCommandGremlin(req)).execute())
				{
//					System.out.println("  " + v);
				}
			}
			catch (Throwable e)
			{
				running = false;
				e.printStackTrace();
			}
		}
	};

	private void addWorkerThread(int interval)
	{
		executor.scheduleAtFixedRate(new Worker(), 1, interval, TimeUnit.MILLISECONDS);
	}

	private void addGremlinThread(int interval)
	{
		executor.scheduleAtFixedRate(new GremlinWorker(), 1, interval, TimeUnit.MILLISECONDS);
	}

	private void stop()
	{
		executor.shutdown();
		System.out.println("stop()");
	}

	public static void main(String[] args) throws InterruptedException
	{

		ConcurrentTest2 test = new ConcurrentTest2();

		test.setup();
		test.readAll();
		
		test.addGremlinThread(2);
		test.addGremlinThread(2);
		test.addWorkerThread(2);
		test.addWorkerThread(4);
		test.addWorkerThread(2);
		test.addWorkerThread(5);

		while(test.isRunning() == true)
		{
			Thread.sleep(50);
		}

		test.stop();
	}


}

**Comment by RoarN** [comment]
Wrong button :)

**Comment by tglman** [comment]
hi @RoarN,

I ran this with 2.2 and seems to go smoothly, probably has been fixed long time ago, closing
