### ISSUE TITLE
insert into V content { out_something: #13:5 } throws exception and continues, but should fail

### ISSUE THREAD

**Issue by mrft** [orientechnologies/orientdb#3808]
On OrientDB 2.0.5

I was trying to get some vertices from another DB into the current one for testing (using the Rest API).

I forgot that if i do a select * from V, I would also get out_ and in_ properties for edges.

So I was inserting things like
insert into V content { out_something: #13:5 } 

Since this #13:5 node (and the cluster also) doesn't exist, I think this should FAIL. But instead it worked, throwing an exception (that I could see in the console where the server was running).

Then, when doing a simple **select * from V**, another error will be thrown, and you will only get the metadata back, and none of the fields. Which is annoying. I think the insert should have failed in the first place, so that I could have solved the problem there, instead of having to find out afterwards that I was inserting impossibe data. this allowed the database to become corrupt, which is bad (not in my simple test, but in general).

<code>
{db=Security} Fetching error on record #13:3500
com.orientechnologies.orient.core.exception.ODatabaseException: Error on retrieving record #24:3495 (cluster: null)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.executeReadRecord(ODatabaseDocumentTx.java:1605)
	at com.orientechnologies.orient.core.tx.OTransactionNoTx.loadRecord(OTransactionNoTx.java:80)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.load(ODatabaseDocumentTx.java:1424)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.load(ODatabaseDocumentTx.java:117)
	at com.orientechnologies.orient.core.record.impl.ODocument.field(ODocument.java:859)
	at com.orientechnologies.orient.core.fetch.OFetchHelper.processRecordRidMap(OFetchHelper.java:140)
	at com.orientechnologies.orient.core.fetch.OFetchHelper.fetch(OFetchHelper.java:70)
	at com.orientechnologies.orient.core.serialization.serializer.record.string.ORecordSerializerJSON.toString(ORecordSerializerJSON.java:337)
	at com.orientechnologies.orient.core.serialization.serializer.record.string.ORecordSerializerStringAbstract.toString(ORecordSerializerStringAbstract.java:665)
	at com.orientechnologies.orient.core.record.ORecordAbstract.toJSON(ORecordAbstract.java:192)
	at com.orientechnologies.orient.server.network.protocol.http.OHttpResponse.formatMultiValue(OHttpResponse.java:366)
	at com.orientechnologies.orient.server.network.protocol.http.OHttpResponse.writeRecords(OHttpResponse.java:330)
	at com.orientechnologies.orient.server.network.protocol.http.OHttpResponse.writeResult(OHttpResponse.java:226)
	at com.orientechnologies.orient.server.network.protocol.http.command.post.OServerCommandPostCommand.execute(OServerCommandPostCommand.java:103)
	at com.orientechnologies.orient.server.network.protocol.http.ONetworkProtocolHttpAbstract.service(ONetworkProtocolHttpAbstract.java:174)
	at com.orientechnologies.orient.server.network.protocol.http.ONetworkProtocolHttpAbstract.execute(ONetworkProtocolHttpAbstract.java:574)
	at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:69)
Caused by: java.lang.IllegalArgumentException: Cluster segment #24 does not exist in database 'Security'
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.checkClusterSegmentIndexRange(OAbstractPaginatedStorage.java:2133)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.getClusterById(OAbstractPaginatedStorage.java:1041)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.readRecord(OAbstractPaginatedStorage.java:694)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.executeReadRecord(ODatabaseDocumentTx.java:1572)
	... 16 more
</code>

Another concern, while thinking of this. could one make the database corrupt by doing a update V set out_friend_of = #14:7 for example? (I think that should fail also, and that one should be forced to use the proper graph syntax to alter edges).

**Comment by lvca** [comment]
This is not an issue: OrientDB allows to preset RID even before they are created. So it's up to you using the GraphAPI to avoid this problems.

**Comment by mrft** [comment]
Does that make sense, even when that cluster doesn't even exist yet?

**Comment by lvca** [comment]
Yes. You could pre-allocate records. We use this technique with the Graph Batch Inserter impl.
