### ISSUE TITLE
Export from v2.0, trying to import in v2.0.5 fails

### ISSUE THREAD

**Issue by mrft** [orientechnologies/orientdb#3811]
<pre>- Creating cluster 'organization'...OK, assigned id=26
- Creating cluster 'mainstructure'...OK, assigned id=27
- Creating cluster '_studio'...OK, assigned id=28
Rebuilding indexes of truncated clusters ...Error on database import happened just before line 0, column 1112
com.orientechnologies.orient.core.exception.OCommandExecutionException: Index 'School.institutionNumber' not found
	at com.orientechnologies.orient.core.sql.OCommandExecutorSQLRebuildIndex.execute(OCommandExecutorSQLRebuildIndex.java:89)
	at com.orientechnologies.orient.core.sql.OCommandExecutorSQLDelegate.execute(OCommandExecutorSQLDelegate.java:64)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.executeCommand(OAbstractPaginatedStorage.java:1189)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.command(OAbstractPaginatedStorage.java:1178)
	at com.orientechnologies.orient.core.command.OCommandRequestTextAbstract.execute(OCommandRequestTextAbstract.java:63)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.command(ONetworkProtocolBinary.java:1178)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.executeRequest(ONetworkProtocolBinary.java:385)
	at com.orientechnologies.orient.server.network.protocol.binary.OBinaryNetworkProtocolAbstract.execute(OBinaryNetworkProtocolAbstract.java:220)
	at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:69)
</pre>

Download link of the exported database http://we.tl/DnpPYcdd8s

**Comment by mrft** [comment]
Seems the other import I tried before messed things up.
So apparently when something fails, everything becomes unstable, and you need to create a new database...

**Comment by mrft** [comment]
I closed it because it worked when importing to a new DB I created called *Sec2*

It fails (even with a freshly downloaded version) always when the database I try to import into is called *Security*

**Comment by lvca** [comment]
So have you tried on importing it in an existent db?

**Comment by mrft** [comment]
I think I have a better understanding of the problem now.

* Create a new DB, name doesn't matter, called Test
* use console to connect to that database *connect remote:localhost/Test*
* start the import with *import database <filename>* OR *import database <filename> -preserveclusterIds=true*
* The import works
* Do the exact same command again: *import database <filename>* OR *import database <filename> -preserveclusterIds=true*
* The import fails.

After that, when dropping the database, and immediately recreating it, the import keeps failing.

**Comment by tglman** [comment]
hi @mrft,

Just one question: between the first and the second import, do you close the console or not ? and does it happen the same if you close and reopen the console ? 
this seems an error on the console that cache some data that shouldn't cache.

**Comment by mrft** [comment]
I just opened the console again. 
Connected to the database.
Executed 'import database <myexport.gz>'
Follwing error occurred
<pre>
Rebuilding indexes of truncated clusters ...Error on database import happened just before line 0, column 1417
com.orientechnologies.orient.core.exception.OCommandExecutionException: Index 'GoverningInstitution.vskoNumber' not found
	at com.orientechnologies.orient.core.sql.OCommandExecutorSQLRebuildIndex.execute(OCommandExecutorSQLRebuildIndex.java:89)
	at com.orientechnologies.orient.core.sql.OCommandExecutorSQLDelegate.execute(OCommandExecutorSQLDelegate.java:64)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.executeCommand(OAbstractPaginatedStorage.java:1189)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.command(OAbstractPaginatedStorage.java:1178)
	at com.orientechnologies.orient.core.command.OCommandRequestTextAbstract.execute(OCommandRequestTextAbstract.java:63)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.command(ONetworkProtocolBinary.java:1178)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.executeRequest(ONetworkProtocolBinary.java:385)
	at com.orientechnologies.orient.server.network.protocol.binary.OBinaryNetworkProtocolAbstract.execute(OBinaryNetworkProtocolAbstract.java:220)
	at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:69)
</pre>

So, I don't think the console caching is causing this. OrientDB has been restarted also between posting the ticket and this new test.

**Comment by lvca** [comment]
Please could you try importing with 2.0.15 or 2.1.2? If you have the same error, is it possible to have the export file?

**Comment by prjhub** [comment]
The issue has been closed because no response has been received after a while. In case the issue is still valid, please reopen it or write a comment that explains why it's still valid and a way to reproduce it. Thank you.
