### ISSUE TITLE
Index error

### ISSUE THREAD

**Issue by martingg88** [orientechnologies/orientdb#3812]
i do have following issue but it will happen once in 2 to 3 days. any idea?

FYI.....i do have one index called as 'entry' that is composed of three fields/properties (etc: func,channel and creator). I have to rebuild index once i have following issue and it is quite troublesome. 

"Probably you need to rebuild indexes. Now executing query using cluster scan"

**Comment by martingg88** [comment]
FYI. this issue will happen if you have composite indexes that contain any link class properties.

**Comment by lvca** [comment]
This is definitely a bug. Did you experience the same with a more recent OrientDB release? Let's say 2.0.15 or 2.1.2?

**Comment by laa** [comment]
Hi,
Do you have any exception stack trace associated with this error ?

**Comment by martingg88** [comment]
not. It have been few months issue and i can't even remember what have caused this issue.

**Comment by martingg88** [comment]
here is the exception strack i just got recently. 

Error on using index tmp.entry in query 'SELECT * FROM tmp WHERE (session_id = "dsdfsdz" AND creator = "#16:11710" AND channel = "advertisement" AND func = "create_banner" ) LIMIT 1'. Probably you need to rebuild indexes. Now executing query using cluster scan
java.lang.ClassCastException: java.lang.String cannot be cast to com.orientechnologies.orient.core.db.record.OIdentifiable
        at com.orientechnologies.orient.core.serialization.serializer.binary.impl.OLinkSerializer.preprocess(OLinkSerializer.java:43)
        at com.orientechnologies.orient.core.serialization.serializer.binary.impl.index.OCompositeKeySerializer.preprocess(OCompositeKeySerializer.java:383)
        at com.orientechnologies.orient.core.serialization.serializer.binary.impl.index.OCompositeKeySerializer.preprocess(OCompositeKeySerializer.java:46)
        at com.orientechnologies.orient.core.index.sbtree.local.OSBTree.iterateEntriesBetweenAscOrder(OSBTree.java:1224)
        at com.orientechnologies.orient.core.index.sbtree.local.OSBTree.iterateEntriesBetween(OSBTree.java:743)
        at com.orientechnologies.orient.core.index.engine.OSBTreeIndexEngine.iterateEntriesBetween(OSBTreeIndexEngine.java:327)
        at com.orientechnologies.orient.core.index.OIndexMultiValues.iterateEntriesBetween(OIndexMultiValues.java:257)
        at com.orientechnologies.orient.core.index.OIndexAbstractDelegate.iterateEntriesBetween(OIndexAbstractDelegate.java:85)
        at com.orientechnologies.orient.core.index.OIndexTxAwareMultiValue.iterateEntriesBetween(OIndexTxAwareMultiValue.java:312)
        at com.orientechnologies.orient.core.sql.operator.OQueryOperatorEquals.executeIndexQuery(OQueryOperatorEquals.java:149)
        at com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.searchForIndexes(OCommandExecutorSQLSelect.java:1859)
        at com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.searchInClasses(OCommandExecutorSQLSelect.java:850)
        at com.orientechnologies.orient.core.sql.OCommandExecutorSQLResultsetAbstract.assignTarget(OCommandExecutorSQLResultsetAbstract.java:207)
        at com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.assignTarget(OCommandExecutorSQLSelect.java:475)
        at com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.executeSearch(OCommandExecutorSQLSelect.java:457)
        at com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.execute(OCommandExecutorSQLSelect.java:428)
        at com.orientechnologies.orient.core.sql.OCommandExecutorSQLDelegate.execute(OCommandExecutorSQLDelegate.java:90)
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.executeCommand(OAbstractPaginatedStorage.java:1469)
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.command(OAbstractPaginatedStorage.java:1450)
        at com.orientechnologies.orient.core.command.OCommandRequestTextAbstract.execute(OCommandRequestTextAbstract.java:63)
        at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.command(ONetworkProtocolBinary.java:1319)
        at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.executeRequest(ONetworkProtocolBinary.java:396)
        at com.orientechnologies.orient.server.network.protocol.binary.OBinaryNetworkProtocolAbstract.execute(OBinaryNetworkProtocolAbstract.java:223)
        at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:77)

**Comment by martingg88** [comment]
FYI. Any index created on link type will treated as OIdentifiable record. this issue happen because 'creator' property in where clause is treated as string. Any idea how to treat this property filter as OIdentifiable record by using orientjs library?

**Comment by martingg88** [comment]
any idea how to solve this?

**Comment by maggiolo00** [comment]
@martingg88 

if you use this query
```
SELECT * FROM tmp WHERE (session_id = "dsdfsdz" AND creator = #16:11710 AND channel = "advertisement" AND func = "create_banner" ) LIMIT 1
```

do you get the exception?

**Comment by martingg88** [comment]
yes it work without quote around RID.

**Comment by martingg88** [comment]
any update...

**Comment by obi1kenobi** [comment]
I just ran into this problem as well -- a query with quotes around the RID will cause the exception, whereas a query without the quotes will not. Both queries will return the same result, but one seems to use the index and the other seems to fall back to a table scan. It would be nice to get this fixed soon!

**Comment by eyurtsev** [comment]
:+1:

**Comment by martingg88** [comment]
+1

**Comment by luigidellaquila** [comment]
Hi guys, 

IMHO the issue here is that a result is returned when RIDs are quoted.
A RID is different from a string, it's correct that the query doesn't use the index when you pass a string.

I'd like to fix that behavior and just return nothing in that case, WDYT?

Thanks

**Comment by obi1kenobi** [comment]
Fine by me, so long as that is a consistent behavior maintained in all operations: querying with a string never matches RIDs.

**Comment by mishak87** [comment]
@luigidellaquila Yes the issue is with subselect in where condition.
Will this be fixed soon?

```sql
-- property Service.node is link to class Node
select x.type() from (select @rid as x from Node where @rid = #77:1) -- returns LINK
select from Service where node.@rid = (select @rid from Node where @rid = #77:1) -- returns nothing
select from Service where node = (select from Node where @rid = #77:1) -- returns nothing
select from Service where node.@rid = "#77:1" -- works
select from Service where node.@rid = #77:1 -- works
select from Service where node = "#77:1" -- works
select from Service where node = #77:1 -- works
```

**Comment by luigidellaquila** [comment]
Hi @mishak87 

For the second and third query you have to use IN operator instead of =

```
select from Service where node.@rid IN (select @rid from Node where @rid = #77:1) 
select from Service where node IN (select from Node where @rid = #77:1) 
```

I hope it helps

Thanks

Luigi
