### ISSUE TITLE
Unable to start Enterprise Workbench

### ISSUE THREAD

**Issue by Wanderfalke** [orientechnologies/orientdb#3834]
Version: 2.0.3
OS: OSX 10.10.2

when starting the workbench, I'm getting following exception:
```
Error on installing dynamic plugin 'workbench'
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.orientechnologies.orient.server.plugin.OServerPluginManager.startPluginClass(OServerPluginManager.java:264)
	at com.orientechnologies.orient.server.plugin.OServerPluginManager.installDynamicPlugin(OServerPluginManager.java:343)
	at com.orientechnologies.orient.server.plugin.OServerPluginManager.updatePlugin(OServerPluginManager.java:194)
	at com.orientechnologies.orient.server.plugin.OServerPluginManager.updatePlugins(OServerPluginManager.java:283)
	at com.orientechnologies.orient.server.plugin.OServerPluginManager.access$000(OServerPluginManager.java:59)
	at com.orientechnologies.orient.server.plugin.OServerPluginManager$1.run(OServerPluginManager.java:92)
	at java.util.TimerThread.mainLoop(Timer.java:555)
	at java.util.TimerThread.run(Timer.java:505)
Caused by: com.orientechnologies.orient.core.exception.OSecurityAccessException: User or password not valid for database: 'monitor'
	at com.orientechnologies.orient.core.metadata.security.OSecurityShared.authenticate(OSecurityShared.java:171)
	at com.orientechnologies.orient.core.metadata.security.OSecurityProxy.authenticate(OSecurityProxy.java:87)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.open(ODatabaseDocumentTx.java:259)
	at com.orientechnologies.workbench.OWorkbenchPlugin.loadConfiguration(OWorkbenchPlugin.java:292)
	at com.orientechnologies.workbench.OWorkbenchPlugin.startup(OWorkbenchPlugin.java:131)
	... 12 more
```

Any help?

**Comment by Torwori** [comment]
Got the same issue on Ubuntu.

**Comment by maggiolo00** [comment]
@Torwori  which version of OrientDB Enterprise?

**Comment by Torwori** [comment]
Same version as @Wanderfalke , 2.0.3

**Comment by maggiolo00** [comment]
@Torwori  Just downloaded 2.0.3 from the site and started without problem on OSX
Any hint on how to replicate it?

**Comment by Torwori** [comment]
@maggiolo00 I'm away from my linux box atm, I'll reply once I get to it.

**Comment by Torwori** [comment]
@maggiolo00 Ok, here's what I did. Downloaded Enterprise Edition 2.1-rc1 and Workbench 2.0.3, ran the server (it started ok), ran Workbench and got this:

```
{db=monitor} Error on installing dynamic plugin 'workbench'
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.orientechnologies.orient.server.plugin.OServerPluginManager.startPluginClass(OServerPluginManager.java:264)
	at com.orientechnologies.orient.server.plugin.OServerPluginManager.installDynamicPlugin(OServerPluginManager.java:343)
	at com.orientechnologies.orient.server.plugin.OServerPluginManager.updatePlugin(OServerPluginManager.java:194)
	at com.orientechnologies.orient.server.plugin.OServerPluginManager.updatePlugins(OServerPluginManager.java:283)
	at com.orientechnologies.orient.server.plugin.OServerPluginManager.startup(OServerPluginManager.java:85)
	at com.orientechnologies.orient.server.OServer.registerPlugins(OServer.java:831)
	at com.orientechnologies.orient.server.OServer.activate(OServer.java:265)
	at com.orientechnologies.orient.server.OServerMain.main(OServerMain.java:41)
Caused by: com.orientechnologies.orient.core.exception.OStorageException: Cannot open local storage '/home/igor/Downloads/orient test folder/orientdb-workbench-2.0.3/databases/monitor' with mode=rw
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.open(OAbstractPaginatedStorage.java:217)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.open(ODatabaseDocumentTx.java:243)
	at com.orientechnologies.workbench.OWorkbenchPlugin.loadConfiguration(OWorkbenchPlugin.java:292)
	at com.orientechnologies.workbench.OWorkbenchPlugin.startup(OWorkbenchPlugin.java:131)
	... 12 more
Caused by: com.orientechnologies.orient.core.exception.OSerializationException: Cannot load database's configuration. The database seems to be corrupted.
	at com.orientechnologies.orient.core.storage.impl.local.OStorageConfigurationSegment.load(OStorageConfigurationSegment.java:86)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.open(OAbstractPaginatedStorage.java:164)
	... 15 more
Caused by: com.orientechnologies.common.concur.lock.OLockException: File '/home/igor/Downloads/orient test folder/orientdb-workbench-2.0.3/databases/monitor/database.ocf' is locked by another process, maybe the database is in use by another process. Use the remote mode with a OrientDB server to allow multiple access to the same database.
	at com.orientechnologies.orient.core.storage.fs.OAbstractFile.lock(OAbstractFile.java:385)
	at com.orientechnologies.orient.core.storage.fs.OAbstractFile.openChannel(OAbstractFile.java:646)
	at com.orientechnologies.orient.core.storage.fs.OAbstractFile.open(OAbstractFile.java:144)
	at com.orientechnologies.orient.core.storage.impl.local.OSingleFileSegment.open(OSingleFileSegment.java:57)
	at com.orientechnologies.orient.core.storage.impl.local.OStorageConfigurationSegment.load(OStorageConfigurationSegment.java:65)
	... 16 more
```

**Comment by maggiolo00** [comment]
Do you have the entire stack?

**Comment by Torwori** [comment]
That's what the console spits out, how can I get the entire stack?

**Comment by maggiolo00** [comment]
The console? Which console?
How do you start the Workbench?

**Comment by Torwori** [comment]
I meant the terminal, sorry.

**Comment by maggiolo00** [comment]
```
          .                                          
          .`        `                                 
          ,      `:.                                  
         `,`    ,:`                                   
         .,.   :,,                                    
         .,,  ,,,                                     
    .    .,.:::::  ````                                 :::::::::     :::::::::   
    ,`   .::,,,,::.,,,,,,`;;                      .:    ::::::::::    :::    :::  
    `,.  ::,,,,,,,:.,,.`  `                       .:    :::      :::  :::     ::: 
     ,,:,:,,,,,,,,::.   `        `         ``     .:    :::      :::  :::     ::: 
      ,,:.,,,,,,,,,: `::, ,,   ::,::`   : :,::`  ::::   :::      :::  :::    :::  
       ,:,,,,,,,,,,::,:   ,,  :.    :   ::    :   .:    :::      :::  :::::::     
        :,,,,,,,,,,:,::   ,,  :      :  :     :   .:    :::      :::  :::::::::   
  `     :,,,,,,,,,,:,::,  ,, .::::::::  :     :   .:    :::      :::  :::     ::: 
  `,...,,:,,,,,,,,,: .:,. ,, ,,         :     :   .:    :::      :::  :::     ::: 
    .,,,,::,,,,,,,:  `: , ,,  :     `   :     :   .:    :::      :::  :::     ::: 
      ...,::,,,,::.. `:  .,,  :,    :   :     :   .:    :::::::::::   :::     ::: 
           ,::::,,,. `:   ,,   :::::    :     :   .:    :::::::::     ::::::::::  
           ,,:` `,,.                                  
          ,,,    .,`                                  
         ,,.     `,                                             WORKBENCH  
       ``        `.                                        ENTERPRISE  EDITION
                 ``                                     www.orientechnologies.com 
                 `                                    


************************************************
*   ORIENTDB WORKBENCH -  ENTERPRISE EDITION   *
*                                              *
* Copyrights (c) 2014 Orient Technologies LTD  *
************************************************
* Version...: 2.0.3                            *
************************************************

To open the Web Console open your browser to the URL: http://10.3.15.68:2491 and use 'admin' as user and password to log in, unless you already changed it.

```

**Comment by maggiolo00** [comment]
Do you see this logging at startup of Workbench?

**Comment by Torwori** [comment]
Just to make sure I'm not doing something wrong, I redownloaded db version 2.0.8 and workbench 2.0.3 and now it's working. Ran db with no errors, ran workbench and it looked like it hung on 
```
           .                                          
          .`        `                                 
          ,      `:.                                  
         `,`    ,:`                                   
         .,.   :,,                                    
         .,,  ,,,                                     
    .    .,.:::::  ````                                 :::::::::     :::::::::   
    ,`   .::,,,,::.,,,,,,`;;                      .:    ::::::::::    :::    :::  
    `,.  ::,,,,,,,:.,,.`  `                       .:    :::      :::  :::     ::: 
     ,,:,:,,,,,,,,::.   `        `         ``     .:    :::      :::  :::     ::: 
      ,,:.,,,,,,,,,: `::, ,,   ::,::`   : :,::`  ::::   :::      :::  :::    :::  
       ,:,,,,,,,,,,::,:   ,,  :.    :   ::    :   .:    :::      :::  :::::::     
        :,,,,,,,,,,:,::   ,,  :      :  :     :   .:    :::      :::  :::::::::   
  `     :,,,,,,,,,,:,::,  ,, .::::::::  :     :   .:    :::      :::  :::     ::: 
  `,...,,:,,,,,,,,,: .:,. ,, ,,         :     :   .:    :::      :::  :::     ::: 
    .,,,,::,,,,,,,:  `: , ,,  :     `   :     :   .:    :::      :::  :::     ::: 
      ...,::,,,,::.. `:  .,,  :,    :   :     :   .:    :::::::::::   :::     ::: 
           ,::::,,,. `:   ,,   :::::    :     :   .:    :::::::::     ::::::::::  
           ,,:` `,,.                                  
          ,,,    .,`                                  
         ,,.     `,                                             WORKBENCH  
       ``        `.                                        ENTERPRISE  EDITION
                 ``                                     www.orientechnologies.com
```

Then when I pointed my browser to localhost:2491 this appeared:
```
Error on loading resource /workbench/index.html
java.net.SocketException: Socket closed
	at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:116)
	at java.net.SocketOutputStream.write(SocketOutputStream.java:153)
	at java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:82)
	at java.io.BufferedOutputStream.flush(BufferedOutputStream.java:140)
	at com.orientechnologies.orient.server.network.protocol.http.OHttpResponse.flush(OHttpResponse.java:507)
	at com.orientechnologies.orient.server.network.protocol.http.OHttpResponse.sendStream(OHttpResponse.java:440)
	at com.orientechnologies.orient.server.network.protocol.http.OHttpResponse.sendStream(OHttpResponse.java:401)
	at com.orientechnologies.orient.server.network.protocol.http.command.get.OServerCommandGetStaticContent.execute(OServerCommandGetStaticContent.java:137)
	at com.orientechnologies.orient.server.network.protocol.http.ONetworkProtocolHttpAbstract.service(ONetworkProtocolHttpAbstract.java:200)
	at com.orientechnologies.orient.server.network.protocol.http.ONetworkProtocolHttpAbstract.execute(ONetworkProtocolHttpAbstract.java:600)
	at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:69)
```
This same error appeared three times in a row (likely because of refreshing).

And then:
```
************************************************
*   ORIENTDB WORKBENCH -  ENTERPRISE EDITION   *
*                                              *
* Copyrights (c) 2014 Orient Technologies LTD  *
************************************************
* Version...: 2.0.3                            *
************************************************

To open the Web Console open your browser to the URL: http://127.0.1.1:2491 and use 'admin' as user and password to log in, unless you already changed it.
```

And now it seems to be working. I'll try rc1 again and see if it will work too.

**Comment by Torwori** [comment]
On 2.1-rc2 everything works right away, but again Workbench is slow to start (spends like a minute on logo). I'll investigate some more to see if I can replicate the error again.

**Comment by maggiolo00** [comment]
Should be slow only the first time because it create the database for storing information.

**Comment by Torwori** [comment]
I see, second startup is much faster.

I've tried everything I could remember and I can't replicate the issue with any version, it just works now. Hopefully it doesn't reappear, I'll drop a comment here if it does. :smile:

**Comment by dalgibbard** [comment]
I also encountered this same 'issue' - the initial orientdb logo was showing, and I didn't realise it was still loading.

Could a little ```Creating initial database, please wait...``` message be added to the first boot? That would stop me (and others) from being unexpectedly impatient :)

**Comment by maggiolo00** [comment]
Seems to be resolved in the latest version. I'm closing this
BTW in OrientDB 2.2 Workbench will be dismissed and most of the feature ported in OrientDB Studio
