### ISSUE TITLE
OutOfMemory Exception when creating Databases

### ISSUE THREAD

**Issue by dblaber** [orientechnologies/orientdb#3849]
I have a loop where I am trying to create 50 databases(remote). Orientdb heap size is set to 2GB, version 2.0.5 on a Solaris SPARC machine :
						for(int i = 0; i < 50; i++)
						{
							OServerAdmin serverAdmin =  new OServerAdmin("remote:"+server)
							.connect("root", "filtered").createDatabase("TestDB_P"+i,"document","plocal");
serverAdmin.close();
						}
I get the out of memory around the 11th iteration of that loop. I also tried creating it by connecting to the console, and manually using create database command, but also receiving out of memory exception. 
nt /10.177.203.218:53979: java.lang.OutOfMemoryError: GC overhead limit exceeded
java.lang.OutOfMemoryError: GC overhead limit exceeded
        at com.orientechnologies.common.concur.lock.OThreadCountersHashTable.<init>(OThreadCountersHashTable.java:70)
        at com.orientechnologies.common.concur.lock.OThreadCountersHashTable.<init>(OThreadCountersHashTable.java:60)
        at com.orientechnologies.common.concur.lock.OReadersWriterSpinLock.<init>(OReadersWriterSpinLock.java:41)
        at com.orientechnologies.common.concur.lock.ONewLockManager.<init>(ONewLockManager.java:96)
        at com.orientechnologies.orient.core.index.hashindex.local.cache.OReadWriteDiskCache.<init>(OReadWriteDiskCache.java:77)
        at com.orientechnologies.orient.core.storage.impl.local.paginated.OLocalPaginatedStorage.initWalAndDiskCache(OLocalPaginatedStorage.java:296)
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.create(OAbstractPaginatedStorage.java:242)
        at com.orientechnologies.orient.core.storage.impl.local.paginated.OLocalPaginatedStorage.create(OLocalPaginatedStorage.java:112)
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.create(ODatabaseDocumentTx.java:374)
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.create(ODatabaseDocumentTx.java:352)
        at com.orientechnologies.orient.server.network.protocol.binary.OBinaryNetworkProtocolAbstract.createDatabase(OBinaryNetworkProtocolAbstract.java:273)
        at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.createDatabase(ONetworkProtocolBinary.java:980)
        at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.executeRequest(ONetworkProtocolBinary.java:290)
        at com.orientechnologies.orient.server.network.protocol.binary.OBinaryNetworkProtocolAbstract.execute(OBinaryNetworkProtocolAbstract.java:220)
        at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:69)

**Comment by laa** [comment]
It will be fixed in 2.1 RC2 release.

**Comment by dblaber** [comment]
I also receive out of memory exception when creating schemas in each of a newly created database(lets say I increased heap to 12gb, created the dbs, then shrank it again to 2gb and tried to create schemas for each), would this be the same issue?

**Comment by laa** [comment]
it is already fixed in RC2 could you try snapshot ?
