### ISSUE TITLE
orientdb console: Error: com.orientechnologies.orient.core.exception.OStorageException: Error on creation of storage 'test'

### ISSUE THREAD

**Issue by rwnew2012** [orientechnologies/orientdb#3856]
I am trying to create remote database, and it gives me this error
orientdb> create database remote:localhost/test admin admin plocal graph

Creating database [remote:localhost/test] using the storage type [plocal]...Cannot create the remote storage: test
com.orientechnologies.orient.core.exception.ODatabaseException: Cannot create database 'test'
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.create(ODatabaseDocumentTx.java:440)
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.create(ODatabaseDocumentTx.java:353)
        at com.orientechnologies.orient.core.db.ODatabaseFactory$1.create(ODatabaseFactory.java:108)
        at com.orientechnologies.orient.server.network.protocol.binary.OBinaryNetworkProtocolAbstract.createDatabase(OBinaryNetworkProtocolAbstract.java:273)
        at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.createDatabase(ONetworkProtocolBinary.java:980)
        at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.executeRequest(ONetworkProtocolBinary.java:290)
        at com.orientechnologies.orient.server.network.protocol.binary.OBinaryNetworkProtocolAbstract.execute(OBinaryNetworkProtocolAbstract.java:220)
        at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:69)
Caused by: com.orientechnologies.orient.core.exception.OStorageException: Error on creation of storage 'test'
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.create(OAbstractPaginatedStorage.java:278)
        at com.orientechnologies.orient.core.storage.impl.local.paginated.OLocalPaginatedStorage.create(OLocalPaginatedStorage.java:112)
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.create(ODatabaseDocumentTx.java:375)
        ... 7 more
Caused by: java.io.IOException: No such file or directory
        at java.io.UnixFileSystem.createFileExclusively(Native Method)
        at java.io.File.createNewFile(File.java:1006)
        at com.orientechnologies.orient.core.storage.impl.local.paginated.OPaginatedStorageDirtyFlag.create(OPaginatedStorageDirtyFlag.java:58)
        at com.orientechnologies.orient.core.storage.impl.local.paginated.OLocalPaginatedStorage.preCreateSteps(OLocalPaginatedStorage.java:195)
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.create(OAbstractPaginatedStorage.java:246)
        ... 9 more

Error: com.orientechnologies.orient.core.exception.OStorageException: Cannot create the remote storage: test

Error: com.orientechnologies.orient.core.exception.ODatabaseException: Cannot create database 'test'

Error: com.orientechnologies.orient.core.exception.OStorageException: Error on creation of storage 'test'

Error: java.io.IOException: No such file or directory

**Comment by rwnew2012** [comment]
I guess this might be file permission issue, close it if it is the case
