### ISSUE TITLE
NPE when creating Lucene Index

### ISSUE THREAD

**Issue by vitorenesduarte** [orientechnologies/orientdb#3858]
```sql
# studio
create class Person
create property Person.isFeatured boolean
create index Person.isFeatured FULLTEXT ENGINE LUCENE

insert into Person set isFeatured = false
```
```bash
# server
2015-04-02 11:43:33:446 SEVERE Internal server error:
java.lang.NullPointerException [ONetworkProtocolHttpDb]
```
__OR:__
```sql
# studio
create class Person
create property Person.isFeatured boolean
insert into Person set isFeatured = false

create index Person.isFeatured FULLTEXT ENGINE LUCENE
```
```bash
# server
2015-04-02 11:47:05:583 INFO  {db=Lucene} - Rebuilding index Lucene.Person.isFeatured (estimated 1 items)... [OIndexRebuildOutputListener]{db=Lucene} Exception during index Person.isFeatured creation.
com.orientechnologies.orient.core.index.OIndexException: Error on rebuilding the index for clusters: [person]
	at com.orientechnologies.orient.core.index.OIndexAbstract.rebuild(OIndexAbstract.java:423)
	at com.orientechnologies.lucene.index.OLuceneIndexNotUnique.rebuild(OLuceneIndexNotUnique.java:178)
	at com.orientechnologies.orient.core.index.OIndexAbstract.create(OIndexAbstract.java:233)
	at com.orientechnologies.orient.core.index.OIndexMultiValues.create(OIndexMultiValues.java:287)
	at com.orientechnologies.lucene.index.OLuceneIndexNotUnique.create(OLuceneIndexNotUnique.java:50)
	at com.orientechnologies.lucene.index.OLuceneIndexNotUnique.create(OLuceneIndexNotUnique.java:37)
	at com.orientechnologies.orient.core.index.OIndexManagerShared.createIndex(OIndexManagerShared.java:169)
	at com.orientechnologies.orient.core.index.OIndexManagerProxy.createIndex(OIndexManagerProxy.java:79)
	at com.orientechnologies.orient.core.metadata.schema.OClassImpl.createIndex(OClassImpl.java:1434)
	at com.orientechnologies.orient.core.sql.OCommandExecutorSQLCreateIndex.execute(OCommandExecutorSQLCreateIndex.java:262)
	at com.orientechnologies.orient.core.sql.OCommandExecutorSQLDelegate.execute(OCommandExecutorSQLDelegate.java:64)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.executeCommand(OAbstractPaginatedStorage.java:1189)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.command(OAbstractPaginatedStorage.java:1178)
	at com.orientechnologies.orient.core.command.OCommandRequestTextAbstract.execute(OCommandRequestTextAbstract.java:63)
	at com.orientechnologies.orient.server.network.protocol.http.command.post.OServerCommandPostCommand.execute(OServerCommandPostCommand.java:81)
	at com.orientechnologies.orient.server.network.protocol.http.ONetworkProtocolHttpAbstract.service(ONetworkProtocolHttpAbstract.java:174)
	at com.orientechnologies.orient.server.network.protocol.http.ONetworkProtocolHttpAbstract.execute(ONetworkProtocolHttpAbstract.java:574)
	at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:69)
Caused by: java.lang.NullPointerException
	at org.apache.lucene.index.DocFieldProcessor.processDocument(DocFieldProcessor.java:186)
	at org.apache.lucene.index.DocumentsWriterPerThread.updateDocument(DocumentsWriterPerThread.java:253)
	at org.apache.lucene.index.DocumentsWriter.updateDocument(DocumentsWriter.java:453)
	at org.apache.lucene.index.IndexWriter.updateDocument(IndexWriter.java:1529)
	at org.apache.lucene.index.IndexWriter.addDocument(IndexWriter.java:1199)
	at org.apache.lucene.index.IndexWriter.addDocument(IndexWriter.java:1180)
	at org.apache.lucene.index.TrackingIndexWriter.addDocument(TrackingIndexWriter.java:148)
	at com.orientechnologies.lucene.manager.OLuceneIndexManagerAbstract.addDocument(OLuceneIndexManagerAbstract.java:100)
	at com.orientechnologies.lucene.manager.OLuceneFullTextIndexManager.put(OLuceneFullTextIndexManager.java:129)
	at com.orientechnologies.lucene.OLuceneIndexEngine.put(OLuceneIndexEngine.java:120)
	at com.orientechnologies.lucene.index.OLuceneIndexNotUnique.put(OLuceneIndexNotUnique.java:66)
	at com.orientechnologies.lucene.index.OLuceneIndexNotUnique.put(OLuceneIndexNotUnique.java:37)
	at com.orientechnologies.orient.core.index.OIndexAbstract.populateIndex(OIndexAbstract.java:860)
	at com.orientechnologies.orient.core.index.OIndexAbstract.indexCluster(OIndexAbstract.java:927)
	at com.orientechnologies.orient.core.index.OIndexAbstract.rebuild(OIndexAbstract.java:405)
	... 17 more

2015-04-02 11:47:05:627 SEVERE Internal server error:
com.orientechnologies.orient.core.index.OIndexException: Error on rebuilding the index for clusters: [person]
--> java.lang.NullPointerException [ONetworkProtocolHttpDb]
```

----
This doesn't happen with __short__:
```sql
create class Person
create property Person.isFeatured short
insert into Person set isFeatured = 0

create index Person.isFeatured FULLTEXT ENGINE LUCENE
```
The server shows that the record was indexed:
```bash
2015-04-02 11:50:15:302 INFO  {db=Lucene} - Rebuilding index Lucene.Person.isFeatured (estimated 1 items)... [OIndexRebuildOutputListener]
2015-04-02 11:50:15:412 INFO  {db=Lucene} --> OK, indexed 1 items in 109 ms [OIndexRebuildOutputListener]
```

But then this query returns nothing:
```sql
select from Person where isFeatured LUCENE 0
```

**Comment by vitorenesduarte** [comment]
I found this while I was trying to find another index for boolean properties since __NOTUNIQUE_HASH_INDEX__ seems to be too slow. As solr supports indexing in boolean properties, I was hoping orientdb-lucene would support too.

**Comment by maggiolo00** [comment]
Hi @vitorenesduarte orientdb-lucene only supports String indexing or Double for
spatial index

**Comment by vitorenesduarte** [comment]
@maggiolo00. Thanks, I know.
If it's not intended to be supported, when creating an index on not supported types, an exception saying exactly that could be thrown instead of NPE or things apparently working.

**Comment by maggiolo00** [comment]
Agreed :D i will fix the NPE

**Comment by vitorenesduarte** [comment]
Great :+1:

**Comment by maggiolo00** [comment]
I have fixed i think we can index also boolean
I will write a test to be sure :D

**Comment by vitorenesduarte** [comment]
That would be pretty cool xD
