### ISSUE TITLE
ConcurrentModificationException on saving mulitple links in a set in an embedded object

### ISSUE THREAD

**Issue by n0lf** [orientechnologies/orientdb#3861]
I try to have an object with an embedded object on another class. The embedded object has Set pointing to a different class.
It works if the Set is also embedded, if there is just one item in the set or if we use a List instead of a Set. 

Iknow it's sort of a weird use case but what we're trying to do is to save a snapshot of some user data in a single document (Document being the snapshot and NestedDocument being the user data). 

--------------------
StackTrace:
Exception in thread "main" com.orientechnologies.orient.core.exception.ODatabaseException: Error on saving record in cluster #-1
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.executeSaveRecord(ODatabaseDocumentTx.java:1758)
	at com.orientechnologies.orient.core.tx.OTransactionNoTx.saveRecord(OTransactionNoTx.java:94)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.save(ODatabaseDocumentTx.java:2277)
	at com.orientechnologies.orient.object.db.OObjectDatabaseTx.save(OObjectDatabaseTx.java:442)
	at com.orientechnologies.orient.object.db.OObjectDatabaseTx.save(OObjectDatabaseTx.java:377)
	at Test.nestedObjectsErrors(Test.java:47)
	at Test.main(Test.java:30)
Caused by: java.util.ConcurrentModificationException
	at java.util.HashMap$HashIterator.nextNode(HashMap.java:1429)
	at java.util.HashMap$EntryIterator.next(HashMap.java:1463)
	at java.util.HashMap$EntryIterator.next(HashMap.java:1461)
	at com.orientechnologies.orient.core.db.record.ORecordLazySet$1.next(ORecordLazySet.java:95)
	at com.orientechnologies.orient.core.db.record.ORecordLazySet$1.next(ORecordLazySet.java:78)
	at com.orientechnologies.orient.core.db.record.OLazyRecordIterator.next(OLazyRecordIterator.java:68)
	at com.orientechnologies.orient.core.db.record.OLazyRecordIterator.next(OLazyRecordIterator.java:38)
	at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinaryV0.writeLinkCollection(ORecordSerializerBinaryV0.java:692)
	at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinaryV0.writeSingleValue(ORecordSerializerBinaryV0.java:563)
	at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinaryV0.serialize(ORecordSerializerBinaryV0.java:255)
	at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinaryV0.writeSingleValue(ORecordSerializerBinaryV0.java:542)
	at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinaryV0.serialize(ORecordSerializerBinaryV0.java:255)
	at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinary.toStream(ORecordSerializerBinary.java:104)
	at com.orientechnologies.orient.core.record.impl.ODocument.toStream(ODocument.java:2061)
	at com.orientechnologies.orient.core.record.impl.ODocument.toStream(ODocument.java:683)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.executeSaveRecord(ODatabaseDocumentTx.java:1658)
	... 6 more
Java Result: 1

______________
Test Code:
public class Test {

    static OObjectDatabaseTx db;

    public static void main(String[] args) {
        db = new OObjectDatabaseTx("remote:localhost/GratefulDeadConcerts").open("admin", "admin");
        db.getEntityManager().registerEntityClass(Document.class);
        db.getEntityManager().registerEntityClass(NestedDocument.class);
        db.getEntityManager().registerEntityClass(CollectionItem.class);
        nestedObjectsErrors();
        db.close();
    }

    private static void nestedObjectsErrors() {
        Document d = new Document();
        NestedDocument n = new NestedDocument();
        CollectionItem c1 = new CollectionItem(), c2 = new CollectionItem();
        c1.setValue("item 1");
        c2.setValue("item 2");
        //it works with a list
        //it doesn't work with any type of Set however
        Set<CollectionItem> set = new HashSet<>(Arrays.asList(c1, c2)); //this fails
        //Set<CollectionItem> set = new HashSet<>(Arrays.asList(c1)); //this works, since there is just 1 item in the set

        n.setSet(set);
        d.setNested(n);
        db.save(d);
    }

    public static class Document {

        @Embedded
        private NestedDocument nested;

        /**
         * @return the nested
         */
        public NestedDocument getNested() {
            return nested;
        }

        /**
         * @param b the nested to set
         */
        public void setNested(NestedDocument n) {
            this.nested = n;
        }
    }

    public static class NestedDocument {

        //@Embedded //everything works if these are embedded
        private Set<CollectionItem> set;

        /**
         * @return the set
         */
        public Set<CollectionItem> getSet() {
            return set;
        }

        /**
         * @param set the set to set
         */
        public void setSet(Set<CollectionItem> set) {
            this.set = set;
        }

    }

    public static class CollectionItem {

        private String value;

        /**
         * @return the value
         */
        public String getValue() {
            return value;
        }

        /**
         * @param value the value to set
         */
        public void setValue(String value) {
            this.value = value;
        }

    }
}

**Comment by tglman** [comment]
fixed in develop and 2.0.x, will be released in 2.0.10
