### ISSUE TITLE
Can't create Lucene Index using Java API

### ISSUE THREAD

**Issue by vitorenesduarte** [orientechnologies/orientdb#3863]
As stated [here](https://github.com/orientechnologies/orientdb-lucene/wiki/Full-Text-Index#lucene-full-text-index), I should be able to create a Lucene Index using Java API.
```java
        OrientGraphNoTx graph = new OrientGraphNoTx(DB_URL, DB_USER, DB_PASS);
        try {
            OSchema schema = graph.getRawGraph().getMetadata().getSchema();
            OClass clazz = schema.createClass("Foo");
            clazz.createProperty("isFeatured", OType.STRING);
            clazz.createIndex("Foo.isFeatured", "FULLTEXT", null, null, "LUCENE", new String[]{"isFeatured"});
        } finally {
            graph.shutdown();
        }
```

```bash
# server
Sent run-time exception to the client /127.0.0.1:53352: java.lang.IllegalArgumentException: No enum constant com.orientechnologies.orient.core.metadata.schema.OType.STRING ENGINE LUCENE
java.lang.IllegalArgumentException: No enum constant com.orientechnologies.orient.core.metadata.schema.OType.STRING ENGINE LUCENE
	at java.lang.Enum.valueOf(Enum.java:238)
	at com.orientechnologies.orient.core.metadata.schema.OType.valueOf(OType.java:63)
	at com.orientechnologies.orient.core.sql.OCommandExecutorSQLCreateIndex.parse(OCommandExecutorSQLCreateIndex.java:203)
	at com.orientechnologies.orient.core.sql.OCommandExecutorSQLCreateIndex.parse(OCommandExecutorSQLCreateIndex.java:56)
	at com.orientechnologies.orient.core.sql.OCommandExecutorSQLDelegate.parse(OCommandExecutorSQLDelegate.java:56)
	at com.orientechnologies.orient.core.sql.OCommandExecutorSQLDelegate.parse(OCommandExecutorSQLDelegate.java:37)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.command(OAbstractPaginatedStorage.java:1176)
	at com.orientechnologies.orient.core.command.OCommandRequestTextAbstract.execute(OCommandRequestTextAbstract.java:63)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.command(ONetworkProtocolBinary.java:1178)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.executeRequest(ONetworkProtocolBinary.java:385)
	at com.orientechnologies.orient.server.network.protocol.binary.OBinaryNetworkProtocolAbstract.execute(OBinaryNetworkProtocolAbstract.java:220)
	at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:69)
```

Am I doing something wrong?

**Comment by xvik** [comment]
Faced this on 2.0.10.

The problem is here: 
```java
com.orientechnologies.orient.core.index.OIndexManagerRemote#createIndex(java.lang.String, java.lang.String, com.orientechnologies.orient.core.index.OIndexDefinition, int[], com.orientechnologies.common.listener.OProgressListener, com.orientechnologies.orient.core.record.impl.ODocument, java.lang.String)
```

```
if (iIndexDefinition != null)
      createIndexDDL = iIndexDefinition.toCreateIndexDDL(iName, iType);
    else
      createIndexDDL = new OSimpleKeyIndexDefinition().toCreateIndexDDL(iName, iType);
```
Here if indexDefinition were null it would go with else branch and query would be correct (for single field case), but  it use indexDefinition, which appends property type at the end.

Probably new method may be added to create index ddl which will count different engine (and simply avoid type addition):
```java
if (iIndexDefinition != null)
      createIndexDDL = iIndexDefinition.toCreateIndexDDL(iName, iType, engine != null);
    
```
