### ISSUE TITLE
Index (composite unique hash) file breaks on startup

### ISSUE THREAD

**Issue by johnmelba** [orientechnologies/orientdb#3865]
2015-04-02 15:17:06:105 FINE  {db=SimilityDb} Checking file integrity of TABLE_XXX.appId_entityName0.hib... [OFileClassic]Caught exception
java.net.SocketException: Broken pipe
	at java.net.SocketOutputStream.socketWrite0(Native Method)
	at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:113)
	at java.net.SocketOutputStream.write(SocketOutputStream.java:159)
	at java.io.BufferedOutputStream.write(BufferedOutputStream.java:122)
	at java.io.FilterOutputStream.write(FilterOutputStream.java:97)
	at com.orientechnologies.orient.server.network.protocol.http.OHttpResponse.send(OHttpResponse.java:139)
	at com.orientechnologies.orient.server.network.protocol.http.command.get.OServerCommandGetDatabase.exec(OServerCommandGetDatabase.java:306)
	at com.orientechnologies.orient.server.network.protocol.http.command.get.OServerCommandGetDatabase.execute(OServerCommandGetDatabase.java:135)
	at com.orientechnologies.orient.server.network.protocol.http.ONetworkProtocolHttpAbstract.service(ONetworkProtocolHttpAbstract.java:174)
	at com.orientechnologies.orient.server.network.protocol.http.ONetworkProtocolHttpAbstract.execute(ONetworkProtocolHttpAbstract.java:574)
	at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:69)

2015-04-02 15:17:06:316 SEVERE Internal server error:
java.net.SocketException: Broken pipe [ONetworkProtocolHttpDb]
2015-04-02 15:17:06:316 FINE  Disconnecting connection with id=6 [OClientConnectionManager]

Have to either restart again or drop and recreate the index for it to work. This happens every now and then and not guaranteed to reproduce at will.

**Comment by tglman** [comment]
hi @johnmelba 
the stack trace doesn't show any relation with the index, is it there any other stack trace ?
it's fine also a flow to reproduce it.

**Comment by johnmelba** [comment]
no other trace we have now. Why are there so many flaky behaviors :(. Are there enough unit tests and load test coverage on composite unique hash indexes ?

**Comment by tglman** [comment]
@johnmelba 

if we cannot find more information relative to the problem, i'll close this, feel free to reopen in with additional data.
