### ISSUE TITLE
Pagination example fails with remote connection to server but succeeds with plocal

### ISSUE THREAD

**Issue by mbhulin** [orientechnologies/orientdb#3871]
I changed the example for pagination in the documentation http://www.orientechnologies.com/docs/last/orientdb.wiki/Pagination.html (Handle it by Hand) which is given for the Document API to the Graph API.
The program runs with a plocal connection without errors and retrieves all 640000 verteces. However it terminates with different error messages when connected to an OrientDB server (no difference whether the server runs on the same or another computer) after about 75000 to 120000 vertices. Version 2.0.6 was used, the server reports these memory resources:
OrientDB auto-config DISKCACHE=5.565MB (heap=455MB os=8.068MB disk=354.988MB)

Here is the code:

import com.orientechnologies.orient.core.id.ORecordId;
import com.orientechnologies.orient.core.sql.query.OSQLSynchQuery;
import com.tinkerpop.blueprints.Vertex;
import com.tinkerpop.blueprints.impls.orient.OrientGraph;
import com.tinkerpop.blueprints.impls.orient.OrientGraphFactory;

public class MainReadBitcoin {

	public static void main(String[] args) {
        OrientGraphFactory factory = new OrientGraphFactory("remote:localhost/VogtSmallDB", "admin", "admin").setupPool(1,10);
		//OrientGraphFactory factory = new OrientGraphFactory("plocal:C:/orientdb/databases/VogtSmallDB", "admin", "admin").setupPool(1,10);
        OrientGraph graph = factory.getTx();

        OSQLSynchQuery largeQuery = new OSQLSynchQuery ("select from trxIn where @rid > ? limit 1000");

        int size = 0;
	    ORecordId lastid = new ORecordId("#13:-1");
        Iterable <Vertex> largeQueryIter = (Iterable <Vertex>) graph.command(largeQuery).execute(lastid); 
        while (largeQueryIter.iterator().hasNext())  {
        	for (Vertex v: largeQueryIter) {
        		lastid = (ORecordId) v.getId();
        		if (size % 5000 == 0) {
        			System.out.print(lastid); System.out.print(" ");
        			System.out.println(v.getProperty("OutPointID"));
        		}
	        	size++;
        	}
        	largeQueryIter = (Iterable <Vertex>) graph.command(largeQuery).execute(lastid);
        	System.out.print("New select executed beginning at id "); System.out.println(lastid);
        }
        System.out.println(size);
        graph.shutdown();
	}
}

This is the console output:
Apr 04, 2015 6:31:50 PM com.orientechnologies.common.log.OLogManager log
INFORMATION: OrientDB auto-config DISKCACHE=4.200MB (heap=1.820MB os=8.068MB disk=354.988MB)
#13:0 4294967295
New select executed beginning at id #13:999
New select executed beginning at id #13:1999
New select executed beginning at id #13:2999
New select executed beginning at id #13:3999
... // some output lines deleted
New select executed beginning at id #13:73999
New select executed beginning at id #13:74999
#13:75000 1
New select executed beginning at id #13:75999
New select executed beginning at id #13:76999
New select executed beginning at id #13:77999
New select executed beginning at id #13:78999
New select executed beginning at id #13:79999
#13:80000 4294967295
New select executed beginning at id #13:80999
Apr 04, 2015 6:31:57 PM com.orientechnologies.common.log.OLogManager log
SCHWERWIEGEND: Removing disconnected network channel '127.0.0.1:2424/VogtSmallDB'...
Apr 04, 2015 6:31:57 PM com.orientechnologies.common.log.OLogManager log
SCHWERWIEGEND: Removing disconnected network channel '127.0.0.1:2424/VogtSmallDB'...
Apr 04, 2015 6:31:57 PM com.orientechnologies.common.log.OLogManager log
SCHWERWIEGEND: Removing disconnected network channel '127.0.0.1:2424/VogtSmallDB'...
Apr 04, 2015 6:31:57 PM com.orientechnologies.common.log.OLogManager log
SCHWERWIEGEND: Removing disconnected network channel '127.0.0.1:2424/VogtSmallDB'...
Apr 04, 2015 6:31:57 PM com.orientechnologies.common.log.OLogManager log
SCHWERWIEGEND: Removing disconnected network channel '127.0.0.1:2424/VogtSmallDB'...
Apr 04, 2015 6:31:57 PM com.orientechnologies.common.log.OLogManager log
SCHWERWIEGEND: Removing disconnected network channel '127.0.0.1:2424/VogtSmallDB'...
... // process manually terminated

When started again the program produced another error message:
... // some output lines deleted
New select executed beginning at id #13:127999
New select executed beginning at id #13:128999
Exception in thread "main" com.orientechnologies.orient.core.exception.ODatabaseException: Database 'remote:localhost/VogtSmallDB' is closed
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.checkOpeness(ODatabaseDocumentTx.java:2605)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.getMetadata(ODatabaseDocumentTx.java:703)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.getMetadata(ODatabaseDocumentTx.java:118)
	at com.orientechnologies.orient.core.sql.query.OSQLQuery.run(OSQLQuery.java:74)
	at com.orientechnologies.orient.core.sql.query.OSQLSynchQuery.run(OSQLSynchQuery.java:85)
	at com.orientechnologies.orient.core.query.OQueryAbstract.execute(OQueryAbstract.java:33)
	at com.tinkerpop.blueprints.impls.orient.OrientGraphCommand.execute(OrientGraphCommand.java:48)
	at MainReadBitcoin.main(MainReadBitcoin.java:28)

And the server console reports at the second run:
15-04-04 18:31:14:376 INFO  OrientDB Server v2.0.6 is active. [OServer]{db=VogtSmallDB} Error on unmarshalling record #13:130732
java.net.SocketException: Connection reset by peer: socket write error)
va.net.SocketException: Connection reset by peer: socket write error
      at java.net.SocketOutputStream.socketWrite0(Native Method)
      at java.net.SocketOutputStream.socketWrite(Unknown Source)
      at java.net.SocketOutputStream.write(Unknown Source)
      at java.io.BufferedOutputStream.flushBuffer(Unknown Source)
      at java.io.BufferedOutputStream.write(Unknown Source)
      at java.io.DataOutputStream.write(Unknown Source)
      at com.orientechnologies.orient.enterprise.channel.binary.OChannelBinary.writeBytes(OChannelBinary.java:322)
      at com.orientechnologies.orient.server.network.protocol.binary.OBinaryNetworkProtocolAbstract.writeRecord(OBinaryNetworkProtocolAbstract.java:431)
      at com.orientechnologies.orient.server.network.protocol.binary.OBinaryNetworkProtocolAbstract.writeIdentifiable(OBinaryNetworkProtocolAbstract.java:139)
      at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.command(ONetworkProtocolBinary.java:16)
      at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.executeRequest(ONetworkProtocolBinary.java:385)
      at com.orientechnologies.orient.server.network.protocol.binary.OBinaryNetworkProtocolAbstract.execute(OBinaryNetworkProtocolAbstract.java:220)
      at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:69)

**Comment by tglman** [comment]
@mbhulin I tried to reproduce this, with both 2.0.6 and 2.1 with no success, from the stack trace seems just a connection problem, can you reproduce it systematically ?

**Comment by tglman** [comment]
no reply, i'm closing this, reopen if needed.
