### ISSUE TITLE
How can I backup and restore without pain?

### ISSUE THREAD

**Issue by StarpTech** [orientechnologies/orientdb#3872]
Hello, Im trying to backup my system and restore it from a zip file.
All examples are from the docs http://www.orientechnologies.com/docs/last/Backup-and-Restore.html

In Windows I get following error:

```
orientdb> connect remote:127.0.0.1/test root root

Disconnecting from the database [null]...OK
Connecting to database [remote:127.0.0.1/test] with user 'root'...
Error: com.orientechnologies.orient.core.exception.OStorageException: Cannot open local storage 'E:/software/orientdb-community-2.0.6/databases/test' with mode=rw

Error: com.orientechnologies.orient.core.exception.OSerializationException: Cannot load database's configuration. The database seems to be corrupted.

Error: java.io.IOException: The process cannot access the file because another process has locked a portion of the file
```

after reading that remote backup & restore commands are only available in the enterprise edition I tried to do it with `plocal` but I get this:

```
orientdb> connect plocal:..\\databases\\test root root

Connecting to remote Server instance [plocal:..\\databases\\test] with user 'root'...Cannot connect to the remote server/database 'remote:plocal:..\\databases\\test/'
com.orientechnologies.common.io.OIOException: Cannot open a connection to remote server: plocal:..\\databases\\test/
        at com.orientechnologies.orient.client.remote.OStorageRemote.getAvailableNetwork(OStorageRemote.java:1849)
        at com.orientechnologies.orient.client.remote.OStorageRemote.beginRequest(OStorageRemote.java:1812)
        at com.orientechnologies.orient.client.remote.OServerAdmin.connect(OServerAdmin.java:89)
        at com.orientechnologies.orient.console.OConsoleDatabaseApp.connect(OConsoleDatabaseApp.java:233)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at com.orientechnologies.common.console.OConsoleApplication.execute(OConsoleApplication.java:381)
        at com.orientechnologies.common.console.OConsoleApplication.executeCommands(OConsoleApplication.java:246)
        at com.orientechnologies.common.console.OConsoleApplication.run(OConsoleApplication.java:135)
        at com.orientechnologies.orient.graph.console.OGremlinConsole.main(OGremlinConsole.java:62)

Error: com.orientechnologies.orient.core.exception.OStorageException: Cannot connect to the remote server/database 'remote:plocal:..\\databases\\test/'

Error: com.orientechnologies.common.io.OIOException: Cannot open a connection to remote server: plocal:..\\databases\\test/
```

then I tried the `backup.sh` with following options:

`.\backup.sh plocal:../databases/test root root test.zip`
and get this curious message:
`Error: com.orientechnologies.orient.core.exception.OSecurityAccessException: User or password not valid for database: 'test'`

**Can anybody show me how can I restore and backup my db really straight forward without blocking my db?**

Thank you!

**Comment by StarpTech** [comment]
When I create a user seperatly for the db and use the credentials, it works! I thought the root user has the privileges.

**Comment by lvca** [comment]
I think the problem here is the usage of `\\`. Could you try using `/` instead?

**Comment by kowalot** [comment]
@StarpTech  plz try
``` sql
.\backup.sh plocal:../databases/test admin admin test.zip
```
I noticed that for remotely created database (lets say with root) I was able to log in with admin? account when I used plocal
