### ISSUE TITLE
Import lead to broken db

### ISSUE THREAD

**Issue by StarpTech** [orientechnologies/orientdb#3873]
Hi
after importing the json file I get a `index 'Node.Mid' not found` exception. This error is reasonable but not the fact that an import can corrupt the whole db structure (includes system classes). Is there any rollback mechanism or safe method to do an import?
```
Importing database database C:\Users\starpetch\Desktop\bc24_prod.json...
Started import of database 'remote:127.0.0.1/bodyclub24' from C:\Users\starpetch\Desktop\bc24_prod.json...
Non merge mode (-merge=false): removing all default non security classes
- Class BroughtIntoRight was removed.
- Class BroughtIntoLeft was removed.
- Class Root was removed.
- Class ORIDs was removed.
- Class Cycle was removed.
- Class OFunction was removed.
- Class _studio was removed.
- Class ORestricted was removed.
- Class OTriggered was removed.
- Class OSchedule was removed.
- Class Settings was removed.
- Class E was removed.
- Class Node was removed.
- Class V was removed.
Removed 14 classes.
Importing database info...OK
Importing clusters...
- Creating cluster 'internal'...OK, assigned id=0
- Creating cluster 'default'...OK, assigned id=3
- Creating cluster 'orole'...OK, assigned id=4
- Creating cluster 'ouser'...OK, assigned id=5
- Creating cluster 'ofunction'...OK, assigned id=6
- Creating cluster 'oschedule'...OK, assigned id=7
- Creating cluster 'orids'...OK, assigned id=8
- Creating cluster 'v'...OK, assigned id=9
- Creating cluster 'e'...OK, assigned id=10
- Creating cluster '_studio'...OK, assigned id=11
- Creating cluster 'node'...OK, assigned id=12
- Creating cluster 'root'...OK, assigned id=13
- Creating cluster 'broughtintoright'...OK, assigned id=14
- Creating cluster 'broughtintoleft'...OK, assigned id=15
- Creating cluster 'settings'...OK, assigned id=16
- Creating cluster 'cycle'...OK, assigned id=17
- Creating cluster 'de_business'...OK, assigned id=18
- Creating cluster 'de_root'...OK, assigned id=19
- Creating cluster 'de_cycle'...OK, assigned id=20
- Creating cluster 'de_settings'...OK, assigned id=21
- Creating cluster 'de_broughtintoleft'...OK, assigned id=22
- Creating cluster 'de_broughtintoright'...OK, assigned id=23
Rebuilding indexes of truncated clusters ...Error on database import happened just before line 0, column 955
com.orientechnologies.orient.core.exception.OCommandExecutionException: Index 'Node.Mid' not found
        at com.orientechnologies.orient.core.sql.OCommandExecutorSQLRebuildIndex.execute(OCommandExecutorSQLRebuildIndex.java:89)
        at com.orientechnologies.orient.core.sql.OCommandExecutorSQLDelegate.execute(OCommandExecutorSQLDelegate.java:64)
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.executeCommand(OAbstractPaginatedStorage.java:1189)
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.command(OAbstractPaginatedStorage.java:1178)
        at com.orientechnologies.orient.core.command.OCommandRequestTextAbstract.execute(OCommandRequestTextAbstract.java:63)
        at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.command(ONetworkProtocolBinary.java:1178)
        at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.executeRequest(ONetworkProtocolBinary.java:385)
        at com.orientechnologies.orient.server.network.protocol.binary.OBinaryNetworkProtocolAbstract.execute(OBinaryNetworkProtocolAbstract.java:220)
        at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:69)

Error: com.orientechnologies.orient.core.db.tool.ODatabaseExportException: Error on importing database 'bodyclub24' from file: C:\Users\starpetch\Desktop\bc24_prod.json

Error: com.orientechnologies.orient.core.exception.OCommandExecutionException: Index 'Node.Mid' not found
```

**Comment by tglman** [comment]
We have a known issue on remote import: https://github.com/orientechnologies/orientdb/issues/3528 that can cause also this problem, will solve this also in 2.2

**Comment by StarpTech** [comment]
thanks for the response.

**Comment by tglman** [comment]
closing as duplicate
