### ISSUE TITLE
Error on creating object of class with method like "get()"

### ISSUE THREAD

**Issue by hitakaken** [orientechnologies/orientdb#3874]
Hi,
When use OrientDB Object Interface, I have design a pojo like this:

> public class ObjectNode{
>    private Map children;
>    public ObjectNode(){}
>    public ObjectNode( Map kids) { children = kids; }
>    public Map getChildren() {return children; }
>    @Transient
>    public Object get(String key){return children.get(key);}
> }

when i use it,  will show exception like this:

> com.orientechnologies.orient.core.exception.ODatabaseException: Error on creating object of class ObjectNode
>   at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
>   at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
> ?   at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
>   at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
>   at com.orientechnologies.common.log.OLogManager.error(OLogManager.java:193)
>   at com.orientechnologies.orient.object.db.OObjectDatabaseTx.newInstance(OObjectDatabaseTx.java:172)
>   at com.orientechnologies.orient.object.db.OObjectDatabaseTx.newInstance(OObjectDatabaseTx.java:113)
>   at com.orientechnologies.orient.object.enhancement.OObjectEntitySerializer.serializeObject(OObjectEntitySerializer.java:122)
>   at com.orientechnologies.orient.object.enhancement.OObjectProxyMethodHandler.setValue(OObjectProxyMethodHandler.java:807)
>   at com.orientechnologies.orient.object.enhancement.OObjectProxyMethodHandler.manageSetMethod(OObjectProxyMethodHandler.java:729)
> Caused by: java.lang.StringIndexOutOfBoundsException: String index out of range: 3
>   at java.lang.String.charAt(String.java:658)
>   at com.orientechnologies.orient.object.enhancement.OObjectMethodFilter.getFieldName(OObjectMethodFilter.java:73)
>   at com.orientechnologies.orient.object.enhancement.OObjectMethodFilter.getFieldName(OObjectMethodFilter.java:59)
>   at com.orientechnologies.orient.object.enhancement.OObjectMethodFilter.isHandled(OObjectMethodFilter.java:35)
>   at javassist.util.proxy.ProxyFactory.computeSignature(ProxyFactory.java:846)
>   at javassist.util.proxy.ProxyFactory.createClass(ProxyFactory.java:398)
>   at com.orientechnologies.orient.object.enhancement.OObjectEntityEnhancer.getProxiedInstance(OObjectEntityEnhancer.java:98)
>   at com.orientechnologies.orient.object.db.OObjectDatabaseTx.newInstance(OObjectDatabaseTx.java:164)
>   ... 30 more

**Comment by hitakaken** [comment]
i guess the default OObjectMethodFilter try to use "get" as prefix ,but haven't check the method name's length
