### ISSUE TITLE
New Node with the same name as current

### ISSUE THREAD

**Issue by Briksins** [orientechnologies/orientdb#3893]
Hi

I'm playing around with cluster and did the fallowing steps

Created in Amazon 1st node instance - run it for first time with blank name (auto generated) to make sure it works. Stopped instance and created image
Created 2nd instance from image (or 2nd node if you like) 
Both nods get connected, but got the fallowing exception:

2015-04-08 15:57:17:909 WARNING [node1428504414825] added new node id=Member [172.31.16.23]:2434 name=ext:777fc065-5af5-48f0-a540-0b53d33cfe9e [OHazelcastPlugin]
2015-04-08 15:57:19:951 SEVERE [node1428504414825] Found a new node with the same name as current: 'node1428504414825'. The node has been excluded. Change the name in its config/orientdb-dserver-config.xml file [OHazelcastPlugin][172.31.16.22]:2434 [orientdb] [3.4.2] hz._hzInstance_1_orientdb.event-5 caught an exception while processing task:com.hazelcast.spi.impl.EventServiceImpl$LocalEventDispatcher@39b40c06
com.orientechnologies.orient.server.distributed.ODistributedException: Found a new node with the same name as current: 'node1428504414825'. The node has been excluded. Change the name in its config/orientdb-dserver-config.xml file
	at com.orientechnologies.orient.server.hazelcast.OHazelcastPlugin.entryAdded(OHazelcastPlugin.java:590)
	at com.hazelcast.map.impl.MapEventPublishingService.dispatch0(MapEventPublishingService.java:85)
	at com.hazelcast.map.impl.MapEventPublishingService.dispatchEntryEventData(MapEventPublishingService.java:64)
	at com.hazelcast.map.impl.MapEventPublishingService.dispatchEvent(MapEventPublishingService.java:39)
	at com.hazelcast.map.impl.MapEventPublishingService.dispatchEvent(MapEventPublishingService.java:17)
	at com.hazelcast.map.impl.MapService.dispatchEvent(MapService.java:76)
	at com.hazelcast.map.impl.MapService.dispatchEvent(MapService.java:51)
	at com.hazelcast.spi.impl.EventServiceImpl$LocalEventDispatcher.run(EventServiceImpl.java:666)
	at com.hazelcast.util.executor.StripedExecutor$Worker.process(StripedExecutor.java:190)
	at com.hazelcast.util.executor.StripedExecutor$Worker.run(StripedExecutor.java:174)

nodes names were saved into config file and file to overwrite itself with new random name

I believe nodes nodes have to handle random names automatically and not exclude nodes if name is similar

**Comment by lvca** [comment]
Node name is assigned at startup and you can change it by editing config/orientdb-server-config.xml. I suggest you to clone the image for 2nd node before node 1 starts.
