### ISSUE TITLE
SELECT .. ORDER BY syntax fails with nested fields

### ISSUE THREAD

**Issue by kowalot** [orientechnologies/orientdb#3907]
Having record

``` sql

+-------------------------------------------------------------------------------------------------+
| Document - @class: Film                                  @rid: #27:0           @version: 1      |
+-------------------------------------------------------------------------------------------------+
|                     Name | Value                                                                |
+-------------------------------------------------------------------------------------------------+
|                   Awards | [{Name:Oscar,Who:[2],Year:1995}]                                     |
|                   Budget | 1000000                                                              |
|                     Cast | [#42:0]                                                              |
|                 Colorful | true                                                                 |
|                 Director | #12:31231236567                                                      |
|                   Genres | [Thriller,Crime]                                                     |
|                    Plots | [a]bc,ab,abcd]                                                       |
|                   Poster | byte[8]                                                              |
|               References | [#24:0,#53:0,#456:4567]                                              |
|                 Released | Thu Apr 09 23:07:47 CEST 2015                                        |
|              SomeObjects | []                                                                   |
|      StarringActorsCount | 32000                                                                |
|       TheMostFamousAward | {Name:Oscar,Who:[2],Year:1995}                                       |
|                    Title | Pulp fiction                                                         |
|                     Year | 1234                                                                 |
+-------------------------------------------------------------------------------------------------+
```
and
``` sql
orientdb {db=test}> select TheMostFamousAward from #27:0

----+------+------------------------------
#   |@CLASS|TheMostFamousAward            
----+------+------------------------------
0   |null  |{Name:Oscar,Who:[2],Year:1995}
----+------+------------------------------

1 item(s) found. Query executed in 0.002 sec(s).
orientdb {db=test}> select TheMostFamousAward.Who from #27:0

----+------+------------------
#   |@CLASS|TheMostFamousAward
----+------+------------------
0   |null  |[2]               
----+------+------------------

1 item(s) found. Query executed in 0.002 sec(s).
orientdb {db=test}> select EXPAND(TheMostFamousAward.Who) from #27:0

----+------+---------+---------
#   |@CLASS|FirstName|LastName 
----+------+---------+---------
0   |null  |Quentin  |Tarantino
1   |null  |Roger    |Avary    
----+------+---------+---------
```
but SELECT .. ORDER BY syntax fails using current DEVELOP branch
``` sql

select EXPAND(TheMostFamousAward.Who) from Film ORDER BY FirstName


orientdb {db=test}> Error: com.orientechnologies.orient.core.exception.OCommandExecutionException: Error on execution of command: sql.select EXPAND(TheMostFamousAward.Who) from Film ORDER BY FirstName

Error: java.lang.ClassCastException: com.orientechnologies.common.collection.OMultiCollectionIterator cannot be cast to java.util.List


```
 
when 2.0.5 works
``` sql

orientdb {db=test}> select EXPAND(TheMostFamousAward.Who) from Film ORDER BY FirstName

----+------+---------+---------
#   |@CLASS|FirstName|LastName 
----+------+---------+---------
0   |null  |Quentin  |Tarantino
1   |null  |Roger    |Avary    
----+------+---------+---------

2 item(s) found. Query executed in 0.004 sec(s).
orientdb {db=test}> 
```

**Comment by PhantomYdn** [comment]
I guess "nested fields" might not be directly related to this issue. In my case I have following query:
```sql
select from OUser where name <> :other SKIP 0 ORDER BY name
```
As a result I see following:
```
2015-04-17 13:53:38:622 INFO  OrientDB Server v2.1-rc1 is active. [OServer]com.orientechnologies.orient.core.sql.parser.ParseException: Encountered " <ORDER> "ORDER "" at line 1, column 47.
Was expecting one of:
    <EOF> 
    <LIMIT> ...
    <TIMEOUT> ...
    <FETCHPLAN> ...
    <LOCK> ...
    <NOCACHE> ...
    <PARALLEL> ...
    ";" ...
    <LIMIT> ...
    <FETCHPLAN> ...
    <TIMEOUT> ...
    <LOCK> ...
    <PARALLEL> ...
    <NOCACHE> ...
    
	at com.orientechnologies.orient.core.sql.parser.OrientSql.generateParseException(OrientSql.java:11362)
	at com.orientechnologies.orient.core.sql.parser.OrientSql.jj_consume_token(OrientSql.java:11235)
```

That SQL worked perfectly on 2.0.x.

**Comment by lvca** [comment]
New SQL Parser is more strict. If you see the syntax SKIP goes after ORDER BY: https://github.com/orientechnologies/orientdb-docs/wiki/SQL-Query

**Comment by PhantomYdn** [comment]
@lvca original problem was not fix. Sorry for mixing 2 issues.

**Comment by kowalot** [comment]
The problem is still present and the error is clear :)
``` sql
Error: java.lang.ClassCastException: com.orientechnologies.common.collection.OMultiCollectionIterator cannot be cast to java.util.List
```
