### ISSUE TITLE
Compatibility problems between OrientDB 1.7.8 and 2.0.6

### ISSUE THREAD

**Issue by lvca** [orientechnologies/orientdb#3913]
It is very simply to reproduce the issue:
 
1.       Download 1.7.8, 2.0.6 community edition from: http://orientdb.com/download/

2.       Run console: ../orientdb-community-1.7.8/bin/console.bat

create database plocal:C:/OrientDB/orientdb-community-1.7.8/databases/test01 admin admin;

create database plocal:C:/OrientDB/orientdb-community-1.7.8/databases/test02 admin admin;

3.       Run  ../orientdb-community-1.7.8/bin/dserver.bat notice server start with no exception. Stop it.

4.       Copy directory: orientdb-community-1.7.8/databases into: ../orientdb-community-2.0.6/databases

5.       Run  ../orientdb-community-2.0.6/bin/dserver.bat notice exception:

 
2015-04-10 14:29:10:306 INFO  [node1428684304423] adding node 'node1428684304423' in partition: db=t
est02 [*] [OHazelcastDistributedDatabase]
2015-04-10 14:29:10:308 WARNING Error deserializing record YXV0b0RlcGxveTp0cnVlLGhvdEFsaWdubWVudDpmY
WxzZSxyZWFkUXVvcnVtOjEsd3JpdGVRdW9ydW06MixmYWlsdXJlQXZhaWxhYmxlTm9kZXNMZXNzUXVvcnVtOmZhbHNlLHJlYWRZb
3VyV3JpdGVzOnRydWUsY2x1c3RlcnM6KGludGVybmFsOigpLGluZGV4OigpLCo6KHNlcnZlcnM6WyI8TkVXX05PREU+Iiwibm9kZ
TE0Mjg2OTM2OTEzMzYiXSkpLHZlcnNpb246MA== send this data for debugging [ORecordSerializerBinary][10.12
5.3.47]:2434 [orientdb] [3.3] hz._hzInstance_1_orientdb.event-2 caught an exception while processing
task:com.hazelcast.spi.impl.EventServiceImpl$LocalEventDispatcher@e968b45
java.lang.ArrayIndexOutOfBoundsException: 97
        at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerialize
rBinary.fromStream(ORecordSerializerBinary.java:72)
        at com.orientechnologies.orient.core.record.impl.ODocument.deserializeFields(ODocument.java:
1755)
        at com.orientechnologies.orient.core.record.impl.ODocument.checkForFields(ODocument.java:218
7)
        at com.orientechnologies.orient.core.record.impl.ODocument.rawField(ODocument.java:834)
        at com.orientechnologies.orient.core.record.impl.ODocument.field(ODocument.java:854)
        at com.orientechnologies.orient.server.distributed.ODistributedAbstractPlugin.updateCachedDa
tabaseConfiguration(ODistributedAbstractPlugin.java:220)
        at com.orientechnologies.orient.server.hazelcast.OHazelcastPlugin.updateCachedDatabaseConfig
uration(OHazelcastPlugin.java:780)
        at com.orientechnologies.orient.server.hazelcast.OHazelcastPlugin.checkDatabaseEvent(OHazelc
astPlugin.java:1070)
        at com.orientechnologies.orient.server.hazelcast.OHazelcastPlugin.entryAdded(OHazelcastPlugi
n.java:607)
        at com.hazelcast.map.MapEventPublishingService.dispatch0(MapEventPublishingService.java:85)
        at com.hazelcast.map.MapEventPublishingService.dispatchEntryEventData(MapEventPublishingServ
ice.java:64)
        at com.hazelcast.map.MapEventPublishingService.dispatchEvent(MapEventPublishingService.java:
39)
        at com.hazelcast.map.MapEventPublishingService.dispatchEvent(MapEventPublishingService.java:
17)
        at com.hazelcast.map.MapService.dispatchEvent(MapService.java:76)
        at com.hazelcast.map.MapService.dispatchEvent(MapService.java:51)
        at com.hazelcast.spi.impl.EventServiceImpl$LocalEventDispatcher.run(EventServiceImpl.java:65
8)
        at com.hazelcast.util.executor.StripedExecutor$Worker.process(StripedExecutor.java:189)
        at com.hazelcast.util.executor.StripedExecutor$Worker.run(StripedExecutor.java:173)
 
2015-04-10 14:29:10:320 WARNING [node1428684304423] updated distributed configuration for database:
test02:
 
Thanks,
Vasil

**Comment by tglman** [comment]
fixed closing
