### ISSUE TITLE
a Null ResultSet returned from JDBC Driver

### ISSUE THREAD

**Issue by atboo** [orientechnologies/orientdb#3915]
The Exception detail message is below:
"Method threw 'java.lang.NullPointerException' exception. Cannot evaluate com.orientechnologies.orient.core.record.impl.ODocument.toString()"

The First found on jdbc driver version :2.0.4
Same occurred on version 2.0.6

**Comment by atboo** [comment]
Stack trace below:
at com.orientechnologies.orient.core.metadata.OMetadataDefault$ThreadLocalSchemaSnapshot.access$100(OMetadataDefault.java:279)
	at com.orientechnologies.orient.core.metadata.OMetadataDefault.clearThreadLocalSchemaSnapshot(OMetadataDefault.java:122)
	at com.orientechnologies.orient.core.record.impl.ODocument.getGlobalPropertyById(ODocument.java:1948)
	at com.orientechnologies.orient.core.record.impl.ODocumentInternal.getGlobalPropertyById(ODocumentInternal.java:55)
	at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinaryV0.getGlobalProperty(ORecordSerializerBinaryV0.java:275)
	at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinaryV0.deserialize(ORecordSerializerBinaryV0.java:175)
	at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinary.fromStream(ORecordSerializerBinary.java:74)
	at com.orientechnologies.orient.core.record.impl.ODocument.deserializeFields(ODocument.java:1754)
	at com.orientechnologies.orient.core.record.impl.ODocument.checkForFields(ODocument.java:2186)
	at com.orientechnologies.orient.core.record.impl.ODocument.fieldNames(ODocument.java:810)
	at com.orientechnologies.orient.jdbc.OrientJdbcResultSet.<init>(OrientJdbcResultSet.java:62)
	at com.orientechnologies.orient.jdbc.OrientJdbcStatement.execute(OrientJdbcStatement.java:112)
	at com.orientechnologies.orient.jdbc.OrientJdbcStatement.executeQuery(OrientJdbcStatement.java:118)

**Comment by lvca** [comment]
Please could you try with OrientDB 2.0.7-SNAPSHOT?

**Comment by atboo** [comment]
To reappear the issue,the scene is:
1.Create new property to an existence Class schema ,furthermore the class already have datas .
2.The previous data no default value set for the new property (NULL)
3.Query by sql via Jdbc.
4.A null resultset returned!

the data server is OrientDB-enterprise-2.0.3

Thanks.

**Comment by lvca** [comment]
@atboo seems the database was closed during that operation. Could you provide me 10 lines of code that reproduce the problem and I can run by myself?

**Comment by prjhub** [comment]
The issue has been closed because no response has been received after a while. In case the issue is still valid, please reopen it or write a comment that explains why it's still valid and a way to reproduce it. Thank you.
