### ISSUE TITLE
Sharding

### ISSUE THREAD

**Issue by vitorenesduarte** [orientechnologies/orientdb#3928]
Hi,

After #3578, now I'm trying to create edges between vertices that live in different nodes.
I'm using [this class](https://gist.github.com/vitorenesduarte/9cd79c64d6d2b591b415) to do that.
I create my schema with:
```sql
ALTER DATABASE CUSTOM useLightweightEdges = true
ALTER DATABASE MINIMUMCLUSTERS 2

create class User extends V
create property User.name string
alter cluster user_0 name user_usa
alter cluster user_1 name user_eur

create class Follows extends E
```
- [hazelcast.xml](https://gist.github.com/vitorenesduarte/8f821d50a0cb8a000d30)
- [default-distributed-db-config.json](https://gist.github.com/vitorenesduarte/244cc80ba0ced364bbe5)

But when I try to create an edge ([line A](https://gist.github.com/vitorenesduarte/9cd79c64d6d2b591b415#file-sharding2-java-L78)) I'm having this weird exception (full stack trace bellow):
```bash
Cannot update record '#13:0' because has been deleted
```

Besides that, `select from V` looks buggy (`select from User` returns more results). 
It looks like each node only returns records from subclasses of V (just User in this case) that live in that same node.

The ouput of the test class is:
```bash
0 : ok
1 : ok
2 : ok
3 : ok
4 : ok
5 : ok
6 : ok
7 : ok
8 : ok
9 : ok
10 : ok
11 : ok
12 : ko -> result : [mike]
13 : ko -> result : [phoebe]
Exception in thread "main" com.orientechnologies.orient.core.exception.OTransactionException: Cannot update record '#13:0' because has been deleted
	at com.orientechnologies.orient.server.distributed.ODistributedStorage.commit(ODistributedStorage.java:878)
	at com.orientechnologies.orient.core.tx.OTransactionOptimistic.doCommit(OTransactionOptimistic.java:483)
	at com.orientechnologies.orient.core.tx.OTransactionOptimistic.commit(OTransactionOptimistic.java:147)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.commit(ODatabaseDocumentTx.java:2406)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.commit(ODatabaseDocumentTx.java:2376)
	at com.tinkerpop.blueprints.impls.orient.OrientTransactionalGraph.commit(OrientTransactionalGraph.java:162)
	at com.orientechnologies.orient.graph.sql.OGraphCommandExecutorSQLFactory.runInTx(OGraphCommandExecutorSQLFactory.java:126)
	at com.orientechnologies.orient.graph.sql.OGraphCommandExecutorSQLFactory.runInTx(OGraphCommandExecutorSQLFactory.java:142)
	at com.orientechnologies.orient.graph.sql.OCommandExecutorSQLCreateEdge.execute(OCommandExecutorSQLCreateEdge.java:126)
	at com.orientechnologies.orient.core.sql.OCommandExecutorSQLDelegate.execute(OCommandExecutorSQLDelegate.java:64)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.executeCommand(OAbstractPaginatedStorage.java:1189)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.command(OAbstractPaginatedStorage.java:1178)
	at com.orientechnologies.orient.server.distributed.ODistributedStorage.command(ODistributedStorage.java:248)
	at com.orientechnologies.orient.core.command.OCommandRequestTextAbstract.execute(OCommandRequestTextAbstract.java:63)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.command(ONetworkProtocolBinary.java:1178)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.executeRequest(ONetworkProtocolBinary.java:385)
	at com.orientechnologies.orient.server.network.protocol.binary.OBinaryNetworkProtocolAbstract.execute(OBinaryNetworkProtocolAbstract.java:217)
	at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:69)
```
__v2.0.7__
Logs:
- [usa node](https://gist.github.com/vitorenesduarte/3cbf95a96fdd13129857)
- [eur node](https://gist.github.com/vitorenesduarte/d2d02c7a0635e8892a7f)

**Comment by lvca** [comment]
@vitorenesduarte Please can you retry with last 2.1-SNAPSHOT?

**Comment by vitorenesduarte** [comment]
Hi @lvca. Sorry, I have been busy at work. 
But I'll try to take a look at this till the end of the week.

**Comment by vitorenesduarte** [comment]
Hi @lvca. Sorry it took so long.

I had to change the test class to [this one](https://gist.github.com/vitorenesduarte/8e519e31a5aaf6c11011) because the one above does not seem to work now. 

The problem with `select from V`seems to be fixed but I still can't create the edge (the commit only seems to fix the first, so I guess it is normal the edge creation still fails).
```bash
Cannot update record '#13:0' because has been deleted
```

The new output is:
```bash
insert into cluster:user_usa set name = 'mike'
select from cluster:user_usa
0 : ok
select from cluster:user_eur
1 : ok
select from User
2 : ok
select from cluster:user_usa
3 : ok
select from cluster:user_eur
4 : ok
select from User
5 : ok
insert into cluster:user_eur set name = 'phoebe'
select from cluster:user_usa
6 : ok
select from cluster:user_eur
7 : ok
select from User
8 : ok
select from cluster:user_usa
9 : ok
select from cluster:user_eur
10 : ok
select from User
11 : ok
select from V
12 : ok
select from V
13 : ok
create edge Follows from (select from User where name = 'mike') to (select from User where name = 'phoebe')
Exception in thread "main" com.orientechnologies.orient.core.exception.OTransactionException: Cannot update record '#13:0' because has been deleted
	at com.orientechnologies.orient.server.distributed.ODistributedStorage.commit(ODistributedStorage.java:982)
	at com.orientechnologies.orient.core.tx.OTransactionOptimistic.doCommit(OTransactionOptimistic.java:596)
	at com.orientechnologies.orient.core.tx.OTransactionOptimistic.commit(OTransactionOptimistic.java:148)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.commit(ODatabaseDocumentTx.java:2543)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.commit(ODatabaseDocumentTx.java:2512)
	at com.tinkerpop.blueprints.impls.orient.OrientTransactionalGraph.commit(OrientTransactionalGraph.java:161)
	at com.orientechnologies.orient.graph.sql.OGraphCommandExecutorSQLFactory.runInTx(OGraphCommandExecutorSQLFactory.java:153)
	at com.orientechnologies.orient.graph.sql.OCommandExecutorSQLCreateEdge.execute(OCommandExecutorSQLCreateEdge.java:139)
	at com.orientechnologies.orient.core.sql.OCommandExecutorSQLDelegate.execute(OCommandExecutorSQLDelegate.java:90)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.executeCommand(OAbstractPaginatedStorage.java:1307)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.command(OAbstractPaginatedStorage.java:1288)
	at com.orientechnologies.orient.server.distributed.ODistributedStorage.command(ODistributedStorage.java:252)
	at com.orientechnologies.orient.core.command.OCommandRequestTextAbstract.execute(OCommandRequestTextAbstract.java:63)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.command(ONetworkProtocolBinary.java:1315)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.executeRequest(ONetworkProtocolBinary.java:397)
	at com.orientechnologies.orient.server.network.protocol.binary.OBinaryNetworkProtocolAbstract.execute(OBinaryNetworkProtocolAbstract.java:218)
	at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:71)
```


Logs:
- [usa node](https://gist.github.com/vitorenesduarte/bde772998b20416f11b7)
- [eur node](https://gist.github.com/vitorenesduarte/08d4e2f56733c66459cf)

**Comment by lvca** [comment]
I've created #4519 to fix this problem. Since the change would involve too much the distributed engine and we're close to the GA, I'm moving this issue to 2.2.

**Comment by lvca** [comment]
We did some fix on creating edges in shader env. I'll retry your test case soon.

**Comment by lvca** [comment]
Hey @vitorenesduarte all your tests pass with 2.1.6-SNAPSHOT. I've just pushed your test to be part of the suite: https://github.com/orientechnologies/orientdb/commit/f42af70dc5b4d92e17f9c169eb515385ed7c9fb5

**Comment by vitorenesduarte** [comment]
Cool.
Thank you for the feedback @lvca.
