### ISSUE TITLE
A out of memory exception raised on retrieving record via JDBC.

### ISSUE THREAD

**Issue by atboo** [orientechnologies/orientdb#3936]
My jvm using default memory usage space setting (64m),after several hours ,the "out of memory" exception raised on sql querying .I sure every resources in application had been released and closed appropriately.  if the issue is just occurred by memory allocation is too small, Could you talk  how many the memory allocation is recommend. 

Thanks a lot.
 
-------
The stack trace is following:

```
com.orientechnologies.orient.core.exception.ODatabaseException: Error on retrieving record #13:1956 (cluster: contact)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.executeReadRecord(ODatabaseDocumentTx.java:1605)
	at com.orientechnologies.orient.core.tx.OTransactionNoTx.loadRecord(OTransactionNoTx.java:80)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.load(ODatabaseDocumentTx.java:1424)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.load(ODatabaseDocumentTx.java:117)
	at com.orientechnologies.orient.core.id.ORecordId.getRecord(ORecordId.java:313)
	at com.tinkerpop.blueprints.impls.orient.OrientElement.getRecord(OrientElement.java:401)
	at com.tinkerpop.blueprints.impls.orient.OrientVertexIterator.filter(OrientVertexIterator.java:76)
	at com.tinkerpop.blueprints.impls.orient.OrientVertexIterator.filter(OrientVertexIterator.java:34)
	at com.orientechnologies.orient.core.iterator.OLazyWrapperIterator.hasNext(OLazyWrapperIterator.java:80)
	at com.orientechnologies.common.collection.OMultiCollectionIterator.hasNext(OMultiCollectionIterator.java:78)
	at com.orientechnologies.common.collection.OMultiCollectionIterator.hasNext(OMultiCollectionIterator.java:78)
	at com.orientechnologies.orient.core.sql.method.misc.OSQLMethodField.execute(OSQLMethodField.java:66)
	at com.orientechnologies.orient.core.sql.methods.OSQLMethodRuntime.execute(OSQLMethodRuntime.java:139)
	at com.orientechnologies.orient.core.sql.filter.OSQLFilterItemAbstract.transformValue(OSQLFilterItemAbstract.java:140)
	at com.orientechnologies.orient.core.sql.functions.OSQLFunctionRuntime.execute(OSQLFunctionRuntime.java:128)
	at com.orientechnologies.orient.core.sql.functions.OSQLFunctionRuntime.getValue(OSQLFunctionRuntime.java:142)
	at com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.applyExpand(OCommandExecutorSQLSelect.java:1778)
	at com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.execute(OCommandExecutorSQLSelect.java:392)
	at com.orientechnologies.orient.core.sql.OCommandExecutorSQLDelegate.execute(OCommandExecutorSQLDelegate.java:64)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.executeCommand(OAbstractPaginatedStorage.java:1184)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.command(OAbstractPaginatedStorage.java:1173)
	at com.orientechnologies.orient.core.command.OCommandRequestTextAbstract.execute(OCommandRequestTextAbstract.java:63)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.command(ONetworkProtocolBinary.java:1178)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.executeRequest(ONetworkProtocolBinary.java:385)
	at com.orientechnologies.orient.server.network.protocol.binary.OBinaryNetworkProtocolAbstract.execute(OBinaryNetworkProtocolAbstract.java:220)
	at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:69)
Caused by: java.lang.OutOfMemoryError: GC overhead limit exceeded
```

**Comment by atboo** [comment]
i check it's the server side exception.

Why doesn't exists the log timestamp for each exception in error log file,i don't know what time it's happened.
-----------

the log file contents is following:

>> Sent run-time exception to the client /121.40.154.189:45880: java.lang.OutOfMemoryError: GC overhead limit exceeded
>> java.lang.OutOfMemoryError: GC overhead limit exceeded
Error on client connection
>> java.lang.OutOfMemoryError: Java heap space
Sent run-time exception to the client /121.40.154.189:45919: java.lang.OutOfMemoryError: Java heap space
>> java.lang.OutOfMemoryError: Java heap space

**Comment by lvca** [comment]
How much memory did you reserve to the OrientDB Server?

**Comment by atboo** [comment]
i use default jvm settings when oom exception occurred,and now increased to 1024m.

**Comment by prjhub** [comment]
The issue has been closed because no response has been received after a while. In case the issue is still valid, please reopen it or write a comment that explains why it's still valid and a way to reproduce it. Thank you.
