### ISSUE TITLE
[OrientDB 2.0.7] NPE importing a DB created with OrientDB 1.5

### ISSUE THREAD

**Issue by giastfader** [orientechnologies/orientdb#3946]
Hi guys.
I have an export file created by OrientDB 1.5.
When I import this file in a new 2.0.7 database I have the following error:
```
Importing indexes ...
- Index '_BB_Node.id'...OKError on database import happened just before line 69, column 680
java.lang.NullPointerException
	at com.orientechnologies.orient.core.index.OSimpleKeyIndexDefinition.fromStream(OSimpleKeyIndexDefinition.java:149)
	at com.orientechnologies.orient.core.type.ODocumentWrapperNoClass.fromStream(ODocumentWrapperNoClass.java:45)
	at com.orientechnologies.orient.core.db.tool.ODatabaseImport.importIndexDefinition(ODatabaseImport.java:1426)
	at com.orientechnologies.orient.core.db.tool.ODatabaseImport.importIndexes(ODatabaseImport.java:1350)
	at com.orientechnologies.orient.core.db.tool.ODatabaseImport.importDatabase(ODatabaseImport.java:427)
	at com.orientechnologies.orient.console.OConsoleDatabaseApp.importDatabase(OConsoleDatabaseApp.java:1539)
	at com.orientechnologies.orient.graph.console.OGremlinConsole.importDatabase(OGremlinConsole.java:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.orientechnologies.common.console.OConsoleApplication.execute(OConsoleApplication.java:381)
	at com.orientechnologies.common.console.OConsoleApplication.executeCommands(OConsoleApplication.java:246)
	at com.orientechnologies.common.console.OConsoleApplication.run(OConsoleApplication.java:135)
	at com.orientechnologies.orient.graph.console.OGremlinConsole.main(OGremlinConsole.java:62)
```

**Comment by lvca** [comment]
Have you tried using 1.7.x version?

**Comment by lvca** [comment]
The issue has been closed because no response has been received after a while. In case the issue is still valid, please reopen it or write a comment that explains why it's still valid and a way to reproduce it. Thank you.
