### ISSUE TITLE
Prepared queries are not working for DDL

### ISSUE THREAD

**Issue by pshirshov** [orientechnologies/orientdb#3949]
``` scala
val graph: OrientGraphNoTx = ...
val command = new OCommandSQL("CREATE INDEX :iname ON :cname ( :pname by key ) UNIQUE")
val request = graph.command(command)
val v = "someclass"        

val map: ImmutableMap[String, String] = ImmutableMap.of(
"iname", s"index-$v-name-key",
"cname", v,
"pname", "name"
)
request.execute(map)
```

Produces the following exception:

```
Tester$ - can't create index someclass
com.orientechnologies.orient.core.exception.OCommandExecutionException: Class :CNAME not found
    at com.orientechnologies.orient.core.sql.OCommandExecutorSQLCreateIndex.parse(OCommandExecutorSQLCreateIndex.java:110)
    at com.orientechnologies.orient.core.sql.OCommandExecutorSQLCreateIndex.parse(OCommandExecutorSQLCreateIndex.java:56)
    at com.orientechnologies.orient.core.sql.OCommandExecutorSQLDelegate.parse(OCommandExecutorSQLDelegate.java:56)
    at com.orientechnologies.orient.core.sql.OCommandExecutorSQLDelegate.parse(OCommandExecutorSQLDelegate.java:37)
    at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.command(OAbstractPaginatedStorage.java:1176)
    at com.orientechnologies.orient.core.command.OCommandRequestTextAbstract.execute(OCommandRequestTextAbstract.java:63)
    at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.command(ONetworkProtocolBinary.java:1178)
    at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.executeRequest(ONetworkProtocolBinary.java:385)
    at com.orientechnologies.orient.server.network.protocol.binary.OBinaryNetworkProtocolAbstract.execute(OBinaryNetworkProtocolAbstract.java:220)
    at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:69)
```

Immutable map is Guava's helper for java.util.Map instantiation.

``` scala
graph.createKeyIndex("name", classOf[Vertex], new Parameter("class", v), new Parameter("type", "unique"))
```

works correctly.

**Comment by lvca** [comment]
This isn't supported yet, because the new parser only works with SELECT.

**Comment by lvca** [comment]
Not relevant anymore, closing it.

**Comment by pshirshov** [comment]
Not relevant bcs of a fix or noone interested?
