### ISSUE TITLE
[2.1]SEVERE Internal server error when updated the system(Database does not open)

### ISSUE THREAD

**Issue by jiujiu1123** [orientechnologies/orientdb#3954]
Hi, I just updated my orientdb to 2.1 but when I try to access my database, 
```
2015-04-18 23:57:39:829 SEVERE Internal server error:
com.orientechnologies.common.exception.OException: Error on creation of shared resource
--> com.orientechnologies.orient.core.exception.OSchemaException: Can't add base class 'notifriend', because of paramaters conflict: message (type=STRING) vs message (type=STRING) [ONetworkProtocolHttpDb]
```
pops up.  The database was previously created in orientdb 2.0 rc1 then updated to orientdb 2.07 (re exported and imported). 
reimport also doesn't work 
```
Importing database schema...Error on importing schema
com.orientechnologies.orient.core.exception.OSchemaException: Can't add base class 'notifriend', because of paramaters conflict: time (type=DATETIME) vs time (type=DATETIME)
	at com.orientechnologies.orient.core.metadata.schema.OClassImpl.checkParametersConflict(OClassImpl.java:2306)
	at com.orientechnologies.orient.core.metadata.schema.OClassImpl.addBaseClass(OClassImpl.java:2288)
	at com.orientechnologies.orient.core.metadata.schema.OClassImpl.setSuperClassesInternal(OClassImpl.java:475)
	at com.orientechnologies.orient.core.metadata.schema.OClassImpl.setSuperClasses(OClassImpl.java:448)
	at com.orientechnologies.orient.core.metadata.schema.OClassImpl.setSuperClassesByNames(OClassImpl.java:417)
	at com.orientechnologies.orient.core.metadata.schema.OClassImpl.set(OClassImpl.java:1514)
	at com.orientechnologies.orient.core.sql.OCommandExecutorSQLAlterClass.execute(OCommandExecutorSQLAlterClass.java:113)
	at com.orientechnologies.orient.core.sql.OCommandExecutorSQLDelegate.execute(OCommandExecutorSQLDelegate.java:83)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.executeCommand(OAbstractPaginatedStorage.java:1182)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.command(OAbstractPaginatedStorage.java:1163)
	at com.orientechnologies.orient.core.command.OCommandRequestTextAbstract.execute(OCommandRequestTextAbstract.java:63)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.command(ONetworkProtocolBinary.java:1172)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.executeRequest(ONetworkProtocolBinary.java:372)
	at com.orientechnologies.orient.server.network.protocol.binary.OBinaryNetworkProtocolAbstract.execute(OBinaryNetworkProtocolAbstract.java:221)
	at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:69)
ERROR (69 entries): com.orientechnologies.orient.core.exception.OSchemaException: Can't add base class 'notifriend', because of paramaters conflict: time (type=DATETIME) vs time (type=DATETIME)

```

**Comment by lvca** [comment]
OrientDB is never compatible with older versions. If you are forced to do it, edit the JSON and remove the multiple inheritance to set only "superClass" (one class)
