### ISSUE TITLE
java.lang.IndexOutOfBoundsException: Index: 0, Size: -1

### ISSUE THREAD

**Issue by dblaber** [orientechnologies/orientdb#3957]
I have a test application that is writing to many different databases of a couple different servers(everything remote). I am using OPartitionedDatabasePoolFactory, and again getting the pool and db from 3 db servers, and 3 databases on each server.  There is a great deal of concurrent access to OPartitionedDatabasePoolFactory and OPartitionedDatabasePool (these are threadsafe object right), however I seem to get the following at a random point when trying issue a query:
com.orientechnologies.orient.core.exception.OStorageException: Error on executing command: sql.select from GridElement where MapName = ? AND Key = ?
        at com.orientechnologies.orient.client.remote.OStorageRemote.handleException(OStorageRemote.java:1507)
        at com.orientechnologies.orient.client.remote.OStorageRemote.command(OStorageRemote.java:1065)
        at com.orientechnologies.orient.client.remote.OStorageRemoteThread.command(OStorageRemoteThread.java:436)
        at com.orientechnologies.orient.core.sql.query.OSQLQuery.run(OSQLQuery.java:71)
        at com.orientechnologies.orient.core.sql.query.OSQLSynchQuery.run(OSQLSynchQuery.java:85)
        at com.orientechnologies.orient.core.query.OQueryAbstract.execute(OQueryAbstract.java:33)
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.query(ODatabaseDocumentTx.java:630)
        at com.someorg.common.orientdbmapimpl.OrientDBAgentManager$MapBatchLoader.run(OrientDBAgentManager.java:99)
        at com.someorg.common.orientdbmapimpl.ParallelExecutor$Runner.run(ParallelExecutor.java:80)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IndexOutOfBoundsException: Index: 0, Size: -1
        at java.util.ArrayList.rangeCheck(ArrayList.java:653)
        at java.util.ArrayList.get(ArrayList.java:429)
        at com.orientechnologies.orient.client.remote.OStorageRemote.getCurrentServerURL(OStorageRemote.java:1830)
        at com.orientechnologies.orient.client.remote.OStorageRemote.beginRequest(OStorageRemote.java:1812)
        at com.orientechnologies.orient.client.remote.OStorageRemote.command(OStorageRemote.java:976)
This is occurring at the client, there is nothing in the server logs, and there is only one ODatabaseDocumentTx per thread.  As a java developer, I have never seen IndexOutOfBounds exception and seen a size of -1, so only thing I can guess is that the arraylist is not being used in thread safe manner, corrupting the list.

**Comment by lvca** [comment]
What OrientDB version? Please specify always the version.

**Comment by dblaber** [comment]
Sorry, version is 2.0.5, oracle jre 1.8.0_40 on solaris.
