### ISSUE TITLE
v2.1-rc1 Reactive Queries Error with nodejs oriento

### ISSUE THREAD

**Issue by sparkycrisse** [orientechnologies/orientdb#3966]
With the new RC I wanted to try out the exciting reactive queries in combination with node following the instructions in this [slideShare presentation](http://www.slideshare.net/LuigiDellAquila/fully-reactive-from-data-to-ui-with-orientdb-nodejs-socketio).
However, after one update is being sent correctly to the node server, then an error is thrown in the OrientDB console window. Any thoughts on this?

```
Cannot push cluster configuration to the client 141.135.172.254:55608
com.orientechnologies.orient.core.exception.ODatabaseException: Database instance is not set in current thread. Assure to set it with: ODatabaseRecordThreadLocal.INSTANCE.set(db);
	at com.orientechnologies.orient.core.db.ODatabaseRecordThreadLocal.get(ODatabaseRecordThreadLocal.java:54)
	at com.orientechnologies.orient.core.db.record.ridbag.ORidBag.toStream(ORidBag.java:236)
	at com.orientechnologies.orient.core.db.record.ridbag.ORidBag.toStream(ORidBag.java:271)
	at com.orientechnologies.orient.core.serialization.serializer.record.string.ORecordSerializerCSVAbstract.fieldToStream(ORecordSerializerCSVAbstract.java:556)
	at com.orientechnologies.orient.core.serialization.serializer.record.string.ORecordSerializerSchemaAware2CSV.toString(ORecordSerializerSchemaAware2CSV.java:506)
	at com.orientechnologies.orient.core.serialization.serializer.record.string.ORecordSerializerStringAbstract.toStream(ORecordSerializerStringAbstract.java:691)
	at com.orientechnologies.orient.core.serialization.serializer.record.string.ORecordSerializerSchemaAware2CSV.toStream(ORecordSerializerSchemaAware2CSV.java:268)
	at com.orientechnologies.orient.core.record.impl.ODocument.toStream(ODocument.java:2169)
	at com.orientechnologies.orient.core.record.impl.ODocument.toStream(ODocument.java:670)
	at com.orientechnologies.orient.server.network.protocol.binary.OBinaryNetworkProtocolAbstract.getRecordBytes(OBinaryNetworkProtocolAbstract.java:421)
	at com.orientechnologies.orient.server.network.protocol.binary.OLiveCommandResultListener.onLiveResult(OLiveCommandResultListener.java:130)
	at com.orientechnologies.orient.core.sql.OCommandExecutorSQLLiveSelect.onLiveResult(OCommandExecutorSQLLiveSelect.java:115)
	at com.orientechnologies.orient.core.query.live.OLiveQueryQueueThread.run(OLiveQueryQueueThread.java:40)

**Comment by luigidellaquila** [comment]
Hi @sparkycrisse 

The error is due to the fact that RidBag serialization requires a db instance set in current thread, and at this moment it's not. Fortunately the active db is available in OCommandExecutorSQLLiveSelect, so it can be fixed quickly.

**Comment by luigidellaquila** [comment]
I applied a fix in develop branch. Could you please confirm that it fixes your case?
In case please reopen 

Thanks

**Comment by sparkycrisse** [comment]
Well now i get the following error in Oriento using the development branch :/

````
Unhandled rejection OrientDB.RequestError: Cannot find a command executor for the command request: sql.live select from Action
    at Operation.parseError (/Users/christopher/node_modules/oriento/lib/transport/binary/protocol28/operation.js:873:13)
    at Operation.consume (/Users/christopher/node_modules/oriento/lib/transport/binary/protocol28/operation.js:463:35)
    at Connection.process (/Users/christopher/node_modules/oriento/lib/transport/binary/connection.js:380:17)
    at Connection.handleSocketData (/Users/christopher/node_modules/oriento/lib/transport/binary/connection.js:281:17)
    at Socket.emit (events.js:95:17)
    at Socket.<anonymous> (_stream_readable.js:764:14)
    at Socket.emit (events.js:92:17)
    at emitReadable_ (_stream_readable.js:426:10)
    at emitReadable (_stream_readable.js:422:5)
    at readableAddChunk (_stream_readable.js:165:9)
    at Socket.Readable.push (_stream_readable.js:127:10)
    at TCP.onread (net.js:528:21)
````

This is my Node.JS Code: 

````` javascript

var Oriento = require('oriento');

var server = Oriento({
	

	host: 'localhost',
	port: '2424',
	username: 'root',
	password: 'hello'
});


console.log("Oriento Test");

var db = server.use({
	name:'testDb',
	username: 'root',
	password: 'hello'
});


db.liveQuery("live select from Action")
	.on('live-insert',function(data){

		console.log("Action Data was inserted!");
	});
`````
