### ISSUE TITLE
Problems creating properties for class "is" 

### ISSUE THREAD

**Issue by andreyvk** [orientechnologies/orientdb#3972]
Hi there,

I've just tried out OrientDB 2.1-rc1. We have a class which is called ```is```. It's an edge. I was running a db initialization script, when it failed on creating ```is.type``` property with the following error:

```
Error: com.orientechnologies.orient.core.sql.OCommandSQLParsingException: Error on parsing command at position #0: Encountered " <FROM> "from "" at line 1, column 17.
Was expecting one of:
    <EOF>
    <TIMEOUT> ...
    <AS> ...
    <FETCHPLAN> ...
    <LOCK> ...
    <LET> ...
    <NOCACHE> ...
    <PARALLEL> ...
    ";" ...
    "," ...
    <AS> ...
    "," ...
```

That did not happen in 2.0.x. Is this an expected behavior? If yes, then how can I escape class name so that command goes through?

**Comment by nagarajasr** [comment]
seems to me an issue with the new parser in 2.1:
here is the server side stack trace, for some strange reason the create property command is getting parsed as a select query:

        at com.orientechnologies.orient.core.sql.OCommandExecutorSQLAbstract.throwParsingException(OCommandExecutorSQLAbstract.java:99)
        at com.orientechnologies.orient.core.sql.OCommandExecutorSQLAbstract.preParse(OCommandExecutorSQLAbstract.java:244)
        at com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.parse(OCommandExecutorSQLSelect.java:217)
        at com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.parse(OCommandExecutorSQLSelect.java:100)
        at com.orientechnologies.orient.core.sql.OCommandExecutorSQLDelegate.parse(OCommandExecutorSQLDelegate.java:74)
        at com.orientechnologies.orient.core.sql.OCommandExecutorSQLDelegate.parse(OCommandExecutorSQLDelegate.java:40)
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.command(OAbstractPaginatedStorage.java:1161)
        at com.orientechnologies.orient.core.command.OCommandRequestTextAbstract.execute(OCommandRequestTextAbstract.java:63)
        at com.orientechnologies.orient.core.metadata.schema.OClassImpl.checkPersistentPropertyType(OClassImpl.java:1867)
        at com.orientechnologies.orient.core.metadata.schema.OClassImpl.addPropertyInternal(OClassImpl.java:1568)
        at com.orientechnologies.orient.core.sql.OCommandExecutorSQLCreateProperty.execute(OCommandExecutorSQLCreateProperty.java:140)
        at com.orientechnologies.orient.core.sql.OCommandExecutorSQLDelegate.execute(OCommandExecutorSQLDelegate.java:83)
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.executeCommand(OAbstractPaginatedStorage.java:1182)
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.command(OAbstractPaginatedStorage.java:1163)
        at com.orientechnologies.orient.core.command.OCommandRequestTextAbstract.execute(OCommandRequestTextAbstract.java:63)
        at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.command(ONetworkProtocolBinary.java:1172)
        at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.executeRequest(ONetworkProtocolBinary.java:372)
        at com.orientechnologies.orient.server.network.protocol.binary.OBinaryNetworkProtocolAbstract.execute(OBinaryNetworkProtocolAbstract.java:221)
        at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:69)

**Comment by andreyvk** [comment]
So it's a bug then. Here's a test case. Forgot to include in the initial post:

```
create class is extends E
create property is.type string
```

**Comment by nagarajasr** [comment]
the code for create property internally does some checks against the property being created, one of those is to check if there is already schema-less data present in the database, having different data type:

"The database contains some schema-less data in the property '" + name + "." + propertyName
          + "' that is not compatible with the type " + type + ". Fix those records and change the schema again"

this causes the following query to be formed internally:
select count(*) from is where type.type() not in ["STRING"] and type is not null

At this point the new parser in 2.1-rc1 encounters the keyword IS immediately after FROM which is unexpected.

I noticed that "IS" is not a reserved keyword in OrientSQL.jj, not sure if that is on purpose? by declaring IS as a reserved word, it can prevent creation of class/ cluster/ index with name as "IS". i'm not sure if the problem runs deeper than that.

**Comment by Wanderfalke** [comment]
I'm having the same problem with edge-class called "edge".

**Comment by benjaminbillet** [comment]
Same problem with a vertex/edge called Like, Desc or any other OrientDB SQL keyword.

**Comment by luigidellaquila** [comment]
Hi,

"is" is not marked as a reserved word but it actually is (I'm going to fix this).
Anyway creating a property called "is" should be allowed, so I'm going to fix the whole problem too.
Using reserved words in queries is allowed using backtick quoting.

**Comment by benjaminbillet** [comment]
Hi,
Quoting can be a solution for queries, however the bug is affecting the Java API as well probably because the Java API builds queries without quoting.

For example, this simple code fails with 2.1-rc4:
graph.createVertexType("Like").createProperty("anything", ...);

**Comment by luigidellaquila** [comment]
Hi @benjaminbillet 
yes, it's exactly what's happening here

**Comment by luigidellaquila** [comment]
fixed in develop branch
