### ISSUE TITLE
java.lang.Character can not be serialized

### ISSUE THREAD

**Issue by dblaber** [orientechnologies/orientdb#3989]
In orientdb 8.0.5 (and probably up), if the class that was registered with entityManager has a java.lang.Character in it, and then saved in .OObjectDatabaseTx.save() will receive the following exception:
com.orientechnologies.orient.core.exception.OSerializationException: Linked type [class java.lang.Character:P] cannot be serialized because is not part of registered entities. To fix this error register this class
        at com.orientechnologies.orient.object.enhancement.OObjectEntitySerializer.typeToStream(OObjectEntitySerializer.java:752)
        at com.orientechnologies.orient.object.enhancement.OObjectEntitySerializer.toStream(OObjectEntitySerializer.java:1160)
        at com.orientechnologies.orient.object.enhancement.OObjectEntitySerializer.serializeObject(OObjectEntitySerializer.java:124)
        at com.orientechnologies.orient.object.db.OObjectDatabaseTx.save(OObjectDatabaseTx.java:432)
        at com.orientechnologies.orient.object.db.OObjectDatabaseTx.save(OObjectDatabaseTx.java:377)
        at com.someorg.common.orientdbmapimpl.OrientDBAgentManager$MapBatchLoader.run(OrientDBAgentManager.java:134)
        at com.someorg.common.orientdbmapimpl.ParallelExecutor$Runner.run(ParallelExecutor.java:80)
        at java.lang.Thread.run(Thread.java:745)

**Comment by dblaber** [comment]
This also seems to happen if the primitive char is is in the pojo i am trying to save.

**Comment by tglman** [comment]
Actually OrientDB don't really support the type char/Character, and if you set that will be translated and stored as a String, so if you get troubles, i'll suggest to use Strings instead.

**Comment by tglman** [comment]
Hi,

Character are not supported and there is no plan to support them, closing this.

Regarads
