### ISSUE TITLE
NumberFormatException when select contains an expression with a LONG value

### ISSUE THREAD

**Issue by fabriziofortino** [orientechnologies/orientdb#3995]
The new parser in 2.1-SNAPSHOT throws the below Exception when the select statement contains an expression with a LONG value (eg: select from MYCLASS where MYPROP >= 1429655550616). The Exception is raised even when the class property type is LONG.

Sent run-time exception to the client /127.0.0.1:62267: java.lang.NumberFormatException: For input string: "1429655550616"
java.lang.NumberFormatException: For input string: "1429655550616"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Integer.parseInt(Integer.java:583)
	at java.lang.Integer.parseInt(Integer.java:615)
	at com.orientechnologies.orient.core.sql.parser.OrientSql.Integer(OrientSql.java:208)
	at com.orientechnologies.orient.core.sql.parser.OrientSql.Number(OrientSql.java:262)
	at com.orientechnologies.orient.core.sql.parser.OrientSql.BaseExpression(OrientSql.java:4165)
	at com.orientechnologies.orient.core.sql.parser.OrientSql.FirstLevelExpression(OrientSql.java:4043)
	at com.orientechnologies.orient.core.sql.parser.OrientSql.MultExpression(OrientSql.java:3972)
	at com.orientechnologies.orient.core.sql.parser.OrientSql.MathExpression(OrientSql.java:3907)
	at com.orientechnologies.orient.core.sql.parser.OrientSql.Expression(OrientSql.java:3850)
	at com.orientechnologies.orient.core.sql.parser.OrientSql.BinaryCondition(OrientSql.java:5239)
	at com.orientechnologies.orient.core.sql.parser.OrientSql.ConditionBlock(OrientSql.java:4869)
	at com.orientechnologies.orient.core.sql.parser.OrientSql.NotBlock(OrientSql.java:4772)
	at com.orientechnologies.orient.core.sql.parser.OrientSql.AndBlock(OrientSql.java:4676)
	at com.orientechnologies.orient.core.sql.parser.OrientSql.OrBlock(OrientSql.java:4626)
	at com.orientechnologies.orient.core.sql.parser.OrientSql.WhereClause(OrientSql.java:4591)
	at com.orientechnologies.orient.core.sql.parser.OrientSql.SelectStatement(OrientSql.java:537)
	at com.orientechnologies.orient.core.sql.parser.OrientSql.Statement(OrientSql.java:304)
	at com.orientechnologies.orient.core.sql.parser.OrientSql.parse(OrientSql.java:87)
	at com.orientechnologies.orient.core.sql.OCommandExecutorSQLAbstract.preParse(OCommandExecutorSQLAbstract.java:234)
	at com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.parse(OCommandExecutorSQLSelect.java:217)
	at com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.parse(OCommandExecutorSQLSelect.java:100)
	at com.orientechnologies.orient.core.sql.OCommandExecutorSQLDelegate.parse(OCommandExecutorSQLDelegate.java:74)
	at com.orientechnologies.orient.core.sql.OCommandExecutorSQLDelegate.parse(OCommandExecutorSQLDelegate.java:40)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.command(OAbstractPaginatedStorage.java:1161)
	at com.orientechnologies.orient.core.sql.query.OSQLQuery.run(OSQLQuery.java:72)
	at com.orientechnologies.orient.core.sql.query.OSQLSynchQuery.run(OSQLSynchQuery.java:85)
	at com.orientechnologies.orient.core.query.OQueryAbstract.execute(OQueryAbstract.java:33)

**Comment by luigidellaquila** [comment]
fixed in develop branch
