### ISSUE TITLE
 Error on fetching record during browsing. The record has been skipped and seems deadlock

### ISSUE THREAD

**Issue by atboo** [orientechnologies/orientdb#4007]
Hey，

I use the sql to query records from web studio,the page shows a long period progressing with no responding. and be forced to interrupt at finally.

version 2.0.7 enterprise

the following exceptions found in orientdb.err

```
 Error on fetching record during browsing. The record has been skipped
com.orientechnologies.orient.core.exception.ODatabaseException: Error on retrieving record #12:2584 (cluster: user)
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.executeReadRecord(ODatabaseDocumentTx.java:1613)
        at com.orientechnologies.orient.core.tx.OTransactionNoTx.loadRecord(OTransactionNoTx.java:80)
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.load(ODatabaseDocumentTx.java:1445)
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.load(ODatabaseDocumentTx.java:118)
        at com.orientechnologies.orient.core.iterator.OIdentifiableIterator.readCurrentRecord(OIdentifiableIterator.java:278)
        at com.orientechnologies.orient.core.iterator.ORecordIteratorClusters.hasNext(ORecordIteratorClusters.java:147)
        at com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.fetchFromTarget(OCommandExecutorSQLSelect.java:1298)
        at com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.executeSearch(OCommandExecutorSQLSelect.java:433)
        at com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.iterator(OCommandExecutorSQLSelect.java:355)
        at com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.iterator(OCommandExecutorSQLSelect.java:348)
        at com.orientechnologies.orient.core.sql.OCommandExecutorSQLResultsetDelegate.iterator(OCommandExecutorSQLResultsetDelegate.java:45)
        at com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.optimizeExecution(OCommandExecutorSQLSelect.java:1030)
        at com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.execute(OCommandExecutorSQLSelect.java:388)
        at com.orientechnologies.orient.core.sql.OCommandExecutorSQLDelegate.execute(OCommandExecutorSQLDelegate.java:64)
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.executeCommand(OAbstractPaginatedStorage.java:1189)
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.command(OAbstractPaginatedStorage.java:1178)
        at com.orientechnologies.orient.core.command.OCommandRequestTextAbstract.execute(OCommandRequestTextAbstract.java:63)
        at com.orientechnologies.orient.server.network.protocol.http.command.post.OServerCommandPostCommand.execute(OServerCommandPostCommand.java:81)
        at com.orientechnologies.orient.server.network.protocol.http.ONetworkProtocolHttpAbstract.service(ONetworkProtocolHttpAbstract.java:174)
        at com.orientechnologies.orient.server.network.protocol.http.ONetworkProtocolHttpAbstract.execute(ONetworkProtocolHttpAbstract.java:574)
        at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:69)
Caused by: com.orientechnologies.common.concur.OTimeoutException: Can not lock record for 2000 ms. seems record is deadlocked by other record
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.acquireReadLock(OAbstractPaginatedStorage.java:1313)
        at com.orientechnologies.orient.core.tx.OTransactionAbstract.lockRecord(OTransactionAbstract.java:120)
        at com.orientechnologies.orient.core.id.ORecordId.lock(ORecordId.java:282)
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.lockRecord(OAbstractPaginatedStorage.java:1784)
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.readRecord(OAbstractPaginatedStorage.java:1430)
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.readRecord(OAbstractPaginatedStorage.java:694)
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.executeReadRecord(ODatabaseDocumentTx.java:1580)
        ... 20 more
```
ps. i use my own connections pool based on apache common pools. is this the vital cause of failure in deadlock?

Make own pool，because，jdbc connection borrow failed from original pool in orientdb frequently (can not get any available connection from pool ). but it works fine when using apache common pool.

the pool code is following

```java
public class Pool {

//    String url=null;
//    Properties info=null;
    Field rawResultField=null;
    Log log = LogFactory.getLog(Pool.class);

    private GenericObjectPool<MyOrientJdbcConnection> internalPool;

    public Pool(SysProps props){

// the former definition for original pool in oriented
//        try {
//            Class.forName(props.getPropValue("orient_db_driver"));
//        } catch (ClassNotFoundException e) {
//            log.error(this,e);
//        }
//
//        this.url=props.getPropValue("orient_db_url");
//        info = new Properties();
//        info.put("user", props.getPropValue("orient_db_user"));
//        info.put("password", props.getPropValue("orient_db_password"));
//        info.put("db.usePool",props.getPropValue("orient_db_use_pool"));
//        info.put("db.pool.min", props.getPropValue("orient_db_pool_min"));   // MINIMUM POOL SIZE
//        info.put("db.pool.max", props.getPropValue("orient_db_pool_max"));  // MAXIMUM POOL SIZE

        try {
            rawResultField = OrientJdbcStatement.class.getDeclaredField("rawResult");
            rawResultField.setAccessible(true);
        }catch (Exception e){
            log.error(this,e);
        }

        GenericObjectPoolConfig config=new GenericObjectPoolConfig();
        int maxTotal=Integer.parseInt(props.getPropValue("orient_db_pool_max"));
        int minTotal=Integer.parseInt(props.getPropValue("orient_db_pool_min"));

        config.setMaxTotal(maxTotal);
        config.setMaxIdle(maxTotal - 10);
        config.setMinIdle(minTotal);
        config.setMaxWaitMillis(10000);
        //config.setTestOnBorrow(true);

        internalPool=new GenericObjectPool<MyOrientJdbcConnection>(new PoolFactory(),config);
        System.getProperties().put("orientdb_pool_" + Pool.class.getClassLoader().hashCode(), this);
        //Connection conn = (OrientJdbcConnection) DriverManager.getConnection("jdbc:orient:remote:localhost/test", info);




    }

    public static Pool getPool(){
        Pool pool= (Pool)System.getProperties().get("orientdb_pool_"+Pool.class.getClassLoader().hashCode());
        if(pool==null){
            return new Pool(SysProps.getProps());
        }
        return pool;
    }

    public MyOrientJdbcConnection getConnection() throws Exception {
        return this.internalPool.borrowObject();

    }


    public void returnConnection(MyOrientJdbcConnection conn){
        if(conn==null) return;
        this.internalPool.returnObject(conn);
    }

    public Field getRawResultField() {
        return rawResultField;
    }

    public long getCreatedCount(){
        return this.internalPool.getCreatedCount();
    }

    public long getDestoryedCount(){
        return this.internalPool.getDestroyedCount();
    }
}

```

The pool factory class code is following:

```java
public class PoolFactory implements PooledObjectFactory {

    private String url = null;
    private SysProps props;
    private Properties info;

    public PoolFactory() {
        props = SysProps.getProps();
        this.url = props.getPropValue("orient_db_url");
        info = new Properties();
        info.put("user", props.getPropValue("orient_db_user"));
        info.put("password", props.getPropValue("orient_db_password"));
        info.put("db.usePool", props.getPropValue("orient_db_use_pool"));
        info.put("db.pool.min", props.getPropValue("orient_db_pool_min"));   // MINIMUM POOL SIZE
        info.put("db.pool.max", props.getPropValue("orient_db_pool_max"));  // MAXIMUM POOL SIZE
    }

    @Override
    public PooledObject makeObject() throws Exception {
        final MyOrientJdbcConnection conn = new MyOrientJdbcConnection(url, info);
        return new DefaultPooledObject<OrientJdbcConnection>(conn);
    }

    @Override
    public void destroyObject(PooledObject pooledObject) throws Exception {
        MyOrientJdbcConnection conn = (MyOrientJdbcConnection) pooledObject.getObject();
        if (conn != null)
            conn.close();
    }

    @Override
    public boolean validateObject(PooledObject pooledObject) {
        MyOrientJdbcConnection conn = (MyOrientJdbcConnection) pooledObject.getObject();
        if(conn==null)return false;
        try {
            return !conn.isClosed();
        }catch (SQLException e){
            return false;
        }
    }

    @Override
    public void activateObject(PooledObject pooledObject) throws Exception {
        // TODO no sure how to  activateObject
    }

    @Override
    public void passivateObject(PooledObject pooledObject) throws Exception {
        // TODO no sure how to  passivateObject
    }


}
```

**Comment by atboo** [comment]
The following code can reproduce the deadlock issue

```java
    public static void testReadLock() {

        final String uuid=ID.genUuid(10);
        MyOrientJdbcConnection conn=null;
        Statement stat=null;
        try {
            conn = Pool.getPool().getConnection();
            stat=conn.createStatement();

            stat.execute("create vertex test_user set name='"+uuid+"'");

        } catch (Exception e) {
            e.printStackTrace();
        }finally {
            if(stat!=null) {
                try {
                    stat.close();
                }catch (Exception ee){;}
            }
            if(conn!=null) {
                try {
                    conn.close();
                }catch (Exception ee){;}
            }
        }


        Thread readThread = new Thread() {
            @Override

            public void run() {
                //super.run();
                System.out.println("reader started");

                MyOrientJdbcConnection conn=null;
                Statement stat=null;
                ResultSet rs=null;
                try {
                    conn = Pool.getPool().getConnection();
                    stat=conn.createStatement();

                    rs=stat.executeQuery("select from test_user where name='"+uuid+"'");

                    sleep(60000); // wait for 1 min
                } catch (Exception e) {
                    e.printStackTrace();
                }finally {
                    if(rs!=null) {
                        try {
                            rs.close();
                        }catch (Exception ee){;}
                    }
                    if(stat!=null) {
                        try {
                            stat.close();
                        }catch (Exception ee){;}
                    }
                    if(conn!=null) {
                        try {
                            conn.close();
                        }catch (Exception ee){;}
                    }
                    System.out.println("reader closed");
                }
            }
        };

        readThread.start();

        Thread writerThread=new Thread(){
            @Override
            public void run() {

                MyOrientJdbcConnection conn=null;
                Statement stat=null;
                try {
                    sleep(2000); // wait for 2 sec
                    System.out.println("writer started");
                    conn = Pool.getPool().getConnection();
                    stat=conn.createStatement();

                    stat.execute("update test_user set name='" + uuid + "111"+"' where name='"+uuid+"'");


                } catch (Exception e) {
                    e.printStackTrace();
                }finally {
                    if(stat!=null) {
                        try {
                            stat.close();
                        }catch (Exception ee){;}
                    }
                    if(conn!=null) {
                        try {
                            conn.close();
                        }catch (Exception ee){;}
                    }

                    System.out.println("writer closed");
                }
            }
        };

        writerThread.start();

    }
```

**Comment by atboo** [comment]
i suggest to add auto release mechanism of recode deadlocked

**Comment by tglman** [comment]
Hi @atboo,
I got your code and changed for use directly the orientdb connection, and i couldn't reproduce the problem, i feel like you have some issue in the connection pool.

Can you provide a test case with an opensource connection pool?

**Comment by martingg88** [comment]
I do have this issue for version 2.0.8 event i set my timeout to 120000 ms. here is the bug i got.

} Error on fetching record during browsing. The record has been skipped
com.orientechnologies.orient.core.exception.ODatabaseException: Error on retrieving record #20:2304 (cluster: log_visit)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.executeReadRecord(ODatabaseDocumentTx.java:1612)
	at com.orientechnologies.orient.core.tx.OTransactionNoTx.loadRecord(OTransactionNoTx.java:80)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.load(ODatabaseDocumentTx.java:1445)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.load(ODatabaseDocumentTx.java:118)
	at com.orientechnologies.orient.core.iterator.OIdentifiableIterator.readCurrentRecord(OIdentifiableIterator.java:278)
	at com.orientechnologies.orient.core.iterator.ORecordIteratorClusters.hasNext(ORecordIteratorClusters.java:147)
	at com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.fetchFromTarget(OCommandExecutorSQLSelect.java:1298)
	at com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.executeSearch(OCommandExecutorSQLSelect.java:433)
	at com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.execute(OCommandExecutorSQLSelect.java:391)
	at com.orientechnologies.orient.core.sql.OCommandExecutorSQLDelegate.execute(OCommandExecutorSQLDelegate.java:64)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.executeCommand(OAbstractPaginatedStorage.java:1189)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.command(OAbstractPaginatedStorage.java:1178)
	at com.orientechnologies.orient.core.command.OCommandRequestTextAbstract.execute(OCommandRequestTextAbstract.java:63)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.command(ONetworkProtocolBinary.java:1178)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.executeRequest(ONetworkProtocolBinary.java:385)
	at com.orientechnologies.orient.server.network.protocol.binary.OBinaryNetworkProtocolAbstract.execute(OBinaryNetworkProtocolAbstract.java:217)
	at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:69)
Caused by: com.orientechnologies.common.concur.OTimeoutException: Can not lock record for 120000 ms. seems record is deadlocked by other record
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.acquireReadLock(OAbstractPaginatedStorage.java:1313)
	at com.orientechnologies.orient.core.tx.OTransactionAbstract.lockRecord(OTransactionAbstract.java:120)
	at com.orientechnologies.orient.core.id.ORecordId.lock(ORecordId.java:281)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.lockRecord(OAbstractPaginatedStorage.java:1784)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.readRecord(OAbstractPaginatedStorage.java:1430)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.readRecord(OAbstractPaginatedStorage.java:694)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.executeReadRecord(ODatabaseDocumentTx.java:1580)

**Comment by tglman** [comment]
@martingg88 
do you have a specific test case, i tried to reproduce the case with the one provided by @atboo with no success, also have a full threads dump will help, so i can understand better all the locking path.

**Comment by martingg88** [comment]
this issue may link to #4090.

**Comment by laa** [comment]
yes that seems like the same

**Comment by laa** [comment]
Fixed
