### ISSUE TITLE
sql -critical!!! NumberFormatException during insert long values

### ISSUE THREAD

**Issue by StarpTech** [orientechnologies/orientdb#4008]
Can't insert long values anymore e.g:

```sql
create vertex Root content { "Name":"test", "Created":1429829535669}
```
**A Hotfix must be released!!! and the tests**

Apparently the parser does not distinguish between INT and LONG values.

Tested on: Studio and binary protocol
OrientDB Server v2.1-rc1
Driver: Oriento 1.1.3, NodeJs

Exception:
```
Sent run-time exception to the client /10.0.2.2:52261: java.lang.NumberFormatException: For input string: "1429829535669"
java.lang.NumberFormatException: For input string: "1429829535669"
        at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
        at java.lang.Integer.parseInt(Integer.java:495)
        at java.lang.Integer.parseInt(Integer.java:527)
        at com.orientechnologies.orient.core.sql.parser.OrientSql.Integer(OrientSql.java:208)
        at com.orientechnologies.orient.core.sql.parser.OrientSql.Number(OrientSql.java:262)
        at com.orientechnologies.orient.core.sql.parser.OrientSql.BaseExpression(OrientSql.java:4165)
        at com.orientechnologies.orient.core.sql.parser.OrientSql.FirstLevelExpression(OrientSql.java:4043)
        at com.orientechnologies.orient.core.sql.parser.OrientSql.MultExpression(OrientSql.java:3972)
        at com.orientechnologies.orient.core.sql.parser.OrientSql.MathExpression(OrientSql.java:3907)
        at com.orientechnologies.orient.core.sql.parser.OrientSql.Expression(OrientSql.java:3850)
        at com.orientechnologies.orient.core.sql.parser.OrientSql.Json(OrientSql.java:7099)
        at com.orientechnologies.orient.core.sql.parser.OrientSql.InsertBody(OrientSql.java:2429)
        at com.orientechnologies.orient.core.sql.parser.OrientSql.CreateVertexStatement(OrientSql.java:2577)
        at com.orientechnologies.orient.core.sql.parser.OrientSql.Statement(OrientSql.java:331)
        at com.orientechnologies.orient.core.sql.parser.OrientSql.parse(OrientSql.java:87)
        at com.orientechnologies.orient.core.sql.OCommandExecutorSQLAbstract.preParse(OCommandExecutorSQLAbstract.java:234)
        at com.orientechnologies.orient.graph.sql.OCommandExecutorSQLCreateVertex.parse(OCommandExecutorSQLCreateVertex.java:64)
        at com.orientechnologies.orient.graph.sql.OCommandExecutorSQLCreateVertex.parse(OCommandExecutorSQLCreateVertex.java:49)
        at com.orientechnologies.orient.core.sql.OCommandExecutorSQLDelegate.parse(OCommandExecutorSQLDelegate.java:74)
        at com.orientechnologies.orient.core.sql.OCommandExecutorSQLDelegate.parse(OCommandExecutorSQLDelegate.java:40)
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.command(OAbstractPaginatedStorage.java:1161)
        at com.orientechnologies.orient.core.command.OCommandRequestTextAbstract.execute(OCommandRequestTextAbstract.java:63)
        at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.command(ONetworkProtocolBinary.java:1172)
        at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.executeRequest(ONetworkProtocolBinary.java:372)
        at com.orientechnologies.orient.server.network.protocol.binary.OBinaryNetworkProtocolAbstract.execute(OBinaryNetworkProtocolAbstract.java:221)
        at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:69)
```

**Comment by StarpTech** [comment]
Releated to https://github.com/orientechnologies/orientdb/issues/3995

**Comment by StarpTech** [comment]
LONG literal is handled like an INTEGER in
https://github.com/orientechnologies/orientdb/blob/master/core/src/main/grammar/OrientSQL.jjt#L485

replace `parseInt` with `parseLong` should fixed the error
https://github.com/orientechnologies/orientdb/blob/master/core/src/main/grammar/OrientSQL.jjt#L467

**Comment by luigidellaquila** [comment]
Hi @StarpTech 

thanks for reporting, I'm on it

**Comment by luigidellaquila** [comment]
Hi @StarpTech 

I just pushed a fix on develop branch, it will be released in 2.1 RC2

Luigi

**Comment by StarpTech** [comment]
@luigidellaquila  nice, thanks.

**Comment by StarpTech** [comment]
There are any tests for the parser ?

**Comment by luigidellaquila** [comment]
yes, there are some specific tests on the parser itself (I'm updating them
to also cover this case), anyway queries are tested in almost all our test
cases ;-)

Luigi


2015-04-24 14:24 GMT+02:00 Dustin <notifications@github.com>:
