### ISSUE TITLE
Create vertex to specified cluster in failure

### ISSUE THREAD

**Issue by atboo** [orientechnologies/orientdb#4011]
sql example:

```sql
create vertex Person cluster user set name='name'
```
the class 'person' is a abstract class,'user' is the cluster of class person.

The sql sometimes executed successfully,but sometimes was failed,the exception is following:

what's wrong ? (version 2.0.8 enterprise)

```
com.orientechnologies.orient.core.exception.OSchemaException: Document belongs to abstract class person and can not be saved
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.save(ODatabaseDocumentTx.java:2246)
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.save(ODatabaseDocumentTx.java:118)
        at com.orientechnologies.orient.core.record.impl.ODocument.save(ODocument.java:1703)
        at com.orientechnologies.orient.core.record.impl.ODocument.save(ODocument.java:1694)
        at com.tinkerpop.blueprints.impls.orient.OrientElement.save(OrientElement.java:305)
        at com.tinkerpop.blueprints.impls.orient.OrientElement.save(OrientElement.java:285)
        at com.orientechnologies.orient.graph.sql.OCommandExecutorSQLCreateVertex$1.call(OCommandExecutorSQLCreateVertex.java:126)
        at com.orientechnologies.orient.graph.sql.OCommandExecutorSQLCreateVertex$1.call(OCommandExecutorSQLCreateVertex.java:106)
        at com.orientechnologies.orient.graph.sql.OGraphCommandExecutorSQLFactory.runInTx(OGraphCommandExecutorSQLFactory.java:123)
        at com.orientechnologies.orient.graph.sql.OGraphCommandExecutorSQLFactory.runInTx(OGraphCommandExecutorSQLFactory.java:142)
        at com.orientechnologies.orient.graph.sql.OCommandExecutorSQLCreateVertex.execute(OCommandExecutorSQLCreateVertex.java:106)
        at com.orientechnologies.orient.core.sql.OCommandExecutorSQLDelegate.execute(OCommandExecutorSQLDelegate.java:64)
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.executeCommand(OAbstractPaginatedStorage.java:1189)
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.command(OAbstractPaginatedStorage.java:1178)
        at com.orientechnologies.orient.core.command.OCommandRequestTextAbstract.execute(OCommandRequestTextAbstract.java:63)
        at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.command(ONetworkProtocolBinary.java:1173)
        at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.executeRequest(ONetworkProtocolBinary.java:380)
        at com.orientechnologies.orient.server.network.protocol.binary.OBinaryNetworkProtocolAbstract.execute(OBinaryNetworkProtocolAbstract.java:217)
        at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:69)
```

**Comment by luigidellaquila** [comment]
Hi @atboo 

the problem here is that you are trying to execute an insert on an abstract class, and it's not allowed (even if you are explicitly declaring an existing cluster, that is, I guess, a cluster of a non-abstract subclass).

You have two ways to make it work:

- make Person non-abstract
- do the insert on the non-abstract subclass

Luigi
