### ISSUE TITLE
No space left on device error on client side

### ISSUE THREAD

**Issue by lvca** [orientechnologies/orientdb#4023]
OrientDB is installed on /mnt/odb1-disk1 and is working fine. When I start a Java client from /mnt/odb1-disk1, I get following error on client side. There are no log entries under orientdb logs. It feels like OrientDB client is calculating the disk size based on current drive (/mnt/odb1-disk1) and then creating a cache file on default mount. What system properties I need to set to unblock myself?

```
Apr 24, 2015 4:50:24 PM com.orientechnologies.common.log.OLogManager log
INFO: OrientDB auto-config DISKCACHE=9,648MB (heap=3,344MB os=15,040MB disk=57,069MB)
Exception in thread "main" com.orientechnologies.common.exception.OException: File flush was abnormally terminated
	at com.orientechnologies.orient.core.index.hashindex.local.cache.OWOWCache.flush(OWOWCache.java:443)
	at com.orientechnologies.orient.core.index.hashindex.local.cache.OWOWCache.flush(OWOWCache.java:449)
	at com.orientechnologies.orient.core.index.hashindex.local.cache.OReadWriteDiskCache.flushBuffer(OReadWriteDiskCache.java:539)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.makeFullCheckpoint(OAbstractPaginatedStorage.java:1349)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.synch(OAbstractPaginatedStorage.java:996)
	at com.orientechnologies.orient.core.index.OIndexManagerAbstract.save(OIndexManagerAbstract.java:115)
	at com.orientechnologies.orient.core.index.OIndexManagerShared.createIndex(OIndexManagerShared.java:178)
	at com.orientechnologies.orient.core.index.OIndexManagerProxy.createIndex(OIndexManagerProxy.java:79)
	at com.orientechnologies.orient.core.sql.OCommandExecutorSQLCreateIndex.execute(OCommandExecutorSQLCreateIndex.java:271)
	at com.orientechnologies.orient.core.sql.OCommandExecutorSQLDelegate.execute(OCommandExecutorSQLDelegate.java:64)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.executeCommand(OAbstractPaginatedStorage.java:1189)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.command(OAbstractPaginatedStorage.java:1178)
	at com.orientechnologies.orient.core.command.OCommandRequestTextAbstract.execute(OCommandRequestTextAbstract.java:63)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.command(ONetworkProtocolBinary.java:1178)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.executeRequest(ONetworkProtocolBinary.java:385)
	at com.orientechnologies.orient.server.network.protocol.binary.OBinaryNetworkProtocolAbstract.execute(OBinaryNetworkProtocolAbstract.java:220)
	at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:69)
Caused by: java.util.concurrent.ExecutionException: java.io.IOException: No space left on device
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:188)
	at com.orientechnologies.orient.core.index.hashindex.local.cache.OWOWCache.flush(OWOWCache.java:438)
	... 16 more
Caused by: java.io.IOException: No space left on device
	at sun.nio.ch.FileDispatcherImpl.pwrite0(Native Method)
	at sun.nio.ch.FileDispatcherImpl.pwrite(FileDispatcherImpl.java:66)
	at sun.nio.ch.IOUtil.writeFromNativeBuffer(IOUtil.java:89)
	at sun.nio.ch.IOUtil.write(IOUtil.java:65)
	at sun.nio.ch.FileChannelImpl.writeInternal(FileChannelImpl.java:738)
	at sun.nio.ch.FileChannelImpl.write(FileChannelImpl.java:723)
	at com.orientechnologies.orient.core.storage.fs.OFileClassic.writeInternal(OFileClassic.java:95)
	at com.orientechnologies.orient.core.storage.fs.OFileClassic.write(OFileClassic.java:214)
	at com.orientechnologies.orient.core.index.hashindex.local.cache.OWOWCache.flushPage(OWOWCache.java:937)
	at com.orientechnologies.orient.core.index.hashindex.local.cache.OWOWCache.access$2000(OWOWCache.java:64)
	at com.orientechnologies.orient.core.index.hashindex.local.cache.OWOWCache$FileFlushTask.call(OWOWCache.java:1236)
	at com.orientechnologies.orient.core.index.hashindex.local.cache.OWOWCache$FileFlushTask.call(OWOWCache.java:1204)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:178)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:292)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
```

Env:

```
Ubuntu 14
Sun JDK 7
Memory 16 GB RAM
Disk Space
Filesystem      Size  Used Avail Use% Mounted on
/dev/sda1       9.9G  2.5G  6.9G  27% /
/dev/sdb         99G   43G   51G  46% /mnt/odb1-disk1
```

**Comment by lvca** [comment]
More info... it happens when client is trying to drop property...

```
com.orientechnologies.common.exception.OException: File flush was abnormally terminated
	at com.orientechnologies.orient.core.index.hashindex.local.cache.OWOWCache.flush(OWOWCache.java:443)
	at com.orientechnologies.orient.core.index.hashindex.local.cache.OWOWCache.flush(OWOWCache.java:449)
	at com.orientechnologies.orient.core.index.hashindex.local.cache.OReadWriteDiskCache.flushBuffer(OReadWriteDiskCache.java:539)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.makeFullCheckpoint(OAbstractPaginatedStorage.java:1349)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.synch(OAbstractPaginatedStorage.java:996)
	at com.orientechnologies.orient.core.metadata.schema.OSchemaShared.saveInternal(OSchemaShared.java:1120)
	at com.orientechnologies.orient.core.metadata.schema.OSchemaShared.releaseSchemaWriteLock(OSchemaShared.java:585)
	at com.orientechnologies.orient.core.metadata.schema.OClassImpl.releaseSchemaWriteLock(OClassImpl.java:1560)
	at com.orientechnologies.orient.core.metadata.schema.OClassImpl.releaseSchemaWriteLock(OClassImpl.java:1555)
	at com.orientechnologies.orient.core.metadata.schema.OClassImpl.dropProperty(OClassImpl.java:649)
	at com.orientechnologies.orient.core.sql.OCommandExecutorSQLDropProperty.execute(OCommandExecutorSQLDropProperty.java:126)
	at com.orientechnologies.orient.core.sql.OCommandExecutorSQLDelegate.execute(OCommandExecutorSQLDelegate.java:64)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.executeCommand(OAbstractPaginatedStorage.java:1189)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.command(OAbstractPaginatedStorage.java:1178)
	at com.orientechnologies.orient.core.command.OCommandRequestTextAbstract.execute(OCommandRequestTextAbstract.java:63)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.command(ONetworkProtocolBinary.java:1178)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.executeRequest(ONetworkProtocolBinary.java:385)
	at com.orientechnologies.orient.server.network.protocol.binary.OBinaryNetworkProtocolAbstract.execute(OBinaryNetworkProtocolAbstract.java:220)
	at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:69)
Caused by: java.util.concurrent.ExecutionException: java.io.IOException: No space left on device
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:188)
	at com.orientechnologies.orient.core.index.hashindex.local.cache.OWOWCache.flush(OWOWCache.java:438)
	... 18 more
```

**Comment by laa** [comment]
Hi, I have a question. If you start client from any other location, you do not have given exception. Do not you ?

**Comment by uttamatsimility** [comment]
Earier both server and client were on same machine. Finally I moved the client to separate vm and this problem went away...

**Comment by lvca** [comment]
is this issue still relevant?

**Comment by lvca** [comment]
Closed because no answer from the user.
