### ISSUE TITLE
NPE while creating the index

### ISSUE THREAD

**Issue by lvca** [orientechnologies/orientdb#4026]
Here's the stack trace. Nothing special about this index, once again restarting odb did the magic:

```
Exception in thread "main" com.orientechnologies.orient.core.exception.OCommandExecutionException: Error on execution of command: sql.create index <CLASS>.<PROP> NOTUNIQUE_HASH_INDEX
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.executeCommand(OAbstractPaginatedStorage.java:1182)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.command(OAbstractPaginatedStorage.java:1165)
	at com.orientechnologies.orient.core.command.OCommandRequestTextAbstract.execute(OCommandRequestTextAbstract.java:63)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.command(ONetworkProtocolBinary.java:1180)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.executeRequest(ONetworkProtocolBinary.java:385)
	at com.orientechnologies.orient.server.network.protocol.binary.OBinaryNetworkProtocolAbstract.execute(OBinaryNetworkProtocolAbstract.java:216)
	at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:65)
Caused by: java.lang.NullPointerException
	at com.orientechnologies.orient.core.storage.impl.local.paginated.base.ODurablePage.<init>(ODurablePage.java:84)
	at com.orientechnologies.orient.core.index.hashindex.local.ODirectoryPage.<init>(ODirectoryPage.java:44)
	at com.orientechnologies.orient.core.index.hashindex.local.ODirectoryFirstPage.<init>(ODirectoryFirstPage.java:44)
	at com.orientechnologies.orient.core.index.hashindex.local.OHashTableDirectory.loadPage(OHashTableDirectory.java:567)
	at com.orientechnologies.orient.core.index.hashindex.local.OHashTableDirectory.getNodeLocalDepth(OHashTableDirectory.java:410)
	at com.orientechnologies.orient.core.index.hashindex.local.OLocalHashTable.getBucket(OLocalHashTable.java:2089)
	at com.orientechnologies.orient.core.index.hashindex.local.OLocalHashTable.firstEntry(OLocalHashTable.java:908)
	at com.orientechnologies.orient.core.index.engine.OHashTableIndexEngine.size(OHashTableIndexEngine.java:168)
	at com.orientechnologies.orient.core.index.OIndexMultiValues.getSize(OIndexMultiValues.java:416)
	at com.orientechnologies.orient.core.index.OIndexTxAware.getSize(OIndexTxAware.java:54)
	at com.orientechnologies.orient.core.sql.OCommandExecutorSQLCreateIndex.execute(OCommandExecutorSQLCreateIndex.java:276)
	at com.orientechnologies.orient.core.sql.OCommandExecutorSQLDelegate.execute(OCommandExecutorSQLDelegate.java:64)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.executeCommand(OAbstractPaginatedStorage.java:1176)

```

**Comment by laa** [comment]
it is fixed in 2.0 RC1 during cache refracting.
