### ISSUE TITLE
RecordId cannot support negative cluster id: -51

### ISSUE THREAD

**Issue by lvca** [orientechnologies/orientdb#4027]
Something is corrupting our record ids and we start getting above mentioned error. At this point orientdb indexes get corrupted and any query based on index (for e.g. select from C where P = <some-val> and there is index on P) returned empty records. We observe following stack trace in logs. We have kept backup of corrupted db. We cannot send db to you but can apply patches or run diagnostics on it.

```
2015-04-20 00:12:41:717 FINE  [ONetworkProtocolHttpAbstract.execute] Requested: GET /listDatabases [ONetworkProtocolHttpDb]Caught exception
com.orientechnologies.orient.core.exception.ODatabaseException: RecordId cannot support negative cluster id. You've used: -51
	at com.orientechnologies.orient.core.id.ORecordId.checkClusterLimits(ORecordId.java:323)
	at com.orientechnologies.orient.core.id.ORecordId.<init>(ORecordId.java:51)
	at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinaryV0.readOptimizedLink(ORecordSerializerBinaryV0.java:462)
	at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinaryV0.readSingleValue(ORecordSerializerBinaryV0.java:360)
	at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinaryV0.deserialize(ORecordSerializerBinaryV0.java:197)
	at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinary.fromStream(ORecordSerializerBinary.java:74)
	at com.orientechnologies.orient.core.record.impl.ODocument.deserializeFields(ODocument.java:1752)
```

**Comment by tglman** [comment]
hi,

I would like to gather a bit more information:
does this error started to happen all together or the were some errors happening progressively ?
Have you done any particular operation like crash,backup/restore, batch import, moment of heavy load, or this happen in the normal application flow ?
Are there any other error in the log that started to appear together with this ?
Do you use a journaled file system ?

I'm improving the log in case of thins errors in a way that it's easier identify the record is causing it, I'll provide also a patched version of orient for do some diagnostic.

In the meanwhile if you can provide some answer to the previous question will be really helpful.

**Comment by tglman** [comment]
Hi,
I improved the logging in a way that we can identify the exact record is creating the problem (here is the change: https://github.com/orientechnologies/orientdb/commit/70acb381ae9ce20559922e190319794df2831e64) it will be released with 2.0.9.

in the meanwhile I'm writing an easy command for let you extract the information we need from the db.

**Comment by johnmelba** [comment]
That would be awesome!

**Comment by tglman** [comment]
Hi @johnmelba 

I've got a dist with a command to get the detail of the failing records, where can i send that ?

thank you

**Comment by tglman** [comment]
no reply since a while, closing
