### ISSUE TITLE
NullPointerException while trying to aquire db from pool

### ISSUE THREAD

**Issue by dblaber** [orientechnologies/orientdb#4044]
Not sure how to replicate this, but I have a long running proccess that is loading millions of records in the db, and at a certain point I receive a series of exceptions when trying to get a connection from the pool. Version is 2.0.8, this application has many thread concurrently executing getting connections and saving documents. 
com.orientechnologies.orient.core.exception.ODatabaseException: Cannot open database
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.open(ODatabaseDocumentTx.java:277)
        at com.orientechnologies.orient.core.db.OPartitionedDatabasePool.acquire(OPartitionedDatabasePool.java:285)
        at com.vendor.common.orientdbmapimpl.OrientDBAgentManager$MapBatchLoader.run(OrientDBAgentManager.java:110)
        at com.vendor.common.orientdbmapimpl.ParallelExecutor$Runner.run(ParallelExecutor.java:80)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
        at com.orientechnologies.orient.client.remote.OStorageRemote.getServerURL(OStorageRemote.java:159)
        at com.orientechnologies.orient.client.remote.OStorageRemoteThread.popSession(OStorageRemoteThread.java:716)
        at com.orientechnologies.orient.client.remote.OStorageRemoteThread.open(OStorageRemoteThread.java:89)
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.open(ODatabaseDocumentTx.java:244)
        ... 4 more

I then receive this exception after, which might be caused by the above (this is when saving record):
com.orientechnologies.orient.core.exception.ODatabaseException: Error on saving record in cluster #-1
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.executeSaveRecord(ODatabaseDocumentTx.java:1766)
        at com.orientechnologies.orient.core.tx.OTransactionNoTx.saveRecord(OTransactionNoTx.java:94)
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.save(ODatabaseDocumentTx.java:2285)
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.save(ODatabaseDocumentTx.java:2119)
        at com.vendor.common.orientdbmapimpl.OrientDBAgentManager$MapBatchLoader.run(OrientDBAgentManager.java:140)
        at com.vzw.datagrid.common.orientdbmapimpl.ParallelExecutor$Runner.run(ParallelExecutor.java:80)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.callbackHooks(ODatabaseDocumentTx.java:942)
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.callbackHookFinalize(ODatabaseDocumentTx.java:2787)
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.executeSaveRecord(ODatabaseDocumentTx.java:1754)
        ... 6 more

**Comment by atboo** [comment]
i use apache common pool to instead of its original pool, and it works fine.

**Comment by lvca** [comment]
What OrientDB release?

**Comment by dblaber** [comment]
This was in version Orientdb version 2.0.8

**Comment by laa** [comment]
It is already fixed in GA we merely do not have thread local there any more.
