### ISSUE TITLE
Jdbc driver does not support batch sql

### ISSUE THREAD

**Issue by atboo** [orientechnologies/orientdb#4047]
Following the example code:

```java
conn = Pool.getPool().getConnection();
conn.setAutoCommit(false);
stat = conn.createStatement();

stat.executeQuery("begin;let ret=select 1;commit;return $ret;");

//as same as the following
//                        stat.execute("begin");
//                        stat.execute("let ret=select 1");
//                        stat.execute("commit");
//                        stat.execute("return $ret");

```

```
com.orientechnologies.orient.core.command.OCommandExecutorNotFoundException: Cannot find a command executor for the command request: sql.begin;let ret=select 1;commit;return $ret;
	at com.orientechnologies.orient.core.sql.OCommandExecutorSQLDelegate.parse(OCommandExecutorSQLDelegate.java:52)
	at com.orientechnologies.orient.core.sql.OCommandExecutorSQLDelegate.parse(OCommandExecutorSQLDelegate.java:37)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.command(OAbstractPaginatedStorage.java:1176)
	at com.orientechnologies.orient.core.command.OCommandRequestTextAbstract.execute(OCommandRequestTextAbstract.java:63)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.command(ONetworkProtocolBinary.java:1173)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.executeRequest(ONetworkProtocolBinary.java:380)
	at com.orientechnologies.orient.server.network.protocol.binary.OBinaryNetworkProtocolAbstract.execute(OBinaryNetworkProtocolAbstract.java:217)
	at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:69)
```

**Comment by atboo** [comment]
how about the sql command keyword 'TRANSACTIONAL' what found in source code and not found in public documents

**Comment by lvca** [comment]
This is already supported through the JDBC batch API: http://www.tutorialspoint.com/jdbc/jdbc-batch-processing.htm
