### ISSUE TITLE
serialization error after massive insert

### ISSUE THREAD

**Issue by luigidellaquila** [orientechnologies/orientdb#4073]
after a massive insert operation, the database has thrown this exception:

```
AVVERTENZA: {db=test} Page in file phrase.pcl with index 493528 was placed in wrong free list, this error will be fixed automatically.
mag 04, 2015 10:12:06 AM com.orientechnologies.common.log.OLogManager log
AVVERTENZA: {db=test} Error deserializing record with id #11:548414 send this data for debugging: AAxQaHJhc2UpAAAAJysAAAAxHGluX1RyYW5zbGF0aW9uAAAAOBYA8ebc31RyYW5zbGF0aW9uAAAAZhYA8ebc39G74on/AQw=
Exception in thread "main" java.lang.StringIndexOutOfBoundsException: String index out of range: -49
        at java.lang.String.checkBounds(String.java:369)
        at java.lang.String.<init>(String.java:413)
        at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinaryV0.stringFromBytes(ORecordSerializerBinaryV0.java:796)
        at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinaryV0.readString(ORecordSerializerBinaryV0.java:753)
        at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinaryV0.readSingleValue(ORecordSerializerBinaryV0.java:302)
        at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinaryV0.deserializePartial(ORecordSerializerBinaryV0.java:141)
        at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinary.fromStream(ORecordSerializerBinary.java:72)
        at com.orientechnologies.orient.core.record.impl.ODocument.deserializeFields(ODocument.java:1730)
        at com.orientechnologies.orient.core.record.impl.ODocument.checkForFields(ODocument.java:2293)
        at com.orientechnologies.orient.core.record.impl.ODocument.fieldType(ODocument.java:1380)
        at com.tinkerpop.blueprints.impls.orient.OrientVertex.createLink(OrientVertex.java:124)
        at com.tinkerpop.blueprints.impls.orient.OrientVertex.addEdge(OrientVertex.java:941)
        at com.tinkerpop.blueprints.impls.orient.OrientVertex.addEdge(OrientVertex.java:853)
```

**Comment by tglman** [comment]
this was long time ago, probably and issue with low level record persistence and pages management, probably already fixed, forwarding to @laa  for double checking

**Comment by laa** [comment]
Yes, it was fixed long time ago. @luigidellaquila you was able to reproduce it ?

**Comment by laa** [comment]
oh that is year , ago. Yes we already fixed given issue.
