### ISSUE TITLE
Disitributed mode: Cannot drop and then recreate class of same name

### ISSUE THREAD

**Issue by dblaber** [orientechnologies/orientdb#4095]
While running orientdb in distributed mode, for development/testing purposes, and even operation purposes, it is necessary to drop and recreate class. This does not appear to be working.

Lets say I have a master master with replication, 2 nodes, if I drop the class, I notice the clusters still exist for that class, for example testclass_<node>. When recreating a class, I notice there is only one cluster listed for that class on the UI, when before there were 3 cluster. When I then try to insert to the recreated class, I see this:
Exception in thread "main" com.orientechnologies.common.exception.OException: Cannot find best cluster for class 'testclass' on server 'DEV1'. ClusterStrategy=local
	at com.orientechnologies.orient.server.distributed.OLocalClusterStrategy.readConfiguration(OLocalClusterStrategy.java:90)
	at com.orientechnologies.orient.server.distributed.OLocalClusterStrategy.getCluster(OLocalClusterStrategy.java:60)
	at com.orientechnologies.orient.core.metadata.schema.OImmutableClass.getClusterForNewInstance(OImmutableClass.java:273)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.save(ODatabaseDocumentTx.java:2248)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.save(ODatabaseDocumentTx.java:2119)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.save(ODatabaseDocumentTx.java:118)
	at com.orientechnologies.orient.server.network.protocol.binary.OBinaryNetworkProtocolAbstract.createRecord(OBinaryNetworkProtocolAbstract.java:359)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.createRecord(ONetworkProtocolBinary.java:1377)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.executeRequest(ONetworkProtocolBinary.java:345)
	at com.orientechnologies.orient.server.network.protocol.binary.OBinaryNetworkProtocolAbstract.execute(OBinaryNetworkProtocolAbstract.java:217)
	at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:69)

This is orientdb version 2.0.8,
-bash-3.2$ cat default-distributed-db-config.json
{
    "autoDeploy": true,
    "hotAlignment": false,
    "executionMode": "synchronous",
    "readQuorum": 1,
    "writeQuorum": 2,
    "failureAvailableNodesLessQuorum": false,
    "readYourWrites": true,
    "clusters": {
        "internal": {
        },
        "index": {
        },
        "*": {
            "servers" : [ "<NEW_NODE>" ]
        }
    }
}

If there is any other information needed, I will provide, this can be replicated right in the studio UI.

**Comment by dblaber** [comment]
I am seeing this same behavior also when attempting to create a class that has been defined in the distributed config json, it only creates a local cluster, so I have to create each cluster manually

**Comment by lvca** [comment]
Please could you retry with 2.1-rc6?

**Comment by WipeKor** [comment]
Still incorrect with 2.1-rc6

**Comment by lvca** [comment]
Reproduced with 2.1.0, working to a fix.

**Comment by lvca** [comment]
Sorry, I was wrong: with 2.1.1-SNAPSHOT this test passes:
``java 
    for (int s = 0; s < SERVERS; ++s) {
      OrientGraphFactory factory = new OrientGraphFactory("plocal:target/server" + s + "/databases/" + getDatabaseName());
      OrientGraphNoTx g = factory.getNoTx();

      try {
        for (int i = 0; i < SERVERS; ++i) {
          g.command(new OCommandSQL("create class TestNewClassIfCanBeDropAndRecreated extends V")).execute();
          g.command(new OCommandSQL("drop class TestNewClassIfCanBeDropAndRecreated")).execute();
          g.command(new OCommandSQL("create class TestNewClassIfCanBeDropAndRecreated extends V")).execute();
          g.command(new OCommandSQL("drop class TestNewClassIfCanBeDropAndRecreated")).execute();
        }
      } finally {
        g.shutdown();
      }
    }
```

**Comment by lvca** [comment]
Marking this as invalid, but please comment/reopen if you can find a way to reproduce it.
