### ISSUE TITLE
Creating lucene indexes yeilds java.lang.AbstractMethodError

### ISSUE THREAD

**Issue by AaronSchulz** [orientechnologies/orientdb#4097]
The DB is empty at this point.

```
orientdb {db=WikiData}> create index HPwCVLocGeoIdx on HPwCV (lat, lon) spatial engine LUCENE


Creating index...
Error: com.orientechnologies.orient.enterprise.channel.binary.OResponseProcessingException: Exception during response pr
ocessing.

Error: java.lang.AbstractMethodError
```

This was compiled from 'develop' yesterday.

**Comment by maggiolo00** [comment]
hi @AaronSchulz 
which version of OrientDB

**Comment by AaronSchulz** [comment]
It's 'develop', orientdb-community-2.1-rc2, as of 9ac59f1923dfe290ffb8caed469436851fde3842

**Comment by AaronSchulz** [comment]
```
[ONetworkProtocolBinary]Sent run-time exception to the client
 /127.0.0.1:54237: java.lang.AbstractMethodError
java.lang.AbstractMethodError
        at com.orientechnologies.orient.core.index.OIndexDefinitionFactory.createMultipleFieldIndexDefinition(OIndexDefinitionFactory.java:90)
        at com.orientechnologies.orient.core.index.OIndexDefinitionFactory.createIndexDefinition(OIndexDefinitionFactory.java:65)
        at com.orientechnologies.orient.core.metadata.schema.OClassImpl.createIndex(OClassImpl.java:1656)
        at com.orientechnologies.orient.core.sql.OCommandExecutorSQLCreateIndex.execute(OCommandExecutorSQLCreateIndex.java:259)
        at com.orientechnologies.orient.core.sql.OCommandExecutorSQLDelegate.execute(OCommandExecutorSQLDelegate.java:83)
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.executeCommand(OAbstractPaginatedStorage.java:1202)
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.command(OAbstractPaginatedStorage.java:1183)
        at com.orientechnologies.orient.core.command.OCommandRequestTextAbstract.execute(OCommandRequestTextAbstract.java:63)
        at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.command(ONetworkProtocolBinary.java:1172)
        at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.executeRequest(ONetworkProtocolBinary.java:372)
        at com.orientechnologies.orient.server.network.protocol.binary.OBinaryNetworkProtocolAbstract.execute(OBinaryNetworkProtocolAbstract.java:221)

        at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:71)
```

**Comment by maggiolo00** [comment]
@AaronSchulz 
i've downloaded the 2.1-rc2 from the website
run
```
create class HPwCV
create property HPwCV.lat DECIMAL
create property HPwCV.lon DECIMAL
create index HPwCVLocGeoIdx on HPwCV (lat, lon) spatial engine LUCENE
```
Without exception.
Did you build also the lucene plugin?

**Comment by AaronSchulz** [comment]
I built it and moved the 4Mb -dist jar file to /libs. Does that method no longer work? I noticed that the plugin is not mentioned when the servers starts up.

**Comment by martingg88** [comment]
any idea how to solve this issue?

**Comment by machak** [comment]
run into this myself: lucene plugin needs an update, I did a quick and dirty fix here:
https://github.com/machak/orientdb-lucene 

However a lot of tests are failing.

**Comment by machak** [comment]
by " lucene plugin needs an update,"  I mean: there is an api change, which is not implemented in lucene plugin...

**Comment by stuk88** [comment]
still cant use lucene index... any updates on that?

**Comment by maggiolo00** [comment]
@stuk88  which version?

**Comment by lvca** [comment]
The issue has been closed because no response has been received after a while. In case the issue is still valid, please reopen it or write a comment that explains why it's still valid and a way to reproduce it. Thank you.
