### ISSUE TITLE
Can't ORDER BY embedded map elements

### ISSUE THREAD

**Issue by mrprescott** [orientechnologies/orientdb#4100]
Before our upgrade to Orient 2.1-rc2, we were happily sorting by keys inside embedded maps - e.g. "select from asset ORDER BY attributes.custom.download_count". This sort of reference no longer parses with the new SQL parser.

**Comment by mrprescott** [comment]
> select attributes.nuget.download_count from asset

----+------+----------
#   |@CLASS|attributes
----+------+----------
0   |null  |416
1   |null  |1590
2   |null  |690
3   |null  |883
4   |null  |603
5   |null  |1367
6   |null  |78038
7   |null  |8241
8   |null  |6844
9   |null  |204
10  |null  |415
11  |null  |75
12  |null  |653
13  |null  |131
14  |null  |921
15  |null  |1348
16  |null  |276
17  |null  |2899
18  |null  |564
19  |null  |2625
----+------+----------
LIMIT EXCEEDED: resultset contains more items not displayed (limit=20)

20 item(s) found. Query executed in 0.013 sec(s).

>select attributes.nuget.download_count from asset order by attributes.nuget.download_count
com.orientechnologies.orient.core.sql.parser.ParseException: Encountered " "." ". "" at line 1, column 70.
Was expecting one of:
    <EOF>
    <LIMIT> ...
    <SKIP2> ...
    <OFFSET> ...
    <TIMEOUT> ...
    <ASC> ...
    <DESC> ...
    <FETCHPLAN> ...
    <LOCK> ...
    <NOCACHE> ...
    <PARALLEL> ...
    <UNWIND> ...
    ";" ...
    "," ...
    <DESC> ...
    <ASC> ...
    "," ...
    <UNWIND> ...
    <SKIP2> ...
    <OFFSET> ...
    <LIMIT> ...
    <FETCHPLAN> ...
    <TIMEOUT> ...
    <LOCK> ...
    <PARALLEL> ...
    <NOCACHE> ...

        at com.orientechnologies.orient.core.sql.parser.OrientSql.generateParseException(OrientSql.java:11861)
        at com.orientechnologies.orient.core.sql.parser.OrientSql.jj_consume_token(OrientSql.java:11734)
        at com.orientechnologies.orient.core.sql.parser.OrientSql.parse(OrientSql.java:88)
        at com.orientechnologies.orient.core.sql.OCommandExecutorSQLAbstract.preParse(OCommandExecutorSQLAbstract.java:234)
        at com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.parse(OCommandExecutorSQLSelect.java:201)
        at com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.parse(OCommandExecutorSQLSelect.java:82)
        at com.orientechnologies.orient.core.sql.OCommandExecutorSQLDelegate.parse(OCommandExecutorSQLDelegate.java:74)
        at com.orientechnologies.orient.core.sql.OCommandExecutorSQLDelegate.parse(OCommandExecutorSQLDelegate.java:40)
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.command(OAbstractPaginatedStorage.java:1181)
        at com.orientechnologies.orient.core.sql.query.OSQLQuery.run(OSQLQuery.java:72)
        at com.orientechnologies.orient.core.sql.query.OSQLSynchQuery.run(OSQLSynchQuery.java:85)
        at com.orientechnologies.orient.core.query.OQueryAbstract.execute(OQueryAbstract.java:33)
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.query(ODatabaseDocumentTx.java:633)
        at com.orientechnologies.orient.console.OConsoleDatabaseApp.select(OConsoleDatabaseApp.java:746)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at com.orientechnologies.common.console.OConsoleApplication.execute(OConsoleApplication.java:381)
        at org.sonatype.nexus.internal.orient.OrientCommands.execute(OrientCommands.java:143)
        at org.sonatype.nexus.internal.orient.OrientCommands$1.execute(OrientCommands.java:106)
        at sun.reflect.GeneratedMethodAccessor40.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.apache.aries.proxy.impl.ProxyHandler$1.invoke(ProxyHandler.java:54)
        at org.apache.aries.proxy.impl.ProxyHandler.invoke(ProxyHandler.java:119)
        at org.sonatype.nexus.commands.$CommandSupport263508723.execute(Unknown Source)
        at org.apache.felix.gogo.runtime.CommandProxy.execute(CommandProxy.java:78)
        at org.apache.felix.gogo.runtime.Closure.executeCmd(Closure.java:477)
        at org.apache.felix.gogo.runtime.Closure.executeStatement(Closure.java:403)
        at org.apache.felix.gogo.runtime.Pipe.run(Pipe.java:108)
        at org.apache.felix.gogo.runtime.Closure.execute(Closure.java:183)
        at org.apache.felix.gogo.runtime.Closure.execute(Closure.java:120)
        at org.apache.felix.gogo.runtime.CommandSessionImpl.execute(CommandSessionImpl.java:92)
        at org.apache.karaf.shell.console.impl.jline.ConsoleImpl.run(ConsoleImpl.java:208)
        at org.apache.karaf.shell.console.impl.jline.LocalConsoleManager$2$1$1.run(LocalConsoleManager.java:109)
        at java.security.AccessController.doPrivileged(Native Method)
        at org.apache.karaf.jaas.modules.JaasHelper.doAs(JaasHelper.java:57)
        at org.apache.karaf.shell.console.impl.jline.LocalConsoleManager$2$1.run(LocalConsoleManager.java:102)

**Comment by lvca** [comment]
@luigidellaquila is this something slipped out to the new parser?

**Comment by luigidellaquila** [comment]
checking right now...

**Comment by luigidellaquila** [comment]
confirmed, it's a problem in the new parser, fixing it right now. ETA 1h

**Comment by luigidellaquila** [comment]
fixed in develop branch
