### ISSUE TITLE
Missing OSGi imports when using hazelcast

### ISSUE THREAD

**Issue by g17** [orientechnologies/orientdb#4101]
## Context

I am running OrientDB in an OSGi environment. When I try to enable hazelcast it fails starting up with a `ClassNotFoundException`:

```
java.lang.ClassNotFoundException: com.orientechnologies.orient.server.hazelcast.OHazelcastPlugin not found by com.orientechnologies.orientdb-server [10]
    at org.apache.felix.framework.BundleWiringImpl.findClassOrResourceByDelegation(BundleWiringImpl.java:1556)
    at org.apache.felix.framework.BundleWiringImpl.access$400(BundleWiringImpl.java:77)
    at org.apache.felix.framework.BundleWiringImpl$BundleClassLoader.loadClass(BundleWiringImpl.java:1993)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    at java.lang.Class.forName0(Native Method)
    at java.lang.Class.forName(Class.java:260)
    at com.orientechnologies.orient.server.OServer.registerPlugins(OServer.java:863)
    at com.orientechnologies.orient.server.OServer.activate(OServer.java:265)
```
## Problem

The problem is that the `orientdb-server` bundle uses `Class.forName()` to load a class. That is usually a bad practice in an OSGi environment. The corresponding package of the `orientdb-distributed` bundle is not listed in the package imports of the `orientdb-server`. So the `OHazelcastPlugin` will never be found on the classpath.
## Solution

A solution without refactoring the `Class.forName()` issue would be to add the `com.orientechnologies.orient.server.hazelcast` package of the `orientdb-distributed` bundle as optional package import to the `orientdb-server` bundle.

**Comment by lvca** [comment]
Done long time ago
