### ISSUE TITLE
FileNotFoundException while initializing distributed node

### ISSUE THREAD

**Issue by wildroco** [orientechnologies/orientdb#4102]
I'm trying to run two nodes in distributed mode.

Below is status of my first node:
 - OrientDB community ver. 2.0.8
 - has one database
 - Lucene spatial index is set
 - network join configuration of hazelcast.xml is set for manual IP

After first node run successfully, I start second node. Second node has same configuration except he has no database initially (empty database folder)

It seems OK for a while. Second node found correct cluster and first node, and start deploying database from first node to second node. After that, deployment failed with java.io.FileNotFoundException while uncompressing lucene index file. 

please help.

exception log is below. (strange characters are Korean. It means 'Can not find the path specified')
--------------------------------------------------------------------------------------------------------
2015-05-07 18:53:59:608 INFO
- Uncompressing file luceneIndexes/SpatialTag.lat_lon/write.lock... [OHazelcastPlugin][node1430980480088] error on copying database 'chocollit' on local server
java.io.FileNotFoundException: C:\Development\WePlace\Chocollit\orientdb-community-2.0.8\databases\chocollit\luceneIndexes\SpatialTag.lat_lon\write.lock (지정된 경로를 찾을 수 없습니다)
        at java.io.FileOutputStream.open(Native Method)
        at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
        at java.io.FileOutputStream.<init>(FileOutputStream.java:162)
        at com.orientechnologies.orient.core.compression.impl.OZIPCompressionUtil.extractFile(OZIPCompressionUtil.java:92)
        at com.orientechnologies.orient.core.compression.impl.OZIPCompressionUtil.uncompressDirectory(OZIPCompressionUtil.java:80)
        at com.orientechnologies.orient.core.storage.impl.local.paginated.OLocalPaginatedStorage.restore(OLocalPaginatedStorage.java:171)
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.restore(ODatabaseDocumentTx.java:2534)
        at com.orientechnologies.orient.server.hazelcast.OHazelcastPlugin.installDatabaseOnLocalNode(OHazelcastPlugin.java:1275)
        at com.orientechnologies.orient.server.hazelcast.OHazelcastPlugin.installDatabase(OHazelcastPlugin.java:956)
        at com.orientechnologies.orient.server.hazelcast.OHazelcastPlugin.installNewDatabases(OHazelcastPlugin.java:1245)
        at com.orientechnologies.orient.server.hazelcast.OHazelcastPlugin.startup(OHazelcastPlugin.java:200)
        at com.orientechnologies.orient.server.OServer.registerPlugins(OServer.java:871)
        at com.orientechnologies.orient.server.OServer.activate(OServer.java:265)
        at com.orientechnologies.orient.server.OServerMain.main(OServerMain.java:41)
ain(OServerMain.java:41)

**Comment by lvca** [comment]
Does the OrientDB process have the permission to write in database folder?

**Comment by wildroco** [comment]
Yes. Other files in database are processed normally.

**Comment by lvca** [comment]
Fixed in 2.1.6

**Comment by nagarajasr** [comment]
@lvca is there a commit id for the fix?
