### ISSUE TITLE
Problem to start the Workbench

### ISSUE THREAD

**Issue by dehbmarques** [orientechnologies/orientdb#4117]
Hi,

I just downloaded the enterprise version and when I try to start the Workbench (```start-workbench.bat```) I get the following error:
```
           .
          .`        `
          ,      `:.
         `,`    ,:`
         .,.   :,,
         .,,  ,,,
    .    .,.:::::  ````                                 :::::::::     :::::::::
    ,`   .::,,,,::.,,,,,,`;;                      .:    ::::::::::    :::    :::
    `,.  ::,,,,,,,:.,,.`  `                       .:    :::      :::  :::     :::
     ,,:,:,,,,,,,,::.   `        `         ``     .:    :::      :::  :::     :::
      ,,:.,,,,,,,,,: `::, ,,   ::,::`   : :,::`  ::::   :::      :::  :::    :::
       ,:,,,,,,,,,,::,:   ,,  :.    :   ::    :   .:    :::      :::  :::::::
        :,,,,,,,,,,:,::   ,,  :      :  :     :   .:    :::      :::  :::::::::
  `     :,,,,,,,,,,:,::,  ,, .::::::::  :     :   .:    :::      :::  :::     :::
  `,...,,:,,,,,,,,,: .:,. ,, ,,         :     :   .:    :::      :::  :::     :::
    .,,,,::,,,,,,,:  `: , ,,  :     `   :     :   .:    :::      :::  :::     :::
      ...,::,,,,::.. `:  .,,  :,    :   :     :   .:    :::::::::::   :::     :::
           ,::::,,,. `:   ,,   :::::    :     :   .:    :::::::::     ::::::::::
           ,,:` `,,.
          ,,,    .,`
         ,,.     `,                                            WORKBENCH
       ``        `.                                       ENTERPRISE  EDITION
                 ``                                    www.orientechnologies.com
                 `

2015-05-08 12:04:12:324 INFO  OrientDB auto-config DISKCACHE=4.240MB (heap=1.797MB os=8.086MB disk=259.417MB) [orientechnologies]
2015-05-08 12:04:12:340 INFO  Loading configuration from: C:/orientdb-enterprise-2.0.8/config/workbench-config.xml... [OServerConfigurationLoaderXml]
2015-05-08 12:04:12:590 INFO  OrientDB Server v2.0.8 (build @BUILD@) is starting up... [OServer]
2015-05-08 12:04:12:621 INFO  Databases directory: C:\orientdb-enterprise-2.0.8\databases [OServer]
2015-05-08 12:04:12:652 INFO  Listening binary connections on 127.0.0.1:2424 (protocol v.28, socket=default) [OServerNetworkListener]
2015-05-08 12:04:12:652 INFO  Installing dynamic plugin 'agent-2.0.8.zip'... [OServerPluginManager]

********************************************************************
*                 ORIENTDB  -  ENTERPRISE EDITION                  *
*                                                                  *
*            Copyrights (c) 2015 Orient Technologies LTD           *
********************************************************************
* Version...: 2.0.8                                                *
********************************************************************

2015-05-08 12:04:12:762 INFO  Profiler is recording metrics with configuration: 60,24 [OEnterpriseProfiler]Error on installing dynamic plugin 'enterprise-agent'
java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at com.orientechnologies.orient.server.plugin.OServerPluginManager.startPluginClass(OServerPluginManager.java:264)
        at com.orientechnologies.orient.server.plugin.OServerPluginManager.installDynamicPlugin(OServerPluginManager.java:343)
        at com.orientechnologies.orient.server.plugin.OServerPluginManager.updatePlugin(OServerPluginManager.java:194)
        at com.orientechnologies.orient.server.plugin.OServerPluginManager.updatePlugins(OServerPluginManager.java:283)
        at com.orientechnologies.orient.server.plugin.OServerPluginManager.startup(OServerPluginManager.java:85)
        at com.orientechnologies.orient.server.OServer.registerPlugins(OServer.java:831)
        at com.orientechnologies.orient.server.OServer.activate(OServer.java:265)
        at com.orientechnologies.orient.server.OServerMain.main(OServerMain.java:41)
Caused by: com.orientechnologies.orient.core.exception.OConfigurationException: HTTP listener not found
        at com.orientechnologies.agent.OEnterpriseAgent.installCommands(OEnterpriseAgent.java:132)
        at com.orientechnologies.agent.OEnterpriseAgent.startup(OEnterpriseAgent.java:77)
        ... 12 more

2015-05-08 12:04:12:762 INFO  Installing dynamic plugin 'orientdb-lucene-2.0.8-dist.jar'... [OServerPluginManager]
2015-05-08 12:04:12:808 INFO  Lucene index plugin installed and active. Lucene version: LUCENE_47 [OLuceneIndexPlugin]Error on installing dynamic plugin 'lucene-index'
com.orientechnologies.orient.core.exception.OConfigurationException: HTTP listener not registered while installing Static Content command
        at com.orientechnologies.orient.server.plugin.OServerPluginManager.registerStaticDirectory(OServerPluginManager.java:207)
        at com.orientechnologies.orient.server.plugin.OServerPluginManager.installDynamicPlugin(OServerPluginManager.java:357)
        at com.orientechnologies.orient.server.plugin.OServerPluginManager.updatePlugin(OServerPluginManager.java:194)
        at com.orientechnologies.orient.server.plugin.OServerPluginManager.updatePlugins(OServerPluginManager.java:283)
        at com.orientechnologies.orient.server.plugin.OServerPluginManager.startup(OServerPluginManager.java:85)
        at com.orientechnologies.orient.server.OServer.registerPlugins(OServer.java:831)
        at com.orientechnologies.orient.server.OServer.activate(OServer.java:265)
        at com.orientechnologies.orient.server.OServerMain.main(OServerMain.java:41)

2015-05-08 12:04:12:808 INFO  Installing dynamic plugin 'studio-2.0.zip'... [OServerPluginManager]Error on installing dynamic plugin 'studio'
com.orientechnologies.orient.core.exception.OConfigurationException: HTTP listener not registered while installing Static Content command
        at com.orientechnologies.orient.server.plugin.OServerPluginManager.registerStaticDirectory(OServerPluginManager.java:207)
        at com.orientechnologies.orient.server.plugin.OServerPluginManager.installDynamicPlugin(OServerPluginManager.java:357)
        at com.orientechnologies.orient.server.plugin.OServerPluginManager.updatePlugin(OServerPluginManager.java:194)
        at com.orientechnologies.orient.server.plugin.OServerPluginManager.updatePlugins(OServerPluginManager.java:283)
        at com.orientechnologies.orient.server.plugin.OServerPluginManager.startup(OServerPluginManager.java:85)
        at com.orientechnologies.orient.server.OServer.registerPlugins(OServer.java:831)
        at com.orientechnologies.orient.server.OServer.activate(OServer.java:265)
        at com.orientechnologies.orient.server.OServerMain.main(OServerMain.java:41)

2015-05-08 12:04:12:824 INFO  OrientDB Server v2.0.8 is active. [OServer]
```

And then every second this other one:

```
2015-05-08 12:05:40:998 INFO  Installing dynamic plugin 'agent-2.0.8.zip'... [OServerPluginManager]

********************************************************************
*                 ORIENTDB  -  ENTERPRISE EDITION                  *
*                                                                  *
*            Copyrights (c) 2015 Orient Technologies LTD           *
********************************************************************
* Version...: 2.0.8                                                *
********************************************************************

2015-05-08 12:05:41:014 INFO  Profiler is recording metrics with configuration: 60,24 [OEnterpriseProfiler]Error on installing dynamic plugin 'enterprise-agent'
java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at com.orientechnologies.orient.server.plugin.OServerPluginManager.startPluginClass(OServerPluginManager.java:264)
        at com.orientechnologies.orient.server.plugin.OServerPluginManager.installDynamicPlugin(OServerPluginManager.java:343)
        at com.orientechnologies.orient.server.plugin.OServerPluginManager.updatePlugin(OServerPluginManager.java:194)
        at com.orientechnologies.orient.server.plugin.OServerPluginManager.updatePlugins(OServerPluginManager.java:283)
        at com.orientechnologies.orient.server.plugin.OServerPluginManager.access$000(OServerPluginManager.java:59)
        at com.orientechnologies.orient.server.plugin.OServerPluginManager$1.run(OServerPluginManager.java:92)
        at java.util.TimerThread.mainLoop(Timer.java:555)
        at java.util.TimerThread.run(Timer.java:505)
Caused by: com.orientechnologies.orient.core.exception.OConfigurationException: HTTP listener not found
        at com.orientechnologies.agent.OEnterpriseAgent.installCommands(OEnterpriseAgent.java:132)
        at com.orientechnologies.agent.OEnterpriseAgent.startup(OEnterpriseAgent.java:77)
        ... 12 more
```

I running on windows 8.1 with orientdb-enterprise-2.0.8 and orientdb-workbench-2.0.3

Am i doing something wrong?

**Comment by cwaldron** [comment]
I'm getting similar behavior with orientdb-enterprise-2.1-rc1 and orientdb-workbench-2.0.8.  I can't find any good documentation about installing Enterprise and Workbench.  In previous version there was an Enterprise Agent that installed with the community version.  It seems that now the Enterprise Version is a complete standalone and doesn't integrate into the community version like the agent did.  Does the Workbench also standalone or does it have to be integrated into the Enterprise edition?  I'm not clear on how to install the Workbench.

**Comment by maggiolo00** [comment]
hi @dehbmarques 
did you remove the http listener from the orientdb-server-config.xml?

**Comment by dehbmarques** [comment]
Hi @maggiolo00 

No, it's there:
```
<listener protocol="http" socket="default" port-range="2480-2490" ip-address="0.0.0.0">
    <commands>
        <command implementation="com.orientechnologies.orient.server.network.protocol.http.command.get.OServerCommandGetStaticContent" pattern="GET|www GET|studio/ GET| GET|*.htm GET|*.html GET|*.xml GET|*.jpeg GET|*.jpg GET|*.png GET|*.gif GET|*.js GET|*.css GET|*.swf GET|*.ico GET|*.txt GET|*.otf GET|*.pjs GET|*.svg GET|*.json GET|*.woff GET|*.ttf GET|*.svgz" stateful="false">
            <parameters>
                <entry value="Cache-Control: no-cache, no-store, max-age=0, must-revalidate\r\nPragma: no-cache" name="http.cache:*.htm *.html"/>
                <entry value="Cache-Control: max-age=120" name="http.cache:default"/>
            </parameters>
        </command>
        <command implementation="com.orientechnologies.orient.graph.server.command.OServerCommandGetGephi" pattern="GET|gephi/*" stateful="false"/>
    </commands>
    <parameters>
        <parameter value="utf-8" name="network.http.charset"/>
    </parameters>
</listener>
```

**Comment by balamaci** [comment]
Hi, seems to be working in 2.0.9

**Comment by dehbmarques** [comment]
Hi @balamaci, still not working for me.

Did you change some config? Or just executed ```start-workbench.bat```?

**Comment by balamaci** [comment]
I had the exact problem when starting the orientdb-community-2.0.8, however with 2.0.9 it worked. I don't know if it's different for enterprise.

**Comment by maggiolo00** [comment]
@dehbmarques 
did you resolve?

**Comment by dehbmarques** [comment]
@maggiolo00 no, just tried again with Orientdb Enterprise-2.1-rc4.

What I did:
- Downloaded the files ```orientdb-enterprise-2.1-rc4.tar.gz``` and ```orientdb-workbench-2.0.3.tar.gz```
- Extracted to ```C:\orientdb-enterprise-2.1-rc4``` and ```C:\orientdb-workbench-2.0.3```
- Set the ```ORIENTDB_HOME``` to ```C:\orientdb-enterprise-2.1-rc4```
- And then executed the ```start-workbench.bat```

I'm getting the same results described in the first comment.

**Comment by maggiolo00** [comment]
Repeat the step without setting the ORIENTDB_HOME
and let me know.

**Comment by dehbmarques** [comment]
Returns:

The ORIENTDB_HOME environment variable is not defined correctly
This environment variable is needed to run this program

**Comment by maggiolo00** [comment]
I think i got it. 
There is an error in the start-workbench.bat
Replace server.bat with start-workbench.bat
And retry to launch the workbench without setting ORIENTDB_HOME

**Comment by dehbmarques** [comment]
Now it didn't return the message 'The ORIENTDB_HOME environment variable...', but I'm still getting the first error.

**Comment by maggiolo00** [comment]
That means that the workbench is trying to load the server plugins (the agent).
which is wrong.

**Comment by dehbmarques** [comment]
Do I have to change something?

I just tried with start-workbench.sh changing the last line to ```exec "$JAVA"``` (found it here http://stackoverflow.com/questions/28768745/orientdb-2-0-3-enterprise-workbench) and it worked.

But in the workbench I'm getting ```java.io.IOException: Server returned HTTP response code: 505 for URL: http://localhost:2480/profiler/realtime/system.databases```

**Comment by maggiolo00** [comment]
in which log?

**Comment by dehbmarques** [comment]
In the workbench.
![image](https://cloud.githubusercontent.com/assets/3743180/8232417/f27a87aa-15a5-11e5-98c9-da25d6a40e5f.png)

**Comment by maggiolo00** [comment]
Do you have a screenshot of the dashboard?

**Comment by dehbmarques** [comment]
Here

![image](https://cloud.githubusercontent.com/assets/3743180/8232568/3b91635e-15a7-11e5-86fc-3e68eb3998a8.png)

**Comment by dehbmarques** [comment]
I just noticed something. ~2 minutes after I start the server, the status changes to offline. And then I have to restart the server to restore the connection.

**Comment by SatishAMP** [comment]
Have im also facing the same issue , Any resolution to http 505 error ?

**Comment by maggiolo00** [comment]
@dehbmarques 

is it solved with the latest stable?

**Comment by dehbmarques** [comment]
@maggiolo00

Yes, with the latest stable it worked smoothly.
Thanks.

**Comment by maggiolo00** [comment]
Great
