### ISSUE TITLE
Cannot open a connection to remote server.

### ISSUE THREAD

**Issue by chitra-solanki** [orientechnologies/orientdb#4121]
Hi, I am new to OrientDB & I am using it on windows server. I am using 2.0.8 community edition.
I was able to connect to server & everything was good until now. Console has suddenly stopped connecting to server. I am getting following error message. I have confirmed that server is listening on 2424 port.

OrientDB console v.2.0.8 (build UNKNOWN@r${buildNumber}; 2015-04-22 20:47:49+0000) www.orientechnologies.com
Type 'help' to display all the supported commands.
Installing extensions for GREMLIN language v.2.6.0
orientdb> connect remote:local root root
Connecting to remote Server instance [remote:local] with user 'root'...Cannot connect to the remote server/database 'remote:local/'
com.orientechnologies.common.io.OIOException: Cannot open a connection to remote server: local:2424/        at com.orientechnologies.orient.client.remote.OStorageRemote.getAvailableNetwork(OStorageRemote.java:1865)        at com.orientechnologies.orient.client.remote.OStorageRemote.beginRequest(OStorageRemote.java:1826)        at com.orientechnologies.orient.client.remote.OServerAdmin.connect(OServerAdmin.java:88)
        at com.orientechnologies.orient.console.OConsoleDatabaseApp.connect(OConsoleDatabaseApp.java:235)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
        at java.lang.reflect.Method.invoke(Method.java:597)
        at com.orientechnologies.common.console.OConsoleApplication.execute(OConsoleApplication.java:381)
        at com.orientechnologies.common.console.OConsoleApplication.executeCommands(OConsoleApplication.java:246)
        at com.orientechnologies.common.console.OConsoleApplication.run(OConsoleApplication.java:135)
        at com.orientechnologies.orient.graph.console.OGremlinConsole.main(OGremlinConsole.java:62)

Error: com.orientechnologies.orient.core.exception.OStorageException: Cannot connect to the remote server/database 'remote:local/'

Error: com.orientechnologies.common.io.OIOException: Cannot open a connection to remote server: local:2424/

orientdb>

**Comment by chitra-solanki** [comment]
Now I am getting warning on Console & Server windows as below before the exception mentioned in the issue.
2015-05-08 16:28:28:567 WARNING Not enough physical memory available for DISKCACHE: 2,435MB (heap=455MB). Set lower Maximum Heap (-Xmx setting on JVM) and restart OrientD
B. Now running with DISKCACHE=256MB [orientechnologies]

**Comment by lvca** [comment]
Did you use local instead of localhost?

**Comment by chitra-solanki** [comment]
It's working. Thanks Luca :)
