### ISSUE TITLE
com.orientechnologies.common.directmemory.ODirectMemoryViolationException Provided offset [127831783] is more than size of allocated ar ea

### ISSUE THREAD

**Issue by SatishAMP** [orientechnologies/orientdb#4129]
[OHazelcastPlugin]Error on updating record #15:72 (cluster: com.orientechnologies.orient.core.storage.impl.local.paginated.OPaginate
dCluster@7ccb99ec)
com.orientechnologies.common.directmemory.ODirectMemoryViolationException: Provided offset [127831783] is more than size of allocated ar
ea  [65552]
        at com.orientechnologies.common.directmemory.ODirectMemoryPointer.rangeCheck(ODirectMemoryPointer.java:215)
        at com.orientechnologies.common.directmemory.ODirectMemoryPointer.getByte(ODirectMemoryPointer.java:140)
        at com.orientechnologies.orient.core.storage.impl.local.paginated.base.ODurablePage.getByteValue(ODurablePage.java:121)
        at com.orientechnologies.orient.core.index.sbtreebonsai.local.OSBTreeBonsaiBucket.<init>(OSBTreeBonsaiBucket.java:163)
        at com.orientechnologies.orient.core.index.sbtreebonsai.local.OSBTreeBonsaiLocal.findBucket(OSBTreeBonsaiLocal.java:1209)
        at com.orientechnologies.orient.core.index.sbtreebonsai.local.OSBTreeBonsaiLocal.get(OSBTreeBonsaiLocal.java:229)
        at com.orientechnologies.orient.core.storage.impl.local.paginated.ORidBagUpdateSerializationOperation.execute(ORidBagUpdateSeria
lizationOperation.java:57)
        at com.orientechnologies.orient.core.storage.impl.local.paginated.ORecordSerializationContext.executeOperations(ORecordSerializa
tionContext.java:99)
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.doUpdateRecord(OAbstractPaginatedStorage.java:
1672)
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.updateRecord(OAbstractPaginatedStorage.java:70
8)
        at com.orientechnologies.orient.server.distributed.ODistributedStorage.updateRecord(ODistributedStorage.java:587)
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.executeSaveRecord(ODatabaseDocumentTx.java:1730)
        at com.orientechnologies.orient.core.tx.OTransactionOptimistic.addRecord(OTransactionOptimistic.java:307)
        at com.orientechnologies.orient.core.tx.OTransactionOptimistic.saveRecord(OTransactionOptimistic.java:248)
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.save(ODatabaseDocumentTx.java:2285)
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.save(ODatabaseDocumentTx.java:118)
        at com.orientechnologies.orient.core.record.impl.ODocument.save(ODocument.java:1710)
        at com.orientechnologies.orient.core.record.impl.ODocument.save(ODocument.java:1701)
        at com.orientechnologies.orient.core.record.impl.ODocument.save(ODocument.java:75)
        at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinaryV0.recursiveLinkSave(ORecordS
erializerBinaryV0.java:674)
        at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinaryV0.writeOptimizedLink(ORecord
SerializerBinaryV0.java:688)
        at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinaryV0.writeSingleValue(ORecordSe
rializerBinaryV0.java:572)
        at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinaryV0.serialize(ORecordSerialize
rBinaryV0.java:261)
        at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinary.toStream(ORecordSerializerBi
nary.java:104)
        at com.orientechnologies.orient.core.record.impl.ODocument.toStream(ODocument.java:2069)
        at com.orientechnologies.orient.core.record.impl.ODocument.toStream(ODocument.java:690)
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.commitEntry(OAbstractPaginatedStorage.java:206
9)
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.commit(OAbstractPaginatedStorage.java:917)
        at com.orientechnologies.orient.server.distributed.ODistributedStorage.commit(ODistributedStorage.java:819)
--More--(60%)

Error on updating record #30:1224499 (cluster: com.orientechnologies.orient.core.storage.impl.local.paginated.OPaginatedCluster@49b92c62
)
com.orientechnologies.orient.core.exception.OStorageException
        at com.orientechnologies.orient.core.storage.impl.local.paginated.OPaginatedCluster.updateRecord(OPaginatedCluster.java:874)
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.doUpdateRecord(OAbstractPaginatedStorage.java:
1668)
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.updateRecord(OAbstractPaginatedStorage.java:70
8)
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.commitEntry(OAbstractPaginatedStorage.java:209
1)
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.commit(OAbstractPaginatedStorage.java:917)
        at com.orientechnologies.orient.server.distributed.ODistributedStorage.commit(ODistributedStorage.java:819)
        at com.orientechnologies.orient.core.tx.OTransactionOptimistic.doCommit(OTransactionOptimistic.java:483)
        at com.orientechnologies.orient.core.tx.OTransactionOptimistic.commit(OTransactionOptimistic.java:147)
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.commit(ODatabaseDocumentTx.java:2406)
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.commit(ODatabaseDocumentTx.java:2376)
        at com.orientechnologies.orient.server.distributed.task.OTxTask.execute(OTxTask.java:116)
        at com.orientechnologies.orient.server.hazelcast.OHazelcastPlugin.executeOnLocalNode(OHazelcastPlugin.java:761)
        at com.orientechnologies.orient.server.hazelcast.ODistributedWorker.onMessage(ODistributedWorker.java:300)
        at com.orientechnologies.orient.server.hazelcast.ODistributedWorker.run(ODistributedWorker.java:121)
Caused by: com.orientechnologies.orient.core.storage.impl.local.paginated.atomicoperations.ONestedRollbackException: Atomic operation wa
s rolled back by internal component
        at com.orientechnologies.orient.core.storage.impl.local.paginated.atomicoperations.OAtomicOperationsManager.endAtomicOperation(O
AtomicOperationsManager.java:102)
        at com.orientechnologies.orient.core.storage.impl.local.paginated.base.ODurableComponent.endAtomicOperation(ODurableComponent.ja
va:95)
        at com.orientechnologies.orient.core.storage.impl.local.paginated.OPaginatedCluster.endAtomicOperation(OPaginatedCluster.java:11
39)
        at com.orientechnologies.orient.core.storage.impl.local.paginated.OPaginatedCluster.updateRecord(OPaginatedCluster.java:871)

**Comment by laa** [comment]
Which version do you use ?

**Comment by SatishAMP** [comment]
Hi We are using 2.0.9 SNAPSHOT

**Comment by laa** [comment]
We will provide fix today for this issue, but you would need to rebuild you data.

**Comment by clapierre** [comment]
We are also experiencing the same problem but we are using release version 1.7.4
What is the status of this bug?  I am happy to upgrade to 2.1 once released.  Will this be fixed then I see there was a 2.1 RC2 released 5 days ago but this bug is still open so its unclear and based on the comment above I am wondering if it has been addressed or not.

Below is a partial stack trace which looks to me similar to the one above.  
Thanks.

com.orientechnologies.common.directmemory.ODirectMemoryViolationException: Provided offset [4339991] is more than size of allocated area [65536]
at com.orientechnologies.common.directmemory.ODirectMemoryPointer.rangeCheck(ODirectMemoryPointer.java:163)
at com.orientechnologies.common.directmemory.ODirectMemoryPointer.getInt(ODirectMemoryPointer.java:78)
at com.orientechnologies.common.serialization.types.OIntegerSerializer.deserializeFromDirectMemory(OIntegerSerializer.java:87)
at com.orientechnologies.orient.core.storage.impl.local.paginated.base.ODurablePage.getIntValue(ODurablePage.java:85)
at com.orientechnologies.orient.core.index.sbtreebonsai.local.OSBTreeBonsaiBucket.getKey(OSBTreeBonsaiBucket.java:211)
at com.orientechnologies.orient.core.index.sbtreebonsai.local.OSBTreeBonsaiBucket.find(OSBTreeBonsaiBucket.java:134)
at com.orientechnologies.orient.core.index.sbtreebonsai.local.OSBTreeBonsaiLocal.findBucket(OSBTreeBonsaiLocal.java:1252)

**Comment by laa** [comment]
Hi,
We have fixed it in rc1.

**Comment by tglman** [comment]
this should be fixed, closing
