### ISSUE TITLE
NPE on remove edge

### ISSUE THREAD

**Issue by lvca** [orientechnologies/orientdb#4162]
java.lang.NullPointerException: null
at com.orientechnologies.orient.core.db.record.ridbag.embedded.OEmbeddedRidBag.removeEntry(OEmbeddedRidBag.java:459)
at com.orientechnologies.orient.core.db.record.ridbag.embedded.OEmbeddedRidBag.remove(OEmbeddedRidBag.java:195)
at com.orientechnologies.orient.core.db.record.ridbag.ORidBag.remove(ORidBag.java:138)
at com.tinkerpop.blueprints.impls.orient.OrientEdge.dropEdgeFromVertex(OrientEdge.java:597)
at com.tinkerpop.blueprints.impls.orient.OrientEdge.remove(OrientEdge.java:402)
at com.orientechnologies.website.services.impl.IssueServiceImpl.createUserRelationship(IssueServiceImpl.java:180)
at com.orientechnologies.website.services.impl.IssueServiceImpl.changeUser(IssueServiceImpl.java:171)

**Comment by tglman** [comment]
Hi,

do you have any step to reproduce it ?

**Comment by tglman** [comment]
I checked the code and i found out that this could happen only if you add a null in the ridbug from the api, so i added the check on the add method, this should not happen again.

by the way the origin of the problem could be also in the application code, with the fix I've done if there is an error in the application code will come out.
