### ISSUE TITLE
Collection pointer returns 0 for fileId

### ISSUE THREAD

**Issue by jberzy** [orientechnologies/orientdb#4167]
***Version:*** 2.1 rc2 non-distributed mode

***Repro Steps:*** (*note: I have not been able to reproduce this issue consistently.*)

1.From a new (plocal, graph) database  execute the following:
```
    create class Person extends V
```
```
    create class Friend extends E
```
```javascript
    var db = orient.getDatabase();
    for(i=0; i<1000; i++)
    {
	    db.command("create vertex Person set name = ?", ["test" + i]);  
    }
```

```
    create edge Friend from #12:0 to (select from Person where @rid <> #12:0)
```

2.Load the record # 12:0 via a binary client and observe the output of the fileId of the collection pointer. In my case it was returning a 0 value.

***Additional Notes:***

I noticed the following stacktrace in the logs, but I'm not certain how/if it's related:

```
Sent run-time exception to the client /0:0:0:0:0:0:0:1:58935: com.orientechnologies.orient.core.exception.OStorageException: File with id 7494618984063434752 does not exist.
com.orientechnologies.orient.core.exception.OStorageException: File with id 7494618984063434752 does not exist.
at com.orientechnologies.orient.core.index.hashindex.local.cache.OWOWCache.openFile(OWOWCache.java:408)
at com.orientechnologies.orient.core.index.hashindex.local.cache.O2QCache.openFile(O2QCache.java:156)
at com.orientechnologies.orient.core.storage.impl.local.paginated.base.ODurableComponent.openFile(ODurableComponent.java:147)
at com.orientechnologies.orient.core.index.sbtreebonsai.local.OSBTreeBonsaiLocal.load(OSBTreeBonsaiLocal.java:487)
at com.orientechnologies.orient.core.db.record.ridbag.sbtree.OSBTreeCollectionManagerShared.loadTree(OSBTreeCollectionManagerShared.java:86)
at com.orientechnologies.orient.core.db.record.ridbag.sbtree.OSBTreeCollectionManagerAbstract.loadSBTree(OSBTreeCollectionManagerAbstract.java:98)
at com.orientechnologies.orient.core.db.record.ridbag.sbtree.OSBTreeCollectionManagerProxy.loadSBTree(OSBTreeCollectionManagerProxy.java:52)
at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.sbTreeBonsaiFirstKey(ONetworkProtocolBinary.java:1861)
at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.executeRequest(ONetworkProtocolBinary.java:420)
at com.orientechnologies.orient.server.network.protocol.binary.OBinaryNetworkProtocolAbstract.execute(OBinaryNetworkProtocolAbstract.java:221)
at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:71)
```

Thanks,
John

**Comment by laa** [comment]
I tried to reproduce this issue more than 10 times without success. Do you have skype or gmail so I we will reproduce and debug it together.

**Comment by jberzy** [comment]
Hello @laa 

contact info sent to the email posted on your public profile.

Thanks,
John

**Comment by laa** [comment]
Hi @jberzy do you mean into lomakin.andrey@gmail.com ?

**Comment by jberzy** [comment]
@laa Correct

**Comment by laa** [comment]
Strange, I did not receive it. Could you send again ?

**Comment by jberzy** [comment]
Strange indeed.

Email sent and I have also added you on Skype.

Thanks,
John

**Comment by laa** [comment]
Fixed.

**Comment by laa** [comment]
Sorry closed wrong issue.

**Comment by laa** [comment]
Hi,We have fixed mt issue in ridbag could you try now ?

**Comment by jberzy** [comment]
Fixed in RC3?

**Comment by laa** [comment]
Not sure, may we chat in Skype then, to debug ?

**Comment by jberzy** [comment]
Sure, I sent you a request.

**Comment by laa** [comment]
Hi, could you do following do export/import of database and use this distribution https://www.dropbox.com/s/xs2w59sncv9ln4m/orientdb-community-2.1-SNAPSHOT-distribution.zip?dl=0 to reproduce issue if it still persists  we will fix it. Sorry for delay we were super busy with new 2.1 release.

**Comment by jberzy** [comment]
Sorry for the late reply. I unintentionally deleted the db that contained the issue. I'll try to repro again

**Comment by laa** [comment]
Hi, do you have any updates ?

**Comment by jberzy** [comment]
Hi, I could not reproduce the issue. My database could have been in a corrupted state from the server not being gracefully shutdown.

**Comment by laa** [comment]
cool, I am closing it.
