### ISSUE TITLE
Orientdb etl Login failure to a remote database

### ISSUE THREAD

**Issue by KarimOurrai** [orientechnologies/orientdb#4175]
```json
{
  "source": { "file": { "path": "./region.csv" } },
  "extractor": { "row": {} },
  "transformers": [
    { "csv": {} },
    { "vertex": { "class": "Region" } }
  ],
  "loader": {
    "orientdb": {
       "dbURL": "remote:URL_to_Database/data-ma",
       "dbUser": "User",
       "dbPassword": "Password",
       "dbAutoCreate": true,
       "standardElementConstraints": false,
       "tx": false,
       "wal": false,
       "batchCommit": 1000,
       "dbType": "graph",
       "classes": [
         {"name": "Region", "extends": "V"},
         {"name": "Country", "extends": "V"},
       ], "indexes": [
         {"class":"Region", "fields":["id:integer"], "type":"UNIQUE" }
       ]
    }
  }
}
```
Hey I have this json file I want to fill a remote database with 'orientdb etl' but it gives login failure although I can connect to it using the Console.sh (Same password and username).

error: 

```
 /opt/orientdb-community-2.1-rc2/bin/oetl.sh /path_to/region.json
OrientDB etl v.2.1-rc2 (build @BUILD@) www.orientechnologies.com
Exception in thread "main" com.orientechnologies.orient.core.exception.OConfigurationException: Error on creating ETL processor
	at com.orientechnologies.orient.etl.OETLProcessor.parse(OETLProcessor.java:275)
	at com.orientechnologies.orient.etl.OETLProcessor.parse(OETLProcessor.java:185)
	at com.orientechnologies.orient.etl.OETLProcessor.main(OETLProcessor.java:160)
Caused by: com.orientechnologies.orient.core.exception.OSecurityAccessException: User or password not valid for database: 'data-ma'
	at com.orientechnologies.orient.core.metadata.security.OSecurityShared.authenticate(OSecurityShared.java:186)
	at com.orientechnologies.orient.core.metadata.security.OSecurityProxy.authenticate(OSecurityProxy.java:87)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.open(ODatabaseDocumentTx.java:239)
	at com.orientechnologies.orient.server.OServer.openDatabase(OServer.java:631)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.openDatabase(ONetworkProtocolBinary.java:638)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.executeRequest(ONetworkProtocolBinary.java:269)
	at com.orientechnologies.orient.server.network.protocol.binary.OBinaryNetworkProtocolAbstract.execute(OBinaryNetworkProtocolAbstract.java:221)
	at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:71)
```

**Comment by lvca** [comment]
Could you send us the database so we can try it?

**Comment by prjhub** [comment]
The issue has been closed because no response has been received after a while. In case the issue is still valid, please reopen it or write a comment that explains why it's still valid and a way to reproduce it. Thank you.
