### ISSUE TITLE
DB class files corruption

### ISSUE THREAD

**Issue by PhantomYdn** [orientechnologies/orientdb#4184]
Guys,

On 2.1-SNAPSHOT after some creation of classes I see something like the following in logs

```java
Caused by: com.orientechnologies.orient.core.exception.OStorageException: File with given id exists but has different name v.pcl vs. proposed testclassa.pcl
	at com.orientechnologies.orient.core.index.hashindex.local.cache.OWOWCache.addFile(OWOWCache.java:348)
	at com.orientechnologies.orient.core.index.hashindex.local.cache.O2QCache.addFile(O2QCache.java:198)
	at com.orientechnologies.orient.core.storage.impl.local.paginated.atomicoperations.OAtomicOperation.commitChanges(OAtomicOperation.java:332)
	at com.orientechnologies.orient.core.storage.impl.local.paginated.atomicoperations.OAtomicOperationsManager.endAtomicOperation(OAtomicOperationsManager.java:121)
	at com.orientechnologies.orient.core.storage.impl.local.paginated.base.ODurableComponent.endAtomicOperation(ODurableComponent.java:81)
	at com.orientechnologies.orient.core.storage.impl.local.paginated.OPaginatedCluster.endAtomicOperation(OPaginatedCluster.java:1221)
	at com.orientechnologies.orient.core.storage.impl.local.paginated.OPaginatedCluster.create(OPaginatedCluster.java:181)
	... 33 more
```

Any ideas? [DB dump with the issue](https://drive.google.com/file/d/0BxzvQixnNXlcN2dPcThFcGJYdFE/view?usp=sharing)

**Comment by laa** [comment]
Hi Ilia,
Could you provide script to reproduce it . Or we may chat with you to debug
code on your side .

**Comment by laa** [comment]
Ah I see you provided dump for DB with issue. I will look on it then.

**Comment by PhantomYdn** [comment]
Andrey, sure - we can talk in skype: just send me a message when you will be ready:)

It's hard to provide a script. I saw that several times on 2.1-SNAPSHOT (first time around 2-3 weeks ago) and each time after creation of some OClass. It's interesting, but DB was working perfectly just till first restart. I use 'plocal'.

**Comment by laa** [comment]
I see interesting,
It seems I know the reason will try to fix it soon.

On Wed, May 20, 2015 at 12:12 AM, Ilia Naryzhny <notifications@github.com>
wrote:

> Andrey, sure - we can talk in skype: just send me a message when you will
> be ready:)
>
> It's hard to provide a script. I saw that several times on 2.1-SNAPSHOT
> (first time around 2-3 weeks ago) and each time after creation of some
> OClass. It's interesting, but DB was working perfectly just till first
> restart. I use 'plocal'.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/orientechnologies/orientdb/issues/4184#issuecomment-103668559>
> .
>



-- 
Best regards,
Andrey Lomakin.
