### ISSUE TITLE
com.orientechnologies.orient.server.distributed.ODistributedStorage cannot be cast to com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage

### ISSUE THREAD

**Issue by dblaber** [orientechnologies/orientdb#4190]
In Orientdb distributed mode 2.1-rc1, I am trying to create a schema remotely using the following code:
ODatabaseDocumentTx db = new ODatabaseDocumentTx("remote:" + server + "/SomeDB");
db.open("blah","blah");
OSchemaProxy schema = db.getMetadata().getSchema();
OClass gridElement = schema.getOrCreateClass("Event");
gridElement.createProperty("recordKey", OType.STRING).setNotNull(true);
gridElement.createIndex("recordKeyIdx", OClass.INDEX_TYPE.UNIQUE_HASH_INDEX, "recordKey");

And receive this exception:
Exception in thread "main" com.orientechnologies.orient.server.distributed.ODistributedException: Error on execution distributed COMMAND
	at com.orientechnologies.orient.server.distributed.ODistributedStorage.command(ODistributedStorage.java:409)
	at com.orientechnologies.orient.core.command.OCommandRequestTextAbstract.execute(OCommandRequestTextAbstract.java:63)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.command(ONetworkProtocolBinary.java:1172)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.executeRequest(ONetworkProtocolBinary.java:372)
	at com.orientechnologies.orient.server.network.protocol.binary.OBinaryNetworkProtocolAbstract.execute(OBinaryNetworkProtocolAbstract.java:221)
	at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:71)
Caused by: com.orientechnologies.orient.core.exception.OCommandExecutionException: Error on execution of command: sql.create index recordKeyIdx on PendingBillEvent3 ( recordKey ) UNIQUE_HASH_INDEX STRING
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.executeCommand(OAbstractPaginatedStorage.java:1215)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.command(OAbstractPaginatedStorage.java:1183)
	at com.orientechnologies.orient.server.distributed.ODistributedStorage.command(ODistributedStorage.java:222)
	at com.orientechnologies.orient.core.command.OCommandRequestTextAbstract.execute(OCommandRequestTextAbstract.java:63)
	at com.orientechnologies.orient.server.distributed.task.OSQLCommandTask.execute(OSQLCommandTask.java:70)
	at com.orientechnologies.orient.server.hazelcast.OHazelcastPlugin.executeOnLocalNode(OHazelcastPlugin.java:772)
	at com.orientechnologies.orient.server.hazelcast.ODistributedWorker.onMessage(ODistributedWorker.java:300)
	at com.orientechnologies.orient.server.hazelcast.ODistributedWorker.run(ODistributedWorker.java:121)
Caused by: java.lang.ClassCastException: com.orientechnologies.orient.server.distributed.ODistributedStorage cannot be cast to com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage
	at com.orientechnologies.orient.core.index.hashindex.local.OHashIndexFactory.createIndex(OHashIndexFactory.java:107)
	at com.orientechnologies.orient.core.index.OIndexes.createIndex(OIndexes.java:165)
	at com.orientechnologies.orient.core.index.OIndexManagerShared.createIndex(OIndexManagerShared.java:154)
	at com.orientechnologies.orient.core.index.OIndexManagerProxy.createIndex(OIndexManagerProxy.java:79)
	at com.orientechnologies.orient.core.sql.OCommandExecutorSQLCreateIndex.execute(OCommandExecutorSQLCreateIndex.java:268)
	at com.orientechnologies.orient.core.sql.OCommandExecutorSQLDelegate.execute(OCommandExecutorSQLDelegate.java:83)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.executeCommand(OAbstractPaginatedStorage.java:1202)
	... 7 more

**Comment by dblaber** [comment]
I realize this is a duplicate of  #4177
