### ISSUE TITLE
Can not create UNIQUE/NONUNIQUE index in distributed mode 

### ISSUE THREAD

**Issue by dblaber** [orientechnologies/orientdb#4202]
In  #4177 , the issue with distributed+hash index is fixed, however it effects more than just hash index (or it is another issue). This is orientdb 2.1 rc2, no hashindex. As of right now, it seems there is no way to use a index in distributed mode. 
I am creating a Schema with Unique Index and NOTUNIQUE index and am receiving this exception:
Exception in thread "main" com.orientechnologies.orient.core.exception.OTransactionException: Error on committing distributed transaction
	at com.orientechnologies.orient.server.distributed.ODistributedStorage.commit(ODistributedStorage.java:967)
	at com.orientechnologies.orient.core.tx.OTransactionOptimistic.doCommit(OTransactionOptimistic.java:491)
	at com.orientechnologies.orient.core.tx.OTransactionOptimistic.commit(OTransactionOptimistic.java:148)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.commit(ODatabaseDocumentTx.java:2412)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.commit(ODatabaseDocumentTx.java:2382)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.commit(ONetworkProtocolBinary.java:1074)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.executeRequest(ONetworkProtocolBinary.java:376)
	at com.orientechnologies.orient.server.network.protocol.binary.OBinaryNetworkProtocolAbstract.execute(OBinaryNetworkProtocolAbstract.java:221)
	at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:71)
Caused by: com.orientechnologies.orient.core.index.OIndexException: Error during insertion of key in index
	at com.orientechnologies.orient.core.index.OIndexMultiValues.put(OIndexMultiValues.java:141)
	at com.orientechnologies.orient.core.index.OIndexMultiValues.put(OIndexMultiValues.java:52)
	at com.orientechnologies.orient.core.index.OIndexAbstract.putInSnapshot(OIndexAbstract.java:871)
	at com.orientechnologies.orient.core.index.OIndexAbstract.applyIndexTxEntry(OIndexAbstract.java:1051)
	at com.orientechnologies.orient.core.index.OIndexAbstract.addTxOperation(OIndexAbstract.java:685)
	at com.orientechnologies.orient.core.tx.OTransactionOptimistic$CommitIndexesCallback.run(OTransactionOptimistic.java:99)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.commit(OAbstractPaginatedStorage.java:927)
	at com.orientechnologies.orient.server.distributed.ODistributedStorage.commit(ODistributedStorage.java:831)
	at com.orientechnologies.orient.core.tx.OTransactionOptimistic.doCommit(OTransactionOptimistic.java:491)
	at com.orientechnologies.orient.core.tx.OTransactionOptimistic.commit(OTransactionOptimistic.java:148)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.commit(ODatabaseDocumentTx.java:2412)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.commit(ODatabaseDocumentTx.java:2382)
	at com.orientechnologies.orient.server.distributed.task.OTxTask.execute(OTxTask.java:115)
	at com.orientechnologies.orient.server.hazelcast.OHazelcastPlugin.executeOnLocalNode(OHazelcastPlugin.java:772)
	at com.orientechnologies.orient.server.hazelcast.ODistributedWorker.onMessage(ODistributedWorker.java:300)
	at com.orientechnologies.orient.server.hazelcast.ODistributedWorker.run(ODistributedWorker.java:121)
Caused by: java.lang.ClassCastException: com.orientechnologies.orient.server.distributed.ODistributedStorage cannot be cast to com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage
	at com.orientechnologies.orient.core.db.record.ridbag.sbtree.OIndexRIDContainer.convertToSbTree(OIndexRIDContainer.java:237)
	at com.orientechnologies.orient.core.db.record.ridbag.sbtree.OIndexRIDContainer.checkTopThreshold(OIndexRIDContainer.java:208)
	at com.orientechnologies.orient.core.db.record.ridbag.sbtree.OIndexRIDContainer.add(OIndexRIDContainer.java:147)
	at com.orientechnologies.orient.core.db.record.ridbag.sbtree.OIndexRIDContainer.add(OIndexRIDContainer.java:44)
	at com.orientechnologies.orient.core.index.OIndexMultiValues.put(OIndexMultiValues.java:133)
	... 15 more

**Comment by dblaber** [comment]
Created a pull request #4205 that does the same thing as #4177 (hash) but for sbtree

**Comment by lvca** [comment]
Thanks, I've just applied it.
