### ISSUE TITLE
OrientDB SAIL Exception on parenthesis containing URLs

### ISSUE THREAD

**Issue by redskate** [orientechnologies/orientdb#4220]
Hi - I do not know whether this here is the right place for placing that - please excuse me if I am wrong. 

OrientDB rc3 is using openrdf 2.6

In loading RDF with a reduced file containing one single line like
<http://dbpedia.org/resource/Futurama_(TV_series)> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://www.w3.org/2004/02/skos/core#Concept> .

And having put in a sturcture spo, 

The code
sc.addStatement(
			vf.createURI(spo.s), 
			vf.createURI(spo.p), 
			ouri, 
			importgraphurl );
sc.commit();

generate the following exception (because of the parenthesis in the url):see below.

com.orientechnologies.orient.core.index.OIndexException: Error during insertion of key in index
	at com.orientechnologies.orient.core.index.OIndexMultiValues.put(OIndexMultiValues.java:141)
	at com.orientechnologies.orient.core.index.OIndexMultiValues.put(OIndexMultiValues.java:52)
	at com.orientechnologies.orient.core.index.OIndexAbstract.putInSnapshot(OIndexAbstract.java:871)
	at com.orientechnologies.orient.core.index.OIndexAbstract.applyIndexTxEntry(OIndexAbstract.java:1051)
	at com.orientechnologies.orient.core.index.OIndexAbstract.addTxOperation(OIndexAbstract.java:685)
	at com.orientechnologies.orient.core.tx.OTransactionOptimistic$CommitIndexesCallback.run(OTransactionOptimistic.java:99)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.commit(OAbstractPaginatedStorage.java:927)
	at com.orientechnologies.orient.core.tx.OTransactionOptimistic.doCommit(OTransactionOptimistic.java:491)
	at com.orientechnologies.orient.core.tx.OTransactionOptimistic.commit(OTransactionOptimistic.java:148)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.commit(ODatabaseDocumentTx.java:2412)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.commit(ODatabaseDocumentTx.java:2382)
	at com.tinkerpop.blueprints.impls.orient.OrientTransactionalGraph.commit(OrientTransactionalGraph.java:161)
	at com.tinkerpop.blueprints.oupls.sail.GraphSailConnection.commitInternal(GraphSailConnection.java:74)
	at org.openrdf.sail.helpers.SailConnectionBase.commit(SailConnectionBase.java:305)
	at com.semweb.load.OrientDBLoader.load_nt_file(OrientDBLoader.java:357)
	at com.semweb.load.OrientDBLoader.traverse_dir(OrientDBLoader.java:517)
	at com.semweb.load.OrientDBLoader.main(OrientDBLoader.java:177)
Caused by: com.orientechnologies.orient.core.index.sbtree.local.OSBTreeException: Error during index update with key #10:20178499 and value true
	at com.orientechnologies.orient.core.index.sbtreebonsai.local.OSBTreeBonsaiLocal.put(OSBTreeBonsaiLocal.java:308)
	at com.orientechnologies.orient.core.db.record.ridbag.sbtree.OIndexRIDContainerSBTree.add(OIndexRIDContainerSBTree.java:137)
	at com.orientechnologies.orient.core.db.record.ridbag.sbtree.OIndexRIDContainerSBTree.add(OIndexRIDContainerSBTree.java:47)
	at com.orientechnologies.orient.core.db.record.ridbag.sbtree.OIndexRIDContainer.add(OIndexRIDContainer.java:146)
	at com.orientechnologies.orient.core.db.record.ridbag.sbtree.OIndexRIDContainer.add(OIndexRIDContainer.java:44)
	at com.orientechnologies.orient.core.index.OIndexMultiValues.put(OIndexMultiValues.java:133)
	... 16 more
Caused by: java.lang.NullPointerException
	at com.orientechnologies.orient.core.storage.impl.local.paginated.atomicoperations.OAtomicOperation.releasePage(OAtomicOperation.java:151)
	at com.orientechnologies.orient.core.storage.impl.local.paginated.base.ODurableComponent.releasePage(ODurableComponent.java:128)
	at com.orientechnologies.orient.core.index.sbtreebonsai.local.OSBTreeBonsaiLocal.findBucket(OSBTreeBonsaiLocal.java:1241)
	at com.orientechnologies.orient.core.index.sbtreebonsai.local.OSBTreeBonsaiLocal.put(OSBTreeBonsaiLocal.java:262)
	... 21 more

**Comment by lvca** [comment]
This should be already fixed. Any chance to try with v2.1.2?
