### ISSUE TITLE
OStreamSerializerSBTreeIndexRIDContainer  com.orientechnologies.orient.server.distributed.ODistributedStorage cannot be cast to com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage

### ISSUE THREAD

**Issue by dblaber** [orientechnologies/orientdb#4237]
As in #4202, it seems like in distributed mode, this issue also exists.

n: Error on committing distributed transaction [ONetworkProtocolBinary]Error on distributed transaction commit
com.orientechnologies.orient.core.index.OIndexException: Error during insertion of key in index
        at com.orientechnologies.orient.core.index.OIndexMultiValues.put(OIndexMultiValues.java:141)
        at com.orientechnologies.orient.core.index.OIndexMultiValues.put(OIndexMultiValues.java:52)
        at com.orientechnologies.orient.core.index.OIndexAbstract.putInSnapshot(OIndexAbstract.java:870)
        at com.orientechnologies.orient.core.index.OIndexAbstract.applyIndexTxEntry(OIndexAbstract.java:1050)
        at com.orientechnologies.orient.core.index.OIndexAbstract.addTxOperation(OIndexAbstract.java:684)
        at com.orientechnologies.orient.core.tx.OTransactionOptimistic$CommitIndexesCallback.run(OTransactionOptimistic.java:100)
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.commit(OAbstractPaginatedStorage.java:930)
        at com.orientechnologies.orient.server.distributed.ODistributedStorage.commit(ODistributedStorage.java:882)
        at com.orientechnologies.orient.core.tx.OTransactionOptimistic.doCommit(OTransactionOptimistic.java:590)
        at com.orientechnologies.orient.core.tx.OTransactionOptimistic.commit(OTransactionOptimistic.java:149)
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.commit(ODatabaseDocumentTx.java:2486)
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.commit(ODatabaseDocumentTx.java:2456)
        at com.orientechnologies.orient.server.distributed.task.OTxTask.execute(OTxTask.java:129)
        at com.orientechnologies.orient.server.hazelcast.OHazelcastPlugin.executeOnLocalNode(OHazelcastPlugin.java:776)
        at com.orientechnologies.orient.server.hazelcast.ODistributedWorker.onMessage(ODistributedWorker.java:300)
        at com.orientechnologies.orient.server.hazelcast.ODistributedWorker.run(ODistributedWorker.java:121)
Caused by: java.lang.ClassCastException: com.orientechnologies.orient.server.distributed.ODistributedStorage cannot be cast to com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage
        at com.orientechnologies.orient.core.serialization.serializer.stream.OStreamSerializerSBTreeIndexRIDContainer.deserializeFromDirectMemoryObject(OStreamSerializerSBTreeIndexRIDContainer.java:258)
        at com.orientechnologies.orient.core.serialization.serializer.stream.OStreamSerializerSBTreeIndexRIDContainer.deserializeFromDirectMemoryObject(OStreamSerializerSBTreeIndexRIDContainer.java:40)
        at com.orientechnologies.orient.core.storage.impl.local.paginated.base.ODurablePage.deserializeFromDirectMemory(ODurablePage.java:129)
        at com.orientechnologies.orient.core.index.sbtree.local.OSBTreeBucket.getEntry(OSBTreeBucket.java:215)
        at com.orientechnologies.orient.core.index.sbtree.local.OSBTree.get(OSBTree.java:198)
        at com.orientechnologies.orient.core.index.engine.OSBTreeIndexEngine.get(OSBTreeIndexEngine.java:232)
        at com.orientechnologies.orient.core.index.OIndexMultiValues.put(OIndexMultiValues.java:115)
        ... 15 more

2.1-rc3

**Comment by optimuspaul** [comment]
I'm seeing something similar
```
PyOrientCommandException: com.orientechnologies.orient.core.exception.OTransactionExceptioncom.orientechnologies.orient.core.exception.OStorageExceptionjava.lang.ClassCastException - Error on committing distributed transactionError during transaction commit.com.orientechnologies.orient.server.distributed.ODistributedStorage cannot be cast to com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage
```

**Comment by lvca** [comment]
This problem seems old. Did you try with v2.1.2?
