### ISSUE TITLE
Cannot obtain an OUser instance when the username contains a single quote character (')

### ISSUE THREAD

**Issue by giastfader** [orientechnologies/orientdb#4260]
OSecurity.getUser("a'");

raises the following exception:
```
an expected error has been detected: java.lang.IllegalStateException: Missing closed string character: ''', position: 43
	at com.orientechnologies.common.parser.OBaseParser.parserNextWord(OBaseParser.java:575)
	at com.orientechnologies.common.parser.OBaseParser.parserNextWord(OBaseParser.java:464)
	at com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.parse(OCommandExecutorSQLSelect.java:226)
	at com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.parse(OCommandExecutorSQLSelect.java:112)
	at com.orientechnologies.orient.core.sql.OCommandExecutorSQLDelegate.parse(OCommandExecutorSQLDelegate.java:52)
	at com.orientechnologies.orient.core.sql.OCommandExecutorSQLDelegate.parse(OCommandExecutorSQLDelegate.java:33)
	at com.orientechnologies.orient.core.storage.OStorageEmbedded.command(OStorageEmbedded.java:101)
	at com.orientechnologies.orient.core.sql.query.OSQLQuery.run(OSQLQuery.java:69)
	at com.orientechnologies.orient.core.sql.query.OSQLSynchQuery.run(OSQLSynchQuery.java:80)
	at com.orientechnologies.orient.core.query.OQueryAbstract.execute(OQueryAbstract.java:29)
	at com.orientechnologies.orient.core.metadata.security.OSecurityShared.getUser(OSecurityShared.java:440)
	at com.orientechnologies.orient.core.metadata.security.OSecurityShared.getUser(OSecurityShared.java:178)
	at com.orientechnologies.orient.core.metadata.security.OSecurityProxy.getUser(OSecurityProxy.java:87)
```

The version is 1.7.10, but I verified in the develop branch that the bugged code is still present:

https://github.com/orientechnologies/orientdb/blob/develop/core/src/main/java/com/orientechnologies/orient/core/metadata/security/OSecurityShared.java#L493

**Comment by luigidellaquila** [comment]
Hi @giastfader 

thanks for reporting, I'm fixing it right now

**Comment by luigidellaquila** [comment]
fixed in develop branch
