### ISSUE TITLE
Asynchronous replication mode (1 node) - properties and edges lost for some vertices

### ISSUE THREAD

**Issue by ylopotun** [orientechnologies/orientdb#4270]
We experience an issue that blocks us from moving on with the replication feature: after we execute a few batches of create vertex/create edge/set vertex property operations (e.g. 3 batches, each batch contains ~1000 operations) we end up with a few vertices that lost all their edges and properties.

I spent a few hours trying to reproduce it in a unit test, but wasn’t able to do it.
The log information seems good to me – last message related to this vertex shows all its properties and edges correctly:
```
2015-05-28 19:45:45,383 [pool-1-thread-5] INFO com.mira.mcs.ucs.ds.pers.orie.OrientDSUtils - createEdge; from: v(DSRecord)[#19:1972]; v: 6; props from: {number=106, in_record=[size=1], out_inputPorts=[size=1], out_outputPorts=[#84:14], @rid=#19:1972, @class=DSRecord, in_devices=[size=1]}; edges from: 4
```
The only exception related to this vertex is the following (in fact, the stale vertex in this case is the vertex to which we create an edge from #19:1972, not #19:1972 itself):
```
2015-05-28 19:45:45,382 [pool-1-thread-5] DEBUG com.orie.orie.core.stor.impl.loca.pagi.OLocalPaginatedStorage - Error during transaction commit, transaction will be rolled back (tx-id=35302)
com.orientechnologies.orient.core.exception.OConcurrentModificationException: Cannot UPDATE the record #19:2697 because the version is not the latest. Probably you are updating an old record or it has been modified by another user (db=v4 your=v3)
       at com.orientechnologies.orient.core.conflict.OVersionRecordConflictStrategy.checkVersions(OVersionRecordConflictStrategy.java:55)
       at com.orientechnologies.orient.core.conflict.OVersionRecordConflictStrategy.onUpdate(OVersionRecordConflictStrategy.java:42)
       at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.checkAndIncrementVersion(OAbstractPaginatedStorage.java:1962)
       at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.doUpdateRecord(OAbstractPaginatedStorage.java:1612)
       at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.updateRecord(OAbstractPaginatedStorage.java:716)
       at com.orientechnologies.orient.server.distributed.ODistributedStorage.updateRecord(ODistributedStorage.java:642)
       at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.executeSaveRecord(ODatabaseDocumentTx.java:1806)
       at com.orientechnologies.orient.core.tx.OTransactionOptimistic.addRecord(OTransactionOptimistic.java:414)
       at com.orientechnologies.orient.core.tx.OTransactionOptimistic.saveRecord(OTransactionOptimistic.java:348)
       at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.save(ODatabaseDocumentTx.java:2372)
       at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.save(ODatabaseDocumentTx.java:119)
       at com.orientechnologies.orient.core.record.impl.ODocument.save(ODocument.java:1690)
       at com.orientechnologies.orient.core.record.impl.ODocument.save(ODocument.java:1681)
       at com.orientechnologies.orient.core.record.impl.ODocument.save(ODocument.java:100)
       at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinaryV0.recursiveLinkSave(ORecordSerializerBinaryV0.java:671)
       at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinaryV0.writeOptimizedLink(ORecordSerializerBinaryV0.java:685)
       at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinaryV0.writeSingleValue(ORecordSerializerBinaryV0.java:569)
       at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinaryV0.serialize(ORecordSerializerBinaryV0.java:258)
       at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinary.toStream(ORecordSerializerBinary.java:104)
       at com.orientechnologies.orient.core.record.impl.ODocument.toStream(ODocument.java:2194)
       at com.orientechnologies.orient.core.record.impl.ODocument.toStream(ODocument.java:679)
       at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.executeSaveRecord(ODatabaseDocumentTx.java:1736)
       at com.orientechnologies.orient.core.tx.OTransactionOptimistic.addRecord(OTransactionOptimistic.java:414)
       at com.orientechnologies.orient.core.tx.OTransactionOptimistic.saveRecord(OTransactionOptimistic.java:348)
       at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.save(ODatabaseDocumentTx.java:2372)
       at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.save(ODatabaseDocumentTx.java:119)
       at com.orientechnologies.orient.core.record.impl.ODocument.save(ODocument.java:1690)
       at com.orientechnologies.orient.core.record.impl.ODocument.save(ODocument.java:1681)
       at com.orientechnologies.orient.core.record.impl.ODocument.save(ODocument.java:100)
       at com.orientechnologies.orient.core.db.record.ridbag.embedded.OEmbeddedRidBag.serialize(OEmbeddedRidBag.java:372)
       at com.orientechnologies.orient.core.db.record.ridbag.ORidBag.toStream(ORidBag.java:264)
       at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinaryV0.writeSingleValue(ORecordSerializerBinaryV0.java:578)
       at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinaryV0.serialize(ORecordSerializerBinaryV0.java:258)
       at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinary.toStream(ORecordSerializerBinary.java:104)
       at com.orientechnologies.orient.core.record.impl.ODocument.toStream(ODocument.java:2194)
       at com.orientechnologies.orient.core.record.impl.ODocument.toStream(ODocument.java:679)
       at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.commitEntry(OAbstractPaginatedStorage.java:2040)
       at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.commit(OAbstractPaginatedStorage.java:925)
       at com.orientechnologies.orient.server.distributed.ODistributedStorage$12.call(ODistributedStorage.java:1077)
       at com.orientechnologies.orient.server.distributed.ODistributedAbstractPlugin.runInDistributedMode(ODistributedAbstractPlugin.java:75)
       at com.orientechnologies.orient.server.distributed.ODistributedStorage.commit(ODistributedStorage.java:1073)
       at com.orientechnologies.orient.core.tx.OTransactionOptimistic.doCommit(OTransactionOptimistic.java:590)
       at com.orientechnologies.orient.core.tx.OTransactionOptimistic.commit(OTransactionOptimistic.java:149)
       at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.commit(ODatabaseDocumentTx.java:2486)
       at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.commit(ODatabaseDocumentTx.java:2456)
       at com.tinkerpop.blueprints.impls.orient.OrientTransactionalGraph.commit(OrientTransactionalGraph.java:161)
       at com.miranda.mcs.ucs.ds.persistence.orientdb.OrientDSUtils.createEdge(OrientDSUtils.java:932)
       at com.miranda.mcs.ucs.ds.persistence.orientdb.OrientDSUtils.addEdge(OrientDSUtils.java:1001)
       at com.miranda.mcs.ucs.ds.persistence.orientdb.OrientRecord.addEdges(OrientRecord.java:532)
       at com.miranda.mcs.ucs.ds.persistence.orientdb.OrientRecord.addValues(OrientRecord.java:417)
       at com.miranda.mcs.ucs.ds.factory.RecordFactory.lambda$adjustCount$128(RecordFactory.java:286)
       at com.miranda.mcs.ucs.ds.factory.RecordFactory$$Lambda$93/1772859730.accept(Unknown Source)
       at java.util.stream.Streams$RangeIntSpliterator.forEachRemaining(Streams.java:114)
       at java.util.stream.IntPipeline$Head.forEach(IntPipeline.java:557)
       at com.miranda.mcs.ucs.ds.factory.RecordFactory.adjustCount(RecordFactory.java:275)
       at com.miranda.mcs.ucs.models.factory.CardFactory.adjustCount(CardFactory.java:89)
       at com.miranda.mcs.ucs.ds.factory.RecordFactory.lambda$create$126(RecordFactory.java:170)
       at com.miranda.mcs.ucs.ds.factory.RecordFactory$$Lambda$92/2058973635.accept(Unknown Source)
       at com.miranda.mcs.ucs.ds.util.DSUtils$ScopeHandler.lambda$notifyConsumers$178(DSUtils.java:931)
       at com.miranda.mcs.ucs.ds.util.DSUtils$ScopeHandler$$Lambda$155/461816111.accept(Unknown Source)
       at java.lang.Iterable.forEach(Iterable.java:75)
       at com.miranda.mcs.ucs.ds.util.DSUtils$ScopeHandler.notifyConsumers(DSUtils.java:927)
       at com.miranda.mcs.ucs.ds.util.DSUtils$ScopeHandler.access$400(DSUtils.java:710)
       at com.miranda.mcs.ucs.ds.util.DSUtils$ScopeHandler$ConsumerImplementation.accept(DSUtils.java:786)
       at com.miranda.mcs.ucs.ds.util.DSUtils$ScopeHandler.lambda$notifyConsumers$178(DSUtils.java:931)
       at com.miranda.mcs.ucs.ds.util.DSUtils$ScopeHandler$$Lambda$155/461816111.accept(Unknown Source)
       at java.lang.Iterable.forEach(Iterable.java:75)
       at com.miranda.mcs.ucs.ds.util.DSUtils$ScopeHandler.notifyConsumers(DSUtils.java:927)
       at com.miranda.mcs.ucs.ds.util.DSUtils$ScopeHandler.access$400(DSUtils.java:710)
       at com.miranda.mcs.ucs.ds.util.DSUtils$ScopeHandler$ConsumerImplementation.accept(DSUtils.java:786)
       at com.miranda.mcs.ucs.ds.util.DSUtils$ScopeHandler.lambda$notifyConsumers$178(DSUtils.java:931)
       at com.miranda.mcs.ucs.ds.util.DSUtils$ScopeHandler$$Lambda$155/461816111.accept(Unknown Source)
       at java.lang.Iterable.forEach(Iterable.java:75)
       at com.miranda.mcs.ucs.ds.util.DSUtils$ScopeHandler.notifyConsumers(DSUtils.java:927)
       at com.miranda.mcs.ucs.ds.util.DSUtils$ScopeHandler.lambda$initialize$176(DSUtils.java:877)
       at com.miranda.mcs.ucs.ds.util.DSUtils$ScopeHandler$$Lambda$77/1942280.propertyChange(Unknown Source)
       at java.beans.PropertyChangeSupport.fire(PropertyChangeSupport.java:335)
       at java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:328)
       at com.miranda.mcs.ucs.ds.persistence.orientdb.OrientTable.lambda$fireRecordPropertyChange$42(OrientTable.java:732)
       at com.miranda.mcs.ucs.ds.persistence.orientdb.OrientTable$$Lambda$72/1308180856.run(Unknown Source)
       at com.miranda.mcs.ucs.ds.persistence.orientdb.OrientTable.fireRecordPropertyChange(OrientTable.java:735)
       at com.miranda.mcs.ucs.ds.persistence.orientdb.OrientRecord.lambda$handleUpdate$61(OrientRecord.java:957)
       at com.miranda.mcs.ucs.ds.persistence.orientdb.OrientRecord$$Lambda$52/369064438.run(Unknown Source)
       at com.miranda.mcs.ucs.ds.persistence.orientdb.OrientDataManager.lambda$runTask$29(OrientDataManager.java:1721)
       at com.miranda.mcs.ucs.ds.persistence.orientdb.OrientDataManager$$Lambda$7/1238055041.accept(Unknown Source)
       at com.miranda.mcs.ucs.ds.persistence.orientdb.OrientDataManager.lambda$withGraph$20(OrientDataManager.java:1203)
       at com.miranda.mcs.ucs.ds.persistence.orientdb.OrientDataManager$$Lambda$8/437583344.apply(Unknown Source)
       at com.miranda.mcs.ucs.ds.persistence.orientdb.OrientDataManager.fromGraph(OrientDataManager.java:1187)
       at com.miranda.mcs.ucs.ds.persistence.orientdb.OrientDataManager.withGraph(OrientDataManager.java:1203)
       at com.miranda.mcs.ucs.ds.persistence.orientdb.OrientDataManager.runTask(OrientDataManager.java:1721)
       at com.miranda.mcs.ucs.ds.DataManagerFactory.lambda$runBackgroundTask$103(DataManagerFactory.java:216)
       at com.miranda.mcs.ucs.ds.DataManagerFactory$$Lambda$11/781357442.call(Unknown Source)
       at java.util.concurrent.FutureTask.run(FutureTask.java:266)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
       at java.lang.Thread.run(Thread.java:745)
```
In case of create edge and set vertex property operations, if concurrent modification exception is thrown, we reload the vertex and re-try the operation, so this should not be an issue.
Do you have any ideas what could be the cause or suggestions on how to pin-point it?
As I already mention, this is a blocker for us so we’d appreciate your assistance.

**Comment by lvca** [comment]
The exception is related to record #19:2697. How this is connected with #19:1972 you mentioned?

**Comment by ylopotun** [comment]
"...the stale vertex in this case is the vertex to which we create an edge from #19:1972, not #19:1972 itself)"

**Comment by lvca** [comment]
So seems the problem could be related to the new version of the stale record incremented because of deep save from node `#19:1972 `. So seems OrientDB has an old copy of record in memory. I tried to reproduce this, but with no success: the local copy of connected vertex is always updated. Can you be more specific about how this happens or do you have a piece of code to reproduce this issue?

**Comment by ylopotun** [comment]
I was able to reproduce the issue with 2.1-SNAPSHOT in a unit test (sent via e-mail).
