### ISSUE TITLE
Error: java.lang.NumberFormatException: For input string: "�EE�"

### ISSUE THREAD

**Issue by StarpTech** [orientechnologies/orientdb#4277]
I got following error during importing. I had to import my db via the JSON format.

Before OrientDb 2.0.9
Upgrade to OrientDb: 2.0.10

```
Connecting to database [plocal:../databases/test] with user 'bc24prod'...OK
orientdb {db=test}> import database /opt/backups/current.zip -preserveClusterIDs=true

Importing database database /opt/backups/current.zip -preserveClusterIDs=true...
Started import of database 'plocal:../databases/test' from /opt/backups/current.zip...
Non merge mode (-merge=false): removing all default non security classes
- Class _studio was removed.
- Class E was removed.
- Class V was removed.
- Class OTriggered was removed.
- Class ORestricted was removed.
- Class OSchedule was removed.
- Class ORIDs was removed.
- Class OFunction was removed.
Removed 8 classes.Error on database import happened just before line 14, column 52
java.lang.NumberFormatException: For input string: "�EE�"
        at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
        at java.lang.Integer.parseInt(Integer.java:580)
        at com.orientechnologies.orient.core.serialization.serializer.OJSONReader.nextChar(OJSONReader.java:273)
        at com.orientechnologies.orient.core.serialization.serializer.OJSONReader.readNext(OJSONReader.java:174)
        at com.orientechnologies.orient.core.serialization.serializer.OJSONReader.readString(OJSONReader.java:92)
        at com.orientechnologies.orient.core.serialization.serializer.OJSONReader.readString(OJSONReader.java:87)
        at com.orientechnologies.orient.core.serialization.serializer.OJSONReader.readString(OJSONReader.java:83)
        at com.orientechnologies.orient.core.db.tool.ODatabaseImport.importDatabase(ODatabaseImport.java:416)
        at com.orientechnologies.orient.console.OConsoleDatabaseApp.importDatabase(OConsoleDatabaseApp.java:1534)
        at com.orientechnologies.orient.graph.console.OGremlinConsole.importDatabase(OGremlinConsole.java:124)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at com.orientechnologies.common.console.OConsoleApplication.execute(OConsoleApplication.java:383)
        at com.orientechnologies.common.console.OConsoleApplication.executeCommands(OConsoleApplication.java:248)
        at com.orientechnologies.common.console.OConsoleApplication.run(OConsoleApplication.java:137)
        at com.orientechnologies.orient.graph.console.OGremlinConsole.main(OGremlinConsole.java:62)

Error: com.orientechnologies.orient.core.db.tool.ODatabaseExportException: Error on importing database 'test' from file: /opt/backups/current.zip

Error: java.lang.NumberFormatException: For input string: "�EE�"

orientdb {db=test}> exit

```

**Comment by lvca** [comment]
Is it possible any record had that content? The problem could be the used encoding. Are you using any particular encoding ?

**Comment by StarpTech** [comment]
I do nothing with encoding. I read and write with the oriento driver and only one field  of my class is of type INTEGER field 'Points'. I can't see any illegal character in this field. I think it is core related.

**Comment by lvca** [comment]
Did you see that chars in the OrientDB export?

**Comment by StarpTech** [comment]
I didn't see anything
