### ISSUE TITLE
java.lang.ArrayIndexOutOfBoundsException 2.0.10

### ISSUE THREAD

**Issue by valenpo** [orientechnologies/orientdb#4280]
When restoring from wal files some times get java.lang.ArrayIndexOutOfBoundsException

```
java.lang.ArrayIndexOutOfBoundsException: null
        at java.lang.System.arraycopy(Native Method)
        at com.orientechnologies.orient.core.storage.impl.local.paginated.wal.OWALChangesTree.fromStream(OWALChangesTree.java:325)
        at com.orientechnologies.orient.core.storage.impl.local.paginated.wal.OUpdatePageRecord.fromStream(OUpdatePageRecord.java:66)
        at com.orientechnologies.orient.core.storage.impl.local.paginated.wal.OWALRecordsFactory.fromStream(OWALRecordsFactory.java:134)
        at com.orientechnologies.orient.core.storage.impl.local.paginated.wal.ODiskWriteAheadLog.read(ODiskWriteAheadLog.java:1021)
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.restoreFrom(OAbstractPaginatedStorage.java:2211)
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.restoreFromFuzzyCheckPoint(OAbstractPaginatedStorage.java:2191)
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.restoreFromCheckPoint(OAbstractPaginatedStorage.java:2166)
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.restoreFromWAL(OAbstractPaginatedStorage.java:2099)
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.restoreIfNeeded(OAbstractPaginatedStorage.java:1473)
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.open(OAbstractPaginatedStorage.java:175)
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.open(ODatabaseDocumentTx.java:244)
        at com.tinkerpop.blueprints.impls.orient.OrientBaseGraph.openOrCreate(OrientBaseGraph.java:1822)
        at com.tinkerpop.blueprints.impls.orient.OrientBaseGraph.<init>(OrientBaseGraph.java:171)
        at com.tinkerpop.blueprints.impls.orient.OrientTransactionalGraph.<init>(OrientTransactionalGraph.java:103)
        at com.tinkerpop.blueprints.impls.orient.OrientTransactionalGraph.<init>(OrientTransactionalGraph.java:99)
        at com.tinkerpop.blueprints.impls.orient.OrientGraph.<init>(OrientGraph.java:69)
        at com.stimulus.archiva.ej.a(MailArchiva:113)
        at com.stimulus.archiva.ei.a(MailArchiva:83)
        at com.stimulus.archiva.database.DatabaseService.b(MailArchiva:303)
        at com.stimulus.archiva.domain.bk$a.run(MailArchiva:163)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
```

**Comment by laa** [comment]
Hi , could you get me example of this wal file ?

**Comment by valenpo** [comment]
Andrey, hi. 
Client deleted all wal files, if we get such file I’ll attach next time. 

> On 3 июня 2015 г., at 12:30, Andrey Lomakin <notifications@github.com> wrote:
> 
> Hi , could you get me example of this wal file ?
> 
> —
> Reply to this email directly or view it on GitHub <https://github.com/orientechnologies/orientdb/issues/4280#issuecomment-108265604>.
> 


Regards,
Valentin Popov

**Comment by laa** [comment]
Sorry we can not this bug without data which caused it we will create tool which automatically backups WAL files in case of exception.
