### ISSUE TITLE
NullPointerException when querying out vertices

### ISSUE THREAD

**Issue by ylopotun** [orientechnologies/orientdb#4284]
When we perform the following query (e.g. via console):
select expand(out('record')) from 14:15 limit 30
it returns an exception:
Error: com.orientechnologies.orient.core.exception.OCommandExecutionException: Error on execution of command: sql.select expand(out('record')) from 14:15 limit 50
Error: java.lang.NullPointerException

I'll send our sample DB via e-mail.

**Comment by luigidellaquila** [comment]
Applied a general high level fix that avoids the problem (on graph API).
Keeping this open to investigate possible flaws in RidBag iterators at a lower level

**Comment by luigidellaquila** [comment]
@laa any advice is welcome on this

**Comment by ylopotun** [comment]
Thanks Luigi. Will your fix work for an existing data or only for the newly created data?

**Comment by luigidellaquila** [comment]
Hi Yuriy,

the fix will work also on existing data. I tried it on your db and it
worked fine.

Thanks

Luigi


2015-06-04 18:00 GMT+02:00 ylopotun <notifications@github.com>:

**Comment by ylopotun** [comment]
So, the mentioned exception no longer appears, but if I do:
select from [14:93, 14:94]

I get another NullPointerException in the server log:

2015-06-04 15:25:28:245 INFO OrientDB Server v2.1-rc3 (build UNKNOWN@r${buildNumber}; 2015-05-22 16:53:13+0000) is active. [OServer]{db=MirandaDS} Fetching error on record #14:94 java.lang.NullPointerException
at com.orientechnologies.orient.core.storage.impl.local.paginated.base.ODurablePage.deserializeFromDirectMemory(ODurablePage.java:127)
at com.orientechnologies.orient.core.index.sbtreebonsai.local.OSBTreeBonsaiBucket.getEntry(OSBTreeBonsaiBucket.java:273)
at com.orientechnologies.orient.core.index.sbtreebonsai.local.OSBTreeBonsaiLocal.findBucket(OSBTreeBonsaiLocal.java:1235)
at com.orientechnologies.orient.core.index.sbtreebonsai.local.OSBTreeBonsaiLocal.loadEntriesMajor(OSBTreeBonsaiLocal.java:729)
at com.orientechnologies.orient.core.index.sbtreebonsai.local.OSBTreeBonsaiLocal.getRealBagSize(OSBTreeBonsaiLocal.java:1335)
at com.orientechnologies.orient.core.db.record.ridbag.sbtree.OSBTreeRidBag.updateSize(OSBTreeRidBag.java:953)
at com.orientechnologies.orient.core.db.record.ridbag.sbtree.OSBTreeRidBag.size(OSBTreeRidBag.java:692)
at com.orientechnologies.orient.core.db.record.ridbag.ORidBag.size(ORidBag.java:182)
at com.orientechnologies.common.collection.OMultiValue.getSize(OMultiValue.java:80)
at com.orientechnologies.common.collection.OMultiValue.getFirstValue(OMultiValue.java:105)
at com.orientechnologies.orient.core.fetch.OFetchHelper.processRecord(OFetchHelper.java:299)
at com.orientechnologies.orient.core.fetch.OFetchHelper.fetch(OFetchHelper.java:72)
at com.orientechnologies.orient.server.network.protocol.binary.OAbstractCommandResultListener.fetchRecord(OAbstractCommandResultListener.java:54)
at com.orientechnologies.orient.server.network.protocol.binary.OSyncCommandResultListener.result(OSyncCommandResultListener.java:45)
at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.command(ONetworkProtocolBinary.java:1227)
at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.executeRequest(ONetworkProtocolBinary.java:390)
at com.orientechnologies.orient.server.network.protocol.binary.OBinaryNetworkProtocolAbstract.execute(OBinaryNetworkProtocolAbstract.java:222)
at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:71)

**Comment by luigidellaquila** [comment]
mmm.. let me check...

**Comment by luigidellaquila** [comment]
Ok, I reproduced the problem. 
It's another issue, different from the first one, we are on it
