### ISSUE TITLE
"Missing linked class" OSchemaException

### ISSUE THREAD

**Issue by nsuneja** [orientechnologies/orientdb#4292]
I have been running into the above exception with orientdb-2.0.9 jars.
Heres what I am doing:

I have to open/create (on the fly), 2 instances of database, one of them with "memory" protocol and
other one with "plocal" protocol.
I am using the object apis, and have defined the schema classes under a java package.
BOTH THE DATABASES ARE USING THE SAME SCHEMA.
I try to generate the schema in the constructor of my database instance class wrapper, with the following code snippet:

```
private void generateSchema(OObjectDatabaseTx db) {

    // Turn on automatic schema generation, for new schema classes.
    db.setAutomaticSchemaGeneration(true);

    db.getEntityManager().registerEntityClasses
    ("com.maxta.base.statsdb.object.pojos");

    // Synchronize existing schema classes.
    db.getMetadata().getSchema().synchronizeSchema();
}
```

Also, note that even the "plocal" database has to be created on the fly (if it doesn't exist), or otherwise
we open the existing database. "memory" database will obviously be created each time the process starts up. 

Below is the exception stack trace which I am getting. Also note that the exception happens for the 2nd database initialization, which in my case is the "memory" database, when we try to synchronizeSchema(). 

OBSERVATION: I have seen that I don't hit the exception if the "plocal" database (which I instantiate
first, before "memory" db) already exists on the disk, and therefore I don't create it, but just open it.

com.orientechnologies.orient.core.exception.OSchemaException: Missing linked class
    at com.orientechnologies.orient.core.metadata.schema.OClassImpl.createProperty(OClassImpl.java:600) ~[orientdb-core-2.0.9.jar:2.0.9]
    at com.orientechnologies.orient.object.metadata.schema.OSchemaProxyObject.generateLinkProperty(OSchemaProxyObject.java:439) ~[orientdb-object-2.0.9.jar:2.0.9]
    at com.orientechnologies.orient.object.metadata.schema.OSchemaProxyObject.generateSchema(OSchemaProxyObject.java:294) ~[orientdb-object-2.0.9.jar:2.0.9]
    at com.orientechnologies.orient.object.metadata.schema.OSchemaProxyObject.synchronizeSchema(OSchemaProxyObject.java:362) ~[orientdb-object-2.0.9.jar:2.0.9]
    at com.maxta.base.statsdb.object.StatsDBObjectInstance.generateSchema(StatsDBObjectInstance.java:248) [bin/:na]
    at com.maxta.base.statsdb.object.StatsDBObjectInstance.initialize(StatsDBObjectInstance.java:281) [bin/:na]
    at com.maxta.base.statsdb.object.StatsDBObjectInstance.<init>(StatsDBObjectInstance.java:544) [bin/:na]
    at com.maxta.base.service.StatsDBService.<init>(StatsDBService.java:140) [bin/:na]
    at com.maxta.base.service.StatsDBService.main(StatsDBService.java:842) [bin/:na]

**Comment by nsuneja** [comment]
Hi

Did anyone get a change to look at this ?

Two other observations:
1) The issue still persists with 2.0.10 jars.
2) The issue is NOT only limited to creating a "memory" db and a "plocal" db.
     I ran into the same issue with a "plocal:/db1" and "plocal:/db2", when both of these databases are
     using the same schema classes.

It looks like either you guys don't support multiple instances of databases (which share the schema)
at all, or I am using the apis incorrectly.
Please also note that obviously I don't face any issues if I create only one instance of database.

It would be great if someone could take a look at this issue. It's urgent and required for our product release.

Regards
Nishant
