### ISSUE TITLE
Can't create an index when it "exists"

### ISSUE THREAD

**Issue by optimuspaul** [orientechnologies/orientdb#4322]
Hey y'all,
`CREATE INDEX id ON cg_sps_legacy (id) UNIQUE`

produces this:

```
Traceback (most recent call last):
  File "sandbox.py", line 71, in <module>
    indexer.index(sps_legacy)
  File "/Users/pjdecoursey/Projects/cg-develop/projects/cg-graph-query/cgql/processors/orient/sidumper.py", line 111, in index
    self.__setup_class(this_thing)
  File "/Users/pjdecoursey/Projects/cg-develop/projects/cg-graph-query/cgql/processors/orient/sidumper.py", line 243, in __setup_class
    self.__create_or_update_indexes(class_name, index_set, indexes, existing_indexes)
  File "/Users/pjdecoursey/Projects/cg-develop/projects/cg-graph-query/cgql/processors/orient/sidumper.py", line 269, in __create_or_update_indexes
    self.orient.command(query)
  File "/Users/pjdecoursey/Projects/cg-develop/projects/pyorient/pyorient/orient.py", line 244, in command
    .prepare(( QUERY_CMD, ) + args).send().fetch_response()
  File "/Users/pjdecoursey/Projects/cg-develop/projects/pyorient/pyorient/messages/commands.py", line 144, in fetch_response
    super( CommandMessage, self ).fetch_response()
  File "/Users/pjdecoursey/Projects/cg-develop/projects/pyorient/pyorient/messages/base.py", line 216, in fetch_response
    self._decode_all()
  File "/Users/pjdecoursey/Projects/cg-develop/projects/pyorient/pyorient/messages/base.py", line 200, in _decode_all
    self._decode_header()
  File "/Users/pjdecoursey/Projects/cg-develop/projects/pyorient/pyorient/messages/base.py", line 181, in _decode_header
    [ exception_message.decode( 'utf8' ) ]
pyorient.exceptions.PyOrientCommandException: com.orientechnologies.orient.core.index.OIndexException - Index with name id already exists.
```

Which seems like you'd expect that, except for this:

```
{
"name": "cg_sps_legacy",
"superClass": "V",
"alias": null,
"abstract": false,
"strictmode": false,
"clusters": [
14
],
"defaultCluster": 14,
"clusterSelection": "round-robin",
"records": 1,
"properties": [
{
"name": "superchunk_id",
"type": "STRING",
"mandatory": false,
"readonly": false,
"notNull": false,
"min": null,
"max": null,
"regexp": null,
"collate": "default"
},
{
"name": "id",
"type": "STRING",
"mandatory": false,
"readonly": false,
"notNull": false,
"min": null,
"max": null,
"regexp": null,
"collate": "default"
}
],
"indexes": [
{
"name": "superchunk_id",
"type": "UNIQUE",
"fields": [
"superchunk_id"
]
}
]
}
```

The index doesn't exist. Stranger still is that I can create the index in the studio manually, just not via that command. What up?

**Comment by optimuspaul** [comment]
if I change the command to:
```CREATE INDEX cg_sps_legacy.id ON cg_sps_legacy (id) UNIQUE```

it works, I think the bug here is that if I name the index the same as a property and specify only that property the index is somehow not registered correctly. Definitely a bug here, probably not super high priority though.
