### ISSUE TITLE
GC not correcting on subsquent calls after 'OutOfMemoryError: GC overhead limit exceeded'

### ISSUE THREAD

**Issue by TT-Dev1** [orientechnologies/orientdb#4327]
**It seems the Garbage Collector gets in a bad state after reporting 'OutOfMemoryError: GC overhead limit exceeded' so that even small operations also start failing...**

REPRO:
**1.** I have a Person class (vertex) from MSSQL import and it contains a StatusID -- 400k+ records (not small but not that large)
**2.** I'd like to create some edges to a new the Status class -- running in console (server is not running).

> CREATE EDGE _Person_PersonStatus FROM (SELECT FROM Person LET $id1 = nPersonID, $id2 = nPersonStatusID WHERE both('_Person_PersonStatus')[0] is null) TO (SELECT FROM PersonStatus WHERE nPersonStatusID = $id2);

(by the way, let me know if there's a better way to do this - "[0] is null" is to keep from creating duplicate edges)

NOTE: this fails with **'Error: java.lang.OutOfMemoryError: GC overhead limit exceeded'** -- _I thought that I saw a different error on the first run but can't reproduce that_

**(fix) 3.**  I make the following enhancement to limit the creation to 100k edges, 50k edges, 10k edges, 5k edges (after failing)

> CREATE EDGE _Person_PersonStatus FROM (SELECT FROM Person LET $id1 = nPersonID, $id2 = nPersonStatusID WHERE both('_Person_PersonStatus')[0] is null **LIMIT 100000**) TO (SELECT FROM PersonStatus WHERE nPersonStatusID = $id2);

Exception in thread "OrientDB WAL Flush Task (MyDb)" java.lang.OutOfMemoryEr
ror: GC overhead limit exceeded
 Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler i
n thread "OrientDB WAL Flush Task (MyDb)"

Eventually, it can't even create 1000 edges

**observation 4.**  DELETE FROM _Person_PersonStatus also fails

(I'm basically stuck at this point until I stop and restart.)

**observation 5.** I can't even close it.

> orientdb {db=MyDb tx=[148386 entries]}> close
>
> Disconnecting from the database [MyDb]...Exception in thread "OrientDB Write
 Cache Flush Task (MyDb)"
> Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler i
n thread "OrientDB Write Cache Flush Task (MyDb)"
> 
> Error: java.lang.OutOfMemoryError: GC overhead limit exceeded
> Exception in thread "OrientDB WAL Flush Task (MyDb)"
java.lang.OutOfMemoryError: GC overhead limit exceeded
orientdb {db=MyDb tx=[148386 entries]}>

2.1-rc3
I did try increasing the memory to ORIENTDB_SETTINGS=-Xmx1024m but that is just kicking the can down the road.

**Comment by lvca** [comment]
We improved memory usage after 2.1-rc3. Please could you try with last 2.1-SNAPSHOT?

**Comment by TifosiTech** [comment]
Just retested in 2.1-rc4 and it appears, by my quick tests, to be fixed.

THANKS!

I will let you know if I come across any further issues.

**Comment by lvca** [comment]
Ok, reopening it.

**Comment by lvca** [comment]
Does it happen during massive delete? Are you executing it in TX?

**Comment by TT-Dev1** [comment]
Yes, it seems I was too optimistic.

I just did a large delete and killed it again -- no transactions, simple unconnected vertex delete [using console].

(I tried this time with 400k rows.)

Connecting to database [plocal:/d:/.....] with user 'admin'...OK
orientdb {db=QpongoDb}> SELECT COUNT(*) FROM xx

----+------+------
   |@CLASS|COUNT
----+------+------
0   |null  |483721
----+------+------

1 item(s) found. Query executed in 0.018 sec(s).
orientdb {db=QpongoDb}> DELETE VERTEX xx
{db=MyDb} Error on fetching record during browsing. The record has been skipped
com.orientechnologies.orient.core.exception.ODatabaseException: Error on retrieving record #88:407428 (cluster: xx____)
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.executeReadRecord(ODatabaseDocumentTx.java:1741)
        at com.orientechnologies.orient.core.tx.OTransactionOptimistic.loadRecord(OTransactionOptimistic.java:224)
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.load(ODatabaseDocumentTx.java:1543)
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.load(ODatabaseDocumentTx.java:120)
        at com.orientechnologies.orient.core.iterator.OIdentifiableIterator.readCurrentRecord(OIdentifiableIterator.java:287)
        at com.orientechnologies.orient.core.iterator.ORecordIteratorClusters.hasNext(ORecordIteratorClusters.java:159)
        at com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.fetch
FromTarget(OCommandExecutorSQLSelect.java:1367)
        at com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.executeSearch(OCommandExecutorSQLSelect.java:447)
        at com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.execute(OCommandExecutorSQLSelect.java:405)
        at com.orientechnologies.orient.core.sql.OCommandExecutorSQLDelegate.execute(OCommandExecutorSQLDelegate.java:90)
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.executeCommand(OAbstractPaginatedStorage.java:1232)
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.command(OAbstractPaginatedStorage.java:1213)
        at com.orientechnologies.orient.core.sql.query.OSQLQuery.run(OSQLQuery.java:72)
        at com.orientechnologies.orient.core.query.OQueryAbstract.execute(OQuery
Abstract.java:33)
        at com.orientechnologies.orient.graph.sql.OCommandExecutorSQLDeleteVertex$2.call(OCommandExecutorSQLDeleteVertex.java:202)
        at com.orientechnologies.orient.graph.sql.OCommandExecutorSQLDeleteVertex$2.call(OCommandExecutorSQLDeleteVertex.java:197)
        at com.orientechnologies.orient.graph.sql.OGraphCommandExecutorSQLFactory.runInTx(OGraphCommandExecutorSQLFactory.java:130)
        at com.orientechnologies.orient.graph.sql.OCommandExecutorSQLDeleteVertex.execute(OCommandExecutorSQLDeleteVertex.java:197)
        at com.orientechnologies.orient.core.sql.OCommandExecutorSQLDelegate.execute(OCommandExecutorSQLDelegate.java:90)
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginat
edStorage.executeCommand(OAbstractPaginatedStorage.java:1232)
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginat
edStorage.command(OAbstractPaginatedStorage.java:1213)
        at com.orientechnologies.orient.core.command.OCommandRequestTextAbstract
.execute(OCommandRequestTextAbstract.java:63)
        at com.orientechnologies.orient.console.OConsoleDatabaseApp.sqlCommand(O
ConsoleDatabaseApp.java:2396)
        at com.orientechnologies.orient.console.OConsoleDatabaseApp.delete(OCons
oleDatabaseApp.java:547)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at com.orientechnologies.common.console.OConsoleApplication.execute(OCon
soleApplication.java:382)
        at com.orientechnologies.common.console.OConsoleApplication.executeComma
nds(OConsoleApplication.java:247)
        at com.orientechnologies.common.console.OConsoleApplication.run(OConsole
Application.java:136)
        at com.orientechnologies.orient.graph.console.OGremlinConsole.main(OGrem
linConsole.java:62)
Caused by: java.lang.OutOfMemoryError: GC overhead limit exceeded
        at com.orientechnologies.orient.core.compression.impl.ONothingCompressio
n.uncompress(ONothingCompression.java:48)
        at com.orientechnologies.orient.core.storage.impl.local.paginated.OPagin
atedCluster.readRecord(OPaginatedCluster.java:574)
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginat
edStorage.doReadRecord(OAbstractPaginatedStorage.java:1757)
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginat
edStorage.readRecord(OAbstractPaginatedStorage.java:1504)
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginat
edStorage.readRecord(OAbstractPaginatedStorage.java:723)
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx$Sim
pleRecordReader.readRecord(ODatabaseDocumentTx.java:3074)
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.executeReadRecord(ODatabaseDocumentTx.java:1708)
        at com.orientechnologies.orient.core.tx.OTransactionOptimistic.loadRecord(OTransactionOptimistic.java:224)
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.load(ODatabaseDocumentTx.java:1543)
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.loa
d(ODatabaseDocumentTx.java:120)
        at com.orientechnologies.orient.core.iterator.OIdentifiableIterator.read
CurrentRecord(OIdentifiableIterator.java:287)
        at com.orientechnologies.orient.core.iterator.ORecordIteratorClusters.hasNext(ORecordIteratorClusters.java:159)
        at com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.fetch
FromTarget(OCommandExecutorSQLSelect.java:1367)
        at com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.executeSearch(OCommandExecutorSQLSelect.java:447)
        at com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.execute(OCommandExecutorSQLSelect.java:405)
        at com.orientechnologies.orient.core.sql.OCommandExecutorSQLDelegate.exe
cute(OCommandExecutorSQLDelegate.java:90)
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.executeCommand(OAbstractPaginatedStorage.java:1232)
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.command(OAbstractPaginatedStorage.java:1213)
        at com.orientechnologies.orient.core.sql.query.OSQLQuery.run(OSQLQuery.java:72)
        at com.orientechnologies.orient.core.query.OQueryAbstract.execute(OQueryAbstract.java:33)
        at com.orientechnologies.orient.graph.sql.OCommandExecutorSQLDeleteVertex$2.call(OCommandExecutorSQLDeleteVertex.java:202)
        at com.orientechnologies.orient.graph.sql.OCommandExecutorSQLDeleteVertex$2.call(OCommandExecutorSQLDeleteVertex.java:197)
        at com.orientechnologies.orient.graph.sql.OGraphCommandExecutorSQLFactory.runInTx(OGraphCommandExecutorSQLFactory.java:130)
        at com.orientechnologies.orient.graph.sql.OCommandExecutorSQLDeleteVertex.execute(OCommandExecutorSQLDeleteVertex.java:197)
        at com.orientechnologies.orient.core.sql.OCommandExecutorSQLDelegate.execute(OCommandExecutorSQLDelegate.java:90)
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.executeCommand(OAbstractPaginatedStorage.java:1232)
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.command(OAbstractPaginatedStorage.java:1213)
        at com.orientechnologies.orient.core.command.OCommandRequestTextAbstract.execute(OCommandRequestTextAbstract.java:63)
        at com.orientechnologies.orient.console.OConsoleDatabaseApp.sqlCommand(OConsoleDatabaseApp.java:2396)
        at com.orientechnologies.orient.console.OConsoleDatabaseApp.delete(OConsoleDatabaseApp.java:547)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)

Error: java.lang.OutOfMemoryError: GC overhead limit exceeded

orientdb {db=QpongoDb tx=[407440 entries]}>

**Comment by lvca** [comment]
Try these 2 commands that don't need RAM at all:
```sql
delete from V unsafe
delete from E unsafe
```

**Comment by TT-Dev1** [comment]
Yes, unsafe works.

D:\OrientDB\bin>console

OrientDB console v.2.1-rc4 (build UNKNOWN@r${buildNumber}; 2015-06-17 14:47:11+0
000) www.orientdb.com
Type 'help' to display all the supported commands.
Installing extensions for GREMLIN language v.2.6.0

orientdb> connect plocal:/d:/OrientDB/databases/MyDb admin admin;

Connecting to database [plocal:/d:/OrientDB/databases/MyDb] with user 'admin'...OK
orientdb {db=MyDb}> DELETE VERTEX xx LIMIT 100

Delete record(s) '100' in 0.313000 sec(s).

orientdb {db=MyDb}> delete from xx **unsafe**

**Delete record(s) '483621' in 66.600998 sec(s).**

**Comment by lvca** [comment]
That's because delete vertex is transactional and require RAM with many records.

**Comment by TT-Dev1** [comment]
I understand, that's why the bug was written for a 'CREATE' case.  If the CREATE but appears again then I should reopen, right?

And on a side note, is there a way that you can cache to disk or do something so that this doesn't CRASH completely (and corrupt the GC so that the database is essentially locked)?

NOTE: MSSQL does this same delete in a few seconds -- I can see there would be a difference if the data was linked to a graph but in this case it is free and unconnected.

**Comment by lvca** [comment]
We know OrientDB is not super optimized for delete, we have much room on improvement here.
