### ISSUE TITLE
File flush was abnormally terminated

### ISSUE THREAD

**Issue by jamieb22** [orientechnologies/orientdb#4332]
2015-06-04 07:17:43 t.c.s.a.np [ERROR] error occured writing stat to database
com.orientechnologies.common.exception.OException: File flush was abnormally terminated
    at com.orientechnologies.orient.core.index.hashindex.local.cache.OWOWCache.flush(OWOWCache.java:524) ~[orientdb-core-2.0.10.jar:2.0.10]
    at com.orientechnologies.orient.core.index.hashindex.local.cache.OWOWCache.flush(OWOWCache.java:530) ~[orientdb-core-2.0.10.jar:2.0.10]
    at com.orientechnologies.orient.core.index.hashindex.local.cache.OReadWriteDiskCache.flushBuffer(OReadWriteDiskCache.java:549) ~[orientdb-core-2.0.10.jar:2.0.10]
    at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.makeFullCheckpoint(OAbstractPaginatedStorage.java:1335) ~[orientdb-core-2.0.10.jar:2.0.10]
    at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.synch(OAbstractPaginatedStorage.java:1001) ~[orientdb-core-2.0.10.jar:2.0.10]
    at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.checkLowDiskSpaceAndFullCheckpointRequests(OAbstractPaginatedStorage.java:2367) ~[orientdb-core-2.0.10.jar:2.0.10]
    at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.commit(OAbstractPaginatedStorage.java:888) ~[orientdb-core-2.0.10.jar:2.0.10]
    at com.orientechnologies.orient.core.tx.OTransactionOptimistic.doCommit(OTransactionOptimistic.java:488) ~[orientdb-core-2.0.10.jar:2.0.10]
    at com.orientechnologies.orient.core.tx.OTransactionOptimistic.commit(OTransactionOptimistic.java:147) ~[orientdb-core-2.0.10.jar:2.0.10]
    at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.commit(ODatabaseDocumentTx.java:2427) ~[orientdb-core-2.0.10.jar:2.0.10]
    at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.commit(ODatabaseDocumentTx.java:2397) ~[orientdb-core-2.0.10.jar:2.0.10]
    at com.tinkerpop.blueprints.impls.orient.OrientBaseGraph.shutdown(OrientBaseGraph.java:1143) ~[orientdb-graphdb-2.0.10.jar:2.0.10]
    at com.tinkerpop.blueprints.impls.orient.OrientBaseGraph.shutdown(OrientBaseGraph.java:1129) ~[orientdb-graphdb-2.0.10.jar:2.0.10]
    at com.tinkerpop.blueprints.impls.orient.OrientBaseGraph.shutdown(OrientBaseGraph.java:1122) ~[orientdb-graphdb-2.0.10.jar:2.0.10]
...
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471) [na:1.7.0_71]
    at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:304) [na:1.7.0_71]
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:178) [na:1.7.0_71]
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [na:1.7.0_71]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [na:1.7.0_71]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [na:1.7.0_71]
    at java.lang.Thread.run(Thread.java:745) [na:1.7.0_71]
Caused by: java.util.concurrent.ExecutionException: java.io.IOException: Stream Closed
    at java.util.concurrent.FutureTask.report(FutureTask.java:122) [na:1.7.0_71]
    at java.util.concurrent.FutureTask.get(FutureTask.java:188) [na:1.7.0_71]
    at com.orientechnologies.orient.core.index.hashindex.local.cache.OWOWCache.flush(OWOWCache.java:519) ~[orientdb-core-2.0.10.jar:2.0.10]
    ... 25 common frames omitted
Caused by: java.io.IOException: Stream Closed
    at java.io.RandomAccessFile.length(Native Method) ~[na:1.7.0_71]
    at com.orientechnologies.orient.core.storage.fs.OFileClassic.write(OFileClassic.java:213) ~[orientdb-core-2.0.10.jar:2.0.10]
    at com.orientechnologies.orient.core.index.hashindex.local.cache.OWOWCache.flushPage(OWOWCache.java:1024) ~[orientdb-core-2.0.10.jar:2.0.10]
    at com.orientechnologies.orient.core.index.hashindex.local.cache.OWOWCache.access$2000(OWOWCache.java:64) ~[orientdb-core-2.0.10.jar:2.0.10]
    at com.orientechnologies.orient.core.index.hashindex.local.cache.OWOWCache$FileFlushTask.call(OWOWCache.java:1326) ~[orientdb-core-2.0.10.jar:2.0.10]
    at com.orientechnologies.orient.core.index.hashindex.local.cache.OWOWCache$FileFlushTask.call(OWOWCache.java:1294) ~[orientdb-core-2.0.10.jar:2.0.10]
    at java.util.concurrent.FutureTask.run(FutureTask.java:262) [na:1.7.0_71]
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:178) [na:1.7.0_71]
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:292) [na:1.7.0_71]
    ... 3 common frames omitted

**Comment by laa** [comment]
Moved to 2.2 GA will fix it once we gather enough data.

**Comment by laa** [comment]
Fixed in RC6 version which will be released today.
