### ISSUE TITLE
pyorient doesn't work with 2.1

### ISSUE THREAD

**Issue by optimuspaul** [orientechnologies/orientdb#4334]
Can't access orientDB with pyorient when db is 2.1-rc3
```
Traceback (most recent call last):
  File "/Users/pjdecoursey/Projects/cg-develop/projects/cg-graph-query/tests/processors/orient/test_setup.py", line 49, in setUp
    indexer.connect_to_orient(ORIENT_HOST, ORIENT_DB, ORIENT_USER, ORIENT_PASS)
  File "/Users/pjdecoursey/Projects/cg-develop/projects/cg-graph-query/cgql/processors/orient/__init__.py", line 38, in connect_to_orient
    self.session_id = client.connect(username, password)
  File "/Users/pjdecoursey/Projects/cg-develop/projects/pyorient/pyorient/orient.py", line 209, in connect
    return self.get_message("ConnectMessage") \
  File "/Users/pjdecoursey/Projects/cg-develop/projects/pyorient/pyorient/orient.py", line 346, in get_message
    return _Message(self._connection)\
  File "/Users/pjdecoursey/Projects/cg-develop/projects/pyorient/pyorient/messages/connection.py", line 18, in __init__
    super( ConnectMessage, self ).__init__(_orient_socket)
  File "/Users/pjdecoursey/Projects/cg-develop/projects/pyorient/pyorient/messages/base.py", line 40, in __init__
    sock.get_connection()
  File "/Users/pjdecoursey/Projects/cg-develop/projects/pyorient/pyorient/orient.py", line 40, in get_connection
    self.connect()
  File "/Users/pjdecoursey/Projects/cg-develop/projects/pyorient/pyorient/orient.py", line 63, in connect
    " is not supported yet by this client.", [])
pyorient.exceptions.PyOrientWrongProtocolVersionException: Protocol version 30 is not supported yet by this client.
```

**Comment by optimuspaul** [comment]
https://github.com/mogui/pyorient/issues/74

**Comment by lvca** [comment]
Did you close it because is invalid?

**Comment by optimuspaul** [comment]
Seemed better to log the issue with the project it relates to.
