### ISSUE TITLE
creating edges that involve different shards introduces "OTransactionException"

### ISSUE THREAD

**Issue by clarkpeng** [orientechnologies/orientdb#4338]
Hi all,

I'm having issue while using OrientVertex.addEdge() API.
My orientdb version is community 2.0.10 and it runs in distributed mode with tcp-ip join as below.

```
multicast enabled="false"
tcp-ip enabled="true"
```

The distributed-config.json has below configurations.

```
"clusters":{
...
"vertex1_server1":{ "servers":["server1"]}
"edge1_server1"  :{ "servers":["server1"]}
"vertex2_server2":{ "servers":["server2"]}
...
}
```

That means:
1. cluster "vertex1_server1" and "edge1_server1" will only reside in server1
2. cluster "vertex2_server2"  will only reside in server2

Now when I wish to add edge1 from cluster "vertex1_server1" to cluster "vertex2_server2", it always throws below exception.

```
Add v1
Add v2
Add e1
[error] (run-main-0) com.orientechnologies.orient.core.exception.OTransactionException: Error on committing distributed transaction
com.orientechnologies.orient.core.exception.OTransactionException: Error on committing distributed transaction
        at com.orientechnologies.orient.server.distributed.ODistributedStorage.commit(ODistributedStorage.java:953)
        at com.orientechnologies.orient.core.tx.OTransactionOptimistic.doCommit(OTransactionOptimistic.java:488)
        at com.orientechnologies.orient.core.tx.OTransactionOptimistic.commit(OTransactionOptimistic.java:147)
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.commit(ODatabaseDocumentTx.java:2427)
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.commit(ODatabaseDocumentTx.java:2397)
        at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.commit(ONetworkProtocolBinary.java:1088)
        at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.executeRequest(ONetworkProtocolBinary.java:390)
        at com.orientechnologies.orient.server.network.protocol.binary.OBinaryNetworkProtocolAbstract.execute(OBinaryNetworkProtocolAbstract.java:217)
        at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:69)
Caused by: com.orientechnologies.orient.core.exception.ODatabaseException: Error on retrieving record #11:0 (cluster: vertex1_prism-orient-db-01)
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.executeReadRecord(ODatabaseDocumentTx.java:1634)
        at com.orientechnologies.orient.core.tx.OTransactionOptimistic.loadRecord(OTransactionOptimistic.java:226)
        at com.orientechnologies.orient.core.tx.OTransactionOptimistic.loadRecord(OTransactionOptimistic.java:237)
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.load(ODatabaseDocumentTx.java:1446)
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.load(ODatabaseDocumentTx.java:118)
        at com.orientechnologies.orient.core.record.impl.ODocument.field(ODocument.java:890)
        at com.orientechnologies.orient.server.distributed.task.OTxTask.execute(OTxTask.java:101)
        at com.orientechnologies.orient.server.hazelcast.OHazelcastPlugin.executeOnLocalNode(OHazelcastPlugin.java:761)
        at com.orientechnologies.orient.server.hazelcast.ODistributedWorker.onMessage(ODistributedWorker.java:300)
        at com.orientechnologies.orient.server.hazelcast.ODistributedWorker.run(ODistributedWorker.java:121)
Caused by: com.orientechnologies.orient.server.distributed.ODistributedException: Error on executing distributed request (id=43 from=prism-orient-db-02 task=record_read userName=admin) against database 'testdb.[vertex1_prism-orient-db-01]' to nodes [prism-orient-db-01]
        at com.orientechnologies.orient.server.hazelcast.OHazelcastDistributedDatabase.send2Nodes(OHazelcastDistributedDatabase.java:195)
        at com.orientechnologies.orient.server.hazelcast.OHazelcastPlugin.sendRequest(OHazelcastPlugin.java:354)
        at com.orientechnologies.orient.server.distributed.ODistributedStorage.readRecord(ODistributedStorage.java:554)
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.executeReadRecord(ODatabaseDocumentTx.java:1601)
        at com.orientechnologies.orient.core.tx.OTransactionOptimistic.loadRecord(OTransactionOptimistic.java:226)
        at com.orientechnologies.orient.core.tx.OTransactionOptimistic.loadRecord(OTransactionOptimistic.java:237)
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.load(ODatabaseDocumentTx.java:1446)
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.load(ODatabaseDocumentTx.java:118)
        at com.orientechnologies.orient.core.record.impl.ODocument.field(ODocument.java:890)
        at com.orientechnologies.orient.server.distributed.task.OTxTask.execute(OTxTask.java:101)
        at com.orientechnologies.orient.server.hazelcast.OHazelcastPlugin.executeOnLocalNode(OHazelcastPlugin.java:761)
        at com.orientechnologies.orient.server.hazelcast.ODistributedWorker.onMessage(ODistributedWorker.java:300)
        at com.orientechnologies.orient.server.hazelcast.ODistributedWorker.run(ODistributedWorker.java:121)
Caused by: com.orientechnologies.orient.server.distributed.ODistributedException: Quorum 1 not reached for request (id=43 from=prism-orient-db-02 task=record_read userName=admin). Elapsed=3025ms No server in conflict. Received: {prism-orient-db-01=waiting-for-response}
        at com.orientechnologies.orient.server.distributed.ODistributedResponseManager.manageConflicts(ODistributedResponseManager.java:585)
        at com.orientechnologies.orient.server.distributed.ODistributedResponseManager.getFinalResponse(ODistributedResponseManager.java:349)
        at com.orientechnologies.orient.server.hazelcast.OHazelcastDistributedDatabase.waitForResponse(OHazelcastDistributedDatabase.java:365)
        at com.orientechnologies.orient.server.hazelcast.OHazelcastDistributedDatabase.send2Nodes(OHazelcastDistributedDatabase.java:192)
        at com.orientechnologies.orient.server.hazelcast.OHazelcastPlugin.sendRequest(OHazelcastPlugin.java:354)
        at com.orientechnologies.orient.server.distributed.ODistributedStorage.readRecord(ODistributedStorage.java:554)
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.executeReadRecord(ODatabaseDocumentTx.java:1601)
        at com.orientechnologies.orient.core.tx.OTransactionOptimistic.loadRecord(OTransactionOptimistic.java:226)
        at com.orientechnologies.orient.core.tx.OTransactionOptimistic.loadRecord(OTransactionOptimistic.java:237)
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.load(ODatabaseDocumentTx.java:1446)
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.load(ODatabaseDocumentTx.java:118)
        at com.orientechnologies.orient.core.record.impl.ODocument.field(ODocument.java:890)
        at com.orientechnologies.orient.server.distributed.task.OTxTask.execute(OTxTask.java:101)
        at com.orientechnologies.orient.server.hazelcast.OHazelcastPlugin.executeOnLocalNode(OHazelcastPlugin.java:761)
        at com.orientechnologies.orient.server.hazelcast.ODistributedWorker.onMessage(ODistributedWorker.java:300)
        at com.orientechnologies.orient.server.hazelcast.ODistributedWorker.run(ODistributedWorker.java:121)
```

If I change distributed-config.json to have all clusters on all servers, then the program executes as expected.

```
"clusters":{
...
"vertex1_server1":{ "servers":["server1", "server2", "<NEW_NODE>"]}
"edge1_server1"  :{ "servers":["server1", "server2", "<NEW_NODE>"]}
"vertex2_server2":{ "servers":["server1", "server2", "<NEW_NODE>"]}
...
}
```

I already raised a question in https://groups.google.com/forum/#!msg/orient-database/E6sxiLYJ9og/q4VGB9_F0SYJ, and Luigi suggests to create a new issue.

It seems to me that while edge1 is going to be created, server1 firstly lock vertex1 and ask server2 to create edge1. When server2 wishes to update vertex2 for edge1, it asks for the lock of vertex1 and deadlock happens so the procedure ends up in timeout.

Actually i kept all the server logs and configurations, but I have no idea how to upload them. In case it's needed, I'll paste the logs in this thread.

The simple test case is as below.

```
import com.tinkerpop.blueprints.impls.orient.OrientGraphFactory

import scala.collection.JavaConverters._
import scala.collection.JavaConversions._

object OrientdbTestdbImporter {

  val uris = Array("remote:server1/testdb")
  val dbs = Array(new OrientGraphFactory(uris(0), "admin", "admin").setupPool(100, 200))

  def main(args: Array[String]) {

    val graphDB = dbs(0).getTx()

    val v1 = graphDB.addVertex("class:Vertex1,cluster:vertex1_server1", Map("pid" -> "v1").asJava.asInstanceOf[java.util.Map[String,Object]])
    graphDB.commit()
    println("Add v1")

    val v2 = graphDB.addVertex("class:Vertex2,cluster:vertex2_server2", Map("pid" -> "v2").asJava.asInstanceOf[java.util.Map[String,Object]])
    graphDB.commit()
    println("Add v2")

    val e1 = v1.addEdge("Edge1", v2, "Edge1", "edge1_server1", Map().asJava.asInstanceOf[java.util.Map[String,Object]])    println("Add e1")
    graphDB.commit()

    println("OK")

    dbs.foreach( _.close())
  }
}
```

Thanks,
Clark

**Comment by lvca** [comment]
Clark, we have a similar test case in TestSharding.java. Please could you see if your case si so much different?

**Comment by clarkpeng** [comment]
Hi Ivca,

Thanks for your suggestion, but my use case is different from TestSharding.java.
I mainly focus on addEdge() for "regular edge" (not light-weight) in TestSharding.java and my test case for the difference.

In TestSharding.java, regular edges (label: "Buy") are added from different client clusters to "class:Product", where the cluster of "class:Product" should be on the same server as the client cluster.
For example, cluster:client_usa --cluster:buy_usa--> cluster:product_usa, and the involved three clusters are all on server "usa".

But in my test case, I try to addEdge() as below:
cluster:vertex1_server1 --cluster:edge1_server1--> cluster:vertex2_server2, where vertex1_server1 and edge1_server1 are "only" on "server1" and vertex2_server2 is "only" on "server2".
Therefore, the involved three clusters are not on the same server.

I'm not sure if this kind of use case contradicts to your design. If it contradicts, then would you please give me some suggestions on how to deal with the vertex that can grow unlimited that we wish to separate them only on a group of servers. (That means we don't want to duplicate them on other servers that have vertices and edges with them.)

Thanks,
Clark

**Comment by lvca** [comment]
@clarkpeng Did you have the chance to try with 2.1.2?
