### ISSUE TITLE
Error creation of sbtree with namecollections_14

### ISSUE THREAD

**Issue by jamieb22** [orientechnologies/orientdb#4339]
The following error occurs when in serting a record in the Orient 2.0.10 

com.orientechnologies.orient.core.index.sbtree.local.OSBTreeException: Error creation of sbtree with namecollections_14
	at com.orientechnologies.orient.core.index.sbtreebonsai.local.OSBTreeBonsaiLocal.create(OSBTreeBonsaiLocal.java:125) ~[orientdb-core-2.0.10.jar:2.0.10]
	at com.orientechnologies.orient.core.db.record.ridbag.sbtree.OSBTreeCollectionManagerShared.createTree(OSBTreeCollectionManagerShared.java:76) ~[orientdb-core-2.0.10.jar:2.0.10]
	at com.orientechnologies.orient.core.db.record.ridbag.sbtree.OSBTreeCollectionManagerShared.createTree(OSBTreeCollectionManagerShared.java:40) ~[orientdb-core-2.0.10.jar:2.0.10]
	at com.orientechnologies.orient.core.db.record.ridbag.sbtree.OSBTreeCollectionManagerAbstract.createSBTree(OSBTreeCollectionManagerAbstract.java:83) ~[orientdb-core-2.0.10.jar:2.0.10]
	at com.orientechnologies.orient.core.db.record.ridbag.sbtree.OSBTreeCollectionManagerShared.createSBTree(OSBTreeCollectionManagerShared.java:61) ~[orientdb-core-2.0.10.jar:2.0.10]
	at com.orientechnologies.orient.core.db.record.ridbag.sbtree.OSBTreeCollectionManagerProxy.createSBTree(OSBTreeCollectionManagerProxy.java:46) ~[orientdb-core-2.0.10.jar:2.0.10]
	at com.orientechnologies.orient.core.db.record.ridbag.sbtree.OSBTreeRidBag.serialize(OSBTreeRidBag.java:786) ~[orientdb-core-2.0.10.jar:2.0.10]
	at com.orientechnologies.orient.core.db.record.ridbag.ORidBag.toStream(ORidBag.java:264) ~[orientdb-core-2.0.10.jar:2.0.10]
	at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinaryV0.writeSingleValue(ORecordSerializerBinaryV0.java:581) ~[orientdb-core-2.0.10.jar:2.0.10]
	at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinaryV0.serialize(ORecordSerializerBinaryV0.java:261) ~[orientdb-core-2.0.10.jar:2.0.10]
	at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinary.toStream(ORecordSerializerBinary.java:104) ~[orientdb-core-2.0.10.jar:2.0.10]
	at com.orientechnologies.orient.core.record.impl.ODocument.toStream(ODocument.java:2105) ~[orientdb-core-2.0.10.jar:2.0.10]
	at com.orientechnologies.orient.core.record.impl.ODocument.toStream(ODocument.java:714) ~[orientdb-core-2.0.10.jar:2.0.10]
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.executeSaveRecord(ODatabaseDocumentTx.java:1687) ~[orientdb-core-2.0.10.jar:2.0.10]
	at com.orientechnologies.orient.core.tx.OTransactionOptimistic.addRecord(OTransactionOptimistic.java:312) ~[orientdb-core-2.0.10.jar:2.0.10]
	at com.orientechnologies.orient.core.tx.OTransactionOptimistic.saveRecord(OTransactionOptimistic.java:253) ~[orientdb-core-2.0.10.jar:2.0.10]
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.save(ODatabaseDocumentTx.java:2306) ~[orientdb-core-2.0.10.jar:2.0.10]
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.save(ODatabaseDocumentTx.java:118) ~[orientdb-core-2.0.10.jar:2.0.10]
	at com.orientechnologies.orient.core.record.impl.ODocument.save(ODocument.java:1734) ~[orientdb-core-2.0.10.jar:2.0.10]
	at com.orientechnologies.orient.core.record.impl.ODocument.save(ODocument.java:1725) ~[orientdb-core-2.0.10.jar:2.0.10]
	at com.orientechnologies.orient.core.record.impl.ODocument.save(ODocument.java:98) ~[orientdb-core-2.0.10.jar:2.0.10]
	at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinaryV0.recursiveLinkSave(ORecordSerializerBinaryV0.java:674) ~[orientdb-core-2.0.10.jar:2.0.10]
	at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinaryV0.writeOptimizedLink(ORecordSerializerBinaryV0.java:688) ~[orientdb-core-2.0.10.jar:2.0.10]
	at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinaryV0.writeSingleValue(ORecordSerializerBinaryV0.java:572) ~[orientdb-core-2.0.10.jar:2.0.10]
	at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinaryV0.serialize(ORecordSerializerBinaryV0.java:261) ~[orientdb-core-2.0.10.jar:2.0.10]
	at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinary.toStream(ORecordSerializerBinary.java:104) ~[orientdb-core-2.0.10.jar:2.0.10]
	at com.orientechnologies.orient.core.record.impl.ODocument.toStream(ODocument.java:2105) ~[orientdb-core-2.0.10.jar:2.0.10]
	at com.orientechnologies.orient.core.record.impl.ODocument.toStream(ODocument.java:714) ~[orientdb-core-2.0.10.jar:2.0.10]
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.commitEntry(OAbstractPaginatedStorage.java:1939) ~[orientdb-core-2.0.10.jar:2.0.10]
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.commit(OAbstractPaginatedStorage.java:922) ~[orientdb-core-2.0.10.jar:2.0.10]
	at com.orientechnologies.orient.core.tx.OTransactionOptimistic.doCommit(OTransactionOptimistic.java:488) ~[orientdb-core-2.0.10.jar:2.0.10]
	at com.orientechnologies.orient.core.tx.OTransactionOptimistic.commit(OTransactionOptimistic.java:147) ~[orientdb-core-2.0.10.jar:2.0.10]
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.commit(ODatabaseDocumentTx.java:2427) ~[orientdb-core-2.0.10.jar:2.0.10]
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.commit(ODatabaseDocumentTx.java:2397) ~[orientdb-core-2.0.10.jar:2.0.10]
	at com.tinkerpop.blueprints.impls.orient.OrientTransactionalGraph.commit(OrientTransactionalGraph.java:162) ~[orientdb-graphdb-2.0.10.jar:2.0.10]
	at ...
..
	at java.util.concurrent.FutureTask.run(FutureTask.java:262) [na:1.7.0_71]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [na:1.7.0_71]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [na:1.7.0_71]
	at java.lang.Thread.run(Thread.java:745) [na:1.7.0_71]
Caused by: com.orientechnologies.orient.core.storage.impl.local.paginated.atomicoperations.ONestedRollbackException: Atomic operation was rolled back by internal component
	at com.orientechnologies.orient.core.storage.impl.local.paginated.atomicoperations.OAtomicOperationsManager.endAtomicOperation(OAtomicOperationsManager.java:108) ~[orientdb-core-2.0.10.jar:2.0.10]
	at com.orientechnologies.orient.core.storage.impl.local.paginated.base.ODurableComponent.endAtomicOperation(ODurableComponent.java:86) ~[orientdb-core-2.0.10.jar:2.0.10]
	at com.orientechnologies.orient.core.index.sbtreebonsai.local.OSBTreeBonsaiLocal.endAtomicOperation(OSBTreeBonsaiLocal.java:624) ~[orientdb-core-2.0.10.jar:2.0.10]
	at com.orientechnologies.orient.core.index.sbtreebonsai.local.OSBTreeBonsaiLocal.create(OSBTreeBonsaiLocal.java:119) ~[orientdb-core-2.0.10.jar:2.0.10]
	... 59 common frames omitted

**Comment by laa** [comment]
Fix for this issue will be backported tomorrow.

**Comment by lvca** [comment]
What's the status of this issue?

**Comment by laa** [comment]
It will be fixed after backport

**Comment by laa** [comment]
Fixed by backporting of ridbag issue from develop to 2.0.x
