### ISSUE TITLE
Atomic operation was rolled back by internal component

### ISSUE THREAD

**Issue by jamieb22** [orientechnologies/orientdb#4340]
Orient 2.0.10 is full of errors. 

com.orientechnologies.orient.core.storage.impl.local.paginated.atomicoperations.ONestedRollbackException: Atomic operation was rolled back by internal component
	at com.orientechnologies.orient.core.storage.impl.local.paginated.atomicoperations.OAtomicOperationsManager.endAtomicOperation(OAtomicOperationsManager.java:108) ~[orientdb-core-2.0.10.jar:2.0.10]
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.endStorageTx(OAbstractPaginatedStorage.java:1436) ~[orientdb-core-2.0.10.jar:2.0.10]
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.commit(OAbstractPaginatedStorage.java:929) ~[orientdb-core-2.0.10.jar:2.0.10]
	at com.orientechnologies.orient.core.tx.OTransactionOptimistic.doCommit(OTransactionOptimistic.java:488) ~[orientdb-core-2.0.10.jar:2.0.10]
	at com.orientechnologies.orient.core.tx.OTransactionOptimistic.commit(OTransactionOptimistic.java:147) ~[orientdb-core-2.0.10.jar:2.0.10]
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.commit(ODatabaseDocumentTx.java:2427) ~[orientdb-core-2.0.10.jar:2.0.10]
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.commit(ODatabaseDocumentTx.java:2397) ~[orientdb-core-2.0.10.jar:2.0.10]
	at com.tinkerpop.blueprints.impls.orient.OrientTransactionalGraph.commit(OrientTransactionalGraph.java:162) ~[orientdb-graphdb-2.0.10.jar:2.0.10]
	at co..
	at java.util.concurrent.FutureTask.run(FutureTask.java:262) [na:1.7.0_71]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [na:1.7.0_71]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [na:1.7.0_71]
	at java.lang.Thread.run(Thread.java:745) [na:1.7.0_71]

**Comment by laa** [comment]
HI, I will backport all issues fixed in 2.1 related to multithreading from tommorow, so this issue also will be fixed.

**Comment by lvca** [comment]
@laa What's the status of this issue?

**Comment by laa** [comment]
we are waiting for reply

**Comment by laa** [comment]
fixed by backporting of fix of ridbag issue from develop to 2.0.x

**Comment by masimakopoulos** [comment]
I am experiencing the same issue using version 2.0.12. Shouldn't this be fixed in this version?

**Comment by laa** [comment]
Hi
It is fixed in 2.1 version .
