### ISSUE TITLE
Exception raised during Importing database with index name not found 

### ISSUE THREAD

**Issue by atboo** [orientechnologies/orientdb#4347]
```
Importing database database /home/xbx_nodes20150609.json.gz -merge=false -preserveClusterIDs=true -rebuildIndexes=false...
Started import of database 'remote:121.40.157.131/xbx_nodes' from /home/xbx_nodes20150609.json.gz...
Non merge mode (-merge=false): removing all default non security classes
Removed 0 classes.
Importing database info...OK
Importing clusters...
- Creating cluster 'internal'...OK, assigned id=0
- Creating cluster 'default'...OK, assigned id=3
- Creating cluster 'orole'...OK, assigned id=4
- Creating cluster 'ouser'...OK, assigned id=5
- Creating cluster 'ofunction'...OK, assigned id=6
- Creating cluster 'oschedule'...OK, assigned id=7
- Creating cluster 'orids'...OK, assigned id=8
- Creating cluster 'v'...OK, assigned id=9
- Creating cluster 'e'...OK, assigned id=10
- Creating cluster '_studio'...OK, assigned id=11
- Creating cluster 'contact'...OK, assigned id=13
- Creating cluster 'bm_release'...OK, assigned id=14
- Creating cluster 'bm_temp'...OK, assigned id=15
- Creating cluster 'comment'...OK, assigned id=16
- Creating cluster 'knows'...OK, assigned id=17
- Creating cluster 'like_benchmark'...OK, assigned id=18
- Creating cluster 'like_comment'...OK, assigned id=19
- Creating cluster 'pub'...OK, assigned id=20
- Creating cluster 'hate_benchmark'...OK, assigned id=21
- Creating cluster 'user'...OK, assigned id=25
Rebuilding indexes of truncated clusters ...Error on database import happened just before line 0, column 867
com.orientechnologies.orient.core.exception.OCommandExecutionException: Index 'benchmark.phone' not found
        at com.orientechnologies.orient.core.sql.OCommandExecutorSQLRebuildIndex.execute(OCommandExecutorSQLRebuildIndex.java:89)
        at com.orientechnologies.orient.core.sql.OCommandExecutorSQLDelegate.execute(OCommandExecutorSQLDelegate.java:64)
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.executeCommand(OAbstractPaginatedStorage.java:1194)
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.command(OAbstractPaginatedStorage.java:1183)
        at com.orientechnologies.orient.core.command.OCommandRequestTextAbstract.execute(OCommandRequestTextAbstract.java:63)
        at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.command(ONetworkProtocolBinary.java:1179)
        at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.executeRequest(ONetworkProtocolBinary.java:386)
        at com.orientechnologies.orient.server.network.protocol.binary.OBinaryNetworkProtocolAbstract.execute(OBinaryNetworkProtocolAbstract.java:217)
        at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:69)

Error: com.orientechnologies.orient.core.db.tool.ODatabaseExportException: Error on importing database 'xbx_nodes' from file: /home/xbx_nodes20150609.json.gz

Error: com.orientechnologies.orient.core.exception.OCommandExecutionException: Index 'benchmark.phone' not found
```

**Comment by atboo** [comment]
Can it continue and ignore the exception when exception happens?

**Comment by StarpTech** [comment]
Transaction are atomic either all occur, or nothing occurs but I see you error. I had the same issue but with an error about "NumberFormatException" https://github.com/orientechnologies/orientdb/issues/4277 This is really annoying. I hope the importer will be improved in the next releases.

**Comment by lvca** [comment]
@atboo any chance to have the export so we can see what's happening? If yes, please send it to support - at - orientdb.com specifying this issue id.

**Comment by lvca** [comment]
Closed because no answer after a while. In case please comment or reopen this.
