### ISSUE TITLE
2.1-rc4 NPE Error on retrieving record

### ISSUE THREAD

**Issue by valenpo** [orientechnologies/orientdb#4385]
Hello, we have some problems of reading records from database. 
It is opened and closed fine. 

We cant provide access to database here, but @laa has a link for download. 

```java
package com.stimulus.archiva.database;

import com.google.common.collect.HashMultiset;
import com.google.common.collect.Multiset;
import com.orientechnologies.orient.core.record.impl.ODocumentInternal;
import com.tinkerpop.blueprints.Edge;
import com.tinkerpop.blueprints.Vertex;
import com.tinkerpop.blueprints.impls.orient.OrientEdge;
import com.tinkerpop.blueprints.impls.orient.OrientElement;
import com.tinkerpop.blueprints.impls.orient.OrientGraph;
import com.tinkerpop.blueprints.impls.orient.OrientVertex;

public class DBT {

	public static void main(String[] args) {
		
		
		OrientGraph graph = null;
		try {
			graph = new OrientGraph("plocal:/Users/valenpo/Downloads/database/archiva.db");
			
			Multiset<String> ms = HashMultiset.create();
			
			for (Vertex vertex : graph.getVertices()) {
				ms.add("vertex - " + getType((OrientVertex) vertex).toString());
			};
			
			for (Edge edge : graph.getEdges()) {
				try {
					ms.add("edge - " + getType((OrientEdge) edge).toString());
				} catch (Exception e) {
					e.printStackTrace();
				}
			};
			
			for (String entry : ms.elementSet()) {
				System.out.println(entry + ": " + ms.count(entry));
			}
			
			
//			System.out.println(Iterables.size(graph.getVertices()));
			
			
		} catch (Exception e) {
			e.printStackTrace();
		} finally {
			graph.shutdown();
		}

	}

	
	static String getType(OrientElement element) {
		return ODocumentInternal.getImmutableSchemaClass(element.getRecord()).getName();
	}
}
```
```
июн 17, 2015 10:34:10 PM com.orientechnologies.common.log.OLogManager log
INFO: OrientDB auto-config DISKCACHE=4 323MB (heap=1 820MB os=8 192MB disk=244 678MB)
июн 17, 2015 10:34:28 PM com.orientechnologies.common.log.OLogManager log
SEVERE: {db=archiva.db} Error on fetching record during browsing. The record has been skipped
com.orientechnologies.orient.core.exception.ODatabaseException: Error on retrieving record #23:1101737 (cluster: item)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.executeReadRecord(ODatabaseDocumentTx.java:1741)
	at com.orientechnologies.orient.core.tx.OTransactionOptimistic.loadRecord(OTransactionOptimistic.java:224)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.load(ODatabaseDocumentTx.java:1543)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.load(ODatabaseDocumentTx.java:120)
	at com.orientechnologies.orient.core.iterator.OIdentifiableIterator.readCurrentRecord(OIdentifiableIterator.java:287)
	at com.orientechnologies.orient.core.iterator.ORecordIteratorClusters.hasNext(ORecordIteratorClusters.java:159)
	at com.tinkerpop.blueprints.impls.orient.OrientElementIterator.hasNext(OrientElementIterator.java:46)
	at com.stimulus.archiva.database.DBT.main(DBT.java:29)
Caused by: java.lang.NullPointerException
	at com.orientechnologies.orient.core.index.hashindex.local.cache.O2QCache.release(O2QCache.java:333)
	at com.orientechnologies.orient.core.storage.impl.local.paginated.base.ODurableComponent.releasePage(ODurableComponent.java:151)
	at com.orientechnologies.orient.core.storage.impl.local.paginated.OPaginatedCluster.readFullEntry(OPaginatedCluster.java:1404)
	at com.orientechnologies.orient.core.storage.impl.local.paginated.OPaginatedCluster.readRecord(OPaginatedCluster.java:550)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.doReadRecord(OAbstractPaginatedStorage.java:1757)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.readRecord(OAbstractPaginatedStorage.java:1504)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.readRecord(OAbstractPaginatedStorage.java:723)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx$SimpleRecordReader.readRecord(ODatabaseDocumentTx.java:3074)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.executeReadRecord(ODatabaseDocumentTx.java:1708)
	... 7 more
```

Regards,
Valentin

**Comment by laa** [comment]
fixed in latest distribution.
