### ISSUE TITLE
NullPointerException after commit

### ISSUE THREAD

**Issue by PhantomYdn** [orientechnologies/orientdb#4396]
Guys,

There is an NPE after attempt to commit:

```java
java.lang.NullPointerException
	at com.orientechnologies.orient.core.record.impl.ODocument.undo(ODocument.java:1494)
	at com.orientechnologies.orient.core.tx.OTransactionRealAbstract.close(OTransactionRealAbstract.java:121)
	at com.orientechnologies.orient.core.tx.OTransactionOptimistic.rollback(OTransactionOptimistic.java:196)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.commit(ODatabaseDocumentTx.java:2558)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.close(ODatabaseDocumentTx.java:1124)
	at com.orientechnologies.orient.core.db.OPartitionedDatabasePool$DatabaseDocumentTxPolled.close(OPartitionedDatabasePool.java:154)
```

It seems that _field might be null.

**Comment by PhantomYdn** [comment]
Issue seems to be related to #4212
