### ISSUE TITLE
Enterprise Workbench: cannot change admin password

### ISSUE THREAD

**Issue by Wanderfalke** [orientechnologies/orientdb#4399]
Workbench v2.0.8

Error while trying to change admin password:
```
{db=monitor} Error transforming record #27:0 to JSON
java.lang.IllegalArgumentException: Unrecognized JSON formatting option: *:1
    at com.orientechnologies.orient.core.serialization.serializer.record.string.ORecordSerializerJSON$FormatSettings.<init>(ORecordSerializerJSON.java:147)
    at com.orientechnologies.orient.core.serialization.serializer.record.string.ORecordSerializerJSON.toString(ORecordSerializerJSON.java:328)
    at com.orientechnologies.orient.core.serialization.serializer.record.string.ORecordSerializerStringAbstract.toString(ORecordSerializerStringAbstract.java:665)
    at com.orientechnologies.orient.core.record.ORecordAbstract.toJSON(ORecordAbstract.java:192)
    at com.orientechnologies.orient.server.network.protocol.http.OHttpResponse.formatMultiValue(OHttpResponse.java:366)
    at com.orientechnologies.orient.server.network.protocol.http.OHttpResponse.writeRecords(OHttpResponse.java:330)
    at com.orientechnologies.orient.server.network.protocol.http.OHttpResponse.writeResult(OHttpResponse.java:226)
    at com.orientechnologies.orient.server.network.protocol.http.OHttpResponse.writeResult(OHttpResponse.java:192)
    at com.orientechnologies.workbench.http.OServerCommandGetLoggedUserInfo.execute(OServerCommandGetLoggedUserInfo.java:66)
    at com.orientechnologies.orient.server.network.protocol.http.ONetworkProtocolHttpAbstract.service(ONetworkProtocolHttpAbstract.java:200)
    at com.orientechnologies.orient.server.network.protocol.http.ONetworkProtocolHttpAbstract.execute(ONetworkProtocolHttpAbstract.java:600)
    at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:69)
```

After that workbench was not usable (could not login) anymore. Had to delete "monitor" database.

**Comment by maggiolo00** [comment]
@Wanderfalke 

did you try the latest version of Workbench?

**Comment by Wanderfalke** [comment]
@maggiolo00 Sorry, but I'm not a user of OrientDB anymore...
