### ISSUE TITLE
NullPointerException in ODistributedConfiguration.getClusterNames()

### ISSUE THREAD

**Issue by DanielHoffmann** [orientechnologies/orientdb#4401]
Hello, I am trying to set up an orientdb distributed server with two nodes, for some reason I am getting a NullPointerException when the second node comes online, no matter which order I started the nodes, the first one comes online but the second one fails with that exception.

Here is my stackstrace on the second node (nodename is "node2"):
```java
2015-06-19 13:19:19:006 WARNING [node2] opening database 'backendDatabase'... [OHazelcastPlugin]
2015-06-19 13:19:19:011 INFO  [node2] loaded database configuration from active cluster [OHazelcastPlugin]
2015-06-19 13:19:19:015 WARNING [node2] updated distributed configuration for database: backendDatabase:
----------
{
}
---------- [OHazelcastPlugin]Exception in thread "main" java.lang.NullPointerException
	at com.orientechnologies.orient.server.distributed.ODistributedConfiguration.getClusterNames(ODistributedConfiguration.java:363)
	at com.orientechnologies.orient.server.distributed.ODistributedConfiguration.addNewNodeInServerList(ODistributedConfiguration.java:409)
	at com.orientechnologies.orient.server.hazelcast.OHazelcastDistributedDatabase.checkLocalNodeInConfiguration(OHazelcastDistributedDatabase.java:421)
	at com.orientechnologies.orient.server.hazelcast.OHazelcastDistributedDatabase.<init>(OHazelcastDistributedDatabase.java:83)
	at com.orientechnologies.orient.server.hazelcast.OHazelcastDistributedMessageService.registerDatabase(OHazelcastDistributedMessageService.java:302)
	at com.orientechnologies.orient.server.hazelcast.OHazelcastPlugin.loadDistributedDatabases(OHazelcastPlugin.java:1224)
	at com.orientechnologies.orient.server.hazelcast.OHazelcastPlugin.startup(OHazelcastPlugin.java:202)
	at com.orientechnologies.orient.server.OServer.registerPlugins(OServer.java:871)
	at com.orientechnologies.orient.server.OServer.activate(OServer.java:265)
	at com.orientechnologies.orient.server.OServerMain.main(OServerMain.java:41)

2015-06-19 13:19:19:031 INFO  [node2] received new status node2.userDatabase=ONLINE [OHazelcastPlugin]
```

**Comment by lvca** [comment]
Which release? Have you tried with 2.1.2?

**Comment by lvca** [comment]
This issue has been resolved log time ago.
