### ISSUE TITLE
Create edge via JDBC returns OCommandExecutorNotFoundException

### ISSUE THREAD

**Issue by nadewor** [orientechnologies/orientdb#4404]
Used Orientdb 2.0.5 community, JDBC 2.0.5 community. Database is used in plocal mode.

Trying to create an edge between two nodes via JDBC returns a OCommandExecutorNotFoundException.

The java code to dynamically generate the query is:   
String sqlStatementStr = "create edge E from " + input_row.RID + " to " + input_row.RID2;
myStatement2.execute(sqlStatementStr);

and the resulting query is:
create edge E from #11:172 to #12:48

Here the part of the stack trace:
com.orientechnologies.orient.core.command.OCommandExecutorNotFoundException: Cannot find a command executor for the command request: sql.create edge E from #11:172 to #12:48
	at com.orientechnologies.orient.core.sql.OCommandExecutorSQLDelegate.parse(OCommandExecutorSQLDelegate.java:52)
	at com.orientechnologies.orient.core.sql.OCommandExecutorSQLDelegate.parse(OCommandExecutorSQLDelegate.java:37)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.command(OAbstractPaginatedStorage.java:1176)
	at com.orientechnologies.orient.core.command.OCommandRequestTextAbstract.execute(OCommandRequestTextAbstract.java:63)
	at com.orientechnologies.orient.jdbc.OrientJdbcStatement.execute(OrientJdbcStatement.java:102)

**Comment by maggiolo00** [comment]
hi @nadewor 
maybe you miss orientdb-graphdb in your pom.xml

**Comment by nadewor** [comment]
hi @maggiolo00 
thanks for the hint I needed forgot to include the proper jars. After including the orientdb-graphdb jar in my path I get an error:
java.lang.ClassCastException: com.tinkerpop.blueprints.impls.orient.OrientEdge cannot be cast to com.orientechnologies.orient.core.record.impl.ODocument
	at com.orientechnologies.orient.jdbc.OrientJdbcResultSet.<init>(OrientJdbcResultSet.java:61)
	at com.orientechnologies.orient.jdbc.OrientJdbcStatement.execute(OrientJdbcStatement.java:112)

I am not sure if the Orientdb allow to create edges through JDBC connection? Or am I using wrong class java.sql.Statement to create an edge?

**Comment by lvca** [comment]
Fixed in 2.0.12-SNAPSHO and 2.1-SNAPSHOT with a039507c196c5c83e833c429664b50978508ad24
