### ISSUE TITLE
Cannot start database

### ISSUE THREAD

**Issue by henryzhao81** [orientechnologies/orientdb#4407]
Using 2.0.11 to start database, server thru exception and cannot start

2015-06-20 07:04:15:007 INFO  [OVariableParser.resolveVariables] Error on resolving property: distributed [orientechnologies]
2015-06-20 07:04:15:009 INFO  Installing Script interpreter. WARN: authenticated clients can execute any kind of code into the server by using the following allowed languages: [sql] [OServerSideScriptInterpreter]Exception in thread "main" java.lang.AbstractMethodError
	at com.orientechnologies.orient.core.index.OIndexes.createIndex(OIndexes.java:150)
	at com.orientechnologies.orient.core.index.OIndexManagerShared.fromStream(OIndexManagerShared.java:357)
	at com.orientechnologies.orient.core.type.ODocumentWrapperNoClass.reload(ODocumentWrapperNoClass.java:74)
	at com.orientechnologies.orient.core.index.OIndexManagerAbstract.load(OIndexManagerAbstract.java:89)
	at com.orientechnologies.orient.core.index.OIndexManagerAbstract.load(OIndexManagerAbstract.java:53)
	at com.orientechnologies.orient.core.metadata.OMetadataDefault$2.call(OMetadataDefault.java:197)
	at com.orientechnologies.orient.core.metadata.OMetadataDefault$2.call(OMetadataDefault.java:187)
	at com.orientechnologies.common.concur.resource.OSharedContainerImpl.getResource(OSharedContainerImpl.java:57)
	at com.orientechnologies.orient.core.metadata.OMetadataDefault.init(OMetadataDefault.java:186)
	at com.orientechnologies.orient.core.metadata.OMetadataDefault.load(OMetadataDefault.java:77)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.initAtFirstOpen(ODatabaseDocumentTx.java:2687)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.open(ODatabaseDocumentTx.java:255)
	at com.proteus.orientdb.facade.factory.DatabaseFactory.getLocalDatabase(DatabaseFactory.java:302)
	at com.proteus.orientdb.api.security.DataSync.loadRawClasses(DataSync.java:159)
	at com.proteus.orientdb.api.security.DataSync.<init>(DataSync.java:148)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:408)
	at java.lang.Class.newInstance(Class.java:438)
	at com.orientechnologies.orient.server.OServer.registerPlugins(OServer.java:879)
	at com.orientechnologies.orient.server.OServer.activate(OServer.java:263)
	at com.orientechnologies.orient.server.OServerMain.main(OServerMain.java:41)

**Comment by smolinari** [comment]
Just a wild guess, but you might have something wrong with your orientdb-server-config.xml file or your hazelcast config file. I could be completely wrong too. 

Scott

**Comment by lvca** [comment]
@henryzhao81 I cannot see the real cause of that exception. Do you have the full log of it?

**Comment by laa** [comment]
This is linkage exception , method which system tries to call is abstract .
Seems distribution is broken

**Comment by laa** [comment]
@henryzhao81 do you still have this exception ?

**Comment by henryzhao81** [comment]
Looks like it is lucene jar, btw what's the correct version of lucene plugin should i use for RC5.

**Comment by lvca** [comment]
@henryzhao81 Could you please retry with 2.1-c6?
