### ISSUE TITLE
Binding pojo field named "timeout" causes exception when generating schema

### ISSUE THREAD

**Issue by zig158** [orientechnologies/orientdb#4409]
When upgrading from 2.0.10 to 2.1-rc4 I discoverer that when I try to generate schema for a pojo with a field named timeout I get a nasty exception. I am still in development phase, so I can rename my field with minimal effort, but this may be a serous issue for someone in production. I am running OrientDB as an embedded server in distributed mode.

I am opening or creating my database with the following code and updating the schema to my pojos.
```
try(OObjectDatabaseTx db = new OObjectDatabaseTx (localProperties.get(LocalProperty.DB_URL))){
    ...
	db.getMetadata().getSchema().generateSchema(MState.class);
    ...
	db.commit();
}
```
Here is my pojo
```
public class MState implements MRecord{
	@Id
	private Object id;
	@Version
	protected Object version;
	...
	private long timeout;
	...
	public long getTimeout() {
		return timeout;
	}
	public void setTimeout(long timeout) {
		this.timeout = timeout;
	}
	...
}
```
Running the code "db.getMetadata().getSchema().generateSchema(MState.class);" produces the following exception when trying to create the timeout field.
```
com.orientechnologies.orient.core.sql.parser.ParseException: Encountered "" at line 1, column 37.
Was expecting one of:
    
	at com.orientechnologies.orient.core.sql.parser.OrientSql.generateParseException(OrientSql.java:12285)
	at com.orientechnologies.orient.core.sql.parser.OrientSql.jj_consume_token(OrientSql.java:12158)
	at com.orientechnologies.orient.core.sql.parser.OrientSql.NotBlock(OrientSql.java:4949)
	at com.orientechnologies.orient.core.sql.parser.OrientSql.AndBlock(OrientSql.java:4845)
	at com.orientechnologies.orient.core.sql.parser.OrientSql.OrBlock(OrientSql.java:4795)
	at com.orientechnologies.orient.core.sql.parser.OrientSql.WhereClause(OrientSql.java:4760)
	at com.orientechnologies.orient.core.sql.parser.OrientSql.SelectStatement(OrientSql.java:659)
	at com.orientechnologies.orient.core.sql.parser.OrientSql.Statement(OrientSql.java:415)
	at com.orientechnologies.orient.core.sql.parser.OrientSql.parse(OrientSql.java:87)
	at com.orientechnologies.orient.core.sql.OCommandExecutorSQLAbstract.preParse(OCommandExecutorSQLAbstract.java:227)
	at com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.parse(OCommandExecutorSQLSelect.java:209)
	at com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.parse(OCommandExecutorSQLSelect.java:89)
	at com.orientechnologies.orient.core.sql.OCommandExecutorSQLDelegate.parse(OCommandExecutorSQLDelegate.java:76)
	at com.orientechnologies.orient.core.sql.OCommandExecutorSQLDelegate.parse(OCommandExecutorSQLDelegate.java:42)
	at com.orientechnologies.orient.server.distributed.ODistributedStorage.command(ODistributedStorage.java:234)
	at com.orientechnologies.orient.core.command.OCommandRequestTextAbstract.execute(OCommandRequestTextAbstract.java:63)
	at com.orientechnologies.orient.core.metadata.schema.OClassImpl.checkPersistentPropertyType(OClassImpl.java:1905)
	at com.orientechnologies.orient.core.metadata.schema.OClassImpl.addPropertyInternal(OClassImpl.java:1600)
	at com.orientechnologies.orient.core.metadata.schema.OClassImpl.addProperty(OClassImpl.java:2292)
	at com.orientechnologies.orient.core.metadata.schema.OClassImpl.createProperty(OClassImpl.java:773)
	at com.orientechnologies.orient.object.metadata.schema.OSchemaProxyObject.generateSchema(OSchemaProxyObject.java:361)
	at com.orientechnologies.orient.object.metadata.schema.OSchemaProxyObject.generateSchema(OSchemaProxyObject.java:271)
...
```

**Comment by luigidellaquila** [comment]
Hi @zig158 

TIMEOUT was declared as a reserved word in the new parser because it could drive to ambiguous statements in some cases. I'm checking if I can allow it in some circumstances, but I cannot ensure this to be fixed.

**Comment by zig158** [comment]
I suspected that this may be the case. A stupid proof error message that tells the user that they are trying to used a reserved word for property name when calling call generateSchema would be a solid solution. The current message is not all that helpful.

**Comment by luigidellaquila** [comment]
I added a better error message.
Sorry, at this stage this cannot be supported. In next releases we will introduce full support to quoted property and class names (backtick quoting) that will allow any string as a property name
