### ISSUE TITLE
Equals operator == is correct in 2.0.10 but fails in 2.1-SNAPSHOT

### ISSUE THREAD

**Issue by StarpTech** [orientechnologies/orientdb#4413]
Occurs in OrientJs and Studio
Orientdb 2.1 SNAPSHOT

This query fails but works with Orientdb 2.0.10. The reason is the wrong equals operator `==` in my case. This is no issue but should be a hint for people who want to upgrades to the latest version.

Query:

```
select from Node where @class <> 'Root' and ( outE('BroughtIntoRight').size() > 1 or outE('BroughtIntoLeft').size() > 1 ) or ( inE('BroughtIntoLeft', 'BroughtIntoRight').size() == 0 or inE('BroughtIntoLeft', 'BroughtIntoRight').size() > 1)
```

Error:
```
OrientDB.RequestError: Error on parsing command at position #0: Encountered "" at line 1, column 126.
Was expecting one of:

    at Operation.parseError (E:\Vagrant\Ubuntu1404\webapp\api\node_modules\orientjs\lib\transport\binary\protocol28\operation.js:879:13)
    at Operation.consume (E:\Vagrant\Ubuntu1404\webapp\api\node_modules\orientjs\lib\transport\binary\protocol28\operation.js:469:35)
    at Connection.process (E:\Vagrant\Ubuntu1404\webapp\api\node_modules\orientjs\lib\transport\binary\connection.js:380:17)
    at Connection.handleSocketData (E:\Vagrant\Ubuntu1404\webapp\api\node_modules\orientjs\lib\transport\binary\connection.js:281:17)
    at Socket.emit (events.js:107:17)
    at readableAddChunk (_stream_readable.js:163:16)
    at Socket.Readable.push (_stream_readable.js:126:10)
    at TCP.onread (net.js:538:20)
From previous event:
    at Connection._sendOp (E:\Vagrant\Ubuntu1404\webapp\api\node_modules\orientjs\lib\transport\binary\connection.js:81:10)
    at Connection.send (E:\Vagrant\Ubuntu1404\webapp\api\node_modules\orientjs\lib\transport\binary\connection.js:65:17)
    at BinaryTransport.send (E:\Vagrant\Ubuntu1404\webapp\api\node_modules\orientjs\lib\transport\binary\index.js:191:43)
    at Server.send (E:\Vagrant\Ubuntu1404\webapp\api\node_modules\orientjs\lib\server\index.js:112:25)
    at Db.<anonymous> (E:\Vagrant\Ubuntu1404\webapp\api\node_modules\orientjs\lib\db\index.js:152:24)
    at bound (domain.js:254:14)
    at Promise.runBound (domain.js:267:12)
From previous event:
    at Db.send (E:\Vagrant\Ubuntu1404\webapp\api\node_modules\orientjs\lib\db\index.js:144:4)
    at Db.exec (E:\Vagrant\Ubuntu1404\webapp\api\node_modules\orientjs\lib\db\index.js:247:22)
    at Db.query (E:\Vagrant\Ubuntu1404\webapp\api\node_modules\orientjs\lib\db\index.js:279:15)
    at Object.internals.query (E:\Vagrant\Ubuntu1404\webapp\api\lib\graph.js:267:16)
    at Object.exports.checkTreeIntegrity (E:\Vagrant\Ubuntu1404\webapp\api\lib\graph.js:996:13)
    at E:\Vagrant\Ubuntu1404\webapp\api\test\graph\bc24treerules.js:130:11
    at Immediate._onImmediate (C:\Users\dustin\AppData\Roaming\npm\node_modules\lab\lib\runner.js:445:17)
    at processImmediate [as _immediateCallback] (timers.js:358:17)
Unhandled rejection OrientDB.RequestError: Error on parsing command at position #0: Encountered "" at line 1, column 126.
Was expecting one of:

    at Operation.parseError (E:\Vagrant\Ubuntu1404\webapp\api\node_modules\orientjs\lib\transport\binary\protocol28\operation.js:879:13)
    at Operation.consume (E:\Vagrant\Ubuntu1404\webapp\api\node_modules\orientjs\lib\transport\binary\protocol28\operation.js:469:35)
    at Connection.process (E:\Vagrant\Ubuntu1404\webapp\api\node_modules\orientjs\lib\transport\binary\connection.js:380:17)
    at Connection.handleSocketData (E:\Vagrant\Ubuntu1404\webapp\api\node_modules\orientjs\lib\transport\binary\connection.js:281:17)
    at Socket.emit (events.js:107:17)
    at readableAddChunk (_stream_readable.js:163:16)
    at Socket.Readable.push (_stream_readable.js:126:10)
    at TCP.onread (net.js:538:20)
From previous event:
    at Connection._sendOp (E:\Vagrant\Ubuntu1404\webapp\api\node_modules\orientjs\lib\transport\binary\connection.js:81:10)
    at Connection.send (E:\Vagrant\Ubuntu1404\webapp\api\node_modules\orientjs\lib\transport\binary\connection.js:65:17)
    at BinaryTransport.send (E:\Vagrant\Ubuntu1404\webapp\api\node_modules\orientjs\lib\transport\binary\index.js:191:43)
    at Server.send (E:\Vagrant\Ubuntu1404\webapp\api\node_modules\orientjs\lib\server\index.js:112:25)
    at Db.<anonymous> (E:\Vagrant\Ubuntu1404\webapp\api\node_modules\orientjs\lib\db\index.js:152:24)
    at bound (domain.js:254:14)
    at Promise.runBound (domain.js:267:12)
From previous event:
    at Db.send (E:\Vagrant\Ubuntu1404\webapp\api\node_modules\orientjs\lib\db\index.js:144:4)
    at Db.exec (E:\Vagrant\Ubuntu1404\webapp\api\node_modules\orientjs\lib\db\index.js:247:22)
    at Db.query (E:\Vagrant\Ubuntu1404\webapp\api\node_modules\orientjs\lib\db\index.js:279:15)
    at Object.internals.query (E:\Vagrant\Ubuntu1404\webapp\api\lib\graph.js:267:16)
    at Object.exports.checkTreeIntegrity (E:\Vagrant\Ubuntu1404\webapp\api\lib\graph.js:996:13)
    at E:\Vagrant\Ubuntu1404\webapp\api\test\graph\bc24treerules.js:130:11
    at Immediate._onImmediate (C:\Users\dustin\AppData\Roaming\npm\node_modules\lab\lib\runner.js:445:17)
    at processImmediate [as _immediateCallback] (timers.js:358:17)
```

**Comment by luigidellaquila** [comment]
Hi @StarpTech 

thanks for the pointer. == could be treated as a synonym for = in 2.1 (as it was in 2.0). I just have to verify if it has negative impact on the new parser

Thanks

Luigi

**Comment by lvca** [comment]
@luigidellaquila Any bas impact on new parser?

**Comment by luigidellaquila** [comment]
Hi @lvca 
I checked it, the modification should be trivial, I'll fix it in next few days

**Comment by luigidellaquila** [comment]
fixed in develop branch
