### ISSUE TITLE
OCommandSQLParsingException: Error on parsing command at position #0: Encountered " <FROM> "from ""

### ISSUE THREAD

**Issue by StarpTech** [orientechnologies/orientdb#4414]
Studio
Orientdb 2.1 SNAPSHOT

```
select from (traverse References from ( select from Node WHERE Email = 'julia@local'  ) WHERE @class = 'Node' ) where $depth = 1
```

```
 [ONetworkProtocolHttpDb]com.orientechnologies.orient.core.sql.parser.ParseException: Encountered " <FROM> "FROM "" at line 1, column 8.
Was expecting one of:
    <TO> ...
    <VALUES> ...
    <SET> ...
    <ADD> ...
    <PUT> ...
    <MERGE> ...
    <CONTENT> ...
    <REMOVE> ...
    <NULL> ...
    <ORDER> ...
    <GROUP> ...
    <OFFSET> ...
    <RECORD> ...
    <LUCENE> ...
    <NEAR> ...
    <WITHIN> ...
    "@this" ...
    <RECORD_ATTRIBUTE> ...
    <INTEGER_LITERAL> ...
    <FLOATING_POINT_LITERAL> ...
    <CHARACTER_LITERAL> ...
    "true" ...
    "false" ...
    "(" ...
    "{" ...
    "[" ...
    "`" ...
    "?" ...
    ":" ...
    "-" ...
    "*" ...
    <IN> ...
    <KEY> ...
    <IDENTIFIER> ...
    <NULL> ...
    <CHARACTER_LITERAL> ...
    "-" ...
    <INTEGER_LITERAL> ...
    "?" ...
    ":" ...
    "(" ...
    "-" ...
    <INTEGER_LITERAL> ...
    "-" ...
    <FLOATING_POINT_LITERAL> ...
    <IDENTIFIER> ...
    <IN> ...
    <SET> ...
    <PUT> ...
    <ADD> ...
    <REMOVE> ...
    <MERGE> ...
    <CONTENT> ...
    <ORDER> ...
    <KEY> ...
    <OFFSET> ...
    <GROUP> ...
    <VALUES> ...
    <RECORD> ...
    <TO> ...
    <LUCENE> ...
    <NEAR> ...
    <WITHIN> ...
    "`" ...
    "@this" ...
    "[" ...
    <IDENTIFIER> ...
    <IN> ...
    <SET> ...
    <PUT> ...
    <ADD> ...
    <REMOVE> ...
    <MERGE> ...
    <CONTENT> ...
    <ORDER> ...
    <KEY> ...
    <OFFSET> ...
    <GROUP> ...
    <VALUES> ...
    <RECORD> ...
    <TO> ...
    <LUCENE> ...
    <NEAR> ...
    <WITHIN> ...
    "`" ...
    <RECORD_ATTRIBUTE> ...
    "*" ...
    "?" ...
    ":" ...
    "{" ...
    "true" ...
    "false" ...
    "-" ...
    <INTEGER_LITERAL> ...
    "?" ...
    ":" ...

        at com.orientechnologies.orient.core.sql.parser.OrientSql.generateParseException(OrientSql.java:12402)
        at com.orientechnologies.orient.core.sql.parser.OrientSql.jj_consume_token(OrientSql.java:12275)
        at com.orientechnologies.orient.core.sql.parser.OrientSql.Expression(OrientSql.java:4019)
        at com.orientechnologies.orient.core.sql.parser.OrientSql.ProjectionItem(OrientSql.java:3244)
        at com.orientechnologies.orient.core.sql.parser.OrientSql.Projection(OrientSql.java:3193)
        at com.orientechnologies.orient.core.sql.parser.OrientSql.SelectWithoutTargetStatement(OrientSql.java:507)
        at com.orientechnologies.orient.core.sql.parser.OrientSql.Statement(OrientSql.java:419)
        at com.orientechnologies.orient.core.sql.parser.OrientSql.parse(OrientSql.java:87)
        at com.orientechnologies.orient.core.sql.OCommandExecutorSQLAbstract.preParse(OCommandExecutorSQLAbstract.java:227)
        at com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.parse(OCommandExecutorSQLSelect.java:220)
        at com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.parse(OCommandExecutorSQLSelect.java:100)
        at com.orientechnologies.orient.core.sql.OCommandExecutorSQLDelegate.parse(OCommandExecutorSQLDelegate.java:76)
        at com.orientechnologies.orient.core.sql.OCommandExecutorSQLDelegate.parse(OCommandExecutorSQLDelegate.java:42)
        at com.orientechnologies.orient.server.network.protocol.http.command.post.OServerCommandPostCommand.execute(OServerCommandPostCommand.java:76)
        at com.orientechnologies.orient.server.network.protocol.http.ONetworkProtocolHttpAbstract.service(ONetworkProtocolHttpAbstract.java:175)
        at com.orientechnologies.orient.server.network.protocol.http.ONetworkProtocolHttpAbstract.execute(ONetworkProtocolHttpAbstract.java:612)
```

**Comment by luigidellaquila** [comment]
checking right now

**Comment by luigidellaquila** [comment]
the parsing error message is not so clear, actually a problem exists in your query: you are using WHERE clause in a TRAVERSE, while it does not support it. Try to replace the WHERE with a WHILE and you'll see your test pass

```
select from (traverse References from ( select from Node WHERE Email = 'julia@local'  ) WHERE @class = 'Node' ) where $depth = 1

**Comment by StarpTech** [comment]
But 'where' was and is supported since many previous versions before 'latest 2.0.10'. Who tells me that this will be deprecated? :/

**Comment by luigidellaquila** [comment]
Hi @StarpTech 

WHERE is supported (and will remain supported) for all the statements except TRAVERSE. 
Maybe in old releases the parser was too permissive...
Take a look at the docs, they have not changed since a while
http://orientdb.com/docs/last/SQL-Traverse.html

Thanks

Luigi

**Comment by StarpTech** [comment]
Testing with 2.0.10 show you that `where` works and this release is 25days ago and I think also in 2.0.11 it works 3 days ago. But ok I will change my query and give feedback. thanks.

**Comment by luigidellaquila** [comment]
by the way, strict SQL parsing can be disabled in 2.1, you can do it from Studio -> DB tab -> Configuration, see the bottom of the page.
This way you will have complete backward compatibility (but you will also have all the defects of the old parser)

**Comment by lvca** [comment]
TRAVERSE accepted WHERE, but we replace it with WHILE because has more sense. If you see the server log you should notice WARNINGs about that usage. With the new parser this syntax is not supported anymore.
