### ISSUE TITLE
ParseException: Encountered " "(" "( ""

### ISSUE THREAD

**Issue by StarpTech** [orientechnologies/orientdb#4415]
Works in 2.0.10 but fails in 2.1 SNAPSHOT

Query:
```
update (select from (traverse References from ( select from Node WHERE Email = 'julia@local'  ) ) WHERE @class = 'Node' and $depth <= 1 and Active = true ) set Points = 0 RETURN BEFORE $current.Points
```

Error: 
````
2015-06-21 15:12:08:076 SEVER {db=testdb_Network_accounting} Sent run-time exception to the client /10.0.2.2:52899: com.orientechnologies.orient.core.sql.OCommandSQLParsingException: Error on parsing command at position #0: Encountered " "(" "( "" at line 1, column 8.
Was expecting one of:
    <TO> ...
    <VALUES> ...
    <SET> ...
    <ADD> ...
    <PUT> ...
    <MERGE> ...
    <CONTENT> ...
    <REMOVE> ...
    <ORDER> ...
    <GROUP> ...
    <OFFSET> ...
    <RECORD> ...
    <LUCENE> ...
    <NEAR> ...
    <WITHIN> ...
    <INTEGER_LITERAL> ...
    "`" ...
    "-" ...
    <IN> ...
    <KEY> ...
    <IDENTIFIER> ...
    <INDEX_IDENTIFIER> ...
    <INDEXVALUES_IDENTIFIER> ...
    <INDEXVALUESASC_IDENTIFIER> ...
    <INDEXVALUESDESC_IDENTIFIER> ...
    <CLUSTER_IDENTIFIER> ...
    "#" ...
     [ONetworkProtocolBinary]com.orientechnologies.orient.core.sql.parser.ParseException: Encountered " "(" "( "" at line 1, column 8.
Was expecting one of:
    <TO> ...
    <VALUES> ...
    <SET> ...
    <ADD> ...
    <PUT> ...
    <MERGE> ...
    <CONTENT> ...
    <REMOVE> ...
    <ORDER> ...
    <GROUP> ...
    <OFFSET> ...
    <RECORD> ...
    <LUCENE> ...
    <NEAR> ...
    <WITHIN> ...
    <INTEGER_LITERAL> ...
    "`" ...
    "-" ...
    <IN> ...
    <KEY> ...
    <IDENTIFIER> ...
    <INDEX_IDENTIFIER> ...
    <INDEXVALUES_IDENTIFIER> ...
    <INDEXVALUESASC_IDENTIFIER> ...
    <INDEXVALUESDESC_IDENTIFIER> ...
    <CLUSTER_IDENTIFIER> ...
    "#" ...

        at com.orientechnologies.orient.core.sql.parser.OrientSql.generateParseException(OrientSql.java:12402)
        at com.orientechnologies.orient.core.sql.parser.OrientSql.jj_consume_token(OrientSql.java:12275)
        at com.orientechnologies.orient.core.sql.parser.OrientSql.UpdateStatement(OrientSql.java:1825)
        at com.orientechnologies.orient.core.sql.parser.OrientSql.Statement(OrientSql.java:452)
        at com.orientechnologies.orient.core.sql.parser.OrientSql.parse(OrientSql.java:87)
        at com.orientechnologies.orient.core.sql.OCommandExecutorSQLAbstract.preParse(OCommandExecutorSQLAbstract.java:227)
        at com.orientechnologies.orient.core.sql.OCommandExecutorSQLUpdate.parse(OCommandExecutorSQLUpdate.java:101)
        at com.orientechnologies.orient.core.sql.OCommandExecutorSQLUpdate.parse(OCommandExecutorSQLUpdate.java:66)
        at com.orientechnologies.orient.core.sql.OCommandExecutorSQLDelegate.parse(OCommandExecutorSQLDelegate.java:76)
        at com.orientechnologies.orient.core.sql.OCommandExecutorSQLDelegate.parse(OCommandExecutorSQLDelegate.java:42)
        at com.orientechnologies.orient.server.network.protocol.http.command.post.OServerCommandPostCommand.execute(OServerCommandPostCommand.java:76)
        at com.orientechnologies.orient.server.network.protocol.http.ONetworkProtocolHttpAbstract.service(ONetworkProtocolHttpAbstract.java:175)
        at com.orientechnologies.orient.server.network.protocol.http.ONetworkProtocolHttpAbstract.execute(ONetworkProtocolHttpAbstract.java:612)
        at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:71)
```

**Comment by luigidellaquila** [comment]
fixed in develop branch
