### ISSUE TITLE
Database already open after 'drop database'

### ISSUE THREAD

**Issue by omgold** [orientechnologies/orientdb#4418]
I run orientdb 2.0.11 in replication mode (2 nodes, default configuration). When create a database on the console, delete it with 'drop database' and try to recreate it, I get the error 'database already open':

orientdb> create database remote:localhost/foobar root abcdefg plocal document    

Creating database [remote:localhost/foobar] using the storage type [plocal]...
Disconnecting from the database [null]...OK
Connecting to database [remote:localhost/foobar] with user 'admin'...OK

DISTRIBUTED CONFIGURATION:
{
  "members": [{
      "id": "a6522a10-9cc9-4ad2-930f-cd3c05d1e60a",
      "name": "lxms",
      "startedOn": "2015-06-22 09:34:27",
      "listeners": [{"protocol":"ONetworkProtocolBinary","listen":"192.168.50.247:2424"},{"protocol":"ONetworkProtocolHttpDb","listen":"192.168.50.247:2480"}],
      "databases": []
      },{
      "id": "10e510f8-2549-4a23-aa48-d563539480a6",
      "name": "mango",
      "startedOn": "2015-06-22 09:22:29",
      "listeners": [{"protocol":"ONetworkProtocolBinary","listen":"192.168.50.103:2424"},{"protocol":"ONetworkProtocolHttpDb","listen":"192.168.50.103:2480"}],
      "databases": []
      }
  ],
  "localName": "_hzInstance_1_orientdb",
  "localId": "10e510f8-2549-4a23-aa48-d563539480a6"
}
Database created successfully.

Current database is: remote:localhost/foobar
orientdb {db=foobar}> drop database remote:localhost/foobar root abcdefg                  

Disconnecting from remote server [remote:localhost/foobar]...
OK
Disconnecting from the database [foobar]...OK

Database 'remote:localhost/foobar' deleted successfully
orientdb> create database remote:localhost/foobar root abcdefg plocal document

Creating database [remote:localhost/foobar] using the storage type [plocal]...Cannot create the remote storage: foobar
com.orientechnologies.orient.core.exception.ODatabaseException: Cannot create database 'foobar'
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.create(ODatabaseDocumentTx.java:440)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.create(ODatabaseDocumentTx.java:353)
	at com.orientechnologies.orient.server.network.protocol.binary.OBinaryNetworkProtocolAbstract.createDatabase(OBinaryNetworkProtocolAbstract.java:270)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.createDatabase(ONetworkProtocolBinary.java:981)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.executeRequest(ONetworkProtocolBinary.java:291)
	at com.orientechnologies.orient.server.network.protocol.binary.OBinaryNetworkProtocolAbstract.execute(OBinaryNetworkProtocolAbstract.java:217)
	at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:69)
Caused by: com.orientechnologies.orient.core.exception.ODatabaseException: Cannot open database
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.open(ODatabaseDocumentTx.java:277)
	at com.orientechnologies.orient.server.OServer.openDatabase(OServer.java:690)
	at com.orientechnologies.orient.server.hazelcast.OHazelcastPlugin.installDbClustersLocalStrategy(OHazelcastPlugin.java:1118)
	at com.orientechnologies.orient.server.hazelcast.OHazelcastPlugin.onOpen(OHazelcastPlugin.java:423)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.callOnOpenListeners(ODatabaseDocumentTx.java:337)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.open(ODatabaseDocumentTx.java:271)
	at com.orientechnologies.orient.server.OServer.openDatabase(OServer.java:663)
	at com.orientechnologies.orient.server.OServer.openDatabase(OServer.java:629)
	at com.orientechnologies.orient.server.hazelcast.ODistributedWorker.initDatabaseInstance(ODistributedWorker.java:161)
	at com.orientechnologies.orient.server.hazelcast.OHazelcastDistributedDatabase.unqueuePendingMessages(OHazelcastDistributedDatabase.java:265)
	at com.orientechnologies.orient.server.hazelcast.OHazelcastDistributedDatabase.configureDatabase(OHazelcastDistributedDatabase.java:210)
	at com.orientechnologies.orient.server.hazelcast.OHazelcastPlugin.onCreate(OHazelcastPlugin.java:387)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.create(ODatabaseDocumentTx.java:430)
	... 6 more
Caused by: java.lang.IllegalStateException: Database foobar is already open
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.open(ODatabaseDocumentTx.java:238)
	... 18 more

Error: com.orientechnologies.orient.core.exception.OStorageException: Cannot create the remote storage: foobar

Error: com.orientechnologies.orient.core.exception.ODatabaseException: Cannot create database 'foobar'

Error: com.orientechnologies.orient.core.exception.ODatabaseException: Cannot open database

Error: java.lang.IllegalStateException: Database foobar is already open

**Comment by lvca** [comment]
What OrientDB version? Please report always it.

**Comment by omgold** [comment]
It's version 2.0.11, as written in the very first line. But with version 2.1RC4 I see a similar problem, though the backtrace looks somewhat different.

**Comment by AnthonyHebig** [comment]
same problem here with 2.1-rc4 version in distributed mode

**Comment by lvca** [comment]
Fixed in 2.1.6
