### ISSUE TITLE
Deadlock when running a query in Orient Studio in a distributed mode

### ISSUE THREAD

**Issue by ylopotun** [orientechnologies/orientdb#4426]
1) Start the server in the distributed mode.

2) Open Orient Studio and run a query

3) Query execution hangs. jvisualvm reprots a deadlock:

Found one Java-level deadlock:
=============================
"OrientDB HTTP Connection /0:0:0:0:0:0:0:1:2480<-/0:0:0:0:0:0:0:1:58826":
  waiting for ownable synchronizer 0x00000000f7daaf30, (a com.orientechnologies.common.concur.lock.OReadersWriterSpinLock),
  which is held by "OrientDB HTTP Connection /0:0:0:0:0:0:0:1:2480<-/0:0:0:0:0:0:0:1:58823"
"OrientDB HTTP Connection /0:0:0:0:0:0:0:1:2480<-/0:0:0:0:0:0:0:1:58823":
  waiting to lock monitor 0x000000001569c378 (object 0x00000000e001b478, a java.util.HashMap),
  which is held by "OrientDB HTTP Connection /0:0:0:0:0:0:0:1:2480<-/0:0:0:0:0:0:0:1:58826"

Java stack information for the threads listed above:
===================================================
"OrientDB HTTP Connection /0:0:0:0:0:0:0:1:2480<-/0:0:0:0:0:0:0:1:58826":
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x00000000f7daaf30> (a com.orientechnologies.common.concur.lock.OReadersWriterSpinLock)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
	at com.orientechnologies.common.concur.lock.OReadersWriterSpinLock.acquireReadLock(OReadersWriterSpinLock.java:80)
	at com.orientechnologies.orient.core.metadata.schema.OSchemaShared.acquireSchemaReadLock(OSchemaShared.java:601)
	at com.orientechnologies.orient.core.metadata.schema.OSchemaShared.getClasses(OSchemaShared.java:806)
	at com.orientechnologies.orient.core.metadata.schema.OSchemaProxy.getClasses(OSchemaProxy.java:181)
	at com.orientechnologies.orient.server.hazelcast.OHazelcastPlugin.installDbClustersLocalStrategy(OHazelcastPlugin.java:1142)
	at com.orientechnologies.orient.server.hazelcast.OHazelcastPlugin.onOpen(OHazelcastPlugin.java:416)
	- locked <0x00000000e001b478> (a java.util.HashMap)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.callOnOpenListeners(ODatabaseDocumentTx.java:342)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.open(ODatabaseDocumentTx.java:276)
	at com.orientechnologies.orient.server.OServer.openDatabase(OServer.java:647)
	at com.orientechnologies.orient.server.OServer.openDatabase(OServer.java:629)
	at com.orientechnologies.orient.server.network.protocol.http.command.OServerCommandAuthenticatedDbAbstract.getProfiledDatabaseInstanceBasic(OServerCommandAuthenticatedDbAbstract.java:249)
	at com.orientechnologies.orient.server.network.protocol.http.command.OServerCommandAuthenticatedDbAbstract.getProfiledDatabaseInstance(OServerCommandAuthenticatedDbAbstract.java:215)
	at com.orientechnologies.orient.server.network.protocol.http.command.post.OServerCommandPostCommand.execute(OServerCommandPostCommand.java:65)
	at com.orientechnologies.orient.server.network.protocol.http.ONetworkProtocolHttpAbstract.service(ONetworkProtocolHttpAbstract.java:175)
	at com.orientechnologies.orient.server.network.protocol.http.ONetworkProtocolHttpAbstract.execute(ONetworkProtocolHttpAbstract.java:612)
	at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:71)
"OrientDB HTTP Connection /0:0:0:0:0:0:0:1:2480<-/0:0:0:0:0:0:0:1:58823":
	at com.orientechnologies.orient.server.distributed.ODistributedAbstractPlugin.getDatabaseConfiguration(ODistributedAbstractPlugin.java:275)
	- waiting to lock <0x00000000e001b478> (a java.util.HashMap)
	at com.orientechnologies.orient.server.hazelcast.OHazelcastPlugin.onCreateClass(OHazelcastPlugin.java:439)
	at com.orientechnologies.orient.core.metadata.schema.OSchemaShared.doCreateClass(OSchemaShared.java:1026)
	at com.orientechnologies.orient.core.metadata.schema.OSchemaShared.createClass(OSchemaShared.java:403)
	at com.orientechnologies.orient.core.metadata.schema.OSchemaProxy.createClass(OSchemaProxy.java:127)
	at com.orientechnologies.orient.core.sql.OCommandExecutorSQLCreateClass.execute(OCommandExecutorSQLCreateClass.java:179)
	at com.orientechnologies.orient.core.sql.OCommandExecutorSQLDelegate.execute(OCommandExecutorSQLDelegate.java:90)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.executeCommand(OAbstractPaginatedStorage.java:1232)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.command(OAbstractPaginatedStorage.java:1213)
	at com.orientechnologies.orient.server.distributed.ODistributedStorage.command(ODistributedStorage.java:301)
	at com.orientechnologies.orient.core.command.OCommandRequestTextAbstract.execute(OCommandRequestTextAbstract.java:63)
	at com.orientechnologies.orient.server.network.protocol.http.command.post.OServerCommandPostCommand.execute(OServerCommandPostCommand.java:81)
	at com.orientechnologies.orient.server.network.protocol.http.ONetworkProtocolHttpAbstract.service(ONetworkProtocolHttpAbstract.java:175)
	at com.orientechnologies.orient.server.network.protocol.http.ONetworkProtocolHttpAbstract.execute(ONetworkProtocolHttpAbstract.java:612)
	at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:71)

**Comment by laa** [comment]
Luca, why to me it is issue of distributed db when clusters are installed, I would need to spend many hours to investigate distributed storage is it OK ?

**Comment by ylopotun** [comment]
Note that this one is reproducible with 2.1-rc4 but not with 2.1-SNAPSHOT anymore.

**Comment by lvca** [comment]
Good. How can we be sure?

**Comment by lvca** [comment]
I'm closing it. In case please reopen or comment it.
