### ISSUE TITLE
Transaction was rolled back more times than it was started

### ISSUE THREAD

**Issue by ylopotun** [orientechnologies/orientdb#4427]
Occasionally when performing a commit the following exception is thrown:

com.orientechnologies.orient.core.exception.OTransactionException: Transaction was rolled back more times than it was started.
	at com.orientechnologies.orient.core.tx.OTransactionOptimistic.rollback(OTransactionOptimistic.java:174)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.commit(ODatabaseDocumentTx.java:2558)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.commit(ODatabaseDocumentTx.java:2517)
	at com.tinkerpop.blueprints.impls.orient.OrientTransactionalGraph.commit(OrientTransactionalGraph.java:161)
	at com.miranda.mcs.ucs.ds.persistence.orientdb.OrientDSUtils.commit(OrientDSUtils.java:1366)

**Comment by laa** [comment]
Hi, I have added additional checks, could you create new distribution from develop branch and use it ?

**Comment by laa** [comment]
Yuriy do you have Skype ?

**Comment by ylopotun** [comment]
Ok, will try with the latest from develop. My skype: jurij_lopotun

**Comment by ylopotun** [comment]
So far we can't reproduce it with 2.1-SNAPSHOT, but the logs are now flooded with Concurrent modification exceptions.

**Comment by laa** [comment]
But CME is very typical one in concurrent environment. Do you handle it in your application ?

**Comment by ylopotun** [comment]
Yes, we handle it. I just mean that the logging that you added: OLogManager.instance().error(this, "Error on TX commit.", e); started flooding the logs with CME stack traces. Is it necessary? I think, logging in this case is already happening in one of the caller methods.

**Comment by laa** [comment]
Hi, I see , I will change it to debug level.

**Comment by ylopotun** [comment]
So, so far I can't reproduce this exception with 2.1-SNAPSHOT.

Looks like this exception was always following the below exception which is reported to be fixed in: 

https://github.com/orientechnologies/orientdb/issues/4396


2015-06-17 08:04:47,573 [pool-1-thread-2] ERROR com.mira.mcs.ucs.ds.fact.FactoryEngine - invokeOneFactory
java.lang.NullPointerException
	at com.orientechnologies.orient.core.record.impl.ODocument.undo(ODocument.java:1494)
	at com.orientechnologies.orient.core.tx.OTransactionRealAbstract.close(OTransactionRealAbstract.java:121)
	at com.orientechnologies.orient.core.tx.OTransactionOptimistic.rollback(OTransactionOptimistic.java:196)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.commit(ODatabaseDocumentTx.java:2558)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.commit(ODatabaseDocumentTx.java:2517)
	at com.tinkerpop.blueprints.impls.orient.OrientTransactionalGraph.commit(OrientTransactionalGraph.java:161)
	at com.miranda.mcs.ucs.ds.persistence.orientdb.OrientDSUtils.commit(OrientDSUtils.java:1366)
	at com.miranda.mcs.ucs.ds.persistence.orientdb.OrientTable.createRecord(OrientTable.java:329)
	at com.miranda.mcs.ucs.ds.factory.RecordFactory.lambda$adjustCount$22(RecordFactory.java:337)
	at com.miranda.mcs.ucs.ds.factory.RecordFactory$$Lambda$104/1599394190.accept(Unknown Source)
	at java.util.stream.Streams$RangeIntSpliterator.forEachRemaining(Streams.java:114)
	at java.util.stream.IntPipeline$Head.forEach(IntPipeline.java:557)
	at com.miranda.mcs.ucs.ds.factory.RecordFactory.adjustCount(RecordFactory.java:299)
	at com.miranda.mcs.ucs.ds.factory.RecordFactory.create(RecordFactory.java:200)
	at com.miranda.mcs.ucs.ds.factory.FactoryEngine.invokeOneFactory(FactoryEngine.java:106)
	at com.miranda.mcs.ucs.ds.factory.FactoryEngine.lambda$null$7(FactoryEngine.java:91)
	at com.miranda.mcs.ucs.ds.factory.FactoryEngine$$Lambda$101/453485293.accept(Unknown Source)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.Iterator.forEachRemaining(Iterator.java:116)
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:512)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:502)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at com.miranda.mcs.ucs.ds.factory.FactoryEngine.lambda$null$8(FactoryEngine.java:86)
	at com.miranda.mcs.ucs.ds.factory.FactoryEngine$$Lambda$99/1117844193.accept(Unknown Source)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at com.miranda.mcs.ucs.ds.factory.FactoryEngine.lambda$null$9(FactoryEngine.java:78)
	at com.miranda.mcs.ucs.ds.factory.FactoryEngine$$Lambda$98/1127333381.apply(Unknown Source)
	at com.miranda.mcs.ucs.ds.util.DSUtils.readWithLock(DSUtils.java:1273)
	at com.miranda.mcs.ucs.ds.factory.FactoryEngine.lambda$static$10(FactoryEngine.java:75)
	at com.miranda.mcs.ucs.ds.factory.FactoryEngine$$Lambda$90/2018018675.accept(Unknown Source)
	at com.miranda.mcs.ucs.ds.factory.FactoryEngine.lambda$forEverEach$16(FactoryEngine.java:172)
	at com.miranda.mcs.ucs.ds.factory.FactoryEngine$$Lambda$93/383848174.listChanged(Unknown Source)
	at ca.odell.glazedlists.event.ListEventAssembler$ListEventFormat.fire(ListEventAssembler.java:414)
	at ca.odell.glazedlists.event.ListEventAssembler$ListEventFormat.fire(ListEventAssembler.java:411)
	at ca.odell.glazedlists.event.SequenceDependenciesEventPublisher$SubjectAndListener.firePendingEvent(SequenceDependenciesEventPublisher.java:445)
	at ca.odell.glazedlists.event.SequenceDependenciesEventPublisher.fireEvent(SequenceDependenciesEventPublisher.java:344)
	at ca.odell.glazedlists.event.ListEventAssembler.commitEvent(ListEventAssembler.java:316)
	at ca.odell.glazedlists.BasicEventList.add(BasicEventList.java:142)
	at com.miranda.mcs.ucs.ds.persistence.orientdb.OrientTable.lambda$null$107(OrientTable.java:448)
	at com.miranda.mcs.ucs.ds.persistence.orientdb.OrientTable$$Lambda$66/1756445238.accept(Unknown Source)
	at com.miranda.mcs.ucs.ds.util.DSUtils.writeWithLock(DSUtils.java:1250)
	at com.miranda.mcs.ucs.ds.util.DSUtils.withEventList(DSUtils.java:1291)
	at com.miranda.mcs.ucs.ds.persistence.orientdb.OrientTable.lambda$addRecordToTableCache$108(OrientTable.java:442)
	at com.miranda.mcs.ucs.ds.persistence.orientdb.OrientTable$$Lambda$65/2035620776.run(Unknown Source)
	at com.miranda.mcs.ucs.ds.persistence.orientdb.OrientDataManager.lambda$runTask$80(OrientDataManager.java:1839)
	at com.miranda.mcs.ucs.ds.persistence.orientdb.OrientDataManager$$Lambda$6/533173186.accept(Unknown Source)
	at com.miranda.mcs.ucs.ds.persistence.orientdb.OrientDataManager.lambda$withGraph$71(OrientDataManager.java:1230)
	at com.miranda.mcs.ucs.ds.persistence.orientdb.OrientDataManager$$Lambda$7/848958019.apply(Unknown Source)
	at com.miranda.mcs.ucs.ds.persistence.orientdb.OrientDataManager.fromGraph(OrientDataManager.java:1214)
	at com.miranda.mcs.ucs.ds.persistence.orientdb.OrientDataManager.withGraph(OrientDataManager.java:1230)
	at com.miranda.mcs.ucs.ds.persistence.orientdb.OrientDataManager.runTask(OrientDataManager.java:1839)
	at com.miranda.mcs.ucs.ds.DataManagerFactory.lambda$runBackgroundTask$164(DataManagerFactory.java:210)
	at com.miranda.mcs.ucs.ds.DataManagerFactory$$Lambda$10/1624355359.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:744)

**Comment by lvca** [comment]
Cool, closing it.
