### ISSUE TITLE
Shutdown Issue 2.0.11?

### ISSUE THREAD

**Issue by dshurt** [orientechnologies/orientdb#4441]
I'm trying to upgrade from 1.7.10 to 2.0.11 and it's **very close** to being a simple drop-in replacement which is fantastic...great job on that!   This is a great database and it's very flexible.  I hate swamping you guys with issues but, hopefully it's helpful. 
I just ran into a couple hiccups.

One is issue is here https://github.com/orientechnologies/orientdb/issues/4440

The other one is minor issue on the shutdown:

To shutdown I'm calling:

... globalInstance = OObjectDatabasePool.global(...)

.... 
//Closing the connection pool
1. globalInstance.close();

OServer server = OServerMain.create();
....
2. server.shutdown();

It shutdown but throws errors.  in 1.7.10 shutdowns without errors.
It's acts like the connection pool is still active after closing.

Log:
------
2015-06-22 16:33:57:697 INFO  OrientDB Server is shutting down... [OServer]
2015-06-22 16:33:57:697 INFO  Shutting down listeners: [OServer]
2015-06-22 16:33:57:698 INFO  - ONetworkProtocolBinary /0.0.0.0:2424: [OServer]
2015-06-22 16:33:57:698 INFO  - ONetworkProtocolHttpDb /0.0.0.0:2480: [OServer]
2015-06-22 16:33:57:698 INFO  Shutting down protocols [OServer]
2015-06-22 16:33:57:698 INFO  Shutting down plugins: [OServerPluginManager]
2015-06-22 16:33:57:698 INFO  - script-interpreter [OServerPluginManager]
2015-06-22 16:33:57:698 INFO  - graph [OServerPluginManager]
2015-06-22 16:33:57:703 INFO  Shutting down databases: [OServer]
2015-06-22 16:33:57:703 INFO  - closing storage: openstorefront... [Orient]
2015-06-22 16:33:57:704 SEVERE Removing disconnected network channel '127.0.0.1:2424/openstorefront'... [OStorageRemote]
2015-06-22 16:33:58:716 INFO  - closing storage: openstorefront... [Orient]
2015-06-22 16:33:59:731 INFO  - closing storage: openstorefront... [Orient]
2015-06-22 16:34:00:733 INFO  - closing storage: openstorefront... [Orient]
2015-06-22 16:34:01:744 INFO  - closing storage: openstorefront... [Orient]
2015-06-22 16:34:02:746 INFO  - closing storage: openstorefront... [Orient]
2015-06-22 16:34:03:748 INFO  - closing storage: openstorefront... [Orient]
2015-06-22 16:34:05:087 WARNING Caught I/O errors, trying to reconnect (error: com.orientechnologies.common.io.OIOException: Cannot open a connection to remote server: 127.0.0.1:2424/openstorefront) [OStorageRemote]Error on releasing database 'openstorefront' in pool
com.orientechnologies.orient.core.exception.OStorageException: Error on commit
	at com.orientechnologies.orient.client.remote.OStorageRemote.handleException(OStorageRemote.java:1591)
	at com.orientechnologies.orient.client.remote.OStorageRemote.commit(OStorageRemote.java:1181)
	at com.orientechnologies.orient.client.remote.OStorageRemoteThread.commit(OStorageRemoteThread.java:445)
	at com.orientechnologies.orient.core.tx.OTransactionOptimistic.doCommit(OTransactionOptimistic.java:475)
	at com.orientechnologies.orient.core.tx.OTransactionOptimistic.commit(OTransactionOptimistic.java:147)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.commit(ODatabaseDocumentTx.java:2430)
	at com.orientechnologies.orient.object.db.OObjectDatabaseTx.commit(OObjectDatabaseTx.java:553)
	at com.orientechnologies.orient.object.db.OObjectDatabaseTxPooled.close(OObjectDatabaseTxPooled.java:110)
	at com.orientechnologies.orient.core.db.ODatabaseFactory.shutdown(ODatabaseFactory.java:97)
	at com.orientechnologies.orient.core.Orient.shutdown(Orient.java:280)
	at com.orientechnologies.orient.server.OServer.shutdown(OServer.java:352)
	at edu.usu.sdl.openstorefront.service.manager.DBManager.cleanup(DBManager.java:105)
	at edu.usu.sdl.openstorefront.service.manager.DBManager.shutdown(DBManager.java:52)
	at edu.usu.sdl.openstorefront.web.init.ApplicationInit.shutdownManager(ApplicationInit.java:112)
	at edu.usu.sdl.openstorefront.web.init.ApplicationInit.contextDestroyed(ApplicationInit.java:103)
	at org.apache.catalina.core.StandardContext.listenerStop(StandardContext.java:5033)
	at org.apache.catalina.core.StandardContext.stopInternal(StandardContext.java:5685)
	at org.apache.catalina.util.LifecycleBase.stop(LifecycleBase.java:232)
	at org.apache.catalina.manager.ManagerServlet.undeploy(ManagerServlet.java:1396)
	at org.apache.catalina.manager.ManagerServlet.doGet(ManagerServlet.java:394)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:620)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:727)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.catalina.filters.SetCharacterEncodingFilter.doFilter(SetCharacterEncodingFilter.java:108)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:610)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:171)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:950)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:408)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1070)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:611)
	at org.apache.tomcat.util.net.AprEndpoint$SocketProcessor.doRun(AprEndpoint.java:2440)
	at org.apache.tomcat.util.net.AprEndpoint$SocketProcessor.run(AprEndpoint.java:2429)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:745)

....(Several more simiular warnings with stacks)

Then
2015-06-22 16:34:45:080 INFO  OrientDB Engine shutdown complete [Orient]
2015-06-22 16:34:45:080 INFO  OrientDB Server shutdown complete [OServer]

So it succeeds but, it appears that there's something with shutdown the connection pool.

**Comment by lvca** [comment]
@laa is this the same bug you already fixed in 2.1-SNAPSHOT?

**Comment by laa** [comment]
No, it is remote storage/connection pool issue assign it to @tglman .

**Comment by tglman** [comment]
fixed in develop and 2.0.x , will be out with 2.0.12
