### ISSUE TITLE
ClassNotFoundException when running in distributed mode in OSGi environment

### ISSUE THREAD

**Issue by ylopotun** [orientechnologies/orientdb#4443]
In OSGi environment Hazelcast bundle's classloader doesnt know about the orient-core bundle's classes, thus the following exception is thrown on its startup:

com.hazelcast.nio.serialization.HazelcastSerializationException: Problem while reading Externalizable class : com.orientechnologies.orient.core.record.impl.ODocument, exception: java.lang.ClassNotFoundException: com.orientechnologies.orient.core.record.impl.ODocument
	at com.hazelcast.nio.serialization.DefaultSerializers$Externalizer.read(DefaultSerializers.java:150)
	at com.hazelcast.nio.serialization.DefaultSerializers$Externalizer.read(DefaultSerializers.java:124)
	at com.hazelcast.nio.serialization.StreamSerializerAdapter.read(StreamSerializerAdapter.java:63)
	at com.hazelcast.nio.serialization.SerializationServiceImpl.readObject(SerializationServiceImpl.java:285)
	at com.hazelcast.nio.serialization.SerializationServiceImpl.toObject(SerializationServiceImpl.java:262)
	at com.hazelcast.spi.impl.NodeEngineImpl.toObject(NodeEngineImpl.java:186)
	at com.hazelcast.map.AbstractMapServiceContextSupport.toObject(AbstractMapServiceContextSupport.java:41)
	at com.hazelcast.map.DefaultMapServiceContext.toObject(DefaultMapServiceContext.java:26)
	at com.hazelcast.map.proxy.MapProxySupport.toObject(MapProxySupport.java:1035)
	at com.hazelcast.map.proxy.MapProxyImpl.get(MapProxyImpl.java:84)
	at com.orientechnologies.orient.server.hazelcast.OHazelcastPlugin.getNodeConfigurationById(OHazelcastPlugin.java:261)
	at com.orientechnologies.orient.server.hazelcast.OHazelcastPlugin.getNodeName(OHazelcastPlugin.java:513)
	at com.orientechnologies.orient.server.hazelcast.OHazelcastPlugin.entryAdded(OHazelcastPlugin.java:632)
	at com.hazelcast.map.MapEventPublishingService.dispatch0(MapEventPublishingService.java:85)
	at com.hazelcast.map.MapEventPublishingService.dispatchEntryEventData(MapEventPublishingService.java:64)
	at com.hazelcast.map.MapEventPublishingService.dispatchEvent(MapEventPublishingService.java:39)
	at com.hazelcast.map.MapEventPublishingService.dispatchEvent(MapEventPublishingService.java:17)
	at com.hazelcast.map.MapService.dispatchEvent(MapService.java:76)
	at com.hazelcast.map.MapService.dispatchEvent(MapService.java:51)
	at com.hazelcast.spi.impl.EventServiceImpl$LocalEventDispatcher.run(EventServiceImpl.java:650)
	at com.hazelcast.util.executor.StripedExecutor$Worker.process(StripedExecutor.java:189)
	at com.hazelcast.util.executor.StripedExecutor$Worker.run(StripedExecutor.java:173)

We need to provide Hazelcast with orient-distributed bundle classloader, which is aware of ODocument class. 

Fixed in a pull request:
https://github.com/orientechnologies/orientdb/pull/4446

**Comment by lvca** [comment]
Fixed thanks to your PR. Thanks so much.
