### ISSUE TITLE
NullPointerException on corrupted database (OrientDB 2.1-rc4)

### ISSUE THREAD

**Issue by jamieb22** [orientechnologies/orientdb#4451]
java.lang.NullPointerException: null
        at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinaryV0.readSingleValue(ORecordSerializerBinaryV0.java:291) ~[orientdb-core-2.1-SNAPSHOT.jar:2.1-SNAPSHOT]
        at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinaryV0.readEmbeddedMap(ORecordSerializerBinaryV0.java:427) ~[orientdb-core-2.1-SNAPSHOT.jar:2.1-SNAPSHOT]
        at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinaryV0.readSingleValue(ORecordSerializerBinaryV0.java:363) ~[orientdb-core-2.1-SNAPSHOT.jar:2.1-SNAPSHOT]
        at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinaryV0.deserializePartial(ORecordSerializerBinaryV0.java:141) ~[orientdb-core-2.1-SNAPSHOT.jar:2.1-SNAPSHOT]
        at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinary.fromStream(ORecordSerializerBinary.java:72) ~[orientdb-core-2.1-SNAPSHOT.jar:2.1-SNAPSHOT]
        at com.orientechnologies.orient.core.record.impl.ODocument.deserializeFields(ODocument.java:1759) ~[orientdb-core-2.1-SNAPSHOT.jar:2.1-SNAPSHOT]
        at com.orientechnologies.orient.core.record.impl.ODocument.checkForFields(ODocument.java:2336) ~[orientdb-core-2.1-SNAPSHOT.jar:2.1-SNAPSHOT]
        at com.orientechnologies.orient.core.record.impl.ODocument.rawField(ODocument.java:760) ~[orientdb-core-2.1-SNAPSHOT.jar:2.1-SNAPSHOT]
        at com.orientechnologies.orient.core.record.impl.ODocument.field(ODocument.java:785) ~[orientdb-core-2.1-SNAPSHOT.jar:2.1-SNAPSHOT]
        at com.tinkerpop.blueprints.impls.orient.OrientElement.getProperty(OrientElement.java:271) ~[orientdb-graphdb-2.1-SNAPSHOT.jar:2.1-SNAPSHOT]
        at com.tinkerpop.blueprints.impls.orient.OrientEdge.getProperty(OrientEdge.java:294) ~[orientdb-graphdb-2.1-SNAPSHOT.jar:2.1-SNAPSHOT]
        at com.stimulus.archiva.ek.a(MailArchiva:844) ~[ek.class:na]
        at com.stimulus.archiva.ez.b(MailArchiva:47) ~[ez.class:na]
        at com.stimulus.archiva.nt.a(MailArchiva:501) ~[nt.class:na]
        at com.stimulus.archiva.nt.run(MailArchiva:469) ~[nt.class:na]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471) [na:1.7.0_75]
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:304) [na:1.7.0_75]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:178) [na:1.7.0_75]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [na:1.7.0_75]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [na:1.7.0_75]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [na:1.7.0_75]
        at java.lang.Thread.run(Thread.java:745) [na:1.7.0_75]

**Comment by tglman** [comment]
@jamieb22 you should have an additional log of this error that show some more information something starting with "Error deserializing record with id", can you send also that?

will be useful have the db or otherwise you can just run "display raw record" from the console with the record id of the broken record.

did you create the database with the 2.1-rc4 ?

**Comment by jamieb22** [comment]
I have supplied the database to Andrey for analysis. I am waiting for his input on what might be wrong. The database was created by prior snapshot of 2.1

**Comment by laa** [comment]
It is already fixed in 2.1 version
