### ISSUE TITLE
Validation of named parameters in a query

### ISSUE THREAD

**Issue by fritaly** [orientechnologies/orientdb#4470]
I'm executing the following query with named parameters

```groovy
def repositorySql = new StringBuilder()
repositorySql << "UPDATE ${GitHubRepository_ClassName} "
repositorySql << "SET name = :name, full_name = :fullname, html_url = :html_url, description = :description, git_url = :git_url, ssh_url = :ssh_url, clone_url = :clone_url, svn_url = :svn_url "
repositorySql << "UPSERT WHERE full_name = :fullname"
```

In the WHERE clause, I have to name my parameter 'fullname' because using 'full_name' raises the following exception.

```
Exception in thread "main" com.orientechnologies.orient.core.exception.OQueryParsingException: Error on parsing query
Query:   full_name = :full_name
------^
	at com.orientechnologies.orient.core.sql.filter.OSQLPredicate.text(OSQLPredicate.java:105)
	at com.orientechnologies.orient.core.sql.filter.OSQLFilter.<init>(OSQLFilter.java:50)
	at com.orientechnologies.orient.core.sql.OSQLEngine.parseCondition(OSQLEngine.java:436)
	at com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.parse(OCommandExecutorSQLSelect.java:217)
	at com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.parse(OCommandExecutorSQLSelect.java:78)
	at com.orientechnologies.orient.core.sql.OCommandExecutorSQLDelegate.parse(OCommandExecutorSQLDelegate.java:56)
	at com.orientechnologies.orient.core.sql.OCommandExecutorSQLDelegate.parse(OCommandExecutorSQLDelegate.java:37)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.command(OAbstractPaginatedStorage.java:1181)
	at com.orientechnologies.orient.core.sql.query.OSQLQuery.run(OSQLQuery.java:71)
	at com.orientechnologies.orient.core.query.OQueryAbstract.execute(OQueryAbstract.java:33)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.query(ODatabaseDocumentTx.java:647)
	at com.orientechnologies.orient.core.sql.OCommandExecutorSQLUpdate.execute(OCommandExecutorSQLUpdate.java:216)
	at com.orientechnologies.orient.core.sql.OCommandExecutorSQLDelegate.execute(OCommandExecutorSQLDelegate.java:64)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.executeCommand(OAbstractPaginatedStorage.java:1194)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.command(OAbstractPaginatedStorage.java:1183)
	at com.orientechnologies.orient.core.command.OCommandRequestTextAbstract.execute(OCommandRequestTextAbstract.java:63)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.command(ONetworkProtocolBinary.java:1179)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.executeRequest(ONetworkProtocolBinary.java:386)
	at com.orientechnologies.orient.server.network.protocol.binary.OBinaryNetworkProtocolAbstract.execute(OBinaryNetworkProtocolAbstract.java:217)
	at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:69)
Caused by: com.orientechnologies.orient.core.exception.OQueryParsingException: Parameter name 'full_name' is invalid, only alphanumeric characters are allowed
	at com.orientechnologies.orient.core.sql.filtPredicate.addParameter(OSQLPredicate.java:400)
	at com.orientechnologies.orient.core.sql.OSQLHelper.parseValue(OSQLHelper.java:180)
	at com.orientechnologies.orient.core.sql.filter.OSQLPredicate.extractConditionItem(OSQLPredicate.java:345)
	at com.orientechnologies.orient.core.sql.filter.OSQLPredicate.extractCondition(OSQLPredicate.java:201)
	at com.orientechnologies.orient.core.sql.filter.OSQLPredicate.extractConditions(OSQLPredicate.java:145)
	at com.orientechnologies.orient.core.sql.filter.OSQLPredicate.text(OSQLPredicate.java:99)
	... 19 more
```

I'm puzzled because I have another SQL UPDATE statement (see below) where I have a parameter named ':full_name' but not inside the WHERE clause.

```groovy
def userSql = new StringBuilder()
userSql << "UPDATE ${GitHubUser_ClassName} "
userSql << "SET name = :name, full_name = :full_name, profile_url = :profile_url, ldap_dn = :ldap_dn, location = :location "
userSql << "UPSERT WHERE name = :name"
```

It looks like naming a parameter 'full_name' is sometimes allowed, sometimes forbidden (apparently when used inside a WHERE clause). 

Is there a different logic for validating parameter names ?

Note: I'm using Community Edition 2.0.11

**Comment by luigidellaquila** [comment]
It's already fixed in develop branch. I just added a new test case for this

**Comment by fritaly** [comment]
Awesome. Thanks !
