### ISSUE TITLE
Create database in console is no good for studio

### ISSUE THREAD

**Issue by optimuspaul** [orientechnologies/orientdb#4471]
I created a database on the console and then tried to login to use it in the studio and got this error.
```
{db=cg_connections} Error on exporting class '_studio'
com.orientechnologies.orient.core.exception.OConfigurationException: Cluster id 11 was not found in database 'cg_connections'
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.count(OAbstractPaginatedStorage.java:617)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.countClusterElements(ODatabaseDocumentTx.java:698)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.countClusterElements(ODatabaseDocumentTx.java:662)
	at com.orientechnologies.orient.core.metadata.schema.OImmutableClass.count(OImmutableClass.java:386)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.countClass(ODatabaseDocumentTx.java:2370)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.countClass(ODatabaseDocumentTx.java:2356)
	at com.orientechnologies.orient.server.network.protocol.http.command.get.OServerCommandGetDatabase.exportClass(OServerCommandGetDatabase.java:70)
	at com.orientechnologies.orient.server.network.protocol.http.command.get.OServerCommandGetDatabase.exec(OServerCommandGetDatabase.java:181)
	at com.orientechnologies.orient.server.network.protocol.http.command.get.OServerCommandGetDatabase.execute(OServerCommandGetDatabase.java:136)
	at com.orientechnologies.orient.server.network.protocol.http.ONetworkProtocolHttpAbstract.service(ONetworkProtocolHttpAbstract.java:174)
	at com.orientechnologies.orient.server.network.protocol.http.ONetworkProtocolHttpAbstract.execute(ONetworkProtocolHttpAbstract.java:574)
	at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:69)
```

**Comment by optimuspaul** [comment]
I don't see cluster 11 either...
```
CLASSES
----------------------------------------------+------------------------------------+------------+----------------+
 NAME                                         | SUPERCLASS                         | CLUSTERS   | RECORDS        |
----------------------------------------------+------------------------------------+------------+----------------+
 E                                            |                                    | 10         |              0 |
 OFunction                                    |                                    | 6          |              0 |
 OIdentity                                    |                                    | -          |              0 |
 ORestricted                                  |                                    | -          |              0 |
 ORIDs                                        |                                    | 8          |              0 |
 ORole                                        | OIdentity                          | 4          |              3 |
 OSchedule                                    |                                    | 7          |              0 |
 OTriggered                                   |                                    | -          |              0 |
 OUser                                        | OIdentity                          | 5          |              3 |
 V                                            |                                    | 9          |              0 |
----------------------------------------------+------------------------------------+------------+----------------+
 TOTAL = 10                                                                                                    6 |
----------------------------------------------+------------------------------------+------------+----------------+
```

**Comment by lvca** [comment]
What release?
