### ISSUE TITLE
Lucene indexes became SBTREE when imported

### ISSUE THREAD

**Issue by optimuspaul** [orientechnologies/orientdb#4473]
I imported data from one DB to another and all the indexes that were Lucene are now SBTREE indexes. :cry:

**Comment by optimuspaul** [comment]
ok
```
Error: com.orientechnologies.orient.core.index.OIndexException: Engine type: 'LUCENE' is not supported. Types are [SBTREE,MVRBTREE]. Please check the engine name or verify that the engine 'LUCENE' is installed correctly
```

**Comment by optimuspaul** [comment]
I retried my import with the lucene plugin installed....
```
2015-06-26 16:59:28:241 SEVERE {db=cg_connections}  [OIndexFullText]
2015-06-26 16:59:28:241 WARNING {db=cg_connections} Cannot load index 'cg_sps_org.name' from storage (rid=#1:38): rebuilt it from scratch [OIndexFullText]{db=cg_connections} Cannot rebuild index 'cg_sps_org.name' from storage (rid=#1:38) because 'com.orientechnologies.orient.core.index.sbtree.local.OSBTreeException: Exception during deletion of sbtree cg_sps_org.name'. The index will be removed in configuration
com.orientechnologies.orient.core.exception.OStorageException: File with name cg_sps_org.name.sbt does not exist in storage cg_connections
	at com.orientechnologies.orient.core.index.hashindex.local.cache.OWOWCache.openFile(OWOWCache.java:249)
	at com.orientechnologies.orient.core.index.hashindex.local.cache.OReadWriteDiskCache.openFile(OReadWriteDiskCache.java:159)
	at com.orientechnologies.orient.core.storage.impl.local.paginated.base.ODurableComponent.openFile(ODurableComponent.java:162)
	at com.orientechnologies.orient.core.index.sbtree.local.OSBTree.load(OSBTree.java:490)
	at com.orientechnologies.orient.core.index.engine.OSBTreeIndexEngine.load(OSBTreeIndexEngine.java:162)
	at com.orientechnologies.orient.core.index.OIndexAbstract.loadFromConfiguration(OIndexAbstract.java:267)
	at com.orientechnologies.orient.core.index.OIndexManagerShared.fromStream(OIndexManagerShared.java:377)
	at com.orientechnologies.orient.core.type.ODocumentWrapperNoClass.reload(ODocumentWrapperNoClass.java:74)
	at com.orientechnologies.orient.core.index.OIndexManagerAbstract.load(OIndexManagerAbstract.java:89)
	at com.orientechnologies.orient.core.index.OIndexManagerAbstract.load(OIndexManagerAbstract.java:53)
	at com.orientechnologies.orient.core.metadata.OMetadataDefault$2.call(OMetadataDefault.java:197)
	at com.orientechnologies.orient.core.metadata.OMetadataDefault$2.call(OMetadataDefault.java:187)
	at com.orientechnologies.common.concur.resource.OSharedContainerImpl.getResource(OSharedContainerImpl.java:57)
	at com.orientechnologies.orient.core.metadata.OMetadataDefault.init(OMetadataDefault.java:186)
	at com.orientechnologies.orient.core.metadata.OMetadataDefault.load(OMetadataDefault.java:77)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.initAtFirstOpen(ODatabaseDocumentTx.java:2687)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.open(ODatabaseDocumentTx.java:255)
	at com.orientechnologies.orient.server.OServer.openDatabase(OServer.java:647)
	at com.orientechnologies.orient.server.OServer.openDatabase(OServer.java:629)
	at com.orientechnologies.orient.server.network.protocol.http.command.OServerCommandAuthenticatedDbAbstract.authenticate(OServerCommandAuthenticatedDbAbstract.java:167)
	at com.orientechnologies.orient.server.network.protocol.http.command.OServerCommandAuthenticatedDbAbstract.beforeExecute(OServerCommandAuthenticatedDbAbstract.java:127)
	at com.orientechnologies.orient.server.network.protocol.http.command.get.OServerCommandGetConnect.beforeExecute(OServerCommandGetConnect.java:50)
	at com.orientechnologies.orient.server.network.protocol.http.ONetworkProtocolHttpAbstract.service(ONetworkProtocolHttpAbstract.java:171)
	at com.orientechnologies.orient.server.network.protocol.http.ONetworkProtocolHttpAbstract.execute(ONetworkProtocolHttpAbstract.java:574)
	at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:69)

2015-06-26 17:00:05:258 INFO  {db=cg_connections} - Rebuilding index cg_connections.cg_sps_org.links__name (estimated 90484 items)... [OIndexRebuildOutputListener]
```

Lol, am I right?

**Comment by optimuspaul** [comment]
I don't think that the lucene plugin I installed was right.  The one I had with 2.0.5 was a different binary and didn't blow up like this. I pulled one down from https://github.com/orientechnologies/orientdb-lucene but that one was pretty old.  Where do I get the one that will work with 2.0.11? and Why is it no longer in the release?

**Comment by optimuspaul** [comment]
```
orientdb {db=cg_connections}> CREATE INDEX cg_sps_org.website ON cg_sps_org (website) FULLTEXT ENGINE LUCENE


Creating index...
Error: java.lang.AbstractMethodError
```

Lucene indexes don't seem to work on 2.0.11

**Comment by optimuspaul** [comment]
I see the same issue with 2.0.10, all my FULLTEXT indexes are reset to be SBTREE vs Lucene, even when the Lucene plugin exists. Dropping and recreating the indexes made it work, but it should honor both the index type and engine on import.
