### ISSUE TITLE
Lock on Hot Backup

### ISSUE THREAD

**Issue by thiagopm** [orientechnologies/orientdb#4475]
Hi, I'd configurated the backup, but when it started db was locked. Even after backup stopped db continued no answering.

I couldn't get extra info or dump. If it happened again I send you.

Here is the log.

<code>
2015-06-26 14:58:04:194 INFO  {db=ilang} 
- Compressing file adhocgroup.cpm... [OAutomaticBackup$1$2]

2015-06-26 14:58:04:210 INFO  {db=ilang} ok size=65.00KB compressedSize=3648 ratio=95% elapsed=16ms [OAutomaticBackup$1$2]

2015-06-26 14:58:04:241 INFO  {db=ilang} 
- Compressing file adhocgroup.pcl... [OAutomaticBackup$1$2]

2015-06-26 14:58:04:288 INFO  {db=ilang} ok size=385.00KB compressedSize=35165 ratio=92% elapsed=78ms [OAutomaticBackup$1$2]

2015-06-26 14:58:04:288 INFO  {db=ilang} 
- Compressing file announcement.cpm... [OAutomaticBackup$1$2]

2015-06-26 14:58:04:646 INFO  {db=ilang} ok size=897.00KB compressedSize=116281 ratio=88% elapsed=358ms [OAutomaticBackup$1$2]

2015-06-26 14:58:04:646 INFO  {db=ilang} 
- Compressing file announcement.pcl... [OAutomaticBackup$1$2]

2015-06-26 14:58:05:816 INFO  {db=ilang} ok size=10.00MB compressedSize=1202954 ratio=89% elapsed=1170ms [OAutomaticBackup$1$2]

2015-06-26 14:58:05:816 INFO  {db=ilang} 
- Compressing file auditing-config.json... [OAutomaticBackup$1$2]

2015-06-26 14:58:05:816 INFO  {db=ilang} ok size=340b compressedSize=143 ratio=58% elapsed=0ms [OAutomaticBackup$1$2]

2015-06-26 14:58:05:816 INFO  {db=ilang} 
- Compressing file author.cpm... [OAutomaticBackup$1$2]

2015-06-26 14:58:13:959 INFO  {db=ilang} ok size=18.31MB compressedSize=3448209 ratio=83% elapsed=8143ms [OAutomaticBackup$1$2]

2015-06-26 14:58:13:959 INFO  {db=ilang} 
- Compressing file author.pcl... [OAutomaticBackup$1$2]

2015-06-26 14:58:33:740 INFO  {db=ilang} ok size=200.25MB compressedSize=24534114 ratio=89% elapsed=19781ms [OAutomaticBackup$1$2]

2015-06-26 14:58:33:740 INFO  {db=ilang} 
- Compressing file ClassDiscipline.ClassDisciplineId.sbt... [OAutomaticBackup$1$2]

2015-06-26 14:58:33:942 INFO  {db=ilang} ok size=1.19MB compressedSize=396877 ratio=69% elapsed=202ms [OAutomaticBackup$1$2]

2015-06-26 14:58:33:942 INFO  {db=ilang} 
- Compressing file classdiscipline.cpm... [OAutomaticBackup$1$2]

2015-06-26 14:58:34:192 INFO  {db=ilang} ok size=705.00KB compressedSize=91148 ratio=88% elapsed=250ms [OAutomaticBackup$1$2]

2015-06-26 14:58:34:192 INFO  {db=ilang} 
- Compressing file classdiscipline.pcl... [OAutomaticBackup$1$2]

2015-06-26 14:58:39:636 INFO  {db=ilang} ok size=61.50MB compressedSize=9536192 ratio=86% elapsed=5444ms [OAutomaticBackup$1$2]

2015-06-26 14:58:39:636 INFO  {db=ilang} 
- Compressing file collections_12.sbc... [OAutomaticBackup$1$2]

2015-06-26 14:58:39:636 INFO  {db=ilang} error: java.io.IOException: The process cannot access the file because another process has locked a portion of the file [OAutomaticBackup$1$2]{db=ilang} Cannot compress file: D:\orientdb-community-2.1-SNAPSHOT\databases\ilang\collections_12.sbc
java.io.IOException: The process cannot access the file because another process has locked a portion of the file
	at java.io.FileInputStream.readBytes(Native Method)
	at java.io.FileInputStream.read(FileInputStream.java:246)
	at com.orientechnologies.common.io.OIOUtils.copyStream(OIOUtils.java:165)
	at com.orientechnologies.orient.core.compression.impl.OZIPCompressionUtil.addFolder(OZIPCompressionUtil.java:142)
	at com.orientechnologies.orient.core.compression.impl.OZIPCompressionUtil.addFolder(OZIPCompressionUtil.java:120)
	at com.orientechnologies.orient.core.compression.impl.OZIPCompressionUtil.compressDirectory(OZIPCompressionUtil.java:51)
	at com.orientechnologies.orient.core.storage.impl.local.paginated.OLocalPaginatedStorage.backup(OLocalPaginatedStorage.java:155)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.backup(ODatabaseDocumentTx.java:2669)
	at com.orientechnologies.orient.server.handler.OAutomaticBackup$1.run(OAutomaticBackup.java:159)
	at java.util.TimerThread.mainLoop(Timer.java:555)
	at java.util.TimerThread.run(Timer.java:505)
{db=ilang} [OAutomaticBackup] - Error on exporting database 'plocal:D:/orientdb-community-2.1-SNAPSHOT/databases/ilang' to file: backup/ilang-20150626145803.zip
java.io.IOException: The process cannot access the file because another process has locked a portion of the file
	at java.io.FileInputStream.readBytes(Native Method)
	at java.io.FileInputStream.read(FileInputStream.java:246)
	at com.orientechnologies.common.io.OIOUtils.copyStream(OIOUtils.java:165)
	at com.orientechnologies.orient.core.compression.impl.OZIPCompressionUtil.addFolder(OZIPCompressionUtil.java:142)
	at com.orientechnologies.orient.core.compression.impl.OZIPCompressionUtil.addFolder(OZIPCompressionUtil.java:120)
	at com.orientechnologies.orient.core.compression.impl.OZIPCompressionUtil.compressDirectory(OZIPCompressionUtil.java:51)
	at com.orientechnologies.orient.core.storage.impl.local.paginated.OLocalPaginatedStorage.backup(OLocalPaginatedStorage.java:155)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.backup(ODatabaseDocumentTx.java:2669)
	at com.orientechnologies.orient.server.handler.OAutomaticBackup$1.run(OAutomaticBackup.java:159)
	at java.util.TimerThread.mainLoop(Timer.java:555)
	at java.util.TimerThread.run(Timer.java:505)

2015-06-26 14:58:39:870 INFO  [OAutomaticBackup] Backup finished: 0 ok, 1 errors [OAutomaticBackup$1]
</code>

**Comment by lvca** [comment]
Did you use the backup.sh? Do you have installed linux containers? In this way you'd have no lock on

**Comment by thiagopm** [comment]
It was configured on OAutomaticBackup.
I do not have installed linux containers, we are running on windows, should we install anything more? 
Other strange thing is that configuration "firstTime", didn't work well, backup started when we started OrientDB service.

**Comment by lvca** [comment]
Please could you provide the snippet of your backup plugin configuration?

**Comment by thiagopm** [comment]
<handler class="com.orientechnologies.orient.server.handler.OAutomaticBackup">
            <parameters>
                <parameter value="true" name="enabled"/>
		<parameter value="1d" name="delay"/>
                <parameter value="05:00:00" name="firstTime"/>
                <parameter value="d:/Orientdb_backup" name="target.directory"/>
                <parameter value="${DBNAME}-${DATE:yyyyMMddHHmmss}.zip" name="target.fileName"/>
                <parameter value="1" name="compressionLevel"/>
                <parameter value="1048576" name="bufferSize"/>
                <parameter value="" name="db.include"/>
                <parameter value="" name="db.exclude"/>
            </parameters>
        </handler>

**Comment by thiagopm** [comment]
<code>
<handler class="com.orientechnologies.orient.server.handler.OAutomaticBackup">
            <parameters>
                <parameter value="false" name="enabled"/>
				<parameter value="1d" name="delay"/>
                <parameter value="05:03:00" name="firstTime"/>
                <parameter value="d:/Orientdb_backup" name="target.directory"/>
                <parameter value="${DBNAME}-${DATE:yyyyMMddHHmmss}.zip" name="target.fileName"/>
                <parameter value="1" name="compressionLevel"/>
                <parameter value="1048576" name="bufferSize"/>
                <parameter value="" name="db.include"/>
                <parameter value="" name="db.exclude"/>
            </parameters>
        </handler>
</code>

**Comment by thiagopm** [comment]
<!--handler class="com.orientechnologies.orient.server.handler.OAutomaticBackup">
		<!--parameters>
			<!--parameter value="false" name="enabled"/>
			<!--parameter value="1d" name="delay"/>
			<!--parameter value="05:03:00" name="firstTime"/>
			<!--parameter value="d:/Orientdb_backup" name="target.directory"/>
			<!--parameter value="${DBNAME}-${DATE:yyyyMMddHHmmss}.zip" name="target.fileName"/>
			<!--parameter value="1" name="compressionLevel"/>
			<!--parameter value="1048576" name="bufferSize"/>
			<!--parameter value="" name="db.include"/>
			<!--parameter value="" name="db.exclude"/>
		<!--/parameters>
	<!--/handler>

**Comment by tglman** [comment]
Fixed by this commit: https://github.com/orientechnologies/orientdb/commit/85ae26c736540282420098f8e4f3be641327f2f4 closing
