### ISSUE TITLE
Error on loading resource /studio/scripts/scripts.js seem to have caused it to crash and burn

### ISSUE THREAD

**Issue by shekhei** [orientechnologies/orientdb#4494]
My orientdb instance(2.0.10) was found dead this morning, and in the log, it said this

```
Error on loading resource /studio/scripts/scripts.js
java.net.SocketException: Broken pipe
        at java.net.SocketOutputStream.socketWrite0(Native Method)
        at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:109)
        at java.net.SocketOutputStream.write(SocketOutputStream.java:153)
        at java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:82)
        at java.io.BufferedOutputStream.write(BufferedOutputStream.java:95)
        at com.orientechnologies.orient.server.network.protocol.http.OHttpResponse.sendStream(OHttpResponse.java:457)
        at com.orientechnologies.orient.server.network.protocol.http.OHttpResponse.sendStream(OHttpResponse.java:422)
        at com.orientechnologies.orient.server.network.protocol.http.command.get.OServerCommandGetStaticContent.execute(OServerCommandGetStaticContent.java:134)
        at com.orientechnologies.orient.server.network.protocol.http.ONetworkProtocolHttpAbstract.service(ONetworkProtocolHttpAbstract.java:174)
        at com.orientechnologies.orient.server.network.protocol.http.ONetworkProtocolHttpAbstract.execute(ONetworkProtocolHttpAbstract.java:574)
        at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:69)
```

I am unsure what might this actually be, could anybody perhaps enlighten me?

**Comment by maggiolo00** [comment]
This is the only log that you have?

**Comment by shekhei** [comment]
@maggiolo00 Unfortunately yes, that's the only log I got.

There wasnt anything else, right after this, it just kinda died.

**Comment by maggiolo00** [comment]
@shekhei  i do not think that is the error that made your ODB server crash

**Comment by shekhei** [comment]
@maggiolo00 I kinda doubt so too, just couldn't find the actual reason, didnt appear anymore after that day.
