### ISSUE TITLE
StringIndexOutOfBoundsException while rebuilding indexes on startup (Orient DB v2.1 RC4)

### ISSUE THREAD

**Issue by jamieb22** [orientechnologies/orientdb#4503]
2015-07-03 07:06:31.417 ERROR - {db=..} Exception during index v_statistic.OID creation.
com.orientechnologies.orient.core.index.OIndexException: Error on rebuilding the index for clusters: [v_statistic]
	at com.orientechnologies.orient.core.index.OIndexAbstract.rebuild(OIndexAbstract.java:438)
	at com.orientechnologies.orient.core.index.OIndexAbstract.create(OIndexAbstract.java:238)
	at com.orientechnologies.orient.core.index.OIndexOneValue.create(OIndexOneValue.java:128)
	at com.orientechnologies.orient.core.index.OIndexOneValue.create(OIndexOneValue.java:45)
	at com.orientechnologies.orient.core.index.OIndexManagerShared.createIndex(OIndexManagerShared.java:169)
	at com.orientechnologies.orient.core.index.OIndexManagerProxy.createIndex(OIndexManagerProxy.java:79)
	at com.orientechnologies.orient.core.metadata.schema.OClassImpl.createIndex(OClassImpl.java:1676)
	at com.orientechnologies.orient.core.metadata.schema.OClassImpl.createIndex(OClassImpl.java:1648)
	at com.orientechnologies.orient.core.metadata.schema.OClassImpl.createIndex(OClassImpl.java:1638)
	at com.orientechnologies.orient.core.metadata.schema.OClassImpl.createIndex(OClassImpl.java:1634)
	at com.orientechnologies.orient.core.metadata.schema.OClassAbstractDelegate.createIndex(OClassAbstractDelegate.java:346)
	at com.tinkerpop.blueprints.impls.orient.OrientElementType.access$301(OrientElementType.java:35)
	at com.tinkerpop.blueprints.impls.orient.OrientElementType$4.call(OrientElementType.java:80)
	at com.tinkerpop.blueprints.impls.orient.OrientElementType$4.call(OrientElementType.java:77)
	at com.tinkerpop.blueprints.impls.orient.OrientBaseGraph.executeOutsideTx(OrientBaseGraph.java:1739)
	at com.tinkerpop.blueprints.impls.orient.OrientElementType.createIndex(OrientElementType.java:77)
	at com.stimulus.archiva.el.c(MailArchiva:358)
	at com.stimulus.archiva.el.a(MailArchiva:296)
	at com.stimulus.archiva.ek.a(MailArchiva:86)
	at com.stimulus.archiva.database.DatabaseService.b(MailArchiva:306)
	at com.stimulus.archiva.domain.bl$a.run(MailArchiva:163)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.StringIndexOutOfBoundsException: String index out of range: -40
	at java.lang.String.checkBounds(String.java:371)
	at java.lang.String.<init>(String.java:415)
	at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinaryV0.stringFromBytes(ORecordSerializerBinaryV0.java:796)
	at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinaryV0.readString(ORecordSerializerBinaryV0.java:753)
	at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinaryV0.readSingleValue(ORecordSerializerBinaryV0.java:302)
	at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinaryV0.deserializePartial(ORecordSerializerBinaryV0.java:141)
	at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinary.fromStream(ORecordSerializerBinary.java:72)
	at com.orientechnologies.orient.core.record.impl.ODocument.deserializeFields(ODocument.java:1755)
	at com.orientechnologies.orient.core.record.impl.ODocument.checkForFields(ODocument.java:2332)
	at com.orientechnologies.orient.core.record.impl.ODocument.rawField(ODocument.java:760)
	at com.orientechnologies.orient.core.record.impl.ODocument.field(ODocument.java:785)
	at com.orientechnologies.orient.core.index.OPropertyIndexDefinition.getDocumentValueToIndex(OPropertyIndexDefinition.java:76)
	at com.orientechnologies.orient.core.index.OIndexAbstract.indexCluster(OIndexAbstract.java:1025)
	at com.orientechnologies.orient.core.index.OIndexAbstract.rebuild(OIndexAbstract.java:420)
	... 23 common frames omitted

**Comment by laa** [comment]
Already fixed in 2.1
