### ISSUE TITLE
OStorageException Exception during index creation on startup (OrientDB 2.1-rc4)

### ISSUE THREAD

**Issue by jamieb22** [orientechnologies/orientdb#4504]
-07-03 07:06:17.518 ERROR - {db=archiva$incdreams} Exception during index v_blob.mgn creation.
com.orientechnologies.orient.core.exception.OStorageException: null
        at com.orientechnologies.orient.core.index.hashindex.local.OLocalHashTable.create(OLocalHashTable.java:180)
        at com.orientechnologies.orient.core.index.engine.OHashTableIndexEngine.create(OHashTableIndexEngine.java:108)
        at com.orientechnologies.orient.core.index.OIndexAbstract.create(OIndexAbstract.java:235)
        at com.orientechnologies.orient.core.index.OIndexMultiValues.create(OIndexMultiValues.java:235)
        at com.orientechnologies.orient.core.index.OIndexMultiValues.create(OIndexMultiValues.java:52)
        at com.orientechnologies.orient.core.index.OIndexManagerShared.createIndex(OIndexManagerShared.java:169)
        at com.orientechnologies.orient.core.index.OIndexManagerProxy.createIndex(OIndexManagerProxy.java:79)
        at com.orientechnologies.orient.core.metadata.schema.OClassImpl.createIndex(OClassImpl.java:1676)
        at com.orientechnologies.orient.core.metadata.schema.OClassImpl.createIndex(OClassImpl.java:1648)
        at com.orientechnologies.orient.core.metadata.schema.OClassImpl.createIndex(OClassImpl.java:1638)
        at com.orientechnologies.orient.core.metadata.schema.OClassImpl.createIndex(OClassImpl.java:1634)
        at com.orientechnologies.orient.core.metadata.schema.OClassAbstractDelegate.createIndex(OClassAbstractDelegate.java:346)
        at com.tinkerpop.blueprints.impls.orient.OrientElementType.access$301(OrientElementType.java:35)
        at com.tinkerpop.blueprints.impls.orient.OrientElementType$4.call(OrientElementType.java:80)
        at com.tinkerpop.blueprints.impls.orient.OrientElementType$4.call(OrientElementType.java:77)
        at com.tinkerpop.blueprints.impls.orient.OrientBaseGraph.executeOutsideTx(OrientBaseGraph.java:1739)
        at com.tinkerpop.blueprints.impls.orient.OrientElementType.createIndex(OrientElementType.java:77)
        at com.stimulus.archiva.el.c(MailArchiva:358)
        at com.stimulus.archiva.el.a(MailArchiva:296)
        at com.stimulus.archiva.ek.a(MailArchiva:86)
        at com.stimulus.archiva.database.DatabaseService.b(MailArchiva:306)
        at com.stimulus.archiva.domain.bl$a.run(MailArchiva:163)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
Caused by: com.orientechnologies.orient.core.exception.OStorageException: File with name v_blob.mgn.hib already exists in storage archiva$incdreams
        at com.orientechnologies.orient.core.index.hashindex.local.cache.OWOWCache.addFile(OWOWCache.java:298)
        at com.orientechnologies.orient.core.index.hashindex.local.cache.O2QCache.addFile(O2QCache.java:115)
        at com.orientechnologies.orient.core.storage.impl.local.paginated.base.ODurableComponent.addFile(ODurableComponent.java:158)
        at com.orientechnologies.orient.core.index.hashindex.local.OLocalHashTable.create(OLocalHashTable.java:164)
        ... 24 common frames omitted

**Comment by laa** [comment]
Already fixed in 2.1
