### ISSUE TITLE
Whitespace in front of SELECT command causes OCommandExecutorNotFoundException

### ISSUE THREAD

**Issue by alip2890** [orientechnologies/orientdb#4517]
I crafted this query and executed it using pyorient:

    init_client().query("""
        SELECT active, inventoried_at, inventory_ids, title,
        OUT('InventoriedAt')[0] as Location,
        OUT('IsCaredBy')[0] AS CaredBy,
        OUT('InventoriedBy')[0] AS Creator from BookInventoryItem
        WHERE @rid = {}
        """.format(rid))

init_client is a convenience method which returns OrientDB instance and initializes it, if necessary. Upon running this code, exception occurs:

    Traceback (most recent call last):
      File "/home/apapsch/PycharmProjects/inventar/inventory/ui.py", line 117, in item_activated_slot
        dat = get_book_data(index.data(Qt.UserRole))
      File "/home/apapsch/PycharmProjects/inventar/inventory/model.py", line 130, in get_book_data
        """.format(rid))[0]
      File "/usr/lib/python3.4/site-packages/pyorient/orient.py", line 252, in query
        .prepare(( QUERY_SYNC, ) + args).send().fetch_response()
      File "/usr/lib/python3.4/site-packages/pyorient/messages/commands.py", line 144, in fetch_response
        super( CommandMessage, self ).fetch_response()
      File "/usr/lib/python3.4/site-packages/pyorient/messages/base.py", line 216, in fetch_response
        self._decode_all()
      File "/usr/lib/python3.4/site-packages/pyorient/messages/base.py", line 200, in _decode_all
        self._decode_header()
      File "/usr/lib/python3.4/site-packages/pyorient/messages/base.py", line 181, in _decode_header
        [ exception_message.decode( 'utf8' ) ]
    pyorient.exceptions.PyOrientCommandException: com.orientechnologies.orient.core.command.OCommandExecutorNotFoundException - Cannot find a command executor for the command request: sql.
        SELECT active, inventoried_at, inventory_ids, title,
        OUT('InventoriedAt')[0] as Location,
        OUT('IsCaredBy')[0] AS CaredBy,
        OUT('InventoriedBy')[0] AS Creator from BookInventoryItem
        WHERE @rid = #19:12

To get this query run successfully, I had to move SELECT directly after """:

    init_client().query("""SELECT

instead of

    init_client().query("""
    SELECT

For now I'll not indent the first line, but it would be nice if whitespace in front of command would be ignored.

**Comment by luigidellaquila** [comment]
fixed in develop branch
