### ISSUE TITLE
 File flush was abnormally terminated (OrientDB 2.1-rc4) bug

### ISSUE THREAD

**Issue by jamieb22** [orientechnologies/orientdb#4520]
com.orientechnologies.common.exception.OException: File flush was abnormally terminated
	at com.orientechnologies.orient.core.index.hashindex.local.cache.OWOWCache.flush(OWOWCache.java:560) ~[orientdb-core-2.1-rc4.jar:2.1-rc4]
	at com.orientechnologies.orient.core.index.hashindex.local.cache.OWOWCache.flush(OWOWCache.java:566) ~[orientdb-core-2.1-rc4.jar:2.1-rc4]
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.makeFullCheckpoint(OAbstractPaginatedStorage.java:1380) ~[orientdb-core-2.1-rc4.jar:2.1-rc4]
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.synch(OAbstractPaginatedStorage.java:1031) ~[orientdb-core-2.1-rc4.jar:2.1-rc4]
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.checkLowDiskSpaceAndFullCheckpointRequests(OAbstractPaginatedStorage.java:2428) ~[orientdb-core-2.1-rc4.jar:2.1-rc4]
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.commit(OAbstractPaginatedStorage.java:918) ~[orientdb-core-2.1-rc4.jar:2.1-rc4]
	at com.orientechnologies.orient.core.tx.OTransactionOptimistic.doCommit(OTransactionOptimistic.java:590) ~[orientdb-core-2.1-rc4.jar:2.1-rc4]
	at com.orientechnologies.orient.core.tx.OTransactionOptimistic.commit(OTransactionOptimistic.java:145) ~[orientdb-core-2.1-rc4.jar:2.1-rc4]
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.commit(ODatabaseDocumentTx.java:2548) ~[orientdb-core-2.1-rc4.jar:2.1-rc4]
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.commit(ODatabaseDocumentTx.java:2517) ~[orientdb-core-2.1-rc4.jar:2.1-rc4]
	at com.tinkerpop.blueprints.impls.orient.OrientTransactionalGraph.commit(OrientTransactionalGraph.java:161) ~[orientdb-graphdb-2.1-rc4.jar:2.1-rc4]
	at com.stimulus.archiva.ek.a(MailArchiva:819) ~[ek.class:na]
	at com.stimulus.archiva.fa.a(MailArchiva:128) ~[fa.class:na]
	at com.stimulus.archiva.ns.run(MailArchiva:459) ~[ns.class:na]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471) [na:1.7.0_75]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:304) [na:1.7.0_75]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:178) [na:1.7.0_75]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [na:1.7.0_75]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [na:1.7.0_75]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [na:1.7.0_75]
	at java.lang.Thread.run(Thread.java:745) [na:1.7.0_75]
Caused by: java.util.concurrent.ExecutionException: java.io.IOException: Stream Closed
	at java.util.concurrent.FutureTask.report(FutureTask.java:122) [na:1.7.0_75]
	at java.util.concurrent.FutureTask.get(FutureTask.java:188) [na:1.7.0_75]
	at com.orientechnologies.orient.core.index.hashindex.local.cache.OWOWCache.flush(OWOWCache.java:555) ~[orientdb-core-2.1-rc4.jar:2.1-rc4]
	... 20 common frames omitted
Caused by: java.io.IOException: Stream Closed
	at java.io.RandomAccessFile.length(Native Method) ~[na:1.7.0_75]
	at com.orientechnologies.orient.core.storage.fs.OFileClassic.write(OFileClassic.java:213) ~[orientdb-core-2.1-rc4.jar:2.1-rc4]
	at com.orientechnologies.orient.core.index.hashindex.local.cache.OWOWCache.flushPage(OWOWCache.java:1106) ~[orientdb-core-2.1-rc4.jar:2.1-rc4]
	at com.orientechnologies.orient.core.index.hashindex.local.cache.OWOWCache.access$2500(OWOWCache.java:58) ~[orientdb-core-2.1-rc4.jar:2.1-rc4]
	at com.orientechnologies.orient.core.index.hashindex.local.cache.OWOWCache$FileFlushTask.flushRing(OWOWCache.java:1522) ~[orientdb-core-2.1-rc4.jar:2.1-rc4]
	at com.orientechnologies.orient.core.index.hashindex.local.cache.OWOWCache$FileFlushTask.call(OWOWCache.java:1499) ~[orientdb-core-2.1-rc4.jar:2.1-rc4]
	at com.orientechnologies.orient.core.index.hashindex.local.cache.OWOWCache$FileFlushTask.call(OWOWCache.java:1487) ~[orientdb-core-2.1-rc4.jar:2.1-rc4]
	at java.util.concurrent.FutureTask.run(FutureTask.java:262) [na:1.7.0_75]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:178) [na:1.7.0_75]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:292) [na:1.7.0_75]
	... 3 common frames omitted

**Comment by laa** [comment]
@jamieb22 I have sent files with additional logs to fix this issue did you receive them ?

**Comment by laa** [comment]
I have sent them to Valentin

**Comment by laa** [comment]
Fixed in RC6 version which will be released today.
