### ISSUE TITLE
Console command drop database throws ODatabaseException and runs in infinite loop

### ISSUE THREAD

**Issue by nagarajasr** [orientechnologies/orientdb#4521]
OrientDB version - 2.1-rc4

steps to reproduce

```sql
$ ./bin/console.sh 
OrientDB console v.2.1-rc4 (build UNKNOWN@r; 2015-06-30 04:18:12+0000) www.orientdb.com
Type 'help' to display all the supported commands.
2015-07-07 14:48:07:273 WARNI Not enough physical memory available for DISKCACHE: 1,543MB (heap=494MB). Set lower Maximum Heap (-Xmx setting on JVM) and restart OrientDB. Now running with DISKCACHE=256MB [orientechnologies]
Installing extensions for GREMLIN language v.2.6.0

orientdb> create database remote:localhost/testdb root password plocal
Creating database [remote:localhost/testdb] using the storage type [plocal]...
Connecting to database [remote:localhost/testdb] with user 'admin'...OK
Database created successfully.

Current database is: remote:localhost/testdb

orientdb {db=testdb}> drop database remote:localhost/testdb root password

Disconnecting from remote server [remote:localhost/testdb]...
OK
Disconnecting from the database [testdb]...
Error: com.orientechnologies.orient.core.exception.ODatabaseException: Database instance is not set in current thread. Assure to set it with: ODatabaseRecordThreadLocal.INSTANCE.set(db);

Error on reading console input: drop database remote:localhost/testdb root password
com.orientechnologies.orient.core.exception.ODatabaseException: Database instance is not set in current thread. Assure to set it with: ODatabaseRecordThreadLocal.INSTANCE.set(db);
        at com.orientechnologies.orient.core.db.ODatabaseRecordThreadLocal.get(ODatabaseRecordThreadLocal.java:52)
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.checkIfActive(ODatabaseDocumentTx.java:3090)
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.getTransaction(ODatabaseDocumentTx.java:1490)
        at com.orientechnologies.orient.console.OConsoleDatabaseApp.getContext(OConsoleDatabaseApp.java:2195)
        at com.orientechnologies.orient.console.OConsoleDatabaseApp.getPrompt(OConsoleDatabaseApp.java:2210)
        at com.orientechnologies.common.console.OConsoleApplication.run(OConsoleApplication.java:128)
        at com.orientechnologies.orient.graph.console.OGremlinConsole.main(OGremlinConsole.java:62)

Error on reading console input: drop database remote:localhost/testdb root password
com.orientechnologies.orient.core.exception.ODatabaseException: Database instance is not set in current thread. Assure to set it with: ODatabaseRecordThreadLocal.INSTANCE.set(db);
        at com.orientechnologies.orient.core.db.ODatabaseRecordThreadLocal.get(ODatabaseRecordThreadLocal.java:52)
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.checkIfActive(ODatabaseDocumentTx.java:3090)
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.getTransaction(ODatabaseDocumentTx.java:1490)
        at com.orientechnologies.orient.console.OConsoleDatabaseApp.getContext(OConsoleDatabaseApp.java:2195)
        at com.orientechnologies.orient.console.OConsoleDatabaseApp.getPrompt(OConsoleDatabaseApp.java:2210)
        at com.orientechnologies.common.console.OConsoleApplication.run(OConsoleApplication.java:128)
        at com.orientechnologies.orient.graph.console.OGremlinConsole.main(OGremlinConsole.java:62)


```

at this point the console goes into an infinite loop printing the same exception stack trace over and over

**Comment by lvca** [comment]
Did you already try with 2.1-rc5?

**Comment by nagarajasr** [comment]
Just tried with 2.1-rc5 now, the issue still persists.

**Comment by nagarajasr** [comment]
@lvca i am still seeing this error, but not consistently - 2.1-rc6

(i realize i am using the drop database command incorrectly, but it shouldn't cause the console to throw this error and run infinite loop)

```

orientdb> connect remote:localhost/testdb root passwd

Connecting to database [remote:localhost/testdb] with user 'root'...OK
orientdb {db=testdb}> drop database testdb


Cannot drop a remote database without connecting to the server with a valid server's user
orientdb {db=testdb}> drop database testdb root passwd

Error: com.orientechnologies.orient.core.exception.ODatabaseException: Error on opening database 'testdb'

Error: com.orientechnologies.orient.core.exception.OConfigurationException: Error in database URL: the engine was not specified. Syntax is: <engine>:<db-type>:<db-name>[?<db-param>=<db-value>[&]]*. URL was: testdb

Error on reading console input: drop database testdb root passwd
java.lang.IllegalStateException: Current database instance (com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx@1b97680c) is not active on current thread (Thread[main,5,main]). Current active database is: com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx@712ff9fa
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.checkIfActive(ODatabaseDocumentTx.java:3133)
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.getTransaction(ODatabaseDocumentTx.java:1504)
        at com.orientechnologies.orient.console.OConsoleDatabaseApp.getContext(OConsoleDatabaseApp.java:2196)
        at com.orientechnologies.orient.console.OConsoleDatabaseApp.getPrompt(OConsoleDatabaseApp.java:2211)
        at com.orientechnologies.common.console.OConsoleApplication.run(OConsoleApplication.java:121)
        at com.orientechnologies.orient.graph.console.OGremlinConsole.main(OGremlinConsole.java:64)

Error on reading console input: drop database testdb root infy1
java.lang.IllegalStateException: Current database instance (com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx@1b97680c) is not active on current thread (Thread[main,5,main]). Current active database is: com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx@712ff9fa
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.checkIfActive(ODatabaseDocumentTx.java:3133)
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.getTransaction(ODatabaseDocumentTx.java:1504)
        at com.orientechnologies.orient.console.OConsoleDatabaseApp.getContext(OConsoleDatabaseApp.java:2196)
        at com.orientechnologies.orient.console.OConsoleDatabaseApp.getPrompt(OConsoleDatabaseApp.java:2211)
        at com.orientechnologies.common.console.OConsoleApplication.run(OConsoleApplication.java:121)
        at com.orientechnologies.orient.graph.console.OGremlinConsole.main(OGremlinConsole.java:64)

Error on reading console input: drop database testdb root infy1
java.lang.IllegalStateException: Current database instance (com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx@1b97680c) is not active on current thread (Thread[main,5,main]). Current active database is: com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx@712ff9fa
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.checkIfActive(ODatabaseDocumentTx.java:3133)
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.getTransaction(ODatabaseDocumentTx.java:1504)
        at com.orientechnologies.orient.console.OConsoleDatabaseApp.getContext(OConsoleDatabaseApp.java:2196)
        at com.orientechnologies.orient.console.OConsoleDatabaseApp.getPrompt(OConsoleDatabaseApp.java:2211)
        at com.orientechnologies.common.console.OConsoleApplication.run(OConsoleApplication.java:121)
        at com.orientechnologies.orient.graph.console.OGremlinConsole.main(OGremlinConsole.java:64)

```

**Comment by lvca** [comment]
Fixed, thanks.
