### ISSUE TITLE
Migrate to 2.1-RC5

### ISSUE THREAD

**Issue by henryzhao81** [orientechnologies/orientdb#4526]
Today I tried to migrate database to RC5 with existing database. But when I start database, I got following exception, 

2015-07-07 23:39:35:383 INFO  Installing Script interpreter. WARN: authenticated clients can execute any kind of code into the server by using the following allowed languages: [sql] [OServerSideScriptInterpreter]{db=pharos} Error during load of index skinTempUnique .
com.orientechnologies.orient.core.exception.OStorageException: File with id 1818527922414 does not exist.
        at com.orientechnologies.orient.core.index.hashindex.local.cache.OWOWCache.openFile(OWOWCache.java:460)
        at com.orientechnologies.orient.core.index.hashindex.local.cache.O2QCache.openFile(O2QCache.java:154)
        at com.orientechnologies.orient.core.storage.impl.local.paginated.base.ODurableComponent.openFile(ODurableComponent.java:173)
        at com.orientechnologies.orient.core.index.hashindex.local.OLocalHashTable20.load(OLocalHashTable20.java:687)
        at com.orientechnologies.orient.core.index.engine.OHashTableIndexEngine.load(OHashTableIndexEngine.java:131)
        at com.orientechnologies.orient.core.index.OIndexAbstract.loadFromConfiguration(OIndexAbstract.java:278)
        at com.orientechnologies.orient.core.index.OIndexManagerShared.fromStream(OIndexManagerShared.java:379)
        at com.orientechnologies.orient.core.type.ODocumentWrapperNoClass.reload(ODocumentWrapperNoClass.java:74)
        at com.orientechnologies.orient.core.index.OIndexManagerAbstract.load(OIndexManagerAbstract.java:99)
        at com.orientechnologies.orient.core.index.OIndexManagerAbstract.load(OIndexManagerAbstract.java:63)
        at com.orientechnologies.orient.core.metadata.OMetadataDefault$2.call(OMetadataDefault.java:165)
        at com.orientechnologies.orient.core.metadata.OMetadataDefault$2.call(OMetadataDefault.java:155)
        at com.orientechnologies.common.concur.resource.OSharedContainerImpl.getResource(OSharedContainerImpl.java:64)
        at com.orientechnologies.orient.core.storage.OStorageAbstract.getResource(OStorageAbstract.java:113)
        at com.orientechnologies.orient.core.metadata.OMetadataDefault.init(OMetadataDefault.java:154)
        at com.orientechnologies.orient.core.metadata.OMetadataDefault.load(OMetadataDefault.java:75)
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.initAtFirstOpen(ODatabaseDocumentTx.java:2834)
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.open(ODatabaseDocumentTx.java:260)
        at com.proteus.orientdb.facade.factory.DatabaseFactory.getLocalDatabase(DatabaseFactory.java:302)
        at com.proteus.orientdb.api.security.DataSync.loadRawClasses(DataSync.java:159)
        at com.proteus.orientdb.api.security.DataSync.<init>(DataSync.java:148)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:408)
        at java.lang.Class.newInstance(Class.java:438)
        at com.orientechnologies.orient.server.OServer.registerPlugins(OServer.java:891)
        at com.orientechnologies.orient.server.OServer.activate(OServer.java:272)
        at com.orientechnologies.orient.server.OServerMain.main(OServerMain.java:41)

2015-07-07 23:39:36:214 WARNI {db=pharos} Cannot load index 'skinTempUnique' from storage (rid=#1:105): rebuilt it from scratch [OIndexUnique]
2015-07-07 23:39:36:217 SEVER {db=pharos} Error during index skinTempUnique delete . [OIndexUnique]{db=pharos} Cannot rebuild index 'skinTempUnique' from storage (rid=#1:105) because 'com.orientechnologies.orient.core.index.OIndexException: Error on rebuilding the index for clusters: [skintemp]'. The index will be removed in configuration
com.orientechnologies.orient.core.exception.OStorageException: File with id 1818527922414 does not exist.
        at com.orientechnologies.orient.core.index.hashindex.local.cache.OWOWCache.openFile(OWOWCache.java:460)
        at com.orientechnologies.orient.core.index.hashindex.local.cache.O2QCache.openFile(O2QCache.java:154)
        at com.orientechnologies.orient.core.storage.impl.local.paginated.base.ODurableComponent.openFile(ODurableComponent.java:173)
        at com.orientechnologies.orient.core.index.hashindex.local.OLocalHashTable20.load(OLocalHashTable20.java:687)
        at com.orientechnologies.orient.core.index.engine.OHashTableIndexEngine.load(OHashTableIndexEngine.java:131)
        at com.orientechnologies.orient.core.index.OIndexAbstract.loadFromConfiguration(OIndexAbstract.java:278)
        at com.orientechnologies.orient.core.index.OIndexManagerShared.fromStream(OIndexManagerShared.java:379)
        at com.orientechnologies.orient.core.type.ODocumentWrapperNoClass.reload(ODocumentWrapperNoClass.java:74)
        at com.orientechnologies.orient.core.index.OIndexManagerAbstract.load(OIndexManagerAbstract.java:99)
        at com.orientechnologies.orient.core.index.OIndexManagerAbstract.load(OIndexManagerAbstract.java:63)
        at com.orientechnologies.orient.core.metadata.OMetadataDefault$2.call(OMetadataDefault.java:165)
        at com.orientechnologies.orient.core.metadata.OMetadataDefault$2.call(OMetadataDefault.java:155)
        at com.orientechnologies.common.concur.resource.OSharedContainerImpl.getResource(OSharedContainerImpl.java:64)
        at com.orientechnologies.orient.core.storage.OStorageAbstract.getResource(OStorageAbstract.java:113)
        at com.orientechnologies.orient.core.metadata.OMetadataDefault.init(OMetadataDefault.java:154)
        at com.orientechnologies.orient.core.metadata.OMetadataDefault.load(OMetadataDefault.java:75)
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.initAtFirstOpen(ODatabaseDocumentTx.java:2834)
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.open(ODatabaseDocumentTx.java:260)
        at com.proteus.orientdb.facade.factory.DatabaseFactory.getLocalDatabase(DatabaseFactory.java:302)
        at com.proteus.orientdb.api.security.DataSync.loadRawClasses(DataSync.java:159)
        at com.proteus.orientdb.api.security.DataSync.<init>(DataSync.java:148)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:408)
        at java.lang.Class.newInstance(Class.java:438)

… …

   Then I try to rebuild index. But when I login to console, I got following error, without login to server, there is no way to rebuild all indexes. Please take a look.

# sh console.sh 

OrientDB console v.2.1-rc5 (build 42) www.orientdb.com
Type 'help' to display all the supported commands.
Installing extensions for GREMLIN language v.2.6.0

orientdb> connect remote:localhost/pharos admin admin

Connecting to database [remote:localhost/pharos] with user 'admin'...
Error: com.orientechnologies.orient.enterprise.channel.binary.OResponseProcessingException: Exception during response processing.

Error: java.lang.AbstractMethodError

**Comment by laa** [comment]
Fixed could you try now ?

**Comment by henryzhao81** [comment]
Looks good, no file not exist issue happened. I still got exception but i think it is lucene jar issue, what's the correct version of lucene jar should i use.  And the fix will merge to rc5 or wait for next version?

**Comment by laa** [comment]
We should wait next version.
