### ISSUE TITLE
Stream Close Exception

### ISSUE THREAD

**Issue by henryzhao81** [orientechnologies/orientdb#4528]
I have experience this issue twice today when using 2.0.11. Don't know what's going at this moment. After restart database, triggering rebuild index. I don't know when this issue could happen again, please help check it.

java.io.IOException: Stream Closed
        at java.io.RandomAccessFile.length(Native Method)
        at com.orientechnologies.orient.core.storage.fs.OFileClassic.write(OFileClassic.java:213)
        at com.orientechnologies.orient.core.index.hashindex.local.cache.OWOWCache.flushPage(OWOWCache.java:1024)
        at com.orientechnologies.orient.core.index.hashindex.local.cache.OWOWCache.access$2000(OWOWCache.java:64)
        at com.orientechnologies.orient.core.index.hashindex.local.cache.OWOWCache$PeriodicFlushTask.iterateBySubRing(OWOWCache.java:1216)
        at com.orientechnologies.orient.core.index.hashindex.local.cache.OWOWCache$PeriodicFlushTask.flushRing(OWOWCache.java:1171)
        at com.orientechnologies.orient.core.index.hashindex.local.cache.OWOWCache$PeriodicFlushTask.run(OWOWCache.java:1147)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Exception during data flush.
java.io.IOException: Stream Closed
        at java.io.RandomAccessFile.length(Native Method)
        at com.orientechnologies.orient.core.storage.fs.OFileClassic.write(OFileClassic.java:213)
        at com.orientechnologies.orient.core.index.hashindex.local.cache.OWOWCache.flushPage(OWOWCache.java:1024)
        at com.orientechnologies.orient.core.index.hashindex.local.cache.OWOWCache.access$2000(OWOWCache.java:64)
        at com.orientechnologies.orient.core.index.hashindex.local.cache.OWOWCache$PeriodicFlushTask.iterateBySubRing(OWOWCache.java:1216)
        at com.orientechnologies.orient.core.index.hashindex.local.cache.OWOWCache$PeriodicFlushTask.flushRing(OWOWCache.java:1171)
        at com.orientechnologies.orient.core.index.hashindex.local.cache.OWOWCache$PeriodicFlushTask.run(OWOWCache.java:1147)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Exception during data flush.
java.io.IOException: Stream Closed
        at java.io.RandomAccessFile.length(Native Method)
        at com.orientechnologies.orient.core.storage.fs.OFileClassic.write(OFileClassic.java:213)
        at com.orientechnologies.orient.core.index.hashindex.local.cache.OWOWCache.flushPage(OWOWCache.java:1024)
        at com.orientechnologies.orient.core.index.hashindex.local.cache.OWOWCache.access$2000(OWOWCache.java:64)
        at com.orientechnologies.orient.core.index.hashindex.local.cache.OWOWCache$PeriodicFlushTask.iterateBySubRing(OWOWCache.java:1216)
        at com.orientechnologies.orient.core.index.hashindex.local.cache.OWOWCache$PeriodicFlushTask.flushRing(OWOWCache.java:1171)
        at com.orientechnologies.orient.core.index.hashindex.local.cache.OWOWCache$PeriodicFlushTask.run(OWOWCache.java:1147)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Exception during data flush.

**Comment by laa** [comment]
Hi, Henry.
About this issue. Is it correct that you restarted database, it was triggered index rebuild and you got this exception ?

**Comment by henryzhao81** [comment]
No, it suddenly happen when database running for a while.

**Comment by laa** [comment]
Fixed in RC6 version which will be released today.
