### ISSUE TITLE
2.2-alpha BUG: importing in-memory database fails through code during indices phase but not console

### ISSUE THREAD

**Issue by zifnab87** [orientechnologies/orientdb#4595]
Hi I wrote some code to import a small dataset in an in-memory database. While the dump is imported in an in-memory database correctly through console - it fails through the following code with error:

I made new dumps after ```repair database``` and ```rebuild index *``` but with only difference that another index has the same error..
```
Total links updated: 1,197

Done. Imported 1,198 records in 2.63 secs



Importing indexes ...
- Index 'Entity.created'...OKError on database import happened just before line 0, column 318147
java.lang.IllegalArgumentException: Index name is missing
	at com.orientechnologies.orient.core.db.tool.ODatabaseImport.importIndexes(ODatabaseImport.java:1367)
	at com.orientechnologies.orient.core.db.tool.ODatabaseImport.importDatabase(ODatabaseImport.java:430)
	at com.nooul.test.integration.InMemoryDatabaseSetup.setup(InMemoryDatabaseSetup.java:44)
	at com.nooul.test.integration.InMemoryDatabaseSetup.main(InMemoryDatabaseSetup.java:15)
Exception in thread "main" com.orientechnologies.orient.core.db.tool.ODatabaseExportException: Error on importing database 'test' from file: D:/temp/orientdb-dump-0.74.gz
	at com.orientechnologies.orient.core.db.tool.ODatabaseImport.importDatabase(ODatabaseImport.java:462)
	at com.nooul.test.integration.InMemoryDatabaseSetup.setup(InMemoryDatabaseSetup.java:44)
	at com.nooul.test.integration.InMemoryDatabaseSetup.main(InMemoryDatabaseSetup.java:15)
Caused by: java.lang.IllegalArgumentException: Index name is missing
	at com.orientechnologies.orient.core.db.tool.ODatabaseImport.importIndexes(ODatabaseImport.java:1367)
	at com.orientechnologies.orient.core.db.tool.ODatabaseImport.importDatabase(ODatabaseImport.java:430)
	... 2 more
```

```java
package com.xxxx.test.integration;

import java.io.IOException;

import com.orientechnologies.orient.client.remote.OServerAdmin;
import com.orientechnologies.orient.core.command.OCommandOutputListener;
import com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx;
import com.orientechnologies.orient.core.db.tool.ODatabaseImport;

public class InMemoryDatabaseSetup {
	
	public static String DB = "test";
	
	public static void main(String args[]){
		setup();
	}
	
	
	
	public static void setup() {
		OServerAdmin serverAdmin;
		try {
			serverAdmin = new OServerAdmin("remote:localhost/"+DB).connect("root", "root");
			if (!serverAdmin.existsDatabase()) {
				serverAdmin.createDatabase(DB, "graph", "memory");
			}
			else {
				serverAdmin.dropDatabase(null);
				serverAdmin.createDatabase(DB, "graph", "memory");
			}
			serverAdmin.close();
		
			ODatabaseDocumentTx db = new ODatabaseDocumentTx("remote:localhost/"+DB);
			db.open("admin", "admin");
			try{
			  OCommandOutputListener listener = new OCommandOutputListener() {
			    @Override
			    public void onMessage(String iText) {
			      System.out.print(iText);
			    }
			  };

			  ODatabaseImport dbImport = new ODatabaseImport(db, "D:/temp/orientdb-dump-0.74.gz", listener);
			  dbImport.importDatabase();
			  dbImport.close();
			} finally {
			  db.close();
			}
			
		} catch (IOException e) {
			e.printStackTrace();
		}
	}
}
```

**Comment by lvca** [comment]
@laa the 2.2-alpha was released a week ago and it's 2.2-SNAPSHOT.

**Comment by laa** [comment]
@lvca what do you mean ?

**Comment by lvca** [comment]
@zifnab87  Please could you retry with 2.1.2 or 2.2-SNAPSHOT ?

**Comment by zifnab87** [comment]
I believe I have this issue even in 2.2-alpha since I am doing that everytime I run my integration tests and it fails

**Comment by zifnab87** [comment]
I updated my code from 2.1.rc5 to 2.1.2 and the problem is resolved :)
