### ISSUE TITLE
plocal Import error

### ISSUE THREAD

**Issue by StarpTech** [orientechnologies/orientdb#4598]
Orientdb 2.0.12

Backup was created by the OAutomaticBackup

I can't restore my database. Please help!

```
java.lang.NumberFormatException: For input string: "?z�"
        at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
        at java.lang.Integer.parseInt(Integer.java:580)
        at com.orientechnologies.orient.core.serialization.serializer.OJSONReader.nextChar(OJSONReader.java:273)
        at com.orientechnologies.orient.core.serialization.serializer.OJSONReader.readNext(OJSONReader.java:174)
        at com.orientechnologies.orient.core.serialization.serializer.OJSONReader.readString(OJSONReader.java:92)
        at com.orientechnologies.orient.core.serialization.serializer.OJSONReader.readString(OJSONReader.java:87)
        at com.orientechnologies.orient.core.serialization.serializer.OJSONReader.readString(OJSONReader.java:83)
        at com.orientechnologies.orient.core.db.tool.ODatabaseImport.importDatabase(ODatabaseImport.java:417)
        at com.orientechnologies.orient.console.OConsoleDatabaseApp.importDatabase(OConsoleDatabaseApp.java:1566)
        at com.orientechnologies.orient.graph.console.OGremlinConsole.importDatabase(OGremlinConsole.java:124)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at com.orientechnologies.common.console.OConsoleApplication.execute(OConsoleApplication.java:383)
        at com.orientechnologies.common.console.OConsoleApplication.executeCommands(OConsoleApplication.java:248)
        at com.orientechnologies.common.console.OConsoleApplication.run(OConsoleApplication.java:137)
        at com.orientechnologies.orient.graph.console.OGremlinConsole.main(OGremlinConsole.java:62)

Error: com.orientechnologies.orient.core.db.tool.ODatabaseExportException: Error on importing database 'testApp' from file: /opt/backup.zip

Error: java.lang.NumberFormatException: For input string: "?z�"

```

**Comment by StarpTech** [comment]
This was my mistake. I used `import` in a wrong way. `restore` was the correct one.
