### ISSUE TITLE
OrientDB 2.0.12 - LinkMap convertLink2Record sets value to null

### ISSUE THREAD

**Issue by guglielmomoretti** [orientechnologies/orientdb#4616]
Hi, 

I have a data structure similar to the one described in [Time Series Use Case](http://orientdb.com/docs/last/Time-series-use-case.html).

When the linkmap contains the following:
![image](https://cloud.githubusercontent.com/assets/2829667/8800546/071cd64a-2fb4-11e5-97dc-6ad5f16d6448.png)

As you can see, the linkedmap contains 3 persistent records and 1 temporary record that will be persisted soon after (when calling tx.commit())

The three records when inside the method convertLink2Record are transformed into NULL values ( **rid.getRecord()** at line 208 of the class **ORecordLazyMap** returns null, even if  record is actually present) as shown below:

![image](https://cloud.githubusercontent.com/assets/2829667/8800612/88c02076-2fb4-11e5-8641-954b2983c8e4.png)

The temporary record is not touched because is not instance of ORID.

If I call reload on each record inside the corresponding HashMap before this point, everything is fine and the **rid.getRecord()** returns the real record instance. However, this software needs to run in an embedded hardware, and due to the fact that I'm using linkedmaps quite a lot, I'd really like avoiding calling this method for each record of each linkedmap.

If I don't call the reload method, this is the exception I get

```com.orientechnologies.orient.core.exception.OTransactionException: Error on transaction commit
14:06:40,967 ERROR [stderr] (pool-11-thread-1) 	at com.orientechnologies.orient.client.remote.OStorageRemote.commitEntry(OStorageRemote.java:2004)
14:06:40,968 ERROR [stderr] (pool-11-thread-1) 	at com.orientechnologies.orient.client.remote.OStorageRemote.commit(OStorageRemote.java:1110)
14:06:40,968 ERROR [stderr] (pool-11-thread-1) 	at com.orientechnologies.orient.client.remote.OStorageRemoteThread.commit(OStorageRemoteThread.java:445)
14:06:40,968 ERROR [stderr] (pool-11-thread-1) 	at com.orientechnologies.orient.core.tx.OTransactionOptimistic.doCommit(OTransactionOptimistic.java:475)
14:06:40,968 ERROR [stderr] (pool-11-thread-1) 	at com.orientechnologies.orient.core.tx.OTransactionOptimistic.commit(OTransactionOptimistic.java:147)
14:06:40,968 ERROR [stderr] (pool-11-thread-1) 	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.commit(ODatabaseDocumentTx.java:2433)
14:06:40,968 ERROR [stderr] (pool-11-thread-1) 	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.commit(ODatabaseDocumentTx.java:2403)
14:06:40,968 ERROR [stderr] (pool-11-thread-1) 	at org.ceia.mdna.collector.processor.EventProcessor.run(EventProcessor.java:230)
14:06:40,968 ERROR [stderr] (pool-11-thread-1) 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
14:06:40,969 ERROR [stderr] (pool-11-thread-1) 	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
14:06:40,969 ERROR [stderr] (pool-11-thread-1) 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
14:06:40,969 ERROR [stderr] (pool-11-thread-1) 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
14:06:40,969 ERROR [stderr] (pool-11-thread-1) 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
14:06:40,969 ERROR [stderr] (pool-11-thread-1) 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
14:06:40,969 ERROR [stderr] (pool-11-thread-1) 	at java.lang.Thread.run(Thread.java:745)
14:06:40,970 ERROR [stderr] (pool-11-thread-1) Caused by: com.orientechnologies.orient.core.exception.OValidationException: The field 'AbstractTreeLoc.dev' has been declared as LINKMAP but contains a null record (probably a deleted record?)
14:06:40,970 ERROR [stderr] (pool-11-thread-1) 	at com.orientechnologies.orient.core.record.impl.ODocument.validateLink(ODocument.java:460)
14:06:40,970 ERROR [stderr] (pool-11-thread-1) 	at com.orientechnologies.orient.core.record.impl.ODocument.validateLinkCollection(ODocument.java:441)
14:06:40,970 ERROR [stderr] (pool-11-thread-1) 	at com.orientechnologies.orient.core.record.impl.ODocument.validateField(ODocument.java:293)
14:06:40,970 ERROR [stderr] (pool-11-thread-1) 	at com.orientechnologies.orient.core.record.impl.ODocument.validate(ODocument.java:1953)
14:06:40,970 ERROR [stderr] (pool-11-thread-1) 	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.save(ODatabaseDocumentTx.java:2255)
14:06:40,970 ERROR [stderr] (pool-11-thread-1) 	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.save(ODatabaseDocumentTx.java:118)
14:06:40,970 ERROR [stderr] (pool-11-thread-1) 	at com.orientechnologies.orient.core.record.impl.ODocument.save(ODocument.java:1727)
14:06:40,971 ERROR [stderr] (pool-11-thread-1) 	at com.orientechnologies.orient.core.record.impl.ODocument.save(ODocument.java:1718)
14:06:40,971 ERROR [stderr] (pool-11-thread-1) 	at com.orientechnologies.orient.core.record.impl.ODocument.save(ODocument.java:76)
14:06:40,971 ERROR [stderr] (pool-11-thread-1) 	at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinaryV0.recursiveLinkSave(ORecordSerializerBinaryV0.java:674)
14:06:40,971 ERROR [stderr] (pool-11-thread-1) 	at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinaryV0.writeOptimizedLink(ORecordSerializerBinaryV0.java:688)
14:06:40,972 ERROR [stderr] (pool-11-thread-1) 	at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinaryV0.writeLinkMap(ORecordSerializerBinaryV0.java:616)
14:06:40,972 ERROR [stderr] (pool-11-thread-1) 	at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinaryV0.writeSingleValue(ORecordSerializerBinaryV0.java:575)
14:06:40,972 ERROR [stderr] (pool-11-thread-1) 	at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinaryV0.serialize(ORecordSerializerBinaryV0.java:261)
14:06:40,972 ERROR [stderr] (pool-11-thread-1) 	at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinary.toStream(ORecordSerializerBinary.java:104)
14:06:40,972 ERROR [stderr] (pool-11-thread-1) 	at com.orientechnologies.orient.core.record.impl.ODocument.toStream(ODocument.java:2100)
14:06:40,972 ERROR [stderr] (pool-11-thread-1) 	at com.orientechnologies.orient.core.record.impl.ODocument.toStream(ODocument.java:695)
14:06:40,973 ERROR [stderr] (pool-11-thread-1) 	at com.orientechnologies.orient.client.remote.OStorageRemote.commitEntry(OStorageRemote.java:1998)
14:06:40,973 ERROR [stderr] (pool-11-thread-1) 	... 14 more```

I'm I doing something by mistake?
Do you have a patch for this or some workaround?

Thanks

Regards
Guglielmo Moretti

**Comment by guglielmomoretti** [comment]
Hi,

I found the problem,

I've two different threads that are using two different connections to the same database.

The first thread persists a vertex in the db and marks it as "not processed"

The second thread asynchronously iterates over all the "not processed" vertices directly by looking them up from the db (always using the java API) and inserts the vertex inside the TimeSerie tree.

This causes the exception above.

I've a simple test case that shows that if I run the described procedure from a single thread, no exception is raised.

As soon as I run the "vertex creation" in, let's say Thread-1, and the tree-insertion in Thread-2, using the same OrientVertex instance, the exception is raised at commit time.

Is this the expected behaviour? 
Is it something related to Caching?

This procedure has been tried with OrientDB 2.0.11, 2.0.12 and the develop branch compiled yesterday.

Regards
Guglielmo

**Comment by lvca** [comment]
The fact the records are null means records don't exist in database. Could you check it? If you want to disable such auto conversion, call `ORecordLazyMap .setAutoConvertToRecord(false)`

**Comment by lvca** [comment]
Are you sharing the same OrientVertex instances across threads?

**Comment by guglielmomoretti** [comment]
Luca,

I'm not sharing the OrientVertex instance, one thread saves the vertex, the other calls getVerticesOfClass() and iterates through them.

Regarding the existence of the record, if I select the same RID that gets translated to null, then I get valid data.

However, by setting ```ORecordLazyMap.setAutoConvertToRecord(false)``` seems to fix this.

Can it be dangerous is any way?

Thanks
Guglielmo

**Comment by lvca** [comment]
It's not dangerous, it's just you have to manual call `rid.getRecord()`
