### ISSUE TITLE
Exceptions on latest OrientDB 2.1-SNAPSHOT and db created previously on 2.0

### ISSUE THREAD

**Issue by PhantomYdn** [orientechnologies/orientdb#4654]
I started to have the following exceptions:

```java
Caused by: com.orientechnologies.orient.core.exception.ODatabaseException: Error on retrieving record #0:2 (cluster: internal)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.executeReadRecord(ODatabaseDocumentTx.java:1771)
	at com.orientechnologies.orient.core.tx.OTransactionNoTx.reloadRecord(OTransactionNoTx.java:122)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.reload(ODatabaseDocumentTx.java:1597)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.reload(ODatabaseDocumentTx.java:120)
	at com.orientechnologies.orient.core.record.ORecordAbstract.reload(ORecordAbstract.java:265)
	... 76 more
Caused by: java.lang.AssertionError
	at com.orientechnologies.orient.core.storage.impl.local.paginated.OPaginatedCluster.readFullEntry(OPaginatedCluster.java:1462)
	at com.orientechnologies.orient.core.storage.impl.local.paginated.OPaginatedCluster.readRecord(OPaginatedCluster.java:559)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.doReadRecord(OAbstractPaginatedStorage.java:1875)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.readRecord(OAbstractPaginatedStorage.java:1613)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.readRecord(OAbstractPaginatedStorage.java:784)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx$SimpleRecordReader.readRecord(ODatabaseDocumentTx.java:3109)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.executeReadRecord(ODatabaseDocumentTx.java:1739)
```
And a lots of exceptions later like this:

```java
com.orientechnologies.orient.core.index.sbtree.local.OSBTreeException: Error during delete of sbtree with name dictionary
	at com.orientechnologies.orient.core.index.sbtree.local.OSBTree.delete(OSBTree.java:434)
	at com.orientechnologies.orient.core.index.engine.OSBTreeIndexEngine.delete(OSBTreeIndexEngine.java:140)
	at com.orientechnologies.orient.core.index.OIndexAbstract.create(OIndexAbstract.java:260)
	at com.orientechnologies.orient.core.index.OIndexOneValue.create(OIndexOneValue.java:128)
	at com.orientechnologies.orient.core.index.OIndexOneValue.create(OIndexOneValue.java:45)
	at com.orientechnologies.orient.core.index.OIndexManagerShared.createIndex(OIndexManagerShared.java:169)
	at com.orientechnologies.orient.core.index.OIndexManagerShared.createIndex(OIndexManagerShared.java:97)
	at com.orientechnologies.orient.core.index.OIndexManagerAbstract.create(OIndexManagerAbstract.java:171)
	at com.orientechnologies.orient.core.metadata.OMetadataDefault$2.call(OMetadataDefault.java:169)
	at com.orientechnologies.orient.core.metadata.OMetadataDefault$2.call(OMetadataDefault.java:156)
	at com.orientechnologies.common.concur.resource.OSharedContainerImpl.getResource(OSharedContainerImpl.java:64)
```

P.S. It was not tested on newly created db on 2.1: and any case we have to have all db from 2.0 be properly handled by new code(?).

**Comment by laa** [comment]
Hi, 
I will remove assertions it was for testing purpose only.

**Comment by laa** [comment]
Fixed

**Comment by PhantomYdn** [comment]
Thanks! Could you please update mvn repository as well? It contains old version..
If it should be done automatically, how often are you guys schedule that?

**Comment by PhantomYdn** [comment]
I see the reason... Code in **develop** is broken:

```java
[ERROR]     constructor InternalError.InternalError(String) is not applicable
      (actual argument CloneNotSupportedException cannot be converted to String by method invocation conversion)
    constructor InternalError.InternalError() is not applicable
      (actual and formal argument lists differ in length)

```

**Comment by jdillon** [comment]
compiles fine under java8 but not java7.  If you guys want to be built java7 and not let new api leak in you might want to setup the animalsniffer.

**Comment by jdillon** [comment]
https://github.com/orientechnologies/orientdb/pull/4662 should make develop compile again on java7, also added https://github.com/orientechnologies/orientdb/pull/4661 to help you guys start using animalsniffer to avoid these sorts of problems in the future.

**Comment by PhantomYdn** [comment]
@jdillon thanks!
@lvca , @laa , please fix codebase for Java7.

**Comment by laa** [comment]
Done )
