### ISSUE TITLE
Error during closing of channel close listener - 2.1-rc6

### ISSUE THREAD

**Issue by nagarajasr** [orientechnologies/orientdb#4667]
Getting this error on creating a new database from OrientDB console from  a fresh installation of 2.1-rc6 (built from source from 2.1-rc6 tag)

```
$ ./bin/console.sh

OrientDB console v.2.1-rc6 (build UNKNOWN@r; 2015-07-28 17:42:04+0000) www.orientdb.com
Type 'help' to display all the supported commands.
2015-07-28 23:23:24:098 WARNI Not enough physical memory available for DISKCACHE: 1,542MB (heap=494MB). Set lower Maximum Heap (-Xmx setting on JVM) and restart OrientDB. Now running with DISKCACHE=256MB [orientechnologies]
Installing extensions for GREMLIN language v.2.6.0

orientdb> create database remote:localhost/testdb root passwd plocal

Creating database [remote:localhost/testdb] using the storage type [plocal]...Error during closing of channel close listener
java.lang.IllegalStateException: Connection cannot be released because the pool doesn't exist anymore
        at com.orientechnologies.orient.client.remote.ORemoteConnectionManager.onChannelClose(ORemoteConnectionManager.java:153)
        at com.orientechnologies.orient.enterprise.channel.OChannel.close(OChannel.java:175)
        at com.orientechnologies.orient.enterprise.channel.binary.OChannelBinary.close(OChannelBinary.java:413)
        at com.orientechnologies.orient.enterprise.channel.binary.OChannelBinaryAsynchClient.close(OChannelBinaryAsynchClient.java:320)
        at com.orientechnologies.orient.client.remote.ORemoteConnectionManager.closePool(ORemoteConnectionManager.java:199)
        at com.orientechnologies.orient.client.remote.ORemoteConnectionManager.closePool(ORemoteConnectionManager.java:192)
        at com.orientechnologies.orient.client.remote.OStorageRemote.close(OStorageRemote.java:312)
        at com.orientechnologies.orient.core.storage.OStorageAbstract.close(OStorageAbstract.java:123)
        at com.orientechnologies.orient.client.remote.OServerAdmin.close(OServerAdmin.java:559)
        at com.orientechnologies.orient.console.OConsoleDatabaseApp.createDatabase(OConsoleDatabaseApp.java:311)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at com.orientechnologies.common.console.OConsoleApplication.execute(OConsoleApplication.java:375)
        at com.orientechnologies.common.console.OConsoleApplication.executeCommands(OConsoleApplication.java:240)
        at com.orientechnologies.common.console.OConsoleApplication.run(OConsoleApplication.java:129)
        at com.orientechnologies.orient.graph.console.OGremlinConsole.main(OGremlinConsole.java:64)

Connecting to database [remote:localhost/testdb] with user 'admin'...OK
Database created successfully.

Current database is: remote:localhost/testdb
orientdb {db=testdb}>
```

and this error upon disconnect:

```
orientdb {db=testdb}> disconnect

Disconnecting from the database [testdb]...Error during closing of channel close listener
java.lang.IllegalStateException: Connection cannot be released because the pool doesn't exist anymore
        at com.orientechnologies.orient.client.remote.ORemoteConnectionManager.onChannelClose(ORemoteConnectionManager.java:153)
        at com.orientechnologies.orient.enterprise.channel.OChannel.close(OChannel.java:175)
        at com.orientechnologies.orient.enterprise.channel.binary.OChannelBinary.close(OChannelBinary.java:413)
        at com.orientechnologies.orient.enterprise.channel.binary.OChannelBinaryAsynchClient.close(OChannelBinaryAsynchClient.java:320)
        at com.orientechnologies.orient.client.remote.ORemoteConnectionManager.closePool(ORemoteConnectionManager.java:199)
        at com.orientechnologies.orient.client.remote.ORemoteConnectionManager.closePool(ORemoteConnectionManager.java:192)
        at com.orientechnologies.orient.client.remote.OStorageRemote.close(OStorageRemote.java:312)
        at com.orientechnologies.orient.core.storage.OStorageAbstract.close(OStorageAbstract.java:123)
        at com.orientechnologies.orient.client.remote.OStorageRemoteThread.close(OStorageRemoteThread.java:188)
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.close(ODatabaseDocumentTx.java:1156)
        at com.orientechnologies.orient.console.OConsoleDatabaseApp.disconnect(OConsoleDatabaseApp.java:264)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at com.orientechnologies.common.console.OConsoleApplication.execute(OConsoleApplication.java:375)
        at com.orientechnologies.common.console.OConsoleApplication.executeCommands(OConsoleApplication.java:240)
        at com.orientechnologies.common.console.OConsoleApplication.run(OConsoleApplication.java:129)
        at com.orientechnologies.orient.graph.console.OGremlinConsole.main(OGremlinConsole.java:64)
Can not unlock lock
java.lang.IllegalMonitorStateException
        at java.util.concurrent.locks.ReentrantLock$Sync.tryRelease(ReentrantLock.java:155)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer.release(AbstractQueuedSynchronizer.java:1260)
        at java.util.concurrent.locks.ReentrantLock.unlock(ReentrantLock.java:460)
        at com.orientechnologies.common.concur.lock.OAdaptiveLock.close(OAdaptiveLock.java:130)
        at com.orientechnologies.orient.enterprise.channel.OChannel.close(OChannel.java:180)
        at com.orientechnologies.orient.enterprise.channel.binary.OChannelBinary.close(OChannelBinary.java:413)
        at com.orientechnologies.orient.enterprise.channel.binary.OChannelBinaryAsynchClient.close(OChannelBinaryAsynchClient.java:320)
        at com.orientechnologies.orient.client.remote.ORemoteConnectionManager.closePool(ORemoteConnectionManager.java:199)
        at com.orientechnologies.orient.client.remote.ORemoteConnectionManager.closePool(ORemoteConnectionManager.java:192)
        at com.orientechnologies.orient.client.remote.OStorageRemote.close(OStorageRemote.java:312)
        at com.orientechnologies.orient.core.storage.OStorageAbstract.close(OStorageAbstract.java:123)
        at com.orientechnologies.orient.client.remote.OStorageRemoteThread.close(OStorageRemoteThread.java:188)
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.close(ODatabaseDocumentTx.java:1156)
        at com.orientechnologies.orient.console.OConsoleDatabaseApp.disconnect(OConsoleDatabaseApp.java:264)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at com.orientechnologies.common.console.OConsoleApplication.execute(OConsoleApplication.java:375)
        at com.orientechnologies.common.console.OConsoleApplication.executeCommands(OConsoleApplication.java:240)
        at com.orientechnologies.common.console.OConsoleApplication.run(OConsoleApplication.java:129)
        at com.orientechnologies.orient.graph.console.OGremlinConsole.main(OGremlinConsole.java:64)
OK
orientdb>
```

**Comment by nagarajasr** [comment]
verified with the official tarball, same issue occurs. could it possibly be related to this 69ad5ec commit?

**Comment by tglman** [comment]
removed wrong resource release and decrease the logging level for managed exceptions, closing
