### ISSUE TITLE
OrientDB console hangs - 2.1-rc6

### ISSUE THREAD

**Issue by nagarajasr** [orientechnologies/orientdb#4668]
script to reproduce the error (useLightWeightEdges=true):

schema and data setup:

```sql
delete vertex edgetest

delete edge edgetestedge

drop class edgetest

drop class edgetestedge

create class edgetest extends v

create class edgetestedge extends e

create property edgetest.in_edgetestedge linklist

create property edgetest.out_edgetestedge linklist

create vertex edgetest set id='parentckt1'

create vertex edgetest set id='childckt2'

create vertex edgetest set id='childckt3'

create vertex edgetest set id='childckt4'

create edge edgetestedge from (select from edgetest where id='parentckt1') to (select from edgetest where id like 'childckt%')

```

The error is seen when following query is run:

```sql

orientdb {db=testdb}> select out_edgetestedge[0] from v unwind out_edgetestedge, in_edgetestedge

Error: java.lang.NullPointerException

orientdb {db=testdb}> select out_edgetestedge.type() from v unwind out_edgetestedge, in_edgetestedge


(hangs forever...)
```

Note: i noticed something strange - if after the NPE, any other simple select query is run (say, select from v), and then followed by the above query, it gives the following output:

```

orientdb {db=testdb}> select from v

2015-07-29 02:25:48:335 SEVER Removing disconnected network channel '127.0.0.1:2424/testdb'... [OStorageRemote]
2015-07-29 02:25:48:375 WARNI Caught I/O errors from Not connected (local socket=?), trying to reconnect (error: java.io.IOException: Channel is closed) [OStorageRemote]
2015-07-29 02:25:48:382 WARNI Connection re-acquired transparently after 6ms and 1 retries to server '127.0.0.1:2424/testdb': no errors will be thrown at application level [OStorageRemote]
----+-----+--------+----------------+-------------+---------------
#   |@RID |@CLASS  |out_edgetestedge|id           |in_edgetestedge
----+-----+--------+----------------+-------------+---------------
0   |#14:0|edgetest|[3]             |parentckt1|null
1   |#14:1|edgetest|null            |childckt2 |[1]
2   |#14:2|edgetest|null            |childckt3 |[1]
3   |#14:3|edgetest|null            |childckt4 |[1]
----+-----+--------+----------------+-------------+---------------

4 item(s) found. Query executed in 0.052 sec(s).

orientdb {db=testdb}> select out_edgetestedge.type() from v unwind out_edgetestedge, in_edgetestedge

----+------+----------------
#   |@CLASS|out_edgetestedge
----+------+----------------
0   |null  |LINKLIST
1   |null  |null
2   |null  |null
3   |null  |null
----+------+----------------

4 item(s) found. Query executed in 0.011 sec(s).

```

server side logs:

```java
{db=testdb} Error on unmarshalling record #-2:1 (com.orientechnologies.orient.core.exception.OSerializationException: Impossible serialize value of type class com.orientechnologies.orient.core.record.impl.ODocument$1$1 with the ODocument binary serializer)
com.orientechnologies.orient.core.exception.OSerializationException: Impossible serialize value of type class com.orientechnologies.orient.core.record.impl.ODocument$1$1 with the ODocument binary serializer
        at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinaryV0.serialize(ORecordSerializerBinaryV0.java:255)
        at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinary.toStream(ORecordSerializerBinary.java:105)
        at com.orientechnologies.orient.core.record.impl.ODocument.toStream(ODocument.java:2234)
        at com.orientechnologies.orient.core.record.impl.ODocument.toStream(ODocument.java:664)
        at com.orientechnologies.orient.server.network.protocol.binary.OBinaryNetworkProtocolAbstract.getRecordBytes(OBinaryNetworkProtocolAbstract.java:419)
        at com.orientechnologies.orient.server.network.protocol.binary.OBinaryNetworkProtocolAbstract.writeRecord(OBinaryNetworkProtocolAbstract.java:434)
        at com.orientechnologies.orient.server.network.protocol.binary.OBinaryNetworkProtocolAbstract.writeIdentifiable(OBinaryNetworkProtocolAbstract.java:136)
        at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.serializeValue(ONetworkProtocolBinary.java:1385)
        at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.command(ONetworkProtocolBinary.java:1333)
        at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.executeRequest(ONetworkProtocolBinary.java:397)
        at com.orientechnologies.orient.server.network.protocol.binary.OBinaryNetworkProtocolAbstract.execute(OBinaryNetworkProtocolAbstract.java:218)
        at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:71)

2015-07-29 02:23:08:422 WARNI {db=testdb} Cannot serialize record: #-2:1{out_edgetestedge:com.orientechnologies.orient.core.record.impl.ODocument$1$1@52744830} v0 [ONetworkProtocolBinary]{db=testdb} Error on unmarshalling record #-2:2 (com.orientechnologies.orient.core.exception.OSerializationException: Impossible serialize value of type class com.orientechnologies.orient.core.record.impl.ODocument$1$1 with the ODocument binary serializer)
com.orientechnologies.orient.core.exception.OSerializationException: Impossible serialize value of type class com.orientechnologies.orient.core.record.impl.ODocument$1$1 with the ODocument binary serializer
        at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinaryV0.serialize(ORecordSerializerBinaryV0.java:255)
        at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinary.toStream(ORecordSerializerBinary.java:105)
        at com.orientechnologies.orient.core.record.impl.ODocument.toStream(ODocument.java:2234)
        at com.orientechnologies.orient.core.record.impl.ODocument.toStream(ODocument.java:664)
        at com.orientechnologies.orient.server.network.protocol.binary.OBinaryNetworkProtocolAbstract.getRecordBytes(OBinaryNetworkProtocolAbstract.java:419)
        at com.orientechnologies.orient.server.network.protocol.binary.OBinaryNetworkProtocolAbstract.writeRecord(OBinaryNetworkProtocolAbstract.java:434)
        at com.orientechnologies.orient.server.network.protocol.binary.OBinaryNetworkProtocolAbstract.writeIdentifiable(OBinaryNetworkProtocolAbstract.java:136)
        at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.serializeValue(ONetworkProtocolBinary.java:1385)
        at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.command(ONetworkProtocolBinary.java:1333)
        at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.executeRequest(ONetworkProtocolBinary.java:397)
        at com.orientechnologies.orient.server.network.protocol.binary.OBinaryNetworkProtocolAbstract.execute(OBinaryNetworkProtocolAbstract.java:218)
        at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:71)

2015-07-29 02:23:08:423 WARNI {db=testdb} Cannot serialize record: #-2:2{out_edgetestedge:com.orientechnologies.orient.core.record.impl.ODocument$1$1@5daef86b} v0 [ONetworkProtocolBinary]

```

```java
Error during channel flush
java.net.SocketException: Socket closed
        at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:121)
        at java.net.SocketOutputStream.write(SocketOutputStream.java:159)
        at java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:82)
        at java.io.BufferedOutputStream.flush(BufferedOutputStream.java:140)
        at java.io.DataOutputStream.flush(DataOutputStream.java:123)
        at com.orientechnologies.orient.enterprise.channel.binary.OChannelBinary.flush(OChannelBinary.java:387)
        at com.orientechnologies.orient.server.network.protocol.binary.OBinaryNetworkProtocolAbstract.handleConnectionError(OBinaryNetworkProtocolAbstract.java:397)
        at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.handleConnectionError(ONetworkProtocolBinary.java:1811)
        at com.orientechnologies.orient.server.network.protocol.binary.OBinaryNetworkProtocolAbstract.execute(OBinaryNetworkProtocolAbstract.java:212)
        at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:71)

```

**Comment by tglman** [comment]
fixed closing

**Comment by lvca** [comment]
@tglman I don't see the reason of closing neither the ref to the commit.
