### ISSUE TITLE
Work bench installataion issue :javax.management.NotCompliantMBeanException: MBean class com.orientechnologies.agent.profiler.OEnterpriseProfiler 

### ISSUE THREAD

**Issue by SatishAMP** [orientechnologies/orientdb#4674]
We are using 2.0.9 Server , 2.0.3 Work bench :
2015-07-29 07:53:52:670 INFO  JMX plugin installed and active: profilerManaged=true [OJMXPlugin]Exception in thread "main" com.orientec
hnologies.orient.core.exception.OConfigurationException: Cannot initialize JMX server
        at com.orientechnologies.orient.server.handler.OJMXPlugin.config(OJMXPlugin.java:74)
        at com.orientechnologies.orient.server.OServer.registerPlugins(OServer.java:870)
        at com.orientechnologies.orient.server.OServer.activate(OServer.java:265)
        at com.orientechnologies.orient.server.OServerMain.main(OServerMain.java:41)
Caused by: javax.management.NotCompliantMBeanException: MBean class com.orientechnologies.agent.profiler.OEnterpriseProfiler does not i
mplement DynamicMBean, and neither follows the Standard MBean conventions (javax.management.NotCompliantMBeanException: Class com.orien
technologies.agent.profiler.OEnterpriseProfiler is not a JMX compliant Standard MBean) nor the MXBean conventions (javax.management.Not
CompliantMBeanException: com.orientechnologies.agent.profiler.OEnterpriseProfiler: Class com.orientechnologies.agent.profiler.OEnterpri
seProfiler is not a JMX compliant MXBean)
        at com.sun.jmx.mbeanserver.Introspector.checkCompliance(Introspector.java:173)
        at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.registerMBean(DefaultMBeanServerInterceptor.java:317)
        at com.sun.jmx.mbeanserver.JmxMBeanServer.registerMBean(JmxMBeanServer.java:522)
        at com.orientechnologies.orient.server.handler.OJMXPlugin.config(OJMXPlugin.java:65)
        ... 3 more

**Comment by laa** [comment]
Hi,
It is fixed in 2.1 -rc6 version

**Comment by SatishAMP** [comment]
HI

We are running our production environment with 2.0.13 , Can't migrate to 2.1 in near future . Can you please help us to fix this in 2.0.13 ?

Thanks
Satish
