### ISSUE TITLE
Huge amount of databases

### ISSUE THREAD

**Issue by Ganitzsh** [orientechnologies/orientdb#4681]
Hi,

I have been working on a project written in Go that needs to duplicate DBs at runtime and work with them via the HTTP API.

My main database model is in `databases/empty_model`. I'm copy/pasting this model as a temporary DB to access it right after the end of the copy by connecting to it and start executing actions on it. These actions are done with the server running and never restarted.

It works, until a certain number of temporary databases. Once I reach this number, depending on the machine, It says the database is corrupted and throws multiple FileNotFoundException and the server completely blows and takes a very long time to shutdown. BUT nothing is missing.

How does OrientDB manage connections to databases? Does it store them in RAM every time you connect to it?

**Comment by laa** [comment]
I think you merely reached limit of open files.
Do you have full stack trace ? Could you try on 2.0-RC6 version ?
It is more immune to such cases.

**Comment by Ganitzsh** [comment]
Here is a stack trace:
```
2015-07-28 23:55:46:202 WARNING {db=_40d6fd76-6ccb-4e58-aa53-630704d15874} Error on loading cluster 'person' (20): file not found. It will be excluded from current database '_40d6fd76-6ccb-4e58-aa53-630704d15874'. [OLocalPaginatedStorage]
2015-07-28 23:55:46:205 FINE  {db=_40d6fd76-6ccb-4e58-aa53-630704d15874} [OFile.openChannel] opening channel for file '/usr/local/src/orientdb/databases/_40d6fd76-6ccb-4e58-aa53-630704d15874/worksfor.pcl' of size: 66560 [OFileClassic]
2015-07-28 23:55:47:229 WARNING {db=_40d6fd76-6ccb-4e58-aa53-630704d15874} Error on loading cluster 'worksfor' (21): file not found. It will be excluded from current database '_40d6fd76-6ccb-4e58-aa53-630704d15874'. [OLocalPaginatedStorage]
2015-07-28 23:55:47:233 FINE  {db=_40d6fd76-6ccb-4e58-aa53-630704d15874} [OFile.openChannel] opening channel for file '/usr/local/src/orientdb/databases/_40d6fd76-6ccb-4e58-aa53-630704d15874/language.pcl' of size: 66560 [OFileClassic]
2015-07-28 23:55:48:252 WARNING {db=_40d6fd76-6ccb-4e58-aa53-630704d15874} Error on loading cluster 'language' (22): file not found. It will be excluded from current database '_40d6fd76-6ccb-4e58-aa53-630704d15874'. [OLocalPaginatedStorage]
2015-07-28 23:55:48:255 FINE  {db=_40d6fd76-6ccb-4e58-aa53-630704d15874} [OFile.openChannel] opening channel for file '/usr/local/src/orientdb/databases/_40d6fd76-6ccb-4e58-aa53-630704d15874/relatedto.pcl' of size: 66560 [OFileClassic]
2015-07-28 23:55:49:276 WARNING {db=_40d6fd76-6ccb-4e58-aa53-630704d15874} Error on loading cluster 'relatedto' (23): file not found. It will be excluded from current database '_40d6fd76-6ccb-4e58-aa53-630704d15874'. [OLocalPaginatedStorage]
2015-07-28 23:55:49:279 FINE  {db=_40d6fd76-6ccb-4e58-aa53-630704d15874} [OFile.openChannel] opening channel for file '/usr/local/src/orientdb/databases/_40d6fd76-6ccb-4e58-aa53-630704d15874/phone.pcl' of size: 66560 [OFileClassic]
2015-07-28 23:55:50:302 WARNING {db=_40d6fd76-6ccb-4e58-aa53-630704d15874} Error on loading cluster 'phone' (24): file not found. It will be excluded from current database '_40d6fd76-6ccb-4e58-aa53-630704d15874'. [OLocalPaginatedStorage]
2015-07-28 23:55:50:305 FINE  {db=_40d6fd76-6ccb-4e58-aa53-630704d15874} [OFile.openChannel] opening channel for file '/usr/local/src/orientdb/databases/_40d6fd76-6ccb-4e58-aa53-630704d15874/gpscoordinates.pcl' of size: 66560 [OFileClassic]
2015-07-28 23:55:51:336 WARNING {db=_40d6fd76-6ccb-4e58-aa53-630704d15874} Error on loading cluster 'gpscoordinates' (25): file not found. It will be excluded from current database '_40d6fd76-6ccb-4e58-aa53-630704d15874'. [OLocalPaginatedStorage]
2015-07-28 23:55:51:338 FINE  {db=_40d6fd76-6ccb-4e58-aa53-630704d15874} [OFile.openChannel] opening channel for file '/usr/local/src/orientdb/databases/_40d6fd76-6ccb-4e58-aa53-630704d15874/job.pcl' of size: 66560 [OFileClassic]
2015-07-28 23:55:52:357 WARNING {db=_40d6fd76-6ccb-4e58-aa53-630704d15874} Error on loading cluster 'job' (26): file not found. It will be excluded from current database '_40d6fd76-6ccb-4e58-aa53-630704d15874'. [OLocalPaginatedStorage]
2015-07-28 23:55:52:361 FINE  {db=_40d6fd76-6ccb-4e58-aa53-630704d15874} [OFile.openChannel] opening channel for file '/usr/local/src/orientdb/databases/_40d6fd76-6ccb-4e58-aa53-630704d15874/education.pcl' of size: 66560 [OFileClassic]
2015-07-28 23:55:53:376 WARNING {db=_40d6fd76-6ccb-4e58-aa53-630704d15874} Error on loading cluster 'education' (27): file not found. It will be excluded from current database '_40d6fd76-6ccb-4e58-aa53-630704d15874'. [OLocalPaginatedStorage]
2015-07-28 23:55:53:379 FINE  {db=_40d6fd76-6ccb-4e58-aa53-630704d15874} [OFile.openChannel] opening channel for file '/usr/local/src/orientdb/databases/_40d6fd76-6ccb-4e58-aa53-630704d15874/worksas.pcl' of size: 66560 [OFileClassic]
2015-07-28 23:55:54:398 WARNING {db=_40d6fd76-6ccb-4e58-aa53-630704d15874} Error on loading cluster 'worksas' (28): file not found. It will be excluded from current database '_40d6fd76-6ccb-4e58-aa53-630704d15874'. [OLocalPaginatedStorage]
2015-07-28 23:55:54:401 FINE  {db=_40d6fd76-6ccb-4e58-aa53-630704d15874} [OFile.openChannel] opening channel for file '/usr/local/src/orientdb/databases/_40d6fd76-6ccb-4e58-aa53-630704d15874/worksin.pcl' of size: 66560 [OFileClassic]
2015-07-28 23:55:55:428 WARNING {db=_40d6fd76-6ccb-4e58-aa53-630704d15874} Error on loading cluster 'worksin' (29): file not found. It will be excluded from current database '_40d6fd76-6ccb-4e58-aa53-630704d15874'. [OLocalPaginatedStorage]
2015-07-28 23:55:55:434 FINE  {db=_40d6fd76-6ccb-4e58-aa53-630704d15874} [OFile.openChannel] opening channel for file '/usr/local/src/orientdb/databases/_40d6fd76-6ccb-4e58-aa53-630704d15874/mail.pcl' of size: 66560 [OFileClassic]
2015-07-28 23:55:56:456 WARNING {db=_40d6fd76-6ccb-4e58-aa53-630704d15874} Error on loading cluster 'mail' (30): file not found. It will be excluded from current database '_40d6fd76-6ccb-4e58-aa53-630704d15874'. [OLocalPaginatedStorage]
2015-07-28 23:55:56:461 FINE  {db=_40d6fd76-6ccb-4e58-aa53-630704d15874} [OFile.openChannel] opening channel for file '/usr/local/src/orientdb/databases/_40d6fd76-6ccb-4e58-aa53-630704d15874/friendwith.pcl' of size: 66560 [OFileClassic]
2015-07-28 23:55:57:480 WARNING {db=_40d6fd76-6ccb-4e58-aa53-630704d15874} Error on loading cluster 'friendwith' (31): file not found. It will be excluded from current database '_40d6fd76-6ccb-4e58-aa53-630704d15874'. [OLocalPaginatedStorage]
2015-07-28 23:55:57:484 FINE  {db=_40d6fd76-6ccb-4e58-aa53-630704d15874} [OFile.openChannel] opening channel for file '/usr/local/src/orientdb/databases/_40d6fd76-6ccb-4e58-aa53-630704d15874/colleagueof.pcl' of size: 66560 [OFileClassic]
2015-07-28 23:55:58:502 WARNING {db=_40d6fd76-6ccb-4e58-aa53-630704d15874} Error on loading cluster 'colleagueof' (32): file not found. It will be excluded from current database '_40d6fd76-6ccb-4e58-aa53-630704d15874'. [OLocalPaginatedStorage]
2015-07-28 23:55:58:506 FINE  {db=_40d6fd76-6ccb-4e58-aa53-630704d15874} [OFile.openChannel] opening channel for file '/usr/local/src/orientdb/databases/_40d6fd76-6ccb-4e58-aa53-630704d15874/link.pcl' of size: 66560 [OFileClassic]
2015-07-28 23:55:59:535 WARNING {db=_40d6fd76-6ccb-4e58-aa53-630704d15874} Error on loading cluster 'link' (33): file not found. It will be excluded from current database '_40d6fd76-6ccb-4e58-aa53-630704d15874'. [OLocalPaginatedStorage]
2015-07-28 23:55:59:544 FINE  {db=_40d6fd76-6ccb-4e58-aa53-630704d15874} [OFile.openChannel] opening channel for file '/usr/local/src/orientdb/databases/_40d6fd76-6ccb-4e58-aa53-630704d15874/knows.pcl' of size: 66560 [OFileClassic]
2015-07-28 23:56:00:581 WARNING {db=_40d6fd76-6ccb-4e58-aa53-630704d15874} Error on loading cluster 'knows' (34): file not found. It will be excluded from current database '_40d6fd76-6ccb-4e58-aa53-630704d15874'. [OLocalPaginatedStorage]
2015-07-28 23:56:00:584 FINE  {db=_40d6fd76-6ccb-4e58-aa53-630704d15874} [OFile.openChannel] opening channel for file '/usr/local/src/orientdb/databases/_40d6fd76-6ccb-4e58-aa53-630704d15874/speaks.pcl' of size: 66560 [OFileClassic]
2015-07-28 23:56:01:640 WARNING {db=_40d6fd76-6ccb-4e58-aa53-630704d15874} Error on loading cluster 'speaks' (35): file not found. It will be excluded from current database '_40d6fd76-6ccb-4e58-aa53-630704d15874'. [OLocalPaginatedStorage]
2015-07-28 23:56:01:726 FINE  {db=_40d6fd76-6ccb-4e58-aa53-630704d15874} [OFile.openChannel] opening channel for file '/usr/local/src/orientdb/databases/_40d6fd76-6ccb-4e58-aa53-630704d15874/livesat.pcl' of size: 66560 [OFileClassic]
2015-07-28 23:56:02:835 WARNING {db=_40d6fd76-6ccb-4e58-aa53-630704d15874} Error on loading cluster 'livesat' (36): file not found. It will be excluded from current database '_40d6fd76-6ccb-4e58-aa53-630704d15874'. [OLocalPaginatedStorage]
2015-07-28 23:56:02:875 FINE  {db=_40d6fd76-6ccb-4e58-aa53-630704d15874} [OFile.openChannel] opening channel for file '/usr/local/src/orientdb/databases/_40d6fd76-6ccb-4e58-aa53-630704d15874/studied.pcl' of size: 66560 [OFileClassic]
2015-07-28 23:56:03:916 WARNING {db=_40d6fd76-6ccb-4e58-aa53-630704d15874} Error on loading cluster 'studied' (37): file not found. It will be excluded from current database '_40d6fd76-6ccb-4e58-aa53-630704d15874'. [OLocalPaginatedStorage]
2015-07-28 23:56:03:919 FINE  {db=_40d6fd76-6ccb-4e58-aa53-630704d15874} [OFile.openChannel] opening channel for file '/usr/local/src/orientdb/databases/_40d6fd76-6ccb-4e58-aa53-630704d15874/is.pcl' of size: 66560 [OFileClassic]
2015-07-28 23:56:05:077 WARNING {db=_40d6fd76-6ccb-4e58-aa53-630704d15874} Error on loading cluster 'is' (38): file not found. It will be excluded from current database '_40d6fd76-6ccb-4e58-aa53-630704d15874'. [OLocalPaginatedStorage]
2015-07-28 23:56:05:107 FINE  {db=_40d6fd76-6ccb-4e58-aa53-630704d15874} [OFile.openChannel] opening channel for file '/usr/local/src/orientdb/databases/_40d6fd76-6ccb-4e58-aa53-630704d15874/learned.pcl' of size: 66560 [OFileClassic]
2015-07-28 23:56:06:190 WARNING {db=_40d6fd76-6ccb-4e58-aa53-630704d15874} Error on loading cluster 'learned' (39): file not found. It will be excluded from current database '_40d6fd76-6ccb-4e58-aa53-630704d15874'. [OLocalPaginatedStorage]
2015-07-28 23:56:06:256 FINE  {db=_40d6fd76-6ccb-4e58-aa53-630704d15874} [OFile.openChannel] opening channel for file '/usr/local/src/orientdb/databases/_40d6fd76-6ccb-4e58-aa53-630704d15874/OUser.name.sbt' of size: 66560 [OFileClassic]
2015-07-28 23:56:07:296 SEVERE {db=_40d6fd76-6ccb-4e58-aa53-630704d15874}  [OIndexUnique]
2015-07-28 23:56:07:297 WARNING {db=_40d6fd76-6ccb-4e58-aa53-630704d15874} Cannot load index 'OUser.name' from storage (rid=#1:1): rebuilt it from scratch [OIndexUnique]
2015-07-28 23:56:07:318 FINE  {db=_40d6fd76-6ccb-4e58-aa53-630704d15874} [OFile.openChannel] opening channel for file '/usr/local/src/orientdb/databases/_40d6fd76-6ccb-4e58-aa53-630704d15874/OUser.name.sbt' of size: 66560 [OFileClassic]{db=_40d6fd76-6ccb-4e58-aa53-630704d15874} Cannot rebuild index 'OUser.name' from storage (rid=#1:1) because 'com.orientechnologies.orient.core.index.sbtree.local.OSBTreeException: Exception during deletion of sbtree OUser.name'. The index will be removed in configuration
com.orientechnologies.orient.core.index.sbtree.local.OSBTreeException: Exception during loading of sbtree OUser.name
	at com.orientechnologies.orient.core.index.sbtree.local.OSBTree.load(OSBTree.java:500)
	at com.orientechnologies.orient.core.index.engine.OSBTreeIndexEngine.load(OSBTreeIndexEngine.java:162)
	at com.orientechnologies.orient.core.index.OIndexAbstract.loadFromConfiguration(OIndexAbstract.java:267)
	at com.orientechnologies.orient.core.index.OIndexManagerShared.fromStream(OIndexManagerShared.java:377)
	at com.orientechnologies.orient.core.type.ODocumentWrapperNoClass.reload(ODocumentWrapperNoClass.java:74)
	at com.orientechnologies.orient.core.index.OIndexManagerAbstract.load(OIndexManagerAbstract.java:89)
	at com.orientechnologies.orient.core.index.OIndexManagerAbstract.load(OIndexManagerAbstract.java:53)
	at com.orientechnologies.orient.core.metadata.OMetadataDefault$2.call(OMetadataDefault.java:197)
	at com.orientechnologies.orient.core.metadata.OMetadataDefault$2.call(OMetadataDefault.java:187)
	at com.orientechnologies.common.concur.resource.OSharedContainerImpl.getResource(OSharedContainerImpl.java:57)
	at com.orientechnologies.orient.core.metadata.OMetadataDefault.init(OMetadataDefault.java:186)
	at com.orientechnologies.orient.core.metadata.OMetadataDefault.load(OMetadataDefault.java:77)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.initAtFirstOpen(ODatabaseDocumentTx.java:2687)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.open(ODatabaseDocumentTx.java:255)
	at com.orientechnologies.orient.server.OServer.openDatabase(OServer.java:647)
	at com.orientechnologies.orient.server.OServer.openDatabase(OServer.java:629)
	at com.orientechnologies.orient.server.network.protocol.http.command.OServerCommandAuthenticatedDbAbstract.authenticate(OServerCommandAuthenticatedDbAbstract.java:167)
	at com.orientechnologies.orient.server.network.protocol.http.command.OServerCommandAuthenticatedDbAbstract.beforeExecute(OServerCommandAuthenticatedDbAbstract.java:127)
	at com.orientechnologies.orient.server.network.protocol.http.command.get.OServerCommandGetConnect.beforeExecute(OServerCommandGetConnect.java:50)
	at com.orientechnologies.orient.server.network.protocol.http.ONetworkProtocolHttpAbstract.service(ONetworkProtocolHttpAbstract.java:171)
	at com.orientechnologies.orient.server.network.protocol.http.ONetworkProtocolHttpAbstract.execute(ONetworkProtocolHttpAbstract.java:574)
	at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:69)
Caused by: java.io.FileNotFoundException: /usr/local/src/orientdb/databases/_40d6fd76-6ccb-4e58-aa53-630704d15874/OUser.name.sbt
	at com.orientechnologies.orient.core.storage.fs.OAbstractFile.openChannel(OAbstractFile.java:635)
	at com.orientechnologies.orient.core.storage.fs.OAbstractFile.open(OAbstractFile.java:144)
	at com.orientechnologies.orient.core.index.hashindex.local.cache.OWOWCache.openFile(OWOWCache.java:849)
	at com.orientechnologies.orient.core.index.hashindex.local.cache.OWOWCache.openFile(OWOWCache.java:251)
	at com.orientechnologies.orient.core.index.hashindex.local.cache.OReadWriteDiskCache.openFile(OReadWriteDiskCache.java:159)
	at com.orientechnologies.orient.core.storage.impl.local.paginated.base.ODurableComponent.openFile(ODurableComponent.java:162)
	at com.orientechnologies.orient.core.index.sbtree.local.OSBTree.load(OSBTree.java:490)
	... 21 more

2015-07-28 23:56:08:364 FINE  {db=_40d6fd76-6ccb-4e58-aa53-630704d15874} [OFile.openChannel] opening channel for file '/usr/local/src/orientdb/databases/_40d6fd76-6ccb-4e58-aa53-630704d15874/ORole.name.sbt' of size: 66560 [OFileClassic]
2015-07-28 23:56:09:384 SEVERE {db=_40d6fd76-6ccb-4e58-aa53-630704d15874}  [OIndexUnique]
2015-07-28 23:56:09:385 WARNING {db=_40d6fd76-6ccb-4e58-aa53-630704d15874} Cannot load index 'ORole.name' from storage (rid=#1:0): rebuilt it from scratch [OIndexUnique]
2015-07-28 23:56:09:390 FINE  {db=_40d6fd76-6ccb-4e58-aa53-630704d15874} [OFile.openChannel] opening channel for file '/usr/local/src/orientdb/databases/_40d6fd76-6ccb-4e58-aa53-630704d15874/ORole.name.sbt' of size: 66560 [OFileClassic]{db=_40d6fd76-6ccb-4e58-aa53-630704d15874} Cannot rebuild index 'ORole.name' from storage (rid=#1:0) because 'com.orientechnologies.orient.core.index.sbtree.local.OSBTreeException: Exception during deletion of sbtree ORole.name'. The index will be removed in configuration
com.orientechnologies.orient.core.index.sbtree.local.OSBTreeException: Exception during loading of sbtree ORole.name
	at com.orientechnologies.orient.core.index.sbtree.local.OSBTree.load(OSBTree.java:500)
	at com.orientechnologies.orient.core.index.engine.OSBTreeIndexEngine.load(OSBTreeIndexEngine.java:162)
	at com.orientechnologies.orient.core.index.OIndexAbstract.loadFromConfiguration(OIndexAbstract.java:267)
	at com.orientechnologies.orient.core.index.OIndexManagerShared.fromStream(OIndexManagerShared.java:377)
	at com.orientechnologies.orient.core.type.ODocumentWrapperNoClass.reload(ODocumentWrapperNoClass.java:74)
	at com.orientechnologies.orient.core.index.OIndexManagerAbstract.load(OIndexManagerAbstract.java:89)
	at com.orientechnologies.orient.core.index.OIndexManagerAbstract.load(OIndexManagerAbstract.java:53)
	at com.orientechnologies.orient.core.metadata.OMetadataDefault$2.call(OMetadataDefault.java:197)
	at com.orientechnologies.orient.core.metadata.OMetadataDefault$2.call(OMetadataDefault.java:187)
	at com.orientechnologies.common.concur.resource.OSharedContainerImpl.getResource(OSharedContainerImpl.java:57)
	at com.orientechnologies.orient.core.metadata.OMetadataDefault.init(OMetadataDefault.java:186)
	at com.orientechnologies.orient.core.metadata.OMetadataDefault.load(OMetadataDefault.java:77)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.initAtFirstOpen(ODatabaseDocumentTx.java:2687)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.open(ODatabaseDocumentTx.java:255)
	at com.orientechnologies.orient.server.OServer.openDatabase(OServer.java:647)
	at com.orientechnologies.orient.server.OServer.openDatabase(OServer.java:629)
	at com.orientechnologies.orient.server.network.protocol.http.command.OServerCommandAuthenticatedDbAbstract.authenticate(OServerCommandAuthenticatedDbAbstract.java:167)
	at com.orientechnologies.orient.server.network.protocol.http.command.OServerCommandAuthenticatedDbAbstract.beforeExecute(OServerCommandAuthenticatedDbAbstract.java:127)
	at com.orientechnologies.orient.server.network.protocol.http.command.get.OServerCommandGetConnect.beforeExecute(OServerCommandGetConnect.java:50)
	at com.orientechnologies.orient.server.network.protocol.http.ONetworkProtocolHttpAbstract.service(ONetworkProtocolHttpAbstract.java:171)
	at com.orientechnologies.orient.server.network.protocol.http.ONetworkProtocolHttpAbstract.execute(ONetworkProtocolHttpAbstract.java:574)
	at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:69)
Caused by: java.io.FileNotFoundException: /usr/local/src/orientdb/databases/_40d6fd76-6ccb-4e58-aa53-630704d15874/ORole.name.sbt
	at com.orientechnologies.orient.core.storage.fs.OAbstractFile.openChannel(OAbstractFile.java:635)
	at com.orientechnologies.orient.core.storage.fs.OAbstractFile.open(OAbstractFile.java:144)
	at com.orientechnologies.orient.core.index.hashindex.local.cache.OWOWCache.openFile(OWOWCache.java:849)
	at com.orientechnologies.orient.core.index.hashindex.local.cache.OWOWCache.openFile(OWOWCache.java:251)
	at com.orientechnologies.orient.core.index.hashindex.local.cache.OReadWriteDiskCache.openFile(OReadWriteDiskCache.java:159)
	at com.orientechnologies.orient.core.storage.impl.local.paginated.base.ODurableComponent.openFile(ODurableComponent.java:162)
	at com.orientechnologies.orient.core.index.sbtree.local.OSBTree.load(OSBTree.java:490)
	... 21 more

2015-07-28 23:56:10:425 FINE  {db=_40d6fd76-6ccb-4e58-aa53-630704d15874} [OFile.openChannel] opening channel for file '/usr/local/src/orientdb/databases/_40d6fd76-6ccb-4e58-aa53-630704d15874/dictionary.sbt' of size: 66560 [OFileClassic]
2015-07-28 23:56:11:449 SEVERE {db=_40d6fd76-6ccb-4e58-aa53-630704d15874}  [OIndexDictionary]
2015-07-28 23:56:11:461 FINE  {db=_40d6fd76-6ccb-4e58-aa53-630704d15874} [OFile.openChannel] opening channel for file '/usr/local/src/orientdb/databases/_40d6fd76-6ccb-4e58-aa53-630704d15874/dictionary.sbt' of size: 66560 [OFileClassic]{db=_40d6fd76-6ccb-4e58-aa53-630704d15874} Cannot rebuild index 'dictionary' from storage (rid=#2:0) because 'com.orientechnologies.orient.core.index.sbtree.local.OSBTreeException: Exception during deletion of sbtree dictionary'. The index will be removed in configuration
com.orientechnologies.orient.core.index.sbtree.local.OSBTreeException: Exception during loading of sbtree dictionary
	at com.orientechnologies.orient.core.index.sbtree.local.OSBTree.load(OSBTree.java:500)
	at com.orientechnologies.orient.core.index.engine.OSBTreeIndexEngine.load(OSBTreeIndexEngine.java:162)
	at com.orientechnologies.orient.core.index.OIndexAbstract.loadFromConfiguration(OIndexAbstract.java:267)
	at com.orientechnologies.orient.core.index.OIndexManagerShared.fromStream(OIndexManagerShared.java:377)
	at com.orientechnologies.orient.core.type.ODocumentWrapperNoClass.reload(ODocumentWrapperNoClass.java:74)
	at com.orientechnologies.orient.core.index.OIndexManagerAbstract.load(OIndexManagerAbstract.java:89)
	at com.orientechnologies.orient.core.index.OIndexManagerAbstract.load(OIndexManagerAbstract.java:53)
	at com.orientechnologies.orient.core.metadata.OMetadataDefault$2.call(OMetadataDefault.java:197)
	at com.orientechnologies.orient.core.metadata.OMetadataDefault$2.call(OMetadataDefault.java:187)
	at com.orientechnologies.common.concur.resource.OSharedContainerImpl.getResource(OSharedContainerImpl.java:57)
	at com.orientechnologies.orient.core.metadata.OMetadataDefault.init(OMetadataDefault.java:186)
	at com.orientechnologies.orient.core.metadata.OMetadataDefault.load(OMetadataDefault.java:77)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.initAtFirstOpen(ODatabaseDocumentTx.java:2687)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.open(ODatabaseDocumentTx.java:255)
	at com.orientechnologies.orient.server.OServer.openDatabase(OServer.java:647)
	at com.orientechnologies.orient.server.OServer.openDatabase(OServer.java:629)
	at com.orientechnologies.orient.server.network.protocol.http.command.OServerCommandAuthenticatedDbAbstract.authenticate(OServerCommandAuthenticatedDbAbstract.java:167)
	at com.orientechnologies.orient.server.network.protocol.http.command.OServerCommandAuthenticatedDbAbstract.beforeExecute(OServerCommandAuthenticatedDbAbstract.java:127)
	at com.orientechnologies.orient.server.network.protocol.http.command.get.OServerCommandGetConnect.beforeExecute(OServerCommandGetConnect.java:50)
	at com.orientechnologies.orient.server.network.protocol.http.ONetworkProtocolHttpAbstract.service(ONetworkProtocolHttpAbstract.java:171)
	at com.orientechnologies.orient.server.network.protocol.http.ONetworkProtocolHttpAbstract.execute(ONetworkProtocolHttpAbstract.java:574)
	at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:69)
Caused by: java.io.FileNotFoundException: /usr/local/src/orientdb/databases/_40d6fd76-6ccb-4e58-aa53-630704d15874/dictionary.sbt
	at com.orientechnologies.orient.core.storage.fs.OAbstractFile.openChannel(OAbstractFile.java:635)
	at com.orientechnologies.orient.core.storage.fs.OAbstractFile.open(OAbstractFile.java:144)
	at com.orientechnologies.orient.core.index.hashindex.local.cache.OWOWCache.openFile(OWOWCache.java:849)
	at com.orientechnologies.orient.core.index.hashindex.local.cache.OWOWCache.openFile(OWOWCache.java:251)
	at com.orientechnologies.orient.core.index.hashindex.local.cache.OReadWriteDiskCache.openFile(OReadWriteDiskCache.java:159)
	at com.orientechnologies.orient.core.storage.impl.local.paginated.base.ODurableComponent.openFile(ODurableComponent.java:162)
	at com.orientechnologies.orient.core.index.sbtree.local.OSBTree.load(OSBTree.java:490)
	... 21 more
```

**Comment by nagarajasr** [comment]
@Ganitzsh if what @laa is hinting about open files is indeed the case, you may be able to work around the problem by increasing the ulimit -n and observe if the problem now occurs at a higher number of temp DBs (or conversely decrease ulimit -n and lower no. of temp DBs). 
i am suggesting this in case you do not wish to upgrade to unstable 2.1-rc6 at this time.

**Comment by Ganitzsh** [comment]
I just tried with a `ulimit -n 10000` and the latest unstable version `2.1-rc6`. It is definitely the cause of my problem, this time I was able to copy a lot more databases with no errors.

What's the difference with version `2.0.13` and `2.1-rc6` when it comes to manage opened files? Is there a way to close files at runtime when they are not needed anymore?

**Comment by laa** [comment]
Hi we have such issue but it requires a lot of time of development because of proper handling of mt issues. So we will implement it but not right now. Probably there is very short solution for this issue but it is not in our top priority list.

**Comment by laa** [comment]
About difference I think that it is not your case actually we discovered that sometimes file descriptors are  closed automatically if such things happens we open them again. But in your case you merely can not open new file. OK I close issue then.

**Comment by nagarajasr** [comment]
@laa just for my knowledge what is 'mt issues' i have seen this mentioned in many places but don't understand the reference.

**Comment by laa** [comment]
it is not bug which we have now, main problem is that whole system thinks that file is open but it is closed and that affects caching functionality .

**Comment by Ganitzsh** [comment]
Thanks for your help. Now I get a clear error from `2.1-rc6`: `Too many open files in system`
Right now the server really never close the opened files? Even after a while of non-usage? Maybe if I wait until the file actually closes it would solve my problem?
