### ISSUE TITLE
Work bench setup , Server offile

### ISSUE THREAD

**Issue by SatishAMP** [orientechnologies/orientdb#4682]
HI

Server : 2.0.9 Version , Work bench : 2.0.3 .

In Work Bench We are getting this error : 
IOException: Server returned HTTP response code: 505 for URL: http://159.202.94.75:2580/profiler/realtime/system.databases

In Server : 
java.net.SocketTimeoutException: Read timed out
        at java.net.SocketInputStream.socketRead0(Native Method)
        at java.net.SocketInputStream.read(SocketInputStream.java:152)
        at java.net.SocketInputStream.read(SocketInputStream.java:122)
        at java.io.BufferedInputStream.fill(BufferedInputStream.java:235)
        at java.io.BufferedInputStream.read(BufferedInputStream.java:254)
        at com.orientechnologies.orient.enterprise.channel.text.OChannelText.read(OChannelText.java:61)
        at com.orientechnologies.orient.server.network.protocol.http.ONetworkProtocolHttpAbstract.readAllContent(ONetworkProtocolHttpAbstract.java:393)
        at com.orientechnologies.orient.server.network.protocol.http.ONetworkProtocolHttpAbstract.execute(ONetworkProtocolHttpAbstract.java:600)
        at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:69)

**Comment by maggiolo00** [comment]
Hi @SatishAMP 
can we close this?

**Comment by maggiolo00** [comment]
hi @SatishAMP i'm closing this.
Should be resolved. In case not just reopen it
