### ISSUE TITLE
orientdb 2.0.13, when I put a vertex to a index, get a exception

### ISSUE THREAD

**Issue by ninesunqian** [orientechnologies/orientdb#4709]
java.lang.NullPointerException

	at com.orientechnologies.orient.core.index.OIndexAbstractDelegate.getName(OIndexAbstractDelegate.java:117)

	at com.orientechnologies.orient.core.index.OIndexTxAware.put(OIndexTxAware.java:97)

	at com.orientechnologies.orient.core.index.OIndexTxAware.put(OIndexTxAware.java:41)

	at com.tinkerpop.blueprints.impls.orient.OrientIndex.put(OrientIndex.java:100)

	at com.tinkerpop.blueprints.impls.orient.OrientIndex.put(OrientIndex.java:49)

**Comment by ninesunqian** [comment]
when I used orientdb 1.7.5 and debug my app by Intellij IDEA,  I got the log about rebuilding index, when I restart a stopped debug.  After I migrating to 2.0.13, I get the exception, and I don't know how to repair it   or repair the database

**Comment by laa** [comment]
How did you migrate to new database release ? by export/import ?

**Comment by ninesunqian** [comment]
I did not use the old data.  
Now, I create index in executeOutsideTx method,  and the bug has disappeared
