### ISSUE TITLE
Prepared Statement for selecting vertices

### ISSUE THREAD

**Issue by elexx** [orientechnologies/orientdb#4712]
I want to use a prepared statement to select some vertices in my GraphDB, but it seems to be more tricky than expected.

If I use the API wrongly, please point me in the right direction and close this issue!

===

The following works, but is prone to all kind of injection attacks:
```java
OSQLSynchQuery<Vertex> command = new OSQLSynchQuery<>("SELECT expand(out('has')[@class = " + clazz + "]) FROM " + id);
graph.command(command).execute();
```

And the equivalent, written as prepared statement throws some exceptions:
```java
OSQLSynchQuery<Vertex> command = new OSQLSynchQuery<>("SELECT expand(out('has')[@class = ?]) FROM ?");
graph.command(command).execute(clazz, id);
```
```
com.orientechnologies.orient.core.exception.OQueryParsingException: Error on parsing command at position #0: Error on parsing query
Query:  ?
------^
	at com.orientechnologies.orient.core.sql.filter.OSQLTarget.<init>(OSQLTarget.java:76) ~[orientdb-core-2.1-rc6.jar:2.1-rc6]
	at com.orientechnologies.orient.core.sql.OSQLEngine.parseTarget(OSQLEngine.java:440) ~[orientdb-core-2.1-rc6.jar:2.1-rc6]
	at com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.parse(OCommandExecutorSQLSelect.java:200) ~[orientdb-core-2.1-rc6.jar:2.1-rc6]
	at com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.parse(OCommandExecutorSQLSelect.java:78) ~[orientdb-core-2.1-rc6.jar:2.1-rc6]
	at com.orientechnologies.orient.core.sql.OCommandExecutorSQLDelegate.parse(OCommandExecutorSQLDelegate.java:56) ~[orientdb-core-2.1-rc6.jar:2.1-rc6]
	at com.orientechnologies.orient.core.sql.OCommandExecutorSQLDelegate.parse(OCommandExecutorSQLDelegate.java:37) ~[orientdb-core-2.1-rc6.jar:2.1-rc6]
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.command(OAbstractPaginatedStorage.java:1181) ~[orientdb-core-2.1-rc6.jar:2.1-rc6]
	at com.orientechnologies.orient.core.sql.query.OSQLQuery.run(OSQLQuery.java:71) ~[orientdb-core-2.1-rc6.jar:2.1-rc6]
	at com.orientechnologies.orient.core.sql.query.OSQLSynchQuery.run(OSQLSynchQuery.java:85) ~[orientdb-core-2.1-rc6.jar:2.1-rc6]
	at com.orientechnologies.orient.core.query.OQueryAbstract.execute(OQueryAbstract.java:33) ~[orientdb-core-2.1-rc6.jar:2.1-rc6]
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.command(ONetworkProtocolBinary.java:1183) ~[orientdb-server-2.1-rc6.jar:2.1-rc6]
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.executeRequest(ONetworkProtocolBinary.java:390) ~[orientdb-server-2.1-rc6.jar:2.1-rc6]
	at com.orientechnologies.orient.server.network.protocol.binary.OBinaryNetworkProtocolAbstract.execute(OBinaryNetworkProtocolAbstract.java:217) ~[orientdb-server-2.1-rc6.jar:2.1-rc6]
	at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:69) ~[orientdb-core-2.1-rc6.jar:2.1-rc6]
Caused by: com.orientechnologies.orient.core.exception.OCommandExecutionException: Class '?' was not found in current database
	at com.orientechnologies.orient.core.sql.filter.OSQLTarget.extractTargets(OSQLTarget.java:262) ~[orientdb-core-2.1-rc6.jar:2.1-rc6]
	at com.orientechnologies.orient.core.sql.filter.OSQLTarget.<init>(OSQLTarget.java:67) ~[orientdb-core-2.1-rc6.jar:2.1-rc6]
	... 13 common frames omitted
```

Originally I tried this with version **2.0.12**, which didn't work, too. And produced a similar stacktrace as the one above, which is from **2.1-rc6**.

**Comment by luigidellaquila** [comment]
Hi @elexx 

what kind of parameters are you passing? Could you please provide the full code?

Thanks a lot

Luigi

**Comment by elexx** [comment]
Currently I don't have access to the database and code, so I can't copy & paste it here.

Both parameters `clazz` and `id` are Strings, where `clazz` is one of my vertex types I registered earlier with`graph.createVertexType("SomeClass")` and `id` is a recordId, for example `#11:0`.

I will create a simple program, demonstrating this problem and post it here soon.

**Comment by elexx** [comment]
I tried to reproduce the error, but was not able to.
Sorry for any inconvenience.

I'll close this issue and reopen another one, with a link to this and a working example, in case I stumble upon this problem again.

**Comment by lvca** [comment]
NP, thanks.
