### ISSUE TITLE
Executing a Test Data Generator - Returned to Find the Application Hung

### ISSUE THREAD

**Issue by compensator** [orientechnologies/orientdb#4731]
Below is the thread dump of its current state:

I've run this application at least 10 times since last week with no problem to generate a test schema and data.  It completed the generation of the third of four types of Edge relationships, then went into a hung state apparently.

Full thread dump Java HotSpot(TM) 64-Bit Server VM (25.45-b02 mixed mode):

"OrientDB <- Asynch Client (teleport-ctrlr/10.148.157.122:2424)" #15 daemon prio=5 os_prio=0 tid=0x000000002974a800 nid=0x272c runnable [0x000000002acaf000]
   java.lang.Thread.State: RUNNABLE
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
	at java.net.SocketInputStream.read(SocketInputStream.java:170)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)
	at java.io.BufferedInputStream.fill(BufferedInputStream.java:246)
	at java.io.BufferedInputStream.read(BufferedInputStream.java:265)
	- locked <0x00000005c16141e8> (a java.io.BufferedInputStream)
	at java.io.DataInputStream.readByte(DataInputStream.java:265)
	at com.orientechnologies.orient.enterprise.channel.binary.OChannelBinary.readByte(OChannelBinary.java:73)
	at com.orientechnologies.orient.enterprise.channel.binary.OChannelBinaryAsynchClient.beginResponse(OChannelBinaryAsynchClient.java:200)
	at com.orientechnologies.orient.enterprise.channel.binary.OAsynchChannelServiceThread.execute(OAsynchChannelServiceThread.java:50)
	at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:69)

"Timer-0" #13 daemon prio=5 os_prio=0 tid=0x0000000029423800 nid=0x11e14 in Object.wait() [0x0000000028a2f000]
   java.lang.Thread.State: TIMED_WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	at java.util.TimerThread.mainLoop(Timer.java:552)
	- locked <0x00000005c1610728> (a java.util.TaskQueue)
	at java.util.TimerThread.run(Timer.java:505)

"Monitor Ctrl-Break" #11 daemon prio=5 os_prio=0 tid=0x0000000026a4f800 nid=0x2288 runnable [0x0000000028b6e000]
   java.lang.Thread.State: RUNNABLE
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
	at java.net.SocketInputStream.read(SocketInputStream.java:170)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)
	at sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:284)
	at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:326)
	at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:178)
	- locked <0x00000007173225d0> (a java.io.InputStreamReader)
	at java.io.InputStreamReader.read(InputStreamReader.java:184)
	at java.io.BufferedReader.fill(BufferedReader.java:161)
	at java.io.BufferedReader.readLine(BufferedReader.java:324)
	- locked <0x00000007173225d0> (a java.io.InputStreamReader)
	at java.io.BufferedReader.readLine(BufferedReader.java:389)
	at com.intellij.rt.execution.application.AppMain$1.run(AppMain.java:93)
	at java.lang.Thread.run(Thread.java:745)

"Service Thread" #10 daemon prio=9 os_prio=0 tid=0x00000000267fd000 nid=0x3bd0 runnable [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"C1 CompilerThread3" #9 daemon prio=9 os_prio=2 tid=0x000000002677d800 nid=0x1362c waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"C2 CompilerThread2" #8 daemon prio=9 os_prio=2 tid=0x0000000026774800 nid=0x104 waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"C2 CompilerThread1" #7 daemon prio=9 os_prio=2 tid=0x000000002676c800 nid=0x1c40 waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"C2 CompilerThread0" #6 daemon prio=9 os_prio=2 tid=0x0000000026765000 nid=0x2adc waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"Attach Listener" #5 daemon prio=5 os_prio=2 tid=0x0000000026763800 nid=0x139a0 runnable [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"Signal Dispatcher" #4 daemon prio=9 os_prio=2 tid=0x0000000026762800 nid=0x1292c waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"Finalizer" #3 daemon prio=8 os_prio=1 tid=0x00000000255a2800 nid=0x1884 in Object.wait() [0x0000000027a5f000]
   java.lang.Thread.State: WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:143)
	- locked <0x00000005c1611340> (a java.lang.ref.ReferenceQueue$Lock)
	at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:164)
	at java.lang.ref.Finalizer$FinalizerThread.run(Finalizer.java:209)

"Reference Handler" #2 daemon prio=10 os_prio=2 tid=0x0000000026713800 nid=0x614 in Object.wait() [0x000000002794f000]
   java.lang.Thread.State: WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	at java.lang.Object.wait(Object.java:502)
	at java.lang.ref.Reference$ReferenceHandler.run(Reference.java:157)
	- locked <0x00000005c1612ac0> (a java.lang.ref.Reference$Lock)

"main" #1 prio=5 os_prio=0 tid=0x0000000001e48000 nid=0x1354c runnable [0x000000000213e000]
   java.lang.Thread.State: RUNNABLE
	at java.net.SocketOutputStream.socketWrite0(Native Method)
	at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:109)
	at java.net.SocketOutputStream.write(SocketOutputStream.java:153)
	at java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:82)
	at java.io.BufferedOutputStream.flush(BufferedOutputStream.java:140)
	- locked <0x00000005c1860938> (a java.io.BufferedOutputStream)
	at com.orientechnologies.orient.enterprise.channel.OChannel.flush(OChannel.java:129)
	at com.orientechnologies.orient.enterprise.channel.binary.OChannelBinary.flush(OChannelBinary.java:385)
	at com.orientechnologies.orient.client.remote.OStorageRemote.endRequest(OStorageRemote.java:1383)
	at com.orientechnologies.orient.client.remote.OStorageRemote.readRecord(OStorageRemote.java:492)
	at com.orientechnologies.orient.client.remote.OStorageRemoteThread.readRecord(OStorageRemoteThread.java:253)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.executeReadRecord(ODatabaseDocumentTx.java:1607)
	at com.orientechnologies.orient.core.tx.OTransactionOptimistic.loadRecord(OTransactionOptimistic.java:226)
	at com.orientechnologies.orient.core.tx.OTransactionOptimistic.loadRecord(OTransactionOptimistic.java:237)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.load(ODatabaseDocumentTx.java:1452)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.load(ODatabaseDocumentTx.java:118)
	at com.orientechnologies.orient.core.id.ORecordId.getRecord(ORecordId.java:318)
	at com.tinkerpop.blueprints.impls.orient.OrientBaseGraph.getVertex(OrientBaseGraph.java:748)
	at example.OrientDBTinkerPopFramesLoader.generatePermissionEdges(OrientDBTinkerPopFramesLoader.java:763)
	at example.OrientDBTinkerPopFramesLoader.main(OrientDBTinkerPopFramesLoader.java:948)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:140)

"VM Thread" os_prio=2 tid=0x0000000026712000 nid=0x10694 runnable 

"GC task thread#0 (ParallelGC)" os_prio=0 tid=0x0000000001e5e800 nid=0x136d0 runnable 

"GC task thread#1 (ParallelGC)" os_prio=0 tid=0x0000000001e60000 nid=0x1ec8 runnable 

"GC task thread#2 (ParallelGC)" os_prio=0 tid=0x0000000001e61800 nid=0x1fc8 runnable 

"GC task thread#3 (ParallelGC)" os_prio=0 tid=0x0000000001e63000 nid=0x10884 runnable 

"GC task thread#4 (ParallelGC)" os_prio=0 tid=0x0000000001e66800 nid=0x139ec runnable 

"GC task thread#5 (ParallelGC)" os_prio=0 tid=0x0000000001e67800 nid=0x10048 runnable 

"GC task thread#6 (ParallelGC)" os_prio=0 tid=0x0000000001e6b000 nid=0x2484 runnable 

"GC task thread#7 (ParallelGC)" os_prio=0 tid=0x0000000001e6c000 nid=0x24ec runnable 

"VM Periodic Task Thread" os_prio=2 tid=0x00000000267df800 nid=0x305c waiting on condition 

JNI global references: 2193

Heap
 PSYoungGen      total 42496K, used 23148K [0x0000000715d00000, 0x000000071a180000, 0x00000007c0000000)
  eden space 41984K, 54% used [0x0000000715d00000,0x000000071738b2f8,0x0000000718600000)
  from space 512K, 12% used [0x000000071a080000,0x000000071a090000,0x000000071a100000)
  to   space 512K, 0% used [0x000000071a100000,0x000000071a100000,0x000000071a180000)
 ParOldGen       total 349696K, used 208185K [0x00000005c1600000, 0x00000005d6b80000, 0x0000000715d00000)
  object space 349696K, 59% used [0x00000005c1600000,0x00000005ce14e568,0x00000005d6b80000)
 Metaspace       used 15473K, capacity 16020K, committed 16256K, reserved 1062912K
  class space    used 1844K, capacity 2112K, committed 2176K, reserved 1048576K

**Comment by compensator** [comment]
I found the error in my code.
