### ISSUE TITLE
Vertex version not increased in the distributed mode

### ISSUE THREAD

**Issue by ylopotun** [orientechnologies/orientdb#4734]
When running in the asynchronous distributed 2-node mode, the addEdge operation doesn't always increase the vertex version on the source node.
This causes replication inconsistency, since on the destination node the vertex version is increased. 

Here is a unit test that demonstrates the issue:
https://github.com/orientechnologies/orientdb/pull/4735

**Comment by lvca** [comment]
Did you try with 2.0.14-SNAPSHOT or 2.1 GA ?

**Comment by ylopotun** [comment]
2.1.0 – latest version in the develop branch.

**Comment by lvca** [comment]
Found the problem: in asynch mode the update on version happens asynchronously. I tried to put a sleep and the test pass:
```java
parentV1.addEdge("edgetype", childV);
graph.commit();

Thread.sleep(300);

assertEquals(i+2, ((OrientVertex) parentV1).getRecord().getVersion());
assertEquals(2, ((OrientVertex) childV).getRecord().getVersion());
```

**Comment by lvca** [comment]
Now I'm not sure if this is a bug or not.

**Comment by ylopotun** [comment]
Ok, I see.
The problem is - if we perform a few updates and commits on the same vertex within a small period of time - at some point we get the following exception on the distributed node:

2015-08-11 15:30:07:894 FINE  Read record #12:50 v.1 size=13 bytes [OLocalPaginatedStorage]Error during transaction commit, transaction will be rolled back (tx-id=112)
com.orientechnologies.orient.core.exception.OConcurrentModificationException: Cannot UPDATE the record #12:0 because the version is not the latest. Probably you are updating an old record or it has been modified by another user (db=v4 your=v3)
	at com.orientechnologies.orient.core.conflict.OVersionRecordConflictStrategy.checkVersions(OVersionRecordConflictStrategy.java:55)
	at com.orientechnologies.orient.core.conflict.OVersionRecordConflictStrategy.onUpdate(OVersionRecordConflictStrategy.java:42)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.checkAndIncrementVersion(OAbstractPaginatedStorage.java:2298)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.doUpdateRecord(OAbstractPaginatedStorage.java:1930)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.updateRecord(OAbstractPaginatedStorage.java:866)
	at com.orientechnologies.orient.server.distributed.ODistributedStorage.updateRecord(ODistributedStorage.java:700)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.executeSaveRecord(ODatabaseDocumentTx.java:1901)
	at com.orientechnologies.orient.core.tx.OTransactionOptimistic.addRecord(OTransactionOptimistic.java:432)
	at com.orientechnologies.orient.core.tx.OTransactionOptimistic.saveRecord(OTransactionOptimistic.java:363)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.save(ODatabaseDocumentTx.java:2464)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.save(ODatabaseDocumentTx.java:1)
	at com.orientechnologies.orient.core.record.impl.ODocument.save(ODocument.java:1725)
	at com.orientechnologies.orient.core.record.impl.ODocument.save(ODocument.java:1716)
	at com.orientechnologies.orient.core.record.impl.ODocument.save(ODocument.java:1)
	at com.orientechnologies.orient.core.record.ORecordAbstract.save(ORecordAbstract.java:1)
	at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinaryV0.recursiveLinkSave(ORecordSerializerBinaryV0.java:671)
	at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinaryV0.writeOptimizedLink(ORecordSerializerBinaryV0.java:685)
	at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinaryV0.writeSingleValue(ORecordSerializerBinaryV0.java:569)
	at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinaryV0.serialize(ORecordSerializerBinaryV0.java:258)
	at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinary.toStream(ORecordSerializerBinary.java:105)
	at com.orientechnologies.orient.core.record.impl.ODocument.toStream(ODocument.java:2234)
	at com.orientechnologies.orient.core.record.impl.ODocument.toStream(ODocument.java:664)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.commitEntry(OAbstractPaginatedStorage.java:2347)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.commit(OAbstractPaginatedStorage.java:1123)
	at com.orientechnologies.orient.server.distributed.ODistributedStorage.commit(ODistributedStorage.java:960)
	at com.orientechnologies.orient.core.tx.OTransactionOptimistic.doCommit(OTransactionOptimistic.java:609)
	at com.orientechnologies.orient.core.tx.OTransactionOptimistic.commit(OTransactionOptimistic.java:156)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.commit(ODatabaseDocumentTx.java:2578)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.commit(ODatabaseDocumentTx.java:2547)
	at com.orientechnologies.orient.server.distributed.task.OTxTask.execute(OTxTask.java:129)
	at com.orientechnologies.orient.server.hazelcast.OHazelcastPlugin.executeOnLocalNode(OHazelcastPlugin.java:805)
	at com.orientechnologies.orient.server.hazelcast.ODistributedWorker.onMessage(ODistributedWorker.java:296)
	at com.orientechnologies.orient.server.hazelcast.ODistributedWorker.run(ODistributedWorker.java:119)

It happens because as you said on the original node the vertex version is updated asynchronously, so the replication operation still contains the non-updated version of the vertex.
I think, the replication operation should be performed only after the version is increased.
What's your opinion?

**Comment by lvca** [comment]
Actually in async mod OrientDB (1) writes on local node, create an (2) async req and (3) returns the value. We could work on assigning right versions after (1), so in this way it would be "synchronized". WDYT?

**Comment by ylopotun** [comment]
Exactly. We need to make sure that in ODistributedStorage.commit when we create a txTask the record we put there has the right version.
Right now it might happen that we put there a record with an old version, which is causing the CME on the distributed node, e.g.:

	Line 714: 2015-08-11 17:30:41:721 FINE  [node1] Added tx entry: (ORecordOperation [record=vertextype#12:0{out_edgetype:[size=14]} v14, type=UPDATE]) [ODistributedStorage]
	Line 726: 2015-08-11 17:30:41:728 FINE  [node1] Added tx entry: (ORecordOperation [record=vertextype#12:0{out_edgetype:[size=15]} v15, type=UPDATE]) [ODistributedStorage]
	Line 735: 2015-08-11 17:30:41:732 FINE  [node1] Added tx entry: (ORecordOperation [record=vertextype#12:0{out_edgetype:[size=16]} v15, type=UPDATE]) [ODistributedStorage]
	Line 747: 2015-08-11 17:30:41:739 FINE  [node1] Added tx entry: (ORecordOperation [record=vertextype#12:0{out_edgetype:[size=17]} v16, type=UPDATE]) [ODistributedStorage]

Notice two entries with the same v15.

**Comment by lvca** [comment]
Fixed ;-)

**Comment by lvca** [comment]
Please could you retry also the other issue? If it's fixed like this please close it ;-)
