### ISSUE TITLE
OObjectDatabasePool.global().acquire() DEPRECATED

### ISSUE THREAD

**Issue by kaaljabr** [orientechnologies/orientdb#4745]
OObjectDatabasePool.global().acquire 
is deprecated now, and returns null when called. how shall I get an instance of OObjectDatabaseTx now?

**Comment by laa** [comment]
HI,
You may use following approach create document database using com.orientechnologies.orient.core.db.OPartitionedDatabasePool and then call constructor  public OObjectDatabaseTx(ODatabaseDocumentTx iDatabase).

**Comment by kaaljabr** [comment]
I am getting an exception immediately when initializing OPartitionedDatabasePool 
```
OPartitionedDatabasePool opDatabasePool = new OPartitionedDatabasePool(
				"remote:localhost/db","username","password");
ODatabaseDocumentTx oDatabaseDocumentTx = opDatabasePool.acquire();
return new OObjectDatabaseTx(oDatabaseDocumentTx);
```
The exception is copied below
```
java.lang.VerifyError: Bad type on operand stack
Exception Details:
  Location:
    com/orientechnologies/orient/core/Orient.startup()Lcom/orientechnologies/orient/core/Orient; @78: putfield
  Reason:
    Type 'com/orientechnologies/common/profiler/OProfilerStub' (current frame, stack[1]) is not assignable to 'com/orientechnologies/common/profiler/OProfiler'
  Current Frame:
    bci: @78
    flags: { }
    locals: { 'com/orientechnologies/orient/core/Orient' }
    stack: { 'com/orientechnologies/orient/core/Orient', 'com/orientechnologies/common/profiler/OProfilerStub' }
  Bytecode:
    0x0000000: 2ab4 0015 b900 3801 00b9 0039 0100 2ab4
    0x0000010: 0024 9900 152a 4c2a b400 15b9 0038 0100
    0x0000020: b900 3a01 002b b02a 123b b800 2cb6 003c
    0x0000030: b500 3d2a b400 3ec7 000f 2abb 003f 5904
    0x0000040: b700 40b5 003e 2abb 0041 59b7 0042 b500
    0x0000050: 432a bb00 4459 b700 45b5 0046 2ab4 0047
    0x0000060: c700 152a bb00 4859 b700 49b5 0047 2ab4
    0x0000070: 0047 b600 4ab8 004b b600 4c3c 2abb 004d
    0x0000080: 591b 1b06 6814 004e b200 50bb 0051 592a
    0x0000090: 1b11 01f4 68b7 0052 b700 53b5 0054 2abb
    0x00000a0: 0055 59b7 0056 b600 572a bb00 5859 b700
    0x00000b0: 59b6 0057 2a12 5ab7 005b b200 5cb6 005d
    0x00000c0: 9900 09b2 005e b800 5f2a 04b5 0024 2ab4
    0x00000d0: 001e b900 6001 004d 2cb9 0061 0100 9900
    0x00000e0: 2e2c b900 6201 00c0 0063 4e2d c600 092d
    0x00000f0: b900 6401 00a7 0014 3a04 b800 662a 1267
    0x0000100: 1904 03bd 0068 b600 69a7 ffcf 2ab7 006a
    0x0000110: 2ab4 001f b900 6001 004d 2cb9 0061 0100
    0x0000120: 9900 3d2c b900 6201 00c0 006b 4e2d c600
    0x0000130: 182d b600 6cc0 0063 3a04 1904 c600 0a19
    0x0000140: 04b9 0064 0100 a700 143a 04b8 0066 2a12
    0x0000150: 6719 0403 bd00 68b6 0069 a7ff c02a b400
    0x0000160: 15b9 0038 0100 b900 3a01 00a7 0016 3a05
    0x0000170: 2ab4 0015 b900 3801 00b9 003a 0100 1905
    0x0000180: bf2a b0                                
  Exception Handler Table:
    bci [235, 245] => handler: 248
    bci [301, 326] => handler: 329
    bci [14, 23] => handler: 366
    bci [39, 349] => handler: 366
    bci [366, 368] => handler: 366
  Stackmap Table:
    same_frame(@39)
    same_frame(@70)
    same_frame(@117)
    append_frame(@201,Integer)
    append_frame(@216,Object[#349])
    append_frame(@245,Object[#350])
    same_locals_1_stack_item_frame(@248,Object[#351])
    chop_frame(@265,1)
    chop_frame(@268,1)
    append_frame(@282,Object[#349])
    append_frame(@326,Object[#352])
    same_locals_1_stack_item_frame(@329,Object[#351])
    chop_frame(@346,1)
    chop_frame(@349,2)
    same_locals_1_stack_item_frame(@366,Object[#353])
    same_frame(@385)

	at com.orientechnologies.orient.core.serialization.serializer.record.string.ORecordSerializerStringAbstract.<clinit>(ORecordSerializerStringAbstract.java:52)
	at com.orientechnologies.orient.core.serialization.serializer.record.ORecordSerializerFactory.<init>(ORecordSerializerFactory.java:47)
	at com.orientechnologies.orient.core.serialization.serializer.record.ORecordSerializerFactory.<clinit>(ORecordSerializerFactory.java:37)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.<clinit>(ODatabaseDocumentTx.java:127)
	at com.orientechnologies.orient.core.db.OPartitionedDatabasePool.initQueue(OPartitionedDatabasePool.java:386)
	at com.orientechnologies.orient.core.db.OPartitionedDatabasePool.<init>(OPartitionedDatabasePool.java:186)
	at com.orientechnologies.orient.core.db.OPartitionedDatabasePool.<init>(OPartitionedDatabasePool.java:171)
	at com.alarabiya.sport.server.persistence.OrientDBManager.getOObjectDatabaseTx(OrientDBManager.java:54)
	at com.alarabiya.sport.server.persistence.OrientDBManager.initialize(OrientDBManager.java:28)
	at com.alarabiya.sport.server.servlet.SportsServletContextListener.contextInitialized(SportsServletContextListener.java:91)
	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:5016)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5524)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1575)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1565)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Aug 09, 2015 12:32:38 PM org.apache.catalina.core.StandardContext listenerStart
SEVERE: Exception sending context initialized event to listener instance of class com.alarabiya.sport.server.servlet.SportsServletContextListener
java.lang.NullPointerException
	at com.alarabiya.sport.server.persistence.OrientDBManager.initialize(OrientDBManager.java:36)
	at com.alarabiya.sport.server.servlet.SportsServletContextListener.contextInitialized(SportsServletContextListener.java:91)
	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:5016)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5524)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1575)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1565)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by AlainBod** [comment]
After migrating to 2.1.0 jars and server, I've got the same exception when doing:

```
private OrientGraphFactory factory = new OrientGraphFactory("remote:orient/v6", "xxx", "xxx").setupPool(1,10);

Exception Details:
  Location:
    com/orientechnologies/orient/core/Orient.startup()Lcom/orientechnologies/orient/core/Orient; @78: putfield
  Reason:
    Type 'com/orientechnologies/common/profiler/OProfilerStub' (current frame, stack[1]) is not assignable to 'com/orientechnologies/common/profiler/OProfiler'
  Current Frame:
    bci: @78
    flags: { }
    locals: { 'com/orientechnologies/orient/core/Orient' }
    stack: { 'com/orientechnologies/orient/core/Orient', 'com/orientechnologies/common/profiler/OProfilerStub' }
  Bytecode:
    0x0000000: 2ab4 0015 b900 3801 00b9 0039 0100 2ab4
    0x0000010: 0024 9900 152a 4c2a b400 15b9 0038 0100
    0x0000020: b900 3a01 002b b02a 123b b800 2cb6 003c
    0x0000030: b500 3d2a b400 3ec7 000f 2abb 003f 5904
    0x0000040: b700 40b5 003e 2abb 0041 59b7 0042 b500
    0x0000050: 432a bb00 4459 b700 45b5 0046 2ab4 0047
    0x0000060: c700 152a bb00 4859 b700 49b5 0047 2ab4
    0x0000070: 0047 b600 4ab8 004b b600 4c3c 2abb 004d
    0x0000080: 591b 1b06 6814 004e b200 50bb 0051 592a
    0x0000090: 1b11 01f4 68b7 0052 b700 53b5 0054 2abb
    0x00000a0: 0055 59b7 0056 b600 572a bb00 5859 b700
    0x00000b0: 59b6 0057 2a12 5ab7 005b b200 5cb6 005d
    0x00000c0: 9900 09b2 005e b800 5f2a 04b5 0024 2ab4
    0x00000d0: 001e b900 6001 004d 2cb9 0061 0100 9900
    0x00000e0: 2e2c b900 6201 00c0 0063 4e2d c600 092d
    0x00000f0: b900 6401 00a7 0014 3a04 b800 662a 1267
    0x0000100: 1904 03bd 0068 b600 69a7 ffcf 2ab7 006a
    0x0000110: 2ab4 001f b900 6001 004d 2cb9 0061 0100
    0x0000120: 9900 3d2c b900 6201 00c0 006b 4e2d c600
    0x0000130: 182d b600 6cc0 0063 3a04 1904 c600 0a19
    0x0000140: 04b9 0064 0100 a700 143a 04b8 0066 2a12
    0x0000150: 6719 0403 bd00 68b6 0069 a7ff c02a b400
    0x0000160: 15b9 0038 0100 b900 3a01 00a7 0016 3a05
    0x0000170: 2ab4 0015 b900 3801 00b9 003a 0100 1905
    0x0000180: bf2a b0                                
  Exception Handler Table:
    bci [235, 245] => handler: 248
    bci [301, 326] => handler: 329
    bci [14, 23] => handler: 366
    bci [39, 349] => handler: 366
    bci [366, 368] => handler: 366
  Stackmap Table:
    same_frame(@39)
    same_frame(@70)
    same_frame(@117)
    append_frame(@201,Integer)
    append_frame(@216,Object[#349])
    append_frame(@245,Object[#350])
    same_locals_1_stack_item_frame(@248,Object[#351])
    chop_frame(@265,1)
    chop_frame(@268,1)
    append_frame(@282,Object[#349])
    append_frame(@326,Object[#352])
    same_locals_1_stack_item_frame(@329,Object[#351])
    chop_frame(@346,1)
    chop_frame(@349,2)
    same_locals_1_stack_item_frame(@366,Object[#353])
    same_frame(@385)

	at com.orientechnologies.orient.core.serialization.serializer.record.string.ORecordSerializerStringAbstract.<clinit>(ORecordSerializerStringAbstract.java:52)
	at com.orientechnologies.orient.core.serialization.serializer.record.ORecordSerializerFactory.<init>(ORecordSerializerFactory.java:47)
	at com.orientechnologies.orient.core.serialization.serializer.record.ORecordSerializerFactory.<clinit>(ORecordSerializerFactory.java:37)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.<clinit>(ODatabaseDocumentTx.java:127)
	at com.orientechnologies.orient.core.db.OPartitionedDatabasePool.initQueue(OPartitionedDatabasePool.java:386)
	at com.orientechnologies.orient.core.db.OPartitionedDatabasePool.<init>(OPartitionedDatabasePool.java:186)
	at com.tinkerpop.blueprints.impls.orient.OrientGraphFactory.setupPool(OrientGraphFactory.java:161)
```

Does that mean I can't migrate to 2.1.0 until this bug is fixed ? Or is there a workaround ?

**Comment by laa** [comment]
Hi,
This exception has nothing to do with pool it is serializer exception. Assigned to @tglman

**Comment by jamesa0008** [comment]
I'm experiencing the same exception using Orient 2.1.1. Runs fine when I run my Grails app in Eclipse  (GGTS) but fails when deploying to either Tomcat 7.0.64 or 8.0.26.

**Comment by laa** [comment]
Cool I close the issue.
