### ISSUE TITLE
FileNotFoundException during creation of class/cluster

### ISSUE THREAD

**Issue by wouterv** [orientechnologies/orientdb#4778]
We are currently migrating our database to orient and during that process we are creating a lot of classes/clusters. We get the following error quite often, although not everytime on the same filename:

```
Caused by: com.orientechnologies.orient.core.exception.OStorageException: Error in creation of new cluster 'bdh_floormanager_nl_vat
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.addCluster(OAbstractPaginatedStorage.java:414) ~[orientdb-core-2.0.14.jar:2.0.14]
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.addCluster(ODatabaseDocumentTx.java:1189) ~[orientdb-core-2.0.14.jar:2.0.14]
	at com.orientechnologies.orient.core.metadata.schema.OSchemaShared.createClusters(OSchemaShared.java:1045) ~[orientdb-core-2.0.14.jar:2.0.14]
	at com.orientechnologies.orient.core.metadata.schema.OSchemaShared.createClass(OSchemaShared.java:367) ~[orientdb-core-2.0.14.jar:2.0.14]
	at com.orientechnologies.orient.core.metadata.schema.OSchemaProxy.createClass(OSchemaProxy.java:96) ~[orientdb-core-2.0.14.jar:2.0.14]
	at <ourpackage>.SchemaUtil$SchemaUpdater.createClass(SchemaUtil.java:236) ~[meta-core-1.5.0-SNAPSHOT.jar:na]
... 
Caused by: com.orientechnologies.orient.core.exception.OStorageException: Error during creation of cluster with name bdh_floormanager_nl_vat
	at com.orientechnologies.orient.core.storage.impl.local.paginated.OPaginatedCluster.create(OPaginatedCluster.java:187) ~[orientdb-core-2.0.14.jar:2.0.14]
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.addClusterInternal(OAbstractPaginatedStorage.java:1788) ~[orientdb-core-2.0.14.jar:2.0.14]
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.doAddCluster(OAbstractPaginatedStorage.java:1761) ~[orientdb-core-2.0.14.jar:2.0.14]
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.addCluster(OAbstractPaginatedStorage.java:411) ~[orientdb-core-2.0.14.jar:2.0.14]
	... 11 common frames omitted
Caused by: java.io.FileNotFoundException: /data/orient/ourdb/bdh_floormanager_nl_vat.cpm
	at com.orientechnologies.orient.core.storage.fs.OAbstractFile.openChannel(OAbstractFile.java:665) ~[orientdb-core-2.0.14.jar:2.0.14]
	at com.orientechnologies.orient.core.storage.fs.OAbstractFile.create(OAbstractFile.java:236) ~[orientdb-core-2.0.14.jar:2.0.14]
	at com.orientechnologies.orient.core.storage.fs.OFileClassic.create(OFileClassic.java:265) ~[orientdb-core-2.0.14.jar:2.0.14]
	at com.orientechnologies.orient.core.index.hashindex.local.cache.OWOWCache.addFile(OWOWCache.java:883) ~[orientdb-core-2.0.14.jar:2.0.14]
	at com.orientechnologies.orient.core.index.hashindex.local.cache.OWOWCache.addFile(OWOWCache.java:374) ~[orientdb-core-2.0.14.jar:2.0.14]
	at com.orientechnologies.orient.core.index.hashindex.local.cache.OReadWriteDiskCache.addFile(OReadWriteDiskCache.java:217) ~[orientdb-core-2.0.14.jar:2.0.14]
	at com.orientechnologies.orient.core.storage.impl.local.paginated.atomicoperations.OAtomicOperation.commitChanges(OAtomicOperation.java:335) ~[orientdb-core-2.0.14.jar:2.0.14]
	at com.orientechnologies.orient.core.storage.impl.local.paginated.atomicoperations.OAtomicOperationsManager.endAtomicOperation(OAtomicOperationsManager.java:124) ~[orientdb-core-2.0.14.jar:2.0.14]
	at com.orientechnologies.orient.core.storage.impl.local.paginated.base.ODurableComponent.endAtomicOperation(ODurableComponent.java:99) ~[orientdb-core-2.0.14.jar:2.0.14]
	at com.orientechnologies.orient.core.storage.impl.local.paginated.OPaginatedCluster.create(OPaginatedCluster.java:184) ~[orientdb-core-2.0.14.jar:2.0.14]
	... 14 common frames omitted
```

There is one thing I notice, and that is the following code bit in OAbstractFile:
```
      for (int i = 0; i < OPEN_RETRY_MAX; ++i)
        try {
          accessFile = new RandomAccessFile(osFile, mode);
          break;
        } catch (FileNotFoundException e) {
          if (i == OPEN_DELAY_RETRY)
            throw e;

          // TRY TO RE-CREATE THE DIRECTORY (THIS HAPPENS ON WINDOWS AFTER A DELETE IS PENDING, USUALLY WHEN REOPEN THE DB VERY
          // FREQUENTLY)
          osFile.getParentFile().mkdirs();
          try {
            Thread.sleep(OPEN_DELAY_RETRY);
          } catch (InterruptedException e1) {
            Thread.currentThread().interrupt();
          }
        }
```
The row " if (i == OPEN_DELAY_RETRY)" seems wrong to me, it retries OPEN_RETRY_MAX, which is 10 and the other is 100, so it will never rethrow the actual error (my guess is that this is a typo and that MAX was meant). 

Instead, it will fail at the next line:

```
      if (accessFile == null)
        throw new FileNotFoundException(osFile.getAbsolutePath());
```
Which doesn't give us any info at all, except that the file isn't there. Fixing the if statement probably won't do us any good either, as the file really isn't there on the filesystem, we checked that.

We are using orient 2.0.14 and are running on Ubuntu 14.0.4.3.
Our java version is 1.7.0_80

**Comment by laa** [comment]
Hi, you have to increase limit of open files in you os. I suppose that is Linux build. Is not it ?

**Comment by wouterv** [comment]
Yep, linux. We increased the limit and the problem was gone, thanks. You might want to give a better error perhaps?

**Comment by laa** [comment]
We would give better error, but we use Java 7 API and can not use modern FIle API and error handling.

**Comment by wouterv** [comment]
There is always to option to catch the FNFE and rethrow with a hint "you might need to increate the open file limit"

**Comment by laa** [comment]
Yes, but only in case if that is only one cause of this exception,
otherwise it will be only misleading.
