### ISSUE TITLE
NullPointerException from SELECT @this.exclude('name') FROM OUser [v2.1.0]

### ISSUE THREAD

**Issue by mwsam** [orientechnologies/orientdb#4796]
Using OrientDB v2.1.0, running the following SQL on a brand new database throws NullPointerException from the console:

```sql
SELECT @this.exclude('name') FROM OUser
```

**Comment by nagarajasr** [comment]
server logs:

```
{db=nagu} Error on unmarshalling record #-2:0 (com.orientechnologies.orient.core.exception.OValidationException: The field 'OUser.name' is mandatory, but not found on record: OUser#5:0{name:null,password:{SHA-256}8C6976E5B5410415BDE908BD4DEE15DFB167A9C873FC4BB8A81F6F2AB448A918,status:ACTIVE,roles:[1]} v1)
com.orientechnologies.orient.core.exception.OValidationException: The field 'OUser.name' is mandatory, but not found on record: OUser#5:0{name:null,password:{SHA-256}8C6976E5B5410415BDE908BD4DEE15DFB167A9C873FC4BB8A81F6F2AB448A918,status:ACTIVE,roles:[1]} v1
        at com.orientechnologies.orient.core.record.impl.ODocument.validateField(ODocument.java:268)
        at com.orientechnologies.orient.core.record.impl.ODocument.validate(ODocument.java:1951)
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.save(ODatabaseDocumentTx.java:2415)
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.save(ODatabaseDocumentTx.java:120)
        at com.orientechnologies.orient.core.record.impl.ODocument.save(ODocument.java:1725)
        at com.orientechnologies.orient.core.record.impl.ODocument.save(ODocument.java:1716)
        at com.orientechnologies.orient.core.record.impl.ODocument.save(ODocument.java:80)
        at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinaryV0.recursiveLinkSave(ORecordSerializerBinaryV0.java:671)
        at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinaryV0.writeOptimizedLink(ORecordSerializerBinaryV0.java:685)
        at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinaryV0.writeSingleValue(ORecordSerializerBinaryV0.java:569)
        at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinaryV0.serialize(ORecordSerializerBinaryV0.java:258)
        at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinary.toStream(ORecordSerializerBinary.java:105)
        at com.orientechnologies.orient.core.record.impl.ODocument.toStream(ODocument.java:2234)
        at com.orientechnologies.orient.core.record.impl.ODocument.toStream(ODocument.java:664)
        at com.orientechnologies.orient.server.network.protocol.binary.OBinaryNetworkProtocolAbstract.getRecordBytes(OBinaryNetworkProtocolAbstract.java:424)
        at com.orientechnologies.orient.server.network.protocol.binary.OBinaryNetworkProtocolAbstract.writeRecord(OBinaryNetworkProtocolAbstract.java:439)
        at com.orientechnologies.orient.server.network.protocol.binary.OBinaryNetworkProtocolAbstract.writeIdentifiable(OBinaryNetworkProtocolAbstract.java:141)
        at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.serializeValue(ONetworkProtocolBinary.java:1384)
        at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.command(ONetworkProtocolBinary.java:1332)
        at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.executeRequest(ONetworkProtocolBinary.java:396)
        at com.orientechnologies.orient.server.network.protocol.binary.OBinaryNetworkProtocolAbstract.execute(OBinaryNetworkProtocolAbstract.java:223)
        at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:77)

2015-08-17 21:38:57:419 WARNI {db=nagu} Cannot serialize record: #-2:0{this:#5:0} v0 [ONetworkProtocolBinary]{db=nagu} Error on unmarshalling record #-2:1 (com.orientechnologies.orient.core.exception.OValidationException: The field 'OUser.name' is mandatory, but not found on record: OUser#5:1{name:null,password:{SHA-256}3D0941964AA3EBDCB00CCEF58B1BB399F9F898465E9886D5AEC7F31090A0FB30,status:ACTIVE,roles:[1]} v1)
com.orientechnologies.orient.core.exception.OValidationException: The field 'OUser.name' is mandatory, but not found on record: OUser#5:1{name:null,password:{SHA-256}3D0941964AA3EBDCB00CCEF58B1BB399F9F898465E9886D5AEC7F31090A0FB30,status:ACTIVE,roles:[1]} v1
        at com.orientechnologies.orient.core.record.impl.ODocument.validateField(ODocument.java:268)
        at com.orientechnologies.orient.core.record.impl.ODocument.validate(ODocument.java:1951)
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.save(ODatabaseDocumentTx.java:2415)
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.save(ODatabaseDocumentTx.java:120)
        at com.orientechnologies.orient.core.record.impl.ODocument.save(ODocument.java:1725)
        at com.orientechnologies.orient.core.record.impl.ODocument.save(ODocument.java:1716)
        at com.orientechnologies.orient.core.record.impl.ODocument.save(ODocument.java:80)
        at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinaryV0.recursiveLinkSave(ORecordSerializerBinaryV0.java:671)
        at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinaryV0.writeOptimizedLink(ORecordSerializerBinaryV0.java:685)
        at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinaryV0.writeSingleValue(ORecordSerializerBinaryV0.java:569)
        at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinaryV0.serialize(ORecordSerializerBinaryV0.java:258)
        at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinary.toStream(ORecordSerializerBinary.java:105)
        at com.orientechnologies.orient.core.record.impl.ODocument.toStream(ODocument.java:2234)
        at com.orientechnologies.orient.core.record.impl.ODocument.toStream(ODocument.java:664)
        at com.orientechnologies.orient.server.network.protocol.binary.OBinaryNetworkProtocolAbstract.getRecordBytes(OBinaryNetworkProtocolAbstract.java:424)
        at com.orientechnologies.orient.server.network.protocol.binary.OBinaryNetworkProtocolAbstract.writeRecord(OBinaryNetworkProtocolAbstract.java:439)
        at com.orientechnologies.orient.server.network.protocol.binary.OBinaryNetworkProtocolAbstract.writeIdentifiable(OBinaryNetworkProtocolAbstract.java:141)
        at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.serializeValue(ONetworkProtocolBinary.java:1384)
        at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.command(ONetworkProtocolBinary.java:1332)
        at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.executeRequest(ONetworkProtocolBinary.java:396)
        at com.orientechnologies.orient.server.network.protocol.binary.OBinaryNetworkProtocolAbstract.execute(OBinaryNetworkProtocolAbstract.java:223)
        at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:77)

2015-08-17 21:38:57:421 WARNI {db=nagu} Cannot serialize record: #-2:1{this:#5:1} v0 [ONetworkProtocolBinary]{db=nagu} Error on unmarshalling record #-2:2 (com.orientechnologies.orient.core.exception.OValidationException: The field 'OUser.name' is mandatory, but not found on record: OUser#5:2{name:null,password:{SHA-256}B93006774CBDD4B299389A03AC3D88C3A76B460D538795BC12718011A909FBA5,status:ACTIVE,roles:[1]} v1)
com.orientechnologies.orient.core.exception.OValidationException: The field 'OUser.name' is mandatory, but not found on record: OUser#5:2{name:null,password:{SHA-256}B93006774CBDD4B299389A03AC3D88C3A76B460D538795BC12718011A909FBA5,status:ACTIVE,roles:[1]} v1
        at com.orientechnologies.orient.core.record.impl.ODocument.validateField(ODocument.java:268)
        at com.orientechnologies.orient.core.record.impl.ODocument.validate(ODocument.java:1951)
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.save(ODatabaseDocumentTx.java:2415)
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.save(ODatabaseDocumentTx.java:120)
        at com.orientechnologies.orient.core.record.impl.ODocument.save(ODocument.java:1725)
        at com.orientechnologies.orient.core.record.impl.ODocument.save(ODocument.java:1716)
        at com.orientechnologies.orient.core.record.impl.ODocument.save(ODocument.java:80)
        at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinaryV0.recursiveLinkSave(ORecordSerializerBinaryV0.java:671)
        at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinaryV0.writeOptimizedLink(ORecordSerializerBinaryV0.java:685)
        at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinaryV0.writeSingleValue(ORecordSerializerBinaryV0.java:569)
        at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinaryV0.serialize(ORecordSerializerBinaryV0.java:258)
        at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinary.toStream(ORecordSerializerBinary.java:105)
        at com.orientechnologies.orient.core.record.impl.ODocument.toStream(ODocument.java:2234)
        at com.orientechnologies.orient.core.record.impl.ODocument.toStream(ODocument.java:664)
        at com.orientechnologies.orient.server.network.protocol.binary.OBinaryNetworkProtocolAbstract.getRecordBytes(OBinaryNetworkProtocolAbstract.java:424)
        at com.orientechnologies.orient.server.network.protocol.binary.OBinaryNetworkProtocolAbstract.writeRecord(OBinaryNetworkProtocolAbstract.java:439)
        at com.orientechnologies.orient.server.network.protocol.binary.OBinaryNetworkProtocolAbstract.writeIdentifiable(OBinaryNetworkProtocolAbstract.java:141)
        at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.serializeValue(ONetworkProtocolBinary.java:1384)
        at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.command(ONetworkProtocolBinary.java:1332)
        at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.executeRequest(ONetworkProtocolBinary.java:396)
        at com.orientechnologies.orient.server.network.protocol.binary.OBinaryNetworkProtocolAbstract.execute(OBinaryNetworkProtocolAbstract.java:223)
        at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:77)

2015-08-17 21:38:57:423 WARNI {db=nagu} Cannot serialize record: #-2:2{this:#5:2} v0 [ONetworkProtocolBinary]
```

after the NPE, no other operation can be performed from the orientdb console (it hangs)

**Comment by nagarajasr** [comment]
interestingly, i created a custom class with a mandatory prop and ran the same query, excluding the mandatory prop. this time, the error message on the server was the same as before, however no NPE on the console. the console still hangs after this. totally weird.

```sql

orientdb {db=nagu}> create class myclass

Class created successfully. Total classes in database now: 46

orientdb {db=nagu}> create property myclass.myprop string

Property created successfully with id=1

orientdb {db=nagu}> alter property myclass.myprop mandatory=true

Property updated successfully

orientdb {db=nagu}> insert into myclass set myprop="abc"

Inserted record 'myclass#43:0{myprop:abc} v1' in 0.029000 sec(s).

orientdb {db=nagu}> select @this.exclude('myprop') from myclass

----+------
#   |@CLASS
----+------
0   |null
----+------

1 item(s) found. Query executed in 0.011 sec(s).
orientdb {db=nagu}>

orientdb {db=nagu}> select @this.exclude('myprop') from myclass

(hangs forever)
```

**Comment by lvca** [comment]
Really weird. I'm on it.

**Comment by lvca** [comment]
Cannot reproduce on 2.1.1-SNAPSHOT. Please can you confirm it?

**Comment by mwsam** [comment]
Problem still exists on snapshot 2.1.1-20150812, I couldn't find snapshot more recent than that for v2.1.1 in https://oss.sonatype.org/content/repositories/snapshots/com/orientechnologies/orientdb-community/2.1.1-SNAPSHOT/

But it works good with snapshot 2.2.0-20150819.

**Comment by lvca** [comment]
I disabled any possible save during network protocol operation. In OrientDB 2.2 we separated the toStream() by save(), so this problem can't happen for its nature.

**Comment by lvca** [comment]
Please let me know if this is working also in 2.1.x.

**Comment by lvca** [comment]
Backported also to 2.0.x (2.0.15+)
