### ISSUE TITLE
Can't delete sub class of ORestricted

### ISSUE THREAD

**Issue by PhantomYdn** [orientechnologies/orientdb#4797]
Guys,

There is the very straight forward testcase which is failing:

```java
@Test
	public void testDeletionOfDependentClass()
	{
		ODatabaseDocument db = wicket.getTester().getDatabase();
		OSchema schema = db.getMetadata().getSchema();
		OClass oRestricted = schema.getClass(OSecurityShared.RESTRICTED_CLASSNAME);
		OClass classA = schema.createClass("TestDeletionOfDependentClass", oRestricted);
		schema.dropClass(classA.getName());
	}
```

Result:

```java
com.orientechnologies.orient.core.exception.OStorageException: Error while removing cluster '13'
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.dropCluster(OAbstractPaginatedStorage.java:552)
	at com.orientechnologies.orient.core.metadata.schema.OSchemaShared.deleteDefaultCluster(OSchemaShared.java:1193)
	at com.orientechnologies.orient.core.metadata.schema.OSchemaShared.dropClassInternal(OSchemaShared.java:1181)
	at com.orientechnologies.orient.core.metadata.schema.OSchemaShared.dropClass(OSchemaShared.java:549)
	at com.orientechnologies.orient.core.metadata.schema.OSchemaProxy.dropClass(OSchemaProxy.java:156)
	at ru.ydn.wicket.wicketorientdb.orientdb.TestInAppOrientDBCompatibility.testDeletionOfDependentClass(TestInAppOrientDBCompatibility.java:660)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.apache.wicket.util.tester.WicketTesterScope$1.evaluate(WicketTesterScope.java:43)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)
Caused by: com.orientechnologies.orient.core.exception.OSecurityException: Class ORestricted cannot be truncated because has record level security enabled (extends ORestricted)
	at com.orientechnologies.orient.core.storage.OStorageAbstract.checkForClusterPermissions(OStorageAbstract.java:207)
	at com.orientechnologies.orient.core.storage.impl.local.paginated.OPaginatedCluster.truncate(OPaginatedCluster.java:992)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.dropCluster(OAbstractPaginatedStorage.java:539)
	... 30 more

```

**Comment by PhantomYdn** [comment]
Guys,
Any chance to have fix of this in 2.1.1?

**Comment by lvca** [comment]
This is correct. Disconnect the inheritance before dropping the class.

**Comment by PhantomYdn** [comment]
@lvca , according to code disconnect with super classes is done during class dropping. But this particular case leads to the error. Imho, disconnect should not be required for such operation as drop class.

**Comment by PhantomYdn** [comment]
@lvca , how about a little bit more complecated testcase?

```java
@Test
	public void testDeletionOfDependentClass()
	{
		ODatabaseDocument db = wicket.getTester().getDatabase();
		OSchema schema = db.getMetadata().getSchema();
		OClass oRestricted = schema.getClass(OSecurityShared.RESTRICTED_CLASSNAME);
		OClass classA = schema.createClass("TestDeletionOfDependentClassA", oRestricted);
		OClass classB = schema.createClass("TestDeletionOfDependentClassB", classA);
		schema.dropClass(classB.getName());
	}
```

I think it should be fixed in OrientDB. In example below classB can't be disconnected from ORestricted. And if we disconnect classA it will hurt other good objects/classes.

**Comment by lvca** [comment]
I don't remember why we did it, probably to let users be careful with it? I think we could remove it. Anybody against it?
