### ISSUE TITLE
NullPointerException in OrientBaseGraph when detaching OrientElement

### ISSUE THREAD

**Issue by enRGi** [orientechnologies/orientdb#4821]
in v2.1.0 an NPE occurs in Line 292 in OrientBaseGraph.java when detaching an OrientElement previously.

**Comment by lvca** [comment]
Do you have the full stack trace?

**Comment by enRGi** [comment]
Sure - This is a web application, so the connection to the database is established as suggested in your [documentation](http://orientdb.com/docs/last/Java-Web-Apps.html) via a Filter.
This is the stacktrace:
```java
org.apache.wicket.WicketRuntimeException: Method onRequest of interface org.apache.wicket.behavior.IBehaviorListener targeted at org.apache.wicket.ajax.markup.html.form.AjaxSubmitLink$1@3dde9105 on component [AjaxSubmitLink [Component id = link]] threw an exception
	at org.apache.wicket.RequestListenerInterface.internalInvoke(RequestListenerInterface.java:268)
	at org.apache.wicket.RequestListenerInterface.invoke(RequestListenerInterface.java:241)
	at org.apache.wicket.core.request.handler.ListenerInterfaceRequestHandler.invokeListener(ListenerInterfaceRequestHandler.java:250)
	at org.apache.wicket.core.request.handler.ListenerInterfaceRequestHandler.respond(ListenerInterfaceRequestHandler.java:236)
	at org.apache.wicket.request.cycle.RequestCycle$HandlerExecutor.respond(RequestCycle.java:862)
	at org.apache.wicket.request.RequestHandlerStack.execute(RequestHandlerStack.java:64)
	at org.apache.wicket.request.cycle.RequestCycle.execute(RequestCycle.java:261)
	at org.apache.wicket.request.cycle.RequestCycle.processRequest(RequestCycle.java:218)
	at org.apache.wicket.request.cycle.RequestCycle.processRequestAndDetach(RequestCycle.java:289)
	at org.apache.wicket.protocol.http.WicketFilter.processRequestCycle(WicketFilter.java:259)
	at org.apache.wicket.protocol.http.WicketFilter.processRequest(WicketFilter.java:201)
	at org.apache.wicket.protocol.http.WicketServlet.doPost(WicketServlet.java:159)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:808)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1669)
	at com.befinesolutions.cryptshare.server.OrientDBFilter.doFilter(OrientDBFilter.java:53)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:585)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:577)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:223)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:52)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
	at org.eclipse.jetty.server.Server.handle(Server.java:497)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:310)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257)
	at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:540)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.apache.wicket.RequestListenerInterface.internalInvoke(RequestListenerInterface.java:258)
	... 35 more
Caused by: java.lang.reflect.UndeclaredThrowableException
	at com.sun.proxy.$Proxy116.getVerifications(Unknown Source)
	at com.befinesolutions.cryptshare.server.business.service.TransferService.completeVerification(TransferService.java:721)
	at com.befinesolutions.cryptshare.server.control.BrowserVerificationController.completeVerification(BrowserVerificationController.java:45)
	at com.befinesolutions.cryptshare.server.component.application.VeriCodePanel$2.onSubmit(VeriCodePanel.java:105)
	at com.befinesolutions.wicket.component.controls.DynamicSubmitButton$1.onSubmit(DynamicSubmitButton.java:70)
	at org.apache.wicket.ajax.markup.html.form.AjaxSubmitLink$1.onSubmit(AjaxSubmitLink.java:116)
	at org.apache.wicket.ajax.form.AjaxFormSubmitBehavior$1.onSubmit(AjaxFormSubmitBehavior.java:182)
	at org.apache.wicket.markup.html.form.Form.delegateSubmit(Form.java:1266)
	at org.apache.wicket.markup.html.form.Form.process(Form.java:938)
	at org.apache.wicket.markup.html.form.Form.onFormSubmitted(Form.java:770)
	at org.apache.wicket.ajax.form.AjaxFormSubmitBehavior.onEvent(AjaxFormSubmitBehavior.java:159)
	at org.apache.wicket.ajax.AjaxEventBehavior.respond(AjaxEventBehavior.java:124)
	at org.apache.wicket.ajax.AbstractDefaultAjaxBehavior.onRequest(AbstractDefaultAjaxBehavior.java:633)
	... 40 more
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.tinkerpop.frames.modules.javahandler.JavaHandlerModule$3.invoke(JavaHandlerModule.java:134)
	at com.befinesolutions.cryptshare.server.data.transfer.SenderVertex$Impl_$$_jvst45b_2.getVerifications(SenderVertex$Impl_$$_jvst45b_2.java)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.tinkerpop.frames.modules.javahandler.JavaMethodHandler.processElement(JavaMethodHandler.java:32)
	at com.tinkerpop.frames.modules.javahandler.JavaMethodHandler.processElement(JavaMethodHandler.java:10)
	at com.tinkerpop.frames.CSFramedElement.invoke(CSFramedElement.java:98)
	... 53 more
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.tinkerpop.frames.modules.javahandler.JavaHandlerModule$3.invoke(JavaHandlerModule.java:143)
	at com.befinesolutions.cryptshare.server.data.transfer.SenderVertex$Impl_$$_jvst45b_2.getVerificationsIterable(SenderVertex$Impl_$$_jvst45b_2.java)
	at com.befinesolutions.cryptshare.server.data.transfer.SenderVertex$Impl.getVerifications(SenderVertex.java:132)
	at com.befinesolutions.cryptshare.server.data.transfer.SenderVertex$Impl_$$_jvst45b_2._d28getVerifications(SenderVertex$Impl_$$_jvst45b_2.java)
	... 66 more
Caused by: java.lang.NullPointerException
	at com.tinkerpop.blueprints.impls.orient.OrientBaseGraph.getEdgeClassNames(OrientBaseGraph.java:292)
	at com.tinkerpop.blueprints.impls.orient.OrientVertex.getVertices(OrientVertex.java:585)
	at com.tinkerpop.frames.annotations.AdjacencyAnnotationHandler.processVertex(AdjacencyAnnotationHandler.java:34)
	at com.tinkerpop.frames.annotations.AdjacencyAnnotationHandler.processElement(AdjacencyAnnotationHandler.java:26)
	at com.tinkerpop.frames.annotations.AdjacencyAnnotationHandler.processElement(AdjacencyAnnotationHandler.java:15)
	at com.tinkerpop.frames.CSFramedElement.invoke(CSFramedElement.java:104)
	at com.sun.proxy.$Proxy116.getVerificationsIterable(Unknown Source)
	... 74 more
```

**Comment by lvca** [comment]
Sorry, the documentation was outdated. I've just updated it:

http://orientdb.com/docs/last/Java-Web-Apps.html

**Comment by enRGi** [comment]
Thank you, but that wasn't the problem. I did of course open the connection with a graph.
```java
@Override
	public void doFilter(ServletRequest request, ServletResponse response, FilterChain chain) throws IOException, ServletException {
		OrientGraph graph = null;
		try {
			graph = orientDBClient.openConnection();
			chain.doFilter(request, response);
		} catch (Exception exc) {
			if (graph != null)
				graph.rollback();
			throw exc;
		} finally {
			if (graph != null)
				graph.shutdown();
		}
	}
```

**Comment by lvca** [comment]
Do you have the updated stack trace?

**Comment by enRGi** [comment]
Sorry, which updated stacktrace? The one I posted previously still applies.
