### ISSUE TITLE
"Class not a subtype" exceptions when running in OSGi environment

### ISSUE THREAD

**Issue by ylopotun** [orientechnologies/orientdb#4849]
When starting OrientDB as a graph DB in an OSGi environment, a few of "class not a subtype" exceptions get thrown, e.g:

orientdb-core bundle:
java.util.ServiceConfigurationError: com.orientechnologies.orient.core.sql.OCommandExecutorSQLFactory: Provider com.orientechnologies.orient.graph.sql.OGraphCommandExecutorSQLFactory not a subtype
	at java.util.ServiceLoader.fail(ServiceLoader.java:239)
	at java.util.ServiceLoader.access$300(ServiceLoader.java:185)
	at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:376)
	at java.util.ServiceLoader$LazyIterator.next(ServiceLoader.java:404)
	at java.util.ServiceLoader$1.next(ServiceLoader.java:480)

orientdb-server bundle:
[main] FATAL com.miranda.mcs.ucs.ds.persistence.orientdb.OrientDataManager - init
java.lang.ClassCastException: com.orientechnologies.orient.graph.handler.OGraphServerHandler cannot be cast to com.orientechnologies.orient.server.plugin.OServerPlugin
	at com.orientechnologies.orient.server.OServer.registerPlugins(OServer.java:963)
	at com.orientechnologies.orient.server.OServer.activate(OServer.java:338)

orientdb-distributed bundle:
java.util.ServiceConfigurationError: com.orientechnologies.orient.core.sql.OCommandExecutorSQLFactory: Provider com.orientechnologies.orient.server.distributed.sql.ODistributedCommandExecutorSQLFactory not a subtype
	at java.util.ServiceLoader.fail(ServiceLoader.java:239)
	at java.util.ServiceLoader.access$300(ServiceLoader.java:185)
	at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:376)
	at java.util.ServiceLoader$LazyIterator.next(ServiceLoader.java:404)
	at java.util.ServiceLoader$1.next(ServiceLoader.java:480)
	at com.orientechnologies.orient.core.sql.OSQLEngine.getCommandFactories(OSQLEngine.java:180)
	at com.orientechnologies.orient.core.sql.OSQLEngine.getCommandNames(OSQLEngine.java:236)
	at com.orientechnologies.orient.core.sql.OSQLEngine.getCommand(OSQLEngine.java:410)
	at com.orientechnologies.orient.core.sql.OCommandExecutorSQLDelegate.parse(OCommandExecutorSQLDelegate.java:70)
	at com.orientechnologies.orient.core.sql.OCommandExecutorSQLDelegate.parse(OCommandExecutorSQLDelegate.java:42)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.command(OAbstractPaginatedStorage.java:1447)
	at com.orientechnologies.orient.core.sql.query.OSQLQuery.run(OSQLQuery.java:72)
	at com.orientechnologies.orient.core.sql.query.OSQLSynchQuery.run(OSQLSynchQuery.java:85)
	at com.orientechnologies.orient.core.query.OQueryAbstract.execute(OQueryAbstract.java:33)
	at com.orientechnologies.orient.core.metadata.security.OSecurityShared.getRole(OSecurityShared.java:275)
	at com.orientechnologies.orient.core.metadata.security.OSecurityShared.createMetadata(OSecurityShared.java:366)
	at com.orientechnologies.orient.core.metadata.security.OSecurityShared.create(OSecurityShared.java:312)
	at com.orientechnologies.orient.core.metadata.security.OSecurityProxy.create(OSecurityProxy.java:74)
	at com.orientechnologies.orient.core.metadata.OMetadataDefault.create(OMetadataDefault.java:92)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.create(ODatabaseDocumentTx.java:415)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.create(ODatabaseDocumentTx.java:358)
	at com.tinkerpop.blueprints.impls.orient.OrientGraphFactory.getDatabase(OrientGraphFactory.java:128)
	at com.tinkerpop.blueprints.impls.orient.OrientGraphFactory.getDatabase(OrientGraphFactory.java:111)
	at com.tinkerpop.blueprints.impls.orient.OrientGraphFactory.getTx(OrientGraphFactory.java:71)

This is a known OSGi-related issue. In OSGi container each bundle has its own class loader and thus all the classes used in a particular bundle should be loaded by its class loader.
In the mentioned exceptions, though, classes are loaded dynamically using ServiceLoader, thus they can't be treated as sub types of classes loaded by the bundle classloader.

A known workaround for this problem is to use DynamicImport-Package directive, which allows a bundle to be wired up to packages that may not be known about in advance.

**Comment by ylopotun** [comment]
Submitted a pull request with the suggested fix:
https://github.com/orientechnologies/orientdb/pull/4850

**Comment by lvca** [comment]
@jdillon, WDYT about this?
