### ISSUE TITLE
Error in OrientDB Log: java.lang.ClassCastException: com.orientechnologies.orient.core.db.record.OTrackedSet cannot be cast to java.util.List

### ISSUE THREAD

**Issue by SKuettner** [orientechnologies/orientdb#4853]
{db=mts_13709875} Error on using index BaseVertex.MasterdataId in query 'SELECT FROM DomainObject WHERE MasterdataId IN :ids'. Probably you need to rebuild indexes. Now executing query using cluster scan
java.lang.ClassCastException: com.orientechnologies.orient.core.db.record.OTrackedSet cannot be cast to java.util.List
                at com.orientechnologies.orient.core.sql.operator.OQueryOperatorIn.executeIndexQuery(OQueryOperatorIn.java:79)
                at com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.searchForIndexes(OCommandExecutorSQLSelect.java:1509)
                at com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.searchInClasses(OCommandExecutorSQLSelect.java:740)
                at com.orientechnologies.orient.core.sql.OCommandExecutorSQLResultsetAbstract.assignTarget(OCommandExecutorSQLResultsetAbstract.java:194)
                at com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.assignTarget(OCommandExecutorSQLSelect.java:420)
                at com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.executeSearch(OCommandExecutorSQLSelect.java:402)
                at com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.iterator(OCommandExecutorSQLSelect.java:337)
                at com.orientechnologies.orient.core.sql.OCommandExecutorSQLResultsetDelegate.iterator(OCommandExecutorSQLResultsetDelegate.java:50)
                at com.orientechnologies.orient.core.sql.OCommandExecutorSQLResultsetAbstract.assignTarget(OCommandExecutorSQLResultsetAbstract.java:201)
                at com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.assignTarget(OCommandExecutorSQLSelect.java:420)
                at com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.executeSearch(OCommandExecutorSQLSelect.java:402)
                at com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.iterator(OCommandExecutorSQLSelect.java:337)
                at com.orientechnologies.orient.core.sql.OCommandExecutorSQLResultsetDelegate.iterator(OCommandExecutorSQLResultsetDelegate.java:50)
                at com.orientechnologies.orient.core.sql.OCommandExecutorSQLResultsetAbstract.assignTarget(OCommandExecutorSQLResultsetAbstract.java:201)
                at com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.assignTarget(OCommandExecutorSQLSelect.java:420)
                at com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.executeSearch(OCommandExecutorSQLSelect.java:402)
                at com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.execute(OCommandExecutorSQLSelect.java:373)
                at com.orientechnologies.orient.core.sql.OCommandExecutorSQLDelegate.execute(OCommandExecutorSQLDelegate.java:64)
                at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.executeCommand(OAbstractPaginatedStorage.java:1191)
                at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.command(OAbstractPaginatedStorage.java:1180)
                at com.orientechnologies.orient.core.sql.query.OSQLQuery.run(OSQLQuery.java:71)
                at com.orientechnologies.orient.core.sql.query.OSQLSynchQuery.run(OSQLSynchQuery.java:85)
                at com.orientechnologies.orient.core.query.OQueryAbstract.execute(OQueryAbstract.java:33)
                at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.command(ONetworkProtocolBinary.java:1183)
                at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.executeRequest(ONetworkProtocolBinary.java:390)
                at com.orientechnologies.orient.server.network.protocol.binary.OBinaryNetworkProtocolAbstract.execute(OBinaryNetworkProtocolAbstract.java:217)
                at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:69)

OrientDB has not been shut down since it was initialized two days ago. We didn't delete any objects in it. So indexes should be intact. Whats wrong here?

**Comment by nagarajasr** [comment]
what version of OrientDB?

**Comment by SKuettner** [comment]
OrientDB 2.0.14.

**Comment by lvca** [comment]
Fixed in 2.0.15-SNAPSHOT, 2.1.1-SNAPSHOT and 2.2-SNAPSHOT.

**Comment by lvca** [comment]
We could do a release for 2.0.15 and 2.1.1 today.

**Comment by SKuettner** [comment]
Will this solve the problem or will we have to rebuild the indices?

**Comment by lvca** [comment]
No need to rebuild indexes.

**Comment by SKuettner** [comment]
We need the 2.0.15 release.
