### ISSUE TITLE
get exception when call backup method.

### ISSUE THREAD

**Issue by ninesunqian** [orientechnologies/orientdb#4855]
- Compressing file luceneIndexes\V.x\segments.gen...ok size=20b compressedSize=11 ratio=45%% elapsed=1ms
- Compressing file luceneIndexes\V.x\segments_2...ok size=81b compressedSize=49 ratio=40%% elapsed=1ms
- Compressing file luceneIndexes\V.x\write.lock...error: java.io.IOException: The process cannot access the file because another process has locked a portion of the file.（I translate from：另一个程序已锁定文件的一部分，进程无法访问。）Aug 25, 2015 6:00:33 PM com.orientechnologies.common.log.OLogManager log
SEVERE: {db=example} Cannot compress file: C:\Users\Administrator\.eulermind\maps\example\luceneIndexes\V.x\write.lock
java.io.IOException: 另一个程序已锁定文件的一部分，进程无法访问。
	at java.io.FileInputStream.readBytes(Native Method)
	at java.io.FileInputStream.read(FileInputStream.java:272)
	at com.orientechnologies.common.io.OIOUtils.copyStream(OIOUtils.java:165)
	at com.orientechnologies.orient.core.compression.impl.OZIPCompressionUtil.addFile(OZIPCompressionUtil.java:186)
	at com.orientechnologies.orient.core.compression.impl.OZIPCompressionUtil.addFolder(OZIPCompressionUtil.java:141)
	at com.orientechnologies.orient.core.compression.impl.OZIPCompressionUtil.addFolder(OZIPCompressionUtil.java:127)
	at com.orientechnologies.orient.core.compression.impl.OZIPCompressionUtil.addFolder(OZIPCompressionUtil.java:127)
	at com.orientechnologies.orient.core.compression.impl.OZIPCompressionUtil.addFolder(OZIPCompressionUtil.java:127)
	at com.orientechnologies.orient.core.compression.impl.OZIPCompressionUtil.compressDirectory(OZIPCompressionUtil.java:57)
	at com.orientechnologies.orient.core.storage.impl.local.paginated.OLocalPaginatedStorage.backup(OLocalPaginatedStorage.java:159)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.backup(ODatabaseDocumentTx.java:2708)
	at eulermind.OrientMindDb.backup(OrientMindDb.java:93)

my code is：

        OCommandOutputListener listener = new OCommandOutputListener() {
            @Override
            public void onMessage(String iText) {
                System.out.print(iText);
            }
        };

        m_graph.shutdown();

        ODatabaseDocumentTx db = new ODatabaseDocumentTx(m_orientDbUrl);
        db.open("admin", "admin");
        db.freeze();

        try {
            Utils.mkdir(backupPath);
            OutputStream out = new FileOutputStream(backupPath + File.separator + "mydb.zip");
            db.backup(out, null, null, listener, 9, 2048);

        } catch (IOException e) {
            e.printStackTrace();

        } finally {
            db.release();
            db.close();
            m_graph = new OrientGraph (m_orientDbUrl, true);

        }

**Comment by ninesunqian** [comment]
the problem may be caused by orientdb-lucene. when m_graph.shutdown,  the lucene lock file write.lock will not be removed

**Comment by robfrank** [comment]
I've fixed this. It will be in 2.2.1
