### ISSUE TITLE
Class com.orientechnologies.agent.profiler.OEnterpriseProfiler is not a JMX compliant MXBean

### ISSUE THREAD

**Issue by SKuettner** [orientechnologies/orientdb#4864]
2015-08-26 09:49:09:937 INFO  JMX plugin installed and active: profilerManaged=true [OJMXPlugin]Exception in thread "main" com.orientechnologies.orient.core.exc
eption.OConfigurationException: Cannot initialize JMX server
        at com.orientechnologies.orient.server.handler.OJMXPlugin.config(OJMXPlugin.java:74)
        at com.orientechnologies.orient.server.OServer.registerPlugins(OServer.java:875)
        at com.orientechnologies.orient.server.OServer.activate(OServer.java:252)
        at com.orientechnologies.orient.server.OServerMain.main(OServerMain.java:41)
Caused by: javax.management.NotCompliantMBeanException: MBean class com.orientechnologies.agent.profiler.OEnterpriseProfiler does not implement DynamicMBean, an
d neither follows the Standard MBean conventions (javax.management.NotCompliantMBeanException: Class com.orientechnologies.agent.profiler.OEnterpriseProfiler is
 not a JMX compliant Standard MBean) nor the MXBean conventions (javax.management.NotCompliantMBeanException: com.orientechnologies.agent.profiler.OEnterprisePr
ofiler: Class com.orientechnologies.agent.profiler.OEnterpriseProfiler is not a JMX compliant MXBean)
        at com.sun.jmx.mbeanserver.Introspector.checkCompliance(Introspector.java:176)
        at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.registerMBean(DefaultMBeanServerInterceptor.java:317)
        at com.sun.jmx.mbeanserver.JmxMBeanServer.registerMBean(JmxMBeanServer.java:522)
        at com.orientechnologies.orient.server.handler.OJMXPlugin.config(OJMXPlugin.java:65)
        ... 3 more

Configuration:

<handler class="com.orientechnologies.orient.server.handler.OJMXPlugin">
	<parameters>
		<parameter name="enabled" value="true"/>
		<parameter name="profilerManaged" value="true"/>
	</parameters>
</handler>

**Comment by maggiolo00** [comment]
hi @SKuettner 

are you still having this issue?

**Comment by SKuettner** [comment]
Hello,

we discontinued using OrientDB, so we currently have no issues.

Regards
Stefan Kuettner

Von: Enrico Risa [mailto:notifications@github.com]
Gesendet: Donnerstag, 3. Dezember 2015 12:55
An: orientechnologies/orientdb
Cc: Küttner, Stefan
Betreff: Re: [orientdb] Class com.orientechnologies.agent.profiler.OEnterpriseProfiler is not a JMX compliant MXBean (#4864)


hi @SKuettner<https://github.com/SKuettner>

are you still having this issue?
