### ISSUE TITLE
Insert with nested subexpression

### ISSUE THREAD

**Issue by oakad** [orientechnologies/orientdb#4872]
I'm trying out Orientdb 2.1. The documentation implies that the following syntax should be supported:

``` sql
create class SeqCounter;
create property SeqCounter.increment Long;
create property SeqCounter.value Long;

insert into index:dictionary set key = 'someSeqCounter', rid = (insert into SeqCounter (increment, value) values (16, 1));
```

However, an attempt to execute the query from the console results in sql parse error (below).

If the above index is not supported (despite what documentation says), what is the correct approach to create a record and add its rid to an index, desirably without invoking intermediate variables?

```
com.orientechnologies.orient.core.sql.OCommandSQLParsingException: Error on parsing command at position #0: Encountered
" "(" "( "" at line 1, column 64.
Was expecting one of:
    <NULL> ...
    "true" ...
    "false" ...
    "{" ...

    at com.orientechnologies.orient.core.sql.OCommandExecutorSQLAbstract.throwParsingException(OCommandExecutorSQLAbstract.java:102)
    at com.orientechnologies.orient.core.sql.OCommandExecutorSQLAbstract.preParse(OCommandExecutorSQLAbstract.java:238)
    at com.orientechnologies.orient.core.sql.OCommandExecutorSQLInsert.parse(OCommandExecutorSQLInsert.java:79)
    at com.orientechnologies.orient.core.sql.OCommandExecutorSQLInsert.parse(OCommandExecutorSQLInsert.java:55)
    at com.orientechnologies.orient.core.sql.OCommandExecutorSQLDelegate.parse(OCommandExecutorSQLDelegate.java:76)
    at com.orientechnologies.orient.core.sql.OCommandExecutorSQLDelegate.parse(OCommandExecutorSQLDelegate.java:42)
    at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.command(OAbstractPaginatedStorage.java:1447)
    at com.orientechnologies.orient.core.command.OCommandRequestTextAbstract.execute(OCommandRequestTextAbstract.java:63
)
.....skipped
```

**Comment by luigidellaquila** [comment]
Thanks for reporting, I'm addressing this issue, it will be fixed in next hotfix release
