### ISSUE TITLE
query by lucene index, get exception: java.lang.String cannot be cast to com.orientechnologies.orient.core.index.OCompositeKey

### ISSUE THREAD

**Issue by ninesunqian** [orientechnologies/orientdb#4879]
public static void main(String argv[]) {
        FileUtil.forceDelete(new File("D:\test_orientdb\test"));
        OrientGraph graph = new OrientGraph ("plocal:D:/test_orientdb/test", true);

        boolean has_x_index = false;
        Set<String> indexedKeys = graph.getIndexedKeys(Vertex.class);

        for (String indexedKey : indexedKeys) {
            if (indexedKey.equals("x")) {
                has_x_index = true;
                break;
            }
        }

        if (has_x_index == false) {
            graph.executeOutsideTx(new OCallable<Object, OrientBaseGraph>() {
                @Override
                public Object call(OrientBaseGraph iArgument) {
                    OClass type = iArgument.getVertexBaseType();
                    if (!type.existsProperty("x")) {
                        type.createProperty("x", OType.STRING);
                    }

                    /*
                    ODocument metadata = new ODocument();
                    metadata.fromJSON("{\"analyzer\":\"org.apache.lucene.analysis.cn.smart.SmartChineseAnalyzer\"}");
                    type.createIndex(type.getName() + "."+"x", "FULLTEXT", null, metadata, "LUCENE", new String[]{"x"});
                    */

                String metadata = "{\"analyzer\":\"org.apache.lucene.analysis.cn.smart.SmartChineseAnalyzer\"}";
                iArgument.command(new OCommandSQL("create index V.x on V x FULLTEXT ENGINE LUCENE METADATA " + metadata));
                    return null;
                }
            });
        }

        Vertex v1 = graph.addVertex(null);
        v1.setProperty("x", "天安门");
        Vertex v2 = graph.addVertex(null);
        v2.setProperty("x", "天安门广场南侧是前门");
        Vertex v3 = graph.addVertex(null);
        v3.setProperty("x", "程序员");
        Vertex v4 = graph.addVertex(null);
        v4.setProperty("x", "程序员会用C语言开发程序");

        for (Vertex v : (Iterable<Vertex>) graph.command(
                new OCommandSQL("select * from V where x LUCENE \"广场前门\"")).execute()) {
            System.out.println("- Bought: " + v);

        }
        /*
        for (Vertex v : graph.getVertices("x", "广场前门")) {
            System.out.print(v.getProperty("x"));
        }
        */

    }

**Comment by ninesunqian** [comment]
java.lang.ClassCastException: java.lang.String cannot be cast to com.orientechnologies.orient.core.index.OCompositeKey
	at com.orientechnologies.orient.core.index.OCompositeKey.compareTo(OCompositeKey.java:35)
	at com.orientechnologies.common.comparator.ODefaultComparator.compare(ODefaultComparator.java:52)
	at java.util.TreeMap.getEntryUsingComparator(TreeMap.java:369)
	at java.util.TreeMap.getEntry(TreeMap.java:340)
	at java.util.TreeMap.get(TreeMap.java:273)
	at com.orientechnologies.orient.core.tx.OTransactionIndexChanges.getChangesPerKey(OTransactionIndexChanges.java:51)
	at com.orientechnologies.orient.core.index.OIndexTxAwareMultiValue.calculateTxValue(OIndexTxAwareMultiValue.java:488)
	at com.orientechnologies.orient.core.index.OIndexTxAwareMultiValue.get(OIndexTxAwareMultiValue.java:290)
	at com.orientechnologies.orient.core.index.OIndexTxAwareMultiValue.get(OIndexTxAwareMultiValue.java:40)
	at com.orientechnologies.lucene.operator.OLuceneTextOperator.executeIndexQuery(OLuceneTextOperator.java:51)
	at com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.searchForIndexes(OCommandExecutorSQLSelect.java:1859)
	at com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.searchInClasses(OCommandExecutorSQLSelect.java:850)
	at com.orientechnologies.orient.core.sql.OCommandExecutorSQLResultsetAbstract.assignTarget(OCommandExecutorSQLResultsetAbstract.java:207)
	at com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.assignTarget(OCommandExecutorSQLSelect.java:475)
	at com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.executeSearch(OCommandExecutorSQLSelect.java:457)
	at com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.execute(OCommandExecutorSQLSelect.java:428)
	at com.orientechnologies.orient.core.sql.OCommandExecutorSQLDelegate.execute(OCommandExecutorSQLDelegate.java:90)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.executeCommand(OAbstractPaginatedStorage.java:1468)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.command(OAbstractPaginatedStorage.java:1449)
	at com.orientechnologies.orient.core.command.OCommandRequestTextAbstract.execute(OCommandRequestTextAbstract.java:63)
	at com.tinkerpop.blueprints.impls.orient.OrientGraphCommand.execute(OrientGraphCommand.java:49)
	at eulermind.OrientMindDb.main(OrientMindDb.java:237)

**Comment by ninesunqian** [comment]
I using orientdb and orientdb-lucene 2.1.0

the pom.xml:

```
       <properties>
            <orient_ver>2.1.0</orient_ver>
        </properties>

        <dependency>
            <groupId>com.orientechnologies</groupId>
            <artifactId>orientdb-graphdb</artifactId>
            <version>${orient_ver}</version>
        </dependency>


        <dependency>
             <groupId>com.orientechnologies</groupId>
             <artifactId>orientdb-lucene</artifactId>
              <version>${orient_ver}</version>
        </dependency>

        <dependency>
            <groupId>org.apache.lucene</groupId>
            <artifactId>lucene-analyzers-smartcn</artifactId>
            <version>4.7.0</version>
        </dependency>
```

**Comment by ninesunqian** [comment]
It is funny thing that: 
I added the smartcn classes to the orientdb-lucene jar file in the orientdb server's plugins directory.
I used the same sql sentences to create index and query, I got the right result

**Comment by ninesunqian** [comment]
maybe it is same as https://github.com/orientechnologies/orientdb-lucene/issues/17

**Comment by ninesunqian** [comment]
When 2.2 will be released ?

**Comment by MVdev1** [comment]
I think this is related...

I am using LUCENE SPATIAL INDEX on a table of lat/long data where the values are shorts representing just the degrees and I see...

2015-08-29 00:49:38:465 INFO  OrientDB Server v2.1.0 (build UNKNOWN@r${buildNumber};

2015-08-05 13:38:23+0000) is active. [OServer]{db=TestDb} **Error on using index L0.y_x in query 'SELECT y, x FROM L0 WHERE [y, x] WITHIN [[-119, 33], [-117,31]] ORDER BY n DESC LIMIT 50'. Probably you need to rebuild indexes. Now executing query using cluster scan**
java.lang.ClassCastException: java.util.ArrayList **cannot be cast to java.lang.Short**
        at com.orientechnologies.common.serialization.types.OShortSerializer.preprocess(OShortSerializer.java:36)
        at com.orientechnologies.orient.core.serialization.serializer.binary.impl.index.OCompositeKeySerializer.preprocess(OCompositeKeySerializer.java:383)
        at com.orientechnologies.orient.core.serialization.serializer.binary.impl.index.OCompositeKeySerializer.preprocess(OCompositeKeySerializer.java:46)
        at com.orientechnologies.orient.core.index.hashindex.local.OLocalHashTable.get(OLocalHashTable.java:320)

When running...

SELECT y,x FROM L0 WHERE [y,x] WITHIN [[33,-119],[31,-117]] ORDER BY n DESC LIMIT 50
or
SELECT y,x FROM L0 WHERE [y,x] WITHIN [[-119,33],[-117,31]] ORDER BY n DESC LIMIT 50

*based on the documentation I'm still not clear which order to put lat/long on each side of the WITHIN -- see issue 4881*

From a table that looks like.....

    CREATE CLASS L0 EXTENDS V;
	CREATE PROPERTY L0.y Short;
	ALTER PROPERTY L0.y NOTNULL true;
	ALTER PROPERTY L0.y MANDATORY true;
	CREATE PROPERTY L0.x Short;
	ALTER PROPERTY L0.x NOTNULL true;
	ALTER PROPERTY L0.x MANDATORY true;
	
	CREATE INDEX L0.i ON L0(y,x) UNIQUE_HASH_INDEX;
	CREATE INDEX L0.l ON L0(y,x) SPATIAL ENGINE LUCENE;

**Comment by maggiolo00** [comment]
hi @ninesunqian 
is not related to 
https://github.com/orientechnologies/orientdb-lucene/issues/17
but to
https://github.com/orientechnologies/orientdb/issues/4257

**Comment by maggiolo00** [comment]
@MVdev1 

your exception is another problem. Did you create another index on the same fields?

**Comment by maggiolo00** [comment]
@ninesunqian 

here it is the 2.2 roadmap
http://orientdb.com/docs/2.1/Roadmap.html#release-22

**Comment by ninesunqian** [comment]
@maggiolo00  OK. I'm looking forward to it.

**Comment by MVdev1** [comment]
Sorry, I missed this question before.
>> Did you create another index on the same fields?
Yes, the problem goes away when I have only the Lucene index, regardless of inheritance.

So my workaround is to swap indexes depending on what take I'm doing.  When in insert mode then I add the HASH indexes, when in view mode I take out the HASH and add back the LUCENE.

**Comment by maggiolo00** [comment]
hi @ninesunqian 

did you try this on 2.2-rc1?

**Comment by robfrank** [comment]
hi, on 2.2.0 it works fine, while in 2.1.x it doesn't works due to the fact that you are implicitly querying the index inside a transaction. You can fix it with a call to commit before execute the query:
```
v4.setProperty("x", "程序员会用C语言开发程序");

    graph.commit();
    for (Vertex v : (Iterable<Vertex>) graph.command(new OCommandSQL("select * from V where x LUCENE \"广场前门\"")).execute()) {
      System.out.println("- Bought: " + v);

    }
```

**Comment by ninesunqian** [comment]
Sorry, my project is stopped. So I did not use OrientDB for long time.
Now I just pick up this work. But I need some time to test the bug.

**Comment by robfrank** [comment]
At this point, my suggestion is to switch to 2.2.0.
