### ISSUE TITLE
Error on opening database: the engine 'remote' was not found.

### ISSUE THREAD

**Issue by rburton** [orientechnologies/orientdb#4883]
The following code runs fine for a while and then unexpectedly it starts throwing the exception down below after about 10 mins. 

```java
try (ODatabaseDocumentTx db = orientGraphFactory.getDatabase()) {
            OCommandSQL query = new OCommandSQL("UPDATE ...");
            db.command(query).execute();
}
```

The OrientGraphFactory is created as:

```java
new OrientGraphFactory("remote:localhost/pages", "test", "test").setupPool(1, 10);
```

# Exception

```java
com.orientechnologies.orient.core.exception.ODatabaseException: Error on opening database 'remote:localhost/pages'
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.<init>(ODatabaseDocumentTx.java:201)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.<init>(ODatabaseDocumentTx.java:165)
	at com.tinkerpop.blueprints.impls.orient.OrientGraphFactory.getDatabase(OrientGraphFactory.java:125)
	at com.tinkerpop.blueprints.impls.orient.OrientGraphFactory.getDatabase(OrientGraphFactory.java:111)
```

and

```java
Caused by: com.orientechnologies.orient.core.exception.OConfigurationException: Error on opening database: the engine 'remote' was not found. URL was: remote:localhost/pages. Registered engines are: []
	at com.orientechnologies.orient.core.Orient.loadStorage(Orient.java:454)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.<init>(ODatabaseDocumentTx.java:184)
	... 41 more
```

**Comment by lvca** [comment]
Seems something called the `Orient.shutdown()`. Do you have any piece of code to reproduce it?

**Comment by rburton** [comment]
The code above is what I'm using. I don't have any calls to Orient.shutdown() anywhere in my code.
Luca mentioned that it could be related to the *.jars in my classpath (see https://twitter.com/lgarulli/status/637547358851567616) The thing that concerns me is this happens after the application runs for a while. It's not easily repeatable. Sometimes it'll run for a while without an issue and then there's times when I get this error, but the web console is still functional.

**Comment by lvca** [comment]
The only point when the storage implementations are unregistered is at shutdown. Could it be you get a severe exception like OutOfMemory or GC errors?

**Comment by lvca** [comment]
The issue has been closed because no response has been received after a while. In case the issue is still valid, please reopen it or write a comment that explains why it's still valid and a way to reproduce it. Thank you.
