### ISSUE TITLE
WARNING: Received unexpected result from query: 1

### ISSUE THREAD

**Issue by wooshie** [orientechnologies/orientdb#4887]
Hi.
Many thanks fro the great work done on OrientDB :)
I'm playing with live query on 2.1 (enterprise dev trial) and i have database with remote storage, have live query enabled in server config.
when i'm trying to run live query i'm getting first the warning:
    WARNING: Received unexpected result from query: 1
and then exception:

``` java
8430 [Thread-21] ERROR o.a.s.z.s.NIOServerCnxnFactory - Thread Thread[Thread-21,5,main] died
com.orientechnologies.orient.core.exception.OStorageException: Error on executing command: sql.select from DataNode where (fetchStatus='new' or fetchStatus='failed') and fetchRetries < 3
        at com.orientechnologies.orient.client.remote.OStorageRemote.handleException(OStorageRemote.java:1744) ~[integration-1.0-SNAPSHOT-all.jar:?]
        at com.orientechnologies.orient.client.remote.OStorageRemote.command(OStorageRemote.java:1241) ~[integration-1.0-SNAPSHOT-all.jar:?]
        at com.orientechnologies.orient.client.remote.OStorageRemoteThread.command(OStorageRemoteThread.java:439) ~[integration-1.0-SNAPSHOT-all.jar:?]
        at com.orientechnologies.orient.core.sql.query.OSQLQuery.run(OSQLQuery.java:72) ~[integration-1.0-SNAPSHOT-all.jar:?]
        at com.orientechnologies.orient.core.sql.query.OSQLSynchQuery.run(OSQLSynchQuery.java:85) ~[integration-1.0-SNAPSHOT-all.jar:?]
        at com.orientechnologies.orient.core.query.OQueryAbstract.execute(OQueryAbstract.java:33) ~[integration-1.0-SNAPSHOT-all.jar:?]
        at com.orientechnologies.orient.core.sql.query.OLiveQuery.execute(OLiveQuery.java:18) ~[integration-1.0-SNAPSHOT-all.jar:?]
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.query(ODatabaseDocumentTx.java:686) ~[integration-1.0-SNAPSHOT-all.jar:?]
        at com.bambr.sweet.integration.OrientDbSprout$LiveQueryRunnable.run(OrientDbSprout.java:144) ~[integration-1.0-SNAPSHOT-all.jar:?]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_40-internal]
Caused by: java.lang.NullPointerException
        at com.orientechnologies.orient.client.remote.OStorageRemote.command(OStorageRemote.java:1218) ~[integration-1.0-SNAPSHOT-all.jar:?]
```

using gradle and follwoing libs are listed there:
    compile 'com.orientechnologies:orientdb-client:2.1.0'
    compile 'com.orientechnologies:orientdb-enterprise:2.1.0'
    compile 'com.orientechnologies:orientdb-core:2.1.0'
    compile 'com.tinkerpop.blueprints:blueprints-core:2.6.0'
    compile 'com.orientechnologies:orientdb-graphdb:2.1.0'
    compile 'com.tinkerpop.gremlin:gremlin-java:2.6.0'
    compile 'com.tinkerpop.gremlin:gremlin-groovy:2.6.0'
    compile 'org.codehaus.groovy:groovy:2.4.4'

Looking at the source code of OStorageRemote class there's only one place where such warning is issued, and in code preceding it, in switch block, there's case for '1' value of type, which puzzles me.
Could someone look into this issue, please? :)

**Comment by luigidellaquila** [comment]
Hi @wooshie 

can you provide a test case for this?
We are making LiveQuery stable in 2.2 and maybe it's already fixed, but I'd like to verify it

Thanks

Luigi

**Comment by wooshie** [comment]
Here it is.
https://bitbucket.org/wooshie/storm-sample

Mind the code quality :) It was a technical demo.
Feel free to use it for testing, wouldn't mind if you find it useful and make nice fork and add it to OrientDb samples :)

**Comment by wooshie** [comment]
any news? :)

**Comment by luigidellaquila** [comment]
hi @wooshie 
we are doing some work on LiveQuery in these days, news will probably arrive in short

Thanks

**Comment by wooshie** [comment]
Cool, thank you.
Was my code of any use?
