### ISSUE TITLE
error on moving existent database fails because of restricted access to database parent folder

### ISSUE THREAD

**Issue by dgommeren** [orientechnologies/orientdb#4891]
OrientDB 2.0.15 in distributed mode (dserver.sh) on Ubuntu 14.04 running inside a Docker container.

We use a symbolic link for the database location (<orientdb-home>/databases -> /data), whereby the parent folder is read-only. At some point OrientDB gave the following log entries (after an apparent restart of the server):

2015-08-31 04:37:16:480 WARNING [45aaa11a-e33a-4283-ac22-e554183ff843] moving existent database 'beeyond' located in '/opt/orientdb/databases/beeyond' to '/opt/orientdb/databases/../backup/databases/beeyond' and get a fresh copy from a remote node... [OHazelcastPlugin]
2015-08-31 04:37:16:481 SEVERE [45aaa11a-e33a-4283-ac22-e554183ff843] error on moving existent database 'beeyond' located in '/opt/orientdb/databases/beeyond' to '/opt/orientdb/databases/../backup/databases/beeyond'. Try to move the database directory manually and retry [OHazelcastPlugin]

Apart from the fact the server instance restarted without any indication and the fact it wanted to copy the entire database from another node, the problem we have is that OrientDB is trying to move the original database to a location in the "databases" parent directory ("backup"): '/opt/orientdb/databases/../backup/databases/beeyond'
OrientDB in our instance does not have access to this folder. It should be possible to configure the location of this folder (or OrientDB should take the "backup" folder in the OrientDB home folder.

**Comment by lvca** [comment]
I've created a new setting:

    DISTRIBUTED_BACKUP_DIRECTORY("distributed.backupDirectory",
      "Directory where to copy an existent database before to download from the cluster", String.class, "../backup/databases"),

If it's null, no backup is created. Or set it to a valid directory.

**Comment by aleksnikolic** [comment]
Running version 2.1.5 inside the docker and I am still experiencing the same issue. Database folder /opt/orientdb/databases is mounted from the host as a volume:

```code
2015-11-18 19:27:49:598 SEVER [orientdb2] error on moving existent database 'test' located in '/opt/orientdb/databases/test' to '/opt/orientdb/databases/../backup/databases/test'. Try to move the database directory manually and retry [OHazelcastPlugin][orientdb2] Error on starting distributed plugin
com.orientechnologies.orient.server.distributed.ODistributedException: Error on moving existent database 'test' located in '/opt/orientdb/databases/test' to '/opt/orientdb/databases/../backup/databases/test'. Try to move the database directory manually and retry
	at com.orientechnologies.orient.server.hazelcast.OHazelcastPlugin.backupCurrentDatabase(OHazelcastPlugin.java:1007)
	at com.orientechnologies.orient.server.hazelcast.OHazelcastPlugin.requestDatabase(OHazelcastPlugin.java:954)
	at com.orientechnologies.orient.server.hazelcast.OHazelcastPlugin.installDatabase(OHazelcastPlugin.java:893)
	at com.orientechnologies.orient.server.hazelcast.OHazelcastPlugin.installNewDatabases(OHazelcastPlugin.java:1448)
	at com.orientechnologies.orient.server.hazelcast.OHazelcastPlugin.startup(OHazelcastPlugin.java:185)
	at com.orientechnologies.orient.server.OServer.registerPlugins(OServer.java:979)
	at com.orientechnologies.orient.server.OServer.activate(OServer.java:346)
	at com.orientechnologies.orient.server.OServerMain.main(OServerMain.java:41)
```

I am passing an ENV variable DISTRIBUTED_BACKUP_DIRECTORY=/opt/orientdb/backup but it seems that it got ignored in 2.1.5. Do you know which config file and section I need to amend if I am not going to setup env variable?

**Comment by lvca** [comment]
Ho do you pass it? Try this in server.sh:

    -DDISTRIBUTED_BACKUP_DIRECTORY=<your folder>
