### ISSUE TITLE
Group by not working in distributed mode

### ISSUE THREAD

**Issue by mattaylor** [orientechnologies/orientdb#4911]
on version 2.1.x running in distributed mode 'group by' clauses appear to be ignored.
When run against a non distributed single node 'group by' clauses work ok.

**Comment by stuartking** [comment]
cc @henryzhao81 

I tested this on a simple DB with two classes, foo and bar. Foo contains a property which is a link to bar. Foo class contains 25016 records, each linking to one of 10 bar records (randomly generated).

When running the server in single instance mode (starting by using server.sh) and running the following query, 10 records are returned:

```
orientdb {db=test}> select bar.name, count(*) from foo group by bar
```

Shutting down the server, then starting it in distributed mode (dserver.sh), running exactly the same query in Studio or over HTTP only returns the total number of records in foo as if the 'group by' property was not defined.

Over the binary protocol a NPE is returned and the following message is in the logs:
```
Error on unmarshalling record #-2:1 (com.orientechnologies.orient.core.exception.OSerializationException: Impossible serialize value of type class com.orientechnologies.orient.core.sql.filter.OSQLFilterItemField with the ODocument binary serializer)
com.orientechnologies.orient.core.exception.OSerializationException: Impossible serialize value of type class com.orientechnologies.orient.core.sql.filter.OSQLFilterItemField with the ODocument binary serializer
	at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinaryV0.serialize(ORecordSerializerBinaryV0.java:255)
	at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinary.toStream(ORecordSerializerBinary.java:105)
	at com.orientechnologies.orient.core.record.impl.ODocument.toStream(ODocument.java:2234)
	at com.orientechnologies.orient.core.record.impl.ODocument.toStream(ODocument.java:664)
	at com.orientechnologies.orient.server.network.protocol.binary.OBinaryNetworkProtocolAbstract.getRecordBytes(OBinaryNetworkProtocolAbstract.java:424)
	at com.orientechnologies.orient.server.network.protocol.binary.OBinaryNetworkProtocolAbstract.writeRecord(OBinaryNetworkProtocolAbstract.java:439)
	at com.orientechnologies.orient.server.network.protocol.binary.OBinaryNetworkProtocolAbstract.writeIdentifiable(OBinaryNetworkProtocolAbstract.java:141)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.serializeValue(ONetworkProtocolBinary.java:1384)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.command(ONetworkProtocolBinary.java:1332)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.executeRequest(ONetworkProtocolBinary.java:396)
	at com.orientechnologies.orient.server.network.protocol.binary.OBinaryNetworkProtocolAbstract.execute(OBinaryNetworkProtocolAbstract.java:223)
	at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:77)
```
