### ISSUE TITLE
Orientdb client goes on endless loop if the server dies

### ISSUE THREAD

**Issue by sajid2045** [orientechnologies/orientdb#4914]
Again, 

This is very critical, The client seems to go in a endless loop if the server is not available / dies in the middle. We can't put it in production as it kills other application hosted in the same container.

[2015-09-03 16:49:31,187] [pool-371-thread-1] [ERROR] [com.orientechnologies.common.log.OLogManager:138] [log] [serviceName:SubscriptionService]=> Cannot open database with url fsasydgrhdb01.foxsports.com.au:2424/subscription-service
com.orientechnologies.common.io.OIOException: Cannot open a connection to remote server: fsasydgrhdb01.foxsports.com.au:2424/subscription-service
        at com.orientechnologies.orient.client.remote.OStorageRemote.getAvailableNetwork(OStorageRemote.java:2114) ~[orientdb-client-2.1.1.jar:2.1.1]
        at com.orientechnologies.orient.client.remote.OStorageRemote.openRemoteDatabase(OStorageRemote.java:1841) [orientdb-client-2.1.1.jar:2.1.1]
        at com.orientechnologies.orient.client.remote.OStorageRemote.handleException(OStorageRemote.java:1806) [orientdb-client-2.1.1.jar:2.1.1]
        at com.orientechnologies.orient.client.remote.OSBTreeBonsaiRemote.firstKey(OSBTreeBonsaiRemote.java:242) [orientdb-client-2.1.1.jar:2.1.1]
        at com.orientechnologies.orient.core.db.record.ridbag.sbtree.OSBTreeRidBag$SBTreeMapEntryIterator.init(OSBTreeRidBag.java:512) [orientdb-core-2.1.1.jar:2.1.1]
        at com.orientechnologies.orient.core.db.record.ridbag.sbtree.OSBTreeRidBag$SBTreeMapEntryIterator.<init>(OSBTreeRidBag.java:446) [orientdb-core-2.1.1.jar:2.1.1]
        at com.orientechnologies.orient.core.db.record.ridbag.sbtree.OSBTreeRidBag.rawIterator(OSBTreeRidBag.java:553) [orientdb-core-2.1.1.jar:2.1.1]
        at com.orientechnologies.orient.core.db.record.ridbag.ORidBag.rawIterator(ORidBag.java:154) [orientdb-core-2.1.1.jar:2.1.1]
        at com.tinkerpop.blueprints.impls.orient.OrientVertex.getVertices(OrientVertex.java:622) [orientdb-graphdb-2.1.1.jar:2.1.1]
        at com.tinkerpop.frames.annotations.AdjacencyAnnotationHandler.processVertex(AdjacencyAnnotationHandler.java:34) [frames-2.6.0.jar:?]
        at com.tinkerpop.frames.annotations.AdjacencyAnnotationHandler.processElement(AdjacencyAnnotationHandler.java:26) [frames-2.6.0.jar:?]
        at com.tinkerpop.frames.annotations.AdjacencyAnnotationHandler.processElement(AdjacencyAnnotationHandler.java:15) [frames-2.6.0.jar:?]
        at com.tinkerpop.frames.FramedElement.invoke(FramedElement.java:89) [frames-2.6.0.jar:?]
        at com.sun.proxy.$Proxy289.getChildren(Unknown Source) [?:?]
        at au.com.foxsports.subscription.service.SubscriptionServiceImpl.topicEvent(SubscriptionServiceImpl.java:547) [subscription-service-api.jar:?]
        at au.com.foxsports.subscription.service.SubscriptionServiceImpl.addNewSubscriptions(SubscriptionServiceImpl.java:534) [subscription-service-api.jar:?]
        at au.com.foxsports.subscription.service.SubscriptionServiceImpl.updateWithRetry(SubscriptionServiceImpl.java:449) [subscription-service-api.jar:?]
        at au.com.foxsports.subscription.service.SubscriptionServiceImpl.access$000(SubscriptionServiceImpl.java:33) [subscription-service-api.jar:?]
        at au.com.foxsports.subscription.service.SubscriptionServiceImpl$1.run(SubscriptionServiceImpl.java:395) [subscription-service-api.jar:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471) [?:1.7.0_60]
        at java.util.concurrent.FutureTask.run(FutureTask.java:262) [?:1.7.0_60]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [?:1.7.0_60]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [?:1.7.0_60]
        at java.lang.Thread.run(Thread.java:745) [?:1.7.0_60]
Caused by: com.orientechnologies.common.io.OIOException: Error on connecting to fsasydgrhdb01.foxsports.com.au:2424/subscription-service
        at com.orientechnologies.orient.client.remote.ORemoteConnectionManager.createNetworkConnection(ORemoteConnectionManager.java:246) ~[orientdb-client-2.1.1.jar:2.1.1]
        at com.orientechnologies.orient.client.remote.ORemoteConnectionManager$1.createNewResource(ORemoteConnectionManager.java:80) ~[orientdb-client-2.1.1.jar:2.1.1]
        at com.orientechnologies.orient.client.remote.ORemoteConnectionManager$1.createNewResource(ORemoteConnectionManager.java:77) ~[orientdb-client-2.1.1.jar:2.1.1]
        at com.orientechnologies.common.concur.resource.OResourcePool.getResource(OResourcePool.java:94) ~[orientdb-core-2.1.1.jar:2.1.1]
        at com.orientechnologies.orient.client.remote.ORemoteConnectionManager.acquire(ORemoteConnectionManager.java:101) ~[orientdb-client-2.1.1.jar:2.1.1]
        at com.orientechnologies.orient.client.remote.OStorageRemote.getAvailableNetwork(OStorageRemote.java:2103) ~[orientdb-client-2.1.1.jar:2.1.1]
        ... 23 more

**Comment by sajid2045** [comment]
Also, after killing the server and starting it, looks like the client enters in some corrupted state and prints a lot of the following logs.

[2015-09-03 16:54:36,375] [pool-371-thread-1] [WARN] [com.orientechnologies.common.log.OLogManager:140] [log] [serviceName:SubscriptionService]=> Caught I/O errors from Not connected (local socket=?), trying to reconnect (error: java.io.IOException: Channel is closed)
[2015-09-03 16:54:36,408] [pool-371-thread-1] [WARN] [com.orientechnologies.common.log.OLogManager:140] [log] [serviceName:SubscriptionService]=> Connection re-acquired transparently after 33ms and 1 retries to server 'fsasydgrhdb01.foxsports.com.au:2424/subscription-service': no errors will be thrown at application level

**Comment by valeriotarenghi** [comment]
HI @sajid2045 
COULD YOU SEND ME YOUR LOG FILE?

**Comment by sajid2045** [comment]
As I said, the server is down,  the log file is the endless loop of this
exception.

**Comment by tglman** [comment]
@sajid2045,

The second log it's normal it's the client that see that the server is down, and retry to connect to it, adding a progressive delay, when the server is up again it reconnect, otherwise it fail after 5 retry (it's configurable with the 'network.retry' property)

The first stack trace show a problem on acquiring a new connection, but seems the original source is hidden, could you add in your logging configuration the package 'com.orientechnologies.orient.client.remote' with the FINEST level, anyway feel free to contact me directly on chat to speed up the troubleshooting.

**Comment by tglman** [comment]
Hi @sajid2045,

I think i found the problem, in case of connection problems the client could go in loop, as explained in a detailed way here: https://github.com/orientechnologies/orientdb/issues/4810, anyway this happen only on case something goes wrong, like url resolution problems, so having a debug log of your case may help us to understand the first problem that brought to the looping.

**Comment by sajid2045** [comment]
Hi,

I think you already have my code, you should be able to reproduce it by
running the client and just killing the server.

-Sajid.

**Comment by tglman** [comment]
hi @sajid2045,

just fixed this, i added a relative test case for connection failure, closing this.

**Comment by sajid2045** [comment]
Does that mean we need to change version, again?

**Comment by tglman** [comment]
The hotfix is still not out, but i think we can release it soon, i've to check the schedule of the hotfix, if you want to test it in your environment ASAP i can provide some jar with the fix that you can use in the client.

**Comment by sajid2045** [comment]
That would be great! We need to test it in production and because of this,
we cant and we are even thinking about going back to 2.0.5 previous stable
version. I really want to stay on the latest since we have spent so much
time on it.

-Sajid.

**Comment by tglman** [comment]
I sent the relative jars by mail

**Comment by sajid2045** [comment]
Hi,

I received the jar but we definitely don't want to run production with manually changed snapshot versions of jar. We need a hotfix release with this fix.

-Sajid.

**Comment by sajid2045** [comment]
Hi again, 

with 2.1.1 , the client goes into the while loop in the above scenario and eventually goes outofmemory ! see below

Sep 07, 2015 8:36:20 PM com.orientechnologies.common.log.OLogManager log
SEVERE: Removing disconnected network channel 'fsasydgrhdb01:2424/subscription-service'...
Sep 07, 2015 8:36:20 PM com.orientechnologies.common.log.OLogManager log
SEVERE: Cannot open database url=fsasydgrhdb01:2424/subscription-service
java.io.EOFException
	at java.io.DataInputStream.readByte(DataInputStream.java:267)
	at com.orientechnologies.orient.enterprise.channel.binary.OChannelBinary.readByte(OChannelBinary.java:73)
	at com.orientechnologies.orient.enterprise.channel.binary.OChannelBinaryAsynchClient.beginResponse(OChannelBinaryAsynchClient.java:200)
	at com.orientechnologies.orient.enterprise.channel.binary.OChannelBinaryAsynchClient.beginResponse(OChannelBinaryAsynchClient.java:171)
	at com.orientechnologies.orient.client.remote.OStorageRemote.beginResponse(OStorageRemote.java:2136)
	at com.orientechnologies.orient.client.remote.OStorageRemote.openRemoteDatabase(OStorageRemote.java:1864)
	at com.orientechnologies.orient.client.remote.OStorageRemote.handleException(OStorageRemote.java:1806)
	at com.orientechnologies.orient.client.remote.OStorageRemote.command(OStorageRemote.java:1241)
	at com.orientechnologies.orient.client.remote.OStorageRemoteThread.command(OStorageRemoteThread.java:439)
	at com.orientechnologies.orient.core.sql.query.OSQLQuery.run(OSQLQuery.java:72)
	at com.orientechnologies.orient.core.sql.query.OSQLSynchQuery.run(OSQLSynchQuery.java:85)
	at com.orientechnologies.orient.core.query.OQueryAbstract.execute(OQueryAbstract.java:33)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.query(ODatabaseDocumentTx.java:686)
	at au.com.foxsports.subscription.service.SubscriptionServiceImpl.getDocument(SubscriptionServiceImpl.java:1259)
	at au.com.foxsports.subscription.service.SubscriptionServiceImpl.update(SubscriptionServiceImpl.java:382)
	at au.com.foxsports.subscription.service.SubscriptionServiceImplTest$1.call(SubscriptionServiceImplTest.java:601)
	at au.com.foxsports.subscription.service.SubscriptionServiceImplTest$1.call(SubscriptionServiceImplTest.java:592)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)

Sep 07, 2015 8:36:20 PM com.orientechnologies.common.log.OLogManager log
SEVERE: Removing disconnected network channel 'fsasydgrhdb01:2424/subscription-service'...
Sep 07, 2015 8:36:20 PM com.orientechnologies.common.log.OLogManager log
SEVERE: Cannot open database url=fsasydgrhdb01:2424/subscription-service
java.io.EOFException
	at java.io.DataInputStream.readByte(DataInputStream.java:267)
	at com.orientechnologies.orient.enterprise.channel.binary.OChannelBinary.readByte(OChannelBinary.java:73)
	at com.orientechnologies.orient.enterprise.channel.binary.OChannelBinaryAsynchClient.beginResponse(OChannelBinaryAsynchClient.java:200)
	at com.orientechnologies.orient.enterprise.channel.binary.OChannelBinaryAsynchClient.beginResponse(OChannelBinaryAsynchClient.java:171)
	at com.orientechnologies.orient.client.remote.OStorageRemote.beginResponse(OStorageRemote.java:2136)
	at com.orientechnologies.orient.client.remote.OStorageRemote.openRemoteDatabase(OStorageRemote.java:1864)
	at com.orientechnologies.orient.client.remote.OStorageRemote.handleException(OStorageRemote.java:1806)
	at com.orientechnologies.orient.client.remote.OStorageRemote.command(OStorageRemote.java:1241)
	at com.orientechnologies.orient.client.remote.OStorageRemoteThread.command(OStorageRemoteThread.java:439)
	at com.orientechnologies.orient.core.sql.query.OSQLQuery.run(OSQLQuery.java:72)
	at com.orientechnologies.orient.core.sql.query.OSQLSynchQuery.run(OSQLSynchQuery.java:85)
	at com.orientechnologies.orient.core.query.OQueryAbstract.execute(OQueryAbstract.java:33)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.query(ODatabaseDocumentTx.java:686)
	at au.com.foxsports.subscription.service.SubscriptionServiceImpl.getDocument(SubscriptionServiceImpl.java:1259)
	at au.com.foxsports.subscription.service.SubscriptionServiceImpl.update(SubscriptionServiceImpl.java:382)
	at au.com.foxsports.subscription.service.SubscriptionServiceImplTest$1.call(SubscriptionServiceImplTest.java:601)
	at au.com.foxsports.subscription.service.SubscriptionServiceImplTest$1.call(SubscriptionServiceImplTest.java:592)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)

Sep 07, 2015 8:36:20 PM com.orientechnologies.common.log.OLogManager log
SEVERE: Removing disconnected network channel 'fsasydgrhdb01:2424/subscription-service'...
Exception in thread "ThreadedStreamConsumer" java.lang.OutOfMemoryError: Java heap space
	at java.util.Arrays.copyOf(Arrays.java:2367)
	at java.lang.AbstractStringBuilder.expandCapacity(AbstractStringBuilder.java:130)
	at java.lang.AbstractStringBuilder.ensureCapacityInternal(AbstractStringBuilder.java:114)
	at java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:415)
	at java.lang.StringBuilder.append(StringBuilder.java:132)
	at org.apache.maven.plugin.surefire.report.TestSetRunListener.getAsString(TestSetRunListener.java:223)
	at org.apache.maven.plugin.surefire.report.TestSetRunListener.wrap(TestSetRunListener.java:230)
	at org.apache.maven.plugin.surefire.report.TestSetRunListener.testError(TestSetRunListener.java:172)
	at org.apache.maven.plugin.surefire.booterclient.output.ForkClient.consumeLine(ForkClient.java:109)
	at org.apache.maven.plugin.surefire.booterclient.output.ThreadedStreamConsumer$Pumper.run(ThreadedStreamConsumer.java:67)
	at java.lang.Thread.run(Thread.java:745)

**Comment by sajid2045** [comment]
NOTE: We would prefer not to take any other changes for the server side as we have done extensive testing and spent many hours on 2.1.1 and we don't want to test any new release. So we want a release on this fix applied.

**Comment by tommeek** [comment]
Hi all, we have a hard date of the 14th Sep for a production release. The only way to hit this with confidence is a hotfix from verison 2.1.1. Can you please let use know when we can get this.

Cheers
Tom

**Comment by sajid2045** [comment]
Also, fyi, I tried to run the client with the new versions:



java.lang.NoClassDefFoundError: Could not initialize class com.orientechnologies.orient.core.Orient
	at com.orientechnologies.orient.core.serialization.serializer.record.string.ORecordSerializerStringAbstract.<clinit>(ORecordSerializerStringAbstract.java:52)
	at com.orientechnologies.orient.core.serialization.serializer.record.ORecordSerializerFactory.<init>(ORecordSerializerFactory.java:47)
	at com.orientechnologies.orient.core.serialization.serializer.record.ORecordSerializerFactory.<clinit>(ORecordSerializerFactory.java:37)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.<clinit>(ODatabaseDocumentTx.java:127)
	at com.orientechnologies.orient.core.db.OPartitionedDatabasePool.initQueue(OPartitionedDatabasePool.java:386)
	at com.orientechnologies.orient.core.db.OPartitionedDatabasePool.<init>(OPartitionedDatabasePool.java:186)
	at com.tinkerpop.blueprints.impls.orient.OrientGraphFactory.setupPool(OrientGraphFactory.java:161)
	at au.com.foxsports.subscription.utils.GraphConnectionPool.init(GraphConnectionPool.java:64)
	at au.com.foxsports.subscription.service.SubscriptionServiceImplTest.setup(SubscriptionServiceImplTest.java:89)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:44)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:41)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:27)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:31)
	at com.intellij.junit4.JUnit4TestRunnerUtil$IgnoreIgnoredTestJUnit4ClassRunner.runChild(JUnit4TestRunnerUtil.java:313)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:48)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:231)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:60)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:50)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:222)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:292)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:157)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:74)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:211)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:67)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:134)


Here is my maven dependencies:

$ mvn dependency:tree |grep 'com.orientechnologies'
[INFO] +- com.orientechnologies:orientdb-core:jar:2.1.2-SNAPSHOT:compile
[INFO] +- com.orientechnologies:orientdb-client:jar:2.1.2-SNAPSHOT:compile
[INFO] +- com.orientechnologies:orientdb-object:jar:2.1.1:compile
[INFO] +- com.orientechnologies:orientdb-graphdb:jar:2.1.1:compile
[INFO] |  +- com.orientechnologies:orientdb-server:jar:2.1.1:compile
[INFO] |  +- com.orientechnologies:orientdb-tools:jar:2.1.1:compile

**Comment by lvca** [comment]
@tommeek 2.1.2 will be released today.

**Comment by sajid2045** [comment]
@Ivca , Is this done?

**Comment by lvca** [comment]
We're waiting for https://github.com/orientechnologies/orientdb/issues/4940

**Comment by sajid2045** [comment]
Hi , Thanks . Can you confirm if we need to update the server setup from 2.1.1 ? Or we can just live with upgrading the client. With production release scheduled next week, we definitely don't want to risk testing 2.1.2 server specially given the new releases are so unstable!

**Comment by tglman** [comment]
the fix for #4940 is server side, so unluckily you have to update also the server, anyway the minor include just a bug fixes, that not introduce regression.

**Comment by sajid2045** [comment]
Have you released it ?

**Comment by sajid2045** [comment]
Also, you know this is getting very risky from our side. How do we know its not going to break something else?

**Comment by sajid2045** [comment]
Also, you know this is getting very risky from our side. How do we know its not going to break something else?

**Comment by sajid2045** [comment]
Hi Guys, Is this released yet? Can someone send me the link?

**Comment by Bonizzi** [comment]
http://orientdb.com/download/

**Comment by sajid2045** [comment]
@Bonizzi , I am really starting to get confused here! The last version I got was the orientdb-enterprise-2.1.1 , now you are pointing me to community!

**Comment by Bonizzi** [comment]
@sajid2045 In that link on the right part of the page there is the link to download the Enterprise Edition

**Comment by sajid2045** [comment]
This is fiexed in 2.1.2
