### ISSUE TITLE
java.lang.NullPointerException for studio profiler

### ISSUE THREAD

**Issue by martingg88** [orientechnologies/orientdb#4932]
any idea why i get java.lang.NullPointerException  when i access to profiler at studio?

**Comment by lvca** [comment]
Do you have any logs?

**Comment by maggiolo00** [comment]
@martingg88  which version?

**Comment by martingg88** [comment]
2.1.1

**Comment by grossvater** [comment]
I have a log from enterprise 2.1.4, maybe it helps. Unfortunately, I can't attach text files (needs write permission to repository), so here it:

2015-10-23 15:20:33:078 FINE  [ONetworkProtocolHttpAbstract.execute] Requested: GET /sqlProfiler/profi [ONetworkProtocolHttpDb]Caught exception
java.lang.NullPointerException
	at com.orientechnologies.agent.http.command.OServerCommandGetSQLProfiler.execute(OServerCommandGetSQLProfiler.java:49)
	at com.orientechnologies.orient.server.network.protocol.http.ONetworkProtocolHttpAbstract.service(ONetworkProtocolHttpAbstract.java:180)
	at com.orientechnologies.orient.server.network.protocol.http.ONetworkProtocolHttpAbstract.execute(ONetworkProtocolHttpAbstract.java:627)
	at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:77)

**Comment by maggiolo00** [comment]
@grossvater 

can you try to login as `admin` user instead of `root`?

**Comment by grossvater** [comment]
I tried, the same result.

**Comment by grossvater** [comment]
I still have the error with a fresh installation of orientdb enterprise 2.1.5 (database GratefulDeadConcerts).

**Comment by grossvater** [comment]
I found that I am able to see the information in "profiler" tab only if I log out. Then, after re-login, the tab is populated and the error is gone. But this only until I execute a first query, then the error message reappears and I have to log out again in order to get rid of it. And yes, this workaround is possible only with admin user (with root, the error is always displayed).

**Comment by maggiolo00** [comment]
hi @grossvater 

can you try with orientdb >= 2.1.8 ?

Should be fixed with root

**Comment by martingg88** [comment]
yes. it is working now for 2.1.8. It will be great if you can add some description/brief for each header in the profile table.
