### ISSUE TITLE
Orientdb client program wouldn't run for long period

### ISSUE THREAD

**Issue by sajid2045** [orientechnologies/orientdb#4940]
Please find the standalone client program. It wouldn't run more than 10 hours in a row. This is why I packaged it all up so you can run it against a fresh orientdb cluster and reproduce the issues.

https://dl.dropboxusercontent.com/u/5968302/subscription-client.tar.gz

You can update the db config : SubscriptionServiceImplTest.java

You can run create_schema.sh to generate the schema and then run_sumulation.sh . It eventually exists with various error.

The last one I got:

java.util.concurrent.ExecutionException: java.lang.RuntimeException: com.orientechnologies.orient.enterprise.channel.binary.OResponseProcessingException: Exception during response processing.
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:202)
	at au.com.foxsports.subscription.service.SubscriptionServiceImplTest.simulateLiveCalls(SubscriptionServiceImplTest.java:630)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:44)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:41)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:28)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:31)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:263)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:69)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:48)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:231)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:60)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:50)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:222)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:292)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:242)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:137)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
Caused by: java.lang.RuntimeException: com.orientechnologies.orient.enterprise.channel.binary.OResponseProcessingException: Exception during response processing.
	at au.com.foxsports.subscription.service.SubscriptionServiceImpl.updateWithRetry(SubscriptionServiceImpl.java:486)
	at au.com.foxsports.subscription.service.SubscriptionServiceImpl.updateWithRetry(SubscriptionServiceImpl.java:482)
	at au.com.foxsports.subscription.service.SubscriptionServiceImpl.updateWithRetry(SubscriptionServiceImpl.java:482)
	at au.com.foxsports.subscription.service.SubscriptionServiceImpl.access$000(SubscriptionServiceImpl.java:33)
	at au.com.foxsports.subscription.service.SubscriptionServiceImpl$1.run(SubscriptionServiceImpl.java:397)
	at au.com.foxsports.subscription.service.SubscriptionServiceImpl.update(SubscriptionServiceImpl.java:403)
	at au.com.foxsports.subscription.service.SubscriptionServiceImplTest$1.call(SubscriptionServiceImplTest.java:601)
	at au.com.foxsports.subscription.service.SubscriptionServiceImplTest$1.call(SubscriptionServiceImplTest.java:592)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
Caused by: com.orientechnologies.orient.enterprise.channel.binary.OResponseProcessingException: Exception during response processing.
	at com.orientechnologies.orient.enterprise.channel.binary.OChannelBinaryAsynchClient.throwSerializedException(OChannelBinaryAsynchClient.java:445)
	at com.orientechnologies.orient.enterprise.channel.binary.OChannelBinaryAsynchClient.handleStatus(OChannelBinaryAsynchClient.java:400)
	at com.orientechnologies.orient.enterprise.channel.binary.OChannelBinaryAsynchClient.beginResponse(OChannelBinaryAsynchClient.java:282)
	at com.orientechnologies.orient.enterprise.channel.binary.OChannelBinaryAsynchClient.beginResponse(OChannelBinaryAsynchClient.java:171)
	at com.orientechnologies.orient.client.remote.OStorageRemote.beginResponse(OStorageRemote.java:2136)
	at com.orientechnologies.orient.client.remote.OStorageRemote.commit(OStorageRemote.java:1364)
	at com.orientechnologies.orient.client.remote.OStorageRemoteThread.commit(OStorageRemoteThread.java:448)
	at com.orientechnologies.orient.core.tx.OTransactionOptimistic.doCommit(OTransactionOptimistic.java:596)
	at com.orientechnologies.orient.core.tx.OTransactionOptimistic.commit(OTransactionOptimistic.java:156)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.commit(ODatabaseDocumentTx.java:2578)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.commit(ODatabaseDocumentTx.java:2547)
	at com.tinkerpop.blueprints.impls.orient.OrientTransactionalGraph.commit(OrientTransactionalGraph.java:161)
	at au.com.foxsports.subscription.service.SubscriptionServiceImpl.updateWithRetry(SubscriptionServiceImpl.java:467)
	... 11 more
Caused by: java.lang.NullPointerException
	at com.orientechnologies.orient.core.record.ORecordInternal.setVersion(ORecordInternal.java:71)
	at com.orientechnologies.orient.server.tx.OTransactionOptimisticProxy.begin(OTransactionOptimisticProxy.java:114)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.begin(ODatabaseDocumentTx.java:1661)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.commit(ONetworkProtocolBinary.java:1218)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.executeRequest(ONetworkProtocolBinary.java:400)
	at com.orientechnologies.orient.server.network.protocol.binary.OBinaryNetworkProtocolAbstract.execute(OBinaryNetworkProtocolAbstract.java:223)
	at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:77)

**Comment by Bonizzi** [comment]
Hi @sajid2045 We started the analysis of log file to find the problem

**Comment by tglman** [comment]
I identified the issue, i'm working for write the relative test case and fix it.

**Comment by tglman** [comment]
fixed in 2.1.x closing
