### ISSUE TITLE
Possible infinite recursion  and StackOverflowError while saving records

### ISSUE THREAD

**Issue by shajigopal** [orientechnologies/orientdb#4941]
OrientDB version: 2.0.5
Running mode: pLocal

We are getting a StackOverflowError when we commit a transaction. We save the records at regular intervals and even then we see this error being hit. The stack-trace shows a possible inifinite recursion.
The Graph was given 10G of DISK_BUFFER and around 4G of heapsize.

A part of the exception is:

com.orientechnologies.orient.core.exception.ODatabaseException: Error on saving record #12:-215
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.executeSaveRecord(ODatabaseDocumentTx.java:1760)
	at com.orientechnologies.orient.core.tx.OTransactionOptimistic.addRecord(OTransactionOptimistic.java:307)
	at com.orientechnologies.orient.core.tx.OTransactionOptimistic.saveRecord(OTransactionOptimistic.java:248)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.save(ODatabaseDocumentTx.java:2277)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.save(ODatabaseDocumentTx.java:117)
	at com.orientechnologies.orient.core.record.impl.ODocument.save(ODocument.java:1706)
	at com.orientechnologies.orient.core.record.impl.ODocument.save(ODocument.java:1697)
	at com.orientechnologies.orient.core.record.impl.ODocument.save(ODocument.java:75)
	at com.orientechnologies.orient.core.db.record.ridbag.sbtree.OSBTreeRidBag.serialize(OSBTreeRidBag.java:760)
	at com.orientechnologies.orient.core.db.record.ridbag.ORidBag.toStream(ORidBag.java:264)
	at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinaryV0.writeSingleValue(ORecordSerializerBinaryV0.java:575)
	at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinaryV0.serialize(ORecordSerializerBinaryV0.java:255)
	at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinary.toStream(ORecordSerializerBinary.java:104)
	at com.orientechnologies.orient.core.record.impl.ODocument.toStream(ODocument.java:2061)
	at com.orientechnologies.orient.core.record.impl.ODocument.toStream(ODocument.java:683)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.executeSaveRecord(ODatabaseDocumentTx.java:1658)
	at com.orientechnologies.orient.core.tx.OTransactionOptimistic.addRecord(OTransactionOptimistic.java:307)
	at com.orientechnologies.orient.core.tx.OTransactionOptimistic.saveRecord(OTransactionOptimistic.java:248)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.save(ODatabaseDocumentTx.java:2277)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.save(ODatabaseDocumentTx.java:117)
	at com.orientechnologies.orient.core.record.impl.ODocument.save(ODocument.java:1706)
	at com.orientechnologies.orient.core.record.impl.ODocument.save(ODocument.java:1697)
	at com.orientechnologies.orient.core.record.impl.ODocument.save(ODocument.java:75)
	at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinaryV0.recursiveLinkSave(ORecordSerializerBinaryV0.java:668)
	at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinaryV0.writeOptimizedLink(ORecordSerializerBinaryV0.java:682)
	at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinaryV0.writeSingleValue(ORecordSerializerBinaryV0.java:566)
	at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinaryV0.serialize(ORecordSerializerBinaryV0.java:255)
	at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinary.toStream(ORecordSerializerBinary.java:104)
	at com.orientechnologies.orient.core.record.impl.ODocument.toStream(ODocument.java:2061)
	at com.orientechnologies.orient.core.record.impl.ODocument.toStream(ODocument.java:683)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.executeSaveRecord(ODatabaseDocumentTx.java:1658)
	at com.orientechnologies.orient.core.tx.OTransactionOptimistic.addRecord(OTransactionOptimistic.java:307)
	at com.orientechnologies.orient.core.tx.OTransactionOptimistic.saveRecord(OTransactionOptimistic.java:248)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.save(ODatabaseDocumentTx.java:2277)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.save(ODatabaseDocumentTx.java:117)
	at com.orientechnologies.orient.core.record.impl.ODocument.save(ODocument.java:1706)
	at com.orientechnologies.orient.core.record.impl.ODocument.save(ODocument.java:1697)
	at com.orientechnologies.orient.core.record.impl.ODocument.save(ODocument.java:75)
....
....
Caused by: 
java.lang.StackOverflowError
	at java.util.HashMap.hash(HashMap.java:374)
	at java.util.HashMap.put(HashMap.java:504)
	at java.util.HashSet.add(HashSet.java:229)
	at com.orientechnologies.orient.core.hook.OHookThreadLocal.push(OHookThreadLocal.java:60)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.callbackHooks(ODatabaseDocumentTx.java:941)
	at com.orientechnologies.orient.core.tx.OTransactionOptimistic.addRecord(OTransactionOptimistic.java:287)
	at com.orientechnologies.orient.core.tx.OTransactionOptimistic.saveRecord(OTransactionOptimistic.java:248)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.save(ODatabaseDocumentTx.java:2277)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.save(ODatabaseDocumentTx.java:117)
	at com.orientechnologies.orient.core.record.impl.ODocument.save(ODocument.java:1706)
	at com.orientechnologies.orient.core.record.impl.ODocument.save(ODocument.java:1697)
	at com.orientechnologies.orient.core.record.impl.ODocument.save(ODocument.java:75)
	at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinaryV0.recursiveLinkSave(ORecordSerializerBinaryV0.java:668)
	at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinaryV0.writeOptimizedLink(ORecordSerializerBinaryV0.java:682)
	at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinaryV0.writeSingleValue(ORecordSerializerBinaryV0.java:566)
	at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinaryV0.serialize(ORecordSerializerBinaryV0.java:255)
	at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinary.toStream(ORecordSerializerBinary.java:104)
	at com.orientechnologies.orient.core.record.impl.ODocument.toStream(ODocument.java:2061)
	at com.orientechnologies.orient.core.record.impl.ODocument.toStream(ODocument.java:683)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.executeSaveRecord(ODatabaseDocumentTx.java:1658)
	... 3347 more

**Comment by tglman** [comment]
Hi @shajigopal,

This can happen if you have a huge graph deeply linked to save all together. it's already fixed in current development version, but it will be out with the 2.2.

**Comment by shajigopal** [comment]
Lvca, thank you for the response. Our product is in the final phases of development and appreciate if we can get a patch on 2.0.5.

**Comment by shajigopal** [comment]
@tglman can the fix be ported to 2.0.5. Our product is in the final phases of development and an update to the latest version may not be possible.

**Comment by tglman** [comment]
@shajigopal,

the fix for this problem was a completely refactor of the save flow, is a to huge change to be ported to an hotfix.

you can workaround increasing the stack size of the JVM based on your average load.
