### ISSUE TITLE
Distributed OrientDB servers not connecting

### ISSUE THREAD

**Issue by tellyarz** [orientechnologies/orientdb#4945]
I have two AWS EC2 instance each running OrientDB Enterprise 2.1. I got an explanation on setting up a distributed database system on AWS on this link: http://orientdb.com/docs/2.1/Distributed-Configuration.html. I have hazelcast-cloud 3.3.5 included in my lib folder for each of the OrientDB server instances. But I keep getting<p> <i>Could not connect to: /xxx.xx.xx.xx:2343. Reason: SocketException[Connection timed out to address xxx.xx.xx.xx:2343]</i></p>

Both servers are in the same security group and VPC

Below is my hazlecast.xml settings:

```xml
<hazelcast
    xsi:schemaLocation="http://www.hazelcast.com/schema/config hazelcast-config-3.0.xsd"
    xmlns="http://www.hazelcast.com/schema/config" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <group>
        <name>orientdb</name>
        <password>orientdb</password>
    </group>
    <network>
        <port auto-increment="true">2434</port>
        <join>
            <multicast enabled="false">
                <multicast-group>235.1.1.1</multicast-group>
                <multicast-port>2434</multicast-port>
            </multicast>
            <aws enabled="true">
                <access-key>xxxxxxx</access-key>
                <secret-key>xxxxxxx</secret-key>
                <region>us-east-1</region>   
                <!--<security-group-name>hazelcast-sg</security-group-name>  
                <tag-key>type</tag-key>                                  
                <tag-value>hz-nodes</tag-value>-->                          
            </aws>
        </join>
    </network>
    <executor-service>
        <pool-size>16</pool-size>
    </executor-service>
</hazelcast>
```

**Comment by flyingrobots** [comment]
I have successfully configured a distributed database hosted on AWS. I'm not sure what your exact problem is, but for what it's worth, my `hazelcast.xml` file looks the same as yours, except I've got:

```
			<aws enabled="true">
				<access-key>{{accessKey}}</access-key>
				<secret-key>{{secretKey}}</secret-key>
				<region>{{region}}</region>
				<host-header>ec2.amazonaws.com</host-header>
				<security-group-name>{{securityGroup}}</security-group-name>
			</aws>
```

Maybe you need the `<host-header>` bit, but maybe your issues are related to how you've configured things on the AWS side.

**Comment by tellyarz** [comment]
Thanks @flyingrobots, I had to use:
```xml
<tcp-ip enabled="true">
      <member>1xx.xx.xx.xx:2434</member>
      <member>1xx.xx.x.xxx:2434</member>
</tcp-ip>
```
and the two server were connecting. But I like your config, I will try that too.

**Comment by muthukumarkubendran** [comment]
Hi @flyingrobots 
I'm currently having issues setting up distributed database on AWS. Below is my error, I used ./dserver.sh to start the database

2016-01-22 19:11:06:036 INFO  [10.94.77.192]:2434 [orientdb] [3.5.3] Backpressure is disabled [OperationService]
2016-01-22 19:11:06:049 INFO  [10.94.77.192]:2434 [orientdb] [3.5.3] Starting with 2 generic operation threads and 2 partition operation threads. [ClassicOperationExecutor]
2016-01-22 19:11:06:459 INFO  [10.94.77.192]:2434 [orientdb] [3.5.3] Hazelcast 3.5.3 (20151011 - 64c663a) starting at Address[10.94.77.192]:2434 [system]
2016-01-22 19:11:06:462 INFO  [10.94.77.192]:2434 [orientdb] [3.5.3] Copyright (c) 2008-2015, Hazelcast, Inc. All Rights Reserved. [system]
2016-01-22 19:11:06:463 INFO  [10.94.77.192]:2434 [orientdb] [3.5.3] Creating AWSJoiner [Node]
2016-01-22 19:11:06:479 INFO  [10.94.77.192]:2434 [orientdb] [3.5.3] Address[10.94.77.192]:2434 is STARTING [LifecycleService]
2016-01-22 19:11:48:657 WARNI Distributed server is not yet ONLINE (status=STARTING), reject incoming connection from /10.94.77.192:54374. If you are trying to shutdown the server, please kill the process [OServerNetworkListener][10.94.77.192]:2434 [orientdb] [3.5.3] Connection timed out
java.net.ConnectException: Connection timed out
        at java.net.PlainSocketImpl.socketConnect(Native Method)
        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
        at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
        at java.net.Socket.connect(Socket.java:589)
        at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:668)


Here is my hazelcast config

 <network>
                <port auto-increment="true">2434</port>
                <join>
                        <multicast enabled="false">
                        </multicast>
                        <aws enabled="true">
                                <access-key>.....</access-key>
                                <secret-key>.....</secret-key>
                                 <region>us-east-1</region>
                                 <host-header>ec2.amazonaws.com</host-header>
                             <security-group-name>hazelcast-sg</security-group-name>
                                 <tag-key>type</tag-key>
                                 <tag-value>hz-nodes</tag-value>
                        </aws>
                </join>
        </network>
and my default-distributed-db-config.json 

{
  "autoDeploy": true,
  "hotAlignment": false,
  "executionMode": "undefined",
  "readQuorum": 1,
  "writeQuorum": 2,
  "failureAvailableNodesLessQuorum": false,
  "readYourWrites": true,
  "servers": {
    "*": "master"
  },
  "clusters": {
    "internal": {
    },
    "index": {
    },
    "*": {
      "servers": ["<NEW_NODE>"]
    }
  }
}

Please help me to figure out why I'm getting connection time out error. 

Thanks in advance
