### ISSUE TITLE
OSecurityException in OUser.allow() method

### ISSUE THREAD

**Issue by PhantomYdn** [orientechnologies/orientdb#5024]
Guys,

Please take a look on the following exception:

```java
om.orientechnologies.orient.core.exception.OSecurityAccessException: User 'reader' has no the permission to execute the operation 'Read' against the resource: ResourceGeneric [name=SYSTEM_CLUSTER, legacyName=database.systemclusters].null
     at com.orientechnologies.orient.core.metadata.security.OImmutableUser.allow(OImmutableUser.java:51)
     at com.orientechnologies.orient.core.iterator.OIdentifiableIterator.checkForSystemClusters(OIdentifiableIterator.java:398)
     at com.orientechnologies.orient.core.iterator.ORecordIteratorClass.<init>(ORecordIteratorClass.java:96)
     at com.orientechnologies.orient.core.iterator.ORecordIteratorClass.<init>(ORecordIteratorClass.java:78)
     at com.orientechnologies.orient.core.sql.OCommandExecutorSQLResultsetAbstract.searchInClasses(OCommandExecutorSQLResultsetAbstract.java:469)
     at com.orientechnologies.orient.core.sql.OCommandExecutorSQLResultsetAbstract.searchInClasses(OCommandExecutorSQLResultsetAbstract.java:458)
     at com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.searchInClasses(OCommandExecutorSQLSelect.java:858)
     at com.orientechnologies.orient.core.sql.OCommandExecutorSQLResultsetAbstract.assignTarget(OCommandExecutorSQLResultsetAbstract.java:207)
     at com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.assignTarget(OCommandExecutorSQLSelect.java:479)
     at com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.executeSearch(OCommandExecutorSQLSelect.java:461)
```
I think it's pretty strange to throw exception in method wich actually should check presence of required rights.

**Comment by PhantomYdn** [comment]
Disregard - my fail
