### ISSUE TITLE
2.1.2 Incorrect behivior for OCommandScriptExecutor

### ISSUE THREAD

**Issue by Gabber** [orientechnologies/orientdb#5030]
Hi, we have an issue with the execution of script from Java Api with the version 2.1.2, we have no problem with the prius version 2.0.x we do something similar to this:

public Object executeTest(){
		final OBasicCommandContext context = new OBasicCommandContext();
		context.setVariable("var1", 1);
		context.setVariable("var2", 2);
		// etc..
		String code = loadCode(); // our custom code, a function that do some stuff calling other classic OFunction in the DB
		OCommandExecutorScript command  = new OCommandExecutorScript();
		command.parse(new OCommandScript("javascript", code));
		return command.executeInContext(context, null)
	}
In the var code we add a function that recall one or more OFunction already on db (as example let say the we call the OFunction 'A'),  once executed the command we get the following error:

Caused by: javax.script.ScriptException: sun.org.mozilla.javascript.internal.EcmaError: ReferenceError: "testA" is not defined. (<Unknown Source>#269) in <Unknown Source> at line number 269
	at com.sun.script.javascript.RhinoCompiledScript.eval(RhinoCompiledScript.java:64)
	at javax.script.CompiledScript.eval(CompiledScript.java:92)
	at com.orientechnologies.orient.core.command.script.OCommandExecutorScript.executeJsr223Script(OCommandExecutorScript.java:123)
	... 33 more
Caused by: sun.org.mozilla.javascript.internal.EcmaError: ReferenceError: "A" is not defined. (<Unknown Source>#269)
	at sun.org.mozilla.javascript.internal.ScriptRuntime.constructError(ScriptRuntime.java:3770)
	at sun.org.mozilla.javascript.internal.ScriptRuntime.constructError(ScriptRuntime.java:3748)
	at sun.org.mozilla.javascript.internal.ScriptRuntime.notFoundError(ScriptRuntime.java:3833)
	at sun.org.mozilla.javascript.internal.ScriptRuntime.getNameFunctionAndThis(ScriptRuntime.java:2218)
	at sun.org.mozilla.javascript.internal.Interpreter.interpretLoop(Interpreter.java:1510)
	at sun.org.mozilla.javascript.internal.Interpreter.interpret(Interpreter.java:849)
	at sun.org.mozilla.javascript.internal.InterpretedFunction.call(InterpretedFunction.java:162)
	at sun.org.mozilla.javascript.internal.ContextFactory.doTopCall(ContextFactory.java:430)
	at com.sun.script.javascript.RhinoScriptEngine$1.superDoTopCall(RhinoScriptEngine.java:116)
	at com.sun.script.javascript.RhinoScriptEngine$1.doTopCall(RhinoScriptEngine.java:109)
	at sun.org.mozilla.javascript.internal.ScriptRuntime.doTopCall(ScriptRuntime.java:3160)
	at sun.org.mozilla.javascript.internal.InterpretedFunction.exec(InterpretedFunction.java:173)
	at com.sun.script.javascript.RhinoCompiledScript.eval(RhinoCompiledScript.java:54)
	... 35 more
In the 2.0.x seems that all the OFunction alredy on the DB were in some way avalaible in the context of execution of the script engine, now you have only the code tha you pass at the command (as checked in debug mode).

**Comment by marcolazzara** [comment]
It seems like OrientDB doesn't recognize anymore other Ofunctions already defined.

**Comment by Gabber** [comment]
We have tested it with the latest version compiled by the 2.2.x branch seems back all right, we think you can close this issue

**Comment by luigidellaquila** [comment]
Hi @Gabber 

as from what you reported in the ML, it is fixed in 2.2 snapshot.
Closing

Thanks a lot

Luigi
