### ISSUE TITLE
2.1.3 server/2.1.3 code: ODatabaseException: Database memory:X is closed during Integration tests

### ISSUE THREAD

**Issue by zifnab87** [orientechnologies/orientdb#5033]
I have integration tests and I have an in memory database that before each test class I import. All the the time I get halfway through my tests (not always the same spot) and I get this message: 

```
com.orientechnologies.orient.core.exception.ODatabaseException: Database 'memory:test' is closed
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.checkOpeness(ODatabaseDocumentTx.java:2822)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.getMetadata(ODatabaseDocumentTx.java:760)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.getMetadata(ODatabaseDocumentTx.java:120)
	at com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.searchInIndex(OCommandExecutorSQLSelect.java:2170)
	at com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.assignTarget(OCommandExecutorSQLSelect.java:481)
	at com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.executeSearch(OCommandExecutorSQLSelect.java:461)
	at com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.execute(OCommandExecutorSQLSelect.java:432)
	at com.orientechnologies.orient.core.sql.OCommandExecutorSQLDelegate.execute(OCommandExecutorSQLDelegate.java:90)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.executeCommand(OAbstractPaginatedStorage.java:1469)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.command(OAbstractPaginatedStorage.java:1450)
	at com.orientechnologies.orient.core.command.OCommandRequestTextAbstract.execute(OCommandRequestTextAbstract.java:63)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.command(ONetworkProtocolBinary.java:1319)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.executeRequest(ONetworkProtocolBinary.java:396)
	at com.orientechnologies.orient.server.network.protocol.binary.OBinaryNetworkProtocolAbstract.execute(OBinaryNetworkProtocolAbstract.java:223)
	at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:77)

com.orientechnologies.orient.core.exception.ODatabaseException: Database 'memory:test' is closed
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.checkOpeness(ODatabaseDocumentTx.java:2822)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.begin(ODatabaseDocumentTx.java:1642)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.commit(ONetworkProtocolBinary.java:1218)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.executeRequest(ONetworkProtocolBinary.java:400)
	at com.orientechnologies.orient.server.network.protocol.binary.OBinaryNetworkProtocolAbstract.execute(OBinaryNetworkProtocolAbstract.java:223)
	at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:77)
```

even though before returning same OrientGraph object  I check if it isClosed() and I do .begin()..without any result.. The exception halts my integration tests and they never finish.. This started happening when I was reusing the same object for all the tests in a class instead of doing new OrientGraph(connString) every time.

In each of my 10+ classes I setup @BeforeClass an in-memory database using this code (:

```java

public class InMemoryDatabaseSetup {
	
	public static String DB = "test";
	
	public static void main(String args[]){
		setup();
	}
	
	public static void setup() {
		OServerAdmin serverAdmin;
		try {
			serverAdmin = new OServerAdmin("remote:localhost/"+DB).connect("root", "admin");
			if (!serverAdmin.existsDatabase()) {
				serverAdmin.createDatabase(DB, "graph", "memory");
				System.out.println("Database "+DB+" doesn't exist - it was created");
			}
			else {
				serverAdmin.dropDatabase(null);
				serverAdmin.createDatabase(DB, "graph", "memory");
				System.out.println("Database "+DB+" exists - it was dropped and created");
			}
			serverAdmin.close();
		
			ODatabaseDocumentTx db = new ODatabaseDocumentTx("remote:localhost/"+DB);
			db.open("root", "admin");
			try{
			  OCommandOutputListener listener = new OCommandOutputListener() {
			    @Override
			    public void onMessage(String iText) {
			      System.out.print(iText);
			    }
			  };

			  ODatabaseImport dbImport = new ODatabaseImport(db, "D:/temp/db-dump-0.76-with-2.2-alpha.gz", listener);
			  dbImport.importDatabase();
			  dbImport.close();
			} 
			
			finally {
			  db.close();
			}
			
		} catch (Exception e) {
			e.printStackTrace();
		
		}
	}
```

This is similar to those closed issues #3260, #3678

I even tried OrientGraphFactory factory with a pool size of 10 and get the OrientGraph objects with factory.getTx().. Also made sure to do @after graph.shutdown().. Still the tests are stuck :/
Any help with this?
Thanks

**Comment by zifnab87** [comment]
@lvca please let me know if there is a quick workaround. I had to halt development because now that I have injected the database to all of my classes instead of making a new connection everytime .. my integration tests can't complete..

**Comment by laa** [comment]
Hi,
Why do you use 2.2-alpha and not 2.1 version at least ?
This branch (2.2-alpha) was not updated for a months.

**Comment by zifnab87** [comment]
Hi @laa, as you can see I even used 2.1.2 server and code and I still have the same issue.. I am trying to replicate it with a small code subset because the integration tests I have are quite a lot.

**Comment by zifnab87** [comment]
I am also getting those warnings

Oct 01, 2015 7:52:59 PM com.orientechnologies.common.log.OLogManager log
WARNING: Caught I/O errors from Not connected (local socket=?), trying to reconnect (error: java.io.EOFException)
Oct 01, 2015 7:52:59 PM com.orientechnologies.common.log.OLogManager log
WARNING: Connection re-acquired transparently after 5ms and 1 retries to server '127.0.0.1:2424/test': no errors will be thrown at application level

almost everytime I import and connect to in memory test database

**Comment by zifnab87** [comment]
If I use the trick from #3678 using my own subclass of OrientGraph just before addVertex() or addEdge is called things are a bit more stable 

But I still get once in a while stuck tests that silently fail without anything written!

Or I am getting this warning from time to time:

WARNING: Error deserializing record with id #25:183 send this data for debugging: ABJJbm5lclRleHRBAAAAIDsAAAA6MQAAAF8zAAAAZQAyQCBhIEAgYiBAIGMgQCBkIEAgZSBAIGYgQEhlODgxNDgxNy01ZDA0LTRhN2UtODhiNC03ZDQ1OTQ1ZmQ2YzOQpa/MhlRIYTFlMGM5ZjgtNjM1Ni00OTJkLThmOWUtYmZiNjkyODMxN2E2 
com.orientechnologies.orient.core.exception.ODatabaseException: Database instance is not set in current thread. Assure to set it with: ODatabaseRecordThreadLocal.INSTANCE.set(db);
	at com.orientechnologies.orient.core.db.ODatabaseRecordThreadLocal.get(ODatabaseRecordThreadLocal.java:51)
	at com.orientechnologies.orient.core.record.ORecordAbstract.getDatabase(ORecordAbstract.java:240)
	at com.orientechnologies.orient.core.record.impl.ODocument.getGlobalPropertyById(ODocument.java:2147)
	at com.orientechnologies.orient.core.record.impl.ODocumentInternal.getGlobalPropertyById(ODocumentInternal.java:60)
	at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinaryV0.getGlobalProperty(ORecordSerializerBinaryV0.java:279)
	at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinaryV0.deserializePartial(ORecordSerializerBinaryV0.java:129)
	at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinary.fromStream(ORecordSerializerBinary.java:72)
	at com.orientechnologies.orient.core.record.impl.ODocument.deserializeFields(ODocument.java:1817)
	at com.orientechnologies.orient.core.record.impl.ODocument.checkForFields(ODocument.java:2405)
	at com.orientechnologies.orient.core.record.impl.ODocument.rawField(ODocument.java:767)
	at com.orientechnologies.orient.core.record.impl.ODocument.field(ODocument.java:792)
	at com.tinkerpop.blueprints.impls.orient.OrientElement.getProperty(OrientElement.java:273)
	at com.nooul.util.ObjectMapper.mapVertexToObj(ObjectMapper.java:81)
	at com.nooul.test.integration.services.InnerTextCreateTest.should_store_it(InnerTextCreateTest.java:45)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.springframework.test.context.junit4.statements.RunBeforeTestMethodCallbacks.evaluate(RunBeforeTestMethodCallbacks.java:73)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.springframework.test.context.junit4.statements.RunAfterTestMethodCallbacks.evaluate(RunAfterTestMethodCallbacks.java:82)
	at org.springframework.test.context.junit4.statements.SpringRepeat.evaluate(SpringRepeat.java:73)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:224)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:83)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.springframework.test.context.junit4.statements.RunBeforeTestClassCallbacks.evaluate(RunBeforeTestClassCallbacks.java:61)
	at org.springframework.test.context.junit4.statements.RunAfterTestClassCallbacks.evaluate(RunAfterTestClassCallbacks.java:68)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.run(SpringJUnit4ClassRunner.java:163)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)

**Comment by zifnab87** [comment]
To my surprise

I was doing 

if(graph.isClosed()) {
 graph.begin();
}

and begin() was one of the reasons throwing exceptions "database X is closed". I think begin() is not clear why is needed.. and how it is possible to reuse connections..

**Comment by lvca** [comment]
`begin()` begins a transaction. A closed graph can't be used anymore (there is not open in Blueprints API, sorry)

**Comment by zifnab87** [comment]
@lvca So can I get a new connection getTx(); and then do begin and then commit , and then begin again etc?? or the connections are completely useless after one commit? Thanks

**Comment by zifnab87** [comment]
@laa @lvca Please don't close those so quickly. I've been fighting this for weeks and it is getting annoying. This problem has to do with OrientDB.. I was able to replicate the problem in this small piece of code:


```
import com.nooul.test.integration.util.InMemoryDatabaseSetup;
import com.orientechnologies.orient.client.remote.OServerAdmin;
import com.orientechnologies.orient.core.command.OCommandOutputListener;
import com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx;
import com.orientechnologies.orient.core.db.tool.ODatabaseImport;
import com.tinkerpop.blueprints.impls.orient.OrientGraph;
import com.tinkerpop.blueprints.impls.orient.OrientGraphFactory;

public class TestBed {
	private static OrientGraphFactory factory = new OrientGraphFactory(ConnectionStrings.testConnection).setupPool(1,10);
	public static void main(String args[]){
		
		for(int i=0; i<1000; i++){
			setup();
			System.out.println("\n--------------------Trial:"+i+"-----------------");
			OrientGraph graph = factory.getTx();
			graph.addVertex("class:someClass");
			graph.addVertex("class:someClass");
			graph.addVertex("class:someClass");
			graph.addVertex("class:someClass");
			graph.addVertex("class:someClass");
			graph.commit();
			OrientGraph graph2 = factory.getTx();
			graph2.addVertex("class:someClass");
			graph2.addVertex("class:someClass");
			graph2.addVertex("class:someClass");
			graph2.addVertex("class:someClass");
			graph2.addVertex("class:someClass");
			graph2.commit();
		}
		
	}
	
	public static void setup() {
		String DB="test";
		OServerAdmin serverAdmin;
		try {
			serverAdmin = new OServerAdmin("remote:localhost/"+DB).connect("root", "admin");
			if (!serverAdmin.existsDatabase()) {
				serverAdmin.createDatabase(DB, "graph", "memory");
				System.out.println("Database "+DB+" doesn't exist - it was created");
			}
			else {
				serverAdmin.dropDatabase(null);
				serverAdmin.createDatabase(DB, "graph", "memory");
				System.out.println("Database "+DB+" exists - it was dropped and created");
			}
			serverAdmin.close();
		
			ODatabaseDocumentTx db = new ODatabaseDocumentTx("remote:localhost/"+DB);
			db.open("root", "admin");
			try{
			  OCommandOutputListener listener = new OCommandOutputListener() {
			    @Override
			    public void onMessage(String iText) {
			      System.out.print(iText);
			    }
			  };

			  ODatabaseImport dbImport = new ODatabaseImport(db, "D:/temp/xxxx-orientdb-dump-0.76-no-indices.gz", listener);
			  dbImport.importDatabase();
			  dbImport.close();
			} 
			
			finally {
			  db.close();
			}
			
		} catch (Exception e) {
			e.printStackTrace();
		
		}
	}
}
```

Here is the issue and it happens in any of the trials.. I even tried different size of pools and it is replicated every single time..
```
Database import completed in 4009 ms
--------------------Trial:7-----------------
Exception in thread "main" com.orientechnologies.orient.core.exception.ODatabaseException: Database 'memory:test' is closed
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.checkOpeness(ODatabaseDocumentTx.java:2826)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.begin(ODatabaseDocumentTx.java:1646)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.commit(ONetworkProtocolBinary.java:1218)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.executeRequest(ONetworkProtocolBinary.java:400)
	at com.orientechnologies.orient.server.network.protocol.binary.OBinaryNetworkProtocolAbstract.execute(OBinaryNetworkProtocolAbstract.java:223)
	at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:77)
```
