### ISSUE TITLE
How to detect that something was added before a commit but will be conflicting with existing vertex in an index after a commit?

### ISSUE THREAD

**Issue by zifnab87** [orientechnologies/orientdb#5047]
Hi.

I have an index called Date.date that is keeping track of unique dates..
The usual scenario is that a Date is commited and then if I try again it will be found in the index.
The problem arises when i could have multiple Date insertions and when I commit it says

```
com.orientechnologies.orient.core.storage.ORecordDuplicatedException: Cannot index record #30:14: found duplicated key '11/22/3333' in index 'Date.date' previously assigned to the record #30:13 RID=#30:13
	at com.orientechnologies.orient.core.index.OIndexUnique.put(OIndexUnique.java:70)
	at com.orientechnologies.orient.core.index.OIndexUnique.put(OIndexUnique.java:34)
	at com.orientechnologies.orient.core.index.OIndexAbstract.putInSnapshot(OIndexAbstract.java:979)
	at com.orientechnologies.orient.core.index.OIndexAbstract.applyIndexTxEntry(OIndexAbstract.java:1165)
	at com.orientechnologies.orient.core.index.OIndexAbstract.addTxOperation(OIndexAbstract.java:776)
	at com.orientechnologies.orient.core.tx.OTransactionOptimistic$CommitIndexesCallback.run(OTransactionOptimistic.java:101)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.commit(OAbstractPaginatedStorage.java:1129)
	at com.orientechnologies.orient.core.tx.OTransactionOptimistic.doCommit(OTransactionOptimistic.java:609)
	at com.orientechnologies.orient.core.tx.OTransactionOptimistic.commit(OTransactionOptimistic.java:156)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.commit(ODatabaseDocumentTx.java:2578)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.commit(ODatabaseDocumentTx.java:2547)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.commit(ONetworkProtocolBinary.java:1221)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.executeRequest(ONetworkProtocolBinary.java:400)
	at com.orientechnologies.orient.server.network.protocol.binary.OBinaryNetworkProtocolAbstract.execute(OBinaryNetworkProtocolAbstract.java:223)
	at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:77)
```
This is because my logic that checks if a Date exists uses the index and before a commit the data is not there, so it lets my code to create it once again..

Is there a way to write some logic about things about to be committed but not yet?

Thanks,
Michail

**Comment by lvca** [comment]
If everything is in a TX, the TX should rollback, so db is consistent. Could you catch this failure and manage it in your app?

**Comment by zifnab87** [comment]
Well the problem is: what if a lot of code is trying to add something if it is not there already using indices and since it is not finding it, it adds it multiple times. Then on commit everything fails..It would be nice, although I don't know how Neo4J or other databases are doing it, to be able to get the not yet committed vertices  from the indices.

**Comment by lvca** [comment]
In concurrency this is not possible, because all the operations are atomic. So if you check a condition to understand if a change is needed, in the time the change is executed the condition could change. So this is a normal problem of any concurrent systems.
