### ISSUE TITLE
2.1.2 - Exported database with -excludeAll -includeSchema=true and I get ParseException during import

### ISSUE THREAD

**Issue by zifnab87** [orientechnologies/orientdb#5048]
I expored the database using  -excludeAll -includeSchema=true so I can have only the schema and no data or indices and I am getting this exception:

```
Importing database schema...ERROR (0 entries): java.text.ParseException: Expected content is "name" but found ]}Oct 02, 2015 8:33:20 AM com.orientechnologies.common.log.OLogManager log
SEVERE: Error on importing schema
java.text.ParseException: Expected content is "name" but found ]}
	at com.orientechnologies.orient.core.serialization.serializer.OJSONReader.checkContent(OJSONReader.java:63)
	at com.orientechnologies.orient.core.db.tool.ODatabaseImport.importSchema(ODatabaseImport.java:778)
	at com.orientechnologies.orient.core.db.tool.ODatabaseImport.importDatabase(ODatabaseImport.java:427)
	at com.xxxx.test.integration.util.InMemoryDatabaseSetup.setup(InMemoryDatabaseSetup.java:42)
	at com.xxxx.test.integration.serializations.UserSerializationTest.setup(UserSerializationTest.java:30)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
	at org.springframework.test.context.junit4.statements.RunBeforeTestClassCallbacks.evaluate(RunBeforeTestClassCallbacks.java:61)
	at org.springframework.test.context.junit4.statements.RunAfterTestClassCallbacks.evaluate(RunAfterTestClassCallbacks.java:68)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.run(SpringJUnit4ClassRunner.java:163)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)


Rebuild of stale indexes...
Start rebuild index ouser.name
Rebuild  of index ouser.name is completed.
Start rebuild index orole.name
Rebuild  of index orole.name is completed.
Stale indexes were rebuilt...
Deleting RID Mapping table...OK
```

**Comment by maggiolo00** [comment]
@zifnab87 which version of OrientDB?

**Comment by zifnab87** [comment]
I say that to the title 2.1.2. Thanks

**Comment by lvca** [comment]
Could you please send via email the exported database?

**Comment by zifnab87** [comment]
sent to support - at - orientdb - dot -com

**Comment by tglman** [comment]
just fixed this, excludeAll disabled the database info that where not enabled when used includeSchema, the missing of database info was making the importer using a wrong backward compatible parser.

closing
