### ISSUE TITLE
Getting the error in starting the OrientDB server in distributed database mode in AWS

### ISSUE THREAD

**Issue by rakeshghodasara** [orientechnologies/orientdb#5050]
2015-10-02 16:49:41:948 INFO  Installing GREMLIN language v.2.6.0 - graph.pool.max=50 [OGraphServerHandler]Exception in thread "main" com.orientechnologies.orient.core.exception.OConfigurationException: Error on creating 'replicator' user
        at com.orientechnologies.orient.server.distributed.ODistributedAbstractPlugin.config(ODistributedAbstractPlugin.java:131)
        at com.orientechnologies.orient.server.hazelcast.OHazelcastPlugin.config(OHazelcastPlugin.java:114)
        at com.orientechnologies.orient.server.OServer.registerPlugins(OServer.java:970)
        at com.orientechnologies.orient.server.OServer.activate(OServer.java:338)
        at com.orientechnologies.orient.server.OServerMain.main(OServerMain.java:41)
Caused by: java.io.FileNotFoundException: /opt/orientdb-community-2.1.2/config/orientdb-server-config.xml (Permission denied)
        at java.io.FileOutputStream.open0(Native Method)
        at java.io.FileOutputStream.open(FileOutputStream.java:270)
        at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
        at java.io.FileOutputStream.<init>(FileOutputStream.java:162)
        at java.io.FileWriter.<init>(FileWriter.java:90)
        at com.orientechnologies.orient.server.config.OServerConfigurationLoaderXml.save(OServerConfigurationLoaderXml.java:119)
        at com.orientechnologies.orient.server.OServer.saveConfiguration(OServer.java:586)
        at com.orientechnologies.orient.server.OServer.addUser(OServer.java:677)
        at com.orientechnologies.orient.server.distributed.ODistributedAbstractPlugin.config(ODistributedAbstractPlugin.java:128)
        ... 4 more

**Comment by lvca** [comment]
Permission denied = the OrientDB process must be able to edit the file: /opt/orientdb-community-2.1.2/config/orientdb-server-config.xml
