### ISSUE TITLE
2.1.3 - ODatabaseException: Error on retrieving record #-1:-7 (cluster: null)

### ISSUE THREAD

**Issue by zifnab87** [orientechnologies/orientdb#5068]
Hello,

Recently I've been getting this error and I am almost certain this part of the code hasn't changed since previous versions.

```
com.orientechnologies.orient.core.exception.ODatabaseException: Error on retrieving record #-1:-7 (cluster: null)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.executeReadRecord(ODatabaseDocumentTx.java:1780)
	at com.orientechnologies.orient.core.tx.OTransactionOptimistic.loadRecord(OTransactionOptimistic.java:243)
	at com.orientechnologies.orient.core.tx.OTransactionOptimistic.loadRecord(OTransactionOptimistic.java:217)
	at com.orientechnologies.orient.core.tx.OTransactionOptimistic.loadRecord(OTransactionOptimistic.java:347)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.load(ODatabaseDocumentTx.java:1550)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.load(ODatabaseDocumentTx.java:120)
	at com.orientechnologies.orient.core.id.ORecordId.getRecord(ORecordId.java:324)
	at com.orientechnologies.orient.server.tx.OTransactionOptimisticProxy.begin(OTransactionOptimisticProxy.java:145)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.begin(ODatabaseDocumentTx.java:1665)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.commit(ONetworkProtocolBinary.java:1218)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.executeRequest(ONetworkProtocolBinary.java:400)
	at com.orientechnologies.orient.server.network.protocol.binary.OBinaryNetworkProtocolAbstract.execute(OBinaryNetworkProtocolAbstract.java:223)
	at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:77)
Caused by: java.lang.IllegalArgumentException: Cannot read record #-1:-7 since the position is invalid in database 'xxxx'
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.readRecord(OAbstractPaginatedStorage.java:1743)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.readRecord(OAbstractPaginatedStorage.java:834)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx$SimpleRecordReader.readRecord(ODatabaseDocumentTx.java:3119)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.executeReadRecord(ODatabaseDocumentTx.java:1747)
	... 12 more
```

Thanks,
Michail

**Comment by laa** [comment]
You can not retrieve record with negative rid. How did you get this exception ? Could you provide more details ?

**Comment by zifnab87** [comment]
Actually it is possible to retrieve a created uncommited Vertex and it works fine. This exception is happening everytime when I commit. I checked all my Vertices and none of them have this id. I will check my Edges too.

**Comment by zifnab87** [comment]
@laa I really don't understand why that is a problem.. I have an uncommitted edge (with id #-1:-7) that is connecting two uncommitted vertices. I will try replicating that problem and get back to you asap. The exception happens when I commit..

Thanks

**Comment by zifnab87** [comment]
@laa I put some logging to see what is happening (in that case edge id#-1:-3 is failing on commit)

Vertex V(#-1:-2,Whole) was stored
Edge E(#-1:-2,ContainsEntity) was stored -V(#-1:-2,Whole) ----> V(#12:1,En)
Edge E(#-1:-3,ContainsPart) was stored -V(#-1:-2,Whole) ----> V(#21:290,Part)
Edge E(#-1:-4,ContainsPart) was stored -V(#-1:-2,Whole) ----> V(#21:288,Part)

**Comment by eugene-kamenev** [comment]
@zifnab87 i think you can call .save() method and then yes, you can retrieve the vertex inside not commited transaction, where you can have negative uuid.

**Comment by laa** [comment]
That is serialization issue , assigned to @tglman

**Comment by tglman** [comment]
hi @zifnab87,

do you have the code that reproduce the transaction that fail ? this is a remote+transaction management problem, it may be due also to a graph operation failed and retried without restart the transaction.

by the way which version are you using ?

**Comment by zifnab87** [comment]
@tglman I was using 2.1.3 - Unfortunately I don't have code to replicate this and other issues although I had offered to give my db for check in the past. I have migrated to TitanDB - due to all those problems.  Thanks

**Comment by lvca** [comment]
Cannot replicate.

**Comment by nishantkumar1292** [comment]
I am getting this error when running `REPAIR DATABASE --fix-graph` from console.

SERVER LOG:
```
Repair of graph 'remote:/home/ubuntu/orientdb-community-2.2.21/databases/db_development' is started ...
Scanning 6190805 edges (skipEdges=0)...

Error: com.orientechnologies.orient.core.exception.ODatabaseException: Error on retrieving record #12:15017 (cluster: listing_or)
        DB name="db_development"

Error: com.orientechnologies.orient.core.exception.ODatabaseException: Error on retrieving record #12:15017 (cluster: listing_or)
        DB name="db_development"
        DB name="db_development"

Error: com.orientechnologies.orient.core.exception.OStorageException: Cannot route read record operation for #12:15017 to the distributed node
        DB name="db_development"

Error: java.nio.BufferUnderflowException
```
@lvca ..Any idea why this error?

**Comment by laa** [comment]
Hi, @nishantkumar1292 I answered you in another issue.
