### ISSUE TITLE
Orientdb throws OSchemaException when using v2.1.3 to open a DB created using v2.0.1

### ISSUE THREAD

**Issue by jayaramcs** [orientechnologies/orientdb#5072]
I have an existing db with production content - originally created using v2.0.1. I am trying to upgrade to v2.1.3 and it gives the following error on the first invocation of

I have tested with 2.0.10 and it works with that version.

My understanding is that the binary versions have not changed between these versions and therefore I should be able to simply open the db using the new version ?

``` java
try (ODatabaseDocument currentDb = ODatabaseRecordThreadLocal.INSTANCE.get();) {
```

Trace ... 

``` java
com.orientechnologies.orient.core.exception.OSchemaException: Cannot add base class 'userAccount', because of parameter conflict: userID (type=STRING) vs userID (type=STRING)
    at com.orientechnologies.orient.core.metadata.schema.OClassImpl.checkParametersConflict(OClassImpl.java:2385)
    at com.orientechnologies.orient.core.metadata.schema.OClassImpl.addBaseClass(OClassImpl.java:2367)
    at com.orientechnologies.orient.core.metadata.schema.OClassImpl.setSuperClassesInternal(OClassImpl.java:459)
    at com.orientechnologies.orient.core.metadata.schema.OSchemaShared.fromStream(OSchemaShared.java:775)
    at com.orientechnologies.orient.core.type.ODocumentWrapperNoClass.reload(ODocumentWrapperNoClass.java:74)
    at com.orientechnologies.orient.core.metadata.schema.OSchemaShared.load(OSchemaShared.java:861)
    at com.orientechnologies.orient.core.metadata.OMetadataDefault$1.call(OMetadataDefault.java:150)
    at com.orientechnologies.orient.core.metadata.OMetadataDefault$1.call(OMetadataDefault.java:145)
    at com.orientechnologies.common.concur.resource.OSharedContainerImpl.getResource(OSharedContainerImpl.java:64)
Caused: com.orientechnologies.common.exception.OException: Error on creation of shared resource
    at com.orientechnologies.common.concur.resource.OSharedContainerImpl.getResource(OSharedContainerImpl.java:66)
    at com.orientechnologies.orient.core.storage.OStorageAbstract.getResource(OStorageAbstract.java:143)
    at com.orientechnologies.orient.core.metadata.OMetadataDefault.init(OMetadataDefault.java:145)
    at com.orientechnologies.orient.core.metadata.OMetadataDefault.load(OMetadataDefault.java:76)
    at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.initAtFirstOpen(ODatabaseDocumentTx.java:2875)
    at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.open(ODatabaseDocumentTx.java:260)
    at com.orientechnologies.orient.core.db.OPartitionedDatabasePool$DatabaseDocumentTxPolled.internalOpen(OPartitionedDatabasePool.java:140)
    at com.orientechnologies.orient.core.db.OPartitionedDatabasePool.openDatabase(OPartitionedDatabasePool.java:343)
    at com.orientechnologies.orient.core.db.OPartitionedDatabasePool.acquire(OPartitionedDatabasePool.java:313)
    at  
...
    at com.orientechnologies.orient.core.db.ODatabaseRecordThreadLocal.get(ODatabaseRecordThreadLocal.java:54)
```

**Comment by santo-it** [comment]
Hi,

Thanks for opening this issue

I'm checking some old issues and noticed this one

I wonder if you have been able to workaround this?

All, please note that 2.0 and 2.1 are EOL now. If you are still on one of these versions, please consider upgrading to latest GA asap. If you encounter any issue during upgrade, let us know 

It would be interesting to understand if a similar issue is still happening with latest minor versions of 2.0 and 2.1 and latest GA version

This issue does not include comments from other users, which can be seen as a good sign

I believe it's safe to tag this with "cannot replicate". Please comment if you are affected or you feel this is still current

Many Thanks,

**Comment by jayaramcs** [comment]
We have since upgraded to 2.2 and do not have this issue anymore. Thanks
