### ISSUE TITLE
Class not found after query parsing error

### ISSUE THREAD

**Issue by serenic** [orientechnologies/orientdb#5075]
Orientdb 2.0.13

Log:

<pre>2015-10-08 10:10:31:331 INFO  [OVariableParser.resolveVariables] Error on resolving property: distributed [orientechnologies]
2015-10-08 10:10:31:332 INFO  Installing Script interpreter. WARN: authenticated clients can execute any kind of code into the server by using the following allowed languages: [sql] [OServerSideScriptInterpreter]
2015-10-08 10:10:31:332 INFO  OrientDB Server v2.0.13 is active. [OServer]Sent run-time exception to the client /127.0.0.1:34499: com.orientechnologies.orient.core.sql.OCommandSQLParsingException: Error on parsing command at position #32: Invalid keyword ''2015-10-07 16:36:55''
Command: select from user where createdAt>'2015-10-07 16:36:55'
----------------------------------------^
com.orientechnologies.orient.core.sql.OCommandSQLParsingException: Error on parsing command at position #32: Invalid keyword ''2015-10-07 16:36:55''
Command: select from user where createdAt>'2015-10-07 16:36:55'
----------------------------------------^
	at com.orientechnologies.orient.core.sql.OCommandExecutorSQLAbstract.throwParsingException(OCommandExecutorSQLAbstract.java:93)
	at com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.parse(OCommandExecutorSQLSelect.java:251)
	at com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.parse(OCommandExecutorSQLSelect.java:78)
	at com.orientechnologies.orient.core.sql.OCommandExecutorSQLDelegate.parse(OCommandExecutorSQLDelegate.java:56)
	at com.orientechnologies.orient.core.sql.OCommandExecutorSQLDelegate.parse(OCommandExecutorSQLDelegate.java:37)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.command(OAbstractPaginatedStorage.java:1178)
	at com.orientechnologies.orient.core.sql.query.OSQLQuery.run(OSQLQuery.java:71)
	at com.orientechnologies.orient.core.sql.query.OSQLSynchQuery.run(OSQLSynchQuery.java:85)
	at com.orientechnologies.orient.core.query.OQueryAbstract.execute(OQueryAbstract.java:33)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.command(ONetworkProtocolBinary.java:1183)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.executeRequest(ONetworkProtocolBinary.java:390)
	at com.orientechnologies.orient.server.network.protocol.binary.OBinaryNetworkProtocolAbstract.execute(OBinaryNetworkProtocolAbstract.java:217)
	at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:69)
Sent run-time exception to the client /127.0.0.1:35067: com.orientechnologies.orient.core.exception.OQueryParsingException: Error on parsing query at position #5: Error on parsing query
Query:  user  WHERE @rid = "11:2"  LIMIT 1
----------^
com.orientechnologies.orient.core.exception.OQueryParsingException: Error on parsing query at position #5: Error on parsing query
Query:  user  WHERE @rid = "11:2"  LIMIT 1
----------^
	at com.orientechnologies.orient.core.sql.filter.OSQLTarget.<init>(OSQLTarget.java:76)
	at com.orientechnologies.orient.core.sql.OSQLEngine.parseTarget(OSQLEngine.java:440)
	at com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.parse(OCommandExecutorSQLSelect.java:200)
	at com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.parse(OCommandExecutorSQLSelect.java:78)
	at com.orientechnologies.orient.core.sql.OCommandExecutorSQLDelegate.parse(OCommandExecutorSQLDelegate.java:56)
	at com.orientechnologies.orient.core.sql.OCommandExecutorSQLDelegate.parse(OCommandExecutorSQLDelegate.java:37)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.command(OAbstractPaginatedStorage.java:1178)
	at com.orientechnologies.orient.core.command.OCommandRequestTextAbstract.execute(OCommandRequestTextAbstract.java:63)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.command(ONetworkProtocolBinary.java:1183)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.executeRequest(ONetworkProtocolBinary.java:390)
	at com.orientechnologies.orient.server.network.protocol.binary.OBinaryNetworkProtocolAbstract.execute(OBinaryNetworkProtocolAbstract.java:217)
	at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:69)
Caused by: com.orientechnologies.orient.core.exception.OCommandExecutionException: Class 'USER' was not found in current database
	at com.orientechnologies.orient.core.sql.filter.OSQLTarget.extractTargets(OSQLTarget.java:262)
	at com.orientechnologies.orient.core.sql.filter.OSQLTarget.<init>(OSQLTarget.java:67)
	... 11 more
</pre>

List of classes before error:
<pre>CLASSES
----------------------------------------------+------------------------------------+------------+----------------+
 NAME                                         | SUPERCLASS                         | CLUSTERS   | RECORDS        |
----------------------------------------------+------------------------------------+------------+----------------+
 E                                            |                                    | 10         |              0 |
 OFunction                                    |                                    | 6          |              0 |
 OIdentity                                    |                                    | -          |              0 |
 ORestricted                                  |                                    | -          |              0 |
 ORIDs                                        |                                    | 8          |              0 |
 ORole                                        | OIdentity                          | 4          |              3 |
 OSchedule                                    |                                    | 7          |              0 |
 OTriggered                                   |                                    | -          |              0 |
 OUser                                        | OIdentity                          | 5          |              3 |
 stat                                         | V                                  | 12         |              1 |
 user                                         | V                                  | 11         |              0 |
 V                                            |                                    | 9          |              0 |
----------------------------------------------+------------------------------------+------------+----------------+
 TOTAL = 12                                                                                                    7 |
----------------------------------------------+------------------------------------+------------+----------------+
</pre>

after:

<pre>CLASSES
----------------------------------------------+------------------------------------+------------+----------------+
 NAME                                         | SUPERCLASS                         | CLUSTERS   | RECORDS        |
----------------------------------------------+------------------------------------+------------+----------------+
 E                                            |                                    | 10         |              0 |
 OFunction                                    |                                    | 6          |              0 |
 OIdentity                                    |                                    | -          |              0 |
 ORestricted                                  |                                    | -          |              0 |
 ORIDs                                        |                                    | 8          |              0 |
 ORole                                        | OIdentity                          | 4          |              3 |
 OSchedule                                    |                                    | 7          |              0 |
 OTriggered                                   |                                    | -          |              0 |
 OUser                                        | OIdentity                          | 5          |              3 |
 stat                                         | V                                  | 12         |              1 |
 V                                            |                                    | 9          |              0 |
----------------------------------------------+------------------------------------+------------+----------------+
 TOTAL = 11                                                                                                    7 |
----------------------------------------------+------------------------------------+------------+----------------+
</pre>

**Comment by luigidellaquila** [comment]
Hi @serenic 

This should be fixed in 2.1 release, any chance to try it?

Thanks

**Comment by serenic** [comment]
Ok, try it. But I can't reproduce this bug again with ver 2.0.13.

**Comment by serenic** [comment]
Again... 

Error on parsing query at position #5: Error on parsing command at position #0: Error on parsing query\nQuery:  user WHERE   @rid = \"12:0\"\n----------^

Sails.js:
User.update command

**Comment by serenic** [comment]
OK, this is a sails.js bug: if I change the source code, while running.

**Comment by maggiolo00** [comment]
hi @serenic 

can i close this?

**Comment by maggiolo00** [comment]
hi @serenic 
Seems resolved i'm closing this. If it is not. Please reopen it

Thanks
