### ISSUE TITLE
× com.orientechnologies.common.exception.OException: Error on creation of shared resource  --> com.orientechnologies.orient.core.exception.OConfigurationException: Super class 'Node' was declared in class 'Fitness' but was not found in schema. Remove the dependency or create the class to continue.

### ISSUE THREAD

**Issue by StarpTech** [orientechnologies/orientdb#5094]
Orientdb 2.1.2 in Studio

I tried
```
CREATE CLASS Node EXTENDS V
CREATE CLASS Car EXTENDS V
```

but nothing works.
Error message with "fine" level
```
NullPointerException
```
Error message with "finest" level
```
× com.orientechnologies.common.exception.OException: Error on creation of shared resource
 --> com.orientechnologies.orient.core.exception.OConfigurationException: Super class 'Node' was declared in class 'Fitness' but was not found in schema. Remove the dependency or create the class to continue.
```

After some attempts I can no longer login in my database

```
        at com.orientechnologies.common.concur.resource.OSharedContainerImpl.getResource(OSharedContainerImpl.java:66)
        at com.orientechnologies.orient.core.storage.OStorageAbstract.getResource(OStorageAbstract.java:143)
        at com.orientechnologies.orient.core.metadata.OMetadataDefault.init(OMetadataDefault.java:145)
        at com.orientechnologies.orient.core.metadata.OMetadataDefault.load(OMetadataDefault.java:76)
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.initAtFirstOpen(ODatabaseDocumentTx.java:2871)
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.open(ODatabaseDocumentTx.java:260)
        at com.orientechnologies.orient.server.OServer.openDatabase(OServer.java:724)
        at com.orientechnologies.orient.server.OServer.openDatabase(OServer.java:706)
        at com.orientechnologies.orient.server.network.protocol.http.command.OServerCommandAuthenticatedDbAbstract.authenticate(OServerCommandAuthenticatedDbAbstract.java:167)
        at com.orientechnologies.orient.server.network.protocol.http.command.OServerCommandAuthenticatedDbAbstract.beforeExecute(OServerCommandAuthenticatedDbAbstract.java:127)
        at com.orientechnologies.orient.server.network.protocol.http.command.get.OServerCommandGetConnect.beforeExecute(OServerCommandGetConnect.java:50)
        at com.orientechnologies.orient.server.network.protocol.http.ONetworkProtocolHttpAbstract.service(ONetworkProtocolHttpAbstract.java:177)
        at com.orientechnologies.orient.server.network.protocol.http.ONetworkProtocolHttpAbstract.execute(ONetworkProtocolHttpAbstract.java:627)
        at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:77)
Caused by: com.orientechnologies.orient.core.exception.OConfigurationException: Super class 'Node' was declared in class 'Fitness' but was not found in schema. Remove the dependency or create the class to continue.
        at com.orientechnologies.orient.core.metadata.schema.OSchemaShared.fromStream(OSchemaShared.java:771)
        at com.orientechnologies.orient.core.type.ODocumentWrapperNoClass.reload(ODocumentWrapperNoClass.java:74)
        at com.orientechnologies.orient.core.metadata.schema.OSchemaShared.load(OSchemaShared.java:861)
        at com.orientechnologies.orient.core.metadata.OMetadataDefault$1.call(OMetadataDefault.java:150)
        at com.orientechnologies.orient.core.metadata.OMetadataDefault$1.call(OMetadataDefault.java:145)
        at com.orientechnologies.common.concur.resource.OSharedContainerImpl.getResource(OSharedContainerImpl.java:64)
        ... 13 more

2015-10-10 20:18:20:977 SEVER Internal server error:
com.orientechnologies.common.exception.OException: Error on creation of shared resource
--> com.orientechnologies.orient.core.exception.OConfigurationException: Super class 'Node' was declared in class 'Fitness' but was not found in schema. Remove the dependency or create the class to continue. [ONetworkProtocolHttpDb]
```

Now I want to delete my database with the modal in studio but the same error is thrown:

```
{"errors":[{"code":500,"reason":500,"content":"com.orientechnologies.common.exception.OException: Error on creation of shared resource\r\n--> com.orientechnologies.orient.core.exception.OConfigurationException: Super class 'Node' was declared in class 'ShopUser' but was not found in schema. Remove the dependency or create the class to continue."}]}
```

**Comment by tglman** [comment]
is it this still valid ? i think has been fixed long time ago

**Comment by tglman** [comment]
Hi @StarpTech

I'm closing this, it should be fixed
