### ISSUE TITLE
Threading and OrientGraphFactory with a pool

### ISSUE THREAD

**Issue by dvoet** [orientechnologies/orientdb#5115]
Hello,

I am seeing an issue that seems to appear when using the database pool within OrientGraphFactory while using an OrientGraph from getTx on multiple threads. Specifically, we get a graph from the pool and begin a transaction. We then pass that graph off to a series of 1 or more Futures (in scala) which will execute on arbitrary threads, careful to call makeActive appropriately, to do the work. Then there is 1 final Future to commit the transaction and close the connection, releasing it back to the pool. In this scenario we often see concurrent modification exceptions which seem unrelated to vertexes we are trying to update. I think I have narrowed it down to OPartitionedDatabasePool using ThreadLocal<PoolData>. It seems that if a pooled graph is not released on the same thread on which it was acquired it may not work as intended. I am not entirely certain that this explains the behavior I am seeing but it certainly does not play well with the work done to allow the same graph to be used on different threads (i.e. OrientBaseGraph.makeActive and http://orientdb.com/docs/last/Java-Multi-Threading.html).

I am using v2.1.4. Any guidance would be much appreciated.

Thanks,
Doug

**Comment by dvoet** [comment]
Here is some java code to illustrate the issue.

Line 90 will throw OConcurrentModificationException. Here is my console output:

```
Oct 14, 2015 11:19:52 AM com.orientechnologies.common.log.OLogManager log
INFO: OrientDB auto-config DISKCACHE=10,695MB (heap=3,641MB os=16,384MB disk=138,015MB)
got the shared graph again
Exception in thread "main" com.orientechnologies.orient.core.exception.OConcurrentModificationException: Cannot UPDATE the record #11:0 because the version is not the latest. Probably you are updating an old record or it has been modified by another user (db=v15 your=v14)
	at com.orientechnologies.orient.core.conflict.OVersionRecordConflictStrategy.checkVersions(OVersionRecordConflictStrategy.java:55)
	at com.orientechnologies.orient.core.conflict.OVersionRecordConflictStrategy.onUpdate(OVersionRecordConflictStrategy.java:42)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.checkAndIncrementVersion(OAbstractPaginatedStorage.java:2020)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.doUpdateRecord(OAbstractPaginatedStorage.java:1657)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.commitEntry(OAbstractPaginatedStorage.java:2106)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.commit(OAbstractPaginatedStorage.java:917)
	at com.orientechnologies.orient.core.tx.OTransactionOptimistic.doCommit(OTransactionOptimistic.java:483)
	at com.orientechnologies.orient.core.tx.OTransactionOptimistic.commit(OTransactionOptimistic.java:147)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.commit(ODatabaseDocumentTx.java:2406)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.commit(ODatabaseDocumentTx.java:2376)
	at com.tinkerpop.blueprints.impls.orient.OrientTransactionalGraph.commit(OrientTransactionalGraph.java:162)
	at TestTx.main(TestTx.java:90)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:140)
```

**Comment by laa** [comment]
Hi graph instance is not thread safe , does not matter whether you make it active or not, you have to have only single single thread which uses current graph instance. Do you follow this approach when you work with graph database ?

**Comment by dvoet** [comment]
We guarantee that only one thread at a time accesses a graph instance as in the test case I sent. But that thread may change.

**Comment by dvoet** [comment]
In any case, if the code in the test case is doing something illegal I would like to know. Given the docs I have read it looks fine. If I get rid of the pool, it works.

**Comment by luigidellaquila** [comment]
Hi @dvoet 

could you please try to add

```java 
myOtherGraph.makeActive();
```

at line 81? I think you still have the previous (closed) graph instance active in the main thread

Please let me know if it fixes the problem

Thanks

Luigi

**Comment by dvoet** [comment]
I updated the code and the problem remains. Please look at the use of ThreadLocal in OPartitionedDatabasePool and you will see that that is the where the issue lies.

It looks like the pool is trying to be smart and give out the same connection on the same thread. IMHO that is not the responsibility of the the pool. The pool should give out a new connection on every request and it is up to the caller to return it to the pool or keep track of 1 per thread. The ThreadLocal functionality in OPartitionedDatabasePool should be removed.

**Comment by urugator** [comment]
OPartitionedDatabasePool javadoc is quite clear about this behavior, but I think it should be better documented in manual (Graph Factory section). I can see a lot of confusion and issues caused by this.

I  currently rely on this feature and I believe that many apps would have to reimplement this behavior in some way if it should be removed.
If it should be part of some pool or part of some factory or something else, that's possible subject of discussion.

**Comment by dvoet** [comment]
I am not saying that this functionality is bad and should be removed entirely, just that it belongs somewhere else. The statement in the javadoc: "This pool has one noticeable difference from other pools," highlights the issue that the pool behaves in a non-standard way and will be confusing to others as I think pool users are not likely to read this javadoc.

The concerns should be separated: one component to keep track of a pool of connections and another to keep track of the current connection for the thread. This is a common pattern in the domain. This way the pool and thread-local current connections can be used together or separately.
