### ISSUE TITLE
Read lock threds during the Performnce testing

### ISSUE THREAD

**Issue by SatishAMP** [orientechnologies/orientdb#5126]
In Distributed environment , 
Test simulated 150K read queries in 5 minutes in one Embedded DB instance
Observed thread blocks during read operation. Around 15 threads were blocked by a RUNNABLE thread which owns Monitor lock on Object “com.orientechnologies.orient.core.record.impl.ODocument” (Refer Attachment)
at com.orientechnologies.orient.server.distributed.ODistributedConfiguration.getClusterConfiguration(ODistributedConfiguration.java:377)
- locked [0x0000000649b42170] (a com.orientechnologies.orient.core.record.impl.ODocument)
at com.orientechnologies.orient.server.distributed.ODistributedConfiguration.getServers(ODistributedConfiguration.java:308)
- locked [0x0000000649b42170] (a com.orientechnologies.orient.core.record.impl.ODocument)
at com.orientechnologies.orient.server.distributed.ODistributedStorage.readRecord(ODistributedStorage.java:540) 

Can you please let us know the cause for blocking threads

**Comment by lvca** [comment]
Ok, going more in deep in the chat, this is not a problem. No deadlock found, just a slow down.

**Comment by SatishAMP** [comment]
Thanks , Closing this issue.
