### ISSUE TITLE
Initialization issue

### ISSUE THREAD

**Issue by gpoirier** [orientechnologies/orientdb#5146]
It seems like there's code that's not thread-safe to initialize orientdb. We have several projects that uses it, and I haven't really found the pattern of when the initialization fail and when it doesn't, but when it fails there's two different way. One is the class initializer for `ODatabaseRecordThreadLocal` that throws an exception, and if that happens of course everything is broken.

The other scenario that I've seen for the first time today is setupPool on a factory that simply blocks, it never return. In both cases, the work around I've found was to execute the following code before we have any of our code do any interaction with orientdb:

```
  if (ODatabaseRecordThreadLocal.INSTANCE == null) {
    sys.error("Calling this manually normally prevent initialization issues.")
  }
```

**Comment by gpoirier** [comment]
My description might not be clear enough, but I'm trying to describe a bug here, not ask a question.

**Comment by laa** [comment]
Sorry but I do not think that you work in correct way with database instance. 
graph and database instances are not thread safe and can not be shared among threads. Do you follow this rule ? :-)

**Comment by gpoirier** [comment]
The first time I saw the problem it looked to me as if it was a concurrency issue, so that thought stuck in my head when it shouldn't have. It's probably not a concurrency issue actually. I can reproduce it without using multiple threads in my own code.

The issue I'm describing here is a failure on creating the factory, it's before there would be the possibility of what you're describing going wrong. And for the record, yes, we threat database instances as bound to a specific threads, we only share the factory between threads, not the graphs or database instances.

Here's how I reproduce the problem in a simple main:


```
import com.orientechnologies.orient.core.db.ODatabaseRecordThreadLocal
import com.tinkerpop.blueprints.impls.orient.OrientGraphFactory

object Main extends App {
  // if (ODatabaseRecordThreadLocal.INSTANCE == null) {
  //  sys.error("Calling this manually apparently prevent an initialization issue.")
  // }

  println("Creating the factory...")
  val factory = new OrientGraphFactory("remote:athena.dev", "root", "orient_pass")//.setupPool(10, 100)
  println("Factory created: " + factory)
}
```

And here's the full list of my dependencies:

```
scalaVersion := "2.11.7"
libraryDependencies ++= Seq(
  "com.orientechnologies" % "orientdb-core" % "2.1.4",
  "com.orientechnologies" % "orientdb-client" % "2.1.4",
  "com.orientechnologies" % "orientdb-graphdb" % "2.1.4",
  "com.orientechnologies" % "orientdb-distributed" % "2.1.4"
)
```
 
In the above code, it's the `setupPool` that fails. If I skip this method, the factory creation works fine and I'm able to get a graph out of the factory with success. But the `setupPool` throws the following exception:

```
java.lang.NoClassDefFoundError: Could not initialize class com.orientechnologies.orient.core.db.ODatabaseRecordThreadLocal
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.activateOnCurrentThread(ODatabaseDocumentTx.java:2804)
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.<init>(ODatabaseDocumentTx.java:171)
        at com.orientechnologies.orient.core.db.OPartitionedDatabasePool$DatabaseDocumentTxPolled.<init>(OPartitionedDatabasePool.java:126)
        at com.orientechnologies.orient.core.db.OPartitionedDatabasePool$DatabaseDocumentTxPolled.<init>(OPartitionedDatabasePool.java:122)
        at com.orientechnologies.orient.core.db.OPartitionedDatabasePool.initQueue(OPartitionedDatabasePool.java:386)
        at com.orientechnologies.orient.core.db.OPartitionedDatabasePool.<init>(OPartitionedDatabasePool.java:186)
        at com.tinkerpop.blueprints.impls.orient.OrientGraphFactory.setupPool(OrientGraphFactory.java:161)
        at com.meta.Main$.delayedEndpoint$com$meta$Main$1(Main.scala:13)
        at com.meta.Main$delayedInit$body.apply(Main.scala:6)
        at scala.Function0$class.apply$mcV$sp(Function0.scala:34)
        at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
        at scala.App$$anonfun$main$1.apply(App.scala:76)
        at scala.App$$anonfun$main$1.apply(App.scala:76)
        at scala.collection.immutable.List.foreach(List.scala:381)
        at scala.collection.generic.TraversableForwarder$class.foreach(TraversableForwarder.scala:35)
        at scala.App$class.main(App.scala:76)
        at com.meta.Main$.main(Main.scala:6)
        at com.meta.Main.main(Main.scala)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
```

And the workaround I've found was to call the code that is commented out in the sample above, the following:

```
if (ODatabaseRecordThreadLocal.INSTANCE == null) {
  sys.error("Calling this manually apparently prevent an initialization issue.")
}
```

**Comment by laa** [comment]
Cool let me check that

**Comment by grexe** [comment]
encountered same issue in version 2.1.9 and successfully applied the workaround from [comment above] (https://github.com/orientechnologies/orientdb/issues/5146#issuecomment-149212850)

**Comment by laa** [comment]
I can not reproduce this one , is it possible to send working test case ?

**Comment by laa** [comment]
Close issue because of no reply. If you reproduce given issue and have information which is requested in issue feel free to reopen it.

**Comment by grexe** [comment]
can confirm this issue exists also on OrientDB 2.1.19, JDK8, running in a Docker container.
It seems yet another OSGi classloading issue, @gpoirier do you also run your app in an OSGi container?

**Comment by gpoirier** [comment]
@grexe I wasn't using OSGi to reproduce the problem, just a simple main without any framework involvement I was able to reproduce.

I don't have the code for it anymore, I'm not working with Orientdb anymore.

**Comment by mmacfadden** [comment]
I just ran into this issue in 2.2.11.  Adding

`ODatabaseRecordThreadLocal.INSTANCE`

To the code fixed the issue.
