### ISSUE TITLE
orientdb 2.1.2 can't create databases 

### ISSUE THREAD

**Issue by crestfallen** [orientechnologies/orientdb#5156]
hi,all 
        i am new here. I want to create a database use 'plocal' used for bulk insert.
        please help,thank you!
OrientGraphFactory factory = new OrientGraphFactory("plocal:E:/orientdb-community-2.1.2/databases/plocaltestdb");
		OrientGraphNoTx oGraph = null;
		try {
			 oGraph = factory.getNoTx();
		     System.out.println("success");
		}catch(Exception e){
			e.printStackTrace();
		}finally {
			oGraph.shutdown();
		}

com.orientechnologies.orient.core.command.OCommandExecutorNotFoundException: Cannot find a command executor for the command request: sql.select from OUser where name = ? limit 1
	at com.orientechnologies.orient.core.sql.OCommandExecutorSQLDelegate.parse(OCommandExecutorSQLDelegate.java:72)
	at com.orientechnologies.orient.core.sql.OCommandExecutorSQLDelegate.parse(OCommandExecutorSQLDelegate.java:42)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.command(OAbstractPaginatedStorage.java:1448)
	at com.orientechnologies.orient.core.sql.query.OSQLQuery.run(OSQLQuery.java:72)
	at com.orientechnologies.orient.core.sql.query.OSQLSynchQuery.run(OSQLSynchQuery.java:85)
	at com.orientechnologies.orient.core.query.OQueryAbstract.execute(OQueryAbstract.java:33)
	at com.orientechnologies.orient.core.metadata.security.OSecurityShared.getUser(OSecurityShared.java:522)
	at com.orientechnologies.orient.core.metadata.security.OSecurityShared.authenticate(OSecurityShared.java:163)
	at com.orientechnologies.orient.core.metadata.security.OSecurityProxy.authenticate(OSecurityProxy.java:87)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.open(ODatabaseDocumentTx.java:265)
	at com.tinkerpop.blueprints.impls.orient.OrientGraphFactory.getDatabase(OrientGraphFactory.java:132)
	at com.tinkerpop.blueprints.impls.orient.OrientGraphFactory.getDatabase(OrientGraphFactory.java:111)
	at com.tinkerpop.blueprints.impls.orient.OrientGraphFactory.getNoTx(OrientGraphFactory.java:90)
	at com.wxy.orientdb.GraphTest.createOrOpenDB(GraphTest.java:64)
	at com.wxy.orientdb.GraphTest.main(GraphTest.java:33)

**Comment by lvca** [comment]
It looks like you didn't include all the jars in your classpath, because SQL commands are not registered.
