### ISSUE TITLE
Dynamic edge class name from field in command

### ISSUE THREAD

**Issue by robfrank** [orientechnologies/orientdb#5170]
_From @MarcelPitch on September 30, 2014 15:47_

Hi,

At the end of my transformer, I try to create a specific class Edge, depending on Vertices classes.

Here's my config.json

``` JSON
{
    "config": {
        "verbose": true
    },
    "source" : {
        "file": {
            "path": "I:\\orientdb-etl\\orientdb-community-2.0-M2\\bin\\hierarchy-test.txt",
            "lock" : false
        }
    },
    "extractor" : {
        "row": {}
    },
    "transformers" : [
        {
                "csv": {
                    "separator": "\t",
                    "nullValue": "",
                    "skipFrom": 0,
                    "skipTo": 0,
                    "columns": [
                        "parent_id:STRING",
                        "child_id:STRING",
                        "type:STRING"
                    ]
                }
        },
        {
            "command" : {
                "command" : "SELECT FROM V WHERE itemCode = $input.parent_id LIMIT 1",
                "output" : "parentVertex"
            }
        },
        {
            "field": {
                "fieldName": "parentVClass",
                "expression": "$parentVertex.@class[0]"}
        },
        {
            "command" : {
                "command" : "SELECT FROM V WHERE itemCode = $input.child_id LIMIT 1",
                "output" : "childVertex"
            }
        },
        {
            "field": {
                "fieldName": "childVClass",
                "expression": "$childVertex.@class[0]"}
        },
        {
            "field": {
                "fieldName": "edgeClass",
                "expression": "if( ( $input.parentVClass == 'Continent' ), 'HAS_CONTINENT', if( ( $input.parentVClass == 'Country' ), 'HAS_COUNTRY', 'HAS_ADMINISTRATIVE_AREA' ) )"
            }
        },
        {
            "command" : {
                "command" : "CREATE EDGE $input.edgeClass FROM $childVertex TO $parentVertex",
                "output" : "edgeZoneRelation"
            }
        }
    ],
    "loader" : {
        "orientdb": {
            "dbURL": "plocal:I:\\orientdb-etl\\orientdb-community-2.0-M2\\databases\\db-test-001",
            "dbAutoCreate": true,
            "dbType": "graph"
        }
    }
}

```

I've tried several synthaxes for this command : 

``` JSON
{
            "command" : {
                "command" : "CREATE EDGE $input.edgeClass FROM $childVertex TO $parentVertex",
                "output" : "edgeZoneRelation"
            }
        }
```

but each time, the ETL send an Error, cause it tries to create an Edge with the class '$input.edgeClass', instead of resolving the field.

Is it the right way to proceed with 'field' and 'command' blocks ?

If so, I'd like to know the way to proceed.

Thank you & have a nice day !

_Copied from original issue: orientechnologies/orientdb-etl#7_

**Comment by robfrank** [comment]
_From @lvca on September 30, 2014 20:5_

Have you tried to use the EDGE transformer?

**Comment by robfrank** [comment]
_From @MarcelPitch on October 1, 2014 12:59_

Hi Luca,

No we didn't, cause we can't seem to find a way to create multiple vertices and edges from one csv record with 'vertex' and 'edge' blocks, like in our example.

**Comment by robfrank** [comment]
_From @lvca on October 1, 2014 15:36_

You can use multiple edge/vertex blocks to create more than one. However in your command, try to enable logging to see if the block before set the field correctly.

Replace "verbose : true" in config block with: log: "debug"

**Comment by robfrank** [comment]
_From @profeg on April 4, 2015 11:22_

output after log: "debug", with json file as above
```bash
OrientDB etl v.2.0.6 (build @BUILD@) www.orientechnologies.com
BEGIN ETL PROCESSOR
[file] DEBUG Reading from file /home/prof/Documents/ETL_server/hierarchy-test.txt
[0:csv] DEBUG Transformer input: parent_id	child_id	type
[0:csv] DEBUG Transformer output: null

2015-04-04 14:18:17:109 WARNING Transformer [csv] returned null, skip rest of pipeline execution [OETLPipeline][1:csv] DEBUG Transformer input: one	two	three
[1:csv] DEBUG parsing=one	two	three
[1:csv] DEBUG document={parent_id:one,child_id:two,type:three}
[1:csv] DEBUG Transformer output: {parent_id:one,child_id:two,type:three}
[1:command] DEBUG Transformer input: {parent_id:one,child_id:two,type:three}
[1:command] DEBUG executing command=SELECT FROM V WHERE itemCode = $input.parent_id LIMIT 1...
[1:command] DEBUG executed command=sql.SELECT FROM V WHERE itemCode = $input.parent_id LIMIT 1, result=[]
[1:command] DEBUG Transformer output (same as input): {parent_id:one,child_id:two,type:three}
[1:field] DEBUG Transformer input: {parent_id:one,child_id:two,type:three}
[1:field] DEBUG set parentVClass=false in document={parent_id:one,child_id:two,type:three,parentVClass:false}
[1:field] DEBUG Transformer output: {parent_id:one,child_id:two,type:three,parentVClass:false}
[1:command] DEBUG Transformer input: {parent_id:one,child_id:two,type:three,parentVClass:false}
[1:command] DEBUG executing command=SELECT FROM V WHERE itemCode = $input.child_id LIMIT 1...
[1:command] DEBUG executed command=sql.SELECT FROM V WHERE itemCode = $input.child_id LIMIT 1, result=[]
[1:command] DEBUG Transformer output (same as input): {parent_id:one,child_id:two,type:three,parentVClass:false}
[1:field] DEBUG Transformer input: {parent_id:one,child_id:two,type:three,parentVClass:false}
[1:field] DEBUG set childVClass=false in document={parent_id:one,child_id:two,type:three,parentVClass:false,childVClass:false}
[1:field] DEBUG Transformer output: {parent_id:one,child_id:two,type:three,parentVClass:false,childVClass:false}
[1:field] DEBUG Transformer input: {parent_id:one,child_id:two,type:three,parentVClass:false,childVClass:false}
[1:field] DEBUG set edgeClass=HAS_ADMINISTRATIVE_AREA in document={parent_id:one,child_id:two,type:three,parentVClass:false,childVClass:false,edgeClass:HAS_ADMINISTRATIVE_AREA}
[1:field] DEBUG Transformer output: {parent_id:one,child_id:two,type:three,parentVClass:false,childVClass:false,edgeClass:HAS_ADMINISTRATIVE_AREA}
[1:command] DEBUG Transformer input: {parent_id:one,child_id:two,type:three,parentVClass:false,childVClass:false,edgeClass:HAS_ADMINISTRATIVE_AREA}
[1:command] DEBUG executing command=CREATE EDGE $input.edgeClass FROM $childVertex TO $parentVertex...
Error in Pipeline execution: com.orientechnologies.orient.core.sql.OCommandSQLParsingException: Error on parsing command at position #0: Class '$INPUT.EDGECLASS' was not found
com.orientechnologies.orient.core.sql.OCommandSQLParsingException: Error on parsing command at position #0: Class '$INPUT.EDGECLASS' was not found
	at com.orientechnologies.orient.graph.sql.OCommandExecutorSQLCreateEdge.parse(OCommandExecutorSQLCreateEdge.java:114)
	at com.orientechnologies.orient.graph.sql.OCommandExecutorSQLCreateEdge.parse(OCommandExecutorSQLCreateEdge.java:54)
	at com.orientechnologies.orient.core.sql.OCommandExecutorSQLDelegate.parse(OCommandExecutorSQLDelegate.java:56)
	at com.orientechnologies.orient.core.sql.OCommandExecutorSQLDelegate.parse(OCommandExecutorSQLDelegate.java:37)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.command(OAbstractPaginatedStorage.java:1176)
	at com.orientechnologies.orient.core.command.OCommandRequestTextAbstract.execute(OCommandRequestTextAbstract.java:63)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.command(ONetworkProtocolBinary.java:1178)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.executeRequest(ONetworkProtocolBinary.java:385)
	at com.orientechnologies.orient.server.network.protocol.binary.OBinaryNetworkProtocolAbstract.execute(OBinaryNetworkProtocolAbstract.java:220)
	at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:69)
ETL process halted: com.orientechnologies.orient.etl.OETLProcessHaltedException: com.orientechnologies.orient.core.sql.OCommandSQLParsingException: Error on parsing command at position #0: Class '$INPUT.EDGECLASS' was not found
```

**Comment by robfrank** [comment]
_From @lvca on April 4, 2015 13:33_

Try using ${input.edgeClass}

**Comment by robfrank** [comment]
_From @cory-p-oncota on September 10, 2015 15:23_

I'm unable to contribute directly but I believe the only issue is here (https://github.com/orientechnologies/orientdb-etl/blob/master/src/main/java/com/orientechnologies/orient/etl/transformer/OEdgeTransformer.java) at L:58. The class name should be generated via a call to the resolve method (from OAbstractTransformer) as is the case in the OVertexTransformer class.

Note, the EDGE transformer is also impacted by this bug.
