### ISSUE TITLE
java.util.ConcurrentModificationException on distributed server on insert

### ISSUE THREAD

**Issue by wouterv** [orientechnologies/orientdb#5172]
We got an java.util.ConcurrentModificationException in orient that only happens when running distributed. Running in a memory database, or a server in single mode doesn't give this issue.

Here's the stacktrace:
```
Exception in thread "main" com.orientechnologies.orient.core.exception.OTransactionException: Error on committing distributed transaction
	at com.orientechnologies.orient.server.distributed.ODistributedStorage.processCommitResult(ODistributedStorage.java:1228)
	at com.orientechnologies.orient.server.distributed.ODistributedStorage.commit(ODistributedStorage.java:1081)
	at com.orientechnologies.orient.core.tx.OTransactionOptimistic.doCommit(OTransactionOptimistic.java:609)
	at com.orientechnologies.orient.core.tx.OTransactionOptimistic.commit(OTransactionOptimistic.java:156)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.commit(ODatabaseDocumentTx.java:2582)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.commit(ODatabaseDocumentTx.java:2551)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.commit(ONetworkProtocolBinary.java:1221)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.executeRequest(ONetworkProtocolBinary.java:400)
	at com.orientechnologies.orient.server.network.protocol.binary.OBinaryNetworkProtocolAbstract.execute(OBinaryNetworkProtocolAbstract.java:223)
	at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:77)
Caused by: com.orientechnologies.orient.core.exception.ODatabaseException: Error on saving record #20:0
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.executeSaveRecord(ODatabaseDocumentTx.java:1944)
	at com.orientechnologies.orient.core.tx.OTransactionOptimistic.addRecord(OTransactionOptimistic.java:432)
	at com.orientechnologies.orient.core.tx.OTransactionOptimistic.saveRecord(OTransactionOptimistic.java:363)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.save(ODatabaseDocumentTx.java:2468)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.save(ODatabaseDocumentTx.java:120)
	at com.orientechnologies.orient.core.record.impl.ODocument.save(ODocument.java:1768)
	at com.orientechnologies.orient.core.record.impl.ODocument.save(ODocument.java:1759)
	at com.orientechnologies.orient.core.record.impl.ODocument.save(ODocument.java:81)
	at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinaryV0.recursiveLinkSave(ORecordSerializerBinaryV0.java:675)
	at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinaryV0.writeOptimizedLink(ORecordSerializerBinaryV0.java:689)
	at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinaryV0.writeSingleValue(ORecordSerializerBinaryV0.java:574)
	at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinaryV0.serialize(ORecordSerializerBinaryV0.java:260)
	at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinary.toStream(ORecordSerializerBinary.java:105)
	at com.orientechnologies.orient.core.record.impl.ODocument.toStream(ODocument.java:2285)
	at com.orientechnologies.orient.core.record.impl.ODocument.toStream(ODocument.java:671)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.executeSaveRecord(ODatabaseDocumentTx.java:1834)
	at com.orientechnologies.orient.core.tx.OTransactionOptimistic.addRecord(OTransactionOptimistic.java:432)
	at com.orientechnologies.orient.core.tx.OTransactionOptimistic.saveRecord(OTransactionOptimistic.java:363)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.save(ODatabaseDocumentTx.java:2468)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.save(ODatabaseDocumentTx.java:120)
	at com.orientechnologies.orient.core.record.impl.ODocument.save(ODocument.java:1768)
	at com.orientechnologies.orient.core.record.impl.ODocument.save(ODocument.java:1759)
	at com.orientechnologies.orient.core.record.impl.ODocument.save(ODocument.java:81)
	at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinaryV0.recursiveLinkSave(ORecordSerializerBinaryV0.java:675)
	at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinaryV0.writeOptimizedLink(ORecordSerializerBinaryV0.java:689)
	at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinaryV0.writeSingleValue(ORecordSerializerBinaryV0.java:574)
	at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinaryV0.serialize(ORecordSerializerBinaryV0.java:260)
	at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinary.toStream(ORecordSerializerBinary.java:105)
	at com.orientechnologies.orient.core.record.impl.ODocument.toStream(ODocument.java:2285)
	at com.orientechnologies.orient.core.record.impl.ODocument.toStream(ODocument.java:671)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.commitEntry(OAbstractPaginatedStorage.java:2328)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.commit(OAbstractPaginatedStorage.java:1111)
	at com.orientechnologies.orient.server.distributed.ODistributedStorage.commit(ODistributedStorage.java:969)
	at com.orientechnologies.orient.core.tx.OTransactionOptimistic.doCommit(OTransactionOptimistic.java:609)
	at com.orientechnologies.orient.core.tx.OTransactionOptimistic.commit(OTransactionOptimistic.java:156)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.commit(ODatabaseDocumentTx.java:2582)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.commit(ODatabaseDocumentTx.java:2551)
	at com.orientechnologies.orient.server.distributed.task.OTxTask.execute(OTxTask.java:131)
	at com.orientechnologies.orient.server.hazelcast.OHazelcastPlugin.executeOnLocalNode(OHazelcastPlugin.java:802)
	at com.orientechnologies.orient.server.hazelcast.ODistributedWorker.onMessage(ODistributedWorker.java:296)
	at com.orientechnologies.orient.server.hazelcast.ODistributedWorker.run(ODistributedWorker.java:119)
Caused by: java.util.ConcurrentModificationException
	at java.util.HashMap$HashIterator.nextEntry(HashMap.java:922)
	at java.util.HashMap$EntryIterator.next(HashMap.java:962)
	at java.util.HashMap$EntryIterator.next(HashMap.java:960)
	at com.orientechnologies.orient.core.db.record.ORecordLazySet$1.next(ORecordLazySet.java:96)
	at com.orientechnologies.orient.core.db.record.ORecordLazySet$1.next(ORecordLazySet.java:73)
	at com.orientechnologies.orient.core.db.record.OLazyRecordIterator.next(OLazyRecordIterator.java:68)
	at com.orientechnologies.orient.core.db.record.OLazyRecordIterator.next(OLazyRecordIterator.java:38)
	at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinaryV0.writeLinkCollection(ORecordSerializerBinaryV0.java:708)
	at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinaryV0.writeSingleValue(ORecordSerializerBinaryV0.java:568)
	at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinaryV0.serialize(ORecordSerializerBinaryV0.java:260)
	at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinary.toStream(ORecordSerializerBinary.java:105)
	at com.orientechnologies.orient.core.record.impl.ODocument.toStream(ODocument.java:2285)
	at com.orientechnologies.orient.core.record.impl.ODocument.toStream(ODocument.java:671)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.executeSaveRecord(ODatabaseDocumentTx.java:1834)
	... 40 more
```

Luckily, I was able to create a test case class which you can reproduce this. Just setup a cluster with two nodes (or perhaps more) and run the main program. If set the runInMemory flag to true, you'll see it just runs fine.

It has probably to do with multiple objects having references to the same childs, but are not being aware that one of those children has a changed ORID.

Here is the reproduction code:

```
import com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx;
import com.orientechnologies.orient.core.id.ORID;
import com.orientechnologies.orient.object.db.OObjectDatabaseTx;
import com.orientechnologies.orient.object.metadata.schema.OSchemaProxyObject;

import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.Version;
import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

public class OrientTest {

    private static boolean runInMemory;

    public static void main(String[] args) {

        ODatabaseDocumentTx documentTx;
        if (runInMemory) {
            documentTx = new ODatabaseDocumentTx("memory:test").create();
        } else {
            documentTx = new ODatabaseDocumentTx("remote:localhost/test").open("admin", "admin");
        }

        OObjectDatabaseTx db = new OObjectDatabaseTx(documentTx);

        OSchemaProxyObject schema = db.getMetadata().getSchema();
        db.getEntityManager().registerEntityClass(Parent.class);
        db.getEntityManager().registerEntityClass(Child.class);
        db.getEntityManager().registerEntityClass(OtherThing.class);
        schema.generateSchema(Parent.class);
        schema.generateSchema(Child.class);
        schema.generateSchema(OtherThing.class);
        Parent parent1 = new Parent();
        parent1 = db.save(parent1);

        Parent parent2 = new Parent();
        parent2 = db.save(parent2);


        Child child1 = new Child();
        parent1.getChildren().add(child1);
        parent1 = db.save(parent1);

        Child child2 = new Child();
        parent2.getChildren().add(child2);
        parent2 = db.save(parent2);

        parent1 = db.detachAll(parent1, true);
        parent2 = db.detachAll(parent2, true);


        db.close();

        db.open("admin", "admin");

        db.begin();
        parent1 = db.load((ORID) parent1.getId());
        parent2 = db.load((ORID) parent2.getId());
        Child child3 = new Child();
        OtherThing otherThing = new OtherThing();
        child3.setOtherThing(otherThing);
        otherThing.setRelationToParent1(parent1);
        otherThing.setRelationToParent2(parent2);
        parent1.getChildren().add(child3);
        parent2.getChildren().add(child3);
        db.save(parent1);
        db.save(parent2);
        db.commit();
    }

    public static class Parent {

        @Id
        private Serializable id;

        @Version
        private int version;

        private Set<Child> children = new HashSet<>();

        public Serializable getId() {
            return id;
        }

        public void setId(Serializable id) {
            this.id = id;
        }

        public Set<Child> getChildren() {
            return children;
        }

        public void setChildren(Set<Child> children) {
            this.children = children;
        }
    }


    public static class Child {

        @Id
        private Serializable id;

        @Version
        private int version;

        @OneToOne
        private OtherThing otherThing;


        public Serializable getId() {
            return id;
        }

        public void setId(Serializable id) {
            this.id = id;
        }

        public OtherThing getOtherThing() {
            return otherThing;
        }

        public void setOtherThing(OtherThing otherThing) {
            this.otherThing = otherThing;
        }
    }

    public static class OtherThing {

        @Id
        private Serializable id;

        @Version
        private int version;

        private Parent relationToParent1;
        private Parent relationToParent2;


        public Serializable getId() {
            return id;
        }

        public void setId(Serializable id) {
            this.id = id;
        }

        public Parent getRelationToParent1() {
            return relationToParent1;
        }

        public void setRelationToParent1(Parent relationToParent1) {
            this.relationToParent1 = relationToParent1;
        }

        public Parent getRelationToParent2() {
            return relationToParent2;
        }

        public void setRelationToParent2(Parent relationToParent2) {
            this.relationToParent2 = relationToParent2;
        }
    }
}
```

**Comment by lvca** [comment]
Thanks for the test case, I'm working on reproducing it now.

**Comment by lvca** [comment]
Running your code against 2 nodes with a fresh "test" database, everything is ok:

```
/Library/Java/JavaVirtualMachines/jdk1.8.0_20.jdk/Contents/Home/bin/java -agentlib:jdwp=transport=dt_socket,address=127.0.0.1:53388,suspend=y,server=n -server -Dfile.encoding=UTF-8 -classpath "/Library/Java/JavaVirtualMachines/jdk1.8.0_20.jdk/Contents/Home/lib/ant-javafx.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_20.jdk/Contents/Home/lib/dt.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_20.jdk/Contents/Home/lib/javafx-mx.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_20.jdk/Contents/Home/lib/jconsole.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_20.jdk/Contents/Home/lib/sa-jdi.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_20.jdk/Contents/Home/lib/tools.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_20.jdk/Contents/Home/jre/lib/charsets.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_20.jdk/Contents/Home/jre/lib/deploy.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_20.jdk/Contents/Home/jre/lib/javaws.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_20.jdk/Contents/Home/jre/lib/jce.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_20.jdk/Contents/Home/jre/lib/jfr.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_20.jdk/Contents/Home/jre/lib/jfxswt.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_20.jdk/Contents/Home/jre/lib/jsse.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_20.jdk/Contents/Home/jre/lib/management-agent.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_20.jdk/Contents/Home/jre/lib/plugin.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_20.jdk/Contents/Home/jre/lib/resources.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_20.jdk/Contents/Home/jre/lib/rt.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_20.jdk/Contents/Home/jre/lib/ext/cldrdata.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_20.jdk/Contents/Home/jre/lib/ext/dnsns.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_20.jdk/Contents/Home/jre/lib/ext/jfxrt.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_20.jdk/Contents/Home/jre/lib/ext/localedata.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_20.jdk/Contents/Home/jre/lib/ext/nashorn.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_20.jdk/Contents/Home/jre/lib/ext/sunec.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_20.jdk/Contents/Home/jre/lib/ext/sunjce_provider.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_20.jdk/Contents/Home/jre/lib/ext/sunpkcs11.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_20.jdk/Contents/Home/jre/lib/ext/zipfs.jar:/Users/luca/work/dev/orientechnologies/orientdb/community/distributed/target/test-classes:/Users/luca/work/dev/orientechnologies/orientdb/community/distributed/target/classes:/Users/luca/work/dev/orientechnologies/orientdb/community/server/target/classes:/Users/luca/work/dev/orientechnologies/orientdb/community/client/target/classes:/Users/luca/work/dev/orientechnologies/orientdb/community/enterprise/target/classes:/Users/luca/.m2/repository/javax/mail/mail/1.4/mail-1.4.jar:/Users/luca/.m2/repository/javax/activation/activation/1.1/activation-1.1.jar:/Users/luca/work/dev/orientechnologies/orientdb/community/graphdb/target/classes:/Users/luca/work/dev/orientechnologies/orientdb/community/tools/target/classes:/Users/luca/work/dev/orientechnologies/orientdb/community/object/target/classes:/Users/luca/.m2/repository/org/hibernate/javax/persistence/hibernate-jpa-2.0-api/1.0.0.Final/hibernate-jpa-2.0-api-1.0.0.Final.jar:/Users/luca/.m2/repository/org/javassist/javassist/3.16.1-GA/javassist-3.16.1-GA.jar:/Users/luca/work/dev/orientechnologies/orientdb/community/core/target/classes:/Users/luca/.m2/repository/org/xerial/snappy/snappy-java/1.1.0.1/snappy-java-1.1.0.1.jar:/Users/luca/.m2/repository/com/googlecode/concurrentlinkedhashmap/concurrentlinkedhashmap-lru/1.4.1/concurrentlinkedhashmap-lru-1.4.1.jar:/Users/luca/.m2/repository/net/java/dev/jna/jna/4.0.0/jna-4.0.0.jar:/Users/luca/.m2/repository/net/java/dev/jna/jna-platform/4.0.0/jna-platform-4.0.0.jar:/Users/luca/.m2/repository/com/tinkerpop/blueprints/blueprints-core/2.6.0/blueprints-core-2.6.0.jar:/Users/luca/.m2/repository/org/codehaus/jettison/jettison/1.3.3/jettison-1.3.3.jar:/Users/luca/.m2/repository/stax/stax-api/1.0.1/stax-api-1.0.1.jar:/Users/luca/.m2/repository/com/fasterxml/jackson/core/jackson-databind/2.2.3/jackson-databind-2.2.3.jar:/Users/luca/.m2/repository/com/fasterxml/jackson/core/jackson-annotations/2.2.3/jackson-annotations-2.2.3.jar:/Users/luca/.m2/repository/com/fasterxml/jackson/core/jackson-core/2.2.3/jackson-core-2.2.3.jar:/Users/luca/.m2/repository/com/carrotsearch/hppc/0.6.0/hppc-0.6.0.jar:/Users/luca/.m2/repository/commons-configuration/commons-configuration/1.6/commons-configuration-1.6.jar:/Users/luca/.m2/repository/commons-collections/commons-collections/3.2.1/commons-collections-3.2.1.jar:/Users/luca/.m2/repository/commons-lang/commons-lang/2.4/commons-lang-2.4.jar:/Users/luca/.m2/repository/commons-digester/commons-digester/1.8/commons-digester-1.8.jar:/Users/luca/.m2/repository/commons-beanutils/commons-beanutils/1.7.0/commons-beanutils-1.7.0.jar:/Users/luca/.m2/repository/commons-beanutils/commons-beanutils-core/1.8.0/commons-beanutils-core-1.8.0.jar:/Users/luca/.m2/repository/commons-logging/commons-logging/1.1.1/commons-logging-1.1.1.jar:/Users/luca/.m2/repository/com/tinkerpop/gremlin/gremlin-java/2.6.0/gremlin-java-2.6.0.jar:/Users/luca/.m2/repository/com/tinkerpop/pipes/2.6.0/pipes-2.6.0.jar:/Users/luca/.m2/repository/com/tinkerpop/gremlin/gremlin-groovy/2.6.0/gremlin-groovy-2.6.0.jar:/Users/luca/.m2/repository/org/apache/ivy/ivy/2.3.0/ivy-2.3.0.jar:/Users/luca/.m2/repository/org/codehaus/groovy/groovy/1.8.9/groovy-1.8.9.jar:/Users/luca/.m2/repository/antlr/antlr/2.7.7/antlr-2.7.7.jar:/Users/luca/.m2/repository/asm/asm/3.2/asm-3.2.jar:/Users/luca/.m2/repository/asm/asm-commons/3.2/asm-commons-3.2.jar:/Users/luca/.m2/repository/asm/asm-util/3.2/asm-util-3.2.jar:/Users/luca/.m2/repository/asm/asm-analysis/3.2/asm-analysis-3.2.jar:/Users/luca/.m2/repository/asm/asm-tree/3.2/asm-tree-3.2.jar:/Users/luca/.m2/repository/org/apache/ant/ant/1.8.3/ant-1.8.3.jar:/Users/luca/.m2/repository/org/apache/ant/ant-launcher/1.8.3/ant-launcher-1.8.3.jar:/Users/luca/.m2/repository/org/fusesource/jansi/jansi/1.5/jansi-1.5.jar:/Users/luca/.m2/repository/jline/jline/0.9.94/jline-0.9.94.jar:/Users/luca/.m2/repository/junit/junit/4.10/junit-4.10.jar:/Users/luca/.m2/repository/org/hamcrest/hamcrest-core/1.1/hamcrest-core-1.1.jar:/Users/luca/.m2/repository/com/hazelcast/hazelcast-all/3.3.5/hazelcast-all-3.3.5.jar:/Users/luca/.m2/repository/net/sourceforge/findbugs/annotations/1.3.2/annotations-1.3.2.jar:/Users/luca/.m2/repository/com/eclipsesource/minimal-json/minimal-json/0.9.1/minimal-json-0.9.1.jar:/Applications/IntelliJ IDEA 14 CE.app/Contents/lib/idea_rt.jar" com.orientechnologies.orient.server.distributed.DistributedObjectDatabaseTree
Connected to the target VM, address: '127.0.0.1:53388', transport: 'socket'
ott 20, 2015 7:26:43 PM com.orientechnologies.common.log.OLogManager log
INFORMAZIONI: OrientDB auto-config DISKCACHE=10.695MB (heap=3.641MB os=16.384MB disk=242.271MB)
ott 20, 2015 7:26:43 PM com.orientechnologies.common.log.OLogManager log
AVVERTENZA: Field 'private java.io.Serializable com.orientechnologies.orient.server.distributed.DistributedObjectDatabaseTree$Parent.id' cannot be managed as type: interface java.io.Serializable
ott 20, 2015 7:26:43 PM com.orientechnologies.common.log.OLogManager log
AVVERTENZA: Field 'private int com.orientechnologies.orient.server.distributed.DistributedObjectDatabaseTree$Parent.version' cannot be a literal to manage the Version
ott 20, 2015 7:26:43 PM com.orientechnologies.common.log.OLogManager log
AVVERTENZA: Field 'private java.io.Serializable com.orientechnologies.orient.server.distributed.DistributedObjectDatabaseTree$Child.id' cannot be managed as type: interface java.io.Serializable
ott 20, 2015 7:26:43 PM com.orientechnologies.common.log.OLogManager log
AVVERTENZA: Field 'private int com.orientechnologies.orient.server.distributed.DistributedObjectDatabaseTree$Child.version' cannot be a literal to manage the Version
ott 20, 2015 7:26:43 PM com.orientechnologies.common.log.OLogManager log
AVVERTENZA: Field 'private java.io.Serializable com.orientechnologies.orient.server.distributed.DistributedObjectDatabaseTree$OtherThing.id' cannot be managed as type: interface java.io.Serializable
ott 20, 2015 7:26:43 PM com.orientechnologies.common.log.OLogManager log
AVVERTENZA: Field 'private int com.orientechnologies.orient.server.distributed.DistributedObjectDatabaseTree$OtherThing.version' cannot be a literal to manage the Version
ott 20, 2015 7:26:44 PM com.orientechnologies.common.log.OLogManager log
AVVERTENZA: Field 'private java.io.Serializable com.orientechnologies.orient.server.distributed.DistributedObjectDatabaseTree$Parent.id' cannot be managed as type: interface java.io.Serializable
ott 20, 2015 7:26:44 PM com.orientechnologies.common.log.OLogManager log
AVVERTENZA: Field 'private int com.orientechnologies.orient.server.distributed.DistributedObjectDatabaseTree$Parent.version' cannot be a literal to manage the Version
ott 20, 2015 7:26:44 PM com.orientechnologies.common.log.OLogManager log
AVVERTENZA: Field 'private java.io.Serializable com.orientechnologies.orient.server.distributed.DistributedObjectDatabaseTree$Child.id' cannot be managed as type: interface java.io.Serializable
ott 20, 2015 7:26:44 PM com.orientechnologies.common.log.OLogManager log
AVVERTENZA: Field 'private int com.orientechnologies.orient.server.distributed.DistributedObjectDatabaseTree$Child.version' cannot be a literal to manage the Version
ott 20, 2015 7:26:44 PM com.orientechnologies.common.log.OLogManager log
AVVERTENZA: Field 'private java.io.Serializable com.orientechnologies.orient.server.distributed.DistributedObjectDatabaseTree$OtherThing.id' cannot be managed as type: interface java.io.Serializable
ott 20, 2015 7:26:44 PM com.orientechnologies.common.log.OLogManager log
AVVERTENZA: Field 'private int com.orientechnologies.orient.server.distributed.DistributedObjectDatabaseTree$OtherThing.version' cannot be a literal to manage the Version
Disconnected from the target VM, address: '127.0.0.1:53388', transport: 'socket'

Process finished with exit code 0
```

**Comment by wouterv** [comment]
Huh. Might be because we still use 2.0.15 as client?

**Comment by wouterv** [comment]
Yep that's it. I ran with the orient source checkout from 2.1.x branch, all works fine. Then checkout 2.0.x branch, and the test fails.

**Comment by lvca** [comment]
Ok, closing issue.
