### ISSUE TITLE
Use OrientDB JDBC in SOLR

### ISSUE THREAD

**Issue by robfrank** [orientechnologies/orientdb#5175]
_From @nomi-ramzan on June 7, 2015 8:49_

Hi !
I am trying to use orient jdbc in solr data import handler.
After load jdbc driver into solr config i am getting this error

```Exception in thread "Thread-15" java.lang.NoSuchMethodError: com.googlecode.concurrentlinkedhashmap.ConcurrentLinkedHashMap$Builder.maximumWeightedCapacity(J)Lcom/googlecode/concurrentl
inkedhashmap/ConcurrentLinkedHashMap$Builder;
        at com.orientechnologies.orient.core.db.record.ridbag.sbtree.OSBTreeCollectionManagerAbstract.<init>(OSBTreeCollectionManagerAbstract.java:43)
        at com.orientechnologies.orient.core.db.record.ridbag.sbtree.OSBTreeCollectionManagerAbstract.<init>(OSBTreeCollectionManagerAbstract.java:48)
        at com.orientechnologies.orient.client.remote.OSBTreeCollectionManagerRemote.<init>(OSBTreeCollectionManagerRemote.java:59)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:408)
        at java.lang.Class.newInstance(Class.java:433)
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx$2.call(ODatabaseDocumentTx.java:2674)
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx$2.call(ODatabaseDocumentTx.java:2665)
        at com.orientechnologies.common.concur.resource.OSharedContainerImpl.getResource(OSharedContainerImpl.java:57)
        at com.orientechnologies.orient.client.remote.OStorageRemoteThread.getResource(OStorageRemoteThread.java:650)
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.initAtFirstOpen(ODatabaseDocumentTx.java:2664)
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.open(ODatabaseDocumentTx.java:255)
        at com.orientechnologies.orient.jdbc.OrientJdbcConnection.<init>(OrientJdbcConnection.java:63)
        at com.orientechnologies.orient.jdbc.OrientJdbcDriver.connect(OrientJdbcDriver.java:48)
        at java.sql.DriverManager.getConnection(DriverManager.java:664)
        at java.sql.DriverManager.getConnection(DriverManager.java:208)
        at org.apache.solr.handler.dataimport.JdbcDataSource$1.call(JdbcDataSource.java:146)
        at org.apache.solr.handler.dataimport.JdbcDataSource$1.call(JdbcDataSource.java:133)
        at org.apache.solr.handler.dataimport.JdbcDataSource.getConnection(JdbcDataSource.java:402)
        at org.apache.solr.handler.dataimport.JdbcDataSource.access$200(JdbcDataSource.java:44)
        at org.apache.solr.handler.dataimport.JdbcDataSource$ResultSetIterator.<init>(JdbcDataSource.java:270)
        at org.apache.solr.handler.dataimport.JdbcDataSource.getData(JdbcDataSource.java:240)
        at org.apache.solr.handler.dataimport.JdbcDataSource.getData(JdbcDataSource.java:44)
        at org.apache.solr.handler.dataimport.SqlEntityProcessor.initQuery(SqlEntityProcessor.java:58)
        at org.apache.solr.handler.dataimport.SqlEntityProcessor.nextRow(SqlEntityProcessor.java:72)
        at org.apache.solr.handler.dataimport.EntityProcessorWrapper.nextRow(EntityProcessorWrapper.java:243)
        at org.apache.solr.handler.dataimport.DocBuilder.buildDocument(DocBuilder.java:475)
        at org.apache.solr.handler.dataimport.DocBuilder.buildDocument(DocBuilder.java:414)
        at org.apache.solr.handler.dataimport.DocBuilder.doFullDump(DocBuilder.java:329)
        at org.apache.solr.handler.dataimport.DocBuilder.execute(DocBuilder.java:232)
        at org.apache.solr.handler.dataimport.DataImporter.doFullImport(DataImporter.java:416)
        at org.apache.solr.handler.dataimport.DataImporter.runCmd(DataImporter.java:480)
        at org.apache.solr.handler.dataimport.DataImporter$1.run(DataImporter.java:461)```

How can I fix this problem ?

Thank you

_Copied from original issue: orientechnologies/orientdb-jdbc#27_

**Comment by robfrank** [comment]
_From @kwoxer on June 7, 2015 17:8_

Yeah much better here as an issue, please also place some ``` around the Java code. (makes it look nicer =)) like

``` 
System.out.print();
```

**Comment by robfrank** [comment]
_From @lvca on June 8, 2015 13:55_

What JARs have you linked?

**Comment by robfrank** [comment]
_From @nomi-ramzan on June 29, 2015 9:0_

Hi @lvca Extremely sorry for late reply. i tried all of them in my project
orientdb-jdbc-1.0-SNAPSHOT-all.jar
orientdb-jdbc-2.0.10.jar
orientdb-jdbc-2.0.10-all.jar
But same issue .

**Comment by robfrank** [comment]
_From @lvca on June 29, 2015 9:2_

That missing method is contained in concurrentlinkedhashmap-lru-1.4.jar, but it's included in `orientdb-jdbc-2.0.10-all.jar`. Could you put also that jar (it's part of OrientDB distribution) in your classpath?

**Comment by robfrank** [comment]
_From @nomi-ramzan on June 29, 2015 9:7_

Yes I am already using this jar file in my project. now i am going to try new version 2.0.11

**Comment by robfrank** [comment]
_From @nomi-ramzan on June 29, 2015 9:11_

Right now i just created new project then add  orientdb-jdbc-2.0.11.jar file in to class path and then 
executed this code 
```package sdafsaf;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.util.Properties;

import com.orientechnologies.orient.jdbc.OrientJdbcConnection;

public class mainCls {

	public static void main(String[] args) throws SQLException {
		Properties info = new Properties();
		info.put("user", "admin");
		info.put("password", "admin");
		Connection conn = (OrientJdbcConnection) DriverManager.getConnection("jdbc:orient:remote:localhost/test", info);
		System.out.print(conn);
	} }

And i am getting this error 
```Exception in thread "main" java.sql.SQLException: No suitable driver found for jdbc:orient:remote:localhost/test
	at java.sql.DriverManager.getConnection(Unknown Source)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at sdafsaf.mainCls.main(mainCls.java:17)```

**Comment by robfrank** [comment]
_From @lvca on June 29, 2015 9:24_

Please look at my comment earlier: don't use orientdb-jdbc-2.0.11.jar unless you want also to link all the dependent jars, but rather link **orientdb-jdbc-2.0.11-all.jar**.

**Comment by robfrank** [comment]
_From @nomi-ramzan on June 29, 2015 9:31_

Dear Luca I tried orientdb-jdbc-1.0-SNAPSHOT-all.jar
orientdb-jdbc-2.0.10.jar
orientdb-jdbc-2.0.10-all.jar all of them together and even one by one also tried the newer version orientdb-jdbc-2.0.11-all.jar alone right now which gives this kind of error 
```Exception in thread "main" java.sql.SQLException: No suitable driver found for jdbc:orient:remote:localhost/test
	at java.sql.DriverManager.getConnection(Unknown Source)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at sdafsaf.mainCls.main(mainCls.java:16)
```

**Comment by robfrank** [comment]
_From @nomi-ramzan on June 29, 2015 10:51_

Dear @lvca 
I tested even latest version( 2.0.11 ) same as orientdb-jdbc-2.0.10-all.jar , I am still getting this error
``` java.lang.NoSuchMethodError: com.googlecode.concurrentlinkedhashmap.ConcurrentLinkedHashMap$Builder.maximumWeightedCapacity(J)Lcom/googlecode/concurrentlinkedhashmap/ConcurrentLinkedHashMap$Builder; ```

I hope it will help you to find the issue.
Regards
Nauman Ramzan

**Comment by robfrank** [comment]
is still valid?
