### ISSUE TITLE
java.lang.NumberFormatException: For input string: ":�"

### ISSUE THREAD

**Issue by StarpTech** [orientechnologies/orientdb#5222]
Orientdb 2.1.4

```
orientdb {db=test}> import database /opt/databases/orientdb-community-2.1.4/backup.zip -preserveClusterIDs=true

Importing database database /opt/databases/orientdb-community-2.1.4/backup.zip -preserveClusterIDs=true...
Started import of database 'plocal:/opt/data/orientdb/databases/test' from /opt/databases/orientdb-community-2.1.4/backup.zip...
Non merge mode (-merge=false): removing all default non security classes
Removed 0 classes.Error on database import happened just before line 224, column 531
java.lang.NumberFormatException: For input string: ":�"
        at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
        at java.lang.Integer.parseInt(Integer.java:580)
        at com.orientechnologies.orient.core.serialization.serializer.OJSONReader.nextChar(OJSONReader.java:273)
        at com.orientechnologies.orient.core.serialization.serializer.OJSONReader.readNext(OJSONReader.java:174)
        at com.orientechnologies.orient.core.serialization.serializer.OJSONReader.readString(OJSONReader.java:92)
        at com.orientechnologies.orient.core.serialization.serializer.OJSONReader.readString(OJSONReader.java:87)
        at com.orientechnologies.orient.core.serialization.serializer.OJSONReader.readString(OJSONReader.java:83)
        at com.orientechnologies.orient.core.db.tool.ODatabaseImport.importDatabase(ODatabaseImport.java:423)
        at com.orientechnologies.orient.console.OConsoleDatabaseApp.importDatabase(OConsoleDatabaseApp.java:1711)
        at com.orientechnologies.orient.graph.console.OGremlinConsole.importDatabase(OGremlinConsole.java:126)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at com.orientechnologies.common.console.OConsoleApplication.execute(OConsoleApplication.java:392)
        at com.orientechnologies.common.console.OConsoleApplication.executeCommands(OConsoleApplication.java:253)
        at com.orientechnologies.common.console.OConsoleApplication.run(OConsoleApplication.java:142)
        at com.orientechnologies.orient.graph.console.OGremlinConsole.main(OGremlinConsole.java:64)

Error: com.orientechnologies.orient.core.db.tool.ODatabaseExportException: Error on importing database 'test' from file: /opt/databases/orientdb-community-2.1.4/backup.zip

Error: java.lang.NumberFormatException: For input string: ":�"

orientdb {db=test}> exit

´´´

**Comment by StarpTech** [comment]
Related https://github.com/orientechnologies/orientdb/issues/4277

**Comment by StarpTech** [comment]
Also here in the Export file I can not see anything which looks like this character.

**Comment by StarpTech** [comment]
In my opinion the operation must not be interrupted. In this scenario it is legitim to use an initial value like 0, 0.0, "" to rescue the database.

**Comment by EricLin2004** [comment]
Getting this issue as well. Exported / tried importing with 2.1.10.

**Comment by lvca** [comment]
@StarpTech i see issue #4277 is closed. Is this still open?

**Comment by StarpTech** [comment]
@lvca I didnt get this error but I think is not fixed by the core I cleaned up my database. @EricLin2004 perhaps you can check whether you can find any none number values. Export your db as json and start a pattern search or via sql in studio.

**Comment by lvca** [comment]
Anybody has any database I can export/import so we can reproduce the problem?

**Comment by vsmori** [comment]
@lvca i have sent it privately into your email. Version 2.0.12 originally.

**Comment by lvca** [comment]
@vsmori sorry, but release v2.0.12 is not supported anymore. Please upgrade to 2.2.x.

**Comment by eegii-mgl** [comment]
I still have this error on local 2.2.10 dev EE.

**Comment by lvca** [comment]
@eegii-mgl any way to reproduce the problem? Your database export?

**Comment by eegii-mgl** [comment]
I think mine was trying to import backup formatted file (.zip) instead of export formatted file (.gz) Are these files different?
