### ISSUE TITLE
Cannot use user defined functions in ETL process

### ISSUE THREAD

**Issue by AlessioDeAngelis** [orientechnologies/orientdb#5236]
Hello,
I created with Studio a dummy javascript function test()  that simply returns 0. 
It works perfectly when I call it in STUDIO in a simple query
SELECT test() FROM V.
However, when I try to call it within the etl process, orientdb doesn't recognize it.

{ "field": {"fieldName": "test", "expression": "eval('test()')"  } }

{ "field": {"fieldName": "test", "expression": "test()"  } }

In both cases I have the following error:

Error in Pipeline execution: com.orientechnologies.orient.core.exception.OQueryParsingException: Error on parsing command at position #0: Error on parsing query
Query: test()
------^
ETL process halted: com.orientechnologies.orient.etl.OETLProcessHaltedException: Halt
Exception in thread "main" com.orientechnologies.orient.etl.OETLProcessHaltedException: Halt
        at com.orientechnologies.orient.etl.OETLPipeline.execute(OETLPipeline.java:149)
        at com.orientechnologies.orient.etl.OETLProcessor.executeSequentially(OETLProcessor.java:458)

Caused by: com.orientechnologies.orient.core.sql.OCommandSQLParsingException: Error on parsing command at position #0: No function with name 'test', available names are : [outv,percentile,ifnull,both,last,count,set,traversedvertex,sum,bothv,date,shortestpath,distinct,mode,distance,document,if,gremlin,map,bothe,avg,dijkstra,min,encode,coalesce,max,eval,traversedelement,ine,label,variance,list,format,in,concat,decimal,difference,symmetricdifference,median,decode,unionall,sysdate,intersect,inv,stddev,uuid,traversededge,oute,first,out]

Is there another way to call user defined functions?
Thank you.
Alessio

**Comment by tanhv90** [comment]
Hello @luigidellaquila ,

How about the current status of this issue?
I'm facing same problem on 2.2.11.

Best regards,
Tan
