### ISSUE TITLE
OSQLNonBlockingQuery misbehaves on bad SQL input

### ISSUE THREAD

**Issue by cstamas** [orientechnologies/orientdb#5244]
When using OSQLNonBlockingQuery with bad (malformed, having bad syntax) query, the OSQLNonBlockingQuery will misbehave by not reporting it back to caller in any way. Even worse, the caller remains unaware what actually happened.

On execute OSQLNonBlockingQuery will start another thread:
https://github.com/sonatype/orientdb/blob/aecb7a891e945575c3ceb6ff29341ca68551df98/core/src/main/java/com/orientechnologies/orient/core/sql/query/OSQLNonBlockingQuery.java#L246

But the execution will fail (on newly started thread) but nothing will notify the listener about it, nor end method will be invoked of listener.

Example stack trace (SQL broken intentionally for example sake):
Exception in thread "Thread-121" com.orientechnologies.orient.core.command.OCommandExecutorNotFoundException: Cannot find a command executor for the command request: sql.SELECTbrokenForExample
	at com.orientechnologies.orient.core.sql.OCommandExecutorSQLDelegate.parse(OCommandExecutorSQLDelegate.java:72)
	at com.orientechnologies.orient.core.sql.OCommandExecutorSQLDelegate.parse(OCommandExecutorSQLDelegate.java:42)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.command(OAbstractPaginatedStorage.java:1431)
	at com.orientechnologies.orient.core.sql.query.OSQLQuery.run(OSQLQuery.java:72)
	at com.orientechnologies.orient.core.query.OQueryAbstract.execute(OQueryAbstract.java:33)
	at com.orientechnologies.orient.core.sql.query.OSQLNonBlockingQuery.access$001(OSQLNonBlockingQuery.java:48)
	at com.orientechnologies.orient.core.sql.query.OSQLNonBlockingQuery$1.run(OSQLNonBlockingQuery.java:251)
	at java.lang.Thread.run(Thread.java:745)

Also, note the use of printStackTrace

**Comment by luigidellaquila** [comment]
Hi @cstamas 

Thanks for reporting, I'm working on a fix right now

Thanks

Luigi

**Comment by luigidellaquila** [comment]
Hi @cstamas 

invoking the ```end()``` method should be an easy fix, the real problem is that ```OCommandResultListener``` does not have an ```onError()``` method, so the thread cannot communicate when an error occurs.

I'm thinking about defining a new interface (something like OCommandErrorListener) for this  purpose, but we have to evaluate if it can be done in a hotfix release.

I'll let you know soon

Thanks

Luigi

**Comment by cstamas** [comment]
Another area of improvement might be to use some thread pool maybe, instead by creating a thread "manually", as that could offer better control and resource use over spawned threads too. Just throwing out ideas :smile: 

Thanks!

**Comment by luigidellaquila** [comment]
You are absolutely right, it's in the roadmap

Thanks

Luigi

**Comment by cstamas** [comment]
Similar stack trace (but other reason, basically a bug, out of bound attempt to use DB):

Exception in thread "Thread-171" com.orientechnologies.orient.core.exception.ODatabaseException: Cannot copy a closed db
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.copy(ODatabaseDocumentTx.java:497)
	at com.orientechnologies.orient.core.sql.query.OSQLNonBlockingQuery$1.run(OSQLNonBlockingQuery.java:249)
	at java.lang.Thread.run(Thread.java:745)

**Comment by luigidellaquila** [comment]
Hi @cstamas 

I just fixed this problem. The fix will be released in 2.1.9 and 2.2.

I'm closing this issue and I created this

https://github.com/orientechnologies/orientdb/issues/5484

to track the enhancement of the OCommandResultListener interface

Thanks

Luigi
