### ISSUE TITLE
empty result for index query

### ISSUE THREAD

**Issue by martingg88** [orientechnologies/orientdb#5252]
do you have any idea on why the return results is empty even i do have data for that class that consist of this index. 

 select key, value from index:hotel.name

**Comment by maggiolo00** [comment]
@martingg88 which type of index is hotel.name?

**Comment by martingg88** [comment]
LUCENE fulltext

another issue. i do have java.lang.UnsupportedOperationException: firstKey for NOTUNIQUE_HASH_INDEX

select key, value from index:user.gender

**Comment by maggiolo00** [comment]
The problem is that with

select key, value from index:user.gender

requires a index scan and i think neither HASH INDEX and LUCENE FULLText supports it.

try to put a  filter

```
select key, value from index:user.gender where key =''
```

**Comment by lvca** [comment]
@maggiolo00 while this is a roundtrip, I'd assign this to @luigidellaquila to make working the query with no conditions even when the index doesn't support scan.

**Comment by martingg88** [comment]
thanks. one more question here. 

does lucene index query support lucene query parser like following?

select from index:manual where key LUCENE 'key:Enrico~0.5'

**Comment by martingg88** [comment]
another issue for lucene full text search.

result have returned: 
select from user where first_name LUCENE "expedia"

no result returned. very weird. 

select from user 
where [first_name, last_name]  LUCENE "(first_name:expedia OR last_name:expedia)"

select from user 
where [first_name, last_name]  LUCENE "expedia"

**Comment by martingg88** [comment]
another issue here..

select  from user
where first_name LUCENE "expedia~" or last_name LUCENE "expedia~"

parser error as follows: 

com.orientechnologies.orient.core.exception.OQueryParsingException: Error on parsing command at position #0: Incompatible conditions found: first_name LUCENE "expedia~" last_name LUCENE "expedia~"

**Comment by maggiolo00** [comment]
@martingg88  which version are you using?

```
select from user where [first_name, last_name] LUCENE "(first_name:expedia OR last_name:expedia)"

select from user where [first_name, last_name] LUCENE "expedia"
```

Do you have one index on 2 fields or do you have two indexes?

**Comment by martingg88** [comment]
v2.1.4...

yes i do index for both fields. i even try to add separate index for both fields and can't work at all.

**Comment by maggiolo00** [comment]
@martingg88 

can you post here the explain of

```
select from user 
where [first_name, last_name] LUCENE "expedia"
```

**Comment by martingg88** [comment]
i think the issue is not from lucene itself. 

i think we will have this issue after rebuild the index few times. here is the error log. 

2015-11-04 23:37:29:639 INFO  {db=hotel} - Rebuilding index hotel.user.first_name_last_name (estimated 3 items)...
 [OIndexRebuildOutputListener]Exception in thread "Thread-34" java.lang.RuntimeException: java.io.IOException: Can
not overwrite: C:\project\database\databases\hotel\luceneIndexes\user.first_name_last_name\_0.cfs
        at org.apache.lucene.search.ControlledRealTimeReopenThread.run(ControlledRealTimeReopenThread.java:247)
Caused by: java.io.IOException: Cannot overwrite: C:\project\database\databases\hotel\luceneIndexes\user.first_nam
e_last_name\_0.cfs
        at org.apache.lucene.store.FSDirectory.ensureCanWrite(FSDirectory.java:293)
        at org.apache.lucene.store.FSDirectory.createOutput(FSDirectory.java:282)
        at org.apache.lucene.store.TrackingDirectoryWrapper.createOutput(TrackingDirectoryWrapper.java:44)
        at org.apache.lucene.store.CompoundFileWriter.getOutput(CompoundFileWriter.java:103)
        at org.apache.lucene.store.CompoundFileWriter.createOutput(CompoundFileWriter.java:231)
        at org.apache.lucene.store.CompoundFileDirectory.createOutput(CompoundFileDirectory.java:332)
        at org.apache.lucene.store.Directory.copy(Directory.java:184)
        at org.apache.lucene.store.TrackingDirectoryWrapper.copy(TrackingDirectoryWrapper.java:50)
        at org.apache.lucene.index.IndexWriter.createCompoundFile(IndexWriter.java:4645)
        at org.apache.lucene.index.DocumentsWriterPerThread.sealFlushedSegment(DocumentsWriterPerThread.java:535)
        at org.apache.lucene.index.DocumentsWriterPerThread.flush(DocumentsWriterPerThread.java:502)
        at org.apache.lucene.index.DocumentsWriter.doFlush(DocumentsWriter.java:506)
        at org.apache.lucene.index.DocumentsWriter.flushAllThreads(DocumentsWriter.java:616)
        at org.apache.lucene.index.IndexWriter.getReader(IndexWriter.java:370)
        at org.apache.lucene.index.StandardDirectoryReader.doOpenFromWriter(StandardDirectoryReader.java:288)
        at org.apache.lucene.index.StandardDirectoryReader.doOpenIfChanged(StandardDirectoryReader.java:263)
        at org.apache.lucene.index.StandardDirectoryReader.doOpenIfChanged(StandardDirectoryReader.java:253)
        at org.apache.lucene.index.DirectoryReader.openIfChanged(DirectoryReader.java:170)
        at org.apache.lucene.search.SearcherManager.refreshIfNeeded(SearcherManager.java:118)
        at org.apache.lucene.search.SearcherManager.refreshIfNeeded(SearcherManager.java:58)
        at org.apache.lucene.search.ReferenceManager.doMaybeRefresh(ReferenceManager.java:176)
        at org.apache.lucene.search.ReferenceManager.maybeRefreshBlocking(ReferenceManager.java:253)
        at org.apache.lucene.search.ControlledRealTimeReopenThread.run(ControlledRealTimeReopenThread.java:245)
        Suppressed: java.io.IOException: Cannot overwrite: C:\project\database\databases\hotel\luceneIndexes\user.

**Comment by maggiolo00** [comment]
@martingg88 

can you help me replicate this rebuild issue?
Which are the steps to reproduce it?

**Comment by martingg88** [comment]
here are steps that might create that issue. 

create lucene composite index for both fields. 
create individual lucene index for both fields. 
repeat this step few times - drop and re-create all indexes. 

you should be able to see the error.

**Comment by martingg88** [comment]
@lvca 

any update for following issue?

 @maggiolo00 while this is a roundtrip, I'd assign this to @luigidellaquila to make working the query with no conditions even when the index doesn't support scan.
