### ISSUE TITLE
Enable/Disable WAL per database via API

### ISSUE THREAD

**Issue by lvca** [orientechnologies/orientdb#5254]
We'd need an high level API to enable/disable WAL. Now to reach this goal this sequence of calls is needed:

``` java
private void reopenWithWALSetTo(final boolean useWAL) {
    db.getStorage().close(true, false);
    db.close();
    OGlobalConfiguration.USE_WAL.setValue(useWAL);
    db = new ODatabaseDocumentTx(dbURL);
    db.open("admin", "admin");
}
```

To know more: http://stackoverflow.com/questions/33415440/toggling-wal-usage-within-same-vm/33453634#33453634

**Comment by bluezio** [comment]
Thanks for doing this!

**Comment by bluezio** [comment]
One question: maybe this snippet is missing something, because at times we get now these exceptions. It looks as if we should clean up some cache as well. Are we missing something, perhaps?

```
java.lang.NullPointerException
	at com.orientechnologies.orient.core.storage.fs.OFileClassic.read(OFileClassic.java:78)
	at com.orientechnologies.orient.core.index.hashindex.local.cache.OWOWCache.cacheFileContent(OWOWCache.java:1015)
	at com.orientechnologies.orient.core.index.hashindex.local.cache.OWOWCache.load(OWOWCache.java:514)
	at com.orientechnologies.orient.core.index.hashindex.local.cache.OReadWriteDiskCache.updateCache(OReadWriteDiskCache.java:687)
	at com.orientechnologies.orient.core.index.hashindex.local.cache.OReadWriteDiskCache.doLoad(OReadWriteDiskCache.java:309)
	at com.orientechnologies.orient.core.index.hashindex.local.cache.OReadWriteDiskCache.load(OReadWriteDiskCache.java:275)
	at com.orientechnologies.orient.core.storage.impl.local.paginated.base.ODurableComponent.loadPage(ODurableComponent.java:123)
	at com.orientechnologies.orient.core.index.sbtreebonsai.local.OSBTreeBonsaiLocal.findBucket(OSBTreeBonsaiLocal.java:1169)
	at com.orientechnologies.orient.core.index.sbtreebonsai.local.OSBTreeBonsaiLocal.loadEntriesMajor(OSBTreeBonsaiLocal.java:674)
	at com.orientechnologies.orient.core.index.sbtree.OSBTreeMapEntryIterator.prefetchData(OSBTreeMapEntryIterator.java:63)
	at com.orientechnologies.orient.core.index.sbtree.OSBTreeMapEntryIterator.next(OSBTreeMapEntryIterator.java:109)
	at com.orientechnologies.orient.core.db.record.ridbag.sbtree.OIndexRIDContainerSBTree$TreeKeyIterator.next(OIndexRIDContainerSBTree.java:226)
	at com.orientechnologies.orient.core.db.record.ridbag.sbtree.OIndexRIDContainerSBTree$TreeKeyIterator.next(OIndexRIDContainerSBTree.java:210)
	at com.orientechnologies.orient.core.index.engine.OSBTreeIndexEngine$OSBTreeIndexCursor.nextEntry(OSBTreeIndexEngine.java:419)
	at com.orientechnologies.orient.core.index.OIndexAbstractCursor.next(OIndexAbstractCursor.java:97)
	at com.orientechnologies.orient.core.index.OIndexAbstractCursor.next(OIndexAbstractCursor.java:34)
	at org.hawk.orientdb.indexes.IndexCursorFactoryNodeIterable$1.next(IndexCursorFactoryNodeIterable.java:50)
	at org.hawk.graph.internal.updater.GraphModelInserter.resolveProxies(GraphModelInserter.java:883)
	at org.hawk.graph.internal.updater.GraphModelUpdater.updateProxies(GraphModelUpdater.java:114)
	at org.hawk.core.runtime.ModelIndexerImpl.internalSynchronise(ModelIndexerImpl.java:348)
	at org.hawk.core.runtime.ModelIndexerImpl.runUpdateTask(ModelIndexerImpl.java:852)
	at org.hawk.core.runtime.ModelIndexerImpl.access$0(ModelIndexerImpl.java:843)
	at org.hawk.core.runtime.ModelIndexerImpl$RunUpdateTask.run(ModelIndexerImpl.java:71)
	at java.util.TimerThread.mainLoop(Timer.java:555)
	at java.util.TimerThread.run(Timer.java:505)
```

**Comment by bluezio** [comment]
I removed my previous comment mentioning an exception we were getting, to avoid confusion. I found out that we were reopening the database while we were iterating query results on our index, due to an odd interaction between our OrientDB backend and the Hawk core.

**Comment by lvca** [comment]
@laa we already have a setting per storage about USE_WAL, we'd need here a way to safely enable/disable WAL.

**Comment by laa** [comment]
The problem there that we can not enable wal in the middle of database interaction. The only way is to close storage and reopen again, exactly as described in issue. We may only provide single command wrapper.

**Comment by lvca** [comment]
Could you please provide a friendly API that does that?

**Comment by lvca** [comment]
Not relevant anymore, closing it.

**Comment by bluezio** [comment]
Just curious: why? Have there been any changes to the WAL in 3.0?
