### ISSUE TITLE
Invalid value of TX counter

### ISSUE THREAD

**Issue by sethrife** [orientechnologies/orientdb#5273]
We are seeing the following error since we've upgraded to this particular version when adding a vertex:

Caused by: com.orientechnologies.orient.core.exception.OStorageException: Invalid value of TX counter
        at com.orientechnologies.orient.core.tx.OTransactionOptimistic.rollback(OTransactionOptimistic.java:175) ~[stormjar.jar:na]
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.commit(ODatabaseDocumentTx.java:2666) ~[stormjar.jar:na]
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.commit(ODatabaseDocumentTx.java:2622) ~[stormjar.jar:na]
        at com.tinkerpop.blueprints.impls.orient.OrientTransactionalGraph.commit(OrientTransactionalGraph.java:161) ~[stormjar.jar:na]
        at x.x.x.services.Tinkerpop2GraphOperations.addVertex(OceanusTinkerpop2GraphOperations.java:36) ~[stormjar.jar:na]
        at x.x.x.x.processor.Processor.lambda$addVertex$5(RaindropProcessor.java:179) ~[stormjar.jar:na]
        at x.x.x.services.ServiceTemplate.lambda$execute$8(ServiceTemplate.java:21) ~[stormjar.jar:na]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[na:1.8.0_65]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[na:1.8.0_65]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[na:1.8.0_65]

I've seen some references to a similar error on Github issues but it doesn't appear to same issue. Any ideas?

**Comment by lvca** [comment]
What release? Please always provide it

**Comment by sethrife** [comment]
2.1.5.

I apologize, the version was provided when filling out the initial issue.

**Comment by grossvater** [comment]
I can reproduce it in conditions described here: http://stackoverflow.com/questions/33346027/invalid-value-of-tx-counter-when-delete-vertexes-with-orientdb-2-1-x. In my case, it seems related to low heap memory (java -Xmx setting)

**Comment by laa** [comment]
Hi @sethrife , sorry for long response could you set log level FINE for com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx logger and send me results of  logging ?

**Comment by laa** [comment]
Close issue because of no reply. If you reproduce given issue and have information which is requested in issue feel free to reopen it.
