### ISSUE TITLE
Cannot connect to remote database during tests

### ISSUE THREAD

**Issue by cory-p-oncota** [orientechnologies/orientdb#5274]
I am creating a connection supplier as follows to a remote database:

```scala
package com.cota.dendron.core

import com.tinkerpop.blueprints.impls.orient.OrientGraphFactory
import com.typesafe.config.ConfigFactory

object DBFactory {
  val config = ConfigFactory.load()

  val factory = new OrientGraphFactory(
    "remote:" + config.getString("com.cota.dendron.orientdb-instance") + "/dendron",
    config.getString("com.cota.dendron.orientdb-user"),
    config.getString("com.cota.dendron.orientdb-password")).setupPool(1, 10)
}
```

...and then acquiring a connection within an Akka actor:

```scala
val dendron = DBFactory.factory.getTx
```

When running the web server, these connections work without issue, however, when executing unit tests against the actor, the following stack is thrown on factory creation:

```
ScriptEngineManager providers.next(): javax.script.ScriptEngineFactory: Provider com.tinkerpop.gremlin.scala.jsr223.ScriptEngineFactory could not be instantiated
Nov 04, 2015 6:08:45 PM com.orientechnologies.common.log.OLogManager log
WARNING: Cannot find default script language for javascript
Nov 04, 2015 6:08:45 PM com.orientechnologies.common.log.OLogManager log
INFO: OrientDB auto-config DISKCACHE=13,407MB (heap=928MB os=16,384MB disk=123,877MB)
Nov 04, 2015 6:08:45 PM com.orientechnologies.common.log.OLogManager log
SEVERE: MBean for read cache cannot be registered
com.orientechnologies.orient.core.exception.OStorageException: Error during registration of read cache MBean.
        at com.orientechnologies.orient.core.storage.cache.local.O2QCache.registerMBean(O2QCache.java:530)
        at com.orientechnologies.orient.core.engine.local.OEngineLocalPaginated.<init>(OEngineLocalPaginated.java:47)
        at com.orientechnologies.orient.core.Orient.startup(Orient.java:224)
        at com.orientechnologies.orient.core.Orient.<clinit>(Orient.java:87)
        at com.orientechnologies.orient.core.serialization.serializer.record.string.ORecordSerializerStringAbstract.<clinit>(ORecordSerializerStringAbstract.java:52)
        at com.orientechnologies.orient.core.serialization.serializer.record.ORecordSerializerFactory.<init>(ORecordSerializerFactory.java:47)
        at com.orientechnologies.orient.core.serialization.serializer.record.ORecordSerializerFactory.<clinit>(ORecordSerializerFactory.java:37)
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.<clinit>(ODatabaseDocumentTx.java:127)
        at com.orientechnologies.orient.core.db.OPartitionedDatabasePool.initQueue(OPartitionedDatabasePool.java:386)
        at com.orientechnologies.orient.core.db.OPartitionedDatabasePool.<init>(OPartitionedDatabasePool.java:186)
        at com.tinkerpop.blueprints.impls.orient.OrientGraphFactory.setupPool(OrientGraphFactory.java:161)
        at com.cota.dendron.core.DBFactory$.<init>(OrientDBFactory.scala:12)
        at com.cota.dendron.core.DBFactory$.<clinit>(OrientDBFactory.scala)
        at com.cota.dendron.core.recognition.RecognitionActorTest.<init>(RecognitionActorTest.scala:17)
        at com.cota.dendron.core.recognition.RecognitionActorTest.<init>(RecognitionActorTest.scala:19)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
        at java.lang.Class.newInstance(Class.java:442)
        at org.scalatest.tools.Framework$ScalaTestTask.execute(Framework.scala:646)
        at sbt.TestRunner.runTest$1(TestFramework.scala:76)
        at sbt.TestRunner.run(TestFramework.scala:85)
        at sbt.TestFramework$$anon$2$$anonfun$$init$$1$$anonfun$apply$8.apply(TestFramework.scala:202)
        at sbt.TestFramework$$anon$2$$anonfun$$init$$1$$anonfun$apply$8.apply(TestFramework.scala:202)
        at sbt.TestFramework$.sbt$TestFramework$$withContextLoader(TestFramework.scala:185)
        at sbt.TestFramework$$anon$2$$anonfun$$init$$1.apply(TestFramework.scala:202)
        at sbt.TestFramework$$anon$2$$anonfun$$init$$1.apply(TestFramework.scala:202)
        at sbt.TestFunction.apply(TestFramework.scala:207)
        at sbt.Tests$$anonfun$9.apply(Tests.scala:216)
        at sbt.Tests$$anonfun$9.apply(Tests.scala:216)
        at sbt.std.Transform$$anon$3$$anonfun$apply$2.apply(System.scala:44)
        at sbt.std.Transform$$anon$3$$anonfun$apply$2.apply(System.scala:44)
        at sbt.std.Transform$$anon$4.work(System.scala:63)
        at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
        at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
        at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
        at sbt.Execute.work(Execute.scala:235)
        at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
        at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
        at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
        at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: javax.management.InstanceAlreadyExistsException: com.orientechnologies.orient.core.storage.cache.local:type=O2QCacheMXBean
        at com.sun.jmx.mbeanserver.Repository.addMBean(Repository.java:437)
        at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.registerWithRepository(DefaultMBeanServerInterceptor.java:1898)
        at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.registerDynamicMBean(DefaultMBeanServerInterceptor.java:966)
        at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.registerObject(DefaultMBeanServerInterceptor.java:900)
        at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.registerMBean(DefaultMBeanServerInterceptor.java:324)
        at com.sun.jmx.mbeanserver.JmxMBeanServer.registerMBean(JmxMBeanServer.java:522)
        at com.orientechnologies.orient.core.storage.cache.local.O2QCache.registerMBean(O2QCache.java:526)
        ... 47 more
```

Do I need to handle initiation and shutdown in a special manner for testing or is this potentially a bug I am encountering?

**Comment by cory-p-oncota** [comment]
Running from SBT requires the following configuration:

fork := true

**Comment by lvca** [comment]
Thanks, it will be useful to the further users. Added under Scala page: http://orientdb.com/docs/last/Scala-Language.html
