### ISSUE TITLE
ConcurrentModificationException in distributed setup with linked sets

### ISSUE THREAD

**Issue by wouterv** [orientechnologies/orientdb#5279]
This is a copy of github bug #5172. 

In that bug it was stated that my use case ran correctly in 2.1.5 and that the problem was that my client was 2.0.15. We upgraded our code to 2.1.5, but the issue persists. So now I try again in the orient source with my testcase running a fresh distributed 2.1.5 enterprise server, and it fails. 

To reproduce:
Unzip 2 copies of orient enterprise 2.1.5 and make sure they are a setup as a cluster.

Create a new plocal test database and make sure the database is synchronized and distributed over both servers. 

Run the following program in the orient source with tag 2.1.5, I put the class in tests/src/tests/java

```
import com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx;
import com.orientechnologies.orient.core.id.ORID;
import com.orientechnologies.orient.object.db.OObjectDatabaseTx;
import com.orientechnologies.orient.object.metadata.schema.OSchemaProxyObject;

import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.Version;
import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

public class OrientTest {

    public static void main(String[] args) {

        ODatabaseDocumentTx documentTx = new ODatabaseDocumentTx("remote:localhost/test").open("admin", "admin");

        OObjectDatabaseTx db = new OObjectDatabaseTx(documentTx);

        OSchemaProxyObject schema = db.getMetadata().getSchema();
        db.getEntityManager().registerEntityClass(Parent.class);
        db.getEntityManager().registerEntityClass(Child.class);
        db.getEntityManager().registerEntityClass(OtherThing.class);
        schema.generateSchema(Parent.class);
        schema.generateSchema(Child.class);
        schema.generateSchema(OtherThing.class);
        Parent parent1 = new Parent();
        parent1 = db.save(parent1);

        Parent parent2 = new Parent();
        parent2 = db.save(parent2);


        Child child1 = new Child();
        parent1.getChildren().add(child1);
        parent1 = db.save(parent1);

        Child child2 = new Child();
        parent2.getChildren().add(child2);
        parent2 = db.save(parent2);

        parent1 = db.detachAll(parent1, true);
        parent2 = db.detachAll(parent2, true);


        db.close();

        db.open("admin", "admin");

        db.begin();
        parent1 = db.load((ORID) parent1.getId());
        parent2 = db.load((ORID) parent2.getId());
        Child child3 = new Child();
        OtherThing otherThing = new OtherThing();
        child3.setOtherThing(otherThing);
        otherThing.setRelationToParent1(parent1);
        otherThing.setRelationToParent2(parent2);
        parent1.getChildren().add(child3);
        parent2.getChildren().add(child3);
        db.save(parent1);
        db.save(parent2);
        db.commit();
    }

    public static class Parent {

        @Id
        private Serializable id;

        @Version
        private int version;

        private Set<Child> children = new HashSet<Child>();

        public Serializable getId() {
            return id;
        }

        public void setId(Serializable id) {
            this.id = id;
        }

        public Set<Child> getChildren() {
            return children;
        }

        public void setChildren(Set<Child> children) {
            this.children = children;
        }
    }


    public static class Child {

        @Id
        private Serializable id;

        @Version
        private int version;

        @OneToOne
        private OtherThing otherThing;


        public Serializable getId() {
            return id;
        }

        public void setId(Serializable id) {
            this.id = id;
        }

        public OtherThing getOtherThing() {
            return otherThing;
        }

        public void setOtherThing(OtherThing otherThing) {
            this.otherThing = otherThing;
        }
    }

    public static class OtherThing {

        @Id
        private Serializable id;

        @Version
        private int version;

        private Parent relationToParent1;
        private Parent relationToParent2;


        public Serializable getId() {
            return id;
        }

        public void setId(Serializable id) {
            this.id = id;
        }

        public Parent getRelationToParent1() {
            return relationToParent1;
        }

        public void setRelationToParent1(Parent relationToParent1) {
            this.relationToParent1 = relationToParent1;
        }

        public Parent getRelationToParent2() {
            return relationToParent2;
        }

        public void setRelationToParent2(Parent relationToParent2) {
            this.relationToParent2 = relationToParent2;
        }
    }
}
```
Error on server:
```
Error on distributed transaction commit
com.orientechnologies.orient.core.exception.ODatabaseException: Error on saving record #20:2
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.executeSaveRecord(ODatabaseDocumentTx.java:2008)
	at com.orientechnologies.orient.core.tx.OTransactionOptimistic.addRecord(OTransactionOptimistic.java:432)
	at com.orientechnologies.orient.core.tx.OTransactionOptimistic.saveRecord(OTransactionOptimistic.java:363)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.save(ODatabaseDocumentTx.java:2532)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.save(ODatabaseDocumentTx.java:121)
	at com.orientechnologies.orient.core.record.impl.ODocument.save(ODocument.java:1768)
	at com.orientechnologies.orient.core.record.impl.ODocument.save(ODocument.java:1759)
	at com.orientechnologies.orient.core.record.impl.ODocument.save(ODocument.java:81)
	at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinaryV0.recursiveLinkSave(ORecordSerializerBinaryV0.java:675)
	at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinaryV0.writeOptimizedLink(ORecordSerializerBinaryV0.java:689)
	at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinaryV0.writeSingleValue(ORecordSerializerBinaryV0.java:574)
	at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinaryV0.serialize(ORecordSerializerBinaryV0.java:260)
	at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinary.toStream(ORecordSerializerBinary.java:105)
	at com.orientechnologies.orient.core.record.impl.ODocument.toStream(ODocument.java:2285)
	at com.orientechnologies.orient.core.record.impl.ODocument.toStream(ODocument.java:671)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.executeSaveRecord(ODatabaseDocumentTx.java:1897)
	at com.orientechnologies.orient.core.tx.OTransactionOptimistic.addRecord(OTransactionOptimistic.java:432)
	at com.orientechnologies.orient.core.tx.OTransactionOptimistic.saveRecord(OTransactionOptimistic.java:363)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.save(ODatabaseDocumentTx.java:2532)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.save(ODatabaseDocumentTx.java:121)
	at com.orientechnologies.orient.core.record.impl.ODocument.save(ODocument.java:1768)
	at com.orientechnologies.orient.core.record.impl.ODocument.save(ODocument.java:1759)
	at com.orientechnologies.orient.core.record.impl.ODocument.save(ODocument.java:81)
	at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinaryV0.recursiveLinkSave(ORecordSerializerBinaryV0.java:675)
	at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinaryV0.writeOptimizedLink(ORecordSerializerBinaryV0.java:689)
	at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinaryV0.writeSingleValue(ORecordSerializerBinaryV0.java:574)
	at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinaryV0.serialize(ORecordSerializerBinaryV0.java:260)
	at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinary.toStream(ORecordSerializerBinary.java:105)
	at com.orientechnologies.orient.core.record.impl.ODocument.toStream(ODocument.java:2285)
	at com.orientechnologies.orient.core.record.impl.ODocument.toStream(ODocument.java:671)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.commitEntry(OAbstractPaginatedStorage.java:2417)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.commit(OAbstractPaginatedStorage.java:1197)
	at com.orientechnologies.orient.server.distributed.ODistributedStorage.commit(ODistributedStorage.java:953)
	at com.orientechnologies.orient.core.tx.OTransactionOptimistic.doCommit(OTransactionOptimistic.java:609)
	at com.orientechnologies.orient.core.tx.OTransactionOptimistic.commit(OTransactionOptimistic.java:156)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.commit(ODatabaseDocumentTx.java:2653)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.commit(ODatabaseDocumentTx.java:2622)
	at com.orientechnologies.orient.server.distributed.task.OTxTask.execute(OTxTask.java:131)
	at com.orientechnologies.orient.server.hazelcast.OHazelcastPlugin.executeOnLocalNode(OHazelcastPlugin.java:802)
	at com.orientechnologies.orient.server.hazelcast.ODistributedWorker.onMessage(ODistributedWorker.java:296)
	at com.orientechnologies.orient.server.hazelcast.ODistributedWorker.run(ODistributedWorker.java:119)
Caused by: java.util.ConcurrentModificationException
	at java.util.HashMap$HashIterator.nextEntry(HashMap.java:922)
	at java.util.HashMap$EntryIterator.next(HashMap.java:962)
	at java.util.HashMap$EntryIterator.next(HashMap.java:960)
	at com.orientechnologies.orient.core.db.record.ORecordLazySet$1.next(ORecordLazySet.java:96)
	at com.orientechnologies.orient.core.db.record.ORecordLazySet$1.next(ORecordLazySet.java:73)
	at com.orientechnologies.orient.core.db.record.OLazyRecordIterator.next(OLazyRecordIterator.java:68)
	at com.orientechnologies.orient.core.db.record.OLazyRecordIterator.next(OLazyRecordIterator.java:38)
	at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinaryV0.writeLinkCollection(ORecordSerializerBinaryV0.java:708)
	at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinaryV0.writeSingleValue(ORecordSerializerBinaryV0.java:568)
	at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinaryV0.serialize(ORecordSerializerBinaryV0.java:260)
	at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinary.toStream(ORecordSerializerBinary.java:105)
	at com.orientechnologies.orient.core.record.impl.ODocument.toStream(ODocument.java:2285)
	at com.orientechnologies.orient.core.record.impl.ODocument.toStream(ODocument.java:671)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.executeSaveRecord(ODatabaseDocumentTx.java:1897)
```

**Comment by tglman** [comment]
Hi @wouterv,

I reproduced it and fixed, i need some more to adapt the test case and include it in our test suite, can you try the snapshot in your development environment so we can confirm it and release?

Thank you.

**Comment by wouterv** [comment]
@tglman I can confirm this fixed our issue, thanks for the speedy fix! 
Looking forward to 2.1.6

**Comment by tglman** [comment]
great, closing.

**Comment by wouterv** [comment]
@tglman I'm curious to the code how you put this in the testsuite. Is there already a commit?

**Comment by tglman** [comment]
just pushed
