### ISSUE TITLE
Can't create user in 2.1.5

### ISSUE THREAD

**Issue by PhantomYdn** [orientechnologies/orientdb#5292]
Guys,

Sometimes during invocation of OSecurity.createUser it's possible to catch the following exception. Please pay attention to the fact that RID and RID of "duplicate" record are actually the same.

```java
com.orientechnologies.orient.core.storage.ORecordDuplicatedException: Cannot index record OUser{name:,password:{SHA-256}5994471ABB01112AFCC18159F6CC74B4F511B99806DA59B3CAF5A9C173CACFC5,status:ACTIVE,roles:[1],registered:Sat Nov 07 15:57:01 PST 2015,upgraded:false}: found duplicated key '' in index 'OUser.name' previously assigned to the record #5:323 RID=#5:323
	at com.orientechnologies.orient.core.index.OIndexTxAwareOneValue.checkEntry(OIndexTxAwareOneValue.java:224)
	at com.orientechnologies.orient.core.index.OClassIndexManager.checkIndexedPropertiesOnCreation(OClassIndexManager.java:341)
	at com.orientechnologies.orient.core.index.OClassIndexManager.checkIndexes(OClassIndexManager.java:585)
	at com.orientechnologies.orient.core.index.OClassIndexManager.onRecordBeforeCreate(OClassIndexManager.java:410)
	at com.orientechnologies.orient.core.hook.ODocumentHookAbstract.onTrigger(ODocumentHookAbstract.java:226)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.callbackHooks(ODatabaseDocumentTx.java:1037)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.executeSaveRecord(ODatabaseDocumentTx.java:1930)
	at com.orientechnologies.orient.core.tx.OTransactionNoTx.saveRecord(OTransactionNoTx.java:160)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.save(ODatabaseDocumentTx.java:2532)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.save(ODatabaseDocumentTx.java:121)
	at com.orientechnologies.orient.core.record.impl.ODocument.save(ODocument.java:1768)
	at com.orientechnologies.orient.core.record.impl.ODocument.save(ODocument.java:1764)
	at com.orientechnologies.orient.core.metadata.security.OUser.save(OUser.java:287)
	at com.orientechnologies.orient.core.metadata.security.OSecurityShared.createUser(OSecurityShared.java:228)
	at com.orientechnologies.orient.core.metadata.security.OSecurityProxy.createUser(OSecurityProxy.java:103)

```

**Comment by laa** [comment]
@PhantomYdn About message inside of exception those are not rids of duplicated and existing records. Those are rids of the same duplicated record.

But please look on 2 pieces of the message from exception above:
This one >Cannot index record OUser{**name:,**password:
And this one >found duplicated **key ''**

As you can see you create user with empty name, is it possible ?

**Comment by laa** [comment]
As additional constraint I will add minimum length of username as part of this issue, and will prohibit spaces in regexp.

**Comment by laa** [comment]
Are you sure that it is not related to https://github.com/orientechnologies/orientdb/issues/4600 ?

**Comment by laa** [comment]
pushed

**Comment by laa** [comment]
Closed because of no reply. Please free to reopen issue if you have information which I asked.
