### ISSUE TITLE
ETL duplicate key error:

### ISSUE THREAD

**Issue by lambdapilgrim** [orientechnologies/orientdb#5300]
I have a Person class, with a UNIQUE index created on the "id" property. I am using the following json for ETL process:

```
{
    "source": { "file": { "path": "/foo/bar/person.csv" } },
    "extractor": { "csv": {} },
    "transformers": [
        { "vertex": { "class": "Person", "skipDuplicates": false} }
    ],
    "loader": {
        "orientdb": {
            "dbURL": "remote:10.10.10.10/PersonDB",
            "dbType": "graph",
            "classes": [
                {"name": "Person", "extends": "V"}
            ], "indexes": [
                {"class": "Person", "fields":["id:long"], "type":"UNIQUE"}
            ]
        }
    }
}
```

But, I get the following error when I run the etl process:

```
rror in Pipeline execution: com.orientechnologies.orient.server.distributed.ODistributedException: Error on execution distributed CREATE_RECORD
ETL process halted: com.orientechnologies.orient.etl.OETLProcessHaltedException: Halt
Exception in thread "main" com.orientechnologies.orient.etl.OETLProcessHaltedException: Halt
        at com.orientechnologies.orient.etl.OETLPipeline.execute(OETLPipeline.java:149)
        at com.orientechnologies.orient.etl.OETLProcessor.executeSequentially(OETLProcessor.java:458)
        at com.orientechnologies.orient.etl.OETLProcessor.execute(OETLProcessor.java:262)
        at com.orientechnologies.orient.etl.OETLProcessor.main(OETLProcessor.java:115)
Caused by: com.orientechnologies.orient.server.distributed.ODistributedException: Error on execution distributed CREATE_RECORD
        at com.orientechnologies.orient.server.distributed.ODistributedStorage.createRecord(ODistributedStorage.java:557)
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.executeSaveRecord(ODatabaseDocumentTx.java:1899)
        at com.orientechnologies.orient.core.tx.OTransactionNoTx.saveRecord(OTransactionNoTx.java:160)
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.save(ODatabaseDocumentTx.java:2468)
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.save(ODatabaseDocumentTx.java:2309)
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.save(ODatabaseDocumentTx.java:120)
        at com.orientechnologies.orient.server.network.protocol.binary.OBinaryNetworkProtocolAbstract.createRecord(OBinaryNetworkProtocolAbstract.java:365)
        at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.createRecord(ONetworkProtocolBinary.java:1565)
        at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.executeRequest(ONetworkProtocolBinary.java:361)
        at com.orientechnologies.orient.server.network.protocol.binary.OBinaryNetworkProtocolAbstract.execute(OBinaryNetworkProtocolAbstract.java:223)
        at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:77)
Caused by: com.orientechnologies.orient.core.storage.ORecordDuplicatedException: Cannot index record Person{name:ABC XYZ ,id:1263403352}: found duplicated key '1263403352' in index 'Person.id' previously assigned to the record #12:3 RID=#12:3
        at com.orientechnologies.orient.core.index.OIndexTxAwareOneValue.checkEntry(OIndexTxAwareOneValue.java:224)
        at com.orientechnologies.orient.core.index.OClassIndexManager.checkIndexedPropertiesOnCreation(OClassIndexManager.java:341)
        at com.orientechnologies.orient.core.index.OClassIndexManager.checkIndexes(OClassIndexManager.java:585)
        at com.orientechnologies.orient.core.index.OClassIndexManager.onRecordBeforeCreate(OClassIndexManager.java:410)
        at com.orientechnologies.orient.core.hook.ODocumentHookAbstract.onTrigger(ODocumentHookAbstract.java:226)
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.callbackHooks(ODatabaseDocumentTx.java:1034)
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.executeSaveRecord(ODatabaseDocumentTx.java:1866)
        at com.orientechnologies.orient.core.tx.OTransactionNoTx.saveRecord(OTransactionNoTx.java:160)
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.save(ODatabaseDocumentTx.java:2468)
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.save(ODatabaseDocumentTx.java:120)
        at com.orientechnologies.orient.core.record.impl.ODocument.save(ODocument.java:1768)
        at com.orientechnologies.orient.core.record.impl.ODocument.save(ODocument.java:81)
        at com.orientechnologies.orient.server.distributed.task.OCreateRecordTask.execute(OCreateRecordTask.java:112)
        at com.orientechnologies.orient.server.hazelcast.OHazelcastPlugin.executeOnLocalNode(OHazelcastPlugin.java:802)
        at com.orientechnologies.orient.server.hazelcast.ODistributedWorker.onMessage(ODistributedWorker.java:296)
        at com.orientechnologies.orient.server.hazelcast.ODistributedWorker.run(ODistributedWorker.java:119)
```

Could someone please help?

**Comment by andreyvk** [comment]
The log says "Cannot index record Person{name:ABC XYZ ,id:1263403352}: found duplicated key '1263403352' in index 'Person.id' previously assigned to the record #12:3 RID=#12:3". So you probably have duplicate ids. If you dont want to enforce this, then your `Person.id` index must be `notunique`

**Comment by robfrank** [comment]
My suggestion is to upgrade your vertex transformer conf to  "skipDuplicates": true
The docs:
http://orientdb.com/docs/last/Transformer.html#vertex

Quoting:
"Vertices with duplicate keys are skipped. If skipDuplicates:true and a UNIQUE constraint is defined on vertices, the ETL will ignore the duplicate with no exceptions. Available since v2.1"

**Comment by lambdapilgrim** [comment]
@robfrank @andreyvk Thanks for the replies. I actually tried setting "skipDuplicates" conf param to true (even though the conf I pasted above has false), but no luck. Also, I read through the documentation about setting a UNIQUE constraint. It seems like setting that constraint is effectively achieved from setting a UNIQUE index, which I have set up for the "id" property on Person class.

Any other ideas?

**Comment by andreyvk** [comment]
@lambdapilgrim what is your Orient version? just double checking because `skipDuplicates` is only available since `2.1.x`

**Comment by robfrank** [comment]
which version are you using?
Are you distributed?
Can you use plocal AND then mode the db? (is faster than remote)
And, could you provide some sample data, SQL script, whatever to enable me on debugging?

**Comment by lambdapilgrim** [comment]
I'm using 2.1.4. Yes, my setup is distributed with a 3-node cluster. I am trying to upload a huge csv file of ~ 500 M records. I haven't tried using plocal yet, but that's not practical for data of this size, and also duplicates could possibly be far and few between. I will try with plocal and update you.

The CSV file is very simple - Just a long id and and a string name
id, name

**Comment by robfrank** [comment]
Did you manage the problem in some way?
