### ISSUE TITLE
develop - shutdown isn't working

### ISSUE THREAD

**Issue by robfrank** [orientechnologies/orientdb#5311]
Sending shutdown command to remote OrientDB Server instance...
nov 13, 2015 10:45:29 AM com.orientechnologies.common.log.OLogManager log
INFORMAZIONI: OrientDB auto-config DISKCACHE=988MB (heap=869MB os=3.905MB disk=218.252MB)
nov 13, 2015 10:45:29 AM com.orientechnologies.common.log.OLogManager log
INFORMAZIONI: Loading configuration from: /home/frank/projects/orientdb/distribution/target/orientdb-community-2.2.0-SNAPSHOT-distribution.dir/orientdb-community-2.2.0-SNAPSHOT/config/orientdb-server-config.xml...
Error: null

I modified OshutdownMain with a sysout:

java.io.EOFException
	at java.io.DataInputStream.readFully(DataInputStream.java:197)
	at java.io.DataInputStream.readFully(DataInputStream.java:169)
	at com.orientechnologies.orient.enterprise.channel.binary.OChannelBinary.readString(OChannelBinary.java:149)
	at com.orientechnologies.orient.server.OServerShutdownMain.connect(OServerShutdownMain.java:132)
	at com.orientechnologies.orient.server.OServerShutdownMain.main(OServerShutdownMain.java:148)
Error: null

**Comment by tglman** [comment]
Fixed the network problem, but the shutdown isn't working due to the fact that read the password from the configuration file(config/orientdb-server-config.xml), and for security reasons in recent versions the password is encrypted.

**Comment by tglman** [comment]
this was fixed by @robfrank, closing
