### ISSUE TITLE
OSchemaException: Class already exists

### ISSUE THREAD

**Issue by deelam** [orientechnologies/orientdb#5317]
Similar to #3471?
When re-opening a graph using the same URI, I get an OSchemaException even though it should be a new graph (since I deleted the data directory).  I expect the new graph to not have any EdgeTypes declared, so exception should not occur.   Workaround: Exception doesn't happen if I use a different URI when opening the second time.

My unit test:
```
    FileUtils.deleteDirectory(new File("./target/orient-us500test2"));
    OrientGraph graph = new OrientGraph("plocal:./target/orient-us500test2");
    graph.createEdgeType("hasDevice");
    graph.shutdown(true);
    
    FileUtils.deleteDirectory(new File("./target/orient-us500test2"));
    OrientGraph graph2 = new OrientGraph("plocal:./target/orient-us500test2");
    graph2.createEdgeType("hasDevice");
    graph2.shutdown();
```

```
com.orientechnologies.orient.core.exception.OSchemaException: Class hasDevice already exists in current database
	at com.orientechnologies.orient.core.metadata.schema.OSchemaShared.doCreateClass(OSchemaShared.java:980)
	at com.orientechnologies.orient.core.metadata.schema.OSchemaShared.createClass(OSchemaShared.java:415)
	at com.orientechnologies.orient.core.metadata.schema.OSchemaShared.createClass(OSchemaShared.java:400)
	at com.orientechnologies.orient.core.metadata.schema.OSchemaProxy.createClass(OSchemaProxy.java:100)
	at com.tinkerpop.blueprints.impls.orient.OrientBaseGraph$6.call(OrientBaseGraph.java:1392)
	at com.tinkerpop.blueprints.impls.orient.OrientBaseGraph$6.call(OrientBaseGraph.java:1389)
	at com.tinkerpop.blueprints.impls.orient.OrientBaseGraph.executeOutsideTx(OrientBaseGraph.java:1744)
	at com.tinkerpop.blueprints.impls.orient.OrientBaseGraph.createEdgeType(OrientBaseGraph.java:1389)
	at com.tinkerpop.blueprints.impls.orient.OrientBaseGraph.createEdgeType(OrientBaseGraph.java:1373)
	at com.tinkerpop.blueprints.impls.orient.OrientBaseGraph.createEdgeType(OrientBaseGraph.java:1358)
```

**Comment by lvca** [comment]
Storage is never closed. Try calling this before the file delete: 

    graph.getRawGraph().getStorage().close(true, false);

**Comment by deelam** [comment]
Your suggestion works.  But this should be handled when I call graph.shutdown().
