### ISSUE TITLE
error export and importing a database that contains lucene indices

### ISSUE THREAD

**Issue by arisAlexis** [orientechnologies/orientdb#5339]
export database was OK.

import database got this error which is very important because the database was left unusable and I needed to delete and recreate it (thank god I had the console commands saved in a txt file and scripts to recreate it). Otherwise import fails. This is dangerous for putting into production. 

Post.body is a lucene fulltext index.

The exported file shows this line in it:

{"name":"Post.body","type":"FULLTEXT","algorithm":"LUCENE","clustersToIndex":["post"],"definition":{"defClass":"com.orientechnologies.orient.core.index.OPropertyIndexDefinition"}

this is the error:

Rebuilding indexes of truncated clusters ...Error on database import happened just before line 0, column 898
com.orientechnologies.orient.core.exception.OCommandExecutionException: Index 'Post.body' not found
        at com.orientechnologies.orient.core.sql.OCommandExecutorSQLRebuildIndex.execute(OCommandExecutorSQLRebuildIndex.java:89)
        at com.orientechnologies.orient.core.sql.OCommandExecutorSQLDelegate.execute(OCommandExecutorSQLDelegate.java:90)
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.executeCommand(OAbstractPaginatedStorage.java:1452)
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.command(OAbstractPaginatedStorage.java:1433)
        at com.orientechnologies.orient.core.command.OCommandRequestTextAbstract.execute(OCommandRequestTextAbstract.java:63)
        at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.command(ONetworkProtocolBinary.java:1319)
        at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.executeRequest(ONetworkProtocolBinary.java:396)
        at com.orientechnologies.orient.server.network.protocol.binary.OBinaryNetworkProtocolAbstract.execute(OBinaryNetworkProtocolAbstract.java:223)
        at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:77)

Error: com.orientechnologies.orient.core.db.tool.ODatabaseExportException: Error on importing database 'social' from file: /home/arisalexis/test.export

Error: com.orientechnologies.orient.core.exception.OCommandExecutionException: Index 'Post.body' not found

**Comment by maggiolo00** [comment]
hi @arisAlexis 

which version of OrientDB?

can you send me the exported database or 
some script in order to reproduce the issue?

Thanks

**Comment by arisAlexis** [comment]
version is 2.1.4 I sent you in email the data.

**Comment by arisAlexis** [comment]
I am sorry. It's not clear that opening the console and doing things while the server is running would cause this. it imports correctly now.

**Comment by arisAlexis** [comment]
pinning down the problem, the import doesn't work (with the error given) when connected as remote with a server running.

**Comment by maggiolo00** [comment]
@arisAlexis 

the problem happens with remote right?

In plocal we have a test that check import/export with lucene
https://github.com/orientechnologies/orientdb/blob/2.1.x/lucene/src/test/java/com/orientechnologies/lucene/test/LuceneExportImportTest.java

I will try with remote.

**Comment by arisAlexis** [comment]
yes without the server running and plocal it imports correctly.

**Comment by arisAlexis** [comment]
Further testing:

I create from the studio a new database. I connect from the console.sh with remote. I import the file. it works OK. Again I import the same file, it produces the error message.

this is a good test case I think unless two consecutive imports should not happen but only in a clean new database? maybe I misread the docs.

**Comment by robfrank** [comment]
should be fixed, closing
