### ISSUE TITLE
second node in a cluster does not get started

### ISSUE THREAD

**Issue by mohamnag** [orientechnologies/orientdb#5340]
As mentioned in #5338, I'm dealing with moving an existing cluster from v2.0.15 to v2.1.5. 

After I setup the first node of v2.1.5, I'm trying to run the second node but with no success. The problem is that I get following errors (sslc is the name of database and sslc-db-backup-1 is the name of first node whereas sslc-db-1 is name of new node):

```
2015-11-17 16:24:29:781 WARNI [sslc-db-1]->[[sslc-db-backup-1]] requesting deploy of database 'sslc' on local server... [OHazelcastPlugin]
2015-11-17 16:24:29:835 WARNI [sslc-db-1] moving existent database 'sslc' located in '/opt/orientdb/databases/sslc' to '/opt/orientdb/databases/../backup/databases/sslc' and get a fresh copy from a remote node... [OHazelcastPlugin]
2015-11-17 16:24:29:835 SEVER [sslc-db-1] error on moving existent database 'sslc' located in '/opt/orientdb/databases/sslc' to '/opt/orientdb/databases/../backup/databases/sslc'. Try to move the database directory manually and retry [OHazelcastPlugin][sslc-db-1] Error on starting distributed plugin
com.orientechnologies.orient.server.distributed.ODistributedException: Error on moving existent database 'sslc' located in '/opt/orientdb/databases/sslc' to '/opt/orientdb/databases/../backup/databases/sslc'. Try to move the database directory manually and retry
	at com.orientechnologies.orient.server.hazelcast.OHazelcastPlugin.backupCurrentDatabase(OHazelcastPlugin.java:1007)
	at com.orientechnologies.orient.server.hazelcast.OHazelcastPlugin.requestDatabase(OHazelcastPlugin.java:954)
	at com.orientechnologies.orient.server.hazelcast.OHazelcastPlugin.installDatabase(OHazelcastPlugin.java:893)
	at com.orientechnologies.orient.server.hazelcast.OHazelcastPlugin.installNewDatabases(OHazelcastPlugin.java:1448)
	at com.orientechnologies.orient.server.hazelcast.OHazelcastPlugin.startup(OHazelcastPlugin.java:185)
	at com.orientechnologies.orient.server.OServer.registerPlugins(OServer.java:979)
	at com.orientechnologies.orient.server.OServer.activate(OServer.java:346)
	at com.orientechnologies.orient.server.OServerMain.main(OServerMain.java:41)
```

first of all, I have no idea why moving database to backup dir fails!! directory exists and is writable for the whole world.

second I double check the "existing" directory before starting the server and it is totally empty. but just after starting the server, the directory contains a file named `distributed-config.json` it seems to me that the start script creates this file itself and then it can not accept it.

**Comment by mohamnag** [comment]
before starting the server I made sure that `/opt/orientdb/databases/` is completely empty (so there is no database). But it seems that server creates that database and put one config file inside it. Afterwards it tries to move that file which has been created by himself.

OrientDB is running with root permissions so there should be no reason why it shall not be able to move files or create new directories.

Here comes the full log from the moment server starts until it shuts down because of the problem:
```
           .                                          
          .`        `                                 
          ,      `:.                                  
         `,`    ,:`                                   
         .,.   :,,                                    
         .,,  ,,,                                     
    .    .,.:::::  ````                                 :::::::::     :::::::::   
    ,`   .::,,,,::.,,,,,,`;;                      .:    ::::::::::    :::    :::  
    `,.  ::,,,,,,,:.,,.`  `                       .:    :::      :::  :::     ::: 
     ,,:,:,,,,,,,,::.   `        `         ``     .:    :::      :::  :::     ::: 
      ,,:.,,,,,,,,,: `::, ,,   ::,::`   : :,::`  ::::   :::      :::  :::    :::  
       ,:,,,,,,,,,,::,:   ,,  :.    :   ::    :   .:    :::      :::  :::::::     
        :,,,,,,,,,,:,::   ,,  :      :  :     :   .:    :::      :::  :::::::::   
  `     :,,,,,,,,,,:,::,  ,, .::::::::  :     :   .:    :::      :::  :::     ::: 
  `,...,,:,,,,,,,,,: .:,. ,, ,,         :     :   .:    :::      :::  :::     ::: 
    .,,,,::,,,,,,,:  `: , ,,  :     `   :     :   .:    :::      :::  :::     ::: 
      ...,::,,,,::.. `:  .,,  :,    :   :     :   .:    :::::::::::   :::     ::: 
           ,::::,,,. `:   ,,   :::::    :     :   .:    :::::::::     ::::::::::  
           ,,:` `,,.                                  
          ,,,    .,`                                  
         ,,.     `,                                          GRAPH DATABASE  
       ``        `.                                                          
                 ``                                          orientdb.com
                 `                                    

2015-11-18 08:11:08:595 INFO  Loading configuration from: /opt/orientdb/config/orientdb-server-config.xml... [OServerConfigurationLoaderXml]
2015-11-18 08:11:19:460 WARNI [sslc-db-backup-1] updated distributed configuration for database: sslc:
----------
{
  "version": 5,
  "autoDeploy": true,
  "hotAlignment": false,
  "executionMode": "undefined",
  "readQuorum": 1,
  "writeQuorum": 1,
  "failureAvailableNodesLessQuorum": false,
  "readYourWrites": true,"clusters":{
    "internal": {
},
    "index": {
},
    "*": {
  "servers": ["sslc-db-1","<NEW_NODE>"]
}
    }
}
---------- [OHazelcastPlugin]
2015-11-18 08:11:19:470 WARNI [sslc-db-backup-1] updated distributed configuration for database: sslc:
----------
{
  "version": 6,
  "autoDeploy": true,
  "hotAlignment": false,
  "executionMode": "undefined",
  "readQuorum": 1,
  "writeQuorum": 1,
  "failureAvailableNodesLessQuorum": false,
  "readYourWrites": true,"clusters":{
    "internal": {
},
    "index": {
},
    "*": {
  "servers": ["sslc-db-1","sslc-db-backup-1","<NEW_NODE>"]
}
    }
}
---------- [OHazelcastPlugin]
2015-11-18 08:11:19:489 WARNI [sslc-db-backup-1]->[[sslc-db-1]] requesting deploy of database 'sslc' on local server... [OHazelcastPlugin]
2015-11-18 08:11:19:589 WARNI [sslc-db-backup-1] moving existent database 'sslc' located in '/opt/orientdb/databases/sslc' to '/opt/orientdb/databases/../backup/databases/sslc' and get a fresh copy from a remote node... [OHazelcastPlugin]
2015-11-18 08:11:19:589 SEVER [sslc-db-backup-1] error on moving existent database 'sslc' located in '/opt/orientdb/databases/sslc' to '/opt/orientdb/databases/../backup/databases/sslc'. Try to move the database directory manually and retry [OHazelcastPlugin][sslc-db-backup-1] Error on starting distributed plugin
com.orientechnologies.orient.server.distributed.ODistributedException: Error on moving existent database 'sslc' located in '/opt/orientdb/databases/sslc' to '/opt/orientdb/databases/../backup/databases/sslc'. Try to move the database directory manually and retry
	at com.orientechnologies.orient.server.hazelcast.OHazelcastPlugin.backupCurrentDatabase(OHazelcastPlugin.java:1007)
	at com.orientechnologies.orient.server.hazelcast.OHazelcastPlugin.requestDatabase(OHazelcastPlugin.java:954)
	at com.orientechnologies.orient.server.hazelcast.OHazelcastPlugin.installDatabase(OHazelcastPlugin.java:893)
	at com.orientechnologies.orient.server.hazelcast.OHazelcastPlugin.installNewDatabases(OHazelcastPlugin.java:1448)
	at com.orientechnologies.orient.server.hazelcast.OHazelcastPlugin.startup(OHazelcastPlugin.java:185)
	at com.orientechnologies.orient.server.OServer.registerPlugins(OServer.java:979)
	at com.orientechnologies.orient.server.OServer.activate(OServer.java:346)
	at com.orientechnologies.orient.server.OServerMain.main(OServerMain.java:41)

```

**Comment by lvca** [comment]
Could you try creating directory `/opt/orientdb/backup/databases/`before starting?

**Comment by mohamnag** [comment]
yes the directory also exists and writable for anybody

**Comment by lvca** [comment]
Are you using docker? 

However, you can also use another directory by setting this config at startup in bin/server.sh script. Example: -Ddistributed.backupDirectory=/tmp (default is "../backup/databases").

**Comment by mohamnag** [comment]
yes as also mentioned on #5338, this is the image I'm using:  github.com/mohamnag/ecs-orientdb

I tried to also change the backup dir but no success.

**Comment by mohamnag** [comment]
this image can only be used on an EC2 instance due to the auto-discovery functionality.

**Comment by lvca** [comment]
This has been fixed in 2.1.6 by setting `-Ddistributed.backupDirectory=""` that means no backup.

**Comment by mohamnag** [comment]
I can confirm that it is not stuck in that step, however it does not seem that the second node ever comes online. The last lines of logs after updating DB config are:
```
---------- [OHazelcastPlugin]
2015-11-27 08:32:38:199 WARNI [sslc-db-backup-1]->[[sslc-db-1]] requesting deploy of database 'sslc' on local server... [OHazelcastPlugin]
2015-11-27 08:32:38:991 WARNI [sslc-db-backup-1] moving existent database 'sslc' located in '/opt/orientdb/databases/sslc' to '/opt/orientdb/databases/""/sslc' and get a fresh copy from a remote node... [OHazelcastPlugin]
2015-11-27 08:32:38:994 WARNI [sslc-db-backup-1]<-[sslc-db-1] installing database 'sslc' to: /opt/orientdb/databases/sslc... [OHazelcastPlugin]
2015-11-27 08:32:39:006 WARNI [sslc-db-backup-1] - writing chunk #1 offset=0 size=315.99KB [OHazelcastPlugin]
```

and it is stuck there like since 3 hours. Do you use any additional ports for this task? I have ports 2424, 2480 and 5701 open on both machines on which first and second node are running.

**Comment by lvca** [comment]
Hi, seems it can't write the first chunk on disk. This should take few milliseconds. Again it seems a configuration problem. I think you should double check the permissions of that folder in relation with OrientDB user.

**Comment by mohamnag** [comment]
Ok it seems that the write is successful and the node does come online, however it is not visible in logs just afterwards. I think this ticket can be closed.

**Comment by lvca** [comment]
Cool, thanks.
