### ISSUE TITLE
ETL Merge transformer in not working

### ISSUE THREAD

**Issue by apiy72** [orientechnologies/orientdb#5341]
Hi,

I am trying to update vertices using merge transformer.
I can see the merge transformer is able find the vertex as it is executing the following line:

log(OETLProcessor.LOG_LEVELS.DEBUG, "joinValue=%s, lookupResult=%s", joinValue, result);
but it gets into the following if condition and results in either nothing or error depending on the unresolvedLinkAction value:  
 if (result == null || OMultiValue.getSize(result) == 0) 

The issue is if it is able to find the vertex why above condition is returning true which is not resulting in update to the vertex.

I have pasted the log and the configuration file below:

Thanks for looking into it.

Piyush
LOG:
====
OrientDB etl v.2.1.4 (build @BUILD@) www.orientdb.com
BEGIN ETL PROCESSOR
[orientdb] DEBUG orientdb: found 4 vertices in class 'null'
[orientdb] DEBUG orientdb: found metadata field 'null'
[1:merge] DEBUG Transformer input: customer{accountID:10013550500_,lastName:Murphy3,firstName:William}
[1:merge] DEBUG joinValue=10013550500_, lookupResult=customer#12:2{accountID:10013550500_,lastName:Murphy2,firstName:William} v1
Pipeline execution halted
ETL process halted: com.orientechnologies.orient.etl.OETLProcessHaltedException: [Merge transformer] Cannot resolve join for value '10013550500_'
Exception in thread "main" com.orientechnologies.orient.etl.OETLProcessHaltedException: [Merge transformer] Cannot resolve join for value '10013550500_'
        at com.orientechnologies.orient.etl.transformer.OMergeTransformer.executeTransform(OMergeTransformer.java:68)
        at com.orientechnologies.orient.etl.transformer.OAbstractTransformer.transform(OAbstractTransformer.java:37)
        at com.orientechnologies.orient.etl.OETLPipeline.execute(OETLPipeline.java:115)
        at com.orientechnologies.orient.etl.OETLProcessor.executeSequentially(OETLProcessor.java:458)
        at com.orientechnologies.orient.etl.OETLProcessor.execute(OETLProcessor.java:262)
        at com.orientechnologies.orient.etl.OETLProcessor.main(OETLProcessor.java:115)

CONFIGURATION:
=================== 

{
"config": {
    "log": "debug"},
  "extractor" : {
    "jdbc": { "driver": "com.mysql.jdbc.Driver",
              "url": "jdbc:mysql://localhost:3306/foodmart?useOldAliasMetadataBehavior=true",
              "userName": "root",
              "userPassword": "wordpass",
              "query": "SELECT 'customer' as `@class`,concat(cast(account_num as char),'_') as accountID,concat(lname,'3') as lastName,fname as firstName FROM foodmart.customer as customer order by 2 limit 2" }
  },
  "transformers" : [
  { "merge": {"joinFieldName":"accountID","lookup":"customer.accountID","unresolvedLinkAction":"HALT"}}
  ],
  "loader" : {
    "orientdb": {
      "dbURL": "remote:localhost/test",
	  "dbUser":"admin",
	  "dbPassword":"admin",
	  "dbAutoDropIfExists":false,
      "dbAutoCreate": true,
	  "dbType": "graph",
	  "tx":false,
	  "classes": [{"name": "customer", "extends":"V"}],
	  "indexes": [{"class":"customer", "fields":["accountID:string"], "type":"UNIQUE" }]
	  
	  
    }
  }
}

OrientDB etl v.2.1.4 (build @BUILD@) www.orientdb.com
BEGIN ETL PROCESSOR
[orientdb] DEBUG orientdb: found 4 vertices in class 'null'
[orientdb] DEBUG orientdb: found metadata field 'null'
[1:merge] DEBUG Transformer input: customer{accountID:10013550500_,lastName:Murphy3,firstName:William}
[1:merge] DEBUG joinValue=10013550500_, lookupResult=customer#12:2{accountID:10013550500_,lastName:Murphy2,firstName:William} v1
Pipeline execution halted
ETL process halted: com.orientechnologies.orient.etl.OETLProcessHaltedException: [Merge transformer] Cannot resolve join for value '10013550500_'
Exception in thread "main" com.orientechnologies.orient.etl.OETLProcessHaltedException: [Merge transformer] Cannot resolve join for value '10013550500_'
        at com.orientechnologies.orient.etl.transformer.OMergeTransformer.executeTransform(OMergeTransformer.java:68)
        at com.orientechnologies.orient.etl.transformer.OAbstractTransformer.transform(OAbstractTransformer.java:37)
        at com.orientechnologies.orient.etl.OETLPipeline.execute(OETLPipeline.java:115)
        at com.orientechnologies.orient.etl.OETLProcessor.executeSequentially(OETLProcessor.java:458)
        at com.orientechnologies.orient.etl.OETLProcessor.execute(OETLProcessor.java:262)
        at com.orientechnologies.orient.etl.OETLProcessor.main(OETLProcessor.java:115)

**Comment by robfrank** [comment]
I've fixed the problem with the merge Transformer. It will be on next 2.1.7 hot fixe and 2.2.
Thank you for reporting
