### ISSUE TITLE
orientdb 2.0.16 exception with java 1.7

### ISSUE THREAD

**Issue by adridcode** [orientechnologies/orientdb#5376]
After a clean installation of orientdb 2.0.16 I get a lot of this exception when I launch the studio:
```shell
java.lang.NoSuchMethodError: java.util.Map.putIfAbsent(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;
        at com.orientechnologies.common.profiler.OProfiler.updateCounter(OProfiler.java:138)
        at com.orientechnologies.orient.server.network.protocol.http.ONetworkProtocolHttpAbstract.connectionClosed(ONetworkProtocolHttpAbstract.java:655)
        at com.orientechnologies.orient.server.network.protocol.http.ONetworkProtocolHttpAbstract.execute(ONetworkProtocolHttpAbstract.java:516)
        at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:69)
java.lang.NoSuchMethodError: java.util.Map.putIfAbsent(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;
        at com.orientechnologies.common.profiler.OProfiler.updateCounter(OProfiler.java:138)
        at com.orientechnologies.orient.server.network.protocol.http.ONetworkProtocolHttpAbstract.connectionClosed(ONetworkProtocolHttpAbstract.java:655)
        at com.orientechnologies.orient.server.network.protocol.http.ONetworkProtocolHttpAbstract.execute(ONetworkProtocolHttpAbstract.java:516)
        at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:69)
java.lang.NoSuchMethodError: java.util.Map.putIfAbsent(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;
        at com.orientechnologies.common.profiler.OProfiler.updateCounter(OProfiler.java:138)
        at com.orientechnologies.orient.server.network.protocol.http.ONetworkProtocolHttpAbstract.connectionClosed(ONetworkProtocolHttpAbstract.java:655)
        at com.orientechnologies.orient.server.network.protocol.http.ONetworkProtocolHttpAbstract.execute(ONetworkProtocolHttpAbstract.java:516)
        at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:69)
java.lang.NoSuchMethodError: java.util.Map.putIfAbsent(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;
        at com.orientechnologies.common.profiler.OProfiler.updateCounter(OProfiler.java:138)
        at com.orientechnologies.orient.server.network.protocol.http.ONetworkProtocolHttpAbstract.connectionClosed(ONetworkProtocolHttpAbstract.java:655)
        at com.orientechnologies.orient.server.network.protocol.http.ONetworkProtocolHttpAbstract.execute(ONetworkProtocolHttpAbstract.java:516)
        at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:69)
```

I can't reproduce it after a clean install of orientdb 2.0.15

Step to reproduce:
- Untar orientdb-community-2.0.16.tar.gz(downloaded from website)
- run bin/server.sh
- browse the studio home page

The exception appear when the studio homepage is loading

It seems that the 2.0.16 version now require java 1.8(I'm on 1.7).

**Comment by guglielmomoretti** [comment]
Happened the same to me. The method *putIfAbsent* of the Map interface has been introduced since java 1.8. So yes, I think it is no more compatible.

**Comment by robfrank** [comment]
I've just fixed the bug on 2.1.x branch and develop. On 2.1x this is the commit: https://github.com/orientechnologies/orientdb/commit/c1b0b302f668e16b34e42b062efb67b198577a18

maybe you can cherry-pick this commit?

I think we will release a 2.1.7 ASAP

**Comment by adridcode** [comment]
Thank you,

I've already upgraded to java 1.8.

I don't know if this need a separated issue, but I experienced some problems with the java upgrade related to my server side javascript functions.

Since java 1.8, java use nashorn instead of rhino for the javascript interpreter and there is some compatibility issue and code syntax change between both.

Maybe you could had a warning in the documentation or the upgrade note because it is not easy to figure that the java upgrade can impact the javascript functions.

**Comment by robfrank** [comment]
Thank you for the point. We will take care to update docs about JS
