### ISSUE TITLE
NPE during tests

### ISSUE THREAD

**Issue by lvca** [orientechnologies/orientdb#5418]
```
2015-12-03 19:54:03:504 INFO  - closing storage: demo... [Orient]Error during orient shutdown.
java.lang.NullPointerException
	at com.orientechnologies.common.concur.lock.OReadersWriterSpinLock.acquireWriteLock(OReadersWriterSpinLock.java:112)
	at com.orientechnologies.orient.client.remote.OStorageRemote.close(OStorageRemote.java:292)
	at com.orientechnologies.orient.core.storage.OStorageAbstract.close(OStorageAbstract.java:124)
	at com.orientechnologies.orient.client.remote.OStorageRemoteThread.close(OStorageRemoteThread.java:188)
	at com.orientechnologies.orient.core.db.OPartitionedDatabasePool.close(OPartitionedDatabasePool.java:373)
	at com.orientechnologies.orient.core.db.OPartitionedDatabasePool.onShutdown(OPartitionedDatabasePool.java:349)
	at com.orientechnologies.orient.core.Orient.shutdown(Orient.java:312)
	at com.orientechnologies.orient.server.OServer.shutdown(OServer.java:437)
	at com.orientechnologies.orient.test.database.auto.RunServerTest.after(RunServerTest.java:25)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:564)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:213)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:138)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:322)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:293)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:84)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:91)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:200)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)

2015-12-03 19:54:03:838 INFO  OrientDB Engine shutdown complete [Orient]
2015-12-03 19:54:03:839 INFO  OrientDB Server shutdown complete [OServer]Tests run: 1434, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 83.353 sec - in TestSuite

```

**Comment by laa** [comment]
Fixed by https://github.com/orientechnologies/orientdb/commit/1d82106d6830f4ee91f7840fbab3587b8501fb00
