### ISSUE TITLE
Cannot rejoin cluster on 2.1.6

### ISSUE THREAD

**Issue by mriehl** [orientechnologies/orientdb#5420]
We are running 3 orientdb servers, server01, server02 and server03.

Due to an OOM that killed the server process, server01 needs to rejoin the cluster, but the distributed plugin fails to initialize although we have `"failureAvailableNodesLessQuorum": false`.
Note that server02 and server03 are still working well.

Here's the log from server01 start:

```

2015-12-04 08:17:04:228 WARNI Name of the hazelcast schema location incorrect using default [AbstractXmlConfigHelper]
2015-12-04 08:17:04:700 WARNI Distributed server is not yet ONLINE (status=STARTING), reject incoming connection from /10.33.255.245:52782. If you are trying to shutdown the server, please kill the process [OServerNetworkListener]
2015-12-04 08:17:11:693 WARNI Distributed server is not yet ONLINE (status=STARTING), reject incoming connection from /10.73.255.246:55550. If you are trying to shutdown the server, please kill the process [OServerNetworkListener]
2015-12-04 08:17:12:429 WARNI Distributed server is not yet ONLINE (status=STARTING), reject incoming connection from /10.33.255.246:33768. If you are trying to shutdown the server, please kill the process [OServerNetworkListener]
2015-12-04 08:17:13:284 WARNI [server01] updated distributed configuration for database: db:
----------
{
  "version": 94,
  "autoDeploy": true,
  "hotAlignment": false,
  "executionMode": "undefined",
  "readQuorum": 1,
  "writeQuorum": 2,
  "failureAvailableNodesLessQuorum": false,
  "readYourWrites": true,
  "servers": {
    "*": "master"
  },
  "clusters": {
    "internal": {
    },
    "index": {
    },
    "*": {
      "servers": ["server03","server02","<NEW_NODE>"]
    },
    "e_server03": {
      "servers": ["server03","server02","<NEW_NODE>"]
    },
    "orids_server03": {
      "servers": ["server03","server02","<NEW_NODE>"]
    },
    "ouser_server03": {
      "servers": ["server03","server02","<NEW_NODE>"]
    },
    "oschedule_server03": {
      "servers": ["server03","server02","<NEW_NODE>"]
    },
    "orole_server03": {
      "servers": ["server03","server02","<NEW_NODE>"]
    },
    "v_server03": {
      "servers": ["server03","server02","<NEW_NODE>"]
    },
    "ofunction_server03": {
      "servers": ["server03","server02","<NEW_NODE>"]
    },
    "ouser_server02": {
      "servers": ["server02","server03","<NEW_NODE>"]
    },
    "oschedule_server02": {
      "servers": ["server02","server03","<NEW_NODE>"]
    },
    "orole_server02": {
      "servers": ["server02","server03","<NEW_NODE>"]
    },
    "orids_server02": {
      "servers": ["server02","server03","<NEW_NODE>"]
    },
    "e_server02": {
      "servers": ["server02","server03","<NEW_NODE>"]
    },
    "v_server02": {
      "servers": ["server02","server03","<NEW_NODE>"]
    },
    "ofunction_server02": {
      "servers": ["server02","server03","<NEW_NODE>"]
    },
    "schemalock_server02": {
      "servers": ["server02","server03","<NEW_NODE>"]
    },
    "schemalock_server03": {
      "servers": ["server03","server02","<NEW_NODE>"]
    },
    "schemaversion_server02": {
      "servers": ["server02","server03","<NEW_NODE>"]
    },
    "schemaversion_server03": {
      "servers": ["server03","server02","<NEW_NODE>"]
    },
    "request_server02": {
      "servers": ["server02","server03","<NEW_NODE>"]
    },
    "request_server03": {
      "servers": ["server03","server02","<NEW_NODE>"]
    },
    "rg_server02": {
      "servers": ["server02","server03","<NEW_NODE>"]
    },
    "rg_server03": {
      "servers": ["server03","server02","<NEW_NODE>"]
    },
    "user_server02": {
      "servers": ["server02","server03","<NEW_NODE>"]
    },
    "user_server03": {
      "servers": ["server03","server02","<NEW_NODE>"]
    },
    "fp_server02": {
      "servers": ["server02","server03","<NEW_NODE>"]
    },
    "fp_server03": {
      "servers": ["server03","server02","<NEW_NODE>"]
    },
    "edge1_server02": {
      "servers": ["server02","server03","<NEW_NODE>"]
    },
    "edge1_server03": {
      "servers": ["server03","server02","<NEW_NODE>"]
    },
    "hasfp_server02": {
      "servers": ["server02","server03","<NEW_NODE>"]
    },
    "hasfp_server03": {
      "servers": ["server03","server02","<NEW_NODE>"]
    },
    "lia_server02": {
      "servers": ["server02","server03","<NEW_NODE>"]
    },
    "lia_server03": {
      "servers": ["server03","server02","<NEW_NODE>"]
    },
    "_studio_server02": {
      "servers": ["server02","server03","<NEW_NODE>"]
    },
    "_studio_server03": {
      "servers": ["server03","server02","<NEW_NODE>"]
    },
    "fp_server01": {
      "servers": ["server03","server02","<NEW_NODE>"]
    },
    "hasfp_server01": {
      "servers": ["server03","server02","<NEW_NODE>"]
    },
    "orole_server01": {
      "servers": ["server03","server02","<NEW_NODE>"]
    },
    "lia_server01": {
      "servers": ["server03","server02","<NEW_NODE>"]
    },
    "schemalock_server01": {
      "servers": ["server03","server02","<NEW_NODE>"]
    },
    "oschedule_server01": {
      "servers": ["server03","server02","<NEW_NODE>"]
    },
    "user_server01": {
      "servers": ["server03","server02","<NEW_NODE>"]
    },
    "request_server01": {
      "servers": ["server03","server02","<NEW_NODE>"]
    },
    "e_server01": {
      "servers": ["server03","server02","<NEW_NODE>"]
    },
    "rg_server01": {
      "servers": ["server03","server02","<NEW_NODE>"]
    },
    "ouser_server01": {
      "servers": ["server03","server02","<NEW_NODE>"]
    },
    "v_server01": {
      "servers": ["server03","server02","<NEW_NODE>"]
    },
    "schemaversion_server01": {
      "servers": ["server03","server02","<NEW_NODE>"]
    },
    "orids_server01": {
      "servers": ["server03","server02","<NEW_NODE>"]
    },
    "edge1_server01": {
      "servers": ["server03","server02","<NEW_NODE>"]
    },
    "_studio_server01": {
      "servers": ["server03","server02","<NEW_NODE>"]
    },
    "ofunction_server01": {
      "servers": ["server03","server02","<NEW_NODE>"]
    }
  }
}
---------- [OHazelcastPlugin]
2015-12-04 08:17:13:291 WARNI [server01] changing mastership of cluster 'fp_server01' from node 'server03' to 'server01' [OHazelcastDistributedDatabase]
2015-12-04 08:17:13:291 WARNI [server01] changing mastership of cluster 'hasfp_server01' from node 'server03' to 'server01' [OHazelcastDistributedDatabase]
2015-12-04 08:17:13:292 WARNI [server01] changing mastership of cluster 'orole_server01' from node 'server03' to 'server01' [OHazelcastDistributedDatabase]
2015-12-04 08:17:13:292 WARNI [server01] changing mastership of cluster 'lia_server01' from node 'server03' to 'server01' [OHazelcastDistributedDatabase]
2015-12-04 08:17:13:292 WARNI [server01] changing mastership of cluster 'schemalock_server01' from node 'server03' to 'server01' [OHazelcastDistributedDatabase]
2015-12-04 08:17:13:293 WARNI [server01] changing mastership of cluster 'oschedule_server01' from node 'server03' to 'server01' [OHazelcastDistributedDatabase]
2015-12-04 08:17:13:293 WARNI [server01] changing mastership of cluster 'user_server01' from node 'server03' to 'server01' [OHazelcastDistributedDatabase]
2015-12-04 08:17:13:293 WARNI [server01] changing mastership of cluster 'request_server01' from node 'server03' to 'server01' [OHazelcastDistributedDatabase]
2015-12-04 08:17:13:293 WARNI [server01] changing mastership of cluster 'e_server01' from node 'server03' to 'server01' [OHazelcastDistributedDatabase]
2015-12-04 08:17:13:294 WARNI [server01] changing mastership of cluster 'rg_server01' from node 'server03' to 'server01' [OHazelcastDistributedDatabase]
2015-12-04 08:17:13:294 WARNI [server01] changing mastership of cluster 'ouser_server01' from node 'server03' to 'server01' [OHazelcastDistributedDatabase]
2015-12-04 08:17:13:294 WARNI [server01] changing mastership of cluster 'v_server01' from node 'server03' to 'server01' [OHazelcastDistributedDatabase]
2015-12-04 08:17:13:295 WARNI [server01] changing mastership of cluster 'schemaversion_server01' from node 'server03' to 'server01' [OHazelcastDistributedDatabase]
2015-12-04 08:17:13:295 WARNI [server01] changing mastership of cluster 'orids_server01' from node 'server03' to 'server01' [OHazelcastDistributedDatabase]
2015-12-04 08:17:13:295 WARNI [server01] changing mastership of cluster 'edge1_server01' from node 'server03' to 'server01' [OHazelcastDistributedDatabase]
2015-12-04 08:17:13:295 WARNI [server01] changing mastership of cluster '_studio_server01' from node 'server03' to 'server01' [OHazelcastDistributedDatabase]
2015-12-04 08:17:13:296 WARNI [server01] changing mastership of cluster 'ofunction_server01' from node 'server03' to 'server01' [OHazelcastDistributedDatabase]
2015-12-04 08:17:13:302 WARNI [server01] updated distributed configuration for database: db:
----------
{
  "version": 112,
  "autoDeploy": true,
  "hotAlignment": false,
  "executionMode": "undefined",
  "readQuorum": 1,
  "writeQuorum": 2,
  "failureAvailableNodesLessQuorum": false,
  "readYourWrites": true,
  "servers": {
    "*": "master"
  },
  "clusters": {
    "internal": {
    },
    "index": {
    },
    "*": {
      "servers": ["server03","server02","server01","<NEW_NODE>"]
    },
    "e_server03": {
      "servers": ["server03","server02","server01","<NEW_NODE>"]
    },
    "orids_server03": {
      "servers": ["server03","server02","server01","<NEW_NODE>"]
    },
    "ouser_server03": {
      "servers": ["server03","server02","server01","<NEW_NODE>"]
    },
    "oschedule_server03": {
      "servers": ["server03","server02","server01","<NEW_NODE>"]
    },
    "orole_server03": {
      "servers": ["server03","server02","server01","<NEW_NODE>"]
    },
    "v_server03": {
      "servers": ["server03","server02","server01","<NEW_NODE>"]
    },
    "ofunction_server03": {
      "servers": ["server03","server02","server01","<NEW_NODE>"]
    },
    "ouser_server02": {
      "servers": ["server02","server03","server01","<NEW_NODE>"]
    },
    "oschedule_server02": {
      "servers": ["server02","server03","server01","<NEW_NODE>"]
    },
    "orole_server02": {
      "servers": ["server02","server03","server01","<NEW_NODE>"]
    },
    "orids_server02": {
      "servers": ["server02","server03","server01","<NEW_NODE>"]
    },
    "e_server02": {
      "servers": ["server02","server03","server01","<NEW_NODE>"]
    },
    "v_server02": {
      "servers": ["server02","server03","server01","<NEW_NODE>"]
    },
    "ofunction_server02": {
      "servers": ["server02","server03","server01","<NEW_NODE>"]
    },
    "schemalock_server02": {
      "servers": ["server02","server03","server01","<NEW_NODE>"]
    },
    "schemalock_server03": {
      "servers": ["server03","server02","server01","<NEW_NODE>"]
    },
    "schemaversion_server02": {
      "servers": ["server02","server03","server01","<NEW_NODE>"]
    },
    "schemaversion_server03": {
      "servers": ["server03","server02","server01","<NEW_NODE>"]
    },
    "request_server02": {
      "servers": ["server02","server03","server01","<NEW_NODE>"]
    },
    "request_server03": {
      "servers": ["server03","server02","server01","<NEW_NODE>"]
    },
    "rg_server02": {
      "servers": ["server02","server03","server01","<NEW_NODE>"]
    },
    "rg_server03": {
      "servers": ["server03","server02","server01","<NEW_NODE>"]
    },
    "user_server02": {
      "servers": ["server02","server03","server01","<NEW_NODE>"]
    },
    "user_server03": {
      "servers": ["server03","server02","server01","<NEW_NODE>"]
    },
    "fp_server02": {
      "servers": ["server02","server03","server01","<NEW_NODE>"]
    },
    "fp_server03": {
      "servers": ["server03","server02","server01","<NEW_NODE>"]
    },
    "edge1_server02": {
      "servers": ["server02","server03","server01","<NEW_NODE>"]
    },
    "edge1_server03": {
      "servers": ["server03","server02","server01","<NEW_NODE>"]
    },
    "hasfp_server02": {
      "servers": ["server02","server03","server01","<NEW_NODE>"]
    },
    "hasfp_server03": {
      "servers": ["server03","server02","server01","<NEW_NODE>"]
    },
    "lia_server02": {
      "servers": ["server02","server03","server01","<NEW_NODE>"]
    },
    "lia_server03": {
      "servers": ["server03","server02","server01","<NEW_NODE>"]
    },
    "_studio_server02": {
      "servers": ["server02","server03","server01","<NEW_NODE>"]
    },
    "_studio_server03": {
      "servers": ["server03","server02","server01","<NEW_NODE>"]
    },
    "fp_server01": {
      "servers": ["server01","server03","server02","<NEW_NODE>"]
    },
    "hasfp_server01": {
      "servers": ["server01","server03","server02","<NEW_NODE>"]
    },
    "orole_server01": {
      "servers": ["server01","server03","server02","<NEW_NODE>"]
    },
    "lia_server01": {
      "servers": ["server01","server03","server02","<NEW_NODE>"]
    },
    "schemalock_server01": {
      "servers": ["server01","server03","server02","<NEW_NODE>"]
    },
    "oschedule_server01": {
      "servers": ["server01","server03","server02","<NEW_NODE>"]
    },
    "user_server01": {
      "servers": ["server01","server03","server02","<NEW_NODE>"]
    },
    "request_server01": {
      "servers": ["server01","server03","server02","<NEW_NODE>"]
    },
    "e_server01": {
      "servers": ["server01","server03","server02","<NEW_NODE>"]
    },
    "rg_server01": {
      "servers": ["server01","server03","server02","<NEW_NODE>"]
    },
    "ouser_server01": {
      "servers": ["server01","server03","server02","<NEW_NODE>"]
    },
    "v_server01": {
      "servers": ["server01","server03","server02","<NEW_NODE>"]
    },
    "schemaversion_server01": {
      "servers": ["server01","server03","server02","<NEW_NODE>"]
    },
    "orids_server01": {
      "servers": ["server01","server03","server02","<NEW_NODE>"]
    },
    "edge1_server01": {
      "servers": ["server01","server03","server02","<NEW_NODE>"]
    },
    "_studio_server01": {
      "servers": ["server01","server03","server02","<NEW_NODE>"]
    },
    "ofunction_server01": {
      "servers": ["server01","server03","server02","<NEW_NODE>"]
    }
  }
}
---------- [OHazelcastPlugin]
2015-12-04 08:17:13:319 WARNI [server01]->[[server03]] requesting deploy of database 'db' on local server... [OHazelcastPlugin][server01] Error on starting distributed plugin
com.orientechnologies.orient.server.distributed.ODistributedException: Quorum cannot be reached because there are no nodes available
	at com.orientechnologies.orient.server.hazelcast.OHazelcastDistributedDatabase.calculateQuorum(OHazelcastDistributedDatabase.java:369)
	at com.orientechnologies.orient.server.hazelcast.OHazelcastDistributedDatabase.send2Nodes(OHazelcastDistributedDatabase.java:119)
	at com.orientechnologies.orient.server.hazelcast.OHazelcastPlugin.sendRequest(OHazelcastPlugin.java:359)
	at com.orientechnologies.orient.server.hazelcast.OHazelcastPlugin.requestDatabase(OHazelcastPlugin.java:939)
	at com.orientechnologies.orient.server.hazelcast.OHazelcastPlugin.installDatabase(OHazelcastPlugin.java:901)
	at com.orientechnologies.orient.server.hazelcast.OHazelcastPlugin.installNewDatabases(OHazelcastPlugin.java:1459)
	at com.orientechnologies.orient.server.hazelcast.OHazelcastPlugin.startup(OHazelcastPlugin.java:184)
	at com.orientechnologies.orient.server.OServer.registerPlugins(OServer.java:979)
	at com.orientechnologies.orient.server.OServer.activate(OServer.java:346)
	at com.orientechnologies.orient.server.OServerMain.main(OServerMain.java:41)
```

Note that the server process terminates after the quorum related exception above.

This did not happen previously (we were running 2.1.4) but since upgrade to 2.1.6 it seems to happen each time a node goes down.
The only thing that seems to help is putting **all** the nodes down and then restarting them.

**Comment by lvca** [comment]
This has been already fixed in 2.1.7 that will be released today, but you can already try it by compiling (`mvn clean install`) the 2.1.x branch.

**Comment by mriehl** [comment]
Awesome, thanks! You guys are the best :star2:

**Comment by lvca** [comment]
Having your confirm on this before to release v2.1.7 would be awesome!

**Comment by mriehl** [comment]
Yes I don't seem to be able to reproduce this with 3 test VMs so :+1:

**Comment by lvca** [comment]
Cool, thank you.

**Comment by mriehl** [comment]
@lvca any estimate when 2.1.7 will be released?
