### ISSUE TITLE
Error in Pipeline execution: com.orientechnologies.orient.core.exception.OSerializationException: Impossible serialize value of type class net.sourceforge.jtds.jdbc.ClobImpl with the ODocument binary serializer

### ISSUE THREAD

**Issue by grachit** [orientechnologies/orientdb#5422]
In order to proceed from issue #5421, I created a custom class loader to load jtds driver to run OETL from java main program.

com.orientechnologies.orient.etl.OETLProcessor.main(new String[]{"E:\\Development\\config.json"});

but seeing following exception:

Error in Pipeline execution: com.orientechnologies.orient.core.exception.OSerializationException: Impossible serialize value of type class net.sourceforge.jtds.jdbc.ClobImpl with the ODocument binary serializer
ETL process halted: com.orientechnologies.orient.etl.OETLProcessHaltedException: Halt
Exception in thread "main" com.orientechnologies.orient.etl.OETLProcessHaltedException: Halt
	at com.orientechnologies.orient.etl.OETLPipeline.execute(OETLPipeline.java:149)
	at com.orientechnologies.orient.etl.OETLProcessor.executeSequentially(OETLProcessor.java:448)
	at com.orientechnologies.orient.etl.OETLProcessor.execute(OETLProcessor.java:255)
	at com.orientechnologies.orient.etl.OETLProcessor.main(OETLProcessor.java:109)
	at DBConnection.main(DBConnection.java:71)
Caused by: com.orientechnologies.orient.core.exception.OSerializationException: Impossible serialize value of type class net.sourceforge.jtds.jdbc.ClobImpl with the ODocument binary serializer
	at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinaryV0.serialize(ORecordSerializerBinaryV0.java:257)
	at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinary.toStream(ORecordSerializerBinary.java:105)
	at com.orientechnologies.orient.core.record.impl.ODocument.toStream(ODocument.java:2285)
	at com.orientechnologies.orient.core.record.impl.ODocument.toStream(ODocument.java:671)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.executeSaveRecord(ODatabaseDocumentTx.java:1903)
	at com.orientechnologies.orient.core.tx.OTransactionNoTx.saveRecord(OTransactionNoTx.java:160)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.save(ODatabaseDocumentTx.java:2538)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.save(ODatabaseDocumentTx.java:121)
	at com.orientechnologies.orient.core.record.impl.ODocument.save(ODocument.java:1768)
	at com.orientechnologies.orient.core.record.impl.ODocument.save(ODocument.java:1759)
	at com.tinkerpop.blueprints.impls.orient.OrientElement.save(OrientElement.java:329)
	at com.tinkerpop.blueprints.impls.orient.OrientElement.save(OrientElement.java:309)
	at com.tinkerpop.blueprints.impls.orient.OrientElement.setProperty(OrientElement.java:204)
	at com.orientechnologies.orient.etl.transformer.OVertexTransformer.executeTransform(OVertexTransformer.java:70)
	at com.orientechnologies.orient.etl.transformer.OAbstractTransformer.transform(OAbstractTransformer.java:37)
	at com.orientechnologies.orient.etl.OETLPipeline.execute(OETLPipeline.java:115)
	... 4 more

**Comment by grachit** [comment]
It has issue with bit data type in sql server. If i don't include that select list, it's work fine. Do we need handle it explicitly?

**Comment by robfrank** [comment]
i fixed mapping of BIT type:
https://github.com/orientechnologies/orientdb/commit/704bdc0690ce89ec282dc0dbbabed63b53b3f59d

I will continue discussion on the #5801
