### ISSUE TITLE
thread contention java remote client

### ISSUE THREAD

**Issue by dvoet** [orientechnologies/orientdb#5433]
Hi,

We are having performance problems using the java client to a remote orient database. There does not appear to be any network issues; calls through the commandline and rest clients are fast and the web console is fast. Looking at thread dumps, it appears as if our code is usually blocked trying to acquire a lock:

```
    at sun.misc.Unsafe.park(boolean, long)
    at java.util.concurrent.locks.LockSupport.park(java.lang.Object) (line: 175)
    at java.util.concurrent.locks.AbstractQueuedSynchronizer.parkAndCheckInterrupt() (line: 836)
    at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireQueued(java.util.concurrent.locks.AbstractQueuedSynchronizer$Node, int) (line: 870)
    at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquire(int) (line: 1199)
    at java.util.concurrent.locks.ReentrantLock$NonfairSync.lock() (line: 209)
    at java.util.concurrent.locks.ReentrantLock.lock() (line: 285)
    at com.orientechnologies.common.concur.lock.OAdaptiveLock.lock() (line: 98)
    at com.orientechnologies.orient.enterprise.channel.OChannel.acquireReadLock() (line: 120)
    at com.orientechnologies.orient.enterprise.channel.binary.OChannelBinaryAsynchClient.beginResponse(int, long, boolean) (line: 182)
    at com.orientechnologies.orient.enterprise.channel.binary.OChannelBinaryAsynchClient.beginResponse(int, boolean)
    at com.orientechnologies.orient.client.remote.OStorageRemote.beginResponse(com.orientechnologies.orient.enterprise.channel.binary.OChannelBinaryAsynchClient) (line: 1871)
    at com.orientechnologies.orient.client.remote.OStorageRemote.readRecord(com.orientechnologies.orient.core.id.ORecordId, java.lang.String, boolean, com.orientechnologies.orient.core.storage.ORecordCallback, boolean, com.orientechnologies.orient.core.storage.OStorage$LOCKING_STRATEGY) (line: 492)
    at com.orientechnologies.orient.client.remote.OStorageRemoteThread.readRecord(com.orientechnologies.orient.core.id.ORecordId, java.lang.String, boolean, com.orientechnologies.orient.core.storage.ORecordCallback, boolean, com.orientechnologies.orient.core.storage.OStorage$LOCKING_STRATEGY) (line: 253)
    at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.executeReadRecord(com.orientechnologies.orient.core.id.ORecordId, com.orientechnologies.orient.core.record.ORecord, java.lang.String, boolean, boolean, com.orientechnologies.orient.core.storage.OStorage$LOCKING_STRATEGY) (line: 1580)
    at com.orientechnologies.orient.core.tx.OTransactionOptimistic.loadRecord(com.orientechnologies.orient.core.id.ORID, com.orientechnologies.orient.core.record.ORecord, java.lang.String, boolean, boolean, com.orientechnologies.orient.core.storage.OStorage$LOCKING_STRATEGY) (line: 226)
    at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.load(com.orientechnologies.orient.core.id.ORID, java.lang.String, boolean, boolean, com.orientechnologies.orient.core.storage.OStorage$LOCKING_STRATEGY)
    at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.load(com.orientechnologies.orient.core.id.ORID, java.lang.String, boolean, boolean, com.orientechnologies.orient.core.storage.OStorage$LOCKING_STRATEGY)
    at com.orientechnologies.orient.core.iterator.OIdentifiableIterator.readCurrentRecord(com.orientechnologies.orient.core.record.ORecord, int) (line: 278)
    at com.orientechnologies.orient.core.iterator.ORecordIteratorClusters.hasNext() (line: 147)
    at com.tinkerpop.blueprints.impls.orient.OrientElementIterator.hasNext()
    at com.tinkerpop.blueprints.impls.orient.OrientElementIterator.next() (line: 52)
    at com.tinkerpop.blueprints.impls.orient.OrientElementIterator.next()
    at com.tinkerpop.pipes.util.iterators.HistoryIterator.next() (line: 25)
    at com.tinkerpop.pipes.IdentityPipe.processNextStart()
    at com.tinkerpop.pipes.AbstractPipe.next()
    at com.tinkerpop.pipes.filter.FilterFunctionPipe.processNextStart() (line: 23)
    at com.tinkerpop.pipes.AbstractPipe.next()
    at com.tinkerpop.pipes.util.Pipeline.next()
    at com.tinkerpop.pipes.util.PipeHelper.counter(java.util.Iterator) (line: 107)
    at com.tinkerpop.gremlin.java.GremlinPipeline.count()
<snip>
```

I believe that the lock is held by a "OrientDB <- Asynch Client" thread:
```
  Thread "OrientDB <- Asynch Client (orientdb.dsde-dev.broadinstitute.org/10.255.10.169:2424)":
    at java.net.SocketInputStream.socketRead0(java.io.FileDescriptor, byte[ ], int, int, int)
    at java.net.SocketInputStream.socketRead(java.io.FileDescriptor, byte[ ], int, int, int)
    at java.net.SocketInputStream.read(byte[ ], int, int, int) (line: 170)
    at java.net.SocketInputStream.read(byte[ ], int, int)
    at java.io.BufferedInputStream.fill() (line: 246)
    at java.io.BufferedInputStream.read() (line: 265)
    at java.io.DataInputStream.readByte() (line: 265)
    at com.orientechnologies.orient.enterprise.channel.binary.OChannelBinary.readByte()
    at com.orientechnologies.orient.enterprise.channel.binary.OChannelBinaryAsynchClient.beginResponse(int, long, boolean) (line: 200)
    at com.orientechnologies.orient.enterprise.channel.binary.OAsynchChannelServiceThread.execute() (line: 50)
    at com.orientechnologies.common.thread.OSoftThread.run() (line: 69)* Thread group "main":
```

This is killing our performance. When we use a plocal database we have sub second response times for our code but with a remote connection it is around 2 seconds for a single request and can be up to 30 seconds under load.

Any ideas what could be causing this or where to look?

Thanks,
Doug

**Comment by dvoet** [comment]
note that my stack traces come from client version 2.0.8 but the same issue exists with 2.1.6.

**Comment by Ashendra** [comment]
Any update on this?

**Comment by tglman** [comment]
hi @dvoet,

I think this error was fixed not log time ago, the fix should be in 2.1.9, anyway we suggest to update to the lastest hotfix.
here is the commit: https://github.com/orientechnologies/orientdb/commit/a8a024c9049b78de8cf0df64d989d0f30ad13392

can you check on your use case and confirm ?

**Comment by Ashendra** [comment]
Did not solved the issue in my case.

**Comment by dvoet** [comment]
This issue among others led us to switch database technologies. So, sorry, I am no longer interested.

**Comment by tglman** [comment]
closing as not valid, we are going to change the client architecture in 3.0 anyway

**Comment by abyssQu** [comment]
having the same issue with 2.1.15. Why is this closed?

**Comment by abyssQu** [comment]
Is there a workaround for this issue? It seems to be related to the size of the overall graph. I have two classes of nodes, say class A and B. There are 500,000 nodes in class A and a few in class B. But I am running into this issue when I query class B. Below is related thread dump.
I am trying to find out if I am doing something wrong or this is a bug or there is the fundamental flaw in the OrientDB design.

Unsafe.park(boolean, long) line: not available [native method]	
LockSupport.park(Object) line: 186	
ReentrantLock$NonfairSync(AbstractQueuedSynchronizer).parkAndCheckInterrupt() line: 834 [local variables unavailable]	
ReentrantLock$NonfairSync(AbstractQueuedSynchronizer).acquireQueued(AbstractQueuedSynchronizer$Node, int) line: 867	
ReentrantLock$NonfairSync(AbstractQueuedSynchronizer).acquire(int) line: 1197	
ReentrantLock$NonfairSync.lock() line: 214	
ReentrantLock.lock() line: 290	
OAdaptiveLock.lock() line: 99	
OChannelBinaryAsynchClient(OChannel).acquireReadLock() line: 121	
OChannelBinaryAsynchClient.beginResponse(int, long, boolean) line: 181	
OChannelBinaryAsynchClient.beginResponse(int, boolean) line: 170	
OStorageRemote.beginResponse(OChannelBinaryAsynchClient) line: 2158	
OStorageRemote.readRecord(ORecordId, String, boolean, ORecordCallback<ORawBuffer>) line: 686	
OStorageRemoteThread.readRecord(ORecordId, String, boolean, ORecordCallback<ORawBuffer>) line: 250	
ODatabaseDocumentTx$SimpleRecordReader.readRecord(OStorage, ORecordId, String, boolean, ORecordVersion) line: 3224	
OPartitionedDatabasePool$DatabaseDocumentTxPolled(ODatabaseDocumentTx).executeReadRecord(ORecordId, ORecord, ORecordVersion, String, boolean, boolean, boolean, LOCKING_STRATEGY, RecordReader) line: 1844	
OTransactionOptimistic.loadRecord(ORID, ORecord, String, boolean, boolean, boolean, OStorage$LOCKING_STRATEGY) line: 243	
OPartitionedDatabasePool$DatabaseDocumentTxPolled(ODatabaseDocumentTx).load(ORID, String, boolean, boolean, boolean, LOCKING_STRATEGY) line: 1620	
OPartitionedDatabasePool$DatabaseDocumentTxPolled(ODatabaseDocumentTx).load(ORID, String, boolean, boolean, boolean, OStorage$LOCKING_STRATEGY) line: 121	
ORecordIteratorClass<REC>(OIdentifiableIterator<REC>).readCurrentRecord(ORecord, int) line: 287	
ORecordIteratorClass<REC>(ORecordIteratorClusters<REC>).hasNext() line: 160	
OrientElementIterator<T>.hasNext() line: 46	
DefaultGraphQuery$DefaultGraphQueryIterable$1.loadNext() line: 119	
DefaultGraphQuery$DefaultGraphQueryIterable$1.hasNext() line: 95

**Comment by lvca** [comment]
@abyssQu Is the client blocked or just slow? How many concurrent threads are you using? How big is the resultset you are fetching?

**Comment by abyssQu** [comment]
just slow, I have around 10 concurrent threads. the result set is very small, as I said the class A only has a few nodes.

**Comment by lvca** [comment]
Could you check the opened socket between client and server? Check with `netstat -a`. They should be 10 if you have 10 concurrent clients. To tune that set `-DCLIENT_CHANNEL_MAX_POOL=100` on the client, but in 2.1.x the default should be 100.

**Comment by abyssQu** [comment]
More than 10, but should be less than 100
```
tcp4       0      0  localhost.49153        localhost.58499        ESTABLISHED
tcp4       0      0  localhost.58499        localhost.49153        ESTABLISHED
tcp4       0      0  localhost.49153        localhost.58495        ESTABLISHED
tcp4       0      0  localhost.58495        localhost.49153        ESTABLISHED
tcp4       0      0  localhost.49153        localhost.58493        FIN_WAIT_2 
tcp4       0      0  localhost.58493        localhost.49153        CLOSE_WAIT 
tcp4       0      0  localhost.49153        localhost.58470        ESTABLISHED
tcp4       0      0  localhost.58470        localhost.49153        ESTABLISHED
tcp4       0      0  localhost.49153        localhost.58469        ESTABLISHED
tcp4       0      0  localhost.49153        localhost.58468        ESTABLISHED
tcp4       0      0  localhost.58469        localhost.49153        ESTABLISHED
tcp4       0      0  localhost.58468        localhost.49153        ESTABLISHED
tcp4       0      0  localhost.49153        localhost.58464        ESTABLISHED
tcp4       0      0  localhost.58464        localhost.49153        ESTABLISHED
tcp4       0      0  localhost.49153        localhost.58462        ESTABLISHED
tcp4       0      0  localhost.58462        localhost.49153        ESTABLISHED
tcp4       0      0  localhost.49153        localhost.58442        ESTABLISHED
tcp4       0      0  localhost.58442        localhost.49153        ESTABLISHED
tcp4       0      0  localhost.49153        localhost.58428        ESTABLISHED
tcp4       0      0  localhost.58428        localhost.49153        ESTABLISHED
tcp4       0      0  localhost.49153        localhost.58392        ESTABLISHED
tcp4       0      0  localhost.49153        localhost.58391        ESTABLISHED
tcp4       0      0  localhost.58392        localhost.49153        ESTABLISHED
tcp4       0      0  localhost.58391        localhost.49153        ESTABLISHED
tcp4       0      0  localhost.49153        localhost.58290        ESTABLISHED
tcp4       0      0  localhost.58290        localhost.49153        ESTABLISHED
tcp4       0      0  localhost.49153        localhost.58262        ESTABLISHED
tcp4       0      0  localhost.58262        localhost.49153        ESTABLISHED
tcp4       0      0  localhost.49153        localhost.58129        ESTABLISHED
tcp4       0      0  localhost.58129        localhost.49153        ESTABLISHED
tcp4       0      0  localhost.kofax-svr    localhost.58075        ESTABLISHED
tcp4       0      0  localhost.58075        localhost.kofax-svr    ESTABLISHED
tcp4       0      0  localhost.kofax-svr    localhost.58074        ESTABLISHED
tcp4       0      0  localhost.58074        localhost.kofax-svr    ESTABLISHED
tcp4       0      0  localhost.49153        localhost.57895        ESTABLISHED
tcp4       0      0  localhost.49153        localhost.57894        ESTABLISHED
tcp4       0      0  localhost.57895        localhost.49153        ESTABLISHED
tcp4       0      0  localhost.57894        localhost.49153        ESTABLISHED
tcp4       0      0  localhost.49153        localhost.57595        ESTABLISHED
tcp4       0      0  localhost.57595        localhost.49153        ESTABLISHED
tcp4       0      0  localhost.kofax-svr    localhost.56651        ESTABLISHED
tcp4       0      0  localhost.56651        localhost.kofax-svr    ESTABLISHED
tcp4       0      0  localhost.kofax-svr    localhost.56650        ESTABLISHED
tcp4       0      0  localhost.56650        localhost.kofax-svr    ESTABLISHED
tcp4       0      0  localhost.kofax-svr    localhost.56644        ESTABLISHED
tcp4       0      0  localhost.56644        localhost.kofax-svr    ESTABLISHED
tcp4       0      0  localhost.kofax-svr    localhost.56639        ESTABLISHED
tcp4       0      0  localhost.56639        localhost.kofax-svr    ESTABLISHED
tcp4       0      0  localhost.8005         *.*                    LISTEN     
tcp4       0      0  localhost.56552        localhost.56557        ESTABLISHED
tcp4       0      0  localhost.56557        localhost.56552        ESTABLISHED
tcp4       0      0  localhost.49153        localhost.55131        ESTABLISHED
tcp4       0      0  localhost.55131        localhost.49153        ESTABLISHED
tcp4       0      0  localhost.49153        localhost.55128        ESTABLISHED
tcp4       0      0  localhost.55128        localhost.49153        ESTABLISHED
tcp4       0      0  localhost.49153        localhost.55117        ESTABLISHED
tcp4       0      0  localhost.55117        localhost.49153        ESTABLISHED
tcp4       0      0  localhost.49153        localhost.55076        ESTABLISHED
tcp4       0      0  localhost.55076        localhost.49153        ESTABLISHED
tcp4       0      0  localhost.49153        localhost.54284        ESTABLISHED
tcp4       0      0  localhost.54284        localhost.49153        ESTABLISHED
tcp4       0      0  localhost.49153        localhost.54239        ESTABLISHED
tcp4       0      0  localhost.54239        localhost.49153        ESTABLISHED
tcp6       0      0  localhost.lingwood     localhost.54179        ESTABLISHED
tcp6       0      0  localhost.54179        localhost.lingwood     ESTABLISHED
```

**Comment by lvca** [comment]
I'm sorry, what's the OrientDB port?

**Comment by lvca** [comment]
Closing because no answer after months. In case please reopen/comment this.

**Comment by gtadudeps** [comment]
Hi @lvca @tglman we are using 2.2.28v of orient client/DB and still experiencing this issue the load is around 31.1 K inserts/read per minute and have 4 concurrent threads but we have identified some thread are getting locked up quite frequently under load and killing the performance of whole application attaching a drill down graph
