### ISSUE TITLE
NPE upon starting OrientDB 2.1.7

### ISSUE THREAD

**Issue by nagarajasr** [orientechnologies/orientdb#5440]
I just built 2.1.7 from source and when starting the DB, received this NPE:

```
./bin/server.sh
           .
          .`        `
          ,      `:.
         `,`    ,:`
         .,.   :,,
         .,,  ,,,
    .    .,.:::::  ````                                 :::::::::     :::::::::
    ,`   .::,,,,::.,,,,,,`;;                      .:    ::::::::::    :::    :::
    `,.  ::,,,,,,,:.,,.`  `                       .:    :::      :::  :::     :::
     ,,:,:,,,,,,,,::.   `        `         ``     .:    :::      :::  :::     :::
      ,,:.,,,,,,,,,: `::, ,,   ::,::`   : :,::`  ::::   :::      :::  :::    :::
       ,:,,,,,,,,,,::,:   ,,  :.    :   ::    :   .:    :::      :::  :::::::
        :,,,,,,,,,,:,::   ,,  :      :  :     :   .:    :::      :::  :::::::::
  `     :,,,,,,,,,,:,::,  ,, .::::::::  :     :   .:    :::      :::  :::     :::
  `,...,,:,,,,,,,,,: .:,. ,, ,,         :     :   .:    :::      :::  :::     :::
    .,,,,::,,,,,,,:  `: , ,,  :     `   :     :   .:    :::      :::  :::     :::
      ...,::,,,,::.. `:  .,,  :,    :   :     :   .:    :::::::::::   :::     :::
           ,::::,,,. `:   ,,   :::::    :     :   .:    :::::::::     ::::::::::
           ,,:` `,,.
          ,,,    .,`
         ,,.     `,                                          GRAPH DATABASE
       ``        `.
                 ``                                          orientdb.com
                 `
java.lang.NullPointerException
        at com.orientechnologies.orient.core.config.OGlobalConfiguration$2.change(OGlobalConfiguration.java:397)
        at com.orientechnologies.orient.core.config.OGlobalConfiguration.setValue(OGlobalConfiguration.java:811)
        at com.orientechnologies.orient.core.config.OGlobalConfiguration.readConfiguration(OGlobalConfiguration.java:728)
        at com.orientechnologies.orient.core.config.OGlobalConfiguration.<clinit>(OGlobalConfiguration.java:638)
        at com.orientechnologies.common.profiler.OProfilerStub.<init>(OProfilerStub.java:38)
        at com.orientechnologies.orient.core.Orient.startup(Orient.java:199)
        at com.orientechnologies.orient.core.Orient.<clinit>(Orient.java:87)
        at com.orientechnologies.orient.server.OServer.<init>(OServer.java:132)
        at com.orientechnologies.orient.server.OServer.<init>(OServer.java:115)
        at com.orientechnologies.orient.server.OServerMain.create(OServerMain.java:26)
        at com.orientechnologies.orient.server.OServerMain.main(OServerMain.java:40)

2015-12-09 19:12:09:188 INFO  OrientDB auto-config DISKCACHE=493MB (heap=455MB os=2,996MB disk=2,162MB) [orientechnologies]
2015-12-09 19:12:09:189 SEVER Can not change cache size in runtime because storage engine plocal was not registered [OGlobalConfiguration$1]
2015-12-09 19:12:09:290 INFO  Loading configuration from: /home/nagu/src/orientdb/releases/orientdb-community-2.1.7/config/orientdb-server-config.xml... [OServerConfigurationLoaderXml]
2015-12-09 19:12:09:457 INFO  OrientDB Server v2.1.7 (build UNKNOWN@r; 2015-12-09 08:15:57+0000) is starting up... [OServer]
2015-12-09 19:12:09:478 INFO  Databases directory: /home/nagu/src/orientdb/releases/orientdb-community-2.1.7/databases [OServer]
2015-12-09 19:12:09:514 INFO  Port 0.0.0.0:2424 busy, trying the next available... [OServerNetworkListener]
2015-12-09 19:12:09:515 INFO  Listening binary connections on 0.0.0.0:2425 (protocol v.32, socket=default) [OServerNetworkListener]
2015-12-09 19:12:09:519 INFO  Port 0.0.0.0:2480 busy, trying the next available... [OServerNetworkListener]
2015-12-09 19:12:09:521 INFO  Listening http connections on 0.0.0.0:2481 (protocol v.10, socket=default) [OServerNetworkListener]

+---------------------------------------------------------------+
|                WARNING: FIRST RUN CONFIGURATION               |
+---------------------------------------------------------------+
| This is the first time the server is running. Please type a   |
| password of your choice for the 'root' user or leave it blank |
| to auto-generate it.                                          |
|                                                               |
| To avoid this message set the environment variable or JVM     |
| setting ORIENTDB_ROOT_PASSWORD to the root password to use.   |
+---------------------------------------------------------------+

Root password [BLANK=auto generate it]: iwonttellyou

2015-12-09 19:26:09:802 INFO  Installing dynamic plugin 'studio-2.1.zip'... [OServerPluginManager]
2015-12-09 19:26:09:889 INFO  Installing GREMLIN language v.2.6.0 - graph.pool.max=50 [OGraphServerHandler]
2015-12-09 19:26:09:890 INFO  [OVariableParser.resolveVariables] Error on resolving property: distributed [orientechnologies]
2015-12-09 19:26:09:891 INFO  Installing Script interpreter. WARN: authenticated clients can execute any kind of code into the server by using the following allowed languages: [sql] [OServerSi
deScriptInterpreter]
2015-12-09 19:26:09:892 INFO  OrientDB Server v2.1.7 (build UNKNOWN@r; 2015-12-09 08:15:57+0000) is active. [OServer]

```

**Comment by luigidellaquila** [comment]
Hi @nagarajasr 

it seems there is a bug in the Git tag, but the official Maven and zip releases work correctly.
Could you please try to download them or to build from 2.1.x branch?

Thanks

Luigi
