### ISSUE TITLE
Problem autodeploy new database on node join

### ISSUE THREAD

**Issue by tglman** [orientechnologies/orientdb#5449]
On autodeploy, at the second node start, the distributed database install get stack.  
stack trace:
```
Found one Java-level deadlock:
=============================
"OrientDB Auditing Logging Thread - GratefulDeadConcerts":
  waiting for ownable synchronizer 0x00000000eb496b08, (a com.orientechnologies.common.concur.lock.OReadersWriterSpinLock),
  which is held by "main"
"main":
  waiting to lock monitor 0x00007f7a00011b18 (object 0x00000000eaf2d548, a java.util.HashMap),
  which is held by "OrientDB Auditing Logging Thread - GratefulDeadConcerts"

Java stack information for the threads listed above:
===================================================
"OrientDB Auditing Logging Thread - GratefulDeadConcerts":
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x00000000eb496b08> (a com.orientechnologies.common.concur.lock.OReadersWriterSpinLock)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
	at com.orientechnologies.common.concur.lock.OReadersWriterSpinLock.acquireReadLock(OReadersWriterSpinLock.java:80)
	at com.orientechnologies.orient.core.metadata.schema.OSchemaShared.acquireSchemaReadLock(OSchemaShared.java:616)
	at com.orientechnologies.orient.core.metadata.schema.OSchemaShared.getClasses(OSchemaShared.java:828)
	at com.orientechnologies.orient.core.metadata.schema.OSchemaProxy.getClasses(OSchemaProxy.java:181)
	at com.orientechnologies.orient.server.hazelcast.OHazelcastPlugin.installDbClustersLocalStrategy(OHazelcastPlugin.java:1304)
	at com.orientechnologies.orient.server.hazelcast.OHazelcastPlugin.onOpen(OHazelcastPlugin.java:442)
	- locked <0x00000000eaf2d548> (a java.util.HashMap)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.callOnOpenListeners(ODatabaseDocumentTx.java:345)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.open(ODatabaseDocumentTx.java:279)
	at com.orientechnologies.agent.auditing.OAuditingLoggingThread.openDatabase(OAuditingLoggingThread.java:86)
	at com.orientechnologies.agent.auditing.OAuditingLoggingThread.run(OAuditingLoggingThread.java:52)
"main":
	at com.orientechnologies.orient.server.distributed.ODistributedAbstractPlugin.getDatabaseConfiguration(ODistributedAbstractPlugin.java:308)
	- waiting to lock <0x00000000eaf2d548> (a java.util.HashMap)
	at com.orientechnologies.orient.server.hazelcast.OHazelcastDistributedDatabase.send2Nodes(OHazelcastDistributedDatabase.java:110)
	at com.orientechnologies.orient.server.hazelcast.OHazelcastPlugin.sendRequest(OHazelcastPlugin.java:359)
	at com.orientechnologies.orient.server.distributed.ODistributedStorage.command(ODistributedStorage.java:307)
	at com.orientechnologies.orient.server.distributed.ODistributedStorage.addCluster(ODistributedStorage.java:1269)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.addCluster(ODatabaseDocumentTx.java:1263)
	at com.orientechnologies.orient.core.metadata.schema.OClassImpl.createClusterIfNeeded(OClassImpl.java:2091)
	at com.orientechnologies.orient.core.metadata.schema.OClassImpl.addCluster(OClassImpl.java:1058)
	at com.orientechnologies.orient.server.hazelcast.OHazelcastPlugin.installLocalClusterPerClass(OHazelcastPlugin.java:1615)
	- locked <0x00000000eaf28288> (a com.orientechnologies.orient.server.hazelcast.OHazelcastPlugin)
	at com.orientechnologies.orient.server.hazelcast.OHazelcastPlugin.installDbClustersForLocalNode(OHazelcastPlugin.java:1291)
	at com.orientechnologies.orient.server.hazelcast.OHazelcastPlugin$2.call(OHazelcastPlugin.java:1125)
	at com.orientechnologies.orient.server.hazelcast.OHazelcastPlugin$2.call(OHazelcastPlugin.java:1122)
	at com.orientechnologies.orient.server.hazelcast.OHazelcastDistributedDatabase.configureDatabase(OHazelcastDistributedDatabase.java:239)
	at com.orientechnologies.orient.server.hazelcast.OHazelcastPlugin.installDatabaseFromNetwork(OHazelcastPlugin.java:1122)
	at com.orientechnologies.orient.server.hazelcast.OHazelcastPlugin.requestDatabase(OHazelcastPlugin.java:964)
	at com.orientechnologies.orient.server.hazelcast.OHazelcastPlugin.installDatabase(OHazelcastPlugin.java:901)
	at com.orientechnologies.orient.server.hazelcast.OHazelcastPlugin.installNewDatabases(OHazelcastPlugin.java:1459)
	at com.orientechnologies.orient.server.hazelcast.OHazelcastPlugin.startup(OHazelcastPlugin.java:184)
	at com.orientechnologies.orient.server.OServer.registerPlugins(OServer.java:979)
	at com.orientechnologies.orient.server.OServer.activate(OServer.java:346)
	at com.orientechnologies.orient.server.OServerMain.main(OServerMain.java:41)

Found 1 deadlock.
```

Reproduced on AWS T2.small  
machine info:  
```
uname -a
Linux ip-10-128-1-243 3.10.0-229.14.1.el7.x86_64 #1 SMP Tue Sep 15 15:05:51 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```
```
CentOS Linux release 7.1.1503 (Core)
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

CentOS Linux release 7.1.1503 (Core)
CentOS Linux release 7.1.1503 (Core)
```

source ami:`ami-33734044`  
java version: openjdk 1.8

**Comment by maggiolo00** [comment]
Fixed in 2.1.x
