### ISSUE TITLE
ClassCastException when save a ODocument:OSBTreeException: Error during removing key OCompositeKey

### ISSUE THREAD

**Issue by vtliem** [orientechnologies/orientdb#5465]
Yesterday, my chat application raised exception when I tried to remove someone from one group chat session. Today, I have debugged but the issue seem to be gone. I viewed log and found:
```
	com.orientechnologies.orient.core.index.OIndexException: Error during removal of entry by key
	at com.orientechnologies.orient.core.index.OIndexMultiValues.remove(OIndexMultiValues.java:218)
	at com.orientechnologies.orient.core.index.OIndexAbstract.removeFromSnapshot(OIndexAbstract.java:984)
	at com.orientechnologies.orient.core.index.OIndexAbstract.applyIndexTxEntry(OIndexAbstract.java:1170)
	at com.orientechnologies.orient.core.index.OIndexAbstract.addTxOperation(OIndexAbstract.java:776)
	at com.orientechnologies.orient.core.tx.OTransactionOptimistic$CommitIndexesCallback.run(OTransactionOptimistic.java:101)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.commit(OAbstractPaginatedStorage.java:1202)
	at com.orientechnologies.orient.core.tx.OTransactionOptimistic.doCommit(OTransactionOptimistic.java:609)
	at com.orientechnologies.orient.core.tx.OTransactionOptimistic.commit(OTransactionOptimistic.java:156)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.commit(ODatabaseDocumentTx.java:2653)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.commit(ODatabaseDocumentTx.java:2622)
	at mypackage...removeUsers(GroupChatModel.java:3066)
	....
	Caused by: java.lang.ClassCastException
```
and 
```
com.orientechnologies.orient.core.index.sbtree.local.OSBTreeException: Error during removing key OCompositeKey{keys=[1, 1449109800000, 1449220665360, 1895]} from sbtree task.state_user
	at com.orientechnologies.orient.core.index.sbtree.local.OSBTree.remove(OSBTree.java:603)
	at com.orientechnologies.orient.core.index.engine.OSBTreeIndexEngine.remove(OSBTreeIndexEngine.java:186)
	at com.orientechnologies.orient.core.index.OIndexAbstract.remove(OIndexAbstract.java:490)
	at com.orientechnologies.orient.core.index.OIndexAbstract.remove(OIndexAbstract.java:471)
	at com.orientechnologies.orient.core.index.OIndexAbstract.removeFromSnapshot(OIndexAbstract.java:984)
	at com.orientechnologies.orient.core.index.OIndexAbstract.applyIndexTxEntry(OIndexAbstract.java:1170)
	at com.orientechnologies.orient.core.index.OIndexAbstract.addTxOperation(OIndexAbstract.java:776)
	at com.orientechnologies.orient.core.tx.OTransactionOptimistic$CommitIndexesCallback.run(OTransactionOptimistic.java:101)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.commit(OAbstractPaginatedStorage.java:1202)
	at com.orientechnologies.orient.core.tx.OTransactionOptimistic.doCommit(OTransactionOptimistic.java:609)
	at com.orientechnologies.orient.core.tx.OTransactionOptimistic.commit(OTransactionOptimistic.java:156)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.commit(ODatabaseDocumentTx.java:2653)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.commit(ODatabaseDocumentTx.java:2622)
	at mypackage...removeUsers(GroupChatModel.java:3066)
	...
	at mypackage...onWebSocketText(ChatSocket.java:655)
	Caused by: java.lang.ClassCastException
```

This is a automatic index and and don't have any code which change the index directly. So I think it's maybe a bug of orientdb.
The index is created with:
```java
clzz.createIndex("task.state_user", OClass.INDEX_TYPE.UNIQUE, "state" (BYTE),
		    "users"(LINKSET), "time"(LONG),"reg"(LONG),"no"(INTEGER));
```
When a user has been removed from group chat session, loop all tasks of session and do:
```java
ODocument task = db.load(taskid,..);
Set<ORID> users = task.field("users");
if(users.contains(theUSER)){
    users.remove(theUSER);
    if(users.isEmpty()) task.removeFiled("users");
    else task.setDirty();
   task.save();      
}
```
OS:Centos 6.6x64
OrientDB 2.1.6
Java:Oracle 1.8.0_66

**Comment by vtliem** [comment]
I can reproduce the bug. When the last user is removed from a task,  "users" will be removed from the task and this exception raised. It's seems there is problem when a  automatic index with OCompositeKey is updated (removed item) if a field of OCompositeKey is missing.

**Comment by laa** [comment]
@vtliem I need full stack trace, but you provided only higher level one.
Could you provide full stack trace  ?

**Comment by vtliem** [comment]
Is this ok?
[orientDB_error_log.txt](https://github.com/orientechnologies/orientdb/files/147650/orientDB_error_log.txt)

**Comment by vtliem** [comment]
If I comment out this line `if(users.isEmpty()) task.removeFiled("users");` I can remove user and task users become empty. But when I add a user to task, it raise this exception
[orientdb_error_log2.txt](https://github.com/orientechnologies/orientdb/files/147665/orientdb_error_log2.txt)

**Comment by laa** [comment]
@vtliem is it correct that you remove field from document and that causes exception ? your issue is following, when you remove field you effectively put null there from index point of view and by default we do not support null values, as result system becomes "lost" and does not know what to do with your document. To support null values could you create index with metadata with ignoreNullValues flag set to false. For example : 

```
final OClass studentClass = schema.createClass("lpirtStudent");
studentClass.createProperty("name", OType.STRING);
studentClass.createProperty("diploma", OType.LINK, diplomaClass);

final ODocument metadata = new ODocument().field("ignoreNullValues", false);
studentClass.createIndex("studentDiplomaAndNameIndex", OClass.INDEX_TYPE.UNIQUE.toString(), null, metadata,
          new String[] { "diploma", "name" `});
```
This should solve your issue.

**Comment by vtliem** [comment]
When I don't remove the field, I can save document, but after that, cannot add user to task.
(https://github.com/orientechnologies/orientdb/issues/5465#issuecomment-189100554)

**Comment by laa** [comment]
@vtliem you do not need to keep field, you should create index in the way which I described above. Could you do that ?

**Comment by vtliem** [comment]
The same exception raised.
When users field (linkset type) was removed, userid also was removed from OCompositeKey.

Normal: 
`[state(BYTE),userid(LINK-One of users)],time(LONG),registered(LONG),no(INT)]`
When users field was removed, the index key became:
`[state(BYTE),time(LONG),registered(LONG),no(INT)]`

Because of that, removing this key from index, time (LONG) will be cast to LINKED->exception.

**Comment by laa** [comment]
@vtliem yes I understand that, the point is that given flag prevents this behaviour. 
OK I will look on it next week.

**Comment by laa** [comment]
Fixed both for indexes with null keys support and without null keys support.
