### ISSUE TITLE
OServerMain.server().shutdown() throws org.apache.lucene.store.AlreadyClosedException

### ISSUE THREAD

**Issue by vantonov1** [orientechnologies/orientdb#5466]
2.2.0-beta

org.apache.lucene.store.AlreadyClosedException: this IndexWriter is closed
	at org.apache.lucene.index.IndexWriter.ensureOpen(IndexWriter.java:719)
	at org.apache.lucene.index.IndexWriter.ensureOpen(IndexWriter.java:733)
	at org.apache.lucene.index.IndexWriter.commit(IndexWriter.java:2943)
	at com.orientechnologies.lucene.engine.OLuceneIndexEngineAbstract.closeIndex(OLuceneIndexEngineAbstract.java:400)
	at com.orientechnologies.lucene.engine.OLuceneIndexEngineAbstract.close(OLuceneIndexEngineAbstract.java:251)
	at com.orientechnologies.lucene.engine.OLuceneIndexEngineAbstract.onShutdown(OLuceneIndexEngineAbstract.java:521)
	at com.orientechnologies.orient.core.Orient.shutdown(Orient.java:326)
	at com.orientechnologies.orient.server.OServer.shutdown(OServer.java:458)

**Comment by robfrank** [comment]
Hi, could you add the code?

**Comment by vantonov1** [comment]
Hmmm... I have test, which creates & deletes vertices etc and calls shutdown() in @After. I dont think the exact test code does matter

Most probably I close index twice, but anyway - server should have graceful shutdown

**Comment by robfrank** [comment]
Yes, I agree on graceful shutdown. 
It seems that the close on the underlying LUCENE index it is called twice. 
Having code, even so simple as a test case, could help me understand what is going wrong.

**Comment by vantonov1** [comment]
Ah, it seems I just called shudown() twice

Really, I got stucked with lucene indexes (
https://groups.google.com/forum/#!topic/orient-database/MMVQAj3FlvE), so
stopped testing

On Wed, Dec 16, 2015 at 3:31 PM, Roberto Franchini <notifications@github.com
> wrote:

> Yes, I agree on graceful shutdown.
> It seems that the close on the underlying LUCENE index it is called twice.
> Having code, even so simple as a test case, could help me understand what
> is going wrong.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/orientechnologies/orientdb/issues/5466#issuecomment-165092253>
> .
>



-- 



Valeri.
