### ISSUE TITLE
NPE while commiting unique index

### ISSUE THREAD

**Issue by vantonov1** [orientechnologies/orientdb#5467]
iSingleValue is of type ORecordId
value==null

Caused by: java.lang.NullPointerException
	at com.orientechnologies.orient.core.index.OIndexUnique.put(OIndexUnique.java:76)
	at com.orientechnologies.orient.core.index.OIndexUnique.put(OIndexUnique.java:35)
	at com.orientechnologies.orient.core.index.OIndexAbstract.putInSnapshot(OIndexAbstract.java:845)
	at com.orientechnologies.orient.core.index.OIndexAbstract.applyIndexTxEntry(OIndexAbstract.java:1022)
	at com.orientechnologies.orient.core.index.OIndexAbstract.addTxOperation(OIndexAbstract.java:706)
	at com.orientechnologies.orient.core.tx.OTransactionOptimistic$CommitIndexesCallback.run(OTransactionOptimistic.java:98)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.commit(OAbstractPaginatedStorage.java:1334)
	... 43 more

**Comment by luigidellaquila** [comment]
Hi @vantonov1 

Any hint on how to reproduce the problem? Do you have a test case that fails?

Thanks

Luigi

**Comment by vantonov1** [comment]
Sorry, right now I cant shorten my test enough (I test my own wrapper level). What I could see is that on commit where are two operations in index changes, one is PUT and one is REMOVE.  In OIndexUnique.put() iSingleValue is temporary record, getRecord() returns null, and we have NPE

![image](https://cloud.githubusercontent.com/assets/12628357/11810193/65cf586e-a33d-11e5-8a46-8f96844108a3.png)


But if I just trying to add and remove vertex and asge, where are no changes in index, and it works

**Comment by laa** [comment]
Hi @vantonov1 , what version do you use ?

**Comment by vantonov1** [comment]
Hi!

Hmm... Most probably it was 2.2.0-beta

I gave up with Orient in December - too unstable for me (most probably because I need embedded mode with complicated transactions)

**Comment by laa** [comment]
Sad to hear that in 3.0 we are going to introduce new transaction model, hope you will be back to us.

**Comment by vantonov1** [comment]
Ok, lets check, see you with 3.0-beta :)

Ah, one more stopper was https://groups.google.com/forum/#!topic/orient-database/MMVQAj3FlvE

**Comment by laa** [comment]
Well @vantonov1 I have tried to reproduce your issue according to description but no luck.  Sad that we reacted so later. But we have new working schedule which allows to react on all issues much earlier. Also as I have wrote in 3.0 version we will have new transaction system.

**Comment by vantonov1** [comment]
I checked again, situation with lucene indexing is simple - all fields encountered in query have to be indexed in the same lucene index. So, if I query for fields from both class and superclass, I cant use index from superclass, all fields from superclass have to be reindexed again

 I created issue https://github.com/orientechnologies/orientdb/issues/5868
