### ISSUE TITLE
import database doesn't work with spatial type

### ISSUE THREAD

**Issue by martingg88** [orientechnologies/orientdb#5476]
here is the definition for the index from *.export file
{"name":"place.distance_spatial","type":"SPATIAL","algorithm":"LUCENE"}

but i have the following error for 2.1.7 version

Index 'place.distance_spatial'...Error on database import happened just before line 0, column 41233
com.orientechnologies.orient.core.index.OIndexException: Index with type SPATIAL and algorithm SBTREE does not exist.
        at com.orientechnologies.orient.core.index.OIndexes.getFactory(OIndexes.java:130)
        at com.orientechnologies.orient.core.index.OIndexDefinitionFactory.createMultipleFieldIndexDefinition(OIndexDefinitionFactory.java:88)
        at com.orientechnologies.orient.core.index.OIndexDefinitionFactory.createIndexDefinition(OIndexDefinitionFactory.java:65)
        at com.orientechnologies.orient.core.sql.OCommandExecutorSQLCreateIndex.execute(OCommandExecutorSQLCreateIndex.java:271)
        at com.orientechnologies.orient.core.sql.OCommandExecutorSQLDelegate.execute(OCommandExecutorSQLDelegate.java:90)
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.executeCommand(OAbstractPaginatedStorage.java:1547)
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.command(OAbstractPaginatedStorage.java:1528)
        at com.orientechnologies.orient.core.command.OCommandRequestTextAbstract.execute(OCommandRequestTextAbstract.java:67)
        at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.command(ONetworkProtocolBinary.java:1323)
        at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.executeRequest(ONetworkProtocolBinary.java:400)
        at com.orientechnologies.orient.server.network.protocol.binary.OBinaryNetworkProtocolAbstract.execute(OBinaryNetworkProtocolAbstract.java:223)
        at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:77)

**Comment by martingg88** [comment]
i have following issue as well when import database

- Index '[]'...Error on database import happened just before line 0, column 81408
com.orientechnologies.orient.core.exception.OSerializationException: Error on unmarshalling JSON content '[]': content must be between { }
        at com.orientechnologies.orient.core.serialization.serializer.record.string.ORecordSerializerJSON.unwrapSource(ORecordSerializerJSON.java:398)
        at com.orientechnologies.orient.core.serialization.serializer.record.string.ORecordSerializerJSON.fromString(ORecordSerializerJSON.java:174)
        at com.orientechnologies.orient.core.serialization.serializer.record.string.ORecordSerializerJSON.fromString(ORecordSerializerJSON.java:170)
        at com.orientechnologies.orient.core.db.tool.ODatabaseImport.importManualIndexes(ODatabaseImport.java:708)
        at com.orientechnologies.orient.core.db.tool.ODatabaseImport.importDatabase(ODatabaseImport.java:436)
        at com.orientechnologies.orient.console.OConsoleDatabaseApp.importDatabase(OConsoleDatabaseApp.java:1711)
        at com.orientechnologies.orient.graph.console.OGremlinConsole.importDatabase(OGremlinConsole.java:129)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at com.orientechnologies.common.console.OConsoleApplication.execute(OConsoleApplication.java:392)
        at com.orientechnologies.common.console.OConsoleApplication.executeCommands(OConsoleApplication.java:253)
        at com.orientechnologies.common.console.OConsoleApplication.run(OConsoleApplication.java:142)
        at com.orientechnologies.orient.graph.console.OGremlinConsole.main(OGremlinConsole.java:66)

**Comment by martingg88** [comment]
export database doesn't include available functions. any idea?

**Comment by robfrank** [comment]
which version please?

**Comment by martingg88** [comment]
2.1.7 version.

**Comment by robfrank** [comment]
ok, so can you give me a sample of your schema and data. This way I can speed up the issue resolution. 
Just for recap: you setup a db with spatial data, then you export it and the you try to reimport. Am I right?

**Comment by martingg88** [comment]
can you setup a dummy class with spatial index. sure will have this issue when you doing export with excluding of records and then import.

**Comment by maggiolo00** [comment]
@martingg88 

from which version did you export the database?

**Comment by martingg88** [comment]
2.1.7 version

**Comment by martingg88** [comment]
no update?

**Comment by martingg88** [comment]
any update?

**Comment by robfrank** [comment]
hi, as reported on https://github.com/orientechnologies/orientdb/issues/5097 , I tested backup/restore and import/export of db with spatial indexes on 2.1.13 and it works fine.

**Comment by martingg88** [comment]
please... this issue is not yet solved for version 2.1.14 and i still have following error when importing..

- Index 'place.distance_spatial'...Error on database import happened just before line 0, column 43415
com.orientechnologies.orient.core.index.OIndexException: Index with type SPATIAL and algorithm SBTREE does not exi
st.
        at com.orientechnologies.orient.core.index.OIndexes.getFactory(OIndexes.java:130)
        at com.orientechnologies.orient.core.index.OIndexDefinitionFactory.createMultipleFieldIndexDefinition(OInd
exDefinitionFactory.java:88)
        at com.orientechnologies.orient.core.index.OIndexDefinitionFactory.createIndexDefinition(OIndexDefinitionF
actory.java:65)
        at com.orientechnologies.orient.core.sql.OCommandExecutorSQLCreateIndex.execute(OCommandExecutorSQLCreateI
ndex.java:276)
        at com.orientechnologies.orient.core.sql.OCommandExecutorSQLDelegate.execute(OCommandExecutorSQLDelegate.j
ava:90)
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.executeCommand(OAbstract
PaginatedStorage.java:1545)
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.command(OAbstractPaginat
edStorage.java:1518)
        at com.orientechnologies.orient.core.command.OCommandRequestTextAbstract.execute(OCommandRequestTextAbstra
ct.java:67)
        at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.command(ONetworkProt
ocolBinary.java:1325)
        at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.executeRequest(ONetw
orkProtocolBinary.java:399)
        at com.orientechnologies.orient.server.network.protocol.binary.OBinaryNetworkProtocolAbstract.execute(OBin
aryNetworkProtocolAbstract.java:223)
        at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:77)

Error: com.orientechnologies.orient.core.db.tool.ODatabaseExportException: Error on importing database 'voyage' fr
om file: C:\Users\martingg\Desktop\voyage.export

Error: com.orientechnologies.orient.core.index.OIndexException: Index with type SPATIAL and algorithm SBTREE does
not exist.

**Comment by martingg88** [comment]
com.orientechnologies.orient.core.index.OIndexException: Index with type SPATIAL and algorithm SBTREE does not exi
st.
        at com.orientechnologies.orient.core.index.OIndexes.getFactory(OIndexes.java:130)
        at com.orientechnologies.orient.core.index.OIndexDefinitionFactory.createMultipleFieldIndexDefinition(OInd
exDefinitionFactory.java:88)
        at com.orientechnologies.orient.core.index.OIndexDefinitionFactory.createIndexDefinition(OIndexDefinitionF
actory.java:65)
        at com.orientechnologies.orient.core.sql.OCommandExecutorSQLCreateIndex.execute(OCommandExecutorSQLCreateI
ndex.java:276)
        at com.orientechnologies.orient.core.sql.OCommandExecutorSQLDelegate.execute(OCommandExecutorSQLDelegate.j
ava:90)
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.executeCommand(OAbstract
PaginatedStorage.java:1545)
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.command(OAbstractPaginat
edStorage.java:1518)
        at com.orientechnologies.orient.core.command.OCommandRequestTextAbstract.execute(OCommandRequestTextAbstra
ct.java:67)
        at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.command(ONetworkProt
ocolBinary.java:1325)
        at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.executeRequest(ONetw
orkProtocolBinary.java:399)
        at com.orientechnologies.orient.server.network.protocol.binary.OBinaryNetworkProtocolAbstract.execute(OBin
aryNetworkProtocolAbstract.java:223)
        at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:77)

Error: com.orientechnologies.orient.core.db.tool.ODatabaseExportException: Error on importing database 'voyage' fr
om file: C:\Users\martingg\Desktop\voyage.export

Error: com.orientechnologies.orient.core.index.OIndexException: Index with type SPATIAL and algorithm SBTREE does
not exist.

**Comment by besil** [comment]
Still no updates?
I'm experiencing the same bug following documentation code (OrientDB version 2.1.16):


    OrientGraphNoTx graph = new OrientGraphFactory("memory:prova", "root", "root").getNoTx();

    OrientVertexType cardSharing = graph.createVertexType("Place");
    cardSharing.createProperty("latitude", OType.DOUBLE);
    cardSharing.createProperty("longitude", OType.DOUBLE);
    cardSharing.createProperty("name", OType.STRING);
    cardSharing.createIndex("Place.latitude_longitude", "SPATIAL",
                null, null, "LUCENE", new String[]{"latitude", "longitude"});

I'm receving the following exception:

    com.orientechnologies.orient.core.index.OIndexException: Index with type SPATIAL and algorithm LUCENE does not exist.

	at com.orientechnologies.orient.core.index.OIndexes.getFactory(OIndexes.java:130)
	at com.orientechnologies.orient.core.index.OIndexDefinitionFactory.createMultipleFieldIndexDefinition(OIndexDefinitionFactory.java:88)
	at com.orientechnologies.orient.core.index.OIndexDefinitionFactory.createIndexDefinition(OIndexDefinitionFactory.java:65)
	at com.orientechnologies.orient.core.metadata.schema.OClassImpl.createIndex(OClassImpl.java:1747)
	at com.orientechnologies.orient.core.metadata.schema.OClassAbstractDelegate.createIndex(OClassAbstractDelegate.java:375)
	at com.tinkerpop.blueprints.impls.orient.OrientElementType.access$601(OrientElementType.java:35)
	at com.tinkerpop.blueprints.impls.orient.OrientElementType$7.call(OrientElementType.java:112)
	at com.tinkerpop.blueprints.impls.orient.OrientElementType$7.call(OrientElementType.java:109)
	at com.tinkerpop.blueprints.impls.orient.OrientBaseGraph.executeOutsideTx(OrientBaseGraph.java:1703)
	at com.tinkerpop.blueprints.impls.orient.OrientElementType.createIndex(OrientElementType.java:109)
	at it.mycards.mycardsapi.OrientSpatialTest.spatialTest(OrientSpatialTest.java:24)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:119)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:42)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:234)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:74)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)


Is there any workaround?

**Comment by maggiolo00** [comment]
I see you are working in memory. 

Did you include orientdb-lucene in your dependencies?

**Comment by besil** [comment]
No, I didn't.
Adding the dependency solved the issue.

Thank you

**Comment by luigidellaquila** [comment]
Great, thanks!

I'm closing the issue then

Luigi
