### ISSUE TITLE
OrientGraph.getVertex() throws IllegalArgumentException when cluster is not defined.

### ISSUE THREAD

**Issue by wouterv** [orientechnologies/orientdb#5478]
Using 2.1.8 build.

If you call graph.getVertex with a cluster that isnt defined, it throws an IllegalArgumentException, while previously it just return null, which seems to be like the wanted behaviour. This is the exception we get:

```

com.orientechnologies.orient.core.exception.ORecordNotFoundException: The record with id '#4654:0' was not found

	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.readRecord(OAbstractPaginatedStorage.java:848)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx$SimpleRecordReader.readRecord(ODatabaseDocumentTx.java:3224)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.executeReadRecord(ODatabaseDocumentTx.java:1844)
	at com.orientechnologies.orient.core.tx.OTransactionOptimistic.loadRecord(OTransactionOptimistic.java:243)
	at com.orientechnologies.orient.core.tx.OTransactionOptimistic.loadRecord(OTransactionOptimistic.java:217)
	at com.orientechnologies.orient.core.tx.OTransactionOptimistic.loadRecord(OTransactionOptimistic.java:347)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.load(ODatabaseDocumentTx.java:1588)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.load(ODatabaseDocumentTx.java:121)
	at com.orientechnologies.orient.core.id.ORecordId.getRecord(ORecordId.java:324)
	at com.tinkerpop.blueprints.impls.orient.OrientBaseGraph.getVertex(OrientBaseGraph.java:768)
....
Caused by: java.lang.IllegalArgumentException: Cluster segment #4654 does not exist in database 'test'
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.checkClusterSegmentIndexRange(OAbstractPaginatedStorage.java:2505)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.getClusterById(OAbstractPaginatedStorage.java:1360)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.readRecord(OAbstractPaginatedStorage.java:846)
	... 115 more
```
```

**Comment by Bonizzi** [comment]
Hi @wouterv this is normal behaviour because you try to access to a cluster that doesn't exist.

**Comment by wouterv** [comment]
Well it was normal in 2.1.6 that it returned null. Now suddenly it is an ugly IllegalArgumentException. 
At least make it a ClusterNotDefinedException so I can catch it or something.

**Comment by wouterv** [comment]
My apologies, I can catch ORecordNotFoundException.
