### ISSUE TITLE
Import command throws an exception

### ISSUE THREAD

**Issue by maseev** [orientechnologies/orientdb#5485]
I've just run into the problem when OrientDb simply can't perform the import command. Here's the stack trace which I get when I'm trying to run the import command:

```
com.orientechnologies.orient.core.db.tool.ODatabaseExportException: Error on importing database 'tmpdb' from file: streaming.json

	at com.orientechnologies.orient.core.db.tool.ODatabaseImport.importDatabase(ODatabaseImport.java:471)
	at orientdb.OrientDbTest.exportImportShouldWorkWithoutExceptions(OrientDbTest.java:92)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:69)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:234)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:74)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
Caused by: com.orientechnologies.orient.core.exception.OSchemaException: Class 'ODocumentWrapper' cannot be dropped because it has sub classes. Remove the dependencies before trying to drop it again
	at com.orientechnologies.orient.core.metadata.schema.OSchemaShared.dropClass(OSchemaShared.java:532)
	at com.orientechnologies.orient.core.metadata.schema.OSchemaProxy.dropClass(OSchemaProxy.java:156)
	at com.orientechnologies.orient.core.db.tool.ODatabaseImport.removeDefaultNonSecurityClasses(ODatabaseImport.java:638)
	at com.orientechnologies.orient.core.db.tool.ODatabaseImport.importDatabase(ODatabaseImport.java:419)
	... 29 more
```

And here's the test I'm running - https://github.com/maseev/orient/blob/master/src/test/java/orientdb/OrientDbTest.java#L70. You can execute it with ```mvn test -Dtest=orientdb.OrientDbTest#exportImportShouldWorkWithoutExceptions```

It turned out, that the problem is lurking somewhere here - https://github.com/orientechnologies/orientdb/blob/master/core/src/main/java/com/orientechnologies/orient/core/db/tool/ODatabaseImport.java#L613. 

OrientDB is trying to drop every class except for ORole, OUser and OIdentity. But it doesn't filter out the ODocumentWrapper class which is a superclass for OIdentity and a transitive superclass for OUser and ORole (through the OIdentity). 
In the end, OrientDb is trying to drop ODocumentWrapper class which obviously has several subclasses. As a result, we get an exception.

**Comment by maseev** [comment]
I really hope you guys add some tests related to the export/import feature, so we can confidently use it in the future, thanks.

**Comment by tglman** [comment]
@maseev 
thank you for so detailed report, we are working on a fix.

bye

**Comment by maseev** [comment]
What kind of reply are you waiting for?

**Comment by tglman** [comment]
hi @maseev i just pushed the wrong button, anyway it's fixed now in both 2.1.x (will be the 2.1.9 release) and 2.2.

**Comment by maseev** [comment]
@tglman Can you add this ticket to the appropriate milestone? Just to be sure that everything will be ok when you guys release a new version of OrientDB.

**Comment by tglman** [comment]
@maseev can i close this ?

**Comment by maseev** [comment]
Yep, of course.
