### ISSUE TITLE
how to benchmark OrientDB with YCSB?

### ISSUE THREAD

**Issue by Hadi14** [orientechnologies/orientdb#5489]
Hi All
i want do benchmark OrientDB with YCSB , i read this link:
https://github.com/brianfrankcooper/YCSB/tree/master/orientdb
i install orientdb and YCSB and run them but it got this messages :
<pre><code>-OrientDB database not found, create fresh db
-Could not initialize OrientDB connection pool for Loader: com.orientechnologies.orient.core.exception.ODatabaseException: Cannot create database ....
-exception.ODatabaseException: Cannot create database
-Location passed in WAL does not exist, or IO error was happened. DB can not work in durable mode in such case.</pre></code>

how can i benchmark OrientDB ?

other questions:
2- what is different between this two orientdb's?
https://github.com/orientechnologies/orientdb
and
http://orientdb.com/download/

3-there is a benchmark folder on "http://orientdb.com/download/" , can i use it for my benchmark?

4- if orienteDB is a multimodel Database , how to use it's dimension of document base for example?

**Comment by laa** [comment]
Hi with big probability, you have problems with access rights.
Could you send full stack trace ?

Also if you wait for couple of weeks we will provide updated version of YCSB benchmark.

**Comment by Hadi14** [comment]
Hi @laa it got this :
and can you reply to other Question?
<pre><code>
Loading workload...
Starting test.
OrientDB loading database url = plocal:/temp/databases/ycsb
2015-12-18 05:29:23:869 0 sec: 0 operations; est completion in 0 seconds 
OrientDB database not found, create fresh db
Could not initialize OrientDB connection pool for Loader: com.orientechnologies.orient.core.exception.ODatabaseException: Cannot create database
com.orientechnologies.orient.core.exception.ODatabaseException: Cannot create database
    at com.orientechnologies.orient.core.db.record.ODatabaseRecordAbstract.create(ODatabaseRecordAbstract.java:384)
    at com.orientechnologies.orient.core.db.ODatabaseWrapperAbstract.create(ODatabaseWrapperAbstract.java:55)
    at com.orientechnologies.orient.core.db.ODatabaseRecordWrapperAbstract.create(ODatabaseRecordWrapperAbstract.java:64)
    at com.yahoo.ycsb.db.OrientDBClient.init(OrientDBClient.java:97)
    at com.yahoo.ycsb.DBWrapper.init(DBWrapper.java:63)
    at com.yahoo.ycsb.ClientThread.run(Client.java:289)
Caused by: com.orientechnologies.orient.core.exception.ODatabaseException: Cannot create database
    at com.orientechnologies.orient.core.db.raw.ODatabaseRaw.create(ODatabaseRaw.java:139)
    at com.orientechnologies.orient.core.db.ODatabaseWrapperAbstract.create(ODatabaseWrapperAbstract.java:55)
    at com.orientechnologies.orient.core.db.record.ODatabaseRecordAbstract.create(ODatabaseRecordAbstract.java:338)
    ... 5 more
Caused by: java.lang.IllegalStateException: Location passed in WAL does not exist, or IO error was happened. DB can not work in durable mode in such case.
    at com.orientechnologies.orient.core.storage.impl.local.paginated.wal.OWriteAheadLog.(OWriteAheadLog.java:614)
    at com.orientechnologies.orient.core.storage.impl.local.paginated.wal.OWriteAheadLog.(OWriteAheadLog.java:590)
    at com.orientechnologies.orient.core.storage.impl.local.paginated.OLocalPaginatedStorage.initWal(OLocalPaginatedStorage.java:1538)
    at com.orientechnologies.orient.core.storage.impl.local.paginated.OLocalPaginatedStorage.create(OLocalPaginatedStorage.java:295)
    at com.orientechnologies.orient.core.db.raw.ODatabaseRaw.create(ODatabaseRaw.java:135)
    ... 7 more
com.orientechnologies.orient.core.exception.ODatabaseException: Database 'plocal:/temp/databases/ycsb' is closed
    at com.orientechnologies.orient.core.db.record.ODatabaseRecordAbstract.checkOpeness(ODatabaseRecordAbstract.java:1552)
    at com.orientechnologies.orient.core.db.record.ODatabaseRecordAbstract.getMetadata(ODatabaseRecordAbstract.java:839)
    at com.orientechnologies.orient.core.db.record.ODatabaseRecordAbstract.getMetadata(ODatabaseRecordAbstract.java:91)
    at com.orientechnologies.orient.core.record.ORecordSchemaAwareAbstract.setClassName(ORecordSchemaAwareAbstract.java:395)
    at com.orientechnologies.orient.core.record.impl.ODocument.(ODocument.java:194)
    at com.yahoo.ycsb.db.OrientDBClient.insert(OrientDBClient.java:136)
    at com.yahoo.ycsb.DBWrapper.insert(DBWrapper.java:158)
    at com.yahoo.ycsb.workloads.CoreWorkload.doInsert(CoreWorkload.java:549)
    at com.yahoo.ycsb.ClientThread.run(Client.java:346)
2015-12-18 05:29:26:000 3 sec: 0 operations; est completion in 106751991167300 days 15 hours [CLEANUP: Count=1, Max=251, Min=251, Avg=251, 90=251, 99=251, 99.9=251, 99.99=251] [INSERT: Count=1, Max=7223, Min=7220, Avg=7222, 90=7223, 99=7223, 99.9=7223, 99.99=7223] 
[OVERALL], RunTime(ms), 3528.0
[OVERALL], Throughput(ops/sec), 0.0
[CLEANUP], Operations, 1.0
[CLEANUP], AverageLatency(us), 251.0
[CLEANUP], MinLatency(us), 251.0
[CLEANUP], MaxLatency(us), 251.0
[CLEANUP], 95thPercentileLatency(us), 251.0
[CLEANUP], 99thPercentileLatency(us), 251.0
[INSERT], Operations, 1.0
[INSERT], AverageLatency(us), 7222.0
[INSERT], MinLatency(us), 7220.0
[INSERT], MaxLatency(us), 7223.0
[INSERT], 95thPercentileLatency(us), 7223.0
[INSERT], 99thPercentileLatency(us), 7223.0
[INSERT], Return=ERROR, 1
Dec 18, 2015 5:29:26 AM com.orientechnologies.common.log.OLogManager log
INFO: - storage: ycsb...
Dec 18, 2015 5:29:26 AM com.orientechnologies.common.log.OLogManager log
INFO: OrientDB Engine shutdown complete
</pre></code>

**Comment by laa** [comment]
Hi, you may use our YCSB port, it has absolutely the same OrientDB client but much simpler to run and actively supported. https://github.com/laa/orientdb-ycsb-benchmark we are planning to migrate to Gradle soon. So it will be even simpler to use. Also you may merely copy paste OrientDB client to latest YCSB branch. But YCSB branch suffers from overflow problems in some cases, so I suggest  you to use our branch.

**Comment by lvca** [comment]
@laa did you send the PR to the original project?

**Comment by laa** [comment]
I may do that periodically.

**Comment by laa** [comment]
2- what is different between this two orientdb's? 
> No difference.
>3-there is a benchmark folder on "http://orientdb.com/download/" , can i use it for my benchmark?
No, it is out of dated version.
>4- if orienteDB is a multimodel Database , how to use it's dimension of document base for example?
Sorry I can not answer this question if few lines, but you may look at examples in our documentation.

**Comment by lvca** [comment]
@laa Did you already send the PR to the original project?

**Comment by laa** [comment]
Not yet, I will finish YCSB https://github.com/orientechnologies/orientdb/issues/4873 and will do.
