### ISSUE TITLE
LIMIT and SKIP not working with named parameters.

### ISSUE THREAD

**Issue by bodiam** [orientechnologies/orientdb#5493]
I'm using the following code:

```
        HashMap<String, String> params = new HashMap<String, String>();
        params.put("title", "SQL");
        params.put("limit", "10");

        return db.command(new OSQLSynchQuery<Book>("select * from Book where title = :title SKIP 20 LIMIT :limit")).execute(params)
```

but this doesn't work. It results in the following stacktrace:

```
com.orientechnologies.orient.core.sql.OCommandSQLParsingException: Error on parsing command at position #0: Error parsing query: 
select * from Book where title = :title SKIP 20 LIMIT :limit
Encountered " <LIMIT> "limit "" at line 1, column 56.
Was expecting one of:
    <TO> ...
    <VALUES> ...
    <SET> ...
    <ADD> ...
    <PUT> ...
    <MERGE> ...
    <CONTENT> ...
    <REMOVE> ...
    <ORDER> ...
    <GROUP> ...
    <OFFSET> ...
    <RECORD> ...
    <LUCENE> ...
    <NEAR> ...
    <WITHIN> ...
    <EXCEPTION> ...
    <IN> ...
    <KEY> ...
    <IDENTIFIER> ...
    <QUOTED_IDENTIFIER> ...
    <IDENTIFIER> ...
    <IN> ...
    <SET> ...
    <PUT> ...
    <ADD> ...
    <REMOVE> ...
    <MERGE> ...
    <CONTENT> ...
    <ORDER> ...
    <KEY> ...
    <OFFSET> ...
    <GROUP> ...
    <VALUES> ...
    <RECORD> ...
    <TO> ...
    <LUCENE> ...
    <NEAR> ...
    <WITHIN> ...
    <EXCEPTION> ...
    <QUOTED_IDENTIFIER> ...
    
	at com.orientechnologies.orient.core.sql.OCommandExecutorSQLAbstract.throwParsingException(OCommandExecutorSQLAbstract.java:102) ~[orientdb-core-2.1.6.jar:2.1.6]
	at com.orientechnologies.orient.core.sql.OCommandExecutorSQLAbstract.preParse(OCommandExecutorSQLAbstract.java:238) ~[orientdb-core-2.1.6.jar:2.1.6]
	at com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.parse(OCommandExecutorSQLSelect.java:218) ~[orientdb-core-2.1.6.jar:2.1.6]
	at com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.parse(OCommandExecutorSQLSelect.java:84) ~[orientdb-core-2.1.6.jar:2.1.6]
	at com.orientechnologies.orient.core.sql.OCommandExecutorSQLDelegate.parse(OCommandExecutorSQLDelegate.java:76) ~[orientdb-core-2.1.6.jar:2.1.6]
	at com.orientechnologies.orient.core.sql.OCommandExecutorSQLDelegate.parse(OCommandExecutorSQLDelegate.java:42) ~[orientdb-core-2.1.6.jar:2.1.6]
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.command(OAbstractPaginatedStorage.java:1517) ~[orientdb-core-2.1.6.jar:2.1.6]
	at com.orientechnologies.orient.core.sql.query.OSQLQuery.run(OSQLQuery.java:72) ~[orientdb-core-2.1.6.jar:2.1.6]
	at com.orientechnologies.orient.core.sql.query.OSQLSynchQuery.run(OSQLSynchQuery.java:85) ~[orientdb-core-2.1.6.jar:2.1.6]
	at com.orientechnologies.orient.core.query.OQueryAbstract.execute(OQueryAbstract.java:33) ~[orientdb-core-2.1.6.jar:2.1.6]
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.command(ONetworkProtocolBinary.java:1319) ~[na:na]
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.executeRequest(ONetworkProtocolBinary.java:396) ~[na:na]
	at com.orientechnologies.orient.server.network.protocol.binary.OBinaryNetworkProtocolAbstract.execute(OBinaryNetworkProtocolAbstract.java:223) ~[na:na]
	at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:77) ~[orientdb-core-2.1.6.jar:2.1.6]
```

I've found the following discussion, https://groups.google.com/forum/#!topic/orient-database/o4f4JEiJneo which mentions that it should be fixed since 2014, but I'm using OrientDB 2.1.5, and it doesn't seem to be fixed. Any suggestions?

**Comment by luigidellaquila** [comment]
Hi @bodiam 

It seems to be a trivial mistake in the parser, it will be fixed in next hours. The `:limit` parameter is interpreted as a reserved word.

In the meantime, you can just replace the `:limit` parameter name with another name, eg. `:lim`. 

Thanks

Luigi

**Comment by bodiam** [comment]
Hi @luigidellaquila ,

The OrientDB might not be flawless, but I truly appreciate the level of support you guys are providing. 

I tested your workaround, and it works. Nice bug :-)

Thanks!

Erik

**Comment by luigidellaquila** [comment]
Hi @bodiam 

I just pushed a fix, it will be released with 2.1.9

Thanks

Luigi

**Comment by Fraternel** [comment]
Hello @luigidellaquila 

I'm using the last **orientdb CE 2.1.9** and the exception is still raised with named parameter *:limit* (whatever the name ; *:lim*, etc.).

Trace:
```com.orientechnologies.orient.core.sql.OCommandSQLParsingException: Error on parsing command at position [...]: Invalid LIMIT value setted to ':LIMIT' but it should be a valid integer. Example: LIMIT 10```

BTW the **strictSql** is disable in database configuration.

Thanks you in advance for your response.
Fraternel.

NB: named parameter for *SKIP* is also affected

**Comment by luigidellaquila** [comment]
Hi @Fraternel 

If I'm not wrong, the implementation of LIMIT as a parameter was provided by the new parser, so if you disable it (strictSql=false) you will loose this capability. I suggest you to keep it enabled, unless you really have a huge quantity of queries to be refactored after a migration.

Thanks

Luigi

**Comment by Fraternel** [comment]
Hello back @luigidellaquila !

Ok I understand the problem. I will use the new parser (and migrate my queries from 2.0.X).

Thank you for your promptness.

Fraternel.
