### ISSUE TITLE
Cannot restore my database

### ISSUE THREAD

**Issue by bodiam** [orientechnologies/orientdb#5507]
Hi guys,

I have an issue: I cannot restore my database. I tried it with a small dump with 10 records, that works, but my actual database with 100.000 records doesn't. I'm using OrientDB 2.1.5 community. Thanks!

```
orientdb {db=BestProgrammingBooks}> IMPORT DATABASE /Users/erikp/Userfiles/projects/bestprogrammingbooks/db/orientdb/2015-12-17.zip

Importing database DATABASE /Users/erikp/Userfiles/projects/bestprogrammingbooks/db/orientdb/2015-12-17.zip...
Started import of database 'plocal:../databases/BestProgrammingBooks' from /Users/erikp/Userfiles/projects/bestprogrammingbooks/db/orientdb/2015-12-17.zip...
Non merge mode (-merge=false): removing all default non security classes
Removed 0 classes.Error on database import happened just before line 299, column 444
java.lang.NumberFormatException: For input string: "22Vp"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Integer.parseInt(Integer.java:580)
	at com.orientechnologies.orient.core.serialization.serializer.OJSONReader.nextChar(OJSONReader.java:273)
	at com.orientechnologies.orient.core.serialization.serializer.OJSONReader.readNext(OJSONReader.java:174)
	at com.orientechnologies.orient.core.serialization.serializer.OJSONReader.readString(OJSONReader.java:92)
	at com.orientechnologies.orient.core.serialization.serializer.OJSONReader.readString(OJSONReader.java:87)
	at com.orientechnologies.orient.core.serialization.serializer.OJSONReader.readString(OJSONReader.java:83)
	at com.orientechnologies.orient.core.db.tool.ODatabaseImport.importDatabase(ODatabaseImport.java:423)
	at com.orientechnologies.orient.console.OConsoleDatabaseApp.importDatabase(OConsoleDatabaseApp.java:1711)
	at com.orientechnologies.orient.graph.console.OGremlinConsole.importDatabase(OGremlinConsole.java:126)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.orientechnologies.common.console.OConsoleApplication.execute(OConsoleApplication.java:392)
	at com.orientechnologies.common.console.OConsoleApplication.executeCommands(OConsoleApplication.java:253)
	at com.orientechnologies.common.console.OConsoleApplication.run(OConsoleApplication.java:142)
	at com.orientechnologies.orient.graph.console.OGremlinConsole.main(OGremlinConsole.java:64)

Error: com.orientechnologies.orient.core.db.tool.ODatabaseExportException: Error on importing database 'BestProgrammingBooks' from file: /Users/erikp/Userfiles/projects/bestprogrammingbooks/db/orientdb/2015-12-17.zip

Error: java.lang.NumberFormatException: For input string: "22Vp"
```

**Comment by maggiolo00** [comment]
hi @bodiam 

did you export from 2.1.5 and import into 2.1.5?

**Comment by bodiam** [comment]
Hi @maggiolo00 , yes, I did, 2.1.5 is the only version I have.

**Comment by maggiolo00** [comment]
how big is the export?
can you send it to me at e.risa@orientdb.com ?

Thanks 
Enrico

**Comment by bodiam** [comment]
Done

**Comment by lvca** [comment]
Did you export or have you executed a backup?

**Comment by bodiam** [comment]
Hi Luca,

Not sure what you mean? Yes, I created a backup, and I did it using the
backup.sh script.

Erik

**Comment by lvca** [comment]
You should use `RESTORE DATABASE` instead of `IMPORT DATABASE` if you did a backup.
