### ISSUE TITLE
2.1.8 java.lang.OutOfMemoryError: null

### ISSUE THREAD

**Issue by valenpo** [orientechnologies/orientdb#5521]
Hello every one! 
After upgrade library from 2.1.5 -> 2.1.8 we get OOM exception and application quit. 

We use 130GB server with 40G heap + other RAM for lucene indexes etc... 

```
Caused by: java.lang.OutOfMemoryError: null
	at sun.misc.Unsafe.allocateMemory(Native Method) ~[na:1.8.0_66]
	at com.orientechnologies.common.directmemory.OUnsafeMemory.allocate(OUnsafeMemory.java:85) ~[orientdb-core-2.1.8.jar:2.1.8]
	at com.orientechnologies.common.directmemory.OUntrackedDirectMemoryPointer.<init>(OUntrackedDirectMemoryPointer.java:75) ~[orientdb-core-2.1.8.jar:2.1.8]
	at com.orientechnologies.common.directmemory.ODirectMemoryPointerFactory.createPointer(ODirectMemoryPointerFactory.java:115) ~[orientdb-core-2.1.8.jar:2.1.8]
	at com.orientechnologies.orient.core.storage.cache.local.OWOWCache.cacheFileContent(OWOWCache.java:1202) ~[orientdb-core-2.1.8.jar:2.1.8]
	at com.orientechnologies.orient.core.storage.cache.local.OWOWCache.load(OWOWCache.java:596) ~[orientdb-core-2.1.8.jar:2.1.8]
	at com.orientechnologies.orient.core.storage.cache.local.O2QCache.updateCache(O2QCache.java:794) ~[orientdb-core-2.1.8.jar:2.1.8]
	at com.orientechnologies.orient.core.storage.cache.local.O2QCache.doLoad(O2QCache.java:364) ~[orientdb-core-2.1.8.jar:2.1.8]
	at com.orientechnologies.orient.core.storage.cache.local.O2QCache.load(O2QCache.java:327) ~[orientdb-core-2.1.8.jar:2.1.8]
	at com.orientechnologies.orient.core.storage.impl.local.paginated.base.ODurableComponent.loadPage(ODurableComponent.java:131) ~[orientdb-core-2.1.8.jar:2.1.8]
	at com.orientechnologies.orient.core.storage.impl.local.paginated.OPaginatedCluster.readRecord(OPaginatedCluster.java:551) ~[orientdb-core-2.1.8.jar:2.1.8]
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.doReadRecord(OAbstractPaginatedStorage.java:2152) ~[orientdb-core-2.1.8.jar:2.1.8]
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.readRecord(OAbstractPaginatedStorage.java:1879) ~[orientdb-core-2.1.8.jar:2.1.8]
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.readRecord(OAbstractPaginatedStorage.java:851) ~[orientdb-core-2.1.8.jar:2.1.8]
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx$SimpleRecordReader.readRecord(ODatabaseDocumentTx.java:3224) ~[orientdb-core-2.1.8.jar:2.1.8]
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.executeReadRecord(ODatabaseDocumentTx.java:1844) ~[orientdb-core-2.1.8.jar:2.1.8]
	... 19 common frames omitted
```

**Comment by laa** [comment]
Valentin, you use Solaris OS, that is known problem with Solaris memory settings.

**Comment by valenpo** [comment]
Andrey, thanks! 

Any recommendation of solving such problem? Or just downgrade to ODB 2.1.5?

Regards,
Valentin.

**Comment by laa** [comment]
@valenpo could  you downgrade a bit and wait for 2.2 release we have to implement new memory management there, if it is successful it will be ported to next 2.1 release.

**Comment by laa** [comment]
Did you have a chance to try it on 2.2 rc1 ?

**Comment by laa** [comment]
Close issue because of no reply. If you reproduce given issue and have information which is requested in issue feel free to reopen it.
