### ISSUE TITLE
OrientDB generates CUSTOM field type instead of LINK

### ISSUE THREAD

**Issue by maseev** [orientechnologies/orientdb#5525]
It looks like you guys lost some code related to that ticket https://github.com/orientechnologies/orientdb/issues/3604. I can't find it in the current code repository version. Have a look at this test [method](https://github.com/maseev/orient/blob/master/src/test/java/orientdb/OrientDbTest.java#L109). 

You can run it with ``` mvn test -Dtest=orientdb.OrientDbTest#linkToSingleEntityShouldWorkWithoutExceptions ``` and you'd get an exception, because the Person class is empty. Notice, Person class implements the Serializable interface. Try to remove it and run the test again - everything would work just fine.

The problem is lurking somewhere [here](https://github.com/orientechnologies/orientdb/blob/7e6e319fa04378c3b02c1ecc6bb49adb89aef457/object/src/main/java/com/orientechnologies/orient/object/metadata/schema/OSchemaProxyObject.java#L303). Because Person class is registered after Citizen class, OrientDB can't find it through the entityManager and because Person is implementing the Serializable interface, the result type remains CUSTOM, but it has to be LINK.

**Comment by tglman** [comment]
Hi @maseev ,

I tryed to reproduce your problem but i couldn't
i sow another test failing i nthe same suite and i fixed it:
```
@Test
  public void registeringABrokenEntityShouldThrowAnException() {
    try (OObjectDatabaseTx db = new OObjectDatabaseTx(pool.acquire())) {
      db.setAutomaticSchemaGeneration(true);
      OEntityManager entityManager = db.getEntityManager();

      Stream.of(Cluster.class, BrokenEntity.class)
          .forEach(clazz -> {
            db.getMetadata().getSchema().generateSchema(clazz);
            entityManager.registerEntityClass(clazz);
          });

      db.getMetadata().getSchema().synchronizeSchema();

      final String queryCluster =
          "SELECT FROM `" + Cluster.class.getSimpleName()+"`";
      final String queryBrokenEntity =
          "SELECT FROM " + BrokenEntity.class.getSimpleName() + " WHERE `cluster` = ?";

      db.command(new OSQLSynchQuery<List<Cluster>>(queryCluster)).execute();
      db.command(new OSQLSynchQuery<List<BrokenEntity>>(queryBrokenEntity)).execute("test");
    }
  }
```

by the way with 2.2.0-beta all the tests pass, fixed this one

**Comment by maseev** [comment]
Hi @tglman. Try to run just a single test which I mentioned earlier. Here's what I get when I run it:

```
maseev@evilmachine:~/projects/orient$ mvn clean test -Dtest=orientdb.OrientDbTest#linkToSingleEntityShouldWorkWithoutExceptions
[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building orientdb 1.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ orientdb ---
[INFO] Deleting /home/maseev/projects/orient/target
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ orientdb ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /home/maseev/projects/orient/src/main/resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.3:compile (default-compile) @ orientdb ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 8 source files to /home/maseev/projects/orient/target/classes
[INFO] 
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ orientdb ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /home/maseev/projects/orient/src/test/resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.3:testCompile (default-testCompile) @ orientdb ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 1 source file to /home/maseev/projects/orient/target/test-classes
[INFO] 
[INFO] --- maven-surefire-plugin:2.18:test (default-test) @ orientdb ---
[INFO] Surefire report directory: /home/maseev/projects/orient/target/surefire-reports

-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running orientdb.OrientDbTest
Feb 25, 2016 2:20:58 PM com.orientechnologies.common.log.OLogManager log
INFO: OrientDB auto-config DISKCACHE=10,342MB (heap=3,541MB os=15,931MB disk=35,864MB)
Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 2.409 sec <<< FAILURE! - in orientdb.OrientDbTest
linkToSingleEntityShouldWorkWithoutExceptions(orientdb.OrientDbTest)  Time elapsed: 0.123 sec  <<< FAILURE!
java.lang.AssertionError: The Person class doesn't have any records
        at org.junit.Assert.fail(Assert.java:88)
        at org.junit.Assert.assertTrue(Assert.java:41)
        at orientdb.OrientDbTest.linkToSingleEntityShouldWorkWithoutExceptions(OrientDbTest.java:115)

Feb 25, 2016 2:20:59 PM com.orientechnologies.common.log.OLogManager log
INFO: {db=tmpdb} - closing storage: tmpdb...

Results :

Failed tests: 
  OrientDbTest.linkToSingleEntityShouldWorkWithoutExceptions:115 The Person class doesn't have any records



Tests run: 1, Failures: 1, Errors: 0, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 8.190 s
[INFO] Finished at: 2016-02-25T14:20:59+06:00
[INFO] Final Memory: 16M/214M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.18:test (default-test) on project orientdb: There are test failures.
[ERROR] 
[ERROR] Please refer to /home/maseev/projects/orient/target/surefire-reports for the individual test results.
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
maseev@evilmachine:~/projects/orient$
```

**P.S.** I just tried to run this test against OrientDB 2.2.0-beta and it seems working without any exceptions. I hope you guys add some tests that cover this use case in order to avoid any regression in the future.

**Comment by maseev** [comment]
@tglman Shall we close this issue since it's fixed in the 2.2.0-beta version?

**Comment by maseev** [comment]
@tglman About that unit test which you fixed - great, but it's a workaround, not a complete solution to the problem. I created another issue #5537 that related to this test.

**Comment by tglman** [comment]
yes, closing
