### ISSUE TITLE
One cluster can't handle more than one class

### ISSUE THREAD

**Issue by maseev** [orientechnologies/orientdb#5530]
I think I've found another bug related to the cluster notion.

Here's the stack trace:

```
com.orientechnologies.orient.core.exception.OSchemaException: Cluster with id 16 already belongs to class Human
	at com.orientechnologies.orient.core.metadata.schema.OSchemaShared.checkClusterCanBeAdded(OSchemaShared.java:485)
	at com.orientechnologies.orient.core.metadata.schema.OClassImpl.addClusterIdInternal(OClassImpl.java:2114)
	at com.orientechnologies.orient.core.metadata.schema.OClassImpl.addCluster(OClassImpl.java:1079)
	at orientdb.OrientDbTest.lambda$addingClassesToTheClusterShouldWorkWithoutExceptions$3(OrientDbTest.java:133)
	at orientdb.OrientDbTest$$Lambda$2/1269773610.accept(Unknown Source)
	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580)
	at orientdb.OrientDbTest.addingClassesToTheClusterShouldWorkWithoutExceptions(OrientDbTest.java:131)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:78)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:212)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:68)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:140)
```

And here's the test [method](https://github.com/maseev/orient/blob/master/src/test/java/orientdb/OrientDbTest.java#L123). You can run it with ``` mvn test -Dtest=orientdb.OrientDbTest#addingClassesToTheClusterShouldWorkWithoutExceptions ```.
I expected that OrientDB could handle this use case, but it couldn't. What I'm trying to do is to attach two classes to the single cluster so I'd be able to query each of them by, like so:

```
SELECT FROM CLUSTER:<cluster_name> WHERE @class = <class>
```

or truncate all records from the particular cluster:

```
TRUNCATE CLUSTER <cluster_name>
```

**Comment by maggiolo00** [comment]
hi @maseev 
from OrientDB 2.0 is not possible to have two classes in one cluster.
See here
http://orientdb.com/docs/2.0/orientdb.wiki/Concepts.html#class

**Comment by maseev** [comment]
So, If I understood you correctly, you mean I have to attach a base class to the Cluster and then save all objects which would have some derivative types by specifying the cluster name, right?

**Comment by maggiolo00** [comment]
You shouldn't attach classes to clusters. 
The engine does that job for you.
You should only create classes and inheritance between them.

For your example i see that you have model

Human
Person
Employee
Citizen

You can just let 
Employee extends Human.
Citizen extends Human

Then you can do this query

```select from Human where @class = <class>```

or if you are interested only in Employee

```select from Employee```

**Comment by maseev** [comment]
Now I see what you mean. Unfortunately, this isn't my case. What I'm trying to do is to logically separate data among let say, different users. So, for example, we'd have a Human class and an Employee class. The Employee class extends the Human class. Now I'd like to separate two records of class Employee from each other. If I could attach more than one class to a single cluster that would have resolved my problem. I would simply query the Employee class like that:

```
select from cluster:<cluster> where @class = <class>
```

But now I have to add some id field that would be used instead of this thing with clusters.

**Comment by smolinari** [comment]
> Now I'd like to separate two records of class Employee from each other.

Can you explain what this means a bit more? 

Scott

**Comment by maggiolo00** [comment]
@maseev  if you want to separate records of Employee class you can
use multiple clusters.

**Comment by maseev** [comment]
It simply means that one user can only see only a subset of data. At first, I thought that I could solve this problem by creating this cluster for each user and attaching classes to them, but it turned out that OrientDB doesn't work that way.

**Comment by maseev** [comment]
@maggiolo00 I would have to create a cluster for each entity class that is used in my application. Isn't it a waste of space?

**Comment by smolinari** [comment]
So, you are trying to create a form of multi-tenancy? 

Scott

**Comment by maggiolo00** [comment]
@maseev 
OrientDB has limits on cluster number (32,767)
http://orientdb.com/docs/2.1/Limits.html#limits
Maybe is not eh better strategy. If you want to allow a user to see a subset of data you could use Record level Security
http://orientdb.com/docs/2.1/Database-Security.html

**Comment by maseev** [comment]
@smolinari yep, that's correct.

**Comment by maseev** [comment]
I think I'll try the approach with the id field that would describe a specific user to which an entity belongs.
So I could query a specific class by specifying an additional id field like so:

```
select from <class> where user_id = <id>
```

**Comment by smolinari** [comment]
Ok. You might be better off using a tenant-id.

The other choice is using the record level security that @maggiolo00 mentioned. 

http://orientdb.com/docs/2.1/Database-Security.html#record-level-security

That means you give your tenants their own user to access the database and ODB will take care of the rest.  

Scott

**Comment by maseev** [comment]
@smolinari, @maggiolo00 Ok, I'll have a look. Thank you guys for your help. I think we can close this ticket.

**Comment by smolinari** [comment]
You can close it yourself. :smile: Look next to the Comment button.

Scott

**Comment by maseev** [comment]
Oh snap! You're right :laughing:
