### ISSUE TITLE
orientdb-workbench-2.1.6 cannot started

### ISSUE THREAD

**Issue by anutech2001** [orientechnologies/orientdb#5554]
When i tried to start a workbench 2.1.6 it show these error. Any help please.

2559-01-05 16:42:32:955 INFO  OrientDB auto-config DISKCACHE=4,302MB (heap=1,815MB os=8,166MB disk=8,237MB) [orientechnologies]
2559-01-05 16:42:33:028 INFO  Loading configuration from: D:/orientdb-workbench-2.1.6/config/workbench-config.xml... [OServerConfigurationLoaderXml]
2559-01-05 16:42:33:185 INFO  OrientDB Server v2.1.6 (build @BUILD@) is starting up... [OServer]
2559-01-05 16:42:33:189 INFO  Databases directory: D:\orientdb-workbench-2.1.6\databases [OServer]
2559-01-05 16:42:33:203 INFO  Listening http connections on 0.0.0.0:2491 (protocol v.10, socket=default) [OServerNetworkListener]
2559-01-05 16:42:33:208 INFO  Installing dynamic plugin 'orientdb-workbench.jar'... [OServerPluginManager]Error on installing dynamic plugin 'workbench'
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.orientechnologies.orient.server.plugin.OServerPluginManager.startPluginClass(OServerPluginManager.java:272)
	at com.orientechnologies.orient.server.plugin.OServerPluginManager.installDynamicPlugin(OServerPluginManager.java:352)
	at com.orientechnologies.orient.server.plugin.OServerPluginManager.updatePlugin(OServerPluginManager.java:202)
	at com.orientechnologies.orient.server.plugin.OServerPluginManager.updatePlugins(OServerPluginManager.java:292)
	at com.orientechnologies.orient.server.plugin.OServerPluginManager.startup(OServerPluginManager.java:93)
	at com.orientechnologies.orient.server.OServer.registerPlugins(OServer.java:939)
	at com.orientechnologies.orient.server.OServer.activate(OServer.java:346)
	at com.orientechnologies.orient.server.OServerMain.main(OServerMain.java:41)
Caused by: com.orientechnologies.orient.core.exception.OSecurityAccessException: User or password not valid for database: 'monitor'
	at com.orientechnologies.orient.core.metadata.security.OSecurityShared.authenticate(OSecurityShared.java:165)
	at com.orientechnologies.orient.core.metadata.security.OSecurityProxy.authenticate(OSecurityProxy.java:87)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.open(ODatabaseDocumentTx.java:268)
	at com.orientechnologies.workbench.OWorkbenchPlugin.loadConfiguration(OWorkbenchPlugin.java:294)
	at com.orientechnologies.workbench.OWorkbenchPlugin.startup(OWorkbenchPlugin.java:133)
	... 12 more

Thanks in advance,
Anurak

**Comment by maggiolo00** [comment]
hi @anutech2001 

Is it first run?

**Comment by anutech2001** [comment]
hi,
   Yes, it is.

**Comment by maggiolo00** [comment]
Can you try to drop the folder `monitor` under databases in the WB distribution  and restart it?

**Comment by anutech2001** [comment]
hi @maggiolo00,
       It's work now after follow your suggestion. Thanks you. I have another 2 questions.
   1. I saw from some document that WB need jdk 6 and later, but I found that WB 2.1.6 need jdk 8 because some of jdk api that it used is a jdk 8 version. So, can you confirmed about the jdk version for WB?
    2. When I tried to stop WB with stop-workbence.bat, it show "Error: null" and the server didn't stop(I already attached the screen). So, I need to press ctrl-c on the server command prompt. Any suggestion?

regrads,
Anurak
    
![stop_orientdb_wb_log](https://cloud.githubusercontent.com/assets/16556054/12132836/463474aa-b452-11e5-80dd-7182635067f9.jpg)

**Comment by maggiolo00** [comment]
hi @anutech2001 

about shutdown we have an open issue about that
https://github.com/orientechnologies/orientdb/issues/4698

**Comment by lvca** [comment]
Workbench has been replaced by the Enhanced Studio in v2.2. Closing it.
