### ISSUE TITLE
OIndexRemote.iterateEntriesMajor() UnsupportedOperationException

### ISSUE THREAD

**Issue by kruthar** [orientechnologies/orientdb#5578]
In a nutshell I am trying to iterate over entries in an ODictionary with the Java API. I had no problems doing this when using a local plocal or memory connection. When I attempted to use a remote connection to a database server on a different machine I ran into issues.

Here is an example of what I am trying to do:

```
ODatabaseDocumentTx db = new ODatabaseDocumentTx("remote:orientdb.vagrant/home/vagrant/test").open(user, password);
ODictionary<ORecord> dictionary = db.getDictionary();
OIndexCursor entries = dictionary.getIndex().iterateEntriesMajor(startkey, true, true);
```

Seeing errors like this:

```
java.lang.UnsupportedOperationException: iterateEntriesMajor
	at com.orientechnologies.orient.core.index.OIndexRemote.iterateEntriesMajor(OIndexRemote.java:344)
	at com.yahoo.ycsb.db.OrientDBClient.scan(OrientDBClient.java:268)
	at com.yahoo.ycsb.DBWrapper.scan(DBWrapper.java:148)
	at com.yahoo.ycsb.workloads.CoreWorkload.doTransactionScan(CoreWorkload.java:763)
	at com.yahoo.ycsb.workloads.CoreWorkload.doTransaction(CoreWorkload.java:622)
	at com.yahoo.ycsb.ClientThread.run(Client.java:329)
```

The iterator methods are, in fact, Unsupported: https://github.com/orientechnologies/orientdb/blob/master/core/src/main/java/com/orientechnologies/orient/core/index/OIndexRemote.java#L342-L345. So, my question is, is that by design? Why are the iterator methods over a remote connection not supported? Thanks a lot.

**Comment by tglman** [comment]
hi,

This is on purpose, there are certain API not supported in remote, probably for this cases should be need to use some more high level API.

Regards

**Comment by gsbomrel** [comment]
> hi,
> 
> This is on purpose, there are certain API not supported in remote, probably for this cases should be need to use some more high level API.
> 
> Regards

@tglman san, Can you please let me know what are other some more high level APIs that can be used instead of iterateEntriesMajor ?

**Comment by andrii0lomakin** [comment]
Hi  @msbomrel2020 , you should use SQL queries instead. They are implicitly using indexes under the hood.
