### ISSUE TITLE
'Cannot serialize record' over 'ONetworkProtocolBinary': 'Error on unmarshalling record'

### ISSUE THREAD

**Issue by neRok00** [orientechnologies/orientdb#5579]
Some queries that I am running via pyorient (python driver via the binary protocal) are causing the error below in the server console (the error is happening in orientdb, not pyorient). I can reproduce this with the following clean database and orientdb version 2.1.9.

    create Vertex V
    create Vertex V
    create Edge E from #9:0 to #9:1

Performing the following query via pyorient causes the error in the server console seen at the bottom. 

    SELECT expand(unionall($foo, $bar)) LET
    $foo = (SELECT *, $bar as bar FROM #9:0 LET $bar = (SELECT expand(out('E')) FROM $current)),
    $bar = (SELECT *, $baz as baz FROM (select expand(bar) from $foo) LET $baz = (SELECT expand(in('E')) FROM $current))

Note this query runs fine in Studio, and in fact it works via pyorient if you `expand($foo)` or `expand($bar)` instead of `expand(unionall($foo, $bar))`.

    2016-01-11 13:25:48:156 WARNI {db=gittest} Cannot serialize record: V#9:1{in_:[#9:0],baz:[1]} v2 [ONetworkProtocolBinary]{db=gittest} Error on unmarshalling record #9:1 (com.orientechnologies.orient.c
    ore.exception.ODatabaseException: Impossible save a record during network serialization)
    com.orientechnologies.orient.core.exception.ODatabaseException: Impossible save a record during network serialization
            at com.orientechnologies.orient.core.serialization.serializer.record.string.ORecordSerializerCSVAbstract.linkToStream(ORecordSerializerCSVAbstract.java:125)
            at com.orientechnologies.orient.core.serialization.serializer.record.string.ORecordSerializerCSVAbstract.fieldToStream(ORecordSerializerCSVAbstract.java:418)
            at com.orientechnologies.orient.core.serialization.serializer.record.string.ORecordSerializerSchemaAware2CSV.toString(ORecordSerializerSchemaAware2CSV.java:506)
            at com.orientechnologies.orient.core.serialization.serializer.record.string.ORecordSerializerStringAbstract.toStream(ORecordSerializerStringAbstract.java:689)
            at com.orientechnologies.orient.core.serialization.serializer.record.string.ORecordSerializerSchemaAware2CSV.toStream(ORecordSerializerSchemaAware2CSV.java:268)
            at com.orientechnologies.orient.core.record.impl.ODocument.toStream(ODocument.java:2290)
            at com.orientechnologies.orient.core.record.impl.ODocument.toStream(ODocument.java:671)
            at com.orientechnologies.orient.server.network.protocol.binary.OBinaryNetworkProtocolAbstract.getRecordBytes(OBinaryNetworkProtocolAbstract.java:432)
            at com.orientechnologies.orient.server.network.protocol.binary.OBinaryNetworkProtocolAbstract.writeRecord(OBinaryNetworkProtocolAbstract.java:451)
            at com.orientechnologies.orient.server.network.protocol.binary.OBinaryNetworkProtocolAbstract.writeIdentifiable(OBinaryNetworkProtocolAbstract.java:141)
            at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.serializeValue(ONetworkProtocolBinary.java:1393)
            at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.command(ONetworkProtocolBinary.java:1341)
            at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.executeRequest(ONetworkProtocolBinary.java:400)
            at com.orientechnologies.orient.server.network.protocol.binary.OBinaryNetworkProtocolAbstract.execute(OBinaryNetworkProtocolAbstract.java:223)
            at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:77)

**Comment by tglman** [comment]
the query fill a persistent document with an additional argument while serialized throw an exception, for fix this it should check that the document is not changed.

**Comment by luigidellaquila** [comment]
@tglman is this still valid?

Thanks

Luigi

**Comment by tglman** [comment]
hi,

this shoud be fixed since 2.2.x because we removed recursive serialization, going to close this.

Bye

**Comment by neRok00** [comment]
Yer, seems to be fixed now like you say.
