### ISSUE TITLE
ArrayIndexOutOfBoundsException on dropVertexType/dropClass

### ISSUE THREAD

**Issue by stdunbar** [orientechnologies/orientdb#5586]
I have a test that is failing after an upgrade from 2.0.9 to 2.1.9.  On the Java client I am getting:

    com.companyname.persistence.exception.PersistenceException: java.lang.ArrayIndexOutOfBoundsException
	    at java.lang.System.arraycopy(Native Method)
	    at com.orientechnologies.orient.core.metadata.schema.OClassImpl.removePolymorphicClusterId(OClassImpl.java:2425)
	    at com.orientechnologies.orient.core.metadata.schema.OClassImpl.removePolymorphicClusterId(OClassImpl.java:2431)
	    at com.orientechnologies.orient.core.metadata.schema.OClassImpl.removePolymorphicClusterId(OClassImpl.java:2431)
	    at com.orientechnologies.orient.core.metadata.schema.OClassImpl.removePolymorphicClusterIds(OClassImpl.java:2416)
	    at com.orientechnologies.orient.core.metadata.schema.OClassImpl.removeBaseClassInternal(OClassImpl.java:1182)
	    at com.orientechnologies.orient.core.metadata.schema.OSchemaShared.dropClassInternal(OSchemaShared.java:1167)
	    at com.orientechnologies.orient.core.metadata.schema.OSchemaShared.dropClass(OSchemaShared.java:551)
	    at com.orientechnologies.orient.core.metadata.schema.OSchemaProxy.dropClass(OSchemaProxy.java:156)
	    at com.tinkerpop.blueprints.impls.orient.OrientBaseGraph$6.call(OrientBaseGraph.java:1357)
	    at com.tinkerpop.blueprints.impls.orient.OrientBaseGraph$6.call(OrientBaseGraph.java:1354)
	    at com.tinkerpop.blueprints.impls.orient.OrientBaseGraph.executeOutsideTx(OrientBaseGraph.java:1782)
	    at com.tinkerpop.blueprints.impls.orient.OrientBaseGraph.dropVertexType(OrientBaseGraph.java:1354)

Using 2.0.9 of the client library (orientdb-graphdb and orientdb-client) does not have this issue.  Tinkerpop (blueprints-core) is at 2.6.0 for both.

This is from a unit test running in a memory database.

**Comment by stdunbar** [comment]
2.2.0-beta is also showing this issue.

**Comment by hohwille** [comment]
I faced this issue in 2.1.9. It only happens in quite specific situations and so far I could not give an instruction how to explicitly reproduce the bug.

**Comment by maggiolo00** [comment]
@stdunbar 

do you have a unit test that i can use to reproduce the issue?

**Comment by maggiolo00** [comment]
@stdunbar 
Fixed. Should be right in time for 2.1.11
