### ISSUE TITLE
NullPointerException on export and browse class on version 2.1.0

### ISSUE THREAD

**Issue by yujinlim** [orientechnologies/orientdb#5598]
I was running an export on a database and found error on when is trying to export class `user` and it happen when i try to `Browse class user` too.
I'm running on OrientDB server version is 2.1.0

```
- Cluster 'user' (id=11).....
java.lang.NullPointerException
	at com.orientechnologies.orient.core.db.record.ORecordLazySet.add(ORecordLazySet.java:131)
	at com.orientechnologies.orient.core.db.record.ORecordLazySet.add(ORecordLazySet.java:52)
	at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinaryV0.readLinkCollection(ORecordSerializerBinaryV0.java:451)
	at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinaryV0.readSingleValue(ORecordSerializerBinaryV0.java:348)
	at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinaryV0.deserialize(ORecordSerializerBinaryV0.java:193)
	at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinary.fromStream(ORecordSerializerBinary.java:74)
	at com.orientechnologies.orient.core.record.impl.ODocument.deserializeFields(ODocument.java:1774)
	at com.orientechnologies.orient.core.record.impl.ODocument.checkForFields(ODocument.java:2354)
	at com.orientechnologies.orient.core.record.impl.ODocument.fieldNames(ODocument.java:729)
	at com.orientechnologies.orient.core.fetch.OFetchHelper.processRecord(OFetchHelper.java:289)
	at com.orientechnologies.orient.core.fetch.OFetchHelper.fetch(OFetchHelper.java:82)
	at com.orientechnologies.orient.core.serialization.serializer.record.string.ORecordSerializerJSON.toString(ORecordSerializerJSON.java:338)
	at com.orientechnologies.orient.core.serialization.serializer.record.string.ORecordSerializerStringAbstract.toString(ORecordSerializerStringAbstract.java:666)
	at com.orientechnologies.orient.core.record.ORecordAbstract.toJSON(ORecordAbstract.java:192)
	at com.orientechnologies.orient.core.db.tool.ODatabaseExport.exportRecord(ODatabaseExport.java:573)
	at com.orientechnologies.orient.core.db.tool.ODatabaseExport.exportRecords(ODatabaseExport.java:201)
	at com.orientechnologies.orient.core.db.tool.ODatabaseExport.exportDatabase(ODatabaseExport.java:126)
	at com.orientechnologies.orient.console.OConsoleDatabaseApp.exportDatabase(OConsoleDatabaseApp.java:1803)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at com.orientechnologies.common.console.OConsoleApplication.execute(OConsoleApplication.java:392)
	at com.orientechnologies.common.console.OConsoleApplication.executeCommands(OConsoleApplication.java:253)
	at com.orientechnologies.common.console.OConsoleApplication.run(OConsoleApplication.java:142)
	at com.orientechnologies.orient.graph.console.OGremlinConsole.main(OGremlinConsole.java:64)
```

**Browse Class User**
```
 browse class user

Error: java.lang.NullPointerException
```

**Comment by yujinlim** [comment]
related https://github.com/orientechnologies/orientdb/issues/4632

**Comment by yujinlim** [comment]
related https://github.com/orientechnologies/orientdb/issues/4865

**Comment by tglman** [comment]
hi @yujinlim,

Like you pointed this issue was already reported, can you just update to the last 2.1 hotfix ? is already fixed there.
