### ISSUE TITLE
Parametrized Prepared Statement not works.

### ISSUE THREAD

**Issue by schernolyas** [orientechnologies/orientdb#5637]
Hi OrientDB team.

I try to do:
___________________
System.out.println("query: select from Customer where name={name}");
query = em.createNativeQuery("select from Customer where name={name}", Customer.class);
query.setParameter("name", "Ivahoe");
customers = query.getResultList();
assertFalse("Customers must be", customers.isEmpty());
______________________

But  get exception.

createNativeQuery(org.hibernate.datastore.ogm.orientdb.OrientDBTest)  Time elapsed: 0.215 sec  <<< ERROR!
com.orientechnologies.orient.core.sql.OCommandSQLParsingException: Error on parsing command at position #0: Error parsing query: 
select from Customer where name={name}
Encountered "" at line 1, column 28.
Was expecting one of:
    
	Storage URL="memory:test"
	Storage URL="memory:test"
	at com.orientechnologies.orient.core.sql.parser.OStatementCache.throwParsingException(OStatementCache.java:113)
	at com.orientechnologies.orient.core.sql.parser.OStatementCache.parse(OStatementCache.java:107)
	at com.orientechnologies.orient.core.sql.parser.OStatementCache.get(OStatementCache.java:85)
	at com.orientechnologies.orient.core.sql.parser.OStatementCache.get(OStatementCache.java:73)
	at com.orientechnologies.orient.core.sql.OCommandExecutorSQLAbstract.preParse(OCommandExecutorSQLAbstract.java:228)
	at com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.parse(OCommandExecutorSQLSelect.java:269)
	at com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.parse(OCommandExecutorSQLSelect.java:115)
	at com.orientechnologies.orient.core.sql.OCommandExecutorSQLDelegate.parse(OCommandExecutorSQLDelegate.java:58)
	at com.orientechnologies.orient.core.sql.OCommandExecutorSQLDelegate.parse(OCommandExecutorSQLDelegate.java:39)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.command(OAbstractPaginatedStorage.java:2439)
	at com.orientechnologies.orient.core.sql.query.OSQLQuery.run(OSQLQuery.java:78)
	at com.orientechnologies.orient.core.sql.query.OSQLAsynchQuery.run(OSQLAsynchQuery.java:74)
	at com.orientechnologies.orient.core.sql.query.OSQLSynchQuery.run(OSQLSynchQuery.java:85)
	at com.orientechnologies.orient.core.query.OQueryAbstract.execute(OQueryAbstract.java:33)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.query(ODatabaseDocumentTx.java:654)
	at com.orientechnologies.orient.jdbc.OrientJdbcPreparedStatement.executeQuery(OrientJdbcPreparedStatement.java:63)
	at org.hibernate.datastore.ogm.orientdb.OrientDBDialect.executeBackendQuery(OrientDBDialect.java:188)
	at org.hibernate.ogm.hibernatecore.impl.BackendCustomLoader$BackendCustomLoaderContext.executeQuery(BackendCustomLoader.java:186)
	at org.hibernate.ogm.hibernatecore.impl.BackendCustomLoader.list(BackendCustomLoader.java:86)
	at org.hibernate.loader.custom.CustomLoader.list(CustomLoader.java:336)
	at org.hibernate.ogm.hibernatecore.impl.OgmSessionImpl.listCustomQuery(OgmSessionImpl.java:261)
	at org.hibernate.ogm.hibernatecore.impl.OgmSessionImpl.list(OgmSessionImpl.java:300)
	at org.hibernate.ogm.query.impl.NoSQLQueryImpl.list(NoSQLQueryImpl.java:130)
	at org.hibernate.jpa.internal.QueryImpl.list(QueryImpl.java:593)
	at org.hibernate.jpa.internal.QueryImpl.getResultList(QueryImpl.java:470)
	at org.hibernate.datastore.ogm.orientdb.OrientDBTest.createNativeQuery(OrientDBTest.java:126)

**Comment by luigidellaquila** [comment]
Hi @schernolyas 

In OrientDB the correct syntax to pass named parameters is `:paramName`, could you please try this:

```
System.out.println("query: select from Customer where name = :name");
query = em.createNativeQuery("select from Customer where name = :name", Customer.class);
query.setParameter("name", "Ivahoe");
customers = query.getResultList();
assertFalse("Customers must be", customers.isEmpty());
```

Thanks

Luigi

**Comment by schernolyas** [comment]
Hi @luigidellaquila 

Thank you for advice. I will try to change char for mark parameter of query.

What about I ask about pull request 5622?   Silence is not good way for solve problems

**Comment by luigidellaquila** [comment]
Hi @schernolyas 

Sorry, it's in my backlog, I'll check it asap

Thanks

Luigi

**Comment by schernolyas** [comment]
Thank you, @luigidellaquila 

Please, see to files which I linked. It is simplest way.  Merging is hard.

**Comment by schernolyas** [comment]
Hi @luigidellaquila 

I tried. Works fine!  

Thank You for your advice!
