### ISSUE TITLE
[2.2.0-beta] PLocal instance crashes randomly when opening a transaction

### ISSUE THREAD

**Issue by Alan47** [orientechnologies/orientdb#5643]
Hello everyone,

we are making extensive use of the 2.2.0-beta version of OrientDB, in PLocal mode. We are quite happy with it, but there's one nasty bug that keeps popping up randomly (after about 30 minutes). The error occurs when a transaction is being opened. It's caused by a NullPointerException deep inside the OrientDB codebase. I had a look at the specific line, it appears that a Map-typed member variable is being accessed with "object.map.get(...)", but the map is null, for what reason I cannot tell.

Here's the stack trace:

```
   com.orientechnologies.orient.core.exception.ODatabaseException: Cannot open database url=plocal:/var/cache/tomcat/temp/graph/989590abeabe4e2e986038ac9515bc8a
 at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.open(ODatabaseDocumentTx.java:276) ~[orientdb-core-2.2.0-beta.jar:2.2.0-beta]
 at com.tinkerpop.blueprints.impls.orient.OrientGraphFactory.getDatabase(OrientGraphFactory.java:132) ~[orientdb-graphdb-2.2.0-beta.jar:2.2.0-beta]
 at com.tinkerpop.blueprints.impls.orient.OrientGraphFactory.getDatabase(OrientGraphFactory.java:111) ~[orientdb-graphdb-2.2.0-beta.jar:2.2.0-beta]
 at com.tinkerpop.blueprints.impls.orient.OrientGraphFactory.getTx(OrientGraphFactory.java:71) ~[orientdb-graphdb-2.2.0-beta.jar:2.2.0-beta]
 // snip, parts of our server code
 at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) [spring-context-4.1.6.RELEASE.jar:4.1.6.RELEASE]
 at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:81) [spring-context-4.1.6.RELEASE.jar:4.1.6.RELEASE]
 at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_45]
 at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_45]
 at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [na:1.8.0_45]
 at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [na:1.8.0_45]
 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_45]
 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_45]
 at java.lang.Thread.run(Thread.java:745) [na:1.8.0_45]

Caused by: java.lang.NullPointerException: null
 at com.orientechnologies.orient.core.storage.impl.local.paginated.atomicoperations.OAtomicOperation$FileChanges.access$100(OAtomicOperation.java:454) ~[orientdb-core-2.2.0-beta.jar:2.2.0-beta]
 at com.orientechnologies.orient.core.storage.impl.local.paginated.atomicoperations.OAtomicOperation.getChangesTree(OAtomicOperation.java:181) ~[orientdb-core-2.2.0-beta.jar:2.2.0-beta]
 at com.orientechnologies.orient.core.storage.impl.local.paginated.base.ODurableComponent.getChangesTree(ODurableComponent.java:118) ~[orientdb-core-2.2.0-beta.jar:2.2.0-beta]
 at com.orientechnologies.orient.core.storage.impl.local.paginated.OPaginatedCluster.getEntries(OPaginatedCluster.java:1062) ~[orientdb-core-2.2.0-beta.jar:2.2.0-beta]
 at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.count(OAbstractPaginatedStorage.java:705) ~[orientdb-core-2.2.0-beta.jar:2.2.0-beta]
 at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.count(OAbstractPaginatedStorage.java:682) ~[orientdb-core-2.2.0-beta.jar:2.2.0-beta]
 at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.countClusterElements(ODatabaseDocumentTx.java:729) ~[orientdb-core-2.2.0-beta.jar:2.2.0-beta]
 at com.orientechnologies.orient.core.metadata.OMetadataDefault.load(OMetadataDefault.java:90) ~[orientdb-core-2.2.0-beta.jar:2.2.0-beta]
 at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.initAtFirstOpen(ODatabaseDocumentTx.java:2824) ~[orientdb-core-2.2.0-beta.jar:2.2.0-beta]
 at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.open(ODatabaseDocumentTx.java:254) ~[orientdb-core-2.2.0-beta.jar:2.2.0-beta]
... 17 common frames omitted
```

We hope that this helps.

Kind regards,

Alan

**Comment by lvca** [comment]
Could you try using 2.2.0-SNAPSHOT instead?

**Comment by Alan47** [comment]
Hi Luca, thanks for the response.
I just tried the snapshot version, on my machine it works just like the beta - I haven't been able to reproduce the stack trace from the opening post in my development environment. It seems that the error only occurs after prolonged use / lifetime of the process, which causes problems for us in production. Unfortunately I don't think that I can convince my team to deploy a snapshot version of a library on a production server... the stack trace is all I can offer for now, sadly. Sorry about that.

**Comment by smolinari** [comment]
But, you are using the beta in production? :smile: 

Scott

**Comment by Alan47** [comment]
We got far better performance from 2.2.0-beta, and things were working fine.

**Comment by lvca** [comment]
@Alan47 if this happens again, could you please post the stack trace with last 2.2.0-SNAPSHOT, so we can easily isolate the problem?

**Comment by smolinari** [comment]
> We got far better performance from 2.2.0-beta, and things were working fine.

Good to hear the beta has better performance. Still, the current snapshot is of 2.2.0 beta, just with the newest changes. If you can risk using the beta to begin with, you can certainly risk using the newest version of the beta, especially if it might solve any problems. 

Scott

**Comment by lvca** [comment]
I'm closing this issue because of no response since a while. In case the issue is still valid, please reopen/comment this. Thanks.
