### ISSUE TITLE
Using user-defined functions in ETL process (v 2.1.3)

### ISSUE THREAD

**Issue by christopherhex** [orientechnologies/orientdb#5651]
Hi, 

I have a JSON file containing a large array of objects (> 10.000) that I would like to import into the database using the ETL-module. I also defined a User-Defined Javascript function in OrientDB Studio that contains all the logic for adding vertices and edges. However I'm not able to access the function in the ETL module?

When using the "CODE"-transformer block, I receive the following error:
```
ETL process halted: com.orientechnologies.orient.etl.OETLProcessHaltedException: com.orientechnologies.orient.core.command.script.OCommandScriptException: Error on parsing script at position #0: Error on execution of the script
Script: monitorUpdate(input.monitor,input.tagId,input.type,input.createTS);
------^
Exception in thread "main" com.orientechnologies.orient.etl.OETLProcessHaltedException: com.orientechnologies.orient.core.command.script.OCommandScriptException: Error on parsing script at position #0: Error on execution of the script
Script: monitorUpdate(input.monitor,input.tagId,input.type,input.createTS);
------^
	at com.orientechnologies.orient.etl.OETLPipeline.execute(OETLPipeline.java:149)
	at com.orientechnologies.orient.etl.OETLProcessor.executeSequentially(OETLProcessor.java:458)
	at com.orientechnologies.orient.etl.OETLProcessor.execute(OETLProcessor.java:262)
	at com.orientechnologies.orient.etl.OETLProcessor.main(OETLProcessor.java:115)
Caused by: com.orientechnologies.orient.core.command.script.OCommandScriptException: Error on parsing script at position #0: Error on execution of the script
Script: monitorUpdate(input.monitor,input.tagId,input.type,input.createTS);
------^
	at com.orientechnologies.orient.core.command.script.OCommandExecutorScript.executeJsr223Script(OCommandExecutorScript.java:139)
	at com.orientechnologies.orient.core.command.script.OCommandExecutorScript.executeInContext(OCommandExecutorScript.java:101)
	at com.orientechnologies.orient.etl.transformer.OCodeTransformer.executeTransform(OCodeTransformer.java:75)
	at com.orientechnologies.orient.etl.transformer.OAbstractTransformer.transform(OAbstractTransformer.java:37)
	at com.orientechnologies.orient.etl.OETLPipeline.execute(OETLPipeline.java:115)
	... 3 more
Caused by: javax.script.ScriptException: ReferenceError: "monitorUpdate" is not defined in <eval> at line number 1
	at jdk.nashorn.api.scripting.NashornScriptEngine.throwAsScriptException(NashornScriptEngine.java:467)
	at jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:451)
	at jdk.nashorn.api.scripting.NashornScriptEngine.access$200(NashornScriptEngine.java:73)
	at jdk.nashorn.api.scripting.NashornScriptEngine$3.eval(NashornScriptEngine.java:507)
	at javax.script.CompiledScript.eval(CompiledScript.java:92)
	at com.orientechnologies.orient.core.command.script.OCommandExecutorScript.executeJsr223Script(OCommandExecutorScript.java:135)
	... 7 more
Caused by: <eval>:1 ReferenceError: "monitorUpdate" is not defined
	at jdk.nashorn.internal.runtime.ECMAErrors.error(ECMAErrors.java:57)
	at jdk.nashorn.internal.runtime.ECMAErrors.referenceError(ECMAErrors.java:319)
	at jdk.nashorn.internal.runtime.ECMAErrors.referenceError(ECMAErrors.java:291)
	at jdk.nashorn.internal.objects.Global.__noSuchProperty__(Global.java:1432)
	at jdk.nashorn.internal.scripts.Script$\^eval\_.:program(<eval>:1)
	at jdk.nashorn.internal.runtime.ScriptFunctionData.invoke(ScriptFunctionData.java:640)
	at jdk.nashorn.internal.runtime.ScriptFunction.invoke(ScriptFunction.java:228)
	at jdk.nashorn.internal.runtime.ScriptRuntime.apply(ScriptRuntime.java:393)
	at jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:446)
	... 11 more
```

I thought a possible workaround might be to use the "COMMAND"-block, and execute the following command:
```
select monitorUpdate(${input.monitor},${input.tagId},${input.type},${input.createTS})
```
But then I receive the following error:
```
com.orientechnologies.orient.core.exception.ODatabaseException: Error on saving record #-2:0
```

Any suggestions on how to use non-idempotent functions from within the ETL module?

**Comment by robfrank** [comment]
Could you please attach json config, function's code, some sample data?
