### ISSUE TITLE
distributed server in orientdb-community-2.1.9

### ISSUE THREAD

**Issue by danciui** [orientechnologies/orientdb#5653]
I am trying to set up a distributed server so my coworkers and I can share the same databases. I am using the orientdb-community-2.1.9 out of the box (no new databases or anything) and following the instructions: run dserver.sh on one of the nodes (zestar), scp the orientdb_community folder to another machine(empire), run dserver.sh on the second machine with dserver.sh still running on the first. For some reason the second machine thinks it's the first, so it's not adding itself as a new node. Everything 100% vanilla, no changes to hazelcast.xml or any of the other xml's in the config directory. When I go into orientdb-server-config.xml on the second machine and change the nodeName from zestar to empire (it was zestar because I scp'ed the whole orientdb_community) i get an error:
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
---------- [OHazelcastPlugin]
2016-01-28 11:33:25:077 INFO  [empire] Saving distributed configuration file for database 'GratefulDeadConcerts' to: /Users/ioana/Downloads/orientdb-community/databases/GratefulDeadConcerts/distributed-config.json [OHazelcastPlugin]
2016-01-28 11:33:25:087 INFO  [empire] found no previous messages in queue orientdb.node.empire.GratefulDeadConcerts.request [OHazelcastDistributedMessageService]
2016-01-28 11:33:25:566 INFO  [empire] Publishing online status for database empire.GratefulDeadConcerts... [OHazelcastDistributedDatabase]
2016-01-28 11:33:25:591 INFO  [empire] received new status empire.GratefulDeadConcerts=ONLINE [OHazelcastPlugin]
2016-01-28 11:33:25:595 INFO  [empire] class 'sung_by', creation of new local cluster 'sung_by_empire' (id=-1) [OHazelcastPlugin]
2016-01-28 11:33:25:719 SEVER [empire] error on creating cluster 'sung_by_empire' in class 'sung_by':  [OHazelcastPlugin][empire] Error on starting distributed plugin
com.orientechnologies.orient.server.distributed.ODistributedException: Error on creating cluster 'sung_by_empire' in class 'sung_by'
	at com.orientechnologies.orient.server.hazelcast.OHazelcastPlugin.installLocalClusterPerClass(OHazelcastPlugin.java:1631)
	at com.orientechnologies.orient.server.hazelcast.OHazelcastPlugin.installDbClustersForLocalNode(OHazelcastPlugin.java:1300)
	at com.orientechnologies.orient.server.hazelcast.OHazelcastPlugin.loadDistributedDatabases(OHazelcastPlugin.java:1441)
	at com.orientechnologies.orient.server.hazelcast.OHazelcastPlugin.startup(OHazelcastPlugin.java:187)
	at com.orientechnologies.orient.server.OServer.registerPlugins(OServer.java:979)
	at com.orientechnologies.orient.server.OServer.activate(OServer.java:346)
	at com.orientechnologies.orient.server.OServerMain.main(OServerMain.java:41)
Caused by: com.orientechnologies.orient.server.distributed.ODistributedException: Quorum cannot be reached because there are no nodes available
	at com.orientechnologies.orient.server.hazelcast.OHazelcastDistributedDatabase.calculateQuorum(OHazelcastDistributedDatabase.java:369)
	at com.orientechnologies.orient.server.hazelcast.OHazelcastDistributedDatabase.send2Nodes(OHazelcastDistributedDatabase.java:119)
	at com.orientechnologies.orient.server.hazelcast.OHazelcastPlugin.sendRequest(OHazelcastPlugin.java:367)
	at com.orientechnologies.orient.server.distributed.ODistributedStorage.command(ODistributedStorage.java:333)
	at com.orientechnologies.orient.server.distributed.ODistributedStorage.addCluster(ODistributedStorage.java:1334)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.addCluster(ODatabaseDocumentTx.java:1291)
	at com.orientechnologies.orient.core.metadata.schema.OClassImpl.createClusterIfNeeded(OClassImpl.java:2108)
	at com.orientechnologies.orient.core.metadata.schema.OClassImpl.addCluster(OClassImpl.java:1074)
	at com.orientechnologies.orient.server.hazelcast.OHazelcastPlugin.installLocalClusterPerClass(OHazelcastPlugin.java:1624)
	... 6 more
~~~~~~~~~~~~~~~~~~~~~~~~~~~
I am running Darwin Kernel Version 15.3.0 RELEASE_X86_64 x86_64 on both computers. 

Thank you in advance!

**Comment by lvca** [comment]
This has been already fixed in last 2.1.x.
