### ISSUE TITLE
NullPointerException on new ORecordIteratorClass if no connection

### ISSUE THREAD

**Issue by visox** [orientechnologies/orientdb#5678]
to reproduce:
```
import com.orientechnologies.orient.client.remote.OServerAdmin;
import com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx;
import com.orientechnologies.orient.core.iterator.ORecordIteratorClass;
import com.orientechnologies.orient.server.OServerMain;

public class ORecordIteratorClassNullPointerExceptionTest {
    private static String url = "remote:localhost";
    private static String user = "root";
    private static String pass = "somepass";
    private static String dbName = "db-test-failing";
    private static String dbType = "graph";
    private static String dbStorage = "memory";

    private static void createDb() throws Exception {
        new OServerAdmin(url)
            .connect(user, pass)
            .createDatabase(dbName, dbType, dbStorage).close();
    }

    private static void startServer() throws Exception { OServerMain.main(new String[0]); }
    private static void stopServer() { OServerMain.server().shutdown(); }

//config/orientdb-server-config.xml needs to be present for OServerMain

    public static void main(String [] args) throws Exception {
        startServer();
        createDb();

        ODatabaseDocumentTx db = new ODatabaseDocumentTx(url + "/" + dbName);
        db.open(user, pass);

        stopServer();

        // this will throw a NullPointerException :(
        try {
            new ORecordIteratorClass(db, db, "V", true);
        } catch (Exception e) {
            // ;(
            e.printStackTrace();
            /*
    java.lang.NullPointerException
	at com.orientechnologies.common.concur.lock.ODistributedCounter.updateCounter(ODistributedCounter.java:71)
	at com.orientechnologies.common.concur.lock.ODistributedCounter.increment(ODistributedCounter.java:45)
	at com.orientechnologies.common.concur.lock.OReadersWriterSpinLock.acquireReadLock(OReadersWriterSpinLock.java:67)
	at com.orientechnologies.orient.client.remote.OStorageRemote.getPhysicalClusterNameById(OStorageRemote.java:1559)
	at com.orientechnologies.orient.client.remote.OStorageRemoteThread.getPhysicalClusterNameById(OStorageRemoteThread.java:534)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.getClusterNameById(ODatabaseDocumentTx.java:1260)
	at com.orientechnologies.orient.core.metadata.schema.OClassImpl.readableClusters(OClassImpl.java:132)
	at com.orientechnologies.orient.core.iterator.ORecordIteratorClass.<init>(ORecordIteratorClass.java:79)
	at com.orientechnologies.orient.core.iterator.ORecordIteratorClass.<init>(ORecordIteratorClass.java:63)
	at com.orientechnologies.orient.core.iterator.ORecordIteratorClass.<init>(ORecordIteratorClass.java:53)
	at ORecordIteratorClassNullPointerExceptionTest.main(ORecordIteratorClassNullPointerExceptionTest.java:36)
             */
        }
    }
}
```

**Comment by laa** [comment]
Hi that is line 71 from distributed counter:

 counters = cts;

As you can see is is impossible to get NPE there, which version do you use ?

**Comment by visox** [comment]
Hi,

so i updated to 2.1.10 and the result is the same.
```
java.lang.NullPointerException
	at com.orientechnologies.common.concur.lock.ODistributedCounter.updateCounter(ODistributedCounter.java:71)
...
```

when i take a look into that method i see
```
private void updateCounter(long delta) {
        int hashCode = ((Integer)this.threadHashCode.get()).intValue();

        while(true) {
...
```
the problem is in the first line of that method, i can tell that `this.threadHashCode` is null

**Comment by laa** [comment]
I see now, that is because you shutdown OrientDB engine after server stop.
You should start server using following code:

OServer.create(false).startup().activate();

And all problems will be solved.

**Comment by visox** [comment]
well that worked, i get not a OException as it should be

**Comment by laa** [comment]
>  i get not a OException as it should be
Sorry I did not understand.

**Comment by visox** [comment]
sorry wrong word order + typo (i edited the post, yes a combo fail)
...
i am just saying it works now as i would expect it to work (i get a proper exception)

**Comment by laa** [comment]
OK . I am closing issue

пн, 15 Фев 2016, 0:13, Michal Lacko <notifications@github.com>:

> sorry wrong word order + typo (i edited the post, yes a combo fail)
> ...
> i am just saying it works now as i would expect it to work (i get a proper
> exception)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/orientechnologies/orientdb/issues/5678#issuecomment-183991123>
> .
>
-- 
Best regards,
Andrey Lomakin, R&D lead.
OrientDB Ltd

twitter:@Andrey_Lomakin linkedin:https://ua.linkedin.com/in/andreylomakin
