### ISSUE TITLE
Query 'Create Edge' not work by JDBC

### ISSUE THREAD

**Issue by schernolyas** [orientechnologies/orientdb#5702]
Hi!

I try to execute query "create edge owner from #25:0 to #17:0".  OrientDB throw exception:
Caused by: java.lang.ClassCastException: com.tinkerpop.blueprints.impls.orient.OrientEdge cannot be cast to com.orientechnologies.orient.core.record.impl.ODocument
        at com.orientechnologies.orient.jdbc.OrientJdbcResultSet.<init>(OrientJdbcResultSet.java:58)
        at com.orientechnologies.orient.jdbc.OrientJdbcStatement.execute(OrientJdbcStatement.java:106)
        at org.hibernate.datastore.ogm.orientdb.utils.AssociationUtil.insertAssociation(AssociationUtil.java:48)

**Comment by schernolyas** [comment]
Fixed. Use 'executeUpdate'
