### ISSUE TITLE
I cannot run distributed server

### ISSUE THREAD

**Issue by jfernandezrico** [orientechnologies/orientdb#5734]
Hello I'm new in OrientDB and I'm a bit lost. When I start my distributed server I get the next error:

```
---------- [OHazelcastPlugin]
2016-02-16 09:16:58:895 INFO  [aplicaciones97sf] Saving distributed configuration file for database 'sftech' to: D:\orientdb-enterprise-2.1.5\databases\sftech\distributed-config.json [OHazelcastPlugin]
2016-02-16 09:16:58:911 INFO  [aplicaciones97sf] found no previous messages in queue orientdb.node.aplicaciones97sf.sftech.request [OHazelcastDistributedMessageService][aplicaciones97sf] Error on starting distributed plugin
com.orientechnologies.orient.core.exception.OQueryParsingException: Error on parsing query at position #6: Error on parsing command at position #0: Error on parsing query
Query:  OUser WHERE name = "replicator" LIMIT 1
-----------^
	at com.orientechnologies.orient.core.sql.filter.OSQLTarget.<init>(OSQLTarget.java:82)
	at com.orientechnologies.orient.core.sql.OSQLEngine.parseTarget(OSQLEngine.java:442)
	at com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.parse(OCommandExecutorSQLSelect.java:236)
	at com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.parse(OCommandExecutorSQLSelect.java:84)
	at com.orientechnologies.orient.core.sql.OCommandExecutorSQLDelegate.parse(OCommandExecutorSQLDelegate.java:76)
	at com.orientechnologies.orient.core.sql.OCommandExecutorSQLDelegate.parse(OCommandExecutorSQLDelegate.java:42)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.command(OAbstractPaginatedStorage.java:1517)
	at com.orientechnologies.orient.core.sql.query.OSQLQuery.run(OSQLQuery.java:72)
	at com.orientechnologies.orient.core.sql.query.OSQLSynchQuery.run(OSQLSynchQuery.java:85)
	at com.orientechnologies.orient.core.query.OQueryAbstract.execute(OQueryAbstract.java:33)
	at com.orientechnologies.orient.core.metadata.security.OSecurityShared.getUser(OSecurityShared.java:522)
	at com.orientechnologies.orient.core.metadata.security.OSecurityShared.authenticate(OSecurityShared.java:163)
	at com.orientechnologies.orient.core.metadata.security.OSecurityProxy.authenticate(OSecurityProxy.java:87)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.open(ODatabaseDocumentTx.java:268)
	at com.orientechnologies.orient.server.OServer.openDatabase(OServer.java:732)
	at com.orientechnologies.orient.server.OServer.openDatabase(OServer.java:714)
	at com.orientechnologies.orient.server.hazelcast.ODistributedWorker.initDatabaseInstance(ODistributedWorker.java:160)
	at com.orientechnologies.orient.server.hazelcast.OHazelcastDistributedDatabase.unqueuePendingMessages(OHazelcastDistributedDatabase.java:323)
	at com.orientechnologies.orient.server.hazelcast.OHazelcastDistributedDatabase.configureDatabase(OHazelcastDistributedDatabase.java:227)
	at com.orientechnologies.orient.server.hazelcast.OHazelcastPlugin.loadDistributedDatabases(OHazelcastPlugin.java:1413)
	at com.orientechnologies.orient.server.hazelcast.OHazelcastPlugin.startup(OHazelcastPlugin.java:187)
	at com.orientechnologies.orient.server.OServer.registerPlugins(OServer.java:979)
	at com.orientechnologies.orient.server.OServer.activate(OServer.java:346)
	at com.orientechnologies.orient.server.OServerMain.main(OServerMain.java:41)
Caused by: com.orientechnologies.orient.core.exception.OCommandExecutionException: Class 'OUSER' was not found in current database
	at com.orientechnologies.orient.core.sql.filter.OSQLTarget.extractTargets(OSQLTarget.java:276)
	at com.orientechnologies.orient.core.sql.filter.OSQLTarget.<init>(OSQLTarget.java:73)
	... 23 more
```

I have the same $ORIENTDB_HOME content in both servers

I attach my config files:

[default-distributed-db-config.json.txt](https://github.com/orientechnologies/orientdb/files/132108/default-distributed-db-config.json.txt)
[hazelcast.xml.txt](https://github.com/orientechnologies/orientdb/files/132109/hazelcast.xml.txt)
[orientdb-server-config.xml.txt](https://github.com/orientechnologies/orientdb/files/132110/orientdb-server-config.xml.txt)

Thank you very much.

**Comment by jfernandezrico** [comment]
[default-distributed-db-config.json.txt](https://github.com/orientechnologies/orientdb/files/132105/default-distributed-db-config.json.txt)

[hazelcast.xml.txt](https://github.com/orientechnologies/orientdb/files/132106/hazelcast.xml.txt)
[orientdb-server-config.xml.txt](https://github.com/orientechnologies/orientdb/files/132107/orientdb-server-config.xml.txt)

**Comment by lvca** [comment]
It seems the database has no OUser class? Could you try opening the database with non-distributed OrientDB by running `server.sh` instead of `dserver.sh` from the very same directory?

**Comment by jfernandezrico** [comment]
Now I get this error
[orient-server.log0.txt](https://github.com/orientechnologies/orientdb/files/132133/orient-server.log0.txt)

**Comment by jfernandezrico** [comment]
Hello it seems that something wrong happens in my database. I think I'm going to reinstall OrientDB.

Do you know how to configurate OrientDB to make backups?

**Comment by lvca** [comment]
@jfernandezrico Have you already looked in documentation?

**Comment by jfernandezrico** [comment]
I've just recovered my backup in my new OrientDB 2.1.11 instance and the replication works fine. Thank you for your support
