### ISSUE TITLE
Error on recovering a database after crash

### ISSUE THREAD

**Issue by lvca** [orientechnologies/orientdb#5757]
```
feb 22, 2016 11:23:33 AM com.orientechnologies.common.log.OLogManager log
AVVERTENZA: $ANSI{green {db=distributed-autorestartstallednode}} Storage 'distributed-autorestartstallednode' was not closed properly. Will try to recover from write ahead log
feb 22, 2016 11:23:33 AM com.orientechnologies.common.log.OLogManager log
INFORMAZIONI: $ANSI{green {db=distributed-autorestartstallednode}} Looking for last checkpoint...
feb 22, 2016 11:23:33 AM com.orientechnologies.common.log.OLogManager log
INFORMAZIONI: $ANSI{green {db=distributed-autorestartstallednode}} FULL checkpoint found.
feb 22, 2016 11:23:33 AM com.orientechnologies.common.log.OLogManager log
INFORMAZIONI: $ANSI{green {db=distributed-autorestartstallednode}} Data restore procedure from full checkpoint is started. Restore is performed from LSN OLogSequenceNumber{segment=0, position=978873}
feb 22, 2016 11:23:33 AM com.orientechnologies.common.log.OLogManager log
AVVERTENZA: $ANSI{green {db=distributed-autorestartstallednode}} Record com.orientechnologies.orient.core.storage.impl.local.paginated.wal.OCheckpointEndRecord{lsn=OLogSequenceNumber{segment=0, position=978897}} will be skipped during data restore
feb 22, 2016 11:23:33 AM com.orientechnologies.common.log.OLogManager log
AVVERTENZA: $ANSI{green {db=distributed-autorestartstallednode}} Non tx operation was used during data modification we will need index rebuild.
feb 22, 2016 11:23:33 AM com.orientechnologies.common.log.OLogManager log
GRAVE: $ANSI{green {db=distributed-autorestartstallednode}} Data restore was paused because of exception. The rest of changes will be rolled back and WAL files will be backed up. Please report issue about this exception to bug tracker and provide WAL files which are backed up in 'wal_backup' directory.
feb 22, 2016 11:23:35 AM com.orientechnologies.common.log.OLogManager log
INFORMAZIONI: $ANSI{green {db=distributed-autorestartstallednode}} Storage data recover was completed
feb 22, 2016 11:23:35 AM com.orientechnologies.common.log.OLogManager log
GRAVE: $ANSI{green {db=distributed-autorestartstallednode}} Can not restore state of cache for storage placed under target/server0/databases/distributed-autorestartstallednode
feb 22, 2016 11:23:35 AM com.orientechnologies.common.log.OLogManager log
INFORMAZIONI: $ANSI{green {db=distributed-autorestartstallednode}} Wait till indexes restore after crash was finished.
feb 22, 2016 11:23:35 AM com.orientechnologies.common.log.OLogManager log
GRAVE: $ANSI{green {db=distributed-autorestartstallednode}} Error on removing index 'dictionary' on rebuilding. Trying removing index files (Cause: com.orientechnologies.orient.core.index.OIndexException: Engine with id -1 is not registered inside of storage
	Storage URL="plocal:target/server0/databases/distributed-autorestartstallednode")
feb 22, 2016 11:23:35 AM com.orientechnologies.common.log.OLogManager log
INFORMAZIONI: $ANSI{green {db=distributed-autorestartstallednode}} Index 'dictionary' is not automatic index and will be added as is
feb 22, 2016 11:23:35 AM com.orientechnologies.common.log.OLogManager log
INFORMAZIONI: $ANSI{green {db=distributed-autorestartstallednode}} Index 'dictionary' was added in DB index list
feb 22, 2016 11:23:35 AM com.orientechnologies.common.log.OLogManager log
GRAVE: $ANSI{green {db=distributed-autorestartstallednode}} Error on removing index 'ORole.name' on rebuilding. Trying removing index files (Cause: com.orientechnologies.orient.core.index.OIndexException: Engine with id -1 is not registered inside of storage
	Storage URL="plocal:target/server0/databases/distributed-autorestartstallednode")
feb 22, 2016 11:23:35 AM com.orientechnologies.common.log.OLogManager log
INFORMAZIONI: $ANSI{green {db=distributed-autorestartstallednode}} Start creation of index 'ORole.name'
feb 22, 2016 11:23:35 AM com.orientechnologies.common.log.OLogManager log
INFORMAZIONI: $ANSI{green {db=distributed-autorestartstallednode}} Index 'ORole.name' was successfully created and rebuild is going to be started
feb 22, 2016 11:23:35 AM com.orientechnologies.common.log.OLogManager log
INFORMAZIONI: $ANSI{green {db=distributed-autorestartstallednode}} - Rebuilding index distributed-autorestartstallednode.ORole.name (estimated 3 items)...
feb 22, 2016 11:23:35 AM com.orientechnologies.common.log.OLogManager log
INFORMAZIONI: $ANSI{green {db=distributed-autorestartstallednode}} --> OK, indexed 3 items in 5 ms
feb 22, 2016 11:23:35 AM com.orientechnologies.common.log.OLogManager log
INFORMAZIONI: $ANSI{green {db=distributed-autorestartstallednode}} Rebuild of 'ORole.name index was successfully finished
feb 22, 2016 11:23:35 AM com.orientechnologies.common.log.OLogManager log
GRAVE: $ANSI{green {db=distributed-autorestartstallednode}} Error on removing index 'OUser.name' on rebuilding. Trying removing index files (Cause: com.orientechnologies.orient.core.index.OIndexException: Engine with id -1 is not registered inside of storage
	Storage URL="plocal:target/server0/databases/distributed-autorestartstallednode")
feb 22, 2016 11:23:35 AM com.orientechnologies.common.log.OLogManager log
INFORMAZIONI: $ANSI{green {db=distributed-autorestartstallednode}} Start creation of index 'OUser.name'
feb 22, 2016 11:23:35 AM com.orientechnologies.common.log.OLogManager log
INFORMAZIONI: $ANSI{green {db=distributed-autorestartstallednode}} Index 'OUser.name' was successfully created and rebuild is going to be started
feb 22, 2016 11:23:35 AM com.orientechnologies.common.log.OLogManager log
INFORMAZIONI: $ANSI{green {db=distributed-autorestartstallednode}} - Rebuilding index distributed-autorestartstallednode.OUser.name (estimated 3 items)...
feb 22, 2016 11:23:35 AM com.orientechnologies.common.log.OLogManager log
INFORMAZIONI: $ANSI{green {db=distributed-autorestartstallednode}} --> OK, indexed 3 items in 1 ms
feb 22, 2016 11:23:35 AM com.orientechnologies.common.log.OLogManager log
INFORMAZIONI: $ANSI{green {db=distributed-autorestartstallednode}} Rebuild of 'OUser.name index was successfully finished
feb 22, 2016 11:23:35 AM com.orientechnologies.common.log.OLogManager log
GRAVE: $ANSI{green {db=distributed-autorestartstallednode}} Error on removing index 'OFunction.name' on rebuilding. Trying removing index files (Cause: com.orientechnologies.orient.core.index.OIndexException: Engine with id -1 is not registered inside of storage
	Storage URL="plocal:target/server0/databases/distributed-autorestartstallednode")
feb 22, 2016 11:23:35 AM com.orientechnologies.common.log.OLogManager log
INFORMAZIONI: $ANSI{green {db=distributed-autorestartstallednode}} Start creation of index 'OFunction.name'
feb 22, 2016 11:23:35 AM com.orientechnologies.common.log.OLogManager log
INFORMAZIONI: $ANSI{green {db=distributed-autorestartstallednode}} Index 'OFunction.name' was successfully created and rebuild is going to be started
feb 22, 2016 11:23:35 AM com.orientechnologies.common.log.OLogManager log
INFORMAZIONI: $ANSI{green {db=distributed-autorestartstallednode}} Rebuild of 'OFunction.name index was successfully finished
feb 22, 2016 11:23:35 AM com.orientechnologies.common.log.OLogManager log
GRAVE: $ANSI{green {db=distributed-autorestartstallednode}} Error on removing index 'Person.name' on rebuilding. Trying removing index files (Cause: com.orientechnologies.orient.core.index.OIndexException: Engine with id -1 is not registered inside of storage
	Storage URL="plocal:target/server0/databases/distributed-autorestartstallednode")
feb 22, 2016 11:23:35 AM com.orientechnologies.common.log.OLogManager log
GRAVE: $ANSI{green {db=distributed-autorestartstallednode}} Error during load of index 'Person.name'
com.orientechnologies.orient.core.exception.OStorageException: File with name Person.name.sbt does not exist in storage distributed-autorestartstallednode
	Storage URL="plocal:target/server0/databases/distributed-autorestartstallednode"
	at com.orientechnologies.orient.core.storage.cache.local.OWOWCache.openFile(OWOWCache.java:342)
	at com.orientechnologies.orient.core.storage.cache.local.twoq.O2QCache.openFile(O2QCache.java:203)
	at com.orientechnologies.orient.core.storage.impl.local.paginated.base.ODurableComponent.openFile(ODurableComponent.java:178)
	at com.orientechnologies.orient.core.index.sbtree.local.OSBTree.load(OSBTree.java:537)
	at com.orientechnologies.orient.core.index.engine.OSBTreeIndexEngine.load(OSBTreeIndexEngine.java:98)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.loadExternalIndexEngine(OAbstractPaginatedStorage.java:1387)
	at com.orientechnologies.orient.core.index.OIndexAbstract.loadFromConfiguration(OIndexAbstract.java:305)
	at com.orientechnologies.orient.core.index.OIndexManagerShared$RecreateIndexesTask.recreateIndex(OIndexManagerShared.java:573)
	at com.orientechnologies.orient.core.index.OIndexManagerShared$RecreateIndexesTask.recreateIndexes(OIndexManagerShared.java:531)
	at com.orientechnologies.orient.core.index.OIndexManagerShared$RecreateIndexesTask.run(OIndexManagerShared.java:512)
	at java.lang.Thread.run(Thread.java:745)

feb 22, 2016 11:23:35 AM com.orientechnologies.common.log.OLogManager log
AVVERTENZA: $ANSI{green {db=distributed-autorestartstallednode}} Cannot load index 'Person.name' rebuilt it from scratch
feb 22, 2016 11:23:35 AM com.orientechnologies.common.log.OLogManager log
INFORMAZIONI: $ANSI{green {db=distributed-autorestartstallednode}} - Rebuilding index distributed-autorestartstallednode.Person.name (estimated 4.002 items)...
feb 22, 2016 11:23:36 AM com.orientechnologies.common.log.OLogManager log
INFORMAZIONI: $ANSI{green {db=distributed-autorestartstallednode}} --> OK, indexed 4.002 items in 325 ms
feb 22, 2016 11:23:36 AM com.orientechnologies.common.log.OLogManager log
INFORMAZIONI: $ANSI{green {db=distributed-autorestartstallednode}} Start creation of index 'Person.name'
feb 22, 2016 11:23:36 AM com.orientechnologies.common.log.OLogManager log
INFORMAZIONI: $ANSI{green {db=distributed-autorestartstallednode}} Index 'Person.name' was successfully created and rebuild is going to be started
feb 22, 2016 11:23:36 AM com.orientechnologies.common.log.OLogManager log
INFORMAZIONI: $ANSI{green {db=distributed-autorestartstallednode}} - Rebuilding index distributed-autorestartstallednode.Person.name (estimated 4.002 items)...
feb 22, 2016 11:23:36 AM com.orientechnologies.common.log.OLogManager log
INFORMAZIONI: $ANSI{green {db=distributed-autorestartstallednode}} --> OK, indexed 4.002 items in 101 ms
feb 22, 2016 11:23:36 AM com.orientechnologies.common.log.OLogManager log
INFORMAZIONI: $ANSI{green {db=distributed-autorestartstallednode}} Rebuild of 'Person.name index was successfully finished
feb 22, 2016 11:23:36 AM com.orientechnologies.common.log.OLogManager log
INFORMAZIONI: $ANSI{green {db=distributed-autorestartstallednode}} 5 indexes were restored successfully, 0 errors
feb 22, 2016 11:23:36 AM com.orientechnologies.common.log.OLogManager log
INFORMAZIONI: $ANSI{green {db=distributed-autorestartstallednode}} Indexes restore after crash was finished.

com.orientechnologies.orient.core.index.sbtree.local.OSBTreeException: Error during delete of sbtree with name dictionary
	Storage URL="plocal:target/server0/databases/distributed-autorestartstallednode"
	Component Name="dictionary"

	at com.orientechnologies.orient.core.index.sbtree.local.OSBTree.delete(OSBTree.java:475)
	at com.orientechnologies.orient.core.index.engine.OSBTreeIndexEngine.delete(OSBTreeIndexEngine.java:87)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.closeIndexes(OAbstractPaginatedStorage.java:3378)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.doClose(OAbstractPaginatedStorage.java:3318)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.close(OAbstractPaginatedStorage.java:424)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.closeOnDelete(ODatabaseDocumentTx.java:2952)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.drop(ODatabaseDocumentTx.java:445)
	at com.orientechnologies.orient.server.distributed.ServerRun.createDatabase(ServerRun.java:90)
	at com.orientechnologies.orient.server.distributed.AbstractServerClusterTest.prepare(AbstractServerClusterTest.java:253)
	at com.orientechnologies.orient.server.distributed.AbstractServerClusterTest.prepare(AbstractServerClusterTest.java:238)
	at com.orientechnologies.orient.server.distributed.AbstractServerClusterTest.prepare(AbstractServerClusterTest.java:229)
	at com.orientechnologies.orient.server.distributed.AutoRestartStalledNodeTest.test(AutoRestartStalledNodeTest.java:57)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:69)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:234)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:74)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
Caused by: java.lang.NullPointerException
	at com.orientechnologies.orient.core.storage.cache.local.OWOWCache.fileNameById(OWOWCache.java:1019)
	at com.orientechnologies.orient.core.storage.impl.local.paginated.atomicoperations.OAtomicOperation.deleteFile(OAtomicOperation.java:296)
	at com.orientechnologies.orient.core.storage.impl.local.paginated.base.ODurableComponent.deleteFile(ODurableComponent.java:194)
	at com.orientechnologies.orient.core.index.sbtree.local.OSBTree.delete(OSBTree.java:464)
	... 45 more
```

**Comment by laa** [comment]
Hi @lvca according to the log "Data restore was paused because of exception. The rest of changes will be rolled back and WAL files will be backed up. Please report issue about this exception to bug tracker and provide WAL files which are backed up in 'wal_backup' directory" 
Could you provide wal_backup directory ?

**Comment by laa** [comment]
Closed because of no answer for 20 days.
