### ISSUE TITLE
Help to Create Databse and Its schema to a server (JAVA GRAPH API)

### ISSUE THREAD

**Issue by stfanbrg** [orientechnologies/orientdb#5764]
Hello,

I am starting a project and I want to create a new database with custom schema (new class of Vertex and Edge only ) using a remote server. (for my test : localhost )

Before to create the database  , I want to test if it exists but It seems I have to use OServerAdmin to test it :: 
           
           ODB exception factory.exists : Cannot check the existance of a database in a remote server. 
           Please use the console or the OServerAdmin class.

So once I had my OServerAdmin, and I checked the Database didn't exist, I create it with 
           serverAdmin.createDatabase("Test,"graph","plocal");
and I create the schema with the follwing function as described in the  Issue #2815

my code ::
          private void createVertexType(final String p_Name,final HashMap<String, OType> p_Attributs) throws RuntimeException{
    	final OrientGraph aOrientGraph = new OrientGraph(graphURL); 
		
		aOrientGraph.executeOutsideTx(new OCallable<Object, OrientBaseGraph>() {
			@Override
			public Object call(OrientBaseGraph iArgument) {	
				OrientVertexType vertex = (OrientVertexType) aOrientGraph.createVertexType(p_Name).setClusterSelection("default");
				Iterator<String> keySetIterator = p_Attributs.keySet().iterator();
				while(keySetIterator.hasNext()){ 
					String key = keySetIterator.next(); 
					vertex.createProperty(key, p_Attributs.get(key));
				} 
				
				return null;
					
				
			}
		});
		
		aOrientGraph.shutdown();
    }
    
    private void createEdgeType(final String p_Name) throws RuntimeException{
    	final OrientGraph aOrientGraph = new OrientGraph(graphURL); 
		
		aOrientGraph.executeOutsideTx(new OCallable<Object, OrientBaseGraph>() {
			@Override
			public Object call(OrientBaseGraph iArgument) {	
				aOrientGraph.createEdgeType(p_Name).setClusterSelection("default");
				return null;
					
				
			}
		});
		
		aOrientGraph.shutdown();
		
    }

After this step, if I use ServerAdmin.existsDatabase()  I have a error network like if the server is frozen : 

GRAVE: Cannot open database with url 127.0.0.1:2480/localhost:2480
com.orientechnologies.common.io.OIOException: Cannot open a connection to remote server: 127.0.0.1:2480/localhost:2480
	at com.orientechnologies.orient.client.remote.OStorageRemote.getAvailableNetwork(OStorageRemote.java:2136)
	at com.orientechnologies.orient.client.remote.OStorageRemote.openRemoteDatabase(OStorageRemote.java:1859)
	at com.orientechnologies.orient.client.remote.OStorageRemote.open(OStorageRemote.java:222)
	at com.orientechnologies.orient.client.remote.OStorageRemoteThread.open(OStorageRemoteThread.java:89)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.open(ODatabaseDocumentTx.java:252)
	at com.tinkerpop.blueprints.impls.orient.OrientGraphFactory.getDatabase(OrientGraphFactory.java:132)
	at com.tinkerpop.blueprints.impls.orient.OrientGraphFactory.drop(OrientGraphFactory.java:59)
	at com.myorpheo.logs.orientdb.OrientDBConnection.dropDatabase(OrientDBConnection.java:282)
	at com.myorpheo.logs.orientdb.OrientDB.dropDataBase(OrientDB.java:291)
	at com.myorpheo.logs.orientdb.MYGUI.dropDataBase(MYGUI.java:241)
	at com.myorpheo.logs.orientdb.MYGUI$5.actionPerformed(MYGUI.java:126)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2018)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2341)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
	at java.awt.Component.processMouseEvent(Component.java:6516)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3321)
	at java.awt.Component.processEvent(Component.java:6281)
	at java.awt.Container.processEvent(Container.java:2229)
	at java.awt.Component.dispatchEventImpl(Component.java:4872)
	at java.awt.Container.dispatchEventImpl(Container.java:2287)
	at java.awt.Component.dispatchEvent(Component.java:4698)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4832)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4492)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4422)
	at java.awt.Container.dispatchEventImpl(Container.java:2273)
	at java.awt.Window.dispatchEventImpl(Window.java:2719)
	at java.awt.Component.dispatchEvent(Component.java:4698)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:747)
	at java.awt.EventQueue.access$300(EventQueue.java:103)
	at java.awt.EventQueue$3.run(EventQueue.java:706)
	at java.awt.EventQueue$3.run(EventQueue.java:704)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:87)
	at java.awt.EventQueue$4.run(EventQueue.java:720)
	at java.awt.EventQueue$4.run(EventQueue.java:718)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:717)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:242)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:161)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:150)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:146)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:138)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:91)
Caused by: com.orientechnologies.common.io.OIOException: Error on connecting to 127.0.0.1:2480/localhost:2480
	at com.orientechnologies.orient.client.remote.ORemoteConnectionManager.createNetworkConnection(ORemoteConnectionManager.java:255)
	at com.orientechnologies.orient.client.remote.ORemoteConnectionManager$1.createNewResource(ORemoteConnectionManager.java:80)
	at com.orientechnologies.orient.client.remote.ORemoteConnectionManager$1.createNewResource(ORemoteConnectionManager.java:77)
	at com.orientechnologies.common.concur.resource.OResourcePool.getResource(OResourcePool.java:94)
	at com.orientechnologies.orient.client.remote.ORemoteConnectionManager.acquire(ORemoteConnectionManager.java:101)
	at com.orientechnologies.orient.client.remote.OStorageRemote.getAvailableNetwork(OStorageRemote.java:2123)
	... 46 more
Caused by: com.orientechnologies.orient.enterprise.channel.binary.ONetworkProtocolException: Cannot read protocol version from remote server /127.0.0.1:2480: java.net.SocketTimeoutException: Read timed out
	at com.orientechnologies.orient.enterprise.channel.binary.OChannelBinaryAsynchClient.<init>(OChannelBinaryAsynchClient.java:99)
	at com.orientechnologies.orient.client.remote.ORemoteConnectionManager.createNetworkConnection(ORemoteConnectionManager.java:242)

On the console server I can see ::
2016-02-23 13:46:39:458 INFO  {db=Test} Created database 'Test' of type 'plocal' [ONetworkProtocolBinary]
2016-02-23 13:46:57:535 SEVER Request not supported. Code: -1 [ONetworkProtocolBinary]
2016-02-23 13:46:57:537 SEVER Received unread response from /127.0.0.1:63286 probably corrupted data from the network connection. Cleared dirty data in the buffer (4 bytes): [├┐├┐├┐├┐] [OChannelBinary
Server]
2016-02-23 13:53:15:960 INFO  {db=Test4} Created database 'Test4' of type 'plocal' [ONetworkProtocolBinary]
2016-02-23 15:10:30:463 INFO  {db=Test} Created database 'Test' of type 'plocal' [ONetworkProtocolBinary]
2016-02-23 15:14:42:268 INFO  {db=Test1} Created database 'Test1' of type 'plocal' [ONetworkProtocolBinary]
2016-02-23 15:15:19:230 SEVER Request not supported. Code: -1 [ONetworkProtocolBinary]
2016-02-23 15:15:19:230 SEVER Received unread response from /127.0.0.1:54557 probably corrupted data from the network connection. Cleared dirty data in the buffer (4 bytes): [├┐├┐├┐├┐] [OChannelBinary
Server]
2016-02-23 15:18:04:236 INFO  {db=Test2} Created database 'Test2' of type 'plocal' [ONetworkProtocolBinary]
2016-02-23 15:18:45:266 SEVER Request not supported. Code: -1 [ONetworkProtocolBinary]
2016-02-23 15:18:45:266 SEVER Received unread response from /127.0.0.1:54859 probably corrupted data from the network connection. Cleared dirty data in the buffer (4 bytes): [├┐├┐├┐├┐] [OChannelBinary
Server]
2016-02-23 15:19:37:748 WARNI ->0:0:0:0:0:0:0:1: Command not found: GET.sqlProfiler/Test2 [ONetworkProtocolHttpDb]
2016-02-23 15:19:40:015 SEVER Internal server error:
com.orientechnologies.orient.core.exception.OQueryParsingException: Error on parsing query at position #8: Error on parsing command at position #0: Error on parsing query
Query:  _studio WHERE user.name = '{{username}}' AND type = 'GraphConfig'
-------------^
--> com.orientechnologies.orient.core.exception.OCommandExecutionException: Class '_STUDIO' was not found in current database [ONetworkProtocolHttpDb]
2016-02-23 15:34:09:463 INFO  {db=Test5} Created database 'Test5' of type 'plocal' [ONetworkProtocolBinary]

where is the mistake ?

**Comment by maggiolo00** [comment]
hi @stfanbrg 

do you have a test case to reproduce this issue?

**Comment by stfanbrg** [comment]
Hi, @maggiolo00 

I have  a Graphic interface and I can reproduce this issue. In my graphic interface I can select the name of the database, click on connection button. The connection will create the data base with the schema  if it is not exist. I can delete the database also. 

![image](https://cloud.githubusercontent.com/assets/14077423/13286382/58863d66-db01-11e5-9874-58346eed9bef.png)

I expect it was you ask .

**Comment by maggiolo00** [comment]
hi @stfanbrg 

are you using studio meanwhile?

**Comment by stfanbrg** [comment]
I use Orientdb-graph  2.1.6 and  orientdb server 2.1.6

**Comment by stfanbrg** [comment]
@maggiolo00 
with Version: Mars Release (4.5.0)

**Comment by maggiolo00** [comment]
How do you create a database?

For drop you should also use the OServerAdmin API

**Comment by stfanbrg** [comment]
Exists Drop and create worked .
So, it is only after the creation of the schema ::     
oServerAdmin.createDatabase(p_BdName,"Graph","plocal"); ok
createSchema() --> ok I can see on the base wit the Studio with my schema
but after this step,  oServerAdmin failed to deal with the server .  
if I do 
                oServerAdmin.close();
		oServerAdmin = null;
                oServerAdmin = new OServerAdmin(url);
		oServerAdmin.connect(p_UserName, p_UserPassword);
the communication is ok. So i think I forgot to do something with my oServerAdmin before or after the schema creation ...

**Comment by stfanbrg** [comment]
@maggiolo00 
may be it is normal because the schema change and my oServerAdmin is not updated with the new contents and I have to delete it and re-intantiate it.

**Comment by maggiolo00** [comment]
hi @stfanbrg i think there is an issue on session handling with OServerAdmin.
I've tested against the 2.2.0-beta and worked.

**Comment by stfanbrg** [comment]
Could you give me more details about Session  handling  (rules )?

**Comment by stfanbrg** [comment]
this page http://orientdb.com/docs/2.0/orientdb.wiki/Server-Management-Java.html do no reference about sesssion .

**Comment by maggiolo00** [comment]
hi @stfanbrg  i think it is not your issue.

When you connect as ServerAdmin you get a session id that can be used to do admin task as create drop database.

Then you connect with OrientGraphFactory and get another session id associated with the user that you typed.

I think when you make the second OServerAdmin request it gets the wrong sessionid from the ThreadLocal.

BTW here there is an explanation on Multithreading 

http://orientdb.com/docs/2.1/Java-Multi-Threading.html

@tglman WDTY about this exception?

**Comment by maggiolo00** [comment]
I think the problem is due the usage in the same thread of
OrientGraphFactory
and 
OServerAdmin

**Comment by stfanbrg** [comment]
@maggiolo00 

So, if I understand, I have to manage my factory (for create the schema)  and my ServerAdmin in two differents thread. right ?

**Comment by maggiolo00** [comment]
@stfanbrg 
If you can make this test, you should not see that exception.

Do you get that exception on server right?

**Comment by maggiolo00** [comment]
Seems that the client is trying to open a connection to 2480

That is strange. The binary port is 2424

**Comment by stfanbrg** [comment]
@maggiolo00 

port number 2424 vs 2480 : I missed this information ... so I didn't use the port number may be i should.
the exception is throw by my OServerAdmin object in my code and  the server shows in the console a problem of network. 

I will try to understand multi-threading and i will inform you of the result.

**Comment by maggiolo00** [comment]
@stfanbrg 

if you do not specity it the dafault is used(2424)
2480 is the default for http

What seems strange is this url in the exception

127.0.0.1:2480/localhost:2480

**Comment by stfanbrg** [comment]
scince yesterday i removed the port number from the URL of the factory. I didn't check if the mistake :: Cannot open database with url 127.0.0.1:2480/localhost:2480 is always presents, but the issue about OserverAdmin yes .
