### ISSUE TITLE
Root password problem

### ISSUE THREAD

**Issue by lucevers** [orientechnologies/orientdb#5769]
A star (*) is visible before configuring the password!
Root password [BLANK=auto generate it]: *

After introducing the root password I got the message below:

Exception in thread "main" com.orientechnologies.orient.core.exception.OSecurityException: Cannot create a key with 'PBKDF2WithHmacSHA1' algorithm
	at com.orientechnologies.orient.core.security.OSecurityManager.getPbkdf2(OSecurityManager.java:235)
	at com.orientechnologies.orient.core.security.OSecurityManager.createHashWithSalt(OSecurityManager.java:185)
	at com.orientechnologies.orient.core.security.OSecurityManager.createHash(OSecurityManager.java:150)
	at com.orientechnologies.orient.server.OServer.addUser(OServer.java:781)
	at com.orientechnologies.orient.server.OServer.createDefaultServerUsers(OServer.java:1049)
	at com.orientechnologies.orient.server.OServer.loadUsers(OServer.java:922)
	at com.orientechnologies.orient.server.OServer.activate(OServer.java:354)
	at com.orientechnologies.orient.server.OServerMain.main(OServerMain.java:41)
Caused by: java.security.NoSuchAlgorithmException: PBKDF2WithHmacSHA256 SecretKeyFactory not available
	at javax.crypto.SecretKeyFactory.<init>(SecretKeyFactory.java:121)
	at javax.crypto.SecretKeyFactory.getInstance(SecretKeyFactory.java:159)
	at com.orientechnologies.orient.core.security.OSecurityManager.getPbkdf2(OSecurityManager.java:225)
	... 7 more

**Comment by tglman** [comment]
hi,

I was going to write this in the changelog right now, java 7 does not have the 'PBKDF2WithHmacSHA256' algorithm embedded, so you have to choose a differnet one with "-Dsecurity.userPasswordDefaultAlgorithm=PBKDF2WithHmacSHA1"

**Comment by smolinari** [comment]
Time to upgrade to Java8. :stuck_out_tongue_winking_eye:  

Scott

**Comment by lucevers** [comment]
Right , I moved to JDK 1.8.0_74 and everything is oke.
Root password [BLANK=auto generate it]: *   -> The first star is it normal looks like a space?

**Comment by maggiolo00** [comment]
Yes the first start is it normal.
