### ISSUE TITLE
OClusterPositionMapException: Error during creation of mapping between logical adn physical record position: java.lang.ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by gerdhub** [orientechnologies/orientdb#5777]
I got the following error when creating a vertex - after that, i cannot query the relevant class anymore and also rebuilding the relevant index fails:

```
$ANSI{green {db=huebscher-kb}} Error on creating record in cluster: plocal cluster: ipattblpostbuch_2
com.orientechnologies.orient.core.exception.OPaginatedClusterException: Error during record creation
	Storage URL="plocal:/opt/orientdb/databases/huebscher-kb"
	Component Name="ipattblpostbuch_2"
	at com.orientechnologies.orient.core.storage.impl.local.paginated.OPaginatedCluster.createRecord(OPaginatedCluster.java:478)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.doCreateRecord(OAbstractPaginatedStorage.java:2899)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.createRecord(OAbstractPaginatedStorage.java:898)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.executeSaveRecord(ODatabaseDocumentTx.java:1935)
	at com.orientechnologies.orient.core.tx.OTransactionNoTx.saveNew(OTransactionNoTx.java:238)
	at com.orientechnologies.orient.core.tx.OTransactionNoTx.saveRecord(OTransactionNoTx.java:172)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.save(ODatabaseDocumentTx.java:2480)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.save(ODatabaseDocumentTx.java:2324)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.save(ODatabaseDocumentTx.java:118)
	at com.orientechnologies.orient.server.network.protocol.binary.OBinaryNetworkProtocolAbstract.createRecord(OBinaryNetworkProtocolAbstract.java:354)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.createRecord(ONetworkProtocolBinary.java:1696)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.executeRequest(ONetworkProtocolBinary.java:422)
	at com.orientechnologies.orient.server.network.protocol.binary.OBinaryNetworkProtocolAbstract.execute(OBinaryNetworkProtocolAbstract.java:210)
	at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:77)
Caused by: com.orientechnologies.orient.core.exception.OClusterPositionMapException: Error during creation of mapping between logical adn physical record position
	Storage URL="plocal:/opt/orientdb/databases/huebscher-kb"
	Component Name="ipattblpostbuch_2"
	at com.orientechnologies.orient.core.storage.impl.local.paginated.OClusterPositionMap.add(OClusterPositionMap.java:226)
	at com.orientechnologies.orient.core.storage.impl.local.paginated.OPaginatedCluster.createRecord(OPaginatedCluster.java:469)
	... 13 more
Caused by: java.lang.ArrayIndexOutOfBoundsException: 117
	at com.orientechnologies.orient.core.storage.impl.local.paginated.wal.OWALPageChangesPortion.updateData(OWALPageChangesPortion.java:237)
	at com.orientechnologies.orient.core.storage.impl.local.paginated.wal.OWALPageChangesPortion.setByteValue(OWALPageChangesPortion.java:60)
	at com.orientechnologies.orient.core.storage.impl.local.paginated.base.ODurablePage.setByteValue(ODurablePage.java:186)
	at com.orientechnologies.orient.core.storage.impl.local.paginated.OClusterPositionMapBucket.add(OClusterPositionMapBucket.java:59)
	at com.orientechnologies.orient.core.storage.impl.local.paginated.OClusterPositionMap.add(OClusterPositionMap.java:219)
	... 14 more
$ANSI{green {db=huebscher-kb}} Error on creating record in cluster: plocal cluster: ipattblpostbuch_2
com.orientechnologies.orient.core.exception.OPaginatedClusterException: Error during record creation
	Storage URL="plocal:/opt/orientdb/databases/huebscher-kb"
	Component Name="ipattblpostbuch_2"
	at com.orientechnologies.orient.core.storage.impl.local.paginated.OPaginatedCluster.createRecord(OPaginatedCluster.java:478)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.doCreateRecord(OAbstractPaginatedStorage.java:2899)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.createRecord(OAbstractPaginatedStorage.java:898)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.executeSaveRecord(ODatabaseDocumentTx.java:1935)
	at com.orientechnologies.orient.core.tx.OTransactionNoTx.saveNew(OTransactionNoTx.java:238)
	at com.orientechnologies.orient.core.tx.OTransactionNoTx.saveRecord(OTransactionNoTx.java:172)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.save(ODatabaseDocumentTx.java:2480)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.save(ODatabaseDocumentTx.java:2324)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.save(ODatabaseDocumentTx.java:118)
	at com.orientechnologies.orient.server.network.protocol.binary.OBinaryNetworkProtocolAbstract.createRecord(OBinaryNetworkProtocolAbstract.java:354)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.createRecord(ONetworkProtocolBinary.java:1696)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.executeRequest(ONetworkProtocolBinary.java:422)
	at com.orientechnologies.orient.server.network.protocol.binary.OBinaryNetworkProtocolAbstract.execute(OBinaryNetworkProtocolAbstract.java:210)
	at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:77)
Caused by: com.orientechnologies.orient.core.exception.OClusterPositionMapException: Error during creation of mapping between logical adn physical record position
	Storage URL="plocal:/opt/orientdb/databases/huebscher-kb"
	Component Name="ipattblpostbuch_2"
	at com.orientechnologies.orient.core.storage.impl.local.paginated.OClusterPositionMap.add(OClusterPositionMap.java:226)
	at com.orientechnologies.orient.core.storage.impl.local.paginated.OPaginatedCluster.createRecord(OPaginatedCluster.java:469)
	... 13 more
Caused by: java.lang.ArrayIndexOutOfBoundsException
```

```
2016-02-25 17:07:05:751 INFO  {db=huebscher-kb} - Rebuilding index huebscher-kb.iPatTblPostbuch.uid (estimated 699.804 items)... [OIndexRebuildOutputListener]
2016-02-25 17:07:11:771 INFO  {db=huebscher-kb} --> OK, indexed 87.403 items in 6.021 ms [OIndexRebuildOutputListener]
2016-02-25 17:07:11:794 SEVER Internal server error:
com.orientechnologies.orient.core.index.OIndexException: Error on rebuilding the index for clusters: [ipattblpostbuch, ipattblpostbuch_2, ipattblpostbuch_1, ipattblpostbuch_7, ipattblpostbuch_4, ipattblpostbuch_3, ipattblpostbuch_6, ipattblpostbuch_5]
	Storage URL="plocal:/opt/orientdb/databases/huebscher-kb"
--> java.lang.IndexOutOfBoundsException [ONetworkProtocolHttpDb]$ANSI{green {db=huebscher-kb}} Error on creating record in cluster: plocal cluster: ipattblpostbuch_2
com.orientechnologies.orient.core.exception.OPaginatedClusterException: Error during record creation
	Storage URL="plocal:/opt/orientdb/databases/huebscher-kb"
	Component Name="ipattblpostbuch_2"
	at com.orientechnologies.orient.core.storage.impl.local.paginated.OPaginatedCluster.createRecord(OPaginatedCluster.java:478)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.doCreateRecord(OAbstractPaginatedStorage.java:2899)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.createRecord(OAbstractPaginatedStorage.java:898)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.executeSaveRecord(ODatabaseDocumentTx.java:1935)
	at com.orientechnologies.orient.core.tx.OTransactionNoTx.saveNew(OTransactionNoTx.java:238)
	at com.orientechnologies.orient.core.tx.OTransactionNoTx.saveRecord(OTransactionNoTx.java:172)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.save(ODatabaseDocumentTx.java:2480)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.save(ODatabaseDocumentTx.java:2324)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.save(ODatabaseDocumentTx.java:118)
	at com.orientechnologies.orient.server.network.protocol.binary.OBinaryNetworkProtocolAbstract.createRecord(OBinaryNetworkProtocolAbstract.java:354)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.createRecord(ONetworkProtocolBinary.java:1696)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.executeRequest(ONetworkProtocolBinary.java:422)
	at com.orientechnologies.orient.server.network.protocol.binary.OBinaryNetworkProtocolAbstract.execute(OBinaryNetworkProtocolAbstract.java:210)
	at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:77)
Caused by: com.orientechnologies.orient.core.exception.OClusterPositionMapException: Error during creation of mapping between logical adn physical record position
	Storage URL="plocal:/opt/orientdb/databases/huebscher-kb"
	Component Name="ipattblpostbuch_2"
	at com.orientechnologies.orient.core.storage.impl.local.paginated.OClusterPositionMap.add(OClusterPositionMap.java:226)
	at com.orientechnologies.orient.core.storage.impl.local.paginated.OPaginatedCluster.createRecord(OPaginatedCluster.java:469)
	... 13 more
Caused by: java.lang.ArrayIndexOutOfBoundsException

```

OrientDB Version is 2.2.0-beta

**Comment by luigidellaquila** [comment]
Hi @gerdhub 

Do you have a deterministic way to reproduce the problem?

Thanks

Luigi

**Comment by luigidellaquila** [comment]
Hi @gerdhub 

Do you have a deterministic way to reproduce the problem?

Thanks

Luigi

**Comment by gerdhub** [comment]
Sorry, not yet. I did a DELETE VERTEX just before, that deleted Vertices linked to Vertices of the relevant class, but I'm not sure whether this was the root cause. I'm currently restoring the db (about 5.000.000 Edges and 250.000 Vertices with a total db size of over 70 GB) and will report if the error happens again.

**Comment by laa** [comment]
@gerdhub Did you archive broken database (please answer yes :-) )

**Comment by gerdhub** [comment]
Unfortunately no, but I think the corruption of the db was related to multithreading. Initially, I thought OrientGraphFactory would handle providing multiple threads with multiple, but constant graph instances itself, however, this might not be the case.

I implemented something like

```
public OrientBaseGraph getGraph(DBTransaction transaction) {

        Thread t = Thread.currentThread();

        if (graphs.containsKey(t)) {
            
            if (graphs.get(t).isClosed()) {
                graphs.remove(t);
            }
            
            switch (transaction) {
                case Tx:
                    if (graphs.get(t) instanceof OrientGraphNoTx) { // if tx requested but graph is notx
                        graphs.get(t).shutdown(false, true);
                        graphs.remove(t);
                    }
                    break;
                case NoTx:
                    if (graphs.get(t) instanceof OrientGraph) { // if tx requested but graph is notx
                        graphs.get(t).shutdown(false, true);
                        graphs.remove(t);
                    }
                    break;
            }
            
        }

        if (!graphs.containsKey(t)) {
            switch (transaction) {
                case Tx:
                    graphs.put(t, factory.getTx());
                    break;
                case NoTx:
                    graphs.put(t, factory.getNoTx());
                    break;
            }
        }

        return graphs.get(t);
    }
```

and the issue never happened again since then.

However, the use of multithreading with orientdb could be documented more extensively. 

Especially in this context, some best practices on how to delete edges from a vertex while iterating over them would be helpful.

**Comment by laa** [comment]
@gerdhub , sorry I do not get it. What do you mean by  

> OrientGraphFactory would handle providing multiple threads with multiple, but constant graph instances 

?

**Comment by laa** [comment]
Oh @gerdhub , I see did you setup pool on OrientGraphFactory instance or used it by default ?

**Comment by laa** [comment]
Fixed

**Comment by laa** [comment]
I have changed graph factory to set up pool by default. So in final version you will not need it any more.

**Comment by gerdhub** [comment]
Ok, thank you!

**Comment by gerdhub** [comment]
One further thought: In my example, I actually have used a pool. However, I assume requesting two graph instances from the pool within the same thread is possible but not "the rule". As far as I understand the documentation one should stick to one graph instance for one thread. So the code above simply ensures that if a graph instance already exists for a given thread, it is reused.
