### ISSUE TITLE
IllegalMonitorStateException in OAdaptiveLock (debug logging output)

### ISSUE THREAD

**Issue by grexe** [orientechnologies/orientdb#5789]
With OrientDB 2.1.9 using the official docker image and the Blueprints 2.6 API, we regularly see this output in the logs - it's only logged at level FINE, but still worries me, what's the cause of this error?
````
[com.orientechnologies.common.concur.lock.OAdaptiveLock] (default task-18) Cannot unlock a lock: java.lang.IllegalMonitorStateException
    at java.util.concurrent.locks.ReentrantLock$Sync.tryRelease(ReentrantLock.java:151)
````

**Comment by laa** [comment]
Hi @grexe , I need full  stack trace exception.

**Comment by grexe** [comment]
sorry for the late reply, here's the stack trace:
(I'm not sure why it's calling shutdown here, seems to be the result of an application Exception)
```
09:46:21,876 FINE  [com.orientechnologies.common.concur.lock.OAdaptiveLock] (default task-18) Cannot unlock a lock: java.lang.IllegalMonitorStateException
    at java.util.concurrent.locks.ReentrantLock$Sync.tryRelease(ReentrantLock.java:151)
    at java.util.concurrent.locks.AbstractQueuedSynchronizer.release(AbstractQueuedSynchronizer.java:1261)
    at java.util.concurrent.locks.ReentrantLock.unlock(ReentrantLock.java:457)
    at com.orientechnologies.common.concur.lock.OAdaptiveLock.close(OAdaptiveLock.java:130)
    at com.orientechnologies.orient.enterprise.channel.OChannel.close(OChannel.java:180)
    at com.orientechnologies.orient.enterprise.channel.binary.OChannelBinary.close(OChannelBinary.java:413)
    at com.orientechnologies.orient.enterprise.channel.binary.OChannelBinaryAsynchClient.close(OChannelBinaryAsynchClient.java:318)
    at com.orientechnologies.orient.client.remote.ORemoteConnectionManager.closePool(ORemoteConnectionManager.java:210)
    at com.orientechnologies.orient.client.remote.ORemoteConnectionManager.closePool(ORemoteConnectionManager.java:201)
    at com.orientechnologies.orient.client.remote.OStorageRemote.close(OStorageRemote.java:310)
    at com.orientechnologies.orient.core.storage.OStorageAbstract.close(OStorageAbstract.java:124)
    at com.orientechnologies.orient.client.remote.OStorageRemoteThread.close(OStorageRemoteThread.java:188)
    at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.close(ODatabaseDocumentTx.java:1195)
    at com.tinkerpop.blueprints.impls.orient.OrientBaseGraph.shutdown(OrientBaseGraph.java:1224)
    at com.tinkerpop.blueprints.impls.orient.OrientBaseGraph.shutdown(OrientBaseGraph.java:1196)
    at com.tinkerpop.blueprints.impls.orient.OrientBaseGraph.shutdown(OrientBaseGraph.java:1189)
    at com.tinkerpop.blueprints.util.wrappers.id.IdGraph.shutdown(IdGraph.java:279)
    at com.tinkerpop.frames.FramedGraph.shutdown(FramedGraph.java:450)
```

**Comment by laa** [comment]
I see assigned to @tglman , it is remote connection manager MT issue.

**Comment by tglman** [comment]
hi @grexe,

we are aware of that exception, is not an error, is due to the fact that we try to ensure that all lock are released on a network channel close, because a close can be triggered by different events outside the normal application flow, we try to check on close if the lock is actually acquired, but there is no safe way to do it, so the only way is try to unlock it an catch the error, here is the code : https://github.com/orientechnologies/orientdb/blob/develop/core/src/main/java/com/orientechnologies/common/concur/lock/OAdaptiveLock.java#L130

you can ignore that error, like you see in our code is only for debug purpose.

Bye

**Comment by grexe** [comment]
thanks that's good to hear, looking forward to 2.2 and v3.0 in summer..!

**Comment by grexe** [comment]
using 2.1.15, could you please just log a message and catch the Exception? As it is a known non-tragic issue, I'd really like my log not be polluted by these Exceptions...

**Comment by tglman** [comment]
hi @grexe,

You have the log level at FINE, if you increase it at INFO it should not log anymore that exception.

**Comment by tglman** [comment]
closing this, because can be removed setting the right log level
