### ISSUE TITLE
Can't build master at label 2.1.11 or 2.1.12 because lucene tests are failing

### ISSUE THREAD

**Issue by Zeemee7** [orientechnologies/orientdb#5793]
On a fresh clone I can't perform a `mvn clean install` on the master branch (currently with label 2.1.12, but it happens also at 2.1.11):

```
Tests run: 30, Failures: 2, Errors: 0, Skipped: 0, Time elapsed: 22.41 sec <<< FAILURE! - in TestSuite
testInsertUpdateTransactionWithIndex(com.orientechnologies.lucene.test.LuceneInsertUpdateSingleDocumentTransactionTest)  Time elapsed: 0.231 sec  <<< FAILURE!
java.lang.AssertionError: expected [2] but found [0]
        at com.orientechnologies.lucene.test.LuceneInsertUpdateSingleDocumentTransactionTest.testInsertUpdateTransactionWithIndex(LuceneInsertUpdateSingleDocumentTransactionTest.java:97)

testInsertUpdateTransactionWithIndex(com.orientechnologies.lucene.test.LuceneInsertUpdateTransactionTest)  Time elapsed: 0.105 sec  <<< FAILURE!
java.lang.AssertionError: expected [1] but found [0]
        at com.orientechnologies.lucene.test.LuceneInsertUpdateTransactionTest.testInsertUpdateTransactionWithIndex(LuceneInsertUpdateTransactionTest.java:97)


Results :

Failed tests:
  LuceneInsertUpdateSingleDocumentTransactionTest.testInsertUpdateTransactionWithIndex:97 expected [2] but found [0]
  LuceneInsertUpdateTransactionTest.testInsertUpdateTransactionWithIndex:97 expected [1] but found [0]

Tests run: 30, Failures: 2, Errors: 0, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] OrientDB ........................................... SUCCESS [  1.330 s]
[INFO] OrientDB Test Commons .............................. SUCCESS [  1.499 s]
[INFO] OrientDB Core ...................................... SUCCESS [01:52 min]
[INFO] OrientDB Enterprise ................................ SUCCESS [  1.133 s]
[INFO] OrientDB Client .................................... SUCCESS [  5.702 s]
[INFO] OrientDB Object .................................... SUCCESS [  6.806 s]
[INFO] OrientDB Server .................................... SUCCESS [ 49.905 s]
[INFO] OrientDB Tools ..................................... SUCCESS [  1.387 s]
[INFO] OrientDB GraphDB ................................... SUCCESS [ 38.980 s]
[INFO] OrientDB Tests ..................................... SUCCESS [04:58 min]
[INFO] OrientDB Distributed Server ........................ SUCCESS [  4.779 s]
[INFO] OrientDB Lucene full text and spatial index ........ FAILURE [ 27.249 s]
[INFO] OrientDB JDBC Driver ............................... SKIPPED
[INFO] OrientDB ETL ....................................... SKIPPED
[INFO] OrientDB Community Distribution .................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 09:10 min
[INFO] Finished at: 2016-03-02T09:19:52+01:00
[INFO] Final Memory: 160M/913M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.19.1:test (default-test) on project orientdb-lucene: There are test failures.
```

`mvn --version` prints:
```
Apache Maven 3.3.3 (7994120775791599e205a5524ec3e0dfe41d4a06; 2015-04-22T13:57:37+02:00)
Maven home: C:\Dev\apache-maven-3.3.3\bin\..
Java version: 1.8.0_65, vendor: Oracle Corporation
Java home: C:\Program Files\Java\jdk1.8.0_65\jre
Default locale: de_DE, platform encoding: Cp1252
OS name: "windows 10", version: "10.0", arch: "amd64", family: "dos"
```

**Comment by robfrank** [comment]
I've just checked out the tag 2.1.12 on master and a mvn clean install was fine:
```code
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] OrientDB ........................................... SUCCESS [  1.035 s]
[INFO] OrientDB Test Commons .............................. SUCCESS [  1.163 s]
[INFO] OrientDB Core ...................................... SUCCESS [01:25 min]
[INFO] OrientDB Enterprise ................................ SUCCESS [  0.684 s]
[INFO] OrientDB Client .................................... SUCCESS [  3.075 s]
[INFO] OrientDB Object .................................... SUCCESS [  5.055 s]
[INFO] OrientDB Server .................................... SUCCESS [ 40.518 s]
[INFO] OrientDB Tools ..................................... SUCCESS [  0.822 s]
[INFO] OrientDB GraphDB ................................... SUCCESS [ 31.204 s]
[INFO] OrientDB Tests ..................................... SUCCESS [03:17 min]
[INFO] OrientDB Distributed Server ........................ SUCCESS [  2.377 s]
[INFO] OrientDB Lucene full text and spatial index ........ SUCCESS [ 18.294 s]
[INFO] OrientDB JDBC Driver ............................... SUCCESS [ 51.075 s]
[INFO] OrientDB ETL ....................................... SUCCESS [ 20.601 s]
[INFO] OrientDB Community Distribution .................... SUCCESS [ 13.376 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 07:52 min
[INFO] Finished at: 2016-03-02T11:10:36+01:00
[INFO] Final Memory: 186M/1597M
[INFO] ------------------------------------------------------------------------
```

```code
mvn --version
Apache Maven 3.3.9 (bb52d8502b132ec0a5a3f4c09453c07478323dc5; 2015-11-10T17:41:47+01:00)
Maven home: /usr/local/Cellar/maven/3.3.9/libexec
Java version: 1.8.0_66, vendor: Azul Systems, Inc.
Java home: /Library/Java/JavaVirtualMachines/zulu-8.jdk/Contents/Home/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "mac os x", version: "10.11.3", arch: "x86_64", family: "mac"
```
Our CI (jenkins) runs on Linux, and all is ok on that.

**Comment by Zeemee7** [comment]
You have an OpenJDK derivate (not Oracle like me), I will try that...

**Comment by robfrank** [comment]
I wonder if it could be the charset, but the tests doesn't use any strange char and it doesn't access to the file system to get text or resources.

**Comment by laa** [comment]
Hi guys ,
I may confirm it runs OK on Linux but always have problem on windows.

ср, 2 Мар 2016, 14:05 Roberto Franchini <notifications@github.com>:

> I wonder if it could be the charset, but the tests doesn't use any strange
> char and it doesn't access to the file system to get text or resources.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/orientechnologies/orientdb/issues/5793#issuecomment-191212517>
> .
>
-- 
Best regards,
Andrey Lomakin, R&D lead.
OrientDB Ltd

twitter:@Andrey_Lomakin linkedin:https://ua.linkedin.com/in/andreylomakin

**Comment by robfrank** [comment]
ok, so it seems a problem with windows. I'll investigate.

**Comment by robfrank** [comment]
@laa  can you check develop on windows?

**Comment by laa** [comment]
Done, still have error

Mar 11, 2016 12:56:35 PM com.orientechnologies.common.log.OLogManager log
INFO: {db=luceneSpatial} Imported: [0] records
Tests run: 30, Failures: 2, Errors: 0, Skipped: 0, Time elapsed: 49.574 sec
<<< FAILURE! - in TestSuite
testInsertUpdateTransactionWithIndex(com.orientechnologies.lucene.test.LuceneInsertUpdateSingleDocumentTransactionTest)
 Time elapsed: 0.061 sec  <<< FAILURE!
java.lang.AssertionError: expected [2] but found [0]
        at
com.orientechnologies.lucene.test.LuceneInsertUpdateSingleDocumentTransactionTest.testInsertUpdateTransactionWithIndex(LuceneInsertUpdateSingleDocumentTransactionTest.java:97)

testInsertUpdateTransactionWithIndex(com.orientechnologies.lucene.test.LuceneInsertUpdateTransactionTest)
 Time elapsed: 0.038 sec  <<< FAILURE!
java.lang.AssertionError: expected [1] but found [0]
        at
com.orientechnologies.lucene.test.LuceneInsertUpdateTransactionTest.testInsertUpdateTransactionWithIndex(LuceneInsertUpdateTransactionTest.java:97)

On Fri, Mar 11, 2016 at 11:40 AM Roberto Franchini <notifications@github.com>
wrote:

> @laa <https://github.com/laa> can you check develop on windows?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/orientechnologies/orientdb/issues/5793#issuecomment-195291752>
> .
>
-- 
Best regards,
Andrey Lomakin, R&D lead.
OrientDB Ltd

twitter:@Andrey_Lomakin linkedin:https://ua.linkedin.com/in/andreylomakin

**Comment by robfrank** [comment]
I need a windows box to understand the problem

**Comment by robfrank** [comment]
I've fixed errors for Lucene on windows, they will be in upcoming 2.2.1 release
