### ISSUE TITLE
Unable to acquire db connections 

### ISSUE THREAD

**Issue by sivan123** [orientechnologies/orientdb#5802]
Orient db version 2.2 Beta

Both the below approaches do not seem to work while they work fine in 2.1.12

new OPartitionedDatabasePool("remote:localhost/Testing","admin","admin",10);

 database = new ODatabaseDocumentTx("remote:localhost/Testing");
        database.setProperty("minPool", 2);
        database.setProperty("maxPool", 5);
        database.open("admin", "admin")

Caused by: com.orientechnologies.orient.core.exception.ODatabaseException: Cannot open database url=remote:localhost/Testing
	Storage URL="remote:localhost/Testing"
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.open(ODatabaseDocumentTx.java:276) ~[orientdb-core-2.2.0-beta.jar:2.2.0-beta]
	at com.orientechnologies.orient.core.db.OPartitionedDatabasePool$DatabaseDocumentTxPolled.internalOpen(OPartitionedDatabasePool.java:140) ~[orientdb-core-2.2.0-beta.jar:2.2.0-beta]
	at com.orientechnologies.orient.core.db.OPartitionedDatabasePool.openDatabase(OPartitionedDatabasePool.java:343) ~[orientdb-core-2.2.0-beta.jar:2.2.0-beta]
	at com.orientechnologies.orient.core.db.OPartitionedDatabasePool.acquire(OPartitionedDatabasePool.java:313) ~[orientdb-core-2.2.0-beta.jar:2.2.0-beta]
	at controllers.api.database.ODocumentTXConnection.getDB(ODocumentTXConnection.java:27) ~[classes/:na]
	at controllers.api.model.PlanUpdateSubscription.subscribePlaUpdate(PlanUpdateSubscription.java:18) ~[classes/:na]
	at controllers.api.services.PlanServices.getPlan(PlanServices.java:19) ~[classes/:na]
	at api.Routes$$anonfun$routes$1$$anonfun$applyOrElse$1$$anonfun$apply$1.apply(Routes.scala:72) ~[classes/:na]
	at api.Routes$$anonfun$routes$1$$anonfun$applyOrElse$1$$anonfun$apply$1.apply(Routes.scala:72) ~[classes/:na]
	at play.core.routing.HandlerInvokerFactory$$anon$4.resultCall(HandlerInvoker.scala:157) ~[play_2.11-2.5.0-M2.jar:2.5.0-M2]
Caused by: java.lang.NumberFormatException: For input string: "UNIQUE"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65) ~[na:1.8.0_66]
	at java.lang.Integer.parseInt(Integer.java:580) ~[na:1.8.0_66]
	at java.lang.Byte.parseByte(Byte.java:149) ~[na:1.8.0_66]
	at java.lang.Byte.parseByte(Byte.java:175) ~[na:1.8.0_66]
	at com.orientechnologies.orient.core.config.OStorageConfiguration.fromStream(OStorageConfiguration.java:438) ~[orientdb-core-2.2.0-beta.jar:2.2.0-beta]
	at com.orientechnologies.orient.core.config.OStorageConfiguration.fromStream(OStorageConfiguration.java:485) ~[orientdb-core-2.2.0-beta.jar:2.2.0-beta]
	at com.orientechnologies.orient.core.config.OStorageConfiguration.load(OStorageConfiguration.java:201) ~[orientdb-core-2.2.0-beta.jar:2.2.0-beta]
	at com.orientechnologies.orient.client.remote.OStorageRemote.open(OStorageRemote.java:238) ~[orientdb-client-2.2.0-beta.jar:2.2.0-beta]
	at com.orientechnologies.orient.client.remote.OStorageRemoteThread.open(OStorageRemoteThread.java:81) ~[orientdb-client-2.2.0-beta.jar:2.2.0-beta]
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.open(ODatabaseDocumentTx.java:242) ~[orientdb-core-2.2.0-beta.jar:2.2.0-beta]

**Comment by laa** [comment]
Hi @sivan123 ,
I need your database to fix given issue . Is it possible to send it ?

**Comment by sivan123** [comment]
Hi @laa . Its just a blank db with just one test class added. as I was in the initial stage of testing it out. Attaching it.
[Testing.zip](https://github.com/orientechnologies/orientdb/files/160129/Testing.zip)

Here is my client library dependency. Could it be that the client libraries in maven are not up to date?

libraryDependencies ++= Seq(
  "com.orientechnologies" % "orientdb-client" % "2.2.0-beta",
  "com.orientechnologies" % "orientdb-graphdb" % "2.2.0-beta",
  "com.orientechnologies" % "orientdb-core" % "2.2.0-beta"
)

**Comment by laa** [comment]
@sivan123 it seems like you use different versions of orientdb on server and client.  Is it possible ?

**Comment by sivan123** [comment]
Hi I was pretty sure I wasn't. Unless the jar files uploaded into maven are not updated..
http://mvnrepository.com/artifact/com.orientechnologies/orientdb-core
That date seems old.. would that be possible?
![image](https://cloud.githubusercontent.com/assets/5057060/14021914/6ce08040-f218-11e5-94c4-1dd86d217646.png)

**Comment by luigidellaquila** [comment]
Hi @sivan123 

yes, it's a problem we are facing, that repo contains an old distro released by mistake (we will release 2.2 beta2 in a few days).

Please use this in the meantime

http://central.maven.org/maven2/com/orientechnologies/orientdb-core/

**Comment by laa** [comment]
Well I close issue then, please reopen it if issue still persist.
