### ISSUE TITLE
serious error for version 2.1.12 (urgent)

### ISSUE THREAD

**Issue by martingg88** [orientechnologies/orientdb#5828]
{db=voyage} Error on creating record in cluster: plocal cluster: locate
com.orientechnologies.orient.core.exception.OStorageException
	at com.orientechnologies.orient.core.storage.impl.local.paginated.OPaginatedCluster.createRecord(OPaginatedCluster.java:434)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.doCreateRecord(OAbstractPaginatedStorage.java:1946)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.createRecord(OAbstractPaginatedStorage.java:751)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.executeSaveRecord(ODatabaseDocumentTx.java:1999)
	at com.orientechnologies.orient.core.tx.OTransactionOptimistic.addRecord(OTransactionOptimistic.java:432)
	at com.orientechnologies.orient.core.tx.OTransactionOptimistic.saveRecord(OTransactionOptimistic.java:363)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.save(ODatabaseDocumentTx.java:2558)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.save(ODatabaseDocumentTx.java:121)
	at com.orientechnologies.orient.core.record.impl.ODocument.save(ODocument.java:1768)
	at com.orientechnologies.orient.core.record.impl.ODocument.save(ODocument.java:1759)
	at com.orientechnologies.orient.core.record.impl.ODocument.save(ODocument.java:81)
	at com.orientechnologies.orient.core.db.record.ridbag.embedded.OEmbeddedRidBag.serialize(OEmbeddedRidBag.java:387)
	at com.orientechnologies.orient.core.db.record.ridbag.ORidBag.toStream(ORidBag.java:277)
	at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinaryV0.writeSingleValue(ORecordSerializerBinaryV0.java:583)
	at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinaryV0.serialize(ORecordSerializerBinaryV0.java:260)
	at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinary.toStream(ORecordSerializerBinary.java:105)
	at com.orientechnologies.orient.core.record.impl.ODocument.toStream(ODocument.java:2296)
	at com.orientechnologies.orient.core.record.impl.ODocument.toStream(ODocument.java:671)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.executeSaveRecord(ODatabaseDocumentTx.java:1933)
	at com.orientechnologies.orient.core.tx.OTransactionOptimistic.addRecord(OTransactionOptimistic.java:432)
	at com.orientechnologies.orient.core.tx.OTransactionOptimistic.saveRecord(OTransactionOptimistic.java:363)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.save(ODatabaseDocumentTx.java:2558)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.save(ODatabaseDocumentTx.java:121)
	at com.orientechnologies.orient.core.record.impl.ODocument.save(ODocument.java:1768)
	at com.orientechnologies.orient.core.record.impl.ODocument.save(ODocument.java:1759)
	at com.orientechnologies.orient.core.record.impl.ODocument.save(ODocument.java:81)
	at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinaryV0.recursiveLinkSave(ORecordSerializerBinaryV0.java:675)
	at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinaryV0.writeOptimizedLink(ORecordSerializerBinaryV0.java:689)
	at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinaryV0.writeSingleValue(ORecordSerializerBinaryV0.java:574)
	at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinaryV0.serialize(ORecordSerializerBinaryV0.java:260)
	at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinary.toStream(ORecordSerializerBinary.java:105)
	at com.orientechnologies.orient.core.record.impl.ODocument.toStream(ODocument.java:2296)
	at com.orientechnologies.orient.core.record.impl.ODocument.toStream(ODocument.java:671)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.executeSaveRecord(ODatabaseDocumentTx.java:1933)
	at com.orientechnologies.orient.core.tx.OTransactionOptimistic.addRecord(OTransactionOptimistic.java:432)
	at com.orientechnologies.orient.core.tx.OTransactionOptimistic.saveRecord(OTransactionOptimistic.java:363)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.save(ODatabaseDocumentTx.java:2558)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.save(ODatabaseDocumentTx.java:121)
	at com.orientechnologies.orient.core.record.impl.ODocument.save(ODocument.java:1768)
	at com.orientechnologies.orient.core.record.impl.ODocument.save(ODocument.java:1759)
	at com.orientechnologies.orient.core.record.impl.ODocument.save(ODocument.java:81)
	at com.orientechnologies.orient.core.db.record.ridbag.embedded.OEmbeddedRidBag.serialize(OEmbeddedRidBag.java:387)
	at com.orientechnologies.orient.core.db.record.ridbag.ORidBag.toStream(ORidBag.java:277)
	at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinaryV0.writeSingleValue(ORecordSerializerBinaryV0.java:583)
	at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinaryV0.serialize(ORecordSerializerBinaryV0.java:260)
	at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinary.toStream(ORecordSerializerBinary.java:105)
	at com.orientechnologies.orient.core.record.impl.ODocument.toStream(ODocument.java:2296)
	at com.orientechnologies.orient.core.record.impl.ODocument.toStream(ODocument.java:671)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.commitEntry(OAbstractPaginatedStorage.java:2426)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.commit(OAbstractPaginatedStorage.java:1189)
	at com.orientechnologies.orient.core.tx.OTransactionOptimistic.doCommit(OTransactionOptimistic.java:606)
	at com.orientechnologies.orient.core.tx.OTransactionOptimistic.commit(OTransactionOptimistic.java:156)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.commit(ODatabaseDocumentTx.java:2679)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.commit(ODatabaseDocumentTx.java:2648)
	at com.orientechnologies.orient.core.command.script.OCommandExecutorScript.executeSQLScript(OCommandExecutorScript.java:284)
	at com.orientechnologies.orient.core.command.script.OCommandExecutorScript.executeSQL(OCommandExecutorScript.java:157)
	at com.orientechnologies.orient.core.command.script.OCommandExecutorScript.executeInContext(OCommandExecutorScript.java:102)
	at com.orientechnologies.orient.core.command.script.OCommandExecutorScript.execute(OCommandExecutorScript.java:91)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.executeCommand(OAbstractPaginatedStorage.java:1530)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.command(OAbstractPaginatedStorage.java:1511)
	at com.orientechnologies.orient.core.command.OCommandRequestTextAbstract.execute(OCommandRequestTextAbstract.java:67)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.command(ONetworkProtocolBinary.java:1323)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.executeRequest(ONetworkProtocolBinary.java:400)
	at com.orientechnologies.orient.server.network.protocol.binary.OBinaryNetworkProtocolAbstract.execute(OBinaryNetworkProtocolAbstract.java:223)
	at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:77)
Caused by: com.orientechnologies.orient.core.exception.OStorageException: Error during creation of mapping between logical adn physical record position.
	at com.orientechnologies.orient.core.storage.impl.local.paginated.OClusterPositionMap.add(OClusterPositionMap.java:201)
	at com.orientechnologies.orient.core.storage.impl.local.paginated.OPaginatedCluster.createRecord(OPaginatedCluster.java:427)
	... 64 more
Caused by: com.orientechnologies.orient.core.storage.impl.local.paginated.atomicoperations.ONestedRollbackException: Atomic operation was rolled back by internal component, exception which caused this rollback is :
com.orientechnologies.orient.core.exception.OStorageException: File with name 'v.sbc' does not exist in storage 'voyage'
	at com.orientechnologies.orient.core.storage.cache.local.OWOWCache.openFile(OWOWCache.java:327)
	at com.orientechnologies.orient.core.storage.cache.local.O2QCache.openFile(O2QCache.java:190)
	at com.orientechnologies.orient.core.storage.impl.local.paginated.atomicoperations.OAtomicOperation.openFile(OAtomicOperation.java:239)
	at com.orientechnologies.orient.core.storage.impl.local.paginated.base.ODurableComponent.openFile(ODurableComponent.java:168)
	at com.orientechnologies.orient.core.index.sbtreebonsai.local.OSBTreeBonsaiLocal.load(OSBTreeBonsaiLocal.java:443)
	at com.orientechnologies.orient.core.db.record.ridbag.sbtree.OSBTreeCollectionManagerShared.loadTree(OSBTreeCollectionManagerShared.java:111)
	at com.orientechnologies.orient.core.db.record.ridbag.sbtree.OSBTreeCollectionManagerAbstract.loadSBTree(OSBTreeCollectionManagerAbstract.java:98)
	at com.orientechnologies.orient.core.db.record.ridbag.sbtree.OSBTreeCollectionManagerProxy.loadSBTree(OSBTreeCollectionManagerProxy.java:52)
	at com.orientechnologies.orient.core.storage.impl.local.paginated.ORidBagUpdateSerializationOperation.loadTree(ORidBagUpdateSerializationOperation.java:76)
	at com.orientechnologies.orient.core.storage.impl.local.paginated.ORidBagUpdateSerializationOperation.execute(ORidBagUpdateSerializationOperation.java:57)
	at com.orientechnologies.orient.core.storage.impl.local.paginated.ORecordSerializationContext.executeOperations(ORecordSerializationContext.java:90)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.doUpdateRecord(OAbstractPaginatedStorage.java:2026)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.updateRecord(OAbstractPaginatedStorage.java:932)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.executeSaveRecord(ODatabaseDocumentTx.java:2005)
	at com.orientechnologies.orient.core.tx.OTransactionOptimistic.addRecord(OTransactionOptimistic.java:432)
	at com.orientechnologies.orient.core.tx.OTransactionOptimistic.saveRecord(OTransactionOptimistic.java:363)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.save(ODatabaseDocumentTx.java:2558)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.save(ODatabaseDocumentTx.java:121)
	at com.orientechnologies.orient.core.record.impl.ODocument.save(ODocument.java:1768)
	at com.orientechnologies.orient.core.record.impl.ODocument.save(ODocument.java:1759)
	at com.orientechnologies.orient.core.record.impl.ODocument.save(ODocument.java:81)
	at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinaryV0.recursiveLinkSave(ORecordSerializerBinaryV0.java:675)
	at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinaryV0.writeOptimizedLink(ORecordSerializerBinaryV0.java:689)
	at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinaryV0.writeSingleValue(ORecordSerializerBinaryV0.java:574)
	at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinaryV0.serialize(ORecordSerializerBinaryV0.java:260)
	at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinary.toStream(ORecordSerializerBinary.java:105)
	at com.orientechnologies.orient.core.record.impl.ODocument.toStream(ODocument.java:2296)
	at com.orientechnologies.orient.core.record.impl.ODocument.toStream(ODocument.java:671)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.commitEntry(OAbstractPaginatedStorage.java:2426)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.commit(OAbstractPaginatedStorage.java:1189)
	at com.orientechnologies.orient.core.tx.OTransactionOptimistic.doCommit(OTransactionOptimistic.java:606)
	at com.orientechnologies.orient.core.tx.OTransactionOptimistic.commit(OTransactionOptimistic.java:156)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.commit(ODatabaseDocumentTx.java:2679)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.commit(ODatabaseDocumentTx.java:2648)
	at com.orientechnologies.orient.core.command.script.OCommandExecutorScript.executeSQLScript(OCommandExecutorScript.java:284)
	at com.orientechnologies.orient.core.command.script.OCommandExecutorScript.executeSQL(OCommandExecutorScript.java:157)
	at com.orientechnologies.orient.core.command.script.OCommandExecutorScript.executeInContext(OCommandExecutorScript.java:102)
	at com.orientechnologies.orient.core.command.script.OCommandExecutorScript.execute(OCommandExecutorScript.java:91)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.executeCommand(OAbstractPaginatedStorage.java:1530)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.command(OAbstractPaginatedStorage.java:1511)
	at com.orientechnologies.orient.core.command.OCommandRequestTextAbstract.execute(OCommandRequestTextAbstract.java:67)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.command(ONetworkProtocolBinary.java:1323)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.executeRequest(ONetworkProtocolBinary.java:400)
	at com.orientechnologies.orient.server.network.protocol.binary.OBinaryNetworkProtocolAbstract.execute(OBinaryNetworkProtocolAbstract.java:223)
	at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:77)

	at com.orientechnologies.orient.core.storage.impl.local.paginated.atomicoperations.OAtomicOperationsManager.endAtomicOperation(OAtomicOperationsManager.java:161)
	at com.orientechnologies.orient.core.storage.impl.local.paginated.base.ODurableComponent.endAtomicOperation(ODurableComponent.java:107)
	at com.orientechnologies.orient.core.storage.impl.local.paginated.OClusterPositionMap.add(OClusterPositionMap.java:197)
	... 65 more

**Comment by laa** [comment]
HI,
@martingg88 did you make export/import from to JSON for this database as we discussed at othere issue ?

**Comment by martingg88** [comment]
yes.. i did export/import, but it's working quite some time. Thereafter, it's no longer work

**Comment by laa** [comment]
I see thank you , you are the single one from tons of users who has given issue )). Any way we are on it.

**Comment by laa** [comment]
Well I have question

**Comment by laa** [comment]
Caused by: com.orientechnologies.orient.core.storage.impl.local.paginated.atomicoperations.ONestedRollbackException: Atomic operation was rolled back by internal component, exception which caused this rollback is :
com.orientechnologies.orient.core.exception.OStorageException: File with name 'v.sbc' does not exist in storage 'voyage'.

do you have 'v.sbc'  in database I think ?

**Comment by martingg88** [comment]
i'm starting to feel upset to use this database for our projects because it's not really for production and it creates a lots of strange issues for us especially for performance wise. haiz.....

FYI. I don't have and never seen v.sbc in my database.

**Comment by laa** [comment]
@martingg88 sad to read this. Is it possible for you to make import again from exported json , (or merely open database which you originally created from JSON) not new one and send me list of files which you get there ?

**Comment by martingg88** [comment]
are you mean i have to export and import from existing database again?

**Comment by martingg88** [comment]
1. I do have backup my database at time interval and here is the config for orientdb. 
2. I have deleted the "voyage" database at /var/backup/orientdb and then manually copy all the files to  "voyage" from backup file (etc. xxxx.zip). 
3. Finally, I can't log on to "voyage" database with root account. really feel strange for this issue. very faint now

       <handler class="com.orientechnologies.orient.server.handler.OAutomaticBackup">
            <parameters>
                <parameter name="enabled" value="true"/>
                <parameter name="delay" value="7d"/>
                <parameter name="firstTime" value="00:00:00"/>
                <parameter name="target.directory" value="/var/backup/orientdb"/>
                <parameter name="target.fileName" value="${DBNAME}-${DATE:yyyy-MM-dd'T'HH:mm:ssZ}.zip"/>
                <parameter name="compressionLevel" value="9"/>
                <parameter name="bufferSize" value="1048576"/>
                
                <parameter name="db.include" value="voyage"/>
                
                <parameter name="db.exclude" value=""/>
                
            </parameters>
        </handler>

**Comment by martingg88** [comment]
is it possible the orientdb server anyhow crashed due to server resource hungry and therefore cause this issue?

**Comment by taburet** [comment]
@martingg88 most likely something went wrong during the JSON import process, as a result one of the required internal files was not created (v.sbc), we have to find the reason behind this failure. Could you please repeat the import from original JSON file(s) and send us OrientDB and operation system logs/errors produced during it along with the file listing of the resulting database directory.

**Comment by martingg88** [comment]
I don't think the issue is from import process because it's working for a long time after imported and thereafter it had this issue suddenly. Anyway, i tried to restored my database from previous backup and it's working now.

**Comment by laa** [comment]
Hi,
We need to understand reason of issue  and need to have as much information
as possible.
If you help us we will be really grateful that you help us to fix given
issue.
Could you send us :
1. List of files after export.
2. Server log at the day when issue happens
3.  OS logs at this date too,  I suppose that you use nix OS.
4. Version of OS and HW configuration.

вт, 15 Мар 2016, 9:12 martingg88 <notifications@github.com>:

> I don't think the issue is from import process because it's working for a
> long time after imported and thereafter it had this issue suddenly. Anyway,
> i tried to restored my database from previous backup and it's working now.
>
> —
> You are receiving this because you were assigned.
>
> Reply to this email directly or view it on GitHub:
>
> https://github.com/orientechnologies/orientdb/issues/5828#issuecomment-196694376
>
-- 
Best regards,
Andrey Lomakin, R&D lead.
OrientDB Ltd

twitter:@Andrey_Lomakin linkedin:https://ua.linkedin.com/in/andreylomakin

**Comment by laa** [comment]
Close issue because of no reply. If you reproduce given issue and have information which is requested in issue feel free to reopen it.
