### ISSUE TITLE
Impossible to clean "invalid verices"

### ISSUE THREAD

**Issue by IliadrilA** [orientechnologies/orientdb#5877]
Hello, I am facing an issue using Java API to get 

```
            for (Edge edge : vertex.getEdges(Direction.OUT)) 
            {
                String type = edge.getLabel();
                Vertex vertexOut = edge.getVertex(Direction.IN);
                String sourcePkId = vertexOut.getProperty(VertexProperty.PK).toString();
                LOGGER.debug("REMOVE link : " + type);
            }
```

And I am getting this trace:

```
Caused by: java.lang.NullPointerException
    at com.tinkerpop.blueprints.impls.orient.OrientElement.getProperty(OrientElement.java:274)
    at com.orange.srs.refobject.business.delegate.cleaning.CleaningDelegate.removeNodesAndLinks(CleaningDelegate.java:222)
    at com.orange.srs.refobject.business.delegate.cleaning.CleaningDelegate.cleaningEntitiesFromQuery(CleaningDelegate.java:138)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606) 
```

However, while performing it in debug, I can see that the vertexOut is displayed as '<invalid record #11:6440593>'. I guess that Vertex is corrupted, so I would like to be able to delete it. Trying it with:

```
 String queryString= "DELETE VERTEX #11:6440593";
            OCommandSQL query = new OCommandSQL(queryString);
            List params = new ArrayList();
            Object deleteResult=graphWrapper.command(query).execute(params); 
```

It appears it does not work.

could you please help me to know how to delete this "invalid record" , and waht this invalid record means?

thanks in advance, Antoine

**Comment by tglman** [comment]
hi @IliadrilA,

Checking the stacktrance i could not find out what was the original problem, can you tell me which version did you use ?

**Comment by tglman** [comment]
hi @IliadrilA,

Did you solve this problem, is there any way we can help?

Regards

**Comment by tglman** [comment]
hi,

Long time without reply, closing
