### ISSUE TITLE
OrientDB 2.1.14-SNAPSHOT on Ubuntu: Failed Server KeepAlive and  NoKeepAliveTests

### ISSUE THREAD

**Issue by fzwaard** [orientechnologies/orientdb#5901]
`Ubuntu 14.04 LTS`

```
Apache Maven 3.0.5
Maven home: /usr/share/maven
Java version: 1.8.0_77, vendor: Oracle Corporation
Java home: /usr/local/java/jdk1.8.0_77/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "3.13.0-24-generic", arch: "amd64", family: "unix"
```

```
git clone https://github.com/orientechnologies/orientdb
cd orientdb
git checkout 2.1.x
mvn -X clean install
```

`[INFO] Building OrientDB 2.1.14-SNAPSHOT`
...

```
2016-03-29 15:35:50:524 INFO  {db=httpdocument} Creating database memory:httpdocument [OServerCommandPostDatabase]Tests run: 47, Failures: 2, Errors: 0, Skipped: 0, Time elapsed: 17.464 sec <<< FAILURE! - in TestSuite
testConnectAutoDisconnectKeepAlive(com.orientechnologies.orient.server.network.http.HttpConnectionTest)  Time elapsed: 7.389 sec  <<< FAILURE!
java.lang.AssertionError: expected [200] but found [500]
        at com.orientechnologies.orient.server.network.http.HttpConnectionTest.testConnectAutoDisconnect(HttpConnectionTest.java:83)
        at com.orientechnologies.orient.server.network.http.HttpConnectionTest.testConnectAutoDisconnectKeepAlive(HttpConnectionTest.java:57)

testConnectAutoDisconnectNoKeepAlive(com.orientechnologies.orient.server.network.http.HttpConnectionTest)  Time elapsed: 5.894 sec  <<< FAILURE!
java.lang.AssertionError: expected [200] but found [500]
        at com.orientechnologies.orient.server.network.http.HttpConnectionTest.testConnectAutoDisconnect(HttpConnectionTest.java:83)
        at com.orientechnologies.orient.server.network.http.HttpConnectionTest.testConnectAutoDisconnectNoKeepAlive(HttpConnectionTest.java:63)

```

Results :

```
Failed tests:
  HttpConnectionTest.testConnectAutoDisconnectKeepAlive:57->testConnectAutoDisconnect:83 expected [200] but found [500]
  HttpConnectionTest.testConnectAutoDisconnectNoKeepAlive:63->testConnectAutoDisconnect:83 expected [200] but found [500]
```

`Tests run: 47, Failures: 2, Errors: 0, Skipped: 0`

```
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] OrientDB .......................................... SUCCESS [1.245s]
[INFO] OrientDB Test Commons ............................. SUCCESS [1.410s]
[INFO] OrientDB Core ..................................... SUCCESS [1:39.684s]
[INFO] OrientDB Enterprise ............................... SUCCESS [0.935s]
[INFO] OrientDB Client ................................... SUCCESS [3.930s]
[INFO] OrientDB Object ................................... SUCCESS [6.572s]
[INFO] OrientDB Server ................................... FAILURE [27.643s]
```

It compiles ok without tests
`mvn clean install -DskipTests`

I see that this goes on since 2.1.9 on Ubuntu https://github.com/orientechnologies/orientdb/issues/5615 but it has not been solved.

Is it safe to run the compiled bins in a production environment even without these tests being passed?

**Comment by lvca** [comment]
Fixed long time ago.
