### ISSUE TITLE
NPE in OAtomicOperation.startAtomicOperation

### ISSUE THREAD

**Issue by zerovian** [orientechnologies/orientdb#5908]
orientdb 2.1.11

NPE during OAtomicOperation.startAtomicOperation.  I don't have a reproducable for this as it happens after a few days.

Caused by: com.orientechnologies.orient.core.exception.ODatabaseException: Error on deleting record in cluster #63
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.executeDeleteRecord(ODatabaseDocumentTx.java:2098)
        at com.orientechnologies.orient.core.tx.OTransactionNoTx.deleteRecord(OTransactionNoTx.java:189)
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.delete(ODatabaseDocumentTx.java:2563)
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.delete(ODatabaseDocumentTx.java:121)
        at com.orientechnologies.orient.core.record.ORecordAbstract.delete(ORecordAbstract.java:293)
        at com.orientechnologies.orient.core.sql.OCommandExecutorSQLDelete.result(OCommandExecutorSQLDelete.java:295)
        at com.orientechnologies.orient.core.sql.OCommandExecutorSQLResultsetAbstract.pushResult(OCommandExecutorSQLResultsetAbstract.java:267)
        at com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.addResult(OCommandExecutorSQLSelect.java:668)
        at com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.handleResult(OCommandExecutorSQLSelect.java:578)
        at com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.executeSearchRecord(OCommandExecutorSQLSelect.java:538)
        at com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.fetchFromTarget(OCommandExecutorSQLSelect.java:1432)
        at com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.fetchValuesFromIndexCursor(OCommandExecutorSQLSelect.java:2056)
        at com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.searchForIndexes(OCommandExecutorSQLSelect.java:1929)
        at com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.searchInClasses(OCommandExecutorSQLSelect.java:874)
        at com.orientechnologies.orient.core.sql.OCommandExecutorSQLResultsetAbstract.assignTarget(OCommandExecutorSQLResultsetAbstract.java:199)
        at com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.assignTarget(OCommandExecutorSQLSelect.java:474)
        at com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.executeSearch(OCommandExecutorSQLSelect.java:456)
        at com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.execute(OCommandExecutorSQLSelect.java:427)
        at com.orientechnologies.orient.core.sql.OCommandExecutorSQLDelegate.execute(OCommandExecutorSQLDelegate.java:90)
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.executeCommand(OAbstractPaginatedStorage.java:1538)
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.command(OAbstractPaginatedStorage.java:1519)
        at com.orientechnologies.orient.core.sql.query.OSQLQuery.run(OSQLQuery.java:72)
        at com.orientechnologies.orient.core.query.OQueryAbstract.execute(OQueryAbstract.java:33)
        at com.orientechnologies.orient.core.sql.OCommandExecutorSQLDelete.execute(OCommandExecutorSQLDelete.java:178)
        at com.orientechnologies.orient.core.sql.OCommandExecutorSQLDelegate.execute(OCommandExecutorSQLDelegate.java:90)
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.executeCommand(OAbstractPaginatedStorage.java:1538)
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.command(OAbstractPaginatedStorage.java:1519)
        at com.orientechnologies.orient.core.command.OCommandRequestTextAbstract.execute(OCommandRequestTextAbstract.java:63)
        at com.orientechnologies.orient.object.db.OCommandSQLPojoWrapper.execute(OCommandSQLPojoWrapper.java:50)
        at com.progress.isq.ipqos.activity.ActivityDataAccess.delete(ActivityDataAccess.java:364)
        at com.progress.isq.ipqos.activity.ActivityService.delete(ActivityService.java:283)
        at com.progress.isq.ipqos.resources.plugins.database.DatabaseActivityProcessor.processAndCollectData(DatabaseActivityProcessor.java:768)
        at com.progress.isq.ipqos.activity.MultiActivityServiceAdapter.processData(MultiActivityServiceAdapter.java:257)
        at com.progress.isq.ipqos.activity.MultiActivityServiceAdapter.processResponse(MultiActivityServiceAdapter.java:219)
        at com.progress.isq.ipqos.activity.MultiActivityServiceAdapter.processActivities(MultiActivityServiceAdapter.java:201)
        at com.progress.isq.ipqos.resources.plugins.database.DatabaseActivityProcessor.processActivities(DatabaseActivityProcessor.java:431)
        at com.progress.isq.ipqos.activity.MultiActivityServiceAdapter.processActivities(MultiActivityServiceAdapter.java:181)
        at com.progress.isq.ipqos.activity.MultiActivityServiceAdapter.fetchAndStoreActivities(MultiActivityServiceAdapter.java:111)
        at com.progress.isq.ipqos.resources.plugins.openedge.work.WorkRunnable.performPolling(WorkRunnable.java:60)
        ... 6 more
Caused by: java.lang.NullPointerException
        at com.orientechnologies.orient.core.storage.impl.local.paginated.atomicoperations.OAtomicOperationsManager.endAtomicOperation(OAtomicOperationsManager.java:148)
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.doDeleteRecord(OAbstractPaginatedStorage.java:2077)
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.deleteRecord(OAbstractPaginatedStorage.java:1025)
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.executeDeleteRecord(ODatabaseDocumentTx.java:2067)

**Comment by laa** [comment]
I fixed NPE, but issue is hidden underneath of NPE. 
Let's try to fix your issue with registration of classes (you may find suggestion in another issue) and then try this change.

**Comment by zerovian** [comment]
I'll try 2.1.14 with those switches, and grab next nightly and test with
that?

**Comment by laa** [comment]
Yes, exactly.

On Mon, Apr 4, 2016 at 5:49 PM zerovian <notifications@github.com> wrote:

> I'll try 2.1.14 with those switches, and grab next nightly and test with
> that?
>
> On Mon, Apr 4, 2016 at 10:00 AM, Andrey Lomakin <notifications@github.com>
> wrote:
>
> > I fixed NPE, but issue is hidden underneath of NPE.
> > Let's try to fix your issue with registration of classes (you may find
> > suggestion in another issue) and then try this change.
> >
> > —
> > You are receiving this because you authored the thread.
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/orientechnologies/orientdb/issues/5908#issuecomment-205306825
> >
> >
>
> —
> You are receiving this because you were assigned.
> Reply to this email directly or view it on GitHub
> <https://github.com/orientechnologies/orientdb/issues/5908#issuecomment-205330999>
>
-- 
Best regards,
Andrey Lomakin, R&D lead.
OrientDB Ltd

twitter:@Andrey_Lomakin linkedin:https://ua.linkedin.com/in/andreylomakin

**Comment by zerovian** [comment]
This went away when 5907 was fixed in 2.1.11-3 hotfix.  Can no longer reproduce.

**Comment by laa** [comment]
Cool I am closing it.
