### ISSUE TITLE
JSON escaping not supported

### ISSUE THREAD

**Issue by schernolyas** [orientechnologies/orientdb#5911]
I try to execute query:
insert into Bookmark content {"isRead":"N","id":"06e3801f-7a75-4224-b3c1-5aab2357f654","isPrivate":"F","isShared":0,"url":"http:\/\/www.hibernate.org\/"}

The parameter "url" is escaped by standartd JSON way. (http://i.stack.imgur.com/CQk5q.gif).

but OrientDB throw exception:

   <error message="Lexical error at line 1, column 130.  Encountered: &quot;/&quot; (47), after : &quot;\&quot;http:\\&quot;" type="com.orientechnologies.orient.core.sql.parser
TokenMgrError">com.orientechnologies.orient.core.sql.parser.TokenMgrError: Lexical error at line 1, column 130.  Encountered: "/" (47), after : "\"http:\\"
       at com.orientechnologies.orient.core.sql.parser.OrientSqlTokenManager.getNextToken(OrientSqlTokenManager.java:5640)
       at com.orientechnologies.orient.core.sql.parser.OrientSql.jj_scan_token(OrientSql.java:24806)
       at com.orientechnologies.orient.core.sql.parser.OrientSql.jj_3R_296(OrientSql.java:22868)
       at com.orientechnologies.orient.core.sql.parser.OrientSql.jj_3R_106(OrientSql.java:22885)
       at com.orientechnologies.orient.core.sql.parser.OrientSql.jj_3R_707(OrientSql.java:24082)
       at com.orientechnologies.orient.core.sql.parser.OrientSql.jj_3R_611(OrientSql.java:24170)
       at com.orientechnologies.orient.core.sql.parser.OrientSql.jj_3R_152(OrientSql.java:24184)
       at com.orientechnologies.orient.core.sql.parser.OrientSql.jj_3R_291(OrientSql.java:24251)
       at com.orientechnologies.orient.core.sql.parser.OrientSql.jj_3R_100(OrientSql.java:24438)
       at com.orientechnologies.orient.core.sql.parser.OrientSql.jj_3_49(OrientSql.java:24468)
       at com.orientechnologies.orient.core.sql.parser.OrientSql.jj_2_49(OrientSql.java:16835)
       at com.orientechnologies.orient.core.sql.parser.OrientSql.InsertStatement(OrientSql.java:3751)
       at com.orientechnologies.orient.core.sql.parser.OrientSql.StatementInternal(OrientSql.java:685)
       at com.orientechnologies.orient.core.sql.parser.OrientSql.Statement(OrientSql.java:570)
       at com.orientechnologies.orient.core.sql.parser.OrientSql.parse(OrientSql.java:79)

Version of orientdb is 2.2.0-beta

**Comment by luigidellaquila** [comment]
Hi @schernolyas 

It's definitely a bug, I'll check it asap

thanks

Luigi

**Comment by schernolyas** [comment]
Base64 content not sopported in JSON way.
Query:
 insert into Bookmark content {"data"
:"DPl62xXzEqG3tIPv7jYYWK34IG4bwTUNk0UUnhYHOluUdPiMQOLSz3V\/GraBuzbEbjDARS6X1wUh53Dh3\/hFpSXVy74iw4K7\/WvwtyvdDJ51\/6qg8RgPyL8qByNXnqxLviMaZk+UZCNmJ+wPJ+\/Jphtb\/cNPw5HmbTIA2VxOq
1OybZIuJaTRVD5tO8sVpMqJTa4IFjMb69vlIYpWctEYByp7gtBCRQOsBeLydnoW+DUOeG1jDyrMmA4hi5M+ctwdn9Vb5wqTjWw=","isRead":"N","id":"52013784-4e32-4e9b-9676-1814ca1256fb","isPrivate":"F","is
Shared":0}

**Comment by luigidellaquila** [comment]
Hi @schernolyas 

I just pushed a fix on develop branch, now I'm back-porting it to 2.1.x

Thanks

Luigi

**Comment by luigidellaquila** [comment]
Done, closing. The fix will be available in v 2.1.16

Please reopen if you experience any related problems

Thanks

Luigi

**Comment by schernolyas** [comment]
HI @luigidellaquila  and @robfrank !

When the fix will at  branch "2.2"? The bug is reproduced :-(

**Comment by luigidellaquila** [comment]
Hi @schernolyas 

I tried it in develop branch and I can confirm that it's fixed. Next 2.2 RC1 will be released in a few days (a few hours if everything is OK).

Thanks

Luigi

**Comment by schernolyas** [comment]
Hi @luigidellaquila !
Thank You very much!
Let me know then You publish the version to maven repository :-)
