### ISSUE TITLE
ClassCastException in OEmbeddedRidBag#next()

### ISSUE THREAD

**Issue by enRGi** [orientechnologies/orientdb#5912]
Using orient-2.1.13 I am getting a ClassCastException when trying to delete a Vertex in Line 90 in OEmbeddedRidBag:
`java.lang.ClassCastException: com.orientechnologies.orient.core.db.record.ridbag.embedded.OEmbeddedRidBag$Tombstone cannot be cast to com.orientechnologies.orient.core.db.record.OIdentifiable
	at com.orientechnologies.orient.core.db.record.ridbag.embedded.OEmbeddedRidBag$EntriesIterator.next(OEmbeddedRidBag.java:90)
	at com.orientechnologies.orient.core.db.record.ridbag.embedded.OEmbeddedRidBag$EntriesIterator.next(OEmbeddedRidBag.java:66)
	at com.orientechnologies.orient.core.iterator.OLazyWrapperIterator.hasNext(OLazyWrapperIterator.java:93)
	at com.orientechnologies.common.collection.OMultiCollectionIterator.hasNext(OMultiCollectionIterator.java:82)
	at com.befinesolutions.gem.orientdb.AdjacentOperationHandler.handle(AdjacentOperationHandler.java:44)
	at com.befinesolutions.gem.orientdb.BaseOrientRepositoryImpl.delete(BaseOrientRepositoryImpl.java:408)
	at com.befinesolutions.gem.orientdb.BaseOrientRepositoryImpl.deleteAdjacent(BaseOrientRepositoryImpl.java:425)
	at com.befinesolutions.gem.orientdb.DeleteAdjacentOperationHandler.onAdjacentFound(DeleteAdjacentOperationHandler.java:29)
	at com.befinesolutions.gem.orientdb.AdjacentOperationHandler.handle(AdjacentOperationHandler.java:49)
	at com.befinesolutions.gem.orientdb.BaseOrientRepositoryImpl.delete(BaseOrientRepositoryImpl.java:408)
	at com.befinesolutions.gem.orientdb.BaseOrientRepositoryImpl.delete(BaseOrientRepositoryImpl.java:371)
	at com.befinesolutions.cryptshare.server.task.CleanupTask$1.perform(CleanupTask.java:302)
	at com.befinesolutions.cryptshare.server.task.CleanupTask$1.perform(CleanupTask.java:1)
	at com.befinesolutions.cryptshare.server.data.apl.repositories.OrientRepositoryImpl.performOnEach(OrientRepositoryImpl.java:133)
	at com.befinesolutions.cryptshare.server.data.apl.repositories.OrientRepositoryImpl.performOnEach(OrientRepositoryImpl.java:113)
	at com.befinesolutions.cryptshare.server.data.apl.repositories.TransferRepositoryImpl.loadLogRetentionExpired(TransferRepositoryImpl.java:76)
	at com.befinesolutions.cryptshare.server.task.CleanupTask.archiveTransfers(CleanupTask.java:283)
	at com.befinesolutions.cryptshare.server.task.CleanupTask.doRun(CleanupTask.java:173)
	at com.befinesolutions.cryptshare.server.task.ServiceTask.start(ServiceTask.java:64)
	at com.befinesolutions.cryptshare.server.task.SuspendableTask.start(SuspendableTask.java:42)
	at com.befinesolutions.cryptshare.server.task.ServiceTask.run(ServiceTask.java:50)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
`
Debugging shows that the entries-array is filled with 'TombStone'-enums:
![2016-03-31_13h58_08](https://cloud.githubusercontent.com/assets/8393975/14175161/8976dc5a-f749-11e5-8aa2-1f53ba0888df.png)

**Comment by laa** [comment]
Sorry but I think that you either call iterator#remove before next or you remove directly from ridbag and then call next.

Could you provide code which operates on ridbag ?

**Comment by laa** [comment]
Any way fixed, could you try on latest 2.1.x ?

**Comment by enRGi** [comment]
Thank you,- The fix is working.

**Comment by Zeemee7** [comment]
I think the fix version isn't correct, it has been fixed in 2.1.15 (as shown by git log).

**Comment by laa** [comment]
@enRGi I agree
