### ISSUE TITLE
NPE in ORole.loadOldVersionOfRules()

### ISSUE THREAD

**Issue by PhantomYdn** [orientechnologies/orientdb#5913]
There is a role inherited from writer. If a user logins who has this role: the following NPE happens:

```
java.lang.NullPointerException
     at com.orientechnologies.orient.core.metadata.security.ORole.loadOldVersionOfRules(ORole.java:407)
     at com.orientechnologies.orient.core.metadata.security.ORole.fromStream(ORole.java:155)
     at com.orientechnologies.orient.core.metadata.security.ORole.<init>(ORole.java:86)
     at com.orientechnologies.orient.core.metadata.security.OUser.fromStream(OUser.java:93)
     at com.orientechnologies.orient.core.metadata.security.OUser.<init>(OUser.java:73)
     at com.orientechnologies.orient.core.metadata.security.OSecurityShared.getUser(OSecurityShared.java:525)
     at com.orientechnologies.orient.core.metadata.security.OSecurityShared.authenticate(OSecurityShared.java:163)
     at com.orientechnologies.orient.core.metadata.security.OSecurityProxy.authenticate(OSecurityProxy.java:87)
     at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.open(ODatabaseDocumentTx.java:264)
     at com.orientechnologies.orient.core.db.OPartitionedDatabasePool$DatabaseDocumentTxPolled.internalOpen(OPartitionedDatabasePool.java:141)
     at com.orientechnologies.orient.core.db.OPartitionedDatabasePool.openDatabase(OPartitionedDatabasePool.java:367)
     at com.orientechnologies.orient.core.db.OPartitionedDatabasePool.acquire(OPartitionedDatabasePool.java:333)
```

To fix that, some rule should be added just to this role. Expected behavior: absence of rules on newly created role should be OK.

OrientDB 2.1.13

**Comment by tglman** [comment]
hi @PhantomYdn,

Reading the exception seems that `a.getValue().intValue()` has null in `a.getValue()` by the way i din't really get how to reproduce this, a snippet of code of user/role creation may help.

Thank You

**Comment by lvca** [comment]
No test case, closing it.
