### ISSUE TITLE
Error on saving record in cluster caused by NPE

### ISSUE THREAD

**Issue by mrboxie** [orientechnologies/orientdb#5920]
We used orientdb 2.0.9 in embedded mode. 
The DB runs into the following exception once a while and subsequent saves trigger the same error. Is this a known issue? Any fix or workaround is greatly appreciated. Thanks for your time!

com.orientechnologies.orient.core.exception.ODatabaseException: Error on saving record in cluster #11        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.executeSaveRecord(ODatabaseDocumentTx.java:1787)
        at com.orientechnologies.orient.core.tx.OTransactionNoTx.saveRecord(OTransactionNoTx.java:102)
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.save(ODatabaseDocumentTx.java:2306)
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.save(ODatabaseDocumentTx.java:118)
        at com.orientechnologies.orient.core.record.impl.ODocument.save(ODocument.java:1711)
        at com.orientechnologies.orient.core.record.impl.ODocument.save(ODocument.java:1702)
        at com.orientechnologies.orient.core.record.impl.ODocument.save(ODocument.java:75)
        at com.orientechnologies.orient.core.serialization.serializer.record.bin             ary.ORecordSerializerBinaryV0.recursiveLinkSave(ORecordSerializerBinaryV0.java:674)
        at com.orientechnologies.orient.core.serialization.serializer.record.bin             ary.ORecordSerializerBinaryV0.writeOptimizedLink(ORecordSerializerBinaryV0.java:688)
        at com.orientechnologies.orient.core.serialization.serializer.record.bin             ary.ORecordSerializerBinaryV0.writeLinkCollection(ORecordSerializerBinaryV0.java:703)
        at com.orientechnologies.orient.core.serialization.serializer.record.bin             ary.ORecordSerializerBinaryV0.writeSingleValue(ORecordSerializerBinaryV0.java:569)
        at com.orientechnologies.orient.core.serialization.serializer.record.bin             ary.ORecordSerializerBinaryV0.serialize(ORecordSerializerBinaryV0.java:261)
        at com.orientechnologies.orient.core.serialization.serializer.record.bin             ary.ORecordSerializerBinary.toStream(ORecordSerializerBinary.java:104)
        at com.orientechnologies.orient.core.record.impl.ODocument.toStream(ODocument.java:2070)
        at com.orientechnologies.orient.core.record.impl.ODocument.toStream(ODocument.java:691)
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.executeSaveRecord(ODatabaseDocumentTx.java:1687)
        at com.orientechnologies.orient.core.tx.OTransactionNoTx.saveRecord(OTransactionNoTx.java:102)
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.save(ODatabaseDocumentTx.java:2306)
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.save(ODatabaseDocumentTx.java:118)
        at com.orientechnologies.orient.core.record.impl.ODocument.save(ODocument.java:1711)
        at com.orientechnologies.orient.core.record.impl.ODocument.save(ODocument.java:1702)
        at com.orientechnologies.orient.core.record.impl.ODocument.save(ODocument.java:75)
        at com.orientechnologies.orient.core.serialization.serializer.record.bin             ary.ORecordSerializerBinaryV0.recursiveLinkSave(ORecordSerializerBinaryV0.java:674)
        at com.orientechnologies.orient.core.serialization.serializer.record.bin             ary.ORecordSerializerBinaryV0.writeOptimizedLink(ORecordSerializerBinaryV0.java:688)
        at com.orientechnologies.orient.core.serialization.serializer.record.bin             ary.ORecordSerializerBinaryV0.writeLinkCollection(ORecordSerializerBinaryV0.java:703)
        at com.orientechnologies.orient.core.serialization.serializer.record.bin             ary.ORecordSerializerBinaryV0.writeSingleValue(ORecordSerializerBinaryV0.java:569)
        at com.orientechnologies.orient.core.serialization.serializer.record.bin             ary.ORecordSerializerBinaryV0.serialize(ORecordSerializerBinaryV0.java:261)
        at com.orientechnologies.orient.core.serialization.serializer.record.bin             ary.ORecordSerializerBinary.toStream(ORecordSerializerBinary.java:104)
        at com.orientechnologies.orient.core.record.impl.ODocument.toStream(ODocument.java:2070)
        at com.orientechnologies.orient.core.record.impl.ODocument.toStream(ODocument.java:691)
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.executeSaveRecord(ODatabaseDocumentTx.java:1687)
        at com.orientechnologies.orient.core.tx.OTransactionNoTx.saveRecord(OTransactionNoTx.java:102)
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.save(ODatabaseDocumentTx.java:2306)
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.save(ODatabaseDocumentTx.java:118)
        at com.orientechnologies.orient.core.record.impl.ODocument.save(ODocument.java:1711)
        at com.orientechnologies.orient.core.record.impl.ODocument.save(ODocument.java:1702)
        at com.orientechnologies.orient.core.record.impl.ODocument.save(ODocument.java:75)
        at com.orientechnologies.orient.core.serialization.serializer.record.bin             ary.ORecordSerializerBinaryV0.recursiveLinkSave(ORecordSerializerBinaryV0.java:674)
        at com.orientechnologies.orient.core.serialization.serializer.record.bin             ary.ORecordSerializerBinaryV0.writeOptimizedLink(ORecordSerializerBinaryV0.java:688)
        at com.orientechnologies.orient.core.serialization.serializer.record.bin             ary.ORecordSerializerBinaryV0.writeSingleValue(ORecordSerializerBinaryV0.java:572)
        at com.orientechnologies.orient.core.serialization.serializer.record.bin             ary.ORecordSerializerBinaryV0.serialize(ORecordSerializerBinaryV0.java:261)
        at com.orientechnologies.orient.core.serialization.serializer.record.bin             ary.ORecordSerializerBinary.toStream(ORecordSerializerBinary.java:104)
        at com.orientechnologies.orient.core.record.impl.ODocument.toStream(ODocument.java:2070)
        at com.orientechnologies.orient.core.record.impl.ODocument.toStream(ODocument.java:691)
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.executeSaveRecord(ODatabaseDocumentTx.java:1687)
        at com.orientechnologies.orient.core.tx.OTransactionNoTx.saveRecord(OTransactionNoTx.java:102)
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.save(ODatabaseDocumentTx.java:2306)
        at com.orientechnologies.orient.object.db.OObjectDatabaseTx.save(OObjectDatabaseTx.java:444)
        at com.orientechnologies.orient.object.db.OObjectDatabaseTx.save(OObjectDatabaseTx.java:379)
        ...
Caused by: java.lang.NullPointerException

**Comment by tglman** [comment]
hi @mrboxie ,

I see that this exception happen with the object database, do you have a test case or example for reproduce it.

**Comment by mrboxie** [comment]
Sorry I don't have a way to reproduce yet. This only happens intermittently. I wonder, just by looking at the stack trace, if you have any hunch on what might be the issue to help us narrow down the scope of investigation.
Thanks,-Bo

Date: Mon, 4 Apr 2016 00:43:48 -0700

**Comment by mrboxie** [comment]
After using customer database, I was able to see the following exception consistently when inserting one type of record in 2.0.9 embedded mode. The trace seem to have more information. I also tried OrientDB 2.1.5 and attach the stacktrace below as well.

I still cannot reproduce without customer database. If the two stacktraces do not provide enough hints, I wonder if you can provide some instructions that I can try on my side to further the investigation as we may not be able to share the customer database.

**StackTrace from using orientdb 2.0.9 embedded mode**
Apr 09, 2016 3:19:20 PM com.orientechnologies.common.log.OLogManager log
SEVERE: {db=statsdb} Error on creating record in cluster: com.orientechnologies.orient.core.storage.impl.local.paginated.OPaginatedCluster@1307a5ec
com.orientechnologies.orient.core.exception.OStorageException
	at com.orientechnologies.orient.core.storage.impl.local.paginated.OPaginatedCluster.createRecord(OPaginatedCluster.java:423)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.doCreateRecord(OAbstractPaginatedStorage.java:1497)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.createRecord(OAbstractPaginatedStorage.java:654)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.executeSaveRecord(ODatabaseDocumentTx.java:1745)
	at com.orientechnologies.orient.core.tx.OTransactionNoTx.saveRecord(OTransactionNoTx.java:102)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.save(ODatabaseDocumentTx.java:2306)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.save(ODatabaseDocumentTx.java:118)
	at com.orientechnologies.orient.core.record.impl.ODocument.save(ODocument.java:1711)
	at com.orientechnologies.orient.core.record.impl.ODocument.save(ODocument.java:1702)
	at com.orientechnologies.orient.core.record.impl.ODocument.save(ODocument.java:75)
	at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinaryV0.recursiveLinkSave(ORecordSerializerBinaryV0.java:674)
	at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinaryV0.writeOptimizedLink(ORecordSerializerBinaryV0.java:688)
	at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinaryV0.writeLinkCollection(ORecordSerializerBinaryV0.java:703)
	at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinaryV0.writeSingleValue(ORecordSerializerBinaryV0.java:569)
	at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinaryV0.serialize(ORecordSerializerBinaryV0.java:261)
	at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinary.toStream(ORecordSerializerBinary.java:104)
	at com.orientechnologies.orient.core.record.impl.ODocument.toStream(ODocument.java:2070)
	at com.orientechnologies.orient.core.record.impl.ODocument.toStream(ODocument.java:691)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.executeSaveRecord(ODatabaseDocumentTx.java:1687)
	at com.orientechnologies.orient.core.tx.OTransactionNoTx.saveRecord(OTransactionNoTx.java:102)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.save(ODatabaseDocumentTx.java:2306)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.save(ODatabaseDocumentTx.java:118)
	at com.orientechnologies.orient.core.record.impl.ODocument.save(ODocument.java:1711)
	at com.orientechnologies.orient.core.record.impl.ODocument.save(ODocument.java:1702)
	at com.orientechnologies.orient.core.record.impl.ODocument.save(ODocument.java:75)
	at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinaryV0.recursiveLinkSave(ORecordSerializerBinaryV0.java:674)
	at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinaryV0.writeOptimizedLink(ORecordSerializerBinaryV0.java:688)
	at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinaryV0.writeLinkCollection(ORecordSerializerBinaryV0.java:703)
	at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinaryV0.writeSingleValue(ORecordSerializerBinaryV0.java:569)
	at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinaryV0.serialize(ORecordSerializerBinaryV0.java:261)
	at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinary.toStream(ORecordSerializerBinary.java:104)
	at com.orientechnologies.orient.core.record.impl.ODocument.toStream(ODocument.java:2070)
	at com.orientechnologies.orient.core.record.impl.ODocument.toStream(ODocument.java:691)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.executeSaveRecord(ODatabaseDocumentTx.java:1687)
	at com.orientechnologies.orient.core.tx.OTransactionNoTx.saveRecord(OTransactionNoTx.java:102)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.save(ODatabaseDocumentTx.java:2306)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.save(ODatabaseDocumentTx.java:118)
	at com.orientechnologies.orient.core.record.impl.ODocument.save(ODocument.java:1711)
	at com.orientechnologies.orient.core.record.impl.ODocument.save(ODocument.java:1702)
	at com.orientechnologies.orient.core.record.impl.ODocument.save(ODocument.java:75)
	at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinaryV0.recursiveLinkSave(ORecordSerializerBinaryV0.java:674)
	at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinaryV0.writeOptimizedLink(ORecordSerializerBinaryV0.java:688)
	at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinaryV0.writeSingleValue(ORecordSerializerBinaryV0.java:572)
	at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinaryV0.serialize(ORecordSerializerBinaryV0.java:261)
	at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinary.toStream(ORecordSerializerBinary.java:104)
	at com.orientechnologies.orient.core.record.impl.ODocument.toStream(ODocument.java:2070)
	at com.orientechnologies.orient.core.record.impl.ODocument.toStream(ODocument.java:691)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.executeSaveRecord(ODatabaseDocumentTx.java:1687)
	at com.orientechnologies.orient.core.tx.OTransactionNoTx.saveRecord(OTransactionNoTx.java:102)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.save(ODatabaseDocumentTx.java:2306)
	at com.orientechnologies.orient.object.db.OObjectDatabaseTx.save(OObjectDatabaseTx.java:444)
	at com.orientechnologies.orient.object.db.OObjectDatabaseTx.save(OObjectDatabaseTx.java:379)
	at com.x.x.x.StatsDBObjectInstance.insertLogEvent(StatsDBObjectInstance.java:642)
	at com.x.x.x.insertPerfData(StatsDBObjectInstance.java:1051)
	at com.x.x.x.StatsDBObjectInstance.main(StatsDBObjectInstance.java:954)
Caused by: java.lang.NullPointerException
	at com.orientechnologies.orient.core.index.hashindex.local.cache.OReadWriteDiskCache.release(OReadWriteDiskCache.java:370)
	at com.orientechnologies.orient.core.storage.impl.local.paginated.base.ODurableComponent.releasePage(ODurableComponent.java:131)
	at com.orientechnologies.orient.core.storage.impl.local.paginated.OPaginatedCluster.findFreePage(OPaginatedCluster.java:1458)
	at com.orientechnologies.orient.core.storage.impl.local.paginated.OPaginatedCluster.addEntry(OPaginatedCluster.java:1390)
	at com.orientechnologies.orient.core.storage.impl.local.paginated.OPaginatedCluster.createRecord(OPaginatedCluster.java:412)

... 54 more

**StackTrace from using orientdb 2.1.5 embedded mode**
Apr 09, 2016 4:55:16 PM com.orientechnologies.common.log.OLogManager log
SEVERE: {db=statsdb} Error on creating record in cluster: plocal cluster: latencydata
com.orientechnologies.orient.core.exception.OStorageException
	at com.orientechnologies.orient.core.storage.impl.local.paginated.OPaginatedCluster.createRecord(OPaginatedCluster.java:391)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.doCreateRecord(OAbstractPaginatedStorage.java:1832)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.createRecord(OAbstractPaginatedStorage.java:722)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.executeSaveRecord(ODatabaseDocumentTx.java:1970)
	at com.orientechnologies.orient.core.tx.OTransactionNoTx.saveRecord(OTransactionNoTx.java:159)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.save(ODatabaseDocumentTx.java:2492)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.save(ODatabaseDocumentTx.java:122)
	at com.orientechnologies.orient.core.record.impl.ODocument.save(ODocument.java:1768)
	at com.orientechnologies.orient.core.record.impl.ODocument.save(ODocument.java:1759)
	at com.orientechnologies.orient.core.record.impl.ODocument.save(ODocument.java:81)
	at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinaryV0.recursiveLinkSave(ORecordSerializerBinaryV0.java:675)
	at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinaryV0.writeOptimizedLink(ORecordSerializerBinaryV0.java:689)
	at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinaryV0.writeLinkCollection(ORecordSerializerBinaryV0.java:713)
	at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinaryV0.writeSingleValue(ORecordSerializerBinaryV0.java:568)
	at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinaryV0.serialize(ORecordSerializerBinaryV0.java:260)
	at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinary.toStream(ORecordSerializerBinary.java:105)
	at com.orientechnologies.orient.core.record.impl.ODocument.toStream(ODocument.java:2296)
	at com.orientechnologies.orient.core.record.impl.ODocument.toStream(ODocument.java:671)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.executeSaveRecord(ODatabaseDocumentTx.java:1904)
	at com.orientechnologies.orient.core.tx.OTransactionNoTx.saveRecord(OTransactionNoTx.java:159)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.save(ODatabaseDocumentTx.java:2492)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.save(ODatabaseDocumentTx.java:122)
	at com.orientechnologies.orient.core.record.impl.ODocument.save(ODocument.java:1768)
	at com.orientechnologies.orient.core.record.impl.ODocument.save(ODocument.java:1759)
	at com.orientechnologies.orient.core.record.impl.ODocument.save(ODocument.java:81)
	at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinaryV0.recursiveLinkSave(ORecordSerializerBinaryV0.java:675)
	at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinaryV0.writeOptimizedLink(ORecordSerializerBinaryV0.java:689)
	at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinaryV0.writeLinkCollection(ORecordSerializerBinaryV0.java:713)
	at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinaryV0.writeSingleValue(ORecordSerializerBinaryV0.java:568)
	at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinaryV0.serialize(ORecordSerializerBinaryV0.java:260)
	at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinary.toStream(ORecordSerializerBinary.java:105)
	at com.orientechnologies.orient.core.record.impl.ODocument.toStream(ODocument.java:2296)
	at com.orientechnologies.orient.core.record.impl.ODocument.toStream(ODocument.java:671)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.executeSaveRecord(ODatabaseDocumentTx.java:1904)
	at com.orientechnologies.orient.core.tx.OTransactionNoTx.saveRecord(OTransactionNoTx.java:159)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.save(ODatabaseDocumentTx.java:2492)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.save(ODatabaseDocumentTx.java:122)
	at com.orientechnologies.orient.core.record.impl.ODocument.save(ODocument.java:1768)
	at com.orientechnologies.orient.core.record.impl.ODocument.save(ODocument.java:1759)
	at com.orientechnologies.orient.core.record.impl.ODocument.save(ODocument.java:81)
	at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinaryV0.recursiveLinkSave(ORecordSerializerBinaryV0.java:675)
	at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinaryV0.writeOptimizedLink(ORecordSerializerBinaryV0.java:689)
	at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinaryV0.writeSingleValue(ORecordSerializerBinaryV0.java:574)
	at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinaryV0.serialize(ORecordSerializerBinaryV0.java:260)
	at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinary.toStream(ORecordSerializerBinary.java:105)
	at com.orientechnologies.orient.core.record.impl.ODocument.toStream(ODocument.java:2296)
	at com.orientechnologies.orient.core.record.impl.ODocument.toStream(ODocument.java:671)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.executeSaveRecord(ODatabaseDocumentTx.java:1904)
	at com.orientechnologies.orient.core.tx.OTransactionNoTx.saveRecord(OTransactionNoTx.java:159)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.save(ODatabaseDocumentTx.java:2492)
	at com.orientechnologies.orient.object.db.OObjectDatabaseTx.save(OObjectDatabaseTx.java:470)
	at com.orientechnologies.orient.object.db.OObjectDatabaseTx.save(OObjectDatabaseTx.java:405)
	at com.x.x.x.StatsDBObjectInstance.insertLogEvent(StatsDBObjectInstance.java:642)
	at com.x.x.x.StatsDBObjectInstance.insertPerfData(StatsDBObjectInstance.java:1057)
	at com.x.x.x.StatsDBObjectInstance.main(StatsDBObjectInstance.java:960)
Caused by: java.lang.NullPointerException
	at com.orientechnologies.orient.core.storage.cache.local.O2QCache.release(O2QCache.java:467)
	at com.orientechnologies.orient.core.storage.impl.local.paginated.base.ODurableComponent.releasePage(ODurableComponent.java:152)
	at com.orientechnologies.orient.core.storage.impl.local.paginated.OPaginatedCluster.findFreePage(OPaginatedCluster.java:1457)
	at com.orientechnologies.orient.core.storage.impl.local.paginated.OPaginatedCluster.addEntry(OPaginatedCluster.java:1389)
	at com.orientechnologies.orient.core.storage.impl.local.paginated.OPaginatedCluster.createRecord(OPaginatedCluster.java:380)
	... 54 more

com.orientechnologies.orient.core.exception.ODatabaseException: Error on saving record in cluster #11
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.executeSaveRecord(ODatabaseDocumentTx.java:2012)
	at com.orientechnologies.orient.core.tx.OTransactionNoTx.saveRecord(OTransactionNoTx.java:159)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.save(ODatabaseDocumentTx.java:2492)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.save(ODatabaseDocumentTx.java:122)
	at com.orientechnologies.orient.core.record.impl.ODocument.save(ODocument.java:1768)
	at com.orientechnologies.orient.core.record.impl.ODocument.save(ODocument.java:1759)
	at com.orientechnologies.orient.core.record.impl.ODocument.save(ODocument.java:81)
	at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinaryV0.recursiveLinkSave(ORecordSerializerBinaryV0.java:675)
	at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinaryV0.writeOptimizedLink(ORecordSerializerBinaryV0.java:689)
	at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinaryV0.writeLinkCollection(ORecordSerializerBinaryV0.java:713)
	at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinaryV0.writeSingleValue(ORecordSerializerBinaryV0.java:568)
	at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinaryV0.serialize(ORecordSerializerBinaryV0.java:260)
	at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinary.toStream(ORecordSerializerBinary.java:105)
	at com.orientechnologies.orient.core.record.impl.ODocument.toStream(ODocument.java:2296)
	at com.orientechnologies.orient.core.record.impl.ODocument.toStream(ODocument.java:671)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.executeSaveRecord(ODatabaseDocumentTx.java:1904)
	at com.orientechnologies.orient.core.tx.OTransactionNoTx.saveRecord(OTransactionNoTx.java:159)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.save(ODatabaseDocumentTx.java:2492)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.save(ODatabaseDocumentTx.java:122)
	at com.orientechnologies.orient.core.record.impl.ODocument.save(ODocument.java:1768)
	at com.orientechnologies.orient.core.record.impl.ODocument.save(ODocument.java:1759)
	at com.orientechnologies.orient.core.record.impl.ODocument.save(ODocument.java:81)
	at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinaryV0.recursiveLinkSave(ORecordSerializerBinaryV0.java:675)
	at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinaryV0.writeOptimizedLink(ORecordSerializerBinaryV0.java:689)
	at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinaryV0.writeLinkCollection(ORecordSerializerBinaryV0.java:713)
	at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinaryV0.writeSingleValue(ORecordSerializerBinaryV0.java:568)
	at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinaryV0.serialize(ORecordSerializerBinaryV0.java:260)
	at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinary.toStream(ORecordSerializerBinary.java:105)
	at com.orientechnologies.orient.core.record.impl.ODocument.toStream(ODocument.java:2296)
	at com.orientechnologies.orient.core.record.impl.ODocument.toStream(ODocument.java:671)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.executeSaveRecord(ODatabaseDocumentTx.java:1904)
	at com.orientechnologies.orient.core.tx.OTransactionNoTx.saveRecord(OTransactionNoTx.java:159)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.save(ODatabaseDocumentTx.java:2492)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.save(ODatabaseDocumentTx.java:122)
	at com.orientechnologies.orient.core.record.impl.ODocument.save(ODocument.java:1768)
	at com.orientechnologies.orient.core.record.impl.ODocument.save(ODocument.java:1759)
	at com.orientechnologies.orient.core.record.impl.ODocument.save(ODocument.java:81)
	at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinaryV0.recursiveLinkSave(ORecordSerializerBinaryV0.java:675)
	at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinaryV0.writeOptimizedLink(ORecordSerializerBinaryV0.java:689)
	at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinaryV0.writeSingleValue(ORecordSerializerBinaryV0.java:574)
	at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinaryV0.serialize(ORecordSerializerBinaryV0.java:260)
	at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinary.toStream(ORecordSerializerBinary.java:105)
	at com.orientechnologies.orient.core.record.impl.ODocument.toStream(ODocument.java:2296)
	at com.orientechnologies.orient.core.record.impl.ODocument.toStream(ODocument.java:671)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.executeSaveRecord(ODatabaseDocumentTx.java:1904)
	at com.orientechnologies.orient.core.tx.OTransactionNoTx.saveRecord(OTransactionNoTx.java:159)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.save(ODatabaseDocumentTx.java:2492)
	at com.orientechnologies.orient.object.db.OObjectDatabaseTx.save(OObjectDatabaseTx.java:470)
	at com.orientechnologies.orient.object.db.OObjectDatabaseTx.save(OObjectDatabaseTx.java:405)
	at com.x.x.x.StatsDBObjectInstance.insertLogEvent(StatsDBObjectInstance.java:642)
	at com.x.x.x.StatsDBObjectInstance.insertPerfData(StatsDBObjectInstance.java:1057)
	at com.x.x.x.StatsDBObjectInstance.main(StatsDBObjectInstance.java:960)
Caused by: java.lang.NullPointerException
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.executeSaveRecord(ODatabaseDocumentTx.java:1971)
	... 51 more

**Comment by mrboxie** [comment]
Hi, 

  I see this issue is moved for next hotfix. Can I assume this is a new issue?

  I wonder if you have any suggestion on how to fix current customer database?

Thank you!

-Bo

**Comment by laa** [comment]
Hi @mrboxie , as you mentioned in issue which you linked, that is issue in 2.0.9 version and I do recommend to upgrade to to latest 2.1 version.

About approaches to fix db, you should make export and then import from JSON, and db will be fixed.
