### ISSUE TITLE
Automatic Indices not updated on insert when in distributed mode. 2.1.14

### ISSUE THREAD

**Issue by dgilling** [orientechnologies/orientdb#5923]
Hey folks, setting up distributed cluster with 3 nodes using 2.1.14 (I also tried 2.1.13) Versions.

Seems that when I use the following distributed config, I am able to successfully commit transactions but any automatic indices I have set up doesn't update. 
Index still doesn't update even if I run distributed mode with only a single node. 
On the other hand, If I run the standalone version, I do correctly see my index updated.

{
  "autoDeploy": true,
  "hotAlignment": false,
  "executionMode": "asynchronous",
  "readQuorum": 1,
  "writeQuorum": 2,
  "failureAvailableNodesLessQuorum": false,
  "readYourWrites": true,
  "servers": {
    "*": "master"
  },
  "clusters": {
    "internal": {
    },
    "index": {
    },
    "*": {
      "servers": ["<NEW_NODE>"]
    }
  }
}

I correctly see the instances when I use console INFO and database compressed and sent to additional nodes when I bring them online.
As a side note, I am NOT using the database IMPORT tool as I need my RID's to be consistent.

Steps:
1. Configure image to start with above config and also copy of database in /databases dir.
2. Start dserver.sh

I don't see any errors related to indexing in log output.
If I rebuild via the portal, then the index is updated with newly added vertices, but that can't be my production strategy. 
Also, dropping and re-creating indices after loading distributed mode still doesn't solve issue.

-------------

As a separate note, If I change my executionMode to "synchronous", I get the following error.
(I don't require synchronous replication, but figured synchronous mode would mitigate any other issues.)

com.orientechnologies.orient.core.exception.OTransactionException: Error on committing distributed transaction
	at com.orientechnologies.orient.server.distributed.ODistributedStorage.processCommitResult(ODistributedStorage.java:1272) ~[orientdb-server-2.1.14.jar:2.1.14]
	at com.orientechnologies.orient.server.distributed.ODistributedStorage.commit(ODistributedStorage.java:1086) ~[orientdb-server-2.1.14.jar:2.1.14]
	at com.orientechnologies.orient.core.tx.OTransactionOptimistic.doCommit(OTransactionOptimistic.java:606) ~[orientdb-core-2.1.14.jar:2.1.14]
	at com.orientechnologies.orient.core.tx.OTransactionOptimistic.commit(OTransactionOptimistic.java:156) ~[orientdb-core-2.1.14.jar:2.1.14]
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.commit(ODatabaseDocumentTx.java:2659) ~[orientdb-core-2.1.14.jar:2.1.14]
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.commit(ODatabaseDocumentTx.java:2627) ~[orientdb-core-2.1.14.jar:2.1.14]
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.commit(ONetworkProtocolBinary.java:1227) ~[orientdb-server-2.1.14.jar:2.1.14]
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.executeRequest(ONetworkProtocolBinary.java:403) ~[orientdb-server-2.1.14.jar:2.1.14]
	at com.orientechnologies.orient.server.network.protocol.binary.OBinaryNetworkProtocolAbstract.execute(OBinaryNetworkProtocolAbstract.java:223) ~[orientdb-server-2.1.14.jar:2.1.14]
	at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:77) ~[orientdb-core-2.1.14.jar:2.1.14]
Caused by: com.orientechnologies.orient.core.exception.ODatabaseException: Error on retrieving record #-1:-10 (cluster: null)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.executeReadRecord(ODatabaseDocumentTx.java:1885) ~[orientdb-core-2.1.14.jar:2.1.14]
	at com.orientechnologies.orient.core.tx.OTransactionOptimistic.loadRecord(OTransactionOptimistic.java:243) ~[orientdb-core-2.1.14.jar:2.1.14]
	at com.orientechnologies.orient.core.tx.OTransactionOptimistic.loadRecord(OTransactionOptimistic.java:217) ~[orientdb-core-2.1.14.jar:2.1.14]
	at com.orientechnologies.orient.core.tx.OTransactionOptimistic.loadRecord(OTransactionOptimistic.java:347) ~[orientdb-core-2.1.14.jar:2.1.14]
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.load(ODatabaseDocumentTx.java:1594) ~[orientdb-core-2.1.14.jar:2.1.14]
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.load(ODatabaseDocumentTx.java:122) ~[orientdb-core-2.1.14.jar:2.1.14]
	at com.orientechnologies.orient.core.id.ORecordId.getRecord(ORecordId.java:324) ~[orientdb-core-2.1.14.jar:2.1.14]
	at com.orientechnologies.orient.core.record.impl.ODocument.validateLink(ODocument.java:451) ~[orientdb-core-2.1.14.jar:2.1.14]
	at com.orientechnologies.orient.core.record.impl.ODocument.validateField(ODocument.java:281) ~[orientdb-core-2.1.14.jar:2.1.14]
	at com.orientechnologies.orient.core.record.impl.ODocument.validate(ODocument.java:2005) ~[orientdb-core-2.1.14.jar:2.1.14]
	at com.orientechnologies.orient.core.record.impl.ODocument.validateEmbedded(ODocument.java:496) ~[orientdb-core-2.1.14.jar:2.1.14]
	at com.orientechnologies.orient.core.record.impl.ODocument.validateField(ODocument.java:303) ~[orientdb-core-2.1.14.jar:2.1.14]
	at com.orientechnologies.orient.core.record.impl.ODocument.validate(ODocument.java:2005) ~[orientdb-core-2.1.14.jar:2.1.14]
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.commit(OAbstractPaginatedStorage.java:1189) ~[orientdb-core-2.1.14.jar:2.1.14]
	at com.orientechnologies.orient.server.distributed.ODistributedStorage.commit(ODistributedStorage.java:974) ~[orientdb-server-2.1.14.jar:2.1.14]
	at com.orientechnologies.orient.core.tx.OTransactionOptimistic.doCommit(OTransactionOptimistic.java:606) ~[orientdb-core-2.1.14.jar:2.1.14]
	at com.orientechnologies.orient.core.tx.OTransactionOptimistic.commit(OTransactionOptimistic.java:156) ~[orientdb-core-2.1.14.jar:2.1.14]
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.commit(ODatabaseDocumentTx.java:2659) ~[orientdb-core-2.1.14.jar:2.1.14]
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.commit(ODatabaseDocumentTx.java:2627) ~[orientdb-core-2.1.14.jar:2.1.14]
	at com.orientechnologies.orient.server.distributed.task.OTxTask.execute(OTxTask.java:131) ~[orientdb-server-2.1.14.jar:2.1.14]
	at com.orientechnologies.orient.server.hazelcast.OHazelcastPlugin.executeOnLocalNode(OHazelcastPlugin.java:810) ~[na:na]
	at com.orientechnologies.orient.server.hazelcast.ODistributedWorker.onMessage(ODistributedWorker.java:279) ~[na:na]
	at com.orientechnologies.orient.server.hazelcast.ODistributedWorker.run(ODistributedWorker.java:103) ~[na:na]
Caused by: com.orientechnologies.orient.core.exception.OStorageException: Cannot route READ_RECORD operation for #-1:-10 to the distributed node
	at com.orientechnologies.orient.server.distributed.ODistributedStorage.handleDistributedException(ODistributedStorage.java:1651) ~[orientdb-server-2.1.14.jar:2.1.14]
	at com.orientechnologies.orient.server.distributed.ODistributedStorage.readRecord(ODistributedStorage.java:648) ~[orientdb-server-2.1.14.jar:2.1.14]
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx$SimpleRecordReader.readRecord(ODatabaseDocumentTx.java:3175) ~[orientdb-core-2.1.14.jar:2.1.14]
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.executeReadRecord(ODatabaseDocumentTx.java:1850) ~[orientdb-core-2.1.14.jar:2.1.14]
	... 22 common frames omitted
Caused by: java.lang.IllegalArgumentException: Cannot read record #-1:-10 since the position is invalid in database 'event-graph-dev'
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.readRecord(OAbstractPaginatedStorage.java:1851) ~[orientdb-core-2.1.14.jar:2.1.14]
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.readRecord(OAbstractPaginatedStorage.java:840) ~[orientdb-core-2.1.14.jar:2.1.14]
	at com.orientechnologies.orient.server.distributed.ODistributedStorage$5.call(ODistributedStorage.java:627) ~[orientdb-server-2.1.14.jar:2.1.14]
	at com.orientechnologies.orient.server.distributed.ODistributedAbstractPlugin.runInDistributedMode(ODistributedAbstractPlugin.java:76) ~[orientdb-server-2.1.14.jar:2.1.14]
	at com.orientechnologies.orient.server.distributed.ODistributedStorage.readRecord(ODistributedStorage.java:624) ~[orientdb-server-2.1.14.jar:2.1.14]
	... 24 common frames omitted

**Comment by dgilling** [comment]
Just to be clear, I am find with index being eventually updated. But as long as that eventual is not forever. 

If I run Select From ClassA Where fieldB = "someValue", I don't get newly added field until I click rebuild index. Same for viewing index itself Select INDEX:ClassA.fieldB where key = "someValue"

I do get the class back on a full scan via Select From V Where fieldB = "someValue"

This index was created for schema defined class ClassA/FieldB, thus works fine when standalone version running.

**Comment by lvca** [comment]
@dgilling did you close this because is not reproducible anymore?

**Comment by dgilling** [comment]
Yes Not Reproducible.

Derric

**Comment by lvca** [comment]
Thanks.
