### ISSUE TITLE
NPE in ODatabaseDocumentTx.open(). Remote pooled connection

### ISSUE THREAD

**Issue by nadestin** [orientechnologies/orientdb#5930]
Starting from version 2.1.14 our application started to get following Exceptions:

com.orientechnologies.orient.core.exception.ODatabaseException: Cannot open database url=remote:yn10:14675/DrTaxDB
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.open(ODatabaseDocumentTx.java:281) ~[na:na]
	at com.orientechnologies.orient.core.db.OPartitionedDatabasePool$DatabaseDocumentTxPolled.internalOpen(OPartitionedDatabasePool.java:130) ~[na:na]
	at com.orientechnologies.orient.core.db.OPartitionedDatabasePool.openDatabase(OPartitionedDatabasePool.java:379) ~[na:na]
	at com.orientechnologies.orient.core.db.OPartitionedDatabasePool.acquire(OPartitionedDatabasePool.java:340) ~[na:na]
	at com.riag.db.dbengine.skin.orientdb.OrientDbSkin.getConnection(OrientDbSkin.java:715) ~[na:na]
	at com.riag.db.dbengine.DBConnection.getConnection(DrTax3_map:82) ~[DrTax3.jar:3.8.20 2016-04-04 09:47:35+0200]
	at com.riag.db.dbengine.skin.orientdb.OrientDbSkin.scanDbClass(OrientDbSkin.java:4683) ~[na:na]
	at com.riag.tm.app.core.domain.ClerkList.scanMandantsleiter(DrTax3_map:125) ~[DrTax3.jar:3.8.20 2016-04-04 09:47:35+0200]
	at com.riag.drtax.appliance.clerkch.F.call(DrTax3_map:332) ~[DrTax3.jar:3.8.20 2016-04-04 09:47:35+0200]
	at java.util.concurrent.FutureTask.run(Unknown Source) [na:1.8.0_74]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [na:1.8.0_74]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [na:1.8.0_74]
	at java.lang.Thread.run(Unknown Source) [na:1.8.0_74]
	at com.riag.db.dbengine.NestedRunner$NestedExecutorThread.run(DrTax3_map:46) [DrTax3.jar:3.8.20 2016-04-04 09:47:35+0200]
Caused by: java.lang.NullPointerException: null
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.open(ODatabaseDocumentTx.java:251) ~[na:na]
	... 13 common frames omitted

Application is heavy multithreaded but with Version 2.1.13 this exception is not showing up.
I tried to build test case but cannot reproduce it somehow. In the real application this NPE comes every time.

Looking in source code the reason of NPE is clear:
250  final String name = ((OStorageProxy) storage).getUserName();
251  if (!name.equals(iUserName)) {

It can only be variable name from the line 250 that starting from version 2.1.14 returns time to time "null". I would propose to change line 251 like this:

if (name == null || (!name.equals(iUserName))) {

That will prevent NPE should name be null and still work correctly.

**Comment by Zeemee7** [comment]
We have the same problem, starting with version 2.1.14. For what I've seen in the code, the proposed fix seems valid for me. I think this happens if OStorageRemoteThreadLocal.INSTANCE.get() calls initialValue(), which creates a new OStorageRemoteSession with connectionUserName null.

**Comment by tglman** [comment]
hi @nadestin, @Zeemee7,

You seems right i'll double check and change that part.

Regargs

**Comment by tglman** [comment]
fixed closing.

Thank you @nadestin  for so detailed reporting.
