### ISSUE TITLE
Teleporter fail to try (4/4) OrientDB importing:             0% [                    ]  

### ISSUE THREAD

**Issue by e-Evolution** [orientechnologies/orientdb#5933]
OrientDB                  
 ______________________________________________________________________________ 
 ___  __/__  ____/__  /___  ____/__  __ \_  __ \__  __\__  __/__  ____/__  _ _ \  
 __  /  __  __/  __  / __  __/  __  /_/ /  / / /_  /_/ /_  /  __  __/  __  /_/ /
 _  /   _  /___  _  /___  /___  _  ____// /_/ /_  _, _/_  /   _  /___  _  _, _/ 
 /_/    /_____/  /_____/_____/  /_/     \____/ /_/ |_| /_/    /_____/  /_/ |_|  

                                                  http://orientdb.com/teleporter

(1/4) Source DB Schema building:    100% [....................]  Elapsed: 00:00:48  Remaining: 00:00:00  Warnings: 5
(2/4) Graph Model building:         100% [....................]  Elapsed: 00:00:00  Remaining: 00:00:00  Warnings: 5
(3/4) OrientDB Schema writing:      100% [....................]  Elapsed: 00:30:02  Remaining: 00:00:00  Warnings: 13

ERROR: org.postgresql.util.PSQLException - El intento de conexión falló.

ERROR: 
org.postgresql.util.PSQLException: El intento de conexión falló.
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:249)
	at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:66)
	at org.postgresql.jdbc2.AbstractJdbc2Connection.<init>(AbstractJdbc2Connection.java:127)
	at org.postgresql.jdbc3.AbstractJdbc3Connection.<init>(AbstractJdbc3Connection.java:29)
	at org.postgresql.jdbc3g.AbstractJdbc3gConnection.<init>(AbstractJdbc3gConnection.java:21)
	at org.postgresql.jdbc4.AbstractJdbc4Connection.<init>(AbstractJdbc4Connection.java:41)
	at org.postgresql.jdbc4.Jdbc4Connection.<init>(Jdbc4Connection.java:24)
	at org.postgresql.Driver.makeConnection(Driver.java:414)
	at org.postgresql.Driver.connect(Driver.java:282)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:247)
	at com.orientdb.teleporter.persistence.util.ODBSourceConnection.getConnection(ODBSourceConnection.java:65)
	at com.orientdb.teleporter.importengine.rdbms.ODBQueryEngine.getRecordsByEntity(ODBQueryEngine.java:136)
	at com.orientdb.teleporter.strategy.rdbms.ODBMSNaiveAggregationStrategy.executeImport(ODBMSNaiveAggregationStrategy.java:164)
	at com.orientdb.teleporter.strategy.rdbms.ODBMSImportStrategy.executeStrategy(ODBMSImportStrategy.java:86)
	at com.orientdb.teleporter.main.OTeleporter.execute(OTeleporter.java:258)
	at com.orientdb.teleporter.main.OTeleporter.main(OTeleporter.java:193)
Caused by: java.net.SocketException: Socket closed
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at org.postgresql.core.PGStream.<init>(PGStream.java:61)
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:121)
	... 16 more

ERROR: com.orientdb.teleporter.exception.OTeleporterRuntimeException - org.postgresql.util.PSQLException: El intento de conexión falló.

ERROR: java.lang.NullPointerException
(4/4) OrientDB importing:             0% [                    ]  Elapsed: 00:00:00  Remaining: 00:00:00  Warnings: 13  Records: 0/470947

Importing complete in 00:31:01

SUMMARY

Source DB Schema
Entities: 845
Relationships: 3218

OrientDB Schema
Vertex Type: 748
Edge Type: 807
Indexes: 748

OrientDB Importing
Analyzed Records: 0/470947
Added Vertices on OrientDB: 0
Updated Vertices on OrientDB: 0
Added Edges on OrientDB: 0

Warning Messages:
The table 'c_hr_payselection_check_v' has not primary key constraints defined in the db schema, thus the correspondent Class Vertex in Orient will not have a default index on the property deriving from the original primary key.
The original type 'timestamptz' is not convertible into any OrientDB type thus, in order to prevent data loss, it will be converted to the OrientDB Type String.
It's not declared a primary key for the Entity t_reconciliation, this might lead to issues during the migration or the sync executions (the first importing is quite safe).
The table 'fact_acct_summary' has not primary key constraints defined in the db schema, thus the correspondent Class Vertex in Orient will not have a default index on the property deriving from the original primary key.
It's not declared a primary key for the Entity a_fundingmode_acct, this might lead to issues during the migration or the sync executions (the first importing is quite safe).
The table 't_alter_column' has not primary key constraints defined in the db schema, thus the correspondent Class Vertex in Orient will not have a default index on the property deriving from the original primary key.
The original type 'bpchar' is not convertible into any OrientDB type thus, in order to prevent data loss, it will be converted to the OrientDB Type String.
It's not declared a primary key for the Entity fact_acct_summary, this might lead to issues during the migration or the sync executions (the first importing is quite safe).
It's not declared a primary key for the Entity t_alter_column, this might lead to issues during the migration or the sync executions (the first importing is quite safe).
The table 't_reconciliation' has not primary key constraints defined in the db schema, thus the correspondent Class Vertex in Orient will not have a default index on the property deriving from the original primary key.
The original type 'name' is not convertible into any OrientDB type thus, in order to prevent data loss, it will be converted to the OrientDB Type String.
It's not declared a primary key for the Entity c_hr_payselection_check_v, this might lead to issues during the migration or the sync executions (the first importing is quite safe).
The table 'a_fundingmode_acct' has not primary key constraints defined in the db schema, thus the correspondent Class Vertex in Orient will not have a default index on the property deriving from the original primary key.

**Comment by G4br13l3** [comment]
Hi @e-Evolution, it seems the connection fell during the records fetching, but the connection succeeded during the 1st, 2nd and 3rd phase when all the queries on the schema are performed in order to build the schema in orientdb. 
Have you tried to restart the migration? If yes, does the execution fail always at the same point?
Is it possible that Postgresql refused the connection for some reason?

**Comment by G4br13l3** [comment]
Hi @e-Evolution, any update about this issue? Did you figure out why the connection to the source database is closed?

**Comment by G4br13l3** [comment]
@e-Evolution I'm closing this issue, please feel free to reopen it if you have issues!
