### ISSUE TITLE
[ Regression on versions >= 2.1.12 ] Regression or changed behaviour with stateless session based on the token.

### ISSUE THREAD

**Issue by Ostico** [orientechnologies/orientdb#5962]
When i tried version 2.1.12 with a token based query i receive a NullPointerException from OrientDB:

```
2016-04-10 03:21:57:405 INFO  /127.0.0.1:50598 - Reading byte (1 byte)... [OChannelBinaryServer]
2016-04-10 03:21:57:405 INFO  /127.0.0.1:50598 - Read byte: 0 [OChannelBinaryServer]
2016-04-10 03:21:57:405 INFO  /127.0.0.1:50598 - Reading int (4 bytes)... [OChannelBinaryServer]
2016-04-10 03:21:57:405 INFO  /127.0.0.1:50598 - Read int: 9764864 [OChannelBinaryServer]
2016-04-10 03:21:57:405 INFO  /127.0.0.1:50598 - Closing socket... [OChannelBinaryServer]Error during sending an error to client
java.lang.NullPointerException
Error during sending an error to client
java.lang.NullPointerException
Exception in thread "OrientDB <- BinaryClient (/127.0.0.1:50598)" java.lang.NullPointerException
	at com.orientechnologies.orient.enterprise.channel.binary.OChannelBinary.close(OChannelBinary.java:393)
	at com.orientechnologies.orient.server.network.protocol.binary.OBinaryNetworkProtocolAbstract.shutdown(OBinaryNetworkProtocolAbstract.java:114)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.shutdown(ONetworkProtocolBinary.java:149)
	at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:85)

2016-04-10 03:21:57:438 INFO  {db=GratefulDeadConcerts} /127.0.0.1:50595 - Flush [OChannelBinaryServer]
```

I tried with version 2.1.15 also, same results.
With preeceding versions all was fine.

This is the test that fails:
https://github.com/mogui/pyorient/blob/master/tests/test_token_auth.py#L44

Please can you tell me if something is changed?

Let me know if you need more info.

**Comment by tglman** [comment]
hi @Ostico,

That bug show up only in case you have the remote debug flag enabled, so as workaround disabled the debug flag, the fix will come out  with the next hotfix.

**Comment by Ostico** [comment]
Tnx!
