### ISSUE TITLE
Unable to import db

### ISSUE THREAD

**Issue by janjilek** [orientechnologies/orientdb#5974]
Hello,
I am using OrientDB 2.1.8 and I need to copy db to other server. I export DB from web console and try to import it via console (-preserveClusterIDs=true) to the new database. Everytime I try to import it, it throws exeption:
Error on database import happened just before line 0, column 31226910
com.orientechnologies.orient.core.exception.ODatabaseException: Database 'remote:localhost/staging' is closed
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.checkOpeness(ODatabaseDocumentTx.java:2826)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.getMetadata(ODatabaseDocumentTx.java:760)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.executeSaveRecord(ODatabaseDocumentTx.java:1931)
	at com.orientechnologies.orient.core.tx.OTransactionNoTx.saveRecord(OTransactionNoTx.java:160)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.save(ODatabaseDocumentTx.java:2468)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.save(ODatabaseDocumentTx.java:120)
	at com.orientechnologies.orient.core.record.impl.ODocument.save(ODocument.java:1768)
	at com.orientechnologies.orient.core.record.impl.ODocument.save(ODocument.java:1759)
	at com.orientechnologies.orient.core.db.tool.ODatabaseImport.rewriteLinksInDocument(ODatabaseImport.java:1568)
	at com.orientechnologies.orient.core.db.tool.ODatabaseImport.migrateLinksInImportedDocuments(ODatabaseImport.java:1538)
	at com.orientechnologies.orient.core.db.tool.ODatabaseImport.importRecords(ODatabaseImport.java:1262)
	at com.orientechnologies.orient.core.db.tool.ODatabaseImport.importDatabase(ODatabaseImport.java:432)
	at com.orientechnologies.orient.console.OConsoleDatabaseApp.importDatabase(OConsoleDatabaseApp.java:1711)
	at com.orientechnologies.orient.graph.console.OGremlinConsole.importDatabase(OGremlinConsole.java:126)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:622)
	at com.orientechnologies.common.console.OConsoleApplication.execute(OConsoleApplication.java:392)
	at com.orientechnologies.common.console.OConsoleApplication.executeCommands(OConsoleApplication.java:253)
	at com.orientechnologies.common.console.OConsoleApplication.run(OConsoleApplication.java:142)
	at com.orientechnologies.orient.graph.console.OGremlinConsole.main(OGremlinConsole.java:64)

What can I do with this? Using different version does not help.

Regards
Jan

**Comment by janjilek** [comment]
I had to run ti 10 times in row to import it. The character on position 31226910 is "3"

**Comment by tglman** [comment]
Hi @janjilek,

Are you running the import using remote or plocal connection, we strongly suggest to use plocal.

**Comment by janjilek** [comment]
I am using remote. Why should I use plocal?

**Comment by tglman** [comment]
Hi @janjilek,

remote import does not support all the cases of plocal,  for example in 2.1 you cannot import database with disable validation, ecc. so we usually suggest to do the import plocal.

**Comment by janjilek** [comment]
Hi,
I understand. But it's strange, that when I import same json X-times in row without cleaning data, it will import with success. 

The import flow: (A < B < C < ... < X)
import database new.json
Error on database import happened just before line 0, column A
import database new.json
Error on database import happened just before line 0, column B
import database new.json
Error on database import happened just before line 0, column C
import database new.json
.
.
.
Error on database import happened just before line 0, column X
import database new.json
Success

**Comment by janjilek** [comment]
It looks like, that it always crash on importing edges. And when I run import again I can see, that re-import is dropping Classes with UNSAFE. So maybe this is why it can import database after X tries.

**Comment by mmacfadden** [comment]
@tglman We are also running into issues with importing to a remote database.  We are needing to orchestrate the import from an application server through the Java API.  It is not really feasible to use plocal in this case.  The only work around we have thought of at this point is to publish to the REST API, which will then import locally, but this is also not idea.

**Comment by tglman** [comment]
Hi @janjilek, @mmacfadden,

we improved the support of the import in remote on the 2.2.5, can you please check your use case ?

Regards.

**Comment by mmacfadden** [comment]
@tglman I will check this out over this coming weekend.  Thanks!

**Comment by mmacfadden** [comment]
@tglman Well this took a long time to get around to.  But I can confirm that this works now.

**Comment by lvca** [comment]
Cool, thank you @mmacfadden.
