### ISSUE TITLE
Error saving record - OSBTreeException: We reached max level of depth of SBTree but still found nothing, seems like tree is in corrupted state. You should rebuild index related to given query.

### ISSUE THREAD

**Issue by mrboxie** [orientechnologies/orientdb#5976]
We are running Orientdb 2.0.9 in embedded mode. We are running into the following exception when trying to insert db record. Not sure if  it is related, the setup for this issue is the same as another issue #5920 we reported. Both cases we had issue with inserting FilePerfData records, not of other types. Please see attached file for classes and indexes used.
[info_class_index.txt](https://github.com/orientechnologies/orientdb/files/217658/info_class_index.txt)

Below is the stacktrace. Let me know if I can provide any information without providing customer DB?

Since we are running in embedded mode, do you suggest we rebuild the index as a workaround to this exception?

Thank you for your time!

-Bo

2016-04-13 16:36:00.837 [pool-7-thread-1] 
com.orientechnologies.orient.core.index.OIndexException: Error during insertion of key in index
        at com.orientechnologies.orient.core.index.OIndexMultiValues.put(OIndexMultiValues.java:141) ~[OIndexMultiValues.class:2.0.9]
        at com.orientechnologies.orient.core.index.OIndexMultiValues.put(OIndexMultiValues.java:52) ~[OIndexMultiValues.class:2.0.9]
        at com.orientechnologies.orient.core.tx.OTransactionNoTx.addIndexEntry(OTransactionNoTx.java:198) ~[OTransactionNoTx.class:2.0.9]
        at com.orientechnologies.orient.core.index.OIndexTxAware.put(OIndexTxAware.java:97) ~[OIndexTxAware.class:2.0.9]
        at com.orientechnologies.orient.core.index.OIndexTxAware.put(OIndexTxAware.java:41) ~[OIndexTxAware.class:2.0.9]
        at com.orientechnologies.orient.core.index.OClassIndexManager.addIndexesEntries(OClassIndexManager.java:543) ~[OClassIndexManager.class:2.0.9]
        at com.orientechnologies.orient.core.index.OClassIndexManager.onRecordAfterCreate(OClassIndexManager.java:310) ~[OClassIndexManager.class:2.0.9]
        at com.orientechnologies.orient.core.hook.ODocumentHookAbstract.onTrigger(ODocumentHookAbstract.java:221) ~[ODocumentHookAbstract.class:2.0.9]
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.callbackHooks(ODatabaseDocumentTx.java:980) ~[ODatabaseDocumentTx.class:2.0.9]
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.callbackHookSuccess(ODatabaseDocumentTx.java:2798) ~[ODatabaseDocumentTx.class:2.0.9]
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.executeSaveRecord(ODatabaseDocumentTx.java:1769) ~[ODatabaseDocumentTx.class:2.0.9]
        at com.orientechnologies.orient.core.tx.OTransactionNoTx.saveRecord(OTransactionNoTx.java:102) ~[OTransactionNoTx.class:2.0.9]
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.save(ODatabaseDocumentTx.java:2306) ~[ODatabaseDocumentTx.class:2.0.9]
        at com.orientechnologies.orient.object.db.OObjectDatabaseTx.save(OObjectDatabaseTx.java:444) ~[OObjectDatabaseTx.class:2.0.9]
        at com.orientechnologies.orient.object.db.OObjectDatabaseTx.save(OObjectDatabaseTx.java:379) ~[OObjectDatabaseTx.class:2.0.9]
        at com.x.x.x.StatsDBObjectInstance.insertLogEvent(StatsDBObjectInstance.java:636) ~[StatsDBObjectInstance.class:3.1.4-172-g3b934cb]
        at com.x.x.x.StatsDBService.gatherFilePerf(StatsDBService.java:636) ~[StatsDBService.class:3.1.4-172-g3b934cb]
        at com.x.x.x.StatsDBService.gatherFilePerfStats(StatsDBService.java:778) ~[StatsDBService.class:3.1.4-172-g3b934cb]
        at sun.reflect.GeneratedMethodAccessor75.invoke(Unknown Source) ~[na:na]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[na:1.7.0_51]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[na:1.7.0_51]
        at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:64) [ScheduledMethodRunnable.class:3.2.8.RELEASE]
        at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:53) [DelegatingErrorHandlingRunnable.class:3.2.8.RELEASE]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [na:1.7.0_51]
        at java.util.concurrent.FutureTask.runAndReset(Unknown Source) [na:1.7.0_51]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(Unknown Source) [na:1.7.0_51]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) [na:1.7.0_51]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [na:1.7.0_51]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [na:1.7.0_51]
        at java.lang.Thread.run(Unknown Source) [na:1.7.0_51]
Caused by: com.orientechnologies.orient.core.index.sbtree.local.OSBTreeException: We reached max level of depth of SBTree but still found nothing, seems like tree is in corrupted state. You should rebuild index related to given query.
        at com.orientechnologies.orient.core.index.sbtree.local.OSBTree.findBucket(OSBTree.java:1543) ~[OSBTree.class:2.0.9]
        at com.orientechnologies.orient.core.index.sbtree.local.OSBTree.get(OSBTree.java:193) ~[OSBTree.class:2.0.9]
        at com.orientechnologies.orient.core.index.engine.OSBTreeIndexEngine.get(OSBTreeIndexEngine.java:225) ~[OSBTreeIndexEngine.class:2.0.9]
        at com.orientechnologies.orient.core.index.OIndexMultiValues.put(OIndexMultiValues.java:115) ~[OIndexMultiValues.class:2.0.9]
        ... 29 common frames omitted

**Comment by laa** [comment]
Hi @mrboxie ,
2.0.9 version had bug in transaction managament system which eventually may lead to corruption of data structures.
Why you did not upgrade to latest 2.0.x or even better 2.1.x version ?

**Comment by mrboxie** [comment]
Thank you. I need comments like yours to be sure the upgrade will help on the issues we are facing.
Really appreciated.

Still wonder if for the issues we saw here and in #5920. Is there any way we can recover the database?

Thanks,
-Bo

**Comment by laa** [comment]
Hi @mrboxie could you update version and try the approach which I suggested you in issue #5920 ?

**Comment by mrboxie** [comment]
Yes, That's what we did. Still wait for the customer to do the upgrade. Will update you. Thank you.
-Bo

Date: Mon, 18 Apr 2016 02:17:12 -0700

**Comment by mrboxie** [comment]
Close for now as we cannot get a date to try on customer site
