### ISSUE TITLE
Random NullPointer on CI tests

### ISSUE THREAD

**Issue by luigidellaquila** [orientechnologies/orientdb#5997]
It happened once during general tests
branch 2.1.x, at commit 6d44b06a5cdcac6eae6bac511b7d0ae40aa91851

Exception in thread "OrientDB ETL pipeline-2" java.lang.NullPointerException
    at com.orientechnologies.orient.core.storage.impl.local.paginated.atomicoperations.OAtomicOperationsManager$WaitingListNode.access$200(OAtomicOperationsManager.java:487)
    at com.orientechnologies.orient.core.storage.impl.local.paginated.atomicoperations.OAtomicOperationsManager.cutWaitingList(OAtomicOperationsManager.java:418)
    at com.orientechnologies.orient.core.storage.impl.local.paginated.atomicoperations.OAtomicOperationsManager.releaseAtomicOperations(OAtomicOperationsManager.java:206)
    at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.synch(OAbstractPaginatedStorage.java:1188)
    at com.orientechnologies.orient.core.metadata.schema.OSchemaShared$1.call(OSchemaShared.java:1214)
    at com.orientechnologies.orient.core.db.OScenarioThreadLocal.executeAsDistributed(OScenarioThreadLocal.java:71)
    at com.orientechnologies.orient.core.metadata.schema.OSchemaShared.saveInternal(OSchemaShared.java:1207)
    at com.orientechnologies.orient.core.metadata.schema.OSchemaShared.releaseSchemaWriteLock(OSchemaShared.java:634)
    at com.orientechnologies.orient.core.metadata.schema.OClassImpl.releaseSchemaWriteLock(OClassImpl.java:1888)
    at com.orientechnologies.orient.core.metadata.schema.OClassImpl.releaseSchemaWriteLock(OClassImpl.java:1883)
    at com.orientechnologies.orient.core.metadata.schema.OClassImpl.addCluster(OClassImpl.java:1095)
    at com.orientechnologies.orient.core.metadata.schema.OClassImpl.addClusters(OClassImpl.java:1063)
    at com.orientechnologies.orient.etl.loader.OOrientDBLoader.beginLoader(OOrientDBLoader.java:433)
    at com.orientechnologies.orient.etl.OETLPipeline.begin(OETLPipeline.java:68)
    at com.orientechnologies.orient.etl.OETLProcessor$2.run(OETLProcessor.java:349)
    at java.lang.Thread.run(Thread.java:744)

**Comment by laa** [comment]
Fixed
