### ISSUE TITLE
Too many files open. 

### ISSUE THREAD

**Issue by willywos** [orientechnologies/orientdb#6003]
Hey,

I'm running OrientDB 2.1.1. When running I am getting these exceptions and then it basically crashes and becomes unusable. 

```
java.net.SocketException: Too many open files
	at java.net.PlainSocketImpl.socketAccept(Native Method)
	at java.net.AbstractPlainSocketImpl.accept(AbstractPlainSocketImpl.java:409)
	at java.net.ServerSocket.implAccept(ServerSocket.java:545)
	at java.net.ServerSocket.accept(ServerSocket.java:513)
	at com.orientechnologies.orient.server.network.OServerNetworkListener.run(OServerNetworkListener.java:190)
```

I've set the ulimit already to like 4000 and that doesn't seem to help. Is there anything I can do? 

Thanks

**Comment by laa** [comment]
Hi @willywos ,
Could you try 2.1.16 version first.
This problem should already be fixed.

**Comment by willywos** [comment]
Hey @laa I think the upgrade is working. I don't see the issue happening in the log files anymore. I'm going to monitor it for the next couple days and I'll reply back here if it does. If you want to close this it's fine. Thanks.

**Comment by laa** [comment]
Hi @willywos , let's wait couple of weeks, if issue will not be confirmed. I close it.

**Comment by laa** [comment]
Close issue as already fixed.
