### ISSUE TITLE
java.lang.ArithmeticException "/ by zero" when using PARALLEL keyword

### ISSUE THREAD

**Issue by oliverfleetwood** [orientechnologies/orientdb#6006]
I get these errors sometimes for the query
```SQL
Select from [some ids...] PARALLEL
```

But not always. Anyone else experiencing this issue? I'll see if I can provide better data to reproduce this error otherwise. 

What I want to do is to speed up the query 
```SQL
Select slowFunction(@rid) from [some ids...]
```

by appending the PARALLEL keyword, thus running slowFunction() for every '@rid' in parallel. Does anyone know if this will actually work?

**Comment by luigidellaquila** [comment]
Hi @oliverfleetwood 

having a simple test case that fails or a database to reproduce the problem (also at random) would help a lot. Do you think you can provide something like that?

Thanks

Luigi

**Comment by oliverfleetwood** [comment]
I'll try to come up with a test case when I have more time. I'll post the full stack trace for now:

```
executing parallel query: Select from [some ids...] PARALLEL
java.lang.ArithmeticException: / by zero
	at com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.parallelExec(OCommandExecutorSQLSelect.java:1544)
	at com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.fetchFromTarget(OCommandExecutorSQLSelect.java:1448)
	at com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.fetchValuesFromIndexCursor(OCommandExecutorSQLSelect.java:2109)
	at com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.searchForIndexes(OCommandExecutorSQLSelect.java:1964)
	at com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.searchInClasses(OCommandExecutorSQLSelect.java:911)
	at com.orientechnologies.orient.core.sql.OCommandExecutorSQLResultsetAbstract.assignTarget(OCommandExecutorSQLResultsetAbstract.java:199)
	at com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.assignTarget(OCommandExecutorSQLSelect.java:497)
	at com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.executeSearch(OCommandExecutorSQLSelect.java:479)
	at com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.execute(OCommandExecutorSQLSelect.java:450)
	at com.orientechnologies.orient.core.sql.OCommandExecutorSQLDelegate.execute(OCommandExecutorSQLDelegate.java:90)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.executeCommand(OAbstractPaginatedStorage.java:1545)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.command(OAbstractPaginatedStorage.java:1518)
	at com.orientechnologies.orient.core.command.OCommandRequestTextAbstract.execute(OCommandRequestTextAbstract.java:67)
	at com.orientechnologies.orient.server.network.protocol.http.command.post.OServerCommandPostCommand.execute(OServerCommandPostCommand.java:81)
	at com.orientechnologies.orient.server.network.protocol.http.ONetworkProtocolHttpAbstract.service(ONetworkProtocolHttpAbstract.java:180)
	at com.orientechnologies.orient.server.network.protocol.http.ONetworkProtocolHttpAbstract.execute(ONetworkProtocolHttpAbstract.java:627)
	at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:77)
```

**Comment by oliverfleetwood** [comment]
I believe this will reproduce the error, though it is not exactly the same query
```SQL
let v1 = create Vertex set name = '1'
let res = select from $v1 PARALLEL
```

**Comment by luigidellaquila** [comment]
Hi @oliverfleetwood 

I just pushed a fix to develop branch. 

Thanks

Luigi
