### ISSUE TITLE
fetching of embedded records

### ISSUE THREAD

**Issue by ODBUser** [orientechnologies/orientdb#6042]
Hi,
Using the Java API (2.1.15), I try to load embedded records with their parents.

I get a VERTEXTYPE "Vertex" that contains an EMBEDDEDLIST of "Embedded1"
Every "Embedded1" contains also an EMBEDDEDLIST of "Embedded2"

In the test below, I create the dabase, the schema and one node with its embedded document.
I then queries the database with an OCommandSQL.

And I get the following warning and exception :
```
WARNING: Error deserializing record with id #13:0 send this data for debugging: AAxWZXJ0ZXgvAAAAEzEAAAAVAAIwBBcJEkVtYmVkZGVkMSsAAAAtLQAAADAABDAwBBcJEkVtYmVkZGVkMikAAABDAAYwMDAJEkVtYmVkZGVkMikAAABYAAYwMDEJEkVtYmVkZGVkMSsAAAByLQAAAHUABDAxBBcJEkVtYmVkZGVkMikAAACIAAYwMTAJEkVtYmVkZGVkMikAAACdAAYwMTE= 
Exception in thread "main" com.orientechnologies.orient.core.exception.ODatabaseException: Database instance is not set in current thread. Assure to set it with: ODatabaseRecordThreadLocal.INSTANCE.set(db);
	at com.orientechnologies.orient.core.db.ODatabaseRecordThreadLocal.get(ODatabaseRecordThreadLocal.java:51)
	at com.orientechnologies.orient.core.record.ORecordAbstract.getDatabase(ORecordAbstract.java:240)
	at com.orientechnologies.orient.core.record.impl.ODocument.getGlobalPropertyById(ODocument.java:2158)
	at com.orientechnologies.orient.core.record.impl.ODocumentInternal.getGlobalPropertyById(ODocumentInternal.java:60)
	at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinaryV0.getGlobalProperty(ORecordSerializerBinaryV0.java:280)
	at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinaryV0.deserialize(ORecordSerializerBinaryV0.java:179)
	at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinaryV0.readSingleValue(ORecordSerializerBinaryV0.java:328)
	at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinaryV0.readEmbeddedCollection(ORecordSerializerBinaryV0.java:474)
	at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinaryV0.readSingleValue(ORecordSerializerBinaryV0.java:347)
	at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinaryV0.deserializePartial(ORecordSerializerBinaryV0.java:143)
	at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinary.fromStream(ORecordSerializerBinary.java:72)
	at com.orientechnologies.orient.core.record.impl.ODocument.deserializeFields(ODocument.java:1817)
	at com.orientechnologies.orient.core.record.impl.ODocument.checkForFields(ODocument.java:2416)
	at com.orientechnologies.orient.core.record.impl.ODocument.fetchClassName(ODocument.java:2492)
	at com.orientechnologies.orient.core.record.impl.ODocument.getImmutableSchemaClass(ODocument.java:2185)
	at com.orientechnologies.orient.core.record.impl.ODocumentInternal.getImmutableSchemaClass(ODocumentInternal.java:56)
	at com.tinkerpop.blueprints.impls.orient.OrientDynaElementIterator.next(OrientDynaElementIterator.java:68)
	at test.Test.main(Test.java:103)
```
I suppose the exception is due to the fact that embedded documents are loaded lazily and when I try to read them, the database connection is already closed.

All works fine if I close the connexion at the end (commented code). And I get the expected output :
```
	name1 : 00
		name2 : 000
		name2 : 001
	name1 : 01
		name2 : 010
		name2 : 011
```

I tried to set the FetchPlan to "*:-1" but I get the same behavior.

test code :
```java
package test;

import java.io.IOException;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;

import com.orientechnologies.orient.client.remote.OServerAdmin;
import com.orientechnologies.orient.core.metadata.schema.OClass;
import com.orientechnologies.orient.core.metadata.schema.OSchema;
import com.orientechnologies.orient.core.metadata.schema.OType;
import com.orientechnologies.orient.core.record.impl.ODocument;
import com.orientechnologies.orient.core.sql.OCommandSQL;
import com.tinkerpop.blueprints.Vertex;
import com.tinkerpop.blueprints.impls.orient.OrientGraph;
import com.tinkerpop.blueprints.impls.orient.OrientGraphFactory;
import com.tinkerpop.blueprints.impls.orient.OrientGraphNoTx;
import com.tinkerpop.blueprints.impls.orient.OrientVertex;
import com.tinkerpop.blueprints.impls.orient.OrientVertexType;

public class Test {

	public static void main(String[] args) throws IOException {
		String path = "remote:localhost/testDB";
		String dbName = "testDB";
		OrientGraphFactory factory = null;

		OServerAdmin serverAdmin = new OServerAdmin(path).connect("root", "root");

		boolean populate = true;

		if(serverAdmin.existsDatabase()){
			System.out.println("The graph '" + path + "' already exists, what do you want to do? (d=drop and process, a=abort)");
			char c = (char) System.in.read();
			if(c == 'd'){
				System.out.println("Dropped.");
				serverAdmin.dropDatabase(null);
				serverAdmin.createDatabase(dbName, "graph", "plocal");
				System.out.println("The graph '" + path + "' has been recreated");
			}
			else{
				System.out.println("Aborted.");
				populate = false;
			}
			System.in.read(); // read the Enter
		}
		else{
			serverAdmin.createDatabase(dbName, "graph", "plocal");
			System.out.println("The graph '" + path + "' does not exists and has been created");
		}
		serverAdmin.close();

		factory = new OrientGraphFactory(path, "root", "root");
		factory.setUseLightweightEdges(true);

		if(populate) {
			OrientGraphNoTx graph = factory.getNoTx();
			try{
				OSchema schema = graph.getRawGraph().getMetadata().getSchema();

				OClass embedded2 = schema.createClass("Embedded2");
				embedded2.createProperty("name2", OType.STRING);

				OClass embedded1 = schema.createClass("Embedded1");
				embedded1.createProperty("name1", OType.STRING);
				embedded1.createProperty("embeddedlist2", OType.EMBEDDEDLIST, embedded2);

				OrientVertexType vertex = graph.createVertexType("Vertex");
				vertex.createProperty("name0", OType.STRING);
				vertex.createProperty("embeddedlist1", OType.EMBEDDEDLIST, embedded1);

				List<ODocument> embeddedlist1 = new ArrayList<ODocument>();
				List<ODocument> embeddedlist2 = new ArrayList<ODocument>();

				embeddedlist2.add(new ODocument("Embedded2").field("name2", new String("000")));
				embeddedlist2.add(new ODocument("Embedded2").field("name2", new String("001")));
				embeddedlist1.add(new ODocument("Embedded1").field("name1", new String("00")).field("embeddedlist2", new ArrayList<ODocument>(embeddedlist2)));

				embeddedlist2.clear();
				embeddedlist2.add(new ODocument("Embedded2").field("name2", new String("010")));
				embeddedlist2.add(new ODocument("Embedded2").field("name2", new String("011")));
				embeddedlist1.add(new ODocument("Embedded1").field("name1", new String("01")).field("embeddedlist2", new ArrayList<ODocument>(embeddedlist2)));

				Vertex vertex0 = graph.addVertex("class:Vertex", "name0", "0", "embeddedlist1", new ArrayList<ODocument>(embeddedlist1));
			} finally{
				graph.shutdown();
			}
		}

		String query = "SELECT FROM #13:0";
		OCommandSQL command = new OCommandSQL(query);

		Iterator<OrientVertex> resultat = null;
		OrientGraph g = factory.getTx();
		try {
			command.setFetchPlan("*:-1");
			resultat = ((Iterable<OrientVertex>)g.command(command).execute()).iterator();
		} finally {
			g.shutdown();
		}
		OrientVertex vertexResultat;
		while (resultat.hasNext()) {
			vertexResultat = resultat.next();
			List<ODocument> embeddedlist1 = vertexResultat.getProperty("embeddedlist1");
			for (ODocument embedded1 : embeddedlist1) {
				System.out.println("\tname1 : " + embedded1.field("name1"));
				List<ODocument> embeddedlist2 = embedded1.field("embeddedlist2");
				for (ODocument embedded2 : embeddedlist2) {
					System.out.println("\t\tname2 : " + embedded2.field("name2"));
				}
			}
		}
//		} finally {
//			g.shutdown();
//		}
	}
}
```
what am I doing wrong ? How to fetch embedded records with their parents ?
Thanks.

**Comment by tglman** [comment]
hi @ODBUser,

For use the ODocument/OrientVertex out of the scope of the session you have to use detach, the fetch plan on the query has a different purpose, that is preloading in memory objects.
