### ISSUE TITLE
NPE in ORecordInteral Line 71 when deleting records in parallel

### ISSUE THREAD

**Issue by enRGi** [orientechnologies/orientdb#6054]
When deleting the same list of records in parallel with two Threads a NullPointerException occurs in ORecordInternal Line 71. The null-reference actually is recognized in OTransactionOptimisticProxy, Line 115, but the exception is not thrown, only kept in memory for throwing it later.
![2016-04-27_12h41_29](https://cloud.githubusercontent.com/assets/8393975/14849909/f8b58efe-0c75-11e6-9761-24aeb7b27123.png)
Then ORecordInternal#setVersion is called using the null-reference and the is running into the NPE.

`Caused by: java.lang.NullPointerException: null
	at com.orientechnologies.orient.core.record.ORecordInternal.setVersion(ORecordInternal.java:71)
	at com.orientechnologies.orient.server.tx.OTransactionOptimisticProxy.begin(OTransactionOptimisticProxy.java:115)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.begin(ODatabaseDocumentTx.java:1679)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.commit(ONetworkProtocolBinary.java:1216)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.executeRequest(ONetworkProtocolBinary.java:403)
	at com.orientechnologies.orient.server.network.protocol.binary.OBinaryNetworkProtocolAbstract.execute(OBinaryNetworkProtocolAbstract.java:223)
	at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:77)`

I am using OrientDB v2.1.15

**Comment by tglman** [comment]
fixed both in develop and 2.1.x, thank you with so detailed report, it was easy to fix.
