### ISSUE TITLE
Failed to open database - The record with id '#0:4' not found

### ISSUE THREAD

**Issue by mrboxie** [orientechnologies/orientdb#6081]
Hi, 
  We have encountered issue reopening database after a server(with orientdb in embedded mode) crash. Using console.sh had the same exception. The DB looks corrupted. We just recently upgraded from 2.0.9 to 2.1.16. With 2.0.9, we did not encounter similar issue or at least not in house. So is this new to 2.1.x? Is the DB recoverable? Thank you for any advice you have. We have the database if you need.

2016-05-02 11:29:43.279 [pool-7-thread-1] ERROR c.m.b.s.object.StatsDBObjectInstance - An exception occurred while opening/creating the database. Retrying...
com.orientechnologies.common.exception.OException: Error on creation of shared resource
	at com.orientechnologies.common.concur.resource.OSharedContainerImpl.getResource(OSharedContainerImpl.java:66) ~[OSharedContainerImpl.class:2.1.16]
	at com.orientechnologies.orient.core.storage.OStorageAbstract.getResource(OStorageAbstract.java:143) ~[OStorageAbstract.class:2.1.16]
	at com.orientechnologies.orient.core.metadata.OMetadataDefault.init(OMetadataDefault.java:141) ~[OMetadataDefault.class:2.1.16]
	at com.orientechnologies.orient.core.metadata.OMetadataDefault.load(OMetadataDefault.java:76) ~[OMetadataDefault.class:2.1.16]
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.initAtFirstOpen(ODatabaseDocumentTx.java:2901) ~[ODatabaseDocumentTx.class:2.1.16]
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.open(ODatabaseDocumentTx.java:259) ~[ODatabaseDocumentTx.class:2.1.16]
	at com.orientechnologies.orient.core.db.ODatabaseWrapperAbstract.open(ODatabaseWrapperAbstract.java:57) ~[ODatabaseWrapperAbstract.class:2.1.16]
	at com.orientechnologies.orient.object.db.OObjectDatabaseTx.open(OObjectDatabaseTx.java:127) ~[OObjectDatabaseTx.class:2.1.16]
	at com.orientechnologies.orient.object.db.OObjectDatabaseTxPooled.<init>(OObjectDatabaseTxPooled.java:48) ~[OObjectDatabaseTxPooled.class:2.1.16]
	at com.orientechnologies.orient.object.db.OObjectDatabasePool.createResource(OObjectDatabasePool.java:51) ~[OObjectDatabasePool.class:2.1.16]
	at com.orientechnologies.orient.object.db.OObjectDatabasePool.createResource(OObjectDatabasePool.java:27) ~[OObjectDatabasePool.class:2.1.16]
	at com.orientechnologies.orient.core.db.ODatabasePoolBase$1.createNewResource(ODatabasePoolBase.java:81) ~[ODatabasePoolBase$1.class:2.1.16]
	at com.orientechnologies.orient.core.db.ODatabasePoolBase$1.createNewResource(ODatabasePoolBase.java:70) ~[ODatabasePoolBase$1.class:2.1.16]
	at com.orientechnologies.common.concur.resource.OResourcePool.getResource(OResourcePool.java:94) ~[OResourcePool.class:2.1.16]
	at com.orientechnologies.common.concur.resource.OReentrantResourcePool.getResource(OReentrantResourcePool.java:84) ~[OReentrantResourcePool.class:2.1.16]
	at com.orientechnologies.orient.core.db.ODatabasePoolAbstract.acquire(ODatabasePoolAbstract.java:158) ~[ODatabasePoolAbstract.class:2.1.16]
	at com.orientechnologies.orient.core.db.ODatabasePoolAbstract.acquire(ODatabasePoolAbstract.java:138) ~[ODatabasePoolAbstract.class:2.1.16]
	at com.orientechnologies.orient.core.db.ODatabasePoolBase.acquire(ODatabasePoolBase.java:112) ~[ODatabasePoolBase.class:2.1.16]
	at com.xxxxx.base.statsdb.object.StatsDBObjectInstance.initialize(StatsDBObjectInstance.java:292) [StatsDBObjectInstance.class:3.1.5-420-g952e67b]
	at sun.reflect.GeneratedMethodAccessor46.invoke(Unknown Source) ~[na:na]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[na:1.7.0_51]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[na:1.7.0_51]
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:64) [ScheduledMethodRunnable.class:3.1.5-420-g952e67b]
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:53) [DelegatingErrorHandlingRunnable.class:3.1.5-420-g952e67b]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [na:1.7.0_51]
	at java.util.concurrent.FutureTask.runAndReset(Unknown Source) [na:1.7.0_51]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(Unknown Source) [na:1.7.0_51]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) [na:1.7.0_51]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [na:1.7.0_51]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [na:1.7.0_51]
	at java.lang.Thread.run(Unknown Source) [na:1.7.0_51]
Caused by: com.orientechnologies.orient.core.exception.ORecordNotFoundException: The record with id '#0:4' not found
	at com.orientechnologies.orient.core.record.ORecordAbstract.reload(ORecordAbstract.java:274) ~[ORecordAbstract.class:2.1.16]
	at com.orientechnologies.orient.core.record.ORecordAbstract.reload(ORecordAbstract.java:256) ~[ORecordAbstract.class:2.1.16]
	at com.orientechnologies.orient.core.record.impl.ODocument.reload(ODocument.java:654) ~[ODocument.class:2.1.16]
	at com.orientechnologies.orient.core.type.ODocumentWrapper.reload(ODocumentWrapper.java:91) ~[ODocumentWrapper.class:2.1.16]
	at com.orientechnologies.orient.core.type.ODocumentWrapperNoClass.reload(ODocumentWrapperNoClass.java:73) ~[ODocumentWrapperNoClass.class:2.1.16]
	at com.orientechnologies.orient.core.metadata.schema.OSchemaShared.load(OSchemaShared.java:856) ~[OSchemaShared.class:2.1.16]
	at com.orientechnologies.orient.core.metadata.OMetadataDefault$1.call(OMetadataDefault.java:146) ~[OMetadataDefault$1.class:2.1.16]
	at com.orientechnologies.orient.core.metadata.OMetadataDefault$1.call(OMetadataDefault.java:141) ~[OMetadataDefault$1.class:2.1.16]
	at com.orientechnologies.common.concur.resource.OSharedContainerImpl.getResource(OSharedContainerImpl.java:64) ~[OSharedContainerImpl.class:2.1.16]
	... 34 common frames omitted
Caused by: com.orientechnologies.orient.core.exception.ODatabaseException: Error on retrieving record #0:4 (cluster: internal)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.executeReadRecord(ODatabaseDocumentTx.java:1855) ~[ODatabaseDocumentTx.class:2.1.16]
	at com.orientechnologies.orient.core.tx.OTransactionNoTx.reloadRecord(OTransactionNoTx.java:125) ~[OTransactionNoTx.class:2.1.16]
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.reload(ODatabaseDocumentTx.java:1619) ~[ODatabaseDocumentTx.class:2.1.16]
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.reload(ODatabaseDocumentTx.java:122) ~[ODatabaseDocumentTx.class:2.1.16]
	at com.orientechnologies.orient.core.record.ORecordAbstract.reload(ORecordAbstract.java:265) ~[ORecordAbstract.class:2.1.16]
	... 42 common frames omitted
Caused by: java.lang.NullPointerException: null
	at com.orientechnologies.orient.core.storage.cache.local.OWOWCache.getFilledUpTo(OWOWCache.java:607) ~[OWOWCache.class:2.1.16]
	at com.orientechnologies.orient.core.storage.impl.local.paginated.base.ODurableComponent.getFilledUpTo(ODurableComponent.java:123) ~[ODurableComponent.class:2.1.16]
	at com.orientechnologies.orient.core.storage.impl.local.paginated.OClusterPositionMap.get(OClusterPositionMap.java:254) ~[OClusterPositionMap.class:2.1.16]
	at com.orientechnologies.orient.core.storage.impl.local.paginated.OPaginatedCluster.readRecord(OPaginatedCluster.java:494) ~[OPaginatedCluster.class:2.1.16]
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.doReadRecord(OAbstractPaginatedStorage.java:2076) ~[OAbstractPaginatedStorage.class:2.1.16]
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.readRecord(OAbstractPaginatedStorage.java:1804) ~[OAbstractPaginatedStorage.class:2.1.16]
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.readRecord(OAbstractPaginatedStorage.java:782) ~[OAbstractPaginatedStorage.class:2.1.16]
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx$SimpleRecordReader.readRecord(ODatabaseDocumentTx.java:3092) ~[ODatabaseDocumentTx$SimpleRecordReader.class:2.1.16]
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.executeReadRecord(ODatabaseDocumentTx.java:1820) ~[ODatabaseDocumentTx.class:2.1.16]
	... 46 common frames omitted

**Comment by laa** [comment]
Hi 
@mrboxie how did you upgrade to 2.1.16 version.
Did you replace libraries or you make export to JSON in ver 2.0.9 and then import from JSON in version 2.1.16 ?

**Comment by mrboxie** [comment]
For server running embedded 2.1.16, the databases are all created new. There is no data from 2.0.9.

Thanks,
-Bo

**Comment by laa** [comment]
@mrboxie I see. Could you send me database ?

**Comment by mrboxie** [comment]
Sent to your gmail as db_open_issue_case_6081.tar.gz. Thank you so much.

-Bo

**Comment by laa** [comment]
Cool, get it. Will start to work on it from Tuesday.

**Comment by mrboxie** [comment]
Hi, 

We ran into another DB corruption issue with 2.1.16 embedded mode. The error message is "com.orientechnologies.common.io.OIOException: You cannot access outside the file size (0 bytes). You have requested portion 0-4 bytes. File: File: database.ocf os-size=1024, stored=0", the database cannot be reopened once the error occurred. 

Let me know if you want me to open this as a separate issue.  We also have the DB if you need it. Thank you!

2016-05-10 16:47:33.737 [pool-7-thread-1] ERROR c.m.b.s.object.StatsDBObjectInstance - An exception occurred while opening/creating the database. Retrying...
com.orientechnologies.orient.core.exception.OStorageException: Cannot open local storage '/private/statsdb' with mode=rw
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.open(OAbstractPaginatedStorage.java:226) ~[OAbstractPaginatedStorage.class:2.1.16]
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.open(ODatabaseDocumentTx.java:248) ~[ODatabaseDocumentTx.class:2.1.16]
	at com.orientechnologies.orient.core.db.ODatabaseWrapperAbstract.open(ODatabaseWrapperAbstract.java:57) ~[ODatabaseWrapperAbstract.class:2.1.16]
	at com.orientechnologies.orient.object.db.OObjectDatabaseTx.open(OObjectDatabaseTx.java:127) ~[OObjectDatabaseTx.class:2.1.16]
	at com.orientechnologies.orient.object.db.OObjectDatabaseTxPooled.<init>(OObjectDatabaseTxPooled.java:48) ~[OObjectDatabaseTxPooled.class:2.1.16]
	at com.orientechnologies.orient.object.db.OObjectDatabasePool.createResource(OObjectDatabasePool.java:51) ~[OObjectDatabasePool.class:2.1.16]
	at com.orientechnologies.orient.object.db.OObjectDatabasePool.createResource(OObjectDatabasePool.java:27) ~[OObjectDatabasePool.class:2.1.16]
	at com.orientechnologies.orient.core.db.ODatabasePoolBase$1.createNewResource(ODatabasePoolBase.java:81) ~[ODatabasePoolBase$1.class:2.1.16]
	at com.orientechnologies.orient.core.db.ODatabasePoolBase$1.createNewResource(ODatabasePoolBase.java:70) ~[ODatabasePoolBase$1.class:2.1.16]
	at com.orientechnologies.common.concur.resource.OResourcePool.getResource(OResourcePool.java:94) ~[OResourcePool.class:2.1.16]
	at com.orientechnologies.common.concur.resource.OReentrantResourcePool.getResource(OReentrantResourcePool.java:84) ~[OReentrantResourcePool.class:2.1.16]
	at com.orientechnologies.orient.core.db.ODatabasePoolAbstract.acquire(ODatabasePoolAbstract.java:158) ~[ODatabasePoolAbstract.class:2.1.16]
	at com.orientechnologies.orient.core.db.ODatabasePoolAbstract.acquire(ODatabasePoolAbstract.java:138) ~[ODatabasePoolAbstract.class:2.1.16]
	at com.orientechnologies.orient.core.db.ODatabasePoolBase.acquire(ODatabasePoolBase.java:112) ~[ODatabasePoolBase.class:2.1.16]
	at com.xxxxx.base.statsdb.object.StatsDBObjectInstance.initialize(StatsDBObjectInstance.java:292) [StatsDBObjectInstance.class:3.1.5-475-g360e030]
	at com.xxxxx.base.statsdb.object.StatsDBObjectInstance.<init>(StatsDBObjectInstance.java:602) [StatsDBObjectInstance.class:3.1.5-475-g360e030]
	at com.xxxxx.base.service.StatsDBService.createDb(StatsDBService.java:220) [StatsDBService.class:3.1.5-475-g360e030]
	at com.xxxxx.base.service.StatsDBService.prepareDb(StatsDBService.java:236) [StatsDBService.class:3.1.5-475-g360e030]
	at com.xxxxx.base.service.StatsDBService.purgeCapacityStats(StatsDBService.java:792) [StatsDBService.class:3.1.5-475-g360e030]
	at sun.reflect.GeneratedMethodAccessor69.invoke(Unknown Source) ~[na:na]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[na:1.7.0_51]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[na:1.7.0_51]
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:64) [ScheduledMethodRunnable.class:3.1.5-475-g360e030]
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:53) [DelegatingErrorHandlingRunnable.class:3.1.5-475-g360e030]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [na:1.7.0_51]
	at java.util.concurrent.FutureTask.runAndReset(Unknown Source) [na:1.7.0_51]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(Unknown Source) [na:1.7.0_51]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) [na:1.7.0_51]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [na:1.7.0_51]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [na:1.7.0_51]
	at java.lang.Thread.run(Unknown Source) [na:1.7.0_51]
Caused by: com.orientechnologies.orient.core.exception.OSerializationException: Cannot load database's configuration. The database seems corrupted
	at com.orientechnologies.orient.core.storage.impl.local.OStorageConfigurationSegment.load(OStorageConfigurationSegment.java:84) ~[OStorageConfigurationSegment.class:2.1.16]
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.open(OAbstractPaginatedStorage.java:164) ~[OAbstractPaginatedStorage.class:2.1.16]
	... 30 common frames omitted
Caused by: com.orientechnologies.common.io.OIOException: You cannot access outside the file size (0 bytes). You have requested portion 0-4 bytes. File: File: database.ocf os-size=1024, stored=0
	at com.orientechnologies.orient.core.storage.fs.OFileClassic.checkRegions(OFileClassic.java:466) ~[OFileClassic.class:2.1.16]
	at com.orientechnologies.orient.core.storage.fs.OFileClassic.readInt(OFileClassic.java:195) ~[OFileClassic.class:2.1.16]
	at com.orientechnologies.orient.core.storage.impl.local.OStorageConfigurationSegment.load(OStorageConfigurationSegment.java:78) ~[OStorageConfigurationSegment.class:2.1.16]
	... 31 common frames omitted

**Comment by mrboxie** [comment]
Hi, 

  Just wonder if you have figured out the cause of these two issues?

Thanks,
-Bo

**Comment by laa** [comment]
Hi sorry, I was busy with other issues. Now I am working on your issue.

**Comment by laa** [comment]
@mrboxie I tried to open distribution which you sent to me and got following exception:

```
2016-05-23 16:49:17:326 WARNI {db=statsdb_grantley} Storage 'statsdb_grantley' was not closed properly. Will try to recover from write ahead log [OLocalPaginatedStorage]
2016-05-23 16:49:17:335 SEVER {db=statsdb_grantley} Restore is not possible because write ahead log is empty. [OLocalPaginatedStorage]
```

Is it exact copy of database ?
If so why WAL (write ahead log is empty ) ?

**Comment by laa** [comment]
@mrboxie seems like you did not store any of the created clusters.
Did you use special settings for a database ?

**Comment by laa** [comment]
@mrboxie do you have a backup of the database which contains all clusters which you have at the moment ? Does not matter how much it is old, I need only list of clusters.

**Comment by mrboxie** [comment]
Hi Andrey,
  Thank you for getting back on this. Here is what I saw from openning "statsdb_grantley":  $ /c/dev/orientdb-community-2.1.1/bin/console.sh
OrientDB console v.2.1.1 (build UNKNOWN@r; 2015-08-31 18:08:38+0000) www.orientdb.comType 'help' to display all the supported commands.Installing extensions for GREMLIN language v.2.6.0
orientdb> connect plocal:/var/statsdb_grantley admin admin
Connecting to database [plocal:/var/statsdb_grantley] with user 'admin'...Error: com.orientechnologies.common.exception.OException: Error on creation of shared resource
Error: com.orientechnologies.orient.core.exception.ORecordNotFoundException: The record with id '#0:4' not found
Error: com.orientechnologies.orient.core.exception.ODatabaseException: Error on retrieving record #0:4 (cluster: internal)
Error: java.lang.NullPointerException
  I don't have backup DB, but have a db with exact the same structure.  Here is the output from "list clusters", the db "statsdb.tgz" is attached. orientdb {db=statsdb}> list clusters

CLUSTERS----------------------------------------------+-------+-------------------+----------------+ NAME                                         | ID    | CONFLICT STRATEGY | RECORDS        |----------------------------------------------+-------+-------------------+----------------+ cachehitdata                                 |    17 |                   |            384 | capacity                                     |    12 |                   |             13 | clusterstats                                 |    11 |                   |              3 | default                                      |     3 | version           |              0 | fileperfdata                                 |    15 |                   |             32 | index                                        |     1 | version           |              0 | internal                                     |     0 | version           |              3 | iostats                                      |    13 |                   |             26 | latencydata                                  |    18 |                   |            192 | manindex                                     |     2 | version           |              0 | nodestats                                    |    19 |                   |              9 | odocumentwrapper                             |     9 |                   |              0 | ofunction                                    |     6 |                   |              0 | orids                                        |     8 |                   |              0 | orole                                        |     4 |                   |              3 | oschedule                                    |     7 |                   |              0 | ouser                                        |     5 |                   |              3 | perfdata                                     |    16 |                   |             96 | poolstats                                    |    20 |                   |             18 | stats                                        |    10 |                   |              0 | throughput                                   |    14 |                   |             52 | vmstats                                      |    21 |                   |             32 |----------------------------------------------+-------+-------------------+----------------+ TOTAL = 22                                                               |            866 |------------------------------------------------------+-------------------+----------------+Date: Mon, 23 May 2016 07:34:11 -0700

**Comment by laa** [comment]
Hi @mrboxie , I looked through the original database which you sent me in the email , and did not see any "*.wal" files, even empty. Do you work with WAL disabled option ? I am asking because I have restored your cluster structure but all looks like data which are written to cache can not be restored because database journal files are absent.

**Comment by mrboxie** [comment]
Good point, Andrey. Yes, I just found the WAL was indeed off!

Date: Tue, 24 May 2016 07:49:30 -0700

**Comment by laa** [comment]
Hi @mrboxie we can not restore the database with WAL switched off, that is actually was the reason for this situation. Please never trade stability for performance. I am closing the issue.

**Comment by mrboxie** [comment]
Thank you so much, Andrey. Truly appreciate your help! Advice well taken - we let things fall through the cracks.
-Bo

Date: Tue, 24 May 2016 21:17:53 -0700
