### ISSUE TITLE
ORecordDuplicateException for non-duplicate record

### ISSUE THREAD

**Issue by nsitanurag** [orientechnologies/orientdb#6084]
I am using latest version of orientdb i.e. 2.1.16
and I have a index at phoneNumber
While inserting (massive inserts) in embedded mode at document level the below exception comes.

Phone number to be insert is `*141*10` and it is found duplicate with phone number `*141*10#` present at 
RID#24:117 and following exception comes

com.orientechnologies.orient.core.storage.ORecordDuplicatedException: Cannot index record contact_info#17:9387{phoneNumber:`*141*10`,lastname:loan,firstname:Air
tel,spamScore:0.0,circle:null,fullname:Airtel loan,city:null,in_contact_link:[#38:9373]} v1: found duplicated key '`*141*10`' in index 'contact_info.phoneNumber
' previously assigned to the record #24:117 RID=#24:117
at com.orientechnologies.orient.core.index.OIndexTxAwareOneValue.checkEntry(OIndexTxAwareOneValue.java:224)
        at com.orientechnologies.orient.core.index.OClassIndexManager.checkIndexedPropertiesOnUpdate(OClassIndexManager.java:376)
        at com.orientechnologies.orient.core.index.OClassIndexManager.checkIndexes(OClassIndexManager.java:583)
        at com.orientechnologies.orient.core.index.OClassIndexManager.onRecordBeforeUpdate(OClassIndexManager.java:430)
        at com.orientechnologies.orient.core.hook.ODocumentHookAbstract.onTrigger(ODocumentHookAbstract.java:256)
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.callbackHooks(ODatabaseDocumentTx.java:1070)
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.executeSaveRecord(ODatabaseDocumentTx.java:1936)
        at com.orientechnologies.orient.core.tx.OTransactionNoTx.saveRecord(OTransactionNoTx.java:159)
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.save(ODatabaseDocumentTx.java:2492)
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.save(ODatabaseDocumentTx.java:122)
        at com.orientechnologies.orient.core.record.impl.ODocument.save(ODocument.java:1768)
        at com.orientechnologies.orient.core.record.impl.ODocument.save(ODocument.java:1759)

**Comment by laa** [comment]
Hi @nsitanurag ,
Why do you think that you do not have duplicated records ?

**Comment by nsitanurag** [comment]
Because one number is `*141*10` which is found to be duplicate with `*141*10#` which should not be the case since second number contains `#` at the end.

**Comment by laa** [comment]
@nsitanurag I got the case, is it possible to send us database for this issue ?

**Comment by nsitanurag** [comment]
Sorry, I had flushed all data and it's not possible. You can make an index on a String property and try inserting *141*10# first and then *141*10 as second record in it.

**Comment by nsitanurag** [comment]
Same problem was observed with String containing `;` (semi-colon) at the end. e.g. `*141*10;`

**Comment by taburet** [comment]
@nsitanurag, I have tried following commands on 2.1.16 and develop branches, everything works fine. Could you please make it fail on your side ;)

```
create database plocal:/tmp/phones
create class Person extends V
create property Person.phone string
create index Person.phone unique

create vertex Person set phone='*141*10#'
create vertex Person set phone='*141*10'
```

**Comment by nsitanurag** [comment]
Ok. I will try and let you know.

**Comment by nsitanurag** [comment]
I am using unique_hash_index and inserting records using document api in embedded mode and not using sql commands in console. Can you try that and check?

**Comment by taburet** [comment]
@nsitanurag yes, I will check it in the embedded mode.

**Comment by taburet** [comment]
Tested on 2.1.16 and develop branches, no exceptions:

```java
final OClass class_ = db.getMetadata().getSchema().createClass("Person");
class_.createProperty("phone", OType.STRING);
class_.createIndex("Person.phone", OClass.INDEX_TYPE.UNIQUE_HASH_INDEX, "phone");

db.begin();
db.newInstance("Person").field("phone", "*141*10#").save();
db.newInstance("Person").field("phone", "*141*10").save();
db.commit();
```

Please make it fail.

**Comment by laa** [comment]
@nsitanurag could you send us the code which you use for massive insertion, to help us to reproduce the issue ?

**Comment by laa** [comment]
Close issue because of no reply. If you reproduce given issue and have information which is requested in issue feel free to reopen it.
