### ISSUE TITLE
Invalid value of TX counter Orient DB 2.1.15

### ISSUE THREAD

**Issue by jamieb22** [orientechnologies/orientdb#6089]
2016-05-05 08:49:54 C.c.s.a.du [DEBUG] failed to touch blob:Invalid value of TX counter
Caused by: com.orientechnologies.orient.core.exception.OStorageException: Invalid value of TX counter
	at com.orientechnologies.orient.core.tx.OTransactionOptimistic.rollback(OTransactionOptimistic.java:175) ~[orientdb-core-2.1.15.jar:2.1.15]
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.commit(ODatabaseDocumentTx.java:2625) ~[orientdb-core-2.1.15.jar:2.1.15]
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.commit(ODatabaseDocumentTx.java:2580) ~[orientdb-core-2.1.15.jar:2.1.15]
	at com.tinkerpop.blueprints.impls.orient.OrientBaseGraph.shutdown(OrientBaseGraph.java:1209) ~[orientdb-graphdb-2.1.15.jar:2.1.15]
	at com.tinkerpop.blueprints.impls.orient.OrientBaseGraph.shutdown(OrientBaseGraph.java:1195) ~[orientdb-graphdb-2.1.15.jar:2.1.15]
	at com.tinkerpop.blueprints.impls.orient.OrientBaseGraph.shutdown(OrientBaseGraph.java:1188) ~[orientdb-graphdb-2.1.15.jar:2.1.15]
	... 21 common frames omitted

**Comment by maggiolo00** [comment]
hi @jamieb22 

do you have a test case to reproduce this?

**Comment by jamieb22** [comment]
This issue is occurring in production. I have seen the same error in a 
number of environments, and also noticed that someone else submitted a 
bug with the same issue, which was prematurely closed. This issue 
definitely exists in Orient DB. I'll be happy to send you a production 
log file, which illustrates the seriousness of the issue. Send me your 
email address and I'll send it directly to you.

**Comment by maggiolo00** [comment]
hi @jamieb22 

you can send it to e.risa@orientdb.com

**Comment by maggiolo00** [comment]
Are you working in plocal or remote?

**Comment by jamieb22** [comment]
plocal. Very straight forward setup. I've seen this error in a number of 
environments. Something is seriously not right.

**Comment by jamieb22** [comment]
I'd have to add that we are seeing corruption in almost all environments 
where orient db is in use.

**Comment by laa** [comment]
@jamieb22 that is already fixed by critical hotfix in 2.1.16 version. https://github.com/orientechnologies/orientdb/issues/5920

**Comment by laa** [comment]
I have sent this update to Valentin, seems like you missed it.

**Comment by laa** [comment]
@jamieb22 sorry wrong issue , this one https://github.com/orientechnologies/orientdb/issues/5907 . In high load environment, NPE may be thrown. That may lead to such situation.

**Comment by jamieb22** [comment]
Andrey

Thank you. Why didn't your unit tests pick this issue up? All these 
critical issues affect the usefulness of Orient DB. If you look at H2 
database, they are in beta for more than 2 years!

**Comment by laa** [comment]
@jamieb22 to make this happens we need to run unit test for several weeks :-) and still will not be sure about result.
