### ISSUE TITLE
"Null Pointer Exception" &  "Current database instance is not active on current thread" Errors

### ISSUE THREAD

**Issue by Kirill1543** [orientechnologies/orientdb#6121]
Hi, I'm trying to upload graph from CSV with JSON ETL. 

System parameters: OrientDB 2.1.16, Linux version 2.6.32-431.el6.x86_64, JAVA 1.8

I have 2 json files - one with Vertices ID's upload and another one with edges between them. When I'm processing it in non-parallel mode - all works fine. With parallel strange errors appears at the beggining: 

Log from Vertices ETL:

`OrientDB etl v.2.1.16 (build 2.1.x@r13efec7610a3eceb539db5ebfb31dea2534aa819; 2016-04-19 10:56:07+0000) www.orientdb.com
BEGIN ETL PROCESSOR
[file] INFO Reading from file /opt/orientdb/orientdb-community-2.1.16/bin/csv/big/vert.csv with encoding UTF-8
Started parallel execution with 3 threads
Exception in thread "OrientDB ETL pipeline-0" java.lang.NullPointerException
        at com.orientechnologies.orient.etl.transformer.OVertexTransformer.begin(OVertexTransformer.java:53)
        at com.orientechnologies.orient.etl.OETLPipeline.begin(OETLPipeline.java:70)
        at com.orientechnologies.orient.etl.OETLProcessor$2.run(OETLProcessor.java:349)
        at java.lang.Thread.run(Thread.java:745)
+ extracted 2,545 rows (0 rows/sec) - 2,545 rows -> loaded 1,042 vertices (0 vertices/sec) Total time: 1000ms [0 warnings, 0 errors]
+ extracted 5,791 rows (3,246 rows/sec) - 5,791 rows -> loaded 4,288 vertices (3,246 vertices/sec) Total time: 2s [0 warnings, 0 errors]
+ extracted 10,460 rows (4,664 rows/sec) - 10,460 rows -> loaded 8,957 vertices (4,664 vertices/sec) Total time: 3001ms [0 warnings, 0 errors]
+ extracted 15,585 rows (5,119 rows/sec) - 15,585 rows -> loaded 14,082 vertices (5,119 vertices/sec) Total time: 4002ms [0 warnings, 0 errors]
+ extracted 21,444 rows (5,859 rows/sec) - 21,444 rows -> loaded 19,955 vertices (5,873 vertices/sec) Total time: 5002ms [0 warnings, 0 errors]
+ extracted 29,853 rows (8,409 rows/sec) - 29,853 rows -> loaded 28,371 vertices (8,416 vertices/sec) Total time: 6002ms [0 warnings, 0 errors]
+ extracted 41,926 rows (12,073 rows/sec) - 41,926 rows -> loaded 40,423 vertices (12,052 vertices/sec) Total time: 7002ms [0 warnings, 0 errors]
+ extracted 57,121 rows (15,195 rows/sec) - 57,121 rows -> loaded 55,627 vertices (15,204 vertices/sec) Total time: 8002ms [0 warnings, 0 errors]
+ extracted 71,932 rows (14,811 rows/sec) - 71,932 rows -> loaded 70,431 vertices (14,804 vertices/sec) Total time: 9002ms [0 warnings, 0 errors]
+ extracted 85,858 rows (13,926 rows/sec) - 85,858 rows -> loaded 84,357 vertices (13,926 vertices/sec) Total time: 10002ms [0 warnings, 0 errors]
+ extracted 97,866 rows (12,008 rows/sec) - 97,866 rows -> loaded 96,363 vertices (12,006 vertices/sec) Total time: 11002ms [0 warnings, 0 errors]
Waiting for the pipeline to finish, remaining 1493 entries to process
END ETL PROCESSOR
+ extracted 100,816 rows (4,108 rows/sec) - 100,816 rows -> loaded 100,816 vertices (6,201 vertices/sec) Total time: 11720ms [0 warnings, 0 errors]
`

Log from Edges ETL:

`OrientDB etl v.2.1.16 (build 2.1.x@r13efec7610a3eceb539db5ebfb31dea2534aa819; 2016-04-19 10:56:07+0000) www.orientdb.com
BEGIN ETL PROCESSOR
[file] INFO Reading from file /opt/orientdb/orientdb-community-2.1.16/bin/csv/big/edge.csv with encoding UTF-8
Started parallel execution with 3 threads
Exception in thread "OrientDB ETL pipeline-0" java.lang.NullPointerException
        at com.orientechnologies.orient.etl.transformer.OVertexTransformer.begin(OVertexTransformer.java:53)
        at com.orientechnologies.orient.etl.OETLPipeline.begin(OETLPipeline.java:70)
        at com.orientechnologies.orient.etl.OETLProcessor$2.run(OETLProcessor.java:349)
        at java.lang.Thread.run(Thread.java:745)
+ extracted 1,799 rows (0 rows/sec) - 1,799 rows -> loaded 297 vertices (0 vertices/sec) Total time: 1000ms [0 warnings, 0 errors]
+ extracted 2,501 rows (702 rows/sec) - 2,501 rows -> loaded 998 vertices (701 vertices/sec) Total time: 2s [0 warnings, 0 errors]
Error in Pipeline execution: java.lang.IllegalStateException: Current database instance (com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx@4fc3d6e4) is not active on current thread (Thread[OrientDB ETL pipeline-1,5,main]). Current active database is: com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx@bfd16b9
Exception in thread "OrientDB ETL pipeline-1" com.orientechnologies.orient.etl.OETLProcessHaltedException: Halt
        at com.orientechnologies.orient.etl.OETLPipeline.execute(OETLPipeline.java:142)
        at com.orientechnologies.orient.etl.OETLProcessor$2.run(OETLProcessor.java:355)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalStateException: Current database instance (com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx@4fc3d6e4) is not active on current thread (Thread[OrientDB ETL pipeline-1,5,main]). Current active database is: com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx@bfd16b9
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.checkIfActive(ODatabaseDocumentTx.java:3111)
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.getTransaction(ODatabaseDocumentTx.java:1523)
        at com.orientechnologies.orient.core.index.OIndexTxAwareOneValue.get(OIndexTxAwareOneValue.java:233)
        at com.orientechnologies.orient.core.index.OIndexTxAwareOneValue.get(OIndexTxAwareOneValue.java:41)
        at com.orientechnologies.orient.etl.transformer.OAbstractLookupTransformer.lookup(OAbstractLookupTransformer.java:87)
        at com.orientechnologies.orient.etl.transformer.OMergeTransformer.executeTransform(OMergeTransformer.java:48)
        at com.orientechnologies.orient.etl.transformer.OAbstractTransformer.transform(OAbstractTransformer.java:37)
        at com.orientechnologies.orient.etl.OETLPipeline.execute(OETLPipeline.java:109)
        ... 2 more
+ extracted 3,391 rows (890 rows/sec) - 3,391 rows -> loaded 1,888 vertices (890 vertices/sec) Total time: 3s [0 warnings, 1 errors]
+ extracted 4,357 rows (966 rows/sec) - 4,357 rows -> loaded 2,854 vertices (966 vertices/sec) Total time: 4s [0 warnings, 1 errors]
+ extracted 5,515 rows (1,158 rows/sec) - 5,515 rows -> loaded 4,012 vertices (1,158 vertices/sec) Total time: 5s [0 warnings, 1 errors]
+ extracted 6,948 rows (1,433 rows/sec) - 6,948 rows -> loaded 5,445 vertices (1,433 vertices/sec) Total time: 6s [0 warnings, 1 errors]
+ extracted 8,499 rows (1,551 rows/sec) - 8,499 rows -> loaded 6,996 vertices (1,551 vertices/sec) Total time: 7s [0 warnings, 1 errors]
+ extracted 10,605 rows (2,103 rows/sec) - 10,605 rows -> loaded 9,102 vertices (2,103 vertices/sec) Total time: 8001ms [0 warnings, 1 errors]
+ extracted 12,959 rows (2,354 rows/sec) - 12,959 rows -> loaded 11,456 vertices (2,354 vertices/sec) Total time: 9001ms [0 warnings, 1 errors]
+ extracted 16,065 rows (3,106 rows/sec) - 16,065 rows -> loaded 14,562 vertices (3,106 vertices/sec) Total time: 10001ms [0 warnings, 1 errors]
`

After this ETL continues with same speed (3k rows/s) like it works in 1 thread. I tried to find similar issues - 0 positive results. Also, seems like strange Null Pointer exception was fixed in 2.1.16 (as i understand).

Jsons and CSVs added:

[edges2P.txt](https://github.com/orientechnologies/orientdb/files/259760/edges2P.txt)
[vertP.txt](https://github.com/orientechnologies/orientdb/files/259759/vertP.txt)

[vert.txt](https://github.com/orientechnologies/orientdb/files/259763/vert.txt)

file with edges is very big, it has simple structure:
ids,ide,val - ID Start Vertex, ID End Vertex, Weight
1,2,0
2,3,1
1,4,2
...

**Comment by Kirill1543** [comment]
More information: 
For Vertices this error does no effect - no differences after end of etl (but seems like 1 thread crashes and it works in 2)
For Edges - still no differences except speed - loading continues in 1 thread (it works with the same speed in non-parallel mode)

**Comment by robfrank** [comment]
hi, sorry for long silent. I fixed a lot of things on 2.2.x series about MT on ETL.
So I invite you to try with latest 2.2.6. Note that the speed-up using parallel is not linear, so even on a 8 cores processor you will not reach an 8x performance.

**Comment by robfrank** [comment]
no response for a while, feel free to reopen if necessary
