### ISSUE TITLE
[ Orient version 2.2.0-rc1 ] Binary Protocol compatibility failure

### ISSUE THREAD

**Issue by Ostico** [orientechnologies/orientdb#6143]
The db_open command to the server seems to not works anymore:

```python
import pyorient
client = pyorient.OrientDB( "localhost", 2424 )
client.db_open(
    'test_tr', "admin", "admin", pyorient.DB_TYPE_GRAPH
)

# Traceback (most recent call last):
#   File "<stdin>", line 2, in <module>
#   File "pyorient/orient.py", line 379, in db_open
#     .prepare((db_name, user, password, db_type, client_id)).send().fetch_response()
#   File "pyorient/messages/database.py", line 100, in fetch_response
#     result = super(DbOpenMessage, self).fetch_response()
#   File "pyorient/messages/base.py", line 256, in fetch_response
#     self._decode_all()
#   File "pyorient/messages/base.py", line 240, in _decode_all
#     self._decode_header()
#   File "pyorient/messages/base.py", line 192, in _decode_header
#     [ exception_message.decode( 'utf8' ) ]
# pyorient.exceptions.PyOrientSecurityAccessException: com.orientechnologies.orient.core.exception.OSecurityAccessException - User or password not valid for database: 'test_tr'
#     Storage URL="memory:test_tr"
```

I tried with root credentials also but i got the same result ( this time i added the binary dump for the request ):

```python
client.db_open(
    db_name, "root", "root", pyorient.DB_TYPE_GRAPH, ""
)

#  Request :
#  00000000: 03 00 00 00 26 00 00 00  28 4F 72 69 65 6E 74 44  ....&...(OrientD
#  00000010: 42 20 50 79 74 68 6F 6E  20 62 69 6E 61 72 79 20  B Python binary 
#  00000020: 63 6C 69 65 6E 74 20 28  70 79 6F 72 69 65 6E 74  client (pyorient
#  00000030: 29 00 00 00 05 31 2E 34  2E 39 00 21 00 00 00 00  )....1.4.9.!....
#  00000040: 00 00 00 13 4F 52 65 63  6F 72 64 44 6F 63 75 6D  ....ORecordDocum
#  00000050: 65 6E 74 32 63 73 76 00  00 00 00 07 74 65 73 74  ent2csv.....test
#  00000060: 5F 74 72 00 00 00 05 67  72 61 70 68 00 00 00 04  _tr....graph....
#  00000070: 72 6F 6F 74 00 00 00 04  72 6F 6F 74              root....root
  
#  Error
#  Traceback (most recent call last):
#    File "/Users/Hashashiyyin/PycharmProjects/pyorient/tests/test_record_contents.py", line 35, in setUp
#      db_name, "root", "root", pyorient.DB_TYPE_GRAPH, ""
#    File "/Users/Hashashiyyin/PycharmProjects/pyorient/pyorient/orient.py", line 379, in db_open
#      .prepare((db_name, user, password, db_type, client_id)).send().fetch_response()
#    File "/Users/Hashashiyyin/PycharmProjects/pyorient/pyorient/messages/database.py", line 100, in fetch_response
#      result = super(DbOpenMessage, self).fetch_response()
#    File "/Users/Hashashiyyin/PycharmProjects/pyorient/pyorient/messages/base.py", line 256, in fetch_response
#      self._decode_all()
#    File "/Users/Hashashiyyin/PycharmProjects/pyorient/pyorient/messages/base.py", line 240, in _decode_all
#      self._decode_header()
#    File "/Users/Hashashiyyin/PycharmProjects/pyorient/pyorient/messages/base.py", line 192, in _decode_header
#      [ exception_message.decode( 'utf8' ) ]
#  PyOrientSecurityAccessException: com.orientechnologies.orient.core.exception.OSecurityAccessException - User or password not valid for database: 'test_tr'
#      Storage URL="memory:test_tr"
``` 

When i try from the console instead:

```
orientdb> connect remote:localhost/test_tr admin admin

Connecting to database [remote:localhost/test_tr] with user 'admin'...OK
orientdb {db=test_tr}>
```

I think that the new protocol 36 is no more compatible with the previous. I studied the binary requests made from the console and from the python driver, they are very different.

```
#### Python driver:
2016-05-14 16:11:45:955 INFO  {db=test_tr} /10.0.2.2:65279 - Reading byte (1 byte)... [OChannelBinaryServer]
2016-05-14 16:11:47:906 INFO  {db=test_tr} /10.0.2.2:65279 - Read byte: 3 [OChannelBinaryServer]
2016-05-14 16:11:47:908 INFO  {db=test_tr} /10.0.2.2:65279 - Reading int (4 bytes)... [OChannelBinaryServer]
2016-05-14 16:11:47:910 INFO  {db=test_tr} /10.0.2.2:65279 - Read int: 37 [OChannelBinaryServer]
2016-05-14 16:11:47:911 INFO  {db=test_tr} /10.0.2.2:65279 - Reading string (4+N bytes)... [OChannelBinaryServer]
2016-05-14 16:11:47:912 INFO  {db=test_tr} /10.0.2.2:65279 - Read string: OrientDB Python binary client (pyorient) [OChannelBinaryServer]
2016-05-14 16:11:47:913 INFO  {db=test_tr} /10.0.2.2:65279 - Reading string (4+N bytes)... [OChannelBinaryServer]
2016-05-14 16:11:47:913 INFO  {db=test_tr} /10.0.2.2:65279 - Read string: 1.4.9 [OChannelBinaryServer]
2016-05-14 16:11:47:914 INFO  {db=test_tr} /10.0.2.2:65279 - Reading short (2 bytes)... [OChannelBinaryServer]
2016-05-14 16:11:47:919 INFO  {db=test_tr} /10.0.2.2:65279 - Read short: 33 [OChannelBinaryServer]
2016-05-14 16:11:47:922 INFO  {db=test_tr} /10.0.2.2:65279 - Reading string (4+N bytes)... [OChannelBinaryServer]
2016-05-14 16:11:47:923 INFO  {db=test_tr} /10.0.2.2:65279 - Read string:  [OChannelBinaryServer]
2016-05-14 16:11:47:924 INFO  {db=test_tr} /10.0.2.2:65279 - Reading string (4+N bytes)... [OChannelBinaryServer]
2016-05-14 16:11:47:925 INFO  {db=test_tr} /10.0.2.2:65279 - Read string: ORecordDocument2csv [OChannelBinaryServer]
2016-05-14 16:11:47:926 INFO  {db=test_tr} /10.0.2.2:65279 - Reading boolean (1 byte)... [OChannelBinaryServer]
2016-05-14 16:11:47:927 INFO  {db=test_tr} /10.0.2.2:65279 - Read boolean: false [OChannelBinaryServer]
2016-05-14 16:11:47:928 INFO  {db=test_tr} /10.0.2.2:65279 - Reading string (4+N bytes)... [OChannelBinaryServer]
2016-05-14 16:11:47:939 INFO  {db=test_tr} /10.0.2.2:65279 - Read string: test_tr [OChannelBinaryServer]
2016-05-14 16:11:47:942 INFO  {db=test_tr} /10.0.2.2:65279 - Reading string (4+N bytes)... [OChannelBinaryServer]
2016-05-14 16:11:47:944 INFO  {db=test_tr} /10.0.2.2:65279 - Read string: graph [OChannelBinaryServer]
2016-05-14 16:11:47:947 INFO  {db=test_tr} /10.0.2.2:65279 - Reading string (4+N bytes)... [OChannelBinaryServer]
2016-05-14 16:11:47:948 INFO  {db=test_tr} /10.0.2.2:65279 - Read string: admin [OChannelBinaryServer]

#### Java driver console
2016-05-14 16:27:25:302 INFO  /10.0.2.2:65317 - Reading byte (1 byte)... [OChannelBinaryServer]
2016-05-14 16:27:25:306 INFO  /10.0.2.2:65317 - Read byte: 3 [OChannelBinaryServer]
2016-05-14 16:27:25:307 INFO  /10.0.2.2:65317 - Reading int (4 bytes)... [OChannelBinaryServer]
2016-05-14 16:27:25:307 INFO  /10.0.2.2:65317 - Read int: -2 [OChannelBinaryServer]
2016-05-14 16:27:25:308 INFO  /10.0.2.2:65317 - Reading string (4+N bytes)... [OChannelBinaryServer]
2016-05-14 16:27:25:309 INFO  /10.0.2.2:65317 - Read string: OrientDB Java [OChannelBinaryServer]
2016-05-14 16:27:25:309 INFO  /10.0.2.2:65317 - Reading string (4+N bytes)... [OChannelBinaryServer]
2016-05-14 16:27:25:310 INFO  /10.0.2.2:65317 - Read string: 2.2.0-rc1 [OChannelBinaryServer]
2016-05-14 16:27:25:311 INFO  /10.0.2.2:65317 - Reading short (2 bytes)... [OChannelBinaryServer]
2016-05-14 16:27:25:311 INFO  /10.0.2.2:65317 - Read short: 36 [OChannelBinaryServer]
2016-05-14 16:27:25:312 INFO  /10.0.2.2:65317 - Reading string (4+N bytes)... [OChannelBinaryServer]
2016-05-14 16:27:25:313 INFO  /10.0.2.2:65317 - Reading string (4+N bytes)... [OChannelBinaryServer]
2016-05-14 16:27:25:313 INFO  /10.0.2.2:65317 - Read string: ORecordSerializerBinary [OChannelBinaryServer]
2016-05-14 16:27:25:314 INFO  /10.0.2.2:65317 - Reading boolean (1 byte)... [OChannelBinaryServer]
2016-05-14 16:27:25:315 INFO  /10.0.2.2:65317 - Read boolean: true [OChannelBinaryServer]
2016-05-14 16:27:25:315 INFO  /10.0.2.2:65317 - Reading boolean (1 byte)... [OChannelBinaryServer]
2016-05-14 16:27:25:316 INFO  /10.0.2.2:65317 - Read boolean: true [OChannelBinaryServer]
2016-05-14 16:27:25:317 INFO  /10.0.2.2:65317 - Reading boolean (1 byte)... [OChannelBinaryServer]
2016-05-14 16:27:25:317 INFO  /10.0.2.2:65317 - Read boolean: true [OChannelBinaryServer]
2016-05-14 16:27:25:318 INFO  /10.0.2.2:65317 - Reading string (4+N bytes)... [OChannelBinaryServer]
2016-05-14 16:27:25:319 INFO  /10.0.2.2:65317 - Read string: test_tr [OChannelBinaryServer]
2016-05-14 16:27:25:319 INFO  /10.0.2.2:65317 - Reading string (4+N bytes)... [OChannelBinaryServer]
2016-05-14 16:27:25:320 INFO  /10.0.2.2:65317 - Read string: admin [OChannelBinaryServer]
2016-05-14 16:27:25:320 INFO  /10.0.2.2:65317 - Reading string (4+N bytes)... [OChannelBinaryServer]
2016-05-14 16:27:25:321 INFO  /10.0.2.2:65317 - Read string: admin [OChannelBinaryServer]
```

I some of my attempts i tried to configure the driver to communicate showing himself as protocol 36, but the header response in the procol is changed, so no responses can be read by the client.

The protocol is obviously changed. 

So, i configured the driver to connect showing himself as protocol 33.
I suppose that the server worked in some backward compatibility. 
The ```connect/drop/create``` messages worked, but the ```open``` one is broken because it is different.

When the protocol changes in some manner, a communication to the maintainers must be sent with the changes and with the the new technical specifications and the online documentation updated accordingly. 

I suppose all drivers will be broken with this new release.

**Comment by tglman** [comment]
hi @Ostico,

I update the documentation for the version 34, 35, 36. for the version 33 be aware that the main difference is that the DB_TYPE String has been removed, as reported here: http://orientdb.com/docs/last/Network-Binary-Protocol.html#version-33

in case try to use the version 32.

hope it help, in any case feel free to contact me direcly so we can speed up any troubleshooting.

**Comment by lvca** [comment]
I added the documentation for connect and create database.
