### ISSUE TITLE
server.bat in orientDb 2.2.0

### ISSUE THREAD

**Issue by kumarkshiva** [orientechnologies/orientdb#6165]
## Expected behavior and actual behavior
server.bat when run on windows fails with below error
Invalid maximum direct memory size: -XX:MaxDirectMemorySize=512g
The specified size exceeds the maximum representable size.
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.

## Steps to reproduce the problem
run server.bat

## Important Questions
MaxDirectMemorySize=512g    is to be changed as MaxDirectMemorySize=512m
### Runninng Mode
- [ ] Embedded, using PLOCAL access mode
- [ ] Embedded, using MEMORY access mode
- [ ] Remote

### Misc
- [ ] I have a distributed setup with multiple servers. How many? 
- [ ] I'm using the Enterprise Edition

### OrientDB Version
- [ ] v2.0.x - Please specify last number: 
- [ ] v2.1.x - Please specify last number: 
- [ X] v2.2.x - Please specify last number: 

### Operating System
- [ ] Linux
- [ ] MacOSX
- [X ] Windows
- [ ] Other Unix
- [ ] Other, name? 

### Java Version
- [ ] 6
- [ ] 7
- [ X] 8

**Comment by lvca** [comment]
@kumarkshiva 500mb is too low. You need few GB at least.

**Comment by kumarkshiva** [comment]
in the server.bat, which is the installer script provided by orientDB, it is a mentioed as MaxDirectMemorySize=512g .
This option better to be be changed as MaxDirectMemorySize=512m or more .
It can be user defined variable also instead of 512gb.

If put as 512 gb, installation fails.

**Comment by DeveloperWonk** [comment]
Encounter this issue on Windows 10 laptop with 4GB ram running JDK 1.8.0.51.  I could not start server for the first time.  I resolved the issue by remove MaxDirectMemorySize from the java_opts_script environment variable.

**Comment by robfrank** [comment]
I guess you have a 32bit system and/or JVM. On a 32bit system the maximun value is 2g. 
Can you confirm that your system or your JVM are 32bit?

**Comment by lgaquino** [comment]
I'm also facing this problem. 
(v2.2 running embedded on my machine => Win7 64bit on a quadCore CPU, with 8gb of RAM.)

I can use the DB via Studio. But my applications cannot properly open a connection. To be more specific:

> 16:41:25,667 ERROR [org.apache.catalina.core.ContainerBase.[jboss.web].[default-host].[/lattes].[Faces Servlet]] (http-localhost/127.0.0.1:8080-1) JBWEB000236: Servlet.service() for servlet Faces Servlet threw exception: java.lang.OutOfMemoryError
	at sun.misc.Unsafe.allocateMemory(Native Method) [rt.jar:1.7.0_51]
	at java.nio.DirectByteBuffer.<init>(DirectByteBuffer.java:127) [rt.jar:1.7.0_51]
	at java.nio.ByteBuffer.allocateDirect(ByteBuffer.java:306) [rt.jar:1.7.0_51]
	at com.orientechnologies.common.directmemory.OByteBufferPool.allocateBuffer(OByteBufferPool.java:309) [orientdb-core-2.2.0.jar:2.2.0]
	at com.orientechnologies.common.directmemory.OByteBufferPool.acquireDirect(OByteBufferPool.java:228) [orientdb-core-2.2.0.jar:2.2.0]
	at com.orientechnologies.orient.core.storage.impl.local.paginated.wal.OLogSegment.readRecord(OLogSegment.java:415) [orientdb-core-2.2.0.jar:2.2.0]
	at com.orientechnologies.orient.core.storage.impl.local.paginated.wal.ODiskWriteAheadLog.read(ODiskWriteAheadLog.java:656) [orientdb-core-2.2.0.jar:2.2.0]
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.restoreFromWAL(OAbstractPaginatedStorage.java:3618) [orientdb-core-2.2.0.jar:2.2.0]
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.recoverIfNeeded(OAbstractPaginatedStorage.java:2945) [orientdb-core-2.2.0.jar:2.2.0]
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.open(OAbstractPaginatedStorage.java:206) [orientdb-core-2.2.0.jar:2.2.0]
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.open(ODatabaseDocumentTx.java:231) [orientdb-core-2.2.0.jar:2.2.0]
	at com.orientechnologies.orient.core.db.OPartitionedDatabasePool$DatabaseDocumentTxPolled.internalOpen(OPartitionedDatabasePool.java:140) [orientdb-core-2.2.0.jar:2.2.0]
	at com.orientechnologies.orient.core.db.OPartitionedDatabasePool.openDatabase(OPartitionedDatabasePool.java:391) [orientdb-core-2.2.0.jar:2.2.0]
	at com.orientechnologies.orient.core.db.OPartitionedDatabasePool.acquire(OPartitionedDatabasePool.java:350) [orientdb-core-2.2.0.jar:2.2.0]
	at com.tinkerpop.blueprints.impls.orient.OrientBaseGraph.<init>(OrientBaseGraph.java:140) [orientdb-graphdb-2.2.0.jar:2.2.0]
	at com.tinkerpop.blueprints.impls.orient.OrientTransactionalGraph.<init>(OrientTransactionalGraph.java:78) [orientdb-graphdb-2.2.0.jar:2.2.0]
	at com.tinkerpop.blueprints.impls.orient.OrientGraph.<init>(OrientGraph.java:135) [orientdb-graphdb-2.2.0.jar:2.2.0]
	at com.tinkerpop.blueprints.impls.orient.OrientGraphFactory.getTx(OrientGraphFactory.java:130) [orientdb-graphdb-2.2.0.jar:2.2.0]


I get the message above right after going through the following code:
`  OrientGraphFactory factory = new OrientGraphFactory(path).setupPool(1, 10);
            return factory.getTx();`


v2.1 worked fine though...

**Comment by robfrank** [comment]
```
 java.lang.OutOfMemoryError at sun.misc.Unsafe.allocateMemory(Native Method) [rt.jar:1.7.0_51] at java.nio.DirectByteBuffer
```
 Please, try with a MaxDirectMemorySize higher than 500m, as Luca stated. And please, tell me if your OS or jour JVM are 32bit.

**Comment by DeveloperWonk** [comment]
Rob, Yes I am using 32bit 1.8 JDK on 64bit Windows 10.  I also tried on Win7 64bit/32bit 1.7JDK with same result.  To clarify, I received the error posted by original submtter when I tried to run server.bat the first time.  Setting MaxDirectMemorySize=2g resolves the original issue but the server throws an exception during startup and fails to start.  If I run Server.bat again the server starts up and I am prompted to enter the root password.  
 
```
2016-05-23 18:49:57:420 INFO  {db=OSystem} Creating the system database 'OSystem' for current server [OSystemDatabase]Exception in thread "main" java.lang.OutOfMemoryError
        at sun.misc.Unsafe.allocateMemory(Native Method)
        at java.nio.DirectByteBuffer.<init>(DirectByteBuffer.java:127)
        at java.nio.ByteBuffer.allocateDirect(ByteBuffer.java:311)
        at com.orientechnologies.common.directmemory.OByteBufferPool.allocateBuffer(OByteBufferPool.java:309)
        at com.orientechnologies.common.directmemory.OByteBufferPool.acquireDirect(OByteBufferPool.java:228)
        at com.orientechnologies.orient.core.storage.cache.local.OWOWCache.cacheFileContent(OWOWCache.java:1255)
        at com.orientechnologies.orient.core.storage.cache.local.OWOWCache.load(OWOWCache.java:617)
        at com.orientechnologies.orient.core.storage.cache.local.twoq.O2QCache.updateCache(O2QCache.java:1200)
        at com.orientechnologies.orient.core.storage.cache.local.twoq.O2QCache.doLoad(O2QCache.java:439)
        at com.orientechnologies.orient.core.storage.cache.local.twoq.O2QCache.allocateNewPage(O2QCache.java:489)
        at com.orientechnologies.orient.core.storage.impl.local.paginated.atomicoperations.OAtomicOperation.commitChanges(OAtomicOperation.java:426)
        at com.orientechnologies.orient.core.storage.impl.local.paginated.atomicoperations.OAtomicOperationsManager.endAtomicOperation(OAtomicOperationsManager.java:420)
        at com.orientechnologies.orient.core.storage.impl.local.paginated.base.ODurableComponent.endAtomicOperation(ODurableComponent.java:118)
        at com.orientechnologies.orient.core.storage.impl.local.paginated.OPaginatedCluster.create(OPaginatedCluster.java:197)
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.addClusterInternal(OAbstractPaginatedStorage.java:3349)
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.doAddCluster(OAbstractPaginatedStorage.java:3330)
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.create(OAbstractPaginatedStorage.java:381)
        at com.orientechnologies.orient.core.storage.impl.local.paginated.OLocalPaginatedStorage.create(OLocalPaginatedStorage.java:120)
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.create(ODatabaseDocumentTx.java:378)
        at com.orientechnologies.orient.server.OSystemDatabase.init(OSystemDatabase.java:106)
        at com.orientechnologies.orient.server.OSystemDatabase.<init>(OSystemDatabase.java:42)
        at com.orientechnologies.orient.server.OServer.initSystemDatabase(OServer.java:1217)
        at com.orientechnologies.orient.server.OServer.activate(OServer.java:343)
        at com.orientechnologies.orient.server.OServerMain.main(OServerMain.java:41)
```

**Comment by anywhichway** [comment]
Just installed v2.2.0, getting the same issue. Will report further when I try the above steps.

java -version
java version "1.8.0_65"
Java(TM) SE Runtime Environment (build 1.8.0_65-b17)
Java HotSpot(TM) Client VM (build 25.65-b01, mixed mode, sharing)

8GB RAM
64bit Windows v10 Pro
i7-4510U CPU

**Comment by anywhichway** [comment]
I completely uninstalled Java and then re-installed u92 64 bit. This resolved the memory issue. However, I now have a number of other issues; not the least of which is errors creating a database. Will log new issues for those.
