### ISSUE TITLE
Clearing OrientDB 2.2.0-rc1 for tests leads to NPE's

### ISSUE THREAD

**Issue by Jotschi** [orientechnologies/orientdb#6171]
## Expected behavior and actual behavior

We are currently clearing our OrientDB 2.1.7 embedded in-memory db for unit tests using OrientGraphNoTx#drop(). 

In 2.2.0-rc1 this is now effectively closing the internal OrientDB storage and thus setting all storage references to null. Further calls (using 2.2.0-rc1) would now cause NPE's since "storage" is null.

```
SEVERE: Error during context close for db null
java.lang.NullPointerException
	at com.orientechnologies.orient.core.db.OPartitionedDatabasePool$DatabaseDocumentTxPolled.close(OPartitionedDatabasePool.java:160)
	at com.tinkerpop.blueprints.impls.orient.OrientBaseGraph.shutdown(OrientBaseGraph.java:1160)
	at com.tinkerpop.blueprints.impls.orient.OrientBaseGraph.shutdown(OrientBaseGraph.java:1132)
	at com.tinkerpop.blueprints.impls.orient.OrientBaseGraph.shutdown(OrientBaseGraph.java:1125)
	at com.gentics.mesh.graphdb.orientdb.OrientDBDropTest.cleanup(OrientDBDropTest.java:21)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:33)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)
```

## Steps to reproduce the problem

```
import static org.junit.Assert.assertEquals;

import org.junit.After;
import org.junit.Test;

import com.tinkerpop.blueprints.impls.orient.OrientGraphFactory;
import com.tinkerpop.blueprints.impls.orient.OrientGraphNoTx;

public class OrientDBDropTest {

	OrientGraphFactory factory = new OrientGraphFactory("memory:tinkerpop");

	@After
	public void cleanup() {
		OrientGraphNoTx noTx = factory.getNoTx();
		try {
			noTx.drop();
		} finally {
			noTx.shutdown();
		}
	}

	@Test
	public void testOne() {
		assertCleanup();
	}

	@Test
	public void testTwo() {
		assertCleanup();
	}

	private void assertCleanup() {
		OrientGraphNoTx noTx = factory.getNoTx();
		try {
			noTx.addVertex(null);
			assertEquals(1, noTx.countVertices());
		} finally {
			noTx.shutdown();
		}
	}
}
```

### Runninng Mode
- [ x] Embedded, using MEMORY access mode

### OrientDB Version
- [x ] v2.2.0-rc1 

### Operating System
- [x ] Linux

### Java Version
- [x ] 8

**Comment by lvca** [comment]
@Jotschi could you please try with 2.2.0?

**Comment by Jotschi** [comment]
@lvca Same exception when using 2.2.0 -  Slightly different line numbers:

```
java.lang.NullPointerException
	at com.orientechnologies.orient.core.db.OPartitionedDatabasePool$DatabaseDocumentTxPolled.close(OPartitionedDatabasePool.java:160)
	at com.tinkerpop.blueprints.impls.orient.OrientBaseGraph.shutdown(OrientBaseGraph.java:1153)
	at com.tinkerpop.blueprints.impls.orient.OrientBaseGraph.shutdown(OrientBaseGraph.java:1125)
	at com.tinkerpop.blueprints.impls.orient.OrientBaseGraph.shutdown(OrientBaseGraph.java:1118)
	at com.gentics.test.orientdb.ODBTest.cleanup(ODBTest.java:21)
```

**Comment by lvca** [comment]
Found, fixed in develop branch.
