### ISSUE TITLE
confusing exception when exiting an OSGi application with OrientDB embedded

### ISSUE THREAD

**Issue by almibe** [orientechnologies/orientdb#6181]
## Expected behavior and actual behavior
When I shutdown an OSGi application that has orientdb embedded in it I am getting the following error.

```
Exception in thread "Thread-6" java.lang.NoClassDefFoundError: com/orientechnologies/orient/core/storage/cache/local/ConcurrentLRUList$OCacheEntryIterator
	at com.orientechnologies.orient.core.storage.cache.local.ConcurrentLRUList.iterator(ConcurrentLRUList.java:306)
	at com.orientechnologies.orient.core.storage.cache.local.O2QCache.clearCacheContent(O2QCache.java:601)
	at com.orientechnologies.orient.core.storage.cache.local.O2QCache.clear(O2QCache.java:381)
	at com.orientechnologies.orient.core.engine.local.OEngineLocalPaginated.shutdown(OEngineLocalPaginated.java:79)
	at com.orientechnologies.orient.core.Orient.shutdown(Orient.java:284)
	at com.orientechnologies.orient.core.OrientShutdownHook.run(OrientShutdownHook.java:32)
Caused by: java.lang.ClassNotFoundException: Unable to load class 'com.orientechnologies.orient.core.storage.cache.local.ConcurrentLRUList$OCacheEntryIterator' because the bundle wiring for com.orientechnologies.orientdb-core is no longer valid.
	at org.apache.felix.framework.BundleWiringImpl.findClassOrResourceByDelegation(BundleWiringImpl.java:1512)
	at org.apache.felix.framework.BundleWiringImpl.access$400(BundleWiringImpl.java:77)
	at org.apache.felix.framework.BundleWiringImpl$BundleClassLoader.loadClass(BundleWiringImpl.java:1988)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 6 more
```

## Steps to reproduce the problem
As a simple test case I am getting this error even if I run the following code anywhere in my application
```
        ODatabaseDocumentTx db = new ODatabaseDocumentTx ( "plocal:/home/alex/tmp/orient" ) ;
        db.create();
        db.close();
```
I wouldn't think I should be getting any exceptions related to OrientDB after closing the database.  I also get the same error when using a factory and calling close() on it.

### Runninng Mode
- [X] Embedded, using PLOCAL access mode
- [X] Embedded, using MEMORY access mode
- [ ] Remote

### Misc
- [ ] I have a distributed setup with multiple servers. How many? 
- [ ] I'm using the Enterprise Edition

### OrientDB Version
- [X] v2.0.x - Please specify last number: 
- [X] v2.1.x - Please specify last number: 
- [X] v2.2.x - Please specify last number: 

### Operating System
- [X] Linux
- [ ] MacOSX
- [ ] Windows
- [ ] Other Unix
- [ ] Other, name? 

### Java Version
- [ ] 6
- [ ] 7
- [X] 8

**Comment by almibe** [comment]
It looks like I can manually shut down OrientDB before the application exits by calling 
```
Orient.instance().shutdown();
```
This works fine for me so I'll close this issue.
