### ISSUE TITLE
OrientDB 2.2.0 - ORecordDuplicatedException during vertex creation

### ISSUE THREAD

**Issue by Jotschi** [orientechnologies/orientdb#6183]
## Expected behavior and actual behavior

Creating vertices causes ORecordDuplicatedException when creating vertices and using a simple UNIQUE_HASH_INDEX index on a single vertex property which is not set within trx. The same code works fine in 2.1.7.  It seems that null values were not causing a duplicate error in 2.1.7. Is there may a way to configure this case in 2.2.x?

```
com.orientechnologies.orient.core.storage.ORecordDuplicatedException: Cannot index record User: found duplicated key 'null' in index 'testIndex' previously assigned to the record #25:0
	Storage URL="memory:tinkerpop"INDEX=testIndex RID=#25:0
	at com.orientechnologies.orient.core.index.OIndexTxAwareOneValue.checkEntry(OIndexTxAwareOneValue.java:247)
	at com.orientechnologies.orient.core.index.OClassIndexManager.checkIndexedPropertiesOnCreation(OClassIndexManager.java:326)
	at com.orientechnologies.orient.core.index.OClassIndexManager.checkIndexes(OClassIndexManager.java:570)
	at com.orientechnologies.orient.core.index.OClassIndexManager.onRecordBeforeCreate(OClassIndexManager.java:391)
	at com.orientechnologies.orient.core.hook.ODocumentHookAbstract.onTrigger(ODocumentHookAbstract.java:227)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.callbackHooks(ODatabaseDocumentTx.java:1052)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.executeSaveRecord(ODatabaseDocumentTx.java:1990)
	at com.orientechnologies.orient.core.tx.OTransactionNoTx.saveNew(OTransactionNoTx.java:243)
	at com.orientechnologies.orient.core.tx.OTransactionNoTx.saveRecord(OTransactionNoTx.java:176)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.save(ODatabaseDocumentTx.java:2529)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.save(ODatabaseDocumentTx.java:1)
	at com.orientechnologies.orient.core.record.impl.ODocument.save(ODocument.java:1817)
	at com.orientechnologies.orient.core.record.impl.ODocument.save(ODocument.java:1808)
	at com.tinkerpop.blueprints.impls.orient.OrientElement.save(OrientElement.java:334)
	at com.tinkerpop.blueprints.impls.orient.OrientElement.save(OrientElement.java:316)
	at com.tinkerpop.blueprints.impls.orient.OrientBaseGraph.addVertex(OrientBaseGraph.java:565)
	at com.tinkerpop.blueprints.impls.orient.OrientBaseGraph.addVertex(OrientBaseGraph.java:495)
	at com.gentics.test.orientdb.NullIndexTest.testIndexConflict(NullIndexTest.java:33)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)
```

## Steps to reproduce the problem

```
package com.gentics.test.orientdb;

import org.junit.Test;

import com.orientechnologies.orient.core.metadata.schema.OClass;
import com.orientechnologies.orient.core.metadata.schema.OType;
import com.tinkerpop.blueprints.impls.orient.OrientGraphFactory;
import com.tinkerpop.blueprints.impls.orient.OrientGraphNoTx;
import com.tinkerpop.blueprints.impls.orient.OrientVertexType;

public class NullIndexTest {

	OrientGraphFactory factory = new OrientGraphFactory("memory:tinkerpop");

	@Test
	public void testIndexConflict() {

		OrientGraphNoTx tx = factory.getNoTx();
		try {
			String name = "User";
			OrientVertexType v = tx.getVertexType(name);
			v = tx.createVertexType(name, "V");
			v.createProperty("someField", OType.STRING);
			v.createIndex("testIndex", OClass.INDEX_TYPE.UNIQUE_HASH_INDEX, "someField");
		} finally {
			tx.shutdown();
		}

		// Add initial vertex
		OrientGraphNoTx noTx = factory.getNoTx();
		try {
			noTx.addVertex("class:User");
			noTx.addVertex("class:User");
		} finally {
			noTx.shutdown();
		}

	}
}
```

### Runninng Mode
- [x] Embedded, using MEMORY access mode

### OrientDB Version
- [x] v2.2.0 / 2.2.1-SNAPSHOT (develop branch / 1990b3dd93949b04039373bf0cb914fb7adeb007)

### Operating System
- [x] Linux

### Java Version
- [x] 8

**Comment by luigidellaquila** [comment]
Hi @Jotschi 

This must be related to this change:

http://orientdb.com/docs/last/Release-2.2.0.html 
(see "NULL values in indexes")

In v.2.2 null values are indexed by default and they are considered in the uniqueness constraints. You can restore the old behavior explicitly declaring that indexes ignore null values:

```
CREATE INDEX indexName ON ClassName (property1, property2) UNIQUE METADATA {ignoreNullValues: true}
```

Thanks

Luigi

**Comment by Jotschi** [comment]
Example via java:
`
v.createIndex("testIndex", OClass.INDEX_TYPE.UNIQUE_HASH_INDEX.toString(), null, new ODocument().fields("ignoreNullValues", true), new String[]{ "someField"});`
