### ISSUE TITLE
Cannot install plugin on 2.2.0 (worked with 2.1.x)

### ISSUE THREAD

**Issue by mriehl** [orientechnologies/orientdb#6187]
## Expected behavior and actual behavior
I have a plugin (`.jar` format) in the `plugins` directory.
It's been working fine for all of `2.1.x`.

On `2.2.0` I get this when starting the orientdb server:

```
2016-05-23 10:06:07:044 SEVER ODefaultServerSecurity.loadConfig() Could not access the security JSON file: /orientdb-home/config/security.json 
[ODefaultServerSecurity]Error on installing dynamic plugin 'my-plugin'
java.lang.ClassNotFoundException: com.company.orientdb.MyPlugin
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:264)
        at com.orientechnologies.orient.server.plugin.OServerPluginManager.startPluginClass(OServerPluginManager.java:261)
        at com.orientechnologies.orient.server.plugin.OServerPluginManager.installDynamicPlugin(OServerPluginManager.java:350)
        at com.orientechnologies.orient.server.plugin.OServerPluginManager.updatePlugin(OServerPluginManager.java:202)
        at com.orientechnologies.orient.server.plugin.OServerPluginManager.updatePlugins(OServerPluginManager.java:290)
        at com.orientechnologies.orient.server.plugin.OServerPluginManager.startup(OServerPluginManager.java:93)
        at com.orientechnologies.orient.server.OServer.registerPlugins(OServer.java:1135)
        at com.orientechnologies.orient.server.OServer.activate(OServer.java:390)
        at com.orientechnologies.orient.server.OServerMain.main(OServerMain.java:41)
```

The jar file in `plugins` is readable by the orientdb user.
I also unzipped the jar to see if all is as it should be and the class files for `com.company.orientdb.MyPlugin` are there. The plugin.json is also there.

## Steps to reproduce the problem
I'm following the [plugin docs](http://orientdb.com/docs/2.2/Extend-Server.html) and it was working on 2.1.x.

Note that I have updated the maven dependencies (`orientdb-core` and `orientdb-server`).

I also don't have a `security.json` file. Maybe something changed here and the default is to not load plugin classes?

### Runninng Mode
- [x] Embedded, using PLOCAL access mode
- [ ] Embedded, using MEMORY access mode
- [ ] Remote

### Misc
- [x] I have a distributed setup with multiple servers. How many? 
  1
- [ ] I'm using the Enterprise Edition

### OrientDB Version
- [ ] v2.0.x - Please specify last number: 
- [ ] v2.1.x - Please specify last number: 
- [x] v2.2.x - Please specify last number: 

### Operating System
- [x] Linux
- [ ] MacOSX
- [ ] Windows
- [ ] Other Unix
- [ ] Other, name? 

### Java Version
- [ ] 6
- [ ] 7
- [x] 8

**Comment by mriehl** [comment]
As an update, I now have a `security.json` config so the warning is gone. The plugin still doesn't load though.

**Comment by mriehl** [comment]
I also installed the plugin `.jar` in the `lib` directory in orientdb home. This seems to resolve the issue.

**Comment by mriehl** [comment]
Closing because I was able to resolve the issue (deploy plugin to both `lib` and `plugins` in orientdb home).
