### ISSUE TITLE
Update/Remove fields which cannot be deserialised

### ISSUE THREAD

**Issue by antonzherdev** [orientechnologies/orientdb#6190]
## Expected behavior and actual behavior

When I try to update/remove a field which is not possible to deserialise, I'm getting an exception: 
```
java.lang.RuntimeException: com.orientechnologies.orient.core.exception.ODatabaseException: Error on deserialization of Serializable
	Storage URL="plocal:/var/erpdb/db"
	at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinaryV0.deserializeValue(ORecordSerializerBinaryV0.java:492)
	at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinaryV0.deserialize(ORecordSerializerBinaryV0.java:279)
	at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinary.fromStream(ORecordSerializerBinary.java:80)
	at com.orientechnologies.orient.core.record.impl.ODocument.deserializeFields(ODocument.java:1866)
	at com.orientechnologies.orient.core.record.impl.ODocument.checkForFields(ODocument.java:2544)
	at com.orientechnologies.orient.core.record.impl.ODocument.field(ODocument.java:1067)
	at com.orientechnologies.orient.core.record.impl.ODocument.field(ODocument.java:913)
	at com.erp.db.DslDataDb.com$erp$db$DslDataDb$$setFieldData(DslDataDb.scala:160)
```

I expect that it should be able to update/remove such a field otherwise there is no way how to do it. This data was there by mistake but there should be a way how to wipe out the data. 

## Steps to reproduce the problem

1. Create a class a store this class in a serialised way in a field;
2. Remove this class;
3. Try to access remove/modify the field.

### Runninng Mode
- [X] Embedded, using PLOCAL access mode
- [ ] Embedded, using MEMORY access mode
- [ ] Remote

### Misc
- [ ] I have a distributed setup with multiple servers. How many? 
- [ ] I'm using the Enterprise Edition

### OrientDB Version
- [ ] v2.0.x - Please specify last number: 
- [ ] v2.1.x - Please specify last number: 
- [X] v2.2.x - Please specify last number: 0

### Operating System
- [X] Linux
- [X] MacOSX
- [ ] Windows
- [ ] Other Unix
- [ ] Other, name? 

### Java Version
- [ ] 6
- [ ] 7
- [X] 8

**Comment by tglman** [comment]
HI @antonzherdev,

You should be able to remove the whole record as it is, so the suggestion is delete that record and create a new one.

By the way, what is the data that is there by mistake, is there any chance that we add some check to avoid this mistake ?

**Comment by tglman** [comment]
Another solution can be get out the field that you want to keep and clear the document.
ex:
```
ODocument doc = db.load(...);
Object keep = doc.field("fieldToKeep");
doc.clear();
doc.field("fieldToKeep",keep);
db.save(doc);
```

**Comment by antonzherdev** [comment]
@tglman Thanks for the solution however it's not working for me. I'm getting the same exception:
```
com.orientechnologies.orient.core.exception.ODatabaseException: Error on deserialization of Serializable
	Storage URL="plocal:/var/erpdb/db"
	at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinaryV0.deserializeValue(ORecordSerializerBinaryV0.java:492)
	at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinaryV0.deserialize(ORecordSerializerBinaryV0.java:279)
	at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinary.fromStream(ORecordSerializerBinary.java:80)
	at com.orientechnologies.orient.core.record.impl.ODocument.deserializeFields(ODocument.java:1866)
	at com.orientechnologies.orient.core.record.impl.ODocument.checkForFields(ODocument.java:2544)
	at com.orientechnologies.orient.core.record.impl.ODocument.setDirty(ODocument.java:1427)
	at com.orientechnologies.orient.core.record.ORecordAbstract.clear(ORecordAbstract.java:97)
	at com.orientechnologies.orient.core.record.impl.ODocument.clear(ODocument.java:1543)
	at com.erp.db.DslDataDb.fixDocument(DslDataDb.scala:93)
	at com.erp.db.DslDataDb.com$erp$db$DslDataDb$$fieldData(DslDataDb.scala:80)
	at com.erp.db.DslDataDb$$anonfun$fields$2.apply(DslDataDb.scala:62)
	at com.erp.db.DslDataDb$$anonfun$fields$2.apply(DslDataDb.scala:60)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
	at scala.collection.immutable.List.map(List.scala:285)
	at com.erp.db.DslDataDb.fields(DslDataDb.scala:60)
	at com.erp.net.NetData$.apply(NetData.scala:31)
	at com.erp.db.WorkspaceDbProcessor.toEntityData(WorkspaceDbProcessor.scala:438)
	at com.erp.db.WorkspaceDbProcessor.com$erp$db$WorkspaceDbProcessor$$toEntityResult(WorkspaceDbProcessor.scala:423)
	at com.erp.db.WorkspaceDbProcessor.load(WorkspaceDbProcessor.scala:26)
	at com.erp.db.WorkspaceDbActor.com$erp$db$WorkspaceDbActor$$processMessage(WorkspaceDbActor.scala:139)
	at com.erp.db.WorkspaceDbActor$$anonfun$active$1$$anonfun$applyOrElse$6.apply(WorkspaceDbActor.scala:119)
	at com.erp.db.WorkspaceDbActor$$anonfun$active$1$$anonfun$applyOrElse$6.apply(WorkspaceDbActor.scala:117)
	at com.erp.db.WorkspaceDbActor.com$erp$db$WorkspaceDbActor$$withDb(WorkspaceDbActor.scala:129)
	at com.erp.db.WorkspaceDbActor$$anonfun$active$1.applyOrElse(WorkspaceDbActor.scala:117)
	at akka.actor.Actor$class.aroundReceive(Actor.scala:482)
	at com.erp.db.WorkspaceDbActor.aroundReceive(WorkspaceDbActor.scala:21)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:526)
	at akka.actor.ActorCell.invoke(ActorCell.scala:495)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257)
	at akka.dispatch.Mailbox.run(Mailbox.scala:224)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:234)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
Caused by: com.orientechnologies.orient.core.exception.ODatabaseException: Error on deserialization of Serializable
	Storage URL="plocal:/var/erpdb/db"
	at com.orientechnologies.orient.core.serialization.serializer.record.binary.OSerializableWrapper.fromStream(OSerializableWrapper.java:48)
	at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinaryV0.deserializeValue(ORecordSerializerBinaryV0.java:486)
	... 37 common frames omitted
Caused by: java.io.InvalidClassException: com.orientechnologies.orient.core.record.ORecordAbstract; local class incompatible: stream classdesc serialVersionUID = 4214747833688988828, local class serialVersionUID = 1613275753098947568
	at java.io.ObjectStreamClass.initNonProxy(ObjectStreamClass.java:621)
	at java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:1623)
	at java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1518)
	at java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:1623)
	at java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1518)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1774)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1351)
	at java.io.ObjectInputStream.readArray(ObjectInputStream.java:1707)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1345)
	at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:1993)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1918)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1801)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1351)
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:371)
	at com.orientechnologies.orient.core.serialization.serializer.record.binary.OSerializableWrapper.fromStream(OSerializableWrapper.java:45)
	... 38 common frames omitted
```

I tried both clear and remove and I'm getting the same exception. The problem is that almost all methods are calling checkForFields and it triggers deserialisation for all fields. For example, setDirty method which is called by the clear method. And the delete method is calling setDirty as well.

I use Scala and I think I forgot to convert Seq[ODocument] into Java collection. So it was serialised.

It's correct when I'm getting the exception when I try to access this field however I think it should allow to modify data in this field. Otherwise there is no way how to fix the situation.

**Comment by tglman** [comment]
hi @antonzherdev so this will work:

```
ODocument doc = db.load(...);
Object keep = doc.field("fieldToKeep");
ODocument docNew = new ODocument(doc.getIdentity());
ORecordInternal.serVersion(docNew,doc.getVersion());
docNew.field("fieldToKeep",keep);
db.save(docNew);
```

another solution is to delete completely the record, in any case save information using the java serialization is not suggested for this kind of troubles.
i would say in this case would be better if you serliaze the value independetly and use fields of BINARY type.

Bye

**Comment by antonzherdev** [comment]
@tglman This solution is not working as well. It produces the same error when I try to save it: 
```
java.lang.RuntimeException: com.orientechnologies.orient.core.exception.ODatabaseException: Error on deserialization of Serializable
	Storage URL="plocal:/var/erpdb/db"
	at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinaryV0.deserializeValue(ORecordSerializerBinaryV0.java:492)
	at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinaryV0.deserialize(ORecordSerializerBinaryV0.java:279)
	at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinary.fromStream(ORecordSerializerBinary.java:80)
	at com.orientechnologies.orient.core.record.impl.ODocument.deserializeFields(ODocument.java:1866)
	at com.orientechnologies.orient.core.record.impl.ODocument.checkForFields(ODocument.java:2544)
	at com.orientechnologies.orient.core.record.impl.ODocument.validate(ODocument.java:2034)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.save(ODatabaseDocumentTx.java:2514)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.save(ODatabaseDocumentTx.java:2404)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.save(ODatabaseDocumentTx.java:99)
	at com.erp.db.DslDataDb.fixDocument(DslDataDb.scala:108)
```

If I try to delete the item I will have the same error. I can do nothing with this item now. This is the problem. 
It was not my intension to store serialised data but OrientDB does it automatically if the data type is not known. It's hard to notice because everything is working until the classes are not modified. This is not ideal but it's fine if there is a way how to clean this data. Because now I have a partially broken database and there is no way to recover.

**Comment by tglman** [comment]
hi @antonzherdev,

I wrote a test case, so i could be 100% sure that my suggestion where right, here it is:https://gist.github.com/tglman/e70de22120d9763cb7ed497dbd4a074d

so this work for sure, there is also a kind of 'emergency api' if you cannot remove the record anymore, but that's is the last option and it don't clean up indexes and staff like that, is  "ODatabaseDocument.hide(doc.getIdentity())" 
Hope this finally helps.

Regards.

**Comment by antonzherdev** [comment]
Hi @tglman 
I tried the solution and it's working for me.
The difference with your previous solution is that you are calling ORecordInternal.setIdentity instead of passing the identity as a constructor parameter. In this case it's working, with constructor parameter it's not.
Thanks!

**Comment by tglman** [comment]
Hi @antonzherdev,

Great that we got it done, can i close this now? we will take care to make this kind of errors easyer to recover from.

Bye

**Comment by antonzherdev** [comment]
@tglman Yes, sure. Thank!
