### ISSUE TITLE
Delete record produce 'Cannot execute non idempotent command'

### ISSUE THREAD

**Issue by christtrc** [orientechnologies/orientdb#6201]
## Expected behavior and actual behavior
```
db.command(new OSQLSynchQuery<>("DELETE FROM dictionary WHERE  type='type' and value='value'")).execute();
```
But:
If I run:
```
db.command(new OSQLSynchQuery<>("DELETE FROM dictionary WHERE  id='id'")).execute();
```
it worked !!

Ecpected behavior:
 return integer 

Actual behavior:
```
Caused by: com.orientechnologies.orient.core.exception.OCommandExecutionException: Cannot execute non idempotent command
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.executeCommand(OAbstractPaginatedStorage.java:1533)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.command(OAbstractPaginatedStorage.java:1528)
	at com.orientechnologies.orient.core.sql.query.OSQLQuery.run(OSQLQuery.java:72)
	at com.orientechnologies.orient.core.sql.query.OSQLSynchQuery.run(OSQLSynchQuery.java:85)
	at com.orientechnologies.orient.core.query.OQueryAbstract.execute(OQueryAbstract.java:33)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.command(ONetworkProtocolBinary.java:1323)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.executeRequest(ONetworkProtocolBinary.java:400)
	at com.orientechnologies.orient.server.network.protocol.binary.OBinaryNetworkProtocolAbstract.execute(OBinaryNetworkProtocolAbstract.java:223)
	at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:77)
```
## Steps to reproduce the problem

Use orientdb client to access remote orientdb server.

### Runninng Mode
- [ ] Embedded, using PLOCAL access mode
- [ ] Embedded, using MEMORY access mode
- [x] Remote

### Misc
- [ ] I have a distributed setup with multiple servers. How many? 
- [ ] I'm using the Enterprise Edition

### OrientDB Version
- [ ] v2.0.x - Please specify last number: 
- [ x ] v2.1.x - Please specify last number: 
- [ ] v2.2.x - Please specify last number: 

### Operating System
- [ ] Linux
- [ x ] MacOSX
- [ ] Windows
- [ ] Other Unix
- [ ] Other, name? 

### Java Version
- [ ] 6
- [ ] 7
- [ x ] 8

**Comment by luigidellaquila** [comment]
Hi @christtrc 

`OSQLSynchQuery` is intended only to execute idempotent commands (SELECT, TRAVERSE...), if you want to execute non idempotent commands like UPDATE and DELETE, you have to use OCommandSQL:

```
db.command(new OCommandSQL("DELETE FROM dictionary WHERE  id='id'")).execute();
```

Thanks

Luigi
