### ISSUE TITLE
JDBC: Support returning of @rid

### ISSUE THREAD

**Issue by lvca** [orientechnologies/orientdb#6205]
JDBC driver should be able to return the RID in query like this:

```
ResultSet rs = conn.createStatement().executeQuery("insert into Card content {"pan":"4444"} return @rid");
```

**Comment by schernolyas** [comment]
@lvca I got exception. See part of stack trace

Caused by: com.orientechnologies.orient.core.exception.OCommandExecutionException: Cannot execute non idempotent command
        Storage URL="memory:test"
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.executeCommand(OAbstractPaginatedStorage.java:2489)
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.command(OAbstractPaginatedStorage.java:2474)
        at com.orientechnologies.orient.core.sql.query.OSQLQuery.run(OSQLQuery.java:78)
        at com.orientechnologies.orient.core.sql.query.OSQLAsynchQuery.run(OSQLAsynchQuery.java:74)
        at com.orientechnologies.orient.core.sql.query.OSQLSynchQuery.run(OSQLSynchQuery.java:85)
        at com.orientechnologies.orient.core.query.OQueryAbstract.execute(OQueryAbstract.java:33)
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.query(ODatabaseDocumentTx.java:672)
        at com.orientechnologies.orient.jdbc.OrientJdbcPreparedStatement.executeQuery(OrientJdbcPreparedStatement.java:75)
