### ISSUE TITLE
LiveQuery do not work after an exceptional shutdown of  NodeJS

### ISSUE THREAD

**Issue by zhiguan-hanks** [orientechnologies/orientdb#6217]
OrientDB 2.1.6  OrientJS 2.2

My code is like the following.
-------------------------------------------------------------------------------------------------
var OrientDB = require('orientjs');
var server = OrientDB({host: 'localhost', port: 2424});
var db = server.use({name: 'test', username: 'admin', password: 'admin'});
db.liveQuery("live select from V")
    .on('live-insert', function(data){
          .......
    })
    .on('live-delete', function(data){
          .......
    })
    .on('live-update', function(data){
          .......
    })

........
LIVE UNSUBSCRIBE iToken (I get the iToken by changing OrientJS source code)
........
-------------------------------------------------------------------------------------------------

It works as I wish.

However, if  I kill the NodeJS process left the UNSUBSCRIBE command not executed,  the problem comes. None of the callbacks( .on('live-XXX', function(data){...} )  is called when data changed, while no exception thrown.

Until the OrientDB re-started, LiveQuery get normal.

**Comment by maggiolo00** [comment]
@zhiguan-hanks 

do you have this behaviour also with OrientDB 2.2?

**Comment by zhiguan-hanks** [comment]
Yes, my team members have tried with OrientDB 2.2(GA and RC) last night, and the problem remains.

**Comment by zhiguan-hanks** [comment]
We found the a **dead loop** in do ... while in function "OLiveCommandResultListener.onLiveResult()", when an unsubscribed LiveQuery exists. Here is the console output:

    in thread "Thread-10" java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
    at java.util.ArrayList.rangeCheck(ArrayList.java:653)
    at java.util.ArrayList.get(ArrayList.java:429)
    at java.util.Collections$SynchronizedList.get(Collections.java:2417)
    at com.orientechnologies.orient.server.network.protocol.binary.OLiveCommandResultListener.onLiveResult(OLiveCommandResultListener.java:111)
    at com.orientechnologies.orient.core.sql.OCommandExecutorSQLLiveSelect$2.call(OCommandExecutorSQLLiveSelect.java:132)
    at com.orientechnologies.orient.core.sql.OCommandExecutorSQLLiveSelect.execInSeparateDatabase(OCommandExecutorSQLLiveSelect.java:142)
    at com.orientechnologies.orient.core.sql.OCommandExecutorSQLLiveSelect.onLiveResult(OCommandExecutorSQLLiveSelect.java:129)
    at com.orientechnologies.orient.core.query.live.OLiveQueryQueueThread.run(OLiveQueryQueueThread.java:68)

**Comment by luigidellaquila** [comment]
Hi @zhiguan-hanks 

I'm fixing the problem in the core, then we will verify if there are also problems in OrientJS about the token

Thanks

Luigi

**Comment by luigidellaquila** [comment]
Hi @zhiguan-hanks 

I just pushed a fix for this in develop branch (next 2.2.1). 
@maggiolo00 let's do some tests together on NodeJS driver to make sure that everything is ok

Thanks

Luigi

**Comment by zhiguan-hanks** [comment]
My advice on fixing this bug in OrientDB core:
1. Automatically unsubscribe all LiveQuerys of the connection, Once disconnected.
2.Can you provide an interface event "**Disconnection**" to developers?

BTW, when will  2.2.1 be available?

Thanks

**Comment by luigidellaquila** [comment]
@tglman could you please take a look at this? (let's talk about it in private if you want)

Thanks

Luigi

**Comment by lvca** [comment]
@tglman  Is this closed?

**Comment by luigidellaquila** [comment]
@lvca we still have to finish the tests with Node.
@maggiolo00 when you have one minute...

Thanks

Luigi

**Comment by zhiguan-hanks** [comment]
Hi everyone, How is it going?

I'd like to know, whether you plan to provide an interface event "Disconnection" on which developers can create a function inside the database to listen? 
Only depending on your interface, we can realize our requirement. That is,

When one user shutdowns, the record( recording online/offline status of him) will be updated and then other users will be notified through LiveQuery.

Thanks a lot.

**Comment by maggiolo00** [comment]
Hi @zhiguan-hanks 

do you mean Disconnection on live query subscribed?

**Comment by zhiguan-hanks** [comment]
DISCONNECTION on live query subscribed AND database connection,
or at least one of them.

I think they are both  required for a maturer database server.

**Comment by zhiguan-hanks** [comment]
About when will  2.2.1 be released?
We will have to develop plugins for 2.2.0.

**Comment by maggiolo00** [comment]
@zhiguan-hanks 

here you can find 2.2.2

http://orientdb.com/download/

**Comment by zhiguan-hanks** [comment]
Hi,  friends,
The awful problem remains as following. Are you sure 2.2.2 enterprise is released correctly:-) ? !!

  `2016-06-15 19:33:23:835 INFO  {db=router} Indexes restore after crash was finished. [OIndexManagerShared]Exception in thread "Thread-16" java.lang.NullPointerException
        at com.orientechnologies.orient.core.query.live.OLiveQueryHook.unsubscribe(OLiveQueryHook.java:102)
        at com.orientechnologies.orient.server.network.protocol.binary.OLiveCommandResultListener.onLiveResult(OLiveCommandResultListener.java:155)
        at com.orientechnologies.orient.core.sql.OCommandExecutorSQLLiveSelect$2.call(OCommandExecutorSQLLiveSelect.java:131)
        at com.orientechnologies.orient.core.sql.OCommandExecutorSQLLiveSelect.execInSeparateDatabase(OCommandExecutorSQLLiveSelect.java:141)
        at com.orientechnologies.orient.core.sql.OCommandExecutorSQLLiveSelect.onLiveResult(OCommandExecutorSQLLiveSelect.java:128)
        at com.orientechnologies.orient.core.query.live.OLiveQueryQueueThread.run(OLiveQueryQueueThread.java:68)`

My use case is explained at the top floor. Thanks.

**Comment by maggiolo00** [comment]
@zhiguan-hanks 
let me check

**Comment by maggiolo00** [comment]
@zhiguan-hanks 
the fix was not complete. Fixed now.

It will be available in 2.2.3 GA

**Comment by maggiolo00** [comment]
@zhiguan-hanks 

can you retry with 2.2.3?
http://orientdb.com/download/

Thanks

**Comment by zhiguan-hanks** [comment]
We tried it over 5 times this morning, and the problem never reappeared. Everything seems going well!

Thanks a lot.

**Comment by maggiolo00** [comment]
Thanks
