### ISSUE TITLE
Token signature failure

### ISSUE THREAD

**Issue by vlasni** [orientechnologies/orientdb#6230]
## Unexpected failure reported in orientdb.err
The following is an extract of what is being logged when I issue `delete vertex vertexName` from Studio:

```
2016-05-30 14:00:37:877 WARNI Token signature failure: AAAAAAd2bGFzbmkyAP////////////8AAAFVArelxQEABHJvb3QAJAAXT1JlY29yZFNlcmlhbGl6ZXJCaW5hcnkADU9yaWVudERCIEphdmEABTIuMi4wc547MErxUlhd4M7AZjeSxQ+g5XwcGzucKqMwACfomig= [OTokenHandlerImpl]
2016-05-30 14:00:37:877 WARNI Token signature failure: AAAAAAd2bGFzbmkyAP////////////8AAAFVApxHqgEABHJvb3QAJAAXT1JlY29yZFNlcmlhbGl6ZXJCaW5hcnkADU9yaWVudERCIEphdmEABTIuMi4wT8q8+Sx8l6RsNnEPAzX4LzL/zRD4+XibTfrtS/a9/5U= [OTokenHandlerImpl]
2016-05-30 14:00:37:878 WARNI Token signature failure: AAAAAAd2bGFzbmkyAP////////////8AAAFVAqnwgwEABHJvb3QAJAAXT1JlY29yZFNlcmlhbGl6ZXJCaW5hcnkADU9yaWVudERCIEphdmEABTIuMi4wUC/j6H8KKGkmK6pCqyMpstz51mfMbYjapgSMje8MA9w= [OTokenHandlerImpl]
2016-05-30 14:00:37:879 WARNI Token signature failure: AAAAAAd2bGFzbmkyAP////////////8AAAFVAqnqKwEABHJvb3QAJAAXT1JlY29yZFNlcmlhbGl6ZXJCaW5hcnkADU9yaWVudERCIEphdmEABTIuMi4w4noDjBb6kgJkeCybA00F/iOWsMeVTwkv5b1qBwCR5iE= [OTokenHandlerImpl]Error executing request
com.orientechnologies.orient.enterprise.channel.binary.OTokenSecurityException: The token provided is not a valid token, signature does not match
	at com.orientechnologies.orient.server.OClientConnection.validateSession(OClientConnection.java:163)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.solveSession(ONetworkProtocolBinary.java:272)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.onBeforeRequest(ONetworkProtocolBinary.java:215)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.execute(ONetworkProtocolBinary.java:173)
	at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:77)
Error executing request
com.orientechnologies.orient.enterprise.channel.binary.OTokenSecurityException: The token provided is not a valid token, signature does not match
	at com.orientechnologies.orient.server.OClientConnection.validateSession(OClientConnection.java:163)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.solveSession(ONetworkProtocolBinary.java:272)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.onBeforeRequest(ONetworkProtocolBinary.java:215)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.execute(ONetworkProtocolBinary.java:173)
	at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:77)
Error executing request
com.orientechnologies.orient.enterprise.channel.binary.OTokenSecurityException: The token provided is not a valid token, signature does not match
	at com.orientechnologies.orient.server.OClientConnection.validateSession(OClientConnection.java:163)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.solveSession(ONetworkProtocolBinary.java:272)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.onBeforeRequest(ONetworkProtocolBinary.java:215)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.execute(ONetworkProtocolBinary.java:173)
	at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:77)
Error executing request
com.orientechnologies.orient.enterprise.channel.binary.OTokenSecurityException: The token provided is not a valid token, signature does not match
	at com.orientechnologies.orient.server.OClientConnection.validateSession(OClientConnection.java:163)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.solveSession(ONetworkProtocolBinary.java:272)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.onBeforeRequest(ONetworkProtocolBinary.java:215)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.execute(ONetworkProtocolBinary.java:173)
	at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:77)

2016-05-30 14:00:37:921 WARNI Token signature failure: AAAAAAd2bGFzbmkyAP////////////8AAAFVAqnwgwEABHJvb3QAJAAXT1JlY29yZFNlcmlhbGl6ZXJCaW5hcnkADU9yaWVudERCIEphdmEABTIuMi4wUC/j6H8KKGkmK6pCqyMpstz51mfMbYjapgSMje8MA9w= [OTokenHandlerImpl]
2016-05-30 14:00:37:923 WARNI Token signature failure: AAAAAAd2bGFzbmkyAP////////////8AAAFVArelxQEABHJvb3QAJAAXT1JlY29yZFNlcmlhbGl6ZXJCaW5hcnkADU9yaWVudERCIEphdmEABTIuMi4wc547MErxUlhd4M7AZjeSxQ+g5XwcGzucKqMwACfomig= [OTokenHandlerImpl]
2016-05-30 14:00:37:923 WARNI Token signature failure: AAAAAAd2bGFzbmkyAP////////////8AAAFVApxHqgEABHJvb3QAJAAXT1JlY29yZFNlcmlhbGl6ZXJCaW5hcnkADU9yaWVudERCIEphdmEABTIuMi4wT8q8+Sx8l6RsNnEPAzX4LzL/zRD4+XibTfrtS/a9/5U= [OTokenHandlerImpl]Error executing request
com.orientechnologies.orient.enterprise.channel.binary.OTokenSecurityException: The token provided is not a valid token, signature does not match
	at com.orientechnologies.orient.server.OClientConnection.validateSession(OClientConnection.java:163)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.solveSession(ONetworkProtocolBinary.java:274)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.onBeforeRequest(ONetworkProtocolBinary.java:215)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.execute(ONetworkProtocolBinary.java:173)
	at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:77)

2016-05-30 14:00:37:924 WARNI Token signature failure: AAAAAAd2bGFzbmkyAP////////////8AAAFVAqnqKwEABHJvb3QAJAAXT1JlY29yZFNlcmlhbGl6ZXJCaW5hcnkADU9yaWVudERCIEphdmEABTIuMi4w4noDjBb6kgJkeCybA00F/iOWsMeVTwkv5b1qBwCR5iE= [OTokenHandlerImpl]Error executing request
com.orientechnologies.orient.enterprise.channel.binary.OTokenSecurityException: The token provided is not a valid token, signature does not match
	at com.orientechnologies.orient.server.OClientConnection.validateSession(OClientConnection.java:163)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.solveSession(ONetworkProtocolBinary.java:274)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.onBeforeRequest(ONetworkProtocolBinary.java:215)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.execute(ONetworkProtocolBinary.java:173)
	at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:77)
Error executing request
com.orientechnologies.orient.enterprise.channel.binary.OTokenSecurityException: The token provided is not a valid token, signature does not match
	at com.orientechnologies.orient.server.OClientConnection.validateSession(OClientConnection.java:163)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.solveSession(ONetworkProtocolBinary.java:274)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.onBeforeRequest(ONetworkProtocolBinary.java:215)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.execute(ONetworkProtocolBinary.java:173)
	at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:77)
Error executing request
com.orientechnologies.orient.enterprise.channel.binary.OTokenSecurityException: The token provided is not a valid token, signature does not match
	at com.orientechnologies.orient.server.OClientConnection.validateSession(OClientConnection.java:163)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.solveSession(ONetworkProtocolBinary.java:274)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.onBeforeRequest(ONetworkProtocolBinary.java:215)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.execute(ONetworkProtocolBinary.java:173)
	at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:77)

```
The vertex I want to delete has 2,994,311 records.

### Runninng Mode
- [ ] Remote

### OrientDB Version
- [ ] v2.2.0

### Operating System
- [ ] Linux

### Java Version
- [ ] 8

**Comment by tglman** [comment]
@vlasni,

This log is not related to any operation in studio, because studio use http protocol and this is an stack trace of the binary protocol, this exception occour when a server is restarted, is just  the client trying to do an operation with an old session that is refused, the binary protocol client will renegotiate the session and no error will be exposed client side.

Closing this

**Comment by vlasni** [comment]
@tglman 
ok, I understand it's not related to Studio, my mistake.
What I am concerned about is that I keep seeing lots of entries in orientdb.err as:

```
2016-06-03 09:22:16:474 WARNI {db=vlasnitest} Token signature failure: AAAAAAp2bGFzbml0ZXN0AP////////////8AAAFVFkSCRgEABHJvb3QAJAAXT1JlY29yZFNlcmlhbGl6ZXJCaW5hcnkADU9yaWVudERCIEphdmEABTIuMi4wc4ZR/uxw0N/fzLeCErB+avaweF0G1griLFCDm5+8/zQ= [OTokenHandlerImpl]
2016-06-03 09:22:16:476 WARNI {db=vlasnitest} Token signature failure: AAAAAAp2bGFzbml0ZXN0AP////////////8AAAFVFhtPzAEABHJvb3QAJAAXT1JlY29yZFNlcmlhbGl6ZXJCaW5hcnkADU9yaWVudERCIEphdmEABTIuMi4w1uh9Qjx+hiB0CoqfmWnSMwLu4VhItsqV8yRQIxGtwF8= [OTokenHandlerImpl]
2016-06-03 09:22:16:484 WARNI {db=vlasnitest} Token signature failure: AAAAAAp2bGFzbml0ZXN0AP////////////8AAAFVFlI94gEABHJvb3QAJAAXT1JlY29yZFNlcmlhbGl6ZXJCaW5hcnkADU9yaWVudERCIEphdmEABTIuMi4wsvQ6hA7bl3alK+Zqgx9U0cUPYOvitVWXcxSbyxF1ksI= [OTokenHandlerImpl]
2016-06-03 09:22:16:485 WARNI Token signature failure: AAAAAAp2bGFzbml0ZXN0AP////////////8AAAFVFkSCewEABHJvb3QAJAAXT1JlY29yZFNlcmlhbGl6ZXJCaW5hcnkADU9yaWVudERCIEphdmEABTIuMi4wG+wX0j7L9ZgY99hyWbTjSf4mSgndiaBgjEc8zRux7iQ= [OTokenHandlerImpl]Error executing request
com.orientechnologies.orient.enterprise.channel.binary.OTokenSecurityException: The token provided is not a valid token, signature does not match
	Storage URL="plocal:/home/develance/orientdb/data/vlasnitest"
	at com.orientechnologies.orient.server.OClientConnection.validateSession(OClientConnection.java:163)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.solveSession(ONetworkProtocolBinary.java:272)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.onBeforeRequest(ONetworkProtocolBinary.java:215)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.execute(ONetworkProtocolBinary.java:173)
	at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:77)
Error executing request
com.orientechnologies.orient.enterprise.channel.binary.OTokenSecurityException: The token provided is not a valid token, signature does not match
	Storage URL="plocal:/home/develance/orientdb/data/vlasnitest"
	at com.orientechnologies.orient.server.OClientConnection.validateSession(OClientConnection.java:163)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.solveSession(ONetworkProtocolBinary.java:272)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.onBeforeRequest(ONetworkProtocolBinary.java:215)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.execute(ONetworkProtocolBinary.java:173)
	at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:77)

```
And it seems to me that there must be some defect perhaps on how I am handling connections?
Because I see them even when server has not been restarted (of course, I might be wrong).

**Comment by tglman** [comment]
hi @vlasni,

This warning does not create any harm, it just advise that one session has been considered invalid and the client should do an automatic reconnect, we had some problem on session management in case if the server is a distributed setup that were fixed in the last week, for the next week we are going to release 2.2.1 so please recheck with that.

Bye
