### ISSUE TITLE
IN filter parameter binding problem

### ISSUE THREAD

**Issue by balazsmaria** [orientechnologies/orientdb#6236]
hey,

I have to queries:

1.
`SELECT EXPAND(out()[age = :value]) FROM #11:0 ORDER BY age asc
`
This works as expected.

2.
`SELECT EXPAND(out()[age IN :values]) FROM #11:0 ORDER BY age asc
`
This throws an exception.

com.orientechnologies.orient.core.exception.OQueryParsingException: Error on parsing command at position #0: Error on parsing query
Query: age IN [31, 34
------^

	at com.orientechnologies.orient.core.sql.filter.OSQLPredicate.text(OSQLPredicate.java:103)
	at com.orientechnologies.orient.core.sql.filter.OSQLPredicate.<init>(OSQLPredicate.java:58)
	at com.orientechnologies.orient.core.record.impl.ODocumentHelper.getFieldValue(ODocumentHelper.java:470)
	at com.orientechnologies.orient.core.sql.functions.coll.OSQLMethodMultiValue.execute(OSQLMethodMultiValue.java:54)
	at com.orientechnologies.orient.core.sql.methods.OSQLMethodRuntime.execute(OSQLMethodRuntime.java:139)
	at com.orientechnologies.orient.core.sql.filter.OSQLFilterItemAbstract.transformValue(OSQLFilterItemAbstract.java:141)
	at com.orientechnologies.orient.core.sql.functions.OSQLFunctionRuntime.execute(OSQLFunctionRuntime.java:133)
	at com.orientechnologies.orient.core.sql.functions.OSQLFunctionRuntime.getValue(OSQLFunctionRuntime.java:147)
	at com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.applyExpand(OCommandExecutorSQLSelect.java:2255)
	at com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.execute(OCommandExecutorSQLSelect.java:447)
	at com.orientechnologies.orient.core.sql.OCommandExecutorSQLDelegate.execute(OCommandExecutorSQLDelegate.java:90)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.executeCommand(OAbstractPaginatedStorage.java:1433)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.command(OAbstractPaginatedStorage.java:1406)
	at com.orientechnologies.orient.core.sql.query.OSQLQuery.run(OSQLQuery.java:72)
	at com.orientechnologies.orient.core.sql.query.OSQLSynchQuery.run(OSQLSynchQuery.java:85)
	at com.orientechnologies.orient.core.query.OQueryAbstract.execute(OQueryAbstract.java:33)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.query(ODatabaseDocumentTx.java:717)

....

Caused by: java.lang.IllegalStateException: Missing closed braket character: ']', position: 14
	at com.orientechnologies.common.parser.OBaseParser.parserNextWord(OBaseParser.java:624)
	at com.orientechnologies.common.parser.OBaseParser.parserNextWord(OBaseParser.java:494)
	at com.orientechnologies.orient.core.sql.filter.OSQLPredicate.extractConditionItem(OSQLPredicate.java:264)
	at com.orientechnologies.orient.core.sql.filter.OSQLPredicate.extractCondition(OSQLPredicate.java:195)
	at com.orientechnologies.orient.core.sql.filter.OSQLPredicate.extractConditions(OSQLPredicate.java:139)
	at com.orientechnologies.orient.core.sql.filter.OSQLPredicate.text(OSQLPredicate.java:93)
	... 53 more

I'm using 2.1.17.

What could be the issue here?

**Comment by luigidellaquila** [comment]
Hi @balazsmaria 

it seems to be a bug, I'll take a look at that ASAP

Thanks

Luigi

**Comment by luigidellaquila** [comment]
Hi @balazsmaria 

I fixed it in develop and 2.1.x branches. The fix will be released with 2.1.20 and 2.2.1

Thanks

Luigi
