### ISSUE TITLE
Error retrieving record

### ISSUE THREAD

**Issue by kerner1000** [orientechnologies/orientdb#6255]
`Jun 03, 2016 5:49:50 PM com.orientechnologies.common.log.OLogManager log
SEVERE: {db=$home$alex$.openchrom$1.1.x$net.openchrom.chromatogram.xxd.identifier.supplier.chromident$test11} Error on fetching record during browsing. The record has been skipped
com.orientechnologies.orient.core.exception.ODatabaseException: Error on retrieving record #15:77 (cluster: chromident_reference_peak)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.executeReadRecord(ODatabaseDocumentTx.java:1855)
	at com.orientechnologies.orient.core.tx.OTransactionNoTx.loadRecord(OTransactionNoTx.java:96)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.load(ODatabaseDocumentTx.java:1596)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.load(ODatabaseDocumentTx.java:122)
	at com.orientechnologies.orient.core.iterator.OIdentifiableIterator.readCurrentRecord(OIdentifiableIterator.java:287)
	at com.orientechnologies.orient.core.iterator.ORecordIteratorClusters.hasNext(ORecordIteratorClusters.java:160)
	at net.openchrom.chromatogram.xxd.identifier.supplier.xident.database.controller.DatabasesOrientDB.deleteOrigin(DatabasesOrientDB.java:148)
	at net.openchrom.chromatogram.xxd.identifier.supplier.xident.ui.internal.runnables.DatabaseOriginDeleteRunnable.run(DatabaseOriginDeleteRunnable.java:35)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:119)
Caused by: com.orientechnologies.common.directmemory.ODirectMemoryViolationException: Last position of provided data interval [771883588] is more than size of allocated area [65552]
	at com.orientechnologies.common.directmemory.OUntrackedDirectMemoryPointer.rangeCheck(OUntrackedDirectMemoryPointer.java:240)
	at com.orientechnologies.common.directmemory.OUntrackedDirectMemoryPointer.get(OUntrackedDirectMemoryPointer.java:83)
	at com.orientechnologies.orient.core.storage.impl.local.paginated.base.ODurablePage.getBinaryValue(ODurablePage.java:113)
	at com.orientechnologies.orient.core.storage.impl.local.paginated.OClusterPage.getRecordBinaryValue(OClusterPage.java:395)
	at com.orientechnologies.orient.core.storage.impl.local.paginated.OPaginatedCluster.readFullEntry(OPaginatedCluster.java:1341)
	at com.orientechnologies.orient.core.storage.impl.local.paginated.OPaginatedCluster.readRecord(OPaginatedCluster.java:516)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.doReadRecord(OAbstractPaginatedStorage.java:2076)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.readRecord(OAbstractPaginatedStorage.java:1804)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.readRecord(OAbstractPaginatedStorage.java:782)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx$SimpleRecordReader.readRecord(ODatabaseDocumentTx.java:3092)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.executeReadRecord(ODatabaseDocumentTx.java:1820)
	... 8 more`

### Runninng Mode
- [x] Embedded, using PLOCAL access mode
- [ ] Embedded, using MEMORY access mode
- [ ] Remote

### Misc
- [ ] I have a distributed setup with multiple servers. How many? 
- [ ] I'm using the Enterprise Edition

### OrientDB Version
- [ ] v2.0.x - Please specify last number: 
- [x] v2.1.x - Please specify last number: 
- [ ] v2.2.x - Please specify last number: 

### Operating System
- [x] Linux
- [ ] MacOSX
- [ ] Windows
- [ ] Other Unix
- [ ] Other, name? 

### Java Version
- [ ] 6
- [ ] 7
- [x] 8

**Comment by krullert** [comment]
+1

**Comment by laa** [comment]
HIi @krullert, we have already discussed this issue in PrjHub issue which  you had may be caused by two facts:

1.  Many OOMs during tx commit (as I can get you , you often saw them before), we are working on new infrastructure to avoid OOM at all. 2.2.x version has much less memory consumpton during tx and I think next versons will rely on new infrastructure which will  prevent OOMs. But right now you should increase heap size to avoid OOM.
2. Database which you use was created on verion prior 2.1.14 in this version TX implementation had issue. But you noticed broken recrod much later.

So I suggest you to increase heap size and make import/export as we discussed.
