### ISSUE TITLE
java.net.SocketException: Too many open files

### ISSUE THREAD

**Issue by laa** [orientechnologies/orientdb#6269]
Hello

Log files have thousands of entries like this one:

java.net.SocketException: Too many open files
	at java.net.PlainSocketImpl.socketAccept(Native Method)
	at java.net.AbstractPlainSocketImpl.accept(AbstractPlainSocketImpl.java:409)
	at java.net.ServerSocket.implAccept(ServerSocket.java:545)
	at java.net.ServerSocket.accept(ServerSocket.java:513)
	at com.orientechnologies.orient.server.network.OServerNetworkListener.run(OServerNetworkListener.java:194)

I executed this command (while OrientDb was running):

sudo lsof | wc -l
129235

It seems orientDb open files and they never are closed. I saw for example a .pcl file opened 30 times.

Is it because we are doing something wrong from the client side or is it a bug? If it is a bug. Could you please suggest a workaround until it is fixed?

I was using Odb 2.1.15 before and I did not have this issue. But perhaps it did not happen to me before because I was not storing too much data. 

In my current DB Version I created 600+ clusters.

Any help will be appreciated.

**Comment by laa** [comment]
Fixed.
