### ISSUE TITLE
Error trying to  open database 

### ISSUE THREAD

**Issue by TomGroves** [orientechnologies/orientdb#6274]
## Expected behavior and actual behavior
`client.db_open( db_name, username, password )`
should open database, instead gives error:

`Traceback (most recent call last):
  File "FirstTest.py", line 18, in <module>
    client.db_open( db_name, username, password )
  File "/home/tom/MyProgs/TestingPyOrient/env/lib/python3.5/site-packages/pyorient/orient.py", line 379, in db_open
    .prepare((db_name, user, password, db_type, client_id)).send().fetch_response()
  File "/home/tom/MyProgs/TestingPyOrient/env/lib/python3.5/site-packages/pyorient/messages/database.py", line 141, in fetch_response
    info = OrientVersion(release)
  File "/home/tom/MyProgs/TestingPyOrient/env/lib/python3.5/site-packages/pyorient/otypes.py", line 202, in __init__
    self._parse_version(release)
  File "/home/tom/MyProgs/TestingPyOrient/env/lib/python3.5/site-packages/pyorient/otypes.py", line 235, in _parse_version
    self.build = int( self.build )
ValueError: invalid literal for int() with base 10: '0 (build develop@r79d281140b01c0bc3b566a46a64f1573cb359783; 2016'
`

## Steps to reproduce the problem
Install OrientDB (Community 2.2.0) (on Ubuntu Server 16.04), Python (3.5.1+), and pyorient (1.5.2)
Run the follow code (obviously with corrent user/password):
```python
import pyorient

username="user"
password="password"

client = pyorient.OrientDB("localhost", 2424)
session_id = client.connect( username, password )

print("SessionID=",session_id)

db_name="GratefulDeadConcerts"

if client.db_exists( db_name, pyorient.STORAGE_TYPE_MEMORY ):
    print("Database",db_name,"exists")
    client.db_open( db_name, username, password )
else:
    print("Database",db_name,"doesn't exist")
```

### Runninng Mode
- [ ] Embedded, using PLOCAL access mode
- [ ] Embedded, using MEMORY access mode
- [X ] Remote

### Misc
- [ ] I have a distributed setup with multiple servers. How many? 
- [ ] I'm using the Enterprise Edition

### OrientDB Version
- [ ] v2.0.x - Please specify last number: 
- [ ] v2.1.x - Please specify last number: 
- [X ] v2.2.x - Please specify last number: 0

### Operating System
- [X ] Linux
- [ ] MacOSX
- [ ] Windows
- [ ] Other Unix
- [ ] Other, name? 

### Java Version
- [ ] 6
- [ ] 7
- [X ] 8

**Comment by paulozullu** [comment]
I have the same problem here

**Comment by maggiolo00** [comment]
@paulozullu 

do you have a script to reproduce the problem?

Thanks
Enrico

**Comment by paulozullu** [comment]
Hi, @maggiolo00 

I just followed the official instructions 

Paulo

**Comment by maggiolo00** [comment]
@paulozullu 
@TomGroves 

see here. Seems to be a known issue with the driver.

https://github.com/orientechnologies/pyorient/issues/17

**Comment by paulozullu** [comment]
Ok, thanks @maggiolo00

**Comment by Spydernaz** [comment]
Hi,

Also getting this issue. Orientdb 2.2.2, Windows 7 & pyorient 1.5.2

This is my script
`import pyorient

#Created all varables

print("connecting to database")

#create connection 
client = pyorient.OrientDB("localhost", 2424) 
session_id = client.connect( "root", "password" )

print("connected to client")
#open databse 
client.db_open( "systems", "root", "password" )

print("connected to database")`


This is the error:
`Traceback (most recent call last):
  File "C:\Users\valana\Desktop\orientdb-community-2.1.17\PythonScripts\Wipe.py"
, line 13, in <module>
    client.db_open( "systems", "root", "password" )
  File "C:\Users\valana\AppData\Local\Programs\Python\Python35-32\lib\site-packages\pyorient\orient.py", line 379, in db_open
    .prepare((db_name, user, password, db_type, client_id)).send().fetch_response()
  File "C:\Users\valana\AppData\Local\Programs\Python\Python35-32\lib\site-packages\pyorient\messages\database.py", line 141, in fetch_response
    info = OrientVersion(release)
  File "C:\Users\valana\AppData\Local\Programs\Python\Python35-32\lib\site-packages\pyorient\otypes.py", line 202, in __init__
    self._parse_version(release)
  File "C:\Users\valana\AppData\Local\Programs\Python\Python35-32\lib\site-packages\pyorient\otypes.py", line 235, in _parse_version
    self.build = int( self.build )
ValueError: invalid literal for int() with base 10: '2 (build develop@re6e0017eee1660146bbb27715832b82a268a438a; 2016'`

**Comment by tglman** [comment]
the relative issue on pyorient has
