### ISSUE TITLE
JAVA ERROR even if using the current version java 8 update 91

### ISSUE THREAD

**Issue by sanjay1k** [orientechnologies/orientdb#6291]
## Expected behavior and actual behavior
Expected - root password should set and orientDB should run after installation
Actual - Getting following JAVA error during installation on MAC Book air running on OS X EI Capitan,

+---------------------------------------------------------------+
|                WARNING: FIRST RUN CONFIGURATION               |
+---------------------------------------------------------------+
| This is the first time the server is running. Please type a   |
| password of your choice for the 'root' user or leave it blank |
| to auto-generate it.                                          |
|                                                               |
| To avoid this message set the environment variable or JVM     |
| setting ORIENTDB_ROOT_PASSWORD to the root password to use.   |
+---------------------------------------------------------------+

Root password [BLANK=auto generate it]: *****
Please confirm the root password: *****^R
ro**
Exception in thread "main" com.orientechnologies.orient.core.exception.OSecurityException: Cannot create a key with 'PBKDF2WithHmacSHA256' algorithm
	at com.orientechnologies.orient.core.security.OSecurityManager.getPbkdf2(OSecurityManager.java:246)
	at com.orientechnologies.orient.core.security.OSecurityManager.createHashWithSalt(OSecurityManager.java:189)
	at com.orientechnologies.orient.core.security.OSecurityManager.createHash(OSecurityManager.java:154)
	at com.orientechnologies.orient.server.OServer.addUser(OServer.java:840)
	at com.orientechnologies.orient.server.OServer.createDefaultServerUsers(OServer.java:1121)
	at com.orientechnologies.orient.server.OServer.loadUsers(OServer.java:990)
	at com.orientechnologies.orient.server.OServer.activate(OServer.java:379)
	at com.orientechnologies.orient.server.OServerMain.main(OServerMain.java:41)
Caused by: java.security.NoSuchAlgorithmException: PBKDF2WithHmacSHA256 SecretKeyFactory not available
	at javax.crypto.SecretKeyFactory.<init>(DashoA13*..)
	at javax.crypto.SecretKeyFactory.getInstance(DashoA13*..)
	at com.orientechnologies.orient.core.security.OSecurityManager.getPbkdf2(OSecurityManager.java:236)
	... 7 more

## Steps to reproduce the problem
1. download the orientdb-community-2.2.0.tar.gz file
2. unzip it and run bin/server.sh from terminal
3. Set root password, again confirm root password
4 hit enter - you will see the above issue.

## Important Questions
Please let me know the steps to fix the issue or fix the orientDB package itself if issue is there. I want to run it on machine ASAP.

### Runninng Mode
MAC terminal

### Misc
NA

### OrientDB Version
community-2.2.0

### Operating System
MacOSX

### Java Version
 8

**Comment by sanjay1k** [comment]
I have seen a similar issue and as a workaround it has been recomended to update the JAVA version of the machine. I did that and updated my java version to latest one ( java 8 update 91). But issue is still as it was. Please find the link for your reference - https://github.com/orientechnologies/orientdb/issues/5769.

**Comment by maggiolo00** [comment]
hi @sanjay1k 
you did update Java after the first startup?

**Comment by sanjay1k** [comment]
Yes, I updated it.

**Comment by sanjay1k** [comment]
Have you found the problem? please help.

**Comment by luigidellaquila** [comment]
Hi @sanjay1k 

This error typically happens when OrientDB runs on Java <= 7.
Could you please add this
```
echo `java -version`
```
in the server.sh and see which Java version appears in the logs?

Thanks

Luigi

**Comment by ttiltonheylin** [comment]
Thomas$ /Users/Thomas/Downloads/orientdb-community-2.2.2/bin/server.sh ; exit;
java version "1.6.0_65"
Java(TM) SE Runtime Environment (build 1.6.0_65-b14-468-11M4833)
Java HotSpot(TM) 64-Bit Server VM (build 20.65-b04-468, mixed mode)

           .                                          
          .`        `                                 
          ,      `:.                                  
         `,`    ,:`                                   
         .,.   :,,                                    
         .,,  ,,,                                     
    .    .,.:::::  ````                                 :::::::::     :::::::::   
    ,`   .::,,,,::.,,,,,,`;;                      .:    ::::::::::    :::    :::  
    `,.  ::,,,,,,,:.,,.`  `                       .:    :::      :::  :::     ::: 
     ,,:,:,,,,,,,,::.   `        `         ``     .:    :::      :::  :::     ::: 
      ,,:.,,,,,,,,,: `::, ,,   ::,::`   : :,::`  ::::   :::      :::  :::    :::  
       ,:,,,,,,,,,,::,:   ,,  :.    :   ::    :   .:    :::      :::  :::::::     
        :,,,,,,,,,,:,::   ,,  :      :  :     :   .:    :::      :::  :::::::::   
  `     :,,,,,,,,,,:,::,  ,, .::::::::  :     :   .:    :::      :::  :::     ::: 
  `,...,,:,,,,,,,,,: .:,. ,, ,,         :     :   .:    :::      :::  :::     ::: 
    .,,,,::,,,,,,,:  `: , ,,  :     `   :     :   .:    :::      :::  :::     ::: 
      ...,::,,,,::.. `:  .,,  :,    :   :     :   .:    :::::::::::   :::     ::: 
           ,::::,,,. `:   ,,   :::::    :     :   .:    :::::::::     ::::::::::  
           ,,:` `,,.                                  
          ,,,    .,`                                  
         ,,.     `,                                          GRAPH DATABASE  
       ``        `.                                                          
                 ``                                          orientdb.com
                 `                                    
removing old pid file /Users/Thomas/Downloads/orientdb-community-2.2.2/bin/orient.pid

2016-06-15 22:59:42:667 INFO  Loading configuration from: /Users/Thomas/Downloads/orientdb-community-2.2.2/config/orientdb-server-config.xml... [OServerConfigurationLoaderXml]
2016-06-15 22:59:42:975 INFO  OrientDB Server v2.2.2 (build develop@re6e0017eee1660146bbb27715832b82a268a438a; 2016-06-13 15:26:13+0000) is starting up... [OServer]
2016-06-15 22:59:42:981 INFO  Databases directory: /Users/Thomas/Downloads/orientdb-community-2.2.2/databases [OServer]
2016-06-15 22:59:43:034 INFO  OrientDB auto-config DISKCACHE=13,845MB (heap=490MB direct=524,288MB os=16,384MB) [orientechnologies]
2016-06-15 22:59:43:327 WARNI Port 0.0.0.0:2424 busy, trying the next available... [OServerNetworkListener]
2016-06-15 22:59:43:328 INFO  Listening binary connections on 0.0.0.0:2425 (protocol v.36, socket=default) [OServerNetworkListener]
2016-06-15 22:59:43:332 WARNI Port 0.0.0.0:2480 busy, trying the next available... [OServerNetworkListener]
2016-06-15 22:59:43:332 INFO  Listening http connections on 0.0.0.0:2481 (protocol v.10, socket=default) [OServerNetworkListener]

+---------------------------------------------------------------+
|                WARNING: FIRST RUN CONFIGURATION               |
+---------------------------------------------------------------+
| This is the first time the server is running. Please type a   |
| password of your choice for the 'root' user or leave it blank |
| to auto-generate it.                                          |
|                                                               |
| To avoid this message set the environment variable or JVM     |
| setting ORIENTDB_ROOT_PASSWORD to the root password to use.   |
+---------------------------------------------------------------+

Root password [BLANK=auto generate it]: *****
Please confirm the root password: *****
Exception in thread "main" com.orientechnologies.orient.core.exception.OSecurityException: Cannot create a key with 'PBKDF2WithHmacSHA256' algorithm
	at com.orientechnologies.orient.core.security.OSecurityManager.getPbkdf2(OSecurityManager.java:246)
	at com.orientechnologies.orient.core.security.OSecurityManager.createHashWithSalt(OSecurityManager.java:189)
	at com.orientechnologies.orient.core.security.OSecurityManager.createHash(OSecurityManager.java:154)
	at com.orientechnologies.orient.server.OServer.addUser(OServer.java:839)
	at com.orientechnologies.orient.server.OServer.createDefaultServerUsers(OServer.java:1126)
	at com.orientechnologies.orient.server.OServer.loadUsers(OServer.java:990)
	at com.orientechnologies.orient.server.OServer.activate(OServer.java:380)
	at com.orientechnologies.orient.server.OServerMain.main(OServerMain.java:41)
Caused by: java.security.NoSuchAlgorithmException: PBKDF2WithHmacSHA256 SecretKeyFactory not available
	at javax.crypto.SecretKeyFactory.<init>(DashoA13*..)
	at javax.crypto.SecretKeyFactory.getInstance(DashoA13*..)
	at com.orientechnologies.orient.core.security.OSecurityManager.getPbkdf2(OSecurityManager.java:236)
	... 7 more

`

**Comment by sanjay1k** [comment]
Hi @luigidellaquila : It prints following in the terminal,

java version "1.6.0_65"
Java(TM) SE Runtime Environment (build 1.6.0_65-b14-468-11M4833)
Java HotSpot(TM) 64-Bit Server VM (build 20.65-b04-468, mixed mode)

Thanks

**Comment by maggiolo00** [comment]
hi @sanjay1k 
@ttiltonheylin 

you seem to have java 1.6

**Comment by sanjay1k** [comment]
thanks @maggiolo00 : I got it :) it seems terminal is still using java 6. May be some environment setting is missing. Let me check. Thanks for your help 👍

**Comment by maggiolo00** [comment]
@ttiltonheylin 
check your java version.

If you want to use java 1.6/7
you should start the server with
```
-Dsecurity.userPasswordDefaultAlgorithm=PBKDF2WithHmacSHA1
```

**Comment by maggiolo00** [comment]
Added in 2.2.0 Release doc.
https://github.com/orientechnologies/orientdb-docs/blob/master/Release-2.2.0.md#salt
Should be online in couple of hours in the official documentation
