### ISSUE TITLE
2.2.0 OIndexException When Initializing new plocal DB (Including OSystem)

### ISSUE THREAD

**Issue by kazelin** [orientechnologies/orientdb#6297]
## Expected behavior and actual behavior
I am trying to start a plocal db running in a jvm. This seems to initialize without issue on Linux, but having issues initializing. I am running OrienDB 2.2.0 GA. I don't have the stack trace as I don't have network, but I will try my best to put the information here.

The issue occurs when OrientDB tries to initialize both 'OSystem' and my own plocal DB. What I am seeing is:

com.orientechnologies.orient.core.db.document.ODataBaseDocumentTx.create(OdatabaseDocumentTx.java:429)......
.....
com.orientechnologies.orient.core.index.OIndexException: Index with type DICTIONARY and algorithm SBTREE does not exist.
at com.orientechnologies.orient.core.index.OIndexes.getFactory(OIndexes.java:130)

I have included all dependencies (jars) included with the GA community build. **So this occurs when orientdb tries to even start creating its own OSystem database.**

Windows 7 x64 / CentOS 6
Java 8u92 32bit
MaxDirectMemorySize set to 800m (anything below or above 1023m this will cause OOM)

### Running Mode
- [x] Embedded, using PLOCAL access mode
- [ ] Embedded, using MEMORY access mode
- [ ] Remote

### Misc
- [ ] I have a distributed setup with multiple servers. How many? 
- [ ] I'm using the Enterprise Edition

### OrientDB Version
- [ ] v2.0.x - Please specify last number: 
- [ ] v2.1.x - Please specify last number: 
- [x] v2.2.0 - Please specify last number: 

### Operating System
- [ ] Linux
- [ ] MacOSX
- [x] Windows
- [ ] Other Unix
- [ ] Other, name? 

### Java Version
- [ ] 6
- [ ] 7
- [x] 8

**Comment by kazelin** [comment]
Apologies, I have adjusted the title/text to adjust for a test I did on Linux. This issue occurs on Linux as well. The testing that was successful was occurring on debugging through eclipse.

**Comment by tglman** [comment]
@kazelin,

Are you embedding the orientdb server ? can you post here the orientdb related code that you use to start your environment

**Comment by tglman** [comment]
hi @kazelin can you try to change your code like this:
```
final OServer orientServer
try
{
      Orient.instance().startup();
      orientServer = OServermain.create();
      try (final InputStream configStream = Server.class.getResourceAsStream("resources/orientdb-server-config.xml"))
      {
           if(configStream == null)
           {
                    throw new exception;
           }
           orientServer.startup();
           orientServer.activate();
      }
}
catch(final exception ex)
{
     throw new exception;
}
```
this should workaroud for your problem

**Comment by kazelin** [comment]
@tglman thank you for the suggestion. The code got past the OIndexException from before, but there is a new error. Excuse me while I type this out:

orient.core.exception.ODatabaseException: Cannot create databsae 'OSystem'
at orient.core.db.document.ODatabaseDocumentTx.create(ODatabaseDocumentTx.java:429)
at orient.server.OSystemDatabase.init(OSystemDatabase.java:106)
at orient.server.OSystemDatabase.<init>(OSystemDatabase.java:42)
at orient.server.OServer.initSystemDatabase(OServer.java:1217)
at orient.server.OServer.activate(OServer.java:343)

Cuased by: orient.core.command.OCommandExecutorNotFoundException: Cannot find a command executor for the command request: sql.select from oRole where name = ? limit 1
at orient.core.sql.oCommandExecutorSQLDelegate.parse(OCommandExecutorSQLDelegate.java:54)
at orient.core.sql.oCommandExecutorSQLDelegate.parse(OCommandExecutorSQLDelegate.java:39)
at orient.core.storage.impl.local.OAbstractPaginatedStorage.command(OAbstractPaginatedStorage.java:2472)
at orient.core.sql.query.OSQLQuery.run(OSQLQuery.java:78)
at orient.core.sql.query.OSQLAsynchQuery.run(OSQLAsynchQuery.java:85)
at orient.core.sql.query.OSQLSynchQuery.run(OSQLSynchQuery.java:33)
at orient.core.metadata.security.OSecurityShared.getRole(OSecurityShared.java:334)
at orient.core.metadata.security.OSecurityShared.createMetadata(OSecurityShared.java:446)
at orient.core.metadata.security.OSecurityShared.create(OSecurityShared.java:383)
at orient.core.metadata.security.OSecurityProxy.create(OSecurityProxy.java:94)
at orient.core.metadata.OMetadataDefault.create(OMetadataDefault.java:102)
at orient.core.db.document.OdatabaseDocumentTx.create(ODatabaseDocumentTx.java:403)

I tried this with 2.2.0 GA and 2.2.2 GA as well with the same result. I assume that the enterprise edition will have no affect on the problem?

**Comment by maggiolo00** [comment]
hi @kazelin 

how did you create the package of your App that embed OrientDB?

**Comment by kazelin** [comment]
This one can be closed as the server can get past creation of the database.

We were running into the issue noted here I believe: https://github.com/orientechnologies/orientdb/issues/6284

Currently having OOM errors on unsafe and direct memory with 32bit jvm on 64bit machines. I will open another one for that if needed.

Thanks guys!
