### ISSUE TITLE
REMOTE engine not found if the code is packaged as jar

### ISSUE THREAD

**Issue by reneses** [orientechnologies/orientdb#6299]
## Expected behavior and actual behavior

It is not possible to connect to a remote database if the application is packaged as a (shaded) jar, while I can perfectly do it running it from my IDE (IntelliJ).

I created a sample project to show it. After executing `mvn package`, and then `java -jar target/test-0.1.jar` the stacktrace is:

```
MacBook-Air:orientdb-bug Reneses$ java -jar target/test-0.1.jar 
Jun 14, 2016 1:33:10 AM com.orientechnologies.common.log.OLogManager log
INFO: OrientDB auto-config DISKCACHE=1,820MB (heap=1,820MB direct=1,820MB os=8,192MB), assuming maximum direct memory size equals to maximum JVM heap size
Jun 14, 2016 1:33:10 AM com.orientechnologies.common.log.OLogManager log
WARNING: MaxDirectMemorySize JVM option is not set or has invalid value, that may cause out of memory errors. Please set the -XX:MaxDirectMemorySize=8192m option when you start the JVM.
Jun 14, 2016 1:33:10 AM com.orientechnologies.common.log.OLogManager log
WARNING: MaxDirectMemorySize JVM option is not set or has invalid value, that may cause out of memory errors. Please set the -XX:MaxDirectMemorySize=8192m option when you start the JVM.
Exception in thread "main" com.orientechnologies.orient.core.exception.ODatabaseException: Error on opening database 'REMOTE:localhost/test'
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.<init>(ODatabaseDocumentTx.java:184)
        at com.orientechnologies.orient.core.db.OPartitionedDatabasePool$DatabaseDocumentTxPolled.<init>(OPartitionedDatabasePool.java:118)
        at com.orientechnologies.orient.core.db.OPartitionedDatabasePool$DatabaseDocumentTxPolled.<init>(OPartitionedDatabasePool.java:114)
        at com.orientechnologies.orient.core.db.OPartitionedDatabasePool.initQueue(OPartitionedDatabasePool.java:438)
        at com.orientechnologies.orient.core.db.OPartitionedDatabasePool.<init>(OPartitionedDatabasePool.java:213)
        at com.tinkerpop.blueprints.impls.orient.OrientGraphFactory.<init>(OrientGraphFactory.java:78)
        at orientdb.test.App.main(App.java:9)
Caused by: com.orientechnologies.orient.core.exception.OConfigurationException: Error on opening database: the engine 'REMOTE' was not found. URL was: REMOTE:localhost/test. Registered engines are: [memory, plocal]
        Storage URL="REMOTE:localhost/test"
        at com.orientechnologies.orient.core.Orient.loadStorage(Orient.java:478)
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.<init>(ODatabaseDocumentTx.java:164)
        ... 6 more
```

I have checked if the shade plugin was skipping the dependency, but does not seem to be the case.

## Steps to reproduce the problem

I have attached the project, including the resulting jar:
[orientdb-bug.zip](https://github.com/orientechnologies/orientdb/files/312915/orientdb-bug.zip)

Main class:

```java
package orientdb.test;
import com.tinkerpop.blueprints.impls.orient.OrientGraphFactory;
public class App {
  public static void main(String[] args) throws Exception {
    OrientGraphFactory factory = new OrientGraphFactory("REMOTE:localhost/test", "root", "root", true);
    factory.getNoTx();
  }
}
```

Pom file:
```xml
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <groupId>orientdb</groupId>
    <artifactId>test</artifactId>
    <version>0.1</version>
    <modelVersion>4.0.0</modelVersion>
    <packaging>jar</packaging>
    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <java.version>1.8</java.version>
    </properties>
    <dependencies>
        <dependency>
            <groupId>com.orientechnologies</groupId>
            <artifactId>orientdb-core</artifactId>
            <version>2.2.0</version>
        </dependency>
        <dependency>
            <groupId>com.orientechnologies</groupId>
            <artifactId>orientdb-graphdb</artifactId>
            <version>2.2.0</version>
        </dependency>
        <dependency>
            <groupId>com.orientechnologies</groupId>
            <artifactId>orientdb-client</artifactId>
            <version>2.2.0</version>
        </dependency>
        <dependency>
            <groupId>com.tinkerpop.blueprints</groupId>
            <artifactId>blueprints-core</artifactId>
            <version>2.6.0</version>
        </dependency>
        <dependency>
            <groupId>net.java.dev.jna</groupId>
            <artifactId>jna</artifactId>
            <version>4.2.1</version>
        </dependency>
        <dependency>
            <groupId>net.java.dev.jna</groupId>
            <artifactId>jna-platform</artifactId>
            <version>4.2.1</version>
        </dependency>
        <dependency>
            <groupId>com.googlecode.concurrentlinkedhashmap</groupId>
            <artifactId>concurrentlinkedhashmap-lru</artifactId>
            <version>1.4.2</version>
        </dependency>
    </dependencies>
    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-jar-plugin</artifactId>
                <version>3.0.0</version>
                <configuration>
                    <archive>
                        <manifest>
                            <mainClass>orientdb.test.App</mainClass>
                        </manifest>
                    </archive>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-shade-plugin</artifactId>
                <version>2.4.3</version>
                <configuration>
                    <minimizeJar>false</minimizeJar>
                    <filters>
                        <filter>
                            <artifact>com.orientechnologies:*</artifact>
                            <includes>
                                <include>**</include>
                            </includes>
                        </filter>
                    </filters>
                    <createDependencyReducedPom>false</createDependencyReducedPom>
                    <transformers>
                        <transformer                         implementation="org.apache.maven.plugins.shade.resource.ManifestResourceTransformer">
                            <mainClass>orientdb.test.App</mainClass>
                        </transformer>
                    </transformers>
                </configuration>
                <executions>
                    <execution>
                        <phase>package</phase>
                        <goals>
                            <goal>shade</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>2.3.2</version>
                <configuration>
                    <source>1.8</source>
                    <target>1.8</target>
                </configuration>
            </plugin>
        </plugins>
    </build>
</project>
```

### Runninng Mode
- [ ] Embedded, using PLOCAL access mode
- [ ] Embedded, using MEMORY access mode
- [X] Remote

### Misc
- [ ] I have a distributed setup with multiple servers. How many? 
- [ ] I'm using the Enterprise Edition

### OrientDB Version
- [ ] v2.0.x - Please specify last number: 
- [ ] v2.1.x - Please specify last number: 
- [X] v2.2.x - Please specify last number: 0

### Operating System
- [ ] Linux
- [X] MacOSX
- [ ] Windows
- [ ] Other Unix
- [ ] Other, name? 

### Java Version
- [ ] 6
- [ ] 7
- [X] 8

**Comment by maggiolo00** [comment]
hi @reneses 

OrientDB uses Java services (META-INF/services) for creating components like Engines. You should add this in your pom.xml in transformers sections in order to append services in case of collision when creating a single shaded jar.
```
<transformer implementation="org.apache.maven.plugins.shade.resource.ServicesResourceTransformer"/>
```

I will mark this issue as documentation, i will add a section on how to build a shaded jar with OrientDB

**Comment by reneses** [comment]
Thanks, it works like a charm now!

**Comment by maggiolo00** [comment]
Docs updated
https://github.com/orientechnologies/orientdb-docs/blob/master/Tutorial-Installation.md#building-a-single-executable-jar-with-orientdb

It should be online in a couple of hours
