### ISSUE TITLE
NullPointerException when invoking OClass::truncate

### ISSUE THREAD

**Issue by diegomtassis** [orientechnologies/orientdb#6312]
This is related to [this issue](https://github.com/orientechnologies/orientdb/issues/6303).

So I have an application which uses intensively OrientDB and I have a lot of integration tests.

When using OrientDB 2.1.5 al the tests pass.
After moving to OrientDB 2.2.2 some tests fail.

In this particular case this test passes in eclipse as well as when run via maven in my windows machine. It also passes when it's run by jenkins in a linux machine for a certain job, but fails when run by another different job.

The stack trace:

```
Stacktrace

com.orientechnologies.orient.core.index.OIndexException: 
Error on rebuilding the index for clusters: [aenclosure_14, adocument_10, aenclosure_13, adocument_11, aenclosure_16, aenclosure_15, aenclosure_18, adocument_14, aenclosure_17, adocument_15, adocument_12, aenclosure_19, adocument_13, adocument_18, adocument_19, aenclosure, adocument_16, adocument_17, aenclosure_10, aenclosure_12, aenclosure_11, adocument_7, adocument_21, aenclosure_3, adocument_8, adocument_22, aenclosure_2, adocument_9, aenclosure_5, adocument_20, aenclosure_4, adocument_3, adocument_4, adocument_5, adocument_23, aenclosure_1, adocument_6, aenclosure_7, aenclosure_6, aenclosure_9, aenclosure_8, adocument, adocument_1, adocument_2, aenclosure_21, aenclosure_20, aenclosure_23, aenclosure_22]
	DB name="dclosure_integration"
	at com.compart.tec.destiny.core.db.browse.FlattenedBrowseUsingBlueprintsIT.<init>(FlattenedBrowseUsingBlueprintsIT.java:42)
Caused by: com.orientechnologies.orient.core.exception.OStorageException: 
File File: ADocument.bundleid.irs, stored=0 does not exist.
	DB name="dclosure_integration"
	at com.compart.tec.destiny.core.db.browse.FlattenedBrowseUsingBlueprintsIT.<init>(FlattenedBrowseUsingBlueprintsIT.java:42)

Standard Error

Jun 16, 2016 12:47:28 PM com.orientechnologies.common.log.OLogManager log
SEVERE: $ANSI{green {db=dclosure_integration}} Error during index 'ADocument.bundleid' delete
Jun 16, 2016 12:47:28 PM com.orientechnologies.common.log.OLogManager log
SEVERE: $ANSI{green {db=dclosure_integration}} Error during index rebuild
java.lang.NullPointerException
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.doClearIndex(OAbstractPaginatedStorage.java:1785)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.clearIndex(OAbstractPaginatedStorage.java:1772)
	at com.orientechnologies.orient.core.index.OIndexAbstract.rebuild(OIndexAbstract.java:449)
	at com.orientechnologies.orient.core.index.OIndexAbstract.rebuild(OIndexAbstract.java:377)
	at com.orientechnologies.orient.core.index.OIndexAbstractDelegate.rebuild(OIndexAbstractDelegate.java:168)
	at com.orientechnologies.orient.core.metadata.schema.OClassImpl.truncate(OClassImpl.java:1547)
```

### Runninng Mode
- [ ] Embedded, using PLOCAL access mode

### OrientDB Version
- [ ] v2.2.x - Please specify last number: 2

### Operating System
- [ ] Linux

### Java Version
- [ ] 8

**Comment by laa** [comment]
HI @diegomtassis ,
Exception which you see is caused by other exception which is swallowed by given one.
If I send you distribution where root exception is logged, could you send me resulting log output ?

**Comment by laa** [comment]
Hi @diegomtassis could you run new distribution ?

**Comment by diegomtassis** [comment]
Hi @laa,

Sorry for the late reply, last week I was very busy.
With OrientDB 2.2.4 all my tests pass again.

Thanks.

**Comment by laa** [comment]
Cool so I close issue )). Thank you very much for answer
