### ISSUE TITLE
Lucene index error in migration from standalone to distributed

### ISSUE THREAD

**Issue by davidheryanto** [orientechnologies/orientdb#6320]
### Create base standalone database e.g. `testdb` in `node-1`
1. Start a server in standalone mode `server.sh`
2. Create a class say `Person` with property `id(INT), name(STRING)`
3. Create a `FULLTEXT LUCENE` index on `Person.name`
4. **Add** a Person record

### Deploy it as distributed databases
1. Stop standalone OrientDB
2. Copy testdb from `node-1` to `$ORIENTDB_HOME/databases/` in a different node e.g. `node-2`
3. Start OrientDB server in node-1 `bin/dserver.sh`
4. Wait until it finished initalizing, then execute `bin/dserver.sh` in node-2
5. An exception is thrown
```
2016-06-19 13:18:47:975 INFO  [node-2]->[node-1] Creating backup of database 'testdb' (compressionRate=7) in directory: /tmp/orientdb/backup_testdb.zip... [OSyncDatabaseTask]Exception in thread "OrientDB SyncDatabase node=node-2 db=testdb" com.orientechnologies.orient.core.exception.ODatabaseException: The database instance is not set in the current thread. Be sure to set it with: ODatabaseRecordThreadLocal.INSTANCE.set(db);
	at com.orientechnologies.orient.core.db.ODatabaseRecordThreadLocal.get(ODatabaseRecordThreadLocal.java:51)
	at com.orientechnologies.lucene.engine.OLuceneIndexEngineAbstract.getDatabase(OLuceneIndexEngineAbstract.java:311)
	at com.orientechnologies.lucene.engine.OLuceneIndexEngineAbstract.reOpen(OLuceneIndexEngineAbstract.java:209)
	at com.orientechnologies.lucene.engine.OLuceneIndexEngineAbstract.release(OLuceneIndexEngineAbstract.java:501)
	at com.orientechnologies.lucene.engine.OLuceneIndexEngineDelegate.release(OLuceneIndexEngineDelegate.java:275)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.release(OAbstractPaginatedStorage.java:2459)
	at com.orientechnologies.orient.core.storage.impl.local.paginated.OLocalPaginatedStorage.backup(OLocalPaginatedStorage.java:188)
	at com.orientechnologies.orient.server.distributed.impl.ODistributedStorage.backup(ODistributedStorage.java:1567)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.backup(ODatabaseDocumentTx.java:2847)
	at com.orientechnologies.orient.server.distributed.impl.task.OSyncDatabaseTask$1.run(OSyncDatabaseTask.java:125)
	at java.lang.Thread.run(Thread.java:745)
```

### Runninng Mode
- [x] Remote

### Misc
- [x] I have a distributed setup with 2 servers

### OrientDB Version
- [x] v2.2.2

### Operating System
- [x] Linux

### Java Version
- [x] 8

### NB
I think it has something to do with the way Lucene indexes are being replicated in distributed mode.

If I create the base DB *without* Lucene index and then I replicate it to another node in the same way as above. Then, only *after the 2 nodes finsished synchronizing*, I created the Lucene index, no error comes up. **This is my current workaround** which is rather inconvenient.

Also the exception does not come up with other built in indexes (happens only with Lucene)

**Comment by maggiolo00** [comment]
hi @davidheryanto 
Fixed it will be available in 
OrientDB 2.2.5
