### ISSUE TITLE
New record allocated but expected another rid

### ISSUE THREAD

**Issue by Dmitry-PlainID** [orientechnologies/orientdb#6323]
When using OrientDB 2.1.16 all the tests pass. After moving to OrientDB 2.2.0 some tests fail.
Sometime I get exception on creating new object:

Caused by: com.orientechnologies.orient.core.exception.OTransactionException: New record allocated #302:36 but the expected was #302:41
	Storage URL="plocal:/home/orientdb-community-2.2.0/databases/RuleEngineDB"
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.commit(OAbstractPaginatedStorage.java:1321)
	at com.orientechnologies.orient.server.distributed.impl.ODistributedStorage.commit(ODistributedStorage.java:1214)
	at com.orientechnologies.orient.core.tx.OTransactionOptimistic.doCommit(OTransactionOptimistic.java:555)
	at com.orientechnologies.orient.core.tx.OTransactionOptimistic.commit(OTransactionOptimistic.java:109)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.commit(ODatabaseDocumentTx.java:2664)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.commit(ODatabaseDocumentTx.java:2634)
	at com.orientechnologies.orient.server.distributed.impl.task.OTxTask.execute(OTxTask.java:118)
	at com.orientechnologies.orient.server.distributed.impl.ODistributedAbstractPlugin$1.call(ODistributedAbstractPlugin.java:591)
	at com.orientechnologies.orient.core.db.OScenarioThreadLocal.executeAsDistributed(OScenarioThreadLocal.java:70)
	at com.orientechnologies.orient.server.distributed.impl.ODistributedAbstractPlugin.executeOnLocalNode(ODistributedAbstractPlugin.java:587)
	at com.orientechnologies.orient.server.distributed.impl.ODistributedWorker.onMessage(ODistributedWorker.java:241)
	at com.orientechnologies.orient.server.distributed.impl.ODistributedWorker.run(ODistributedWorker.java:93)

**Comment by tglman** [comment]
hi all,
This should be fixed now, it will be released with 2.2.4, closing
