### ISSUE TITLE
Plocal engine not loading - Embedded Server

### ISSUE THREAD

**Issue by Dacnomanie** [orientechnologies/orientdb#6355]
Put the default database in GratefulDeadConcerts
Server is running in distributed mode
It's throwing errors about the 'plocal' engine not being loaded, it says only remote is loaded

Here's the log:

```
2016-06-28 17:09:14:461 WARNI MaxDirectMemorySize option is not set. It may cause OutOfMemoryError. Please set the option -XX:MaxDirectMemorySize=4096m when you start the JVM [orientechnologies]
2016-06-28 17:09:14:463 INFO  OrientDB auto-config DISKCACHE=1,137MB (heap=910MB os=4,096MB) [orientechnologies]
2016-06-28 17:09:14:501 INFO  Loading configuration from: config/orientdb-server-config.xml... [OServerConfigurationLoaderXml]
2016-06-28 17:09:14:855 INFO  OrientDB Server v2.2.0-beta2 is starting up... [OServer]
2016-06-28 17:09:14:862 INFO  Databases directory: /Library/WebServer/Documents/OTHER/CarnootServer/out/artifacts/Output/databases [OServer]
2016-06-28 17:09:15:078 INFO  Listening binary connections on 0.0.0.0:2424 (protocol v.34, socket=default) [OServerNetworkListener]
2016-06-28 17:09:15:081 INFO  Listening http connections on 0.0.0.0:2480 (protocol v.10, socket=default) [OServerNetworkListener]
2016-06-28 17:09:15:608 INFO  Installing dynamic plugin 'studio-2.2.zip'... [OServerPluginManager]
2016-06-28 17:09:15:642 INFO  Installed GREMLIN language v.2.6.0 - graph.pool.max=50 [OGraphServerHandler]
2016-06-28 17:09:15:718 INFO  Configuring Hazelcast from '/Library/WebServer/Documents/OTHER/CarnootServer/out/artifacts/Output/config/hazelcast.xml'. [FileSystemXmlConfig]
2016-06-28 17:09:15:779 WARNI Name of the hazelcast schema location incorrect using default [AbstractXmlConfigHelper]
2016-06-28 17:09:16:099 INFO  [LOCAL] [orientdb] [3.6.1] Prefer IPv4 stack is true. [DefaultAddressPicker]
2016-06-28 17:09:16:119 INFO  [LOCAL] [orientdb] [3.6.1] Picked Address[10.75.251.44]:2434, using socket ServerSocket[addr=/0:0:0:0:0:0:0:0,localport=2434], bind any local is true [DefaultAddressPicker]
2016-06-28 17:09:16:309 INFO  [10.75.251.44]:2434 [orientdb] [3.6.1] Backpressure is disabled [OperationService]
2016-06-28 17:09:16:335 INFO  [10.75.251.44]:2434 [orientdb] [3.6.1] Starting with 2 generic operation threads and 4 partition operation threads. [ClassicOperationExecutor]
2016-06-28 17:09:16:751 INFO  [10.75.251.44]:2434 [orientdb] [3.6.1] Hazelcast 3.6.1 (20160228 - d0d2a77) starting at Address[10.75.251.44]:2434 [system]
2016-06-28 17:09:16:752 INFO  [10.75.251.44]:2434 [orientdb] [3.6.1] Copyright (c) 2008-2016, Hazelcast, Inc. All Rights Reserved. [system]
2016-06-28 17:09:16:752 INFO  [10.75.251.44]:2434 [orientdb] [3.6.1] Configured Hazelcast Serialization version : 1 [system]
2016-06-28 17:09:16:768 INFO  [10.75.251.44]:2434 [orientdb] [3.6.1] Creating MulticastJoiner [Node]
2016-06-28 17:09:16:778 INFO  [10.75.251.44]:2434 [orientdb] [3.6.1] Address[10.75.251.44]:2434 is STARTING [LifecycleService]
2016-06-28 17:09:16:901 INFO  [10.75.251.44]:2434 [orientdb] [3.6.1] TcpIpConnectionManager configured with Non Blocking IO-threading model: 3 input threads and 3 output threads [NonBlockingIOThreadingModel]
2016-06-28 17:09:19:974 INFO  [10.75.251.44]:2434 [orientdb] [3.6.1] 


Members [1] {
	Member [10.75.251.44]:2434 this
}
 [MulticastJoiner]
2016-06-28 17:09:20:013 INFO  [10.75.251.44]:2434 [orientdb] [3.6.1] Address[10.75.251.44]:2434 is STARTED [LifecycleService]
2016-06-28 17:09:20:013 INFO  Starting distributed server 'AMNPICNJKBHCM' (hzID=-1)... [OHazelcastPlugin]
2016-06-28 17:09:20:054 INFO  [10.75.251.44]:2434 [orientdb] [3.6.1] Initializing cluster partition table arrangement... [InternalPartitionService]
2016-06-28 17:09:20:078 SEVER [AMNPICNJKBHCM] Cannot find node with id '3110776c-742d-4599-9a49-39f25982ac4a' [OHazelcastPlugin]
2016-06-28 17:09:20:110 INFO  [AMNPICNJKBHCM] Opening database 'GratefulDeadConcerts'... [OHazelcastPlugin]
2016-06-28 17:09:20:111 INFO  [AMNPICNJKBHCM] loaded database configuration from disk: /Library/WebServer/Documents/OTHER/CarnootServer/out/artifacts/Output/databases/GratefulDeadConcerts/distributed-config.json [OHazelcastPlugin]
2016-06-28 17:09:20:121 INFO  [AMNPICNJKBHCM] New distributed configuration for database: GratefulDeadConcerts (version=1)

LEGEND: X = Owner, o = Copy
+--------+-----------+----------+-------------+
|CLUSTER |writeQuorum|readQuorum|AMNPICNJKBHCM|
+--------+-----------+----------+-------------+
|*       |     1     |    1     |      X      |
|internal|     1     |    1     |             |
+--------+-----------+----------+-------------+

 [OHazelcastPlugin]
2016-06-28 17:09:20:122 INFO  [AMNPICNJKBHCM] Current node started as MASTER for database 'GratefulDeadConcerts' [OHazelcastPlugin]
2016-06-28 17:09:20:124 INFO  [AMNPICNJKBHCM] Removing offline server 'AMNPICNJKBHCM' for database 'GratefulDeadConcerts' in distributed configuration [OHazelcastPlugin]
2016-06-28 17:09:20:129 INFO  [AMNPICNJKBHCM] New distributed configuration for database: GratefulDeadConcerts (version=2)

LEGEND: X = Owner, o = Copy
+--------+-----------+----------+
|CLUSTER |writeQuorum|readQuorum|
+--------+-----------+----------+
|*       |     1     |    1     |
|internal|     1     |    1     |
+--------+-----------+----------+

 [OHazelcastPlugin]
2016-06-28 17:09:20:129 INFO  [AMNPICNJKBHCM] Saving distributed configuration file for database 'GratefulDeadConcerts' to: /Library/WebServer/Documents/OTHER/CarnootServer/out/artifacts/Output/databases/GratefulDeadConcerts/distributed-config.json [OHazelcastPlugin]
2016-06-28 17:09:20:136 INFO  [AMNPICNJKBHCM] adding node 'AMNPICNJKBHCM' in partition: db=GratefulDeadConcerts [*] [ODistributedDatabaseImpl]
2016-06-28 17:09:20:137 INFO  [AMNPICNJKBHCM] received new status AMNPICNJKBHCM.GratefulDeadConcerts=ONLINE [OHazelcastPlugin]
2016-06-28 17:09:20:138 INFO  [AMNPICNJKBHCM] New distributed configuration for database: GratefulDeadConcerts (version=3)

LEGEND: X = Owner, o = Copy
+--------+-----------+----------+-------------+
|CLUSTER |writeQuorum|readQuorum|AMNPICNJKBHCM|
+--------+-----------+----------+-------------+
|*       |     1     |    1     |      X      |
|internal|     1     |    1     |             |
+--------+-----------+----------+-------------+

 [OHazelcastPlugin]
2016-06-28 17:09:20:138 INFO  [AMNPICNJKBHCM] Saving distributed configuration file for database 'GratefulDeadConcerts' to: /Library/WebServer/Documents/OTHER/CarnootServer/out/artifacts/Output/databases/GratefulDeadConcerts/distributed-config.json [OHazelcastPlugin][AMNPICNJKBHCM] Error on starting distributed plugin
com.orientechnologies.orient.core.exception.ODatabaseException: Error on opening database 'plocal:/Library/WebServer/Documents/OTHER/CarnootServer/out/artifacts/Output/databases/GratefulDeadConcerts'
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.<init>(ODatabaseDocumentTx.java:179)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.<init>(ODatabaseDocumentTx.java:143)
	at com.orientechnologies.orient.server.OServer.openDatabase(OServer.java:874)
	at com.orientechnologies.orient.server.hazelcast.OHazelcastPlugin.loadDistributedDatabases(OHazelcastPlugin.java:1792)
	at com.orientechnologies.orient.server.hazelcast.OHazelcastPlugin.startup(OHazelcastPlugin.java:245)
	at com.orientechnologies.orient.server.OServer.registerPlugins(OServer.java:1166)
	at com.orientechnologies.orient.server.OServer.activate(OServer.java:383)
	at Program.main(Program.java:28)
Caused by: com.orientechnologies.orient.core.exception.OConfigurationException: Error on opening database: the engine 'plocal' was not found. URL was: plocal:/Library/WebServer/Documents/OTHER/CarnootServer/out/artifacts/Output/databases/GratefulDeadConcerts. Registered engines are: [remote]
	Storage URL="plocal:/Library/WebServer/Documents/OTHER/CarnootServer/out/artifacts/Output/databases/GratefulDeadConcerts"
	at com.orientechnologies.orient.core.Orient.loadStorage(Orient.java:477)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.<init>(ODatabaseDocumentTx.java:162)
	... 7 more
Exception in thread "OrientDB ONetworkProtocolHttpDb listen at 0.0.0.0:2480" com.orientechnologies.orient.server.distributed.ODistributedStartupException: Error on starting distributed plugin
	at com.orientechnologies.orient.server.hazelcast.OHazelcastPlugin.startup(OHazelcastPlugin.java:269)
	at com.orientechnologies.orient.server.OServer.registerPlugins(OServer.java:1166)
	at com.orientechnologies.orient.server.OServer.activate(OServer.java:383)
	at Program.main(Program.java:28)
Caused by: com.orientechnologies.orient.core.exception.ODatabaseException: Error on opening database 'plocal:/Library/WebServer/Documents/OTHER/CarnootServer/out/artifacts/Output/databases/GratefulDeadConcerts'
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.<init>(ODatabaseDocumentTx.java:179)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.<init>(ODatabaseDocumentTx.java:143)
	at com.orientechnologies.orient.server.OServer.openDatabase(OServer.java:874)
	at com.orientechnologies.orient.server.hazelcast.OHazelcastPlugin.loadDistributedDatabases(OHazelcastPlugin.java:1792)
	at com.orientechnologies.orient.server.hazelcast.OHazelcastPlugin.startup(OHazelcastPlugin.java:245)
	... 3 more
Caused by: com.orientechnologies.orient.core.exception.OConfigurationException: Error on opening database: the engine 'plocal' was not found. URL was: plocal:/Library/WebServer/Documents/OTHER/CarnootServer/out/artifacts/Output/databases/GratefulDeadConcerts. Registered engines are: [remote]
	Storage URL="plocal:/Library/WebServer/Documents/OTHER/CarnootServer/out/artifacts/Output/databases/GratefulDeadConcerts"
	at com.orientechnologies.orient.core.Orient.loadStorage(Orient.java:477)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.<init>(ODatabaseDocumentTx.java:162)
	... 7 more

```

Here's the code I am using:
 ```
public static void main(String[] args) throws Exception {
        System.setProperty("ORIENTDB_HOME",System.getProperty("user.dir"));
        System.setProperty("distributed","true");
        SecureRandom random = new SecureRandom();
        String RootPassword = new BigInteger(500000, random).toString(32);
        System.setProperty("ORIENTDB_ROOT_PASSWORD", RootPassword);
        System.setProperty("ORIENTDB_NODE_NAME", new BigInteger(64, random).toString(32).toUpperCase());

        OServer server = OServerMain.create();
        server.setServerRootDirectory(System.getProperty("user.dir"));
        server.startup();
        server.activate();

        Runnable WebService = new WebHandler(server);
        WebService.run();
    }
```

```
public class WebHandler implements Runnable {
    OServer Server;
    OPartitionedDatabasePoolFactory DBPoolFactory;

    public WebHandler(OServer Server) {
        this.Server = Server;
        DBPoolFactory = Server.getDatabasePoolFactory();
        OLogManager.instance().error(this, "test");
        for (OPartitionedDatabasePool PL : DBPoolFactory.getPools()){
            OLogManager.instance().error(this, PL.getUrl());
        }

        OLogManager.instance().error(this, "test2");

    }

    public void run() {
        while(true) {
            OLogManager.instance().error(this, Server.getDatabaseDirectory());
            try {
                Thread.sleep(1000);
            } catch (InterruptedException e) {
                e.printStackTrace();
            }
        }
    }
}
```

**Comment by maggiolo00** [comment]
hi @Dacnomanie 

how did you create the jar?

**Comment by Dacnomanie** [comment]
Manifest file pointing to the main class, referenced the server and client
jar and extracted all jar files in the lib directory to the output jar

**Comment by maggiolo00** [comment]
Hi @Dacnomanie 

if you are using maven and building a fat jar you should use maven shade plugin.
http://orientdb.com/docs/2.2.x/Tutorial-Installation.html#building-a-single-executable-jar-with-orientdb

**Comment by maggiolo00** [comment]
Or you can manually merge the Meta-Inf/services files

**Comment by maggiolo00** [comment]
@Dacnomanie 

did you try to merge the services files?

**Comment by Dacnomanie** [comment]
Haven't just yet, been busy. I will test it tonight or tomorrow.

**Comment by Dacnomanie** [comment]
Used maven shade, it worked.

**Comment by joshmalina** [comment]
@jacksenk mind posting your pom file for how you configured the shade plugin for orient?

**Comment by jacksenk** [comment]
Unfortunately, I no longer have access to that. My apologies.
