### ISSUE TITLE
Lucene tests are failed on Windows

### ISSUE THREAD

**Issue by laa** [orientechnologies/orientdb#6388]
Lucene tests are failed on Windows on 2.2.x branch with following output:

shouldBackupAndRestore(com.orientechnologies.lucene.test.LuceneBackupRestoreTest)  Time elapsed: 2.119 sec  <<< ERROR!
java.io.FileNotFoundException: .\target\com.orientechnologies.lucene.test.LuceneBackupRestoreTest\luceneIndexes\City.name_0.cfs (The requested operation cannot be performed on a file with a user-mapped section open)
        at java.io.FileOutputStream.open0(Native Method)
        at java.io.FileOutputStream.open(FileOutputStream.java:270)
        at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
        at java.io.FileOutputStream.<init>(FileOutputStream.java:162)
        at com.orientechnologies.orient.core.compression.impl.OZIPCompressionUtil.extractFile(OZIPCompressionUtil.java:100)
        at com.orientechnologies.orient.core.compression.impl.OZIPCompressionUtil.uncompressDirectory(OZIPCompressionUtil.java:88)
        at com.orientechnologies.orient.core.storage.impl.local.paginated.OLocalPaginatedStorage.restore(OLocalPaginatedStorage.java:204)
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.restore(ODatabaseDocumentTx.java:2860)
        at com.orientechnologies.lucene.test.LuceneBackupRestoreTest.shouldBackupAndRestore(LuceneBackupRestoreTest.java:100)

shouldBackupAndRestore(com.orientechnologies.lucene.test.LuceneBackupRestoreTest)  Time elapsed: 2.12 sec  <<< ERROR!
java.lang.IllegalStateException: Current instance is owned by other thread : 'main'
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.setupThreadOwner(ODatabaseDocumentTx.java:340)
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.open(ODatabaseDocumentTx.java:222)
        at com.orientechnologies.lucene.test.LuceneBackupRestoreTest.dropIfExists(LuceneBackupRestoreTest.java:71)
        at com.orientechnologies.lucene.test.LuceneBackupRestoreTest.tearDown(LuceneBackupRestoreTest.java:78)

**Comment by robfrank** [comment]
latest commit seems to solve this problem

**Comment by G4br13l3** [comment]
Hi guys, so we can close this issue?

Thanks.

**Comment by laa** [comment]
No, they still fail on Windows, result of build which I made a few minutes ago

```
Tests in error:
com.orientechnologies.lucene.test.LuceneAutomaticBackupRestoreTest.shouldBackupAndRestore(com.orientechnologies.lucene.test.LuceneAutomaticBackupRestoreTest)
  Run 1: LuceneAutomaticBackupRestoreTest.shouldBackupAndRestore:166 ▒ FileNotFound C:\...
  Run 2: LuceneAutomaticBackupRestoreTest.tearDown:112->dropIfExists:105 ▒ IllegalState

com.orientechnologies.lucene.test.LuceneBackupRestoreTest.shouldBackupAndRestore(com.orientechnologies.lucene.test.LuceneBackupRestoreTest)
  Run 1: LuceneBackupRestoreTest.shouldBackupAndRestore:100 ▒ FileNotFound .\target\com...
  Run 2: LuceneBackupRestoreTest.tearDown:78->dropIfExists:71 ▒ IllegalState Current in...

```
