### ISSUE TITLE
Unable to connect to remote server

### ISSUE THREAD

**Issue by MartinBrugnara** [orientechnologies/orientdb#6395]
## Expected behavior and actual behavior
Connect to remote server

## Steps to reproduce the problem
```
bash: (create the database)
> curl -X POST "http://orient:2480/database/mysuperdb/plocal/graph"

gremlin: (connect to the database)
> import com.tinkerpop.blueprints.impls.orient.OrientGraph
> g = new OrientGraph("remote:orient/mysuperdb")
```
#### Exception:
```
Exception in thread "main" java.lang.AbstractMethodError: com.orientechnologies.orient.client.remote.OEngineRemote.isShared()Z
        at com.orientechnologies.orient.core.Orient.loadStorage(Orient.java:236)
        at com.orientechnologies.orient.core.db.raw.ODatabaseRaw.open(ODatabaseRaw.java:88)
        at com.orientechnologies.orient.core.db.ODatabaseWrapperAbstract.open(ODatabaseWrapperAbstract.java:49)
        at com.orientechnologies.orient.core.db.record.ODatabaseRecordAbstract.open(ODatabaseRecordAbstract.java:119)
        at com.orientechnologies.orient.core.db.ODatabaseWrapperAbstract.open(ODatabaseWrapperAbstract.java:49)
        at com.tinkerpop.blueprints.impls.orient.OrientBaseGraph.openOrCreate(OrientBaseGraph.java:759)
        at com.tinkerpop.blueprints.impls.orient.OrientBaseGraph.<init>(OrientBaseGraph.java:98)
        at com.tinkerpop.blueprints.impls.orient.OrientTransactionalGraph.<init>(OrientTransactionalGraph.java:34)
        at com.tinkerpop.blueprints.impls.orient.OrientGraph.<init>(OrientGraph.java:27)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
        at org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstructor.java:77)
        at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrapNoCoerce.callConstructor(ConstructorSite.java:102)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallConstructor(CallSiteArray.java:54)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:182)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:190)
        at Script1.run(Script1.groovy:20)
        at com.tinkerpop.gremlin.groovy.jsr223.GremlinGroovyScriptEngine.eval(GremlinGroovyScriptEngine.java:219)
        at com.tinkerpop.gremlin.groovy.jsr223.GremlinGroovyScriptEngine.eval(GremlinGroovyScriptEngine.java:90)
        at com.tinkerpop.gremlin.groovy.jsr223.GremlinGroovyScriptEngine.eval(GremlinGroovyScriptEngine.java:85)
        at javax.script.AbstractScriptEngine.eval(AbstractScriptEngine.java:212)
        at com.tinkerpop.gremlin.groovy.jsr223.ScriptExecutor.evaluate(ScriptExecutor.java:36)
        at com.tinkerpop.gremlin.groovy.jsr223.ScriptExecutor.main(ScriptExecutor.java:20)
Exception in thread "Thread-2" java.lang.NullPointerException
        at com.orientechnologies.orient.client.remote.OEngineRemote.shutdown(OEngineRemote.java:68)
        at com.orientechnologies.orient.core.Orient.shutdown(Orient.java:143)
        at com.orientechnologies.orient.core.OrientShutdownHook.run(OrientShutdownHook.java:28)
```

### Runninng Mode
- [ ] Embedded, using PLOCAL access mode
- [ ] Embedded, using MEMORY access mode
- [x] Remote

### Misc
- [ ] I have a distributed setup with multiple servers. How many? 
- [ ] I'm using the Enterprise Edition

### OrientDB Version
- [ ] v2.0.x - Please specify last number: 
- [ ] v2.1.x - Please specify last number: 
- [x] v2.2.x - Please specify last number: 2.2.3

### Operating System
- [x] Linux
- [ ] MacOSX
- [ ] Windows
- [ ] Other Unix
- [ ] Other, name? 

### Java Version
- [ ] 6
- [ ] 7
- [x] 8 (FROM java:openjdk-8-jdk-alpine)

**Comment by tglman** [comment]
hi @MartinBrugnara 

This bug was fixed since 2.2.4.

Closing

**Comment by MartinBrugnara** [comment]
@tglman not really: I still got this:
```
Exception in thread "main" java.lang.AbstractMethodError: com.orientechnologies.orient.client.remote.OEngineRemote.isShared()Z
       	at com.orientechnologies.orient.core.Orient.loadStorage(Orient.java:236)
       	at com.orientechnologies.orient.core.db.raw.ODatabaseRaw.open(ODatabaseRaw.java:88)
       	at com.orientechnologies.orient.core.db.ODatabaseWrapperAbstract.open(ODatabaseWrapperAbstract.java:49)
       	at com.orientechnologies.orient.core.db.record.ODatabaseRecordAbstract.open(ODatabaseRecordAbstract.java:119)
       	at com.orientechnologies.orient.core.db.ODatabaseWrapperAbstract.open(ODatabaseWrapperAbstract.java:49)
       	at com.tinkerpop.blueprints.impls.orient.OrientBaseGraph.openOrCreate(OrientBaseGraph.java:759)
       	at com.tinkerpop.blueprints.impls.orient.OrientBaseGraph.<init>(OrientBaseGraph.java:98)
       	at com.tinkerpop.blueprints.impls.orient.OrientTransactionalGraph.<init>(OrientTransactionalGraph.java:34)
       	at com.tinkerpop.blueprints.impls.orient.OrientGraph.<init>(OrientGraph.java:27)
       	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
       	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
       	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
       	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
       	at org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstructor.java:77)
       	at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrapNoCoerce.callConstructor(ConstructorSite.java:102)
       	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallConstructor(CallSiteArray.java:54)
       	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:182)
       	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:190)
       	at Script1.run(Script1.groovy:20)
       	at com.tinkerpop.gremlin.groovy.jsr223.GremlinGroovyScriptEngine.eval(GremlinGroovyScriptEngine.java:219)
       	at com.tinkerpop.gremlin.groovy.jsr223.GremlinGroovyScriptEngine.eval(GremlinGroovyScriptEngine.java:90)
       	at com.tinkerpop.gremlin.groovy.jsr223.GremlinGroovyScriptEngine.eval(GremlinGroovyScriptEngine.java:85)
       	at javax.script.AbstractScriptEngine.eval(AbstractScriptEngine.java:212)
       	at com.tinkerpop.gremlin.groovy.jsr223.ScriptExecutor.evaluate(ScriptExecutor.java:36)
       	at com.tinkerpop.gremlin.groovy.jsr223.ScriptExecutor.main(ScriptExecutor.java:20)
```

Could this be related to the gremlin 2.4 driver?

**Comment by tglman** [comment]
hi,

it look like you have douplicated jars in your classpath, or something like that, do you use maven? what is are your dependencies ?

Regards

**Comment by MartinBrugnara** [comment]
Yes and no:
My whole setup consists of two containers - follows their definition - whose connections are defined by a compose file that also follows:

The one I use to run gremlin (gremlin-orientdb):
```
FROM anapsix/alpine-java:jdk7

MAINTAINER Brugnara <martin.brugnara@gmail.com>

WORKDIR /

ENV GREMLIN_TAG=2.4.0 \
    PATH=/opt/gremlin/bin:$PATH \
    GREMLIN_HOME=/opt/gremlin \
    ORIENTDB_VERSION=2.2.4

RUN apk add --update curl ca-certificates && \
    curl -L -o /tmp/gremlin.zip \
        tinkerpop.com/downloads/gremlin/gremlin-groovy-${GREMLIN_TAG}.zip && \
    unzip /tmp/gremlin.zip -d /opt/ && \
    rm /tmp/gremlin.zip && \
    ln -s /opt/gremlin-groovy-${GREMLIN_TAG} /opt/gremlin

# I also tried enabling the following two:
# RUN cd $GREMLIN_HOME/lib && curl -O http://central.maven.org/maven2/com/orientechnologies/orientdb-distributed/${ORIENTDB_VERSION}/orientdb-distributed-${ORIENTDB_VERSION}.jar
# RUN cd $GREMLIN_HOME/lib && curl -O http://central.maven.org/maven2/com/orientechnologies/orientdb-core/${ORIENTDB_VERSION}/orientdb-core-${ORIENTDB_VERSION}.jar

RUN cd $GREMLIN_HOME/lib && curl -O http://central.maven.org/maven2/com/orientechnologies/orientdb-client/${ORIENTDB_VERSION}/orientdb-client-${ORIENTDB_VERSION}.jar
RUN cd $GREMLIN_HOME/lib && curl -O http://central.maven.org/maven2/com/orientechnologies/orientdb-enterprise/${ORIENTDB_VERSION}/orientdb-enterprise-${ORIENTDB_VERSION}.jar

RUN sed -i.bak 's:$JAVA $JAVA_OPTIONS:$JAVA $JAVA_OPTIONS -Dstorage.diskCache.bufferSize=40960:g' /opt/gremlin/bin/gremlin.sh

WORKDIR /exp

CMD ["/exp/execute.sh"]
```

The server (orientdb):
```
############################################################
# Dockerfile to run an OrientDB (Graph) Container
############################################################

FROM java:openjdk-8-jdk-alpine

MAINTAINER OrientDB LTD (info@orientdb.com)

# Override the solr download location with e.g.:
#   docker build -t mine --build-arg ORIENTDB_DOWNLOAD_SERVER=http://repo1.maven.org/maven2/com/orientechnologies/ .
ARG ORIENTDB_DOWNLOAD_SERVER

ENV ORIENTDB_VERSION 2.2.4

ENV ORIENTDB_DOWNLOAD_URL ${ORIENTDB_DOWNLOAD_SERVER:-http://central.maven.org/maven2/com/orientechnologies/orientdb-community/}$ORIENTDB_VERSION/orientdb-community-$ORIENTDB_VERSION.zip

RUN apk add --update unzip curl && rm -rf /var/cache/apk/*

#download distribution tar, untar and delete databases
RUN \
  curl -o orientdb.zip $ORIENTDB_DOWNLOAD_URL \
  && unzip orientdb.zip -d /opt/ \
  && rm orientdb.zip \
  && rm -rf /orientdb/databases/* \
  && ln -s /opt/orientdb-community-${ORIENTDB_VERSION} /orientdb

ENV PATH /orientdb/bin:$PATH
RUN chmod +x  /orientdb/bin/*

# Disable volumes.
#VOLUME ["/orientdb/backup", "/orientdb/databases", "/orientdb/config"]

WORKDIR /orientdb

#OrientDb binary
EXPOSE 2424

#OrientDb http
EXPOSE 2480

# Default command start the server
CMD ["server.sh"]
```

Compose:
```
orientdb:
    image: gremlin-orientdb
    volumes:
        - ../exp/:/exp
    links:
        - orient
orient:
    image: orientdb
    command: server.sh
```

Thanks for reopening and helping!

**Comment by tglman** [comment]
hi @MartinBrugnara,

I see that for the client part you are getting gremling and the orientdb clinets libraries in a separate way, I would suggest to use everytime the orientdb distribution if is possible, because it contains all the libraries needed and also the gremlin libraries, all of it tested together.

Regards

**Comment by MartinBrugnara** [comment]
@tglman sorry for the delay,
I switched to use the binary shipped by orientdb, I also changed mode, I am now working with the embedded mode and `plocal` as storage.

I am now having other issue unrelated to this one, but they are already tracked in another thread (#6577).

Thank you for your support.
