### ISSUE TITLE
Error oteleporter (Too many open files)

### ISSUE THREAD

**Issue by e-Evolution** [orientechnologies/orientdb#6396]
## Expected behavior and actual behavior

Error when try using oteleporter for large DB using Postresql

## Steps to reproduce the problem

./oteleporter.sh -jdriver postgresql -jurl jdbc:postgresql://localhost:5433/382 -juser adempiere  -jpasswd adempiere  -ourl plocal:/Users/e-Evolution/Desktop/databases/382

### OrientDB Version

orientdb-enterprise-2.2.3

### Operating System

- [Capitan ] MacOSX

### Java Version
- [ ] 8

./oteleporter.sh -jdriver postgresql -jurl jdbc:postgresql://localhost:5433/382 -juser adempiere  -jpasswd adempiere  -ourl plocal:/Users/e-Evolution/Desktop/databases/382 

OrientDB                  
 ______________________________________________________________________________ 
 ___  __/__  ____/__  /___  ____/__  __ \_  __ \__  __\__  __/__  ____/__  _ _ \  
 __  /  __  __/  __  / __  __/  __  /_/ /  / / /_  /_/ /_  /  __  __/  __  /_/ /
 _  /   _  /___  _  /___  /___  _  ____// /_/ /_  _, _/_  /   _  /___  _  _, _/ 
 /_/    /_____/  /_____/_____/  /_/     \____/ /_/ |_| /_/    /_____/  /_/ |_|  

                                                  http://orientdb.com/teleporter

No configuration file was found. Migration will be performed with standard mapping policies.
(1/4) Source DB Schema building:    100% [....................]  Elapsed: 00:00:55  Remaining: 00:00:00  Warnings: 6
(2/4) Graph Model building:         100% [....................]  Elapsed: 00:00:00  Remaining: 00:00:00  Warnings: 6

(3/4) OrientDB Schema writing:       29% [.....               ]  Elapsed: 00:10:54  Remaining: 00:26:42  Warnings: 8memory errors. Please set the -XX:MaxDirectMemorySize=16384m option when you start the JVM. [Class]
ERROR: 
com.orientechnologies.orient.core.exception.OPaginatedClusterException - Error during creation of cluster with name pa_ratioelement_2
	DB name="382"
	Component Name="pa_ratioelement_2"
ERROR: 
com.orientechnologies.orient.core.exception.OPaginatedClusterException: Error during creation of cluster with name pa_ratioelement_2
	DB name="382"
	Component Name="pa_ratioelement_2"
	at com.orientechnologies.orient.core.storage.impl.local.paginated.OPaginatedCluster.create(OPaginatedCluster.java:201)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.addClusterInternal(OAbstractPaginatedStorage.java:3398)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.doAddCluster(OAbstractPaginatedStorage.java:3379)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.addCluster(OAbstractPaginatedStorage.java:511)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.addCluster(ODatabaseDocumentTx.java:1302)
	at com.orientechnologies.orient.core.metadata.schema.OSchemaShared.createClusters(OSchemaShared.java:1218)
	at com.orientechnologies.orient.core.metadata.schema.OSchemaShared.createClusters(OSchemaShared.java:1191)
	at com.orientechnologies.orient.core.metadata.schema.OSchemaShared.createClass(OSchemaShared.java:382)
	at com.orientechnologies.orient.core.metadata.schema.OSchemaShared.createClass(OSchemaShared.java:363)
	at com.orientechnologies.orient.core.metadata.schema.OSchemaProxy.createClass(OSchemaProxy.java:95)
	at com.tinkerpop.blueprints.impls.orient.OrientBaseGraph$5.call(OrientBaseGraph.java:1311)
	at com.tinkerpop.blueprints.impls.orient.OrientBaseGraph$5.call(OrientBaseGraph.java:1309)
	at com.tinkerpop.blueprints.impls.orient.OrientBaseGraph.executeOutsideTx(OrientBaseGraph.java:1829)
	at com.tinkerpop.blueprints.impls.orient.OrientBaseGraph.createVertexType(OrientBaseGraph.java:1309)
	at com.tinkerpop.blueprints.impls.orient.OrientBaseGraph.createVertexType(OrientBaseGraph.java:1276)
	at com.tinkerpop.blueprints.impls.orient.OrientBaseGraph.createVertexType(OrientBaseGraph.java:1247)
	at com.orientechnologies.teleporter.writer.OGraphModelWriter.writeModelOnOrient(OGraphModelWriter.java:102)
	at com.orientechnologies.teleporter.strategy.rdbms.ODBMSNaiveAggregationStrategy.createSchemaMapper(ODBMSNaiveAggregationStrategy.java:92)
	at com.orientechnologies.teleporter.strategy.rdbms.ODBMSImportStrategy.executeStrategy(ODBMSImportStrategy.java:85)
	at com.orientechnologies.teleporter.main.OTeleporter.execute(OTeleporter.java:272)
	at com.orientechnologies.teleporter.main.OTeleporter.main(OTeleporter.java:206)
Caused by: java.io.FileNotFoundException: /Users/e-Evolution/Desktop/databases/382/pa_ratioelement_2.cpm (Too many open files)
	at java.io.RandomAccessFile.open0(Native Method)
	at java.io.RandomAccessFile.open(RandomAccessFile.java:316)
	at java.io.RandomAccessFile.<init>(RandomAccessFile.java:243)
	at com.orientechnologies.orient.core.storage.fs.OFileClassic.openChannel(OFileClassic.java:791)
	at com.orientechnologies.orient.core.storage.fs.OFileClassic.create(OFileClassic.java:528)
	at com.orientechnologies.orient.core.storage.cache.local.OWOWCache.addFile(OWOWCache.java:1055)
	at com.orientechnologies.orient.core.storage.cache.local.OWOWCache.addFile(OWOWCache.java:450)
	at com.orientechnologies.orient.core.storage.cache.local.twoq.O2QCache.addFile(O2QCache.java:275)
	at com.orientechnologies.orient.core.storage.impl.local.paginated.atomicoperations.OAtomicOperation.commitChanges(OAtomicOperation.java:411)
	at com.orientechnologies.orient.core.storage.impl.local.paginated.atomicoperations.OAtomicOperationsManager.endAtomicOperation(OAtomicOperationsManager.java:420)
	at com.orientechnologies.orient.core.storage.impl.local.paginated.base.ODurableComponent.endAtomicOperation(ODurableComponent.java:116)
	at com.orientechnologies.orient.core.storage.impl.local.paginated.OPaginatedCluster.create(OPaginatedCluster.java:197)
	... 20 more

Exception in thread "main" com.orientechnologies.teleporter.exception.OTeleporterRuntimeException: com.orientechnologies.orient.core.exception.OPaginatedClusterException: Error during creation of cluster with name pa_ratioelement_2
	DB name="382"
	Component Name="pa_ratioelement_2"
	at com.orientechnologies.teleporter.writer.OGraphModelWriter.writeModelOnOrient(OGraphModelWriter.java:261)
	at com.orientechnologies.teleporter.strategy.rdbms.ODBMSNaiveAggregationStrategy.createSchemaMapper(ODBMSNaiveAggregationStrategy.java:92)
	at com.orientechnologies.teleporter.strategy.rdbms.ODBMSImportStrategy.executeStrategy(ODBMSImportStrategy.java:85)
	at com.orientechnologies.teleporter.main.OTeleporter.execute(OTeleporter.java:272)
	at com.orientechnologies.teleporter.main.OTeleporter.main(OTeleporter.java:206)
Caused by: com.orientechnologies.orient.core.exception.OPaginatedClusterException: Error during creation of cluster with name pa_ratioelement_2
	DB name="382"
	Component Name="pa_ratioelement_2"
	at com.orientechnologies.orient.core.storage.impl.local.paginated.OPaginatedCluster.create(OPaginatedCluster.java:201)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.addClusterInternal(OAbstractPaginatedStorage.java:3398)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.doAddCluster(OAbstractPaginatedStorage.java:3379)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.addCluster(OAbstractPaginatedStorage.java:511)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.addCluster(ODatabaseDocumentTx.java:1302)
	at com.orientechnologies.orient.core.metadata.schema.OSchemaShared.createClusters(OSchemaShared.java:1218)
	at com.orientechnologies.orient.core.metadata.schema.OSchemaShared.createClusters(OSchemaShared.java:1191)
	at com.orientechnologies.orient.core.metadata.schema.OSchemaShared.createClass(OSchemaShared.java:382)
	at com.orientechnologies.orient.core.metadata.schema.OSchemaShared.createClass(OSchemaShared.java:363)
	at com.orientechnologies.orient.core.metadata.schema.OSchemaProxy.createClass(OSchemaProxy.java:95)
	at com.tinkerpop.blueprints.impls.orient.OrientBaseGraph$5.call(OrientBaseGraph.java:1311)
	at com.tinkerpop.blueprints.impls.orient.OrientBaseGraph$5.call(OrientBaseGraph.java:1309)
	at com.tinkerpop.blueprints.impls.orient.OrientBaseGraph.executeOutsideTx(OrientBaseGraph.java:1829)
	at com.tinkerpop.blueprints.impls.orient.OrientBaseGraph.createVertexType(OrientBaseGraph.java:1309)
	at com.tinkerpop.blueprints.impls.orient.OrientBaseGraph.createVertexType(OrientBaseGraph.java:1276)
	at com.tinkerpop.blueprints.impls.orient.OrientBaseGraph.createVertexType(OrientBaseGraph.java:1247)
	at com.orientechnologies.teleporter.writer.OGraphModelWriter.writeModelOnOrient(OGraphModelWriter.java:102)
	... 4 more
Caused by: java.io.FileNotFoundException: /Users/e-Evolution/Desktop/databases/382/pa_ratioelement_2.cpm (Too many open files)
	at java.io.RandomAccessFile.open0(Native Method)
	at java.io.RandomAccessFile.open(RandomAccessFile.java:316)
	at java.io.RandomAccessFile.<init>(RandomAccessFile.java:243)
	at com.orientechnologies.orient.core.storage.fs.OFileClassic.openChannel(OFileClassic.java:791)
	at com.orientechnologies.orient.core.storage.fs.OFileClassic.create(OFileClassic.java:528)
	at com.orientechnologies.orient.core.storage.cache.local.OWOWCache.addFile(OWOWCache.java:1055)
	at com.orientechnologies.orient.core.storage.cache.local.OWOWCache.addFile(OWOWCache.java:450)
	at com.orientechnologies.orient.core.storage.cache.local.twoq.O2QCache.addFile(O2QCache.java:275)
	at com.orientechnologies.orient.core.storage.impl.local.paginated.atomicoperations.OAtomicOperation.commitChanges(OAtomicOperation.java:411)
	at com.orientechnologies.orient.core.storage.impl.local.paginated.atomicoperations.OAtomicOperationsManager.endAtomicOperation(OAtomicOperationsManager.java:420)
	at com.orientechnologies.orient.core.storage.impl.local.paginated.base.ODurableComponent.endAtomicOperation(ODurableComponent.java:116)
	at com.orientechnologies.orient.core.storage.impl.local.paginated.OPaginatedCluster.create(OPaginatedCluster.java:197)
	... 20 more

**Comment by G4br13l3** [comment]
Hi, there is a memory leak in orientdb core. We have just fixed it, thus it will be completely solved in orientdb 2.2.4 that will be released next week. Meanwhile you can try to set -XX:MaxDirectMemorySize=16384m option when you start the JVM as suggested in your stacktrace.
Let me know if you are able to bypass the issue in this way.
Thanks.

**Comment by G4br13l3** [comment]
Hi, there is a memory leak in orientdb core. We have just fixed it, thus it will be completely solved in orientdb 2.2.4 that will be released next week. Meanwhile you can try to set -XX:MaxDirectMemorySize=16384m option when you start the JVM as suggested in your stacktrace.
Let me know if you are able to bypass the issue in this way.
Thanks.

**Comment by G4br13l3** [comment]
The hotfix was released last Friday so this issue should be resolved. Let me know if there are new problems during the migration. 
Thanks
