### ISSUE TITLE
Calculations with sysdate in WHERE condition prevents index usage

### ISSUE THREAD

**Issue by xscratt** [orientechnologies/orientdb#6399]
## Expected behavior and actual behavior

I need to get the vertices in time window, which should be calculated based on the current date (for example, last 5 minutes; last hour). I created property `V.recordedAt` with type `DATETIME` with `NOTUNIQUE` index, and use queries kinda `SELECT FROM V WHERE recordedAt > sysdate() - 350000`. It works, however, OrientDB performs full scan of a class instead of index use, and the following message appears in the log.

```
$ANSI{green {db=test}} Error on using index V.recordedAt in query 'select FROM V WHERE recordedAt > sysdate() - 350000'. Probably you need to rebuild indexes. Now executing query using cluster scan
java.lang.ClassCastException: com.orientechnologies.orient.core.sql.filter.OSQLFilterCondition cannot be cast to java.util.Date
    at com.orientechnologies.common.serialization.types.ODateTimeSerializer.preprocess(ODateTimeSerializer.java:35)
    at com.orientechnologies.orient.core.index.sbtree.local.OSBTree.iterateEntriesMajorAsc(OSBTree.java:1185)
    at com.orientechnologies.orient.core.index.sbtree.local.OSBTree.iterateEntriesMajor(OSBTree.java:735)
    at com.orientechnologies.orient.core.index.engine.OSBTreeIndexEngine.iterateEntriesMajor(OSBTreeIndexEngine.java:186)
    at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.doIterateIndexEntriesMajor(OAbstractPaginatedStorage.java:2052)
    at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.iterateIndexEntriesMajor(OAbstractPaginatedStorage.java:2040)
    at com.orientechnologies.orient.core.index.OIndexMultiValues.iterateEntriesMajor(OIndexMultiValues.java:240)
    at com.orientechnologies.orient.core.index.OIndexAbstractDelegate.iterateEntriesMajor(OIndexAbstractDelegate.java:110)
    at com.orientechnologies.orient.core.index.OIndexTxAwareMultiValue.iterateEntriesMajor(OIndexTxAwareMultiValue.java:365)
    at com.orientechnologies.orient.core.sql.operator.OQueryOperatorMajor.executeIndexQuery(OQueryOperatorMajor.java:97)
    at com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.searchForIndexes(OCommandExecutorSQLSelect.java:2213)
    at com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.searchInClasses(OCommandExecutorSQLSelect.java:994)
    at com.orientechnologies.orient.core.sql.OCommandExecutorSQLResultsetAbstract.assignTarget(OCommandExecutorSQLResultsetAbstract.java:202)
    at com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.assignTarget(OCommandExecutorSQLSelect.java:515)
    at com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.executeSearch(OCommandExecutorSQLSelect.java:497)
    at com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.execute(OCommandExecutorSQLSelect.java:473)
    at com.orientechnologies.orient.core.sql.OCommandExecutorSQLDelegate.execute(OCommandExecutorSQLDelegate.java:72)
    at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.executeCommand(OAbstractPaginatedStorage.java:2577)
    at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.command(OAbstractPaginatedStorage.java:2523)
    at com.orientechnologies.orient.core.sql.query.OSQLQuery.run(OSQLQuery.java:78)
    at com.orientechnologies.orient.core.sql.query.OSQLAsynchQuery.run(OSQLAsynchQuery.java:74)
    at com.orientechnologies.orient.core.sql.query.OSQLSynchQuery.run(OSQLSynchQuery.java:85)
    at com.orientechnologies.orient.core.query.OQueryAbstract.execute(OQueryAbstract.java:33)
    at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.command(ONetworkProtocolBinary.java:1421)
    at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.executeRequest(ONetworkProtocolBinary.java:456)
    at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.execute(ONetworkProtocolBinary.java:199)
    at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:77)
```

Also I noticed if use `eval` it works as expected: `SELECT FROM V WHERE recordedAt > eval("sysdate() - 350000")` (the error is not appeared and index is used). Is it correct behavior, or it's a bug?

## Steps to reproduce the problem

Create database and run the following commands:
```sql
ALTER DATABASE DATETIMEFORMAT "yyyy-MM-dd'T'HH:mm:ss.SSS'Z'"
ALTER DATABASE DATEFORMAT "yyyy-MM-dd"
ALTER DATABASE TIMEZONE "UTC"

CREATE PROPERTY V.recordedAt DATETIME
ALTER PROPERTY V.recordedAt MANDATORY TRUE
ALTER PROPERTY V.recordedAt NOTNULL TRUE

CREATE INDEX V.recordedAt NOTUNIQUE METADATA {ignoreNullValues: true}

CREATE VERTEX V SET name="test1", recordedAt=sysdate()
CREATE VERTEX V SET name="test2", recordedAt=sysdate()
CREATE VERTEX V SET name="test3", recordedAt=sysdate()

SELECT FROM V WHERE recordedAt > sysdate() - 350000
```
Last query returns correct result, but doesn't use index.

### Runninng Mode
- [ ] Embedded, using PLOCAL access mode
- [ ] Embedded, using MEMORY access mode
- [x] Remote

### Misc
- [ ] I have a distributed setup with multiple servers. How many? 
- [ ] I'm using the Enterprise Edition

### OrientDB Version
- [ ] v2.0.x
- [ ] v2.1.x
- [x] v2.2.x - OrientDB 2.2.3 Community

### Operating System
- [x] Linux, image from [dockerhub](https://hub.docker.com/_/orientdb/)
- [ ] MacOSX
- [ ] Windows
- [ ] Other Unix
- [ ] Other, name? 

### Java Version
- [ ] 6
- [ ] 7
- [x] 8

**Comment by luigidellaquila** [comment]
Hi @xscratt 

it seems to be a bug, I'll take a look at it in next few hours/days

Thanks

Luigi

**Comment by luigidellaquila** [comment]
Hi @xscratt 

I fixed the exception, but the query is still not able to use the index in that case.
Anyway, I strongly suggest you to use eval() in these cases, because math expressions in the current executor are not completely supported (they will be in next release)

Thanks

Luigi

**Comment by xscratt** [comment]
Hi @luigidellaquila 

Thank you!
