### ISSUE TITLE
Error on opening database: the engine 'remote' was not found.

### ISSUE THREAD

**Issue by daiyueweng** [orientechnologies/orientdb#6420]
## Expected behavior and actual behavior
should connect to the database specified straight away

## Steps to reproduce the problem
    import com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx;
    import com.orientechnologies.orient.core.record.impl.ODocument;

    public class OrientDBJavaTest {

    public static void main(String[] args) {
        
        // OPEN THE DATABASE
        ODatabaseDocumentTx db = new  ODatabaseDocumentTx("remote:localhost/OrientDBTest").open("admin", "admin");

        // CREATE A NEW DOCUMENT AND FILL IT
        ODocument doc = new ODocument("Person");
        doc.field("name", "Luke");
        doc.field("surname", "Skywalker");
        doc.field("city", new ODocument("City").field("name", "Rome").field("country", "Italy"));

        // SAVE THE DOCUMENT
        doc.save();

        db.close();
    }
    
}

## Important Questions
I have added the following jars
`orientdb-core-2.2.4.jar`
`concurrentlinkedhashmap-lru-1.4.1.jar`
`orientdb-client-2.2.4.jar`
`orientdb-server-2.2.4.jar`

couldn't find `orientdb-enterprise-**.jar` in `lib`

Created a database using `Orientdb studio` called `OrientDBTest`.

Tried the example listed in the documentation, but didn't work, got the following errors:

    Exception in thread "main" com.orientechnologies.orient.core.exception.ODatabaseException: Error on opening database 'remote:localhost/OrientDBTest'
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.<init>(ODatabaseDocumentTx.java:187)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.<init>(ODatabaseDocumentTx.java:148)
	at orientdbjavatest.OrientDBJavaTest.main(OrientDBJavaTest.java:24)
    Caused by: com.orientechnologies.orient.core.exception.OConfigurationException: Error on opening database: the engine 'remote' was not found. URL was: remote:localhost/OrientDBTest. Registered engines are: [memory, plocal]
	DB name="remote:localhost/OrientDBTest"
	at com.orientechnologies.orient.core.Orient.loadStorage(Orient.java:476)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.<init>(ODatabaseDocumentTx.java:167)
	... 2 more
    C:\Users\user\AppData\Local\NetBeans\Cache\8.1\executor-snippets\run.xml:53: Java returned: 1

### Runninng Mode
- [x] Remote

### Misc
- [x] I'm using the Community Edition

### OrientDB Version
- [x] v2.2.x - Please specify last number: 4 

### Operating System
- [x] Windows 10 X64 

### Java Version
- [x] 8

**Comment by maggiolo00** [comment]
@daiyueweng 

how did you add the jars?

**Comment by daiyueweng** [comment]
under `netbeans`, right clicked `Libraries`, `Add JAR/Folder`

**Comment by maggiolo00** [comment]
From Exception 
Seems that orientdb-client.* is missing.

**Comment by daiyueweng** [comment]
run it again, 

    Exception in thread "main" com.orientechnologies.orient.core.exception.ODatabaseException: Error on opening database 'remote:localhost/OrientDBTest'
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.<init>(ODatabaseDocumentTx.java:187)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.<init>(ODatabaseDocumentTx.java:148)
	at orientdbjavatest.OrientDBJavaTest.main(OrientDBJavaTest.java:24)
    Caused by: com.orientechnologies.orient.core.exception.OConfigurationException: Error on opening database: the engine 'remote' was not found. URL was: remote:localhost/OrientDBTest. Registered engines are: [memory, plocal]
	DB name="remote:localhost/OrientDBTest"
	at com.orientechnologies.orient.core.Orient.loadStorage(Orient.java:476)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.<init>(ODatabaseDocumentTx.java:167)
	... 2 more`

**Comment by maggiolo00** [comment]
Can you look for the class

`OStorageRemote` in your classpath?
is it available?

**Comment by daiyueweng** [comment]
`OStorageRemote` can't be found in `lib`, hence I couldn't add it to the classpath in NetBeans.

**Comment by maggiolo00** [comment]
Can you screenshot your lib folder?

**Comment by daiyueweng** [comment]
![orientdb_lib](https://cloud.githubusercontent.com/assets/16350007/16869981/4a730692-4a77-11e6-901c-9378a31b041a.PNG)

**Comment by maggiolo00** [comment]
Seems that NetBeans does not found orientdb-client.*.jar

**Comment by maggiolo00** [comment]
You could use maven to better manage the orientdb dependency

**Comment by daiyueweng** [comment]
this is the screenshot of my orientdb test project structure in NetBeans

![orientdb_netbeans_lib](https://cloud.githubusercontent.com/assets/16350007/16870276/b12dcd44-4a78-11e6-9241-a51b91281e3a.PNG)

**Comment by maggiolo00** [comment]
Cool 👍

**Comment by LianaNapalkova** [comment]
I have the same issue in IntellijIDEA 2018.1.6 with SBT project. The error message `Caused by: com.orientechnologies.orient.core.exception.OConfigurationException: Error on opening database: the engine 'remote' was not found. URL was: remote:XXX.XX.XX.XX/database/TEST_1. Registered engines are: []`. The class `OStorageRemote` is included in the path.

**Comment by maggiolo00** [comment]
hi @LianaNapalkova 

did you include `orientdb-client` as dependency?

**Comment by LianaNapalkova** [comment]
Yes, orientdb-client:2.2.2, orientdb-core:2.2.2, orientdb-graphdb:2.2.2, orientdb-server:2.2.2 and orientdb-tools:2.2.2 are included.
