### ISSUE TITLE
Impossible to add a null identifiable in a ridbag

### ISSUE THREAD

**Issue by OTalmor** [orientechnologies/orientdb#6467]
## OrientDB Version, operating system, or hardware.

v2.2.5 
## Operating System
- [ X] Linux
## Expected behaviour and actual behaviour

object should be created but fails with the following: 
2016-07-26 05:51:23,995 WARNING [com.orientechnologies.orient.server.distributed.ODistributedResponseManager](default task-36) [nodea] Detected 1 node(s) in timeout or in conflict and quorum (2) has not been reached, rolling back changes for request (id=1.31 task=tx user=#5:0)
2016-07-26 05:51:23,997 SEVERE [com.orientechnologies.orient.server.distributed.impl.ODistributedTxContextImpl](default task-36) [nodea] Error on fixing transaction 1.31 db=RuleEngineDB task=record_update(#156:0 v.4726 realV.-2147478922): java.lang.NullPointerException: Impossible to add a null identifiable in a ridbag at com.orientechnologies.orient.core.db.record.ridbag.embedded.OEmbeddedRidBag.addEntry(OEmbeddedRidBag.java:492) at com.orientechnologies.orient.core.db.record.ridbag.embedded.OEmbeddedRidBag.doDeserialization(OEmbeddedRidBag.java:541)
this happens after I restart one of the node (embedded) of my distibuted environment. 
## Steps to reproduce the problem

restart embedded node. 
creating an object that is referring to another object.

**Comment by tglman** [comment]
hi, 
Just made a check to keep the original value instead of make this exception come up, this will not solve the original problem of data record content propagation in distributed.

Regards.

**Comment by G4br13l3** [comment]
Hi @OTalmor,

did you try with last hotfix?

Thanks.

**Comment by lvca** [comment]
I'm closing this issue because of no response since a while. In case the issue is still valid, please reopen/comment this. Thanks.
