### ISSUE TITLE
com.orientechnologies.orient.enterprise.channel.binary.OTokenSecurityException: The token provided is expired

### ISSUE THREAD

**Issue by kumarkshiva** [orientechnologies/orientdb#6468]
Our tests initiated using Jmeter are failing after 4th iteration.
More details are as below :-
```
2016-07-26 15:06:29:993 INFO  OrientDB auto-config DISKCACHE=6,372MB (heap=6,372MB direct=6,372MB os=28,671MB), assuming maximum direct memory size equals to maximum JVM heap size [orientechnologies]
2016-07-26 15:06:30:047 WARNI MaxDirectMemorySize JVM option is not set or has invalid value, that may cause out of memory errors. Please set the -XX:MaxDirectMemorySize=28671m option when you start the JVM. [Class]
2016-07-26 15:06:30:145 WARNI MaxDirectMemorySize JVM option is not set or has invalid value, that may cause out of memory errors. Please set the -XX:MaxDirectMemorySize=28671m option when you start the JVM. [Class]
2016-07-26 15:06:30:181 INFO  Loading configuration from: C:/IntelliSURF/orientdb-community-2.2.0-GA/config/orientdb-server-config.xml... [OServerConfigurationLoaderXml]
2016-07-26 15:06:30:698 INFO  OrientDB Server v2.2.0 (build @BUILD@) is starting up... [OServer]
2016-07-26 15:06:30:709 INFO  Databases directory: C:\IntelliSURF\orientdb-community-2.2.0-GA\databases [OServer]
2016-07-26 15:06:31:107 INFO  Listening binary connections on 0.0.0.0:3424 (protocol v.36, socket=default) [OServerNetworkListener]
2016-07-26 15:06:31:110 INFO  Listening http connections on 0.0.0.0:2480 (protocol v.10, socket=default) [OServerNetworkListener]
2016-07-26 15:06:31:120 WARNI Found ORIENTDB_ROOT_PASSWORD variable, using this value as root's password [OServer]
2016-07-26 15:06:31:605 INFO  Installing dynamic plugin 'orientdb-spatial-2.2.0-dist.jar'... [OServerPluginManager]
2016-07-26 15:06:31:616 INFO  Spatial index plugin startup [OLuceneSpatialIndexPlugin]
2016-07-26 15:06:31:718 INFO  Spatial index plugin installed and active. Lucene version: 5.3.2 [OLuceneSpatialIndexPlugin]
2016-07-26 15:06:31:719 INFO  Installing dynamic plugin 'studio-2.2.zip'... [OServerPluginManager]
2016-07-26 15:06:31:761 INFO  Installed GREMLIN language v.2.6.0 - graph.pool.max=50 [OGraphServerHandler]
2016-07-26 15:06:31:761 INFO  [OVariableParser.resolveVariables] Error on resolving property: distributed [orientechnologies]
2016-07-26 15:06:31:761 WARNI Authenticated clients can execute any kind of code into the server by using the following allowed languages: [sql] [OServerSideScriptInterpreter]
2016-07-26 15:06:31:770 INFO  ODefaultPasswordAuthenticator is active [ODefaultPasswordAuthenticator]
2016-07-26 15:06:31:770 INFO  OServerConfigAuthenticator is active [OServerConfigAuthenticator]
2016-07-26 15:06:31:770 INFO  OSystemUserAuthenticator is active [OSystemUserAuthenticator]
2016-07-26 15:06:31:770 INFO  OrientDB Server is active v2.2.0 (build @BUILD@). [OServer]
2016-07-26 15:07:12:402 WARNI {db=isc} Storage 'isc' was not closed properly. Will try to recover from write ahead log [OLocalPaginatedStorage]
2016-07-26 15:07:12:403 INFO  {db=isc} Looking for last checkpoint... [OLocalPaginatedStorage]
2016-07-26 15:07:13:556 INFO  {db=isc} Found FUZZY checkpoint. [OLocalPaginatedStorage]
2016-07-26 15:07:13:557 INFO  {db=isc} Data restore procedure from FUZZY checkpoint is started. [OLocalPaginatedStorage]
2016-07-26 15:07:13:559 WARNI {db=isc} Record com.orientechnologies.orient.core.storage.impl.local.paginated.wal.OFuzzyCheckpointEndRecord{lsn=OLogSequenceNumber{segment=0, position=30710138}} will be skipped during data restore [OLocalPaginatedStorage]
2016-07-26 15:07:13:567 WARNI {db=isc} Record OFuzzyCheckpointStartRecord{lsn=OLogSequenceNumber{segment=0, position=30710145}} com.orientechnologies.orient.core.storage.impl.local.paginated.wal.OFuzzyCheckpointStartRecord{lsn=null, previousCheckpoint=OLogSequenceNumber{segment=0, position=30710098}} will be skipped during data restore [OLocalPaginatedStorage]
2016-07-26 15:07:13:567 WARNI {db=isc} Record com.orientechnologies.orient.core.storage.impl.local.paginated.wal.OFuzzyCheckpointEndRecord{lsn=OLogSequenceNumber{segment=0, position=30710185}} will be skipped during data restore [OLocalPaginatedStorage]
2016-07-26 15:07:13:567 INFO  {db=isc} Storage data recover was completed [OLocalPaginatedStorage]Error executing request
com.orientechnologies.orient.enterprise.channel.binary.OTokenSecurityException: The token provided is expired
	at com.orientechnologies.orient.server.OClientConnection.validateSession(OClientConnection.java:167)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.solveSession(ONetworkProtocolBinary.java:274)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.onBeforeRequest(ONetworkProtocolBinary.java:215)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.execute(ONetworkProtocolBinary.java:173)
	at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:77)
Error executing request
```

**Comment by luigidellaquila** [comment]
Hi @kumarkshiva 

The exception you see in the stack trace was already fixed in v. 2.2.5 (latest stable), do you have a chance to try it?

Thanks

Luigi

**Comment by kumarkshiva** [comment]
after upgrade to 2.2.5 , we are seeing the issues :-

2016-08-05 17:31:57:530 INFO  Loading configuration from: C:/IntelliSURF/orientdb-community-2.2.5/config/orientdb-server-config.xml... [OServerConfigurationLoaderXml]
2016-08-05 17:31:57:809 INFO  OrientDB Server v2.2.5 (build @BUILD@) is starting up... [OServer]
2016-08-05 17:31:57:815 INFO  Databases directory: C:\IntelliSURF\orientdb-community-2.2.5\databases [OServer]
2016-08-05 17:31:57:876 INFO  OrientDB auto-config DISKCACHE=3,600MB (heap=3,600MB direct=3,600MB os=16,197MB), assuming maximum direct memory size equals to maximum JVM heap size [orientechnologies]
2016-08-05 17:31:57:877 WARNI MaxDirectMemorySize JVM option is not set or has invalid value, that may cause out of memory errors. Please set the -XX:MaxDirectMemorySize=16197m option when you start the JVM. [Class]
2016-08-05 17:31:58:769 INFO  Listening binary connections on 0.0.0.0:3424 (protocol v.36, socket=default) [OServerNetworkListener]
2016-08-05 17:31:58:776 INFO  Listening http connections on 0.0.0.0:3480 (protocol v.10, socket=default) [OServerNetworkListener]
2016-08-05 17:31:58:788 INFO  Installing dynamic plugin 'studio-2.2.zip'... [OServerPluginManager]
2016-08-05 17:31:58:829 INFO  Installed GREMLIN language v.2.6.0 - graph.pool.max=50 [OGraphServerHandler]
2016-08-05 17:31:58:830 INFO  [OVariableParser.resolveVariables] Error on resolving property: distributed [orientechnologies]
2016-08-05 17:31:58:835 WARNI Authenticated clients can execute any kind of code into the server by using the following allowed languages: [sql] [OServerSideScriptInterpreter]
2016-08-05 17:31:58:839 INFO  ODefaultPasswordAuthenticator is active [ODefaultPasswordAuthenticator]
2016-08-05 17:31:58:841 INFO  OServerConfigAuthenticator is active [OServerConfigAuthenticator]
2016-08-05 17:31:58:842 INFO  OSystemUserAuthenticator is active [OSystemUserAuthenticator]
2016-08-05 17:31:58:844 INFO  OrientDB Server is active v2.2.5 (build @BUILD@). [OServer]
2016-08-05 17:31:59:086 WARNI Token signature failure: AAAAAANpc2MA/////////////wAAAVZP2KtSAQAEcm9vdAAkABdPUmVjb3JkU2VyaWFsaXplckJpbmFyeQANT3JpZW50REIgSmF2YQAFMi4yLjADEseWC0dOHN2KMXqF2cvh0/cNudXkzN/0fZ9yA88s9w== [OTokenHandlerImpl]Error executing request
com.orientechnologies.orient.enterprise.channel.binary.OTokenSecurityException: The token provided is not a valid token, signature does not match
	at com.orientechnologies.orient.server.OClientConnection.validateSession(OClientConnection.java:174)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.solveSession(ONetworkProtocolBinary.java:289)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.onBeforeRequest(ONetworkProtocolBinary.java:226)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.execute(ONetworkProtocolBinary.java:184)
	at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:77)

**Comment by fabriziofortino** [comment]
I am experiencing the same problem with v 2.2.6.

I have a java application (spring-boot) connected to an OrientDB Server through the java client (I use the connections pool). When the application starts I don't see any problem. After a while every request throws the below errors on the ODB server. It's worth noticing that the request return the correct result but the errors slow down the query drastically.

```
Error executing request
orientdb_1  | com.orientechnologies.orient.enterprise.channel.binary.OTokenSecurityException: The token provided is expired
orientdb_1  | 	DB name="my-db"
orientdb_1  | 	at com.orientechnologies.orient.server.OClientConnection.validateSession(OClientConnection.java:178)
orientdb_1  | 	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.solveSession(ONetworkProtocolBinary.java:294)
orientdb_1  | 	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.onBeforeRequest(ONetworkProtocolBinary.java:231)
orientdb_1  | 	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.execute(ONetworkProtocolBinary.java:188)
orientdb_1  | 	at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:77)
orientdb_1  | Error executing request
orientdb_1  | com.orientechnologies.orient.enterprise.channel.binary.OTokenSecurityException: missing session and token
orientdb_1  | 	DB name="my-db"
orientdb_1  | 	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.solveSession(ONetworkProtocolBinary.java:290)
orientdb_1  | 	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.onBeforeRequest(ONetworkProtocolBinary.java:231)
orientdb_1  | 	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.execute(ONetworkProtocolBinary.java:188)
orientdb_1  | 	at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:77)
```

**Comment by fabriziofortino** [comment]
I have upgraded client and server to v 2.2.7 and tested it for several hours.

I can't see the server side errors anymore. When the client makes some request after a period of inactivity I see the following logs

`2016-08-18 10:17:54.876  INFO 4563 --- [nio-8090-exec-9] c.o.orient.client.remote.OStorageRemote  : Caught Network I/O errors on 192.168.99.102:2424/my-db, trying an automatic reconnection... (error: Channel is closed)`

After a few requests these logs disappear and the queries response time improves (back to the original value I'd say). I think this is the correct behaviour: the 'bad' connections in the pool get replaced with the 'good' ones.

The issue has been fixed. Thanks!

**Comment by lvca** [comment]
Cool, thanks for the report.
