### ISSUE TITLE
unable to deploy orientdb 2.2 with openJDK 8 and jboss eap 6.2

### ISSUE THREAD

**Issue by balamanian** [orientechnologies/orientdb#6472]
Hi i am using open jdk 8 and jboss eap 6.2 for my application. while creating OrientGraphFactory, it will throw the below exception 

Caused by: java.lang.NoClassDefFoundError: Could not initialize class com.orientechnologies.orient.core.db.OPartitionedDatabasePool$DatabaseDocumentTxPolled
    at com.orientechnologies.orient.core.db.OPartitionedDatabasePool.initQueue(OPartitionedDatabasePool.java:442) [orientdb-core-2.2.2.jar:2.2.2]
    at com.orientechnologies.orient.core.db.OPartitionedDatabasePool.<init>(OPartitionedDatabasePool.java:217) [orientdb-core-2.2.2.jar:2.2.2]
    at com.tinkerpop.blueprints.impls.orient.OrientGraphFactory.<init>(OrientGraphFactory.java:78) [orientdb-graphdb-2.2.2.jar:2.2.2]
    at com.tinkerpop.blueprints.impls.orient.OrientGraphFactory.<init>(OrientGraphFactory.java:55) [orientdb-graphdb-2.2.2.jar:2.2.2]
    at com.cisco.sdp.core.graph.OrientDbClient.afterPropertiesSet(OrientDbClient.java:88) [platform-core.jar:]
    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1633) [spring-beans-4.1.6.RELEASE.jar:4.1.6.RELEASE]
    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1570) [spring-beans-4.1.6.RELEASE.jar:4.1.6.RELEASE]
    ... 52 more

when i tried with my standalone program with openjdk 8, its working fine.. but while trying to deploy on jboss eap 6.2 its failing..

Please guide me to solve that issue

**Comment by balamanian** [comment]
Hi,
  its not issue with orient db side... it problem with class my class loading setting on server side.

thanks
