### ISSUE TITLE
NPE while updating Lucene-indexed field

### ISSUE THREAD

**Issue by vantonov1** [orientechnologies/orientdb#6490]
v2.2.3

1 Create record with Lucene indexed field == null
2 Update record with field not null

After update, trying to remove old (non-existing) value, OLuceneTxChangesMultiRid.remove calls key.toString() with key == null

com.orientechnologies.orient.core.exception.ODatabaseException: Error on saving record #561:10
	DB name="default"
	at com.orientechnologies.orient.core.tx.OTransactionOptimistic.addRecord(OTransactionOptimistic.java:526)
	at com.orientechnologies.orient.core.tx.OTransactionOptimistic.saveRecord(OTransactionOptimistic.java:367)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.save(ODatabaseDocumentTx.java:2534)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.save(ODatabaseDocumentTx.java:101)
	at com.orientechnologies.orient.core.record.impl.ODocument.save(ODocument.java:1794)
	at com.orientechnologies.orient.core.record.impl.ODocument.save(ODocument.java:1785)
	at com.tinkerpop.blueprints.impls.orient.OrientElement.save(OrientElement.java:327)
	at com.tinkerpop.blueprints.impls.orient.OrientElement.save(OrientElement.java:309)
	at com.tinkerpop.blueprints.impls.orient.OrientElement.setProperty(OrientElement.java:196)

Caused by: java.lang.NullPointerException
	at com.orientechnologies.lucene.tx.OLuceneTxChangesMultiRid.remove(OLuceneTxChangesMultiRid.java:58)
	at com.orientechnologies.lucene.index.OLuceneIndexNotUnique.remove(OLuceneIndexNotUnique.java:159)
	at com.orientechnologies.orient.core.index.OClassIndexManager.removeFromIndex(OClassIndexManager.java:617)
	at com.orientechnologies.orient.core.index.OClassIndexManager.deleteIndexKey(OClassIndexManager.java:268)
	at com.orientechnologies.orient.core.index.OClassIndexManager.processIndexUpdateFieldAssignment(OClassIndexManager.java:206)
	at com.orientechnologies.orient.core.index.OClassIndexManager.processSingleIndexUpdate(OClassIndexManager.java:179)
	at com.orientechnologies.orient.core.index.OClassIndexManager.processIndexUpdate(OClassIndexManager.java:456)
	at com.orientechnologies.orient.core.index.OClassIndexManager.onRecordAfterUpdate(OClassIndexManager.java:440)
	at com.orientechnologies.orient.core.hook.ODocumentHookAbstract.onTrigger(ODocumentHookAbstract.java:260)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.callbackHooks(ODatabaseDocumentTx.java:1075)
	at com.orientechnologies.orient.core.tx.OTransactionOptimistic.addRecord(OTransactionOptimistic.java:501)

**Comment by maggiolo00** [comment]
hi @vantonov1 

within the same Transaction?

**Comment by maggiolo00** [comment]
Which is the type of the field indexed?

**Comment by vantonov1** [comment]
1No, it is 2 separate transactions
2 LINKLIST. Im trying to index blob (stored as a list of ORecordBytes) by Lucene, not sure it is a right way

For Lucene index, isNullValuesIgnored() is false (really?), but OLuceneTxChangesMultiRid doesnt support removing null value

**Comment by maggiolo00** [comment]
@vantonov1 

that was changed in 2.2.x by default for indexes. I guess yes it OLuceneTxChangesMultiRid does not support removing null values.

2) I'm not sure you can do that. You can index LinkList of String. How are you going to query a ORecordBytes stored in Lucene?

**Comment by vantonov1** [comment]
Well, what I want is to be able to do select .... LUCENE <word in the blob>

**Comment by vantonov1** [comment]
Ops, select LUCENE some-word-in-the-blob

**Comment by maggiolo00** [comment]
Yes but against ORecordBytes ( byte[] ) indexed in LUCENE it is not supported.
Only String,  Collection<String> are supported

**Comment by robfrank** [comment]
@vantonov1 Lucene is able to index and search TEXT. One of the first step of any Lucene's analyzer is to tokenize words, I don't think a byte[] can be tokenized in any way.

**Comment by vantonov1** [comment]
Ok. If I would collect a unique set of words from the file and index it as a String or Collection of String, in theory it could be up to tens of thousands of unique words. Is it normal to store it directly in field?

**Comment by vantonov1** [comment]
I guess, it is a kind of common scenario 

1 store some file in orient
2 Do text extraction (using tika for example)
3 Index stored file by text it contains, with stemming and all nice features Lucene provides

It would be nice if you add that scenario [here](http://orientdb.com/docs/2.2/Use-Cases.html) because you have [Lucene indexing](http://orientdb.com/docs/2.1/Full-Text-Index.html), you have [binary data support](http://orientdb.com/docs/2.1/Binary-Data.html), but it is not clear how to combine it

**Comment by robfrank** [comment]
I did it in another life, with orientDB 1.1.0... We used to store text and PDF as binary blobs inside orientdb and analyze them with NLP tools and store results to Lucene Indexes. 
Now it could be done with a single data store, OrientDb. But you can't create a Lucene index over  binary data,  you need text. Note that  you can customize analyzers:


http://orientdb.com/docs/last/Full-Text-Index.html

**Comment by vantonov1** [comment]
It would be nice to have some sort of custom adapters between record field and index. Now I need to support another field with extracted text for Lucene to index (index could be updated manually as well, but how to use it in SELECT?..)

Ok, I would try to store extracted text as String, but of course anyway NPE should be fixed

Thanks!

**Comment by maggiolo00** [comment]
Fixed
