### ISSUE TITLE
Distributed test cases random error

### ISSUE THREAD

**Issue by lvca** [orientechnologies/orientdb#6532]
In the distributed tests I see this (it happened in the last weeks):

```
2016-08-05 08:09:15:382 SEVER Cannot store state of cache for storage placed under /Users/luca/work/dev/orientechnologies/orientdb/community/distributed/target/server1/databases/db-B (error: java.io.FileNotFoundException: /Users/luca/work/dev/orientechnologies/orientdb/community/distributed/target/server1/databases/db-B/cache.stt (No such file or directory)) [O2QCache]
2016-08-05 08:09:15:398 INFO  - closing storage: db-C... [Orient]
2016-08-05 08:09:15:398 SEVER Cannot store state of cache for storage placed under /Users/luca/work/dev/orientechnologies/orientdb/community/distributed/target/server0/databases/db-C (error: java.io.FileNotFoundException: /Users/luca/work/dev/orientechnologies/orientdb/community/distributed/target/server0/databases/db-C/cache.stt (No such file or directory)) [O2QCache]
2016-08-05 08:09:15:412 INFO  - closing storage: db-B... [Orient]
2016-08-05 08:09:15:412 SEVER Cannot store state of cache for storage placed under /Users/luca/work/dev/orientechnologies/orientdb/community/distributed/target/server0/databases/db-B (error: java.io.FileNotFoundException: /Users/luca/work/dev/orientechnologies/orientdb/community/distributed/target/server0/databases/db-B/cache.stt (No such file or directory)) [O2QCache]
2016-08-05 08:09:15:426 INFO  - closing storage: db-A... [Orient]
2016-08-05 08:09:15:426 SEVER Cannot store state of cache for storage placed under /Users/luca/work/dev/orientechnologies/orientdb/community/distributed/target/server1/databases/db-A (error: java.io.FileNotFoundException: /Users/luca/work/dev/orientechnologies/orientdb/community/distributed/target/server1/databases/db-A/cache.stt (No such file or directory)) [O2QCache]
2016-08-05 08:09:15:438 INFO  - closing storage: db-A... [Orient]
2016-08-05 08:09:15:439 SEVER Cannot store state of cache for storage placed under /Users/luca/work/dev/orientechnologies/orientdb/community/distributed/target/server0/databases/db-A (error: java.io.FileNotFoundException: /Users/luca/work/dev/orientechnologies/orientdb/community/distributed/target/server0/databases/db-A/cache.stt (No such file or directory)) [O2QCache]-- error on closing storage
com.orientechnologies.orient.core.exception.OWriteCacheException: File flush was abnormally terminated
    at com.orientechnologies.orient.core.storage.cache.local.OWOWCache.flush(OWOWCache.java:696)
    at com.orientechnologies.orient.core.storage.cache.local.OWOWCache.flush(OWOWCache.java:707)
    at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.makeFullCheckpoint(OAbstractPaginatedStorage.java:2869)
    at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.doClose(OAbstractPaginatedStorage.java:3517)
    at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.close(OAbstractPaginatedStorage.java:459)
    at com.orientechnologies.orient.core.Orient.closeAllStorages(Orient.java:385)
    at com.orientechnologies.orient.server.distributed.AbstractServerClusterTest.init(AbstractServerClusterTest.java:102)
    at com.orientechnologies.orient.server.distributed.scenariotest.ThreeClientsRecordDeleteWithTransactionsOnMultipleServersScenarioTest.test(ThreeClientsRecordDeleteWithTransactionsOnMultipleServersScenarioTest.java:59)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
    at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
    at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
    at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
    at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
    at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
    at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
    at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
    at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
    at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
    at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
    at org.junit.runners.Suite.runChild(Suite.java:128)
    at org.junit.runners.Suite.runChild(Suite.java:27)
    at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
    at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
    at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
    at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
    at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
    at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
    at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
    at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:119)
    at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:42)
    at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:234)
    at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:74)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
Caused by: java.util.concurrent.ExecutionException: com.orientechnologies.common.io.OIOException: File /Users/luca/work/dev/orientechnologies/orientdb/community/distributed/target/server0/databases/db-A/osequence.cpm was not found
    at java.util.concurrent.FutureTask.report(FutureTask.java:122)
    at java.util.concurrent.FutureTask.get(FutureTask.java:192)
    at com.orientechnologies.orient.core.storage.cache.local.OWOWCache.flush(OWOWCache.java:691)
    ... 42 more
Caused by: com.orientechnologies.common.io.OIOException: File /Users/luca/work/dev/orientechnologies/orientdb/community/distributed/target/server0/databases/db-A/osequence.cpm was not found
    at com.orientechnologies.orient.core.storage.fs.OFileClassic.open(OFileClassic.java:603)
    at com.orientechnologies.common.collection.closabledictionary.OClosableEntry.makeAcquiredFromClosed(OClosableEntry.java:98)
    at com.orientechnologies.common.collection.closabledictionary.OClosableLinkedContainer.acquire(OClosableLinkedContainer.java:272)
    at com.orientechnologies.orient.core.storage.cache.local.OWOWCache$FileFlushTask.call(OWOWCache.java:1833)
    at com.orientechnologies.orient.core.storage.cache.local.OWOWCache$FileFlushTask.call(OWOWCache.java:1818)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
```

**Comment by laa** [comment]
It was fixed by @taburet several days ago.
