### ISSUE TITLE
Distributed delta-sync random errors

### ISSUE THREAD

**Issue by lvca** [orientechnologies/orientdb#6533]
I see this randomly, like 1 every 20 runs:

```
2016-08-05 01:32:36:474 INFO  [europe1] Database copied correctly, size=18.52MB [ODistributedAbstractPlugin$3][europe1]<-[europe0] Error on installing database delta 'platform' on local server
com.orientechnologies.orient.core.exception.ODatabaseException: RecordId cannot support cluster id major than 32767. Found: 761673315
    DB name="platform"
    at com.orientechnologies.orient.core.id.ORecordId.checkClusterLimits(ORecordId.java:338)
    at com.orientechnologies.orient.core.id.ORecordId.<init>(ORecordId.java:50)
    at com.orientechnologies.orient.server.distributed.impl.OIncrementalServerSync$1.call(OIncrementalServerSync.java:108)
    at com.orientechnologies.orient.core.db.OScenarioThreadLocal.executeAsDistributed(OScenarioThreadLocal.java:70)
    at com.orientechnologies.orient.server.distributed.impl.OIncrementalServerSync.importDelta(OIncrementalServerSync.java:78)
    at com.orientechnologies.orient.server.distributed.impl.ODistributedAbstractPlugin$7.call(ODistributedAbstractPlugin.java:1784)
    at com.orientechnologies.orient.server.distributed.impl.ODistributedAbstractPlugin$7.call(ODistributedAbstractPlugin.java:1778)
    at com.orientechnologies.orient.server.distributed.impl.ODistributedAbstractPlugin.executeInDistributedDatabaseLock(ODistributedAbstractPlugin.java:1517)
    at com.orientechnologies.orient.server.distributed.impl.ODistributedAbstractPlugin.installDatabaseOnLocalNode(ODistributedAbstractPlugin.java:1778)
    at com.orientechnologies.orient.server.distributed.impl.ODistributedAbstractPlugin.installDatabaseFromNetwork(ODistributedAbstractPlugin.java:1367)
    at com.orientechnologies.orient.server.distributed.impl.ODistributedAbstractPlugin.requestDatabaseDelta(ODistributedAbstractPlugin.java:1065)
    at com.orientechnologies.orient.server.distributed.impl.ODistributedAbstractPlugin.installDatabase(ODistributedAbstractPlugin.java:958)
    at com.orientechnologies.orient.server.hazelcast.OHazelcastPlugin.installNewDatabasesFromCluster(OHazelcastPlugin.java:863)
    at com.orientechnologies.orient.server.hazelcast.OHazelcastPlugin.startup(OHazelcastPlugin.java:172)
    at com.orientechnologies.orient.server.OServer.registerPlugins(OServer.java:1207)
    at com.orientechnologies.orient.server.OServer.activate(OServer.java:390)
    at test.OrientDBCluster.execute(OrientDBCluster.java:67)
    at test.OrientDBCluster.main(OrientDBCluster.java:178)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
```

**Comment by laa** [comment]
@lvca do you still have those ones ?

**Comment by lvca** [comment]
Not anymore.
