### ISSUE TITLE
NPE in ODatabaseDocumentTx.open() after index  being restored

### ISSUE THREAD

**Issue by vantonov1** [orientechnologies/orientdb#6542]
v 2.2.3

DB was stopped during tests, all indexes restored successfully, but during open it throws NPE

Problem is, that OAbstractPaginatedStorage.indexEngines array was changed, and OIndexOneValue.indexId field is invalid

Index instance was returned from OIndexManagerShared.classPropertyIndex, it seems not to be updated during db restore

 Error on using index OUser.name in query 'select from OUser where name = ? limit 1'. Probably you need to rebuild indexes. Now executing query using cluster scan
java.lang.NullPointerException
    at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.doGetIndexValue(OAbstractPaginatedStorage.java:1820)
    at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.getIndexValue(OAbstractPaginatedStorage.java:1809)
    at com.orientechnologies.orient.core.index.OIndexOneValue.get(OIndexOneValue.java:55)
    at com.orientechnologies.orient.core.index.OIndexOneValue.get(OIndexOneValue.java:39)
    at com.orientechnologies.orient.core.index.OIndexAbstractDelegate.get(OIndexAbstractDelegate.java:59)
    at com.orientechnologies.orient.core.index.OIndexTxAwareOneValue.get(OIndexTxAwareOneValue.java:261)
    at com.orientechnologies.orient.core.index.OIndexTxAwareOneValue.get(OIndexTxAwareOneValue.java:41)
    at com.orientechnologies.orient.core.sql.operator.OQueryOperatorEquals.executeIndexQuery(OQueryOperatorEquals.java:156)
    at com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.searchForIndexes(OCommandExecutorSQLSelect.java:2213)
    at com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.searchInClasses(OCommandExecutorSQLSelect.java:994)
    at com.orientechnologies.orient.core.sql.OCommandExecutorSQLResultsetAbstract.assignTarget(OCommandExecutorSQLResultsetAbstract.java:202)
    at com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.assignTarget(OCommandExecutorSQLSelect.java:515)
    at com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.executeSearch(OCommandExecutorSQLSelect.java:497)
    at com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.execute(OCommandExecutorSQLSelect.java:473)
    at com.orientechnologies.orient.core.sql.OCommandExecutorSQLDelegate.execute(OCommandExecutorSQLDelegate.java:72)
    at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.executeCommand(OAbstractPaginatedStorage.java:2577)
    at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.command(OAbstractPaginatedStorage.java:2523)
    at com.orientechnologies.orient.core.sql.query.OSQLQuery.run(OSQLQuery.java:78)
    at com.orientechnologies.orient.core.sql.query.OSQLAsynchQuery.run(OSQLAsynchQuery.java:74)
    at com.orientechnologies.orient.core.sql.query.OSQLSynchQuery.run(OSQLSynchQuery.java:85)
    at com.orientechnologies.orient.core.query.OQueryAbstract.execute(OQueryAbstract.java:33)
    at com.orientechnologies.orient.core.metadata.security.OSecurityShared.getUser(OSecurityShared.java:608)
    at com.orientechnologies.orient.core.metadata.security.OSecurityExternal.getUser(OSecurityExternal.java:94)
    at com.orientechnologies.orient.core.metadata.security.OSecurityShared.authenticate(OSecurityShared.java:235)
    at com.orientechnologies.orient.core.metadata.security.OSecurityExternal.authenticate(OSecurityExternal.java:62)
    at com.orientechnologies.orient.core.metadata.security.OSecurityProxy.authenticate(OSecurityProxy.java:107)
    at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.open(ODatabaseDocumentTx.java:249)

**Comment by laa** [comment]
@vantonov1 is it possible to got this db ?

**Comment by vantonov1** [comment]
During restart all indexes were rebuilt, so I dont think you'll see anything interested

IMHO problem is not broken a index, but outdated list of index instances in memory - some indexes were removed and added in OAbstractPaginatedStorage.addIndexEngine(), but OIndexManagerShared.classPropertyIndex still hold old instances with wrong indexId

**Comment by vantonov1** [comment]
BTW, the whole idea to get index by its position in non-constant array is strange for me. Why not to get index ny name, are you trying to avoid one HashMap lookup?

**Comment by laa** [comment]
@vantonov1 exactly

**Comment by vantonov1** [comment]
Hmm... a wrote - 

"During restart all indexes were rebuilt, so I dont think you'll see anything interested"

**Comment by laa** [comment]
ah I see sorry )) so we should rely only on stack trace, let me see what I can do there

**Comment by laa** [comment]
@vantonov1 I did not get it sorry. So when you open database it started to rebuild itself, and then when the request is issued you have got this exception.  But if you open database from other JVM you do not have this exception is it correct ?

**Comment by vantonov1** [comment]
No. Problem is, that at start system reads index info into OAbstractPaginatedStorage.indexEngines, and has references to items in that array by index (OIndexOneValue.indexId). When index files restored, info in indexEngines changed (I guess items are removed and when added again), so OIndexOneValue.indexId points to a wrong item.

If you restart db again, it reads correct info (index were restored), so everything works

**Comment by laa** [comment]
@vantonov1 fixed, now if the index contains the invalid id of index engine it will be automatically reloaded.
