### ISSUE TITLE
Lucene indexes raise an exception after database backup

### ISSUE THREAD

**Issue by antonzherdev** [orientechnologies/orientdb#6544]
## OrientDB Version, operating system, or hardware.
- v2.0 SNAPSHOT[ ] - .18[ ] .17[ ] .16[ ] .15[ ] .14[ ] .13[ ] .12[ ] .11[ ] .10[ ] .9[ ] .8[ ] .7[ ] .6[ ] .5[ ] .4[ ] .3[ ] .2[ ] .1[ ] .0[ ]
- v2.1 SNAPSHOT[ ] - .16[ ] .15[ ] .14[ ] .13[ ] .12[ ] .11[ ] .10[ ] .9[ ] .8[ ] .7[ ] .6[ ] .5[ ] .4[ ] .3[ ] .2[ ] .1[ ] .0[ ]
- v2.2 SNAPSHOT[ ] - .6[X] .rc1[ ] .beta2[ ] .beta1[ ]

## Operating System
- [X] Linux
- [X] MacOSX
- [ ] Windows
- [ ] Other Unix
- [ ] Other, name? 

## Expected behavior and actual behavior
```
java.lang.IllegalArgumentException: targetGen=642 was never returned by the ReferenceManager instance (current gen=27)
        at org.apache.lucene.search.ControlledRealTimeReopenThread.waitForGeneration(ControlledRealTimeReopenThread.java:160)
        at org.apache.lucene.search.ControlledRealTimeReopenThread.waitForGeneration(ControlledRealTimeReopenThread.java:135)
        at com.orientechnologies.lucene.engine.OLuceneIndexEngineAbstract.searcher(OLuceneIndexEngineAbstract.java:432)
        at com.orientechnologies.lucene.engine.OLuceneFullTextIndexEngine.getResults(OLuceneFullTextIndexEngine.java:214)
        at com.orientechnologies.lucene.engine.OLuceneFullTextIndexEngine.getInTx(OLuceneFullTextIndexEngine.java:281)
        at com.orientechnologies.lucene.engine.OLuceneFullTextIndexEngine.get(OLuceneFullTextIndexEngine.java:112)
        at com.orientechnologies.lucene.engine.OLuceneIndexEngineDelegate.get(OLuceneIndexEngineDelegate.java:122)
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.doGetIndexValue(OAbstractPaginatedStorage.java:1913)
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.getIndexValue(OAbstractPaginatedStorage.java:1902)
        at com.orientechnologies.lucene.index.OLuceneIndexNotUnique.get(OLuceneIndexNotUnique.java:213)
        at com.orientechnologies.lucene.index.OLuceneIndexNotUnique.get(OLuceneIndexNotUnique.java:45)
```
## Steps to reproduce the problem
1. Modify content of Lucene index 
2. Make backup of the database 
3. Try to use the index (get data or modify)

**Comment by maggiolo00** [comment]
How did you backup the databases?

**Comment by antonzherdev** [comment]
@maggiolo00 I do not think that It's not related to the problem, but I'm using OAutomaticBackup and I create index with:
```
val itp = OClass.INDEX_TYPE.FULLTEXT.toString
val factory: OIndexFactory = OIndexes.getFactory(itp, null)
db.getMetadata.getIndexManager.createIndex(searchIndexName(workspaceId, dslType), itp,
new OSimpleKeyIndexDefinition(factory.getLastVersion, OType.STRING), null, null, null, OLuceneIndexFactory.LUCENE_ALGORITHM)
```

I will make pull request with the fix in couple of minutes when tests will pass. 

In fact the problem is very simple: backup is calling OLuceneIndexEngineAbstract.reOpen, it's recreating TrackingIndexWriter but do not flush reopenToken.

**Comment by maggiolo00** [comment]
@antonzherdev 

Fixed By PR
Thanks
