### ISSUE TITLE
Error after execute teleporter to migrate a mysql database to orientdb

### ISSUE THREAD

**Issue by TrainYourBrain** [orientechnologies/orientdb#6557]
## OrientDB Version, operating system, or hardware.
- v2.2.7 Enterprise

## Operating System
- [ ] Linux
- [ ] MacOSX
- [x ] Windows 10
- [ ] Other Unix
- [ ] Other, name? 

## Expected behavior and actual behavior

 ______________________________________________________________________________
 ___  __/__  ____/__  /___  ____/__  __ \_  __ \__  __\__  __/__  ____/__  _ _ \
 __  /  __  __/  __  / __  __/  __  /_/ /  / / /_  /_/ /_  /  __  __/  __  /_/ /
 _  /   _  /___  _  /___  /___  _  ____// /_/ /_  _, _/_  /   _  /___  _  _, _/
 /_/    /_____/  /_____/_____/  /_/     \____/ /_/ |_| /_/    /_____/  /_/ |_|

                                                  http://orientdb.com/teleporter

ERROR:
java.lang.NullPointerException
ERROR:
java.lang.NullPointerException
        at com.orientechnologies.teleporter.util.ODriverConfigurator.isDriverAlreadyPresent(ODriverConfigurator.java:175)
        at com.orientechnologies.teleporter.util.ODriverConfigurator.checkConfiguration(ODriverConfigurator.java:124)
        at com.orientechnologies.teleporter.main.OTeleporter.execute(OTeleporter.java:256)
        at com.orientechnologies.teleporter.main.OTeleporter.main(OTeleporter.java:206)

Exception in thread "main" com.orientechnologies.teleporter.exception.OTeleporterRuntimeException: java.lang.NullPointerException
        at com.orientechnologies.teleporter.util.ODriverConfigurator.checkConfiguration(ODriverConfigurator.java:158)
        at com.orientechnologies.teleporter.main.OTeleporter.execute(OTeleporter.java:256)
        at com.orientechnologies.teleporter.main.OTeleporter.main(OTeleporter.java:206)
Caused by: java.lang.NullPointerException
        at com.orientechnologies.teleporter.util.ODriverConfigurator.isDriverAlreadyPresent(ODriverConfigurator.java:175)
        at com.orientechnologies.teleporter.util.ODriverConfigurator.checkConfiguration(ODriverConfigurator.java:124)
        ... 2 more

## Steps to reproduce the problem

I use follow command and get the error:

C:\tmp\orientdb-enterprise-2.2.7\bin\oteleporter.bat -jdriver mysql -jurl jdbc:mysql://localhost:5599/testdb -juser admin -jpasswd mypassword -ourl plocal:C:/tmp/orientdb-enterprise-2.2.7/databases/testdb -s naive -nr java -v 2

**Comment by G4br13l3** [comment]
Hi @TrainYourBrain, can you try running the script in the ORIENTDB_HOME\bin directory?
So you should run in C:\tmp\orientdb-enterprise-2.2.7\bin\ the same command:

oteleporter.bat -jdriver mysql -jurl jdbc:mysql://localhost:5599/testdb -juser admin -jpasswd mypassword -ourl plocal:C:/tmp/orientdb-enterprise-2.2.7/databases/testdb -s naive -nr java -v 2

Let me know if it works, thanks.

**Comment by G4br13l3** [comment]
I'm closing this, please feel free to reopen it if you have further issues, thanks.

**Comment by TrainYourBrain** [comment]
Hello G4br13l3 ,

great note . That was the solution with ORIENTDB_HOME\bin directory.

Thanks
