### ISSUE TITLE
Incorrect Lucene engine shutdown

### ISSUE THREAD

**Issue by taburet** [orientechnologies/orientdb#6561]
Lucene engine cannot be shutdown from the shutdown hook because of:

```
com.orientechnologies.orient.core.exception.ODatabaseException: The database instance is not set in the current thread. Be sure to set it with: ODatabaseRecordThreadLocal.INSTANCE.set(db);
	at com.orientechnologies.orient.core.db.ODatabaseRecordThreadLocal.get(ODatabaseRecordThreadLocal.java:51)
	at com.orientechnologies.lucene.engine.OLuceneIndexEngineAbstract.getDatabase(OLuceneIndexEngineAbstract.java:312)
	at com.orientechnologies.lucene.engine.OLuceneFacetManager.delete(OLuceneFacetManager.java:107)
	at com.orientechnologies.lucene.engine.OLuceneFullTextIndexEngine.delete(OLuceneFullTextIndexEngine.java:80)
	at com.orientechnologies.lucene.engine.OLuceneIndexEngineDelegate.delete(OLuceneIndexEngineDelegate.java:81)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.doClose(OAbstractPaginatedStorage.java:3568)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.close(OAbstractPaginatedStorage.java:535)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.delete(OAbstractPaginatedStorage.java:543)
	at com.orientechnologies.orient.core.storage.impl.memory.ODirectMemoryStorage.shutdown(ODirectMemoryStorage.java:130)
```

`TestVertexIndex` test updated to workaround this.

**Comment by maggiolo00** [comment]
@taburet 

in develop or 2.2.x?

I did run from Idea this test `TestVertexIndex`
with  `graph.shutdown()` without this exception

**Comment by taburet** [comment]
In 2.2.x. `graph.shutdown()` doesn't close the storage actually. The storage closed later from the shutdown hook and throws the mentioned exception which is inhibited and written to the error log, but due to some logging misconfiguration in Lucene module (?) it's not visible in the log. Just place a breakpoint in `OLuceneFacetManager.delete`, don't forget to comment out the `closeAllStorages` workaround call in `deInit`.

**Comment by taburet** [comment]
Seem like the logging problem is not specific to Lucene module only, maybe logging subsystem is shutdown early than ODB shutdown hook is called or something like that.

**Comment by maggiolo00** [comment]
Could be

**Comment by taburet** [comment]
BTW, `graph.shutdown()` unsets the `ODatabaseRecordThreadLocal`, so even if your later perform the storage shutdown from the user thread, not the one associated with the JVM shutdown hook's, using the `Orient.instance().shutdown`, for example, it will fail.
