### ISSUE TITLE
ETL: csv extractor throws exception when trying to use predefinedFormat: Default

### ISSUE THREAD

**Issue by william76** [orientechnologies/orientdb#6573]
## OrientDB Version, operating system, or hardware.
- [X] v2.2.7

## Operating System
- [ ] Linux
- [X] MacOSX (El Capitan)
- [ ] Windows
- [ ] Other Unix
- [ ] Other, name? 

## Expected behavior and actual behavior

Per [http://orientdb.com/docs/2.2.x/Extractor.html](http://orientdb.com/docs/2.2.x/Extractor.html), I have a CSV file that I'm trying to import and I set the "predefinedFormat" value to "DEFAULT" and I get the following output:

```
OrientDB etl v.2.2.7 (build 2.2.x@rdcab5af4dce4b538bdb4b372abba46e3fc9f19b7; 2016-08-11 15:17:33+0000) www.orientdb.com
Exception in thread "main" com.orientechnologies.orient.core.exception.OConfigurationException: Error on creating ETL processor
	at com.orientechnologies.orient.etl.OETLProcessor.parse(OETLProcessor.java:225)
	at com.orientechnologies.orient.etl.OETLProcessor.parse(OETLProcessor.java:176)
	at com.orientechnologies.orient.etl.OETLProcessor.parseConfigAndParameters(OETLProcessor.java:144)
	at com.orientechnologies.orient.etl.OETLProcessor.main(OETLProcessor.java:108)
Caused by: java.lang.IllegalArgumentException: No enum constant com.orientechnologies.apache.commons.csv.CSVFormat.Predefined.DEFAULT
	at java.lang.Enum.valueOf(Enum.java:238)
	at com.orientechnologies.apache.commons.csv.CSVFormat$Predefined.valueOf(CSVFormat.java:155)
	at com.orientechnologies.apache.commons.csv.CSVFormat.valueOf(CSVFormat.java:376)
	at com.orientechnologies.orient.etl.extractor.OCSVExtractor.configure(OCSVExtractor.java:77)
	at com.orientechnologies.orient.etl.OETLProcessor.configureComponent(OETLProcessor.java:449)
	at com.orientechnologies.orient.etl.OETLProcessor.configureExtractors(OETLProcessor.java:273)
	at com.orientechnologies.orient.etl.OETLProcessor.parse(OETLProcessor.java:207)
	... 3 more
```

## Steps to reproduce the problem
I have a .json extractor with the following code in it:

```
    "extractor": { "csv": { "predefinedFormat": "DEFAULT",
                            "ignoreEmptyLines": true,
                            "nullValue": "N/A",
                            "dateFormat": "yyyy-mm-dd",
                            "columns": ["label:string","data:float","Date:date"]
                          }
                 },
```

**Comment by robfrank** [comment]
I was able to reproduce the bug. We are going to release 2.2.10 in a few days. In the meanwhile, if you don't need a specific csv parsing format, simply get rid of ```
"predefinedFormat": "DEFAULT",
```

**Comment by robfrank** [comment]
I've pushed the fix:

https://github.com/orientechnologies/orientdb/commit/7fe62b30d1ec4ae2d6c99ba9262216092f41bba0


And fixed the docs:
http://orientdb.com/docs/2.2.x/Extractor.html

We will release 2.2.10 asap
