### ISSUE TITLE
NPE with parallel execution on the same record.

### ISSUE THREAD

**Issue by PhantomYdn** [orientechnologies/orientdb#6596]
## OrientDB Version, operating system, or hardware.
- v2.1 SNAPSHOT: 2.1.19-2.1.21 - versions more earlier were not tested
## Operating System
- [X] Linux - but it shouldn't matter

## Expected behavior and actual behavior

Sometimes with parallel execution on the same record it's possible to catch something like this:

```java
 java.lang.NullPointerException
	at com.orientechnologies.orient.core.record.impl.ODocumentHelper.getIdentifiableValue(ODocumentHelper.java:743)
	at com.orientechnologies.orient.core.record.impl.ODocumentHelper.getFieldValue(ODocumentHelper.java:511)
	at com.orientechnologies.orient.core.record.impl.ODocumentHelper.getFieldValue(ODocumentHelper.java:215)
	at com.orientechnologies.orient.core.record.impl.ODocument.rawField(ODocument.java:772)
	at com.orientechnologies.orient.core.record.impl.ODocument.field(ODocument.java:783)
```

## Steps to reproduce the problem
There is no specific reproduceble usecase. Hope that existing stacktrace will help to figure out how to fix. I mean check for null not only identifiable, but also a record themselves.

**Comment by lvca** [comment]
ODocument is not thread-safe, so you should never access to it from multiple threads.

**Comment by PhantomYdn** [comment]
Access is not through ODocument, but through ORecordId. So both threads storing just a reference - not document themselves.

**Comment by lvca** [comment]
Could you post the line of code that caused this?
