### ISSUE TITLE
Database instance is not set in current thread.

### ISSUE THREAD

**Issue by kerner1000** [orientechnologies/orientdb#6619]
## Version and Operating System
2.1.16, Linux

## Expected behavior and actual behavior

It seems like the db instance is set in the JavaFX thread (see stacktrace, javafx.application.PlatformImpl..), but exception is thrown anyway.

```
DEBUG controller.DatabaseControllerOrientDB.initOnDB (DatabaseControllerOrientDB.java:244) New connection acquired (now 1 open, thread: JavaFX Application Thread)
Exception in thread "JavaFX Application Thread" com.orientechnologies.orient.core.exception.ODatabaseException: Database instance is not set in current thread. Assure to set it with: ODatabaseRecordThreadLocal.INSTANCE.set(db);
	at com.orientechnologies.orient.core.db.ODatabaseRecordThreadLocal.get(ODatabaseRecordThreadLocal.java:51)
	at com.orientechnologies.orient.core.record.ORecordAbstract.getDatabase(ORecordAbstract.java:240)
	at com.orientechnologies.orient.core.record.impl.ODocument.save(ODocument.java:1768)
	at com.orientechnologies.orient.core.record.impl.ODocument.save(ODocument.java:1759)
	at net.openchrom.chromatogram.xxd.identifier.supplier.xident.database.document.Documents.setBoolean(Documents.java:102)
	at net.openchrom.chromatogram.xxd.identifier.supplier.xident.database.document.LibraryPeakDocuments.setActive(LibraryPeakDocuments.java:96)
	at net.openchrom.chromatogram.xxd.identifier.supplier.xident.beans.DAOLibraryPeak.lambda$1(DAOLibraryPeak.java:24)
	at com.sun.javafx.application.PlatformImpl.lambda$null$173(PlatformImpl.java:295)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$174(PlatformImpl.java:294)
```

Are there any other reasons why `Orient.instance().getDatabaseThreadFactory()` could be `null`?

**Comment by kerner1000** [comment]
After some debugging, I assume it is necessary that `ODatabasePool` and  `ODatabase` need to be created in the same thread.
Is this correct?

**Comment by lvca** [comment]
The instance retrieved form the pool cannot be used in another thread. Retrieve rather the instance on the thread you need it.

**Comment by kerner1000** [comment]
Thanks @lvca for this info!

I think it would be very good to do some documentation on these threadding things, they have caused me some headaches ;)

I have refactored everything from handing `ODocument` instances around to `ÒDatabase` instances to `ODatabasePool` instances  to handing around only the DB URL string.... which finally seems to work..

**Comment by lvca** [comment]
I've just improved the docs for further users: http://orientdb.com/docs/2.2/Java-Multi-Threading.html#working-with-databases
