### ISSUE TITLE
Cluster Strategy inexplicably changes to round-robin in distributed setup

### ISSUE THREAD

**Issue by bwRavencl** [orientechnologies/orientdb#6636]
## OrientDB Version, operating system, or hardware.
- v2.0 SNAPSHOT[ ] - .18[ ] .17[ ] .16[ ] .15[ ] .14[ ] .13[ ] .12[ ] .11[ ] .10[ ] .9[ ] .8[ ] .7[ ] .6[ ] .5[ ] .4[ ] .3[ ] .2[ ] .1[ ] .0[ ]
- v2.1 SNAPSHOT[ ] - .16[ ] .15[ ] .14[ ] .13[ ] .12[ ] .11[ ] .10[ ] .9[ ] .8[ ] .7[ ] .6[ ] .5[ ] .4[ ] .3[ ] .2[ ] .1[ ] .0[ ]
- v2.2 SNAPSHOT[x] - .rc1[ ] .beta2[ ] .beta1[ ]
- v3.0 SNAPSHOT[x]

## Operating System
- [ ] Linux
- [x] MacOSX
- [ ] Windows
- [ ] Other Unix
- [ ] Other, name? 

## Expected behavior and actual behavior
This issue concerns 2.2 and 3.0-SNAPSHOT in distributed + embedded mode with transactions enabled:

After adding multiple vertices of a previously added vertex type, the cluster selection strategy inexplicably changes from `OLocalClusterStrategy` to `ORoundRobinClusterSelectionStrategy`, leading to an `OSchemaException`. 
Meanwhile `OClass::setClusterSelection()` is not getting called.
## Steps to reproduce the problem
 - Launch a single embedded node, setup schema and shutdown:  

```java
final String nodeName = "devel1";
System.setProperty("ORIENTDB_NODE_NAME", nodeName);
System.setProperty("ORIENTDB_HOME", new File("").getAbsolutePath() + File.separator + nodeName);
System.setProperty("ORIENTDB_ROOT_PASSWORD", "123");
final OServer server = OServerMain.create(true);
server.startup(config);
server.activate();

final OrientGraphFactory factory = new OrientGraphFactory("plocal:" + nodeName + File.separator + "databases" + File.separator + "test");
final OrientGraphNoTx graphNoTx = factory.getNoTx();

if (graphNoTx.getVertexType("Person") == null)
	graphNoTx.createVertexType("Person", 1)

final OrientVertexType vtPerson = graphNoTx.getVertexType("Person");
 // explicitely set cluster selction strategy to 'local'
vtPerson.setClusterSelection(OLocalClusterStrategy.NAME);

if (vtPerson.getProperty("firstName") == null)
	vtPerson.createProperty("firstName", OType.STRING);

if (vtPerson.getProperty("lastName") == null)
	vtPerson.createProperty("lastName", OType.STRING);

if (vtPerson.getProperty("out_lives") == null)
	vtPerson.createEdgeProperty(Direction.OUT, "lives");

if (vtPerson.getProperty("out_history") == null)
	vtPerson.createEdgeProperty(Direction.OUT, "history");

vtPerson.setStrictMode(true);

graphNoTx.shutdown();
factory.close();
server.shutdown();
```

- Relaunch first node and add multiple vertices of class 'Person':

```java
final String nodeName = "devel1";
System.setProperty("ORIENTDB_NODE_NAME", nodeName);
System.setProperty("ORIENTDB_HOME", new File("").getAbsolutePath() + File.separator + nodeName);
System.setProperty("ORIENTDB_ROOT_PASSWORD", "123");
final OServer server = OServerMain.create(true);
server.startup(config);
server.activate();

final OrientGraphFactory factory = new OrientGraphFactory("plocal:" + nodeName + File.separator + "databases" + File.separator + "test");

while (true) {
	// press 'return' a few times and then launch second node
	System.in.read();

	final OrientGraph graph = factory.getTx();

	// should always be 'local'
	System.out.println("ClusterSelectionStrategy: " + graph.getVertexType("Person").getClusterSelection().getName());

	graph.addVertex("class:Person", "firstName", "Roger", "lastName", "Smith");
	graph.getRawGraph().commit();

	graph.shutdown();
}

factory.close();
server.shutdown();
```

- Launching the second node and also adding multiple vertices of class 'Person' triggers the described behavior:

```java
final String nodeName = "devel2";
System.setProperty("ORIENTDB_NODE_NAME", nodeName);
System.setProperty("ORIENTDB_HOME", new File("").getAbsolutePath() + File.separator + nodeName);
System.setProperty("ORIENTDB_ROOT_PASSWORD", "123");
final OServer server = OServerMain.create(true);
server.startup(config);
server.activate();

final OrientGraphFactory factory = new OrientGraphFactory("plocal:" + nodeName + File.separator + "databases" + File.separator + "test");

while (true) {
	// pressing 'return' 2 to 10 times should trigger the described behavior
	System.in.read();

	final OrientGraph graph = factory.getTx();

	// should always be 'local', but eventually changes to 'round-robin'
	System.out.println("ClusterSelectionStrategy: " + graph.getVertexType("Person").getClusterSelection().getName());

	graph.addVertex("class:Person", "firstName", "Roger", "lastName", "Smith");
	graph.getRawGraph().commit();

	graph.shutdown();
}

factory.close();
server.shutdown();
```

## Used configuration:

- orientdb-server-config.xml: 

```xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>

<orient-server>
	<handlers>
		<handler
			class="com.orientechnologies.orient.graph.handler.OGraphServerHandler">
			<parameters>
				<parameter name="enabled" value="true" />
				<parameter name="graph.pool.max" value="50" />
			</parameters>
		</handler>
		<!-- CLUSTER PLUGIN, TO TURN ON SET THE 'ENABLED' PARAMETER TO 'true' -->
		<handler
			class="com.orientechnologies.orient.server.hazelcast.OHazelcastPlugin">
			<parameters>
				<!-- <parameter name="nodeName" value="europe1" /> -->
				<parameter name="enabled" value="true" />
				<parameter name="configuration.db.default"
					value="${ORIENTDB_HOME}/config/default-distributed-db-config.json" />
				<parameter name="configuration.hazelcast" value="${ORIENTDB_HOME}/config/hazelcast.xml" />
			</parameters>
		</handler>
		<!-- JMX SERVER, TO TURN ON SET THE 'ENABLED' PARAMETER TO 'true' -->
		<handler class="com.orientechnologies.orient.server.handler.OJMXPlugin">
			<parameters>
				<parameter name="enabled" value="false" />
				<parameter name="profilerManaged" value="true" />
			</parameters>
		</handler>
		<!-- AUTOMATIC BACKUP, TO TURN ON SET THE 'ENABLED' PARAMETER TO 'true' -->
		<handler
			class="com.orientechnologies.orient.server.handler.OAutomaticBackup">
			<parameters>
				<parameter name="enabled" value="false" />
				<!-- LOCATION OF JSON CONFIGURATION FILE -->
				<parameter name="config"
					value="${ORIENTDB_HOME}/config/automatic-backup.json" />
			</parameters>
		</handler>
		<!-- SERVER SIDE SCRIPT INTERPRETER. WARNING, THIS CAN BE A SECURITY HOLE 
			BECAUSE MALICIOUS CODE COULD BE INJECTED. ENABLE IT ONLY IF CLIENTS ARE TRUSTED, 
			TO TURN ON SET THE 'ENABLED' PARAMETER TO 'true' -->
		<handler
			class="com.orientechnologies.orient.server.handler.OServerSideScriptInterpreter">
			<parameters>
				<parameter name="enabled" value="true" />
				<parameter name="allowedLanguages" value="SQL" />
			</parameters>
		</handler>

	</handlers>
	<network>
		<sockets>
			<socket
				implementation="com.orientechnologies.orient.server.network.OServerTLSSocketFactory"
				name="ssl">
				<parameters>
					<parameter value="false" name="network.ssl.clientAuth" />
					<parameter value="config/cert/orientdb.ks" name="network.ssl.keyStore" />
					<parameter value="password" name="network.ssl.keyStorePassword" />
					<parameter value="config/cert/orientdb.ks" name="network.ssl.trustStore" />
					<parameter value="password" name="network.ssl.trustStorePassword" />
				</parameters>
			</socket>
			<socket
				implementation="com.orientechnologies.orient.server.network.OServerTLSSocketFactory"
				name="https">
				<parameters>
					<parameter value="false" name="network.ssl.clientAuth" />
					<parameter value="config/cert/orientdb.ks" name="network.ssl.keyStore" />
					<parameter value="password" name="network.ssl.keyStorePassword" />
					<parameter value="config/cert/orientdb.ks" name="network.ssl.trustStore" />
					<parameter value="password" name="network.ssl.trustStorePassword" />
				</parameters>
			</socket>
		</sockets>
		<protocols>
			<!-- Default registered protocol. It reads commands using the HTTP protocol 
				and write data locally -->
			<protocol name="binary"
				implementation="com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary" />
			<protocol name="http"
				implementation="com.orientechnologies.orient.server.network.protocol.http.ONetworkProtocolHttpDb" />
		</protocols>
		<listeners>
			<listener protocol="binary" ip-address="0.0.0.0" port-range="2424-2430"
				socket="default" />
			<listener protocol="http" ip-address="0.0.0.0" port-range="2480-2490"
				socket="default">
				<parameters>
					<!-- Connection's custom parameters. If not specified the global configuration 
						will be taken -->
					<parameter name="network.http.charset" value="utf-8" />
					<parameter value="true" name="network.http.jsonResponseError" />
					<!-- Define additional HTTP headers to always send as response -->
					<!-- Allow cross-site scripting -->
					<!-- parameter name="network.http.additionalResponseHeaders" value="Access-Control-Allow-Origin: 
						*;Access-Control-Allow-Credentials: true" / -->
				</parameters>
				<commands>
					<command
						pattern="GET|www GET|studio/ GET| GET|*.htm GET|*.html GET|*.xml GET|*.jpeg GET|*.jpg GET|*.png GET|*.gif GET|*.js GET|*.css GET|*.swf GET|*.ico GET|*.txt GET|*.otf GET|*.pjs GET|*.svg GET|*.json GET|*.woff GET|*.woff2 GET|*.ttf GET|*.svgz"
						implementation="com.orientechnologies.orient.server.network.protocol.http.command.get.OServerCommandGetStaticContent">
						<parameters>
							<!-- Don't cache html resources in development mode -->
							<entry name="http.cache:*.htm *.html"
								value="Cache-Control: no-cache, no-store, max-age=0, must-revalidate\r\nPragma: no-cache" />
							<!-- Default caching -->
							<entry name="http.cache:default" value="Cache-Control: max-age=120" />
						</parameters>
					</command>
					<command pattern="GET|gephi/*"
						implementation="com.orientechnologies.orient.graph.server.command.OServerCommandGetGephi" />
				</commands>
			</listener>
		</listeners>
		<cluster>
		</cluster>
	</network>
	<storages>
	</storages>
	<users>
		<user name="root" password="123" resources="*" />
	</users>
	<properties>
		<!-- DATABASE POOL: size min/max -->
		<entry name="db.pool.min" value="1" />
		<entry name="db.pool.max" value="50" />

		<!-- PROFILER: configures the profiler as <seconds-for-snapshot>,<archive-snapshot-size>,<summary-size> -->
		<entry name="profiler.enabled" value="false" />
		<!-- <entry name="profiler.config" value="30,10,10" /> -->
	</properties>
</orient-server>
```

- default-distributed-db-config.json:

```json
{
  "autoDeploy": true,
  "hotAlignment": false,
  "readQuorum": 1,
  "writeQuorum": "majority",
  "executionMode": "undefined",
  "readYourWrites": true,
  "servers": {
    "*": "master"
  },
  "clusters": {
    "internal": {
    },
    "*": {
      "servers": ["<NEW_NODE>"]
    }
  }
}
```

**Comment by lvca** [comment]
Do you have the same problem with last 2.2.10?

**Comment by bwRavencl** [comment]
The problem still exists in 2.2.10.
Also it seems that in 2.2.x the cluster strategy is generally set to "round-robin".
Shouldn't a distributed setup always use "local"?

**Comment by lvca** [comment]
Starting from 2.2.10, there is no more specific "local" strategy, but OrientDB always installs the local as a wrapper to any strategy. So if you see round-robin, it's a local + round-robin that means the round-robin is done between the local clusters only.

In your code above, instead of printing the name, could you please print the strategy class name? it should be `OLocalClusterWrapperStrategy`.

Do you see any error on record creation because this strategy is missing?

**Comment by bwRavencl** [comment]
When printing the class name I get similar results:
Initially the strategy is  `com.orientechnologies.orient.server.distributed.impl.OLocalClusterWrapperStrategy` while adding a number of records it switches to `com.orientechnologies.orient.core.metadata.schema.clusterselection.ORoundRobinClusterSelectionStrategy`.
Which seems to provoke the above-mentioned `OSchemaException`.

**Comment by lvca** [comment]
I've added this assert in most of the distributed tests and it's never false:

```
      Assert.assertTrue(
          database.getMetadata().getSchema().getClass("Person").getClusterSelection() instanceof OLocalClusterWrapperStrategy);
```

So it has to be related with something in the way you start OrientDB embedded servers. Did you even stop any server in your tests?

**Comment by lvca** [comment]
Actually one test case fails because this new check. Checking why...

**Comment by lvca** [comment]
The test was using `remote:` but this is ok, because the strategy is installed only in the server side classes. Could you please try to dump also this information?

```java
System.out.println("ClusterSelectionStrategy for " + graph.getRawGraph().getURL() + ": " + graph.getVertexType("Person").getClusterSelection().getName());
```

**Comment by bwRavencl** [comment]
I added dumping of the requested information to my sample application, here's the output:

```
StrategyClassName: com.orientechnologies.orient.server.distributed.impl.OLocalClusterWrapperStrategy
ClusterSelectionStrategy for plocal:/Users/matteo/Projekte/secNAC/workspace-OrientDB/saOrientDB/devel1/databases/test: round-robin

ID = #25:0
 firstName = Roger
 lastName = Smith

Total: 1

devel1->add
StrategyClassName: com.orientechnologies.orient.core.metadata.schema.clusterselection.ORoundRobinClusterSelectionStrategy
ClusterSelectionStrategy for plocal:/Users/matteo/Projekte/secNAC/workspace-OrientDB/saOrientDB/devel1/databases/test: round-robin

ID = #25:0
 firstName = Roger
 lastName = Smith

ID = #25:1
 firstName = Roger
 lastName = Smith

Total: 2
```

Again the output for the strategy classname changes after creating the first record.
The 'new' dump is always `round-robin`.

Here's how the printed information is obtained:
```
System.out.println("StrategyClassName: " + graph.getVertexType("Person").getClusterSelection().getClass().getName());
System.out.println("ClusterSelectionStrategy for " + graph.getRawGraph().getURL() + ": " + graph.getVertexType("Person").getClusterSelection().getName());
```

**Comment by lvca** [comment]
Thanks for the report, I'm investigating into it.

**Comment by lvca** [comment]
Ok, reproduced. Working to fix it.

**Comment by lvca** [comment]
Fixed in 2.2.x branch. Could you please try it?

**Comment by bwRavencl** [comment]
Thanks @lvca - I will test it tomorrow and let you know how it goes.

**Comment by bwRavencl** [comment]
Your fix in 2.2.x seems to be working for me. 👍 
However, I'm running into a new issue, probably related to issues #6779 and #6765:

```
2016-10-13 10:49:30:588 INFO  Local node 'devel1' is not the owner for cluster 'person' (it is 'devel2'). Reloading distributed configuration for database 'test' 
com.orientechnologies.orient.server.distributed.ODistributedConfigurationChangedException: Local node 'devel1' is not the owner for cluster 'person' (it is 'devel2')
DB name="test" 
at com.orientechnologies.orient.server.distributed.impl.ODistributedStorage.checkForCluster(ODistributedStorage.java:1820) 
at com.orientechnologies.orient.server.distributed.impl.ODistributedTransactionManager.checkForClusterIds(ODistributedTransactionManager.java:275) 
at com.orientechnologies.orient.server.distributed.impl.ODistributedTransactionManager.commit(ODistributedTransactionManager.java:87) 
at com.orientechnologies.orient.server.distributed.impl.ODistributedStorage.commit(ODistributedStorage.java:1241) 
at com.orientechnologies.orient.core.tx.OTransactionOptimistic.doCommit(OTransactionOptimistic.java:566) 
at com.orientechnologies.orient.core.tx.OTransactionOptimistic.commit(OTransactionOptimistic.java:106) 
at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.commit(ODatabaseDocumentTx.java:2728) 
at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.commit(ODatabaseDocumentTx.java:2697) 
at com.tinkerpop.blueprints.impls.orient.OrientTransactionalGraph.commit(OrientTransactionalGraph.java:175) 
…
```

**Comment by voondo** [comment]
Same issue here with OUser with the latest 2.12-SNAPSHOT

**Comment by lvca** [comment]
@bwRavencl if you catch the generic exception `ONeedRetryException`, you can catch also `ODistributedConfigurationChangedException` and retry the operation. This case could happen only when the cluster cfg is changed during CRUD operations.

**Comment by bwRavencl** [comment]
> @bwRavencl if you catch the generic exception ONeedRetryException, you can catch also ODistributedConfigurationChangedException and retry the operation. This case could happen only when the cluster cfg is changed during CRUD operations.

Thanks @lvca  that did the trick...
