### ISSUE TITLE
HA: when database is installed, check for complete installation

### ISSUE THREAD

**Issue by lvca** [orientechnologies/orientdb#6645]
This is the error about this problem:

```
2016-09-01 13:16:16:837 INFO  [node2] Database 'GamesOfThrones' not present, waiting for it (retry=0/100)... [ODistributedWorker]
2016-09-01 13:16:17:142 INFO  [node2] Database 'GamesOfThrones' not present, waiting for it (retry=1/100)... [ODistributedWorker]
2016-09-01 13:16:17:446 INFO  [node2] Database 'GamesOfThrones' not present, waiting for it (retry=2/100)... [ODistributedWorker]
2016-09-01 13:16:17:750 INFO  [node2] Database 'GamesOfThrones' not present, waiting for it (retry=3/100)... [ODistributedWorker]
2016-09-01 13:16:18:054 INFO  [node2] Database 'GamesOfThrones' not present, waiting for it (retry=4/100)... [ODistributedWorker]
2016-09-01 13:16:18:359 INFO  [node2] Database 'GamesOfThrones' not present, waiting for it (retry=5/100)... [ODistributedWorker]
2016-09-01 13:16:18:663 INFO  [node2] Database 'GamesOfThrones' not present, waiting for it (retry=6/100)... [ODistributedWorker]
2016-09-01 13:16:18:967 INFO  [node2] Database 'GamesOfThrones' not present, waiting for it (retry=7/100)... [ODistributedWorker]
2016-09-01 13:16:19:272 INFO  [node2] Database 'GamesOfThrones' not present, waiting for it (retry=8/100)... [ODistributedWorker]
2016-09-01 13:16:19:576 INFO  [node2] Database 'GamesOfThrones' not present, waiting for it (retry=9/100)... [ODistributedWorker]
2016-09-01 13:16:19:882 INFO  [node2] Database 'GamesOfThrones' not present, waiting for it (retry=10/100)... [ODistributedWorker]
2016-09-01 13:16:19:947 INFO  [node2]<-[node3] Copying remote database 'GamesOfThrones' to: /var/folders/zc/y34429014c3bt_x1587qblth0000gn/T//orientdb/install_GamesOfThrones.zip [OHazelcastPlugin]
2016-09-01 13:16:19:948 INFO  [node2]<-[node3] Installing database 'GamesOfThrones' to: /temp/orientdb/orientdb-community-2.2.1-SNAPSHOT/node2/databases/GamesOfThrones... [OHazelcastPlugin]
2016-09-01 13:16:19:949 INFO  [node2] - writing chunk #1 offset=0 size=2.07MB [OHazelcastPlugin]
2016-09-01 13:16:19:951 WARNI [node2]<-[node3] LSN not found in database from network, database delta sync will be not available for database 'GamesOfThrones' [ODistributedAbstractPlugin$3]
2016-09-01 13:16:19:951 INFO  [node2] Database copied correctly, size=2.07MB [ODistributedAbstractPlugin$3][node2]<-[node1] Error on executing distributed request 0.38: (command_sql(create cluster `orole_0`)) worker=0
com.orientechnologies.orient.core.exception.OStorageException: Cannot open local storage '/temp/orientdb/orientdb-community-2.2.1-SNAPSHOT/node2/databases/GamesOfThrones' with mode=rw
    DB name="GamesOfThrones"
    at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.open(OAbstractPaginatedStorage.java:339)
    at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.open(ODatabaseDocumentTx.java:257)
    at com.orientechnologies.orient.server.OServer.openDatabaseBypassingSecurity(OServer.java:944)
    at com.orientechnologies.orient.server.OServer.openDatabase(OServer.java:911)
    at com.orientechnologies.orient.server.OServer.openDatabase(OServer.java:896)
    at com.orientechnologies.orient.server.distributed.impl.ODistributedDatabaseImpl.getDatabaseInstance(ODistributedDatabaseImpl.java:658)
    at com.orientechnologies.orient.server.distributed.impl.ODistributedWorker.initDatabaseInstance(ODistributedWorker.java:129)
    at com.orientechnologies.orient.server.distributed.impl.ODistributedWorker.onMessage(ODistributedWorker.java:263)
    at com.orientechnologies.orient.server.distributed.impl.ODistributedWorker.run(ODistributedWorker.java:96)
Caused by: com.orientechnologies.orient.core.exception.OStorageException: Cannot open the storage 'GamesOfThrones' because it does not exist in path: /temp/orientdb/orientdb-community-2.2.1-SNAPSHOT/node2/databases/GamesOfThrones
    DB name="GamesOfThrones"
    at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.open(OAbstractPaginatedStorage.java:279)
    ... 8 more
[node2]<-[node1] Error on executing distributed request 0.40: (command_sql(create cluster `orole_1`)) worker=0
com.orientechnologies.orient.core.exception.OStorageException: Cannot open local storage '/temp/orientdb/orientdb-community-2.2.1-SNAPSHOT/node2/databases/GamesOfThrones' with mode=rw
    DB name="GamesOfThrones"
    at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.open(OAbstractPaginatedStorage.java:339)
    at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.open(ODatabaseDocumentTx.java:257)
    at com.orientechnologies.orient.server.OServer.openDatabaseBypassingSecurity(OServer.java:944)
    at com.orientechnologies.orient.server.OServer.openDatabase(OServer.java:911)
    at com.orientechnologies.orient.server.OServer.openDatabase(OServer.java:896)
    at com.orientechnologies.orient.server.distributed.impl.ODistributedDatabaseImpl.getDatabaseInstance(ODistributedDatabaseImpl.java:658)
    at com.orientechnologies.orient.server.distributed.impl.ODistributedWorker.initDatabaseInstance(ODistributedWorker.java:129)
    at com.orientechnologies.orient.server.distributed.impl.ODistributedWorker.onMessage(ODistributedWorker.java:263)
    at com.orientechnologies.orient.server.distributed.impl.ODistributedWorker.run(ODistributedWorker.java:96)
Caused by: com.orientechnologies.orient.core.exception.OStorageException: Cannot open the storage 'GamesOfThrones' because it does not exist in path: /temp/orientdb/orientdb-community-2.2.1-SNAPSHOT/node2/databases/GamesOfThrones
    DB name="GamesOfThrones"
    at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.open(OAbstractPaginatedStorage.java:279)
    ... 8 more
[node2]<-[node1] Error on executing distributed request 0.42: (command_sql(create cluster `osequence_0`)) worker=0
com.orientechnologies.orient.core.exception.OStorageException: Cannot open local storage '/temp/orientdb/orientdb-community-2.2.1-SNAPSHOT/node2/databases/GamesOfThrones' with mode=rw
    DB name="GamesOfThrones"
    at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.open(OAbstractPaginatedStorage.java:339)
    at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.open(ODatabaseDocumentTx.java:257)
    at com.orientechnologies.orient.server.OServer.openDatabaseBypassingSecurity(OServer.java:944)
    at com.orientechnologies.orient.server.OServer.openDatabase(OServer.java:911)
    at com.orientechnologies.orient.server.OServer.openDatabase(OServer.java:896)
    at com.orientechnologies.orient.server.distributed.impl.ODistributedDatabaseImpl.getDatabaseInstance(ODistributedDatabaseImpl.java:658)
    at com.orientechnologies.orient.server.distributed.impl.ODistributedWorker.initDatabaseInstance(ODistributedWorker.java:129)
    at com.orientechnologies.orient.server.distributed.impl.ODistributedWorker.onMessage(ODistributedWorker.java:263)
    at com.orientechnologies.orient.server.distributed.impl.ODistributedWorker.run(ODistributedWorker.java:96)
Caused by: com.orientechnologies.orient.core.exception.OStorageException: Cannot open the storage 'GamesOfThrones' because it does not exist in path: /temp/orientdb/orientdb-community-2.2.1-SNAPSHOT/node2/databases/GamesOfThrones
    DB name="GamesOfThrones"
    at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.open(OAbstractPaginatedStorage.java:279)
    ... 8 more
[node2]<-[node1] Error on executing distributed request 0.44: (command_sql(create cluster `osequence_1`)) worker=0
com.orientechnologies.orient.core.exception.OStorageException: Cannot open local storage '/temp/orientdb/orientdb-community-2.2.1-SNAPSHOT/node2/databases/GamesOfThrones' with mode=rw
    DB name="GamesOfThrones"
    at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.open(OAbstractPaginatedStorage.java:339)
    at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.open(ODatabaseDocumentTx.java:257)
    at com.orientechnologies.orient.server.OServer.openDatabaseBypassingSecurity(OServer.java:944)
    at com.orientechnologies.orient.server.OServer.openDatabase(OServer.java:911)
    at com.orientechnologies.orient.server.OServer.openDatabase(OServer.java:896)
    at com.orientechnologies.orient.server.distributed.impl.ODistributedDatabaseImpl.getDatabaseInstance(ODistributedDatabaseImpl.java:658)
    at com.orientechnologies.orient.server.distributed.impl.ODistributedWorker.initDatabaseInstance(ODistributedWorker.java:129)
    at com.orientechnologies.orient.server.distributed.impl.ODistributedWorker.onMessage(ODistributedWorker.java:263)
    at com.orientechnologies.orient.server.distributed.impl.ODistributedWorker.run(ODistributedWorker.java:96)
Caused by: com.orientechnologies.orient.core.exception.OStorageException: Cannot open the storage 'GamesOfThrones' because it does not exist in path: /temp/orientdb/orientdb-community-2.2.1-SNAPSHOT/node2/databases/GamesOfThrones
    DB name="GamesOfThrones"
```

**Comment by lvca** [comment]
Fixed in 2.2.15.
