### ISSUE TITLE
NoClassDefFoundError on shutdown

### ISSUE THREAD

**Issue by jamieb22** [orientechnologies/orientdb#6646]
## OrientDB Version

- v2.2.8

## Operating System
- [ ] Linux
- [x] MacOSX
- [ ] Windows
- [ ] Other Unix
- [ ] Other, name? 

## Expected behavior and actual behavior

On Tomcat 8 shutdown Orient DB outputting:

Exception in thread "Thread-109" java.lang.NoClassDefFoundError: com/orientechnologies/common/log/OLogManager$DebugLogManager
	at com.orientechnologies.common.log.OLogManager.shutdown(OLogManager.java:303)
	at com.orientechnologies.orient.core.OrientShutdownHook.run(OrientShutdownHook.java:37)
Caused by: java.lang.ClassNotFoundException: com.orientechnologies.common.log.OLogManager$DebugLogManager
	at org.apache.catalina.loader.WebappClassLoader.loadClass(WebappClassLoader.java:1720)
	at org.apache.catalina.loader.WebappClassLoader.loadClass(WebappClassLoader.java:1571)
	... 2 more

Expecting a clean shutdown with no errors.

**Comment by taburet** [comment]
Fixed on 2.2.x and develop.
