### ISSUE TITLE
Not work with Alpine container

### ISSUE THREAD

**Issue by RodrigoLimasss** [orientechnologies/orientdb#6678]
## OrientDB Version, operating system, or hardware.
- v2.2.9, RedHat host, docker Alpine:3.3.

## Operating System
- [X] Linux
- [ ] MacOSX
- [ ] Windows
- [ ] Other Unix
- [ ] Other, name? 

## Expected behavior and actual behavior

Hi guys, I got these error only under an Alpine container. I just changed for ubuntu 14.04 and also in windows, it's worked fine!!!

java.lang.NoClassDefFoundError: Could not initialize class com.orientechnologies.orient.core.db.ODatabaseRecordThreadLocal
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.activateOnCurrentThread(ODatabaseDocumentTx.java:3026)
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.<init>(ODatabaseDocumentTx.java:160)
        at com.orientechnologies.orient.core.db.OPartitionedDatabasePool$DatabaseDocumentTxPooled.<init>(OPartitionedDatabasePool.java:423)
        at com.orientechnologies.orient.core.db.OPartitionedDatabasePool$DatabaseDocumentTxPooled.<init>(OPartitionedDatabasePool.java:419)
        at com.orientechnologies.orient.core.db.OPartitionedDatabasePool.initQueue(OPartitionedDatabasePool.java:355)
        at com.orientechnologies.orient.core.db.OPartitionedDatabasePool.<init>(OPartitionedDatabasePool.java:116)
        at com.tinkerpop.blueprints.impls.orient.OrientGraphFactory.<init>(OrientGraphFactory.java:71)
        at com.tinkerpop.blueprints.impls.orient.OrientGraphFactory.<init>(OrientGraphFactory.java:52)

----------
        
## Steps to reproduce the problem
Using Scala 2.11.7 application, Akka 2.4.4 and 'orientdb-graphdb' v2.2.9 in docker with Alpine: 3.3 and Oracle JDK 8.

**Comment by robfrank** [comment]
sincerely I don't know why, The container should be isolated from the host... should be. I tested   on my host (mac) which uses a VM to run container inside. can you show me the docker command you use, just to be sure you are using the offical image:

https://hub.docker.com/_/orientdb/

**Comment by RodrigoLimasss** [comment]
Hi @robfrank I'm not running the Orientdb database on container, I'm running a client application that I did with Scala. This happening with 'orientdb-graphdb' v2.2.9 library.

Follow my Dockerfile attached.
[Dockerfile.txt](https://github.com/orientechnologies/orientdb/files/464749/Dockerfile.txt)

**Comment by robfrank** [comment]
I don't know what is going wrong. My suggestion is to rely on an official apline/openjdk image and add your app to it.

**Comment by mindnuts** [comment]
@RodrigoLimasss I had similar issues and i switched to this Docker image:
```sh
FROM frolvlad/alpine-oraclejdk8:full
```

Let me know if it works for you.

**Comment by robfrank** [comment]
AFAIK this problem isn't related with OrientDB itself. At lest with the scarse details provided. I close the issue.
