### ISSUE TITLE
Misleading error "user or password not valid for database" 

### ISSUE THREAD

**Issue by jamieb22** [orientechnologies/orientdb#6680]
## OrientDB Version, operating system, or hardware.
- v2.2.9

## Operating System
- [ X] Linux
- [ ] MacOSX
- [ ] Windows
- [ ] Other Unix
- [ ] Other, name? 

## Expected behavior and actual behavior

I've never changed the password to the database. After, deleting the database and starting up again... it comes up with the below error: 
2016-09-11 20:39:37 s.c.s.a.d.DatabaseService [ERROR] failed to connect to database:User or password not valid for database: 'archiva$smpl'
	DB name="archiva$smpl"
com.orientechnologies.orient.core.exception.OSecurityAccessException: User or password not valid for database: 'archiva$smpl'
	DB name="archiva$smpl"
	at com.orientechnologies.orient.core.metadata.security.OSecurityShared.authenticate(OSecurityShared.java:237)
	at com.orientechnologies.orient.core.metadata.security.OSecurityProxy.authenticate(OSecurityProxy.java:107)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.open(ODatabaseDocumentTx.java:274)
	at com.tinkerpop.blueprints.impls.orient.OrientBaseGraph.openOrCreate(OrientBaseGraph.java:1984)
	at com.tinkerpop.blueprints.impls.orient.OrientBaseGraph.<init>(OrientBaseGraph.java:162)
	at com.tinkerpop.blueprints.impls.orient.OrientTransactionalGraph.<init>(OrientTransactionalGraph.java:103)
	at com.tinkerpop.blueprints.impls.orient.OrientTransactionalGraph.<init>(OrientTransactionalGraph.java:99)
	at com.tinkerpop.blueprints.impls.orient.OrientGraph.<init>(OrientGraph.java:76)
	at com.stimulus.archiva.database.blueprints.BluePrintDatabaseUtil.mergeSameItems(BluePrintDatabaseUtil.java:149)
	at com.stimulus.archiva.database.blueprints.BluePrintDatabase.connect(BluePrintDatabase.java:84)
	at com.stimulus.archiva.database.DatabaseService.startup(DatabaseService.java:328)
	at com.stimulus.archiva.domain.Services$ServiceStartup.run(Services.java:169)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by lvca** [comment]
We cannot return the database is not existent, to avoid exposing this information to an attacker.
