### ISSUE TITLE
Distribution storage calculate average bug

### ISSUE THREAD

**Issue by syzdykov** [orientechnologies/orientdb#6685]
## OrientDB Version, operating system, or hardware.
- v2.2 SNAPSHOT[x]

## Operating System
- [x] Linux

## Expected behavior and actual behavior
Several days ago we started to use distributed storage and some of our api methods started throw exceptions. It seems distributed storage has a bug with calculation avg when there is no fields.
Here is console output:

```
> orientdb {db=mydb}> SELECT count(*) AS total FROM Review WHERE movie = #21:22
> 
> +----+-----+
> |#   |total|
> +----+-----+
> |0   |0    |
> +----+-----+
> 
> 1 item(s) found. Query executed in 0.024 sec(s).
> orientdb {db=mydb}> SELECT avg(*) AS total FROM Review WHERE movie = #21:22
> 
> Error: com.orientechnologies.orient.core.exception.OStorageException: Cannot route COMMAND operation to the distributed node
>        	DB name="mydb"
>        	DB name="mydb"
> 
> Error: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
```

Here is the stacktrace:

```
> Cannot route COMMAND operation to the distributed node
> java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
> 	at java.util.ArrayList.rangeCheck(ArrayList.java:653)
> 	at java.util.ArrayList.get(ArrayList.java:429)
> 	at com.orientechnologies.orient.core.sql.functions.math.OSQLFunctionAverage.mergeDistributedResult(OSQLFunctionAverage.java:114)
> 	at com.orientechnologies.orient.server.distributed.impl.ODistributedStorage.mergeResultByAggregation(ODistributedStorage.java:462)
> 	at com.orientechnologies.orient.server.distributed.impl.ODistributedStorage.command(ODistributedStorage.java:279)
> 	at com.orientechnologies.orient.core.sql.query.OSQLQuery.run(OSQLQuery.java:78)
> 	at com.orientechnologies.orient.core.sql.query.OSQLAsynchQuery.run(OSQLAsynchQuery.java:74)
> 	at com.orientechnologies.orient.core.sql.query.OSQLSynchQuery.run(OSQLSynchQuery.java:85)
> 	at com.orientechnologies.orient.core.query.OQueryAbstract.execute(OQueryAbstract.java:33)
> 	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.command(ONetworkProtocolBinary.java:1493)
> 	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.executeRequest(ONetworkProtocolBinary.java:581)
> 	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.sessionRequest(ONetworkProtocolBinary.java:318)
> 	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.execute(ONetworkProtocolBinary.java:194)
> 	at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:77)
```

**Comment by lvca** [comment]
Fixed.
