### ISSUE TITLE
Database import reports success when it actually failed, and has non-deterministic errors

### ISSUE THREAD

**Issue by obi1kenobi** [orientechnologies/orientdb#6687]
## OrientDB Version, operating system, or hardware.
- v2.0 SNAPSHOT[ ] - .18[ ] .17[ ] .16[ ] .15[ ] .14[ ] .13[ ] .12[ ] .11[ ] .10[ ] .9[ ] .8[ ] .7[ ] .6[ ] .5[ ] .4[ ] .3[ ] .2[ ] .1[ ] .0[ ]
- v2.1 SNAPSHOT[ ] - .16[ ] .15[ ] .14[ ] .13[ ] .12[ ] .11[ ] .10[ ] .9[ ] .8[ ] .7[ ] .6[ ] .5[ ] .4[ ] .3[ ] .2[ ] .1[ ] .0[ ]
- v2.2 SNAPSHOT[ ] - .8[x] .rc1[ ] .beta2[ ] .beta1[ ]

## Operating System
- [x] Linux
- [ ] MacOSX
- [ ] Windows
- [ ] Other Unix
- [ ] Other, name? 

## Expected behavior and actual behavior

Expected: `IMPORT DATABASE` with a valid file should always succeed. When the import process reports success, the database should have been correctly imported and contain all the imported data.

Actual: `IMPORT DATABASE` occasionally throws errors (non-deterministically) on our test workload, which always uses the same input file. However, the errors are caught and suppressed by the import process, which exits cleanly rather than propagating the error. This leaves the database in an inconsistent state, where data is *silently missing*, the absolute worst possible outcome.

## Steps to reproduce the problem

Our workload is quite complex and I am not able to share the exact data file we use in our tests. However, the error appears to be due to a race condition in the import logic, and I'm including an anonymized log, where all sensitive information has been replaced by placeholders like `<foo>` and `<bar>`. 

Note that despite the obvious errors, the log ends with `Database import completed in 24183 ms` and the console returns with exit code 0. However, on inspection, it's obvious that many classes and records that existed in the input file are missing from the database.

```
OrientDB console v.2.2.8 (build 2.2.x@r39259e190e16045fe1425b1c0485f8562fca055b; 2016-08-23 14:38:49+0000) www.orientdb.com
Type 'help' to display all the supported commands.
Installing extensions for GREMLIN language v.2.6.0

orientdb> create database remote:localhost:2424/test_db <user> <password> memory graph

Creating database [remote:localhost:2424/test_db] using the storage type [memory]...
Connecting to database [remote:localhost:2424/test_db] with user '<user>'...OK
Database created successfully.

orientdb {db=test_db}> import database /tmp/orientdb_test_5266feb7ffbb57090fd8.json.gz

Importing database database /tmp/orientdb_test_5266feb7ffbb57090fd8.json.gz...
Started import of database 'memory:test_db' from /tmp/test_dbimport4451078741195597604orientdb_test_5266feb7ffbb57090fd8.json.gz...
Non merge mode (-merge=false): removing all default non security classes
- Class E was removed.
- Class V was removed.
- Class OTriggered was removed.
- Class ORestricted was removed.
- Class OSchedule was removed.
- Class OSequence was removed.
- Class OFunction was removed.
Removed 7 classes.
Importing database info...OK
Importing clusters...
- Creating cluster 'internal'...OK, assigned id=0
- Creating cluster 'default'...OK, assigned id=3
- Creating cluster 'orole'...OK, assigned id=4
- Creating cluster 'ouser'...OK, assigned id=5
- Creating cluster 'ofunction'...OK, assigned id=6
- Creating cluster 'osequence'...OK, assigned id=7
- Creating cluster 'oschedule'...OK, assigned id=8
- Creating cluster 'v'...OK, assigned id=9
- Creating cluster 'v_1'...OK, assigned id=10
- Creating cluster 'v_2'...OK, assigned id=11
- Creating cluster 'v_3'...OK, assigned id=12
- Creating cluster 'v_4'...OK, assigned id=13
- Creating cluster 'v_5'...OK, assigned id=14
- Creating cluster 'v_6'...OK, assigned id=15
- Creating cluster 'v_7'...OK, assigned id=16
- Creating cluster 'e'...OK, assigned id=17
- Creating cluster 'e_1'...OK, assigned id=18
- Creating cluster 'e_2'...OK, assigned id=19
- Creating cluster 'e_3'...OK, assigned id=20
- Creating cluster 'e_4'...OK, assigned id=21
- Creating cluster 'e_5'...OK, assigned id=22
- Creating cluster 'e_6'...OK, assigned id=23
- Creating cluster 'e_7'...OK, assigned id=24
- Creating cluster '<foo>'...OK, assigned id=25
- Creating cluster '<foo>_1'...OK, assigned id=26
- Creating cluster '<foo>_2'...OK, assigned id=27
- Creating cluster '<foo>_3'...OK, assigned id=28
- Creating cluster '<foo>_4'...OK, assigned id=29
- Creating cluster '<foo>_5'...OK, assigned id=30
- Creating cluster '<foo>_6'...OK, assigned id=31
- Creating cluster '<foo>_7'...OK, assigned id=32
[...]
- Creating cluster '<bar>'...OK, assigned id=1737
- Creating cluster '<bar>_1'...OK, assigned id=1738
- Creating cluster '<bar>_2'...OK, assigned id=1739
- Creating cluster '<bar>_3'...OK, assigned id=1740
- Creating cluster '<bar>_4'...OK, assigned id=1741
- Creating cluster '<bar>_5'...OK, assigned id=1742
- Creating cluster '<bar>_6'...OK, assigned id=1743
- Creating cluster '<bar>_7'...OK, assigned id=1744
- Creating cluster '<baz>'...OK, assigned id=1745
- Creating cluster '<baz>_1'...OK, assigned id=1746
- Creating cluster '<baz>_2'...OK, assigned id=1747
- Creating cluster '<baz>_3'...OK, assigned id=1748
- Creating cluster '<baz>_4'...OK, assigned id=1749
- Creating cluster '<baz>_5'...OK, assigned id=1750
- Creating cluster '<baz>_6'...OK, assigned id=1751
- Creating cluster '<baz>_7'...
Started import of database 'memory:test_db' from /tmp/test_dbimport8873810688560870491orientdb_test_5266feb7ffbb57090fd8.json.gz...
Non merge mode (-merge=false): removing all default non security classes
- Class <foo> was removed.
[...]
- Class <bar> was removed.
- Class <baz> was removed.Error on database import happened just before line 0, column 0
com.orientechnologies.orient.core.exception.ORecordNotFoundException: The record with id '#128:2' was not found
	DB name="test_db"
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.readRecord(OAbstractPaginatedStorage.java:1134)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx$SimpleRecordReader.readRecord(ODatabaseDocumentTx.java:3253)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.executeReadRecord(ODatabaseDocumentTx.java:1884)
	at com.orientechnologies.orient.core.tx.OTransactionNoTx.loadRecord(OTransactionNoTx.java:115)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.load(ODatabaseDocumentTx.java:1624)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.load(ODatabaseDocumentTx.java:103)
	at com.orientechnologies.orient.core.record.impl.ODocument.field(ODocument.java:826)
	at com.orientechnologies.orient.core.index.OPropertyIndexDefinition.getDocumentValueToIndex(OPropertyIndexDefinition.java:72)
	at com.orientechnologies.orient.core.index.OCompositeIndexDefinition.getDocumentValueToIndex(OCompositeIndexDefinition.java:141)
	at com.orientechnologies.orient.core.index.OIndexAbstract.indexCluster(OIndexAbstract.java:994)
	at com.orientechnologies.orient.core.index.OIndexAbstract.fillIndex(OIndexAbstract.java:506)
	at com.orientechnologies.orient.core.index.OIndexAbstract.rebuild(OIndexAbstract.java:467)
	at com.orientechnologies.orient.core.index.OIndexAbstract.rebuild(OIndexAbstract.java:380)
	at com.orientechnologies.orient.core.index.OIndexAbstract.removeCluster(OIndexAbstract.java:709)
	at com.orientechnologies.orient.core.index.OIndexAbstract.removeCluster(OIndexAbstract.java:69)
	at com.orientechnologies.orient.core.index.OIndexManagerAbstract.removeClusterFromIndex(OIndexManagerAbstract.java:205)
	at com.orientechnologies.orient.core.index.OIndexManagerProxy.removeClusterFromIndex(OIndexManagerProxy.java:180)
	at com.orientechnologies.orient.core.metadata.schema.OClassImpl.removeClusterFromIndexes(OClassImpl.java:2685)
	at com.orientechnologies.orient.core.metadata.schema.OClassImpl.removePolymorphicClusterId(OClassImpl.java:2669)
	at com.orientechnologies.orient.core.metadata.schema.OClassImpl.removePolymorphicClusterIds(OClassImpl.java:2656)
	at com.orientechnologies.orient.core.metadata.schema.OClassImpl.removeBaseClassInternal(OClassImpl.java:1284)
	at com.orientechnologies.orient.core.metadata.schema.OSchemaShared.dropClassInternal(OSchemaShared.java:1260)
	at com.orientechnologies.orient.core.metadata.schema.OSchemaShared.dropClass(OSchemaShared.java:530)
	at com.orientechnologies.orient.core.metadata.schema.OSchemaProxy.dropClass(OSchemaProxy.java:146)
	at com.orientechnologies.orient.core.db.tool.ODatabaseImport.removeDefaultNonSecurityClasses(ODatabaseImport.java:661)
	at com.orientechnologies.orient.core.db.tool.ODatabaseImport.importDatabase(ODatabaseImport.java:396)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.importDatabase(ONetworkProtocolBinary.java:2916)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.executeRequest(ONetworkProtocolBinary.java:635)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.sessionRequest(ONetworkProtocolBinary.java:320)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.execute(ONetworkProtocolBinary.java:196)
	at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:77)
Caused by: java.lang.IllegalArgumentException: Cluster 128 is null
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.getClusterById(OAbstractPaginatedStorage.java:2474)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.readRecord(OAbstractPaginatedStorage.java:1132)
	... 30 more

Started import of database 'memory:test_db' from /tmp/test_dbimport2910385604345260478orientdb_test_5266feb7ffbb57090fd8.json.gz...
Non merge mode (-merge=false): removing all default non security classes
- Class <foo> was removed.
[...]
- Class <bar> was removed.
- Class <baz> was removed.Error on database import happened just before line 0, column 0
com.orientechnologies.orient.core.index.OIndexException: Error on rebuilding the index for clusters: [<foo>, <bar>_7, <bar>_5, <bar>_6, <bar>_3, <bar>_4, <baz>_5, <baz>_6, <baz>_3, <baz>_4, <baz>_7, <foo>_1, <foo>_2, <foo>_3, <foo>_4, <foo>_5, <foo>_6, <baz>_1, <foo>_7, <baz>_2, <bar>_1, <bar>_2]
	DB name="test_db"
	at com.orientechnologies.orient.core.index.OIndexAbstract.rebuild(OIndexAbstract.java:479)
	at com.orientechnologies.orient.core.index.OIndexAbstract.rebuild(OIndexAbstract.java:380)
	at com.orientechnologies.orient.core.index.OIndexAbstract.removeCluster(OIndexAbstract.java:709)
	at com.orientechnologies.orient.core.index.OIndexAbstract.removeCluster(OIndexAbstract.java:69)
	at com.orientechnologies.orient.core.index.OIndexManagerAbstract.removeClusterFromIndex(OIndexManagerAbstract.java:205)
	at com.orientechnologies.orient.core.index.OIndexManagerProxy.removeClusterFromIndex(OIndexManagerProxy.java:180)
	at com.orientechnologies.orient.core.metadata.schema.OClassImpl.removeClusterFromIndexes(OClassImpl.java:2685)
	at com.orientechnologies.orient.core.metadata.schema.OClassImpl.removePolymorphicClusterId(OClassImpl.java:2669)
	at com.orientechnologies.orient.core.metadata.schema.OClassImpl.removePolymorphicClusterIds(OClassImpl.java:2656)
	at com.orientechnologies.orient.core.metadata.schema.OClassImpl.removeBaseClassInternal(OClassImpl.java:1284)
	at com.orientechnologies.orient.core.metadata.schema.OSchemaShared.dropClassInternal(OSchemaShared.java:1260)
	at com.orientechnologies.orient.core.metadata.schema.OSchemaShared.dropClass(OSchemaShared.java:530)
	at com.orientechnologies.orient.core.metadata.schema.OSchemaProxy.dropClass(OSchemaProxy.java:146)
	at com.orientechnologies.orient.core.db.tool.ODatabaseImport.removeDefaultNonSecurityClasses(ODatabaseImport.java:661)
	at com.orientechnologies.orient.core.db.tool.ODatabaseImport.importDatabase(ODatabaseImport.java:396)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.importDatabase(ONetworkProtocolBinary.java:2916)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.executeRequest(ONetworkProtocolBinary.java:635)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.sessionRequest(ONetworkProtocolBinary.java:320)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.execute(ONetworkProtocolBinary.java:196)
	at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:77)
Caused by: java.lang.IllegalArgumentException: Cluster '<foo>_5' was not found
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.countClusterElements(ODatabaseDocumentTx.java:797)
	at com.orientechnologies.orient.core.index.OIndexAbstract.fillIndex(OIndexAbstract.java:499)
	at com.orientechnologies.orient.core.index.OIndexAbstract.rebuild(OIndexAbstract.java:467)
	... 19 more

Started import of database 'memory:test_db' from /tmp/test_dbimport7595174986014529205orientdb_test_5266feb7ffbb57090fd8.json.gz...
Non merge mode (-merge=false): removing all default non security classes
- Class <foo> was removed.
[...]
- Class <bar> was removed.
- Class <baz> was removed.
- Class E was removed.
- Class V was removed.
Removed 185 classes.
Rebuild of stale indexes...
Start rebuild index ouser.name
Rebuild  of index ouser.name is completed.
Start rebuild index orole.name
Rebuild  of index orole.name is completed.
Stale indexes were rebuilt...
Deleting RID Mapping table...OK

Database import completed in 24183 ms
```

**Comment by eyurtsev** [comment]
+1

**Comment by benjamincohen1** [comment]
+1

**Comment by tglman** [comment]
hi @obi1kenobi,

Do yu have a test export? it will speed up a lot the fix with it.

bye

**Comment by obi1kenobi** [comment]
I unfortunately cannot do that, because the export contains all of my company's proprietary data. Please let me know if there is any other way in which I can help debug this.

**Comment by tglman** [comment]
hi @obi1kenobi,

Ok, from the error seems that there are some trouble rebuilding the index while dropping the existing data, in anycase the index rebuild for the import case should not be needed, so i'll refactor a bit the import to drop all the index before dropping the data itself, this should solve your problem, but anyway with the source import is hard to prove the fix.

Regerds

**Comment by obi1kenobi** [comment]
I'm not sure why existing data is being dropped, as the import is into a clean (freshly-created) database.

I have managed to create an export file that deterministically causes the error. I will attempt to diff it against a good export file and report back what I find -- hopefully that will aid your search for the bug.

**Comment by tglman** [comment]
hi @obi1kenobi,

I did the refactor that i said before on the 2.2.x branch, if you have chance could you try the 2.2.11-SNAPSHOT, it should fix the problem.

It's a bit guessing though ;)

bye

**Comment by obi1kenobi** [comment]
I was able to get to the bottom of the above bug -- it is caused by OrientDB allowing two IMPORT DATABASE commands to happen simultaneously. While the two imports are in progress, they clobber each other's data and produce the unusual errors and stack traces I was seeing.

I would suggest modifying the database to only allow one IMPORT command to proceed at any one time, or at least altering the documentation to make it clear that multiple imports can cause undefined behavior.

**Comment by lvca** [comment]
Updated docs with "Import process doesn't lock the database, so any concurrent operations are allowed, but they could interfer in the import process causing errors."

**Comment by obi1kenobi** [comment]
Thanks!
