### ISSUE TITLE
High CPU usage

### ISSUE THREAD

**Issue by smil2k** [orientechnologies/orientdb#6698]
## OrientDB Version, operating system, or hardware.
- v2.2.9

## Operating System
- [x] Linux
- [ ] MacOSX
- [ ] Windows
- [ ] Other Unix
- [ ] Other, name? 

openjdk version "1.8.0_91"
OpenJDK Runtime Environment (build 1.8.0_91-8u91-b14-1~bpo8+1-b14)
OpenJDK 64-Bit Server VM (build 25.91-b14, mixed mode)

After running some hours days, a thread seems to stuck in the orient server.
Did anyone experienced this behavior?

"OrientDB (/172.20.0.8:2424) <- BinaryClient (/172.20.0.7:44358)" #242 daemon prio=5 os_prio=0 tid=0x00007fd0b8022000 nid=0xf9 runnable [0x00007fd0bfdfc000]
   java.lang.Thread.State: RUNNABLE
        at java.lang.Throwable.fillInStackTrace(Native Method)
        at java.lang.Throwable.fillInStackTrace(Throwable.java:783)
        - locked <0x00000000f0396330> (a java.net.SocketException)
        at java.lang.Throwable.<init>(Throwable.java:265)
        at java.lang.Exception.<init>(Exception.java:66)
        at java.io.IOException.<init>(IOException.java:58)
        at java.net.SocketException.<init>(SocketException.java:47)
        at java.net.SocketInputStream.read(SocketInputStream.java:154)
        at java.net.SocketInputStream.read(SocketInputStream.java:141)
        at java.io.BufferedInputStream.fill(BufferedInputStream.java:246)
        at java.io.BufferedInputStream.read(BufferedInputStream.java:265)
        - locked <0x00000000d058eb80> (a java.io.BufferedInputStream)
        at java.io.DataInputStream.readByte(DataInputStream.java:265)
        at com.orientechnologies.orient.enterprise.channel.binary.OChannelBinary.readByte(OChannelBinary.java:68)
        at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.execute(ONetworkProtocolBinary.java:187)
        at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:77)

**Comment by tglman** [comment]
hi @smil2k,

this thread is just waiting for a binary request and is blocked on the socket read, in any case of a new request arrive or the socket will be closed this thread will resume normaly, and as the status say 'RUNNABLE' means that is ready to run as soon as an event happen, from the title you said that there is a high CPU, this thread is actually stopped so should not be the cause, do you have a full stack dump ?

Regards

**Comment by smil2k** [comment]
Hi,

This thread stays there. First it take up one CPU, then another connection gets this problem, then it takes up 2 cores.

Can you please check, whether it is possible, that the binaryclient goes into an endless loop in case of an unexpected socket close?

Cheers,

Tamas

**Comment by G4br13l3** [comment]
Hi @smil2k, we will check as soon as possible!
Thanks for you report.

**Comment by tglman** [comment]
hi @smil2k,

A while ago we had some issues in the client in the 2.2 RC, that have been fixed, there is a limit on the retry in the client so it should never go in an endless loop, in any case that stack is the server side that is doing nothing, if you have problem client side can you please send us the thread dump of the client ?

Regards.

**Comment by smil2k** [comment]
I did no see it a while ago. Let's close.
