### ISSUE TITLE
Client hanging after unsuccessful vertex batch removal + NPE

### ISSUE THREAD

**Issue by lukaszkaleta** [orientechnologies/orientdb#6704]
## OrientDB Version, operating system, or hardware.
- v2.2.9

## Operating System
- [ ] Linux

## Expected behavior and actual behavior
After NPE (should not occur anyway) orient db binary client should continue working

## Steps to reproduce the problem
Error occurs during removing vertices

`com.orientechnologies.orient.enterprise.channel.binary.OResponseProcessingException: Exception during response processing
	at com.orientechnologies.orient.client.binary.OChannelBinaryAsynchClient.throwSerializedException(OChannelBinaryAsynchClient.java:444)
	at com.orientechnologies.orient.client.binary.OChannelBinaryAsynchClient.handleStatus(OChannelBinaryAsynchClient.java:379)
	at com.orientechnologies.orient.client.binary.OChannelBinaryAsynchClient.beginResponse(OChannelBinaryAsynchClient.java:261)
	at com.orientechnologies.orient.client.binary.OChannelBinaryAsynchClient.beginResponse(OChannelBinaryAsynchClient.java:153)
	at com.orientechnologies.orient.client.remote.OStorageRemote.beginResponse(OStorageRemote.java:2133)
	at com.orientechnologies.orient.client.remote.OSBTreeBonsaiRemote$2.execute(OSBTreeBonsaiRemote.java:188)
	at com.orientechnologies.orient.client.remote.OSBTreeBonsaiRemote$2.execute(OSBTreeBonsaiRemote.java:172)
	at com.orientechnologies.orient.client.remote.OStorageRemote$2.execute(OStorageRemote.java:198)
	at com.orientechnologies.orient.client.remote.OStorageRemote.baseNetworkOperation(OStorageRemote.java:230)
	at com.orientechnologies.orient.client.remote.OStorageRemote.networkOperation(OStorageRemote.java:195)
	at com.orientechnologies.orient.client.remote.OSBTreeBonsaiRemote.fetchEntriesMajor(OSBTreeBonsaiRemote.java:172)
	at com.orientechnologies.orient.client.remote.OSBTreeBonsaiRemote.loadEntriesMajor(OSBTreeBonsaiRemote.java:149)
	at com.orientechnologies.orient.core.db.record.ridbag.sbtree.OSBTreeRidBag$SBTreeMapEntryIterator.prefetchData(OSBTreeRidBag.java:465)
	at com.orientechnologies.orient.core.db.record.ridbag.sbtree.OSBTreeRidBag$SBTreeMapEntryIterator.next(OSBTreeRidBag.java:447)
	at com.orientechnologies.orient.core.db.record.ridbag.sbtree.OSBTreeRidBag$SBTreeMapEntryIterator.next(OSBTreeRidBag.java:427)
	at com.orientechnologies.orient.core.db.record.ridbag.sbtree.OSBTreeRidBag.nextChangedNotRemovedSBTreeEntry(OSBTreeRidBag.java:1068)
	at com.orientechnologies.orient.core.db.record.ridbag.sbtree.OSBTreeRidBag.access$200(OSBTreeRidBag.java:57)
	at com.orientechnologies.orient.core.db.record.ridbag.sbtree.OSBTreeRidBag$RIDBagIterator.next(OSBTreeRidBag.java:332)
	at com.orientechnologies.orient.core.db.record.ridbag.sbtree.OSBTreeRidBag$RIDBagIterator.next(OSBTreeRidBag.java:256)
	at com.tinkerpop.blueprints.impls.orient.OrientBaseGraph.removeEdges(OrientBaseGraph.java:2021)
	at com.tinkerpop.blueprints.impls.orient.OrientGraph.removeEdgesInternal(OrientGraph.java:440)
	at com.tinkerpop.blueprints.impls.orient.OrientVertex.remove(OrientVertex.java:521)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at com.picklepick.backend.pickle.PickleService.deletePickle(PickleService.java:329)
	at com.picklepick.backend.pickle.PickleEndpoint.deletePickle(PickleEndpoint.java:64)
	at sun.reflect.GeneratedMethodAccessor212.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:139)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:295)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:249)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:236)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:395)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:202)
	at org.jboss.resteasy.plugins.server.servlet.ServletContainerDispatcher.service(ServletContainerDispatcher.java:221)
	at org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:56)
	at org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:51)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:770)
	at io.undertow.servlet.handlers.ServletHandler.handleRequest(ServletHandler.java:85)
	at io.undertow.servlet.handlers.security.ServletSecurityRoleHandler.handleRequest(ServletSecurityRoleHandler.java:62)
	at io.undertow.servlet.handlers.ServletDispatchingHandler.handleRequest(ServletDispatchingHandler.java:36)
	at io.undertow.servlet.handlers.security.SSLInformationAssociationHandler.handleRequest(SSLInformationAssociationHandler.java:131)
	at io.undertow.servlet.handlers.security.ServletAuthenticationCallHandler.handleRequest(ServletAuthenticationCallHandler.java:57)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at io.undertow.security.handlers.AbstractConfidentialityHandler.handleRequest(AbstractConfidentialityHandler.java:46)
	at io.undertow.servlet.handlers.security.ServletConfidentialityConstraintHandler.handleRequest(ServletConfidentialityConstraintHandler.java:64)
	at io.undertow.security.handlers.AuthenticationMechanismsHandler.handleRequest(AuthenticationMechanismsHandler.java:60)
	at io.undertow.servlet.handlers.security.CachedAuthenticatedSessionHandler.handleRequest(CachedAuthenticatedSessionHandler.java:77)
	at io.undertow.security.handlers.AbstractSecurityContextAssociationHandler.handleRequest(AbstractSecurityContextAssociationHandler.java:43)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at io.undertow.servlet.handlers.ServletInitialHandler.handleFirstRequest(ServletInitialHandler.java:285)
	at io.undertow.servlet.handlers.ServletInitialHandler.dispatchRequest(ServletInitialHandler.java:264)
	at io.undertow.servlet.handlers.ServletInitialHandler.access$000(ServletInitialHandler.java:81)
	at io.undertow.servlet.handlers.ServletInitialHandler$1.handleRequest(ServletInitialHandler.java:175)
	at io.undertow.server.Connectors.executeRootHandler(Connectors.java:202)
	at io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:792)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
	at com.orientechnologies.orient.core.db.record.ridbag.sbtree.OSBTreeCollectionManagerAbstract$SBTreeBonsaiContainer.access$010(OSBTreeCollectionManagerAbstract.java:191)
	at com.orientechnologies.orient.core.db.record.ridbag.sbtree.OSBTreeCollectionManagerAbstract.releaseSBTree(OSBTreeCollectionManagerAbstract.java:132)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.sbTreeBonsaiGetEntriesMajor(ONetworkProtocolBinary.java:2259)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.executeRequest(ONetworkProtocolBinary.java:621)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.sessionRequest(ONetworkProtocolBinary.java:318)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.execute(ONetworkProtocolBinary.java:194)
	at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:77)
`

**Comment by G4br13l3** [comment]
Hi @lukaszkaleta, can you be more specific about the steps to reproduce this issue please?
What is your working scenario in which vertices' deleting throws this exception?
Thanks.

**Comment by lukaszkaleta** [comment]
Problem is I do not have steps. It happens from time to time. I did not be able to reproduce it by unittest. I assume that some other thread is doing on those verticies I am trying to remove.

**Comment by G4br13l3** [comment]
Ok, I've labeled it as bug. We are taking care of that.
Thanks for your report.

**Comment by taburet** [comment]
The problem was:

1. Client A connects to the server fetches a vertex, its edges are not loaded immediately but managed through lazy loading mechanism.
2. Client B also fetches the vertex.
3. Client A deletes the vertex and associated edges.
4. Client B tries to lazy load the edges, but they are already deleted.

There was no check for such situation on the server. Added a check throwing ORecordContentNotFoundException.
