### ISSUE TITLE
server error log (it is a bug?)

### ISSUE THREAD

**Issue by publicocean0** [orientechnologies/orientdb#6707]
## OrientDB Version, operating system, or hardware.

2.2.8
## Operating System
- [x ] Linux
## Expected behavior and actual behavior

`2016-09-17 15:52:23:618 WARNI Token signature failure: AAAAAAhzdHJlYW1lcgAABQAAAAAAAAAAAAABVyz5wG8AACQAF09SZWNvcmRTZXJpYWxpemVyQmluYXJ5AA1PcmllbnREQiBKYXZhAAUyLjIuOFHqT7shN22bGQNacTkM4JbYQnyn2aA38Nlr7Bl+Xs5G [OTokenHandlerImpl]$ANSI{green {db=aa}} Cannot serialize an exception object
java.io.NotSerializableException: jdk.nashorn.api.scripting.ScriptObjectMirror
    at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1184)
    at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1548)
    at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1509)
    at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1432)
    at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1178)
    at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1548)
    at java.io.ObjectOutputStream.defaultWriteObject(ObjectOutputStream.java:441)
    at java.lang.Throwable.writeObject(Throwable.java:985)
    at sun.reflect.GeneratedMethodAccessor12.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at java.io.ObjectStreamClass.invokeWriteObject(ObjectStreamClass.java:1028)
    at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1496)
    at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1432)
    at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1178)
    at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1548)
    at java.io.ObjectOutputStream.defaultWriteObject(ObjectOutputStream.java:441)
    at java.lang.Throwable.writeObject(Throwable.java:985)
    at sun.reflect.GeneratedMethodAccessor12.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at java.io.ObjectStreamClass.invokeWriteObject(ObjectStreamClass.java:1028)
    at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1496)
    at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1432)
    at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1178)
    at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:348)
    at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.serializeExceptionObject(ONetworkProtocolBinary.java:2189)
    at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.sendError(ONetworkProtocolBinary.java:1006)
    at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.sendErrorOrDropConnection(ONetworkProtocolBinary.java:2660)
    at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.sessionRequest(ONetworkProtocolBinary.java:335)
    at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.execute(ONetworkProtocolBinary.java:196)
    at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:77)
`

**Comment by lvca** [comment]
It looks like something from a JS function was returned and OrientDB didn't know how to do that. Do yo have the function we can run to reproduce the problem?

**Comment by publicocean0** [comment]
Ah ok, i thought was a problem to convert exception for passing it to client. this error appear rarely in server log , i will investigate asap , just i i ll see it again.

**Comment by lvca** [comment]
@publicocean0 have you seen this error recently?

**Comment by publicocean0** [comment]
no , no more .
