### ISSUE TITLE
ODatabaseDocumentTx swallow Exceptions

### ISSUE THREAD

**Issue by hirodes** [orientechnologies/orientdb#6740]
## OrientDB Version, operating system, or hardware.
- v2.2.10 

## Operating System
- [ ] Linux

## Expected behavior and actual behavior
Expects to get an exception on commit of the transaction when storing data with duplicate key in index.
In stead the exception is logged and then swallowed within the ODatabaseDocumentTx class (line 1211):

`     try {`
`         commit(true);`
`      } catch (Exception e) {`
`          OLogManager.instance().error(this, "Exception during commit of active transaction", e);`
`      }`

Thus my code will never see the exception and I won't know of the duplicate key vilation.

How can I get the exception?

## Steps to reproduce the problem

OrientGraphFactory factory = new OrientGraphFactory(url, user, password).setupPool(minConnections, maxConnections);

og = factory.getTx();
try {
  OrientVertex v = og.getVertex(id);
  v.setProperty(entry.getKey(), entry.getValue());
}
catch (Exception e) {
...
}
finally {
  og.commit();
}
 
server.log:
`
21:18:23,718 SEVERE [com.orientechnologies.orient.core.db.OPartitionedDatabasePool$DatabaseDocumentTxPooled] (http-/0.0.0.0:8080-3) Exception during commit of active transaction: com.orientechnologies.orient.core.storage.ORecordDuplicatedException: Cannot index record #12:5015: found duplicated key 'f2' in index 'User.key' previously assigned to the record #12:5014
        DB name="PAM"
        DB name="PAM" INDEX=User.key RID=#12:5014
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) [rt.jar:1.7.0_79]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57) [rt.jar:1.7.0_79]
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) [rt.jar:1.7.0_79]
        at java.lang.reflect.Constructor.newInstance(Constructor.java:526) [rt.jar:1.7.0_79]
        at com.orientechnologies.orient.client.binary.OChannelBinaryAsynchClient.throwSerializedException(OChannelBinaryAsynchClient.java:428) [orientdb-client-2.2.10.jar:2.2.10]
        at com.orientechnologies.orient.client.binary.OChannelBinaryAsynchClient.handleStatus(OChannelBinaryAsynchClient.java:379) [orientdb-client-2.2.10.jar:2.2.10]
        at com.orientechnologies.orient.client.binary.OChannelBinaryAsynchClient.beginResponse(OChannelBinaryAsynchClient.java:261) [orientdb-client-2.2.10.jar:2.2.10]
        at com.orientechnologies.orient.client.binary.OChannelBinaryAsynchClient.beginResponse(OChannelBinaryAsynchClient.java:153) [orientdb-client-2.2.10.jar:2.2.10]
        at com.orientechnologies.orient.client.remote.OStorageRemote.beginResponse(OStorageRemote.java:2133) [orientdb-client-2.2.10.jar:2.2.10]
        at com.orientechnologies.orient.client.remote.OStorageRemote$28.execute(OStorageRemote.java:1316) [orientdb-client-2.2.10.jar:2.2.10]
        at com.orientechnologies.orient.client.remote.OStorageRemote$28.execute(OStorageRemote.java:1289) [orientdb-client-2.2.10.jar:2.2.10]
        at com.orientechnologies.orient.client.remote.OStorageRemote$2.execute(OStorageRemote.java:198) [orientdb-client-2.2.10.jar:2.2.10]
        at com.orientechnologies.orient.client.remote.OStorageRemote.baseNetworkOperation(OStorageRemote.java:230) [orientdb-client-2.2.10.jar:2.2.10]
        at com.orientechnologies.orient.client.remote.OStorageRemote.networkOperation(OStorageRemote.java:195) [orientdb-client-2.2.10.jar:2.2.10]
        at com.orientechnologies.orient.client.remote.OStorageRemote.commit(OStorageRemote.java:1289) [orientdb-client-2.2.10.jar:2.2.10]
        at com.orientechnologies.orient.core.tx.OTransactionOptimistic.doCommit(OTransactionOptimistic.java:560) [orientdb-core-2.2.10.jar:2.2.10]
        at com.orientechnologies.orient.core.tx.OTransactionOptimistic.commit(OTransactionOptimistic.java:106) [orientdb-core-2.2.10.jar:2.2.10]
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.commit(ODatabaseDocumentTx.java:2733) [orientdb-core-2.2.10.jar:2.2.10]
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.close(ODatabaseDocumentTx.java:1209) [orientdb-core-2.2.10.jar:2.2.10]
        at com.orientechnologies.orient.core.db.OPartitionedDatabasePool$DatabaseDocumentTxPooled.close(OPartitionedDatabasePool.java:470) [orientdb-core-2.2.10.jar:2.2.10]
        at com.tinkerpop.blueprints.impls.orient.OrientBaseGraph.shutdown(OrientBaseGraph.java:1172) [orientdb-graphdb-2.2.10.jar:2.2.10]
        at com.tinkerpop.blueprints.impls.orient.OrientBaseGraph.shutdown(OrientBaseGraph.java:1144) [orientdb-graphdb-2.2.10.jar:2.2.10]
        at com.tinkerpop.blueprints.impls.orient.OrientBaseGraph.shutdown(OrientBaseGraph.java:1137) [orientdb-graphdb-2.2.10.jar:2.2.10]
`

**Comment by lvca** [comment]
That code is in the `close()`, not the `commit()`, so your snippet works. This means if you're closing the database and there is an exception, it's forced to be closed.

**Comment by hirodes** [comment]
Thank you so much. Yes you are right, that happens when I call a shutdown without a commit. I changed my code to always do a commit before the shutdown and now I do see exception!
