### ISSUE TITLE
Cannot open remote database

### ISSUE THREAD

**Issue by bartoszm** [orientechnologies/orientdb#6751]
## OrientDB Version, operating system, or hardware.
- v2.2 SNAPSHOT[ ] - .rc1[ ] .beta2[ ] .beta1[ ]

## Operating System
- [ ] Windows

## Expected behavior and actual behavior
When trying to open a remote DB on Tomcat NPE is thrown 
It is due to the fact that 
`java.lang.Package#getImplementationVersion` might return `null`

and  `com.orientechnologies.orient.core.security.OSecurityManager#isAlgorithmSupported` is not checking for null values

`
com.orientechnologies.orient.core.exception.ODatabaseException: Cannot open database url=remote:localhost/tapi-test1
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.open(ODatabaseDocumentTx.java:293)
[..cut..]
Caused by: java.lang.NullPointerException
	at com.orientechnologies.orient.core.security.OSecurityManager.isAlgorithmSupported(OSecurityManager.java:255)
	at com.orientechnologies.orient.core.security.OSecurityManager.validateAlgorithm(OSecurityManager.java:268)
	at com.orientechnologies.orient.core.security.OSecurityManager.createHash(OSecurityManager.java:139)
	at com.orientechnologies.orient.core.metadata.security.OUser.encryptPassword(OUser.java:81)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.initAtFirstOpen(ODatabaseDocumentTx.java:3091)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.open(ODatabaseDocumentTx.java:269)
	... 52 more`

## Steps to reproduce the problem
Try to open a connection from within a Tomcat server (war application)

**Comment by bartoszm** [comment]
Actually the issue is cause by JRebel - still, handling null values in `com.orientechnologies.orient.core.security.OSecurityManager#isAlgorithmSupported ` would be nice

**Comment by SDIPro** [comment]
Added null checks to Runtime.class.getPackage() and getPackage().getImplementationVersion() in isAlgorithmSupported().
