### ISSUE TITLE
Default heap/cache size on large data

### ISSUE THREAD

**Issue by taburet** [orientechnologies/orientdb#6755]
As #6666 reveals, there is probably some problem on large data (~300GB) with default heap/cache size settings. Seem like there are some exceptions that somehow got silenced. We should try to recreate the problem on one of our test servers.

**Comment by rdelangh** [comment]
@taburet 
Dbase schema is not very complex : 
- 3 'document' classes, each one containing some 20-30 STRING attributes and one single DATE attribute
- number of records in the 3 classes is estimated to be some 13M in 1st class "mds_csv_cf12", 313M in 2nd class "mds_csv_cf14", 10M in class "mds_csv_cf15"
- total size of the database on its filesystem is now approx 460GB

Does this help, or do you need other information?

**Comment by taburet** [comment]
@rdelangh, I think that is enough information, thank you.

**Comment by taburet** [comment]
@rdelangh tried various combinations of heap/cache size on a synthetic database, no leaks or "OCachePointer.finalize: readers != 0" messages. Could you please revert the heap/cache size to the defaults and execute the leak detection procedure on your side as described [here](http://orientdb.com/docs/2.2/Leak-Detector.html).

**Comment by rdelangh** [comment]
@laa, @taburet 
Meanwhile I installed v2.2.11

1. I left its default parameters in "bin/server.sh" for the heap, i.e. "-Xms512m -Xmx512m" , unchanged
2. launched a first client connection via "console.sh", trying to connect to our big database (> 500GB); nothing happens for minutes, I see in the filesystem that various of the big files of that database are being accessed (scanned for consistency?)
3. meanwhile, I launch an extra client which makes REST calls to the server, for inserting records into another database (which is already opened)
4. after inserting some 30000 records, the next insert of a new batch of 5000 records hangs, and then fails with REST response code 500, message is "java.lang.OutOfMemoryError: GC overhead limit exceeded"

The server logs say

java.lang.OutOfMemoryError: GC overhead limit exceeded
        at java.io.BufferedOutputStream.<init>(BufferedOutputStream.java:76)
        at com.orientechnologies.orient.enterprise.channel.text.OChannelTextServer.<init>(OChannelTextServer.java:34)
        at com.orientechnologies.orient.server.network.protocol.http.ONetworkProtocolHttpAbstract.config(ONetworkProtocolHttpAbstract.java:109)
        at com.orientechnologies.orient.server.network.protocol.http.ONetworkProtocolHttpDb.config(ONetworkProtocolHttpDb.java:43)
        at com.orientechnologies.orient.server.network.OServerNetworkListener.run(OServerNetworkListener.java:216)
Error on client connection

So I go into your leak detection procedure:
1. stopped the node again
2. modified the "bin/server.sh" script so that the following extra parameters are added to the startup commandline: 
-Dmemory.directMemory.trackMode=true -Djava.util.logging.manager=com.orientechnologies.common.log.OLogManager\$DebugLogManager (mind you that I escaped the dollar sign before "DebugLogManager")
3. started the node again, doing exactly the same as above:
- start the "bin/console.sh", and connect with our smaller database "navi", deleting some 30000 recently inserted records;
- still from the console, connect with our big database "cdrarch"; after few mins the GC errors appear
- the logs on the server (I had to stop the server quickly to avoid that all logfiles 'overflowed'...):

2016-10-12 15:56:34:544 INFO  OrientDB Studio available at http://10.49.69.190:2480/studio/index.html [OServer]
2016-10-12 15:56:34:544 INFO  OrientDB Server is active v2.2.11 (build 2.2.x@r8b3a478e3ca7321a48e7cf0f5991569bbe06ed89; 2016-10-03 09:39:41+0000). [OServer]
2016-10-12 15:57:26:417 INFO  {db=navi} [TIP] Query 'SELECT FROM idtv_bannerlog WHERE event_dt BETWEEN '2016-06-15 00:00:00' AND '2016-06-16 00:00:00'' returned a res
ult set with more than 10000 records. Check if you really need all these records, or reduce the resultset by using a LIMIT to improve both performance and used RAM [O
ProfilerStub]
2016-10-12 15:58:10:559 SEVER OCachePointer.finalize: readers != 0 [OCachePointer]DIRECT-TRACK: untracked direct byte buffer `664EBA9` detected.
java.lang.Exception
        at com.orientechnologies.common.directmemory.OByteBufferPool.untrackBuffer(OByteBufferPool.java:550)
        at com.orientechnologies.common.directmemory.OByteBufferPool.release(OByteBufferPool.java:354)
        at com.orientechnologies.orient.core.storage.cache.OCachePointer.finalize(OCachePointer.java:262)
        at java.lang.System$2.invokeFinalize(System.java:1270)
        at java.lang.ref.Finalizer.runFinalizer(Finalizer.java:98)
        at java.lang.ref.Finalizer.access$100(Finalizer.java:34)
        at java.lang.ref.Finalizer$FinalizerThread.run(Finalizer.java:210)

2016-10-12 15:58:10:567 SEVER OCachePointer.finalize: readers != 0 [OCachePointer]DIRECT-TRACK: untracked direct byte buffer `F92C625` detected.
java.lang.Exception
        at com.orientechnologies.common.directmemory.OByteBufferPool.untrackBuffer(OByteBufferPool.java:550)
        at com.orientechnologies.common.directmemory.OByteBufferPool.release(OByteBufferPool.java:354)
        at com.orientechnologies.orient.core.storage.cache.OCachePointer.finalize(OCachePointer.java:262)
        at java.lang.System$2.invokeFinalize(System.java:1270)
        at java.lang.ref.Finalizer.runFinalizer(Finalizer.java:98)
        at java.lang.ref.Finalizer.access$100(Finalizer.java:34)
        at java.lang.ref.Finalizer$FinalizerThread.run(Finalizer.java:210)

2016-10-12 15:58:10:568 SEVER OCachePointer.finalize: readers != 0 [OCachePointer]DIRECT-TRACK: untracked direct byte buffer `695A5283` detected.
java.lang.Exception
        at com.orientechnologies.common.directmemory.OByteBufferPool.untrackBuffer(OByteBufferPool.java:550)
        at com.orientechnologies.common.directmemory.OByteBufferPool.release(OByteBufferPool.java:354)
        at com.orientechnologies.orient.core.storage.cache.OCachePointer.finalize(OCachePointer.java:262)
        at java.lang.System$2.invokeFinalize(System.java:1270)
        at java.lang.ref.Finalizer.runFinalizer(Finalizer.java:98)
        at java.lang.ref.Finalizer.access$100(Finalizer.java:34)
        at java.lang.ref.Finalizer$FinalizerThread.run(Finalizer.java:210)

2016-10-12 15:58:10:568 SEVER OCachePointer.finalize: readers != 0 [OCachePointer]DIRECT-TRACK: untracked direct byte buffer `64A24505` detected.
java.lang.Exception
        at com.orientechnologies.common.directmemory.OByteBufferPool.untrackBuffer(OByteBufferPool.java:550)
        at com.orientechnologies.common.directmemory.OByteBufferPool.release(OByteBufferPool.java:354)
        at com.orientechnologies.orient.core.storage.cache.OCachePointer.finalize(OCachePointer.java:262)
        at java.lang.System$2.invokeFinalize(System.java:1270)
        at java.lang.ref.Finalizer.runFinalizer(Finalizer.java:98)
        at java.lang.ref.Finalizer.access$100(Finalizer.java:34)
        at java.lang.ref.Finalizer$FinalizerThread.run(Finalizer.java:210)

...

**Comment by rdelangh** [comment]
@laa, @taburet 
FYI, setting "-Xmx6000m" makes the server spin again like a charm, absorbing zillions of data without any GC errors.

**Comment by lvca** [comment]
@rdelangh thanks for the feedback. @taburet and @laa why did we limit the max heap in the server.sh?

**Comment by taburet** [comment]
@lvca there are different `-Xmx` defaults for different JVM versions for different platforms from different vendors. For example, for Oracle's Java 6 JVM it's no more than a 256MB regardless of the amount of RAM installed. Limit was raised in newer versions, but it's still inconsistent across versions, platforms and vendors.

We may try to obtain the default `-Xmx` value in `server.sh/bat` and limit its lower value to, say, 512m, or calculate the `-Xmx` by hands with the amount of installed RAM in mind. That will require bash/cmd hacking and we must be sure it works with all possible JVM+platform combinations, or at least it must be able to fail gracefully to some reasonable default. Maybe it's even will be better to create a separate Java launcher to eliminate the platform/vendor difference. WDYT?

Closing the issue, since we are not handling the OOM situations in current ODB design.
