### ISSUE TITLE
Error on opening database: the engine 'remote' was not found

### ISSUE THREAD

**Issue by borov333** [orientechnologies/orientdb#6764]
## OrientDB Version, operating system, or hardware.
- v2.2.10

## Operating System
- [x ] Linux
- [x ] MacOSX

## Expected behavior and actual behavior

I'm unable to connect to the orientdb database from the fat jar. However, I can successfully connect to db on the exact same code and build (using gradle) from my Netbeans IDE. I can also easily connect from the console and studio is running and working fine in the browser. Here is the error I'm getting:

Exception in thread "main" com.orientechnologies.orient.core.exception.ODatabaseException: Error on opening database 'remote:localhost/Customers'
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.<init>(ODatabaseDocumentTx.java:190)
	at com.orientechnologies.orient.core.db.OPartitionedDatabasePool$DatabaseDocumentTxPooled.<init>(OPartitionedDatabasePool.java:423)
	at com.orientechnologies.orient.core.db.OPartitionedDatabasePool$DatabaseDocumentTxPooled.<init>(OPartitionedDatabasePool.java:419)
	at com.orientechnologies.orient.core.db.OPartitionedDatabasePool.initQueue(OPartitionedDatabasePool.java:355)
	at com.orientechnologies.orient.core.db.OPartitionedDatabasePool.<init>(OPartitionedDatabasePool.java:116)
	at com.orientechnologies.orient.core.db.OPartitionedDatabasePoolFactory.get(OPartitionedDatabasePoolFactory.java:116)
	at com.engine.core.DbPool.init(DbPool.java:39)
	at com.engine.Engine.initDbPool(Engine.java:115)
	at com.engine.Engine.main(Engine.java:37)
Caused by: com.orientechnologies.orient.core.exception.OConfigurationException: Error on opening database: **the engine 'remote' was not found. URL was: remote:localhost/Customers**. Registered engines are: [memory, plocal]
	DB name="remote:localhost/Customers"
	at com.orientechnologies.orient.core.Orient.loadStorage(Orient.java:462)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.<init>(ODatabaseDocumentTx.java:170)

I searched on google for hours before posting this issue. Many recommend that the issue may be with the fact that "orientdb-client" jar may not be found at the time of running. I doubt that this is the case here. I'm using the exact same gradle build script to run it in Netbeans IDE as well as building it in the console. I'm using com.github.johnrengelman.shadow library (https://github.com/johnrengelman/shadow) to build the fat (uber) jar and when I unarchived this fat jar I do clearly see that all Remote client classes are there. 

Let me know if I can run any other tests or get you any additional info to help.

**Comment by maggiolo00** [comment]
hi @borov333 

that exception means that in your fat jar some services files are missing.

if you build a fat jar with maven you can use the shade plugin

http://orientdb.com/docs/2.2/Tutorial-Installation.html#building-a-single-executable-jar-with-orientdb

With gradle i don't know. You should check with that plugin how to merge the resource/service files.

Thanks

**Comment by borov333** [comment]
Enrico - you're genius!

That was the exact problem, by default, building a fat jar with the shadow
plugin for gradle was not including services. However, it is a very simple
fix. In case anyone else asks you guys for the solution with gradle, you
can refer to this link:
http://imperceptiblethoughts.com/shadow/#controlling_jar_content_merging

Just add:

shadowJar {
  mergeServiceFiles()
}


Thanks
