### ISSUE TITLE
Local node 'aNode' is not the master for cluster 'aCluster' (it is 'anotherNode')

### ISSUE THREAD

**Issue by wazmataz** [orientechnologies/orientdb#6765]
## OrientDB Version, operating system, or hardware.
2.2.8

## Operating System
- [x] Linux
- [ ] MacOSX
- [ ] Windows
- [ ] Other Unix
- [ ] Other, name? 

## Expected behavior and actual behavior
We're using OrientDB in a cluster with 5 nodes with the Java API libraries on top of it. Both of them are using version 2.2.8, and we're using Tinkerpop Blueprints version 2.6.0. We're experiencing a strange issue where the database runs fine for some time, then we suddenly start encountering the error below. We have only started experiencing this issue since we upgraded to 2.2 from 1.7.

## Update
Looking in to this further we're consistently seeing this issue now. We believe the issue is related to some code where we remove an edge, then re-create it with the exact same details (label, inVertex, iClassName, iClusterName) in quick succession. We perform a graph.commit between these 2 stages. The 2 Vertexes / Vertices we're trying to connect are actually on different clusters (the first part of the rid is different). We also tried reducing the number of nodes in our OrientDB cluster down to a single node and we still saw this error.

## default-distributed-db-config.json
`{
    "autoDeploy": true,
    "hotAlignment": false,
    "readQuorum": 1,
    "writeQuorum": "all",
    "failureAvailableNodesLessQuorum": false,
    "readYourWrites": true,
    "executionMode": "synchronous",
    "servers": {
        "*": "master"
    },
    "clusters": {
        "internal": {
        },
        "index": {
        },
        "*": {
            "servers" : [ "<NEW_NODE>" ]
        }
    }
}`

## Stacktrace
`com.orientechnologies.orient.server.distributed.ODistributedConfigurationChangedException: Local node 'aNode' is not the master for cluster 'aCluster' (it is 'anotherNode')
	DB name="dbName"
	DB name="dbName"
	at sun.reflect.GeneratedConstructorAccessor61.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at com.orientechnologies.orient.client.binary.OChannelBinaryAsynchClient.throwSerializedException(OChannelBinaryAsynchClient.java:428)
	at com.orientechnologies.orient.client.binary.OChannelBinaryAsynchClient.handleStatus(OChannelBinaryAsynchClient.java:379)
	at com.orientechnologies.orient.client.binary.OChannelBinaryAsynchClient.beginResponse(OChannelBinaryAsynchClient.java:261)
	at com.orientechnologies.orient.client.binary.OChannelBinaryAsynchClient.beginResponse(OChannelBinaryAsynchClient.java:153)
	at com.orientechnologies.orient.client.remote.OStorageRemote.beginResponse(OStorageRemote.java:2133)
	at com.orientechnologies.orient.client.remote.OStorageRemote$28.execute(OStorageRemote.java:1316)
	at com.orientechnologies.orient.client.remote.OStorageRemote$28.execute(OStorageRemote.java:1289)
	at com.orientechnologies.orient.client.remote.OStorageRemote$2.execute(OStorageRemote.java:198)
	at com.orientechnologies.orient.client.remote.OStorageRemote.baseNetworkOperation(OStorageRemote.java:230)
	at com.orientechnologies.orient.client.remote.OStorageRemote.networkOperation(OStorageRemote.java:195)
	at com.orientechnologies.orient.client.remote.OStorageRemote.commit(OStorageRemote.java:1289)
	at com.orientechnologies.orient.core.tx.OTransactionOptimistic.doCommit(OTransactionOptimistic.java:560)
	at com.orientechnologies.orient.core.tx.OTransactionOptimistic.commit(OTransactionOptimistic.java:106)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.commit(ODatabaseDocumentTx.java:2733)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.commit(ODatabaseDocumentTx.java:2703)
	at com.tinkerpop.blueprints.impls.orient.OrientTransactionalGraph.commit(OrientTransactionalGraph.java:175)`

**Comment by lvca** [comment]
Do you pass the cluster name to the API? If you pass it, you have to be sure the local node is the owner of that cluster. The best thing to do is to pass it as null, so OrientDB will use one available on local server.

**Comment by wazmataz** [comment]
We're no longer passing in the cluster name when adding the edge to the vertex, as follows:
`aVertex.addEdge("label", anotherVertex, "label", null, new HashMap<String, String>());`

but are still encountering the error message:
`com.orientechnologies.orient.server.distributed.ODistributedConfigurationChangedException: Local node 'node1473777852498' is not the master for cluster 'aCluster' (it is 'node1473777851951')`

The aCluster is actually an @class value in the Edge metadata

**Comment by lvca** [comment]
Ok, this could be the problem: at first analysis, OrientDB uses "label" as edge class, then, in the post-processing phase, the class is overridden causing this error.

Could you please try this?

`aVertex.addEdge("aCluster", anotherVertex);`

**Comment by wazmataz** [comment]
removing the cluster name and class name from the api call solved this issue.
