### ISSUE TITLE
NullPointerException during incremental restore

### ISSUE THREAD

**Issue by yeoedward** [orientechnologies/orientdb#6774]
## OrientDB Version, operating system, or hardware.
OrientDB Enterprise Edition v2.2.4

## Operating System
Linux

## Expected behavior and actual behavior
Incremental restore using the Java API throws a null pointer exception. A corrupted database is created from this restore. It cannot be deleted nor logged into via the web studio.

## Steps to reproduce the problem
If I execute a single incremental backup and restore (single ibu file in the backup directory), everything works fine. However, if I execute another incremental backup after creating one new vertex (meaning two ibu files now), and then try to restore, I get the exception below during the restore. Note that I tried but was unable to reproduce this on an example database. I cannot share my database publicly nor privately because it contains proprietary data. Please let me know if there is any more information I can provide to help with debugging.

Command executed (Java API):

```
new OServerAdmin(dbHost)
  .connect(username, password)
  .createDatabase(dbName, "graph", "plocal", backupPath);
```

Server Log:

```
2016-10-03 19:33:26:319 WARNI {db=<restore_db_name>} Record OFuzzyCheckpointStartRecord{lsn=OLogSequenceNumber{segment=#, position=#}} com.orientechnologies.orient.core.storage.impl.local.paginated.wal.OFuzzyCheckpointStartRecord{lsn=null, previousCheckpoint=OLogSequenceNumber{segment=#, position=#}} will be skipped during data restore [OEnterpriseLocalPaginatedStorage]
2016-10-03 19:33:26:320 WARNI {db=<restore_db_name>} Record com.orientechnologies.orient.core.storage.impl.local.paginated.wal.OFuzzyCheckpointEndRecord{lsn=OLogSequenceNumber{segment=#, position=#}} will be skipped during data restore [OEnterpriseLocalPaginatedStorage]
```

Exception:

```
Caused by: com.orientechnologies.orient.enterprise.channel.binary.OResponseProcessingException: Exception during response processing
	at com.orientechnologies.orient.client.binary.OChannelBinaryAsynchClient.throwSerializedException(OChannelBinaryAsynchClient.java:443)
	at com.orientechnologies.orient.client.binary.OChannelBinaryAsynchClient.handleStatus(OChannelBinaryAsynchClient.java:378)
	at com.orientechnologies.orient.client.binary.OChannelBinaryAsynchClient.beginResponse(OChannelBinaryAsynchClient.java:260)
	at com.orientechnologies.orient.client.binary.OChannelBinaryAsynchClient.beginResponse(OChannelBinaryAsynchClient.java:152)
	at com.orientechnologies.orient.client.remote.OStorageRemote.beginResponse(OStorageRemote.java:2087)
	at com.orientechnologies.orient.client.remote.OStorageRemote.getResponse(OStorageRemote.java:2095)
	at com.orientechnologies.orient.client.remote.OServerAdmin$5.execute(OServerAdmin.java:265)
	at com.orientechnologies.orient.client.remote.OServerAdmin$5.execute(OServerAdmin.java:243)
	at com.orientechnologies.orient.client.remote.OServerAdmin.networkAdminOperation(OServerAdmin.java:695)
	... 8 more
Caused by: java.lang.NullPointerException
	at com.orientechnologies.lucene.engine.OLuceneIndexEngineDelegate.close(OLuceneIndexEngineDelegate.java:117)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.closeIndexes(OAbstractPaginatedStorage.java:3554)
	at com.orientechnologies.orient.core.storage.impl.local.paginated.OEnterpriseLocalPaginatedStorage.restoreFromIncrementalBackup(OEnterpriseLocalPaginatedStorage.java:419)
	at com.orientechnologies.orient.core.storage.impl.local.paginated.OEnterpriseLocalPaginatedStorage.restoreFromIncrementalBackup(OEnterpriseLocalPaginatedStorage.java:398)
	at com.orientechnologies.orient.core.storage.impl.local.paginated.OEnterpriseLocalPaginatedStorage.restoreFromIncrementalBackup(OEnterpriseLocalPaginatedStorage.java:364)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.create(ODatabaseDocumentTx.java:374)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.createDatabase(ONetworkProtocolBinary.java:2585)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.createDatabase(ONetworkProtocolBinary.java:1160)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.executeRequest(ONetworkProtocolBinary.java:362)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.execute(ONetworkProtocolBinary.java:199)
	at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:77)
```

**Comment by maggiolo00** [comment]
hi @yeoedward 

i've fixed the NPE.
But for now Lucene indexes are not supported in the incremental backup. So once it's finished you should rebuild Lucene indexes at least until this is implemented 

https://github.com/orientechnologies/orientdb/issues/5958

Thanks

**Comment by yeoedward** [comment]
Thanks @maggiolo00 !
