### ISSUE TITLE
Node name should support all characters, including dot.

### ISSUE THREAD

**Issue by dominioon** [orientechnologies/orientdb#6787]
## OrientDB Version, operating system, or hardware.
-  [x] v2.2.11
## Operating System
- [X] Linux
## Expected behavior and actual behavior

Node name should support all characters, including dot.
## Steps to reproduce the problem

`System.setProperty("ORIENTDB_NODE_NAME", "my.node.name");
`

```
....
Caused by: java.lang.IllegalArgumentException: Property 'my.node' is null, is possible to set a value with dotted notation only on not null property
    at com.orientechnologies.orient.core.record.impl.ODocument.field(ODocument.java:1053)
    at com.orientechnologies.orient.core.record.impl.ODocument.field(ODocument.java:912)
    at com.orientechnologies.orient.server.distributed.impl.ODistributedOutput.formatClusterTable(ODistributedOutput.java:566)
    at com.orientechnologies.orient.server.distributed.impl.ODistributedAbstractPlugin.updateCachedDatabaseConfiguration(ODistributedAbstractPlugin.java:384)
    at com.orientechnologies.orient.server.hazelcast.OHazelcastPlugin.updateCachedDatabaseConfiguration(OHazelcastPlugin.java:673)
    at com.orientechnologies.orient.server.distributed.impl.ODistributedAbstractPlugin.executeInDistributedDatabaseLock(ODistributedAbstractPlugin.java:1490)
    at com.orientechnologies.orient.server.distributed.impl.ODistributedDatabaseImpl.checkLocalNodeInConfiguration(ODistributedDatabaseImpl.java:811)
    at com.orientechnologies.orient.server.distributed.impl.ODistributedDatabaseImpl.<init>(ODistributedDatabaseImpl.java:104)
    at com.orientechnologies.orient.server.distributed.impl.ODistributedMessageServiceImpl.registerDatabase(ODistributedMessageServiceImpl.java:126)
    at com.orientechnologies.orient.server.hazelcast.OHazelcastPlugin.onCreate(OHazelcastPlugin.java:949)
    at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.create(ODatabaseDocumentTx.java:467)
    at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.create(ODatabaseDocumentTx.java:389)
    at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.createDatabase(ONetworkProtocolBinary.java:2656)
    at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.createDatabase(ONetworkProtocolBinary.java:1247)
    at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.executeRequest(ONetworkProtocolBinary.java:482)
    at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.sessionRequest(ONetworkProtocolBinary.java:318)
    at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.execute(ONetworkProtocolBinary.java:194)
    at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:77)

```

**Comment by lvca** [comment]
This is not supported, sorry. Could you use another character instead of . ?
