### ISSUE TITLE
Range filtering (in, out) throws NegativeArrayException when the provided range is out of bounds

### ISSUE THREAD

**Issue by benjaminbillet** [orientechnologies/orientdb#6793]
## OrientDB Version, operating system, or hardware.
2.2.11 MacOS X

## Expected behavior and actual behavior
`SELECT out('edge')[10-20] FROM V` throws a `NegativeArrayException` if a vertex has less than 10 edges of type "edge". The problem is easy to reproduce: it occurs in studio, console and client APIs.

The problem occurs only with ranges, `SELECT out('edge')[10] FROM V` doesn't fail. However, it returns an empty tuple while I would have expected no results at all:

```
> SELECT out('anEdge')[0] FROM RootType

+----+
|#   |
+----+
|0   |
+----+

1 item(s) found. Query executed in 0.003 sec(s).
```

Some test code:
```java
OrientVertex vertex1 = graph.addVertex("class:V");
OrientVertex vertex2 = graph.addVertex("class:V");
vertex1.addEdge("edge", vertex2);
graph.commit();

String query = "SELECT out('edge')[10] FROM V";
Iterable<OrientVertex> results = graph.command(new OCommandSQL(query)).execute();
// ok, but results contains one element

query = "SELECT out('nonExistingEdge')[0] FROM V";
results = graph.command(new OCommandSQL(query)).execute();
// ok, but results contains one element

query = "SELECT out('nonExistingEdge')[0-10] FROM V";
results = graph.command(new OCommandSQL(query)).execute();
// ok, but results contains one element

query = "SELECT out('nonExistingEdge')[10-20] FROM V";
results = graph.command(new OCommandSQL(query)).execute();
/* Exception in thread "main" com.orientechnologies.orient.core.exception.OCommandExecutionException: Error on execution of command: sql.SELECT out('nonExistingEdge')[10-20] FROM V
...
Caused by: java.lang.NegativeArraySizeException
at com.orientechnologies.orient.core.record.impl.ODocumentHelper.getFieldValue(ODocumentHelper.java:452)
at com.orientechnologies.orient.core.sql.functions.coll.OSQLMethodMultiValue.execute(OSQLMethodMultiValue.java:54)
at com.orientechnologies.orient.core.sql.method.OSQLMethodRuntime.execute(OSQLMethodRuntime.java:139)
at com.orientechnologies.orient.core.sql.filter.OSQLFilterItemAbstract.transformValue(OSQLFilterItemAbstract.java:140)
at com.orientechnologies.orient.core.sql.functions.OSQLFunctionRuntime.execute(OSQLFunctionRuntime.java:134)
at com.orientechnologies.orient.core.sql.ORuntimeResult.applyRecord(ORuntimeResult.java:141)
at com.orientechnologies.orient.core.sql.ORuntimeResult.getProjectionResult(ORuntimeResult.java:255)
at com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.addResult(OCommandExecutorSQLSelect.java:707)
at com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.handleResult(OCommandExecutorSQLSelect.java:673)
at com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.executeSearchRecord(OCommandExecutorSQLSelect.java:630)
at com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.serialIterator(OCommandExecutorSQLSelect.java:1619)
at com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.fetchFromTarget(OCommandExecutorSQLSelect.java:1566)
at com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.executeSearch(OCommandExecutorSQLSelect.java:525)
at com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.execute(OCommandExecutorSQLSelect.java:488)
at com.orientechnologies.orient.core.sql.OCommandExecutorSQLDelegate.execute(OCommandExecutorSQLDelegate.java:74)
at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.executeCommand(OAbstractPaginatedStorage.java:2672)
at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.command(OAbstractPaginatedStorage.java:2618)
at com.orientechnologies.orient.core.command.OCommandRequestTextAbstract.execute(OCommandRequestTextAbstract.java:69)
at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.command(ONetworkProtocolBinary.java:1438)
at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.executeRequest(ONetworkProtocolBinary.java:576)
at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.sessionRequest(ONetworkProtocolBinary.java:321)
at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.execute(ONetworkProtocolBinary.java:197)
at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:77)*/
```

**Comment by luigidellaquila** [comment]
Hi @benjaminbillet 

I just pushed a fix for this, the fix will be released with 2.2.12

Thanks

Luigi

**Comment by benjaminbillet** [comment]
Thanks a lot. However, I read the fix and I think it will only solve the range exception problem, but not the empty tuple problem. Typically, if the index is greater than the number of edges, the database returns an empty tuple. 

Example:
```
> SELECT out('edgeType')[0] FROM RootType

+----+
|#   |
+----+
|0   |
+----+

1 item(s) found. Query executed in 0.003 sec(s).
```
From client side, we have to deal with this empty element. For example, in Java, the OrientDynaElementIterable will contains one element with no properties.
```java
String query = "SELECT out('nonExistingEdge')[0] FROM RootType";
Iterable<OrientVertex> results = graph.command(new OCommandSQL(query)).execute();
System.out.println(results.iterator().hasNext()); // true
OrientVertex v = results.iterator().next();
System.out.println(v); // v(null)[#-2:0]
System.out.println(v.getProperties()); // {}
```

Maybe should I create a new issue for this? Or is it the expected behavior?

**Comment by luigidellaquila** [comment]
Hi @benjaminbillet 

The result of the query depends on the starting node, not on the number of results in the out(), eg. if you change the query as follows:

```
SELECT out('edgeType')[0] as edge, @class FROM RootType
```

you will see what I mean.

If you only need the vertices on the other side, you can use the expand() function, eg.

```
SELECT expand(out('edgeType')[0]) FROM RootType
```

In this case you won't have any empty tuples

I hope I got it right...

Thanks

Luigi

**Comment by benjaminbillet** [comment]
Ok, you're right. This is more clear now, thanks :)
