### ISSUE TITLE
Live Query stops working under heavy load

### ISSUE THREAD

**Issue by dominioon** [orientechnologies/orientdb#6794]
## OrientDB Version, operating system, or hardware.
-  [x] v2.2.11
## Operating System
- [X] Linux
## Steps to reproduce the problem

Hard to reproduce. Happened in a two-node environment when made an update (via Studio) involving hundreds or thousands of records to a table which had live update listener set up.

Log from node2:

```
[10/7/16 16:05:53:839 EEST] 00000025 nt.server.distributed.impl.OConflictResolverDatabaseRepairer I [node2]->[[node2, node1]] Auto repairing completed. Sent 1 fix messages for 1 records (reqId=1.49777)
[10/7/16 16:06:09:187 EEST] 00000076 com.orientechnologies.orient.client.remote.OStorageRemote    I Caught Network I/O errors on 127.0.0.1:2424/DatabaseName, trying an automatic reconnection... (error: Timeout on reading response)
[10/7/16 16:06:09:213 EEST] 00000075 nt.server.network.protocol.binary.OLiveCommandResultListener W Unsubscribing live query for connection OClientConnection [id=7, source=?, since=1475762277693]
[10/7/16 16:06:19:509 EEST] 00000075 nt.server.network.protocol.binary.OLiveCommandResultListener W Unsubscribing live query for connection OClientConnection [id=7, source=/127.0.0.1:36718, since=1475762277693]
[10/7/16 16:06:22:150 EEST] 000033d3 com.orientechnologies.common.profiler.OProfilerStub          I [10/7/16 16:06:38:956 EEST] 00000025 gies.orient.server.distributed.impl.ODistributedDatabaseImpl W [node2] Timeout (10002ms) on waiting for synchronous responses from nodes=[node1] responsesSoFar=[] request=(id=1.49797 task=heartbeat timestamp: 1475845588954)
[10/7/16 16:06:38:960 EEST] 00000025 ologies.orient.server.distributed.impl.OClusterHealthChecker W [node2]->[node1] Server 'node1' did not respond to the heartbeat message (db=DatabaseName, timeout=10000ms), but cannot be set OFFLINE by configuration
[10/7/16 16:07:27:459 EEST] 000033d3 java.lang.Class                                              W Error on unsubscribing client
[10/7/16 16:07:27:462 EEST] 000033d3 java.lang.Class                                              W Error on unsubscribing client
[10/7/16 16:07:27:560 EEST] 00000075 nt.server.network.protocol.binary.OLiveCommandResultListener W Unsubscribing live query for connection OClientConnection [id=7, source=/127.0.0.1:36715, since=1475762277693]
[10/7/16 16:09:27:608 EEST] 00000075 ientechnologies.orient.core.query.live.OLiveQueryQueueThread W Error executing live query subscriber.
java.lang.NullPointerException
        at com.orientechnologies.orient.server.network.protocol.binary.OLiveCommandResultListener.onLiveResult(OLiveCommandResultListener.java:113)
        at com.orientechnologies.orient.core.sql.OCommandExecutorSQLLiveSelect$2.call(OCommandExecutorSQLLiveSelect.java:131)
        at com.orientechnologies.orient.core.sql.OCommandExecutorSQLLiveSelect.execInSeparateDatabase(OCommandExecutorSQLLiveSelect.java:141)
        at com.orientechnologies.orient.core.sql.OCommandExecutorSQLLiveSelect.onLiveResult(OCommandExecutorSQLLiveSelect.java:128)
        at com.orientechnologies.orient.core.query.live.OLiveQueryQueueThread.run(OLiveQueryQueueThread.java:69)
```

Both nodes were actually up and running. The error keeps popping up with every new update, and even restarting the live queries with `live unsubscribe` and new `live select from` did not help.

**Comment by maggiolo00** [comment]
@dominioon 

do you get the NPE when you try to live unsubscribe?

**Comment by dominioon** [comment]
@maggiolo00 

I think the updaters restart routine worked without exceptions (sorry, dont have the logs for that any more). The NPE (OLiveCommandResultListener.java:113) was coming with every new update that any of the nodes was doing.

**Comment by maggiolo00** [comment]
@dominioon 

do you use live query from java?

**Comment by dominioon** [comment]
@maggiolo00 , yes from java. You can see the main concept of the program from the file attached to  https://github.com/orientechnologies/orientdb/issues/6718 .

**Comment by maggiolo00** [comment]
@dominioon 

thanks i will give it a look. I tried to reproduce it with 2 nodes, 1 live query from a client and a massive update from studio without luck. Let me check your code

**Comment by maggiolo00** [comment]
@dominioon 

still not able to reproduce it. Do you have a deterministic way to reproduce it?

Thanks

**Comment by dominioon** [comment]
@maggiolo00,
unfortunately no. I just had encountered it twice and the only way to resolve it was to restart the server. Maybe just code and stacktrace analysis can give some hints how that NPE is possible?

**Comment by horuzhiy** [comment]
Looks like increasing 'network.token.expireTimeout' helps for avoid disconnection of live queries from the server.
I using java with connection pooling and randomly there where disconnections - 'onError' where called in OLiveResultListener. And on service side with ('FINE' logs) 'com.orientechnologies.orient.enterprise.channel.binary.OTokenSecurityException: The token provided is expired' appear.

**Comment by lvca** [comment]
@tglman is this a problem of token renewal?
