### ISSUE TITLE
NullPointerException in serializer

### ISSUE THREAD

**Issue by smil2k** [orientechnologies/orientdb#6800]
## OrientDB Version, operating system, or hardware.

- v2.2.9

## Operating System
- [x] Linux
- [ ] MacOSX
- [ ] Windows
- [ ] Other Unix
- [ ] Other, name? 

## Steps to reproduce the problem

2016-10-11 05:21:46.166 [kafka-consumer-modules-events-E615E245-8C68-11E6-AFC0-0050568B6471-admin-service-0] WARN  c.o.o.c.s.s.r.b.ORecordSerializerBinary - Error deserializin
g record to get field-names, send this data for debugging: ABhPcmllbnRPZmZzZXRDAAAAJD8AAAAnCkB0eXBlAAAAWAcAtuMDYG1vZHVsZXMtZXZlbnRzOkZMRUVUQURBUFRFUkhPUklaT05TVUJTQ1JJUFRJT046
MAJk 
2016-10-11 05:21:46.194 [kafka-consumer-modules-events-E620B7C4-8C68-11E6-AFC0-0050568B6471-admin-service-0] ERROR c.l.p.u.e.ExceptionLoggingExecutorService - Exception caught
 during run
java.lang.NullPointerException: null
        at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinaryV0.getFieldNames(ORecordSerializerBinaryV0.java:319)
        at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinary.getFieldNames(ORecordSerializerBinary.java:112)
        at com.orientechnologies.orient.core.record.impl.ODocument.fieldNames(ODocument.java:735)

2016-10-11 05:26:00.011 [kafka-consumer-modules-events-E615E245-8C68-11E6-AFC0-0050568B6471-admin-service-0] WARN  c.o.o.c.s.s.r.b.ORecordSerializerBinary - Error deserializing record to get field-names, send this data for debugging: ABhPcmllbnRPZmZzZXRDAAAAJD8AAAAnCkB0eXBlAAAAWAcAtuMDYG1vZHVsZXMtZXZlbnRzOkZMRUVUQURBUFRFUkhPUklaT05TVUJTQ1JJUFRJT046MAJk 
2016-10-11 05:26:00.011 [kafka-consumer-modules-events-E616F3BA-8C68-11E6-AFC0-0050568B6471-admin-service-0] WARN  c.o.o.c.s.s.r.b.ORecordSerializerBinary - Error deserializing record to get field-names, send this data for debugging: ABhPcmllbnRPZmZzZXRDAAAAJD8AAAAnCkB0eXBlAAAAYQcAtuMDcm1vZHVsZXMtZXZlbnRzOkFJUkxJTkVJTlRFR1JJVFlDSEVDS0hPUklaT05TVUJTQ1JJUFRJT046MAJk 
2016-10-11 05:26:00.011 [kafka-consumer-modules-events-E615E245-8C68-11E6-AFC0-0050568B6471-admin-service-0] ERROR c.l.p.u.e.ExceptionLoggingExecutorService - Exception caught during run
java.lang.NullPointerException: null
2016-10-11 05:26:00.022 [kafka-consumer-modules-events-E616F3BA-8C68-11E6-AFC0-0050568B6471-admin-service-0] ERROR c.l.p.u.e.ExceptionLoggingExecutorService - Exception caught during run
java.lang.NullPointerException: null
2016-10-11 05:26:00.012 [kafka-consumer-modules-events-E618052D-8C68-11E6-AFC0-0050568B6471-admin-service-0] WARN  c.o.o.c.s.s.r.b.ORecordSerializerBinary - Error deserializing record to get field-names, send this data for debugging: ABhPcmllbnRPZmZzZXRDAAAAJD8AAAAnCkB0eXBlAAAAXQcAtuMDam1vZHVsZXMtZXZlbnRzOlNFQ1VSSVRZUkVBRE1PREVMSE9SSVpPTlNVQlNDUklQVElPTjowAmQ= 
2016-10-11 05:26:00.023 [kafka-consumer-modules-events-E618052D-8C68-11E6-AFC0-0050568B6471-admin-service-0] ERROR c.l.p.u.e.ExceptionLoggingExecutorService - Exception caught during run
java.lang.NullPointerException: null
2016-10-11 05:26:00.012 [kafka-consumer-modules-events-E616A599-8C68-11E6-AFC0-0050568B6471-admin-service-0] WARN  c.o.o.c.s.s.r.b.ORecordSerializerBinary - Error deserializing record to get field-names, send this data for debugging: ABhPcmllbnRPZmZzZXRDAAAAJD8AAAAnCkB0eXBlAAAAWgcAtuMDZG1vZHVsZXMtZXZlbnRzOkZMRUVUUkVBRE1PREVMSE9SSVpPTlNVQlNDUklQVElPTjowAmQ= 
2016-10-11 05:26:00.023 [kafka-consumer-modules-events-E616A599-8C68-11E6-AFC0-0050568B6471-admin-service-0] ERROR c.l.p.u.e.ExceptionLoggingExecutorService - Exception caught during run
java.lang.NullPointerException: null
2016-10-11 05:26:00.012 [kafka-consumer-modules-events-E61F582E-8C68-11E6-AFC0-0050568B6471-admin-service-0] WARN  c.o.o.c.s.s.r.b.ORecordSerializerBinary - Error deserializing record to get field-names, send this data for debugging: ABhPcmllbnRPZmZzZXRDAAAAJD8AAAAnCkB0eXBlAAAAXgcAtuMDbG1vZHVsZXMtZXZlbnRzOlNFQ1VSSVRZV1JJVEVNT0RFTEhPUklaT05TVUJTQ1JJUFRJT046MAJk 
2016-10-11 05:26:00.012 [kafka-consumer-modules-events-E62090B3-8C68-11E6-AFC0-0050568B6471-admin-service-0] WARN  c.o.o.c.s.s.r.b.ORecordSerializerBinary - Error deserializing record to get field-names, send this data for debugging: ABhPcmllbnRPZmZzZXRDAAAAJD8AAAAnCkB0eXBlAAAAWwcAtuMDZm1vZHVsZXMtZXZlbnRzOkZMRUVUV1JJVEVNT0RFTEhPUklaT05TVUJTQ1JJUFRJT046MAJk 
2016-10-11 05:26:00.023 [kafka-consumer-modules-events-E61F582E-8C68-11E6-AFC0-0050568B6471-admin-service-0] ERROR c.l.p.u.e.ExceptionLoggingExecutorService - Exception caught during run
java.lang.NullPointerException: null
2016-10-11 05:26:00.023 [kafka-consumer-modules-events-E62090B3-8C68-11E6-AFC0-0050568B6471-admin-service-0] ERROR c.l.p.u.e.ExceptionLoggingExecutorService - Exception caught during run
java.lang.NullPointerException: null
2016-10-11 05:26:00.023 [kafka-consumer-modules-events-E616F3BA-8C68-11E6-AFC0-0050568B6471-admin-service-0] WARN  c.o.o.c.s.s.r.b.ORecordSerializerBinary - Error deserializing record to get field-names, send this data for debugging: ABhPcmllbnRPZmZzZXRDAAAAJD8AAAAnCkB0eXBlAAAAYQcAtuMDcm1vZHVsZXMtZXZlbnRzOkFJUkxJTkVJTlRFR1JJVFlDSEVDS0hPUklaT05TVUJTQ1JJUFRJT046MAJk 
2016-10-11 05:26:00.023 [kafka-consumer-modules-events-E616F3BA-8C68-11E6-AFC0-0050568B6471-admin-service-0] ERROR c.l.p.u.e.ExceptionLoggingExecutorService - Exception caught during run
java.lang.NullPointerException: null
2016-10-11 05:26:00.012 [kafka-consumer-modules-events-E61FF46F-8C68-11E6-AFC0-0050568B6471-admin-service-0] WARN  c.o.o.c.s.s.r.b.ORecordSerializerBinary - Error deserializing record to get field-names, send this data for debugging: ABhPcmllbnRPZmZzZXRDAAAAJD8AAAAnCkB0eXBlAAAAWgcAtuMDZG1vZHVsZXMtZXZlbnRzOkFJUkxJTkVBREFQVEVSSE9SSVpPTlNVQlNDUklQVElPTjowAmQ= 
2016-10-11 05:26:00.023 [kafka-consumer-modules-events-E61FF46F-8C68-11E6-AFC0-0050568B6471-admin-service-0] ERROR c.l.p.u.e.ExceptionLoggingExecutorService - Exception caught during run
java.lang.NullPointerException: null
2016-10-11 05:26:00.023 [kafka-consumer-modules-events-E615E245-8C68-11E6-AFC0-0050568B6471-admin-service-0] WARN  c.o.o.c.s.s.r.b.ORecordSerializerBinary - Error deserializing record to get field-names, send this data for debugging: ABhPcmllbnRPZmZzZXRDAAAAJD8AAAAnCkB0eXBlAAAAWAcAtuMDYG1vZHVsZXMtZXZlbnRzOkZMRUVUQURBUFRFUkhPUklaT05TVUJTQ1JJUFRJT046MAJk 
2016-10-11 05:26:00.023 [kafka-consumer-modules-events-E615E245-8C68-11E6-AFC0-0050568B6471-admin-service-0] ERROR c.l.p.u.e.ExceptionLoggingExecutorService - Exception caught during run
java.lang.NullPointerException: null
2016-10-11 05:26:00.012 [kafka-consumer-modules-events-E6167E88-8C68-11E6-AFC0-0050568B6471-admin-service-0] WARN  c.o.o.c.s.s.r.b.ORecordSerializerBinary - Error deserializing record to get field-names, send this data for debugging: ABhPcmllbnRPZmZzZXRDAAAAJD8AAAAnCkB0eXBlAAAAbwcAtuMDjAFtb2R1bGVzLWV2ZW50czpGTEVFVEFEQVBURVJTVUJGTEVFVEdST1VQSU5URUdSSVRZSE9SSVpPTlNVQlNDUklQVElPTjowAmQ=

**Comment by tglman** [comment]
hi @smil2k,

This error can happen client side right after the schema is changed server side, i add a fix that reload the schema in this case.

As workaround you can assure that the schema client-side is update with `db.getMetadata().getSchema().reload(); `

Bye

**Comment by smil2k** [comment]
Do you have one central metadata, or this needs to be done per DB instance.

What is the cost of calling this method? Is it safe to call it every minute or so?

**Comment by smil2k** [comment]
Additionally could you please change the serializator code, so that it would throw a meaningful message like: "Field bla not existing in our schema. This might happen if you run with stale metadata."

I can understand, that this is too low level area to trigger a refresh, but I think it does not build trust in your software if a known state honoured with null pointer exceptions. 

Seeing null pointer exceptions in a database code's log is a major red flag!

**Comment by tglman** [comment]
hi @smil2k,

The automatic reload fix is already been done, and as well the exception has been changed in a more meaning full way, this fixes will be released in 2.2.12.

The schema is shared for all the instances of the database, so is enough only a reload after you modified the schema structure, i would not suggest you to add an automatic reload once a while, but do it more targeted following your schema changes, if the schema changed are done by the application, the reload is not needed.

In any case as soon as this fix is shipped, the reload won't be needed anymore.

Regards

**Comment by smil2k** [comment]
Thank you for the explanation. The schema changes were not coming from that application, but a different one.

We will look forward the new 2.2.12 version. 

Cheers,

Tamas
