### ISSUE TITLE
java.lang.NullPointerException: null OSBTree.findBucket

### ISSUE THREAD

**Issue by jamieb22** [orientechnologies/orientdb#6802]
## OrientDB Version, operating system, or hardware.

Orient DB 2.2.11

## Operating System

.19.0-66-generic #74~14.04.1-Ubuntu SMP Tue Jul 19 19:56:11 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

## Expected behavior and actual behavior

A Null pointer exception is generated..

```
java.lang.NullPointerException: null
        at com.orientechnologies.orient.core.index.sbtree.local.OSBTree.findBucket(OSBTree.java:1701)
        at com.orientechnologies.orient.core.index.sbtree.local.OSBTree.get(OSBTree.java:199)
        at com.orientechnologies.orient.core.index.engine.OSBTreeIndexEngine.get(OSBTreeIndexEngine.java:128)
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.doGetIndexValue(OAbstractPaginatedStorage.java:1921)
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.getIndexValue(OAbstractPaginatedStorage.java:1910)
        at com.orientechnologies.orient.core.index.OIndexOneValue.get(OIndexOneValue.java:56)
        at com.orientechnologies.orient.core.index.OIndexOneValue.get(OIndexOneValue.java:40)
        at com.orientechnologies.orient.core.index.OIndexAbstractDelegate.get(OIndexAbstractDelegate.java:58)
        at com.orientechnologies.orient.core.index.OIndexTxAwareOneValue.get(OIndexTxAwareOneValue.java:262)
        at com.orientechnologies.orient.core.index.OIndexTxAwareOneValue.get(OIndexTxAwareOneValue.java:40)
        at com.tinkerpop.blueprints.impls.orient.OrientBaseGraph.getVertices(OrientBaseGraph.java:845)
        at com.stimulus.archiva.hp.f(MailArchiva:367)
        at com.stimulus.archiva.hp.d(MailArchiva:352)
        at com.stimulus.archiva.hp.a(MailArchiva:172)
        at com.stimulus.archiva.database.DatabaseService.a(MailArchiva:446)
        at com.stimulus.archiva.database.DatabaseService.a(MailArchiva:386)
        at com.stimulus.archiva.database.DatabaseService.a(MailArchiva:365)
        at com.stimulus.archiva.pr.b(MailArchiva:652)
        at com.stimulus.archiva.pr.a(MailArchiva:625)
        at com.stimulus.archiva.gn$f.a(MailArchiva:670)
        at com.stimulus.archiva.gn$f.a(MailArchiva:626)
        at com.stimulus.archiva.gn$b.b(MailArchiva:699)
        at com.stimulus.archiva.gn$b.onSuccess(MailArchiva:685)
        at com.google.api.client.googleapis.batch.BatchUnparsedResponse.parseAndCallback(BatchUnparsedResponse.java:197)
        at com.google.api.client.googleapis.batch.BatchUnparsedResponse.parseNextResponse(BatchUnparsedResponse.java:155)
        at com.google.api.client.googleapis.batch.BatchRequest.execute(BatchRequest.java:253)
   ....
```

We are not expecting any null pointer exceptions.

**Comment by taburet** [comment]
Could you please share the corresponding *.sbt index file and the arguments of OrientBaseGraph#getVertices call? Did you use the database in a non-tx mode before this exception arise?

As temporary workaround, please rebuild the index as described [here](http://orientdb.com/docs/2.2.x/SQL-Rebuild-Index.html).

**Comment by taburet** [comment]
Closing because of no reply.
