### ISSUE TITLE
" Restore is not possible because write ahead log is empty." for replica server

### ISSUE THREAD

**Issue by tttlh** [orientechnologies/orientdb#6805]
## OrientDB Version, operating system, or hardware.
- v2.2.8
## Operating System
- [x] Linux
## Cluster

 bbs1: master
 bbs2: replica
## Expected behavior and actual behavior

replica server can't be restored.
## Steps to reproduce the problem

The replica server stopped to work at 1am with some heap size exceptions.

from replica:

``` log
2016-10-13 00:21:39:278 WARNI [bbs2] Timeout (91218ms) on waiting for synchronous responses from nodes=[bbs1] responsesSoFar=[] request=(id=1.27501 task=heartbeat timestamp: 1476288682229) [ODistributedDatabaseImpl]Error on client connection
java.lang.OutOfMemoryError: Java heap space
        at java.io.BufferedInputStream.<init>(BufferedInputStream.java:203)
        at com.orientechnologies.orient.enterprise.channel.binary.OChannelBinaryServer.<init>(OChannelBinaryServer.java:38)
        at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.config(ONetworkProtocolBinary.java:145)
        at com.orientechnologies.orient.server.network.OServerNetworkListener.run(OServerNetworkListener.java:216)
Exception in thread "hz._hzInstance_1_orientdb.SlowOperationDetectorThread" java.lang.OutOfMemoryError: Java heap space

2016-10-13 00:49:16:912 WARNI [bbs2]->[bbs1] Server 'bbs1' did not respond to the heartbeat message (db=GratefulDeadConcerts, timeout=10000ms), but cannot be set OFFLINE by configuration [OClusterHealthChecker]
2016-10-13 00:53:53:021 WARNI [192.168.3.10]:2434 [orientdb] [3.6.3] This node does not have a connection to Member [192.168.1.127]:2434 [ClusterHeartbeatManager]Error during WAL background flush
java.lang.OutOfMemoryError: Java heap space
        at com.orientechnologies.orient.core.storage.impl.local.paginated.wal.OLogSegment.commitLog(OLogSegment.java:170)
        at com.orientechnologies.orient.core.storage.impl.local.paginated.wal.OLogSegment.access$100(OLogSegment.java:33)
        at com.orientechnologies.orient.core.storage.impl.local.paginated.wal.OLogSegment$FlushTask.run(OLogSegment.java:138)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)

```

from master:

``` log
2016-10-13 00:09:03:632 WARNI Cannot serialize record: #-2:338{uid:8214636,rcount:25} v0 [ONetworkProtocolBinary]
2016-10-13 00:09:03:632 WARNI Cannot serialize record: #-2:863{uid:7993040,rcount:25} v0 [ONetworkProtocolBinary]
2016-10-13 00:09:03:632 WARNI Cannot serialize record: #-2:16953{uid:7894288,rcount:25} v0 [ONetworkProtocolBinary]Error on unmarshalling record #-2:935 (java.net.SocketException: Broken pipe)
java.net.SocketException: Broken pipe
        at java.net.SocketOutputStream.socketWrite0(Native Method)
        at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:109)
        at java.net.SocketOutputStream.write(SocketOutputStream.java:153)
        at java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:82)
        at java.io.BufferedOutputStream.write(BufferedOutputStream.java:126)
        at java.io.DataOutputStream.write(DataOutputStream.java:107)
        at com.orientechnologies.orient.enterprise.channel.binary.OChannelBinary.writeBytes(OChannelBinary.java:276)
        at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.writeRecord(ONetworkProtocolBinary.java:2845)
        at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.writeIdentifiable(ONetworkProtocolBinary.java:2629)
        at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.serializeValue(ONetworkProtocolBinary.java:1597)
        at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.command(ONetworkProtocolBinary.java:1542)
        at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.executeRequest(ONetworkProtocolBinary.java:579)
        at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.sessionRequest(ONetworkProtocolBinary.java:320)
        at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.execute(ONetworkProtocolBinary.java:196)
        at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:77)

2016-10-13 00:09:05:701 WARNI Cannot serialize record: #-2:935{uid:22241241,rcount:40} v0 [ONetworkProtocolBinary]
2016-10-13 00:09:05:701 WARNI Cannot serialize record: #-2:240{uid:21491041,rcount:40} v0 [ONetworkProtocolBinary]
2016-10-13 00:09:05:701 WARNI Cannot serialize record: #-2:905{uid:19333566,rcount:40} v0 [ONetworkProtocolBinary]
2016-10-13 00:10:46:771 WARNI [bbs1] Timeout (10039ms) on waiting for synchronous responses from nodes=[bbs2] responsesSoFar=[] request=(id=0.79344 task=heartbeat timestamp: 1476288636731) [ODistributedDatabaseImpl]
2016-10-13 00:10:46:772 WARNI [bbs1]->[bbs2] Server 'bbs2' did not respond to the heartbeat message (db=GratefulDeadConcerts, timeout=10000ms), but cannot be set OFFLINE by configuration [OClusterHealthChecker]
2016-10-13 00:10:56:772 WARNI [bbs1]->[bbs2] Server 'bbs2' did not respond to the heartbeat message (db=mysns, timeout=10000ms), but cannot be set OFFLINE by configuration [OClusterHealthChecker]
2016-10-13 00:11:08:903 WARNI [bbs1]->[bbs2] Server 'bbs2' did not respond to the heartbeat message (db=GratefulDeadConcerts, timeout=10000ms), but cannot be set OFFLINE by configuration [OClusterHealthChecker]
2016-10-13 00:11:18:903 WARNI [bbs1]->[bbs2] Server 'bbs2' did not respond to the heartbeat message (db=mysns, timeout=10000ms), but cannot be set OFFLINE by configuration [OClusterHealthChecker]
2016-10-13 00:11:36:901 WARNI [bbs1]->[bbs2] Server 'bbs2' did not respond to the heartbeat message (db=GratefulDeadConcerts, timeout=10000ms), but cannot be set OFFLINE by configuration [OClusterHealthChecker]
2016-10-13 00:11:46:901 WARNI [bbs1]->[bbs2] Server 'bbs2' did not respond to the heartbeat message (db=mysns, timeout=10000ms), but cannot be set OFFLINE by configuration [OClusterHealthChecker]

```

Then when I restart the master and then restart the replica, I got this
from replica:

``` log
2016-10-13 11:16:10:268 WARNI [bbs2]->[[bbs1]] Requesting deploy of database 'mysns' on local server... [OHazelcastPlugin]
2016-10-13 11:16:13:431 WARNI [bbs2] Moving existent database 'mysns' in '/usr/local/orientdb-community-2.2.8/databases/mysns' to '/usr/local/orientdb-community-2.2.8/databases//../backup/databases/mysns' and get a fresh copy from a remote node... [OHazelcastPlugin]
2016-10-13 11:17:29:448 WARNI {db=mysns} Storage 'mysns' was not closed properly. Will try to recover from write ahead log [OLocalPaginatedStorage]
2016-10-13 11:17:29:449 SEVER {db=mysns} Restore is not possible because write ahead log is empty. [OLocalPaginatedStorage]
2016-10-13 11:17:31:482 WARNI {db=mysns} Database is open by another process [OPaginatedStorageDirtyFlag]
2016-10-13 11:17:31:638 WARNI {db=mysns} MBean with name com.orientechnologies.orient.core.storage.impl.local.paginated.atomicoperations:id=1278582676,name="mysns",type=OAtomicOperationsMangerMXBean has already registered. Probably your system was not shutdown correctly or you have several running applications which use OrientDB engine inside [OAtomicOperationsManager]
2016-10-13 11:17:31:639 WARNI {db=mysns} Storage 'mysns' was not closed properly. Will try to recover from write ahead log [OLocalPaginatedStorage]
2016-10-13 11:17:31:639 SEVER {db=mysns} Restore is not possible because write ahead log is empty. [OLocalPaginatedStorage]
2016-10-13 11:17:33:994 WARNI {db=mysns} Database is open by another process [OPaginatedStorageDirtyFlag]
2016-10-13 11:17:34:015 WARNI {db=mysns} MBean with name com.orientechnologies.orient.core.storage.impl.local.paginated.atomicoperations:id=1278582676,name="mysns",type=OAtomicOperationsMangerMXBean has already registered. Probably your system was not shutdown correctly or you have several running applications which use OrientDB engine inside [OAtomicOperationsManager]
2016-10-13 11:17:34:015 WARNI {db=mysns} Storage 'mysns' was not closed properly. Will try to recover from write ahead log [OLocalPaginatedStorage]
2016-10-13 11:17:34:016 SEVER {db=mysns} Restore is not possible because write ahead log is empty. [OLocalPaginatedStorage]
2016-10-13 11:17:38:982 WARNI {db=mysns} Database is open by another process [OPaginatedStorageDirtyFlag]
2016-10-13 11:17:39:161 WARNI {db=mysns} MBean with name com.orientechnologies.orient.core.storage.impl.local.paginated.atomicoperations:id=1278582676,name="mysns",type=OAtomicOperationsMangerMXBean has already registered. Probably your system was not shutdown correctly or you have several running applications which use OrientDB engine inside [OAtomicOperationsManager]
2016-10-13 11:17:39:162 WARNI {db=mysns} Storage 'mysns' was not closed properly. Will try to recover from write ahead log [OLocalPaginatedStorage]
2016-10-13 11:17:39:162 SEVER {db=mysns} Restore is not possible because write ahead log is empty. [OLocalPaginatedStorage]
2016-10-13 11:17:40:228 WARNI {db=mysns} Database is open by another process [OPaginatedStorageDirtyFlag]
2016-10-13 11:17:40:256 WARNI {db=mysns} MBean with name com.orientechnologies.orient.core.storage.impl.local.paginated.atomicoperations:id=1278582676,name="mysns",type=OAtomicOperationsMangerMXBean has already registered. Probably your system was not shutdown correctly or you have several running applications which use OrientDB engine inside [OAtomicOperationsManager]

```

from master:

``` log
2016-10-13 11:17:23:082 INFO  [bbs1]->[bbs2] - transferring chunk #47 offset=192933888 size=8384701... [OCopyDatabaseChunkTask]
2016-10-13 11:17:24:057 WARNI [bbs1]->[bbs2] Server 'bbs2' did not respond to the heartbeat message (db=GratefulDeadConcerts, timeout=10000ms), but cannot be set OFFLINE by configuration [OClusterHealthChecker]
2016-10-13 11:17:24:691 INFO  [bbs1]->[bbs2] - transferring chunk #48 offset=201318589 size=3907... [OCopyDatabaseChunkTask]
2016-10-13 11:17:24:698 INFO  [bbs1]->[bbs2] - transferring chunk #49 offset=201322496 size=8384605... [OCopyDatabaseChunkTask]
2016-10-13 11:17:28:341 INFO  [bbs1]->[bbs2] - transferring chunk #50 offset=209707101 size=4003... [OCopyDatabaseChunkTask]
2016-10-13 11:17:28:500 INFO  [bbs1]->[bbs2] - transferring chunk #51 offset=209711104 size=8384235... [OCopyDatabaseChunkTask]
2016-10-13 11:17:31:162 INFO  [bbs1]->[bbs2] - transferring chunk #52 offset=218095339 size=277... [OCopyDatabaseChunkTask]
2016-10-13 11:17:31:169 INFO  [bbs1]->[bbs2] - transferring chunk #53 offset=218095616 size=8387903... [OCopyDatabaseChunkTask]
2016-10-13 11:17:33:504 INFO  [bbs1]->[bbs2] - transferring chunk #54 offset=226483519 size=705... [OCopyDatabaseChunkTask]
2016-10-13 11:17:33:511 INFO  [bbs1]->[bbs2] - transferring chunk #55 offset=226484224 size=8387453... [OCopyDatabaseChunkTask]
2016-10-13 11:17:34:062 WARNI [bbs1]->[bbs2] Server 'bbs2' did not respond to the heartbeat message (db=GratefulDeadConcerts, timeout=10000ms), but cannot be set OFFLINE by configuration [OClusterHealthChecker]
2016-10-13 11:17:36:483 INFO  [bbs1]->[bbs2] - transferring chunk #56 offset=234871677 size=1155... [OCopyDatabaseChunkTask]
2016-10-13 11:17:36:490 INFO  [bbs1]->[bbs2] - transferring chunk #57 offset=234872832 size=8387282... [OCopyDatabaseChunkTask]
2016-10-13 11:17:39:680 INFO  [bbs1]->[bbs2] - transferring chunk #58 offset=243260114 size=1326... [OCopyDatabaseChunkTask]
2016-10-13 11:17:39:688 INFO  [bbs1]->[bbs2] - transferring chunk #59 offset=243261440 size=8386832... [OCopyDatabaseChunkTask]
2016-10-13 11:17:42:678 INFO  [bbs1]->[bbs2] - transferring chunk #60 offset=251648272 size=1776... [OCopyDatabaseChunkTask]
2016-10-13 11:17:42:686 INFO  [bbs1]->[bbs2] - transferring chunk #61 offset=251650048 size=8386506... [OCopyDatabaseChunkTask]
2016-10-13 11:17:44:065 WARNI [bbs1]->[bbs2] Server 'bbs2' did not respond to the heartbeat message (db=GratefulDeadConcerts, timeout=10000ms), but cannot be set OFFLINE by configuration [OClusterHealthChecker]
2016-10-13 11:17:45:494 INFO  [bbs1]->[bbs2] - transferring chunk #62 offset=260036554 size=2102... [OCopyDatabaseChunkTask]
2016-10-13 11:17:45:501 INFO  [bbs1]->[bbs2] - transferring chunk #63 offset=260038656 size=8386345... [OCopyDatabaseChunkTask]
2016-10-13 11:17:48:672 INFO  [bbs1]->[bbs2] - transferring chunk #64 offset=268425001 size=2263... [OCopyDatabaseChunkTask]
2016-10-13 11:17:48:679 INFO  [bbs1]->[bbs2] - transferring chunk #65 offset=268427264 size=8385931... [OCopyDatabaseChunkTask]
2016-10-13 11:17:48:765 INFO  [bbs1]->[bbs2] Backup of database 'mysns' completed. lastOperationId=1.3... [OSyncDatabaseTask$1]
2016-10-13 11:17:48:777 INFO  [bbs1]->[bbs2] - transferring chunk #66 offset=276813195 size=454562... [OCopyDatabaseChunkTask]
2016-10-13 11:17:48:778 INFO  [bbs1] Received updated status bbs1.mysns=ONLINE [OHazelcastPlugin]
2016-10-13 11:18:14:133 WARNI [bbs1] Timeout (30063ms) on waiting for synchronous responses from nodes=[bbs2] responsesSoFar=[] request=(id=0.72 task=heartbeat timestamp: 1476328664070) [ODistributedDatabaseImpl]
2016-10-13 11:18:14:133 WARNI [bbs1]->[bbs2] Server 'bbs2' did not respond to the heartbeat message (db=GratefulDeadConcerts, timeout=10000ms), but cannot be set OFFLINE by configuration [OClusterHealthChecker]
2016-10-13 11:18:14:136 INFO  [bbs1] Distributed servers status:

+-----+--------+------------------------------------+-----+---------+----------------+----------------+-----------------------+
|Name |Status  |Databases                           |Conns|StartedOn|Binary          |HTTP            |UsedMemory             |
+-----+--------+------------------------------------+-----+---------+----------------+----------------+-----------------------+
|bbs1*|ONLINE  |GratefulDeadConcerts=ONLINE (MASTER)|104  |11:15:41 |192.168.1.127:2424|192.168.1.127:2480|2.38GB/5.71GB (41.76%) |
|     |        |mysns=ONLINE (MASTER)             |     |         |                |                |                       |
|bbs2 |STARTING|                                    |0    |11:15:58 |192.168.3.10:2424 |192.168.3.10:2480 |405.33MB/5.44GB (7.28%)|
+-----+--------+------------------------------------+-----+---------+----------------+----------------+-----------------------+
 [OHazelcastPlugin]
2016-10-13 11:20:34:845 WARNI [bbs1]->[bbs2] Server 'bbs2' did not respond to the heartbeat message (db=GratefulDeadConcerts, timeout=10000ms), but cannot be set OFFLINE by configuration [OClusterHealthChecker]Error on unmarshalling record #-2:968 (java.net.SocketException: Broken pipe)
java.net.SocketException: Broken pipe
        at java.net.SocketOutputStream.socketWrite0(Native Method)
        at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:109)
        at java.net.SocketOutputStream.write(SocketOutputStream.java:153)
        at java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:82)
        at java.io.BufferedOutputStream.write(BufferedOutputStream.java:126)
        at java.io.DataOutputStream.write(DataOutputStream.java:107)
        at com.orientechnologies.orient.enterprise.channel.binary.OChannelBinary.writeBytes(OChannelBinary.java:276)
        at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.writeRecord(ONetworkProtocolBinary.java:2845)
        at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.writeIdentifiable(ONetworkProtocolBinary.java:2629)
        at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.serializeValue(ONetworkProtocolBinary.java:1597)
        at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.command(ONetworkProtocolBinary.java:1542)
        at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.executeRequest(ONetworkProtocolBinary.java:579)
        at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.sessionRequest(ONetworkProtocolBinary.java:320)
        at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.execute(ONetworkProtocolBinary.java:196)
        at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:77)

2016-10-13 11:21:07:318 WARNI Cannot serialize record: #-2:968{uid:17133217,rcount:41} v0 [ONetworkProtocolBinary]
2016-10-13 11:21:07:319 WARNI Cannot serialize record: #-2:4376{uid:12905248,rcount:41} v0 [ONetworkProtocolBinary]
2016-10-13 11:22:01:089 INFO  [192.168.1.127]:2434 [orientdb] [3.6.3] Connection [Address[192.168.3.10]:2434] lost. Reason: java.io.EOFException[Remote socket closed!] [TcpIpConnection]
2016-10-13 11:22:01:090 WARNI [192.168.1.127]:2434 [orientdb] [3.6.3] hz._hzInstance_1_orientdb.IO.thread-in-0 Closing socket to endpoint Address[192.168.3.10]:2434, Cause:java.io.EOFException: Remote socket closed! [NonBlockingSocketReader]
2016-10-13 11:22:01:531 INFO  [192.168.1.127]:2434 [orientdb] [3.6.3] Connecting to /192.168.3.10:2434, timeout: 0, bind-any: false [InitConnectionTask]
2016-10-13 11:22:01:532 INFO  [192.168.1.127]:2434 [orientdb] [3.6.3] Could not connect to: /192.168.3.10:2434. Reason: SocketException[Connection refused to address /192.168.3.10:2434] [InitConnectionTask]
2016-10-13 11:22:06:458 WARNI [bbs1]->[bbs2] Error on sending message to distributed node (java.net.SocketException: Connection reset) retrying (1/3) [ORemoteServerChannel]
2016-10-13 11:22:06:459 WARNI [bbs1]->[bbs2] Error on reconnecting to distributed node (java.net.ConnectException: Connection refused) [ORemoteServerChannel]
2016-10-13 11:22:06:459 WARNI [bbs1]->[bbs2] Error on sending message to distributed node (java.net.SocketException: Socket closed) retrying (2/3) [ORemoteServerChannel]
2016-10-13 11:22:06:531 INFO  [192.168.1.127]:2434 [orientdb] [3.6.3] Connecting to /192.168.3.10:2434, timeout: 0, bind-any: false [InitConnectionTask]
2016-10-13 11:22:06:531 INFO  [192.168.1.127]:2434 [orientdb] [3.6.3] Could not connect to: /192.168.3.10:2434. Reason: SocketException[Connection refused to address /192.168.3.10:2434] [InitConnectionTask]
2016-10-13 11:22:06:860 WARNI [bbs1]->[bbs2] Error on reconnecting to distributed node (java.net.ConnectException: Connection refused) [ORemoteServerChannel]
2016-10-13 11:22:06:860 WARNI [bbs1]->[bbs2] Error on sending message to distributed node (java.net.SocketException: Socket closed) retrying (3/3) [ORemoteServerChannel]
2016-10-13 11:22:07:461 WARNI [bbs1]->[bbs2] Error on reconnecting to distributed node (java.net.ConnectException: Connection refused) [ORemoteServerChannel]
2016-10-13 11:22:07:463 WARNI [bbs1]->[bbs2] Error on sending message to distributed node (java.net.SocketException: Socket closed) retrying (1/3) [ORemoteServerChannel]
2016-10-13 11:22:07:463 SEVER [bbs1]->[bbs2] Error on sending distributed request id=0.210 task=tx user=#5:0 (Connection refused). Active nodes: [bbs1, bbs2] [ODistributedDatabaseImpl]
2016-10-13 11:22:07:463 WARNI [bbs1]->[bbs2] Error on reconnecting to distributed node (java.net.ConnectException: Connection refused) [ORemoteServerChannel]
2016-10-13 11:22:07:463 INFO  [192.168.1.127]:2434 [orientdb] [3.6.3] Connecting to /192.168.3.10:2434, timeout: 0, bind-any: false [InitConnectionTask]
2016-10-13 11:22:07:463 WARNI [bbs1]->[bbs2] Error on sending message to distributed node (java.net.SocketException: Socket closed) retrying (2/3) [ORemoteServerChannel]
2016-10-13 11:22:07:464 INFO  [192.168.1.127]:2434 [orientdb] [3.6.3] Could not connect to: /192.168.3.10:2434. Reason: SocketException[Connection refused to address /192.168.3.10:2434] [InitConnectionTask]
2016-10-13 11:22:07:464 WARNI [192.168.1.127]:2434 [orientdb] [3.6.3] Removing connection to endpoint Address[192.168.3.10]:2434 Cause => java.net.SocketException {Connection refused to address /192.168.3.10:2434}, Error-Count: 5 [TcpIpConnectionMonitor]
2016-10-13 11:22:07:465 INFO  [192.168.1.127]:2434 [orientdb] [3.6.3] Removing Member [192.168.3.10]:2434 [ClusterService]
2016-10-13 11:22:07:465 INFO  [192.168.1.127]:2434 [orientdb] [3.6.3] Connecting to /192.168.3.10:2434, timeout: 0, bind-any: false [InitConnectionTask]
2016-10-13 11:22:07:465 INFO  [192.168.1.127]:2434 [orientdb] [3.6.3] Removing Member [192.168.3.10]:2434 [InternalPartitionService]
```

**Comment by taburet** [comment]
Hi! What is the max heap size (-Xmx) setting for the replica server?

**Comment by tttlh** [comment]
heap size: -Xms5g -Xmx6g 
database： 1.4G

**Comment by taburet** [comment]
Could you please capture a heap dump of the replica server, when OOMs start to appear?

**Comment by taburet** [comment]
@tttlh is it still happening? The most probable cause of OOMs are some very large queries, if there are many such queries running in parallel they could easily eat all available heap.

**Comment by taburet** [comment]
Closing because of no reply.
