### ISSUE TITLE
OrientJdbcResultSet.getBoolean error

### ISSUE THREAD

**Issue by vsspt** [orientechnologies/orientdb#6814]
## OrientDB Version, operating system, or hardware.
- v2.2.10, v2.2.11

## Operating System
- [x ] Windows 8

## JVM
- 1.8.0_101-b13

## Framework
- Spring 4.3.2

## Expected behavior and actual behavior
- OrientJdbcResultSet.getBoolean should be able to obtain Boolean column Values.
- Instead, an UncategorizedSQLException is raised.

## Steps to reproduce the problem

1. Use a table with a Boolean datatype.
2. Create a Bean extending org.springframework.jdbc.core.support.JdbcDaoSupport
3. Execute a getJdbcTemplate().queryForObject for a Boolean object

# Java code
```java
public class TestDAO extends JdbcDaoSupport{

	private static final String DML = "select B_VAL from TABLE_TEST";
	
	public void dummySelect(){
		getJdbcTemplate().queryForObject(DML, Boolean.class);
	}
}
```

# Raised error
```
org.springframework.jdbc.UncategorizedSQLException: StatementCallback; uncategorized SQLException for SQL [select B_VAL from TABLE_TEST]; SQL state [null]; error code [0]; An error occurred during the retrieval of the boolean value at column 'B' ---> {"@type":"d","@rid":"#-2:0","@version":0,"B_VAL":false}; nested exception is java.sql.SQLException: An error occurred during the retrieval of the boolean value at column 'B' ---> {"@type":"d","@rid":"#-2:0","@version":0,"B_VAL":false}
	at com.orientechnologies.orient.jdbc.OrientJdbcResultSet.getBoolean(OrientJdbcResultSet.java:362)
	at com.orientechnologies.orient.jdbc.OrientJdbcResultSet.getBoolean(OrientJdbcResultSet.java:356)
	at org.springframework.jdbc.support.JdbcUtils.getResultSetValue(JdbcUtils.java:151)
	at org.springframework.jdbc.core.SingleColumnRowMapper.getColumnValue(SingleColumnRowMapper.java:130)
	at org.springframework.jdbc.core.SingleColumnRowMapper.mapRow(SingleColumnRowMapper.java:96)
	at org.springframework.jdbc.core.RowMapperResultSetExtractor.extractData(RowMapperResultSetExtractor.java:93)
	at org.springframework.jdbc.core.RowMapperResultSetExtractor.extractData(RowMapperResultSetExtractor.java:60)
	at org.springframework.jdbc.core.JdbcTemplate$1QueryStatementCallback.doInStatement(JdbcTemplate.java:459)
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:404)
	at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:470)
	at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:480)
	at org.springframework.jdbc.core.JdbcTemplate.queryForObject(JdbcTemplate.java:490)
	at org.springframework.jdbc.core.JdbcTemplate.queryForObject(JdbcTemplate.java:496)
```

**Comment by robfrank** [comment]
I've corrected the behaviour in case of fields with the underscore inside the name. Tests are all green on 2.2.x and develop and will be included in next 2.2.12 release
