### ISSUE TITLE
./dserver.sh not working on AWS EC2

### ISSUE THREAD

**Issue by prakhar21** [orientechnologies/orientdb#6819]
`
2016-10-17 12:16:40:314 INFO  [172.31.30.166]:2434 [orientdb] [3.6.5] Copyright (c) 2008-2016, Hazelcast, Inc. All Rights Reserved. [system]
2016-10-17 12:16:40:314 INFO  [172.31.30.166]:2434 [orientdb] [3.6.5] Configured Hazelcast Serialization version : 1 [system]
2016-10-17 12:16:40:482 INFO  [172.31.30.166]:2434 [orientdb] [3.6.5] Backpressure is disabled [OperationService]
2016-10-17 12:16:40:505 INFO  [172.31.30.166]:2434 [orientdb] [3.6.5] Starting with 1 generic operation threads and 1 partition operation threads. [ClassicOperationExecutor]
2016-10-17 12:16:40:822 INFO  [172.31.30.166]:2434 [orientdb] [3.6.5] Creating AWSJoiner [Node]
2016-10-17 12:16:40:827 INFO  [172.31.30.166]:2434 [orientdb] [3.6.5] Address[172.31.30.166]:2434 is STARTING [LifecycleService]
2016-10-17 12:16:40:902 INFO  [172.31.30.166]:2434 [orientdb] [3.6.5] TcpIpConnectionManager configured with Non Blocking IO-threading model: 3 input threads and 3 output threads [NonBlockingIOThreadingModel][172.31.30.166]:2434 [orientdb] [3.6.5] ec2.us-west-1b.amazonaws.com
java.net.UnknownHostException: ec2.us-west-1b.amazonaws.com
    at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:178)
    at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
    at java.net.Socket.connect(Socket.java:579)
    at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:635)
    at sun.security.ssl.BaseSSLSocketImpl.connect(BaseSSLSocketImpl.java:160)
    at sun.net.NetworkClient.doConnect(NetworkClient.java:180)
    at sun.net.www.http.HttpClient.openServer(HttpClient.java:432)
    at sun.net.www.http.HttpClient.openServer(HttpClient.java:527)
    at sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:264)
    at sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:367)
    at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:191)
    at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:934)
    at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:177)
    at sun.net.www.protocol.https.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:153)
    at com.hazelcast.aws.impl.DescribeInstances.callService(DescribeInstances.java:158)
    at com.hazelcast.aws.impl.DescribeInstances.execute(DescribeInstances.java:144)
    at com.hazelcast.aws.AWSClient.getPrivateIpAddresses(AWSClient.java:53)
    at com.hazelcast.cluster.impl.TcpIpJoinerOverAWS.getMembers(TcpIpJoinerOverAWS.java:42)
    at com.hazelcast.cluster.impl.TcpIpJoiner.getPossibleAddresses(TcpIpJoiner.java:399)
    at com.hazelcast.cluster.impl.TcpIpJoiner.joinViaPossibleMembers(TcpIpJoiner.java:126)
    at com.hazelcast.cluster.impl.TcpIpJoiner.doJoin(TcpIpJoiner.java:84)
    at com.hazelcast.cluster.impl.AbstractJoiner.join(AbstractJoiner.java:103)
    at com.hazelcast.instance.Node.join(Node.java:582)
    at com.hazelcast.instance.Node.start(Node.java:339)
    at com.hazelcast.instance.HazelcastInstanceImpl.<init>(HazelcastInstanceImpl.java:131)
    at com.hazelcast.instance.HazelcastInstanceFactory.constructHazelcastInstance(HazelcastInstanceFactory.java:160)
    at com.hazelcast.instance.HazelcastInstanceFactory.newHazelcastInstance(HazelcastInstanceFactory.java:143)
    at com.hazelcast.instance.HazelcastInstanceFactory.newHazelcastInstance(HazelcastInstanceFactory.java:111)
    at com.hazelcast.core.Hazelcast.newHazelcastInstance(Hazelcast.java:58)
    at com.orientechnologies.orient.server.hazelcast.OHazelcastPlugin.configureHazelcast(OHazelcastPlugin.java:581)
    at com.orientechnologies.orient.server.hazelcast.OHazelcastPlugin.startup(OHazelcastPlugin.java:144)
    at com.orientechnologies.orient.server.OServer.registerPlugins(OServer.java:1208)
    at com.orientechnologies.orient.server.OServer.activate(OServer.java:391)
    at com.orientechnologies.orient.server.OServerMain.main(OServerMain.java:41)
`

**I have added the below chunk in my `hazelcast.xml`**
`
<aws enabled="true">
                                <access-key>{{key}}</access-key>
                                <secret-key>{{secret}}</secret-key>
                                <region>{{region}}</region>
                                <host-header>ec2.amazonaws.com</host-header>
                                <security-group-name>{{group}}</security-group-name>
</aws>
`

Please, let me know the porblem.

**Comment by madama** [comment]
The used IAM user has the ec2-describe-instances permission? In order to do a discovery hazelcast 'scan' the other ec2 instance to figure out which are in the same security-group.

**Comment by G4br13l3** [comment]
Hi @prakhar21, any update on the issue?

**Comment by santo-it** [comment]
Hi,

I am closing this for lack of feedback. If you have any additional details, please comment and we will reopen the issue

Please test with latest available version first, and specify as many details as possible on how to reproduce the issue

Many thanks,
