### ISSUE TITLE
Error transforming record ... to JSON

### ISSUE THREAD

**Issue by rdelangh** [orientechnologies/orientdb#6847]
## OrientDB Version, operating system, or hardware.
- v2.2.12 SNAPSHOT 20161019
## Operating System
- [x] Linux

Yesterday I had a program running which is loading tons of records in classes. At the same time I launched some queries against these classes, and noticed that these queries did not return any result even after some hours ...
So I suspected already that again something was not going right in the server: found this morning that the server does not accept any connections (from console, from web gui, from REST API).
The logs contain this : 

```
$ANSI{green {db=cdrarch}} Error transforming record #-2:130 to JSON
java.lang.ArrayIndexOutOfBoundsException: 8217
        at com.orientechnologies.orient.server.network.protocol.http.OChunkedResponse.write(OChunkedResponse.java:37)
        at java.io.OutputStream.write(OutputStream.java:116)
        at sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:221)
        at sun.nio.cs.StreamEncoder.implWrite(StreamEncoder.java:282)
        at sun.nio.cs.StreamEncoder.write(StreamEncoder.java:125)
        at sun.nio.cs.StreamEncoder.write(StreamEncoder.java:135)
        at java.io.OutputStreamWriter.write(OutputStreamWriter.java:220)
        at java.io.Writer.write(Writer.java:157)
        at java.io.Writer.append(Writer.java:227)
        at com.orientechnologies.orient.server.network.protocol.http.OHttpResponse.formatMultiValue(OHttpResponse.java:415)
        at com.orientechnologies.orient.server.network.protocol.http.OHttpResponse.writeRecordsOnStream(OHttpResponse.java:362
)
        at com.orientechnologies.orient.server.network.protocol.http.OHttpResponse.access$000(OHttpResponse.java:44)
        at com.orientechnologies.orient.server.network.protocol.http.OHttpResponse$2.call(OHttpResponse.java:337)
        at com.orientechnologies.orient.server.network.protocol.http.OHttpResponse$2.call(OHttpResponse.java:332)
        at com.orientechnologies.orient.server.network.protocol.http.OHttpResponse.sendStream(OHttpResponse.java:507)
        at com.orientechnologies.orient.server.network.protocol.http.OHttpResponse.writeRecords(OHttpResponse.java:332)
        at com.orientechnologies.orient.server.network.protocol.http.OHttpResponse.writeRecords(OHttpResponse.java:248)
        at com.orientechnologies.orient.server.network.protocol.http.command.get.OServerCommandGetQuery.execute(OServerCommand
GetQuery.java:78)
        at com.orientechnologies.orient.server.network.protocol.http.ONetworkProtocolHttpAbstract.service(ONetworkProtocolHttp
Abstract.java:168)
        at com.orientechnologies.orient.server.network.protocol.http.ONetworkProtocolHttpAbstract.execute(ONetworkProtocolHttp
Abstract.java:616)
        at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:77)

java.lang.ArrayIndexOutOfBoundsException: 8218
        at com.orientechnologies.orient.server.network.protocol.http.OChunkedResponse.write(OChunkedResponse.java:37)
        at java.io.OutputStream.write(OutputStream.java:116)
        at sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:221)
        at sun.nio.cs.StreamEncoder.implWrite(StreamEncoder.java:282)
        at sun.nio.cs.StreamEncoder.write(StreamEncoder.java:125)
        at sun.nio.cs.StreamEncoder.write(StreamEncoder.java:135)
        at java.io.OutputStreamWriter.write(OutputStreamWriter.java:220)
        at java.io.Writer.write(Writer.java:157)
        at java.io.Writer.append(Writer.java:227)
        at com.orientechnologies.orient.server.network.protocol.http.OHttpResponse.formatMultiValue(OHttpResponse.java:415)
        at com.orientechnologies.orient.server.network.protocol.http.OHttpResponse.writeRecordsOnStream(OHttpResponse.java:362
)
        at com.orientechnologies.orient.server.network.protocol.http.OHttpResponse.access$000(OHttpResponse.java:44)
        at com.orientechnologies.orient.server.network.protocol.http.OHttpResponse$2.call(OHttpResponse.java:337)
        at com.orientechnologies.orient.server.network.protocol.http.OHttpResponse$2.call(OHttpResponse.java:332)
        at com.orientechnologies.orient.server.network.protocol.http.OHttpResponse.sendStream(OHttpResponse.java:507)
        at com.orientechnologies.orient.server.network.protocol.http.OHttpResponse.writeRecords(OHttpResponse.java:332)
        at com.orientechnologies.orient.server.network.protocol.http.OHttpResponse.writeRecords(OHttpResponse.java:248)
        at com.orientechnologies.orient.server.network.protocol.http.command.get.OServerCommandGetQuery.execute(OServerCommand
GetQuery.java:78)
        at com.orientechnologies.orient.server.network.protocol.http.ONetworkProtocolHttpAbstract.service(ONetworkProtocolHttp
Abstract.java:168)
        at com.orientechnologies.orient.server.network.protocol.http.ONetworkProtocolHttpAbstract.execute(ONetworkProtocolHttp
Abstract.java:616)
        at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:77)
```

and many more of the same kind of messages.

Note the starting line:

```
$ANSI{green {db=cdrarch}} Error transforming record #-2:130 to JSON
```

Isn't the first part of the recordID (#-2) the cluster number ? Is this negative number (-2) normal, or any indication of the problem ?

Seems quite unstable during real workloads, this OrientDB ...

**Comment by rdelangh** [comment]
Server is completely stuck, as it does even not accept any connection anymore to shut it down gracefully :
```
$ bin/shutdown.sh -h orient1.bc -P 2424-2430 -u root -p $ourPwd ;tail -f log/orient-server.log.0
pid file not present or params detected
allowed parameters
-h | --host hostname : name or ip of the host where OrientDB is running. Deafult to localhost
-P | --ports  ports : ports in the form of single value or range. Default to 2424-2430
-p | --password password : the super user password
-u | --user username: the super user name. Default to root
example: shutdown.sh -h orientserver.mydomain -P 2424-2430 -u root -p securePassword
Sending shutdown command to remote OrientDB Server instance...
Oct 26, 2016 10:57:26 AM com.orientechnologies.common.log.OLogManager log
SEVERE: Error on connecting to orient1.bc:2424
com.orientechnologies.orient.enterprise.channel.binary.ONetworkProtocolException: Cannot read protocol version from remote server orient1.bc/10.49.69.190:2424: java.net.SocketTimeoutException: Read timed out
        at com.orientechnologies.orient.client.binary.OChannelBinaryAsynchClient.<init>(OChannelBinaryAsynchClient.java:103)
        at com.orientechnologies.orient.client.binary.OChannelBinaryAsynchClient.<init>(OChannelBinaryAsynchClient.java:71)
        at com.orientechnologies.orient.client.binary.OChannelBinaryAsynchClientSynch.<init>(OChannelBinaryAsynchClientSynch.java:37)
        at com.orientechnologies.orient.server.OServerShutdownMain.connect(OServerShutdownMain.java:64)
        at com.orientechnologies.orient.server.OServerShutdownMain.main(OServerShutdownMain.java:119)

Oct 26, 2016 10:57:26 AM com.orientechnologies.common.log.OLogManager log
SEVERE: Error on connecting to orient1.bc:2425
java.net.ConnectException: Connection refused
        at java.net.PlainSocketImpl.socketConnect(Native Method)
        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
        at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
        at java.net.Socket.connect(Socket.java:589)
        at com.orientechnologies.orient.client.binary.OChannelBinaryAsynchClient.<init>(OChannelBinaryAsynchClient.java:87)
        at com.orientechnologies.orient.client.binary.OChannelBinaryAsynchClient.<init>(OChannelBinaryAsynchClient.java:71)
        at com.orientechnologies.orient.client.binary.OChannelBinaryAsynchClientSynch.<init>(OChannelBinaryAsynchClientSynch.java:37)
        at com.orientechnologies.orient.server.OServerShutdownMain.connect(OServerShutdownMain.java:64)
        at com.orientechnologies.orient.server.OServerShutdownMain.main(OServerShutdownMain.java:119)
...

2016-10-26 01:07:55:848 SEVER Internal server error:
java.net.SocketException: Socket closed [ONetworkProtocolHttpDb]Error on client connection
```

The very last messages in the logfile are : 
```
java.lang.OutOfMemoryError: Java heap space
        at java.io.BufferedOutputStream.<init>(BufferedOutputStream.java:76)
        at com.orientechnologies.orient.enterprise.channel.text.OChannelTextServer.<init>(OChannelTextServer.java:34)
        at com.orientechnologies.orient.server.network.protocol.http.ONetworkProtocolHttpAbstract.config(ONetworkProtocolHttpAbstract.java:109)
        at com.orientechnologies.orient.server.network.protocol.http.ONetworkProtocolHttpDb.config(ONetworkProtocolHttpDb.java:43)
        at com.orientechnologies.orient.server.network.OServerNetworkListener.run(OServerNetworkListener.java:216)
```

So an OOM situation, once more ... :-(

When I start the server process, I redirect its STDOUT and STERR messages to separate file; there I find the following messages:
```
java.lang.OutOfMemoryError: Java heap space
Dumping heap to java_pid16509.hprof ...
Heap dump file created [7613662532 bytes in 96.861 secs]
Error on client connection
java.lang.OutOfMemoryError: Java heap space
        at java.io.BufferedOutputStream.<init>(BufferedOutputStream.java:76)
        at com.orientechnologies.orient.enterprise.channel.text.OChannelTextServer.<init>(OChannelTextServer.java:34)
        at com.orientechnologies.orient.server.network.protocol.http.ONetworkProtocolHttpAbstract.config(ONetworkProtocolHttpAbstract.java:109)
        at com.orientechnologies.orient.server.network.protocol.http.ONetworkProtocolHttpDb.config(ONetworkProtocolHttpDb.java:43)
        at com.orientechnologies.orient.server.network.OServerNetworkListener.run(OServerNetworkListener.java:216)
Error on client connection
...
```

That heap dump file "java_pid16509.hprof" is found in the "bin" subdir:
```
$ ls -l ./bin/java_pid16509.hprof
-rw------- 1 orientdb orientdb 7613662532 Oct 26 10:40 ./bin/java_pid16509.hprof
```

**It's a binary file. What program can I use to export its contents into readable format?**

-> trying to shut the program with a "kill" did not work
-> therefor aborting the program with a "kill -9" ... :-(

Restarted the server.

**Comment by rdelangh** [comment]
@tglman , @lvca 
I got exactly the same situation again. How can this be investigated ?

**Comment by tglman** [comment]
hi @rdelangh,

From the error seems that you are running a query that load a lot of record in memory, can you share with us the `./bin/java_pid16509.hprof` ? 

As well will be useful know what kind of query you are running, based on that we can understand if is sufficent toone some memory settings. 


Bye

**Comment by rdelangh** [comment]
@tglman 
The file is a few GB in size (even ZIPped), likely impossible to get it uploaded or transferred to you. Is there any means that I open/analyze this file here locally ?

**Comment by tglman** [comment]
Hi @rdelangh,

hprof is a standard dump of the jvm you can open it with many tools, like VisualVM (that you should already have installed),Eclipse, YourKit, ecc

here some more info : http://stackoverflow.com/questions/185893/how-do-i-analyze-a-hprof-file

What you need to look for is for what are the object that have more instances and that retain more memory.

Bye

**Comment by rdelangh** [comment]
@tglman 
ok, have it open with VisualVM.

1) the objects that have most instances are:
- java.util.LinkedHashMap$Entry : 16% instances (20558455), size=1.233 GB
- com.orientechnologies.orient.core.record.impl.ODocumentEntry : 16% instances (20545452), size=1.376GB
- char[] : 16% instances (20383145), size=0.985GB
- java.lang.String : 16% instances (20380014), size=0.570GB

Rest is less than 5% of the instances and smaller size

**Comment by tglman** [comment]
hi @rdelangh,

It look like you did a query without 'limit' ( or better with `limit -1`) , if you do that all the record will be loaded in memory and this is what seems happening, you should do your query using limit.

**Comment by rdelangh** [comment]
@tglman 
I think this is then a bug of ODB : you can not guarantee that the user ever launches a query without LIMIT, this could for example be the case in a subquery . In any case, ODB should manage its data in memory better, so that it avoids itself from overflowing.

**Comment by tglman** [comment]
hi @rdelangh,

We are aware if this limits and we are working to solve them with streaming and similar solutions, some fixes landed already in the 2.2.x and major changes are occourring in develop, the 3.0 will be free of memory related issues.

As today the current solution are: 
- design your query to select just the data that you need.
- in case of a query run by mistake disconnect the client this will interrupt the query and free the resources.
- in case not having control of the client connect with the server user to the admin tool and interrupt the too long running sessions (like you do with any dbms), this will free up resources.


Be aware that some limits are protocol related, some query that use too much resources using http may run fine using the binary protocol.

Hope this help.

**Comment by tglman** [comment]
hi @rdelangh,

Do you still have this issue ? 

Regards

**Comment by rdelangh** [comment]
@tglman 
yes indeed : when one query is requesting very much resources of the server, the entire server functionality grants to a halt, possibly the server even crashes with an OOM dump.

-> remains a big problem in the current 2.2.x releases apparently : a single job can kill then entire server. There is no normal multi-tasking in the server it seems.

**Comment by rdelangh** [comment]
@tglman 
by the way : currently running 2.2.14 and occasionally (when I forgot that I cannot launch very heavy queries against the server) this occurs again (= server granted to a halt by a single query or index build).
