### ISSUE TITLE
An exception in distribte mode【Local node 'node07' is not the owner for cluster 'test_25' (it is 'node08')】

### ISSUE THREAD

**Issue by weixliu** [orientechnologies/orientdb#6910]
## OrientDB Version, operating system, or hardware.
- v2.2 12

## Operating System
- [ ] Linux

## Expected behavior and actual behavior
I want to get help that how this exception occur & some development document in java API with distribute mode orientDB.Thanks~
## Steps to reproduce the problem
First, I just setup a distribute orientdb, I think it's right.
Then, I use orientdb create a database(just some class, vetex & edge), I get database in each of orientdb in cluster.
But finally I insert data to orientdb, I got exception with this, and I don't know why?

```
2016-11-14 19:24:37,543 [com.test.testDB.graph.OrientDBImportUtil:315]-[ERROR] pool-9-thread-25 
com.orientechnologies.orient.server.distributed.ODistributedConfigurationChangedException: Local node 'node07' is not the owner for cluster 'vetex_25' (it is 'node08')
	DB name="test_db"
	DB name="test_db"
	at sun.reflect.GeneratedConstructorAccessor50.newInstance(Unknown Source) ~[na:na]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[na:1.7.0_67]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526) ~[na:1.7.0_67]
	at com.orientechnologies.orient.client.binary.OChannelBinaryAsynchClient.throwSerializedException(OChannelBinaryAsynchClient.java:437) ~[orientdb-client-2.2.12.jar:2.2.12]
	at com.orientechnologies.orient.client.binary.OChannelBinaryAsynchClient.handleStatus(OChannelBinaryAsynchClient.java:388) ~[orientdb-client-2.2.12.jar:2.2.12]
	at com.orientechnologies.orient.client.binary.OChannelBinaryAsynchClient.beginResponse(OChannelBinaryAsynchClient.java:270) ~[orientdb-client-2.2.12.jar:2.2.12]
	at com.orientechnologies.orient.client.binary.OChannelBinaryAsynchClient.beginResponse(OChannelBinaryAsynchClient.java:162) ~[orientdb-client-2.2.12.jar:2.2.12]
	at com.orientechnologies.orient.client.remote.OStorageRemote.beginResponse(OStorageRemote.java:2138) ~[orientdb-client-2.2.12.jar:2.2.12]
	at com.orientechnologies.orient.client.remote.OStorageRemote$6.execute(OStorageRemote.java:548) ~[orientdb-client-2.2.12.jar:2.2.12]
	at com.orientechnologies.orient.client.remote.OStorageRemote$6.execute(OStorageRemote.java:542) ~[orientdb-client-2.2.12.jar:2.2.12]
	at com.orientechnologies.orient.client.remote.OStorageRemote$1.execute(OStorageRemote.java:164) ~[orientdb-client-2.2.12.jar:2.2.12]
	at com.orientechnologies.orient.client.remote.OStorageRemote.baseNetworkOperation(OStorageRemote.java:235) ~[orientdb-client-2.2.12.jar:2.2.12]
	at com.orientechnologies.orient.client.remote.OStorageRemote.asyncNetworkOperation(OStorageRemote.java:156) ~[orientdb-client-2.2.12.jar:2.2.12]
	at com.orientechnologies.orient.client.remote.OStorageRemote.createRecord(OStorageRemote.java:528) ~[orientdb-client-2.2.12.jar:2.2.12]
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.executeSaveRecord(ODatabaseDocumentTx.java:2095) ~[orientdb-core-2.2.12.jar:2.2.12]
	at com.orientechnologies.orient.core.tx.OTransactionNoTx.saveNew(OTransactionNoTx.java:246) ~[orientdb-core-2.2.12.jar:2.2.12]
	at com.orientechnologies.orient.core.tx.OTransactionNoTx.saveRecord(OTransactionNoTx.java:179) ~[orientdb-core-2.2.12.jar:2.2.12]
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.save(ODatabaseDocumentTx.java:2597) ~[orientdb-core-2.2.12.jar:2.2.12]
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.save(ODatabaseDocumentTx.java:103) ~[orientdb-core-2.2.12.jar:2.2.12]
	at com.orientechnologies.orient.core.record.impl.ODocument.save(ODocument.java:1802) ~[orientdb-core-2.2.12.jar:2.2.12]
	at com.orientechnologies.orient.core.record.impl.ODocument.save(ODocument.java:1793) ~[orientdb-core-2.2.12.jar:2.2.12]
	at com.tinkerpop.blueprints.impls.orient.OrientElement.save(OrientElement.java:333) ~[orientdb-graphdb-2.2.12.jar:2.2.12]
	at com.tinkerpop.blueprints.impls.orient.OrientElement.save(OrientElement.java:315) ~[orientdb-graphdb-2.2.12.jar:2.2.12]
	at com.tinkerpop.blueprints.impls.orient.OrientBaseGraph.addVertex(OrientBaseGraph.java:579) ~[orientdb-graphdb-2.2.12.jar:2.2.12]
	at com.thunisoft.wmcloud.graph.GraphUtils.addAjVertex(GraphUtils.java:129) ~[wmcloud-graph-loader.jar:na]
	at com.thunisoft.wmcloud.graph.GraphUtils.createGraph(GraphUtils.java:329) ~[wmcloud-graph-loader.jar:na]
	at com.thunisoft.writDB.graph.OrientDBImportUtil$TaskRunner.run(OrientDBImportUtil.java:305) ~[classes/:na]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [na:1.7.0_67]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [na:1.7.0_67]
	at java.lang.Thread.run(Thread.java:745) [na:1.7.0_67]
```

**Comment by lvca** [comment]
This problem has been already resolved in 2.2.x (2.2.x branch of github).

**Comment by lvca** [comment]
We will publish 2.2.13 in the next 48 hours, but you can build your own 2.2.-13-SNAPSHOT from 2.2.x branch.

**Comment by weixliu** [comment]
Thanks for reply, I'll try 2.2.13 later~
