### ISSUE TITLE
Property name starting with a number can be created but not deleted again

### ISSUE THREAD

**Issue by temilmg** [orientechnologies/orientdb#6956]
## OrientDB Version, operating system, or hardware.
- v2.2.13

## Operating System
- [ ] Linux

## Expected behavior and actual behavior
Its possible to create a property with a name starting with a number but its not possible to delete it again using java api or studio

## Steps to reproduce the problem

Create a property:
database.getVertexType("Prod").createProperty("1234something", OType.STRING);

try to delete property:
OrientVertexType ovtype = database.getVertexType("Prod");
ovtype.dropProperty("1234something");

Stacktrace:
Exception in thread "main" com.orientechnologies.orient.core.sql.OCommandSQLParsingException: Error parsing query:
drop property Prod.1234something
   ^
Encountered " <DROP> "drop "" at line 1, column 1.
Was expecting one of:
    <SELECT> ...
    <TRAVERSE> ...
    <MATCH> ...
    <INSERT> ...
    <RETURN> ...
    <PROFILE> ...
    <FIND> ...
    <REBUILD> ...
    <OPTIMIZE> ...
    <GRANT> ...
    <REVOKE> ...
    <BEGIN> ...
    <COMMIT> ...
    <ROLLBACK> ...
    <IF> ...
    <SLEEP> ...
    <CONSOLE> ...
    
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at com.orientechnologies.orient.client.binary.OChannelBinaryAsynchClient.throwSerializedException(OChannelBinaryAsynchClient.java:437)
	at com.orientechnologies.orient.client.binary.OChannelBinaryAsynchClient.handleStatus(OChannelBinaryAsynchClient.java:388)
	at com.orientechnologies.orient.client.binary.OChannelBinaryAsynchClient.beginResponse(OChannelBinaryAsynchClient.java:270)
	at com.orientechnologies.orient.client.binary.OChannelBinaryAsynchClient.beginResponse(OChannelBinaryAsynchClient.java:162)
	at com.orientechnologies.orient.client.remote.OStorageRemote.beginResponse(OStorageRemote.java:2167)
	at com.orientechnologies.orient.client.remote.OStorageRemote$27.execute(OStorageRemote.java:1160)
	at com.orientechnologies.orient.client.remote.OStorageRemote$2.execute(OStorageRemote.java:196)
	at com.orientechnologies.orient.client.remote.OStorageRemote.baseNetworkOperation(OStorageRemote.java:235)
	at com.orientechnologies.orient.client.remote.OStorageRemote.networkOperationRetry(OStorageRemote.java:193)
	at com.orientechnologies.orient.client.remote.OStorageRemote.networkOperation(OStorageRemote.java:204)
	at com.orientechnologies.orient.client.remote.OStorageRemote.command(OStorageRemote.java:1136)
	at com.orientechnologies.orient.core.command.OCommandRequestTextAbstract.execute(OCommandRequestTextAbstract.java:69)
	at com.orientechnologies.orient.core.metadata.schema.OClassImpl.dropProperty(OClassImpl.java:878)
	at com.orientechnologies.orient.core.metadata.schema.OClassAbstractDelegate.dropProperty(OClassAbstractDelegate.java:190)

**Comment by luigidellaquila** [comment]
Fixed in branch 2.2.x, the fix will be released with 2.2.15

Thanks

Luigi
