### ISSUE TITLE
OrientDB should update logs on restoring from WAL

### ISSUE THREAD

**Issue by lodrion** [orientechnologies/orientdb#6971]
## OrientDB Version, operating system, or hardware.
- v2.0 SNAPSHOT[ ] - .18[ ] .17[ ] .16[ ] .15[ ] .14[ ] .13[ ] .12[ ] .11[ ] .10[ ] .9[ ] .8[ ] .7[ ] .6[ ] .5[ ] .4[ ] .3[ ] .2[ ] .1[ ] .0[ ]
- v2.1 SNAPSHOT[ ] - .16[ ] .15[ ] .14[ ] .13[ ] .12[ ] .11[ ] .10[ ] .9[ ] .8[ ] .7[ ] .6[ ] .5[ ] .4[ ] .3[ ] .2[ ] .1[ ] .0[ ]
- v2.2 SNAPSHOT[ ] - .rc1[ ] .beta2[ ] .beta1[ ]

## Operating System
- [x ] Linux
- [ ] MacOSX
- [ ] Windows
- [ ] Other Unix
- [ ] Other, name? 

## Expected behavior and actual behavior
We had an orientdb server (started with bin/server.sh) crash while under heavy write load and restart.
It has been running at 100% CPU for the last hour and a half and not responding to connections with jstack output being very uninformative, e.g.

"OrientDB (/172.17.0.10:2424) <- BinaryClient (/10.100.2.211:36556)" #23 daemon prio=5 os_prio=0 tid=0x00007f376400c000 nid=0xfba waiting on condition [0x00007f3794dc0000]
   java.lang.Thread.State: WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x0000000680f051d0> (a com.orientechnologies.common.concur.lock.OReadersWriterSpinLock)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
	at com.orientechnologies.common.concur.lock.OReadersWriterSpinLock.acquireReadLock(OReadersWriterSpinLock.java:87)
	at com.orientechnologies.orient.core.storage.impl.local.paginated.OLocalPaginatedStorage.getConfiguration(OLocalPaginatedStorage.java:218)
	at com.orientechnologies.orient.core.sql.OCommandExecutorSQLAbstract.preParse(OCommandExecutorSQLAbstract.java:225)
	at com.orientechnologies.orient.core.sql.OCommandExecutorSQLDelete.parse(OCommandExecutorSQLDelete.java:86)
	at com.orientechnologies.orient.core.sql.OCommandExecutorSQLDelete.parse(OCommandExecutorSQLDelete.java:60)
	at com.orientechnologies.orient.core.sql.OCommandExecutorSQLDelegate.parse(OCommandExecutorSQLDelegate.java:58)
	at com.orientechnologies.orient.core.sql.OCommandExecutorSQLDelegate.parse(OCommandExecutorSQLDelegate.java:39)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.command(OAbstractPaginatedStorage.java:2621)
	at com.orientechnologies.orient.core.command.OCommandRequestTextAbstract.execute(OCommandRequestTextAbstract.java:69)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.command(ONetworkProtocolBinary.java:1438)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.executeRequest(ONetworkProtocolBinary.java:576)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.sessionRequest(ONetworkProtocolBinary.java:321)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.execute(ONetworkProtocolBinary.java:197)
	at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:77)

There are 190 threads waiting at
com.orientechnologies.common.concur.lock.OReadersWriterSpinLock.acquireReadLock(OReadersWriterSpinLock.java:87)

The server does not respond to requests and there is nothing in the logs indicating that anything is going on. The only evidence we have for it not being completely wedged is that ctime on the WAL file is being updated.

It would be nice to at least see some kind of status updates in the logs. Also we are able to recreate the full database from backups in minutes, so WAL processing taking multiple hours does not quite make sense.

## Steps to reproduce the problem

Crash the server in the middle of the update and restart it

**Comment by laa** [comment]
@lodrion we have update of restore status in log what version do you use ?

**Comment by lodrion** [comment]
We are on  2.2.12.
BTW, I had to kill the server because the restore was taking too long... and that completely (and irrevocably) destroyed the indices, so we had to restore the database from backups. 

I suspect the root cause was sustained high write throughput from multiple connections

**Comment by laa** [comment]
@lodrion do you still have complete thread dump of this case ?

**Comment by lodrion** [comment]
Not anymore, sorry

**Comment by laa** [comment]
@lodrion sorry but without full stack trace I do not have enough information to fix the issue. I will close issue , but if you reproduce it, please reopen issue and provide full stack trace as separate gist so we will be able to fix given issue.
