### ISSUE TITLE
Exception during data flush java.lang.OutOfMemoryError: Java heap space

### ISSUE THREAD

**Issue by thePunIssuer** [orientechnologies/orientdb#6975]
## OrientDB Version, operating system, or hardware.
- v2.0 SNAPSHOT[ ] - .18[ ] .17[ ] .16[ ] .15[ ] .14[ ] .13[ ] .12[ ] .11[ ] .10[ ] .9[ ] .8[ ] .7[ ] .6[ ] .5[ ] .4[ ] .3[ ] .2[ ] .1[ ] .0[ ]
- v2.1 SNAPSHOT[ ] - .16[ ] .15[ ] .14[ ] .13[ ] .12[ ] .11[ ] .10[ ] .9[ ] .8[ ] .7[ ] .6[ ] .5[ ] .4[ ] .3[ ] .2[ ] .1[ ] .0[ ]
- v2.2 .13[X]

## Operating System
- [X] Linux
- [ ] MacOSX
- [ ] Windows
- [ ] Other Unix
- [ ] Other, name? 

Raspberry Pi 3

## Expected behavior and actual behavior
To maintain a finite list of values of multiple sensors, we regularly delete the oldest ones via
`select from expand(out(hasValue)) from >>id of sensor vertex<< order by @rid limit >>amount of excessive values<<`
and afterwards deleting these values via Java API.

However, instead of deleting the Vertices, the Write Cache Flush Task encounters an OutOfMemoryError:
```
2016-12-02 06:50:30,091 ERROR [OrientDB Write Cache Flush Task (data)] c.o.o.c.s.c.l.OWOWCache$PeriodicFlushTask - Exception during data flush
java.lang.OutOfMemoryError: Java heap space
```
## Steps to reproduce the problem
Unfortunately, the device with this issue is running on the premises of a customer of ours, so we only have limited data and access.
We are running an embedded database engine within our software with (not explicitly configured) 224MB Heap and these options:
`-XX:MaxDirectMemorySize=3g -Dmemory.chunk.size=67108864 -Dstorage.wal.cacheSize=512 -Dstorage.wal.maxSegmentSize=32 -Dstorage.wal.maxSize=256 -Dstorage.diskCache.bufferSize=256`

Is there anything that we should specificially look for? Should we get the 8GB dump of the customers sdcard and provide that?

We noticed that the data partition of the device was filling up, with only ~130MB of free space. Since a full disk does have decreased performance, could this be relevant for this issue?

**Comment by taburet** [comment]
Hi @thePunIssuer, the answer is simple – there is no enough heap space to process the requests. Increase the heap size or/and lower the size of the single request or/and lower the number of request running in parallel. Capture the heap and thread dump next time you see OOM, I will inspect them for leaks.

Regarding disk space, most likely it's growing because of OOMs on it's cleanup. Please share database directory file listing including file sizes.

**Comment by taburet** [comment]
You may try replace`select from expand(out(hasValue)) from >>id of sensor vertex<< order by @rid limit >>amount of excessive values<<` with `select from Value where in(‘hasValue’) contains >> id of sensor<< order by @rid limit x`, that will lower memory requirements to process the query, but will raise CPU requirements.

**Comment by taburet** [comment]
@thePunIssuer any news on the issue? Have you tried to optimize the configuration or the query?

**Comment by thePunIssuer** [comment]
Hi @taburet, sorry for the long delay.
I recently got hold of the database and it turns out that somehow our housekeeping failed and the device accumulated over 8 million data points in total, with some sensors having around 380k values attached.

I resorted to deleting all values, and exporting/importing the database. Thank you very much for your assistance :)

FYI, on my development machine, deleting (a limited batch of) oldest values did work using your suggested query. My initial query `select from expand(out(hasValue)) from >>id of sensor vertex<< order by @rid limit >>amount of excessive values<<`), failed with
```
java.lang.OutOfMemoryError: GC overhead limit exceeded
	at java.lang.StringCoding$StringEncoder.encode(StringCoding.java:300)
	at java.lang.StringCoding.encode(StringCoding.java:344)
	at java.lang.StringCoding.encode(StringCoding.java:387)
	at java.lang.String.getBytes(String.java:958)
	at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinaryV0.deserializePartial(ORecordSerializerBinaryV0.java:78)
	at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinary.fromStream(ORecordSerializerBinary.java:78)
	at com.orientechnologies.orient.core.record.impl.ODocument.deserializeFields(ODocument.java:1851)
	at com.orientechnologies.orient.core.record.impl.ODocument.checkForFields(ODocument.java:2626)
	at com.orientechnologies.orient.core.record.impl.ODocument.rawField(ODocument.java:773)
	at com.orientechnologies.orient.core.record.impl.ODocument.field(ODocument.java:823)
	at com.orientechnologies.orient.core.record.impl.ODocumentComparator.compare(ODocumentComparator.java:72)
	at com.orientechnologies.orient.core.record.impl.ODocumentComparator.compare(ODocumentComparator.java:45)
	at java.util.TimSort.countRunAndMakeAscending(TimSort.java:360)
	at java.util.TimSort.sort(TimSort.java:234)
	at java.util.Arrays.sort(Arrays.java:1512)
	at java.util.ArrayList.sort(ArrayList.java:1454)
	at java.util.Collections.sort(Collections.java:175)
	at com.orientechnologies.orient.core.record.impl.ODocumentHelper.sort(ODocumentHelper.java:84)
	at com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.applySort(OCommandExecutorSQLSelect.java:2526)
	at com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.applyOrderBy(OCommandExecutorSQLSelect.java:2514)
	at com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.execute(OCommandExecutorSQLSelect.java:492)
	at com.orientechnologies.orient.core.sql.OCommandExecutorSQLDelegate.execute(OCommandExecutorSQLDelegate.java:74)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.executeCommand(OAbstractPaginatedStorage.java:2577)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.command(OAbstractPaginatedStorage.java:2523)
	at com.orientechnologies.orient.core.command.OCommandRequestTextAbstract.execute(OCommandRequestTextAbstract.java:69)
	at com.tinkerpop.blueprints.impls.orient.OrientGraphCommand.execute(OrientGraphCommand.java:49)
```
I can't really tell if this is to be expected by these amounts of data.
