### ISSUE TITLE
NPE when querying edges through gremlin API, with an index named "notAnOClass.otherStuff"

### ISSUE THREAD

**Issue by clepelli** [orientechnologies/orientdb#6980]
## OrientDB Version, operating system, or hardware.
- v2.2.11

## Operating System
- [x ] Linux

## Expected behavior and actual behavior
I run a query on orient-studio with gremlin language : g.E()

Expected :  to see some edges !

Actual : Null Pointer Exception, see stackTrace bellow. It seems that the getIndexedKeys method in stacktrace bellow makes the false assumption that an index named <something>.<otherStuff> should ever mean <something> is a class name... Is it documented somewhere ?

## Steps to reproduce the problem

Create an index with name "lucene.someClass.someField"
go to orient studio and query "g.E()"

##workaround

Call my index someClass.someField.lucene should work, remains to be tested.

## Stack trace
```
com.orientechnologies.orient.core.exception.OCommandExecutionException: Error on execution of the GREMLIN script
	DB name="orient"
	at com.orientechnologies.orient.graph.gremlin.OGremlinHelper.execute(OGremlinHelper.java:161)
	at com.orientechnologies.orient.graph.gremlin.OGremlinHelper.execute(OGremlinHelper.java:81)
	at com.orientechnologies.orient.graph.gremlin.OCommandGremlinExecutor.execute(OCommandGremlinExecutor.java:58)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.executeCommand(OAbstractPaginatedStorage.java:2672)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.command(OAbstractPaginatedStorage.java:2618)
	at com.orientechnologies.orient.core.command.OCommandRequestTextAbstract.execute(OCommandRequestTextAbstract.java:69)
	at com.orientechnologies.orient.server.network.protocol.http.command.post.OServerCommandPostCommand.execute(OServerCommandPostCommand.java:106)
	at com.orientechnologies.orient.graph.server.command.OServerCommandPostCommandGraph.execute(OServerCommandPostCommandGraph.java:37)
	at com.orientechnologies.orient.server.network.protocol.http.ONetworkProtocolHttpAbstract.service(ONetworkProtocolHttpAbstract.java:168)
	at com.orientechnologies.orient.server.network.protocol.http.ONetworkProtocolHttpAbstract.execute(ONetworkProtocolHttpAbstract.java:616)
	at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:77)
Caused by: java.lang.NullPointerException: null
	at com.tinkerpop.blueprints.impls.orient.OrientBaseGraph.getIndexedKeys(OrientBaseGraph.java:1744)
	at com.tinkerpop.blueprints.impls.orient.OrientGraphQuery$OrientGraphQueryIterable.getIndexedKeys(OrientGraphQuery.java:83)
	at com.tinkerpop.blueprints.util.DefaultGraphQuery$DefaultGraphQueryIterable.getElementIterable(DefaultGraphQuery.java:145)
	at com.tinkerpop.blueprints.util.DefaultGraphQuery$DefaultGraphQueryIterable.<init>(DefaultGraphQuery.java:82)
	at com.tinkerpop.blueprints.impls.orient.OrientGraphQuery$OrientGraphQueryIterable.<init>(OrientGraphQuery.java:74)
	at com.tinkerpop.blueprints.impls.orient.OrientGraphQuery.edges(OrientGraphQuery.java:239)
	at com.tinkerpop.pipes.transform.GraphQueryPipe.processNextStart(GraphQueryPipe.java:49)
	at com.tinkerpop.pipes.transform.GraphQueryPipe.processNextStart(GraphQueryPipe.java:17)
	at com.tinkerpop.pipes.AbstractPipe.hasNext(AbstractPipe.java:98)
	at com.tinkerpop.pipes.util.Pipeline.hasNext(Pipeline.java:105)
	at com.orientechnologies.orient.graph.gremlin.OGremlinHelper.execute(OGremlinHelper.java:129)
	... 10 common frames omitted

```

**Comment by maggiolo00** [comment]
Hi @clepelli 

I've fixed the NPE. It will be available in the next release 2.2.14
Thanks
