### ISSUE TITLE
Corrupt database after upgrading from 2.0 to 2.2 (server issue?)

### ISSUE THREAD

**Issue by RoarN** [orientechnologies/orientdb#6982]
OrientDB 2.2.13 on Windows

We upgradet the OrientDB version from 2.0 to 2.2.13 

On one of our systems we got a problem with the database.

Running this simple request in Studio:
	SELECT * FROM Maintenance WHERE targetType='SERVICE' and toTime >= 1

Causes an exception:
2016-12-08 13:04:31,609 [Thread-18] ERROR com.ceesoft.ceeview.datastore.maintenance.MaintenanceStore - Data Store exception
com.orientechnologies.orient.core.exception.OCommandExecutionException: Error on execution of command: sql.SELECT * FROM Maintenance WHERE targetType='SERVICE' and toTime >= 1
	DB name="ceeview"
	DB name="ceeview"
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.orientechnologies.orient.client.binary.OChannelBinaryAsynchClient.throwSerializedException(OChannelBinaryAsynchClient.java:437)
	at com.orientechnologies.orient.client.binary.OChannelBinaryAsynchClient.handleStatus(OChannelBinaryAsynchClient.java:388)
	at com.orientechnologies.orient.client.binary.OChannelBinaryAsynchClient.beginResponse(OChannelBinaryAsynchClient.java:270)
	at com.orientechnologies.orient.client.binary.OChannelBinaryAsynchClient.beginResponse(OChannelBinaryAsynchClient.java:162)
	at com.orientechnologies.orient.client.remote.OStorageRemote.beginResponse(OStorageRemote.java:2167)
	at com.orientechnologies.orient.client.remote.OStorageRemote$27.execute(OStorageRemote.java:1160)
	at com.orientechnologies.orient.client.remote.OStorageRemote$2.execute(OStorageRemote.java:196)
	at com.orientechnologies.orient.client.remote.OStorageRemote.baseNetworkOperation(OStorageRemote.java:235)
	at com.orientechnologies.orient.client.remote.OStorageRemote.networkOperationRetry(OStorageRemote.java:193)
	at com.orientechnologies.orient.client.remote.OStorageRemote.networkOperation(OStorageRemote.java:204)
	at com.orientechnologies.orient.client.remote.OStorageRemote.command(OStorageRemote.java:1136)
	at com.orientechnologies.orient.core.command.OCommandRequestTextAbstract.execute(OCommandRequestTextAbstract.java:69)
	at com.tinkerpop.blueprints.impls.orient.OrientGraphCommand.execute(OrientGraphCommand.java:49)
	

orientdb.log and Studio had the following error message: 	
2016-12-08 13:46:47:720 SEVER Internal server error:
java.lang.ArrayIndexOutOfBoundsException: -47 [ONetworkProtocolHttpDb]	
	
Running the same query in the console worked just fine so I suspect it is a server issue.
	
Regards,
/Roar

**Comment by RoarN** [comment]
This is the database with issues:
[ceeview.zip](https://github.com/orientechnologies/orientdb/files/639463/ceeview.zip)

**Comment by tglman** [comment]
hi @RoarN, 

The database seems to have been created with 1.x vesion and is written with a serializer that has been deprecated in 2.2, you should export and import the database to be able to migrate.

Regards

**Comment by RoarN** [comment]
How can you tell that it is created with 1.x? 

Any way, everything else seems to work just fine (so far) except the query
SELECT * FROM Maintenance WHERE targetType='SERVICE' and toTime >= 1

SELECT * FROM Maintenance
without the where statement works just fin as well.

**Comment by tglman** [comment]
hi @RoarN,

I got the database and was create with a serializer that wes deprecated in 2.0, so the database come probably from an earlier version, we still have the deprecated serializer on 2.2 but we do not guarantee that it work on the disc anymore, so it can happen that some data is read correctly and some no, the solution is export import.

Bye

**Comment by RoarN** [comment]
I got 2 comments regarding this answer.

1)  My main concern is that it is impossible to tell that this is the situation, neither the database nor the client API actually states that the database was too old and incompatible with the current version.
Instead we get hanging connections, silent failures or random errors on queries to the database. This has happened a lot since we started to use OrientDB (1.0) and is not a good way to build trust with the users, both yours and ours.

2) Even if we actually were able to detect incompatible database versions this solution would be impractical. Today we have 7-8 installations, but within a year or two we expect to have 50+. To manually export/import all the databases would be a nightmare even if we had access to all the customer sites. If the implementation changes so that the versions are incompatible the database server should automatically handle the conversion.


I will try to export/import and see if that solves the issue with this database. But as I said, it would be nice to actually get an error message right away that states that the version is incompatible with the database.

**Comment by tglman** [comment]
hi @RoarN,

We got your feedback, i made the database throw a meaningful error as soon as you open it, so far this is the first feedback with this compatibility issue, most of our user made this migration in 2.0 and 2.1.

Since 2.x we are more conservative on the way are managed database internal structures, and we are trying to avoid all manual migration implementing smooth migration systems.

Regards

**Comment by RoarN** [comment]
Hi,

Good news :) 

A meaningful error mesages is a good start, and if you manage to handle migration internally on later upgrades that would be great.

Thanks,
/Roar

**Comment by tglman** [comment]
Hi @RoarN,

Going to close this, i think i answered to your question
