### ISSUE TITLE
Error fetching record java.lang.StringIndexOutOfBoundsException

### ISSUE THREAD

**Issue by willywos** [orientechnologies/orientdb#6984]
## OrientDB Version, operating system, or hardware.
- v2.2.12

## Operating System
- [x] Linux
- [x] MacOSX

## Expected behavior and actual behavior

When I go to query for a particular user record I have I get an exception. 

```
Fetching error on record #39:18
java.lang.StringIndexOutOfBoundsException: String index out of range: -60
	at java.lang.String.checkBounds(String.java:381)
	at java.lang.String.<init>(String.java:425)
	at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinaryV0.stringFromBytes(ORecordSerializerBinaryV0.java:990)
	at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinaryV0.readString(ORecordSerializerBinaryV0.java:947)
	at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinaryV0.deserializeValue(ORecordSerializerBinaryV0.java:406)
	at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinaryV0.readEmbeddedMap(ORecordSerializerBinaryV0.java:571)
	at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinaryV0.deserializeValue(ORecordSerializerBinaryV0.java:467)
	at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinaryV0.readEmbeddedMap(ORecordSerializerBinaryV0.java:571)
	at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinaryV0.deserializeValue(ORecordSerializerBinaryV0.java:467)
	at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinaryV0.readEmbeddedList(ORecordSerializerBinaryV0.java:648)
	at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinaryV0.deserializeValue(ORecordSerializerBinaryV0.java:449)
	at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinaryV0.deserializePartial(ORecordSerializerBinaryV0.java:148)
	at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinary.fromStream(ORecordSerializerBinary.java:78)
	at com.orientechnologies.orient.core.record.impl.ODocument.deserializeFields(ODocument.java:1851)
	at com.orientechnologies.orient.core.record.impl.ODocument.checkForFields(ODocument.java:2625)
	at com.orientechnologies.orient.core.record.impl.ODocument.rawField(ODocument.java:773)
	at com.orientechnologies.orient.core.fetch.OFetchHelper.processRecord(OFetchHelper.java:298)
	at com.orientechnologies.orient.core.fetch.OFetchHelper.fetch(OFetchHelper.java:75)
	at com.orientechnologies.orient.core.serialization.serializer.record.string.ORecordSerializerJSON.toString(ORecordSerializerJSON.java:343)
	at com.orientechnologies.orient.core.serialization.serializer.record.string.ORecordSerializerStringAbstract.toString(ORecordSerializerStringAbstract.java:664)
	at com.orientechnologies.orient.core.record.ORecordAbstract.toJSON(ORecordAbstract.java:191)
	at com.orientechnologies.orient.server.network.protocol.http.OHttpResponse.formatMultiValue(OHttpResponse.java:413)
	at com.orientechnologies.orient.server.network.protocol.http.OHttpResponse.writeRecordsOnStream(OHttpResponse.java:362)
	at com.orientechnologies.orient.server.network.protocol.http.OHttpResponse.access$000(OHttpResponse.java:44)
	at com.orientechnologies.orient.server.network.protocol.http.OHttpResponse$2.call(OHttpResponse.java:337)
	at com.orientechnologies.orient.server.network.protocol.http.OHttpResponse$2.call(OHttpResponse.java:332)
	at com.orientechnologies.orient.server.network.protocol.http.OHttpResponse.sendStream(OHttpResponse.java:507)
	at com.orientechnologies.orient.server.network.protocol.http.OHttpResponse.writeRecords(OHttpResponse.java:332)
	at com.orientechnologies.orient.server.network.protocol.http.OHttpGraphResponse.writeRecords(OHttpGraphResponse.java:59)
	at com.orientechnologies.orient.server.network.protocol.http.OHttpResponse.writeResult(OHttpResponse.java:229)
	at com.orientechnologies.orient.server.network.protocol.http.command.post.OServerCommandPostCommand.execute(OServerCommandPostCommand.java:134)
	at com.orientechnologies.orient.graph.server.command.OServerCommandPostCommandGraph.execute(OServerCommandPostCommandGraph.java:37)
	at com.orientechnologies.orient.server.network.protocol.http.ONetworkProtocolHttpAbstract.service(ONetworkProtocolHttpAbstract.java:168)
	at com.orientechnologies.orient.server.network.protocol.http.ONetworkProtocolHttpAbstract.execute(ONetworkProtocolHttpAbstract.java:616)
	at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:77)
```

I'm not sure how to fix this issue. I can't remove the record, update the record or even query the record without getting the above exception. 

When I try from the web studio console I get 

```
SEVER Internal server error:
java.lang.StringIndexOutOfBoundsException: String index out of range: -60 [ONetworkProtocolHttpDb]
WARNI {db=####} Error deserializing record with id #39:18 send this data for debugging: AAh1c2Vy9QEAAAJusQEAAAJvswEAAAJ2tQEAAAJ3twEAAAKAYwAAApplAAACnL0BAAACndkBAAAC38kBAAAC6csBAAA....
````

I've tried to Base64 decode the data it says for debugging but I can't really make out what it is, It looks like it's binary of some sort. 

I'm not sure what the user did to get the data in a bad state like this or how to reproduce the problem. I'm kind of all out of ideas on what to do. 

Thanks.

**Comment by willywos** [comment]
It looks like I was able to use truncate record to delete it. Is there anyway to create a new record with the same rid so I don't have to update all the relationships?

**Comment by tglman** [comment]
hi @willywos,

I'm afraid there is now way to recreate the record with the same rid.

There is a command to find all the references of a rid  ex: "find references #10:10" this browse the whole database and find all the record that point to the rid.

Hope this help
Regards

**Comment by willywos** [comment]
Thanks @tglman. I think since we had a backup of the database we will just restore from that to fix the issue for right now. We have like 100+ references for the id across our system so that makes it hard to update and make sure we got them all. Thanks for the help 👍

**Comment by tglman** [comment]
@willywos,

so where you able to solve all the case? can we consider this close ?

Regards

**Comment by willywos** [comment]
@tglman nah not really, I wasn't able to figure out how to recreate the issue and we restored from a backup. Feel free to close it if you want. Thanks again.

**Comment by tglman** [comment]
hi @willywos,

Ok i'll close it for now, if it happen again adn you have more information feel free to reopen.

Regards
