### ISSUE TITLE
Error on OrientGraphNoTx

### ISSUE THREAD

**Issue by wq1101** [orientechnologies/orientdb#6986]
## OrientDB Version, operating system, or hardware.
- v2.2。13 SNAPSHOT[*] 

## Operating System
- [* ] Linux
- [ ] MacOSX
- [ ] Windows
- [ ] Other Unix
- [ ] Other, name? 

## Expected behavior and actual behavior
Run OrientGraphNoTx on 3 nodes cluster, while responding :

Exception in thread "main" com.orientechnologies.orient.server.distributed.task.ODistributedOperationException: Cannot execute distributed request (id=0.6665273 task=tx) because all worker threads (8) are busy
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at com.orientechnologies.orient.client.binary.OChannelBinaryAsynchClient.throwSerializedException(OChannelBinaryAsynchClient.java:437)
	at com.orientechnologies.orient.client.binary.OChannelBinaryAsynchClient.handleStatus(OChannelBinaryAsynchClient.java:388)
	at com.orientechnologies.orient.client.binary.OChannelBinaryAsynchClient.beginResponse(OChannelBinaryAsynchClient.java:270)
	at com.orientechnologies.orient.client.binary.OChannelBinaryAsynchClient.beginResponse(OChannelBinaryAsynchClient.java:162)
	at com.orientechnologies.orient.client.remote.OStorageRemote.beginResponse(OStorageRemote.java:2167)
	at com.orientechnologies.orient.client.remote.OStorageRemote$27.execute(OStorageRemote.java:1160)
	at com.orientechnologies.orient.client.remote.OStorageRemote$2.execute(OStorageRemote.java:196)
	at com.orientechnologies.orient.client.remote.OStorageRemote.baseNetworkOperation(OStorageRemote.java:235)
	at com.orientechnologies.orient.client.remote.OStorageRemote.networkOperationRetry(OStorageRemote.java:193)
	at com.orientechnologies.orient.client.remote.OStorageRemote.networkOperation(OStorageRemote.java:204)
	at com.orientechnologies.orient.client.remote.OStorageRemote.command(OStorageRemote.java:1136)
	at com.orientechnologies.orient.core.command.OCommandRequestTextAbstract.execute(OCommandRequestTextAbstract.java:69)
	at com.tinkerpop.blueprints.impls.orient.OrientGraphCommand.execute(OrientGraphCommand.java:49)
	at GraphNoTxEdge.run(GraphNoTxEdge.java:91)
	at tests.GraphNoTxEdge(tests.java:383)

**Comment by lvca** [comment]
What kind of operations are you executing at the same time?

**Comment by wq1101** [comment]
OrientGraphNoTx getGraph = new OrientGraphNoTx(conn, "root", "password");
getGraph.makeActive();

**Comment by lvca** [comment]
We fixed this problem in 2.2.21. Please use this.
