### ISSUE TITLE
expand(outE()) throws a nullpointer exception in orientdb server side

### ISSUE THREAD

**Issue by temilmg** [orientechnologies/orientdb#7018]
## OrientDB Version, operating system, or hardware.
- v2.2.13

## Operating System
- [ ] Linux

## Expected behavior and actual behavior

select expand(outE()) from #38:0
This query used to work in 2.1.17 but not in 2.2.13 It throws the following nullpointer exception

 java.lang.NullPointerException
at com.tinkerpop.blueprints.impls.orient.OrientEdgeIterator.createGraphElement(OrientEdgeIterator.java:109)
at com.tinkerpop.blueprints.impls.orient.OrientEdgeIterator.createGraphElement(OrientEdgeIterator.java:41)
at com.orientechnologies.orient.core.iterator.OLazyWrapperIterator.hasNext(OLazyWrapperIterator.java:93)
at com.orientechnologies.common.collection.OMultiCollectionIterator.hasNextInternal(OMultiCollectionIterator.java:97)
at com.orientechnologies.common.collection.OMultiCollectionIterator.hasNext(OMultiCollectionIterator.java:78)
at com.orientechnologies.common.collection.OMultiCollectionIterator.hasNextInternal(OMultiCollectionIterator.java:97)
at com.orientechnologies.common.collection.OMultiCollectionIterator.hasNext(OMultiCollectionIterator.java:78)
at com.orientechnologies.orient.core.sql.OCommandExecutorSQLResultsetAbstract.getResult(OCommandExecutorSQLResultsetAbstract.java:254)
at com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.execute(OCommandExecutorSQLSelect.java:495)
at com.orientechnologies.orient.core.sql.OCommandExecutorSQLDelegate.execute(OCommandExecutorSQLDelegate.java:74)
at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.executeCommand(OAbstractPaginatedStorage.java:2577)
at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.command(OAbstractPaginatedStorage.java:2523)
at com.orientechnologies.orient.core.command.OCommandRequestTextAbstract.execute(OCommandRequestTextAbstract.java:69)
at com.orientechnologies.orient.server.network.protocol.http.command.post.OServerCommandPostCommand.execute(OServerCommandPostCommand.java:106)
at com.orientechnologies.orient.graph.server.command.OServerCommandPostCommandGraph.execute(OServerCommandPostCommandGraph.java:37)
at com.orientechnologies.orient.server.network.protocol.http.ONetworkProtocolHttpAbstract.service(ONetworkProtocolHttpAbstract.java:169)
at com.orientechnologies.orient.server.network.protocol.http.ONetworkProtocolHttpAbstract.execute(ONetworkProtocolHttpAbstract.java:621)
at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:77)

**Comment by temilmg** [comment]
When doing the query as follows
select outE() from #38:0
then i can see from the rids that one of them is a vertex and and not an edge. Im guessing its some kind of lightweight edge!?
If this is the problem then I dont think the query should brake down just because it meets a lightweight edge when doing the expand!

**Comment by luigidellaquila** [comment]
Hi @temilmg 

Do you have a db or a test case to reproduce the problem?

Thanks

Luigi

**Comment by temilmg** [comment]
Seems I am not allowed to attach the .gz file that i get from exporting the db from Orientdb!
But it is easy to reproduce as follows:
1. create two vertex classes (ClassA,ClassB)
2. Create one edge class (myedge).
3. Fill in some data
4. Create a few normal edges 
5. Change to using lightweight edges and create a lightweight edge
6. perform the query: select expand(outE("myedge")) from ClassA
This will result in a nullpointer exception

**Comment by luigidellaquila** [comment]
Hi @temilmg 

I managed to reproduce the issue, I'm fixing it now

Thanks

Luigi

**Comment by luigidellaquila** [comment]
Just pushed a fix on 2.2.x branch, it will be released with v 2.2.16

Closing, thanks!

Luigi

**Comment by santo-it** [comment]
Noted in the [Release Notes](https://github.com/orientechnologies/orientdb/wiki/OrientDB-2.2-Release-Notes)
