### ISSUE TITLE
Teleporter import data error

### ISSUE THREAD

**Issue by cuijinyi** [orientechnologies/orientdb#7038]
## OrientDB Version, operating system, or hardware.
- v2.2 enterprise trail

## Operating System
- [ x] Windows

## Expected behavior and actual behavior
import data from mysql5.6 error

Exception in thread "pool-12-thread-1" com.orientechnologies.orient.core.sql.parser.TokenMgrError: Lexical error at line 1, column 53.  Encountered: "\ufeff" (65279), after : ""
        at com.orientechnologies.orient.core.sql.parser.OrientSqlTokenManager.getNextToken(OrientSqlTokenManager.java:6140)
        at com.orientechnologies.orient.core.sql.parser.OrientSql.jj_ntk(OrientSql.java:26947)
        at com.orientechnologies.orient.core.sql.parser.OrientSql.CreateIndexStatement(OrientSql.java:15120)
        at com.orientechnologies.orient.core.sql.parser.OrientSql.StatementInternal(OrientSql.java:755)
        at com.orientechnologies.orient.core.sql.parser.OrientSql.Statement(OrientSql.java:624)
        at com.orientechnologies.orient.core.sql.parser.OrientSql.parse(OrientSql.java:75)
        at com.orientechnologies.orient.core.sql.parser.OStatementCache.parse(OStatementCache.java:89)
        at com.orientechnologies.orient.core.sql.parser.OStatementCache.get(OStatementCache.java:72)
        at com.orientechnologies.orient.core.sql.parser.OStatementCache.get(OStatementCache.java:62)
        at com.orientechnologies.orient.core.sql.OCommandExecutorSQLAbstract.preParse(OCommandExecutorSQLAbstract.java:228)
        at com.orientechnologies.orient.core.sql.OCommandExecutorSQLCreateIndex.parse(OCommandExecutorSQLCreateIndex.java:77)
        at com.orientechnologies.orient.core.sql.OCommandExecutorSQLCreateIndex.parse(OCommandExecutorSQLCreateIndex.java:53)
        at com.orientechnologies.orient.core.sql.OCommandExecutorSQLDelegate.parse(OCommandExecutorSQLDelegate.java:58)
        at com.orientechnologies.orient.core.sql.OCommandExecutorSQLDelegate.parse(OCommandExecutorSQLDelegate.java:39)
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.command(OAbstractPaginatedStorage.java:2521)
        at com.orientechnologies.orient.core.command.OCommandRequestTextAbstract.execute(OCommandRequestTextAbstract.java:69)
        at com.orientechnologies.teleporter.writer.OGraphModelWriter.writeModelOnOrient(OGraphModelWriter.java:243)
        at com.orientechnologies.teleporter.strategy.rdbms.ODBMSNaiveStrategy.createSchemaMapper(ODBMSNaiveStrategy.java:88)
        at com.orientechnologies.teleporter.strategy.rdbms.ODBMSImportStrategy.executeStrategy(ODBMSImportStrategy.java:85)
        at com.orientechnologies.teleporter.main.OTeleporter.execute(OTeleporter.java:272)
        at com.orientechnologies.teleporter.main.OTeleporter.execute(OTeleporter.java:286)
        at com.orientechnologies.teleporter.http.handler.OTeleporterJob.run(OTeleporterJob.java:71)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)

## Steps to reproduce the problem
a 30,000,000 test data from mysql,do not know which table's record number error

**Comment by G4br13l3** [comment]
Hi @cuijinyi, is this the full stacktrace?
Can I have additional info about the schema and the execution? Does it crash during the 3th phase?

**Comment by G4br13l3** [comment]
By the way, I guess it depends on the byte order mark "U+FEFF", we are working to support it.
Thanks.
