### ISSUE TITLE
Error during transaction commit: NullPointerException

### ISSUE THREAD

**Issue by jamieb22** [orientechnologies/orientdb#7070]
## OrientDB Version, operating system, or hardware.
- v2.0 SNAPSHOT[ ] - .18[ ] .17[ ] .16[ ] .15[ ] .14[ ] .13[ ] .12[ ] .11[ ] .10[ ] .9[ ] .8[ ] .7[ ] .6[ ] .5[ ] .4[ ] .3[ ] .2[ ] .1[ ] .0[ ]
- v2.1 SNAPSHOT[ ] - .16[ ] .15[ ] .14[ ] .13[ ] .12[ ] .11[ ] .10[ ] .9[ ] .8[ ] .7[ ] .6[ ] .5[ ] .4[ ] .3[ ] .2[ ] .1[ ] .0[ ]
- v2.2 SNAPSHOT[ ] - .rc1[ ] .beta2[ ] .beta1[ ]

## Operating System
- [ X] Linux
- [ ] MacOSX
- [ ] Windows
- [ ] Other Unix
- [ ] Other, name? 

## Expected behavior and actual behavior

com.stimulus.archiva.domain.aa: Error during transaction commit^M
        DB name="archiva$te"
        
Caused by: com.orientechnologies.orient.core.exception.OStorageException: Error during transaction commit^M
        DB name="archiva$te"
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.makeRollback(OAbstractPaginatedStorage.java:2205)
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.commit(OAbstractPaginatedStorage.java:1430)
        at com.orientechnologies.orient.core.tx.OTransactionOptimistic.doCommit(OTransactionOptimistic.java:539)
        at com.orientechnologies.orient.core.tx.OTransactionOptimistic.commit(OTransactionOptimistic.java:104)
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.commit(ODatabaseDocumentTx.java:2783)
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.commit(ODatabaseDocumentTx.java:2753)
        at com.tinkerpop.blueprints.impls.orient.OrientTransactionalGraph.commit(OrientTransactionalGraph.java:182)
     ..
Caused by: java.lang.NullPointerException: null
        at com.orientechnologies.common.directmemory.OByteBufferPool.acquireDirect(OByteBufferPool.java:310)
        at com.orientechnologies.orient.core.storage.cache.local.OWOWCache.cacheFileContent(OWOWCache.java:1293)
        at com.orientechnologies.orient.core.storage.cache.local.OWOWCache.load(OWOWCache.java:648)
        at com.orientechnologies.orient.core.storage.cache.local.twoq.O2QCache.updateCache(O2QCache.java:1110)
        at com.orientechnologies.orient.core.storage.cache.local.twoq.O2QCache.doLoad(O2QCache.java:351)
        at com.orientechnologies.orient.core.storage.cache.local.twoq.O2QCache.allocateNewPage(O2QCache.java:401)
        at com.orientechnologies.orient.core.storage.impl.local.paginated.atomicoperations.OAtomicOperation.commitChanges(OAtomicOperation.java:434)
        at com.orientechnologies.orient.core.storage.impl.local.paginated.atomicoperations.OAtomicOperationsManager.endAtomicOperation(OAtomicOperationsManager.java:460)
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.endStorageTx(OAbstractPaginatedStorage.java:2913)
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.commit(OAbstractPaginatedStorage.java:1421)
        ... 28 common frames omitted

**Comment by laa** [comment]
@jamieb22 it means that your direct memory settings are incorrect for this database and OS can not allocate needed amount of memory.

**Comment by laa** [comment]
@jamieb22 also please specify version of database to double check

**Comment by jamieb22** [comment]
Yeah, i think you're right. I had just figured it out directly after posting...one of your colleagues suggested to set the following:

export CATALINA_OPTS="-server -Dversion=enterpriseedition -Xloggc:/mnt/archive-four/gc.log -XX:+PrintGCDetails -XX
:+PrintGCTimeStamps -XX:+PrintGCDateStamps -XX:+PrintTenuringDistribution -XX:+PrintGCApplicationStoppedTime -Xms6g
 -XX:MetaspaceSize=256m -XX:MaxMetaspaceSize=256m -XX:+UseCompressedOops -XX:CompressedClassSpaceSize=128m -XX:-Use
AdaptiveSizePolicy -XX:InitialCodeCacheSize=48m -XX:ReservedCodeCacheSize=48m -XX:ParallelGCThreads=8 -XX:MaxDirect
MemorySize=8g -Dstorage.diskCache.bufferSize=20480"

When I return it back to 

export CATALINA_OPTS="-Dversion=enterpriseedition -Xmx6g -Xms256m -XX:MaxDirectMemorySize=512g -Dgraphdb.cache.size
=64"

it works better. I am still sending unrelated errors in the log however

**Comment by laa** [comment]
@jamieb22 I think that after such crash database should be exported to and imported from JSON otherwise you will see many such exceptions. Please make such import and close related issues if they are gone after this step.

**Comment by jamieb22** [comment]
Its not easy to do with fifty or so databases on one machine. Some of them are quite largely. It will take weeks to do that. The indexes seem particularly vulnerable to corruption. I am seeing this error everywhere in the logs
java.lang.NullPointerException: null
        at com.orientechnologies.orient.core.index.sbtree.local.OSBTree.findBucket(OSBTree.java:1754)
        at com.orientechnologies.orient.core.index.sbtree.local.OSBTree.get(OSBTree.java:200)
        at com.orientechnologies.orient.core.index.engine.OSBTreeIndexEngine.get(OSBTreeIndexEngine.java:128)
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.doGetIndexValue(OAbstract
PaginatedStorage.java:1777)
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.getIndexValue(OAbstractPa
ginatedStorage.java:1766)
        at com.orientechnologies.orient.core.index.OIndexOneValue.get(OIndexOneValue.java:56)
        at com.orientechnologies.orient.core.index.OIndexOneValue.get(OIndexOneValue.java:40)
        at com.orientechnologies.orient.core.index.OIndexAbstractDelegate.get(OIndexAbstractDelegate.java:58)
        at com.orientechnologies.orient.core.index.OIndexTxAwareOneValue.get(OIndexTxAwareOneValue.java:262)
        at com.orientechnologies.orient.core.index.OIndexTxAwareOneValue.get(OIndexTxAwareOneValue.java:40)
        at com.tinkerpop.blueprints.impls.orient.OrientBaseGraph.getVertices(OrientBaseGraph.java:813)
       ..com.google.api.client.googleapis.batch.BatchUnparsedResponse.parseAndCallback(BatchUnparsedResponse.java
:197)
        at com.google.api.client.googleapis.batch.BatchUnparsedResponse.parseNextResponse(BatchUnparsedResponse.jav
a:155)
        at com.google.api.client.googleapis.batch.BatchRequest.execute(BatchRequest.java:253)

**Comment by jamieb22** [comment]
I am also seeing the following error on one of the instances:

Caused by: java.lang.NullPointerException: null
        at com.orientechnologies.orient.core.storage.impl.local.paginated.base.ODurablePage.deserializeFromDirectMe
mory(ODurablePage.java:164)
        at com.orientechnologies.orient.core.index.sbtreebonsai.local.OSBTreeBonsaiBucket.getEntry(OSBTreeBonsaiBuc
ket.java:280)
        at com.orientechnologies.orient.core.index.sbtreebonsai.local.OSBTreeBonsaiLocal.findBucket(OSBTreeBonsaiLo
cal.java:1359)
        at com.orientechnologies.orient.core.index.sbtreebonsai.local.OSBTreeBonsaiLocal.loadEntriesMajor(OSBTreeBo
nsaiLocal.java:774)
        at com.orientechnologies.orient.core.index.sbtreebonsai.local.OSBTreeBonsaiLocal.getRealBagSize(OSBTreeBons
aiLocal.java:1462)
        at com.orientechnologies.orient.core.db.record.ridbag.sbtree.OSBTreeRidBag.updateSize(OSBTreeRidBag.java:10
29)
        at com.orientechnologies.orient.core.db.record.ridbag.sbtree.OSBTreeRidBag.size(OSBTreeRidBag.java:748)
        at com.orientechnologies.orient.core.db.record.ridbag.ORidBag.size(ORidBag.java:191)
        at com.tinkerpop.blueprints.impls.orient.OrientVertex.getEdges(OrientVertex.java:840)
        at com.tinkerpop.blueprints.impls.orient.OrientVertex.getEdges(OrientVertex.java:768)
        at com.tinkerpop.blueprints.util.DefaultVertexQuery$DefaultVertexQueryIterable.<init>(DefaultVertexQuery.ja
va:110)
        at com.tinkerpop.blueprints.util.DefaultVertexQuery.edges(DefaultVertexQuery.java:80)
        at com.tinkerpop.pipes.transform.VertexQueryPipe.processNextStart(VertexQueryPipe.java:113)
        at com.tinkerpop.pipes.transform.VertexQueryPipe.processNextStart(VertexQueryPipe.java:19)
        at com.tinkerpop.pipes.AbstractPipe.hasNext(AbstractPipe.java:98)
        at com.tinkerpop.pipes.transform.OrderPipe.processNextStart(OrderPipe.java:86)
        at com.tinkerpop.pipes.AbstractPipe.next(AbstractPipe.java:89)
        at com.tinkerpop.pipes.filter.FilterFunctionPipe.processNextStart(FilterFunctionPipe.java:23)
        at com.tinkerpop.pipes.AbstractPipe.hasNext(AbstractPipe.java:98)
        at com.tinkerpop.pipes.util.Pipeline.hasNext(Pipeline.java:105)
        at com.stimulus.archiva.ig.a(MailArchiva:143)
        at com.stimulus.archiva.database.DatabaseService.a(MailArchiva:496)
        at com.stimulus.archiva.database.DatabaseService.a(MailArchiva:455)
        at com.stimulus.archiva.database.DatabaseService.a(MailArchiva:385)
        ... 19 common frames omitted

**Comment by laa** [comment]
@jamieb22 those NPEs are caused by the previous issue we found a reason for it going to fix soon. 
Once we fix also direct memory issues we will release next 2.2.15 version of ODB.
You need to rebuild indexes after that or even better to make export/import as I wrote above sorry for that.

**Comment by jamieb22** [comment]
Can you please tell me the logic behind why we need to set -XX:MaxDirectMemorySize=512g, when a machine only has say 32GB of physical RAM? I can't figure it out. Also, other databases such as H2 don't require any custom direct memory settings, why is Orient DB any different? Cant you tune the database functioning for the default JVM settings?

**Comment by laa** [comment]
@jamieb22 other databases either use Unsafe (such as Cassandra ) which will be deprecated in next releases of work in heap memory which causes GC pauses. -XX:MaxDirectMemorySize that is limit of maximum direct memory like Xmx but not demand to allocate it.

**Comment by jamieb22** [comment]
How much direct memory does Orient actually consume? if you take a look at the previous setting that didn't work, maximum direct memory is set to 8GB (see: -XX:MaxDirect MemorySize=8g). Surely, this should be more than sufficient for caches etc.? Why doesn't Orient DB need more than 8GB? I still don't get it.

**Comment by jamieb22** [comment]
Unless I am getting the complete wrong end of the stick, I would expect Orient DB consumption of direct memory should be in the KB or MB, not GB.

**Comment by laa** [comment]
@jamieb22 the most sufficient for caches to take as much memory as possible in such way you avoid disk IO overhead and work on memory for us many frequently accessed items as possible. MaxDirect MemorySize is a maximum limit of direct memory from JVM perspective, JVM does not prohibit you to allocate as many new objects as possible, but it will throw OOM in a case of you exceed limit the same is with direct memory. In your settings you had disk cache size storage.diskCache.bufferSize=20480 so it is 20GB which of course much bigger than 8 GB.

**Comment by jamieb22** [comment]
Thanks for the explanation. I believe it was your colleague that came up with those settings. May I suggest that Orient DB should focus on actually getting a stable working database, rather that push for top performance. Every single build for the past two years has had critical bugs in it resulting in data corruption. In my opinion index and data corruption is the biggest problem facing Orient DB, and has been ever since I started working with it.

**Comment by laa** [comment]
@jamieb22 every build as you commented did not introduce new bugs in reality because of changes in
 every build we decreased an amount of bugs which are reported by users for a storage engine to *three bugs*.  
One for increased consumption of non-heap memory (it is not related to direct memory), 
one for broken data files for very specific cases as yours (actually your issues mostly the source of such specific cases) and one for incorrect initialization of index ids after the crash. 
IMHO having only three bugs all over very complex storage engine is a definite sign that we spend our development time on a right set of tasks. 
About again new bugs in new builds, a bug which you pointed about NPE in the index was caused by the code which was introduced even when I was not part of the project,
 so many many years ago and is not part of new builds. The rest of issues are performance issues. 
 If for our users' functionality is too slow and they will use it only if it is faster we bound to make a system faster otherwise we will be out of the market because people will choose more rapid systems and not body will be able to fix the rest of the bugs in storage engine too. So every development is a balance between new and old features, and decreasing of an amount of bugs to three sign for me that this balance is correct. 
 Hope you will also agree that reducing of a sum of bugs to three is a good sign that developers take system stability seriously.

**Comment by jamieb22** [comment]
Andrey, performance is nothing without reliability, durability, etc. When it comes to a database, it is a non negotiable. I wish I could take a video of our experiences over the past few years, to show you what I refer to. Over the years, we have been forced to reduce our dependency on Orient DB. Even though, we actually need the functionality of a graph DB, we're putting more information in H2, because Orient DB cannot be trusted to preserve data.

**Comment by laa** [comment]
@jamieb22 I agree with you, but if there will be no developers who will fix issues? The second question which you did not answer. 
If an amount of issues reduced to three and issue which caused NPE in your case is introduced in version prior 1.0 does not mean that we take new bugs seriously?

**Comment by jamieb22** [comment]
I am not saying the Orient DB team is not willing to fix bugs. Its obvious the Orient DB team is super enthusiastic and for that we are grateful.  However, I do believe that Orient DB may not be entirely listening to overall feedback from its user base. The message is this: Currently, Orient DB doesn't work reliably in real production environments, nor does it preserve data over time. It is still plagued with critical bugs.

With our product, we spent years and years watching it running in live environments using a profiler, and observing its behavior. There is no substitute for this. This is the missing piece, along with the fact that I feel you guys are too gungho in introducing new features and place far too much of an emphasis on performance benchmarking. Everyone knows that mature databases tend to be slower than upstarts, mostly because mature databases have more locking, safety checks that are designed to ensure the integrity of data.

**Comment by laa** [comment]
@jamieb22 " Currently, Orient DB doesn't work reliably in real production environments, nor does it preserve data over time. It is still plagued with critical bugs." If that is true who pays bills then? We do have a venture capital in company and all money which we have we have by selling of our services and many users renew contracts again.  I think much better to say that "Currently, Orient DB doesn't work reliably in *your* very specific production environments, nor does it preserve data over time. It is still plagued with critical bugs."

About "plague" of bugs how many bugs did  you count at the moment , could you send links to me ?

**Comment by jamieb22** [comment]
Andrey, you can look at our github history and see how many bugs Valentin and I have reported over time.  To further illustrate,  I just started our server now, when Orient loads an older database, lone and behold, it comes up with a NullPointerException on the OIndexAbstract.getVersion function. From our software standpoint, it is unusable. NullPointerException's appear to be the most common Orient exception, which leads me to think that there is not enough validation happening in Orient code.
---
java.lang.NullPointerException: null
	at com.orientechnologies.orient.core.index.OIndexAbstract.getVersion(OIndexAbstract.java:787)
	at com.orientechnologies.orient.core.index.OIndexAbstractDelegate.getVersion(OIndexAbstractDelegate.java:275)
	at com.stimulus.archiva.database.blueprints.BluePrintDatabaseUtil.dropOldIndexes(BluePrintDatabaseUtil.java:124)

**Comment by jamieb22** [comment]
Here another bug I just discovered. What I did was start the OrientDatabase internally, stop it, and then delete the database files from the file system, then start the database up again (all the while the Java process stays running). When Orient DB is started the second time, it comes with an error "Error occurred while executing a write operation to database 'archiva$humpty' due to limited free space on the disk". This error is outputted when there is in fact plenty of disk space available:
Filesystem      Size   Used  Avail Capacity iused      ifree %iused  Mounted on
/dev/disk1     465Gi  405Gi   60Gi    88% 2760793 4292206486    0%   /

2017-01-12 11:51:19 h.c.s.a.d.DatabaseService [ERROR] failed to connect to database:Error during saving of record with rid #0:1
	DB name="archiva$humpty"
com.orientechnologies.orient.core.exception.ODatabaseException: Error during saving of record with rid #0:1
	DB name="archiva$humpty"
	at com.orientechnologies.orient.core.tx.OTransactionNoTx.saveRecord(OTransactionNoTx.java:197)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.save(ODatabaseDocumentTx.java:2649)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.save(ODatabaseDocumentTx.java:101)
	at com.orientechnologies.orient.core.record.impl.ODocument.save(ODocument.java:1802)
	at com.orientechnologies.orient.core.record.impl.ODocument.save(ODocument.java:1798)
	at com.orientechnologies.orient.core.metadata.schema.OSchemaShared$2.call(OSchemaShared.java:1319)
	at com.orientechnologies.orient.core.db.OScenarioThreadLocal.executeAsDistributed(OScenarioThreadLocal.java:70)
	at com.orientechnologies.orient.core.metadata.schema.OSchemaShared.saveInternal(OSchemaShared.java:1314)
	at com.orientechnologies.orient.core.metadata.schema.OSchemaShared.releaseSchemaWriteLock(OSchemaShared.java:627)
	at com.orientechnologies.orient.core.metadata.schema.OSchemaShared.releaseSchemaWriteLock(OSchemaShared.java:616)
	at com.orientechnologies.orient.core.metadata.schema.OSchemaShared.doCreateClass(OSchemaShared.java:1052)
	at com.orientechnologies.orient.core.metadata.schema.OSchemaShared.createClass(OSchemaShared.java:378)
	at com.orientechnologies.orient.core.metadata.schema.OSchemaShared.createClass(OSchemaShared.java:363)
	at com.orientechnologies.orient.core.metadata.schema.OSchemaProxy.createClass(OSchemaProxy.java:95)
	at com.tinkerpop.blueprints.impls.orient.OrientBaseGraph$5.call(OrientBaseGraph.java:1275)
	at com.tinkerpop.blueprints.impls.orient.OrientBaseGraph$5.call(OrientBaseGraph.java:1273)
	at com.tinkerpop.blueprints.impls.orient.OrientBaseGraph.executeOutsideTx(OrientBaseGraph.java:1758)
	at com.tinkerpop.blueprints.impls.orient.OrientBaseGraph.createVertexType(OrientBaseGraph.java:1273)
	at com.tinkerpop.blueprints.impls.orient.OrientBaseGraph.createVertexType(OrientBaseGraph.java:1245)
	at com.tinkerpop.blueprints.impls.orient.OrientBaseGraph.createVertexType(OrientBaseGraph.java:1220)
	..
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: com.orientechnologies.orient.core.exception.OLowDiskSpaceException: Error occurred while executing a write operation to database 'archiva$humpty' due to limited free space on the disk (0 MB). The database is now working in read-only mode. Please close the database (or stop OrientDB), make room on your hard drive and then reopen the database. The minimal required space is 256 MB. Required space is now set to 256MB (you can change it by setting parameter storage.diskCache.diskFreeSpaceLimit) .
	DB name="archiva$humpty"
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.checkLowDiskSpaceFullCheckpointRequestsAndBackgroundDataFlushExceptions(OAbstractPaginatedStorage.java:4054)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.updateRecord(OAbstractPaginatedStorage.java:1102)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.executeSaveRecord(ODatabaseDocumentTx.java:2123)
	at com.orientechnologies.orient.core.tx.OTransactionNoTx.saveRecord(OTransactionNoTx.java:178)
	... 27 common frames omitted

**Comment by laa** [comment]
@jamieb22 you created issue for that we provided fix and asked for feedback . But you did not answer. 
All issues which you created we either  fixed or asked for additional data. But typicaly you do not answer on our questions and obviously we can not fix such issues. Could you provide me links on active issues which  you suppose still exists inside of database, so I will estimate how plague is it ?

**Comment by laa** [comment]
"OLowDiskSpaceException" means that you have not enough space this issue is already fixed in develop-cache branch and will be moved to 2.2.x once I will fix all tests. Any thing else?

Could you either confirm or reopen issue about 
"java.lang.NullPointerException: null
at com.orientechnologies.orient.core.index.OIndexAbstract.getVersion(OIndexAbstract.java:787)"

did you try fix which we asked you to try?
Also if you wish your issues fixed as do suggest you to answer when we ask to confirm fix, usually we asked twice and if users ignores question for 14-20 days we close issue.

**Comment by laa** [comment]
Will be cool if you create an issue in a bug tracker, then we will count how big our "plague" of bugs is. 
Looking forward to reading, estimate and count all issues which you send to us.

Also, I hope that you will answer our questions when we ask for additional information or confirmation of fix.

**Comment by jamieb22** [comment]
I just tried the same start, stop, delete database, start procedure in a productive environment, and I get a different error this time:

```
su/debug/debug.log:com.orientechnologies.common.io.OIOException: File /var/opt/mailarchiva/su/database/archiva/su/ouser.cpm was not found
su/debug/debug.log:        at com.orientechnologies.orient.core.storage.fs.OFileClassic.open(O
FileClassic.java:603)
su/debug/debug.log:        at com.orientechnologies.common.collection.closabledictionary.OClos
ableEntry.makeAcquiredFromClosed(OClosableEntry.java:98)
su/debug/debug.log:        at com.orientechnologies.common.collection.closabledictionary.OClos
ableLinkedContainer.acquire(OClosableLinkedContainer.java:272)
su/debug/debug.log:        at com.orientechnologies.orient.core.storage.cache.local.OWOWCache.
getFilledUpTo(OWOWCache.java:731)
su/debug/debug.log:        at com.orientechnologies.orient.core.storage.impl.local.paginated.b
ase.ODurableComponent.getFilledUpTo(ODurableComponent.java:135)
su/debug/debug.log:        at com.orientechnologies.orient.core.storage.impl.local.paginated.O
ClusterPositionMap.getFirstPosition(OClusterPositionMap.java:653)
su/debug/debug.log:        at com.orientechnologies.orient.core.storage.impl.local.paginated.O
PaginatedCluster.getFirstPosition(OPaginatedCluster.java:1423)
su/debug/debug.log:        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPa
ginatedStorage.getClusterDataRange(OAbstractPaginatedStorage.java:791)
```

**Comment by laa** [comment]
@jamieb22 could you create a separate issue for each bug, so we will estimate an amount of issues which you call "plague of issues" and fix each of them. Please do not stack issues in already closed issue, because we can not track issues in such manner. Also please reopen and answer on our questions for issues which you think we closed incorrectly.  I am really looking forward to counting this plug of issue to fix all of them and decrease this plague to nothing. Because without proper tracking of issues and without feedback from users we merely can not fix issues which they are worried about.

**Comment by jamieb22** [comment]
I've just added a comment for https://github.com/orientechnologies/orientdb/issues/6651. Can you reopen the bug? We also are pretty sure that there is some kind of memory leak in Orient DB code. Our servers keep dying, heap space is ok, but virtual memory is consumed.
