### ISSUE TITLE
java.lang.ClassNotFoundException: com.orientechnologies.orient.server.distributed.ODistributedException

### ISSUE THREAD

**Issue by aaronjwhiteside** [orientechnologies/orientdb#7071]
## OrientDB Version, operating system, or hardware.
- v2.2.14

## Operating System
- [ ] Linux
- [X] MacOSX
- [ ] Windows
- [ ] Other Unix
- [ ] Other, name? 

## Expected behavior and actual behavior

Exception from the client side:
```
Jan 11, 2017 11:45:47 AM com.orientechnologies.common.log.OLogManager log
SEVERE: Error during exception deserialization
java.lang.ClassNotFoundException: com.orientechnologies.orient.server.distributed.ODistributedException
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at java.io.ObjectInputStream.resolveClass(ObjectInputStream.java:628)
	at java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:1620)
	at java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1521)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1781)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1353)
	at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2018)
	at java.io.ObjectInputStream.defaultReadObject(ObjectInputStream.java:503)
	at java.lang.Throwable.readObject(Throwable.java:914)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at java.io.ObjectStreamClass.invokeReadObject(ObjectStreamClass.java:1058)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1909)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1808)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1353)
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:373)
	at com.orientechnologies.orient.client.binary.OChannelBinaryAsynchClient.throwSerializedException(OChannelBinaryAsynchClient.java:429)
	at com.orientechnologies.orient.client.binary.OChannelBinaryAsynchClient.handleStatus(OChannelBinaryAsynchClient.java:393)
	at com.orientechnologies.orient.client.binary.OChannelBinaryAsynchClient.beginResponse(OChannelBinaryAsynchClient.java:275)
	at com.orientechnologies.orient.client.binary.OChannelBinaryAsynchClient.beginResponse(OChannelBinaryAsynchClient.java:167)
	at com.orientechnologies.orient.client.remote.OStorageRemote.beginResponse(OStorageRemote.java:2167)
	at com.orientechnologies.orient.client.remote.OStorageRemote$6.execute(OStorageRemote.java:548)
	at com.orientechnologies.orient.client.remote.OStorageRemote$6.execute(OStorageRemote.java:542)
	at com.orientechnologies.orient.client.remote.OStorageRemote$1.execute(OStorageRemote.java:164)
	at com.orientechnologies.orient.client.remote.OStorageRemote.baseNetworkOperation(OStorageRemote.java:235)
	at com.orientechnologies.orient.client.remote.OStorageRemote.asyncNetworkOperation(OStorageRemote.java:156)
	at com.orientechnologies.orient.client.remote.OStorageRemote.createRecord(OStorageRemote.java:528)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.executeSaveRecord(ODatabaseDocumentTx.java:2117)
	at com.orientechnologies.orient.core.tx.OTransactionNoTx.saveNew(OTransactionNoTx.java:235)
	at com.orientechnologies.orient.core.tx.OTransactionNoTx.saveRecord(OTransactionNoTx.java:168)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.save(ODatabaseDocumentTx.java:2649)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.save(ODatabaseDocumentTx.java:2583)
	at OrientTest.lambda$run$0(OrientTest.java:78)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

```

Exception from the server side (node1 only)
```
Error executing request
java.lang.NullPointerException
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.waitDistribuedIsOnline(ONetworkProtocolBinary.java:449)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.onBeforeOperationalRequest(ONetworkProtocolBinary.java:420)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.sessionRequest(ONetworkProtocolBinary.java:303)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.execute(ONetworkProtocolBinary.java:197)
	at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:77)
```

I'm also seeing a lot of these in the node1 logs.
```
2017-01-11 11:45:47:397 INFO  Local node 'node1' is not the owner for cluster 'Party_node2' (it is 'node2'). Switching to a valid cluster of the same class: 'Party_node2' [ODistributedStorage]
2017-01-11 11:45:47:399 INFO  Local node 'node1' is not the owner for cluster 'Party_node2' (it is 'node2'). Switching to a valid cluster of the same class: 'Party_node3' [ODistributedStorage]
2017-01-11 11:45:48:935 INFO  Local node 'node1' is not the owner for cluster 'Party_node2' (it is 'node2'). Switching to a valid cluster of the same class: 'Party_node3' [ODistributedStorage]
2017-01-11 11:45:48:935 INFO  Local node 'node1' is not the owner for cluster 'Party_node2' (it is 'node2'). Switching to a valid cluster of the same class: 'Party_node1' [ODistributedStorage]
2017-01-11 11:45:48:935 INFO  Local node 'node1' is not the owner for cluster 'Party_node2' (it is 'node2'). Switching to a valid cluster of the same class: 'Party_node2' [ODistributedStorage]

```

## Steps to reproduce the problem
Three nodes (node1, node2, node3) started in distributed mode, each with the same config as below.

There seems to be an issue with cluster ownership though, despite the config and naming convention of the clusters.

```
LIST CLUSTERS
...
|35  |party_node1|  43|Party    |                 | 5058|   node1    |[node2,node3]|        true        |
|36  |party_node2|  44|Party    |                 |    0|   node1    |[node2,node3]|        true        |
|37  |party_node3|  51|Party    |                 |    0|   node1    |[node2,node3]|        true        |
...
```

```
        for (int i = 0; i < count; i++) {
            completionService.submit(() -> {
                ODatabaseDocumentTx conn = pool.acquire();
                try {
                    conn.activateOnCurrentThread();
                    ODocument party = new ODocument("Party");
                    party.field("name", "Test");
                    party.field("type", "TEST");

                    String cluster = Thread.currentThread().getId() % 2 == 0 ? "Party_node1" : "Party_node2";
                    conn.save(party, cluster);

                } finally {
                    conn.close();
                }
            }, null);
        }
```
```
    "Party_node1": {
      "@type": "d",
      "@version": 0,
      "servers": [
        "node1",
        "node2",
        "node3",
        "<NEW_NODE>"
      ]
    },
    "Party_node2": {
      "@type": "d",
      "@version": 0,
      "servers": [
        "node2",
        "node1",
        "node3",
        "<NEW_NODE>"
      ]
    },
    "Party_node3": {
      "@type": "d",
      "@version": 0,
      "servers": [
        "node3",
        "node1",
        "node2",
        "<NEW_NODE>"
      ]
    }
```

**Comment by lvca** [comment]
Some of the OrientDB jars were missing from the classpath. If you are you using OSGi the issue has been fixed.
