### ISSUE TITLE
Error on closing file

### ISSUE THREAD

**Issue by rdelangh** [orientechnologies/orientdb#7075]
## OrientDB Version, operating system, or hardware.
- v2.2.14

## Operating System
- [x] Linux

Somehow one of the cluster files has got into troubles:
During a query from class "cdr_icx_20170108" the following server logs are spawned:

```
Error on closing file /opt/orientdb/databases/cdrarch/cl_cdr_icx_20170108_p1.pcl
java.io.IOException: Stream Closed
        at java.io.RandomAccessFile.length(Native Method)
        at com.orientechnologies.orient.core.storage.fs.OFileClassic.close(OFileClassic.java:643)
        at com.orientechnologies.common.collection.closabledictionary.OClosableEntry.makeClosed(OClosableEntry.java:168)
        at com.orientechnologies.common.collection.closabledictionary.OClosableLinkedContainer.evict(OClosableLinkedContainer.java:707)
        at com.orientechnologies.common.collection.closabledictionary.OClosableLinkedContainer.access$400(OClosableLinkedContainer.java:33)
        at com.orientechnologies.common.collection.closabledictionary.OClosableLinkedContainer$LogOpen.run(OClosableLinkedContainer.java:775)
        at com.orientechnologies.common.collection.closabledictionary.OClosableLinkedContainer.drainWriteBuffer(OClosableLinkedContainer.java:666)
        at com.orientechnologies.common.collection.closabledictionary.OClosableLinkedContainer.drainBuffers(OClosableLinkedContainer.java:617)
        at com.orientechnologies.common.collection.closabledictionary.OClosableLinkedContainer.tryToDrainBuffers(OClosableLinkedContainer.java:606)
        at com.orientechnologies.common.collection.closabledictionary.OClosableLinkedContainer.afterWrite(OClosableLinkedContainer.java:549)
        at com.orientechnologies.common.collection.closabledictionary.OClosableLinkedContainer.logOpen(OClosableLinkedContainer.java:510)
        at com.orientechnologies.common.collection.closabledictionary.OClosableLinkedContainer.acquire(OClosableLinkedContainer.java:284)
        at com.orientechnologies.orient.core.storage.cache.local.OWOWCache$PeriodicalFuzzyCheckpointTask.run(OWOWCache.java:1768)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Error during fuzzy checkpoint
com.orientechnologies.common.io.OIOException: Error on closing file /opt/orientdb/databases/cdrarch/cl_cdr_icx_20170108_p1.pcl
        at com.orientechnologies.orient.core.storage.fs.OFileClassic.close(OFileClassic.java:659)
        at com.orientechnologies.common.collection.closabledictionary.OClosableEntry.makeClosed(OClosableEntry.java:168)
        at com.orientechnologies.common.collection.closabledictionary.OClosableLinkedContainer.evict(OClosableLinkedContainer.java:707)
        at com.orientechnologies.common.collection.closabledictionary.OClosableLinkedContainer.access$400(OClosableLinkedContainer.java:33)
        at com.orientechnologies.common.collection.closabledictionary.OClosableLinkedContainer$LogOpen.run(OClosableLinkedContainer.java:775)
        at com.orientechnologies.common.collection.closabledictionary.OClosableLinkedContainer.drainWriteBuffer(OClosableLinkedContainer.java:666)
        at com.orientechnologies.common.collection.closabledictionary.OClosableLinkedContainer.drainBuffers(OClosableLinkedContainer.java:617)
        at com.orientechnologies.common.collection.closabledictionary.OClosableLinkedContainer.tryToDrainBuffers(OClosableLinkedContainer.java:606)
        at com.orientechnologies.common.collection.closabledictionary.OClosableLinkedContainer.afterWrite(OClosableLinkedContainer.java:549)
        at com.orientechnologies.common.collection.closabledictionary.OClosableLinkedContainer.logOpen(OClosableLinkedContainer.java:510)
        at com.orientechnologies.common.collection.closabledictionary.OClosableLinkedContainer.acquire(OClosableLinkedContainer.java:284)
        at com.orientechnologies.orient.core.storage.cache.local.OWOWCache$PeriodicalFuzzyCheckpointTask.run(OWOWCache.java:1768)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.IOException: Stream Closed
        at java.io.RandomAccessFile.length(Native Method)
        at com.orientechnologies.orient.core.storage.fs.OFileClassic.close(OFileClassic.java:643)
        ... 18 more
```

That query now runs very slow.

Is that file corrupted ? If so, how to fix it? If not, why these messages?

**Comment by rdelangh** [comment]
During restart, the server logs get the following:

```
...

2017-01-12 20:17:13:267 INFO  OrientDB Server is active v2.2.14 (build 2.2.x@r483093384e4fdbe825e2de0950f007776ee27a84; 2016-12-22 14:57:07+0000). [OServer]
2017-01-12 20:17:16:946 WARNI {db=OSystem} Storage 'OSystem' was not closed properly. Will try to recover from write ahead log [OLocalPaginatedStorage]
2017-01-12 20:17:16:947 INFO  {db=OSystem} Looking for last checkpoint... [OLocalPaginatedStorage]
2017-01-12 20:17:16:959 INFO  {db=OSystem} FULL checkpoint found. [OLocalPaginatedStorage]
2017-01-12 20:17:16:960 WARNI {db=OSystem} FULL checkpoint has not completed. [OLocalPaginatedStorage]
2017-01-12 20:17:16:961 WARNI {db=OSystem} Restore will start from the previous checkpoint. [OLocalPaginatedStorage]
2017-01-12 20:17:16:961 INFO  {db=OSystem} Data restore procedure from FUZZY checkpoint is started. [OLocalPaginatedStorage]
2017-01-12 20:17:16:964 WARNI {db=OSystem} Record OFuzzyCheckpointStartRecord{lsn=LSN{segment=0, position=3104382}} com.orientechnologies.orient.core.storage.impl.local.paginated.wal.OFuzzyCheckpointStartRecord{lsn=null, previousCheckpoint=LSN{segment=0, position=3104342}} will be skipped during data restore [OLocalPaginatedStorage]
2017-01-12 20:17:16:972 INFO  {db=OSystem} 1 operations were processed, current LSN is LSN{segment=0, position=3104382} last LSN is LSN{segment=0, position=3104485} [OLocalPaginatedStorage]
2017-01-12 20:17:16:972 WARNI {db=OSystem} Record OFuzzyCheckpointStartRecord{lsn=LSN{segment=0, position=3104422}} com.orientechnologies.orient.core.storage.impl.local.paginated.wal.OFuzzyCheckpointStartRecord{lsn=null, previousCheckpoint=LSN{segment=0, position=3104382}} will be skipped during data restore [OLocalPaginatedStorage]
2017-01-12 20:17:16:973 WARNI {db=OSystem} Record com.orientechnologies.orient.core.storage.impl.local.paginated.wal.OFullCheckpointStartRecord{lsn=LSN{segment=0, position=3104462}, previousCheckpoint=LSN{segment=0, position=3104422}} will be skipped during data restore [OLocalPaginatedStorage]
2017-01-12 20:17:16:973 INFO  {db=OSystem} Storage data recover was completed [OLocalPaginatedStorage]
```

-> anything usefull in here?

**Comment by rdelangh** [comment]
Without doing any activities (not opening a connection to a database), I shutdown the server again. 
Then restarted it.
No such server logs.

I opened a connection to database "cdrarch", which immediately spawns the following messages:
```

2017-01-12 20:20:46:666 WARNI {db=cdrarch} Storage 'cdrarch' was not closed properly. Will try to recover from write ahead log [OLocalPaginatedStorage]
2017-01-12 20:20:46:667 INFO  {db=cdrarch} Looking for last checkpoint... [OLocalPaginatedStorage]
2017-01-12 20:20:46:668 INFO  {db=cdrarch} FULL checkpoint found. [OLocalPaginatedStorage]
2017-01-12 20:20:46:669 WARNI {db=cdrarch} FULL checkpoint has not completed. [OLocalPaginatedStorage]
2017-01-12 20:20:46:671 WARNI {db=cdrarch} Restore will start from the previous checkpoint. [OLocalPaginatedStorage]
2017-01-12 20:20:46:671 INFO  {db=cdrarch} Data restore procedure from FUZZY checkpoint is started. [OLocalPaginatedStorage]
2017-01-12 20:20:46:674 WARNI {db=cdrarch} Record OFuzzyCheckpointStartRecord{lsn=LSN{segment=134130, position=122819911}} com.orientechnologies.orient.core.storage.impl.local.paginated.wal.OFuzzyCheckpointStartRecord{lsn=null, previousCheckpoint=LSN{segment=134130, position=122819871}} will be skipped during data restore [OLocalPaginatedStorage]
2017-01-12 20:20:46:674 INFO  {db=cdrarch} 1 operations were processed, current LSN is LSN{segment=134130, position=122819911} last LSN is LSN{segment=134130, position=122820014} [OLocalPaginatedStorage]
2017-01-12 20:20:46:675 WARNI {db=cdrarch} Record OFuzzyCheckpointStartRecord{lsn=LSN{segment=134130, position=122819951}} com.orientechnologies.orient.core.storage.impl.local.paginated.wal.OFuzzyCheckpointStartRecord{lsn=null, previousCheckpoint=LSN{segment=134130, position=122819911}} will be skipped during data restore [OLocalPaginatedStorage]
2017-01-12 20:20:46:676 WARNI {db=cdrarch} Record com.orientechnologies.orient.core.storage.impl.local.paginated.wal.OFullCheckpointStartRecord{lsn=LSN{segment=134130, position=122819991}, previousCheckpoint=LSN{segment=134130, position=122819951}} will be skipped during data restore [OLocalPaginatedStorage]
```

So did a shutdown once more, followed by a restart (no server logs), then open dbase connection again: no server error logs.

Launced the query again: no server error logs, fast results.

-> issue can be closed...

**Comment by laa** [comment]
@rdelangh seems like you have more open files than the sum of WAL files and data files. You have two possibilities there limit an amount of data files even more, or increase an amount of open files allowed by a system for a single thread. IMHO I suggest you do last one, but if you prefer to keep less amount of open files in OrientDB you may set parameter storage.openFiles.limit to 256 for example, I suppose this will be enough

**Comment by rdelangh** [comment]
@laa thx Andrey
Can you tell me what the current (default) limit is for OrientDB?
The Unix (= Ubuntu in our case) limit is currently set on 1024 open files per process.

**Comment by cmassi** [comment]
You can set -Denvironment.dumpCfgAtStartup=true and check the value, e.g:
...
- STORAGE
  + storage.openFiles.limit = 512

**Comment by laa** [comment]
@rdelangh our limit is 512, so we will hit the problem only if you additionally have 512  WAL files +- 20.  We can not know for sure whether there were so much WAL  files though it is possible. But I suppose if you set limit about 65536 open files it will solve issues with WAL files too. In 3.0 we will use the same pool for WAL files as for data files, so this problem will be gone forever. Also, dev branch is from two till five times faster than 2.2.x branch (I will provide numbers in new blog post soon) so I do suggest you to use it once it will be released.

**Comment by rdelangh** [comment]
@laa ok, will set the limit in the O/S already to (surely not excessive) higher level, this can never harm nowaday (enough RAM).
And looking forward to that 'dev' branch !!

**Comment by laa** [comment]
Fixed
