### ISSUE TITLE
ouser.cpm was not found

### ISSUE THREAD

**Issue by jamieb22** [orientechnologies/orientdb#7079]
## OrientDB Version, operating system, or hardware.
- v2.2.14

## Operating System
- [X ] Linux

## Expected behavior and actual behavior

Our application is multitenant and has one orient database per internal "instance". After starting the application, we may "shutdown" an instance to perform maintenance (all the while, the JVM stays running). The internal shutdown procedure involves calls OrientGraphFactory.close(). Theoretically, the database should be closed. However, if we then decide to delete the  files pertaining to that instance from disk and then startup the instance (i.e. new OrientGraphFactory) then, we get an error stating that ouser.cpm was not found.  How can this come about? Could it be that the shared cache is not being cleared correctly of the instance's data after the database is closed?

```
2017-01-13 17:59:24 t.c.s.a.d.DatabaseService [ERROR] failed to connect to database:File /var/opt/mailarchiva/true/database/archiva/true/ouser.cpm was not found
com.orientechnologies.common.io.OIOException: File /var/opt/mailarchiva/true/database/archiva/true/ouser.cpm was not found
        at com.orientechnologies.orient.core.storage.fs.OFileClassic.open(OFileClassic.java:581)
        at com.orientechnologies.common.collection.closabledictionary.OClosableEntry.makeAcquiredFromClosed(OClosableEntry.java:98)
        at com.orientechnologies.common.collection.closabledictionary.OClosableLinkedContainer.acquire(OClosableLinkedContainer.java
:272)
        at com.orientechnologies.orient.core.storage.cache.local.OWOWCache.getFilledUpTo(OWOWCache.java:731)
        at com.orientechnologies.orient.core.storage.impl.local.paginated.base.ODurableComponent.getFilledUpTo(ODurableComponent.jav
a:135)
        at com.orientechnologies.orient.core.storage.impl.local.paginated.OClusterPositionMap.getFirstPosition(OClusterPositionMap.j
ava:653)
        at com.orientechnologies.orient.core.storage.impl.local.paginated.OPaginatedCluster.getFirstPosition(OPaginatedCluster.java:
1423)
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.getClusterDataRange(OAbstractPaginatedStor
age.java:791)
        at com.orientechnologies.orient.core.iterator.ORecordIteratorClusters.updateClusterRange(ORecordIteratorClusters.java:408)
        at com.orientechnologies.orient.core.iterator.ORecordIteratorClass.config(ORecordIteratorClass.java:139)
        at com.orientechnologies.orient.core.iterator.ORecordIteratorClass.<init>(ORecordIteratorClass.java:90)
        at com.orientechnologies.orient.core.iterator.ORecordIteratorClass.<init>(ORecordIteratorClass.java:68)
        at com.orientechnologies.orient.core.sql.OCommandExecutorSQLResultsetAbstract.searchInClasses(OCommandExecutorSQLResultsetAb
stract.java:479)
        at com.orientechnologies.orient.core.sql.OCommandExecutorSQLResultsetAbstract.searchInClasses(OCommandExecutorSQLResultsetAb
stract.java:468)
        at com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.searchInClasses(OCommandExecutorSQLSelect.java:1004)
        at com.orientechnologies.orient.core.sql.OCommandExecutorSQLResultsetAbstract.assignTarget(OCommandExecutorSQLResultsetAbstr
act.java:209)
        at com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.assignTarget(OCommandExecutorSQLSelect.java:530)
        at com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.executeSearch(OCommandExecutorSQLSelect.java:512)
        at com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.execute(OCommandExecutorSQLSelect.java:488)

```

**Comment by jamieb22** [comment]
To add to this, on Linux, if I shutdown an OrientGraphFactory..

```
databaseUtils.getGraphFactory().getDatabase().close();
databaseUtils.getGraphFactory().close();
```
Then try to connect to the database from the Orient console... it says Error: com.orientechnologies.orient.core.exception.OStorageException: Can not open storage it is acquired by other process. Surely if I've shut the database down, I should be able to use it again? I've double checked all OrientGraph objects, and they are all being closed.

Connecting to database [plocal:/var/opt/mailarchiva/open/database/archiva/open] with user 'admin'...
Error: com.orientechnologies.orient.core.exception.OStorageException: Cannot open local storage '/var/opt/mailarchiva/open/database/archiva/open' with mode=rw
        DB name="open"

**Comment by laa** [comment]
"Theoretically, the database should be closed." That is not true,  database (in your terminology) is open till JVM is running when you make. OrientGraphFactory.close() closes only connection to database.  If you close connection storage still will be open. But storage itself you as you call database still is open.  "shared cache is not being cleared correctly" it is not cleared if a database is still open. To close a database, you should call following commands:

1.  storage = database.getStorage 
2.  database.close
3. storage.close(true, false)

The database is the only connection to the storage, but not storage itself. 

P.S. If you do maintenance with files which you think are closed, obviously your data will be broken and will be lost.

**Comment by laa** [comment]
I close the issue as invalid. But if you repeat those steps and bug will be reproduced, please feel free to reopen it.

**Comment by laa** [comment]
P.S. Also if you make backups or move/copy files when JVM is running but storage is not closed move data will be broken on 100%.
