### ISSUE TITLE
NullPointerException OEngineLocalPaginated.changeCacheSize

### ISSUE THREAD

**Issue by jamieb22** [orientechnologies/orientdb#7088]
## OrientDB Version, operating system, or hardware.
- v2.2.15-Snapshot

## Operating System
- [X ] Linux
 
## Expected behavior and actual behavior

```
2017-01-17 07:38:11.472 INFO  - OrientDB auto-config DISKCACHE=5,461MB (heap=5,461MB direct=5,461MB os=32,174MB), assuming maximum direct memory size equals to maximum JVM heap size
2017-01-17 07:38:11.472 ERROR - java.lang.NullPointerException
2017-01-17 07:38:11.472 ERROR - java.lang.NullPointerException
2017-01-17 07:38:11.473 ERROR -         at com.orientechnologies.orient.core.engine.local.OEngineLocalPaginated.changeCacheSize(OEngineLocalPaginated.java:80)
2017-01-17 07:38:11.473 ERROR -         at com.orientechnologies.orient.core.engine.local.OEngineLocalPaginated.changeCacheSize(OEngineLocalPaginated.java:80)
2017-01-17 07:38:11.473 ERROR -         at com.orientechnologies.orient.core.config.OGlobalConfiguration$1.change(OGlobalConfiguration.java:114)
2017-01-17 07:38:11.473 ERROR -         at com.orientechnologies.orient.core.config.OGlobalConfiguration$1.change(OGlobalConfiguration.java:114)
2017-01-17 07:38:11.473 ERROR -         at com.orientechnologies.orient.core.config.OGlobalConfiguration.setValue(OGlobalConfiguration.java:1056)
2017-01-17 07:38:11.473 ERROR -         at com.orientechnologies.orient.core.config.OGlobalConfiguration.setValue(OGlobalConfiguration.java:1056)
2017-01-17 07:38:11.473 ERROR -         at com.orientechnologies.orient.core.engine.OMemoryAndLocalPaginatedEnginesInitializer.configureDefaultDiskCacheSize(OMemoryAndLocalPaginatedEng
inesInitializer.java:89)
2017-01-17 07:38:11.473 ERROR -         at com.orientechnologies.orient.core.engine.OMemoryAndLocalPaginatedEnginesInitializer.configureDefaultDiskCacheSize(OMemoryAndLocalPaginatedEng
inesInitializer.java:89)
2017-01-17 07:38:11.473 ERROR -         at com.orientechnologies.orient.core.engine.OMemoryAndLocalPaginatedEnginesInitializer.configureDefaults(OMemoryAndLocalPaginatedEnginesInitiali
zer.java:63)
2017-01-17 07:38:11.473 ERROR -         at com.orientechnologies.orient.core.engine.OMemoryAndLocalPaginatedEnginesInitializer.configureDefaults(OMemoryAndLocalPaginatedEnginesInitiali
zer.java:63)
2017-01-17 07:38:11.473 ERROR -         at com.orientechnologies.orient.core.engine.OMemoryAndLocalPaginatedEnginesInitializer.initialize(OMemoryAndLocalPaginatedEnginesInitializer.jav
a:52)
2017-01-17 07:38:11.473 ERROR -         at com.orientechnologies.orient.core.engine.OMemoryAndLocalPaginatedEnginesInitializer.initialize(OMemoryAndLocalPaginatedEnginesInitializer.jav
a:52)
2017-01-17 07:38:11.473 ERROR -         at com.orientechnologies.orient.core.engine.local.OEngineLocalPaginated.startup(OEngineLocalPaginated.java:56)
2017-01-17 07:38:11.473 ERROR -         at com.orientechnologies.orient.core.engine.local.OEngineLocalPaginated.startup(OEngineLocalPaginated.java:56)
2017-01-17 07:38:11.473 ERROR -         at com.orientechnologies.orient.core.Orient.startEngine(Orient.java:858)
2017-01-17 07:38:11.473 ERROR -         at com.orientechnologies.orient.core.Orient.startEngine(Orient.java:858)
2017-01-17 07:38:11.473 ERROR -         at com.orientechnologies.orient.core.Orient.loadStorage(Orient.java:466)
2017-01-17 07:38:11.473 ERROR -         at com.orientechnologies.orient.core.Orient.loadStorage(Orient.java:466)
2017-01-17 07:38:11.473 ERROR -         at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.<init>(ODatabaseDocumentTx.java:174)
2017-01-17 07:38:11.473 ERROR -         at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.<init>(ODatabaseDocumentTx.java:174)
2017-01-17 07:38:11.473 ERROR -         at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.<init>(ODatabaseDocumentTx.java:155)
2017-01-17 07:38:11.473 ERROR -         at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.<init>(ODatabaseDocumentTx.java:155)
2017-01-17 07:38:11.473 ERROR -         at com.tinkerpop.blueprints.impls.orient.OrientBaseGraph.openOrCreate(OrientBaseGraph.java:1940)
2017-01-17 07:38:11.473 ERROR -         at com.tinkerpop.blueprints.impls.orient.OrientBaseGraph.openOrCreate(OrientBaseGraph.java:1940)
2017-01-17 07:38:11.473 ERROR -         at com.tinkerpop.blueprints.impls.orient.OrientBaseGraph.<init>(OrientBaseGraph.java:163)
2017-01-17 07:38:11.473 ERROR -         at com.tinkerpop.blueprints.impls.orient.OrientBaseGraph.<init>(OrientBaseGraph.java:163)
2017-01-17 07:38:11.473 ERROR -         at com.tinkerpop.blueprints.impls.orient.OrientTransactionalGraph.<init>(OrientTransactionalGraph.java:102)
2017-01-17 07:38:11.473 ERROR -         at com.tinkerpop.blueprints.impls.orient.OrientTransactionalGraph.<init>(OrientTransactionalGraph.java:102)
2017-01-17 07:38:11.473 ERROR -         at com.tinkerpop.blueprints.impls.orient.OrientTransactionalGraph.<init>(OrientTransactionalGraph.java:98)
2017-01-17 07:38:11.473 ERROR -         at com.tinkerpop.blueprints.impls.orient.OrientTransactionalGraph.<init>(OrientTransactionalGraph.java:98)
2017-01-17 07:38:11.473 ERROR -         at com.tinkerpop.blueprints.impls.orient.OrientGraph.<init>(OrientGraph.java:76)
2017-01-17 07:38:11.473 ERROR -         at com.tinkerpop.blueprints.impls.orient.OrientGraph.<init>(OrientGraph.java:76)
```

**Comment by laa** [comment]
Fixed
