### ISSUE TITLE
Error on creating ETL processor

### ISSUE THREAD

**Issue by ahr12** [orientechnologies/orientdb#7109]
Hi, I'm trying to upload graph from JSON with JSON ETL.
System parameters: OrientDB 2.2.14, ubuntu 14.04 64 bit, JAVA 1.8

I am gating the followings errors - 
Exception in thread "main" com.orientechnologies.orient.core.exception.OConfigurationException: Error on creating ETL processor
	DB name="plocal:/tmp/databases/testdb"
	at com.orientechnologies.orient.etl.OETLProcessor.parse(OETLProcessor.java:245)
	at com.orientechnologies.orient.etl.OETLProcessor.parse(OETLProcessor.java:186)
	at com.orientechnologies.orient.etl.OETLProcessor.parseConfigAndParameters(OETLProcessor.java:176)
	at com.orientechnologies.orient.etl.OETLProcessor.main(OETLProcessor.java:140)
Caused by: java.lang.NullPointerException
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.get(ODatabaseDocumentTx.java:1468)
	at com.tinkerpop.blueprints.impls.orient.OrientBaseGraph.readDatabaseConfiguration(OrientBaseGraph.java:1851)
	at com.tinkerpop.blueprints.impls.orient.OrientBaseGraph.<init>(OrientBaseGraph.java:146)
	at com.tinkerpop.blueprints.impls.orient.OrientGraphNoTx.<init>(OrientGraphNoTx.java:62)
	at com.tinkerpop.blueprints.impls.orient.OrientGraphFactory$2.getGraph(OrientGraphFactory.java:116)
	at com.tinkerpop.blueprints.impls.orient.OrientGraphFactory.getNoTx(OrientGraphFactory.java:240)
	at com.orientechnologies.orient.etl.loader.OOrientDBLoader.configureGraphDB(OOrientDBLoader.java:407)
	at com.orientechnologies.orient.etl.loader.OOrientDBLoader.configure(OOrientDBLoader.java:345)
	at com.orientechnologies.orient.etl.OETLProcessor.configureComponent(OETLProcessor.java:484)
	at com.orientechnologies.orient.etl.OETLProcessor.configureLoader(OETLProcessor.java:297)
	at com.orientechnologies.orient.etl.OETLProcessor.parse(OETLProcessor.java:229)
	... 3 more

**Comment by robfrank** [comment]
Could you provide the configuration Json and some sample data?

**Comment by ahr12** [comment]
configuration JSON file

{
  "config": {
    "log": "debug"
  },
  "source" : {
    "file": { "path": "/tmp/test.json" }
  },
  "extractor" : {
    "json": {}
  },
  "transformers" : [
    { "merge": { "joinFieldName": "id", "lookup": "Account.id" } },
    { "vertex": { "class": "Account"} },
    { "edge": {
      "class": "Friend",
      "joinFieldName": "friends",
      "lookup": "Account.id",
      "unresolvedLinkAction": "CREATE"
    } },
    { "edge": {
      "class": "Enemy",
      "joinFieldName": "enemies",
      "lookup": "Account.id",
      "unresolvedLinkAction": "CREATE"
    } }
  ],
  "loader" : {
    "orientdb": {
      "dbURL": "plocal:/tmp/databases/testdb",
      "dbUser": "admin",
      "dbPassword": "admin",
      "dbAutoDropIfExists": true,
      "dbAutoCreate": true,
      "standardElementConstraints": false,
      "tx": false,
      "wal": false,
      "batchCommit": 1000,
      "dbType": "graph",
      "classes": [{"name": "Account", "extends":"V"}, {"name": "Friend", "extends":"E"}, {"name": 'Enemy', "extends":"E"}],
      "indexes": [{"class":"Account", "fields":["id:integer"], "type":"UNIQUE_HASH_INDEX" }]
    }
  }
}


Sample data - test.json

[
 {
  "name": "Joe",
  "id": 1,
  "friends": [2,4,5],
  "enemies": [6]
 },
 {
  "name": "Suzie",
  "id": 2,
  "friends": [1,4,6],
  "enemies": [5,2]
 }
]

**Comment by saeedtabrizi** [comment]
Hi @robfrank , i have same problem in odb 2.2.15 

osm data can take from [OpenStreetMap](https://www.openstreetmap.org/export#map=17/35.76241/51.37396)  as test.osm

configuration : 
  `{
    "config": {
        "log": "debug"
    },
    "begin": [
        {
            "let": {
                "name": "$filePath",
                "value": "6565"
            }
        },
        {
            "let": {
                "name": "$className",
                "value": "hello"
            }
        }
    ],
    "source": {
        "file": {
            "path": "/mnt/hdd2/test.osm"
        }
    },
    "extractor": {
        "xml": {
            "rootNode": "osm.node"
        }
    },
    "transformers": [
        {
            "vertex": {
                "class": "Osm_Node"
            }
        }
    ],
    "loader": {
        "output": {}
    }
}`

my output log :
`OrientDB etl v.2.2.15 (build 2.2.x@rebf7b80c08613e871633edeb39c5c985e26b176c; 2017-01-19
07:39:00+0000) www.orientdb.com
BEGIN ETL PROCESSOR
[file] INFO Reading from file /mnt/hdd2/test.osm with encoding UTF-8
Started execution with 1 worker threads
ETL process has problem: java.lang.NullPointerException
END ETL PROCESSOR
+ extracted 0 entries (0 entries/sec) - 0 entries -> loaded 0 bytes (0 bytes/sec) Total t
ime: 77ms [0 warnings, 0 errors]`

what can i do ?

**Comment by lvca** [comment]
@saeedtabrizi can you see where the NPE originated from?

**Comment by saeedtabrizi** [comment]
Hi @lvca as i explained in https://github.com/orientechnologies/orientdb/issues/7107#issuecomment-275579245 , after some tries and spending some hours , now i can to transfer my data from .osm xml files to orientdb but i realized the documentaion of ETL is not suitable and true . 
I recommend review the documentation of ETL again . 

Thanks 
Saeed

**Comment by robfrank** [comment]
Hi, I replicated the problem. The workaround is to avoid `"dbAutoDropIfExists": true,`

I tested with previous versions and the same problem is there since a long time. I'll fix it for next release.

**Comment by robfrank** [comment]
Just pushed the fix, you can download the etl module 2.2.16-SNAPSHOT and drop it inside the lib folder. Delete the 2.2.15 jar before!

https://oss.sonatype.org/content/repositories/snapshots/com/orientechnologies/orientdb-etl/2.2.16-SNAPSHOT/


Please close the issue if the fix solves your problem

**Comment by saeedtabrizi** [comment]
Many Thanks @robfrank . i will check it .
