### ISSUE TITLE
Changing schema from double to decimal doesnt seem to work (v2.1.x)

### ISSUE THREAD

**Issue by andreyvk** [orientechnologies/orientdb#7121]
## OrientDB Version, operating system, or hardware.
- v2.1.25

## Operating System
Linux

Hi,

I was changing schema from some of the classes' attributes from `double` to `decimal` using an sql script through console (there are a bunch of attributes that needed conversion). 

At my first attempt to run the script database got corrupted throwing some error regarding `BigDecimal`.  I've rearranged the commands in the SQL script a little bit and seem to be able to run it through. However, on my first attempt to update a record I've got an exception (see below). And as a result of the records of that class cannot be updated now.

**Question**: is that something known in Orient 2.1.x or might this be a bug? If initial schema is needed, I can send it by email only. Company policy, of course :)

I'm still trying out different ways to make it work. If I find more info, I'll send it

```
com.orientechnologies.orient.core.exception.ODatabaseException: Error on saving record #125:0
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.executeSaveRecord(ODatabaseDocumentTx.java:2048)
        at com.orientechnologies.orient.core.tx.OTransactionNoTx.saveRecord(OTransactionNoTx.java:160)
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.save(ODatabaseDocumentTx.java:2526)
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.save(ODatabaseDocumentTx.java:122)
        at com.orientechnologies.orient.core.record.impl.ODocument.save(ODocument.java:1759)
        at com.orientechnologies.orient.core.record.impl.ODocument.save(ODocument.java:1750)
        at com.orientechnologies.orient.core.sql.OCommandExecutorSQLUpdate.result(OCommandExecutorSQLUpdate.java:342)
        at com.orientechnologies.orient.core.sql.OCommandExecutorSQLResultsetAbstract.pushResult(OCommandExecutorSQLResultsetAbstract.java:267)
        at com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.addResult(OCommandExecutorSQLSelect.java:703)
        at com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.handleResult(OCommandExecutorSQLSelect.java:610)
        at com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.executeSearchRecord(OCommandExecutorSQLSelect.java:559)
        at com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.fetchFromTarget(OCommandExecutorSQLSelect.java:1480)
        at com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.executeSearch(OCommandExecutorSQLSelect.java:488)
        at com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.execute(OCommandExecutorSQLSelect.java:446)
        at com.orientechnologies.orient.core.sql.OCommandExecutorSQLDelegate.execute(OCommandExecutorSQLDelegate.java:90)
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.executeCommand(OAbstractPaginatedStorage.java:1433)
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.command(OAbstractPaginatedStorage.java:1406)
        at com.orientechnologies.orient.core.sql.query.OSQLQuery.run(OSQLQuery.java:72)
        at com.orientechnologies.orient.core.query.OQueryAbstract.execute(OQueryAbstract.java:33)
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.query(ODatabaseDocumentTx.java:743)
        at com.orientechnologies.orient.core.sql.OCommandExecutorSQLUpdate.execute(OCommandExecutorSQLUpdate.java:264)
        at com.orientechnologies.orient.core.sql.OCommandExecutorSQLDelegate.execute(OCommandExecutorSQLDelegate.java:90)
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.executeCommand(OAbstractPaginatedStorage.java:1433)
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.command(OAbstractPaginatedStorage.java:1406)
        at com.orientechnologies.orient.core.command.OCommandRequestTextAbstract.execute(OCommandRequestTextAbstract.java:67)
        at com.orientechnologies.orient.server.network.protocol.http.command.post.OServerCommandPostCommand.execute(OServerCommandPostCommand.java:81)
        at com.orientechnologies.orient.server.network.protocol.http.ONetworkProtocolHttpAbstract.service(ONetworkProtocolHttpAbstract.java:180)
        at com.orientechnologies.orient.server.network.protocol.http.ONetworkProtocolHttpAbstract.execute(ONetworkProtocolHttpAbstract.java:627)
        at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:77)
Caused by: java.lang.ClassCastException: java.lang.Float cannot be cast to java.math.BigDecimal
        at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinaryV0.writeSingleValue(ORecordSerializerBinaryV0.java:576)
        at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinaryV0.serialize(ORecordSerializerBinaryV0.java:258)
        at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinaryV0.writeSingleValue(ORecordSerializerBinaryV0.java:565)
        at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinaryV0.writeEmbeddedCollection(ORecordSerializerBinaryV0.java:761)
        at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinaryV0.writeSingleValue(ORecordSerializerBinaryV0.java:573)
        at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinaryV0.serialize(ORecordSerializerBinaryV0.java:258)
        at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinary.toStream(ORecordSerializerBinary.java:105)
        at com.orientechnologies.orient.core.record.impl.ODocument.toStream(ODocument.java:2287)
        at com.orientechnologies.orient.core.record.impl.ODocument.toStream(ODocument.java:662)
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.executeSaveRecord(ODatabaseDocumentTx.java:1938)
        ... 28 more
```

**Comment by andreyvk** [comment]
Seems like the problem happens when embedded attributes' schema is changed from `double` to `decimal`. Basically, our class has an `embeddedlist` or a class that contained a few `double` attributes. Also the main class had `double` attributes.

I ran SQL script separately first for the main class. There was no problem. But then I ran a second portion of script changing schema for embedded class. After that the problem came back.

**Comment by andreyvk** [comment]
**UPDATE 2**: I've tried a higher version of Orient. This error **does not** happen on 2.2.15.

However, we cannot move our DB to 2.2 yet, as I found that some indices are not updated properly. If I will be able to identify how index gets corrupted, I'll make another issue.

**Comment by tglman** [comment]
hi @andreyvk,

The 2.1 is out of support, do you have any chance to update to 2.2.x ?

Regards

**Comment by andreyvk** [comment]
@tglman hi,

I've tried to migrate to 2.2, but like i mentioned above we have some problem with indexing. So far it doesnt look like there's a problem with Orient but rather a problem with the PHP driver or the database file itself. Im still debugging. Gonna close this issue meanwhile. If I find something I'll let you guys know.
