### ISSUE TITLE
SQL parser fails on expression with brackets before expression with NOT IN condition

### ISSUE THREAD

**Issue by andreyvk** [orientechnologies/orientdb#7122]
## OrientDB Version, operating system, or hardware.
v2.2.15

## Operating System
Linux

Hi,

I think I found an issue with SQL parser which is specific to using brackets before an expression, which contains `not in` condition.

Steps to reproduce:

**Schema**
```
create class Test extends V
create property Test.val1 integer
create property Test.val2 string

insert into Test content {"val1": 10, "val2": "foo" }
insert into Test content {"val1": 20, "val2": "bar" }
```

**FAILED**
```
select from Test 
where (val1 < 100)
and val2 not in ['bar']
```

**SUCCEEDED**
```
select from Test 
where val1 < 100
and val2 not in ['bar']

select from Test 
where  val2 not in ['bar'] 
and (val1 < 100)
```

The **FAILED** SQL above will throw at least one exception in the log (i think as many record it matches, as many errors it throws). Exception is as follows:

```
2017-01-25 12:58:58:286 FINE  {db=test} Read record #102:1 v.1 size=24 bytes [OLocalPaginatedStorage]$ANSI{green {db=test}} Error on evaluating expression ((val2 NOT IN))
java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Boolean
        at com.orientechnologies.orient.core.sql.operator.OQueryOperatorNot.evaluateRecord(OQueryOperatorNot.java:55)
        at com.orientechnologies.orient.core.sql.filter.OSQLFilterCondition.evaluate(OSQLFilterCondition.java:149)
        at com.orientechnologies.orient.core.sql.filter.OSQLFilterCondition.evaluate(OSQLFilterCondition.java:380)
        at com.orientechnologies.orient.core.sql.filter.OSQLFilterCondition.evaluate(OSQLFilterCondition.java:94)
        at com.orientechnologies.orient.core.sql.filter.OSQLFilter.evaluate(OSQLFilter.java:103)
        at com.orientechnologies.orient.core.sql.OCommandExecutorSQLResultsetAbstract.evaluateRecord(OCommandExecutorSQLResultsetAbstract.java:419)
        at com.orientechnologies.orient.core.sql.OCommandExecutorSQLResultsetAbstract.filter(OCommandExecutorSQLResultsetAbstract.java:409)
        at com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.executeSearchRecord(OCommandExecutorSQLSelect.java:612)
        at com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.serialIterator(OCommandExecutorSQLSelect.java:1619)
        at com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.fetchFromTarget(OCommandExecutorSQLSelect.java:1566)
        at com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.executeSearch(OCommandExecutorSQLSelect.java:525)
        at com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.execute(OCommandExecutorSQLSelect.java:488)
        at com.orientechnologies.orient.core.sql.OCommandExecutorSQLDelegate.execute(OCommandExecutorSQLDelegate.java:74)
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.executeCommand(OAbstractPaginatedStorage.java:2592)
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.command(OAbstractPaginatedStorage.java:2538)
        at com.orientechnologies.orient.core.command.OCommandRequestTextAbstract.execute(OCommandRequestTextAbstract.java:69)
        at com.orientechnologies.orient.server.network.protocol.http.command.post.OServerCommandPostCommand.execute(OServerCommandPostCommand.java:106)
        at com.orientechnologies.orient.graph.server.command.OServerCommandPostCommandGraph.execute(OServerCommandPostCommandGraph.java:37)
        at com.orientechnologies.orient.server.network.protocol.http.ONetworkProtocolHttpAbstract.service(ONetworkProtocolHttpAbstract.java:169)
        at com.orientechnologies.orient.server.network.protocol.http.ONetworkProtocolHttpAbstract.execute(ONetworkProtocolHttpAbstract.java:622)
        at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:77)
```

**Comment by luigidellaquila** [comment]
Hi @andreyvk 

Thank you for reporting, it seems to be a problem in the query parsing, I'll check it asap

Thanks

Luigi

**Comment by luigidellaquila** [comment]
Hi @andreyvk 

I just checked this issue and it works fine in v 2.2.28, so I'd say it's already fixed long time ago.
I'm closing this ticket, please feel free to reopen if you need further help (and sorry for the long silence)

Thanks

Luigi
