### ISSUE TITLE
ConcurrentModification exception when saving from Studio

### ISSUE THREAD

**Issue by andreyvk** [orientechnologies/orientdb#7134]
## OrientDB Version, operating system, or hardware.
v2.2.15

## Operating System
Linux

Hi,

A simple save from the studio (just open any record and hit 'Save' button) always throws a `ConcurrentModificationException`. Here's the log

```
2017-01-30 18:16:44:402 FINE  {db=nsdev} onOpen [OLuceneIndexFactory]
2017-01-30 18:16:44:407 FINE  {db=nsdev} Read record #107:15305 v.21 size=5867 bytes [OLocalPaginatedStorage]
2017-01-30 18:16:44:410 FINE  {db=nsdev} Updated record #107:15305 v.22 size=5886 [OLocalPaginatedStorage]
2017-01-30 18:16:44:414 FINE  {db=nsdev} onClose [OLuceneIndexFactory]Caught exception
com.orientechnologies.orient.core.exception.OConcurrentModificationException: Cannot UPDATE the record #107:15305 because the version is not the latest. Probably you are updating an old record or it has been modified by another user (db=v22 your=v21)
        DB name="nsdev"
        at com.orientechnologies.orient.core.conflict.OVersionRecordConflictStrategy.checkVersions(OVersionRecordConflictStrategy.java:56)
        at com.orientechnologies.orient.core.conflict.OVersionRecordConflictStrategy.onUpdate(OVersionRecordConflictStrategy.java:43)
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.checkAndIncrementVersion(OAbstractPaginatedStorage.java:3568)
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.doUpdateRecord(OAbstractPaginatedStorage.java:3065)
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.updateRecord(OAbstractPaginatedStorage.java:1121)
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.executeSaveRecord(ODatabaseDocumentTx.java:2190)
        at com.orientechnologies.orient.core.tx.OTransactionNoTx.saveRecord(OTransactionNoTx.java:181)
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.save(ODatabaseDocumentTx.java:2716)
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.save(ODatabaseDocumentTx.java:103)
        at com.orientechnologies.orient.core.record.impl.ODocument.save(ODocument.java:1802)
        at com.orientechnologies.orient.core.record.impl.ODocument.save(ODocument.java:1793)
        at com.orientechnologies.orient.server.network.protocol.http.command.put.OServerCommandPutDocument.execute(OServerCommandPutDocument.java:96)
        at com.orientechnologies.orient.server.network.protocol.http.ONetworkProtocolHttpAbstract.service(ONetworkProtocolHttpAbstract.java:169)
        at com.orientechnologies.orient.server.network.protocol.http.ONetworkProtocolHttpAbstract.execute(ONetworkProtocolHttpAbstract.java:622)
        at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:77)
```

**Comment by maggiolo00** [comment]
@andreyvk 

i was not able to reproduce it with the bundled db GratefulDeadConcerts

How can i replicate it?

**Comment by andreyvk** [comment]
@maggiolo00 strange... 

I've actually tried more records and some save fine and some throw this exception. I've already set log level to the FINEST. There's no more log that i can gather for you. Is it possible to debug this some other way?

**Comment by maggiolo00** [comment]
@andreyvk 

If you can create a dataset with some records that fail would be awesome.
I should debug and see the internal state of the record

Could be some field type that makes the difference

**Comment by andreyvk** [comment]
@maggiolo00 I'll see what I can do. This is a production db. It's very large and I cant disclose it. However, plz keep this issue open. I'll come back to it.

**Comment by lvca** [comment]
@andreyvk is the very same record updated in background by the application or any other process?

**Comment by andreyvk** [comment]
@lvca no, there's no process on the background. 

The database that we have was moved over from 2.1.19.  And previously from earlier versions of Orient.  The whole class of records - one that causes concurrency exception now - seems to have a problem. On top of this issue we are having another one: some indexes are not updated, when we create a new record from our software (basically we cant search properly after that). However, when I store a record from a script (using the same library as is used in our software) or directly from the studio - no problem. 

So, it's a mess, basically. When I have something concrete I can send you guys, I'll knock. Meanwhile i'll close this issue.
