### ISSUE TITLE
Database open issue

### ISSUE THREAD

**Issue by smallik** [orientechnologies/orientdb#7183]
## Expected behavior  

new instance of ODatabaseDocumentTx

I am trying to get an instance of the database. I get  security exception.
After starting tomcat and manually login to the database using the studio then the exception is not happening. 
clearly there is an issue here as the behavior is modified based on if I manually logged in to the studio or not. 

## Actual behavior  

com.orientechnologies.orient.core.exception.OSecurityAccessException: User or password not valid for database:

## Steps to reproduce  

	public static void test3()
	{
		OrientGraphFactory factory=new OrientGraphFactory("plocal:C:/GO/ArtiE/server/artielabs","artie","artie").setupPool(2, 2000);
		ODatabaseDocumentTx doctx = factory.getDatabase(false, true);
		doctx.begin();
		
		String query="select * from my_test_table where scope = 'domain'";
	    OSQLSynchQuery<OIdentifiable> oquery = new OSQLSynchQuery<OIdentifiable>(query);
		List<ODocument> list=doctx.query(oquery);
		System.out.println("******total records in my_test_table*****:"+list.size());

		doctx.rollback();
		doctx.close();
		factory.close();
}

below is the full stack trace.

com.orientechnologies.orient.core.exception.OSecurityAccessException: User or password not valid for database: 'artielabs'
        DB name="artielabs"
        at com.orientechnologies.orient.core.metadata.security.OSecurityShared.authenticate(OSecurityShared.java:237)
        at com.orientechnologies.orient.core.metadata.security.OSecurityExternal.authenticate(OSecurityExternal.java:62)
        at com.orientechnologies.orient.core.metadata.security.OSecurityProxy.authenticate(OSecurityProxy.java:107)
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.open(ODatabaseDocumentTx.java:280)
        at com.orientechnologies.orient.core.db.OPartitionedDatabasePool$DatabaseDocumentTxPooled.internalOpen(OPartitionedDatabasePool.java:447)
        at com.orientechnologies.orient.core.db.OPartitionedDatabasePool.openDatabase(OPartitionedDatabasePool.java:310)
        at com.orientechnologies.orient.core.db.OPartitionedDatabasePool.acquire(OPartitionedDatabasePool.java:268)
        at com.tinkerpop.blueprints.impls.orient.OrientGraphFactory.getDatabase(OrientGraphFactory.java:287)
        at com.artie.server.test.test3(test.java:26)
        at com.artie.server.ArtieServer.onMessage(ArtieServer.java:97)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.tomcat.websocket.pojo.PojoMessageHandlerWholeBase.onMessage(PojoMessageHandlerWholeBase.java:80)
        at org.apache.tomcat.websocket.WsFrameBase.sendMessageText(WsFrameBase.java:399)
        at org.apache.tomcat.websocket.server.WsFrameServer.sendMessageText(WsFrameServer.java:107)
        at org.apache.tomcat.websocket.WsFrameBase.processDataText(WsFrameBase.java:500)
        at org.apache.tomcat.websocket.WsFrameBase.processData(WsFrameBase.java:295)
        at org.apache.tomcat.websocket.WsFrameBase.processInputBuffer(WsFrameBase.java:130)
        at org.apache.tomcat.websocket.server.WsFrameServer.onDataAvailable(WsFrameServer.java:70)
        at org.apache.tomcat.websocket.server.WsHttpUpgradeHandler.upgradeDispatch(WsHttpUpgradeHandler.java:148)
        at org.apache.coyote.http11.upgrade.UpgradeProcessorInternal.dispatch(UpgradeProcessorInternal.java:54)
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:53)
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:745)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1455)
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.lang.Thread.run(Thread.java:745)

**Comment by smallik** [comment]
I tried to create the embedded database and run the test in one call to make things single. below is the code and  console output.

	public static void main(String[] args)
	{
		OServer server=null;
		try {
			server = OServerMain.create();
			server.startup(new File("C:/GO/ArtiE/server/config/orientdb-server-config.xml"));
			server.activate();
			test3();
			server.shutdown();
			Orient.instance().shutdown();
		} catch (Exception e) {
			e.printStackTrace();
			server.shutdown();
			Orient.instance().shutdown();
		}
	}

Console output is below:

2017-02-20 14:05:50:545 INFO  Loading configuration from: C:/GO/ArtiE/server/config/orientdb-server-config.xml... [OServerConfigurationLoaderXml]
2017-02-20 14:05:50:736 INFO  OrientDB Server v2.2.7 is starting up... [OServer]
2017-02-20 14:05:50:747 INFO  Databases directory: C:\GO\ArtiE\server\domains [OServer]
2017-02-20 14:05:50:863 INFO  OrientDB auto-config DISKCACHE=3,609MB (heap=3,609MB direct=3,609MB os=16,235MB), assuming maximum direct memory size equals to maximum JVM heap size [orientechnologies]
2017-02-20 14:05:50:864 WARNI MaxDirectMemorySize JVM option is not set or has invalid value, that may cause out of memory errors. Please set the -XX:MaxDirectMemorySize=16235m option when you start the JVM. [Class]
2017-02-20 14:05:51:301 WARNI Port 0.0.0.0:2424 busy, trying the next available... [OServerNetworkListener]
2017-02-20 14:05:51:302 INFO  Listening binary connections on 0.0.0.0:2425 (protocol v.36, socket=default) [OServerNetworkListener]
2017-02-20 14:05:51:305 WARNI Port 0.0.0.0:2480 busy, trying the next available... [OServerNetworkListener]
2017-02-20 14:05:51:306 INFO  Listening http connections on 0.0.0.0:2481 (protocol v.10, socket=default) [OServerNetworkListener]
2017-02-20 14:05:51:315 INFO  ODefaultPasswordAuthenticator is active [ODefaultPasswordAuthenticator]
2017-02-20 14:05:51:316 INFO  OServerConfigAuthenticator is active [OServerConfigAuthenticator]
2017-02-20 14:05:51:316 INFO  OSystemUserAuthenticator is active [OSystemUserAuthenticator]
2017-02-20 14:05:51:324 WARNI GREMLIN language not available (not in classpath) [OGremlinHelper]
2017-02-20 14:05:51:335 INFO  [OVariableParser.resolveVariables] Error on resolving property: distributed [orientechnologies]
2017-02-20 14:05:51:338 WARNI Authenticated clients can execute any kind of code into the server by using the following allowed languages: [sql] [OServerSideScriptInterpreter]
2017-02-20 14:05:51:408 INFO  OrientDB Studio available at http://10.0.0.129:2481/studio/index.html [OServer]
2017-02-20 14:05:51:409 INFO  OrientDB Server is active v2.2.7. [OServer]com.orientechnologies.orient.core.exception.OStorageException: Cannot open local storage 'C:/GO/ArtiE/server/artielabs' with mode=rw
	DB name="artielabs"
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.open(OAbstractPaginatedStorage.java:259)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.open(ODatabaseDocumentTx.java:257)
	at com.orientechnologies.orient.core.db.OPartitionedDatabasePool$DatabaseDocumentTxPooled.internalOpen(OPartitionedDatabasePool.java:443)
	at com.orientechnologies.orient.core.db.OPartitionedDatabasePool.openDatabase(OPartitionedDatabasePool.java:306)
	at com.orientechnologies.orient.core.db.OPartitionedDatabasePool.acquire(OPartitionedDatabasePool.java:261)
	at com.tinkerpop.blueprints.impls.orient.OrientGraphFactory.getDatabase(OrientGraphFactory.java:169)
	at com.artie.server.test.test3(test.java:42)
	at com.artie.server.test.main(test.java:28)
Caused by: com.orientechnologies.orient.core.exception.OStorageException: Can not open storage it is acquired by other process
	DB name="artielabs"
	at com.orientechnologies.orient.core.storage.impl.local.paginated.OPaginatedStorageDirtyFlag.lockFile(OPaginatedStorageDirtyFlag.java:103)
	at com.orientechnologies.orient.core.storage.impl.local.paginated.OPaginatedStorageDirtyFlag.open(OPaginatedStorageDirtyFlag.java:138)
	at com.orientechnologies.orient.core.storage.impl.local.paginated.OLocalPaginatedStorage.preOpenSteps(OLocalPaginatedStorage.java:330)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.open(OAbstractPaginatedStorage.java:211)
	... 7 more

2017-02-20 14:05:51:441 INFO  {db=artielabs} OrientDB Server is shutting down... [OServer]
2017-02-20 14:05:51:444 INFO  {db=artielabs} Shutting down listeners: [OServer]
2017-02-20 14:05:51:446 INFO  {db=artielabs} - ONetworkProtocolBinary /0.0.0.0:2425: [OServer]
2017-02-20 14:05:51:446 INFO  {db=artielabs} - ONetworkProtocolHttpDb /0.0.0.0:2481: [OServer]
2017-02-20 14:05:51:447 INFO  {db=artielabs} Shutting down protocols [OServer]
2017-02-20 14:05:51:447 INFO  {db=artielabs} Shutting down plugins: [OServerPluginManager]
2017-02-20 14:05:51:447 INFO  {db=artielabs} - script-interpreter [OServerPluginManager]
2017-02-20 14:05:51:447 INFO  {db=artielabs} - graph [OServerPluginManager]
2017-02-20 14:05:51:448 INFO  {db=artielabs} Shutting down databases: [OServer]
2017-02-20 14:05:51:449 INFO  {db=artielabs} Orient Engine is shutting down... [Orient]
2017-02-20 14:05:51:475 INFO  {db=artielabs} - shutdown storage: artielabs... [Orient]
2017-02-20 14:05:51:475 INFO  {db=artielabs} - shutdown storage: OSystem... [Orient]
2017-02-20 14:05:51:532 INFO  OrientDB Engine shutdown complete [Orient]
2017-02-20 14:05:51:535 INFO  OrientDB Server shutdown complete
 [OServer]

**Comment by smallik** [comment]
I am attaching the config file used in this test

[orientdb-server-config.txt](https://github.com/orientechnologies/orientdb/files/788338/orientdb-server-config.txt)

**Comment by smallik** [comment]
https://github.com/orientechnologies/orientdb/issues/7184

This was happening because of the above issue. the database location was wrong and because of the above issue its creating the database in the wrong location instead of reporting that the database was not found.
