### ISSUE TITLE
NullPointerException on storage.useWAL is false

### ISSUE THREAD

**Issue by wellpeng** [orientechnologies/orientdb#7243]
## Expected behavior  
<add here>  

## Actual behavior  
 [OHazelcastPlugin]Cannot route create record operation for #69:0 to the distributed node
java.lang.NullPointerException
	at com.orientechnologies.orient.server.distributed.impl.ODistributedStorage.executeRecordOperationInLock(ODistributedStorage.java:1205)
	at com.orientechnologies.orient.server.distributed.impl.ODistributedStorage.createRecord(ODistributedStorage.java:635)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.executeSaveRecord(ODatabaseDocumentTx.java:2179)
	at com.orientechnologies.orient.core.tx.OTransactionNoTx.saveNew(OTransactionNoTx.java:235)
	at com.orientechnologies.orient.core.tx.OTransactionNoTx.saveRecord(OTransactionNoTx.java:168)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.save(ODatabaseDocumentTx.java:2696)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.save(ODatabaseDocumentTx.java:103)
	at com.orientechnologies.orient.core.record.impl.ODocument.save(ODocument.java:1802)
	at com.orientechnologies.orient.core.record.impl.ODocument.save(ODocument.java:1793)
	at com.orientechnologies.orient.server.network.protocol.http.command.post.OServerCommandPostDocument.execute(OServerCommandPostDocument.java:54)
	at com.orientechnologies.orient.server.network.protocol.http.ONetworkProtocolHttpAbstract.service(ONetworkProtocolHttpAbstract.java:169)
	at com.orientechnologies.orient.server.network.protocol.http.ONetworkProtocolHttpAbstract.execute(ONetworkProtocolHttpAbstract.java:622)
	at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:77)

## Steps to reproduce  
1. orientdb-server-config.xml properties add:
\<entry name="storage.useWAL" value="false"/\>

2. exec dserver.sh on node1
3. exec dserver.sh on node2
4. create graphdb on studio ui

**Comment by laa** [comment]
@wellpeng we will fix this issue. But if you do not use WAL you can not restore data in your server after crash. It will be a complete mess for you. Is it OK ?

**Comment by wellpeng** [comment]
Thanks laa.
I can't disable WAL in the distributed?

**Comment by laa** [comment]
I suppose you can not because it may prevent incremental replication. But this setting in general is not recommended because you will risk to lose all your data.
