### ISSUE TITLE
OSecurityException trying to change admin username

### ISSUE THREAD

**Issue by lucafrosini** [orientechnologies/orientdb#7245]
### OS: Ubuntu 16.10

I connect as **admin** to db and then I try to change admin username on save I get the following exception.

Please also note that the logging is also writing the metadata to have a colourized output on console $ANSI{green {db=gcube}} 

```
$ANSI{green {db=gcube}} securityRecordChange() Exception: 
com.orientechnologies.orient.core.exception.OSecurityException: User 'gcube' has no status
	DB name="gcube"
	at com.orientechnologies.orient.core.metadata.security.OUser.getAccountStatus(OUser.java:239)
	at com.orientechnologies.orient.core.metadata.security.OImmutableUser.<init>(OImmutableUser.java:36)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.reloadUser(ODatabaseDocumentTx.java:1011)
	at com.orientechnologies.orient.server.security.ODefaultServerSecurity$2.run(ODefaultServerSecurity.java:558)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

```

## Steps to reproduce  

```
OrientGraphFactory factory = new OrientGraphFactory("dburl", "admin", "admin").setupPool(1, 10);
OrientGraphNoTx orientGraphNoTx = factory.getNoTx();

OMetadata oMetadata = orientGraphNoTx.getRawGraph().getMetadata();
OSecurity oSecurity = oMetadata.getSecurity();
			
OUser admin = oSecurity.getUser("admin");
admin.setName("MyNewAdminName");
admin.save();
```

and even if  I do (maintaining the original connection)

```
OUser reader = oSecurity.getUser("reader");
reader.setPassword("mySecurePassword");
reader.save();

```

**Comment by maggiolo00** [comment]
hi @lucafrosini 

is the `url` remote or plocal ?

**Comment by lucafrosini** [comment]
remote

**Comment by lucafrosini** [comment]
Just to be sure.
the url is in the form remote:
The storage mode is plocal.

**Comment by luigidellaquila** [comment]
Great, closing then

Thanks!

Luigi
