### ISSUE TITLE
oetls.sh dbAutoDropIfExists does not work

### ISSUE THREAD

**Issue by danciui** [orientechnologies/orientdb#7251]
###OrientDB Version: orientdb-community-2.2.16
###Java Version: Java 8 Update 91
###OS: Mac Os Sierra 10.12.3

###Expected behavior
db gets dropped and recreated 
 
###Actual behavior
Exception in thread "main" com.orientechnologies.orient.core.exception.OConfigurationException: Error on creating ETL processor
	at com.orientechnologies.orient.etl.OETLProcessor.parse(OETLProcessor.java:237)
	at com.orientechnologies.orient.etl.OETLProcessor.parse(OETLProcessor.java:177)
	at com.orientechnologies.orient.etl.OETLProcessor.parseConfigAndParameters(OETLProcessor.java:145)
	at com.orientechnologies.orient.etl.OETLProcessor.main(OETLProcessor.java:109)
Caused by: java.lang.IllegalStateException: The current database instance (com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx@7334aada) is not active on the current thread (Thread[main,5,main]). Current active database is: null
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.checkIfActive(ODatabaseDocumentTx.java:3344)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.close(ODatabaseDocumentTx.java:1241)
	at com.orientechnologies.orient.etl.loader.OOrientDBLoader.manageRemoteDatabase(OOrientDBLoader.java:367)
	at com.orientechnologies.orient.etl.loader.OOrientDBLoader.configure(OOrientDBLoader.java:326)
	at com.orientechnologies.orient.etl.OETLProcessor.configureComponent(OETLProcessor.java:476)
	at com.orientechnologies.orient.etl.OETLProcessor.configureLoader(OETLProcessor.java:289)
	at com.orientechnologies.orient.etl.OETLProcessor.parse(OETLProcessor.java:221)
	... 3 more

###Steps to reproduce
[Archive.zip](https://github.com/orientechnologies/orientdb/files/853879/Archive.zip)

**Comment by robfrank** [comment]
Thank you very much for your report, just a couple of lines wrong.
The fix will be included in 2.2.18
