### ISSUE TITLE
ALTER DATABASE TIMEZONE GMT

### ISSUE THREAD

**Issue by schernolyas** [orientechnologies/orientdb#7279]
## Expected behavior  
The query must   change timezone of database

## Actual behavior  
Get exception.
java.lang.IllegalArgumentException: Timezone can't be null
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentAbstract.set(ODatabaseDocumentAbstract.java:1119)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentAbstract.setInternal(ODatabaseDocumentAbstract.java:560)
	at com.orientechnologies.orient.core.sql.parser.OAlterDatabaseStatement.executeSimpleAlter(OAlterDatabaseStatement.java:77)
	at com.orientechnologies.orient.core.sql.parser.OAlterDatabaseStatement.executeDDL(OAlterDatabaseStatement.java:40)
	at com.orientechnologies.orient.core.sql.executor.ODDLExecutionPlan.executeInternal(ODDLExecutionPlan.java:47)
	at com.orientechnologies.orient.core.sql.parser.ODDLStatement.execute(ODDLStatement.java:42)
	at com.orientechnologies.orient.core.sql.parser.OStatement.execute(OStatement.java:54)

## Steps to reproduce  
<add here>

**Comment by luigidellaquila** [comment]
Hi @schernolyas 

could you please try quoting the timezone:

```
ALTER DATABASE TIMEZONE "GMT"
```

This should work fine

Thanks

Luigi

**Comment by schernolyas** [comment]
Hi @luigidellaquila !
Fixed! Thanks!

But ... Why did You change it? It works for 2.2.*

**Comment by luigidellaquila** [comment]
Hi @schernolyas 

In v 3.0 we are still doing some changes, probably the GA will support both syntaxes

Thanks

Luigi

**Comment by schernolyas** [comment]
fixed.
