### ISSUE TITLE
Latest OrientDB 2.2.x snapshot can't open graph created with 2.2.17

### ISSUE THREAD

**Issue by peturrun** [orientechnologies/orientdb#7290]
## Expected behavior  
Graph should be opened

## Actual behavior  
Opening fails:

<pre>
Exception in thread "main" com.orientechnologies.orient.core.exception.OStorageException: Cannot open local storage '/tmp/graph' with mode=rw
	DB name="graph"
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.open(OAbstractPaginatedStorage.java:344)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.open(ODatabaseDocumentTx.java:258)
	at com.orientechnologies.orient.core.db.OPartitionedDatabasePool$DatabaseDocumentTxPooled.internalOpen(OPartitionedDatabasePool.java:447)
	at com.orientechnologies.orient.core.db.OPartitionedDatabasePool.openDatabase(OPartitionedDatabasePool.java:310)
	at com.orientechnologies.orient.core.db.OPartitionedDatabasePool.acquire(OPartitionedDatabasePool.java:268)
	at com.tinkerpop.blueprints.impls.orient.OrientBaseGraph.<init>(OrientBaseGraph.java:146)
	at com.tinkerpop.blueprints.impls.orient.OrientTransactionalGraph.<init>(OrientTransactionalGraph.java:77)
	at com.tinkerpop.blueprints.impls.orient.OrientGraph.<init>(OrientGraph.java:135)
	at com.tinkerpop.blueprints.impls.orient.OrientGraphFactory$1.getGraph(OrientGraphFactory.java:84)
	at com.tinkerpop.blueprints.impls.orient.OrientGraphFactory.getTx(OrientGraphFactory.java:221)
	at com.activitystream.OpenTest.main(OpenTest.java:12)
Caused by: java.io.EOFException: End of file is reached
	at com.orientechnologies.orient.core.storage.impl.local.paginated.OPaginatedStorageDirtyFlag.readByteBuffer(OPaginatedStorageDirtyFlag.java:286)
	at com.orientechnologies.orient.core.storage.impl.local.paginated.OPaginatedStorageDirtyFlag.open(OPaginatedStorageDirtyFlag.java:135)
	at com.orientechnologies.orient.core.storage.impl.local.paginated.OLocalPaginatedStorage.preOpenSteps(OLocalPaginatedStorage.java:331)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.open(OAbstractPaginatedStorage.java:295)
	... 10 more
</pre>

## Steps to reproduce  
1. Create fresh graph with 2.2.17
2. Try to open with latest 2.2.18 snapshot

**Comment by laa** [comment]
Hi, fixed.

**Comment by acmeguy** [comment]
Are you forgetting to push something @laa ?

**Comment by laa** [comment]
Right, https://github.com/orientechnologies/orientdb/commit/f42259c1e9630598dbad84f06e05f55e12c6ef27 sorry.

**Comment by peturrun** [comment]
Works fine now, thanks!
