### ISSUE TITLE
3.0.0-497-snapshot: db upgrade + traverse -> NPE

### ISSUE THREAD

**Issue by santo-it** [orientechnologies/orientdb#7315]
Hi,

Part of the _3.0 Support Readiness_ process, I am testing database binary compatibility. 

How to reproduce the issue:

1. download orientdb version of the panama-papers db (this has been created with 2.2): https://github.com/santo-it/panama-papers-orientdb
2. unzip the db in the `databases` directory
3. start the server and connect via `Studio`
4. execute the query

```
TRAVERSE * FROM (MATCH {class: Officer, as: o, where:(name.toLowerCase() LIKE "pedro delgado")} RETURN o) MAXDEPTH 6
```

Result:

```
Internal server error:

java.lang.NullPointerException
        at com.orientechnologies.orient.core.sql.executor.DepthFirstTraverseStep.fetchNextEntryPoints(DepthFirstTraverseStep.java:25)
        at com.orientechnologies.orient.core.sql.executor.AbstractTraverseStep.fetchNextBlock(AbstractTraverseStep.java:97)
        at com.orientechnologies.orient.core.sql.executor.AbstractTraverseStep.access$000(AbstractTraverseStep.java:15)
        at com.orientechnologies.orient.core.sql.executor.AbstractTraverseStep$1.hasNext(AbstractTraverseStep.java:44)
        at com.orientechnologies.orient.core.sql.parser.OLocalResultSet.fetchNext(OLocalResultSet.java:28)
        at com.orientechnologies.orient.core.sql.parser.OLocalResultSet.<init>(OLocalResultSet.java:23)
        at com.orientechnologies.orient.core.sql.parser.OTraverseStatement.execute(OTraverseStatement.java:77)
        at com.orientechnologies.orient.core.sql.parser.OStatement.execute(OStatement.java:55)
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentEmbedded.command(ODatabaseDocumentEmbedded.java:397)
        at com.orientechnologies.orient.server.network.protocol.http.command.post.OServerCommandPostCommand.executeStatement(OServerCommandPostCommand.java:174)
        at com.orientechnologies.orient.server.network.protocol.http.command.post.OServerCommandPostCommand.execute(OServerCommandPostCommand.java:84)
        at com.orientechnologies.orient.server.network.protocol.http.command.post.OServerCommandPostCommandGraph.execute(OServerCommandPostCommandGraph.java:36)
        at com.orientechnologies.orient.server.network.protocol.http.ONetworkProtocolHttpAbstract.service(ONetworkProtocolHttpAbstract.java:168)
        at com.orientechnologies.orient.server.network.protocol.http.ONetworkProtocolHttpAbstract.execute(ONetworkProtocolHttpAbstract.java:625)
        at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:77)
```

Thanks,

**Comment by luigidellaquila** [comment]
Thanks @santo-it 

I'll check it asap

Luigi

**Comment by luigidellaquila** [comment]
Hi @santo-it 

I just pushed a fix on develop branch.

Closing, thanks!

Luigi
