### ISSUE TITLE
Java App waiting indefinitely on read lock

### ISSUE THREAD

**Issue by busbaby** [orientechnologies/orientdb#7328]
## Expected behavior  
OSQLSynchQuery should complete without waiting indefinitely for read lock.

Dependencies:
com.orientechnologies:orientdb-core:2.2.18
com.orientechnologies:orientdb-client:2.2.18

## Actual behavior  
Please see attached jstack dump.

## Steps to reproduce  
<add here>  
[acquireReadLock.txt](https://github.com/orientechnologies/orientdb/files/911366/acquireReadLock.txt)

**Comment by laa** [comment]
@tglman could you take a look ?

**Comment by busbaby** [comment]
Invalidating. It appeared as though the client was waiting indefinitely on the read lock, however the thread was in fact thrashing the connection with the same query over and over.

**Comment by tglman** [comment]
hi @busbaby,

I checked the dump, the thread that is waiting for the read lock, is waiting for this thread:
```
"OrientDB <- Asynch Client (<PRIVATE>)" #28 daemon prio=5 os_prio=0 tid=0x0000000028578000 nid=0x256c runnable [0x000000002f86e000]
   java.lang.Thread.State: RUNNABLE
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
	at java.net.SocketInputStream.read(SocketInputStream.java:170)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)
	at java.io.BufferedInputStream.fill(BufferedInputStream.java:246)
	at java.io.BufferedInputStream.read(BufferedInputStream.java:265)
	- locked <0x00000005c29e0760> (a java.io.BufferedInputStream)
	at java.io.DataInputStream.readByte(DataInputStream.java:265)
	at com.orientechnologies.orient.enterprise.channel.binary.OChannelBinary.readByte(OChannelBinary.java:68)
	at com.orientechnologies.orient.client.binary.OChannelBinaryAsynchClient.beginResponse(OChannelBinaryAsynchClient.java:194)
	at com.orientechnologies.orient.client.binary.OAsynchChannelServiceThread.execute(OAsynchChannelServiceThread.java:55)
	at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:77)
```

That is reading the data from a socket, I presume that the query is still running on the server, can you check the status of the server ?

In any case monitor you server and client log for any stack trace, if something goes wrong you should be able to see the error.

Kind Regards

**Comment by tglman** [comment]
hi,

good to know.

Regards
