### ISSUE TITLE
failed to  disable OAutomaticBackup

### ISSUE THREAD

**Issue by dataweng** [orientechnologies/orientdb#7331]
## Expected behavior  
disable automatic backup database  

## Actual behavior  
after orientdb running few minutes, automatic backup .....

then dserver.log show :

The server is frozen (usually is because a backup is running). Redirecting the request to another server^M
        DB name="gacenter_tst". Reconnecting to 10.10.10.74:2424 (from=whrzx03 to=whrzx04)
        at com.orientechnologies.agent.OEnterpriseAgent.onBeforeClientRequest(OEnterpriseAgent.java:404)
        at com.orientechnologies.orient.server.plugin.OServerPluginHelper.invokeHandlerCallbackOnBeforeClientRequest(OServerPluginHelper.java:56)
        at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.onBeforeOperationalRequest(ONetworkProtocolBinary.java:443)
        at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.sessionRequest(ONetworkProtocolBinary.java:306)
        at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.execute(ONetworkProtocolBinary.java:200)
        at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:77)

 

## Steps to reproduce  
orientdb-server-config.xml :
        <handler class="com.orientechnologies.orient.server.handler.OAutomaticBackup">
            <parameters>
                <parameter value="false" name="enabled"/>
                <parameter value="${ORIENTDB_HOME}/config/automatic-backup.json" name="config"/>
            </parameters>
        </handler>

**Comment by dataweng** [comment]
<handler class="com.orientechnologies.orient.server.handler.OAutomaticBackup">
            <parameters>
                <parameter value="false" name="enabled"/>
                <parameter value="${ORIENTDB_HOME}/config/automatic-backup.json" name="config"/>
            </parameters>
        </handler>

**Comment by lvca** [comment]
Fixed in 7a561a5a4f77a2fda180e9d6ece73ff757af2462.
