### ISSUE TITLE
Deadlock during transaction simultanios commit and index drop in distributed storage

### ISSUE THREAD

**Issue by laa** [orientechnologies/orientdb#7335]
## Expected behavior  
During commit of data and drop of indexes both operations should run without deadlocking of each other

## Actual behavior  
Because of different order in which index and storage locks are acquired during commit in distributed storage we catch deadlock sometimes

Commit stack trace
```
at com.orientechnologies.common.concur.lock.OReadersWriterSpinLock.acquireReadLock(OReadersWriterSpinLock.java:84)
    at com.orientechnologies.orient.core.index.OIndexAbstract.acquireSharedLock(OIndexAbstract.java:1083)
    at com.orientechnologies.orient.core.index.OIndexAbstract.addTxOperation(OIndexAbstract.java:759)
    at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.commitIndexes(OAbstractPaginatedStorage.java:1479)
    at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.commit(OAbstractPaginatedStorage.java:1443)
    at com.orientechnologies.orient.server.distributed.impl.ODistributedStorage.commit(ODistributedStorage.java:1380
```
Index drop stack trace
```
at com.orientechnologies.orient.core.storage.impl.local.paginated.atomicoperations.OAtomicOperationsManager.startAtomicOperation(OAtomicOperationsManager.java:142)
    at com.orientechnologies.orient.core.storage.impl.local.paginated.base.ODurableComponent.startAtomicOperation(ODurableComponent.java:123)
    at com.orientechnologies.orient.core.index.sbtree.local.OSBTree.delete(OSBTree.java:349)
    at com.orientechnologies.orient.core.index.engine.OSBTreeIndexEngine.delete(OSBTreeIndexEngine.java:87)
    at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.deleteIndexEngine(OAbstractPaginatedStorage.java:1673)
    at com.orientechnologies.orient.core.index.OIndexAbstract.delete(OIndexAbstract.java:649)
    at com.orientechnologies.orient.core.index.OIndexAbstract.delete(OIndexAbstract.java:71)
    at com.orientechnologies.orient.core.index.OIndexManagerShared.dropIndex(OIndexManagerShared.java:257)
```

**Comment by lvca** [comment]
This is the last trace with an updated 2.2.x:
```
Found one Java-level deadlock:
=============================
"OrientDB DistributedWorker node=europe-2 db=distributed-backup1node id=4":
  waiting for ownable synchronizer 0x00000006c1702910, (a com.orientechnologies.common.concur.lock.OReadersWriterSpinLock),
  which is held by "OrientDB DistributedWorker node=europe-2 db=distributed-backup1node id=0"
"OrientDB DistributedWorker node=europe-2 db=distributed-backup1node id=0":
  waiting for ownable synchronizer 0x00000006c17516d0, (a java.util.concurrent.locks.ReentrantReadWriteLock$NonfairSync),
  which is held by "OrientDB DistributedWorker node=europe-2 db=distributed-backup1node id=4"

Java stack information for the threads listed above:
===================================================
"OrientDB DistributedWorker node=europe-2 db=distributed-backup1node id=4":
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x00000006c1702910> (a com.orientechnologies.common.concur.lock.OReadersWriterSpinLock)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
	at com.orientechnologies.common.concur.lock.OReadersWriterSpinLock.acquireReadLock(OReadersWriterSpinLock.java:87)
	at com.orientechnologies.orient.core.index.OIndexAbstract.acquireSharedLock(OIndexAbstract.java:1083)
	at com.orientechnologies.orient.core.index.OIndexAbstract.addTxOperation(OIndexAbstract.java:759)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.commitIndexes(OAbstractPaginatedStorage.java:1477)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.commit(OAbstractPaginatedStorage.java:1442)
	at com.orientechnologies.orient.server.distributed.impl.ODistributedStorage.commit(ODistributedStorage.java:1381)
	at com.orientechnologies.orient.core.tx.OTransactionOptimistic.doCommit(OTransactionOptimistic.java:527)
	at com.orientechnologies.orient.core.tx.OTransactionOptimistic.commit(OTransactionOptimistic.java:99)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.commit(ODatabaseDocumentTx.java:2845)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.commit(ODatabaseDocumentTx.java:2814)
	at com.orientechnologies.orient.server.distributed.impl.task.OTxTask.execute(OTxTask.java:131)
	at com.orientechnologies.orient.server.distributed.impl.ODistributedAbstractPlugin$1.call(ODistributedAbstractPlugin.java:587)
	at com.orientechnologies.orient.core.db.OScenarioThreadLocal.executeAsDistributed(OScenarioThreadLocal.java:70)
	at com.orientechnologies.orient.server.distributed.impl.ODistributedAbstractPlugin.executeOnLocalNode(ODistributedAbstractPlugin.java:583)
	at com.orientechnologies.orient.server.distributed.impl.ODistributedWorker.onMessage(ODistributedWorker.java:328)
	at com.orientechnologies.orient.server.distributed.impl.ODistributedWorker.run(ODistributedWorker.java:104)
"OrientDB DistributedWorker node=europe-2 db=distributed-backup1node id=0":
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x00000006c17516d0> (a java.util.concurrent.locks.ReentrantReadWriteLock$NonfairSync)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.parkAndCheckInterrupt(AbstractQueuedSynchronizer.java:836)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireQueued(AbstractQueuedSynchronizer.java:870)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquire(AbstractQueuedSynchronizer.java:1199)
	at java.util.concurrent.locks.ReentrantReadWriteLock$WriteLock.lock(ReentrantReadWriteLock.java:943)
	at com.orientechnologies.common.concur.lock.OOneEntryPerKeyLockManager.acquireLock(OOneEntryPerKeyLockManager.java:171)
	at com.orientechnologies.common.concur.lock.OOneEntryPerKeyLockManager.acquireLock(OOneEntryPerKeyLockManager.java:101)
	at com.orientechnologies.orient.core.storage.impl.local.paginated.atomicoperations.OAtomicOperationsManager.acquireExclusiveLockTillOperationComplete(OAtomicOperationsManager.java:503)
	at com.orientechnologies.orient.core.storage.impl.local.paginated.atomicoperations.OAtomicOperationsManager.startAtomicOperation(OAtomicOperationsManager.java:236)
	at com.orientechnologies.orient.core.storage.impl.local.paginated.atomicoperations.OAtomicOperationsManager.startAtomicOperation(OAtomicOperationsManager.java:142)
	at com.orientechnologies.orient.core.storage.impl.local.paginated.base.ODurableComponent.startAtomicOperation(ODurableComponent.java:123)
	at com.orientechnologies.orient.core.index.sbtree.local.OSBTree.delete(OSBTree.java:349)
	at com.orientechnologies.orient.core.index.engine.OSBTreeIndexEngine.delete(OSBTreeIndexEngine.java:87)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.deleteIndexEngine(OAbstractPaginatedStorage.java:1671)
	at com.orientechnologies.orient.core.index.OIndexAbstract.delete(OIndexAbstract.java:649)
	at com.orientechnologies.orient.core.index.OIndexAbstract.delete(OIndexAbstract.java:71)
	at com.orientechnologies.orient.core.index.OIndexManagerShared.dropIndex(OIndexManagerShared.java:257)
	at com.orientechnologies.orient.core.index.OIndexManagerProxy.dropIndex(OIndexManagerProxy.java:100)
	at com.orientechnologies.orient.core.sql.OCommandExecutorSQLDropIndex.execute(OCommandExecutorSQLDropIndex.java:96)
	at com.orientechnologies.orient.core.sql.OCommandExecutorSQLDelegate.execute(OCommandExecutorSQLDelegate.java:74)
	at com.orientechnologies.orient.server.distributed.impl.task.OSQLCommandTask.execute(OSQLCommandTask.java:121)
	at com.orientechnologies.orient.server.distributed.impl.ODistributedAbstractPlugin$1.call(ODistributedAbstractPlugin.java:587)
	at com.orientechnologies.orient.core.db.OScenarioThreadLocal.executeAsDistributed(OScenarioThreadLocal.java:70)
	at com.orientechnologies.orient.server.distributed.impl.ODistributedAbstractPlugin.executeOnLocalNode(ODistributedAbstractPlugin.java:583)
	at com.orientechnologies.orient.server.distributed.impl.ODistributedWorker.onMessage(ODistributedWorker.java:328)
	at com.orientechnologies.orient.server.distributed.impl.ODistributedWorker.run(ODistributedWorker.java:104)

Found 1 deadlock.
```

**Comment by lvca** [comment]
To reproduce it, just run the test `OneNodeBackupTest`.

**Comment by laa** [comment]
@lvca I have tried to run test, but as result I always get:

```
com.orientechnologies.orient.server.distributed.ODistributedStartupException: Error on starting distributed plugin

	at com.orientechnologies.orient.server.hazelcast.OHazelcastPlugin.startup(OHazelcastPlugin.java:309)
	at com.orientechnologies.orient.server.OServer.registerPlugins(OServer.java:1242)
	at com.orientechnologies.orient.server.OServer.activate(OServer.java:397)
	at com.orientechnologies.orient.server.distributed.ServerRun.startServer(ServerRun.java:179)
	at com.orientechnologies.orient.server.distributed.AbstractServerClusterTest.startServers(AbstractServerClusterTest.java:171)
	at com.orientechnologies.orient.server.distributed.AbstractServerClusterTest.execute(AbstractServerClusterTest.java:118)
	at com.orientechnologies.orient.server.distributed.OneNodeBackupTest.test(OneNodeBackupTest.java:58)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:51)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
Caused by: java.lang.NullPointerException
	at com.orientechnologies.orient.server.hazelcast.OHazelcastPlugin$6.call(OHazelcastPlugin.java:743)
	at com.orientechnologies.orient.server.hazelcast.OHazelcastPlugin$6.call(OHazelcastPlugin.java:727)
	at com.orientechnologies.orient.server.distributed.impl.ODistributedAbstractPlugin.executeInDistributedDatabaseLock(ODistributedAbstractPlugin.java:1669)
	at com.orientechnologies.orient.server.hazelcast.OHazelcastPlugin.loadLocalDatabases(OHazelcastPlugin.java:727)
	at com.orientechnologies.orient.server.hazelcast.OHazelcastPlugin.startup(OHazelcastPlugin.java:254)
	... 28 more

```

Will try to fix using thread dump

**Comment by laa** [comment]
@lvca I have tried `OneNodeBackupTest` this tests two hours in a row and was not able to detect any deadlock could you check that deadlock is still present.

**Comment by lvca** [comment]
I can't reproduce it anymore, it looks like it has been fixed.
