### ISSUE TITLE
java.lang.NoClassDefFoundError: com/orientechnologies/common/directmemory/OByteBufferPool

### ISSUE THREAD

**Issue by lucafrosini** [orientechnologies/orientdb#7345]
## Actual behavior  
I'm runnign a java application inside Tomcat. On tomcat shutdown I obtain the following exception:

```
Exception in thread "Thread-4" java.lang.NoClassDefFoundError: com/orientechnologies/common/directmemory/OByteBufferPool
	at com.orientechnologies.orient.core.Orient$OShutdownEnginesHandler.shutdown(Orient.java:930)
	at com.orientechnologies.orient.core.Orient.shutdown(Orient.java:331)
	at com.orientechnologies.orient.core.OrientShutdownHook.run(OrientShutdownHook.java:40)
Caused by: java.lang.ClassNotFoundException: com.orientechnologies.common.directmemory.OByteBufferPool
	at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1892)
	at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1735)
	... 3 more


```

**Comment by laa** [comment]
@lucafrosini you use incorrect distribution, system can not find class in class loader

**Comment by lucafrosini** [comment]
I have the following dependencies in my pom. Am I missing something or am I doing some mistakes?

```
		<dependency>
			<groupId>com.orientechnologies</groupId>
			<artifactId>orientdb-graphdb</artifactId>
			<version>2.2.18</version>
		</dependency>
		<dependency>
			<groupId>com.tinkerpop</groupId>
			<artifactId>frames</artifactId>
			<version>2.6.0</version>
		</dependency>
```

**Comment by laa** [comment]
you should generate dependency graph I suppose tinkerpop adds old orientdb version which overwrites one which you specified.

**Comment by lucafrosini** [comment]
Sorry, but I'm in trouble.

```
<groupId>com.orientechnologies</groupId>
<artifactId>orientdb-graphdb</artifactId>
<version>2.2.18</version>
```
uses as parent 

```
<groupId>com.orientechnologies</groupId>
<artifactId>orientdb-parent</artifactId>
<version>2.2.18</version>
```
which declares 

```
<blueprints.version>2.6.0</blueprints.version>
```

For such a reason I added the 2.6.0 version of frames.

Anyway I removed frames from my dependencies but I'm still getting the exception.

Do you have any ideas?

**Comment by laa** [comment]
@lucafrosini could you run ```mvn dependency:tree -Dverbose```  and attach gist to this issue?

**Comment by lucafrosini** [comment]
This is the full dependency tree: Most of dependencies (org.gcube) are internal of gcube project and should not impact.

```
[INFO] org.gcube.information-system:resource-registry:war:1.4.0-SNAPSHOT
[INFO] +- org.gcube.core:common-encryption:jar:1.0.3-SNAPSHOT:provided
[INFO] |  \- org.gcube.core:common-scope:jar:1.2.1-SNAPSHOT:provided
[INFO] |     +- (org.gcube.core:common-configuration-scanner:jar:1.1.0-SNAPSHOT:provided - omitted for duplicate)
[INFO] |     +- org.gcube.core:common-scope-maps:jar:1.0.6-SNAPSHOT:provided
[INFO] |     \- (org.slf4j:slf4j-api:jar:1.7.5:provided - version managed from 1.7.2; omitted for duplicate)
[INFO] +- org.gcube.core:common-smartgears-app:jar:2.0.2-SNAPSHOT:provided
[INFO] |  +- org.reflections:reflections:jar:0.9.10:provided
[INFO] |  |  +- (com.google.guava:guava:jar:15.0:provided - omitted for conflict with 18.0)
[INFO] |  |  +- (org.javassist:javassist:jar:3.19.0-GA:provided - omitted for conflict with 3.20.0-GA)
[INFO] |  |  \- com.google.code.findbugs:annotations:jar:2.0.1:provided
[INFO] |  +- (org.javassist:javassist:jar:3.20.0-GA:compile - scope updated from provided; omitted for duplicate)
[INFO] |  \- com.google.guava:guava:jar:18.0:provided
[INFO] +- org.gcube.common:authorization-client:jar:2.0.1-SNAPSHOT:provided (scope not updated to compile)
[INFO] |  +- (org.gcube.common:common-authorization:jar:2.0.2-SNAPSHOT:provided - omitted for duplicate)
[INFO] |  \- (org.slf4j:slf4j-api:jar:1.7.5:provided - version managed from 1.6.4; omitted for duplicate)
[INFO] +- org.gcube.common:common-authorization:jar:2.0.2-SNAPSHOT:provided
[INFO] |  +- (org.gcube.core:common-scope:jar:1.2.1-SNAPSHOT:provided - omitted for duplicate)
[INFO] |  +- org.gcube.core:common-configuration-scanner:jar:1.1.0-SNAPSHOT:provided
[INFO] |  |  \- (org.slf4j:slf4j-api:jar:1.7.5:provided - version managed from 1.6.4; omitted for duplicate)
[INFO] |  \- (org.slf4j:slf4j-api:jar:1.7.5:provided - version managed from 1.6.4; omitted for duplicate)
[INFO] +- org.gcube.information-system:resource-registry-api:jar:1.4.0-SNAPSHOT:compile
[INFO] |  +- (org.gcube.information-system:information-system-model:jar:1.4.0-SNAPSHOT:compile - omitted for duplicate)
[INFO] |  \- (org.gcube.common:authorization-client:jar:2.0.1-SNAPSHOT:compile - omitted for duplicate)
[INFO] +- org.gcube.information-system:information-system-model:jar:1.4.0-SNAPSHOT:compile
[INFO] |  +- com.fasterxml.jackson.core:jackson-databind:jar:2.6.0:compile
[INFO] |  |  +- (com.fasterxml.jackson.core:jackson-annotations:jar:2.6.0:compile - omitted for duplicate)
[INFO] |  |  \- (com.fasterxml.jackson.core:jackson-core:jar:2.6.0:compile - omitted for duplicate)
[INFO] |  +- com.fasterxml.jackson.core:jackson-annotations:jar:2.6.0:compile
[INFO] |  \- com.fasterxml.jackson.core:jackson-core:jar:2.6.0:compile
[INFO] +- com.orientechnologies:orientdb-graphdb:jar:2.2.18:compile
[INFO] |  +- com.orientechnologies:orientdb-server:jar:2.2.18:compile
[INFO] |  |  +- com.orientechnologies:orientdb-client:jar:2.2.18:compile
[INFO] |  |  |  \- (com.orientechnologies:orientdb-core:jar:2.2.18:compile - omitted for duplicate)
[INFO] |  |  +- (com.orientechnologies:orientdb-tools:jar:2.2.18:compile - omitted for duplicate)
[INFO] |  |  \- javax.mail:mail:jar:1.4.7:compile
[INFO] |  |     \- javax.activation:activation:jar:1.1:compile
[INFO] |  +- com.orientechnologies:orientdb-tools:jar:2.2.18:compile
[INFO] |  |  +- (com.orientechnologies:orientdb-client:jar:2.2.18:compile - omitted for duplicate)
[INFO] |  |  +- (com.orientechnologies:orientdb-core:jar:2.2.18:compile - omitted for duplicate)
[INFO] |  |  \- (com.fasterxml.jackson.core:jackson-databind:jar:2.6.0:compile - omitted for duplicate)
[INFO] |  +- com.orientechnologies:orientdb-core:jar:2.2.18:compile
[INFO] |  |  +- org.xerial.snappy:snappy-java:jar:1.1.0.1:compile
[INFO] |  |  \- com.googlecode.concurrentlinkedhashmap:concurrentlinkedhashmap-lru:jar:1.4.1:compile
[INFO] |  +- commons-collections:commons-collections:jar:3.2.2:compile
[INFO] |  \- com.tinkerpop.blueprints:blueprints-core:jar:2.6.0:compile
[INFO] |     +- org.codehaus.jettison:jettison:jar:1.3.3:compile
[INFO] |     |  \- stax:stax-api:jar:1.0.1:compile
[INFO] |     +- (com.fasterxml.jackson.core:jackson-databind:jar:2.6.0:compile - version managed from 2.2.3; omitted for duplicate)
[INFO] |     +- com.carrotsearch:hppc:jar:0.6.0:compile
[INFO] |     +- commons-configuration:commons-configuration:jar:1.6:compile
[INFO] |     |  +- commons-lang:commons-lang:jar:2.4:compile
[INFO] |     |  +- commons-digester:commons-digester:jar:1.8:compile
[INFO] |     |  |  \- commons-beanutils:commons-beanutils:jar:1.7.0:compile
[INFO] |     |  \- commons-beanutils:commons-beanutils-core:jar:1.8.0:compile
[INFO] |     \- commons-logging:commons-logging:jar:1.1.1:compile
[INFO] +- javax.ws.rs:javax.ws.rs-api:jar:2.0.1:compile
[INFO] +- org.glassfish.jersey.containers:jersey-container-servlet:jar:2.13:compile
[INFO] |  +- org.glassfish.jersey.containers:jersey-container-servlet-core:jar:2.13:compile
[INFO] |  |  +- org.glassfish.hk2.external:javax.inject:jar:2.3.0-b10:compile
[INFO] |  |  +- (org.glassfish.jersey.core:jersey-common:jar:2.13:compile - omitted for duplicate)
[INFO] |  |  +- (org.glassfish.jersey.core:jersey-server:jar:2.13:compile - omitted for duplicate)
[INFO] |  |  \- (javax.ws.rs:javax.ws.rs-api:jar:2.0.1:compile - omitted for duplicate)
[INFO] |  +- org.glassfish.jersey.core:jersey-common:jar:2.13:compile
[INFO] |  |  +- (javax.ws.rs:javax.ws.rs-api:jar:2.0.1:compile - omitted for duplicate)
[INFO] |  |  +- javax.annotation:javax.annotation-api:jar:1.2:compile
[INFO] |  |  +- org.glassfish.jersey.bundles.repackaged:jersey-guava:jar:2.13:compile
[INFO] |  |  +- org.glassfish.hk2:hk2-api:jar:2.3.0-b10:compile
[INFO] |  |  |  +- org.glassfish.hk2:hk2-utils:jar:2.3.0-b10:compile
[INFO] |  |  |  \- org.glassfish.hk2.external:aopalliance-repackaged:jar:2.3.0-b10:compile
[INFO] |  |  +- (org.glassfish.hk2.external:javax.inject:jar:2.3.0-b10:compile - omitted for duplicate)
[INFO] |  |  +- org.glassfish.hk2:hk2-locator:jar:2.3.0-b10:compile
[INFO] |  |  |  +- (org.glassfish.hk2.external:javax.inject:jar:2.3.0-b10:compile - omitted for duplicate)
[INFO] |  |  |  +- (org.glassfish.hk2.external:aopalliance-repackaged:jar:2.3.0-b10:compile - omitted for duplicate)
[INFO] |  |  |  +- (org.glassfish.hk2:hk2-api:jar:2.3.0-b10:compile - omitted for duplicate)
[INFO] |  |  |  +- (org.glassfish.hk2:hk2-utils:jar:2.3.0-b10:compile - omitted for duplicate)
[INFO] |  |  |  \- org.javassist:javassist:jar:3.18.1-GA:compile
[INFO] |  |  \- org.glassfish.hk2:osgi-resource-locator:jar:1.0.1:compile
[INFO] |  +- org.glassfish.jersey.core:jersey-server:jar:2.13:compile
[INFO] |  |  +- (org.glassfish.jersey.core:jersey-common:jar:2.13:compile - omitted for duplicate)
[INFO] |  |  +- org.glassfish.jersey.core:jersey-client:jar:2.17:compile
[INFO] |  |  |  +- (org.glassfish.jersey.core:jersey-common:jar:2.13:compile - omitted for duplicate)
[INFO] |  |  |  +- (javax.ws.rs:javax.ws.rs-api:jar:2.0.1:compile - omitted for duplicate)
[INFO] |  |  |  +- (org.glassfish.hk2:hk2-api:jar:2.3.0-b10:compile - omitted for duplicate)
[INFO] |  |  |  +- (org.glassfish.hk2.external:javax.inject:jar:2.3.0-b10:compile - omitted for duplicate)
[INFO] |  |  |  \- (org.glassfish.hk2:hk2-locator:jar:2.3.0-b10:compile - omitted for duplicate)
[INFO] |  |  +- (javax.ws.rs:javax.ws.rs-api:jar:2.0.1:compile - omitted for duplicate)
[INFO] |  |  +- (javax.annotation:javax.annotation-api:jar:1.2:compile - omitted for duplicate)
[INFO] |  |  +- (org.glassfish.hk2:hk2-api:jar:2.3.0-b10:compile - omitted for duplicate)
[INFO] |  |  +- (org.glassfish.hk2.external:javax.inject:jar:2.3.0-b10:compile - omitted for duplicate)
[INFO] |  |  +- (org.glassfish.hk2:hk2-locator:jar:2.3.0-b10:compile - omitted for duplicate)
[INFO] |  |  \- javax.validation:validation-api:jar:1.1.0.Final:compile
[INFO] |  \- (javax.ws.rs:javax.ws.rs-api:jar:2.0.1:compile - omitted for duplicate)
[INFO] +- javax.servlet:javax.servlet-api:jar:3.0.1:provided
[INFO] +- org.slf4j:slf4j-api:jar:1.7.5:provided
[INFO] +- junit:junit:jar:4.11:test
[INFO] |  \- org.hamcrest:hamcrest-core:jar:1.3:test
[INFO] +- org.glassfish.jersey.test-framework.providers:jersey-test-framework-provider-simple:jar:2.17:test
[INFO] |  +- org.glassfish.jersey.test-framework:jersey-test-framework-core:jar:2.17:test
[INFO] |  |  +- (org.glassfish.jersey.core:jersey-server:jar:2.17:test - omitted for conflict with 2.13)
[INFO] |  |  +- (org.glassfish.jersey.containers:jersey-container-servlet-core:jar:2.17:test - omitted for conflict with 2.13)
[INFO] |  |  +- (javax.servlet:javax.servlet-api:jar:3.0.1:test - omitted for duplicate)
[INFO] |  |  +- (junit:junit:jar:4.11:test - omitted for duplicate)
[INFO] |  |  \- (org.ow2.asm:asm-debug-all:jar:5.0.2:test - omitted for duplicate)
[INFO] |  +- org.glassfish.jersey.containers:jersey-container-simple-http:jar:2.17:test
[INFO] |  |  +- (org.glassfish.hk2.external:javax.inject:jar:2.4.0-b10:test - omitted for conflict with 2.3.0-b10)
[INFO] |  |  +- org.simpleframework:simple:jar:5.1.4:test
[INFO] |  |  +- (org.glassfish.jersey.core:jersey-common:jar:2.17:test - omitted for conflict with 2.13)
[INFO] |  |  +- (org.glassfish.jersey.core:jersey-server:jar:2.17:test - omitted for conflict with 2.13)
[INFO] |  |  \- (javax.ws.rs:javax.ws.rs-api:jar:2.0.1:test - omitted for duplicate)
[INFO] |  +- (org.glassfish.jersey.core:jersey-server:jar:2.17:test - omitted for conflict with 2.13)
[INFO] |  +- (org.glassfish.jersey.core:jersey-client:jar:2.17:compile - scope updated from test; omitted for duplicate)
[INFO] |  +- (junit:junit:jar:4.11:test - omitted for duplicate)
[INFO] |  \- org.ow2.asm:asm-debug-all:jar:5.0.2:test
[INFO] +- org.gcube.information-system:gcube-resources:jar:1.4.0-SNAPSHOT:test
[INFO] |  +- (org.gcube.information-system:information-system-model:jar:1.4.0-SNAPSHOT:test - omitted for duplicate)
[INFO] |  +- (com.fasterxml.jackson.core:jackson-databind:jar:2.6.0:test - version managed from 2.2.3; omitted for duplicate)
[INFO] |  +- (com.fasterxml.jackson.core:jackson-annotations:jar:2.6.0:test - omitted for duplicate)
[INFO] |  \- (com.fasterxml.jackson.core:jackson-core:jar:2.6.0:test - omitted for duplicate)
[INFO] \- ch.qos.logback:logback-classic:jar:1.0.13:test
[INFO]    +- ch.qos.logback:logback-core:jar:1.0.13:test
[INFO]    \- (org.slf4j:slf4j-api:jar:1.7.5:test - version managed from 1.6.4; omitted for duplicate)

```

**Comment by laa** [comment]
Ok . Then next step )) Is it possible to share project with me so I will repeat exception ?

**Comment by lucafrosini** [comment]
It is not so simple because you need our container (a tomcat plus some gcube libraries)

The source code is available here (Open source code with EUPL licence):
http://svn.research-infrastructures.eu/public/d4science/gcube/trunk/information-system/resource-registry/

You can find the compiled war here:
https://goo.gl/lQyW12


Moreover you have to download our bundle which provide a tomcat and an installation script wich mainly copy some lib in tomcat/lib folder from here:

http://maven.research-infrastructures.eu/nexus/service/local/repositories/gcube-releases/content/org/gcube/distribution/smartgears-distribution-bundle/2.1.0-4.3.0-142337/smartgears-distribution-bundle-2.1.0-4.3.0-142337.tar.gz


Then there is simple procedure to follow but you have to spent half an hour to complete the whole installation. If you think is useful I'll be happy to provide all details and I'll send a secret key privately.

Otherwise I'll try to isolate the project to be able to run in a standard tomcat container.

Let me know.

**Comment by lucafrosini** [comment]
This is the full list of library in tomcat/lib so you can check if there a library which can cause conflict

```
accounting-lib-2.5.0-20170323.091541-12.jar
annotations-api.jar
authorization-client-2.0.1-20170411.133935-356.jar
catalina-ant.jar
catalina-ha.jar
catalina.jar
catalina-tribes.jar
common-authorization-2.0.2-20170411.133745-84.jar
common-configuration-scanner-1.1.0-20170411.134613-951.jar
common-encryption-1.0.3-20170217.102619-1.jar
common-events-1.0.1-20170410.184058-980.jar
common-gcore-resources-1.3.2-20170411.134548-939.jar
common-gcore-stubs-1.2.2-20170410.225617-397.jar
common-scope-1.2.1-20170411.134527-404.jar
common-scope-maps-1.0.6-20170213.164847-1.jar
common-smartgears-2.2.0-SNAPSHOT.jar
common-smartgears-utils-1.0.3-20170410.203850-11.jar
common-validator-1.0.0-20170410.230755-1552.jar
core-io-1.4.4.jar
discovery-client-1.0.1-20170410.225649-2045.jar
document-store-lib-1.6.0-20170405.082727-62.jar
document-store-lib-couchbase-1.3.1-20170411.002005-16.jar
ecj-4.4.2.jar
el-api.jar
ic-client-1.0.3-20170213.140529-2.jar
jackson-annotations-2.6.0.jar
jackson-core-2.6.0.jar
jackson-databind-2.6.0.jar
jasper-el.jar
jasper.jar
java-client-2.2.3.jar
jsp-api.jar
logback-classic-1.0.13.jar
logback-core-1.0.13.jar
logback.xml
registry-publisher-1.2.8-20170411.095610-1.jar
rxjava-1.2.7.jar
servlet-api.jar
slf4j-api-1.7.5.jar
smartgears-app.list
smartgears.list
tomcat7-websocket.jar
tomcat-api.jar
tomcat-coyote.jar
tomcat-dbcp.jar
tomcat-i18n-es.jar
tomcat-i18n-fr.jar
tomcat-i18n-ja.jar
tomcat-jdbc.jar
tomcat-util.jar
websocket-api.jar
```

**Comment by laa** [comment]
@lucafrosini I just checked a jar file inside the war and OByteBufferPool is present there http://i.imgur.com/oLL8DCj.png . It looks like class loader issue then. In such case, I propose you to disable shutdown hook. During the start of your web application in application context listener, for example, could you call method https://github.com/orientechnologies/orientdb/blob/2.2.x/core/src/main/java/com/orientechnologies/orient/core/Orient.java#L698 . It will disable hook, and I hope it will solve your problem. But because you disabled hook, during a stop of your application (again an application context listener is a right place ) you should manually call https://github.com/orientechnologies/orientdb/blob/2.2.x/core/src/main/java/com/orientechnologies/orient/core/Orient.java#L921 . Hope it will help.

**Comment by lucafrosini** [comment]
Thanks a lot. I'll do as you suggested

**Comment by lucafrosini** [comment]
Removing the other webapp the exception disappears. So, I confirm that is something related to classloader. Thanks a lot
