### ISSUE TITLE
WebLogic 12c Embedded xerces Class Cast Exception

### ISSUE THREAD

**Issue by fredfortier** [orientechnologies/orientdb#7367]
### OS: Windows Server 2008

I running full OrientDB server embedded in my Java EE application. We're often targeting WebSphere but occasionally other application servers. I just tried running it on WebLogic 12c. I received this exception on startup. 
`weblogic.application.ModuleException: java.lang.ClassCastException: com.sun.org.apache.xerces.internal.dom.ElementNSImpl cannot be cast to com.orientechnologi
enerConfiguration
        at weblogic.application.internal.ExtensibleModuleWrapper.start(ExtensibleModuleWrapper.java:140)
        at weblogic.application.internal.flow.ModuleListenerInvoker.start(ModuleListenerInvoker.java:124)
        at weblogic.application.internal.flow.ModuleStateDriver$3.next(ModuleStateDriver.java:216)
        at weblogic.application.internal.flow.ModuleStateDriver$3.next(ModuleStateDriver.java:211)
        at weblogic.application.utils.StateMachineDriver.nextState(StateMachineDriver.java:42)
        Truncated. see log file for complete stacktrace
Caused By: java.lang.ClassCastException: com.sun.org.apache.xerces.internal.dom.ElementNSImpl cannot be cast to com.orientechnologies.orient.server.config.OSe
        at com.orientechnologies.orient.server.OServer.activate(OServer.java:322)
        at com.enchoice.kwcn.ejbs.impl.DatabaseServerBean.warmUpApplication(DatabaseServerBean.java:99)
        at com.enchoice.kwcn.ejbs.impl.DatabaseServerBean.init(DatabaseServerBean.java:65)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        Truncated. see log file for complete stacktrace`

I assume that OrientDB wants a specific version of xerces which does not match the version which ships with WebLogic. I tried the following filter which did not work.
`    
<prefer-application-packages>
        <package-name>com.sun.org.apache.xerces.*</package-name>
    </prefer-application-packages>
`

Do you have any recommendation based on your own testing with WebLogic?

**Comment by fredfortier** [comment]
After more investigation, I believe that the issue might be JAXB implementation of WebLogic 12c versus what's expected by OrientDB. I might be able to solve this by including alternate JAXB libraries in my application. Which JAXB implementation is compatible with OrientDB?

**Comment by fredfortier** [comment]
I was able to fix the issue by adding this entry into my weblogic-application.xml.
`<prefer-application-resources>
    <resource-name>META-INF/services/javax.xml.bind.JAXBContext</resource-name>
</prefer-application-resources>`

Where javax.xml.bind.JAXBContext contains this:
`com.sun.xml.bind.v2.ContextFactory`

**Comment by lvca** [comment]
Cool, thanks for sharing it.

**Comment by mayurbavisiya** [comment]
java.lang.ClassNotFoundException: org/apache/xerces/jaxp/DocumentBuilderFactoryImpl at java.lang.Class.forName0(Native Method) at java.lang.Class.forName(Class.java:348) at javax.xml.parsers.FactoryFinder.getProviderClass(FactoryFinder.java:124) at javax.xml.parsers.FactoryFinder.newInstance(FactoryFinder.java:188) at javax.xml.parsers.FactoryFinder.newInstance(FactoryFinder.java:152) at javax.xml.parsers.FactoryFinder.find(FactoryFinder.java:232) at javax.xml.parsers.DocumentBuilderFactory.newInstance(DocumentBuilderFactory.java:120)

 I am getting exception after adding resource-name>META-INF/services/javax.xml.bind.JAXBContext</resource-name> 

please recommend soln.
