### ISSUE TITLE
the uncorrected shotdown cause orientdb cache exception

### ISSUE THREAD

**Issue by weixliu** [orientechnologies/orientdb#7402]
## Actual behavior  
```
2017-05-01 10:49:50:600 INFO  {db=wmcloud_cpwsw} Previous maximum cache size was 780558 current maximum cache size is 167116. Cache state for storage /wm/orientdb-community-2.2.15-SNAPSHOT/databases/wmcloud_cpwsw will not be restored. 
[O2QCache]$ANSI{green {db=wmcloud_cpwsw}} Error on updating record #106:74389 (cluster: plocal cluster: dsr_1)
java.lang.NullPointerException
	at com.orientechnologies.common.directmemory.OByteBufferPool.acquireDirect(OByteBufferPool.java:310)
	at com.orientechnologies.orient.core.storage.cache.local.OWOWCache.cacheFileContent(OWOWCache.java:1262)
	at com.orientechnologies.orient.core.storage.cache.local.OWOWCache.load(OWOWCache.java:648)
	at com.orientechnologies.orient.core.storage.cache.local.twoq.O2QCache.updateCache(O2QCache.java:1110)
	at com.orientechnologies.orient.core.storage.cache.local.twoq.O2QCache.doLoad(O2QCache.java:351)
	at com.orientechnologies.orient.core.storage.cache.local.twoq.O2QCache.load(O2QCache.java:296)
	at com.orientechnologies.orient.core.storage.cache.pages.OLruPageCache.loadPage(OLruPageCache.java:71)
	at com.orientechnologies.orient.core.storage.impl.local.paginated.atomicoperations.OAtomicOperation.loadPage(OAtomicOperation.java:128)
	at com.orientechnologies.orient.core.storage.impl.local.paginated.base.ODurableComponent.loadPage(ODurableComponent.java:150)
	at com.orientechnologies.orient.core.storage.impl.local.paginated.base.ODurableComponent.loadPage(ODurableComponent.java:142)
	at com.orientechnologies.orient.core.index.sbtreebonsai.local.OSBTreeBonsaiLocal.load(OSBTreeBonsaiLocal.java:493)
	at com.orientechnologies.orient.core.db.record.ridbag.sbtree.OSBTreeCollectionManagerShared.loadTree(OSBTreeCollectionManagerShared.java:107)
	at com.orientechnologies.orient.core.db.record.ridbag.sbtree.OSBTreeCollectionManagerAbstract.loadSBTree(OSBTreeCollectionManagerAbstract.java:174)
	at com.orientechnologies.orient.core.storage.impl.local.paginated.ORidBagUpdateSerializationOperation.loadTree(ORidBagUpdateSerializationOperation.java:76)
	at com.orientechnologies.orient.core.storage.impl.local.paginated.ORidBagUpdateSerializationOperation.execute(ORidBagUpdateSerializationOperation.java:57)
	at com.orientechnologies.orient.core.storage.impl.local.paginated.ORecordSerializationContext.executeOperations(ORecordSerializationContext.java:90)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.doUpdateRecord(OAbstractPaginatedStorage.java:3072)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.updateRecord(OAbstractPaginatedStorage.java:1121)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.executeSaveRecord(ODatabaseDocumentTx.java:2123)
	at com.orientechnologies.orient.core.tx.OTransactionNoTx.saveRecord(OTransactionNoTx.java:178)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.save(ODatabaseDocumentTx.java:2649)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.save(ODatabaseDocumentTx.java:2518)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.save(ODatabaseDocumentTx.java:101)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.updateRecord(ONetworkProtocolBinary.java:2801)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.updateRecord(ONetworkProtocolBinary.java:1719)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.executeRequest(ONetworkProtocolBinary.java:566)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.sessionRequest(ONetworkProtocolBinary.java:336)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.execute(ONetworkProtocolBinary.java:200)
	at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:77)
```

## Steps to reproduce  
The server is shut down because power off, and I don't shut orientdb before that. After power on, I just use `orinetdb.sh start` to restart the orientdb, 1 days later I got this exception. Is that because some place think the cache exist some information, and actually when I restart it, the cache is missing? cause this problem?Because when I restart it, I found this `2017-05-01 10:49:50:600 INFO  {db=wmcloud_cpwsw} Previous maximum cache size was 780558 current maximum cache size is 167116. Cache state for storage /wm/orientdb-community-2.2.15-SNAPSHOT/databases/wmcloud_cpwsw will not be restored. `

**Comment by laa** [comment]
@weixliu have you seen data restore process when you started a server ?

**Comment by weixliu** [comment]
Yes, when I started a server, the log show that it try to restore process. All the log it below.
```
2017-05-01 10:49:15:480 INFO  Loading configuration from: /wm/orientdb-community-2.2.15-SNAPSHOT/config/orientdb-server-config.xml... [OServerConfigurationLoaderXml]
2017-05-01 10:49:16:085 INFO  OrientDB Server v2.2.15-SNAPSHOT (build 2.2.x@r415f08b08db0c5229d4e6e1e25d0783392002fa3; 2017-01-04 03:21:24+0000) is starting up... [OServer]
2017-05-01 10:49:16:096 INFO  Databases directory: /wm/orientdb-community-2.2.15-SNAPSHOT/databases [OServer]
2017-05-01 10:49:16:220 INFO  OrientDB auto-config DISKCACHE=12,288MB (heap=7,851MB direct=12,288MB os=64,349MB) [OMemoryAndLocalPaginatedEnginesInitializer]
2017-05-01 10:49:16:785 INFO  Listening binary connections on 0.0.0.0:2424 (protocol v.36, socket=default) [OServerNetworkListener]
2017-05-01 10:49:16:789 INFO  Listening http connections on 0.0.0.0:2480 (protocol v.10, socket=default) [OServerNetworkListener]
2017-05-01 10:49:16:797 INFO  Found ORIENTDB_ROOT_PASSWORD variable, using this value as root's password [OServer]
2017-05-01 10:49:16:804 INFO  Installing dynamic plugin 'orientdb-studio-2.2.15-20170103.105442-4.zip'... [OServerPluginManager]
2017-05-01 10:49:16:817 INFO  ODefaultPasswordAuthenticator is active [ODefaultPasswordAuthenticator]
2017-05-01 10:49:16:818 INFO  OServerConfigAuthenticator is active [OServerConfigAuthenticator]
2017-05-01 10:49:16:820 INFO  OSystemUserAuthenticator is active [OSystemUserAuthenticator]
2017-05-01 10:49:16:860 INFO  Installed GREMLIN language v.2.6.0 - graph.pool.max=50 [OGraphServerHandler]
2017-05-01 10:49:16:860 INFO  [OVariableParser.resolveVariables] Error on resolving property: distributed [orientechnologies]
2017-05-01 10:49:16:865 WARNI Authenticated clients can execute any kind of code into the server by using the following allowed languages: [sql] [OServerSideScriptInterpreter]
2017-05-01 10:49:16:869 INFO  OrientDB Studio available at http://172.16.6.213:2480/studio/index.html [OServer]
2017-05-01 10:49:16:870 INFO  OrientDB Server is active v2.2.15-SNAPSHOT (build 2.2.x@r415f08b08db0c5229d4e6e1e25d0783392002fa3; 2017-01-04 03:21:24+0000). [OServer]
2017-05-01 10:49:34:455 WARNI {db=OSystem} Storage 'OSystem' was not closed properly. Will try to recover from write ahead log [OLocalPaginatedStorage]
2017-05-01 10:49:34:456 INFO  {db=OSystem} Looking for last checkpoint... [OLocalPaginatedStorage]
2017-05-01 10:49:34:460 INFO  {db=OSystem} Found FUZZY checkpoint. [OLocalPaginatedStorage]
2017-05-01 10:49:34:462 INFO  {db=OSystem} Data restore procedure from FUZZY checkpoint is started. [OLocalPaginatedStorage]
2017-05-01 10:49:34:465 WARNI {db=OSystem} Record com.orientechnologies.orient.core.storage.impl.local.paginated.wal.OFuzzyCheckpointEndRecord{lsn=LSN{segment=0, position=1924523}} will be skipped during data restore [OLocalPaginatedStorage]
2017-05-01 10:49:34:466 INFO  {db=OSystem} 1 operations were processed, current LSN is LSN{segment=0, position=1924523} last LSN is LSN{segment=0, position=1924576} [OLocalPaginatedStorage]
2017-05-01 10:49:34:467 WARNI {db=OSystem} Record OFuzzyCheckpointStartRecord{lsn=LSN{segment=0, position=1924530}} com.orientechnologies.orient.core.storage.impl.local.paginated.wal.OFuzzyCheckpointStartRecord{lsn=null, previousCheckpoint=LSN{segment=0, position=1924483}} will be skipped during data restore [OLocalPaginatedStorage]
2017-05-01 10:49:34:467 WARNI {db=OSystem} Record com.orientechnologies.orient.core.storage.impl.local.paginated.wal.OFuzzyCheckpointEndRecord{lsn=LSN{segment=0, position=1924570}} will be skipped during data restore [OLocalPaginatedStorage]
2017-05-01 10:49:34:468 INFO  {db=OSystem} Storage data recover was completed [OLocalPaginatedStorage]
2017-05-01 10:49:35:483 INFO  {db=OSystem} Previous maximum cache size was 780558 current maximum cache size is 167116. Cache state for storage /wm/orientdb-community-2.2.15-SNAPSHOT/databases/OSystem will not be restored. [O2QCache]
2017-05-01 10:49:46:978 WARNI {db=wmcloud_cpwsw} Storage 'wmcloud_cpwsw' was not closed properly. Will try to recover from write ahead log [OLocalPaginatedStorage]
2017-05-01 10:49:46:978 INFO  {db=wmcloud_cpwsw} Looking for last checkpoint... [OLocalPaginatedStorage]
2017-05-01 10:49:46:979 INFO  {db=wmcloud_cpwsw} Found FUZZY checkpoint. [OLocalPaginatedStorage]
2017-05-01 10:49:46:980 INFO  {db=wmcloud_cpwsw} Data restore procedure from FUZZY checkpoint is started. [OLocalPaginatedStorage]
2017-05-01 10:49:46:981 WARNI {db=wmcloud_cpwsw} Record com.orientechnologies.orient.core.storage.impl.local.paginated.wal.OFuzzyCheckpointEndRecord{lsn=LSN{segment=7037, position=25104138}} will be skipped during data restore [OLocalPaginatedStorage]
2017-05-01 10:49:46:981 INFO  {db=wmcloud_cpwsw} 1 operations were processed, current LSN is LSN{segment=7037, position=25104138} last LSN is LSN{segment=7037, position=25104191} [OLocalPaginatedStorage]
2017-05-01 10:49:46:982 WARNI {db=wmcloud_cpwsw} Record OFuzzyCheckpointStartRecord{lsn=LSN{segment=7037, position=25104145}} com.orientechnologies.orient.core.storage.impl.local.paginated.wal.OFuzzyCheckpointStartRecord{lsn=null, previousCheckpoint=LSN{segment=7037, position=25104098}} will be skipped during data restore [OLocalPaginatedStorage]
2017-05-01 10:49:46:983 WARNI {db=wmcloud_cpwsw} Record com.orientechnologies.orient.core.storage.impl.local.paginated.wal.OFuzzyCheckpointEndRecord{lsn=LSN{segment=7037, position=25104185}} will be skipped during data restore [OLocalPaginatedStorage]
2017-05-01 10:49:46:983 INFO  {db=wmcloud_cpwsw} Storage data recover was completed [OLocalPaginatedStorage]
2017-05-01 10:49:50:600 INFO  {db=wmcloud_cpwsw} Previous maximum cache size was 780558 current maximum cache size is 167116. Cache state for storage /wm/orientdb-community-2.2.15-SNAPSHOT/databases/wmcloud_cpwsw will not be restored.
```

**Comment by weixliu** [comment]
any information about this?

**Comment by laa** [comment]
@weixliu I do not think that it is related to the incorrect shutdown. You had NPE in direct memory allocator I do not think that any data page corruption may be related to direct memory allocator more likely you have got a bug in byte buffer which was fixed by commit https://github.com/orientechnologies/orientdb/commit/e7562eaab24ebfbebf10c2a819f660c3b584ac98 . I suppose that is just coincidence that you got it after a server crash. As you can see this fix is present in version since 2.2.17 . I suggest you update to latest version.  Actually, I suggest you wait till 2.2.20 version which we are going release today because it also contains very important memory leak fix and to run a server using this version. But do double check could you send me java command line parameters which you use in server script?

**Comment by laa** [comment]
Hi, @weixliu do you have any update on this issue?

**Comment by weixliu** [comment]
OK, Sorry don't get your early reply. I using 2.2.15 snapshot, I'll try the new release 2.2.18 to check whether it crashed.
Below it's my server script, I just change jvm memory & MaxDirectMemorySize, other I use default.
https://gist.github.com/weixliu/6fe10f3263091d93e406e1ecc8f63661

**Comment by weixliu** [comment]
@laa I think maybe you mean 2.2.18, not 2.2.20.

**Comment by laa** [comment]
Hi @weixliu , no I mean 2.2.20 it was released a couple of days ago and contains additional fixes of memory consumption. Very useful ones.

**Comment by weixliu** [comment]
OK, I found that in tag. Thank you, I'll try the new release.
