### ISSUE TITLE
 Invalid value of TX counter

### ISSUE THREAD

**Issue by careerscale** [orientechnologies/orientdb#7425]
## Expected behavior  
Transaction to work

## Actual behavior  
6:59:57.968 [http-nio-8084-exec-2] WARN - Unable to close graph {}
com.orientechnologies.orient.core.exception.OStorageException: Invalid value of TX counter
	DB name="mlm"
	at com.orientechnologies.orient.core.tx.OTransactionOptimistic.rollback(OTransactionOptimistic.java:129) ~[orientdb-core-3.0.0-SNAPSHOT.jar:3.0.0-SNAPSHOT]
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentAbstract.commit(ODatabaseDocumentAbstract.java:2609) ~[orientdb-core-3.0.0-SNAPSHOT.jar:3.0.0-SNAPSHOT]
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentAbstract.commit(ODatabaseDocumentAbstract.java:2565) ~[orientdb-core-3.0.0-SNAPSHOT.jar:3.0.0-SNAPSHOT]
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.commit(ODatabaseDocumentTx.java:885) ~[orientdb-core-3.0.0-SNAPSHOT.jar:3.0.0-SNAPSHOT]
	at com.tinkerpop.blueprints.impls.orient.OrientBaseGraph.shutdown(OrientBaseGraph.java:1164) ~[orientdb-graphdb-3.0.0-SNAPSHOT.jar:3.0.0-SNAPSHOT]
	at com.tinkerpop.blueprints.impls.orient.OrientBaseGraph.shutdown(OrientBaseGraph.java:1148) ~[orientdb-graphdb-3.0.0-SNAPSHOT.jar:3.0.0-SNAPSHOT]
	at com.tinkerpop.blueprints.impls.orient.OrientBaseGraph.shutdown(OrientBaseGraph.java:1141) ~[orientdb-graphdb-3.0.0-SNAPSHOT.jar:3.0.0-SNAPSHOT]
	at com.callidus.mlm.data.dao.impl.BaseDaoImpl.closeGraph(BaseDaoImpl.java:76) [classes/:?]
	at com.callidus.mlm.service.internal.MemberServiceImpl.saveMember(MemberServiceImpl.java:224) [classes/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_121]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_121]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_121]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_121]
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:333) [spring-aop-4.3.7.RELEASE.jar:4.3.7.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:190) [spring-aop-4.3.7.RELEASE.jar:4.3.7.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157) [spring-aop-4.3.7.RELEASE.jar:4.3.7.RELEASE]
	at org.springframework.aop.aspectj.MethodInvocationProceedingJoinPoint.proceed(MethodInvocationProceedingJoinPoint.java:85) [spring-aop-4.3.7.RELEASE.jar:4.3.7.RELEASE]
	at com.callidus.mlm.audit.ApplicationAuditor.serviceMethodExecutionTime(ApplicationAuditor.java:42) [classes/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_121]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_121]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_121]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_121]
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethodWithGivenArgs(AbstractAspectJAdvice.java:629) [spring-aop-4.3.7.RELEASE.jar:4.3.7.RELEASE]
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethod(AbstractAspectJAdvice.java:618) [spring-aop-4.3.7.RELEASE.jar:4.3.7.RELEASE]
	at org.springframework.aop.aspectj.AspectJAroundAdvice.invoke(AspectJAroundAdvice.java:70) [spring-aop-4.3.7.RELEASE.jar:4.3.7.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179) [spring-aop-4.3.7.RELEASE.jar:4.3.7.RELEASE]
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:92) [spring-aop-4.3.7.RELEASE.jar:4.3.7.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179) [spring-aop-4.3.7.RELEASE.jar:4.3.7.RELEASE]
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:213) [spring-aop-4.3.7.RELEASE.jar:4.3.7.RELEASE]
	at com.sun.proxy.$Proxy117.saveMember(Unknown Source) [?:?]
## Steps to reproduce  
I am not sure if I can provide exact steps to reproduce without sharing codebase which I cant do.

This exception is happening with fresh db schema and few operations.  here are the methods to create graph/database document

 @Override
    public OrientGraph getOrientGraph() {
        return getOrientGraph(false);

    }

    @Override
    public OrientGraph getOrientGraph(boolean isTransaction) {
        OrientGraph orientGraph = mlmOrientDbConfig.getOrientGraph();
        if (!isTransaction) {
            orientGraph.setAutoStartTx(isTransaction);
            orientGraph.begin();

        }
        return orientGraph;
    }

    @Override
    public ODatabaseDocument getDbDocument() {
        return getDbDocument(false);
    }

    @Override
    public ODatabaseDocument getDbDocument(boolean isTransaction) {
        return mlmOrientDbConfig.getODatabaseDocument();
    }

    @Override
    public void closeDatabase(ODatabaseDocument database) {
        try {
            if (database != null && database.isActiveOnCurrentThread() && !database.isClosed()) {

                database.close();
            }
        } catch (Exception e) {
            LOG.warn("Unable to close db connection {} ", e);
        }
    }

    @Override
    public void closeGraph(OrientGraph orientGraph) {
        if (orientGraph != null && !orientGraph.isClosed()) {
            try {
                orientGraph.shutdown();
            } catch (Exception e) {
                LOG.warn("Unable to close graph {}", e);
            }
        }
    }

We are using commit() on success and during exception rollback.

I am not sure why we are not able to get rid of this exception, it happens in few operations through app (UI).

**Comment by careerscale** [comment]
using orientdb-graphdb 3.0 snapshot, moving to gremlin in a day or so.

**Comment by tglman** [comment]
hi @careerscale,

Just reporting here what we said in the chat, the commit operation if it goes in error handle by itself the rollback, so is not needed to run the rollback in that case, hope it help to fix the problem.

Regards

**Comment by careerscale** [comment]
I will update you today/tomorrow, we are modifying all our code to use gremlin, earlier we use document api and graph api (TP 2.6).  if we can not hit this issue again for a week or so, may be we can close this issue. So I will keep you posted.

Having too many APIs is confusing, I think you should deprecate some of the APIs and let only 1 or 2 ways exist for the customers like me. More choices meaning more possible gaps in understanding or even the APIs  may not be in sync.

**Comment by lvca** [comment]
TP2.6 is for compatibility only, WDYT @tglman @santo-it to make this more clear in the download page and in the documentation?

**Comment by tglman** [comment]
hi @lvca,

Yes we are going to update that, in the documentation we refer to TinkerPop 2 as backward compatible [here](http://orientdb.com/docs/3.0.x/release/3.0/What-is-new-in-OrientDB-3.0.html#integration-with-apache-tinkerpop-2x), but we can make more clear that is deprecated

**Comment by careerscale** [comment]
Let us close this one. I dont think there is any open item here. But  https://github.com/orientechnologies/orientdb/issues/7444 is a open issue though. 
These 2 look related to me.
