### ISSUE TITLE
Not able to log to SysLog

### ISSUE THREAD

**Issue by nivedita-p** [orientechnologies/orientdb#7439]
## Expected behavior  
Log events to Syslog 

## Actual behavior  
java.lang.ClassNotFoundException: com.orientechnologies.security.syslog.ODefaultSyslog
        at java.net.URLClassLoader$1.run(URLClassLoader.java:359)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:348)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:347)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:312)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:195)
        at com.orientechnologies.orient.server.OServer.loadClass(OServer.java:217)
        at com.orientechnologies.orient.server.OServer.registerPlugins(OServer.java:1225)
        at com.orientechnologies.orient.server.OServer.activate(OServer.java:397)
        at com.orientechnologies.orient.server.OServerMain$1.run(OServerMain.java:46)

## Steps to reproduce  
I'm trying to send orientdb logs to syslog instead of ${ORIENTDB_HOME}/log/orientdb.log. I'm using community version. For this I added the following snippet In orientdb-server-config.xml as mentioned in https://orientdb.com/docs/2.2/SysLog-Plugin.html 

```
<handler class="com.orientechnologies.security.syslog.ODefaultSyslog">
    <parameters>
        <parameter name="enabled" value="true"/>
        <parameter name="debug" value="false"/>
        <parameter name="hostname" value="localhost"/>
        <parameter name="port" value="514"/>
        <parameter name="appName" value="OrientDB"/>
    </parameters>
</handler>

```

**Comment by maggiolo00** [comment]
Hi @nivedita-p 

The security plugin is not bundle with OrientDB community edition.

You should compile it from [here](https://github.com/orientechnologies/orientdb-security) by choosing the right tag

and place it under `$ORIENTDB_HOME/plugins`

**Comment by maggiolo00** [comment]
hi @nivedita-p 

were you able to install the security-plugin?

**Comment by nkbali** [comment]
I managed to build the jar and added it o my plugins directory. Configured the server config file but still nothing appears in my syslog.

Added to handlers section of the server config file.

</handler><handler class="com.orientechnologies.security.syslog.ODefaultSyslog">
    <parameters>
        <parameter name="enabled" value="true"/>
        <parameter name="debug" value="false"/>
        <parameter name="hostname" value="localhost"/>
        <parameter name="port" value="514"/>
        <parameter name="appName" value="jbossOrientDB"/>
    </parameters>
</handler>

I am using the community edition of orient db.
