### ISSUE TITLE
Vertex.value  java.lang.IllegalStateException: The property does not exist as the key has no associated value for the provided element

### ISSUE THREAD

**Issue by careerscale** [orientechnologies/orientdb#7455]
## Expected behavior  
either empty or null should be returned

## Actual behavior  
java.lang.IllegalStateException: The property does not exist as the key has no associated value for the provided element: v[#25:0]:test
	at org.apache.tinkerpop.gremlin.structure.Property$Exceptions.propertyDoesNotExist(Property.java:155)
	at org.apache.tinkerpop.gremlin.structure.Element.lambda$value$1(Element.java:94)
	at org.apache.tinkerpop.gremlin.structure.Property.orElseThrow(Property.java:101)
	at org.apache.tinkerpop.gremlin.structure.Element.value(Element.java:94)
	at com.orientdb.samples.test.GraphApiIdBugTp3Test.lambda$1(GraphApiIdBugTp3Test.java:110)
	at com.orientechnologies.orient.core.sql.executor.OResultSet$2.tryAdvance(OResultSet.java:125)
	at java.util.Spliterator.forEachRemaining(Spliterator.java:326)
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580)
	at com.orientdb.samples.test.GraphApiIdBugTp3Test.testBugForUnknownProperty(GraphApiIdBugTp3Test.java:105)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)

## Steps to reproduce  
https://github.com/careerscale/orientdb-demo/blob/master/orientdb-java-sample/src/test/java/com/orientdb/samples/test/GraphApiIdBugTp3Test.java

run testBugForUnknownProperty() method or  similar method can be written

**Comment by G4br13l3** [comment]
Hi careerscale,
thanks for your test case, your contribute is really important to us in order to improve the next 3.0. We are going to reproduce the issue and investigate. 
Meanwhile can you give us some more info about your system environment please?
We will let you know as soon as possible.
Your contribute is really important to us in order to improve the next 3.0.  

Thanks. 

Gabriele

**Comment by careerscale** [comment]
run the schema first https://github.com/careerscale/orientdb-demo/blob/master/orientdb-java-sample/src/test/resources/test.sql

then running the test will fail the test with exception.   Please let me know if you need any specific informaton

**Comment by careerscale** [comment]
@G4br13l3 
When I wrote in memory test, it worked fine, but with remote it failed,  I think this bug goes into gremlin and not in orientdb. I am not sure. please suggest.

https://github.com/careerscale/orientdb-demo/blob/master/orientdb-java-sample/src/test/java/com/orientdb/samples/test/TransactionalTestsOrientGraph3InMemory.java

**Comment by G4br13l3** [comment]
Thanks for all the details @careerscale, we'll investigate your user case.

**Comment by maggiolo00** [comment]
Hi @careerscale 

the default implementation of `value(String key)` of TP3 throws `NoSuchElementException`

You should use `property(String key)` API and  use the returned  `Property` in order to check if it's 
present or not.

**Comment by careerscale** [comment]
Thanks @maggiolo00 , I didn't realize about TP3 definitions. btw for the in memory  orientdb i didnt see this exception, any reason for it.

**Comment by maggiolo00** [comment]
@careerscale 
with this test does not fail `TransactionalTestsOrientGraph3InMemory.java` ?

**Comment by careerscale** [comment]
yes, I thought the following test should fail from `TransactionalTestsOrientGraph3InMemory.java `.  

I am using "value" for random name as property and it still works.

`    @Test
    public void testBugForUnknownProperty() {

        OrientGraph graph = factory.getTx();;
        graph.addVertex(CLASS_PREFIX + USER, createProperties());

        graph.commit();
        graph.close();

        graph = factory.getTx();
        OResultSet vertices = graph.executeSql("select from User");


        vertices.vertexStream().forEach(v -> {
            // this works
            String someProperty = v.getProperty("name");

            OrientGraph graph1 = factory.getTx();
            graph1.vertices(v.getRecord().getIdentity()).next().value("test");
            graph1.close();
            // graph.vertices(v.)

        });

        graph.close();
    }`

**Comment by maggiolo00** [comment]
Hi @careerscale 

it does not fail because it's not entering the forEach because there are no records in class `User`. You use this code to create vertex 

```
graph.addVertex(CLASS_PREFIX + USER, createProperties());
```

but the syntax with "class:" was for TP2 that didn't support label.

In TP3 you should use it in this way

```
graph.addVertex(T.label,USER, NAME,"first +  last" + new Random().nextDouble());
```

**Comment by careerscale** [comment]
that is my bad, thanks for pointing it out.

**Comment by careerscale** [comment]
Ok, modified  this a bit, now I run into this exception, what does this mean? I think making the db active etc are required for document model but not for TP3 graph right (being done internally).

com.orientechnologies.orient.core.exception.ODatabaseException: The database instance is not set in the current thread. Be sure to set it with: ODatabaseRecordThreadLocal.INSTANCE.set(db);
	at com.orientechnologies.orient.core.db.ODatabaseRecordThreadLocal.get(ODatabaseRecordThreadLocal.java:51)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentAbstract.checkIfActive(ODatabaseDocumentAbstract.java:2949)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentAbstract.getClusterNameById(ODatabaseDocumentAbstract.java:907)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentAbstract.countClusterElements(ODatabaseDocumentAbstract.java:371)
	at com.orientechnologies.orient.core.iterator.ORecordIteratorCluster.<init>(ORecordIteratorCluster.java:73)
	at com.orientechnologies.orient.core.iterator.ORecordIteratorCluster.<init>(ORecordIteratorCluster.java:40)
	at com.orientechnologies.orient.core.sql.executor.FetchFromClusterExecutionStep.syncPull(FetchFromClusterExecutionStep.java:37)
	at com.orientechnologies.orient.core.sql.executor.FetchFromClassExecutionStep$1.hasNext(FetchFromClassExecutionStep.java:104)
	at com.orientechnologies.orient.core.sql.parser.OLocalResultSet.hasNext(OLocalResultSet.java:39)
	at com.orientechnologies.orient.core.sql.parser.OLocalResultSetLifecycleDecorator.hasNext(OLocalResultSetLifecycleDecorator.java:43)
	at com.orientechnologies.orient.core.sql.executor.OResultSet$2.tryAdvance(OResultSet.java:122)
	at java.util.Spliterator.forEachRemaining(Spliterator.java:326)
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580)
	at com.orientdb.samples.test.TransactionalTestsOrientGraph3InMemory.testBugForUnknownProperty(TransactionalTestsOrientGraph3InMemory.java:107)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)

**Comment by maggiolo00** [comment]
HI @careerscale  
i think the problem is that you are getting another graph in the forEach
If you use the same instance it should be fine. I think we will need to change
the executeSQL in order to return a result set of  OrientVertex/OrientEdge instead of the underlying 
implementation of OrientDB so you will not need to do that.

**Comment by careerscale** [comment]
@maggiolo00 , is there going to be a fix or should we close this ticket?

**Comment by maggiolo00** [comment]
Hi @careerscale 

i'm going to implement a new ResultSet that works on OrientVertex/OrientEdge

I've opened an issue here to track the implementation

https://github.com/orientechnologies/orientdb-gremlin/issues/130
