### ISSUE TITLE
java.lang.ClassCastException: com.orientechnologies.orient.core.db.record.ORecordLazyList cannot be cast to com.orientechnologies.orient.core.db.record.ridbag.ORidBag

### ISSUE THREAD

**Issue by tommasop** [orientechnologies/orientdb#7472]
## Expected behavior  

These query must work:

UPDATE EDGE LayerEntities SET out = #29:243 WHERE in = #35:65 AND out <> #29:243

## Actual behavior  

The query returns the following error:

**java.lang.ClassCastException: com.orientechnologies.orient.core.db.record.ORecordLazyList cannot be cast to com.orientechnologies.orient.core.db.record.ridbag.ORidBag**

## Database Record Level Security

We have Drawing -DrawingLayers-> Layer -LayerEntities-> Entity.
The Drawing and Layer classes inherits from ORestricted and the OUser has _allow on every Drawing and Layer record.
The Entity class has no database record level security.
We are basically moving an Entity from one Layer to another.

**Comment by luigidellaquila** [comment]
Hi @tommasop 

Do you have a full stack trace for this problem?

Thanks

Luigi

**Comment by tommasop** [comment]
Here it is, I narrowed it down to the following query:

UPDATE EDGE LayerEntities SET out = #29:243 WHERE in = #35:65 AND out <> #29:243

```
2017-06-06 13:21:07:933 INFO  {db=ucad_demo} Storage data recover was completed [OLocalPaginatedStorage]
2017-06-06 13:21:08:011 WARNI {db=ucad_demo} Cannot restore state of cache for storage placed under /orientdb/databases/ucad_demo [O2QCache]
2017-06-06 13:21:08:016 FINE  {db=ucad_demo} Read record #0:1 v.243 size=34659 bytes (thread=23 tx=false) [OLocalPaginatedStorage]
2017-06-06 13:21:08:065 FINE  {db=ucad_demo} Read record #0:2 v.46 size=15537 bytes (thread=23 tx=false) [OLocalPaginatedStorage]
2017-06-06 13:21:08:121 FINE  {db=ucad_demo} Read record #5:3 v.3441 size=175 bytes (thread=23 tx=false) [OLocalPaginatedStorage]
2017-06-06 13:21:08:145 FINE  {db=ucad_demo} Read record #4:9 v.1156 size=60 bytes (thread=23 tx=false) [OLocalPaginatedStorage]
2017-06-06 13:21:08:148 FINE  {db=ucad_demo} Read record #4:0 v.2 size=69 bytes (thread=23 tx=false) [OLocalPaginatedStorage]
2017-06-06 13:21:08:726 FINE  {db=ucad_demo} Read record #5:3 v.3441 size=175 bytes (thread=23 tx=false) [OLocalPaginatedStorage]
2017-06-06 13:21:08:728 FINE  {db=ucad_demo} Read record #4:9 v.1156 size=60 bytes (thread=23 tx=false) [OLocalPaginatedStorage]
2017-06-06 13:21:08:729 FINE  {db=ucad_demo} Read record #4:0 v.2 size=69 bytes (thread=23 tx=false) [OLocalPaginatedStorage]
2017-06-06 13:21:08:755 FINE  {db=ucad_demo} Read record #43:65 v.1 size=32 bytes (thread=23 tx=false) [OLocalPaginatedStorage]
2017-06-06 13:21:08:762 FINE  {db=ucad_demo} Read record #29:243 v.10 size=268 bytes (thread=23 tx=false) [OLocalPaginatedStorage]
2017-06-06 13:21:08:764 FINE  {db=ucad_demo} Read record #35:65 v.9 size=537 bytes (thread=23 tx=false) [OLocalPaginatedStorage]
2017-06-06 13:21:08:765 FINE  {db=ucad_demo} Read record #29:242 v.20 size=285 bytes (thread=23 tx=false) [OLocalPaginatedStorage]Caught exception
com.orientechnologies.orient.core.exception.OCommandExecutionException: Error on execution of command: sql.select from LayerEntities WHERE in = #35:65 AND out <> #29:243
	DB name="ucad_demo"
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.executeCommand(OAbstractPaginatedStorage.java:2599)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.command(OAbstractPaginatedStorage.java:2524)
	at com.orientechnologies.orient.core.sql.query.OSQLQuery.run(OSQLQuery.java:78)
	at com.orientechnologies.orient.core.sql.query.OSQLAsynchQuery.run(OSQLAsynchQuery.java:74)
	at com.orientechnologies.orient.core.query.OQueryAbstract.execute(OQueryAbstract.java:33)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.query(ODatabaseDocumentTx.java:750)
	at com.orientechnologies.orient.core.sql.OCommandExecutorSQLUpdate.execute(OCommandExecutorSQLUpdate.java:292)
	at com.orientechnologies.orient.core.sql.OCommandExecutorSQLDelegate.execute(OCommandExecutorSQLDelegate.java:74)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.executeCommand(OAbstractPaginatedStorage.java:2578)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.command(OAbstractPaginatedStorage.java:2524)
	at com.orientechnologies.orient.core.command.OCommandRequestTextAbstract.execute(OCommandRequestTextAbstract.java:69)
	at com.orientechnologies.orient.server.network.protocol.http.command.post.OServerCommandPostCommand.execute(OServerCommandPostCommand.java:106)
	at com.orientechnologies.orient.graph.server.command.OServerCommandPostCommandGraph.execute(OServerCommandPostCommandGraph.java:37)
	at com.orientechnologies.orient.server.network.protocol.http.ONetworkProtocolHttpAbstract.service(ONetworkProtocolHttpAbstract.java:169)
	at com.orientechnologies.orient.server.network.protocol.http.ONetworkProtocolHttpAbstract.execute(ONetworkProtocolHttpAbstract.java:621)
	at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:77)
Caused by: java.lang.ClassCastException: com.orientechnologies.orient.core.db.record.ORecordLazyList cannot be cast to com.orientechnologies.orient.core.db.record.ridbag.ORidBag
	at com.orientechnologies.orient.core.sql.OCommandExecutorSQLUpdate.changeVertexEdgePointer(OCommandExecutorSQLUpdate.java:425)
	at com.orientechnologies.orient.core.sql.OCommandExecutorSQLUpdate.handleUpdateEdge(OCommandExecutorSQLUpdate.java:406)
	at com.orientechnologies.orient.core.sql.OCommandExecutorSQLUpdate.result(OCommandExecutorSQLUpdate.java:356)
	at com.orientechnologies.orient.core.sql.OCommandExecutorSQLResultsetAbstract.pushResult(OCommandExecutorSQLResultsetAbstract.java:285)
	at com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.addResult(OCommandExecutorSQLSelect.java:737)
	at com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.handleResult(OCommandExecutorSQLSelect.java:669)
	at com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.executeSearchRecord(OCommandExecutorSQLSelect.java:626)
	at com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.serialIterator(OCommandExecutorSQLSelect.java:1615)
	at com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.fetchFromTarget(OCommandExecutorSQLSelect.java:1562)
	at com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.fetchValuesFromIndexCursor(OCommandExecutorSQLSelect.java:2447)
	at com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.searchForIndexes(OCommandExecutorSQLSelect.java:2262)
	at com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.searchInClasses(OCommandExecutorSQLSelect.java:997)
	at com.orientechnologies.orient.core.sql.OCommandExecutorSQLResultsetAbstract.assignTarget(OCommandExecutorSQLResultsetAbstract.java:209)
	at com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.assignTarget(OCommandExecutorSQLSelect.java:526)
	at com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.executeSearch(OCommandExecutorSQLSelect.java:508)
	at com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.execute(OCommandExecutorSQLSelect.java:484)
	at com.orientechnologies.orient.core.sql.OCommandExecutorSQLDelegate.execute(OCommandExecutorSQLDelegate.java:74)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.executeCommand(OAbstractPaginatedStorage.java:2578)
	... 15 more
Internal server error:

java.lang.ClassCastException: com.orientechnologies.orient.core.db.record.ORecordLazyList cannot be cast to com.orientechnologies.orient.core.db.record.ridbag.ORidBag
	at com.orientechnologies.orient.core.sql.OCommandExecutorSQLUpdate.changeVertexEdgePointer(OCommandExecutorSQLUpdate.java:425)
	at com.orientechnologies.orient.core.sql.OCommandExecutorSQLUpdate.handleUpdateEdge(OCommandExecutorSQLUpdate.java:406)
	at com.orientechnologies.orient.core.sql.OCommandExecutorSQLUpdate.result(OCommandExecutorSQLUpdate.java:356)
	at com.orientechnologies.orient.core.sql.OCommandExecutorSQLResultsetAbstract.pushResult(OCommandExecutorSQLResultsetAbstract.java:285)
	at com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.addResult(OCommandExecutorSQLSelect.java:737)
	at com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.handleResult(OCommandExecutorSQLSelect.java:669)
	at com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.executeSearchRecord(OCommandExecutorSQLSelect.java:626)
	at com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.serialIterator(OCommandExecutorSQLSelect.java:1615)
	at com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.fetchFromTarget(OCommandExecutorSQLSelect.java:1562)
	at com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.fetchValuesFromIndexCursor(OCommandExecutorSQLSelect.java:2447)
	at com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.searchForIndexes(OCommandExecutorSQLSelect.java:2262)
	at com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.searchInClasses(OCommandExecutorSQLSelect.java:997)
	at com.orientechnologies.orient.core.sql.OCommandExecutorSQLResultsetAbstract.assignTarget(OCommandExecutorSQLResultsetAbstract.java:209)
	at com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.assignTarget(OCommandExecutorSQLSelect.java:526)
	at com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.executeSearch(OCommandExecutorSQLSelect.java:508)
	at com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.execute(OCommandExecutorSQLSelect.java:484)
	at com.orientechnologies.orient.core.sql.OCommandExecutorSQLDelegate.execute(OCommandExecutorSQLDelegate.java:74)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.executeCommand(OAbstractPaginatedStorage.java:2578)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.command(OAbstractPaginatedStorage.java:2524)
	at com.orientechnologies.orient.core.sql.query.OSQLQuery.run(OSQLQuery.java:78)
	at com.orientechnologies.orient.core.sql.query.OSQLAsynchQuery.run(OSQLAsynchQuery.java:74)
	at com.orientechnologies.orient.core.query.OQueryAbstract.execute(OQueryAbstract.java:33)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.query(ODatabaseDocumentTx.java:750)
	at com.orientechnologies.orient.core.sql.OCommandExecutorSQLUpdate.execute(OCommandExecutorSQLUpdate.java:292)
	at com.orientechnologies.orient.core.sql.OCommandExecutorSQLDelegate.execute(OCommandExecutorSQLDelegate.java:74)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.executeCommand(OAbstractPaginatedStorage.java:2578)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.command(OAbstractPaginatedStorage.java:2524)
	at com.orientechnologies.orient.core.command.OCommandRequestTextAbstract.execute(OCommandRequestTextAbstract.java:69)
	at com.orientechnologies.orient.server.network.protocol.http.command.post.OServerCommandPostCommand.execute(OServerCommandPostCommand.java:106)
	at com.orientechnologies.orient.graph.server.command.OServerCommandPostCommandGraph.execute(OServerCommandPostCommandGraph.java:37)
	at com.orientechnologies.orient.server.network.protocol.http.ONetworkProtocolHttpAbstract.service(ONetworkProtocolHttpAbstract.java:169)
	at com.orientechnologies.orient.server.network.protocol.http.ONetworkProtocolHttpAbstract.execute(ONetworkProtocolHttpAbstract.java:621)
	at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:77)
```

**Comment by luigidellaquila** [comment]
Hi @tommasop 

Thank you very much, the fix should not be too hard to do. I'll give you a feedback soon

Thanks

Luigi

**Comment by luigidellaquila** [comment]
Hi @tommasop 

I just pushed a fix on 2.2.x branch, could you please try it and let me know if the problem is solved?

Thanks

Luigi

**Comment by tommasop** [comment]
Will try asap and get back to you thanks a lot!

**Comment by tommasop** [comment]
I confirm the patch solves the issue, thanks a lot for the quick fix!

**Comment by luigidellaquila** [comment]
Hi @tommasop 

Did you have a chance to test it?
I'm closing this issue, please feel free to reopen if you need further help

Thanks

Luigi
