### ISSUE TITLE
Classes extended from both Vertex (V) and Edge (E) should work properly.

### ISSUE THREAD

**Issue by zhuj** [orientechnologies/orientdb#7487]
## Expected behavior  

Documents of classes which extend both Vertex (V) and Edge (E) should work properly.
Or (at least) there should be an explicit check in API to prevent doing that.

## Actual behavior  

NullPointerException is thrown in the «GRAPH» page in the *OrientDB Studio* for the query "select from V":
```
java.lang.NullPointerException
	at com.orientechnologies.orient.server.network.protocol.http.OHttpGraphResponse.writeRecords(OHttpGraphResponse.java:139)
	at com.orientechnologies.orient.server.network.protocol.http.OHttpResponse.writeResult(OHttpResponse.java:230)
	at com.orientechnologies.orient.server.network.protocol.http.command.post.OServerCommandPostCommand.execute(OServerCommandPostCommand.java:114)
	at com.orientechnologies.orient.server.network.protocol.http.command.post.OServerCommandPostCommandGraph.execute(OServerCommandPostCommandGraph.java:36)
	at com.orientechnologies.orient.server.network.protocol.http.ONetworkProtocolHttpAbstract.service(ONetworkProtocolHttpAbstract.java:168)
	at com.orientechnologies.orient.server.network.protocol.http.ONetworkProtocolHttpAbstract.execute(ONetworkProtocolHttpAbstract.java:625)
	at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:77)

```

## Steps to reproduce  

API allows to create a class which is a subclass of both Vertex (V) and Edge (E). There is no error on this stage.

```
package org.mentha.utils.archimate.orientdb

import com.orientechnologies.orient.server.OServer
import com.orientechnologies.orient.server.OServerMain
import com.orientechnologies.orient.core.db.document.ODatabaseDocument
import com.orientechnologies.orient.core.db._
import com.orientechnologies.orient.core.metadata.schema._
import com.orientechnologies.orient.core.record._
import com.orientechnologies.orient.core.record.impl._

object Test {

  val config: OrientDBConfig = new OrientDBConfigBuilder().build()

  val server: OServer = OServerMain.create.startup.activate
  server.createDatabase("archimate", ODatabaseType.MEMORY, config)
  
  val odb: OrientDB = new OrientDB("remote:localhost", config)
  val session: ODatabaseDocument = odb.open("archimate", "root", "root")

  val schema: OSchema = {
    val s = session.getMetadata.getSchema
    s.reload()
    s
  }

  val E = schema.getClass(OClass.EDGE_CLASS_NAME)
  val V = schema.getClass(OClass.VERTEX_CLASS_NAME)

  val modelClass = schema.getOrCreateClass("Model", V)

  val aspectClass = schema.getOrCreateClass("Aspect", V)
  aspectClass.createProperty("model", OType.LINK, modelClass).setMandatory(true)

  val elementClass = schema.getOrCreateClass("Element", aspectClass)

  val relationshipClass = schema.getOrCreateClass("Relationship", aspectClass, E) // HERE IT IS: I'm able to create a class which extends both Vertex and Edge, and nobody warns me....
  relationshipClass.createProperty(OEdge.DIRECITON_OUT, OType.LINK, aspectClass).setMandatory(true)
  relationshipClass.createProperty(OEdge.DIRECITON_IN, OType.LINK, aspectClass).setMandatory(true)

  private def newRelationship(out: ODocument, in: ODocument)(relClass: OClass)(model: ODocument): ODocument = {
    // if the magic above is possible, then I want to have the method com.orientechnologies.orient.core.db.document.ODatabaseDocumentAbstract#getConnectionFieldName being public (and located next to OVertexDelegate#createLink) 
    def getConnectionFieldName(dir: ODirection, edgeClass: OClass): String = {
      val prefix = if (ODirection.OUT == dir) { "out_" } else { "in_" }
      if (edgeClass.getName == "E") { prefix } else { prefix + edgeClass.getName }
    }

    val outFieldName = getConnectionFieldName(ODirection.OUT, relClass)
    val inFieldName = getConnectionFieldName(ODirection.IN, relClass)

    val ei = session.newInstance(relClass.getName).asInstanceOf[ODocument]
    ei.field("model", model)
    ei.setProperty("model", model)
    ei.setProperty(OEdge.DIRECITON_OUT, out)
    ei.setProperty(OEdge.DIRECITON_IN, in)

    OVertexDelegate.createLink(out, ei, outFieldName)
    OVertexDelegate.createLink(in, ei, inFieldName)
    ei
  }


  def main(args: Array[String]): Unit = {

    val model = session.newInstance(modelClass.getName).asInstanceOf[ODocument]
    model.save()

    val v1 = session.newInstance(elementClass.getName).asInstanceOf[ODocument]

    v1.setProperty("model", model)
    v1.save()

    val v2 = session.newInstance(elementClass.getName).asInstanceOf[ODocument]
    v2.setProperty("model", model)
    v2.save()

    val e1 = newRelationship(v1, v2)(relationshipClass)(model)
    e1.save()

    val e2 = newRelationship(v2, v1)(relationshipClass)(model)
    e2.save()

//    that is the aim of such a complex inheritance: to be able to make a relationship (an edge) between either vertexes and edges
//    val xx = newRelationship(e1, e2)(relationshipClass)(model)
//    xx.save()

  }
}
```

## Fix suggestion

The reason is in [OEdgeIterator.java#91](https://github.com/orientechnologies/orientdb/blob/develop/core/src/main/java/com/orientechnologies/orient/core/record/impl/OEdgeIterator.java#L91) - it creates fake edges with no real element inside, which will cause NPE.

Due to the contract of com.orientechnologies.orient.core.record.OElement#getPropertyNames it should not return nulls, also all usages of this method are null-pointer-unsafe (for in record.getPropertyNames). 

The suggestion is to return `Collections.emptySet()` instead of `null` in [OEdgeDelegate.java#getPropertyNames](https://github.com/orientechnologies/orientdb/blob/develop/core/src/main/java/com/orientechnologies/orient/core/record/impl/OEdgeDelegate.java#L115).

**Comment by tglman** [comment]
hi @zhuj,

Yes we have a problem on the validation of class creation, you should not be allowed to create a class that is an edge and a vertex.

Regards
