### ISSUE TITLE
NPE in ODocument.containsField(...)

### ISSUE THREAD

**Issue by PhantomYdn** [orientechnologies/orientdb#7498]
### OS: any

There is the following exception happening in our code:

```java
Caused by: java.lang.NullPointerException
        at com.orientechnologies.orient.core.record.impl.ODocument.containsField(ODocument.java:1366)
        at org.orienteer.core.hook.CallbackHook.onTrigger(CallbackHook.java:101)
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.callbackHooks(ODatabaseDocumentTx.java:1139)
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.executeReadRecord(ODatabaseDocumentTx.java:2035)
```

According to code: extra check of `_fields` seems needed. Also I noticed, that not all methods contains safe use of _fields.

**Comment by tglman** [comment]
hi @PhantomYdn,

This is quite strange, the filed `_fields` that seems missing from `https://github.com/orientechnologies/orientdb/blob/2.2.x/core/src/main/java/com/orientechnologies/orient/core/record/impl/ODocument.java#L1366` is initialized by the call one line before (1365) that call this method:https://github.com/orientechnologies/orientdb/blob/2.2.x/core/src/main/java/com/orientechnologies/orient/core/record/impl/ODocument.java#L2617 so looking at the code seems impossible to happen if not in multithread, and the ODocument is not designed to support multiple threads.

Bye

**Comment by PhantomYdn** [comment]
I think you are right. It happened on OUser document wrapper. And my perception was there is nothing to do in app code - that instance was stored and reused in parallel within OrientDB. Checking one more time what can be done.
