### ISSUE TITLE
OrientDB 3.0 -0621/0622builds OSerializationException: Cannot read transaction record from the network. Transaction aborted (because of NPE)

### ISSUE THREAD

**Issue by careerscale** [orientechnologies/orientdb#7510]
## Expected behavior  
My application should work as it was working before.  we are using remote for db (**remote:localhost/test**)

## Actual behavior  

```
Caused by: com.orientechnologies.orient.core.exception.OSerializationException: Cannot read transaction record from the network. Transaction aborted
	DB name="test"
	DB name="test"
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_121]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_121]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_121]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_121]
	at com.orientechnologies.orient.client.binary.OChannelBinaryAsynchClient.throwSerializedException(OChannelBinaryAsynchClient.java:323) ~[orientdb-client-3.0.0-SNAPSHOT.jar:3.0.0-SNAPSHOT]
	at com.orientechnologies.orient.client.binary.OChannelBinaryAsynchClient.handleStatus(OChannelBinaryAsynchClient.java:280) ~[orientdb-client-3.0.0-SNAPSHOT.jar:3.0.0-SNAPSHOT]
	at com.orientechnologies.orient.client.binary.OChannelBinaryAsynchClient.beginResponse(OChannelBinaryAsynchClient.java:195) ~[orientdb-client-3.0.0-SNAPSHOT.jar:3.0.0-SNAPSHOT]
	at com.orientechnologies.orient.client.binary.OChannelBinaryAsynchClient.beginResponse(OChannelBinaryAsynchClient.java:159) ~[orientdb-client-3.0.0-SNAPSHOT.jar:3.0.0-SNAPSHOT]
	at com.orientechnologies.orient.client.remote.OStorageRemote.beginResponse(OStorageRemote.java:1658) ~[orientdb-client-3.0.0-SNAPSHOT.jar:3.0.0-SNAPSHOT]
	at com.orientechnologies.orient.client.remote.OStorageRemote$2.execute(OStorageRemote.java:224) ~[orientdb-client-3.0.0-SNAPSHOT.jar:3.0.0-SNAPSHOT]
	at com.orientechnologies.orient.client.remote.OStorageRemote$2.execute(OStorageRemote.java:210) ~[orientdb-client-3.0.0-SNAPSHOT.jar:3.0.0-SNAPSHOT]
	at com.orientechnologies.orient.client.remote.OStorageRemote.baseNetworkOperation(OStorageRemote.java:274) ~[orientdb-client-3.0.0-SNAPSHOT.jar:3.0.0-SNAPSHOT]
	at com.orientechnologies.orient.client.remote.OStorageRemote.networkOperationRetryTimeout(OStorageRemote.java:210) ~[orientdb-client-3.0.0-SNAPSHOT.jar:3.0.0-SNAPSHOT]
	at com.orientechnologies.orient.client.remote.OStorageRemote.networkOperation(OStorageRemote.java:238) ~[orientdb-client-3.0.0-SNAPSHOT.jar:3.0.0-SNAPSHOT]
	at com.orientechnologies.orient.client.remote.OStorageRemote.commit(OStorageRemote.java:890) ~[orientdb-client-3.0.0-SNAPSHOT.jar:3.0.0-SNAPSHOT]
	at com.orientechnologies.orient.core.tx.OTransactionOptimistic.doCommit(OTransactionOptimistic.java:545) ~[orientdb-core-3.0.0-SNAPSHOT.jar:3.0.0-SNAPSHOT]
	at com.orientechnologies.orient.core.tx.OTransactionOptimistic.commit(OTransactionOptimistic.java:110) ~[orientdb-core-3.0.0-SNAPSHOT.jar:3.0.0-SNAPSHOT]
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentAbstract.commit(ODatabaseDocumentAbstract.java:2584) ~[orientdb-core-3.0.0-SNAPSHOT.jar:3.0.0-SNAPSHOT]
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentAbstract.commit(ODatabaseDocumentAbstract.java:2553) ~[orientdb-core-3.0.0-SNAPSHOT.jar:3.0.0-SNAPSHOT]
	at org.apache.tinkerpop.gremlin.orientdb.OrientGraph.commit(OrientGraph.java:527) ~[orientdb-gremlin-3.0.0-SNAPSHOT.jar:3.0.0-SNAPSHOT]
	at com.callidus.mlm.service.internal.AbstractBaseService.commit(AbstractBaseService.java:52) ~[classes/:?]
	at com.callidus.mlm.service.internal.CompanyServiceImpl.createCompany(CompanyServiceImpl.java:59) ~[classes/:?]
	... 64 more
	Suppressed: com.orientechnologies.orient.core.exception.OSerializationException: Cannot read transaction record from the network. Transaction aborted
	DB name="test"
		at com.orientechnologies.orient.server.tx.OTransactionOptimisticServer.begin(OTransactionOptimisticServer.java:191) ~[?:?]
		at com.orientechnologies.orient.core.db.document.ODatabaseDocumentAbstract.rawBegin(ODatabaseDocumentAbstract.java:1369) ~[orientdb-core-3.0.0-SNAPSHOT.jar:3.0.0-SNAPSHOT]
		at com.orientechnologies.orient.server.OConnectionBinaryExecutor.executeCommit37(OConnectionBinaryExecutor.java:1226) ~[?:?]
		at com.orientechnologies.orient.client.remote.message.OCommit37Request.execute(OCommit37Request.java:124) ~[orientdb-client-3.0.0-SNAPSHOT.jar:3.0.0-SNAPSHOT]
		at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.sessionRequest(ONetworkProtocolBinary.java:258) ~[?:?]
		at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.execute(ONetworkProtocolBinary.java:180) ~[?:?]
		at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:77) ~[orientdb-core-3.0.0-SNAPSHOT.jar:3.0.0-SNAPSHOT]
	Caused by: java.lang.NullPointerException
		at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerNetworkV37.readRidBag(ORecordSerializerNetworkV37.java:388) ~[orientdb-core-3.0.0-SNAPSHOT.jar:3.0.0-SNAPSHOT]
		at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerNetworkV37.deserializeValue(ORecordSerializerNetworkV37.java:304) ~[orientdb-core-3.0.0-SNAPSHOT.jar:3.0.0-SNAPSHOT]
		at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerNetworkV37.deserialize(ORecordSerializerNetworkV37.java:121) ~[orientdb-core-3.0.0-SNAPSHOT.jar:3.0.0-SNAPSHOT]
		at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerNetworkV37.fromStream(ORecordSerializerNetworkV37.java:843) ~[orientdb-core-3.0.0-SNAPSHOT.jar:3.0.0-SNAPSHOT]
		at com.orientechnologies.orient.server.tx.OTransactionOptimisticServer.begin(OTransactionOptimisticServer.java:70) ~[?:?]
		... 6 more
Caused by: java.lang.NullPointerException
	at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerNetworkV37.readRidBag(ORecordSerializerNetworkV37.java:388) ~[orientdb-core-3.0.0-SNAPSHOT.jar:3.0.0-SNAPSHOT]
	at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerNetworkV37.deserializeValue(ORecordSerializerNetworkV37.java:304) ~[orientdb-core-3.0.0-SNAPSHOT.jar:3.0.0-SNAPSHOT]
	at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerNetworkV37.deserialize(ORecordSerializerNetworkV37.java:121) ~[orientdb-core-3.0.0-SNAPSHOT.jar:3.0.0-SNAPSHOT]
	at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerNetworkV37.fromStream(ORecordSerializerNetworkV37.java:843) ~[orientdb-core-3.0.0-SNAPSHOT.jar:3.0.0-SNAPSHOT]
	at com.orientechnologies.orient.server.tx.OTransactionOptimisticServer.begin(OTransactionOptimisticServer.java:70) ~[?:?]
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentAbstract.rawBegin(ODatabaseDocumentAbstract.java:1369) ~[orientdb-core-3.0.0-SNAPSHOT.jar:3.0.0-SNAPSHOT]
	at com.orientechnologies.orient.server.OConnectionBinaryExecutor.executeCommit37(OConnectionBinaryExecutor.java:1226) ~[?:?]
	at com.orientechnologies.orient.client.remote.message.OCommit37Request.execute(OCommit37Request.java:124) ~[orientdb-client-3.0.0-SNAPSHOT.jar:3.0.0-SNAPSHOT]
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.sessionRequest(ONetworkProtocolBinary.java:258) ~[?:?]
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.execute(ONetworkProtocolBinary.java:180) ~[?:?]
	at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:77) ~[orientdb-core-3.0.0-SNAPSHOT.jar:3.0.0-SNAPSHOT]


```## Steps to reproduce  
<add here>

**Comment by careerscale** [comment]
sorry closed by mistake. re-opened again

**Comment by careerscale** [comment]
@luigidellaquila  do we know if this is a known issue or something to be fixed?

**Comment by luigidellaquila** [comment]
Hi @careerscale 

AFAIK it's not a known issue, I'm assigning it to @tglman for a check.

Thanks

Luigi

**Comment by careerscale** [comment]
@luigidellaquila , thank you

**Comment by tglman** [comment]
hi @careerscale,

I fixed similar issue recently but I cannot bet that are exactly the same of this, do you have a simple test case for this case ? 

Regards

**Comment by careerscale** [comment]
tried my old unit tests, they seem to be OK. 

But this error is the first one that comes for me in my application while creating base entity and so cannot do anything else. kind of blocker for the application.

Let me see If i can write new unit test for it.

**Comment by careerscale** [comment]
@tglman , our application breaks and never able to make it fixed with latest orientdb libraries and db. 
so we are using bit older version (few days older) but I think I will come back again to reproduce it.

**Comment by tglman** [comment]
hi @careerscale,

I've been wondering a bit a about this error, and I think "I guessed" the problem, so now I'm writing a test that prove my guessing and in case i've already the fix for the problem.

Regard

**Comment by careerscale** [comment]
I think I don't see this issue any more. trying to test my pending issues with 06/28 build
