### ISSUE TITLE
NPE during database upgrade

### ISSUE THREAD

**Issue by PhantomYdn** [orientechnologies/orientdb#7512]
### OS: linux 

We had db which run on 2.1.19. But now we tried to run it on instance of Orienteer which use 2.2.20. So OrientDB tried to convert DB and failed with the following exception:

```java
Caused by: java.lang.NullPointerException
at java.util.Locale.<init>(Locale.java:573)
at java.util.Locale.<init>(Locale.java:602)
at com.orientechnologies.orient.core.config.OStorageConfiguration.getLocaleInstance(OStorageConfiguration.java:242)
at com.orientechnologies.orient.core.storage.impl.local.paginated.wal.ODiskWriteAheadLog$FilenameFilter.<init>(ODiskWriteAheadLog.java:144)
at com.orientechnologies.orient.core.storage.impl.local.paginated.wal.ODiskWriteAheadLog.<init>(ODiskWriteAheadLog.java:215)
at com.orientechnologies.orient.core.storage.impl.local.paginated.wal.ODiskWriteAheadLog.<init>(ODiskWriteAheadLog.java:154)
at com.orientechnologies.orient.core.storage.impl.local.paginated.OLocalPaginatedStorage.initWalAndDiskCache(OLocalPaginatedStorage.java:484)
at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.open(OAbstractPaginatedStorage.java:255)
```

What can be done to prevent this failing?

**Comment by PhantomYdn** [comment]
Reason is simple. On 2.1.19 country was not required. Just checked in old version of Orienteer - it's null. So during upgrade it leads to NPE because of this code of Locale:

```java
public Locale(String language, String country, String variant) {
        if (language== null || country == null || variant == null) {
            throw new NullPointerException();
        }
        baseLocale = BaseLocale.getInstance(convertOldISOCodes(language), "", country, variant);
        localeExtensions = getCompatibilityExtensions(language, "", country, variant);
    }
```

**Comment by laa** [comment]
Guys this issue is already in progress and fixed by storage team I am assigning it back to us

**Comment by laa** [comment]
Fixed, @PhantomYdn could you try now?

**Comment by laa** [comment]
Hi @PhantomYdn did you have a chance to look on it?

**Comment by laa** [comment]
@PhantomYdn is it possible to provide some ETA when you will be able to check issue?

**Comment by laa** [comment]
Hi @PhantomYdn could you provide an update on this issue?

**Comment by lvca** [comment]
Closing the issue because of no response. In case, please reopen it.
