### ISSUE TITLE
RestClient::Conflict: 409 Conflict when deleting edges from Ruby

### ISSUE THREAD

**Issue by nishantkumar1292** [orientechnologies/orientdb#7523]
## Expected behavior  
While on working on Rails Application, I need to delete some edges. I am using a loop to perform this task iterating over the nodes. The expected behavior must be to perform all the deletions mentioned.

## Actual behavior  
After a few delete operations I get an error as mentioned above. The full trace in mentioned below:
```
DELETE EDGE FROM (select expand(in('brand')) from #12:71591) TO (select from #12:71591)
Time taken: 0.006898657
1/72 listing nodes done
DELETE EDGE FROM (select expand(in('brand')) from #12:84870) TO (select from #12:84870)
Time taken: 0.003101258
2/72 listing nodes done
DELETE EDGE FROM (select expand(in('brand')) from #12:85269) TO (select from #12:85269)
Time taken: 0.004319336
3/72 listing nodes done
DELETE EDGE FROM (select expand(in('brand')) from #12:85339) TO (select from #12:85339)
RestClient::Conflict: 409 Conflict
        from /home/ubuntu/.rvm/gems/ruby-2.4.0/gems/rest-client-1.8.0/lib/restclient/abstract_response.rb:74:in `return!'
        from /home/ubuntu/.rvm/gems/ruby-2.4.0/gems/rest-client-1.8.0/lib/restclient/request.rb:495:in `process_result'
        from /home/ubuntu/.rvm/gems/ruby-2.4.0/gems/rest-client-1.8.0/lib/restclient/request.rb:421:in `block in transmit'
        from /home/ubuntu/.rvm/rubies/ruby-2.4.0/lib/ruby/2.4.0/net/http.rb:877:in `start'
        from /home/ubuntu/.rvm/gems/ruby-2.4.0/gems/rest-client-1.8.0/lib/restclient/request.rb:413:in `transmit'
        from /home/ubuntu/.rvm/gems/ruby-2.4.0/gems/rest-client-1.8.0/lib/restclient/request.rb:176:in `execute'
        from /home/ubuntu/.rvm/gems/ruby-2.4.0/gems/rest-client-1.8.0/lib/restclient/request.rb:41:in `execute'
        from /home/ubuntu/.rvm/gems/ruby-2.4.0/gems/rest-client-1.8.0/lib/restclient/resource.rb:67:in `post'
        from /home/ubuntu/.rvm/gems/ruby-2.4.0/bundler/gems/active-orient-fdae334715ca/lib/rest/operations.rb:113:in `execute'
```

## Steps to Reproduce
Perform delete edge operations in a loop from Ruby using [active-orient](https://github.com/topofocus/active-orient) gem.

**Comment by maggiolo00** [comment]
hi @nishantkumar1292 

did you get also a description with the conflict?

The conflict could be that concurrent modification happened.

**Comment by topofocus** [comment]
Worked recently on ActiveOrient. 

The RestClient::Conflict-Error signals that the server has not accepted the request. 
The solution is to wait  a few ms and then retry.
This is added to ActiveOrient#Execute 

Further: The execute method has been modified to be thread-safe

The Issue should  be solved now
