### ISSUE TITLE
(OrientDBEmbedded.java -[node1] Error on starting distributed plugin com.orientechnologies.orient.core.exception.ODatabaseException: Cannot open database 'demodb'

### ISSUE THREAD

**Issue by careerscale** [orientechnologies/orientdb#7525]
## Expected behavior  
Expecting orientdb work fine with embedded mode and with cluster support (with -Ddistributed=true).

## Actual behavior  
```
00:40:10.313 [restartedMain] INFO  com.orientechnologies.orient.server.hazelcast.OHazelcastPlugin - [node1] Broadcasting new distributed configuration for database: demodb (version=3)

00:40:10.315 [restartedMain] ERROR com.orientechnologies.orient.server.hazelcast.OHazelcastPlugin - [node1] Error on starting distributed plugin
com.orientechnologies.orient.core.exception.ODatabaseException: Cannot open database 'demodb'
	at com.orientechnologies.orient.core.db.OrientDBEmbedded.openNoAuthenticate(OrientDBEmbedded.java:110) ~[orientdb-core-3.0.0-SNAPSHOT.jar:3.0.0-SNAPSHOT]
	at com.orientechnologies.orient.server.OServer.openDatabase(OServer.java:841) ~[orientdb-server-3.0.0-SNAPSHOT.jar:3.0.0-SNAPSHOT]
	at com.orientechnologies.orient.server.distributed.impl.ODistributedAbstractPlugin.reassignClustersOwnership(ODistributedAbstractPlugin.java:720) ~[orientdb-distributed-3.0.0-SNAPSHOT.jar:3.0.0-SNAPSHOT]
	at com.orientechnologies.orient.server.hazelcast.OHazelcastPlugin$7.call(OHazelcastPlugin.java:759) ~[orientdb-distributed-3.0.0-SNAPSHOT.jar:3.0.0-SNAPSHOT]
	at com.orientechnologies.orient.server.hazelcast.OHazelcastPlugin$7.call(OHazelcastPlugin.java:746) ~[orientdb-distributed-3.0.0-SNAPSHOT.jar:3.0.0-SNAPSHOT]
	at com.orientechnologies.orient.server.distributed.impl.ODistributedAbstractPlugin.executeInDistributedDatabaseLock(ODistributedAbstractPlugin.java:1591) ~[orientdb-distributed-3.0.0-SNAPSHOT.jar:3.0.0-SNAPSHOT]
	at com.orientechnologies.orient.server.hazelcast.OHazelcastPlugin.loadLocalDatabases(OHazelcastPlugin.java:746) ~[orientdb-distributed-3.0.0-SNAPSHOT.jar:3.0.0-SNAPSHOT]
	at com.orientechnologies.orient.server.hazelcast.OHazelcastPlugin.startup(OHazelcastPlugin.java:273) [orientdb-distributed-3.0.0-SNAPSHOT.jar:3.0.0-SNAPSHOT]
	at com.orientechnologies.orient.server.OServer.registerPlugins(OServer.java:1109) [orientdb-server-3.0.0-SNAPSHOT.jar:3.0.0-SNAPSHOT]
	at com.orientechnologies.orient.server.OServer.activate(OServer.java:398) [orientdb-server-3.0.0-SNAPSHOT.jar:3.0.0-SNAPSHOT]
	at com.company.test.config.MLMOrientDbConfig.getFactory(MLMOrientDbConfig.java:64) [classes/:?]
	at com.company.testconfig.MLMOrientDbConfig$$EnhancerBySpringCGLIB$$a940651e.CGLIB$getFactory$0(<generated>) [classes/:?]
	at com.company.test.config.MLMOrientDbConfig$$EnhancerBySpringCGLIB$$a940651e$$FastClassBySpringCGLIB$$53063c0f.invoke(<generated>) [classes/:?]
	at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:228) [spring-core-4.3.7.RELEASE.jar:4.3.7.RELEASE]
	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:358) [spring-context-4.3.7.RELEASE.jar:4.3.7.RELEASE]
	at com.company.test.config.MLMOrientDbConfig$$EnhancerBySpringCGLIB$$a940651e.getFactory(<generated>) [classes/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_121]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_121]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_121]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_121]
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:162) [spring-beans-4.3.7.RELEASE.jar:4.3.7.RELEASE]
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:588) [spring-beans-4.3.7.RELEASE.jar:4.3.7.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1173) [spring-beans-4.3.7.RELEASE.jar:4.3.7.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1067) [spring-beans-4.3.7.RELEASE.jar:4.3.7.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:513) [spring-beans-4.3.7.RELEASE.jar:4.3.7.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:483) [spring-beans-4.3.7.RELEASE.jar:4.3.7.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306) [spring-beans-4.3.7.RELEASE.jar:4.3.7.RELEASE]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230) [spring-beans-4.3.7.RELEASE.jar:4.3.7.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302) [spring-beans-4.3.7.RELEASE.jar:4.3.7.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197) [spring-beans-4.3.7.RELEASE.jar:4.3.7.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:761) [spring-beans-4.3.7.RELEASE.jar:4.3.7.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:866) [spring-context-4.3.7.RELEASE.jar:4.3.7.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:542) [spring-context-4.3.7.RELEASE.jar:4.3.7.RELEASE]
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:122) [spring-boot-1.5.2.RELEASE.jar:1.5.2.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:737) [spring-boot-1.5.2.RELEASE.jar:1.5.2.RELEASE]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:370) [spring-boot-1.5.2.RELEASE.jar:1.5.2.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:314) [spring-boot-1.5.2.RELEASE.jar:1.5.2.RELEASE]
	at com.company.test.MlmApplication.main(MlmApplication.java:43) [classes/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_121]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_121]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_121]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_121]
	at org.springframework.boot.devtools.restart.RestartLauncher.run(RestartLauncher.java:49) [spring-boot-devtools-1.5.2.RELEASE.jar:1.5.2.RELEASE]
Caused by: com.orientechnologies.orient.core.exception.OStorageException: Cannot open local storage 'C:\software\orientdb-community-3.0.0-SNAPSHOT\databases/demodb' with mode=rw
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.open(OAbstractPaginatedStorage.java:266) ~[orientdb-core-3.0.0-SNAPSHOT.jar:3.0.0-SNAPSHOT]
	at com.orientechnologies.orient.core.db.OrientDBEmbedded.openNoAuthenticate(OrientDBEmbedded.java:105) ~[orientdb-core-3.0.0-SNAPSHOT.jar:3.0.0-SNAPSHOT]
	... 42 more
Caused by: com.orientechnologies.orient.core.index.OIndexException: Index type: FULLTEXT is not supported. Types are [NOTUNIQUE_HASH_INDEX,FULLTEXT,UNIQUE,UNIQUE_HASH_INDEX,DICTIONARY,DICTIONARY_HASH_INDEX,NOTUNIQUE,FULLTEXT_HASH_INDEX]
	at com.orientechnologies.orient.core.index.OIndexes.findFactoryByAlgorithmAndType(OIndexes.java:166) ~[orientdb-core-3.0.0-SNAPSHOT.jar:3.0.0-SNAPSHOT]
	at com.orientechnologies.orient.core.index.OIndexes.createIndexEngine(OIndexes.java:173) ~[orientdb-core-3.0.0-SNAPSHOT.jar:3.0.0-SNAPSHOT]
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.openIndexes(OAbstractPaginatedStorage.java:288) ~[orientdb-core-3.0.0-SNAPSHOT.jar:3.0.0-SNAPSHOT]
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.open(OAbstractPaginatedStorage.java:236) ~[orientdb-core-3.0.0-SNAPSHOT.jar:3.0.0-SNAPSHOT]
	at com.orientechnologies.orient.core.db.OrientDBEmbedded.openNoAuthenticate(OrientDBEmbedded.java:105) ~[orientdb-core-3.0.0-SNAPSHOT.jar:3.0.0-SNAPSHOT]
	... 42 more
00:40:10.319 [restartedMain] INFO  com.orientechnologies.orient.core.db.OrientDBEmbedded - - shutdown storage: demodb...
00:40:10.321 [restartedMain] ERROR com.company.test.config.MLMOrientDbConfig - Error while server startup:: Error on starting distributed plugin
00:40:10.941 [restartedMain] WARN  org.springframework.boot.autoconfigure.groovy.template.GroovyTemplateAutoConfiguration - Cannot find template location: classpath:/templates/ (please add some templates, check your Groovy configuration, or set spring.groovy.template.check-template-location=false)
00:40:12.194 [restartedMain] INFO  org.apache.coyote.http11.Http11NioProtocol - Initializing ProtocolHandler ["http-nio-8084"]
00:40:12.217 [restartedMain] INFO  org.apache.coyote.http11.Http11NioProtocol - Starting ProtocolHandler [http-nio-8084]
00:40:12.222 [restartedMain] INFO  org.apache.tomcat.util.net.NioSelectorPool - Using a shared selector for servlet write/read
```

## Steps to reproduce  

Create a java web application with embedded orientdb reference and enable distrubuted support.

**Comment by careerscale** [comment]
@luigidellaquila, @tglman  is this expected behavior? I thought it should work fine in embedded mode and with clustering.

**Comment by luigidellaquila** [comment]
Hi @careerscale 

the problem here seems to be with an index. Do you have Lucene jar files in the classpath?

As a quick test, you can drop "demodb" database and try again, as the problem seems to arise when the db tries to open that DB

Thanks

Luigi

**Comment by careerscale** [comment]
@luigidellaquila ,

yes, we tried that.  

C:\software\orientdb-community-3.0.0-SNAPSHOT\bin>console.bat c:\git_repo\test-parent\resources\db\schema.sql

OrientDB console v.3.0.0-SNAPSHOT (build b43ef3417ae43bcaa6c9745d263b0cba2628037c) https://www.orientdb.com
Type 'help' to display all the supported commands.

Previous value was: false
ignoreErrors = true

Disconnecting from remote server [remote:localhost/test]...
OK

Database 'remote:localhost/test' deleted successfully

Previous value was: true
ignoreErrors = false

Creating database [remote:localhost/test] using the storage type [plocal]...
Error: com.orientechnologies.orient.core.exception.OStorageException: Cannot create the remote storage: test

Error: com.orientechnologies.orient.core.exception.ODatabaseException: Cannot create database 'test'
        DB name="test"
        DB name="test"

Error: com.orientechnologies.orient.core.exception.OStorageException: Storage test is not opened.
        DB name="test"

C:\software\orientdb-community-3.0.0-SNAPSHOT\bin>


`04:22:35.507 [OrientDB (/127.0.0.1:2424) <- BinaryClient (/127.0.0.1:59834)] ERROR com.orientechnologies.orient.core.storage.impl.local.paginated.OLocalPaginatedStorage - Exception `205F0358` in storage `test`
com.orientechnologies.orient.core.exception.OStorageException: Storage test is not opened.
	DB name="test"
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.checkOpenness(OAbstractPaginatedStorage.java:3474) [orientdb-core-3.0.0-SNAPSHOT.jar:3.0.0-SNAPSHOT]
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.getClusterIdByName(OAbstractPaginatedStorage.java:1356) [orientdb-core-3.0.0-SNAPSHOT.jar:3.0.0-SNAPSHOT]
	at com.orientechnologies.orient.server.distributed.impl.ODistributedStorage.getClusterIdByName(ODistributedStorage.java:1710) [orientdb-distributed-3.0.0-SNAPSHOT.jar:3.0.0-SNAPSHOT]
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentAbstract.getClusterIdByName(ODatabaseDocumentAbstract.java:891) [orientdb-core-3.0.0-SNAPSHOT.jar:3.0.0-SNAPSHOT]
	at com.orientechnologies.orient.core.metadata.OMetadataDefault.init(OMetadataDefault.java:130) [orientdb-core-3.0.0-SNAPSHOT.jar:3.0.0-SNAPSHOT]
	at com.orientechnologies.orient.server.distributed.impl.ODatabaseDocumentDistributed.createMetadata(ODatabaseDocumentDistributed.java:417) [orientdb-distributed-3.0.0-SNAPSHOT.jar:3.0.0-SNAPSHOT]
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentEmbedded.internalCreate(ODatabaseDocumentEmbedded.java:194) [orientdb-core-3.0.0-SNAPSHOT.jar:3.0.0-SNAPSHOT]
	at com.orientechnologies.orient.core.db.OrientDBEmbedded.internalCreate(OrientDBEmbedded.java:239) [orientdb-core-3.0.0-SNAPSHOT.jar:3.0.0-SNAPSHOT]
	at com.orientechnologies.orient.core.db.OrientDBEmbedded.create(OrientDBEmbedded.java:185) [orientdb-core-3.0.0-SNAPSHOT.jar:3.0.0-SNAPSHOT]
	at com.orientechnologies.orient.server.OServer.createDatabase(OServer.java:1151) [orientdb-server-3.0.0-SNAPSHOT.jar:3.0.0-SNAPSHOT]
	at com.orientechnologies.orient.server.OConnectionBinaryExecutor.executeCreateDatabase(OConnectionBinaryExecutor.java:133) [orientdb-server-3.0.0-SNAPSHOT.jar:3.0.0-SNAPSHOT]
	at com.orientechnologies.orient.client.remote.message.OCreateDatabaseRequest.execute(OCreateDatabaseRequest.java:95) [orientdb-client-3.0.0-SNAPSHOT.jar:3.0.0-SNAPSHOT]
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.sessionRequest(ONetworkProtocolBinary.java:258) [orientdb-server-3.0.0-SNAPSHOT.jar:3.0.0-SNAPSHOT]
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.execute(ONetworkProtocolBinary.java:180) [orientdb-server-3.0.0-SNAPSHOT.jar:3.0.0-SNAPSHOT]
	at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:77) [orientdb-core-3.0.0-SNAPSHOT.jar:3.0.0-SNAPSHOT]

REPLICATION LATENCY AVERAGE (in milliseconds)
+-------+------+
|Servers|node1*|
+-------+------+
|node1* |      |
+-------+------+

REPLICATION MESSAGE COUNTERS (servers: source on the row and destination on the column)
+-------+------+-----+
|Servers|node1*|TOTAL|
+-------+------+-----+
|node1* |      |    0|
+-------+------+-----+
|TOTAL  |  null|    0|
+-------+------+-----+

REPLICATION MESSAGE CURRENT NODE STATS
+-------+-----+
|Servers|TOTAL|
+-------+-----+
|node1* |    0|
+-------+-----+
|TOTAL  |    0|
+-------+-----+


DATABASE 'test' ON SERVER 'node1'
- HA RESOURCE LOCKS FOR SERVER 'node1'
- HA RECORD LOCKS FOR DATABASE 'test'

- MESSAGES IN QUEUES:
 - QUEUE LOCK EXECUTING: null
 - QUEUE UNLOCK EXECUTING: null
 - QUEUE 0 EXECUTING: null
 - QUEUE 1 EXECUTING: null
 - QUEUE 2 EXECUTING: null
 - QUEUE 3 EXECUTING: null
 - QUEUE 4 EXECUTING: null
 - QUEUE 5 EXECUTING: null
 - QUEUE 6 EXECUTING: null
 - QUEUE 7 EXECUTING: null

REPLICATION LATENCY AVERAGE (in milliseconds)
+-------+------+
|Servers|node1*|
+-------+------+
|node1* |      |
+-------+------+

REPLICATION MESSAGE COUNTERS (servers: source on the row and destination on the column)
+-------+------+-----+
|Servers|node1*|TOTAL|
+-------+------+-----+
|node1* |      |    0|
+-------+------+-----+
|TOTAL  |  null|    0|
+-------+------+-----+

REPLICATION MESSAGE CURRENT NODE STATS
+-------+-----+
|Servers|TOTAL|
+-------+-----+
|node1* |    0|
+-------+-----+
|TOTAL  |    0|
+-------+-----+


DATABASE 'test' ON SERVER 'node1'
- HA RESOURCE LOCKS FOR SERVER 'node1'
- HA RECORD LOCKS FOR DATABASE 'test'

- MESSAGES IN QUEUES:
 - QUEUE LOCK EXECUTING: null
 - QUEUE UNLOCK EXECUTING: null
 - QUEUE 0 EXECUTING: null
 - QUEUE 1 EXECUTING: null
 - QUEUE 2 EXECUTING: null
 - QUEUE 3 EXECUTING: null
 - QUEUE 4 EXECUTING: null
 - QUEUE 5 EXECUTING: null
 - QUEUE 6 EXECUTING: null
 - QUEUE 7 EXECUTING: null`

**Comment by careerscale** [comment]
@luigidellaquila , it seems to be that I was using few days older version of db software where as the application db was latest one (I needed to give orientdb_home as a VM argument.

when I took latest snapshot, no more exceptions, but my db script execution from command prompt, never terminates, it seems to create db but next  statement is 

![image](https://user-images.githubusercontent.com/342691/27791432-ce2e43c8-5fa9-11e7-9575-3d35f5bb39b9.png)

Also, though I start application multiple times, it prompts for node name everytime.

`Node name [BLANK=auto generate it]: node1`

is this normal?

**Comment by careerscale** [comment]
one more question:
do we need to run multiple servers? do we have any mandatory quorum when we run with distributed=true VM argument

**Comment by careerscale** [comment]
@santo-it , thank you. Opened the ticket. should we close this one?

**Comment by santo-it** [comment]
Yes, I'm closing this. Many thanks.
