### ISSUE TITLE
NPE during creation of a property for a specific class

### ISSUE THREAD

**Issue by PhantomYdn** [orientechnologies/orientdb#7546]
### OS: linux

It seems that OrientDB doesn't like class with name "Report". After creation of such class there are lots of interesting stuff is happening. And the only one solution: rollback to previous backup.

Creation of a new property for class "Report" or attempt to retrieve newly created class lead to the NPE in the same place.

Creation of property:
```java
java.lang.NullPointerException
     at com.orientechnologies.orient.core.storage.impl.local.paginated.OPaginatedCluster.getEntries(OPaginatedCluster.java:1425)
     at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.count(OAbstractPaginatedStorage.java:1158)
     at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.countClusterElements(ODatabaseDocumentTx.java:816)
     at com.orientechnologies.orient.core.iterator.ORecordIteratorClass.config(ORecordIteratorClass.java:141)
     at com.orientechnologies.orient.core.iterator.ORecordIteratorClass.<init>(ORecordIteratorClass.java:90)
     at com.orientechnologies.orient.core.iterator.ORecordIteratorClass.<init>(ORecordIteratorClass.java:68)
     at com.orientechnologies.orient.core.sql.OCommandExecutorSQLResultsetAbstract.searchInClasses(OCommandExecutorSQLResultsetAbstract.java:479)
     at com.orientechnologies.orient.core.sql.OCommandExecutorSQLResultsetAbstract.searchInClasses(OCommandExecutorSQLResultsetAbstract.java:468)
     at com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.searchInClasses(OCommandExecutorSQLSelect.java:1004)
     at com.orientechnologies.orient.core.sql.OCommandExecutorSQLResultsetAbstract.assignTarget(OCommandExecutorSQLResultsetAbstract.java:209)
     at com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.assignTarget(OCommandExecutorSQLSelect.java:530)
     at com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.executeSearch(OCommandExecutorSQLSelect.java:512)
     at com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.execute(OCommandExecutorSQLSelect.java:488)
     at com.orientechnologies.orient.core.sql.OCommandExecutorSQLDelegate.execute(OCommandExecutorSQLDelegate.java:74)
     at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.executeCommand(OAbstractPaginatedStorage.java:3200)
     at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.command(OAbstractPaginatedStorage.java:3138)
     at com.orientechnologies.orient.core.command.OCommandRequestTextAbstract.execute(OCommandRequestTextAbstract.java:69)
     at com.orientechnologies.orient.core.metadata.schema.OClassImpl.checkPersistentPropertyType(OClassImpl.java:2186)
     at com.orientechnologies.orient.core.metadata.schema.OClassImpl.addPropertyInternal(OClassImpl.java:1812)
     at com.orientechnologies.orient.core.metadata.schema.OClassImpl$6.call(OClassImpl.java:2606)
     at com.orientechnologies.orient.core.metadata.schema.OClassImpl$6.call(OClassImpl.java:2603)
     at com.orientechnologies.orient.core.db.OScenarioThreadLocal.executeAsDistributed(OScenarioThreadLocal.java:70)
     at com.orientechnologies.orient.core.metadata.schema.OClassImpl.addProperty(OClassImpl.java:2603)
     at com.orientechnologies.orient.core.metadata.schema.OClassImpl.createProperty(OClassImpl.java:807)
```

Count of documents for a class:

```java
Caused by: java.lang.NullPointerException
	at com.orientechnologies.orient.core.storage.impl.local.paginated.OPaginatedCluster.getEntries(OPaginatedCluster.java:1425)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.count(OAbstractPaginatedStorage.java:1158)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.countClusterElements(ODatabaseDocumentTx.java:816)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.countClusterElements(ODatabaseDocumentTx.java:770)
	at com.orientechnologies.orient.core.metadata.schema.OClassImpl.count(OClassImpl.java:1510)
	at com.orientechnologies.orient.core.metadata.schema.OClassImpl.count(OClassImpl.java:1503)
```

If "Report" is so specific - please make it a keyword.

**Comment by laa** [comment]
@PhantomYdn just to clarify is it 2.2.2 version?

**Comment by PhantomYdn** [comment]
I'm sorry - you are right. I meant 2.2.22

**Comment by laa** [comment]
@PhantomYdn do you have broken database, which you are talking about? Do you have logs from this database? Preferably since the creation of a class Report? That is very important.

**Comment by PhantomYdn** [comment]
Backup was provided through Skype.

**Comment by laa** [comment]
Fixed. @santo-it description for release notes "In early versions of OrientDB deleted files did not preserve their ids correctly, as result after upgrade to latest version and creation of the cluster with the same name  all cluster files are assigned the same id, so one file overwrites another file in file system and created cluster contains incomplete information about its state. "

**Comment by PhantomYdn** [comment]
@laa , thank you a lot!
