### ISSUE TITLE
Cannot open local storage 'C:/orientdb-teleporter-community-2.2.23/databases/OSystem' with mode=rw at first run

### ISSUE THREAD

**Issue by adepase** [orientechnologies/orientdb#7553]
### OrientDB Version: orientdb-teleporter-community-2.2.23
OrientDB Server v2.2.23 (build 1318ca25b3927d22d6a7d5316000e20cb3d9329c)
Databases directory: C:\orientdb-teleporter-community-2.2.23\databases [OServer]
OrientDB auto-config DISKCACHE=1.024MB (heap=910MB direct=1.024MB os=8.122MB) 

### Java Version: 
The first time it gave this information:
INFO  32 bit JVM is detected. Lowering disk cache size from 1.024MB to 512MB. [OGlobalConfiguration]
Analizing the server.bat I understand that it found C:\Program Files (x86)\Java\jdk1.8.0_92 (it was in the JAVA_HOME variable).
However after the first run I forced it to use the 64bit version (C:\Program Files\Java\jdk1.8.0_92\bin) and it didn't displayed any more any information about the JVM (so I understand it correctly found that that was a 64bit version), but, sadly, with the same result 

## Expected behavior  
Clean first startup

## Actual behavior  
Following errors and no way to login from the Web studio (I tried both with the root user, with the password supplied during the installation phase and with admin/admin):

017-07-15 11:29:47:887 INFO  OrientDB Server is active v2.2.23 (build 1318ca25b3927d22d6a7d5316000e20cb3d9329c). [OServer]$ANSI{green {db=OSystem}} Exception `01F1F6FC` in storage `OSystem`
com.orientechnologies.orient.core.exception.OStorageException: Cannot open local storage 'C:/orientdb-teleporter-community-2.2.23/databases/OSystem' with mode=rw
        DB name="OSystem"
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.open(OAbstractPaginatedStorage.java:299)
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.open(ODatabaseDocumentTx.java:258)
        at com.orientechnologies.orient.server.OServer.openDatabaseBypassingSecurity(OServer.java:980)
        at com.orientechnologies.orient.server.OServer.openDatabase(OServer.java:947)
        at com.orientechnologies.orient.server.OServer.openDatabase(OServer.java:932)
        at com.orientechnologies.orient.server.OSystemDatabase.openSystemDatabase(OSystemDatabase.java:92)
        at com.orientechnologies.orient.server.OSystemDatabase.execute(OSystemDatabase.java:99)
        at com.orientechnologies.orient.server.security.ODefaultServerSecurity.getSystemUser(ODefaultServerSecurity.java:284)
        at com.orientechnologies.orient.server.security.authenticator.OSystemUserAuthenticator.isAuthorized(OSystemUserAuthenticator.java:93)
        at com.orientechnologies.orient.server.security.ODefaultServerSecurity.isAuthorized(ODefaultServerSecurity.java:311)
        at com.orientechnologies.orient.server.network.protocol.http.command.get.OServerCommandGetListDatabases.execute(OServerCommandGetListDatabases.java:56)
        at com.orientechnologies.orient.server.network.protocol.http.ONetworkProtocolHttpAbstract.service(ONetworkProtocolHttpAbstract.java:169)
        at com.orientechnologies.orient.server.network.protocol.http.ONetworkProtocolHttpAbstract.execute(ONetworkProtocolHttpAbstract.java:621)
        at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:77)
Caused by: com.orientechnologies.common.io.OIOException: You cannot access outside the file size (0 bytes). You have requested portion 0-4 bytes. File: File: database.ocf os-size=1024, stored=0
        at com.orientechnologies.orient.core.storage.fs.OFileClassic.checkRegions(OFileClassic.java:517)
        at com.orientechnologies.orient.core.storage.fs.OFileClassic.readInt(OFileClassic.java:250)
        at com.orientechnologies.orient.core.storage.impl.local.OStorageConfigurationSegment.load(OStorageConfigurationSegment.java:103)
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.open(OAbstractPaginatedStorage.java:240)
        ... 13 more

## Steps to reproduce  
Downloaded zip.
Extracted in C:\.
Changed server.bat memory sizes (512G->1G). 
Executed server.bat (both by clicking on in and writing on the command line, in two differents steps - the second after a clean shutdown)
connect to http://my_local_ip_address:2480/studio/index.html#/
Before connecting, no errors, only the first log startup lines. After connecting, the first error appeared also without trying to login. The web page seems ok.

**Comment by adepase** [comment]
I tried a last thing: I uninstalled everything and re-installed it. I changed the .bat in the same way as said before, but I forced the 64bit version of Java before the first run. Everything went ok.
I suggest to add this point to the documentation (and a check in the startup script with a warning big as an house, maybe asking for a confirmation before continuing).

**Comment by laa** [comment]
@adepase how did you get a server ?

**Comment by adepase** [comment]
Sorry, I cannot understand your question. Explain, please. And, please,
note that I found the solution (written in a comment). I cannot change the
status, but, it's ok
Thank you
    Alessandro


2017-07-15 14:40 GMT+02:00 Andrey Lomakin <notifications@github.com>:

**Comment by laa** [comment]
Hi @adepase, I suppose database fixed itself and your biggest problem was that distribution which you downloaded was broken. Could you provide a source from which you downloaded distribution? You are right though that we require 64 bit JVM for a server to run.

**Comment by adepase** [comment]
No, Andrey, I uninstalled and reinstalled the _same_ distribution (I kept
the .zip and unzipped it again, when I had that idea of forcing the JDK),
so it didn't fixed itself, (I tried several times before uninstall it, no
way): I completely uninstalled it and forced a different (64bit instead
32bit, but _same_ version) installation of the JDK.
Just that.
It means that the very first run with a 32bit version breaks the
installation and no matter if you use it with a 64bit version later.
You have to use a 64bit version since the very first run, so to make it
work.

Glad to hear that you know you require the 64 bit version, but the startup
process simply gives a simple INFO in the log, almost invisible among the
other rows, while it should stop or, at least, ask to continue with a very
big warning.

However I simply downloaded it from the official Web site, ie.from
http://orientdb.com/download/ (Windows distribution, Community Edition)

BR
   Alessandro



2017-07-15 15:09 GMT+02:00 Andrey Lomakin <notifications@github.com>:

**Comment by laa** [comment]
@adepase I see thank you for feedback and provided information.  @robfrank could we add -d64 switch on server start. I do not think that today there are pure 32 bit systems.
