### ISSUE TITLE
OrientDB token error when reading

### ISSUE THREAD

**Issue by Raycoms** [orientechnologies/orientdb#7572]
Exception in thread "Delivery Thread" com.orientechnologies.orient.core.sql.parser.TokenMgrError: Lexical error at line 1, column 146.  Encountered: "\r" (13), after : "\'/U\ufffd\ufffd\ufffdn(\ufffd39\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd5\u0005 no\ufffd\ufffd]\ufffd\ufffd\ufffd]}!^o\u001c"
	at com.orientechnologies.orient.core.sql.parser.OrientSqlTokenManager.getNextToken(OrientSqlTokenManager.java:5966)
	at com.orientechnologies.orient.core.sql.parser.OrientSql.jj_scan_token(OrientSql.java:26084)
	at com.orientechnologies.orient.core.sql.parser.OrientSql.jj_3R_280(OrientSql.java:23918)
	at com.orientechnologies.orient.core.sql.parser.OrientSql.jj_3R_108(OrientSql.java:23935)
	at com.orientechnologies.orient.core.sql.parser.OrientSql.jj_3R_138(OrientSql.java:20576)
	at com.orientechnologies.orient.core.sql.parser.OrientSql.jj_3R_324(OrientSql.java:21673)
	at com.orientechnologies.orient.core.sql.parser.OrientSql.jj_3R_130(OrientSql.java:21869)
	at com.orientechnologies.orient.core.sql.parser.OrientSql.jj_3R_682(OrientSql.java:21982)
	at com.orientechnologies.orient.core.sql.parser.OrientSql.jj_3R_594(OrientSql.java:22014)
	at com.orientechnologies.orient.core.sql.parser.OrientSql.jj_3R_464(OrientSql.java:22133)
	at com.orientechnologies.orient.core.sql.parser.OrientSql.jj_3R_465(OrientSql.java:22140)
	at com.orientechnologies.orient.core.sql.parser.OrientSql.jj_3R_296(OrientSql.java:22180)
	at com.orientechnologies.orient.core.sql.parser.OrientSql.jj_3R_115(OrientSql.java:22208)
	at com.orientechnologies.orient.core.sql.parser.OrientSql.jj_3R_376(OrientSql.java:22223)
	at com.orientechnologies.orient.core.sql.parser.OrientSql.jj_3R_218(OrientSql.java:20987)
	at com.orientechnologies.orient.core.sql.parser.OrientSql.jj_3R_93(OrientSql.java:21053)
	at com.orientechnologies.orient.core.sql.parser.OrientSql.jj_3_36(OrientSql.java:21362)
	at com.orientechnologies.orient.core.sql.parser.OrientSql.jj_2_36(OrientSql.java:17931)
	at com.orientechnologies.orient.core.sql.parser.OrientSql.QueryStatement(OrientSql.java:893)
	at com.orientechnologies.orient.core.sql.parser.OrientSql.StatementInternal(OrientSql.java:717)
	at com.orientechnologies.orient.core.sql.parser.OrientSql.Statement(OrientSql.java:609)
	at com.orientechnologies.orient.core.sql.parser.OrientSql.parse(OrientSql.java:76)
	at com.orientechnologies.orient.core.sql.parser.OStatementCache.parse(OStatementCache.java:89)
	at com.orientechnologies.orient.core.sql.parser.OStatementCache.get(OStatementCache.java:72)
	at com.orientechnologies.orient.core.sql.parser.OStatementCache.get(OStatementCache.java:62)
	at com.orientechnologies.orient.core.sql.OCommandExecutorSQLAbstract.preParse(OCommandExecutorSQLAbstract.java:229)
	at com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.parse(OCommandExecutorSQLSelect.java:266)
	at com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.parse(OCommandExecutorSQLSelect.java:100)
	at com.orientechnologies.orient.core.sql.OCommandExecutorSQLDelegate.parse(OCommandExecutorSQLDelegate.java:58)
	at com.orientechnologies.orient.core.sql.OCommandExecutorSQLDelegate.parse(OCommandExecutorSQLDelegate.java:39)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.command(OAbstractPaginatedStorage.java:2616)
	at com.orientechnologies.orient.core.sql.query.OSQLQuery.run(OSQLQuery.java:78)
	at com.orientechnologies.orient.core.sql.query.OSQLAsynchQuery.run(OSQLAsynchQuery.java:74)
	at com.orientechnologies.orient.core.sql.query.OSQLSynchQuery.run(OSQLSynchQuery.java:85)
	at com.orientechnologies.orient.core.query.OQueryAbstract.execute(OQueryAbstract.java:33)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.query(ODatabaseDocumentTx.java:728)
	at com.tinkerpop.blueprints.impls.orient.OrientGraphQuery.vertices(OrientGraphQuery.java:204)
	at com.tinkerpop.blueprints.impls.orient.OrientBaseGraph.getVertices(OrientBaseGraph.java:933)
	at main.java.com.bag.server.database.OrientDBDatabaseAccess.getVertexList(OrientDBDatabaseAccess.java:211)
	at main.java.com.bag.server.database.OrientDBDatabaseAccess.compareNode(OrientDBDatabaseAccess.java:247)
	at main.java.com.bag.server.database.interfaces.IDatabaseAccess.equalHashNode(IDatabaseAccess.java:82)
	at main.java.com.bag.server.database.interfaces.IDatabaseAccess.equalHash(IDatabaseAccess.java:37)
	at main.java.com.bag.server.ConflictHandler.isCorrect(ConflictHandler.java:195)
	at main.java.com.bag.server.ConflictHandler.checkForConflict(ConflictHandler.java:52)
	at main.java.com.bag.server.GlobalClusterSlave.executeCommit(GlobalClusterSlave.java:214)
	at main.java.com.bag.server.GlobalClusterSlave.appExecuteBatch(GlobalClusterSlave.java:112)
	at bftsmart.tom.server.defaultservices.DefaultRecoverable.executeBatch(DefaultRecoverable.java:87)
	at bftsmart.tom.server.defaultservices.DefaultRecoverable.executeBatch(DefaultRecoverable.java:68)
	at bftsmart.tom.ServiceReplica.receiveMessages(ServiceReplica.java:432)
	at bftsmart.tom.core.DeliveryThread.deliverMessages(DeliveryThread.java:293)
	at bftsmart.tom.core.DeliveryThread.run(DeliveryThread.java:225)

That's the data where he gets problem reading.
I do sb.toString() to store it.

MessageDigest mDigest = MessageDigest.getInstance("SHA1");

        byte[] result = mDigest.digest(node.getBytes());

        StringBuilder sb = new StringBuilder();
        for (final byte aResult : result)
        {
            sb.append(Integer.toString((aResult & 0xff) + 0x100, 16).substring(1));
        }

        return sb.toString();

**Comment by luigidellaquila** [comment]
Hi @Raycoms 

could you please post a full example on how to reproduce the problem? Do you pass the result of `sb.toString()` to the query as a paramater?

Thanks

Luigi

**Comment by Raycoms** [comment]
/**
     * Returns a list of vertices from the database matching the nodeStorage.
     *
     * @param nodeStorage the nodeStorage.
     * @param graph       the graph database.
     * @return a list of vertices.
     */
    private Iterable<Vertex> getVertexList(final NodeStorage nodeStorage, final OrientGraph graph)
    {
        final String[] propertyKeys = nodeStorage.getProperties().keySet().toArray(new String[0]);
        final Object[] propertyValues = nodeStorage.getProperties().values().toArray();

        try
        {
            return graph.getVertices(nodeStorage.getId(), propertyKeys, propertyValues);
        }
        catch (OQueryParsingException e)
        {
            Log.getLogger().info(String.format("Class %s doesn't exist.", nodeStorage.getId()), e);
            return Collections.emptyList();
        }
        catch(TokenMgrError e)
        {
            Log.getLogger().info("TokenMgrError: ", e); 
            return Collections.emptyList();
        }
    }

Yes the result of sb.toString() is one of the property values in the hashmap in the "nodestorage"

**Comment by Raycoms** [comment]
Just noticed it is that part:

final byte[] signature = TOMUtil.signMessage(keyLoader.loadPrivateKey(), tempStorage.getBytes());
tempStorage.addProperty("signature" + idClient, new String(signature, "UTF-8"));

It works well with all other graph databases though (Neo4j, Sparksee and Titan).

**Comment by luigidellaquila** [comment]
Hi @Raycoms 

I'm working to a fix, I hope I'll be able to push it today

Thanks

Luigi

**Comment by Raycoms** [comment]
Great to hear =)

2017-07-20 10:54 GMT+01:00 luigidellaquila <notifications@github.com>:

**Comment by luigidellaquila** [comment]
Hi @Raycoms 

I pushed a fix on 2.2.x branch that should fix this problem. Could you please try latest snapshot and let me know if it's the case?

Thanks

Luigi

**Comment by luigidellaquila** [comment]
Hi @Raycoms 

The snapshot is in Sonatype repositories (https://oss.sonatype.org/content/repositories/snapshots/com/orientechnologies/orientdb-community/2.2.25-SNAPSHOT/) but not yet in Maven Central of course

Thanks

Luigi

**Comment by lvca** [comment]
@Raycoms any news on this?

**Comment by Raycoms** [comment]
I'm currently still traveling I will get to test it when I return.

2017-08-05 7:50 GMT+01:00 Luca Garulli <notifications@github.com>:

**Comment by luigidellaquila** [comment]
Hi @Raycoms 

This was fixed a few months ago, I suppose everything is OK on this issue (it seems so on my side), I'm closing it but please feel free to reopen if you still see problems

Thanks

Luigi
