### ISSUE TITLE
NullPointerException while trying to perform action with record previously deleted by another thread

### ISSUE THREAD

**Issue by arkolesnik** [orientechnologies/orientdb#7575]
## Expected behavior  
If record not found (i.e. was previously deleted by another thread), ORecordNotFoundException should be thrown.

## Actual behavior  
In most cases I get NullPointerException in attempt to delete or modify instance returned by database.load(new ORecordId(clusterID, randomPosition)). 

## Steps to reproduce  
1. Create custom class with different properties.
2. Create ~100 instances of ODocument in this class. 
3. Fill in all fields.
4. Create task for 8 threads and try to randomly get existing instance and then modify or delete it. If to catch NullPointerException, sometimes ORecordNotFoundException is thrown - correct behavior. If not to catch NullPointerException, in many cases database.load() returns null.

**Comment by tglman** [comment]
hi @arkolesnik,

Can you add the test case or an example? and would be cool also the full stack trace.

Bye

**Comment by arkolesnik** [comment]
Hi @tglman! 
I didn't provide a stack trace because it can be different each time and it is not quite informative. I can show you one of them: 
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at IndexesLoadTest.shouldRecreateIndexes(IndexesLoadTest.java:71)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:72)
	at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:123)
Caused by: java.lang.NullPointerException
	at IndexesLoadTest.modifyMapProperty(IndexesLoadTest.java:270)
	at IndexesLoadTest.modifyRecordProperties(IndexesLoadTest.java:242)
	at IndexesLoadTest.performOperationAgainstRecord(IndexesLoadTest.java:154)
	at IndexesLoadTest.lambda$shouldRecreateIndexes$0(IndexesLoadTest.java:63)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

Here we are trying to modify a record came from database.load(new ORecordId(clusterID, randomPosition))

I suppose it would be more informative for you to see and run this test  - I've just created a separate branch for it, hope it will help. 
https://github.com/arkolesnik/orientdb-automation/tree/issue7575-npe-example
You should run shouldRecreateIndexes() test from IndexesLoadTest class, but please previously change static field public static final String PATH = "plocal:D:/tmp/database/testuniqueindexes" (CreateDatabaseForLoadFixture class) - unfortunately I have it local at the moment. And after this everything must work. The test runs 1 minute.

**Comment by tglman** [comment]
hi @arkolesnik,

As today the `db.load(rid)` return a null record if you do a load of a record that do not exist, in other kind of operations is expected to throw a `ORecordNotFoundException`,I cannot point right now what exactly do what, but yes this case should be uniformed or at least made clear on the API that can throw the exception and the API that just return null.

Regards
