### ISSUE TITLE
CREATE VERTEX with double nested Json content fails

### ISSUE THREAD

**Issue by Kanji-Galaxy** [orientechnologies/orientdb#7596]
## Expected behavior  
Insert double nested Json content via CREATE VERTEX command.

## Actual behavior  
Insert works for non-nested and single nested Json content but it fails when providing double nested Json content. For the insert, I am using the Studio GUI.

This problem does not occur in OrientDB version 2.2.4.

## Steps to reproduce  
- Create Class "Publisher" with the following properties:
  - id: String
  - name: Embedded (Linked Class: XLocal)
- Create Generic Class "XLocal" with the following properties:
  - de: String
  - en: String
  - ja: Embedded (Linked Class: XLocalJapanese)
- Create Generic Class "XLocalJapanese" with the following properties:
  - kana: String
  - kanji: String
  - romaji: String

Now, if you try to create a vertex with the following command, it fails.

````
CREATE VERTEX Publisher content 
	{
		"id": "P0112",
		"name": {
    		"@type": "d",
    		"@version": 0,
    		"@class": "XLocal",
    		"de": "Ministerium für Gesundheit, Arbeit und Soziales",
    		"en": "Ministry of Health, Labour and Welfare (MHLW)",
    		"ja": {
        		"@type": "d",
        		"@version": 0,
        		"@class": "XLocalJapanese",
        		"kanji": "厚生労働省",
        		"romaji": "Kōsei Rōdōshō",
        		"kana": "こうせいろうどうしょう"
   			}
		},
		"country": "C001"
	}
````

Instead you are getting this error message:

`java.lang.ClassCastException: java.util.HashMap cannot be cast to com.orientechnologies.orient.core.record.impl.ODocument`

Stack trace:
````
java.lang.ClassCastException: java.util.HashMap cannot be cast to com.orientechnologies.orient.core.record.impl.ODocument
	at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinaryV0.serializeValue(ORecordSerializerBinaryV0.java:724)
	at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinaryV0.serialize(ORecordSerializerBinaryV0.java:382)
	at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinaryV0.serializeValue(ORecordSerializerBinaryV0.java:724)
	at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinaryV0.serialize(ORecordSerializerBinaryV0.java:382)
	at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinary.toStream(ORecordSerializerBinary.java:111)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.commitEntry(OAbstractPaginatedStorage.java:4317)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.commit(OAbstractPaginatedStorage.java:1650)
	at com.orientechnologies.orient.core.storage.impl.local.OMicroTransaction.doCommit(OMicroTransaction.java:372)
	at com.orientechnologies.orient.core.storage.impl.local.OMicroTransaction.commit(OMicroTransaction.java:161)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentAbstract.endMicroTransaction(ODatabaseDocumentAbstract.java:3105)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentAbstract.executeSaveRecord(ODatabaseDocumentAbstract.java:1627)
	at com.orientechnologies.orient.core.tx.OTransactionNoTx.saveNew(OTransactionNoTx.java:244)
	at com.orientechnologies.orient.core.tx.OTransactionNoTx.saveRecord(OTransactionNoTx.java:174)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentAbstract.save(ODatabaseDocumentAbstract.java:2434)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentAbstract.save(ODatabaseDocumentAbstract.java:2310)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentAbstract.save(ODatabaseDocumentAbstract.java:93)
	at com.orientechnologies.orient.core.sql.executor.SaveElementStep$1.next(SaveElementStep.java:40)
	at com.orientechnologies.orient.core.sql.executor.OInsertExecutionPlan.executeInternal(OInsertExecutionPlan.java:49)
	at com.orientechnologies.orient.core.sql.parser.OCreateVertexStatement.execute(OCreateVertexStatement.java:58)
	at com.orientechnologies.orient.core.sql.parser.OStatement.execute(OStatement.java:58)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentEmbedded.command(ODatabaseDocumentEmbedded.java:432)
	at com.orientechnologies.orient.server.network.protocol.http.command.post.OServerCommandPostCommand.executeStatement(OServerCommandPostCommand.java:174)
	at com.orientechnologies.orient.server.network.protocol.http.command.post.OServerCommandPostCommand.execute(OServerCommandPostCommand.java:84)
	at com.orientechnologies.orient.server.network.protocol.http.command.post.OServerCommandPostCommandGraph.execute(OServerCommandPostCommandGraph.java:36)
	at com.orientechnologies.orient.server.network.protocol.http.ONetworkProtocolHttpAbstract.service(ONetworkProtocolHttpAbstract.java:168)
	at com.orientechnologies.orient.server.network.protocol.http.ONetworkProtocolHttpAbstract.execute(ONetworkProtocolHttpAbstract.java:630)
	at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:77)
````

**Comment by luigidellaquila** [comment]
Hi @Kanji-Galaxy 

I'm checking it, I'll let you know asap

Thanks

Luigi

**Comment by luigidellaquila** [comment]
Hi @Kanji-Galaxy 

I tried this simple script, but I couldn't manage to reproduce the problem on latest 3.0.0 snapshot

```
Create  Class XLocalJapanese
create property XLocalJapanese.kana String
create property XLocalJapanese.kanji String
create property XLocalJapanese.romaji String

Create Class XLocal
create property XLocal.de String
create property XLocal.en String
create property XLocal.ja Embedded XLocalJapanese

Create Class Publisher extends V
create property Publisher.id String
create property Publisher.name Embedded XLocal

CREATE VERTEX Publisher content 
	{
		"id": "P0112",
		"name": {
    		"@type": "d",
    		"@version": 0,
    		"@class": "XLocal",
    		"de": "Ministerium für Gesundheit, Arbeit und Soziales",
    		"en": "Ministry of Health, Labour and Welfare (MHLW)",
    		"ja": {
        		"@type": "d",
        		"@version": 0,
        		"@class": "XLocalJapanese",
        		"kanji": "厚生労働省",
        		"romaji": "Kōsei Rōdōshō",
        		"kana": "こうせいろうどうしょう"
   			}
		},
		"country": "C001"
	}
```

any hint on how to reproduce?

Thanks

Luigi

**Comment by Kanji-Galaxy** [comment]
Hi Luigi,

I tried the same now on a completely new database and it suddenly works. I slowly think it might be something else in my old database.

Sorry for the false alarm...

Cheers,
Joern
