### ISSUE TITLE
Inline LINK Batch Variable

### ISSUE THREAD

**Issue by TropicalPenguin** [orientechnologies/orientdb#7633]
## Expected behavior  
Should be able to set batch variables to RID values. Useful, for example, when substituting a single value into a batch with tokens and conditional logic. E.g. Where `/* token */` can be replaced by a RID

```sql
/* Do stuff */
LET foo = /* token */
if ($foo is not null) {
    // Do something with $foo
}
/* Do other stuff... */
```

## Actual behavior  
```
com.orientechnologies.orient.core.command.OCommandExecutorNotFoundException: Cannot find a command executor for the command request: sql.#1:0
	DB name="pac"
	at com.orientechnologies.orient.core.sql.OCommandExecutorSQLDelegate.parse(OCommandExecutorSQLDelegate.java:54)
	at com.orientechnologies.orient.core.sql.OCommandExecutorSQLDelegate.parse(OCommandExecutorSQLDelegate.java:39)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.command(OAbstractPaginatedStorage.java:3144)
	at com.orientechnologies.orient.core.command.OCommandRequestTextAbstract.execute(OCommandRequestTextAbstract.java:69)
	at com.orientechnologies.orient.core.command.script.OCommandExecutorScript.executeCommand(OCommandExecutorScript.java:486)
	at com.orientechnologies.orient.core.command.script.OCommandExecutorScript.executeLet(OCommandExecutorScript.java:624)
	at com.orientechnologies.orient.core.command.script.OCommandExecutorScript.executeSQLScript(OCommandExecutorScript.java:276)
	at com.orientechnologies.orient.core.command.script.OCommandExecutorScript.executeSQL(OCommandExecutorScript.java:197)
	at com.orientechnologies.orient.core.command.script.OCommandExecutorScript.executeInContext(OCommandExecutorScript.java:104)
	at com.orientechnologies.orient.core.command.script.OCommandExecutorScript.execute(OCommandExecutorScript.java:88)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.executeCommand(OAbstractPaginatedStorage.java:3208)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.command(OAbstractPaginatedStorage.java:3146)
	at com.orientechnologies.orient.core.command.OCommandRequestTextAbstract.execute(OCommandRequestTextAbstract.java:69)
	at com.orientechnologies.orient.server.network.protocol.http.command.post.OServerCommandPostBatch.execute(OServerCommandPostBatch.java:196)
	at com.orientechnologies.orient.server.network.protocol.http.ONetworkProtocolHttpAbstract.service(ONetworkProtocolHttpAbstract.java:173)
	at com.orientechnologies.orient.server.network.protocol.http.ONetworkProtocolHttpAbstract.execute(ONetworkProtocolHttpAbstract.java:625)
	at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:77)
```

## Steps to reproduce  

Executing a simple batch, substituting any RID - valid or not, like this:

```sql
BEGIN
LET foo = #1:0
COMMIT
```
... gives an error.

Whereas LINKLIST works...
```sql
BEGIN
LET foo = [#1:0]
COMMIT
```

**Comment by luigidellaquila** [comment]
Hi @TropicalPenguin 

I just fixed this issue on branch 2.2.x, it will be released with 2.2.30.

Leaving open to port the fix to 3.0

Thanks

Luigi
