### ISSUE TITLE
Vertex not accessible any more when having 2.343.000 edges of the same class

### ISSUE THREAD

**Issue by markusforster** [orientechnologies/orientdb#7642]
## Expected behavior  
SELECT FROM "edgeClass" where IN="rid" shows correct result 

SELECT from "rid" should show the same connected vertices as out_"edgeClass" but returns java.lang.NullPointerException  

## Steps to reproduce  
create 2343001 vertices and connect one (vertex1) of them to all the others as a "super vertex". 
SELECT from @rid_vertex1 should produce the error

**Comment by luigidellaquila** [comment]
Hi @markusforster 

Do you have a full stack trace? Does OrientDB produce any other related logs?

Thanks

Luigi

**Comment by markusforster** [comment]
Hi, 
from my webapp that is accessing the orientdb I get the following stacktrace:

Error executing request
com.orientechnologies.common.io.OIOException: Impossible to write a chunk of length:24344722 max allowed chunk length:16777216 see NETWORK_BINARY_MAX_CONTENT_LENGTH settings 
	at com.orientechnologies.orient.enterprise.channel.binary.OChannelBinary.writeBytes(OChannelBinary.java:271)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.readRecord(ONetworkProtocolBinary.java:1908)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.executeRequest(ONetworkProtocolBinary.java:603)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.sessionRequest(ONetworkProtocolBinary.java:384)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.execute(ONetworkProtocolBinary.java:207)
	at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:77)

Is there a way to increase NETWORK_BINARY_MAX_CONTENT_LENGTH ?

When requesting from orientdb console I get the following stacktrace:

Error on unmarshalling record #14:2412777 (com.orientechnologies.common.io.OIOException: Impossible to write a chunk of length:24344722 max allowed chunk length:16777216 see NETWORK_BINARY_MAX_CONTENT_LENGTH settings )
com.orientechnologies.common.io.OIOException: Impossible to write a chunk of length:24344722 max allowed chunk length:16777216 see NETWORK_BINARY_MAX_CONTENT_LENGTH settings 
	at com.orientechnologies.orient.enterprise.channel.binary.OChannelBinary.writeBytes(OChannelBinary.java:271)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.writeRecord(ONetworkProtocolBinary.java:2899)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.writeIdentifiable(ONetworkProtocolBinary.java:2682)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.serializeValue(ONetworkProtocolBinary.java:1608)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.command(ONetworkProtocolBinary.java:1553)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.executeRequest(ONetworkProtocolBinary.java:646)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.sessionRequest(ONetworkProtocolBinary.java:384)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.execute(ONetworkProtocolBinary.java:207)
	at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:77)

2017-08-11 08:48:49:533 WARNI Cannot serialize record: V#14:2412777{in_source:[size=2434463],entityId:LocationEntity:luxembourg,entityLevel:super,entityType:LocationEntity,occurence:0} v2436 [ONetworkProtocolBinary]Error on unmarshalling record #14:2412777 (com.orientechnologies.common.io.OIOException: Impossible to write a chunk of length:24344722 max allowed chunk length:16777216 see NETWORK_BINARY_MAX_CONTENT_LENGTH settings )
com.orientechnologies.common.io.OIOException: Impossible to write a chunk of length:24344722 max allowed chunk length:16777216 see NETWORK_BINARY_MAX_CONTENT_LENGTH settings 
	at com.orientechnologies.orient.enterprise.channel.binary.OChannelBinary.writeBytes(OChannelBinary.java:271)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.writeRecord(ONetworkProtocolBinary.java:2899)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.writeIdentifiable(ONetworkProtocolBinary.java:2682)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.serializeValue(ONetworkProtocolBinary.java:1608)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.command(ONetworkProtocolBinary.java:1553)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.executeRequest(ONetworkProtocolBinary.java:646)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.sessionRequest(ONetworkProtocolBinary.java:384)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.execute(ONetworkProtocolBinary.java:207)
	at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:77)

2017-08-11 08:48:50:129 WARNI Cannot serialize record: V#14:2412777{in_source:[size=2434463],entityId:LocationEntity:luxembourg,entityLevel:super,entityType:LocationEntity,occurence:0} v2436 [ONetworkProtocolBinary]


Overall it seems to be a problem with the vertex's size.

Do you have any recommendations?

**Comment by luigidellaquila** [comment]
Hi @markusforster 

It seems the vertex is too big to be serialized on the network with basic configuration, you can increase NETWORK_BINARY_MAX_CONTENT_LENGTH as follows:

- from orientdb-server-config.xml: add the following property in the section at the end of the file:

```
<properties>
...
<entry name="network.binary.maxLength" value="<a value in KB here>"/>
...
```

- at startup, specifying the following parameter on the command line:

```
-Dnetwork.binary.maxLength=<aValueInKb>

eg. 

-Dnetwork.binary.maxLength=32768
```

- if you are running embedded, you can do the following before you start the server:
```
OGlobalConfiguration.NETWORK_BINARY_MAX_CONTENT_LENGTH.set(32768);
```

I hope it helps

Thanks

Luigi

**Comment by markusforster** [comment]
Hi luigidellaquila,
thanks so far,

after doing the suggested entry in the config and setting the command line option and restarting the orientdb server I still get the error message:

Error: com.orientechnologies.common.io.OIOException: Impossible to read a chunk of length:24344738 max allowed chunk length:16777216 see NETWORK_BINARY_MAX_CONTENT_LENGTH settings 

Looks like the config entry doesn't change the value.

**Comment by luigidellaquila** [comment]
Hi @markusforster 

Could you please try setting the value via command line? Maybe there is a problem on loading that particular property from XML

Thanks

Luigi

**Comment by markusforster** [comment]
Hi @luigidellaquila ,

I tried that too .... also no effect.

Best,

Markus

**Comment by luigidellaquila** [comment]
Ok, assigning to @tglman for a check

Thanks

Luigi

**Comment by tglman** [comment]
hi @markusforster,

You need to set the same setting in both the server and the client to make it work properly.

Regards
