### ISSUE TITLE
question: Does import database operation delete existed records?

### ISSUE THREAD

**Issue by HuangKBAaron** [orientechnologies/orientdb#7653]
## Expected behavior  
Import database doesn't delete existed records.

## Actual behavior  
just found imported 30000 records were deleted!

## Steps to reproduce  
Because inserting record is really time consuming, I use some other server do the inserting paralleled, and import one of them to the main server. Found the existed 30000 record deleted!
script:
`import database xxxx10-15.export.gz -preserveClusterIDs=true`
Questions:
How can i restore the deleted records? And how to import without deleting existed records?

**Comment by tglman** [comment]
hi @HuangKBAaron,

Yes by default an "database import" delete all the existing data and reimport the new one, if you want to move just some data you should do and "export database -excludeAll -includeClass=ClassName file.tar.gz"  and after "import database -merge file.tar.gz" for more details have a look to : http://orientdb.com/docs/last/Console-Command-Export.html and http://orientdb.com/docs/last/Console-Command-Import.html

**Comment by HuangKBAaron** [comment]
@tglman many thx! I will try and report status later.

**Comment by HuangKBAaron** [comment]
@tglman，about the script you suggested:
`export database -excludeAll -includeClass=ClassName file.tar.gz`
There are lots of class name out there, is it better to use includeSchema than listing all the classname?

**Comment by HuangKBAaron** [comment]
@tglman @luigidellaquila 
The script given did work PARTIALLY. In my demo db, there are 720 records of v_volume. 
Here is the steps:
1. Export by:
`export database C:\projects\personal\Volkswagen-volume-predict\data\vw-schema-record-index.gz -excludeAll "v_city_cluster v_fuel_type v_pr_vol_output e_has_type v_ev_type v_segment v_pr_vol_input v_body_type e_content_item v_product_type" -includeRecords=true`

2. Added one record of v_volume to the db will be restored to.

3. Import by:
`import database C:\projects\personal\Volkswagen-volume-predict\data\vw-schema-record-index.gz -merge=true`

observed result:
```
Importing database database C:\projects\personal\Volkswagen-volume-predict\data\vw-schema-record-index.gz -merge=true...
Started import of database 'plocal:C:/projects/orientdb-c/databases/Volkswagen-volume-predict' from C:\Users\HUANGK~1\AppData\Local\Temp\Volkswagen-volume-predictimport5202552626653811236vw-schema-record-index.gz...

Importing records...

Started migration of links (-migrateLinks=true). Links are going to be updated according to new RIDs:
- Cluster v_content_3... Completed migration of 6 records in current cluster
- Cluster v_content_2... Completed migration of 6 records in current cluster
- Cluster v_content_1... Completed migration of 8 records in current cluster
- Cluster v_brand_indicator_3... Completed migration of 2 records in current cluster
- Cluster v_brand_indicator_2... Completed migration of 2 records in current cluster
- Cluster v_brand_indicator_1... Completed migration of 2 records in current cluster
- Cluster v_product_type_1... Completed migration of 2 records in current cluster
- Cluster v_product_type_3... Completed migration of 0 records in current cluster
- Cluster v_product_type_2... Completed migration of 0 records in current cluster
- Cluster oschedule... Completed migration of 0 records in current cluster
- Cluster e_in_pr_3... Completed migration of 360 records in current cluster
- Cluster e_in_pr_1... Completed migration of 360 records in current cluster
- Cluster e_in_pr_2... Completed migration of 360 records in current cluster
- Cluster e_content_item... Completed migration of 22 records in current cluster
- Cluster osequence... Completed migration of 0 records in current cluster
- Cluster orole... Completed migration of 6 records in current cluster
- Cluster v_segment_2... Completed migration of 4 records in current cluster
- Cluster v_segment_1... Completed migration of 4 records in current cluster
- Cluster v_city_level_1... Completed migration of 2 records in current cluster
- Cluster v_volume_1... Completed migration of 360 records in current cluster
- Cluster v_volume_2... Completed migration of 360 records in current cluster
- Cluster v_segment_3... Completed migration of 2 records in current cluster
- Cluster v_volume_3... Completed migration of 360 records in current cluster
- Cluster v_city_level_2... Completed migration of 2 records in current cluster
- Cluster v_city_level_3... Completed migration of 2 records in current cluster
- Cluster v_city_level... Completed migration of 4 records in current cluster
- Cluster v_model... Completed migration of 0 records in current cluster
- Cluster _studio_2... Completed migration of 10 records in current cluster
- Cluster _studio_3... Completed migration of 10 records in current cluster
- Cluster default... Completed migration of 0 records in current cluster
- Cluster v_calculation_type_3... Completed migration of 0 records in current cluster
- Cluster v_calculation_type_2... Completed migration of 2 records in current cluster
- Cluster v_calculation_type_1... Completed migration of 2 records in current cluster
- Cluster _studio_1... Completed migration of 10 records in current cluster
- Cluster v_content... Completed migration of 8 records in current cluster
- Cluster e... Completed migration of 0 records in current cluster
- Cluster v_body_type... Completed migration of 4 records in current cluster
- Cluster v... Completed migration of 0 records in current cluster
- Cluster v_ssss_type... Completed migration of 4 records in current cluster
- Cluster v_body_type_3... Completed migration of 2 records in current cluster
- Cluster v_body_type_2... Completed migration of 4 records in current cluster
- Cluster v_calculation_type... Completed migration of 2 records in current cluster
- Cluster v_body_type_1... Completed migration of 4 records in current cluster
- Cluster v_ev_type... Completed migration of 2 records in current cluster
- Cluster v_pr_vol_output... Completed migration of 0 records in current cluster
- Cluster v_ev_type_1... Completed migration of 2 records in current cluster
- Cluster v_ev_type_3... Completed migration of 0 records in current cluster
- Cluster v_ev_type_2... Completed migration of 0 records in current cluster
- Cluster v_pr_vol_input_3... Completed migration of 0 records in current cluster
- Cluster v_pr_vol_input_2... Completed migration of 0 records in current cluster
- Cluster v_pr_vol_input_1... Completed migration of 0 records in current cluster
- Cluster v_pr_vol_input... Completed migration of 0 records in current cluster
- Cluster e_has_type... Completed migration of 2,194 records in current cluster
- Cluster v_2... Completed migration of 0 records in current cluster
- Cluster v_1... Completed migration of 0 records in current cluster
- Cluster v_3... Completed migration of 0 records in current cluster
- Cluster v_ssss_type_1... Completed migration of 4 records in current cluster
- Cluster _studio... Completed migration of 12 records in current cluster
- Cluster v_ssss_type_2... Completed migration of 4 records in current cluster
- Cluster v_ssss_type_3... Completed migration of 2 records in current cluster
- Cluster v_plan_round_3... Completed migration of 0 records in current cluster
- Cluster e_content_item_1... Completed migration of 20 records in current cluster
- Cluster v_plan_round_2... Completed migration of 0 records in current cluster
- Cluster e_content_item_2... Completed migration of 20 records in current cluster
- Cluster e_content_item_3... Completed migration of 20 records in current cluster
- Cluster ofunction... Completed migration of 0 records in current cluster
- Cluster v_plan_round_1... Completed migration of 2 records in current cluster
- Cluster v_city_cluster_2... Completed migration of 2 records in current cluster
- Cluster v_city_cluster_3... Completed migration of 0 records in current cluster
- Cluster v_city_cluster_1... Completed migration of 2 records in current cluster
- Cluster v_city_cluster... Completed migration of 2 records in current cluster
- Cluster e_has_type_3... Completed migration of 2,192 records in current cluster
- Cluster e_has_type_2... Completed migration of 2,192 records in current cluster
- Cluster e_has_type_1... Completed migration of 2,194 records in current cluster
- Cluster v_segment... Completed migration of 4 records in current cluster
- Cluster e_1... Completed migration of 0 records in current cluster
- Cluster e_3... Completed migration of 0 records in current cluster
- Cluster e_2... Completed migration of 0 records in current cluster
- Cluster v_pr_vol_output_1... Completed migration of 0 records in current cluster
- Cluster v_pr_vol_output_2... Completed migration of 0 records in current cluster
- Cluster v_brand_indicator... Completed migration of 2 records in current cluster
- Cluster v_pr_vol_output_3... Completed migration of 0 records in current cluster
- Cluster v_product_type... Completed migration of 2 records in current cluster
- Cluster v_volume... Completed migration of 361 records in current cluster
- Cluster v_model_3... Completed migration of 0 records in current cluster
- Cluster ouser... Completed migration of 6 records in current cluster
- Cluster v_model_1... Completed migration of 0 records in current cluster
- Cluster e_in_pr... Completed migration of 360 records in current cluster
- Cluster v_model_2... Completed migration of 0 records in current cluster
- Cluster v_fuel_type... Completed migration of 2 records in current cluster
- Cluster v_fuel_type_3... Completed migration of 0 records in current cluster
- Cluster v_fuel_type_2... Completed migration of 0 records in current cluster
- Cluster v_fuel_type_1... Completed migration of 2 records in current cluster
- Cluster v_plan_round... Completed migration of 2 records in current cluster
Total links updated: 11,905

Done. Imported 5,954 records in 2.43 secs

Rebuild of stale indexes...
Start rebuild index ouser.nameError on database import happened just before line 0, column 948304
com.orientechnologies.orient.core.storage.ORecordDuplicatedException: Cannot index record #5:3: found duplicated key 'admin' in index 'OUser.name' previously assigned to the record #5:0
        DB name="Volkswagen-volume-predict" INDEX=OUser.name RID=#5:0
        at com.orientechnologies.orient.core.index.OIndexUnique$1.validate(OIndexUnique.java:47)
        at com.orientechnologies.orient.core.index.OIndexUnique$1.validate(OIndexUnique.java:37)
        at com.orientechnologies.orient.core.index.sbtree.local.OSBTree.put(OSBTree.java:873)
        at com.orientechnologies.orient.core.index.sbtree.local.OSBTree.validatedPut(OSBTree.java:267)
        at com.orientechnologies.orient.core.index.engine.OSBTreeIndexEngine.validatedPut(OSBTreeIndexEngine.java:169)
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.doValidatedPutIndexValue(OAbstractPaginatedStorage.java:1953)
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.validatedPutIndexValue(OAbstractPaginatedStorage.java:1939)
        at com.orientechnologies.orient.core.index.OIndexUnique.put(OIndexUnique.java:82)
        at com.orientechnologies.orient.core.index.OIndexUnique.put(OIndexUnique.java:35)
        at com.orientechnologies.orient.core.index.OIndexAbstract.populateIndex(OIndexAbstract.java:944)
        at com.orientechnologies.orient.core.index.OIndexAbstract.indexCluster(OIndexAbstract.java:1044)
        at com.orientechnologies.orient.core.index.OIndexAbstract.fillIndex(OIndexAbstract.java:543)
        at com.orientechnologies.orient.core.index.OIndexAbstract.rebuild(OIndexAbstract.java:504)
        at com.orientechnologies.orient.core.index.OIndexAbstract.rebuild(OIndexAbstract.java:407)
        at com.orientechnologies.orient.core.index.OIndexAbstractDelegate.rebuild(OIndexAbstractDelegate.java:167)
        at com.orientechnologies.orient.core.sql.OCommandExecutorSQLRebuildIndex.execute(OCommandExecutorSQLRebuildIndex.java:105)
        at com.orientechnologies.orient.core.sql.OCommandExecutorSQLDelegate.execute(OCommandExecutorSQLDelegate.java:74)
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.executeCommand(OAbstractPaginatedStorage.java:2578)
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.command(OAbstractPaginatedStorage.java:2524)
        at com.orientechnologies.orient.core.command.OCommandRequestTextAbstract.execute(OCommandRequestTextAbstract.java:69)
        at com.orientechnologies.orient.core.db.tool.ODatabaseImport.rebuildIndexes(ODatabaseImport.java:482)
        at com.orientechnologies.orient.core.db.tool.ODatabaseImport.importDatabase(ODatabaseImport.java:428)
        at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.importDatabase(ONetworkProtocolBinary.java:2915)
        at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.executeRequest(ONetworkProtocolBinary.java:654)
        at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.sessionRequest(ONetworkProtocolBinary.java:337)
        at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.execute(ONetworkProtocolBinary.java:201)
        at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:77)

Error: com.orientechnologies.common.io.OIOException

Error: java.io.EOFException
```
The total record of v_volume became 1441. And the extra record has been deleted.

**Comment by HuangKBAaron** [comment]
@tglman, @luigidellaquila, tried with the real records. it works and produce some ghost records. For example, there a class, v_body_type, has two same records after imported, with different rid, #21:0, #21:2. Tried the following script:
`select count(*) from v_volume LET $body_t=in('e_has_type')[@class='v_body_type'] where $body_t.@rid=21:0`
returned 0 (ZERO)
`select count(*) from v_volume LET $body_t=in('e_has_type')[@class='v_body_type'] where $body_t.@rid=21:2`
returned all v_volumes' record count.
Read from web studio tool, 21:0 does have edge connected
![image](https://user-images.githubusercontent.com/14175239/29513591-6810596c-8698-11e7-9931-fc93b242c5ac.png)
Clicked one of them:
![image](https://user-images.githubusercontent.com/14175239/29513635-85d349fa-8698-11e7-8d5d-4536e4eb5b58.png)
The 21:0 was gone:
![image](https://user-images.githubusercontent.com/14175239/29513749-d02e8b5e-8698-11e7-810f-483447f72385.png)
Tried another edge:
![image](https://user-images.githubusercontent.com/14175239/29513798-f9b6aef2-8698-11e7-9481-36a164d024a9.png)

**Comment by tglman** [comment]
Hi @HuangKBAaron,

Is normal that if you export and import only one class if this reference records of different class this will end up to stale references, the import procedure do not clean stale references, yes is ok to delete this data.

In any case i see that you where able to run the import correctly, closing this.
 
Regards
