### ISSUE TITLE
OConcurrentModificationException in distributed environment.

### ISSUE THREAD

**Issue by FelisChaus** [orientechnologies/orientdb#7657]
## Expected behavior  
Massive update, trying to reset field to NULL. 

## Actual behavior  
OConcurrentModificationException when I am running the snippet below with parameter 'limit' of 1'000'000.

## Steps to reproduce  
```
public class StressTest {
    static String url = "remote:localhost/testdb";
    static String user = "root";
    static String password = "orientdb";
    static int limit = 0;
 
    private void test(final ODatabaseDocumentTx db, int caseID) {
        OSchemaProxy proxy = db.getMetadata().getSchema();
        // 1. Clean up previous test scars.
        if (proxy.getClass("Test") != null) {
            proxy.dropClass("Test");
        }
        // 2. Create test class.
        if (proxy.getClass("Test") == null) {
            proxy.createClass("Test");
            OClass issue = proxy.getClass("Test");
            issue.createProperty("value", OType.STRING);
            proxy.reload();
            System.out.printf("Schema altered.\n");
        }
        // 3. Fulfil test class with random data.
        db.begin();
        for (int i = 0; i < limit; i++) {
            String cmd = "insert into Test set value = uuid()";
            db.command(new OCommandScript("sql", cmd)).execute();
        }
        db.commit();
        // 4. Test update behaviour.
        System.out.printf("Issue test %d/%d.\n", caseID, limit);
        if (caseID == 1) { // Here we fail.
            String cmd = "begin\n";
            cmd += "update Test set value = null\n";
            cmd += "commit";
            db.command(new OCommandScript("sql", cmd)).execute();
        } else { // Here we pass.
            db.begin();
            String cmd = "update Test set value = null";
            db.command(new OCommandScript("sql", cmd)).execute();
            db.commit();
        }
        System.out.printf("Issue test passed.\n");
    }
 
    public static void main(String[] args) {
        Instant first = Instant.now();
        if (4 == args.length) {
            url = args[0];
            user = args[1];
            password = args[2];
            limit = Integer.valueOf(args[3]);
        }
        try {
            ODatabaseDocumentTx db = new ODatabaseDocumentTx(url);
            db.open(user, password);
            try {
                StressTest m = new StressTest();
                m.test(db, 1);
            } finally {
                db.close();
            }
        } catch (final OException e) {
            e.printStackTrace();
        }
        Instant second = Instant.now();
        Duration duration = Duration.between(first, second);
        System.out.printf("Elapsed time %s\n", duration.toString());
    }
}
```

It is not only the case, the others I am trying to reproduce, they are too stochastic. Nevertheless
this one is stable.

We are using enterprise solution as your customers from ctco.lv.

**Comment by lvca** [comment]
@FelisChaus, the exception `OConcurrentModificationException` is normal in OrientDB and concurrency must be handled. In your test where the OConcurrentModificationException is thrown?

**Comment by FelisChaus** [comment]
@lvca, this is the exception raise from the following code:

_String cmd = "begin\n";
cmd += "update Test set value = null\n";
cmd += "commit";
db.command(new OCommandScript("sql", cmd)).execute();_

com.orientechnologies.orient.core.exception.OConcurrentModificationException: Cannot UPDATE the record #13:244329 because the version is not the latest. Probably you are updating an old record or it has been modified by another user (db=v1 your=v2)
DB name="WalletTest"
DB name="WalletTest"
at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
at com.orientechnologies.orient.client.binary.OChannelBinaryAsynchClient.throwSerializedException(OChannelBinaryAsynchClient.java:447)
at com.orientechnologies.orient.client.binary.OChannelBinaryAsynchClient.handleStatus(OChannelBinaryAsynchClient.java:398)
at com.orientechnologies.orient.client.binary.OChannelBinaryAsynchClient.beginResponse(OChannelBinaryAsynchClient.java:280)
at com.orientechnologies.orient.client.binary.OChannelBinaryAsynchClient.beginResponse(OChannelBinaryAsynchClient.java:167)
at com.orientechnologies.orient.client.remote.OStorageRemote.beginResponse(OStorageRemote.java:2338)
at com.orientechnologies.orient.client.remote.OStorageRemote$27.execute(OStorageRemote.java:1202)
at com.orientechnologies.orient.client.remote.OStorageRemote$2.execute(OStorageRemote.java:200)
at com.orientechnologies.orient.client.remote.OStorageRemote.baseNetworkOperation(OStorageRemote.java:245)
at com.orientechnologies.orient.client.remote.OStorageRemote.networkOperationRetry(OStorageRemote.java:197)
at com.orientechnologies.orient.client.remote.OStorageRemote.networkOperation(OStorageRemote.java:208)
at com.orientechnologies.orient.client.remote.OStorageRemote.command(OStorageRemote.java:1178)
at com.orientechnologies.orient.core.command.OCommandRequestTextAbstract.execute(OCommandRequestTextAbstract.java:69)
at lv.ctco.StressTest.test(StressTest.java:46)
at lv.ctco.StressTest.main(StressTest.java:69)
Elapsed time PT45M25.594S
Aug 15, 2017 12:58:36 PM com.orientechnologies.common.log.OLogManager log
INFO: Orient Engine is shutting down...

**Comment by FelisChaus** [comment]
And no one except me was connected to the database.

**Comment by FelisChaus** [comment]
Hope the following could help. I faced this bug on version 2.1.16 and 2.1.25 and the _limit_ when exception raised with database corruption was only 19771 records. On 2.1.16 and 2.1.25 crash could be steadily reproduced on OrientDB single instance on mac. That is because I repeated run on 2.2.25.

**Comment by lvca** [comment]
Could you please try to execute this?

```
String cmd = "begin\n"; cmd += "update Test set value = null\n"; cmd += "commit retry 20"; db.command(new OCommandScript("sql", cmd)).execute();
```

**Comment by FelisChaus** [comment]
The same result:

com.orientechnologies.orient.core.exception.ODatabaseException: Database 'plocal:/var/lib/orientdb/WalletTest' is closed
DB name="WalletTest"
DB name="WalletTest"
at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
at com.orientechnologies.orient.client.binary.OChannelBinaryAsynchClient.throwSerializedException(OChannelBinaryAsynchClient.java:447)
at com.orientechnologies.orient.client.binary.OChannelBinaryAsynchClient.handleStatus(OChannelBinaryAsynchClient.java:398)
at com.orientechnologies.orient.client.binary.OChannelBinaryAsynchClient.beginResponse(OChannelBinaryAsynchClient.java:280)
at com.orientechnologies.orient.client.binary.OChannelBinaryAsynchClient.beginResponse(OChannelBinaryAsynchClient.java:167)
at com.orientechnologies.orient.client.remote.OStorageRemote.beginResponse(OStorageRemote.java:2338)
at com.orientechnologies.orient.client.remote.OStorageRemote$27.execute(OStorageRemote.java:1202)
at com.orientechnologies.orient.client.remote.OStorageRemote$2.execute(OStorageRemote.java:200)
at com.orientechnologies.orient.client.remote.OStorageRemote.baseNetworkOperation(OStorageRemote.java:245)
at com.orientechnologies.orient.client.remote.OStorageRemote.networkOperationRetry(OStorageRemote.java:197)
at com.orientechnologies.orient.client.remote.OStorageRemote.networkOperation(OStorageRemote.java:208)
at com.orientechnologies.orient.client.remote.OStorageRemote.command(OStorageRemote.java:1178)
at com.orientechnologies.orient.core.command.OCommandRequestTextAbstract.execute(OCommandRequestTextAbstract.java:69)
at lv.ctco.StressTest.test(StressTest.java:45)
at lv.ctco.StressTest.main(StressTest.java:75)

Elapsed time PT1H4.202S

**Comment by FelisChaus** [comment]
On the first node we got the following server side exception:

Exception `4467D280` in storage `WalletTest`
com.orientechnologies.orient.core.exception.ODatabaseException: Database 'plocal:/var/lib/orientdb/WalletTest' is closed
DB name="WalletTest"
at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.checkOpeness(ODatabaseDocumentTx.java:3145)
at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.getMetadata(ODatabaseDocumentTx.java:837)
at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.getMetadata(ODatabaseDocumentTx.java:102)
at com.orientechnologies.orient.core.record.impl.ODocument.getGlobalPropertyById(ODocument.java:2194)
at com.orientechnologies.orient.core.record.impl.ODocumentInternal.getGlobalPropertyById(ODocumentInternal.java:64)
at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinaryV0.getGlobalProperty(ORecordSerializerBinaryV0.java:515)
at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinaryV0.deserialize(ORecordSerializerBinaryV0.java:259)
at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinary.fromStream(ORecordSerializerBinary.java:80)
at com.orientechnologies.orient.core.record.impl.ODocument.deserializeFields(ODocument.java:1854)
at com.orientechnologies.orient.core.record.impl.ODocument.checkForFields(ODocument.java:2623)
at com.orientechnologies.orient.core.record.impl.ODocument.validate(ODocument.java:2027)
at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.commit(OAbstractPaginatedStorage.java:1598)
at com.orientechnologies.orient.server.distributed.impl.ODistributedStorage.commit(ODistributedStorage.java:1389)
at com.orientechnologies.orient.server.distributed.impl.ODistributedTransactionManager$1.call(ODistributedTransactionManager.java:117)
at com.orientechnologies.orient.core.db.OScenarioThreadLocal.executeAsDistributed(OScenarioThreadLocal.java:70)
at com.orientechnologies.orient.server.distributed.impl.ODistributedTransactionManager.commit(ODistributedTransactionManager.java:114)
at com.orientechnologies.orient.server.distributed.impl.ODistributedStorage.commit(ODistributedStorage.java:1432)
at com.orientechnologies.orient.core.tx.OTransactionOptimistic.doCommit(OTransactionOptimistic.java:541)
at com.orientechnologies.orient.core.tx.OTransactionOptimistic.commit(OTransactionOptimistic.java:99)
at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.commit(ODatabaseDocumentTx.java:2891)
at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.commit(ODatabaseDocumentTx.java:2860)
at com.orientechnologies.orient.core.command.script.OCommandExecutorScript.executeSQLScript(OCommandExecutorScript.java:325)
at com.orientechnologies.orient.core.command.script.OCommandExecutorScript.executeSQL(OCommandExecutorScript.java:197)
at com.orientechnologies.orient.core.command.script.OCommandExecutorScript.executeInContext(OCommandExecutorScript.java:104)
at com.orientechnologies.orient.core.command.script.OCommandExecutorScript.execute(OCommandExecutorScript.java:88)
at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.executeCommand(OAbstractPaginatedStorage.java:3208)
at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.command(OAbstractPaginatedStorage.java:3146)
at com.orientechnologies.orient.server.distributed.impl.ODistributedStorage.command(ODistributedStorage.java:261)
at com.orientechnologies.orient.core.command.OCommandRequestTextAbstract.execute(OCommandRequestTextAbstract.java:69)
at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.command(ONetworkProtocolBinary.java:1529)
at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.executeRequest(ONetworkProtocolBinary.java:646)
at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.sessionRequest(ONetworkProtocolBinary.java:384)
at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.execute(ONetworkProtocolBinary.java:207)
at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:77)

**Comment by FelisChaus** [comment]
On the second and third nodes:

2017-08-16 10:40:31:639 WARNI [n2]->[n3] Server 'n3' did not respond to the gossip message (db=WalletTest, timeout=10000ms), but cannot be set OFFLINE by configuration [OClusterHealthChecker]

**Comment by FelisChaus** [comment]
@lvca, we will repeat tests using 2.2.26. Seems and hope new Hazelcast should resolve the issue.

**Comment by lvca** [comment]
@FelisChaus thanks, with 2.2.26 we fixed many issues like that.

**Comment by FelisChaus** [comment]
@Ivca, please do not close the issue. We are in progress with upgraded JVM and playing with OrientDB parameters. Next week I am preparing a full report.

Have a nice weekend.

**Comment by lvca** [comment]
Cool, waiting for your feedback. Have a nice weekend too.

**Comment by FelisChaus** [comment]
Hi,

We updated JMV version from 1.8.0_72 to 1.8.0_144.
OrientDB  2.2.26.
Sources attached.

In master and 2 slaves configuration we successfully passes all 3 tests.
In a--master configuration we still got the exception and non-ACID behaviour on rollback.
Please see details in issue7657.txt attached to the comment.

Thank you in advance,
Boris

[issue7657.txt](https://github.com/orientechnologies/orientdb/files/1274990/issue7657.txt)



[OrientDBTest.zip](https://github.com/orientechnologies/orientdb/files/1274968/OrientDBTest.zip)

**Comment by FelisChaus** [comment]
The behavior became more stable after upgrading to the 2.2.31
