### ISSUE TITLE
bug in search_class lucene - nullpointer 

### ISSUE THREAD

**Issue by publicocean0** [orientechnologies/orientdb#7658]
### Java Version: 7  

com.orientechnologies.orient.core.exception.OCommandExecutionException: Error on execution of command: sql.select  from S  where search_class('account:"PZVLQAB8DMKPU5LZ40GQLM21F"') = true
	DB name="abc"
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.executeCommand(OAbstractPaginatedStorage.java:3246)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.command(OAbstractPaginatedStorage.java:3162)
	at com.orientechnologies.orient.core.command.OCommandRequestTextAbstract.execute(OCommandRequestTextAbstract.java:68)
	at com.orientechnologies.orient.server.OConnectionBinaryExecutor.executeCommand(OConnectionBinaryExecutor.java:571)
	at com.orientechnologies.orient.client.remote.message.OCommandRequest.execute(OCommandRequest.java:103)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.sessionRequest(ONetworkProtocolBinary.java:278)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.execute(ONetworkProtocolBinary.java:184)
	at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:77)
Caused by: java.lang.NullPointerException
	at com.orientechnologies.lucene.functions.OLuceneSearchOnClassFunction.searchForIndex(OLuceneSearchOnClassFunction.java:147)
	at com.orientechnologies.lucene.functions.OLuceneSearchOnClassFunction.searchForIndex(OLuceneSearchOnClassFunction.java:143)
	at com.orientechnologies.lucene.functions.OLuceneSearchFunctionTemplate.estimate(OLuceneSearchFunctionTemplate.java:44)
	at com.orientechnologies.orient.core.sql.parser.OFunctionCall.estimateIndexedFunction(OFunctionCall.java:170)
	at com.orientechnologies.orient.core.sql.parser.OLevelZeroIdentifier.estimateIndexedFunction(OLevelZeroIdentifier.java:80)
	at com.orientechnologies.orient.core.sql.parser.OBaseIdentifier.estimateIndexedFunction(OBaseIdentifier.java:81)
	at com.orientechnologies.orient.core.sql.parser.OBaseExpression.estimateIndexedFunction(OBaseExpression.java:145)
	at com.orientechnologies.orient.core.sql.parser.OExpression.estimateIndexedFunction(OExpression.java:282)
	at com.orientechnologies.orient.core.sql.parser.OBinaryCondition.estimateIndexed(OBinaryCondition.java:99)
	at com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.tryIndexedFunctions(OCommandExecutorSQLSelect.java:2283)
	at com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.searchForIndexes(OCommandExecutorSQLSelect.java:2075)
	at com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.searchInClasses(OCommandExecutorSQLSelect.java:995)
	at com.orientechnologies.orient.core.sql.OCommandExecutorSQLResultsetAbstract.assignTarget(OCommandExecutorSQLResultsetAbstract.java:202)
	at com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.assignTarget(OCommandExecutorSQLSelect.java:515)
	at com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.executeSearch(OCommandExecutorSQLSelect.java:497)
	at com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.execute(OCommandExecutorSQLSelect.java:473)
	at com.orientechnologies.orient.core.sql.OCommandExecutorSQLDelegate.execute(OCommandExecutorSQLDelegate.java:74)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.executeCommand(OAbstractPaginatedStorage.java:3225)

**Comment by publicocean0** [comment]
same query works in console

**Comment by publicocean0** [comment]
null pointer in this line 

 OMetadata dbMetadata = ctx.getDatabase().activateOnCurrentThread().getMetadata();

**Comment by tglman** [comment]
hi @publicocean0,

I see you are using the legacy API `command(new OCommandSql("..."))` or `query(new OSQLSyncQuery("..")` could you try to use the new API `command("...")` or `query("...")`, the new API will use the new executor, that probably don't have this problem.

Regards

**Comment by publicocean0** [comment]
yes but i m using object db , not document db

**Comment by publicocean0** [comment]
i m in debug in orientdb server :   

ctx.getDatabase() is null

**Comment by publicocean0** [comment]
default OResultSet command(String query, Object... args) throws OCommandSQLParsingException, OCommandExecutionException {
    throw new UnsupportedOperationException();
  }

**Comment by tglman** [comment]
hi @publicocean0,

Yes In object you can just use the old one, so we will investigate  what is it and try to fix it.

Regards

**Comment by publicocean0** [comment]
ok thanks . Else in my side if you implement unsupported api 
i could converts all my methods with  stream().collect(Collectors.toList()); i think

**Comment by tglman** [comment]
Hi @publicocean0,

The object now delegate to the underlying layer for query, so this should work, closing.
