### ISSUE TITLE
OutOfMemoryError: Direct buffer memory. Build unique hash index on big table

### ISSUE THREAD

**Issue by zlfsimon** [orientechnologies/orientdb#7665]
## Actual behavior  
`/bin/java -d64 -server -XX:+UseG1GC -Xms4G -Xmx16G -Djna.nosys=true -Dmemory.directMemory.trackMode=true -XX:+HeapDumpOnOutOfMemoryError -XX:MaxDirectMemorySize=10g -Djava.awt.headless=true -Dfile.encoding=UTF8 -Drhino.opt.level=9 -Djava.util.logging.config.file=/gp/data/arangodb/orientdb-community-2.2.26-SNAPSHOT/config/orientdb-server-log.properties -Dorientdb.config.file=/gp/data/arangodb/orientdb-community-2.2.26-SNAPSHOT/config/orientdb-server-config.xml -Dorientdb.www.path=/gp/data/arangodb/orientdb-community-2.2.26-SNAPSHOT/www -Dorientdb.build.number=2.2.x@r72a35a4bb42c4ca33272e7a59ad4c7a1d3ee859d; 2017-08-02 13:50:43+0000 -cp /gp/data/arangodb/orientdb-community-2.2.26-SNAPSHOT/lib/orientdb-server-2.2.25.jar:/gp/data/arangodb/orientdb-community-2.2.26-SNAPSHOT/lib/*:/gp/data/arangodb/orientdb-community-2.2.26-SNAPSHOT/plugins/* com.orientechnologies.orient.server.OServerMa`

```
2017-08-17 12:03:18:528 INFO  {db=test} --> 79.34% progress, 91,635,575 indexed so far (17,821 items/sec) [OIndexRebuildOutputListener]
2017-08-17 12:03:28:529 INFO  {db=test} --> 79.50% progress, 91,812,618 indexed so far (17,704 items/sec) [OIndexRebuildOutputListener]
2017-08-17 12:03:38:530 INFO  {db=test} --> 79.65% progress, 91,988,180 indexed so far (17,556 items/sec) [OIndexRebuildOutputListener]$ANSI{green {db=test}} Exception `549F3242` in storage `test`
java.lang.OutOfMemoryError: Direct buffer memory
        at java.nio.Bits.reserveMemory(Bits.java:693)
        at java.nio.DirectByteBuffer.<init>(DirectByteBuffer.java:123)
        at java.nio.ByteBuffer.allocateDirect(ByteBuffer.java:311)
        at com.orientechnologies.common.directmemory.OByteBufferPool.allocateBuffer(OByteBufferPool.java:335)
        at com.orientechnologies.common.directmemory.OByteBufferPool.acquireDirect(OByteBufferPool.java:286)
        at com.orientechnologies.orient.core.storage.cache.local.OWOWCache.loadFileContent(OWOWCache.java:1454)
        at com.orientechnologies.orient.core.storage.cache.local.OWOWCache.load(OWOWCache.java:701)
        at com.orientechnologies.orient.core.storage.cache.local.twoq.O2QCache.updateCache(O2QCache.java:1147)
        at com.orientechnologies.orient.core.storage.cache.local.twoq.O2QCache.doLoad(O2QCache.java:349)
        at com.orientechnologies.orient.core.storage.cache.local.twoq.O2QCache.load(O2QCache.java:294)
        at com.orientechnologies.orient.core.storage.cache.pages.OLruPageCache.loadPage(OLruPageCache.java:71)
        at com.orientechnologies.orient.core.storage.impl.local.paginated.atomicoperations.OAtomicOperation.loadPage(OAtomicOperation.java:128)
        at com.orientechnologies.orient.core.storage.impl.local.paginated.base.ODurableComponent.loadPage(ODurableComponent.java:150)
        at com.orientechnologies.orient.core.storage.impl.local.paginated.base.ODurableComponent.loadPage(ODurableComponent.java:142)
        at com.orientechnologies.orient.core.index.hashindex.local.OLocalHashTable.doPut(OLocalHashTable.java:1530)
        at com.orientechnologies.orient.core.index.hashindex.local.OLocalHashTable.put(OLocalHashTable.java:1459)
        at com.orientechnologies.orient.core.index.hashindex.local.OLocalHashTable.validatedPut(OLocalHashTable.java:412)
        at com.orientechnologies.orient.core.index.engine.OHashTableIndexEngine.validatedPut(OHashTableIndexEngine.java:156)
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.doValidatedPutIndexValue(OAbstractPaginatedStorage.java:2357)
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.validatedPutIndexValue(OAbstractPaginatedStorage.java:2336)
        at com.orientechnologies.orient.core.index.OIndexUnique.put(OIndexUnique.java:82)
        at com.orientechnologies.orient.core.index.OIndexUnique.put(OIndexUnique.java:35)
        at com.orientechnologies.orient.core.index.OIndexAbstract.populateIndex(OIndexAbstract.java:940)
        at com.orientechnologies.orient.core.index.OIndexAbstract.indexCluster(OIndexAbstract.java:1040)
        at com.orientechnologies.orient.core.index.OIndexAbstract.fillIndex(OIndexAbstract.java:539)
        at com.orientechnologies.orient.core.index.OIndexAbstract.create(OIndexAbstract.java:250)
        at com.orientechnologies.orient.core.index.OIndexOneValue.create(OIndexOneValue.java:129)
        at com.orientechnologies.orient.core.index.OIndexOneValue.create(OIndexOneValue.java:40)
        at com.orientechnologies.orient.core.index.OIndexManagerShared.createIndex(OIndexManagerShared.java:169)
        at com.orientechnologies.orient.core.index.OIndexManagerProxy.createIndex(OIndexManagerProxy.java:87)
        at com.orientechnologies.orient.core.metadata.schema.OClassImpl.createIndex(OClassImpl.java:1897)
        at com.orientechnologies.orient.core.sql.OCommandExecutorSQLCreateIndex.execute(OCommandExecutorSQLCreateIndex.java:269)
        at com.orientechnologies.orient.core.sql.OCommandExecutorSQLDelegate.execute(OCommandExecutorSQLDelegate.java:74)
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.executeCommand(OAbstractPaginatedStorage.java:3213)
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.command(OAbstractPaginatedStorage.java:3151)
        at com.orientechnologies.orient.core.command.OCommandRequestTextAbstract.execute(OCommandRequestTextAbstract.java:69)
        at com.orientechnologies.orient.server.network.protocol.http.command.post.OServerCommandPostCommand.execute(OServerCommandPostCommand.java:106)
        at com.orientechnologies.orient.graph.server.command.OServerCommandPostCommandGraph.execute(OServerCommandPostCommandGraph.java:37)
        at com.orientechnologies.orient.server.network.protocol.http.ONetworkProtocolHttpAbstract.service(ONetworkProtocolHttpAbstract.java:173)
        at com.orientechnologies.orient.server.network.protocol.http.ONetworkProtocolHttpAbstract.execute(ONetworkProtocolHttpAbstract.java:625)
        at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:77)
$ANSI{green {db=test}} Exception `549F3242` in storage `test`
java.lang.OutOfMemoryError: Direct buffer memory
        at java.nio.Bits.reserveMemory(Bits.java:693)
        at java.nio.DirectByteBuffer.<init>(DirectByteBuffer.java:123)
        at java.nio.ByteBuffer.allocateDirect(ByteBuffer.java:311)
        at com.orientechnologies.common.directmemory.OByteBufferPool.allocateBuffer(OByteBufferPool.java:335)
        at com.orientechnologies.common.directmemory.OByteBufferPool.acquireDirect(OByteBufferPool.java:286)
        at com.orientechnologies.orient.core.storage.cache.local.OWOWCache.loadFileContent(OWOWCache.java:1454)
        at com.orientechnologies.orient.core.storage.cache.local.OWOWCache.load(OWOWCache.java:701)
        at com.orientechnologies.orient.core.storage.cache.local.twoq.O2QCache.updateCache(O2QCache.java:1147)
        at com.orientechnologies.orient.core.storage.cache.local.twoq.O2QCache.doLoad(O2QCache.java:349)
        at com.orientechnologies.orient.core.storage.cache.local.twoq.O2QCache.load(O2QCache.java:294)
        at com.orientechnologies.orient.core.storage.cache.pages.OLruPageCache.loadPage(OLruPageCache.java:71)
        at com.orientechnologies.orient.core.storage.impl.local.paginated.atomicoperations.OAtomicOperation.loadPage(OAtomicOperation.java:128)
        at com.orientechnologies.orient.core.storage.impl.local.paginated.base.ODurableComponent.loadPage(ODurableComponent.java:150)
        at com.orientechnologies.orient.core.storage.impl.local.paginated.base.ODurableComponent.loadPage(ODurableComponent.java:142)
        at com.orientechnologies.orient.core.index.hashindex.local.OLocalHashTable.doPut(OLocalHashTable.java:1530)
        at com.orientechnologies.orient.core.index.hashindex.local.OLocalHashTable.put(OLocalHashTable.java:1459)
        at com.orientechnologies.orient.core.index.hashindex.local.OLocalHashTable.validatedPut(OLocalHashTable.java:412)
        at com.orientechnologies.orient.core.index.engine.OHashTableIndexEngine.validatedPut(OHashTableIndexEngine.java:156)
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.doValidatedPutIndexValue(OAbstractPaginatedStorage.java:2357)
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.validatedPutIndexValue(OAbstractPaginatedStorage.java:2336)
        at com.orientechnologies.orient.core.index.OIndexUnique.put(OIndexUnique.java:82)
        at com.orientechnologies.orient.core.index.OIndexUnique.put(OIndexUnique.java:35)
        at com.orientechnologies.orient.core.index.OIndexAbstract.populateIndex(OIndexAbstract.java:940)
        at com.orientechnologies.orient.core.index.OIndexAbstract.indexCluster(OIndexAbstract.java:1040)
        at com.orientechnologies.orient.core.index.OIndexAbstract.fillIndex(OIndexAbstract.java:539)
        at com.orientechnologies.orient.core.index.OIndexAbstract.create(OIndexAbstract.java:250)
        at com.orientechnologies.orient.core.index.OIndexOneValue.create(OIndexOneValue.java:129)
        at com.orientechnologies.orient.core.index.OIndexOneValue.create(OIndexOneValue.java:40)
        at com.orientechnologies.orient.core.index.OIndexManagerShared.createIndex(OIndexManagerShared.java:169)
        at com.orientechnologies.orient.core.index.OIndexManagerProxy.createIndex(OIndexManagerProxy.java:87)
        at com.orientechnologies.orient.core.metadata.schema.OClassImpl.createIndex(OClassImpl.java:1897)
        at com.orientechnologies.orient.core.sql.OCommandExecutorSQLCreateIndex.execute(OCommandExecutorSQLCreateIndex.java:269)
        at com.orientechnologies.orient.core.sql.OCommandExecutorSQLDelegate.execute(OCommandExecutorSQLDelegate.java:74)
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.executeCommand(OAbstractPaginatedStorage.java:3213)
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.command(OAbstractPaginatedStorage.java:3151)
        at com.orientechnologies.orient.core.command.OCommandRequestTextAbstract.execute(OCommandRequestTextAbstract.java:69)
        at com.orientechnologies.orient.server.network.protocol.http.command.post.OServerCommandPostCommand.execute(OServerCommandPostCommand.java:106)
        at com.orientechnologies.orient.graph.server.command.OServerCommandPostCommandGraph.execute(OServerCommandPostCommandGraph.java:37)
        at com.orientechnologies.orient.server.network.protocol.http.ONetworkProtocolHttpAbstract.service(ONetworkProtocolHttpAbstract.java:173)
        at com.orientechnologies.orient.server.network.protocol.http.ONetworkProtocolHttpAbstract.execute(ONetworkProtocolHttpAbstract.java:625)
        at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:77)
$ANSI{green {db=test}} Exception `549F3242` in storage `test`
java.lang.OutOfMemoryError: Direct buffer memory
        at java.nio.Bits.reserveMemory(Bits.java:693)
        at java.nio.DirectByteBuffer.<init>(DirectByteBuffer.java:123)
        at java.nio.ByteBuffer.allocateDirect(ByteBuffer.java:311)
        at com.orientechnologies.common.directmemory.OByteBufferPool.allocateBuffer(OByteBufferPool.java:335)
        at com.orientechnologies.common.directmemory.OByteBufferPool.acquireDirect(OByteBufferPool.java:286)
        at com.orientechnologies.orient.core.storage.cache.local.OWOWCache.loadFileContent(OWOWCache.java:1454)
        at com.orientechnologies.orient.core.storage.cache.local.OWOWCache.load(OWOWCache.java:701)
        at com.orientechnologies.orient.core.storage.cache.local.twoq.O2QCache.updateCache(O2QCache.java:1147)
        at com.orientechnologies.orient.core.storage.cache.local.twoq.O2QCache.doLoad(O2QCache.java:349)
        at com.orientechnologies.orient.core.storage.cache.local.twoq.O2QCache.load(O2QCache.java:294)
        at com.orientechnologies.orient.core.storage.cache.pages.OLruPageCache.loadPage(OLruPageCache.java:71)
        at com.orientechnologies.orient.core.storage.impl.local.paginated.atomicoperations.OAtomicOperation.loadPage(OAtomicOperation.java:128)
        at com.orientechnologies.orient.core.storage.impl.local.paginated.base.ODurableComponent.loadPage(ODurableComponent.java:150)
        at com.orientechnologies.orient.core.storage.impl.local.paginated.base.ODurableComponent.loadPage(ODurableComponent.java:142)
        at com.orientechnologies.orient.core.index.hashindex.local.OLocalHashTable.doPut(OLocalHashTable.java:1530)
        at com.orientechnologies.orient.core.index.hashindex.local.OLocalHashTable.put(OLocalHashTable.java:1459)
        at com.orientechnologies.orient.core.index.hashindex.local.OLocalHashTable.validatedPut(OLocalHashTable.java:412)
        at com.orientechnologies.orient.core.index.engine.OHashTableIndexEngine.validatedPut(OHashTableIndexEngine.java:156)
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.doValidatedPutIndexValue(OAbstractPaginatedStorage.java:2357)
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.validatedPutIndexValue(OAbstractPaginatedStorage.java:2336)
        at com.orientechnologies.orient.core.index.OIndexUnique.put(OIndexUnique.java:82)
        at com.orientechnologies.orient.core.index.OIndexUnique.put(OIndexUnique.java:35)
        at com.orientechnologies.orient.core.index.OIndexAbstract.populateIndex(OIndexAbstract.java:940)
        at com.orientechnologies.orient.core.index.OIndexAbstract.indexCluster(OIndexAbstract.java:1040)
        at com.orientechnologies.orient.core.index.OIndexAbstract.fillIndex(OIndexAbstract.java:539)
        at com.orientechnologies.orient.core.index.OIndexAbstract.create(OIndexAbstract.java:250)
        at com.orientechnologies.orient.core.index.OIndexOneValue.create(OIndexOneValue.java:129)
        at com.orientechnologies.orient.core.index.OIndexOneValue.create(OIndexOneValue.java:40)
        at com.orientechnologies.orient.core.index.OIndexManagerShared.createIndex(OIndexManagerShared.java:169)
        at com.orientechnologies.orient.core.index.OIndexManagerProxy.createIndex(OIndexManagerProxy.java:87)
        at com.orientechnologies.orient.core.metadata.schema.OClassImpl.createIndex(OClassImpl.java:1897)
        at com.orientechnologies.orient.core.sql.OCommandExecutorSQLCreateIndex.execute(OCommandExecutorSQLCreateIndex.java:269)
        at com.orientechnologies.orient.core.sql.OCommandExecutorSQLDelegate.execute(OCommandExecutorSQLDelegate.java:74)
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.executeCommand(OAbstractPaginatedStorage.java:3213)
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.command(OAbstractPaginatedStorage.java:3151)
        at com.orientechnologies.orient.core.command.OCommandRequestTextAbstract.execute(OCommandRequestTextAbstract.java:69)
        at com.orientechnologies.orient.server.network.protocol.http.command.post.OServerCommandPostCommand.execute(OServerCommandPostCommand.java:106)
        at com.orientechnologies.orient.graph.server.command.OServerCommandPostCommandGraph.execute(OServerCommandPostCommandGraph.java:37)
        at com.orientechnologies.orient.server.network.protocol.http.ONetworkProtocolHttpAbstract.service(ONetworkProtocolHttpAbstract.java:173)
        at com.orientechnologies.orient.server.network.protocol.http.ONetworkProtocolHttpAbstract.execute(ONetworkProtocolHttpAbstract.java:625)
        at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:77)

2017-08-17 12:05:14:339 INFO  Database 'GratefulDeadConcerts' uses 8,694MB/10,238MB of DISKCACHE memory, while Heap is not completely used (usedHeap=4096MB maxHeap=16384MB). To improve performance set maxHeap to 4915MB and DISKCACHE to 21706MB [OAbstractProfiler$MemoryChecker]
2017-08-17 12:05:14:339 INFO  -> Open server.sh (or server.bat on Windows) and change the following variables: 1) MAXHEAP=-Xmx4915M 2) MAXDISKCACHE=21706 [OAbstractProfiler$MemoryChecker]  

## Steps to reproduce  
```
<add here>

**Comment by laa** [comment]
HI @zlfsimon could you send full log as a separate gist, please do not insert it directly inside issue since the server start?

**Comment by zlfsimon** [comment]
Pls see the below attachment:
[orient-server.log.1.zip](https://github.com/orientechnologies/orientdb/files/1230404/orient-server.log.1.zip)

**Comment by zlfsimon** [comment]
BTW, I find all operation will been blocked during index built section, event open a studio page "http://192.168.1.53:2480/studio/index.html#/database/test/schema" or connect a new console. 
does it means create index will lock whole db?

**Comment by laa** [comment]
@zlfsimon yes, during the index rebuild/creation you can not use DB because it cause retrieval of incorrect results during query processing. About your main issue, I will provide you with patched build today, to understand the reason of your problem.

**Comment by zlfsimon** [comment]
@laa  is there some recommend threshold for orientdb, such as the max records of vertex or edge for a single machine, or some benchmark for  huge class (table)

**Comment by laa** [comment]
@zlfsimon it highly depends on the character of the load which you will perform on this database and law of data distribution. In generally DB size on disk should be not more than 4 times bigger than the size of disk cache. But again, you know saying "There are lies, there are dirty lies and there are benchmarks" so I do suggest you make own benchmarks which will reflect you load and data distribution.

**Comment by laa** [comment]
@zlfsimon could you try this build https://drive.google.com/file/d/0B2oZq2xVp841VWlFSkFMRHhpeFU/view?usp=sharing

**Comment by laa** [comment]
@zlfsimon did you have a chance to try new build?

**Comment by zlfsimon** [comment]
@laa  It works fine in this build, thanks very much

**Comment by laa** [comment]
@zlfsimon thank you for feedback. @santo-it for release notes: "In previous versions of OrientDB, because of number overflow, some times size of direct memory chunk which has to be allocated was calculated incorrectly. That is fixed in new version. "
