### ISSUE TITLE
OPaginatedCluster.deleteRecord null(OrientDB-2.1.11)

### ISSUE THREAD

**Issue by BaarathiNMS** [orientechnologies/orientdb#7669]
ERROR [2017-08-18T14:06:59,133] : [InventoryDataPersisterMaster_MajorEventInventoryDataBuilder] : MajorEventInventoryWriter: ():
com.orientechnologies.orient.core.exception.OStorageException: null
        at com.orientechnologies.orient.core.storage.impl.local.paginated.OPaginatedCluster.deleteRecord(OPaginatedCluster.java:705) ~[orientdb-core-2.1.11.jar:2.1.11]
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.doCreateRecord(OAbstractPaginatedStorage.java:1955) ~[orientdb-core-2.1.11.jar
:2.1.11]
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.createRecord(OAbstractPaginatedStorage.java:743) ~[orientdb-core-2.1.11.jar:2.
1.11]
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.executeSaveRecord(ODatabaseDocumentTx.java:1999) ~[orientdb-core-2.1.11.jar:2.1.11]
        at com.orientechnologies.orient.core.tx.OTransactionOptimistic.addRecord(OTransactionOptimistic.java:432) ~[orientdb-core-2.1.11.jar:2.1.11]
        at com.orientechnologies.orient.core.tx.OTransactionOptimistic.saveRecord(OTransactionOptimistic.java:363) ~[orientdb-core-2.1.11.jar:2.1.11]
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.save(ODatabaseDocumentTx.java:2514) ~[orientdb-core-2.1.11.jar:2.1.11]
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.save(ODatabaseDocumentTx.java:2444) ~[orientdb-core-2.1.11.jar:2.1.11]
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.save(ODatabaseDocumentTx.java:121) ~[orientdb-core-2.1.11.jar:2.1.11]
        at com.orientechnologies.orient.core.record.ORecordAbstract.save(ORecordAbstract.java:287) ~[orientdb-core-2.1.11.jar:2.1.11]
        at com.orientechnologies.orient.core.record.ORecordAbstract.save(ORecordAbstract.java:279) ~[orientdb-core-2.1.11.jar:2.1.11]
        at com.orientechnologies.orient.core.record.ORecordAbstract.save(ORecordAbstract.java:48) ~[orientdb-core-2.1.11.jar:2.1.11]
        at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinaryV0.recursiveLinkSave(ORecordSerializerBinaryV0.java:675) ~[or
ientdb-core-2.1.11.jar:2.1.11]
        at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinaryV0.writeOptimizedLink(ORecordSerializerBinaryV0.java:689) ~[o
rientdb-core-2.1.11.jar:2.1.11]
        at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinaryV0.writeSingleValue(ORecordSerializerBinaryV0.java:574) ~[ori
entdb-core-2.1.11.jar:2.1.11]
        at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinaryV0.serialize(ORecordSerializerBinaryV0.java:260) ~[orientdb-c
ore-2.1.11.jar:2.1.11]
        at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinary.toStream(ORecordSerializerBinary.java:105) ~[orientdb-core-2
.1.11.jar:2.1.11]
        at com.orientechnologies.orient.core.record.impl.ODocument.toStream(ODocument.java:2296) ~[orientdb-core-2.1.11.jar:2.1.11]
        at com.orientechnologies.orient.core.record.impl.ODocument.toStream(ODocument.java:671) ~[orientdb-core-2.1.11.jar:2.1.11]
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.commitEntry(OAbstractPaginatedStorage.java:2446) ~[orientdb-core-2.1.11.jar:2.
1.11]
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.commit(OAbstractPaginatedStorage.java:1181) ~[orientdb-core-2.1.11.jar:2.1.11]
        at com.orientechnologies.orient.core.tx.OTransactionOptimistic.doCommit(OTransactionOptimistic.java:606) ~[orientdb-core-2.1.11.jar:2.1.11]
        at com.orientechnologies.orient.core.tx.OTransactionOptimistic.commit(OTransactionOptimistic.java:156) ~[orientdb-core-2.1.11.jar:2.1.11]
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.commit(ODatabaseDocumentTx.java:2689) ~[orientdb-core-2.1.11.jar:2.1.11]
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.commit(ODatabaseDocumentTx.java:2658) ~[orientdb-core-2.1.11.jar:2.1.11]
at in.co.nmsworks.documenttdb.db.DocDB.commit(DocDB.java:645) ~[cygnetfc.jar:?]
        at in.co.nmsworks.cygnet.telecom.fault.rcasia.majorevent.inventory.persister.MajorEventInventoryWriter.addOrUpdateCircuitOrSNCTrees(MajorEventInventoryWriter.java:101) ~[cygnet-otnms.jar:?]
        at in.co.nmsworks.cygnet.telecom.fault.rcasia.majorevent.inventory.persister.MajorEventInventoryDataPersister.doWorkForUpdate(MajorEventInventoryDataPersister.java:76) ~[cygnet-otnms.jar:?]
        at in.co.nmsworks.cygnet.telecom.fault.rcasia.inventory.queue.InventoryDataPersisterMaster.run(InventoryDataPersisterMaster.java:95) ~[cygnet-otnms.jar:?]
        at java.lang.Thread.run(Thread.java:745) [?:1.7.0_71]
Caused by: com.orientechnologies.orient.core.storage.impl.local.paginated.atomicoperations.ONestedRollbackException: Atomic operation was rolled back by internal component, exception which caused this rollback is :
com.orientechnologies.orient.core.exception.OStorageException
        at com.orientechnologies.orient.core.storage.impl.local.paginated.OPaginatedCluster.createRecord(OPaginatedCluster.java:434)
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.doCreateRecord(OAbstractPaginatedStorage.java:1938)
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.createRecord(OAbstractPaginatedStorage.java:743)
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.executeSaveRecord(ODatabaseDocumentTx.java:1999)
        at com.orientechnologies.orient.core.tx.OTransactionOptimistic.addRecord(OTransactionOptimistic.java:432)
        at com.orientechnologies.orient.core.tx.OTransactionOptimistic.saveRecord(OTransactionOptimistic.java:363)
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.save(ODatabaseDocumentTx.java:2514)
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.save(ODatabaseDocumentTx.java:2444)
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.save(ODatabaseDocumentTx.java:121)
        at com.orientechnologies.orient.core.record.ORecordAbstract.save(ORecordAbstract.java:287)
        at com.orientechnologies.orient.core.record.ORecordAbstract.save(ORecordAbstract.java:279)
        at com.orientechnologies.orient.core.record.ORecordAbstract.save(ORecordAbstract.java:48)
        at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinaryV0.recursiveLinkSave(ORecordSerializerBinaryV0.java:675)
        at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinaryV0.writeOptimizedLink(ORecordSerializerBinaryV0.java:689)
        at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinaryV0.writeSingleValue(ORecordSerializerBinaryV0.java:574)
        at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinaryV0.serialize(ORecordSerializerBinaryV0.java:260)
        at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinary.toStream(ORecordSerializerBinary.java:105)
        at com.orientechnologies.orient.core.record.impl.ODocument.toStream(ODocument.java:2296)
        at com.orientechnologies.orient.core.record.impl.ODocument.toStream(ODocument.java:671)
at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.commitEntry(OAbstractPaginatedStorage.java:2446)
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.commit(OAbstractPaginatedStorage.java:1181)
        at com.orientechnologies.orient.core.tx.OTransactionOptimistic.doCommit(OTransactionOptimistic.java:606)
        at com.orientechnologies.orient.core.tx.OTransactionOptimistic.commit(OTransactionOptimistic.java:156)
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.commit(ODatabaseDocumentTx.java:2689)
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.commit(ODatabaseDocumentTx.java:2658)
        at in.co.nmsworks.documenttdb.db.DocDB.commit(DocDB.java:645)

Client version -- 68

**Comment by laa** [comment]
Hi @BaarathiNMS , all versions of ODB till 2.2.15 had a problem with usage of Java NIO, in the case of high load some data may be not flushed to disk, as result data structure may be broken.

**Comment by laa** [comment]
Please update to latest 2.2.x and make export/import from/to JSON. It will fix all this problem now and in the future.

**Comment by BaarathiNMS** [comment]
hi @laa Thanks. Oru version is 2.1.11. If we update latest orient jars to our database, will it work..???
If not then how can we recover all the data from our database..??

**Comment by laa** [comment]
Hi @BaarathiNMS , if you just update jars it will not work, because disk data structure is damaged but if you make export of your data to JSON and then import back all will be OK.

**Comment by BaarathiNMS** [comment]
Thanks @laa .

**Comment by laa** [comment]
@BaarathiNMS any updates on this issue?

**Comment by laa** [comment]
Hi @BaarathiNMS any updates on this issue?

**Comment by laa** [comment]
closed because of no reply, but I suppose the issue is fixed
