### ISSUE TITLE
OrientDB does not recover after abrupt power failure - EOFException - OStorageException: Cannot open local storage '/.../ddnmondb' with mode=rw

### ISSUE THREAD

**Issue by vguhesan** [orientechnologies/orientdb#7674]
### Java Version: 
java version "1.8.0_121"
Java(TM) SE Runtime Environment (build 1.8.0_121-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.121-b13, mixed mode)  
## Expected behavior  
the database recovers after an abrupt power failure 

## Actual behavior  
Database is unable to recover  

## Steps to reproduce  
We have a two node cluster. Both nodes were operational and then the data-center experienced an abrupt power failure and when power was restored. Node1- complained that it is waiting on Node2 to acquire a lock (as expected) since this database is owned by Node2. On Node2, we are seeing the following exception.

OStorageException: Cannot open local storage '/.../ddnmondb' with mode=rw
...
Caused by: java.io.EOFException
	at java.io.DataInputStream.readFully(DataInputStream.java:197)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at com.orientechnologies.orient.core.storage.cache.local.twoq.O2QCache.loadCacheState(O2QCache.java:658)

Additional Details:

>>>>>>>> devdm3n2 (NODE2) Exception >>>>>>>>>>>>
2017-08-21 18:04:04:626 INFO  [192.168.1.156]:2434 [5e29b2a28563955899c1f5ee92bb553a] [3.6.5] All migration tasks have been completed, queues are empty. [InternalPartitionService]$ANSI{green {db=ddnmondb}} Exception `7637B209` in storage `ddnmondb`
com.orientechnologies.orient.core.exception.OStorageException: Cannot open local storage '/data/ddnmon/orientdb/databases/ddnmondb' with mode=rw
	DB name="ddnmondb"
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.open(OAbstractPaginatedStorage.java:299)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.open(ODatabaseDocumentTx.java:258)
	at com.orientechnologies.orient.server.OServer.openDatabaseBypassingSecurity(OServer.java:987)
	at com.orientechnologies.orient.server.OServer.openDatabase(OServer.java:954)
	at com.orientechnologies.orient.server.OServer.openDatabase(OServer.java:939)
	at com.orientechnologies.orient.server.distributed.impl.ODistributedAbstractPlugin.reassignClustersOwnership(ODistributedAbstractPlugin.java:739)
	at com.orientechnologies.orient.server.hazelcast.OHazelcastPlugin$6.call(OHazelcastPlugin.java:740)
	at com.orientechnologies.orient.server.hazelcast.OHazelcastPlugin$6.call(OHazelcastPlugin.java:727)
	at com.orientechnologies.orient.server.distributed.impl.ODistributedAbstractPlugin.executeInDistributedDatabaseLock(ODistributedAbstractPlugin.java:1686)
	at com.orientechnologies.orient.server.hazelcast.OHazelcastPlugin.loadLocalDatabases(OHazelcastPlugin.java:727)
	at com.orientechnologies.orient.server.hazelcast.OHazelcastPlugin.startup(OHazelcastPlugin.java:254)
	at com.orientechnologies.orient.server.OServer.registerPlugins(OServer.java:1249)
	at com.orientechnologies.orient.server.OServer.activate(OServer.java:399)
	at com.orientechnologies.orient.server.OServerMain$1.run(OServerMain.java:46)
Caused by: com.orientechnologies.orient.core.exception.OStorageException: Cannot restore state of cache for storage placed under /data/ddnmon/orientdb/databases/ddnmondb
	DB name="ddnmondb"
	at com.orientechnologies.orient.core.storage.cache.local.twoq.O2QCache.loadCacheState(O2QCache.java:685)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.open(OAbstractPaginatedStorage.java:279)
	... 13 more
Caused by: java.io.EOFException
	at java.io.DataInputStream.readFully(DataInputStream.java:197)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at com.orientechnologies.orient.core.storage.cache.local.twoq.O2QCache.loadCacheState(O2QCache.java:658)
	... 14 more
[devdm3n2] Error on starting distributed plugin
com.orientechnologies.orient.core.exception.OStorageException: Cannot open local storage '/data/ddnmon/orientdb/databases/ddnmondb' with mode=rw
	DB name="ddnmondb"
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.open(OAbstractPaginatedStorage.java:299)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.open(ODatabaseDocumentTx.java:258)
	at com.orientechnologies.orient.server.OServer.openDatabaseBypassingSecurity(OServer.java:987)
	at com.orientechnologies.orient.server.OServer.openDatabase(OServer.java:954)
	at com.orientechnologies.orient.server.OServer.openDatabase(OServer.java:939)
	at com.orientechnologies.orient.server.distributed.impl.ODistributedAbstractPlugin.reassignClustersOwnership(ODistributedAbstractPlugin.java:739)
	at com.orientechnologies.orient.server.hazelcast.OHazelcastPlugin$6.call(OHazelcastPlugin.java:740)
	at com.orientechnologies.orient.server.hazelcast.OHazelcastPlugin$6.call(OHazelcastPlugin.java:727)
	at com.orientechnologies.orient.server.distributed.impl.ODistributedAbstractPlugin.executeInDistributedDatabaseLock(ODistributedAbstractPlugin.java:1686)
	at com.orientechnologies.orient.server.hazelcast.OHazelcastPlugin.loadLocalDatabases(OHazelcastPlugin.java:727)
	at com.orientechnologies.orient.server.hazelcast.OHazelcastPlugin.startup(OHazelcastPlugin.java:254)
	at com.orientechnologies.orient.server.OServer.registerPlugins(OServer.java:1249)
	at com.orientechnologies.orient.server.OServer.activate(OServer.java:399)
	at com.orientechnologies.orient.server.OServerMain$1.run(OServerMain.java:46)
Caused by: com.orientechnologies.orient.core.exception.OStorageException: Cannot restore state of cache for storage placed under /data/ddnmon/orientdb/databases/ddnmondb
	DB name="ddnmondb"
	at com.orientechnologies.orient.core.storage.cache.local.twoq.O2QCache.loadCacheState(O2QCache.java:685)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.open(OAbstractPaginatedStorage.java:279)
	... 13 more
Caused by: java.io.EOFException
	at java.io.DataInputStream.readFully(DataInputStream.java:197)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at com.orientechnologies.orient.core.storage.cache.local.twoq.O2QCache.loadCacheState(O2QCache.java:658)
	... 14 more
com.orientechnologies.orient.server.distributed.ODistributedStartupException: Error on starting distributed plugin
	at com.orientechnologies.orient.server.hazelcast.OHazelcastPlugin.startup(OHazelcastPlugin.java:309)
	at com.orientechnologies.orient.server.OServer.registerPlugins(OServer.java:1249)
	at com.orientechnologies.orient.server.OServer.activate(OServer.java:399)
	at com.orientechnologies.orient.server.OServerMain$1.run(OServerMain.java:46)
Caused by: com.orientechnologies.orient.core.exception.OStorageException: Cannot open local storage '/data/ddnmon/orientdb/databases/ddnmondb' with mode=rw
	DB name="ddnmondb"
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.open(OAbstractPaginatedStorage.java:299)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.open(ODatabaseDocumentTx.java:258)
	at com.orientechnologies.orient.server.OServer.openDatabaseBypassingSecurity(OServer.java:987)
	at com.orientechnologies.orient.server.OServer.openDatabase(OServer.java:954)
	at com.orientechnologies.orient.server.OServer.openDatabase(OServer.java:939)
	at com.orientechnologies.orient.server.distributed.impl.ODistributedAbstractPlugin.reassignClustersOwnership(ODistributedAbstractPlugin.java:739)
	at com.orientechnologies.orient.server.hazelcast.OHazelcastPlugin$6.call(OHazelcastPlugin.java:740)
	at com.orientechnologies.orient.server.hazelcast.OHazelcastPlugin$6.call(OHazelcastPlugin.java:727)
	at com.orientechnologies.orient.server.distributed.impl.ODistributedAbstractPlugin.executeInDistributedDatabaseLock(ODistributedAbstractPlugin.java:1686)
	at com.orientechnologies.orient.server.hazelcast.OHazelcastPlugin.loadLocalDatabases(OHazelcastPlugin.java:727)
	at com.orientechnologies.orient.server.hazelcast.OHazelcastPlugin.startup(OHazelcastPlugin.java:254)
	... 3 more
Caused by: com.orientechnologies.orient.core.exception.OStorageException: Cannot restore state of cache for storage placed under /data/ddnmon/orientdb/databases/ddnmondb
	DB name="ddnmondb"
	at com.orientechnologies.orient.core.storage.cache.local.twoq.O2QCache.loadCacheState(O2QCache.java:685)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.open(OAbstractPaginatedStorage.java:279)
	... 13 more
Caused by: java.io.EOFException
	at java.io.DataInputStream.readFully(DataInputStream.java:197)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at com.orientechnologies.orient.core.storage.cache.local.twoq.O2QCache.loadCacheState(O2QCache.java:658)
	... 14 more
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>

>>>>>>>>>>>> devdm3n1 (NODE1) EXCEPTION >>>>>>>>>>>>>>>>>>
2017-08-21 18:04:24:440 WARNI [devdm3n1]->[devdm3n2] Server 'devdm3n1' cannot acquire distributed lock on resource 'ddnmondb' (timeout=20000)... [ODistributedLockManagerRequester][devdm3n1] Error on starting distributed plugin
com.orientechnologies.common.concur.lock.OLockException: Server 'devdm3n1' cannot acquire exclusive lock on resource 'ddnmondb' (timeout=20000)
	at com.orientechnologies.orient.server.distributed.impl.ODistributedLockManagerRequester.acquireExclusiveLock(ODistributedLockManagerRequester.java:72)
	at com.orientechnologies.orient.server.distributed.impl.ODistributedAbstractPlugin.executeInDistributedDatabaseLock(ODistributedAbstractPlugin.java:1669)
	at com.orientechnologies.orient.server.hazelcast.OHazelcastPlugin.loadLocalDatabases(OHazelcastPlugin.java:727)
	at com.orientechnologies.orient.server.hazelcast.OHazelcastPlugin.startup(OHazelcastPlugin.java:254)
	at com.orientechnologies.orient.server.OServer.registerPlugins(OServer.java:1249)
	at com.orientechnologies.orient.server.OServer.activate(OServer.java:399)
	at com.orientechnologies.orient.server.OServerMain$1.run(OServerMain.java:46)
com.orientechnologies.orient.server.distributed.ODistributedStartupException: Error on starting distributed plugin
	at com.orientechnologies.orient.server.hazelcast.OHazelcastPlugin.startup(OHazelcastPlugin.java:309)
	at com.orientechnologies.orient.server.OServer.registerPlugins(OServer.java:1249)
	at com.orientechnologies.orient.server.OServer.activate(OServer.java:399)
	at com.orientechnologies.orient.server.OServerMain$1.run(OServerMain.java:46)
Caused by: com.orientechnologies.common.concur.lock.OLockException: Server 'devdm3n1' cannot acquire exclusive lock on resource 'ddnmondb' (timeout=20000)
	at com.orientechnologies.orient.server.distributed.impl.ODistributedLockManagerRequester.acquireExclusiveLock(ODistributedLockManagerRequester.java:72)
	at com.orientechnologies.orient.server.distributed.impl.ODistributedAbstractPlugin.executeInDistributedDatabaseLock(ODistributedAbstractPlugin.java:1669)
	at com.orientechnologies.orient.server.hazelcast.OHazelcastPlugin.loadLocalDatabases(OHazelcastPlugin.java:727)
	at com.orientechnologies.orient.server.hazelcast.OHazelcastPlugin.startup(OHazelcastPlugin.java:254)
	... 3 more
Error executing request
com.orientechnologies.orient.core.exception.ODatabaseException: Error on plugin lookup: the server did not start correctly
	DB name="ddnmondb"
	at com.orientechnologies.orient.server.OServer.getPlugin(OServer.java:860)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.openDatabase(ONetworkProtocolBinary.java:930)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.handshakeRequest(ONetworkProtocolBinary.java:238)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.execute(ONetworkProtocolBinary.java:203)
	at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:77)
Error executing request
com.orientechnologies.orient.core.exception.ODatabaseException: Error on plugin lookup: the server did not start correctly
	DB name="ddnmondb"
	at com.orientechnologies.orient.server.OServer.getPlugin(OServer.java:860)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.openDatabase(ONetworkProtocolBinary.java:930)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.handshakeRequest(ONetworkProtocolBinary.java:238)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.execute(ONetworkProtocolBinary.java:203)
	at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:77)
Error executing request
com.orientechnologies.orient.core.exception.ODatabaseException: Error on plugin lookup: the server did not start correctly
	DB name="ddnmondb"
	at com.orientechnologies.orient.server.OServer.getPlugin(OServer.java:860)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.openDatabase(ONetworkProtocolBinary.java:930)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.handshakeRequest(ONetworkProtocolBinary.java:238)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.execute(ONetworkProtocolBinary.java:203)
	at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:77)
Error executing request
com.orientechnologies.orient.core.exception.ODatabaseException: Error on plugin lookup: the server did not start correctly
	DB name="ddnmondb"
	at com.orientechnologies.orient.server.OServer.getPlugin(OServer.java:860)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.openDatabase(ONetworkProtocolBinary.java:930)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.handshakeRequest(ONetworkProtocolBinary.java:238)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.execute(ONetworkProtocolBinary.java:203)
	at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:77)
Error executing request
com.orientechnologies.orient.core.exception.ODatabaseException: Error on plugin lookup: the server did not start correctly
	DB name="ddnmondb"
	at com.orientechnologies.orient.server.OServer.getPlugin(OServer.java:860)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.openDatabase(ONetworkProtocolBinary.java:930)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.handshakeRequest(ONetworkProtocolBinary.java:238)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.execute(ONetworkProtocolBinary.java:203)
	at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:77)
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>

**Comment by laa** [comment]
Probably that is already fixed let me check it

**Comment by laa** [comment]
@santo-it , release notes: "When the server is loaded its cache state restored back into memory from a disk file, but sometimes if replication between nodes is broken for some reasons, a file which contains cache state may be broken. Before this issue, if IO exception happened on all operations on this cache state file except reading of size of the cache, we correctly handled it and continue server load. But IO exception during operation of reading of size of the cache was not handled correctly and server start was aborted. This fix corrects given problem"
