### ISSUE TITLE
Memory leak detector is switched off

### ISSUE THREAD

**Issue by laa** [orientechnologies/orientdb#7694]
When I run tests I see a lot of:
"
DIRECT-TRACK: unreleased direct memory buffer `6D1058B7` detected.
java.lang.Exception
        at com.orientechnologies.common.directmemory.OByteBufferPool$TrackedBufferReference.<init>(OByteBufferPool.java:816)
        at com.orientechnologies.common.directmemory.OByteBufferPool.track(OByteBufferPool.java:743)
        at com.orientechnologies.common.directmemory.OByteBufferPool.acquireDirect(OByteBufferPool.java:301)
        at com.orientechnologies.orient.core.storage.impl.memory.ODirectMemoryOnlyDiskCache$MemoryFile.addNewPage(ODirectMemoryOnlyDiskCache.java:535)
"

We need to detect leaks in fail tests in such cases

**Comment by laa** [comment]
Fxied
