### ISSUE TITLE
IllegalstateException when client or storage shut down

### ISSUE THREAD

**Issue by robfrank** [orientechnologies/orientdb#7695]
Launching the QA tests  on distribution module, at the end this exception appears:
```shell
Exception in thread "Thread-64" java.lang.IllegalStateException: Connection cannot be released because the pool doesn't exist anymore
	at com.orientechnologies.orient.client.remote.ORemoteConnectionManager.remove(ORemoteConnectionManager.java:127)
	at com.orientechnologies.orient.client.remote.OStorageRemote.onPushDisconnect(OStorageRemote.java:1931)
	at com.orientechnologies.orient.client.remote.OStorageRemotePushThread.run(OStorageRemotePushThread.java:66)
```

To launch the tests in distribution module:  mvn clean install -Pqa

**Comment by tglman** [comment]
fixed, closing

**Comment by laa** [comment]
Cool ! Finally ))
