### ISSUE TITLE
Error during read of record com.orientechnologies.orient.core.exception.ODatabaseException: Database 'plocal:/home/kisho.dai/mnt/orientdb/orientdb-enterprise-2.2.22/databases/sns' is closed

### ISSUE THREAD

**Issue by KishoDai** [orientechnologies/orientdb#7709]
## Expected behavior  
No error log.  
The issue is very strange. I can still select/upsert orientdb. But the logs is increasing very quickly .

## Actual behavior  
```
$ANSI{green {db=sns}} Error during read of record
com.orientechnologies.orient.core.exception.ODatabaseException: Database 'plocal:/home/kisho.dai/mnt/orientdb/orientdb-enterprise-2.2.22/databases/sns' is closed
	DB name="sns"
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.checkOpeness(ODatabaseDocumentTx.java:3145)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.executeReadRecord(ODatabaseDocumentTx.java:1956)
	at com.orientechnologies.orient.core.tx.OTransactionNoTx.loadRecord(OTransactionNoTx.java:98)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.load(ODatabaseDocumentTx.java:1766)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.load(ODatabaseDocumentTx.java:102)
	at com.orientechnologies.orient.core.iterator.OIdentifiableIterator.readCurrentRecord(OIdentifiableIterator.java:290)
	at com.orientechnologies.orient.core.iterator.ORecordIteratorClusters.hasNext(ORecordIteratorClusters.java:167)
	at com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.serialIterator(OCommandExecutorSQLSelect.java:1617)
	at com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.fetchFromTarget(OCommandExecutorSQLSelect.java:1566)
	at com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.executeSearch(OCommandExecutorSQLSelect.java:525)
	at com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.execute(OCommandExecutorSQLSelect.java:488)
	at com.orientechnologies.orient.core.sql.OCommandExecutorSQLDelegate.execute(OCommandExecutorSQLDelegate.java:74)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.executeCommand(OAbstractPaginatedStorage.java:3200)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.command(OAbstractPaginatedStorage.java:3138)
	at com.orientechnologies.orient.core.sql.query.OSQLQuery.run(OSQLQuery.java:78)
	at com.orientechnologies.orient.core.sql.query.OSQLAsynchQuery.run(OSQLAsynchQuery.java:74)
	at com.orientechnologies.orient.core.query.OQueryAbstract.execute(OQueryAbstract.java:33)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.query(ODatabaseDocumentTx.java:755)
	at com.orientechnologies.orient.core.sql.OCommandExecutorSQLUpdate.execute(OCommandExecutorSQLUpdate.java:303)
	at com.orientechnologies.orient.core.sql.OCommandExecutorSQLDelegate.execute(OCommandExecutorSQLDelegate.java:74)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.executeCommand(OAbstractPaginatedStorage.java:3200)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.command(OAbstractPaginatedStorage.java:3138)
	at com.orientechnologies.orient.core.command.OCommandRequestTextAbstract.execute(OCommandRequestTextAbstract.java:69)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.command(ONetworkProtocolBinary.java:1520)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.executeRequest(ONetworkProtocolBinary.java:642)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.sessionRequest(ONetworkProtocolBinary.java:380)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.execute(ONetworkProtocolBinary.java:203)
	at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:77) 
```

**Comment by tglman** [comment]
Hi @KishoDai,

A couple of question, are you running a distributed environment? Is it there any long running session?

I'm asking this because the reason for a close database under a running session can happen in case of distributed re-sync or for timeout of the session.

Regards

**Comment by laa** [comment]
@KishoDai @tglman guys what about this issue, does it still exist? Could we close it?

**Comment by laa** [comment]
@KishoDai do you still experience this issue?

**Comment by laa** [comment]
@KishoDai do you still experience this issue?

**Comment by laa** [comment]
Hi @KishoDai do you still experience this issue?

**Comment by laa** [comment]
Hi @KishoDai do you still experience this issue?

**Comment by laa** [comment]
Hi @KishoDai do you still experience this issue?

**Comment by luigidellaquila** [comment]
No response for a long time, closing.
Please feel free to re-open if you have any further info

Thanks

Luigi
