### ISSUE TITLE
HA: problem on reading the WAL after server crash

### ISSUE THREAD

**Issue by lvca** [orientechnologies/orientdb#7711]
This has been reproduced 3 times by internal HA testing after restarting random nodes.

```
2017-09-04 15:07:57:733 INFO  [node1]->[node2] Creating delta backup of database 'stress-test-db-20170904_150644' (startLSN=LSN{segment=0, position=1408376}) in directory: /var/folders/zc/y34429014c3bt_x1587qblth0000gn/T/orientdb/backup_node2_stress-test-db-20170904_150644_server0.zip... [OSyncDatabaseDeltaTask]Exception `64C4ED84` in storage `stress-test-db-20170904_150644`
java.nio.BufferUnderflowException
    at java.nio.HeapByteBuffer.get(HeapByteBuffer.java:151)
    at java.nio.ByteBuffer.get(ByteBuffer.java:715)
    at com.orientechnologies.orient.core.storage.impl.local.paginated.wal.OWALPageV2.getRecord(OWALPageV2.java:113)
    at com.orientechnologies.orient.core.storage.impl.local.paginated.wal.OLogSegmentV2.readRecord(OLogSegmentV2.java:747)
    at com.orientechnologies.orient.core.storage.impl.local.paginated.wal.OLogSegmentV2.getNextLSN(OLogSegmentV2.java:780)
    at com.orientechnologies.orient.core.storage.impl.local.paginated.wal.ODiskWriteAheadLog.next(ODiskWriteAheadLog.java:892)
    at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.recordsChangedAfterLSN(OAbstractPaginatedStorage.java:995)
    at com.orientechnologies.orient.server.distributed.impl.task.OSyncDatabaseDeltaTask.deltaBackup(OSyncDatabaseDeltaTask.java:138)
    at com.orientechnologies.orient.server.distributed.impl.task.OSyncDatabaseDeltaTask.execute(OSyncDatabaseDeltaTask.java:70)
    at com.orientechnologies.orient.server.distributed.impl.ODistributedAbstractPlugin$1.call(ODistributedAbstractPlugin.java:604)
    at com.orientechnologies.orient.core.db.OScenarioThreadLocal.executeAsDistributed(OScenarioThreadLocal.java:70)
    at com.orientechnologies.orient.server.distributed.impl.ODistributedAbstractPlugin.executeOnLocalNode(ODistributedAbstractPlugin.java:600)
    at com.orientechnologies.orient.server.distributed.impl.ODistributedWorker.onMessage(ODistributedWorker.java:347)
    at com.orientechnologies.orient.server.distributed.impl.ODistributedWorker.run(ODistributedWorker.java:121)
```

**Comment by laa** [comment]
Fixed in the latest version, closing.
