### ISSUE TITLE
OLockException: No more resources available in pool (max=100).

### ISSUE THREAD

**Issue by jaydeep1993** [orientechnologies/orientdb#7716]
### Java Version: 
java version "1.7.0_55"
OpenJDK Runtime Environment (IcedTea 2.4.7) (7u55-2.4.7-1ubuntu1~0.12.04.2)
OpenJDK 64-Bit Server VM (build 24.51-b03, mixed mode)   

### orientdb-server-config.xml
```
<properties>
        <entry value="1" name="db.pool.min"/>
        <entry value="flase" name="storage.keepOpen"/>
        <entry value="5000" name="db.pool.max"/>
        <entry value="true" name="profiler.enabled"/>
        <entry value="info" name="log.console.level"/>
        <entry value="fine" name="log.file.level"/>
        <entry value="5000" name="client.channel.maxPool" />
        <entry value="5000" name="distributed.queueMaxSize" />
        <entry value="/apps/orient/databases" name="server.database.path" />
</properties>
```
### Java Api to acquire db-pool (acquired on application-start)
```
       @Override
	public void afterPropertiesSet() throws Exception {
		odbPool = new OObjectDatabasePool(dbUrl, userName, password);
		odbPool.setup(2, 200);
	}
	@Override
	public OObjectDatabaseTx getObjectDB() {
		OObjectDatabaseTx odb = odbPool.acquire();
		odb.setLazyLoading(false);
		return odb;
	}
```
### sql query in java 
We are following below syntax to execute queries
```
       @Override
	public boolean create(BufferedTxn bufferedTxn) {
		OObjectDatabaseTx objDb = odb.getObjectDB();
		List<BufferedTxn> txn = new ArrayList<>();
		try {
			objDb.save(bufferedTxn);
			return true;
		} catch (Exception e) {
			LOGGER.error(e.getMessage(), e);
			return false;
		} finally {
			objDb.close();
		}
	}
```

### Log from tomcat java application
```
05-Sep-2017` 14-43-35:007 ERROR com.main.service.otp.SaOtpController Cannot open a connection to remote server: <ip>:2424/db_name
	DB name="db_name"
com.orientechnologies.orient.core.exception.OStorageException: Cannot open a connection to remote server: <ip>:2424/db_name
	DB name="db_name"
	at com.orientechnologies.orient.client.remote.OStorageRemote.getNetwork(OStorageRemote.java:2210) ~[orientdb-client-2.2.24.jar:2.2.24]
	at com.orientechnologies.orient.client.remote.OStorageRemote.openRemoteDatabase(OStorageRemote.java:1918) ~[orientdb-client-2.2.24.jar:2.2.24]
	at com.orientechnologies.orient.client.remote.OStorageRemote.openRemoteDatabase(OStorageRemote.java:1858) ~[orientdb-client-2.2.24.jar:2.2.24]
	at com.orientechnologies.orient.client.remote.OStorageRemote.open(OStorageRemote.java:356) ~[orientdb-client-2.2.24.jar:2.2.24]
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.open(ODatabaseDocumentTx.java:258) ~[orientdb-core-2.2.24.jar:2.2.24]
	at com.orientechnologies.orient.core.db.ODatabaseWrapperAbstract.open(ODatabaseWrapperAbstract.java:56) ~[orientdb-core-2.2.24.jar:2.2.24]
	at com.orientechnologies.orient.object.db.OObjectDatabaseTx.open(OObjectDatabaseTx.java:120) ~[orientdb-object-2.2.24.jar:2.2.24]
	at com.orientechnologies.orient.object.db.OObjectDatabaseTxPooled.<init>(OObjectDatabaseTxPooled.java:48) ~[orientdb-object-2.2.24.jar:2.2.24]
	at com.orientechnologies.orient.object.db.OObjectDatabasePool.createResource(OObjectDatabasePool.java:51) ~[orientdb-object-2.2.24.jar:2.2.24]
	at com.orientechnologies.orient.object.db.OObjectDatabasePool.createResource(OObjectDatabasePool.java:27) ~[orientdb-object-2.2.24.jar:2.2.24]
	at com.orientechnologies.orient.core.db.ODatabasePoolBase$1.createNewResource(ODatabasePoolBase.java:81) ~[orientdb-core-2.2.24.jar:2.2.24]
	at com.orientechnologies.orient.core.db.ODatabasePoolBase$1.createNewResource(ODatabasePoolBase.java:70) ~[orientdb-core-2.2.24.jar:2.2.24]
	at com.orientechnologies.common.concur.resource.OResourcePool.getResource(OResourcePool.java:91) ~[orientdb-core-2.2.24.jar:2.2.24]
	at com.orientechnologies.common.concur.resource.OReentrantResourcePool.getResource(OReentrantResourcePool.java:84) ~[orientdb-core-2.2.24.jar:2.2.24]
	at com.orientechnologies.orient.core.db.ODatabasePoolAbstract.acquire(ODatabasePoolAbstract.java:158) ~[orientdb-core-2.2.24.jar:2.2.24]
	at com.orientechnologies.orient.core.db.ODatabasePoolAbstract.acquire(ODatabasePoolAbstract.java:138) ~[orientdb-core-2.2.24.jar:2.2.24]
	at com.orientechnologies.orient.core.db.ODatabasePoolBase.acquire(ODatabasePoolBase.java:112) ~[orientdb-core-2.2.24.jar:2.2.24]
5872b6.invoke(<generated>) ~[dobby-store-1.0.jar:?]
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204) ~[spring-core-4.3.2.RELEASE.jar:4.3.2.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:720) ~[spring-aop-4.3.2.RELEASE.jar:4.3.2.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157) ~[spring-aop-4.3.2.RELEASE.jar:4.3.2.RELEASE]
	at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:136) ~[spring-tx-4.3.2.RELEASE.jar:4.3.2.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179) ~[spring-aop-4.3.2.RELEASE.jar:4.3.2.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:655) ~[spring-aop-4.3.2.RELEASE.jar:4.3.2.RELEASE]
	at com.main.store.support.portal.BufferedTxnDao$$EnhancerBySpringCGLIB$$dffe2d72.findByUUID(<generated>) ~[dobby-store-1.0.jar:?]
	at sun.reflect.GeneratedMethodAccessor66.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_112]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_112]
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:221) [spring-web-4.3.2.RELEASE.jar:4.3.2.RELEASE]
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:136) [spring-web-4.3.2.RELEASE.jar:4.3.2.RELEASE]
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:114) [spring-webmvc-4.3.2.RELEASE.jar:4.3.2.RELEASE]
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:827) [spring-webmvc-4.3.2.RELEASE.jar:4.3.2.RELEASE]
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:738) [spring-webmvc-4.3.2.RELEASE.jar:4.3.2.RELEASE]
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85) [spring-webmvc-4.3.2.RELEASE.jar:4.3.2.RELEASE]
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:963) [spring-webmvc-4.3.2.RELEASE.jar:4.3.2.RELEASE]
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:897) [spring-webmvc-4.3.2.RELEASE.jar:4.3.2.RELEASE]
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970) [spring-webmvc-4.3.2.RELEASE.jar:4.3.2.RELEASE]
	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:872) [spring-webmvc-4.3.2.RELEASE.jar:4.3.2.RELEASE]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:648) [servlet-api.jar:?]
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846) [spring-webmvc-4.3.2.RELEASE.jar:4.3.2.RELEASE]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:729) [servlet-api.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:230) [catalina.jar:8.5.4]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165) [catalina.jar:8.5.4]
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52) [tomcat-websocket.jar:8.5.4]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192) [catalina.jar:8.5.4]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165) [catalina.jar:8.5.4]
	at org.apache.logging.log4j.web.Log4jServletFilter.doFilter(Log4jServletFilter.java:71) [log4j-web-2.6.2.jar:2.6.2]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192) [catalina.jar:8.5.4]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165) [catalina.jar:8.5.4]
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:197) [spring-web-4.3.2.RELEASE.jar:4.3.2.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) [spring-web-4.3.2.RELEASE.jar:4.3.2.RELEASE]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192) [catalina.jar:8.5.4]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165) [catalina.jar:8.5.4]
	at org.springframework.boot.web.support.ErrorPageFilter.doFilter(ErrorPageFilter.java:119) [spring-boot-1.4.0.RELEASE.jar:1.4.0.RELEASE]
	at org.springframework.boot.web.support.ErrorPageFilter.access$000(ErrorPageFilter.java:61) [spring-boot-1.4.0.RELEASE.jar:1.4.0.RELEASE]
	at org.springframework.boot.web.support.ErrorPageFilter$1.doFilterInternal(ErrorPageFilter.java:94) [spring-boot-1.4.0.RELEASE.jar:1.4.0.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) [spring-web-4.3.2.RELEASE.jar:4.3.2.RELEASE]
	at org.springframework.boot.web.support.ErrorPageFilter.doFilter(ErrorPageFilter.java:112) [spring-boot-1.4.0.RELEASE.jar:1.4.0.RELEASE]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192) [catalina.jar:8.5.4]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165) [catalina.jar:8.5.4]
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198) [catalina.jar:8.5.4]
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:108) [catalina.jar:8.5.4]
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:522) [catalina.jar:8.5.4]
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140) [catalina.jar:8.5.4]
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79) [catalina.jar:8.5.4]
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:620) [catalina.jar:8.5.4]
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87) [catalina.jar:8.5.4]
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:349) [catalina.jar:8.5.4]
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:1110) [tomcat-coyote.jar:8.5.4]
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66) [tomcat-coyote.jar:8.5.4]
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:785) [tomcat-coyote.jar:8.5.4]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1425) [tomcat-coyote.jar:8.5.4]
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) [tomcat-coyote.jar:8.5.4]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_112]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_112]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-util.jar:8.5.4]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_112]
Caused by: com.orientechnologies.common.concur.lock.OLockException: No more resources available in pool (max=100). Requested resource: <ip>:2424/db_name
	at com.orientechnologies.common.concur.resource.OResourcePool.getResource(OResourcePool.java:66) ~[orientdb-core-2.2.24.jar:2.2.24]
	at com.orientechnologies.orient.client.remote.ORemoteConnectionPool.acquire(ORemoteConnectionPool.java:98) ~[orientdb-client-2.2.24.jar:2.2.24]
	at com.orientechnologies.orient.client.remote.ORemoteConnectionManager.acquire(ORemoteConnectionManager.java:101) ~[orientdb-client-2.2.24.jar:2.2.2
```

**Comment by tglman** [comment]
hi @jaydeep1993,

from the error and the configuration I see that you set `client.channel.maxPool` on the server and not in the client, you should set that as environment variable of the client.

Hope it help,

Emanuele

**Comment by tglman** [comment]
hi @jaydeep1993,

For set the setting depends on the way you run the system, if is a simple java command line you can use `java .... -Dclient.channel.maxPool=5000` or you can set it directly in the java code of the client before connect using `OGlobalConfiguration.CLIENT_CHANNEL_MAX_POOL.setValue(5000)`.

Regards

Emanuele

**Comment by sarutumuluri** [comment]
We have multiple tomcat applications connecting to same database. One of the tomcat application starts giving error(StackTrace attached) after running for 10 minutes.

We have two databases. We are not running distributed instances.

**Comment by ashish-kl** [comment]
`client.channel.maxPool` is among the global confg parameters on the orientdb studio .
So we set it up there.
Is this supposed to setup on client not on server?

**Comment by jaydeep1993** [comment]
```OGlobalConfiguration.CLIENT_CHANNEL_MAX_POOL.setValue(5000)``` doesn't seem to work.
behaviour is the same.

**Comment by sarutumuluri** [comment]
Request a remote session to debug this issue

**Comment by tglman** [comment]
hi @jaydeep1993,

As mentioned in this issue: https://www.prjhub.com/#/issues/9270 the problem was a slowdown due to defragmentation happening on a specific class, this put pressure on the pool that ran out of connections pretty soon, with the configuration set to 5000 you should not hit this problem, in any case as mentioned in the other issue would be cool have another thread dump of the server to double check that all the slowdown have cleared.

Kind Regards

**Comment by tglman** [comment]
hi @jaydeep1993,

Did you have any problem recently ? can we close this issue ?

Regards

**Comment by tglman** [comment]
Hi @jaydeep1993,

I'm going to close this, please reopen if you have further problems.

Regards
