### ISSUE TITLE
om.orientechnologies.orient.core.sql.parser.TokenMgrError: Lexical error at line 1, column 116.  Encountered: <EOF> after : "\"\u5587\u53ed\u9ec4"

### ISSUE THREAD

**Issue by KishoDai** [orientechnologies/orientdb#7741]
## Expected behavior  
Can update some special characters.

## Actual behavior  
java.lang.RuntimeException: java.util.concurrent.ExecutionException: com.orientechnologies.orient.enterprise.channel.binary.OResponseProcessingException: Exception during response processing
        at cn.memedai.orientdb.teleporter.sns.common.consumer.AddressBookPhoneCommonConsumer.blockThreadStage(AddressBookPhoneCommonConsumer.java:216)
        at cn.memedai.orientdb.teleporter.sns.common.consumer.AddressBookPhoneCommonConsumer.process(AddressBookPhoneCommonConsumer.java:139)
        at cn.memedai.orientdb.teleporter.BlockingQueueDataBatchProcessConsumer.run(BlockingQueueDataBatchProcessConsumer.java:59)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.util.concurrent.ExecutionException: com.orientechnologies.orient.enterprise.channel.binary.OResponseProcessingException: Exception during response processing
        at java.util.concurrent.FutureTask.report(FutureTask.java:122)
        at java.util.concurrent.FutureTask.get(FutureTask.java:192)
        at cn.memedai.orientdb.teleporter.sns.common.consumer.AddressBookPhoneCommonConsumer.blockThreadStage(AddressBookPhoneCommonConsumer.java:214)
        ... 7 common frames omitted
Caused by: com.orientechnologies.orient.enterprise.channel.binary.OResponseProcessingException: Exception during response processing
        at com.orientechnologies.orient.client.binary.OChannelBinaryAsynchClient.throwSerializedException(OChannelBinaryAsynchClient.java:458)
        at com.orientechnologies.orient.client.binary.OChannelBinaryAsynchClient.handleStatus(OChannelBinaryAsynchClient.java:393)
        at com.orientechnologies.orient.client.binary.OChannelBinaryAsynchClient.beginResponse(OChannelBinaryAsynchClient.java:275)
        at com.orientechnologies.orient.client.binary.OChannelBinaryAsynchClient.beginResponse(OChannelBinaryAsynchClient.java:167)
        at com.orientechnologies.orient.client.remote.OStorageRemote.beginResponse(OStorageRemote.java:2225)
        at com.orientechnologies.orient.client.remote.OStorageRemote$27.execute(OStorageRemote.java:1200)
        at com.orientechnologies.orient.client.remote.OStorageRemote$2.execute(OStorageRemote.java:198)
        at com.orientechnologies.orient.client.remote.OStorageRemote.baseNetworkOperation(OStorageRemote.java:243)
        at com.orientechnologies.orient.client.remote.OStorageRemote.networkOperationRetry(OStorageRemote.java:195)
        at com.orientechnologies.orient.client.remote.OStorageRemote.networkOperation(OStorageRemote.java:206)
        at com.orientechnologies.orient.client.remote.OStorageRemote.command(OStorageRemote.java:1176)
        at com.orientechnologies.orient.core.command.OCommandRequestTextAbstract.execute(OCommandRequestTextAbstract.java:69)
        at cn.memedai.orientdb.utils.OrientSqlUtils.executeBatchSQLs(OrientSqlUtils.java:176)
        at cn.memedai.orientdb.teleporter.sns.common.consumer.AddressBookPhoneCommonConsumer$2.run(AddressBookPhoneCommonConsumer.java:184)
        ... 5 common frames omitted
Caused by: com.orientechnologies.orient.core.sql.parser.TokenMgrError: Lexical error at line 1, column 116.  Encountered: <EOF> after : "\"\u5587\u53ed\u9ec4"
        at com.orientechnologies.orient.core.sql.parser.OrientSqlTokenManager.getNextToken(OrientSqlTokenManager.java:6184)
        at com.orientechnologies.orient.core.sql.parser.OrientSql.jj_scan_token(OrientSql.java:27031)
        at com.orientechnologies.orient.core.sql.parser.OrientSql.jj_3R_289(OrientSql.java:24161)
        at com.orientechnologies.orient.core.sql.parser.OrientSql.jj_3R_113(OrientSql.java:24192)
        at com.orientechnologies.orient.core.sql.parser.OrientSql.jj_3R_460(OrientSql.java:25620)
        at com.orientechnologies.orient.core.sql.parser.OrientSql.jj_3_59(OrientSql.java:25685)
        at com.orientechnologies.orient.core.sql.parser.OrientSql.jj_3R_107(OrientSql.java:25850)
        at com.orientechnologies.orient.core.sql.parser.OrientSql.jj_3R_178(OrientSql.java:25353)
        at com.orientechnologies.orient.core.sql.parser.OrientSql.jj_3R_78(OrientSql.java:25404)
        at com.orientechnologies.orient.core.sql.parser.OrientSql.jj_3_20(OrientSql.java:22607)
        at com.orientechnologies.orient.core.sql.parser.OrientSql.jj_2_20(OrientSql.java:18518)
        at com.orientechnologies.orient.core.sql.parser.OrientSql.StatementInternal(OrientSql.java:778)
        at com.orientechnologies.orient.client.remote.OStorageRemote.baseNetworkOperation(OStorageRemote.java:243)
        at com.orientechnologies.orient.client.remote.OStorageRemote.networkOperationRetry(OStorageRemote.java:195)
        at com.orientechnologies.orient.client.remote.OStorageRemote.networkOperation(OStorageRemote.java:206)
        at com.orientechnologies.orient.client.remote.OStorageRemote.command(OStorageRemote.java:1176)
        at com.orientechnologies.orient.core.command.OCommandRequestTextAbstract.execute(OCommandRequestTextAbstract.java:69)
        at cn.memedai.orientdb.utils.OrientSqlUtils.executeBatchSQLs(OrientSqlUtils.java:176)
        at cn.memedai.orientdb.teleporter.sns.common.consumer.AddressBookPhoneCommonConsumer$2.run(AddressBookPhoneCommonConsumer.java:184)
        ... 5 common frames omitted
Caused by: com.orientechnologies.orient.core.sql.parser.TokenMgrError: Lexical error at line 1, column 116.  Encountered: <EOF> after : "\"\u5587\u53ed\u9ec4"
        at com.orientechnologies.orient.core.sql.parser.OrientSqlTokenManager.getNextToken(OrientSqlTokenManager.java:6184)
        at com.orientechnologies.orient.core.sql.parser.OrientSql.jj_scan_token(OrientSql.java:27031)
        at com.orientechnologies.orient.core.sql.parser.OrientSql.jj_3R_289(OrientSql.java:24161)
        at com.orientechnologies.orient.core.sql.parser.OrientSql.jj_3R_113(OrientSql.java:24192)
        at com.orientechnologies.orient.core.sql.parser.OrientSql.jj_3R_460(OrientSql.java:25620)
        at com.orientechnologies.orient.core.sql.parser.OrientSql.jj_3_59(OrientSql.java:25685)
        at com.orientechnologies.orient.core.sql.parser.OrientSql.jj_3R_107(OrientSql.java:25850)
        at com.orientechnologies.orient.core.sql.parser.OrientSql.jj_3R_178(OrientSql.java:25353)
        at com.orientechnologies.orient.core.sql.parser.OrientSql.jj_3R_78(OrientSql.java:25404)
        at com.orientechnologies.orient.core.sql.parser.OrientSql.jj_3_20(OrientSql.java:22607)
        at com.orientechnologies.orient.core.sql.parser.OrientSql.jj_2_20(OrientSql.java:18518)
        at com.orientechnologies.orient.core.sql.parser.OrientSql.StatementInternal(OrientSql.java:778)
        at com.orientechnologies.orient.core.sql.parser.OrientSql.Statement(OrientSql.java:630)
        at com.orientechnologies.orient.core.sql.parser.OrientSql.parse(OrientSql.java:75)
        at com.orientechnologies.orient.core.sql.parser.OStatementCache.parse(OStatementCache.java:100)
        at com.orientechnologies.orient.core.sql.parser.OStatementCache.get(OStatementCache.java:81)
        at com.orientechnologies.orient.core.sql.parser.OStatementCache.get(OStatementCache.java:64)
        at com.orientechnologies.orient.core.sql.OCommandExecutorSQLAbstract.preParse(OCommandExecutorSQLAbstract.java:225)
        at com.orientechnologies.orient.graph.sql.OCommandExecutorSQLCreateEdge.parse(OCommandExecutorSQLCreateEdge.java:66)
        at com.orientechnologies.orient.graph.sql.OCommandExecutorSQLCreateEdge.parse(OCommandExecutorSQLCreateEdge.java:46)
        at com.orientechnologies.orient.core.sql.OCommandExecutorSQLDelegate.parse(OCommandExecutorSQLDelegate.java:58)
        at com.orientechnologies.orient.core.sql.OCommandExecutorSQLDelegate.parse(OCommandExecutorSQLDelegate.java:39)
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.command(OAbstractPaginatedStorage.java:3136)
        at com.orientechnologies.orient.core.command.OCommandRequestTextAbstract.execute(OCommandRequestTextAbstract.java:69)
        at com.orientechnologies.orient.core.command.script.OCommandExecutorScript.executeCommand(OCommandExecutorScript.java:485)
        at com.orientechnologies.orient.core.command.script.OCommandExecutorScript.executeLet(OCommandExecutorScript.java:622)
        at com.orientechnologies.orient.core.command.script.OCommandExecutorScript.executeSQLScript(OCommandExecutorScript.java:276)
        at com.orientechnologies.orient.core.command.script.OCommandExecutorScript.executeSQL(OCommandExecutorScript.java:197)
        at com.orientechnologies.orient.core.command.script.OCommandExecutorScript.executeInContext(OCommandExecutorScript.java:104)
        at com.orientechnologies.orient.core.command.script.OCommandExecutorScript.execute(OCommandExecutorScript.java:88)
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.executeCommand(OAbstractPaginatedStorage.java:3200)
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.command(OAbstractPaginatedStorage.java:3138)
        at com.orientechnologies.orient.core.command.OCommandRequestTextAbstract.execute(OCommandRequestTextAbstract.java:69)
        at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.command(ONetworkProtocolBinary.java:1520)
        at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.executeRequest(ONetworkProtocolBinary.java:642)
        at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.sessionRequest(ONetworkProtocolBinary.java:380)
        at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.execute(ONetworkProtocolBinary.java:203)
        at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:77)
 

## Steps to reproduce  
<add here>

**Comment by luigidellaquila** [comment]
Hi @KishoDai 

It's a query parsing error, do you have the statement that fails to parse? I need it to reproduce the problem

Thanks

Luigi

**Comment by luigidellaquila** [comment]
HI @KishoDai 

Any chance to have the statement that caused this problem?

Thanks

Luigi

**Comment by luigidellaquila** [comment]
Hi @KishoDai 

I'm closing this issue as I have no way to replicate it. Please re-open if you have any additional info

Thanks

Luigi
