### ISSUE TITLE
Custom type unserializing is not working

### ISSUE THREAD

**Issue by vitormcruz** [orientechnologies/orientdb#7743]
## Expected behavior  
When defining and binding an OObjectSerializerContext for a given object, lazy fetch should use unserializeFieldValue.

## Actual behavior  
While the object is stored using serializeFieldValue, when it is fetched the proxy object don't call unserializeFieldValue in order to set the correct object in the class.

## Steps to reproduce  
For a given database

        OObjectSerializerContext serializerContext = new OObjectSerializerContext();
        serializerContext.bind(new OObjectSerializer<DateTime, Long>() {
            @Override
            Object serializeFieldValue(Class<?> iClass, DateTime iFieldValue) {
                return iFieldValue.getMillis()
            }

            @Override
            Object unserializeFieldValue(Class<?> iClass, Long iFieldValue) {
                return new DateTime(iFieldValue)
            }
        }, database)

       OObjectSerializerHelper.bindSerializerContext(null, serializerContext)
       database.save(new ClassWithADateTimeField(DateTime.now())
       for(ClassWithADateTimeField obj : database.browseClass(ClassWithADateTimeField)){
           System.out.println(obj.getDate())    <--- Fail here, unserializeFieldValue is not called.
       }

**Comment by maggiolo00** [comment]
hi @vitormcruz 

is `serializeFieldValue` called when saving?

**Comment by vitormcruz** [comment]
Yes.

**Comment by maggiolo00** [comment]
hi @vitormcruz 

did you use the api

to register the Serialization context ?

`OObjectSerializerHelper.bindSerializerContext`

https://orientdb.com/docs/2.2/Object-2-Record-Java-Binding.html#custom-types

**Comment by vitormcruz** [comment]
Yes, I removed from the "Steps to reproduce" by mistake, but I call `OObjectSerializerHelper.bindSerializerContext(null, serializerContext). I will edit it.

**Comment by maggiolo00** [comment]
Can you try to bind `DateTime.class` in this way instead of null


```
OObjectSerializerHelper.bindSerializerContext(DateTime.class, serializerContext).
```

**Comment by vitormcruz** [comment]
Yes, I got a:

```
Caused by: java.lang.NullPointerException
	at java.lang.Class.isAssignableFrom(Native Method)
	at com.orientechnologies.orient.object.enhancement.OObjectEntitySerializer.serializeFieldValue(OObjectEntitySerializer.java:751)
	at com.orientechnologies.orient.object.enhancement.OObjectEntitySerializer.typeToStream(OObjectEntitySerializer.java:811)
	at com.orientechnologies.orient.object.enhancement.OObjectEntitySerializer.toStream(OObjectEntitySerializer.java:1211)
	at com.orientechnologies.orient.object.enhancement.OObjectEntitySerializer.serializeObject(OObjectEntitySerializer.java:145)
	at com.orientechnologies.orient.object.db.OObjectDatabaseTx.save(OObjectDatabaseTx.java:453)
	at com.orientechnologies.orient.object.db.OObjectDatabaseTx.save(OObjectDatabaseTx.java:398)
	at com.orientechnologies.orient.core.db.ODatabase$save$0.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
```

**Comment by maggiolo00** [comment]
hi @vitormcruz 

do you have a test case to reproduce this issue?

**Comment by tglman** [comment]
hi @vitormcruz, 

The object module is not anymore actively maintained, we will fix issue with reproducible test case and merge any work from the community that looks good enough, anyway the core team will not do any huge work on the object layer.

Regards

**Comment by vitormcruz** [comment]
Hello @maggiolo00 , I figured out that the issue happens when I register the class before the serializer binder. Thre goes the test case, you can see the problem not raising by switching the bind statement comment:

```import com.orientechnologies.orient.client.remote.OServerAdmin;
import com.orientechnologies.orient.core.serialization.serializer.object.OObjectSerializer;
import com.orientechnologies.orient.object.db.OObjectDatabaseTx;
import com.orientechnologies.orient.object.serialization.OObjectSerializerContext;
import com.orientechnologies.orient.object.serialization.OObjectSerializerHelper;
import com.orientechnologies.orient.server.OServer;
import com.orientechnologies.orient.server.OServerMain;
import com.orientechnologies.orient.server.config.OServerConfiguration;
import com.orientechnologies.orient.server.config.OServerNetworkConfiguration;
import com.orientechnologies.orient.server.config.OServerUserConfiguration;
import org.joda.time.DateTime;

import java.io.File;

public class TestCase {

    public static void main(String[] args) throws Exception {

        //Start Ebedded Server
        System.setProperty("ORIENTDB_HOME", new File("").getAbsolutePath());

        OServer orientDbServer = OServerMain.create();

        OServerConfiguration configuration = new OServerConfiguration();
        configuration.location = "memory";
        configuration.network = new OServerNetworkConfiguration(new Object());
        configuration.users = new OServerUserConfiguration[]{ new OServerUserConfiguration("root", "root", "*")};
        orientDbServer.startup(configuration);

        orientDbServer.activate();
        Runtime.getRuntime().addShutdownHook(new Thread(new Runnable() {
            @Override
            public void run() {
                orientDbServer.shutdown();
            }
        }));

        //Create and open Test in-memory database
        new OServerAdmin("localhost").connect("root", "root")
                                     .createDatabase("test", "document", "memory")
                                     .close();

        OObjectDatabaseTx database = new OObjectDatabaseTx("memory:localhost/test").open("admin", "admin");

        //Define a serializer for joda DateTime
        OObjectSerializerContext serializerContext = new OObjectSerializerContext();
        serializerContext.bind(new OObjectSerializer<DateTime, Long>() {
            @Override
            public Object serializeFieldValue(Class<?> iClass, DateTime iFieldValue) {
                return iFieldValue.getMillis();
            }

            @Override
            public Object unserializeFieldValue(Class<?> iClass, Long iFieldValue) {
                return new DateTime(iFieldValue);
            }
        }, database);

        database.getEntityManager().registerEntityClass(DummyEntity.class);

        OObjectSerializerHelper.bindSerializerContext(null, serializerContext);

//        database.getEntityManager().registerEntityClass(DummyEntity.class);

        //Start using the database
        database.save(new DummyEntity(DateTime.now()));

        System.out.println("\n");
        for (Object o : database.browseClass(DummyEntity.class)) {
            DummyEntity dummyEntity = (DummyEntity) o;
            System.out.println(dummyEntity.getDateTime());
        }

        System.exit(0);
    }

    public static class DummyEntity {
        private DateTime dateTime;

        public DummyEntity() {
        }

        DummyEntity(DateTime dateTime) {
            this.dateTime = dateTime;
        }

        DateTime getDateTime() {
            return dateTime;
        }

        void setDateTime(DateTime dateTime) {
            this.dateTime = dateTime;
        }
    }
}

**Comment by vitormcruz** [comment]
Hi @tglman , is there any reason to do so? It seems very usefully  to me (I am still experimenting).
