### ISSUE TITLE
Question: plocal and FULL TEXT Lucene Index

### ISSUE THREAD

**Issue by carloprad** [orientechnologies/orientdb#7749]
### OS: CentOS Linux release 7.3.1611 (Core)

Hi,
we've developed a java application accessing ODB using remote protocol.
Everything works fine.

Eventually we've tried to check a possible performance gain switching to plocal access, but when the application starts throws out this exception:

> ERROR com.app.graph.interfaces.GraphPool - Schema loading failed due to the following error
com.orientechnologies.orient.core.exception.OStorageException: Cannot open local storage '/path/to/my/db' with mode=rw
DB name="db"
at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.open(OAbstractPaginatedStorage.java:346) ~[app.jar:?]
at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.open(ODatabaseDocumentTx.java:259) ~[app.jar:?]
at com.orientechnologies.orient.core.db.OPartitionedDatabasePool$DatabaseDocumentTxPooled.internalOpen(OPartitionedDatabasePool.java:447) ~[app.jar:?]
at com.orientechnologies.orient.core.db.OPartitionedDatabasePool.openDatabase(OPartitionedDatabasePool.java:310) ~[app.jar:?]
at com.orientechnologies.orient.core.db.OPartitionedDatabasePool.acquire(OPartitionedDatabasePool.java:268) ~[app.jar:?]
at com.tinkerpop.blueprints.impls.orient.OrientBaseGraph.<init>(OrientBaseGraph.java:145) ~[app.jar:?]
at com.tinkerpop.blueprints.impls.orient.OrientTransactionalGraph.<init>(OrientTransactionalGraph.java:77) ~[app.jar:?]
at com.tinkerpop.blueprints.impls.orient.OrientGraph.<init>(OrientGraph.java:135) ~[app.jar:?]
at com.tinkerpop.blueprints.impls.orient.OrientGraphFactory$1.getGraph(OrientGraphFactory.java:84) ~[app.jar:?]
at com.tinkerpop.blueprints.impls.orient.OrientGraphFactory.getTx(OrientGraphFactory.java:221) ~[app.jar:?]
at com.app.graph.impl.orientdb.OrientGraphPool.getTx(OrientGraphPool.java:88) ~[app.jar:?]
at com.app.graph.impl.orientdb.OrientGraphPool.lambda$loadSchema$0(OrientGraphPool.java:119) ~[app.jar:?]
at io.vertx.core.impl.VertxImpl$InternalTimerHandler.handle(VertxImpl.java:784) ~[app.jar:?]
at io.vertx.core.impl.VertxImpl$InternalTimerHandler.handle(VertxImpl.java:755) ~[app.jar:?]
at io.vertx.core.impl.ContextImpl.lambda$wrapTask$2(ContextImpl.java:324) ~[app.jar:?]
at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163) [app.jar:?]
at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:403) [app.jar:?]
at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:445) [app.jar:?]
at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858) [app.jar:?]
at java.lang.Thread.run(Thread.java:745) [?:1.8.0_112]
Caused by: com.orientechnologies.orient.core.index.OIndexException: Index type FULLTEXT is not supported by the engine 'LUCENE'. Types are [NOTUNIQUE_HASH_INDEX,FULLTEXT,UNIQUE,UNIQUE_HASH_INDEX,DICTIONARY,DICTIONARY_HASH_INDEX,NOTUNIQUE,FULLTEXT_HASH_INDEX]
DB name="db"
at com.orientechnologies.orient.core.index.OIndexes.findFactoryByAlgorithmAndType(OIndexes.java:167) ~[app.jar:?]
at com.orientechnologies.orient.core.index.OIndexes.createIndexEngine(OIndexes.java:174) ~[app.jar:?]
at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.openIndexes(OAbstractPaginatedStorage.java:361) ~[app.jar:?]
at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.open(OAbstractPaginatedStorage.java:317) ~[app.jar:?]
... 19 more

We've proceded with these steps:

- stop app.jar
- stop orientdb
- change app's configuration access to orientdb
- start app.jar

Here the dependecies specified in pom.xml

> <dependency>
	<groupId>com.orientechnologies</groupId>
	<artifactId>orientdb-core</artifactId>
	<version>2.2.27</version>
</dependency>

> <dependency>
	<groupId>com.orientechnologies</groupId>
	<artifactId>orientdb-graphdb</artifactId>
	<version>2.2.27</version>
</dependency>

> <dependency>
	<groupId>com.orientechnologies</groupId>
	<artifactId>orientdb-server</artifactId>
	<version>2.2.27</version>
</dependency>

> <dependency>
	<groupId>com.orientechnologies</groupId>
	<artifactId>orientdb-client</artifactId>
	<version>2.2.27</version>
</dependency> 

Is this the expected behaviour (i.e. because of the previous db creation/manipulation)?
Do we have to specify something at the code level?
Please, can you link us some documentation pages in order to better understand what's going on?

Thanks!

**Comment by luigidellaquila** [comment]
Hi @carloprad,

You just have to add Lucene dependencies to your pom.xml

```
<groupId>com.orientechnologies</groupId>
<artifactId>orientdb-lucene</artifactId>
<version>2.2.27</version>
```

This should solve the problem

Thanks

Luigi

**Comment by luigidellaquila** [comment]
Hi @carloprad 

Did you have a chance to check my suggestion? Did it help?

Thanks

Luigi

**Comment by luigidellaquila** [comment]
Hi @carloprad 

I'm closing this issue, please feel free to re-open if you need further help

Thanks

Luigi
