### ISSUE TITLE
OLogSegmentV2 cannot be cast to OLogSegmentV1

### ISSUE THREAD

**Issue by jamieb22** [orientechnologies/orientdb#7756]
## Expected behavior  
Upgraded Orient from 2.2.25 to 2.2.27. Expected database to open fine. 

## Actual behavior  

```
om.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.open(OAbstractPaginatedStorage.java:297) at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.open(ODatabaseDocumentTx.java:258) at com.tinkerpop.blueprints.impls.orient.OrientBaseGraph.openOrCreate(OrientBaseGraph.java:1918) at com.tinkerpop.blueprints.impls.orient.OrientBaseGraph.<init>(OrientBaseGraph.java:162) at com.tinkerpop.blueprints.impls.orient.OrientTransactionalGraph.<init>(OrientTransactionalGraph.java:102)

at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.open(OAbstractPaginatedSt
        at com.tinkerpop.blueprints.impls.orient.OrientTransactionalGraph.<init>(OrientTransactionalGraph.java:98)
        at com.tinkerpop.blueprints.impls.orient.OrientGraph.<init>(OrientGraph.java:103)
        ..
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassCastException: com.orientechnologies.orient.core.storage.impl.local.paginated.wal.OLogSegmentV2 cannot be cast to com.orientechnologies.orient.core.storage.impl.local.paginated.wal.OLogSegmentV1
        at com.orientechnologies.orient.core.storage.impl.local.paginated.wal.OLogSegmentV1.compareTo(OLogSegmentV1.java:397)
        at com.orientechnologies.orient.core.storage.impl.local.paginated.wal.OLogSegmentV1.compareTo(OLogSegmentV1.java:34)
        at java.util.ComparableTimSort.countRunAndMakeAscending(ComparableTimSort.java:320)
        at java.util.ComparableTimSort.sort(ComparableTimSort.java:188)
        at java.util.Arrays.sort(Arrays.java:1312)
        at java.util.Arrays.sort(Arrays.java:1506)
        at java.util.ArrayList.sort(ArrayList.java:1454)
        at java.util.Collections.sort(Collections.java:141)
        at com.orientechnologies.orient.core.storage.impl.local.paginated.wal.ODiskWriteAheadLog.<init>(ODiskWriteAheadLog.java:282)
        at com.orientechnologies.orient.core.storage.impl.local.paginated.wal.ODiskWriteAheadLog.<init>(ODiskWriteAheadLog.java:155)
        at com.orientechnologies.orient.core.storage.impl.local.paginated.OLocalPaginatedStorage.initWalAndDiskCache(OLocalPaginatedStorage.java:581)
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.open(OAbstractPaginatedStorage.java:259)
        ... 13 common frames omitted
```

<add here>  

## Steps to reproduce  
<add here>

**Comment by laa** [comment]
fixed
