### ISSUE TITLE
Deadlock at com.tinkerpop.blueprints.impls.orient.OrientBaseGraph.<init>(OrientBaseGraph.java:143)

### ISSUE THREAD

**Issue by hp1975** [orientechnologies/orientdb#7757]
## Expected behavior  
OrientGraphFactory.getTx shoud return the graph 

## Actual behavior  
OrientGraphFactory.getTx shoud return the graph but it's BLOCKED in this function

## Steps to reproduce  

"http-nio-9090-exec-133" - Thread t@70898
   java.lang.Thread.State: WAITING
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for <42831a72> (a java.util.concurrent.Semaphore$NonfairSync)
	at java.util.concurrent.locks.LockSupport.park(Unknown Source)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.parkAndCheckInterrupt(Unknown Source)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedInterruptibly(Unknown Source)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly(Unknown Source)
	at java.util.concurrent.Semaphore.acquire(Unknown Source)
	at com.orientechnologies.orient.core.db.OPartitionedDatabasePool.acquire(OPartitionedDatabasePool.java:196)
	at com.tinkerpop.blueprints.impls.orient.OrientBaseGraph.<init>(OrientBaseGraph.java:143)
	at com.tinkerpop.blueprints.impls.orient.OrientTransactionalGraph.<init>(OrientTransactionalGraph.java:77)
	at com.tinkerpop.blueprints.impls.orient.OrientGraph.<init>(OrientGraph.java:135)
	at com.tinkerpop.blueprints.impls.orient.OrientGraphFactory$1.getGraph(OrientGraphFactory.java:84)
	at com.tinkerpop.blueprints.impls.orient.OrientGraphFactory.getTx(OrientGraphFactory.java:221)
	at

**Comment by hp1975** [comment]
yes, it may be a pool problem, but threads in my application are blocked by this thread; the symtom looks a deadlock

**Comment by laa** [comment]
@hp1975 threads will be locked if connections are exhausted and not returned to the pool. Could you send a full thread dump as a gist?

**Comment by hp1975** [comment]
I can only send the full dump into your email address, and cc my boss.

**Comment by laa** [comment]
@hp1975 I understand a.lomakin@orientdb.com
