### ISSUE TITLE
live select seems broken in v3 (develop)

### ISSUE THREAD

**Issue by pvalsecc** [orientechnologies/orientdb#7761]
## Expected behavior  
I do on a freshly created DB:
```
CREATE CLASS Test EXTENDS V
CREATE PROPERTY Test.x STRING
LIVE SELECT FROM Test
```

I expect to receive notifications when stuff is added to the `Test` table.

## Actual behavior  

Instead, I get a NPE:
```
Exception `4AE37055` in storage `test`
com.orientechnologies.orient.core.exception.OCommandExecutionException: Error on execution of command: sql.LIVE SELECT FROM Test
        DB name="test"
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.executeCommand(OAbstractPaginatedStorage.java:3492)
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.command(OAbstractPaginatedStorage.java:3408)
        at com.orientechnologies.orient.core.sql.query.OSQLQuery.run(OSQLQuery.java:78)
        at com.orientechnologies.orient.core.sql.query.OSQLAsynchQuery.run(OSQLAsynchQuery.java:74)
        at com.orientechnologies.orient.core.sql.query.OSQLSynchQuery.run(OSQLSynchQuery.java:86)
        at com.orientechnologies.orient.core.query.OQueryAbstract.execute(OQueryAbstract.java:33)
        at com.orientechnologies.orient.core.sql.query.OLiveQuery.execute(OLiveQuery.java:70)
        at com.orientechnologies.orient.server.OConnectionBinaryExecutor.executeCommand(OConnectionBinaryExecutor.java:576)
        at com.orientechnologies.orient.client.remote.message.OCommandRequest.execute(OCommandRequest.java:103)
        at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.sessionRequest(ONetworkProtocolBinary.java:279)
        at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.execute(ONetworkProtocolBinary.java:185)
        at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:77)
Caused by: java.lang.NullPointerException
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentEmbedded.copy(ODatabaseDocumentEmbedded.java:302)
        at com.orientechnologies.orient.core.sql.OCommandExecutorSQLLiveSelect$1.call(OCommandExecutorSQLLiveSelect.java:65)
        at com.orientechnologies.orient.core.sql.OCommandExecutorSQLLiveSelect.execInSeparateDatabase(OCommandExecutorSQLLiveSelect.java:142)
        at com.orientechnologies.orient.core.sql.OCommandExecutorSQLLiveSelect.execute(OCommandExecutorSQLLiveSelect.java:63)
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.executeCommand(OAbstractPaginatedStorage.java:3471)
        ... 11 more
```

With 2.2.24, it works fine.

## Steps to reproduce  

See "Expected behavior "

**Comment by luigidellaquila** [comment]
Hi @pvalsecc 

How are you executing these statements? Can you please post a Java snippet?

Thanks

Luigi

**Comment by pvalsecc** [comment]
I develop an Erlang client library. 
Yes, I use root. Those are automated tests that create a fresh DB and run everything as root.

**Comment by luigidellaquila** [comment]
Ok, the problem is clear, we have to change a little bit the logic to manage server level users.
Assigning to @tglman for a check
Thanks

Luigi

**Comment by tglman** [comment]
hi @pvalsecc,

Just pushed a fix for this issue on develop branch, closing.

Bye

**Comment by pvalsecc** [comment]
Just tested develop. It's so broken at it's core that I cannot even create a database with it. Even with the web interface (studio).
I did:
```
mvn clean
mvn install -DskipTests
cd distribution/target/orientdb-community-3.0.0-SNAPSHOT.dir/orientdb-community-3.0.0-SNAPSHOT
bin/server.sh
# set the root passord
```

It shows 505 StackOverflowError with nothing in the logs.

**Comment by luigidellaquila** [comment]
Hi @pvalsecc 

I'm checking it, there seems to be a problem in the build.
I got an error 505 but not a StackOverflowError, do you have a stack trace?

Thanks

Luigi

**Comment by luigidellaquila** [comment]
Hi @pvalsecc 

Sorry, one of last commits created a problem with the authentication, I just reverted it, now it works fine

Thanks

Luigi

**Comment by pvalsecc** [comment]
@luigidellaquila No, no stacktrace. Checked stdout and the log file.

**Comment by tglman** [comment]
hi @pvalsecc,

I found the issue, it was due to the security plugin that was off in our test environments, I added tests with the security plugin on, this should be fixed now.

I'll reopen it, please close it if you can verify that is fixed.

**Comment by pvalsecc** [comment]
OK, tested with 5afc7ad009 and there is some progress. I can create the DB, subscribe to the live select, but the RID that comes in the push notification is wrong.

I create a record using "INSERT INTO Test (x) VALUES ('X')", The command returns a correct RID (#25:0), but the notification I get from my livre subscription has RID=#25:-2. I guess you send the notification before assigning the cluster position.

Do you want me to open a new issue or we continue on this one?

**Comment by pvalsecc** [comment]
I've created another issue: https://github.com/orientechnologies/orientdb/issues/7828
