### ISSUE TITLE
Frequent getting java.io.IOException: No locks available

### ISSUE THREAD

**Issue by JOSHI919** [orientechnologies/orientdb#7777]
### OS:  Ubuntu 16.04.2 LTS

1.  I have created multi tenant databases and getting frequent below mentioned error in individual databases (issue server log in point 7).
2.  Lets say i have total 10 databases in orientDB under database folder out of those 7 will work fine and for rest 3 i will get below error.

3. For months orientdb was working fine but now sudden this issue came and there was no change done in server.

4. If its a NFS(network file system) issue it should come in all 10 databases.

5. After orientdb server restart (shutdown.sh and server.sh) it will work fine for few minutes / hour but again same issue use to  start coming.

6. After opening individual connection to each database i am closing it, below is java code used.

OPartitionedDatabasePoolFactory poolFactory = null;   
 OPartitionedDatabasePool pool =null;
ODatabaseDocumentTx con=null;

try{
        poolFactory = new OPartitionedDatabasePoolFactory();
         pool = poolFactory.get(databaseIP,username,password);
        con=pool.acquire();
              // program logic ahead
}
 finally{
                    con.close();
                        pool.close();
                        poolFactory.close();
                }

7 .ORIENT DB ERROR LOG
   ===================
ANSI{green {db=dataBase2}} Error during storage close
java.io.IOException: No locks available
        at sun.nio.ch.FileDispatcherImpl.lock0(Native Method)
        at sun.nio.ch.FileDispatcherImpl.lock(FileDispatcherImpl.java:90)
        at sun.nio.ch.FileChannelImpl.tryLock(FileChannelImpl.java:1115)
        at java.nio.channels.FileChannel.tryLock(FileChannel.java:1155)
        at com.orientechnologies.orient.core.storage.fs.OFileClassic.lock(OFileClassic.java:744)
        at com.orientechnologies.orient.core.storage.fs.OFileClassic.openChannel(OFileClassic.java:813)
        at com.orientechnologies.orient.core.storage.fs.OFileClassic.open(OFileClassic.java:603)
        at com.orientechnologies.orient.core.storage.cache.local.OWOWCache.openFile(OWOWCache.java:1046)
        at com.orientechnologies.orient.core.storage.cache.local.OWOWCache.openFile(OWOWCache.java:341)
        at com.orientechnologies.orient.core.storage.cache.local.twoq.O2QCache.openFile(O2QCache.java:195)
        at com.orientechnologies.orient.core.storage.impl.local.paginated.base.ODurableComponent.openFile(ODurableComponent.java:183)
        at com.orientechnologies.orient.core.storage.impl.local.paginated.OClusterPositionMap.open(OClusterPositionMap.java:53)
        at com.orientechnologies.orient.core.storage.impl.local.paginated.OPaginatedCluster.open(OPaginatedCluster.java:227)
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.openClusters(OAbstractPaginatedStorage.java:290)
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.open(OAbstractPaginatedStorage.java:208)
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.open(ODatabaseDocumentTx.java:232)
        at com.orientechnologies.orient.server.OServer.openDatabase(OServer.java:915)
        at com.orientechnologies.orient.server.OServer.openDatabase(OServer.java:885)
        at com.orientechnologies.orient.server.OServer.openDatabase(OServer.java:876)
        at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.openDatabase(ONetworkProtocolBinary.java:706)
        at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.executeRequest(ONetworkProtocolBinary.java:345)
        at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.execute(ONetworkProtocolBinary.java:199)
        at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:77)

**Comment by lvca** [comment]
Issue already resolved long time ago, please upgrade to 2.2.28.
