### ISSUE TITLE
Distributed Graph Database : java.io.IOException: Permission denied

### ISSUE THREAD

**Issue by DrXala** [orientechnologies/orientdb#7784]
## Context
  * 1 serveur Linux Debian 9
  * 2 OrientDB instances version CE 2.2.28
  * Oracle Java 8

Instance odb-01 listner :
  * tcp/2524 (bin)
  * tcp/2580 (web)
  * tcp/2534 (hazelcast)

Intsance odb-02 listner :
  * tcp/2424 (bin)
  * tcp/2480 (web)
  * tcp/2434 (hazelcast)

I want to create one distributed graph database "MyTest" with two master nodes.

## Nodes configuration

odb-01 `orientdb-server-config.xml`:
```
        <handler class="com.orientechnologies.orient.server.hazelcast.OHazelcastPlugin">
            <parameters>
                <parameter value="true" name="enabled"/>
                <parameter value="${ORIENTDB_HOME}/config/default-distributed-db-config.json" name="configuration.db.default"/>
                <parameter value="${ORIENTDB_HOME}/config/hazelcast.xml" name="configuration.hazelcast"/>
                <parameter value="odb-01" name="nodeName"/>
            </parameters>
```
odb-02 `orientdb-server-config.xml`:
```
        <handler class="com.orientechnologies.orient.server.hazelcast.OHazelcastPlugin">
            <parameters>
                <parameter value="true" name="enabled"/>
                <parameter value="${ORIENTDB_HOME}/config/default-distributed-db-config.json" name="configuration.db.default"/>
                <parameter value="${ORIENTDB_HOME}/config/hazelcast.xml" name="configuration.hazelcast"/>
                <parameter value="odb-02" name="nodeName"/>
            </parameters>
```

odb-01 and odb-02 `default-distributed-db-config.json`:
```
{
  "autoDeploy": true,
  "readQuorum": 1,
  "writeQuorum": "majority",
  "executionMode": "undefined",
  "readYourWrites": true,
  "newNodeStrategy": "dynamic",
  "servers": {
    "*": "master"
  },
  "clusters": {
    "internal": {
    },
    "*": {
      "servers": ["<NEW_NODE>"]
    }
  }
}
```

odb-01 `hazelcast.xml`:
```
        <network>
                <port auto-increment="false">2534</port>
                <join>
                        <multicast enabled="false">
                                <multicast-group>235.1.1.1</multicast-group>
                                <multicast-port>2434</multicast-port>
                        </multicast>
                        <tcp-ip enabled="true">
                                <member>10.1.2.121:2434</member>
                        </tcp-ip>
                </join>
        </network>
```

odb-02 `hazelcast.xml`:
```
        <network>
                <port auto-increment="false">2434</port>
                <join>
                        <multicast enabled="false">
                                <multicast-group>235.1.1.1</multicast-group>
                                <multicast-port>2434</multicast-port>
                        </multicast>
                        <tcp-ip enabled="true">
                                <member>10.1.2.121:2534</member>
                        </tcp-ip>
                </join>
        </network>
```

## Problem

When I start odb-01 and odb-02 services, I look like this error in server log:
```
017-10-03 17:13:06:876 INFO  [odb-01] Received updated status odb-02.MyTest=SYNCHRONIZING [OHazelcastPlugin]
2017-10-03 17:13:06:877 INFO  [odb-01]->[odb-02] Deploying database MyTest... [OSyncDatabaseTask]
2017-10-03 17:13:06:877 INFO  [odb-01]->[odb-02] Deploy database task completed [OSyncDatabaseTask][odb-01]<-[odb-02] Error on executing distributed request 1.150 on local node: deploy_db
java.io.IOException: Permission non accordée
	at java.io.UnixFileSystem.createFileExclusively(Native Method)
	at java.io.File.createNewFile(File.java:1012)
	at com.orientechnologies.orient.server.distributed.impl.task.OSyncDatabaseTask.execute(OSyncDatabaseTask.java:98)
	at com.orientechnologies.orient.server.distributed.impl.ODistributedAbstractPlugin$1.call(ODistributedAbstractPlugin.java:604)
	at com.orientechnologies.orient.core.db.OScenarioThreadLocal.executeAsDistributed(OScenarioThreadLocal.java:70)
	at com.orientechnologies.orient.server.distributed.impl.ODistributedAbstractPlugin.executeOnLocalNode(ODistributedAbstractPlugin.java:600)
	at com.orientechnologies.orient.server.distributed.impl.ODistributedWorker.onMessage(ODistributedWorker.java:357)
	at com.orientechnologies.orient.server.distributed.impl.ODistributedWorker.run(ODistributedWorker.java:125)

2017-10-03 17:13:06:879 INFO  [odb-01]<-[odb-02] Received updated status odb-02.MyTest=NOT_AVAILABLE [OHazelcastPlugin]
2017-10-03 17:13:13:571 INFO  [odb-01] Distributed servers status (*=current @=lockManager[odb-01]):

+------------+------+-----------------------------+-----+---------+---------------+---------------+------------------------+
|Name        |Status|Databases                    |Conns|StartedOn|Binary         |HTTP           |UsedMemory              |
+------------+------+-----------------------------+-----+---------+---------------+---------------+------------------------+
|odb-01(*)(@)|ONLINE|MyTest=ONLINE (MASTER)       |3    |17:07:50 |10.1.2.121:2524|10.1.2.121:2580|782,26MB/3,83GB (19,93%)|
|odb-02      |ONLINE|MyTest=NOT_AVAILABLE (MASTER)|3    |17:08:06 |10.1.2.121:2424|10.1.2.121:2480|86,85MB/3,98GB (2,13%)  |
+------------+------+-----------------------------+-----+---------+---------------+---------------+------------------------+
```

Translate `java.io.IOException: Permission non accordée` by `java.io.IOException: Permission denied`.

So I have check the filesystem rules in all directory but it's ok, I think.

For odb-01 instance:
```
odb-01# ll config/
total 44
-rwxrwxrwx 1 orientdb orientdb  254 oct.   2 16:52 automatic-backup.json
drwxrwxrwx 2 orientdb orientdb    6 sept. 26 10:06 cert
-rwxrwxrwx 1 orientdb orientdb  403 oct.   3 16:23 default-distributed-db-config.json
-rwxrwxrwx 1 orientdb orientdb 2345 oct.   3 15:46 hazelcast.xml
-rwxrwxrwx 1 orientdb orientdb 1488 oct.   2 16:52 jdbc-drivers.json
-rwxrwxrwx 1 orientdb orientdb 1410 oct.   2 16:52 orientdb-client-log.properties
-rwxrwxrwx 1 orientdb orientdb 5585 oct.   3 17:07 orientdb-server-config.xml
-rwxrwxrwx 1 orientdb orientdb 5529 oct.   2 16:52 orientdb-server-config.xml.install
-rwxrwxrwx 1 orientdb orientdb 2011 oct.   3 14:13 orientdb-server-log.properties
-rwxrwxrwx 1 orientdb orientdb  993 oct.   2 16:52 security.json
odb-01# ll databases/
total 16
drwxr-xr-x 2 orientdb orientdb 8192 oct.   3 17:05 MyTest
drwxr-xr-x 2 orientdb orientdb 4096 oct.   3 17:05 OSystem
odb-01# ll databases/MyTest/
total 22944
-rw-r--r-- 1 orientdb orientdb     3200 oct.   3 17:05 cache.stt
-rw-r--r-- 1 orientdb orientdb      114 oct.   3 16:17 command-cache.json
-rw-r--r-- 1 orientdb orientdb     5405 oct.   3 16:17 database.ocf
-rw-r--r-- 1 orientdb orientdb     1024 oct.   3 16:17 default.cpm
...
```

For odb-02 instance:
```
odb-02# ll config/
total 44
-rwxrwxrwx 1 orientdb orientdb  254 oct.   2 16:03 automatic-backup.json
drwxrwxrwx 2 orientdb orientdb    6 oct.   2 16:03 cert
-rwxrwxrwx 1 orientdb orientdb  403 oct.   3 16:23 default-distributed-db-config.json
-rwxrwxrwx 1 orientdb orientdb 2344 oct.   3 15:45 hazelcast.xml
-rwxrwxrwx 1 orientdb orientdb 1488 oct.   2 16:03 jdbc-drivers.json
-rwxrwxrwx 1 orientdb orientdb 1410 oct.   2 16:03 orientdb-client-log.properties
-rwxrwxrwx 1 orientdb orientdb 5585 oct.   3 17:08 orientdb-server-config.xml
-rwxrwxrwx 1 orientdb orientdb 5529 oct.   2 16:03 orientdb-server-config.xml.install
-rwxrwxrwx 1 orientdb orientdb 2008 oct.   2 16:03 orientdb-server-log.properties
-rwxrwxrwx 1 orientdb orientdb  993 oct.   2 16:03 security.json
odb-02# ll databases/
total 16
drwxr-xr-x 2 orientdb orientdb 8192 oct.   3 17:38 MyTest
drwxr-xr-x 2 orientdb orientdb 4096 oct.   3 17:05 OSystem
odb-02# ll databases/MyTest/
total 22944
-rw-r--r-- 1 orientdb orientdb     3200 oct.   3 17:38 cache.stt
-rw-r--r-- 1 orientdb orientdb      114 oct.   3 16:17 command-cache.json
-rw-r--r-- 1 orientdb orientdb     5405 oct.   3 16:17 database.ocf
-rw-r--r-- 1 orientdb orientdb     1024 oct.   3 16:17 default.cpm
-rw-r--r-- 1 orientdb orientdb    66560 oct.   3 16:17 default.pcl
-rw-r--r-- 1 orientdb orientdb     1024 oct.   3 16:17 dictionary.nbt
-rw-r--r-- 1 orientdb orientdb    66560 oct.   3 16:17 dictionary.sbt
-rw-r--r-- 1 orientdb orientdb        2 oct.   3 17:38 dirty.fl
-rw-r--r-- 1 orientdb orientdb      394 oct.   3 17:08 distributed-config.json
-rw-r--r-- 1 orientdb orientdb      221 oct.   3 17:05 distributed-sync.json
...
```

Thank you

**Comment by DrXala** [comment]
Ok! I have fix my problem! 😃 

When a node is in 'synchronizing' state, he try to create a zipfile in `/tmp/orientdb`, but on my system, this directory didn't have sufficient rights for my user `orientdb`...

I don't understand why this directory didn't have `orientdb` right.

**Comment by lvca** [comment]
Cool, so it was only a configuration problem. Closing the issue then.
