### ISSUE TITLE
Micro-transactions cannot be rolled back when OrientDB engine is started with  -Dstorage.useWAL=false

### ISSUE THREAD

**Issue by BrunoSupiot** [orientechnologies/orientdb#7785]
## Expected behavior  
Trying a massive import from a JDBC database, we expected better performances with -Dstorage.useWAL=false (we don't use a transactional mode)

## Actual behavior  
[ERROR] 2017-10-04 13:22:40 [main] c.o.o.c.s.i.l.p.OLocalPaginatedStorage - $ANSI{green {db=connectitdb}} Exception `6161B39B` in storage `connectitdb` [142]
com.orientechnologies.orient.core.exception.OStorageException: WAL mode is not active. Transactions are not supported in given mode
	DB name="connectitdb"
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.rollback(OAbstractPaginatedStorage.java:2733)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.makeRollback(OAbstractPaginatedStorage.java:2666)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.commit(OAbstractPaginatedStorage.java:1665)
	at com.orientechnologies.orient.core.storage.impl.local.OMicroTransaction.doCommit(OMicroTransaction.java:372)
	at com.orientechnologies.orient.core.storage.impl.local.OMicroTransaction.commit(OMicroTransaction.java:161)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentAbstract.endMicroTransaction(ODatabaseDocumentAbstract.java:3105)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentAbstract.executeSaveRecord(ODatabaseDocumentAbstract.java:1627)
	at com.orientechnologies.orient.core.tx.OTransactionNoTx.saveNew(OTransactionNoTx.java:244)
	at com.orientechnologies.orient.core.tx.OTransactionNoTx.saveRecord(OTransactionNoTx.java:174)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentAbstract.save(ODatabaseDocumentAbstract.java:2434)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentAbstract.save(ODatabaseDocumentAbstract.java:93)
	at com.orientechnologies.orient.core.record.impl.ODocument.save(ODocument.java:2125)
	at com.orientechnologies.orient.core.record.impl.ODocument.save(ODocument.java:2116)
	at com.orientechnologies.orient.core.record.impl.ODocument.save(ODocument.java:63)
	at com.activus.connectit.storage.service.graph.AbstractGraphService.save(AbstractGraphService.java:410)

## Steps to reproduce  
massive Insertions in an non-transactional mode with   -Dstorage.useWAL=false.

**Comment by laa** [comment]
We can run TXs without WAL but without durability, of course, this check is not actual I will remove it soon.

**Comment by laa** [comment]
Fixed
