### ISSUE TITLE
java.lang.ArrayIndexOutOfBoundsException: 0 on dev build of CI 3.0

### ISSUE THREAD

**Issue by laa** [orientechnologies/orientdb#7794]
On CI we have got this exception 

java.lang.ArrayIndexOutOfBoundsException: 0
	at com.orientechnologies.orient.core.index.hashindex.local.OLocalHashTableWALTestIT.restoreDataFromWAL(OLocalHashTableWALTestIT.java:255)
	at com.orientechnologies.orient.core.index.hashindex.local.OLocalHashTableWALTestIT.assertFileRestoreFromWAL(OLocalHashTableWALTestIT.java:217)
	at com.orientechnologies.orient.core.index.hashindex.local.OLocalHashTableWALTestIT.testKeyDeleteRandomUniform(OLocalHashTableWALTestIT.java:168)

Standard Output

testKeyDeleteRandomUniform : 1507289765031
Start data restore

**Comment by laa** [comment]
Fixed in new version of WAL
