### ISSUE TITLE
ClassCastException in security module in 3.0 version

### ISSUE THREAD

**Issue by laa** [orientechnologies/orientdb#7804]
### OrientDB Version: 3.0 
If you run `mvn clean install` you will see:

```
java.lang.ClassCastException: java.util.LinkedHashMap cannot be cast to com.orientechnologies.orient.core.record.impl.ODocument
       at com.orientechnologies.orient.server.security.ODefaultServerSecurity.getSection(ODefaultServerSecurity.java:772)
        at com.orientechnologies.orient.server.security.ODefaultServerSecurity.onAfterDynamicPlugins(ODefaultServerSecurity.java:683)
        at com.orientechnologies.orient.server.security.ODefaultServerSecurity.reload(ODefaultServerSecurity.java:501)
        at com.orientechnologies.orient.server.OServerDatabaseOperationsTest.before(OServerDatabaseOperationsTest.java:52)
```

**Comment by maggiolo00** [comment]
Fixed
