### ISSUE TITLE
Debug Server

### ISSUE THREAD

**Issue by weickdev** [orientechnologies/orientdb#7814]
I want do debug the server code, so I follow [this](http://orientdb.com/docs/last/Contribute-to-OrientDB.html) guid to run the ```OServerMain```.  
Following the document, I set the JVM parameters as:
```
-server
-DORIENTDB_HOME=/Users/weickdev/codes/github/orientdb/graphdb
-Dorientdb.www.path=src/site
-Djava.util.logging.config.file=${ORIENTDB_HOME}/config/orientdb-server-log.properties
-Dorientdb.config.file=${ORIENTDB_HOME}/config/orientdb-server-config.xml
-Drhino.opt.level=9
-Ddistributed=true
```
But I run the server from the IDE, I get below error message:
```
2017-10-12 17:02:53:520 INFO  Listening http connections on 0.0.0.0:2480 (protocol v.10, socket=default) [OServerNetworkListener]java.lang.IllegalArgumentException: Cannot create custom command invoking the constructor: com.orientechnologies.orient.graph.server.command.OServerCommandGetGephi(com.orientechnologies.orient.server.config.OServerCommandConfiguration@4cb1daeb)
	at com.orientechnologies.orient.server.network.OServerNetworkListener.createCommand(OServerNetworkListener.java:131)
	at com.orientechnologies.orient.server.network.OServerNetworkListener.<init>(OServerNetworkListener.java:90)
	at com.orientechnologies.orient.server.OServer.activate(OServer.java:390)
	at com.orientechnologies.orient.server.OServerMain$1.run(OServerMain.java:46)
Caused by: java.lang.ClassNotFoundException: com.orientechnologies.orient.graph.server.command.OServerCommandGetGephi
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at com.orientechnologies.orient.server.network.OServerNetworkListener.createCommand(OServerNetworkListener.java:125)
	... 3 more
```

Is there anything wrong with my VM parameters?

**Comment by maggiolo00** [comment]
Are you using IntelliJ?

Seems that the class `OServerCommandGetGephi ` was not found. You should set the classpath of module `orientdb-graphdb`

**Comment by weickdev** [comment]
Hi @maggiolo00 I am using IntelliJ now. I could not quite understand the 'set the classpath of module orientdb-graphdb', I had added the orientdb-graphdb module to the orientdb-server module like this:

```File-> Project Structure-> Libraries and click green "+" to add the directory folder of module oritentdb-graphdb ```

So what do you mean by 'set the classpath of module orientdb-graphdb'? Should I set the classpath of orientdb-graphdb to some values?

**Comment by maggiolo00** [comment]
Try to set it here
<img width="1069" alt="screen shot 2017-10-12 at 12 16 23" src="https://user-images.githubusercontent.com/98812/31491596-2b0c30a8-af48-11e7-8ae9-1da9d655dced.png">

**Comment by weickdev** [comment]
@maggiolo00 , thanks, It works now. But after I input the root password, there alert another error:
```
+---------------------------------------------------------------+
|                WARNING: FIRST RUN CONFIGURATION               |
+---------------------------------------------------------------+
| This is the first time the server is running. Please type a   |
| password of your choice for the 'root' user or leave it blank |
| to auto-generate it.                                          |
|                                                               |
| To avoid this message set the environment variable or JVM     |
| setting ORIENTDB_ROOT_PASSWORD to the root password to use.   |
+---------------------------------------------------------------+

Root password [BLANK=auto generate it]: admin
Please confirm the root password: admin

2017-10-12 18:34:02:386 INFO  ODefaultPasswordAuthenticator is active [ODefaultPasswordAuthenticator]
2017-10-12 18:34:02:387 INFO  OServerConfigAuthenticator is active [OServerConfigAuthenticator]
2017-10-12 18:34:02:389 INFO  OSystemUserAuthenticator is active [OSystemUserAuthenticator]
2017-10-12 18:34:02:439 INFO  Installed GREMLIN language v.2.6.0 - graph.pool.max=50 [OGraphServerHandler]java.lang.ClassNotFoundException: com.orientechnologies.orient.server.hazelcast.OHazelcastPlugin
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at com.orientechnologies.orient.server.OServer.loadClass(OServer.java:220)
	at com.orientechnologies.orient.server.OServer.registerPlugins(OServer.java:1240)
	at com.orientechnologies.orient.server.OServer.activate(OServer.java:406)
	at com.orientechnologies.orient.server.OServerMain$1.run(OServerMain.java:46)

```

**Comment by maggiolo00** [comment]
Hi @weickdev 

sorry i didn't noticed that you were trying to spin the distributed environment. 
In that case instead of `orientdb-graphdb` you should select `orientdb-distributed` as classpath module.
This should fix the exception
Thanks

**Comment by weickdev** [comment]
@maggiolo00 I change it to standalone mode, now It start successfully, but there are some warnings:
```
2017-10-12 18:43:47:237 INFO  ODefaultPasswordAuthenticator is active [ODefaultPasswordAuthenticator]
2017-10-12 18:43:47:238 INFO  OServerConfigAuthenticator is active [OServerConfigAuthenticator]
2017-10-12 18:43:47:240 INFO  OSystemUserAuthenticator is active [OSystemUserAuthenticator]
2017-10-12 18:43:47:369 INFO  Installed GREMLIN language v.2.6.0 - graph.pool.max=50 [OGraphServerHandler]
2017-10-12 18:43:47:370 INFO  [OVariableParser.resolveVariables] Error on resolving property: distributed [orientechnologies]
2017-10-12 18:43:47:389 WARNI Authenticated clients can execute any kind of code into the server by using the following allowed languages: [sql] [OServerSideScriptInterpreter]
2017-10-12 18:43:47:400 INFO  OrientDB Studio available at http://10.10.10.22:2480/studio/index.html [OServer]
2017-10-12 18:43:47:400 INFO  OrientDB Server is active v2.2.28 (build 7f8db5be4bbc6b9f9382fdcce95c505c0588f238). [OServer]
2017-10-12 18:43:51:160 WARNI path variable points to 'src/site' but it doesn't exists [OServerCommandGetStaticContent]
2017-10-12 18:43:51:160 WARNI path variable points to 'src/site' but it isn't a directory [OServerCommandGetStaticContent]
2017-10-12 18:43:55:968 WARNI path variable points to 'src/site' but it doesn't exists [OServerCommandGetStaticContent]
2017-10-12 18:43:55:968 WARNI path variable points to 'src/site' but it isn't a directory [OServerCommandGetStaticContent]
2017-10-12 18:44:01:922 WARNI path variable points to 'src/site' but it doesn't exists [OServerCommandGetStaticContent]
2017-10-12 18:44:01:923 WARNI path variable points to 'src/site' but it isn't a directory [OServerCommandGetStaticContent]
2017-10-12 18:44:03:954 WARNI path variable points to 'src/site' but it doesn't exists [OServerCommandGetStaticContent]
2017-10-12 18:44:03:954 WARNI path variable points to 'src/site' but it isn't a directory [OServerCommandGetStaticContent]
```
And I can open the http://localhost:2048

**Comment by maggiolo00** [comment]
You can't right ?

**Comment by weickdev** [comment]
@maggiolo00 no I can't, I change the commit...

**Comment by maggiolo00** [comment]
hi @weickdev 
studio is not loaded automatically when developing running it from IDE
The best way to load studio is configure the `$ORIENTDB_HOME` and place a distribution of Studio 
under the folder `$ORIENTDB_HOME/plugins`

**Comment by weickdev** [comment]
hi @maggiolo00 , thank you so much. I connect my server via client, it works well now. By the way, if I want to run it out side the IDE, what should I do? One way I can think of is to replace the jar under lib directory of official version. Is there any other way?

**Comment by maggiolo00** [comment]
Hi @weickdev 

if you need to pack a distribution with some changes you can change the jar as you said
or you can do from the root directory of the source code
`mvn clean install -DskipTests` 

and then check under `distribution/target` folder for the packages

**Comment by weickdev** [comment]
@maggiolo00 It works, Thank you so much!
