### ISSUE TITLE
create edge throws ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by weickdev** [orientechnologies/orientdb#7837]
### OS: CentOS

When I insert edges, I find there are many logs like this:
```
com.orientechnologies.orient.core.exception.OStorageException: Error on executing command: sql.CREATE EDGE invest FROM (SELECT FROM Person WHERE _key="5F6F46D993DF8F72E40F612278D8968A") TO (SELECT FROM Company WHERE _key="49FD77C666507DD42F7069D635527E2F") CONTENT {"invest_amount_unit":"元","_from":"Person/5F6F46D993DF8F72E40F612278D8968A","entity_type":"invest","src_id":"5F6F46D993DF8F72E40F612278D8968A","invest_amount":"100000.0","utime":"2017-06-27 18:08:09","ctime":"2017-06-27 18:08:09","dst_id":"49FD77C666507DD42F7069D635527E2F","_to":"Company/49FD77C666507DD42F7069D635527E2F","_key":"0FC0CA6A63A3266EA1F0AA9C9CB48BB9"};
	DB name="dev"
	at com.orientechnologies.orient.client.remote.OStorageRemote.baseNetworkOperation(OStorageRemote.java:322) ~[orientdb-client-3.0.0m2.jar!/:3.0.0m2]
	at com.orientechnologies.orient.client.remote.OStorageRemote.networkOperationRetryTimeout(OStorageRemote.java:209) ~[orientdb-client-3.0.0m2.jar!/:3.0.0m2]
	at com.orientechnologies.orient.client.remote.OStorageRemote.networkOperation(OStorageRemote.java:237) ~[orientdb-client-3.0.0m2.jar!/:3.0.0m2]
	at com.orientechnologies.orient.client.remote.OStorageRemote.command(OStorageRemote.java:823) ~[orientdb-client-3.0.0m2.jar!/:3.0.0m2]
	at com.orientechnologies.orient.core.command.OCommandRequestTextAbstract.execute(OCommandRequestTextAbstract.java:68) ~[orientdb-core-3.0.0m2.jar!/:3.0.0m2]
	at com.tinkerpop.blueprints.impls.orient.OrientGraphCommand.execute(OrientGraphCommand.java:49) ~[orientdb-graphdb-3.0.0m2.jar!/:3.0.0m2]
	at com.haizhi.test.orientdb.runner.HbaseRelationScan.lambda$null$2(HbaseRelationScan.java:150) ~[classes!/:1.0-SNAPSHOT]
	at java.util.ArrayList.forEach(ArrayList.java:1249) ~[na:1.8.0_131]
	at com.haizhi.test.orientdb.runner.HbaseRelationScan.lambda$saveBySql$3(HbaseRelationScan.java:136) ~[classes!/:1.0-SNAPSHOT]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[na:1.8.0_131]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[na:1.8.0_131]
	at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_131]
Caused by: java.lang.ArrayIndexOutOfBoundsException: 687865856
	at com.orientechnologies.common.exception.OErrorCode.getErrorCode(OErrorCode.java:99) ~[orientdb-core-3.0.0m2.jar!/:3.0.0m2]
	at com.orientechnologies.orient.client.remote.message.OError37Response.read(OError37Response.java:37) ~[orientdb-client-3.0.0m2.jar!/:3.0.0m2]
	at com.orientechnologies.orient.client.binary.OChannelBinaryAsynchClient.handleStatus(OChannelBinaryAsynchClient.java:276) ~[orientdb-client-3.0.0m2.jar!/:3.0.0m2]
	at com.orientechnologies.orient.client.binary.OChannelBinaryAsynchClient.beginResponse(OChannelBinaryAsynchClient.java:195) ~[orientdb-client-3.0.0m2.jar!/:3.0.0m2]
	at com.orientechnologies.orient.client.binary.OChannelBinaryAsynchClient.beginResponse(OChannelBinaryAsynchClient.java:159) ~[orientdb-client-3.0.0m2.jar!/:3.0.0m2]
	at com.orientechnologies.orient.client.remote.OStorageRemote.beginResponse(OStorageRemote.java:1658) ~[orientdb-client-3.0.0m2.jar!/:3.0.0m2]
	at com.orientechnologies.orient.client.remote.OStorageRemote$2.execute(OStorageRemote.java:223) ~[orientdb-client-3.0.0m2.jar!/:3.0.0m2]
	at com.orientechnologies.orient.client.remote.OStorageRemote$2.execute(OStorageRemote.java:209) ~[orientdb-client-3.0.0m2.jar!/:3.0.0m2]
	at com.orientechnologies.orient.client.remote.OStorageRemote.baseNetworkOperation(OStorageRemote.java:273) ~[orientdb-client-3.0.0m2.jar!/:3.0.0m2]
	... 11 common frames omitted
```

**Comment by weickdev** [comment]
@tglman @laa How is this bug going? Will you fix it recently?

**Comment by zlfsimon** [comment]
+1

**Comment by weickdev** [comment]
@zlfsimon @laa Is there any feedback? Or how can we avoid this issue? This issue blocks us to test the other features of the V3.x

**Comment by laa** [comment]
Hi @weickdev , I will add workaround till @tglman will not fix it. Few minutes.

**Comment by laa** [comment]
@weickdev it should be fixed could you create new build and check?

**Comment by weickdev** [comment]
@laa Thanks so much. I check it right now.

**Comment by weickdev** [comment]
@laa It works well now, I close this issue, thanks for your help.
