### ISSUE TITLE
com.orientechnologies.orient.core.exception.OStorageException: Cannot put key value entry in index

### ISSUE THREAD

**Issue by ghost** [orientechnologies/orientdb#7848]
## Expected behavior  
Data from the database is displayed in the application.  

## Actual behavior  
My Application has access to the db, data is inserted in the db, but the select command shows no data. Login works. Everything works fine until 2.2.15. 2.2.16 and above are not working anymore. I probably think this is an issue with the lucene index.

`$ANSI{green {db=asdfasdf}} Exception `7E17F995` in storage `asdfasdf`
com.orientechnologies.orient.core.exception.OStorageException: Cannot put key value entry in index
	DB name="asdfasdf"
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.doCallIndexEngine(OAbstractPaginatedStorage.java:2339)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.callIndexEngine(OAbstractPaginatedStorage.java:2293)
	at com.orientechnologies.lucene.index.OLuceneIndexNotUnique.commitSnapshot(OLuceneIndexNotUnique.java:123)
	at com.orientechnologies.orient.core.index.OIndexAbstract.commit(OIndexAbstract.java:812)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.commitIndexes(OAbstractPaginatedStorage.java:1865)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.commit(OAbstractPaginatedStorage.java:1819)
	at com.orientechnologies.orient.core.tx.OTransactionOptimistic.doCommit(OTransactionOptimistic.java:541)
	at com.orientechnologies.orient.core.tx.OTransactionOptimistic.commit(OTransactionOptimistic.java:99)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.commit(ODatabaseDocumentTx.java:2915)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.commit(ODatabaseDocumentTx.java:2877)
	at com.orientechnologies.orient.core.command.script.OCommandExecutorScript.executeSQLScript(OCommandExecutorScript.java:357)
	at com.orientechnologies.orient.core.command.script.OCommandExecutorScript.executeSQL(OCommandExecutorScript.java:229)
	at com.orientechnologies.orient.core.command.script.OCommandExecutorScript.executeInContext(OCommandExecutorScript.java:105)
	at com.orientechnologies.orient.core.command.script.OCommandExecutorScript.execute(OCommandExecutorScript.java:89)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.executeCommand(OAbstractPaginatedStorage.java:3340)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.command(OAbstractPaginatedStorage.java:3278)
	at com.orientechnologies.orient.core.command.OCommandRequestTextAbstract.execute(OCommandRequestTextAbstract.java:69)
	at com.orientechnologies.orient.server.network.protocol.http.command.post.OServerCommandPostBatch.execute(OServerCommandPostBatch.java:196)
	at com.orientechnologies.orient.server.network.protocol.http.ONetworkProtocolHttpAbstract.service(ONetworkProtocolHttpAbstract.java:173)
	at com.orientechnologies.orient.server.network.protocol.http.ONetworkProtocolHttpAbstract.execute(ONetworkProtocolHttpAbstract.java:629)
	at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:81)
Caused by: org.apache.lucene.store.AlreadyClosedException: this IndexWriter is closed
	at org.apache.lucene.index.IndexWriter.ensureOpen(IndexWriter.java:719)
	at org.apache.lucene.index.IndexWriter.ensureOpen(IndexWriter.java:733)
	at org.apache.lucene.index.IndexWriter.updateDocument(IndexWriter.java:1471)
	at org.apache.lucene.index.IndexWriter.addDocument(IndexWriter.java:1254)
	at org.apache.lucene.index.TrackingIndexWriter.addDocument(TrackingIndexWriter.java:112)
	at com.orientechnologies.lucene.engine.OLuceneIndexEngineAbstract.addDocument(OLuceneIndexEngineAbstract.java:160)
	at com.orientechnologies.lucene.engine.OLuceneFullTextIndexEngine.put(OLuceneFullTextIndexEngine.java:149)
	at com.orientechnologies.lucene.index.OLuceneIndexNotUnique$2.callEngine(OLuceneIndexNotUnique.java:141)
	at com.orientechnologies.lucene.index.OLuceneIndexNotUnique$2.callEngine(OLuceneIndexNotUnique.java:123)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.doCallIndexEngine(OAbstractPaginatedStorage.java:2328)
	... 20 more
Caused by: java.io.IOException: Unable to unmap the mapped buffer: MMapIndexInput(path="mypath/databases/asdfasdf/luceneIndexes/idxV_scopeString/_0_Lucene50_0.doc")
	at org.apache.lucene.store.MMapDirectory$2.freeBuffer(MMapDirectory.java:329)
	at org.apache.lucene.store.ByteBufferIndexInput.freeBuffer(ByteBufferIndexInput.java:376)
	at org.apache.lucene.store.ByteBufferIndexInput.close(ByteBufferIndexInput.java:355)
	at org.apache.lucene.codecs.lucene50.Lucene50CompoundFormat.write(Lucene50CompoundFormat.java:92)
	at org.apache.lucene.index.IndexWriter.createCompoundFile(IndexWriter.java:4680)
	at org.apache.lucene.index.DocumentsWriterPerThread.sealFlushedSegment(DocumentsWriterPerThread.java:492)
	at org.apache.lucene.index.DocumentsWriterPerThread.flush(DocumentsWriterPerThread.java:459)
	at org.apache.lucene.index.DocumentsWriter.doFlush(DocumentsWriter.java:503)
	at org.apache.lucene.index.DocumentsWriter.flushAllThreads(DocumentsWriter.java:615)
	at org.apache.lucene.index.IndexWriter.getReader(IndexWriter.java:423)
	at org.apache.lucene.index.StandardDirectoryReader.doOpenFromWriter(StandardDirectoryReader.java:286)
	at org.apache.lucene.index.StandardDirectoryReader.doOpenIfChanged(StandardDirectoryReader.java:261)
	at org.apache.lucene.index.StandardDirectoryReader.doOpenIfChanged(StandardDirectoryReader.java:251)
	at org.apache.lucene.index.DirectoryReader.openIfChanged(DirectoryReader.java:123)
	at org.apache.lucene.search.SearcherManager.refreshIfNeeded(SearcherManager.java:137)
	at org.apache.lucene.search.SearcherManager.refreshIfNeeded(SearcherManager.java:58)
	at org.apache.lucene.search.ReferenceManager.doMaybeRefresh(ReferenceManager.java:176)
	at org.apache.lucene.search.ReferenceManager.maybeRefreshBlocking(ReferenceManager.java:253)
	at org.apache.lucene.search.ControlledRealTimeReopenThread.run(ControlledRealTimeReopenThread.java:245)
Caused by: java.lang.IllegalAccessException: class org.apache.lucene.store.MMapDirectory$2$1 cannot access class jdk.internal.ref.Cleaner (in module java.base) because module java.base does not export jdk.internal.ref to unnamed module @d773f22
	at java.base/jdk.internal.reflect.Reflection.newIllegalAccessException(Reflection.java:361)
	at java.base/java.lang.reflect.AccessibleObject.checkAccess(AccessibleObject.java:589)
	at java.base/java.lang.reflect.Method.invoke(Method.java:556)
	at org.apache.lucene.store.MMapDirectory$2$1.run(MMapDirectory.java:322)
	at org.apache.lucene.store.MMapDirectory$2$1.run(MMapDirectory.java:314)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at org.apache.lucene.store.MMapDirectory$2.freeBuffer(MMapDirectory.java:314)
	... 18 more
$ANSI{green {db=asdfasdf}} Exception `7E17F995` in storage `asdfasdf`
com.orientechnologies.orient.core.exception.OStorageException: Cannot put key value entry in index
	DB name="asdfasdf"
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.doCallIndexEngine(OAbstractPaginatedStorage.java:2339)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.callIndexEngine(OAbstractPaginatedStorage.java:2293)
	at com.orientechnologies.lucene.index.OLuceneIndexNotUnique.commitSnapshot(OLuceneIndexNotUnique.java:123)
	at com.orientechnologies.orient.core.index.OIndexAbstract.commit(OIndexAbstract.java:812)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.commitIndexes(OAbstractPaginatedStorage.java:1865)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.commit(OAbstractPaginatedStorage.java:1819)
	at com.orientechnologies.orient.core.tx.OTransactionOptimistic.doCommit(OTransactionOptimistic.java:541)
	at com.orientechnologies.orient.core.tx.OTransactionOptimistic.commit(OTransactionOptimistic.java:99)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.commit(ODatabaseDocumentTx.java:2915)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.commit(ODatabaseDocumentTx.java:2877)
	at com.orientechnologies.orient.core.command.script.OCommandExecutorScript.executeSQLScript(OCommandExecutorScript.java:357)
	at com.orientechnologies.orient.core.command.script.OCommandExecutorScript.executeSQL(OCommandExecutorScript.java:229)
	at com.orientechnologies.orient.core.command.script.OCommandExecutorScript.executeInContext(OCommandExecutorScript.java:105)
	at com.orientechnologies.orient.core.command.script.OCommandExecutorScript.execute(OCommandExecutorScript.java:89)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.executeCommand(OAbstractPaginatedStorage.java:3340)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.command(OAbstractPaginatedStorage.java:3278)
	at com.orientechnologies.orient.core.command.OCommandRequestTextAbstract.execute(OCommandRequestTextAbstract.java:69)
	at com.orientechnologies.orient.server.network.protocol.http.command.post.OServerCommandPostBatch.execute(OServerCommandPostBatch.java:196)
	at com.orientechnologies.orient.server.network.protocol.http.ONetworkProtocolHttpAbstract.service(ONetworkProtocolHttpAbstract.java:173)
	at com.orientechnologies.orient.server.network.protocol.http.ONetworkProtocolHttpAbstract.execute(ONetworkProtocolHttpAbstract.java:629)
	at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:81)
Caused by: org.apache.lucene.store.AlreadyClosedException: this IndexWriter is closed
	at org.apache.lucene.index.IndexWriter.ensureOpen(IndexWriter.java:719)
	at org.apache.lucene.index.IndexWriter.ensureOpen(IndexWriter.java:733)
	at org.apache.lucene.index.IndexWriter.updateDocument(IndexWriter.java:1471)
	at org.apache.lucene.index.IndexWriter.addDocument(IndexWriter.java:1254)
	at org.apache.lucene.index.TrackingIndexWriter.addDocument(TrackingIndexWriter.java:112)
	at com.orientechnologies.lucene.engine.OLuceneIndexEngineAbstract.addDocument(OLuceneIndexEngineAbstract.java:160)
	at com.orientechnologies.lucene.engine.OLuceneFullTextIndexEngine.put(OLuceneFullTextIndexEngine.java:149)
	at com.orientechnologies.lucene.index.OLuceneIndexNotUnique$2.callEngine(OLuceneIndexNotUnique.java:141)
	at com.orientechnologies.lucene.index.OLuceneIndexNotUnique$2.callEngine(OLuceneIndexNotUnique.java:123)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.doCallIndexEngine(OAbstractPaginatedStorage.java:2328)
	... 20 more
Caused by: java.io.IOException: Unable to unmap the mapped buffer: MMapIndexInput(path="mypath/databases/asdfasdf/luceneIndexes/idxV_scopeString/_0_Lucene50_0.doc")
	at org.apache.lucene.store.MMapDirectory$2.freeBuffer(MMapDirectory.java:329)
	at org.apache.lucene.store.ByteBufferIndexInput.freeBuffer(ByteBufferIndexInput.java:376)
	at org.apache.lucene.store.ByteBufferIndexInput.close(ByteBufferIndexInput.java:355)
	at org.apache.lucene.codecs.lucene50.Lucene50CompoundFormat.write(Lucene50CompoundFormat.java:92)
	at org.apache.lucene.index.IndexWriter.createCompoundFile(IndexWriter.java:4680)
	at org.apache.lucene.index.DocumentsWriterPerThread.sealFlushedSegment(DocumentsWriterPerThread.java:492)
	at org.apache.lucene.index.DocumentsWriterPerThread.flush(DocumentsWriterPerThread.java:459)
	at org.apache.lucene.index.DocumentsWriter.doFlush(DocumentsWriter.java:503)
	at org.apache.lucene.index.DocumentsWriter.flushAllThreads(DocumentsWriter.java:615)
	at org.apache.lucene.index.IndexWriter.getReader(IndexWriter.java:423)
	at org.apache.lucene.index.StandardDirectoryReader.doOpenFromWriter(StandardDirectoryReader.java:286)
	at org.apache.lucene.index.StandardDirectoryReader.doOpenIfChanged(StandardDirectoryReader.java:261)
	at org.apache.lucene.index.StandardDirectoryReader.doOpenIfChanged(StandardDirectoryReader.java:251)
	at org.apache.lucene.index.DirectoryReader.openIfChanged(DirectoryReader.java:123)
	at org.apache.lucene.search.SearcherManager.refreshIfNeeded(SearcherManager.java:137)
	at org.apache.lucene.search.SearcherManager.refreshIfNeeded(SearcherManager.java:58)
	at org.apache.lucene.search.ReferenceManager.doMaybeRefresh(ReferenceManager.java:176)
	at org.apache.lucene.search.ReferenceManager.maybeRefreshBlocking(ReferenceManager.java:253)
	at org.apache.lucene.search.ControlledRealTimeReopenThread.run(ControlledRealTimeReopenThread.java:245)
Caused by: java.lang.IllegalAccessException: class org.apache.lucene.store.MMapDirectory$2$1 cannot access class jdk.internal.ref.Cleaner (in module java.base) because module java.base does not export jdk.internal.ref to unnamed module @d773f22
	at java.base/jdk.internal.reflect.Reflection.newIllegalAccessException(Reflection.java:361)
	at java.base/java.lang.reflect.AccessibleObject.checkAccess(AccessibleObject.java:589)
	at java.base/java.lang.reflect.Method.invoke(Method.java:556)
	at org.apache.lucene.store.MMapDirectory$2$1.run(MMapDirectory.java:322)
	at org.apache.lucene.store.MMapDirectory$2$1.run(MMapDirectory.java:314)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at org.apache.lucene.store.MMapDirectory$2.freeBuffer(MMapDirectory.java:314)
	... 18 more
`

**Comment by maggiolo00** [comment]
Hi @medworker 

this seems a problem with lucene and Java 9,
we use lucene  version `5.3.2` and i think it doesn't play well with it. 
Can you try with Java 8 ?

Thanks

**Comment by medworker** [comment]
Hello @maggiolo00 
thanks that helps, the above errors are gone with Java 8.
But i have still some issues

`$ANSI{green {db=adsf}} Fetching error on record #71:192
java.lang.ClassCastException: com.orientechnologies.orient.core.db.record.OTrackedMap cannot be cast to com.orientechnologies.orient.core.db.record.OIdentifiable
	at com.orientechnologies.orient.core.fetch.OFetchHelper.fetchCollectionRidMap(OFetchHelper.java:216)
	at com.orientechnologies.orient.core.fetch.OFetchHelper.fetchRidMap(OFetchHelper.java:193)
	at com.orientechnologies.orient.core.fetch.OFetchHelper.processRecordRidMap(OFetchHelper.java:175)
	at com.orientechnologies.orient.core.fetch.OFetchHelper.updateRidMap(OFetchHelper.java:270)
	at com.orientechnologies.orient.core.fetch.OFetchHelper.fetchDocumentRidMap(OFetchHelper.java:207)
	at com.orientechnologies.orient.core.fetch.OFetchHelper.fetchRidMap(OFetchHelper.java:190)
	at com.orientechnologies.orient.core.fetch.OFetchHelper.processRecordRidMap(OFetchHelper.java:175)
	at com.orientechnologies.orient.core.fetch.OFetchHelper.updateRidMap(OFetchHelper.java:270)
	at com.orientechnologies.orient.core.fetch.OFetchHelper.fetchCollectionRidMap(OFetchHelper.java:221)
	at com.orientechnologies.orient.core.fetch.OFetchHelper.fetchRidMap(OFetchHelper.java:193)
	at com.orientechnologies.orient.core.fetch.OFetchHelper.processRecordRidMap(OFetchHelper.java:175)
	at com.orientechnologies.orient.core.fetch.OFetchHelper.fetch(OFetchHelper.java:75)
	at com.orientechnologies.orient.core.serialization.serializer.record.string.ORecordSerializerJSON.toString(ORecordSerializerJSON.java:354)
	at com.orientechnologies.orient.core.serialization.serializer.record.string.ORecordSerializerStringAbstract.toString(ORecordSerializerStringAbstract.java:672)
	at com.orientechnologies.orient.core.record.ORecordAbstract.toJSON(ORecordAbstract.java:191)
	at com.orientechnologies.orient.server.network.protocol.http.OHttpResponse.formatMultiValue(OHttpResponse.java:416)
	at com.orientechnologies.orient.server.network.protocol.http.OHttpResponse.writeRecordsOnStream(OHttpResponse.java:365)
	at com.orientechnologies.orient.server.network.protocol.http.OHttpResponse.writeRecords(OHttpResponse.java:350)
	at com.orientechnologies.orient.server.network.protocol.http.OHttpGraphResponse.writeRecords(OHttpGraphResponse.java:63)
	at com.orientechnologies.orient.server.network.protocol.http.OHttpResponse.writeResult(OHttpResponse.java:230)
	at com.orientechnologies.orient.server.network.protocol.http.command.post.OServerCommandPostCommand.execute(OServerCommandPostCommand.java:134)
	at com.orientechnologies.orient.graph.server.command.OServerCommandPostCommandGraph.execute(OServerCommandPostCommandGraph.java:37)
	at com.orientechnologies.orient.server.network.protocol.http.ONetworkProtocolHttpAbstract.service(ONetworkProtocolHttpAbstract.java:173)
	at com.orientechnologies.orient.server.network.protocol.http.ONetworkProtocolHttpAbstract.execute(ONetworkProtocolHttpAbstract.java:629)
	at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:81)`

**Comment by medworker** [comment]
Hello @maggiolo00,
i would like to keep you up to date. We have not solved the issue so far.
In detail: Everything works fine unter version 2.2.15. With version 2.2.16 and above, it looks like we have a problem with the lucene index. I have queries which response with an empty result. When i remove the lucene index from the query, then the query returns a result. We are currently try to find the problem.

**Comment by maggiolo00** [comment]
Hi @medworker 

so the previous error with JAVA 8 is gone and now with version >= 2.2.16 you are getting the issue above?

Do you have a way to reproduce it so i we can fix this ?

Thanks

**Comment by medworker** [comment]
Hi @maggiolo00 
i hope this helps. I have the following query in 2.2.15, this query gets "44" as result.

`SELECT count(*) FROM MeetingPublished LET $bpl = (select from (traverse in_MeetingPersonLink from $parent.$current) where @class = "MeetingPersonLink" and out = #169:1 and isRead = true) WHERE (((_scopeString LUCENE 'any OR ((18a44ed5c7e64bf7b1c3ecbe8a5644c6 OR anyMEDClient) AND (f44e2a42756d462396771642fed1413d OR anyTeam) AND (c89c123e82c74124b2847368a5be7ba6 OR anyPerson))') and (((MeetingType is not null) and (MeetingType.key <> 'approvalRequest') and (MeetingType.key <> 'serviceInstruction') and (MeetingType.key <> 'agendaPoint')) and (($bpl.size() = 0) AND (isDone IS null)))) and _deleted = false)`

then i change the database to 2.2.16 and rerun the query, i always get "44" as result. Our application can make new records, they are stored correctly in the database, but they are not shown in version 2.2.16. If i change the db to 2.2.15 the above inserted records are shown again.

So if i now make a indexRebuild in version 2.2.16, the above query get "0" as result. If i remove the WHERE clause with the "_scopeString" then i get "113" as result. So i guess we have some problem with the lucene index. But i can be wrong, i´m not a database expert, but this is the only thing i found out.

So i don´t know if it´s a problem with our application or with the database? All version from 2.2.16 to 2.2.29 are not working for us, with the same problem.

I hope this was clear enough?

thx

**Comment by maggiolo00** [comment]
Hi @medworker 

do you see exceptions with 2.2.16 - 2.2.29?

**Comment by maggiolo00** [comment]
Is there any chance you could share a dataset that is affected by this?

Thanks

**Comment by medworker** [comment]
Hello,
sure, give me your contact details or another option, then i will send you a database with this issue.
thx

**Comment by maggiolo00** [comment]
Hi @medworker 

you can send the database or the instructions to `e.risa@orientdb.com` 

Thanks

**Comment by hosseinGanjyar** [comment]
I've this error for insert data to index column...
I don't using JAVA v8..I want using latest java version.... please solved this problem,,,,
