### ISSUE TITLE
console.bat - IllegalArgumentException: Unknown signal: WINCH

### ISSUE THREAD

**Issue by fc90** [orientechnologies/orientdb#7863]
## Expected behavior  
OrientDB console should start when console.bat is executed

## Actual behavior  
The following exception is thrown:
Exception in thread "main" java.lang.ExceptionInInitializerError
        at com.orientechnologies.orient.graph.console.OGremlinConsole.main(OGremlinConsole.java:70)
Caused by: java.lang.IllegalArgumentException: Unknown signal: WINCH
        at sun.misc.Signal.<init>(Unknown Source)
        at com.orientechnologies.common.console.TTYConsoleReader.<clinit>(TTYConsoleReader.java:58)
        ... 1 more

## Steps to reproduce  
execute console.bat

**Comment by luigidellaquila** [comment]
Hi @fc90 

I just pushed a fix for this on v 2.2.x branch. Could you please try it and let me know if it works fine on your system?

Thanks

Luigi

**Comment by fc90** [comment]
Hi @luigidellaquila 

yes the patch fixes the problem. I think the issue can be closed! 

Thank you for the quick answer. 

Fabio
