### ISSUE TITLE
Orient - Non fair sync

### ISSUE THREAD

**Issue by rbaarathinms** [orientechnologies/orientdb#7870]
Hi @laa, We are starting our orient in embedded mode.
Our orient version is 2.2.20
Java version - jdk1.8.0_121

 - parking to wait for  <0x00002ab48cd75d08> (a java.util.concurrent.locks.ReentrantReadWriteLock$NonfairSync)
    at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
    at java.util.concurrent.locks.AbstractQueuedSynchronizer.parkAndCheckInterrupt(AbstractQueuedSynchronizer.java:836)
    at java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireShared(AbstractQueuedSynchronizer.java:967)
    at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireShared(AbstractQueuedSynchronizer.java:1283)
    at java.util.concurrent.locks.ReentrantReadWriteLock$ReadLock.lock(ReentrantReadWriteLock.java:727)
    at com.orientechnologies.common.concur.lock.OOneEntryPerKeyLockManager.acquireLock(OOneEntryPerKeyLockManager.java:169)
    at com.orientechnologies.common.concur.lock.OOneEntryPerKeyLockManager.acquireLock(OOneEntryPerKeyLockManager.java:101)
    at com.orientechnologies.orient.core.storage.impl.local.paginated.atomicoperations.OAtomicOperationsManager.acquireReadLock(OAtomicOperationsManager.java:519)
    at com.orientechnologies.orient.core.index.hashindex.local.OLocalHashTable.get(OLocalHashTable.java:325)
    at com.orientechnologies.orient.core.index.engine.OHashTableIndexEngine.get(OHashTableIndexEngine.java:145)
    at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.doGetIndexValue(OAbstractPaginatedStorage.java:1764)
    at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.getIndexValue(OAbstractPaginatedStorage.java:1753)
    at com.orientechnologies.orient.core.index.OIndexMultiValues.get(OIndexMultiValues.java:67)
    at com.orientechnologies.orient.core.index.OIndexMultiValues.get(OIndexMultiValues.java:44)
    at com.orientechnologies.orient.core.index.OIndexAbstractDelegate.get(OIndexAbstractDelegate.java:58)
    at com.orientechnologies.orient.core.index.OIndexTxAwareMultiValue.get(OIndexTxAwareMultiValue.java:297)
    at com.orientechnologies.orient.core.index.OIndexTxAwareMultiValue.get(OIndexTxAwareMultiValue.java:39)
    at in.co.nmsworks.documenttdb.db.DocDB.getDocTypeObjects(DocDB.java:151)
    at in.co.nmsworks.documenttdb.db.DocDB.getDocTypeObjects(DocDB.java:173)
    at in.co.nmsworks.cygnet.telecom.fault.rcasia.inventory.store.SDHRcaInvReader.getOtherEndNodes(SDHRcaInvReader.java:732)
    at in.co.nmsworks.cygnet.telecom.fault.rcasia.inventory.store.SDHRcaInvReader.getRelationshipAndOtherEndNodes(SDHRcaInvReader.java:1800)
    at in.co.nmsworks.cygnet.telecom.fault.rcasia.inventory.store.PatternTreeBuilder.fillPatternTree(PatternTreeBuilder.java:89)
    at in.co.nmsworks.cygnet.telecom.fault.rcasia.inventory.store.PatternTreeBuilder.processTreeBuildingForPTP(PatternTreeBuilder.java:137)
    at in.co.nmsworks.cygnet.telecom.fault.rcasia.inventory.store.PatternTreeBuilder.fillPatternTree(PatternTreeBuilder.java:79)
    at in.co.nmsworks.cygnet.telecom.fault.rcasia.inventory.store.PatternTreeBuilder.buildPatternTree(PatternTreeBuilder.java:62)
    at in.co.nmsworks.cygnet.telecom.fault.rcasia.inventory.store.PatternTreeBuilder.getImpactAnalysisDataHolder(PatternTreeBuilder.java:48)
    at in.co.nmsworks.cygnet.telecom.fault.rcasia.inventory.store.SDHRcaInvReader.buildImpactAnalysisDataHolder(SDHRcaInvReader.java:561)
    at in.co.nmsworks.cygnet.telecom.fault.rcasia.inventory.store.SDHRcaInvReader.buildImpactAnalysisDataHolder(SDHRcaInvReader.java:538)
    at in.co.nmsworks.cygnet.telecom.fault.rcasia.plug.impl.circuit.impact.node.constructor.impl2.InventoryDataUtils.getImpactAnalysisDataHolder(InventoryDataUtils.java:648)
    at in.co.nmsworks.cygnet.telecom.fault.rcasia.plug.impl.circuit.impact.node.constructor.impl2.DefaultImpactAnalysisDataBuilder.buildImpactAnalysisData(DefaultImpactAnalysisDataBuilder.java:34)
    at in.co.nmsworks.cygnet.telecom.fault.rcasia.plug.impl.circuit.impl2.CircuitPlugHelper.getImpactAnalysisDataHolder(CircuitPlugHelper.java:171)
    at in.co.nmsworks.cygnet.telecom.fault.rcasia.plug.impl.circuit.impl2.CircuitPlug.getImpactAnalysisDataHolder(CircuitPlug.java:314)
    at in.co.nmsworks.cygnet.telecom.fault.rcasia.plug.impl.circuit.impl2.CircuitPlug.acquireLockAndReturnWrapperForAnalyze(CircuitPlug.java:163)
    at in.co.nmsworks.cygnet.telecom.fault.rcasia.plug.impl.circuit.impl2.CircuitPlug.getLockResource(CircuitPlug.java:117)
    at in.co.nmsworks.cygnet.telecom.fault.rcasia.plug.Plug.lock(Plug.java:615)
    at in.co.nmsworks.cygnet.telecom.fault.rcasia.plug.Plug.doWorkForSingleEvent(Plug.java:261)
    at in.co.nmsworks.cygnet.telecom.fault.rcasia.plug.Plug.computeAndStore(Plug.java:231)
    at in.co.nmsworks.cygnet.telecom.fault.rcasia.server.PlugJob.doWork(PlugJob.java:151)
    at com.nmsworks.cygnet.util.treejob.TreeJob.run(TreeJob.java:44)
    at com.nmsworks.cygnet.util.orderingexecutor.MultiKeyOrderingExecutor$DependentJob.run(MultiKeyOrderingExecutor.java:351)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)

We are getting the above exception. U were asking for orient server logs, tell us how to enable orient logs..????

**Comment by laa** [comment]
Hi, @rbaarathinms .
That is not an exception. Maybe you sent me a different part of the application log?
For the enabling of server logs you can start your JVM with the following system property `-Djava.util.logging.config.file=orientdb_log.properties` . Content of `orientdb_log.properties` file may be like that https://gist.github.com/laa/4828bbb6a51ad2e37111f687fb320b59 .

**Comment by laa** [comment]
Hi @rbaarathinms could you clarify what do you mean?

**Comment by laa** [comment]
closing because of no reply.
