### ISSUE TITLE
StackOverflow while starting in OSGi environment

### ISSUE THREAD

**Issue by Dmitry-PlainID** [orientechnologies/orientdb#7882]
### OS: Mac  

This happened when ODatabaseRecordThreadLocal.INSTANCE changed to ODatabaseRecordThreadLocal.instance()

## Steps to reproduce  
OServer oServer = OServerMain.create();
oServer.setServerRootDirectory(ORIENTDB_HOME);
oServer.startup(new File(ORIENTDB_HOME, SERVER_CONF));
oServer.activate();

While initialising the OScriptManager  `ScriptEngineManager.getEngineByName` returns null, so you write warning message and entrancing to infinity loop.

## Stack trace
	at com.orientechnologies.orient.core.command.script.OScriptManager.<init>(OScriptManager.java:58) ~[?:?]
        at com.orientechnologies.orient.core.Orient.<init>(Orient.java:75) ~[?:?]
        at com.orientechnologies.orient.core.Orient.instance(Orient.java:171) ~[?:?]
        at com.orientechnologies.orient.core.db.ODatabaseRecordThreadLocal.instance(ODatabaseRecordThreadLocal.java:45) ~[?:?]
        at com.orientechnologies.common.log.OLogManager.log(OLogManager.java:101) ~[?:?]
        at com.orientechnologies.common.log.OLogManager.warn(OLogManager.java:186) ~[?:?]
        at com.orientechnologies.orient.core.command.script.OScriptManager.<init>(OScriptManager.java:72) ~[?:?]
        at com.orientechnologies.orient.core.Orient.<init>(Orient.java:75) ~[?:?]
        at com.orientechnologies.orient.core.Orient.instance(Orient.java:171) ~[?:?]
        at com.orientechnologies.orient.core.db.ODatabaseRecordThreadLocal.instance(ODatabaseRecordThreadLocal.java:45) ~[?:?]
        at com.orientechnologies.common.log.OLogManager.log(OLogManager.java:101) ~[?:?]
        at com.orientechnologies.common.log.OLogManager.warn(OLogManager.java:186) ~[?:?]
        at com.orientechnologies.orient.core.command.script.OScriptManager.<init>(OScriptManager.java:72) ~[?:?]
        at com.orientechnologies.orient.core.Orient.<init>(Orient.java:75) ~[?:?]
        at com.orientechnologies.orient.core.Orient.instance(Orient.java:171) ~[?:?]
        at com.orientechnologies.orient.core.db.ODatabaseRecordThreadLocal.instance(ODatabaseRecordThreadLocal.java:45) ~[?:?]

**Comment by laa** [comment]
@Dmitry-PlainID it is a simple issue, I will fix it tomorrow.

**Comment by laa** [comment]
Fixed in 2.2.x will move to 3.0 tomorrow

**Comment by laa** [comment]
@Dmitry-PlainID could you check the changes?

**Comment by Dmitry-PlainID** [comment]
It works, 
Thanks
