### ISSUE TITLE
NoClassDefFoundError OSecuritySystem

### ISSUE THREAD

**Issue by thanveeraqtharah** [orientechnologies/orientdb#7889]
## Expected behavior  
Below is the Dependency details  :

                 <dependency>
			<groupId>com.orientechnologies</groupId>
			<artifactId>orientdb-server</artifactId>
			<version>2.2.30</version>
		</dependency>
		<dependency>
			<groupId>com.orientechnologies</groupId>
			<artifactId>orientdb-enterprise</artifactId>
			<version>2.1.25</version>
		</dependency>  
                

Earlier I was using orientDb version 2.1.19  and it was working fine without any exception. But I had to use 'MATCH'. So I was told to upgrade the version to 2.2.30 as previous version had no support for 'MATCH'.

## Actual behavior  
Below exception is thrown.

Exception in thread "main" java.lang.NoClassDefFoundError: com/orientechnologies/orient/core/security/OSecuritySystem
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at com.orientechnologies.orient.server.OServerMain.create(OServerMain.java:26)
	at com.superizzi.prismapp.db.DatabaseHelper.startServer(DatabaseHelper.java:16)
	at com.superizzi.prismapp.PrismAppApplication.main(PrismAppApplication.java:14)
Caused by: java.lang.ClassNotFoundException: com.orientechnologies.orient.core.security.OSecuritySystem
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 15 more

## Steps to reproduce  
Please let me know how to get rid of this Exception

**Comment by luigidellaquila** [comment]
Hi @thanveeraqtharah 

I think the problem is in the mix of 2.2.30 with 2.1.25, please try to use the following and remove all the other dependencies

```
        <dependency>
		<groupId>com.orientechnologies</groupId>
		<artifactId>orientdb-graphdb</artifactId>
		<version>2.2.30</version>
	</dependency> 
        <dependency>
		<groupId>com.orientechnologies</groupId>
		<artifactId>orientdb-server</artifactId>
		<version>2.2.30</version>
	</dependency> 

``` 

Thanks

Luigi

**Comment by thanveeraqtharah** [comment]
Thank you , it got solved:)
