### ISSUE TITLE
java.lang.IllegalArgumentException Exception while creating record

### ISSUE THREAD

**Issue by Archana3007** [orientechnologies/orientdb#7900]
## Expected behavior  
It should be able to save the new vertex 

## Actual behavior  
It is giving error while commiting the Graph transaction by graph.commit(); 

##Error

2017-11-26 18:01:38,498 ERROR [io.undertow.request] (default task-35) UT005023: Exception handling request to /crl-api/rest/MEV: org.jboss.resteasy.spi.UnhandledException: com.orientechnologies.orient.core.exception.OPaginatedClusterException: Error during record deletion
        DB name="cm_data"
        Component Name="mev_3"
        DB name="cm_data"
        Component Name="mev_3"
        at org.jboss.resteasy.core.ExceptionHandler.handleApplicationException(ExceptionHandler.java:76) [resteasy-jaxrs-3.0.10.Final.jar:]
        at org.jboss.resteasy.core.ExceptionHandler.handleException(ExceptionHandler.java:212) [resteasy-jaxrs-3.0.10.Final.jar:]
        at org.jboss.resteasy.core.SynchronousDispatcher.writeException(SynchronousDispatcher.java:149) [resteasy-jaxrs-3.0.10.Final.jar:]
        at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:372) [resteasy-jaxrs-3.0.10.Final.jar:]
        at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:179) [resteasy-jaxrs-3.0.10.Final.jar:]
        at org.jboss.resteasy.plugins.server.servlet.ServletContainerDispatcher.service(ServletContainerDispatcher.java:220) [resteasy-jaxrs-3.0.10.Final.jar:]
        at org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:56) [resteasy-jaxrs-3.0.10.Final.jar:]
        at org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:51) [resteasy-jaxrs-3.0.10.Final.jar:]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:790) [jboss-servlet-api_3.1_spec-1.0.0.Final.jar:1.0.0.Final]
        at io.undertow.servlet.handlers.ServletHandler.handleRequest(ServletHandler.java:85) [undertow-servlet-1.1.0.Final.jar:1.1.0.Final]
        at io.undertow.servlet.handlers.security.ServletSecurityRoleHandler.handleRequest(ServletSecurityRoleHandler.java:61) [undertow-servlet-1.1.0.Final.jar:1.1.0.Final]
        at io.undertow.servlet.handlers.ServletDispatchingHandler.handleRequest(ServletDispatchingHandler.java:36) [undertow-servlet-1.1.0.Final.jar:1.1.0.Final]
        at org.wildfly.extension.undertow.security.SecurityContextAssociationHandler.handleRequest(SecurityContextAssociationHandler.java:78)
        at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43) [undertow-core-1.1.0.Final.jar:1.1.0.Final]
        at io.undertow.servlet.handlers.security.SSLInformationAssociationHandler.handleRequest(SSLInformationAssociationHandler.java:131) [undertow-servlet-1.1.0.Final.jar:1.1.0.Final]
        at io.undertow.servlet.handlers.security.ServletAuthenticationCallHandler.handleRequest(ServletAuthenticationCallHandler.java:56) [undertow-servlet-1.1.0.Final.jar:1.1.0.Final]
        at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43) [undertow-core-1.1.0.Final.jar:1.1.0.Final]
        at io.undertow.security.handlers.AbstractConfidentialityHandler.handleRequest(AbstractConfidentialityHandler.java:45) [undertow-core-1.1.0.Final.jar:1.1.0.Final]
        at io.undertow.servlet.handlers.security.ServletConfidentialityConstraintHandler.handleRequest(ServletConfidentialityConstraintHandler.java:63) [undertow-servlet-1.1.0.Final.jar:1.1.0.Final]
        at io.undertow.security.handlers.AuthenticationMechanismsHandler.handleRequest(AuthenticationMechanismsHandler.java:58) [undertow-core-1.1.0.Final.jar:1.1.0.Final]
        at io.undertow.servlet.handlers.security.CachedAuthenticatedSessionHandler.handleRequest(CachedAuthenticatedSessionHandler.java:70) [undertow-servlet-1.1.0.Final.jar:1.1.0.Final]
        at io.undertow.security.handlers.SecurityInitialHandler.handleRequest(SecurityInitialHandler.java:76) [undertow-core-1.1.0.Final.jar:1.1.0.Final]
        at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43) [undertow-core-1.1.0.Final.jar:1.1.0.Final]
        at org.wildfly.extension.undertow.security.jacc.JACCContextIdHandler.handleRequest(JACCContextIdHandler.java:61)
        at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43) [undertow-core-1.1.0.Final.jar:1.1.0.Final]
        at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43) [undertow-core-1.1.0.Final.jar:1.1.0.Final]
        at io.undertow.servlet.handlers.ServletInitialHandler.handleFirstRequest(ServletInitialHandler.java:261) [undertow-servlet-1.1.0.Final.jar:1.1.0.Final]
        at io.undertow.servlet.handlers.ServletInitialHandler.dispatchRequest(ServletInitialHandler.java:247) [undertow-servlet-1.1.0.Final.jar:1.1.0.Final]
        at io.undertow.servlet.handlers.ServletInitialHandler.access$000(ServletInitialHandler.java:76) [undertow-servlet-1.1.0.Final.jar:1.1.0.Final]
        at io.undertow.servlet.handlers.ServletInitialHandler$1.handleRequest(ServletInitialHandler.java:166) [undertow-servlet-1.1.0.Final.jar:1.1.0.Final]
        at io.undertow.server.Connectors.executeRootHandler(Connectors.java:197) [undertow-core-1.1.0.Final.jar:1.1.0.Final]
        at io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:759) [undertow-core-1.1.0.Final.jar:1.1.0.Final]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [rt.jar:1.8.0_45]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [rt.jar:1.8.0_45]
        at java.lang.Thread.run(Thread.java:745) [rt.jar:1.8.0_45]
Caused by: com.orientechnologies.orient.core.exception.OPaginatedClusterException: Error during record deletion
        DB name="cm_data"
        Component Name="mev_3"
        DB name="cm_data"
        Component Name="mev_3"
        at sun.reflect.GeneratedConstructorAccessor112.newInstance(Unknown Source) [:1.8.0_45]
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) [rt.jar:1.8.0_45]
        at java.lang.reflect.Constructor.newInstance(Constructor.java:422) [rt.jar:1.8.0_45]
        at com.orientechnologies.orient.client.binary.OChannelBinaryAsynchClient.throwSerializedException(OChannelBinaryAsynchClient.java:442) [orientdb-client-2.2.18.jar:2.2.18]
        at com.orientechnologies.orient.client.binary.OChannelBinaryAsynchClient.handleStatus(OChannelBinaryAsynchClient.java:393) [orientdb-client-2.2.18.jar:2.2.18]
        at com.orientechnologies.orient.client.binary.OChannelBinaryAsynchClient.beginResponse(OChannelBinaryAsynchClient.java:275) [orientdb-client-2.2.18.jar:2.2.18]
        at com.orientechnologies.orient.client.binary.OChannelBinaryAsynchClient.beginResponse(OChannelBinaryAsynchClient.java:167) [orientdb-client-2.2.18.jar:2.2.18]
        at com.orientechnologies.orient.client.remote.OStorageRemote.beginResponse(OStorageRemote.java:2225) [orientdb-client-2.2.18.jar:2.2.18]
        at com.orientechnologies.orient.client.remote.OStorageRemote$28.execute(OStorageRemote.java:1396) [orientdb-client-2.2.18.jar:2.2.18]
        at com.orientechnologies.orient.client.remote.OStorageRemote$28.execute(OStorageRemote.java:1368) [orientdb-client-2.2.18.jar:2.2.18]
        at com.orientechnologies.orient.client.remote.OStorageRemote$2.execute(OStorageRemote.java:198) [orientdb-client-2.2.18.jar:2.2.18]
        at com.orientechnologies.orient.client.remote.OStorageRemote.baseNetworkOperation(OStorageRemote.java:243) [orientdb-client-2.2.18.jar:2.2.18]
        at com.orientechnologies.orient.client.remote.OStorageRemote.networkOperationRetry(OStorageRemote.java:195) [orientdb-client-2.2.18.jar:2.2.18]
        at com.orientechnologies.orient.client.remote.OStorageRemote.networkOperation(OStorageRemote.java:206) [orientdb-client-2.2.18.jar:2.2.18]
        at com.orientechnologies.orient.client.remote.OStorageRemote.commit(OStorageRemote.java:1368) [orientdb-client-2.2.18.jar:2.2.18]
        at com.orientechnologies.orient.core.tx.OTransactionOptimistic.doCommit(OTransactionOptimistic.java:533) [orientdb-core-2.2.18.jar:2.2.18]
        at com.orientechnologies.orient.core.tx.OTransactionOptimistic.commit(OTransactionOptimistic.java:104) [orientdb-core-2.2.18.jar:2.2.18]
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.commit(ODatabaseDocumentTx.java:2840) [orientdb-core-2.2.18.jar:2.2.18]
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.commit(ODatabaseDocumentTx.java:2809) [orientdb-core-2.2.18.jar:2.2.18]
        at com.tinkerpop.blueprints.impls.orient.OrientTransactionalGraph.commit(OrientTransactionalGraph.java:182) [orientdb-graphdb-2.2.18.jar:]
        at com.amadeus.crl.api.orientdb.NodeLoader.updateList(NodeLoader.java:61) [classes:]
        at com.amadeus.crl.api.orientdb.NodeLoader.load(NodeLoader.java:46) [classes:]
        at com.amadeus.crl.api.rest.RestMEV.postMEV(RestMEV.java:34) [classes:]
        at com.amadeus.crl.api.rest.RestMEV$Proxy$_$$_WeldClientProxy.postMEV(Unknown Source) [classes:]
        at sun.reflect.GeneratedMethodAccessor168.invoke(Unknown Source) [:1.8.0_45]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) [rt.jar:1.8.0_45]
        at java.lang.reflect.Method.invoke(Method.java:497) [rt.jar:1.8.0_45]
        at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:137) [resteasy-jaxrs-3.0.10.Final.jar:]
        at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:296) [resteasy-jaxrs-3.0.10.Final.jar:]
        at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:250) [resteasy-jaxrs-3.0.10.Final.jar:]
        at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:237) [resteasy-jaxrs-3.0.10.Final.jar:]
        at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:356) [resteasy-jaxrs-3.0.10.Final.jar:]
        ... 31 more
Caused by: com.orientechnologies.orient.core.storage.impl.local.paginated.atomicoperations.ONestedRollbackException: Atomic operation was rolled back by internal component, exception which caused this rollback is :
com.orientechnologies.orient.core.exception.OPaginatedClusterException: Error during record creation
        DB name="cm_data"
        Component Name="mev_3"
        at com.orientechnologies.orient.core.storage.impl.local.paginated.OPaginatedCluster.createSinglePageRecord(OPaginatedCluster.java:609)
        at com.orientechnologies.orient.core.storage.impl.local.paginated.OPaginatedCluster.createDataRecord(OPaginatedCluster.java:486)
        at com.orientechnologies.orient.core.storage.impl.local.paginated.OPaginatedCluster.createRecord(OPaginatedCluster.java:451)
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.doCreateRecord(OAbstractPaginatedStorage.java:3032)
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.commitEntry(OAbstractPaginatedStorage.java:3652)
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.commit(OAbstractPaginatedStorage.java:1439)
        at com.orientechnologies.orient.core.tx.OTransactionOptimistic.doCommit(OTransactionOptimistic.java:539)
        at com.orientechnologies.orient.core.tx.OTransactionOptimistic.commit(OTransactionOptimistic.java:104)
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.commit(ODatabaseDocumentTx.java:2840)
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.commit(ODatabaseDocumentTx.java:2809)
        at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.commit(ONetworkProtocolBinary.java:1343)
        at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.executeRequest(ONetworkProtocolBinary.java:601)
        at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.sessionRequest(ONetworkProtocolBinary.java:336)
        at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.execute(ONetworkProtocolBinary.java:200)
        at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:77)
Caused by: java.lang.IllegalArgumentException
        at java.nio.Buffer.position(Buffer.java:244)
        at com.orientechnologies.orient.core.storage.impl.local.paginated.wal.OWALPageChangesPortion.readData(OWALPageChangesPortion.java:226)
        at com.orientechnologies.orient.core.storage.impl.local.paginated.wal.OWALPageChangesPortion.getIntValue(OWALPageChangesPortion.java:85)
        at com.orientechnologies.orient.core.storage.impl.local.paginated.base.ODurablePage.getIntValue(ODurablePage.java:116)
        at com.orientechnologies.orient.core.storage.impl.local.paginated.OClusterPage.appendRecord(OClusterPage.java:102)
        at com.orientechnologies.orient.core.storage.impl.local.paginated.OPaginatedCluster.addEntry(OPaginatedCluster.java:2005)
        at com.orientechnologies.orient.core.storage.impl.local.paginated.OPaginatedCluster.createSinglePageRecord(OPaginatedCluster.java:600)
        ... 14 more

        DB name="cm_data"
        at com.orientechnologies.orient.core.storage.impl.local.paginated.atomicoperations.OAtomicOperationsManager.endAtomicOperation(OAtomicOperationsManager.java:457) [orientdb-core-2.2.18.jar:2.2.18]
        at com.orientechnologies.orient.core.storage.impl.local.paginated.atomicoperations.OAtomicOperationsManager.endAtomicOperation(OAtomicOperationsManager.java:412) [orientdb-core-2.2.18.jar:2.2.18]
        at com.orientechnologies.orient.core.storage.impl.local.paginated.base.ODurableComponent.endAtomicOperation(ODurableComponent.java:116) [orientdb-core-2.2.18.jar:2.2.18]
        at com.orientechnologies.orient.core.storage.impl.local.paginated.OPaginatedCluster.deleteRecord(OPaginatedCluster.java:781) [orientdb-core-2.2.18.jar:2.2.18]
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.doCreateRecord(OAbstractPaginatedStorage.java:3049) [orientdb-core-2.2.18.jar:2.2.18]
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.commitEntry(OAbstractPaginatedStorage.java:3652) [orientdb-core-2.2.18.jar:2.2.18]
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.commit(OAbstractPaginatedStorage.java:1439) [orientdb-core-2.2.18.jar:2.2.18]
        at com.orientechnologies.orient.core.tx.OTransactionOptimistic.doCommit(OTransactionOptimistic.java:539) [orientdb-core-2.2.18.jar:2.2.18]
        at com.orientechnologies.orient.core.tx.OTransactionOptimistic.commit(OTransactionOptimistic.java:104) [orientdb-core-2.2.18.jar:2.2.18]
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.commit(ODatabaseDocumentTx.java:2840) [orientdb-core-2.2.18.jar:2.2.18]
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.commit(ODatabaseDocumentTx.java:2809) [orientdb-core-2.2.18.jar:2.2.18]
        at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.commit(ONetworkProtocolBinary.java:1343) [orientdb-server-2.2.18.jar:2.2.18]
        at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.executeRequest(ONetworkProtocolBinary.java:601) [orientdb-server-2.2.18.jar:2.2.18]
        at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.sessionRequest(ONetworkProtocolBinary.java:336) [orientdb-server-2.2.18.jar:2.2.18]
        at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.execute(ONetworkProtocolBinary.java:200) [orientdb-server-2.2.18.jar:2.2.18]
        at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:77) [orientdb-core-2.2.18.jar:2.2.18]

**Comment by laa** [comment]
Hi @Archana3007 you use very old version. Several critical fixes were provided after that. Could you make export to json, update version to latest one which is 2.2.30 and than import database. If issue will not gone, please send us update we will look into that.

**Comment by Archana3007** [comment]
I am trying to run the orientdb-community-importers-2.2.30 ,but I am getting below error:-

2017-11-28 10:10:00:781 INFO  Loading configuration from: /home/glassfish/orientdb-community-importers-2.2.30/config/orientdb-server-config.xml... [OServerConfigurationLoaderXml]
2017-11-28 10:10:01:215 INFO  OrientDB Server v2.2.30 (build 43d850df23c0fd1edca7279761c2238fdc6cc576, branch 2.2.x) is starting up... [OServer]
2017-11-28 10:10:01:220 INFO  Databases directory: /home/glassfish/orientdb-community-importers-2.2.30/databases [OServer]
2017-11-28 10:10:01:261 INFO  Auto configuration of disk cache size. [OMemoryAndLocalPaginatedEnginesInitializer]Exception in thread "Thread-0" java.lang.UnsatisfiedLinkError: /tmp/jna-1350950868/jna5910576871112492572.tmp: /tmp/jna-1350950868/jna5910576871112492572.tmp: failed to map segment from shared object: Operation not permitted
        at java.lang.ClassLoader$NativeLibrary.load(Native Method)
        at java.lang.ClassLoader.loadLibrary1(ClassLoader.java:1939)
        at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1864)
        at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1825)
        at java.lang.Runtime.load0(Runtime.java:792)
        at java.lang.System.load(System.java:1059)
        at com.sun.jna.Native.loadNativeDispatchLibraryFromClasspath(Native.java:947)
        at com.sun.jna.Native.loadNativeDispatchLibrary(Native.java:922)
        at com.sun.jna.Native.<clinit>(Native.java:190)
        at com.orientechnologies.common.jna.ONative.instance(ONative.java:31)
        at com.orientechnologies.orient.core.engine.OMemoryAndLocalPaginatedEnginesInitializer.configureDefaultDiskCacheSize(OMemoryAndLocalPaginatedEnginesInitializer.java:87)
        at com.orientechnologies.orient.core.engine.OMemoryAndLocalPaginatedEnginesInitializer.configureDefaults(OMemoryAndLocalPaginatedEnginesInitializer.java:66)
        at com.orientechnologies.orient.core.engine.OMemoryAndLocalPaginatedEnginesInitializer.initialize(OMemoryAndLocalPaginatedEnginesInitializer.java:53)
        at com.orientechnologies.orient.core.engine.local.OEngineLocalPaginated.startup(OEngineLocalPaginated.java:56)
        at com.orientechnologies.orient.core.Orient.startEngine(Orient.java:925)
        at com.orientechnologies.orient.core.Orient.loadStorage(Orient.java:518)
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.<init>(ODatabaseDocumentTx.java:173)
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.<init>(ODatabaseDocumentTx.java:154)
        at com.orientechnologies.orient.server.OSystemDatabase.init(OSystemDatabase.java:151)
        at com.orientechnologies.orient.server.OSystemDatabase.<init>(OSystemDatabase.java:44)
        at com.orientechnologies.orient.server.OServer.initSystemDatabase(OServer.java:1298)
        at com.orientechnologies.orient.server.OServer.activate(OServer.java:358)
        at com.orientechnologies.orient.server.OServerMain$1.run(OServerMain.java:48)

**Comment by laa** [comment]
you have access issues with  `/tmp` folder

**Comment by laa** [comment]
As root, edit` /etc/fstab` configuration file and remove `noexec` from the mount option of `/tmp` directory. Then run `mount -o remount /tmp`

**Comment by laa** [comment]
or you can change temporary directory using setting `-Djava.io.tmpdir=<tmp dir>`

**Comment by Archana3007** [comment]
Hello @laa yes I am able to update to the newer version I need to import the data and test my application once.

**Comment by Archana3007** [comment]
I am trying to import data but I am getting the same cluster error.

2017-12-08 07:18:59:772 SEVER Internal server error:
java.lang.IllegalStateException: Index dictionary can not be loaded [ONetworkProtocolHttpDb]$ANSI{green {db=cm_data}} Error on creating record in cluster: plocal cluster: mev

**Comment by laa** [comment]
@Archana3007 could you give me your JSON file so I will repeat your problem.

**Comment by laa** [comment]
@Archana3007 could you also send me an error which you see during data import?

**Comment by Archana3007** [comment]
Sorry For typo I am getting error while exporting data . beside error it is creating the zip file .The zip file too  huge to share.

Below is the error:-
**Error on execution of command: sql.select from index:dictionary
java.lang.IllegalStateException :Index dictionary cannot be loaded**

**Comment by laa** [comment]
@Archana3007 you will have the error during export because data are broken on disk. You should use olde version to export data and new version to import them. That would be ides. Once you will reimport them,  they will be obviously fixed.

**Comment by laa** [comment]
Hi @Archana3007 did you export/import your data? Any errors so far?

**Comment by Archana3007** [comment]
Hello @laa ,

The import worked fine.There is no exception so far.
Thank you for help :-).

Regards,
Archana
