### ISSUE TITLE
NullPointerException!mybatis to do crud

### ISSUE THREAD

**Issue by Godbother** [orientechnologies/orientdb#7910]
## Expected behavior  
4 vertex

## Actual behavior  
Exception in thread "main" org.apache.ibatis.exceptions.PersistenceException: 
### Cause: java.lang.NullPointerException
	at org.apache.ibatis.exceptions.ExceptionFactory.wrapException(ExceptionFactory.java:30)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:150)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:141)
	at org.apache.ibatis.binding.MapperMethod.executeForMany(MapperMethod.java:137)
	at org.apache.ibatis.binding.MapperMethod.execute(MapperMethod.java:75)
	at org.apache.ibatis.binding.MapperProxy.invoke(MapperProxy.java:59)
	at com.sun.proxy.$Proxy0.test1(Unknown Source)
	at dao.OrientDaoUsed.dotest(OrientDaoUsed.java:13)
	at dao.OrientDaoUsed.main(OrientDaoUsed.java:21)
Caused by: java.lang.NullPointerException
	at com.orientechnologies.orient.jdbc.OrientJdbcResultSetMetaData.getColumnType(OrientJdbcResultSetMetaData.java:194)
	at org.apache.ibatis.executor.resultset.ResultSetWrapper.<init>(ResultSetWrapper.java:60)
	at org.apache.ibatis.executor.resultset.DefaultResultSetHandler.getFirstResultSet(DefaultResultSetHandler.java:248)
	at org.apache.ibatis.executor.resultset.DefaultResultSetHandler.handleResultSets(DefaultResultSetHandler.java:185)
	at org.apache.ibatis.executor.statement.PreparedStatementHandler.query(PreparedStatementHandler.java:64)
	at org.apache.ibatis.executor.statement.RoutingStatementHandler.query(RoutingStatementHandler.java:79)
	at org.apache.ibatis.executor.SimpleExecutor.doQuery(SimpleExecutor.java:63)
	at org.apache.ibatis.executor.BaseExecutor.queryFromDatabase(BaseExecutor.java:324)
	at org.apache.ibatis.executor.BaseExecutor.query(BaseExecutor.java:156)
	at org.apache.ibatis.executor.CachingExecutor.query(CachingExecutor.java:109)
	at org.apache.ibatis.executor.CachingExecutor.query(CachingExecutor.java:83)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:148)
	... 7 more

## Steps to reproduce  
mybatis-mapper:
<!DOCTYPE mapper
        PUBLIC "-//mybatis.org//DTD Mapper 3.0//EN"
        "http://mybatis.org/dtd/mybatis-3-mapper.dtd">
<mapper namespace="dao.OrientdbDao">
    <select id="test1" resultType="java.lang.Object">
        SELECT * FROM V
    </select>
</mapper>

is it wrong sql?or it cannot be used in mybatis?

**Comment by luigidellaquila** [comment]
Hi @Godbother 

The SQL is correct, if you could share a simple test case to reproduce the problem (I have no direct experience with Mybatis) it will help a lot to reproduce and fix

Thanks

Luigi

**Comment by Godbother** [comment]
I'm sorry to reply to you so late.
**# testclass:**
public class OrientDaoUsed {
    private static void dotest() {
        SqlSession session = OrientdbService.newSqlSession();
        try {
            OrientdbDao orientdbDao = session.getMapper(OrientdbDao.class);
            List<Object> ret = orientdbDao.test1();
            System.out.println(ret.toString());
        } finally {
            session.close();
        }
    }

    public static void main(String[] args) {
        dotest();
    }
}
# **service**
public class OrientdbService {
    private static String mybatisResource = "mybatis-config.xml";

    private static SqlSessionFactory sqlSessionFactory;
    public static SqlSessionFactory getSqlSessionFactory() {
        try {
            if (sqlSessionFactory == null) {
                BufferedInputStream inputStream = (BufferedInputStream) Resources.getResourceAsStream(mybatisResource);
                sqlSessionFactory = new SqlSessionFactoryBuilder().build(inputStream);
            }

            return sqlSessionFactory;
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }

    public static SqlSession newSqlSession() {
        SqlSession session = getSqlSessionFactory().openSession();
        return session;
    }
}
# **Dao&DaoXml**
public interface OrientdbDao {
    public List<Object> test1();
}
<mapper namespace="dao.OrientdbDao">
    <select id="test1" resultType="java.lang.Object">
        SELECT * FROM V
    </select>
</mapper>

I got the connection to my ordb,but throw a Exception
