### ISSUE TITLE
Error: Error on committing distributed transaction

### ISSUE THREAD

**Issue by cuvelierm** [orientechnologies/orientdb#7914]
### OS: Ubuntu 16.04.3 LTS<os here>  
Docker version 17.09.0-ce, build afdb6d4

## Expected behavior  
Execute the batch I am running correctly.
This works fine on a single server, yet throws errors on a distributed setup of 3 servers.

## Actual behavior  
After the error is thrown, the isnerted item is being deleted automatically.
Throwing an error 
`2017-12-04 10:51:20:010 INFO  [orient1] Reassignment of clusters for database 'xxx' completed (classes=174) [OHazelcastPlugin]Error on transaction commit `17AD4095`
com.orientechnologies.orient.core.exception.OTransactionException: Error on committing distributed transaction
        DB name="xxx"
        at com.orientechnologies.orient.server.distributed.impl.ODistributedTransactionManager.processCommitResult(ODistributedTransactionManager.java:774)
        at com.orientechnologies.orient.server.distributed.impl.ODistributedTransactionManager.commit(ODistributedTransactionManager.java:186)
        at com.orientechnologies.orient.server.distributed.impl.ODistributedStorage.commit(ODistributedStorage.java:1420)
        at com.orientechnologies.orient.core.tx.OTransactionOptimistic.doCommit(OTransactionOptimistic.java:541)
        at com.orientechnologies.orient.core.tx.OTransactionOptimistic.commit(OTransactionOptimistic.java:99)
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.commit(ODatabaseDocumentTx.java:2922)
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.commit(ODatabaseDocumentTx.java:2884)
        at com.orientechnologies.orient.core.command.script.OCommandExecutorScript.executeSQLScript(OCommandExecutorScript.java:357)
        at com.orientechnologies.orient.core.command.script.OCommandExecutorScript.executeSQL(OCommandExecutorScript.java:229)
        at com.orientechnologies.orient.core.command.script.OCommandExecutorScript.executeInContext(OCommandExecutorScript.java:105)
        at com.orientechnologies.orient.core.command.script.OCommandExecutorScript.execute(OCommandExecutorScript.java:89)
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.executeCommand(OAbstractPaginatedStorage.java:3421)
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.command(OAbstractPaginatedStorage.java:3339)
        at com.orientechnologies.orient.server.distributed.impl.ODistributedStorage.command(ODistributedStorage.java:259)
        at com.orientechnologies.orient.core.command.OCommandRequestTextAbstract.execute(OCommandRequestTextAbstract.java:69)
        at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.command(ONetworkProtocolBinary.java:1564)
        at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.executeRequest(ONetworkProtocolBinary.java:664)
        at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.sessionRequest(ONetworkProtocolBinary.java:398)
        at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.execute(ONetworkProtocolBinary.java:217)
        at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:82)
Caused by: com.orientechnologies.orient.server.distributed.ODistributedException: Skipped request id=0.18 task=tx[5]{record_create(#226:0 v.0),record_create(#1122:0 v.0),record_update(#305:3359 v.1363),record_create(#939:0 v.0),record_update(#283:26 v.20)} user=#5:3 on database 'xxx' because LSN{segment=0, position=257843} < current LSN{segment=0, position=13839342}
        at com.orientechnologies.orient.server.distributed.impl.ODistributedDatabaseImpl.processRequest(ODistributedDatabaseImpl.java:216)
        at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.executeDistributedRequest(ONetworkProtocolBinary.java:1062)
        at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.distributedRequest(ONetworkProtocolBinary.java:334)
        at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.execute(ONetworkProtocolBinary.java:215)
        ... 1 more
Exception `17AD4095` in storage `plocal:/orientdb/databases/xxx`: 2.2.30 (build 43d850df23c0fd1edca7279761c2238fdc6cc576, branch 2.2.x)
com.orientechnologies.orient.core.exception.OTransactionException: Error on committing distributed transaction
        DB name="xxx"
        at com.orientechnologies.orient.server.distributed.impl.ODistributedTransactionManager.processCommitResult(ODistributedTransactionManager.java:774)
        at com.orientechnologies.orient.server.distributed.impl.ODistributedTransactionManager.commit(ODistributedTransactionManager.java:186)
        at com.orientechnologies.orient.server.distributed.impl.ODistributedStorage.commit(ODistributedStorage.java:1420)
        at com.orientechnologies.orient.core.tx.OTransactionOptimistic.doCommit(OTransactionOptimistic.java:541)
        at com.orientechnologies.orient.core.tx.OTransactionOptimistic.commit(OTransactionOptimistic.java:99)
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.commit(ODatabaseDocumentTx.java:2922)
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.commit(ODatabaseDocumentTx.java:2884)
        at com.orientechnologies.orient.core.command.script.OCommandExecutorScript.executeSQLScript(OCommandExecutorScript.java:357)
        at com.orientechnologies.orient.core.command.script.OCommandExecutorScript.executeSQL(OCommandExecutorScript.java:229)
        at com.orientechnologies.orient.core.command.script.OCommandExecutorScript.executeInContext(OCommandExecutorScript.java:105)
        at com.orientechnologies.orient.core.command.script.OCommandExecutorScript.execute(OCommandExecutorScript.java:89)
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.executeCommand(OAbstractPaginatedStorage.java:3421)
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.command(OAbstractPaginatedStorage.java:3339)
        at com.orientechnologies.orient.server.distributed.impl.ODistributedStorage.command(ODistributedStorage.java:259)
        at com.orientechnologies.orient.core.command.OCommandRequestTextAbstract.execute(OCommandRequestTextAbstract.java:69)
        at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.command(ONetworkProtocolBinary.java:1564)
        at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.executeRequest(ONetworkProtocolBinary.java:664)
        at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.sessionRequest(ONetworkProtocolBinary.java:398)
        at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.execute(ONetworkProtocolBinary.java:217)
        at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:82)
Caused by: com.orientechnologies.orient.server.distributed.ODistributedException: Skipped request id=0.18 task=tx[5]{record_create(#226:0 v.0),record_create(#1122:0 v.0),record_update(#305:3359 v.1363),record_create(#939:0 v.0),record_update(#283:26 v.20)} user=#5:3 on database 'xxx' because LSN{segment=0, position=257843} < current LSN{segment=0, position=13839342}
        at com.orientechnologies.orient.server.distributed.impl.ODistributedDatabaseImpl.processRequest(ODistributedDatabaseImpl.java:216)
        at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.executeDistributedRequest(ONetworkProtocolBinary.java:1062)
        at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.distributedRequest(ONetworkProtocolBinary.java:334)
        at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.execute(ONetworkProtocolBinary.java:215)
        ... 1 more
Exception `17AD4095` in storage `plocal:/orientdb/databases/xxx`: 2.2.30 (build 43d850df23c0fd1edca7279761c2238fdc6cc576, branch 2.2.x)
com.orientechnologies.orient.core.exception.OTransactionException: Error on committing distributed transaction
        DB name="xxx"
        at com.orientechnologies.orient.server.distributed.impl.ODistributedTransactionManager.processCommitResult(ODistributedTransactionManager.java:774)
        at com.orientechnologies.orient.server.distributed.impl.ODistributedTransactionManager.commit(ODistributedTransactionManager.java:186)
        at com.orientechnologies.orient.server.distributed.impl.ODistributedStorage.commit(ODistributedStorage.java:1420)
        at com.orientechnologies.orient.core.tx.OTransactionOptimistic.doCommit(OTransactionOptimistic.java:541)
        at com.orientechnologies.orient.core.tx.OTransactionOptimistic.commit(OTransactionOptimistic.java:99)
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.commit(ODatabaseDocumentTx.java:2922)
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.commit(ODatabaseDocumentTx.java:2884)
        at com.orientechnologies.orient.core.command.script.OCommandExecutorScript.executeSQLScript(OCommandExecutorScript.java:357)
        at com.orientechnologies.orient.core.command.script.OCommandExecutorScript.executeSQL(OCommandExecutorScript.java:229)
        at com.orientechnologies.orient.core.command.script.OCommandExecutorScript.executeInContext(OCommandExecutorScript.java:105)
        at com.orientechnologies.orient.core.command.script.OCommandExecutorScript.execute(OCommandExecutorScript.java:89)
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.executeCommand(OAbstractPaginatedStorage.java:3421)
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.command(OAbstractPaginatedStorage.java:3339)
        at com.orientechnologies.orient.server.distributed.impl.ODistributedStorage.command(ODistributedStorage.java:259)
        at com.orientechnologies.orient.core.command.OCommandRequestTextAbstract.execute(OCommandRequestTextAbstract.java:69)
        at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.command(ONetworkProtocolBinary.java:1564)
        at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.executeRequest(ONetworkProtocolBinary.java:664)
        at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.sessionRequest(ONetworkProtocolBinary.java:398)
        at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.execute(ONetworkProtocolBinary.java:217)
        at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:82)
Caused by: com.orientechnologies.orient.server.distributed.ODistributedException: Skipped request id=0.18 task=tx[5]{record_create(#226:0 v.0),record_create(#1122:0 v.0),record_update(#305:3359 v.1363),record_create(#939:0 v.0),record_update(#283:26 v.20)} user=#5:3 on database 'xxx' because LSN{segment=0, position=257843} < current LSN{segment=0, position=13839342}
        at com.orientechnologies.orient.server.distributed.impl.ODistributedDatabaseImpl.processRequest(ODistributedDatabaseImpl.java:216)
        at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.executeDistributedRequest(ONetworkProtocolBinary.java:1062)
        at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.distributedRequest(ONetworkProtocolBinary.java:334)
        at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.execute(ONetworkProtocolBinary.java:215)
        ... 1 more
`

## Steps to reproduce  
Execute a batch on a distributed setup(currently this is defined as 3 servers: orient1, orient2, orient3).
`begin
let $vert = CREATE VERTEX `comment` CONTENT {"text":"strgq","dateAdded":"2017-12-04T10:56:30.861Z","_id":"5a2529de2814151668f02118"};
let $0 = CREATE edge user_comment from (select from `user` WHERE  `_id` = 'x5mxEBwhMfiLSQHaK'  ) TO $vert;
let $1 = CREATE edge story_comment from (select from `story` WHERE  `_id` = '5a25100d064c8d43a480ab5e'  ) TO $vert;
commit 
return $vert
`

**Comment by cuvelierm** [comment]
ANy aid would be apreciated, since running a website on a wsingle DB instance is not safe at all.
Having multiple instances up and still being performant would be a good thing.
