### ISSUE TITLE
3.0.0 throw exception when start

### ISSUE THREAD

**Issue by weickdev** [orientechnologies/orientdb#7933]
### OS: CentOS

I pull the last code on develop branch, compile it and get the orientdb-community-3.0.0-SNAPSHOT.zip. When I unzip it and run it, it throws this exception:
```
java.lang.IllegalAccessException: Class java.util.logging.LogManager$1 can not access a member of class com.orientechnologies.common.log.OLogManager with modifiers "protected"
	at sun.reflect.Reflection.ensureMemberAccess(Reflection.java:102)
	at java.lang.Class.newInstance(Class.java:436)
	at java.util.logging.LogManager$1.run(LogManager.java:192)
	at java.util.logging.LogManager$1.run(LogManager.java:181)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.util.logging.LogManager.<clinit>(LogManager.java:181)
	at java.util.logging.Logger.demandLogger(Logger.java:448)
	at java.util.logging.Logger.getLogger(Logger.java:502)
	at jdk.nashorn.internal.runtime.logging.DebugLogger.instantiateLogger(DebugLogger.java:84)
	at jdk.nashorn.internal.runtime.logging.DebugLogger.<init>(DebugLogger.java:77)
	at jdk.nashorn.internal.runtime.logging.DebugLogger.<clinit>(DebugLogger.java:55)
	at jdk.nashorn.internal.lookup.MethodHandleFactory$StandardMethodHandleFunctionality.<init>(MethodHandleFactory.java:325)
	at jdk.nashorn.internal.lookup.MethodHandleFactory.<clinit>(MethodHandleFactory.java:103)
	at jdk.nashorn.internal.runtime.Context.initLoggers(Context.java:1404)
	at jdk.nashorn.internal.runtime.Context.<init>(Context.java:549)
	at jdk.nashorn.internal.runtime.Context.<init>(Context.java:466)
	at jdk.nashorn.api.scripting.NashornScriptEngine$1.run(NashornScriptEngine.java:129)
	at jdk.nashorn.api.scripting.NashornScriptEngine$1.run(NashornScriptEngine.java:125)
	at java.security.AccessController.doPrivileged(Native Method)
	at jdk.nashorn.api.scripting.NashornScriptEngine.<init>(NashornScriptEngine.java:125)
	at jdk.nashorn.api.scripting.NashornScriptEngineFactory.getScriptEngine(NashornScriptEngineFactory.java:148)
	at javax.script.ScriptEngineManager.getEngineByName(ScriptEngineManager.java:238)
	at com.orientechnologies.orient.core.command.script.OScriptManager.<init>(OScriptManager.java:78)
	at com.orientechnologies.orient.core.Orient.<init>(Orient.java:74)
	at com.orientechnologies.orient.core.Orient.startUp(Orient.java:198)
	at com.orientechnologies.orient.core.Orient.instance(Orient.java:184)
	at com.orientechnologies.orient.server.OServer.<init>(OServer.java:107)
	at com.orientechnologies.orient.server.OServerMain.create(OServerMain.java:28)
	at com.orientechnologies.orient.server.OServerMain$1.run(OServerMain.java:47)
```

**Comment by luigidellaquila** [comment]
Hi @weickdev 

I fixed it just a few hours ago, now it shoud be OK

Thanks

Luigi

**Comment by weickdev** [comment]
@luigidellaquila  Thanks, It works well now.
