### ISSUE TITLE
v3.0 compile error

### ISSUE THREAD

**Issue by weickdev** [orientechnologies/orientdb#7934]
### OS: CentOS 

When I run `mvn clean install -DskipTests`, I get below exception. But the compile can run successful.
```
[INFO] --- maven-bundle-plugin:3.0.1:manifest (bundle-manifest) @ orientdb-core ---
[INFO]
[INFO] --- javassist-maven-plugin:1.1.0:javassist (default) @ orientdb-core ---
[ERROR] Class com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage could not not be instrumented due to initialize FAILED.
java.lang.ClassCastException: javassist.bytecode.InterfaceMethodrefInfo cannot be cast to javassist.bytecode.MethodrefInfo
	at javassist.bytecode.ConstPool.getMethodrefType(ConstPool.java:452)
	at javassist.bytecode.stackmap.Tracer.doInvokeMethod(Tracer.java:800)
	at javassist.bytecode.stackmap.Tracer.doOpcode148_201(Tracer.java:597)
	at javassist.bytecode.stackmap.Tracer.doOpcode(Tracer.java:81)
	at javassist.bytecode.stackmap.MapMaker.make(MapMaker.java:187)
	at javassist.bytecode.stackmap.MapMaker.make(MapMaker.java:199)
	at javassist.bytecode.stackmap.MapMaker.make(MapMaker.java:199)
	at javassist.bytecode.stackmap.MapMaker.make(MapMaker.java:164)
	at javassist.bytecode.stackmap.MapMaker.make(MapMaker.java:108)
	at javassist.bytecode.MethodInfo.rebuildStackMap(MethodInfo.java:423)
	at javassist.bytecode.MethodInfo.rebuildStackMapIf6(MethodInfo.java:405)
	at javassist.CtBehavior.addCatch(CtBehavior.java:1096)
	at javassist.CtBehavior.addCatch(CtBehavior.java:1048)
	at com.orientechnologies.common.javassist.OStaticInitializerExceptionLoggerWeaver.applyTransformations(OStaticInitializerExceptionLoggerWeaver.java:32)
	at de.icongmbh.oss.maven.plugin.javassist.ClassTransformer.transform(ClassTransformer.java:171)
	at de.icongmbh.oss.maven.plugin.javassist.ClassTransformer.transform(ClassTransformer.java:131)
	at de.icongmbh.oss.maven.plugin.javassist.JavassistTransformerExecutor.execute(JavassistTransformerExecutor.java:107)
	at de.icongmbh.oss.maven.plugin.javassist.JavassistTransformerExecutor.execute(JavassistTransformerExecutor.java:98)
	at de.icongmbh.oss.maven.plugin.javassist.JavassistMojo.execute(JavassistMojo.java:118)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:154)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:146)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:309)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:194)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:107)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:993)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:345)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:191)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
[INFO] #2216 classes instrumented by com.orientechnologies.common.javassist.OStaticInitializerExceptionLoggerWeaver
```

**Comment by laa** [comment]
Hi @weickdev both of your issues will be fixed today.

**Comment by laa** [comment]
fixed
