### ISSUE TITLE
[SOS]com.orientechnologies.orient.core.db.record.OTrackedMap cannot be cast to com.orientechnologies.orient.core.db.record.OIdentifiable

### ISSUE THREAD

**Issue by lightjiao** [orientechnologies/orientdb#7947]
### Execute sql below
```
SELECT *, bothE('e_object').asSet() AS `relation_list` FROM v_object WHERE 1 = 1 AND `objectId` = 'HOST' FETCHPLAN `*`:1 `relation_list`:1 in_e_instance_*:-2 out_e_instance_*:-2
```
Orientdb throw a exception 
```
$ANSI{green {db=cmdb_org_1080}} Exception `6D100F27` in storage `cmdb_org_1080`
com.orientechnologies.orient.core.exception.OCommandExecutionException: Error on execution of command: sql.SELECT *, bothE('e_object').asSet() AS `relation_list` FROM v_object WHERE 1 = 1 AND `objectId` = 'HOST' FETCHPLAN `*`:1 `relation_list`:1 in_e_instance_*:-2 out_e_instance_*:-2^M
    DB name="cmdb_org_1080"
    at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.executeCommand(OAbstractPaginatedStorage.java:3229)
    at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.command(OAbstractPaginatedStorage.java:3146)
    at com.orientechnologies.orient.core.sql.query.OSQLQuery.run(OSQLQuery.java:78)
    at com.orientechnologies.orient.core.sql.query.OSQLAsynchQuery.run(OSQLAsynchQuery.java:74)
    at com.orientechnologies.orient.core.sql.query.OSQLSynchQuery.run(OSQLSynchQuery.java:85)
    at com.orientechnologies.orient.core.query.OQueryAbstract.execute(OQueryAbstract.java:33)
    at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.query(ODatabaseDocumentTx.java:755)
    at com.orientechnologies.orient.server.network.protocol.http.command.get.OServerCommandGetQuery.execute(OServerCommandGetQuery.java:67)
    at com.orientechnologies.orient.server.network.protocol.http.ONetworkProtocolHttpAbstract.service(ONetworkProtocolHttpAbstract.java:173)
    at com.orientechnologies.orient.server.network.protocol.http.ONetworkProtocolHttpAbstract.execute(ONetworkProtocolHttpAbstract.java:629)
    at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:77)
Caused by: java.lang.ClassCastException: com.orientechnologies.orient.core.db.record.OTrackedMap cannot be cast to com.orientechnologies.orient.core.db.record.OIdentifiable
    at com.orientechnologies.orient.core.iterator.OLazyWrapperIterator.getGraphElementRecord(OLazyWrapperIterator.java:61)
    at com.orientechnologies.orient.core.iterator.OLazyWrapperIterator.hasNext(OLazyWrapperIterator.java:103)
    at com.orientechnologies.common.collection.OMultiCollectionIterator.getNextPartial(OMultiCollectionIterator.java:259)
    at com.orientechnologies.common.collection.OMultiCollectionIterator.hasNextInternal(OMultiCollectionIterator.java:88)
    at com.orientechnologies.common.collection.OMultiCollectionIterator.hasNext(OMultiCollectionIterator.java:78)
    at com.orientechnologies.orient.core.sql.method.misc.OSQLMethodAsSet.execute(OSQLMethodAsSet.java:68)
    at com.orientechnologies.orient.core.sql.method.OSQLMethodRuntime.execute(OSQLMethodRuntime.java:139)
    at com.orientechnologies.orient.core.sql.filter.OSQLFilterItemAbstract.transformValue(OSQLFilterItemAbstract.java:140)
    at com.orientechnologies.orient.core.sql.functions.OSQLFunctionRuntime.execute(OSQLFunctionRuntime.java:134)
    at com.orientechnologies.orient.core.sql.ORuntimeResult.applyRecord(ORuntimeResult.java:141)
    at com.orientechnologies.orient.core.sql.ORuntimeResult.getProjectionResult(ORuntimeResult.java:255)
    at com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.addResult(OCommandExecutorSQLSelect.java:725)
    at com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.handleResult(OCommandExecutorSQLSelect.java:674)
    at com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.executeSearchRecord(OCommandExecutorSQLSelect.java:630)
    at com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.serialIterator(OCommandExecutorSQLSelect.java:1637)
    at com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.fetchFromTarget(OCommandExecutorSQLSelect.java:1584)
    at com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.fetchValuesFromIndexCursor(OCommandExecutorSQLSelect.java:2464)
    at com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.searchForIndexes(OCommandExecutorSQLSelect.java:2278)
    at com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.searchInClasses(OCommandExecutorSQLSelect.java:1019)
    at com.orientechnologies.orient.core.sql.OCommandExecutorSQLResultsetAbstract.assignTarget(OCommandExecutorSQLResultsetAbstract.java:209)
    at com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.assignTarget(OCommandExecutorSQLSelect.java:530)
    at com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.executeSearch(OCommandExecutorSQLSelect.java:512)
    at com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.execute(OCommandExecutorSQLSelect.java:488)
    at com.orientechnologies.orient.core.sql.OCommandExecutorSQLDelegate.execute(OCommandExecutorSQLDelegate.java:74)
    at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.executeCommand(OAbstractPaginatedStorage.java:3208)
    ... 10 more
```

but sql below is ok. 
```
SELECT *  FROM v_object WHERE 1 = 1 AND `objectId` = 'HOST' FETCHPLAN `*`:1 `relation_list`:1 in_e_instance_*:-2 out_e_instance_*:-2
```

this is a very serious problem for me,  the data in orientdb is very important, is there any way to fix this problem?

**Comment by luigidellaquila** [comment]
Hi @lightjiao 

Do you have a dataset where I can reproduce this issue?

Thanks

Luigi

**Comment by lightjiao** [comment]
@luigidellaquila sorry you are waiting.
some of `v_object` data lose it's edge information, I don't know why, I delete the vertex and related edge, solved my problem.

and sorry we cannot offer the database to you.

perhaps, the exception can be more readable.

My English is not very well, thanks reading.

**Comment by luigidellaquila** [comment]
Hi @lightjiao 

Thank you for letting me know, I'll try to see if we can make the exception more explicit

Thanks

Luigi
