### ISSUE TITLE
Import database fail

### ISSUE THREAD

**Issue by bsuieric** [orientechnologies/orientdb#7981]
## Description
I connected to the db1 database directly into the console. I exported the database.
I connected to the db2 database directly into the console. I tried to import the db previously exported.

## Expected behavior 
 
I'm trying to import a database previously exported from the same server

## Stack trace 
Importing records...Error on database import happened just before line 0, column 258978
com.orientechnologies.orient.core.db.tool.ODatabaseImportException: Error on importing record
	at com.orientechnologies.orient.core.db.tool.ODatabaseImport.importRecord(ODatabaseImport.java:1344)
	at com.orientechnologies.orient.core.db.tool.ODatabaseImport.importRecords(ODatabaseImport.java:1274)
	at com.orientechnologies.orient.core.db.tool.ODatabaseImport.importDatabase(ODatabaseImport.java:418)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.importDatabase(ONetworkProtocolBinary.java:2914)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.executeRequest(ONetworkProtocolBinary.java:653)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.sessionRequest(ONetworkProtocolBinary.java:336)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.execute(ONetworkProtocolBinary.java:200)
	at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:77)
Caused by: com.orientechnologies.orient.core.exception.OSerializationException: Error on unmarshalling JSON content for record #15:0
	DB name="ogs_test"
	at com.orientechnologies.orient.core.serialization.serializer.record.string.ORecordSerializerJSON.fromString(ORecordSerializerJSON.java:313)
	at com.orientechnologies.orient.core.serialization.serializer.record.string.ORecordSerializerJSON.fromString(ORecordSerializerJSON.java:171)
	at com.orientechnologies.orient.core.db.tool.ODatabaseImport.importRecord(ODatabaseImport.java:1326)
	... 7 more
Caused by: com.orientechnologies.common.io.OIOException: Bad Base64 input character decimal 46 in array position 2
	at com.orientechnologies.orient.core.serialization.OBase64Utils.decode(OBase64Utils.java:1591)
	at com.orientechnologies.orient.core.serialization.OBase64Utils.decode(OBase64Utils.java:1640)
	at com.orientechnologies.orient.core.serialization.OBase64Utils.decode(OBase64Utils.java:1609)
	at com.orientechnologies.orient.core.serialization.serializer.record.string.ORecordSerializerJSON.getValue(ORecordSerializerJSON.java:545)
	at com.orientechnologies.orient.core.serialization.serializer.record.string.ORecordSerializerJSON.fromString(ORecordSerializerJSON.java:259)
	... 9 more 

## Steps to reproduce  
from console:

  connect remote..../db1 user password
  export database db1.json

  connect remote..../db2 user password
  import database db1.json

**Comment by tglman** [comment]
Hi @bsuieric,

The error seems related to a specific content, can you still reproduce this problem ?

Regards

**Comment by akshay-mahakalkar** [comment]
@laa 
I also have similar issue with few of my databases. I have issue when importing database. There is a record id for which import process fails. This is on 3.0.29 version.
This issue is not with every server I have, few are broken. Can you please suggest something to fix or remove/skip this record when importing?

**Comment by tglman** [comment]
Hi, 

we did a few fixes in recent version like the 3.2.x series for the improve the import, anyway if you still have problem and you can identify a specific set of records that cause the problem, you can try to delete that specific records in the database itself before the export is executed ( by the way do backups all the times before deleting data).

Bye
