### ISSUE TITLE
OCommandExecutionException "Class not found" when trying to GraphTraversal.hasNext

### ISSUE THREAD

**Issue by anthony-o** [orientechnologies/orientdb#7985]
## Expected behavior  
This code to work:
```java
// Using org.apache.tinkerpop:tinkergraph-gremlin:3.3.0 and com.orientechnologies:orientdb-gremlin:3.0.0RC1
// import org.apache.tinkerpop.gremlin.process.traversal.dsl.graph.GraphTraversal;
// graph variable is an instance of org.apache.tinkerpop.gremlin.structure.Graph

GraphTraversal<Vertex, Vertex> rootTraversal = graph.traversal().V().hasLabel("Root");
if (rootTraversal.hasNext()) {
	Object rootVertexId = rootTraversal.next().id();
}
```

## Actual behavior  
Following exception is thrown:
```
com.orientechnologies.orient.core.exception.OCommandExecutionException: Class not found: `Root`
	DB name="mydb"
	DB name="mydb"
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.orientechnologies.orient.client.binary.OChannelBinaryAsynchClient.throwSerializedException(OChannelBinaryAsynchClient.java:318)
	at com.orientechnologies.orient.client.binary.OChannelBinaryAsynchClient.handleStatus(OChannelBinaryAsynchClient.java:275)
	at com.orientechnologies.orient.client.binary.OChannelBinaryAsynchClient.beginResponse(OChannelBinaryAsynchClient.java:191)
	at com.orientechnologies.orient.client.binary.OChannelBinaryAsynchClient.beginResponse(OChannelBinaryAsynchClient.java:153)
	at com.orientechnologies.orient.client.remote.OStorageRemote.beginResponse(OStorageRemote.java:1693)
	at com.orientechnologies.orient.client.remote.OStorageRemote.lambda$networkOperationRetryTimeout$2(OStorageRemote.java:226)
	at com.orientechnologies.orient.client.remote.OStorageRemote.baseNetworkOperation(OStorageRemote.java:279)
	at com.orientechnologies.orient.client.remote.OStorageRemote.networkOperationRetryTimeout(OStorageRemote.java:214)
	at com.orientechnologies.orient.client.remote.OStorageRemote.networkOperationNoRetry(OStorageRemote.java:239)
	at com.orientechnologies.orient.client.remote.OStorageRemote.command(OStorageRemote.java:867)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentRemote.command(ODatabaseDocumentRemote.java:360)
	at org.apache.tinkerpop.gremlin.orientdb.OrientGraph.lambda$executeSql$2(OrientGraph.java:254)
	at org.apache.tinkerpop.gremlin.orientdb.OrientGraph.executeWithConnectionCheck(OrientGraph.java:193)
	at org.apache.tinkerpop.gremlin.orientdb.OrientGraph.executeSql(OrientGraph.java:252)
	at org.apache.tinkerpop.gremlin.orientdb.OrientGraphQuery.execute(OrientGraphQuery.java:30)
	at org.apache.tinkerpop.gremlin.orientdb.traversal.step.sideEffect.OrientGraphStep.lambda$elements$6(OrientGraphStep.java:78)
	at java.util.Optional.map(Optional.java:215)
	at org.apache.tinkerpop.gremlin.orientdb.traversal.step.sideEffect.OrientGraphStep.elements(OrientGraphStep.java:77)
	at org.apache.tinkerpop.gremlin.orientdb.traversal.step.sideEffect.OrientGraphStep.vertices(OrientGraphStep.java:47)
	at org.apache.tinkerpop.gremlin.orientdb.traversal.step.sideEffect.OrientGraphStep.lambda$new$0(OrientGraphStep.java:39)
	at org.apache.tinkerpop.gremlin.process.traversal.step.map.GraphStep.processNextStart(GraphStep.java:139)
	at org.apache.tinkerpop.gremlin.process.traversal.step.util.AbstractStep.hasNext(AbstractStep.java:143)
	at org.apache.tinkerpop.gremlin.process.traversal.util.DefaultTraversal.hasNext(DefaultTraversal.java:192)

```

**Comment by maggiolo00** [comment]
Hi @anthony-o 

i've just pushed a fix. It will be available in the next release

Thanks
