### ISSUE TITLE
write data to orientdb on spark throws com.esotericsoftware.kryo.KryoException: java.lang.UnsupportedOperationException

### ISSUE THREAD

**Issue by moxiaofan9** [orientechnologies/orientdb#7986]
## Expected behavior  
<add here>  

## Steps to reproduce  
(1) when i build spark and set .config("spark.serializer", "org.apache.spark.serializer.KryoSerializer") 
it throws exption like this, and when i change to "JavaSerializer" and it works
18/01/06 21:26:18 ERROR TaskResultGetter: Exception while getting task result
com.esotericsoftware.kryo.KryoException: java.lang.UnsupportedOperationException
Serialization trace:
allProperties (com.orientechnologies.orient.core.metadata.schema.OImmutableClass)
classes (com.orientechnologies.orient.core.metadata.schema.OImmutableSchema)
schema (com.orientechnologies.orient.core.metadata.schema.OImmutableClass)
_immutableClazz (com.orientechnologies.orient.core.record.impl.ODocument)
element (com.orientechnologies.orient.core.record.impl.OVertexDelegate)
        at com.esotericsoftware.kryo.serializers.ObjectField.read(ObjectField.java:144)
        at com.esotericsoftware.kryo.serializers.FieldSerializer.read(FieldSerializer.java:551)
        at com.esotericsoftware.kryo.Kryo.readClassAndObject(Kryo.java:790)
        at com.esotericsoftware.kryo.serializers.MapSerializer.read(MapSerializer.java:161)
        at com.esotericsoftware.kryo.serializers.MapSerializer.read(MapSerializer.java:39)
        at com.esotericsoftware.kryo.Kryo.readObject(Kryo.java:708)
        at com.esotericsoftware.kryo.serializers.ObjectField.read(ObjectField.java:125)
        at com.esotericsoftware.kryo.serializers.FieldSerializer.read(FieldSerializer.java:551)
        at com.esotericsoftware.kryo.Kryo.readObject(Kryo.java:708)
        at com.esotericsoftware.kryo.serializers.ObjectField.read(ObjectField.java:125)
        at com.esotericsoftware.kryo.serializers.FieldSerializer.read(FieldSerializer.java:551)
        at com.esotericsoftware.kryo.Kryo.readObject(Kryo.java:708)
        at com.esotericsoftware.kryo.serializers.ObjectField.read(ObjectField.java:125)
        at com.esotericsoftware.kryo.serializers.FieldSerializer.read(FieldSerializer.java:551)
        at com.esotericsoftware.kryo.Kryo.readObject(Kryo.java:708)
        at com.esotericsoftware.kryo.serializers.ObjectField.read(ObjectField.java:125)
        at com.esotericsoftware.kryo.serializers.FieldSerializer.read(FieldSerializer.java:551)

**Comment by tglman** [comment]
hi @SmallWong414,

the ODocument has a custom java serialization implementation (it implements Externalizable) and probably KryoSerializer do not support that, so you should not use that specific serializer with orientdb documents.

Regards

**Comment by SmallWong414** [comment]
@tglman ok,i see,thanks
