### ISSUE TITLE
distributed mode start failed

### ISSUE THREAD

**Issue by weickdev** [orientechnologies/orientdb#7990]
### OS: CentOS  

After I set the config/orientdb-server-config.xml file on node0:
```
<parameter name="enabled" value="true"/>
```
I run bin/dserver.sh, it works well. Then I copy all ODB files to node1 and run bin/dserver.sh
 then I get below error message:
```
2018-01-10 14:29:50:652 WARNI [odb1]->[[odb0]] requesting delta database sync for 'demodb' on local server...Error on checking cluster health
com.orientechnologies.orient.core.exception.ODatabaseException: Cannot open database 'demodb'
	at com.orientechnologies.orient.core.db.OrientDBEmbedded.openNoAuthenticate(OrientDBEmbedded.java:99)
	at com.orientechnologies.orient.core.db.OrientDBEmbedded.openNoAuthenticate(OrientDBEmbedded.java:49)
	at com.orientechnologies.orient.server.OServer.openDatabase(OServer.java:877)
	at com.orientechnologies.orient.server.distributed.impl.ODistributedDatabaseImpl.getDatabaseInstance(ODistributedDatabaseImpl.java:938)
	at com.orientechnologies.orient.server.distributed.impl.ODistributedAbstractPlugin.checkIntegrityOfLastTransactions(ODistributedAbstractPlugin.java:1187)
	at com.orientechnologies.orient.server.distributed.impl.ODistributedAbstractPlugin.requestDatabaseDelta(ODistributedAbstractPlugin.java:1040)
	at com.orientechnologies.orient.server.distributed.impl.ODistributedAbstractPlugin$3.call(ODistributedAbstractPlugin.java:950)
	at com.orientechnologies.orient.server.distributed.impl.ODistributedAbstractPlugin$3.call(ODistributedAbstractPlugin.java:894)
	at com.orientechnologies.orient.server.distributed.impl.ODistributedAbstractPlugin.executeInDistributedDatabaseLock(ODistributedAbstractPlugin.java:1724)
	at com.orientechnologies.orient.server.distributed.impl.ODistributedAbstractPlugin.installDatabase(ODistributedAbstractPlugin.java:893)
	at com.orientechnologies.orient.server.distributed.impl.OClusterHealthChecker.checkServerStatus(OClusterHealthChecker.java:207)
	at com.orientechnologies.orient.server.distributed.impl.OClusterHealthChecker.run(OClusterHealthChecker.java:60)
	at java.util.TimerThread.mainLoop(Timer.java:555)
	at java.util.TimerThread.run(Timer.java:505)
Caused by: com.orientechnologies.orient.core.exception.ODatabaseException: Impossible to open database from version before 2.x use export import instead
	DB name="demodb"
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentEmbedded.init(ODatabaseDocumentEmbedded.java:115)
	at com.orientechnologies.orient.server.distributed.impl.ODatabaseDocumentDistributed.lambda$init$0(ODatabaseDocumentDistributed.java:431)
	at com.orientechnologies.orient.core.db.OScenarioThreadLocal.executeAsDistributed(OScenarioThreadLocal.java:69)
	at com.orientechnologies.orient.server.distributed.impl.ODatabaseDocumentDistributed.init(ODatabaseDocumentDistributed.java:430)
	at com.orientechnologies.orient.core.db.OrientDBEmbedded.openNoAuthenticate(OrientDBEmbedded.java:92)
	... 13 more
```

**Comment by tglman** [comment]
Hi @weickdev,

This is probably due to a not correct install of the database on the specific node, it could happen if the node is shutdown while the sync of a database is running, the solution for that now is remove the database from the database folder, when you start the server again the database will be migrated from the other nodes.

Regards

**Comment by weickdev** [comment]
@tglman If I try this process:
1. start node0, it works well
2. delete databases files of node1, and start node1, node1 works well
3. stop node1 and restart it(without delete any database files), it works well too
4. stop node0 and node1, now no node is running
5. start node0, it works well
6. start node1, it throws error!
7. delete database files of node1 and restart it, it works well

It looks like: if there is at least one node is running, I can stop and restart other nodes well. If all nodes are stopped, then only the first starting node works well. The others must start before delete the database files.

**Comment by tglman** [comment]
hi @weickdev,

I tried to reproduce that today and i don't see the problem, I thing this is a but that I fixed ~20th of Jennuary, can you try again with the last snapshot?

Regards
