### ISSUE TITLE
Getting error com.orientechnologies.orient.core.exception.OStorageException: Cannot open local storage '/../employeeDb' with mode=rw

### ISSUE THREAD

**Issue by ranajit484** [orientechnologies/orientdb#7998]
## Expected behavior  
It should connect to database  

## Actual behavior  

`Exception '38A1B784' in storage 'plocal:/../employeeDb': 2.2.30 (build 43d850df23c0fd1edca7279761c2238fdc6cc576, branch 2.2.x)
com.orientechnologies.orient.core.exception.OStorageException: Cannot open local storage '/../employeeDb' with mode=rw
	DB name="employeeDb"
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.open(OAbstractPaginatedStorage.java:326)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.open(ODatabaseDocumentTx.java:259)
	at com.orientechnologies.orient.server.OServer.openDatabaseBypassingSecurity(OServer.java:995)
	at com.orientechnologies.orient.server.OServer.openDatabase(OServer.java:974)
	at com.orientechnologies.orient.server.OServer.openDatabase(OServer.java:947)
	at com.orientechnologies.orient.server.OServer.openDatabase(OServer.java:938)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.openDatabase(ONetworkProtocolBinary.java:914)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.handshakeRequest(ONetworkProtocolBinary.java:248)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.execute(ONetworkProtocolBinary.java:213)
	at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:82)
Caused by: java.lang.ArrayIndexOutOfBoundsException: 1743
	at com.orientechnologies.orient.core.config.OStorageConfiguration.fromStream(OStorageConfiguration.java:529)
	at com.orientechnologies.orient.core.storage.impl.local.OStorageConfigurationSegment.load(OStorageConfigurationSegment.java:138)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.open(OAbstractPaginatedStorage.java:270)
	... 9 more
`

## Steps to reproduce  
We don't know what happened, all of a sudden its starting to show this error, after stopping and restarting docker container

**Comment by laa** [comment]
@ranajit484 do you work on a distributed server or on single node server?

**Comment by ranajit484** [comment]
@laa It's single node server

**Comment by laa** [comment]
Did you update version recently to a newer one?

**Comment by ranajit484** [comment]
Yeah. from 2.2.29 to 2.2.30 few days back.

**Comment by laa** [comment]
Ok. I will fix change code to avoid that in future. But for now, I suppose we need to fix your problem. Do you have any backups of your database? I need backup after which you did not change database schema or settings, data itself does not matter.

**Comment by ranajit484** [comment]
Unfortunately, we don't have any backup :(

**Comment by laa** [comment]
do you at least remember which schema did you have and which setting did you use?

**Comment by ranajit484** [comment]
Yeah.. schema and settings, we know.

**Comment by laa** [comment]
Ok so please create an empty database with the same settings and the same schema, then please replace file "database.ocf" in your production database and please tell me result does your database work or not )) I will fix your issue next week, so you will not have it anymore.

**Comment by ranajit484** [comment]
Yeah.. I have done the same. It's working for me now. Thanks for the suggestion.
