### ISSUE TITLE
Full Backup error. Wal file not found

### ISSUE THREAD

**Issue by ScoobyMax** [orientechnologies/orientdb#8005]
## Expected behavior  
on version 2.2.21 all backup was good

## Actual behavior  
On version 2.2.31 we catching errors

```
$ANSI{green {db=vis_demo}} Error on backup of database 'plocal:/opt/orientdb-community-2.2.31/databases/vis_demo' to directory: /opt/backup/orient/
java.lang.IllegalArgumentException: Directory /opt/orientdb-community-2.2.31/databases/vis_demo/vis_demo.9.wal not found
        at com.orientechnologies.orient.core.compression.impl.OZIPCompressionUtil.addFolder(OZIPCompressionUtil.java:145)
        at com.orientechnologies.orient.core.compression.impl.OZIPCompressionUtil.addFolder(OZIPCompressionUtil.java:127)
        at com.orientechnologies.orient.core.compression.impl.OZIPCompressionUtil.compressDirectory(OZIPCompressionUtil.java:57)
        at com.orientechnologies.orient.core.storage.impl.local.paginated.OLocalPaginatedStorage.backup(OLocalPaginatedStorage.java:229)
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.backup(ODatabaseDocumentTx.java:3060)
        at com.orientechnologies.orient.server.handler.OAutomaticBackup.fullBackupDatabase(OAutomaticBackup.java:353)
        at com.orientechnologies.orient.server.handler.OAutomaticBackup$1.run(OAutomaticBackup.java:183)
        at java.util.TimerThread.mainLoop(Timer.java:555)
        at java.util.TimerThread.run(Timer.java:505)

```
in results we have
2018-01-16 03:56:51:640 INFO  Automatic Backup finished: 5 ok, 3 errors

## Steps to reproduce  

/opt/orientdb-community-2.2.31/config/automatic-backup.json
```
{
  "enabled": true,
  "mode": "FULL_BACKUP",
  "exportOptions": "",
  "delay": "24h",
  "firstTime": "03:15:00",
  "targetDirectory": "/opt/backup/orient",
  "targetFileName": "${DBNAME}-${DATE:yyyyMMdd}.zip",
  "compressionLevel": 9,
  "bufferSize": 1048576
}

```

[orientdb.zip](https://github.com/orientechnologies/orientdb/files/1633671/orientdb.zip)

**Comment by laa** [comment]
Fixed

**Comment by peterlynch** [comment]
What were the affected versions of this bug?

**Comment by laa** [comment]
I think all versions were affected since the backup creation.

**Comment by laa** [comment]
Sorry, my bad I suppose few versions not more than 2.2.28 are affected. But in the previous version, we calculate LSNs of backups incorrectly, so I suggest to upgrade to latest version anyway.

**Comment by medworker** [comment]
Hello, i had the same issue with version 2.2.31, i upgraded to 2.2.33 this morning, but i got still the exact backup error that the wal file was not found. Should it work in the 2.2.33 version?

**Comment by laa** [comment]
No, it is not released yet.
