### ISSUE TITLE
Error when opening multiple databases using try-with-resource : The database instance is not set in the current thread

### ISSUE THREAD

**Issue by holocentric-bmsnext** [orientechnologies/orientdb#8009]
### Java Version: 1.8 (Spring 1.5.9), using below maven dependency for orientdb
```
	<dependency>
		<groupId>com.orientechnologies</groupId>
		<artifactId>orientdb-core</artifactId>
		<version>3.0.0RC1</version>
	</dependency>
	<dependency>
		<groupId>com.orientechnologies</groupId>
		<artifactId>orientdb-client</artifactId>
		<version>3.0.0RC1</version>
	</dependency>
```
## Expected behavior  
There should not be any exceptions.

## Actual behavior  
An Exception is thrown.
```
2018-01-18 12:05:54.303 ERROR 8716 --- [nio-5012-exec-1] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is com.orientechnologies.orient.core.exception.ODatabaseException: The database instance is not set in the current thread. Be sure to set it with: ODatabaseRecordThreadLocal.instance().set(db);] with root cause

com.orientechnologies.orient.core.exception.ODatabaseException: The database instance is not set in the current thread. Be sure to set it with: ODatabaseRecordThreadLocal.instance().set(db);
	at com.orientechnologies.orient.core.db.ODatabaseRecordThreadLocal.get(ODatabaseRecordThreadLocal.java:63) ~[orientdb-core-3.0.0RC1.jar:3.0.0RC1]
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentAbstract.checkIfActive(ODatabaseDocumentAbstract.java:2796) ~[orientdb-core-3.0.0RC1.jar:3.0.0RC1]
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentAbstract.close(ODatabaseDocumentAbstract.java:799) ~[orientdb-core-3.0.0RC1.jar:3.0.0RC1]
```

## Steps to reproduce  
```
OrientDB orientDb = new OrientDB("remote:localhost", OrientDBConfig.defaultConfig());
try (ODatabaseDocument database = orientDb.open(storeId1, "username", "password");
				ODatabaseDocument database2= orientDb.open(storeId2, "username",
						"password")) {

OResultSet resultSet = database.query("traverse * from v");

			while (resultSet.hasNext()) {
				OResult record = resultSet.next();
				record.getElement().ifPresent(element ->

				{
					String schemaType = element.getSchemaType();
				});

			}

			resultSet.close();
}
```

**Comment by tglman** [comment]
Hi,

As reported in internal tickets, for use multiple database one one thread you should use `activateOnCurrentThread()`
ex:
```

String storeId1 = "test1";
        String storeId2 = "test2";
        OrientDB orientDb = new OrientDB("remote:localhost",
                OrientDBConfig.defaultConfig());

        try {
            ODatabaseDocument database = orientDb
                    .open(storeId1, "root", "root");
            ODatabaseDocument database2 = orientDb.open(storeId2, "root",
                    "root");
            database.activateOnCurrentThread();
            OResultSet resultSet = database.query("traverse * from v");
            while (resultSet.hasNext()) {
                OResult record = resultSet.next();
                record.getElement().ifPresent(element -> {
                    String schemaType = element.getSchemaType().toString();
                });
                System.out.println("record " + record.toString());
            }
            resultSet.close();

            database2.activateOnCurrentThread();
            OResultSet resultSet2 = database2.query("traverse * from v");
            while (resultSet2.hasNext()) {
                OResult record = resultSet2.next();
                record.getElement().ifPresent(element -> {
                    String schemaType = element.getSchemaType().toString();
                });
                System.out.println("record " + record.toString());
            }
            resultSet2.close();
        } catch (Exception e) {
            System.out.println(e);
        }
        orientDb.close();
```

**Comment by tglman** [comment]
Hi,

I tested now, the close require the database on the current thread so there is an issue with autoclose 'try' block, reopening

Regards
