### ISSUE TITLE
Lucene WHERE clause breaks queries with .include(...) in 3.x

### ISSUE THREAD

**Issue by metametametameta** [orientechnologies/orientdb#8023]
## Expected behavior  

.include(...) usage as described at http://orientdb.com/docs/3.0.x/sql/SQL-Methods.html#include doesn't work when Lucene where clause is present. This used to work fine on 2.x

The following two queries work as expected in both 2.x and 3.x

```sql
select expand(out('Folder','File')) 
from C32510 
where [searchOid_] LUCENE "(searchOid_:5d9405de-8184-3322-a19e-33d9cf26a535)"
```

```sql
select expand(out('Folder','File').include('@version', 'searchOid_', 'displayName_'))
from C32510
where @version = 5
```

but the following two throw an Exception in 3.x.

```sql
select expand(out('Folder','File').include('displayName_','searchOid_')) 
from C32510 
where [searchOid_] LUCENE "(searchOid_:5d9405de-8184-3322-a19e-33d9cf26a535)"

select expand(out('Folder','File').include('displayName_','searchOid_')) 
from C32510
where SEARCH_FIELDS(["searchOid_"], "searchOid_:5d9405de-8184-3322-a19e-33d9cf26a535") = true
```

## Actual behavior  

The last two queries above throw something like

```
Suppressed: com.orientechnologies.orient.core.exception.OCommandExecutionException: Invalild value for $current: null
	DB name="testdb"
		at com.orientechnologies.orient.core.sql.parser.OMethodCall.execute(OMethodCall.java:87)
		at com.orientechnologies.orient.core.sql.parser.OMethodCall.execute(OMethodCall.java:66)
		at com.orientechnologies.orient.core.sql.parser.OModifier.execute(OModifier.java:91)
		at com.orientechnologies.orient.core.sql.parser.OBaseExpression.execute(OBaseExpression.java:123)
		at com.orientechnologies.orient.core.sql.parser.OExpression.execute(OExpression.java:107)
		at com.orientechnologies.orient.core.sql.parser.OProjectionItem.execute(OProjectionItem.java:127)
		at com.orientechnologies.orient.core.sql.parser.OProjection.calculateSingle(OProjection.java:114)
		at com.orientechnologies.orient.core.sql.executor.ProjectionCalculationStep.calculateProjections(ProjectionCalculationStep.java:61)
		at com.orientechnologies.orient.core.sql.executor.ProjectionCalculationStep.access$000(ProjectionCalculationStep.java:13)
		at com.orientechnologies.orient.core.sql.executor.ProjectionCalculationStep$1.next(ProjectionCalculationStep.java:38)
		at com.orientechnologies.orient.core.sql.executor.ExpandStep.fetchNext(ExpandStep.java:124)
		at com.orientechnologies.orient.core.sql.executor.ExpandStep.access$000(ExpandStep.java:18)
		at com.orientechnologies.orient.core.sql.executor.ExpandStep$1.hasNext(ExpandStep.java:44)
		at com.orientechnologies.orient.core.sql.executor.OrderByStep.init(OrderByStep.java:99)
		at com.orientechnologies.orient.core.sql.executor.OrderByStep.lambda$syncPull$0(OrderByStep.java:38)
		at java.util.Optional.ifPresent(Optional.java:159)
		at com.orientechnologies.orient.core.sql.executor.OrderByStep.syncPull(OrderByStep.java:38)
		at com.orientechnologies.orient.core.sql.executor.OSelectExecutionPlan.fetchNext(OSelectExecutionPlan.java:35)
		at com.orientechnologies.orient.core.sql.parser.OLocalResultSet.fetchNext(OLocalResultSet.java:27)
		at com.orientechnologies.orient.core.sql.parser.OLocalResultSet.<init>(OLocalResultSet.java:23)
		at com.orientechnologies.orient.core.sql.parser.OSelectStatement.execute(OSelectStatement.java:244)
		at com.orientechnologies.orient.core.sql.parser.OStatement.execute(OStatement.java:59)
		at com.orientechnologies.orient.core.db.document.ODatabaseDocumentEmbedded.query(ODatabaseDocumentEmbedded.java:522)
		at com.orientechnologies.orient.server.OConnectionBinaryExecutor.executeQuery(OConnectionBinaryExecutor.java:1155)
		at com.orientechnologies.orient.client.remote.message.OQueryRequest.execute(OQueryRequest.java:128)
		at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.sessionRequest(ONetworkProtocolBinary.java:276)
		at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.execute(ONetworkProtocolBinary.java:182)
		at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:82)
```

**Comment by metametametameta** [comment]
Here is an example from demodb for easy reproduction

This works

```sql
select expand(in('HasEaten')) from Locations
WHERE SEARCH_FIELDS(["Name"], "+Name:ugo*") = true
```

This also works

```sql
select expand(in('HasEaten').include('Phone')) from Locations
```

But this fails

```sql
select expand(in('HasEaten').include('Phone')) from Locations
WHERE SEARCH_FIELDS(["Name"], "+Name:ugo*") = true
```

`com.orientechnologies.orient.core.exception.OCommandExecutionException: Invalild value for $current: null`
