### ISSUE TITLE
Cannot update a ODocument having dots in property names

### ISSUE THREAD

**Issue by sboucard** [orientechnologies/orientdb#8069]
### OS: Windows 10

I can create a ODocument that contains a property whose name is "a.b.c".
But then I cannot update the document using code like the following:

```
OElement element = session.load(myORID);
element.setProperty("a.b.c", "hello");
```

This throws the following exception:

```
com.orientechnologies.orient.core.exception.ODatabaseException: Error during saving of record with rid #19:2
	DB name="mydb"
	at com.orientechnologies.orient.core.tx.OTransactionNoTx.saveRecord(OTransactionNoTx.java:206)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentAbstract.saveInternal(ODatabaseDocumentAbstract.java:2299)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentAbstract.save(ODatabaseDocumentAbstract.java:2259)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentAbstract.save(ODatabaseDocumentAbstract.java:90)
	at com.orientechnologies.orient.core.record.impl.ODocument.save(ODocument.java:2099)
	at com.orientechnologies.orient.core.record.impl.ODocument.save(ODocument.java:2090)
	at com.orientechnologies.orient.core.record.impl.ODocument.save(ODocument.java:63)
Caused by: com.orientechnologies.orient.enterprise.channel.binary.OResponseProcessingException: Exception during response processing
	at com.orientechnologies.orient.client.binary.OChannelBinaryAsynchClient.throwSerializedException(OChannelBinaryAsynchClient.java:328)
	at com.orientechnologies.orient.client.binary.OChannelBinaryAsynchClient.handleStatus(OChannelBinaryAsynchClient.java:275)
	at com.orientechnologies.orient.client.binary.OChannelBinaryAsynchClient.beginResponse(OChannelBinaryAsynchClient.java:191)
	at com.orientechnologies.orient.client.binary.OChannelBinaryAsynchClient.beginResponse(OChannelBinaryAsynchClient.java:153)
	at com.orientechnologies.orient.client.remote.OStorageRemote.beginResponse(OStorageRemote.java:1693)
	at com.orientechnologies.orient.client.remote.OStorageRemote.lambda$asyncNetworkOperationRetry$1(OStorageRemote.java:176)
	at com.orientechnologies.orient.client.remote.OStorageRemote.baseNetworkOperation(OStorageRemote.java:279)
	at com.orientechnologies.orient.client.remote.OStorageRemote.asyncNetworkOperationRetry(OStorageRemote.java:163)
	at com.orientechnologies.orient.client.remote.OStorageRemote.asyncNetworkOperationNoRetry(OStorageRemote.java:151)
	at com.orientechnologies.orient.client.remote.OStorageRemote.updateRecord(OStorageRemote.java:667)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentAbstract.executeSaveRecord(ODatabaseDocumentAbstract.java:1542)
	at com.orientechnologies.orient.core.tx.OTransactionNoTx.saveRecord(OTransactionNoTx.java:184)
	... 99 more
Caused by: java.lang.IllegalArgumentException: Property 'a.b' is null, is possible to set a value with dotted notation only on not null property
	at com.orientechnologies.orient.core.record.impl.ODocument.field(ODocument.java:1366)
	at com.orientechnologies.orient.core.record.impl.ODocument.field(ODocument.java:1225)
	at com.orientechnologies.orient.core.record.impl.ODocument.mergeMap(ODocument.java:2473)
	at com.orientechnologies.orient.core.record.impl.ODocument.merge(ODocument.java:1540)
	at com.orientechnologies.orient.server.OConnectionBinaryExecutor.executeUpdateRecord(OConnectionBinaryExecutor.java:413)
	at com.orientechnologies.orient.client.remote.message.OUpdateRecordRequest.execute(OUpdateRecordRequest.java:132)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.sessionRequest(ONetworkProtocolBinary.java:276)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.execute(ONetworkProtocolBinary.java:182)
	at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:82)
```

My use case is to store RDF predicates as property names within OrientDB.
This defect is a no-go for choosing OrientDB as my reference graph DB platform, which would be too bad as it provides all necessary features.
I hope you can fix this before final 3.0 is out (or tell me where I made a mistake or what switch I can activate to workaround).

**Comment by luigidellaquila** [comment]
Hi @sboucard 

We are fixing it now, I'll let you know asap

Thanks

Luiig

**Comment by luigidellaquila** [comment]
Hi @sboucard 

I just pushed a fix, the snapshot will be available in a few minutes.
Could you please try it and let me know if it covers your case 100%?

Thanks

Luigi

**Comment by sboucard** [comment]
You rock!

**Comment by sboucard** [comment]
I do confirm the fix on my end.
Many thanks for your reactivity, I really appreciate!
