### ISSUE TITLE
failures with Java-9

### ISSUE THREAD

**Issue by rdelangh** [orientechnologies/orientdb#8081]
## Expected behavior  
Normal start/stop with Java v9

## Actual behavior  
- startup is ok
- console.sh gives errors when disconnecting from dbase:
```
$ /opt/orientdb/orientdb-community-2.2.31-SNAPSHOT/bin/console.sh
OrientDB console v.2.2.31-SNAPSHOT (build 97f1131baee11213c40e5f55b150416d31ff7412, branch branches/2-2-x.15993v/workspace/core) https://www.orientdb.com
Type 'help' to display all the supported commands.
Installing extensions for GREMLIN language v.2.6.0
orientdb> CONNECT remote:localhost/cdrarch admin $ourpwd
Connecting to database [remote:localhost/cdrarch] with user 'admin'...OK
orientdb {db=cdrarch}> quit

WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.orientechnologies.common.directmemory.OByteBufferPool (file:/opt/orientdb/orientdb-community-2.2.31-SNAPSHOT/lib/orientdb-core-2.2.31-SNAPSHOT.jar) to method sun.nio.ch.DirectBuffer.cleaner()
WARNING: Please consider reporting this to the maintainers of com.orientechnologies.common.directmemory.OByteBufferPool
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
$ java -version
openjdk version "9.0.1"
OpenJDK Runtime Environment (build 9.0.1+11)
OpenJDK 64-Bit Server VM (build 9.0.1+11, mixed mode)
```

**Comment by laa** [comment]
@rdelangh that is only warning, it is already fixed in 3.0 but 2.2.x will work as is.

**Comment by rdelangh** [comment]
ok, thanks for this feedback !

**Comment by rdelangh** [comment]
however, anyhow failures while trying to INSERT new records:
```
2018-02-07 16:07:55:724 INFO  OrientDB Server is active v2.2.31-SNAPSHOT (build 97f1131baee11213c40e5f55b150416d31ff7412, branch branches/2-2-x.15993v/workspace/core). [O
Server]
2018-02-07 16:13:46:101 INFO  {db=cdrarch} Storage 'plocal:/opt/orientdb/databases/cdrarch' is opened under OrientDB distribution : 2.2.31-SNAPSHOT (build 97f1131baee1121
3c40e5f55b150416d31ff7412, branch branches/2-2-x.15993v/workspace/core) [OLocalPaginatedStorage]$ANSI{green {db=cdrarch}} error while opening closed index:: idx_cdr_af_20
180204_1
java.io.IOException: Unable to unmap the mapped buffer: MMapIndexInput(path="/opt/orientdb/databases/cdrarch/luceneIndexes/idx_cdr_af_20180204_1/_j9.si")
        at org.apache.lucene.store.MMapDirectory$2.freeBuffer(MMapDirectory.java:329)
        at org.apache.lucene.store.ByteBufferIndexInput.freeBuffer(ByteBufferIndexInput.java:376)
        at org.apache.lucene.store.ByteBufferIndexInput.close(ByteBufferIndexInput.java:355)
        at org.apache.lucene.store.BufferedChecksumIndexInput.close(BufferedChecksumIndexInput.java:60)
        at org.apache.lucene.codecs.lucene50.Lucene50SegmentInfoFormat.read(Lucene50SegmentInfoFormat.java:120)
        at org.apache.lucene.index.SegmentInfos.readCommit(SegmentInfos.java:362)
        at org.apache.lucene.index.IndexWriter.<init>(IndexWriter.java:909)
        at com.orientechnologies.lucene.engine.OLuceneIndexWriterFactory.createIndexWriter(OLuceneIndexWriterFactory.java:22)
        at com.orientechnologies.lucene.engine.OLuceneFullTextIndexEngine.createIndexWriter(OLuceneFullTextIndexEngine.java:81)
        at com.orientechnologies.lucene.engine.OLuceneIndexEngineAbstract.open(OLuceneIndexEngineAbstract.java:281)
        at com.orientechnologies.lucene.engine.OLuceneIndexEngineAbstract.reOpen(OLuceneIndexEngineAbstract.java:262)
        at com.orientechnologies.lucene.engine.OLuceneIndexEngineAbstract.openIfClosed(OLuceneIndexEngineAbstract.java:450)
        at com.orientechnologies.lucene.engine.OLuceneFullTextIndexEngine.put(OLuceneFullTextIndexEngine.java:128)
        at com.orientechnologies.lucene.index.OLuceneIndexNotUnique$2.callEngine(OLuceneIndexNotUnique.java:141)
        at com.orientechnologies.lucene.index.OLuceneIndexNotUnique$2.callEngine(OLuceneIndexNotUnique.java:123)
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.doCallIndexEngine(OAbstractPaginatedStorage.java:2373)
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.callIndexEngine(OAbstractPaginatedStorage.java:2338)
        at com.orientechnologies.lucene.index.OLuceneIndexNotUnique.commitSnapshot(OLuceneIndexNotUnique.java:123)
        at com.orientechnologies.orient.core.index.OIndexAbstract.commit(OIndexAbstract.java:812)
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.commitIndexes(OAbstractPaginatedStorage.java:1910)
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.commit(OAbstractPaginatedStorage.java:1864)
        at com.orientechnologies.orient.core.tx.OTransactionOptimistic.doCommit(OTransactionOptimistic.java:541)
        at com.orientechnologies.orient.core.tx.OTransactionOptimistic.commit(OTransactionOptimistic.java:99)
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.commit(ODatabaseDocumentTx.java:2922)
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.commit(ODatabaseDocumentTx.java:2884)
        at com.orientechnologies.orient.server.network.protocol.http.command.post.OServerCommandPostBatch.execute(OServerCommandPostBatch.java:201)
        at com.orientechnologies.orient.server.network.protocol.http.ONetworkProtocolHttpAbstract.service(ONetworkProtocolHttpAbstract.java:173)
        at com.orientechnologies.orient.server.network.protocol.http.ONetworkProtocolHttpAbstract.execute(ONetworkProtocolHttpAbstract.java:629)
        at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:82)
        Suppressed: java.io.IOException: Unable to unmap the mapped buffer: MMapIndexInput(path="/opt/orientdb/databases/cdrarch/luceneIndexes/idx_cdr_af_20180204_1/segments_163")
                at org.apache.lucene.store.MMapDirectory$2.freeBuffer(MMapDirectory.java:329)
                at org.apache.lucene.store.ByteBufferIndexInput.freeBuffer(ByteBufferIndexInput.java:376)
                at org.apache.lucene.store.ByteBufferIndexInput.close(ByteBufferIndexInput.java:355)
                at org.apache.lucene.store.BufferedChecksumIndexInput.close(BufferedChecksumIndexInput.java:60)
                at org.apache.lucene.index.SegmentInfos.readCommit(SegmentInfos.java:459)
                ... 23 more
        Caused by: java.lang.IllegalAccessException: class org.apache.lucene.store.MMapDirectory$2$1 cannot access class jdk.internal.ref.Cleaner (in module java.base) because module java.base does not export jdk.internal.ref to unnamed module @5aaa4602
                at java.base/jdk.internal.reflect.Reflection.newIllegalAccessException(Reflection.java:361)
                at java.base/java.lang.reflect.AccessibleObject.checkAccess(AccessibleObject.java:589)
                at java.base/java.lang.reflect.Method.invoke(Method.java:556)
                at org.apache.lucene.store.MMapDirectory$2$1.run(MMapDirectory.java:322)
                at org.apache.lucene.store.MMapDirectory$2$1.run(MMapDirectory.java:314)
                at java.base/java.security.AccessController.doPrivileged(Native Method)
                at org.apache.lucene.store.MMapDirectory$2.freeBuffer(MMapDirectory.java:314)
                ... 27 more
Caused by: java.lang.IllegalAccessException: class org.apache.lucene.store.MMapDirectory$2$1 cannot access class jdk.internal.ref.Cleaner (in module java.base) because module java.base does not export jdk.internal.ref to unnamed module @5aaa4602
        at java.base/jdk.internal.reflect.Reflection.newIllegalAccessException(Reflection.java:361)
        at java.base/java.lang.reflect.AccessibleObject.checkAccess(AccessibleObject.java:589)
        at java.base/java.lang.reflect.Method.invoke(Method.java:556)
        at org.apache.lucene.store.MMapDirectory$2$1.run(MMapDirectory.java:322)
        at org.apache.lucene.store.MMapDirectory$2$1.run(MMapDirectory.java:314)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
...
```

**Comment by rdelangh** [comment]
ok, I found a solution:
1) this server got a complete off-line copy of the database from another server; the new server is running Java 9, the old server is running Java 8
2) on the old server, I also got the same failure when trying to insert records;
on the old server, I could run a "rebuild index cdr_af_20180204_1" ;
on the new server, I could NOT run this same index rebuild, with following errors:
```
orientdb {db=cdrarch}> rebuild index idx_cdr_af_20180204_1
Rebuilding index(es)...
Error: com.orientechnologies.orient.core.index.OIndexException: Error on rebuilding the index for clusters: [cl_cdr_af_20180204_p0, cl_cdr_af_20180204_p1, cl_cdr_af_20180204_p4, cl_cdr_af_20180204_p5, cl_cdr_af_20180204_p2, cl_cdr_af_20180204_p3]
        DB name="cdrarch"
        DB name="cdrarch"
Error: org.apache.lucene.store.AlreadyClosedException: this IndexWriter is closed
Error: java.io.IOException: Unable to unmap the mapped buffer: MMapIndexInput(path="/opt/orientdb/databases/cdrarch/luceneIndexes/idx_cdr_af_20180204_1/_0_Lucene50_0.doc")
Error: java.lang.IllegalAccessException: class org.apache.lucene.store.MMapDirectory$2$1 cannot access class jdk.internal.ref.Cleaner (in module java.base) because module java.base does not export jdk.internal.ref to unnamed module @5aaa4602
```
3) so I replaced the Java-9 on the new server by the same Java-8 like on the other servers, and now the index rebuild was succesfull !
4) now the inserts in this database on the new server is working fine as well

-> so definitely issues with Java-9 support that need to be solved
