### ISSUE TITLE
NullPointerException using an non existing index in SQL

### ISSUE THREAD

**Issue by sboucard** [orientechnologies/orientdb#8088]
### OS: Windows 10

Using Studio, got a NullPointerException in my SELECT execution caused by the use of an index that does not exist (a typo in my case).
The original error was obviously on my side, but I guess you would like to provide a better error message in such case.

The SQL looks like this one:
```
SELECT
FROM INDEX:ìndexthatdoesnotexist
```

The stacktrace is the following:
````
java.lang.NullPointerException
	at com.orientechnologies.orient.core.sql.executor.OSelectExecutionPlanner.calculateTargetClusters(OSelectExecutionPlanner.java:343)
	at com.orientechnologies.orient.core.sql.executor.OSelectExecutionPlanner.calculateShardingStrategy(OSelectExecutionPlanner.java:174)
	at com.orientechnologies.orient.core.sql.executor.OSelectExecutionPlanner.createExecutionPlan(OSelectExecutionPlanner.java:64)
	at com.orientechnologies.orient.core.sql.parser.OSelectStatement.createExecutionPlan(OSelectStatement.java:264)
	at com.orientechnologies.orient.core.sql.parser.OSelectStatement.execute(OSelectStatement.java:242)
	at com.orientechnologies.orient.core.sql.parser.OStatement.execute(OStatement.java:59)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentEmbedded.command(ODatabaseDocumentEmbedded.java:545)
	at com.orientechnologies.orient.server.network.protocol.http.command.post.OServerCommandPostCommand.executeStatement(OServerCommandPostCommand.java:174)
	at com.orientechnologies.orient.server.network.protocol.http.command.post.OServerCommandPostCommand.execute(OServerCommandPostCommand.java:84)
	at com.orientechnologies.orient.server.network.protocol.http.command.post.OServerCommandPostCommandGraph.execute(OServerCommandPostCommandGraph.java:36)
	at com.orientechnologies.orient.server.network.protocol.http.ONetworkProtocolHttpAbstract.service(ONetworkProtocolHttpAbstract.java:172)
	at com.orientechnologies.orient.server.network.protocol.http.ONetworkProtocolHttpAbstract.execute(ONetworkProtocolHttpAbstract.java:633)
	at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:82)
````

**Comment by luigidellaquila** [comment]
Hi @sboucard 

I just pushed a fix for this, now the query executor returns a much more meaningful error

Thanks

Luigi
