### ISSUE TITLE
Critical: Embedded LiveQuery causes a stackoverflow.

### ISSUE THREAD

**Issue by ShakAttacked** [orientechnologies/orientdb#8092]
### OS: Centos

Hi,

As of recent update LiveQuery causes a stackoverflow when an action triggers LiveQuery.  I've commented all my code in the implementation of OLiveQueryResultListener and it still crashes.  having

`database.live("select from Person", liveQueryListener);`

will crash.  The release I have before then is the 30th of January.

Thanks,
Safwan

**Comment by ShakAttacked** [comment]
Hi Luigi,

See attached stack that might help.  However, I have a theory that might help. :)  I think something broke in the code that doesn't check that a record has been prepared.  In my prototype, I have 3 records and they reference each other. I think that's the problem.  I'm including the result from Studio so you can see the relationship.

```

"result": [
        {
            "@type": "d",
            "@rid": "#21:0",
            "@version": 1,
            "@class": "Person",
            "data": "MyData",
            "name": "Bob4",
            "_id": "23423423423424fa",
            "index_id": "#25:0",
            "counter_id": "#29:0",
            "@fieldTypes": "index_id=x,counter_id=x"
        }
    ]

"result": [
        {
            "@type": "d",
            "@rid": "#25:0",
            "@version": 1,
            "@class": "PersonIndex",
            "name": "Bob4",
            "usersObject": {
                "23423423423424fa": {
                    "i": "23423423423424fa",
                    "n": "Bob4"
                },
                "Person": {
                    "i": "23423423423424fa",
                    "n": "Bob4"
                }
            },
            "users": [
                "#21:0"
            ],
            "person_id": "#21:0",
            "@fieldTypes": "users=z,person_id=x"
        }
    ]


"result": [
        {
            "@type": "d",
            "@rid": "#29:0",
            "@version": 1,
            "@class": "PersonCounter",
            "PERSON_COUNT": 1,
            "person_id": "#21:0",
            "@fieldTypes": "PERSON_COUNT=l,person_id=x"
        }
    ]
```

```
"OrientDB HTTP Connection /0:0:0:0:0:0:0:1:2480<-/0:0:0:0:0:0:0:1:56530@4759" daemon prio=5 tid=0x31 nid=NA runnable
  java.lang.Thread.State: RUNNABLE
	  at com.orientechnologies.orient.core.record.impl.ODocumentHelper.cloneValue(ODocumentHelper.java:889)
	  at com.orientechnologies.orient.core.record.impl.ODocument.copyTo(ODocument.java:855)
	  at com.orientechnologies.orient.core.record.impl.ODocument.copy(ODocument.java:823)
	  at com.orientechnologies.orient.core.record.impl.ODocumentHelper.cloneValue(ODocumentHelper.java:892)
	  at com.orientechnologies.orient.core.record.impl.ODocument.copyTo(ODocument.java:855)
	  at com.orientechnologies.orient.core.record.impl.ODocument.copy(ODocument.java:823)
	  at com.orientechnologies.orient.core.record.impl.ODocumentHelper.cloneValue(ODocumentHelper.java:892)
	  at com.orientechnologies.orient.core.record.impl.ODocument.copyTo(ODocument.java:855)
	  at com.orientechnologies.orient.core.record.impl.ODocument.copy(ODocument.java:823)
	  at com.orientechnologies.orient.core.record.impl.ODocumentHelper.cloneValue(ODocumentHelper.java:892)
	  at com.orientechnologies.orient.core.record.impl.ODocument.copyTo(ODocument.java:855)
	  at com.orientechnologies.orient.core.record.impl.ODocument.copy(ODocument.java:823)
	  at com.orientechnologies.orient.core.record.impl.ODocumentHelper.cloneValue(ODocumentHelper.java:892)
	  at com.orientechnologies.orient.core.record.impl.ODocument.copyTo(ODocument.java:855)
	  at com.orientechnologies.orient.core.record.impl.ODocument.copy(ODocument.java:823)
	  at com.orientechnologies.orient.core.record.impl.ODocumentHelper.cloneValue(ODocumentHelper.java:892)
	  at com.orientechnologies.orient.core.record.impl.ODocument.copyTo(ODocument.java:855)
	  at com.orientechnologies.orient.core.record.impl.ODocument.copy(ODocument.java:823)
	  at com.orientechnologies.orient.core.record.impl.ODocumentHelper.cloneValue(ODocumentHelper.java:892)
	  at com.orientechnologies.orient.core.record.impl.ODocument.copyTo(ODocument.java:855)
	  at com.orientechnologies.orient.core.record.impl.ODocument.copy(ODocument.java:823)
	  at com.orientechnologies.orient.core.record.impl.ODocumentHelper.cloneValue(ODocumentHelper.java:892)
	  at com.orientechnologies.orient.core.record.impl.ODocument.copyTo(ODocument.java:855)
	  at com.orientechnologies.orient.core.record.impl.ODocument.copy(ODocument.java:823)
	  at com.orientechnologies.orient.core.query.live.OLiveQueryHookV2.addOp(OLiveQueryHookV2.java:236)
	  at com.orientechnologies.orient.core.query.live.OLiveQueryHookV2.onRecordAfterCreate(OLiveQueryHookV2.java:210)
	  at com.orientechnologies.orient.core.hook.ODocumentHookAbstract.onTrigger(ODocumentHookAbstract.java:221)
	  at com.orientechnologies.orient.core.db.document.ODatabaseDocumentAbstract.callbackHooks(ODatabaseDocumentAbstract.java:707)
	  at com.orientechnologies.orient.core.storage.impl.local.OMicroTransaction.addRecordOperation(OMicroTransaction.java:523)
	  at com.orientechnologies.orient.core.storage.impl.local.OMicroTransaction.saveRecord(OMicroTransaction.java:308)
	  at com.orientechnologies.orient.core.storage.impl.local.OMicroTransaction.reSave(OMicroTransaction.java:608)
	  at com.orientechnologies.orient.core.storage.impl.local.OMicroTransaction.addRecordOperation(OMicroTransaction.java:465)
	  at com.orientechnologies.orient.core.storage.impl.local.OMicroTransaction.saveRecord(OMicroTransaction.java:308)
	  at com.orientechnologies.orient.core.db.document.ODatabaseDocumentEmbedded.executeSaveRecord(ODatabaseDocumentEmbedded.java:730)
	  at com.orientechnologies.orient.core.tx.OTransactionNoTx.saveNew(OTransactionNoTx.java:244)
	  at com.orientechnologies.orient.core.tx.OTransactionNoTx.saveRecord(OTransactionNoTx.java:174)
	  at com.orientechnologies.orient.core.db.document.ODatabaseDocumentAbstract.saveInternal(ODatabaseDocumentAbstract.java:2063)
	  at com.orientechnologies.orient.core.db.document.ODatabaseDocumentAbstract.save(ODatabaseDocumentAbstract.java:2023)
	  at com.orientechnologies.orient.core.db.document.ODatabaseDocumentAbstract.save(ODatabaseDocumentAbstract.java:1926)
	  at com.orientechnologies.orient.core.db.document.ODatabaseDocumentAbstract.save(ODatabaseDocumentAbstract.java:87)
	  at com.orientechnologies.orient.core.sql.executor.SaveElementStep$1.next(SaveElementStep.java:40)
	  at com.orientechnologies.orient.core.sql.executor.OInsertExecutionPlan.executeInternal(OInsertExecutionPlan.java:49)
	  at com.orientechnologies.orient.core.sql.parser.OInsertStatement.execute(OInsertStatement.java:119)
	  at com.orientechnologies.orient.core.command.OSqlScriptExecutor.execute(OSqlScriptExecutor.java:41)
	  at com.orientechnologies.orient.core.db.document.ODatabaseDocumentEmbedded.execute(ODatabaseDocumentEmbedded.java:588)
	  at com.orientechnologies.orient.server.network.protocol.http.command.post.OServerCommandPostCommand.executeStatement(OServerCommandPostCommand.java:174)
	  at com.orientechnologies.orient.server.network.protocol.http.command.post.OServerCommandPostCommand.execute(OServerCommandPostCommand.java:84)
	  at com.orientechnologies.orient.server.network.protocol.http.command.post.OServerCommandPostCommandGraph.execute(OServerCommandPostCommandGraph.java:36)
	  at com.orientechnologies.orient.server.network.protocol.http.ONetworkProtocolHttpAbstract.service(ONetworkProtocolHttpAbstract.java:172)
	  at com.orientechnologies.orient.server.network.protocol.http.ONetworkProtocolHttpAbstract.execute(ONetworkProtocolHttpAbstract.java:633)
	  at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:82)

"commons-pool-evictor-thread@4972" prio=5 tid=0x23 nid=NA waiting
  java.lang.Thread.State: WAITING
	  at sun.misc.Unsafe.park(Unsafe.java:-1)
	  at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215)
	  at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2078)
	  at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:1093)
	  at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:809)
	  at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1067)
	  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1127)
	  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	  at java.lang.Thread.run(Thread.java:745)

"OrientDB Write Cache Flush Task (touca_data)@4973" daemon prio=10 tid=0x1e nid=NA waiting
  java.lang.Thread.State: WAITING
	  at sun.misc.Unsafe.park(Unsafe.java:-1)
	  at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215)
	  at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2078)
	  at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:1093)
	  at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:809)
	  at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1067)
	  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1127)
	  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	  at java.lang.Thread.run(Thread.java:745)

"WAL Closer Task (touca_data)@4975" daemon prio=5 tid=0x1c nid=NA waiting
  java.lang.Thread.State: WAITING
	  at sun.misc.Unsafe.park(Unsafe.java:-1)
	  at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
	  at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2039)
	  at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:1081)
	  at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:809)
	  at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1067)
	  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1127)
	  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	  at java.lang.Thread.run(Thread.java:745)

"Thread-11@4976" daemon prio=5 tid=0x1b nid=NA waiting
  java.lang.Thread.State: WAITING
	  at sun.misc.Unsafe.park(Unsafe.java:-1)
	  at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215)
	  at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2078)
	  at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:1093)
	  at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:809)
	  at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1067)
	  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1127)
	  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	  at java.lang.Thread.run(Thread.java:745)

"OrientDB Write Cache Flush Task (OSystem)@4979" daemon prio=10 tid=0x14 nid=NA waiting
  java.lang.Thread.State: WAITING
	  at sun.misc.Unsafe.park(Unsafe.java:-1)
	  at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215)
	  at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2078)
	  at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:1093)
	  at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:809)
	  at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1067)
	  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1127)
	  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	  at java.lang.Thread.run(Thread.java:745)

"WAL Closer Task (OSystem)@4981" daemon prio=5 tid=0x12 nid=NA waiting
  java.lang.Thread.State: WAITING
	  at sun.misc.Unsafe.park(Unsafe.java:-1)
	  at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
	  at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2039)
	  at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:1081)
	  at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:809)
	  at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1067)
	  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1127)
	  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	  at java.lang.Thread.run(Thread.java:745)

"Thread-5@4982" daemon prio=5 tid=0x11 nid=NA waiting
  java.lang.Thread.State: WAITING
	  at sun.misc.Unsafe.park(Unsafe.java:-1)
	  at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215)
	  at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2078)
	  at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:1093)
	  at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:809)
	  at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1067)
	  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1127)
	  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	  at java.lang.Thread.run(Thread.java:745)

"Thread-0@4984" prio=5 tid=0xb nid=NA waiting
  java.lang.Thread.State: WAITING
	  at sun.misc.Unsafe.park(Unsafe.java:-1)
	  at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
	  at java.util.concurrent.locks.AbstractQueuedSynchronizer.parkAndCheckInterrupt(AbstractQueuedSynchronizer.java:836)
	  at java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedInterruptibly(AbstractQueuedSynchronizer.java:997)
	  at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly(AbstractQueuedSynchronizer.java:1304)
	  at java.util.concurrent.CountDownLatch.await(CountDownLatch.java:231)
	  at com.orientechnologies.orient.server.OServer.waitForShutdown(OServer.java:609)
	  at com.orientechnologies.orient.server.OServerMain$1.run(OServerMain.java:49)

"Thread-17@4955" prio=5 tid=0x21 nid=NA waiting
  java.lang.Thread.State: WAITING
	  at sun.misc.Unsafe.park(Unsafe.java:-1)
	  at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
	  at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2039)
	  at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:442)
	  at com.orientechnologies.orient.core.query.live.OLiveQueryQueueThreadV2.run(OLiveQueryQueueThreadV2.java:58)

"OrientDB WAL Flush Task (touca_data)@4974" daemon prio=5 tid=0x1d nid=NA runnable
  java.lang.Thread.State: RUNNABLE
	  at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1067)
	  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1127)
	  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	  at java.lang.Thread.run(Thread.java:745)

"OrientDB WAL Flush Task (OSystem)@4980" daemon prio=5 tid=0x13 nid=NA runnable
  java.lang.Thread.State: RUNNABLE
	  at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1067)
	  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1127)
	  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	  at java.lang.Thread.run(Thread.java:745)

"main@4988" prio=5 tid=0x1 nid=NA waiting
  java.lang.Thread.State: WAITING
	  at java.lang.Object.wait(Object.java:-1)
	  at java.lang.Thread.join(Thread.java:1245)
	  at java.lang.Thread.join(Thread.java:1319)
	  at com.orientechnologies.orient.server.OServerMain.main(OServerMain.java:59)

"OrientDB HTTP Connection /0:0:0:0:0:0:0:1:2480<-/0:0:0:0:0:0:0:1:57424@4833" daemon prio=5 tid=0x3f nid=NA runnable
  java.lang.Thread.State: RUNNABLE
	  at java.net.SocketInputStream.socketRead0(SocketInputStream.java:-1)
	  at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
	  at java.net.SocketInputStream.read(SocketInputStream.java:170)
	  at java.net.SocketInputStream.read(SocketInputStream.java:141)
	  at java.io.BufferedInputStream.fill(BufferedInputStream.java:246)
	  at java.io.BufferedInputStream.read(BufferedInputStream.java:265)
	  - locked <0x137d> (a java.io.BufferedInputStream)
	  at com.orientechnologies.orient.enterprise.channel.text.OChannelText.read(OChannelText.java:61)
	  at com.orientechnologies.orient.server.network.protocol.http.ONetworkProtocolHttpAbstract.execute(ONetworkProtocolHttpAbstract.java:577)
	  at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:82)

"OrientDB ONetworkProtocolHttpDb listen at 0.0.0.0:2480-2490@4977" prio=5 tid=0x19 nid=NA runnable
  java.lang.Thread.State: RUNNABLE
	  at java.net.PlainSocketImpl.socketAccept(PlainSocketImpl.java:-1)
	  at java.net.AbstractPlainSocketImpl.accept(AbstractPlainSocketImpl.java:404)
	  at java.net.ServerSocket.implAccept(ServerSocket.java:545)
	  at java.net.ServerSocket.accept(ServerSocket.java:513)
	  at com.orientechnologies.orient.server.network.OServerNetworkListener.run(OServerNetworkListener.java:188)

"OrientDB ONetworkProtocolBinary listen at 0.0.0.0:2424-2430@4978" prio=5 tid=0x17 nid=NA runnable
  java.lang.Thread.State: RUNNABLE
	  at java.net.PlainSocketImpl.socketAccept(PlainSocketImpl.java:-1)
	  at java.net.AbstractPlainSocketImpl.accept(AbstractPlainSocketImpl.java:404)
	  at java.net.ServerSocket.implAccept(ServerSocket.java:545)
	  at java.net.ServerSocket.accept(ServerSocket.java:513)
	  at com.orientechnologies.orient.server.network.OServerNetworkListener.run(OServerNetworkListener.java:188)

"Timer-0@4983" daemon prio=5 tid=0xd nid=NA waiting
  java.lang.Thread.State: WAITING
	  at java.lang.Object.wait(Object.java:-1)
	  at java.util.TimerThread.mainLoop(Timer.java:552)
	  at java.util.TimerThread.run(Timer.java:505)

"Finalizer@4986" daemon prio=8 tid=0x3 nid=NA waiting
  java.lang.Thread.State: WAITING
	  at java.lang.Object.wait(Object.java:-1)
	  at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:143)
	  at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:164)
	  at java.lang.ref.Finalizer$FinalizerThread.run(Finalizer.java:209)

"Reference Handler@4987" daemon prio=10 tid=0x2 nid=NA waiting
  java.lang.Thread.State: WAITING
	  at java.lang.Object.wait(Object.java:-1)
	  at java.lang.Object.wait(Object.java:502)
	  at java.lang.ref.Reference$ReferenceHandler.run(Reference.java:157)

"OrientDB HTTP Connection /0:0:0:0:0:0:0:1:2480<-/0:0:0:0:0:0:0:1:58520@4968" daemon prio=5 tid=0x4b nid=NA runnable
  java.lang.Thread.State: RUNNABLE

"OrientDB HTTP Connection /0:0:0:0:0:0:0:1:2480<-/0:0:0:0:0:0:0:1:58518@4969" daemon prio=5 tid=0x4a nid=NA runnable
  java.lang.Thread.State: RUNNABLE

"OrientDB HTTP Connection /0:0:0:0:0:0:0:1:2480<-/0:0:0:0:0:0:0:1:58516@4970" daemon prio=5 tid=0x49 nid=NA runnable
  java.lang.Thread.State: RUNNABLE

"OrientDB HTTP Connection /0:0:0:0:0:0:0:1:2480<-/0:0:0:0:0:0:0:1:58454@4971" daemon prio=5 tid=0x48 nid=NA runnable
  java.lang.Thread.State: RUNNABLE

"Signal Dispatcher@4985" daemon prio=9 tid=0x4 nid=NA runnable
  java.lang.Thread.State: RUNNABLE

```

**Comment by luigidellaquila** [comment]
Hi @ShakAttacked 

Ok, it makes sense now, I think I know where to look at.

Thanks

Luigi

**Comment by luigidellaquila** [comment]
@ShakAttacked 

Could you please post the exact statement you are using? I'm having some problems to reproduce it

Thanks

Luigi

**Comment by ShakAttacked** [comment]
@luigidellaquila 

Not so easy unfortunately.. it all starts from the query below but it's Hooks that create the other 2 records.  I will try to describe the flow of hooks below.  Also, I'll send you my code by email. It might help.

```
INSERT INTO Person (name, data, _id) 
          VALUES ('Bob4', 'MyData', '23423423423424fa')
```

```
onRecordBeforeCreate on Person. will create 2 records, one in PersonCounter and another in PersonIndex record. it'll modify the fields below on the Person record.
   "index_id": "#25:0",
   "counter_id": "#29:0",
The PersonIndex will copy some values from Person and have a reference back to Person.
The PersonCounter will have a reference back to Person as well.

onRecordAfterCreate on Person. 
it will increment a counter in PersonCounter.
will add a value into users field in PersonIndex (EmbeddedList).  
It will also add 2 values into usersObject in PersonIndex.

```
Thanks,
Safwan

**Comment by luigidellaquila** [comment]
Ok, so you have a circular dependency, from Person to PersonIndex and back to Person, is it correct?

Thanks

Luigi

**Comment by ShakAttacked** [comment]
Correct, same for PersonCounter.. see email I just sent you, it's prototype code and not cleaned up but should help.  Only look at onRecordBeforeCreate  and onRecordAfterCreate  in testHook.

Thanks,
Safwan

**Comment by ShakAttacked** [comment]
Just to be clear.. this will only fail if you have.

**Comment by luigidellaquila** [comment]
Hi @ShakAttacked 

Good news, I found and fixed the problem.
I just pushed the fix, a new snapshot should be available in a few minutes

Thanks

Luigi
