### ISSUE TITLE
java.util.zip.ZipException: invalid code lengths set when plugin is getting installed.

### ISSUE THREAD

**Issue by ShakAttacked** [orientechnologies/orientdb#8104]
### OS: Centos

Hi,  Exception showing with a plugin is updated.  doesn't happen all the time.

```
2018-02-14 10:31:28:645 INFO  Installing dynamic plugin 'pluginname.jar'...Error on installing dynamic plugin 'pluginname.jar'
java.util.zip.ZipException: invalid code lengths set
	at java.util.zip.InflaterInputStream.read(InflaterInputStream.java:164)
	at java.io.FilterInputStream.read(FilterInputStream.java:133)
	at com.orientechnologies.common.io.OIOUtils.copyStream(OIOUtils.java:193)
	at com.orientechnologies.orient.core.record.ORecordAbstract.fromJSON(ORecordAbstract.java:179)
	at com.orientechnologies.orient.core.record.impl.ODocument.fromJSON(ODocument.java:2059)
	at com.orientechnologies.orient.server.plugin.OServerPluginManager.installDynamicPlugin(OServerPluginManager.java:348)
	at com.orientechnologies.orient.server.plugin.OServerPluginManager.updatePlugin(OServerPluginManager.java:210)
	at com.orientechnologies.orient.server.plugin.OServerPluginManager.updatePlugins(OServerPluginManager.java:308)
	at com.orientechnologies.orient.server.plugin.OServerPluginManager.access$000(OServerPluginManager.java:58)
	at com.orientechnologies.orient.server.plugin.OServerPluginManager$1.run(OServerPluginManager.java:101)
	at java.util.TimerThread.mainLoop(Timer.java:555)
	at java.util.TimerThread.run(Timer.java:505)


```

Thanks,
Safwan

**Comment by luigidellaquila** [comment]
Hi @ShakAttacked 

It seems to be a problem with the format of the jar file (the Java zip library is failing).
Could you please provide the jar (privately)? I'll check it

Thanks

Luigi

**Comment by ShakAttacked** [comment]
Hi @luigidellaquila ,

it doesn't happen when I restart the server. it's only during the update of the plugin. do you still want it?

Thanks,
Safwan

**Comment by luigidellaquila** [comment]
Ok, got it, so the problem could be related to the hot loading of the file, maybe it's just trying to unzip too early (the file is not completely copied) or it's just loading it the wrong way.

I'll try to reproduce the problem with my code, but if you have a chance to send me the file maybe it will help

Thanks

Luigi
