### ISSUE TITLE
`IMPORT DATABASE` fails on WAL file missing

### ISSUE THREAD

**Issue by triketora** [orientechnologies/orientdb#8124]
## Expected behavior  
`IMPORT DATABASE` command should successfully import exported zip file and load data into database. 

## Actual behavior  
Errors on WAL file not found.

```
orientdb {db=bb_dev}> IMPORT DATABASE /Users/tracy/Desktop/ORIENTDB_2018-02-26_bb_staging.zip

Importing database DATABASE /Users/tracy/Desktop/ORIENTDB_2018-02-26_bb_staging.zip...
Started import of database 'plocal:/Users/tracy/programs/orientdb-community-importers-2.2.31/databases/bb_dev' from /var/folders/yp/qsg86t_92tn9lssm_tn83khw0000gn/T/bb_devimport1375537095340454090ORIENTDB_2018-02-26_bb_staging.zip...
Non merge mode (-merge=false): removing all default non security classesError on database import happened just before line 0, column 1
com.orientechnologies.common.io.OIOException: Error during appending of new segment to the WAL
	at com.orientechnologies.orient.core.storage.impl.local.paginated.wal.ODiskWriteAheadLog.appendNewSegment(ODiskWriteAheadLog.java:1156)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.makeFullCheckpoint(OAbstractPaginatedStorage.java:3707)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.synch(OAbstractPaginatedStorage.java:2933)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.checkLowDiskSpaceRequestsAndReadOnlyConditions(OAbstractPaginatedStorage.java:5048)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.deleteIndexEngine(OAbstractPaginatedStorage.java:2112)
	at com.orientechnologies.orient.core.index.OIndexAbstract.delete(OIndexAbstract.java:645)
	at com.orientechnologies.orient.core.index.OIndexAbstract.delete(OIndexAbstract.java:67)
	at com.orientechnologies.orient.core.index.OIndexManagerShared.dropIndex(OIndexManagerShared.java:261)
	at com.orientechnologies.orient.core.index.OIndexManagerProxy.dropIndex(OIndexManagerProxy.java:100)
	at com.orientechnologies.orient.core.db.tool.ODatabaseImport.removeDefaultNonSecurityClasses(ODatabaseImport.java:411)
	at com.orientechnologies.orient.core.db.tool.ODatabaseImport.importDatabase(ODatabaseImport.java:161)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.importDatabase(ONetworkProtocolBinary.java:2990)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.executeRequest(ONetworkProtocolBinary.java:720)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.sessionRequest(ONetworkProtocolBinary.java:398)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.execute(ONetworkProtocolBinary.java:217)
	at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:82)
Caused by: java.io.FileNotFoundException: /Users/tracy/programs/orientdb-community-importers-2.2.31/databases/bb_dev/bb_dev.5.wal (No such file or directory)
	at java.io.RandomAccessFile.open0(Native Method)
	at java.io.RandomAccessFile.open(RandomAccessFile.java:316)
	at java.io.RandomAccessFile.<init>(RandomAccessFile.java:243)
	at com.orientechnologies.orient.core.storage.impl.local.paginated.wal.OLogSegmentV2.getRndFile(OLogSegmentV2.java:397)
	at com.orientechnologies.orient.core.storage.impl.local.paginated.wal.OLogSegmentV2.init(OLogSegmentV2.java:441)
	at com.orientechnologies.orient.core.storage.impl.local.paginated.wal.ODiskWriteAheadLog.appendNewSegment(ODiskWriteAheadLog.java:627)
	at com.orientechnologies.orient.core.storage.impl.local.paginated.wal.ODiskWriteAheadLog.appendNewSegment(ODiskWriteAheadLog.java:1153)
	... 15 more

Error: com.orientechnologies.common.io.OIOException

Error: java.io.EOFException
```

## Steps to reproduce  
1. Start console.
2. Connect to database.
3. Run `IMPORT DATABASE` command.

**Comment by laa** [comment]
Hi @triketora could you send me your backup file? Becuase we have the test on database import and it never fails.

**Comment by triketora** [comment]
I was able to get it working... I don't think I did anything different, but it imports successfully now.

**Comment by laa** [comment]
It is hard to fix it then because we can not reproduce it. If you encounter this issue problem again, please reopen the issue.
