### ISSUE TITLE
Syncing restarted node fails with cluster not found error

### ISSUE THREAD

**Issue by Jotschi** [orientechnologies/orientdb#8127]
### OS: Debian Linux

I'm seeing the following exceptions if I restart a previously stopped node in my cluster:

> Cluster id 922 was not found in database 'storage'

Log:
```
TEST INFO  [dockerjava-netty-1-14] [Slf4jLogConsumer.java:44] - STDERR: 2018-02-28 10:34:31:472 INFO  Storage 'plocal:/mesh/data/graphdb/storage' is opened under OrientDB distribution : 2.2.32 (build 68709d4478301dc6af110621f13fb176e4ca98b0, branch 2.2.x)Exception `460EAB33` in storage `plocal:/mesh/data/graphdb/storage`: 2.2.32 (build 68709d4478301dc6af110621f13fb176e4ca98b0, branch 2.2.x)
TEST INFO  [dockerjava-netty-1-14] [Slf4jLogConsumer.java:44] - STDERR: com.orientechnologies.orient.core.exception.OConfigurationException: Cluster id 922 was not found in database 'storage'
TEST INFO  [dockerjava-netty-1-14] [Slf4jLogConsumer.java:44] - STDERR: DB name="storage"
TEST INFO  [dockerjava-netty-1-14] [Slf4jLogConsumer.java:44] - STDERR: at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.count(OAbstractPaginatedStorage.java:1311)
TEST INFO  [dockerjava-netty-1-14] [Slf4jLogConsumer.java:44] - STDERR: at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.countClusterElements(ODatabaseDocumentTx.java:821)
TEST INFO  [dockerjava-netty-1-14] [Slf4jLogConsumer.java:44] - STDERR: at com.orientechnologies.orient.core.iterator.ORecordIteratorClass.config(ORecordIteratorClass.java:141)
TEST INFO  [dockerjava-netty-1-14] [Slf4jLogConsumer.java:44] - STDERR: at com.orientechnologies.orient.core.iterator.ORecordIteratorClass.<init>(ORecordIteratorClass.java:90)
TEST INFO  [dockerjava-netty-1-14] [Slf4jLogConsumer.java:44] - STDERR: at com.orientechnologies.orient.core.iterator.ORecordIteratorClass.<init>(ORecordIteratorClass.java:68)
TEST INFO  [dockerjava-netty-1-14] [Slf4jLogConsumer.java:44] - STDERR: at com.orientechnologies.orient.core.sql.OCommandExecutorSQLResultsetAbstract.searchInClasses(OCommandExecutorSQLResultsetAbstract.java:484)
TEST INFO  [dockerjava-netty-1-14] [Slf4jLogConsumer.java:44] - STDERR: at com.orientechnologies.orient.core.sql.OCommandExecutorSQLResultsetAbstract.searchInClasses(OCommandExecutorSQLResultsetAbstract.java:473)
TEST INFO  [dockerjava-netty-1-14] [Slf4jLogConsumer.java:44] - STDERR: at com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.searchInClasses(OCommandExecutorSQLSelect.java:1020)
TEST INFO  [dockerjava-netty-1-14] [Slf4jLogConsumer.java:44] - STDERR: at com.orientechnologies.orient.core.sql.OCommandExecutorSQLResultsetAbstract.assignTarget(OCommandExecutorSQLResultsetAbstract.java:211)
TEST INFO  [dockerjava-netty-1-14] [Slf4jLogConsumer.java:44] - STDERR: at com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.assignTarget(OCommandExecutorSQLSelect.java:527)
TEST INFO  [dockerjava-netty-1-14] [Slf4jLogConsumer.java:44] - STDERR: at com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.executeSearch(OCommandExecutorSQLSelect.java:509)
TEST INFO  [dockerjava-netty-1-14] [Slf4jLogConsumer.java:44] - STDERR: at com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.execute(OCommandExecutorSQLSelect.java:485)
TEST INFO  [dockerjava-netty-1-14] [Slf4jLogConsumer.java:44] - STDERR: at com.orientechnologies.orient.core.sql.OCommandExecutorSQLDelegate.execute(OCommandExecutorSQLDelegate.java:70)
TEST INFO  [dockerjava-netty-1-14] [Slf4jLogConsumer.java:44] - STDERR: at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.executeCommand(OAbstractPaginatedStorage.java:3417)
TEST INFO  [dockerjava-netty-1-14] [Slf4jLogConsumer.java:44] - STDERR: at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.command(OAbstractPaginatedStorage.java:3335)
TEST INFO  [dockerjava-netty-1-14] [Slf4jLogConsumer.java:44] - STDERR: at com.orientechnologies.orient.core.sql.query.OSQLQuery.run(OSQLQuery.java:78)
TEST INFO  [dockerjava-netty-1-14] [Slf4jLogConsumer.java:44] - STDERR: at com.orientechnologies.orient.core.sql.query.OSQLAsynchQuery.run(OSQLAsynchQuery.java:74)
TEST INFO  [dockerjava-netty-1-14] [Slf4jLogConsumer.java:44] - STDERR: at com.orientechnologies.orient.core.sql.query.OSQLSynchQuery.run(OSQLSynchQuery.java:102)
TEST INFO  [dockerjava-netty-1-14] [Slf4jLogConsumer.java:44] - STDERR: at com.orientechnologies.orient.core.query.OQueryAbstract.execute(OQueryAbstract.java:33)
TEST INFO  [dockerjava-netty-1-14] [Slf4jLogConsumer.java:44] - STDERR: at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.query(ODatabaseDocumentTx.java:760)
TEST INFO  [dockerjava-netty-1-14] [Slf4jLogConsumer.java:44] - STDERR: at com.orientechnologies.orient.core.metadata.function.OFunctionLibraryImpl.load(OFunctionLibraryImpl.java:73)
TEST INFO  [dockerjava-netty-1-14] [Slf4jLogConsumer.java:44] - STDERR: at com.orientechnologies.orient.core.metadata.OMetadataDefault$5.call(OMetadataDefault.java:238)
TEST INFO  [dockerjava-netty-1-14] [Slf4jLogConsumer.java:44] - STDERR: at com.orientechnologies.orient.core.metadata.OMetadataDefault$5.call(OMetadataDefault.java:234)
TEST INFO  [dockerjava-netty-1-8] [Slf4jLogConsumer.java:44] - STDERR: 
TEST INFO  [dockerjava-netty-1-14] [Slf4jLogConsumer.java:44] - STDERR: at com.orientechnologies.common.concur.resource.OSharedContainerImpl.getResource(OSharedContainerImpl.java:62)
TEST INFO  [dockerjava-netty-1-8] [Slf4jLogConsumer.java:44] - STDERR: 2018-02-28 10:34:31:501 INFO  [nodeC@0-17-1-SNAPSHOT] Trying to recover current server for database 'storage'...
TEST INFO  [dockerjava-netty-1-14] [Slf4jLogConsumer.java:44] - STDERR: at com.orientechnologies.orient.core.storage.OStorageAbstract.getResource(OStorageAbstract.java:144)
TEST INFO  [dockerjava-netty-1-14] [Slf4jLogConsumer.java:44] - STDERR: at com.orientechnologies.orient.core.metadata.OMetadataDefault.init(OMetadataDefault.java:234)
TEST INFO  [dockerjava-netty-1-14] [Slf4jLogConsumer.java:44] - STDERR: at com.orientechnologies.orient.core.metadata.OMetadataDefault.load(OMetadataDefault.java:89)
TEST INFO  [dockerjava-netty-1-14] [Slf4jLogConsumer.java:44] - STDERR: at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.initAtFirstOpen(ODatabaseDocumentTx.java:3224)
TEST INFO  [dockerjava-netty-1-14] [Slf4jLogConsumer.java:44] - STDERR: at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.open(ODatabaseDocumentTx.java:271)
TEST INFO  [dockerjava-netty-1-14] [Slf4jLogConsumer.java:44] - STDERR: at com.orientechnologies.orient.server.OServer.openDatabaseBypassingSecurity(OServer.java:1006)
TEST INFO  [dockerjava-netty-1-14] [Slf4jLogConsumer.java:44] - STDERR: at com.orientechnologies.orient.server.OServer.openDatabase(OServer.java:973)
TEST INFO  [dockerjava-netty-1-14] [Slf4jLogConsumer.java:44] - STDERR: at com.orientechnologies.orient.server.distributed.impl.ODistributedAbstractPlugin.installDatabaseOnLocalNode(ODistributedAbstractPlugin.java:2060)
TEST INFO  [dockerjava-netty-1-14] [Slf4jLogConsumer.java:44] - STDERR: at com.orientechnologies.orient.server.distributed.impl.ODistributedAbstractPlugin.installDatabaseFromNetwork(ODistributedAbstractPlugin.java:1565)
TEST INFO  [dockerjava-netty-1-14] [Slf4jLogConsumer.java:44] - STDERR: at com.orientechnologies.orient.server.distributed.impl.ODistributedAbstractPlugin.requestDatabaseFullSync(ODistributedAbstractPlugin.java:1309)
TEST INFO  [dockerjava-netty-1-14] [Slf4jLogConsumer.java:44] - STDERR: at com.orientechnologies.orient.server.distributed.impl.ODistributedAbstractPlugin.requestFullDatabase(ODistributedAbstractPlugin.java:1022)
TEST INFO  [dockerjava-netty-1-14] [Slf4jLogConsumer.java:44] - STDERR: at com.orientechnologies.orient.server.distributed.impl.ODistributedAbstractPlugin$3.call(ODistributedAbstractPlugin.java:966)
TEST INFO  [dockerjava-netty-1-14] [Slf4jLogConsumer.java:44] - STDERR: at com.orientechnologies.orient.server.distributed.impl.ODistributedAbstractPlugin$3.call(ODistributedAbstractPlugin.java:895)
TEST INFO  [dockerjava-netty-1-14] [Slf4jLogConsumer.java:44] - STDERR: at com.orientechnologies.orient.server.distributed.impl.ODistributedAbstractPlugin.executeInDistributedDatabaseLock(ODistributedAbstractPlugin.java:1783)
TEST INFO  [dockerjava-netty-1-14] [Slf4jLogConsumer.java:44] - STDERR: at com.orientechnologies.orient.server.distributed.impl.ODistributedAbstractPlugin.installDatabase(ODistributedAbstractPlugin.java:894)
TEST INFO  [dockerjava-netty-1-14] [Slf4jLogConsumer.java:44] - STDERR: at com.orientechnologies.orient.server.distributed.impl.OClusterHealthChecker.checkServerStatus(OClusterHealthChecker.java:203)
TEST INFO  [dockerjava-netty-1-14] [Slf4jLogConsumer.java:44] - STDERR: at com.orientechnologies.orient.server.distributed.impl.OClusterHealthChecker.run(OClusterHealthChecker.java:59)
TEST INFO  [dockerjava-netty-1-14] [Slf4jLogConsumer.java:44] - STDERR: at java.util.TimerThread.mainLoop(Timer.java:555)
TEST INFO  [dockerjava-netty-1-14] [Slf4jLogConsumer.java:44] - STDERR: at java.util.TimerThread.run(Timer.java:505)
```

Full log:
* https://gist.github.com/Jotschi/fb1dd92a11d4a21fdef64be7da54e143

The following error has already been reported in https://www.prjhub.com/#/issues/9914

```
TEST INFO  [dockerjava-netty-1-14] [Slf4jLogConsumer.java:44] - STDERR: com.orientechnologies.orient.core.exception.ODatabaseException: Cannot execute delta-sync because a new file has been added. Filename: 'oschedule_0.cpm' (id=395391725742327774)
```

**Comment by Jotschi** [comment]
@tglman This error happens when using the latest 2.2.33-SNAPSHOT

**Comment by tglman** [comment]
Hi @Jotschi,

I will try to reproduce and fix right after I get done a review of the sync order, if you have a way to reproduce this deterministically let me know.

Regards
Emanuele

**Comment by tglman** [comment]
Hi @Jotschi,

I found an issue when in some cases for syncing we were using a not updated backup, this could have created this issue, I just pushed the fix for this, it should be in the 2.2.34-SNAPSHOT in a couple of hours.

Regards

**Comment by Jotschi** [comment]
@tglman Thanks for the feedback. I'll try to test the snapshot as soon as possible. I check my tests on Thursday or Friday since I'm in a workshop right now.

**Comment by Jotschi** [comment]
I did not see the error when using 2.2.34-SNAPSHOT. Closing the issue. Thanks for the fix.
