### ISSUE TITLE
teleporter error about execution of oteleporter.sh

### ISSUE THREAD

**Issue by shushengxing** [orientechnologies/orientdb#8130]
### OS: centos7  

When I use oteleporter.sh to import data from postgresql to orientdb, it has a error. The description is as follows, and it never occurred before. This operation is the same as the previous operation, but it occurs the error.

ERROR:
com.orientechnologies.teleporter.exception.OTeleporterRuntimeException - com.orientechnologies.orient.core.exception.OSerializationException: Error on unmarshalling JSON content '<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN"> <html> <title> 301 Moved Permanently </title> <body> <h1>Moved Permanently</h1> <p>The document has moved <a href="https://orientdb.com/jdbc-drivers.json">here</a></p></body></html>' : content must be between { } 
at com.orientechnologies.teleporter.util.ODriverConfigurator.readJsonFromUrl(ODriverConfigurator.java:233)
at com.orientechnologies.teleporter.util.ODriverConfigurator.checkConfiguration(ODriverConfigurator.java:102)
at com.orientechnologies.teleporter.main.OTeleporter.execute(OTeleporter.java:248)
at com.orientechnologies.teleporter.main.OTeleporter.main(OTeleporter.java:205)

**Comment by shushengxing** [comment]
I look forward to your help. 
Thanks very much.

**Comment by tglman** [comment]
Hi,

We fixed this, closing.
