### ISSUE TITLE
Distributed sync fails because WAL file rotates

### ISSUE THREAD

**Issue by aandriyc** [orientechnologies/orientdb#8144]
## Expected behavior  
Initial database sync completes successfully  

## Actual behavior  
During sync WAL file name rotates, but sync looks for old file and replication fails (actual wal files that present during failure are some-db.2.wal, some-db.3.wal even though some-db.0.wal was in place when replication started):

java.lang.IllegalArgumentException: Directory /opt/orientdb/databases/some-db/some-db.0.wal not found
	at com.orientechnologies.orient.core.compression.impl.OZIPCompressionUtil.addFolder(OZIPCompressionUtil.java:145)
	at com.orientechnologies.orient.core.compression.impl.OZIPCompressionUtil.addFolder(OZIPCompressionUtil.java:127)
	at com.orientechnologies.orient.core.compression.impl.OZIPCompressionUtil.compressDirectory(OZIPCompressionUtil.java:57)
	at com.orientechnologies.orient.core.storage.impl.local.paginated.OLocalPaginatedStorage.backup(OLocalPaginatedStorage.java:229)
	at com.orientechnologies.orient.server.distributed.impl.ODistributedStorage.backup(ODistributedStorage.java:1880)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.backup(ODatabaseDocumentTx.java:3060)
	at com.orientechnologies.orient.server.distributed.impl.task.OSyncDatabaseTask$1.run(OSyncDatabaseTask.java:123)
	at java.lang.Thread.run(Thread.java:748)

## Steps to reproduce  
Do initial sync in distributed setup on large DB, so sync takes significant time

**Comment by laa** [comment]
Duplication of https://github.com/orientechnologies/orientdb/issues/8005 will try to fix it ASAP.
