### ISSUE TITLE
List of Map can't be serialized or deserialized in 2.3.30 (Distributed)

### ISSUE THREAD

**Issue by dgilling** [orientechnologies/orientdb#8145]
I am trying to store an embedded list of map in a class. This is for a class that is mixed schema. i.e. certain fields are created from JSON and I have no control over that schema, but needs to hold a json array.

I have tried both a list of ODocument and also a list of Map since documentation is unclear what the java clients supports. Neither seems to work though. Maybe it's something I'm doing but the exception message has little insight even for someone who's been using OrientDb for awhile.

## CASE 1
For an entity:

```java
class MyClass {
java.util.Set<java.util.Map<String, Object>> field = new java.util.HashSet<>();
}
```
When I serialize the object, I get an error:
com.orientechnologies.orient.object.enhancement.OObjectEntitySerializer:1370

```java
    if (iType.equals(OType.LINKLIST) || iType.equals(OType.LINKSET) || iType.equals(OType.LINKMAP))
      linkedType = OType.LINK;
    else if (iType.equals(OType.EMBEDDEDLIST) || iType.equals(OType.EMBEDDEDSET) || iType.equals(OType.EMBEDDEDMAP))
      if (firstValue instanceof List)
        linkedType = OType.EMBEDDEDLIST;
      else if (firstValue instanceof Set)
        linkedType = OType.EMBEDDEDSET;
      else if (firstValue instanceof Map)
        linkedType = OType.EMBEDDEDMAP;
      else
        linkedType = OType.EMBEDDED;
    else
      throw new IllegalArgumentException("Type " + iType + " must be a multi value type (collection or map)");
```

The field type is supposed to be an EMBEDDEDSET or EMBEDDEDLIST (I tried both after dropping the columns), although the client lib is assigning it as an EMBEDDED iType

[error] application - Error serializing object of class class com.moesif.graphdb.entities.verticies.eventdata.EventGraphQlDefinition
	DB name="event-graph-dev"
com.orientechnologies.orient.core.exception.OSerializationException: Error serializing object of class class com.moesif.graphdb.entities.verticies.eventdata.EventGraphQlDefinition
	DB name="event-graph-dev"
	at com.orientechnologies.orient.object.enhancement.OObjectEntitySerializer.serializeObject(OObjectEntitySerializer.java:147)
	at com.orientechnologies.orient.object.enhancement.OObjectEntitySerializer.typeToStream(OObjectEntitySerializer.java:808)
	at com.orientechnologies.orient.object.enhancement.OObjectEntitySerializer.multiValueToStream(OObjectEntitySerializer.java:1374)
	at com.orientechnologies.orient.object.enhancement.OObjectEntitySerializer.typeToStream(OObjectEntitySerializer.java:796)
	at com.orientechnologies.orient.object.enhancement.OObjectEntitySerializer.toStream(OObjectEntitySerializer.java:1211)
	at com.orientechnologies.orient.object.enhancement.OObjectEntitySerializer.serializeObject(OObjectEntitySerializer.java:145)
	at com.orientechnologies.orient.object.enhancement.OObjectEntitySerializer.typeToStream(OObjectEntitySerializer.java:808)
	at com.orientechnologies.orient.object.enhancement.OObjectEntitySerializer.toStream(OObjectEntitySerializer.java:1211)
	at com.orientechnologies.orient.object.enhancement.OObjectEntitySerializer.serializeObject(OObjectEntitySerializer.java:145)
	at com.orientechnologies.orient.object.enhancement.OObjectProxyMethodHandler.setValue(OObjectProxyMethodHandler.java:845)
Caused by: java.lang.IllegalArgumentException: Type EMBEDDED must be a multi value type (collection or map)
	at com.orientechnologies.orient.object.enhancement.OObjectEntitySerializer.multiValueToStream(OObjectEntitySerializer.java:1370)
	at com.orientechnologies.orient.object.enhancement.OObjectEntitySerializer.typeToStream(OObjectEntitySerializer.java:799)
	at com.orientechnologies.orient.object.enhancement.OObjectEntitySerializer.multiValueToStream(OObjectEntitySerializer.java:1391)
	at com.orientechnologies.orient.object.enhancement.OObjectEntitySerializer.typeToStream(OObjectEntitySerializer.java:799)
	at com.orientechnologies.orient.object.enhancement.OObjectEntitySerializer.multiValueToStream(OObjectEntitySerializer.java:1374)
	at com.orientechnologies.orient.object.enhancement.OObjectEntitySerializer.typeToStream(OObjectEntitySerializer.java:796)
	at com.orientechnologies.orient.object.enhancement.OObjectEntitySerializer.toStream(OObjectEntitySerializer.java:1211)
	at com.orientechnologies.orient.object.enhancement.OObjectEntitySerializer.serializeObject(OObjectEntitySerializer.java:145)
	at com.orientechnologies.orient.object.enhancement.OObjectEntitySerializer.typeToStream(OObjectEntitySerializer.java:808)
	at com.orientechnologies.orient.object.enhancement.OObjectEntitySerializer.multiValueToStream(OObjectEntitySerializer.java:1374)

## CASE 2
For an entity:

```java
class MyClass {
    @Embedded
    private java.util.Set<ODocument> field = new java.util.HashSet<>();
}
```

It serializes and stores correctly on insert, but when I attempt to read the field back, I get the following error:
com.orientechnologies.orient.object.enhancement.OObjectEntityEnhancer:82

```java
  public <T> T getProxiedInstance(final Class<T> iClass, Object iEnclosingInstance, final ODocument doc, final ProxyObject parent,
      Object... iArgs) {
    if (iClass == null) {
      throw new OSerializationException("Type '" + doc.getClassName()
          + "' cannot be serialized because is not part of registered entities. To fix this error register this class");
    }
```
[error] application - Type 'null' cannot be serialized because is not part of registered entities. To fix this error register this class
	DB name="event-graph-dev"
com.orientechnologies.orient.core.exception.OSerializationException: Type 'null' cannot be serialized because is not part of registered entities. To fix this error register this class
	DB name="event-graph-dev"
	at com.orientechnologies.orient.object.enhancement.OObjectEntityEnhancer.getProxiedInstance(OObjectEntityEnhancer.java:82)
	at com.orientechnologies.orient.object.enhancement.OObjectEntityEnhancer.getProxiedInstance(OObjectEntityEnhancer.java:64)
	at com.orientechnologies.orient.object.db.OObjectDatabaseTx.getUserObjectByRecord(OObjectDatabaseTx.java:773)
	at com.orientechnologies.orient.object.db.ODatabasePojoAbstract.getUserObjectByRecord(ODatabasePojoAbstract.java:383)
	at com.orientechnologies.orient.object.db.OObjectLazyIterator.next(OObjectLazyIterator.java:88)
	at com.orientechnologies.orient.object.db.OObjectLazyIterator.next(OObjectLazyIterator.java:64)

The document class is anonymous and embedded which should be supported correct according to your data types documentation correct? The document is created from the 
new ODocument.fromJSON(myJsonString)

## Steps to reproduce  
See cases above.

**Comment by tglman** [comment]
Hi @dgilling,

Did you find a solution ?

Regards
