### ISSUE TITLE
Unexpected OTokenSecurityException 

### ISSUE THREAD

**Issue by sreznick** [orientechnologies/orientdb#8159]
### Java Version: openjdk version "1.8.0_151"
(accordingly with java -v output) 

## Expected behavior  
Normal query execution

## Actual behavior  
OTokenSecurityException thrown

## Steps to reproduce  
I'm not sure it is easily reporducible in any environment. So I just describe what I see.

We are develooing application relying on OrientDb. 
It starts to work in expected way. However at some moment (it could take few hours or day but it happens regularly) upon call to ODatabase.query() method some kind of exception is thrown.

Stack trace looks like following:

 threw exception [Request processing failed; nested exception is com.orientechnologies.orient.enterprise.channel.binary.OTokenSecurityException: missing session and token] with root cause
com.orientechnologies.orient.enterprise.channel.binary.OTokenSecurityException: missing session and token
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at com.orientechnologies.orient.client.binary.OChannelBinaryAsynchClient.throwSerializedException(OChannelBinaryAsynchClient.java:318)
        at com.orientechnologies.orient.client.binary.OChannelBinaryAsynchClient.handleStatus(OChannelBinaryAsynchClient.java:275)
        at com.orientechnologies.orient.client.binary.OChannelBinaryAsynchClient.beginResponse(OChannelBinaryAsynchClient.java:191)
        at com.orientechnologies.orient.client.binary.OChannelBinaryAsynchClient.beginResponse(OChannelBinaryAsynchClient.java:153)
        at com.orientechnologies.orient.client.remote.OStorageRemote.beginResponse(OStorageRemote.java:1766)
        at com.orientechnologies.orient.client.remote.OStorageRemote.lambda$networkOperationRetryTimeout$2(OStorageRemote.java:226)
        at com.orientechnologies.orient.client.remote.OStorageRemote.baseNetworkOperation(OStorageRemote.java:284)
        at com.orientechnologies.orient.client.remote.OStorageRemote.networkOperationRetryTimeout(OStorageRemote.java:214)
        at com.orientechnologies.orient.client.remote.OStorageRemote.networkOperation(OStorageRemote.java:243)
        at com.orientechnologies.orient.client.remote.OStorageRemote.query(OStorageRemote.java:860)
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentRemote.query(ODatabaseDocumentRemote.java:345)

It looks like problem happens on server side and exception is passed to client in serialized form.

Could you please kindly explain what could be reason to this. Shoud I tune something ?

Thanks,
Sergey Reznick

**Comment by sreznick** [comment]
As soon as it happens first time it repeats in stable way until application is restarted.

**Comment by maggiolo00** [comment]
Hi @sreznick 

thanks for reporting this. I was able to reproduce this and I've just pushed a fix

**Comment by maggiolo00** [comment]
@sreznick 
I will be available in the next release

**Comment by sreznick** [comment]
Thank you very much

**Comment by liyangzhou** [comment]
this issue had fixed? which version?
