### ISSUE TITLE
thread blocked on OClosableLinkedContainer.logRemoved

### ISSUE THREAD

**Issue by jamieb22** [orientechnologies/orientdb#8168]
## Expected behavior  
 
No blockage

## Actual behavior  

rvice-3 - priority:5 - threadId:0x0000000005014800 - nativeId:0x2371 - state:BLOCKED
stackTrace:
java.lang.Thread.State: BLOCKED (on object monitor)
at com.orientechnologies.common.collection.closabledictionary.OClosableLinkedContainer.logRemoved(OClosableLinkedContainer.java:606)
at com.orientechnologies.common.collection.closabledictionary.OClosableLinkedContainer.remove(OClosableLinkedContainer.java:267)
at com.orientechnologies.orient.core.storage.cache.local.OWOWCache.close(OWOWCache.java:1058)
at com.orientechnologies.orient.core.storage.cache.local.twoq.O2QCache.closeStorage(O2QCache.java:622)
at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.doClose(OAbstractPaginatedStorage.java:4441)
at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.close(OAbstractPaginatedStorage.java:580)
at ..
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
at java.lang.Thread.run(Thread.java:745)

## Steps to reproduce  
<add here>

**Comment by laa** [comment]
@jamieb22 do you have deadlock or thread is blocked on object monitor?

**Comment by jamieb22** [comment]
[catalina.zip](https://github.com/orientechnologies/orientdb/files/1838200/catalina.zip)
Andrey
I think its blocked on an object monitor. Please do me a favour download the attached zip and load into http://fastthread.io/. You can examine all Orient DB stacks.

**Comment by laa** [comment]
Hi @jamieb22 , if you look at this method you will see that there are no any locks here https://github.com/orientechnologies/orientdb/blob/2.2.x/core/src/main/java/com/orientechnologies/common/collection/closabledictionary/OClosableLinkedContainer.java#L605 . So most likely thread is blocked in save point by GC. Could you elaborate more why do you think there is a problem? Threads always are blocked periodically.

**Comment by jamieb22** [comment]
Thank you for analyzing. Sorry to disturb.
