### ISSUE TITLE
OCommandSQLParsingException when combining backslash and semicolon in batch mode

### ISSUE THREAD

**Issue by k-sok** [orientechnologies/orientdb#8178]
## Expected behavior  

Vertex should be created in batch mode

## Actual behavior  

```
com.orientechnologies.orient.core.sql.OCommandSQLParsingException: Error parsing query: CREATE VERTEX test SET prop1 = " \\", prop2 = "
        DB name="test"
        at com.orientechnologies.orient.core.sql.parser.OStatementCache.throwParsingException(OStatementCache.java:150)
        at com.orientechnologies.orient.core.sql.parser.OStatementCache.parse(OStatementCache.java:140)
        at com.orientechnologies.orient.core.sql.parser.OStatementCache.get(OStatementCache.java:88)
        at com.orientechnologies.orient.core.sql.parser.OStatementCache.get(OStatementCache.java:70)
        at com.orientechnologies.orient.core.sql.OCommandExecutorSQLAbstract.preParse(OCommandExecutorSQLAbstract.java:235)
        at com.orientechnologies.orient.graph.sql.OCommandExecutorSQLCreateVertex.parse(OCommandExecutorSQLCreateVertex.java:60)
        at com.orientechnologies.orient.graph.sql.OCommandExecutorSQLCreateVertex.parse(OCommandExecutorSQLCreateVertex.java:46)
        at com.orientechnologies.orient.core.sql.OCommandExecutorSQLDelegate.parse(OCommandExecutorSQLDelegate.java:53)
        at com.orientechnologies.orient.core.sql.OCommandExecutorSQLDelegate.parse(OCommandExecutorSQLDelegate.java:34)
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.command(OAbstractPaginatedStorage.java:3319)
        at com.orientechnologies.orient.core.command.OCommandRequestTextAbstract.execute(OCommandRequestTextAbstract.java:69)
        at com.orientechnologies.orient.core.command.script.OCommandExecutorScript.executeCommand(OCommandExecutorScript.java:519)
        at com.orientechnologies.orient.core.command.script.OCommandExecutorScript.executeSQLScript(OCommandExecutorScript.java:383)
        at com.orientechnologies.orient.core.command.script.OCommandExecutorScript.executeSQL(OCommandExecutorScript.java:229)
        at com.orientechnologies.orient.core.command.script.OCommandExecutorScript.executeInContext(OCommandExecutorScript.java:105)
        at com.orientechnologies.orient.core.command.script.OCommandExecutorScript.execute(OCommandExecutorScript.java:89)
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.executeCommand(OAbstractPaginatedStorage.java:3417)
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.command(OAbstractPaginatedStorage.java:3335)
        at com.orientechnologies.orient.core.command.OCommandRequestTextAbstract.execute(OCommandRequestTextAbstract.java:69)
        at com.orientechnologies.orient.server.network.protocol.http.command.post.OServerCommandPostBatch.execute(OServerCommandPostBatch.java:196)
        at com.orientechnologies.orient.server.network.protocol.http.ONetworkProtocolHttpAbstract.service(ONetworkProtocolHttpAbstract.java:173)
        at com.orientechnologies.orient.server.network.protocol.http.ONetworkProtocolHttpAbstract.execute(ONetworkProtocolHttpAbstract.java:629)
        at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:82)
```

## Steps to reproduce  

```
create class test extends V
create property test.prop1 STRING
create property test.prop2 STRING
create vertex test set prop1="\\", prop2=";"
```

The create vertex command works fine in command mode but not in batch mode. However, the following commands work in batch mode, too:

add a space after backslash
`create vertex test set prop1="\\ ", prop2=";" `

replace semicolon by something else
`create vertex test set prop1="\\", prop2="xyz" `

change order of properties
`create vertex test set  prop2=";", prop1="\\"`

Have also tested with version 2.2.24.  It doesn't work either but a different error is issued:

`com.orientechnologies.orient.core.sql.parser.TokenMgrError: Lexical error at`

**Comment by k-sok** [comment]
Can anybody reproduce this?
