### ISSUE TITLE
Unable to delete corrupted record using console/studio

### ISSUE THREAD

**Issue by bipulkarnani** [orientechnologies/orientdb#8188]
## Expected behavior  
Delete corrupted record as shown in the log:

```Caused by: com.orientechnologies.orient.core.exception.OStorageException: Cannot route read record operation for #56:527 to the distributed node
        DB name="paysense"
        at com.orientechnologies.orient.server.distributed.impl.ODistributedStorage.handleDistributedException(ODistributedStorage.java:1992)
        at com.orientechnologies.orient.server.distributed.impl.ODistributedStorage.readRecord(ODistributedStorage.java:797)
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx$SimpleRecordReader.readRecord(ODatabaseDocumentTx.java:3366)
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.executeReadRecord(ODatabaseDocumentTx.java:2017)
        ... 42 more
Caused by: java.lang.ArrayIndexOutOfBoundsException
        at com.orientechnologies.orient.core.compression.impl.ONothingCompression.uncompress(ONothingCompression.java:49)
        at com.orientechnologies.orient.core.storage.impl.local.paginated.OPaginatedCluster.readRecordBuffer(OPaginatedCluster.java:716)
        at com.orientechnologies.orient.core.storage.impl.local.paginated.OPaginatedCluster.readRecord(OPaginatedCluster.java:667)
        at com.orientechnologies.orient.core.storage.impl.local.paginated.OPaginatedCluster.readRecord(OPaginatedCluster.java:646)
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.doReadRecord(OAbstractPaginatedStorage.java:3980)
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.readRecord(OAbstractPaginatedStorage.java:3595)
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.readRecord(OAbstractPaginatedStorage.java:1250)
        at com.orientechnologies.orient.server.distributed.impl.ODistributedStorage$6.call(ODistributedStorage.java:765)
        at com.orientechnologies.orient.core.db.OScenarioThreadLocal.executeAsDistributed(OScenarioThreadLocal.java:70)
        at com.orientechnologies.orient.server.distributed.impl.ODistributedStorage.readRecord(ODistributedStorage.java:762)
        ... 44 more
``` 

## Actual behavior  
But delete command fails with `java.lang.ArrayIndexOutOfBoundsException` if run from console/studio.

## Steps to reproduce  
Somehow few records got corrupted and now we are trying to delete those records but all our subsequent queries failing if one query involves those corrupted record.

**Comment by laa** [comment]
Hi @bipulkarnani . For now, you have two options. You can make export/import of the database. That should fix your problem. But I do suggest to switch to the latest 2.2.x version because you will have this issue again, or you could wait until I will add the ability to isolate broken pages in `repair database`, but in such case, you have to switch to the latest 2.2.x anyway.

**Comment by bipulkarnani** [comment]
Hi @laa ,

We tried import/export and it was taking in couple of days just to export the data. Hence we decided to switch to the latest version (2.2.33) and load the entire data from scratch through ETL.

Thanks,
Bipul.

**Comment by laa** [comment]
Well, I suppose we can close it then.
