### ISSUE TITLE
OrientDB 2.2.33 - ORecordDuplicatedException during vertex creation with remote DB

### ISSUE THREAD

**Issue by valenpo** [orientechnologies/orientdb#8189]
## Expected behavior  
Adding vertexes should be complete fine. But working only for embedded and memory DB's. 

## Actual behavior  
ORecordDuplicatedException during vertex creation with remote: DB
```
com.orientechnologies.orient.core.storage.ORecordDuplicatedException: Cannot index record User: found duplicated key 'null' in index 'testIndex' previously assigned to the record #25:0
	DB name="tinkerpop"
	DB name="tinkerpop"
 INDEX=testIndex RID=#25:0
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.orientechnologies.orient.client.binary.OChannelBinaryAsynchClient.throwSerializedException(OChannelBinaryAsynchClient.java:449)
	at com.orientechnologies.orient.client.binary.OChannelBinaryAsynchClient.handleStatus(OChannelBinaryAsynchClient.java:400)
	at com.orientechnologies.orient.client.binary.OChannelBinaryAsynchClient.beginResponse(OChannelBinaryAsynchClient.java:283)
	at com.orientechnologies.orient.client.binary.OChannelBinaryAsynchClient.beginResponse(OChannelBinaryAsynchClient.java:167)
	at com.orientechnologies.orient.client.remote.OStorageRemote.beginResponse(OStorageRemote.java:2347)
	at com.orientechnologies.orient.client.remote.OStorageRemote$6.execute(OStorageRemote.java:576)
	at com.orientechnologies.orient.client.remote.OStorageRemote$6.execute(OStorageRemote.java:570)
	at com.orientechnologies.orient.client.remote.OStorageRemote$1.execute(OStorageRemote.java:168)
	at com.orientechnologies.orient.client.remote.OStorageRemote.baseNetworkOperation(OStorageRemote.java:245)
	at com.orientechnologies.orient.client.remote.OStorageRemote.asyncNetworkOperation(OStorageRemote.java:160)
	at com.orientechnologies.orient.client.remote.OStorageRemote.createRecord(OStorageRemote.java:556)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.executeSaveRecord(ODatabaseDocumentTx.java:2216)
	at com.orientechnologies.orient.core.tx.OTransactionNoTx.saveNew(OTransactionNoTx.java:241)
	at com.orientechnologies.orient.core.tx.OTransactionNoTx.saveRecord(OTransactionNoTx.java:171)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.save(ODatabaseDocumentTx.java:2775)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.save(ODatabaseDocumentTx.java:103)
	at com.orientechnologies.orient.core.record.impl.ODocument.save(ODocument.java:1805)
	at com.orientechnologies.orient.core.record.impl.ODocument.save(ODocument.java:1796)
	at com.tinkerpop.blueprints.impls.orient.OrientElement.save(OrientElement.java:333)
	at com.tinkerpop.blueprints.impls.orient.OrientElement.save(OrientElement.java:315)
	at com.tinkerpop.blueprints.impls.orient.OrientBaseGraph.addVertex(OrientBaseGraph.java:520)
	at com.tinkerpop.blueprints.impls.orient.OrientBaseGraph.addVertex(OrientBaseGraph.java:451)
	at com.stimulus.archiva.database.blueprints.BluePrintDatabaseTest.testIndexConflict(BluePrintDatabaseTest.java:60)
```

## Steps to reproduce  
- start orientdb-community-2.2.33
- run test code.

```
package com.stimulus.archiva.database.blueprints;

import com.orientechnologies.orient.client.db.ODatabaseHelper;
import com.orientechnologies.orient.core.index.OIndex;
import com.orientechnologies.orient.core.metadata.schema.OClass;
import com.orientechnologies.orient.core.metadata.schema.OType;
import com.stimulus.archiva.database.ConnectionSettings;
import com.stimulus.archiva.database.DatabaseMock;
import com.stimulus.archiva.domain.Application;
import com.stimulus.archiva.domain.Database;
import com.stimulus.archiva.domain.database.TreeItem;
import com.tinkerpop.blueprints.impls.orient.OrientGraph;
import com.tinkerpop.blueprints.impls.orient.OrientGraphFactory;
import com.tinkerpop.blueprints.impls.orient.OrientGraphNoTx;
import com.tinkerpop.blueprints.impls.orient.OrientVertexType;
import org.junit.Assert;
import org.junit.FixMethodOrder;
import org.junit.Ignore;
import org.junit.Test;
import org.junit.runners.MethodSorters;

import java.io.IOException;

import static org.mockito.Mockito.when;

/**
 * Created by Valentin Popov popov@mailarchiva.ru on 27/03/2018.
 */
@FixMethodOrder(MethodSorters.NAME_ASCENDING)
public class BluePrintDatabaseTest {

    private static final String domain = "@domain.com";

    @Test
    public void testIndexConflict() throws IOException {
        String[] dbURIs = {"memory:tinkerpop", "remote:localhost/tinkerpop"};

        for (String dbURI : dbURIs) {
            if (dbURI.startsWith("remote")) {
                System.setProperty("ORIENTDB_ROOT_PASSWORD", "admin");
                ODatabaseHelper.createDatabase(null, dbURI);
            }

            OrientGraphFactory factory = new OrientGraphFactory(dbURI);
            OrientGraphNoTx tx = factory.getNoTx();
            try {
                String name = "User";
                OrientVertexType v = tx.createVertexType(name, "V");
                v.createProperty("someField", OType.STRING);
                OIndex<?> index = v.createIndex("testIndex", OClass.INDEX_TYPE.UNIQUE, "someField");
                index.getDefinition().setNullValuesIgnored(true);
            } finally {
                tx.shutdown();
            }

            // Add initial vertex
            OrientGraphNoTx noTx = factory.getNoTx();
            try {
                noTx.addVertex("class:User");
                noTx.addVertex("class:User");
            } finally {
                noTx.shutdown();
            }

            System.out.println("success " + dbURI); factory.close();

        }
    }
}
```

**Comment by valenpo** [comment]
any news about bug fix?

**Comment by tglman** [comment]
Hi @valenpo.


The reason of your problem is that :`index.getDefinition().setNullValuesIgnored(true);`  is not propagate in remote.

please use instead:

```
v.createIndex("test", OClass.INDEX_TYPE.UNIQUE.toString(), null, new ODocument().fields("ignoreNullValues", true), new String[]{"someField"});
```

Regards
