### ISSUE TITLE
com.orientechnologies.orient.core.exception.OSerializationException: Found null entry in ridbag with rid=#39:-2

### ISSUE THREAD

**Issue by valenpo** [orientechnologies/orientdb#8203]
## Expected behavior  
<add here>  

## Actual behavior  

```
com.orientechnologies.orient.core.exception.OSerializationException: Found null entry in ridbag with rid=#39:-2
	DB name="tinkerpop"
	at com.orientechnologies.orient.core.db.record.ridbag.embedded.OEmbeddedRidBag.serialize(OEmbeddedRidBag.java:423)
	at com.orientechnologies.orient.core.db.record.ridbag.ORidBag.toStream(ORidBag.java:273)
	at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinaryV0.serializeValue(ORecordSerializerBinaryV0.java:763)
	at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinaryV0.serialize(ORecordSerializerBinaryV0.java:385)
	at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinary.toStream(ORecordSerializerBinary.java:99)
	at com.orientechnologies.orient.core.record.impl.ODocument.toStream(ODocument.java:2381)
	at com.orientechnologies.orient.core.record.impl.ODocument.toStream(ODocument.java:664)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.commitEntry(OAbstractPaginatedStorage.java:4522)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.commit(OAbstractPaginatedStorage.java:1815)
	at com.orientechnologies.orient.core.tx.OTransactionOptimistic.doCommit(OTransactionOptimistic.java:541)
	at com.orientechnologies.orient.core.tx.OTransactionOptimistic.commit(OTransactionOptimistic.java:99)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.commit(ODatabaseDocumentTx.java:2915)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.commit(ODatabaseDocumentTx.java:2877)
	at com.tinkerpop.blueprints.impls.orient.OrientBaseGraph.shutdown(OrientBaseGraph.java:1093)
	at com.tinkerpop.blueprints.impls.orient.OrientBaseGraph.shutdown(OrientBaseGraph.java:1079)
	at com.tinkerpop.blueprints.impls.orient.OrientBaseGraph.shutdown(OrientBaseGraph.java:1072)
```  

## Steps to reproduce  

```
package com.stimulus.archiva.database.blueprints;

import com.google.common.collect.Iterables;
import com.google.common.util.concurrent.MoreExecutors;
import com.orientechnologies.orient.client.db.ODatabaseHelper;
import com.orientechnologies.orient.core.index.OIndex;
import com.orientechnologies.orient.core.metadata.schema.OClass;
import com.orientechnologies.orient.core.metadata.schema.OType;
import com.stimulus.archiva.database.ConnectionSettings;
import com.stimulus.archiva.database.DatabaseMock;
import com.stimulus.archiva.domain.Application;
import com.stimulus.archiva.domain.Database;
import com.stimulus.archiva.domain.database.TreeItem;
import com.tinkerpop.blueprints.Graph;
import com.tinkerpop.blueprints.Vertex;
import com.tinkerpop.blueprints.impls.orient.OrientGraph;
import com.tinkerpop.blueprints.impls.orient.OrientGraphFactory;
import com.tinkerpop.blueprints.impls.orient.OrientGraphNoTx;
import com.tinkerpop.blueprints.impls.orient.OrientVertexType;
import org.junit.Assert;
import org.junit.FixMethodOrder;
import org.junit.Ignore;
import org.junit.Test;
import org.junit.runners.MethodSorters;

import java.io.IOException;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;
import java.util.concurrent.TimeUnit;

import static org.mockito.Mockito.when;

/**
 * Created by Valentin Popov popov@mailarchiva.ru on 27/03/2018.
 */
@FixMethodOrder(MethodSorters.NAME_ASCENDING)
public class BluePrintDatabaseTest {

    private static final String domain = "@domain.com";
    OrientGraphFactory factory = new OrientGraphFactory("memory:tinkerpop");
    String name = "User";
    String className = "class:" + name;

    @Test
    public void multipleConnections() {
        factory.setupPool(0, 16);

        String userName = "userName";

        OrientGraphNoTx tx = factory.getNoTx();
        try {
            OrientVertexType v = tx.createVertexType(name, "V");
            v.createProperty(userName, OType.STRING);
            OIndex<?> index = v.createIndex(userName, OClass.INDEX_TYPE.UNIQUE, userName);
            index.getDefinition().setNullValuesIgnored(true);
            tx.createEdgeType("friends", "E");
        } finally {
            tx.shutdown();
        }

        Vertex root;
        Graph graph = factory.getTx();
        try {
            root = graph.addVertex(className);
            root.setProperty(userName, "root");
        } finally {
            graph.shutdown();
        }

        ExecutorService executorService = Executors.newFixedThreadPool(64);

        for (int i = 0; i < 100; i++) {
            int friendID = i;
            executorService.submit(() -> {
                Graph graph1 = factory.getTx();
                try {
                    String friendName = "friend" + friendID;
                    Vertex friend = getOrInsert(userName, friendName);
                    graph1.addEdge("root" + friendName, root, friend, "friends");
                } catch (Exception e) {
                    e.printStackTrace();
                } finally {
                    graph1.shutdown();
                }
            });
        }

        MoreExecutors.shutdownAndAwaitTermination(executorService, 1, TimeUnit.MINUTES);
    }

    private Vertex getOrInsert(String key, String value) {
        Graph graph = factory.getTx();
        try {
            Vertex friend = Iterables.getFirst(graph.getVertices(key, value), null);
            if (friend == null)
                friend = graph.addVertex(className);
            friend.setProperty(key, value);
            return friend;
        } finally {
            graph.shutdown();
        }
    }
}
```

**Comment by tglman** [comment]
Hi @valenpo,

I fixed a couple of things in your test case now has no problems:
```
import com.google.common.collect.Iterables;
import com.google.common.util.concurrent.MoreExecutors;
import com.orientechnologies.orient.core.exception.OConcurrentModificationException;
import com.orientechnologies.orient.core.index.OIndex;
import com.orientechnologies.orient.core.metadata.schema.OClass;
import com.orientechnologies.orient.core.metadata.schema.OType;
import com.tinkerpop.blueprints.Graph;
import com.tinkerpop.blueprints.Vertex;
import com.tinkerpop.blueprints.impls.orient.OrientGraph;
import com.tinkerpop.blueprints.impls.orient.OrientGraphFactory;
import com.tinkerpop.blueprints.impls.orient.OrientGraphNoTx;
import com.tinkerpop.blueprints.impls.orient.OrientVertexType;
import org.junit.FixMethodOrder;
import org.junit.Test;
import org.junit.runners.MethodSorters;

import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;
import java.util.concurrent.TimeUnit;

/**
 * Created by Valentin Popov popov@mailarchiva.ru on 27/03/2018.
 */
@FixMethodOrder(MethodSorters.NAME_ASCENDING)
public class BluePrintDatabaseTest {

  private static final String domain = "@domain.com";
  OrientGraphFactory factory   = new OrientGraphFactory("memory:tinkerpop");
  String             name      = "User";
  String             className = "class:" + name;

  @Test
  public void multipleConnections() {
    factory.setupPool(0, 16);

    String userName = "userName";

    OrientGraphNoTx tx = factory.getNoTx();
    try {
      OrientVertexType v = tx.createVertexType(name, "V");
      v.createProperty(userName, OType.STRING);
      OIndex<?> index = v.createIndex(userName, OClass.INDEX_TYPE.UNIQUE, userName);
      index.getDefinition().setNullValuesIgnored(true);
      tx.createEdgeType("friends", "E");
    } finally {
      tx.shutdown();
    }

    Object rootId;
    Vertex root;
    Graph graph = factory.getTx();
    try {
      root = graph.addVertex(className);
      root.setProperty(userName, "root");
    } finally {
      graph.shutdown();
    }
    rootId = root.getId();

    ExecutorService executorService = Executors.newFixedThreadPool(2);

    for (int i = 0; i < 100; i++) {
      int friendID = i;
      executorService.submit(() -> {
        Graph internal = factory.getTx();
        try {
          for (int r = 0; r < 10; r++) {
            try {
              Vertex rootVertex = internal.getVertex(rootId);

              String friendName = "friend" + friendID;
              Vertex friend = getOrInsert(internal, userName, friendName);
              internal.addEdge("root" + friendName, rootVertex, friend, "friends");

              ((OrientGraph) internal).commit();
              return;
            } catch (OConcurrentModificationException e) {
              //retry
            }
          }
        } catch (Exception e) {
          e.printStackTrace();
        } finally {
          internal.shutdown();
        }

      });
    }

    MoreExecutors.shutdownAndAwaitTermination(executorService, 1, TimeUnit.MINUTES);
  }

  private Vertex getOrInsert(Graph graph, String key, String value) {
    Vertex friend = Iterables.getFirst(graph.getVertices(key, value), null);
    if (friend == null)
      friend = graph.addVertex(className);
    friend.setProperty(key, value);
    return friend;
  }
}
```

The important thing is not to share instances of OVertex across threads and not play with multiple nested sessions.

**Comment by valenpo** [comment]
Hi @tglman, 

So if I right understand, in each transaction I should take Element from DB? What about speed?
If yes, maybe it is possible add such info to documentation? 

Thanks!
