### ISSUE TITLE
com.orientechnologies.orient.core.exception.OStorageException: Error during transaction commit

### ISSUE THREAD

**Issue by valenpo** [orientechnologies/orientdb#8204]
## Expected behavior  
<add here>  

## Actual behavior  
```
Apr 10, 2018 3:05:43 PM com.orientechnologies.common.log.OLogManager log
SEVERE: $ANSI{green {db=tinkerpop}} Error during context close for db null
com.orientechnologies.orient.core.exception.OStorageException: Error during transaction commit
	DB name="tinkerpop"
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.makeRollback(OAbstractPaginatedStorage.java:2810)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.commit(OAbstractPaginatedStorage.java:1830)
	at com.orientechnologies.orient.core.tx.OTransactionOptimistic.doCommit(OTransactionOptimistic.java:541)
	at com.orientechnologies.orient.core.tx.OTransactionOptimistic.commit(OTransactionOptimistic.java:99)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.commit(ODatabaseDocumentTx.java:2915)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.commit(ODatabaseDocumentTx.java:2877)
	at com.tinkerpop.blueprints.impls.orient.OrientBaseGraph.shutdown(OrientBaseGraph.java:1093)
	at com.tinkerpop.blueprints.impls.orient.OrientBaseGraph.shutdown(OrientBaseGraph.java:1079)
	at com.tinkerpop.blueprints.impls.orient.OrientBaseGraph.shutdown(OrientBaseGraph.java:1072)
	at com.stimulus.archiva.database.blueprints.BluePrintDatabaseTest.lambda$multipleConnections$0(BluePrintDatabaseTest.java:83)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ArrayIndexOutOfBoundsException: 2
	at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinaryV0.serialize(ORecordSerializerBinaryV0.java:368)
	at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinary.toStream(ORecordSerializerBinary.java:99)
	at com.orientechnologies.orient.core.record.impl.ODocument.toStream(ODocument.java:2381)
	at com.orientechnologies.orient.core.record.impl.ODocument.toStream(ODocument.java:664)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.commitEntry(OAbstractPaginatedStorage.java:4522)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.commit(OAbstractPaginatedStorage.java:1815)
``` 

## Steps to reproduce  
```
package com.stimulus.archiva.database.blueprints;

import com.google.common.collect.Iterables;
import com.google.common.util.concurrent.MoreExecutors;
import com.orientechnologies.orient.client.db.ODatabaseHelper;
import com.orientechnologies.orient.core.index.OIndex;
import com.orientechnologies.orient.core.metadata.schema.OClass;
import com.orientechnologies.orient.core.metadata.schema.OType;
import com.stimulus.archiva.database.ConnectionSettings;
import com.stimulus.archiva.database.DatabaseMock;
import com.stimulus.archiva.domain.Application;
import com.stimulus.archiva.domain.Database;
import com.stimulus.archiva.domain.database.TreeItem;
import com.tinkerpop.blueprints.Graph;
import com.tinkerpop.blueprints.Vertex;
import com.tinkerpop.blueprints.impls.orient.OrientGraph;
import com.tinkerpop.blueprints.impls.orient.OrientGraphFactory;
import com.tinkerpop.blueprints.impls.orient.OrientGraphNoTx;
import com.tinkerpop.blueprints.impls.orient.OrientVertexType;
import org.junit.Assert;
import org.junit.FixMethodOrder;
import org.junit.Ignore;
import org.junit.Test;
import org.junit.runners.MethodSorters;

import java.io.IOException;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;
import java.util.concurrent.TimeUnit;

import static org.mockito.Mockito.when;

/**
 * Created by Valentin Popov popov@mailarchiva.ru on 27/03/2018.
 */
@FixMethodOrder(MethodSorters.NAME_ASCENDING)
public class BluePrintDatabaseTest {

    private static final String domain = "@domain.com";
    OrientGraphFactory factory = new OrientGraphFactory("memory:tinkerpop");
    String name = "User";
    String className = "class:" + name;

    @Test
    public void multipleConnections() {
        factory.setupPool(0, 16);

        String userName = "userName";

        OrientGraphNoTx tx = factory.getNoTx();
        try {
            OrientVertexType v = tx.createVertexType(name, "V");
            v.createProperty(userName, OType.STRING);
            OIndex<?> index = v.createIndex(userName, OClass.INDEX_TYPE.UNIQUE, userName);
            index.getDefinition().setNullValuesIgnored(true);
            tx.createEdgeType("friends", "E");
        } finally {
            tx.shutdown();
        }

        Vertex root;
        Graph graph = factory.getTx();
        try {
            root = graph.addVertex(className);
            root.setProperty(userName, "root");
        } finally {
            graph.shutdown();
        }

        ExecutorService executorService = Executors.newFixedThreadPool(2);

        for (int i = 0; i < 100; i++) {
            int friendID = i;
            executorService.submit(() -> {
                Graph internal = factory.getTx();
                try {
                    String friendName = "friend" + friendID;
                    Vertex friend = getOrInsert(userName, friendName);
                    internal.addEdge("root" + friendName, root, friend, "friends");
                } catch (Exception e) {
                    e.printStackTrace();
                } finally {
                    internal.shutdown();
                }
            });
        }

        MoreExecutors.shutdownAndAwaitTermination(executorService, 1, TimeUnit.MINUTES);
    }

    private Vertex getOrInsert(String key, String value) {
        Graph graph = factory.getTx();
        try {
            Vertex friend = Iterables.getFirst(graph.getVertices(key, value), null);
            if (friend == null)
                friend = graph.addVertex(className);
            friend.setProperty(key, value);
            return friend;
        } finally {
            graph.shutdown();
        }
    }
}
```

**Comment by valenpo** [comment]
@tglman thanks. That helps.
