### ISSUE TITLE
"SocketTimeoutException: Read timed out" during creating/rebuilding index on large database

### ISSUE THREAD

**Issue by jedrzej999** [orientechnologies/orientdb#8208]
## Expected behavior  
Creating index...
Created index successfully in 0.702000 sec(s).
Index created successfully

## Actual behavior  
Creating index...
Error: com.orientechnologies.common.io.OIOException: Read timed out
Error: java.net.SocketTimeoutException: Read timed out

(After a while index is created anyway)

## Steps to reproduce
1. Create graph database
2. Load 10 milion records
3. Create index on two fields in one class (eg. CREATE INDEX Person.givenName_familyName ON Person(givenName, familyName) NOTUNIQUE)
4. Get the error:
Error: com.orientechnologies.common.io.OIOException: Read timed out
Error: java.net.SocketTimeoutException: Read timed out
5. After a while index is created anyway but not prompted, behaviour looks like an error

Settings
java -server -Xms30G -Xmx30G -Djna.nosys=true 
-XX:+HeapDumpOnOutOfMemoryError 
-Djava.awt.headless=true -Dfile.encoding=UTF8 
-Drhino.opt.level=9 -Denvironment.dumpCfgAtStartup=true 
-Djava.util.logging.manager=com.orientechnologies.common.log.ShutdownLogManager 
-Djava.util.logging.config.file=/opt/orientdb/config/orientdb-server-log.properties 
-Dorientdb.config.file=/opt/orientdb/config/orientdb-server-config.xml 
-Dorientdb.www.path=/opt/orientdb/www -Dorientdb.build.number=develop@rf833ecfdbc293875a429e9831d0ff6a467db076d

**Comment by luigidellaquila** [comment]
Hi @jedrzej999 

How are you creating the index? Are you doing it from Java API? Connecting from plocal or remote?

Thanks

Luigi

**Comment by jedrzej999** [comment]
Hi,
I am creating index via SQL statement in through console.sh

CREATE INDEX Person.givenName_familyName ON Person(givenName, familyName)
NOTUNIQUE

2018-04-12 11:53 GMT+02:00 luigidellaquila <notifications@github.com>:

**Comment by luigidellaquila** [comment]
Ok, thank you, I'll try to reproduce

Thanks

Luigi

**Comment by bommireddyharish** [comment]
Exception in thread "main" com.orientechnologies.common.io.OIOException: Read timed out
	at com.orientechnologies.orient.client.remote.OStorageRemote.baseNetworkOperation(OStorageRemote.java:327)
	at com.orientechnologies.orient.client.remote.OStorageRemote.networkOperationRetryTimeout(OStorageRemote.java:214)
	at com.orientechnologies.orient.client.remote.OStorageRemote.networkOperationNoRetry(OStorageRemote.java:239)
	at com.orientechnologies.orient.client.remote.OStorageRemote.execute(OStorageRemote.java:960)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentRemote.execute(ODatabaseDocumentRemote.java:425)
	at com.bt.srims.shared.framework.graph.execution.engine.GraphExecutionEngineImpl.executeGremlin(GraphExecutionEngineImpl.java:51)
	at com.bt.srims.shared.framework.graph.execution.engine.test.GremlinExecutionEngineTest.main(GremlinExecutionEngineTest.java:32)
Caused by: java.net.SocketTimeoutException: Read timed out
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.socketRead(Unknown Source)
	at java.net.SocketInputStream.read(Unknown Source)
	at java.net.SocketInputStream.read(Unknown Source)
	at java.io.BufferedInputStream.fill(Unknown Source)
	at java.io.BufferedInputStream.read(Unknown Source)
	at java.io.DataInputStream.readInt(Unknown Source)
	at com.orientechnologies.orient.enterprise.channel.binary.OChannelBinary.readBytes(OChannelBinary.java:159)
	at com.orientechnologies.orient.core.serialization.serializer.result.binary.OResultSerializerNetwork.fromStream(OResultSerializerNetwork.java:655)
	at com.orientechnologies.orient.client.remote.message.OMessageHelper.readProjection(OMessageHelper.java:503)
	at com.orientechnologies.orient.client.remote.message.OMessageHelper.readResult(OMessageHelper.java:471)
	at com.orientechnologies.orient.client.remote.message.OQueryResponse.read(OQueryResponse.java:73)
	at com.orientechnologies.orient.client.remote.OStorageRemote.lambda$networkOperationRetryTimeout$2(OStorageRemote.java:227)
	at com.orientechnologies.orient.client.remote.OStorageRemote.baseNetworkOperation(OStorageRemote.java:285)
	... 6 more


This thing i got when i am querying from db  query is big enough at the end of i am adding "map{it.get().values()}"
then i got it, If i am not using map{} it is working fine can u help me out with this.
Thanks.
