### ISSUE TITLE
Trying to create fulltext lucene index on n-properties throws exception

### ISSUE THREAD

**Issue by temilmg** [orientechnologies/orientdb#8209]
### OS: Linux  

Using the Orient Java api it is not possible to create fulltext lucene index on n-properties (a single property works fine)

## Expected behavior  
No exception

## Actual behavior  
The following exception is thrown:
```
com.orientechnologies.orient.core.index.OIndexException: Index with type FULLTEXT and algorithm LUCENE does not exist.
	DB name="tenant-danalim2"
	at com.orientechnologies.orient.core.index.OIndexes.getFactory(OIndexes.java:130)
	at com.orientechnologies.orient.core.index.OIndexDefinitionFactory.createMultipleFieldIndexDefinition(OIndexDefinitionFactory.java:93)
	at com.orientechnologies.orient.core.index.OIndexDefinitionFactory.createIndexDefinition(OIndexDefinitionFactory.java:70)
	at com.orientechnologies.orient.core.metadata.schema.OClassImpl.createIndex(OClassImpl.java:1897)

```

## Steps to reproduce  
(Code similar to the code in the documentation but adding an extra property)
```
OSchema schema = databaseDocumentTx.getMetadata().getSchema();
OClass oClass = schema.createClass("Foo");
oClass.createProperty("name", OType.STRING);
oClass.createIndex("City.name", "FULLTEXT", null, null, "LUCENE", new String[] { "name","surname"});
```

**Comment by maggiolo00** [comment]
Hi @temilmg 

are you using ODB as embedded?

Did you import the module `orientdb-lucene` ?

**Comment by temilmg** [comment]
I am using remote connection and i am only including orientdb-graphdb as i was under the impression that lucene had been added to this jar (seems to be for fulltext lucene on a single property)

Adding orientdb-lucene solves the problem!

Is everything supposed to be in orientdb-graphdb? If yes do you want me to leave this bug open as a reminder, or should i just close it?

**Comment by temilmg** [comment]
Thanks

**Comment by temilmg** [comment]
When i add the orientdb-lucene dependency i get the following error:
(if i remove orientdb-lucene then the error disappears)
```
	com.orientechnologies.orient.core.exception.ODatabaseException: Error on opening database 'remote:orientdb:2424/dana'
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.<init>(ODatabaseDocumentTx.java:193)
	at com.orientechnologies.orient.core.db.OPartitionedDatabasePool$DatabaseDocumentTxPooled.<init>(OPartitionedDatabasePool.java:428)
	at com.orientechnologies.orient.core.db.OPartitionedDatabasePool$DatabaseDocumentTxPooled.<init>(OPartitionedDatabasePool.java:424)
	at com.orientechnologies.orient.core.db.OPartitionedDatabasePool.initQueue(OPartitionedDatabasePool.java:358)
	at com.orientechnologies.orient.core.db.OPartitionedDatabasePool.<init>(OPartitionedDatabasePool.java:117)
	at com.tinkerpop.blueprints.impls.orient.OrientGraphFactory.<init>(OrientGraphFactory.java:174)
	at com.tinkerpop.blueprints.impls.orient.OrientGraphFactory.<init>(OrientGraphFactory.java:155)

	Caused by: com.orientechnologies.orient.core.exception.OConfigurationException: Error on opening database: the engine 'remote' was not found. URL was: remote:orientdb:2424/dana. Registered engines are: [memory, plocal]
		DB name="remote:orientdb:2424/dana"
		at com.orientechnologies.orient.core.Orient.loadStorage(Orient.java:519)
		at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.<init>(ODatabaseDocumentTx.java:173)
		... 46 more
```

**Comment by tglman** [comment]
Hi @temilmg,

This error means that you do not have in the dependencies the orientdb-client, I would suggest to double check if there is some conflict(maybe different versions) when you add that dependency.

Regards

**Comment by temilmg** [comment]
To begin with i only had orientdb-graphdb but then lucene index on n-properties didnt work

Then I added orientdb-lucene and it worked locally but when I created a fat jar for a docker deployment it threw the openening database exception above.

I made the following workaround (maybe there is a better maven way but i am far from an expert in maven):

Making an exclusion on orientdb-client in orientdb-lucene fixes the opening database error 

```
<dependency>
			<groupId>com.orientechnologies</groupId>
			<artifactId>orientdb-graphdb</artifactId>
			<version>2.2.32</version>
		</dependency>
		<dependency>
			<groupId>com.orientechnologies</groupId>
			<artifactId>orientdb-lucene</artifactId>
			<version>2.2.32</version>
			<exclusions>
				<exclusion>
					<groupId>com.orientechnologies</groupId>
					<artifactId>orientdb-client</artifactId>
				</exclusion>
			</exclusions>
		</dependency>	
```		    		


but still the indexing doesnt work. There is a class loader in OIndexes that is not loading the oLuceneIndexFactory so I had to manually register it first with the following code:

```
OLuceneIndexFactory oLuceneIndexFactory = new OLuceneIndexFactory();
OIndexes.registerFactory(oLuceneIndexFactory);
```

**Comment by maggiolo00** [comment]
Hi @temilmg 

if you are building a single jar you should use this

https://orientdb.com/docs/last/Tutorial-Installation.html#building-a-single-executable-jar-with-orientdb

Thanks

**Comment by temilmg** [comment]
Thanks I will have a look at that!
I think I can close this one now
