### ISSUE TITLE
Nullpointer exception at login on 3.0.0

### ISSUE THREAD

**Issue by 33Fraise33** [orientechnologies/orientdb#8218]
## Expected behavior  
logging in on the webpanel should be ok 

## Actual behavior  
loggin in works but throws an error in the console: 

```
Internal server error:

java.lang.NullPointerException
	at com.orientechnologies.orient.core.sql.parser.OSuffixIdentifier.execute(OSuffixIdentifier.java:76)
	at com.orientechnologies.orient.core.sql.parser.OSuffixIdentifier.execute(OSuffixIdentifier.java:196)
	at com.orientechnologies.orient.core.sql.parser.OModifier.execute(OModifier.java:93)
	at com.orientechnologies.orient.core.sql.parser.OBaseExpression.execute(OBaseExpression.java:125)
	at com.orientechnologies.orient.core.sql.parser.OExpression.execute(OExpression.java:109)
	at com.orientechnologies.orient.core.sql.parser.OBinaryCondition.evaluate(OBinaryCondition.java:44)
	at com.orientechnologies.orient.core.sql.parser.ONotBlock.evaluate(ONotBlock.java:45)
	at com.orientechnologies.orient.core.sql.parser.OAndBlock.evaluate(OAndBlock.java:48)
	at com.orientechnologies.orient.core.sql.parser.OOrBlock.evaluate(OOrBlock.java:50)
	at com.orientechnologies.orient.core.sql.parser.OWhereClause.matchesFilters(OWhereClause.java:50)
	at com.orientechnologies.orient.core.sql.executor.FilterStep$1.fetchNextItem(FilterStep.java:63)
	at com.orientechnologies.orient.core.sql.executor.FilterStep$1.hasNext(FilterStep.java:83)
	at com.orientechnologies.orient.core.sql.executor.ProjectionCalculationStep$1.hasNext(ProjectionCalculationStep.java:33)
	at com.orientechnologies.orient.core.sql.parser.OLocalResultSet.fetchNext(OLocalResultSet.java:36)
	at com.orientechnologies.orient.core.sql.parser.OLocalResultSet.<init>(OLocalResultSet.java:29)
	at com.orientechnologies.orient.core.sql.parser.OSelectStatement.execute(OSelectStatement.java:281)
	at com.orientechnologies.orient.core.command.OSqlScriptExecutor.execute(OSqlScriptExecutor.java:44)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentEmbedded.execute(ODatabaseDocumentEmbedded.java:588)
	at com.orientechnologies.orient.server.network.protocol.http.command.post.OServerCommandPostCommand.executeStatement(OServerCommandPostCommand.java:174)
	at com.orientechnologies.tinkerpop.command.OServerCommandPostCommandGremlin.executeStatement(OServerCommandPostCommandGremlin.java:48)
	at com.orientechnologies.orient.server.network.protocol.http.command.post.OServerCommandPostCommand.execute(OServerCommandPostCommand.java:84)
	at com.orientechnologies.orient.server.network.protocol.http.command.post.OServerCommandPostCommandGraph.execute(OServerCommandPostCommandGraph.java:36)
	at com.orientechnologies.orient.server.network.protocol.http.ONetworkProtocolHttpAbstract.service(ONetworkProtocolHttpAbstract.java:172)
	at com.orientechnologies.orient.server.network.protocol.http.ONetworkProtocolHttpAbstract.execute(ONetworkProtocolHttpAbstract.java:633)
	at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:82)

```

## Steps to reproduce  
I'm not sure if I'm doing something wrong. I'm using the latest docker orient from this dockerfile: 
https://raw.githubusercontent.com/orientechnologies/orientdb-docker/master/3.0/x86_64/alpine/Dockerfile

I also imported our database with the command `IMPORT DATABASE`

**Comment by luigidellaquila** [comment]
Hi @33Fraise33 

I'm checking it now

Thanks

Luigi

**Comment by luigidellaquila** [comment]
Hi @33Fraise33 

I don't seem to be able to reproduce the problem... how did you build and launch the image?

Thanks

Luigi

**Comment by luigidellaquila** [comment]
And which database did you import?

Thanks

Luigi

**Comment by 33Fraise33** [comment]
Hello what I did to run this docker image: 

`sudo docker build -t orient3 https://raw.githubusercontent.com/orientechnologies/orientdb-docker/master/3.0/x86_64/alpine/Dockerfile`

run the container with ansible: 

```
- name: setup orient docker container
  docker_container:
    name: orientdb
    image: orient3
    command: "/orientdb/bin/server.sh"
    published_ports:
      - 2424:2424
      - 2480:2480
    network_mode: host
    volumes:
      - "/orientdb/config:/orientdb/config"
      - "/orientdb/databases:/orientdb/databases"
      - "/orientdb/backup:/orientdb/bin/backup"
    log_options:
      max-size: 200m
    env:
      ORIENTDB_ROOT_PASSWORD: "<password here>"
      ORIENTDB_NODE_NAME: "{{ ansible_hostname }}"
      ORIENTDB_OPTS_MEMORY: "-Xms20G -Xmx20G"
    state: started
```
my server config: 

```
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<orient-server>
    <handlers>
        <handler class="com.orientechnologies.tinkerpop.handler.OGraphServerHandler">
            <parameters>
                <parameter value="true" name="enabled"/>
                <parameter value="50" name="graph.pool.max"/>
            </parameters>
        </handler>
        <handler class="com.orientechnologies.orient.server.hazelcast.OHazelcastPlugin">
            <parameters>
                <parameter value="false" name="enabled"/>
                <parameter value="${ORIENTDB_HOME}/config/default-distributed-db-config.json" name="configuration.db.default"/>
                <parameter value="${ORIENTDB_HOME}/config/hazelcast.xml" name="configuration.hazelcast"/>
            </parameters>
        </handler>
        <handler class="com.orientechnologies.orient.server.handler.OJMXPlugin">
            <parameters>
                <parameter value="false" name="enabled"/>
                <parameter value="true" name="profilerManaged"/>
            </parameters>
        </handler>
        <handler class="com.orientechnologies.orient.server.handler.OAutomaticBackup">
            <parameters>
                <parameter value="false" name="enabled"/>
                <parameter value="${ORIENTDB_HOME}/config/automatic-backup.json" name="config"/>
            </parameters>
        </handler>
        <handler class="com.orientechnologies.orient.server.handler.OServerSideScriptInterpreter">
            <parameters>
                <parameter value="true" name="enabled"/>
                <parameter value="SQL" name="allowedLanguages"/>
            </parameters>
        </handler>
    </handlers>
    <network>
        <sockets>
            <socket implementation="com.orientechnologies.orient.server.network.OServerTLSSocketFactory" name="ssl">
                <parameters>
                    <parameter value="false" name="network.ssl.clientAuth"/>
                    <parameter value="config/cert/orientdb.ks" name="network.ssl.keyStore"/>
                    <parameter value="password" name="network.ssl.keyStorePassword"/>
                    <parameter value="config/cert/orientdb.ks" name="network.ssl.trustStore"/>
                    <parameter value="password" name="network.ssl.trustStorePassword"/>
                </parameters>
            </socket>
            <socket implementation="com.orientechnologies.orient.server.network.OServerTLSSocketFactory" name="https">
                <parameters>
                    <parameter value="false" name="network.ssl.clientAuth"/>
                    <parameter value="config/cert/orientdb.ks" name="network.ssl.keyStore"/>
                    <parameter value="password" name="network.ssl.keyStorePassword"/>
                    <parameter value="config/cert/orientdb.ks" name="network.ssl.trustStore"/>
                    <parameter value="password" name="network.ssl.trustStorePassword"/>
                </parameters>
            </socket>
        </sockets>
        <protocols>
            <protocol implementation="com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary" name="binary"/>
            <protocol implementation="com.orientechnologies.orient.server.network.protocol.http.ONetworkProtocolHttpDb" name="http"/>
        </protocols>
        <listeners>
            <listener protocol="binary" socket="default" port-range="2424-2430" ip-address="0.0.0.0"/>
            <listener protocol="http" socket="default" port-range="2480-2490" ip-address="0.0.0.0">
                <commands>
                    <command implementation="com.orientechnologies.orient.server.network.protocol.http.command.get.OServerCommandGetStaticContent" pattern="GET|www GET|studio/ GET| GET|*.htm GET|*.html GET|*.xml GET|*.jpeg GET|*.jpg GET|*.png GET|*.gif GET|*.js GET|*.css GET|*.swf GET|*.ico GET|*.txt GET|*.otf GET|*.pjs GET|*.svg GET|*.json GET|*.woff GET|*.woff2 GET|*.ttf GET|*.svgz" stateful="false">
                        <parameters>
                            <entry value="Cache-Control: no-cache, no-store, max-age=0, must-revalidate\r\nPragma: no-cache" name="http.cache:*.htm *.html"/>
                            <entry value="Cache-Control: max-age=120" name="http.cache:default"/>
                        </parameters>
                    </command>
                    <command implementation="com.orientechnologies.orient.server.network.protocol.http.command.get.OServerCommandGetGephi" pattern="GET|gephi/*" stateful="false"/>
                </commands>
                <parameters>
                    <parameter value="utf-8" name="network.http.charset"/>
                    <parameter value="true" name="network.http.jsonResponseError"/>
                </parameters>
            </listener>
        </listeners>
    </network>
    <storages/>
    <users>
    </users>
    <properties>
        <entry value="1" name="db.pool.min"/>
        <entry value="50" name="db.pool.max"/>
        <entry value="false" name="profiler.enabled"/>
    </properties>
</orient-server>

```

export the database through the webpanel of a 2.2.31 server. Startup the container, create the database you want to import and add a temporary admin user. When done shutdown the container.

Run: `sudo docker run --rm -it -v /orientdb/databases:/orientdb/databases -v /orientdb/backup:/orientdb/bin/backup orientdb:<version tag> /orientdb/bin/console.sh`
(backup is where my export is at)

run: `connect plocal:/orientdb/databases/kayzr <tempadminuser> <password>`
run: `import database /orientdb/bin/backup/<backupname>.gz`

Now when I log in I get this error.

**Comment by 33Fraise33** [comment]
Ok I think I have found the issue. I tried it out with the following server: http://central.maven.org/maven2/com/orientechnologies/orientdb-community/3.0.0/ (the zip version)

I started the server, created my database, added a user which exists in my backup as well (for example the user 'x' with admin rights). I shutdown orientdb, I run the console and connect plocal with my new db. I do a restore on the database and when done I start the server (no config changes at all). I log in as the user root, I remove the user 'x'. Now I log out and log in again as root and tada, there is the issue.

**Comment by luigidellaquila** [comment]
Thank you very much @33Fraise33, that's interesting.
It should be easy to reproduce, I'll let you know asap

Thanks

Luigi

**Comment by 33Fraise33** [comment]
what might be interesting is that I disabled the default user creation. So I had to make an admin user to import my database as root is not accepted when trying to connect plocal to my newly created db.

**Comment by 33Fraise33** [comment]
Ok I have some more information which is actually different from my previous statement: 

I started the server, created my database, added a user 'tempuser' with admin rights to import the database as I don't have default users. I shutdown orientdb, I connect plocal and import the database with the user 'tempuser'. When done I disconnect from my console and I startup my container. I connect with root on the webpanel, no logs at that time. I delete the user with my username, log out and log in again, no logs (this user was reader and admin). I remove the user with username 'server' which has reader, writer & admin, I log out and in again with root and there is the NullPointer. I have no idea what causes this. At first I thought it was the same username as the temporary user but now I created a different user for that I'm still seeing this issue which is odd.

**Comment by 33Fraise33** [comment]
Extra:

When syncing the database in distributed mode the other nodes also have this issue.

**Comment by luigidellaquila** [comment]
Hi @33Fraise33 

Little update here: I was able to reproduce the problem once, even without exporting/importing the db, so the problem seems to exist in general. The problem is that I can't manage to reproduce it again and I don't remember the exact steps I did the first time... I tried a lot of combinations of operations but I never succeeded again, so it must be something very specific. 

I'll keep trying, I'll let you know as soon as I have a fix

Thanks

Luigi

**Comment by 33Fraise33** [comment]
Ok thanks for the update. It's a very weird bug. I'm able to reproduce it 100% of the time if I delete our specific 'server' user.

**Comment by markodjurovic** [comment]
@33Fraise33 
Hi, thank you for reporting this issue. I am trying to reproduce issue, currently with no success. So please if you may provide me more details:
* About back, what procedure you were using export/import or backup/restore?
* How did you delete user by DROP USER, or direct delete from OUser?

**Comment by 33Fraise33** [comment]
@markodjurovic all info on how I imported over here: https://github.com/orientechnologies/orientdb/issues/8218#issuecomment-381955909 

Deleting of the user always happened through the webpanel. Also @luigidellaquila was able to reproduce occasionally so I'm not completely sure what triggers it. Anyway I won't be working with orient anymore real soon so if you cannot reproduce this you might want to close this then.
