### ISSUE TITLE
Too Many Fix Messages And Negative Record ID In Distributed "dserver.sh"

### ISSUE THREAD

**Issue by hossein-md** [orientechnologies/orientdb#8233]
## Expected behavior  
<add here>  

I run Orientdb in two different ways:
1- I have one server and it is run by "server.sh" command.
2- I have Three servers and they are run by "dserver.sh" command. (cloud way)
For the case 1 as I expected my code (with java graph-api) runs well.
For the case 2 I expect that Orientdb works as well as case 1 (or near the case 1)
Number of shards, and hardware configs for the case 1 and 2 are the same.

Also I use the default "default-distributed-db-config.json" file without any modification. (Means every server has whole the database) 

## Actual behavior  
After less than a day, case 2 (means cloud way) becomes slow. For case 2 I have gotten two types of logs as the following:
1) I have gotten this error with different number (like: ``` #119:-78, #130:-2, #88:-3, ... ```)
```
Error on transaction commit `6785D785`
com.orientechnologies.orient.core.exception.OSerializationException: Impossible to serialize invalid link :#119:-78 in embedded session
	DB name="myDB"
	at com.orientechnologies.orient.core.db.record.ridbag.embedded.OEmbeddedRidBag.serialize(OEmbeddedRidBag.java:422)
	at com.orientechnologies.orient.core.db.record.ridbag.ORidBag.toStream(ORidBag.java:234)
	at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinaryV0.serializeValue(ORecordSerializerBinaryV0.java:763)
	at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinaryV0.serialize(ORecordSerializerBinaryV0.java:385)
	at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinary.toStream(ORecordSerializerBinary.java:99)
	at com.orientechnologies.orient.core.record.impl.ODocument.toStream(ODocument.java:2381)
	at com.orientechnologies.orient.core.record.impl.ODocument.toStream(ODocument.java:664)
	at com.orientechnologies.orient.server.distributed.impl.task.OUpdateRecordTask.init(OUpdateRecordTask.java:73)
	at com.orientechnologies.orient.server.distributed.impl.task.OFixUpdateRecordTask.init(OFixUpdateRecordTask.java:38)
	at com.orientechnologies.orient.server.distributed.impl.ODistributedTransactionManager.createUndoTasksFromTx(ODistributedTransactionManager.java:667)
	at com.orientechnologies.orient.server.distributed.impl.ODistributedTransactionManager.commit(ODistributedTransactionManager.java:112)
	at com.orientechnologies.orient.server.distributed.impl.ODistributedStorage.commit(ODistributedStorage.java:1421)
	at com.orientechnologies.orient.core.tx.OTransactionOptimistic.doCommit(OTransactionOptimistic.java:541)
	at com.orientechnologies.orient.core.tx.OTransactionOptimistic.commit(OTransactionOptimistic.java:99)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.commit(ODatabaseDocumentTx.java:2923)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.commit(ODatabaseDocumentTx.java:2885)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.commit(ONetworkProtocolBinary.java:1434)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.executeRequest(ONetworkProtocolBinary.java:668)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.sessionRequest(ONetworkProtocolBinary.java:398)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.execute(ONetworkProtocolBinary.java:217)
	at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:82)
```

2) I have gotten a lot of this INFO with different reqIds.
```
Auto repairing completed. Sent 438 fix messages for 2639 records (reqId=0.102188)
```

**Comment by gtadudeps** [comment]
Hi we are also facing these two issues any update on this?

**Comment by sshuliar** [comment]
I have the same issue as well. Can someone help to identify why it's happening?

**Comment by ygyg70** [comment]
We may be having the same issue, version 2.2.36.
Any update?

**Comment by gsbomrel** [comment]
@sshuliar, cc @laa  did you solve this issue ? It was perfectly working in 2.2.0. Now, after upgrading to 2.2.37, we got the same error while creating.

**Comment by tglman** [comment]
Hi,

Versions 2.2.x are out of any support since ~3 years, hard to get any fix or updates on that versions, is suggested to migrate to a 3.x version better if 3.2.x

Regards
