### ISSUE TITLE
Socket write error on the server 

### ISSUE THREAD

**Issue by jayaramcs** [orientechnologies/orientdb#8248]
## Expected behavior  
No Severe errors 

## Actual behavior  
```SEVERE [null]: $ANSI{green {db=CyberTriage}} Error on unmarshalling record #57:298404 (java.net.SocketException: Software caused connection abort: socket write error)
java.net.SocketException: Software caused connection abort: socket write error
	at java.net.SocketOutputStream.socketWrite0(Native Method)
	at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:111)
	at java.net.SocketOutputStream.write(SocketOutputStream.java:155)
	at java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:82)
	at java.io.BufferedOutputStream.write(BufferedOutputStream.java:126)
	at java.io.DataOutputStream.write(DataOutputStream.java:107)
	at com.orientechnologies.orient.enterprise.channel.binary.OChannelBinary.writeBytes(OChannelBinary.java:279)
[catch] at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.writeRecord(ONetworkProtocolBinary.java:2928)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.writeIdentifiable(ONetworkProtocolBinary.java:2701)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.readRecord(ONetworkProtocolBinary.java:1961)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.executeRequest(ONetworkProtocolBinary.java:621)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.sessionRequest(ONetworkProtocolBinary.java:398)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.execute(ONetworkProtocolBinary.java:217)
	at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:82)
``` 

## Steps to reproduce  
Insert data 
have a client program retrieve the data . 

I started to notice this issue only in the latest 2.2.33 build.

**Comment by tglman** [comment]
Hi @jayaramcs,

This error seems just that the client disconnected while receiving the data, if is not recurrent should not be a problem, I would suggest to double check if the client is up and running and that you don't have network problems.

Regards

**Comment by jayaramcs** [comment]
Hi @tglman 
I did not detect any network problems (I had an active RDP session to the client from the server when I got the errors). The client application was left running, although I don't know if orientdb client is disconnecting after a time period of inactivity ? 

It does not seem to be causing any side effects, however it does end up bubbling up to my application later and ends up showing traces and a ton of SEVERE errors in log messages.

If this is not a big issue, can you please consider dropping the severity level on this? 

Thanks

**Comment by tglman** [comment]
Hi @jayaramcs,

Could you share the log of the server and the client so we can be sure there are no other issue?

Regards
