### ISSUE TITLE
Getting database is closed exception for graph.shutdown()

### ISSUE THREAD

**Issue by shubhambondarde** [orientechnologies/orientdb#8251]
### OS: windows

Getting database is closed exception for graph.shutdown()

**The following is the error stack trace:**
com.orientechnologies.orient.core.exception.ODatabaseException: Database is closed
	at com.tinkerpop.blueprints.impls.orient.OrientBaseGraph.makeActive(OrientBaseGraph.java:306)
	at com.tinkerpop.blueprints.impls.orient.OrientBaseGraph.pollGraphFromStack(OrientBaseGraph.java:1868)
	at com.tinkerpop.blueprints.impls.orient.OrientBaseGraph.shutdown(OrientBaseGraph.java:1121)
	at com.tinkerpop.blueprints.impls.orient.OrientBaseGraph.shutdown(OrientBaseGraph.java:1079)
	at com.tinkerpop.blueprints.impls.orient.OrientBaseGraph.shutdown(OrientBaseGraph.java:1072)

**Comment by shubhambondarde** [comment]
This issue is also reproducing on latest Orientdb version 2.2.34
The following is the stack trace:

SEVERE: Error during context close for db null
com.orientechnologies.orient.core.exception.ODatabaseException: Database is closed
        at com.tinkerpop.blueprints.impls.orient.OrientBaseGraph.makeActive(OrientBaseGraph.java:309)
        at com.tinkerpop.blueprints.impls.orient.OrientBaseGraph.pollGraphFromStack(OrientBaseGraph.java:1873)
        at com.tinkerpop.blueprints.impls.orient.OrientBaseGraph.shutdown(OrientBaseGraph.java:1118)
        at com.tinkerpop.blueprints.impls.orient.OrientBaseGraph.shutdown(OrientBaseGraph.java:1080)
        at com.tinkerpop.blueprints.impls.orient.OrientBaseGraph.shutdown(OrientBaseGraph.java:1073)

**Comment by luigidellaquila** [comment]
Hi @shubhambondarde 

Could you please post some code to understand how to reproduce it?

Thanks

Luigi

**Comment by shubhambondarde** [comment]
Hi @luigidellaquila 

The following is the code snippet we use to close the db connection:
This exception does not occur every time. There is no fix pattern to reproduce this issue.

if (db != null) {	
  db.activateOnCurrentThread();
  if (!og.isClosed()) {                                            
	og.shutdown();                                  **getting exception at this line** 
 }
 db.close();
 db = null;
}

**Comment by tglman** [comment]
Hi @shubhambondarde,

This can happen if you share the same instance of the graph across multiple threads, that would as well justify the random failure.

Regards

**Comment by shubhambondarde** [comment]
Hi @tglman and @luigidellaquila 

We are getting the graph instance as follows:
OrientGraphFactory ogf = new OrientGraphFactory(databaseUrl, username, password);
OrientTransactionalGraph og = ogf.getTx();

Is there any chance that we can get same og(graph) instance?
