### ISSUE TITLE
Cannot serialize record. 

### ISSUE THREAD

**Issue by bipulkarnani** [orientechnologies/orientdb#8257]
### Java Version: docker image

Frequently we are getting the following error:
```
2018-05-10 05:18:14:150 WARNI Cannot serialize record: #-2:137{key1:key1_value,key2:key2_value} v0Error on unmarshalling record #-2:138 (java.net.SocketException: Broken pipe (Write failed))
java.net.SocketException: Broken pipe (Write failed)
        at java.net.SocketOutputStream.socketWrite0(Native Method)
        at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:111)
        at java.net.SocketOutputStream.write(SocketOutputStream.java:155)
        at java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:82)
        at java.io.BufferedOutputStream.write(BufferedOutputStream.java:126)
        at java.io.DataOutputStream.write(DataOutputStream.java:107)
        at com.orientechnologies.orient.enterprise.channel.binary.OChannelBinary.writeBytes(OChannelBinary.java:279)
        at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.writeRecord(ONetworkProtocolBinary.java:2928)
        at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.writeIdentifiable(ONetworkProtocolBinary.java:2701)
        at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.serializeValue(ONetworkProtocolBinary.java:1643)
        at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.command(ONetworkProtocolBinary.java:1588)
        at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.executeRequest(ONetworkProtocolBinary.java:664)
        at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.sessionRequest(ONetworkProtocolBinary.java:398)
        at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.execute(ONetworkProtocolBinary.java:217)
        at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:82)
```

There is no pattern for this error. We noticed that when we run long running queries, this error keeps on repeating itself.

**Comment by tglman** [comment]
Hi @bipulkarnani,

This error say that there was a network problem while the result of a query was written on the socket to be sent back to the client,
I would suggest to check if you have some firewall rule that interrupt long running sockets or something similar, this is definitely a networking problem.

Regards

**Comment by bipulkarnani** [comment]
Hi @tglman,

Thanks for the reply. I will check it at my end for firewall settings. Closing the issue.
