### ISSUE TITLE
server side hook not working 

### ISSUE THREAD

**Issue by gibrit** [orientechnologies/orientdb#8264]
## Expected behavior  
I am trying to create a hook on server side ( i did  it  older versions ) . here is  simple  hook  and ran some queries on orientdb studio .. getting errors.  
```
package com.simple;
public class SimpleHook extends ORecordHookAbstract {

    @Override
    public DISTRIBUTED_EXECUTION_MODE getDistributedExecutionMode() {
        return DISTRIBUTED_EXECUTION_MODE.BOTH;
    }
    
}
```

## Actual behavior  

 2.2.34 (build f340442755a31eabc91b87cb3ef99eda5cee6ebd, branch 2.2.x)
java.lang.NoSuchFieldError: INSTANCE
	at com.orientechnologies.orient.graph.sql.OGraphCommandExecutorSQLFactory.runWithAnyGraph(OGraphCommandExecutorSQLFactory.java:205)
	at com.orientechnologies.orient.graph.sql.OCommandExecutorSQLCreateVertex.execute(OCommandExecutorSQLCreateVertex.java:125)
	at com.orientechnologies.orient.core.sql.OCommandExecutorSQLDelegate.execute(OCommandExecutorSQLDelegate.java:70)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.executeCommand(OAbstractPaginatedStorage.java:3399)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.command(OAbstractPaginatedStorage.java:3317)
	at com.orientechnologies.orient.core.command.OCommandRequestTextAbstract.execute(OCommandRequestTextAbstract.java:69)
	at com.orientechnologies.orient.server.network.protocol.http.command.post.OServerCommandPostCommand.execute(OServerCommandPostCommand.java:106)
	at com.orientechnologies.orient.graph.server.command.OServerCommandPostCommandGraph.execute(OServerCommandPostCommandGraph.java:37)
	at com.orientechnologies.orient.server.network.protocol.http.ONetworkProtocolHttpAbstract.service(ONetworkProtocolHttpAbstract.java:173)
	at com.orientechnologies.orient.server.network.protocol.http.ONetworkProtocolHttpAbstract.execute(ONetworkProtocolHttpAbstract.java:629)
	at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:82)
Uncaught exception in thread OrientDB HTTP Connection /127.0.0.1:2480<-/127.0.0.1:57510 <command>sql.create vertex oauth2scope set name='deneme' , role='deneme'</command>

## Steps to reproduce  
1) Stop server
2)copy the jar to lib folder . 
3)config.xml  adding 
 ```
<hooks>
	<hook class="com.simple.SimpleHook" position="REGULAR"/>
</hooks>

```
4)  start server 
5) run some query on orientdb studio 

problem may be caused by deprecated   ODatabaseRecordThreadLocal.INSTANCE

**Comment by luigidellaquila** [comment]
Hi @gibrit 

Could you please check your dependencies? I think you are using an old version of the graph module

Thanks

Luigi

**Comment by gibrit** [comment]
the problem is that ..  thank you for your response

**Comment by gibrit** [comment]
ups sorry
