### ISSUE TITLE
[v3.0.0] CREATE EDGE throws` java.lang.NullPointerException` when useLightweightEdges is enabled

### ISSUE THREAD

**Issue by mehdizarepour** [orientechnologies/orientdb#8267]
### OS: Linux

I want to use lightweight edges in OrientDB 3.0.0

## Expected behavior

`CREATE EDGE` command should create a lightweight edge between two vertexes

## Actual behavior

But it throws  `java.lang.NullPointerException` error

## Steps to reproduce  

1. Create a new database and enable the "useLightweightEdges" flag

   - **Issue 1:** In the OrientDB Studio the "Lightweight edges" option in the "New Database" modal doesn't enable `useLightweightEdges` and I have to run `ALTER DATABASE CUSTOM useLightweightEdges = true` or use configuration tab in the DB page)

2. Run these commands:

```sql

INSERT INTO V SET id = 1

INSERT INTO V SET id = 2


CREATE EDGE E FROM (SELECT FROM V WHERE id = 1) To(SELECT FROM V WHERE id = 2)
```

**Issue 2:** it throws `java.lang.NullPointerException` error

If I disable the `useLightweightEdges` using `ALTER DATABASE CUSTOM useLightweightEdges = false` it create a normal edge and doesn't throw any errors

Error stack for Issue 2:

```
java.lang.NullPointerException

    at com.orientechnologies.orient.core.record.ORecordInternal.getDirtyManager(ORecordInternal.java:134)

    at com.orientechnologies.orient.core.db.document.ODatabaseDocumentAbstract.save(ODatabaseDocumentAbstract.java:2012)

    at com.orientechnologies.orient.core.db.document.ODatabaseDocumentAbstract.save(ODatabaseDocumentAbstract.java:1922)

    at com.orientechnologies.orient.core.db.document.ODatabaseDocumentAbstract.save(ODatabaseDocumentAbstract.java:84)

    at com.orientechnologies.orient.core.sql.executor.SaveElementStep$1.next(SaveElementStep.java:40)

    at com.orientechnologies.orient.core.sql.executor.OInsertExecutionPlan.executeInternal(OInsertExecutionPlan.java:49)

    at com.orientechnologies.orient.core.sql.parser.OCreateEdgeStatement.execute(OCreateEdgeStatement.java:63)

    at com.orientechnologies.orient.core.command.OSqlScriptExecutor.execute(OSqlScriptExecutor.java:44)

    at com.orientechnologies.orient.core.db.document.ODatabaseDocumentEmbedded.execute(ODatabaseDocumentEmbedded.java:588)

    at com.orientechnologies.orient.server.network.protocol.http.command.post.OServerCommandPostCommand.executeStatement(OServerCommandPostCommand.java:174)

    at com.orientechnologies.orient.server.network.protocol.http.command.post.OServerCommandPostCommand.execute(OServerCommandPostCommand.java:84)

    at com.orientechnologies.orient.server.network.protocol.http.command.post.OServerCommandPostCommandGraph.execute(OServerCommandPostCommandGraph.java:36)

    at com.orientechnologies.orient.server.network.protocol.http.ONetworkProtocolHttpAbstract.service(ONetworkProtocolHttpAbstract.java:172)

    at com.orientechnologies.orient.server.network.protocol.http.ONetworkProtocolHttpAbstract.execute(ONetworkProtocolHttpAbstract.java:633)

    at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:82)
```

Thanks

**Comment by tglman** [comment]
Hi @mehdizarepour,

I've fixed this, this fix will be included in 3.0.2 release.

Regards
