### ISSUE TITLE
OrientGraphFactory.getNoTx() gets stuck when the DB is created on the files-system.

### ISSUE THREAD

**Issue by morad-morad** [orientechnologies/orientdb#8295]
### OS: suse 11

OrientGraphFactory.getNoTx() gets stuck when the DB is created on the files-system.
only 21 files are created in the db directory. The first file is manindex.cpm and the last file is jobs.db.0.wal and then it gets stuck. The time difference between the first created file and the last created file is 7 minutes.
When the DB created in memory everything works fine.
What could be the issue? Is there any requirements on the file system?

**Comment by laa** [comment]
Hi @morad-morad , could you attach a stack trace when DB gets stuck? Could you add it as a gist? Please do not put full stack traces into issue comments.

**Comment by morad-morad** [comment]
Thanks.
Uploaded stack-trace and jstack output.

[stack.tar.gz](https://github.com/orientechnologies/orientdb/files/2045692/stack.tar.gz)

**Comment by laa** [comment]
Hi @morad-morad I see that system waits for checking of the amount of free space during the flush of data from WAL nothing more. Could you do the following? Could you send me several such thread dumps with let say 1 min interval? I suppose 5 of them would be cool to have. If that is slow down because of free space check I will provide you patch to fix it very soon.

**Comment by morad-morad** [comment]
Thanks @laa 
I'll send the thread dumps soon.

**Comment by morad-morad** [comment]
Hi @laa 
Can we get the patch please? Is there any quick fix that we can do?

Thanks

**Comment by laa** [comment]
Hi @morad-morad could you try this distribution https://drive.google.com/file/d/1b5UEaMrTzehA2Y9ozgNQgxNfA020zFhT/view?usp=sharing . Could you also start from a fresh database? Do not try to open previous one. Because I see that it is crashed and the system tries to restore it.

**Comment by laa** [comment]
@morad-morad yes you are right.

**Comment by morad-morad** [comment]
Hi @laa 
I get the following exception when using the provided distribution:

java.lang.NoSuchFieldError: INSTANCE
	at com.tinkerpop.blueprints.impls.orient.OrientBaseGraph.makeActive(OrientBaseGraph.java:366)
	at com.tinkerpop.blueprints.impls.orient.OrientBaseGraph.<init>(OrientBaseGraph.java:146)
	at com.tinkerpop.blueprints.impls.orient.OrientGraphNoTx.<init>(OrientGraphNoTx.java:62)
	at com.tinkerpop.blueprints.impls.orient.OrientGraphFactory$2.getGraph(OrientGraphFactory.java:116)
	at com.tinkerpop.blueprints.impls.orient.OrientGraphFactory.getNoTx(OrientGraphFactory.java:240)

**Comment by laa** [comment]
Hi @morad-morad that means that you have issues with your classpath, how do you build the project?

**Comment by morad-morad** [comment]
Thanks. you're right I fixed my classpath but now I get another exception:

java.util.ServiceConfigurationError: com.orientechnologies.orient.core.index.OIndexFactory: Provider com.orientechnologies.orient.core.index.hashindex.local.OHashIndexFactory not found
	at java.util.ServiceLoader.fail(ServiceLoader.java:239)
	at java.util.ServiceLoader.access$300(ServiceLoader.java:185)
	at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:372)
	at java.util.ServiceLoader$LazyIterator.next(ServiceLoader.java:404)
	at java.util.ServiceLoader$1.next(ServiceLoader.java:480)
	at com.orientechnologies.orient.core.index.OIndexes.getFactories(OIndexes.java:73)
	at com.orientechnologies.orient.core.index.OIndexes.getAllFactories(OIndexes.java:85)
	at com.orientechnologies.orient.core.index.OIndexes.getFactory(OIndexes.java:120)
	at com.orientechnologies.orient.core.index.OIndexManagerAbstract.create(OIndexManagerAbstract.java:172)
	at com.orientechnologies.orient.core.db.OSharedContextEmbedded.create(OSharedContextEmbedded.java:113)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentEmbedded.createMetadata(ODatabaseDocumentEmbedded.java:250)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentEmbedded.internalCreate(ODatabaseDocumentEmbedded.java:221)
	at com.orientechnologies.orient.core.db.OrientDBEmbedded.internalCreate(OrientDBEmbedded.java:266)
	at com.orientechnologies.orient.core.db.OrientDBEmbedded.create(OrientDBEmbedded.java:209)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.create(ODatabaseDocumentTx.java:978)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.create(ODatabaseDocumentTx.java:947)
	at com.orientechnologies.orient.core.db.OPartitionedDatabasePool.openDatabase(OPartitionedDatabasePool.java:297)
	at com.orientechnologies.orient.core.db.OPartitionedDatabasePool.acquire(OPartitionedDatabasePool.java:261)
	at com.tinkerpop.blueprints.impls.orient.OrientBaseGraph.<init>(OrientBaseGraph.java:147)
	at com.tinkerpop.blueprints.impls.orient.OrientGraphNoTx.<init>(OrientGraphNoTx.java:61)
	at com.tinkerpop.blueprints.impls.orient.OrientGraphFactory$2.getGraph(OrientGraphFactory.java:119)
	at com.tinkerpop.blueprints.impls.orient.OrientGraphFactory.getNoTx(OrientGraphFactory.java:244)

**Comment by laa** [comment]
Hi @morad-morad that is also should be an issue in the classpath, probably you use different versions of libraries.

**Comment by morad-morad** [comment]
Hi @laa 
I need orientdb-graphdb jar of the same version (3.0.2)
How can I get it? it doesn't exist in the provided distribution

**Comment by laa** [comment]
Hi @morad-morad could you take this jar from here http://central.maven.org/maven2/com/orientechnologies/orientdb-community-tp2/3.0.1/

**Comment by morad-morad** [comment]
Hi @laa 
Still getting the same exception... my classpath contains the jars in the libs directory of the distributions that you provided. I use it at compilation and runtime. compilation passes successfully, bu I get the following exception at runtime:

Exception in thread "main" org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'GraphDbFactoryBean': Invocation of init method failed; nested exception is java.util.ServiceConfigurationError: com.orientechnologies.orient.core.index.OIndexFactory: Provider com.orientechnologies.orient.core.index.hashindex.local.OHashIndexFactory not found
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:136)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsBeforeInitialization(AbstractAutowireCapableBeanFactory.java:408)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1570)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:545)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:482)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:775)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:861)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:541)
	at org.springframework.context.support.ClassPathXmlApplicationContext.<init>(ClassPathXmlApplicationContext.java:139)
	at org.springframework.context.support.ClassPathXmlApplicationContext.<init>(ClassPathXmlApplicationContext.java:83)
	at com.simpledb.Main.main(Main.java:9)
Caused by: java.util.ServiceConfigurationError: com.orientechnologies.orient.core.index.OIndexFactory: Provider com.orientechnologies.orient.core.index.hashindex.local.OHashIndexFactory not found
	at java.util.ServiceLoader.fail(ServiceLoader.java:239)
	at java.util.ServiceLoader.access$300(ServiceLoader.java:185)
	at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:372)
	at java.util.ServiceLoader$LazyIterator.next(ServiceLoader.java:404)
	at java.util.ServiceLoader$1.next(ServiceLoader.java:480)
	at com.orientechnologies.orient.core.index.OIndexes.getFactories(OIndexes.java:73)
	at com.orientechnologies.orient.core.index.OIndexes.getAllFactories(OIndexes.java:85)
	at com.orientechnologies.orient.core.index.OIndexes.getFactory(OIndexes.java:120)
	at com.orientechnologies.orient.core.index.OIndexManagerAbstract.create(OIndexManagerAbstract.java:172)
	at com.orientechnologies.orient.core.db.OSharedContextEmbedded.create(OSharedContextEmbedded.java:113)

**Comment by morad-morad** [comment]
Hi @laa 
I was able to solve this issue by removing the checkFreeSpace in OLogSegment.java

**Comment by laa** [comment]
Hi @morad-morad did you use 2.2.17 since begging? Because I see 3.0 version in issue.

**Comment by morad-morad** [comment]
Hi @laa  Yes I use 2.2.17 from beginning sorry it was my mistake. But I did try to use 3.0.0 and it also got stuck for me.

**Comment by laa** [comment]
Hi @morad-morad. It is partially correct. We can not just remove check of free space, but we can enforce minimum check interval of free space.   I see here two variants I will apply the previous patch either to latest  3.0.x version or to latest 2.2.x version and we check it again. What variant do you prefer?

**Comment by morad-morad** [comment]
Hi @laa
I use orientdb-core-2.2.17.jar and orientdb-graph-2.2.17.jar. So I prefer the latest 2.2.x version.
Thanks

**Comment by morad-morad** [comment]
Hi @laa Any updates? can I get the patched latest 2.2.x?

**Comment by laa** [comment]
Hi @morad-morad could you check this build?https://drive.google.com/file/d/1qV4HodVLKwitX_FIksEYv4MiDGhWMqWq/view?usp=sharing

**Comment by morad-morad** [comment]
Thanks @laa 
I'll try it and update you

**Comment by morad-morad** [comment]
Hi @laa 
unfortunately this didn't work
Attached thread dumps
[jstacks.tar.gz](https://github.com/orientechnologies/orientdb/files/2114384/jstacks.tar.gz)

**Comment by laa** [comment]
Hi @morad-morad , got it. Will provide you other solution in a couple of days.

**Comment by laa** [comment]
Hi @morad-morad could you try this one https://drive.google.com/file/d/1qV4HodVLKwitX_FIksEYv4MiDGhWMqWq/view?usp=sharing

**Comment by laa** [comment]
Hi @morad-morad could you check the latest build provided with the patch?

**Comment by laa** [comment]
Hi @morad-morad could you check the latest build provided with the patch?

**Comment by laa** [comment]
Moved to 3.1 version because of no response.

**Comment by laa** [comment]
Hi guys, please let me know if this issue still actual I will work on it.
