### ISSUE TITLE
console still interprets file path strings for special characters

### ISSUE THREAD

**Issue by hrstoyanov** [orientechnologies/orientdb#8325]
## Expected behavior  
console executes the scripts

## Actual behavior  
console fails attempts to interpret file names and fails to execute scripts 

Here is a gradle task I use to automate the creation of my sample database - I put all file paths in single quotes (I also tried double-quotes with the same result):

```groovy
task createDevDatabase(type: JavaExec){
    doFirst {
        new File("${projectDir}/../rehabowner.db").deleteDir()
    }
    main = 'com.orientechnologies.orient.console.OConsoleDatabaseApp'
    classpath = configurations.odb
    jvmArgs  = ['-Dfile.encoding=utf-8',
                '-Djna.nosys=true',
                '-Djava.awt.headless=true',
                '-Djava.util.logging.config.file=${projectDir}/src/main/odb/config/odb-client-log.properties'
    ]
    args  = [
            "set verbose 10;"+
            "create database plocal:'${projectDir}/../rehabowner.db admin admin';" +
            "load script '${projectDir}/src/main/odb/scripts/schema.sql';" +
            "load script '${projectDir}/src/main/odb/scripts/sample_data.sql';" +
            "disconnect;"
    ]
}
```

Here is what  I get:

```
com.orientechnologies.orient.console.OConsoleDatabaseApp set verbose 10;create database plocal:'C:\temp\gitlab\peruncs\
recres\recres-webapp/../rehabowner.db admin admin';load script 'C:\temp\gitlab\peruncs\recres\recres-webapp/src/main/odb/scripts/schema.sql';load script 'C:\temp\gitlab\peruncs\recres\recres-webapp/src/main/odb/scripts/sample_data.sql';disconnect;
Successfully started process 'command 'C:\Program Files (x86)\Java\jre1.8.0_172\bin\java.exe''

OrientDB console v.3.0.2 - Veloce (build e47e693f1470a7a642461be26983d4eca70777fd, branch develop) https://www.orientdb.com
Type 'help' to display all the supported commands.

Previous value was: 2
verbose = 10

ecres-webapp/../rehabowner.db admin admin] using the storage type [PLOCAL]...

ecres-webapp\../rehabowner.db admin admin: Illegal char <       > at index 3: C:\       emp\gitlab\peruncs\
:recres-webapp:createDevDatabase (Thread[Task worker for ':',5,main]) completed. Took 1.101 secs.
```

As you can see, ```\r``` which is part of the path is __being interpreted and the path gets broken__. Other random ```\X``` in typical windows path can break script and database paths.

On Unix/MacOs, there is no issue since paths there use ```/```

**Comment by hrstoyanov** [comment]
This was supposed to have been resolved with #8284, but it is not.

**Comment by luigidellaquila** [comment]
Hi @hrstoyanov 

I just pushed a fix that should resolve the problem, the snapshot will be available in a few minutes

Thanks

Luigi

**Comment by luigidellaquila** [comment]
Hi @hrstoyanov 

using quotes is safer if you have blank spaces in the URI, but it should not be necessary in general

Thanks

Luigi

**Comment by hrstoyanov** [comment]
Thanks @luigidellaquila ,
 Just to clarify, the proper way (at least works on my windows machine)  to quote CREATE DATABASE and LOAD SCRIPT paths is;

```groovy
 args  = [
            "set verbose 1;"+ //versbose=1 makes the build silent
            "create database 'plocal:${projectDir}/../rehabowner.db' admin admin;" +
            "load script '${projectDir}/src/main/odb/scripts/schema.sql';" +
            "load script '${projectDir}/src/main/odb/scripts/sample_data.sql';" +
            "disconnect;"
    ]
```
Maybe a few clarification  words about this in the docs would help others.

**Comment by luigidellaquila** [comment]
Hi @hrstoyanov 

Good point, I'll add this info to the docs

Thanks

Luigi

**Comment by hrstoyanov** [comment]
@luigidellaquila you may need to update the demodb and add quotes for the scripts - I tried to build ODB from github and got this:

```
OrientDB console v.3.0.3-SNAPSHOT - Veloce (build ??????, branch UNKNOWN_BRANCH) https://www.orientdb.com
Type 'help' to display all the supported commands.
Jun 21, 2018 2:47:14 PM com.orientechnologies.common.log.OLogManager log
INFO: Windows OS is detected, 262144 limit of open files will be set for the disk cache.
Jun 21, 2018 2:47:14 PM com.orientechnologies.common.log.OLogManager log
INFO: 17120395264 B/16327 MB/15 GB of physical memory were detected on machine
Jun 21, 2018 2:47:14 PM com.orientechnologies.common.log.OLogManager log
INFO: Detected memory limit for current process is 17120395264 B/16327 MB/15 GB
Jun 21, 2018 2:47:14 PM com.orientechnologies.common.log.OLogManager log
INFO: JVM can use maximum 1820MB of heap memory
Jun 21, 2018 2:47:14 PM com.orientechnologies.common.log.OLogManager log
INFO: Because OrientDB is running outside a container 2g of memory will be left unallocated according to the setting 'memory.leftToOS' not taking into account h
eap memory
Jun 21, 2018 2:47:14 PM com.orientechnologies.common.log.OLogManager log
INFO: OrientDB auto-config DISKCACHE=12,458MB (heap=1,820MB os=16,327MB)
Jun 21, 2018 2:47:14 PM com.orientechnologies.common.log.OLogManager log
INFO: Storage 'plocal:C:\temp\github\orientdb\distribution\target\databases/demodb' is created under OrientDB distribution : 3.0.3-SNAPSHOT - Veloce (build ????
??, branch UNKNOWN_BRANCH)
Creating database [plocal:C:\temp\github\orientdb\distribution/target/databases/demodb] using the storage type [PLOCAL]...
Database created successfully.

Current database is: plocal:C:\temp\github\orientdb\distribution/target/databases/demodb
Disconnecting from the database [demodb]...OK
Jun 21, 2018 2:47:16 PM com.orientechnologies.common.log.OLogManager log
INFO: - shutdown storage: demodb...

Jun 21, 2018 2:47:16 PM com.orientechnologies.common.log.OLogManager log
SEVERE: Error on opening database: C:\temp\github\orientdb\distribution\        emp\github\orientdb\distribution\target\databases/demodb. Current location is: C
:\temp\github\orientdb\distribution\.
Connecting to database [plocal:C:       emp\github\orientdb\distribution/target/databases/demodb] with user 'admin'...
java.nio.file.InvalidPathException: Illegal char <      > at index 37: C:/temp/github/orientdb/distribution/    emp/github/orientdb/distribution/target/database
s/demodb
        at sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:182)
        at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:153)
        at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77)
        at sun.nio.fs.WindowsPath.parse(WindowsPath.java:94)
        at sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:255)
        at java.nio.file.Paths.get(Paths.java:84)
        at com.orientechnologies.orient.core.storage.impl.local.paginated.OLocalPaginatedStorage.<init>(OLocalPaginatedStorage.java:100)
        at com.orientechnologies.orient.core.engine.local.OEngineLocalPaginated.createStorage(OEngineLocalPaginated.java:95)
        at com.orientechnologies.orient.core.db.OrientDBEmbedded.getOrInitStorage(OrientDBEmbedded.java:173)
        at com.orientechnologies.orient.core.db.OrientDBEmbedded.open(OrientDBEmbedded.java:129)
        at com.orientechnologies.orient.core.db.OrientDB.open(OrientDB.java:205)
        at com.orientechnologies.orient.core.db.OrientDB.open(OrientDB.java:190)
        at com.orientechnologies.orient.console.OConsoleDatabaseApp.connect(OConsoleDatabaseApp.java:224)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.orientechnologies.common.console.OConsoleApplication.execute(OConsoleApplication.java:420)
        at com.orientechnologies.common.console.OConsoleApplication.executeCommands(OConsoleApplication.java:256)
        at com.orientechnologies.common.console.OConsoleApplication.executeBatch(OConsoleApplication.java:211)
        at com.orientechnologies.common.console.OConsoleApplication.run(OConsoleApplication.java:134)
        at com.orientechnologies.orient.console.OConsoleDatabaseApp.main(OConsoleDatabaseApp.java:136)


Error: com.orientechnologies.orient.core.exception.ODatabaseException: Cannot open database 'demodb'

Error: com.orientechnologies.orient.core.exception.ODatabaseException: Error on opening database: C:\temp\github\orientdb\distribution\ emp\github\orientdb\dist
```

**Comment by hrstoyanov** [comment]
I tried to fix the POM file, but no success:
```xml
<plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>exec-maven-plugin</artifactId>
                <version>1.4.0</version>
                <executions>
                    <execution>
                        <id>build-db</id>
                        <phase>prepare-package</phase>
                        <goals>
                            <goal>exec</goal>
                        </goals>
                        <configuration>
                            <executable>${java.home}/bin/java</executable>
                            <workingDirectory>${project.basedir}</workingDirectory>
                            <arguments>
                                <argument>-Xmx${heapSize}</argument>
                                <argument>-DridBag.embeddedToSbtreeBonsaiThreshold=10000000</argument>
                                <argument>-classpath</argument>
                                <classpath/>
                                <argument>com.orientechnologies.orient.console.OConsoleDatabaseApp</argument>
                                <argument>CREATE DATABASE 'plocal:${basedir}/target/databases/demodb';</argument>
                                <argument>CONNECT 'plocal:${basedir}/target/databases/demodb' admin admin;</argument>
                                <argument>LOAD SCRIPT '${basedir}/src/main/resources/demodb-1-schema.osql';</argument>
                                <argument>LOAD SCRIPT '${basedir}/src/main/resources/demodb-2.osql';</argument>
                                <argument>LOAD SCRIPT '${basedir}/src/main/resources/demodb-3.osql';</argument>
                                <argument>LOAD SCRIPT '${basedir}/src/main/resources/demodb-4.osql';</argument>
                                <argument>LOAD SCRIPT '${basedir}/src/main/resources/demodb-5.osql';</argument>
                            </arguments>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
```

**Comment by hrstoyanov** [comment]
@luigidellaquila 
I just realized this issue is not yet completely fixed in the lastest 3.0.3-SNAPSHOT.  ```CONNECT 'plocal:/winpath'; admin admin``` fails with Windows paths (with or without quotes around the url),  while ```CREATE DATABASE 'plocal:/winpath'; admin admin``` works!

Not sure why there is a difference ???

**Comment by luigidellaquila** [comment]
Hi @hrstoyanov 

We just tried it and it seems to work fine. Could you please post a path that makes it fail?

Thanks

Luigi

**Comment by hrstoyanov** [comment]
@luigidellaquila 
Here is the Gradle snippet of code that I use - you see how I warp CONNECT url into '' in my ```seedDatabase``` task:

```
def ODBConsoleConfig = {
    main = 'com.orientechnologies.orient.console.OConsoleDatabaseApp'
    classpath = configurations.odb
    jvmArgs  = ['-Dfile.encoding=utf-8',
                '-Djna.nosys=true',
                '-Djava.awt.headless=true',
                '-Djava.util.logging.config.file=${projectDir}/src/main/odb/config/odb-client-log.properties'
    ]
}

task seedDatabase(type: JavaExec){
    configure ODBConsoleConfig
    args  = [
        "connect  'plocal:${projectDir}/../rehabowner.db' admin admin;" +
        "load script '${projectDir}/src/main/odb/scripts/seed_data.sql';" +
        "disconnect;"
    ]
}
```

I have also attached 
[issue8325-connect.zip](https://github.com/orientechnologies/orientdb/files/2134014/issue8325-connect.zip) the output log. You can see in the log how the CONNECT command is being run and how the presence of  ```\r``` in the url path breaks it in Windows. Note that I __do not see this url path issue__ with CREATE DATABASE ...

**Comment by luigidellaquila** [comment]
Thank you @hrstoyanov , I'll check it asap

Luigi

**Comment by luigidellaquila** [comment]
Hi @hrstoyanov 

I just pushed a new fix, now also the "connect" is correctly managed

Thanks

Luigi

**Comment by hrstoyanov** [comment]
@luigidellaquila , .. sigh ... now I am seeing different issue, see the new attached file
[issue8325-connect.zip](https://github.com/orientechnologies/orientdb/files/2142598/issue8325-connect.zip)

**Comment by luigidellaquila** [comment]
Hi @hrstoyanov 

It could be the two blank spaces after `connect`, I'll check it and let you know asap

Thanks

Luigi

**Comment by luigidellaquila** [comment]
Hi @hrstoyanov 

It could be the two blank spaces after `connect`, I'll check it and let you know asap

Thanks

Luigi

**Comment by luigidellaquila** [comment]
Hi @hrstoyanov 

Yes, that was the problem, I just pushed a fix

Thanks

Luigi

**Comment by hrstoyanov** [comment]
@luigidellaquila well, now there is another problem, see attachment
[issue8325-connect.zip](https://github.com/orientechnologies/orientdb/files/2146041/issue8325-connect.zip)

**Comment by luigidellaquila** [comment]
Uhm... ok, the problem here seem to be the quotes, checking now

**Comment by luigidellaquila** [comment]
Hi @hrstoyanov 

Thank you very much for your patience, I just pushed another fix

Luigi

**Comment by hrstoyanov** [comment]
@luigidellaquila  works now!
