### ISSUE TITLE
OSecurityException: Cannot create a key with 'PBKDF2WithHmacSHA256' algorithm in Java Version: 1.8.0_172

### ISSUE THREAD

**Issue by asadganiev** [orientechnologies/orientdb#8333]
### OS: macOS High Sierra Version 10.13.4

``` java
OrientDB orientDB = new OrientDB("plocal:/tmp/", OrientDBConfig.defaultConfig());
orientDB.create("test", ODatabaseType.PLOCAL);
orientDB.close();
```
Error:

```java
com.orientechnologies.orient.core.exception.OSecurityException: Cannot create a key with 'PBKDF2WithHmacSHA256' algorithm
	DB name="test"
        ...
Caused by: java.security.NoSuchAlgorithmException: PBKDF2WithHmacSHA256 SecretKeyFactory not available
	at javax.crypto.SecretKeyFactory.<init>(SecretKeyFactory.java:122)
	at javax.crypto.SecretKeyFactory.getInstance(SecretKeyFactory.java:160)
	at com.orientechnologies.orient.core.security.OSecurityManager.getPbkdf2(OSecurityManager.java:236)
	... 56 more
```
I have added this method in order to check if PBKDF2WithHmacSHA256 supported
```java
private static boolean isAlgorithmSupported(final String algorithm) {
    // Java 7 specific checks.
    if (Runtime.class.getPackage() != null &&
            Runtime.class.getPackage().getImplementationVersion() != null) {
        if (Runtime.class.getPackage().getImplementationVersion().startsWith("1.7")) {
            // Java 7 does not support the PBKDF2_SHA256_ALGORITHM.
            if (algorithm != null && algorithm.equals(PBKDF2_SHA256_ALGORITHM)) {
                return false;
            }
        }
    }

    return true;
}
```

```java
System.out.println(isAlgorithmSupported("PBKDF2WithHmacSHA256"));
```
Prints `true`.

**Comment by asadganiev** [comment]
This problem occurred in my test class when I was using PowerMockito. It was fixed by ignoring [javax.crypto.*](https://stackoverflow.com/a/22249508/8898704) in my test:

```java
@PowerMockIgnore("javax.crypto.*")
@RunWith(PowerMockRunner.class)
```
