### ISSUE TITLE
Cannot UPDATE REMOVE from Map in 3.x

### ISSUE THREAD

**Issue by mmacfadden** [orientechnologies/orientdb#8334]
## Expected behavior  
Apologies if I missed something in the documentation regarding migrating to 3.x, however it seems like removing elements from a MAP (either embedded or linked) using the previous syntax is problematic. The following SQL worked in 2.2.35:  

```SQL
CREATE CLASS Test;
INSERT INTO Test SET m = {"k1": "v1", "k2": "v2"};
UPDATE Test REMOVE m = "k1";
SELECT FROM Test;
```

The result was  `[{"m": {"k2":"v2"}}]`

## Actual behavior 

This same script in 3.0.2 produces the following exception:

```
java.lang.IllegalArgumentException: Object {k1=v1, k2=v2} is not a multi value
    at com.orientechnologies.common.collection.OMultiValue.remove(OMultiValue.java:660)
    at com.orientechnologies.orient.core.sql.parser.OUpdateRemoveItem.applyUpdate(OUpdateRemoveItem.java:75)
    at com.orientechnologies.orient.core.sql.executor.UpdateRemoveStep$1.next(UpdateRemoveStep.java:36)
    at com.orientechnologies.orient.core.sql.executor.SaveElementStep$1.next(SaveElementStep.java:37)
    at com.orientechnologies.orient.core.sql.executor.CountStep.syncPull(CountStep.java:53)
    at com.orientechnologies.orient.core.sql.executor.OSelectExecutionPlan.fetchNext(OSelectExecutionPlan.java:37)
    at com.orientechnologies.orient.core.sql.executor.OUpdateExecutionPlan.executeInternal(OUpdateExecutionPlan.java:46)
    at com.orientechnologies.orient.core.sql.parser.OUpdateStatement.execute(OUpdateStatement.java:156)
    at com.orientechnologies.orient.core.command.OSqlScriptExecutor.execute(OSqlScriptExecutor.java:70)
    at com.orientechnologies.orient.core.db.document.ODatabaseDocumentEmbedded.execute(ODatabaseDocumentEmbedded.java:600)
```

I've reviewed the following docs and did not see any planned changes to this syntax.

- https://orientdb.com/docs/3.0.x/release/3.0/SQL-Changes.html
- https://orientdb.com/docs/3.0.x/release/3.0/Upgrading-to-OrientDB-3.0.html
- https://orientdb.com/docs/3.0.x/sql/SQL-Update.html

This does not seem to be a parsing issue though. A quick review of the stack suggests that this is in the execution phase. I took a look at OUpdateRemoveItem:

https://github.com/orientechnologies/orientdb/blob/9847c4359eab6476b403a1777c5f97d7f6e02957/core/src/main/java/com/orientechnologies/orient/core/sql/parser/OUpdateRemoveItem.java#L74

Oddly it checks `OMultiValue.isMultiValue(leftVal)` before calling `OMultiValue.remove(leftVal, rightVal, false);` which returns true. Then in `OMultiValue.remove()` it blows up for some reason. This seems like a bug inside OMultiValue perhaps.

**Comment by mmacfadden** [comment]
It seems as though this syntax works:

`UPDATE Test REMOVE m.`k1`;`

But this one does not:

`UPDATE Test REMOVE m["k1"];`

Is this intended?

**Comment by luigidellaquila** [comment]
Hi @mmacfadden 

The square bracket syntax is supposed to work, so I'd say it's a bug. I'll check it asap

Thanks

Luigi

**Comment by luigidellaquila** [comment]
Hi @mmacfadden 

I just pushed a fix, now all the different syntaxes work fine

Thanks

Luigi
