### ISSUE TITLE
Attempt to etablish a remote connection on local host fail due to AbstractMethodError

### ISSUE THREAD

**Issue by edmondboulet** [orientechnologies/orientdb#8340]
## Expected behavior  
graph = factory.getTx(); is supposed to get the Tx out of an OrientGraphFactory that already exist.

## Actual behavior  
throw an Error whith the trace :

java.lang.AbstractMethodError: Method com/orientechnologies/orient/core/db/document/ODatabaseDocumentRemote.beforeReadOperations(Lcom/orientechnologies/orient/core/db/record/OIdentifiable;)Z is abstract
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentRemote.beforeReadOperations(ODatabaseDocumentRemote.java)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentAbstract.executeReadRecord(ODatabaseDocumentAbstract.java:1352)
	at com.orientechnologies.orient.core.tx.OTransactionNoTx.reloadRecord(OTransactionNoTx.java:131)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentAbstract.reload(ODatabaseDocumentAbstract.java:1164)
	...

## Steps to reproduce  
Execute the following constructor while a gremlin server is running and the "newDB" already exist.

code will throw the error at " graph = factory.getTx();"

``
import org.apache.tinkerpop.gremlin.orientdb.OrientGraph;
import org.apache.tinkerpop.gremlin.orientdb.OrientGraphFactory;

public class OrientDBDataBaseGenerationTool {
String directory = "/home/me/OrientDB/orientdb-tp3-3.0.2/databases/newDB";
OrientGraph graph;

public OrientDBDataBaseGenerationTool(){
		OrientGraphFactory factory = new OrientGraphFactory("remote:localhost/newDB","root","root");
		graph = factory.getTx();
		graph.close();
		factory.close();
}
}
``

**Comment by edmondboulet** [comment]
Tried to change my import to :

import com.tinkerpop.blueprints.impls.orient.OrientGraph;
import com.tinkerpop.blueprints.impls.orient.OrientGraphFactory;

Same result.

**Comment by tglman** [comment]
Hi @edmondboulet,

Usually this kind of error happen because you are using jars of core and client of different version also minor, or if you have duplicate jars in your classpath.

Regards

**Comment by edmondboulet** [comment]
Hello @tglman 

Thanks for the answer I will look into it and kup.

**Comment by tglman** [comment]
Hi @edmondboulet,

No Problem, closing this.
