### ISSUE TITLE
Getting error on createSchema.

### ISSUE THREAD

**Issue by shubhambondarde** [orientechnologies/orientdb#8342]
### OS: windows

Getting following error for createSchema function:
**java.lang.NoSuchMethodError: java.util.concurrent.ConcurrentHashMap.keySet()Ljava/util/concurrent/ConcurrentHashMap$KeySetView**;
        at com.orientechnologies.common.concur.lock.OReadersWriterSpinLock.releaseWriteLock(OReadersWriterSpinLock.java:178)
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.addCluster(OAbstractPaginatedStorage.java:686)
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.addCluster(ODatabaseDocumentTx.java:1380)
        at com.orientechnologies.orient.core.metadata.schema.OSchemaShared.createClusters(OSchemaShared.java:1235)
        at com.orientechnologies.orient.core.metadata.schema.OSchemaShared.doCreateClass(OSchemaShared.java:991)
        at com.orientechnologies.orient.core.metadata.schema.OSchemaShared.createClass(OSchemaShared.java:379)
        at com.orientechnologies.orient.core.metadata.schema.OSchemaShared.createClass(OSchemaShared.java:364)
        at com.orientechnologies.orient.core.metadata.schema.OSchemaProxy.createClass(OSchemaProxy.java:96)

This was working fine for orientdb version 2.2.29.
Now we are using 2.2.34 and getting this error. Please let us know what should be done to avoid such exception.

**Comment by shubhambondarde** [comment]
Any update on this issue? when and in which version we will get fix for this?

**Comment by laa** [comment]
@luigidellaquila the problem is that distributions which we do are compiled on Java 8. And Java 8 supports overloading of return types. This method, keySet returns in Java 8 different real value than in Java 6. That is why we see this exception. Could we provide an official update of latest ODB using Java 6 compiler?

**Comment by shubhambondarde** [comment]
Hi @laa and @luigidellaquila,
Can you please let us know when and in which version can we get this fix?

**Comment by laa** [comment]
Closed because we do not support 2.x versions.
