### ISSUE TITLE
Unable to make public long com.sun.management.internal.OperatingSystemImpl.getTotalPhysicalMemorySize() accessible: module jdk.management does not "opens com.sun.management.internal" to unnamed module

### ISSUE THREAD

**Issue by StrangeTcy** [orientechnologies/orientdb#8359]
### OrientDB Version: 
Community 3.0.2

### Java Version:
openjdk version "10.0.1" 2018-04-17
OpenJDK Runtime Environment (build 10.0.1+10)
OpenJDK 64-Bit Server VM (build 10.0.1+10, mixed mode)

### OS: 
Ubuntu 16.04 x64 

## Expected behavior  
The server would be started and a prompt for a password would appear

## Actual behavior  
```
2018-06-24 16:59:56:333 INFO  Loading configuration from: /opt/orientdb/config/orientdb-server-config.xml... [OServerConfigurationLoaderXml]WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.sun.xml.bind.v2.runtime.reflect.opt.Injector$1 (file:/opt/orientdb/lib/jaxb-impl-2.2.3-1.jar) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int)
WARNING: Please consider reporting this to the maintainers of com.sun.xml.bind.v2.runtime.reflect.opt.Injector$1
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release

2018-06-24 16:59:57:747 INFO  OrientDB Server v2.2.22 (build fb2b7d321ea8a5a5b18a82237049804aace9e3de) is starting up... [OServer]
2018-06-24 16:59:57:763 INFO  Databases directory: /opt/orientdb/databases [OServer]Error during initialization of engine 'plocal', engine will be removed
java.lang.reflect.InaccessibleObjectException: Unable to make public long com.sun.management.internal.OperatingSystemImpl.getTotalPhysicalMemorySize() accessible: module jdk.management does not "opens com.sun.management.internal" to unnamed module @7fe3240a
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:337)
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:281)
	at java.base/java.lang.reflect.Method.checkCanSetAccessible(Method.java:198)
	at java.base/java.lang.reflect.Method.setAccessible(Method.java:192)
	at com.orientechnologies.common.util.OMemory.getPhysicalMemorySize(OMemory.java:66)
	at com.orientechnologies.orient.core.engine.OMemoryAndLocalPaginatedEnginesInitializer.configureDefaultDiskCacheSize(OMemoryAndLocalPaginatedEnginesInitializer.java:80)
	at com.orientechnologies.orient.core.engine.OMemoryAndLocalPaginatedEnginesInitializer.configureDefaults(OMemoryAndLocalPaginatedEnginesInitializer.java:63)
	at com.orientechnologies.orient.core.engine.OMemoryAndLocalPaginatedEnginesInitializer.initialize(OMemoryAndLocalPaginatedEnginesInitializer.java:52)
	at com.orientechnologies.orient.core.engine.local.OEngineLocalPaginated.startup(OEngineLocalPaginated.java:56)
	at com.orientechnologies.orient.core.Orient.startEngine(Orient.java:881)
	at com.orientechnologies.orient.core.Orient.loadStorage(Orient.java:474)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.<init>(ODatabaseDocumentTx.java:172)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.<init>(ODatabaseDocumentTx.java:153)
	at com.orientechnologies.orient.server.OSystemDatabase.init(OSystemDatabase.java:151)
	at com.orientechnologies.orient.server.OSystemDatabase.<init>(OSystemDatabase.java:44)
	at com.orientechnologies.orient.server.OServer.initSystemDatabase(OServer.java:1283)
	at com.orientechnologies.orient.server.OServer.activate(OServer.java:350)
	at com.orientechnologies.orient.server.OServerMain$1.run(OServerMain.java:46)
Error during engine shutdown
java.lang.NullPointerException
	at com.orientechnologies.orient.core.engine.local.OEngineLocalPaginated.shutdown(OEngineLocalPaginated.java:115)
	at com.orientechnologies.orient.core.Orient.startEngine(Orient.java:887)
	at com.orientechnologies.orient.core.Orient.loadStorage(Orient.java:474)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.<init>(ODatabaseDocumentTx.java:172)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.<init>(ODatabaseDocumentTx.java:153)
	at com.orientechnologies.orient.server.OSystemDatabase.init(OSystemDatabase.java:151)
	at com.orientechnologies.orient.server.OSystemDatabase.<init>(OSystemDatabase.java:44)
	at com.orientechnologies.orient.server.OServer.initSystemDatabase(OServer.java:1283)
	at com.orientechnologies.orient.server.OServer.activate(OServer.java:350)
	at com.orientechnologies.orient.server.OServerMain$1.run(OServerMain.java:46)
com.orientechnologies.orient.core.exception.ODatabaseException: Error on opening database 'plocal:/opt/orientdb/databases/OSystem'
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.<init>(ODatabaseDocumentTx.java:192)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.<init>(ODatabaseDocumentTx.java:153)
	at com.orientechnologies.orient.server.OSystemDatabase.init(OSystemDatabase.java:151)
	at com.orientechnologies.orient.server.OSystemDatabase.<init>(OSystemDatabase.java:44)
	at com.orientechnologies.orient.server.OServer.initSystemDatabase(OServer.java:1283)
	at com.orientechnologies.orient.server.OServer.activate(OServer.java:350)
	at com.orientechnologies.orient.server.OServerMain$1.run(OServerMain.java:46)
Caused by: com.orientechnologies.orient.core.exception.OConfigurationException: Error on opening database: the engine 'plocal' was unable to start. URL was: plocal:/opt/orientdb/databases/OSystem. Registered engines was: [memory, remote, plocal]
	DB name="plocal:/opt/orientdb/databases/OSystem"
	at com.orientechnologies.orient.core.Orient.loadStorage(Orient.java:475)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.<init>(ODatabaseDocumentTx.java:172)
	... 6 more
```

## Steps to reproduce  
Download the community edition .gz
Extract it
`mv` the extracted directory to `/opt/orientdb`
`cd` there
try to `sudo bin/server.sh`

**Comment by luigidellaquila** [comment]
Hi @StrangeTcy 

From the logs I see it's OrientDB v 2.2.22, please upgrade to 2.2.36, it should be already fixed

Thanks

Luigi

**Comment by StrangeTcy** [comment]
Sorry, I'm confused. 

- I download, extract and copy an archive named orientdb 3.0.2 (that's the actual [link](https://s3.us-east-2.amazonaws.com/orientdb3/releases/3.0.2/orientdb-3.0.2.tar.gz) I use)
- I try to `sudo bin/server.sh` there
- I get errors that, among other things, indicate that the actual version of OrientDB is 2.2.22 and not 3.0.2 as I would (reasonably, I think) expect.

Anyway, try to do the same with OrientDB 2.2.36 didn't resolve the issue, unless I've done something wrong.

**Comment by StrangeTcy** [comment]
Update: a version that was provided in an archive that's pointed to by the "for any OS" link contains the 3.0.2 version, and it does work.
Still, I think that's confusing.

**Comment by luigidellaquila** [comment]
Hi @StrangeTcy 

Oh, got it, thank you very much for pointing it out, I'll fix the website

Thanks

Luigi

**Comment by luigidellaquila** [comment]
Hi @StrangeTcy 

I checked the website and everything seems to be OK.

So just to recollect the information, if you have a chance to use v 3.0.x I'd strongly suggest you to do so. For v 2.2.x we will do a check, probably there is an incompatibility with Java 10

Thanks

Luigi

**Comment by luigidellaquila** [comment]
Hi @StrangeTcy 

I just checked the source code and saw that OMemory.getPhysicalMemorySize() no longer exists in v 2.2.36, so it's unlikely that the error is the same.

Could you please post the error you obtain with latest version?

Thanks

Luigi
