### ISSUE TITLE
Strange field validation error?

### ISSUE THREAD

**Issue by hrstoyanov** [orientechnologies/orientdb#8367]
### OS: MacOS 

I have the following class schema definition:
```
-- Action for auditing.
CREATE CLASS    Action ;
CREATE PROPERTY Action.on                 DATETIME  (MANDATORY TRUE, DEFAULT "sysdate()", READONLY TRUE);
CREATE PROPERTY Action.user               LINK      User (READONLY TRUE);
-- [C]reate, [U]pdate, [D]elete, [V]iew  type of action.
CREATE PROPERTY Action.type               STRING    (READONLY TRUE, MANDATORY TRUE, NOTNULL);
CREATE PROPERTY Action.ipAddress          STRING (READONLY TRUE);
CREATE PROPERTY Action.dnsName            STRING (READONLY TRUE);
CREATE PROPERTY Action.networkDevice      Link NetworkDevice (READONLY TRUE);      -- The networked device (Computer/cellphone) from which the action was executed
CREATE PROPERTY Action.affected           LINKSET     (READONLY TRUE);             -- Affected objects
CREATE PROPERTY Action.oldValues          EMBEDDEDMAP (READONLY TRUE);             -- An optional, varied list of old values, <string,object>
CREATE PROPERTY Action.newValues          EMBEDDEDMAP (READONLY TRUE);             -- An optional, varied list of new values, <string,object>
CREATE PROPERTY Action.comment            STRING(READONLY TRUE);                   -- [Optional] Detail action description
```
I am definitely seting the ```Action.type``` filed as seen from this debugger snapshot:

-- See line 62 in the upper panel (the code)
-- See the variable dump in the lower panel - the value is clearly set as "C"
-- Also all other properties on the OElement action appear properly set!

<img width="1047" alt="screen shot 2018-07-01 at 7 57 51 pm" src="https://user-images.githubusercontent.com/5327044/42143305-4a1968cc-7d69-11e8-97f7-abf162078d35.png">

But when I save the Action object (line 70 in my code), I get the following  exception! __Why__???

```
com.orientechnologies.orient.core.exception.OValidationException: The field 'Action.type' is mandatory, but not found on record: Action{on:Sun Jul 01 19:49:10 PDT 2018}
        DB name="rehabowner.db"
        Error Code="4"
        DB name="rehabowner.db"
        Error Code="4"
        at sun.reflect.GeneratedConstructorAccessor1557.newInstance(Unknown Source)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at com.orientechnologies.orient.client.binary.OChannelBinaryAsynchClient.throwSerializedException(OChannelBinaryAsynchClient.java:318)
        at com.orientechnologies.orient.client.binary.OChannelBinaryAsynchClient.handleStatus(OChannelBinaryAsynchClient.java:275)
        at com.orientechnologies.orient.client.binary.OChannelBinaryAsynchClient.beginResponse(OChannelBinaryAsynchClient.java:191)
        at com.orientechnologies.orient.client.binary.OChannelBinaryAsynchClient.beginResponse(OChannelBinaryAsynchClient.java:153)
        at com.orientechnologies.orient.client.remote.OStorageRemote.beginResponse(OStorageRemote.java:1812)
        at com.orientechnologies.orient.client.remote.OS
```

**Comment by hrstoyanov** [comment]
@luigidellaquila I found the reason - not sure if it is a bug or not - __If this is a ODB bug, please fix it.__

Here is portion of my schema to help you understand:

```
-- Tracker, used for auditing. More fields are defined later after Action definition ...
CREATE CLASS Tracker ABSTRACT;

-- User is an authenticated human 
CREATE CLASS User EXTENDS V,Tracker ABSTRACT;
CREATE PROPERTY User.auth0Id        STRING; 
CREATE INDEX    User.auth0Id        UNIQUE_HASH_INDEX STRING; -- From Auth0
CREATE PROPERTY User.firstName      STRING (MANDATORY TRUE, NOTNULL);
CREATE PROPERTY User.middleName     STRING;
CREATE PROPERTY User.lastName       STRING (MANDATORY TRUE, NOTNULL);
CREATE PROPERTY User.namePrefix     STRING;
CREATE PROPERTY User.nameSuffix     STRING;
CREATE PROPERTY User.email          STRING (MANDATORY TRUE, NOTNULL);
CREATE PROPERTY User.phone          STRING;

-- Staffer is managing accounts.TODO
CREATE CLASS Staffer EXTENDS User;

-- Action for auditing.
CREATE CLASS    Action ;
CREATE PROPERTY Action.on                 DATETIME  (MANDATORY TRUE, DEFAULT "sysdate()", READONLY TRUE);
CREATE PROPERTY Action.user               LINK      User (READONLY TRUE);
-- [C]reate, [U]pdate, [D]elete, [V]iew  type of action.
CREATE PROPERTY Action.type               STRING    (READONLY TRUE, MANDATORY TRUE, NOTNULL);
CREATE PROPERTY Action.ipAddress          STRING (READONLY TRUE);
CREATE PROPERTY Action.dnsName            STRING (READONLY TRUE);
CREATE PROPERTY Action.networkDevice      Link NetworkDevice (READONLY TRUE);     
CREATE PROPERTY Action.affected           LINKSET     (READONLY TRUE);             
CREATE PROPERTY Action.oldValues          EMBEDDEDMAP (READONLY TRUE);             
CREATE PROPERTY Action.newValues          EMBEDDEDMAP (READONLY TRUE);             
CREATE PROPERTY Action.comment            STRING(READONLY TRUE);                   


--Tracker back-pointers to Action
CREATE PROPERTY Tracker.created          LINK Action;
CREATE PROPERTY Tracker.lastModified     LINK Action;
CREATE PROPERTY Tracker.deactivated      LINK Action;
```

You can barely see this in the screenshot, but at the code bottom I had this order of saving objects:
```
action.save();
stafferVertex.save();
```
Where the auditing Action (an Element) is linked through the Tracker with the Staffer (a user vertex)

This was causing the issue. I fixed the problem by switching the order of saving:
```
stafferVertex.save();
action.save();
```

**Comment by hrstoyanov** [comment]
@luigidellaquila interested to know what you think. What if I wrap the operations in a transaction, would the order still matter?

**Comment by luigidellaquila** [comment]
Hi @hrstoyanov 

Good question, it's definitely worth trying. 
In a transaction, the order of operations does not matter as in notx, so probably it will work fine

Thanks

Luigi
