### ISSUE TITLE
NullPointerException OPaginatedCluster.close

### ISSUE THREAD

**Issue by jamieb22** [orientechnologies/orientdb#8403]
### Java Version: 
java version "1.8.0_172"
Java(TM) SE Runtime Environment (build 1.8.0_172-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.172-b11, mixed mode)
### OS: <os here>  
Linux  4.4.0-116-generic #140-Ubuntu SMP Mon Feb 12 21:23:04 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
## Expected behavior  

Not expecting a null ptr on open db.

## Actual behavior  
om.orientechnologies.orient.core.exception.ODatabaseException: Cannot open database url=plocal:/var/opt/db/6f3acbfa-b92c-4f6c-aedc-3e465110264e/database/archiva$6f3acbfa-b92c-4f6c-aedc-3e465110264e^M
        DB name="archiva$6f3acbfa-b92c-4f6c-aedc-3e465110264e"
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.open(ODatabaseDocumentTx.java:295)
        at com.orientechnologies.orient.core.db.OPartitionedDatabasePool$DatabaseDocumentTxPooled.internalOpen(OPartitionedDatabasePool.java:450)
        at com.orientechnologies.orient.core.db.OPartitionedDatabasePool.openDatabase(OPartitionedDatabasePool.java:311)
        at com.orientechnologies.orient.core.db.OPartitionedDatabasePool.acquire(OPartitionedDatabasePool.java:269)
        at com.tinkerpop.blueprints.impls.orient.OrientBaseGraph.<init>(OrientBaseGraph.java:145)        at com.tinkerpop.blueprints.impls.orient.OrientTransactionalGraph.<init>(OrientTransactionalGraph.java:77)
        at com.tinkerpop.blueprints.impls.orient.OrientGraph.<init>(OrientGraph.java:135)
        at com.tinkerpop.blueprints.impls.orient.OrientGraphFactory$1.getGraph(OrientGraphFactory.java:85)
        at com.tinkerpop.blueprints.impls.orient.OrientGraphFactory.getTx(OrientGraphFactory.java:222)
       ..
Caused by: java.lang.NullPointerException: null
        at com.orientechnologies.orient.core.storage.impl.local.paginated.OPaginatedCluster.close(OPaginatedCluster.java:348)
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.open(OAbstractPaginatedStorage.java:308)
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.open(ODatabaseDocumentTx.java:259)

## Steps to reproduce  
<add here>

**Comment by laa** [comment]
Hi @jamieb22 that was an internal error, caused by the fact that you can not open DB, but the root cause of the issue that DB was not opened is different. You should see other stack traces too. Could send all of them?

**Comment by laa** [comment]
Actually environment was not initialized from this database, that was the cause of the issue. But we need to know why it was not initialized.
