### ISSUE TITLE
Cannot access database after setting wrong LOCALE for existing database

### ISSUE THREAD

**Issue by rornellas** [orientechnologies/orientdb#8423]
## Expected behavior  
The wrong LOCALE be ignored and a default one be set

## Actual behavior  
Error when trying to access database after wrong set of LOCALE information

## Steps to reproduce  
Create a database, fill with some data and then set LOCALE database option to "BR"

I am get the following stacktrace:

2018-07-20 22:13:20:229 WARNI Information about storage locale is undefined (country is undefined) default locale pt-br_BR will be used [OStorageConfigurationSegment]Exception `2DDE89C7` in storage `plocal:/opt/orientdb-3.0.4/databases/dtec`: 3.0.4 - Veloce (build 4578b51f72a55feaa0852bc8ddd52929011d956c, branch 3.0.x)
com.orientechnologies.orient.core.exception.OStorageException: Cannot open local storage '/opt/orientdb-3.0.4/databases/dtec' with mode=rw
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.open(OAbstractPaginatedStorage.java:437)
        at com.orientechnologies.orient.core.db.OrientDBEmbedded.openNoAuthenticate(OrientDBEmbedded.java:90)
        at com.orientechnologies.orient.core.db.OrientDBEmbedded.openNoAuthenticate(OrientDBEmbedded.java:49)
        at com.orientechnologies.orient.server.OServer.openDatabase(OServer.java:926)
        at com.orientechnologies.orient.server.OServer.openDatabase(OServer.java:898)
        at com.orientechnologies.orient.server.network.protocol.http.command.OServerCommandAuthenticatedDbAbstract.authenticate(OServerCommandAuthenticatedDbAbstract.java:162)
        at com.orientechnologies.orient.server.network.protocol.http.command.OServerCommandAuthenticatedDbAbstract.beforeExecute(OServerCommandAuthenticatedDbAbstract.java:122)
        at com.orientechnologies.orient.server.network.protocol.http.command.get.OServerCommandGetConnect.beforeExecute(OServerCommandGetConnect.java:50)
        at com.orientechnologies.orient.server.network.protocol.http.ONetworkProtocolHttpAbstract.service(ONetworkProtocolHttpAbstract.java:169)
        at com.orientechnologies.orient.server.network.protocol.http.ONetworkProtocolHttpAbstract.execute(ONetworkProtocolHttpAbstract.java:633)
        at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:82)
Caused by: java.lang.NullPointerException
        at java.util.Locale.<init>(Locale.java:648)
        at java.util.Locale.<init>(Locale.java:677)
        at com.orientechnologies.orient.core.config.OStorageConfigurationImpl.getLocaleInstance(OStorageConfigurationImpl.java:347)
        at com.orientechnologies.orient.core.storage.impl.local.paginated.wal.ODiskWriteAheadLog.<init>(ODiskWriteAheadLog.java:208)
        at com.orientechnologies.orient.core.storage.impl.local.paginated.wal.ODiskWriteAheadLog.<init>(ODiskWriteAheadLog.java:128)
        at com.orientechnologies.orient.core.storage.impl.local.paginated.OLocalPaginatedStorage.initWalAndDiskCache(OLocalPaginatedStorage.java:497)
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.open(OAbstractPaginatedStorage.java:392)
        ... 10 more
Internal server error:

java.lang.NullPointerException
        at java.util.Locale.<init>(Locale.java:648)
        at java.util.Locale.<init>(Locale.java:677)
        at com.orientechnologies.orient.core.config.OStorageConfigurationImpl.getLocaleInstance(OStorageConfigurationImpl.java:347)
        at com.orientechnologies.orient.core.storage.impl.local.paginated.wal.ODiskWriteAheadLog.<init>(ODiskWriteAheadLog.java:208)
        at com.orientechnologies.orient.core.storage.impl.local.paginated.wal.ODiskWriteAheadLog.<init>(ODiskWriteAheadLog.java:128)
        at com.orientechnologies.orient.core.storage.impl.local.paginated.OLocalPaginatedStorage.initWalAndDiskCache(OLocalPaginatedStorage.java:497)
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.open(OAbstractPaginatedStorage.java:392)
        at com.orientechnologies.orient.core.db.OrientDBEmbedded.openNoAuthenticate(OrientDBEmbedded.java:90)
        at com.orientechnologies.orient.core.db.OrientDBEmbedded.openNoAuthenticate(OrientDBEmbedded.java:49)
        at com.orientechnologies.orient.server.OServer.openDatabase(OServer.java:926)
        at com.orientechnologies.orient.server.OServer.openDatabase(OServer.java:898)
        at com.orientechnologies.orient.server.network.protocol.http.command.OServerCommandAuthenticatedDbAbstract.authenticate(OServerCommandAuthenticatedDbAbstract.java:162)
        at com.orientechnologies.orient.server.network.protocol.http.command.OServerCommandAuthenticatedDbAbstract.beforeExecute(OServerCommandAuthenticatedDbAbstract.java:122)
        at com.orientechnologies.orient.server.network.protocol.http.command.get.OServerCommandGetConnect.beforeExecute(OServerCommandGetConnect.java:50)
        at com.orientechnologies.orient.server.network.protocol.http.ONetworkProtocolHttpAbstract.service(ONetworkProtocolHttpAbstract.java:169)
        at com.orientechnologies.orient.server.network.protocol.http.ONetworkProtocolHttpAbstract.execute(ONetworkProtocolHttpAbstract.java:633)

For god sake, help me.!

**Comment by rornellas** [comment]
Anyone? I am stuck at that point... If someone could just tell me where should I fix the locale to be able to access my database I would appreciate alot!

**Comment by laa** [comment]
Hi @rornellas could you try this build?

**Comment by rornellas** [comment]
Ok... I tried building orientdb core only and replaced my orientdb core jar by the new one. It worked!
Thank you!
I have executed a query and my database is working!

**Comment by laa** [comment]
https://drive.google.com/file/d/1hUESY2UFEuAFyV4wBCGGJDA5yGXkD81a/view?usp=sharing sorry forgot the link

**Comment by laa** [comment]
Cool :-)

**Comment by rornellas** [comment]
:)
Just to let you know... I have downloaded the file from googledrive, but when I try to run with the same command I used before, I get the following error:

-bash: ./server.sh: /bin/sh^M: bad interpreter: No such file or directory

If I try using bash:

: not found30: server.sh:
: not found33: server.sh:
server.sh: 91: server.sh: Syntax error: word unexpected (expecting "do")
