### ISSUE TITLE
Getting java.nio.BufferUnderflowException when querying

### ISSUE THREAD

**Issue by srini6teen** [orientechnologies/orientdb#8442]
## Expected behavior  
Query should perform without throwing ByteUnderflowException  

## Actual behavior  
Exception thrown while executing the below query. 

SELECT
FROM
(
	match { class: a, AS: a }	
  	.out('aTob') { AS: b, WHERE: (field1 is defined and field1 = true) }
        .out('bToC') { WHERE: (field2 = 'XYZ'), AS: c }
  	return a
)

This query works fine when I add a LIMIT of 121 records. 
If I add a limit of 122 or run the query without a limit, it throws "BufferUnderflowException"  

Stack Trace:
Exception `66F7FD08` in storage `plocal:/orientdb/databases/database-test`: 3.0.4 - Veloce (build 4578b51f72a55feaa0852bc8ddd52929011d956c, branch 3.0.x)
java.nio.BufferUnderflowException
	at java.nio.DirectByteBuffer.get(DirectByteBuffer.java:271)
	at java.nio.ByteBuffer.get(ByteBuffer.java:715)
	at com.orientechnologies.orient.core.storage.impl.local.paginated.base.ODurablePage.getBinaryValue(ODurablePage.java:155)
	at com.orientechnologies.orient.core.storage.impl.local.paginated.OClusterPage.getRecordBinaryValue(OClusterPage.java:376)
	at com.orientechnologies.orient.core.storage.impl.local.paginated.OPaginatedCluster.readFullEntry(OPaginatedCluster.java:1837)
	at com.orientechnologies.orient.core.storage.impl.local.paginated.OPaginatedCluster.internalReadRecord(OPaginatedCluster.java:700)
	at com.orientechnologies.orient.core.storage.impl.local.paginated.OPaginatedCluster.readRecord(OPaginatedCluster.java:667)
	at com.orientechnologies.orient.core.storage.impl.local.paginated.OPaginatedCluster.readRecord(OPaginatedCluster.java:649)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.doReadRecord(OAbstractPaginatedStorage.java:4547)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.readRecord(OAbstractPaginatedStorage.java:4223)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.readRecord(OAbstractPaginatedStorage.java:1605)
	at com.orientechnologies.orient.core.db.document.SimpleRecordReader.readRecord(SimpleRecordReader.java:21)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentAbstract.executeReadRecord(ODatabaseDocumentAbstract.java:1345)
	at com.orientechnologies.orient.core.tx.OTransactionNoTx.loadRecord(OTransactionNoTx.java:109)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentAbstract.load(ODatabaseDocumentAbstract.java:1114)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentAbstract.load(ODatabaseDocumentAbstract.java:84)
	at com.orientechnologies.orient.core.record.impl.ODocument.getProperty(ODocument.java:305)
	at com.orientechnologies.orient.core.record.impl.OEdgeDocument.getTo(OEdgeDocument.java:33)
	at com.orientechnologies.orient.core.record.impl.OEdgeToVertexIterator.next(OEdgeToVertexIterator.java:32)
	at com.orientechnologies.orient.core.record.impl.OEdgeToVertexIterator.next(OEdgeToVertexIterator.java:12)
	at com.orientechnologies.orient.core.sql.executor.MatchEdgeTraverser.traversePatternEdge(MatchEdgeTraverser.java:295)
	at com.orientechnologies.orient.core.sql.executor.MatchEdgeTraverser.executeTraversal(MatchEdgeTraverser.java:127)
	at com.orientechnologies.orient.core.sql.executor.MatchEdgeTraverser.init(MatchEdgeTraverser.java:98)
	at com.orientechnologies.orient.core.sql.executor.MatchEdgeTraverser.hasNext(MatchEdgeTraverser.java:35)
	at com.orientechnologies.orient.core.sql.executor.MatchStep.fetchNext(MatchStep.java:108)
	at com.orientechnologies.orient.core.sql.executor.MatchStep.access$000(MatchStep.java:13)
	at com.orientechnologies.orient.core.sql.executor.MatchStep$1.next(MatchStep.java:65)
	at com.orientechnologies.orient.core.sql.executor.MatchStep.fetchNext(MatchStep.java:103)
	at com.orientechnologies.orient.core.sql.executor.MatchStep.access$000(MatchStep.java:13)
	at com.orientechnologies.orient.core.sql.executor.MatchStep$1.next(MatchStep.java:65)
	at com.orientechnologies.orient.core.sql.executor.ProjectionCalculationStep$1.next(ProjectionCalculationStep.java:38)
	at com.orientechnologies.orient.core.sql.parser.OLocalResultSet.next(OLocalResultSet.java:69)
	at com.orientechnologies.orient.core.sql.parser.OLocalResultSetLifecycleDecorator.next(OLocalResultSetLifecycleDecorator.java:56)
	at com.orientechnologies.orient.server.network.protocol.http.command.post.OServerCommandPostCommand.execute(OServerCommandPostCommand.java:96)
	at com.orientechnologies.orient.server.network.protocol.http.command.post.OServerCommandPostCommandGraph.execute(OServerCommandPostCommandGraph.java:36)
	at com.orientechnologies.orient.server.network.protocol.http.ONetworkProtocolHttpAbstract.service(ONetworkProtocolHttpAbstract.java:172)
	at com.orientechnologies.orient.server.network.protocol.http.ONetworkProtocolHttpAbstract.execute(ONetworkProtocolHttpAbstract.java:633)
	at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:82)

**Comment by laa** [comment]
Hi @srini6teen could you send me the server logs and DB content. Do you have one?

**Comment by laa** [comment]
Hi @srini6teen could you send me the server logs and DB content. Do you have one?

**Comment by laa** [comment]
Hi, if this issue still actual please let us know otherwise we will close it.
