### ISSUE TITLE
OrientDB distributed-mode getVerticies() causes exception

### ISSUE THREAD

**Issue by berevesero** [orientechnologies/orientdb#8448]
### OS: <os here>  

Hello,

i running OrientDB in distributed mode with 4 nodes (dbis51, dbis52, dbis53, dbis54). I have two classes: `ridclass` and `tokenclass`. The `ridclass` has the property record as LONG and this property is also indexed as `unique`. I want to reach the following behavior:
If I create a record of the `ridclass` on a node with record property 1 (`ridclass.record = 1`), for example on node dbis52, I want to check later whether the record exists in the database or not. For indexing I use on node dbis53 the following method:

            tempRidVertex = graph.addVertex("ridclass", "ridcluster_dbis53");
            tempRidVertex.setProperty("record", "test");

 For checking whether the record exists I use the following:

            for (Vertex vertex : graph.getVertices("ridclass.record", 1)) {
                System.out.println("it exists!");
            }

My  `default-distributed-db-config.json` looks like this:

{
  "autoDeploy": true,
  "readQuorum": 1,
  "writeQuorum": "majority",
  "executionMode": "undefined",
  "readYourWrites": true,
  "newNodeStrategy": "dynamic",
  "servers": {
    "*": "master"
  },
  "clusters": {
    "internal": {
    },
    "ridcluster_dbis51":{
      "servers": [ "dbis51" ]
    },
    "ridcluster_dbis52":{
      "servers": [ "dbis52" ]
    },
    "ridcluster_dbis53":{
      "servers": [ "dbis53" ]
    },
    "ridcluster_dbis54":{
      "servers": [ "dbis54" ]
    },
    "tokencluster_dbis51":{
      "servers": [ "dbis51" ]
    },
    "tokencluster_dbis52":{
      "servers": [ "dbis52" ]
    },
    "tokencluster_dbis53":{
      "servers": [ "dbis53" ]
    },
    "tokencluster_dbis54":{
      "servers": [ "dbis54" ]
    },
    "*": {
      "servers": ["<NEW_NODE>"]
    }
  }
}

Now happens several strange things:
1. If I index a record the web frontend shows that there are still no records, also the console show this. But if I load a record with: load record 60:0 it shows me the corresponding record.

2. If I search for a specific record over the `ridclass.record` index my program freeze and OrientDB throws the following exceptions:

        2018-08-03 14:48:27:696 WARNI [dbis51] Error on sending message to distributed node     (java.io.NotSerializableException: com.orientechnologies.orient.core.sql.OSoftQueryResultList) retrying (1/3)
        2018-08-03 14:48:27:703 WARNI [dbis51] Error on sending message to distributed node (java.io.NotSerializableException: com.orientechnologies.orient.core.sql.OSoftQueryResultList) retrying (2/3)
        2018-08-03 14:48:28:110 WARNI [dbis51] Error on sending message to distributed node (java.io.NotSerializableException: com.orientechnologies.orient.core.sql.OSoftQueryResultList) retrying (3/3)[dbis51] Error on sending response 'com.orientechnologies.orient.core.sql.query.OBasicResultSet@1' back (reqId=0.44 err=com.orientechnologies.orient.server.distributed.ODistributedException: Cannot send response back to the sender node 'dbis51')
        com.orientechnologies.orient.server.distributed.ODistributedException: Cannot send response back to the sender node 'dbis51'
	        at com.orientechnologies.orient.server.distributed.ORemoteServerChannel.networkOperation(ORemoteServerChannel.java:215)
	        at com.orientechnologies.orient.server.distributed.ORemoteServerChannel.sendResponse(ORemoteServerChannel.java:103)
	        at com.orientechnologies.orient.server.distributed.ORemoteServerController.sendResponse(ORemoteServerController.java:74)
	        at com.orientechnologies.orient.server.distributed.impl.ODistributedWorker.sendResponseBack(ODistributedWorker.java:439)
	        at com.orientechnologies.orient.server.distributed.impl.ODistributedWorker.sendResponseBack(ODistributedWorker.java:413)
	        at com.orientechnologies.orient.server.distributed.impl.ODistributedWorker.onMessage(ODistributedWorker.java:399)
	        at com.orientechnologies.orient.server.distributed.impl.ODistributedWorker.run(ODistributedWorker.java:127)
       Caused by: java.io.NotSerializableException: com.orientechnologies.orient.core.sql.OSoftQueryResultList
	        at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1184)
	        at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1548)
	        at java.io.ObjectOutputStream.defaultWriteObject(ObjectOutputStream.java:441)
	        at java.util.Collections$SynchronizedCollection.writeObject(Collections.java:2081)
	        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
                at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	        at java.lang.reflect.Method.invoke(Method.java:498)
	        at java.io.ObjectStreamClass.invokeWriteObject(ObjectStreamClass.java:1128)
	        at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1496)
	        at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1432)
	        at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1178)
	        at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:348)
	        at com.orientechnologies.orient.core.sql.query.OBasicResultSet.writeExternal(OBasicResultSet.java:227)
	        at java.io.ObjectOutputStream.writeExternalData(ObjectOutputStream.java:1459)
	        at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1430)
	        at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1178)
	        at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:348)
	        at com.orientechnologies.orient.core.serialization.OStreamableHelper.toStream(OStreamableHelper.java:80)
	        at com.orientechnologies.orient.server.distributed.ODistributedResponse.toStream(ODistributedResponse.java:92)
	        at com.orientechnologies.orient.server.distributed.ORemoteServerChannel$2.execute(ORemoteServerChannel.java:106)
	        at com.orientechnologies.orient.server.distributed.ORemoteServerChannel.networkOperation(ORemoteServerChannel.java:166)
	        ... 6 more

         2018-08-03 14:50:27:673 WARNI [dbis51] Timeout (120001ms) on waiting for synchronous responses from nodes=[dbis51] responsesSoFar=[] request=(id=0.44 task=command_sql(select EXPAND( rid ) from index:ridclass.record where key = ?))

Maybe someone has an idea for this problem or why this happens?

Kind regards
Sedir Mohammed

**Comment by adler4566** [comment]
If I insert the vertices like this:

        OrientVertex tempRidVertex = graph.addVertex("class:ridclass");

The vertices are shown in the web frontend and in the console, and additionally I can search over the index but it has an other big problem! All vertices are stored on cluster '58' and this is namely my dbis51... It makes no difference if I index the vertices on server dbis52, dbis53, or dbis54, they are still stored on dbis51.
Maybe my config is wrong?

Kind regards
Sedir Mohammed

**Comment by cloudloveseven** [comment]
hi,adler4566, I want to know how you deal the Split brain of distribute cluster?   "From time to time server nodes go down. This does not necessarily relate to problems in OrientDB, (for instance, it could originate from limitations in system resources)"

**Comment by adler4566** [comment]
Hey @cloudloveseven, I'm sorry, but I'm not sure if i Understand your question.... I have a 4 node cluster, and each node has 23 GB ram and 24 cores, so I can't imagine that the system is not powerful enough.

The splitting works like that I have the records on one node, and I want to save all these records local on this node. Because of this I Use the following statement on node "dbis53":

        tempRidVertex = graph.addVertex("ridclass", "ridcluster_dbis53");
        tempRidVertex.setProperty("record", "test");
