### ISSUE TITLE
ODB server annoying startup exception

### ISSUE THREAD

**Issue by hrstoyanov** [orientechnologies/orientdb#8450]
### OS: any

Starting ODB server, directly after building it from sources gives me this (potentially harmless, but annoying) trace:
```
Can't load log handler "java.util.logging.FileHandler"
java.nio.file.NoSuchFileException: ..\log\orient-server.log.0.lck
java.nio.file.NoSuchFileException: ..\log\orient-server.log.0.lck
        at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:79)
        at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:97)
        at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:102)
        at sun.nio.fs.WindowsFileSystemProvider.newFileChannel(WindowsFileSystemProvider.java:115)
        at java.nio.channels.FileChannel.open(FileChannel.java:287)
        at java.nio.channels.FileChannel.open(FileChannel.java:335)
        at java.util.logging.FileHandler.openFiles(FileHandler.java:478)
        at java.util.logging.FileHandler.<init>(FileHandler.java:281)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at java.lang.Class.newInstance(Class.java:442)
        at java.util.logging.LogManager$5.run(LogManager.java:966)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.util.logging.LogManager.loadLoggerHandlers(LogManager.java:958)
        at java.util.logging.LogManager.initializeGlobalHandlers(LogManager.java:1578)
        at java.util.logging.LogManager.access$1500(LogManager.java:145)
        at java.util.logging.LogManager$RootLogger.accessCheckedHandlers(LogManager.java:1667)
        at java.util.logging.Logger.getHandlers(Logger.java:1777)
        at java.util.logging.Logger.log(Logger.java:735)
        at com.orientechnologies.common.log.OLogManager.log(OLogManager.java:188)
        at com.orientechnologies.common.log.OLogManager.infoNoDb(OLogManager.java:219)
        at com.orientechnologies.common.jna.ONative.getOpenFilesLimit(ONative.java:114)
        at com.orientechnologies.orient.core.engine.local.OEngineLocalPaginated.getOpenFilesLimit(OEngineLocalPaginated.java:63)
        at com.orientechnologies.orient.core.engine.local.OEngineLocalPaginated.<init>(OEngineLocalPaginated.java:48)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at java.lang.Class.newInstance(Class.java:442)
        at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:380)
        at java.util.ServiceLoader$LazyIterator.next(ServiceLoader.java:404)
        at java.util.ServiceLoader$1.next(ServiceLoader.java:480)
        at com.orientechnologies.orient.core.Orient.registerEngines(Orient.java:362)
        at com.orientechnologies.orient.core.Orient.startup(Orient.java:284)
        at com.orientechnologies.orient.core.Orient.startUp(Orient.java:200)
        at com.orientechnologies.orient.core.Orient.instance(Orient.java:185)
        at com.orientechnologies.orient.server.OServer.<init>(OServer.java:111)
        at com.orientechnologies.orient.server.OServerMain.create(OServerMain.java:28)
        at com.orientechnologies.orient.server.OServerMain$1.run(OServerMain.java:47)
```

**Comment by OrientDBColin** [comment]
Hi @hrstoyanov, I've noticed this myself and also find it a bit annoying.  It can make a user think there's a serious problem on start-up when there's not.  I'll see what we can do about it.

**Comment by hrstoyanov** [comment]
@luigidellaquila can you help?

**Comment by OrientDBColin** [comment]
Hi @hrstoyanov.  I looked into this and discovered that it's related to orientdb-server-log.properties and this property:

java.util.logging.FileHandler.pattern=../log/orient-server.log

If you start OrientDB from its top-level directory (bin\server.bat), the startup exception is thrown.

You have two options: 1) Start from the bin directory and just run server.bat, 2) Change the FileHandler.pattern to ./log/orient-server.log.

**Comment by hrstoyanov** [comment]
Thank you!
I was starting from the root: '''bin\server.bat'''
