### ISSUE TITLE
Unexpected java.lang.ClassCastException 

### ISSUE THREAD

**Issue by hrstoyanov** [orientechnologies/orientdb#8463]
### OS: MacOs  

What does the below exception mean and why am i getting it?

I have this piece of code, where I try to store in the "affected" field a vertex and an edges.
```
...
CREATE PROPERTY Action.affected   LINKSET  (READONLY TRUE); 
...
public void  affects(OElement... affected) {
            action.setProperty("affected", affected);
}
```

```
Caused by: java.lang.ClassCastException: com.orientechnologies.orient.core.record.impl.OEdgeDelegate cannot be cast to com.orientechnologies.orient.core.record.ORecordAbstract
        at com.orientechnologies.orient.core.record.ORecordInternal.addIdentityChangeListener(ORecordInternal.java:111)
        at com.orientechnologies.orient.core.db.record.ORecordLazySet.add(ORecordLazySet.java:132)
        at com.orientechnologies.orient.core.db.record.ORecordLazySet.add(ORecordLazySet.java:44)
        at com.orientechnologies.orient.core.record.impl.ODocumentHelper.convertField(ODocumentHelper.java:139)
        at com.orientechnologies.orient.core.record.impl.ODocument.setProperty(ODocument.java:413)
        at com.orientechnologies.orient.core.record.impl.ODocument.setProperty(ODocument.java:354)

```

**Comment by hrstoyanov** [comment]
Hi @luigidellaquila 
I does look like a bug, indeed.

The Action element is for keeping an audit trail of various "actions" in the system and looks like this:
```
CREATE CLASS    Action ;
CREATE PROPERTY Action.on                 DATETIME  (MANDATORY TRUE, DEFAULT "sysdate()", READONLY TRUE);
CREATE PROPERTY Action.user               LINK      User (READONLY TRUE);
CREATE PROPERTY Action.type               STRING    (READONLY TRUE); -- [C]reate, [U]pdate, [D]elete, [V]iew, [O]ther  type of action.
CREATE PROPERTY Action.ipAddress          STRING (READONLY TRUE);
CREATE PROPERTY Action.dnsName            STRING (READONLY TRUE);
CREATE PROPERTY Action.networkDevice      Link NetworkDevice (READONLY TRUE);      -- The networked device (Computer/cellphone) from which the action was executed
CREATE PROPERTY Action.affected           LINKSET     (READONLY TRUE);             -- Affected objects
CREATE PROPERTY Action.oldValues          EMBEDDEDMAP (READONLY TRUE);             -- An optional, varied list of old values, <string,object>
CREATE PROPERTY Action.newValues          EMBEDDEDMAP (READONLY TRUE);             -- An optional, varied list of new values, <string,object>
CREATE PROPERTY Action.comment            STRING(READONLY TRUE);                   -- [Optional] Detail action description
```

The exact Java code is:
```
new ActionDAO
                        .Builder(session)
                        .ofType(Action.Type.C)
                        .byUser(userVertex)
                        .affects(accountVertex, worksForEdge)
                        .fromHttpRequest(httpRequest, session)
                        .withComment("Created Stripe customer and subscription")
                        .withNewValues(new ActionDAO.ValuesBuilder()
                                .add("created by:", auth0Id)
                                .add("Stripe customer id:", customer.getId())
                                .add("Stripe subscription id:", subscription.getId()))
                        .build()
                        .save();
```

but it boils down to:
```
...
action = session.newElement("Action");
...

public Builder affects(OElement... affected) {
            action.setProperty("affected", affected);
            return this;
        }
...
```

Note, if I do not use the ```affected``` field, the action would be persisted successfully.

**Comment by luigidellaquila** [comment]
Hi @hrstoyanov 

Probably it depends on the fact that OrientDB does not manage Object[] properties.
You can try the following:

```
        public Builder affects(OElement... affected) {
            action.setProperty("affected", Arrays.asList(affected));
            return this;
        }
```

Thanks

Luigi

**Comment by hrstoyanov** [comment]
@luigidellaquila 
Confirmed, the work-around with collections works! I still feel that if you let arrays fail with obscure runtime exceptions like in my example, you have a gap in the API, but I will let you decide if you want to work on this issue or close it.

Thanks

**Comment by luigidellaquila** [comment]
Hi @hrstoyanov 

I guess we can add an explicit check there and throw an explicit exception

Thanks

Luigi

**Comment by hrstoyanov** [comment]
@luigidellaquila 
This issse is back again with 3.0.10 and the workaround we discussed before:

```
CREATE PROPERTY Action.affected  LINKSET  (READONLY TRUE);   -- Affected objects
...
 public Builder affects(OElement... affected) {
    action.setProperty("affected", Arrays.asList(affected));
    return this;
 }
```

 no longer works, here is what I get:

```
Caused by: java.lang.ClassCastException: com.orientechnologies.orient.core.record.impl.OEdgeDelegate cannot be cast to com.orientechnologies.orient.core.record.ORecordAbstract
        at com.orientechnologies.orient.core.record.ORecordInternal.addIdentityChangeListener(ORecordInternal.java:111)
        at com.orientechnologies.orient.core.db.record.ORecordLazySet.add(ORecordLazySet.java:132)
        at com.orientechnologies.orient.core.db.record.ORecordTrackedSet.addAll(ORecordTrackedSet.java:118)
        at com.orientechnologies.orient.core.record.impl.ODocumentHelper.convertField(ODocumentHelper.java:145)
        at com.orientechnologies.orient.core.record.impl.ODocument.setProperty(ODocument.java:413)
        at com.orientechnologies.orient.core.record.impl.ODocument.setProperty(ODocument.java:354)
        at com.recres.web.server.dao.ActionDAO$Builder.affects(ActionDAO.java:105)
        at com.recres.web.server.AccountSvcImpl.subscribe(AccountSvcImpl.java:85)
        ... 8 more
```

**Comment by luigidellaquila** [comment]
Ok, I think I got the problem, I'm fixing it now

Thanks

Luigi

**Comment by luigidellaquila** [comment]
Hi @hrstoyanov 

I just pushed a fix for this last problem, now it should be OK

Thanks

Luigi

**Comment by hrstoyanov** [comment]
hm .. i am still seeing the error in the 3.0.x branch:
```
Caused by: java.lang.ClassCastException: com.orientechnologies.orient.core.record.impl.OEdgeDelegate cannot be cast to com.orientechnologies.orient.core.record.ORecordAbstract
        at com.orientechnologies.orient.core.record.ORecordInternal.addIdentityChangeListener(ORecordInternal.java:111)
        at com.orientechnologies.orient.core.db.record.ORecordLazySet.add(ORecordLazySet.java:132)
        at com.orientechnologies.orient.core.db.record.ORecordTrackedSet.addAll(ORecordTrackedSet.java:118)
        at com.orientechnologies.orient.core.record.impl.ODocumentHelper.convertField(ODocumentHelper.java:145)
        at com.orientechnologies.orient.core.record.impl.ODocument.setProperty(ODocument.java:413)
        at com.orientechnologies.orient.core.record.impl.ODocument.setProperty(ODocument.java:354)
        at com.recres.web.server.dao.ActionDAO$Builder.affects(ActionDAO.java:105)
        at com.recres.web.server.AccountSvcImpl.subscribe(AccountSvcImpl.java:85)
```
