### ISSUE TITLE
traversedVertex triggers ClassCastException ArrayDeque -> List

### ISSUE THREAD

**Issue by sigurdurm** [orientechnologies/orientdb#8474]
## Expected behavior  
SQL command, that contains traversedVertex(), executes without problems.

## Actual behavior  
```
com.orientechnologies.orient.core.exception.OCommandExecutionException: ...
Caused by: java.lang.ClassCastException: java.util.ArrayDeque cannot be cast to java.util.List
```

## Steps to reproduce  
We had a SQL command that workes fine on OrientDB v2.2.32, but gives an Exception in OrientDB v3:
```
select $depth as degrees, traversedVertex(-1,14) as vertexes from (traverse both('IS') from #1849:0 maxdepth 14)
```

The command above works fine in the **Studio**, but fails when executing the command like this in code:
`tenant.getTenantGraph().command(new OCommandSQL(queryString)).execute()`

## Exception
```
2018-08-20 11:35:59.302 ERROR   --- [           main] c.o.o.c.s.i.memory.ODirectMemoryStorage  : Exception `46612BFC` in storage `memory:test`: 3.0.6 - Veloce (build b63614ab180ff02b75d65054b2a77116c16c0a3c, branch 3.0.x)

com.orientechnologies.orient.core.exception.OCommandExecutionException: Error on execution of command: sql.select $depth as degrees, traversedVertex(-1,14) as vertexes from (traverse both('IS') from #1849:0 maxdepth 14)
	DB name="test"

	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.executeCommand(OAbstractPaginatedStorage.java:3807)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.command(OAbstractPaginatedStorage.java:3723)
	at com.orientechnologies.orient.core.command.OCommandRequestTextAbstract.execute(OCommandRequestTextAbstract.java:68)
	at com.tinkerpop.blueprints.impls.orient.OrientGraphCommand.execute(OrientGraphCommand.java:49)
	at com.activitystream.core.model.factories.ActivityStreamManager.getNetworkForQuery(ActivityStreamManager.java:344)
	at com.activitystream.core.model.factories.ActivityStreamManagerTest.runQuery(ActivityStreamManagerTest.java:203)
	at com.activitystream.core.model.factories.ActivityStreamManagerTest.runQueryReturningASingleResult(ActivityStreamManagerTest.java:186)
	at com.activitystream.core.model.factories.ActivityStreamManagerTest.findsCustomerEventRelatedToEntity(ActivityStreamManagerTest.java:70)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:648)
	at org.testng.TestRunner.run(TestRunner.java:505)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
	at org.testng.SuiteRunner.run(SuiteRunner.java:364)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
	at org.testng.TestNG.runSuites(TestNG.java:1049)
	at org.testng.TestNG.run(TestNG.java:1017)
	at org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:72)
	at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:123)
Caused by: java.lang.ClassCastException: java.util.ArrayDeque cannot be cast to java.util.List
	at com.orientechnologies.orient.core.sql.functions.coll.OSQLFunctionTraversedElement.evaluate(OSQLFunctionTraversedElement.java:78)
	at com.orientechnologies.orient.core.sql.functions.coll.OSQLFunctionTraversedVertex.execute(OSQLFunctionTraversedVertex.java:40)
	at com.orientechnologies.orient.core.sql.functions.OSQLFunctionRuntime.execute(OSQLFunctionRuntime.java:128)
	at com.orientechnologies.orient.core.sql.ORuntimeResult.applyRecord(ORuntimeResult.java:127)
	at com.orientechnologies.orient.core.sql.ORuntimeResult.getProjectionResult(ORuntimeResult.java:261)
	at com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.addResult(OCommandExecutorSQLSelect.java:698)
	at com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.handleResult(OCommandExecutorSQLSelect.java:665)
	at com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.executeSearchRecord(OCommandExecutorSQLSelect.java:615)
	at com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.serialIterator(OCommandExecutorSQLSelect.java:1611)
	at com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.fetchFromTarget(OCommandExecutorSQLSelect.java:1557)
	at com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.executeSearch(OCommandExecutorSQLSelect.java:510)
	at com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.execute(OCommandExecutorSQLSelect.java:473)
	at com.orientechnologies.orient.core.sql.OCommandExecutorSQLDelegate.execute(OCommandExecutorSQLDelegate.java:74)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.executeCommand(OAbstractPaginatedStorage.java:3786)
	... 31 more

```

**Comment by luigidellaquila** [comment]
Hi @sigurdurm 

I'm fixing it now, but please consider that you are using a deprecated API, so you are running the query with the legacy SQL executor (this is why in Studio, that uses the new executor, it works fine).

Thanks

Luigi

**Comment by luigidellaquila** [comment]
Hi @sigurdurm 

I just pushed a fix, now it should be OK

Thanks

Luigi
