### ISSUE TITLE
Removing index causes exception

### ISSUE THREAD

**Issue by temilmg** [orientechnologies/orientdb#8484]
### OS: <linux>  

I have an SBTREE index on a datetime when that index is removed updates and inserts of records fail I get the following transaction exception (These exceptions persist until i restart the db server)

```
com.orientechnologies.orient.core.exception.OTransactionException: Cannot find index 'Data_activity__created' while committing transaction
DB name="data"
DB name="data"
at sun.reflect.GeneratedConstructorAccessor26.newInstance(Unknown Source)
at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
at com.orientechnologies.orient.client.binary.OChannelBinaryAsynchClient.throwSerializedException(OChannelBinaryAsynchClient.java:449)
at com.orientechnologies.orient.client.binary.OChannelBinaryAsynchClient.handleStatus(OChannelBinaryAsynchClient.java:400)
at com.orientechnologies.orient.client.binary.OChannelBinaryAsynchClient.beginResponse(OChannelBinaryAsynchClient.java:283)
at com.orientechnologies.orient.client.binary.OChannelBinaryAsynchClient.beginResponse(OChannelBinaryAsynchClient.java:167)
at com.orientechnologies.orient.client.remote.OStorageRemote.beginResponse(OStorageRemote.java:2362)
at com.orientechnologies.orient.client.remote.OStorageRemote$28.execute(OStorageRemote.java:1404)
at com.orientechnologies.orient.client.remote.OStorageRemote$28.execute(OStorageRemote.java:1377)
at com.orientechnologies.orient.client.remote.OStorageRemote$2.execute(OStorageRemote.java:206)
at com.orientechnologies.orient.client.remote.OStorageRemote.baseNetworkOperation(OStorageRemote.java:251)
at com.orientechnologies.orient.client.remote.OStorageRemote.networkOperationRetry(OStorageRemote.java:203)
at com.orientechnologies.orient.client.remote.OStorageRemote.networkOperation(OStorageRemote.java:214)
at com.orientechnologies.orient.client.remote.OStorageRemote.commit(OStorageRemote.java:1377)
at com.orientechnologies.orient.core.tx.OTransactionOptimistic.doCommit(OTransactionOptimistic.java:541)
at com.orientechnologies.orient.core.tx.OTransactionOptimistic.commit(OTransactionOptimistic.java:99)
at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.commit(ODatabaseDocumentTx.java:2922)
at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.commit(ODatabaseDocumentTx.java:2884)
at com.tinkerpop.blueprints.impls.orient.OrientTransactionalGraph.commit(OrientTransactionalGraph.java:182)
```

**Comment by temilmg** [comment]
OS: Linux

**Comment by temilmg** [comment]
if i use graph.getRawGraph().getMetadata().getIndexManager().reload(); before making a query then it works

**Comment by luigidellaquila** [comment]
Hi @temilmg 

How do you remove the index? Which API do you use?

Thanks

Luigi

**Comment by temilmg** [comment]
We use the java api. We have one admin client that sometimes changes some indices. In another application (using the same db) we do graph.getRawGraph().getMetadata().getIndexManager().reload();
before any insert, update or delete in order to avoid the above mentioned exception.

**Comment by luigidellaquila** [comment]
Hi @temilmg 

If I got it right, you are using v 2.2.x, so I suspect it's a structural problem in the synchronization of the schema with the client. We'll try to check it anyway.

If it's not the case, and you are using v 3.0 then it could be a much more trivial problem, so please let me know

Thanks

Luigi

**Comment by temilmg** [comment]
Sorry for the very late reply. We were using 2.2.x. 
I will close this issue since It hasn't been a big problem (reload of indexmanger worked)
