### ISSUE TITLE
orientdb start failed after stop ungracefully

### ISSUE THREAD

**Issue by dragon9783** [orientechnologies/orientdb#8507]
## Expected behavior  
OrientDB Server start up success

## Actual behavior  
OrientDB Server start failed

## Steps to reproduce  
Maybe OrientDB Server stop ungracefully

## Log to trace
```
2018-09-03 06:45:40:408 WARNI {db=metadata} Storage 'metadata' was not closed properly. Will try to recover from write ahead log...
2018-09-03 06:45:40:409 INFO  {db=metadata} Looking for last checkpoint...
2018-09-03 06:45:40:411 INFO  {db=metadata} FULL checkpoint found.
2018-09-03 06:45:40:411 INFO  {db=metadata} Data restore procedure from full checkpoint is started. Restore is performed from LSN LSN{segment=262, position=28}
2018-09-03 06:45:40:413 WARNI {db=metadata} Record com.orientechnologies.orient.core.storage.impl.local.paginated.wal.OCheckpointEndRecord{lsn=LSN{segment=262, position=52}} will be skipped during data restore
2018-09-03 06:45:40:413 INFO  {db=metadata} 1 operations were processed, current LSN is LSN{segment=262, position=52} last LSN is LSN{segment=262, position=52}$ANSI{green {db=metadata}} Exception during storage data restore
java.lang.NullPointerException
	at com.orientechnologies.orient.core.storage.impl.local.paginated.wal.ODiskWriteAheadLog.cutTill(ODiskWriteAheadLog.java:919)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.makeFullCheckpoint(OAbstractPaginatedStorage.java:3718)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.recoverIfNeeded(OAbstractPaginatedStorage.java:3920)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.open(OAbstractPaginatedStorage.java:294)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.open(ODatabaseDocumentTx.java:259)
	at com.orientechnologies.orient.server.OServer.openDatabaseBypassingSecurity(OServer.java:1006)
	at com.orientechnologies.orient.server.OServer.openDatabase(OServer.java:985)
	at com.orientechnologies.orient.server.OServer.openDatabase(OServer.java:958)
	at com.orientechnologies.orient.server.OServer.openDatabase(OServer.java:949)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.openDatabase(ONetworkProtocolBinary.java:914)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.handshakeRequest(ONetworkProtocolBinary.java:248)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.execute(ONetworkProtocolBinary.java:213)
	at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:82)
Exception `1ED188B2` in storage `plocal:/orientdb/databases/metadata`: 2.2.32 (build 68709d4478301dc6af110621f13fb176e4ca98b0, branch 2.2.x)
java.lang.NullPointerException
	at com.orientechnologies.orient.core.storage.impl.local.paginated.wal.ODiskWriteAheadLog.cutTill(ODiskWriteAheadLog.java:919)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.makeFullCheckpoint(OAbstractPaginatedStorage.java:3718)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.doClose(OAbstractPaginatedStorage.java:4397)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.close(OAbstractPaginatedStorage.java:580)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.open(OAbstractPaginatedStorage.java:316)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.open(ODatabaseDocumentTx.java:259)
	at com.orientechnologies.orient.server.OServer.openDatabaseBypassingSecurity(OServer.java:1006)
	at com.orientechnologies.orient.server.OServer.openDatabase(OServer.java:985)
	at com.orientechnologies.orient.server.OServer.openDatabase(OServer.java:958)
	at com.orientechnologies.orient.server.OServer.openDatabase(OServer.java:949)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.openDatabase(ONetworkProtocolBinary.java:914)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.handshakeRequest(ONetworkProtocolBinary.java:248)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.execute(ONetworkProtocolBinary.java:213)
	at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:82)
$ANSI{green {db=metadata}} Error during storage close
java.lang.NullPointerException
	at com.orientechnologies.orient.core.storage.impl.local.paginated.wal.ODiskWriteAheadLog.cutTill(ODiskWriteAheadLog.java:919)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.makeFullCheckpoint(OAbstractPaginatedStorage.java:3718)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.doClose(OAbstractPaginatedStorage.java:4397)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.close(OAbstractPaginatedStorage.java:580)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.open(OAbstractPaginatedStorage.java:316)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.open(ODatabaseDocumentTx.java:259)
	at com.orientechnologies.orient.server.OServer.openDatabaseBypassingSecurity(OServer.java:1006)
	at com.orientechnologies.orient.server.OServer.openDatabase(OServer.java:985)
	at com.orientechnologies.orient.server.OServer.openDatabase(OServer.java:958)
	at com.orientechnologies.orient.server.OServer.openDatabase(OServer.java:949)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.openDatabase(ONetworkProtocolBinary.java:914)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.handshakeRequest(ONetworkProtocolBinary.java:248)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.execute(ONetworkProtocolBinary.java:213)
	at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:82)
Exception `1081AF81` in storage `plocal:/orientdb/databases/metadata`: 2.2.32 (build 68709d4478301dc6af110621f13fb176e4ca98b0, branch 2.2.x)
com.orientechnologies.orient.core.exception.OStorageException: Cannot open local storage '/orientdb/databases/metadata' with mode=rw
	DB name="metadata"
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.open(OAbstractPaginatedStorage.java:323)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.open(ODatabaseDocumentTx.java:259)
	at com.orientechnologies.orient.server.OServer.openDatabaseBypassingSecurity(OServer.java:1006)
	at com.orientechnologies.orient.server.OServer.openDatabase(OServer.java:985)
	at com.orientechnologies.orient.server.OServer.openDatabase(OServer.java:958)
	at com.orientechnologies.orient.server.OServer.openDatabase(OServer.java:949)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.openDatabase(ONetworkProtocolBinary.java:914)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.handshakeRequest(ONetworkProtocolBinary.java:248)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.execute(ONetworkProtocolBinary.java:213)
	at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:82)
Caused by: java.lang.NullPointerException
	at com.orientechnologies.orient.core.storage.impl.local.paginated.wal.ODiskWriteAheadLog.cutTill(ODiskWriteAheadLog.java:919)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.makeFullCheckpoint(OAbstractPaginatedStorage.java:3718)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.recoverIfNeeded(OAbstractPaginatedStorage.java:3920)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.open(OAbstractPaginatedStorage.java:294)
	... 9 more
```

**Comment by laa** [comment]
Closed because we do not support 2.x versions.

**Comment by robinZhao** [comment]
current problem on 3.0.22
