### ISSUE TITLE
How to fix brokenRids while merging databases?

### ISSUE THREAD

**Issue by cegprakash** [orientechnologies/orientdb#8518]
### OS: 18.04

I tried to do import few nodes(classes) from a database to another database. 

## Expected behavior  
Databases should get merged

## Actual behavior  
But I get brokenRid error. How can I fix it?

Here is the error I get after I import
```
Total links updated: 14,672

Done. Imported 14,562 records in 12.99 secs
Error on database import happened just before line 0, column 3160367
com.orientechnologies.orient.core.db.tool.ODatabaseImportException: Invalid format. Found unsupported tag 'brokenRids'
    at com.orientechnologies.orient.core.db.tool.ODatabaseImport.importDatabase(ODatabaseImport.java:190)
    at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.importDatabase(ONetworkProtocolBinary.java:3003)
    at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.executeRequest(ONetworkProtocolBinary.java:721)
    at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.sessionRequest(ONetworkProtocolBinary.java:399)
    at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.execute(ONetworkProtocolBinary.java:218)
    at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:82)

Error: com.orientechnologies.common.io.OIOException

Error: java.io.EOFException
```
## Steps to reproduce  
Just try to import a database in an existing database which already has some data using -merge=true option.

**Comment by markodjurovic** [comment]
Hi @cegprakash 
thank you for reporting this. Fix for this issue will be in 2.2.38 (as also in 3.0.8). Or it can be built right now from from source code using appropriate branch (2.2.x and 3.0.x).
