### ISSUE TITLE
[BUG] order by exception

### ISSUE THREAD

**Issue by lightjiao** [orientechnologies/orientdb#8529]
## Problem sql
select from v_instance_ipaddr order by _order_name asc limit 10 

## Expected behavior  
return right and no exception

## Actual behavior  
got a exception
```
$ANSI{green {db=cmdb_org_3333}} Exception `5F12F191` in storage `cmdb_org_3333`
com.orientechnologies.orient.core.exception.OCommandExecutionException: Error on execution of command: sql.select from v_instance_ipaddr order by _order_name asc limit 10
DB name="cmdb_org_3333"
at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.executeCommand(OAbstractPaginatedStorage.java:3361)
at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.command(OAbstractPaginatedStorage.java:3278)
at com.orientechnologies.orient.core.command.OCommandRequestTextAbstract.execute(OCommandRequestTextAbstract.java:69)
at com.orientechnologies.orient.server.network.protocol.http.command.post.OServerCommandPostCommand.execute(OServerCommandPostCommand.java:106)
at com.orientechnologies.orient.graph.server.command.OServerCommandPostCommandGraph.execute(OServerCommandPostCommandGraph.java:37)
at com.orientechnologies.orient.server.network.protocol.http.ONetworkProtocolHttpAbstract.service(ONetworkProtocolHttpAbstract.java:173)
at com.orientechnologies.orient.server.network.protocol.http.ONetworkProtocolHttpAbstract.execute(ONetworkProtocolHttpAbstract.java:629)
at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:81)
Caused by: java.lang.IllegalArgumentException: Comparison method violates its general contract!
at java.util.TimSort.mergeHi(TimSort.java:899)
at java.util.TimSort.mergeAt(TimSort.java:516)
at java.util.TimSort.mergeForceCollapse(TimSort.java:457)
at java.util.TimSort.sort(TimSort.java:254)
at java.util.Arrays.sort(Arrays.java:1512)
at java.util.ArrayList.sort(ArrayList.java:1462)
at java.util.Collections.sort(Collections.java:175)
at com.orientechnologies.orient.core.record.impl.ODocumentHelper.sort(ODocumentHelper.java:84)
at com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.applySort(OCommandExecutorSQLSelect.java:2545)
at com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.applyOrderBy(OCommandExecutorSQLSelect.java:2533)
at com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.applyPartialOrderBy(OCommandExecutorSQLSelect.java:836)
at com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.addResult(OCommandExecutorSQLSelect.java:772)
at com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.handleResult(OCommandExecutorSQLSelect.java:671)
at com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.executeSearchRecord(OCommandExecutorSQLSelect.java:627)
at com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.serialIterator(OCommandExecutorSQLSelect.java:1642)
at com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.fetchFromTarget(OCommandExecutorSQLSelect.java:1589)
at com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.executeSearch(OCommandExecutorSQLSelect.java:522)
at com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.execute(OCommandExecutorSQLSelect.java:485)
at com.orientechnologies.orient.core.sql.OCommandExecutorSQLDelegate.execute(OCommandExecutorSQLDelegate.java:70)
at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.executeCommand(OAbstractPaginatedStorage.java:3340)
... 7 more

```

## Here is my data
the class have 160770 ip address info, and the `_order_name` attribute is convert ip to int for special query and sort

**Comment by luigidellaquila** [comment]
Hi @lightjiao 

Is it possible that you have some string data (or other types) in "_order_name"?
Having a dataset to reproduce the issue would help a lot

Thanks

Luigi

**Comment by lightjiao** [comment]
Hi @luigidellaquila 
I create a property on `_order_name`, my problem solved ……

BUT this is still a bug, the sort code is not robust enough.

**Comment by jonsalvas** [comment]
Just in case this issue is still interesting for you. I had this issue today in 3.0.23. It is caused by schema-free fields which store different data (in my case sometimes int and sometimes long). I fixed this by executing the following command:
UPDATE TARGET set timestamp = timestamp.asLong()
