### ISSUE TITLE
running server in distributed mode

### ISSUE THREAD

**Issue by gilko1981** [orientechnologies/orientdb#8546]
## Expected behavior  
running orientDB cluster on two remote nodes successfully

## Actual behavior  
Got exception:
2018-09-17 13:47:55:090 INFO  [172.17.0.2]:2434 [orientdb] [3.8.4] Established socket connection between /172.17.0.2:60609 and /10.0.0.18:2424 [TcpIpConnectionManager][172.17.0.2]:2434 [orientdb] [3.8.4] Connection[id=1, /172.17.0.2:56121->/10.0.0.225:2424, endpoint=[10
.0.0.225]:2424, alive=false, type=NONE] closed. Reason: **Exception in NonBlockingSocketReader**  

## Steps to reproduce  
1. started docker machine:
`sudo docker run -d --name orient_data -p 2424:2424 -p 2480:2480 -e distributed=true -e ORIENTDB_HOME=/orientdb -e ORIENTDB_ROOT_PASSWORD=<password> -v /data/orient-db-data/config/:/orientdb/config/ -v /data/orient-db-data/databases/:/orientdb/databases/ -v /data/orient-db-data/backups:/orientdb/backups orientdb:2.2.35 /orientdb/bin/dserver.sh`

2. modified hazelcast.xml
```
		<join>
			<multicast enabled="false">
				<multicast-group>235.1.1.1</multicast-group>
				<multicast-port>2434</multicast-port>
			</multicast>
                        <tcp-ip enabled="true">
                             <member>10.0.0.18:2424</member>
                             <member>10.0.0.225:2424</member>
                        </tcp-ip>
		</join>
```

3. orientdb-server-config.xml:  

        <handler class="com.orientechnologies.orient.server.hazelcast.OHazelcastPlugin">
            <parameters>
                <parameter value="${distributed}" name="enabled"/>
                <parameter value="${ORIENTDB_HOME}/config/default-distributed-db-config.json" name="configuration.db.default"/>
                <parameter value="${ORIENTDB_HOME}/config/hazelcast.xml" name="configuration.hazelcast"/>
                <parameter value="node1537183215860" name="nodeName"/>
            </parameters>
        </handler>

**LOGS:**
```
2018-09-17 13:47:57:075 INFO  [172.17.0.2]:2434 [orientdb] [3.8.4] Connecting to /10.0.0.18:2424, timeout: 0, bind-any: true [InitConnectionTask]
2018-09-17 13:47:57:075 INFO  [172.17.0.2]:2434 [orientdb] [3.8.4] Connecting to /10.0.0.225:2424, timeout: 0, bind-any: true [InitConnectionTask]
2018-09-17 13:47:57:076 INFO  [172.17.0.2]:2434 [orientdb] [3.8.4] Established socket connection between /172.17.0.2:37891 and /10.0.0.18:2424 [TcpIpConnectionManager]
2018-09-17 13:47:57:077 INFO  [172.17.0.2]:2434 [orientdb] [3.8.4] Established socket connection between /172.17.0.2:42819 and /10.0.0.225:2424 [TcpIpConnectionManager]Error executing request
com.orientechnologies.common.io.OIOException: Impossible to read a chunk of length:553648127 max allowed chunk length:16777216 see NETWORK_BINARY_MAX_CONTENT_LENGTH settings
	at com.orientechnologies.orient.enterprise.channel.binary.OChannelBinary.readBytes(OChannelBinary.java:160)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.onBeforeOperationalRequest(ONetworkProtocolBinary.java:492)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.sessionRequest(ONetworkProtocolBinary.java:365)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.execute(ONetworkProtocolBinary.java:218)
	at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:82)
```

**Comment by arpitaagarwal** [comment]
I am using Orient 3.0.10 and facing same issue on concurrent write. I have created following setup -

2 node cluster
copied orientdb folder at 2 different locations and started ./dserver.sh file. Both nodes connected to each other through multicast
Using Person-FriendOf example code to write 10k Person-FriendOf-Person (vertex-edge-vertex). There are multiple threads writing same data each.
Person:name has unique index
It works well for 2 threads but as number of threads increases, it times out.
Getting following logs - Timeout (1244ms) on waiting for synchronous responses from nodes=[node2, node1] responsesSoFar=[node2] request=(id=1.105226 task=TxPhase1) [ODistributedDatabaseImpl]

Any clues?

**Comment by 340370** [comment]
Hi Guys,

I am facing the same issue in OrientDB 2.2.29 cluster setup. Please let me know in case we have got any workaround.

Thanks
Anupam
