### ISSUE TITLE
IllegalArgumentException: fromKey > toKey while iterateEntriesMinor

### ISSUE THREAD

**Issue by antonzherdev** [orientechnologies/orientdb#8573]
## Expected behavior  
No exception

## Actual behavior  
```
java.lang.IllegalArgumentException: fromKey > toKey
java.lang.IllegalArgumentException: fromKey > toKey
	at java.util.TreeMap$NavigableSubMap.<init>(TreeMap.java:1368)
	at java.util.TreeMap$AscendingSubMap.<init>(TreeMap.java:1855)
	at java.util.TreeMap.subMap(TreeMap.java:913)
	at com.orientechnologies.orient.core.tx.OTransactionIndexChanges.firstAndLastKeys(OTransactionIndexChanges.java:92)
	at com.orientechnologies.orient.core.index.OIndexTxAwareOneValue$PureTxBetweenIndexBackwardCursor.<init>(OIndexTxAwareOneValue.java:125)
	at com.orientechnologies.orient.core.index.OIndexTxAwareOneValue.iterateEntriesMinor(OIndexTxAwareOneValue.java:345)
```

## Steps to reproduce  
In a transaction add an item in an index. Call iterateEntriesMinor for the index with a kea lower than the added key.

Caused by the #7919 fix

**Comment by laa** [comment]
Fixed
