### ISSUE TITLE
NPE reading objects from DB after a crash

### ISSUE THREAD

**Issue by zerovian** [orientechnologies/orientdb#8588]
## Expected behavior  
After crash recovery database should not contain corrupted records.

## Actual behavior  
NPE

## Steps to reproduce  
After database is running for several minutes. I crashed it to test recover.  After a couple of minutes of reading/writing reads, received NPE.

Below is stack.  I'll also attach .zip file if github allows it.

13:06:02.551 [doWork: nbbedmbaker4.empty] ERROR com.orientechnologies.orient.core.storage.impl.local.paginated.OLocalPaginatedStorage - Exception `7299F6C2` in storage `plocal:c:\progress\oemgmt120\work\cachedb/cachedb`: 3.0.8 - Veloce (build ace6fe7e50f069968d2ec61678848606703db1c0, branch 3.0.x)
java.lang.NullPointerException: null
	at com.orientechnologies.orient.core.serialization.serializer.binary.impl.index.OCompositeKeySerializer.deserializeFromByteBufferObject(OCompositeKeySerializer.java:355)
	at com.orientechnologies.orient.core.serialization.serializer.binary.impl.index.OCompositeKeySerializer.deserializeFromByteBufferObject(OCompositeKeySerializer.java:42)
	at com.orientechnologies.orient.core.storage.impl.local.paginated.base.ODurablePage.deserializeFromDirectMemory(ODurablePage.java:182)
	at com.orientechnologies.orient.core.storage.index.sbtree.local.OSBTreeBucket.getKey(OSBTreeBucket.java:377)
	at com.orientechnologies.orient.core.storage.index.sbtree.local.OSBTreeBucket.find(OSBTreeBucket.java:137)
	at com.orientechnologies.orient.core.storage.index.sbtree.local.OSBTree.findBucket(OSBTree.java:1728)
	at com.orientechnologies.orient.core.storage.index.sbtree.local.OSBTree.iterateEntriesBetweenAscOrder(OSBTree.java:1453)
	at com.orientechnologies.orient.core.storage.index.sbtree.local.OSBTree.iterateEntriesBetween(OSBTree.java:964)
	at com.orientechnologies.orient.core.storage.index.engine.OSBTreeIndexEngine.iterateEntriesBetween(OSBTreeIndexEngine.java:188)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.doIterateIndexEntriesBetween(OAbstractPaginatedStorage.java:2989)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.iterateIndexEntriesBetween(OAbstractPaginatedStorage.java:2968)
	at com.orientechnologies.orient.core.index.OIndexMultiValues.iterateEntriesBetween(OIndexMultiValues.java:249)
	at com.orientechnologies.orient.core.index.OIndexAbstractDelegate.iterateEntriesBetween(OIndexAbstractDelegate.java:110)
	at com.orientechnologies.orient.core.index.OIndexTxAwareMultiValue.iterateEntriesBetween(OIndexTxAwareMultiValue.java:344)
	at com.orientechnologies.orient.core.sql.executor.FetchFromIndexStep.init(FetchFromIndexStep.java:361)
	at com.orientechnologies.orient.core.sql.executor.FetchFromIndexStep.processAndBlock(FetchFromIndexStep.java:302)
	at com.orientechnologies.orient.core.sql.executor.FetchFromIndexStep.init(FetchFromIndexStep.java:225)
	at com.orientechnologies.orient.core.sql.executor.FetchFromIndexStep.init(FetchFromIndexStep.java:206)
	at com.orientechnologies.orient.core.sql.executor.FetchFromIndexStep.syncPull(FetchFromIndexStep.java:71)
	at com.orientechnologies.orient.core.sql.executor.GetValueFromIndexEntryStep$1.fetchNextItem(GetValueFromIndexEntryStep.java:92)
	at com.orientechnologies.orient.core.sql.executor.GetValueFromIndexEntryStep$1.hasNext(GetValueFromIndexEntryStep.java:58)
	at com.orientechnologies.orient.core.sql.executor.FilterByClassStep$1.fetchNextItem(FilterByClassStep.java:50)
	at com.orientechnologies.orient.core.sql.executor.FilterByClassStep$1.hasNext(FilterByClassStep.java:88)
	at com.orientechnologies.orient.core.sql.parser.OLocalResultSet.fetchNext(OLocalResultSet.java:36)
	at com.orientechnologies.orient.core.sql.parser.OLocalResultSet.<init>(OLocalResultSet.java:29)
	at com.orientechnologies.orient.core.sql.parser.OSelectStatement.execute(OSelectStatement.java:271)
	at com.orientechnologies.orient.core.sql.parser.OStatement.execute(OStatement.java:62)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentEmbedded.command(ODatabaseDocumentEmbedded.java:540)
	at com.orientechnologies.orient.object.db.OObjectDatabaseTx.command(OObjectDatabaseTx.java:1151)
	at com.progress.isq.ipqos.activity.ActivityDataAccess.getList(ActivityDataAccess.java:277)
	at com.progress.isq.ipqos.activity.ActivityService.getList(ActivityService.java:250)
	at com.progress.isq.ipqos.activity.ActivityService.deleteResourceActivityGroupAndActivities(ActivityService.java:499)
	at com.progress.isq.ipqos.activity.ServiceAdapter.deleteResourceActivityGroupAndActivities(ServiceAdapter.java:186)
	at com.progress.isq.ipqos.resources.plugins.database.DatabaseActivityProcessor.delete(DatabaseActivityProcessor.java:1142)
	at com.progress.isq.ipqos.resources.plugins.database.DatabaseActivityProcessor.processAndCollectData(DatabaseActivityProcessor.java:1026)
	at com.progress.isq.ipqos.activity.MultiActivityServiceAdapter.processData(MultiActivityServiceAdapter.java:339)
	at com.progress.isq.ipqos.activity.MultiActivityServiceAdapter.processResponse(MultiActivityServiceAdapter.java:295)
	at com.progress.isq.ipqos.activity.MultiActivityServiceAdapter.processActivities(MultiActivityServiceAdapter.java:248)
	at com.progress.isq.ipqos.activity.MultiActivityServiceAdapter.processActivities(MultiActivityServiceAdapter.java:224)
	at com.progress.isq.ipqos.activity.MultiActivityServiceAdapter.fetchAndStoreActivities(MultiActivityServiceAdapter.java:137)
	at com.progress.isq.ipqos.resources.plugins.openedge.work.WorkRunnable.performPolling(WorkRunnable.java:75)
	at com.progress.isq.ipqos.resources.plugins.openedge.work.DatabaseInstWork.doWork(DatabaseInstWork.java:81)
	at com.progress.isq.ipqos.resources.plugins.database.DatabaseInstResource.doWork(DatabaseInstResource.java:519)
	at com.progress.isq.ipqos.ScheduledWorkShell.run(ScheduledWorkShell.java:130)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
13:06:02.552 [doWork: nbbedmbaker4.empty] ERROR Fathom - Unexpected exception occurred during resource polling for localhost:resource.database.local.empty
com.progress.isq.ipqos.WorkErrorException: null
	at com.progress.isq.ipqos.resources.plugins.openedge.work.WorkRunnable.performPolling(WorkRunnable.java:79)
	at com.progress.isq.ipqos.resources.plugins.openedge.work.DatabaseInstWork.doWork(DatabaseInstWork.java:81)
	at com.progress.isq.ipqos.resources.plugins.database.DatabaseInstResource.doWork(DatabaseInstResource.java:519)
	at com.progress.isq.ipqos.ScheduledWorkShell.run(ScheduledWorkShell.java:130)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException: null
	at com.orientechnologies.orient.core.serialization.serializer.binary.impl.index.OCompositeKeySerializer.deserializeFromByteBufferObject(OCompositeKeySerializer.java:355)
	at com.orientechnologies.orient.core.serialization.serializer.binary.impl.index.OCompositeKeySerializer.deserializeFromByteBufferObject(OCompositeKeySerializer.java:42)
	at com.orientechnologies.orient.core.storage.impl.local.paginated.base.ODurablePage.deserializeFromDirectMemory(ODurablePage.java:182)
	at com.orientechnologies.orient.core.storage.index.sbtree.local.OSBTreeBucket.getKey(OSBTreeBucket.java:377)
	at com.orientechnologies.orient.core.storage.index.sbtree.local.OSBTreeBucket.find(OSBTreeBucket.java:137)
	at com.orientechnologies.orient.core.storage.index.sbtree.local.OSBTree.findBucket(OSBTree.java:1728)
	at com.orientechnologies.orient.core.storage.index.sbtree.local.OSBTree.iterateEntriesBetweenAscOrder(OSBTree.java:1453)
	at com.orientechnologies.orient.core.storage.index.sbtree.local.OSBTree.iterateEntriesBetween(OSBTree.java:964)
	at com.orientechnologies.orient.core.storage.index.engine.OSBTreeIndexEngine.iterateEntriesBetween(OSBTreeIndexEngine.java:188)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.doIterateIndexEntriesBetween(OAbstractPaginatedStorage.java:2989)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.iterateIndexEntriesBetween(OAbstractPaginatedStorage.java:2968)
	at com.orientechnologies.orient.core.index.OIndexMultiValues.iterateEntriesBetween(OIndexMultiValues.java:249)
	at com.orientechnologies.orient.core.index.OIndexAbstractDelegate.iterateEntriesBetween(OIndexAbstractDelegate.java:110)
	at com.orientechnologies.orient.core.index.OIndexTxAwareMultiValue.iterateEntriesBetween(OIndexTxAwareMultiValue.java:344)
	at com.orientechnologies.orient.core.sql.executor.FetchFromIndexStep.init(FetchFromIndexStep.java:361)
	at com.orientechnologies.orient.core.sql.executor.FetchFromIndexStep.processAndBlock(FetchFromIndexStep.java:302)
	at com.orientechnologies.orient.core.sql.executor.FetchFromIndexStep.init(FetchFromIndexStep.java:225)
	at com.orientechnologies.orient.core.sql.executor.FetchFromIndexStep.init(FetchFromIndexStep.java:206)
	at com.orientechnologies.orient.core.sql.executor.FetchFromIndexStep.syncPull(FetchFromIndexStep.java:71)
	at com.orientechnologies.orient.core.sql.executor.GetValueFromIndexEntryStep$1.fetchNextItem(GetValueFromIndexEntryStep.java:92)
	at com.orientechnologies.orient.core.sql.executor.GetValueFromIndexEntryStep$1.hasNext(GetValueFromIndexEntryStep.java:58)
	at com.orientechnologies.orient.core.sql.executor.FilterByClassStep$1.fetchNextItem(FilterByClassStep.java:50)
	at com.orientechnologies.orient.core.sql.executor.FilterByClassStep$1.hasNext(FilterByClassStep.java:88)
	at com.orientechnologies.orient.core.sql.parser.OLocalResultSet.fetchNext(OLocalResultSet.java:36)
	at com.orientechnologies.orient.core.sql.parser.OLocalResultSet.<init>(OLocalResultSet.java:29)
	at com.orientechnologies.orient.core.sql.parser.OSelectStatement.execute(OSelectStatement.java:271)
	at com.orientechnologies.orient.core.sql.parser.OStatement.execute(OStatement.java:62)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentEmbedded.command(ODatabaseDocumentEmbedded.java:540)
	at com.orientechnologies.orient.object.db.OObjectDatabaseTx.command(OObjectDatabaseTx.java:1151)
	at com.progress.isq.ipqos.activity.ActivityDataAccess.getList(ActivityDataAccess.java:277)
	at com.progress.isq.ipqos.activity.ActivityService.getList(ActivityService.java:250)
	at com.progress.isq.ipqos.activity.ActivityService.deleteResourceActivityGroupAndActivities(ActivityService.java:499)
	at com.progress.isq.ipqos.activity.ServiceAdapter.deleteResourceActivityGroupAndActivities(ServiceAdapter.java:186)
	at com.progress.isq.ipqos.resources.plugins.database.DatabaseActivityProcessor.delete(DatabaseActivityProcessor.java:1142)
	at com.progress.isq.ipqos.resources.plugins.database.DatabaseActivityProcessor.processAndCollectData(DatabaseActivityProcessor.java:1026)
	at com.progress.isq.ipqos.activity.MultiActivityServiceAdapter.processData(MultiActivityServiceAdapter.java:339)
	at com.progress.isq.ipqos.activity.MultiActivityServiceAdapter.processResponse(MultiActivityServiceAdapter.java:295)
	at com.progress.isq.ipqos.activity.MultiActivityServiceAdapter.processActivities(MultiActivityServiceAdapter.java:248)
	at com.progress.isq.ipqos.activity.MultiActivityServiceAdapter.processActivities(MultiActivityServiceAdapter.java:224)
	at com.progress.isq.ipqos.activity.MultiActivityServiceAdapter.fetchAndStoreActivities(MultiActivityServiceAdapter.java:137)
	at com.progress.isq.ipqos.resources.plugins.openedge.work.WorkRunnable.performPolling(WorkRunnable.java:75)
	... 6 common frames omitted

**Comment by zerovian** [comment]
[cachedb.zip](https://github.com/orientechnologies/orientdb/files/2456933/cachedb.zip)

**Comment by zerovian** [comment]
FYI, this is running in embedded mode.

**Comment by zerovian** [comment]
In 2.2.x we used to run into similar issues where indexes were corrupt after a crash. we resorted to using "rebuild index on non-soft close" configuration option.  This appears to be deprecated in 3.x branch.

**Comment by laa** [comment]
Hi, we have made several changes to improve durability system, could you try on 3.0.9.

**Comment by zerovian** [comment]
Tried with 3.0.9.  Still getting NPE.  Now also getting arrayindexoutof bounds.  I've attached startup log and stacks from a few of the errors.

[orientdb_3.0.6_arrayindexoutofbounds_aftercrash.txt](https://github.com/orientechnologies/orientdb/files/2501961/orientdb_3.0.6_arrayindexoutofbounds_aftercrash.txt)

**Comment by zerovian** [comment]
In 3.0.8 forcing an index rebuild didn't fix the issue.  Now In 3.0.9, if I force an index rebuild all the errors go away.  Would still like index recovery to work better.

**Comment by zerovian** [comment]
I can reproduce every time with a new database on 3.0 9.  Every crash corrupts the indexes.  A rebuild fixes the errors.

**Comment by laa** [comment]
@zerovian I want to understand exact steps to reproduce it.

Could you send me instructions, which I can follow step by step to see the same?
As I understand from your comments you can reproduce it every time.

**Comment by zerovian** [comment]
Give me a week or so I'll try to extract enough of the app apart to create a test case out of it.  The app has lots of classes, lots of threads and lots of deletes/creates one each thread.



Scenario is I have a webapp running in Tomcat, with 2 embedded databases.  1 database is almost entirely read only and is rarely touched, other than to read from it.  Almost no writes.  The other database has lots of reads/creates/deletes...almost no updates.  (is being used as a time series database).  After running for several minutes I kill the Tomcat server and restart everything.  Crash recovery completes, no errors...after a short while I start getting the NPE and AIOB errors.   If I force an index rebuild (from within the app using java API's) after opening the database, no problems, everything is clean and smooth.  All writes to both databases are using transactions.

**Comment by zerovian** [comment]
updated to 3.0.10.  whatever this fix is "Fix potential non-completed atomic operatios" (from the 3.0.10 release notes) seems to have addressed the problem.  After multiple crashes and restarts with no explicit index rebuild, no NPEs or arrayindexoutofbounds errors were encountered.

Will close after some more testing.

**Comment by zerovian** [comment]
Closing. can no longer duplicate with 3.0.10

**Comment by laa** [comment]
@zerovian thank you very much for your feedback and help.
