### ISSUE TITLE
Live query crashes after new edge created

### ISSUE THREAD

**Issue by pcholder** [orientechnologies/orientdb#8594]
## Expected behavior  
 When i subscribe on any Entity (subclass of vertex), live query works normally even the edge between entity1 and entity2 created.

## Actual behavior  
All live queries opened in current ODatabaseSession crashes after new  edge created

`Exception in thread "Thread-3" com.orientechnologies.common.io.OIOException: Impossible to read a chunk of length:55703937 max allowed chunk length:16777216 see NETWORK_BINARY_MAX_CONTENT_LENGTH settings 
	at com.orientechnologies.orient.enterprise.channel.binary.OChannelBinary.readBytes(OChannelBinary.java:165)
	at com.orientechnologies.orient.core.serialization.serializer.result.binary.OResultSerializerNetwork.fromStream(OResultSerializerNetwork.java:655)
	at com.orientechnologies.orient.client.remote.message.OMessageHelper.readProjection(OMessageHelper.java:503)
	at com.orientechnologies.orient.client.remote.message.OMessageHelper.readResult(OMessageHelper.java:471)
	at com.orientechnologies.orient.client.remote.message.OLiveQueryPushRequest.read(OLiveQueryPushRequest.java:83)
	at com.orientechnologies.orient.client.remote.OStorageRemotePushThread.run(OStorageRemotePushThread.java:58)`

## Steps to reproduce  
1. Create vertex Entity class, liveSession, subscribe on Entity changes and any number of other changes.
2. open new session, create entity1, close session  // ok, event fired
3. open new session, create entity2, and edge(entity1, entity2), close session // -> after that all listeners 
4. open new session, create entity3.

Now all listeners from step 1 are not working.

Code to reproduce here:
https://github.com/pcholder/orientLiveQueryBug

May be i use orient in not properly manner, please help me.

**Comment by luigidellaquila** [comment]
Hi @pcholder 

I just pushed a fix for this issue, it will be released with v 3.0.9

Thanks

Luigi
