### ISSUE TITLE
LOGIN SESSION EXPIRED

### ISSUE THREAD

**Issue by octal-laurence** [orientechnologies/orientdb#8600]
### OS: Ubuntu 16.04 LTS  

I have created database from studio, and its working while creating schema (vertex) it keeps loading when saving.
**1st**.  I create vertex ('applicants'), It gives me an error Java (null)
**2nd**. Then if I refresh it, the created vertex ('applicant') is listed on the vertex classess, I dont know why, but I believe it shouldn't be there because upon creating the vertex it gives me an error.
**3rd** When I add vertex properties it keeps loading. nothings happen, if I refresh no properties was added.
**4th** After then I logout and reset the orientdb from my Ubuntu 16.04 LTS.
**5th** Then I log in again using same credentials I used before, then It cant log in it says session expired always. but my other databases is working.

![image](https://user-images.githubusercontent.com/40681919/46939347-f83bba80-d05d-11e8-86d0-c7a4a92c6eb6.png)

**Comment by mmacfadden** [comment]
@octal-laurence I don't know if it is related, but in 3.0.8 and 3.0.9 I have been having a similar issue where randomly the database users can't log in.  I have to log in as Root and remove the admin and writer users and re-add them with the same username, password, and roles.

When this happens are you able to still log into the database using the "root" username and password? If so, can you go to the security tab and delete the admin user and re-add it with the admin role, and the same password?  Can you then log in?

Just trying to see if we are having roughly the same issue.  I think some how the users are getting corrupted.

**Comment by octal-laurence** [comment]
Hi,
    the root credential isnt working at all and any credential I used its
not working. this happens to me 2nd time. it says "Session Expired"

Regards,
Geroy, John Laurence P.

**Comment by octal-laurence** [comment]
Hi,
    the root credential isnt working at all and any credential I used its not working. this happens to me 2nd time. it says "Session Expired"

Regards,
Geroy, John Laurence P.

**Comment by mmacfadden** [comment]
I assume the root credentials still work for the server as a whole. Meaning you can uses them to create and open other databases, even after the error occurs?

Is this database running locally?

If so you might try shutting down the OrientDB server. Then using the console.sh to open the database using the `plocal` url.  Then running check database.  These steps might not be exact but:

1. $ORIENTDB_HOME/bin/console.sh
2. connect plocal:/$ORIENTDB_HOME/databases/<my-broken-database> root <password>
3. CHECK DATABASE

This might tell you what is wrong.  You can read more about it here:

- [http://orientdb.com/docs/3.0.x/console/Console-Command-Check-Database.html](http://orientdb.com/docs/3.0.x/console/Console-Command-Check-Database.html)
- [http://orientdb.com/docs/3.0.x/console/Console-Commands.html](http://orientdb.com/docs/3.0.x/console/Console-Commands.html)

Lastly, if you look at the server logs in step 1 above, does it say anything more that Java (null)?

**Comment by mmacfadden** [comment]
@octal-laurence Wondering if you made any progress on this issue, or if you still need some help?

**Comment by octal-laurence** [comment]
Currently I havent figure it out yet, but I have a new Issue. on Drivers
Node js

>
I follow this sample from the docs, this 1 is saving binary data to
orientdb record.
[image: image.png]

then here is my code
[image: image.png]

when I execute this, the promise return method is keep loading nothing
happen on my node js, I didn't get the promise result from *rec* neither *err,
*however i'm pretty sure the other method from db.record is working like
get, update etc. except for this method *record.create(type b)*;

can you help me please.
my node js keep loading only ig to this.
[image: image.png]

**Comment by octal-laurence** [comment]
Hi, Re-opening this issue again. it happened again.

1. I was creating schema for my vertexes,
2. and then suddenly it keeps loading after saving my structure from scheme, then I hit refresh on my browser to reload the studio.
3.after that I can't login again is says "Session Expired", even I use the root user, I need help

**Comment by EngiNinja** [comment]
I have the same issue

**Comment by TheWizl** [comment]
I have the same issue

**Comment by TheWizl** [comment]
I have restarted the whole server and it doesn´t help

**Comment by big213** [comment]
I just experienced the same issue as described in the original post. After running an OrientDB server on 3.0.13 for 7 months without problems, I encountered some strange errors when I attempted to add some unique hash indexes on a vertex class, which seemed to happen for no apparent reason. First, it gave me a `java.lang.NullPointerException` error on the bottom whenever I did anything in the studio, and then whenever I tried to do anything, it gave me the same error. After I logged out to see if that would fix it, it did not let me log back in, giving the same exact error messages as shown in the original post.

This is obviously very concerning because I no longer have any way of accessing the database and the data within via the studio, and it seems like the database has been corrupted somehow, with no way for me to access or restore the data. The error messages I am getting in the command line when I try to login are as follows:

`com.orientechnologies.orient.core.exception.OStorageException: File with name ___exportImportRIDMap.him does not exist in storage tb_api006
        DB name="tb_api006"
        at com.orientechnologies.orient.core.storage.cache.local.OWOWCache.loadFile(OWOWCache.java:732)
        at com.orientechnologies.orient.core.storage.impl.local.paginated.base.ODurableComponent.openFile(ODurableComponent.java:188)
        at com.orientechnologies.orient.core.storage.index.hashindex.local.OLocalHashTable.load(OLocalHashTable.java:491)
        at com.orientechnologies.orient.core.storage.index.engine.OHashTableIndexEngine.load(OHashTableIndexEngine.java:143)
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.loadExternalIndexEngine(OAbstractPaginatedStorage.java:2337)
        at com.orientechnologies.orient.core.index.OIndexAbstract.loadFromConfiguration(OIndexAbstract.java:291)
        at com.orientechnologies.orient.core.index.OIndexManagerShared.fromStream(OIndexManagerShared.java:405)
        at com.orientechnologies.orient.core.type.ODocumentWrapperNoClass.reload(ODocumentWrapperNoClass.java:66)
        at com.orientechnologies.orient.core.index.OIndexManagerAbstract.load(OIndexManagerAbstract.java:104)
        at com.orientechnologies.orient.core.db.OSharedContextEmbedded.load(OSharedContextEmbedded.java:65)
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentEmbedded.loadMetadata(ODatabaseDocumentEmbedded.java:292)
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentEmbedded.init(ODatabaseDocumentEmbedded.java:162)
        at com.orientechnologies.orient.core.db.OrientDBEmbedded.openNoAuthenticate(OrientDBEmbedded.java:239)
        at com.orientechnologies.orient.core.db.OrientDBEmbedded.openNoAuthenticate(OrientDBEmbedded.java:59)
        at com.orientechnologies.orient.server.OServer.openDatabase(OServer.java:936)
        at com.orientechnologies.orient.server.OServer.openDatabase(OServer.java:908)
        at com.orientechnologies.orient.server.network.protocol.http.command.OServerCommandAuthenticatedDbAbstract.authenticate(OServerCommandAuthenticatedDbAbstract.java:162)
        at com.orientechnologies.orient.server.network.protocol.http.command.OServerCommandAuthenticatedDbAbstract.beforeExecute(OServerCommandAuthenticatedDbAbstract.java:122)
        at com.orientechnologies.orient.server.network.protocol.http.command.get.OServerCommandGetConnect.beforeExecute(OServerCommandGetConnect.java:50)
        at com.orientechnologies.orient.server.network.protocol.http.ONetworkProtocolHttpAbstract.service(ONetworkProtocolHttpAbstract.java:225)
        at com.orientechnologies.orient.server.network.protocol.http.ONetworkProtocolHttpAbstract.execute(ONetworkProtocolHttpAbstract.java:707)
        at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:69)`

`$ANSI{green {db=tb_api006}} Error during load of index '___exportImportRIDMap'
com.orientechnologies.orient.core.exception.OStorageException: File with name ___exportImportRIDMap.him does not exist in storage tb_api006
        DB name="tb_api006"
        at com.orientechnologies.orient.core.storage.cache.local.OWOWCache.loadFile(OWOWCache.java:732)
        at com.orientechnologies.orient.core.storage.impl.local.paginated.base.ODurableComponent.openFile(ODurableComponent.java:188)
        at com.orientechnologies.orient.core.storage.index.hashindex.local.OLocalHashTable.load(OLocalHashTable.java:491)
        at com.orientechnologies.orient.core.storage.index.engine.OHashTableIndexEngine.load(OHashTableIndexEngine.java:143)
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.loadExternalIndexEngine(OAbstractPaginatedStorage.java:2337)
        at com.orientechnologies.orient.core.index.OIndexAbstract.loadFromConfiguration(OIndexAbstract.java:291)
        at com.orientechnologies.orient.core.index.OIndexManagerShared.fromStream(OIndexManagerShared.java:405)
        at com.orientechnologies.orient.core.type.ODocumentWrapperNoClass.reload(ODocumentWrapperNoClass.java:66)
        at com.orientechnologies.orient.core.index.OIndexManagerAbstract.load(OIndexManagerAbstract.java:104)
        at com.orientechnologies.orient.core.db.OSharedContextEmbedded.load(OSharedContextEmbedded.java:65)
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentEmbedded.loadMetadata(ODatabaseDocumentEmbedded.java:292)
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentEmbedded.init(ODatabaseDocumentEmbedded.java:162)
        at com.orientechnologies.orient.core.db.OrientDBEmbedded.openNoAuthenticate(OrientDBEmbedded.java:239)
        at com.orientechnologies.orient.core.db.OrientDBEmbedded.openNoAuthenticate(OrientDBEmbedded.java:59)
        at com.orientechnologies.orient.server.OServer.openDatabase(OServer.java:936)
        at com.orientechnologies.orient.server.OServer.openDatabase(OServer.java:908)
        at com.orientechnologies.orient.server.network.protocol.http.command.OServerCommandAuthenticatedDbAbstract.authenticate(OServerCommandAuthenticatedDbAbstract.java:162)
        at com.orientechnologies.orient.server.network.protocol.http.command.OServerCommandAuthenticatedDbAbstract.beforeExecute(OServerCommandAuthenticatedDbAbstract.java:122)
        at com.orientechnologies.orient.server.network.protocol.http.command.get.OServerCommandGetConnect.beforeExecute(OServerCommandGetConnect.java:50)
        at com.orientechnologies.orient.server.network.protocol.http.ONetworkProtocolHttpAbstract.service(ONetworkProtocolHttpAbstract.java:225)
        at com.orientechnologies.orient.server.network.protocol.http.ONetworkProtocolHttpAbstract.execute(ONetworkProtocolHttpAbstract.java:707)
        at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:69)`

`Internal server error:

java.lang.NullPointerException
        at com.orientechnologies.orient.core.metadata.schema.OImmutableProperty.<init>(OImmutableProperty.java:102)
        at com.orientechnologies.orient.core.metadata.schema.OImmutableClass.<init>(OImmutableClass.java:119)
        at com.orientechnologies.orient.core.metadata.schema.OImmutableSchema.<init>(OImmutableSchema.java:69)
        at com.orientechnologies.orient.core.metadata.schema.OSchemaShared.forceSnapshot(OSchemaShared.java:164)
        at com.orientechnologies.orient.core.metadata.schema.SchemaSnapshotOnIndexesUpdateListener.onIndexManagerUpdate(SchemaSnapshotOnIndexesUpdateListener.java:22)
        at com.orientechnologies.orient.core.index.OIndexManagerAbstract.releaseExclusiveLock(OIndexManagerAbstract.java:447)
        at com.orientechnologies.orient.core.index.OIndexManagerAbstract.load(OIndexManagerAbstract.java:106)
        at com.orientechnologies.orient.core.db.OSharedContextEmbedded.load(OSharedContextEmbedded.java:65)
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentEmbedded.loadMetadata(ODatabaseDocumentEmbedded.java:292)
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentEmbedded.init(ODatabaseDocumentEmbedded.java:162)
        at com.orientechnologies.orient.core.db.OrientDBEmbedded.openNoAuthenticate(OrientDBEmbedded.java:239)
        at com.orientechnologies.orient.core.db.OrientDBEmbedded.openNoAuthenticate(OrientDBEmbedded.java:59)
        at com.orientechnologies.orient.server.OServer.openDatabase(OServer.java:936)
        at com.orientechnologies.orient.server.OServer.openDatabase(OServer.java:908)
        at com.orientechnologies.orient.server.network.protocol.http.command.OServerCommandAuthenticatedDbAbstract.authenticate(OServerCommandAuthenticatedDbAbstract.java:162)
        at com.orientechnologies.orient.server.network.protocol.http.command.OServerCommandAuthenticatedDbAbstract.beforeExecute(OServerCommandAuthenticatedDbAbstract.java:122)
        at com.orientechnologies.orient.server.network.protocol.http.command.get.OServerCommandGetConnect.beforeExecute(OServerCommandGetConnect.java:50)
        at com.orientechnologies.orient.server.network.protocol.http.ONetworkProtocolHttpAbstract.service(ONetworkProtocolHttpAbstract.java:225)
        at com.orientechnologies.orient.server.network.protocol.http.ONetworkProtocolHttpAbstract.execute(ONetworkProtocolHttpAbstract.java:707)
        at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:69)`
