### ISSUE TITLE
Internal Server Error while getting connected vertices.

### ISSUE THREAD

**Issue by anukul-mohil** [orientechnologies/orientdb#8607]
## Expected behavior  
Return all the vertices having an edge to the vertex with name 'main', 
`g.V().has('MyVertex', 'name', 'main').in()`

## Actual behavior  
Returns Error: `java.lang.NullPointerException: out vertex on edge COMPONENT_OF#89:7648{out:null,in:#45:2} v2`
on studio and in server logs this:
```  
Internal server error: java.lang.NullPointerException: out vertex on edge COMPONENT_OF#89:7648{out:null,in:#45:2} v2
        at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:226)
        at org.apache.tinkerpop.gremlin.orientdb.OrientEdge.<init>(OrientEdge.java:32)
        at org.apache.tinkerpop.gremlin.orientdb.OrientEdge.<init>(OrientEdge.java:39)
        at org.apache.tinkerpop.gremlin.orientdb.OrientEdge.<init>(OrientEdge.java:48)
        at org.apache.tinkerpop.gremlin.orientdb.OElementFactory.wrapEdge(OElementFactory.java:18)
        at org.apache.tinkerpop.gremlin.orientdb.OrientVertex.lambda$edges$8(OrientVertex.java:131)
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
        at java.util.Iterator.forEachRemaining(Iterator.java:116)
        at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
        at org.apache.tinkerpop.gremlin.orientdb.OrientVertex.edges(OrientVertex.java:133)
        at org.apache.tinkerpop.gremlin.process.traversal.step.map.VertexStep.flatMap(VertexStep.java:55)
        at org.apache.tinkerpop.gremlin.process.traversal.step.map.FlatMapStep.processNextStart(FlatMapStep.java:49)
        at org.apache.tinkerpop.gremlin.process.traversal.step.util.AbstractStep.hasNext(AbstractStep.java:143)
        at org.apache.tinkerpop.gremlin.process.traversal.step.util.ExpandableStepIterator.hasNext(ExpandableStepIterator.java:42)
        at org.apache.tinkerpop.gremlin.process.traversal.step.util.ReducingBarrierStep.processAllStarts(ReducingBarrierStep.java:83)
        at org.apache.tinkerpop.gremlin.process.traversal.step.util.ReducingBarrierStep.processNextStart(ReducingBarrierStep.java:113)
        at org.apache.tinkerpop.gremlin.process.traversal.step.util.AbstractStep.hasNext(AbstractStep.java:143)
        at org.apache.tinkerpop.gremlin.process.traversal.util.DefaultTraversal.hasNext(DefaultTraversal.java:192)
        at org.apache.tinkerpop.gremlin.orientdb.executor.OGremlinScriptResultSet.hasNext(OGremlinScriptResultSet.java:37)
        at com.orientechnologies.orient.core.sql.parser.OLocalResultSetLifecycleDecorator.hasNext(OLocalResultSetLifecycleDecorator.java:44)
        at com.orientechnologies.orient.server.network.protocol.http.command.post.OServerCommandPostCommand.execute(OServerCommandPostCommand.java:92)
        at com.orientechnologies.orient.server.network.protocol.http.command.post.OServerCommandPostCommandGraph.execute(OServerCommandPostCommandGraph.java:36)
        at com.orientechnologies.orient.server.network.protocol.http.ONetworkProtocolHttpAbstract.service(ONetworkProtocolHttpAbstract.java:172)
        at com.orientechnologies.orient.server.network.protocol.http.ONetworkProtocolHttpAbstract.execute(ONetworkProtocolHttpAbstract.java:633)
        at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:82)

```

## Steps to reproduce  
We can't seem to reproduce this but there were some rollback transactions that failed, that may have caused this.
We tried running `repair database` command which did return this 
- Repairing database...
- Removing broken links...
-- Done! Fixed links: 122, modified documents: 120
Repair database complete (0 errors)`
but that didn't solve this issue. 

The only thing it did was in the exception returned one of the vertex which was deleted but was showing up like this: 
``` 
Internal server error:
java.lang.NullPointerException: out vertex on edge COMPONENT_OF#89:7648{out:#44:7642,in:#45:2} v1 

changed to 

 java.lang.NullPointerException: out vertex on edge COMPONENT_OF#89:7648{out:null,in:#45:2} v2 
 
```
that is I think it just cleared the dead vertices lying around but apparently was not able to clear the reference of the dead edge on this `main` vertex.

Any help is appreciated.
Thanks.

**Comment by luigidellaquila** [comment]
HI @anukul-mohil 

The problem here is that your DB contains a broken edge: `#89:7648{out:null,in:#45:2}`

What I can suggest is to run a `DELETE EDGE  #89:7648` from Studio.
If it fails, you can manually check record #45:2 (from Studio) and see if it points to the edge, detach it manually using plain SQL and delete the edge with `DELETE #89:7648 UNSAFE`

It would be interesting to understand how it happened, but I don't know how easy it is. What I can suggest in general is to upgrade to v 3.0.9, as it contains a lot of bug fixes

Thanks

Luigi
