### ISSUE TITLE
Live query for single element throws exception

### ISSUE THREAD

**Issue by pcholder** [orientechnologies/orientdb#8620]
## Expected behavior  
live query works as documented

## Actual behavior  
When subscribe to record ID, it throws error
`
java.lang.ArrayIndexOutOfBoundsException: 1677721600
	at com.orientechnologies.common.exception.OErrorCode.getErrorCode(OErrorCode.java:85)
	at com.orientechnologies.orient.client.remote.message.OError37Response.read(OError37Response.java:38)
	at com.orientechnologies.orient.client.binary.OChannelBinaryAsynchClient.handleStatus(OChannelBinaryAsynchClient.java:271)
	at com.orientechnologies.orient.client.remote.OStorageRemotePushThread.run(OStorageRemotePushThread.java:54)`

## Steps to reproduce  

Three lines:
```
OVertex item = db.newVertex();
item.save();
OLiveQueryMonitor live = db.live("LIVE SELECT FROM " + item.getIdentity(), itemListener);
```

**Comment by pcholder** [comment]
Seems fast but dangerous
```
  public static OErrorCode getErrorCode(int code) {
    return codes[code];
  }
```
when used in `OError37Response.java`
```
    int code = network.readInt();
    this.errorIdentifier = network.readInt();
    this.code = OErrorCode.getErrorCode(code);
```

**Comment by pcholder** [comment]
I tried last snapshot 3.1 and changed my query to this one:
`db.live("LIVE SELECT FROM MyItemClass WHERE @rid=", concreteItemListener, itemRid);`
Error message no longer appears, but listener ignores any events.

**Comment by tglman** [comment]
Hi,

There where some issue in the error management that i just fixed, anyway the query on the rid should be possible, we are checking that as well.

Regards
