### ISSUE TITLE
Unable to connect orient database through console.

### ISSUE THREAD

**Issue by rbaarathinms** [orientechnologies/orientdb#8622]
OrientDB Version: orientdb-community-2.2.20
Java Version: Java -8 (jre-1.8.144) 
OS : Centos/ Windows -7

Expected behavior
     Orient storage corrupted during server restart.

Actual behavior  
     * A built orient database is configured with our application server. After server initialization, some exception occured in orient database which are reported below.

$ANSI{green {db=rcasdh}} Error on using index OUser.name in query 'select from OUser where name = ? limit 1'. Probably you need to rebuild indexes. Now executing query using cluster scan
java.lang.NullPointerException
        at com.orientechnologies.common.directmemory.OByteBufferPool.acquireDirect(OByteBufferPool.java:297)
        at com.orientechnologies.orient.core.storage.cache.local.OWOWCache.cacheFileContent(OWOWCache.java:1280)
        at com.orientechnologies.orient.core.storage.cache.local.OWOWCache.load(OWOWCache.java:656)
        at com.orientechnologies.orient.core.storage.cache.local.twoq.O2QCache.updateCache(O2QCache.java:1113)
        at com.orientechnologies.orient.core.storage.cache.local.twoq.O2QCache.doLoad(O2QCache.java:353)
        at com.orientechnologies.orient.core.storage.cache.local.twoq.O2QCache.load(O2QCache.java:298)
        at com.orientechnologies.orient.core.storage.impl.local.paginated.base.ODurableComponent.loadPage(ODurableComponent.java:148)
        at com.orientechnologies.orient.core.storage.impl.local.paginated.base.ODurableComponent.loadPage(ODurableComponent.java:142)
        at com.orientechnologies.orient.core.index.sbtree.local.OSBTree.findBucket(OSBTree.java:1764)
        at com.orientechnologies.orient.core.index.sbtree.local.OSBTree.get(OSBTree.java:200)
        at com.orientechnologies.orient.core.index.engine.OSBTreeIndexEngine.get(OSBTreeIndexEngine.java:128)
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.doGetIndexValue(OAbstractPaginatedStorage.java:1764)
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.getIndexValue(OAbstractPaginatedStorage.java:1753)
        at com.orientechnologies.orient.core.index.OIndexOneValue.get(OIndexOneValue.java:58)
        at com.orientechnologies.orient.core.index.OIndexOneValue.get(OIndexOneValue.java:40)
        at com.orientechnologies.orient.core.index.OIndexAbstractDelegate.get(OIndexAbstractDelegate.java:58)
        at com.orientechnologies.orient.core.index.OIndexTxAwareOneValue.get(OIndexTxAwareOneValue.java:262)
        at com.orientechnologies.orient.core.index.OIndexTxAwareOneValue.get(OIndexTxAwareOneValue.java:40)
        at com.orientechnologies.orient.core.sql.operator.OQueryOperatorEquals.executeIndexQuery(OQueryOperatorEquals.java:158)
        at com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.searchForIndexes(OCommandExecutorSQLSelect.java:2173)
        at com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.searchInClasses(OCommandExecutorSQLSelect.java:997)
        at com.orientechnologies.orient.core.sql.OCommandExecutorSQLResultsetAbstract.assignTarget(OCommandExecutorSQLResultsetAbstract.java:209)
        at com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.assignTarget(OCommandExecutorSQLSelect.java:526)
        at com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.executeSearch(OCommandExecutorSQLSelect.java:508)
        at com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.execute(OCommandExecutorSQLSelect.java:484)
        at com.orientechnologies.orient.core.sql.OCommandExecutorSQLDelegate.execute(OCommandExecutorSQLDelegate.java:74)
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.executeCommand(OAbstractPaginatedStorage.java:2578)
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.command(OAbstractPaginatedStorage.java:2524)
        at com.orientechnologies.orient.core.sql.query.OSQLQuery.run(OSQLQuery.java:78)
        at com.orientechnologies.orient.core.sql.query.OSQLAsynchQuery.run(OSQLAsynchQuery.java:74)
        at com.orientechnologies.orient.core.sql.query.OSQLSynchQuery.run(OSQLSynchQuery.java:85)
        at com.orientechnologies.orient.core.query.OQueryAbstract.execute(OQueryAbstract.java:33)
        at com.orientechnologies.orient.core.metadata.security.OSecurityShared.getUser(OSecurityShared.java:607)
        at com.orientechnologies.orient.core.metadata.security.OSecurityExternal.getUser(OSecurityExternal.java:94)
        at com.orientechnologies.orient.core.metadata.security.OSecurityShared.authenticate(OSecurityShared.java:235)
        at com.orientechnologies.orient.core.metadata.security.OSecurityExternal.authenticate(OSecurityExternal.java:62)
        at com.orientechnologies.orient.core.metadata.security.OSecurityProxy.authenticate(OSecurityProxy.java:107)
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.open(ODatabaseDocumentTx.java:275)
        at com.orientechnologies.orient.core.db.OPartitionedDatabasePool$DatabaseDocumentTxPooled.internalOpen(OPartitionedDatabasePool.java:447)
        at com.orientechnologies.orient.core.db.OPartitionedDatabasePool.openDatabase(OPartitionedDatabasePool.java:313)
        at com.orientechnologies.orient.core.db.OPartitionedDatabasePool.acquire(OPartitionedDatabasePool.java:250)
        at in.co.nmsworks.documenttdb.spi.impl.orient.OrientInternal.getDatabase(OrientInternal.java:530)
        at in.co.nmsworks.documenttdb.db.DocDB.createDB(DocDB.java:390)
        at in.co.nmsworks.documenttdb.db.DocDB.<init>(DocDB.java:77)
        at in.co.nmsworks.documenttdb.db.DocDB.<init>(DocDB.java:82)
        at in.co.nmsworks.cygnet.telecom.fault.rcasia.inventory.store.SDHRcaInvReader.getTLPatternInventoryEntitiesForPTP(SDHRcaInvReader.java:1761)
        at in.co.nmsworks.cygnet.telecom.fault.rcasia.plug.impl.circuit.impl2.CircuitPlugHelper.getResourcesToLockForInvBuilding(CircuitPlugHelper.java:213)
        at in.co.nmsworks.cygnet.telecom.fault.rcasia.plug.impl.circuit.wdm.impl.WDMCircuitPlugHelper.getImpactAnalysisDataHolder(WDMCircuitPlugHelper.java:365)
        at in.co.nmsworks.cygnet.telecom.fault.rcasia.plug.impl.circuit.wdm.impl.WDMCircuitPlugHelper.getImpactAnalysisDataHolder(WDMCircuitPlugHelper.java:349)
        at in.co.nmsworks.cygnet.telecom.fault.rcasia.plug.impl.circuit.wdm.impl.WDMCircuitPlug.acquireLockAndReturnWrapperForAnalyze(WDMCircuitPlug.java:140)
        at in.co.nmsworks.cygnet.telecom.fault.rcasia.plug.impl.circuit.wdm.impl.WDMCircuitPlug.getLockResource(WDMCircuitPlug.java:106)
        at in.co.nmsworks.cygnet.telecom.fault.rcasia.plug.Plug.lock(Plug.java:723)
        at in.co.nmsworks.cygnet.telecom.fault.rcasia.plug.Plug.doLockForEvent(Plug.java:318)
        at in.co.nmsworks.cygnet.telecom.fault.rcasia.server.LockKeysPlugJob.doWork(LockKeysPlugJob.java:151)
        at com.nmsworks.cygnet.util.treejob.TreeJob.run(TreeJob.java:44)
        at com.nmsworks.cygnet.util.orderingexecutor.MultiKeyOrderingExecutor$DependentJob.run(MultiKeyOrderingExecutor.java:408)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
*************************************************************************************************************************
**** We don't observe any memory issue or Full GC or server crash but still facing the above issue.

This exception is getting repeated during every server restart. Hence we are trying to connect the orient through console and getting the below exception.

orientdb> connect remote:localhost/rcawdm root root

Disconnecting from the database [null]...OK
Connecting to database [remote:localhost/rcawdm] with user 'root'...
Error: com.orientechnologies.orient.core.exception.ORecordNotFoundException: The record with id '#0:1' was not found
        DB name="rcawdm"

Error: com.orientechnologies.orient.core.exception.ODatabaseException: Error on retrieving record #0:1 (cluster: internal)
        DB name="rcawdm"

Error: com.orientechnologies.orient.core.exception.ODatabaseException: Error on retrieving record #0:1 (cluster: internal)
        DB name="rcawdm"
        DB name="rcawdm"

Error: java.lang.NullPointerException

*******************************************************************************************************************************

**** This exception is repeatedly occuring after every server restart. It is not possible to build a new orient during every restart. 

Kindly help us in resolving the issue.

**Comment by luigidellaquila** [comment]
Hi @rbaarathinms 

I see you are using OrientDB v 2.2.20, please upgrade to latest hotfix (2.2.37 as of now, but I'd suggest to migrate to 3.0), there is a chance that is an old problem and that it's already fixed

Thanks

Luigi
