### ISSUE TITLE
ORecordSerializerBinary NPE

### ISSUE THREAD

**Issue by grimace** [orientechnologies/orientdb#8626]
## Expected behavior  
should be able to load record, if there is an invalid property, it should just come back as null.

## Actual behavior  
record (Vertex) can not be loaded or deleted

## Steps to reproduce  
currently existing on DB, not sure how to reproduce, but have stacktrace...:

```
[ORecordSerializerBinary]Internal server error:

java.lang.NullPointerException
	at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinaryV0.deserializeValue(ORecordSerializerBinaryV0.java:543)
	at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinaryV0.deserializeValue(ORecordSerializerBinaryV0.java:416)
	at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinaryV0.readEmbeddedList(ORecordSerializerBinaryV0.java:833)
	at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinaryV0.deserializeValue(ORecordSerializerBinaryV0.java:618)
	at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinaryV0.deserializeValue(ORecordSerializerBinaryV0.java:416)
	at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinaryV0.readEmbeddedMap(ORecordSerializerBinaryV0.java:757)
	at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinaryV0.deserializeValue(ORecordSerializerBinaryV0.java:653)
	at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinaryV0.deserializeValue(ORecordSerializerBinaryV0.java:416)
	at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinaryV0.readEmbeddedList(ORecordSerializerBinaryV0.java:833)
	at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinaryV0.deserializeValue(ORecordSerializerBinaryV0.java:618)
	at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinaryV0.deserializeValue(ORecordSerializerBinaryV0.java:416)
	at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinaryV0.readEmbeddedMap(ORecordSerializerBinaryV0.java:757)
	at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinaryV0.deserializeValue(ORecordSerializerBinaryV0.java:653)
	at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinaryV0.deserializeValue(ORecordSerializerBinaryV0.java:416)
	at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinaryV0.readEmbeddedList(ORecordSerializerBinaryV0.java:833)
	at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinaryV0.deserializeValue(ORecordSerializerBinaryV0.java:618)
	at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinaryV0.deserializeValue(ORecordSerializerBinaryV0.java:416)
	at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinaryV0.deserialize(ORecordSerializerBinaryV0.java:290)
	at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinary.fromStream(ORecordSerializerBinary.java:104)
	at com.orientechnologies.orient.core.record.impl.ODocument.deserializeFields(ODocument.java:2172)
	at com.orientechnologies.orient.core.record.impl.ODocument.checkForFields(ODocument.java:2958)
	at com.orientechnologies.orient.core.record.impl.ODocument.setDirty(ODocument.java:1744)
	at com.orientechnologies.orient.core.record.impl.OSimpleMultiValueChangeListener.onAfterRecordChanged(OSimpleMultiValueChangeListener.java:56)
	at com.orientechnologies.orient.core.db.record.ridbag.embedded.OEmbeddedRidBag.fireCollectionChangedEvent(OEmbeddedRidBag.java:498)
	at com.orientechnologies.orient.core.db.record.ridbag.embedded.OEmbeddedRidBag.remove(OEmbeddedRidBag.java:265)
	at com.orientechnologies.orient.core.db.record.ridbag.ORidBag.remove(ORidBag.java:158)
	at com.orientechnologies.orient.core.record.impl.OVertexDelegate.detachEdge(OVertexDelegate.java:231)
	at com.orientechnologies.orient.core.record.impl.OVertexDelegate.detachIncomingEdge(OVertexDelegate.java:202)
	at com.orientechnologies.orient.core.record.impl.OEdgeDelegate.deleteLinks(OEdgeDelegate.java:137)
	at com.orientechnologies.orient.core.record.impl.OEdgeDocument.delete(OEdgeDocument.java:51)
	at com.orientechnologies.orient.core.record.impl.OEdgeDocument.delete(OEdgeDocument.java:8)
	at com.orientechnologies.orient.core.record.impl.OVertexDocument.deleteLinks(OVertexDocument.java:303)
	at com.orientechnologies.orient.core.record.impl.OVertexDocument.delete(OVertexDocument.java:295)
	at com.orientechnologies.orient.core.record.impl.OVertexDocument.delete(OVertexDocument.java:21)
	at com.orientechnologies.orient.core.sql.executor.DeleteStep$1.next(DeleteStep.java:36)
	at com.orientechnologies.orient.core.sql.executor.CountStep.syncPull(CountStep.java:53)
	at com.orientechnologies.orient.core.sql.executor.OSelectExecutionPlan.fetchNext(OSelectExecutionPlan.java:37)
	at com.orientechnologies.orient.core.sql.executor.OUpdateExecutionPlan.executeInternal(OUpdateExecutionPlan.java:46)
	at com.orientechnologies.orient.core.sql.parser.ODeleteVertexStatement.execute(ODeleteVertexStatement.java:58)
	at com.orientechnologies.orient.core.sql.parser.OStatement.execute(OStatement.java:62)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentEmbedded.command(ODatabaseDocumentEmbedded.java:540)
	at com.orientechnologies.orient.server.network.protocol.http.command.post.OServerCommandPostCommand.executeStatement(OServerCommandPostCommand.java:178)
	at com.orientechnologies.orient.server.network.protocol.http.command.post.OServerCommandPostCommand.execute(OServerCommandPostCommand.java:85)
	at com.orientechnologies.orient.server.network.protocol.http.command.post.OServerCommandPostCommandGraph.execute(OServerCommandPostCommandGraph.java:36)
	at com.orientechnologies.orient.server.network.protocol.http.ONetworkProtocolHttpAbstract.service(ONetworkProtocolHttpAbstract.java:176)
	at com.orientechnologies.orient.server.network.protocol.http.ONetworkProtocolHttpAbstract.execute(ONetworkProtocolHttpAbstract.java:655)
	at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:69)

```

**Comment by markodjurovic** [comment]
Hi @grimace ,
thank you for reporting this. If you can please answer me on few questions:
1. Is database created with version 3.0.x of OrientDB?
2. Did you experienced some issues related to storage you are using for the database, or network issues if you are connecting to database remotely?

**Comment by grimace** [comment]
Yes, it was created with 3.0.x  ( 3.0.6 I believe ), and I do believe there was an issue where I had a OutOfMemory happen on the remote server. 
In my mind, It really could be a corrupted record, but I do not know of any way to resolve that.  Is there a DB repair?   Can I physically remove that record?  The record in question is a Vertex with a json/map property on it.   I can not even remove Vertex - I get same error above.   I've been able to recreate my DB and am running a parallel instance ( which seems to be working fine ).  I would like to know how to resolve this in case something similar happens in the future.

**Comment by markodjurovic** [comment]
Hi @grimace,

thank you on answers. It looks like corruption caused by some non graceful issue, like OOM. There is repair tool and there is a chance that it can help:
