### ISSUE TITLE
OStorageRemote NPE

### ISSUE THREAD

**Issue by valenpo** [orientechnologies/orientdb#8649]
## Expected behavior  
Trying connect to multiply remote databases:
remote:localhost/data
remote:localhost/enron
remote:localhost/two

connection to databases are executed simultaneously, and checking existents of databases: 

```
if (!ODatabaseHelper.existsDatabase(connectionSettings.getUrl())) {
            ODatabaseHelper.createDatabase(null, connectionSettings.getUrl());
        }
```

In some point I get connected to one database, and get NPE on OStorageRemote. getNetwork(final String iCurrentURL)

Here is on method, connectionManager is null. 
  ```
public OChannelBinaryAsynchClient getNetwork(final String iCurrentURL) {
    OChannelBinaryAsynchClient network;
    do {
      try {
        network = connectionManager.acquire(iCurrentURL, clientConfiguration, connectionOptions, asynchEventListener);
      } catch (OIOException cause) {
        throw cause;
      } catch (Exception cause) {
        throw OException.wrapException(new OStorageException("Cannot open a connection to remote server: " + iCurrentURL), cause);
      }
      if (!network.tryLock()) {
        // CANNOT LOCK IT, MAYBE HASN'T BE CORRECTLY UNLOCKED BY PREVIOUS USER?
        OLogManager.instance()
            .error(this, "Removing locked network channel '%s' (connected=%s)...", null, iCurrentURL, network.isConnected());
        connectionManager.remove(network);
        network = null;
      }
    } while (network == null);
    return network;
  }
```

```
2018-11-08 11:56:27 d.c.s.a.d.Services [DEBUG] error:stop:com.orientechnologies.orient.core.exception.OStorageException: Cannot connect to the remote server/database 'remote:localhost/data'
com.orientechnologies.orient.core.exception.OStorageException: Cannot connect to the remote server/database 'remote:localhost/data'
	at com.orientechnologies.orient.client.remote.OServerAdmin.networkAdminOperation(OServerAdmin.java:695)
	at com.orientechnologies.orient.client.remote.OServerAdmin.connect(OServerAdmin.java:87)
	at com.orientechnologies.orient.client.db.ODatabaseHelper.existsDatabase(ODatabaseHelper.java:102)
	at com.stimulus.archiva.database.blueprints.BluePrintDatabaseUtil.createIfNoExist(BluePrintDatabaseUtil.java:424)
	at com.stimulus.archiva.database.blueprints.BluePrintDatabase.connect(BluePrintDatabase.java:89)
	at com.stimulus.archiva.database.DatabaseService.startup(DatabaseService.java:223)
	at com.stimulus.archiva.domain.Services$ServiceController.lambda$startStop$0(Services.java:138)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.orientechnologies.orient.core.exception.OStorageException: Cannot open a connection to remote server: 127.0.0.1:2424/data
	at com.orientechnologies.orient.client.remote.OStorageRemote.getNetwork(OStorageRemote.java:2350)
	at com.orientechnologies.orient.client.remote.OServerAdmin.networkAdminOperation(OServerAdmin.java:680)
	... 9 common frames omitted
Caused by: java.lang.NullPointerException: null
	at com.orientechnologies.orient.client.remote.OStorageRemote.getNetwork(OStorageRemote.java:2346)
	... 10 common frames omitted
```

On method 
## Actual behavior  
<add here>  

## Steps to reproduce  
```
@Test
    public void checkExist() throws InterruptedException {

        String[] applications = {"enron", "supercompany", "central", "enron", "data"};

        String connectionURL = "remote:127.0.0.1:2424/";
        System.setProperty("ORIENTDB_ROOT_PASSWORD", "admin");

        ExecutorService executorService = Executors.newCachedThreadPool();

        for (String db: applications) {
            executorService.submit(() -> {
                try {
                    System.out.println(MessageFormat.format("database {0} exist {1}", db,
                            ODatabaseHelper.existsDatabase(connectionURL + db)));
                } catch (Exception e) {
                    e.printStackTrace();
                }
            });
        }

        executorService.awaitTermination(1, TimeUnit.SECONDS);
        executorService.shutdown();
    }
```

**Comment by valenpo** [comment]
@laa any updates?
