### ISSUE TITLE
Server crashes with infinite stack trace loop

### ISSUE THREAD

**Issue by hrstoyanov** [orientechnologies/orientdb#8679]
### OS: MacOs  

I am getting infinite loop of log stack traces in the server console and the server becomes unresponsive. So, I have to kill it:

```
2018-11-27 02:02:42:662 SEVER Can not flush data because of issue during data write, Error during WAL write for storage ro.db [OWOWCache$PeriodicFlushTask]
2018-11-27 02:02:42:693 SEVER Can not flush data because of issue during data write, Error during WAL write for storage ro.db [OWOWCache$PeriodicFlushTask]
2018-11-27 02:02:42:718 SEVER Can not flush data because of issue during data write, Error during WAL write for storage ro.db [OWOWCache$PeriodicFlushTask]
2018-11-27 02:02:42:745 SEVER Can not flush data because of issue during data write, Error during WAL write for storage ro.db [OWOWCache$PeriodicFlushTask]
2018-11-27 02:02:42:772 SEVER Can not flush data because of issue during data write, Error during WAL write for storage ro.db [OWOWCache$PeriodicFlushTask]
2018-11-27 02:02:42:799 SEVER Can not flush data because of issue during data write, Error during WAL write for storage ro.db [OWOWCache$PeriodicFlushTask]
2018-11-27 02:02:42:830 SEVER Can not flush data because of issue during data write, Error during WAL write for storage ro.db [OWOWCache$PeriodicFlushTask]
2018-11-27 02:02:42:856 SEVER Can not flush data because of issue during data write, Error during WAL write for storage ro.db [OWOWCache$PeriodicFlushTask]
2018-11-27 02:02:42:881 SEVER Can not flush data because of issue during data write, Error during WAL write for storage ro.db [OWOWCache$PeriodicFlushTask]
2018-11-27 02:02:42:910 SEVER Can not flush data because of issue during data write, Error during WAL write for storage ro.db [OWOWCache$PeriodicFlushTask]
2018-11-27 02:02:42:936 SEVER Can not flush data because of issue during data write, Error during WAL write for storage ro.db [OWOWCache$PeriodicFlushTask]
2018-11-27 02:02:42:964 SEVER Can not flush data because of issue during data write, Error during WAL write for storage ro.db [OWOWCache$PeriodicFlushTask]
2018-11-27 02:02:42:993 SEVER Can not flush data because of issue during data write, Error during WAL write for storage ro.db [OWOWCache$PeriodicFlushTask]
2018-11-27 02:02:43:020 SEVER Can not flush data because of issue during data write, Error during WAL write for storage ro.db [OWOWCache$PeriodicFlushTask]
2018-11-27 02:02:43:048 SEVER Can not flush data because of issue during data write, Error during WAL write for storage ro.db [OWOWCache$PeriodicFlushTask]
2018-11-27 02:02:43:078 SEVER Can not flush data because of issue during data write, Error during WAL write for storage ro.db [OWOWCache$PeriodicFlushTask]
2018-11-27 02:02:43:107 SEVER Can not flush data because of issue during data write, Error during WAL write for storage ro.db [OWOWCache$PeriodicFlushTask]
2018-11-27 02:02:43:137 SEVER Can not flush data because of issue during data write, Error during WAL write for storage ro.db [OWOWCache$PeriodicFlushTask]
2018-11-27 02:02:43:167 SEVER Can not flush data because of issue during data write, Error during WAL write for storage ro.db [OWOWCache$PeriodicFlushTask]
2018-11-27 02:02:43:193 SEVER Can not flush data because of issue during data write, Error during WAL write for storage ro.db [OWOWCache$PeriodicFlushTask]
2018-11-27 02:02:43:219 SEVER Can not flush data because of issue during data write, Error during WAL write for storage ro.db [OWOWCache$PeriodicFlushTask]
2018-11-27 02:02:43:245 SEVER Can not flush data because of issue during data write, Error during WAL write for storage ro.db [OWOWCache$PeriodicFlushTask]
2018-11-27 02:02:43:272 SEVER Can not flush data because of issue during data write, Error during WAL write for storage ro.db [OWOWCache$PeriodicFlushTask]
2018-11-27 02:02:43:301 SEVER Can not flush data because of issue during data write, Error during WAL write for storage ro.db [OWOWCache$PeriodicFlushTask]
2018-11-27 02:02:43:328 SEVER Can not flush data because of issue during data write, Error during WAL write for storage ro.db [OWOWCache$PeriodicFlushTask]
2018-11-27 02:02:43:358 SEVER Can not flush data because of issue during data write, Error during WAL write for storage ro.db [OWOWCache$PeriodicFlushTask]
2018-11-27 02:02:43:383 SEVER Can not flush data because of issue during data write, Error during WAL write for storage ro.db [OWOWCache$PeriodicFlushTask]
2018-11-27 02:02:43:414 SEVER Can not flush data because of issue during data write, Error during WAL write for storage ro.db [OWOWCache$PeriodicFlushTask]
2018-11-27 02:02:43:444 SEVER Can not flush data because of issue during data write, Error during WAL write for storage ro.db [OWOWCache$PeriodicFlushTask]
2018-11-27 02:02:43:472 SEVER Can not flush data because of issue during data write, Error during WAL write for storage ro.db [OWOWCache$PeriodicFlushTask]
2018-11-27 02:02:43:503 SEVER Can not flush data because of issue during data write, Error during WAL write for storage ro.db [OWOWCache$PeriodicFlushTask]
2018-11-27 02:02:43:532 SEVER Can not flush data because of issue during data write, Error during WAL write for storage ro.db [OWOWCache$PeriodicFlushTask]
2018-11-27 02:02:43:561 SEVER Can not flush data because of issue during data write, Error during WAL write for storage ro.db [OWOWCache$PeriodicFlushTask]
2018-11-27 02:02:43:586 SEVER Can not flush data because of issue during data write, Error during WAL write for storage ro.db [OWOWCache$PeriodicFlushTask]
2018-11-27 02:02:43:617 SEVER Can not flush data because of issue during data write, Error during WAL write for storage ro.db [OWOWCache$PeriodicFlushTask]
2018-11-27 02:02:43:645 SEVER Can not flush data because of issue during data write, Error during WAL write for storage ro.db [OWOWCache$PeriodicFlushTask]Error during WAL writing
java.util.concurrent.ExecutionException: java.nio.channels.ClosedChannelException
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at com.orientechnologies.orient.core.storage.impl.local.paginated.wal.cas.OCASDiskWriteAheadLog$RecordsWriter.run(OCASDiskWriteAheadLog.java:1985)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.nio.channels.ClosedChannelException
	at sun.nio.ch.FileChannelImpl.ensureOpen(FileChannelImpl.java:110)
	at sun.nio.ch.FileChannelImpl.force(FileChannelImpl.java:379)
	at com.orientechnologies.orient.core.storage.impl.local.paginated.wal.cas.OWALChannelFile.force(OWALChannelFile.java:33)
	at com.orientechnologies.orient.core.storage.impl.local.paginated.wal.cas.OCASDiskWriteAheadLog$RecordsWriter.lambda$run$0(OCASDiskWriteAheadLog.java:2028)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	... 3 more
Exception in thread 'OrientDB WAL Flush Task'
java.lang.IllegalStateException: java.util.concurrent.ExecutionException: java.nio.channels.ClosedChannelException
	at com.orientechnologies.orient.core.storage.impl.local.paginated.wal.cas.OCASDiskWriteAheadLog$RecordsWriter.run(OCASDiskWriteAheadLog.java:2058)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.util.concurrent.ExecutionException: java.nio.channels.ClosedChannelException
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at com.orientechnologies.orient.core.storage.impl.local.paginated.wal.cas.OCASDiskWriteAheadLog$RecordsWriter.run(OCASDiskWriteAheadLog.java:1985)
	... 7 more
Caused by: java.nio.channels.ClosedChannelException
	at sun.nio.ch.FileChannelImpl.ensureOpen(FileChannelImpl.java:110)
	at sun.nio.ch.FileChannelImpl.force(FileChannelImpl.java:379)
	at com.orientechnologies.orient.core.storage.impl.local.paginated.wal.cas.OWALChannelFile.force(OWALChannelFile.java:33)
	at com.orientechnologies.orient.core.storage.impl.local.paginated.wal.cas.OCASDiskWriteAheadLog$RecordsWriter.lambda$run$0(OCASDiskWriteAheadLog.java:2028)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	... 3 more
```

**Comment by laa** [comment]
Hi, @hrstoyanov is this fixed once you removed dot "." from DB name?

**Comment by hrstoyanov** [comment]
seems like it , i have not seen it ever since I removed the "." in the db file name
