### ISSUE TITLE
Error in data flush background thread: null ptr exception

### ISSUE THREAD

**Issue by jamieb22** [orientechnologies/orientdb#8682]
## Expected behavior  

No error.

## Actual behavior 
 
Error in data flush background thread, please restart database and send full stack trace inside of bug report
	DB name="archiva@xxx"
com.orientechnologies.orient.core.exception.OStorageException: Error in data flush background thread, please restart database and send full stack trace inside of bug report
	DB name="archiva@xxx"
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.checkLowDiskSpaceRequestsAndReadOnlyConditions(OAbstractPaginatedStorage.java:5104)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.commit(OAbstractPaginatedStorage.java:1729)
	at com.orientechnologies.orient.core.tx.OTransactionOptimistic.doCommit(OTransactionOptimistic.java:541)
	at com.orientechnologies.orient.core.tx.OTransactionOptimistic.commit(OTransactionOptimistic.java:99)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.commit(ODatabaseDocumentTx.java:2908)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.commit(ODatabaseDocumentTx.java:2870)
	at com.tinkerpop.blueprints.impls.orient.OrientTransactionalGraph.commit(OrientTransactionalGraph.java:182)
Caused by: java.lang.NullPointerException: null

## Steps to reproduce  

Not sure how to reproduce. Occurs in production.

**Comment by laa** [comment]
Could you send log starting from caused by?

**Comment by jamieb22** [comment]
Andrey... I looked everywhere in the log file but the stack after caused by is not available anywhere.

**Comment by zerovian** [comment]
Also ran into this... with an NPE at the core of it.

Orientdb 2.2.37


   Exception at Fri May 24 09:15:48 EDT 2019: com.progress.isq.ipqos.TransactionRolledbackException
   Message (throw): Log file monitor p1ehowup8003:resource.openedge.webspeed.vpasd4.vpasd4BrokerLogFileMonitor failed
   Message (excp):  Commit failed.
   Stack Trace:

Caused by: com.orientechnologies.orient.core.exception.OStorageException: Error in data flush background thread, please restart database and send full stack trace inside of bug report
	DB name="configdb"
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.checkLowDiskSpaceRequestsAndReadOnlyConditions(OAbstractPaginatedStorage.java:5088)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.commit(OAbstractPaginatedStorage.java:1728)
	at com.orientechnologies.orient.core.tx.OTransactionOptimistic.doCommit(OTransactionOptimistic.java:541)
	at com.orientechnologies.orient.core.tx.OTransactionOptimistic.commit(OTransactionOptimistic.java:99)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.commit(ODatabaseDocumentTx.java:2922)
	at com.orientechnologies.orient.object.db.OObjectDatabaseTx.commit(OObjectDatabaseTx.java:572)
	at com.orientechnologies.orient.object.db.OObjectDatabaseTx.commit(OObjectDatabaseTx.java:567)
	at com.progress.isq.ipqos.AbstractDataAccess.commit(AbstractDataAccess.java:109)
	... 7 more
Caused by: java.lang.NullPointerException
	at com.orientechnologies.orient.core.storage.impl.local.paginated.wal.ODiskWriteAheadLog.cutTill(ODiskWriteAheadLog.java:919)
	at com.orientechnologies.orient.core.storage.cache.local.OWOWCache$PeriodicalFuzzyCheckpointTask.run(OWOWCache.java:2155)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:522)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:319)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:191)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	... 3 more

**Comment by laa** [comment]
Hi @zerovian we do not support 2.2.x community edition. Please check 3.0.x version and if the issue will be persistent please let me know.
