### ISSUE TITLE
OObjectDatabaseTx.save does not save a new object when it is called by OJPAEntityManager.persist

### ISSUE THREAD

**Issue by xavier-atero** [orientechnologies/orientdb#8723]
## Expected behavior  
The new object is saved to the database

## Actual behavior  
The new object is not saved to the database

## Steps to reproduce  

In a Spring boot application with JPA and the following code:

**persistence.xml**
``` xml
<?xml version="1.0" encoding="UTF-8"?>
<persistence version="2.0"
    xmlns="http://java.sun.com/xml/ns/persistence" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://java.sun.com/xml/ns/persistence http://java.sun.com/xml/ns/persistence/persistence_2_0.xsd">
    <persistence-unit name="appJpaUnit">
        <provider>com.orientechnologies.orient.object.jpa.OJPAPersistenceProvider</provider>

        <!-- JPA entities must be registered here -->
        <class>Automaticu.WebAPI.ManchesterPlan.Planning.Model.Agent</class>

        <properties>
            <property name="javax.persistence.jdbc.url" value="remote:localhost/ManchesterPlan02" />
            <property name="javax.persistence.jdbc.user" value="admin" />
            <property name="javax.persistence.jdbc.password" value="admin" />
        </properties>
    </persistence-unit>
</persistence>
```
**Agent.java**
``` java
package Automaticu.WebAPI.ManchesterPlan.Planning.Model;

import javax.persistence.Entity;
import javax.persistence.Id;

@Entity
public class Agent {
	
	@Id
	private String rid;
	private String name;
	
	public Agent() {
	}

	public Agent(String name) {
		super();
		this.name = name;
	}

	public String getRid() {
		return rid;
	}

	public void setRid(String rid) {
		this.rid = rid;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}
}
```

**AgentService.java**
``` java
package Automaticu.WebAPI.ManchesterPlan.Planning.Service;

import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;

import org.springframework.stereotype.Service;

import Automaticu.WebAPI.ManchesterPlan.Planning.Model.Agent;

@Service
public class AgentService {

	private EntityManager manager;

	public void addAgent(Agent agent) {

		EntityManagerFactory emf = Persistence.createEntityManagerFactory("appJpaUnit");
		manager = emf.createEntityManager();
		manager.persist(agent);
	}

}
```
**AgentController.java**
``` java
package Automaticu.WebAPI.ManchesterPlan.Planning.Controller;

import Automaticu.WebAPI.ManchesterPlan.Planning.Model.Agent;
import Automaticu.WebAPI.ManchesterPlan.Planning.Service.AgentService;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.PostMapping;

@RestController
public class AgentController {

	@Autowired
	private AgentService agent_service;

	@PostMapping("/agents")
	public void addAgent(@RequestBody Agent agent) {
		agent_service.addAgent(agent);
	}

}
```

## Scenario 1: POST request with no rid
**Call:**
``` json
{
    "name": "new_name"
}
```
**Console output:**
```
2019-01-10 19:49:51.057  INFO 12628 --- [nio-8080-exec-3] c.o.o.o.jpa.OJPAPersistenceProvider      : EntityManagerFactory created. com.orientechnologies.orient.object.jpa.OJPAEntityManagerFactory@655d4876
2019-01-10 19:49:51.228  INFO 12628 --- [nio-8080-exec-3] c.o.o.o.jpa.OJPAPersistenceProvider      : EntityManager created for persistence unit : com.orientechnologies.orient.object.jpa.OJPAEntityManagerFactory@655d4876
```
**Result:**
The object is not created in the database.

## Scenario 2: POST request with rid of existing object in the db
**Call:**
``` json
{
    "rid": "42:0",
    "name": "new_name"
}
```
**Console output:**
```
2019-01-10 19:51:22.184  INFO 12628 --- [nio-8080-exec-5] c.o.o.o.jpa.OJPAPersistenceProvider      : EntityManagerFactory created. com.orientechnologies.orient.object.jpa.OJPAEntityManagerFactory@46016bef
2019-01-10 19:51:22.348  INFO 12628 --- [nio-8080-exec-5] c.o.o.o.jpa.OJPAPersistenceProvider      : EntityManager created for persistence unit : com.orientechnologies.orient.object.jpa.OJPAEntityManagerFactory@46016bef
```
**Result:**
The object is updated in the database.

## Scenario 3: POST request with rid not maching any existing object in the db
**Call:**
``` json
{
    "rid": "42:1",
    "name": "new_name"
}
```
**Response:**
```
{
    "timestamp": "2019-01-10T18:55:22.996+0000",
    "status": 500,
    "error": "Internal Server Error",
    "message": "The record with id '#42:1' was not found\r\n\tDB name=\"ManchesterPlan02\"",
    "path": "/agents"
}
```
**Console output:**
```
2019-01-10 19:55:16.975  INFO 12628 --- [nio-8080-exec-2] c.o.o.o.jpa.OJPAPersistenceProvider      : EntityManagerFactory created. com.orientechnologies.orient.object.jpa.OJPAEntityManagerFactory@3d6d542
2019-01-10 19:55:17.131  INFO 12628 --- [nio-8080-exec-2] c.o.o.o.jpa.OJPAPersistenceProvider      : EntityManager created for persistence unit : com.orientechnologies.orient.object.jpa.OJPAEntityManagerFactory@3d6d542
2019-01-10 19:55:22.990 ERROR 12628 --- [nio-8080-exec-2] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is com.orientechnologies.orient.core.exception.ORecordNotFoundException: The record with id '#42:1' was not found
	DB name="ManchesterPlan02"] with root cause

com.orientechnologies.orient.core.exception.ORecordNotFoundException: The record with id '#42:1' was not found
	DB name="ManchesterPlan02"
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentAbstract.reload(ODatabaseDocumentAbstract.java:1163) ~[orientdb-core-3.0.0.jar:3.0.0]
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentAbstract.reload(ODatabaseDocumentAbstract.java:84) ~[orientdb-core-3.0.0.jar:3.0.0]
	at com.orientechnologies.orient.core.record.ORecordAbstract.reload(ORecordAbstract.java:260) ~[orientdb-core-3.0.0.jar:3.0.0]
	at com.orientechnologies.orient.core.record.ORecordAbstract.reload(ORecordAbstract.java:243) ~[orientdb-core-3.0.0.jar:3.0.0]
	at com.orientechnologies.orient.object.enhancement.OObjectEntitySerializer.toStream(OObjectEntitySerializer.java:1149) ~[orientdb-object-3.0.0.jar:3.0.0]
	at com.orientechnologies.orient.object.enhancement.OObjectEntitySerializer.serializeObject(OObjectEntitySerializer.java:148) ~[orientdb-object-3.0.0.jar:3.0.0]
	at com.orientechnologies.orient.object.db.OObjectDatabaseTx.save(OObjectDatabaseTx.java:499) ~[orientdb-object-3.0.0.jar:3.0.0]
	at com.orientechnologies.orient.object.db.OObjectDatabaseTx.save(OObjectDatabaseTx.java:444) ~[orientdb-object-3.0.0.jar:3.0.0]
	at com.orientechnologies.orient.object.jpa.OJPAEntityManager.persist(OJPAEntityManager.java:68) ~[orientdb-object-3.0.0.jar:3.0.0]
	at Automaticu.WebAPI.ManchesterPlan.Planning.Service.AgentService.addAgent(AgentService.java:45) ~[bin/:na]
	at Automaticu.WebAPI.ManchesterPlan.Planning.Controller.AgentController.addAgent(AgentController.java:35) ~[bin/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_161]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_161]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_161]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_161]
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:209) ~[spring-web-5.0.9.RELEASE.jar:5.0.9.RELEASE]
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:136) ~[spring-web-5.0.9.RELEASE.jar:5.0.9.RELEASE]
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:102) ~[spring-webmvc-5.0.9.RELEASE.jar:5.0.9.RELEASE]
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:891) ~[spring-webmvc-5.0.9.RELEASE.jar:5.0.9.RELEASE]
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:797) ~[spring-webmvc-5.0.9.RELEASE.jar:5.0.9.RELEASE]
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87) ~[spring-webmvc-5.0.9.RELEASE.jar:5.0.9.RELEASE]
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:991) ~[spring-webmvc-5.0.9.RELEASE.jar:5.0.9.RELEASE]
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:925) ~[spring-webmvc-5.0.9.RELEASE.jar:5.0.9.RELEASE]
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:974) ~[spring-webmvc-5.0.9.RELEASE.jar:5.0.9.RELEASE]
	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:877) ~[spring-webmvc-5.0.9.RELEASE.jar:5.0.9.RELEASE]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:661) ~[tomcat-embed-core-8.5.34.jar:8.5.34]
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:851) ~[spring-webmvc-5.0.9.RELEASE.jar:5.0.9.RELEASE]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:742) ~[tomcat-embed-core-8.5.34.jar:8.5.34]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231) ~[tomcat-embed-core-8.5.34.jar:8.5.34]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-8.5.34.jar:8.5.34]
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52) ~[tomcat-embed-websocket-8.5.34.jar:8.5.34]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat-embed-core-8.5.34.jar:8.5.34]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-8.5.34.jar:8.5.34]
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:99) ~[spring-web-5.0.9.RELEASE.jar:5.0.9.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) ~[spring-web-5.0.9.RELEASE.jar:5.0.9.RELEASE]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat-embed-core-8.5.34.jar:8.5.34]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-8.5.34.jar:8.5.34]
	at org.springframework.web.filter.HttpPutFormContentFilter.doFilterInternal(HttpPutFormContentFilter.java:109) ~[spring-web-5.0.9.RELEASE.jar:5.0.9.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) ~[spring-web-5.0.9.RELEASE.jar:5.0.9.RELEASE]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat-embed-core-8.5.34.jar:8.5.34]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-8.5.34.jar:8.5.34]
	at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:93) ~[spring-web-5.0.9.RELEASE.jar:5.0.9.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) ~[spring-web-5.0.9.RELEASE.jar:5.0.9.RELEASE]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat-embed-core-8.5.34.jar:8.5.34]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-8.5.34.jar:8.5.34]
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:200) ~[spring-web-5.0.9.RELEASE.jar:5.0.9.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) ~[spring-web-5.0.9.RELEASE.jar:5.0.9.RELEASE]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat-embed-core-8.5.34.jar:8.5.34]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-8.5.34.jar:8.5.34]
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198) ~[tomcat-embed-core-8.5.34.jar:8.5.34]
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96) [tomcat-embed-core-8.5.34.jar:8.5.34]
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:493) [tomcat-embed-core-8.5.34.jar:8.5.34]
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140) [tomcat-embed-core-8.5.34.jar:8.5.34]
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81) [tomcat-embed-core-8.5.34.jar:8.5.34]
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87) [tomcat-embed-core-8.5.34.jar:8.5.34]
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342) [tomcat-embed-core-8.5.34.jar:8.5.34]
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:800) [tomcat-embed-core-8.5.34.jar:8.5.34]
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66) [tomcat-embed-core-8.5.34.jar:8.5.34]
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:806) [tomcat-embed-core-8.5.34.jar:8.5.34]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1498) [tomcat-embed-core-8.5.34.jar:8.5.34]
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) [tomcat-embed-core-8.5.34.jar:8.5.34]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_161]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_161]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-embed-core-8.5.34.jar:8.5.34]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_161]
```
**Result:**
The object is not created in the database.

According to the documentation ...

**OObjectDatabaseTx.java**
 
``` java
  /**
   * Saves an object to the databasein synchronous mode . First checks if the object is new or not. In case it's new a new ODocument
   * is created and bound to the object, otherwise the ODocument is retrieved and updated. The object is introspected using the Java
   * Reflection to extract the field values. <br> If a multi value (array, collection or map of objects) is passed, then each single
   * object is stored separately.
   */
  public <RET> RET save(final Object iContent) {
    return (RET) save(iContent, (String) null, OPERATION_MODE.SYNCHRONOUS, false, null, null);
  }
```
Is this a bug or do I have to modify my code or configuration for the object to be created?

Thank you

**Comment by xavier-atero** [comment]
The OObjectDatabaseTx class works as expected. The issue was that the name of the table in orientdb (V_Agent) did not match the name of the class (Agent).
