### ISSUE TITLE
IOException: Cannot delete file. Retry limit exceeded. (11)

### ISSUE THREAD

**Issue by rgischk** [orientechnologies/orientdb#8738]
## Expected behavior  
No exception  

## Actual behavior  
Exception occurred on production system  

## Steps to reproduce  
Exact steps to reproduce not known. Following exception occurred on production system. It seems that orientdb was not able to delete a file, but it does not state which file and why. More verbose logging would be helpful here.

- I cannot provide the application code or database.
- The only related/similar issue I found was #3546, but that is supposed to be fixed in 2.0

```
com.orientechnologies.orient.core.exception.ODatabaseException: Error during saving of record with rid #321:0
	DB name="database"
	at com.orientechnologies.orient.core.tx.OTransactionNoTx.saveRecord(OTransactionNoTx.java:203) ~[orientdb-core-2.2.22.jar:2.2.22]
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.save(ODatabaseDocumentTx.java:2758) ~[orientdb-core-2.2.22.jar:2.2.22]
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.save(ODatabaseDocumentTx.java:102) ~[orientdb-core-2.2.22.jar:2.2.22]
	at com.orientechnologies.orient.core.record.impl.ODocument.save(ODocument.java:1805) ~[orientdb-core-2.2.22.jar:2.2.22]
	at com.orientechnologies.orient.core.record.impl.ODocument.save(ODocument.java:1796) ~[orientdb-core-2.2.22.jar:2.2.22]
	at com.orientechnologies.orient.core.sql.OCommandExecutorSQLUpdate.result(OCommandExecutorSQLUpdate.java:357) ~[orientdb-core-2.2.22.jar:2.2.22]
	at com.orientechnologies.orient.core.sql.OCommandExecutorSQLResultsetAbstract.pushResult(OCommandExecutorSQLResultsetAbstract.java:285) ~[orientdb-core-2.2.22.jar:2.2.22]
	at com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.addResult(OCommandExecutorSQLSelect.java:741) ~[orientdb-core-2.2.22.jar:2.2.22]
	at com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.handleResult(OCommandExecutorSQLSelect.java:673) ~[orientdb-core-2.2.22.jar:2.2.22]
	at com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.executeSearchRecord(OCommandExecutorSQLSelect.java:630) ~[orientdb-core-2.2.22.jar:2.2.22]
	at com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.serialIterator(OCommandExecutorSQLSelect.java:1619) ~[orientdb-core-2.2.22.jar:2.2.22]
	at com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.fetchFromTarget(OCommandExecutorSQLSelect.java:1566) ~[orientdb-core-2.2.22.jar:2.2.22]
	at com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.executeSearch(OCommandExecutorSQLSelect.java:525) ~[orientdb-core-2.2.22.jar:2.2.22]
	at com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.execute(OCommandExecutorSQLSelect.java:488) ~[orientdb-core-2.2.22.jar:2.2.22]
	at com.orientechnologies.orient.core.sql.OCommandExecutorSQLDelegate.execute(OCommandExecutorSQLDelegate.java:74) ~[orientdb-core-2.2.22.jar:2.2.22]
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.executeCommand(OAbstractPaginatedStorage.java:3200) ~[orientdb-core-2.2.22.jar:2.2.22]
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.command(OAbstractPaginatedStorage.java:3138) ~[orientdb-core-2.2.22.jar:2.2.22]
	at com.orientechnologies.orient.core.sql.query.OSQLQuery.run(OSQLQuery.java:78) ~[orientdb-core-2.2.22.jar:2.2.22]
	at com.orientechnologies.orient.core.sql.query.OSQLAsynchQuery.run(OSQLAsynchQuery.java:74) ~[orientdb-core-2.2.22.jar:2.2.22]
	at com.orientechnologies.orient.core.query.OQueryAbstract.execute(OQueryAbstract.java:33) ~[orientdb-core-2.2.22.jar:2.2.22]
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.query(ODatabaseDocumentTx.java:755) ~[orientdb-core-2.2.22.jar:2.2.22]
	at com.orientechnologies.orient.core.sql.OCommandExecutorSQLUpdate.execute(OCommandExecutorSQLUpdate.java:291) ~[orientdb-core-2.2.22.jar:2.2.22]
	at com.orientechnologies.orient.core.sql.OCommandExecutorSQLDelegate.execute(OCommandExecutorSQLDelegate.java:74) ~[orientdb-core-2.2.22.jar:2.2.22]
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.executeCommand(OAbstractPaginatedStorage.java:3200) ~[orientdb-core-2.2.22.jar:2.2.22]
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.command(OAbstractPaginatedStorage.java:3138) ~[orientdb-core-2.2.22.jar:2.2.22]
	at com.orientechnologies.orient.core.command.OCommandRequestTextAbstract.execute(OCommandRequestTextAbstract.java:69) ~[orientdb-core-2.2.22.jar:2.2.22]
	at com.tinkerpop.blueprints.impls.orient.OrientGraphCommand.execute(OrientGraphCommand.java:49) ~[orientdb-graphdb-2.2.22.jar:2.2.22]
	at ... <<<application code>>>
Caused by: com.orientechnologies.orient.core.exception.OStorageException: Error in data flush background thread, please restart database and send full stack trace inside of bug report
	DB name="database"
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.checkLowDiskSpaceFullCheckpointRequestsAndBackgroundDataFlushExceptions(OAbstractPaginatedStorage.java:4855) ~[orientdb-core-2.2.22.jar:2.2.22]
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.updateRecord(OAbstractPaginatedStorage.java:1280) ~[orientdb-core-2.2.22.jar:2.2.22]
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.executeSaveRecord(ODatabaseDocumentTx.java:2216) ~[orientdb-core-2.2.22.jar:2.2.22]
	at com.orientechnologies.orient.core.tx.OTransactionNoTx.saveRecord(OTransactionNoTx.java:181) ~[orientdb-core-2.2.22.jar:2.2.22]
	... 210 more
Caused by: java.io.IOException: Cannot delete file. Retry limit exceeded. (11)
	at com.orientechnologies.orient.core.storage.impl.local.paginated.wal.OLogSegment.delete(OLogSegment.java:446) ~[orientdb-core-2.2.22.jar:2.2.22]
	at com.orientechnologies.orient.core.storage.impl.local.paginated.wal.ODiskWriteAheadLog.cutTill(ODiskWriteAheadLog.java:857) ~[orientdb-core-2.2.22.jar:2.2.22]
	at com.orientechnologies.orient.core.storage.cache.local.OWOWCache$PeriodicalFuzzyCheckpointTask.run(OWOWCache.java:2024) ~[orientdb-core-2.2.22.jar:2.2.22]
	... 7 more
```

**Comment by rgischk** [comment]
I just found out, that we lost some logging files on that system, due to a faulty logging configuration. It could be, that this error is not the root cause of the problem, but that is was instead caused by another unknown problem.
Anyways it would be nice to have some more verbose logging about why the file could not have been deleted. And maybe you have an idea what could cause this issue?

**Comment by laa** [comment]
We do not support 2.2.x any more please try on 3.0.21+ version and check whether issue is fixed.
