### ISSUE TITLE
ERROR OLocalPaginatedStorage - Exception `02841DB9`

### ISSUE THREAD

**Issue by diegomtassis** [orientechnologies/orientdb#8749]
### Java Version: 8

Using the object API.
We got the following exception on a production environment.

```
2019-01-31T09:50:13.480+0100 [Thread-11] ERROR OLocalPaginatedStorage - Exception `02841DB9` in storage `plocal:C:/Program Files/Compart/IIC/DBData/database/IICDB`: 2.2.37 (build a7541e7ceeabf592dd9a7b2928b6c023cbc73193, branch 2.2.x)
java.lang.IllegalMonitorStateException: null
	at java.util.concurrent.locks.ReentrantReadWriteLock$Sync.tryRelease(ReentrantReadWriteLock.java:371)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.release(AbstractQueuedSynchronizer.java:1261)
	at java.util.concurrent.locks.ReentrantReadWriteLock$WriteLock.unlock(ReentrantReadWriteLock.java:1131)
	at com.orientechnologies.common.concur.lock.OOneEntryPerKeyLockManager.releaseLock(OOneEntryPerKeyLockManager.java:216)
	at com.orientechnologies.orient.core.storage.impl.local.paginated.atomicoperations.OAtomicOperationsManager.ensureThatComponentsUnlocked(OAtomicOperationsManager.java:509)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.commit(OAbstractPaginatedStorage.java:1878)
	at com.orientechnologies.orient.core.tx.OTransactionOptimistic.doCommit(OTransactionOptimistic.java:541)
	at com.orientechnologies.orient.core.tx.OTransactionOptimistic.commit(OTransactionOptimistic.java:99)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.commit(ODatabaseDocumentTx.java:2908)
	at com.orientechnologies.orient.object.db.OObjectDatabaseTx.commit(OObjectDatabaseTx.java:572)
	at com.orientechnologies.orient.object.db.OObjectDatabaseTx.commit(OObjectDatabaseTx.java:567)
	at com.orientechnologies.orient.object.db.OObjectDatabaseTx.commit(OObjectDatabaseTx.java:78)
```

After this, our persistence layer started to fail.
The server was restarted and the application bahaved correctly since then.

Is there any easy explanation for this error?

This error has been something exceptional. The server has been working for more than 3 months without any similar error. We also have installations exactly equal to this, same environment, same version of the product, same workload, and everything works fine.

I can try to provide more info if necessary.

Thanks.

**Comment by diegomtassis** [comment]
Hi Andrey,

Thanks for the quick answer. 

So you think it happened because of some kind of degradation, right?

We are using orientdb in several of our products, many installations and nothing like that had happened before. As I said, we have installations almost identical to the one that failed, should we expect this error again? If so, is restarting the database the only solution? (we use plocal embedded database there?

For the moment upgrading to 3.0 is not possible for us.
