### ISSUE TITLE
Problem with WAL after updateing from 3.0.6 to 3.0.14

### ISSUE THREAD

**Issue by EricSchreiner** [orientechnologies/orientdb#8750]
## Expected behavior  
We usind Orientdb for years now after update from 3.0.6 to 3.0.14 we see the following errors on shutting down. (Database is broken afterwards....)

## Actual behavior  
see below  

## Steps to reproduce  
Feb. 01, 2019 3:32:57 NACHM. com.orientechnologies.common.log.OLogManager log
SCHWERWIEGEND: Error during WAL writing
java.nio.file.FileAlreadyExistsException: C:\Users\Eric\.picapport.cc\db\db.3.0.14\db.3.0.14.2.wal
	at java.base/sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:87)
	at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:103)
	at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:108)
	at java.base/sun.nio.fs.WindowsFileSystemProvider.newFileChannel(WindowsFileSystemProvider.java:116)
	at java.base/java.nio.channels.FileChannel.open(FileChannel.java:292)
	at java.base/java.nio.channels.FileChannel.open(FileChannel.java:340)
	at com.orientechnologies.orient.core.storage.impl.local.paginated.wal.cas.OWALFile.createWriteWALFile(OWALFile.java:38)
	at com.orientechnologies.orient.core.storage.impl.local.paginated.wal.cas.OCASDiskWriteAheadLog$RecordsWriter.run(OCASDiskWriteAheadLog.java:1862)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:514)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1135)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:844)

Feb. 01, 2019 3:32:57 NACHM. com.orientechnologies.common.log.OLogManager log
SCHWERWIEGEND: Exception in thread 'OrientDB WAL Flush Task'
java.lang.IllegalStateException: java.nio.file.FileAlreadyExistsException: C:\Users\Eric\.picapport.cc\db\db.3.0.14\db.3.0.14.2.wal
	at com.orientechnologies.orient.core.storage.impl.local.paginated.wal.cas.OCASDiskWriteAheadLog$RecordsWriter.run(OCASDiskWriteAheadLog.java:2060)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:514)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1135)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:844)
Caused by: java.nio.file.FileAlreadyExistsException: C:\Users\Eric\.picapport.cc\db\db.3.0.14\db.3.0.14.2.wal
	at java.base/sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:87)
	at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:103)
	at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:108)
	at java.base/sun.nio.fs.WindowsFileSystemProvider.newFileChannel(WindowsFileSystemProvider.java:116)
	at java.base/java.nio.channels.FileChannel.open(FileChannel.java:292)
	at java.base/java.nio.channels.FileChannel.open(FileChannel.java:340)
	at com.orientechnologies.orient.core.storage.impl.local.paginated.wal.cas.OWALFile.createWriteWALFile(OWALFile.java:38)
	at com.orientechnologies.orient.core.storage.impl.local.paginated.wal.cas.OCASDiskWriteAheadLog$RecordsWriter.run(OCASDiskWriteAheadLog.java:1862)
	... 6 more

Feb. 01, 2019 3:32:57 NACHM. com.orientechnologies.common.log.OLogManager log
SCHWERWIEGEND: Error during FSync of WAL data
java.nio.channels.ClosedChannelException
	at java.base/sun.nio.ch.FileChannelImpl.ensureOpen(FileChannelImpl.java:158)
	at java.base/sun.nio.ch.FileChannelImpl.force(FileChannelImpl.java:452)
	at com.orientechnologies.orient.core.storage.impl.local.paginated.wal.cas.OWALChannelFile.force(OWALChannelFile.java:33)
	at com.orientechnologies.orient.core.storage.impl.local.paginated.wal.cas.OCASDiskWriteAheadLog$RecordsWriter.lambda$run$0(OCASDiskWriteAheadLog.java:2030)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1135)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:844)

Feb. 01, 2019 3:32:57 NACHM. com.orientechnologies.common.log.OLogManager log
SCHWERWIEGEND: Exception in thread 'OrientDB WAL Write Task Thread)'
java.nio.channels.ClosedChannelException
	at java.base/sun.nio.ch.FileChannelImpl.ensureOpen(FileChannelImpl.java:158)
	at java.base/sun.nio.ch.FileChannelImpl.force(FileChannelImpl.java:452)
	at com.orientechnologies.orient.core.storage.impl.local.paginated.wal.cas.OWALChannelFile.force(OWALChannelFile.java:33)
	at com.orientechnologies.orient.core.storage.impl.local.paginated.wal.cas.OCASDiskWriteAheadLog$RecordsWriter.lambda$run$0(OCASDiskWriteAheadLog.java:2030)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1135)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:844)

Feb. 01, 2019 3:32:57 NACHM. com.orientechnologies.common.log.OLogManager log
SCHWERWIEGEND: Exception `560E1BF3` in storage `plocal:C:\Users\Eric\.picapport.cc\db/db.3.0.14`: 3.0.14 - Veloce (build ac128c5a9ba4c6dc9d25a32b92962d8863774423, branch 3.0.x)
com.orientechnologies.orient.core.exception.OStorageException: Error during WAL write for storage db.3.0.14
	DB name="db.3.0.14"
	at com.orientechnologies.orient.core.storage.impl.local.paginated.wal.cas.OCASDiskWriteAheadLog.waitTillWriteWillBeFinished(OCASDiskWriteAheadLog.java:657)
	at com.orientechnologies.orient.core.storage.impl.local.paginated.wal.cas.OCASDiskWriteAheadLog.flush(OCASDiskWriteAheadLog.java:1366)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.makeFullCheckpoint(OAbstractPaginatedStorage.java:4343)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.doClose(OAbstractPaginatedStorage.java:4942)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.close(OAbstractPaginatedStorage.java:669)
	at com.orientechnologies.orient.core.storage.OStorageAbstract.shutdown(OStorageAbstract.java:236)
	at com.orientechnologies.orient.core.db.OrientDBEmbedded.internalClose(OrientDBEmbedded.java:486)
	at com.orientechnologies.orient.core.db.OrientDBEmbedded.close(OrientDBEmbedded.java:475)
	at com.orientechnologies.orient.core.db.OrientDB.close(OrientDB.java:292)
	at de.contecon.picapport.db.PicApportDBService.closeOrientDb(PicApportDBService.java:423)
	at de.contecon.picapport.db.PicApportDBService.stopDatabase(PicApportDBService.java:278)
	at de.contecon.picapport.db.PicApportDBService.stopDatabase(PicApportDBService.java:250)
	at de.contecon.picapport.PicApport.shutdown(PicApport.java:1624)
	at de.contecon.picapport.PicApport.doCmd_exit(PicApport.java:1744)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at de.contecon.picapport.PicApportCmdQueue.consumeCommand(PicApportCmdQueue.java:126)
	at de.contecon.picapport.PicApportCmdQueue.access$1(PicApportCmdQueue.java:108)
	at de.contecon.picapport.PicApportCmdQueue$CommandConsumer.run(PicApportCmdQueue.java:160)
	at java.base/java.lang.Thread.run(Thread.java:844)
Caused by: java.util.concurrent.ExecutionException: java.nio.channels.ClosedChannelException
	at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
	at com.orientechnologies.orient.core.storage.impl.local.paginated.wal.cas.OCASDiskWriteAheadLog.waitTillWriteWillBeFinished(OCASDiskWriteAheadLog.java:653)
	... 21 more
Caused by: java.nio.channels.ClosedChannelException
	at java.base/sun.nio.ch.FileChannelImpl.ensureOpen(FileChannelImpl.java:158)
	at java.base/sun.nio.ch.FileChannelImpl.force(FileChannelImpl.java:452)
	at com.orientechnologies.orient.core.storage.impl.local.paginated.wal.cas.OWALChannelFile.force(OWALChannelFile.java:33)
	at com.orientechnologies.orient.core.storage.impl.local.paginated.wal.cas.OCASDiskWriteAheadLog$RecordsWriter.lambda$run$0(OCASDiskWriteAheadLog.java:2030)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1135)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	... 1 more

Feb. 01, 2019 3:32:57 NACHM. com.orientechnologies.common.log.OLogManager log
WARNUNG: $ANSI{green {db=db.3.0.14}} -- error on shutdown storage
com.orientechnologies.orient.core.exception.OStorageException: Error during WAL write for storage db.3.0.14
	DB name="db.3.0.14"
	at com.orientechnologies.orient.core.storage.impl.local.paginated.wal.cas.OCASDiskWriteAheadLog.waitTillWriteWillBeFinished(OCASDiskWriteAheadLog.java:657)
	at com.orientechnologies.orient.core.storage.impl.local.paginated.wal.cas.OCASDiskWriteAheadLog.flush(OCASDiskWriteAheadLog.java:1366)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.makeFullCheckpoint(OAbstractPaginatedStorage.java:4343)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.doClose(OAbstractPaginatedStorage.java:4942)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.close(OAbstractPaginatedStorage.java:669)
	at com.orientechnologies.orient.core.storage.OStorageAbstract.shutdown(OStorageAbstract.java:236)
	at com.orientechnologies.orient.core.db.OrientDBEmbedded.internalClose(OrientDBEmbedded.java:486)
	at com.orientechnologies.orient.core.db.OrientDBEmbedded.close(OrientDBEmbedded.java:475)
	at com.orientechnologies.orient.core.db.OrientDB.close(OrientDB.java:292)
	at de.contecon.picapport.db.PicApportDBService.closeOrientDb(PicApportDBService.java:423)
	at de.contecon.picapport.db.PicApportDBService.stopDatabase(PicApportDBService.java:278)
	at de.contecon.picapport.db.PicApportDBService.stopDatabase(PicApportDBService.java:250)
	at de.contecon.picapport.PicApport.shutdown(PicApport.java:1624)
	at de.contecon.picapport.PicApport.doCmd_exit(PicApport.java:1744)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at de.contecon.picapport.PicApportCmdQueue.consumeCommand(PicApportCmdQueue.java:126)
	at de.contecon.picapport.PicApportCmdQueue.access$1(PicApportCmdQueue.java:108)
	at de.contecon.picapport.PicApportCmdQueue$CommandConsumer.run(PicApportCmdQueue.java:160)
	at java.base/java.lang.Thread.run(Thread.java:844)
Caused by: java.util.concurrent.ExecutionException: java.nio.channels.ClosedChannelException
	at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
	at com.orientechnologies.orient.core.storage.impl.local.paginated.wal.cas.OCASDiskWriteAheadLog.waitTillWriteWillBeFinished(OCASDiskWriteAheadLog.java:653)
	... 21 more
Caused by: java.nio.channels.ClosedChannelException
	at java.base/sun.nio.ch.FileChannelImpl.ensureOpen(FileChannelImpl.java:158)
	at java.base/sun.nio.ch.FileChannelImpl.force(FileChannelImpl.java:452)
	at com.orientechnologies.orient.core.storage.impl.local.paginated.wal.cas.OWALChannelFile.force(OWALChannelFile.java:33)
	at com.orientechnologies.orient.core.storage.impl.local.paginated.wal.cas.OCASDiskWriteAheadLog$RecordsWriter.lambda$run$0(OCASDiskWriteAheadLog.java:2030)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1135)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	... 1 more

**Comment by EricSchreiner** [comment]
Hello @laa,
I hope you remember me from the memory issues we had some time ago. I'm desperate. After updating from 3.0.6 to 3.0.14 we get the nested error described above when we stop our application (It occurs during OrientDB.close(OrientDB.java:292)) I've already checked our multi-threading structure with no result (see attachment) do you have any idea (anything is welcome) what can cause the problem?
[threads.txt](https://github.com/orientechnologies/orientdb/files/2828578/threads.txt)

**Comment by EricSchreiner** [comment]
Hi @laa good to hear from you. And yes it seems you've got it BINGO!!! after replacing the dots with an underscore it seems to work as before. I should have asked you earlier - it would have saved me some hours ;-) now my question is it a bug or feature? Anyway I leave the underscore. Thank you very much and best regards from Graz airport. Eric

**Comment by laa** [comment]
That is a bug of parsing of segment number by file name. I will work on this once I have a gap between tasks.

**Comment by EricSchreiner** [comment]
Hi @laa , thanks again. I decided to switch from dots to underscore so there is no need to hurry...

**Comment by laa** [comment]
Fixed in 3.0.20
