### ISSUE TITLE
Cannot connect to OrientDb with Nginx as reverse proxy

### ISSUE THREAD

**Issue by Maciejszuchta** [orientechnologies/orientdb#8755]
## Expected behavior  
I have an Orient DB setup on my remote Server. Successfully configured Nginx to proxy requests for OrientDb studio and I can successfully access it via web browser.
However, when I want to connect to database from c# .Net Core application I cannot connect to database.

After some time I get:
`Orient.Client.OException: Incorect Protocol Version 0
   at Orient.Client.Protocol.Connection.InitializeServerConnection(String userName, String userPassword)
   at Orient.Client.OServer..ctor(String hostname, Int32 port, String userName, String userPassword)
   at ServiceModule.OrientDbManager.Setup() in D:\***\***\ServiceModule\ServiceModule\GraphSerialization\OrientDb\OrientDbManager.cs:line 40`

My nginx sites-available looks like this:

```
 server {
         listen 80;
         listen 443;
         ssl on;
         ssl_certificate /etc/ssl/200933196.crt;
         ssl_certificate_key /etc/ssl/116740882_decrypted.key;
         server_name orientdb-aitef.mydomain.com;
         location / {
                 proxy_pass http://127.0.0.1:2480;
                 proxy_http_version 1.1;
         }
         location /database {              
                proxy_pass http://127.0.0.1:2424;
        }
 }
```

`location /database` doesn't work because 
```
Orient.Client.OException: Unknown host
   at Orient.Client.Protocol.Connection.InitializeServerConnection(String userName, String userPassword)
   at Orient.Client.OServer..ctor(String hostname, Int32 port, String userName, String userPassword)
   at ServiceModule.OrientDbManager.Setup()
```

Any piece of advice whould be appriciated  on how to configure Nginx with OrientDB.

**Comment by Maciejszuchta** [comment]
Ok i found a solution
I had to add this section to nginx.conf
```
stream{
        upstream stream_orientdb{
                server 127.0.0.1:2424;
        }
        server{
                listen 8080;
                proxy_connect_timeout 5s;
                proxy_timeout 20s;
                proxy_pass stream_orientdb;
        }
}

http {

        ##
        # Basic Settings
        ##

        sendfile on;
        tcp_nopush on;
...
...
...
```

And now I connect to port 8080, from my .NET app like this
```
 ConnectionOptions options = new ConnectionOptions()
            {
                DatabaseName = "demodb",
                DatabaseType = ODatabaseType.Graph,
                HostName = "orientdb-aitef.mydomain.com",
                UserName = "root",
                Password = "password",
                Port = 8080
            };
            try
            {
                Console.WriteLine("1!");
                var server = new OServer(options.HostName, options.Port, options.UserName, options.Password);
                Console.WriteLine("Database " + (server.DatabaseExist(options.DatabaseName, OStorageType.PLocal)?"exists":"doesn't exist"));
                //_database = new ODatabase(options);
                //Console.WriteLine(_database.CountRecords);
                Console.WriteLine("2!");
            }
```
Hope someone finds it usefull in future :)
