### ISSUE TITLE
Exception `786BB8F1` in storage `plocal: ....: Error on update storage configuration is thrown from time to time

### ISSUE THREAD

**Issue by EricSchreiner** [orientechnologies/orientdb#8771]
## Expected behavior  
No Exception

## Actual behavior  
Exception is thrown from timie to time 

## Steps to reproduce  
Hello @laa 

I hope it is OK if I mention you directly. We see this Exception frequently (once every couple of hours) in our Server log (Server is running fro weeks). The strange thing is: The database seems to work fine with no problems. Do you have any ideas what could cause that problem?

ERROR@ 15:13:54.918 Exception Error PhotoCrawler.DirectoryConsumer.run: com.orientechnologies.orient.core.exception.OSerializationException: Error on update storage configuration DB name="db_3_0_14"
Feb. 13, 2019 7:23:10 NACHM. com.orientechnologies.common.log.OLogManager log
SCHWERWIEGEND: **Exception `786BB8F1` in storage `plocal:C:\Users\Picapport\.picapport\db/db_3_0_14`: 3.0.14 - Veloce (build ac128c5a9ba4c6dc9d25a32b92962d8863774423, branch 3.0.x)
com.orientechnologies.orient.core.exception.OSerializationException: Error on update storage configuration**
DB name="db_3_0_14"
at com.orientechnologies.orient.core.storage.impl.local.OStorageConfigurationSegment.update(OStorageConfigurationSegment.java:203)
at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.setValidation(OAbstractPaginatedStorage.java:6105)
at com.orientechnologies.orient.core.db.document.ODatabaseDocumentEmbedded.set(ODatabaseDocumentEmbedded.java:386)
at com.orientechnologies.orient.core.db.document.ODatabaseDocumentAbstract.setValidationEnabled(ODatabaseDocumentAbstract.java:792)
at com.orientechnologies.orient.core.intent.OIntentMassiveInsert.end(OIntentMassiveInsert.java:100)
at com.orientechnologies.orient.core.db.document.ODatabaseDocumentAbstract.internalClose(ODatabaseDocumentAbstract.java:871)
at com.orientechnologies.orient.core.db.ODatabaseDocumentEmbeddedPooled.close(ODatabaseDocumentEmbeddedPooled.java:41)
at de.contecon.picapport.db.DbWrapper.close(Unknown Source)
at de.contecon.picapport.directoryservices.PhotoCrawler$DirectoryConsumer.consume(Unknown Source)
at de.contecon.picapport.directoryservices.PhotoCrawler$DirectoryConsumer.run(Unknown Source)
at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.nio.file.AccessDeniedException: C:\Users\Picapport\.picapport\db\db_3_0_14\database.ocf
at java.base/sun.nio.fs.WindowsException.translateToIOException(Unknown Source)
at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(Unknown Source)
at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(Unknown Source)
at java.base/sun.nio.fs.WindowsFileSystemProvider.newFileChannel(Unknown Source)
at java.base/java.nio.channels.FileChannel.open(Unknown Source)
at java.base/java.nio.channels.FileChannel.open(Unknown Source)
at com.orientechnologies.orient.core.storage.impl.local.OStorageConfigurationSegment.update(OStorageConfigurationSegment.java:197)
... 10 more

**Comment by laa** [comment]
Hi @EricSchreiner .
Caused by: java.nio.file.AccessDeniedException: C:\Users\Picapport.picapport\db\db_3_0_14\database.ocf. Means that you do not have access to the file. Am I mistaken.

**Comment by EricSchreiner** [comment]
Hi @laa,
all directories below .picapport/db have been created by the same server (process) this includes all the files. That's why I think this is a bit strange (cannot be the case)

**Comment by laa** [comment]
OK @EricSchreiner , could you try with 3.0.15 version? We have a different approach when storage configuration under the same infrastructure as the data files. It should help.

**Comment by EricSchreiner** [comment]
Hi @laa OK I've already upated to 3.0.15 yesterday evening I'll come back to you after the weekend....

**Comment by laa** [comment]
OK, see you :-)

**Comment by EricSchreiner** [comment]
Hi @laa, thanks again, you were right. The strange messages seems to have disappeared with 3.0.15.

**Comment by laa** [comment]
@EricSchreiner there is a regression in performance in this release on which I am working on right now. In the case of a lot of duplications, updates can be slow. I suppose to fix it till the end of the week.

**Comment by EricSchreiner** [comment]
HI @laa that sounds good because we also finalizing a new release. So I wait until you've made your fixes.
One more question: Are you involved in the fix of issue #8602 . This also causes us a lot of trouble....

**Comment by laa** [comment]
@EricSchreiner No, that is a layer up to the storage.
