### ISSUE TITLE
Error when using lucene indexes

### ISSUE THREAD

**Issue by Y0ba** [orientechnologies/orientdb#8774]
## Expected behavior  
No Error

## Actual behavior  
First error:
```
ERROR com.orientechnologies.lucene.engine.OLuceneFullTextIndexEngine - $ANSI{green {db=...}} Error on get searcher from Lucene index
java.lang.IllegalStateException: The managed reference has already closed - this is likely a bug when the reference count is modified outside of the ReferenceManager
	at org.apache.lucene.search.ReferenceManager.acquire(ReferenceManager.java:114) ~[lucene-core-7.3.0.jar:7.3.0 98a6b3d642928b1ac9076c6c5a369472581f7633 - woody - 2018-03-28 14:31:58]
	at com.orientechnologies.lucene.engine.OLuceneIndexEngineAbstract.searcher(OLuceneIndexEngineAbstract.java:434) ~[orientdb-lucene-3.0.14.jar:3.0.14]
	at com.orientechnologies.lucene.engine.OLuceneFullTextIndexEngine.getResults(OLuceneFullTextIndexEngine.java:191) ~[orientdb-lucene-3.0.14.jar:3.0.14]
	at com.orientechnologies.lucene.engine.OLuceneFullTextIndexEngine.getInTx(OLuceneFullTextIndexEngine.java:280) ~[orientdb-lucene-3.0.14.jar:3.0.14]
	at com.orientechnologies.lucene.engine.OLuceneFullTextIndexEngine.get(OLuceneFullTextIndexEngine.java:140) ~[orientdb-lucene-3.0.14.jar:3.0.14]
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.doGetIndexValue(OAbstractPaginatedStorage.java:2693) ~[orientdb-core-3.0.14.jar:3.0.14]
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.getIndexValue(OAbstractPaginatedStorage.java:2674) ~[orientdb-core-3.0.14.jar:3.0.14]
	at com.orientechnologies.lucene.index.OLuceneIndexNotUnique.get(OLuceneIndexNotUnique.java:275) ~[orientdb-lucene-3.0.14.jar:3.0.14]
	at com.orientechnologies.lucene.functions.OLuceneSearchOnIndexFunction.searchFromTarget(OLuceneSearchOnIndexFunction.java:118) ~[orientdb-lucene-3.0.14.jar:3.0.14]
	at com.orientechnologies.orient.core.sql.parser.OFunctionCall.executeIndexedFunction(OFunctionCall.java:169) ~[orientdb-core-3.0.14.jar:3.0.14]
	at com.orientechnologies.orient.core.sql.parser.OLevelZeroIdentifier.executeIndexedFunction(OLevelZeroIdentifier.java:96) ~[orientdb-core-3.0.14.jar:3.0.14]
	at com.orientechnologies.orient.core.sql.parser.OBaseIdentifier.executeIndexedFunction(OBaseIdentifier.java:104) ~[orientdb-core-3.0.14.jar:3.0.14]
	at com.orientechnologies.orient.core.sql.parser.OBaseExpression.executeIndexedFunction(OBaseExpression.java:165) ~[orientdb-core-3.0.14.jar:3.0.14]
	at com.orientechnologies.orient.core.sql.parser.OExpression.executeIndexedFunction(OExpression.java:296) ~[orientdb-core-3.0.14.jar:3.0.14]
	at com.orientechnologies.orient.core.sql.parser.OBinaryCondition.executeIndexedFunction(OBinaryCondition.java:137) ~[orientdb-core-3.0.14.jar:3.0.14]
	at com.orientechnologies.orient.core.sql.executor.FetchFromIndexedFunctionStep.init(FetchFromIndexedFunctionStep.java:100) ~[orientdb-core-3.0.14.jar:3.0.14]
	at com.orientechnologies.orient.core.sql.executor.FetchFromIndexedFunctionStep.syncPull(FetchFromIndexedFunctionStep.java:38) ~[orientdb-core-3.0.14.jar:3.0.14]
	at com.orientechnologies.orient.core.sql.executor.OSelectExecutionPlan.fetchNext(OSelectExecutionPlan.java:37) ~[orientdb-core-3.0.14.jar:3.0.14]
	at com.orientechnologies.orient.core.sql.executor.ParallelExecStep.fetchNext(ParallelExecStep.java:83) ~[orientdb-core-3.0.14.jar:3.0.14]
	at com.orientechnologies.orient.core.sql.executor.ParallelExecStep$1.hasNext(ParallelExecStep.java:37) ~[orientdb-core-3.0.14.jar:3.0.14]
	at com.orientechnologies.orient.core.sql.executor.FilterByClustersStep$1.fetchNextItem(FilterByClustersStep.java:58) ~[orientdb-core-3.0.14.jar:3.0.14]
	at com.orientechnologies.orient.core.sql.executor.FilterByClustersStep$1.hasNext(FilterByClustersStep.java:93) ~[orientdb-core-3.0.14.jar:3.0.14]
	at com.orientechnologies.orient.core.sql.executor.DistinctExecutionStep.fetchNext(DistinctExecutionStep.java:91) ~[orientdb-core-3.0.14.jar:3.0.14]
	at com.orientechnologies.orient.core.sql.executor.DistinctExecutionStep.access$000(DistinctExecutionStep.java:15) ~[orientdb-core-3.0.14.jar:3.0.14]
	at com.orientechnologies.orient.core.sql.executor.DistinctExecutionStep$1.hasNext(DistinctExecutionStep.java:43) ~[orientdb-core-3.0.14.jar:3.0.14]
	at com.orientechnologies.orient.core.sql.executor.FilterByClassStep$1.fetchNextItem(FilterByClassStep.java:50) ~[orientdb-core-3.0.14.jar:3.0.14]
	at com.orientechnologies.orient.core.sql.executor.FilterByClassStep$1.hasNext(FilterByClassStep.java:88) ~[orientdb-core-3.0.14.jar:3.0.14]
	at com.orientechnologies.orient.core.sql.parser.OLocalResultSet.fetchNext(OLocalResultSet.java:36) ~[orientdb-core-3.0.14.jar:3.0.14]
	at com.orientechnologies.orient.core.sql.parser.OLocalResultSet.<init>(OLocalResultSet.java:29) ~[orientdb-core-3.0.14.jar:3.0.14]
	at com.orientechnologies.orient.core.sql.parser.OSelectStatement.execute(OSelectStatement.java:285) ~[orientdb-core-3.0.14.jar:3.0.14]
	at com.orientechnologies.orient.core.sql.parser.OStatement.execute(OStatement.java:70) ~[orientdb-core-3.0.14.jar:3.0.14]
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentEmbedded.query(ODatabaseDocumentEmbedded.java:527) ~[orientdb-core-3.0.14.jar:3.0.14]
```
Next error:
```
ERROR com.orientechnologies.orient.core.storage.disk.OLocalPaginatedStorage - Exception `5C615070` in storage `plocal:...`: 3.0.14 - Veloce (build ac128c5a9ba4c6dc9d25a32b92962d8863774423, branch 3.0.x)
com.orientechnologies.lucene.exception.OLuceneIndexException: Error on get searcher from Lucene index
	at com.orientechnologies.lucene.engine.OLuceneIndexEngineAbstract.searcher(OLuceneIndexEngineAbstract.java:437) ~[orientdb-lucene-3.0.14.jar:3.0.14]
	at com.orientechnologies.lucene.engine.OLuceneFullTextIndexEngine.getResults(OLuceneFullTextIndexEngine.java:191) ~[orientdb-lucene-3.0.14.jar:3.0.14]
	at com.orientechnologies.lucene.engine.OLuceneFullTextIndexEngine.getInTx(OLuceneFullTextIndexEngine.java:280) ~[orientdb-lucene-3.0.14.jar:3.0.14]
	at com.orientechnologies.lucene.engine.OLuceneFullTextIndexEngine.get(OLuceneFullTextIndexEngine.java:140) ~[orientdb-lucene-3.0.14.jar:3.0.14]
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.doGetIndexValue(OAbstractPaginatedStorage.java:2693) ~[orientdb-core-3.0.14.jar:3.0.14]
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.getIndexValue(OAbstractPaginatedStorage.java:2674) ~[orientdb-core-3.0.14.jar:3.0.14]
	at com.orientechnologies.lucene.index.OLuceneIndexNotUnique.get(OLuceneIndexNotUnique.java:275) ~[orientdb-lucene-3.0.14.jar:3.0.14]
	at com.orientechnologies.lucene.functions.OLuceneSearchOnIndexFunction.searchFromTarget(OLuceneSearchOnIndexFunction.java:118) ~[orientdb-lucene-3.0.14.jar:3.0.14]
	at com.orientechnologies.orient.core.sql.parser.OFunctionCall.executeIndexedFunction(OFunctionCall.java:169) ~[orientdb-core-3.0.14.jar:3.0.14]
	at com.orientechnologies.orient.core.sql.parser.OLevelZeroIdentifier.executeIndexedFunction(OLevelZeroIdentifier.java:96) ~[orientdb-core-3.0.14.jar:3.0.14]
	at com.orientechnologies.orient.core.sql.parser.OBaseIdentifier.executeIndexedFunction(OBaseIdentifier.java:104) ~[orientdb-core-3.0.14.jar:3.0.14]
	at com.orientechnologies.orient.core.sql.parser.OBaseExpression.executeIndexedFunction(OBaseExpression.java:165) ~[orientdb-core-3.0.14.jar:3.0.14]
	at com.orientechnologies.orient.core.sql.parser.OExpression.executeIndexedFunction(OExpression.java:296) ~[orientdb-core-3.0.14.jar:3.0.14]
	at com.orientechnologies.orient.core.sql.parser.OBinaryCondition.executeIndexedFunction(OBinaryCondition.java:137) ~[orientdb-core-3.0.14.jar:3.0.14]
	at com.orientechnologies.orient.core.sql.executor.FetchFromIndexedFunctionStep.init(FetchFromIndexedFunctionStep.java:100) ~[orientdb-core-3.0.14.jar:3.0.14]
	at com.orientechnologies.orient.core.sql.executor.FetchFromIndexedFunctionStep.syncPull(FetchFromIndexedFunctionStep.java:38) ~[orientdb-core-3.0.14.jar:3.0.14]
	at com.orientechnologies.orient.core.sql.executor.OSelectExecutionPlan.fetchNext(OSelectExecutionPlan.java:37) ~[orientdb-core-3.0.14.jar:3.0.14]
	at com.orientechnologies.orient.core.sql.executor.ParallelExecStep.fetchNext(ParallelExecStep.java:83) ~[orientdb-core-3.0.14.jar:3.0.14]
	at com.orientechnologies.orient.core.sql.executor.ParallelExecStep$1.hasNext(ParallelExecStep.java:37) ~[orientdb-core-3.0.14.jar:3.0.14]
	at com.orientechnologies.orient.core.sql.executor.FilterByClustersStep$1.fetchNextItem(FilterByClustersStep.java:58) ~[orientdb-core-3.0.14.jar:3.0.14]
	at com.orientechnologies.orient.core.sql.executor.FilterByClustersStep$1.hasNext(FilterByClustersStep.java:93) ~[orientdb-core-3.0.14.jar:3.0.14]
	at com.orientechnologies.orient.core.sql.executor.DistinctExecutionStep.fetchNext(DistinctExecutionStep.java:91) ~[orientdb-core-3.0.14.jar:3.0.14]
	at com.orientechnologies.orient.core.sql.executor.DistinctExecutionStep.access$000(DistinctExecutionStep.java:15) ~[orientdb-core-3.0.14.jar:3.0.14]
	at com.orientechnologies.orient.core.sql.executor.DistinctExecutionStep$1.hasNext(DistinctExecutionStep.java:43) ~[orientdb-core-3.0.14.jar:3.0.14]
	at com.orientechnologies.orient.core.sql.executor.FilterByClassStep$1.fetchNextItem(FilterByClassStep.java:50) ~[orientdb-core-3.0.14.jar:3.0.14]
	at com.orientechnologies.orient.core.sql.executor.FilterByClassStep$1.hasNext(FilterByClassStep.java:88) ~[orientdb-core-3.0.14.jar:3.0.14]
	at com.orientechnologies.orient.core.sql.parser.OLocalResultSet.fetchNext(OLocalResultSet.java:36) ~[orientdb-core-3.0.14.jar:3.0.14]
	at com.orientechnologies.orient.core.sql.parser.OLocalResultSet.<init>(OLocalResultSet.java:29) ~[orientdb-core-3.0.14.jar:3.0.14]
	at com.orientechnologies.orient.core.sql.parser.OSelectStatement.execute(OSelectStatement.java:285) ~[orientdb-core-3.0.14.jar:3.0.14]
	at com.orientechnologies.orient.core.sql.parser.OStatement.execute(OStatement.java:70) ~[orientdb-core-3.0.14.jar:3.0.14]
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentEmbedded.query(ODatabaseDocumentEmbedded.java:527) ~[orientdb-core-3.0.14.jar:3.0.14]
...
Caused by: java.lang.IllegalStateException: The managed reference has already closed - this is likely a bug when the reference count is modified outside of the ReferenceManager
	at org.apache.lucene.search.ReferenceManager.acquire(ReferenceManager.java:114) ~[lucene-core-7.3.0.jar:7.3.0 98a6b3d642928b1ac9076c6c5a369472581f7633 - woody - 2018-03-28 14:31:58]
	at com.orientechnologies.lucene.engine.OLuceneIndexEngineAbstract.searcher(OLuceneIndexEngineAbstract.java:434) ~[orientdb-lucene-3.0.14.jar:3.0.14]
	... 45 more
```
## Steps to reproduce  
I don't have steps, since these errors intermittently get thrown when using lucene indexes.

**Comment by Y0ba** [comment]
Also, there is error when closing OrientDB:
```
ERROR com.orientechnologies.lucene.engine.OLuceneFullTextIndexEngine - Error on closing Lucene index
org.apache.lucene.store.AlreadyClosedException: this IndexReader is closed
	at org.apache.lucene.index.IndexReader.decRef(IndexReader.java:239) ~[lucene-core-7.3.0.jar:7.3.0 98a6b3d642928b1ac9076c6c5a369472581f7633 - woody - 2018-03-28 14:31:58]
	at org.apache.lucene.search.SearcherManager.decRef(SearcherManager.java:149) ~[lucene-core-7.3.0.jar:7.3.0 98a6b3d642928b1ac9076c6c5a369472581f7633 - woody - 2018-03-28 14:31:58]
	at org.apache.lucene.search.SearcherManager.decRef(SearcherManager.java:58) ~[lucene-core-7.3.0.jar:7.3.0 98a6b3d642928b1ac9076c6c5a369472581f7633 - woody - 2018-03-28 14:31:58]
	at org.apache.lucene.search.ReferenceManager.release(ReferenceManager.java:274) ~[lucene-core-7.3.0.jar:7.3.0 98a6b3d642928b1ac9076c6c5a369472581f7633 - woody - 2018-03-28 14:31:58]
	at org.apache.lucene.search.ReferenceManager.swapReference(ReferenceManager.java:62) ~[lucene-core-7.3.0.jar:7.3.0 98a6b3d642928b1ac9076c6c5a369472581f7633 - woody - 2018-03-28 14:31:58]
	at org.apache.lucene.search.ReferenceManager.close(ReferenceManager.java:146) ~[lucene-core-7.3.0.jar:7.3.0 98a6b3d642928b1ac9076c6c5a369472581f7633 - woody - 2018-03-28 14:31:58]
	at com.orientechnologies.lucene.engine.OLuceneIndexEngineAbstract.closeSearchManager(OLuceneIndexEngineAbstract.java:302) ~[orientdb-lucene-3.0.14.jar:3.0.14]
	at com.orientechnologies.lucene.engine.OLuceneIndexEngineAbstract.doClose(OLuceneIndexEngineAbstract.java:531) ~[orientdb-lucene-3.0.14.jar:3.0.14]
	at com.orientechnologies.lucene.engine.OLuceneIndexEngineAbstract.close(OLuceneIndexEngineAbstract.java:519) ~[orientdb-lucene-3.0.14.jar:3.0.14]
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.doClose(OAbstractPaginatedStorage.java:4959) ~[orientdb-core-3.0.14.jar:3.0.14]
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.close(OAbstractPaginatedStorage.java:669) ~[orientdb-core-3.0.14.jar:3.0.14]
	at com.orientechnologies.orient.core.storage.OStorageAbstract.shutdown(OStorageAbstract.java:236) ~[orientdb-core-3.0.14.jar:3.0.14]
	at com.orientechnologies.orient.core.db.OrientDBEmbedded.internalClose(OrientDBEmbedded.java:486) ~[orientdb-core-3.0.14.jar:3.0.14]
	at com.orientechnologies.orient.core.Orient$OShutdownOrientDBInstancesHandler.shutdown(Orient.java:796) ~[orientdb-core-3.0.14.jar:3.0.14]
	at com.orientechnologies.orient.core.Orient.shutdown(Orient.java:394) ~[orientdb-core-3.0.14.jar:3.0.14]
	at com.orientechnologies.orient.core.OSignalHandler.handle(OSignalHandler.java:68) ~[orientdb-core-3.0.14.jar:3.0.14]
	at sun.misc.Signal$InternalMiscHandler.handle(Signal.java:198) ~[?:?]
	at jdk.internal.misc.Signal$1.run(Signal.java:220) ~[?:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]
```

**Comment by amnous** [comment]
Hi,
Are there any updates on this issue, I am facing same issue but with OrientDB version 3.0.24 and JAVA 8
