### ISSUE TITLE
Getting "Internal server error" when record ID does not exist in DB.

### ISSUE THREAD

**Issue by petervavro** [orientechnologies/orientdb#8776]
### OS: Mac OS X 10.14.3

Running query : `SELECT * FROM #1543243:18;`
`#1543243:18` does not exists in my DB.

## Expected behavior  
0 records found.

## Actual behavior  
```
Internal server error:

java.lang.NullPointerException
	at com.orientechnologies.orient.core.sql.executor.OSelectExecutionPlanner.lambda$getMinimalSetOfNodesForShardedQuery$0(OSelectExecutionPlanner.java:306)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1603)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
	at com.orientechnologies.orient.core.sql.executor.OSelectExecutionPlanner.getMinimalSetOfNodesForShardedQuery(OSelectExecutionPlanner.java:306)
	at com.orientechnologies.orient.core.sql.executor.OSelectExecutionPlanner.calculateShardingStrategy(OSelectExecutionPlanner.java:272)
	at com.orientechnologies.orient.core.sql.executor.OSelectExecutionPlanner.createExecutionPlan(OSelectExecutionPlanner.java:137)
	at com.orientechnologies.orient.core.sql.parser.OSelectStatement.createExecutionPlan(OSelectStatement.java:291)
	at com.orientechnologies.orient.core.sql.parser.OSelectStatement.execute(OSelectStatement.java:269)
	at com.orientechnologies.orient.core.sql.parser.OStatement.execute(OStatement.java:62)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentEmbedded.command(ODatabaseDocumentEmbedded.java:540)
	at com.orientechnologies.orient.server.network.protocol.http.command.post.OServerCommandPostCommand.executeStatement(OServerCommandPostCommand.java:178)
	at com.orientechnologies.orient.server.network.protocol.http.command.post.OServerCommandPostCommand.execute(OServerCommandPostCommand.java:85)
	at com.orientechnologies.orient.server.network.protocol.http.command.post.OServerCommandPostCommandGraph.execute(OServerCommandPostCommandGraph.java:36)
	at com.orientechnologies.orient.server.network.protocol.http.ONetworkProtocolHttpAbstract.service(ONetworkProtocolHttpAbstract.java:223)
	at com.orientechnologies.orient.server.network.protocol.http.ONetworkProtocolHttpAbstract.execute(ONetworkProtocolHttpAbstract.java:702)
	at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:69)

```

**Comment by luigidellaquila** [comment]
Hi @petervavro 

I just pushed a fix, now the error is managed more gracefully

Thanks

Luigi
