### ISSUE TITLE
EXPORT problems

### ISSUE THREAD

**Issue by 209** [orientechnologies/orientdb#8781]
### Java Version:
openjdk version "1.8.0_191"
OpenJDK Runtime Environment (IcedTea 3.10.0) (Alpine 8.191.12-r0)
OpenJDK 64-Bit Server VM (build 25.191-b12, mixed mode)
## Expected behavior  
Export finish without errors. 

## Actual behavior  
I have 70Mb errors:
`
 java.net.SocketException: Broken pipe (Write failed)
app_1  | 	at java.net.SocketOutputStream.socketWrite0(Native Method)
app_1  | 	at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:111)
app_1  | 	at java.net.SocketOutputStream.write(SocketOutputStream.java:155)
app_1  | 	at java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:82)
app_1  | 	at java.io.BufferedOutputStream.write(BufferedOutputStream.java:121)
app_1  | 	at java.util.zip.DeflaterOutputStream.deflate(DeflaterOutputStream.java:253)
app_1  | 	at java.util.zip.DeflaterOutputStream.write(DeflaterOutputStream.java:211)
app_1  | 	at java.util.zip.GZIPOutputStream.write(GZIPOutputStream.java:145)
app_1  | 	at sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:221)
app_1  | 	at sun.nio.cs.StreamEncoder.implWrite(StreamEncoder.java:282)
app_1  | 	at sun.nio.cs.StreamEncoder.write(StreamEncoder.java:125)
app_1  | 	at sun.nio.cs.StreamEncoder.write(StreamEncoder.java:135)
app_1  | 	at java.io.OutputStreamWriter.write(OutputStreamWriter.java:220)
app_1  | 	at java.io.Writer.write(Writer.java:157)
app_1  | 	at java.io.Writer.append(Writer.java:227)
app_1  | 	at com.orientechnologies.orient.core.serialization.serializer.OJSONWriter.append(OJSONWriter.java:460)
app_1  | 	at com.orientechnologies.orient.core.db.tool.ODatabaseExport.exportRecord(ODatabaseExport.java:636)
app_1  | 	at com.orientechnologies.orient.core.db.tool.ODatabaseExport.exportRecords(ODatabaseExport.java:236)
app_1  | 	at com.orientechnologies.orient.core.db.tool.ODatabaseExport.exportDatabase(ODatabaseExport.java:136)
app_1  | 	at com.orientechnologies.orient.server.network.protocol.http.command.get.OServerCommandGetExportDatabase.exportStandard(OServerCommandGetExportDatabase.java:60)
app_1  | 	at com.orientechnologies.orient.server.network.protocol.http.command.get.OServerCommandGetExportDatabase.execute(OServerCommandGetExportDatabase.java:44)
app_1  | 	at com.orientechnologies.orient.server.network.protocol.http.ONetworkProtocolHttpAbstract.service(ONetworkProtocolHttpAbstract.java:223)
app_1  | 	at com.orientechnologies.orient.server.network.protocol.http.ONetworkProtocolHttpAbstract.execute(ONetworkProtocolHttpAbstract.java:702)
app_1  | 	at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:69)
app_1  | $ANSI{green {db=SN}} 
app_1  | Error on exporting record #15:199464. It seems corrupted; size: 93 bytes, raw content (as string):
app_1  | ==========
app_1  | 
         User7;"out_UserToGroup? in_GroupToUserN??g??@
`
Finally export file size: 547M

## Steps to reproduce  
>connect remote... 
>EXPORT DATABASE ../source/sn.export

And I have problems with WAL: https://github.com/orientechnologies/orientdb/issues/8560

**Comment by 209** [comment]
$ANSI{green {db=SN}} Error on exporting database 'SN' to: streaming.json
app_1  | java.net.SocketException: Broken pipe (Write failed)
app_1  | 	at java.net.SocketOutputStream.socketWrite0(Native Method)
app_1  | 	at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:111)
app_1  | 	at java.net.SocketOutputStream.write(SocketOutputStream.java:155)
app_1  | 	at java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:82)
app_1  | 	at java.io.BufferedOutputStream.write(BufferedOutputStream.java:121)
app_1  | 	at java.util.zip.DeflaterOutputStream.deflate(DeflaterOutputStream.java:253)
app_1  | 	at java.util.zip.DeflaterOutputStream.write(DeflaterOutputStream.java:211)
app_1  | 	at java.util.zip.GZIPOutputStream.write(GZIPOutputStream.java:145)
app_1  | 	at sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:221)
app_1  | 	at sun.nio.cs.StreamEncoder.implClose(StreamEncoder.java:316)
app_1  | 	at sun.nio.cs.StreamEncoder.close(StreamEncoder.java:149)
app_1  | 	at java.io.OutputStreamWriter.close(OutputStreamWriter.java:233)
app_1  | 	at com.orientechnologies.orient.core.serialization.serializer.OJSONWriter.close(OJSONWriter.java:455)
app_1  | 	at com.orientechnologies.orient.core.db.tool.ODatabaseExport.close(ODatabaseExport.java:298)
app_1  | 	at com.orientechnologies.orient.core.db.tool.ODatabaseExport.exportDatabase(ODatabaseExport.java:149)
app_1  | 	at com.orientechnologies.orient.server.network.protocol.http.command.get.OServerCommandGetExportDatabase.exportStandard(OServerCommandGetExportDatabase.java:60)
app_1  | 	at com.orientechnologies.orient.server.network.protocol.http.command.get.OServerCommandGetExportDatabase.execute(OServerCommandGetExportDatabase.java:44)
app_1  | 	at com.orientechnologies.orient.server.network.protocol.http.ONetworkProtocolHttpAbstract.service(ONetworkProtocolHttpAbstract.java:223)
app_1  | 	at com.orientechnologies.orient.server.network.protocol.http.ONetworkProtocolHttpAbstract.execute(ONetworkProtocolHttpAbstract.java:702)
app_1  | 	at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:69)
