### ISSUE TITLE
Exception during parse query for filter by class instance

### ISSUE THREAD

**Issue by vitalii-honchar** [orientechnologies/orientdb#8797]
## Expected behavior  
Query:
```
db.query(new OSQLSynchQuery<>("select from ParentClass where @class instanceof ?"), "ChildClass");
```
returns list of documents which are instances of class `ChildClass`.

## Actual behavior  
Throws exception:
```
com.orientechnologies.orient.core.sql.OCommandSQLParsingException: Error parsing query:
select from ParentClass where @class instanceof ?
                                   ^
Encountered "" at line 1, column 31.
Was expecting one of:
    
	DB name="WicketOrientTestDb"
	at com.orientechnologies.orient.core.sql.parser.OStatementCache.throwParsingException(OStatementCache.java:146)
	at com.orientechnologies.orient.core.sql.parser.OStatementCache.parse(OStatementCache.java:138)
	at com.orientechnologies.orient.core.sql.parser.OStatementCache.get(OStatementCache.java:88)
	at com.orientechnologies.orient.core.sql.parser.OStatementCache.get(OStatementCache.java:70)
	at com.orientechnologies.orient.core.sql.OCommandExecutorSQLAbstract.preParse(OCommandExecutorSQLAbstract.java:235)
	at com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.parse(OCommandExecutorSQLSelect.java:259)
	at com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.parse(OCommandExecutorSQLSelect.java:93)
	at com.orientechnologies.orient.core.sql.OCommandExecutorSQLDelegate.parse(OCommandExecutorSQLDelegate.java:53)
	at com.orientechnologies.orient.core.sql.OCommandExecutorSQLDelegate.parse(OCommandExecutorSQLDelegate.java:34)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.command(OAbstractPaginatedStorage.java:3302)
	at com.orientechnologies.orient.core.sql.query.OSQLQuery.run(OSQLQuery.java:78)
	at com.orientechnologies.orient.core.sql.query.OSQLAsynchQuery.run(OSQLAsynchQuery.java:74)
	at com.orientechnologies.orient.core.sql.query.OSQLSynchQuery.run(OSQLSynchQuery.java:102)
	at com.orientechnologies.orient.core.query.OQueryAbstract.execute(OQueryAbstract.java:33)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.query(ODatabaseDocumentTx.java:756)
```

If try to execute query just like this:
```
db.query(new OSQLSynchQuery<>("select from ParentClass where @class instanceof \"ChildClass\"");
```
all works as expected

## Steps to reproduce  
```
OSchema schema = db.getMetadata().getSchema();
OClass parentClass = schema.createClass("ParentClass");
OClass childClass = schema.createClass("ChildClass");

new ODocument(parentClass).save();
new ODocument(childClass).save();

String sql = "select from ParentClass where @class instanceof ?";

List<ODocument> docs = db.query(new OSQLSynchQuery<>(sql), "ChildClass");

docs.forEach(d -> System.out.println("d = " + d));
```

Thanks,
Vitaliy Gonchar

**Comment by WeaxMe** [comment]
If use `@this` instead `@class` it throws same exception too

**Comment by WeaxMe** [comment]
Same exception with build query `select from Parent where @class in ["Child", "Child2"]` from Java API.
