### ISSUE TITLE
Automatic backups doesn't work

### ISSUE THREAD

**Issue by d3pl0y21** [orientechnologies/orientdb#8813]
## Expected behavior  
The automatic backup should work

## Actual behavior  
I upgraded from OrientDB version 2.2.11 to version 3.0.14 and tested up to version 3.0.17, and still get the same error message during automatic backups.

I copied the contents of the "database" folder to the new installation path, first I got error messages about obsolete lucene indexes that I solved using the following technique: 
https://lucene.apache.org/solr/guide/6_6/indexupgrader-tool.html

After solving this problem, the automatic backups still don't work and I get the following error message: 
```bash
2019-03-11 16:15:59:144 INFO  {db=mdm} ok size=4,00KB compressedSize=62 ratio=99% elapsed=37ms [OAutomaticBackup$2]Exception `60D35EF8` in storage `plocal:/data/orientdb/databases/mdm`: 3.0.17 - Veloce (build 84af3dc7a5f8bca700354564d5fcc3b7545441fc, branch 3.0.x)
java.lang.NullPointerException
        at com.orientechnologies.lucene.engine.OLuceneDirectoryFactory.createDirectory(OLuceneDirectoryFactory.java:32)
        at com.orientechnologies.lucene.engine.OLuceneIndexEngineAbstract.open(OLuceneIndexEngineAbstract.java:221)
        at com.orientechnologies.lucene.engine.OLuceneIndexEngineAbstract.reOpen(OLuceneIndexEngineAbstract.java:203)
        at com.orientechnologies.lucene.engine.OLuceneIndexEngineAbstract.release(OLuceneIndexEngineAbstract.java:603)
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.release(OAbstractPaginatedStorage.java:3815)
        at com.orientechnologies.orient.core.storage.disk.OLocalPaginatedStorage.backup(OLocalPaginatedStorage.java:261)
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentAbstract.backup(ODatabaseDocumentAbstract.java:2409)
        at com.orientechnologies.orient.server.handler.OAutomaticBackup.fullBackupDatabase(OAutomaticBackup.java:370)
        at com.orientechnologies.orient.server.handler.OAutomaticBackup$1.run(OAutomaticBackup.java:188)
        at com.orientechnologies.orient.core.Orient$4.run(Orient.java:466)
        at java.util.TimerThread.mainLoop(Timer.java:555)
        at java.util.TimerThread.run(Timer.java:505)
Exception `60D35EF8` in storage `plocal:/data/orientdb/databases/mdm`: 3.0.17 - Veloce (build 84af3dc7a5f8bca700354564d5fcc3b7545441fc, branch 3.0.x)
java.lang.NullPointerException
        at com.orientechnologies.lucene.engine.OLuceneDirectoryFactory.createDirectory(OLuceneDirectoryFactory.java:32)
        at com.orientechnologies.lucene.engine.OLuceneIndexEngineAbstract.open(OLuceneIndexEngineAbstract.java:221)
        at com.orientechnologies.lucene.engine.OLuceneIndexEngineAbstract.reOpen(OLuceneIndexEngineAbstract.java:203)
        at com.orientechnologies.lucene.engine.OLuceneIndexEngineAbstract.release(OLuceneIndexEngineAbstract.java:603)
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.release(OAbstractPaginatedStorage.java:3815)
        at com.orientechnologies.orient.core.storage.disk.OLocalPaginatedStorage.backup(OLocalPaginatedStorage.java:261)
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentAbstract.backup(ODatabaseDocumentAbstract.java:2409)
        at com.orientechnologies.orient.server.handler.OAutomaticBackup.fullBackupDatabase(OAutomaticBackup.java:370)
        at com.orientechnologies.orient.server.handler.OAutomaticBackup$1.run(OAutomaticBackup.java:188)
        at com.orientechnologies.orient.core.Orient$4.run(Orient.java:466)
        at java.util.TimerThread.mainLoop(Timer.java:555)
        at java.util.TimerThread.run(Timer.java:505)
Error during backup processing, file /tmp/backup/mdm-20190311161502.zip.tmp will be deleted

java.lang.NullPointerException
        at com.orientechnologies.lucene.engine.OLuceneDirectoryFactory.createDirectory(OLuceneDirectoryFactory.java:32)
        at com.orientechnologies.lucene.engine.OLuceneIndexEngineAbstract.open(OLuceneIndexEngineAbstract.java:221)
        at com.orientechnologies.lucene.engine.OLuceneIndexEngineAbstract.reOpen(OLuceneIndexEngineAbstract.java:203)
        at com.orientechnologies.lucene.engine.OLuceneIndexEngineAbstract.release(OLuceneIndexEngineAbstract.java:603)
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.release(OAbstractPaginatedStorage.java:3815)
        at com.orientechnologies.orient.core.storage.disk.OLocalPaginatedStorage.backup(OLocalPaginatedStorage.java:261)
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentAbstract.backup(ODatabaseDocumentAbstract.java:2409)
        at com.orientechnologies.orient.server.handler.OAutomaticBackup.fullBackupDatabase(OAutomaticBackup.java:370)
        at com.orientechnologies.orient.server.handler.OAutomaticBackup$1.run(OAutomaticBackup.java:188)
        at com.orientechnologies.orient.core.Orient$4.run(Orient.java:466)
        at java.util.TimerThread.mainLoop(Timer.java:555)
        at java.util.TimerThread.run(Timer.java:505)
$ANSI{green {db=mdm}} Error on backup of database 'mdm' to directory: /tmp/backup/
java.lang.NullPointerException
        at com.orientechnologies.lucene.engine.OLuceneDirectoryFactory.createDirectory(OLuceneDirectoryFactory.java:32)
        at com.orientechnologies.lucene.engine.OLuceneIndexEngineAbstract.open(OLuceneIndexEngineAbstract.java:221)
        at com.orientechnologies.lucene.engine.OLuceneIndexEngineAbstract.reOpen(OLuceneIndexEngineAbstract.java:203)
        at com.orientechnologies.lucene.engine.OLuceneIndexEngineAbstract.release(OLuceneIndexEngineAbstract.java:603)
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.release(OAbstractPaginatedStorage.java:3815)
        at com.orientechnologies.orient.core.storage.disk.OLocalPaginatedStorage.backup(OLocalPaginatedStorage.java:261)
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentAbstract.backup(ODatabaseDocumentAbstract.java:2409)
        at com.orientechnologies.orient.server.handler.OAutomaticBackup.fullBackupDatabase(OAutomaticBackup.java:370)
        at com.orientechnologies.orient.server.handler.OAutomaticBackup$1.run(OAutomaticBackup.java:188)
        at com.orientechnologies.orient.core.Orient$4.run(Orient.java:466)
        at java.util.TimerThread.mainLoop(Timer.java:555)
        at java.util.TimerThread.run(Timer.java:505)

2019-03-11 16:15:59:168 INFO  Automatic Backup finished: 1 ok, 1 errors [OAutomaticBackup$1]
```
I'm thinking about a data compatibility problem between version 2.2 and version 3.0
The error message is not very explicit, so I don't know where the error may come from as well as how to solve it.

## Steps to reproduce  
<add here>  
<An SQL script to reproduce the problem or a JUnit test case will increase **A LOT** the chance to have a quick fix>

**Comment by andreyvk** [comment]
Had the same issue recently. Orient stops backing up after some time. Had to restart it in order to get rid of the problem

**Comment by jacquipre** [comment]
Hi, we're getting the same error when using the backup functionality with 
```
try (ODatabaseDocumentTx db = // acquire database from pool ) {
            OCommandOutputListener listener = // logs somethings

            try (OutputStream out = new FileOutputStream(path)) {
                db.backup(out, null, null, listener, 1, 2048);
            }
}
```
Our lucene indices are of directory type "ram".

What was the solution for this issue? Why it was closed?
