### ISSUE TITLE
nodejs update whole record ( or Vertex )

### ISSUE THREAD

**Issue by grimace** [orientechnologies/orientdb#8819]
## Expected behavior  
how to update whole record, where multiple fields have changed and I don't want to set every vertex field in statement

## Actual behavior  
it's not clear

## I can do this,
```
          session.update(rid)
              .set({ test:'nothing'})
              .one()
              .then(update => {
                  console.log("Records Updated:", update);
              });
```
but can't do this:
```
          session.update(rid)
              .set(vertex)
              .one()
              .then(update => {
                  console.log("Records Updated:", update);
              });
```
Is that possible, or is there more documentation on how to do this?

**Comment by wolf4ood** [comment]
Hi @grimace 

what's inside vertex variable?

**Comment by grimace** [comment]
It's an Event Object that extends a Vertex and has multiple fields of different types.  For our purposes, we are building an editor ( similar to the studio ) where the contents can be edited and the whole object saved ( updated ) to the DB.

**Comment by wolf4ood** [comment]
@grimace 

do you get an error with this?

```js
session.update(rid)
              .set(vertex)
              .one()
              .then(update => {
                  console.log("Records Updated:", update);
              });
```

**Comment by grimace** [comment]
Yes, I get:
```
Unhandled rejection OrientDB.RequestError: Error parsing query:

     ^
Encountered " <UPDATE> "UPDATE "" at line 1, column 1.
Was expecting one of:
    <WHILE> ...
    <IF> ...
    <FOREACH> ...
    ";" ...
    <IF> ...
    
	DB name="TEST_DB"
	Error Code="1"
    at child.Operation.parseError (/odbproject/node_modules/orientjs/lib/client/network/protocol37/operation.js:1224:13)
    at child.Operation.consume (/odbproject/node_modules/orientjs/lib/client/network/protocol37/operation.js:566:35)
    at ONetworkConnection.Connection.process (/odbproject/node_modules/orientjs/lib/client/network/conn.js:462:17)
    at ONetworkConnection.Connection.handleSocketData (/odbproject/node_modules/orientjs/lib/client/network/conn.js:344:20)
    at Socket.emit (events.js:182:13)
    at addChunk (_stream_readable.js:283:12)
    at readableAddChunk (_stream_readable.js:264:11)
    at Socket.Readable.push (_stream_readable.js:219:10)
    at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
```

**Comment by grimace** [comment]
Turns out if I remove the @rid, @class and @version, then it works fine:
```
            delete vertex['@rid'];
            delete vertex['@class'];
            delete vertex['@version'];
            console.log('vertex: '+JSON.stringify(vertex));
            session.update(rid)
              .set(vertex)
              .one()
              .then(update => {
                  console.log("Records Updated:", update);
              });
```

which is certainly acceptable for me.
