### ISSUE TITLE
Unable to install/start v3.0.18 for Mac

### ISSUE THREAD

**Issue by petervavro** [orientechnologies/orientdb#8826]
## Expected behavior  
As described in readme.txt > QUICK START.

## Actual behavior  
I am not able to install/start OrientDB v3.0.18 on Mac. Getting following error in the terminal :
```
2019-03-28 10:38:30:464 INFO  Loading configuration from: /Users/x/orientdb-3.0.18/config/orientdb-server-config.xml... [OServerConfigurationLoaderXml]Exception in thread "Thread-0" java.lang.NoClassDefFoundError: javax/activation/DataSource
	at com.sun.xml.bind.v2.model.impl.RuntimeBuiltinLeafInfoImpl.<clinit>(RuntimeBuiltinLeafInfoImpl.java:478)
	at com.sun.xml.bind.v2.model.impl.RuntimeTypeInfoSetImpl.<init>(RuntimeTypeInfoSetImpl.java:63)
	at com.sun.xml.bind.v2.model.impl.RuntimeModelBuilder.createTypeInfoSet(RuntimeModelBuilder.java:128)
	at com.sun.xml.bind.v2.model.impl.RuntimeModelBuilder.createTypeInfoSet(RuntimeModelBuilder.java:84)
	at com.sun.xml.bind.v2.model.impl.ModelBuilder.<init>(ModelBuilder.java:162)
	at com.sun.xml.bind.v2.model.impl.RuntimeModelBuilder.<init>(RuntimeModelBuilder.java:92)
	at com.sun.xml.bind.v2.runtime.JAXBContextImpl.getTypeInfoSet(JAXBContextImpl.java:455)
	at com.sun.xml.bind.v2.runtime.JAXBContextImpl.<init>(JAXBContextImpl.java:303)
	at com.sun.xml.bind.v2.runtime.JAXBContextImpl.<init>(JAXBContextImpl.java:139)
	at com.sun.xml.bind.v2.runtime.JAXBContextImpl$JAXBContextBuilder.build(JAXBContextImpl.java:1156)
	at com.sun.xml.bind.v2.ContextFactory.createContext(ContextFactory.java:165)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at javax.xml.bind.ContextFinder.newInstance(ContextFinder.java:297)
	at javax.xml.bind.ContextFinder.newInstance(ContextFinder.java:286)
	at javax.xml.bind.ContextFinder.find(ContextFinder.java:409)
	at javax.xml.bind.JAXBContext.newInstance(JAXBContext.java:721)
	at javax.xml.bind.JAXBContext.newInstance(JAXBContext.java:662)
	at com.orientechnologies.orient.server.config.OServerConfigurationLoaderXml.load(OServerConfigurationLoaderXml.java:66)
	at com.orientechnologies.orient.server.config.OServerConfigurationManager.<init>(OServerConfigurationManager.java:51)
	at com.orientechnologies.orient.server.OServer.startup(OServer.java:309)
	at com.orientechnologies.orient.server.OServer.startup(OServer.java:299)
	at com.orientechnologies.orient.server.OServerMain$1.run(OServerMain.java:48)
Caused by: java.lang.ClassNotFoundException: javax.activation.DataSource
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:582)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	... 25 more
```

## Steps to reproduce  
`$ orientdb-3.0.18/bin/server.sh`

**Comment by bibou1** [comment]
Hi,
I have the same problem, did you find the solution ?

**Comment by bibou1** [comment]
Hi Laa,
Thank you for answering, I can not control the subject, should I paste the code in the orientdb-server-config.xml file? That's what I did and it still does not work, did I have to stick it to a pre-designated place?
Thank you for the time you will take to answer me.

**Comment by grimace** [comment]
This is also happening to me on ubuntu 18 ( with java 11 ).   Is there a way to work around without rebuilding the server?

**Comment by laa** [comment]
Hi guys. I do not need to rebuild server or change XML you need to put jar described by this maven dependency into the server `lib` directory.

**Comment by lancedouglas1** [comment]
FYI, for people looking for that dependency jar, it's here: `http://central.maven.org/maven2/javax/activation/javax.activation-api/1.2.0/javax.activation-api-1.2.0.jar`

I just wget'ed the file into the $ORIENT_INSTALLATION_DIR/lib folder and then ran $ORIENT_INSTALLATION_DIR/bin/server.sh and it worked as expected, now.

**Comment by TomekQl** [comment]
the same problem in debian.
