### ISSUE TITLE
Using ETL to import data from mysql, an "Exception in thread'OrientDB WAL Flush Task'" exception occurs

### ISSUE THREAD

**Issue by nohunt** [orientechnologies/orientdb#8843]
### OS: <centos 6.5 64bit>  

```
Exception in thread 'OrientDB WAL Flush Task'
java.lang.IllegalStateException: java.util.concurrent.ExecutionException: java.io.IOException: Can not fsync file
	at com.orientechnologies.orient.core.storage.impl.local.paginated.wal.cas.OCASDiskWriteAheadLog$RecordsWriter.run(OCASDiskWriteAheadLog.java:2054)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.util.concurrent.ExecutionException: java.io.IOException: Can not fsync file
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at com.orientechnologies.orient.core.storage.impl.local.paginated.wal.cas.OCASDiskWriteAheadLog$RecordsWriter.run(OCASDiskWriteAheadLog.java:1981)
	... 7 more
Caused by: java.io.IOException: Can not fsync file
	at com.orientechnologies.common.jna.ONative.fsync(ONative.java:265)
	at com.orientechnologies.orient.core.storage.impl.local.paginated.wal.cas.OWALFdFile.force(OWALFdFile.java:22)
	at com.orientechnologies.orient.core.storage.impl.local.paginated.wal.cas.OCASDiskWriteAheadLog$RecordsWriter.lambda$run$0(OCASDiskWriteAheadLog.java:2024)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	... 3 more
Caused by: com.sun.jna.LastErrorException: [9] Bad file descriptor
	at com.sun.jna.Native.invokeInt(Native Method)
	at com.sun.jna.Function.invoke(Function.java:419)
	at com.sun.jna.Function.invoke(Function.java:354)
	at com.sun.jna.Library$Handler.invoke(Library.java:244)
	at com.sun.proxy.$Proxy2.fsync(Unknown Source)
	at com.orientechnologies.common.jna.ONative.fsync(ONative.java:263)
	... 6 more
```

restart "server.sh" The following error occurred

```
2019-04-18 14:41:10:349 INFO  12630000 operations were processed, current LSN is OLogSequenceNumber{segment=23, position=18} last LSN is OLogSequenceNumber{segment=26, position=18} [OLocalPaginatedStorage]
2019-04-18 14:41:14:900 INFO  12640000 operations were processed, current LSN is OLogSequenceNumber{segment=23, position=18} last LSN is OLogSequenceNumber{segment=26, position=18} [OLocalPaginatedStorage]
2019-04-18 14:41:19:322 INFO  12650000 operations were processed, current LSN is OLogSequenceNumber{segment=23, position=18} last LSN is OLogSequenceNumber{segment=26, position=18} [OLocalPaginatedStorage]
2019-04-18 14:41:23:698 INFO  12660000 operations were processed, current LSN is OLogSequenceNumber{segment=23, position=18} last LSN is OLogSequenceNumber{segment=26, position=18} [OLocalPaginatedStorage]
```

**Comment by laa** [comment]
Hi please set system property "-Dstorage.wal.allowDirectIO= false" it should solve the issue.

**Comment by nohunt** [comment]
Thank you, let me try it.

**Comment by nohunt** [comment]
> Hi please set system property "-Dstorage.wal.allowDirectIO= false" it should solve the issue.

Thank you, let me try it.

**Comment by nohunt** [comment]
According to the above method, the problem is solved. But at the same time, I modified the JVM to make the memory settings. Because MySQL has 1 billion data. I'm afraid the data is too big. I read it in batches. Because I found that oirentdb reads all the data at once.
