### ISSUE TITLE
v3.0.18 : insert of JSON via REST api suddenly fails on indexes

### ISSUE THREAD

**Issue by rdelangh** [orientechnologies/orientdb#8855]
## Expected behavior  
Continue inserting records as JSON batches, via REST api

## Actual behavior  
I send a new batch of JSON insert requests, and get the following error back from the server:
```
java.lang.ClassCastException: com.orientechnologies.orient.core.index.engine.v1.OCellBTreeSingleValueIndexEngine cannot be cast to com.orientechnologies.lucene.engine.OLuceneIndexEngine
```
The class has 2 indexes:
- one unique SBtree index
- another Lucene index

-> what information do you need from me to help you diagnose this problem ?

## Steps to reproduce  
<add here>  
<An SQL script to reproduce the problem or a JUnit test case will increase **A LOT** the chance to have a quick fix>

**Comment by rdelangh** [comment]
server logs :
```
Exception `39524D53` in storage `plocal:/opt/orientdb/databases/cdrarch`: 3.0.18 - Veloce (build 747595e790a081371496f3bb9c57cec395644d82, branch 3.0.x)
com.orientechnologies.orient.core.exception.OStorageException: Cannot put key value entry in index
        DB name="cdrarch"
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.doCallIndexEngine(OAbstractPaginatedStorage.java:2776)
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.callIndexEngine(OAbstractPaginatedStorage.java:2744)
        at com.orientechnologies.lucene.index.OLuceneIndexNotUnique.getTransactionChanges(OLuceneIndexNotUnique.java:232)
        at com.orientechnologies.lucene.index.OLuceneIndexNotUnique.put(OLuceneIndexNotUnique.java:290)
        at com.orientechnologies.lucene.index.OLuceneIndexNotUnique.put(OLuceneIndexNotUnique.java:52)
        at com.orientechnologies.orient.core.index.OClassIndexManager.putInIndex(OClassIndexManager.java:107)
        at com.orientechnologies.orient.core.index.OClassIndexManager.applyChanges(OClassIndexManager.java:433)
        at com.orientechnologies.orient.core.index.OClassIndexManager.checkIndexesAfterCreate(OClassIndexManager.java:62)
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentEmbedded.afterCreateOperations(ODatabaseDocumentEmbedded.java:978)
        at com.orientechnologies.orient.core.tx.OTransactionOptimistic.addRecord(OTransactionOptimistic.java:474)
        at com.orientechnologies.orient.core.tx.OTransactionOptimistic.saveRecord(OTransactionOptimistic.java:322)
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentAbstract.saveInternal(ODatabaseDocumentAbstract.java:2132)
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentAbstract.save(ODatabaseDocumentAbstract.java:2097)
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentAbstract.save(ODatabaseDocumentAbstract.java:138)
        at com.orientechnologies.orient.core.record.impl.ODocument.save(ODocument.java:2169)
        at com.orientechnologies.orient.core.record.impl.ODocument.save(ODocument.java:2160)
        at com.orientechnologies.orient.server.network.protocol.http.command.post.OServerCommandPostBatch.execute(OServerCommandPostBatch.java:120)
        at com.orientechnologies.orient.server.network.protocol.http.ONetworkProtocolHttpAbstract.service(ONetworkProtocolHttpAbstract.java:223)
        at com.orientechnologies.orient.server.network.protocol.http.ONetworkProtocolHttpAbstract.execute(ONetworkProtocolHttpAbstract.java:702)
        at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:69)
Caused by: java.lang.ClassCastException: com.orientechnologies.orient.core.index.engine.v1.OCellBTreeSingleValueIndexEngine cannot be cast to com.orientechnologies.lucene.engine.OLuceneIndexEngine
        at com.orientechnologies.lucene.index.OLuceneIndexNotUnique.lambda$getTransactionChanges$3(OLuceneIndexNotUnique.java:233)
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.doCallIndexEngine(OAbstractPaginatedStorage.java:2773)
        ... 19 more
Exception `0BCAEB5E` in storage `plocal:/opt/orientdb/databases/cdrarch`: 3.0.18 - Veloce (build 747595e790a081371496f3bb9c57cec395644d82, branch 3.0.x)
com.orientechnologies.orient.core.exception.OStorageException: Cannot put key value entry in index
        DB name="cdrarch"
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.doCallIndexEngine(OAbstractPaginatedStorage.java:2776)
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.callIndexEngine(OAbstractPaginatedStorage.java:2744)
        at com.orientechnologies.lucene.index.OLuceneIndexNotUnique.getTransactionChanges(OLuceneIndexNotUnique.java:232)
        at com.orientechnologies.lucene.index.OLuceneIndexNotUnique.put(OLuceneIndexNotUnique.java:290)
        at com.orientechnologies.lucene.index.OLuceneIndexNotUnique.put(OLuceneIndexNotUnique.java:52)
        at com.orientechnologies.orient.core.index.OClassIndexManager.putInIndex(OClassIndexManager.java:107)
        at com.orientechnologies.orient.core.index.OClassIndexManager.applyChanges(OClassIndexManager.java:433)
        at com.orientechnologies.orient.core.index.OClassIndexManager.checkIndexesAfterCreate(OClassIndexManager.java:62)
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentEmbedded.afterCreateOperations(ODatabaseDocumentEmbedded.java:978)
        at com.orientechnologies.orient.core.tx.OTransactionOptimistic.addRecord(OTransactionOptimistic.java:474)
        at com.orientechnologies.orient.core.tx.OTransactionOptimistic.saveRecord(OTransactionOptimistic.java:322)
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentAbstract.saveInternal(ODatabaseDocumentAbstract.java:2132)
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentAbstract.save(ODatabaseDocumentAbstract.java:2097)
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentAbstract.save(ODatabaseDocumentAbstract.java:138)
        at com.orientechnologies.orient.core.record.impl.ODocument.save(ODocument.java:2169)
        at com.orientechnologies.orient.core.record.impl.ODocument.save(ODocument.java:2160)
        at com.orientechnologies.orient.server.network.protocol.http.command.post.OServerCommandPostBatch.execute(OServerCommandPostBatch.java:120)
        at com.orientechnologies.orient.server.network.protocol.http.ONetworkProtocolHttpAbstract.service(ONetworkProtocolHttpAbstract.java:223)
        at com.orientechnologies.orient.server.network.protocol.http.ONetworkProtocolHttpAbstract.execute(ONetworkProtocolHttpAbstract.java:702)
        at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:69)
Caused by: java.lang.ClassCastException: com.orientechnologies.orient.core.index.engine.v1.OCellBTreeSingleValueIndexEngine cannot be cast to com.orientechnologies.lucene.engine.OLuceneIndexEngine
        at com.orientechnologies.lucene.index.OLuceneIndexNotUnique.lambda$getTransactionChanges$3(OLuceneIndexNotUnique.java:233)
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.doCallIndexEngine(OAbstractPaginatedStorage.java:2773)
        ... 19 more
```

**Comment by rdelangh** [comment]
there are already some 24.5 M records inserted with this same method till now. But any new attempt to insert more records is producing the above error.

**Comment by rdelangh** [comment]
I have rebuilt these 2 indexes of this class, with no better result.
We store those records in multiple classes, all with identical layout, just the dates in the records determine in which of such class they will be insert; so I have found that in a next class (for other dates) there is a very single (=1) record existing. I have rebuilt also the same indexes of that other class, and now I get a different error during my insert attempts:
```
java.lang.UnsupportedOperationException: Validated put is not supported by OLuceneFullTextIndexEngine
```
The insert operations are sent via the REST api in JSON format , and look like this:
```
{ "transaction": true, "operations": [ { "type": "c", "record": { "@class":"cdr_af_20180506", ... }, { "@class":"cdr_af_20180506", ... }, ... ] }
```

**Comment by laa** [comment]
Hi, did you put 3.0.18 jars over existing database or created a new one?

**Comment by rdelangh** [comment]
hi @laa, thx for commenting !
I have taken an existing dbase, emptied it entirely (= dropped ALL classes), then created the classes from scratch again.
So there should have been nothing in the indexes neither anymore, all empty.

In this class, there is now already about 25M records newly inserted via 3.0.18 without problems. But now it is stuck...

**Comment by myflowpl** [comment]
@rdelangh did you solve this problem ?

Had the same issue, I'm migrating from 2.2 to 3.0.19 for me it was:
1 - now indexes don't support by default null, so if I want to add document withoud field with index, I got this error
2 - I had to rebuild all idexes

now it is working again

**Comment by laa** [comment]
Hi, if that is still actual we will work on that. Otherwise, we will close the issue.

**Comment by myflowpl** [comment]
I solved this issue and posted my workaround, so for me you can close it.
