### ISSUE TITLE
Can`t run server.sh

### ISSUE THREAD

**Issue by Xaiot** [orientechnologies/orientdb#8863]
## Expected behavior  
it should start a server

## Actual behavior  
Cannot  run server.sh

I can`t run server.sh here is log:
2019-05-07 20:22:30:004 INFO  Detected limit of amount of simultaneously open files is 4096,  limit of open files for disk cache will be set to 1536 [ONative]
2019-05-07 20:22:30:006 WARNI Value of limit of simultaneously open files is too small, recommended value is 262144 [ONative]
2019-05-07 20:22:30:016 INFO  Loading configuration from: /home/xaiot/OrientDb/orientdb-3.0.18/config/orientdb-server-config.xml... [OServerConfigurationLoaderXml]
2019-05-07 20:22:30:179 INFO  OrientDB Server v3.0.18 - Veloce (build 747595e790a081371496f3bb9c57cec395644d82, branch 3.0.x) is starting up... [OServer]
2019-05-07 20:22:30:228 INFO  12485132288 B/11906 MB/11 GB of physical memory were detected on machine [ONative]
2019-05-07 20:22:30:228 INFO  Soft memory limit for this process is set to -1 B/-1 MB/-1 GB [ONative]
2019-05-07 20:22:30:229 INFO  Hard memory limit for this process is set to -1 B/-1 MB/-1 GB [ONative]
2019-05-07 20:22:30:229 INFO  Path to 'memory' cgroup is '/' [ONative]
2019-05-07 20:22:30:232 INFO  Mounting path for memory cgroup controller is '/sys/fs/cgroup/memory' [ONative]
2019-05-07 20:22:30:232 INFO  cgroup soft memory limit is 9223372036854771712 B/8796093022207 MB/8589934591 GB [ONative]
2019-05-07 20:22:30:233 INFO  cgroup hard memory limit is 9223372036854771712 B/8796093022207 MB/8589934591 GB [ONative]
2019-05-07 20:22:30:233 INFO  Detected memory limit for current process is 12485132288 B/11906 MB/11 GB [ONative]
2019-05-07 20:22:30:234 INFO  JVM can use maximum 228MB of heap memory [OMemoryAndLocalPaginatedEnginesInitializer]
2019-05-07 20:22:30:234 INFO  Because OrientDB is running outside a container 12% of memory will be left unallocated according to the setting 'memory.leftToOS' not taking into account heap memory [OMemoryAndLocalPaginatedEnginesInitializer]
2019-05-07 20:22:30:235 INFO  OrientDB auto-config DISKCACHE=10,249MB (heap=228MB os=11,906MB) [orientechnologies]
2019-05-07 20:22:30:237 INFO  System is started under an effective user : `root` [OEngineLocalPaginated]
2019-05-07 20:22:30:276 INFO  WAL maximum segment size is set to 6,144 MB [OrientDBDistributed]
2019-05-07 20:22:30:277 INFO  Databases directory: /home/xaiot/OrientDb/orientdb-3.0.18/databases [OServer]
2019-05-07 20:22:30:336 INFO  Direct IO for WAL located in /home/xaiot/OrientDb/orientdb-3.0.18/databases/OSystem is allowed with block size 4096 bytes. [OCASDiskWriteAheadLog]
2019-05-07 20:22:30:336 INFO  Page size for WAL located in /home/xaiot/OrientDb/orientdb-3.0.18/databases/OSystem is set to 4096 bytes. [OCASDiskWriteAheadLog]Exception `2983508C` in storage `plocal:/home/xaiot/OrientDb/orientdb-3.0.18/databases/OSystem`: 3.0.18 - Veloce (build 747595e790a081371496f3bb9c57cec395644d82, branch 3.0.x)
com.orientechnologies.orient.core.exception.OStorageException: Database is locked by another process, please shutdown process and try again
	at com.orientechnologies.orient.core.storage.impl.local.paginated.OPaginatedStorageDirtyFlag.lockFile(OPaginatedStorageDirtyFlag.java:102)
	at com.orientechnologies.orient.core.storage.impl.local.paginated.OPaginatedStorageDirtyFlag.open(OPaginatedStorageDirtyFlag.java:127)
	at com.orientechnologies.orient.core.storage.disk.OLocalPaginatedStorage.checkIfStorageDirty(OLocalPaginatedStorage.java:432)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.open(OAbstractPaginatedStorage.java:372)
	at com.orientechnologies.orient.core.db.OrientDBEmbedded.openNoAuthorization(OrientDBEmbedded.java:257)
	at com.orientechnologies.orient.core.db.OrientDBEmbedded.openNoAuthorization(OrientDBEmbedded.java:59)
	at com.orientechnologies.orient.server.OSystemDatabase.openSystemDatabase(OSystemDatabase.java:97)
	at com.orientechnologies.orient.server.OSystemDatabase.checkServerId(OSystemDatabase.java:174)
	at com.orientechnologies.orient.server.OSystemDatabase.init(OSystemDatabase.java:162)
	at com.orientechnologies.orient.server.OSystemDatabase.<init>(OSystemDatabase.java:49)
	at com.orientechnologies.orient.server.OServer.initSystemDatabase(OServer.java:1212)
	at com.orientechnologies.orient.server.OServer.activate(OServer.java:421)
	at com.orientechnologies.orient.server.OServerMain$1.run(OServerMain.java:48)

2019-05-07 20:22:30:464 INFO  - shutdown storage: OSystem... [OrientDBDistributed]Error during server execution
com.orientechnologies.orient.core.exception.ODatabaseException: Cannot open database 'OSystem'
	at com.orientechnologies.orient.core.db.OrientDBEmbedded.openNoAuthorization(OrientDBEmbedded.java:266)
	at com.orientechnologies.orient.core.db.OrientDBEmbedded.openNoAuthorization(OrientDBEmbedded.java:59)
	at com.orientechnologies.orient.server.OSystemDatabase.openSystemDatabase(OSystemDatabase.java:97)
	at com.orientechnologies.orient.server.OSystemDatabase.checkServerId(OSystemDatabase.java:174)
	at com.orientechnologies.orient.server.OSystemDatabase.init(OSystemDatabase.java:162)
	at com.orientechnologies.orient.server.OSystemDatabase.<init>(OSystemDatabase.java:49)
	at com.orientechnologies.orient.server.OServer.initSystemDatabase(OServer.java:1212)
	at com.orientechnologies.orient.server.OServer.activate(OServer.java:421)
	at com.orientechnologies.orient.server.OServerMain$1.run(OServerMain.java:48)
Caused by: com.orientechnologies.orient.core.exception.OStorageException: Database is locked by another process, please shutdown process and try again
	at com.orientechnologies.orient.core.storage.impl.local.paginated.OPaginatedStorageDirtyFlag.lockFile(OPaginatedStorageDirtyFlag.java:102)
	at com.orientechnologies.orient.core.storage.impl.local.paginated.OPaginatedStorageDirtyFlag.open(OPaginatedStorageDirtyFlag.java:127)
	at com.orientechnologies.orient.core.storage.disk.OLocalPaginatedStorage.checkIfStorageDirty(OLocalPaginatedStorage.java:432)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.open(OAbstractPaginatedStorage.java:372)
	at com.orientechnologies.orient.core.db.OrientDBEmbedded.openNoAuthorization(OrientDBEmbedded.java:257)
	... 8 more

**Comment by ASXHOLE** [comment]
hi，
Your database file is locked  by another process. You can kill all OrientDB process and run server.sh again.
Hope this helps.

**Comment by laa** [comment]
yes that is correct
