### ISSUE TITLE
ODB 3.x supports modern Java time types (Instant, LocalDate)?

### ISSUE THREAD

**Issue by hrstoyanov** [orientechnologies/orientdb#8868]
### OS: Windows  

I have a schema field:
``` 
CREATE PROPERTY Action.on  DATETIME  (MANDATORY TRUE, DEFAULT "sysdate()", READONLY TRUE);
```

and I would like to store ```java.time.Instant``` value:
```
 action.setProperty("on", Instant.now());
```

but getting:

```
java.lang.ClassCastException: java.time.Instant cannot be cast to java.util.Date
        at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerNetworkV37.serializeValue(ORecordSerializerNetworkV37.java:546)
        at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerNetworkV37.serialize(ORecordSerializerNetworkV37.java:157)
        at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerNetworkV37.serializeValue(ORecordSerializerNetworkV37.java:563)
        at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerNetworkV37.serialize(ORecordSerializerNetworkV37.java:157)
        at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerNetworkV37.toStream(ORecordSerializerNetworkV37.java:874)

```

**Comment by luigidellaquila** [comment]
Hi @hrstoyanov 

Right now OrientDB only supports Date type, not other java date types, so you have to convert it to java.util.Date.
I'm marking it as an enhancement, we will likely support it in the future

Thanks

Luigi

**Comment by hrstoyanov** [comment]
Thanks @luigidellaquila 
Do you have any code  pointer for me (where to look in the codebase in general), so I can try to fix this myself.

**Comment by luigidellaquila** [comment]
Hi @hrstoyanov 

It's not an easy topic in general, it can be managed in different ways.
A possible approach is to support new data types, in this case you can check com.orientechnologies.orient.core.metadata.schema.OType class and see where it is used

Thanks

Luigi
