### ISSUE TITLE
exited with code 137

### ISSUE THREAD

**Issue by freeart** [orientechnologies/orientdb#8871]
### OS: docker openjdk:8-jdk-alpine  

Hi!
I have an issue about out of memory (I hope) on the machine without any activity. Seems like a memory leak
The base has few rows in the single table and nobody works with it. And every 2-3 weeks orientdb is in down. The server has 3.7Gb ram. And the same situation on the prod server with 7.6Gb ram. 
Lines in log:
```
orientdb-develop | 2019-05-06 11:54:34:764 INFO  Detected limit of amount of simultaneously open files is 1048576,  limit of open files for disk cache will be set to 523776 [ONative]
orientdb-develop | 2019-05-06 11:54:34:792 INFO  Loading configuration from: /orientdb/config/orientdb-server-config.xml... [OServerConfigurationLoaderXml]
orientdb-develop | 2019-05-06 11:54:35:114 INFO  OrientDB Server v3.1.0-SNAPSHOT - Veloce (build d970b12033f0462f0239ea0ad8ed41207e6e26f1, branch develop) is starting up... [OServer]
orientdb-develop | 2019-05-06 11:54:35:208 INFO  4035751936 B/3848 MB/3 GB of physical memory were detected on machine [ONative]
orientdb-develop | 2019-05-06 11:54:35:209 INFO  Soft memory limit for this process is set to -1 B/-1 MB/-1 GB [ONative]
orientdb-develop | 2019-05-06 11:54:35:209 INFO  Hard memory limit for this process is set to -1 B/-1 MB/-1 GB [ONative]
orientdb-develop | 2019-05-06 11:54:35:210 INFO  Path to 'memory' cgroup is '/docker/4421acd5770caa5c74227e89876331b09d3c1cddd58f25c200368d7895ae9192' [ONative]
orientdb-develop | 2019-05-06 11:54:35:215 INFO  Mounting path for memory cgroup controller is '/sys/fs/cgroup/memory' [ONative]
orientdb-develop | 2019-05-06 11:54:35:216 INFO  Can not find '/sys/fs/cgroup/memory/docker/4421acd5770caa5c74227e89876331b09d3c1cddd58f25c200368d7895ae9192' path for memory cgroup, it is supposed that process is running in container, will try to read root '/sys/fs/cgroup/memory' memory cgroup data [ONative]
orientdb-develop | 2019-05-06 11:54:35:216 INFO  cgroup soft memory limit is 9223372036854771712 B/8796093022207 MB/8589934591 GB [ONative]
orientdb-develop | 2019-05-06 11:54:35:217 INFO  cgroup hard memory limit is 9223372036854771712 B/8796093022207 MB/8589934591 GB [ONative]
orientdb-develop | 2019-05-06 11:54:35:218 INFO  Detected memory limit for current process is 4035751936 B/3848 MB/3 GB [ONative]
orientdb-develop | 2019-05-06 11:54:35:219 INFO  JVM can use maximum 1963MB of heap memory [OMemoryAndLocalPaginatedEnginesInitializer]
orientdb-develop | 2019-05-06 11:54:35:219 INFO  Because OrientDB is running inside a container 256m of memory will be left unallocated according to the setting 'memory.leftToContainer' not taking into account heap memory [OMemoryAndLocalPaginatedEnginesInitializer]
orientdb-develop | 2019-05-06 11:54:35:220 INFO  OrientDB auto-config DISKCACHE=1,629MB (heap=1,963MB os=3,848MB) [orientechnologies]
orientdb-develop | 2019-05-06 11:54:35:225 INFO  System is started under an effective user : `root` [OEngineLocalPaginated]
orientdb-develop | 2019-05-06 11:54:35:267 INFO  WAL maximum segment size is set to 6,144 MB [OrientDBDistributed]
orientdb-develop | 2019-05-06 11:54:35:271 INFO  Databases directory: /orientdb/databases [OServer]
orientdb-develop | 2019-05-06 11:54:35:399 INFO  Direct IO for WAL located in /orientdb/databases/OSystem is allowed with block size 4096 bytes. [OCASDiskWriteAheadLog]
orientdb-develop | 2019-05-06 11:54:35:400 INFO  Page size for WAL located in /orientdb/databases/OSystem is set to 4096 bytes. [OCASDiskWriteAheadLog]
orientdb-develop | 2019-05-06 11:54:36:071 INFO  Storage 'plocal:/orientdb/databases/OSystem' is opened under OrientDB distribution : 3.1.0-SNAPSHOT - Veloce (build d970b12033f0462f0239ea0ad8ed41207e6e26f1, branch develop) [OLocalPaginatedStorage]
orientdb-develop | 2019-05-06 11:54:36:548 INFO  Listening binary connections on 0.0.0.0:2424 (protocol v.37, socket=default) [OServerNetworkListener]
orientdb-develop | 2019-05-06 11:54:36:555 INFO  Listening http connections on 0.0.0.0:2480 (protocol v.10, socket=default) [OServerNetworkListener]
orientdb-develop | 2019-05-06 11:54:36:563 INFO  Found ORIENTDB_ROOT_PASSWORD variable, using this value as root's password [OServer]
orientdb-develop | 2019-05-06 11:54:37:394 INFO  Installing dynamic plugin 'orientdb-etl-3.1.0-SNAPSHOT.jar'... [OServerPluginManager]
orientdb-develop | 2019-05-06 11:54:37:402 INFO  Installing dynamic plugin 'orientdb-studio-3.1.0-20181211.100617-23.zip'... [OServerPluginManager]
orientdb-develop | 2019-05-06 11:54:37:407 INFO  ODefaultPasswordAuthenticator is active [ODefaultPasswordAuthenticator]
orientdb-develop | 2019-05-06 11:54:37:408 INFO  OServerConfigAuthenticator is active [OServerConfigAuthenticator]
orientdb-develop | 2019-05-06 11:54:37:409 INFO  OSystemUserAuthenticator is active [OSystemUserAuthenticator]
orientdb-develop | 2019-05-06 11:54:37:411 INFO  [OVariableParser.resolveVariables] Property not found: distributed [orientechnologies]
orientdb-develop | 2019-05-06 11:54:37:420 WARNI Authenticated clients can execute any kind of code into the server by using the following allowed languages: [sql] [OServerSideScriptInterpreter]
orientdb-develop | 2019-05-06 11:54:37:424 INFO  OrientDB Studio available at http://x.x.x.x:2480/studio/index.html [OServer]
orientdb-develop | 2019-05-06 11:54:37:424 INFO  OrientDB Server is active v3.1.0-SNAPSHOT - Veloce (build d970b12033f0462f0239ea0ad8ed41207e6e26f1, branch develop). [OServer]
orientdb-develop | 2019-05-06 11:55:22:321 INFO  Direct IO for WAL located in /orientdb/databases/shsh is allowed with block size 4096 bytes. [OCASDiskWriteAheadLog]
orientdb-develop | 2019-05-06 11:55:22:322 INFO  Page size for WAL located in /orientdb/databases/shsh is set to 4096 bytes. [OCASDiskWriteAheadLog]
orientdb-develop | 2019-05-06 11:55:22:522 INFO  Storage 'plocal:/orientdb/databases/shsh' is opened under OrientDB distribution : 3.1.0-SNAPSHOT - Veloce (build d970b12033f0462f0239ea0ad8ed41207e6e26f1, branch develop) [OLocalPaginatedStorage]
orientdb-develop | 2019-05-06 11:59:35:375 INFO  Making fuzzy checkpoint [OLocalPaginatedStorage]
orientdb-develop | 2019-05-06 12:00:22:321 INFO  Making fuzzy checkpoint [OLocalPaginatedStorage]
orientdb-develop | 2019-05-06 13:15:22:336 INFO  Making fuzzy checkpoint [OLocalPaginatedStorage]
orientdb-develop | 2019-05-07 14:25:22:495 INFO  Making fuzzy checkpoint [OLocalPaginatedStorage]
orientdb-develop | 2019-05-07 14:55:22:507 INFO  Making fuzzy checkpoint [OLocalPaginatedStorage]
orientdb-develop | 2019-05-07 15:35:22:519 INFO  Making fuzzy checkpoint [OLocalPaginatedStorage]
orientdb-develop | 2019-05-13 07:25:23:125 INFO  Making fuzzy checkpoint [OLocalPaginatedStorage]
orientdb-develop | 2019-05-13 07:55:23:137 INFO  Making fuzzy checkpoint [OLocalPaginatedStorage]
orientdb-develop | 2019-05-13 08:30:23:145 INFO  Making fuzzy checkpoint [OLocalPaginatedStorage]
orientdb-develop | 2019-05-13 09:10:23:157 INFO  Making fuzzy checkpoint [OLocalPaginatedStorage]
orientdb-develop | 2019-05-13 10:15:23:169 INFO  Making fuzzy checkpoint [OLocalPaginatedStorage]
orientdb-develop | 2019-05-13 10:30:23:177 INFO  Making fuzzy checkpoint [OLocalPaginatedStorage]
orientdb-develop | 2019-05-13 11:15:23:187 INFO  Making fuzzy checkpoint [OLocalPaginatedStorage]
orientdb-develop | 2019-05-13 12:35:23:199 INFO  Making fuzzy checkpoint [OLocalPaginatedStorage]
orientdb-develop | 2019-05-13 13:05:23:207 INFO  Making fuzzy checkpoint [OLocalPaginatedStorage]
orientdb-develop | 2019-05-13 13:40:23:217 INFO  Making fuzzy checkpoint [OLocalPaginatedStorage]
orientdb-develop | 2019-05-13 14:50:23:230 INFO  Making fuzzy checkpoint [OLocalPaginatedStorage]
orientdb-develop | 2019-05-14 08:50:23:319 INFO  Making fuzzy checkpoint [OLocalPaginatedStorage]
orientdb-develop | 2019-05-14 12:10:23:351 INFO  Making fuzzy checkpoint [OLocalPaginatedStorage]
orientdb-develop | 2019-05-15 13:15:23:488 INFO  Making fuzzy checkpoint [OLocalPaginatedStorage]
orientdb-develop | 2019-05-15 13:55:23:498 INFO  Making fuzzy checkpoint [OLocalPaginatedStorage]
orientdb-develop | 2019-05-15 14:25:23:510 INFO  Making fuzzy checkpoint [OLocalPaginatedStorage]
orientdb-develop | 2019-05-15 14:55:23:520 INFO  Making fuzzy checkpoint [OLocalPaginatedStorage]
orientdb-develop | 2019-05-16 07:55:23:611 INFO  Making fuzzy checkpoint [OLocalPaginatedStorage]
orientdb-develop | 2019-05-16 09:20:23:624 INFO  Making fuzzy checkpoint [OLocalPaginatedStorage]
orientdb-develop | 2019-05-16 09:55:23:647 INFO  Making fuzzy checkpoint [OLocalPaginatedStorage]
orientdb-develop | 2019-05-16 10:45:23:655 INFO  Making fuzzy checkpoint [OLocalPaginatedStorage]
orientdb-develop | 2019-05-16 13:00:23:679 INFO  Making fuzzy checkpoint [OLocalPaginatedStorage]
orientdb-develop | 2019-05-16 19:04:39:108 WARNI ->x.x.x.x: Error on invalid content:
orientdb-develop | /*￠Cookie: mstshash=Administr [ONetworkProtocolHttpDb]
orientdb-develop | 2019-05-17 08:15:23:779 INFO  Making fuzzy checkpoint [OLocalPaginatedStorage]
orientdb-develop | 2019-05-17 08:50:23:787 INFO  Making fuzzy checkpoint [OLocalPaginatedStorage]
orientdb-develop exited with code 137
```
```sh
journalctl -k | grep -i -e memory -e oom
```
Shows
```
May 17 11:52:18 prod1 kernel: node invoked oom-killer: gfp_mask=0x14200ca(GFP_HIGHUSER_MOVABLE), nodemask=(null), order=0, oom_score_adj=0
May 17 11:52:19 prod1 kernel:  oom_kill_process+0x220/0x440
May 17 11:52:19 prod1 kernel:  out_of_memory+0x2d1/0x4f0
May 17 11:52:19 prod1 kernel: [ pid ]   uid  tgid total_vm      rss pgtables_bytes swapents oom_score_adj name
May 17 11:52:19 prod1 kernel: Out of memory: Kill process 17414 (java) score 425 or sacrifice child
May 17 11:52:19 prod1 kernel: oom_reaper: reaped process 17414 (java), now anon-rss:0kB, file-rss:0kB, shmem-rss:0kB
```

**Comment by laa** [comment]
Hi @freeart I am working on that right now. Will provide a fix in a couple of days. I suppose.

**Comment by freeart** [comment]
@laa Hi! Any news about it? We have orientdb in productions and sometimes it downs by OOM watcher.

**Comment by laa** [comment]
Hi @freeart , we have released 3.0.21 could you try it and provide feedback ?

**Comment by freeart** [comment]
@laa Ok, I have updated my test machine. Let’s see. I will write about any OOM problems.

**Comment by laa** [comment]
@freeart do you have any updates?

**Comment by freeart** [comment]
@laa 2 weeks is online and seems good. I need more time

**Comment by freeart** [comment]
@laa I think we can close the issue. It works fine - 4 weeks without extra memory consumption. If OOM happens again I will reopen the issue

**Comment by laa** [comment]
Cool, thank you.

**Comment by darangel1273** [comment]
Hello,
(I am new at this)
I have this error, on Eclipse, with openjdk:

```
nov. 16, 2020 6:08:24 DA TARDE com.orientechnologies.common.log.OLogManager log
INFO: Detected limit of amount of simultaneously open files is 1048576,  limit of open files for disk cache will be set to 523776
Exception in thread "main" com.orientechnologies.orient.core.exception.ODatabaseException: Cannot open database 'rui'
	at com.orientechnologies.orient.core.db.OrientDBRemote.open(OrientDBRemote.java:113)
	at com.orientechnologies.orient.core.db.OrientDB.open(OrientDB.java:224)
	at com.orientechnologies.orient.core.db.OrientDB.open(OrientDB.java:210)
	at root.rui.LigaOrientDB.main(LigaOrientDB.java:13)
Caused by: com.orientechnologies.orient.core.exception.OStorageException: Cannot create a connection to remote server address(es): [ruin:2480]
	DB name="rui"
	at com.orientechnologies.orient.client.remote.OStorageRemote.openRemoteDatabase(OStorageRemote.java:1906)
	at com.orientechnologies.orient.client.remote.OStorageRemote.openRemoteDatabase(OStorageRemote.java:1750)
	at com.orientechnologies.orient.client.remote.OStorageRemote.open(OStorageRemote.java:570)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentRemote.internalOpen(ODatabaseDocumentRemote.java:235)
	at com.orientechnologies.orient.core.db.OrientDBRemote.open(OrientDBRemote.java:110)
	... 3 more

```

With a simple class to learn OrinetDB:



`package root.rui;

import com.orientechnologies.orient.core.db.ODatabaseSession;
import com.orientechnologies.orient.core.db.OrientDB;
import com.orientechnologies.orient.core.db.OrientDBConfig;

public class LigaOrientDB {

	public static void main(String[] args) {
		// TODO Auto-generated method stub
		//OrientDB o =new OrientDB("remote:192.168.1.64:2480", OrientDBConfig.defaultConfig() );
		//OrientDB o =new OrientDB("remote:localhost:2480", OrientDBConfig.defaultConfig() );
		OrientDB o =new OrientDB("remote:ruin:2480", OrientDBConfig.defaultConfig() );
		ODatabaseSession s = o.open("rui", "admin","admin" );
		if (s.getClass("Pessoa") == null )   { s.createVertexClass("Pessoa" ) ; }
		if (s.getClass("AmigoDe" ) == null ) { s.createEdgeClass("AmigoDe") ; }
		s.close();
		o.close();
	}
}
`
Can anyone tell me, what I am doing wrong?
Thank's in advance.
