### ISSUE TITLE
ODB 3.0.x server timeout

### ISSUE THREAD

**Issue by hrstoyanov** [orientechnologies/orientdb#8872]
## Expected behavior  
@laa @tglman 

I have Java EE [OpenLiberty](https://openliberty.io) server connecting to an ODB server over TCP/IP using [JCA ODB](https://github.com/peruncs/orientdb-jca) adapter. It works fine, but after a prolonged inactivity period, the ODB server will close the TCP connection (it seems from the exception stack trace below) without telling the Java EE server. This is not exactly a bug, but I would like to know:

1. Is there an ODB server configuration setting to prevent timeouts, closing the connection for inactivity?

2. Is there a way for clients to an ODB server to be notified prior to their connection being killed (some event maybe)?

3. What would happen if I start embedding the ODB server in the Java EE server (same JVM) where there is no TCP/IP anymore? Would connections be timed out again?

It seems that ODB connection pool should transparently re-establish a timed out connection (using the same credentials, connection pointer), rather than forcing me to code around this issue at higher level (say JCA adapter)

Any advise appreciated!

## Actual behavior  
```
[ERROR   ] SRVE0777E: Exception thrown by application class 'com.orientechnologies.orient.client.remote.ORemoteConnectionPool.createNetworkConnection:62'
com.orientechnologies.common.io.OIOException: Error on connecting to 127.0.0.1:2424/rehabowner
        at com.orientechnologies.orient.client.remote.ORemoteConnectionPool.createNetworkConnection(ORemoteConnectionPool.java:62)
        at com.orientechnologies.orient.client.remote.ORemoteConnectionPool.createNewResource(ORemoteConnectionPool.java:68)
        at com.orientechnologies.orient.client.remote.ORemoteConnectionPool.createNewResource(ORemoteConnectionPool.java:15)
        at com.orientechnologies.common.concur.resource.OResourcePool.getResource(OResourcePool.java:95)
        at com.orientechnologies.orient.client.remote.ORemoteConnectionPool.acquire(ORemoteConnectionPool.java:90)
        at com.orientechnologies.orient.client.remote.ORemoteConnectionManager.acquire(ORemoteConnectionManager.java:93)
        at com.orientechnologies.orient.client.remote.OStorageRemote.getNetwork(OStorageRemote.java:1960)
        at com.orientechnologies.orient.client.remote.OStorageRemote.baseNetworkOperation(OStorageRemote.java:385)
        at com.orientechnologies.orient.client.remote.OStorageRemote.networkOperationRetryTimeout(OStorageRemote.java:333)
        at com.orientechnologies.orient.client.remote.OStorageRemote.networkOperation(OStorageRemote.java:367)
        at com.orientechnologies.orient.client.remote.OStorageRemote.query(OStorageRemote.java:1013)
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentRemote.query(ODatabaseDocumentRemote.java:368)
        at com.recres.web.server.dao.NetworkDeviceDAO.findOrCreate(NetworkDeviceDAO.java:24)
        at com.recres.web.server.dao.NetworkDeviceDAO.findOrCreate(NetworkDeviceDAO.java:19)
        at com.recres.web.server.dao.ActionDAO$Builder.fromHttpRequest(ActionDAO.java:135)
        at com.recres.web.server.dao.ActionDAO$Builder.fromHttpRequest(ActionDAO.java:99)
        at com.recres.web.server.StafferSvcImpl.logInSignUp(StafferSvcImpl.java:118)
        at com.recres.web.server.StafferSvcImpl$Proxy$_$$_WeldClientProxy.logInSignUp(Unknown Source)
        at sun.reflect.GeneratedMethodAccessor728.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.ibm.ws.jaxrs20.server.LibertyJaxRsServerFactoryBean.performInvocation(LibertyJaxRsServerFactoryBean.java:652)
        at [internal classes]
        at com.recres.web.server.BootstrapFilter.doFilter(BootstrapFilter.java:41)
        at com.ibm.ws.webcontainer.filter.FilterInstanceWrapper.doFilter(FilterInstanceWrapper.java:201)
        at [internal classes]
Caused by: java.net.ConnectException: Connection refused (Connection refused)
        at java.net.PlainSocketImpl.socketConnect(Native Method)
        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
        at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
        at java.net.Socket.connect(Socket.java:589)
        at com.orientechnologies.orient.client.binary.OChannelBinaryAsynchClient.<init>(OChannelBinaryAsynchClient.java:72)
```

**Comment by hrstoyanov** [comment]
@laa ?

**Comment by tglman** [comment]
Hi,

This error seems that the client cannot reach the server, a simple network problem.

Closing this
