### ISSUE TITLE
Error on loading of index by configuration, java.lang.IllegalArgumentException: COLLATE cannot be null

### ISSUE THREAD

**Issue by efenzha** [orientechnologies/orientdb#8875]
### OrientDB Version: <version here>  
orientdb-3.0.18
### Java Version: <version here>  
1.8.0_152
### OS: <os here>  
linux
## Expected behavior  
connect to database without ERROR

## Actual behavior  
ERROR is reported

## Steps to reproduce  
- launch origenDb, no database.
- create a database 'abc' on Console.
- In scala code, trying to connect the database.
`
val graph = new OrientGraphNoTx(Settings.getOrientDbUrl)
      if (graph.getVertexType("EiffelEvent") == null) {
        graph.command(new OCommandSQL("ALTER DATABASE DATETIMEFORMAT \"yyyy-MM-dd'T'HH:mm:ss.SSS'Z'\"")).execute()

        val eType = graph.createVertexType("EiffelEvent")

        eType.createProperty("eventId", OType.STRING)
        eType.createProperty("eventType", OType.STRING)
        eType.createProperty("eventTime", OType.DATETIME)
        eType.createProperty("rawEiffel", OType.STRING)
        eType.createProperty("stage", OType.STRING)

        graph.createKeyIndex("eventId", classOf[Vertex], new Parameter("type", "UNIQUE"), new Parameter("class", "EiffelEvent"))
        graph.createKeyIndex("stage", classOf[Vertex], new Parameter("type", "NOTUNIQUE"), new Parameter("class", "EiffelEvent"))
      }

      if (graph.getEdgeType("inputEventId") == null) {
        graph.createEdgeType("inputEventId")
      }
`

- Every time I uses 'OrientGraphNoTx' to connect the database, it will reports lot of below errors.
`
2019-05-21 13:24:22 ERROR OIndexManagerRemote:188 - Error on loading of index by configuration: {type:UNIQUE_HASH_INDEX,name:OFunction.name,indexVersion:2,indexDefinition:{className:OFunction,field:name,keyType:STRING,collate:default,nullValuesIgnored:false},indexDefinitionClass:com.orientechnologies.orient.core.index.OPropertyIndexDefinition,clusters:[1],algorithm:HASH_INDEX,valueContainerAlgorithm:NONE}
java.lang.IllegalArgumentException: COLLATE cannot be null
	at com.orientechnologies.orient.core.index.OAbstractIndexDefinition.setCollate(OAbstractIndexDefinition.java:47)
	at com.orientechnologies.orient.core.index.OAbstractIndexDefinition.setCollate(OAbstractIndexDefinition.java:55)
	at com.orientechnologies.orient.core.index.OPropertyIndexDefinition.serializeFromStream(OPropertyIndexDefinition.java:174)
	at com.orientechnologies.orient.core.index.OPropertyIndexDefinition.fromStream(OPropertyIndexDefinition.java:139)
	at com.orientechnologies.orient.core.type.ODocumentWrapperNoClass.fromStream(ODocumentWrapperNoClass.java:44)
	at com.orientechnologies.orient.core.index.OIndexAbstract.loadMetadataInternal(OIndexAbstract.java:127)
	at com.orientechnologies.orient.core.index.OIndexManagerRemote.fromStream(OIndexManagerRemote.java:162)
	at com.orientechnologies.orient.core.type.ODocumentWrapperNoClass.reload(ODocumentWrapperNoClass.java:59)
	at com.orientechnologies.orient.core.index.OIndexManagerAbstract.reload(OIndexManagerAbstract.java:116)
	at com.orientechnologies.orient.core.db.document.OSharedContextRemote.reload(OSharedContextRemote.java:59)
	at com.orientechnologies.orient.core.metadata.OMetadataDefault.reload(OMetadataDefault.java:147)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentAbstract.reload(ODatabaseDocumentAbstract.java:247)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentRemote.command(ODatabaseDocumentRemote.java:413)
	at com.orientechnologies.orient.core.metadata.schema.OSchemaRemote.createClass(OSchemaRemote.java:123)
	at com.orientechnologies.orient.core.metadata.schema.OSchemaShared.createClass(OSchemaShared.java:232)
	at com.orientechnologies.orient.core.metadata.schema.OSchemaProxy.createClass(OSchemaProxy.java:88)
	at com.tinkerpop.blueprints.impls.orient.OrientBaseGraph$5.call(OrientBaseGraph.java:1362)
	at com.tinkerpop.blueprints.impls.orient.OrientBaseGraph$5.call(OrientBaseGraph.java:1359)
	at com.tinkerpop.blueprints.impls.orient.OrientBaseGraph.executeOutsideTx(OrientBaseGraph.java:1868)
	at com.tinkerpop.blueprints.impls.orient.OrientBaseGraph.createVertexType(OrientBaseGraph.java:1359)
	at com.tinkerpop.blueprints.impls.orient.OrientBaseGraph.createVertexType(OrientBaseGraph.java:1328)
	at com.tinkerpop.blueprints.impls.orient.OrientBaseGraph.createVertexType(OrientBaseGraph.java:1301)
	at jobleadtime.util.GraphDb.init(GraphDb.scala:29)
	at jobleadtime.util.Global$.<init>(Global.scala:27)
	at jobleadtime.util.Global$.<clinit>(Global.scala)
	at Main$.main(Main.scala:16)
	at Main.main(Main.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.spark.deploy.JavaMainApplication.start(SparkApplication.scala:52)
	at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:894)
	at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:198)
	at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:228)
	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:137)
	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
2019-05-21 13:24:22 ERROR OIndexManagerRemote:188 - Error on loading of index by configuration: {type:UNIQUE,name:ORole.name,indexVersion:2,indexDefinition:{className:ORole,field:name,keyType:STRING,collate:ci,nullValuesIgnored:false},indexDefinitionClass:com.orientechnologies.orient.core.index.OPropertyIndexDefinition,clusters:[1],algorithm:CELL_BTREE,valueContainerAlgorithm:NONE}
java.lang.IllegalArgumentException: COLLATE cannot be null
	at com.orientechnologies.orient.core.index.OAbstractIndexDefinition.setCollate(OAbstractIndexDefinition.java:47)
	at com.orientechnologies.orient.core.index.OAbstractIndexDefinition.setCollate(OAbstractIndexDefinition.java:55)
	at com.orientechnologies.orient.core.index.OPropertyIndexDefinition.serializeFromStream(OPropertyIndexDefinition.java:174)
	at com.orientechnologies.orient.core.index.OPropertyIndexDefinition.fromStream(OPropertyIndexDefinition.java:139)
	at com.orientechnologies.orient.core.type.ODocumentWrapperNoClass.fromStream(ODocumentWrapperNoClass.java:44)
	at com.orientechnologies.orient.core.index.OIndexAbstract.loadMetadataInternal(OIndexAbstract.java:127)
	at com.orientechnologies.orient.core.index.OIndexManagerRemote.fromStream(OIndexManagerRemote.java:162)
	at com.orientechnologies.orient.core.type.ODocumentWrapperNoClass.reload(ODocumentWrapperNoClass.java:59)
	at com.orientechnologies.orient.core.index.OIndexManagerAbstract.reload(OIndexManagerAbstract.java:116)
	at com.orientechnologies.orient.core.db.document.OSharedContextRemote.reload(OSharedContextRemote.java:59)
	at com.orientechnologies.orient.core.metadata.OMetadataDefault.reload(OMetadataDefault.java:147)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentAbstract.reload(ODatabaseDocumentAbstract.java:247)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentRemote.command(ODatabaseDocumentRemote.java:413)
	at com.orientechnologies.orient.core.metadata.schema.OSchemaRemote.createClass(OSchemaRemote.java:123)
	at com.orientechnologies.orient.core.metadata.schema.OSchemaShared.createClass(OSchemaShared.java:232)
	at com.orientechnologies.orient.core.metadata.schema.OSchemaProxy.createClass(OSchemaProxy.java:88)
	at com.tinkerpop.blueprints.impls.orient.OrientBaseGraph$5.call(OrientBaseGraph.java:1362)
	at com.tinkerpop.blueprints.impls.orient.OrientBaseGraph$5.call(OrientBaseGraph.java:1359)
	at com.tinkerpop.blueprints.impls.orient.OrientBaseGraph.executeOutsideTx(OrientBaseGraph.java:1868)
	at com.tinkerpop.blueprints.impls.orient.OrientBaseGraph.createVertexType(OrientBaseGraph.java:1359)
	at com.tinkerpop.blueprints.impls.orient.OrientBaseGraph.createVertexType(OrientBaseGraph.java:1328)
	at com.tinkerpop.blueprints.impls.orient.OrientBaseGraph.createVertexType(OrientBaseGraph.java:1301)
	at jobleadtime.util.GraphDb.init(GraphDb.scala:29)
	at jobleadtime.util.Global$.<init>(Global.scala:27)
	at jobleadtime.util.Global$.<clinit>(Global.scala)
	at Main$.main(Main.scala:16)
	at Main.main(Main.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.spark.deploy.JavaMainApplication.start(SparkApplication.scala:52)
	at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:894)
	at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:198)
	at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:228)
	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:137)
	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
2019-05-21 13:24:22 ERROR OIndexManagerRemote:188 - Error on loading of index by configuration: {type:UNIQUE,name:OUser.name,indexVersion:2,indexDefinition:{className:OUser,field:name,keyType:STRING,collate:ci,nullValuesIgnored:false},indexDefinitionClass:com.orientechnologies.orient.core.index.OPropertyIndexDefinition,clusters:[1],algorithm:CELL_BTREE,valueContainerAlgorithm:NONE}
java.lang.IllegalArgumentException: COLLATE cannot be null
	at com.orientechnologies.orient.core.index.OAbstractIndexDefinition.setCollate(OAbstractIndexDefinition.java:47)
	at com.orientechnologies.orient.core.index.OAbstractIndexDefinition.setCollate(OAbstractIndexDefinition.java:55)
	at com.orientechnologies.orient.core.index.OPropertyIndexDefinition.serializeFromStream(OPropertyIndexDefinition.java:174)
	at com.orientechnologies.orient.core.index.OPropertyIndexDefinition.fromStream(OPropertyIndexDefinition.java:139)
	at com.orientechnologies.orient.core.type.ODocumentWrapperNoClass.fromStream(ODocumentWrapperNoClass.java:44)
	at com.orientechnologies.orient.core.index.OIndexAbstract.loadMetadataInternal(OIndexAbstract.java:127)
	at com.orientechnologies.orient.core.index.OIndexManagerRemote.fromStream(OIndexManagerRemote.java:162)
	at com.orientechnologies.orient.core.type.ODocumentWrapperNoClass.reload(ODocumentWrapperNoClass.java:59)
	at com.orientechnologies.orient.core.index.OIndexManagerAbstract.reload(OIndexManagerAbstract.java:116)
	at com.orientechnologies.orient.core.db.document.OSharedContextRemote.reload(OSharedContextRemote.java:59)
	at com.orientechnologies.orient.core.metadata.OMetadataDefault.reload(OMetadataDefault.java:147)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentAbstract.reload(ODatabaseDocumentAbstract.java:247)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentRemote.command(ODatabaseDocumentRemote.java:413)
	at com.orientechnologies.orient.core.metadata.schema.OSchemaRemote.createClass(OSchemaRemote.java:123)
	at com.orientechnologies.orient.core.metadata.schema.OSchemaShared.createClass(OSchemaShared.java:232)
	at com.orientechnologies.orient.core.metadata.schema.OSchemaProxy.createClass(OSchemaProxy.java:88)
	at com.tinkerpop.blueprints.impls.orient.OrientBaseGraph$5.call(OrientBaseGraph.java:1362)
	at com.tinkerpop.blueprints.impls.orient.OrientBaseGraph$5.call(OrientBaseGraph.java:1359)
	at com.tinkerpop.blueprints.impls.orient.OrientBaseGraph.executeOutsideTx(OrientBaseGraph.java:1868)
	at com.tinkerpop.blueprints.impls.orient.OrientBaseGraph.createVertexType(OrientBaseGraph.java:1359)
	at com.tinkerpop.blueprints.impls.orient.OrientBaseGraph.createVertexType(OrientBaseGraph.java:1328)
	at com.tinkerpop.blueprints.impls.orient.OrientBaseGraph.createVertexType(OrientBaseGraph.java:1301)
	at jobleadtime.util.GraphDb.init(GraphDb.scala:29)
	at jobleadtime.util.Global$.<init>(Global.scala:27)
	at jobleadtime.util.Global$.<clinit>(Global.scala)
	at Main$.main(Main.scala:16)
	at Main.main(Main.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.spark.deploy.JavaMainApplication.start(SparkApplication.scala:52)
	at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:894)
	at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:198)
	at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:228)
	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:137)
	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)

2019-05-21 13:24:35 ERROR OIndexManagerRemote:188 - Error on loading of index by configuration: {type:NOTUNIQUE,name:EiffelEvent.stage,indexVersion:2,indexDefinition:{className:EiffelEvent,field:stage,keyType:STRING,collate:default,nullValuesIgnored:false},indexDefinitionClass:com.orientechnologies.orient.core.index.OPropertyIndexDefinition,clusters:[8],algorithm:CELL_BTREE,valueContainerAlgorithm:SBTREEBONSAISET}
java.lang.IllegalArgumentException: COLLATE cannot be null
	at com.orientechnologies.orient.core.index.OAbstractIndexDefinition.setCollate(OAbstractIndexDefinition.java:47)
	at com.orientechnologies.orient.core.index.OAbstractIndexDefinition.setCollate(OAbstractIndexDefinition.java:55)
	at com.orientechnologies.orient.core.index.OPropertyIndexDefinition.serializeFromStream(OPropertyIndexDefinition.java:174)
	at com.orientechnologies.orient.core.index.OPropertyIndexDefinition.fromStream(OPropertyIndexDefinition.java:139)
	at com.orientechnologies.orient.core.type.ODocumentWrapperNoClass.fromStream(ODocumentWrapperNoClass.java:44)
	at com.orientechnologies.orient.core.index.OIndexAbstract.loadMetadataInternal(OIndexAbstract.java:127)
	at com.orientechnologies.orient.core.index.OIndexManagerRemote.fromStream(OIndexManagerRemote.java:162)
	at com.orientechnologies.orient.core.type.ODocumentWrapperNoClass.reload(ODocumentWrapperNoClass.java:59)
	at com.orientechnologies.orient.core.index.OIndexManagerAbstract.reload(OIndexManagerAbstract.java:116)
	at com.orientechnologies.orient.core.index.OIndexManagerRemote.createIndex(OIndexManagerRemote.java:73)
	at com.orientechnologies.orient.core.index.OIndexManagerRemote.createIndex(OIndexManagerRemote.java:86)
	at com.orientechnologies.orient.core.index.OIndexManagerProxy.createIndex(OIndexManagerProxy.java:80)
	at com.tinkerpop.blueprints.impls.orient.OrientBaseGraph$12.call(OrientBaseGraph.java:1710)
	at com.tinkerpop.blueprints.impls.orient.OrientBaseGraph$12.call(OrientBaseGraph.java:1666)
	at com.tinkerpop.blueprints.impls.orient.OrientBaseGraph.executeOutsideTx(OrientBaseGraph.java:1868)
	at com.tinkerpop.blueprints.impls.orient.OrientBaseGraph.createKeyIndex(OrientBaseGraph.java:1666)
	at jobleadtime.util.GraphDb.init(GraphDb.scala:38)
	at jobleadtime.util.Global$.<init>(Global.scala:27)
	at jobleadtime.util.Global$.<clinit>(Global.scala)
	at Main$.main(Main.scala:16)
	at Main.main(Main.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.spark.deploy.JavaMainApplication.start(SparkApplication.scala:52)
	at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:894)
	at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:198)
	at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:228)
	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:137)
	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
`

<An SQL script to reproduce the problem or a JUnit test case will increase **A LOT** the chance to have a quick fix>

**Comment by laa** [comment]
Hi guys, please let me know if this issue still actual I will work on it.

**Comment by efenzha** [comment]
Hi @laa ,
No, it doesn't show in the version .31

**Comment by laa** [comment]
Cool!
