### ISSUE TITLE
Exception in thread 'OrientDB WAL Flush Task', ODirectMemoryAllocationFailedException

### ISSUE THREAD

**Issue by efenzha** [orientechnologies/orientdb#8882]
## Expected behavior  
No error during high concurrent writing

## Actual behavior  
crashes after around 3 hours

## Steps to reproduce  
adding vertex and edges with Spark, around 15000 records writing per second.

Config:
ORIENTDB_OPTS_MEMORY="-Xms2G -Xmx4G"
JAVA_OPTS_SCRIPT="-Djna.nosys=true -XX:+HeapDumpOnOutOfMemoryError -XX:MaxDirectMemorySize=512G -Djava.awt.headless=true -Dfile.encoding=UTF8 -Drhino.opt.level=9"
ORIENTDB_SETTINGS="-Dstorage.wal.syncOnPageFlush=false -Dstorage.wal.allowDirectIO=false"

Error during WAL writing
com.orientechnologies.common.exception.ODirectMemoryAllocationFailedException: Can not allocate direct memory chunk of size 134217728
	at com.orientechnologies.common.directmemory.ODirectMemoryAllocator.allocate(ODirectMemoryAllocator.java:131)
	at com.orientechnologies.orient.core.storage.impl.local.paginated.wal.cas.OCASDiskWriteAheadLog$RecordsWriter.run(OCASDiskWriteAheadLog.java:1882)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Exception in thread 'OrientDB WAL Flush Task'
com.orientechnologies.common.exception.ODirectMemoryAllocationFailedException: Can not allocate direct memory chunk of size 134217728
	at com.orientechnologies.common.directmemory.ODirectMemoryAllocator.allocate(ODirectMemoryAllocator.java:131)
	at com.orientechnologies.orient.core.storage.impl.local.paginated.wal.cas.OCASDiskWriteAheadLog$RecordsWriter.run(OCASDiskWriteAheadLog.java:1882)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

**Comment by laa** [comment]
Hi, fix in progress will be released soon

**Comment by efenzha** [comment]
> Hi, fix in progress will be released soon

That's great!

**Comment by anupbhore** [comment]
Any updates on this work? Is there any workaround?

**Comment by laa** [comment]
Hi, that is already fixed in the latest versions.
