### ISSUE TITLE
Exception when using a pool with embedded distributed database

### ISSUE THREAD

**Issue by ygyg70** [orientechnologies/orientdb#8885]
## Expected behavior  
Should be able to use a pool  

## Actual behavior  
Pool works when using non-distributed mode
Pool works when first creating a database in distributed mode
Pool doesn't work when restarting an embedded database in distributed mode   

## Steps to reproduce  
Using embedded distributed database, create some objects. Stop the server. Start the server. Try to acquire a database from the pool.

Note - the file that is  locked seems to always be osequence_{some_number}.cpm

Here is the Orient part of the exception log:

File is already opened under:
----------------------------------------------------------------------------------------------------
	java.base/java.lang.Thread.getStackTrace(Thread.java:1606)
	com.orientechnologies.orient.core.storage.fs.OFileClassic.acquireExclusiveAccess(OFileClassic.java:679)
	com.orientechnologies.orient.core.storage.fs.OFileClassic.open(OFileClassic.java:623)
	com.orientechnologies.orient.core.storage.cache.local.OWOWCache.readNameIdMapV2(OWOWCache.java:1890)
	com.orientechnologies.orient.core.storage.cache.local.OWOWCache.initNameIdMapping(OWOWCache.java:1781)
	com.orientechnologies.orient.core.storage.cache.local.OWOWCache.loadRegisteredFiles(OWOWCache.java:479)
	com.orientechnologies.orient.core.storage.disk.OLocalPaginatedStorage.initWalAndDiskCache(OLocalPaginatedStorage.java:632)
	com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.open(OAbstractPaginatedStorage.java:371)
	com.orientechnologies.orient.core.db.OrientDBEmbedded.openNoAuthenticate(OrientDBEmbedded.java:236)
	com.orientechnologies.orient.core.db.OrientDBEmbedded.openNoAuthenticate(OrientDBEmbedded.java:59)
	com.orientechnologies.orient.server.OServer.openDatabase(OServer.java:923)
	com.orientechnologies.orient.server.distributed.impl.ODistributedAbstractPlugin.reassignClustersOwnership(ODistributedAbstractPlugin.java:801)
	com.orientechnologies.orient.server.hazelcast.OHazelcastPlugin$4.call(OHazelcastPlugin.java:809)
	com.orientechnologies.orient.server.hazelcast.OHazelcastPlugin$4.call(OHazelcastPlugin.java:796)
	com.orientechnologies.orient.server.distributed.impl.ODistributedAbstractPlugin.executeInDistributedDatabaseLock(ODistributedAbstractPlugin.java:1770)
	com.orientechnologies.orient.server.hazelcast.OHazelcastPlugin.loadLocalDatabases(OHazelcastPlugin.java:796)
	com.orientechnologies.orient.server.hazelcast.OHazelcastPlugin.startup(OHazelcastPlugin.java:300)
	com.orientechnologies.orient.server.OServer.registerPlugins(OServer.java:1194)
	com.orientechnologies.orient.server.OServer.activate(OServer.java:469)
----------------------------------------------------------------------------------------------------

	at com.orientechnologies.orient.core.storage.fs.OFileClassic.acquireExclusiveAccess(OFileClassic.java:675)
	at com.orientechnologies.orient.core.storage.fs.OFileClassic.open(OFileClassic.java:623)
	at com.orientechnologies.orient.core.storage.cache.local.OWOWCache.readNameIdMapV2(OWOWCache.java:1890)
	at com.orientechnologies.orient.core.storage.cache.local.OWOWCache.initNameIdMapping(OWOWCache.java:1781)
	at com.orientechnologies.orient.core.storage.cache.local.OWOWCache.loadRegisteredFiles(OWOWCache.java:479)
	at com.orientechnologies.orient.core.storage.disk.OLocalPaginatedStorage.initWalAndDiskCache(OLocalPaginatedStorage.java:632)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.open(OAbstractPaginatedStorage.java:371)
	at com.orientechnologies.orient.core.db.OrientDBEmbedded.poolOpen(OrientDBEmbedded.java:320)
	at com.orientechnologies.orient.core.db.ODatabasePoolImpl$1.createNewResource(ODatabasePoolImpl.java:44)
	at com.orientechnologies.orient.core.db.ODatabasePoolImpl$1.createNewResource(ODatabasePoolImpl.java:41)
	at com.orientechnologies.common.concur.resource.OResourcePool.getResource(OResourcePool.java:95)
	at com.orientechnologies.orient.core.db.ODatabasePoolImpl.acquire(ODatabasePoolImpl.java:67)
	at com.orientechnologies.orient.core.db.ODatabasePool.acquire(ODatabasePool.java:132)

**Comment by ygyg70** [comment]
Was able to get it to work by using ODatabasePool over OrientGraphFactory
