### ISSUE TITLE
[Bug Report] Read timeout (always) on select `outE()` - Reproducible

### ISSUE THREAD

**Issue by matanshukry** [orientechnologies/orientdb#8891]
## Expected behavior
Return edges

## Actual behavior  
Hangs and after a while read timeout

## Steps to reproduce  
```
create class person extends V
create property person.name String

create class friend extends E
create property friend.status String


create vertex person set name="Bob1"
create vertex person set name="Bob2"
create vertex person set name="Bob3"
create vertex person set name="Bob4"

create edge friend from (select from person where name="Bob1") to (select from person where name="Bob2") set status="Good"
create edge friend from (select from person where name="Bob2") to (select from person where name="Bob3") set status="Very Good"
create edge friend from (select from person where name="Bob3") to (select from person where name="Bob4") set status="Bad"

orientdb {db=my_db}> select outE() from person
```

## Extra query info

```
orientdb {db=my_db}> select from person

+----+-----+------+----+----------+---------+
|#   |@RID |@CLASS|name|out_friend|in_friend|
+----+-----+------+----+----------+---------+
|0   |#24:0|person|Bob1|[#25:0]   |         |
|1   |#24:1|person|Bob2|[#25:1]   |[#25:0]  |
|2   |#24:2|person|Bob3|[#25:2]   |[#25:1]  |
|3   |#24:3|person|Bob4|          |[#25:2]  |
+----+-----+------+----+----------+---------+

4 item(s) found. Query executed in 0.014 sec(s).


orientdb {db=my_db}> select from friend

+----+-----+------+-----+-----+---------+
|#   |@RID |@CLASS|out  |in   |status   |
+----+-----+------+-----+-----+---------+
|0   |#25:0|friend|#24:0|#24:1|Good     |
|1   |#25:1|friend|#24:1|#24:2|Very Good|
|2   |#25:2|friend|#24:2|#24:3|Bad      |
+----+-----+------+-----+-----+---------+
```

## Other technical info

- The log had no error either
- when using `list connections` in another console, it just shows "Listening" for command.

p.s.
I was trying to do some other queries and it seems they are also causing read timeout.
e.g.
```
select unionall(tags, [2,3]) from place
```
where place is a vertex that has 3 records in it, tags is a property containing an embeddedlist, each record contains different values.

## Actual Bug
Did some debugging and found the stack trace (which is silented). I tried to see if there were any recent changes around the code but couldn't find any.

```
java.lang.ClassCastException: com.orientechnologies.common.collection.OMultiCollectionIterator cannot be cast to java.util.Collection
	at com.orientechnologies.orient.core.serialization.serializer.result.binary.OResultSerializerNetwork.serializeValue(OResultSerializerNetwork.java:401)
	at com.orientechnologies.orient.core.serialization.serializer.result.binary.OResultSerializerNetwork.serialize(OResultSerializerNetwork.java:132)
	at com.orientechnologies.orient.core.serialization.serializer.result.binary.OResultSerializerNetwork.toStream(OResultSerializerNetwork.java:651)
	at com.orientechnologies.orient.client.remote.message.OMessageHelper.writeProjection(OMessageHelper.java:411)
	at com.orientechnologies.orient.client.remote.message.OMessageHelper.writeResult(OMessageHelper.java:448)
	at com.orientechnologies.orient.client.remote.message.OQueryResponse.write(OQueryResponse.java:56)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.sessionRequest(ONetworkProtocolBinary.java:340)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.execute(ONetworkProtocolBinary.java:205)
	at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:69)
```

Also, the reason why it's not shown normally is:
https://github.com/orientechnologies/orientdb/blob/develop/core/src/main/java/com/orientechnologies/common/thread/OSoftThread.java#L72

```
        if (dumpExceptions)
          OLogManager.instance().error(this, "Error during thread execution", e);
```
dumpExceptions is always false (due to the constructor of `ONetworkProtocol`)

**Comment by luigidellaquila** [comment]
Hi @matanshukry 

I just pushed a fix for this problem, it will be released with v 3.0.20

I'm keeping this issue open just to remember that I have to add some additional checks on result set composition

Thanks

Luigi

**Comment by matanshukry** [comment]
Great, I'll work with it locally using develop branch. Thanks!

**Comment by tglman** [comment]
Hi,
The iterator problem is fixed, and the network blocked as well has been fixed in recent versions.
Closing
