### ISSUE TITLE
WAL native memory is not released after massive inserts.

### ISSUE THREAD

**Issue by kerjes** [orientechnologies/orientdb#8895]
WAL native memory is not released after massive inserts.
As part of a volume test simulating long time usage of OrientDB in production, disabling WAL is not an option.
Java Heap allocation is fine.

## Expected behavior  
Allocated native memory (used by WAL) should be released after finished massive insert.
## Actual behavior  
Native memory allocation is not released. 

Eventually server log reports:
2019-05-31 10:16:39:960 SEVER Can not flush data because of issue during data write, 
java.util.concurrent.ExecutionException: com.sun.jna.LastErrorException: [12]
Cannot allocate memory [OWOWCache$PeriodicFlushTask]

Exception in thread 'OrientDB WAL Flush Task'
com.sun.jna.LastErrorException: [12] Cannot allocate memory
        at com.sun.jna.Native.invokeInt(Native Method)
        at com.sun.jna.Function.invoke(Function.java:419)
        at com.sun.jna.Function.invoke(Function.java:354)
        at com.sun.jna.Library$Handler.invoke(Library.java:244)
        at com.sun.proxy.$Proxy2.posix_memalign(Unknown Source)
        at com.orientechnologies.common.jna.ONative.posix_memalign(ONative.java:250)
        at com.orientechnologies.common.directmemory.ODirectMemoryAllocator.allocate(ODirectMemoryAllocator.java:141)

Client log reports:
Caused by: com.sun.jna.LastErrorException: [12] Cannot allocate memory
 at com.sun.jna.Native.invokeInt(Native Method)
 at com.sun.jna.Function.invoke(Function.java:419)
 at com.sun.jna.Function.invoke(Function.java:354)
 at com.sun.jna.Library$Handler.invoke(Library.java:244)
 at com.sun.proxy.$Proxy4.posix_memalign(Unknown Source)
 at com.orientechnologies.common.jna.ONative.posix_memalign(ONative.java:250)
 at com.orientechnologies.common.directmemory.ODirectMemoryAllocator.allocate(ODirectMemoryAllocator.java:141)
 at com.orientechnologies.orient.core.storage.impl.local.paginated.wal.cas.OCASDiskWriteAheadLog$RecordsWriter.run(OCASDiskWriteAheadLog.java:1882)
 ... 7 more
 [CIRCULAR REFERENCE:com.orientechnologies.orient.core.exception.OStorageException: 
 Error in data flush background thread, please restart database and send full stack trace inside of bug report

## Steps to reproduce  
A java-program (not publishable due to NDA) was written to simulate production like data and generate large amount of data.
The program was run with out transactions and mostly doing the following in pseudo code:

1. session.query("SELECT FROM Person where id=?", p.getId())
2. if not exist 
     OVertex res = session.newVertex("Person");
3. res.save();
4.		try (OResultSet resultSet = session.query("SELECT FROM " + link + " where in=? and out=?",
				oVertexB.getIdentity(), oVertexA.getIdentity())) {
			if (!resultSet.hasNext()) {
				OEdge edge = oVertexA.addEdge(oVertexB, link);
				edge.setProperty("from", new Date());
				edge.setProperty("to", new Date());
				edge.save();
			}
		)

![visualvm](https://user-images.githubusercontent.com/51361510/58875862-e8e0ae80-86cc-11e9-861b-98be3df19854.png)
![top1](https://user-images.githubusercontent.com/51361510/58879253-8d66ee80-86d5-11e9-8f01-cead919778b5.png)
![top2](https://user-images.githubusercontent.com/51361510/58879267-91930c00-86d5-11e9-98d1-b0dad46487b2.png)

**Comment by kerjes** [comment]
Typo
Actual behavior
Native memory is not released.

**Comment by laa** [comment]
The fix under the testing I will let you know once we will integrate it. That is the question of a couple of days.

**Comment by laa** [comment]
Hi @kerjes we released 3.0.21 version could you try it ?

**Comment by kerjes** [comment]
Hello, thanks for the response, will test v.3.0.21 ASAP

**Comment by kerjes** [comment]
Installed v.3.0.21 and run two massive inserts with appr. 1 million nodes each. First run completed without crashing but memory was not released, same top-graph as above.  Second run caused OrientDB to crash without any error messages in server-log. Client-log output:

Run nr 1;
Main.Params(nrOfGraphs=1000000, nrOfPersons=1000000, nrOfVehicles=1000000, transacted=false)
Generating 1000000 graphs, with 1000000 persons and 1000000 vehicles
next infoId=1200001
firstRun=false
pnr.size()=1400000, diff=0, maxTry=7
males=700092, females=699908
Person.size=1000000, diff=0, maxTry=0
Vehicle.size=1000000, diff=0, maxTry=4
Start: Saving data to OrientDB........
Saving data to OrientDB, took: 13813,808 sek, created: 1060490 vertices and 10924954 edges.


Run nr 2:
Main.Params(nrOfGraphs=1000000, nrOfPersons=1000000, nrOfVehicles=1000000, transacted=false)
Generating 1000000 graphs, with 1000000 persons and 1000000 vehicles
next infoId=2200001
firstRun=false
pnr.size()=1400000, diff=0, maxTry=9
males=699859, females=700141
Person.size=1000000, diff=0, maxTry=0
Vehicle.size=1000000, diff=0, maxTry=4
Start: Saving data to OrientDB..................................................................................................
jun 20, 2019 2:58:55 EM com.orientechnologies.common.log.OLogManager log
INFO: Caught Network I/O errors on 127.0.0.1:2424/grund, trying an automatic reconnection... (error: null)
jun 20, 2019 2:58:55 EM com.orientechnologies.common.log.OLogManager log
ALLVARLIG: Error on transaction commit `5E3C412D`
com.orientechnologies.common.io.OIOException
        at com.orientechnologies.orient.client.remote.OStorageRemote.baseNetworkOperation(OStorageRemote.java:452)
        at com.orientechnologies.orient.client.remote.OStorageRemote.networkOperationRetryTimeout(OStorageRemote.java:333)
        at com.orientechnologies.orient.client.remote.OStorageRemote.networkOperationNoRetry(OStorageRemote.java:363)
        at com.orientechnologies.orient.client.remote.OStorageRemote.commit(OStorageRemote.java:1138)
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentAbstract.internalCommit(ODatabaseDocumentAbstract.java:2730)
        at com.orientechnologies.orient.core.tx.OTransactionOptimistic.doCommit(OTransactionOptimistic.java:534)
        at com.orientechnologies.orient.core.tx.OTransactionOptimistic.commit(OTransactionOptimistic.java:101)
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentAbstract.commit(ODatabaseDocumentAbstract.java:2203)
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentAbstract.commit(ODatabaseDocumentAbstract.java:2173)
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentAbstract.saveGraph(ODatabaseDocumentAbstract.java:2108)
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentAbstract.save(ODatabaseDocumentAbstract.java:2059)
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentAbstract.save(ODatabaseDocumentAbstract.java:85)
        at com.orientechnologies.orient.core.record.impl.ODocument.save(ODocument.java:2169)
        at com.orientechnologies.orient.core.record.impl.ODocument.save(ODocument.java:2160)
        at com.orientechnologies.orient.core.record.impl.OEdgeDelegate.save(OEdgeDelegate.java:453)
Caused by: java.io.EOFException
        at java.io.DataInputStream.readByte(DataInputStream.java:267)
        at com.orientechnologies.orient.enterprise.channel.binary.OChannelBinary.readByte(OChannelBinary.java:73)
        at com.orientechnologies.orient.client.binary.OChannelBinaryAsynchClient.beginResponse(OChannelBinaryAsynchClient.java:174)
        at com.orientechnologies.orient.client.binary.OChannelBinaryAsynchClient.beginResponse(OChannelBinaryAsynchClient.java:158)
        at com.orientechnologies.orient.client.remote.OStorageRemote.beginResponse(OStorageRemote.java:1979)
        at com.orientechnologies.orient.client.remote.OStorageRemote.lambda$networkOperationRetryTimeout$2(OStorageRemote.java:350)
        at com.orientechnologies.orient.client.remote.OStorageRemote.baseNetworkOperation(OStorageRemote.java:409)

**Comment by kerjes** [comment]
> Hi @kerjes we released 3.0.21 version could you try it ?

Installed v.3.0.21 and run two massive inserts with appr. 1 million nodes each. First run completed without crashing but memory was not released, same top-graph as above.  Second run caused OrientDB to crash without any error messages in server-log. Client-log output:

Run nr 1;
Main.Params(nrOfGraphs=1000000, nrOfPersons=1000000, nrOfVehicles=1000000, transacted=false)
Generating 1000000 graphs, with 1000000 persons and 1000000 vehicles
next infoId=1200001
firstRun=false
pnr.size()=1400000, diff=0, maxTry=7
males=700092, females=699908
Person.size=1000000, diff=0, maxTry=0
Vehicle.size=1000000, diff=0, maxTry=4
Start: Saving data to OrientDB........
Saving data to OrientDB, took: 13813,808 sek, created: 1060490 vertices and 10924954 edges.


Run nr 2:
Main.Params(nrOfGraphs=1000000, nrOfPersons=1000000, nrOfVehicles=1000000, transacted=false)
Generating 1000000 graphs, with 1000000 persons and 1000000 vehicles
next infoId=2200001
firstRun=false
pnr.size()=1400000, diff=0, maxTry=9
males=699859, females=700141
Person.size=1000000, diff=0, maxTry=0
Vehicle.size=1000000, diff=0, maxTry=4
Start: Saving data to OrientDB..................................................................................................
jun 20, 2019 2:58:55 EM com.orientechnologies.common.log.OLogManager log
INFO: Caught Network I/O errors on 127.0.0.1:2424/grund, trying an automatic reconnection... (error: null)
jun 20, 2019 2:58:55 EM com.orientechnologies.common.log.OLogManager log
ALLVARLIG: Error on transaction commit `5E3C412D`
com.orientechnologies.common.io.OIOException
        at com.orientechnologies.orient.client.remote.OStorageRemote.baseNetworkOperation(OStorageRemote.java:452)
        at com.orientechnologies.orient.client.remote.OStorageRemote.networkOperationRetryTimeout(OStorageRemote.java:333)
        at com.orientechnologies.orient.client.remote.OStorageRemote.networkOperationNoRetry(OStorageRemote.java:363)
        at com.orientechnologies.orient.client.remote.OStorageRemote.commit(OStorageRemote.java:1138)
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentAbstract.internalCommit(ODatabaseDocumentAbstract.java:2730)
        at com.orientechnologies.orient.core.tx.OTransactionOptimistic.doCommit(OTransactionOptimistic.java:534)
        at com.orientechnologies.orient.core.tx.OTransactionOptimistic.commit(OTransactionOptimistic.java:101)
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentAbstract.commit(ODatabaseDocumentAbstract.java:2203)
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentAbstract.commit(ODatabaseDocumentAbstract.java:2173)
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentAbstract.saveGraph(ODatabaseDocumentAbstract.java:2108)
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentAbstract.save(ODatabaseDocumentAbstract.java:2059)
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentAbstract.save(ODatabaseDocumentAbstract.java:85)
        at com.orientechnologies.orient.core.record.impl.ODocument.save(ODocument.java:2169)
        at com.orientechnologies.orient.core.record.impl.ODocument.save(ODocument.java:2160)
        at com.orientechnologies.orient.core.record.impl.OEdgeDelegate.save(OEdgeDelegate.java:453)
Caused by: java.io.EOFException
        at java.io.DataInputStream.readByte(DataInputStream.java:267)
        at com.orientechnologies.orient.enterprise.channel.binary.OChannelBinary.readByte(OChannelBinary.java:73)
        at com.orientechnologies.orient.client.binary.OChannelBinaryAsynchClient.beginResponse(OChannelBinaryAsynchClient.java:174)
        at com.orientechnologies.orient.client.binary.OChannelBinaryAsynchClient.beginResponse(OChannelBinaryAsynchClient.java:158)
        at com.orientechnologies.orient.client.remote.OStorageRemote.beginResponse(OStorageRemote.java:1979)
        at com.orientechnologies.orient.client.remote.OStorageRemote.lambda$networkOperationRetryTimeout$2(OStorageRemote.java:350)
        at com.orientechnologies.orient.client.remote.OStorageRemote.baseNetworkOperation(OStorageRemote.java:409)

**Comment by kerjes** [comment]
> Hi @kerjes we released 3.0.21 version could you try it ?

Installed v.3.0.21 and run two massive inserts with appr. 1 million nodes each. First run completed without crashing but memory was not released, same top-graph as above.  Second run caused OrientDB to crash without any error messages in server-log. Client-log output:

Run nr 1;
Main.Params(nrOfGraphs=1000000, nrOfPersons=1000000, nrOfVehicles=1000000, transacted=false)
Generating 1000000 graphs, with 1000000 persons and 1000000 vehicles
next infoId=1200001
firstRun=false
pnr.size()=1400000, diff=0, maxTry=7
males=700092, females=699908
Person.size=1000000, diff=0, maxTry=0
Vehicle.size=1000000, diff=0, maxTry=4
Start: Saving data to OrientDB........
Saving data to OrientDB, took: 13813,808 sek, created: 1060490 vertices and 10924954 edges.


Run nr 2:
Main.Params(nrOfGraphs=1000000, nrOfPersons=1000000, nrOfVehicles=1000000, transacted=false)
Generating 1000000 graphs, with 1000000 persons and 1000000 vehicles
next infoId=2200001
firstRun=false
pnr.size()=1400000, diff=0, maxTry=9
males=699859, females=700141
Person.size=1000000, diff=0, maxTry=0
Vehicle.size=1000000, diff=0, maxTry=4
Start: Saving data to OrientDB..................................................................................................
jun 20, 2019 2:58:55 EM com.orientechnologies.common.log.OLogManager log
INFO: Caught Network I/O errors on 127.0.0.1:2424/grund, trying an automatic reconnection... (error: null)
jun 20, 2019 2:58:55 EM com.orientechnologies.common.log.OLogManager log
ALLVARLIG: Error on transaction commit `5E3C412D`
com.orientechnologies.common.io.OIOException
        at com.orientechnologies.orient.client.remote.OStorageRemote.baseNetworkOperation(OStorageRemote.java:452)
        at com.orientechnologies.orient.client.remote.OStorageRemote.networkOperationRetryTimeout(OStorageRemote.java:333)
        at com.orientechnologies.orient.client.remote.OStorageRemote.networkOperationNoRetry(OStorageRemote.java:363)
        at com.orientechnologies.orient.client.remote.OStorageRemote.commit(OStorageRemote.java:1138)
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentAbstract.internalCommit(ODatabaseDocumentAbstract.java:2730)
        at com.orientechnologies.orient.core.tx.OTransactionOptimistic.doCommit(OTransactionOptimistic.java:534)
        at com.orientechnologies.orient.core.tx.OTransactionOptimistic.commit(OTransactionOptimistic.java:101)
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentAbstract.commit(ODatabaseDocumentAbstract.java:2203)
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentAbstract.commit(ODatabaseDocumentAbstract.java:2173)
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentAbstract.saveGraph(ODatabaseDocumentAbstract.java:2108)
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentAbstract.save(ODatabaseDocumentAbstract.java:2059)
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentAbstract.save(ODatabaseDocumentAbstract.java:85)
        at com.orientechnologies.orient.core.record.impl.ODocument.save(ODocument.java:2169)
        at com.orientechnologies.orient.core.record.impl.ODocument.save(ODocument.java:2160)
        at com.orientechnologies.orient.core.record.impl.OEdgeDelegate.save(OEdgeDelegate.java:453)
Caused by: java.io.EOFException
        at java.io.DataInputStream.readByte(DataInputStream.java:267)
        at com.orientechnologies.orient.enterprise.channel.binary.OChannelBinary.readByte(OChannelBinary.java:73)
        at com.orientechnologies.orient.client.binary.OChannelBinaryAsynchClient.beginResponse(OChannelBinaryAsynchClient.java:174)
        at com.orientechnologies.orient.client.binary.OChannelBinaryAsynchClient.beginResponse(OChannelBinaryAsynchClient.java:158)
        at com.orientechnologies.orient.client.remote.OStorageRemote.beginResponse(OStorageRemote.java:1979)
        at com.orientechnologies.orient.client.remote.OStorageRemote.lambda$networkOperationRetryTimeout$2(OStorageRemote.java:350)
        at com.orientechnologies.orient.client.remote.OStorageRemote.baseNetworkOperation(OStorageRemote.java:409)

**Comment by laa** [comment]
Hi @kerjes could you send me settings which you used to run server, and server log output on start and amount of RAM which you had ?

**Comment by kerjes** [comment]
> Hi @kerjes could you send me settings which you used to run server, and server log output on start and amount of RAM which you had ?

Hi @laa, the settings are default as included in the release, attaching  console.log file using -Denvironement.dumpCfgAtStartup=true
Memory is 8GB and 2GB assiged to OrientDB run on 2-CPU virtual linux.
OrientDB installed on a 20GB disk.

[console.log](https://github.com/orientechnologies/orientdb/files/3311084/console.log)

**Comment by laa** [comment]
Hi @kerjes if you got you correctly you have 2 GB memory limit for OrientDB process, or I misunderstood you ?

**Comment by kerjes** [comment]
Hi @Iaa, memory used for OrientDb is
-Xms2G -Xmx2G

as part of standard settings included in the release, nothing is changed. And OrientDb is run on a 8GB Linux machine.

**Comment by laa** [comment]
Hi @kerjes what was memory consumption of process after the first run ?

**Comment by kerjes** [comment]
> Hi @kerjes what was memory consumption of process after the first run ?

Hi @laa, memory-consumption was the same as before (v.3.0.19)
![first_run](https://user-images.githubusercontent.com/51361510/59919898-02059100-9429-11e9-9e7d-4c198cb0cfb1.png)
Once swap memory is used, (the lower bar), then there's not much time left before things goes bad.
Is there a paramter to limit the amout of WAL-memory used?

**Comment by laa** [comment]
Hi @kerjes memory consumption expected to be 6GB,  but you have 8GB why then you have OOM killer killing your up ? Did you observe memory usage numbers bigger than 6GB for this application ?

**Comment by kerjes** [comment]
Hi @Iaa, not sure if understand your question, but memory-monitoring was done with JVisualVM and linux-top-command. And memory usage must have been was bigger than 6GB as swap memory was used, as shown in above top-grpah.

 

 

 

Från: Andrey Lomakin <notifications@github.com> 
Skickat: den 21 juni 2019 15:37
Till: orientechnologies/orientdb <orientdb@noreply.github.com>
Kopia: kerjes <krsokolow@gmail.com>; Mention <mention@noreply.github.com>
Ämne: Re: [orientechnologies/orientdb] WAL native memory is not released after massive inserts. (#8895)

 

Hi @kerjes <https://github.com/kerjes>  memory consumption expected to be 6GB, but you have 8GB why then you have OOM killer killing your up ? Did you observe memory usage numbers bigger than 6GB for this application ?

**Comment by laa** [comment]
Hi @kerjes I see that RES memory according to your list from the "top" command is 4 GB and then 6GB. So I do not see memory usage overhead from ODB application. Could you try with 3GB disk cache size instead of 4GB probably that will solve issue.

**Comment by kerjes** [comment]
Hi @laa. If could specify exactly which parameter for disk cache size you referring to then I could try a new run with OOM-application next week. And if there any specfic loggin-data you would like to have, please specifiy.

**Comment by laa** [comment]
Hi @kaidzen you should set following system property during server start `-Dstorage.diskCache.bufferSize=3072`. Then would be good to check size of RS memory using top command.

**Comment by laa** [comment]
Hi @kaidzen , any update on this?

**Comment by kerjes** [comment]
Hi @Iaa,
I run some consecutive tests with OOM-app with -Dstorage.diskCache.bufferSize=3072, 
on a virtual Linux machine (Ubuntu 18.04.2 LTS, Openjdk version "1.8.0_212") with the following results:

Start of run nr1 (only showing necessary params from top for OrientDb):
RES=3,115G	%CPU = 45,8, 	%MEM=40,2	COMMAND=java -server -Xms2G -Xmx2G -D.jna…

After run1
RES=4,999G	%CPU = 0,3 	%MEM=65,5	COMMAND=java -server -Xms2G -Xmx2G -D.jna…

During run2
RES=5,161G	%CPU = 79,4, 	%MEM=66,6	COMMAND=java -server -Xms2G -Xmx2G -D.jna…
RES=5,171G	%CPU = 80,1 	%MEM=66,8	COMMAND=java -server -Xms2G -Xmx2G -D.jna…

After run3
RES=5,192G	%CPU = 0,3 	%MEM=67,0	COMMAND=java -server -Xms2G -Xmx2G -D.jna…

During run4
RES=5,193G	%CPU = 79,1 	%MEM=67,0	COMMAND=java -server -Xms2G -Xmx2G -D.jna…
About to finish run 4 and something goes wrong
RES=5,204G	%CPU = 738,5 	%MEM=67,2	COMMAND=java -server -Xms2G -Xmx2G -D.jna…
CPU-usage is at max 800% (8-cpus) and OrientDB is unresponsive. Stopping orient with kill -9.

Initial problem “Cannot allocate memory” is solved and RES almost stabilized, 
only gradual increase at the end.  Cannot say what happened at the end of run 4.

**Comment by laa** [comment]
Hi @kerjes that is what I expected. Sorry for asking but could you run the same load 10 times to be sure that memory consumption is always about 5 GB and if that is true we close the issue.

**Comment by kerjes** [comment]
Hi @laa. This time I run the OOM-app 10 times on bare metal Linux-installation, (L)Ubuntu 18.04.2 LTS, Openjdk version "1.8.0_212", 
i7 SSD 8GB memory using only a 350 MB memory footprint. Here are thre results from top.

top_before1.log:  PID USER  PR  NI    VIRT    RES   DELT S  %CPU %MIN      TIME+ COMMAND
top_befo  2383 orient    20   0 9719480 1,408g  20964 S   0,0 18,2   4:02.46 java -server -Xms2G -Xmx2G ... -Dstorage.diskCache.bufferSize=3072

top1.log:  PID USER  PR  NI    VIRT    RES   DELT S  %CPU %MIN      TIME+ COMMAND
top1.log  2383 orient    20   0 9721528 4,258g  20952 S   0,0 55,0  96:20.74 java -server -Xms2G -Xmx2G ... -Dstorage.diskCache.bufferSize=3072

top2.log:  PID USER  PR  NI    VIRT    RES   DELT S  %CPU %MIN      TIME+ COMMAND
top2.log  2383 orient    20   0 9721528 5,132g  15524 S   0,0 66,3 415:47.04 java -server -Xms2G -Xmx2G ... -Dstorage.diskCache.bufferSize=3072

top3.log:  PID USER  PR  NI    VIRT    RES   DELT S  %CPU %MIN      TIME+ COMMAND
top3.log  2383 orient    20   0 9721528 5,149g  15072 S   0,0 66,5 738:42.40 java -server -Xms2G -Xmx2G ... -Dstorage.diskCache.bufferSize=3072

top4.log:  PID USER  PR  NI    VIRT    RES   DELT S  %CPU %MIN      TIME+ COMMAND
top4.log  2383 orient    20   0 9721528 5,180g  15128 S   0,0 66,9   1063:09 java -server -Xms2G -Xmx2G ... -Dstorage.diskCache.bufferSize=3072

top5.log:  PID USER  PR  NI    VIRT    RES   DELT S  %CPU %MIN      TIME+ COMMAND
top5.log  2383 orient    20   0 9721528 5,230g   6960 S   6,2 67,5   1394:21 java -server -Xms2G -Xmx2G ... -Dstorage.diskCache.bufferSize=3072

top6.log:  PID USER  PR  NI    VIRT    RES   DELT S  %CPU %MIN      TIME+ COMMAND
top6.log  2383 orient    20   0 9721528 5,237g    344 S   0,0 67,6   1600:19 java -server -Xms2G -Xmx2G ... -Dstorage.diskCache.bufferSize=3072

top7.log:  PID USER  PR  NI    VIRT    RES   DELT S  %CPU %MIN      TIME+ COMMAND
top7.log  2383 orient    20   0 9721528 5,239g      0 S   0,0 67,7   1821:51 java -server -Xms2G -Xmx2G ... -Dstorage.diskCache.bufferSize=3072

top8.log:  PID USER  PR  NI    VIRT    RES   DELT S  %CPU %MIN      TIME+ COMMAND
top8.log  2383 orient    20   0 9721528 5,240g      0 S   0,0 67,7   2181:05 java -server -Xms2G -Xmx2G ... -Dstorage.diskCache.bufferSize=3072

top9.log:  PID USER  PR  NI    VIRT    RES   DELT S  %CPU %MIN      TIME+ COMMAND
top9.log  2383 orient    20   0 9788092 5,289g    472 S   0,0 68,3   2547:22 java -server -Xms2G -Xmx2G ... -Dstorage.diskCache.bufferSize=3072

top10.log:  PID USER  PR  NI    VIRT    RES   DELT S  %CPU %MIN      TIME+ COMMAND
top10.log  2383 orient    20   0 9919180 5,294g      0 S   0,0 68,4   2785:32 java -server -Xms2G -Xmx2G ... -Dstorage.diskCache.bufferSize=3072

The results are same as previously, a slight increase in RES, almost stable.

**Comment by laa** [comment]
Hi @kerjes cool. Thank you. I close issue then.
