### ISSUE TITLE
UPDATE with MERGE synax error when using named params v3.0.x

### ISSUE THREAD

**Issue by myflowpl** [orientechnologies/orientdb#8896]
OrientDB Version: 3.0.18
Java Version: 1.8.0_111
OS: Ubuntu 18.04
OrientJS Version:  3.0.5 

### this works if you put json inline:
````typescript
const json = JSON.stringify(item);

let data: any = await db.command(`UPDATE EventRegistration MERGE ${json} RETURN AFTER WHERE hash = :hash AND rid=:rid`, {
   params: {
        hash: hash,
        rid: rid
    }
}).one();
````
### and this not if you use named parameters:
```typescript
let data: any = await db.command(`UPDATE EventRegistration MERGE :data RETURN AFTER WHERE hash = :hash AND rid=:rid`, {
   params: {
      hash: hash,
       rid: rid,
       data: item
    }
}).one();
```

### it throws error:
````
Error parsing query: 
UPDATE EventRegistration MERGE :data RETURN AFTER WHERE hash = :hash AND rid=:rid
     ^
Encountered " <UPDATE> "UPDATE "" at line 1, column 1.
Was expecting one of:
    <SELECT> ...
    <TRAVERSE> ...
    <MATCH> ... 
    <INSERT> ...
    <RETURN> ...
    <FIND> ...
    <REBUILD> ...
    <OPTIMIZE> ...
    <GRANT> ...
    <REVOKE> ...
    <BEGIN> ...
    <COMMIT> ...
    <ROLLBACK> ... 
    <IF> ...
    <SLEEP> ...
    <CONSOLE> ...
    <MOVE> ...
    <SELECT> ...
    <SELECT> ...
    <TRAVERSE> ...
    <MATCH> ...
    <FIND> ...
    <INSERT> ...
    
        DB name="smdb_dev" 
        Error Code="1" +5116ms
OrientDB.RequestError: Error parsing query:
UPDATE EventRegistration MERGE :data RETURN AFTER WHERE hash = :hash AND rid=:rid
     ^
Encountered " <UPDATE> "UPDATE "" at line 1, column 1.
Was expecting one of:
    <SELECT> ...
    <TRAVERSE> ...
    <MATCH> ...
    <INSERT> ...
    <RETURN> ...
    <FIND> ...
    <REBUILD> ...
    <OPTIMIZE> ...
    <GRANT> ...
    <REVOKE> ...
    <BEGIN> ...
    <COMMIT> ...
    <ROLLBACK> ...
    <IF> ...
    <SLEEP> ...
    <CONSOLE> ...
    <MOVE> ...
    <SELECT> ...
    <SELECT> ...
    <TRAVERSE> ...
    <MATCH> ...
    <FIND> ...
    <INSERT> ... 
    
        DB name="smdb_dev"
        Error Code="1"
    at child.Operation.parseError (/mnt/c/Users/Piotr/www/slackmap/node_modules/orientjs/lib/client/network/protocol37/operation.js:1224:13)
    at child.Operation.consume (/mnt/c/Users/Piotr/www/slackmap/node_modules/orientjs/lib/client/network/protocol37/operation.js:566:35)
    at ONetworkConnection.Connection.process (/mnt/c/Users/Piotr/www/slackmap/node_modules/orientjs/lib/client/network/conn.js:462:17)
    at ONetworkConnection.Connection.handleSocketData (/mnt/c/Users/Piotr/www/slackmap/node_modules/orientjs/lib/client/network/conn.js:344:20)
    at Socket.emit (events.js:189:13)
    at addChunk (_stream_readable.js:284:12)
    at readableAddChunk (_stream_readable.js:265:11)
    at Socket.Readable.push (_stream_readable.js:220:10) 
    at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
````

It was working on v2.2 version

It should work with v3 right ?

**Comment by myflowpl** [comment]
@luigidellaquila this is very similar to  #8666

and that was quick fix, may be this one will also be possible to fix with next version ?

**Comment by luigidellaquila** [comment]
Hi @myflowpl 

This should not be too complex to do, I'm marking it as an enhancement, I'll work on it as soon as I can

Thanks

Luigi

**Comment by myflowpl** [comment]
Any news on this one?
It was labeled as `enhanecement` but it should be labeled as `bug`
this feature is in the docs 
http://orientdb.com/docs/3.0.x/sql/SQL-Update.html
and it was working in version 2.2

@luigidellaquila you said it shouldn't be complex ?

**Comment by seanmworkman** [comment]
I am having the same problem in a batch. Are there any updates on this?

@luigidellaquila?
