### ISSUE TITLE
"missing session and token" after a period of time without interacting with OrientDB

### ISSUE THREAD

**Issue by matanshukry** [orientechnologies/orientdb#8899]
## Expected behavior  
Do required operations without an exception

## Actual behavior  
Get an exception when attempting to reach to OrientDB after a period of time without interacting with it.

## Steps to reproduce 
1. Start the app
2. The app will reach to the database for some initialization.
3. Wait a bit (can't say how long, but I think 5m should be more than enough)
4. Do an operation that will make the app reach the database again

## Relevant Issues
Issue #8772 

## Relevant Logs
```
com.orientechnologies.orient.enterprise.channel.binary.OTokenSecurityException: missing session and token
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[na:1.8.0_191]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[na:1.8.0_191]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[na:1.8.0_191]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[na:1.8.0_191]
	at com.orientechnologies.orient.client.binary.OChannelBinaryAsynchClient.handleException(OChannelBinaryAsynchClient.java:338) ~[orientdb-client-3.0.18.jar:3.0.18]
	at com.orientechnologies.orient.client.binary.OChannelBinaryAsynchClient.handleStatus(OChannelBinaryAsynchClient.java:285) ~[orientdb-client-3.0.18.jar:3.0.18]
	at com.orientechnologies.orient.client.binary.OChannelBinaryAsynchClient.handleStatus(OChannelBinaryAsynchClient.java:307) ~[orientdb-client-3.0.18.jar:3.0.18]
	at com.orientechnologies.orient.client.binary.OChannelBinaryAsynchClient.beginResponse(OChannelBinaryAsynchClient.java:196) ~[orientdb-client-3.0.18.jar:3.0.18]
	at com.orientechnologies.orient.client.binary.OChannelBinaryAsynchClient.beginResponse(OChannelBinaryAsynchClient.java:158) ~[orientdb-client-3.0.18.jar:3.0.18]
	at com.orientechnologies.orient.client.remote.OStorageRemote.beginResponse(OStorageRemote.java:1953) ~[orientdb-client-3.0.18.jar:3.0.18]
	at com.orientechnologies.orient.client.remote.OStorageRemote.lambda$networkOperationRetryTimeout$2(OStorageRemote.java:348) ~[orientdb-client-3.0.18.jar:3.0.18]
	at com.orientechnologies.orient.client.remote.OStorageRemote.baseNetworkOperation(OStorageRemote.java:407) ~[orientdb-client-3.0.18.jar:3.0.18]
	at com.orientechnologies.orient.client.remote.OStorageRemote.networkOperationRetryTimeout(OStorageRemote.java:331) ~[orientdb-client-3.0.18.jar:3.0.18]
	at com.orientechnologies.orient.client.remote.OStorageRemote.networkOperation(OStorageRemote.java:365) ~[orientdb-client-3.0.18.jar:3.0.18]
	at com.orientechnologies.orient.client.remote.OStorageRemote.query(OStorageRemote.java:1011) ~[orientdb-client-3.0.18.jar:3.0.18]
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentRemote.query(ODatabaseDocumentRemote.java:368) ~[orientdb-client-3.0.18.jar:3.0.18]
	...
```

**Comment by wolf4ood** [comment]
Hi @matanshukry 

are you executing only query in this flow of the app?

Or do you have also write operations in a TX?

Thanks

**Comment by matanshukry** [comment]
@wolf4ood nope, a read-only query (simple select).

**Comment by wolf4ood** [comment]
@matanshukry 

strange, i've tried to reproduce it even by decreasing the token timeout, but without luck

Are you able to provide some help to reproduce this?

Thanks

**Comment by matanshukry** [comment]
There's also the chance it happens between pod restarts.
I'm running orient on a pod in minikube and it restarts some times (I didn't give it enough memory), so I think it might occur between the restarts.

**Comment by matanshukry** [comment]
Just verified it also happens without any restarts of the pods, just long time between calls.

**Comment by wolf4ood** [comment]
@matanshukry 

are you able to provide a test case or a reproducer for this?

Thanks

**Comment by matanshukry** [comment]
@wolf4ood it happens all the time on my project so I can definitely reproduce it, but it's not "on demand", it does seems to be time related. Hence I didn't really try to create a test case or something similar.

I'm running orientdb locally from develop branch in debug mode, so if you want we can talk privately and you'll give me some points on what you're looking for / where, and I can try and debug it my self when it happens.

**Comment by matanshukry** [comment]
@wolf4ood ok managed to find it alone - you're gonna love me.

The issue is on this line:
https://github.com/orientechnologies/orientdb/blob/develop/server/src/main/java/com/orientechnologies/orient/server/OClientConnection.java#L165

The connection attempt to validate the session, and since all bytes are equal - it assumes valid. The method below it though ( https://github.com/orientechnologies/orientdb/blob/develop/server/src/main/java/com/orientechnologies/orient/server/OClientConnection.java#L182 ) is crucial - it not only validates the token and return the result, it also sets the validity field on the token class it self ( https://github.com/orientechnologies/orientdb/blob/develop/server/src/main/java/com/orientechnologies/orient/server/token/OTokenHandlerImpl.java#L163 ).

Since the method is never called, the `isValid` field of the token is never changed, and always stays at the default, false.

Then, in the client connection manager, when the token expiry has passed (happens after 1h of no communication), and the valid flag is false (always), it is removed from the connection manager:
https://github.com/orientechnologies/orientdb/blob/develop/server/src/main/java/com/orientechnologies/orient/server/OClientConnectionManager.java#L117

Let me know if you need more information.

p.s.
Thank you and/or love notes can be sent directly to my email ;)

**Comment by wolf4ood** [comment]
Hi @matanshukry 

thanks for the detailed information. :)
Let me try to reproduce it because even if the connection manager remove the session, the client at the next request should renegotiate a new token.

**Comment by matanshukry** [comment]
@wolf4ood What you're saying isn't conflicting with the bug, and it is correct. The next request is successful. But the current/last one has an exception thrown and is failed.

**Comment by wolf4ood** [comment]
@matanshukry 
I mean the client should catch missing token exception, and retry the operation if some condition are valid

**Comment by matanshukry** [comment]
@wolf4ood - Oh, didn't see that. Tell me where that code is so I can debug it?

**Comment by wolf4ood** [comment]
@matanshukry 

here it's the code

https://github.com/orientechnologies/orientdb/blob/3.0.x/client/src/main/java/com/orientechnologies/orient/client/remote/OStorageRemote.java#L319

**Comment by matanshukry** [comment]
@wolf4ood - After checking the I found the bug, and it seems you @luigidellaquila Already fixed it 2 months ago, but my client version wasn't updated to the latest.
Just in case anyone will need the info in the future, this was the commit that fixed the issue: https://github.com/orientechnologies/orientdb/commit/a292545f1324ce71a3a3c26ef219c9f06ce6bdac

Also, I recommend changing the "New Issue" template on Github to have 2 lines of versions - for client and for server, rather than just the single now. 

Either way I'm no longer encountering this issue, so I'm closing this issue.

**Comment by shubhamsdx** [comment]
I'm getting this error in 3.0.24

**Comment by Charles74** [comment]
I found this thread because I was occasionally seeing the same exception. 
It turns out, as suggested above, it is related to, abandoning or leaving a transaction open. I changed my code to always check if a transaction is in progress and commit it. I was reading from the database using 3 gremlin queries, but still `graph.tx().isOpen()` returns true.
