### ISSUE TITLE
Cannot open remote and local database with same name simultaneously 

### ISSUE THREAD

**Issue by jayaramcs** [orientechnologies/orientdb#8930]
## Expected behavior  
I am migrating from Orient 2.x to 3.x. 
I have 2 database instances. Db Name is "accounts". One instance runs locally in embedded mode within a Java application. The second instance runs on a remote server (accounts-server).
In 2.x I was able to connect to the remote database ("accounts") while I also had the local database open. 
In 3.x, this appears to have regressed. What am I missing? 

## Actual behavior  
 ```JAVA
 com.orientechnologies.orient.core.exception.ODatabaseException: Cannot open database 'accounts'
	at com.orientechnologies.orient.core.db.OrientDBRemote.open(OrientDBRemote.java:89)
	at com.orientechnologies.orient.core.db.OrientDB.open(OrientDB.java:205)
	at com.orientechnologies.orient.core.db.OrientDB.open(OrientDB.java:190)
...
Caused by: com.orientechnologies.orient.core.exception.ODatabaseException: Cannot open database 'accounts'
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Unknown Source)
	at java.base/java.lang.reflect.Constructor.newInstance(Unknown Source)
	at com.orientechnologies.orient.client.binary.OChannelBinaryAsynchClient.handleException(OChannelBinaryAsynchClient.java:338)
	at com.orientechnologies.orient.client.binary.OChannelBinaryAsynchClient.handleStatus(OChannelBinaryAsynchClient.java:285)
	at com.orientechnologies.orient.client.binary.OChannelBinaryAsynchClient.handleStatus(OChannelBinaryAsynchClient.java:307)
	at com.orientechnologies.orient.client.binary.OChannelBinaryAsynchClient.beginResponse(OChannelBinaryAsynchClient.java:196)
	at com.orientechnologies.orient.client.binary.OChannelBinaryAsynchClient.beginResponse(OChannelBinaryAsynchClient.java:158)
	at com.orientechnologies.orient.client.remote.OStorageRemote.openRemoteDatabase(OStorageRemote.java:1433)
	at com.orientechnologies.orient.client.remote.OStorageRemote.openRemoteDatabase(OStorageRemote.java:1513)
	at com.orientechnologies.orient.client.remote.OStorageRemote.openRemoteDatabase(OStorageRemote.java:1414)
	at com.orientechnologies.orient.client.remote.OStorageRemote.open(OStorageRemote.java:417)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentRemote.internalOpen(ODatabaseDocumentRemote.java:225)
	at com.orientechnologies.orient.core.db.OrientDBRemote.open(OrientDBRemote.java:86)
	... 11 common frames omitted
	Suppressed: com.orientechnologies.orient.core.exception.ODatabaseException: Cannot open database 'accounts'
		at com.orientechnologies.orient.core.db.OrientDBEmbedded.open(OrientDBEmbedded.java:300)
		at com.orientechnologies.orient.core.db.OrientDBEmbedded.open(OrientDBEmbedded.java:226)
		at com.orientechnologies.orient.server.OServer.openDatabase(OServer.java:939)
		at com.orientechnologies.orient.server.OServer.openDatabase(OServer.java:913)
		at com.orientechnologies.orient.server.OConnectionBinaryExecutor.executeDatabaseOpen37(OConnectionBinaryExecutor.java:1187)
		at com.orientechnologies.orient.client.remote.message.OOpen37Request.execute(OOpen37Request.java:77)
		at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.sessionRequest(ONetworkProtocolBinary.java:309)
		at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.execute(ONetworkProtocolBinary.java:211)
		at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:69)
	Caused by: java.lang.IllegalStateException: File is allowed to be opened only once.
File is already opened under: 
----------------------------------------------------------------------------------------------------
	java.base/java.lang.Thread.getStackTrace(Unknown Source)
	com.orientechnologies.orient.core.storage.fs.OFileClassic.acquireExclusiveAccess(OFileClassic.java:679)
	com.orientechnologies.orient.core.storage.fs.OFileClassic.open(OFileClassic.java:623)
	com.orientechnologies.orient.core.storage.cache.local.OWOWCache.readNameIdMapV2(OWOWCache.java:1890)
	com.orientechnologies.orient.core.storage.cache.local.OWOWCache.initNameIdMapping(OWOWCache.java:1781)
	com.orientechnologies.orient.core.storage.cache.local.OWOWCache.loadRegisteredFiles(OWOWCache.java:479)
	com.orientechnologies.orient.core.storage.disk.OLocalPaginatedStorage.initWalAndDiskCache(OLocalPaginatedStorage.java:632)
	com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.open(OAbstractPaginatedStorage.java:371)
	com.orientechnologies.orient.core.db.OrientDBEmbedded.poolOpen(OrientDBEmbedded.java:320)
	com.orientechnologies.orient.core.db.ODatabasePoolImpl$1.createNewResource(ODatabasePoolImpl.java:44)
	com.orientechnologies.orient.core.db.ODatabasePoolImpl$1.createNewResource(ODatabasePoolImpl.java:41)
	com.orientechnologies.common.concur.resource.OResourcePool.getResource(OResourcePool.java:95)
	com.orientechnologies.orient.core.db.ODatabasePoolImpl.acquire(ODatabasePoolImpl.java:67)
	com.orientechnologies.orient.core.db.ODatabasePool.acquire(ODatabasePool.java:132)
```
## Steps to reproduce  

Initialize an embedded database connection and Pool 
```JAVA
ORIENT_DB_CONNECTION = new OrientDB("plocal:c:\database", OrientDBConfig.defaultConfig());
ORIENT_DB_POOL = new ODatabasePool(ORIENT_DB_CONNECTION, "accounts", "admin","admin");
```
Do some queries by acquiring connection etc. 
```JAVA
try(ODatabaseSession session = ORIENT_DB_POOL.acquire();){
...
}
```

Open connection to Remote accounts 
```JAVA
OrientDB orientDb = new OrientDB("remote:accounts-server,"root","pswd", OrientDBConfig.defaultConfig());
database = orientDb.open("accounts", "admin", "admin");
```
<An SQL script to reproduce the problem or a JUnit test case will increase **A LOT** the chance to have a quick fix>

**Comment by jayaramcs** [comment]
**Updates and code to recreate the issue.** 
https://gist.github.com/jayaramcs/aa5e03e390cc29afee77ae30733251a2 

In order to recreate the issue, put a breakpoint on line 71 of the EmbeddedTestServer. At this point, it is my understanding that we have started up an embedded server and we are allowed to connect to it using the plocal protocol from within the same JVM.

While the server is at break-point, run the client code - connect over the remote protocol. This errors out with the following stack on the server.

if my understanding of [this]( http://orientdb.com/docs/3.0.x/internals/Embedded-Server.html) is incorrect, please advise on how we can achieve this. 

My use case is as follows. 
A Java (fx) standalone application starts up in embedded mode. At some point, the user may choose to connect the application to a server.  
The server is also running an embedded orient instance, similar to the Embedded Server in my gist. 
When the client connects to the server, it errors out and causes the issues.   

```java
java.lang.IllegalStateException: File is allowed to be opened only once.
File is already opened under: 
----------------------------------------------------------------------------------------------------
	java.base/java.lang.Thread.getStackTrace(Thread.java:1602)
	com.orientechnologies.orient.core.storage.fs.OFileClassic.acquireExclusiveAccess(OFileClassic.java:679)
	com.orientechnologies.orient.core.storage.fs.OFileClassic.open(OFileClassic.java:623)
	com.orientechnologies.orient.core.storage.cache.local.OWOWCache.readNameIdMapV2(OWOWCache.java:1890)
	com.orientechnologies.orient.core.storage.cache.local.OWOWCache.initNameIdMapping(OWOWCache.java:1781)
	com.orientechnologies.orient.core.storage.cache.local.OWOWCache.loadRegisteredFiles(OWOWCache.java:479)
	com.orientechnologies.orient.core.storage.disk.OLocalPaginatedStorage.initWalAndDiskCache(OLocalPaginatedStorage.java:632)
	com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.open(OAbstractPaginatedStorage.java:371)
	com.orientechnologies.orient.core.db.OrientDBEmbedded.poolOpen(OrientDBEmbedded.java:320)
	com.orientechnologies.orient.core.db.ODatabasePoolImpl$1.createNewResource(ODatabasePoolImpl.java:44)
	com.orientechnologies.orient.core.db.ODatabasePoolImpl$1.createNewResource(ODatabasePoolImpl.java:41)
	com.orientechnologies.common.concur.resource.OResourcePool.getResource(OResourcePool.java:95)
	com.orientechnologies.orient.core.db.ODatabasePoolImpl.acquire(ODatabasePoolImpl.java:67)
	com.orientechnologies.orient.core.db.ODatabasePool.acquire(ODatabasePool.java:132)
	com.jayaram.test.EmbeddedTestServer.main(EmbeddedTestServer.java:75)```

**Comment by luigidellaquila** [comment]
Hi @jayaramcs 

In v 3.0 the flow of the instantiation and acquisition of resources for local databases is a bit more strict, so two OrientDB instances (even in the same JVM) cannot access the same resources.
In this case, the server (gist line 23) and your OrientDB instance (gist line 62) are competing on the same folders, this is why it's failing.
To fix the problem, you can replace line 62 with the following

```
OrientDB orient = server.getContext();
```
(and just move the declaration of `server` variable in a place where it's visible from that point)

I hope it helps

Thanks

Luigi

**Comment by jayaramcs** [comment]
Thanks @luigidellaquila ! This works for me now. 

On a side note for someone who may run into this. Please note that the db names are case sensitive and if you are not careful, you can get a similar stack trace when opening the connection.
