### ISSUE TITLE
Make exception message more useful in ORecordSerializerBinaryV0

### ISSUE THREAD

**Issue by vitalii-honchar** [orientechnologies/orientdb#8931]
### OS: Ubuntu 18.04

This [exception](https://github.com/orientechnologies/orientdb/blob/2.2.37/core/src/main/java/com/orientechnologies/orient/core/serialization/serializer/record/binary/ORecordSerializerBinaryV0.java#L870) doesn't contains meaningful information.

Exception throws in case when link is not saved to database and added link record id to exception message, thus in exception message was added -1:-1 without any useful information about record...

Exception looks like this:
```
Caused by: com.orientechnologies.orient.core.exception.ODatabaseException: Impossible to serialize invalid link #-1:-1
	DB name="Orienteer"
	at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinaryV0.writeOptimizedLink(ORecordSerializerBinaryV0.java:870)
	at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinaryV0.serializeValue(ORecordSerializerBinaryV0.java:757)
	at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinaryV0.serialize(ORecordSerializerBinaryV0.java:385)
	at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinary.toStream(ORecordSerializerBinary.java:99)
	at com.orientechnologies.orient.core.record.impl.ODocument.toStream(ODocument.java:2381)
	at com.orientechnologies.orient.core.record.impl.ODocument.toStream(ODocument.java:664)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.executeSaveRecord(ODatabaseDocumentTx.java:2174)
	at com.orientechnologies.orient.core.tx.OTransactionNoTx.saveRecord(OTransactionNoTx.java:191)
	... 67 more
```

Please show record in case of this exception, because debug application without normal exceptions is a hard.

**Comment by cuongrep** [comment]
@tglman, @laa 
I found this issue has been closed as the milestones: 3.2.x, 3.2.7.
Because I have the same issue, I'm interested in the issue.
I have tried to find a way to reproduce the issue and the way to solve it. But I only found a way to solve it by upgrading to a specific version, I have never known how to verify if it has been solved or not.
Could you please give me more detail or a link to any discussion on how to solve and verify whether the issue was solved?
