### ISSUE TITLE
[Bug] client OSerializationException -> server OIOException -> "infinite" client waiting

### ISSUE THREAD

**Issue by matanshukry** [orientechnologies/orientdb#8946]
## Expected behavior
Connections should be closed regardless of exceptions

## Actual behavior  
Connections aren't closed.

## Steps to reproduce  
Flow:
(1) (Client Side) I'm trying to save an entity to the database. I'm using a type orientdb can't serialize though, so it throws an exception
(2) (Server Side) The server doesn't like that, and throws an exception too. Something is messed up there too.
(3) (Client Side) Since there was an exception, I'm trying to close the connection so I can return it to the resource pool. When trying to close it though, the client seems to be waiting for the server response. The server never respond, since it has it's own exception
(4) (Client Side) now the client has an open connection, waiting for a message from the server (which will never happen), with a timeout of 1h.

On the client, I'm getting this exception:
```
com.orientechnologies.orient.core.exception.OSerializationException: Impossible serialize value of type class com.msh.myapp.models.MyAlbum with the Result binary serializer
	DB name="mydb"
	at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerNetworkV37.writeEmbeddedMap(ORecordSerializerNetworkV37.java:660)
	at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerNetworkV37.serializeValue(ORecordSerializerNetworkV37.java:596)
	at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerNetworkV37.writeEmbeddedMap(ORecordSerializerNetworkV37.java:663)
	at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerNetworkV37.serializeValue(ORecordSerializerNetworkV37.java:596)
	at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerNetworkV37.serialize(ORecordSerializerNetworkV37.java:157)
	at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerNetworkV37.toStream(ORecordSerializerNetworkV37.java:874)
	at com.orientechnologies.orient.core.record.impl.ODocument.toStream(ODocument.java:2799)
	at com.orientechnologies.orient.core.record.impl.ODocument.toStream(ODocument.java:1038)
	at com.orientechnologies.orient.client.remote.message.OMessageHelper.getRecordBytes(OMessageHelper.java:83)
	at com.orientechnologies.orient.client.remote.message.OQueryRequest.write(OQueryRequest.java:94)
	at com.orientechnologies.orient.client.remote.OStorageRemote.lambda$networkOperationRetryTimeout$2(OStorageRemote.java:231)
	at com.orientechnologies.orient.client.remote.OStorageRemote.baseNetworkOperation(OStorageRemote.java:303)
	at com.orientechnologies.orient.client.remote.OStorageRemote.networkOperationRetryTimeout(OStorageRemote.java:227)
	at com.orientechnologies.orient.client.remote.OStorageRemote.networkOperationNoRetry(OStorageRemote.java:257)
	at com.orientechnologies.orient.client.remote.OStorageRemote.command(OStorageRemote.java:942)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentRemote.command(ODatabaseDocumentRemote.java:410)
```

When that happens, the server is then encountering the following exception:
```
2019-07-05 17:55:44:961 FINE  {db=mydb} Request id:27 type:45 [ONetworkProtocolBinary]com.orientechnologies.common.io.OIOException: Impossible to read a chunk of length:1006632960 max allowed chunk length:16777216 see NETWORK_BINARY_MAX_CONTENT_LENGTH settings 
	at com.orientechnologies.orient.enterprise.channel.binary.OChannelBinary.readBytes(OChannelBinary.java:165)
```

**Comment by tglman** [comment]
Hi,
This issue should be already solved in 3.0.31, Closing.
