### ISSUE TITLE
Occasional 'cannot open database' errors

### ISSUE THREAD

**Issue by MaryPercival** [orientechnologies/orientdb#8960]
## Expected behavior  
ODatabaseSession objects can be acquired from ODatabasePool, used for queries and closed without errors.

## Actual behavior  
Occasional errors are seen when trying to query: saying ODatabaseException: Cannot open database 'databases'
 
In my code the stack trace is:
Caused by: com.orientechnologies.orient.core.exception.ODatabaseException: Cannot open database 'databases'
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at com.orientechnologies.orient.client.binary.OChannelBinaryAsynchClient.handleException(OChannelBinaryAsynchClient.java:338)
	at com.orientechnologies.orient.client.binary.OChannelBinaryAsynchClient.handleStatus(OChannelBinaryAsynchClient.java:285)
	at com.orientechnologies.orient.client.binary.OChannelBinaryAsynchClient.handleStatus(OChannelBinaryAsynchClient.java:307)
	at com.orientechnologies.orient.client.binary.OChannelBinaryAsynchClient.beginResponse(OChannelBinaryAsynchClient.java:196)
	at com.orientechnologies.orient.client.binary.OChannelBinaryAsynchClient.beginResponse(OChannelBinaryAsynchClient.java:158)
	at com.orientechnologies.orient.client.remote.OStorageRemote.beginResponse(OStorageRemote.java:1953)
	at com.orientechnologies.orient.client.remote.OStorageRemote.lambda$networkOperationRetryTimeout$2(OStorageRemote.java:348)
	at com.orientechnologies.orient.client.remote.OStorageRemote.baseNetworkOperation(OStorageRemote.java:407)
	at com.orientechnologies.orient.client.remote.OStorageRemote.networkOperationRetryTimeout(OStorageRemote.java:331)
	at com.orientechnologies.orient.client.remote.OStorageRemote.networkOperation(OStorageRemote.java:365)
	at com.orientechnologies.orient.client.remote.OStorageRemote.query(OStorageRemote.java:1028)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentRemote.query(ODatabaseDocumentRemote.java:380)

. . . . . 
	... 10 common frames omitted
	Suppressed: com.orientechnologies.orient.core.exception.ODatabaseException: Cannot open database 'databases'
		at com.orientechnologies.orient.core.db.OrientDBEmbedded.openNoAuthenticate(OrientDBEmbedded.java:246)
		at com.orientechnologies.orient.core.db.OrientDBEmbedded.openNoAuthenticate(OrientDBEmbedded.java:59)
		at com.orientechnologies.orient.server.OServer.openDatabase(OServer.java:923)
		at com.orientechnologies.orient.server.OClientConnection.init(OClientConnection.java:235)
		at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.onBeforeOperationalRequest(ONetworkProtocolBinary.java:452)
		at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.sessionRequest(ONetworkProtocolBinary.java:260)
		at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.execute(ONetworkProtocolBinary.java:206)
		at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:69)
	Caused by: com.orientechnologies.orient.core.exception.OStorageException: Cannot open the storage 'databases' because it does not exist in path: /orientdb/databases/databases
		at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.open(OAbstractPaginatedStorage.java:363)
		at com.orientechnologies.orient.core.db.OrientDBEmbedded.openNoAuthenticate(OrientDBEmbedded.java:236)
		... 7 common frames omitted
Caused by: com.orientechnologies.orient.core.exception.OStorageException: Cannot open the storage 'databases' because it does not exist in path: /orientdb/databases/databases
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.open(OAbstractPaginatedStorage.java:363)
	at com.orientechnologies.orient.core.db.OrientDBEmbedded.openNoAuthenticate(OrientDBEmbedded.java:236)
	at com.orientechnologies.orient.core.db.OrientDBEmbedded.openNoAuthenticate(OrientDBEmbedded.java:59)
	at com.orientechnologies.orient.server.OServer.openDatabase(OServer.java:923)
	at com.orientechnologies.orient.server.OClientConnection.init(OClientConnection.java:235)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.onBeforeOperationalRequest(ONetworkProtocolBinary.java:452)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.sessionRequest(ONetworkProtocolBinary.java:260)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.execute(ONetworkProtocolBinary.java:206)
	at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:69)

In the orient db (docker container) log:
Exception `3865F881` in storage `plocal:/orientdb/databases/databases`: 3.0.18 - Veloce (build 747595e790a081371496f3bb9c57cec395644d82, branch 3.0.x)
com.orientechnologies.orient.core.exception.OStorageException: Cannot open the storage 'databases' because it does not exist in path: /orientdb/databases/databases
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.open(OAbstractPaginatedStorage.java:363)
	at com.orientechnologies.orient.core.db.OrientDBEmbedded.openNoAuthenticate(OrientDBEmbedded.java:236)
	at com.orientechnologies.orient.core.db.OrientDBEmbedded.openNoAuthenticate(OrientDBEmbedded.java:59)
	at com.orientechnologies.orient.server.OServer.openDatabase(OServer.java:923)
	at com.orientechnologies.orient.server.OClientConnection.init(OClientConnection.java:235)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.onBeforeOperationalRequest(ONetworkProtocolBinary.java:452)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.sessionRequest(ONetworkProtocolBinary.java:260)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.execute(ONetworkProtocolBinary.java:206)
	at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:69)

## Steps to reproduce  
The code is like this:
There is an ODatabasePool instance that has been created:
   	pool = new ODatabasePool(orientDB, settings.getDatabase(), settings.getUsr(), settings.getPwd(), config);

Each time I want to execute a query I acquire an ODatabaseSession instance from this pool and call activateOnCurrentThread() on it.

Then I build a statement with some constant strings and some parameters and call query in a try block where the finally block closes both the result set and the ODatabaseSession:
e.g.
		ODatabaseSession conn = null;
		OResultSet rs = null;
		try {
			conn = orientDBFactory.getDB();
			List<myEntity> results = new ArrayList<>();
			String statement = MSHT_GUID_SELECT + GUID;
			Map<String, Object> params = new HashMap<>();
			params.put(GUID, guid);
			rs = conn.query(statement, params);
			while (rs.hasNext()) {
				OResult item = rs.next();
				results.add(fromDoc(item.toElement()));
			}

			return (results.isEmpty() ? Optional.empty() : Optional.ofNullable(results.get(0)));
		} finally {
			closeRs(rs);
			closeConn(conn);
		}

where closeRs and closeConn are defined as follow:
	private void closeRs(OResultSet rs) {
		if (rs != null) {
			rs.close();
		}

	}
	private void closeConn(ODatabaseSession conn) {
		if (conn != null && conn.isActiveOnCurrentThread()) {
			conn.close();
		}
		
	}

fromDoc() just converts from OElement to the type of java POJO I want to return. It does not use do anything with orientdb connections or APIs.

**Comment by wolf4ood** [comment]
Hi @MaryPercival 

can we close this?

Thanks
