### ISSUE TITLE
Strange behavior during saving records

### ISSUE THREAD

**Issue by vitalii-honchar** [orientechnologies/orientdb#8966]
## Expected behavior  
Save document into database

## Actual behavior  
In some cases OrientDB don't save documents. This is very strange, because first OrientDB works as expected, but then it starts don't save records and there is no exceptions. I use hooks and there is triggers event onAfterCreate, but there is no saved record.

When I try to use database after this event (save record, but records wasn't saved) I receive error when try to read documents which links to record which must be saved, but it wasn't saved.
Exceptions:
```
java.lang.IllegalArgumentException: Cluster 2731 is null
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.getClusterById(OAbstractPaginatedStorage.java:3016)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.readRecord(OAbstractPaginatedStorage.java:1405)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx$SimpleRecordReader.readRecord(ODatabaseDocumentTx.java:3395)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.executeReadRecord(ODatabaseDocumentTx.java:2008)
	at com.orientechnologies.orient.core.tx.OTransactionOptimistic.loadRecord(OTransactionOptimistic.java:187)
	at com.orientechnologies.orient.core.tx.OTransactionOptimistic.loadRecord(OTransactionOptimistic.java:162)
	at com.orientechnologies.orient.core.tx.OTransactionOptimistic.loadRecord(OTransactionOptimistic.java:291)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.load(ODatabaseDocumentTx.java:1725)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.load(ODatabaseDocumentTx.java:103)
	at com.orientechnologies.orient.core.id.ORecordId.getRecord(ORecordId.java:329)
	at com.orientechnologies.orient.core.record.impl.ODocument.validateLink(ODocument.java:436)
	at com.orientechnologies.orient.core.record.impl.ODocument.validateField(ODocument.java:240)
	at com.orientechnologies.orient.core.record.impl.ODocument.validate(ODocument.java:2047)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.save(ODatabaseDocumentTx.java:2748)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.save(ODatabaseDocumentTx.java:103)
	at com.orientechnologies.orient.core.record.impl.ODocument.save(ODocument.java:1805)
	at com.orientechnologies.orient.core.record.impl.ODocument.save(ODocument.java:1796)
	at org.orienteer.core.hook.ReferencesConsistencyHook.removeLink(ReferencesConsistencyHook.java:349)
	at org.orienteer.core.hook.ReferencesConsistencyHook.onRecordAfterDelete(ReferencesConsistencyHook.java:274)
	at com.orientechnologies.orient.core.hook.ODocumentHookAbstract.onTrigger(ODocumentHookAbstract.java:266)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.callbackHooks(ODatabaseDocumentTx.java:1146)
	at com.orientechnologies.orient.core.tx.OTransactionOptimistic.addRecord(OTransactionOptimistic.java:486)
	at com.orientechnologies.orient.core.tx.OTransactionOptimistic.deleteRecord(OTransactionOptimistic.java:299)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.delete(ODatabaseDocumentTx.java:2799)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.delete(ODatabaseDocumentTx.java:103)
	at com.orientechnologies.orient.core.record.ORecordAbstract.delete(ORecordAbstract.java:293)
	at com.orientechnologies.orient.core.record.ORecordAbstract.delete(ORecordAbstract.java:48)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.delete(ODatabaseDocumentTx.java:1801)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.delete(ODatabaseDocumentTx.java:103)
	at com.offerai.hook.OfferRequestFlyerHook.onRecordBeforeDelete(OfferRequestFlyerHook.java:86)
	at com.orientechnologies.orient.core.hook.ODocumentHookAbstract.onTrigger(ODocumentHookAbstract.java:263)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.callbackHooks(ODatabaseDocumentTx.java:1146)
	at com.orientechnologies.orient.core.tx.OTransactionOptimistic.addRecord(OTransactionOptimistic.java:411)
	at com.orientechnologies.orient.core.tx.OTransactionOptimistic.deleteRecord(OTransactionOptimistic.java:299)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.delete(ODatabaseDocumentTx.java:2799)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.delete(ODatabaseDocumentTx.java:103)
	at com.orientechnologies.orient.core.record.ORecordAbstract.delete(ORecordAbstract.java:293)
	at com.orientechnologies.orient.core.sql.OCommandExecutorSQLDelete.result(OCommandExecutorSQLDelete.java:321)
	at com.orientechnologies.orient.core.sql.OCommandExecutorSQLResultsetAbstract.pushResult(OCommandExecutorSQLResultsetAbstract.java:279)
	at com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.addResult(OCommandExecutorSQLSelect.java:759)
	at com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.handleResult(OCommandExecutorSQLSelect.java:670)
	at com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.executeSearchRecord(OCommandExecutorSQLSelect.java:627)
	at com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.serialIterator(OCommandExecutorSQLSelect.java:1638)
	at com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.fetchFromTarget(OCommandExecutorSQLSelect.java:1585)
	at com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.executeSearch(OCommandExecutorSQLSelect.java:522)
	at com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.execute(OCommandExecutorSQLSelect.java:485)
	at com.orientechnologies.orient.core.sql.OCommandExecutorSQLDelegate.execute(OCommandExecutorSQLDelegate.java:70)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.executeCommand(OAbstractPaginatedStorage.java:3400)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.command(OAbstractPaginatedStorage.java:3318)
	at com.orientechnologies.orient.core.sql.query.OSQLQuery.run(OSQLQuery.java:78)
	at com.orientechnologies.orient.core.sql.query.OSQLAsynchQuery.run(OSQLAsynchQuery.java:74)
	at com.orientechnologies.orient.core.query.OQueryAbstract.execute(OQueryAbstract.java:33)
	at com.orientechnologies.orient.core.sql.OCommandExecutorSQLDelete.execute(OCommandExecutorSQLDelete.java:200)
	at com.orientechnologies.orient.core.sql.OCommandExecutorSQLDelegate.execute(OCommandExecutorSQLDelegate.java:70)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.executeCommand(OAbstractPaginatedStorage.java:3400)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.command(OAbstractPaginatedStorage.java:3318)
	at com.orientechnologies.orient.core.command.OCommandRequestTextAbstract.execute(OCommandRequestTextAbstract.java:69)
	at org.orienteer.devutils.ODBScriptEngine.eval(ODBScriptEngine.java:45)
	at ru.ydn.wicket.wicketconsole.ScriptExecutor.executeWithoutHistory(ScriptExecutor.java:86)
	at ru.ydn.wicket.wicketconsole.ScriptExecutor.execute(ScriptExecutor.java:73)
	at ru.ydn.wicket.wicketconsole.WicketConsolePanel.onScriptExecute(WicketConsolePanel.java:136)
	at ru.ydn.wicket.wicketconsole.WicketConsolePanel$1.onSubmit(WicketConsolePanel.java:62)
	at org.apache.wicket.ajax.form.AjaxFormSubmitBehavior$AjaxFormSubmitter.onSubmit(AjaxFormSubmitBehavior.java:223)
	at org.apache.wicket.markup.html.form.Form.delegateSubmit(Form.java:1308)
	at org.apache.wicket.markup.html.form.Form.process(Form.java:1001)
	at org.apache.wicket.markup.html.form.Form.onFormSubmitted(Form.java:825)
	at org.apache.wicket.ajax.form.AjaxFormSubmitBehavior.onEvent(AjaxFormSubmitBehavior.java:176)
	at org.apache.wicket.ajax.AjaxEventBehavior.respond(AjaxEventBehavior.java:127)
	at org.apache.wicket.ajax.AbstractDefaultAjaxBehavior.onRequest(AbstractDefaultAjaxBehavior.java:598)
	at org.apache.wicket.core.request.handler.ListenerRequestHandler.internalInvoke(ListenerRequestHandler.java:306)
	at org.apache.wicket.core.request.handler.ListenerRequestHandler.invoke(ListenerRequestHandler.java:280)
	at org.apache.wicket.core.request.handler.ListenerRequestHandler.invokeListener(ListenerRequestHandler.java:222)
	at org.apache.wicket.core.request.handler.ListenerRequestHandler.respond(ListenerRequestHandler.java:208)
	at org.apache.wicket.request.cycle.RequestCycle$HandlerExecutor.respond(RequestCycle.java:914)
	at org.apache.wicket.request.RequestHandlerExecutor.execute(RequestHandlerExecutor.java:65)
	at org.apache.wicket.request.cycle.RequestCycle.execute(RequestCycle.java:282)
	at org.apache.wicket.request.cycle.RequestCycle.processRequest(RequestCycle.java:253)
	at org.apache.wicket.request.cycle.RequestCycle.processRequestAndDetach(RequestCycle.java:221)
	at org.apache.wicket.protocol.http.WicketFilter.processRequestCycle(WicketFilter.java:275)
	at org.apache.wicket.protocol.http.WicketFilter.processRequest(WicketFilter.java:206)
	at org.apache.wicket.protocol.http.WicketFilter.doFilter(WicketFilter.java:299)
	at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:82)
	at com.google.inject.servlet.ManagedFilterPipeline.dispatch(ManagedFilterPipeline.java:120)
	at com.google.inject.servlet.GuiceFilter.doFilter(GuiceFilter.java:133)
	at org.orienteer.core.OrienteerFilter.doFilter(OrienteerFilter.java:110)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1634)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:533)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:146)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:548)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:257)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1595)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:255)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1340)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:203)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:473)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1564)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:201)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1242)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:144)
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:220)
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:126)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.Server.handle(Server.java:503)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:364)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:260)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:305)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:118)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:333)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:310)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:126)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:366)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:765)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:683)
	at java.lang.Thread.run(Thread.java:748)
```

```
Caused by: com.orientechnologies.orient.core.exception.ORecordNotFoundException: The record with id '#2731:0' was not found
	DB name="Orienteer"
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.readRecord(OAbstractPaginatedStorage.java:1407)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx$SimpleRecordReader.readRecord(ODatabaseDocumentTx.java:3395)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.executeReadRecord(ODatabaseDocumentTx.java:2008)
	at com.orientechnologies.orient.core.tx.OTransactionOptimistic.loadRecord(OTransactionOptimistic.java:187)
	at com.orientechnologies.orient.core.tx.OTransactionOptimistic.loadRecord(OTransactionOptimistic.java:162)
	at com.orientechnologies.orient.core.tx.OTransactionOptimistic.loadRecord(OTransactionOptimistic.java:291)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.load(ODatabaseDocumentTx.java:1725)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.load(ODatabaseDocumentTx.java:103)
	at com.orientechnologies.orient.core.record.impl.ODocument.field(ODocument.java:828)
	at ru.ydn.wicket.wicketorientdb.model.DynamicPropertyValueModel.load(DynamicPropertyValueModel.java:46)
	at org.apache.wicket.model.LoadableDetachableModel.getObject(LoadableDetachableModel.java:128)
	at org.apache.wicket.Component.getDefaultModelObject(Component.java:1579)
	... 105 more
Caused by: java.lang.IllegalArgumentException: Cluster 2731 is null
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.getClusterById(OAbstractPaginatedStorage.java:3016)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.readRecord(OAbstractPaginatedStorage.java:1405)
	... 116 more
```

I can give you this database if need.

Thanks, 
Vitalii

**Comment by WeaxMe** [comment]
This is very important for us. I need to know this is OrientDB issue or this is our issue...

**Comment by PhantomYdn** [comment]
@laa , @luigidellaquila , could you please advise about the issue?

**Comment by WeaxMe** [comment]
I debug OrientDB and found that exception throws when we try to read OUser._allowRead field or OUser._allowUpdate field.

```
2019-07-30 11:10:19:206 WARNI {db=Orienteer} Error deserializing record with id #1165:1 send this data for debugging: ABZPU2VsbGVyVXNlcpUCAAAAWskBAAAAaMsBAAAAbZcCAAAAcw0AAAB+CQAAAIgBAAABBw8AAAEVlQMAAAEYaQAAAT0LAAABQBEAAAFDEwAAAUelAgAAAUsAGmJAb2ZmZXJhaS5jb20ISmFjawpCdXJucxQ0MjUyODM4MjIyElNVU1BFTkRFRPoBe1BCS0RGMldpdGhIbWFjU0hBMjU2fUIzNTQ5OUFGQjFBMzdFN0FDNDZGQTFERkU2ODNFQzQ4MkY0OUExRUQwNjJBMzQ2NjpGQkQzQUJCOUI0OUYwNTg1NUFFODBBMUJCQUMzMUYyOUQ1RTBGNDUwRUJFNjkwQjM6NjU1MzYaYkBvZmZlcmFpLmNvbQIKAEgwNzdkNDgxYi02ZjU5LTRmZWMtOTVhOC1jYmNjMDNlNDQ2MTXUAwgCCBQCmhIBApoSAeqy6KyFWw==  [ORecordSerializerBinary]$ANSI{green {db=Orienteer}} Error on fetching record during browsing. The record has been skipped
com.orientechnologies.orient.core.exception.ODatabaseException: Error on retrieving record #1165:1 (cluster: oselleruser_2)
	DB name="Orienteer"
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.executeReadRecord(ODatabaseDocumentTx.java:2046)
	at com.orientechnologies.orient.core.tx.OTransactionNoTx.loadRecord(OTransactionNoTx.java:98)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.load(ODatabaseDocumentTx.java:1757)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.load(ODatabaseDocumentTx.java:103)
	at com.orientechnologies.orient.core.iterator.OIdentifiableIterator.readCurrentRecord(OIdentifiableIterator.java:300)
	at com.orientechnologies.orient.core.iterator.ORecordIteratorClusters.hasNext(ORecordIteratorClusters.java:167)
	at com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.serialIterator(OCommandExecutorSQLSelect.java:1636)
	at com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.fetchFromTarget(OCommandExecutorSQLSelect.java:1585)
	at com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.executeSearch(OCommandExecutorSQLSelect.java:522)
	at com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.execute(OCommandExecutorSQLSelect.java:485)
	at com.orientechnologies.orient.core.sql.OCommandExecutorSQLDelegate.execute(OCommandExecutorSQLDelegate.java:70)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.executeCommand(OAbstractPaginatedStorage.java:3400)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.command(OAbstractPaginatedStorage.java:3318)
	at com.orientechnologies.orient.core.sql.query.OSQLQuery.run(OSQLQuery.java:78)
	at com.orientechnologies.orient.core.sql.query.OSQLAsynchQuery.run(OSQLAsynchQuery.java:74)
	at com.orientechnologies.orient.core.sql.query.OSQLSynchQuery.run(OSQLSynchQuery.java:102)
	at com.orientechnologies.orient.core.query.OQueryAbstract.execute(OQueryAbstract.java:33)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.query(ODatabaseDocumentTx.java:756)
	at com.offerai.repository.AgentRepository.getModerators(AgentRepository.java:43)
	at ru.ydn.wicket.wicketorientdb.utils.DBClosure$1.execute(DBClosure.java:101)
	at ru.ydn.wicket.wicketorientdb.utils.DBClosure.execute(DBClosure.java:55)
	at ru.ydn.wicket.wicketorientdb.utils.DBClosure.sudo(DBClosure.java:103)
	at com.offerai.repository.AgentRepository.getModerators(AgentRepository.java:35)
	at com.offerai.model.offer.OfferRequestStatus.lambda$static$3(OfferRequestStatus.java:25)
	at com.offerai.model.offer.OfferRequestStatus.getParticipants(OfferRequestStatus.java:113)
	at com.offerai.service.offer.request.IOfferRequestNotifyService.notify(IOfferRequestNotifyService.java:22)
	at com.offerai.hook.OfferRequestHook.onRecordAfterCreate(OfferRequestHook.java:114)
	at com.orientechnologies.orient.core.hook.ODocumentHookAbstract.onTrigger(ODocumentHookAbstract.java:221)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.callbackHooks(ODatabaseDocumentTx.java:1146)
	at com.orientechnologies.orient.core.tx.OTransactionOptimistic.addRecord(OTransactionOptimistic.java:474)
	at com.orientechnologies.orient.core.tx.OTransactionOptimistic.saveRecord(OTransactionOptimistic.java:334)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.save(ODatabaseDocumentTx.java:2768)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.save(ODatabaseDocumentTx.java:103)
	at com.orientechnologies.orient.core.record.impl.ODocument.save(ODocument.java:1805)
	at com.orientechnologies.orient.core.record.impl.ODocument.save(ODocument.java:1796)
	at com.offerai.repository.DatabaseHelper.lambda$save$3(DatabaseHelper.java:59)
	at com.offerai.repository.DatabaseHelper.update(DatabaseHelper.java:170)
	at com.offerai.repository.DatabaseHelper.save(DatabaseHelper.java:56)
	at com.offerai.repository.DatabaseHelper.lambda$save$5(DatabaseHelper.java:83)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at com.offerai.repository.DatabaseHelper.save(DatabaseHelper.java:83)
	at com.offerai.repository.DatabaseHelper.save(DatabaseHelper.java:48)
	at com.offerai.service.offer.request.OfferRequestService.createSellerLeadOffer(OfferRequestService.java:73)
	at com.offerai.service.offer.request.IOfferRequestService.lambda$createSellerLeadOffer$4(IOfferRequestService.java:37)
	at ru.ydn.wicket.wicketorientdb.utils.DBClosure$2.execute(DBClosure.java:114)
	at ru.ydn.wicket.wicketorientdb.utils.DBClosure$2.execute(DBClosure.java:111)
	at ru.ydn.wicket.wicketorientdb.utils.DBClosure.execute(DBClosure.java:55)
	at ru.ydn.wicket.wicketorientdb.utils.DBClosure.sudoConsumer(DBClosure.java:117)
	at com.offerai.service.offer.request.IOfferRequestService.createSellerLeadOffer(IOfferRequestService.java:37)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.wicket.proxy.LazyInitProxyFactory$JdkHandler.invoke(LazyInitProxyFactory.java:521)
	at com.sun.proxy.$Proxy79.createSellerLeadOffer(Unknown Source)
	at com.offerai.component.panel.OfferRequestFormPanel.onEvent(OfferRequestFormPanel.java:114)
	at org.apache.wicket.settings.FrameworkSettings.dispatchEvent(FrameworkSettings.java:151)
	at org.apache.wicket.ComponentEventSender.dispatchToComponent(ComponentEventSender.java:282)
	at org.apache.wicket.ComponentEventSender.access$100(ComponentEventSender.java:36)
	at org.apache.wicket.ComponentEventSender$ComponentEventVisitor.component(ComponentEventSender.java:329)
	at org.apache.wicket.ComponentEventSender$ComponentEventVisitor.component(ComponentEventSender.java:306)
	at org.apache.wicket.Component.visitParents(Component.java:3396)
	at org.apache.wicket.Component.visitParents(Component.java:3361)
	at org.apache.wicket.ComponentEventSender.bubble(ComponentEventSender.java:250)
	at org.apache.wicket.ComponentEventSender.send(ComponentEventSender.java:65)
	at org.apache.wicket.Component.send(Component.java:4413)
	at com.offerai.component.panel.OfferFormContactPanel$1.onSubmit(OfferFormContactPanel.java:45)
	at org.apache.wicket.ajax.markup.html.form.AjaxSubmitLink$1.onSubmit(AjaxSubmitLink.java:111)
	at org.apache.wicket.ajax.form.AjaxFormSubmitBehavior$AjaxFormSubmitter.onSubmit(AjaxFormSubmitBehavior.java:223)
	at org.apache.wicket.markup.html.form.Form.delegateSubmit(Form.java:1308)
	at org.apache.wicket.markup.html.form.Form.process(Form.java:1001)
	at org.apache.wicket.markup.html.form.Form.onFormSubmitted(Form.java:825)
	at org.apache.wicket.ajax.form.AjaxFormSubmitBehavior.onEvent(AjaxFormSubmitBehavior.java:176)
	at org.apache.wicket.ajax.AjaxEventBehavior.respond(AjaxEventBehavior.java:127)
	at org.apache.wicket.ajax.AbstractDefaultAjaxBehavior.onRequest(AbstractDefaultAjaxBehavior.java:598)
	at org.apache.wicket.core.request.handler.ListenerRequestHandler.internalInvoke(ListenerRequestHandler.java:306)
	at org.apache.wicket.core.request.handler.ListenerRequestHandler.invoke(ListenerRequestHandler.java:280)
	at org.apache.wicket.core.request.handler.ListenerRequestHandler.invokeListener(ListenerRequestHandler.java:222)
	at org.apache.wicket.core.request.handler.ListenerRequestHandler.respond(ListenerRequestHandler.java:208)
	at org.apache.wicket.request.cycle.RequestCycle$HandlerExecutor.respond(RequestCycle.java:914)
	at org.apache.wicket.request.RequestHandlerExecutor.execute(RequestHandlerExecutor.java:65)
	at org.apache.wicket.request.cycle.RequestCycle.execute(RequestCycle.java:282)
	at org.apache.wicket.request.cycle.RequestCycle.processRequest(RequestCycle.java:253)
	at org.apache.wicket.request.cycle.RequestCycle.processRequestAndDetach(RequestCycle.java:221)
	at org.apache.wicket.protocol.http.WicketFilter.processRequestCycle(WicketFilter.java:275)
	at org.apache.wicket.protocol.http.WicketFilter.processRequest(WicketFilter.java:206)
	at org.apache.wicket.protocol.http.WicketFilter.doFilter(WicketFilter.java:299)
	at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:82)
	at com.google.inject.servlet.ManagedFilterPipeline.dispatch(ManagedFilterPipeline.java:120)
	at com.google.inject.servlet.GuiceFilter.doFilter(GuiceFilter.java:133)
	at org.orienteer.core.OrienteerFilter.doFilter(OrienteerFilter.java:110)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1634)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:533)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:146)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:548)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:257)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1595)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:255)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1340)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:203)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:473)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1564)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:201)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1242)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:144)
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:220)
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:126)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.Server.handle(Server.java:503)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:364)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:260)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:305)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:118)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:333)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:310)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:126)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:366)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:765)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:683)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IllegalArgumentException: Record with id #1165:-1 has not be found
	at com.orientechnologies.orient.core.db.record.ORecordLazySet.add(ORecordLazySet.java:149)
	at com.orientechnologies.orient.core.db.record.ORecordLazySet.add(ORecordLazySet.java:52)
	at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinaryV0.readLinkCollection(ORecordSerializerBinaryV0.java:600)
	at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinaryV0.deserializeValue(ORecordSerializerBinaryV0.java:455)
	at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinaryV0.deserialize(ORecordSerializerBinaryV0.java:277)
	at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinary.fromStream(ORecordSerializerBinary.java:80)
	at com.orientechnologies.orient.core.record.impl.ODocument.deserializeFields(ODocument.java:1854)
	at com.orientechnologies.orient.core.record.impl.ODocument.checkForFields(ODocument.java:2626)
	at com.orientechnologies.orient.core.record.impl.ODocument.field(ODocument.java:1063)
	at com.orientechnologies.orient.core.record.impl.ODocument.field(ODocument.java:914)
	at org.orienteer.core.hook.CalculablePropertiesHook.onRecordAfterRead(CalculablePropertiesHook.java:176)
	at com.orientechnologies.orient.core.hook.ODocumentHookAbstract.onTrigger(ODocumentHookAbstract.java:236)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.callbackHooks(ODatabaseDocumentTx.java:1146)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.executeReadRecord(ODatabaseDocumentTx.java:2031)
	... 122 more
```
We update this fields when user creates: https://github.com/OrienteerBAP/Orienteer/blob/master/orienteer-users/src/main/java/org/orienteer/users/hook/OrienteerUserHook.java#L63-L64

May be problem is in this place? We update links when record didn't exists yet.
But if this is true, so why another records works? I can't reproduce issue manually. I don't know when it starts throws exception (means that saving record is incorrect, as I understand)
