### ISSUE TITLE
Parsing error during parse query

### ISSUE THREAD

**Issue by WeaxMe** [orientechnologies/orientdb#8975]
## Expected behavior  
This query success executes:
`select from FilterTestOClass where datetime in [date('2017-01-01 01:01:01.000', 'yyyy-MM-dd HH:mm:ss.SSS')]`

## Actual behavior  
Query `select from FilterTestOClass where datetime in [date('2017-01-01 01:01:01.000', 'yyyy-MM-dd HH:mm:ss.SSS')]` throws exception.

```
com.orientechnologies.orient.core.exception.OQueryParsingException: Error on parsing query at position #72: Error on parsing query
Query:  datetime IN [date('2017-01-01 01:01:01.000', 'yyyy-MM-dd HH:mm:ss.SSS')]
-----------------------------------------------------------------------------^
	DB name="WicketOrientTestDb"
	at com.orientechnologies.orient.core.sql.filter.OSQLPredicate.text(OSQLPredicate.java:107)
	at com.orientechnologies.orient.core.sql.filter.OSQLFilter.<init>(OSQLFilter.java:53)
	at com.orientechnologies.orient.core.sql.OSQLEngine.parseCondition(OSQLEngine.java:496)
	at com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.parse(OCommandExecutorSQLSelect.java:285)
	at com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.parse(OCommandExecutorSQLSelect.java:96)
	at com.orientechnologies.orient.core.sql.OCommandExecutorSQLDelegate.parse(OCommandExecutorSQLDelegate.java:58)
	at com.orientechnologies.orient.core.sql.OCommandExecutorSQLDelegate.parse(OCommandExecutorSQLDelegate.java:39)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.command(OAbstractPaginatedStorage.java:3920)
	at com.orientechnologies.orient.core.sql.query.OSQLQuery.run(OSQLQuery.java:77)
	at com.orientechnologies.orient.core.sql.query.OSQLAsynchQuery.run(OSQLAsynchQuery.java:74)
	at com.orientechnologies.orient.core.sql.query.OSQLSynchQuery.run(OSQLSynchQuery.java:86)
	at com.orientechnologies.orient.core.query.OQueryAbstract.execute(OQueryAbstract.java:33)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentAbstract.query(ODatabaseDocumentAbstract.java:313)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.query(ODatabaseDocumentTx.java:762)
	at ru.ydn.wicket.wicketorientdb.filter.TestFilters.lambda$testDateTimeCollection$0(TestFilters.java:288)
	at ru.ydn.wicket.wicketorientdb.utils.DBClosure$2.execute(DBClosure.java:114)
	at ru.ydn.wicket.wicketorientdb.utils.DBClosure$2.execute(DBClosure.java:111)
	at ru.ydn.wicket.wicketorientdb.utils.DBClosure.execute(DBClosure.java:55)
	at ru.ydn.wicket.wicketorientdb.utils.DBClosure.sudoConsumer(DBClosure.java:117)
	at ru.ydn.wicket.wicketorientdb.filter.TestFilters.testDateTimeCollection(TestFilters.java:287)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at ru.ydn.wicket.wicketorientdb.filter.WicketOrientDbFilterTesterScope$1.evaluate(WicketOrientDbFilterTesterScope.java:37)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
Caused by: com.orientechnologies.orient.core.exception.OSerializationException: Found invalid ) character at position 25 of text 'yyyy-MM-dd HH:mm:ss.SSS'). Ensure it is opened and closed correctly.
	DB name="WicketOrientTestDb"
	at com.orientechnologies.orient.core.serialization.serializer.OStringSerializerHelper.parse(OStringSerializerHelper.java:360)
	at com.orientechnologies.orient.core.serialization.serializer.OStringSerializerHelper.parse(OStringSerializerHelper.java:304)
	at com.orientechnologies.orient.core.serialization.serializer.OStringSerializerHelper.smartSplit(OStringSerializerHelper.java:246)
	at com.orientechnologies.orient.core.sql.filter.OSQLFilterItemAbstract.<init>(OSQLFilterItemAbstract.java:58)
	at com.orientechnologies.orient.core.sql.filter.OSQLFilterItemField.<init>(OSQLFilterItemField.java:102)
	at com.orientechnologies.orient.core.sql.OSQLHelper.parseValue(OSQLHelper.java:250)
	at com.orientechnologies.orient.core.sql.OSQLHelper.parseValue(OSQLHelper.java:225)
	at com.orientechnologies.orient.core.sql.OSQLHelper.parseValue(OSQLHelper.java:221)
	at com.orientechnologies.orient.core.sql.filter.OSQLPredicate.convertCollectionItems(OSQLPredicate.java:364)
	at com.orientechnologies.orient.core.sql.filter.OSQLPredicate.extractConditionItem(OSQLPredicate.java:310)
	at com.orientechnologies.orient.core.sql.filter.OSQLPredicate.extractCondition(OSQLPredicate.java:203)
	at com.orientechnologies.orient.core.sql.filter.OSQLPredicate.extractConditions(OSQLPredicate.java:144)
	at com.orientechnologies.orient.core.sql.filter.OSQLPredicate.text(OSQLPredicate.java:96)
	... 45 more


```

If execute this query from OrientDB web studio it successfully executes, but if execute it from Java API it ends with exception

## Steps to reproduce  
```
            List<?> query = db.query(new OSQLSynchQuery<>("select from FilterTestOClass where datetime in [date('2017-01-01 01:01:01.000', 'yyyy-MM-dd HH:mm:ss.SSS')]"));

```

**Comment by WeaxMe** [comment]
May be error is in this method: https://github.com/orientechnologies/orientdb/blob/f2deb4877761e2465145f7dce20e19ae7521a223/core/src/main/java/com/orientechnologies/orient/core/serialization/serializer/OStringSerializerHelper.java#L309

**Comment by wolf4ood** [comment]
Hi @WeaxMe 

the reason why it works with studio is that, the new parser executor is used.
By using the 

```
            List<?> query = db.query(new OSQLSynchQuery<>("select from FilterTestOClass where datetime in [date('2017-01-01 01:01:01.000', 'yyyy-MM-dd HH:mm:ss.SSS')]"));

```
APIs it will use the old parser/executor which has been replaced. 

Is there a reason why you are not using the new APIs?

Link for the reference

http://orientdb.com/docs/3.0.x/java/Java-Query-API.html

**Comment by WeaxMe** [comment]
Hi @wolf4ood 

I tried to use new API and it works. Yeah I migrate from 2.2.x and tried compile project, but test fails, so will move to new API.

Thanks!
