### ISSUE TITLE
ClassCastException OMixedIndexRIDContainer cannot be cast to sbtree.OIndexRIDContainer 

### ISSUE THREAD

**Issue by jayaramcs** [orientechnologies/orientdb#8983]
## Expected behavior  
No class cast exception   

## Actual behavior  

Upon upgrading from 2.x to 3.0.21 and trying to insert a record, this error is thrown. 

  ```
 com.orientechnologies.orient.core.exception.ODatabaseException: Error during saving of record with rid #121:1
	DB name="mydb"
	at com.orientechnologies.orient.core.tx.OTransactionNoTx.saveRecord(OTransactionNoTx.java:206)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentAbstract.saveInternal(ODatabaseDocumentAbstract.java:2099)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentAbstract.save(ODatabaseDocumentAbstract.java:2064)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentAbstract.save(ODatabaseDocumentAbstract.java:1954)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentAbstract.save(ODatabaseDocumentAbstract.java:85)
...
Caused by: java.lang.ClassCastException: com.orientechnologies.orient.core.storage.ridbag.sbtree.OMixedIndexRIDContainer cannot be cast to com.orientechnologies.orient.core.storage.ridbag.sbtree.OIndexRIDContainer
	at com.orientechnologies.orient.core.serialization.serializer.stream.OStreamSerializerSBTreeIndexRIDContainer.getObjectSize(OStreamSerializerSBTreeIndexRIDContainer.java:42)
	at com.orientechnologies.orient.core.storage.index.hashindex.local.OHashIndexBucket.addEntry(OHashIndexBucket.java:302)
	at com.orientechnologies.orient.core.storage.index.hashindex.local.OLocalHashTable.doPut(OLocalHashTable.java:1295)
SEVERE [com.orientechnologies.orient.core.storage.disk.OLocalPaginatedStorage]: Exception `4E59EBAD` in storage `plocal:C:\temp\3.0/mydb`: 3.0.21 - Veloce (build 1d8b0c01ca8fe12a516bba355681e3ec8b218d1d, branch 3.0.x)
java.lang.ClassCastException: com.orientechnologies.orient.core.storage.ridbag.sbtree.OMixedIndexRIDContainer cannot be cast to com.orientechnologies.orient.core.storage.ridbag.sbtree.OIndexRIDContainer
	at com.orientechnologies.orient.core.serialization.serializer.stream.OStreamSerializerSBTreeIndexRIDContainer.getObjectSize(OStreamSerializerSBTreeIndexRIDContainer.java:42)
	at com.orientechnologies.orient.core.storage.index.hashindex.local.OLocalHashTable.put(OLocalHashTable.java:1195)
	at com.orientechnologies.orient.core.storage.index.hashindex.local.OLocalHashTable.put(OLocalHashTable.java:259)
	at com.orientechnologies.orient.core.storage.index.engine.OHashTableIndexEngine.put(OHashTableIndexEngine.java:173)
	at com.orientechnologies.orient.core.storage.index.engine.OHashTableIndexEngine.update(OHashTableIndexEngine.java:181)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.doUpdateIndexEntry(OAbstractPaginatedStorage.java:2821)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.updateIndexEntry(OAbstractPaginatedStorage.java:2732)
	at com.orientechnologies.orient.core.index.OIndexMultiValues.doPutV0(OIndexMultiValues.java:189)
	at com.orientechnologies.orient.core.index.OIndexMultiValues.put(OIndexMultiValues.java:128)
	at com.orientechnologies.orient.core.index.OIndexMultiValues.put(OIndexMultiValues.java:53)
	at com.orientechnologies.orient.core.index.OIndexAbstract.putInSnapshot(OIndexAbstract.java:847)
	at com.orientechnologies.orient.core.index.OIndexAbstract.applyIndexTxEntry(OIndexAbstract.java:693)
	at com.orientechnologies.orient.core.index.OIndexAbstract.addTxOperation(OIndexAbstract.java:665)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.commitIndexes(OAbstractPaginatedStorage.java:2242)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.commit(OAbstractPaginatedStorage.java:2170)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.commit(OAbstractPaginatedStorage.java:1993)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentAbstract.internalCommit(ODatabaseDocumentAbstract.java:2732)
	at com.orientechnologies.orient.core.storage.impl.local.OMicroTransaction.doCommit(OMicroTransaction.java:363)
	at com.orientechnologies.orient.core.storage.impl.local.OMicroTransaction.commit(OMicroTransaction.java:166)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentEmbedded.endMicroTransaction(ODatabaseDocumentEmbedded.java:799)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentEmbedded.executeSaveRecord(ODatabaseDocumentEmbedded.java:789)
	at com.orientechnologies.orient.core.tx.OTransactionNoTx.saveNew(OTransactionNoTx.java:244)
	at com.orientechnologies.orient.core.tx.OTransactionNoTx.saveRecord(OTransactionNoTx.java:174)
	... 17 common frames omitted
10:46:39.376 [Thread-37] ERROR c.b.d.c.u.v.h.CreateSessionStandardModeTask - DB Exception
	at com.orientechnologies.orient.core.storage.index.hashindex.local.OHashIndexBucket.addEntry(OHashIndexBucket.java:302)
	at com.orientechnologies.orient.core.storage.index.hashindex.local.OLocalHashTable.doPut(OLocalHashTable.java:1295)
	at com.orientechnologies.orient.core.storage.index.hashindex.local.OLocalHashTable.put(OLocalHashTable.java:1195)
	at com.orientechnologies.orient.core.storage.index.hashindex.local.OLocalHashTable.put(OLocalHashTable.java:259)
	at com.orientechnologies.orient.core.storage.index.engine.OHashTableIndexEngine.put(OHashTableIndexEngine.java:173)
	at com.orientechnologies.orient.core.storage.index.engine.OHashTableIndexEngine.update(OHashTableIndexEngine.java:181)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.doUpdateIndexEntry(OAbstractPaginatedStorage.java:2821)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.updateIndexEntry(OAbstractPaginatedStorage.java:2732)
	at com.orientechnologies.orient.core.index.OIndexMultiValues.doPutV0(OIndexMultiValues.java:189)
	at com.orientechnologies.orient.core.index.OIndexMultiValues.put(OIndexMultiValues.java:128)
	at com.orientechnologies.orient.core.index.OIndexMultiValues.put(OIndexMultiValues.java:53)
	at com.orientechnologies.orient.core.index.OIndexAbstract.putInSnapshot(OIndexAbstract.java:847)
	at com.orientechnologies.orient.core.index.OIndexAbstract.applyIndexTxEntry(OIndexAbstract.java:693)
	at com.orientechnologies.orient.core.index.OIndexAbstract.addTxOperation(OIndexAbstract.java:665)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.commitIndexes(OAbstractPaginatedStorage.java:2242)
[catch] at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.commit(OAbstractPaginatedStorage.java:2170)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.commit(OAbstractPaginatedStorage.java:1993)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentAbstract.internalCommit(ODatabaseDocumentAbstract.java:2732)
	at com.orientechnologies.orient.core.storage.impl.local.OMicroTransaction.doCommit(OMicroTransaction.java:363)
	at com.orientechnologies.orient.core.storage.impl.local.OMicroTransaction.commit(OMicroTransaction.java:166)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentEmbedded.endMicroTransaction(ODatabaseDocumentEmbedded.java:799)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentEmbedded.executeSaveRecord(ODatabaseDocumentEmbedded.java:789)
	at com.orientechnologies.orient.core.tx.OTransactionNoTx.saveNew(OTransactionNoTx.java:244)
	at com.orientechnologies.orient.core.tx.OTransactionNoTx.saveRecord(OTransactionNoTx.java:174)
 com.orientechnologies.orient.core.exception.ODatabaseException: Error during saving of record with rid #121:1
	DB name="mydb"
...
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentAbstract.saveInternal(ODatabaseDocumentAbstract.java:2099)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentAbstract.save(ODatabaseDocumentAbstract.java:2064)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentAbstract.save(ODatabaseDocumentAbstract.java:1954)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentAbstract.save(ODatabaseDocumentAbstract.java:85)
   
java.lang.ClassCastException: com.orientechnologies.orient.core.storage.ridbag.sbtree.OMixedIndexRIDContainer cannot be cast to com.orientechnologies.orient.core.storage.ridbag.sbtree.OIndexRIDContainer
Caused by: com.orientechnologies.orient.core.exception.ODatabaseException: Error during saving of record with rid #121:1
	at com.orientechnologies.orient.core.serialization.serializer.stream.OStreamSerializerSBTreeIndexRIDContainer.getObjectSize(OStreamSerializerSBTreeIndexRIDContainer.java:42)
	DB name="mydb"
	at com.orientechnologies.orient.core.tx.OTransactionNoTx.saveRecord(OTransactionNoTx.java:206)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentAbstract.saveInternal(ODatabaseDocumentAbstract.java:2099)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentAbstract.save(ODatabaseDocumentAbstract.java:2064)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentAbstract.save(ODatabaseDocumentAbstract.java:1954)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentAbstract.save(ODatabaseDocumentAbstract.java:85) 
	... 12 common frames omitted
Caused by: java.lang.ClassCastException: com.orientechnologies.orient.core.storage.ridbag.sbtree.OMixedIndexRIDContainer cannot be cast to com.orientechnologies.orient.core.storage.ridbag.sbtree.OIndexRIDContainer
	at com.orientechnologies.orient.core.serialization.serializer.stream.OStreamSerializerSBTreeIndexRIDContainer.getObjectSize(OStreamSerializerSBTreeIndexRIDContainer.java:42)
	at com.orientechnologies.orient.core.storage.index.hashindex.local.OHashIndexBucket.addEntry(OHashIndexBucket.java:302)
	at com.orientechnologies.orient.core.storage.index.hashindex.local.OLocalHashTable.doPut(OLocalHashTable.java:1295)
	at com.orientechnologies.orient.core.storage.index.hashindex.local.OLocalHashTable.put(OLocalHashTable.java:1195)
	at com.orientechnologies.orient.core.storage.index.hashindex.local.OLocalHashTable.put(OLocalHashTable.java:259)
	at com.orientechnologies.orient.core.storage.index.engine.OHashTableIndexEngine.put(OHashTableIndexEngine.java:173)
	at com.orientechnologies.orient.core.storage.index.engine.OHashTableIndexEngine.update(OHashTableIndexEngine.java:181)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.doUpdateIndexEntry(OAbstractPaginatedStorage.java:2821)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.updateIndexEntry(OAbstractPaginatedStorage.java:2732)
	at com.orientechnologies.orient.core.index.OIndexMultiValues.doPutV0(OIndexMultiValues.java:189)
	at com.orientechnologies.orient.core.index.OIndexMultiValues.put(OIndexMultiValues.java:128)
	at com.orientechnologies.orient.core.index.OIndexMultiValues.put(OIndexMultiValues.java:53)
	at com.orientechnologies.orient.core.index.OIndexAbstract.putInSnapshot(OIndexAbstract.java:847)
	at com.orientechnologies.orient.core.index.OIndexAbstract.applyIndexTxEntry(OIndexAbstract.java:693)
	at com.orientechnologies.orient.core.index.OIndexAbstract.addTxOperation(OIndexAbstract.java:665)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.commitIndexes(OAbstractPaginatedStorage.java:2242)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.commit(OAbstractPaginatedStorage.java:2170)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.commit(OAbstractPaginatedStorage.java:1993)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentAbstract.internalCommit(ODatabaseDocumentAbstract.java:2732)
	at com.orientechnologies.orient.core.storage.impl.local.OMicroTransaction.doCommit(OMicroTransaction.java:363)
	at com.orientechnologies.orient.core.storage.impl.local.OMicroTransaction.commit(OMicroTransaction.java:166)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentEmbedded.endMicroTransaction(ODatabaseDocumentEmbedded.java:799)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentEmbedded.executeSaveRecord(ODatabaseDocumentEmbedded.java:789)
	at com.orientechnologies.orient.core.tx.OTransactionNoTx.saveNew(OTransactionNoTx.java:244)
	at com.orientechnologies.orient.core.tx.OTransactionNoTx.saveRecord(OTransactionNoTx.java:174)
	... 17 common frames omitted
	at com.orientechnologies.orient.core.storage.index.hashindex.local.OHashIndexBucket.addEntry(OHashIndexBucket.java:302)
	at com.orientechnologies.orient.core.storage.index.hashindex.local.OLocalHashTable.doPut(OLocalHashTable.java:1295)
	at com.orientechnologies.orient.core.storage.index.hashindex.local.OLocalHashTable.put(OLocalHashTable.java:1195)
	at com.orientechnologies.orient.core.storage.index.hashindex.local.OLocalHashTable.put(OLocalHashTable.java:259)
	at com.orientechnologies.orient.core.storage.index.engine.OHashTableIndexEngine.put(OHashTableIndexEngine.java:173)
	at com.orientechnologies.orient.core.storage.index.engine.OHashTableIndexEngine.update(OHashTableIndexEngine.java:181)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.doUpdateIndexEntry(OAbstractPaginatedStorage.java:2821)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.updateIndexEntry(OAbstractPaginatedStorage.java:2732)
	at com.orientechnologies.orient.core.index.OIndexMultiValues.doPutV0(OIndexMultiValues.java:189)
	at com.orientechnologies.orient.core.index.OIndexMultiValues.put(OIndexMultiValues.java:128)
	at com.orientechnologies.orient.core.index.OIndexMultiValues.put(OIndexMultiValues.java:53)
	at com.orientechnologies.orient.core.index.OIndexAbstract.putInSnapshot(OIndexAbstract.java:847)
	at com.orientechnologies.orient.core.index.OIndexAbstract.applyIndexTxEntry(OIndexAbstract.java:693)
	at com.orientechnologies.orient.core.index.OIndexAbstract.addTxOperation(OIndexAbstract.java:665)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.commitIndexes(OAbstractPaginatedStorage.java:2242)
[catch] at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.commit(OAbstractPaginatedStorage.java:2170)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.commit(OAbstractPaginatedStorage.java:1993)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentAbstract.internalCommit(ODatabaseDocumentAbstract.java:2732)
	at com.orientechnologies.orient.core.storage.impl.local.OMicroTransaction.doCommit(OMicroTransaction.java:363)
	at com.orientechnologies.orient.core.storage.impl.local.OMicroTransaction.commit(OMicroTransaction.java:166)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentEmbedded.endMicroTransaction(ODatabaseDocumentEmbedded.java:799)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentEmbedded.executeSaveRecord(ODatabaseDocumentEmbedded.java:789)
	at com.orientechnologies.orient.core.tx.OTransactionNoTx.saveNew(OTransactionNoTx.java:244)
	at com.orientechnologies.orient.core.tx.OTransactionNoTx.saveRecord(OTransactionNoTx.java:174)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentAbstract.saveInternal(ODatabaseDocumentAbstract.java:2099)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentAbstract.save(ODatabaseDocumentAbstract.java:2064)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentAbstract.save(ODatabaseDocumentAbstract.java:1954)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentAbstract.save(ODatabaseDocumentAbstract.java:85)
 
```

## Steps to reproduce  
Create a db in 2.x 
add data
upgrade to 3.0.21

**Comment by jayaramcs** [comment]
This seems to fix the issue, but obviously, there is the exception. 

```
orientdb {db=mydb}> rebuild index *;

Rebuilding index(es)...
Rebuilt index(es). Found
Error: java.util.IllegalFormatConversionException: d != java.util.ArrayList
```

**Comment by jayaramcs** [comment]
Quick update:
Running rebuild index from java does not seem to throw the same error. I see normal index rebuild logs in my log files.

       ```
      try {
                LOGGER.info("Rebuilding db index. This may take a few minutes to complete.");
                currentDb.command("rebuild index *;");
            } catch (Throwable ex) {
                LOGGER.error("Index rebuild failed", ex.getLocalizedMessage());
            }
```

**Comment by laa** [comment]
Fixed
