### ISSUE TITLE
OPageIsBrokenException on insert after server crash

### ISSUE THREAD

**Issue by jayaramcs** [orientechnologies/orientdb#8991]
## Expected behavior  
No exception 

## Actual behavior  
```
com.orientechnologies.orient.core.exception.OPageIsBrokenException: Following files and pages are detected to be broken ['file_9.pcl' :121;], storage is switched to 'read only' mode. Any modification operations are prohibited. To restore database and make it fully operational you may export and import database to and from JSON.
	DB name="wraith"
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.checkReadOnlyConditions(OAbstractPaginatedStorage.java:5722)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.checkLowDiskSpaceRequestsAndReadOnlyConditions(OAbstractPaginatedStorage.java:5683)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.commit(OAbstractPaginatedStorage.java:2031)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.commit(OAbstractPaginatedStorage.java:1993)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentAbstract.internalCommit(ODatabaseDocumentAbstract.java:2732)
	at com.orientechnologies.orient.core.storage.impl.local.OMicroTransaction.doCommit(OMicroTransaction.java:363)
	at com.orientechnologies.orient.core.storage.impl.local.OMicroTransaction.commit(OMicroTransaction.java:166)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentEmbedded.endMicroTransaction(ODatabaseDocumentEmbedded.java:799)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentEmbedded.executeSaveRecord(ODatabaseDocumentEmbedded.java:789)
	at com.orientechnologies.orient.core.tx.OTransactionNoTx.saveNew(OTransactionNoTx.java:248)
	at com.orientechnologies.orient.core.tx.OTransactionNoTx.saveRecord(OTransactionNoTx.java:174)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentAbstract.saveInternal(ODatabaseDocumentAbstract.java:2099)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentAbstract.save(ODatabaseDocumentAbstract.java:2064)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentAbstract.save(ODatabaseDocumentAbstract.java:85)
	at com.orientechnologies.orient.core.record.impl.ODocument.save(ODocument.java:2169)
	at com.orientechnologies.orient.core.record.impl.ODocument.save(ODocument.java:2160)
```  

## Steps to reproduce  

Crash the JVM during insert. Restart the server. Try to insert again. 

This is similar to this issue [Find files broken while write data to orientdb 2.2.30  ](https://github.com/orientechnologies/orientdb/issues/8012)

Originally we had this issue without the need to crash the server. Just inserting a large volume of data was enough to crash it. We have upgraded to 3.0.21 in hopes of solving it and the large volume insert no longer seems to create this problem (limited testing so far).

But if the JVM crashes for any reason, it results in the OPageIsBrokenException error.

Running repair database from the console had no effect. 

The larger issue we have is the ability to detect this early enough to allow for an export/restore process. Currently, the error is thrown only when that particular table is inserted into. This is simply too late for us to warn the user that the database is corrupted and needs repairs. 

Any help is much appreciated in resolving the issue.

**Comment by laa** [comment]
Sorry is not the same which you opened several days ago ? https://github.com/orientechnologies/orientdb/issues/8979

**Comment by jayaramcs** [comment]
Not really. So that issue did go away after we turned on WAL. 
To elaborate, in #8979 we had the following use case. 
- Start Orient db, WAL OFF
- insert data - info table 
- insert data - file table
- JVM Crash
- None of the data that we wrote was persisted 

Now what we are seeing is 
- Start Orient Db. WAL ON 
- insert data - info table 
- insert data - file table (massive insert declareIntent(new OIntentMassiveInsert())) 
- JVM Crash 
- info table is fine
- file table is fine for Query 
- File table crashes on insert 

Does this make sense ?

**Comment by laa** [comment]
Oh, I see, please try 3.0.22 version. I provide fix on this version, which similar to what you are experiencing. If problem still persists, please let me know.

**Comment by jayaramcs** [comment]
the 3.0.33 upgrade seems to be helping. We have not seen any more crashes. I will close this now. Should we come across it again, I will let you know.
