### ISSUE TITLE
Threads accessing orient stuck and application was arrested.

### ISSUE THREAD

**Issue by rbaarathi** [orientechnologies/orientdb#9002]
OrientDB - 2.2.20
JAVA 8
Centos - 7

Expected behavior :
                Application to work normally with read and write operation. 

Actual behavior:

              Orient document database building done separately and the same has been verified and validated. After orient building gets completed, reading on different orient storage starts.

About an hour, every thread got stuck in orient and no further moving observed and entire application gets stuck.

After several restart the same issue observed.. 

              Below stack observed in jstack during such stuck.
 
              "PlugInvokationTask-190830141841223979-190830141841210513-WDMCircuitPlug" #599 prio=5 os_prio=0 tid=0x00007f4c58028800 nid=0x91d0 waiting on condition [0x00007f4a0c6470
00]
   java.lang.Thread.State: WAITING (parking)
        at sun.misc.Unsafe.park(Native Method)
        - parking to wait for  <0x00007f4d5ea7b460> (a com.orientechnologies.common.concur.lock.OReadersWriterSpinLock)
        at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
        at com.orientechnologies.common.concur.lock.OReadersWriterSpinLock.acquireReadLock(OReadersWriterSpinLock.java:87)
        at com.orientechnologies.orient.core.storage.cache.local.twoq.O2QCache.release(O2QCache.java:437)
        at com.orientechnologies.orient.core.storage.impl.local.paginated.base.ODurableComponent.releasePage(ODurableComponent.java:169)
        at com.orientechnologies.orient.core.index.hashindex.local.OHashTableDirectory.releasePage(OHashTableDirectory.java:698)
        at com.orientechnologies.orient.core.index.hashindex.local.OHashTableDirectory.getNodeLocalDepth(OHashTableDirectory.java:465)
        at com.orientechnologies.orient.core.index.hashindex.local.OLocalHashTable.getBucket(OLocalHashTable.java:2041)
        at com.orientechnologies.orient.core.index.hashindex.local.OLocalHashTable.get(OLocalHashTable.java:354)
        at com.orientechnologies.orient.core.index.engine.OHashTableIndexEngine.get(OHashTableIndexEngine.java:145)
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.doGetIndexValue(OAbstractPaginatedStorage.java:1764)
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.getIndexValue(OAbstractPaginatedStorage.java:1753)
        at com.orientechnologies.orient.core.index.OIndexMultiValues.get(OIndexMultiValues.java:67)
        at com.orientechnologies.orient.core.index.OIndexMultiValues.get(OIndexMultiValues.java:44)
        at com.orientechnologies.orient.core.index.OIndexAbstractDelegate.get(OIndexAbstractDelegate.java:58)
        at com.orientechnologies.orient.core.index.OIndexTxAwareMultiValue.get(OIndexTxAwareMultiValue.java:297)
        at com.orientechnologies.orient.core.index.OIndexTxAwareMultiValue.get(OIndexTxAwareMultiValue.java:39)
        at in.co.nmsworks.documenttdb.db.DocDB.getDocTypeObjects(DocDB.java:188)
        at in.co.nmsworks.documenttdb.db.DocDB.getDocTypeObjects(DocDB.java:210)
        at in.co.nmsworks.cygnet.telecom.fault.rcasia.inventory.store.InvReader.getEntitiesByNonUniqueKeySearch(InvReader.java:312)
        at in.co.nmsworks.cygnet.telecom.fault.rcasia.inventory.store.wdm.WDMRcaInvReader.getConnectionEntitiesForPTPOrCTP(WDMRcaInvReader.java:657)
        at in.co.nmsworks.cygnet.telecom.fault.rcasia.inventory.store.wdm.WDMRcaInvReader.addEndTPToConnectionRoutesAndReturnConnectionKeys(WDMRcaInvReader.java:504)
        at in.co.nmsworks.cygnet.telecom.fault.rcasia.inventory.store.wdm.WDMRcaInvReader.addEndTPToConnectionRoutesAndReturnConnectionKeys(WDMRcaInvReader.java:496)
        at in.co.nmsworks.cygnet.telecom.fault.rcasia.inventory.store.wdm.WDMRcaInvReader.buildImpactAnalysisDataHolder(WDMRcaInvReader.java:2335)
        at in.co.nmsworks.cygnet.telecom.fault.rcasia.inventory.store.wdm.WDMRcaInvReader.buildImpactAnalysisDataHolder(WDMRcaInvReader.java:2190)
        at in.co.nmsworks.cygnet.telecom.fault.rcasia.inventory.store.wdm.WDMRcaInvReader.buildImpactAnalysisData(WDMRcaInvReader.java:76)
        at in.co.nmsworks.cygnet.telecom.fault.rcasia.plug.impl.circuit.wdm.impact.node.constructor.impl.PTPAndEqptImpactAnalysisDataBuilder.buildImpactAnalysisData(PTPAndEqptImpactAnalysisDataBuilder.java:34)
        at in.co.nmsworks.cygnet.telecom.fault.rcasia.plug.impl.circuit.wdm.impl.WDMCircuitPlugHelper.getImpactAnalysisDataHolder(WDMCircuitPlugHelper.java:376)
        at in.co.nmsworks.cygnet.telecom.fault.rcasia.plug.impl.circuit.wdm.impl.WDMCircuitPlugHelper.getImpactAnalysisDataHolder(WDMCircuitPlugHelper.java:355)
        at in.co.nmsworks.cygnet.telecom.fault.rcasia.plug.impl.circuit.wdm.impl.WDMCircuitPlug.acquireLockAndReturnWrapperForAnalyze(WDMCircuitPlug.java:145)
        at in.co.nmsworks.cygnet.telecom.fault.rcasia.plug.impl.circuit.wdm.impl.WDMCircuitPlug.getLockResource(WDMCircuitPlug.java:110)

Kindly please suggest on the above issue. It is very urgent..

Please suggest.......................

**Comment by rbaarathi** [comment]
"PlugInvokationTask-190830141841354934-190830141841210074-WDMCircuitPlug" #604 prio=5 os_prio=0 tid=0x00007f4bbc014800 nid=0x91d5 waiting on condition [0x00007f4a09e420
00]
   java.lang.Thread.State: WAITING (parking)
        at sun.misc.Unsafe.park(Native Method)
        - parking to wait for  <0x00007f4d5ea7b460> (a com.orientechnologies.common.concur.lock.OReadersWriterSpinLock)
        at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
        at com.orientechnologies.common.concur.lock.OReadersWriterSpinLock.acquireReadLock(OReadersWriterSpinLock.java:87)
        at com.orientechnologies.orient.core.storage.cache.local.twoq.O2QCache.release(O2QCache.java:437)
        at com.orientechnologies.orient.core.storage.impl.local.paginated.base.ODurableComponent.releasePage(ODurableComponent.java:169)
        at com.orientechnologies.orient.core.storage.impl.local.paginated.OPaginatedCluster.readRecordBuffer(OPaginatedCluster.java:701)
        at com.orientechnologies.orient.core.storage.impl.local.paginated.OPaginatedCluster.readRecord(OPaginatedCluster.java:667)
        at com.orientechnologies.orient.core.storage.impl.local.paginated.OPaginatedCluster.readRecord(OPaginatedCluster.java:646)
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.doReadRecord(OAbstractPaginatedStorage.java:3260)
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.readRecord(OAbstractPaginatedStorage.java:2879)
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.readRecord(OAbstractPaginatedStorage.java:1064)
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx$SimpleRecordReader.readRecord(ODatabaseDocumentTx.java:3436)
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.executeReadRecord(ODatabaseDocumentTx.java:2012)
        at com.orientechnologies.orient.core.tx.OTransactionNoTx.loadRecord(OTransactionNoTx.java:106)
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.load(ODatabaseDocumentTx.java:1729)
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.load(ODatabaseDocumentTx.java:102)
        at com.orientechnologies.orient.core.id.ORecordId.getRecord(ORecordId.java:329)
        at in.co.nmsworks.documenttdb.db.DocDB.getDocTypeObjects(DocDB.java:198)
        at in.co.nmsworks.documenttdb.db.DocDB.getDocTypeObjects(DocDB.java:210)
        at in.co.nmsworks.cygnet.telecom.fault.rcasia.inventory.store.InvReader.getEntitiesByNonUniqueKeySearch(InvReader.java:312)
        at in.co.nmsworks.cygnet.telecom.fault.rcasia.inventory.store.InvReader.getPortionEntitiesForPattern(InvReader.java:493)
        at in.co.nmsworks.cygnet.telecom.fault.rcasia.inventory.store.InvReader.getPortionEntitiesForPattern(InvReader.java:438)
        at in.co.nmsworks.cygnet.telecom.fault.rcasia.inventory.store.wdm.WDMRcaInvReader.getPortions(WDMRcaInvReader.java:592)
        at in.co.nmsworks.cygnet.telecom.fault.rcasia.inventory.store.wdm.WDMRcaInvReader.getPortions(WDMRcaInvReader.java:577)
        at in.co.nmsworks.cygnet.telecom.fault.rcasia.inventory.store.wdm.WDMRcaInvReader.buildImpactAnalysisDataHolder(WDMRcaInvReader.java:2305)
        at in.co.nmsworks.cygnet.telecom.fault.rcasia.inventory.store.wdm.WDMRcaInvReader.lambda$buildImpactAnalysisDataHolder$9(WDMRcaInvReader.java:2360)
        at in.co.nmsworks.cygnet.telecom.fault.rcasia.inventory.store.wdm.WDMRcaInvReader$$Lambda$249/483376995.accept(Unknown Source)
        at java.lang.Iterable.forEach(Iterable.java:75)
        at in.co.nmsworks.cygnet.telecom.fault.rcasia.inventory.store.wdm.WDMRcaInvReader.buildImpactAnalysisDataHolder(WDMRcaInvReader.java:2356)
        at in.co.nmsworks.cygnet.telecom.fault.rcasia.inventory.store.wdm.WDMRcaInvReader.buildImpactAnalysisDataHolder(WDMRcaInvReader.java:2190)
        at in.co.nmsworks.cygnet.telecom.fault.rcasia.inventory.store.wdm.WDMRcaInvReader.buildImpactAnalysisData(WDMRcaInvReader.java:76)
        at in.co.nmsworks.cygnet.telecom.fault.rcasia.plug.impl.circuit.wdm.impact.node.constructor.impl.PTPAndEqptImpactAnalysisDataBuilder.buildImpactAnalysisData(PTP
AndEqptImpactAnalysisDataBuilder.java:34)

**Comment by rbaarathi** [comment]
Please suggest when this OReadersWriterSpinLock occurs and also suggest how to overcome this..

**Comment by rbaarathi** [comment]
Please suggest when this OReadersWriterSpinLock occurs and also suggest how to overcome this..

**Comment by rbaarathi** [comment]
Hi @laa .. Please respond..

**Comment by matanshukry** [comment]
@rbaarathi OrientDB is moving towards v3.x. Can you replicate that behavior on any of the 3.x version as well?

**Comment by rbaarathi** [comment]
Hi @matanshukry.. will try to replicate in 3.x..

**Comment by tglman** [comment]
Hi,
Can you replicate this or can we close this ?
Regards
