### ISSUE TITLE
Unknown checkpoint record type

### ISSUE THREAD

**Issue by jamieb22** [orientechnologies/orientdb#9005]
### OrientDB Version: 3.0.23
[olddb.zip](https://github.com/orientechnologies/orientdb/files/3577721/olddb.zip)

## Expected behavior  
Database was created with version 2.2.37.

## Actual behavior  

```
2019-09-05 16:46:21 t.c.s.a.d.Services [DEB 2.2.37.UG] error:stop:com.orientechnologies.orient.core.exception.ODatabaseException: Cannot open database 'archiva'
com.orientechnologies.orient.core.exception.ODatabaseException: Cannot open database 'archiva'
	at com.orientechnologies.orient.core.db.OrientDBEmbedded.open(OrientDBEmbedded.java:300)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.open(ODatabaseDocumentTx.java:904)
	at com.orientechnologies.orient.core.db.OPartitionedDatabasePool$DatabaseDocumentTxPooled.internalOpen(OPartitionedDatabasePool.java:440)
	at com.orientechnologies.orient.core.db.OPartitionedDatabasePool.openDatabase(OPartitionedDatabasePool.java:303)
	at com.orientechnologies.orient.core.db.OPartitionedDatabasePool.acquire(OPartitionedDatabasePool.java:261)
	at com.tinkerpop.blueprints.impls.orient.OrientBaseGraph.<init>(OrientBaseGraph.java:172)
	at com.tinkerpop.blueprints.impls.orient.OrientTransactionalGraph.<init>(OrientTransactionalGraph.java:78)
	at com.tinkerpop.blueprints.impls.orient.OrientGraph.<init>(OrientGraph.java:137)
	at com.tinkerpop.blueprints.impls.orient.OrientGraphFactory$1.getGraph(OrientGraphFactory.java:87)
	at com.tinkerpop.blueprints.impls.orient.OrientGraphFactory.getTx(OrientGraphFactory.java:224)
	at com.stimulus.archiva.database.blueprints.BluePrintDatabaseUtil.dropOldIndexes(BluePrintDatabaseUtil.java:112)
	at com.stimulus.archiva.database.blueprints.BluePrintDatabaseUtil.initGraphFactory(BluePrintDatabaseUtil.java:171)
	at com.stimulus.archiva.database.blueprints.BluePrintDatabase.connect(BluePrintDatabase.java:96)
	at com.stimulus.archiva.database.DatabaseService.startup(DatabaseService.java:186)
	at com.stimulus.archiva.domain.Services$ServiceController.lambda$startStop$0(Services.java:142)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.orientechnologies.orient.core.exception.OStorageException: Unknown checkpoint record type com.orientechnologies.orient.core.storage.impl.local.paginated.wal.cas.OEmptyWALRecord
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.restoreFromWAL(OAbstractPaginatedStorage.java:5289)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.recoverIfNeeded(OAbstractPaginatedStorage.java:4512)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.open(OAbstractPaginatedStorage.java:376)
	at com.orientechnologies.orient.core.db.OrientDBEmbedded.open(OrientDBEmbedded.java:281)
	... 17 common frames omitted
```

## Steps to reproduce  

Open the attached database (it was created using 2.2.37 and I believe it was shutdown correctly)

**Comment by laa** [comment]
@jamieb22 EmptyWALRecord was introduced in 3.0.x we do not support downgrade of versions.

**Comment by laa** [comment]
Closed because of no answer.
