### ISSUE TITLE
Database does not boot up when using Docker

### ISSUE THREAD

**Issue by silvae86** [orientechnologies/orientdb#9046]
## Expected behavior  
Database should boot up.

## Actual behavior  
Database does not boot. Stack trace:

```
iMac:archgraph joaorocha$ docker-compose up
Recreating archgraph-orientdb ... done
Attaching to archgraph-orientdb
archgraph-orientdb |            .                                          
archgraph-orientdb |           .`        `                                 
archgraph-orientdb |           ,      `:.                                  
archgraph-orientdb |          `,`    ,:`                                   
archgraph-orientdb |          .,.   :,,                                    
archgraph-orientdb |          .,,  ,,,                                     
archgraph-orientdb |     .    .,.:::::  ````                                 :::::::::     :::::::::   
archgraph-orientdb |     ,`   .::,,,,::.,,,,,,`;;                      .:    ::::::::::    :::    :::  
archgraph-orientdb |     `,.  ::,,,,,,,:.,,.`  `                       .:    :::      :::  :::     ::: 
archgraph-orientdb |      ,,:,:,,,,,,,,::.   `        `         ``     .:    :::      :::  :::     ::: 
archgraph-orientdb |       ,,:.,,,,,,,,,: `::, ,,   ::,::`   : :,::`  ::::   :::      :::  :::    :::  
archgraph-orientdb |        ,:,,,,,,,,,,::,:   ,,  :.    :   ::    :   .:    :::      :::  :::::::     
archgraph-orientdb |         :,,,,,,,,,,:,::   ,,  :      :  :     :   .:    :::      :::  :::::::::   
archgraph-orientdb |   `     :,,,,,,,,,,:,::,  ,, .::::::::  :     :   .:    :::      :::  :::     ::: 
archgraph-orientdb |   `,...,,:,,,,,,,,,: .:,. ,, ,,         :     :   .:    :::      :::  :::     ::: 
archgraph-orientdb |     .,,,,::,,,,,,,:  `: , ,,  :     `   :     :   .:    :::      :::  :::     ::: 
archgraph-orientdb |       ...,::,,,,::.. `:  .,,  :,    :   :     :   .:    :::::::::::   :::     ::: 
archgraph-orientdb |            ,::::,,,. `:   ,,   :::::    :     :   .:    :::::::::     ::::::::::  
archgraph-orientdb |            ,,:` `,,.                                  
archgraph-orientdb |           ,,,    .,`                                  
archgraph-orientdb |          ,,.     `,                                              VELOCE  
archgraph-orientdb |        ``        `.                                                          
archgraph-orientdb |                  ``                                       www.orientdb.com
archgraph-orientdb |                  `                                    
archgraph-orientdb | 
archgraph-orientdb | 2019-10-18 22:51:03:154 INFO  Loading configuration from: /orientdb/config/orientdb-server-config.xml... [OServerConfigurationLoaderXml]
archgraph-orientdb | 2019-10-18 22:51:03:306 INFO  OrientDB Server v3.0.24 - Veloce (build 2ed52e4b2ebce991f3ac461032890e1e1a49d3a1, branch UNKNOWN) is starting up... [OServer]
archgraph-orientdb | 2019-10-18 22:51:03:356 INFO  2096263168 B/1999 MB/1 GB of physical memory were detected on machine [ONative]
archgraph-orientdb | 2019-10-18 22:51:03:357 INFO  Soft memory limit for this process is set to -1 B/-1 MB/-1 GB [ONative]
archgraph-orientdb | 2019-10-18 22:51:03:357 INFO  Hard memory limit for this process is set to -1 B/-1 MB/-1 GB [ONative]
archgraph-orientdb | 2019-10-18 22:51:03:358 INFO  Path to 'memory' cgroup is '/docker/2d29b4fc2c4c5e708e54511da333b7aaf1a98e50826038b249a97138c341b117' [ONative]
archgraph-orientdb | 2019-10-18 22:51:03:361 INFO  Mounting path for memory cgroup controller is '/sys/fs/memory' [ONative]
archgraph-orientdb | 2019-10-18 22:51:03:361 INFO  Can not find '/sys/fs/memory/docker/2d29b4fc2c4c5e708e54511da333b7aaf1a98e50826038b249a97138c341b117' path for memory cgroup, it is supposed that process is running in container, will try to read root '/sys/fs/memory' memory cgroup data [ONative]
archgraph-orientdb | 2019-10-18 22:51:03:362 INFO  Can not read memory soft limit for cgroup '/sys/fs/memory' [ONative]
archgraph-orientdb | 2019-10-18 22:51:03:362 INFO  Can not read memory hard limit for cgroup '/sys/fs/memory' [ONative]
archgraph-orientdb | 2019-10-18 22:51:03:363 INFO  Detected memory limit for current process is 2096263168 B/1999 MB/1 GB [ONative]
archgraph-orientdb | 2019-10-18 22:51:03:364 INFO  JVM can use maximum 1963MB of heap memory [OMemoryAndLocalPaginatedEnginesInitializer]
archgraph-orientdb | 2019-10-18 22:51:03:364 INFO  Because OrientDB is running inside a container 12% of memory will be left unallocated according to the setting 'memory.leftToContainer' not taking into account heap memory [OMemoryAndLocalPaginatedEnginesInitializer]
archgraph-orientdb | 2019-10-18 22:51:03:366 WARNI Not enough physical memory available for DISKCACHE: 1,999MB (heap=1,963MB). Set lower Maximum Heap (-Xmx setting on JVM) and restart OrientDB. Now running with DISKCACHE=256MB [orientechnologies]
archgraph-orientdb | 2019-10-18 22:51:03:367 INFO  OrientDB config DISKCACHE=256MB (heap=1,963MB os=1,999MB) [orientechnologies]
archgraph-orientdb | 2019-10-18 22:51:03:370 WARNI The sum of the configured JVM maximum heap size (2058354688 bytes) and the OrientDB maximum cache size (268435456 bytes) is larger than the available physical memory size (com.orientechnologies.common.jna.ONative$MemoryLimitResult@144169b4 bytes). That may cause out of memory errors, please tune the configuration up. Use the -Xmx JVM option to lower the JVM maximum heap memory size or storage.diskCache.bufferSize OrientDB option to lower memory requirements of the cache. [OMemory]
archgraph-orientdb | 2019-10-18 22:51:03:370 INFO  System is started under an effective user : `root` [OEngineLocalPaginated]
archgraph-orientdb | 2019-10-18 22:51:03:371 INFO  Allocation of 3891 pages. [OEngineLocalPaginated]
archgraph-orientdb | 2019-10-18 22:51:03:441 INFO  WAL maximum segment size is set to 3,577 MB [OrientDBDistributed]
archgraph-orientdb | 2019-10-18 22:51:03:442 INFO  Databases directory: /orientdb/databases [OServer]
archgraph-orientdb | 2019-10-18 22:51:03:509 INFO  Direct IO for WAL located in /orientdb/databases/OSystem is allowed with block size 4096 bytes. [OCASDiskWriteAheadLog]
archgraph-orientdb | 2019-10-18 22:51:03:510 INFO  Page size for WAL located in /orientdb/databases/OSystem is set to 4096 bytes. [OCASDiskWriteAheadLog]Can not open file using Linux API, Java FileChannel will be used instead
archgraph-orientdb | com.sun.jna.LastErrorException: [22] Invalid argument
archgraph-orientdb |    at com.sun.jna.Native.invokeInt(Native Method)
archgraph-orientdb |    at com.sun.jna.Function.invoke(Function.java:419)
archgraph-orientdb |    at com.sun.jna.Function.invoke(Function.java:354)
archgraph-orientdb |    at com.sun.jna.Library$Handler.invoke(Library.java:244)
archgraph-orientdb |    at com.sun.proxy.$Proxy2.open(Unknown Source)
archgraph-orientdb |    at com.orientechnologies.common.jna.ONative.open(ONative.java:234)
archgraph-orientdb |    at com.orientechnologies.orient.core.storage.impl.local.paginated.wal.cas.OWALFile.createWriteWALFile(OWALFile.java:29)
archgraph-orientdb |    at com.orientechnologies.orient.core.storage.impl.local.paginated.wal.cas.OCASDiskWriteAheadLog$RecordsWriter.run(OCASDiskWriteAheadLog.java:1875)
archgraph-orientdb |    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
archgraph-orientdb |    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
archgraph-orientdb |    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
archgraph-orientdb |    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
archgraph-orientdb |    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
archgraph-orientdb |    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
archgraph-orientdb |    at java.lang.Thread.run(Thread.java:748)
archgraph-orientdb | 
archgraph-orientdb | 2019-10-18 22:51:03:912 INFO  Storage 'plocal:/orientdb/databases/OSystem' is opened under OrientDB distribution : 3.0.24 - Veloce (build 2ed52e4b2ebce991f3ac461032890e1e1a49d3a1, branch UNKNOWN) [OLocalPaginatedStorage]
archgraph-orientdb | 2019-10-18 22:51:04:113 SEVER ODefaultServerSecurity.loadConfig() Could not access the security JSON file: /orientdb/config/security.json [ODefaultServerSecurity]
archgraph-orientdb | 2019-10-18 22:51:04:145 INFO  Listening binary connections on 127.0.0.1:2424 (protocol v.37, socket=default) [OServerNetworkListener]
archgraph-orientdb | 2019-10-18 22:51:04:151 INFO  Installing dynamic plugin 'orientdb-etl-3.0.24.jar'... [OServerPluginManager]Error on installing dynamic plugin 'etl'
archgraph-orientdb | java.lang.reflect.InvocationTargetException
archgraph-orientdb |    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
archgraph-orientdb |    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
archgraph-orientdb |    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
archgraph-orientdb |    at java.lang.reflect.Method.invoke(Method.java:498)
archgraph-orientdb |    at com.orientechnologies.orient.server.plugin.OServerPluginManager.startPluginClass(OServerPluginManager.java:277)
archgraph-orientdb |    at com.orientechnologies.orient.server.plugin.OServerPluginManager.installDynamicPlugin(OServerPluginManager.java:359)
archgraph-orientdb |    at com.orientechnologies.orient.server.plugin.OServerPluginManager.updatePlugin(OServerPluginManager.java:201)
archgraph-orientdb |    at com.orientechnologies.orient.server.plugin.OServerPluginManager.updatePlugins(OServerPluginManager.java:299)
archgraph-orientdb |    at com.orientechnologies.orient.server.plugin.OServerPluginManager.startup(OServerPluginManager.java:94)
archgraph-orientdb |    at com.orientechnologies.orient.server.OServer.registerPlugins(OServer.java:1139)
archgraph-orientdb |    at com.orientechnologies.orient.server.OServer.activate(OServer.java:469)
archgraph-orientdb |    at com.orientechnologies.orient.server.OServerMain$1.run(OServerMain.java:48)
archgraph-orientdb | Caused by: com.orientechnologies.orient.core.exception.OConfigurationException: HTTP listener not found
archgraph-orientdb |    at com.orientechnologies.orient.etl.OETLPlugin.startup(OETLPlugin.java:79)
archgraph-orientdb |    ... 12 more
archgraph-orientdb | 
archgraph-orientdb | 2019-10-18 22:51:04:159 INFO  Installing dynamic plugin 'orientdb-studio-3.0.24.zip'... [OServerPluginManager]Error on installing dynamic plugin 'studio'
archgraph-orientdb | com.orientechnologies.orient.core.exception.OConfigurationException: HTTP listener not registered while installing Static Content command
archgraph-orientdb |    at com.orientechnologies.orient.server.plugin.OServerPluginManager.registerStaticDirectory(OServerPluginManager.java:214)
archgraph-orientdb |    at com.orientechnologies.orient.server.plugin.OServerPluginManager.installDynamicPlugin(OServerPluginManager.java:373)
archgraph-orientdb |    at com.orientechnologies.orient.server.plugin.OServerPluginManager.updatePlugin(OServerPluginManager.java:201)
archgraph-orientdb |    at com.orientechnologies.orient.server.plugin.OServerPluginManager.updatePlugins(OServerPluginManager.java:299)
archgraph-orientdb |    at com.orientechnologies.orient.server.plugin.OServerPluginManager.startup(OServerPluginManager.java:94)
archgraph-orientdb |    at com.orientechnologies.orient.server.OServer.registerPlugins(OServer.java:1139)
archgraph-orientdb |    at com.orientechnologies.orient.server.OServer.activate(OServer.java:469)
archgraph-orientdb |    at com.orientechnologies.orient.server.OServerMain$1.run(OServerMain.java:48)
archgraph-orientdb | 
archgraph-orientdb | 2019-10-18 22:51:04:161 WARNI onAfterDynamicPlugins() Configuration document is empty [ODefaultServerSecurity]
archgraph-orientdb | 2019-10-18 22:51:04:162 INFO  OrientDB Studio available at http://localhost:2480/studio/index.html [OServer]
```

## Steps to reproduce  

Create a docker-compose like this:

```yaml
version: '3.3'

services:
  orientdb:
    container_name: archgraph-orientdb
    image: orientdb:3.0.24
    ports:
      - "2424:2424"
      - "2480:2480"
    environment:
      - ORIENTDB_ROOT_PASSWORD=rootpwd
    volumes:
      - ./volumes/orientdb/config:/orientdb/config
      - ./volumes/orientdb/databases:/orientdb/databases
      - ./volumes/orientdb/backups:/orientdb/backup
    networks:
      - archgraph-docker-deployment
    restart: on-failure
networks:
  archgraph-docker-deployment: {}
```

And run `docker-compose up`

## Alternative scenario

Also, if you comment out the volumes, the database will boot. However, when you try to create a database via the Java API:

```groovy
	OrientGraphFactory graphFactory

	public static final String DATABASE_URI = "remote:127.0.0.1/archgraph"
	public static final String SERVER_USERNAME = "root"
	public static final String SERVER_PASSWORD = "rootpwd"

	static OrientGraphFactory databaseFactory() {
		// change to 'remote:host/dbname' if persistent storage needed
		def factory = new OrientGraphFactory(DATABASE_URI,SERVER_USERNAME, SERVER_PASSWORD).setupPool(1, 20)
		factory.getDatabase(true, true)
		factory
	}
```

 you will get an error saying that the database does not exist at a path, for example:

```shell
Caused by: com.orientechnologies.orient.core.exception.OStorageException: Cannot open the storage 'archgraph' because it does not exist in path: /orientdb/databases/archgraph
```

You need to log into the OrientDB studio and create the database manually. At first I thought it would be the user id running the orientDB process inside the docker container that would be causing some permissions error, but that is not the case because manual database creation (via Studio Web UI) works fine. 

I do not want to rely on manual database creation, because our use case relies on automated deployment.

**Comment by silvae86** [comment]
Update: Same behaviour in macOS Catalina.

**Comment by silvae86** [comment]
Another Update: same behaviour in Ubuntu Linux. Just starting the container using the command in the docker hub page: 

`docker run --name orientdb -p 2424:2424 -p 2480:2480 -e ORIENTDB_ROOT_PASSWORD=rootpwd orientdb`

and trying to log in....yields....:

```
com.orientechnologies.orient.core.exception.OStorageException: Cannot open the storage 'undefined' because it does not exist in path: /orientdb/databases/undefined
```

**Comment by silvae86** [comment]
I got it working but without named volumes. Another trick is to create the database explicitly via API if it does not exist.

My current docker-compose: 

```docker
version: '3'
services:
  orientdb3:
    image: orientdb:3.0.24
    networks:
    - default
    environment:
      ORIENTDB_ROOT_PASSWORD: "rootpwd"
      ORIENTDB_NODE_NAME: "odb1"
      ORIENTDB_OPTS_MEMORY: "-Xms4G -Xmx4G"
    ports:
      - 2480:2480
      - 2424:2424
    volumes:
      # - ./volumes/orientdb/config:/orientdb/config
      # - ./volumes/orientdb/databases:/orientdb/databases
      - ./volumes/orientdb/backups:/orientdb/backup
    logging:
      driver: json-file
      options:
        max-size: "200k"
        max-file: "10"
    restart: on-failure
```

Database initialization code in Groovy:

package db

import com.orientechnologies.orient.core.db.ODatabaseType
import com.orientechnologies.orient.core.db.OrientDB
import com.orientechnologies.orient.core.db.OrientDBConfig
import org.apache.tinkerpop.gremlin.orientdb.OrientGraphFactory
import groovy.transform.CompileStatic

@CompileStatic
class DBConnection {
	OrientGraphFactory graphFactory
	static databaseExists = false;

	public static final String DATABASE_NAME = "archgraph"
	public static final String DATABASE_HOST = "127.0.0.1"
	public static final String DATABASE_URI = "remote:"+DATABASE_HOST+ "/" + DATABASE_NAME
	public static final String SERVER_USERNAME = "root"
	public static final String SERVER_PASSWORD = "rootpwd"

	static OrientGraphFactory databaseFactory() {
		if(!databaseExists)
		{
			// create database if not exists
			OrientDB orientDB = new OrientDB("remote:localhost",SERVER_USERNAME, SERVER_PASSWORD, OrientDBConfig.defaultConfig());
			orientDB.createIfNotExists(DATABASE_NAME, ODatabaseType.PLOCAL);
			orientDB.close();
			databaseExists = true;
		}

		// change to 'remote:host/dbname' if persistent storage needed
		def factory = new OrientGraphFactory(DATABASE_URI,SERVER_USERNAME, SERVER_PASSWORD).setupPool(1, 20)
		factory.getDatabase(true, false)
		factory
	}

	static OrientGraphFactory memoryFactory(){
		OrientGraphFactory factory = new OrientGraphFactory("memory:tinkerpop")
		factory
	}
}
