### ISSUE TITLE
OrientDb throws java.lang.IllegalStateException: Invalid content found while iterating edges.

### ISSUE THREAD

**Issue by nischalkumar** [orientechnologies/orientdb#9055]
## Expected behavior
Gremlin-core: 3.4.4
On running this query   
List<Map<String, Object> response  = graph.traversal().V()
                .hasLabel("AwsEBSVolume")
                .as("AwsEBSVolume")
                .has("attr1", P.within("1"))
                .out("AwsEBSVolume"+ "_" + "Tag").as("a")
                .select("AwsEBSVolume", "a").toList()
Expected behaviour is non null response.
## Actual behavior  
threw exception
java.lang.IllegalStateException: Invalid content found while iterating edges, value 'AwsEBSVolume_Tag#241:706{out:#33:100,in:#44:5766,is_child:true} v1' is not an edge
    at com.orientechnologies.orient.core.record.impl.OEdgeIterator.createGraphElement(OEdgeIterator.java:107) ~[orientdb-core-3.0.22.jar!/:3.0.22]
    at com.orientechnologies.orient.core.record.impl.OEdgeIterator.createGraphElement(OEdgeIterator.java:36) ~[orientdb-core-3.0.22.jar!/:3.0.22]
    at com.orientechnologies.orient.core.iterator.OLazyWrapperIterator.hasNext(OLazyWrapperIterator.java:93) ~[orientdb-core-3.0.22.jar!/:3.0.22]
    at com.orientechnologies.common.collection.OMultiCollectionIterator.getNextPartial(OMultiCollectionIterator.java:259) ~[orientdb-core-3.0.22.jar!/:3.0.22]
    at com.orientechnologies.common.collection.OMultiCollectionIterator.hasNextInternal(OMultiCollectionIterator.java:88) ~[orientdb-core-3.0.22.jar!/:3.0.22]
    at com.orientechnologies.common.collection.OMultiCollectionIterator.hasNext(OMultiCollectionIterator.java:78) ~[orientdb-core-3.0.22.jar!/:3.0.22]
    at com.orientechnologies.orient.core.record.impl.OEdgeToVertexIterator.hasNext(OEdgeToVertexIterator.java:25) ~[orientdb-core-3.0.22.jar!/:3.0.22]
    at java.util.Spliterators$IteratorSpliterator.tryAdvance(Spliterators.java:1811) ~[na:1.8.0_222]
    at java.util.stream.StreamSpliterators$WrappingSpliterator.lambda$initPartialTraversalState$0(StreamSpliterators.java:295) ~[na:1.8.0_222]
    at java.util.stream.StreamSpliterators$AbstractWrappingSpliterator.fillBuffer(StreamSpliterators.java:207) ~[na:1.8.0_222]
    at java.util.stream.StreamSpliterators$AbstractWrappingSpliterator.doAdvance(StreamSpliterators.java:162) ~[na:1.8.0_222]
    at java.util.stream.StreamSpliterators$WrappingSpliterator.tryAdvance(StreamSpliterators.java:301) ~[na:1.8.0_222]
    at java.util.Spliterators$1Adapter.hasNext(Spliterators.java:681) ~[na:1.8.0_222]
    at org.apache.tinkerpop.gremlin.process.traversal.step.map.FlatMapStep.processNextStart(FlatMapStep.java:44) ~[gremlin-core-3.4.4.jar!/:3.4.4]
    at org.apache.tinkerpop.gremlin.process.traversal.step.util.AbstractStep.hasNext(AbstractStep.java:143) ~[gremlin-core-3.4.4.jar!/:3.4.4]
    at org.apache.tinkerpop.gremlin.process.traversal.step.util.ExpandableStepIterator.next(ExpandableStepIterator.java:50) ~[gremlin-core-3.4.4.jar!/:3.4.4]
    at org.apache.tinkerpop.gremlin.process.traversal.step.map.MapStep.processNextStart(MapStep.java:36) ~[gremlin-core-3.4.4.jar!/:3.4.4]
    at org.apache.tinkerpop.gremlin.process.traversal.step.map.SelectStep.processNextStart(SelectStep.java:156) ~[gremlin-core-3.4.4.jar!/:3.4.4]
    at org.apache.tinkerpop.gremlin.process.traversal.step.util.AbstractStep.next(AbstractStep.java:128) ~[gremlin-core-3.4.4.jar!/:3.4.4]
    at org.apache.tinkerpop.gremlin.process.traversal.step.util.AbstractStep.next(AbstractStep.java:38) ~[gremlin-core-3.4.4.jar!/:3.4.4]
    at org.apache.tinkerpop.gremlin.process.traversal.Traversal.fill(Traversal.java:180) ~[gremlin-core-3.4.4.jar!/:3.4.4]
    at org.apache.tinkerpop.gremlin.process.traversal.Traversal.toList(Traversal.java:118) ~[gremlin-core-3.4.4.jar!/:3.4.4]

## Steps to reproduce  
 Can not reproduce it. This error went away with  a restart
<An SQL script to reproduce the problem or a JUnit test case will increase **A LOT** the chance to have a quick fix>

**Comment by nischalkumar** [comment]
is this because I am setting connection pool properties incorrectly?
