### ISSUE TITLE
extractor csv not foundetl import csv

### ISSUE THREAD

**Issue by aMayii** [orientechnologies/orientdb#9056]
## Expected behavior  
<add here>  

## Actual behavior  
I followed the official tutorial.But in the first step it went wrong. And I used an absolute path.
https://orientdb.com/docs/last/Import-the-Database-of-Beers.html
EXtractor 'csv' not found 
ETL Process
Import Beer Categories
csv
{
  "source": { "file": { "path": "/root/graphDB/orientDb/openbeer/openbeerdb_csv/categories.csv" } },
  "extractor": { "csv": {} },
  "transformers": [
    { "vertex": { "class": "Category" } }
  ],
  "loader": {
    "orientdb": {
       "dbURL": "plocal:../databases/openbeerdb",
       "dbType": "graph",
       "classes": [
         {"name": "Category", "extends": "V"}
       ], "indexes": [
         {"class":"Category", "fields":["id:integer"], "type":"UNIQUE" }
       ]
    }
  }
}
error info:
# /opt/orientdb/bin/oetl.sh ./catedories.json
OrientDB etl v.2.1.2 (build @BUILD@) www.orientdb.com
Exception in thread "main" com.orientechnologies.orient.core.exception.OConfigurationException: Error on loading config file: ./catedories.json
        at com.orientechnologies.orient.etl.OETLProcessor.main(OETLProcessor.java:149)

#

 /opt/orientdb/bin/oetl.sh /root/graphDB/orientDb/catedories.json
OrientDB etl v.2.1.2 (build @BUILD@) www.orientdb.com
Exception in thread "main" com.orientechnologies.orient.core.exception.OConfigurationException: Error on creating ETLprocessor
        at com.orientechnologies.orient.etl.OETLProcessor.parse(OETLProcessor.java:278)
        at com.orientechnologies.orient.etl.OETLProcessor.parse(OETLProcessor.java:186)
        at com.orientechnologies.orient.etl.OETLProcessor.main(OETLProcessor.java:161)
Caused by: java.lang.IllegalArgumentException: Extractor 'csv' not found
        at com.orientechnologies.orient.etl.OETLComponentFactory.getExtractor(OETLComponentFactory.java:134)
        at com.orientechnologies.orient.etl.OETLProcessor.parse(OETLProcessor.java:244)
        ... 2 more

**Comment by tglman** [comment]
Hi,

This is on a really old version of OrientDB not supported anymore, closing it.
