### ISSUE TITLE
com.orientechnologies.orient.core.sql.parser.TokenMgrError: Lexical error at line 2, column 120. 

### ISSUE THREAD

**Issue by schernolyas** [orientechnologies/orientdb#9065]
## Expected behavior  
get result of batch execution

## Actual behavior  
query is hanging.
I see stacktrace at server log:

Uncaught exception in thread OrientDB (/127.0.0.1:2424) <- BinaryClient (/127.0.0.1:50762)
com.orientechnologies.orient.core.sql.parser.TokenMgrError: Lexical error at line 2, column 120.  Encountered: <EOF> after : "\"London\'; let e = create edge Lives from $account to $city; commit;return $a;"
	at com.orientechnologies.orient.core.sql.parser.OrientSqlTokenManager.getNextToken(OrientSqlTokenManager.java:6590)
	at com.orientechnologies.orient.core.sql.parser.OrientSql.jj_scan_token(OrientSql.java:31411)
	at com.orientechnologies.orient.core.sql.parser.OrientSql.jj_3R_560(OrientSql.java:24037)
...
	at com.orientechnologies.orient.core.sql.parser.OrientSql.parseScript(OrientSql.java:284)
	at com.orientechnologies.orient.core.sql.OSQLEngine.parseScript(OSQLEngine.java:82)
	at com.orientechnologies.orient.core.sql.OSQLEngine.parseScript(OSQLEngine.java:76)
	at com.orientechnologies.orient.core.command.OSqlScriptExecutor.execute(OSqlScriptExecutor.java:28)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentEmbedded.execute(ODatabaseDocumentEmbedded.java:617)
	at com.orientechnologies.orient.server.OConnectionBinaryExecutor.executeQuery(OConnectionBinaryExecutor.java:1299)
	at com.orientechnologies.orient.client.remote.message.OQueryRequest.execute(OQueryRequest.java:136)

## Steps to reproduce  
`public static void main(String[] args) {
    OrientDB orientDBEnv = new OrientDB("remote:localhost", "admin", "admin", OrientDBConfig.defaultConfig());
    ODatabasePool orientDBPool = new ODatabasePool(orientDBEnv, "graph", "admin", "admin");

    try (ODatabaseSession databaseSession = orientDBPool.acquire()) {
      String script = "begin;"
          + " let account=create vertex Account set name = \"Luke\";"
          + " let city = select from City where name = \"London\';"
          + " let e = create edge Lives from $account to $city;"
          + " commit;"
          + "return $a";
      try (OResultSet resultSet = databaseSession.execute("sql", script)) {
        resultSet.forEachRemaining(new Consumer<OResult>() {
          @Override
          public void accept(OResult oResult) {
            System.out.println(oResult.toJSON());
          }
        });
      }
    }
    orientDBPool.close();
    orientDBEnv.close();
  }`

**Comment by luigidellaquila** [comment]
Hi @schernolyas 

I didn't test it, but I think the problem is here

```
" let city = select from City where name = \"London\';"
```

See the double quote before London and the single quote after it ;-)

Thanks

Luigi

**Comment by schernolyas** [comment]
Hi @luigidellaquila !
I have corrected my batch script to:
`String script = "begin;"
          + " let account=create vertex Account set name = \"Luke\";"
          + " let city = select from City where name = \"London\";"
          + " let e = create edge Lives from $account to $city;"
          + " commit;"
          + "return $e";`
It is works.  
Thank you very much !
