### ISSUE TITLE
No enum constant com.orientechnologies.orient.core.metadata.schema.OType.NUMBER

### ISSUE THREAD

**Issue by kkaustubhvyas** [orientechnologies/orientdb#9070]
### orientjs version ^2.2.1
Using OrientDB docker image latest 

## Expected behavior  
Migrations are supposed to run smoothly

## Actual behavior  
Database and tables get created but fails at some step giving following error:

`{ OrientDB.RequestError: No enum constant com.orientechnologies.orient.core.metadata.schema.OType.NUMBER
    at child.Operation.parseError (/home/kaustubh/Development/test-project/node_modules/orientjs/lib/transport/binary/protocol33/operation.js:905:13)
    at child.Operation.consume (/home/kaustubh/Development/test-project/node_modules/orientjs/lib/transport/binary/protocol33/operation.js:496:35)
    at Connection.process (/home/kaustubh/Development/test-project/node_modules/orientjs/lib/transport/binary/connection.js:459:17)
    at Connection.handleSocketData (/home/kaustubh/Development/test-project/node_modules/orientjs/lib/transport/binary/connection.js:331:20)
    at Socket.emit (events.js:198:13)
    at Socket.EventEmitter.emit (domain.js:448:20)
    at addChunk (_stream_readable.js:288:12)
    at readableAddChunk (_stream_readable.js:269:11)
    at Socket.Readable.push (_stream_readable.js:224:10)
    at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
  name: 'OrientDB.RequestError',
  message:
   'No enum constant com.orientechnologies.orient.core.metadata.schema.OType.NUMBER',
  data: {},
  previous: [],
  id: 1,
  type: 'java.lang.IllegalArgumentException',
  hasMore: 0 }`

**Comment by kkaustubhvyas** [comment]
sorry, supposed to post in ORM repository
