### ISSUE TITLE
Null Pointer Exception when  using class names with a '.' in them (e.g. SELECT COUNT(*) from `Class.Name`;)

### ISSUE THREAD

**Issue by pontusvision** [orientechnologies/orientdb#9097]
## Expected behavior  
Return the count of documents in a class

## Actual behavior  
```
 java.lang.NullPointerException    
at com.orientechnologies.orient.core.sql.executor.OSelectExecutionPlanner.securityPoliciesExistForClass(OSelectExecutionPlanner.java:525)  
at com.orientechnologies.orient.core.sql.executor.OSelectExecutionPlanner.handleHardwiredCountOnClass(OSelectExecutionPlanner.java:514)    
at com.orientechnologies.orient.core.sql.executor.OSelectExecutionPlanner.handleHardwiredOptimizations(OSelectExecutionPlanner.java:490)   
at com.orientechnologies.orient.core.sql.executor.OSelectExecutionPlanner.createExecutionPlan(OSelectExecutionPlanner.java:81)             
at com.orientechnologies.orient.core.sql.parser.OSelectStatement.createExecutionPlan(OSelectStatement.java:297)                            
at com.orientechnologies.orient.core.sql.parser.OSelectStatement.execute(OSelectStatement.java:286)                                        
at com.orientechnologies.orient.core.sql.parser.OStatement.execute(OStatement.java:87)                                                     
at com.orientechnologies.orient.core.db.document.ODatabaseDocumentEmbedded.command(ODatabaseDocumentEmbedded.java:572)                     
at org.apache.tinkerpop.gremlin.orientdb.OrientGraph.lambda$executeSql$2(OrientGraph.java:266)                                             
at org.apache.tinkerpop.gremlin.orientdb.OrientGraph.executeWithConnectionCheck(OrientGraph.java:205)                                      
at org.apache.tinkerpop.gremlin.orientdb.OrientGraph.executeSql(OrientGraph.java:264)                                                      
at org.apache.tinkerpop.gremlin.orientdb.OrientStandardGraph.executeSql(OrientStandardGraph.java:184)
                                      
at org.apache.tinkerpop.gremlin.orientdb.OGraph$executeSql$1.call(Unknown Source)

```

## Steps to reproduce  

1) create a class with a . in the name (e.g. Events.Consent)
```
CREATE CLASS `Events.Consent` EXTENDS V;
SELECT COUNT(*) from `Events.Consent`;
```

## Proposed Solution:

Change the following in the OSelectExecutionPlanner.securityPoliciesExistForClass() function:
```
  private boolean securityPoliciesExistForClass(OIdentifier targetClass, OCommandContext ctx) {
    ODatabaseInternal db = (ODatabaseInternal) ctx.getDatabase();
    OSecurityInternal security = db.getSharedContext().getSecurity();
    OClass clazz = db.getClass(targetClass.getStringValue()); // normalize class name case
    // LPPM - clazz.getName() is getting rid of the `quotes`, causing issues where class names have dots in them.
    // targetClass.toString(), in contrast, preserves the `quotes`.
    // return security.isReadRestrictedBySecurityPolicy((ODatabaseSession) db, "database.class." + clazz.getName());
    return security.isReadRestrictedBySecurityPolicy((ODatabaseSession) db, "database.class." + targetClass.toString());
  }
```

**Comment by luigidellaquila** [comment]
Hi @pontusvision 

This is already fixed in the snapshot, I just double-checked and it works fine

Thanks

Luigi
