### ISSUE TITLE
(OObjectDatabase)Map Link type with Set or List Value throwing Exception [moved]

### ISSUE THREAD

**Issue by lvca** [orientechnologies/orientdb#910]
This is [Issue 910](http://code.google.com/p/orient/issues/detail?id=910) moved from a Google Code project.
Added by 2012-06-25T20:38:01.000Z by [itechnol...@gmail.com](http://code.google.com/u/115149179340969656099/).
Please review that bug for more context and additional comments, but update this bug.

Original labels: Type-Defect, Priority-Medium, v2.0

### Original description

    orientdb-1.1.0-SNAPSHOT
    using trunk 5871
    build.number=12090
    
    Using OObjectDatabase
    
    I am trying to add a Role to for 1 of my users with the following method. My user can have more than 1 role and i can have many users that have access to this account. The roles are stored in
     Map<User, Set<Role> userRoles
    
    public void addUserRole(AbstractUser user, Role role) {
          
            Set<Role> persistantRoles;
    
            if (userRoles.containsKey(user)) {
                persistantRoles = userRoles.get(user);
            } else
                persistantRoles = new HashSet<Role>();
    
            persistantRoles.add(role);
            userRoles.put(user, persistantRoles);
    
        }
    
    When i try the following
    
    AbstractUser elizabeth = new TestUser();
            elizabeth.setFirstName(&quot;Elizabeth&quot;);
            elizabeth.setLastName(&quot;Collins&quot;);
            elizabeth.setUserName(&quot;abc@domain.co.nz&quot;);
            elizabeth.setPassword(TestUser.encryptPassword(&quot;password123&quot;));
           
           
           
            AbstractAccount lumberbank = new TestAccount();
            lumberbank.addUser(elizabeth);
            lumberbank.addUserRole(elizabeth, new Role(&quot;Super User&quot;));
            database.save(lumberbank);
    
    I get this exception also seem to get if when using Map<User, List<Role>>:
    
    com.orientechnologies.orient.core.exception.OSerializationException: Error serializing object of class class com.zero2go.domainPojos.TestAccount
        at com.orientechnologies.orient.object.enhancement.OObjectEntitySerializer.serializeObject(OObjectEntitySerializer.java:107)
        at com.orientechnologies.orient.object.db.OObjectDatabaseTx.save(OObjectDatabaseTx.java:299)
        at com.orientechnologies.orient.object.db.OObjectDatabaseTx.save(OObjectDatabaseTx.java:245)
        at com.zero2go.tests.ObjectDBTest.addUser(ObjectDBTest.java:127)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:601)
        at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:44)
        at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
        at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:41)
        at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20)
        at org.junit.runners.BlockJUnit4ClassRunner.runNotIgnored(BlockJUnit4ClassRunner.java:79)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:71)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:49)
        at org.junit.runners.ParentRunner$3.run(ParentRunner.java:193)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:52)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:191)
        at org.junit.runners.ParentRunner.access$000(ParentRunner.java:42)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:184)
        at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:28)
        at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:31)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:236)
        at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
        at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
        at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)
        at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
        at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
        at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)
    Caused by: java.lang.IllegalArgumentException: Type LINK must be a multi value type (collection or map)
        at com.orientechnologies.orient.object.enhancement.OObjectEntitySerializer.multiValueToStream(OObjectEntitySerializer.java:867)
        at com.orientechnologies.orient.object.enhancement.OObjectEntitySerializer.typeToStream(OObjectEntitySerializer.java:412)
        at com.orientechnologies.orient.object.enhancement.OObjectEntitySerializer.multiValueToStream(OObjectEntitySerializer.java:888)
        at com.orientechnologies.orient.object.enhancement.OObjectEntitySerializer.typeToStream(OObjectEntitySerializer.java:415)
        at com.orientechnologies.orient.object.enhancement.OObjectEntitySerializer.toStream(OObjectEntitySerializer.java:719)
        at com.orientechnologies.orient.object.enhancement.OObjectEntitySerializer.serializeObject(OObjectEntitySerializer.java:105)
        ... 28 more

**Comment by lvca** [comment]
Fixed long time ago.
