### ISSUE TITLE
'Data center configuration is supported only in OrientDB Enterprise Edition' error when starting OrientDB in distributed mode

### ISSUE THREAD

**Issue by eduardnegru** [orientechnologies/orientdb#9103]
OrientDB Version: 3.0.23 (community edition)

Java Version: openjdk 11.0.5  

OS: Ubuntu 18.05

**Expected behavior**

Start a 3-node cluster in distributed mode using dserver.sh.

**Actual behavior** 

Error when starting server with dserver.sh.

According to the [documentation][1], there is a property, dataCenters, which is only available in the Enterprise edition of Orientdb. Please find below the default-distributed-db-config.json file, which does not contain the dataCenters property. However, OrientDB complains that dataCenters property is only avaiable in Enterprise mode.

**Stack trace**

```
2019-12-30 12:25:16:733 WARNI Storing configuration for property:'client.session.tokenBased' not existing in current version [OClusterBasedStorageConfiguration]Error during server execution
com.orientechnologies.orient.server.distributed.ODistributedStartupException: Error on starting distributed plugin
	at com.orientechnologies.orient.server.hazelcast.OHazelcastPlugin.startup(OHazelcastPlugin.java:345)
	at com.orientechnologies.orient.server.OServer.registerPlugins(OServer.java:1194)
	at com.orientechnologies.orient.server.OServer.activate(OServer.java:469)
	at com.orientechnologies.orient.server.OServerMain$1.run(OServerMain.java:48)
Caused by: com.orientechnologies.orient.core.exception.OConfigurationException: Data center configuration is supported only in OrientDB Enterprise Edition
	at com.orientechnologies.orient.server.distributed.impl.ODefaultDistributedStrategy.validateConfiguration(ODefaultDistributedStrategy.java:42)
	at com.orientechnologies.orient.server.hazelcast.OHazelcastPlugin.updateCachedDatabaseConfiguration(OHazelcastPlugin.java:842)
	at com.orientechnologies.orient.server.distributed.impl.ODistributedStorage.getDistributedConfiguration(ODistributedStorage.java:1562)
	at com.orientechnologies.orient.server.distributed.impl.ODistributedAbstractPlugin.getDatabaseConfiguration(ODistributedAbstractPlugin.java:481)
	at com.orientechnologies.orient.server.distributed.impl.ODistributedAbstractPlugin.getDatabaseConfiguration(ODistributedAbstractPlugin.java:472)
	at com.orientechnologies.orient.server.distributed.impl.ODistributedAbstractPlugin.executeInDistributedDatabaseLock(ODistributedAbstractPlugin.java:1761)
	at com.orientechnologies.orient.server.hazelcast.OHazelcastPlugin.loadLocalDatabases(OHazelcastPlugin.java:798)
	at com.orientechnologies.orient.server.hazelcast.OHazelcastPlugin.startup(OHazelcastPlugin.java:302)
	... 3 more
```

_default-distributed-db-config.json_

```
{
  "replication": true,
  "hotAlignment": true,
  "autoDeploy": true,
  "readQuorum": 1,
  "writeQuorum": "majority",
  "executionMode": "undefined",
  "readYourWrites": true,
  "newNodeStrategy": "static",
  "servers": {
    "node1": "master",
    "node2": "master",
    "node3": "replica"
  },
  "clusters": {
    "internal": {
    },
    "*": {
      "servers": ["<NEW_NODE>"]
    }
  }
}
```

  [1]: https://orientdb.org/docs/3.0.x/distributed/Distributed-Configuration.html

**Comment by eduardnegru** [comment]
Deployment was done via this ansible script[1]. Installed orientdb manually on the server and it worked.

[1] https://github.com/migibert/orientdb-role
