### ISSUE TITLE
OpenJDK 11 or higher support

### ISSUE THREAD

**Issue by srbala** [orientechnologies/orientdb#9106]
## Expected behavior  
No exception 

## Actual behavior  
Exception due to use of sun.misc.* package

## Steps to reproduce  
https://github.com/jbake-org/jbake/issues/617
https://github.com/jmcgarr/jmcgarr.github.io/issues/3

JDK 11 and higer removal of sun.misc.* package

**Comment by tglman** [comment]
Hi,

The 3.1.x should already support jdk 11

Regards

**Comment by laa** [comment]
We are running ODB on JDK 11. No issues as for now.

**Comment by domidodo** [comment]
This bug has come back in the current versions.
The latest Version i can use is `3.2.10`.

I can go higher with an existing database. But I wouldn't be able to initialize any more.

I am using:
```
openjdk 11.0.24 2024-07-16 LTS
OpenJDK Runtime Environment Zulu11.74+15-CA (build 11.0.24+8-LTS)
OpenJDK 64-Bit Server VM Zulu11.74+15-CA (build 11.0.24+8-LTS, mixed mode)
```

And with the current version ( `3.2.35` ), I get the following error:
```
C:\Users\x.y\.jdks\openjdk-23.0.1\bin\java.exe -agentlib:jdwp=transport=dt_socket,address=127.0.0.1:55236,suspend=y,server=n -javaagent:C:\Users\x.y\AppData\Local\JetBrains\IntelliJIdea2024.2\captureAgent\debugger-agent.jar -Dkotlinx.coroutines.debug.enable.creation.stack.trace=false -Ddebugger.agent.enable.coroutines=true -Dfile.encoding=UTF-8 -Dsun.stdout.encoding=UTF-8 -Dsun.stderr.encoding=UTF-8 -classpath "C:\repos\com.demo\target\classes;C:\Users\x.y\.m2\repository\org\jcommander\jcommander\1.83\jcommander-1.83.jar;C:\Users\x.y\.m2\repository\com\orientechnologies\orientdb-graphdb\3.2.35\orientdb-graphdb-3.2.35.jar;C:\Users\x.y\.m2\repository\com\orientechnologies\orientdb-server\3.2.35\orientdb-server-3.2.35.jar;C:\Users\x.y\.m2\repository\org\glassfish\jaxb\jaxb-runtime\3.0.2\jaxb-runtime-3.0.2.jar;C:\Users\x.y\.m2\repository\com\sun\activation\jakarta.activation\2.0.1\jakarta.activation-2.0.1.jar;C:\Users\x.y\.m2\repository\org\bouncycastle\bcpkix-jdk18on\1.77\bcpkix-jdk18on-1.77.jar;C:\Users\x.y\.m2\repository\org\bouncycastle\bcprov-jdk18on\1.77\bcprov-jdk18on-1.77.jar;C:\Users\x.y\.m2\repository\org\bouncycastle\bcutil-jdk18on\1.77\bcutil-jdk18on-1.77.jar;C:\Users\x.y\.m2\repository\com\orientechnologies\orientdb-tools\3.2.35\orientdb-tools-3.2.35.jar;C:\Users\x.y\.m2\repository\jakarta\xml\bind\jakarta.xml.bind-api\3.0.1\jakarta.xml.bind-api-3.0.1.jar;C:\Users\x.y\.m2\repository\org\glassfish\jaxb\jaxb-core\3.0.2\jaxb-core-3.0.2.jar;C:\Users\x.y\.m2\repository\org\glassfish\jaxb\txw2\3.0.2\txw2-3.0.2.jar;C:\Users\x.y\.m2\repository\com\sun\istack\istack-commons-runtime\4.0.1\istack-commons-runtime-4.0.1.jar;C:\Users\x.y\.m2\repository\com\orientechnologies\orientdb-core\3.2.35\orientdb-core-3.2.35.jar;C:\Users\x.y\.m2\repository\com\github\jnr\jnr-posix\3.1.15\jnr-posix-3.1.15.jar;C:\Users\x.y\.m2\repository\com\github\jnr\jnr-ffi\2.2.11\jnr-ffi-2.2.11.jar;C:\Users\x.y\.m2\repository\com\github\jnr\jffi\1.3.9\jffi-1.3.9.jar;C:\Users\x.y\.m2\repository\com\github\jnr\jffi\1.3.9\jffi-1.3.9-native.jar;C:\Users\x.y\.m2\repository\org\ow2\asm\asm-commons\9.2\asm-commons-9.2.jar;C:\Users\x.y\.m2\repository\org\ow2\asm\asm-analysis\9.2\asm-analysis-9.2.jar;C:\Users\x.y\.m2\repository\org\ow2\asm\asm-tree\9.2\asm-tree-9.2.jar;C:\Users\x.y\.m2\repository\org\ow2\asm\asm-util\9.2\asm-util-9.2.jar;C:\Users\x.y\.m2\repository\com\github\jnr\jnr-a64asm\1.0.0\jnr-a64asm-1.0.0.jar;C:\Users\x.y\.m2\repository\com\github\jnr\jnr-x86asm\1.0.2\jnr-x86asm-1.0.2.jar;C:\Users\x.y\.m2\repository\com\github\jnr\jnr-constants\0.10.3\jnr-constants-0.10.3.jar;C:\Users\x.y\.m2\repository\com\googlecode\concurrentlinkedhashmap\concurrentlinkedhashmap-lru\1.4.2\concurrentlinkedhashmap-lru-1.4.2.jar;C:\Users\x.y\.m2\repository\org\lz4\lz4-java\1.8.0\lz4-java-1.8.0.jar;C:\Users\x.y\.m2\repository\commons-lang\commons-lang\2.6\commons-lang-2.6.jar;C:\Users\x.y\.m2\repository\javax\activation\javax.activation-api\1.2.0\javax.activation-api-1.2.0.jar;C:\Users\x.y\.m2\repository\com\fasterxml\jackson\core\jackson-core\2.15.2\jackson-core-2.15.2.jar;C:\Users\x.y\.m2\repository\org\graalvm\sdk\graal-sdk\21.3.5\graal-sdk-21.3.5.jar;C:\Users\x.y\.m2\repository\org\graalvm\truffle\truffle-api\21.3.5\truffle-api-21.3.5.jar;C:\Users\x.y\.m2\repository\org\graalvm\js\js\21.3.5\js-21.3.5.jar;C:\Users\x.y\.m2\repository\org\graalvm\regex\regex\21.3.5\regex-21.3.5.jar;C:\Users\x.y\.m2\repository\com\ibm\icu\icu4j\71.1\icu4j-71.1.jar;C:\Users\x.y\.m2\repository\org\graalvm\js\js-scriptengine\21.3.5\js-scriptengine-21.3.5.jar;C:\Users\x.y\.m2\repository\org\graalvm\tools\profiler\21.3.5\profiler-21.3.5.jar;C:\Users\x.y\.m2\repository\org\graalvm\tools\chromeinspector\21.3.5\chromeinspector-21.3.5.jar;C:\Users\x.y\.m2\repository\com\tinkerpop\blueprints\blueprints-core\2.6.0\blueprints-core-2.6.0.jar;C:\Users\x.y\.m2\repository\org\codehaus\jettison\jettison\1.3.3\jettison-1.3.3.jar;C:\Users\x.y\.m2\repository\stax\stax-api\1.0.1\stax-api-1.0.1.jar;C:\Users\x.y\.m2\repository\com\carrotsearch\hppc\0.6.0\hppc-0.6.0.jar;C:\Users\x.y\.m2\repository\commons-configuration\commons-configuration\1.6\commons-configuration-1.6.jar;C:\Users\x.y\.m2\repository\commons-collections\commons-collections\3.2.1\commons-collections-3.2.1.jar;C:\Users\x.y\.m2\repository\commons-digester\commons-digester\1.8\commons-digester-1.8.jar;C:\Users\x.y\.m2\repository\commons-beanutils\commons-beanutils\1.7.0\commons-beanutils-1.7.0.jar;C:\Users\x.y\.m2\repository\commons-beanutils\commons-beanutils-core\1.8.0\commons-beanutils-core-1.8.0.jar;C:\Users\x.y\.m2\repository\commons-logging\commons-logging\1.1.1\commons-logging-1.1.1.jar;C:\Users\x.y\.m2\repository\org\codehaus\groovy\groovy\2.5.19\groovy-2.5.19.jar;C:\Users\x.y\.m2\repository\org\codehaus\groovy\groovy-jsr223\2.5.19\groovy-jsr223-2.5.19.jar;C:\Users\x.y\.m2\repository\com\fasterxml\jackson\core\jackson-databind\2.14.2\jackson-databind-2.14.2.jar;C:\Users\x.y\.m2\repository\com\fasterxml\jackson\core\jackson-annotations\2.14.2\jackson-annotations-2.14.2.jar;C:\Users\x.y\.m2\repository\com\orientechnologies\orientdb-client\3.2.35\orientdb-client-3.2.35.jar;C:\Users\x.y\.m2\repository\com\esotericsoftware\kryo\kryo5\5.6.2\kryo5-5.6.2.jar;C:\Users\x.y\.m2\repository\org\dizitart\nitrite\4.3.0\nitrite-4.3.0.jar;C:\Users\x.y\.m2\repository\org\slf4j\slf4j-api\2.0.13\slf4j-api-2.0.13.jar;C:\Users\x.y\.m2\repository\org\jasypt\jasypt\1.9.3\jasypt-1.9.3.jar;C:\Users\x.y\.m2\repository\commons-codec\commons-codec\1.17.0\commons-codec-1.17.0.jar;C:\Users\x.y\.m2\repository\org\dizitart\nitrite-mvstore-adapter\4.3.0\nitrite-mvstore-adapter-4.3.0.jar;C:\Users\x.y\.m2\repository\com\h2database\h2-mvstore\2.2.224\h2-mvstore-2.2.224.jar;C:\Users\x.y\.m2\repository\org\ow2\asm\asm\9.7\asm-9.7.jar;C:\Users\x.y\.m2\repository\org\apache\logging\log4j\log4j-api\2.24.1\log4j-api-2.24.1.jar;C:\Users\x.y\.m2\repository\org\apache\logging\log4j\log4j-core\2.24.1\log4j-core-2.24.1.jar;C:\Users\x.y\.m2\repository\org\apache\maven\maven-aether-provider\3.3.9\maven-aether-provider-3.3.9.jar;C:\Users\x.y\.m2\repository\org\apache\maven\maven-model\3.3.9\maven-model-3.3.9.jar;C:\Users\x.y\.m2\repository\org\apache\maven\maven-model-builder\3.3.9\maven-model-builder-3.3.9.jar;C:\Users\x.y\.m2\repository\org\codehaus\plexus\plexus-interpolation\1.21\plexus-interpolation-1.21.jar;C:\Users\x.y\.m2\repository\org\apache\maven\maven-artifact\3.3.9\maven-artifact-3.3.9.jar;C:\Users\x.y\.m2\repository\org\apache\maven\maven-builder-support\3.3.9\maven-builder-support-3.3.9.jar;C:\Users\x.y\.m2\repository\com\google\guava\guava\18.0\guava-18.0.jar;C:\Users\x.y\.m2\repository\org\apache\maven\maven-repository-metadata\3.3.9\maven-repository-metadata-3.3.9.jar;C:\Users\x.y\.m2\repository\org\eclipse\aether\aether-spi\1.0.2.v20150114\aether-spi-1.0.2.v20150114.jar;C:\Users\x.y\.m2\repository\org\eclipse\aether\aether-util\1.0.2.v20150114\aether-util-1.0.2.v20150114.jar;C:\Users\x.y\.m2\repository\org\eclipse\aether\aether-impl\1.0.2.v20150114\aether-impl-1.0.2.v20150114.jar;C:\Users\x.y\.m2\repository\org\codehaus\plexus\plexus-component-annotations\1.6\plexus-component-annotations-1.6.jar;C:\Users\x.y\.m2\repository\org\codehaus\plexus\plexus-utils\3.0.22\plexus-utils-3.0.22.jar;C:\Users\x.y\.m2\repository\org\apache\commons\commons-lang3\3.4\commons-lang3-3.4.jar;C:\Users\x.y\.m2\repository\org\eclipse\aether\aether-api\1.1.0\aether-api-1.1.0.jar;C:\Users\x.y\.m2\repository\org\eclipse\aether\aether-connector-basic\1.1.0\aether-connector-basic-1.1.0.jar;C:\Users\x.y\.m2\repository\org\eclipse\aether\aether-transport-file\1.1.0\aether-transport-file-1.1.0.jar;C:\Users\x.y\.m2\repository\org\eclipse\aether\aether-transport-http\1.1.0\aether-transport-http-1.1.0.jar;C:\Users\x.y\.m2\repository\org\apache\httpcomponents\httpclient\4.3.5\httpclient-4.3.5.jar;C:\Users\x.y\.m2\repository\org\apache\httpcomponents\httpcore\4.3.2\httpcore-4.3.2.jar;C:\Users\x.y\.m2\repository\org\slf4j\jcl-over-slf4j\1.6.2\jcl-over-slf4j-1.6.2.jar;C:\GIT\intellij\IntelliJ IDEA 2024.2.3\lib\idea_rt.jar" com.demo.Main init
Connected to the target VM, address: '127.0.0.1:55236', transport: 'socket'
Nov. 19, 2024 10:40:25 AM com.orientechnologies.common.log.OLogManager log
INFORMATION: Windows OS is detected, 262144 limit of open files will be set for the disk cache.

2024-11-19 10:40:26:485 INFO  OrientDB Server v3.2.35 (build ${buildNumber}, branch UNKNOWN) is starting up... [OServer]Exception in thread "main" java.lang.NoSuchMethodError: 'void sun.misc.Unsafe.ensureClassInitialized(java.lang.Class)'
	at com.oracle.truffle.api.library.LibraryFactory.ensureLibraryInitialized(LibraryFactory.java:384)
	at com.oracle.truffle.api.library.LibraryFactory.getUncached(LibraryFactory.java:364)
	at com.oracle.truffle.api.library.LibraryFactory.<init>(LibraryFactory.java:210)
	at com.oracle.truffle.api.interop.InteropLibraryGen.<init>(InteropLibraryGen.java:170)
	at com.oracle.truffle.api.interop.InteropLibraryGen.<clinit>(InteropLibraryGen.java:161)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:578)
	at java.base/java.lang.Class.forName(Class.java:557)
	at com.oracle.truffle.api.library.LibraryFactory.loadGeneratedClass(LibraryFactory.java:771)
	at com.oracle.truffle.api.library.LibraryFactory.resolveImpl(LibraryFactory.java:734)
	at com.oracle.truffle.api.library.LibraryFactory.resolve(LibraryFactory.java:727)
	at com.oracle.truffle.api.interop.InteropLibrary.<clinit>(InteropLibrary.java:2878)
	at com.oracle.truffle.polyglot.PolyglotValueDispatch.<clinit>(PolyglotValueDispatch.java:156)
	at com.oracle.truffle.polyglot.PolyglotImpl.initialize(PolyglotImpl.java:147)
	at org.graalvm.polyglot.impl.AbstractPolyglotImpl.setConstructors(AbstractPolyglotImpl.java:238)
	at org.graalvm.polyglot.Engine$1.loadAndValidateProviders(Engine.java:845)
	at org.graalvm.polyglot.Engine$1.run(Engine.java:818)
	at org.graalvm.polyglot.Engine$1.run(Engine.java:792)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:319)
	at org.graalvm.polyglot.Engine.initEngineImpl(Engine.java:792)
	at org.graalvm.polyglot.Engine.access$000(Engine.java:110)
	at org.graalvm.polyglot.Engine$ImplHolder.<clinit>(Engine.java:136)
	at org.graalvm.polyglot.Engine.getImpl(Engine.java:324)
	at org.graalvm.polyglot.HostAccess$Builder.targetTypeMapping(HostAccess.java:1071)
	at com.oracle.truffle.js.scriptengine.GraalJSScriptEngine.createNashornHostAccess(GraalJSScriptEngine.java:104)
	at com.oracle.truffle.js.scriptengine.GraalJSScriptEngine.<clinit>(GraalJSScriptEngine.java:99)
	at com.oracle.truffle.js.scriptengine.GraalJSEngineFactory.getScriptEngine(GraalJSEngineFactory.java:196)
	at com.oracle.truffle.js.scriptengine.GraalJSEngineFactory.getScriptEngine(GraalJSEngineFactory.java:58)
	at java.scripting/javax.script.ScriptEngineManager.lambda$getEngineBy$2(ScriptEngineManager.java:237)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:215)
	at java.base/java.util.stream.StreamSpliterators$WrappingSpliterator.tryAdvance(StreamSpliterators.java:305)
	at java.base/java.util.stream.Streams$ConcatSpliterator.tryAdvance(Streams.java:723)
	at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:147)
	at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:588)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:574)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:560)
	at java.base/java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:150)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:265)
	at java.base/java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:687)
	at java.scripting/javax.script.ScriptEngineManager.getEngineBy(ScriptEngineManager.java:246)
	at java.scripting/javax.script.ScriptEngineManager.getEngineByName(ScriptEngineManager.java:185)
	at com.orientechnologies.orient.core.command.script.OScriptManager.<init>(OScriptManager.java:113)
	at com.orientechnologies.orient.core.db.OrientDBEmbedded.<init>(OrientDBEmbedded.java:105)
	at com.orientechnologies.orient.core.db.OrientDBInternal.embedded(OrientDBInternal.java:120)
	at com.orientechnologies.orient.server.OServer.startupFromConfiguration(OServer.java:388)
	at com.orientechnologies.orient.server.OServer.startup(OServer.java:320)
	at com.demo.Main.main(Main.java:37)

2024-11-19 10:40:26:899 INFO  OrientDB Server is shutting down... [OServer]Disconnected from the target VM, address: '127.0.0.1:55236', transport: 'socket'

Process finished with exit code 1
```

**Comment by tglman** [comment]
Hi,

Thanks for re-report this, we do run test against jdk 11 on the actions so should work, I know that the script engine is dynamic though depending on which jdk it may run polyglot or jsr223 script engine, so maybe there is a problem around that.

Reopening now for future checking
