### ISSUE TITLE
Orient DB Error on commit ClassCastException 

### ISSUE THREAD

**Issue by jamieb22** [orientechnologies/orientdb#9107]
### OrientDB Version
3.0.26

### Java Version
Java(TM) SE Runtime Environment (build 1.8.0_181-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.181-b13, mixed mode)

### OS
Linux insightcom 4.15.0-33-generic #36-Ubuntu SMP Wed Aug 15 16:00:05 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

## Expected behavior  

No error.

## Actual behavior  

2020-01-15 05:55:10 5.c.s.a.wk [ERROR] exception occurred getting message: {fecd35f41359cfefc114ab54f4362822} from database.
com.orientechnologies.orient.core.exception.OStorageException: Error on commit^M
        DB name="5240be8e-4617-4d20-9062-2f4bca0ff92e"
        at com.orientechnologies.orient.client.remote.OStorageRemote.baseNetworkOperation(OStorageRemote.java:361)
        at com.orientechnologies.orient.client.remote.OStorageRemote.networkOperationRetryTimeout(OStorageRemote.java:227)
        at com.orientechnologies.orient.client.remote.OStorageRemote.networkOperationNoRetry(OStorageRemote.java:257)
        at com.orientechnologies.orient.client.remote.OStorageRemote.commit(OStorageRemote.java:1032)
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentAbstract.internalCommit(ODatabaseDocumentAbstract.java:2721)
        at com.orientechnologies.orient.core.tx.OTransactionOptimistic.doCommit(OTransactionOptimistic.java:533)
        at com.orientechnologies.orient.core.tx.OTransactionOptimistic.commit(OTransactionOptimistic.java:103)
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentAbstract.commit(ODatabaseDocumentAbstract.java:2194)
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentAbstract.commit(ODatabaseDocumentAbstract.java:2164)
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.commit(ODatabaseDocumentTx.java:735)
        at com.tinkerpop.blueprints.impls.orient.OrientTransactionalGraph.commit(OrientTransactionalGraph.java:184)
       ....
Caused by: java.lang.ClassCastException: null

## Steps to reproduce  

Occurs in production.

**Comment by wolf4ood** [comment]
Hi @jamieb22 

do you have the server logs? Do you see some exceptions?

Thans

**Comment by jamieb22** [comment]
[orientdblogs.zip](https://github.com/orientechnologies/orientdb/files/4063756/orientdblogs.zip)

See attached. Please be aware we are running multiple databases in one server.

**Comment by jamieb22** [comment]
These databases were created with Orient DB V2.2.x. Most of them V2.2.37

**Comment by jamieb22** [comment]
My apologies. Just realize there are no stacks in the logs I sent you because log level is set to INFO, I will set Orient DB server logging to FINE level and will send you the log files.
