### ISSUE TITLE
ERROR OIndexManagerRemote: Error on loading of index by configuration

### ISSUE THREAD

**Issue by efenzha** [orientechnologies/orientdb#9109]
## Expected behavior  
No ERROR message

## Actual behavior  
OrientDB prints ERROR message.  

## Steps to reproduce  
1. connect to existing OrientDB database.
2. OrientDB prints this ERROR message for **all indexed fields**. These ERROR messages are printed every time client is connecting to the database. It seems the database is still working, and client still can get data by searching.

**Question:
What is the meaning of this ERROR? What shall I do to solve the problem behind this ERROR?**

_20/01/17 08:35:26 ERROR OIndexManagerRemote: Error on loading of index by configuration: {type:UNIQUE,name:ORole.name,indexVersion:2,indexDefinition:{className:ORole,field:name,keyType:STRING,collate:ci,nullValuesIgnored:false},indexDefinitionClass:com.orientechnologies.orient.core.index.OPropertyIndexDefinition,clusters:[1],algorithm:CELL_BTREE,valueContainerAlgorithm:NONE}
java.lang.IllegalArgumentException: COLLATE cannot be null
	at com.orientechnologies.orient.core.index.OAbstractIndexDefinition.setCollate(OAbstractIndexDefinition.java:47)
	at com.orientechnologies.orient.core.index.OAbstractIndexDefinition.setCollate(OAbstractIndexDefinition.java:55)
	at com.orientechnologies.orient.core.index.OPropertyIndexDefinition.serializeFromStream(OPropertyIndexDefinition.java:174)
	at com.orientechnologies.orient.core.index.OPropertyIndexDefinition.fromStream(OPropertyIndexDefinition.java:139)
	at com.orientechnologies.orient.core.type.ODocumentWrapperNoClass.fromStream(ODocumentWrapperNoClass.java:44)
	at com.orientechnologies.orient.core.index.OIndexAbstract.loadMetadataInternal(OIndexAbstract.java:127)
	at com.orientechnologies.orient.core.index.OIndexManagerRemote.fromStream(OIndexManagerRemote.java:162)
	at com.orientechnologies.orient.core.type.ODocumentWrapperNoClass.reload(ODocumentWrapperNoClass.java:66)
	at com.orientechnologies.orient.core.index.OIndexManagerAbstract.load(OIndexManagerAbstract.java:104)
	at com.orientechnologies.orient.core.db.document.OSharedContextRemote.load(OSharedContextRemote.java:33)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentRemote.loadMetadata(ODatabaseDocumentRemote.java:278)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentRemote.initAtFirstOpen(ODatabaseDocumentRemote.java:263)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentRemote.internalOpen(ODatabaseDocumentRemote.java:229)
	at com.orientechnologies.orient.core.db.OrientDBRemote.open(OrientDBRemote.java:86)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.open(ODatabaseDocumentTx.java:898)
	at com.tinkerpop.blueprints.impls.orient.OrientBaseGraph.openOrCreate(OrientBaseGraph.java:2016)
	at com.tinkerpop.blueprints.impls.orient.OrientBaseGraph.<init>(OrientBaseGraph.java:191)
	at com.tinkerpop.blueprints.impls.orient.OrientGraphNoTx.<init>(OrientGraphNoTx.java:66)_

**Comment by tglman** [comment]
Hi,

This seems an issue with the metadata management, could you share with us your classes and indexes ? or an example of them that reproduce the issue ?

Regards
