### ISSUE TITLE
Gremlin compatibility not present in console

### ISSUE THREAD

**Issue by jpelayo** [orientechnologies/orientdb#9114]
Hi,

I've just downloaded the v3 OSX package in order to test native Gremlin compatibility:
https://s3.us-east-2.amazonaws.com/orientdb3/releases/3.0.27/orientdb-3.0.27.tar.gz

When I launch the console, it starts with:
```
>./orientdb-3.0.27/bin/console.sh
OrientDB console v.3.0.27 - Veloce (build bc8f77600494cab71fb347d4c29f71c793442464, branch 3.0.x) https://www.orientdb.com
Type 'help' to display all the supported commands.
orientdb>
```
Not with the documented Gremlin plugin notice:
```
OrientDB console v.X.X.X (build 0) www.orientdb.com
Type 'HELP' to display all the commands supported.
Installing extensions for GREMLIN language v.X.X.X
orientdb>
```
so it of course lauches an error:
```
orientdb {db=test01}> gremlin g.V()

!Unrecognized command: 'gremlin g.V()'
```
I understand that it is not working as documented, so please, how can I enable the native Gremlin plugin on the OrientDB console?

Cheers!

**Comment by wolf4ood** [comment]
hi @jpelayo 

the wrapped gremlin console has been removed, since it was with TP2 implementation.

The Gremlin v3 implementation is here

https://github.com/orientechnologies/orientdb-gremlin

and comes with a gremlin server bundled, but not a console.

https://s3.us-east-2.amazonaws.com/orientdb3/releases/3.0.27/orientdb-tp3-3.0.27.zip

You can or download a gremlin console or run gremlin query in Studio against a orientdb tp3 edition

Thanks

**Comment by jpelayo** [comment]
Thank you!

I have deployed
```
https://s3.us-east-2.amazonaws.com/orientdb3/releases/3.0.27/orientdb-tp3-3.0.27.zip
```

And I have created a database named test01 with the browser studio.

Then I create test01.properties
```
gremlin.graph=org.apache.tinkerpop.gremlin.orientdb.OrientEmbeddedFactory
orient-db-name=test01
orient-user=xxxx
orient-pass=xxx
```
And I update gremlin-server.yaml
```
host: localhost
port: 8182
scriptEvaluationTimeout: 30000
channelizer: org.apache.tinkerpop.gremlin.server.channel.WebSocketChannelizer
graphManager : com.orientechnologies.tinkerpop.server.OrientGremlinGraphManager
graphs: {
  graph : ../config/test01.properties
...
```
in order to connect from a Gremlin console with
```
:remote connect tinkerpop.server /Users/xxx/Applications/TinkerPop/orientdb_gremlin_remote.yaml
```
with orientdb_gremlin_remote.yaml being:
```
hosts: [localhost]
port: 8182
username: xxx
password: xxxx
connectionPool: {
  enableSsl: false,
  sslEnabledProtocols: [TLSv1.2] }
serializer: { className: org.apache.tinkerpop.gremlin.driver.ser.GryoMessageSerializerV3d0, config: { serializeResultToString: true }}
```
(which BTW does not work with "enableSsl: true"

The problem is that wit demodb.properties the server will start, but with test01.properties it does not:
```
2020-01-24 15:40:04:161 INFO  Graph [graph] was successfully configured via [../config/test01.properties]. [GremlinServer]
2020-01-24 15:40:04:162 INFO  Initialized Gremlin thread pool.  Threads in pool named with pattern gremlin-* [ServerGremlinExecutor]
2020-01-24 15:40:04:227 INFO  Initialized GremlinExecutor and preparing GremlinScriptEngines instances. [ServerGremlinExecutor]
2020-01-24 15:40:04:239 INFO  Page size for WAL located in /Users/xxx/Applications/orientdb-tp3-3.0.27/databases/test01 is set to 4096 bytes. [OCASDiskWriteAheadLog]
2020-01-24 15:40:04:272 INFO  Storage 'plocal:/Users/pelayo/Applications/orientdb-tp3-3.0.27/databases/test01' is opened under OrientDB distribution : 3.0.27 - Veloce (build bc8f77600494cab71fb347d4c29f71c793442464, branch 3.0.x) [OLocalPaginatedStorage]
-----STOPS HERE-----
```
and the revealing line of a working gremlin server
```
2020-01-24 15:37:03:893 INFO  Channel started at port 8182. [GremlinServer]
```
is not there.

Am I missing something, please ?

Thanks Enrico!

**Comment by wolf4ood** [comment]
@jpelayo 

Strange, i did tried and it worked.

So it seems stucked? Could you share the thread dump?

You can make it  via `kill -3 <ODB_PID>`

**Comment by jpelayo** [comment]
Hi, let me try...
```
           .                                          
          .`        `                                 
          ,      `:.                                  
         `,`    ,:`                                   
         .,.   :,,                                    
         .,,  ,,,                                     
    .    .,.:::::  ````                                 :::::::::     :::::::::   
    ,`   .::,,,,::.,,,,,,`;;                      .:    ::::::::::    :::    :::  
    `,.  ::,,,,,,,:.,,.`  `                       .:    :::      :::  :::     ::: 
     ,,:,:,,,,,,,,::.   `        `         ``     .:    :::      :::  :::     ::: 
      ,,:.,,,,,,,,,: `::, ,,   ::,::`   : :,::`  ::::   :::      :::  :::    :::  
       ,:,,,,,,,,,,::,:   ,,  :.    :   ::    :   .:    :::      :::  :::::::     
        :,,,,,,,,,,:,::   ,,  :      :  :     :   .:    :::      :::  :::::::::   
  `     :,,,,,,,,,,:,::,  ,, .::::::::  :     :   .:    :::      :::  :::     ::: 
  `,...,,:,,,,,,,,,: .:,. ,, ,,         :     :   .:    :::      :::  :::     ::: 
    .,,,,::,,,,,,,:  `: , ,,  :     `   :     :   .:    :::      :::  :::     ::: 
      ...,::,,,,::.. `:  .,,  :,    :   :     :   .:    :::::::::::   :::     ::: 
           ,::::,,,. `:   ,,   :::::    :     :   .:    :::::::::     ::::::::::  
           ,,:` `,,.                                  
          ,,,    .,`                                  
         ,,.     `,                                              VELOCE  
       ``        `.                                                          
                 ``                                       www.orientdb.com
                 `                                    
removing old pid file /Users/xxx/Applications/orientdb-tp3-3.0.27/bin/orient.pid

2020-01-24 16:07:50:757 INFO  Default limit of open files (512) will be used. [ONative]
2020-01-24 16:07:50:790 INFO  Loading configuration from: /Users/xxxx/Applications/orientdb-tp3-3.0.27/config/orientdb-server-config.xml... [OServerConfigurationLoaderXml]
2020-01-24 16:07:51:036 INFO  OrientDB Server v3.0.27 - Veloce (build bc8f77600494cab71fb347d4c29f71c793442464, branch 3.0.x) is starting up... [OServer]
2020-01-24 16:07:51:119 INFO  17179869184 B/16384 MB/16 GB of physical memory were detected on machine [ONative]
2020-01-24 16:07:51:120 INFO  Detected memory limit for current process is 17179869184 B/16384 MB/16 GB [ONative]
2020-01-24 16:07:51:121 INFO  JVM can use maximum 1963MB of heap memory [OMemoryAndLocalPaginatedEnginesInitializer]
2020-01-24 16:07:51:121 INFO  Because OrientDB is running outside a container 12% of memory will be left unallocated according to the setting 'memory.leftToOS' not taking into account heap memory [OMemoryAndLocalPaginatedEnginesInitializer]
2020-01-24 16:07:51:123 INFO  OrientDB auto-config DISKCACHE=12.454MB (heap=1.963MB os=16.384MB) [orientechnologies]
2020-01-24 16:07:51:124 INFO  System is started under an effective user : `xxx` [OEngineLocalPaginated]
2020-01-24 16:07:51:125 INFO  Allocation of 189300 pages. [OEngineLocalPaginated]
2020-01-24 16:07:51:626 INFO  WAL maximum segment size is set to 6.144 MB [OrientDBDistributed]
2020-01-24 16:07:51:626 INFO  Databases directory: /Users/xxx/Applications/orientdb-tp3-3.0.27/databases [OServer]
2020-01-24 16:07:51:710 INFO  Page size for WAL located in /Users/xxxx/Applications/orientdb-tp3-3.0.27/databases/OSystem is set to 4096 bytes. [OCASDiskWriteAheadLog]
2020-01-24 16:07:51:775 WARNI Storage 'OSystem' was not closed properly. Will try to recover from write ahead log [OLocalPaginatedStorage]
2020-01-24 16:07:51:775 INFO  Looking for last checkpoint... [OLocalPaginatedStorage]
2020-01-24 16:07:51:779 INFO  FULL checkpoint found. [OLocalPaginatedStorage]
2020-01-24 16:07:51:782 INFO  Data restore procedure from full checkpoint is started. Restore is performed from LSN OLogSequenceNumber{segment=13, position=18} [OLocalPaginatedStorage]
2020-01-24 16:07:51:784 WARNI Record com.orientechnologies.orient.core.storage.impl.local.paginated.wal.OCheckpointEndRecord{lsn=OLogSequenceNumber{segment=13, position=40}} will be skipped during data restore [OLocalPaginatedStorage]
2020-01-24 16:07:51:785 INFO  1 operations were processed, current LSN is OLogSequenceNumber{segment=13, position=40} last LSN is OLogSequenceNumber{segment=14, position=18} [OLocalPaginatedStorage]
2020-01-24 16:07:51:785 WARNI Record com.orientechnologies.orient.core.storage.impl.local.paginated.wal.cas.OEmptyWALRecord{lsn=OLogSequenceNumber{segment=14, position=18}} will be skipped during data restore [OLocalPaginatedStorage]
2020-01-24 16:07:51:791 INFO  Storage data recover was completed [OLocalPaginatedStorage]
2020-01-24 16:07:52:198 INFO  Storage 'plocal:/Users/xxxx/Applications/orientdb-tp3-3.0.27/databases/OSystem' is opened under OrientDB distribution : 3.0.27 - Veloce (build bc8f77600494cab71fb347d4c29f71c793442464, branch 3.0.x) [OLocalPaginatedStorage]
2020-01-24 16:07:52:601 INFO  Listening binary connections on 0.0.0.0:2424 (protocol v.37, socket=default) [OServerNetworkListener]
2020-01-24 16:07:52:604 INFO  Listening http connections on 0.0.0.0:2480 (protocol v.10, socket=default) [OServerNetworkListener]
2020-01-24 16:07:52:612 INFO  Installing dynamic plugin 'orientdb-etl-3.0.27.jar'... [OServerPluginManager]
2020-01-24 16:07:52:617 INFO  Installing dynamic plugin 'orientdb-studio-3.0.27.zip'... [OServerPluginManager]
2020-01-24 16:07:52:619 INFO  ODefaultPasswordAuthenticator is active [ODefaultPasswordAuthenticator]
2020-01-24 16:07:52:620 INFO  OServerConfigAuthenticator is active [OServerConfigAuthenticator]
2020-01-24 16:07:52:621 INFO  OSystemUserAuthenticator is active [OSystemUserAuthenticator]
2020-01-24 16:07:52:722 INFO  70 attributes loaded from 95 stream(s) in 87ms, 70 saved, 1601 ignored: ["Ant-Version", "Archiver-Version", "Automatic-Module-Name", "BUILD", "Bnd-LastModified", "Build-Id", "Build-Jdk", "Build-Version", "Built-By", "Built-Date", "Bundle-ActivationPolicy", "Bundle-Activator", "Bundle-Category", "Bundle-ClassPath", "Bundle-Description", "Bundle-DocURL", "Bundle-License", "Bundle-ManifestVersion", "Bundle-Name", "Bundle-NativeCode", "Bundle-RequiredExecutionEnvironment", "Bundle-SymbolicName", "Bundle-Vendor", "Bundle-Version", "Class-Path", "Created-By", "DSTAMP", "DynamicImport-Package", "Eclipse-BuddyPolicy", "Export-Package", "Extension-Name", "Extension-name", "Fragment-Host", "Git-Revision", "Git-Url", "Ignore-Package", "Implementation-Build", "Implementation-Build-Date", "Implementation-Build-Id", "Implementation-Title", "Implementation-URL", "Implementation-Vendor", "Implementation-Vendor-Id", "Implementation-Version", "Import-Package", "Include-Resource", "JCabi-Build", "JCabi-Date", "JCabi-Version", "Main-Class", "Main-class", "Major-Version", "Manifest-Version", "Multi-Release", "Originally-Created-By", "Private-Package", "Require-Bundle", "Require-Capability", "Specification-Title", "Specification-Vendor", "Specification-Version", "TODAY", "TSTAMP", "Tool", "VERSION", "X-Compile-Source-JDK", "X-Compile-Target-JDK", "hash", "url", "version"] [Manifests]
2020-01-24 16:07:52:722 INFO  Installed GREMLIN language v.3.3.0 - graph.pool.max=50 [OGraphServerHandler]
2020-01-24 16:07:52:726 INFO  [OVariableParser.resolveVariables] Property not found: distributed [orientechnologies]
2020-01-24 16:07:52:735 WARNI Authenticated clients can execute any kind of code into the server by using the following allowed languages: [sql] [OServerSideScriptInterpreter]
2020-01-24 16:07:52:735 INFO  Gremlin Server is starting up... [OGremlinServerPlugin]
2020-01-24 16:07:52:851 INFO  Configured Metrics JmxReporter configured with domain= and agentId= [MetricManager]
2020-01-24 16:07:53:016 INFO  Graph [graph] was successfully configured via [../config/test01.properties]. [GremlinServer]
2020-01-24 16:07:53:016 INFO  Initialized Gremlin thread pool.  Threads in pool named with pattern gremlin-* [ServerGremlinExecutor]
2020-01-24 16:07:53:099 INFO  Initialized GremlinExecutor and preparing GremlinScriptEngines instances. [ServerGremlinExecutor]
2020-01-24 16:07:53:113 INFO  Page size for WAL located in /Users/xxxx/Applications/orientdb-tp3-3.0.27/databases/test01 is set to 4096 bytes. [OCASDiskWriteAheadLog]
2020-01-24 16:07:53:138 WARNI Storage 'test01' was not closed properly. Will try to recover from write ahead log [OLocalPaginatedStorage]
2020-01-24 16:07:53:138 INFO  Looking for last checkpoint... [OLocalPaginatedStorage]
2020-01-24 16:07:53:139 INFO  FULL checkpoint found. [OLocalPaginatedStorage]
2020-01-24 16:07:53:140 INFO  Data restore procedure from full checkpoint is started. Restore is performed from LSN OLogSequenceNumber{segment=11, position=18} [OLocalPaginatedStorage]
2020-01-24 16:07:53:141 WARNI Record com.orientechnologies.orient.core.storage.impl.local.paginated.wal.OCheckpointEndRecord{lsn=OLogSequenceNumber{segment=11, position=40}} will be skipped during data restore [OLocalPaginatedStorage]
2020-01-24 16:07:53:141 INFO  1 operations were processed, current LSN is OLogSequenceNumber{segment=11, position=40} last LSN is OLogSequenceNumber{segment=12, position=18} [OLocalPaginatedStorage]
2020-01-24 16:07:53:142 WARNI Record com.orientechnologies.orient.core.storage.impl.local.paginated.wal.cas.OEmptyWALRecord{lsn=OLogSequenceNumber{segment=12, position=18}} will be skipped during data restore [OLocalPaginatedStorage]
2020-01-24 16:07:53:144 INFO  Storage data recover was completed [OLocalPaginatedStorage]
2020-01-24 16:07:53:153 INFO  Storage 'plocal:/Users/xxx/Applications/orientdb-tp3-3.0.27/databases/test01' is opened under OrientDB distribution : 3.0.27 - Veloce (build bc8f77600494cab71fb347d4c29f71c793442464, branch 3.0.x) [OLocalPaginatedStorage]
```
dump:

```
Full thread dump Java HotSpot(TM) 64-Bit Server VM (25.161-b12 mixed mode):

"OrientDB HTTP Connection /127.0.0.1:2480<-/127.0.0.1:63493" #30 daemon prio=5 os_prio=31 tid=0x00007f97bedb9800 nid=0x5a03 runnable [0x000070000e2d3000]
   java.lang.Thread.State: RUNNABLE
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
	at java.net.SocketInputStream.read(SocketInputStream.java:171)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)
	at java.io.BufferedInputStream.fill(BufferedInputStream.java:246)
	at java.io.BufferedInputStream.read(BufferedInputStream.java:265)
	- locked <0x0000000799689c48> (a java.io.BufferedInputStream)
	at com.orientechnologies.orient.enterprise.channel.text.OChannelText.read(OChannelText.java:61)
	at com.orientechnologies.orient.server.network.protocol.http.ONetworkProtocolHttpAbstract.execute(ONetworkProtocolHttpAbstract.java:651)
	at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:69)

"gremlin-server-exec-1" #27 prio=5 os_prio=31 tid=0x00007f97beda5800 nid=0x5903 waiting on condition [0x000070000e1d0000]
   java.lang.Thread.State: WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x00000007a2ae7ee8> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2039)
	at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:442)
	at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1074)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1134)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

"OrientDB ONetworkProtocolHttpDb listen at 0.0.0.0:2480-2490" #22 prio=5 os_prio=31 tid=0x00007f97beda6800 nid=0x5803 runnable [0x000070000e0cd000]
   java.lang.Thread.State: RUNNABLE
	at java.net.PlainSocketImpl.socketAccept(Native Method)
	at java.net.AbstractPlainSocketImpl.accept(AbstractPlainSocketImpl.java:409)
	at java.net.ServerSocket.implAccept(ServerSocket.java:545)
	at java.net.ServerSocket.accept(ServerSocket.java:513)
	at com.orientechnologies.orient.server.network.OServerNetworkListener.run(OServerNetworkListener.java:188)

"OrientDB ONetworkProtocolBinary listen at 0.0.0.0:2424-2430" #20 prio=5 os_prio=31 tid=0x00007f97bd5cb000 nid=0x5603 runnable [0x000070000dfca000]
   java.lang.Thread.State: RUNNABLE
	at java.net.PlainSocketImpl.socketAccept(Native Method)
	at java.net.AbstractPlainSocketImpl.accept(AbstractPlainSocketImpl.java:409)
	at java.net.ServerSocket.implAccept(ServerSocket.java:545)
	at java.net.ServerSocket.accept(ServerSocket.java:513)
	at com.orientechnologies.orient.server.network.OServerNetworkListener.run(OServerNetworkListener.java:188)

"OrientDB Write Cache Flush Task" #17 daemon prio=5 os_prio=31 tid=0x00007f97bed76800 nid=0x5503 waiting on condition [0x000070000dec7000]
   java.lang.Thread.State: TIMED_WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x0000000740012768> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
	at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2078)
	at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:1093)
	at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:809)
	at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1074)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1134)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

"OrientDB WAL Write Task Thread)" #16 daemon prio=5 os_prio=31 tid=0x00007f97bd55d800 nid=0x4103 waiting on condition [0x000070000ddc4000]
   java.lang.Thread.State: WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x0000000740019c08> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2039)
	at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:442)
	at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1074)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1134)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

"OrientDB WAL Flush Task" #15 daemon prio=5 os_prio=31 tid=0x00007f97bda4d000 nid=0x4003 waiting on condition [0x000070000dcc1000]
   java.lang.Thread.State: TIMED_WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x0000000740021bd8> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
	at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2078)
	at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:1093)
	at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:809)
	at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1074)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1134)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

"Thread-5" #14 daemon prio=5 os_prio=31 tid=0x00007f97bd54f800 nid=0x4403 waiting on condition [0x000070000dbbe000]
   java.lang.Thread.State: TIMED_WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x0000000740029ba8> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
	at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2078)
	at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:1093)
	at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:809)
	at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1074)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1134)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

"Timer-0" #11 daemon prio=5 os_prio=31 tid=0x00007f97bec69800 nid=0x3d03 in Object.wait() [0x000070000dabb000]
   java.lang.Thread.State: TIMED_WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	- waiting on <0x0000000740019e90> (a java.util.TaskQueue)
	at java.util.TimerThread.mainLoop(Timer.java:552)
	- locked <0x0000000740019e90> (a java.util.TaskQueue)
	at java.util.TimerThread.run(Timer.java:505)

"Thread-0" #9 prio=5 os_prio=31 tid=0x00007f97bd0a4800 nid=0x3c03 waiting on condition [0x000070000d9b8000]
   java.lang.Thread.State: WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x00000007a3eaa0f8> (a java.util.concurrent.CompletableFuture$Signaller)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
	at java.util.concurrent.CompletableFuture$Signaller.block(CompletableFuture.java:1693)
	at java.util.concurrent.ForkJoinPool.managedBlock(ForkJoinPool.java:3323)
	at java.util.concurrent.CompletableFuture.waitingGet(CompletableFuture.java:1729)
	at java.util.concurrent.CompletableFuture.join(CompletableFuture.java:1934)
	at org.apache.tinkerpop.gremlin.server.util.ServerGremlinExecutor.lambda$new$4(ServerGremlinExecutor.java:141)
	at org.apache.tinkerpop.gremlin.server.util.ServerGremlinExecutor$$Lambda$119/107398031.accept(Unknown Source)
	at java.util.LinkedHashMap$LinkedKeySet.forEach(LinkedHashMap.java:559)
	at org.apache.tinkerpop.gremlin.server.util.ServerGremlinExecutor.<init>(ServerGremlinExecutor.java:136)
	at org.apache.tinkerpop.gremlin.server.GremlinServer.<init>(GremlinServer.java:111)
	at com.orientechnologies.tinkerpop.server.OGremlinServerPlugin.onAfterActivate(OGremlinServerPlugin.java:83)
	at com.orientechnologies.orient.server.OServer.activate(OServer.java:472)
	at com.orientechnologies.orient.server.OServerMain$1.run(OServerMain.java:48)

"Service Thread" #8 daemon prio=9 os_prio=31 tid=0x00007f97bd069000 nid=0x4703 runnable [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"C1 CompilerThread2" #7 daemon prio=9 os_prio=31 tid=0x00007f97bd038800 nid=0x3903 waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"C2 CompilerThread1" #6 daemon prio=9 os_prio=31 tid=0x00007f97be838800 nid=0x3703 waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"C2 CompilerThread0" #5 daemon prio=9 os_prio=31 tid=0x00007f97be837800 nid=0x3603 waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"Signal Dispatcher" #4 daemon prio=9 os_prio=31 tid=0x00007f97bd02d800 nid=0x3403 waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"Finalizer" #3 daemon prio=8 os_prio=31 tid=0x00007f97bd808800 nid=0x2f03 in Object.wait() [0x000070000d2a3000]
   java.lang.Thread.State: WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	- waiting on <0x000000074002a568> (a java.lang.ref.ReferenceQueue$Lock)
	at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:143)
	- locked <0x000000074002a568> (a java.lang.ref.ReferenceQueue$Lock)
	at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:164)
	at java.lang.ref.Finalizer$FinalizerThread.run(Finalizer.java:209)

"Reference Handler" #2 daemon prio=10 os_prio=31 tid=0x00007f97bd805800 nid=0x2e03 in Object.wait() [0x000070000d1a0000]
   java.lang.Thread.State: WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	- waiting on <0x000000074002a720> (a java.lang.ref.Reference$Lock)
	at java.lang.Object.wait(Object.java:502)
	at java.lang.ref.Reference.tryHandlePending(Reference.java:191)
	- locked <0x000000074002a720> (a java.lang.ref.Reference$Lock)
	at java.lang.ref.Reference$ReferenceHandler.run(Reference.java:153)

"main" #1 prio=5 os_prio=31 tid=0x00007f97be801800 nid=0x2603 in Object.wait() [0x000070000cb8e000]
   java.lang.Thread.State: WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	- waiting on <0x0000000740021cc0> (a com.orientechnologies.orient.server.OServerMain$1)
	at java.lang.Thread.join(Thread.java:1252)
	- locked <0x0000000740021cc0> (a com.orientechnologies.orient.server.OServerMain$1)
	at java.lang.Thread.join(Thread.java:1326)
	at com.orientechnologies.orient.server.OServerMain.main(OServerMain.java:59)

"VM Thread" os_prio=31 tid=0x00007f97be831800 nid=0x2d03 runnable 

"GC task thread#0 (ParallelGC)" os_prio=31 tid=0x00007f97be80b000 nid=0x1e07 runnable 

"GC task thread#1 (ParallelGC)" os_prio=31 tid=0x00007f97bd012800 nid=0x2a03 runnable 

"GC task thread#2 (ParallelGC)" os_prio=31 tid=0x00007f97be000800 nid=0x5403 runnable 

"GC task thread#3 (ParallelGC)" os_prio=31 tid=0x00007f97bd013000 nid=0x2c03 runnable 

"VM Periodic Task Thread" os_prio=31 tid=0x00007f97bd07c000 nid=0x4603 waiting on condition 

JNI global references: 1930

Heap
 PSYoungGen      total 611840K, used 302299K [0x0000000795580000, 0x00000007c0000000, 0x00000007c0000000)
  eden space 524800K, 57% used [0x0000000795580000,0x00000007a7cb6c68,0x00000007b5600000)
  from space 87040K, 0% used [0x00000007b5600000,0x00000007b5600000,0x00000007bab00000)
  to   space 87040K, 0% used [0x00000007bab00000,0x00000007bab00000,0x00000007c0000000)
 ParOldGen       total 1398272K, used 42609K [0x0000000740000000, 0x0000000795580000, 0x0000000795580000)
  object space 1398272K, 3% used [0x0000000740000000,0x000000074299c578,0x0000000795580000)
 Metaspace       used 33547K, capacity 34501K, committed 34560K, reserved 1079296K
  class space    used 4039K, capacity 4351K, committed 4352K, reserved 1048576K
```

**Comment by wolf4ood** [comment]
Hi @jpelayo 

i've managed to reproduce it by using the wrong credentials in the `.properties` file.

Check if they are correct. It seems that the startup log swallows the exception.

Let me know if that was the case

Thanks

**Comment by jpelayo** [comment]
Hi,
No, I'm sure it is not a typo. In order to make sure, I copy/pasted the credentials on the web studio in test01.properties to the web login access textbox, and I can enter the database via web. 
Could it be some kind of login method mismatch or a hidden ssl requirement for login?
Cheers!

**Comment by wolf4ood** [comment]
@jpelayo 

are you using the root credentials (Server User)?

if yes try the database user, by default `admin/admin`

Let me know

Thanks

**Comment by jpelayo** [comment]
Jackpot.

That was the case. I didn't know about any default username.

I can now do a regular connection with a stock Tinkerpop console.

Thank you very much, Enrico.

**Comment by jpelayo** [comment]
Solved by wolf4ood

**Comment by jpelayo** [comment]
Sorry, additional question.
Does a graph created using the gremlin console connected to the embedded gremlin server be reflected as a graph in the orientdb graph editor?
I have created some vertices and edges, and they are stored but the Graph Editor is empty.
```
gremlin> g.E()
==>e[#29:-6][#21:-2-fits->#25:-4]
==>e[#30:-7][#22:-3-fits->#25:-4]
==>e[#31:-8][#21:-2-fits->#26:-5]
==>e[#32:-9][#22:-3-fits->#26:-5]
```
Server is receiving:
```
2020-01-25 12:14:47:286 INFO  New session established for 2a3d83f7-1daf-4555-bc6f-76aaa166cfb8 [Session]
2020-01-25 12:15:06:629 INFO  {db=sm01test} created class 'article' as subclass of 'V' [OrientGraph]
2020-01-25 12:17:48:739 INFO  {db=sm01test} created class 'user' as subclass of 'V' [OrientGraph]
2020-01-25 12:32:05:013 INFO  {db=sm01test} created class 'fits' as subclass of 'E' [OrientGraph]
```
![Captura de pantalla 2020-01-25 a las 12 51 01](https://user-images.githubusercontent.com/10059639/73120662-5f3e6380-3f71-11ea-94f9-38123e1facc0.jpg)

![Captura de pantalla 2020-01-25 a las 12 52 38](https://user-images.githubusercontent.com/10059639/73120690-ae849400-3f71-11ea-8c83-85b43cdd1bbc.jpg)

![Captura de pantalla 2020-01-25 a las 12 52 58](https://user-images.githubusercontent.com/10059639/73120693-b5130b80-3f71-11ea-940b-b60e65c95d81.jpg)
