### ISSUE TITLE
DB crashed and could not recover

### ISSUE THREAD

**Issue by andreyvk** [orientechnologies/orientdb#9133]
### OrientDB Version: 3.0.12

Hi,

Yesterday our DB crashed beyond recovery. First we ran a query from the Studio and by mistake put a large limit. First DB became unresponsive and after forced server restart stopped working saying smth like 'database was not closed properly' and that it will 'try to recover from lookahead log', which it never did and we were not able to make any connection to it neight from console, nor from the Studio, nor from the driver.

In order to keep things running we've replaced mydb.wmr with one from our previous backups. This allowed us to start db but now log is full of exceptions (naturally) that look like the following. 

Please advise.

```
Exception `5E2D6E97` in storage `plocal:/usr/local/orientdb/orientdb-3.0.12/databases/mydb`: 3.0.12 - Veloce (build b89d566f96b4632bc56422887d7f249e5c2ce23f, branch 3.0.x)
java.lang.NullPointerException
$ANSI{green {db=mydb}} Error on fetching record during browsing. The record has been skipped
com.orientechnologies.orient.core.exception.ODatabaseException: Error on retrieving record #35:18966 (cluster: user)
        DB name="mydb"
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentAbstract.executeReadRecord(ODatabaseDocumentAbstract.java:1430)
        at com.orientechnologies.orient.core.tx.OTransactionNoTx.loadRecord(OTransactionNoTx.java:90)
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentAbstract.load(ODatabaseDocumentAbstract.java:1185)
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentAbstract.load(ODatabaseDocumentAbstract.java:138)
        at com.orientechnologies.orient.core.iterator.OIdentifiableIterator.readCurrentRecord(OIdentifiableIterator.java:288)
        at com.orientechnologies.orient.core.iterator.ORecordIteratorClusters.hasNext(ORecordIteratorClusters.java:164)
        at com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.serialIterator(OCommandExecutorSQLSelect.java:1609)
        at com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.fetchFromTarget(OCommandExecutorSQLSelect.java:1557)
        at com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.executeSearch(OCommandExecutorSQLSelect.java:510)
        at com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.execute(OCommandExecutorSQLSelect.java:473)
        at com.orientechnologies.orient.core.sql.OCommandExecutorSQLDelegate.execute(OCommandExecutorSQLDelegate.java:74)
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.executeCommand(OAbstractPaginatedStorage.java:3797)
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.command(OAbstractPaginatedStorage.java:3731)
        at com.orientechnologies.orient.core.sql.query.OSQLQuery.run(OSQLQuery.java:71)
        at com.orientechnologies.orient.core.sql.query.OSQLAsynchQuery.run(OSQLAsynchQuery.java:74)
        at com.orientechnologies.orient.core.sql.query.OSQLSynchQuery.run(OSQLSynchQuery.java:86)
        at com.orientechnologies.orient.core.query.OQueryAbstract.execute(OQueryAbstract.java:33)
        at com.orientechnologies.orient.server.OConnectionBinaryExecutor.executeCommand(OConnectionBinaryExecutor.java:739)
        at com.orientechnologies.orient.client.remote.message.OCommandRequest.execute(OCommandRequest.java:103)
        at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.sessionRequest(ONetworkProtocolBinary.java:304)
        at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.execute(ONetworkProtocolBinary.java:206)
        at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:69)
Caused by: java.lang.NullPointerException
Exception `16782296` in storage `plocal:/usr/local/orientdb/orientdb-3.0.12/databases/mydb`: 3.0.12 - Veloce (build b89d566f96b4632bc56422887d7f249e5c2ce23f, branch 3.0.x)
java.lang.NegativeArraySizeException
        at com.orientechnologies.common.serialization.types.OStringSerializer.deserializeFromByteBufferObject(OStringSerializer.java:164)
        at com.orientechnologies.common.serialization.types.OStringSerializer.deserializeFromByteBufferObject(OStringSerializer.java:33)
        at com.orientechnologies.orient.core.storage.impl.local.paginated.base.ODurablePage.deserializeFromDirectMemory(ODurablePage.java:165)
        at com.orientechnologies.orient.core.storage.index.sbtree.local.OSBTreeBucket.getKey(OSBTreeBucket.java:377)
        at com.orientechnologies.orient.core.storage.index.sbtree.local.OSBTreeBucket.find(OSBTreeBucket.java:137)
        at com.orientechnologies.orient.core.storage.index.sbtree.local.OSBTree.findBucket(OSBTree.java:1379)
        at com.orientechnologies.orient.core.storage.index.sbtree.local.OSBTree.update(OSBTree.java:254)
        at com.orientechnologies.orient.core.storage.index.engine.OSBTreeIndexEngine.update(OSBTreeIndexEngine.java:198)
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.doUpdateIndexEntry(OAbstractPaginatedStorage.java:2769)
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.updateIndexEntry(OAbstractPaginatedStorage.java:2682)
        at com.orientechnologies.orient.core.index.OIndexMultiValues.put(OIndexMultiValues.java:173)
        at com.orientechnologies.orient.core.index.OIndexMultiValues.put(OIndexMultiValues.java:52)
        at com.orientechnologies.orient.core.index.OIndexAbstract.putInSnapshot(OIndexAbstract.java:862)
        at com.orientechnologies.orient.core.index.OIndexAbstract.applyIndexTxEntry(OIndexAbstract.java:705)
        at com.orientechnologies.orient.core.index.OIndexAbstract.addTxOperation(OIndexAbstract.java:677)
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.commitIndexes(OAbstractPaginatedStorage.java:2229)
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.commit(OAbstractPaginatedStorage.java:2157)
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.commit(OAbstractPaginatedStorage.java:1980)
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentAbstract.internalCommit(ODatabaseDocumentAbstract.java:2804)
        at com.orientechnologies.orient.core.storage.impl.local.OMicroTransaction.doCommit(OMicroTransaction.java:363)
        at com.orientechnologies.orient.core.storage.impl.local.OMicroTransaction.commit(OMicroTransaction.java:166)
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentEmbedded.endMicroTransaction(ODatabaseDocumentEmbedded.java:756)
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentEmbedded.executeSaveRecord(ODatabaseDocumentEmbedded.java:746)
        at com.orientechnologies.orient.core.tx.OTransactionNoTx.saveRecord(OTransactionNoTx.java:184)
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentAbstract.saveInternal(ODatabaseDocumentAbstract.java:2130)
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentAbstract.save(ODatabaseDocumentAbstract.java:2095)
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentAbstract.save(ODatabaseDocumentAbstract.java:1987)
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentAbstract.save(ODatabaseDocumentAbstract.java:138)
        at com.orientechnologies.orient.server.OConnectionBinaryExecutor.executeUpdateRecord(OConnectionBinaryExecutor.java:575)
        at com.orientechnologies.orient.client.remote.message.OUpdateRecordRequest.execute(OUpdateRecordRequest.java:133)
        at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.sessionRequest(ONetworkProtocolBinary.java:304)
        at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.execute(ONetworkProtocolBinary.java:206)
        at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:69)
Exception `16782296` in storage `plocal:/usr/local/orientdb/orientdb-3.0.12/databases/mydb`: 3.0.12 - Veloce (build b89d566f96b4632bc56422887d7f249e5c2ce23f, branch 3.0.x)
java.lang.NegativeArraySizeException
        at com.orientechnologies.common.serialization.types.OStringSerializer.deserializeFromByteBufferObject(OStringSerializer.java:164)
        at com.orientechnologies.common.serialization.types.OStringSerializer.deserializeFromByteBufferObject(OStringSerializer.java:33)
        at com.orientechnologies.orient.core.storage.impl.local.paginated.base.ODurablePage.deserializeFromDirectMemory(ODurablePage.java:165)
        at com.orientechnologies.orient.core.storage.index.sbtree.local.OSBTreeBucket.getKey(OSBTreeBucket.java:377)
        at com.orientechnologies.orient.core.storage.index.sbtree.local.OSBTreeBucket.find(OSBTreeBucket.java:137)
        at com.orientechnologies.orient.core.storage.index.sbtree.local.OSBTree.findBucket(OSBTree.java:1379)
        at com.orientechnologies.orient.core.storage.index.sbtree.local.OSBTree.update(OSBTree.java:254)
        at com.orientechnologies.orient.core.storage.index.engine.OSBTreeIndexEngine.update(OSBTreeIndexEngine.java:198)
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.doUpdateIndexEntry(OAbstractPaginatedStorage.java:2769)
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.updateIndexEntry(OAbstractPaginatedStorage.java:2682)
        at com.orientechnologies.orient.core.index.OIndexMultiValues.put(OIndexMultiValues.java:173)
        at com.orientechnologies.orient.core.index.OIndexMultiValues.put(OIndexMultiValues.java:52)
        at com.orientechnologies.orient.core.index.OIndexAbstract.putInSnapshot(OIndexAbstract.java:862)
        at com.orientechnologies.orient.core.index.OIndexAbstract.applyIndexTxEntry(OIndexAbstract.java:705)
        at com.orientechnologies.orient.core.index.OIndexAbstract.addTxOperation(OIndexAbstract.java:677)
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.commitIndexes(OAbstractPaginatedStorage.java:2229)
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.commit(OAbstractPaginatedStorage.java:2157)
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.commit(OAbstractPaginatedStorage.java:1980)
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentAbstract.internalCommit(ODatabaseDocumentAbstract.java:2804)
        at com.orientechnologies.orient.core.storage.impl.local.OMicroTransaction.doCommit(OMicroTransaction.java:363)
        at com.orientechnologies.orient.core.storage.impl.local.OMicroTransaction.commit(OMicroTransaction.java:166)
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentEmbedded.endMicroTransaction(ODatabaseDocumentEmbedded.java:756)
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentEmbedded.executeSaveRecord(ODatabaseDocumentEmbedded.java:746)
        at com.orientechnologies.orient.core.tx.OTransactionNoTx.saveRecord(OTransactionNoTx.java:184)
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentAbstract.saveInternal(ODatabaseDocumentAbstract.java:2130)
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentAbstract.save(ODatabaseDocumentAbstract.java:2095)
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentAbstract.save(ODatabaseDocumentAbstract.java:1987)
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentAbstract.save(ODatabaseDocumentAbstract.java:138)
        at com.orientechnologies.orient.server.OConnectionBinaryExecutor.executeUpdateRecord(OConnectionBinaryExecutor.java:575)
        at com.orientechnologies.orient.client.remote.message.OUpdateRecordRequest.execute(OUpdateRecordRequest.java:133)
        at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.sessionRequest(ONetworkProtocolBinary.java:304)
        at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.execute(ONetworkProtocolBinary.java:206)
        at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:69)

2020-02-11 07:53:42:090 INFO  Before fuzzy checkpoint: min LSN segment is null, WAL begin is OLogSequenceNumber{segment=57, position=18}, WAL end is OLogSequenceNumber{segment=57, position=4152}, fuzzy segment is 57 [OLocalPaginatedStorage]
2020-02-11 07:53:42:090 INFO  No reason to make fuzzy checkpoint [OLocalPaginatedStorage]


Exception `5E2D6E97` in storage `plocal:/usr/local/orientdb/orientdb-3.0.12/databases/mydb`: 3.0.12 - Veloce (build b89d566f96b4632bc56422887d7f249e5c2ce23f, branch 3.0.x)
java.lang.NullPointerException
$ANSI{green {db=mydb}} Error on fetching record during browsing. The record has been skipped
com.orientechnologies.orient.core.exception.ODatabaseException: Error on retrieving record #35:18966 (cluster: user)
        DB name="mydb"
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentAbstract.executeReadRecord(ODatabaseDocumentAbstract.java:1430)
        at com.orientechnologies.orient.core.tx.OTransactionNoTx.loadRecord(OTransactionNoTx.java:90)
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentAbstract.load(ODatabaseDocumentAbstract.java:1185)
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentAbstract.load(ODatabaseDocumentAbstract.java:138)
        at com.orientechnologies.orient.core.iterator.OIdentifiableIterator.readCurrentRecord(OIdentifiableIterator.java:288)
        at com.orientechnologies.orient.core.iterator.ORecordIteratorClusters.hasNext(ORecordIteratorClusters.java:164)
        at com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.serialIterator(OCommandExecutorSQLSelect.java:1609)
        at com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.fetchFromTarget(OCommandExecutorSQLSelect.java:1557)
        at com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.executeSearch(OCommandExecutorSQLSelect.java:510)
        at com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.execute(OCommandExecutorSQLSelect.java:473)
        at com.orientechnologies.orient.core.sql.OCommandExecutorSQLDelegate.execute(OCommandExecutorSQLDelegate.java:74)
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.executeCommand(OAbstractPaginatedStorage.java:3797)
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.command(OAbstractPaginatedStorage.java:3731)
        at com.orientechnologies.orient.core.sql.query.OSQLQuery.run(OSQLQuery.java:71)
        at com.orientechnologies.orient.core.sql.query.OSQLAsynchQuery.run(OSQLAsynchQuery.java:74)
        at com.orientechnologies.orient.core.sql.query.OSQLSynchQuery.run(OSQLSynchQuery.java:86)
        at com.orientechnologies.orient.core.query.OQueryAbstract.execute(OQueryAbstract.java:33)
        at com.orientechnologies.orient.server.OConnectionBinaryExecutor.executeCommand(OConnectionBinaryExecutor.java:739)
        at com.orientechnologies.orient.client.remote.message.OCommandRequest.execute(OCommandRequest.java:103)
        at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.sessionRequest(ONetworkProtocolBinary.java:304)
        at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.execute(ONetworkProtocolBinary.java:206)
        at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:69)

```

**Comment by andreyvk** [comment]
There are also more exceptions that look like the following:

```
2020-02-11 08:01:19:671 INFO  Before fuzzy checkpoint: min LSN segment is null, WAL begin is OLogSequenceNumber{segment=2, position=18}, WAL end is OLogSequenceNumber{segment=2, position=24}, fuzzy segment is 2 [OLocalPaginatedStorage]
2020-02-11 08:01:19:671 INFO  No reason to make fuzzy checkpoint [OLocalPaginatedStorage]Exception `72FFC3D9` in storage `plocal:/usr/local/orientdb/orientdb-3.0.12/databases/mydb`: 3.0.12 - Veloce (build b89d566f96b4632bc56422887d7f249e5c2ce23f, branch 3.0.x)
java.lang.NegativeArraySizeException
        at com.orientechnologies.common.serialization.types.OStringSerializer.deserializeFromByteBufferObject(OStringSerializer.java:164)
        at com.orientechnologies.common.serialization.types.OStringSerializer.deserializeFromByteBufferObject(OStringSerializer.java:33)
        at com.orientechnologies.orient.core.storage.impl.local.paginated.base.ODurablePage.deserializeFromDirectMemory(ODurablePage.java:165)
        at com.orientechnologies.orient.core.storage.index.sbtree.local.OSBTreeBucket.getKey(OSBTreeBucket.java:377)
        at com.orientechnologies.orient.core.storage.index.sbtree.local.OSBTreeBucket.find(OSBTreeBucket.java:137)
        at com.orientechnologies.orient.core.storage.index.sbtree.local.OSBTree.findBucket(OSBTree.java:1379)
        at com.orientechnologies.orient.core.storage.index.sbtree.local.OSBTree.update(OSBTree.java:254)
        at com.orientechnologies.orient.core.storage.index.engine.OSBTreeIndexEngine.update(OSBTreeIndexEngine.java:198)
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.doUpdateIndexEntry(OAbstractPaginatedStorage.java:2769)
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.updateIndexEntry(OAbstractPaginatedStorage.java:2682)
        at com.orientechnologies.orient.core.index.OIndexMultiValues.put(OIndexMultiValues.java:173)
        at com.orientechnologies.orient.core.index.OIndexMultiValues.put(OIndexMultiValues.java:52)
        at com.orientechnologies.orient.core.index.OIndexAbstract.putInSnapshot(OIndexAbstract.java:862)
        at com.orientechnologies.orient.core.index.OIndexAbstract.applyIndexTxEntry(OIndexAbstract.java:705)
        at com.orientechnologies.orient.core.index.OIndexAbstract.addTxOperation(OIndexAbstract.java:677)
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.commitIndexes(OAbstractPaginatedStorage.java:2229)
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.commit(OAbstractPaginatedStorage.java:2157)
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.commit(OAbstractPaginatedStorage.java:1980)
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentAbstract.internalCommit(ODatabaseDocumentAbstract.java:2804)
        at com.orientechnologies.orient.core.storage.impl.local.OMicroTransaction.doCommit(OMicroTransaction.java:363)
        at com.orientechnologies.orient.core.storage.impl.local.OMicroTransaction.commit(OMicroTransaction.java:166)
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentEmbedded.endMicroTransaction(ODatabaseDocumentEmbedded.java:756)
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentEmbedded.executeSaveRecord(ODatabaseDocumentEmbedded.java:746)
        at com.orientechnologies.orient.core.tx.OTransactionNoTx.saveRecord(OTransactionNoTx.java:184)
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentAbstract.saveInternal(ODatabaseDocumentAbstract.java:2130)
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentAbstract.save(ODatabaseDocumentAbstract.java:2095)
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentAbstract.save(ODatabaseDocumentAbstract.java:1987)
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentAbstract.save(ODatabaseDocumentAbstract.java:138)
        at com.orientechnologies.orient.server.OConnectionBinaryExecutor.executeUpdateRecord(OConnectionBinaryExecutor.java:575)
        at com.orientechnologies.orient.client.remote.message.OUpdateRecordRequest.execute(OUpdateRecordRequest.java:133)
        at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.sessionRequest(ONetworkProtocolBinary.java:304)
        at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.execute(ONetworkProtocolBinary.java:206)
        at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:69)
Exception `72FFC3D9` in storage `plocal:/usr/local/orientdb/orientdb-3.0.12/databases/mydb`: 3.0.12 - Veloce (build b89d566f96b4632bc56422887d7f249e5c2ce23f, branch 3.0.x)
java.lang.NegativeArraySizeException
        at com.orientechnologies.common.serialization.types.OStringSerializer.deserializeFromByteBufferObject(OStringSerializer.java:164)
        at com.orientechnologies.common.serialization.types.OStringSerializer.deserializeFromByteBufferObject(OStringSerializer.java:33)
        at com.orientechnologies.orient.core.storage.impl.local.paginated.base.ODurablePage.deserializeFromDirectMemory(ODurablePage.java:165)
        at com.orientechnologies.orient.core.storage.index.sbtree.local.OSBTreeBucket.getKey(OSBTreeBucket.java:377)
        at com.orientechnologies.orient.core.storage.index.sbtree.local.OSBTreeBucket.find(OSBTreeBucket.java:137)
        at com.orientechnologies.orient.core.storage.index.sbtree.local.OSBTree.findBucket(OSBTree.java:1379)
        at com.orientechnologies.orient.core.storage.index.sbtree.local.OSBTree.update(OSBTree.java:254)
        at com.orientechnologies.orient.core.storage.index.engine.OSBTreeIndexEngine.update(OSBTreeIndexEngine.java:198)
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.doUpdateIndexEntry(OAbstractPaginatedStorage.java:2769)
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.updateIndexEntry(OAbstractPaginatedStorage.java:2682)
        at com.orientechnologies.orient.core.index.OIndexMultiValues.put(OIndexMultiValues.java:173)
        at com.orientechnologies.orient.core.index.OIndexMultiValues.put(OIndexMultiValues.java:52)
        at com.orientechnologies.orient.core.index.OIndexAbstract.putInSnapshot(OIndexAbstract.java:862)
        at com.orientechnologies.orient.core.index.OIndexAbstract.applyIndexTxEntry(OIndexAbstract.java:705)
        at com.orientechnologies.orient.core.index.OIndexAbstract.addTxOperation(OIndexAbstract.java:677)
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.commitIndexes(OAbstractPaginatedStorage.java:2229)
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.commit(OAbstractPaginatedStorage.java:2157)
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.commit(OAbstractPaginatedStorage.java:1980)
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentAbstract.internalCommit(ODatabaseDocumentAbstract.java:2804)
        at com.orientechnologies.orient.core.storage.impl.local.OMicroTransaction.doCommit(OMicroTransaction.java:363)
        at com.orientechnologies.orient.core.storage.impl.local.OMicroTransaction.commit(OMicroTransaction.java:166)
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentEmbedded.endMicroTransaction(ODatabaseDocumentEmbedded.java:756)
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentEmbedded.executeSaveRecord(ODatabaseDocumentEmbedded.java:746)
        at com.orientechnologies.orient.core.tx.OTransactionNoTx.saveRecord(OTransactionNoTx.java:184)
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentAbstract.saveInternal(ODatabaseDocumentAbstract.java:2130)
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentAbstract.save(ODatabaseDocumentAbstract.java:2095)
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentAbstract.save(ODatabaseDocumentAbstract.java:1987)
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentAbstract.save(ODatabaseDocumentAbstract.java:138)
        at com.orientechnologies.orient.server.OConnectionBinaryExecutor.executeUpdateRecord(OConnectionBinaryExecutor.java:575)
        at com.orientechnologies.orient.client.remote.message.OUpdateRecordRequest.execute(OUpdateRecordRequest.java:133)
        at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.sessionRequest(ONetworkProtocolBinary.java:304)
        at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.execute(ONetworkProtocolBinary.java:206)
        at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:69)
```
