### ISSUE TITLE
Migrating from 2.2.20 orient to 3.0.26 but orient building got struck.

### ISSUE THREAD

**Issue by rbaarathi** [orientechnologies/orientdb#9140]
## Expected behavior  
Current orient version using 2.2.20.
Now trying to migrating to 3.0.26
Adding new orient jars in my application server and trying to build new orient database.

## Actual behavior 
We are adding various objectTypes of ODocument into orient database.

During addition, observing following jstack and hence orient threads in waiting state.

"InventoryDataBuilderMaster_CircuitPlugInventoryDataBuilder" #848 prio=5 os_prio=0 tid=0x00007fc15ec8c800 nid=0x4df6 waiting on condition [0x00007fc0d
7944000]
   java.lang.Thread.State: WAITING (parking)
        at sun.misc.Unsafe.park(Native Method)
        - parking to wait for  <0x0000000724854388> (a com.orientechnologies.common.concur.lock.OReadersWriterSpinLock)
        at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
        at com.orientechnologies.common.concur.lock.OReadersWriterSpinLock.acquireReadLock(OReadersWriterSpinLock.java:143)
        at com.orientechnologies.orient.core.metadata.schema.OSchemaShared.acquireSchemaReadLock(OSchemaShared.java:335)
        at com.orientechnologies.orient.core.metadata.schema.OSchemaShared.countClasses(OSchemaShared.java:178)
        at com.orientechnologies.orient.core.metadata.schema.OSchemaProxy.countClasses(OSchemaProxy.java:57)
        at com.orientechnologies.orient.core.db.OPartitionedDatabasePool$DatabaseDocumentTxPooled.internalOpen(OPartitionedDatabasePool.java:445)
        at com.orientechnologies.orient.core.db.OPartitionedDatabasePool.openDatabase(OPartitionedDatabasePool.java:306)
        at com.orientechnologies.orient.core.db.OPartitionedDatabasePool.acquire(OPartitionedDatabasePool.java:246)
        at in.co.nmsworks.documenttdb.spi.impl.orient.OrientInternal.getDatabase(OrientInternal.java:521)
        at in.co.nmsworks.documenttdb.db.DocDB.createDB(DocDB.java:390)
        at in.co.nmsworks.documenttdb.db.DocDB.<init>(DocDB.java:77)
        at in.co.nmsworks.documenttdb.db.DocDB.<init>(DocDB.java:82)
        at in.co.nmsworks.cygnet.telecom.fault.rcasia.inventory.store.InvWriter.addObjectsToOrientDB(InvWriter.java:980)
        at in.co.nmsworks.cygnet.telecom.fault.rcasia.inventory.builder.CircuitPlugInventoryDataPersister.addObjectsToOrientDB(CircuitPlugInventoryDat
aPersister.java:777)
        - locked <0x000000070b88aad0> (a in.co.nmsworks.cygnet.telecom.fault.rcasia.inventory.builder.CircuitPlugInventoryDataPersister)
        at in.co.nmsworks.cygnet.telecom.fault.rcasia.inventory.builder.CircuitPlugInventoryDataPersister.storeStatus(CircuitPlugInventoryDataPersiste
r.java:768)
        at in.co.nmsworks.cygnet.telecom.fault.rcasia.inventory.queue.InventoryDataBuilderMaster.getInventoryDataBuilderJobs(InventoryDataBuilderMaste
r.java:310)
        at in.co.nmsworks.cygnet.telecom.fault.rcasia.inventory.queue.InventoryDataBuilderMaster.process(InventoryDataBuilderMaster.java:273)
        at in.co.nmsworks.cygnet.telecom.fault.rcasia.inventory.queue.InventoryDataBuilderMaster.run(InventoryDataBuilderMaster.java:211)
        at in.co.nmsworks.util.ShutdownAwareJobFactory$ShutdownAwareRunnable.run(ShutdownAwareJobFactory.java:162)
        at java.lang.Thread.run(Thread.java:745)

Please suggest for the above mentioned issue.

Is there  anything I have to add to my application server please suggest..

Post here for any more information needed.

**Comment by rbaarathi** [comment]
@laa Please suggest on this..

**Comment by laa** [comment]
Hi @rbaarathi it is hard to say. Could you provide full stack trace?

**Comment by rbaarathi** [comment]
[td1.txt](https://github.com/orientechnologies/orientdb/files/4212548/td1.txt)

This is the full thread dump..

**Comment by laa** [comment]
Looks like a deadlock... I am on it.

**Comment by rbaarathi** [comment]
@laa  Ok thanks.. Please suggest some solution..

**Comment by laa** [comment]
It is needed to make changes in code, we will provide new hotfix.

**Comment by rbaarathi** [comment]
So wat should I do now..?

**Comment by laa** [comment]
Please wait a bit till we produce new hotfix with resolved deadlock issue. It should not take too long.

**Comment by rbaarathi** [comment]
FYI.

We have introduced multi threading concept while adding documents to orient database.

We form our own clusters (multiple clusters based on the object size) for each table and each thread will persist data in parallel to each clusters across table in orient.

No 2 threads will access same cluster during writing.

Total configured thread count = 50 / 100 (based on the size)

Using the above mentioned concept we have done orient building and it works fine in our old version. (orient version 2.2.20)

We are using the older version for the past three years.

Now we are trying to reproduce the same using v3.0.26.

**Comment by rbaarathi** [comment]
Hi @laa .. Any update..?

**Comment by laa** [comment]
Hi @rbaarathi could you try this build https://drive.google.com/file/d/1Ufd8de9Ajfmx_TzvWRU0k-yrKT985MZP/view?usp=sharing . If issue is fixed I will put it in hotfix release.

**Comment by rbaarathi** [comment]
I have updated the orient jars that you have shared and trying to build orient database.
Again building got struck.

Please check the thread dump shared and update.
[td2.txt](https://github.com/orientechnologies/orientdb/files/4279634/td2.txt)

**Comment by laa** [comment]
Hi @rbaarathi could you try this build ? https://drive.google.com/file/d/1dEj8JXRfZqJZJrVuDbgC2F8ZgCbZime5/view?usp=sharing

**Comment by rbaarathi** [comment]
Hi @laa 

Thanks for the immediate fix that you have done.

orient 3.0.30-SNAPSHOT build works fine.

I can able to build orient database with latest version and it works.

**Comment by rbaarathi** [comment]
Hi @laa 

Can u please release this build..?

**Comment by tglman** [comment]
Hi @rbaarathi,

The 3.0.30 has been released a while ago, I'm closing this.
Regards
