### ISSUE TITLE
IndexOutOfBoundsException inserting data with "scripts"

### ISSUE THREAD

**Issue by madmac2501** [orientechnologies/orientdb#9144]
## Expected behavior  
There are no exceptions when inserting

## Actual behavior  
`Exception `76F1BE16` in storage `plocal:/opt/orientdb/databases/test`: 3.0.25 - Veloce (build ac37bbb108b048fa9a8fb17d094fc614cb61dce4, branch 3.0.x)
java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
        at java.util.ArrayList.rangeCheck(ArrayList.java:657)
        at java.util.ArrayList.get(ArrayList.java:433)
        at com.orientechnologies.orient.core.storage.index.sbtree.multivalue.v2.Bucket.shrink(Bucket.java:954)
        at com.orientechnologies.orient.core.storage.index.sbtree.multivalue.v2.OCellBTreeMultiValueV2.splitNonRootBucket(OCellBTreeMultiValueV2.java:1325)
        at com.orientechnologies.orient.core.storage.index.sbtree.multivalue.v2.OCellBTreeMultiValueV2.splitBucket(OCellBTreeMultiValueV2.java:1262)
        at com.orientechnologies.orient.core.storage.index.sbtree.multivalue.v2.OCellBTreeMultiValueV2.put(OCellBTreeMultiValueV2.java:323)
        at com.orientechnologies.orient.core.index.engine.v1.OCellBTreeMultiValueIndexEngine.put(OCellBTreeMultiValueIndexEngine.java:175)
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.doPutRidIndexEntry(OAbstractPaginatedStorage.java:2785)
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.putRidIndexEntry(OAbstractPaginatedStorage.java:2751)
        at com.orientechnologies.orient.core.index.OIndexMultiValues.doPutV1(OIndexMultiValues.java:200)
        at com.orientechnologies.orient.core.index.OIndexMultiValues.put(OIndexMultiValues.java:130)
        at com.orientechnologies.orient.core.index.OIndexMultiValues.put(OIndexMultiValues.java:53)
        at com.orientechnologies.orient.core.index.OIndexAbstract.putInSnapshot(OIndexAbstract.java:847)
        at com.orientechnologies.orient.core.index.OIndexAbstract.applyIndexTxEntry(OIndexAbstract.java:693)
        at com.orientechnologies.orient.core.index.OIndexAbstract.addTxOperation(OIndexAbstract.java:665)
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.commitIndexes(OAbstractPaginatedStorage.java:2153)
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.commit(OAbstractPaginatedStorage.java:2081)
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.commit(OAbstractPaginatedStorage.java:1904)
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentAbstract.internalCommit(ODatabaseDocumentAbstract.java:2721)
        at com.orientechnologies.orient.core.storage.impl.local.OMicroTransaction.doCommit(OMicroTransaction.java:363)
        at com.orientechnologies.orient.core.storage.impl.local.OMicroTransaction.commit(OMicroTransaction.java:166)
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentEmbedded.endMicroTransaction(ODatabaseDocumentEmbedded.java:797)
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentEmbedded.executeSaveRecord(ODatabaseDocumentEmbedded.java:787)
        at com.orientechnologies.orient.core.tx.OTransactionNoTx.saveRecord(OTransactionNoTx.java:184)
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentAbstract.saveInternal(ODatabaseDocumentAbstract.java:2088)
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentAbstract.save(ODatabaseDocumentAbstract.java:2050)
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentAbstract.save(ODatabaseDocumentAbstract.java:1940)
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentAbstract.save(ODatabaseDocumentAbstract.java:86)
        at com.orientechnologies.orient.core.sql.executor.SaveElementStep$1.next(SaveElementStep.java:40)
        at com.orientechnologies.orient.core.sql.executor.ConvertToResultInternalStep$1.fetchNextItem(ConvertToResultInternalStep.java:62)
        at com.orientechnologies.orient.core.sql.executor.ConvertToResultInternalStep$1.hasNext(ConvertToResultInternalStep.java:88)
        at com.orientechnologies.orient.core.sql.executor.OUpdateExecutionPlan.executeInternal(OUpdateExecutionPlan.java:47)
        at com.orientechnologies.orient.core.sql.parser.OUpdateStatement.execute(OUpdateStatement.java:169)
        at com.orientechnologies.orient.core.sql.parser.OLetStatement.executeSimple(OLetStatement.java:36)
        at com.orientechnologies.orient.core.sql.executor.OSingleOpExecutionPlan.executeInternal(OSingleOpExecutionPlan.java:99)
        at com.orientechnologies.orient.core.sql.executor.ScriptLineStep.syncPull(ScriptLineStep.java:37)
        at com.orientechnologies.orient.core.sql.executor.OScriptExecutionPlan.executeFull(OScriptExecutionPlan.java:215)
        at com.orientechnologies.orient.core.sql.executor.ForEachStep.syncPull(ForEachStep.java:47)
        at com.orientechnologies.orient.core.sql.executor.OSelectExecutionPlan.fetchNext(OSelectExecutionPlan.java:37)
        at com.orientechnologies.orient.core.sql.executor.OUpdateExecutionPlan.executeInternal(OUpdateExecutionPlan.java:46)
        at com.orientechnologies.orient.core.sql.executor.ScriptLineStep.syncPull(ScriptLineStep.java:33)
        at com.orientechnologies.orient.core.sql.executor.OScriptExecutionPlan.doExecute(OScriptExecutionPlan.java:89)
        at com.orientechnologies.orient.core.sql.executor.OScriptExecutionPlan.fetchNext(OScriptExecutionPlan.java:50)
        at com.orientechnologies.orient.core.sql.parser.OLocalResultSet.fetchNext(OLocalResultSet.java:39)
        at com.orientechnologies.orient.core.sql.parser.OLocalResultSet.<init>(OLocalResultSet.java:30)
        at com.orientechnologies.orient.core.command.OSqlScriptExecutor.executeInternal(OSqlScriptExecutor.java:109)
        at com.orientechnologies.orient.core.command.OSqlScriptExecutor.execute(OSqlScriptExecutor.java:55)
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentEmbedded.execute(ODatabaseDocumentEmbedded.java:637)
        at com.orientechnologies.orient.server.OConnectionBinaryExecutor.executeQuery(OConnectionBinaryExecutor.java:1297)
        at com.orientechnologies.orient.client.remote.message.OQueryRequest.execute(OQueryRequest.java:136)
        at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.sessionRequest(ONetworkProtocolBinary.java:310)
        at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.execute(ONetworkProtocolBinary.java:212)
        at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:69)`

## Steps to reproduce  
My setup is that I'm running an scheduled process that inserts periodically into orientdb using "scripts" using multiple threads. I've been running this for a few days and I found these exceptions. Let me know what info could be helpful to fix this issue. Thanks!

**Comment by laa** [comment]
That is hard to understand from a single exception. Maybe you have logs from the server to check them ?

**Comment by madmac2501** [comment]
I'm sorry but I don't keep these logs, this was when we run OrientDB in a single node. The good thing is that I no longer saw this again as we moved to newer versions in 3 distributed nodes. If there is not enough information to move forward please close the ticket. I'll open a new one it if I see it again.
