### ISSUE TITLE
Getting a new instance of a POJO object with the class containing a single get() method causes a string out of bounds exception

### ISSUE THREAD

**Issue by phinibb** [orientechnologies/orientdb#9145]
## Expected behavior  
OObjectMethodFilter.getfieldname should find all methods that begin with get and set and return a list of these

## Actual behavior  
if the class that it is checking has just as method called get or set, a java.lang.StringIndexOutOfBoundsException: String index out of range: 3 exception is thrown

## Steps to reproduce  
Create a class with a single get() 
Register the class as a POJO using .getEntityManager().registerEntityClass(g)
and try to make an instance of that POJO class using .newInstance(x)

The full exception is below:
java.lang.StringIndexOutOfBoundsException: String index out of range: 3
	at java.lang.String.charAt(String.java:658)
	at com.orientechnologies.orient.object.enhancement.OObjectMethodFilter.getFieldName(OObjectMethodFilter.java:87)
	at com.orientechnologies.orient.object.enhancement.OObjectMethodFilter.getFieldName(OObjectMethodFilter.java:69)
	at com.orientechnologies.orient.object.enhancement.OObjectMethodFilter.isHandled(OObjectMethodFilter.java:41)
	at javassist.util.proxy.ProxyFactory.computeSignature(ProxyFactory.java:1008)
	at javassist.util.proxy.ProxyFactory.createClass(ProxyFactory.java:479)
	at com.orientechnologies.orient.object.enhancement.OObjectEntityEnhancer.getProxiedInstance(OObjectEntityEnhancer.java:97)
	at com.orientechnologies.orient.object.db.OObjectDatabaseTx.newInstance(OObjectDatabaseTx.java:211)
	at com.orientechnologies.orient.object.db.OObjectDatabaseTx.newInstance(OObjectDatabaseTx.java:115)
	at com.company.Database.getNewJavaClassInstance(Database.java:175)

**Comment by phinibb** [comment]
Similar to this topic: https://github.com/orientechnologies/orientdb/issues/3874

The fix in the topic : https://github.com/orientechnologies/orientdb/issues/3874#issuecomment-89764154

seems to workto bypass this issue
