### ISSUE TITLE
orientdb start crash on kubernetes with nfs persistent volume

### ISSUE THREAD

**Issue by dragon9783** [orientechnologies/orientdb#9152]
### OrientDB Version: <version here>  
3.0.22
## Expected behavior  
orientdb start success

## Actual behavior  
orientdb start crash
```
           .
          .`        `
          ,      `:.
         `,`    ,:`
         .,.   :,,
         .,,  ,,,
    .    .,.:::::  ````                                 :::::::::     :::::::::
    ,`   .::,,,,::.,,,,,,`;;                      .:    ::::::::::    :::    :::
    `,.  ::,,,,,,,:.,,.`  `                       .:    :::      :::  :::     :::
     ,,:,:,,,,,,,,::.   `        `         ``     .:    :::      :::  :::     :::
      ,,:.,,,,,,,,,: `::, ,,   ::,::`   : :,::`  ::::   :::      :::  :::    :::
       ,:,,,,,,,,,,::,:   ,,  :.    :   ::    :   .:    :::      :::  :::::::
        :,,,,,,,,,,:,::   ,,  :      :  :     :   .:    :::      :::  :::::::::
  `     :,,,,,,,,,,:,::,  ,, .::::::::  :     :   .:    :::      :::  :::     :::
  `,...,,:,,,,,,,,,: .:,. ,, ,,         :     :   .:    :::      :::  :::     :::
    .,,,,::,,,,,,,:  `: , ,,  :     `   :     :   .:    :::      :::  :::     :::
      ...,::,,,,::.. `:  .,,  :,    :   :     :   .:    :::::::::::   :::     :::
           ,::::,,,. `:   ,,   :::::    :     :   .:    :::::::::     ::::::::::
           ,,:` `,,.
          ,,,    .,`
         ,,.     `,                                              VELOCE
       ``        `.
                 ``                                       www.orientdb.com
                 `

2020-02-25 12:24:15:121 INFO  Detected limit of amount of simultaneously open files is 1048576,  limit of open files for disk cache will be set to 523776 [ONative]
2020-02-25 12:24:15:139 INFO  Loading configuration from: /orientdb/config/orientdb-server-config.xml... [OServerConfigurationLoaderXml]
2020-02-25 12:24:15:335 INFO  OrientDB Server v3.0.22 - Veloce (build 8afc634a2ea9c351898ae57dee8d739ff4851252, branch 3.0.x) is starting up... [OServer]
2020-02-25 12:24:15:390 INFO  16819924992 B/16040 MB/15 GB of physical memory were detected on machine [ONative]
2020-02-25 12:24:15:391 INFO  Soft memory limit for this process is set to -1 B/-1 MB/-1 GB [ONative]
2020-02-25 12:24:15:392 INFO  Hard memory limit for this process is set to -1 B/-1 MB/-1 GB [ONative]
2020-02-25 12:24:15:392 INFO  Path to 'memory' cgroup is '/kubepods/besteffort/podf7ec488c-ba5e-493c-814f-34eff1255dde/38069c461f372fb0b16f96599de91403e70dd4a4285ef8d1bcd9ada776c1c6c7' [ONative]
2020-02-25 12:24:15:395 INFO  Mounting path for memory cgroup controller is '/sys/fs/cgroup/memory' [ONative]
2020-02-25 12:24:15:395 INFO  Can not find '/sys/fs/cgroup/memory/kubepods/besteffort/podf7ec488c-ba5e-493c-814f-34eff1255dde/38069c461f372fb0b16f96599de91403e70dd4a4285ef8d1bcd9ada776c1c6c7' path for memory cgroup, it is supposed that process is running in container, will try to read root '/sys/fs/cgroup/memory' memory cgroup data [ONative]
2020-02-25 12:24:15:396 INFO  cgroup soft memory limit is 9223372036854771712 B/8796093022207 MB/8589934591 GB [ONative]
2020-02-25 12:24:15:396 INFO  cgroup hard memory limit is 9223372036854771712 B/8796093022207 MB/8589934591 GB [ONative]
2020-02-25 12:24:15:397 INFO  Detected memory limit for current process is 16819924992 B/16040 MB/15 GB [ONative]
2020-02-25 12:24:15:398 INFO  JVM can use maximum 1979MB of heap memory [OMemoryAndLocalPaginatedEnginesInitializer]
2020-02-25 12:24:15:398 INFO  Because OrientDB is running inside a container 12% of memory will be left unallocated according to the setting 'memory.leftToContainer' not taking into account heap memory [OMemoryAndLocalPaginatedEnginesInitializer]
2020-02-25 12:24:15:400 INFO  OrientDB auto-config DISKCACHE=12,136MB (heap=1,979MB os=16,040MB) [orientechnologies]
2020-02-25 12:24:15:403 INFO  System is started under an effective user : `root` [OEngineLocalPaginated]
2020-02-25 12:24:15:403 INFO  Allocation of 184467 pages. [OEngineLocalPaginated]
2020-02-25 12:24:16:034 INFO  WAL maximum segment size is set to 6,144 MB [OrientDBDistributed]
2020-02-25 12:24:16:036 INFO  Databases directory: /orientdb/databases [OServer]
2020-02-25 12:24:16:067 INFO  Creating the system database 'OSystem' for current server [OSystemDatabase]
2020-02-25 12:24:16:111 INFO  Direct IO for WAL located in /orientdb/databases/OSystem is allowed with block size 1048576 bytes. [OCASDiskWriteAheadLog]
2020-02-25 12:24:16:112 INFO  Page size for WAL located in /orientdb/databases/OSystem is set to 1048576 bytes. [OCASDiskWriteAheadLog]Can not open file using Linux API, Java FileChannel will be used instead
com.sun.jna.LastErrorException: [22] Invalid argument
	at com.sun.jna.Native.invokeInt(Native Method)
	at com.sun.jna.Function.invoke(Function.java:419)
	at com.sun.jna.Function.invoke(Function.java:354)
	at com.sun.jna.Library$Handler.invoke(Library.java:244)
	at com.sun.proxy.$Proxy2.open(Unknown Source)
	at com.orientechnologies.common.jna.ONative.open(ONative.java:234)
	at com.orientechnologies.orient.core.storage.impl.local.paginated.wal.cas.OWALFile.createWriteWALFile(OWALFile.java:29)
	at com.orientechnologies.orient.core.storage.impl.local.paginated.wal.cas.OCASDiskWriteAheadLog$RecordsWriter.run(OCASDiskWriteAheadLog.java:1875)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Error during WAL writing
java.lang.NullPointerException
	at com.orientechnologies.orient.core.storage.impl.local.paginated.wal.cas.OCASDiskWriteAheadLog$RecordsWriter.run(OCASDiskWriteAheadLog.java:1909)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Exception in thread 'OrientDB WAL Flush Task'
java.lang.NullPointerException
	at com.orientechnologies.orient.core.storage.impl.local.paginated.wal.cas.OCASDiskWriteAheadLog$RecordsWriter.run(OCASDiskWriteAheadLog.java:1909)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Exception during WAL flush
java.util.concurrent.ExecutionException: java.lang.NullPointerException
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at com.orientechnologies.orient.core.storage.impl.local.paginated.wal.cas.OCASDiskWriteAheadLog.doFlush(OCASDiskWriteAheadLog.java:1517)
	at com.orientechnologies.orient.core.storage.impl.local.paginated.wal.cas.OCASDiskWriteAheadLog.log(OCASDiskWriteAheadLog.java:1119)
	at com.orientechnologies.orient.core.storage.impl.local.paginated.wal.cas.OCASDiskWriteAheadLog.<init>(OCASDiskWriteAheadLog.java:312)
	at com.orientechnologies.orient.core.storage.disk.OLocalPaginatedStorage.initWalAndDiskCache(OLocalPaginatedStorage.java:589)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.create(OAbstractPaginatedStorage.java:585)
	at com.orientechnologies.orient.core.storage.disk.OLocalPaginatedStorage.create(OLocalPaginatedStorage.java:155)
	at com.orientechnologies.orient.core.db.OrientDBEmbedded.internalCreate(OrientDBEmbedded.java:429)
	at com.orientechnologies.orient.core.db.OrientDBEmbedded.create(OrientDBEmbedded.java:379)
	at com.orientechnologies.orient.server.OServer.createDatabase(OServer.java:1236)
	at com.orientechnologies.orient.server.OSystemDatabase.init(OSystemDatabase.java:160)
	at com.orientechnologies.orient.server.OSystemDatabase.<init>(OSystemDatabase.java:49)
	at com.orientechnologies.orient.server.OServer.initSystemDatabase(OServer.java:1212)
	at com.orientechnologies.orient.server.OServer.activate(OServer.java:421)
	at com.orientechnologies.orient.server.OServerMain$1.run(OServerMain.java:48)
Caused by: java.lang.NullPointerException
	at com.orientechnologies.orient.core.storage.impl.local.paginated.wal.cas.OCASDiskWriteAheadLog$RecordsWriter.run(OCASDiskWriteAheadLog.java:1909)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Exception `69FF5881` in storage `plocal:/orientdb/databases/OSystem`: 3.0.22 - Veloce (build 8afc634a2ea9c351898ae57dee8d739ff4851252, branch 3.0.x)
java.lang.IllegalStateException: java.util.concurrent.ExecutionException: java.lang.NullPointerException
	at com.orientechnologies.orient.core.storage.impl.local.paginated.wal.cas.OCASDiskWriteAheadLog.doFlush(OCASDiskWriteAheadLog.java:1520)
	at com.orientechnologies.orient.core.storage.impl.local.paginated.wal.cas.OCASDiskWriteAheadLog.log(OCASDiskWriteAheadLog.java:1119)
	at com.orientechnologies.orient.core.storage.impl.local.paginated.wal.cas.OCASDiskWriteAheadLog.<init>(OCASDiskWriteAheadLog.java:312)
	at com.orientechnologies.orient.core.storage.disk.OLocalPaginatedStorage.initWalAndDiskCache(OLocalPaginatedStorage.java:589)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.create(OAbstractPaginatedStorage.java:585)
	at com.orientechnologies.orient.core.storage.disk.OLocalPaginatedStorage.create(OLocalPaginatedStorage.java:155)
	at com.orientechnologies.orient.core.db.OrientDBEmbedded.internalCreate(OrientDBEmbedded.java:429)
	at com.orientechnologies.orient.core.db.OrientDBEmbedded.create(OrientDBEmbedded.java:379)
	at com.orientechnologies.orient.server.OServer.createDatabase(OServer.java:1236)
	at com.orientechnologies.orient.server.OSystemDatabase.init(OSystemDatabase.java:160)
	at com.orientechnologies.orient.server.OSystemDatabase.<init>(OSystemDatabase.java:49)
	at com.orientechnologies.orient.server.OServer.initSystemDatabase(OServer.java:1212)
	at com.orientechnologies.orient.server.OServer.activate(OServer.java:421)
	at com.orientechnologies.orient.server.OServerMain$1.run(OServerMain.java:48)
Caused by: java.util.concurrent.ExecutionException: java.lang.NullPointerException
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at com.orientechnologies.orient.core.storage.impl.local.paginated.wal.cas.OCASDiskWriteAheadLog.doFlush(OCASDiskWriteAheadLog.java:1517)
	... 13 more
Caused by: java.lang.NullPointerException
	at com.orientechnologies.orient.core.storage.impl.local.paginated.wal.cas.OCASDiskWriteAheadLog$RecordsWriter.run(OCASDiskWriteAheadLog.java:1909)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

## Steps to reproduce  
1. install kubernetes cluster
2. setup nfs storage class
3. run orientdb with nfs persistent volume

**Comment by laa** [comment]
Hi please disable direct io using this system property -storage.wal.allowDirectIO=false.

**Comment by dragon9783** [comment]
ok, i will try now, thanks a lot
