### ISSUE TITLE
Hazlecast Issue in Distributed Mode

### ISSUE THREAD

**Issue by mmacfadden** [orientechnologies/orientdb#9168]
## Expected behavior  
The server should start and cluster with statically defined TCP/IP Hazlecast hosts.

## Actual behavior 
The server fails to start with the following exception:
```
Caused by: java.net.UnknownHostException: 192.168.65.2:2435: invalid IPv6 address
       at java.net.InetAddress.getAllByName(InetAddress.java:1170)
       at java.net.InetAddress.getAllByName(InetAddress.java:1127)
       at com.orientechnologies.orient.client.binary.OChannelBinaryClientAbstract.<init>(OChannelBinaryClientAbstract.java:65)
       at com.orientechnologies.orient.client.binary.OChannelBinarySynchClient.<init>(OChannelBinarySynchClient.java:32)
       at com.orientechnologies.orient.server.distributed.ORemoteServerChannel.connect(ORemoteServerChannel.java:122)
       at com.orientechnologies.orient.server.distributed.ORemoteServerChannel.<init>(ORemoteServerChannel.java:90)
       at com.orientechnologies.orient.server.distributed.ORemoteServerController.<init>(ORemoteServerController.java:53)
       at com.orientechnologies.orient.server.hazelcast.OHazelcastPlugin.getRemoteServer(OHazelcastPlugin.java:683)
       at com.orientechnologies.orient.server.hazelcast.OHazelcastPlugin.startup(OHazelcastPlugin.java:287)
```

## Steps to reproduce  
We used the config below and then start up using the `dserver.sh`.  It seems like the issue is that hazlecast allows you to specify host and ports like this:

```
<member>192.168.65.2:2435</member>
```

OrientDB seems to be getting this record and calling `java.net.InetAddress.getAllByName` which does not like that string.

**Node 1 Config:**
```xml
<hazelcast
	xsi:schemaLocation="http://www.hazelcast.com/schema/config hazelcast-config-3.3.xsd"
	xmlns="http://www.hazelcast.com/schema/config" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<group>
		<name>orientdb</name>
		<password>orientdb</password>
	</group>
	<network>
	        <public-address>192.168.65.2:2434</public-address>
		<port auto-increment="false">2434</port>
		<join>
			<multicast enabled="false">
				<multicast-group>235.1.1.1</multicast-group>
				<multicast-port>2434</multicast-port>
			</multicast>
			<tcp-ip enabled="true">
                            <member>192.168.65.2:2435</member>
                         </tcp-ip>
		</join>
	</network>
	<executor-service>
		<pool-size>16</pool-size>
	</executor-service>
</hazelcast>
```

**Node 2 Config:**
```xml
<hazelcast
	xsi:schemaLocation="http://www.hazelcast.com/schema/config hazelcast-config-3.3.xsd"
	xmlns="http://www.hazelcast.com/schema/config" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<group>
		<name>orientdb</name>
		<password>orientdb</password>
	</group>
	<network>
	        <public-address>192.168.65.2:2435</public-address>
		<port auto-increment="false">2435</port>
		<join>
			<multicast enabled="false">
				<multicast-group>235.1.1.1</multicast-group>
				<multicast-port>2434</multicast-port>
			</multicast>
			<tcp-ip enabled="true">
                         </tcp-ip>
		</join>
	</network>
	<executor-service>
		<pool-size>16</pool-size>
	</executor-service>
</hazelcast>
```

**Comment by bulanan** [comment]
I also have this problem, any estimation when it will be fixed or any workaround?
