### ISSUE TITLE
NPE due to incorrect condition in java

### ISSUE THREAD

**Issue by PhantomYdn** [orientechnologies/orientdb#9169]
Hello,

Please check the following 2 lines of code
https://github.com/orientechnologies/orientdb/blob/add35f9de6cc3f50f630a15d96e1a5df32007aeb/core/src/main/java/com/orientechnologies/orient/core/storage/impl/local/statistic/OSessionStoragePerformanceStatistic.java#L1197-L1198

As you can see: you can get easily NPE if walCountersHolder==null (our case).

Full exception:
```
Uncaught exception in thread 'OrientDB Write Cache Flush Task (Orienteer)'
java.lang.NullPointerException
        at com.orientechnologies.orient.core.storage.impl.local.statistic.OSessionStoragePerformanceStatistic.makeSnapshotIfNeeded(OSessionStoragePerformanceStatistic.java:1236)
        at com.orientechnologies.orient.core.storage.impl.local.statistic.OSessionStoragePerformanceStatistic.stopWriteCacheFlushTimer(OSessionStoragePerformanceStatistic.java:716)
        at com.orientechnologies.orient.core.storage.cache.local.OWOWCache$PeriodicFlushTask.run(OWOWCache.java:1931)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```

**Comment by PhantomYdn** [comment]
Btw, NPE is also possible if monitoring was not started for some reason (exception and etc), but stopMonitoring has been invoked due to the following construction:

https://github.com/orientechnologies/orientdb/blob/3d0100489243d1408d9ade83724db689d02d548f/core/src/main/java/com/orientechnologies/orient/core/storage/impl/local/statistic/OPerformanceStatisticManager.java#L291-L301

I think it will be safer if `stopMonitoring()` will exit immediately if monitoring was not enabled.

**Comment by PhantomYdn** [comment]
I'm sorry, but it seems that OPerformanceStatisticManager was not fully tested, because due to mentioned NPE - it's not possible to get OWOWCache$PeriodicFlushTask running - it stops execution after first Exception (btw - why? Critical things, imho, should be retryable) - so if performance monitoring was started - WOW Cache stops immediately flushing. Am I missing something?

**Comment by laa** [comment]
Fixed

**Comment by PhantomYdn** [comment]
Nice fix;) Thank you!
