### ISSUE TITLE
[Bug] [3.1.0] [works in 3.1.0-M3] [Client] NPE on updating vertex after edge exist

### ISSUE THREAD

**Issue by matanshukry** [orientechnologies/orientdb#9179]
## Expected behavior
Not to throw an NPE

## Actual behavior
throw an npe.
Stacktrace:

```
java.lang.NullPointerException: null
	at com.orientechnologies.orient.core.serialization.serializer.record.binary.ODocumentSerializerDelta.serializeDeltaLinkBag(ODocumentSerializerDelta.java:607) ~[orientdb-core-3.1.0-beta1.jar:3.1.0-beta1]
	at com.orientechnologies.orient.core.serialization.serializer.record.binary.ODocumentSerializerDelta.serializeDeltaValue(ODocumentSerializerDelta.java:585) ~[orientdb-core-3.1.0-beta1.jar:3.1.0-beta1]
	at com.orientechnologies.orient.core.serialization.serializer.record.binary.ODocumentSerializerDelta.serializeDeltaEntry(ODocumentSerializerDelta.java:558) ~[orientdb-core-3.1.0-beta1.jar:3.1.0-beta1]
	at com.orientechnologies.orient.core.serialization.serializer.record.binary.ODocumentSerializerDelta.serializeDelta(ODocumentSerializerDelta.java:542) ~[orientdb-core-3.1.0-beta1.jar:3.1.0-beta1]
	at com.orientechnologies.orient.core.serialization.serializer.record.binary.ODocumentSerializerDelta.serializeDelta(ODocumentSerializerDelta.java:66) ~[orientdb-core-3.1.0-beta1.jar:3.1.0-beta1]
	at com.orientechnologies.orient.client.remote.message.OCommit38Request.<init>(OCommit38Request.java:65) ~[orientdb-client-3.1.0-beta1.jar:3.1.0-beta1]
	at com.orientechnologies.orient.client.remote.OStorageRemote.commit(OStorageRemote.java:1009) ~[orientdb-client-3.1.0-beta1.jar:3.1.0-beta1]
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentAbstract.internalCommit(ODatabaseDocumentAbstract.java:2326) [orientdb-core-3.1.0-beta1.jar:3.1.0-beta1]
	at com.orientechnologies.orient.core.tx.OTransactionOptimistic.doCommit(OTransactionOptimistic.java:554) ~[orientdb-core-3.1.0-beta1.jar:3.1.0-beta1]
	at com.orientechnologies.orient.core.tx.OTransactionOptimistic.commit(OTransactionOptimistic.java:105) ~[orientdb-core-3.1.0-beta1.jar:3.1.0-beta1]
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentAbstract.commit(ODatabaseDocumentAbstract.java:1882) [orientdb-core-3.1.0-beta1.jar:3.1.0-beta1]
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentAbstract.commit(ODatabaseDocumentAbstract.java:1852) [orientdb-core-3.1.0-beta1.jar:3.1.0-beta1]
```

I can also add that `timeline` variable was null in there.

## Steps to reproduce  

- The NPE happens when I run a software I made that creates 100 vertices and then creates, and then for each one creates 1-5 (random) edges between them.
- Each call is, both to create the vertices and the edges, is separate and has a `.begin()` before it and `.commit()` after it
- the query it self isn't that complex, it uses 2 sub select to choose the vertices and set some data, nothing too special

## Notes

As mentioned in the title, there is no NPE when using the older version `3.1.0-M3`

**Comment by luigidellaquila** [comment]
Hi @matanshukry 

Did you have a chance to try it on latest snapshot? There is a chance that it's already fixed

https://oss.sonatype.org/content/repositories/snapshots/com/orientechnologies/orientdb-community/3.1.0-SNAPSHOT/

Thanks

Luigi

**Comment by matanshukry** [comment]
@luigidellaquila not sure how to try it; I'm using source for the server and maven central (gradle) for the client, but I can't find any snapshot (or relevant) version in maven central nor any snapshot (or relevant) tag/branch

**Comment by tglman** [comment]
Hi @matanshukry,

The 3.1.0 has been just released could you try with that version ?

Regards

**Comment by matanshukry** [comment]
Just realized this is an older one and I've created a duplicate issue #9276 
It definitely still exist though.

Let me know which one to close

**Comment by matanshukry** [comment]
Update (worse): the bug doesn't actually happen on the `CREATE EDGE` query, but rather on an update query after there is an edge. ANY update query on the user.
