### ISSUE TITLE
Create+delete vertex with unique index inside transaction causes NPE

### ISSUE THREAD

**Issue by arch7tect** [orientechnologies/orientdb#9185]
## Expected behavior  
batch executes without errors  

## Actual behavior  
NPE occures  

## Steps to reproduce  
drop class _Object if exists unsafe;
create class _Object extends V;
create property _Object.name STRING;
CREATE INDEX _Object.name UNIQUE;
begin;
insert into _Object(name) values ('c');
let top = (select from _Object where name='c');
delete vertex $top;
commit;
return $top;

**Comment by luigidellaquila** [comment]
Adding the full stack trace for reference

```
com.orientechnologies.orient.core.exception.OStorageException: Exception during execution of component operation inside of storage testq
	DB name="testq"
	at com.orientechnologies.orient.core.storage.impl.local.paginated.atomicoperations.OAtomicOperationsManager.calculateInsideComponentOperation(OAtomicOperationsManager.java:220)
	at com.orientechnologies.orient.core.storage.impl.local.paginated.atomicoperations.OAtomicOperationsManager.calculateInsideComponentOperation(OAtomicOperationsManager.java:209)
	at com.orientechnologies.orient.core.storage.impl.local.paginated.base.ODurableComponent.calculateInsideComponentOperation(ODurableComponent.java:99)
	at com.orientechnologies.orient.core.storage.index.sbtree.singlevalue.OCellBTreeSingleValue.update(OCellBTreeSingleValue.java:209)
	at com.orientechnologies.orient.core.storage.index.sbtree.singlevalue.OCellBTreeSingleValue.validatedPut(OCellBTreeSingleValue.java:204)
	at com.orientechnologies.orient.core.index.engine.v1.OCellBTreeSingleValueIndexEngine.validatedPut(OCellBTreeSingleValueIndexEngine.java:137)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.doValidatedPutIndexValue(OAbstractPaginatedStorage.java:3348)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.validatedPutIndexValue(OAbstractPaginatedStorage.java:3308)
	at com.orientechnologies.orient.core.index.OIndexUnique.doPut(OIndexUnique.java:91)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.applyTxChanges(OAbstractPaginatedStorage.java:2541)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.commitIndexes(OAbstractPaginatedStorage.java:2523)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.commit(OAbstractPaginatedStorage.java:2453)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.commit(OAbstractPaginatedStorage.java:2274)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentAbstract.internalCommit(ODatabaseDocumentAbstract.java:2702)
	at com.orientechnologies.orient.core.tx.OTransactionOptimistic.doCommit(OTransactionOptimistic.java:533)
	at com.orientechnologies.orient.core.tx.OTransactionOptimistic.commit(OTransactionOptimistic.java:103)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentAbstract.commit(ODatabaseDocumentAbstract.java:2183)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentAbstract.commit(ODatabaseDocumentAbstract.java:2153)
	at com.orientechnologies.orient.core.sql.parser.OCommitStatement.executeSimple(OCommitStatement.java:30)
	at com.orientechnologies.orient.core.sql.executor.OSingleOpExecutionPlan.executeInternal(OSingleOpExecutionPlan.java:99)
	at com.orientechnologies.orient.core.sql.executor.ScriptLineStep.syncPull(ScriptLineStep.java:37)
	at com.orientechnologies.orient.core.sql.executor.OScriptExecutionPlan.executeUntilReturn(OScriptExecutionPlan.java:188)
	at com.orientechnologies.orient.core.sql.executor.OScriptExecutionPlan.doExecute(OScriptExecutionPlan.java:86)
	at com.orientechnologies.orient.core.sql.executor.OScriptExecutionPlan.fetchNext(OScriptExecutionPlan.java:50)
	at com.orientechnologies.orient.core.sql.parser.OLocalResultSet.fetchNext(OLocalResultSet.java:39)
	at com.orientechnologies.orient.core.sql.parser.OLocalResultSet.<init>(OLocalResultSet.java:30)
	at com.orientechnologies.orient.core.command.OSqlScriptExecutor.executeInternal(OSqlScriptExecutor.java:114)
	at com.orientechnologies.orient.core.command.OSqlScriptExecutor.execute(OSqlScriptExecutor.java:45)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentEmbedded.execute(ODatabaseDocumentEmbedded.java:618)
	at com.orientechnologies.orient.server.network.protocol.http.command.post.OServerCommandPostBatch.execute(OServerCommandPostBatch.java:203)
	at com.orientechnologies.orient.server.network.protocol.http.ONetworkProtocolHttpAbstract.service(ONetworkProtocolHttpAbstract.java:228)
	at com.orientechnologies.orient.server.network.protocol.http.ONetworkProtocolHttpAbstract.execute(ONetworkProtocolHttpAbstract.java:707)
	at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:69)
Caused by: java.lang.NullPointerException
	at com.orientechnologies.orient.core.index.OIndexUnique.lambda$new$0(OIndexUnique.java:56)
	at com.orientechnologies.orient.core.storage.index.sbtree.singlevalue.OCellBTreeSingleValue.lambda$update$1(OCellBTreeSingleValue.java:249)
	at com.orientechnologies.orient.core.storage.impl.local.paginated.atomicoperations.OAtomicOperationsManager.calculateInsideComponentOperation(OAtomicOperationsManager.java:217)
	... 32 more
```
