### ISSUE TITLE
NullPointerException when comitting tx after deleting a document

### ISSUE THREAD

**Issue by diegomtassis** [orientechnologies/orientdb#9198]
We are migrating one of our applications from OrientDB 2.2.37 to 3.0.30.

We have several integration tests failing, all of them follow the same pattern:

1. A transaction is begun
2. A document is created and saved
3. The document is deleted
4. The transaction is committed

All the tests pass with 2.2.37, but with 3.0.30 the commit throws a NullPointerException.

The stacktrace:

`Caused by: java.lang.NullPointerException
	at com.orientechnologies.orient.core.index.OIndexUnique.lambda$new$0(OIndexUnique.java:56)
	at com.orientechnologies.orient.core.storage.index.hashindex.local.OLocalHashTable.doPut(OLocalHashTable.java:1235)
	at com.orientechnologies.orient.core.storage.index.hashindex.local.OLocalHashTable.lambda$put$5(OLocalHashTable.java:1166)
	at com.orientechnologies.orient.core.storage.impl.local.paginated.atomicoperations.OAtomicOperationsManager.calculateInsideComponentOperation(OAtomicOperationsManager.java:217)
	... 72 more`

`SEVERE: $ANSI{green {db=AbstractOrientDBResourceRepositoryWithRealResourcesIT}} Error on transaction commit `594131F2`
com.orientechnologies.orient.core.exception.OStorageException: Exception during execution of component operation inside of storage AbstractOrientDBResourceRepositoryWithRealResourcesIT
	DB name="AbstractOrientDBResourceRepositoryWithRealResourcesIT"
	at com.orientechnologies.orient.core.storage.impl.local.paginated.atomicoperations.OAtomicOperationsManager.calculateInsideComponentOperation(OAtomicOperationsManager.java:220)
	at com.orientechnologies.orient.core.storage.impl.local.paginated.atomicoperations.OAtomicOperationsManager.calculateInsideComponentOperation(OAtomicOperationsManager.java:209)
	at com.orientechnologies.orient.core.storage.impl.local.paginated.base.ODurableComponent.calculateInsideComponentOperation(ODurableComponent.java:99)
	at com.orientechnologies.orient.core.storage.index.hashindex.local.OLocalHashTable.put(OLocalHashTable.java:1148)
	at com.orientechnologies.orient.core.storage.index.hashindex.local.OLocalHashTable.validatedPut(OLocalHashTable.java:256)
	at com.orientechnologies.orient.core.storage.index.engine.OHashTableIndexEngine.validatedPut(OHashTableIndexEngine.java:183)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.doValidatedPutIndexValue(OAbstractPaginatedStorage.java:3344)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.validatedPutIndexValue(OAbstractPaginatedStorage.java:3308)
	at com.orientechnologies.orient.core.index.OIndexUnique.doPut(OIndexUnique.java:91)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.applyTxChanges(OAbstractPaginatedStorage.java:2541)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.commitIndexes(OAbstractPaginatedStorage.java:2523)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.commit(OAbstractPaginatedStorage.java:2453)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.commit(OAbstractPaginatedStorage.java:2274)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentAbstract.internalCommit(ODatabaseDocumentAbstract.java:2702)
	at com.orientechnologies.orient.core.tx.OTransactionOptimistic.doCommit(OTransactionOptimistic.java:533)
	at com.orientechnologies.orient.core.tx.OTransactionOptimistic.commit(OTransactionOptimistic.java:103)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentAbstract.commit(ODatabaseDocumentAbstract.java:2183)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentAbstract.commit(ODatabaseDocumentAbstract.java:2153)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.commit(ODatabaseDocumentTx.java:729)`

**Comment by laa** [comment]
Fixed in https://github.com/orientechnologies/orientdb/issues/9185
