### ISSUE TITLE
Exception in commit when Live Query running

### ISSUE THREAD

**Issue by pkendall64** [orientechnologies/orientdb#9200]
## Expected behavior  
Adding edges should work without failure when a live query is running

## Actual behavior  
We have a live query in progress and read a vertex from the database that has some edges to other vertices. We then add another vertex and an edge to this already existing vertex that has other edges and we get the following exception.

```
	Suppressed: com.orientechnologies.orient.core.exception.OSerializationException: Cannot read transaction record from the network. Transaction aborted
	DB name="test"
		at com.orientechnologies.orient.server.tx.OTransactionOptimisticServer.begin(OTransactionOptimisticServer.java:208)
		at com.orientechnologies.orient.core.db.document.ODatabaseDocumentAbstract.rawBegin(ODatabaseDocumentAbstract.java:1243)
		at com.orientechnologies.orient.server.OConnectionBinaryExecutor.executeCommit37(OConnectionBinaryExecutor.java:1269)
		at com.orientechnologies.orient.client.remote.message.OCommit37Request.execute(OCommit37Request.java:124)
		at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.sessionRequest(ONetworkProtocolBinary.java:310)
		at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.execute(ONetworkProtocolBinary.java:212)
		at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:69)
	Caused by: com.orientechnologies.orient.core.exception.ODatabaseException: Error on saving record #57:0
	DB name="test"
		at com.orientechnologies.orient.server.tx.OTransactionOptimisticServer.addRecord(OTransactionOptimisticServer.java:442)
		at com.orientechnologies.orient.server.tx.OTransactionOptimisticServer.begin(OTransactionOptimisticServer.java:158)
		... 6 more
	Caused by: java.lang.IllegalArgumentException: Invalid property value for OResult: [#25:0] - com.orientechnologies.orient.core.db.record.ridbag.ORidBag
		at com.orientechnologies.orient.core.sql.executor.OResultInternal.checkType(OResultInternal.java:67)
		at com.orientechnologies.orient.core.sql.executor.OResultInternal.setProperty(OResultInternal.java:40)
		at com.orientechnologies.orient.core.query.live.OLiveQueryHookV2.calculateBefore(OLiveQueryHookV2.java:232)
		at com.orientechnologies.orient.core.query.live.OLiveQueryHookV2.addOp(OLiveQueryHookV2.java:191)
		at com.orientechnologies.orient.core.db.document.ODatabaseDocumentEmbedded.afterUpdateOperations(ODatabaseDocumentEmbedded.java:1032)
		at com.orientechnologies.orient.server.tx.OTransactionOptimisticServer.addRecord(OTransactionOptimisticServer.java:391)
		... 7 more
	[CIRCULAR REFERENCE:com.orientechnologies.orient.core.exception.ODatabaseException: Error on saving record #57:0
	DB name="test"]
```

## Steps to reproduce  
I have created a test case which can be added to `OrientDBRemoteTest` that shows the exact problem.

```
  @Test
  public void testLiveModification() throws InterruptedException {
    factory.create("test", ODatabaseType.MEMORY);
    ODatabasePool p = new ODatabasePool(factory, "test", "admin", "admin");

    ODatabaseSession db = p.acquire();
    OClass v = db.getMetadata().getSchema().getClass(OClass.VERTEX_CLASS_NAME);
    OClass e = db.getMetadata().getSchema().getClass(OClass.EDGE_CLASS_NAME);
    db.getMetadata().getSchema().createClass("other", v);
    db.getMetadata().getSchema().createClass("test", v);
    db.getMetadata().getSchema().createClass("test2", v);
    db.getMetadata().getSchema().createClass("testedge", e);
    OLiveQueryResultListener listener = new OLiveQueryResultListener () {
      @Override
      public void onCreate(ODatabaseDocument database, OResult data) {
      }

      @Override
      public void onUpdate(ODatabaseDocument database, OResult before, OResult after) {
      }

      @Override
      public void onDelete(ODatabaseDocument database, OResult data) {
      }

      @Override
      public void onError(ODatabaseDocument database, OException exception) {
      }

      @Override
      public void onEnd(ODatabaseDocument database) {
      }
    };
    db.close();

    db = p.acquire();
    db.begin();
    db.newVertex("other").save();
    db.commit();
    db.close();

    OLiveQueryMonitor monitor = p.acquire().live("select from other", listener);
    Assert.assertNotNull(monitor);

    db = p.acquire();
    db.begin();
    OVertex vt10 = db.newVertex("test2").save();
    OVertex vt11 = db.newVertex("test").save();
    OVertex vt12 = db.newVertex("test").save();
    vt10.addEdge(vt11).save();
    vt10.addEdge(vt12).save();
    db.commit();
    db.close();

    db = p.acquire();
    db.begin();
    OResultSet rs = db.query("select from test");
    Object[] vs = rs.vertexStream().toArray();
    rs.close();
    OVertex vt2 = db.newVertex("test2").save();
    for (int i=0 ; i<vs.length ; i++) {
      ((OVertex)vs[i]).addEdge(vt2, "testedge").save();
    }
    db.commit();
    db.close();

    p.close();
  }
```

**Comment by luigidellaquila** [comment]
Hi @pkendall64 

Thanks for the PR, it fixes the issue

Closing, thanks!

Luigi
