### ISSUE TITLE
Orientdb fails to connect in distributed mode with multiple orientdb pods

### ISSUE THREAD

**Issue by akshay-mahakalkar** [orientechnologies/orientdb#9228]
## Expected behavior  
When I have created orientdb replication on kubernetes cluster with hazecaste plugin and statefulsets of kubernetes. To create the replication I simply use following helm chart 
[Orientdb Helm chart](https://github.com/helm/charts/tree/master/incubator/orientdb)
I have set the chart to create 2 replicas of orientdb in distributed mode.
When I try to enter data via console from container of one pod, it works properly.
When I try to access from nodejs program using orientjs. It should create a database and create a class. following is my code.
```
const OrientDBClient = require("orientjs").OrientDBClient;
const Orientjs = require('orientjs');
console.log('Running test scripts')
async function dbTest() {
 try {
 console.log("Attempting to start DB");
 let dbConfig = {
 "host": 'orientdbservice-svc',
 "port": 2424,
 "username": 'root',
 "password": 'qwertyuiop',
 "name": "testdb",
 "user": 'root',
 "type": 'graph',
 "storage": 'plocal',
 "useToken": true,
 "servers": [{host: 'orientdbservice-svc', port: 2424}],
 "pool": { max: 10 }
 };
 let server = Orientjs(dbConfig);
 console.log("Connection Established!");
 let createDB = await server.create(dbConfig).then(()=>{
    console.log("DB created");
});
 server.close();
 let client = await OrientDBClient.connect(dbConfig);
 let pool = await client.sessions(dbConfig);
 console.log("Attempting to start Inserting data");
 let db = await pool.acquire();
 db.create('CLASS', `Player`).one().then(()=>{
   console.log("Data inserted Successfully");
   });
   db.close();
   await pool.close();
   await client.close();
   } catch (error) {
   console.log("Error while Process", error);
   }
}
dbTest();
```
## Actual behavior  
It throws error
```
Error while Process { OrientDB.RequestError: missing session and token
    at child.Operation.parseError (/usr/src/app/node_modules/orientjs/lib/client/network/protocol37/operation.js:1247:13)
    at child.Operation.consume (/usr/src/app/node_modules/orientjs/lib/client/network/protocol37/operation.js:571:35)
    at ONetworkConnection.Connection.process (/usr/src/app/node_modules/orientjs/lib/client/network/conn.js:462:17)
    at ONetworkConnection.Connection.handleSocketData (/usr/src/app/node_modules/orientjs/lib/client/network/conn.js:344:20)
    at Socket.emit (events.js:182:13)
    at addChunk (_stream_readable.js:283:12)
    at readableAddChunk (_stream_readable.js:264:11)
    at Socket.Readable.push (_stream_readable.js:219:10)
    at TCP.onread (net.js:639:20)
  name: 'OrientDB.RequestError',
  message: 'missing session and token',
  data: {},
  isMVCC: [Function],
  isTokenException: [Function],
  previous: [],
  code: 5,
  identifier: 0,
  id: 1,
  type:
   'com.orientechnologies.orient.enterprise.channel.binary.OTokenSecurityException',
  hasMore: 0 }
```
## Steps to reproduce  
1. Install the helm chart given in the above link with 2 pods.
2. create a pod with image that can run nodejs script.
3. push the script inside container.
## Tests to check
1. When the above nodejs script run with just one orientdb pod it works perfect.
2. When the above nodejs script run with 2 orientdb pods, it fails with following error.
```
Running test scripts
Attempting to start DB
Connection Established!
DB created
Attempting to start Inserting data
Unhandled rejection Error: pool is draining and cannot accept work
    at Pool.acquire (/usr/src/app/node_modules/generic-pool/lib/Pool.js:436:9)
    at Promise (/usr/src/app/node_modules/orientjs/lib/client/pool/index.js:36:10)
    at Promise._execute (/usr/src/app/node_modules/orientjs/node_modules/bluebird/js/release/debuggability.js:313:9)
    at Promise._resolveFromExecutor (/usr/src/app/node_modules/orientjs/node_modules/bluebird/js/release/promise.js:488:18)
    at new Promise (/usr/src/app/node_modules/orientjs/node_modules/bluebird/js/release/promise.js:79:10)
    at ONetworkPool.acquire (/usr/src/app/node_modules/orientjs/lib/client/pool/index.js:34:12)
    at ONetworkBinary.acquireConnection (/usr/src/app/node_modules/orientjs/lib/client/network/binary.js:31:22)
    at SessionManager.acquireSession (/usr/src/app/node_modules/orientjs/lib/client/database/session.js:101:41)
    at withRetrySession (/usr/src/app/node_modules/orientjs/lib/client/database/session.js:159:21)
    at Promise (/usr/src/app/node_modules/orientjs/lib/client/database/session.js:184:7)
    at Promise._execute (/usr/src/app/node_modules/orientjs/node_modules/bluebird/js/release/debuggability.js:313:9)
    at Promise._resolveFromExecutor (/usr/src/app/node_modules/orientjs/node_modules/bluebird/js/release/promise.js:488:18)
    at new Promise (/usr/src/app/node_modules/orientjs/node_modules/bluebird/js/release/promise.js:79:10)
    at SessionManager.withSession (/usr/src/app/node_modules/orientjs/lib/client/database/session.js:180:12)
    at tryCatcher (/usr/src/app/node_modules/orientjs/node_modules/bluebird/js/release/util.js:16:23)
```
3. When the above nodejs script run with 2 pod and database is already created comment code
```
 let createDB = await server.create(dbConfig).then(()=>{
    console.log("DB created");
});
```
it fails with following error.
```
Running test scripts
Attempting to start DB
Connection Established!
Error while Process { OrientDB.RequestError: missing session and token
    at child.Operation.parseError (/usr/src/app/node_modules/orientjs/lib/client/network/protocol37/operation.js:1247:13)
    at child.Operation.consume (/usr/src/app/node_modules/orientjs/lib/client/network/protocol37/operation.js:571:35)
    at ONetworkConnection.Connection.process (/usr/src/app/node_modules/orientjs/lib/client/network/conn.js:462:17)
    at ONetworkConnection.Connection.handleSocketData (/usr/src/app/node_modules/orientjs/lib/client/network/conn.js:344:20)
    at Socket.emit (events.js:182:13)
    at addChunk (_stream_readable.js:283:12)
    at readableAddChunk (_stream_readable.js:264:11)
    at Socket.Readable.push (_stream_readable.js:219:10)
    at TCP.onread (net.js:639:20)
  name: 'OrientDB.RequestError',
  message: 'missing session and token',
  data: {},
  isMVCC: [Function],
  isTokenException: [Function],
  previous: [],
  code: 5,
  identifier: 0,
  id: 1,
  type:
   'com.orientechnologies.orient.enterprise.channel.binary.OTokenSecurityException',
  hasMore: 0 }
```
or sometimes
```
Unhandled rejection OrientDB.RequestError: Error on creating cluster 'player2' on distributed nodes: local and remote ids assigned are different
    at child.Operation.parseError (/usr/src/app/node_modules/orientjs/lib/client/network/protocol37/operation.js:1247:13)
    at child.Operation.consume (/usr/src/app/node_modules/orientjs/lib/client/network/protocol37/operation.js:571:35)
    at ONetworkConnection.Connection.process (/usr/src/app/node_modules/orientjs/lib/client/network/conn.js:462:17)
    at ONetworkConnection.Connection.handleSocketData (/usr/src/app/node_modules/orientjs/lib/client/network/conn.js:344:20)
    at Socket.emit (events.js:182:13)
    at addChunk (_stream_readable.js:283:12)
    at readableAddChunk (_stream_readable.js:264:11)
    at Socket.Readable.push (_stream_readable.js:219:10)
    at TCP.onread (net.js:639:20)
 ```

**Comment by wolf4ood** [comment]
Hi @akshay-mahakalkar 


i think you should rely on persistent naming convention using stateful set.

The main issue is that orientdb connections are stateful with a session token id which identify the session on the server. If Kubernetes loadbalance the request for you you will get `missing session and token`

The last time that i tried i used the same config explained here

https://kubernetes.io/docs/tasks/run-application/run-replicated-stateful-application/

Let me know if that helps

Thanks

**Comment by akshay-mahakalkar** [comment]
Hi @wolf4ood ,

I have attached my configuration files here. I have a Kubernetes cluster with 2 replicas of orientdb with statefulset and it provided persistent naming convention so I didn't touch that.
[config.zip](https://github.com/orientechnologies/orientdb/files/4547681/config.zip)

I read the checked the link, but that one is for master slave configuration. I have tried that also by updating default-distributed-db-config.json file as below:
```
{
  "autoDeploy": true,
  "hotAlignment": true,
  "executionMode": "undefined",
  "readQuorum": 1,
  "writeQuorum": "majority",
  "readYourWrites": true,
  "newNodeStrategy": "static",
  "servers": { 
    "orientdbservice-0": "master",
    "orientdbservice-1": "replica"
  },
  "clusters": {
    "internal": {},
    "*": {
      "servers": ["<NEW_NODE>"]
    }
  }
}
```
but this didn't work.

In orientdb documentation they mentioned multi master nodes where every node can be master. so I have kept **servers: { "*": "master" }**

**Comment by akshay-mahakalkar** [comment]
Hi @wolf4ood ,
as per your article it worked, but I have to forcefully provide the address of 1st orientdb pod.
I have provided the address of other pods in server section. Now my database initialization conf looks as below,
```
let dbConfig = {
 "host": 'orientdbservice-0.orientdbservice-headless.default.svc.cluster.local',
 "port": 2424,
 "username": 'root',
 "password": 'qwertyuiop',
 "name": "testdb",
 "user": 'root',
 "type": 'graph',
 "storage": 'plocal',
 "useToken": true,
 "servers": [{host: 'orientdbservice-1.orientdbservice-headless.default.svc.cluster.local', port: 2424}],
 "pool": { max: 10 }
 };
```
This is as per given on orientjs npm page.
But does this configuration will improve the performance as compared to single pod of orientdb?

Any other suggestion from your side for optimum use of both orientdb stateful pods..
