### ISSUE TITLE
Exception in thread 'OrientDB WAL Flush Task'

### ISSUE THREAD

**Issue by quanghaisoft** [orientechnologies/orientdb#9270]
## Expected behavior  
Upsert success, not raise any error

## Actual behavior  
```
Exception in thread 'OrientDB WAL Flush Task'
java.nio.BufferOverflowException
	at java.nio.Buffer.nextPutIndex(Buffer.java:527)
	at java.nio.DirectByteBuffer.putInt(DirectByteBuffer.java:706)
	at com.orientechnologies.orient.core.storage.impl.local.paginated.wal.cas.OCASDiskWriteAheadLog$RecordsWriter.run(OCASDiskWriteAheadLog.java:1920)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```
Can not  update/insert data any more

## Steps to reproduce  
My OrientDB system has over 100 classes with over 50GB data, setup in cluster mode with 6 node, on 6 different IP.
When I upsert big data into 1 master node orientdb in distributed , 
Error appear in logs

```
Exception in thread 'OrientDB WAL Flush Task'
java.nio.BufferOverflowException
	at java.nio.Buffer.nextPutIndex(Buffer.java:527)
	at java.nio.DirectByteBuffer.putInt(DirectByteBuffer.java:706)
	at com.orientechnologies.orient.core.storage.impl.local.paginated.wal.cas.OCASDiskWriteAheadLog$RecordsWriter.run(OCASDiskWriteAheadLog.java:1920)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by laa** [comment]
Hi, @quanghaisoft what is the WAL page size in your environment? You can find size of the WAL page in the log. Do you set any non-default settings? Thank you for the bug report.

**Comment by quanghaisoft** [comment]
thanks you for your answer , this is logs, recent day, this error not appear
config in server.sh
 -Dstorage.wal.maxSegmentSize=128 -Dstorage.wal.maxSize=16384 

2020-06-03 17:01:01:421 INFO  Allocation of 972800 pages. [OEngineLocalPaginated]
2020-06-03 17:01:03:978 INFO  WAL maximum segment size is set to 6,144 MB [OrientDBDistributed]
2020-06-03 17:01:03:978 INFO  Databases directory: /data/orientdb/databases [OServer]
2020-06-03 17:01:04:039 INFO  Direct IO for WAL located in /data/orientdb/databases/OSystem is allowed with block size 4096 bytes. [OCASDiskWriteAheadLog]
2020-06-03 17:01:04:040 INFO  Page size for WAL located in /data/orientdb/databases/OSystem is set to 4096 bytes. [OCASDiskWriteAheadLog]
2020-06-03 17:01:04:104 WARNI Storage 'OSystem' was not closed properly. Will try to recover from write ahead log [OLocalPaginatedStorage]

**Comment by quanghaisoft** [comment]
we have writed a very larger number of concurrent data

**Comment by laa** [comment]
Hi @quanghaisoft . I am not sure that I understood you. Do you mean that now you can not reproduce this error on your tests?

**Comment by quanghaisoft** [comment]
this error not display again. we are runing in production, so i can not test it.if it appears i ll open this issue

**Comment by quanghaisoft** [comment]
this bug in my production so we copy data and rebuild cluster immediately.if it appears again,we will send it to you

**Comment by laa** [comment]
I see thank, I will try to reproduce with settings which you sent to me.

**Comment by laa** [comment]
Hi @quanghaisoft what amount of RAM do you have on the server ?

**Comment by quanghaisoft** [comment]
we using more than 150G ram , CPU 24 core on  node , with 6 node in cluster

**Comment by quanghaisoft** [comment]
when we using multi write upsert to one vertex in 3 master node, it slow down , can you help me a  recommend Config  to active fast upsert with bigdata
this is current config:
 
    JAVA_OPTS_SCRIPT="-XX:+PerfDisableSharedMem -XX:+AlwaysPreTouch -XX:+UseG1GC -XX:+ScavengeBeforeFullGC -XX:+DisableExplicitGC -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/app/orientdb/gcjava/heapdump_oom.log -XX:+PrintGCDetails -XX:+PrintGCTimeStamps -XX:+PrintGCDateStamps -XX:+UseGCLogFileRotation -XX:NumberOfGCLogFiles=10 -XX:GCLogFileSize=100M -Xloggc:/app/orientdb/gcjava/gc_stat.txt  -Ddistributed.dbWorkerThreads=16   -Dtx.autoRetry=5000    -Ddistributed.concurrentTxMaxAutoRetry=500 -Ddistributed.concurrentTxAutoRetryDelay=200 -Ddistributed.asynchResponsesTimeout=80000    -Ddistributed.atomicLockTimeout=15000    -Dnetwork.maxConcurrentSessions=2000  -Ddistributed.localQueueSize=1000000 -Ddistributed.queueMaxSize=1000000 -Ddistributed.autoRemoveOfflineServers=13000 -Dnetwork.http.sessionExpireTimeout=15000 -Dstorage.wal.fuzzyCheckpointInterval=43200 -Dstorage.openFiles.limit=64000 -Dstorage.diskCache.bufferSize=64000 -Dstorage.wal.maxSegmentSize=128 -Dstorage.wal.maxSize=16384 -Dnetwork.maxConcurrentSessions=50000 -Duser.timezone=Asia/Ho_Chi_Minh -Djna.nosys=true -Djava.awt.headless=true -Dfile.encoding=UTF8 -Drhino.opt.level=9 -Dstorage.wal.commitTimeout=3000   -Ddistributed.commandQuickTaskTimeout=130000 -Dscript.pool.maxSize=50 -Ddb.pool.maxSize=300"

**Comment by quanghaisoft** [comment]
when write upsert commend on 3 node master (multiwrite) it display too many errror ,please see attactment 
[orient-server.log.txt](https://github.com/orientechnologies/orientdb/files/4802332/orient-server.log.txt)

**Comment by laa** [comment]
@quanghaisoft issue which you had with WAL was caused by integer overflow. It is already fixed. I can not help you with the issue with distributed storage because I am working on another set of components. Could you please create a separate issue for your problem?

**Comment by quanghaisoft** [comment]
I have just see this error again, i you give me a snapshot of 3.0.31 version


Jun 19 18:45:00 ograph06-76 server.sh[29054]: Exception in thread 'OrientDB WAL Flush Task'
Jun 19 18:45:00 ograph06-76 server.sh[29054]: java.nio.BufferOverflowException
Jun 19 18:45:00 ograph06-76 server.sh[29054]:         at java.nio.Buffer.nextPutIndex(Buffer.java:527)
Jun 19 18:45:00 ograph06-76 server.sh[29054]:         at java.nio.DirectByteBuffer.putInt(DirectByteBuffer.java:706)
Jun 19 18:45:00 ograph06-76 server.sh[29054]:         at com.orientechnologies.orient.core.storage.impl.local.paginated.wal.cas.OCASDiskWriteAheadLog$RecordsWriter.run(OCASDiskWriteAheadLog.java:1920)
Jun 19 18:45:00 ograph06-76 server.sh[29054]:         at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
Jun 19 18:45:00 ograph06-76 server.sh[29054]:         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
Jun 19 18:45:00 ograph06-76 server.sh[29054]:         at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
Jun 19 18:45:00 ograph06-76 server.sh[29054]:         at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
Jun 19 18:45:00 ograph06-76 server.sh[29054]:         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
Jun 19 18:45:00 ograph06-76 server.sh[29054]:         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
Jun 19 18:45:00 ograph06-76 server.sh[29054]:         at java.lang.Thread.run(Thread.java:748)

**Comment by quanghaisoft** [comment]
in others node have this error: Error during WAL writing
java.nio.file.NoSuchFileException: /data/orientdb/databases/OSystem
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
	at sun.nio.fs.UnixFileStore.readAttributes(UnixFileStore.java:111)
	at sun.nio.fs.UnixFileStore.getUsableSpace(UnixFileStore.java:124)
	at com.orientechnologies.orient.core.storage.impl.local.paginated.wal.cas.OCASDiskWriteAheadLog.checkFreeSpace(OCASDiskWriteAheadLog.java:1439)
	at com.orientechnologies.orient.core.storage.impl.local.paginated.wal.cas.OCASDiskWriteAheadLog.access$4000(OCASDiskWriteAheadLog.java:52)
	at com.orientechnologies.orient.core.storage.impl.local.paginated.wal.cas.OCASDiskWriteAheadLog$RecordsWriter.run(OCASDiskWriteAheadLog.java:2053)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

**Comment by laa** [comment]
I see, interesting. I will fix another issue and then will be back to yours.

**Comment by laa** [comment]
@quanghaisoft about directory `: /data/orientdb/databases/OSystem` does it really exist ?

**Comment by quanghaisoft** [comment]
i'm sorry, my server is running in production, so i copy dir databases in a master node to all node and restart   the distributed  cluster, all i have is logs dir

**Comment by quanghaisoft** [comment]
one server full of log file with text: 
Exception in thread 'OrientDB WAL Flush Task'  java.nio.BufferOverflowException  at java.nio.Buffer.nextPutIndex(Buffer.java:527)....

**Comment by laa** [comment]
I did not get it. Did you copy file system data under live server and put it under the replicas or did you shutdown replicas? The correct way to do that is to remove broken databases from nodes and start "empty" replicas, the system will copy all the data correctly.

**Comment by quanghaisoft** [comment]
I has 5 server 71,72,73,74,75,76, i writing data to a master node 71
,but it suddenly error , and all client writing error and stopped, so i login ssh and view log, 
server 71,72,73,74,75 ok
server 76 has full of error: java.nio.BufferOverflowException

**Comment by quanghaisoft** [comment]
> @quanghaisoft about directory `: /data/orientdb/databases/OSystem` does it really exist ?

I''m sorry this error is old,it is last 6 day before

**Comment by quanghaisoft** [comment]
@laa Please help me with this error , can you give me a .jar at 3.0.31

Jun 19 18:45:00 ograph06-76 server.sh[29054]: Exception in thread 'OrientDB WAL Flush Task'
Jun 19 18:45:00 ograph06-76 server.sh[29054]: java.nio.BufferOverflowException
Jun 19 18:45:00 ograph06-76 server.sh[29054]: at java.nio.Buffer.nextPutIndex(Buffer.java:527)
Jun 19 18:45:00 ograph06-76 server.sh[29054]: at

**Comment by laa** [comment]
@quanghaisoft you can download https://orientdb.org/download 3.0.32 changes are minor only small fixes in few components.

**Comment by laa** [comment]
@quanghaisoft could you send me log directory from the 76 node of the cluster ?

**Comment by quanghaisoft** [comment]
[log.zip](https://github.com/orientechnologies/orientdb/files/4805228/log.zip)
this is logs directory after i  recopy data and restart server.

**Comment by quanghaisoft** [comment]
> @quanghaisoft you can download https://orientdb.org/download 3.0.32 changes are minor only small fixes in few components.

OK thank you

**Comment by quanghaisoft** [comment]
I have upgraded to version 3.0.32 and am watching, if I run a problem again I will notify you, thanks a lot

**Comment by laa** [comment]
@quanghaisoft what version of JDK do you use?

**Comment by laa** [comment]
Hi, @quanghaisoft I have introduced a small fix, which should resolve your issue. Is it possible for you to apply new build which I will send to you?

**Comment by quanghaisoft** [comment]
Please send me new build you have fixed, thanks you very much 

we using java  : 

java version "1.8.0_211"
Java(TM) SE Runtime Environment (build 1.8.0_211-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.211-b12, mixed mode)

**Comment by laa** [comment]
@quanghaisoft I am going to add more precautions, it will take couple of days, then I will provide you with new distribution.

**Comment by laa** [comment]
@quanghaisoft could you try this build https://drive.google.com/file/d/1wtQpyzbfeD3w07NpurG1wmGIxScggGXI/view?usp=sharing

**Comment by quanghaisoft** [comment]
> @quanghaisoft could you try this build https://drive.google.com/file/d/1wtQpyzbfeD3w07NpurG1wmGIxScggGXI/view?usp=sharing

Thanks you very much, please give me access to file with email bumha... or xuanhuong...

**Comment by quanghaisoft** [comment]
I have installed and when start service it throw an exception below

2020-07-17 22:22:43:223 INFO  Limit of open files for disk cache will be set to 64000. [OEngineLocalPaginated]
2020-07-17 22:22:43:242 INFO  Loading configuration from: /app/orientdb/config/orientdb-server-config.xml... [OServerConfigurationLoaderXml]
2020-07-17 22:22:43:436 INFO  OrientDB Server v3.0.33-SNAPSHOT - Veloce (build 2b8066106ff63f44391489f85096ab47b80b41c6, branch laa_3.0.x) is starting up... [OServer]
2020-07-17 22:22:43:456 INFO  OrientDB config DISKCACHE=120,000MB [orientechnologies]
2020-07-17 22:22:43:528 INFO  System is started under an effective user : `orientdb` [OEngineLocalPaginated]
2020-07-17 22:22:43:528 INFO  Allocation of 1824000 pages. [OEngineLocalPaginated]
2020-07-17 22:22:43:579 INFO  WAL maximum segment size is set to 6,144 MB [OrientDBEmbedded]
2020-07-17 22:22:43:580 INFO  Databases directory: /app/orientdb/databases [OServer]
2020-07-17 22:22:43:636 INFO  Direct IO for WAL located in /app/orientdb/databases/OSystem is allowed with block size 4096 bytes. [OCASDiskWriteAheadLog]
2020-07-17 22:22:43:636 INFO  Page size for WAL located in /app/orientdb/databases/OSystem is set to 4096 bytes. [OCASDiskWriteAheadLog]Exception `68A09ED8` in storage `plocal:/app/orientdb/databases/OSystem`: 3.0.33-SNAPSHOT - Veloce (build 2b8066106ff63f44391489f85096ab47b80b41c6, branch laa_3.0.x)
java.lang.NoSuchMethodError: java.nio.ByteBuffer.position(I)Ljava/nio/ByteBuffer;
	at com.orientechnologies.common.io.OIOUtils.readByteBuffer(OIOUtils.java:368)
	at com.orientechnologies.orient.core.storage.impl.local.paginated.wal.cas.OCASDiskWriteAheadLog.readMasterRecord(OCASDiskWriteAheadLog.java:481)
	at com.orientechnologies.orient.core.storage.impl.local.paginated.wal.cas.OCASDiskWriteAheadLog.readLastCheckpointInfo(OCASDiskWriteAheadLog.java:406)
	at com.orientechnologies.orient.core.storage.impl.local.paginated.wal.cas.OCASDiskWriteAheadLog.<init>(OCASDiskWriteAheadLog.java:286)
	at com.orientechnologies.orient.core.storage.disk.OLocalPaginatedStorage.initWalAndDiskCache(OLocalPaginatedStorage.java:574)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.open(OAbstractPaginatedStorage.java:392)
	at com.orientechnologies.orient.core.db.OrientDBEmbedded.openNoAuthorization(OrientDBEmbedded.java:259)
	at com.orientechnologies.orient.core.db.OrientDBEmbedded.openNoAuthorization(OrientDBEmbedded.java:56)
	at com.orientechnologies.orient.server.OSystemDatabase.openSystemDatabase(OSystemDatabase.java:97)
	at com.orientechnologies.orient.server.OSystemDatabase.checkServerId(OSystemDatabase.java:174)
	at com.orientechnologies.orient.server.OSystemDatabase.init(OSystemDatabase.java:162)
	at com.orientechnologies.orient.server.OSystemDatabase.<init>(OSystemDatabase.java:49)
	at com.orientechnologies.orient.server.OServer.initSystemDatabase(OServer.java:1212)
	at com.orientechnologies.orient.server.OServer.activate(OServer.java:421)
	at com.orientechnologies.orient.server.OServerMain$1.run(OServerMain.java:48)
JVM error was thrown
java.lang.NoSuchMethodError: java.nio.ByteBuffer.position(I)Ljava/nio/ByteBuffer;
	at com.orientechnologies.common.io.OIOUtils.readByteBuffer(OIOUtils.java:368)
	at com.orientechnologies.orient.core.storage.impl.local.paginated.wal.cas.OCASDiskWriteAheadLog.readMasterRecord(OCASDiskWriteAheadLog.java:481)
	at com.orientechnologies.orient.core.storage.impl.local.paginated.wal.cas.OCASDiskWriteAheadLog.readLastCheckpointInfo(OCASDiskWriteAheadLog.java:406)
	at com.orientechnologies.orient.core.storage.impl.local.paginated.wal.cas.OCASDiskWriteAheadLog.<init>(OCASDiskWriteAheadLog.java:286)
	at com.orientechnologies.orient.core.storage.disk.OLocalPaginatedStorage.initWalAndDiskCache(OLocalPaginatedStorage.java:574)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.open(OAbstractPaginatedStorage.java:392)
	at com.orientechnologies.orient.core.db.OrientDBEmbedded.openNoAuthorization(OrientDBEmbedded.java:259)
	at com.orientechnologies.orient.core.db.OrientDBEmbedded.openNoAuthorization(OrientDBEmbedded.java:56)
	at com.orientechnologies.orient.server.OSystemDatabase.openSystemDatabase(OSystemDatabase.java:97)
	at com.orientechnologies.orient.server.OSystemDatabase.checkServerId(OSystemDatabase.java:174)
	at com.orientechnologies.orient.server.OSystemDatabase.init(OSystemDatabase.java:162)
	at com.orientechnologies.orient.server.OSystemDatabase.<init>(OSystemDatabase.java:49)
	at com.orientechnologies.orient.server.OServer.initSystemDatabase(OServer.java:1212)
	at com.orientechnologies.orient.server.OServer.activate(OServer.java:421)
	at com.orientechnologies.orient.server.OServerMain$1.run(OServerMain.java:48)

**Comment by laa** [comment]
I see it was built under higher JDK, the same API but now returns the current instance of the buffer. I will rebuild it next week.

**Comment by quanghaisoft** [comment]
> I see it was built under higher JDK, the same API but now returns the current instance of the buffer. I will rebuild it next week.

OK thanks you very much .

**Comment by laa** [comment]
Guys, could you try https://oss.sonatype.org/content/repositories/snapshots/com/orientechnologies/orientdb-community/3.0.33-SNAPSHOT/orientdb-community-3.0.33-20200717.164059-15.zip this build?

**Comment by quanghaisoft** [comment]
> Guys, could you try https://oss.sonatype.org/content/repositories/snapshots/com/orientechnologies/orientdb-community/3.0.33-SNAPSHOT/orientdb-community-3.0.33-20200717.164059-15.zip this build?

OK i will try it , thanks a lot

**Comment by quanghaisoft** [comment]
> Guys, could you try https://oss.sonatype.org/content/repositories/snapshots/com/orientechnologies/orientdb-community/3.0.33-SNAPSHOT/orientdb-community-3.0.33-20200717.164059-15.zip this build?

I have upgraded to this build and it works fine, thanks you very much .

**Comment by laa** [comment]
Hi @quanghaisoft it could be one more reason why you experience this issue. It is inside the code of the distributed database. We are planning to port it soon to all the versions. I will let you know.

**Comment by quanghaisoft** [comment]
> Hi @quanghaisoft it could be one more reason why you experience this issue. It is inside the code of the distributed database. We are planning to port it soon to all the versions. I will let you know.

Yes, thanks a lot, we'll waiting for it.

**Comment by laa** [comment]
Fixed. Should be delivered in next hotfix. Please reopen if the issue will still persist on your side.
