### ISSUE TITLE
size of orient db client thread pool too large?

### ISSUE THREAD

**Issue by jamieb22** [orientechnologies/orientdb#9274]
### OrientDB Version: 3.0.31

When running Orient DB 3.0.31 in a multi-tenant scenario with several databases opened at the same time, there are a huge number of Orient DB daemon threads waiting, and most  (>100) do not appear to be doing useful work. Needless to say, if a thread pool is too large, then it negatively affects the performance of the server due to unnecessary context switching, and adds 1M stack size overhead per thread. In short, the suggestion is that current size of Orient DB client thread pool is too large, and does not materially improve Orient DB performance, but actually detracts from it.

"Thread-1564" #4434 daemon prio=5 os_prio=0 tid=0x00007fb0027af800 nid=0x4585 waiting on condition [0x00007faff34e3000]
   java.lang.Thread.State: WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x000000033c3d22a0> (a java.util.concurrent.SynchronousQueue$TransferStack)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
	at java.util.concurrent.SynchronousQueue$TransferStack.awaitFulfill(SynchronousQueue.java:458)
	at java.util.concurrent.SynchronousQueue$TransferStack.transfer(SynchronousQueue.java:362)
	at java.util.concurrent.SynchronousQueue.put(SynchronousQueue.java:877)
	at com.orientechnologies.orient.client.remote.OStorageRemotePushThread.run(OStorageRemotePushThread.java:61)

Refer to attached JFR snapshot for example.

[2020-06-01_06-08-00.zip](https://github.com/orientechnologies/orientdb/files/4710160/2020-06-01_06-08-00.zip)

**Comment by tglman** [comment]
Hi,

Yes as today we do have one instance of OStorageRemotePushThread per database on the client, this can be improved in future, having one single pool for each instance of `OrientDBRemote`.

Regards
