### ISSUE TITLE
[Bug] [3.1.0] [Client?] NPE when creating an edge

### ISSUE THREAD

**Issue by matanshukry** [orientechnologies/orientdb#9276]
## Expected behavior
Create an edge (or throw a non-NPE exception if needed)

## Actual behavior
An exception (NPE) is thrown

## Steps to reproduce

I'm executing the following query:
```
CREATE EDGE MyEdge FROM (SELECT FROM MyVertex WHERE id = ? AND options & ? == ?) TO (SELECT FROM MyVertex WHERE id = ? AND options & ? == ?) SET createdAt=?
```

- `id` is type `string`
- `options` is type `int`
- `createdAt` is type `long`

## Log

```
2020-06-01 16:10:19.681 ERROR 24952 --- [ XNIO-1 task-48] c.o.o.c.d.ODatabaseDocumentRemotePooled  : Error on transaction commit `5AD38747`

java.lang.NullPointerException: null
	at com.orientechnologies.orient.core.serialization.serializer.record.binary.ODocumentSerializerDelta.serializeDeltaLinkBag(ODocumentSerializerDelta.java:605) ~[orientdb-core-3.1.0.jar:3.1.0]
	at com.orientechnologies.orient.core.serialization.serializer.record.binary.ODocumentSerializerDelta.serializeDeltaValue(ODocumentSerializerDelta.java:583) ~[orientdb-core-3.1.0.jar:3.1.0]
	at com.orientechnologies.orient.core.serialization.serializer.record.binary.ODocumentSerializerDelta.serializeDeltaEntry(ODocumentSerializerDelta.java:556) ~[orientdb-core-3.1.0.jar:3.1.0]
	at com.orientechnologies.orient.core.serialization.serializer.record.binary.ODocumentSerializerDelta.serializeDelta(ODocumentSerializerDelta.java:540) ~[orientdb-core-3.1.0.jar:3.1.0]
	at com.orientechnologies.orient.core.serialization.serializer.record.binary.ODocumentSerializerDelta.serializeDelta(ODocumentSerializerDelta.java:64) ~[orientdb-core-3.1.0.jar:3.1.0]
	at com.orientechnologies.orient.client.remote.message.OCommit38Request.<init>(OCommit38Request.java:65) ~[orientdb-client-3.1.0.jar:3.1.0]
	at com.orientechnologies.orient.client.remote.OStorageRemote.commit(OStorageRemote.java:1014) ~[orientdb-client-3.1.0.jar:3.1.0]
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentAbstract.internalCommit(ODatabaseDocumentAbstract.java:2320) [orientdb-core-3.1.0.jar:3.1.0]
	at com.orientechnologies.orient.core.tx.OTransactionOptimistic.doCommit(OTransactionOptimistic.java:558) ~[orientdb-core-3.1.0.jar:3.1.0]
	at com.orientechnologies.orient.core.tx.OTransactionOptimistic.commit(OTransactionOptimistic.java:109) ~[orientdb-core-3.1.0.jar:3.1.0]
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentAbstract.commit(ODatabaseDocumentAbstract.java:1879) [orientdb-core-3.1.0.jar:3.1.0]
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentAbstract.commit(ODatabaseDocumentAbstract.java:1849) [orientdb-core-3.1.0.jar:3.1.0]
	...
```

## Extra Useful Information

Since I'm running OrientDB locally and I can recreate the exception I put a breakpoint when the exception happens to get a bit more info. I'm not sure what info is relevant, so I just got a screenshot with some values IntelliJ shows

The breakpoint with the exception. You can see `timeline` is null
![image](https://user-images.githubusercontent.com/5613042/83413486-91cb0200-a424-11ea-9003-aa31d87a661a.png)

The stack trace:
![image](https://user-images.githubusercontent.com/5613042/83413442-81b32280-a424-11ea-9f87-736f47e79fd6.png)

**Comment by matanshukry** [comment]
Any news/insights on this?

**Comment by matanshukry** [comment]
Closing due to duplicate #9179
