### ISSUE TITLE
java.lang.IllegalMonitorStateException in distributed orientdb deployment

### ISSUE THREAD

**Issue by madmac2501** [orientechnologies/orientdb#9285]
## Expected behavior  
Database syncs correctly without blocking.

## Actual behavior  
Trying to recover a database in distributed mode throws these errors. And database recovery gets hang and doesn't try to resync/recover database

2020-06-07 18:16:07:546 INFO  [orientdb-3] Trying to recover current server for database 'xxx'... [OClusterHealthChecker][172.25.1.198]:2434 [orientdb] [3.10.6] Current thread is not owner of the lock! -> Owner: 6877d042-373c-4f99-8ee5-a7b189ea2f43, thread ID: 123
java.lang.IllegalMonitorStateException: Current thread is not owner of the lock! -> Owner: 6877d042-373c-4f99-8ee5-a7b189ea2f43, thread ID: 123
	at com.hazelcast.concurrent.lock.operations.UnlockOperation.unlock(UnlockOperation.java:75)
	at com.hazelcast.concurrent.lock.operations.UnlockOperation.run(UnlockOperation.java:64)
	at com.hazelcast.spi.Operation.call(Operation.java:148)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.call(OperationRunnerImpl.java:202)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:191)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:120)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.run(OperationThread.java:100)
[172.25.1.198]:2434 [orientdb] [3.10.6] Current thread is not owner of the lock! -> Owner: 6877d042-373c-4f99-8ee5-a7b189ea2f43, thread ID: 123
java.lang.IllegalMonitorStateException: Current thread is not owner of the lock! -> Owner: 6877d042-373c-4f99-8ee5-a7b189ea2f43, thread ID: 123
	at com.hazelcast.concurrent.lock.operations.UnlockOperation.unlock(UnlockOperation.java:75)
	at com.hazelcast.concurrent.lock.operations.UnlockOperation.run(UnlockOperation.java:64)
	at com.hazelcast.spi.Operation.call(Operation.java:148)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.call(OperationRunnerImpl.java:202)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:191)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:120)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.run(OperationThread.java:100)
Error on checking cluster health
java.lang.IllegalMonitorStateException: Current thread is not owner of the lock! -> Owner: 6877d042-373c-4f99-8ee5-a7b189ea2f43, thread ID: 123
	at com.hazelcast.concurrent.lock.operations.UnlockOperation.unlock(UnlockOperation.java:75)
	at com.hazelcast.concurrent.lock.operations.UnlockOperation.run(UnlockOperation.java:64)
	at com.hazelcast.spi.Operation.call(Operation.java:148)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.call(OperationRunnerImpl.java:202)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:191)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:120)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.run(OperationThread.java:100)
	at ------ submitted from ------.(Unknown Source)
	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.resolve(InvocationFuture.java:127)
	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.resolveAndThrowIfException(InvocationFuture.java:79)
	at com.hazelcast.spi.impl.AbstractInvocationFuture.get(AbstractInvocationFuture.java:162)
	at com.hazelcast.spi.impl.AbstractInvocationFuture.join(AbstractInvocationFuture.java:143)
	at com.hazelcast.concurrent.lock.LockProxySupport.unlock(LockProxySupport.java:151)
	at com.hazelcast.concurrent.lock.LockProxy.unlock(LockProxy.java:106)
	at com.orientechnologies.orient.server.hazelcast.OHazelcastLockManager.releaseExclusiveLock(OHazelcastLockManager.java:37)
	at com.orientechnologies.orient.server.distributed.impl.ODistributedAbstractPlugin.executeInDistributedDatabaseLock(ODistributedAbstractPlugin.java:1588)
	at com.orientechnologies.orient.server.distributed.impl.ODistributedAbstractPlugin.installDatabase(ODistributedAbstractPlugin.java:886)
	at com.orientechnologies.orient.server.distributed.impl.OClusterHealthChecker.checkServerStatus(OClusterHealthChecker.java:216)
	at com.orientechnologies.orient.server.distributed.impl.OClusterHealthChecker.run(OClusterHealthChecker.java:67)
	at com.orientechnologies.orient.core.Orient$3.run(Orient.java:412)
	at java.util.TimerThread.mainLoop(Timer.java:555)
	at java.util.TimerThread.run(Timer.java:505)

## Steps to reproduce  
Not sure, probably a restart of a database

**Comment by madmac2501** [comment]
I still reproduce this in 3.1.1

`[172.26.76.23]:2434 [orientdb] [3.10.6] Current thread is not owner of the lock! -> Owner: 38ae651c-e2f5-466d-96d0-32e5ffb2a10b, thread ID: 10
java.lang.IllegalMonitorStateException: Current thread is not owner of the lock! -> Owner: 38ae651c-e2f5-466d-96d0-32e5ffb2a10b, thread ID: 10
	at com.hazelcast.concurrent.lock.operations.UnlockOperation.unlock(UnlockOperation.java:75)
	at com.hazelcast.concurrent.lock.operations.UnlockOperation.run(UnlockOperation.java:64)
	at com.hazelcast.spi.Operation.call(Operation.java:148)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.call(OperationRunnerImpl.java:202)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:191)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:120)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.run(OperationThread.java:100)
Error on checking cluster health
java.lang.IllegalMonitorStateException: Current thread is not owner of the lock! -> Owner: 38ae651c-e2f5-466d-96d0-32e5ffb2a10b, thread ID: 10
	at com.hazelcast.concurrent.lock.operations.UnlockOperation.unlock(UnlockOperation.java:75)
	at com.hazelcast.concurrent.lock.operations.UnlockOperation.run(UnlockOperation.java:64)
	at com.hazelcast.spi.Operation.call(Operation.java:148)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.call(OperationRunnerImpl.java:202)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:191)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:120)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.run(OperationThread.java:100)
	at ------ submitted from ------.(Unknown Source)
	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.resolve(InvocationFuture.java:127)
	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.resolveAndThrowIfException(InvocationFuture.java:79)
	at com.hazelcast.spi.impl.AbstractInvocationFuture.get(AbstractInvocationFuture.java:162)
	at com.hazelcast.spi.impl.AbstractInvocationFuture.join(AbstractInvocationFuture.java:143)
	at com.hazelcast.concurrent.lock.LockProxySupport.unlock(LockProxySupport.java:151)
	at com.hazelcast.concurrent.lock.LockProxy.unlock(LockProxy.java:106)
	at com.orientechnologies.orient.server.hazelcast.OHazelcastLockManager.releaseExclusiveLock(OHazelcastLockManager.java:35)
	at com.orientechnologies.orient.server.distributed.impl.ODistributedAbstractPlugin.executeInDistributedDatabaseLock(ODistributedAbstractPlugin.java:1962)
	at com.orientechnologies.orient.server.distributed.impl.ODistributedAbstractPlugin.installDatabase(ODistributedAbstractPlugin.java:1022)
	at com.orientechnologies.orient.server.distributed.impl.OClusterHealthChecker.checkServerStatus(OClusterHealthChecker.java:271)
	at com.orientechnologies.orient.server.distributed.impl.OClusterHealthChecker.run(OClusterHealthChecker.java:78)
	at com.orientechnologies.orient.core.Orient$3.run(Orient.java:430)
	at java.util.TimerThread.mainLoop(Timer.java:555)
	at java.util.TimerThread.run(Timer.java:505)

2020-07-08 11:00:42:862 INFO  [oriendb-cluster-1-demo-cloud-se-aws-us-east-1] Trying to recover current server for database 'justdoit'... [OClusterHealthChecker][172.26.76.23]:2434 [orientdb] [3.10.6] Current thread is not owner of the lock! -> Owner: 38ae651c-e2f5-466d-96d0-32e5ffb2a10b, thread ID: 10
java.lang.IllegalMonitorStateException: Current thread is not owner of the lock! -> Owner: 38ae651c-e2f5-466d-96d0-32e5ffb2a10b, thread ID: 10
	at com.hazelcast.concurrent.lock.operations.UnlockOperation.unlock(UnlockOperation.java:75)
	at com.hazelcast.concurrent.lock.operations.UnlockOperation.run(UnlockOperation.java:64)
	at com.hazelcast.spi.Operation.call(Operation.java:148)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.call(OperationRunnerImpl.java:202)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:191)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:120)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.run(OperationThread.java:100)
[172.26.76.23]:2434 [orientdb] [3.10.6] Current thread is not owner of the lock! -> Owner: 38ae651c-e2f5-466d-96d0-32e5ffb2a10b, thread ID: 10
java.lang.IllegalMonitorStateException: Current thread is not owner of the lock! -> Owner: 38ae651c-e2f5-466d-96d0-32e5ffb2a10b, thread ID: 10
	at com.hazelcast.concurrent.lock.operations.UnlockOperation.unlock(UnlockOperation.java:75)
	at com.hazelcast.concurrent.lock.operations.UnlockOperation.run(UnlockOperation.java:64)
	at com.hazelcast.spi.Operation.call(Operation.java:148)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.call(OperationRunnerImpl.java:202)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:191)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:120)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.run(OperationThread.java:100)
Error on checking cluster health
java.lang.IllegalMonitorStateException: Current thread is not owner of the lock! -> Owner: 38ae651c-e2f5-466d-96d0-32e5ffb2a10b, thread ID: 10
	at com.hazelcast.concurrent.lock.operations.UnlockOperation.unlock(UnlockOperation.java:75)
	at com.hazelcast.concurrent.lock.operations.UnlockOperation.run(UnlockOperation.java:64)
	at com.hazelcast.spi.Operation.call(Operation.java:148)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.call(OperationRunnerImpl.java:202)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:191)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:120)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.run(OperationThread.java:100)
	at ------ submitted from ------.(Unknown Source)
	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.resolve(InvocationFuture.java:127)
	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.resolveAndThrowIfException(InvocationFuture.java:79)
	at com.hazelcast.spi.impl.AbstractInvocationFuture.get(AbstractInvocationFuture.java:162)
	at com.hazelcast.spi.impl.AbstractInvocationFuture.join(AbstractInvocationFuture.java:143)
	at com.hazelcast.concurrent.lock.LockProxySupport.unlock(LockProxySupport.java:151)
	at com.hazelcast.concurrent.lock.LockProxy.unlock(LockProxy.java:106)
	at com.orientechnologies.orient.server.hazelcast.OHazelcastLockManager.releaseExclusiveLock(OHazelcastLockManager.java:35)
	at com.orientechnologies.orient.server.distributed.impl.ODistributedAbstractPlugin.executeInDistributedDatabaseLock(ODistributedAbstractPlugin.java:1962)
	at com.orientechnologies.orient.server.distributed.impl.ODistributedAbstractPlugin.installDatabase(ODistributedAbstractPlugin.java:1022)
	at com.orientechnologies.orient.server.distributed.impl.OClusterHealthChecker.checkServerStatus(OClusterHealthChecker.java:271)
	at com.orientechnologies.orient.server.distributed.impl.OClusterHealthChecker.run(OClusterHealthChecker.java:78)
	at com.orientechnologies.orient.core.Orient$3.run(Orient.java:430)
	at java.util.TimerThread.mainLoop(Timer.java:555)
	at java.util.TimerThread.run(Timer.java:505)

2020-07-08 11:01:23:866 INFO  [oriendb-cluster-1-demo-cloud-se-aws-us-east-1] Trying to recover current server for database 'justdoit'... [OClusterHealthChecker][172.26.76.23]:2434 [orientdb] [3.10.6] Current thread is not owner of the lock! -> Owner: 38ae651c-e2f5-466d-96d0-32e5ffb2a10b, thread ID: 10
java.lang.IllegalMonitorStateException: Current thread is not owner of the lock! -> Owner: 38ae651c-e2f5-466d-96d0-32e5ffb2a10b, thread ID: 10
	at com.hazelcast.concurrent.lock.operations.UnlockOperation.unlock(UnlockOperation.java:75)
	at com.hazelcast.concurrent.lock.operations.UnlockOperation.run(UnlockOperation.java:64)
	at com.hazelcast.spi.Operation.call(Operation.java:148)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.call(OperationRunnerImpl.java:202)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:191)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:120)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.run(OperationThread.java:100)
[172.26.76.23]:2434 [orientdb] [3.10.6] Current thread is not owner of the lock! -> Owner: 38ae651c-e2f5-466d-96d0-32e5ffb2a10b, thread ID: 10
java.lang.IllegalMonitorStateException: Current thread is not owner of the lock! -> Owner: 38ae651c-e2f5-466d-96d0-32e5ffb2a10b, thread ID: 10
	at com.hazelcast.concurrent.lock.operations.UnlockOperation.unlock(UnlockOperation.java:75)
	at com.hazelcast.concurrent.lock.operations.UnlockOperation.run(UnlockOperation.java:64)
	at com.hazelcast.spi.Operation.call(Operation.java:148)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.call(OperationRunnerImpl.java:202)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:191)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:120)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.run(OperationThread.java:100)
Error on checking cluster health
java.lang.IllegalMonitorStateException: Current thread is not owner of the lock! -> Owner: 38ae651c-e2f5-466d-96d0-32e5ffb2a10b, thread ID: 10
	at com.hazelcast.concurrent.lock.operations.UnlockOperation.unlock(UnlockOperation.java:75)
	at com.hazelcast.concurrent.lock.operations.UnlockOperation.run(UnlockOperation.java:64)
	at com.hazelcast.spi.Operation.call(Operation.java:148)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.call(OperationRunnerImpl.java:202)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:191)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:120)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.run(OperationThread.java:100)
	at ------ submitted from ------.(Unknown Source)
	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.resolve(InvocationFuture.java:127)
	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.resolveAndThrowIfException(InvocationFuture.java:79)
	at com.hazelcast.spi.impl.AbstractInvocationFuture.get(AbstractInvocationFuture.java:162)
	at com.hazelcast.spi.impl.AbstractInvocationFuture.join(AbstractInvocationFuture.java:143)
	at com.hazelcast.concurrent.lock.LockProxySupport.unlock(LockProxySupport.java:151)
	at com.hazelcast.concurrent.lock.LockProxy.unlock(LockProxy.java:106)
	at com.orientechnologies.orient.server.hazelcast.OHazelcastLockManager.releaseExclusiveLock(OHazelcastLockManager.java:35)
	at com.orientechnologies.orient.server.distributed.impl.ODistributedAbstractPlugin.executeInDistributedDatabaseLock(ODistributedAbstractPlugin.java:1962)
	at com.orientechnologies.orient.server.distributed.impl.ODistributedAbstractPlugin.installDatabase(ODistributedAbstractPlugin.java:1022)
	at com.orientechnologies.orient.server.distributed.impl.OClusterHealthChecker.checkServerStatus(OClusterHealthChecker.java:271)
	at com.orientechnologies.orient.server.distributed.impl.OClusterHealthChecker.run(OClusterHealthChecker.java:78)
	at com.orientechnologies.orient.core.Orient$3.run(Orient.java:430)
	at java.util.TimerThread.mainLoop(Timer.java:555)
	at java.util.TimerThread.run(Timer.java:505)
`
