### ISSUE TITLE
StringIndexOutOfBoundsException after migrating from 3.0.22 to 3.1.0

### ISSUE THREAD

**Issue by typingtanuki** [orientechnologies/orientdb#9308]
## Expected behavior  
Can migrate to 3.1.0 and use database.

## Actual behavior  
Migration goes fine, upon restart DB fails with StringIndexOutOfBoundsException

## Steps to reproduce  

* Create new database on 3.0.22
* Add some documents
* Stop database
* Switch to 3.1.0
* Start database
* Add/edit some documents
* Stop database
* Restart database
** Issue will occur while opening the database

Stack trace:
`Caused by: com.orientechnologies.orient.core.exception.OStorageException: Exception during execution of atomic operation inside of storage hedge
	at com.orientechnologies.orient.core.storage.impl.local.paginated.atomicoperations.OAtomicOperationsManager.executeInsideAtomicOperation(OAtomicOperationsManager.java:179)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.open(OAbstractPaginatedStorage.java:307)
	at com.orientechnologies.orient.core.db.OrientDBEmbedded.open(OrientDBEmbedded.java:412)
	... 22 common frames omitted
Caused by: java.lang.StringIndexOutOfBoundsException: offset 22, count 16777216, length 147
	at java.base/java.lang.String.checkBoundsOffCount(String.java:3304)
	at java.base/java.lang.String.<init>(String.java:505)
	at com.orientechnologies.orient.core.storage.config.OClusterBasedStorageConfiguration.deserializeStringValue(OClusterBasedStorageConfiguration.java:1588)
	at com.orientechnologies.orient.core.storage.config.OClusterBasedStorageConfiguration.deserializeIndexEngineProperty(OClusterBasedStorageConfiguration.java:1421)
	at com.orientechnologies.orient.core.storage.config.OClusterBasedStorageConfiguration.getIndexEngine(OClusterBasedStorageConfiguration.java:1183)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.openIndexes(OAbstractPaginatedStorage.java:433)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.lambda$open$1(OAbstractPaginatedStorage.java:329)
	at com.orientechnologies.orient.core.storage.impl.local.paginated.atomicoperations.OAtomicOperationsManager.executeInsideAtomicOperation(OAtomicOperationsManager.java:175)
	... 24 common frames omitted`

**Comment by laa** [comment]
Fixed

**Comment by typingtanuki** [comment]
Thanks for the quick fix.
Do you know when it will be part of a release ?

**Comment by laa** [comment]
@typingtanuki we should release the next version during the two weeks.

**Comment by typingtanuki** [comment]
Awesome, thanks
