### ISSUE TITLE
OrientDB 3.1.0 suddenly stops working indicating Error in data flush background thread, please restart database and send full stack trace inside of bug report

### ISSUE THREAD

**Issue by CanonTino** [orientechnologies/orientdb#9314]
## Actual behavior  
`
2020-06-24 10:54:03:256 WARNI Received signal: SIGINT [OSignalHandler]
2020-06-24 10:54:03:257 INFO  OrientDB Server is shutting down... [OServer]
2020-06-24 10:54:03:257 INFO  Shutting down listeners: [OServer]
2020-06-24 10:54:03:257 INFO  - ONetworkProtocolBinary /0.0.0.0:2424: [OServer]
2020-06-24 10:54:03:257 INFO  - ONetworkProtocolHttpDb /0.0.0.0:2480: [OServer]
2020-06-24 10:54:03:257 INFO  Shutting down protocols [OServer]
2020-06-24 10:54:03:258 INFO  Shutting down plugins: [OServerPluginManager]
2020-06-24 10:54:03:258 INFO  - studio [OServerPluginManager]
2020-06-24 10:54:03:258 INFO  - teleporter [OServerPluginManager]
2020-06-24 10:54:03:258 INFO  - custom-sql-functions-manager [OServerPluginManager]
2020-06-24 10:54:03:258 INFO  - script-interpreter [OServerPluginManager]
2020-06-24 10:54:03:258 INFO  - etl [OServerPluginManager]
2020-06-24 10:54:03:258 INFO  - neo4j-importer [OServerPluginManager]
2020-06-24 10:54:03:258 INFO  Shutting down databases: [OServer]
2020-06-24 10:54:03:258 INFO  Orient Engine is shutting down... [Orient]
2020-06-24 10:54:03:260 INFO  - shutdown storage: OSystem... [OrientDBDistributed]
2020-06-24 10:54:03:269 SEVER Can not flush data because of issue during data write, You cannot access outside the file size (65536 bytes). You have requested portion from 0-131072 bytes. File: File: keydok_2_2759850.cpm os-size=66560, stored=65536 [OWOWCache$PeriodicFlushTask]
2020-06-24 10:54:03:297 SEVER Can not flush data because of issue during data write, You cannot access outside the file size (65536 bytes). You have requested portion from 0-131072 bytes. File: File: keydok_2_2759850.cpm os-size=66560, stored=65536 [OWOWCache$PeriodicFlushTask]
2020-06-24 10:54:03:313 INFO  - shutdown storage: MAPP... [OrientDBDistributed]
2020-06-24 10:54:03:314 SEVER Can not flush file data because of issue during data write, You cannot access outside the file size (65536 bytes). You have requested portion from 0-131072 bytes. File: File: keydok_2_2759850.cpm os-size=66560, stored=65536 [OWOWCache$FileFlushTask]Exception `2EC9DD4F` in storage `plocal:/Users/florentinosalazar/Downloads/orientdb-3.1.0/databases/MAPP`: 3.1.0 - Veloce (build da09ce5af52267b70035d8600551a5032065807a, branch develop)
com.orientechnologies.orient.core.exception.OStorageException: Error in data flush background thread, please restart database and send full stack trace inside of bug report
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.checkReadOnlyConditions(OAbstractPaginatedStorage.java:5719)
	at com.orientechnologies.orient.core.storage.impl.local.paginated.atomicoperations.OAtomicOperationsManager.checkReadOnlyConditions(OAtomicOperationsManager.java:142)
	at com.orientechnologies.orient.core.storage.impl.local.paginated.atomicoperations.OAtomicOperationsManager.startAtomicOperation(OAtomicOperationsManager.java:135)
	at com.orientechnologies.orient.core.storage.impl.local.paginated.atomicoperations.OAtomicOperationsManager.executeInsideAtomicOperation(OAtomicOperationsManager.java:173)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.doClose(OAbstractPaginatedStorage.java:5029)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.close(OAbstractPaginatedStorage.java:680)
	at com.orientechnologies.orient.core.storage.OStorageAbstract.shutdown(OStorageAbstract.java:214)
	at com.orientechnologies.orient.core.db.OrientDBEmbedded.internalClose(OrientDBEmbedded.java:777)
	at com.orientechnologies.orient.core.Orient$OShutdownOrientDBInstancesHandler.shutdown(Orient.java:799)
	at com.orientechnologies.orient.core.Orient.shutdown(Orient.java:373)
	at com.orientechnologies.orient.server.OServer.deinit(OServer.java:581)
	at com.orientechnologies.orient.server.OServer.shutdown(OServer.java:500)
	at com.orientechnologies.orient.server.OServerShutdownHook.run(OServerShutdownHook.java:40)
Caused by: com.orientechnologies.common.io.OIOException: You cannot access outside the file size (65536 bytes). You have requested portion from 0-131072 bytes. File: File: keydok_2_2759850.cpm os-size=66560, stored=65536
	at com.orientechnologies.orient.core.storage.fs.OFileClassic.checkRegions(OFileClassic.java:307)
	at com.orientechnologies.orient.core.storage.fs.OFileClassic.write(OFileClassic.java:214)
	at com.orientechnologies.orient.core.storage.fs.OFileClassic.write(OFileClassic.java:228)
	at com.orientechnologies.orient.core.storage.cache.local.OWOWCache.flushPages(OWOWCache.java:2871)
	at com.orientechnologies.orient.core.storage.cache.local.OWOWCache.flushWriteCacheFromMinLSN(OWOWCache.java:2779)
	at com.orientechnologies.orient.core.storage.cache.local.OWOWCache.access$2300(OWOWCache.java:109)
	at com.orientechnologies.orient.core.storage.cache.local.OWOWCache$PeriodicFlushTask.run(OWOWCache.java:2546)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
-- error on shutdown storage
com.orientechnologies.orient.core.exception.OStorageException: Error in data flush background thread, please restart database and send full stack trace inside of bug report
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.checkReadOnlyConditions(OAbstractPaginatedStorage.java:5719)
	at com.orientechnologies.orient.core.storage.impl.local.paginated.atomicoperations.OAtomicOperationsManager.checkReadOnlyConditions(OAtomicOperationsManager.java:142)
	at com.orientechnologies.orient.core.storage.impl.local.paginated.atomicoperations.OAtomicOperationsManager.startAtomicOperation(OAtomicOperationsManager.java:135)
	at com.orientechnologies.orient.core.storage.impl.local.paginated.atomicoperations.OAtomicOperationsManager.executeInsideAtomicOperation(OAtomicOperationsManager.java:173)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.doClose(OAbstractPaginatedStorage.java:5029)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.close(OAbstractPaginatedStorage.java:680)
	at com.orientechnologies.orient.core.storage.OStorageAbstract.shutdown(OStorageAbstract.java:214)
	at com.orientechnologies.orient.core.db.OrientDBEmbedded.internalClose(OrientDBEmbedded.java:777)
	at com.orientechnologies.orient.core.Orient$OShutdownOrientDBInstancesHandler.shutdown(Orient.java:799)
	at com.orientechnologies.orient.core.Orient.shutdown(Orient.java:373)
	at com.orientechnologies.orient.server.OServer.deinit(OServer.java:581)
	at com.orientechnologies.orient.server.OServer.shutdown(OServer.java:500)
	at com.orientechnologies.orient.server.OServerShutdownHook.run(OServerShutdownHook.java:40)
Caused by: com.orientechnologies.common.io.OIOException: You cannot access outside the file size (65536 bytes). You have requested portion from 0-131072 bytes. File: File: keydok_2_2759850.cpm os-size=66560, stored=65536
	at com.orientechnologies.orient.core.storage.fs.OFileClassic.checkRegions(OFileClassic.java:307)
	at com.orientechnologies.orient.core.storage.fs.OFileClassic.write(OFileClassic.java:214)
	at com.orientechnologies.orient.core.storage.fs.OFileClassic.write(OFileClassic.java:228)
	at com.orientechnologies.orient.core.storage.cache.local.OWOWCache.flushPages(OWOWCache.java:2871)
	at com.orientechnologies.orient.core.storage.cache.local.OWOWCache.flushWriteCacheFromMinLSN(OWOWCache.java:2779)
	at com.orientechnologies.orient.core.storage.cache.local.OWOWCache.access$2300(OWOWCache.java:109)
	at com.orientechnologies.orient.core.storage.cache.local.OWOWCache$PeriodicFlushTask.run(OWOWCache.java:2546)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

2020-06-24 10:54:03:324 SEVER Can not flush data because of issue during data write, You cannot access outside the file size (65536 bytes). You have requested portion from 0-131072 bytes. File: File: keydok_2_2759850.cpm os-size=66560, stored=65536 [OWOWCache$PeriodicFlushTask]Exception during calling of shutdown handler OShutdownOrientDBInstancesHandler
com.orientechnologies.orient.core.exception.OStorageException: Error during closing the storages
	at com.orientechnologies.orient.core.db.OrientDBEmbedded.internalClose(OrientDBEmbedded.java:794)
	at com.orientechnologies.orient.core.Orient$OShutdownOrientDBInstancesHandler.shutdown(Orient.java:799)
	at com.orientechnologies.orient.core.Orient.shutdown(Orient.java:373)
	at com.orientechnologies.orient.server.OServer.deinit(OServer.java:581)
	at com.orientechnologies.orient.server.OServer.shutdown(OServer.java:500)
	at com.orientechnologies.orient.server.OServerShutdownHook.run(OServerShutdownHook.java:40)
Caused by: com.orientechnologies.orient.core.exception.OStorageException: Error in data flush background thread, please restart database and send full stack trace inside of bug report
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.checkReadOnlyConditions(OAbstractPaginatedStorage.java:5719)
	at com.orientechnologies.orient.core.storage.impl.local.paginated.atomicoperations.OAtomicOperationsManager.checkReadOnlyConditions(OAtomicOperationsManager.java:142)
	at com.orientechnologies.orient.core.storage.impl.local.paginated.atomicoperations.OAtomicOperationsManager.startAtomicOperation(OAtomicOperationsManager.java:135)
	at com.orientechnologies.orient.core.storage.impl.local.paginated.atomicoperations.OAtomicOperationsManager.executeInsideAtomicOperation(OAtomicOperationsManager.java:173)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.doClose(OAbstractPaginatedStorage.java:5029)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.close(OAbstractPaginatedStorage.java:680)
	at com.orientechnologies.orient.core.storage.OStorageAbstract.shutdown(OStorageAbstract.java:214)
	at com.orientechnologies.orient.core.db.OrientDBEmbedded.internalClose(OrientDBEmbedded.java:777)
	... 5 more
Caused by: com.orientechnologies.common.io.OIOException: You cannot access outside the file size (65536 bytes). You have requested portion from 0-131072 bytes. File: File: keydok_2_2759850.cpm os-size=66560, stored=65536
	at com.orientechnologies.orient.core.storage.fs.OFileClassic.checkRegions(OFileClassic.java:307)
	at com.orientechnologies.orient.core.storage.fs.OFileClassic.write(OFileClassic.java:214)
	at com.orientechnologies.orient.core.storage.fs.OFileClassic.write(OFileClassic.java:228)
	at com.orientechnologies.orient.core.storage.cache.local.OWOWCache.flushPages(OWOWCache.java:2871)
	at com.orientechnologies.orient.core.storage.cache.local.OWOWCache.flushWriteCacheFromMinLSN(OWOWCache.java:2779)
	at com.orientechnologies.orient.core.storage.cache.local.OWOWCache.access$2300(OWOWCache.java:109)
	at com.orientechnologies.orient.core.storage.cache.local.OWOWCache$PeriodicFlushTask.run(OWOWCache.java:2546)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

2020-06-24 10:54:03:447 SEVER Can not flush data because of issue during data write, You cannot access outside the file size (65536 bytes). You have requested portion from 0-131072 bytes. File: File: keydok_2_2759850.cpm os-size=66560, stored=65536 [OWOWCache$PeriodicFlushTask]
2020-06-24 10:54:03:447 INFO  Clearing byte buffer pool [Orient]
2020-06-24 10:54:03:475 SEVER Can not flush data because of issue during data write, You cannot access outside the file size (65536 bytes). You have requested portion from 0-131072 bytes. File: File: keydok_2_2759850.cpm os-size=66560, stored=65536 [OWOWCache$PeriodicFlushTask]
2020-06-24 10:54:03:505 SEVER Can not flush data because of issue during data write, You cannot access outside the file size (65536 bytes). You have requested portion from 0-131072 bytes. File: File: keydok_2_2759850.cpm os-size=66560, stored=65536 [OWOWCache$PeriodicFlushTask]
2020-06-24 10:54:03:533 SEVER Can not flush data because of issue during data write, You cannot access outside the file size (65536 bytes). You have requested portion from 0-131072 bytes. File: File: keydok_2_2759850.cpm os-size=66560, stored=65536 [OWOWCache$PeriodicFlushTask]
2020-06-24 10:54:03:561 SEVER Can not flush data because of issue during data write, You cannot access outside the file size (65536 bytes). You have requested portion from 0-131072 bytes. File: File: keydok_2_2759850.cpm os-size=66560, stored=65536 [OWOWCache$PeriodicFlushTask]
2020-06-24 10:54:03:591 SEVER Can not flush data because of issue during data write, You cannot access outside the file size (65536 bytes). You have requested portion from 0-131072 bytes. File: File: keydok_2_2759850.cpm os-size=66560, stored=65536 [OWOWCache$PeriodicFlushTask]
2020-06-24 10:54:03:619 SEVER Can not flush data because of issue during data write, You cannot access outside the file size (65536 bytes). You have requested portion from 0-131072 bytes. File: File: keydok_2_2759850.cpm os-size=66560, stored=65536 [OWOWCache$PeriodicFlushTask]
2020-06-24 10:54:03:647 SEVER Can not flush data because of issue during data write, You cannot access outside the file size (65536 bytes). You have requested portion from 0-131072 bytes. File: File: keydok_2_2759850.cpm os-size=66560, stored=65536 [OWOWCache$PeriodicFlushTask]
2020-06-24 10:54:03:673 SEVER Can not flush data because of issue during data write, You cannot access outside the file size (65536 bytes). You have requested portion from 0-131072 bytes. File: File: keydok_2_2759850.cpm os-size=66560, stored=65536 [OWOWCache$PeriodicFlushTask]
2020-06-24 10:54:03:699 SEVER Can not flush data because of issue during data write, You cannot access outside the file size (65536 bytes). You have requested portion from 0-131072 bytes. File: File: keydok_2_2759850.cpm os-size=66560, stored=65536 [OWOWCache$PeriodicFlushTask]
`

## Steps to reproduce  
The error suddenly appears. I haven't identify any pattern or conditions in order to this exception appears.

**Comment by laa** [comment]
Hi @CanonTino . Did you switch off `storage.diskCache.useAsyncIO` parameter? This parameter was used to smooth migration to the async io in development and should not be changed in production. OFileClassic class, which you use right now is not supported any more and will be removed in next versions. So I do not suggest to use it.

**Comment by laa** [comment]
Oh, I suppose I got it how that happens. We will release a version with a fix during a week.

**Comment by CanonTino** [comment]
Hi @laa sorry I didn’t reply before but it is sun rising  here in Mexico.

Thank you so much for your answers. I’ll check the release you mentioned.

**Comment by laa** [comment]
Fixed. We are going to release hotfix next week.

**Comment by VincentSleepless** [comment]
i found same question in 3.1.5~ plz check ! it flush all most 2gb log in a short time with SEVER Can not flush data because of issue during data write, and can not create thread!

**Comment by andrii0lomakin** [comment]
Hi @VincentSleepless . Not sure that I understood you. Do you have this issue ?
