### ISSUE TITLE
OutOfMemoryError caused by Nessus scan

### ISSUE THREAD

**Issue by ygyg70** [orientechnologies/orientdb#9327]
## Expected behavior  
Nessus scan request ignored  gracefully

## Actual behavior  
Orient tries to read 1.2 GB of data and throws OOM error

## Steps to reproduce  
Run Nessus scan on a server embedding OriebtDB:
https://www.tenable.com/products/nessus

java.lang.OutOfMemoryError: Java heap space
	at com.orientechnologies.orient.enterprise.channel.binary.OChannelBinary.readString(OChannelBinary.java:150)
	at com.orientechnologies.orient.client.remote.message.OSetGlobalConfigurationRequest.read(OSetGlobalConfigurationRequest.java:34)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.sessionRequest(ONetworkProtocolBinary.java:281)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.execute(ONetworkProtocolBinary.java:211)
	at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:69)

**Comment by lvca** [comment]
What's the query? We suggest upgrading to the latest 3.1.x where such memory issues have been resolved.
