### ISSUE TITLE
Cannot route TX operation against distributed node

### ISSUE THREAD

**Issue by madmac2501** [orientechnologies/orientdb#9361]
## Expected behavior  
Distributed mode is stable.

Aside from this please let me know when is ok to test the distributed mode in 3.1.2-SNAPSHOT version. Thanks!

## Actual behavior  
I get this exception when just writing anything into the database

java.lang.NullPointerException
Error on transaction commit `618061B9`
com.orientechnologies.orient.core.exception.OStorageException: Cannot route TX operation against distributed node
	DB name="xxx"
	at com.orientechnologies.orient.server.distributed.impl.ODistributedStorage.handleDistributedException(ODistributedStorage.java:773)
	at com.orientechnologies.orient.server.distributed.impl.ODatabaseDocumentDistributed.distributedCommitV1(ODatabaseDocumentDistributed.java:460)
	at com.orientechnologies.orient.server.distributed.impl.ODatabaseDocumentDistributed.internalCommit(ODatabaseDocumentDistributed.java:400)
	at com.orientechnologies.orient.core.tx.OTransactionOptimistic.doCommit(OTransactionOptimistic.java:602)
	at com.orientechnologies.orient.core.tx.OTransactionOptimistic.commit(OTransactionOptimistic.java:106)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentAbstract.commit(ODatabaseDocumentAbstract.java:1984)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentAbstract.commit(ODatabaseDocumentAbstract.java:1954)
	at com.orientechnologies.orient.core.sql.parser.OCommitStatement.executeSimple(OCommitStatement.java:30)
	at com.orientechnologies.orient.core.sql.executor.OSingleOpExecutionPlan.executeInternal(OSingleOpExecutionPlan.java:95)
	at com.orientechnologies.orient.core.sql.executor.ScriptLineStep.syncPull(ScriptLineStep.java:37)
	at com.orientechnologies.orient.core.sql.executor.OScriptExecutionPlan.doExecute(OScriptExecutionPlan.java:78)
	at com.orientechnologies.orient.core.sql.executor.OScriptExecutionPlan.fetchNext(OScriptExecutionPlan.java:39)
	at com.orientechnologies.orient.core.sql.parser.OLocalResultSet.fetchNext(OLocalResultSet.java:36)
	at com.orientechnologies.orient.core.sql.parser.OLocalResultSet.<init>(OLocalResultSet.java:27)
	at com.orientechnologies.orient.core.command.OSqlScriptExecutor.executeInternal(OSqlScriptExecutor.java:126)
	at com.orientechnologies.orient.core.command.OSqlScriptExecutor.execute(OSqlScriptExecutor.java:65)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentEmbedded.execute(ODatabaseDocumentEmbedded.java:675)
	at com.orientechnologies.orient.server.OConnectionBinaryExecutor.executeQuery(OConnectionBinaryExecutor.java:1494)
	at com.orientechnologies.orient.client.remote.message.OQueryRequest.execute(OQueryRequest.java:143)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.sessionRequest(ONetworkProtocolBinary.java:354)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.execute(ONetworkProtocolBinary.java:238)
	at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:67)
Caused by: java.lang.NullPointerException

## Steps to reproduce  
Setup a 3 node distributed database with 3.1.2-snapshot from 20200729
Write to a node

**Comment by leoChaoGlut** [comment]
+1

**Comment by leoChaoGlut** [comment]
3.0.34 without this problem

**Comment by VincentSleepless** [comment]
+1 in 3.1.5
