### ISSUE TITLE
com.orientechnologies.orient.server.distributed.task.ODistributedRecordLockedException: Timeout (100ms) on acquiring lock

### ISSUE THREAD

**Issue by vishalugor** [orientechnologies/orientdb#9362]
## Expected behavior  
Data get inserted  

## Actual behavior  
Getting below exception
com.orientechnologies.orient.server.distributed.task.ODistributedRecordLockedException: Timeout (100ms) on acquiring lock on record #202:-1 on server 'vishal01'. ^M
        DB name="vishald"^M
        DB name="vishald"
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_251]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_251]
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_251]
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_251]
        at com.orientechnologies.orient.client.binary.OChannelBinaryAsynchClient.handleException(OChannelBinaryAsynchClient.java:357) ~[orientdb-client-3.1.1.jar:3.1.1]
        at com.orientechnologies.orient.client.binary.OChannelBinaryAsynchClient.handleStatus(OChannelBinaryAsynchClient.java:305) ~[orientdb-client-3.1.1.jar:3.1.1]
        at com.orientechnologies.orient.client.binary.OChannelBinaryAsynchClient.handleStatus(OChannelBinaryAsynchClient.java:327) ~[orientdb-client-3.1.1.jar:3.1.1]
        at com.orientechnologies.orient.client.binary.OChannelBinaryAsynchClient.beginResponse(OChannelBinaryAsynchClient.java:211) ~[orientdb-client-3.1.1.jar:3.1.1]
        at com.orientechnologies.orient.client.binary.OChannelBinaryAsynchClient.beginResponse(OChannelBinaryAsynchClient.java:169) ~[orientdb-client-3.1.1.jar:3.1.1]
        at com.orientechnologies.orient.client.remote.OStorageRemote.beginResponse(OStorageRemote.java:2221) ~[orientdb-client-3.1.1.jar:3.1.1]
        at com.orientechnologies.orient.client.remote.OStorageRemote.lambda$networkOperationRetryTimeout$2(OStorageRemote.java:385) ~[orientdb-client-3.1.1.jar:3.1.1]
        at com.orientechnologies.orient.client.remote.OStorageRemote.baseNetworkOperation(OStorageRemote.java:447) ~[orientdb-client-3.1.1.jar:3.1.1]
        at com.orientechnologies.orient.client.remote.OStorageRemote.networkOperationRetryTimeout(OStorageRemote.java:365) ~[orientdb-client-3.1.1.jar:3.1.1]
        at com.orientechnologies.orient.client.remote.OStorageRemote.networkOperationNoRetry(OStorageRemote.java:400) ~[orientdb-client-3.1.1.jar:3.1.1]
        at com.orientechnologies.orient.client.remote.OStorageRemote.commit(OStorageRemote.java:1304) ~[orientdb-client-3.1.1.jar:3.1.1]
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentAbstract.internalCommit(ODatabaseDocumentAbstract.java:2466) ~[orientdb-core-3.1.1.jar:3.1.1]
        at com.orientechnologies.orient.core.tx.OTransactionOptimistic.doCommit(OTransactionOptimistic.java:602) ~[orientdb-core-3.1.1.jar:3.1.1]
        at com.orientechnologies.orient.core.tx.OTransactionOptimistic.commit(OTransactionOptimistic.java:106) ~[orientdb-core-3.1.1.jar:3.1.1]
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentAbstract.commit(ODatabaseDocumentAbstract.java:1984) ~[orientdb-core-3.1.1.jar:3.1.1]
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentAbstract.commit(ODatabaseDocumentAbstract.java:1954) ~[orientdb-core-3.1.1.jar:3.1.1]

## Using below code to acquire acquire connection  

private OrientDBUtil () {
		orientDB = new OrientDB("remote:vishal01, vishal02","root","xxx", OrientDBConfig.defaultConfig());

		OrientDBConfigBuilder poolCfg = OrientDBConfig.builder();
		poolCfg.addConfig(OGlobalConfiguration.DB_POOL_ACQUIRE_TIMEOUT, 1000);
		poolCfg.addConfig(OGlobalConfiguration.CLIENT_CHANNEL_MAX_POOL, 5000);
		poolCfg.addConfig(OGlobalConfiguration.DB_POOL_MIN, 50);
		poolCfg.addConfig(OGlobalConfiguration.DB_POOL_MAX, 100);
		pool = new ODatabasePool(orientDB,"vishald","root","xxx", poolCfg.build()); 
	} 
	
	public ODatabasePool connection() {
		return this.pool;
	}

Multiple threads are inserting the different data in distributed server vishal01 & vishal02

**Comment by lucafrosini** [comment]
I'm experiencing the same issue with version 3.0.34 as well as 3.0.29 with no other concurrent access.
I tried to use just one instance still running in distributed mode.

To experience the issue it is enogh to run the following command in in Studio:
DELETE VERTEX <MyVertexClass>

Removing the distributed configuration I have no issues.

Let me know if you need more details such as full configuration and/or a DB dump
