### ISSUE TITLE
deadlock when writing in parallel from several java clients

### ISSUE THREAD

**Issue by madmac2501** [orientechnologies/orientdb#9371]
## Expected behavior  
OrientDB is more resilient to errors.
Advice on a simple java client to write to OrientDB

## Actual behavior  
OrientDB master deadlocks

## Steps to reproduce  
I have a deployment with 1 master and 2 replicas
The main thing that I think that affects is that I'm writing in parallel from several java clients

I've attached a thread dump with 36 blocked threads
[thread_dump.txt](https://github.com/orientechnologies/orientdb/files/5067898/thread_dump.txt)

After analyzing it in https://spotify.github.io/threaddump-analyzer/ I see that one thread has a lock and all the rest are waiting for it. The thread is blocked in a socket write operation and another thing that I have seen is that the TCP connection 172.26.75.92:41320 no longer exists.

Please add some mechanism to at least mitigate this by adding a timeout or configuration. And also please point me to an example of a properly implemented java client writer.

Thanks a lot

`
"OrientDB (/172.26.76.23:2424) <- BinaryClient (/172.26.75.92:41320)": running, holding [0x00000005c307c030, 0x00000005c307c228, 0x00000005c309a4a0]
	at java.net.SocketOutputStream.socketWrite0(Native Method)
	at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:111)
	at java.net.SocketOutputStream.write(SocketOutputStream.java:155)
	at java.io.BufferedOutputStream.write(BufferedOutputStream.java:122)
	at java.io.DataOutputStream.write(DataOutputStream.java:107)
	at java.io.FilterOutputStream.write(FilterOutputStream.java:97)
	at com.orientechnologies.orient.client.remote.message.OMessageHelper.writeTransactionEntry(OMessageHelper.java:192)
	at com.orientechnologies.orient.server.distributed.impl.task.OTransactionPhase1Task.toStream(OTransactionPhase1Task.java:218)
	at com.orientechnologies.orient.server.distributed.ODistributedRequest.toStream(ODistributedRequest.java:100)
	at com.orientechnologies.orient.server.distributed.ORemoteServerChannel.lambda$sendRequest$0(ORemoteServerChannel.java:103)
	at com.orientechnologies.orient.server.distributed.ORemoteServerChannel$$Lambda$201/461793454.execute(Unknown Source)
	at com.orientechnologies.orient.server.distributed.ORemoteServerChannel.networkOperation(ORemoteServerChannel.java:159)
	at com.orientechnologies.orient.server.distributed.ORemoteServerChannel.sendRequest(ORemoteServerChannel.java:102)
	at com.orientechnologies.orient.server.distributed.ORemoteServerController.sendRequest(ORemoteServerController.java:66)
	at com.orientechnologies.orient.server.distributed.impl.ODistributedDatabaseImpl.send2Nodes(ODistributedDatabaseImpl.java:498)
	at com.orientechnologies.orient.server.distributed.impl.ODistributedAbstractPlugin.sendRequest(ODistributedAbstractPlugin.java:625)
	at com.orientechnologies.orient.server.distributed.impl.ONewDistributedTransactionManager.retriedCommit(ONewDistributedTransactionManager.java:196)
	at com.orientechnologies.orient.server.distributed.impl.ONewDistributedTransactionManager.commit(ONewDistributedTransactionManager.java:84)
	at com.orientechnologies.orient.server.distributed.impl.ODatabaseDocumentDistributed.internalCommit(ODatabaseDocumentDistributed.java:372)
	at com.orientechnologies.orient.core.tx.OTransactionOptimistic.doCommit(OTransactionOptimistic.java:533)
	at com.orientechnologies.orient.core.tx.OTransactionOptimistic.commit(OTransactionOptimistic.java:103)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentAbstract.commit(ODatabaseDocumentAbstract.java:2238)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentAbstract.commit(ODatabaseDocumentAbstract.java:2208)
	at com.orientechnologies.orient.core.sql.parser.OCommitStatement.executeSimple(OCommitStatement.java:30)
	at com.orientechnologies.orient.core.sql.executor.OSingleOpExecutionPlan.executeInternal(OSingleOpExecutionPlan.java:99)
	at com.orientechnologies.orient.core.sql.executor.ScriptLineStep.syncPull(ScriptLineStep.java:37)
	at com.orientechnologies.orient.core.sql.executor.OScriptExecutionPlan.doExecute(OScriptExecutionPlan.java:89)
	at com.orientechnologies.orient.core.sql.executor.OScriptExecutionPlan.fetchNext(OScriptExecutionPlan.java:50)
	at com.orientechnologies.orient.core.sql.parser.OLocalResultSet.fetchNext(OLocalResultSet.java:39)
	at com.orientechnologies.orient.core.sql.parser.OLocalResultSet.<init>(OLocalResultSet.java:30)
	at com.orientechnologies.orient.core.command.OSqlScriptExecutor.executeInternal(OSqlScriptExecutor.java:114)
	at com.orientechnologies.orient.core.command.OSqlScriptExecutor.execute(OSqlScriptExecutor.java:60)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentEmbedded.execute(ODatabaseDocumentEmbedded.java:638)
	at com.orientechnologies.orient.server.OConnectionBinaryExecutor.executeQuery(OConnectionBinaryExecutor.java:1192)
	at com.orientechnologies.orient.client.remote.message.OQueryRequest.execute(OQueryRequest.java:136)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.sessionRequest(ONetworkProtocolBinary.java:319)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.execute(ONetworkProtocolBinary.java:214)
	at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:69)`

**Comment by tglman** [comment]
Hi,

As you point also on the stack trace there is a thread writing on the socket that, block the others, the lock that we use has the granularity of record, so if there are multiple transactions trying to do write on a specific record they will go ahead 1 by 1.

Regards

**Comment by madmac2501** [comment]
Hi,

in this case these the thread have been locked for hours in that point without progressing.

Thanks for taking a look at it!

**Comment by madmac2501** [comment]
Hi,

it just happened to me again. I was deleting from OrientDB using this query with the Orientdb web ui. No insertion was being done at the same time.

BEGIN;
DELETE VERTEX myVertex where age < (SYSDATE().asLong() - 86400000) LIMIT 5000;
COMMIT;

[thread_dump_delete.txt](https://github.com/orientechnologies/orientdb/files/5080289/thread_dump_delete.txt)


The deadlocked thread was "OrientDB HTTP Connection /172.26.76.23:2480<-/172.26.16.95:34428" and I found that the TCP connection was in CLOSE_WAIT state

tcp6       1      0 172.26.76.23:2480       172.26.16.95:34428      CLOSE_WAIT  31423/java  

Best regards

**Comment by ozgursucu** [comment]
Hi @madmac2501 what is the current situation of this problem? Actually we have updated from 3.0.24 to 3.1.15 but we are facing deadlock issues much higher than 3.0.24 so we will try the latest 3.0.x version.

**Comment by madmac2501** [comment]
Hi, I moved to another solution and no longer use OrientDB.

Thanks for asking.

**Comment by ozgursucu** [comment]
Which solution have you applied?

**Comment by madmac2501** [comment]
I used a different product.

**Comment by tglman** [comment]
hi @ozgursucu 

Could you try 3.2.x ?

Regards
