### ISSUE TITLE
server.sh: Could not initialize class com.kenai.jffi.MemoryIO$SingletonHolder at com.kenai.jffi.MemoryIO.getInstance(MemoryIO.java:64)

### ISSUE THREAD

**Issue by slederman** [orientechnologies/orientdb#9395]
## Expected behavior  
Orientdb server should start when I run ./server.sh from the bin directory.

## Actual behavior  
removing old pid file /ai/orientdb-3.1.2/bin/orient.pid

2020-09-21 14:56:42:830 INFO  Can not detect value of limit of open files. [ONative]
2020-09-21 14:56:42:838 INFO  Default limit of open files (512) will be used. [ONative]
2020-09-21 14:56:42:856 INFO  Loading configuration from: /ai/orientdb-3.1.2/config/orientdb-server-config.xml... [OServerConfigurationLoaderXml]
2020-09-21 14:56:43:252 INFO  OrientDB Server v3.1.2 - Veloce (build 555d4a1824fdc980c2c2a680a840d68fc03f3b5e, branch 3.1.x) is starting up... [OServer]
2020-09-21 14:56:43:827 INFO  405541326848 B/386754 MB/377 GB of physical memory were detected on machine [ONative]
2020-09-21 14:56:43:828 INFO  Can not detect memory limit value. [ONative]
2020-09-21 14:56:43:829 INFO  Path to 'memory' cgroup is '/' [ONative]
2020-09-21 14:56:43:835 INFO  Mounting path for memory cgroup controller is '/sys/fs/cgroup/memory' [ONative]
2020-09-21 14:56:43:836 INFO  cgroup soft memory limit is 9223372036854771712 B/8796093022207 MB/8589934591 GB [ONative]
2020-09-21 14:56:43:837 INFO  cgroup hard memory limit is 9223372036854771712 B/8796093022207 MB/8589934591 GB [ONative]
2020-09-21 14:56:43:838 INFO  Detected memory limit for current process is 405541326848 B/386754 MB/377 GB [ONative]
2020-09-21 14:56:43:840 INFO  JVM can use maximum 1963MB of heap memory [OMemoryAndLocalPaginatedEnginesInitializer]
2020-09-21 14:56:43:841 INFO  Because OrientDB is running outside a container 2g of memory will be left unallocated according to the setting 'memory.leftToOS' not taking into account heap memory [OMemoryAndLocalPaginatedEnginesInitializer]
2020-09-21 14:56:43:841 INFO  OrientDB auto-config DISKCACHE=382,743MB (heap=1,963MB os=386,754MB) [orientechnologies]
2020-09-21 14:56:43:847 INFO  System is started under an effective user : `user` 
[OEngineLocalPaginated]
2020-09-21 14:56:43:869 INFO  Allocation of 5817693 pages. [OEngineLocalPaginated]
2020-09-21 14:56:44:038 INFO  WAL maximum segment size is set to 7,530 MB [OrientDBEmbedded]
2020-09-21 14:56:44:062 INFO  Databases directory: /ai/orientdb-3.1.2/databases [OServer]
2020-09-21 14:56:44:110 INFO  Creating the system database 'OSystem' for current server [OSystemDatabase]
2020-09-21 14:56:44:172 INFO  Page size for WAL located in /ai/orientdb-3.1.2/databases/OSystem is set to 4096 bytes. [CASDiskWriteAheadLog]Exception `480B7195` in storage `plocal:/ai/orientdb-3.1.2/databases/OSystem`: 3.1.2 - Veloce (build 555d4a1824fdc980c2c2a680a840d68fc03f3b5e, branch 3.1.x)
java.lang.NoClassDefFoundError: Could not initialize class com.kenai.jffi.MemoryIO$SingletonHolder
        at com.kenai.jffi.MemoryIO.getInstance(MemoryIO.java:64)
        at com.orientechnologies.common.directmemory.ODirectMemoryAllocator.allocate(ODirectMemoryAllocator.java:123)
        at com.orientechnologies.orient.core.storage.impl.local.paginated.wal.cas.CASDiskWriteAheadLog.<init>(CASDiskWriteAheadLog.java:393)
        at com.orientechnologies.orient.core.storage.disk.OLocalPaginatedStorage.initWalAndDiskCache(OLocalPaginatedStorage.java:786)
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.create(OAbstractPaginatedStorage.java:731)
        at com.orientechnologies.orient.core.storage.disk.OLocalPaginatedStorage.create(OLocalPaginatedStorage.java:207)
        at com.orientechnologies.orient.core.db.OrientDBEmbedded.internalCreate(OrientDBEmbedded.java:743)
        at com.orientechnologies.orient.core.db.OrientDBEmbedded.create(OrientDBEmbedded.java:635)
        at com.orientechnologies.orient.server.OSystemDatabase.init(OSystemDatabase.java:155)
        at com.orientechnologies.orient.server.OSystemDatabase.<init>(OSystemDatabase.java:50)
        at com.orientechnologies.orient.server.OServer.initSystemDatabase(OServer.java:1276)
        at com.orientechnologies.orient.server.OServer.activate(OServer.java:444)
        at com.orientechnologies.orient.server.OServerMain$1.run(OServerMain.java:49)
JVM error was thrown
java.lang.NoClassDefFoundError: Could not initialize class com.kenai.jffi.MemoryIO$SingletonHolder
        at com.kenai.jffi.MemoryIO.getInstance(MemoryIO.java:64)
        at com.orientechnologies.common.directmemory.ODirectMemoryAllocator.allocate(ODirectMemoryAllocator.java:123)
        at com.orientechnologies.orient.core.storage.impl.local.paginated.wal.cas.CASDiskWriteAheadLog.<init>(CASDiskWriteAheadLog.java:393)
        at com.orientechnologies.orient.core.storage.disk.OLocalPaginatedStorage.initWalAndDiskCache(OLocalPaginatedStorage.java:786)
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.create(OAbstractPaginatedStorage.java:731)
        at com.orientechnologies.orient.core.storage.disk.OLocalPaginatedStorage.create(OLocalPaginatedStorage.java:207)
        at com.orientechnologies.orient.core.db.OrientDBEmbedded.internalCreate(OrientDBEmbedded.java:743)
        at com.orientechnologies.orient.core.db.OrientDBEmbedded.create(OrientDBEmbedded.java:635)
        at com.orientechnologies.orient.server.OSystemDatabase.init(OSystemDatabase.java:155)
        at com.orientechnologies.orient.server.OSystemDatabase.<init>(OSystemDatabase.java:50)
        at com.orientechnologies.orient.server.OServer.initSystemDatabase(OServer.java:1276)
        at com.orientechnologies.orient.server.OServer.activate(OServer.java:444)
        at com.orientechnologies.orient.server.OServerMain$1.run(OServerMain.java:49)
Exception `480B7195` in storage `plocal:/ai/orientdb-3.1.2/databases/OSystem`: 3.1.2 - Veloce (build 555d4a1824fdc980c2c2a680a840d68fc03f3b5e, branch 3.1.x)
java.lang.NoClassDefFoundError: Could not initialize class com.kenai.jffi.MemoryIO$SingletonHolder
        at com.kenai.jffi.MemoryIO.getInstance(MemoryIO.java:64)
        at com.orientechnologies.common.directmemory.ODirectMemoryAllocator.allocate(ODirectMemoryAllocator.java:123)
        at com.orientechnologies.orient.core.storage.impl.local.paginated.wal.cas.CASDiskWriteAheadLog.<init>(CASDiskWriteAheadLog.java:393)
        at com.orientechnologies.orient.core.storage.disk.OLocalPaginatedStorage.initWalAndDiskCache(OLocalPaginatedStorage.java:786)
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.create(OAbstractPaginatedStorage.java:731)
        at com.orientechnologies.orient.core.storage.disk.OLocalPaginatedStorage.create(OLocalPaginatedStorage.java:207)
        at com.orientechnologies.orient.core.db.OrientDBEmbedded.internalCreate(OrientDBEmbedded.java:743)
        at com.orientechnologies.orient.core.db.OrientDBEmbedded.create(OrientDBEmbedded.java:635)
        at com.orientechnologies.orient.server.OSystemDatabase.init(OSystemDatabase.java:155)
        at com.orientechnologies.orient.server.OSystemDatabase.<init>(OSystemDatabase.java:50)
        at com.orientechnologies.orient.server.OServer.initSystemDatabase(OServer.java:1276)
        at com.orientechnologies.orient.server.OServer.activate(OServer.java:444)
        at com.orientechnologies.orient.server.OServerMain$1.run(OServerMain.java:49)
Exception in thread "Thread-0" java.lang.NoClassDefFoundError: Could not initialize class com.kenai.jffi.MemoryIO$SingletonHolder
        at com.kenai.jffi.MemoryIO.getInstance(MemoryIO.java:64)
        at com.orientechnologies.common.directmemory.ODirectMemoryAllocator.allocate(ODirectMemoryAllocator.java:123)
        at com.orientechnologies.orient.core.storage.impl.local.paginated.wal.cas.CASDiskWriteAheadLog.<init>(CASDiskWriteAheadLog.java:393)
        at com.orientechnologies.orient.core.storage.disk.OLocalPaginatedStorage.initWalAndDiskCache(OLocalPaginatedStorage.java:786)
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.create(OAbstractPaginatedStorage.java:731)
        at com.orientechnologies.orient.core.storage.disk.OLocalPaginatedStorage.create(OLocalPaginatedStorage.java:207)
        at com.orientechnologies.orient.core.db.OrientDBEmbedded.internalCreate(OrientDBEmbedded.java:743)
        at com.orientechnologies.orient.core.db.OrientDBEmbedded.create(OrientDBEmbedded.java:635)
        at com.orientechnologies.orient.server.OSystemDatabase.init(OSystemDatabase.java:155)
        at com.orientechnologies.orient.server.OSystemDatabase.<init>(OSystemDatabase.java:50)
        at com.orientechnologies.orient.server.OServer.initSystemDatabase(OServer.java:1276)
        at com.orientechnologies.orient.server.OServer.activate(OServer.java:444)
        at com.orientechnologies.orient.server.OServerMain$1.run(OServerMain.java:49)

## Steps to reproduce  
cd {orientdb}/bin
./server.sh

**Comment by andrii0lomakin** [comment]
Hi, likely database does not have access to the `/tmp` folder which doesn't allow to deploy temporary lib to access native functions.

**Comment by slederman** [comment]
Yes, that was the problem. Redirecting the JVM  to a different temp folder fixed the problem. Thanks.

**Comment by ritdubal3011** [comment]
I'm getting the same error while running orientdb server.
I tried redirecting to a different path of `TMP_MOUNT`, which is in `orientdb/bin/backup.sh`, but did not work.

Any alternate solution?

**Comment by ErikNeudert** [comment]
I had the same problem on my M1 Mac, because Orient doesn't run with Arm JDK.
Resolved this using an x64 java:

set -x JAVA_HOME /Library/Java/JavaVirtualMachines/zulu-11.jdk.x64/Contents/Home
.../bin/server.sh
