### ISSUE TITLE
OrientDB deadlocked

### ISSUE THREAD

**Issue by madmac2501** [orientechnologies/orientdb#9400]
## Expected behavior  
OrientDB doesn't deadlock
[orient-server-boot.log](https://github.com/orientechnologies/orientdb/files/5313550/orient-server-boot.log)

## Actual behavior  
All OrientDB  requests are blocked, event the database cannot be listed

## Steps to reproduce  
I'm mostly upserting in parallel from multiple threads. I don't know the specific use case.

I've attached a thread dump

**Comment by madmac2501** [comment]
I've reviewed the logs and I thing this log may be related 

com.orientechnologies.orient.core.exception.OStorageException: Exception during execution of atomic operation inside of storage xxx
at com.orientechnologies.orient.core.storage.impl.local.paginated.atomicoperations.OAtomicOperationsManager.executeInsideAtomicOperation(OAtomicOperationsManager.java:157)
at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage$2.run(OAbstractPaginatedStorage.java:4884)
at com.orientechnologies.orient.core.Orient$3.run(Orient.java:419)
at java.util.TimerThread.mainLoop(Timer.java:555)
at java.util.TimerThread.run(Timer.java:505)
Caused by: java.lang.NullPointerException
at com.orientechnologies.orient.core.storage.ridbag.sbtree.OSBTreeCollectionManagerShared.tryDelete(OSBTreeCollectionManagerShared.java:198)
at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage$2.lambda$run$0(OAbstractPaginatedStorage.java:4885)
at com.orientechnologies.orient.core.storage.impl.local.paginated.atomicoperations.OAtomicOperationsManager.executeInsideAtomicOperation(OAtomicOperationsManager.java:153)
... 4 more

**Comment by andrii0lomakin** [comment]
Hi, thank you. That is very useful.

**Comment by andrii0lomakin** [comment]
Fixed in all branches.

**Comment by madmac2501** [comment]
@laa I think you already fixed this in commit eae3e3112b7005a243a7551460eb0e706331a4cb . I don't know if there are more possible changes to improve this situation.

**Comment by andrii0lomakin** [comment]
I do not completely understand did you check version with commit of without commit ?

**Comment by madmac2501** [comment]
I reproduced the issue with a version without the commit, sorry for the noise.
