### ISSUE TITLE
NPE during execution of simple SQL

### ISSUE THREAD

**Issue by PhantomYdn** [orientechnologies/orientdb#9405]
### OS: any

Execute the following SQL:

```sql
select from OMyAnyClass where any() containstext "test"
```

## Expected behavior  

SQL should be successfully executed as it was in OrientDB v2.

## Actual behavior  
NPE is happening:

```
java.lang.NullPointerException
     at com.orientechnologies.orient.core.sql.parser.OFunctionCall.execute(OFunctionCall.java:125)
     at com.orientechnologies.orient.core.sql.parser.OFunctionCall.execute(OFunctionCall.java:82)
     at com.orientechnologies.orient.core.sql.parser.OLevelZeroIdentifier.execute(OLevelZeroIdentifier.java:52)
     at com.orientechnologies.orient.core.sql.parser.OBaseIdentifier.execute(OBaseIdentifier.java:62)
     at com.orientechnologies.orient.core.sql.parser.OBaseExpression.execute(OBaseExpression.java:111)
     at com.orientechnologies.orient.core.sql.parser.OExpression.execute(OExpression.java:102)
     at com.orientechnologies.orient.core.sql.parser.OContainsTextCondition.evaluate(OContainsTextCondition.java:42)
     at com.orientechnologies.orient.core.sql.parser.ONotBlock.evaluate(ONotBlock.java:44)
     at com.orientechnologies.orient.core.sql.parser.OAndBlock.evaluate(OAndBlock.java:47)
     at com.orientechnologies.orient.core.sql.parser.OOrBlock.evaluate(OOrBlock.java:49)
     at com.orientechnologies.orient.core.sql.parser.OWhereClause.matchesFilters(OWhereClause.java:56)
     at com.orientechnologies.orient.core.sql.executor.FilterStep$1.fetchNextItem(FilterStep.java:64)
     at com.orientechnologies.orient.core.sql.executor.FilterStep$1.hasNext(FilterStep.java:87)
     at com.orientechnologies.orient.core.sql.executor.AggregateProjectionCalculationStep.executeAggregation(AggregateProjectionCalculationStep.java:91)
     at com.orientechnologies.orient.core.sql.executor.AggregateProjectionCalculationStep.syncPull(AggregateProjectionCalculationStep.java:43)
     at com.orientechnologies.orient.core.sql.executor.GuaranteeEmptyCountStep.syncPull(GuaranteeEmptyCountStep.java:25)
     at com.orientechnologies.orient.core.sql.executor.ProjectionCalculationStep.syncPull(ProjectionCalculationStep.java:27)
     at com.orientechnologies.orient.core.sql.executor.OSelectExecutionPlan.fetchNext(OSelectExecutionPlan.java:34)
     at com.orientechnologies.orient.core.sql.parser.OLocalResultSet.fetchNext(OLocalResultSet.java:36)
     at com.orientechnologies.orient.core.sql.parser.OLocalResultSet.<init>(OLocalResultSet.java:27)
     at com.orientechnologies.orient.core.sql.parser.OSelectStatement.execute(OSelectStatement.java:296)
     at com.orientechnologies.orient.core.sql.parser.OStatement.execute(OStatement.java:81)
     at com.orientechnologies.orient.core.db.document.ODatabaseDocumentEmbedded.query(ODatabaseDocumentEmbedded.java:573)
```

**Comment by PhantomYdn** [comment]
3.1.4 contains the same problem. Dear OrientDB team, @laa, @luigidellaquila, @tglman, please help to fix this issue in OrientDB query parser.

**Comment by PhantomYdn** [comment]
As it was said above, there is NPE in latest versions in attempt to execute mentioned query. But in 3.0.4 it was:
```
com.orientechnologies.orient.core.exception.OCommandExecutionException:
Funciton not found: any
        DB name="BroadSelectQueryTest"
        at com.orientechnologies.orient.core.sql.BroadSelectQueryTest.testCreateIndexOnMissingPropertyWithCollate(BroadSelectQueryTest.java:30)
```

This switch from OCommandExecutionException `Function not found` to NPE happened in the following commit: https://github.com/orientechnologies/orientdb/commit/aac5894ef98e7106071d0f03c40e421d5909bb93
(Yes - it's become funny after reading comment for this commit: fix NPE on function invocation - one fix for NPE lead to another NPE issue)

P.S. Still investigating where support of `any() containstext "test"` disappeared.

**Comment by luigidellaquila** [comment]
Hi @PhantomYdn 

Thank you very much for reporting, I'll check it ASAP.

Thanks

Luigi

**Comment by luigidellaquila** [comment]
Hi @PhantomYdn 

I just pushed a fix for this.
The fix will be released with next v 3.1.5

Thanks

Luigi

**Comment by PhantomYdn** [comment]
@luigidellaquila , thank you! But just my curiosity: is `all()` also supported?

**Comment by luigidellaquila** [comment]
Hi @PhantomYdn 

I didn't check it, but it's so unusual (I hardly find a meaningful use case for that) that I wouldn't be surprised if it doesn't work and nobody noticed

Thanks

Luigi

**Comment by PhantomYdn** [comment]
@luigidellaquila, we use `all()` in other place to verify that there is "at least something" in an object: as it's explained in documentation: https://orientdb.com/docs/last/sql/SQL-Where.html Btw, might be you can spot another part of this documentation page which shouldn't work in 3.x...

**Comment by luigidellaquila** [comment]
Hi @PhantomYdn 

Let me reopen this issue, I'll do a complete check

Thanks

Luigi

**Comment by PhantomYdn** [comment]
@luigidellaquila , @dritter-sap , closed by mistake, I guess?

**Comment by luigidellaquila** [comment]
Hi @PhantomYdn 

yes, closed with a commit (not intended I think).
Anyway, I already did a few checks and fixed some cases of usage of any() and all().
I still have to complete the checks though

Thanks

Luigi

**Comment by PhantomYdn** [comment]
@luigidellaquila, wanted to close ticket, but just found out that `any() containstext` doesn't work with EMBEDDEDMAP properly.

**Comment by PhantomYdn** [comment]
Seems to be related to #9474
