### ISSUE TITLE
OTrackedList cannot be cast to java.lang.Comparable

### ISSUE THREAD

**Issue by aberdev** [orientechnologies/orientdb#9411]
## Expected behavior  
Commit successuflly after insert or update 
## Actual behavior  
An exception is raised when  trying to commit a transaction but is not thrown to the client :
`java.lang.ClassCastException: com.orientechnologies.orient.core.db.record.OTrackedList cannot be cast to java.lang.Comparable
at java.util.TreeMap.compare(TreeMap.java:1294)
at java.util.TreeMap.put(TreeMap.java:538)
at com.orientechnologies.orient.client.remote.message.OMessageHelper.readTransactionIndexChanges(OMessageHelper.java:370)
at com.orientechnologies.orient.client.remote.message.OCommit37Request.read(OCommit37Request.java:108)
at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.sessionRequest(ONetworkProtocolBinary.java:282)
at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.execute(ONetworkProtocolBinary.java:212)
at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:69)`

## Steps to reproduce  
The exception doesn't occure for all inserts or update.It's related to the iserted data ?
Thanks

**Comment by tglman** [comment]
Hi @aberdev,

From this error seems that you are doing a transaction that include an indexed record, and there is an issue with the value of the field you are indexing, can you share more info on what kind of schema you have and what kind of record participate in the transaction ?

Bye

**Comment by lvca** [comment]
No answer, closing the issue for now. In case, please comment on this very issue.
