### ISSUE TITLE
AssertionError when opening DB which was created in 3.0.25 using 3.1.3

### ISSUE THREAD

**Issue by Jotschi** [orientechnologies/orientdb#9412]
I'm getting the following exception when opening a DB which was created in 3.0.25 using OrientDB 3.1.3

```
java.lang.AssertionError
	at com.orientechnologies.orient.core.storage.config.OClusterBasedStorageConfiguration.getUuid(OClusterBasedStorageConfiguration.java:724)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.lambda$open$1(OAbstractPaginatedStorage.java:450)
	at com.orientechnologies.orient.core.storage.impl.local.paginated.atomicoperations.OAtomicOperationsManager.executeInsideAtomicOperation(OAtomicOperationsManager.java:189)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.open(OAbstractPaginatedStorage.java:438)
	at com.orientechnologies.orient.core.db.OrientDBEmbedded.open(OrientDBEmbedded.java:483)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.open(ODatabaseDocumentTx.java:928)
	at com.orientechnologies.orient.core.db.OPartitionedDatabasePool$DatabaseDocumentTxPooled.internalOpen(OPartitionedDatabasePool.java:437)
	at com.orientechnologies.orient.core.db.OPartitionedDatabasePool.openDatabase(OPartitionedDatabasePool.java:304)
	at com.orientechnologies.orient.core.db.OPartitionedDatabasePool.acquire(OPartitionedDatabasePool.java:259)
	at com.tinkerpop.blueprints.impls.orient.OrientBaseGraph.<init>(OrientBaseGraph.java:178)
	at com.tinkerpop.blueprints.impls.orient.OrientTransactionalGraph.<init>(OrientTransactionalGraph.java:82)
	at com.tinkerpop.blueprints.impls.orient.OrientGraph.<init>(OrientGraph.java:125)
	at com.tinkerpop.blueprints.impls.orient.OrientGraphFactory$1.getGraph(OrientGraphFactory.java:92)
	at com.tinkerpop.blueprints.impls.orient.OrientGraphFactory.getTx(OrientGraphFactory.java:242)
	at com.gentics.mesh.graphdb.tx.impl.OrientLocalStorageImpl.rawTx(OrientLocalStorageImpl.java:55)
```

The assertion in `OClusterBasedStorageConfiguration#getUuid()` causes the problem.

Due to this assertion no null value will be returned and thus the null handling of `OAbstractPaginatedStorage#open` (Line 451) is not being used.

Removing the assertion lets our test pass and fixes the issue.

**Comment by luigidellaquila** [comment]
Hi @Jotschi 

This assert is not needed indeed, and it is not meaningful in terms of backward compatibility, so we just removed it

Thanks

Luigi

**Comment by Jotschi** [comment]
@luigidellaquila Thanks. I'm closing the issue.
