### ISSUE TITLE
Creation of a new database with OrientDB 3.1.3 fails

### ISSUE THREAD

**Issue by kai-baumann** [orientechnologies/orientdb#9415]
### Java Version:
openjdk version "1.8.0_265"
OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_265-b01)
OpenJDK 64-Bit Server VM (AdoptOpenJDK)(build 25.265-b01, mixed mode)
## Expected behavior  
Creation of a new datbase withOrientDB Studio.

## Actual behavior  
Creation of a new datbase withOrientDB Studio with the following exception:

`com.orientechnologies.common.jnr.LastErrorException: Error during execution of native call, error code 95
		at com.orientechnologies.common.jnr.ONative.checkLastError(ONative.java:328)
		at com.orientechnologies.common.jnr.ONative.fallocate(ONative.java:303)
		at com.orientechnologies.orient.core.storage.fs.AsyncFile.allocateSpace(AsyncFile.java:308)
		at com.orientechnologies.orient.core.storage.cache.local.OWOWCache.allocateNewPage(OWOWCache.java:1203)
		at com.orientechnologies.orient.core.storage.cache.chm.AsyncReadCache.allocateNewPage(AsyncReadCache.java:372)
		at com.orientechnologies.orient.core.storage.impl.local.paginated.atomicoperations.OAtomicOperationBinaryTracking.commitChanges(OAtomicOperationBinaryTracking.java:532)
		at com.orientechnologies.orient.core.storage.impl.local.paginated.atomicoperations.OAtomicOperationsManager.endAtomicOperation(OAtomicOperationsManager.java:378)
		at com.orientechnologies.orient.core.storage.impl.local.paginated.atomicoperations.OAtomicOperationsManager.calculateInsideAtomicOperation(OAtomicOperationsManager.java:180)
		at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.addIndexEngine(OAbstractPaginatedStorage.java:2753)
		at com.orientechnologies.orient.core.index.OIndexAbstract.create(OIndexAbstract.java:239)
		at com.orientechnologies.orient.core.index.OIndexOneValue.create(OIndexOneValue.java:120)
		at com.orientechnologies.orient.core.index.OIndexOneValue.create(OIndexOneValue.java:46)
		at com.orientechnologies.orient.core.index.OIndexManagerShared.createIndex(OIndexManagerShared.java:200)
		at com.orientechnologies.orient.core.metadata.schema.OClassImpl.createIndex(OClassImpl.java:1118)
		at com.orientechnologies.orient.core.metadata.schema.OClassImpl.createIndex(OClassImpl.java:1075)
		at com.orientechnologies.orient.core.metadata.schema.OClassImpl.createIndex(OClassImpl.java:1058)
		at com.orientechnologies.orient.core.metadata.schema.OPropertyImpl.createIndex(OPropertyImpl.java:168)
		at com.orientechnologies.orient.core.metadata.schema.OPropertyImpl.createIndex(OPropertyImpl.java:153)
		at com.orientechnologies.orient.core.metadata.function.OFunctionLibraryImpl.init(OFunctionLibraryImpl.java:156)
		at com.orientechnologies.orient.core.metadata.function.OFunctionLibraryImpl.create(OFunctionLibraryImpl.java:59)
		at com.orientechnologies.orient.core.db.OSharedContextEmbedded.create(OSharedContextEmbedded.java:134)
		at com.orientechnologies.orient.core.db.document.ODatabaseDocumentEmbedded.createMetadata(ODatabaseDocumentEmbedded.java:301)
		at com.orientechnologies.orient.core.db.document.ODatabaseDocumentEmbedded.internalCreate(ODatabaseDocumentEmbedded.java:280)
		at com.orientechnologies.orient.core.db.OrientDBEmbedded.internalCreate(OrientDBEmbedded.java:756)
		at com.orientechnologies.orient.core.db.OrientDBEmbedded.create(OrientDBEmbedded.java:635)
		at com.orientechnologies.orient.server.OServer.createDatabase(OServer.java:1319)
		at com.orientechnologies.orient.server.network.protocol.http.command.post.OServerCommandPostDatabase.execute(OServerCommandPostDatabase.java:79)
		at com.orientechnologies.orient.server.network.protocol.http.ONetworkProtocolHttpAbstract.service(ONetworkProtocolHttpAbstract.java:253)
		at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:67)
		$ANSI{green {db=test}} Exception during index 'OFunction.name' creation
		com.orientechnologies.common.jnr.LastErrorException: Error during execution of native call, error code 95
		at com.orientechnologies.common.jnr.ONative.checkLastError(ONative.java:328)
		at com.orientechnologies.common.jnr.ONative.fallocate(ONative.java:303)
		at com.orientechnologies.orient.core.storage.fs.AsyncFile.allocateSpace(AsyncFile.java:308)
		at com.orientechnologies.orient.core.storage.cache.local.OWOWCache.allocateNewPage(OWOWCache.java:1203)
		at com.orientechnologies.orient.core.storage.cache.chm.AsyncReadCache.allocateNewPage(AsyncReadCache.java:372)
		at com.orientechnologies.orient.core.storage.impl.local.paginated.atomicoperations.OAtomicOperationBinaryTracking.commitChanges(OAtomicOperationBinaryTracking.java:532)
		at com.orientechnologies.orient.core.storage.impl.local.paginated.atomicoperations.OAtomicOperationsManager.endAtomicOperation(OAtomicOperationsManager.java:378)
		at com.orientechnologies.orient.core.storage.impl.local.paginated.atomicoperations.OAtomicOperationsManager.calculateInsideAtomicOperation(OAtomicOperationsManager.java:180)
		at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.addIndexEngine(OAbstractPaginatedStorage.java:2753)
		at com.orientechnologies.orient.core.index.OIndexAbstract.create(OIndexAbstract.java:239)
		at com.orientechnologies.orient.core.index.OIndexOneValue.create(OIndexOneValue.java:120)
		at com.orientechnologies.orient.core.index.OIndexOneValue.create(OIndexOneValue.java:46)
		at com.orientechnologies.orient.core.index.OIndexManagerShared.createIndex(OIndexManagerShared.java:200)
		at com.orientechnologies.orient.core.metadata.schema.OClassImpl.createIndex(OClassImpl.java:1075)
		at com.orientechnologies.orient.core.metadata.schema.OClassImpl.createIndex(OClassImpl.java:1058)
		at com.orientechnologies.orient.core.metadata.schema.OPropertyImpl.createIndex(OPropertyImpl.java:168)
		at com.orientechnologies.orient.core.metadata.schema.OPropertyImpl.createIndex(OPropertyImpl.java:153)
		at com.orientechnologies.orient.core.metadata.function.OFunctionLibraryImpl.init(OFunctionLibraryImpl.java:156)
		at com.orientechnologies.orient.core.metadata.function.OFunctionLibraryImpl.create(OFunctionLibraryImpl.java:59)
		at com.orientechnologies.orient.core.db.OSharedContextEmbedded.create(OSharedContextEmbedded.java:134)
		at com.orientechnologies.orient.core.db.document.ODatabaseDocumentEmbedded.createMetadata(ODatabaseDocumentEmbedded.java:301)
		at com.orientechnologies.orient.core.db.document.ODatabaseDocumentEmbedded.internalCreate(ODatabaseDocumentEmbedded.java:280)
		at com.orientechnologies.orient.core.db.OrientDBEmbedded.internalCreate(OrientDBEmbedded.java:756)
		at com.orientechnologies.orient.core.db.OrientDBEmbedded.create(OrientDBEmbedded.java:635)
		at com.orientechnologies.orient.server.OServer.createDatabase(OServer.java:1319)
		at com.orientechnologies.orient.server.network.protocol.http.command.post.OServerCommandPostDatabase.execute(OServerCommandPostDatabase.java:79)
		at com.orientechnologies.orient.server.network.protocol.http.ONetworkProtocolHttpAbstract.service(ONetworkProtocolHttpAbstract.java:253)
		at com.orientechnologies.orient.server.network.protocol.http.ONetworkProtocolHttpAbstract.execute(ONetworkProtocolHttpAbstract.java:813)
		at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:67)`

## Steps to reproduce
- Start the image orientdb:3.1.3 with a Windows 10 Docker Host.
- Open OrientDB Studio and create a new database.
- The error will be printed to the log of the docker image.

I created the following mounts:
volumes:
      - C:/.../databases:/orientdb/databases
      - C:/.../:/orientdb/backup
The last version i used before upgrading to 3.1.3 was 3.0.34. On this version everything works fine.

**Comment by kai-baumann** [comment]
If the volumes are removed then the error does not occur.

**Comment by andrii0lomakin** [comment]
Hi @kai-baumann , could you set `storage.disk.useNativeOsAPI` system property or server property in server-config.xml to false and try again ?

**Comment by kai-baumann** [comment]
Hello @laa, I added `<entry value="true" name="storage.disk.useNativeOsAPI"/>` at the end of the file `orientdb-server-config.xml ` but I still get the same error. Is this file correct or could I set an environment variable for the docker container?

**Comment by andrii0lomakin** [comment]
Hi @kai-baumann you should use not `true` value but `false`.

**Comment by kai-baumann** [comment]
Hello @laa, after setting the variable to `false` the container does start on a windows machine with mounted volumes.

**Comment by andrii0lomakin** [comment]
Good, thank you for the report.
