### ISSUE TITLE
java.lang.NullPointerException on trying to connect to database

### ISSUE THREAD

**Issue by nerfur** [orientechnologies/orientdb#9424]
## Expected behavior  
connecting to database

## Actual behavior  
not connecting to database

## Steps to reproduce  
Just trying to connect from Studio or console.sh and I suddenly get this, appears while simple testing orientdb fresh docker, create some databases, learning udemy course, bam only this one database is not accessible, others work ok

2020-10-28 08:53:16:070 INFO  Page size for WAL located in /orientdb/databases/eDCIPAM is set to 4096 bytes. [CASDiskWriteAheadLog]
2020-10-28 08:53:16:089 INFO  DWL:eDCIPAM: block size = 4096 bytes, maximum segment size = 12009 MB [DoubleWriteLogGL]Exception `33EBCDDC` in storage `plocal:/orientdb/databases/eDCIPAM`: 3.1.4 - Veloce (build 0d47e1cd37cb69c185fb4959e925863e8ca3abcf, branch UNKNOWN)
com.orientechnologies.orient.core.exception.OStorageException: Exception during execution of atomic operation inside of storage eDCIPAM
        at com.orientechnologies.orient.core.storage.impl.local.paginated.atomicoperations.OAtomicOperationsManager.executeInsideAtomicOperation(OAtomicOperationsManager.java:195)
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.open(OAbstractPaginatedStorage.java:438)
        at com.orientechnologies.orient.core.db.OrientDBEmbedded.openNoAuthenticate(OrientDBEmbedded.java:429)
        at com.orientechnologies.orient.core.db.OrientDBEmbedded.openNoAuthenticate(OrientDBEmbedded.java:78)
        at com.orientechnologies.orient.server.OServer.openDatabase(OServer.java:977)
        at com.orientechnologies.orient.server.OServer.openDatabase(OServer.java:943)
        at com.orientechnologies.orient.server.network.protocol.http.command.OServerCommandAuthenticatedDbAbstract.authenticate(OServerCommandAuthenticatedDbAbstract.java:193)
        at com.orientechnologies.orient.server.network.protocol.http.command.OServerCommandAuthenticatedDbAbstract.beforeExecute(OServerCommandAuthenticatedDbAbstract.java:135)
        at com.orientechnologies.orient.server.network.protocol.http.command.get.OServerCommandGetConnect.beforeExecute(OServerCommandGetConnect.java:55)
        at com.orientechnologies.orient.server.network.protocol.http.ONetworkProtocolHttpAbstract.service(ONetworkProtocolHttpAbstract.java:250)
        at com.orientechnologies.orient.server.network.protocol.http.ONetworkProtocolHttpAbstract.execute(ONetworkProtocolHttpAbstract.java:811)
        at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:67)
Caused by: java.lang.NullPointerException
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.checkRidBagsPresence(OAbstractPaginatedStorage.java:686)
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.lambda$open$1(OAbstractPaginatedStorage.java:466)
        at com.orientechnologies.orient.core.storage.impl.local.paginated.atomicoperations.OAtomicOperationsManager.executeInsideAtomicOperation(OAtomicOperationsManager.java:189)
        ... 11 more
Internal server error:

java.lang.NullPointerException
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.checkRidBagsPresence(OAbstractPaginatedStorage.java:686)
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.lambda$open$1(OAbstractPaginatedStorage.java:466)
        at com.orientechnologies.orient.core.storage.impl.local.paginated.atomicoperations.OAtomicOperationsManager.executeInsideAtomicOperation(OAtomicOperationsManager.java:189)
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.open(OAbstractPaginatedStorage.java:438)
        at com.orientechnologies.orient.core.db.OrientDBEmbedded.openNoAuthenticate(OrientDBEmbedded.java:429)
        at com.orientechnologies.orient.core.db.OrientDBEmbedded.openNoAuthenticate(OrientDBEmbedded.java:78)
        at com.orientechnologies.orient.server.OServer.openDatabase(OServer.java:977)
        at com.orientechnologies.orient.server.OServer.openDatabase(OServer.java:943)
        at com.orientechnologies.orient.server.network.protocol.http.command.OServerCommandAuthenticatedDbAbstract.authenticate(OServerCommandAuthenticatedDbAbstract.java:193)
        at com.orientechnologies.orient.server.network.protocol.http.command.OServerCommandAuthenticatedDbAbstract.beforeExecute(OServerCommandAuthenticatedDbAbstract.java:135)
        at com.orientechnologies.orient.server.network.protocol.http.command.get.OServerCommandGetConnect.beforeExecute(OServerCommandGetConnect.java:55)
        at com.orientechnologies.orient.server.network.protocol.http.ONetworkProtocolHttpAbstract.service(ONetworkProtocolHttpAbstract.java:250)
        at com.orientechnologies.orient.server.network.protocol.http.ONetworkProtocolHttpAbstract.execute(ONetworkProtocolHttpAbstract.java:811)
        at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:67)

**Comment by Jotschi** [comment]
@luigidellaquila FYI: I think this the same error that we reported via `757591 / 2020`.

**Comment by luigidellaquila** [comment]
Thank you for reporting @nerfur 

@Jotschi yes, I think it's the same, thank you for pointing it out.

We are already checking it, we'll give you an update ASAP

Thanks

Luigi

**Comment by luigidellaquila** [comment]
Hi @nerfur @Jotschi 

The fix is already on 3.1.x branch, the snapshot will be available in a few hours

Thanks

Luigi

**Comment by PhantomYdn** [comment]
Got the same problem... Database, unfortunately, becomes unusable.  Is there any chance to reanimate db? For example by taking 3.1.5?

**Comment by luigidellaquila** [comment]
Hi @PhantomYdn 

I'd suggest to try opening it with v 3.1.5-SNAPSHOT, it should be fine

https://oss.sonatype.org/content/repositories/snapshots/com/orientechnologies/orientdb-community/3.1.5-SNAPSHOT/

Thanks

Luigi
