### ISSUE TITLE
NullPointerException after migrating from 3.0.22 to 3.1.2

### ISSUE THREAD

**Issue by typingtanuki** [orientechnologies/orientdb#9425]
## Expected behavior  

Can migrate to 3.1.0 and use database.

## Actual behavior  

Migration goes fine, upon restart DB seems to work, but some inserts will fail with a NullPointerException

## Steps to reproduce  

* Create new database on 3.0.22
* Add some documents
* Stop database
* Switch to 3.1.2
* Start database
* Insert some documents
** Note: Seems to be more likely to happen in classes which were declared, but empty

Stacktrace:
```
ERROR OLocalPaginatedStorage - Exception `29216B00` in storage `plocal:C:\managementdb\edge`: 3.1.2 - Veloce (build 8b6ef394ce7b45017e84a65efb9ce7534c56aa8e, branch UNKNOWN)
java.lang.NullPointerException: null
    at com.orientechnologies.orient.core.index.engine.v1.OCellBTreeMultiValueIndexEngine.acquireAtomicExclusiveLock(OCellBTreeMultiValueIndexEngine.java:573)
    at com.orientechnologies.orient.core.index.OIndexAbstract.acquireAtomicExclusiveLock(OIndexAbstract.java:1019)
    at com.orientechnologies.orient.core.index.OIndexAbstractDelegate.acquireAtomicExclusiveLock(OIndexAbstractDelegate.java:376)
    at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.lockIndexes(OAbstractPaginatedStorage.java:6848)
    at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.commit(OAbstractPaginatedStorage.java:2452)
    at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.commit(OAbstractPaginatedStorage.java:2257)
    at com.orientechnologies.orient.core.db.document.ODatabaseDocumentAbstract.internalCommit(ODatabaseDocumentAbstract.java:2466)
    at com.orientechnologies.orient.core.tx.OTransactionOptimistic.doCommit(OTransactionOptimistic.java:602)
    at com.orientechnologies.orient.core.tx.OTransactionOptimistic.commit(OTransactionOptimistic.java:106)
    at com.orientechnologies.orient.core.db.document.ODatabaseDocumentAbstract.commit(ODatabaseDocumentAbstract.java:1984)
    at com.orientechnologies.orient.core.db.document.ODatabaseDocumentAbstract.commit(ODatabaseDocumentAbstract.java:1954)
```

**Comment by grimace** [comment]
I'm seeing this as well.  Any thoughts?

**Comment by andrii0lomakin** [comment]
Hi, that is already fixed in the latest version.

**Comment by grimace** [comment]
yeah, I just downloaded and installed 3.14 and it is definitely fixed.
