### ISSUE TITLE
OFunction scripting stopped working

### ISSUE THREAD

**Issue by PhantomYdn** [orientechnologies/orientdb#9432]
### OS: Ubuntu  

Create OFunction with the following code:

```java
java.lang.System.out.println("Test")
```

## Expected behavior  
Execution of this function should be successful with corresponding message in logs or console.

## Actual behavior  
Exception happened:
```
java.lang.ClassNotFoundException: java.lang.System.out.println

Root cause:

java.lang.ClassNotFoundException: java.lang.System.out.println
     at jdk.nashorn.internal.runtime.NativeJavaPackage.classNotFound(NativeJavaPackage.java:162)
     at jdk.nashorn.internal.scripts.Script$Recompilation$75$25$\^eval\_.handleContent(<eval>:2)
     at jdk.nashorn.internal.runtime.ScriptFunctionData.invoke(ScriptFunctionData.java:637)
     at jdk.nashorn.internal.runtime.ScriptFunction.invoke(ScriptFunction.java:494)
     at jdk.nashorn.internal.runtime.ScriptRuntime.apply(ScriptRuntime.java:393)
     at jdk.nashorn.api.scripting.ScriptObjectMirror.callMember(ScriptObjectMirror.java:199)
     at jdk.nashorn.api.scripting.NashornScriptEngine.invokeImpl(NashornScriptEngine.java:386)
     at jdk.nashorn.api.scripting.NashornScriptEngine.invokeFunction(NashornScriptEngine.java:190)
     at com.orientechnologies.orient.core.command.script.OCommandExecutorFunction.executeInContext(OCommandExecutorFunction.java:99)
     at com.orientechnologies.orient.core.metadata.function.OFunction.executeInContext(OFunction.java:161)
     at com.orientechnologies.orient.core.metadata.function.OFunction.execute(OFunction.java:131)
```

## Notes
It worked perfectly in OrientDb 2.x

**Comment by PhantomYdn** [comment]
"Issue was introduced' by the following commit: https://github.com/orientechnologies/orientdb/commit/40544dc82105884de0c78a893a84439871029e23

Is there any documentation on how to use these security scripts?

**Comment by PhantomYdn** [comment]
Btw, there are few comments to this implementation:
1) Assumed that user can define list of allowed packages in OScriptManager, but according to code: it's not packages, but classNames - which makes configuration much more granular and inconvinient. Will be good to have either on package level or use wildcards.
2) There is no way to disable this behavior. It would be nice to allow users to decide: use or not.
3) ClassFilter is good, but whats about using more secured `SecurityManager`?

**Comment by PhantomYdn** [comment]
Btw, seems that disregard how deeply ClassFilter was configured: it's not possible to work with java object. Error message:

```
TypeError: Java reflection not supported when class filter is present
```

So, the main question for us: how to disable this feature?:)

**Comment by lvca** [comment]
You should provide the allowed packages via `scriptManager.addAllowedPackages("java.lang.System")` first.

**Comment by PhantomYdn** [comment]
@lvca , point was different.
1. Currently only classes can by entered, but not packages - but name of the function assume using if packages.
2. Using secured narshorn even with configured classes doesn't allow reflection. So it will be good to have option to disable it.

**Comment by lvca** [comment]
Can you use GraalVM then? It's more flexible, fast and it's the future.

**Comment by PhantomYdn** [comment]
Potentially - yes. But there are separate disadvantages from GraalVM... Graal is not so graal:) 
Need to check that in GraalVM in case of secured filter reflection will be still available...

In any case, we have already use workaround: https://github.com/OrienteerBAP/Orienteer/commit/c38288baf9d96cd519e619b6badd97ee18303145#diff-79f894404bbbfa6934881a98d90e833ea3e4c30bdf741380c327037a9d0b7948
