### ISSUE TITLE
nov. 16, 2020 6:43:54 DA TARDE com.orientechnologies.common.log.OLogManager log INFO: Detected limit of amount of simultaneously open files is 1048576,  limit of open files for disk cache will be set to 523776 Exception in thread "main" com.orientechnologies.orient.core.exception.ODatabaseException: Cannot open database 'demodb'

### ISSUE THREAD

**Issue by darangel1273** [orientechnologies/orientdb#9441]
## Expected behavior  
<add here>  

## Actual behavior  
Hello,
(I am new at this)
I have this error, on Eclipse, with openjdk:

```
nov. 16, 2020 6:08:24 DA TARDE com.orientechnologies.common.log.OLogManager log
INFO: Detected limit of amount of simultaneously open files is 1048576,  limit of open files for disk cache will be set to 523776
Exception in thread "main" com.orientechnologies.orient.core.exception.ODatabaseException: Cannot open database 'rui'
	at com.orientechnologies.orient.core.db.OrientDBRemote.open(OrientDBRemote.java:113)
	at com.orientechnologies.orient.core.db.OrientDB.open(OrientDB.java:224)
	at com.orientechnologies.orient.core.db.OrientDB.open(OrientDB.java:210)
	at root.rui.LigaOrientDB.main(LigaOrientDB.java:13)
Caused by: com.orientechnologies.orient.core.exception.OStorageException: Cannot create a connection to remote server address(es): [ruin:2480]
	DB name="rui"
	at com.orientechnologies.orient.client.remote.OStorageRemote.openRemoteDatabase(OStorageRemote.java:1906)
	at com.orientechnologies.orient.client.remote.OStorageRemote.openRemoteDatabase(OStorageRemote.java:1750)
	at com.orientechnologies.orient.client.remote.OStorageRemote.open(OStorageRemote.java:570)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentRemote.internalOpen(ODatabaseDocumentRemote.java:235)
	at com.orientechnologies.orient.core.db.OrientDBRemote.open(OrientDBRemote.java:110)
	... 3 more

```

With a simple class to learn OrinetDB:

`package root.rui;

import com.orientechnologies.orient.core.db.ODatabaseSession;
import com.orientechnologies.orient.core.db.OrientDB;
import com.orientechnologies.orient.core.db.OrientDBConfig;

public class LigaOrientDB {

	public static void main(String[] args) {
		// TODO Auto-generated method stub
		//OrientDB o =new OrientDB("remote:192.168.1.64:2480", OrientDBConfig.defaultConfig() );
		//OrientDB o =new OrientDB("remote:localhost:2480", OrientDBConfig.defaultConfig() );
		OrientDB o =new OrientDB("remote:ruin:2480", OrientDBConfig.defaultConfig() );
		ODatabaseSession s = o.open("rui", "admin","admin" );
		if (s.getClass("Pessoa") == null )   { s.createVertexClass("Pessoa" ) ; }
		if (s.getClass("AmigoDe" ) == null ) { s.createEdgeClass("AmigoDe") ; }
		s.close();
		o.close();
	}
}
`
Can anyone tell me, what I am doing wrong?
Thank's in advance.

## Steps to reproduce  

nov. 16, 2020 6:43:54 DA TARDE com.orientechnologies.common.log.OLogManager log
**INFO: Detected limit of amount of simultaneously open files is 1048576,  limit of open files for disk cache will be set to 523776**
Exception in thread "main" com.orientechnologies.orient.core.exception.ODatabaseException: Cannot open database 'demodb'

**Comment by lvca** [comment]
It looks like your database has thousands of classes/clusters created. Could you please check under the directory "databases" how many files you have there?
