### ISSUE TITLE
OrientDB REST API works with encoding incorrectly

### ISSUE THREAD

**Issue by PhantomYdn** [orientechnologies/orientdb#9456]
### OS: Any

There are 2 HTTP headers which related to encoding: `Accept-Encoding: ` and `Content-Encoding: `.  There is use case: Client is OK to receive GZIPped answer from the server, but request is plain. In this case   `Content-Encoding: ` will be absent, but `Accept-Encoding: ` will have `gzip`.  But OrientDB, for some reason instead of `Content-Encoding: ` use `Accept-Encoding: ` for identifying: is content encoded or not. As a result: the mentioned case is failing with the following exception:

```
java.util.zip.ZipException: Not in GZIP format
	at java.util.zip.GZIPInputStream.readHeader(Unknown Source)
	at java.util.zip.GZIPInputStream.<init>(Unknown Source)
	at com.orientechnologies.orient.server.network.protocol.http.ONetworkProtocolHttpAbstract.deCompress(ONetworkProtocolHttpAbstract.java:890)
	at com.orientechnologies.orient.server.network.protocol.http.ONetworkProtocolHttpAbstract.readAllContent(ONetworkProtocolHttpAbstract.java:710)
	at com.orientechnologies.orient.server.network.protocol.http.ONetworkProtocolHttpAbstract.execute(ONetworkProtocolHttpAbstract.java:796)
	at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:67)
```

## Expected behavior  
All combination of encoding should be supported

## Actual behavior  
Case when `request is NOT encoded, but response is encoded` is not supported

**Comment by PhantomYdn** [comment]
Please consider to merge PR #9457

**Comment by lvca** [comment]
@PhantomYdn Thanks for the PR, looks good to me.
