### ISSUE TITLE
File with name config.nd does not exist in storage

### ISSUE THREAD

**Issue by adriancoca** [orientechnologies/orientdb#9459]
## Expected behavior  
When trying to login in Orient studio in console i have the next message.
It seems that after a server restart something happend only to a database.

2020-11-25 00:01:19:840 INFO  Free space map is absent inside of config cluster of storage dev . Information about free space present inside of each page will be recovered. [OPaginatedClusterV2]
2020-11-25 00:01:19:841 INFO  Scanning of free space for cluster config in storage dev started ... [OPaginatedClusterV2]
2020-11-25 00:01:19:841 INFO  Page scan for cluster config is completed. [OPaginatedClusterV2]Exception `752EA98C` in storage `plocal:C:\orientdb-3.1.5\databases/dev`: 3.1.5 - Veloce (build 846eeb77dcb175a9fbd7ed534e039424322f44a7, branch 3.1.x)
com.orientechnologies.orient.core.exception.OStorageException: Exception during execution of atomic operation inside of storage dev
        at com.orientechnologies.orient.core.storage.impl.local.paginated.atomicoperations.OAtomicOperationsManager.executeInsideAtomicOperation(OAtomicOperationsManager.java:195)
...................
**Caused by: com.orientechnologies.orient.core.exception.OStorageException: File with name config.nd does not exist in storage dev**
        at com.orientechnologies.orient.core.storage.cache.local.OWOWCache.loadFile(OWOWCache.java:760)
      ..............com.orientechnologies.orient.core.storage.impl.local.paginated.atomicoperations.OAtomicOperationsManager.executeInsideAtomicOperation(OAtomicOperationsManager.java:189)
        ... 11 more

**Comment by andrii0lomakin** [comment]
Hi @adriancoca , could you provide the full stack trace?

**Comment by andrii0lomakin** [comment]
@adriancoca I have run several tests and can not reproduce your issue if you could share your database with me to reproduce it. That would be good.

**Comment by adriancoca** [comment]
@laa Can you give me an email to send you an archive with the broken database?

This is the full message from console.

com.orientechnologies.orient.core.exception.OStorageException: Exception during execution of atomic operation inside of storage dev
	at com.orientechnologies.orient.core.storage.impl.local.paginated.atomicoperations.OAtomicOperationsManager.executeInsideAtomicOperation(OAtomicOperationsManager.java:195)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.open(OAbstractPaginatedStorage.java:438)
	at com.orientechnologies.orient.core.db.OrientDBEmbedded.openNoAuthenticate(OrientDBEmbedded.java:429)
	at com.orientechnologies.orient.core.db.OrientDBEmbedded.openNoAuthenticate(OrientDBEmbedded.java:78)
	at com.orientechnologies.orient.server.OServer.openDatabase(OServer.java:992)
	at com.orientechnologies.orient.server.OServer.openDatabase(OServer.java:958)
	at com.orientechnologies.orient.server.network.protocol.http.command.OServerCommandAuthenticatedDbAbstract.authenticate(OServerCommandAuthenticatedDbAbstract.java:193)
	at com.orientechnologies.orient.server.network.protocol.http.command.OServerCommandAuthenticatedDbAbstract.beforeExecute(OServerCommandAuthenticatedDbAbstract.java:135)
	at com.orientechnologies.orient.server.network.protocol.http.command.get.OServerCommandGetConnect.beforeExecute(OServerCommandGetConnect.java:55)
	at com.orientechnologies.orient.server.network.protocol.http.ONetworkProtocolHttpAbstract.service(ONetworkProtocolHttpAbstract.java:250)
	at com.orientechnologies.orient.server.network.protocol.http.ONetworkProtocolHttpAbstract.execute(ONetworkProtocolHttpAbstract.java:813)
	at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:67)
Caused by: com.orientechnologies.orient.core.exception.OStorageException: File with name config.nd does not exist in storage dev
	at com.orientechnologies.orient.core.storage.cache.local.OWOWCache.loadFile(OWOWCache.java:760)
	at com.orientechnologies.orient.core.storage.impl.local.paginated.atomicoperations.OAtomicOperationBinaryTracking.loadFile(OAtomicOperationBinaryTracking.java:372)
	at com.orientechnologies.orient.core.storage.impl.local.paginated.base.ODurableComponent.openFile(ODurableComponent.java:193)
	at com.orientechnologies.orient.core.storage.index.sbtree.singlevalue.v1.CellBTreeSingleValueV1.load(CellBTreeSingleValueV1.java:473)
	at com.orientechnologies.orient.core.storage.config.OClusterBasedStorageConfiguration.load(OClusterBasedStorageConfiguration.java:248)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.lambda$open$1(OAbstractPaginatedStorage.java:443)
	at com.orientechnologies.orient.core.storage.impl.local.paginated.atomicoperations.OAtomicOperationsManager.executeInsideAtomicOperation(OAtomicOperationsManager.java:189)
	... 11 more

**Comment by andrii0lomakin** [comment]
@adriancoca I would need an original version of the broken database. Do you have one? So I will reproduce the whole cycle myself. ?  a.lomakin@sap.com

**Comment by andrii0lomakin** [comment]
Hi @adriancoca . I am working right now with issues from commercial support. Once I am done with them, I will check yours.

**Comment by adriancoca** [comment]
Hello again, any news regarding that problem?
