### ISSUE TITLE
"Vertex id can not be null"

### ISSUE THREAD

**Issue by johny65** [orientechnologies/orientdb#9460]
## Expected behavior  

Call to `OrientVertex::getEdges` without exception.

## Actual behavior  

Sometimes calling to `getEdges` on a vertex throws an `java.lang.IllegalArgumentException: Vertex id can not be null`. If I retry the operation, the call is successful. I don't know in which conditions this happens, it's somewhat random.

The full stacktrace is the following:

```
java.lang.IllegalArgumentException: Vertex id can not be null
        at com.tinkerpop.blueprints.util.ExceptionFactory.vertexIdCanNotBeNull(ExceptionFactory.java:14)
        at com.tinkerpop.blueprints.impls.orient.OrientBaseGraph.getVertex(OrientBaseGraph.java:680)
        at com.tinkerpop.blueprints.impls.orient.OrientEdge.getVertex(OrientEdge.java:163)
        at com.tinkerpop.blueprints.impls.orient.OrientEdgeIterator.filter(OrientEdgeIterator.java:127)
        at com.tinkerpop.blueprints.impls.orient.OrientEdgeIterator.filter(OrientEdgeIterator.java:41)
        at com.orientechnologies.orient.core.iterator.OLazyWrapperIterator.hasNext(OLazyWrapperIterator.java:94)
        at com.orientechnologies.common.collection.OMultiCollectionIterator.getNextPartial(OMultiCollectionIterator.java:259)
        at com.orientechnologies.common.collection.OMultiCollectionIterator.hasNextInternal(OMultiCollectionIterator.java:88)
        at com.orientechnologies.common.collection.OMultiCollectionIterator.hasNext(OMultiCollectionIterator.java:78)
```

## Steps to reproduce  

I just have a for loop:

```
for (Edge edge : vertex.getEdges(otherVertex, direction, relation)) {
    ...
}
```
<add here>  
<An SQL script to reproduce the problem or a JUnit test case will increase **A LOT** the chance to have a quick fix>

**Comment by lvca** [comment]
This is the case when otherVertex is null. How do you get otherVertex? Could you please check that it's not null?

**Comment by johny65** [comment]
`otherVertex` is not null. I found that the problem occurs when the vertices in the database are inconsistent... the edge goes out from vertex but doesn't go in into otherVertex. I don't know why the database got inconsistent :/..
