### ISSUE TITLE
Console optimize is failing

### ISSUE THREAD

**Issue by PhantomYdn** [orientechnologies/orientdb#9472]
### OS: any

Invoking of OrientDB console command `optimize database` leads to the following exception:

```java
java.util.IllegalFormatConversionException: f != java.util.ArrayList
at java.util.Formatter$FormatSpecifier.failConversion(Formatter.java:4302)
at java.util.Formatter$FormatSpecifier.printFloat(Formatter.java:2806)
at java.util.Formatter$FormatSpecifier.print(Formatter.java:2753)
at java.util.Formatter.format(Formatter.java:2520)
at java.io.PrintStream.format(PrintStream.java:970)
at java.io.PrintStream.printf(PrintStream.java:871)
at com.orientechnologies.common.console.OConsoleApplication.message(OConsoleApplication.java:164)
at com.orientechnologies.orient.console.OConsoleDatabaseApp.sqlCommand(OConsoleDatabaseApp.java:3467)
at com.orientechnologies.orient.console.OConsoleDatabaseApp.optimizeDatabase(OConsoleDatabaseApp.java:849)
```

**Comment by lvca** [comment]
Fixed in develop branch
