### ISSUE TITLE
OrientDB 3.0.34 deadlocked

### ISSUE THREAD

**Issue by madmac2501** [orientechnologies/orientdb#9521]
## Expected behavior  
OrientDB doesn't deadlock

## Actual behavior  
After some weeks running Orientdb has deadlocked

## Steps to reproduce  
Thread dump attached

[orient-server-boot.log](https://github.com/orientechnologies/orientdb/files/5866117/orient-server-boot.log)

**Comment by madmac2501** [comment]
Taking  a look at the logs I saw this. Just after restarting OrientDB this exception appears and OrientDB in unresponsive. Even if 3.0.34 is not as maintained as 3.1.x please review this just in case it also happens in 3.1.x. I have the feeling that an unhandled exception doesn't free a lock and provokes the deadlock.

com.orientechnologies.orient.core.exception.OStorageException: Exception during execution of atomic operation inside of storage database_name
	at com.orientechnologies.orient.core.storage.impl.local.paginated.atomicoperations.OAtomicOperationsManager.executeInsideAtomicOperation(OAtomicOperationsManager.java:157)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage$2.run(OAbstractPaginatedStorage.java:4884)
	at com.orientechnologies.orient.core.Orient$3.run(Orient.java:419)
	at java.util.TimerThread.mainLoop(Timer.java:555)
	at java.util.TimerThread.run(Timer.java:505)
Caused by: java.lang.NullPointerException
	at com.orientechnologies.orient.core.storage.ridbag.sbtree.OSBTreeCollectionManagerShared.tryDelete(OSBTreeCollectionManagerShared.java:198)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage$2.lambda$run$0(OAbstractPaginatedStorage.java:4885)
	at com.orientechnologies.orient.core.storage.impl.local.paginated.atomicoperations.OAtomicOperationsManager.executeInsideAtomicOperation(OAtomicOperationsManager.java:153)
	... 4 more
Error during deletion of rid bag
com.orientechnologies.orient.core.exception.OStorageException: Exception during execution of atomic operation inside of storage database_name
	at com.orientechnologies.orient.core.storage.impl.local.paginated.atomicoperations.OAtomicOperationsManager.executeInsideAtomicOperation(OAtomicOperationsManager.java:157)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage$2.run(OAbstractPaginatedStorage.java:4884)
	at com.orientechnologies.orient.core.Orient$3.run(Orient.java:419)
	at java.util.TimerThread.mainLoop(Timer.java:555)
	at java.util.TimerThread.run(Timer.java:505)
Caused by: java.lang.NullPointerException
	at com.orientechnologies.orient.core.storage.ridbag.sbtree.OSBTreeCollectionManagerShared.tryDelete(OSBTreeCollectionManagerShared.java:198)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage$2.lambda$run$0(OAbstractPaginatedStorage.java:4885)
	at com.orientechnologies.orient.core.storage.impl.local.paginated.atomicoperations.OAtomicOperationsManager.executeInsideAtomicOperation(OAtomicOperationsManager.java:153)
	... 4 more

**Comment by madmac2501** [comment]
Duplicated of https://github.com/orientechnologies/orientdb/issues/9400
