### ISSUE TITLE
Can't import database: Component collections_52 can not be removed because it still contains 1 ridbags

### ISSUE THREAD

**Issue by arch7tect** [orientechnologies/orientdb#9531]
## Expected behavior  
1. export db with  ODatabaseExport
2. import db  with ODatabaseImport (merge=false)
3. expected success

## Actual behavior  
Exception:
Caused by: com.orientechnologies.orient.core.exception.NotEmptyComponentCanNotBeRemovedException: Component collections_52 can not be removed because it still contains 1 ridbags
	at com.orientechnologies.orient.core.storage.index.sbtreebonsai.local.OSBTreeBonsaiLocal.lambda$deleteComponent$6(OSBTreeBonsaiLocal.java:550)
	at com.orientechnologies.orient.core.storage.impl.local.paginated.atomicoperations.OAtomicOperationsManager.executeInsideComponentOperation(OAtomicOperationsManager.java:195)
	at com.orientechnologies.orient.core.storage.impl.local.paginated.atomicoperations.OAtomicOperationsManager.executeInsideComponentOperation(OAtomicOperationsManager.java:187)
	at com.orientechnologies.orient.core.storage.impl.local.paginated.base.ODurableComponent.executeInsideComponentOperation(ODurableComponent.java:102)
	at com.orientechnologies.orient.core.storage.index.sbtreebonsai.local.OSBTreeBonsaiLocal.deleteComponent(OSBTreeBonsaiLocal.java:528)
	at com.orientechnologies.orient.core.storage.ridbag.sbtree.OSBTreeCollectionManagerShared.deleteComponentByClusterId(OSBTreeCollectionManagerShared.java:177)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.lambda$dropCluster$5(OAbstractPaginatedStorage.java:1034)
	at com.orientechnologies.orient.core.storage.impl.local.paginated.atomicoperations.OAtomicOperationsManager.calculateInsideAtomicOperation(OAtomicOperationsManager.java:152)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.dropCluster(OAbstractPaginatedStorage.java:1025)
	at com.orientechnologies.orient.core.metadata.schema.OSchemaEmbedded.deleteCluster(OSchemaEmbedded.java:756)
	at com.orientechnologies.orient.core.metadata.schema.OSchemaEmbedded.dropClassInternal(OSchemaEmbedded.java:616)
	at com.orientechnologies.orient.core.metadata.schema.OSchemaEmbedded.doDropClass(OSchemaEmbedded.java:582)
	at com.orientechnologies.orient.core.metadata.schema.OSchemaEmbedded.dropClass(OSchemaEmbedded.java:571)
	at com.orientechnologies.orient.core.metadata.schema.OSchemaProxy.dropClass(OSchemaProxy.java:125)
	at com.orientechnologies.orient.core.db.tool.ODatabaseImport.removeDefaultNonSecurityClasses(ODatabaseImport.java:503)
	at com.orientechnologies.orient.core.db.tool.ODatabaseImport.importDatabase(ODatabaseImport.java:195)
	... 3 more
  

## Steps to reproduce  

git clone https://github.com/arch7tect/testimport.git
cd testimport
mvn package exec:java

**Comment by florian-stoica** [comment]
Any news here? It happened to me too on OrientDB V 3.1.15 with JDK 16
