### ISSUE TITLE
Cannot open DB Error: java.lang.NumberFormatException: For input string: "2147483648"

### ISSUE THREAD

**Issue by EdwinLuther** [orientechnologies/orientdb#9541]
## Expected behavior  
Should be able to login to database

## Actual behavior  
Unable to login to database in web and in console
Getting the below error
Error: com.orientechnologies.orient.core.exception.OStorageException: Exception during execution of atomic operation inside of storage DBNAME

Cannot open DB Error: java.lang.NumberFormatException: For input string: "2147483648" 

## Steps to reproduce  
It was working fine and all of a sudden stopped working. 
I have tried different configurations, restarted service, restarted machine, tried with console.sh
Nothing is working
<An SQL script to reproduce the problem or a JUnit test case will increase **A LOT** the chance to have a quick fix>

**Comment by EdwinLuther** [comment]
Below is the complete exception
2021-02-12 05:22:49:949 INFO  DWL:DBNAME: block size = 4096 bytes, maximum segment size = 4095 MB [DoubleWriteLogGL]Exception `12D2B984` in storage `plocal:/datadisk/orientdb/databases/DBNAME`: 3.1.6 - Veloce (build 0352408a42c45ef8823aa721fc84c8b4ed077ac7, branch 3.1.x)
com.orientechnologies.orient.core.exception.OStorageException: Exception during execution of atomic operation inside of storage DBNAME
	at com.orientechnologies.orient.core.storage.impl.local.paginated.atomicoperations.OAtomicOperationsManager.executeInsideAtomicOperation(OAtomicOperationsManager.java:176)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.open(OAbstractPaginatedStorage.java:406)
	at com.orientechnologies.orient.core.db.OrientDBEmbedded.getAndOpenStorage(OrientDBEmbedded.java:500)
	at com.orientechnologies.orient.core.db.OrientDBEmbedded.openNoAuthenticate(OrientDBEmbedded.java:429)
	at com.orientechnologies.orient.core.db.OrientDBEmbedded.openNoAuthenticate(OrientDBEmbedded.java:79)
	at com.orientechnologies.orient.server.OServer.openDatabase(OServer.java:976)
	at com.orientechnologies.orient.server.OServer.openDatabase(OServer.java:947)
	at com.orientechnologies.orient.server.OConnectionBinaryExecutor.executeDatabaseOpen37(OConnectionBinaryExecutor.java:1369)
	at com.orientechnologies.orient.client.remote.message.OOpen37Request.execute(OOpen37Request.java:75)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.sessionRequest(ONetworkProtocolBinary.java:355)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.execute(ONetworkProtocolBinary.java:239)
	at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:67)
Caused by: java.lang.NumberFormatException: For input string: "2147483648"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Integer.parseInt(Integer.java:587)
	at java.lang.Integer.parseInt(Integer.java:615)
	at com.orientechnologies.orient.core.metadata.schema.OType.convert(OType.java:375)
	at com.orientechnologies.orient.core.storage.config.OClusterBasedStorageConfiguration.readConfiguration(OClusterBasedStorageConfiguration.java:943)
	at com.orientechnologies.orient.core.storage.config.OClusterBasedStorageConfiguration.load(OClusterBasedStorageConfiguration.java:253)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.lambda$open$1(OAbstractPaginatedStorage.java:412)
	at com.orientechnologies.orient.core.storage.impl.local.paginated.atomicoperations.OAtomicOperationsManager.executeInsideAtomicOperation(OAtomicOperationsManager.java:170)
	... 11 more
