### ISSUE TITLE
3.1.8 throws "Id of WAL operation can not be duplicated"

### ISSUE THREAD

**Issue by scrabb** [orientechnologies/orientdb#9547]
## Actual behavior  
Opening any db causes
```
java.lang.IllegalStateException: Id of WAL operation can not be duplicated
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.fetchNextOperationId(OAbstractPaginatedStorage.java:6502)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.restoreFromBeginning(OAbstractPaginatedStorage.java:6221)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.restoreFromWAL(OAbstractPaginatedStorage.java:6161)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.recoverIfNeeded(OAbstractPaginatedStorage.java:5320)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.open(OAbstractPaginatedStorage.java:401)
	at com.orientechnologies.orient.core.db.OrientDBEmbedded.getAndOpenStorage(OrientDBEmbedded.java:500)
	at com.orientechnologies.orient.core.db.OrientDBEmbedded.openNoAuthorization(OrientDBEmbedded.java:455)
	at com.orientechnologies.orient.core.db.OrientDBEmbedded.openNoAuthorization(OrientDBEmbedded.java:79)
	at com.orientechnologies.orient.server.OSystemDatabase.openSystemDatabase(OSystemDatabase.java:93)
	at com.orientechnologies.orient.server.OSystemDatabase.checkServerId(OSystemDatabase.java:169)
	at com.orientechnologies.orient.server.OSystemDatabase.init(OSystemDatabase.java:157)
	at com.orientechnologies.orient.server.OSystemDatabase.<init>(OSystemDatabase.java:50)
	at com.orientechnologies.orient.server.OServer.initSystemDatabase(OServer.java:1275)
	at com.orientechnologies.orient.server.OServer.activate(OServer.java:445)
	at com.orientechnologies.orient.server.OServerMain$1.run(OServerMain.java:49)
```

**Comment by lvca** [comment]
@scrabb 3.1.x release is pretty old. Have you considered upgrading to the latest version?

**Comment by lvca** [comment]
@laa any update on this?

**Comment by andrii0lomakin** [comment]
Hi guys, according to stack trace you try to recover crashed database. We do not support recovering crashed databases between versions. Please recover using the same version and then migrate to the new version.

**Comment by sunilrebel** [comment]
@laa - I'm also facing the same issue. Can you please guide - **how to migrate database to a new version with a recommended way**?
My current OrientDB version is 3.0.27 which needs to be upgraded to 3.1.9

Copying the `<database folder>` from the `databases` folder of 3.0.27 to 3.1.9 `databases` folder, throws this exception.

**Comment by ghost** [comment]
@laa, I am getting this issue.  I was running on 3.1.7 with everything stable.  After I moved to 3.1.9, I got the exact same issue.

**Comment by johny65** [comment]
> We do not support recovering crashed databases between versions.

Not even between same minor versions (between 3.1.x)? That makes no sense in a production environment. See #9598.

**Comment by jamieb22** [comment]
FYI: This duplicate WAL Id issue is still present in 3.2.2. To reproduce the issue, sample database can be downloaded from #9542.
