### ISSUE TITLE
NPE in eval(...)

### ISSUE THREAD

**Issue by PhantomYdn** [orientechnologies/orientdb#9579]
### OS: Win

There is NPE in eval function. Just try something like:

```sql
select eval()
select eval($currentUser)
```

## Expected behavior  
If statement is not correct: there should be other type of error

## Actual behavior  
NullPointerException
```
java.lang.NullPointerException
     at com.orientechnologies.orient.core.sql.functions.math.OSQLFunctionEval.execute(OSQLFunctionEval.java:49)
     at com.orientechnologies.orient.core.sql.parser.OFunctionCall.execute(OFunctionCall.java:128)
     at com.orientechnologies.orient.core.sql.parser.OFunctionCall.execute(OFunctionCall.java:82)
     at com.orientechnologies.orient.core.sql.parser.OLevelZeroIdentifier.execute(OLevelZeroIdentifier.java:52)
     at com.orientechnologies.orient.core.sql.parser.OBaseIdentifier.execute(OBaseIdentifier.java:62)
     at com.orientechnologies.orient.core.sql.parser.OBaseExpression.execute(OBaseExpression.java:111)
     at com.orientechnologies.orient.core.sql.parser.OExpression.execute(OExpression.java:102)
     at com.orientechnologies.orient.core.sql.parser.OProjectionItem.execute(OProjectionItem.java:149)
     at com.orientechnologies.orient.core.sql.parser.OProjection.calculateSingle(OProjection.java:110)
     at com.orientechnologies.orient.core.sql.executor.ProjectionCalculationStep.calculateProjections(ProjectionCalculationStep.java:64)
     at com.orientechnologies.orient.core.sql.executor.ProjectionCalculationStep.access$000(ProjectionCalculationStep.java:10)
     at com.orientechnologies.orient.core.sql.executor.ProjectionCalculationStep$1.next(ProjectionCalculationStep.java:39)
     at com.orientechnologies.orient.core.sql.parser.OLocalResultSet.next(OLocalResultSet.java:70)
```

```
java.lang.ArrayIndexOutOfBoundsException: 0
     at com.orientechnologies.orient.core.sql.functions.math.OSQLFunctionEval.execute(OSQLFunctionEval.java:49)
     at com.orientechnologies.orient.core.sql.parser.OFunctionCall.execute(OFunctionCall.java:128)
     at com.orientechnologies.orient.core.sql.parser.OFunctionCall.execute(OFunctionCall.java:82)
     at com.orientechnologies.orient.core.sql.parser.OLevelZeroIdentifier.execute(OLevelZeroIdentifier.java:52)
     at com.orientechnologies.orient.core.sql.parser.OBaseIdentifier.execute(OBaseIdentifier.java:62)
     at com.orientechnologies.orient.core.sql.parser.OBaseExpression.execute(OBaseExpression.java:111)
     at com.orientechnologies.orient.core.sql.parser.OExpression.execute(OExpression.java:102)
     at com.orientechnologies.orient.core.sql.parser.OProjectionItem.execute(OProjectionItem.java:149)
     at com.orientechnologies.orient.core.sql.parser.OProjection.calculateSingle(OProjection.java:110)
     at com.orientechnologies.orient.core.sql.executor.ProjectionCalculationStep.calculateProjections(ProjectionCalculationStep.java:64)
     at com.orientechnologies.orient.core.sql.executor.ProjectionCalculationStep.access$000(ProjectionCalculationStep.java:10)
     at com.orientechnologies.orient.core.sql.executor.ProjectionCalculationStep$1.next(ProjectionCalculationStep.java:39)
     at com.orientechnologies.orient.core.sql.parser.OLocalResultSet.next(OLocalResultSet.java:70)
```

**Comment by luigidellaquila** [comment]
Hi @PhantomYdn 

I fixed both these problems. You will still get an error in the first case, because eval() function is supposed to have exactly one parameter,  but a much more clear one (command execution exception with a meaningful error message)

The fix will be released with v 3.1.12

Thanks

Luigi
