### ISSUE TITLE
OSerializationException in server when executing query that works fine in studio

### ISSUE THREAD

**Issue by sanderPostma** [orientechnologies/orientdb#9585]
## Expected behavior  
For db.query() to return a OResultSet reflecting what I see in studio

## Actual behavior 
_On server side_ 
`com.orientechnologies.orient.core.exception.OSerializationException: Impossible serialize value of type class com.orientechnologies.orient.core.record.impl.OEdgeToVertexIterable with the Result binary serializer
        DB name="SphereonGraph"
        at com.orientechnologies.orient.core.serialization.serializer.result.binary.OResultSerializerNetwork.serialize(OResultSerializerNetwork.java:163)
        at com.orientechnologies.orient.core.serialization.serializer.result.binary.OResultSerializerNetwork.toStream(OResultSerializerNetwork.java:667)
        at com.orientechnologies.orient.client.remote.message.OMessageHelper.writeProjection(OMessageHelper.java:425)
        at com.orientechnologies.orient.client.remote.message.OMessageHelper.writeResult(OMessageHelper.java:473)
        at com.orientechnologies.orient.client.remote.message.OQueryResponse.write(OQueryResponse.java:68)
        at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.sessionRequest(ONetworkProtocolBinary.java:391)
        at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.execute(ONetworkProtocolBinary.java:239)
        at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:67)`

_On the client side_
`Caused by: java.io.EOFException`

## Steps to reproduce  
- Open Orient studio
- Run a query similar as listed below
- Open a database and ODatabaseSession using remote:<host>
- Run a query similar as listed below -> boom
`

select collection.funckey, document from Case  
         let collection = in('CollectionToCase'),  
         lastSnapshot = last(out($parent.CaseToSnapshot)),   
         document = lastSnapshot.out('SnapshotToDocument')`

**Comment by sanderPostma** [comment]
.outE() throws a different exception
> java.lang.ClassCastException: class com.orientechnologies.common.collection.OMultiCollectionIterator cannot be cast to class java.util.Collection

The problem goes away when doing out().asSet() or out().asList so this is just a case of a bad exception message. Maybe OResultSerializerNetwork can automatically apply "asList()" because it just doesn't support serializing iterators, but at least it can give a more meaningful message that it doesn't support the result set in this form and hint at using .asList() or .asSet()
The client side EOFException is even worse, really useless.

I can donate some time to do some fixes regarding this if you let me know what you'd want.
