### ISSUE TITLE
java.lang.NullPointerException ORunQueryExecutionPlanTask.getResult(ORunQueryExecutionPlanTask.java:94)

### ISSUE THREAD

**Issue by lee2015new** [orientechnologies/orientdb#9593]
## Expected behavior  
we have 2 clusters and set to sharding  model, 1 server per cluster. After insert 5 records of class <User>, cluster A have 3 records and cluster B has 2 records. when we select all data by SQL like this:select * from User, we want to get 5 records 

## Actual behavior  
When we select data we got exception below:
OrientDB Server is active v3.1.11 - Veloce (build 5556db1fc563d899c6f841908d38ff021b09975e, branch 3.1.x). [OServer]Internal server error:

java.lang.NullPointerException
        at com.orientechnologies.orient.server.distributed.impl.task.ORunQueryExecutionPlanTask.getResult(ORunQueryExecutionPlanTask.java:110)
        at com.orientechnologies.orient.server.distributed.impl.ODatabaseDocumentDistributed.queryOnNode(ODatabaseDocumentDistributed.java:304)
        at com.orientechnologies.orient.core.sql.executor.DistributedExecutionStep.sendSerializedExecutionPlan(DistributedExecutionStep.java:71)
        at com.orientechnologies.orient.core.sql.executor.DistributedExecutionStep.init(DistributedExecutionStep.java:64)
        at com.orientechnologies.orient.core.sql.executor.DistributedExecutionStep.syncPull(DistributedExecutionStep.java:31)
        at com.orientechnologies.orient.core.sql.executor.OSelectExecutionPlan.fetchNext(OSelectExecutionPlan.java:34)
        at com.orientechnologies.orient.core.sql.executor.ParallelExecStep.fetchNext(ParallelExecStep.java:81)
        at com.orientechnologies.orient.core.sql.executor.ParallelExecStep$1.hasNext(ParallelExecStep.java:37)
        at com.orientechnologies.orient.core.sql.executor.ProjectionCalculationStep$1.hasNext(ProjectionCalculationStep.java:31)
        at com.orientechnologies.orient.core.sql.parser.OLocalResultSet.hasNext(OLocalResultSet.java:53)
        at com.orientechnologies.orient.core.sql.parser.OLocalResultSetLifecycleDecorator.hasNext(OLocalResultSetLifecycleDecorator.java:41)
        at com.orientechnologies.orient.server.network.protocol.http.command.post.OServerCommandPostCommand.execute(OServerCommandPostCommand.java:125)
        at com.orientechnologies.orient.server.network.protocol.http.command.post.OServerCommandPostCommandGraph.execute(OServerCommandPostCommandGraph.java:34)
        at com.orientechnologies.orient.server.network.protocol.http.ONetworkProtocolHttpAbstract.service(ONetworkProtocolHttpAbstract.java:253)
        at com.orientechnologies.orient.server.network.protocol.http.ONetworkProtocolHttpAbstract.execute(ONetworkProtocolHttpAbstract.java:811)
        at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:67)

2021-04-28 17:04:12:464 WARNI [orientdb_node_1]->[orientdb_node_0] Server 'orientdb_node_0' did not respond to the gossip message (db=new, timeout=10000ms), but cannot be set OFFLINE by configuration [OClusterHealthChecker]

## Steps to reproduce  
select * from User  
<An SQL script to reproduce the problem or a JUnit test case will increase **A LOT** the chance to have a quick fix>

**Comment by lee2015new** [comment]
Has anybody here?

**Comment by lee2015new** [comment]
Help!

**Comment by luigidellaquila** [comment]
Hi @lee2015new 

I'm afraid the problem here is a bit more complex: the sharding capabilities have many known issues, so even if we find an easy fix for this, you will find more problems later. In general, sharding is not recommended for a productive environment.
My advice is to stick to a full-replica deployment for now

Thanks

Luigi

**Comment by lee2015new** [comment]
> Hi @lee2015new
> 
> I'm afraid the problem here is a bit more complex: the sharding capabilities have many known issues, so even if we find an easy fix for this, you will find more problems later. In general, sharding is not recommended for a productive environment.
> My advice is to stick to a full-replica deployment for now
> 
> Thanks
> 
> Luigi

Ok，thank you
