### ISSUE TITLE
SQL Engine Internal Error: IndexOutOfBoundsException

### ISSUE THREAD

**Issue by PhantomYdn** [orientechnologies/orientdb#9597]
### OS: win10

During one of the executions of relatively simple OrientDB SQL got the following exception (below). Let me mention that in most the cases query works well - so it's just one occasion out of hundreds of executions.

```
Caused by: java.lang.IndexOutOfBoundsException: toIndex = 2147483647
	at java.util.ArrayList.subListRangeCheck(ArrayList.java:1014)
	at java.util.ArrayList.subList(ArrayList.java:1006)
	at com.orientechnologies.orient.core.sql.executor.OrderByStep.init(OrderByStep.java:140)
	at com.orientechnologies.orient.core.sql.executor.OrderByStep.lambda$syncPull$0(OrderByStep.java:49)
	at java.util.Optional.ifPresent(Optional.java:159)
	at com.orientechnologies.orient.core.sql.executor.OrderByStep.syncPull(OrderByStep.java:49)
	at com.orientechnologies.orient.core.sql.executor.LimitExecutionStep.syncPull(LimitExecutionStep.java:28)
	at com.orientechnologies.orient.core.sql.executor.OSelectExecutionPlan.fetchNext(OSelectExecutionPlan.java:34)
	at com.orientechnologies.orient.core.sql.parser.OLocalResultSet.fetchNext(OLocalResultSet.java:36)
	at com.orientechnologies.orient.core.sql.parser.OLocalResultSet.<init>(OLocalResultSet.java:27)
	at com.orientechnologies.orient.core.sql.parser.OSelectStatement.execute(OSelectStatement.java:296)
	at com.orientechnologies.orient.core.sql.parser.OStatement.execute(OStatement.java:81)
```

Query was:

```sql
select from (select expand(leads) from :campaign) where lastInteraction.campaign is null order by lastActivity desc limit :limit
```

**Comment by PhantomYdn** [comment]
Problem is here:

```java
          // compact, only at twice as the buffer, to avoid to do it at each add
          if (this.maxResults != null && maxResults * 2 < cachedResult.size()) {
            cachedResult.sort((a, b) -> orderBy.compare(a, b, ctx));
            cachedResult = new ArrayList<>(cachedResult.subList(0, maxResults));  <--- here
            sorted = true;
          }
```

Seems to be some concurrency issue.
Query can be executed in parallel: but in our case it's different thread, different ODatabaseSession and etc.

**Comment by PhantomYdn** [comment]
Ok - it was easy. LIMIT was set to Integer.MAX_VALUE, so when maxResult was multiplied to 2: it becomes less than cache size.
I recommend to change `maxResults * 2 < cachedResult.size()` to `maxResults  < cachedResult.size()>>1`

**Comment by luigidellaquila** [comment]
Hi @PhantomYdn 

Good catch, thank you very much, I'm checking it now

Thanks

Luigi
