### ISSUE TITLE
Can not create document with readOnly embedded field

### ISSUE THREAD

**Issue by mmacfadden** [orientechnologies/orientdb#9612]
## Expected behavior  
I should be able to create schema that has a mandatory and readonly field that is an embedded class.

## Actual behavior  
I can not create the class and instead get the following exception:

```
com.orientechnologies.orient.core.exception.OValidationException: The field 'Test.embedded' is immutable and cannot be altered. Field value is: Embedded{id:e1}
	DB name="TestDatabase"
	Error Code="4"
	at com.orientechnologies.orient.core.record.impl.ODocument.validateField(ODocument.java:892)
	at com.orientechnologies.orient.core.record.impl.ODocument.validate(ODocument.java:2625)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.commit(OAbstractPaginatedStorage.java:2351)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.commit(OAbstractPaginatedStorage.java:2292)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentAbstract.internalCommit(ODatabaseDocumentAbstract.java:2285)
	at com.orientechnologies.orient.core.storage.impl.local.OMicroTransaction.doCommit(OMicroTransaction.java:357)
	at com.orientechnologies.orient.core.storage.impl.local.OMicroTransaction.commit(OMicroTransaction.java:173)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentEmbedded.endMicroTransaction(ODatabaseDocumentEmbedded.java:931)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentEmbedded.saveAll(ODatabaseDocumentEmbedded.java:1361)
	at com.orientechnologies.orient.core.tx.OTransactionNoTx.saveRecord(OTransactionNoTx.java:208)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentAbstract.saveInternal(ODatabaseDocumentAbstract.java:1675)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentAbstract.save(ODatabaseDocumentAbstract.java:1623)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentAbstract.save(ODatabaseDocumentAbstract.java:133)
	at com.orientechnologies.orient.core.record.impl.ODocument.save(ODocument.java:2361)
	at com.orientechnologies.orient.core.record.impl.ODocument.save(ODocument.java:2350)
	at com.orientechnologies.orient.core.record.impl.ODocument.save(ODocument.java:122)
	at ODBTest2.main(ODBTest.java:62)
```

## Steps to reproduce  
Here is a Java class that shows the error

```java
import com.orientechnologies.common.log.OLogManager;
import com.orientechnologies.orient.core.db.ODatabaseType;
import com.orientechnologies.orient.core.db.OrientDB;
import com.orientechnologies.orient.core.db.OrientDBConfig;
import com.orientechnologies.orient.core.db.document.ODatabaseDocument;
import com.orientechnologies.orient.core.metadata.schema.OClass;
import com.orientechnologies.orient.core.metadata.schema.OProperty;
import com.orientechnologies.orient.core.metadata.schema.OType;
import com.orientechnologies.orient.core.record.OElement;
import com.orientechnologies.orient.core.security.OGlobalUserImpl;
import com.orientechnologies.orient.core.sql.executor.OResultSet;

import java.util.HashMap;

public class ODBTest {
    public static void main(String[] args) {
        OLogManager.instance().setConsoleLevel("WARNING");

        //
        // Create an ODB Database to use.
        //
        final String OdbUserName = "root";
        final String OdbPassword = "password";
        final OrientDBConfig config = OrientDBConfig.defaultConfig();
        config.getUsers().add(new OGlobalUserImpl(OdbUserName, OdbPassword, "*"));
        final OrientDB orientDB = new OrientDB("memory:TestDB", config);
        final String dbName = "TestDatabase";
        orientDB.create(dbName, ODatabaseType.MEMORY, config);
        final ODatabaseDocument db = orientDB.open(dbName, OdbUserName, OdbPassword);

        //
        // Create the Schema
        //

        final OClass EmbeddedClass = db.createClass("Embedded");
        final OProperty embeddedId = EmbeddedClass.createProperty("id", OType.STRING);
        embeddedId.setReadonly(true);
        embeddedId.setNotNull(true);
        embeddedId.setMandatory(true);

        final OClass TestClass = db.createClass("Test");
        final OProperty idProp =
                TestClass.createProperty("id", OType.STRING);
        idProp.setReadonly(true);
        idProp.setNotNull(true);
        idProp.setMandatory(true);

        final OProperty embeddedProp =
                TestClass.createProperty("embedded", OType.EMBEDDED, EmbeddedClass);
        embeddedProp.setReadonly(true);
        embeddedProp.setNotNull(true);
        embeddedProp.setMandatory(true);

        try {
            // Try to create an instance of the document.
            final OElement embeddedDoc = db.newElement(EmbeddedClass.getName());
            embeddedDoc.setProperty("id", "e1");

            final OElement testDoc = db.newElement(TestClass.getName());
            testDoc.setProperty("id", "1");
            testDoc.setProperty("embedded", embeddedDoc);

            testDoc.save();

            // This does not work either
//            final HashMap<String, Object> params = new HashMap<>();
//            params.put("embedded", embeddedDoc);
//            db.command("INSERT INTO Test SET id=1, embedded=:embedded", params);

            final OResultSet results = db.query("SELECT FROM Test");
            results.forEachRemaining(doc -> System.out.println(doc.toJSON()));
        } catch (Throwable e){
            e.printStackTrace();
        }

        db.close();
        orientDB.close();
    }
}
```

**Comment by mmacfadden** [comment]
FYI. This is preventing our migration from 3.0.x to 3.2.x.

**Comment by mmacfadden** [comment]
@luigidellaquila and @laa If there is anything I can do to help with this please let me know. Happy to help.
