### ISSUE TITLE
User or password not valid for username for new created plocal database

### ISSUE THREAD

**Issue by devent** [orientechnologies/orientdb#9613]
## Expected behavior  
New plocal database can be opened with admin/admin

## Actual behavior  
```
com.orientechnologies.orient.core.exception.OSecurityAccessException: User or password not valid for username: admin, database: 'test'
	DB name="test"
	at com.orientechnologies.orient.core.metadata.security.OSecurityShared.securityAuthenticate(OSecurityShared.java:295)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentEmbedded.internalOpen(ODatabaseDocumentEmbedded.java:261)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentEmbedded.internalOpen(ODatabaseDocumentEmbedded.java:247)
	at com.orientechnologies.orient.core.db.OrientDBEmbedded.open(OrientDBEmbedded.java:501)
	at com.orientechnologies.orient.core.db.OrientDB.open(OrientDB.java:226)
```

## Steps to reproduce  
```
// Groovy JUnit 5 Test
    @Test
    void "orientdb create db"(@TempDir Path tmp) {
        def o = new OrientDB("embedded:${tmp.toFile().absolutePath}", OrientDBConfig.defaultConfig());
        o.create("test", ODatabaseType.PLOCAL)
        def db = o.open("test", "admin", "admin") // exception here
        db.close()
        o.close()
    }
```

**Comment by devent** [comment]
It works fine in version 3.1.11

**Comment by timw** [comment]
Default users are no longer created automatically for databases since 3.2.0.

https://orientdb.org/docs/3.2.x/release/3.2/What-is-new-in-OrientDB-3.2.html

**Comment by devent** [comment]
Thank you. I was searching for the 3.2 docu.

If you go to https://orientdb.org/docs then you are redirected to http://www.orientdb.com/docs/last/index.html and in the drop down menu is just versions 2.2.x, 3.0 and 3.1.
From https://orientdb.org/ you can go to "Full documentation" that is https://orientdb.org/docs/3.0.x/ and there is also just versions 2.2.x, 3.0 and 3.1.
