### ISSUE TITLE
Error deserializing record

### ISSUE THREAD

**Issue by maxim22m** [orientechnologies/orientdb#9622]
## Expected behavior  
`normally print record in studio or console`

## Steps to reproduce  
when I want to select record with id #37:26652 server console print below error/warning and repeatedly just print "A". ([screenshot of server.bat](https://i.stack.imgur.com/3aIBm.png))
- DB is working fine but accidentally this happening.
- I use batch insert with REST API.
- I using transaction.
- I insert with script, first UPSERT vertex then create edge, so fully of update and insert.
- I also add some property in edges
this behavior also exist when other query on this record like delete, also cannot add property in itself class and with every try that error happening.
I guess maybe some character in that record cause of this, but till cannot select I'm not sure. what is your idea?

## Actual behavior  
```2021-06-07 15:16:06:033 INFO  Storage 'plocal:C:\orientdb-3.2.0\databases/c_graph' is opened under OrientDB distribution : 3.2.0 (build c08b76230798b477a8abbf2312b30ecddad842ad, branch develop) [OLocalPaginatedStorage]java.lang.ArrayIndexOutOfBoundsException: -1
    at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinary.fromStream(ORecordSerializerBinary.java:102)
    at com.orientechnologies.orient.core.record.impl.ODocument.deserializeFields(ODocument.java:2422)
    at com.orientechnologies.orient.core.record.impl.ODocument.checkForFields(ODocument.java:3258)
    at com.orientechnologies.orient.core.record.impl.ODocument.hasProperty(ODocument.java:1938)
    at com.orientechnologies.orient.core.record.impl.ODocument.containsField(ODocument.java:1925)
    at com.orientechnologies.orient.core.sql.executor.OResultInternal.hasProperty(OResultInternal.java:245)
    at com.orientechnologies.orient.core.sql.parser.OSuffixIdentifier.execute(OSuffixIdentifier.java:118)
    at com.orientechnologies.orient.core.sql.parser.OBaseIdentifier.execute(OBaseIdentifier.java:65)
    at com.orientechnologies.orient.core.sql.parser.OBaseExpression.execute(OBaseExpression.java:111)
    at com.orientechnologies.orient.core.sql.parser.OExpression.execute(OExpression.java:102)
    at com.orientechnologies.orient.core.sql.parser.ONotInCondition.evaluate(ONotInCondition.java:53)
    at com.orientechnologies.orient.core.sql.parser.ONotBlock.evaluate(ONotBlock.java:44)
    at com.orientechnologies.orient.core.sql.parser.OAndBlock.evaluate(OAndBlock.java:47)
    at com.orientechnologies.orient.core.sql.parser.OOrBlock.evaluate(OOrBlock.java:49)
    at com.orientechnologies.orient.core.sql.parser.OWhereClause.matchesFilters(OWhereClause.java:56)
    at com.orientechnologies.orient.core.sql.executor.FilterStep$1.fetchNextItem(FilterStep.java:64)
    at com.orientechnologies.orient.core.sql.executor.FilterStep$1.hasNext(FilterStep.java:87)
    at com.orientechnologies.orient.core.sql.parser.OLocalResultSet.fetchNext(OLocalResultSet.java:37)
    at com.orientechnologies.orient.core.sql.parser.OLocalResultSet.<init>(OLocalResultSet.java:27)
    at com.orientechnologies.orient.core.sql.parser.OSelectStatement.execute(OSelectStatement.java:276)
    at com.orientechnologies.orient.core.sql.parser.OStatement.execute(OStatement.java:72)
    at com.orientechnologies.orient.core.db.document.ODatabaseDocumentEmbedded.command(ODatabaseDocumentEmbedded.java:654)
    at com.orientechnologies.orient.core.metadata.schema.OClassImpl.checkPersistentPropertyType(OClassImpl.java:1428)
    at com.orientechnologies.orient.core.metadata.schema.OClassEmbedded.addPropertyInternal(OClassEmbedded.java:427)
    at com.orientechnologies.orient.core.metadata.schema.OClassEmbedded$1.call(OClassEmbedded.java:65)
    at com.orientechnologies.orient.core.metadata.schema.OClassEmbedded$1.call(OClassEmbedded.java:62)
    at com.orientechnologies.orient.core.db.OScenarioThreadLocal.executeAsDistributed(OScenarioThreadLocal.java:91)
    at com.orientechnologies.orient.core.metadata.schema.OClassEmbedded.addProperty(OClassEmbedded.java:61)
    at com.orientechnologies.orient.core.sql.parser.OCreatePropertyStatement.executeInternal(OCreatePropertyStatement.java:87)
    at com.orientechnologies.orient.core.sql.parser.OCreatePropertyStatement.executeDDL(OCreatePropertyStatement.java:45)
    at com.orientechnologies.orient.core.sql.executor.ODDLExecutionPlan.executeInternal(ODDLExecutionPlan.java:51)
    at com.orientechnologies.orient.core.sql.parser.ODDLStatement.execute(ODDLStatement.java:40)
    at com.orientechnologies.orient.core.sql.parser.OStatement.execute(OStatement.java:72)
    at com.orientechnologies.orient.core.db.document.ODatabaseDocumentEmbedded.command(ODatabaseDocumentEmbedded.java:654)
    at com.orientechnologies.orient.server.network.protocol.http.command.post.OServerCommandPostCommand.executeStatement(OServerCommandPostCommand.java:219)
    at com.orientechnologies.orient.server.network.protocol.http.command.post.OServerCommandPostCommand.execute(OServerCommandPostCommand.java:104)
    at com.orientechnologies.orient.server.network.protocol.http.command.post.OServerCommandPostCommandGraph.execute(OServerCommandPostCommandGraph.java:34)
    at com.orientechnologies.orient.server.network.protocol.http.ONetworkProtocolHttpAbstract.service(ONetworkProtocolHttpAbstract.java:242)
    at com.orientechnologies.orient.server.network.protocol.http.ONetworkProtocolHttpAbstract.execute(ONetworkProtocolHttpAbstract.java:800)
    at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:67)

2021-06-07 15:16:25:421 WARNI {db=c_graph} Error deserializing record with id #37:26652 send this data for debugging: //////////8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA```

**Comment by tglman** [comment]
Hi, 

Could you try to reproduce this with the last release 3.2.7 ?

Bye
