### ISSUE TITLE
Error importing database 

### ISSUE THREAD

**Issue by adriancoca** [orientechnologies/orientdb#9623]
## Actual behavior  
Removed 16 classes.
Importing database info...OK
Importing clusters...
- Creating cluster 'internal'...OK, assigned id=0
- Creating cluster 'default'...OK, assigned id=3
- Creating cluster 'osecuritypolicy'...Error on database import happened just before line 0, column 474
com.orientechnologies.orient.core.exception.OConfigurationException: Imported cluster 'osecuritypolicy' has id=6 different from the original: 4. To continue the import drop the cluster 'ouser' that has 3 records
        DB name="kaseriaproduction"
        at com.orientechnologies.orient.core.db.tool.ODatabaseImport.importClusters(ODatabaseImport.java:1002)
        at com.orientechnologies.orient.core.db.tool.ODatabaseImport.importDatabase(ODatabaseImport.java:207)
        at com.orientechnologies.orient.console.OConsoleDatabaseApp.importDatabase(OConsoleDatabaseApp.java:2046)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.orientechnologies.common.console.OConsoleApplication.execute(OConsoleApplication.java:451)
        at com.orientechnologies.common.console.OConsoleApplication.executeCommands(OConsoleApplication.java:287)
        at com.orientechnologies.common.console.OConsoleApplication.run(OConsoleApplication.java:142)
        at com.orientechnologies.orient.console.OConsoleDatabaseApp.main(OConsoleDatabaseApp.java:128)

Error: com.orientechnologies.orient.core.db.tool.ODatabaseExportException: Error on importing database 'kaseriaproduction' from file: kaseria.gz

**Comment by sblommers** [comment]
Did you try dropping the cluster from the target database as the error suggests?
