### ISSUE TITLE
Socket Read time out REST API batch push using thread in java

### ISSUE THREAD

**Issue by KirubakaranSP** [orientechnologies/orientdb#9624]
## Expected behavior  
Am pushing batch of vertex through REST API from java via Thread.It results in Socket java.net.SocketTimeoutException: Read timed out .Am i missing any configuration here ?I've tried configuring NETWORK_SOCKET_TIMEOUT,still same exists.Kindly help me on this.
Request details : 
Content-Type - application/json
Authorization header has been set

Exception trace 
Suppressed: java.net.SocketTimeoutException: Read timed out|
at java.net.SocketInputStream.socketRead0(Native Method)|
at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)|
at java.net.SocketInputStream.read(SocketInputStream.java:171)|
at java.net.SocketInputStream.read(SocketInputStream.java:141)|
at java.io.BufferedInputStream.fill(BufferedInputStream.java:246)|
at java.io.BufferedInputStream.read1(BufferedInputStream.java:286)|
at java.io.BufferedInputStream.read(BufferedInputStream.java:345)|
at sun.net.www.http.HttpClient.parseHTTPHeader(HttpClient.java:735)|
at sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:678)|
at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1587)|
at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1492)|
at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480)|

**Comment by lvca** [comment]
What's the size of the packet you're sending?

**Comment by KirubakaranSP** [comment]
The size of the packet is 1000 and parallely running 10 threads.

**Comment by lvca** [comment]
1,000 operations or 1,000 bytes? How big is the packet in Kb/Mb?

**Comment by KirubakaranSP** [comment]
I am inserting 1000 vertices  as JSON through rest API from java.

**Comment by lvca** [comment]
It all depends on how big is each vertex. How many properties? Do you have binary or long strings? If you can compute that amount in terms of total Kb sent it would be helpful.

Generally speaking, if you're sending big packets concurrently, OrientDB's web socket could having hard time to process the requests.

Try reducing the parallel threads from 10 to 3 and see how it goes. Also from 1000 vertices, try with 300.

Try to play around those numbers to see a good configuration based on your data and hw/sw available.
