### ISSUE TITLE
UnsupportedOperationException while fetching vertices by VertexQuery using remote connection

### ISSUE THREAD

**Issue by baguadev** [orientechnologies/orientdb#9661]
## Expected behavior  
It should be possible to fetch vertices by relation. As it works in 3.0.x versions of OrientDB.
Also if the number of fetched vertices is less than 40 it works fine as in this case OEmbeddedRidBag is used.

## Actual behavior  
Exception thrown:
java.lang.UnsupportedOperationException: null
	at com.orientechnologies.orient.client.remote.OSBTreeCollectionManagerRemote.loadTree(OSBTreeCollectionManagerRemote.java:68)
	at com.orientechnologies.orient.core.storage.ridbag.sbtree.OSBTreeCollectionManagerAbstract.loadSBTree(OSBTreeCollectionManagerAbstract.java:195)
	at com.orientechnologies.orient.core.storage.ridbag.sbtree.OSBTreeRidBag.loadTree(OSBTreeRidBag.java:894)
	at com.orientechnologies.orient.core.storage.ridbag.sbtree.OSBTreeRidBag.access$500(OSBTreeRidBag.java:76)
	at com.orientechnologies.orient.core.storage.ridbag.sbtree.OSBTreeRidBag$SBTreeMapEntryIterator.init(OSBTreeRidBag.java:393)
	at com.orientechnologies.orient.core.storage.ridbag.sbtree.OSBTreeRidBag$SBTreeMapEntryIterator.<init>(OSBTreeRidBag.java:320)
	at com.orientechnologies.orient.core.storage.ridbag.sbtree.OSBTreeRidBag.rawIterator(OSBTreeRidBag.java:469)
	at com.orientechnologies.orient.core.db.record.ridbag.ORidBag.rawIterator(ORidBag.java:206)
	at com.tinkerpop.blueprints.impls.orient.OrientVertex.getEdges(OrientVertex.java:839)
	at com.tinkerpop.blueprints.impls.orient.OrientVertex.getEdges(OrientVertex.java:747)
	at com.tinkerpop.blueprints.util.DefaultVertexQuery$DefaultVertexQueryIterable.<init>(DefaultVertexQuery.java:110)
	at com.tinkerpop.blueprints.util.DefaultVertexQuery.vertices(DefaultVertexQuery.java:84)

## Steps to reproduce  
Probably the result of this commit :
* disabled support for tree ridbags in remote
https://github.com/orientechnologies/orientdb/commit/8110b05af752733b24b1b334a998f70c0b3843c1

Also i've tried to always use embedded ridbag by setting following configuration setting on client side:
OGlobalConfiguration.RID_BAG_EMBEDDED_TO_SBTREEBONSAI_THRESHOLD.setValue(Integer.MAX_VALUE);
but it seems to have no affect.  Is there a way to avoid somehow OSBTreeRidBag and always use embedded one?
Thanks

**Comment by andrii0lomakin** [comment]
HI @baguadev , in 3.2 version we use a new version of the tree-based presentation of edges, which is completely independent of the storage that you use. Is it feasible for you to upgrade? Do you have the same problems in the case of usage of the embedded databases for example if you open it from the console on the server side?

**Comment by andrii0lomakin** [comment]
If it is feasible for you to migrate you need to wait till the system will automatically upgrade the format of the presentation of edges. That will be performed the first time you open the database. Once migration is completed you will automatically use the new format.

**Comment by baguadev** [comment]
Thanks for reply, @laa 
Unfortunately wasn't able to run version 3.2.0 under JDK 16.  It throws an exception:
Exception in thread "main" java.lang.NoClassDefFoundError: jdk/nashorn/api/scripting/ClassFilter
	at com.orientechnologies.orient.core.command.script.js.OJSScriptEngineFactory.maybeWrap(OJSScriptEngineFactory.java:20)
	at com.orientechnologies.orient.core.command.script.OScriptManager.registerEngine(OScriptManager.java:495)
	at com.orientechnologies.orient.core.command.script.OScriptManager.<init>(OScriptManager.java:107)
	at com.orientechnologies.orient.core.db.OrientDBEmbedded.<init>(OrientDBEmbedded.java:108)
	at com.orientechnologies.orient.core.db.OrientDBInternal.embedded(OrientDBInternal.java:119)
	at com.orientechnologies.orient.server.OServer.startupFromConfiguration(OServer.java:408)
	at com.orientechnologies.orient.server.OServer.startup(OServer.java:340)

But discovered that if i set the option ridBag.embeddedToSbtreeBonsaiThreshold to Integer.MAX_VALUE on a server side and then populate database with data it can be accessed later without error. 
In my case this approach works as i can repopulate all data into database from scratch.
So can continue with version 3.1.x for now.
Thanks

**Comment by andrii0lomakin** [comment]
Hi @baguadev 
I did not notice that initially, we do not support Java 16. Only Java 11, currently we have work in progress for migration of project under Java 16.

**Comment by andrii0lomakin** [comment]
Hi @baguadev, could you try the same on Java 11 ?

**Comment by baguadev** [comment]
Hello @laa 
Tried it on JDK 11 with version 3.2.0
When ran it against existing DB got error:
com.orientechnologies.orient.core.exception.OCommandExecutionException: Cannot create user guest: role guest does not exist
	DB name="OSystem"
	at com.orientechnologies.orient.core.sql.parser.OCreateSystemUserStatement.lambda$executeSimple$0(OCreateSystemUserStatement.java:99)
	at com.orientechnologies.orient.core.db.OSystemDatabase.executeWithDB(OSystemDatabase.java:201)
	at com.orientechnologies.orient.core.sql.parser.OCreateSystemUserStatement.executeSimple(OCreateSystemUserStatement.java:48)
	at com.orientechnologies.orient.core.sql.executor.OSingleOpServerExecutionPlan.executeInternal(OSingleOpServerExecutionPlan.java:97)
	at com.orientechnologies.orient.core.sql.parser.OSimpleExecServerStatement.execute(OSimpleExecServerStatement.java:49)
	at com.orientechnologies.orient.core.sql.parser.OServerStatement.execute(OServerStatement.java:72)
	at com.orientechnologies.orient.core.db.OrientDBEmbedded.executeServerStatement(OrientDBEmbedded.java:1194)
	at com.orientechnologies.orient.core.db.OrientDB.execute(OrientDB.java:364)
	at com.orientechnologies.orient.server.OServer.createDefaultServerUsers(OServer.java:1067)
	at com.orientechnologies.orient.server.OServer.loadUsers(OServer.java:908)
	at com.orientechnologies.orient.server.OServer.activate(OServer.java:498)

So for now will stay on 3.1.x with that workaround setting
Thanks

**Comment by andrii0lomakin** [comment]
@baguadev since 3.2 version default users are switched off to prevent security problems you need to create your own users.

**Comment by andrii0lomakin** [comment]
You do suggest  you do not use default users because of security reasons

**Comment by tglman** [comment]
we got a duplicate here: https://github.com/orientechnologies/orientdb/issues/9677 

I think we need to actually fix the original problem, reading of the tree  are still needed in remote, and there is already an implementation for read them, is probably just not used in all the cases is needed

**Comment by tglman** [comment]
Hi,
This should have been fixed in 3.1.13

bye

**Comment by tglman** [comment]
Solved a while ago, closing
