### ISSUE TITLE
OrientDB v3.2.0 server side javascript function throws exception

### ISSUE THREAD

**Issue by holocentric-bmsnext** [orientechnologies/orientdb#9675]
### OS: windows

tested with <entry value="false" name="OGlobalConfiguration.SCRIPT_POLYGLOT_USE_GRAAL"/>

## Expected behavior  
the size of the OMultiCollectionIterator instance should be returned and no exceptions should be thrown.
Same script used to work prior to 3.2.0 (e.g. works fine in 3.1.7)

## Actual behavior  
javax.script.ScriptException: org.graalvm.polyglot.PolyglotException: TypeError: invokeMember (size) on com.orientechnologies.common.collection.OMultiCollectionIterator@1876bfd6 failed due to: Unknown identifier: size --> org.graalvm.polyglot.PolyglotException: TypeError: invokeMember (size) on com.orientechnologies.common.collection.OMultiCollectionIterator@1876bfd6 failed due to: Unknown identifier: size 

## Steps to reproduce  
Create two vertices and add some edges between the vertices
Create a javascript function that takes the edges as an input parameter
inside the function, return items.size() or try to call any method on the OMultiCollectionIterator class.

Call that function from studio, 
e.g. select countSize(outE("EdgeClassName")) from VertexClassName

**Comment by calebeaires** [comment]
Same here. This is a key feature at the lib, but the last version does not works.

**Comment by tglman** [comment]
Hi,

Do you have an example function for this case ?

Regards

**Comment by holocentric-bmsnext** [comment]
just create a javascript function in the studio named 'countSize'. then from the Browse enter this query

create two vertex classes (VertexClassName and VertexClassNamexx), then create an edge class between the two vertices. name it 'EdgeClassName'
`select countSize(outE("EdgeClassName")) from VertexClassName`

in the countSize javascript function, it should have one input argument, which should be the edges passed in.
call this
`edges.size()`


then you will get below error in the orient console logs

`ion : 3.2.9 (build 4912c478a195f920bde77e6c014e7beab1dda229, branch UNKNOWN) [OLocalPaginatedStorage]$ANSI{green {db=Repository}} Error during sending an error to client
java.io.NotSerializableException: com.oracle.truffle.polyglot.PolyglotExceptionImpl
        at java.io.ObjectOutputStream.writeObject0(Unknown Source)
        at java.io.ObjectOutputStream.defaultWriteFields(Unknown Source)
        at java.io.ObjectOutputStream.writeSerialData(Unknown Source)
        at java.io.ObjectOutputStream.writeOrdinaryObject(Unknown Source)
        at java.io.ObjectOutputStream.writeObject0(Unknown Source)
        at java.io.ObjectOutputStream.defaultWriteFields(Unknown Source)
        at java.io.ObjectOutputStream.defaultWriteObject(Unknown Source)
        at java.lang.Throwable.writeObject(Unknown Source)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at java.io.ObjectStreamClass.invokeWriteObject(Unknown Source)
        at java.io.ObjectOutputStream.writeSerialData(Unknown Source)
        at java.io.ObjectOutputStream.writeOrdinaryObject(Unknown Source)
        at java.io.ObjectOutputStream.writeObject0(Unknown Source)
        at java.io.ObjectOutputStream.defaultWriteFields(Unknown Source)
        at java.io.ObjectOutputStream.defaultWriteObject(Unknown Source)
        at java.lang.Throwable.writeObject(Unknown Source)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at java.io.ObjectStreamClass.invokeWriteObject(Unknown Source)
        at java.io.ObjectOutputStream.writeSerialData(Unknown Source)
        at java.io.ObjectOutputStream.writeOrdinaryObject(Unknown Source)
        at java.io.ObjectOutputStream.writeObject0(Unknown Source)
        at java.io.ObjectOutputStream.writeObject(Unknown Source)
        at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.sendError(ONetworkProtocolBinary.java:769)
        at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.sessionRequest(ONetworkProtocolBinary.java:376)
        at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.execute(ONetworkProtocolBinary.java:239)
        at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:68)
$ANSI{green {db=Repository}} Error during sending an error to client
java.io.NotSerializableException: com.oracle.truffle.polyglot.PolyglotExceptionImpl
        at java.io.ObjectOutputStream.writeObject0(Unknown Source)
        at java.io.ObjectOutputStream.defaultWriteFields(Unknown Source)
        at java.io.ObjectOutputStream.writeSerialData(Unknown Source)
        at java.io.ObjectOutputStream.writeOrdinaryObject(Unknown Source)
        at java.io.ObjectOutputStream.writeObject0(Unknown Source)
        at java.io.ObjectOutputStream.defaultWriteFields(Unknown Source)
        at java.io.ObjectOutputStream.defaultWriteObject(Unknown Source)
        at java.lang.Throwable.writeObject(Unknown Source)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at java.io.ObjectStreamClass.invokeWriteObject(Unknown Source)
        at java.io.ObjectOutputStream.writeSerialData(Unknown Source)
        at java.io.ObjectOutputStream.writeOrdinaryObject(Unknown Source)
        at java.io.ObjectOutputStream.writeObject0(Unknown Source)
        at java.io.ObjectOutputStream.defaultWriteFields(Unknown Source)
        at java.io.ObjectOutputStream.defaultWriteObject(Unknown Source)
        at java.lang.Throwable.writeObject(Unknown Source)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at java.io.ObjectStreamClass.invokeWriteObject(Unknown Source)
        at java.io.ObjectOutputStream.writeSerialData(Unknown Source)
        at java.io.ObjectOutputStream.writeOrdinaryObject(Unknown Source)
        at java.io.ObjectOutputStream.writeObject0(Unknown Source)
        at java.io.ObjectOutputStream.writeObject(Unknown Source)
        at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.sendError(ONetworkProtocolBinary.java:769)
        at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.sessionRequest(ONetworkProtocolBinary.java:376)
        at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.execute(ONetworkProtocolBinary.java:239)
        at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:68)`

![image](https://user-images.githubusercontent.com/34297409/189795706-118b217e-5e70-4319-b905-859cdc98c3e3.png)

As a result, we have not been able to upgrade to orientdb 3.2.0, would appreciate if a workaround can be provided.

**Comment by holocentric-bmsnext** [comment]
with orient v 3.2.9 adding below line in the config solves the problem.
`	<entry name="script.polyglot.useGraal" value="false" />`

**Comment by shanmathik** [comment]
Hi @holocentric-bmsnext & @tglman  ,
Can you specify what exactly needs to be added to the config, it would really help. Thanks!

**Comment by tglman** [comment]
Hi,

looking at the issue I guess has been enough to add the package in the list of allowed packages in the `orientdb-server-config.xml` something like this:
```xml
...
        <handler
                class="com.orientechnologies.orient.server.handler.OServerSideScriptInterpreter">
            <parameters>
                <parameter name="enabled" value="true"/>
                <parameter name="allowedLanguages" value="SQL,gremlin,groovy"/>
                <!--  Comma separated packages  allowed in JS scripts eg. java.math.*, java.util.ArrayList -->
                <parameter name="allowedPackages" value="com.orientechnologies.common.collection.OMultiCollectionIterator"/>
            </parameters>
        </handler>
...
```

but I do not know if @holocentric-bmsnext actually did that.

Regards

**Comment by holocentric-bmsnext** [comment]
Hi,
adding this line fixed the problem
`<entry name="script.polyglot.useGraal" value="false" />`

Regards

**Comment by cuongrep** [comment]
@tglman,
Hi,
In case, I'm using OrientDB embedded mode, I got the same problem regarding `java.lang.ClassNotFoundException: org.graalvm.polyglot.PolyglotException`
What should I configure? Bro?
