### ISSUE TITLE
Orient DB 3.2.2 not resilient on SIGKILL

### ISSUE THREAD

**Issue by jamieb22** [orientechnologies/orientdb#9685]
## Expected behavior  

When database is killed, it *always* results in a corrupted state. It is not resilient.

## Actual behavior  

```
Caused by: com.orientechnologies.orient.core.exception.OStorageException: Exception during execution of atomic operation inside of storage archiva
	at com.orientechnologies.orient.core.storage.impl.local.paginated.atomicoperations.OAtomicOperationsManager.executeInsideAtomicOperation(OAtomicOperationsManager.java:157)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.open(OAbstractPaginatedStorage.java:414)
	at com.orientechnologies.orient.core.db.OrientDBEmbedded.open(OrientDBEmbedded.java:296)
	... 19 common frames omitted
Caused by: java.lang.NullPointerException: null
	at com.orientechnologies.orient.core.storage.cache.chm.AsyncReadCache.releaseFromRead(AsyncReadCache.java:290)
	at com.orientechnologies.orient.core.storage.impl.local.paginated.atomicoperations.OAtomicOperation.releasePageFromRead(OAtomicOperation.java:244)
	at com.orientechnologies.orient.core.storage.impl.local.paginated.base.ODurableComponent.releasePageFromRead(ODurableComponent.java:169)
	at com.orientechnologies.orient.core.storage.index.sbtree.singlevalue.OCellBTreeSingleValue.findBucket(OCellBTreeSingleValue.java:1247)
	at com.orientechnologies.orient.core.storage.index.sbtree.singlevalue.OCellBTreeSingleValue.get(OCellBTreeSingleValue.java:164)
	at com.orientechnologies.orient.core.storage.config.OClusterBasedStorageConfiguration.readProperty(OClusterBasedStorageConfiguration.java:1619)
	at com.orientechnologies.orient.core.storage.config.OClusterBasedStorageConfiguration.readConfiguration(OClusterBasedStorageConfiguration.java:814)
	at com.orientechnologies.orient.core.storage.config.OClusterBasedStorageConfiguration.load(OClusterBasedStorageConfiguration.java:177)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.lambda$open$1(OAbstractPaginatedStorage.java:417)
	at com.orientechnologies.orient.core.storage.impl.local.paginated.atomicoperations.OAtomicOperationsManager.executeInsideAtomicOperation(OAtomicOperationsManager.java:153)
	... 21 common frames omitted
```

## Steps to reproduce  

Start Orient DB update, kill the database using kill -9 command. Start server up and the database will no longer [open.]

([database.zip](https://github.com/orientechnologies/orientdb/files/7220616/database.zip))

I refer you to this thread: https://news.ycombinator.com/item?id=7135325

**Comment by jamieb22** [comment]
More errors in below db.

  c[archiva.zip](https://github.com/orientechnologies/orientdb/files/7230078/archiva.zip)

**Comment by jamieb22** [comment]
```
com.orientechnologies.orient.core.exception.ODatabaseException: Cannot open database 'archiva'
	at com.orientechnologies.orient.core.db.OrientDBEmbedded.open(OrientDBEmbedded.java:315)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.open(ODatabaseDocumentTx.java:898)
	at com.orientechnologies.orient.core.db.OPartitionedDatabasePool$DatabaseDocumentTxPooled.internalOpen(OPartitionedDatabasePool.java:440)
	at com.orientechnologies.orient.core.db.OPartitionedDatabasePool.openDatabase(OPartitionedDatabasePool.java:303)
	at com.orientechnologies.orient.core.db.OPartitionedDatabasePool.acquire(OPartitionedDatabasePool.java:261)
	at com.tinkerpop.blueprints.impls.orient.OrientBaseGraph.<init>(OrientBaseGraph.java:146)
	at com.tinkerpop.blueprints.impls.orient.OrientTransactionalGraph.<init>(OrientTransactionalGraph.java:78)
	at com.tinkerpop.blueprints.impls.orient.OrientGraph.<init>(OrientGraph.java:137)
	at com.tinkerpop.blueprints.impls.orient.OrientGraphFactory$1.getGraph(OrientGraphFactory.java:87)
	at com.tinkerpop.blueprints.impls.orient.OrientGraphFactory.getTx(OrientGraphFactory.java:224)
	..
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.orientechnologies.orient.core.exception.OStorageException: Exception during execution of atomic operation inside of storage archiva
	at com.orientechnologies.orient.core.storage.impl.local.paginated.atomicoperations.OAtomicOperationsManager.executeInsideAtomicOperation(OAtomicOperationsManager.java:157)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.open(OAbstractPaginatedStorage.java:414)
	at com.orientechnologies.orient.core.db.OrientDBEmbedded.open(OrientDBEmbedded.java:296)
	... 19 common frames omitted
Caused by: java.lang.IllegalArgumentException: null
	at java.nio.Buffer.position(Buffer.java:244)
	at com.orientechnologies.orient.core.storage.impl.local.paginated.base.ODurablePage.deserializeFromDirectMemory(ODurablePage.java:170)
	at com.orientechnologies.orient.core.storage.index.sbtree.singlevalue.OSBTreeBucketSingleValue.getKey(OSBTreeBucketSingleValue.java:317)
	at com.orientechnologies.orient.core.storage.index.sbtree.singlevalue.OSBTreeBucketSingleValue.find(OSBTreeBucketSingleValue.java:103)
	at com.orientechnologies.orient.core.storage.index.sbtree.singlevalue.OCellBTreeSingleValue.findBucket(OCellBTreeSingleValue.java:1230)
	at com.orientechnologies.orient.core.storage.index.sbtree.singlevalue.OCellBTreeSingleValue.get(OCellBTreeSingleValue.java:164)
	at com.orientechnologies.orient.core.storage.config.OClusterBasedStorageConfiguration.readProperty(OClusterBasedStorageConfiguration.java:1619)
	at com.orientechnologies.orient.core.storage.config.OClusterBasedStorageConfiguration.readConfiguration(OClusterBasedStorageConfiguration.java:814)
	at com.orientechnologies.orient.core.storage.config.OClusterBasedStorageConfiguration.load(OClusterBasedStorageConfiguration.java:177)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.lambda$open$1(OAbstractPaginatedStorage.java:417)
	at com.orientechnologies.orient.core.storage.impl.local.paginated.atomicoperations.OAtomicOperationsManager.executeInsideAtomicOperation(OAtomicOperationsManager.java:153)
	... 21 common frames omitted


```


[archiva.zip](https://github.com/orientechnologies/orientdb/files/7230086/archiva.zip)

**Comment by jamieb22** [comment]
```
com.orientechnologies.orient.core.exception.ODatabaseException: Cannot open database 'archiva'
	at com.orientechnologies.orient.core.db.OrientDBEmbedded.open(OrientDBEmbedded.java:315)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.open(ODatabaseDocumentTx.java:898)
	at com.orientechnologies.orient.core.db.OPartitionedDatabasePool$DatabaseDocumentTxPooled.internalOpen(OPartitionedDatabasePool.java:440)
	at com.orientechnologies.orient.core.db.OPartitionedDatabasePool.openDatabase(OPartitionedDatabasePool.java:303)
	at com.orientechnologies.orient.core.db.OPartitionedDatabasePool.acquire(OPartitionedDatabasePool.java:261)
	..
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.orientechnologies.orient.core.exception.OStorageException: Exception during execution of atomic operation inside of storage archiva
	at com.orientechnologies.orient.core.storage.impl.local.paginated.atomicoperations.OAtomicOperationsManager.executeInsideAtomicOperation(OAtomicOperationsManager.java:157)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.open(OAbstractPaginatedStorage.java:414)
	at com.orientechnologies.orient.core.db.OrientDBEmbedded.open(OrientDBEmbedded.java:296)
	... 19 common frames omitted
Caused by: java.lang.IndexOutOfBoundsException: null
	at java.nio.Buffer.checkIndex(Buffer.java:550)
	at java.nio.DirectByteBuffer.getInt(DirectByteBuffer.java:684)
	at com.orientechnologies.orient.core.storage.impl.local.paginated.base.ODurablePage.getIntValue(ODurablePage.java:119)
	at com.orientechnologies.orient.core.storage.index.sbtree.singlevalue.OSBTreeBucketSingleValue.getRight(OSBTreeBucketSingleValue.java:235)
	at com.orientechnologies.orient.core.storage.index.sbtree.singlevalue.OCellBTreeSingleValue.findBucket(OCellBTreeSingleValue.java:1241)
	at com.orientechnologies.orient.core.storage.index.sbtree.singlevalue.OCellBTreeSingleValue.get(OCellBTreeSingleValue.java:164)
	at com.orientechnologies.orient.core.storage.config.OClusterBasedStorageConfiguration.readProperty(OClusterBasedStorageConfiguration.java:1619)
	at com.orientechnologies.orient.core.storage.config.OClusterBasedStorageConfiguration.readConfiguration(OClusterBasedStorageConfiguration.java:814)
	at com.orientechnologies.orient.core.storage.config.OClusterBasedStorageConfiguration.load(OClusterBasedStorageConfiguration.java:177)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.lambda$open$1(OAbstractPaginatedStorage.java:417)
	at com.orientechnologies.orient.core.storage.impl.local.paginated.atomicoperations.OAtomicOperationsManager.executeInsideAtomicOperation(OAtomicOperationsManager.java:153)
	... 21 common frames omitted
```

[archiva.zip](https://github.com/orientechnologies/orientdb/files/7230146/archiva.zip)

**Comment by luigidellaquila** [comment]
Hi @jamieb22 

Looking at the stack traces, I see something strange: the line numbers do not match with the source of v 3.2.2.
Can you please check that you do not have old JAR files in the distribution? Do you have an $ORIENTDB_HOME system variable set?

Thanks

Luigi

**Comment by jamieb22** [comment]
Thanks for identifying the cause. My apologies. The issue is resolved when I reinstalled OrientDB.
