### ISSUE TITLE
String record parsed as double on import

### ISSUE THREAD

**Issue by florian-stoica** [orientechnologies/orientdb#9742]
## Expected behavior  
Simple import/export should work

## Actual behavior  
java.lang.NumberFormatException: For input string: "1.0[ICCProfile]GreenTRC-0.0"
	at jdk.internal.math.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:2054) ~[?:?]
	at jdk.internal.math.FloatingDecimal.parseDouble(FloatingDecimal.java:110) ~[?:?]
	at java.lang.Double.parseDouble(Double.java:556) ~[?:?]
	at java.lang.Double.<init>(Double.java:638) ~[?:?]
	at com.orientechnologies.orient.core.serialization.serializer.record.string.ORecordSerializerJSON.getValueV0(ORecordSerializerJSON.java:1048) ~[orientdb-core-3.2.3.jar!/:3.2.3]
	at com.orientechnologies.orient.core.serialization.serializer.record.string.ORecordSerializerJSON.processRecordsV0(ORecordSerializerJSON.java:642) ~[orientdb-core-3.2.3.jar!/:3.2.3]
	at com.orientechnologies.orient.core.serialization.serializer.record.string.ORecordSerializerJSON.fromStringV0(ORecordSerializerJSON.java:462) ~[orientdb-core-3.2.3.jar!/:3.2.3]
	at com.orientechnologies.orient.core.serialization.serializer.record.string.ORecordSerializerJSON.fromStream(ORecordSerializerJSON.java:323) ~[orientdb-core-3.2.3.jar!/:3.2.3]
	at com.orientechnologies.orient.core.db.tool.ODatabaseImport.importRecord(ODatabaseImport.java:2235) ~[orientdb-core-3.2.3.jar!/:3.2.3]
	at com.orientechnologies.orient.core.db.tool.ODatabaseImport.importRecords(ODatabaseImport.java:2583) ~[orientdb-core-3.2.3.jar!/:3.2.3]
	at com.orientechnologies.orient.core.db.tool.ODatabaseImport.importDatabase(ODatabaseImport.java:542) ~[orientdb-core-3.2.3.jar!/:3.2.3]

It seems that because the value has dot it gets treated like a double ?!

**Comment by florian-stoica** [comment]
The root cause seems to be in ODatabaseImport L2235 that parsing fails. As a workaround, I've overridden ODatabaseExport and set EXPORTER_VERSION to 12 so it goes the other way, and like this the import is successful
