### ISSUE TITLE
Unable to open DB created by same version of Orient

### ISSUE THREAD

**Issue by florian-stoica** [orientechnologies/orientdb#9743]
## Expected behavior  
Open database created on the same version of orient

## Actual behavior  
Crashes with:
com.orientechnologies.orient.core.exception.OStorageException: Database has been opened at version 3.2.3 (build dc98198215aa57baf29b32adb657dc3733acdb55, branch UNKNOWN) but is attempted to be restored at version 3.2.3 (build dc98198215aa57baf29b32adb657dc3733acdb55, branch develop). Please use correct version to restore database.
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.recoverIfNeeded(OAbstractPaginatedStorage.java:5233)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.open(OAbstractPaginatedStorage.java:328)
	at com.orientechnologies.orient.core.db.OrientDBEmbedded.getAndOpenStorage(OrientDBEmbedded.java:522)
	at com.orientechnologies.orient.core.db.OrientDBEmbedded.open(OrientDBEmbedded.java:473)
	at com.orientechnologies.orient.core.db.OrientDBDistributed.open(OrientDBDistributed.java:252)
	at com.orientechnologies.orient.core.db.OrientDBEmbedded.open(OrientDBEmbedded.java:413)
	at com.orientechnologies.orient.core.db.OrientDBDistributed.open(OrientDBDistributed.java:237)
	at com.orientechnologies.orient.server.OServer.openDatabase(OServer.java:842)

IMO the check from OAbstractPaginatedStorage L5228 should compare version + revision rather than the whole to string value of the version that also includes the branch name. Although revision HASH alone should ensure correct version.

**Comment by andrii0lomakin** [comment]
Hi @florian-stoica , the version in OrientDB includes also the branch from which it was created. You use two different builds. Once was build form UNKNOWN branch and other one from develop branch.

**Comment by andrii0lomakin** [comment]
But I suppose you are right, it should include hash alone.

**Comment by chaudharisuresh997** [comment]
this issue is recreated at version 3.2.9 we promoted from 3.2.8 to 3.2.9

**Comment by tglman** [comment]
Hi,

yes this check is still active in all the version of OrientDB, if you try to open a database that need to run a recover from WAL procedure, it will fail to open if opened with a version that is not  exactly the same of when it was opened last time, to recover from this situation you just need to open the database with the original version and wait the recover from WAL to finish, shutdown safely the instance and then you can open the database with subsequent versions.

Regards
