### ISSUE TITLE
OStorageException when truncating a class

### ISSUE THREAD

**Issue by diegomtassis** [orientechnologies/orientdb#9746]
### OrientDB Version: 3.0.41

I have a utility class with a method which truncates all the user data from a database.

This is the method. I have tried 2 different approaches and both fail.

```
    public static final void truncate(ODatabase<?> database) {

        LOGGER.info("Truncating database: {}", database.getURL());
        database.getMetadata().getSchema().getClasses().stream()
                .filter(oClass -> !oClass.getName().startsWith(ORIENTDB_CLASS_PREFIX)) //
                .forEach(oClass -> {
                    try {
                        oClass.truncate();
                    } catch (IOException e) {
                        LOGGER.info("Error truncating class", e);
                    }
                });
    }
```

```
    public static final void truncate(ODatabase<?> database) {

        LOGGER.info("Truncating database: {}", database.getURL());
        database.getMetadata().getSchema().getClasses().stream()
                .filter(oClass -> !oClass.getName().startsWith(ORIENTDB_CLASS_PREFIX)) //
                .forEach(oClass -> {
                    try {
                        database.command(new OCommandSQL("TRUNCATE CLASS " + oClass.getName() + " POLYMORPHIC UNSAFE"))
                                .execute();
                    } catch (OStorageException e) {
                        LOGGER.info("Error truncating class", e);
                    }
                });
    }
```
And this is the error I get:
```
    com.orientechnologies.orient.core.exception.OStorageException: Cluster id '-1' is outside the of range of configured clusters (0-56) in database 'TruncateTest'
    DB name="TruncateTest"
    at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.checkClusterId(OAbstractPaginatedStorage.java:953)
    at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.getClusterNameById(OAbstractPaginatedStorage.java:969)
    at com.orientechnologies.orient.core.metadata.schema.OClassImpl.truncate(OClassImpl.java:860)
```

**Comment by tglman** [comment]
Hi, 

This looks like there is a class in the schema that has a wrong definition, in the meaning that it contains in the list of clusters the cluster with the `-1` id  that means that is an undefined cluster.

So the problem does not seems to be related to the truncate itself, but to something ahead that allowed to create a wrong definition.

Could you share the schema of the specific class, or describe a lit of steps that brought to the wrong schema ?

Bye
