### ISSUE TITLE
while Migration of db , inserting the Vertex gettign error Cannot get by real bag size sb-tree bonsai

### ISSUE THREAD

**Issue by veeralok1** [orientechnologies/orientdb#9757]
## Expected behavior  
In should create the vertex to the target db  

## Actual behavior  
Getting error : Caused by: com.orientechnologies.orient.core.exception.OStorageException: Cannot get by real bag size sb-tree bonsai
```
[ERROR] 2022-01-27 11:04:15.812 [pool-49-thread-1] AsyncDataMigrationService - something went wrong while pushing data to cloudleaf for cluster:category_8068c968_b761_450f_a4c9_be0b2a546cf5 vertex id ::97f16023-f6db-470e-85e4-d5f226053821
com.orientechnologies.orient.core.exception.ODatabaseException: Error during saving of record with rid #-1:-1
	DB name="cloudleafdemo"
	at com.orientechnologies.orient.core.tx.OTransactionNoTx.saveRecord(OTransactionNoTx.java:206) ~[orientdb-core-3.0.31.jar:3.0.31]
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentAbstract.saveInternal(ODatabaseDocumentAbstract.java:2077) ~[orientdb-core-3.0.31.jar:3.0.31]
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentAbstract.save(ODatabaseDocumentAbstract.java:2039) ~[orientdb-core-3.0.31.jar:3.0.31]
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentAbstract.save(ODatabaseDocumentAbstract.java:86) ~[orientdb-core-3.0.31.jar:3.0.31]
	at com.orientechnologies.orient.core.record.impl.ODocument.save(ODocument.java:2178) ~[orientdb-core-3.0.31.jar:3.0.31]
	at com.orientechnologies.orient.core.record.impl.ODocument.save(ODocument.java:2169) ~[orientdb-core-3.0.31.jar:3.0.31]
	at com.orientechnologies.orient.core.record.impl.ODocument.save(ODocument.java:120) ~[orientdb-core-3.0.31.jar:3.0.31]
	at com.cloudleaf.cloudos.graphapp.service.AsyncDataMigrationService.pushData(AsyncDataMigrationService.java:226) [classes/:?]
	at com.cloudleaf.cloudos.graphapp.service.AsyncDataMigrationService.access$200(AsyncDataMigrationService.java:40) [classes/:?]
	at com.cloudleaf.cloudos.graphapp.service.AsyncDataMigrationService$PullAndPushData.run(AsyncDataMigrationService.java:410) [classes/:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_261]
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266) [?:1.8.0_261]
	at java.util.concurrent.FutureTask.run(FutureTask.java) [?:1.8.0_261]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_261]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_261]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_261]
Caused by: com.orientechnologies.orient.core.exception.OStorageException: Cannot get by real bag size sb-tree bonsai
	DB name="cloudleafdemo"
	at com.orientechnologies.orient.client.remote.OStorageRemote.baseNetworkOperation(OStorageRemote.java:366) ~[orientdb-client-3.0.31.jar:3.0.31]
	at com.orientechnologies.orient.client.remote.OStorageRemote.networkOperationRetryTimeout(OStorageRemote.java:228) ~[orientdb-client-3.0.31.jar:3.0.31]
	at com.orientechnologies.orient.client.remote.OStorageRemote.networkOperation(OStorageRemote.java:265) ~[orientdb-client-3.0.31.jar:3.0.31]
	at com.orientechnologies.orient.client.remote.OSBTreeBonsaiRemote.getRealBagSize(OSBTreeBonsaiRemote.java:203) ~[orientdb-client-3.0.31.jar:3.0.31]
	at com.orientechnologies.orient.core.storage.ridbag.sbtree.OSBTreeRidBag.updateSize(OSBTreeRidBag.java:947) ~[orientdb-core-3.0.31.jar:3.0.31]
	at com.orientechnologies.orient.core.storage.ridbag.sbtree.OSBTreeRidBag.size(OSBTreeRidBag.java:624) ~[orientdb-core-3.0.31.jar:3.0.31]
	at com.orientechnologies.orient.core.db.record.ridbag.ORidBag.size(ORidBag.java:202) ~[orientdb-core-3.0.31.jar:3.0.31]
	at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerNetworkV37.writeRidBag(ORecordSerializerNetworkV37.java:346) ~[orientdb-core-3.0.31.jar:3.0.31]
	at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerNetworkV37.serializeValue(ORecordSerializerNetworkV37.java:606) ~[orientdb-core-3.0.31.jar:3.0.31]
	at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerNetworkV37.serialize(ORecordSerializerNetworkV37.java:157) ~[orientdb-core-3.0.31.jar:3.0.31]
	at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerNetworkV37.toStream(ORecordSerializerNetworkV37.java:881) ~[orientdb-core-3.0.31.jar:3.0.31]
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentRemote.executeSaveRecord(ODatabaseDocumentRemote.java:590) ~[orientdb-client-3.0.31.jar:3.0.31]
	at com.orientechnologies.orient.core.tx.OTransactionNoTx.saveNew(OTransactionNoTx.java:244) ~[orientdb-core-3.0.31.jar:3.0.31]
	at com.orientechnologies.orient.core.tx.OTransactionNoTx.saveRecord(OTransactionNoTx.java:174) ~[orientdb-core-3.0.31.jar:3.0.31]
	... 15 more
Caused by: java.lang.NullPointerException
	at com.orientechnologies.orient.core.storage.ridbag.sbtree.OSBTreeCollectionManagerAbstract.releaseSBTree(OSBTreeCollectionManagerAbstract.java:221) ~[orientdb-core-3.0.31.jar:3.0.31]
	at com.orientechnologies.orient.server.OConnectionBinaryExecutor.executeSBTGetRealSize(OConnectionBinaryExecutor.java:1139) ~[orientdb-server-3.0.31.jar:3.0.31]
	at com.orientechnologies.orient.client.remote.message.OSBTGetRealBagSizeRequest.execute(OSBTGetRealBagSizeRequest.java:102) ~[orientdb-client-3.0.31.jar:3.0.31]
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.sessionRequest(ONetworkProtocolBinary.java:355) ~[orientdb-server-3.0.31.jar:3.0.31]
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.execute(ONetworkProtocolBinary.java:239) ~[orientdb-server-3.0.31.jar:3.0.31]
	at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:67) ~[orientdb-core-3.0.31.jar:3.0.31]
[ERROR] 2022-01-27 11:04:15.864 [pool-49-thread-1] AsyncDataMigrationService - something went wrong while pushing data to cloudleaf for cluster:category_8068c968_b761_450f_a4c9_be0b2a546cf5 vertex id ::65bee74e-4935-467b-9c00-e2a88caefd75
com.orientechnologies.orient.core.exception.ODatabaseException: Error during saving of record with rid #-1:-1
	DB name="cloudleafdemo"
	at com.orientechnologies.orient.core.tx.OTransactionNoTx.saveRecord(OTransactionNoTx.java:206) ~[orientdb-core-3.0.31.jar:3.0.31]
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentAbstract.saveInternal(ODatabaseDocumentAbstract.java:2077) ~[orientdb-core-3.0.31.jar:3.0.31]
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentAbstract.save(ODatabaseDocumentAbstract.java:2039) ~[orientdb-core-3.0.31.jar:3.0.31]
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentAbstract.save(ODatabaseDocumentAbstract.java:86) ~[orientdb-core-3.0.31.jar:3.0.31]
	at com.orientechnologies.orient.core.record.impl.ODocument.save(ODocument.java:2178) ~[orientdb-core-3.0.31.jar:3.0.31]
	at com.orientechnologies.orient.core.record.impl.ODocument.save(ODocument.java:2169) ~[orientdb-core-3.0.31.jar:3.0.31]
	at com.orientechnologies.orient.core.record.impl.ODocument.save(ODocument.java:120) ~[orientdb-core-3.0.31.jar:3.0.31]
	at com.cloudleaf.cloudos.graphapp.service.AsyncDataMigrationService.pushData(AsyncDataMigrationService.java:226) [classes/:?]
	at com.cloudleaf.cloudos.graphapp.service.AsyncDataMigrationService.access$200(AsyncDataMigrationService.java:40) [classes/:?]
	at com.cloudleaf.cloudos.graphapp.service.AsyncDataMigrationService$PullAndPushData.run(AsyncDataMigrationService.java:410) [classes/:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_261]
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266) [?:1.8.0_261]
	at java.util.concurrent.FutureTask.run(FutureTask.java) [?:1.8.0_261]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_261]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_261]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_261]

```
## Steps to reproduce  
<add here>  
<An SQL script to reproduce the problem or a JUnit test case will increase **A LOT** the chance to have a quick fix>

**Comment by tglman** [comment]
Hi,

I've seen this error in the past and should be already fixed, could you try a more recent version of OrientDB?

Regards
