### ISSUE TITLE
Found null entry in ridbag with rid=#29:-1

### ISSUE THREAD

**Issue by adriancoca** [orientechnologies/orientdb#9767]
### OS: Windows server 2019

When i try to link two nodes from OrientDB studio the next error appear that crash Orient.

Internal error happened in storage production please restart the server or re-open the storage to undergo the restore process and fix the error.
DB name="production"

2022-03-01 14:03:22:765 SEVER {db=production} Found null entry in ridbag with rid=#29:-1 [ORecordSerializerBinaryV1]Exception `4B0BDCBC` in storage `plocal:C:\orientdb-community-3.2.5\databases/production`: 3.2.5 (build c4298657c01683192ba0b7bfffdf82226c164506, branch UNKNOWN)
com.orientechnologies.orient.core.exception.OSerializationException: Found null entry in ridbag with rid=#29:-1
	DB name="production"
	at com.orientechnologies.orient.core.serialization.serializer.record.binary.HelperClasses.writeEmbeddedRidbag(HelperClasses.java:378)
	at com.orientechnologies.orient.core.serialization.serializer.record.binary.HelperClasses.writeRidBag(HelperClasses.java:354)
	at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinaryV1.writeRidBag(ORecordSerializerBinaryV1.java:731)
	at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinaryV1.serializeValue(ORecordSerializerBinaryV1.java:1020)
	at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinaryV1.serializeValues(ORecordSerializerBinaryV1.java:404)
	at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinaryV1.serializeDocument(ORecordSerializerBinaryV1.java:462)
	at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinaryV1.serialize(ORecordSerializerBinaryV1.java:483)
	at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinary.toStream(ORecordSerializerBinary.java:132)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.commitEntry(OAbstractPaginatedStorage.java:5946)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.commit(OAbstractPaginatedStorage.java:2367)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.commit(OAbstractPaginatedStorage.java:2190)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentEmbedded.internalCommit(ODatabaseDocumentEmbedded.java:1978)
	at com.orientechnologies.orient.core.tx.OTransactionOptimistic.doCommit(OTransactionOptimistic.java:621)
	at com.orientechnologies.orient.core.tx.OTransactionOptimistic.commit(OTransactionOptimistic.java:114)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentAbstract.commit(ODatabaseDocumentAbstract.java:1593)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentAbstract.commit(ODatabaseDocumentAbstract.java:1563)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentEmbedded.saveAll(ODatabaseDocumentEmbedded.java:1272)
	at com.orientechnologies.orient.core.tx.OTransactionNoTx.saveRecord(OTransactionNoTx.java:208)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentAbstract.saveInternal(ODatabaseDocumentAbstract.java:1484)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentAbstract.save(ODatabaseDocumentAbstract.java:1432)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentAbstract.save(ODatabaseDocumentAbstract.java:1315)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentAbstract.save(ODatabaseDocumentAbstract.java:78)
	at com.orientechnologies.orient.core.sql.executor.SaveElementStep$1.next(SaveElementStep.java:37)
	at com.orientechnologies.orient.core.sql.executor.OInsertExecutionPlan.executeInternal(OInsertExecutionPlan.java:46)
	at com.orientechnologies.orient.core.sql.parser.OCreateEdgeStatement.execute(OCreateEdgeStatement.java:59)
	at com.orientechnologies.orient.core.sql.parser.OStatement.execute(OStatement.java:72)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentEmbedded.command(ODatabaseDocumentEmbedded.java:633)
	at com.orientechnologies.orient.server.network.protocol.http.command.post.OServerCommandPostCommand.executeStatement(OServerCommandPostCommand.java:221)
	at com.orientechnologies.orient.server.network.protocol.http.command.post.OServerCommandPostCommand.execute(OServerCommandPostCommand.java:104)
	at com.orientechnologies.orient.server.network.protocol.http.command.post.OServerCommandPostCommandGraph.execute(OServerCommandPostCommandGraph.java:34)
	at com.orientechnologies.orient.server.network.protocol.http.ONetworkProtocolHttpAbstract.service(ONetworkProtocolHttpAbstract.java:242)
	at com.orientechnologies.orient.server.network.protocol.http.ONetworkProtocolHttpAbstract.execute(ONetworkProtocolHttpAbstract.java:800)
	at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:68)
$ANSI{green {db=production}} Error on transaction commit `4B0BDCBC`

**Comment by adriancoca** [comment]
![image](https://user-images.githubusercontent.com/7643185/156325365-9d94f741-090e-4975-a0f3-d31377623b28.png)

**Comment by adriancoca** [comment]
@laa any ideea regarding this problem, now i have a broken database

**Comment by simonebri** [comment]
Exactly same problem, with OpenJDK Runtime Environment (build 1.8.0_312-8u312-b07-0ubuntu1~20.04-b07) and Ubuntu 20.04.4 LTS (Focal Fossa) server

**Comment by adriancoca** [comment]
Wrong edge remain as info when selecting from user -> How can this info be removed ?  ![image](https://user-images.githubusercontent.com/7643185/167381982-2c19c537-fa5d-462f-90c9-9dc5a7bc43d5.png)

**Comment by tglman** [comment]
Hi,

for this problem I see that you are sending a query trough the http APIs, could you share the query with the relative parameters?

Regards

**Comment by adriancoca** [comment]
It's just a simple sql.

![image](https://user-images.githubusercontent.com/7643185/175282650-85687edf-dd92-423c-9371-530957d9e6a6.png)

**Comment by adriancoca** [comment]
trying to make a edge between the nodes gives null entry Orient 3.2.17 , all repair commands cannot fix this ...
![image](https://user-images.githubusercontent.com/7643185/229149341-5cd78089-9579-429e-a1ec-21711cef3085.png)

**Comment by tglman** [comment]
Hi,

I did change a bit the code to remove invalid links instead of fail, even though this invalid link should have been created by and write operation, I see that when reading your are getting there error, but maybe you have a way to identify a write operation that crate this issue.

Regards

**Comment by adriancoca** [comment]
It seems that next two lines can generate this problem, and one of User vertex goes in invalid state and I am unable to make new links to him. The solution is like a previously said to "clone" that User vertex and remake links with him. 

```
await orientService.executeCommand(company,`DELETE EDGE SUBORDER_OF WHERE out.username=:userUsername`, { userUsername: username });
    await orientService.executeCommand(company,`CREATE EDGE SUBORDER_OF FROM (SELECT * FROM User WHERE username=:userUsername) TO (SELECT * FROM User WHERE username=:parentUsername)`, { userUsername: user, parentUsername: parent});
```

I don't know what is wrong in above logic, maybe receiving some wrong params but in that case no link should be created.

I hope this can help you.
Thanks!

**Comment by tglman** [comment]
Hi,

The 3.2.18 has been released with fixes around this use case, feel free to verify if this is already solved also for you.

Regards
