### ISSUE TITLE
 Error on  connect plocal:../databases/...  - Can not calculate size of file 

### ISSUE THREAD

**Issue by adriancoca** [orientechnologies/orientdb#9768]
Connecting to database [plocal:../databases/production] with user 'root'...Exception `139982DE` in storage `plocal:C:\orientdb-community-3.2.5\bin\..\databases/production`: 3.2.5 (build c4298657c01683192ba0b7bfffdf82226c164506, branch UNKNOWN)
com.orientechnologies.orient.core.exception.OStorageException: Can not calculate size of file C:\orientdb-community-3.2.5\bin\..\databases\production\production_2.dwl
        at com.orientechnologies.orient.core.storage.cache.local.doublewritelog.DoubleWriteLogGL.lambda$calculateLogSize$4(DoubleWriteLogGL.java:295)
        at java.util.stream.ReferencePipeline$5$1.accept(ReferencePipeline.java:227)
        at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
        at java.util.Iterator.forEachRemaining(Iterator.java:116)
        at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.util.stream.LongPipeline.reduce(LongPipeline.java:439)
        at java.util.stream.LongPipeline.sum(LongPipeline.java:397)
        at com.orientechnologies.orient.core.storage.cache.local.doublewritelog.DoubleWriteLogGL.calculateLogSize(DoubleWriteLogGL.java:299)
        at com.orientechnologies.orient.core.storage.cache.local.doublewritelog.DoubleWriteLogGL.open(DoubleWriteLogGL.java:121)
        at com.orientechnologies.orient.core.storage.cache.local.OWOWCache.loadRegisteredFiles(OWOWCache.java:500)
        at com.orientechnologies.orient.core.storage.disk.OLocalPaginatedStorage.initWalAndDiskCache(OLocalPaginatedStorage.java:817)
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.open(OAbstractPaginatedStorage.java:300)
        at com.orientechnologies.orient.core.db.OrientDBEmbedded.getAndOpenStorage(OrientDBEmbedded.java:522)
        at com.orientechnologies.orient.core.db.OrientDBEmbedded.open(OrientDBEmbedded.java:473)
        at com.orientechnologies.orient.core.db.OrientDB.open(OrientDB.java:226)
        at com.orientechnologies.orient.core.db.OrientDB.open(OrientDB.java:212)
        at com.orientechnologies.orient.console.OConsoleDatabaseApp.connect(OConsoleDatabaseApp.java:261)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.orientechnologies.common.console.OConsoleApplication.execute(OConsoleApplication.java:456)
        at com.orientechnologies.common.console.OConsoleApplication.executeCommands(OConsoleApplication.java:283)
        at com.orientechnologies.common.console.OConsoleApplication.run(OConsoleApplication.java:144)
        at com.orientechnologies.orient.console.OConsoleDatabaseApp.main(OConsoleDatabaseApp.java:162)
Caused by: java.nio.file.AccessDeniedException: C:\orientdb-community-3.2.5\bin\..\databases\production\production_2.dwl
        at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:83)
        at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:97)
        at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:102)
        at sun.nio.fs.WindowsFileAttributeViews$Basic.readAttributes(WindowsFileAttributeViews.java:53)
        at sun.nio.fs.WindowsFileAttributeViews$Basic.readAttributes(WindowsFileAttributeViews.java:38)
        at sun.nio.fs.WindowsFileSystemProvider.readAttributes(WindowsFileSystemProvider.java:193)
        at java.nio.file.Files.readAttributes(Files.java:1737)
        at java.nio.file.Files.size(Files.java:2332)
        at com.orientechnologies.orient.core.storage.cache.local.doublewritelog.DoubleWriteLogGL.lambda$calculateLogSize$4(DoubleWriteLogGL.java:291)
        ... 28 more

Error: com.orientechnologies.orient.core.exception.ODatabaseException: Cannot open database 'production'

Error: com.orientechnologies.orient.core.exception.OStorageException: Can not calculate size of file C:\orientdb-community-3.2.5\bin\..\databases\production\production_2.dwl

Error: java.nio.file.AccessDeniedException: C:\orientdb-community-3.2.5\bin\..\databases\production\production_2.dwl

**Comment by andrii0lomakin** [comment]
Hi, you have no right to access the database by the system user which you use.
That is why you have got this exception.
