### ISSUE TITLE
Unable to access orientd database

### ISSUE THREAD

**Issue by sawantnitesh76ns** [orientechnologies/orientdb#9783]
## Expected behavior  
The application should be able to access the orientdb database but something is happend and because of that it is not able to access the database

## Actual behavior  
My orientdb database is down and because of that im unable to login on my website. I have also tried to login in database but it is showing an below error

```
Connecting to database ["remote:localhost/<database_name>"] with user '<user_name>'...
Error: com.orientechnologies.orient.core.exception.ODatabaseException: Cannot open database '<database_name>'

Error: com.orientechnologies.orient.core.exception.ODatabaseException: Cannot open database '<database_name>'

Error: com.orientechnologies.orient.core.exception.ODatabaseException: Error on retrieving record #0:1 (cluster: internal)
    DB name="<database_name>"

Error: com.orientechnologies.orient.core.exception.OPaginatedClusterException: Content of record #0:1 was broken
    DB name="<database_name>"
    Component Name="internal"
```

**Comment by andrii0lomakin** [comment]
Hi, could you share the full stack trace?

**Comment by andrii0lomakin** [comment]
Also, do you have logs from the database which we can check?

**Comment by sawantnitesh76ns** [comment]
Okay i will provide you the full stack trace and logs of that database

**Comment by sawantnitesh76ns** [comment]
Logs 
2022-04-11 09:53:48:620 INFO  OrientDB Server is active v3.0.27 - Veloce (build bc8f77600494cab71fb347d4c29f71c793442464, branch 3.0.x). [OServer]
2022-04-11 09:55:02:634 INFO  Direct IO for WAL located in /var/lib/orientdb-3.0.27/databases/databizurm is allowed with block size 4096 bytes. [OCASDiskWriteAheadLog]
2022-04-11 09:55:02:634 INFO  Page size for WAL located in /var/lib/orientdb-3.0.27/databases/databizurm is set to 4096 bytes. [OCASDiskWriteAheadLog]
2022-04-11 09:55:02:756 INFO  Storage 'plocal:/var/lib/orientdb-3.0.27/databases/databizurm' is opened under OrientDB distribution : 3.0.27 - Veloce (build bc8f77600494cab71fb347d4c29f71c793442464, branch 3.0.x) [OLocalPaginatedStorage]
2022-04-11 09:55:02:922 WARNI {db=databizurm} Token signature failure: AAAAAApkYXRhYml6dXJtAAAFAAAAAAAAAAMAAAGAGD/QtwAAJQAMb25ldF9zZXJfdjM3AAtKYXZhIENsaWVudABQMy4wLjI3IC0gVmVsb2NlIChidWlsZCBlNGU3M2U3NzA3NGM0ZjQ5MzM3YWU1OGIxNzE1MTNjZDEwYWMxMTU3LCBicmFuY2ggVU5LTk9XTikykHOElDNhh39Jy/bRW4A8MmM8/a6CM00ryNj/QdAY6Q== [OTokenHandlerImpl]
2022-04-11 09:55:03:179 INFO  Direct IO for WAL located in /var/lib/orientdb-3.0.27/databases/databiz is allowed with block size 4096 bytes. [OCASDiskWriteAheadLog]
2022-04-11 09:55:03:180 INFO  Page size for WAL located in /var/lib/orientdb-3.0.27/databases/databiz is set to 4096 bytes. [OCASDiskWriteAheadLog]Exception `5E0EBF2E` in storage `plocal:/var/lib/orientdb-3.0.27/databases/databiz`: 3.0.27 - Veloce (build bc8f77600494cab71fb347d4c29f71c793442464, branch 3.0.x)
java.lang.IllegalStateException: Invalid binary version of cluster 2
	at com.orientechnologies.orient.core.storage.impl.local.paginated.wal.OPaginatedClusterFactory.createCluster(OPaginatedClusterFactory.java:49)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.createClusterFromConfig(OAbstractPaginatedStorage.java:4752)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.openClusters(OAbstractPaginatedStorage.java:448)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.open(OAbstractPaginatedStorage.java:312)
	at com.orientechnologies.orient.core.db.OrientDBEmbedded.open(OrientDBEmbedded.java:283)
	at com.orientechnologies.orient.core.db.OrientDBEmbedded.open(OrientDBEmbedded.java:228)
	at com.orientechnologies.orient.server.OServer.openDatabase(OServer.java:939)
	at com.orientechnologies.orient.server.OServer.openDatabase(OServer.java:913)
	at com.orientechnologies.orient.server.OConnectionBinaryExecutor.executeDatabaseOpen37(OConnectionBinaryExecutor.java:1187)
	at com.orientechnologies.orient.client.remote.message.OOpen37Request.execute(OOpen37Request.java:77)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.sessionRequest(ONetworkProtocolBinary.java:310)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.execute(ONetworkProtocolBinary.java:212)
	at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:69)

2022-04-11 09:55:04:547 INFO  Direct IO for WAL located in /var/lib/orientdb-3.0.27/databases/databiz is allowed with block size 4096 bytes. [OCASDiskWriteAheadLog]
2022-04-11 09:55:04:548 INFO  Page size for WAL located in /var/lib/orientdb-3.0.27/databases/databiz is set to 4096 bytes. [OCASDiskWriteAheadLog]Exception `119DA7A4` in storage `plocal:/var/lib/orientdb-3.0.27/databases/databiz`: 3.0.27 - Veloce (build bc8f77600494cab71fb347d4c29f71c793442464, branch 3.0.x)
java.lang.IllegalStateException: Invalid binary version of cluster 2
	at com.orientechnologies.orient.core.storage.impl.local.paginated.wal.OPaginatedClusterFactory.createCluster(OPaginatedClusterFactory.java:49)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.createClusterFromConfig(OAbstractPaginatedStorage.java:4752)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.openClusters(OAbstractPaginatedStorage.java:448)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.open(OAbstractPaginatedStorage.java:312)
	at com.orientechnologies.orient.core.db.OrientDBEmbedded.open(OrientDBEmbedded.java:283)
	at com.orientechnologies.orient.core.db.OrientDBEmbedded.open(OrientDBEmbedded.java:228)
	at com.orientechnologies.orient.server.OServer.openDatabase(OServer.java:939)
	at com.orientechnologies.orient.server.OServer.openDatabase(OServer.java:913)
	at com.orientechnologies.orient.server.OConnectionBinaryExecutor.executeDatabaseOpen37(OConnectionBinaryExecutor.java:1187)
	at com.orientechnologies.orient.client.remote.message.OOpen37Request.execute(OOpen37Request.java:77)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.sessionRequest(ONetworkProtocolBinary.java:310)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.execute(ONetworkProtocolBinary.java:212)
	at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:69)

2022-04-11 09:55:05:387 INFO  Direct IO for WAL located in /var/lib/orientdb-3.0.27/databases/databiz is allowed with block size 4096 bytes. [OCASDiskWriteAheadLog]
2022-04-11 09:55:05:388 INFO  Page size for WAL located in /var/lib/orientdb-3.0.27/databases/databiz is set to 4096 bytes. [OCASDiskWriteAheadLog]Exception `371A2B73` in storage `plocal:/var/lib/orientdb-3.0.27/databases/databiz`: 3.0.27 - Veloce (build bc8f77600494cab71fb347d4c29f71c793442464, branch 3.0.x)
java.lang.IllegalStateException: Invalid binary version of cluster 2
	at com.orientechnologies.orient.core.storage.impl.local.paginated.wal.OPaginatedClusterFactory.createCluster(OPaginatedClusterFactory.java:49)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.createClusterFromConfig(OAbstractPaginatedStorage.java:4752)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.openClusters(OAbstractPaginatedStorage.java:448)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.open(OAbstractPaginatedStorage.java:312)
	at com.orientechnologies.orient.core.db.OrientDBEmbedded.open(OrientDBEmbedded.java:283)
	at com.orientechnologies.orient.core.db.OrientDBEmbedded.open(OrientDBEmbedded.java:228)
	at com.orientechnologies.orient.server.OServer.openDatabase(OServer.java:939)
	at com.orientechnologies.orient.server.OServer.openDatabase(OServer.java:913)
	at com.orientechnologies.orient.server.OConnectionBinaryExecutor.executeDatabaseOpen37(OConnectionBinaryExecutor.java:1187)
	at com.orientechnologies.orient.client.remote.message.OOpen37Request.execute(OOpen37Request.java:77)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.sessionRequest(ONetworkProtocolBinary.java:310)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.execute(ONetworkProtocolBinary.java:212)
	at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:69)

2022-04-11 09:55:06:176 INFO  Direct IO for WAL located in /var/lib/orientdb-3.0.27/databases/databiz is allowed with block size 4096 bytes. [OCASDiskWriteAheadLog]
2022-04-11 09:55:06:176 INFO  Page size for WAL located in /var/lib/orientdb-3.0.27/databases/databiz is set to 4096 bytes. [OCASDiskWriteAheadLog]Exception `5857BE01` in storage `plocal:/var/lib/orientdb-3.0.27/databases/databiz`: 3.0.27 - Veloce (build bc8f77600494cab71fb347d4c29f71c793442464, branch 3.0.x)
java.lang.IllegalStateException: Invalid binary version of cluster 2
	at com.orientechnologies.orient.core.storage.impl.local.paginated.wal.OPaginatedClusterFactory.createCluster(OPaginatedClusterFactory.java:49)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.createClusterFromConfig(OAbstractPaginatedStorage.java:4752)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.openClusters(OAbstractPaginatedStorage.java:448)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.open(OAbstractPaginatedStorage.java:312)
	at com.orientechnologies.orient.core.db.OrientDBEmbedded.open(OrientDBEmbedded.java:283)
	at com.orientechnologies.orient.core.db.OrientDBEmbedded.open(OrientDBEmbedded.java:228)
	at com.orientechnologies.orient.server.OServer.openDatabase(OServer.java:939)
	at com.orientechnologies.orient.server.OServer.openDatabase(OServer.java:913)
	at com.orientechnologies.orient.server.OConnectionBinaryExecutor.executeDatabaseOpen37(OConnectionBinaryExecutor.java:1187)
	at com.orientechnologies.orient.client.remote.message.OOpen37Request.execute(OOpen37Request.java:77)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.sessionRequest(ONetworkProtocolBinary.java:310)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.execute(ONetworkProtocolBinary.java:212)
	at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:69)

2022-04-11 09:55:06:985 INFO  Direct IO for WAL located in /var/lib/orientdb-3.0.27/databases/databiz is allowed with block size 4096 bytes. [OCASDiskWriteAheadLog]
2022-04-11 09:55:06:985 INFO  Page size for WAL located in /var/lib/orientdb-3.0.27/databases/databiz is set to 4096 bytes. [OCASDiskWriteAheadLog]Exception `6E40B750` in storage `plocal:/var/lib/orientdb-3.0.27/databases/databiz`: 3.0.27 - Veloce (build bc8f77600494cab71fb347d4c29f71c793442464, branch 3.0.x)
java.lang.IllegalStateException: Invalid binary version of cluster 2
	at com.orientechnologies.orient.core.storage.impl.local.paginated.wal.OPaginatedClusterFactory.createCluster(OPaginatedClusterFactory.java:49)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.createClusterFromConfig(OAbstractPaginatedStorage.java:4752)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.openClusters(OAbstractPaginatedStorage.java:448)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.open(OAbstractPaginatedStorage.java:312)
	at com.orientechnologies.orient.core.db.OrientDBEmbedded.open(OrientDBEmbedded.java:283)
	at com.orientechnologies.orient.core.db.OrientDBEmbedded.open(OrientDBEmbedded.java:228)
	at com.orientechnologies.orient.server.OServer.openDatabase(OServer.java:939)
	at com.orientechnologies.orient.server.OServer.openDatabase(OServer.java:913)
	at com.orientechnologies.orient.server.OConnectionBinaryExecutor.executeDatabaseOpen37(OConnectionBinaryExecutor.java:1187)
	at com.orientechnologies.orient.client.remote.message.OOpen37Request.execute(OOpen37Request.java:77)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.sessionRequest(ONetworkProtocolBinary.java:310)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.execute(ONetworkProtocolBinary.java:212)
	at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:69)

2022-04-11 09:55:07:912 INFO  Direct IO for WAL located in /var/lib/orientdb-3.0.27/databases/databiz is allowed with block size 4096 bytes. [OCASDiskWriteAheadLog]
2022-04-11 09:55:07:913 INFO  Page size for WAL located in /var/lib/orientdb-3.0.27/databases/databiz is set to 4096 bytes. [OCASDiskWriteAheadLog]Exception `3E875E31` in storage `plocal:/var/lib/orientdb-3.0.27/databases/databiz`: 3.0.27 - Veloce (build bc8f77600494cab71fb347d4c29f71c793442464, branch 3.0.x)
java.lang.IllegalStateException: Invalid binary version of cluster 2
	at com.orientechnologies.orient.core.storage.impl.local.paginated.wal.OPaginatedClusterFactory.createCluster(OPaginatedClusterFactory.java:49)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.createClusterFromConfig(OAbstractPaginatedStorage.java:4752)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.openClusters(OAbstractPaginatedStorage.java:448)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.open(OAbstractPaginatedStorage.java:312)
	at com.orientechnologies.orient.core.db.OrientDBEmbedded.open(OrientDBEmbedded.java:283)
	at com.orientechnologies.orient.core.db.OrientDBEmbedded.open(OrientDBEmbedded.java:228)
	at com.orientechnologies.orient.server.OServer.openDatabase(OServer.java:939)
	at com.orientechnologies.orient.server.OServer.openDatabase(OServer.java:913)
	at com.orientechnologies.orient.server.OConnectionBinaryExecutor.executeDatabaseOpen37(OConnectionBinaryExecutor.java:1187)
	at com.orientechnologies.orient.client.remote.message.OOpen37Request.execute(OOpen37Request.java:77)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.sessionRequest(ONetworkProtocolBinary.java:310)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.execute(ONetworkProtocolBinary.java:212)
	at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:69)

**Comment by andrii0lomakin** [comment]
From what I see you opened a database created by a newer version using an older implementation. Such an approach is not supported.

**Comment by sawantnitesh76ns** [comment]
Yes i got these latter by debugging it more. Thanks for the help.
