### ISSUE TITLE
NPE on non unique index storage when deleting rows

### ISSUE THREAD

**Issue by boddissattva** [orientechnologies/orientdb#9803]
Hello,

We had the following error on one of our server instance and be very pleased to be given a hint about the problem.

To be noted : 
* This happens once and cannot be reproduced.
* The database is very small.
* The deletion is not in an explicit transaction.
* After a restart, everthing seems fine.

## Actual behavior  
`Caused by: com.orientechnologies.orient.core.exception.OStorageException: Exception during execution of component operation inside component idx_DataSetHistory_dataSetId.irs in storage chutney_component_db
DB name="chutney_component_db"
at com.orientechnologies.orient.core.storage.impl.local.paginated.atomicoperations.OAtomicOperationsManager.executeInsideComponentOperation(OAtomicOperationsManager.java:181)
at com.orientechnologies.orient.core.storage.impl.local.paginated.atomicoperations.OAtomicOperationsManager.executeInsideComponentOperation(OAtomicOperationsManager.java:166)
at com.orientechnologies.orient.core.storage.impl.local.paginated.base.ODurableComponent.executeInsideComponentOperation(ODurableComponent.java:102)
at com.orientechnologies.orient.core.storage.index.sbtreebonsai.local.OSBTreeBonsaiLocal.create(OSBTreeBonsaiLocal.java:111)
at com.orientechnologies.orient.core.storage.ridbag.sbtree.OIndexRIDContainerSBTree.<init>(OIndexRIDContainerSBTree.java:82)
at com.orientechnologies.orient.core.storage.ridbag.sbtree.OMixedIndexRIDContainer.delete(OMixedIndexRIDContainer.java:316)
at com.orientechnologies.orient.core.index.OIndexMultiValues$EntityRemover.update(OIndexMultiValues.java:530)
at com.orientechnologies.orient.core.sharding.auto.OAutoShardingIndexEngine.update(OAutoShardingIndexEngine.java:323)
at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.doUpdateIndexEntry(OAbstractPaginatedStorage.java:3294)
at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.updateIndexEntry(OAbstractPaginatedStorage.java:3211)
at com.orientechnologies.orient.core.index.OIndexMultiValues.doRemoveV0(OIndexMultiValues.java:277)
at com.orientechnologies.orient.core.index.OIndexMultiValues.doRemove(OIndexMultiValues.java:252)
at com.orientechnologies.orient.core.index.OIndexAbstractDelegate.doRemove(OIndexAbstractDelegate.java:442)
at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.applyTxChanges(OAbstractPaginatedStorage.java:2476)
at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.commitIndexes(OAbstractPaginatedStorage.java:2457)
at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.commit(OAbstractPaginatedStorage.java:2374)
at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.commit(OAbstractPaginatedStorage.java:2188)
at com.orientechnologies.orient.core.db.document.ODatabaseDocumentEmbedded.internalCommit(ODatabaseDocumentEmbedded.java:2078)
at com.orientechnologies.orient.core.tx.OTransactionOptimistic.doCommit(OTransactionOptimistic.java:591)
at com.orientechnologies.orient.core.tx.OTransactionOptimistic.commit(OTransactionOptimistic.java:110)
at com.orientechnologies.orient.core.db.document.ODatabaseDocumentAbstract.commit(ODatabaseDocumentAbstract.java:1555)
at com.orientechnologies.orient.core.db.document.ODatabaseDocumentAbstract.commit(ODatabaseDocumentAbstract.java:1525)
at com.orientechnologies.orient.core.db.document.ODatabaseDocumentEmbedded.executeDeleteRecord(ODatabaseDocumentEmbedded.java:879)
at com.orientechnologies.orient.core.tx.OTransactionNoTx.deleteRecord(OTransactionNoTx.java:172)
at com.orientechnologies.orient.core.db.document.ODatabaseDocumentEmbedded.delete(ODatabaseDocumentEmbedded.java:1042)
at com.orientechnologies.orient.core.db.document.ODatabaseDocumentEmbedded.delete(ODatabaseDocumentEmbedded.java:92)
at com.orientechnologies.orient.core.record.ORecordAbstract.delete(ORecordAbstract.java:297)
at com.orientechnologies.orient.core.record.ORecordAbstract.delete(ORecordAbstract.java:44)
at com.orientechnologies.orient.core.sql.executor.DeleteStep$1.next(DeleteStep.java:35)
at com.orientechnologies.orient.core.sql.executor.CountStep.syncPull(CountStep.java:52)
at com.orientechnologies.orient.core.sql.executor.OSelectExecutionPlan.fetchNext(OSelectExecutionPlan.java:34)
at com.orientechnologies.orient.core.sql.executor.OUpdateExecutionPlan.executeInternal(OUpdateExecutionPlan.java:41)
at com.orientechnologies.orient.core.sql.parser.ODeleteStatement.execute(ODeleteStatement.java:127)
at com.orientechnologies.orient.core.sql.parser.OStatement.execute(OStatement.java:72)
at com.orientechnologies.orient.core.db.document.ODatabaseDocumentEmbedded.command(ODatabaseDocumentEmbedded.java:633)
at com.chutneytesting.design.infra.storage.dataset.OrientDataSetHistoryRepository.removeHistory(OrientDataSetHistoryRepository.java:182)
at com.chutneytesting.design.infra.storage.dataset.OrientDataSetHistoryRepository$$FastClassBySpringCGLIB$$fa0e29b3.invoke(<generated>)
at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:771)
at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:749)
at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:139)
at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:749)
at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:691)
at com.chutneytesting.design.infra.storage.dataset.OrientDataSetHistoryRepository$$EnhancerBySpringCGLIB$$57a504d7.removeHistory(<generated>)
at com.chutneytesting.design.api.dataset.DataSetController.deleteById(DataSetController.java:84)
at com.chutneytesting.design.api.dataset.DataSetController$$FastClassBySpringCGLIB$$2786c89.invoke(<generated>)
at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:771)
at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:749)
at org.springframework.security.access.intercept.aopalliance.MethodSecurityInterceptor.invoke(MethodSecurityInterceptor.java:69)
at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:749)
at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:691)
at com.chutneytesting.design.api.dataset.DataSetController$$EnhancerBySpringCGLIB$$188d2c54.deleteById(<generated>)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:190)
at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:138)
at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:105)
at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:878)
at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:792)
at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1040)
at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:943)
at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)
at org.springframework.web.servlet.FrameworkServlet.doDelete(FrameworkServlet.java:931)
at javax.servlet.http.HttpServlet.service(HttpServlet.java:523)
... 91 common frames omitted
Caused by: java.lang.NullPointerException: null
at com.orientechnologies.orient.core.storage.impl.local.paginated.atomicoperations.OAtomicOperationBinaryTracking.releasePageFromWrite(OAtomicOperationBinaryTracking.java:278)
at com.orientechnologies.orient.core.storage.impl.local.paginated.base.ODurableComponent.releasePageFromWrite(ODurableComponent.java:172)
at com.orientechnologies.orient.core.storage.index.sbtreebonsai.local.OSBTreeBonsaiLocal.allocateBucketForWrite(OSBTreeBonsaiLocal.java:1660)
at com.orientechnologies.orient.core.storage.index.sbtreebonsai.local.OSBTreeBonsaiLocal.initAfterCreate(OSBTreeBonsaiLocal.java:170)
at com.orientechnologies.orient.core.storage.index.sbtreebonsai.local.OSBTreeBonsaiLocal.lambda$create$1(OSBTreeBonsaiLocal.java:126)
at com.orientechnologies.orient.core.storage.impl.local.paginated.atomicoperations.OAtomicOperationsManager.executeInsideComponentOperation(OAtomicOperationsManager.java:174)
... 162 common frames omitted`

## Steps to reproduce  
Can't reproduce it in Junit test after many tries.

**Comment by andrii0lomakin** [comment]
Hi,
Did you use the database from the previous version?

**Comment by boddissattva** [comment]
After check, yes we use on this instance the previous version 3.2.4 for some time.

**Comment by tglman** [comment]
Hi,

Could you try the latest 3.2.7, we fixed quite a few errors around the storage operations.

Regards

**Comment by tglman** [comment]
Hi, 
This should be for sure fixed in 3.2.9.

Regard
