### ISSUE TITLE
Database repair Error during processing of edge with id

### ISSUE THREAD

**Issue by adriancoca** [orientechnologies/orientdb#9806]
### Java Version: 8

.1250000 edges were processed out of 1356891
.Error during processing of edge with id #201:4347
java.lang.NullPointerException
        at com.orientechnologies.orient.core.db.tool.OBonsaiTreeRepair.repairDatabaseRidbags(OBonsaiTreeRepair.java:54)
        at com.orientechnologies.orient.console.OConsoleDatabaseApp.repairDatabase(OConsoleDatabaseApp.java:1986)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.orientechnologies.common.console.OConsoleApplication.execute(OConsoleApplication.java:451)
        at com.orientechnologies.common.console.OConsoleApplication.executeCommands(OConsoleApplication.java:287)
        at com.orientechnologies.common.console.OConsoleApplication.run(OConsoleApplication.java:142)
        at com.orientechnologies.orient.console.OConsoleDatabaseApp.main(OConsoleDatabaseApp.java:128)
1251000 edges were processed out of 1356891
.1252000 edges were processed out of 1356891
.1253000 edges were processed out of 1356891
.1254000 edges were processed out of 1356891
.1255000 edges were processed out of 1356891
.Error during processing of edge with id #202:4467
java.lang.NullPointerException
        at com.orientechnologies.orient.core.db.tool.OBonsaiTreeRepair.repairDatabaseRidbags(OBonsaiTreeRepair.java:54)
        at com.orientechnologies.orient.console.OConsoleDatabaseApp.repairDatabase(OConsoleDatabaseApp.java:1986)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.orientechnologies.common.console.OConsoleApplication.execute(OConsoleApplication.java:451)
        at com.orientechnologies.common.console.OConsoleApplication.executeCommands(OConsoleApplication.java:287)
        at com.orientechnologies.common.console.OConsoleApplication.run(OConsoleApplication.java:142)
        at com.orientechnologies.orient.console.OConsoleDatabaseApp.main(OConsoleDatabaseApp.java:128)

**Comment by tglman** [comment]
Hi,

A fix for this has been release in 3.2.7.

Regards

**Comment by adriancoca** [comment]
Hello, I tried again with that database backup restored in orient 3.2.7. That error doesn't appear anymore, but I still have another problem I am not sure if it is related with this https://github.com/orientechnologies/orientdb/issues/9767 . In that case it seems that the vertex may be broken the solution was to "clone" that node and remake all links with the new vertex. I am closing this issue because the reported problem seems to be resolved. Thanks!
