### ISSUE TITLE
java.lang.OutOfMemoryError while executing SQL query

### ISSUE THREAD

**Issue by amlbor** [orientechnologies/orientdb#9808]
## Expected behavior  
SQL query should execute successfully and return results. The query contains multiple AND-OR conditions.

`SELECT FROM TestClass WHERE (((Property1 is null) or (Property1 = #107:150)) and ((Property2 is null) or (Property2 = #107:150)) and ((Property3 is null) or (Property3 = #107:150)) and ((Property4 is null) or (Property4 = #107:150)) and ((Property5 is null) or (Property5 = #107:150)) and ((Property6 is null) or (Property6 = #107:150)) and ((Property7 is null) or (Property7 = #107:150)) and ((Property8 is null) or (Property8 = #107:150)) and ((Property9 is null) or (Property9 = #107:150)) and ((Property10 is null) or (Property10 = #107:150)) and ((Property11 is null) or (Property11 = #107:150)) and ((Property12 is null) or (Property12 = #107:150)) and ((Property13 is null) or (Property13 = #107:150)) and ((Property14 is null) or (Property14 = #107:150)) and ((Property15 is null) or (Property15 = #107:150)) and ((Property16 is null) or (Property16 = #107:150)) and ((Property17 is null) or (Property17 = #107:150)))`   

## Actual behavior  
This query fails with following exception.
 ```
java.lang.OutOfMemoryError: GC overhead limit exceeded
        at com.orientechnologies.orient.core.sql.parser.OBaseExpression.copy(OBaseExpression.java:306)
        at com.orientechnologies.orient.core.sql.parser.OBaseExpression.copy(OBaseExpression.java:22)
        at com.orientechnologies.orient.core.sql.parser.OExpression.copy(OExpression.java:446)
        at com.orientechnologies.orient.core.sql.parser.OBinaryCondition.copy(OBinaryCondition.java:200)
        at com.orientechnologies.orient.core.sql.parser.OBinaryCondition.copy(OBinaryCondition.java:22)
        at com.orientechnologies.orient.core.sql.parser.OAndBlock.copy(OAndBlock.java:172)
        at com.orientechnologies.orient.core.sql.parser.OWhereClause.lambda$copy$0(OWhereClause.java:326)
        at com.orientechnologies.orient.core.sql.parser.OWhereClause$$Lambda$153/1923043570.apply(Unknown Source)
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
        at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:566)
        at com.orientechnologies.orient.core.sql.parser.OWhereClause.copy(OWhereClause.java:326)
        at com.orientechnologies.orient.core.sql.executor.OSelectExecutionPlanner.handleWhere(OSelectExecutionPlanner.java:1522)
        at com.orientechnologies.orient.core.sql.executor.OSelectExecutionPlanner.createExecutionPlan(OSelectExecutionPlanner.java:96)
        at com.orientechnologies.orient.core.sql.parser.OSelectStatement.createExecutionPlan(OSelectStatement.java:301)
        at com.orientechnologies.orient.core.sql.parser.OSelectStatement.execute(OSelectStatement.java:271)
        at com.orientechnologies.orient.core.sql.parser.OStatement.execute(OStatement.java:79)
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentEmbedded.command(ODatabaseDocumentEmbedded.java:567)
        at com.orientechnologies.orient.server.network.protocol.http.command.post.OServerCommandPostCommand.executeStatement(OServerCommandPostCommand.java:189)
        at com.orientechnologies.orient.server.network.protocol.http.command.post.OServerCommandPostCommand.execute(OServerCommandPostCommand.java:95)
        at com.orientechnologies.orient.server.network.protocol.http.command.post.OServerCommandPostCommandGraph.execute(OServerCommandPostCommandGraph.java:36)
        at com.orientechnologies.orient.server.network.protocol.http.ONetworkProtocolHttpAbstract.service(ONetworkProtocolHttpAbstract.java:228)     
        at com.orientechnologies.orient.server.network.protocol.http.ONetworkProtocolHttpAbstract.execute(ONetworkProtocolHttpAbstract.java:707)     
        at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:69)
```

## Steps to reproduce  

1. Run the orientdb/run it using docker image
2. Create Database
3. Add Class TestClass
4. Add 20 properties like Property1, Property2 etc
5. No need to add any records
6. Run the above query
7. Observe the console for error

NOTE: This issue does not reproduce if lesser number of properties used in where condition, I was able to run query successfully with 16 properties. However, performance was slower.

PFA exported file attached.
[AndOrQueryIssue.gz](https://github.com/orientechnologies/orientdb/files/8709277/AndOrQueryIssue.gz)

**Comment by vishalkumarmahato** [comment]
is this issue is Still open @tglman

**Comment by tglman** [comment]
Hi,

yes it is, we found the root cause of the problem, for better search of usable indexes we do flatten conditions for example if you have:
`a=1 and (b=2 or c=3)` we flatten it to `a=1 and b=2 or a=1 and c=3` as you see in a use case with a lot of conditions this become somewhat exponential.
We do not have a solution yet on this because opting out of the flatten would reduce the cases when we can use the index, so need to find the right balance on how to solve this.

Regards

**Comment by amlbor** [comment]
@tglman - is there any workaround till the issue is resolved?

**Comment by tglman** [comment]
Hi, 

A work around you could try is to split the query in a query and a subquery, so this will reduce the amount of conditions for each query and reduce the chances to send it in out of memory ex:

```
select * from (select * from A where a=1 and b=2) where c=1 and d=2
```

we are actively working to fix this problem anyway. 

Regards

**Comment by amlbor** [comment]
Hi @tglman - Any updates on this issue?

**Comment by amlbor** [comment]
Hi, Any updates on this issue?

**Comment by tglman** [comment]
Hi,

Recently there has been some work to reduce the memory usage of the query components, which should improve the situation, but the root problem of exponential creation of conditions is still there, the reason why this still exists, is that to find the best index, we need to flat down the conditions, and that do the exponential work, to remove that is needed another way to find the index, that's the hard part now.
