### ISSUE TITLE
Channel is closed 

### ISSUE THREAD

**Issue by veeralok1** [orientechnologies/orientdb#9811]
## Expected behavior  
I am running the orientDB cluster of 3 nodes with all master and writeQuram is All and ReadQuram is 1 .  It should save without any issue. 

## Actual behavior  

AS part of our migration work we are creating the Vertex in orient db with 10 threads and batch  of 20 . In my local we not facing any issue , but with same configuration when going in kubernetes deployment and connecting from local , getting the Read time out  followed by channel is closed followed by socket closed for some of the vertex while saving.  For small set of data is working well.

## Below is the error 
```
com.orientechnologies.orient.core.exception.ODatabaseException: Error during saving of record with rid #-1:-1
	DB name="cloudleaf"
	at com.orientechnologies.orient.core.tx.OTransactionNoTx.saveRecord(OTransactionNoTx.java:206) ~[orientdb-core-3.0.31.jar:3.0.31]
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentAbstract.saveInternal(ODatabaseDocumentAbstract.java:2077) ~[orientdb-core-3.0.31.jar:3.0.31]
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentAbstract.save(ODatabaseDocumentAbstract.java:2039) ~[orientdb-core-3.0.31.jar:3.0.31]
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentAbstract.save(ODatabaseDocumentAbstract.java:86) ~[orientdb-core-3.0.31.jar:3.0.31]
	at com.orientechnologies.orient.core.record.impl.ODocument.save(ODocument.java:2178) ~[orientdb-core-3.0.31.jar:3.0.31]
	at com.orientechnologies.orient.core.record.impl.ODocument.save(ODocument.java:2169) ~[orientdb-core-3.0.31.jar:3.0.31]
	at com.orientechnologies.orient.core.record.impl.ODocument.save(ODocument.java:120) ~[orientdb-core-3.0.31.jar:3.0.31]
	at com.cloudleaf.cloudos.graphapp.service.AsyncDataMigrationService.pushData(AsyncDataMigrationService.java:695) [classes/:?]
	at com.cloudleaf.cloudos.graphapp.service.AsyncDataMigrationService.access$200(AsyncDataMigrationService.java:45) [classes/:?]
	at com.cloudleaf.cloudos.graphapp.service.AsyncDataMigrationService$PullAndPushData.run(AsyncDataMigrationService.java:995) [classes/:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_322]
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266) [?:1.8.0_322]
	at java.util.concurrent.FutureTask.run(FutureTask.java) [?:1.8.0_322]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_322]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_322]
	at java.lang.Thread.run(Thread.java:750) [?:1.8.0_322]
Caused by: com.orientechnologies.common.io.OIOException: Read timed out
	at com.orientechnologies.orient.client.remote.OStorageRemote.baseNetworkOperation(OStorageRemote.java:351) ~[orientdb-client-3.0.31.jar:3.0.31]
	at com.orientechnologies.orient.client.remote.OStorageRemote.asyncNetworkOperationRetry(OStorageRemote.java:173) ~[orientdb-client-3.0.31.jar:3.0.31]
	at com.orientechnologies.orient.client.remote.OStorageRemote.asyncNetworkOperationNoRetry(OStorageRemote.java:161) ~[orientdb-client-3.0.31.jar:3.0.31]
	at com.orientechnologies.orient.client.remote.OStorageRemote.createRecord(OStorageRemote.java:618) ~[orientdb-client-3.0.31.jar:3.0.31]
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentRemote.executeSaveRecord(ODatabaseDocumentRemote.java:606) ~[orientdb-client-3.0.31.jar:3.0.31]
	at com.orientechnologies.orient.core.tx.OTransactionNoTx.saveNew(OTransactionNoTx.java:244) ~[orientdb-core-3.0.31.jar:3.0.31]
	at com.orientechnologies.orient.core.tx.OTransactionNoTx.saveRecord(OTransactionNoTx.java:174) ~[orientdb-core-3.0.31.jar:3.0.31]
	... 15 more
Caused by: java.net.SocketTimeoutException: Read timed out
	at java.net.SocketInputStream.socketRead0(Native Method) ~[?:1.8.0_322]
	at java.net.SocketInputStream.socketRead(SocketInputStream.java:116) ~[?:1.8.0_322]
	at java.net.SocketInputStream.read(SocketInputStream.java:171) ~[?:1.8.0_322]
	at java.net.SocketInputStream.read(SocketInputStream.java:141) ~[?:1.8.0_322]
	at java.io.BufferedInputStream.read1(BufferedInputStream.java:284) ~[?:1.8.0_322]
	at java.io.BufferedInputStream.read(BufferedInputStream.java:345) ~[?:1.8.0_322]
	at java.io.DataInputStream.readFully(DataInputStream.java:195) ~[?:1.8.0_322]
	at java.io.DataInputStream.readFully(DataInputStream.java:169) ~[?:1.8.0_322]
	at com.orientechnologies.orient.enterprise.channel.binary.OChannelBinary.readBytes(OChannelBinary.java:181) ~[orientdb-core-3.0.31.jar:3.0.31]
	at com.orientechnologies.orient.client.binary.OChannelBinaryAsynchClient.beginResponse(OChannelBinaryAsynchClient.java:191) ~[orientdb-client-3.0.31.jar:3.0.31]
	at com.orientechnologies.orient.client.binary.OChannelBinaryAsynchClient.beginResponse(OChannelBinaryAsynchClient.java:158) ~[orientdb-client-3.0.31.jar:3.0.31]
	at com.orientechnologies.orient.client.remote.OStorageRemote.beginResponse(OStorageRemote.java:1891) ~[orientdb-client-3.0.31.jar:3.0.31]
	at com.orientechnologies.orient.client.remote.OStorageRemote.lambda$asyncNetworkOperationRetry$1(OStorageRemote.java:190) ~[orientdb-client-3.0.31.jar:3.0.31]
	at com.orientechnologies.orient.client.remote.OStorageRemote.baseNetworkOperation(OStorageRemote.java:307) ~[orientdb-client-3.0.31.jar:3.0.31]
	at com.orientechnologies.orient.client.remote.OStorageRemote.asyncNetworkOperationRetry(OStorageRemote.java:173) ~[orientdb-client-3.0.31.jar:3.0.31]
	at com.orientechnologies.orient.client.remote.OStorageRemote.asyncNetworkOperationNoRetry(OStorageRemote.java:161) ~[orientdb-client-3.0.31.jar:3.0.31]
	at com.orientechnologies.orient.client.remote.OStorageRemote.createRecord(OStorageRemote.java:618) ~[orientdb-client-3.0.31.jar:3.0.31]
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentRemote.executeSaveRecord(ODatabaseDocumentRemote.java:606) ~[orientdb-client-3.0.31.jar:3.0.31]
	at com.orientechnologies.orient.core.tx.OTransactionNoTx.saveNew(OTransactionNoTx.java:244) ~[orientdb-core-3.0.31.jar:3.0.31]
	at com.orientechnologies.orient.core.tx.OTransactionNoTx.saveRecord(OTransactionNoTx.java:174) ~[orientdb-core-3.0.31.jar:3.0.31]
	... 15 more
[ERROR] 2022-05-19 17:07:30.519 [pool-16-thread-5] AsyncDataMigrationService - something went wrong while pushing data to cloudleaf for cluster:custodyasset_8068c968_b761_450f_a4c9_be0b2a546cf5 vertex id ::1c358a5b-a2e7-48d7-90e4-2596efdcc3ef
com.orientechnologies.orient.core.exception.ODatabaseException: Error during saving of record with rid #-1:-1
	DB name="cloudleaf"
	at com.orientechnologies.orient.core.tx.OTransactionNoTx.saveRecord(OTransactionNoTx.java:206) ~[orientdb-core-3.0.31.jar:3.0.31]
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentAbstract.saveInternal(ODatabaseDocumentAbstract.java:2077) ~[orientdb-core-3.0.31.jar:3.0.31]
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentAbstract.save(ODatabaseDocumentAbstract.java:2039) ~[orientdb-core-3.0.31.jar:3.0.31]
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentAbstract.save(ODatabaseDocumentAbstract.java:86) ~[orientdb-core-3.0.31.jar:3.0.31]
	at com.orientechnologies.orient.core.record.impl.ODocument.save(ODocument.java:2178) ~[orientdb-core-3.0.31.jar:3.0.31]
	at com.orientechnologies.orient.core.record.impl.ODocument.save(ODocument.java:2169) ~[orientdb-core-3.0.31.jar:3.0.31]
	at com.orientechnologies.orient.core.record.impl.ODocument.save(ODocument.java:120) ~[orientdb-core-3.0.31.jar:3.0.31]
	at com.cloudleaf.cloudos.graphapp.service.AsyncDataMigrationService.pushData(AsyncDataMigrationService.java:695) [classes/:?]
	at com.cloudleaf.cloudos.graphapp.service.AsyncDataMigrationService.access$200(AsyncDataMigrationService.java:45) [classes/:?]
	at com.cloudleaf.cloudos.graphapp.service.AsyncDataMigrationService$PullAndPushData.run(AsyncDataMigrationService.java:995) [classes/:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_322]
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266) [?:1.8.0_322]
	at java.util.concurrent.FutureTask.run(FutureTask.java) [?:1.8.0_322]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_322]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_322]
	at java.lang.Thread.run(Thread.java:750) [?:1.8.0_322]
Caused by: com.orientechnologies.common.io.OIOException: Channel is closed
	at com.orientechnologies.orient.client.remote.OStorageRemote.baseNetworkOperation(OStorageRemote.java:351) ~[orientdb-client-3.0.31.jar:3.0.31]
	at com.orientechnologies.orient.client.remote.OStorageRemote.asyncNetworkOperationRetry(OStorageRemote.java:173) ~[orientdb-client-3.0.31.jar:3.0.31]
	at com.orientechnologies.orient.client.remote.OStorageRemote.asyncNetworkOperationNoRetry(OStorageRemote.java:161) ~[orientdb-client-3.0.31.jar:3.0.31]
	at com.orientechnologies.orient.client.remote.OStorageRemote.createRecord(OStorageRemote.java:618) ~[orientdb-client-3.0.31.jar:3.0.31]
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentRemote.executeSaveRecord(ODatabaseDocumentRemote.java:606) ~[orientdb-client-3.0.31.jar:3.0.31]
	at com.orientechnologies.orient.core.tx.OTransactionNoTx.saveNew(OTransactionNoTx.java:244) ~[orientdb-core-3.0.31.jar:3.0.31]
	at com.orientechnologies.orient.core.tx.OTransactionNoTx.saveRecord(OTransactionNoTx.java:174) ~[orientdb-core-3.0.31.jar:3.0.31]
	... 15 more
Caused by: java.io.IOException: Channel is closed
	at com.orientechnologies.orient.client.binary.OChannelBinaryAsynchClient.beginResponse(OChannelBinaryAsynchClient.java:169) ~[orientdb-client-3.0.31.jar:3.0.31]
	at com.orientechnologies.orient.client.binary.OChannelBinaryAsynchClient.beginResponse(OChannelBinaryAsynchClient.java:158) ~[orientdb-client-3.0.31.jar:3.0.31]
	at com.orientechnologies.orient.client.remote.OStorageRemote.beginResponse(OStorageRemote.java:1891) ~[orientdb-client-3.0.31.jar:3.0.31]
	at com.orientechnologies.orient.client.remote.OStorageRemote.lambda$asyncNetworkOperationRetry$1(OStorageRemote.java:190) ~[orientdb-client-3.0.31.jar:3.0.31]
	at com.orientechnologies.orient.client.remote.OStorageRemote.baseNetworkOperation(OStorageRemote.java:307) ~[orientdb-client-3.0.31.jar:3.0.31]
	at com.orientechnologies.orient.client.remote.OStorageRemote.asyncNetworkOperationRetry(OStorageRemote.java:173) ~[orientdb-client-3.0.31.jar:3.0.31]
	at com.orientechnologies.orient.client.remote.OStorageRemote.asyncNetworkOperationNoRetry(OStorageRemote.java:161) ~[orientdb-client-3.0.31.jar:3.0.31]
	at com.orientechnologies.orient.client.remote.OStorageRemote.createRecord(OStorageRemote.java:618) ~[orientdb-client-3.0.31.jar:3.0.31]
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentRemote.executeSaveRecord(ODatabaseDocumentRemote.java:606) ~[orientdb-client-3.0.31.jar:3.0.31]
	at com.orientechnologies.orient.core.tx.OTransactionNoTx.saveNew(OTransactionNoTx.java:244) ~[orientdb-core-3.0.31.jar:3.0.31]
	at com.orientechnologies.orient.core.tx.OTransactionNoTx.saveRecord(OTransactionNoTx.java:174) ~[orientdb-core-3.0.31.jar:3.0.31]
	... 15 more
[ERROR] 2022-05-19 17:07:30.519 [pool-16-thread-3] AsyncDataMigrationService - something went wrong while pushing data to cloudleaf for cluster:custodyasset_8068c968_b761_450f_a4c9_be0b2a546cf5 vertex id ::391a357c-5fb6-4ce7-a458-03e83e58834d
com.orientechnologies.orient.core.exception.ODatabaseException: Error during saving of record with rid #-1:-1
	DB name="cloudleaf"
	at com.orientechnologies.orient.core.tx.OTransactionNoTx.saveRecord(OTransactionNoTx.java:206) ~[orientdb-core-3.0.31.jar:3.0.31]
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentAbstract.saveInternal(ODatabaseDocumentAbstract.java:2077) ~[orientdb-core-3.0.31.jar:3.0.31]
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentAbstract.save(ODatabaseDocumentAbstract.java:2039) ~[orientdb-core-3.0.31.jar:3.0.31]
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentAbstract.save(ODatabaseDocumentAbstract.java:86) ~[orientdb-core-3.0.31.jar:3.0.31]
	at com.orientechnologies.orient.core.record.impl.ODocument.save(ODocument.java:2178) ~[orientdb-core-3.0.31.jar:3.0.31]
	at com.orientechnologies.orient.core.record.impl.ODocument.save(ODocument.java:2169) ~[orientdb-core-3.0.31.jar:3.0.31]
	at com.orientechnologies.orient.core.record.impl.ODocument.save(ODocument.java:120) ~[orientdb-core-3.0.31.jar:3.0.31]
	at com.cloudleaf.cloudos.graphapp.service.AsyncDataMigrationService.pushData(AsyncDataMigrationService.java:695) [classes/:?]
	at com.cloudleaf.cloudos.graphapp.service.AsyncDataMigrationService.access$200(AsyncDataMigrationService.java:45) [classes/:?]
	at com.cloudleaf.cloudos.graphapp.service.AsyncDataMigrationService$PullAndPushData.run(AsyncDataMigrationService.java:995) [classes/:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_322]
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266) [?:1.8.0_322]
	at java.util.concurrent.FutureTask.run(FutureTask.java) [?:1.8.0_322]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_322]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_322]
	at java.lang.Thread.run(Thread.java:750) [?:1.8.0_322]
Caused by: com.orientechnologies.common.io.OIOException: Socket closed
	at com.orientechnologies.orient.client.remote.OStorageRemote.baseNetworkOperation(OStorageRemote.java:351) ~[orientdb-client-3.0.31.jar:3.0.31]
	at com.orientechnologies.orient.client.remote.OStorageRemote.asyncNetworkOperationRetry(OStorageRemote.java:173) ~[orientdb-client-3.0.31.jar:3.0.31]
	at com.orientechnologies.orient.client.remote.OStorageRemote.asyncNetworkOperationNoRetry(OStorageRemote.java:161) ~[orientdb-client-3.0.31.jar:3.0.31]
	at com.orientechnologies.orient.client.remote.OStorageRemote.createRecord(OStorageRemote.java:618) ~[orientdb-client-3.0.31.jar:3.0.31]
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentRemote.executeSaveRecord(ODatabaseDocumentRemote.java:606) ~[orientdb-client-3.0.31.jar:3.0.31]
	at com.orientechnologies.orient.core.tx.OTransactionNoTx.saveNew(OTransactionNoTx.java:244) ~[orientdb-core-3.0.31.jar:3.0.31]
	at com.orientechnologies.orient.core.tx.OTransactionNoTx.saveRecord(OTransactionNoTx.java:174) ~[orientdb-core-3.0.31.jar:3.0.31]
	... 15 more
Caused by: java.net.SocketException: Socket closed
	at java.net.SocketInputStream.socketRead0(Native Method) ~[?:1.8.0_322]
	at java.net.SocketInputStream.socketRead(SocketInputStream.java:116) ~[?:1.8.0_322]
	at java.net.SocketInputStream.read(SocketInputStream.java:171) ~[?:1.8.0_322]
	at java.net.SocketInputStream.read(SocketInputStream.java:141) ~[?:1.8.0_322]
	at java.io.BufferedInputStream.fill(BufferedInputStream.java:246) ~[?:1.8.0_322]
	at java.io.BufferedInputStream.read(BufferedInputStream.java:265) ~[?:1.8.0_322]
	at java.io.DataInputStream.readByte(DataInputStream.java:265) ~[?:1.8.0_322]
	at com.orientechnologies.orient.enterprise.channel.binary.OChannelBinary.readByte(OChannelBinary.java:73) ~[orientdb-core-3.0.31.jar:3.0.31]
	at com.orientechnologies.orient.client.binary.OChannelBinaryAsynchClient.beginResponse(OChannelBinaryAsynchClient.java:174) ~[orientdb-client-3.0.31.jar:3.0.31]
	at com.orientechnologies.orient.client.binary.OChannelBinaryAsynchClient.beginResponse(OChannelBinaryAsynchClient.java:158) ~[orientdb-client-3.0.31.jar:3.0.31]
	at com.orientechnologies.orient.client.remote.OStorageRemote.beginResponse(OStorageRemote.java:1891) ~[orientdb-client-3.0.31.jar:3.0.31]
	at com.orientechnologies.orient.client.remote.OStorageRemote.lambda$asyncNetworkOperationRetry$1(OStorageRemote.java:190) ~[orientdb-client-3.0.31.jar:3.0.31]
	at com.orientechnologies.orient.client.remote.OStorageRemote.baseNetworkOperation(OStorageRemote.java:307) ~[orientdb-client-3.0.31.jar:3.0.31]
	at com.orientechnologies.orient.client.remote.OStorageRemote.asyncNetworkOperationRetry(OStorageRemote.java:173) ~[orientdb-client-3.0.31.jar:3.0.31]
	at com.orientechnologies.orient.client.remote.OStorageRemote.asyncNetworkOperationNoRetry(OStorageRemote.java:161) ~[orientdb-client-3.0.31.jar:3.0.31]
	at com.orientechnologies.orient.client.remote.OStorageRemote.createRecord(OStorageRemote.java:618) ~[orientdb-client-3.0.31.jar:3.0.31]
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentRemote.executeSaveRecord(ODatabaseDocumentRemote.java:606) ~[orientdb-client-3.0.31.jar:3.0.31]
	at com.orientechnologies.orient.core.tx.OTransactionNoTx.saveNew(OTransactionNoTx.java:244) ~[orientdb-core-3.0.31.jar:3.0.31]
	at com.orientechnologies.orient.core.tx.OTransactionNoTx.saveRecord(OTransactionNoTx.java:174) ~[orientdb-core-3.0.31.jar:3.0.31]
	... 15 more
```
I read in one article that due to large packet size . this happens , So let me know where can we increase the packet size for concurrent saving.

**Comment by tglman** [comment]
Hi,

Could you try this with the latest release ? also i see from the error that the version you are using ins 3.0.x, make sure that both client and server are the same version to avoid this kind of errors.

Regards
