### ISSUE TITLE
NullPointerException when login into a database

### ISSUE THREAD

**Issue by woody0907** [orientechnologies/orientdb#9836]
## Expected behavior  
login to bmc20220630 dababase 

## Actual behavior  
Session expired

## Steps to reproduce  
<add here>  
<An SQL script to reproduce the problem or a JUnit test case will increase **A LOT** the chance to have a quick fix>

2022-06-30 11:17:25:540 INFO  Detected limit of amount of simultaneously open files is 262144,  limit of open files for disk cache will be set to 130560 [ONative]
2022-06-30 11:17:25:609 INFO  Loading configuration from: /opt/orientdb-3.2.3/config/orientdb-server-config.xml... [OServerConfigurationLoaderXml]
2022-06-30 11:17:25:941 INFO  OrientDB Server v3.2.3 (build dc98198215aa57baf29b32adb657dc3733acdb55, branch develop) is starting up... [OServer]
2022-06-30 11:17:26:673 INFO  50476023808 B/48137 MB/47 GB of physical memory were detected on machine [ONative]
2022-06-30 11:17:26:674 INFO  Soft memory limit for this process is set to -1 B/-1 MB/-1 GB [ONative]
2022-06-30 11:17:26:674 INFO  Hard memory limit for this process is set to -1 B/-1 MB/-1 GB [ONative]
2022-06-30 11:17:26:675 INFO  Path to 'memory' cgroup is '/user.slice' [ONative]
2022-06-30 11:17:26:679 INFO  Mounting path for memory cgroup controller is '/sys/fs/cgroup/memory' [ONative]
2022-06-30 11:17:26:680 INFO  cgroup soft memory limit is 9223372036854771712 B/8796093022207 MB/8589934591 GB [ONative]
2022-06-30 11:17:26:681 INFO  cgroup hard memory limit is 9223372036854771712 B/8796093022207 MB/8589934591 GB [ONative]
2022-06-30 11:17:26:681 INFO  Detected memory limit for current process is 50476023808 B/48137 MB/47 GB [ONative]
2022-06-30 11:17:26:682 INFO  JVM can use maximum 3925MB of heap memory [OMemoryAndLocalPaginatedEnginesInitializer]
2022-06-30 11:17:26:683 INFO  Because OrientDB is running outside a container 2g of memory will be left unallocated according to the setting 'memory.leftToOS' not taking into account heap memory [OMemoryAndLocalPaginatedEnginesInitializer]
2022-06-30 11:17:26:683 INFO  OrientDB auto-config DISKCACHE=42,164MB (heap=3,925MB os=48,137MB) [orientechnologies]
2022-06-30 11:17:26:686 INFO  System is started under an effective user : `root` [OEngineLocalPaginated]
2022-06-30 11:17:26:687 WARNI You are running under the "root" user privileges that introduces security risks. Please consider to run under a user dedicated to be used to run current server instance. [OEngineLocalPaginated]
2022-06-30 11:17:26:687 INFO  Allocation of 640892 pages. [OEngineLocalPaginated]
2022-06-30 11:17:29:252 INFO  WAL maximum segment size is set to 12,656 MB [OrientDBDistributed]
2022-06-30 11:17:30:411 INFO  ODefaultPasswordAuthenticator is active [ODefaultPasswordAuthenticator]
2022-06-30 11:17:30:412 INFO  OServerConfigAuthenticator is active [OServerConfigAuthenticator]
2022-06-30 11:17:30:413 INFO  OSystemUserAuthenticator is active [OSystemUserAuthenticator]
2022-06-30 11:17:30:572 INFO  Databases directory: /opt/orientdb-3.2.3/databases [OServer]
2022-06-30 11:17:30:694 INFO  Page size for WAL located in /opt/orientdb-3.2.3/databases/OSystem is set to 4096 bytes. [CASDiskWriteAheadLog]
2022-06-30 11:17:30:761 INFO  DWL:OSystem: block size = 4096 bytes, maximum segment size = 12656 MB [DoubleWriteLogGL]
2022-06-30 11:17:31:097 INFO  Storage 'plocal:/opt/orientdb-3.2.3/databases/OSystem' is opened under OrientDB distribution : 3.2.3 (build dc98198215aa57baf29b32adb657dc3733acdb55, branch develop) [OLocalPaginatedStorage]
2022-06-30 11:17:31:481 INFO  Listening binary connections on 0.0.0.0:2424 (protocol v.38, socket=default) [OServerNetworkListener]
2022-06-30 11:17:31:494 INFO  Listening http connections on 0.0.0.0:2480 (protocol v.10, socket=default) [OServerNetworkListener]
2022-06-30 11:17:31:581 INFO  Found ORIENTDB_ROOT_PASSWORD variable, using this value as root's password [OServer]
2022-06-30 11:17:31:587 INFO  Installing dynamic plugin 'orientdb-etl-3.2.3.jar'... [OServerPluginManager]
2022-06-30 11:17:31:611 INFO  Installing dynamic plugin 'orientdb-studio-3.2.3.zip'... [OServerPluginManager]
2022-06-30 11:17:31:622 INFO  Installing dynamic plugin 'orientdb-teleporter-3.2.3.jar'... [OServerPluginManager]
2022-06-30 11:17:31:671 INFO  Installing dynamic plugin 'orientdb-neo4j-importer-plugin-3.2.3-dist.jar'... [OServerPluginManager]
2022-06-30 11:17:31:676 INFO  [OVariableParser.resolveVariables] Property not found: distributed [orientechnologies]
2022-06-30 11:17:31:689 WARNI Authenticated clients can execute any kind of code into the server by using the following allowed languages: [sql] [OServerSideScriptInterpreter]
2022-06-30 11:17:31:692 INFO  OrientDB Server is active v3.2.3 (build dc98198215aa57baf29b32adb657dc3733acdb55, branch develop). [OServer]
2022-06-30 11:17:55:985 INFO  Page size for WAL located in /opt/orientdb-3.2.3/databases/bmc20220630 is set to 4096 bytes. [CASDiskWriteAheadLog]
2022-06-30 11:17:56:137 INFO  DWL:bmc20220630: block size = 4096 bytes, maximum segment size = 12656 MB [DoubleWriteLogGL]Exception `37243E0B` in storage `plocal:/opt/orientdb-3.2.3/databases/bmc20220630`: 3.2.3 (build dc98198215aa57baf29b32adb657dc3733acdb55, branch develop)
java.lang.NullPointerException
	at com.orientechnologies.orient.core.storage.cache.chm.AsyncReadCache.releaseFromRead(AsyncReadCache.java:310)
	at com.orientechnologies.orient.core.storage.impl.local.paginated.base.ODurableComponent.releasePageFromRead(ODurableComponent.java:179)
	at com.orientechnologies.orient.core.storage.index.sbtreebonsai.global.btree.BTree.firstItem(BTree.java:311)
	at com.orientechnologies.orient.core.storage.index.sbtreebonsai.global.btree.BTree.firstKey(BTree.java:230)
	at com.orientechnologies.orient.core.storage.ridbag.sbtree.OSBTreeCollectionManagerShared.load(OSBTreeCollectionManagerShared.java:87)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.open(OAbstractPaginatedStorage.java:359)
	at com.orientechnologies.orient.core.db.OrientDBEmbedded.getAndOpenStorage(OrientDBEmbedded.java:522)
	at com.orientechnologies.orient.core.db.OrientDBEmbedded.open(OrientDBEmbedded.java:473)
	at com.orientechnologies.orient.core.db.OrientDBDistributed.open(OrientDBDistributed.java:252)
	at com.orientechnologies.orient.core.db.OrientDBEmbedded.open(OrientDBEmbedded.java:413)
	at com.orientechnologies.orient.core.db.OrientDBDistributed.open(OrientDBDistributed.java:237)
	at com.orientechnologies.orient.server.OServer.openDatabase(OServer.java:842)
	at com.orientechnologies.orient.server.OServer.openDatabase(OServer.java:835)
	at com.orientechnologies.orient.server.network.protocol.http.command.OServerCommandAuthenticatedDbAbstract.authenticate(OServerCommandAuthenticatedDbAbstract.java:194)
	at com.orientechnologies.orient.server.network.protocol.http.command.OServerCommandAuthenticatedDbAbstract.beforeExecute(OServerCommandAuthenticatedDbAbstract.java:136)
	at com.orientechnologies.orient.server.network.protocol.http.command.get.OServerCommandGetConnect.beforeExecute(OServerCommandGetConnect.java:55)
	at com.orientechnologies.orient.server.network.protocol.http.ONetworkProtocolHttpAbstract.service(ONetworkProtocolHttpAbstract.java:239)
	at com.orientechnologies.orient.server.network.protocol.http.ONetworkProtocolHttpAbstract.execute(ONetworkProtocolHttpAbstract.java:800)
	at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:68)

**Comment by tglman** [comment]
Hi,

did you try to update to 3.2.8, this may be already fixed.

Bye

**Comment by woody0907** [comment]
I have update to 3.2.8, but the problem is still there, the error messages code line changed:
java.lang.NullPointerException
	at com.orientechnologies.orient.core.storage.index.sbtreebonsai.global.btree.BTree.firstItem(BTree.java:301)
	at com.orientechnologies.orient.core.storage.index.sbtreebonsai.global.btree.BTree.firstKey(BTree.java:222)
	at com.orientechnologies.orient.core.storage.ridbag.sbtree.OSBTreeCollectionManagerShared.load(OSBTreeCollectionManagerShared.java:87)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.open(OAbstractPaginatedStorage.java:354)
	at com.orientechnologies.orient.core.db.OrientDBEmbedded.getAndOpenStorage(OrientDBEmbedded.java:522)
	at com.orientechnologies.orient.core.db.OrientDBEmbedded.open(OrientDBEmbedded.java:473)
	at com.orientechnologies.orient.core.db.OrientDBDistributed.open(OrientDBDistributed.java:254)
	at com.orientechnologies.orient.core.db.OrientDBEmbedded.open(OrientDBEmbedded.java:413)
	at com.orientechnologies.orient.core.db.OrientDBDistributed.open(OrientDBDistributed.java:239)
	at com.orientechnologies.orient.server.OServer.openDatabase(OServer.java:842)
	at com.orientechnologies.orient.server.OServer.openDatabase(OServer.java:835)
	at com.orientechnologies.orient.server.network.protocol.http.command.OServerCommandAuthenticatedDbAbstract.authenticate(OServerCommandAuthenticatedDbAbstract.java:194)
	at com.orientechnologies.orient.server.network.protocol.http.command.OServerCommandAuthenticatedDbAbstract.beforeExecute(OServerCommandAuthenticatedDbAbstract.java:136)
	at com.orientechnologies.orient.server.network.protocol.http.command.get.OServerCommandGetConnect.beforeExecute(OServerCommandGetConnect.java:55)
	at com.orientechnologies.orient.server.network.protocol.http.ONetworkProtocolHttpAbstract.service(ONetworkProtocolHttpAbstract.java:239)
	at com.orientechnologies.orient.server.network.protocol.http.ONetworkProtocolHttpAbstract.execute(ONetworkProtocolHttpAbstract.java:800)
	at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:68)

**Comment by dhayalramk** [comment]
Getting same error, Any suggestions?

**Comment by tglman** [comment]
Hi, 

This is a bit strange, is the database you are using coming from the 3.2.x series ore created with a older version of OrientDB ?

Bye

**Comment by tglman** [comment]
Hi,

Also if you have the chance to share a database with this problem, it would be very helpful to reproduce the problem.

Bye

**Comment by tglman** [comment]
Hi,

This issues seems related to some problem with indexes we had in the first release of 3.2.x, this should be completely solved from 3.2.9, could you double check?

Regards
