### ISSUE TITLE
Index corruption, CellBTreeSingleValueV3 class endless loop

### ISSUE THREAD

**Issue by yaolinhu** [orientechnologies/orientdb#9839]
## Expected behavior  
Returns the desired result when using a unique index

## Actual behavior  
When a query SQL goes through the unique index, no result is returned. Check the class /core/storage/index/sbtree/singlevalue/v3/CellBTreeSingleValueV3.java, method readkeysfrombuckets , orientdb server has entered an endless loop.   

## Steps to reproduce  
<add here>  
sql examle :  
select count(*) as count from rtype1 where relationID = 1; //An index is established on the attribute relationID of type rtype1.

This is an occasional question. Has the new version 3.1.18 been repaired?

**Comment by tglman** [comment]
Hi, 

There have been fixes around indexes (so CellBTreeSingleValueV3.java) some released some not yet released, that may solve as well this problem, it would be useful have an example database or an example software that would help to reproduce this case.

Regards

**Comment by yaolinhu** [comment]
See attachment for test database.   

I don't know when the index corruption was caused, Please confirm whether this problem has been fixed?

**Comment by tglman** [comment]
Hi,

I tried the database I reproduced the problem, but the issue seems related to index persistence, some persistent data structures go in a reference loop, and I cannot reproduce the way you can reach this state, if you have a script or test case that can bring a valid database to this state it would be really helpful!

Anyway is possible to work around this problem "regenerating" the index, you could do that doing and export and import of the database.

Regards

**Comment by yaolinhu** [comment]
Sorry, I really don't know how to reproduce this problem, but it has appeared several times. Is this related to disk? For example, insufficient disk space or poor disk performance? 

Regards

**Comment by pontusvision** [comment]
I'm also running into issues around the CellBTreeSingleValueBucketV3 where the code is looking for a serializer with an ID of 0, and getting a null pointer in deserializeFromByteBufferObject()... to troubleshoot it, I modified the code in  deserializeFromByteBufferObject() to do the following:
```
  @SuppressWarnings("unchecked")
      OBinarySerializer<Object> binarySerializer =
          (OBinarySerializer<Object>) factory.getObjectSerializer(serializerId);
      if (binarySerializer == null){
        terminateProcess(new OStorageException("Failed to find binary serializer for "+ serializerId),this);
      }
    
```
I can reproduce this relatively easily at a client site, but they have PII data in their database, so I can't send it out very easily.

Here's the stack trace (this is version 3.2.8 + my mods to  terminate the DB and print the id it's looking for.
```
        at com.orientechnologies.orient.core.serialization.serializer.binary.impl.index.OCompositeKeySerializer.deserializeFromByteBufferObject(OCompositeKeySerializer.java:390)
        at com.orientechnologies.orient.core.serialization.serializer.binary.impl.index.OCompositeKeySerializer.deserializeFromByteBufferObject(OCompositeKeySerializer.java:45)
        at com.orientechnologies.orient.core.storage.impl.local.paginated.base.ODurablePage.deserializeFromDirectMemory(ODurablePage.java:220)
        at com.orientechnologies.orient.core.storage.index.sbtree.singlevalue.v3.CellBTreeSingleValueBucketV3.getKey(CellBTreeSingleValueBucketV3.java:337)
        at com.orientechnologies.orient.core.storage.index.sbtree.singlevalue.v3.CellBTreeSingleValueV3.splitBucket(CellBTreeSingleValueV3.java:1412)
        at com.orientechnologies.orient.core.storage.index.sbtree.singlevalue.v3.CellBTreeSingleValueV3.splitNonRootBucket(CellBTreeSingleValueV3.java:1499)
        at com.orientechnologies.orient.core.storage.index.sbtree.singlevalue.v3.CellBTreeSingleValueV3.splitBucket(CellBTreeSingleValueV3.java:1422)
        at com.orientechnologies.orient.core.storage.index.sbtree.singlevalue.v3.CellBTreeSingleValueV3.lambda$update$1(CellBTreeSingleValueV3.java:324)
        at com.orientechnologies.orient.core.storage.impl.local.paginated.atomicoperations.OAtomicOperationsManager.calculateInsideComponentOperation(OAtomicOperationsManager.java:221)
        at com.orientechnologies.orient.core.storage.impl.local.paginated.atomicoperations.OAtomicOperationsManager.calculateInsideComponentOperation(OAtomicOperationsManager.java:213)
        at com.orientechnologies.orient.core.storage.impl.local.paginated.base.ODurableComponent.calculateInsideComponentOperation(ODurableComponent.java:96)
        at com.orientechnologies.orient.core.storage.index.sbtree.singlevalue.v3.CellBTreeSingleValueV3.update(CellBTreeSingleValueV3.java:229)
        at com.orientechnologies.orient.core.storage.index.sbtree.singlevalue.v3.CellBTreeSingleValueV3.validatedPut(CellBTreeSingleValueV3.java:221)
        at com.orientechnologies.orient.core.index.engine.v1.OCellBTreeSingleValueIndexEngine.validatedPut(OCellBTreeSingleValueIndexEngine.java:209)
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.doValidatedPutIndexValue(OAbstractPaginatedStorage.java:3520)
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.validatedPutIndexValue(OAbstractPaginatedStorage.java:3472)
        at com.orientechnologies.orient.core.index.OIndexUnique.doPut(OIndexUnique.java:116)
        at com.orientechnologies.orient.core.index.OIndexAbstractDelegate.doPut(OIndexAbstractDelegate.java:436)
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.applyTxChanges(OAbstractPaginatedStorage.java:2466)
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.commitIndexes(OAbstractPaginatedStorage.java:2450)
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.commit(OAbstractPaginatedStorage.java:2368)
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.commit(OAbstractPaginatedStorage.java:2182)
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentEmbedded.internalCommit(ODatabaseDocumentEmbedded.java:1821)
        at com.orientechnologies.orient.core.tx.OTransactionOptimistic.doCommit(OTransactionOptimistic.java:621)
        at com.orientechnologies.orient.core.tx.OTransactionOptimistic.commit(OTransactionOptimistic.java:114)
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentAbstract.commit(ODatabaseDocumentAbstract.java:1593)
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentAbstract.commit(ODatabaseDocumentAbstract.java:1563)
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentEmbedded.saveAll(ODatabaseDocumentEmbedded.java:1148)
        at com.orientechnologies.orient.core.tx.OTransactionNoTx.saveRecord(OTransactionNoTx.java:208)
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentAbstract.saveInternal(ODatabaseDocumentAbstract.java:1484)
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentAbstract.save(ODatabaseDocumentAbstract.java:1432)
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentAbstract.save(ODatabaseDocumentAbstract.java:1315)
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentAbstract.save(ODatabaseDocumentAbstract.java:78)
        at com.orientechnologies.orient.core.sql.executor.SaveElementStep$1.next(SaveElementStep.java:37)
        at com.orientechnologies.orient.core.sql.executor.ConvertToResultInternalStep$1.fetchNextItem(ConvertToResultInternalStep.java:60)
        at com.orientechnologies.orient.core.sql.executor.ConvertToResultInternalStep$1.hasNext(ConvertToResultInternalStep.java:86)
        at com.orientechnologies.orient.core.sql.executor.OUpdateExecutionPlan.executeInternal(OUpdateExecutionPlan.java:42)
        at com.orientechnologies.orient.core.sql.parser.OUpdateStatement.execute(OUpdateStatement.java:173)
        at com.orientechnologies.orient.core.sql.parser.OStatement.execute(OStatement.java:81)
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentEmbedded.command(ODatabaseDocumentEmbedded.java:583)
        at org.apache.tinkerpop.gremlin.orientdb.OrientGraph.executeSql(OrientGraph.java:248)
        at org.apache.tinkerpop.gremlin.orientdb.OrientStandardGraph.executeSql(OrientStandardGraph.java:187)
        at org.apache.tinkerpop.gremlin.orientdb.OGraph$executeSql.call(Unknown Source)
        at com.pontusvision.graphutils.Matcher.processVerticesSlim(matching.groovy:2216)
```

**Comment by tglman** [comment]
Hi,

This issue seems to be a bug in the index implementation fixes have been done in it recently, the most recent is included in 3.2.9 release, from that release on should not be there issues with indexes itself.

Regards
