### ISSUE TITLE
NullPointerException when executing a complex query using ODatabaseDocument.query()

### ISSUE THREAD

**Issue by cunrein** [orientechnologies/orientdb#9894]
## Expected behavior  
The query described below should execute and return results the same as the Orientdb Console

## Actual behavior  
```
var quary = """ 
select from UOM_OBJECT where 
  ((UUID IN (select expand(in('isUomType').UUID) from (traverse in('hasParentUomType') from (
    select from UOM_TYPE where UUID = '12345678-abcd-abcd-abcd-1234567890ab')))) AND
    ((NAME = 'George of the Jungle' AND (UUID IN (select in('isCountry').in('hasUomCountry').UUID 
      from COUNTRY where ISO_2_CODE = 'CG'))) OR
    ((NAME = 'Jane' AND (UUID IN (select in('isCountry').in('hasUomCountry').UUID 
      from COUNTRY where ISO_2_CODE = 'US'))))) AND 
        inCOI.COI_ID IN ['22345678-abcd-abcd-abcd-2234567890ab'] order by UUID limit 10000
"""
```
Call to `ODatabaseDocument.query(query)` throws an exception:
```
Caused by: java.lang.NullPointerException: null
    at com.orienttechnologies.orient.core.sql.function.graph.OSQLFunctionMove.v2v(OSQLFunctionMove.java:79)
    at com.orienttechnologies.orient.core.sql.function.graph.OSQLFunctionIn.move(OSQLFunctionIn.java:39)
...
```
## Steps to reproduce  
Connect to a database and create a query similar to the one above. Then using a connected `ODatabaseDocument` execute the constructed `query`. If the constructed query is not traversing edges the query is successful. The query that is used must traverse at least one edge (more traversals are better the query above has four traversals).

**Comment by tglman** [comment]
Hi,

The 3.2.12 has been just released and should already include a fix for this case, please double check it.

**Comment by cunrein** [comment]
The enterprise agent is failing to build due to an NPE in the tests after the 3.2.12 release:
Results :

```
Failed tests: 
  OMetricCSVQueryAggregatorTest.csvAggregatorTest:107 expected:<[select from] OUser> but was:<[SELECT FROM] OUser>
  QueryProfilerFilterTest.testFilterQueries:74
Tests in error: 
com.orientechnologies.security.auditing.AuditingChangePasswordTest.changePasswordTest(com.orientechnologies.security.auditing.AuditingChangePasswordTest)
  Run 1: AuditingChangePasswordTest>EEBaseServerHttpTest.init:49 » OCommandExecution Ca...
  Run 2: AuditingChangePasswordTest>EEBaseServerHttpTest.after:64 » NullPointer

com.orientechnologies.security.auditing.AuditingRetentionConfigTest.retentionGeneral(com.orientechnologies.security.auditing.AuditingRetentionConfigTest)
  Run 1: AuditingRetentionConfigTest>EEBaseServerHttpTest.init:49 » OCommandExecution C...
  Run 2: AuditingRetentionConfigTest>EEBaseServerHttpTest.after:64 » NullPointer

com.orientechnologies.security.auditing.AuditingRootLogTest.changePasswordWitRootTest(com.orientechnologies.security.auditing.AuditingRootLogTest)
  Run 1: AuditingRootLogTest>EEBaseServerHttpTest.init:49 » OCommandExecution Cannot cr...
  Run 2: AuditingRootLogTest>EEBaseServerHttpTest.after:64 » NullPointer

com.orientechnologies.security.auditing.AuditingRootLogTest.loginGuest(com.orientechnologies.security.auditing.AuditingRootLogTest)
  Run 1: AuditingRootLogTest>EEBaseServerHttpTest.init:49 » OCommandExecution Cannot cr...
  Run 2: AuditingRootLogTest>EEBaseServerHttpTest.after:64 » NullPointer

com.orientechnologies.security.auditing.AuditingRootLogTest.loginReader(com.orientechnologies.security.auditing.AuditingRootLogTest)
  Run 1: AuditingRootLogTest>EEBaseServerHttpTest.init:49 » OCommandExecution Cannot cr...
  Run 2: AuditingRootLogTest>EEBaseServerHttpTest.after:64 » NullPointer

com.orientechnologies.security.auditing.AuditingRootLogTest.postSecurity(com.orientechnologies.security.auditing.AuditingRootLogTest)
  Run 1: AuditingRootLogTest>EEBaseServerHttpTest.init:49 » OCommandExecution Cannot cr...
  Run 2: AuditingRootLogTest>EEBaseServerHttpTest.after:64 » NullPointer

com.orientechnologies.security.auditing.AuditingRootLogTest.postSecurityAndAuditingConfig(com.orientechnologies.security.auditing.AuditingRootLogTest)
  Run 1: AuditingRootLogTest>EEBaseServerHttpTest.init:49 » OCommandExecution Cannot cr...
  Run 2: AuditingRootLogTest>EEBaseServerHttpTest.after:64 » NullPointer

com.orientechnologies.security.auditing.AuditingRootLogTest.reloadSecurityTest(com.orientechnologies.security.auditing.AuditingRootLogTest)
  Run 1: AuditingRootLogTest>EEBaseServerHttpTest.init:49 » OCommandExecution Cannot cr...
  Run 2: AuditingRootLogTest>EEBaseServerHttpTest.after:64 » NullPointer

  SystemDbAuditingTest.createDropClassTest:90 » OCommandExecution Class not foun...

Tests run: 72, Failures: 2, Errors: 9, Skipped: 2
```

Stack Trace: 
```
Running com.orientechnologies.security.auditing.AuditingRetentionConfigTest
Tests run: 2, Failures: 0, Errors: 2, Skipped: 0, Time elapsed: 1.846 sec <<< FAILURE! - in com.orientechnologies.security.auditing.AuditingRetentionConfigTest
retentionGeneral(com.orientechnologies.security.auditing.AuditingRetentionConfigTest)  Time elapsed: 1.803 sec  <<< ERROR!
com.orientechnologies.orient.core.exception.OCommandExecutionException: 
Cannot create user guest: role guest does not exist
	DB name="OSystem"
	at com.orientechnologies.orient.core.sql.parser.OCreateSystemUserStatement.lambda$executeSimple$0(OCreateSystemUserStatement.java:99)
	at com.orientechnologies.orient.core.db.OSystemDatabase.executeWithDB(OSystemDatabase.java:197)
	at com.orientechnologies.orient.core.sql.parser.OCreateSystemUserStatement.executeSimple(OCreateSystemUserStatement.java:48)
	at com.orientechnologies.orient.core.sql.executor.OSingleOpServerExecutionPlan.executeInternal(OSingleOpServerExecutionPlan.java:97)
	at com.orientechnologies.orient.core.sql.parser.OSimpleExecServerStatement.execute(OSimpleExecServerStatement.java:49)
	at com.orientechnologies.orient.core.sql.parser.OServerStatement.execute(OServerStatement.java:77)
	at com.orientechnologies.orient.core.db.OrientDBEmbedded.executeServerStatement(OrientDBEmbedded.java:1224)
	at com.orientechnologies.orient.core.db.OrientDB.execute(OrientDB.java:364)
	at com.orientechnologies.orient.server.OServer.createDefaultServerUsers(OServer.java:1048)
	at com.orientechnologies.orient.server.OServer.loadUsers(OServer.java:894)
	at com.orientechnologies.orient.server.OServer.activate(OServer.java:478)
	at com.orientechnologies.orient.server.OServer.startFromClasspathConfig(OServer.java:156)
	at com.orientechnologies.orient.server.distributed.http.EEBaseServerHttpTest.init(EEBaseServerHttpTest.java:49)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.RunBefores.invokeMethod(RunBefores.java:33)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:61)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:367)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:274)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:238)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:161)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:290)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:242)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:121)

retentionGeneral(com.orientechnologies.security.auditing.AuditingRetentionConfigTest)  Time elapsed: 1.803 sec  <<< ERROR!
java.lang.NullPointerException
	at com.orientechnologies.orient.server.distributed.http.EEBaseServerHttpTest.after(EEBaseServerHttpTest.java:64)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.RunAfters.invokeMethod(RunAfters.java:46)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:33)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:61)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:367)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:274)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:238)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:161)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:290)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:242)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:121)
```

**Comment by tglman** [comment]
Hi, 

yes this was fixed after the release, just build without running test for that plugin, or get the public jar

**Comment by cunrein** [comment]
The original problem identified in this ticket appears to be resolved.

**Comment by tglman** [comment]
Hi,

Thanks, closing
