### ISSUE TITLE
ArrayOutOfBoundsException when creating an edge

### ISSUE THREAD

**Issue by gbaudic** [orientechnologies/orientdb#9898]
## Expected behavior  
Creating a new edge in the database succeeds.  

## Actual behavior  
We obtain the following stack trace in our logs:
```
com.orientechnologies.orient.core.exception.OStorageException: Exception during execution of component operation inside of storage XYZ
	DB name="XYZ"
	at com.orientechnologies.orient.core.storage.impl.local.paginated.atomicoperations.OAtomicOperationsManager.calculateInsideComponentOperation(OAtomicOperationsManager.java:222)
	at com.orientechnologies.orient.core.storage.impl.local.paginated.atomicoperations.OAtomicOperationsManager.calculateInsideComponentOperation(OAtomicOperationsManager.java:211)
	at com.orientechnologies.orient.core.storage.impl.local.paginated.base.ODurableComponent.calculateInsideComponentOperation(ODurableComponent.java:99)
	at com.orientechnologies.orient.core.storage.index.sbtreebonsai.local.OSBTreeBonsaiLocal.put(OSBTreeBonsaiLocal.java:182)
	at com.orientechnologies.orient.core.storage.impl.local.paginated.ORidBagUpdateSerializationOperation.execute(ORidBagUpdateSerializationOperation.java:72)
	at com.orientechnologies.orient.core.storage.impl.local.paginated.ORecordSerializationContext.executeOperations(ORecordSerializationContext.java:90)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.doUpdateRecord(OAbstractPaginatedStorage.java:5336)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.commitEntry(OAbstractPaginatedStorage.java:5849)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.commit(OAbstractPaginatedStorage.java:2746)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.commit(OAbstractPaginatedStorage.java:2574)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentAbstract.internalCommit(ODatabaseDocumentAbstract.java:2766)
	at com.orientechnologies.orient.core.storage.impl.local.OMicroTransaction.doCommit(OMicroTransaction.java:363)
	at com.orientechnologies.orient.core.storage.impl.local.OMicroTransaction.commit(OMicroTransaction.java:166)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentEmbedded.endMicroTransaction(ODatabaseDocumentEmbedded.java:919)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentEmbedded.executeSaveRecord(ODatabaseDocumentEmbedded.java:909)
	at com.orientechnologies.orient.core.tx.OTransactionNoTx.saveRecord(OTransactionNoTx.java:184)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentAbstract.saveInternal(ODatabaseDocumentAbstract.java:2141)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentAbstract.save(ODatabaseDocumentAbstract.java:2103)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentAbstract.save(ODatabaseDocumentAbstract.java:135)
	at com.orientechnologies.orient.core.record.impl.ODocument.save(ODocument.java:2178)
	at com.orientechnologies.orient.core.record.impl.ODocument.save(ODocument.java:2169)
	at com.tinkerpop.blueprints.impls.orient.OrientGraphNoTx.addEdgeInternal(OrientGraphNoTx.java:258)
	at com.tinkerpop.blueprints.impls.orient.OrientGraphNoTx.addEdgeInternal(OrientGraphNoTx.java:136)
	at com.tinkerpop.blueprints.impls.orient.OrientVertex.addEdge(OrientVertex.java:760)
	at com.tinkerpop.blueprints.impls.orient.OrientVertex.addEdge(OrientVertex.java:736)
	...
	at com.orientechnologies.orient.core.sql.functions.OSQLFunctionRuntime.execute(OSQLFunctionRuntime.java:128)
	at com.orientechnologies.orient.core.sql.ORuntimeResult.applyRecord(ORuntimeResult.java:127)
	at com.orientechnologies.orient.core.sql.ORuntimeResult.getProjectionResult(ORuntimeResult.java:261)
	at com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.addResult(OCommandExecutorSQLSelect.java:696)
	at com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.handleNoTarget(OCommandExecutorSQLSelect.java:2852)
	at com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.execute(OCommandExecutorSQLSelect.java:473)
	at com.orientechnologies.orient.core.sql.OCommandExecutorSQLDelegate.execute(OCommandExecutorSQLDelegate.java:74)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.executeCommand(OAbstractPaginatedStorage.java:4624)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.command(OAbstractPaginatedStorage.java:4558)
	at com.orientechnologies.orient.core.sql.query.OSQLQuery.run(OSQLQuery.java:77)
	at com.orientechnologies.orient.core.sql.query.OSQLAsynchQuery.run(OSQLAsynchQuery.java:74)
	at com.orientechnologies.orient.core.sql.query.OSQLSynchQuery.run(OSQLSynchQuery.java:86)
	at com.orientechnologies.orient.core.query.OQueryAbstract.execute(OQueryAbstract.java:33)
	at com.orientechnologies.orient.server.OConnectionBinaryExecutor.executeCommand(OConnectionBinaryExecutor.java:603)
	at com.orientechnologies.orient.client.remote.message.OCommandRequest.execute(OCommandRequest.java:103)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.sessionRequest(ONetworkProtocolBinary.java:320)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.execute(ONetworkProtocolBinary.java:215)
	at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:69)
Caused by: java.lang.ArrayIndexOutOfBoundsException: 69
	at com.orientechnologies.orient.core.storage.impl.local.paginated.wal.OWALPageChangesPortion.updateData(OWALPageChangesPortion.java:318)
	at com.orientechnologies.orient.core.storage.impl.local.paginated.wal.OWALPageChangesPortion.setLongValue(OWALPageChangesPortion.java:43)
	at com.orientechnologies.orient.core.storage.impl.local.paginated.base.ODurablePage.setLongValue(ODurablePage.java:225)
	at com.orientechnologies.orient.core.storage.index.sbtreebonsai.local.OBonsaiBucketAbstract.setBucketPointer(OBonsaiBucketAbstract.java:55)
	at com.orientechnologies.orient.core.storage.index.sbtreebonsai.local.OSBTreeBonsaiBucket.addEntry(OSBTreeBonsaiBucket.java:411)
	at com.orientechnologies.orient.core.storage.index.sbtreebonsai.local.OSBTreeBonsaiLocal.splitBucket(OSBTreeBonsaiLocal.java:950)
	at com.orientechnologies.orient.core.storage.index.sbtreebonsai.local.OSBTreeBonsaiLocal.lambda$put$1(OSBTreeBonsaiLocal.java:206)
	at com.orientechnologies.orient.core.storage.impl.local.paginated.atomicoperations.OAtomicOperationsManager.calculateInsideComponentOperation(OAtomicOperationsManager.java:219)
	... 142 common frames omitted
```
This error can be reproduced on our side in a deterministic way. When debugging, we notice that we want to access index 69 in an array of 64 elements, hence the error.   

## Questions
  * Based on the stacktrace above, do you have any idea on what could have caused the database to reach this state? We are currently suspecting an improper shutdown of OrientDB, but is it possible that other, more usual operations (e.g., creating edges or vertices) can lead to this situation too?
  * Is there any possibility to check the database to find such errors (or ensure the database is error-free)? We are aware of the `CHECK DATABASE` SQL command, but in this case it did not detect any problem. Given the error above, we suspect there is more incorrect data in the database... 
  * Is there any possibility to fix these errors? Will the `REPAIR DATABASE` SQL command be of any help here? 

Any feedback will be appreciated.

**Comment by tglman** [comment]
Hi,

I did see similar errors, in OrientDB up to 3.2.6 and has been fixed, but not in the 3.0.x series, I would suggest you to update to at least hotfix of 3.0.x(that should be 3.0.44), or preferably the latest 3.2.x (latest 3.2.12) the 3.0.x is not receiving anymore hot fixes.

Regards

**Comment by gbaudic** [comment]
FYI, we keep investigating on this issue. The actual cause seems more and more likely to be an improper shutdown of the database.
After using the `REPAIR DATABASE --fix-ridbags --fix-bonsai` command on the database, we are no longer able to reproduce the issue.
