### ISSUE TITLE
NullPointerException when rebuilding an index

### ISSUE THREAD

**Issue by michele-pinto-kensu** [orientechnologies/orientdb#9899]
## Expected behavior  
The index should be rebuilt with success

## Actual behavior  
Rebuilding the index, ODB crashes with the following error:

> 2022-11-16 15:32:57:731 WARNI {db=damgraph} Invalid type index: 56 [OType]
2022-11-16 15:32:57:732 SEVER {db=damgraph} Error during index 'ObservationContextView.lds_id_usage__timestamp' delete [OIndexNotUnique]
java.lang.NullPointerException
		at com.orientechnologies.orient.core.serialization.serializer.binary.impl.index.CompositeKeySerializer.deserializeKeyFromByteBuffer(CompositeKeySerializer.java:181)
		at com.orientechnologies.orient.core.serialization.serializer.binary.impl.index.CompositeKeySerializer.deserialize(CompositeKeySerializer.java:173)
		at com.orientechnologies.orient.core.serialization.serializer.binary.impl.index.CompositeKeySerializer.deserializeFromByteBufferObject(CompositeKeySerializer.java:360)
		at com.orientechnologies.orient.core.serialization.serializer.binary.impl.index.CompositeKeySerializer.deserializeFromByteBufferObject(CompositeKeySerializer.java:25)
		at com.orientechnologies.orient.core.storage.impl.local.paginated.base.ODurablePage.deserializeFromDirectMemory(ODurablePage.java:231)
		at com.orientechnologies.orient.core.storage.index.sbtree.singlevalue.v3.CellBTreeSingleValueBucketV3.getKey(CellBTreeSingleValueBucketV3.java:340)
		at com.orientechnologies.orient.core.storage.index.sbtree.singlevalue.v3.CellBTreeSingleValueBucketV3.find(CellBTreeSingleValueBucketV3.java:94)
        at com.orientechnologies.orient.core.storage.index.sbtree.singlevalue.v3.CellBTreeSingleValueV3.findBucket(CellBTreeSingleValueV3.java:1747)
		at com.orientechnologies.orient.core.storage.index.sbtree.singlevalue.v3.CellBTreeSingleValueV3.fetchNextForwardCachePortion(CellBTreeSingleValueV3.java:1963)
		at com.orientechnologies.orient.core.storage.index.sbtree.singlevalue.v3.SpliteratorForward.tryAdvance(SpliteratorForward.java:56)
		at java.base/java.util.Spliterator.forEachRemaining(Spliterator.java:326)
		at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
		at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
		at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
		at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
		at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
		at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
		at com.orientechnologies.orient.core.index.OIndexAbstract.doDelete(OIndexAbstract.java:676)
		at com.orientechnologies.orient.core.index.OIndexAbstract.rebuild(OIndexAbstract.java:510)
		at com.orientechnologies.orient.core.index.OIndexAbstract.rebuild(OIndexAbstract.java:373)
		at com.orientechnologies.orient.core.index.OIndexAbstractDelegate.rebuild(OIndexAbstractDelegate.java:234)
		at com.orientechnologies.orient.core.sql.parser.ORebuildIndexStatement.executeSimple(ORebuildIndexStatement.java:51)
		at com.orientechnologies.orient.core.sql.executor.OSingleOpExecutionPlan.executeInternal(OSingleOpExecutionPlan.java:95)
		at com.orientechnologies.orient.core.sql.parser.OSimpleExecStatement.execute(OSimpleExecStatement.java:45)
		at com.orientechnologies.orient.core.sql.parser.OStatement.execute(OStatement.java:76)
		at com.orientechnologies.orient.core.db.document.ODatabaseDocumentEmbedded.command(ODatabaseDocumentEmbedded.java:613)
		at com.orientechnologies.orient.server.network.protocol.http.command.post.OServerCommandPostCommand.executeStatement(OServerCommandPostCommand.java:221)
		at com.orientechnologies.orient.server.network.protocol.http.command.post.OServerCommandPostCommand.execute(OServerCommandPostCommand.java:104)
		at com.orientechnologies.orient.server.network.protocol.http.command.post.OServerCommandPostCommandGraph.execute(OServerCommandPostCommandGraph.java:34)
		at com.orientechnologies.orient.server.network.protocol.http.ONetworkProtocolHttpAbstract.service(ONetworkProtocolHttpAbstract.java:242)
		at com.orientechnologies.orient.server.network.protocol.http.ONetworkProtocolHttpAbstract.execute(ONetworkProtocolHttpAbstract.java:800)
		at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:68)

## Steps to reproduce  
<add here>  
<An SQL script to reproduce the problem or a JUnit test case will increase **A LOT** the chance to have a quick fix>

- index type: NOTUNIQUE (composite key)
- engine: CELL_BTREE

**Comment by leszekgruchala** [comment]
@tglman additional details.
1. Rebuilding this index throws the above exception and causes an `internal storage error`, we have to restart the database
2. Deleting this index throws the above exception and does NOT crash the database
3. The index is a compound index of 3 fields: STRING + STRING + LONG, NOTUNIQUE, CELL_BTREE

It's a production blocker for us. Can you please share any ETA or a possible workaround with us? Thank you

**Comment by tglman** [comment]
Hi,

This bug was fixed in the recent version but yes rebuilding the index cause reading data that make it fails, so there is no really a way out of it, the only way is to run an export of data without including indexes  using `-includeIndexDefinitions=false` as described [here](https://orientechnologies.github.io/docs/3.2.x/console/Console-Command-Export.html?highlight=export#console---export) and than reimport it and recreate the index manually.

P.S. : please do not ask for free ETA

**Comment by tglman** [comment]
Hi,

Some fixes should be included in the 3.2.13 for avoid the crash on rebuild, not sure yet if it cover all the cases, feel free to try the 3.2.13.

Regards

**Comment by tglman** [comment]
Hi,

Some improved where also made from 3.2.14, that should avoid all the case when a rebuild fail for deleting the old index.

Regards
