### ISSUE TITLE
NullPointerException on OResultInternal when deleting vertices

### ISSUE THREAD

**Issue by SirStoke** [orientechnologies/orientdb#9900]
## Expected behavior

Statement runs fine

## Actual behavior

An NPE is thrown upon running a `DELETE` statement:

```
java.lang.NullPointerException: null
	at com.orientechnologies.orient.core.sql.executor.OResultInternal.hashCode(OResultInternal.java:479)
	at java.base/java.util.HashMap.hash(HashMap.java:340)
	at java.base/java.util.HashMap.containsKey(HashMap.java:592)
	at java.base/java.util.HashSet.contains(HashSet.java:204)
	at com.orientechnologies.orient.core.sql.executor.DistinctExecutionStep.alreadyVisited(DistinctExecutionStep.java:149)
	at com.orientechnologies.orient.core.sql.executor.DistinctExecutionStep.fetchNext(DistinctExecutionStep.java:105)
	at com.orientechnologies.orient.core.sql.executor.DistinctExecutionStep.access$100(DistinctExecutionStep.java:15)
	at com.orientechnologies.orient.core.sql.executor.DistinctExecutionStep$1.hasNext(DistinctExecutionStep.java:53)
	at com.orientechnologies.orient.core.sql.executor.FilterByClassStep$1.fetchNextItem(FilterByClassStep.java:50)
	at com.orientechnologies.orient.core.sql.executor.FilterByClassStep$1.hasNext(FilterByClassStep.java:82)
	at com.orientechnologies.orient.core.sql.executor.SubQueryStep$1.hasNext(SubQueryStep.java:40)
	at com.orientechnologies.orient.core.sql.executor.CastToVertexStep$1.hasNext(CastToVertexStep.java:26)
	at com.orientechnologies.orient.core.sql.executor.DeleteStep$1.hasNext(DeleteStep.java:26)
	at com.orientechnologies.orient.core.sql.executor.CountStep.syncPull(CountStep.java:50)
	at com.orientechnologies.orient.core.sql.executor.OSelectExecutionPlan.fetchNext(OSelectExecutionPlan.java:35)
	at com.orientechnologies.orient.core.sql.executor.OUpdateExecutionPlan.executeInternal(OUpdateExecutionPlan.java:41)
	at com.orientechnologies.orient.core.sql.parser.ODeleteVertexStatement.execute(ODeleteVertexStatement.java:46)
	at com.orientechnologies.orient.core.sql.parser.OStatement.execute(OStatement.java:85)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentEmbedded.command(ODatabaseDocumentEmbedded.java:642)
	at com.orientechnologies.orient.server.OConnectionBinaryExecutor.executeQuery(OConnectionBinaryExecutor.java:1338)
	at com.orientechnologies.orient.client.remote.message.OQueryRequest.execute(OQueryRequest.java:143)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.sessionRequest(ONetworkProtocolBinary.java:355)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.execute(ONetworkProtocolBinary.java:239)
	at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:68)
Wrapped by: com.orientechnologies.orient.core.exception.OStorageException: Error on executing command: delete vertex `GenericV` where uuid IN :UUIDs
	DB name="dbname"
	at com.orientechnologies.orient.client.remote.OStorageRemote.baseNetworkOperation(OStorageRemote.java:568)
	at com.orientechnologies.orient.client.remote.OStorageRemote.networkOperationRetryTimeout(OStorageRemote.java:420)
	at com.orientechnologies.orient.client.remote.OStorageRemote.networkOperationNoRetry(OStorageRemote.java:455)
	at com.orientechnologies.orient.client.remote.OStorageRemote.command(OStorageRemote.java:1204)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentRemote.command(ODatabaseDocumentRemote.java:408)
```

## Steps to reproduce  

The issue presents intermittently upon running ```delete vertex `GenericV` where uuid IN :UUIDs```

**Comment by tglman** [comment]
a commit was just pushed to cover this case, will be release next hotfix (3.2.13).

Regards

**Comment by michele-pinto-kensu** [comment]
Hi @tglman do you know already when this HF release will be released? Thanks

**Comment by tglman** [comment]
Hi,

The 3.2.13 has been shipped with the fix of this case, leaving this open for now to add additional test cases for cover the case.

Regards
