### ISSUE TITLE
Java API throws a NullPointerException from OResultInternal when trying to execute queries with edge traversals

### ISSUE THREAD

**Issue by cunrein** [orientechnologies/orientdb#9903]
## Expected behavior  
When using `ODatabaseDocument.query(query)` to execute the query below the Java APIs should not throw a `NullPointerException` from ` OResultInternal`
```
SELECT FROM OBJECT WHERE (NAME = 'Thing 1' OR (UUID IN (SELECT in('hasAttribute').UUID FROM ATTRIBUTE WHERE VALUE in ['TRUE', 'true', 'True'] and out('isDataDictionary').DATATYPE = 'VIEW' AND out('isDataDictionary').NAME = 'Some Group'))) and inCOI.COI_ID IN ['123456'] LIMIT 100000
```

## Actual behavior  
When executing the query above the following is thrown:
```
com.orientechnologies.orient.core.exception.OStorageException: Error on executing command: SELECT FROM OBJECT WHERE (NAME = 'Thing 1' OR (UUID IN (SELECT in('hasAttribute').UUID FROM ATTRIBUTE WHERE VALUE in ['TRUE', 'true', 'True'] and out('isDataDictionary').DATATYPE = 'VIEW' AND out('isDataDictionary').NAME = 'Some Group'))) and inCOI.COI_ID IN ['123456'] LIMIT 100000
DB name = trunk
at com.orientechnologies.orient.client.remote.OStorageRemote.baseNetworkOperation(OStorageRemote.java:564)
at com.orientechnologies.orient.client.remote.OStorageRemote.networkOperationRetryTimeout(OStorageRemote.java:415)
...
Caused by java.lang.NullPointerException: null
  at com.orientechnologies.orient.core.sql.executor.OResultInternal.hashCode(OResultInternal.java:479)
  at java.base/java.util.HashMap.hash(HashMap.java:340)
  at java.base/java.util.HashMap.containsKey(HashMap.java:592)
  at java.base/java.util.HashMap.contains(HashMap.java:204)
  at java.base/java.util.HashMap.containsKey(HashMap.java:592)
  at com.orientechnologies.orient.core.sql.executor.DistinctExecutionStep.alreadyVisited(DistinctExecutionStep.java:149)
  at com.orientechnologies.orient.core.sql.executor.DistinctExecutionStep.fetchNext(DistinctExecutionStep.java:105)
  at com.orientechnologies.orient.core.sql.executor.DistinctExecutionStep.access$100(DistinctExecutionStep.java:15)
  at com.orientechnologies.orient.core.sql.executor.DistinctExecutionStep.hasNext(DistinctExecutionStep.java:53)
  at com.orientechnologies.orient.core.sql.executor.FilterStep$1.fetchNextItem(FilterStep.java:54)
  at com.orientechnologies.orient.core.sql.executor.FilterStep$1.hasNext(FilterStep.java:87)
```
 but the same query executes just fine in the console. 

## Steps to reproduce  
This appears to be related to edge traversals like [issue 9894](https://github.com/orientechnologies/orientdb/issues/9894) 

Connect to a database and create a query similar to the one above. Then using a connected ODatabaseDocument execute the constructed query. If the constructed query is not traversing edges the query is successful. The query that is used must traverse at least one edge (more traversals are better the query above has four traversals).

**Comment by tglman** [comment]
Hi,

This looks like the same error of  #9900  that has been fixed in the last hotfix 3.2.13.

Closing this
