### ISSUE TITLE
REPAIR DATABASE throws error

### ISSUE THREAD

**Issue by npomaroli** [orientechnologies/orientdb#9916]
## Expected behavior  
The really expected behavior is that the database should not break - even if it is shutdown uncleanly (e.g. due to OOM or other issues).
And if the database already has an error, REPAIR DATABASE should be able to fix it in a way, that it is at least possible to read all (still present) data from it without getting Exceptions.

## Actual behavior  
We have a database, which throws (various) Exceptions when reading specific records.
When trying to repair it with the CLI "REPAIR DATABASE" command, we also get a (similar) Exception:

```
orientdb {db=storage}> check database

Checking storage.Check of storage is started...Check of storage completed in 2929ms.  without errors.
orientdb {db=storage}> repair database --fix-graph

2023-02-02 12:02:36:617 WARNI {db=storage} Unrecognized option database, skipped [OConsoleDatabaseApp]
2023-02-02 12:02:36:617 WARNI {db=storage} Unrecognized option --fix-graph, skipped [OConsoleDatabaseApp]Repair of graph 'plocal:C:\Users\apagtxpomaroli\orientdb-community-3.2.15\bin\..\..\workspace-mdm\mesh\server\data\graphdb/storage' is started ...
Scanning 162700 edges (skipEdges=0)...

2023-02-02 12:02:38:979 SEVER Exception `7051777C` in storage `plocal:C:\Users\apagtxpomaroli\orientdb-community-3.2.15\bin\..\..\workspace-mdm\mesh\server\data\graphdb/storage`: 3.2.15 (build 844ddc3063c05e9c8be796817e85c9b3e6542f5d, branch UNKNOWN) [OLocalPaginatedStorage]
java.nio.BufferUnderflowException
        at java.base/java.nio.DirectByteBuffer.get(DirectByteBuffer.java:294)
        at java.base/java.nio.ByteBuffer.get(ByteBuffer.java:770)
        at com.orientechnologies.orient.core.storage.impl.local.paginated.base.ODurablePage.getBinaryValue(ODurablePage.java:204)
        at com.orientechnologies.orient.core.storage.cluster.OClusterPage.getRecordBinaryValue(OClusterPage.java:659)
        at com.orientechnologies.orient.core.storage.cluster.v2.OPaginatedClusterV2.internalReadRecord(OPaginatedClusterV2.java:688)
        at com.orientechnologies.orient.core.storage.cluster.v2.OPaginatedClusterV2.readRecord(OPaginatedClusterV2.java:644)
        at com.orientechnologies.orient.core.storage.cluster.v2.OPaginatedClusterV2.readRecord(OPaginatedClusterV2.java:629)
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.doReadRecord(OAbstractPaginatedStorage.java:5145)
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.readRecord(OAbstractPaginatedStorage.java:4857)
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.readRecord(OAbstractPaginatedStorage.java:1919)
        at com.orientechnologies.orient.core.db.document.SimpleRecordReader.readRecord(SimpleRecordReader.java:24)
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentEmbedded.executeReadRecord(ODatabaseDocumentEmbedded.java:1345)
        at com.orientechnologies.orient.core.tx.OTransactionNoTx.loadRecord(OTransactionNoTx.java:123)
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentAbstract.load(ODatabaseDocumentAbstract.java:745)
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentAbstract.load(ODatabaseDocumentAbstract.java:80)
        at com.orientechnologies.orient.core.record.impl.ODocument.getProperty(ODocument.java:417)
        at com.orientechnologies.orient.core.record.impl.OEdgeDocument.getFrom(OEdgeDocument.java:29)
        at com.orientechnologies.orient.core.db.tool.OGraphRepair.repairEdges(OGraphRepair.java:173)
        at com.orientechnologies.orient.core.db.tool.OGraphRepair.repair(OGraphRepair.java:58)
        at com.orientechnologies.orient.console.OConsoleDatabaseApp.repairDatabase(OConsoleDatabaseApp.java:2436)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at com.orientechnologies.common.console.OConsoleApplication.execute(OConsoleApplication.java:456)
        at com.orientechnologies.common.console.OConsoleApplication.executeCommands(OConsoleApplication.java:283)
        at com.orientechnologies.common.console.OConsoleApplication.run(OConsoleApplication.java:144)
        at com.orientechnologies.orient.console.OConsoleDatabaseApp.main(OConsoleDatabaseApp.java:162)

Error: com.orientechnologies.orient.core.exception.ODatabaseException: Error on retrieving record #331:170147 (cluster: nodegraphfieldcontainerimpl_1)
        DB name="storage"

Error: java.nio.BufferUnderflowException
```

**Comment by tglman** [comment]
Hi,

This looks quite strange is a long while i do not see similar errors, it does look that some error created some persistent not valid state, it would be quite useful with which version this problem was created, I see you mention some quite updated release of 3.1.x and 3.2.x but as far as I understood this version are just used to run the repair, are not the version that created the persistent problem

The repair database it mainly correct graph connections so is not designed to correct this cases, anyway we could evolve it to handle this case as well.

Regards

**Comment by npomaroli** [comment]
The problem was created with Version 3.1.18, and yes, we tried to repair the database with versions 3.1.18, 3.1.20 and 3.2.15.

**Comment by tglman** [comment]
Ok, than the problem is on a recent version, do you have any trace on how you produced it in the first place ? was it a "kill crash" an "OOM", or any other similar failure ?  this could help as to identify the root cause of the problem.

to recover the database you can try to remove the "corrupted record" to do that you can use:  `truncate record #331:170147` as described here: https://orientechnologies.github.io/docs/3.2.x/sql/SQL-Truncate-Record.html?highlight=truncate%20re#sql---truncate-record

Anyway I cannot guarantee this will work, but is worth trying, as well make a backup of the database every time before do this kind of operations.

**Comment by npomaroli** [comment]
I tried to truncate the broken record, but this caused another exception:
```
orientdb {db=storage}> truncate record #331:170147
Exception `6DEE4F1B` in storage `plocal:C:\Users\apagtxpomaroli\orientdb-community-3.1.18\bin\..\..\workspace-mdm\mesh\server\data\graphdb/storage`: 3.1.18 - Veloce (build 3e291dfa02e5e732090230e7ade92e8745d556d8, branch UNKNOWN)
com.orientechnologies.orient.core.exception.OStorageException: Exception during execution of atomic operation inside of storage storage
        DB name="storage"
        at com.orientechnologies.orient.core.storage.impl.local.paginated.atomicoperations.OAtomicOperationsManager.calculateInsideAtomicOperation(OAtomicOperationsManager.java:144)
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.deleteRecord(OAbstractPaginatedStorage.java:2023)
        at com.orientechnologies.orient.core.sql.parser.OTruncateRecordStatement.executeSimple(OTruncateRecordStatement.java:47)
        at com.orientechnologies.orient.core.sql.executor.OSingleOpExecutionPlan.executeInternal(OSingleOpExecutionPlan.java:95)
        at com.orientechnologies.orient.core.sql.parser.OSimpleExecStatement.execute(OSimpleExecStatement.java:45)
        at com.orientechnologies.orient.core.sql.parser.OStatement.execute(OStatement.java:72)
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentEmbedded.command(ODatabaseDocumentEmbedded.java:647)
        at com.orientechnologies.orient.console.OConsoleDatabaseApp.sqlCommand(OConsoleDatabaseApp.java:3462)
        at com.orientechnologies.orient.console.OConsoleDatabaseApp.truncateRecord(OConsoleDatabaseApp.java:642)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.orientechnologies.common.console.OConsoleApplication.execute(OConsoleApplication.java:445)
        at com.orientechnologies.common.console.OConsoleApplication.executeCommands(OConsoleApplication.java:283)
        at com.orientechnologies.common.console.OConsoleApplication.run(OConsoleApplication.java:144)
        at com.orientechnologies.orient.console.OConsoleDatabaseApp.main(OConsoleDatabaseApp.java:159)
Caused by: java.lang.IndexOutOfBoundsException
        at java.nio.Buffer.checkIndex(Buffer.java:545)
        at java.nio.DirectByteBuffer.get(DirectByteBuffer.java:252)
        at com.orientechnologies.orient.core.storage.impl.local.paginated.base.ODurablePage.getByteValue(ODurablePage.java:251)
        at com.orientechnologies.orient.core.storage.cluster.OClusterPage.getRecordByteValue(OClusterPage.java:568)
        at com.orientechnologies.orient.core.storage.cluster.v2.OPaginatedClusterV2.getPhysicalPosition(OPaginatedClusterV2.java:1010)
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.doDeleteRecord(OAbstractPaginatedStorage.java:5390)
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.lambda$deleteRecord$8(OAbstractPaginatedStorage.java:2024)
        at com.orientechnologies.orient.core.storage.impl.local.paginated.atomicoperations.OAtomicOperationsManager.calculateInsideAtomicOperation(OAtomicOperationsManager.java:138)
        ... 16 more

Error: com.orientechnologies.orient.core.exception.OCommandExecutionException: Error on executing command
        DB name="storage"

Error: com.orientechnologies.orient.core.exception.OStorageException: Exception during execution of atomic operation inside of storage storage
        DB name="storage"

Error: java.lang.IndexOutOfBoundsException

orientdb {db=storage}> Exception `6992EB71` in storage `plocal:C:\Users\apagtxpomaroli\orientdb-community-3.1.18\bin\..\..\workspace-mdm\mesh\server\data\graphdb/storage`: 3.1.18 - Veloce (build 3e291dfa02e5e732090230e7ade92e8745d556d8, branch UNKNOWN)
com.orientechnologies.orient.core.exception.OStorageException: Internal error happened in storage storage please restart the server or re-open the storage to undergo the restore process and fix the error.
        DB name="storage"
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.checkErrorState(OAbstractPaginatedStorage.java:4806)
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.checkOpenness(OAbstractPaginatedStorage.java:4797)
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.getClusterIdByName(OAbstractPaginatedStorage.java:2071)
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentAbstract.getClusterIdByName(ODatabaseDocumentAbstract.java:805)
        at com.orientechnologies.orient.core.metadata.OMetadataDefault.init(OMetadataDefault.java:129)
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentEmbedded.loadMetadata(ODatabaseDocumentEmbedded.java:332)
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentEmbedded.init(ODatabaseDocumentEmbedded.java:210)
        at com.orientechnologies.orient.core.db.OrientDBEmbedded.openNoAuthorization(OrientDBEmbedded.java:458)
        at com.orientechnologies.orient.core.db.OrientDBEmbedded.lambda$executeNoAuthorization$9(OrientDBEmbedded.java:1094)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:750)
Caused by: com.orientechnologies.orient.core.exception.OStorageException: Exception during execution of atomic operation inside of storage storage
        DB name="storage"
        at com.orientechnologies.orient.core.storage.impl.local.paginated.atomicoperations.OAtomicOperationsManager.calculateInsideAtomicOperation(OAtomicOperationsManager.java:144)
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.deleteRecord(OAbstractPaginatedStorage.java:2023)
        at com.orientechnologies.orient.core.sql.parser.OTruncateRecordStatement.executeSimple(OTruncateRecordStatement.java:47)
        at com.orientechnologies.orient.core.sql.executor.OSingleOpExecutionPlan.executeInternal(OSingleOpExecutionPlan.java:95)
        at com.orientechnologies.orient.core.sql.parser.OSimpleExecStatement.execute(OSimpleExecStatement.java:45)
        at com.orientechnologies.orient.core.sql.parser.OStatement.execute(OStatement.java:72)
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentEmbedded.command(ODatabaseDocumentEmbedded.java:647)
        at com.orientechnologies.orient.console.OConsoleDatabaseApp.sqlCommand(OConsoleDatabaseApp.java:3462)
        at com.orientechnologies.orient.console.OConsoleDatabaseApp.truncateRecord(OConsoleDatabaseApp.java:642)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.orientechnologies.common.console.OConsoleApplication.execute(OConsoleApplication.java:445)
        at com.orientechnologies.common.console.OConsoleApplication.executeCommands(OConsoleApplication.java:283)
        at com.orientechnologies.common.console.OConsoleApplication.run(OConsoleApplication.java:144)
        at com.orientechnologies.orient.console.OConsoleDatabaseApp.main(OConsoleDatabaseApp.java:159)
Caused by: java.lang.IndexOutOfBoundsException
        at java.nio.Buffer.checkIndex(Buffer.java:545)
        at java.nio.DirectByteBuffer.get(DirectByteBuffer.java:252)
        at com.orientechnologies.orient.core.storage.impl.local.paginated.base.ODurablePage.getByteValue(ODurablePage.java:251)
        at com.orientechnologies.orient.core.storage.cluster.OClusterPage.getRecordByteValue(OClusterPage.java:568)
        at com.orientechnologies.orient.core.storage.cluster.v2.OPaginatedClusterV2.getPhysicalPosition(OPaginatedClusterV2.java:1010)
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.doDeleteRecord(OAbstractPaginatedStorage.java:5390)
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.lambda$deleteRecord$8(OAbstractPaginatedStorage.java:2024)
        at com.orientechnologies.orient.core.storage.impl.local.paginated.atomicoperations.OAtomicOperationsManager.calculateInsideAtomicOperation(OAtomicOperationsManager.java:138)
        ... 16 more
```

As for the reason of the broken database: Regrettably we cannot say for sure, but it is most likely that it was either an OOM or the process was killed or maybe a combination of both.
OrientDB is running in cluster mode (3 masters, 1 replica) in OpenShift. We have definitely seen problems with heap memory consumption, it is lpossible that they caused excessive garbage collections, which lead to the instance becoming unresponsive. OpenShift will then try to terminate the unhealthy pod - first by sending SIGTERM, but if the pod fails to terminate within a certain timeout, it will most probably kill it forcefully.
