### ISSUE TITLE
Database import leads to OSecurityAccessException

### ISSUE THREAD

**Issue by jacquipre** [orientechnologies/orientdb#9922]
## Expected behavior  
It is possible to import a database without an error.  

## Actual behavior  
We have a scenario where we import a database (which was formerly exported in an older OrientDB version). 
This was working fine until OrientDB version 3.2.15 but with 3.2.16 we are now getting the following error:
```
Caused by: com.orientechnologies.orient.core.exception.OSecurityAccessException: User 'admin' does not have 
permission to execute the operation 'Update' against the resource: 
ResourceGeneric [name=CLASS, legacyName=database.class].ORole
	DB name="database"
	at com.orientechnologies.orient.core.metadata.security.OImmutableUser.allow(OImmutableUser.java:81) ~[orientdb-core-3.2.16.jar:3.2.16]
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentEmbedded.checkSecurity(ODatabaseDocumentEmbedded.java:1478) ~[orientdb-core-3.2.16.jar:3.2.16]
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentEmbedded.checkSecurity(ODatabaseDocumentEmbedded.java:1518) ~[orientdb-core-3.2.16.jar:3.2.16]
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentAbstract.saveInternal(ODatabaseDocumentAbstract.java:1478) ~[orientdb-core-3.2.16.jar:3.2.16]
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentAbstract.save(ODatabaseDocumentAbstract.java:1434) ~[orientdb-core-3.2.16.jar:3.2.16]
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentAbstract.save(ODatabaseDocumentAbstract.java:80) ~[orientdb-core-3.2.16.jar:3.2.16]
	at com.orientechnologies.orient.core.record.impl.ODocument.save(ODocument.java:2423) ~[orientdb-core-3.2.16.jar:3.2.16]
	at com.orientechnologies.orient.core.record.impl.ODocument.save(ODocument.java:2417) ~[orientdb-core-3.2.16.jar:3.2.16]
	at com.orientechnologies.orient.core.metadata.security.ORole.save(ORole.java:381) ~[orientdb-core-3.2.16.jar:3.2.16]
	at com.orientechnologies.orient.core.metadata.security.OSecurityShared.setDefaultAdminPermissions(OSecurityShared.java:839) ~[orientdb-core-3.2.16.jar:3.2.16]
	at com.orientechnologies.orient.core.metadata.security.OSecurityShared.setupPredicateSecurity(OSecurityShared.java:1063) ~[orientdb-core-3.2.16.jar:3.2.16]
	at com.orientechnologies.orient.core.metadata.security.OSecurityShared.load(OSecurityShared.java:1052) ~[orientdb-core-3.2.16.jar:3.2.16]
	at com.orientechnologies.orient.core.db.OSharedContextEmbedded.reload(OSharedContextEmbedded.java:137) ~[orientdb-core-3.2.16.jar:3.2.16]
	at com.orientechnologies.orient.core.metadata.OMetadataDefault.reload(OMetadataDefault.java:136) ~[orientdb-core-3.2.16.jar:3.2.16]
	at com.orientechnologies.orient.core.db.tool.ODatabaseImport.importRecords(ODatabaseImport.java:1450) ~[orientdb-core-3.2.16.jar:3.2.16]
	at com.orientechnologies.orient.core.db.tool.ODatabaseImport.importDatabase(ODatabaseImport.java:227) ~[orientdb-core-3.2.16.jar:3.2.16]
```  
Looking into the diff between these two OrientDB version, we can see that this change in [ODatabaseImport](https://github.com/orientechnologies/orientdb/commit/f8424ce73695ae09e3fe4edd276654b11d2eb853#diff-8445d67b2da9170d9faa0ac38cd1cb46fd6bfc4de78f5c4ee7c2f7778431a451L168) leads to the error since the `OIntentMassiveInsert.begin()` and `OIntentMassiveInsert.end()` is not called anymore.
These methods disabled the security check by setting the current database owner to `null` while importing.

Why was this change made? 
What can we do to make it work again? 
Is there something wrong with our solution?

## Steps to reproduce  
Get an exported database json from any OrientDB version (we used one from OrientDB 2.2.37).
Import that database into a running server. 
We used this code:
```
try (ODatabaseDocumentInternal db = // acquire a database from the database pool )) {
 // Make sure the database is empty before performing the import
 db.drop();
 db.create();
    try (InputStream in = // database file as InputStream) {
        ODatabaseImport dataImport = new ODatabaseImport(db, in, LOGGER::debug);
        dataImport.importDatabase(); // <-- error
        dataImport.close();
    }
}
// ...
```

**Comment by tglman** [comment]
Hi,

This looks a bit strange, what user did you use for do the import of the database ? a user with role "admin" is required, in recent version has been removed some logic that disabled security checks during the import, that looks the cause of this problem.

Regards

**Comment by jacquipre** [comment]
We are using the "admin" user.

**Comment by tglman** [comment]
Hi,

I changed the last develop to check the permission at the start of the import and than disable security checks for the rest of the execution that actually are not needed to be checked, there is a snapshot available here: https://oss.sonatype.org/content/repositories/snapshots/com/orientechnologies/orientdb-community/3.2.17-SNAPSHOT/orientdb-community-3.2.17-20230220.154254-4.tar.gz that should not have the problem, it would be cool if you could verify it.

Regards

**Comment by jacquipre** [comment]
Hi,
with this Snapshot version the database import is working as expected, without the security exception 👍 

Thanks and regards, jacquipre.

**Comment by tglman** [comment]
Hi, 

the 3.2.17 has been released.

Closing
