### ISSUE TITLE
File with name osecuritypolicy.pcl does not exist in storage

### ISSUE THREAD

**Issue by npomaroli** [orientechnologies/orientdb#9949]
### OS: alpine (running in OpenShift) 

We are running OrientDB in a cluster (3 master nodes, 1 replica) in OpenShift. In cases, where one of the storages gets corrupt, we normally stop the instance and copy over the database files from another (also stopped) instance. After starting both instances, they usually form a cluster and we end up with a cluster, which appears to be "in sync".

## Expected behavior  
Recreating a cluster instance by copying the database files from another instance of the same cluster should work.

## Actual behavior  
When starting the instance with the copy of the database files, OrientDB fails to start with an error like this:
```
Caused by: com.orientechnologies.orient.core.exception.OStorageException: File with name osecuritypolicy.pcl does not exist in storage
```

Indeed, the database does not contain a file with that exact name, but it contains files with the following names:
```
osecuritypolicy_1548021505.cpm
osecuritypolicy_1554621669.fsm
osecuritypolicy_1718266823.pcl
osecuritypolicy_1_1922803403.pcl
osecuritypolicy_1_247095690.cpm
osecuritypolicy_1_533679527.fsm
osecuritypolicy_2_1808066301.fsm
osecuritypolicy_2_1977395499.pcl
osecuritypolicy_2_702947540.cpm
```

Why is OrientDB expecting the file with name osecuritypolicy.pcl?
Is there anything, we can do to allow copying the database files from one instance to another without problems to start OrientDB afterwards?

**Comment by tglman** [comment]
Hi,

In the specific of the file names, this are just the "data files" of an OrientDB default schema class called OSecurityPolicy, that it does exists by default in all the 3.2.x series.

The copy of the files manually even if not suggested should work pretty fine if done on both node off, in this case seems that maybe some file was not copied correctly or some base files containing the mapping was not copied over or overwritten by a older version, so make sure to copy over all the file in the database folder.

Regards

**Comment by npomaroli** [comment]
Hi,

thanks for the answer.
The copying was done by one of our customers (in order to "fix" a broken database on one instance). I am pretty sure that it was done with both OrientDB instances stopped, and I am also pretty sure that all of the files from the db directory were copied.

Our customer tried this multiple times on different systems, and - with one exception - got the exact same error message on all systems. The only system, where starting the instance with the copy worked fine had a much smaller database, so it seems that the db size somehow matters.

You mentioned 'some base files containing the mapping', can you please be more specific about which file that would be?

Maybe interesting: The error happens when the OrientDB instance tries to connect to an already running cluster:

```
2023-03-30 09:40:08:139 SEVER [gentics-mesh-2] Error on installing database 'storage' on local node (error=com.orientechnologies.orient.core.exception.ODatabaseException: Cannot open database 'storage') [OHazelcastPlugin]
com.orientechnologies.orient.core.exception.ODatabaseException: Cannot open database 'storage'
	at com.orientechnologies.orient.core.db.OrientDBEmbedded.openNoAuthorization(OrientDBEmbedded.java:478)
	at com.orientechnologies.orient.core.db.OrientDBEmbedded.openNoAuthorization(OrientDBEmbedded.java:86)
	at com.orientechnologies.orient.server.distributed.impl.ODistributedDatabaseImpl.getDatabaseInstance(ODistributedDatabaseImpl.java:608)
	at com.orientechnologies.orient.server.distributed.impl.ODistributedPlugin.requestNewDatabaseDelta(ODistributedPlugin.java:1452)
	at com.orientechnologies.orient.server.distributed.impl.ODistributedPlugin.access$200(ODistributedPlugin.java:152)
	at com.orientechnologies.orient.server.distributed.impl.ODistributedPlugin$5.call(ODistributedPlugin.java:1365)
	at com.orientechnologies.orient.server.distributed.impl.ODistributedPlugin$5.call(ODistributedPlugin.java:1290)
	at com.orientechnologies.orient.server.hazelcast.OHazelcastClusterMetadataManager.executeInDistributedDatabaseLock(OHazelcastClusterMetadataManager.java:1538)
	at com.orientechnologies.orient.server.distributed.impl.ODistributedPlugin.executeInDistributedDatabaseLock(ODistributedPlugin.java:274)
	at com.orientechnologies.orient.server.distributed.impl.ODistributedPlugin.installDatabase(ODistributedPlugin.java:1286)
	at com.orientechnologies.orient.server.distributed.impl.ODistributedPlugin.installNewDatabasesFromCluster(ODistributedPlugin.java:2771)
	at com.orientechnologies.orient.server.hazelcast.OHazelcastClusterMetadataManager.lambda$startupHazelcastPlugin$0(OHazelcastClusterMetadataManager.java:222)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: com.orientechnologies.orient.core.exception.OStorageException: Exception during execution of atomic operation inside of storage storage
	at com.orientechnologies.orient.core.storage.impl.local.paginated.atomicoperations.OAtomicOperationsManager.executeInsideAtomicOperation(OAtomicOperationsManager.java:146)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.open(OAbstractPaginatedStorage.java:437)
	at com.orientechnologies.orient.core.db.OrientDBEmbedded.getAndOpenStorage(OrientDBEmbedded.java:542)
	at com.orientechnologies.orient.core.db.OrientDBEmbedded.openNoAuthorization(OrientDBEmbedded.java:469)
	... 12 more
Caused by: com.orientechnologies.orient.core.exception.OStorageException: Exception during execution of component operation inside component osecuritypolicy.pcl in storage storage
	at com.orientechnologies.orient.core.storage.impl.local.paginated.atomicoperations.OAtomicOperationsManager.executeInsideComponentOperation(OAtomicOperationsManager.java:172)
	at com.orientechnologies.orient.core.storage.impl.local.paginated.atomicoperations.OAtomicOperationsManager.executeInsideComponentOperation(OAtomicOperationsManager.java:157)
	at com.orientechnologies.orient.core.storage.impl.local.paginated.base.ODurableComponent.executeInsideComponentOperation(ODurableComponent.java:102)
	at com.orientechnologies.orient.core.storage.cluster.v2.OPaginatedClusterV2.open(OPaginatedClusterV2.java:196)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.openClusters(OAbstractPaginatedStorage.java:656)
	at com.orientechnologies.orient.core.storage.impl.local.paginated.atomicoperations.OAtomicOperationsManager.executeInsideAtomicOperation(OAtomicOperationsManager.java:140)
	... 15 more
Caused by: com.orientechnologies.orient.core.exception.OStorageException: File with name osecuritypolicy.pcl does not exist in storage storage
	at com.orientechnologies.orient.core.storage.cache.local.OWOWCache.loadFile(OWOWCache.java:653)
	at com.orientechnologies.orient.core.storage.impl.local.paginated.atomicoperations.OAtomicOperationBinaryTracking.loadFile(OAtomicOperationBinaryTracking.java:354)
	at com.orientechnologies.orient.core.storage.impl.local.paginated.base.ODurableComponent.openFile(ODurableComponent.java:196)
	at com.orientechnologies.orient.core.storage.cluster.v2.OPaginatedClusterV2.lambda$open$1(OPaginatedClusterV2.java:201)
	at com.orientechnologies.orient.core.storage.impl.local.paginated.atomicoperations.OAtomicOperationsManager.executeInsideComponentOperation(OAtomicOperationsManager.java:165)
	... 20 more
```

What I find most strange: OrientDB is expecting the file 'osecuritypolicy.pcl' to exist, but in the whole database, there is not a single *.pcl file, which has a name with that pattern ([name].pcl). All existing .pcl files have names like [name]\_[digits].pcl or [name]\_[digit]\_[digits].pcl (see the files I mentioned in the description).

**Comment by tglman** [comment]
Hi,

there is a file named `name_id_map_v3.cm` in this the database that keep the mapping from the `[name].pcl` to `[name]_[digits].pcl`  if the database is older the file name may be : `name_id_map_v2.cm` or `name_id_map.cm`.

this is a bit strange anyway, the `OSecurityPolicy` is often created at the start of the database, and if you are not using the security policy should never be changed anyway, it may be a bit different if the database is older than 3.1, than maybe the security policy files are created after for a `migration at first open` with a newer OrientDB version.

**Comment by npomaroli** [comment]
Hi @tglman,
thanks for support in this case, but it now turned out that (due to some strange behaviour when using "oc cp" in OpenShift) not the whole database was copied from one instance to the other.

With this, I am closing this issue now.
